### PR TITLE
Use yaml_io sugar for reading and writing serialized files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #15868.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@damrongguoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049#-:-MnkdenkDemJSyTJ5WPJ:b-4tfozp)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049)* status: 2 unresolved discussions, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16049#-Mnl4OBME8QIIFdWOFwa:-Mnl4OBME8QIIFdWOFwb:bka5n95) (no related file):*
Is it true that all non-sugar usages are gone? A simple grep seems to suggest so.

---
___
*[systems/analysis/test/simulator_gflags_main.cc, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16049#-Mnl45BG2qcKv5Gh0zBL:-Mnl45BG2qcKv5Gh0zBM:b9ivud0) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4b8ddce613f164d6ae6c03954f5c5c11cdd852/systems/analysis/test/simulator_gflags_main.cc#L2)):*
> ```cpp
> #include <gflags/gflags.h>
> #include <yaml-cpp/yaml.h>
> ```

nit, not needed anymore?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16049#-Mnl4OBME8QIIFdWOFwa:-MnlC1hTD-QZKxXlfkxS:b-n119dz) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is it true that all non-sugar usages are gone? A simple grep seems to suggest so.
</blockquote></details>

Other than #16050, yes, that's the goal.

---

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: pending minor questions.

> Reviewed 15 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049#-:-MnlZZCeCqvwkWWxGKuz:b4rqc9w)* status: 10 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlEQHU0xqq1Ff9ioZP:-MnlEQHU0xqq1Ff9ioZQ:b-8io4x4) (no related file):*
I'm glad to see removal of `#include "yaml-cpp/yaml.h"` in this PR.

I still see `#include "yaml-cpp/yaml.h"` in `yaml_write_archive.cc` and `yaml_read_archive.h` and confirm that it's not oversight.

---
___
*[common/yaml/yaml_io.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16049#-Mnl9ixN4BNy1K7jQdT-:-Mnl9ixN4BNy1K7jQdT0:b-yad1pj) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4b8ddce613f164d6ae6c03954f5c5c11cdd852/common/yaml/yaml_io.cc#L14)):*
> ```cpp
>   if (out.fail()) {
>     throw std::runtime_error(fmt::format(
>         "SaveYamlFile() could not open '{}' for writing",
> ```

This might be a philosophical question. The error message is thrown in `WriteFile()`, and the message itself says `SaveYamlFile() could not...`, which indeed calls `WriteFile()`.  My concern is that other functions could call `WriteFile()` too, and the error message could cause confusion.

If we can be sure that only SaveYamlFile() could call WriteFile(), then we are ok.

Since this is already a practice before this PR, I won't take it as a defect; just discussion.  It's fine to keep it as is.
___
*[common/yaml/yaml_io.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlCB0wB24v0A6nS8sO:-MnlCB0xDNPPIK-DCvSA:bs4q9op) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4b8ddce613f164d6ae6c03954f5c5c11cdd852/common/yaml/yaml_io.cc#L20)):*
> ```cpp
>   if (out.fail()) {
>     throw std::runtime_error(fmt::format(
>         "SaveYamlFile() could not write to '{}'",
> ```

Ditto.
___
*[examples/acrobot/BUILD.bazel, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlFwfe1YFo5tB6kThW:-MnlFwff1BCXaB2ILvS3:b-yx3az) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/BUILD.bazel#L155)):*
> ```Starlark
>         "//common:name_value",
>         "//common/schema:stochastic",
>         "//common/yaml",
> ```

Would `"//common/yaml:yaml_io",` work too?

As a user, I cannot differentiate `yaml:yaml_io` from `yaml`.

Well, `//common/yaml` is shorter than `//common/yaml:yaml_io`, so that might be a good reason to keep it as is.
___
*[examples/acrobot/spong_sim.cc, line 84 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlI8o-D1vEL6KWCY1f:-MnlI8o-D1vEL6KWCY1g:b-o7osgl) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/spong_sim.cc#L84)):*
> ```cpp
>   const Scenario scenario = SampleScenario(stochastic_scenario);
>   if (!FLAGS_dump_scenario.empty()) {
>     SaveYamlFile(FLAGS_dump_scenario, scenario);
> ```

Now it's only one line, which is much easier to read!
___
*[examples/acrobot/spong_sim.cc, line 131 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlIoW08Ki65clY273h:-MnlIoW08Ki65clY273i:b-royyo8) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/spong_sim.cc#L131)):*
> ```cpp
>     return 1;
>   }
>   const Scenario stochastic_scenario = LoadYamlFile<Scenario>(FLAGS_scenario);
> ```

nit: `const auto` ?  The `Scenario` is in `LoadYamlFile<Scenario>` already.
___
*[multibody/parsing/model_directives.h, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlYD192muRL_llqwyS:-MnlYD192muRL_llqwyT:bidfdjc) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/multibody/parsing/model_directives.h#L7)):*
> ```objc
> ///
> /// For more information on how structures are converted to and from YAML,
> /// refer to @ref yaml_serialization "YAML Serialization".
> ```

The Doxygen looks good.  I did:
```
bazel run //doc/doxygen_cxx:build -- --serve --quick drake.{common,multibody}
```


and the link to `YAML Serialization` looks reasonable.


___
*[multibody/parsing/process_model_directives.cc, line 265 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlMmnxCIu1aY4NN6r0:-MnlMmnxCIu1aY4NN6r1:b142zl5) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/multibody/parsing/process_model_directives.cc#L265)):*
> ```cpp
>   }
> 
>   const ModelDirectives defaults;
> ```

I  peek at `model_directives.h` and think the `defaults` would contain an empty `std::vector` (defaults.empty()==true), right?
___
*[systems/analysis/test/simulator_config_functions_test.cc, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlOQaX6NBwIowbWSX2:-MnlOQaX6NBwIowbWSX3:b-lx50r7) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/systems/analysis/test/simulator_config_functions_test.cc#L92)):*
> ```cpp
> 
>   // Ensure that the string and the struct have the same fields.
>   const SimulatorConfig bespoke = LoadYamlString<SimulatorConfig>(
> ```

nit: `const auto` ?
___
*[tools/vector_gen/test/sample_test.cc, line 221 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlQYwX5r4FSgzftZ2B:-MnlQYwX5r4FSgzftZ2C:b-yipyck) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/tools/vector_gen/test/sample_test.cc#L221)):*
> ```cpp
> unset: 99e9
> )""";
>   const auto dut = drake::yaml::LoadYamlString<Sample<double>>(yaml_text);
> ```

If we want to keep `values:` in 
```
values:
  x: 0
  two_word: -1
  absone: 0.25
  unset: 99e9
```
Could we exercise the `child_name` option like this?
```C++
const auto dut = drake::yaml::LoadYamlString<Sample<double>>(
    yaml_text, "values" /*child_name*/);
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlEQHU0xqq1Ff9ioZP:-MnlcHnaBWJ6ydOuIPIu:blahkk7) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm glad to see removal of `#include "yaml-cpp/yaml.h"` in this PR.

I still see `#include "yaml-cpp/yaml.h"` in `yaml_write_archive.cc` and `yaml_read_archive.h` and confirm that it's not oversight.
</blockquote></details>

Yes, this is as-intended.  We don't want users to touch it, but we ourselves _do_ still need to use it internally.  The eventual resolution of #15868 will move the yaml_read_archive use from .h to .cc, but that requires a deprecation first (in the next PR).

---
___
*[common/yaml/yaml_io.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16049#-Mnl9ixN4BNy1K7jQdT-:-Mnldw7p5E8rPoJjrZX1:bqah91s) ([raw file](https://github.com/robotlocomotion/drake/blob/6a4b8ddce613f164d6ae6c03954f5c5c11cdd852/common/yaml/yaml_io.cc#L14)):*
> If we can be sure that only SaveYamlFile() could call WriteFile(), then we are ok.

If some new drake-internal code starts calling this and fails to adjust the message string to match, then that's their problem.
___
*[examples/acrobot/BUILD.bazel, line 155 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlFwfe1YFo5tB6kThW:-MnlcdAq1BfPIZZhBBpe:bdeagnw) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/BUILD.bazel#L155)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Would `"//common/yaml:yaml_io",` work too?

As a user, I cannot differentiate `yaml:yaml_io` from `yaml`.

Well, `//common/yaml` is shorter than `//common/yaml:yaml_io`, so that might be a good reason to keep it as is.
</blockquote></details>

Saying `"//common/yaml"` means "give me everything from that module, even if that's somewhat more than I strictly need".  Spelling out `"//common/yaml:yaml_io"` is more specific about what I need, but requires more babysitting over time as the exact dependencies and spelling change.

It's a matter of judgement whether the babysitting is worth the extra developer time.  For something like yaml stuff, I think it's not worthwhile.

For `"//systems/analysis:simulator"` (just the simulator) vs `"//systems/analysis"` (which drags in the entire dependency world of mathematical programs and every single solver library), the extra dependency precision _is_ worth it.  (This is a signal that the analysis folder should be split up, by the way.)
___
*[examples/acrobot/spong_sim.cc, line 131 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlIoW08Ki65clY273h:-Mnlf-SJ6rIsUD9yuPSv:b-4ti0c5) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/spong_sim.cc#L131)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit: `const auto` ?  The `Scenario` is in `LoadYamlFile<Scenario>` already.
</blockquote></details>

Because this file is a tutorial, I am erring on the side of being more explicit to help our more naive readers.  (In our unit tests that are targeted more towards drake developers, I've been satisfied to use `auto`.)
___
*[multibody/parsing/process_model_directives.cc, line 265 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlMmnxCIu1aY4NN6r0:-MnldfTr5ZJSpLxYp5QR:b-iixxv3) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/multibody/parsing/process_model_directives.cc#L265)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I  peek at `model_directives.h` and think the `defaults` would contain an empty `std::vector` (defaults.empty()==true), right?
</blockquote></details>

Yes, that's correct.  I added more comments in case the rationale was unclear.
___
*[systems/analysis/test/simulator_config_functions_test.cc, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlOQaX6NBwIowbWSX2:-Mnlei4QBNU9MY3norXx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/systems/analysis/test/simulator_config_functions_test.cc#L92)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit: `const auto` ?
</blockquote></details>

Done.
___
*[tools/vector_gen/test/sample_test.cc, line 221 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlQYwX5r4FSgzftZ2B:-MnldlPoAVdZx6hfujF1:b1rafjh) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/tools/vector_gen/test/sample_test.cc#L221)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

If we want to keep `values:` in 
```
values:
  x: 0
  two_word: -1
  absone: 0.25
  unset: 99e9
```
Could we exercise the `child_name` option like this?
```C++
const auto dut = drake::yaml::LoadYamlString<Sample<double>>(
    yaml_text, "values" /*child_name*/);
```
</blockquote></details>

Yes, that would be possible.  My judgement was that using a child_name in this demo was more confusing than helpful.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule (on Monday), please.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlEQHU0xqq1Ff9ioZP:-MnlraCQ52NmjAI9GIcM:b-h6uexc) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, this is as-intended.  We don't want users to touch it, but we ourselves _do_ still need to use it internally.  The eventual resolution of #15868 will move the yaml_read_archive use from .h to .cc, but that requires a deprecation first (in the next PR).
</blockquote></details>

I see.  Thanks for the clarification.

---
___
*[examples/acrobot/spong_sim.cc, line 131 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16049#-MnlIoW08Ki65clY273h:-Mnls40r43lAl-SRyt2C:bazyeb) ([raw file](https://github.com/robotlocomotion/drake/blob/4d7130e67359a03449df986bb37a76d441f607b7/examples/acrobot/spong_sim.cc#L131)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because this file is a tutorial, I am erring on the side of being more explicit to help our more naive readers.  (In our unit tests that are targeted more towards drake developers, I've been satisfied to use `auto`.)
</blockquote></details>

I see.  I agree to be more explicit in the example code for general users.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  This is much simpler and clearer; a real improvement.

> Reviewed 13 of 16 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16049#-:-Mo-1gTi5TbQJM01FzA4:b-enplql)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),DamrongGuoy (waiting on @jwnimmer-tri)

**Pull request merged**
