### PR TITLE
[primitives] Add SharedPointerSystem

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.  Note that `r_base..r2` is the copy from Anzu and `r2..r3` are the edits for Drake.

+@sherm1 for platform review per schedule, please.

(Commits are properly curated.)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260#-:-N2vtDnX1hiM-a769NA3:bnfp4nl)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2vt2xYELHNYuDNQPWF:-N2vt2xZ55hnpIYBUspX:b-3z290t) (no related file):*
BTW, will this get python bindings later?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2vt2xYELHNYuDNQPWF:-N2vtlYO75tyuOD2KZf8:bbmbwy4) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, will this get python bindings later?
</blockquote></details>

#17264

___

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few comments

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260#-:-N2xJIU4-4vEbyV3hTIJ:b-tv2fmf)* status: 6 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`systems/primitives/shared_pointer_system.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xFrDW8CZvQkbJ0Rvr:-N2xFrDW8CZvQkbJ0Rvs:bdxwoch) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L22)):*
> ```objc
> Scalar conversion is supported and will simply increment the reference count
> for the contained object. Advanced users who need to disable conversion may
> access the get_system_scalar_converter() to do so. Note that the contained
> ```

minor: I don't understand this sentence -- can you clarify? Why would anyone want to disable conversion? And even if they did, how does accessing the SystemScalarConverter achieve that end?
___
*[`systems/primitives/shared_pointer_system.h` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xH2hB4r2P0qRDWVRZ:-N2xH2hB4r2P0qRDWVR_:b-bfe3zv) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L36)):*
> ```objc
>     Calls to get<>() must provide the same type for retrieval. */
>   template <typename Held>
>   explicit SharedPointerSystem(std::shared_ptr<Held> value_to_hold)
> ```

minor: I assume the intent is that this would be called with `std::move(shptr)` so that the reference count won't increase. But a caller could easily forget that in which case the reference count would be 2 on entry and it wouldn't really be this System holding onto the object. In particular the object wouldn't get destructed on System destruction as claimed in the class doc.

Consider making this signature require an rvalue to force a move. (Also for AddToBuilder)



_Code snippet:_
```objc
SharedPointerSystem(std::shared_ptr<Held>&& value_to_hold)
```
___
*[`systems/primitives/shared_pointer_system.h` line 57 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xCKA_7Yfk4-nPUcQD:-N2xCKA_7Yfk4-nPUcQE:b-3r4uuh) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L57)):*
> ```objc
> 
>   /** Creates a system holding the given value and adds it to the builder.
>   The value is allowed to be `nullptr`. Returns an alias to the value.
> ```

BTW consider clarifying that either an alias or nullptr is returned.
___
*[`systems/primitives/shared_pointer_system.h` line 88 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xDDQ_6p-Lct5DJ0jR:-N2xDDQ_6p-Lct5DJ0jS:b-6kyakr) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L88)):*
> ```objc
>   }
> 
>   /** (Advanced) Retrieves an alias to the stored value.
> ```

BTW not clear to me why this is marked (Advanced). Isn't this the nuts-and-bolts access method?
___
*[`systems/primitives/test/shared_pointer_system_test.cc` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xIJUEDvPqtuVVQYkZ:-N2xIJUEDvPqtuVVQYk_:bd0qg3a) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/test/shared_pointer_system_test.cc#L22)):*
> ```cpp
> GTEST_TEST(SharedPointerSystemTest, CtorFromShared) {
>   auto held = std::make_shared<std::string>("held");
>   auto dut = std::make_unique<SharedPointerSystem<double>>(std::move(held));
> ```

BTW per comment above I believe the std::move is optional here but probably shouldn't be.
___
*[`systems/primitives/test/shared_pointer_system_test.cc` line 65 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xJAUzDtwBWu2SvA_l:-N2xJAUzDtwBWu2SvA_m:b-1fj5gl) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/test/shared_pointer_system_test.cc#L65)):*
> ```cpp
>   EXPECT_THROW(dut->get<std::string_view>(), std::bad_cast);
> }
> ```

minor: needs a unit test verifying proper behavior for nullptr input

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: 2 unresolved discussions (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/primitives/shared_pointer_system.h` line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xFrDW8CZvQkbJ0Rvr:-N2yZKFE4qZ7c1bTdbFW:b-17ihhj) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L22)):*
> Why would anyone want to disable conversion?

You could imagine that if someone wanted to start from a unique_ptr, they might want to disable any ability of this system to increment the reference count -- so that when this object is destroyed, the held object is definitively released.

> And even if they did, how does accessing the SystemScalarConverter achieve that end?

Oops.  I failed to realize that `get_mutable_system_scalar_converter` is protected, so the users can't actually access it.  (If they could access it, they could call `Remove` to disable things.)  In any case, we can probably want to build in this feature until someone really needs unique ownership.  So far, I'll bet that nobody does, so I've nixed this comment.
___
*[`systems/primitives/shared_pointer_system.h` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xH2hB4r2P0qRDWVRZ:-N2y_B6-A3wrTgvyZgug:b-pltyb2) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L36)):*
> ... in which case the reference count would be 2 on entry and it wouldn't really be this System holding onto the object.

This is true only if the caller preserves their own shared_ptr indefinitely; in most cases, it would go out of scope anyway, even if not moved-from.

> In particular the object wouldn't get destructed on System destruction as claimed in the class doc.

The doc says the pointer is released, not that the object is destroyed.

My intention here is not to forbid callers from keeping their own copy (reference count) if they wanted to do so.  Should I try to make that more clear somehow in the docs?
___
*[`systems/primitives/shared_pointer_system.h` line 88 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xDDQ_6p-Lct5DJ0jR:-N2yX8MX2gvBoo98dEbk:bqlw1fs) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L88)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW not clear to me why this is marked (Advanced). Isn't this the nuts-and-bolts access method?
</blockquote></details>

This is "Advanced" because figuring out the correct `<Held>` to pass in not entirely obvious, in case you are far removed from the place of construction (e.g., the template argument doesn't obey subtyping; it has to be exact).

The primary use case for this system is ownership, not access.  All users we have so far keep their own raw aliases baked in elsewhere.

(One might wonder why they can't all just use shared_ptr directly themselves and be done with it, but unfortunately that's not how they got written.)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: 2 unresolved discussions (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`systems/primitives/shared_pointer_system.h` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xH2hB4r2P0qRDWVRZ:-N3-z49xClcjkYzaRTYy:b4dg53w) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... in which case the reference count would be 2 on entry and it wouldn't really be this System holding onto the object.

This is true only if the caller preserves their own shared_ptr indefinitely; in most cases, it would go out of scope anyway, even if not moved-from.

> In particular the object wouldn't get destructed on System destruction as claimed in the class doc.

The doc says the pointer is released, not that the object is destroyed.

My intention here is not to forbid callers from keeping their own copy (reference count) if they wanted to do so.  Should I try to make that more clear somehow in the docs?
</blockquote></details>

Yes I think it is worth mentioning in the constructor doc that if the user intends the SharedPointerSystem to be the object owner then they should be sure to std::move the pointer in.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform), base commit is latest master (waiting on @rpoyner-tri and @sherm1)

___
*[`systems/primitives/shared_pointer_system.h` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17260#-N2xH2hB4r2P0qRDWVRZ:-N304EMZ3UJ5rkLITynt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/be7548ce1fff8d0d79ac2998595a4fd2c4cb4215/systems/primitives/shared_pointer_system.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Yes I think it is worth mentioning in the constructor doc that if the user intends the SharedPointerSystem to be the object owner then they should be sure to std::move the pointer in.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17260)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Pull request merged**
