### PR TITLE
[pydrake] Begin adding typed (i.e., schema-based) YAML loading

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18566 (and therefore #17112).

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18564)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18564)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
This is ready for feature review, either @SeanCurtis-TRI or @rpoyner-tri?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18564)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/yaml.py` line 152 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18564#-NLTn1V_3F-XhZoSLhDF:-NLTn1V_3F-XhZoSLhDG:bios7li) ([raw file](https://github.com/robotlocomotion/drake/blob/c199fdd7cab0731cc462191a743b71c39aa09c64/bindings/pydrake/common/yaml.py#L152)):*
> ```Python
>     fields = getattr(obj, "__fields__", None)
>     if fields is not None:
>         return dict([
> ```

This branch isn't unit tested yet.  (Coming in the future).  I should either TODO it for unit testing, or yank it until the next PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/yaml.py` line 152 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLTn1V_3F-XhZoSLhDF:-NLWO0NG4pb2a7KShcUZ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c199fdd7cab0731cc462191a743b71c39aa09c64/bindings/pydrake/common/yaml.py#L152)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This branch isn't unit tested yet.  (Coming in the future).  I should either TODO it for unit testing, or yank it until the next PR.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-:-NLWkl-j092xdI4Gc8X3:b-vdt6d3)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
*[`bindings/pydrake/common/yaml.py` line 141 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLX8ee75WBaCKs2O7hP:-NLX8ee75WBaCKs2O7hQ:b-83l5s8) ([raw file](https://github.com/RobotLocomotion/drake/blob/45146acab18074dc790cf426b7a02624ffbca286/bindings/pydrake/common/yaml.py#L141)):*
> ```Python
> def _enumerate_field_types(obj):
>     """Returns a Mapping[str, type] of the schema-based field names and types
>     of the given object `obj`. (Note that `obj` is a value, not a type.)
> ```

I think this comment might be wrong.  I'll work on improving / confirming.



_Code quote:_
```Python
(Note that `obj` is a value, not a type.)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`bindings/pydrake/common/yaml.py` line 141 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLX8ee75WBaCKs2O7hP:-NLXBclb87PwJgI4mQNU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/45146acab18074dc790cf426b7a02624ffbca286/bindings/pydrake/common/yaml.py#L141)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this comment might be wrong.  I'll work on improving / confirming.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-:-NLXnenP3i8G18yKNx8s:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 283 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLXO-BR4RGVo1hFxjyH:-NLXO-BS05avxXGgHEfc:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cb01a529a5e2b7992880b5a1a5a667488159925/bindings/pydrake/common/test/yaml_typed_test.py#L283)):*
> ```Python
>     @run_with_multiple_values(_all_typed_read_options())
>     def test_read_optional(self, *, options):
>         # The test case numberes here (1..12) reference the specification as
> ```

typo



_Suggestion:_
```Python
numbers
```
___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 395 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLXnPvkAphDljgm2M9T:-NLXnPvkAphDljgm2M9U:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/0cb01a529a5e2b7992880b5a1a5a667488159925/bindings/pydrake/common/test/yaml_typed_test.py#L395)):*
> ```Python
> 
> 
> class TestYamlTypedReadAccepatance(unittest.TestCase):
> ```

typo



_Suggestion:_
```Python
Acceptance
```

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.  (Feel free to spill to Eric tomorrow if need be.)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm:

I gave a best-effort review. Feel free to tag a reviewer with more Python experience if in doubt.

> Reviewed 1 of 4 files at r1, 3 of 5 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-:-NLYdjB26X9hf1GFk-v1:bd80ek8)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 303 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLYbme1EljS0n93cffG:-NLYbme1EljS0n93cffH:br5gucs) ([raw file](https://github.com/RobotLocomotion/drake/blob/5304ef9640e3108c6d313e5ac75f4ecf88041e51/bindings/pydrake/common/test/yaml_typed_test.py#L303)):*
> ```Python
>                     else:
>                         amended_data = "foo: bar"
>                     actual = yaml_load_typed(
> ```

nit, typo



_Suggestion:_
```Python
                    actual = yaml_load_typed(
                        schema=schema, data=amended_data, **options)
```

**Comment by jwnimmer-tri** [comment]
I am going to keep the PR train moving, but \CC @EricCousineau-TRI in case you'd like to give it a once-over.  In any case I'll plan to ping you (Eric) once the new subsystem is complete, so you can take a look.  It will similar to the Python schema stuff in Anzu, except that here I don't plan to enforce anything with numpy types yet.  (I plan to use numpy.typing to that effect, eventually; just not this quarter.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`bindings/pydrake/common/test/yaml_typed_test.py` line 303 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18564#-NLYbme1EljS0n93cffG:-NLYeXsU3X5dLfwH2jra:bmjw0s4) ([raw file](https://github.com/RobotLocomotion/drake/blob/5304ef9640e3108c6d313e5ac75f4ecf88041e51/bindings/pydrake/common/test/yaml_typed_test.py#L303)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, typo
</blockquote></details>

Yikes!  Thanks, fixed.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18564)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
