### PR TITLE
Add gcc_copts option to drake_cc_foo macros

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7013)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for all review per rotation, please.

**Comment by SeanCurtis-TRI** [comment]
From the slack conversation, I infer that this is supposed to enable *suppression* of unused variable warnings (via use of `gcc_copts = ["-Wno-unused-parameter"]`, right? However, the behavior I'm observing on my machine is inconsistent with this assumption.

Test 1:
Add a simple unused variable to code.
Run:
  - `bazel build --compiler=clang-3.9 drake/geometry:geometry_state`
  - `bazel build --compiler=gcc-4.9 drake/geometry:geometry_state`
Result:
  Both builds flag the unused variable.
  - gcc error: `error: unused variable 'unused' [-Werror=unused-variable]`
  - clang error: `error: unused variable 'unused' [-Werror,-Wunused-variable]`

Test 2:
Same as test 1, but add `copts = ["-Wno-unused-parameter"]` to the `geometry_state` build target
Result: Exactly the same.

Checkout these changes and repeat tests 1 and 2 as 1b and 2b:
Test 1b result: The same, as one would expect.
Test 2b result: The same, again, as one would expect.
Test 3:
  Add the `gcc_copts = ["-Wno-unused-parameter"]` flag
Result: The same. No change; the same as all previous efforts. 

So, am I misunderstanding what this PR is supposed to achieve? Furthermore, the slack conversation indicated concern that passing a gcc flag to clang might cause problems, but it appears to *not* be the case -- if, in fact, the flag is actually being passed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7013#-:-Ktvd_WM43JFOIa_DCcH:b159sb5)*

**Comment by jwnimmer-tri** [comment]
> From the slack conversation, I infer that this is supposed to enable suppression of unused variable warnings (via use of gcc_copts = ["-Wno-unused-parameter"], right?

Yes, but unused _parameters_ specifically.

> Add a simple unused variable to code.

You need to test with a dead parameter, not a dead local variable.  Both GCC and Clang flag dead local variables (under a different warning flag, I think its `-Wunused`); only GCC flags dead parameters by default, under `Wunused-parameter`.

> Same as test 1, but add copts = ["-Wno-unused-parameter"]
> Result: The same. No change; the same as all previous efforts.

Because you added a dead local variable, not a dead parameter.

> Furthermore, the slack conversation indicated concern that passing a gcc flag to clang might cause problems, but it appears to not be the case -- if, in fact, the flag is actually being passed.

On further study, Clang does support `Wunused-parameter` so that's why its not complaining.  So indeed, for `Wno-unused-parameter` we could just use `copts` and not need `gcc_copts`.  But since we _do_ enable some other GCC-only flags by default, it still seems worthwhile to admit gcc-specific copts.

**Comment by SeanCurtis-TRI** [comment]
D'oh! As soon as I saw the emphasized "parameters" I kicked myself (despite how many times I copied-and-pasted the flag....sheesh.)

:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7013#-:-KtviiF1e9LUsIgvnbSE:bbd62nq)*

**Pull request merged**
