### PR TITLE
Add more tests on the BoundingBoxConstraint dual solution.

### PR DESCRIPTION
**Pull request by hongkai-dai**
When the BoundingBoxConstraint is an equality constraint on the variable, the dual solution could be tricky. We add more tests to make sure the dual solution is correct.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-NdsQ-NoDN71c0RE1glW:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
ping @AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-NeiTpRS7vaJmQvEPQKy:b536n7t)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
Which solvers does this apply to?

I see changes for `CLP`, `Gurobi`, `IPOPT`, `Mosek`, `Scs`, and `Snopt`.

This is missing `OSQP` and `CSDP` .

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-NeyLwsm92fYkXlyCm5A:b7saryl)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/clp_solver_test.cc` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPEhX6Q-eOa2pecJE:-NeyPEhX6Q-eOa2pecJF:bxqhxut) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/clp_solver_test.cc#L92)):*
> ```cpp
> GTEST_TEST(TestDual, DualSolution5) {
>   ClpSolver solver;
>   if (solver.available()) {
> ```

The test already checks if the solver is available so this may be uneeded
___
*[`solvers/test/gurobi_solver_test.cc` line 615 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPRrPAgIJqBeiWzwe:-NeyPRrPAgIJqBeiWzwf:b849h91) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/gurobi_solver_test.cc#L615)):*
> ```cpp
> GTEST_TEST(GurobiTest, LPDualSolution5) {
>   GurobiSolver solver;
>   TestLPDualSolution5(solver);
> ```

Why does this not need a tolerance, but the mosek ones do?
___
*[`solvers/test/linear_program_examples.h` line 262 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyMknb57bx_fz_1BX5:-NeyMknb57bx_fz_1BX6:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.h#L262)):*
> ```objc
> 
> /** Test LP with BoundingBoxConstraint, with some lower bound equal to the upper
>  * bound. */
> ```





_Suggestion:_
```objc
/** Test LP with BoundingBoxConstraint, with some lower bounds equal to the upper
 * bounds. */
```
___
*[`solvers/test/linear_program_examples.cc` line 635 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNBWpDZUwLckOCwgH:-NeyNBWpDZUwLckOCwgI:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L635)):*
> ```cpp
>   // -2 <= x(1) <= 1
>   //
>   // Note that after aggregating all bounds, then bounds on x(1) is 1 <= x(1) <=
> ```





_Suggestion:_
```cpp
the
```
___
*[`solvers/test/linear_program_examples.cc` line 635 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNDfDEooHp4wm2g_2:-NeyNDfDEooHp4wm2g_3:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L635)):*
> ```cpp
>   // -2 <= x(1) <= 1
>   //
>   // Note that after aggregating all bounds, then bounds on x(1) is 1 <= x(1) <=
> ```





_Suggestion:_
```cpp
 are
 
```
___
*[`solvers/test/linear_program_examples.cc` line 636 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNHS-6Sv7B5KPpMIg:-NeyNHS-6Sv7B5KPpMIh:b2niczw) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L636)):*
> ```cpp
>   //
>   // Note that after aggregating all bounds, then bounds on x(1) is 1 <= x(1) <=
>   // 1, but its lower bound comes from bbcon1, while the upper bound comes from
> ```

the



_Code quote:_
```cpp
its
```
___
*[`solvers/test/mosek_solver_test.cc` line 497 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPgsv166nE4A9p_tI:-NeyPgsv166nE4A9p_tJ:b-5vf3ub) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/mosek_solver_test.cc#L497)):*
> ```cpp
> GTEST_TEST(MosekTest, LPDualSolution5) {
>   MosekSolver solver;
>   if (solver.available()) {
> ```

The test already checks if the solver is available.

**Review by hongkai-dai — COMMENTED** [review]
The extra tests we add in this PR are linear programs. OSQP doesn't work well for linear programs (in fact it is not in our linear program solver list https://github.com/RobotLocomotion/drake/blob/b25ee4415b49a0ef8e65b093071d4697338c3718/solvers/choose_best_solver.cc#L155-L170

For CSDP, I haven't added getting the dual solution for CSDP solver yet. Currently if we call GetDualSolution() for a result returned from CSDP, it will throw a runtime error.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-Nf1xzdc06G5QF_bHPdf:b-d9yml3)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/clp_solver_test.cc` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPEhX6Q-eOa2pecJE:-Nf1ypxP2AzLBuX1lva7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/clp_solver_test.cc#L92)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The test already checks if the solver is available so this may be uneeded
</blockquote></details>

Done.
___
*[`solvers/test/gurobi_solver_test.cc` line 615 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPRrPAgIJqBeiWzwe:-Nf1ys9Y71xyEudyW6JA:b6o18aj) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/gurobi_solver_test.cc#L615)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Why does this not need a tolerance, but the mosek ones do?
</blockquote></details>

Neither one needs to specify the tolerance. But I was just trying to stay consistent with other tests inside mosek_solver_test.cc, that they use 1E-8 as the tolerance.
___
*[`solvers/test/linear_program_examples.h` line 262 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyMknb57bx_fz_1BX5:-Nf1zbNbBTSKp7Hq0jls:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.h#L262)):*
> ```objc
> 
> /** Test LP with BoundingBoxConstraint, with some lower bound equal to the upper
>  * bound. */
> ```

Done.
___
*[`solvers/test/linear_program_examples.cc` line 635 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNBWpDZUwLckOCwgH:-Nf1zfcT34iznATsw_FD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L635)):*
> ```cpp
>   // -2 <= x(1) <= 1
>   //
>   // Note that after aggregating all bounds, then bounds on x(1) is 1 <= x(1) <=
> ```

Done.
___
*[`solvers/test/linear_program_examples.cc` line 635 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNDfDEooHp4wm2g_2:-Nf1zjmN8WxyzSwksr7v:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L635)):*
> ```cpp
>   // -2 <= x(1) <= 1
>   //
>   // Note that after aggregating all bounds, then bounds on x(1) is 1 <= x(1) <=
> ```

Done.
___
*[`solvers/test/linear_program_examples.cc` line 636 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyNHS-6Sv7B5KPpMIg:-Nf1zqdD-tOLIb6mRGIH:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/linear_program_examples.cc#L636)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`solvers/test/mosek_solver_test.cc` line 497 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-NeyPgsv166nE4A9p_tI:-Nf1zw_bBfhroBJEl8fJ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7e778fa651fb905b85bd862de1b2a33bf873985f/solvers/test/mosek_solver_test.cc#L497)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The test already checks if the solver is available.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-Nf97jyP3kJS4BSwGa_W:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-NfA2kf06TCBkoWaWcpq:b-2hj6f6)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20160#-:-NfBUR470SztzLyLuKQW:bnfp4nl)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
