### PR TITLE
[workspace] Upgrade python_rules to latest release 0.26.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #20462.

We'll plan to squash-and-merge using the PR title as the subject, and no commit body other than Co-authored-by.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20473)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20473)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both(?) reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20473#-:-NiaNr_T9jh1QJMwFMy_:bnfp4nl)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20473#-:-NiaNwppBqzZVt6JgbJ4:bm9o57a)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
-@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20473#-:-NiaO6nE50WRt-fZoHti:ba35lat)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
