### PR TITLE
[render] Remove RenderEngineOspray entirely

### LINKED ISSUE #14326: Disable RenderEngineOspray on macOS
Per discussion in #13253, it's going to get increasingly more difficult to maintain Ospray on macOS -- especially with the switch to ARM hardware.  We will make it Ubuntu-only to reduce our build-support engineering cost.

\CC @SeanCurtis-TRI

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Other than killing the class, its factory, bindings, and their tests, this also touches a fair amount of other sites in the code:

1. Documentation of various sorts have references to the render engine removed.
2. Build infrastructure removes explicit dependencies on OSPRay (and Embree).
3. Removed OSPRay-specific functionality from docker configuration.

resolves #14326

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jamiesnape for review. While I left CI content, I'm not sure if there are places where I dug too deeply or not deeply enough.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339#-:-MMLSRrt6w7IUGOm78E_:bndm572)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

I think we are basically good. I will need to go through everything VTK-related soon anyway.

You probably should request a Mac Catalina build.

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339#-:-MMLURAc6mrXvml4LjdT:b31040t)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[tools/workspace/vtk/dockerfile_build_vtk_binaries, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14339#-MMLTKUHBvIOBdl6sXsn:-MMLTKUHBvIOBdl6sXso:bslt7yl) ([raw file](https://github.com/robotlocomotion/drake/blob/04e027555bf2fb3f7bca6290215212bcede04b1d/tools/workspace/vtk/dockerfile_build_vtk_binaries#L21)):*
> ```
>   -DCMAKE_MODULE_LINKER_FLAGS:STRING='-Wl,-Bsymbolic-functions -Wl,-z,now -Wl,-z,relro' \
>   -DCMAKE_SHARED_LINKER_FLAGS:STRING='-Wl,-Bsymbolic-functions -Wl,-z,now -Wl,-z,relro' \
>   -DModule_vtkRenderingOSPRay:BOOL=OFF \
> ```

BTW Delete the whole line.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339#-:-MMME_z5B4hQemJWZcpq:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jamiesnape and @rpoyner-tri)

___
*[tools/workspace/vtk/dockerfile_build_vtk_binaries, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14339#-MMLTKUHBvIOBdl6sXsn:-MMMETzx0-zGTxvWvsTs:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/04e027555bf2fb3f7bca6290215212bcede04b1d/tools/workspace/vtk/dockerfile_build_vtk_binaries#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Delete the whole line.
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14339#-:-MMMekvV-oAkqI5zhsMy:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jamiesnape

**Pull request merged**
