### PR TITLE
Adds LCM period argument to AllegroCommandReceiver's constructor.

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@huihuatri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732#-:-MUtOOmh4mifsUJchT3Z:b1py1es)* status: LGTM missing from assignee huihuaTRI, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @huihuaTRI)

**Review by huihuaTRI — COMMENTED** [review]
:lgtm: with one suggestion.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732#-:-MUtSLfm9Oz78fIyGHNo:btrovwl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rcory)

___
*[examples/allegro_hand/allegro_lcm.h, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14732#-MUtS5db5gomTzQU2EtZ:-MUtS5db5gomTzQU2Et_:b-tz1gsz) ([raw file](https://github.com/robotlocomotion/drake/blob/63a311e2d02a6395fcf20f842cf7586d5df536c6/examples/allegro_hand/allegro_lcm.h#L53)):*
> ```objc
> 
>   void set_lcm_period(double period) {
>     lcm_period_ = period;
> ```

nit: maybe add a check to assert `period > 0`. The user probably will never make this mistake, but I often think it is useful to do basic checks.

**Comment by jwnimmer-tri** [comment]
I'm confused.  Maybe I misread this PR, but only he constructor reads the value -- the setter will have no effect so the System event handling?

**Review by rcory — COMMENTED** [review]
@jwnimmer-tri You're right. Yikes! I've updated to take in the argument in the constructor  (and also changed the name/description of this PR to correctly reflect the changes).

PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732#-:-MUtZyum9odb52tARnM8:buwz3vz)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @huihuaTRI and @rcory)

**Review by huihuaTRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @huihuaTRI and @rcory)

___
*[examples/allegro_hand/allegro_lcm.h, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14732#-MUt_cyh4F-91RErNAQ5:-MUt_cyh4F-91RErNAQ6:b-5j7lfr) ([raw file](https://github.com/robotlocomotion/drake/blob/1f9d25b3bed0a0ef9ccfb391500c383869f7bee9/examples/allegro_hand/allegro_lcm.h#L69)):*
> ```objc
>   int torque_output_port_ = 0;
>   const int num_joints_ = 16;
>   double lcm_period_;
> ```

nit: should be const

**Review by rcory — COMMENTED** [review]
+@soonho-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732#-:-MUtd5ui0h-1BoH1cSJh:bxwr5c8)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @huihuaTRI and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732#-:-MUtkbrf5xm53pcbeoBx:bnfp4nl)* status: 1 unresolved discussion (waiting on @rcory)

___
*[examples/allegro_hand/allegro_lcm.h, line 51 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14732#-MUtkOqyDywl3ZMTDHat:-MUtkOqz8m0SawqRlQma:b-xmje7o) ([raw file](https://github.com/robotlocomotion/drake/blob/4cc933e85059ebe4cab5316290136b01d21e871b/examples/allegro_hand/allegro_lcm.h#L51)):*
> ```objc
>   }
> 
>   double lcm_period() {
> ```

nit, => `double lcm_period() const`

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14732)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),huihuaTRI

**Pull request merged**
