### PR TITLE
moved body index correction out of RBM and into the mex file

### LINKED ISSUE #1053: suspicious lines in RigidBodyManipulatorContact.cpp
was poking through RigidBodyManipulatorContact.cpp (quieting a few windows build warnings) and was surprised to see the lines:

139:     forwardJac(bodyInd - 1, bodyPoints, 0, J_tmp);

and 

163:   forwarddJac(bodyInd - 1, bodyPoints, dJ_tmp); //dJac instead of Jac

those look very suspicious to me.  I think it should be just bodyInd (not bodyInd-1, which only happens at mex interface levels when we convert matlab indices into c++ indices).   @psiorx - can you take a look at confirm for me?

### PR DESCRIPTION
**Pull request by psiorx**
Resolves #1053

### CODE REVIEW

**Comment by psiorx** [comment]
Closing to fix unit tests.

**Comment by psiorx** [comment]
Once more, with feeling.

**Comment by RussTedrake** [comment]
looks good.  will just wait drake001.

**Comment by psiorx** [comment]
This is a drake-distro error, no?

**Comment by psiorx** [comment]
Bumping drake001

**Pull request merged**
