### PR TITLE
Test Ipopt integration on Mac

### PR DESCRIPTION
**Pull request by sammy-tri**
This is a second try at #2429.  I'm not sure it's going to work as well as I'd hoped either.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2430)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
Closing this PR as I don't think I need to do any more test runs until it's finally time to try integrating IPOPT.

**Pull request closed without merging**
