### PR TITLE
In maliput, change from .toRotationMatrix() to new RotationMatrix class.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10186)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Changes like this to automotive code need an automotive feature reviewer.  +@maddog-tri +@SeanCurtis-TRI for review, please.

**Comment by jwnimmer-tri** [comment]
Furthermore, I believe that not using Drake sugar for these concepts is _intentional_ in maliput, so I suspect this PR will be rejected in its entirety.  (The "Calc" convention is for multibody & systems-framework only -- it is _not_ a Drake-wide convention, and is _not_ used in maliput.)  I suspect that you should exclude all of `automotive` from #9865 work entirely.

**Comment by jwnimmer-tri** [comment]
I'll let @maddog-tri provide a decision.  It's not my call.

Possibly the context you're missing here is that there is a lot of of TRI-internal code (not part of Drake) that is using these (maliput) function signatures, and that body of work doesn't use `math::RotationMatrix` -- so that code would need to gain a `.matrix()` wart, just like the small unit tests here did, nevermind adjusting for the the method rename, and nevermind that it's a flag day instead of deprecation transition.  So, the API changes here don't seem worth it.  Maybe the `return q.toRotationMatrix` should change to `return RotationMatrix(q).matrix()`, at most.

**Comment by maddog-tri** [comment]
I understand where you're coming from, but if you do (2), then you open the whole can of worms of marking things deprecated and ensuring consistency with other methods and other maliput classes, etc, or else you have two confusingly identical methods.  I'd prefer to leave everything as `.matrix()` and only `.matrix()` and leave all the case-changing to a future maintenance/debt-payment task.

**Comment by jwnimmer-tri** [comment]
Also, the maliput name `.matrix()` is _not_ defective with respect to Drake GSG.  It's an accessor, it's less than 5 lines long, and it's O(1).  Sure, it's tens of CPU cycles instead of 2 or 5 or something, but who cares?

**Comment by jwnimmer-tri** [comment]
The changes other than to `lane_data.h` seems like unrelated whitespace rejiggering, should should not be part of this PR?

**Comment by jwnimmer-tri** [comment]
Ah, I recall now that the `geometry/test/proximity_engine_test.cc` test was a fix-forward from a prior PR's mistake (as noted by "Random:" note upthread), so I guess that should stay.  I guess I'll let @maddog-tri respond to other maliput-related whitespace shrapnel left over here.

**Pull request merged**
