### PR TITLE
[fem] Move corotated model out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
Just a few minor comments on needed documentation now this is coming out of dev.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617#-:-MwRkHTj3SHcaHM4n05m:bobs4cg)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/corotated_model.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRhMhcAvDkAdqnuBTe:-MwRhMhcAvDkAdqnuBTf:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.h#L44)):*
> ```objc
>   /* Constructs a CorotatedModel constitutive model with the
>    prescribed Young's modulus and Poisson's ratio.
>    @param youngs_modulus  Young's modulus of the model, with unit N/m²
> ```





_Suggestion:_
```objc
with units of N/m².
```
___
*[multibody/fem/corotated_model.h, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRgzHG3iBu4KWioilw:-MwRgzHH38muTe6sGugM:b-iat9td) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.h#L45)):*
> ```objc
>    prescribed Young's modulus and Poisson's ratio.
>    @param youngs_modulus  Young's modulus of the model, with unit N/m²
>    @param poissons_ratio   Poisson's ratio of the model, unitless.
> ```

minor, spacing between variables's names and brief description.
___
*[multibody/fem/corotated_model.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRiTpJBWgTyI_W6QyD:-MwRiTpJBWgTyI_W6QyE:bplydtn) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.cc#L43)):*
> ```cpp
>     const Matrix3<T>& R = data.R()[i];
>     const Matrix3<T>& JFinvT = data.JFinvT()[i];
>     (*P)[i] = 2.0 * mu_ * (F - R) + lambda_ * Jm1 * JFinvT;
> ```

minor, in this file we don't use the same notation as in the cited paper. 
Probably worth saying a few words at least?
___
*[multibody/fem/corotated_model_data.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRiyOs8Vw6zmXier0w:-MwRiyOs8Vw6zmXier0x:b-jx8mv6) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model_data.h#L14)):*
> ```objc
> 
> /* Data supporting calculations in CorotatedModel.
>  See CorotatedModel for how the data is used. See DeformationGradientData for
> ```

Actually there is nothing in `CorotatedMOdel` that explains understand this class better, without diving into the source.
Probably worth including a high level description of the data here including for instance how the notation used here is different from the one used in [Stomakhin, 2012], and why.



_Code quote:_
```objc
See CorotatedModel for how the data is used.
```
___
*[multibody/fem/corotated_model_data.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRjGoD8hBPNLnR6jlt:-MwRjGoE6nbZ1PklIvka:bjw7108) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model_data.h#L29)):*
> ```objc
>   CorotatedModelData();
> 
>   const std::array<Matrix3<T>, num_locations>& R() const { return R_; }
> ```

this methods now need at least some minimum documentation.
Also probably worth if possible to make an explicit connection to the symbols in the cited paper [Stomakhin, 2012].

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617#-:-MwSXYtOA7Na3feeBXII:b-i35568)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[multibody/fem/corotated_model.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRhMhcAvDkAdqnuBTe:-MwSRu_SEnb97p1UPuFm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.h#L44)):*
> ```objc
>   /* Constructs a CorotatedModel constitutive model with the
>    prescribed Young's modulus and Poisson's ratio.
>    @param youngs_modulus  Young's modulus of the model, with unit N/m²
> ```

Done.
___
*[multibody/fem/corotated_model.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRiTpJBWgTyI_W6QyD:-MwSTgki8JzPgS-nlf2N:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.cc#L43)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, in this file we don't use the same notation as in the cited paper. 
Probably worth saying a few words at least?
</blockquote></details>

Done, thanks.
___
*[multibody/fem/corotated_model_data.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRiyOs8Vw6zmXier0w:-MwSVJrT4Nfv1EKfbD8k:blw27i9) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model_data.h#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Actually there is nothing in `CorotatedMOdel` that explains understand this class better, without diving into the source.
Probably worth including a high level description of the data here including for instance how the notation used here is different from the one used in [Stomakhin, 2012], and why.
</blockquote></details>

I added some description of the data in the class doc. The deviation from the formula in the paper is mentioned close to the implementation in the source.
___
*[multibody/fem/corotated_model_data.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRjGoD8hBPNLnR6jlt:-MwSV_kv3PzWx1uiptUj:b5qfb4d) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model_data.h#L29)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this methods now need at least some minimum documentation.
Also probably worth if possible to make an explicit connection to the symbols in the cited paper [Stomakhin, 2012].
</blockquote></details>

I briefly went over the paper again and didn't find any mention of the polar decomposition. We prefer the polar over explicitly finding the singular values here since it's needed in the calculation of stress and stress derivative. I don't think that line of reasoning should be described in the doc of this method here though.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with some nits
(noting that most of this is still `internal` code)

> Reviewed 5 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617#-:-MwSn5xo-9sxN79JnO6B:bxdyw9z)* status: 5 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/corotated_model.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSnLXVBTrPbWBFJK42:-MwSnLXVBTrPbWBFJK43:biabygb) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.h#L33)):*
> ```objc
> template <typename T, int num_locations>
> class CorotatedModel final
>     : public ConstitutiveModel<CorotatedModel<T, num_locations>,
> ```

nit Using multiple (static) inheritance only for traits (as a mixin) has an odd code smell, esp. for traits with 2 attributes. (I'm not sure if there is existing precedent).

Consider inline-alias:
```
using Traits = CorotatedModelTraits<T, num_locations>;
using Data = typename Traits::Data;
using T = typename Traits::T;
```

(feel free to dismiss ofc)
___
*[multibody/fem/corotated_model.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSoM_s9-OW-px41SUz:-MwSoM_s9-OW-px41SV-:b-uclv8l) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.cc#L7)):*
> ```cpp
> 
> #include "drake/common/autodiff.h"
> #include "drake/multibody/fem/calc_lame_parameters.h"
> ```

BTW Teehee, "Lame" :P
___
*[multibody/fem/corotated_model.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSoPha4zZVMVFftIzu:-MwSoPha4zZVMVFftIzv:b-v33bhx) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.cc#L7)):*
> ```cpp
> 
> #include "drake/common/autodiff.h"
> #include "drake/multibody/fem/calc_lame_parameters.h"
> ```

nit The dev version of the Lamé parametrs, `fixed_fem/dev/calc_lame_parameters`, appear unused now?

Can they be deleted?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)* status: 5 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/corotated_model.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRhMhcAvDkAdqnuBTe:-MwT2jVd4qysnJR0nXi8:bngtphl) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.h#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

period at the end of sentence. 
Why two spaces between variable name and description?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[multibody/fem/corotated_model.h, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwRhMhcAvDkAdqnuBTe:-MwTKMWI8fXBxyA9tbVQ:b-45xm4v) ([raw file](https://github.com/robotlocomotion/drake/blob/9cad8b779e1882cab3bf62845da50e15d13ffe51/multibody/fem/corotated_model.h#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

period at the end of sentence. 
Why two spaces between variable name and description?
</blockquote></details>

Done re period. thanks.
I like two spaces out side of doxygen when VS code doesn't do the highlight.
___
*[multibody/fem/corotated_model.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSnLXVBTrPbWBFJK42:-MwTKKjgBAt35LojUXU5:b-o6r32i) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.h#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Using multiple (static) inheritance only for traits (as a mixin) has an odd code smell, esp. for traits with 2 attributes. (I'm not sure if there is existing precedent).

Consider inline-alias:
```
using Traits = CorotatedModelTraits<T, num_locations>;
using Data = typename Traits::Data;
using T = typename Traits::T;
```

(feel free to dismiss ofc)
</blockquote></details>

Done, thanks.

`using T = typename Traits::T;` won't work though because T is already a template parameter of the class, right?
___
*[multibody/fem/corotated_model.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSoM_s9-OW-px41SUz:-MwTKdyz0hgAz8OjlKzb:bxseeig) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.cc#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Teehee, "Lame" :P
</blockquote></details>

Lame that we can't do tones.
___
*[multibody/fem/corotated_model.cc, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSoPha4zZVMVFftIzu:-MwTKkOLD-66NCEjStPm:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.cc#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The dev version of the Lamé parametrs, `fixed_fem/dev/calc_lame_parameters`, appear unused now?

Can they be deleted?
</blockquote></details>

Done, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/corotated_model.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSnLXVBTrPbWBFJK42:-MwTU9Ep4LO0o6JGaCp-:bt2tykv) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done, thanks.

`using T = typename Traits::T;` won't work though because T is already a template parameter of the class, right?
</blockquote></details>

OK Ah, gotcha. Workaround is to be indirect via param, e.g. `template <typename T_ ...> ... using T = T_`, iff you care about alias being present for downstream as `CorotatedModel<>::T`.

However, if you don't care, then this works!

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16617)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/corotated_model.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16617#-MwSnLXVBTrPbWBFJK42:-MwTUtcy-XG09OeQeTeX:b271dm1) ([raw file](https://github.com/robotlocomotion/drake/blob/bbad59e17f030233bbc85c311afd4f35684569ab/multibody/fem/corotated_model.h#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, gotcha. Workaround is to be indirect via param, e.g. `template <typename T_ ...> ... using T = T_`, iff you care about alias being present for downstream as `CorotatedModel<>::T`.

However, if you don't care, then this works!
</blockquote></details>

Got it, thanks. I'm content with this as is.

**Pull request merged**
