### PR TITLE
[pydrake] Bind symbolic.Expression.get_kind

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16013.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16012#-:-MnRd7FnB6U_w7YomfwH:bxqo58p)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/test/symbolic_test.py, line 610 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16012#-MnRcTkK5SJrKLUaMntM:-MnRcTkK5SJrKLUaMntN:bdbl4xi) ([raw file](https://github.com/robotlocomotion/drake/blob/2a4346b9c2e91122336761cdddf0e8326898a9c3/bindings/pydrake/test/symbolic_test.py#L610)):*
> ```Python
> 
>     def test_get_kind(self):
>         self.assertEqual((x + y).get_kind(), sym.ExpressionKind.Add)
> ```

BTW As I reviewed this, the "defects" I looked for were:

1. Did this capture all the enumerated types?
2. Did the right doc string get attached to the right enum value?
3. Is this the type that gets returned by `get_kind()`.

This test reasonably samples the third item. Anything we can do about the other two? One can imagine we would like to fail fast if `Integral` gets added (per the TODO) and not bound or if things were get cross wired. Probably overkill and not in line with the rest of our pydrake tests. But it's always disappointing during Review when the work the reviewer puts in doesn't seem to be represented in the tests.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16012)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/test/symbolic_test.py, line 610 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16012#-MnRcTkK5SJrKLUaMntM:-MnRsw0n6LP9RFFhWIKt:b-b6tkt5) ([raw file](https://github.com/robotlocomotion/drake/blob/2a4346b9c2e91122336761cdddf0e8326898a9c3/bindings/pydrake/test/symbolic_test.py#L610)):*
> (2) Did the right doc string get attached to the right enum value?

In pydrake bindings, checking that the developer correctly pasted `(..., &thing, doc.thing.doc)` into the bindings (and not, say, `(..., &thing, doc.not_thing.doc)`) is always only checked via code review, not unit testing.  Par for the course.

The only way I see toward testing this is something like putting the `file_coverage.csv` data under unit test, which is to say that we insist that every public C++ API Doxygen string is either used in the bindings or specifically excluded.  That isn't really tractable until we insist that (at least for some packages) all of the C++ is bound.  I would like to do that eventually, just can't do it today.

> (1) Did this capture all the enumerated types?

Absent any C++ code that allows for either introspection or visiting (even just, e.g., a kMaxValue constant), there's no easy way to test for this.

**Comment by jwnimmer-tri** [comment]
Skipping the slow Debug build; not relevant here.

**Pull request merged**
