### PR TITLE
[tutorials] Adds an example of using `namedview` in authoring leaf systems

### PR DESCRIPTION
**Pull request by RussTedrake**
I had a question come up about naming elements of a state vector, and thought it would be an excellent addition to the tutorial.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`tutorials/authoring_leaf_systems.ipynb` line 430 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUXVpR5x4hytfn8Hx3:-NOUaa-68p-5apasopEJ:b-frddkc) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L430)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@EricCousineau-TRI -- is there a reason we don't allow the default (all zeros) initializer for `namedview()`?  It often seems an unnecessary burden to have to initialize it everywhere.
</blockquote></details>

Alternatively (or additionally), it seems like it would be nice to initialize from a Dictionary.  e.g.
```NamedViewDemo.MyDiscreteState({'a': 1, 'b': 2})```

**Review by SeanCurtis-TRI — COMMENTED** [review]
I did a drive by review because a) I was curious and b) I vaguely anticipate this'll come to me on Monday. )

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-:-NOVUB4uDpaE1TX0OZOM:bmf8vwv)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOVP8Ag0TJxgZtVhdea:-NOVP8Ag0TJxgZtVhdeb:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L365)):*
> ```
>     "## Naming Vector Values\n",
>     "\n",
>     "Abstract-valued ports, state, and/or parameters can be used to work with structured data. But it can also be convenient to use sting names to reference the individual elements of vector-valued data. In Python, we recommend using a `namedview` workflow, as demonstrated in the example below. For the equivalent in C++, see [this issue](https://github.com/RobotLocomotion/drake/issues/12566).\n",
> ```

nit



_Suggestion:_
```
string
```
___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOVPYnA9t9x5hwCZ4T4:-NOVPYnA9t9x5hwCZ4T5:b-q6z98q) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L365)):*
> ```
>     "## Naming Vector Values\n",
>     "\n",
>     "Abstract-valued ports, state, and/or parameters can be used to work with structured data. But it can also be convenient to use sting names to reference the individual elements of vector-valued data. In Python, we recommend using a `namedview` workflow, as demonstrated in the example below. For the equivalent in C++, see [this issue](https://github.com/RobotLocomotion/drake/issues/12566).\n",
> ```

nit: Might be worth providing a link to the [pydrake documentation](https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview) so they are fully aware that this is a drake thing. I know it's included in the imports, but that is so remote from this usage, it's easy to forget.



_Code quote:_
```
namedview
```
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOVQUjzBPgGEtfMGBpg:-NOVQUjzBPgGEtfMGBph:b-e2ppfq) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L367)):*
> ```
>     "Abstract-valued ports, state, and/or parameters can be used to work with structured data. But it can also be convenient to use sting names to reference the individual elements of vector-valued data. In Python, we recommend using a `namedview` workflow, as demonstrated in the example below. For the equivalent in C++, see [this issue](https://github.com/RobotLocomotion/drake/issues/12566).\n",
>     "\n",
>     "Note that the memory layout for a continuous state vector is slightly different than for discrete state, parameters, and input/output port data, so the syntax for dealing with it requires a slightly distinct `CopyToVector()` and `SetFromVector()`.  See [issue #9171](https://github.com/RobotLocomotion/drake/issues/9171)."
> ```

BTW It might be nice to have an example of `SetFromVector()` relating to the named view. As it is, the only invocation you have is for `derivatives` which is not the same.



_Code quote:_
```
SetFromVector()
```
___
*[`tutorials/authoring_leaf_systems.ipynb` line 402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUY0AK6etnBRg3QLiz:-NOVSb_ZDjJ4QAppvwAx:b-lahoi3) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L402)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@EricCousineau-TRI -- this one surprised me (and we should not merge the example until we resolve it).  In CalcOutput below, I was able to put a `namedview` on top of the `output.get_mutable_value()`, and have updates to the named view update the underlying BasicVector.  I then expected it to work the same way here, but it does not.  Are we eating a copy somewhere in the pipeline here, and not in the output case?
</blockquote></details>

Worth noting, I swapped the current code for this:

```py
        next_state = discrete_values.get_mutable_value()
        next_state[0] = discrete_state.a + 1
        next_state[1] = discrete_state.b + continuous_state.x
```

and the same problem exists; it doesn't appear to be related to named view. My hypothesis:

I believe this is related to #17349. Because we return an Eigen type, we translate it into a list and pass it back. However, because the contents are just doubles, they don't automatically feedback through. In contrast, the output port is `BasicVector` valued, so it passes through a different path.

**Comment by RussTedrake** [comment]
*[`tutorials/authoring_leaf_systems.ipynb` line 402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUY0AK6etnBRg3QLiz:-NOXGVgb9tDhrfyofSbh:bi6xi04) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L402)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Worth noting, I swapped the current code for this:

```py
        next_state = discrete_values.get_mutable_value()
        next_state[0] = discrete_state.a + 1
        next_state[1] = discrete_state.b + continuous_state.x
```

and the same problem exists; it doesn't appear to be related to named view. My hypothesis:

I believe this is related to #17349. Because we return an Eigen type, we translate it into a list and pass it back. However, because the contents are just doubles, they don't automatically feedback through. In contrast, the output port is `BasicVector` valued, so it passes through a different path.
</blockquote></details>

Thanks!  (Yes, I understood it wasn't about `namedview`, sorry if that wasn't clear.

I looked into it more and have fixed the bindings. I guess it is similar to #17349, but via `VectorBlock`.  Yikes.  We definitely need to seek and destroy those cases.

**Review by RussTedrake — COMMENTED** [review]
+@SeanCurtis-TRI for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-:-NOe6S1u1x8gM02xpNJx:b-fuqef1)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOVPYnA9t9x5hwCZ4T4:-NOe7mch2X37OFqU9K8s:b-339pqn) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L365)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Might be worth providing a link to the [pydrake documentation](https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview) so they are fully aware that this is a drake thing. I know it's included in the imports, but that is so remote from this usage, it's easy to forget.
</blockquote></details>

Done. I also linked to directly to the namedtuple that will be more familiar and which inspired it.
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOVQUjzBPgGEtfMGBpg:-NOe8rsm2uVnL9P6lgmB:bnjkhwr) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L367)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It might be nice to have an example of `SetFromVector()` relating to the named view. As it is, the only invocation you have is for `derivatives` which is not the same.
</blockquote></details>

won't fix.  I toyed with this.  but i don't think it's the recommended path for any of the bits I've implemented here, and it felt ungainly to have "you could have written that line in this different but functionally identical way...".  The only subtlety, imho, is the syntax of passing the argument like `view[:]`; in this respect the example in `CalcTimeDerivatives` is representative enough for me.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-:-NOjikywACtLBf-eRXTk:bmxilld)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @RussTedrake)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 402 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUY0AK6etnBRg3QLiz:-NOkzL5i3IHpuUTJrSKY:bro95ma) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L402)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Thanks!  (Yes, I understood it wasn't about `namedview`, sorry if that wasn't clear.

I looked into it more and have fixed the bindings. I guess it is similar to #17349, but via `VectorBlock`.  Yikes.  We definitely need to seek and destroy those cases.
</blockquote></details>

Sorry you ran into that, and sweet on the fix!
___
*[`tutorials/authoring_leaf_systems.ipynb` line 430 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUXVpR5x4hytfn8Hx3:-NOkydF_31XfCdnJEvCz:bw1yjft) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L430)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Alternatively (or additionally), it seems like it would be nice to initialize from a Dictionary.  e.g.
```NamedViewDemo.MyDiscreteState({'a': 1, 'b': 2})```
</blockquote></details>

I'd be fine w/ something like that!

I have a slight concern about initializing a view type with its own data by default, but that could be mitigated w/ state methods, such as
`MyNamedView.zeros()` or `MyNamedView.make(a=1, b=2)`

I'm concerned about constructing from a `dict`, because users may think it could be aliasing the entries from the dict. I don't believe it's trivial to try and make the `dict` values alias-able while also ensuring that `np.asarray(view)` aliases properly.

I can file an issue, if you'd like?
___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl-CDACYubO4myrHBW:-NOl-CDBEFufo6rczTzk:b-c9l3j3) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L365)):*
> ```
>     "## Naming Vector Values\n",
>     "\n",
>     "Abstract-valued ports, state, and/or parameters can be used to work with structured data. But it can also be convenient to use string names to reference the individual elements of vector-valued data. In Python, we recommend using a [`namedview`](https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview) workflow, which was inspired by Python's [`namedtuple`](https://docs.python.org/3.6/library/collections.html?highlight=namedtuple#collections.namedtuple) and is demonstrated in the example below. The Drake developers plan to [provide similar functionality in C++](https://github.com/RobotLocomotion/drake/issues/12566).\n",
> ```

nit Ah, it was inspired more directly by `namedlist`: https://gitlab.com/ericvsmith/namedlist
See: https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview

But transitively, yes, inspired by `namedtuple` ;)
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl05kZ5aWVYl_XBFBi:-NOl05kZ5aWVYl_XBFBj:b-8l30qp) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L367)):*
> ```
>     "Abstract-valued ports, state, and/or parameters can be used to work with structured data. But it can also be convenient to use string names to reference the individual elements of vector-valued data. In Python, we recommend using a [`namedview`](https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview) workflow, which was inspired by Python's [`namedtuple`](https://docs.python.org/3.6/library/collections.html?highlight=namedtuple#collections.namedtuple) and is demonstrated in the example below. The Drake developers plan to [provide similar functionality in C++](https://github.com/RobotLocomotion/drake/issues/12566).\n",
>     "\n",
>     "Note that the memory layout for a continuous state vector is slightly different than for discrete state, parameters, and input/output port data, so the syntax for dealing with it requires a slightly distinct `CopyToVector()` and `SetFromVector()`.  See [issue #9171](https://github.com/RobotLocomotion/drake/issues/9171)."
> ```

nit Is it worth explicitly showing that `np.asarray(view)` will alias the data in this example?

I realize that is missing from the poorly formatted example code in the Sphinx rendering:
https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview
___
*[`tutorials/authoring_leaf_systems.ipynb` line 410 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl09bTChkgnJeZMXWR:-NOl09bU0RoR1sWU25U-:b2bfuac) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L410)):*
> ```
>     "        dstate_dt.z = -continuous_state.z\n",
>     "        dstate_dt.theta = -np.arctan2(continuous_state.z, continuous_state.x)\n",
>     "        derivatives.SetFromVector(dstate_dt[:])\n",
> ```

nit Is the `[:]` necessary?

I would think that `NamedViewBase.__array__` should allow the array to implicitly convert, and thus satisfy the pybind11 bindings on the "conversion" pass of casting.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: feature with some minor comments

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-:-NOl1ELu-YXc37lXogeQ:boykq3y)* status: 4 unresolved discussions (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl686GCGe4YGz4D-00:-NOl686H-o1ulzSN99y-:b-txrj19) (no related file):*
FYI Going to file separate doc-fix PR.

___
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl05kZ5aWVYl_XBFBi:-NOl1AOYBGQ5rZT2RtoD:b-relb0g) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L367)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is it worth explicitly showing that `np.asarray(view)` will alias the data in this example?

I realize that is missing from the poorly formatted example code in the Sphinx rendering:
https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview
</blockquote></details>

(I will include relevant info in above-mentioned doc-fix PR)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: 4 unresolved discussions (waiting on @EricCousineau-TRI and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl686GCGe4YGz4D-00:-NOl6gcM7amfxiaNEP_z:b-oatb7k) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Going to file separate doc-fix PR.
</blockquote></details>

How will that play with #18825?

___
___
*[`tutorials/authoring_leaf_systems.ipynb` line 410 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl09bTChkgnJeZMXWR:-NOl6NLo5hAQsqxmJZCu:b-kred34) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L410)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is the `[:]` necessary?

I would think that `NamedViewBase.__array__` should allow the array to implicitly convert, and thus satisfy the pybind11 bindings on the "conversion" pass of casting.
</blockquote></details>

Oh, please, let it be true. I had a similar thought but didn't follow up. Fingers crossed.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: 4 unresolved discussions (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl686GCGe4YGz4D-00:-NOl7otq-O5FH5hyTerd:b2j3qcc) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

How will that play with #18825?
</blockquote></details>

Ah, wasn't aware of that one. Will re-cater the PR to focus on improving docs for `np.asarray` and remove formatting changes. Then it should play well with it!

___

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 430 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUXVpR5x4hytfn8Hx3:-NOlGtdc55txOVWBsqU8:b-mo6vv2) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L430)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'd be fine w/ something like that!

I have a slight concern about initializing a view type with its own data by default, but that could be mitigated w/ state methods, such as
`MyNamedView.zeros()` or `MyNamedView.make(a=1, b=2)`

I'm concerned about constructing from a `dict`, because users may think it could be aliasing the entries from the dict. I don't believe it's trivial to try and make the `dict` values alias-able while also ensuring that `np.asarray(view)` aliases properly.

I can file an issue, if you'd like?
</blockquote></details>

The `.zeros()` sounds good to me, and it's like 5 lines.  I've just added it here.  PTAL.
___
*[`tutorials/authoring_leaf_systems.ipynb` line 365 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl-CDACYubO4myrHBW:-NOlBRrU9337rfu4GN_H:bn0ptci) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L365)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Ah, it was inspired more directly by `namedlist`: https://gitlab.com/ericvsmith/namedlist
See: https://drake.mit.edu/pydrake/pydrake.common.containers.html?highlight=namedview#pydrake.common.containers.namedview

But transitively, yes, inspired by `namedtuple` ;)
</blockquote></details>

the transitive all of the way to the most familiar is what I want.  
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl05kZ5aWVYl_XBFBi:-NOlBhpABM1d01v4KkqT:b5lrknx) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L367)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(I will include relevant info in above-mentioned doc-fix PR)
</blockquote></details>

i don't think we can recommend asarray for the continuous state?  The memory points to VectorBase, not BasicVector (because if we declared a second order system, the velocities are stored separately).  Recommending it here because we happen to not have second derivatives seems like a footgun to me?
___
*[`tutorials/authoring_leaf_systems.ipynb` line 410 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl09bTChkgnJeZMXWR:-NOlGHrZ0n_lIb1Q_X5t:bzgcejb) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L410)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Oh, please, let it be true. I had a similar thought but didn't follow up. Fingers crossed.
</blockquote></details>

sorry... despite the discussion in #18831, the [:] seems necessary here.  (if I remove it, I get
```
SetFromVector(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.systems.framework.ContinuousState_𝓣float𝓤, value: numpy.ndarray[numpy.float64[m, 1]]) -> None

Invoked with: <pydrake.systems.framework.ContinuousState_𝓣float𝓤 object at 0x7fac1c139eb0>, MyContinuousState(x=-0.5, z=-0.92, theta=2.068618659411898)
```
and similarly for the uses of [:] below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 430 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOUXVpR5x4hytfn8Hx3:-NOlSBwFBmhGK9GNKJoW:b8qb989) ([raw file](https://github.com/RobotLocomotion/drake/blob/60970ce505ce034bc346394b196db4c1bcb8ca9d/tutorials/authoring_leaf_systems.ipynb#L430)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The `.zeros()` sounds good to me, and it's like 5 lines.  I've just added it here.  PTAL.
</blockquote></details>

OK Looks good!
___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl05kZ5aWVYl_XBFBi:-NOlSFctC98IupOHds2D:bcx7aks) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L367)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i don't think we can recommend asarray for the continuous state?  The memory points to VectorBase, not BasicVector (because if we declared a second order system, the velocities are stored separately).  Recommending it here because we happen to not have second derivatives seems like a footgun to me?
</blockquote></details>

Sorry, not to say "try to alias original C++ memory", but rather "here's some inline of the nuance discussed in docs".

Perhaps a better question is - is it worth explicitly calling out the use of `[:]` and/or `np.asarray(...)` here?
The surrounding text does not mention it.

Maybe something to the tune of:

```
Note that usages of `my_view[:]` are meant as a shorthand to get a NumPy array view of the namedview itself.
For more details, see the example and warning in the documentation for `namedview` linked above.
```
___
*[`tutorials/authoring_leaf_systems.ipynb` line 410 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl09bTChkgnJeZMXWR:-NOlReZfCRwLHJdBzrSo:b-ymsi5a) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L410)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

sorry... despite the discussion in #18831, the [:] seems necessary here.  (if I remove it, I get
```
SetFromVector(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.systems.framework.ContinuousState_𝓣float𝓤, value: numpy.ndarray[numpy.float64[m, 1]]) -> None

Invoked with: <pydrake.systems.framework.ContinuousState_𝓣float𝓤 object at 0x7fac1c139eb0>, MyContinuousState(x=-0.5, z=-0.92, theta=2.068618659411898)
```
and similarly for the uses of [:] below.
</blockquote></details>

OK Gotcha.
Will file issue to either fix or justify why `pybind11` doesn't try `np.asarray` during conversion pass. I should add a unittest to illustrate this specifically.
___
*[`bindings/pydrake/common/test/containers_test.py` line 119 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOlS3lbB1o5SYF4SHsw:-NOlS3lc4WJgdAJBQJQA:b-584p1g) ([raw file](https://github.com/RobotLocomotion/drake/blob/b56dfe6c6924142413000e6e1e9ca52ed2563b6c/bindings/pydrake/common/test/containers_test.py#L119)):*
> ```Python
>     def test_zeros(self):
>         MyView = namedview("MyView", ["a", "b"])
>         view = MyView.zeros()
> ```

BTW This is more akin to `np.zeros()`. Alternatively, consider `.Zero()`, so it is closer to Eigen and things like `SpatialVector.Zero()`.
(Sorry for not mentioning that earlier!)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[`tutorials/authoring_leaf_systems.ipynb` line 367 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl05kZ5aWVYl_XBFBi:-NOlW4wD1SZtPWdtA46P:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L367)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry, not to say "try to alias original C++ memory", but rather "here's some inline of the nuance discussed in docs".

Perhaps a better question is - is it worth explicitly calling out the use of `[:]` and/or `np.asarray(...)` here?
The surrounding text does not mention it.

Maybe something to the tune of:

```
Note that usages of `my_view[:]` are meant as a shorthand to get a NumPy array view of the namedview itself.
For more details, see the example and warning in the documentation for `namedview` linked above.
```

</blockquote></details>

Done.
___
*[`tutorials/authoring_leaf_systems.ipynb` line 410 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOl09bTChkgnJeZMXWR:-NOlWDi0BFkl1g2kw90Q:b-ucfkn4) ([raw file](https://github.com/RobotLocomotion/drake/blob/eef024d871c9d5ca853211d38a5aadb249cd43bf/tutorials/authoring_leaf_systems.ipynb#L410)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Gotcha.
Will file issue to either fix or justify why `pybind11` doesn't try `np.asarray` during conversion pass. I should add a unittest to illustrate this specifically.
</blockquote></details>

Thanks.
___
*[`bindings/pydrake/common/test/containers_test.py` line 119 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18809#-NOlS3lbB1o5SYF4SHsw:-NOlVayZ0AHblN3YXB0G:bfsog5b) ([raw file](https://github.com/RobotLocomotion/drake/blob/b56dfe6c6924142413000e6e1e9ca52ed2563b6c/bindings/pydrake/common/test/containers_test.py#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This is more akin to `np.zeros()`. Alternatively, consider `.Zero()`, so it is closer to Eigen and things like `SpatialVector.Zero()`.
(Sorry for not mentioning that earlier!)
</blockquote></details>

Done. `.Zero()` it is.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18809)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
Reminder for the release notes manager: a notable "release notes: fix" item here was: "Fix DiscreteValues::get_mutable_value to allow mutation".  We'll need to insert that into the notes manually; it didn't make it into the commit message.

**Comment by RussTedrake** [comment]
i actually did put it in the commit message.

**Comment by jwnimmer-tri** [comment]
Yup, but Sean's merge lost it for whatever reason.

**Comment by SeanCurtis-TRI** [comment]
Blast! The one time I don't look at reviewable's window when I merged.  :-P That's why I should never yield my distrust.

**Comment by RussTedrake** [comment]
Just so I understand, how can that happen?  Was it not merged via github/reviewable?

**Comment by jwnimmer-tri** [comment]
If Sean didn't do it on purpose, then it's a reviewable bug:
https://github.com/Reviewable/Reviewable/issues/1009

**Pull request merged**
