### PR TITLE
Remove compatibility shims for Focal

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This reverts commit 6b32a81c.

No release notes.  We'll use #20952 to announce this change, overall.

See also #20970 for one more C++20-related cleanup.

Requires:
- [x] #20954
- [x] #20961

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20965)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20965)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Even though this won't pass CI until the CI config changes, I think the code here is finished so we can kick off the review.

+@ggould-tri for both reviews per schedule (Tuesday), please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20965)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: in anticipation of the CI change.

> Reviewed 26 of 28 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20965#-:-Nr0srqD0lWiEFk_uSMN:bvmer1x)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20965#-Nr0sXjOClfkUuk7hAOj:-Nr0sXjOClfkUuk7hAOk:b68x7y5) (no related file):*
BTW, the other idiom to kill off when we drop C++17 support is uses of `if (foo.count(bar))`/`if (foo.count(bar) > 0)` since we now get the more readable `foo.contains(bar)`.
Definitely a followup-PR kind of thing.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20965)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20965#-Nr0sXjOClfkUuk7hAOj:-Nr1lXKz9U4x93sUfitP:bd0o87) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW, the other idiom to kill off when we drop C++17 support is uses of `if (foo.count(bar))`/`if (foo.count(bar) > 0)` since we now get the more readable `foo.contains(bar)`.
Definitely a followup-PR kind of thing.
</blockquote></details>

Good reminder!  I put it on my personal TODO list.

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
