### PR TITLE
Upgrade externals to latest releases (Feb 2022)

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Working towards #16481

The changes to scs are from the PR [Under the hood API refactoring](https://github.com/cvxgrp/scs/pull/197). Specifically, see [glbopts.h](https://github.com/cvxgrp/scs/blob/cd4028d024972876883ed3b187076c8ef94062cb/include/glbopts.h#L12)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Looks like `uWebsockets` started using `std::from_chars` from `<charconv>` to parse Apple user-agents (https://github.com/uNetworking/uWebSockets/commit/89ea606da99a621e61fd504f8c6278819eb4702c), but our GCC 7 on Ubuntu 18 doesn't offer that header.

**Review by sherm1 — COMMENTED** [review]
Is this ready for feature review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484#-:-MuspoDJEaAPETHLrQCS:b-deb1wo)* status: needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes

**Review by BetsyMcPhail — COMMENTED** [review]
CI is happy so we're ready for review. +@jwnimmer-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484#-:-MuvMayG9N4ZhTxQFdxC:b-v3yyk2)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) LGTM so far.

Once the next change is pushed, please also launch a macOS CI build.  Then we should be OK to merge.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484#-:-MuvPg0H2kCb1gPPrwqI:b5r48ej)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @BetsyMcPhail)

___
*[solvers/scs_solver.cc, line 729 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16484#-MuvPLLN0Q5z-G9KC8q8:-MuvPLLN0Q5z-G9KC8q9:b-921vn5) ([raw file](https://github.com/robotlocomotion/drake/blob/f362cb293f5e69b87c47e669c5a73683f1000777/solvers/scs_solver.cc#L729)):*
> ```cpp
>   // their instantiated members) upon return from the DoSolve function.
>   ScopeExit scs_free_guard([&cone, &scs_problem_data, &scs_stgs]() {
>     _scs_free_data(scs_problem_data, cone, scs_stgs);
> ```

These changes are curated into the Xacro commit.  They should be part of the SCS commit, instead.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/scs_solver.cc, line 729 at r9](https://reviewable.io/reviews/robotlocomotion/drake/16484#-MuvPLLN0Q5z-G9KC8q8:-MuvRYUs5gdJ84wCux0V:b-qu8hpd) ([raw file](https://github.com/robotlocomotion/drake/blob/f362cb293f5e69b87c47e669c5a73683f1000777/solvers/scs_solver.cc#L729)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These changes are curated into the Xacro commit.  They should be part of the SCS commit, instead.
</blockquote></details>

Good catch - thanks

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews.

Both macOS builds have passed, so the only thing remaining on this PR is to play the rebase game to reach the tip of master before merging.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484#-:-MuvtBkVC0nH72ee4fZn:boepscn)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
Rebase is done... I don't have permissions to force merge without waiting for tests

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16484#-:-MuvvvU-EeCgh_QyvNKz:b-ocu76x)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), base commit is latest master (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
I'll force the merge as soon as one of the bazel builds passes.

**Pull request merged**
