### PR TITLE
[models] Delete robot descriptions that now live in drake_models

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #13942.

Follow-up from #21218.

Anzu CI has been checked and passed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both (?) reviews per schedule (tomorrow), please.

If there are parts that seem like they deserve a second reviewer, or separate feature reviewers, just let me know.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`manipulation/models/jaco_description/README.md` line 0 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-NuVOxa1BsuQc-z5M9iG:-NuVOxa1BsuQc-z5M9iH:bwlq34k) ([raw file](https://github.com/RobotLocomotion/drake/blob/95677a883039ae04192ad070bf14a36d722bfa72/manipulation/models/jaco_description/README.md#L0)):*
FYI This PR purposely doesn't delete two of the files here.  Those are tracked under #21216.

**Review by xuchenhan-tri — COMMENTED** [review]
FYI, I probably won't be able to get to it until tomorrow. I have back-to-back meetings all day today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-:-NuVPvEw19KIZR4XqWtx:b-47m7l1)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
No problem, thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
checkpoint for my sanity.

> Reviewed 100 of 172 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-:-NuX2w9S9_ng_KpOnaVt:b8q6e1i)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`examples/manipulation_station/BUILD.bazel` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-NuX1hpT69Qg6SI3hGSt:-NuX1hpT69Qg6SI3hGSu:bptacmv) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebfd700002b905368298bb27e1100a1c20e26847/examples/manipulation_station/BUILD.bazel#L35)):*
> ```Starlark
>         # anymore, but removing them breaks too many other things. We'll
>         # revisit this later when we finally delete these paths entirely.
>         "//manipulation/models/iiwa_description:models",
> ```

BTW, I want to make sure that we can properly delete these now because they are already included in `@drake_models://wsg_50_description` and `@drake_models:iiwa_description`, right?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`examples/manipulation_station/BUILD.bazel` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-NuX1hpT69Qg6SI3hGSt:-NuX3KV01qGbE2-IHtnj:bz89lot) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebfd700002b905368298bb27e1100a1c20e26847/examples/manipulation_station/BUILD.bazel#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I want to make sure that we can properly delete these now because they are already included in `@drake_models://wsg_50_description` and `@drake_models:iiwa_description`, right?
</blockquote></details>

It's slightly more nuanced than that.

For the purposes of all of the code in this directory, the pre-existing `"@drake_models//:iiwa_description",` item (about 6 lines prior) was already sufficient -- both on master, and in this PR.

The problem (prior to this PR) was that other code that transitively depended on the manipulation station library code was relying on the manipulation station to declare `"//manipulation/models/iiwa_description:models"` as a data dep.  Code in other packages wasn't doing "DWYU" correctly.  Trying to fix that in prior PRs was too much of a headache, especially because there used to be circular model file dependencies until #21241 landed.

Now that this PR finally adjusts all of the data paths project-wide to be correct and precise, we don't need this little hack anymore.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`examples/manipulation_station/BUILD.bazel` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-NuX1hpT69Qg6SI3hGSt:-NuXEelAB6TYnD7RdCWQ:b-wdj8zi) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebfd700002b905368298bb27e1100a1c20e26847/examples/manipulation_station/BUILD.bazel#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's slightly more nuanced than that.

For the purposes of all of the code in this directory, the pre-existing `"@drake_models//:iiwa_description",` item (about 6 lines prior) was already sufficient -- both on master, and in this PR.

The problem (prior to this PR) was that other code that transitively depended on the manipulation station library code was relying on the manipulation station to declare `"//manipulation/models/iiwa_description:models"` as a data dep.  Code in other packages wasn't doing "DWYU" correctly.  Trying to fix that in prior PRs was too much of a headache, especially because there used to be circular model file dependencies until #21241 landed.

Now that this PR finally adjusts all of the data paths project-wide to be correct and precise, we don't need this little hack anymore.
</blockquote></details>

Nice, thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2

> Reviewed 72 of 172 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-:-NuZqJeMBUCv_TP2uGad:bks4n6x)* status: 1 unresolved discussion

___
*[`bindings/pydrake/examples/test/manipulation_station_test.py` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-NuZobVM-htIlj0KZObk:-NuZobVM-htIlj0KZObl:b-ejfkef) ([raw file](https://github.com/RobotLocomotion/drake/blob/95677a883039ae04192ad070bf14a36d722bfa72/bindings/pydrake/examples/test/manipulation_station_test.py#L5)):*
> ```Python
> import numpy as np
> 
> from pydrake.common import FindResourceOrThrow
> ```

nit, no longer needed.

**Review by jwnimmer-tri — COMMENTED** [review]
Thanks for the slog.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21243#-:-Nu_MzgL4nlwMFxri0Lw:b56kfdx)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
