### PR TITLE
Add DRAKE_ASSERT statements to ensure programs being solved in parallel are actually threadsafe.

### PR DESCRIPTION
**Pull request by cohnt**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228)

### CODE REVIEW

**Comment by cohnt** [comment]
We recently added a couple pieces of code where we solve mathematical programs in parallel, without actually asserting that they're thread-safe. This isn't a problem, since they are thread-safe, but if someone changes these programs down the line and inadvertently makes them not-thread-safe, it could lead to very confusing errors.

+@alexandreamice for feature review on this one?

**Review by AlexandreAmice — COMMENTED** [review]
You want to put the asserts right before solve. 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-:-OCFvV3f0k9oA-ZzPf1i:b-4pcpcu)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/convex_set.cc` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-OCFunLCDg5HRBOEhSEO:-OCFunLD5iLkV5QncTJr:b-ppu2ni) ([raw file](https://github.com/RobotLocomotion/drake/blob/b17a567586f3dbb246d5059889ca101a76cea24a/geometry/optimization/convex_set.cc#L123)):*
> ```cpp
>   for (int i = 0; i < ssize(progs); ++i) {
>     ConstructEmptyBoundednessProgram(&(progs[i]), s);
>     DRAKE_ASSERT(progs[i].IsThreadSafe());
> ```

No need for this one here. Only need to check before calling solve
___
*[`geometry/optimization/convex_set.cc` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-OCFvRBT0V_e1Q5U5BeM:-OCFvRBUBsvjnq8FYBMI:bwrd15k) ([raw file](https://github.com/RobotLocomotion/drake/blob/b17a567586f3dbb246d5059889ca101a76cea24a/geometry/optimization/convex_set.cc#L161)):*
> ```cpp
>     progs[thread_num].linear_costs()[0].evaluator()->update_coefficient_entry(
>         dimension, maximize ? -1 : 1);
>     solver_interfaces[thread_num]->Solve(progs[thread_num], std::nullopt,
> ```

Put the asserts before `Solve`

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/optimization/convex_set.cc` line 123 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-OCFunLCDg5HRBOEhSEO:-OCFwxpK8RN0AE60xkC_:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b17a567586f3dbb246d5059889ca101a76cea24a/geometry/optimization/convex_set.cc#L123)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

No need for this one here. Only need to check before calling solve
</blockquote></details>

Done.
___
*[`geometry/optimization/convex_set.cc` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-OCFvRBT0V_e1Q5U5BeM:-OCFwyR23tplWLFiLFAy:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b17a567586f3dbb246d5059889ca101a76cea24a/geometry/optimization/convex_set.cc#L161)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Put the asserts before `Solve`
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-:-OCVaYBB0LJGFMtDhCu9:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
+@ggould-tri for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-:-OCd02M7D7c-mwUCGrIn:b-y7xxy6)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: ; thanks!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22228#-:-OCd3YkJD9BaCQ3pZm5q:bgzwoow)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
