### PR TITLE
Fix cpplint build/header_guard

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix cpplint build/header_guard, again.  (Somehow my PR #1949 left the suppression in place, likely due to a merge error on my part.)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@maddog-tri One more simple review?

**Comment by maddog-tri** [comment]
:thumbs-up: - neither defects nor suggestions.

**Comment by jwnimmer-tri** [comment]
@david-german-tri Ready to merge.  The windows builds were SUCCESS and then went red due to some kind of results upload exception.

**Comment by david-german-tri** [comment]
Right, that's a known issue - @jamiesnape attributes it to a flaky MSFT-specific protocol.

**Pull request merged**
