### PR TITLE
Revert "parsing: Add support for SDFormat 1.8 model composition"

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Reverts RobotLocomotion/drake#14401.

It seems like this change introduces additional frame frame names into the world model instance (and elsewhere), which may unexpectedly conflict with existing frame names.  It seems safest to revert the new feature while we explore further.

\CC @azeey @EricCousineau-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15079)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Personally disprefer revert, but totes understand on more time for fixing.
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15079#-:-MaV-jQm562BCBy98XJS:bpwg2r7)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15079#-:-MaV-p927Gg2q9JN7aXq:b7dr7wo)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
(Unfortunately all of the nice unrelated TODOs were in the same commit, so those are going away as well.)

**Comment by EricCousineau-TRI** [comment]
Aye; Addisu and I will file a chaser PR to restore / provide basis for discussion and all that.

**Pull request merged**
