### PR TITLE
add EvalAbstractInput to system.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3670)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 499 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGD_euU8c0cnPfQx8O:-KTGD_euU8c0cnPfQx8P:bpnuigh) ([raw file](https://github.com/robotlocomotion/drake/blob/fc4634b55c7a95858543b0f5c14c37bcd942d894/drake/systems/framework/system.h#L499)):*
> ```objc
>   /// the port's abstract value pointer, or nullptr if the port is not
>   /// connected.
>   const AbstractValue* EvalAbstractInput(const Context<T>& context,
> ```

META x2: please add unit test coverage for both these new functions.

---

*[drake/systems/framework/system.h, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGDYB98-Ss7O13T8Ue:-KTGDYB98-Ss7O13T8Uf:b-60km0o) ([raw file](https://github.com/robotlocomotion/drake/blob/fc4634b55c7a95858543b0f5c14c37bcd942d894/drake/systems/framework/system.h#L508)):*
> ```objc
>   /// up-to-date, delegating to our parent Diagram if necessary. Returns
>   /// the port's abstract value, or nullptr if the port is not connected.
>   template <typename V>
> ```

Please document the template parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3670)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 499 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGD_euU8c0cnPfQx8O:-KTGuqs6myqqcyXoqt4D:bklw5j7) ([raw file](https://github.com/robotlocomotion/drake/blob/fc4634b55c7a95858543b0f5c14c37bcd942d894/drake/systems/framework/system.h#L499)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> META x2: please add unit test coverage for both these new functions.
</details>
added a test, please take a look.

---

*[drake/systems/framework/system.h, line 508 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGDYB98-Ss7O13T8Ue:-KTGuwQulCirVATUXJxE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fc4634b55c7a95858543b0f5c14c37bcd942d894/drake/systems/framework/system.h#L508)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please document the template parameter.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3670)*

**Comment by david-german-tri** [comment]
:lgtm: Awesome, thanks very much.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/test/system_test.cc, line 210 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGvq2Ct8BuW3Y4XuzP:-KTGvq2DLrO-KHOXGnD0:bhxibv8) ([raw file](https://github.com/robotlocomotion/drake/blob/7a9a994b318c4f7262d5ab6ca692765d19a2e6a1/drake/systems/framework/test/system_test.cc#L210)):*
> ```cpp
> 
> // A shell System for AbstractValue IO test
> class ValueIOTestSystem : public System<double> {
> ```

BTW, you could inherit from LeafSystem and get some of the implementation here for free.

---

*[drake/systems/framework/test/system_test.cc, line 294 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGw2JcivzVTFFXsbSA:-KTGw2JcivzVTFFXsbSB:b4aevxn) ([raw file](https://github.com/robotlocomotion/drake/blob/7a9a994b318c4f7262d5ab6ca692765d19a2e6a1/drake/systems/framework/test/system_test.cc#L294)):*
> ```cpp
>   EXPECT_EQ(output->get_num_ports(), 2);
> 
>   EXPECT_EQ(output->get_data(0)->GetValue<std::string>().compare("inputoutput"),
> ```

You can just EXPECT_EQ on the two strings directly, no need for `.compare`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-:-KTGw8tFgoqnvO1yDK7B:b7r3teu)*

**Comment by siyuanfeng-tri** [comment]
thanks

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/test/system_test.cc, line 210 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGvq2Ct8BuW3Y4XuzP:-KTHEPUWyJ9OpPFeGUMP:bobtaaw) ([raw file](https://github.com/robotlocomotion/drake/blob/7a9a994b318c4f7262d5ab6ca692765d19a2e6a1/drake/systems/framework/test/system_test.cc#L210)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, you could inherit from LeafSystem and get some of the implementation here for free.
</details>
yeah. I was thinking about it, but wanted to keep things flat. 

---

*[drake/systems/framework/test/system_test.cc, line 294 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-KTGw2JcivzVTFFXsbSA:-KTH9cmZapbjB7DmSQbx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a9a994b318c4f7262d5ab6ca692765d19a2e6a1/drake/systems/framework/test/system_test.cc#L294)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> You can just EXPECT_EQ on the two strings directly, no need for `.compare`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3670#-:-KTHEZBQbmCAwCQwMg29:b-k73z76)*

**Pull request merged**
