### PR TITLE
Disable Appveyor and Travis CI Linux builds

### PR DESCRIPTION
**Pull request by jamiesnape**
Per discussion in the meeting earlier. These builds are subsumed by the Jenkins builds. There is strong possibility that the Appveyor build of this PR will fail, but other builds are expected to pass.

@RussTedrake PTAL.

### CODE REVIEW

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
Since the rebase removed the conversation thread: The old versions of the files will always be in the git history, so there is no reason to leave stale files or comment out code.

**Comment by RussTedrake** [comment]
yes.  i agree with your comments.

**Comment by RussTedrake** [comment]
@jamiesnape -- am concerned that appveyor is still catching things that jenkins is not.  perhaps we should leave appveyor up until that is resolved?

**Comment by jamiesnape** [comment]
Sure. We can leave this open and/or I can split off the Travis CI changes. Whichever you prefer.

**Comment by billhoffman** [comment]
I am thinking that we need to downgrade CMake on some of the Amazon machines.  I think that is where we are seeing differences now.

**Comment by RussTedrake** [comment]
sounds good. we’ll eventually want to have the minimum required version of
matlab, etc on the build servers, too.

**Comment by jamiesnape** [comment]
We need a higher version than the minimum of CMake on the build servers to support various CDash features and code analysis tools.

**Comment by RussTedrake** [comment]
it does seem like jenkins is now failing on the expected test... at least sometimes (it's more random than I hoped).  i will watch incoming PRs for another day or two, then pull the trigger on this.

**Comment by RussTedrake** [comment]
appveyor failed, yet again, on something flakey, in #1857.  anyone object to me merging this?

**Comment by jamiesnape** [comment]
I have no objections.

**Comment by jhoare** [comment]
Appveyor failure appears to be due to a broken chocolaty installer. If you'd like I can switch it back to download the s3 hosted binaries that we were using before I changed to using chocolaty.

**Comment by RussTedrake** [comment]
@jhoare -- no need.  let's focus our efforts on jenkins.  i will disable appveyor.

**Pull request merged**
