### PR TITLE
[workspace] Upgrade meshcat_python to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Tested locally via `/bazel-bin/manipulation/util/show_model         --meshcat default         --find_resource         drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15296)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15296#-:-MdY_Gbh24b19Aqab8_E:b4xzgsb)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15296#-MdY_Kk9121tZ5cW5cu3:-MdY_Kk9121tZ5cW5cu4:bgpre5f) (no related file):*
Working: Briefly repeating local test.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15296)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15296#-MdY_Kk9121tZ5cW5cu3:-MdYafCy4VhkLQcATxzw:b7yfj18) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Briefly repeating local test.
</blockquote></details>

OK Locally confirmed that nothing seems unexpected / out of place!

---

**Pull request merged**
