### PR TITLE
Follow PEP 394 now that Homebrew (supposedly) does

### LINKED ISSUE #8231: homebrew python3 issues
#8228 fixes some problems but we still have other issues. I've only tested `bindings/pydrake` but I found that the following tests failed:

```
//bindings/pydrake/util:_isolated/cpp_param_pybind_test                  FAILED in 0.5s
//bindings/pydrake/util:_isolated/cpp_template_pybind_test               FAILED in 0.3s
//bindings/pydrake/util:cpp_param_pybind_test                            FAILED in 0.5s
//bindings/pydrake/util:cpp_template_pybind_test                         FAILED in 0.3s
```

Here is a snippet of an error message:

```
==================== Test output for //bindings/pydrake/util:_isolated/cpp_template_pybind_test:
[ RUN      ] CppTemplateTest.TemplateClass
unknown file: Failure
C++ exception with description "ImportError: dlopen(/usr/local/opt/python2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so, 2): Symbol not found: __PySlice_AdjustIndices
  Referenced from: /usr/local/opt/python2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
  Expected in: flat namespace
 in /usr/local/opt/python2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
```

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #8231.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8340)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
+@soonho-tri for feature-review.

---

Reviewed 12 of 33 files at r1.
Review status: 12 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8340#-:-L7Pxbcu2W1OBeXgrm_g:bv8csgy)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 21 of 33 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8340#-:-L7PzscYw75nxV_p2ZiI:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 32 of 33 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8340#-:-L7QDm2vMxFr1EY3EJxt:bnfp4nl)*

**Pull request merged**
