### PR TITLE
Design StateUpdater class and FemModel class

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
See the more detailed design doc [here](https://docs.google.com/document/d/1RqeR-K2_TKaxEp9e7_qSykL6QWN6bI2tHxZ1BL7v5ao/edit?ts=5fdae31b). 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for a design review please, thank you.

This is an experiment to do a design review with Reviewable before fully committing to the design. The hope is to resolve design-level discussions before implementing the details. Anyone who feels like providing some feedback either on the mechanism or the specific design in this PR is welcome to do so.

Tagging @amcastro-tri , @seancurtis-tri , @rpoyner-tri, @jwnimmer-tri who may be interested in lending their opinions.  Feedback is much appreciated but not required, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MR3SIoE-i3ygqLdXpYa:b-7l7ukw)* status: LGTM missing from assignee sherm1(platform), labeled "do not merge" (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
These classes look fine but are out of context so it's hard to tell if they serve their intended purpose. It would be helpful to see how they are supposed to be used.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRW2r8h5XH12XODh8_n:b6gcfye)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW23sh8tBUsPQTRZr6:-MRW23si6Krv75lFEZ9W:b3j9k5d) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/newmark_scheme.h#L11)):*
> ```objc
> /* Implements the interface StateUpdater with Newmark-beta time integration
>  scheme. The states are updated according to the following equation:
>             v = vₙ + dt ⋅ (γ ⋅ aₙ + (1−γ) ⋅ a)
> ```

BTW are aₙ and a reversed here? Doesn't change anything with γ=0.5 but the convention seems opposite the one for x on the next line (and [Wikipedia's version](https://en.wikipedia.org/wiki/Newmark-beta_method)).
___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW2RDy4ioOFhPXwZqr:-MRW2RDy4ioOFhPXwZqs:bek2kd) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/newmark_scheme.h#L47)):*
> ```objc
>     const VectorX<T>& an = state->qddot();
>     const VectorX<T>& vn = state->qdot();
>     state->set_q(state()->q() + dt * vn + dt_sqrt * (an + beta_ * dz));
> ```

Won't compile.
___
*[multibody/fixed_fem/dev/state_updater.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW-GW563sCF67Ud-ws:-MRW-GW563sCF67Ud-wt:boel40) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/state_updater.h#L34)):*
> ```objc
>  the solution of the linear solve, `dz`. In addition, %StateUpdater also
>  provides the derivatives of the states with respect to the key variable `z`,
>  namely, `dq/dz`,  `dq̇/dz`, and `dq̈/dz`, that are needed for building ∇G.
> ```

nit: shouldn't these be partial derivatives?

**Review by xuchenhan-tri — COMMENTED** [review]
@sherm1 I added the implementation and unit tests for FemModel and StateUpdater. Please take a look, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRbfpP3AIte6t2VsvS4:btnf6ed)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW23sh8tBUsPQTRZr6:-MRbfMrhDH0S7hCNd_NI:b-jki99t) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/newmark_scheme.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW are aₙ and a reversed here? Doesn't change anything with γ=0.5 but the convention seems opposite the one for x on the next line (and [Wikipedia's version](https://en.wikipedia.org/wiki/Newmark-beta_method)).
</blockquote></details>

Yes! Thanks for catching that. I decided not to include Newmark scheme in this PR to keep the LOC manageable. It should be fixed by the time it gets PR'ed.
___
*[multibody/fixed_fem/dev/newmark_scheme.h, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW2RDy4ioOFhPXwZqr:-MRbfBlS4jq_ymuPOO77:bv7h37o) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/newmark_scheme.h#L47)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Won't compile.
</blockquote></details>

Will be fixed when we PR Newmark Scheme.
___
*[multibody/fixed_fem/dev/state_updater.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRW-GW563sCF67Ud-ws:-MRbfj7t0pmWfOCBv6H7:b-ftjk9v) ([raw file](https://github.com/robotlocomotion/drake/blob/8c504c5a2f85c6160c8c97f41501e73c59858e3f/multibody/fixed_fem/dev/state_updater.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: shouldn't these be partial derivatives?
</blockquote></details>


Done, thanks!

**Review by sherm1 — COMMENTED** [review]
Checkpoint.

> Reviewed 4 of 13 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRu_rzN3lRC-GvbQaN2:by96gdd)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRuYOzb4gajY6FbOa3i:-MRuYOzb4gajY6FbOa3j:bu156lt) ([raw file](https://github.com/robotlocomotion/drake/blob/f74738fd0d13cf12d565e55452d1ef2bc4231e3c/multibody/fixed_fem/dev/fem_model.h#L139)):*
> ```objc
>                                                              k);
>            it; ++it) {
>         it.valueRef() = 0.0;
> ```

BTW I'd be surprised if Eigen doesn't provide a tidier way to zero a sparse matrix, like `Eigen::SparseMatrix<T>::Zero` or the [`setZero()`](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#ad3c7416090f913e8685523cb3ab7c2f7) method. Have you checked that there isn't one that serves your purpose here? 
___
*[multibody/fixed_fem/dev/fem_model.h, line 259 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRu_8e50ASUQNF8ItcA:-MRu_8e50ASUQNF8ItcB:b-etsihg) ([raw file](https://github.com/robotlocomotion/drake/blob/f74738fd0d13cf12d565e55452d1ef2bc4231e3c/multibody/fixed_fem/dev/fem_model.h#L259)):*
> ```objc
>     if constexpr (FemState<Element>::ode_order() == 0) {
>       return state_derivatives[0] * stiffness_matrix;
>     } else {
> ```

BTW when a normal `if` condition block ends in return you can avoid hard-to-read nesting if if/else/else/etc because the else's are not needed. I _think_ that would also work fine here for `if constexpr` -- that might make this more readable also.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/fem_model.h, line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRuYOzb4gajY6FbOa3i:-MRvoVuE9-Jhh-TP_JM7:b-4woz6f) ([raw file](https://github.com/robotlocomotion/drake/blob/f74738fd0d13cf12d565e55452d1ef2bc4231e3c/multibody/fixed_fem/dev/fem_model.h#L139)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'd be surprised if Eigen doesn't provide a tidier way to zero a sparse matrix, like `Eigen::SparseMatrix<T>::Zero` or the [`setZero()`](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#ad3c7416090f913e8685523cb3ab7c2f7) method. Have you checked that there isn't one that serves your purpose here? 
</blockquote></details>

I was under the impression that `SparseMatrix::setZero()` deallocates memory. But apparently I was wrong as by Eigen's [documentation](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#title38) clearly states otherwise.
Done.
___
*[multibody/fixed_fem/dev/fem_model.h, line 259 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRu_8e50ASUQNF8ItcA:-MRvoLuh7pt5k--I6fIG:b-lzdmll) ([raw file](https://github.com/robotlocomotion/drake/blob/f74738fd0d13cf12d565e55452d1ef2bc4231e3c/multibody/fixed_fem/dev/fem_model.h#L259)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW when a normal `if` condition block ends in return you can avoid hard-to-read nesting if if/else/else/etc because the else's are not needed. I _think_ that would also work fine here for `if constexpr` -- that might make this more readable also.
</blockquote></details>

Yes, you are right, thanks! Done.

**Review by sherm1 — COMMENTED** [review]
Looks good. My only substantive question is about the virtuals in StateUpdater, PTAL.

> Reviewed 7 of 13 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRvzG2NEvHHCetpQWcS:b4evaw4)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/state_updater.h, line 46 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRvvxTP7BzoUI7kZJl_:-MRvvxTP7BzoUI7kZJla:b804hqv) ([raw file](https://github.com/robotlocomotion/drake/blob/497008bf009ea52def99d193f4d38f3724b1874d/multibody/fixed_fem/dev/state_updater.h#L46)):*
> ```objc
>    [∂q/∂z, ∂q̇/∂z, ∂q̈/∂z]. If q̇ or q̈ are not a part of the state, their
>    derivatives are set to 0.  */
>   virtual Vector3<T> state_derivatives() const = 0;
> ```

This looks like it would require a per-element virtual function call. I was expecting those all to be gone with the heavily-templatized design. Is there a reason why this is virtual rather than part of the templatized architecture?

**Review by xuchenhan-tri — COMMENTED** [review]
Good catch! I was a little sloppy and let the "virtualness" bleed into the element level. This should be fixed by the latest revision.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRw3HsAEnRX3oeA8HMN:b-cz4sng)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/state_updater.h, line 46 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRvvxTP7BzoUI7kZJl_:-MRw3gK53dbHS8rBeNtn:bmlq9qy) ([raw file](https://github.com/robotlocomotion/drake/blob/497008bf009ea52def99d193f4d38f3724b1874d/multibody/fixed_fem/dev/state_updater.h#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This looks like it would require a per-element virtual function call. I was expecting those all to be gone with the heavily-templatized design. Is there a reason why this is virtual rather than part of the templatized architecture?
</blockquote></details>

This "virtualness" should not reach the element level. It should only stay at the FemModel level instead. My previous implementation was sloppy but the issue should be fixed now, PTAL, thank you!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/fem_model.h, line 241 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRwstOX4Ju2w6C8siZV:-MRwstOY6IQBRf5AvUXt:b-8e5kfx) ([raw file](https://github.com/robotlocomotion/drake/blob/78038bcf8c6aff3be08b8d232aee4b9bf228da26/multibody/fixed_fem/dev/fem_model.h#L241)):*
> ```objc
>    @param[in] state    The FemState to evaluate the residual at.
>    @param[in] state_derivatives    The derivatives of the states with respect to
>    the key variable `z`, namely, `∂q/∂z`,  `∂q̇/∂z`, and `∂q̈/∂z`.
> ```

I'm confused by this variable. It is only a Vector3, yet claims to be the derivatives of q which is (to my understanding) not a scalar. And two lines above these 3 numbers are described as "weights". Also state_derivatives appears to have the same value for all elements, which might make sense for weights but not for derivatives. Can you clarify this for me?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/fem_model.h, line 241 at r5](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRwstOX4Ju2w6C8siZV:-MRx0Xp87WjoXAYSU5GO:b12lg1u) ([raw file](https://github.com/robotlocomotion/drake/blob/78038bcf8c6aff3be08b8d232aee4b9bf228da26/multibody/fixed_fem/dev/fem_model.h#L241)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm confused by this variable. It is only a Vector3, yet claims to be the derivatives of q which is (to my understanding) not a scalar. And two lines above these 3 numbers are described as "weights". Also state_derivatives appears to have the same value for all elements, which might make sense for weights but not for derivatives. Can you clarify this for me?
</blockquote></details>

I can see the source of confusion. I removed the notion of `StateUpdater` from `FemModel` completely in hope of alleviating that confusion. As the new name suggests, the variable you are referring to serves as the weights used to combine stiffness/damping/mass matrices. 

As for the dimension of the "derivatives": it really should be described as the derivative of `q` (for example) of a particular dof  (a scalar) w.r.t the variable `z` evaluated at a particular dof (scalar), instead of the derivative of the entire state `q`. If all dofs are advanced with the same time-stepping scheme, then that derivative is the same for all elements.  I agree that the name of the variable is confusing at best and thus the name change.

**Review by sherm1 — COMMENTED** [review]
Great, thanks -- now it makes sense! 
I see the StateUpdater is still in this PR and used in one spot -- that's still a mystery to me.

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRze0bpBCeT60JQGWC2:bj1uk55)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, line 113 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRzdr8P5PbdWFEaT3Wd:-MRzdr8P5PbdWFEaT3We:b-h8bhwg) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f945c39e6b72b43da8ffb42a24d3c5125a4c21/multibody/fixed_fem/dev/test/static_elasticity_model_test.cc#L113)):*
> ```cpp
>   ZerothOrderStateUpdater<FemState<ElementType>> state_updater;
>   model_.CalcTangentMatrix(state, state_updater.state_derivatives(),
>                            &tangent_matrix);
> ```

This still says "state derivatives" -- please make it say "weights" instead!

**Review by xuchenhan-tri — COMMENTED** [review]
I believe you meant "state_derivatives" instead of "StateUpdater", and I made changes accordingly.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MRzs5pnB1wXe_AsQvKl:bhuoeb8)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, line 113 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRzdr8P5PbdWFEaT3Wd:-MRztKRPBWBFe2fw72p8:bnyr1zt) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f945c39e6b72b43da8ffb42a24d3c5125a4c21/multibody/fixed_fem/dev/test/static_elasticity_model_test.cc#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This still says "state derivatives" -- please make it say "weights" instead!
</blockquote></details>

Sorry that I misunderstood before. I thought the comment was on the API of `FemModel` not on the API of `StateUpdater`. 

I made some changes so that `state_derivatives()` are completely erased in favor of `weights()`.

**Review by sherm1 — COMMENTED** [review]
Well I did mean StateUpdater because I didn't understand what it was doing due to my confusion between actual state derivatives and the relationship between the chosen independent variable z and the states to be updated. I believe I've got the picture now; the changes you made helped a lot. Some comments below.

Design :lgtm:

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MS0Dcu25y0r9iVtPWuo:b-sbh7bx)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/state_updater.h, line 44 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MS0Ak_48kb4ZxBbbsa9:-MS0Ak_48kb4ZxBbbsaA:b8s72ur) ([raw file](https://github.com/robotlocomotion/drake/blob/93a5ec6e25231a828796297a9caaed8ce63ac39d/multibody/fixed_fem/dev/state_updater.h#L44)):*
> ```objc
> 
>   /** Returns the derivative of the state with respect to the key variable `z`,
>    [∂q/∂z, ∂q̇/∂z, ∂q̈/∂z], for a single degree of freedom. The derivatives can be
> ```

I still find this wording confusing. Would it make sense here to say that this is for a "representative" degree of freedom and the derivative w.r.t. z is the same for all dofs in the same model?
___
*[multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, line 113 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRzdr8P5PbdWFEaT3Wd:-MS0BYih7T-RAKdXFOHH:b-n41kgv) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f945c39e6b72b43da8ffb42a24d3c5125a4c21/multibody/fixed_fem/dev/test/static_elasticity_model_test.cc#L113)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Sorry that I misunderstood before. I thought the comment was on the API of `FemModel` not on the API of `StateUpdater`. 

I made some changes so that `state_derivatives()` are completely erased in favor of `weights()`.
</blockquote></details>

I think I understand now why you originally called those "derivatives" but I found that very confusing due to all the other derivatives in the overall problem. Now I see these just capture the relationship between the q, qdot, and qdotdot quantities and the independent variable z. I think `weights` is an improvement over the confusing state_derivatives, although it doesn't quite capture the concept, which I'm now thinking of as `relation_between_states_and_z` or `dependence_of_states_on_z`. I think it's OK as is but I'd like to see a comment, maybe in StateUpdater::weights(), that would explain the meaning better.

**Review by xuchenhan-tri — COMMENTED** [review]
I see, sorry for the confusion. I have added some more comment and hopefully it's more clear now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535#-:-MS0If493dm_JO9gBIXy:b-546nnf)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[multibody/fixed_fem/dev/state_updater.h, line 44 at r7](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MS0Ak_48kb4ZxBbbsa9:-MS0IOl-8BgBxOxDksvl:bowwlt3) ([raw file](https://github.com/robotlocomotion/drake/blob/93a5ec6e25231a828796297a9caaed8ce63ac39d/multibody/fixed_fem/dev/state_updater.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I still find this wording confusing. Would it make sense here to say that this is for a "representative" degree of freedom and the derivative w.r.t. z is the same for all dofs in the same model?
</blockquote></details>

Yes, I have reworded the comment by incorporating your suggestion, thank you.
___
*[multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, line 113 at r6](https://reviewable.io/reviews/robotlocomotion/drake/14535#-MRzdr8P5PbdWFEaT3Wd:-MS0Fs3D3Ub7CV_qxNTt:b-58zmro) ([raw file](https://github.com/robotlocomotion/drake/blob/b1f945c39e6b72b43da8ffb42a24d3c5125a4c21/multibody/fixed_fem/dev/test/static_elasticity_model_test.cc#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think I understand now why you originally called those "derivatives" but I found that very confusing due to all the other derivatives in the overall problem. Now I see these just capture the relationship between the q, qdot, and qdotdot quantities and the independent variable z. I think `weights` is an improvement over the confusing state_derivatives, although it doesn't quite capture the concept, which I'm now thinking of as `relation_between_states_and_z` or `dependence_of_states_on_z`. I think it's OK as is but I'd like to see a comment, maybe in StateUpdater::weights(), that would explain the meaning better.
</blockquote></details>

I agree `weights` is probably not the best name for the method, but the concept is a bit hard to articulate to begin with. Instead of trying to come up with a succinct name that captures the concept, I choose to do you suggest: add some comment to explain the meaning.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14535)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform), exempt from platform review

**Pull request merged**
