### PR TITLE
BUILD COP: Revert "Modified allURDFs() to be more robust against the user cloning drake into a directory whose path includes "*/dev/*""

### PR DESCRIPTION
**Pull request by jamiesnape**
Reverts RobotLocomotion/drake#2356

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2377)

### CODE REVIEW

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/49/

**Comment by liangfok** [comment]
@jamiesnape, I'm having trouble opening the Jenkins URL. Is it just me?

**Comment by jamiesnape** [comment]
Unfortunately two PR's were merged in quick succession.

**Comment by jamiesnape** [comment]
@liangfok The build has not started yet, so the link will not be active.

**Comment by liangfok** [comment]
Was there a previous error on Jenkins that I can look at to begin investigating the problem?

**Comment by liangfok** [comment]
Could this be it? https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-windows-msvc-32-experimental-2171-1500&field2=buildstarttime&compare2=84&value2=now

**Comment by jamiesnape** [comment]
This is the build history: https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-continuous-matlab/buildTimeTrend

**Comment by jamiesnape** [comment]
If you find the issue, push a branch with the fix to this repo so that we can run the equivalent of the continuous job on Jenkins.

**Comment by liangfok** [comment]
OK will do. 

I just noticed that the unit tests that are failing were not run on experimental builds, which is why we did not catch this problem prior to merging into master.

Here are the failing tests:
https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=21003

I assume they are not run in the experimental build because they take too long?

I will next try to replicate the problem locally.

**Comment by jamiesnape** [comment]
They are long running, yes.

**Comment by liangfok** [comment]
There's some suspiscion that the breakage was due to https://github.com/RobotLocomotion/drake/pull/2345.

I will thus hold off further investigation until we receive the results of reverting https://github.com/RobotLocomotion/drake/pull/2356.

**Pull request closed without merging**
