### PR TITLE
Remove dead code in drakeUtil and drakeGeometryUtil

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6464.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7364)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all review per rotation, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/drakeGeometryUtil.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7364#-Kxhr7GyLf0jdkgkG38u:-Kxhr7GyLf0jdkgkG38v:bp41ayo) ([raw file](https://github.com/robotlocomotion/drake/blob/b2401115a19b56fbf610f56301a27cd233efc77a/drake/util/drakeGeometryUtil.h#L23)):*
> ```objc
> #include "drake/math/quaternion.h"
> #include "drake/math/rotation_conversion_gradient.h"
> ```

BTW Can a duplicate of the `TODO` in` drakeUtil.h` be placed here - to update names to be style-guide consistent?

---

*[drake/util/drakeUtil.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7364#-KxhqrpATBmgictfggBv:-KxhqrpATBmgictfggBw:biywyfg) ([raw file](https://github.com/robotlocomotion/drake/blob/b2401115a19b56fbf610f56301a27cd233efc77a/drake/util/drakeUtil.h#L29)):*
> ```objc
> 
> template <typename Derived>
> inline void sizecheck(const Eigen::MatrixBase<Derived>& mat, size_t rows,
> ```

BTW I'd honestly prefer something like `sizecheck` to stay alive in some debugging utilities, if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7364#-:-Kxhr2twr_3VgWvrNRtJ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/drakeGeometryUtil.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7364#-Kxhr7GyLf0jdkgkG38u:-Kxhs5mGSpEUsuoD3hf_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b2401115a19b56fbf610f56301a27cd233efc77a/drake/util/drakeGeometryUtil.h#L23)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can a duplicate of the `TODO` in` drakeUtil.h` be placed here - to update names to be style-guide consistent?
</blockquote></details>

Done.

---

*[drake/util/drakeUtil.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7364#-KxhqrpATBmgictfggBv:-Kxhs90Ln9-PJyw0sV21:b2uelfy) ([raw file](https://github.com/robotlocomotion/drake/blob/b2401115a19b56fbf610f56301a27cd233efc77a/drake/util/drakeUtil.h#L29)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I'd honestly prefer something like `sizecheck` to stay alive in some debugging utilities, if possible.
</blockquote></details>

OK Anyone who wants such a function is free to PR it, with appropriate unit testing.  Since this code is unused, untested, and styleguide-deficient, I feel OK about deleting it for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7364)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7364)*

**Pull request merged**
