### PR TITLE
Split common/test/symbolic_expression.test.cc file

### PR DESCRIPTION
**Pull request by soonho-tri**
Close https://github.com/RobotLocomotion/drake/issues/4848

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4859)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-:-Kb8Zoe8Wn0cvx4xi8AL:b-utjvo1)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-:-KbBQNklIoh-emNQFEbD:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , platform-review please.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-:-KbBQZWM2GS9GdAx0rsI:bq8ci7j)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-KbBVcZn9drZIjDpQ3Up:-KbBVcZn9drZIjDpQ3Uq:b-aj9a3l) (no related file):*
Aside from the `#include` lines, `namespace` lines, and cut-n-paste text -- is there any new or edited content in here that I should look at more closely?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859)*

**Comment by soonho-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-KbBVcZn9drZIjDpQ3Up:-KbBVz39_zq9wJTS9o_p:brdaev5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aside from the `#include` lines, `namespace` lines, and cut-n-paste text -- is there any new or edited content in here that I should look at more closely?
</blockquote></details>

Only CMakeLists.txt and BUILD files, but I'm sure that they're all good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4859#-:-KbBWBHpf_OYMRf1XjpU:bnfp4nl)*

**Pull request merged**
