### PR TITLE
Upgrade SpatialMomentum documentation and keyword arguments for Python.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
Note: The Python bindings for SpatialMomentum::Shift() are not "correct" now.
In a later commit, I'll deprecate the old/bad ones and create new ones.
However, we can make progress on the vast majority of this now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MyoFinw6AkFekFNZ8je:bgbvl2w)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending some minor things.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MytFH9e27vPxfP1SdAG:b-xobrwg)* status: 6 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

___
*[multibody/math/spatial_momentum.h, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytBjb20RA2hBqHpeWt:-MytBjb20RA2hBqHpeWu:b-rbyhf1) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L85)):*
> ```objc
>   /// a 6-element vector, i.e., a 3-element angular momentum 𝐡 and a
>   /// 3-element translational momentum 𝐥. This constructor will assert the
>   /// size of `A` is six (6) either at compile-time for fixed sized Eigen
> ```

typo A -> L
___
*[multibody/math/spatial_momentum.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytCIEF1QjCLfAIBwNr:-MytCIEF1QjCLfAIBwNs:b8kpl5v) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L102)):*
> ```objc
>   ///   l_MS_E = l_MS_E         (translational momentum of `this` is unchanged).
>   ///  h_MSQ_E = h_MSP_E + p_QP_E x l_MS_E
>   ///          = h_MSP_E - p_PQ_E x l_MS_E
> ```

BTW rather than these alternatives, consider just writing
```c++
h_MSQ_E = h_MSP_E + l_MS_E x p_PQ_E
```
(That seems like the cleanest one to me since it just involves "+" and data we're given.)
___
*[multibody/math/spatial_momentum.h, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytCv6N03SDn-7JwEpz:-MytCv6N03SDn-7JwEq-:btainmu) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L105)):*
> ```objc
>   /// </pre>
>   /// Note: Spatial momenta shift similar to spatial force (see SpatialForce)
>   /// and in a transpose way to spatial velocity (see SpatialVelocity).
> ```

Hmmm. "transpose" doesn't seem right here. Transposing doesn't change the element order -- in order for transpose to make sense I think you would have to introduce Jain's shift operator (which is actually the thing that gets transposed rather than the SpatialVector).

My inclination would be just to delete the last part or replace it with something like "but differently from shifting a motion quantity (see SpatialVelocity)".
___
*[multibody/math/spatial_momentum.h, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE7ju43a4cNUpGbtY:-MytE7ju43a4cNUpGbtZ:bd6wpi9) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L113)):*
> ```objc
>     // "rigid body transformation operator" to write this as:
>     //   L_MSQ = Φ(-p_PQ)L_MSP
>     //         = Φ(p_QP)L_MSP     where Φᵀ(p_QP) is the linear operator:
> ```

minor: you wrote Φᵀ above but then wrote down Φ (or at least something is inconsistent here)
___
*[multibody/math/spatial_momentum.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE-FP2bkMaj1gh4Iu:-MytE-FP2bkMaj1gh4Iv:b-uiwpjw) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L114)):*
> ```objc
>     //   L_MSQ = Φ(-p_PQ)L_MSP
>     //         = Φ(p_QP)L_MSP     where Φᵀ(p_QP) is the linear operator:
>     //   Φ(p_PQ) = | I₃  p_PQx |
> ```

The sign looks wrong to me -- this should be -p_PQx or p_QPx I think.
___
*[multibody/math/spatial_velocity.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytExt049IqaBnYefOa:-MytExt049IqaBnYefOb:b-j2wkqn) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_velocity.h#L94)):*
> ```objc
>     // where `px_BoCo` denotes the cross product skew-symmetric matrix such that
>     // `px_BoCo vec = p_BoCo x vec` (where vec is any vector).
>     // The transpose of this operator shifts spatial force or spatial momentum
> ```

minor: this comment is confusing now because it is Φ, not Φᵀ, that shifts spatial force & momentum. Just say that explicitly here.

**Review by mitiguy — COMMENTED** [review]
@sherm1   This is ready for another look.
I added the new/corrected Python bindings and deprecated the old/incorrect ones.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-Myy4nn-0YYzTjfVdx4p:b-r6n10c)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/math/spatial_momentum.h, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytBjb20RA2hBqHpeWt:-MyxgRwX5GHP6LL6GTAF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L85)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo A -> L
</blockquote></details>

Done.
___
*[multibody/math/spatial_momentum.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytCIEF1QjCLfAIBwNr:-MyxghYu5PHtS6SMpy4u:b-dpd2aq) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L102)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW rather than these alternatives, consider just writing
```c++
h_MSQ_E = h_MSP_E + l_MS_E x p_PQ_E
```
(That seems like the cleanest one to me since it just involves "+" and data we're given.)
</blockquote></details>

I'd prefer to keep it as is for several reasons.
1. Velocity is more related to shifts and cross products of the form  𝛚 x 𝐩  whereas force and momentum are more related to shifts and cross products of the form  𝐩 x 𝐟  and  𝐩 x 𝐥.
Moreover, angular momentum is called "moment of momentum" due to its relationship to other moments, e.g.,  moment of a force (𝐩 x 𝐟), hence (𝐩 x 𝐥) instead of (𝐥 x 𝐩).  More information on this at:
https://physics.stackexchange.com/questions/381179/why-is-angular-momentum-sometimes-called-moment-of-momentum.
2. The new documentation is consistent with the old documentation (weak reason).
3. The way we actually implement it is closer to    h_MSQ_E  = h_MSP_E  -  p_PQ_E x l_MS_E
___
*[multibody/math/spatial_momentum.h, line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytCv6N03SDn-7JwEpz:-MyxkI0K18qTIzYQJSi4:b-q98d2d) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Hmmm. "transpose" doesn't seem right here. Transposing doesn't change the element order -- in order for transpose to make sense I think you would have to introduce Jain's shift operator (which is actually the thing that gets transposed rather than the SpatialVector).

My inclination would be just to delete the last part or replace it with something like "but differently from shifting a motion quantity (see SpatialVelocity)".
</blockquote></details>

Done.  Trying something "different".
___
*[multibody/math/spatial_momentum.h, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE7ju43a4cNUpGbtY:-MyxlzUVDKjlVGpgMhVa:b-50w8tr) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: you wrote Φᵀ above but then wrote down Φ (or at least something is inconsistent here)
</blockquote></details>

Done.  Reverted to original documentation (which had just Φ).



_Code quote:_
```objc
  /// where `Φ(p_PQ)` is the linear operator: <pre>
  ///   Φ(p_PQ) = | I₃ p_PQx |
  ///             | 0     I₃ |
```
___
*[multibody/math/spatial_momentum.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE-FP2bkMaj1gh4Iu:-MyxmLW92AsgU7sM1Ym2:b-glzjw4) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L114)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The sign looks wrong to me -- this should be -p_PQx or p_QPx I think.
</blockquote></details>

TBD.  I need to review Jain's book (do not have it now).
___
*[multibody/math/spatial_velocity.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytExt049IqaBnYefOa:-MyxpM6V4rqEbzqHJ6sF:b-imafpn) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_velocity.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this comment is confusing now because it is Φ, not Φᵀ, that shifts spatial force & momentum. Just say that explicitly here.
</blockquote></details>

Done -- with more generic language.

**Review by sherm1 — COMMENTED** [review]
Thanks, a few new comments.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-Mz27SXn1VrQ4UzD7EGi:b-7dx7zj)* status: 6 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/math/spatial_acceleration.h, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz23NWx0MJqLk_n9bU8:-Mz23NWy2W-FJJ7P1zWF:bn2mgav) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_acceleration.h#L77)):*
> ```objc
>                       const Eigen::Ref<const Vector3<T>>& a) : Base(alpha, a) {}
> 
>   /// Constructs a spatial acceleration `A` from an Eigen expression that
> ```

nit: you didn't use backquotes around "A" above or "L" elsewhere. I don't think you need them here either. It's clear what they are without the (hardly visible) format change. In any case should be consistent.
___
*[multibody/math/spatial_momentum.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE-FP2bkMaj1gh4Iu:-Mz25MJLD906lC5m4FkR:b-tuvwzj) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L114)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

TBD.  I need to review Jain's book (do not have it now).
</blockquote></details>

You can just apply the operator to see that it produces h_MSP + p_PQ x l_MS rather than h_MSP - p_PQ x l_MS which is what you wrote above.
___
*[multibody/math/spatial_momentum.h, line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz23uHsB5VgcfwohxAS:-Mz23uHsB5VgcfwohxAT:b-kixcee) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_momentum.h#L85)):*
> ```objc
>   /// a 6-element vector, i.e., a 3-element angular momentum 𝐡 and a
>   /// 3-element translational momentum 𝐥. This constructor will assert the
>   /// size of `L` is six (6) either at compile-time for fixed sized Eigen
> ```

nit: inconsistent use of back quotes in this comment. I suggest just removing them -- they add noise here in the header and IMO don't add clarity in Doxygen either.
___
*[multibody/math/spatial_momentum.h, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz24ulv2RbjjjxvRgxu:-Mz24ulv2RbjjjxvRgxv:b-9h85q0) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_momentum.h#L119)):*
> ```objc
>     // `p_PQx vec = p_PQ x vec` (where vec is any vector).
>     // Note: There are related Φ operators that shift spatial force and spatial
>     // velocity (see SpatialForce::Shift() and SpatialVelocity:Shift()).
> ```

BTW the text that was there before seemed better. The operators really are Φ and Φᵀ -- they aren't just related.
___
*[multibody/math/spatial_velocity.h, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz25n-e8655Sy8VdJ8A:-Mz25n-e8655Sy8VdJ8B:b-46h4me) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_velocity.h#L94)):*
> ```objc
>     // where `px_BoCo` denotes the cross product skew-symmetric matrix such that
>     // `px_BoCo vec = p_BoCo x vec` (where vec is any vector).
>     // Note: There are related Φ operators that shift spatial force and spatial
> ```

This seems more confusing. These operators aren't just related -- it is literally Φ and Φᵀ. You should just say that explicitly rather than the mysterious "related". I only thought the existing comment was confusing because it talked about (Φᵀ)ᵀ rather than Φ.
___
*[bindings/pydrake/multibody/math_py.cc, line 188 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz26gew2m2tnPcWtgib:-Mz26gew2m2tnPcWtgic:bry953k) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/bindings/pydrake/multibody/math_py.cc#L188)):*
> ```cpp
>     constexpr char doc_Shift_deprecatedArgName[] =
>         "The keyword argument (kwarg) has been renamed from"
>         " Shift(p_BqBq_E) to"
> ```

typo p_BqBq -> BpBq

**Review by mitiguy — COMMENTED** [review]
@sherm1  Ready for another look.  Prioritize as appropriate -- with demands of this wee's robotics onsite.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MzHq2pxAhRJ6zwCr-2a:b-nhyjwg)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/math/spatial_acceleration.h, line 77 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz23NWx0MJqLk_n9bU8:-MzGqtFRECUNEJvZnWKn:bo9nnyq) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_acceleration.h#L77)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: you didn't use backquotes around "A" above or "L" elsewhere. I don't think you need them here either. It's clear what they are without the (hardly visible) format change. In any case should be consistent.
</blockquote></details>

Done.  Here and elsewhere.
___
*[multibody/math/spatial_momentum.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MytE-FP2bkMaj1gh4Iu:-MzHdrVUB9Tng_Pl8m45:bjebjra) ([raw file](https://github.com/robotlocomotion/drake/blob/227e478e05802294b223ff948e11062294dc2b4d/multibody/math/spatial_momentum.h#L114)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You can just apply the operator to see that it produces h_MSP + p_PQ x l_MS rather than h_MSP - p_PQ x l_MS which is what you wrote above.
</blockquote></details>

Updated in spatial momentum and in spatial velocity.
Will update spatial force subsequently.
___
*[multibody/math/spatial_momentum.h, line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz23uHsB5VgcfwohxAS:-MzGqqQBEv1SgV5mTXy-:bo9nnyq) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_momentum.h#L85)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: inconsistent use of back quotes in this comment. I suggest just removing them -- they add noise here in the header and IMO don't add clarity in Doxygen either.
</blockquote></details>

Done.  Here and elsewhere.
___
*[multibody/math/spatial_momentum.h, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz24ulv2RbjjjxvRgxu:-MzHeEi3Dqp65DnIKW2k:bjebjra) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_momentum.h#L119)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the text that was there before seemed better. The operators really are Φ and Φᵀ -- they aren't just related.
</blockquote></details>

Updated in spatial momentum and in spatial velocity.
Will update spatial force subsequently.
___
*[multibody/math/spatial_velocity.h, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz25n-e8655Sy8VdJ8A:-MzHeHOn0t1cBkWEjmyD:bjebjra) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/multibody/math/spatial_velocity.h#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems more confusing. These operators aren't just related -- it is literally Φ and Φᵀ. You should just say that explicitly rather than the mysterious "related". I only thought the existing comment was confusing because it talked about (Φᵀ)ᵀ rather than Φ.
</blockquote></details>

Updated in spatial momentum and in spatial velocity.
Will update spatial force subsequently.
___
*[bindings/pydrake/multibody/math_py.cc, line 188 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mz26gew2m2tnPcWtgib:-MzGt3dR0C-cRdSP1k0v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5f9c26d1ae1652bda44c90641fe3b5b2043e81/bindings/pydrake/multibody/math_py.cc#L188)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo p_BqBq -> BpBq
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review per rotation (Monday), please
(unless someone can grab it earlier)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MzVqElN6QYdsBskn5qY:b-7s7463)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy and @rpoyner-tri)

**Review by mitiguy — COMMENTED** [review]
@sherm1 -- in case you want to take one more look at this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MzXHLGp2cUv598ZwFwq:bk85dz4)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @sherm1)

___
*[multibody/math/spatial_velocity.h, line 92 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MzVpgPn3LsLznWBgfy-:-MzX9MwP8v1tJnZj76ED:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2637fac780555eac857eef7e174d446e8e65c05c/multibody/math/spatial_velocity.h#L92)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the lower left should be -pₓ (transpose of a skew-symmetric matrix)
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: newly deprecated) 
:lgtm: deprecation date issue

> Reviewed 1 of 5 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844#-:-MzougZyBsAjMJH_y-vK:b-gizve)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[bindings/pydrake/multibody/math_py.cc, line 190 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16844#-Mzow4Rp3TwfYzV3ovrV:-Mzow4Rq0ky-9sHvkJgz:bef22x) ([raw file](https://github.com/robotlocomotion/drake/blob/e9f8610d0ea88a072fda6a46b07ffabafedec394/bindings/pydrake/multibody/math_py.cc#L190)):*
> ```cpp
>         " Shift(p_BpBq_E) to"
>         " Shift(offset)."
>         " Deprecated kwarg will be unavailable after 2022-07-01.";
> ```

This PR will have the unfortunate fate of landing in April, so the deprecation date needs to be pushed to 2022-08-01.



_Code quote:_
```cpp
2022-07-01
```
___
*[bindings/pydrake/multibody/test/math_test.py, line 210 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16844#-MzowFK62AeQn2jxTxpT:-MzowFK62AeQn2jxTxpU:bfhxjxh) ([raw file](https://github.com/robotlocomotion/drake/blob/e9f8610d0ea88a072fda6a46b07ffabafedec394/bindings/pydrake/multibody/test/math_test.py#L210)):*
> ```Python
>         dut = SpatialMomentum_[T].Zero()
>         self.assertIsInstance(dut.Shift(offset=p), SpatialMomentum_[T])
>         # TODO(2022-07-01) Remove with completion of deprecation.
> ```

ditto above re deprecation date.



_Code quote:_
```Python
2022-07-01
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16844)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Comment by jwnimmer-tri** [comment]
FYI the commit message used here was not correctly tidied up.

**Pull request merged**
