### PR TITLE
add reset capability to signal logger

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8200)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@naveenoid  for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-:-L6P8zPueMqNoSNUWkuC:bnpzzxu)*

**Comment by naveenoid** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/signal_log.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-L6PI2Re4nnOHhKdjEap:-L6PI2RfBmoQkugJlmKz:bdvtqhm) ([raw file](https://github.com/robotlocomotion/drake/blob/89c242a5750e2de3e471738019782754382fa89d/systems/primitives/signal_log.h#L38)):*
> ```objc
> 
>   /** Reset the logged data. */
>   void reset() { num_samples_ = 0; }
> ```

Why not also resize sample_times and data?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/signal_log.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-L6PI2Re4nnOHhKdjEap:-L6QgDdSWQcrwjuQudGW:bcnr84l) ([raw file](https://github.com/robotlocomotion/drake/blob/89c242a5750e2de3e471738019782754382fa89d/systems/primitives/signal_log.h#L38)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Why not also resize sample_times and data?
</blockquote></details>

As far as the caller is concerned, it could go either way.  Whether or now you actually give back the memory, in the case where the initial logging has exceeded the batch allocation size, seems like an implementation detail for which I'm not sure there is a right answer.  

The use case that motivated this was running the same simulation multiple times from different initial conditions.  In that case, at least, if my trajectories were long, I'd prefer to have it keep the maximum allocated size between runs.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-:-L6T6T5Iyt9Yp8LMRLCn:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@seancurtis-tri for platform

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-:-L6T9vxrUphRj4ENJMBE:b-drqrgr)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with one minor documenting suggestion.

---

Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/signal_log.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-L6TRq39Qq26uGARXk5k:-L6TRq39Qq26uGARXk5l:b-tccpjm) ([raw file](https://github.com/robotlocomotion/drake/blob/89c242a5750e2de3e471738019782754382fa89d/systems/primitives/signal_log.h#L38)):*
> ```objc
> 
>   /** Reset the logged data. */
>   void reset() { num_samples_ = 0; }
> ```

FYI I had a moment of suspicion on this line of code and had to convince myself it is correct. I'd recommend putting a comment to future developers so that they can know *why* this is correct. (I.e., that this effectively clears `sample_times_` and `data_`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-:-L6TSbEZ6n-725dqifOm:b-t5l5r)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/signal_log.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8200#-L6TRq39Qq26uGARXk5k:-L6TWby7RIQKenG4hnDh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/89c242a5750e2de3e471738019782754382fa89d/systems/primitives/signal_log.h#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I had a moment of suspicion on this line of code and had to convince myself it is correct. I'd recommend putting a comment to future developers so that they can know *why* this is correct. (I.e., that this effectively clears `sample_times_` and `data_`.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8200)*

**Pull request merged**
