### PR TITLE
Reorganize installation software

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.  Full WIP series at https://github.com/jwnimmer-tri/drake/tree/build-drake-folder-6996.

Consolidate the generic helpers into `/tools/install/`.
Move details of workspace items into `/tools/workspace/foo/`.

This is a non-functional change, merely moving some files around.
Future commits will factor the targets differently.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7316)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@jamiesnape @fbudin69500 What do you think of this PR, from a design / principle standpoint?

If the design looks good, then from a code standpoint would either of you like to sign up for a feature review?

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 98 of 98 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7316#-:-Kx92dZvXAaiPTNf2_Fo:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7316#-:-Kx9Ckto4MdgB6hLU-mQ:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm: + :apple: tested

---

Reviewed 98 of 98 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7316#-:-Kx9HSZm_kIRFihJ0Vh8:bzal9dn)*

**Pull request merged**
