### PR TITLE
[pybind] Moves a historically flaky RenderEngine test into its own test

### LINKED ISSUE #14720: Flaky test in geometry_test should be isolated
# The Problem

A unit test added in #14375 has flaky behavior on mac. In essence, the test does the following:

1. We have a C++ class (`RenderEngine`) bound in Python.
   - Three methods under test (`DoRenderColorImage`, `DoRenderDepthImage`, `DoRenderLabelImage`) all throw exceptions if not properly implemented in derived classes.
2. In Python, we sub-class it into `MinimalEngine` which gives token implementations of *some* of the API (a portion of the API which is *not* under test.)
3. From `MinimalEngine`, we derive another class (e.g., `ColorOnlyEngine`) which implements `DoRenderColorImage` but leaves the other two alone.
    - We expect color imaging to "no throw" but depth and label to "throw".
    - We have similar types for color and depth labels.

Since the test entered master, this test has been flaky on mac; sometimes a test that *should* throw, doesn't.

# The Solution

Rather than mark all of `geometry_test.py` as flaky (covering a *large* number of tests), we isolate this particular `RenderEngine` test into its own module and mark it flaky all by itself.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The test that confirmed derived RenderEngines are informed if they fail to implement the rendering API has proven to be flaky on the mac. This moves that test into its own "test" that can be marked flaky.

No new code is written. The old test just received some new doc strings to provide a bit more context.

resolves #14720

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@betsymcphail for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724#-:-MUn_xINACk2eoaFn8Rj:b7hpxdc)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14724#-MUndtTq-RCsUxNGFQVQ:-MUndtTq-RCsUxNGFQVR:b9k2b0y) (no related file):*
There's currently a pycode style failure. I'm going to let the tests finish out (especially on the mac) before I push the fix.

---

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724#-:-MUnk8Y15gU8joXS1s14:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Passed https://drake-jenkins.csail.mit.edu/job/mac-big-sur-clang-bazel-experimental-release/8/ (with only the pycode style issue).

+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724#-:-MUo8Sfm5Oh4RTDpX3Pq:bm51cqx)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @BetsyMcPhail and @sherm1)

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one minor comment.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724#-:-MUolWPr4F16arSL7VFe:bkn926a)* status: 2 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/test/geometry_render_engine_subclass_test.py, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14724#-MUokyLQB9p7bPGXLLto:-MUokyLR9DGtQTN-Oxs4:b-e26af) ([raw file](https://github.com/robotlocomotion/drake/blob/a91053e49ea7b3c72274e288ad863f03e526d02a/bindings/pydrake/test/geometry_render_engine_subclass_test.py#L3)):*
> ```Python
> """For reasons not yet understood (see issue #14686), the unit tests where we
> confirm the semantics of deriving a RenderEngine implementation in python are
> being isolated (see issue #14720)."""
> ```

This says "For reasons not yet understood ... the test is being isolated". I think you wanted to say "... the test is flaky" therefore it is being isolated?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Typo fixed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724#-:-MUoo3GpB-bYmCFAYG42:bix7gpd)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @sherm1)

___
*[bindings/pydrake/test/geometry_render_engine_subclass_test.py, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14724#-MUokyLQB9p7bPGXLLto:-MUoo0joEA3evVhRv95m:b-6ldl4l) ([raw file](https://github.com/robotlocomotion/drake/blob/a91053e49ea7b3c72274e288ad863f03e526d02a/bindings/pydrake/test/geometry_render_engine_subclass_test.py#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This says "For reasons not yet understood ... the test is being isolated". I think you wanted to say "... the test is flaky" therefore it is being isolated?
</blockquote></details>

Yes indeed.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14724)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),BetsyMcPhail

**Comment by EricCousineau-TRI** [comment]
Affects repro steps in #14686

**Pull request merged**
