### PR TITLE
Update SHA for styleguide

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Relates https://github.com/RobotLocomotion/styleguide/pull/12

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9110)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
+@jamiesnape for feature review, please.

**Comment by m-chaturvedi** [comment]
New message: "Update SHA for styleguide. Close # 8316."

**Comment by jamiesnape** [comment]
`Closes #8316` would be the magic words for GitHub. You will notice there is no cross-reference to here on #8316.

**Comment by jamiesnape** [comment]
(or at least there wasn't until I wrote that)

**Comment by m-chaturvedi** [comment]
:D

**Comment by m-chaturvedi** [comment]
+@ggould-tri for platform review, please.

**Pull request merged**
