### PR TITLE
[workspace] Fix "disable drake-visualizer on macOS" for Ubuntu again

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hotfix for #16962 and #16945.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16964)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16964)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16964#-:-N-ckEIqBpwBU1QT1sk_:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/workspace/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16964#-N-ckGwMExObR7hcjpET:-N-ckGwMExObR7hcjpEU:b-sffujn) ([raw file](https://github.com/robotlocomotion/drake/blob/9acae47992adc50380ef62dbedf7a73aaffe439e/tools/workspace/BUILD.bazel#L12)):*
> ```Starlark
> load(
>     "@drake_visualizer//:defs.bzl",
>     _DRAKE_VISUALIZER_ENABLED = "ENABLED",
> ```

tricksy. TIL.

**Comment by jwnimmer-tri** [comment]
The CI test is still running, but my local `test //...` on mac passed.  I'll call that good enough to merge now.

**Pull request merged**
