### PR TITLE
Collide BVHs using OBB intersection test with callback on the resulting pairs

### PR DESCRIPTION
**Pull request by tehbelinda**
- pass transform for comparing the AABBs using OBB intersection test
- early exit option as soon as a potential collision pair is found
- accumulator wrapper helper function for getting a list of all the pairs

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12418)

### CODE REVIEW

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhAVUR0esN-Tbxlhx3:-LuiVhRO-71nDTQaFChX:b6359ey) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L172)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This if-else logic is slightly broken.

Imagine that b's left is nullptr, but a has two children. This first test will fail and we'll take the else branch. We'll put node_a against b's left null child as the first step. That means, you have a pair (node, nullptr) in your stack. Your previous code doesn't handle this.

And there's a mirror scenario as well.
</blockquote></details>

If b's left is nullptr, it should pass and go into this first if. E.g. if the branching looks like this:

      (node_a)                                 (node b)
    /             \
(a left)    (a right)

then the stack will then get (a left) + (node b)  and (a right) + (node b)

The remaining else then handles the mirror case:

      (node_a)                                 (node b)
                                                     /             \
                                                (b left)    (b right)

where the stack will get (node a) + (b left)  and (node a) + (b right)

As well as the case when they both have children:

      (node_a)                                 (node b)
      /             \                               /             \
(a left)    (a right)                   (b left)    (b right)
                                          
where the stack will still get (node a) + (b left)  and (node a) + (b right)

so I don't think there should be any nullptrs in the stack since that's all  the cases?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhAVUR0esN-Tbxlhx3:-LuiXosOEcDroQ8T2-kG:b-h0z1e8) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L172)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

If b's left is nullptr, it should pass and go into this first if. E.g. if the branching looks like this:

      (node_a)                                 (node b)
    /             \
(a left)    (a right)

then the stack will then get (a left) + (node b)  and (a right) + (node b)

The remaining else then handles the mirror case:

      (node_a)                                 (node b)
                                                     /             \
                                                (b left)    (b right)

where the stack will get (node a) + (b left)  and (node a) + (b right)

As well as the case when they both have children:

      (node_a)                                 (node b)
      /             \                               /             \
(a left)    (a right)                   (b left)    (b right)
                                          
where the stack will still get (node a) + (b left)  and (node a) + (b right)

so I don't think there should be any nullptrs in the stack since that's all  the cases?
</blockquote></details>

sorry about the formatting...let me try that again. These were the 3 cases I was trying to show
```
     (node_a)                                 (node b)
    /         \
(a left)   (a right)
```

```
     (node_a)                                 (node b)
                                             /         \
                                         (b left)   (b right)
```

```
     (node_a)                                 (node b)
    /         \                              /         \
(a left)   (a right)                     (b left)   (b right)
```

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhBejw6SbAIQgpHTbm:-LuiYrxy8-osgZPmyo0c:b-5nsbpg) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L174)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm somewhat surprised by this logic. In my mind, if A and B intersect, it should lead to four new tests: (A.L, B.L), (A.R, B.L), (A.L, B.R), (A.R, B.R) (obviously, omitting any of those tests in which the node does not exist).

I'm not sure how to compare with what you have here -- it may be that the flawed logic is preventing me from doing that comparison. I just wanted to express that thought.
</blockquote></details>

Since this is iterative it will get to testing the next level when the pair comes back through the stack. I guess right now it's doing a descend b and then descend a traversal. I could split the cases out so that it goes straight to the (A.L, B.L), (A.R, B.L), (A.L, B.R), (A.R, B.R) pairings and then it'd be more like a descend both?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 205 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhCo_t3htGurwD7LYm:-Luidtyb8G5vQpNDgJtl:bv3a32x) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L205)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was surprised to see friend status? You're using non-public API to do the collision?
</blockquote></details>

yeah for the initial emplace onto the stack. I access the private root_node_ 
`node_stack.emplace(*root_node_, *(bvh.root_node_));`
does it make sense to just add public getter instead?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 191 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhCe7C4AgJ7C9y7cEw:-LuixeDRCZOr4VSFJAYg:bexg493) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L191)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Weirdness with the use of `auto` here.
</blockquote></details>

as in it should be explicit instead of auto? I figured since it was just creating an empty vector it would look repetitive

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 172 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LuhAVUR0esN-Tbxlhx3:-LujI7MF-ygrZxCWbrpL:bea1ka2) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L172)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm talking about *this* case.

```
   A          B
 /   \         \
A.L  A.R        B.R
```

In this case:
  - if (everything is leaf) will fail.
 - b.L == null && b.R == null will fail
 - so, it will fall through to the final else and dispatch (A, B.L) and (A, B.R) and (A, B.L) is the bad one.

In all of your examples above, you're assuming that a node either has two children or no children, and I don't think you get to do that. (And you're certainly not doing that in your definition of a "leaf").
</blockquote></details>

Hmm yes I was assuming that... given the tree is split down the median and there's only one element per leaf node, won't it always be perfectly balanced?

Just trying to think through the cases
1 element:
```
  e1
```
2 elements:
```
   *
 /   \
e1   e2
```
3 elements:
```
   *
 /   \
e1    *
    /   \
   e2   e3
```
And the rest would just build on that. Am I missing something else?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Luh9eiF1jPkBKGtddFX:-LujNTB5AduBZavb3fpw:b-u4rs8r) ([raw file](https://github.com/robotlocomotion/drake/blob/2384c8d490123f693069fcb1e0e4258cb586ef05/geometry/proximity/bounding_volume_hierarchy.h#L146)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You probably don't need a stack here. Conceptually, a stack feels nice. But you just need a queue of BV-pairs to test. It doesn't matter if you functionally go depth first or breadth first (particularly if you're single-threaded). That said, nothing *wrong* with a stack.

The default implementation of the stack uses a deque. When we get around to profiling this, it's conceivable that, for performance reasons, we swap it to a vector with some meaningful pre-allocated block of memory (a function of the the number of leaves in each tree).
</blockquote></details>

Did the vector - any suggestions on what that function should be? does it make sense to just use the number of elements/leaves as is since it can't descend any further than that?

**Comment by tehbelinda** [comment]
Added in the OBB tests - though I'm still trying to generate cases to trigger the last lot of axes tests

**Comment by tehbelinda** [comment]
+@seancurtis-tri for feature review please

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvfnraa70Q8scZuvJDJ:-Lvh7EFICn1BKOaTAwNy:b-5wm6pi) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/bounding_volume_hierarchy.h#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: Does this branch work if `num_elements == 0`?
</blockquote></details>

if that happens, it'll fail before it gets to this when trying to compute the bounding volume since there'll be an invalid half width. but if it were to make it here, it would recurse on itself

Is it possible for a mesh to have zero elements?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 276 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgiVW04ETsKZlRmeAQ:-LvhjyjoEfNVaCEvjx4s:b-5g9ak9) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L276)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: There are a couple of ways to achieve this -- one is to *position* the box. The other is to *pose* the box. I feel like posing the box is probably the more robust way of testing this.
</blockquote></details>

not sure I understand this - do you just mean using the RigidTransform like the other axis test? I also wanted to test that overlapping still worked with off-centre boxes but I guess there's another test below for that

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgisJl0pfICzC3cI9N:-LvhlMYl4ONQarllvgTe:bjrmm8c) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Not sure what this sentence means: "overlapping with offset center"?
</blockquote></details>

I was trying to test that even though the translation between frame A and B wouldn't cause an overlap on its own, the center position of the volume in the frame is offset, such that the two volumes are in overlap. I.e. making sure the center calculation from `const Vector3<double>& t = X_AB.translation() - a.center() + b.center();` got tested

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 214 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgXR7KC6hyIn9509v_:-LvhmDCA0TuQP_PIGLuW:b-nxog2s) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L214)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It's difficult to appreciate the full importance of this.
</blockquote></details>

are you saying it's not worth testing the template specialisation here? and/or that in general it's not necessary to test the mixture of tris and tets since the bounding volume flow is the same and abstracts that part away?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 197 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgWdeU5oRS7MLafgoM:-LvhnbZT5a_iqAkpgRa5:b-bv2y61) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L197)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm not persuaded by this test. It isn't obvious to me that this covers all the code paths and that each case provides uniquely beneficial functionality. Can you document the significance of each test?  (Failing that, we might rethink the test.)
</blockquote></details>

Hmm good point, I wrote these before HasOverlap, and that now takes care of the finer cases of overlapping so really this should focus on the traversal. I'll add a test for a different number element mesh that should reach definitely the cases of comparing a branch node with a leaf node. I assume those are the code paths you are also referring to?

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgVGHE9sFiDOgDDaEv:-Lvl6__z3j1BC2IBSA1V:b-s7as9j) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

bvh.h is no longer particularly templated (and based on a comment I added, may not be templated at all). As such, anything that isn't small with the intent of being inlined should have its implementation moved to the .cc file.
</blockquote></details>

do you mean just for the transform type of double vs autodiff? there's still the MeshType templating

---

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 267 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvlfXpZ0S9kUqpCBbx1:-LvlfXp_-XxCVUrddzYE:b1kh4xy) ([raw file](https://github.com/robotlocomotion/drake/blob/777250051793bb83fa8205d106d3ed1da967d8af/geometry/proximity/bounding_volume_hierarchy.h#L267)):*
> ```objc
>   template <class OtherMeshType, typename T>
>   std::vector<std::pair<IndexType, typename OtherMeshType::ElementIndex>>
>   GetCollidingPairs(const BoundingVolumeHierarchy<OtherMeshType>& bvh,
> ```

@SeanCurtis-TRI After some of the other comments you made, I've been wondering - what do you think of also renaming this since they may not actually be in collision? perhaps to GetUnculledPairs?

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgVGHE9sFiDOgDDaEv:-LvmfysY5HfSSMgu7bwQ:b-cu6r01) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

That comment may have been a total brainfart. Not being tempalted on scalar type, I'd blanked out on the fact that it *is* templated on mesh type.  So, you can disregard that statement.

That said, we *could* still move the implementation into the .cc file by explicitly saying that we're only supporting it for `VolumeMesh` and `SurfaceMesh`. That does have compile-time benefit and we'll only have to revisit that when we expand the BVH to include other kinds of primitives.
</blockquote></details>

So the style guide says to avoid using explicit template instantiations in cc files but if you think it's worth it here I'm happy to move them. I imagine new primitives aren't on any near-term roadmaps?

---

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 267 at r5](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvlfXpZ0S9kUqpCBbx1:-Lvmgi5j3bBp3jpQ5Tmg:brhr5sx) ([raw file](https://github.com/robotlocomotion/drake/blob/777250051793bb83fa8205d106d3ed1da967d8af/geometry/proximity/bounding_volume_hierarchy.h#L267)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

How about `GetCollisionCandidates()`.  The "candidate" word appears with some regularity in the `geometry/` folder (largely influenced by my own biases, of course.)
</blockquote></details>

sure, consistency sounds good, thanks!

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 178 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgWCAI2mO-DGfFqGOh:-LvmiuME4uMwCHdrmPMp:b-qsk6yg) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L178)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This sentence didn't quite parse for me.
</blockquote></details>

Updated this case

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 176 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgWKXI5Vfef8JYoZcG:-LvmjBZgBmQDPHnHoXKE:b68dui2) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L176)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: When documenting these tests, it's very helpful to give some insight into the design of the test and what exactly it's intended to test.
</blockquote></details>

Ok I tried to focus more on branching and traversal - does this make more sense? I'm wondering if I should reuse the ascii art from earlier comments when we were going through the branch/leaf comparison cases...

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvfnraa70Q8scZuvJDJ:-LvrH7ZT4yXJodsYKXN5:b6vib5z) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/bounding_volume_hierarchy.h#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In principle, I see no reason. The code allows it (e.g., one can easily *construct* an empty mesh). Given that, this code should do the right thing.
</blockquote></details>

Hmm ok in that case what should the behaviour be? Does it still make sense to have a tree with a root node with some kind of invalid bounding volume? e.g. center at -infinity and halfwidth of....0? We currently demand that halfwidth >= 0 but should it be -infinity in this case? 
Or, does it instead make more sense not to build a tree, but to leave the root_node as nullptr and add nullptr checks in usages?

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgVGHE9sFiDOgDDaEv:-LvrNbbF0-Jx0T6VGA_f:baumcug) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ironically, we do that *all* the time. Look for the string `DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS` which exists for *precisely* this purpose.  :)
</blockquote></details>

ok, do you think it also makes sense for the Collide functions though? since now that's also adding the 4 combinations of mesh types

---

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvgVGHE9sFiDOgDDaEv:-LvusD0z-hLmx__5WUvb:b-7sak18) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll defer to you on that.
</blockquote></details>

ok, if you're okay with those remaining in the .h file, then I'd rather leave them than specify that many

---

**Comment by EricCousineau-TRI** [comment]
Sorry about the `mkdoc` errors! I can reproduce that error on my machine, and applying #12476 to this PR will fix it.

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 305 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvzqTFeDhsfuOcnacVt:-Lw0BjGpAVc6YZ6mB7I-:bufnjz9) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L305)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'm not sure the lower-case "a" and "b" contribute much to the diagram.
</blockquote></details>

sure I can remove them, I thought it might be helpful since I'm calling out box b above and to distinguish it from the frame letter

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 312 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvzqwvJ1AcXj4SDVJ01:-Lw0CSf94cu8tCmYPi03:b88a1ez) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L312)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd propose:

> For this test, we define point Q as the *minimum* point of the box in its own frame (i.e., center - half size). We want to pose box B so Q is the uniquely closest point to A at a Point D in  the interior of the +x face of box A. The rest of the box extends farther along the +x axis (as suggested in the above illustration). Point Q will be a small epsilon away from the nearby face either outside (if `expect_overlap` is false) or inside (if true).

The goal is not to discuss this in 2D (even though you're forced to illustrate it in 2D).
</blockquote></details>

sure, I was going to refer to the boxes themselves as lower case box a and box b to distinguish them from the frame - do you think that's necessary?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 345 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvzu9dH7fpMEiRNSQVM:-Lw0DUfV5dBOwo_R-Xh4:b-dayxpm) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L345)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This is where we've changed frames without calling it out.

So, in reality, we have frames alpha and beta which are the frames in which the bounding boxes are aligned and centered on the origin. X_Aalpha is a translation between alpha and A. Similarly, X_Bbeta is that translation.  

In that case, we originally have defined p_alphaD. And this addition makes it p_AD.

We should ponder this and revisit the rhetoric. We want to get these exactly right or no one else will ever be able to read this code.  :)
</blockquote></details>

What about using Ao instead of A? so p_AoD = p_AD + a.center()?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 312 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LvzqwvJ1AcXj4SDVJ01:-Lw0E3FyE8HgFFb3rtwM:b-o624bf) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L312)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

sure, I was going to refer to the boxes themselves as lower case box a and box b to distinguish them from the frame - do you think that's necessary?
</blockquote></details>

actually after reading below, I think sticking with A and B works for the boxes and using Ao Bo for the frames works instead

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.h, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvfnraa70Q8scZuvJDJ:-Lw0XfYO0wIOIoejnSSw:b-emnags) ([raw file](https://github.com/robotlocomotion/drake/blob/94317e6b6946228a1b15ba173d8a142adf559aae/geometry/proximity/bounding_volume_hierarchy.h#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm perfectly content with putting the burden on the caller of only constructing meshes with elements. We can either:
 - Have the mesh constructors throw in that case.
 - And/or DRAKE_DEMAND "here".
The first option seems to be the superior option.
</blockquote></details>

by throw in the mesh constructor do you mean a logic error? or DRAKE_DEMAND

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/bounding_volume_hierarchy.cc, line 15 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvzq0Y555kbU6LJhc_G:-Lw08JKL97H-Kxp9p-mk:b-asip7l) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/bounding_volume_hierarchy.cc#L15)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I was thinking about this yesterday. I'm glad you caught it.  :)
</blockquote></details>

yeah! thanks Sean

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 345 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvzu9dH7fpMEiRNSQVM:-Lw0lHBf7a0jYOICtN_k:b-cufihh) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L345)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

What about using Ao instead of A? so p_AoD = p_AD + a.center()?
</blockquote></details>

wait ignore that comment, that was the wrong way around, it should be p_AD = p_AalphaD + alpha.center...what about just calling it out in the comment that we're building up to p_AD?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 315 at r8](https://reviewable.io/reviews/robotlocomotion/drake/12418#-Lvzvk9p3STRgMEXccz5:-Lw0pt2gE9b59zm4gn8R:b-tpg13c) ([raw file](https://github.com/robotlocomotion/drake/blob/ab1b689f7be58098af1e75fc394014b0f3187439/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L315)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I suspect that when we do the other 9 tests, this name will be too generic; it certainly won't be sufficient for those cases.

You might consider breaking it up into two tests. `HasOverlapBoxAxes` and `HasOverlapCrossedEdgeAxes` or some such thing. Then you don't have to worry about two names that play nicely together in the same scope.
</blockquote></details>

what about calculate_corner_transform and calculate_edge_transform?

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 338 at r10](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LwFllQP0Hwa7LHzZxoy:-LwFqfAe5Q1Xh8tdNJwX:bnjmsa4) ([raw file](https://github.com/robotlocomotion/drake/blob/758d8ef4c4d5c0dc39026bc7beeb26bc1b0b90c4/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L338)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit `p_Bo_A` should be `p_ABo_A` or `p_AB` or `p_AoBo_A` , etc., But it definitely needs a "from".
</blockquote></details>

can it be `p_BBo_A`? since it's kind of from itself? and not to be confused with `p_AoBo_A` which is what we're trying to solve for

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 408 at r10](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LwFmo2-7PpNLxh4oRTx:-LwFrPGD-WP80YKQPOm6:b-bou0vw) ([raw file](https://github.com/robotlocomotion/drake/blob/758d8ef4c4d5c0dc39026bc7beeb26bc1b0b90c4/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L408)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit `+x × +z` = `-y`, yes? Why not just say that? Is there significance that I missed?
</blockquote></details>

what if I say the y edge between the +x and +z faces? it's not necessarily +y or -y since the edge is aligned with y and potentially goes through the origin

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 338 at r10](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LwFllQP0Hwa7LHzZxoy:-LwFtXx18usdvT5fZ6w4:b-tpxiic) ([raw file](https://github.com/robotlocomotion/drake/blob/758d8ef4c4d5c0dc39026bc7beeb26bc1b0b90c4/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L338)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

can it be `p_BBo_A`? since it's kind of from itself? and not to be confused with `p_AoBo_A` which is what we're trying to solve for
</blockquote></details>

as per f2f, renaming to p_BoBc_A since it's the center point  in frame B

**Comment by tehbelinda** [comment]
___
*[geometry/proximity/test/bounding_volume_hierarchy_test.cc, line 338 at r10](https://reviewable.io/reviews/robotlocomotion/drake/12418#-LwFllQP0Hwa7LHzZxoy:-LwFteG4-Qp5uB4fYvH0:bn05b6x) ([raw file](https://github.com/robotlocomotion/drake/blob/758d8ef4c4d5c0dc39026bc7beeb26bc1b0b90c4/geometry/proximity/test/bounding_volume_hierarchy_test.cc#L338)):*
<details><summary><i>Previously, tehbelinda (Bel) wrote…</i></summary><blockquote>

as per f2f, renaming to p_BoBc_A since it's the center point  in frame B
</blockquote></details>

*center point of the box

**Comment by soonho-tri** [comment]
BTW, please note that this is a good time to rebase this PR onto the current `master` to avoid any issues of auto-merging.

**Pull request merged**
