### PR TITLE
Remove a PiecewisePolynomialTrajectory constructor which duplicated PiecewisePolynomial::FirstOrderHold().

### PR DESCRIPTION
**Pull request by Lucy-tri**
Update users of the old constructor, kuka_demo.cc and kuka_plan_runner.cc, to call FirstOrderHold() instead.
Update tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4498)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@sammy-tri  for feature review

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYyOKK8ZNPews44grIT:b-4ynxeg)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: pending platform review

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYyRYUqpLmYg3L3LiqN:b-r3ag1h)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review since it'd otherwise be my day today

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYySMnaiQwix4UbJ8_P:b-j550z7)*

**Comment by Lucy-tri** [comment]
Was I supposed to have done something differently when I submitted this PR, like squash?  
What does the "curate commits before merging" mean? I thought I could just do something like squash when I merged?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYyViXp3KbP5UxvJzxD:b-cezbkr)*

**Comment by sammy-tri** [comment]
Squash when merge should be fine (further discussion occurred offline).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYyfZBt0ulw02nKBM4X:b-y8p7a3)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyqkxpdkWohxUBdp04:-KYyqkxpdkWohxUBdp05:bwm4xv2) ([raw file](https://github.com/robotlocomotion/drake/blob/12e226b9b8de733ea06f6910668fe1df1846c880/drake/common/trajectories/piecewise_polynomial_trajectory.cc#L1)):*
> ```cpp
> #include "drake/common/trajectories/piecewise_polynomial_trajectory.h"
> ```

The `cc` file should stay around, so that we have confirmation that the header parses on its own.  At minimum, that means this include statement and a comment saying "just a compile test" or alike.

Or even better, consider moving some code from the h to cc file where appropriate / possible.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyrN2MSZdEIGxNRrMU:-KYyrN2N6Ee4wRLHBIDd:b-yew4fb) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L118)):*
> ```cpp
>     for (int i = 0; i < plan->num_states; ++i) {
>       knots[i] = Eigen::MatrixXd::Zero(kNumJoints, 1);
>     }
> ```

BTW There's a `vector` constructor that takes the value to fill with, which would not not having to write this loop out manually.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyrl2dKJbb1vO1Vz7z:-KYyrl2dKJbb1vO1Vz8-:bmfm1iv) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L140)):*
> ```cpp
>     }
>   }
>   printf("\n");
> ```

BTW Sigh.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyu3g3zuDdZlLt85Rl:-KYyu3g4v0zAHgE0_kmv:bekamjo) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L147)):*
> ```cpp
>   }
> 
>   std::vector<PiecewisePolynomial<double>::CoefficientMatrix> knots(
> ```

BTW This typename is an obscure way of saying `vector<MatrixXd>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498)*

**Comment by Lucy-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyqkxpdkWohxUBdp04:-KYz0d6dxMKXHgAdaRF_:b-udsq0c) ([raw file](https://github.com/robotlocomotion/drake/blob/12e226b9b8de733ea06f6910668fe1df1846c880/drake/common/trajectories/piecewise_polynomial_trajectory.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `cc` file should stay around, so that we have confirmation that the header parses on its own.  At minimum, that means this include statement and a comment saying "just a compile test" or alike.

Or even better, consider moving some code from the h to cc file where appropriate / possible.
</blockquote></details>

Done. I do have some one line methods I could move to the cc file, but it seems more understandable to leave them in the .h file.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyrN2MSZdEIGxNRrMU:-KYzBZcKKpYNYUKjq31-:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW There's a `vector` constructor that takes the value to fill with, which would not not having to write this loop out manually.
</blockquote></details>

Done. 

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyrl2dKJbb1vO1Vz7z:-KYzBbsctyqeiSrxU9ov:b-1ospt1) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L140)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Sigh.
</blockquote></details>

Done: removed.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYyu3g3zuDdZlLt85Rl:-KYzBe4x1tNtgGZahfgy:b-4rcdvi) ([raw file](https://github.com/robotlocomotion/drake/blob/abe61d37e64b7731c2be368142f6d945a704d5b2/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This typename is an obscure way of saying `vector<MatrixXd>`.
</blockquote></details>

Done. Yeah, I thought it might be more clear to say CoefficientMatrix, but it's such a long type name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYzE-0bWsRFqYfV8WVn:-KYzE-0bWsRFqYfV8WVo:b-j01x6t) ([raw file](https://github.com/robotlocomotion/drake/blob/cff68749f092712a73377aff4ca613a20af37dee/drake/common/trajectories/CMakeLists.txt#L6)):*
> ```CMake
>     piecewise_polynomial.cc
>     piecewise_polynomial_base.cc
>     piecewise_polynomial_trajectory.cc
> ```

Be sure to put this back!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498)*

**Comment by Lucy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-KYzE-0bWsRFqYfV8WVn:-KYzGILnwCPObf2s4Z2f:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/cff68749f092712a73377aff4ca613a20af37dee/drake/common/trajectories/CMakeLists.txt#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Be sure to put this back!
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYzH-J2XlcFhs20hrjx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by Lucy-tri** [comment]
-(status: curate commits before merging)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4498#-:-KYzSQK9y01sMNPQch8L:b-l70x01)*

**Pull request merged**
