### PR TITLE
System2.0 examples moved to plants

### PR DESCRIPTION
**Pull request by naveenoid**
Following slack channel discussions, the SpringMassSystem and ControlledSpringMassSystem examples are moved into system/plants along with the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3653)

### CODE REVIEW

**Comment by naveenoid** [comment]
+ @david-german-tri for feature review

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/CMakeLists.txt, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-KTFcY8nI89C0dkeZaO3:-KTFcY8nI89C0dkeZaO4:b5t05jt) ([raw file](https://github.com/robotlocomotion/drake/blob/a60a7dc2863424d55a978856f8dee65a61b914e4/drake/systems/plants/CMakeLists.txt#L205)):*
> ```CMake
> #System2.0 Plants
> add_subdirectory(spring_mass_system)
> add_subdirectory(controlled_spring_mass_system)
> ```

nit: newline at end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-:-KTFciSSPDf-yXrUcTe5:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm: Just one BTW comment.

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/CMakeLists.txt, line 214 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-KTG6sb8Kp68914ku37I:-KTG6sb8Kp68914ku37J:b-soeajh) ([raw file](https://github.com/robotlocomotion/drake/blob/a60a7dc2863424d55a978856f8dee65a61b914e4/drake/systems/plants/test/CMakeLists.txt#L214)):*
> ```CMake
> add_subdirectory(rigid_body_tree)
> 
> #System2.0 Tests
> ```

BTW: nit: Add space after "#".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-:-KTGAySajLkR4icMI4-_:blu91d5)*

**Comment by naveenoid** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/CMakeLists.txt, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-KTFcY8nI89C0dkeZaO3:-KTGeIbUUpTiPGuIxW8W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a60a7dc2863424d55a978856f8dee65a61b914e4/drake/systems/plants/CMakeLists.txt#L205)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> nit: newline at end of file
</details>
Done.

---

*[drake/systems/plants/test/CMakeLists.txt, line 214 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-KTG6sb8Kp68914ku37I:-KTGeJgRX5oU8lW4jE8A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a60a7dc2863424d55a978856f8dee65a61b914e4/drake/systems/plants/test/CMakeLists.txt#L214)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: Add space after "#".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3653)*

**Comment by naveenoid** [comment]
Fixed the minor issues. PTAL.

---

Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-:-KTGehu0PHXVzQqCgtCD:b-eriahk)*

**Comment by david-german-tri** [comment]
Given the current time in Switzerland, I'm going to go ahead and merge this, lest you get conflicts by tomorrow AM.

---

Review status: 13 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3653#-:-KTGvIjl9NiZdgHm3_Kr:bna5bfh)*

**Comment by naveenoid** [comment]
Thanks a lot!

**Pull request merged**
