### PR TITLE
MBT methods to compute relative transforms and convert positions between frames

### PR DESCRIPTION
**Pull request by amcastro-tri**
More code in preparation for Jacobians computations and IK.
The plan is to push next the geometric Jacobian computation and compare to the results obtained by AutoDiffXd'ing the code in this PR in some interesting model like the kuka arm.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7485)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-:-Kz0f6B1EA8aMl9MWUad:bltox9h)*

**Comment by hongkai-dai** [comment]
:lgtm: I have a few comments. +@sammy-tri for platform review please.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 543 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4d-BKubSuQn_-wiwV:-Kz4d-BKubSuQn_-wiwW:b-hjwa48) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.cc#L543)):*
> ```cpp
>     const Frame<T>& to_frame_A,
>     EigenPtr<Matrix3X<T>> p_AQi) const {
>   DRAKE_DEMAND(p_BQi.rows() == 3);
> ```

For my own education purpose, is this check still necessary, as `p_BQi` is of type `Eigen::Ref<const Matrix3X<T>>`?

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1008 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4bOO6E9e-qDCd-rlW:-Kz4bOO6E9e-qDCd-rlX:bscv6oy) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.h#L1008)):*
> ```objc
>   /// frame A can be computed from the position `p_BQ` of this point measured
>   /// and expressed in frame B using the transformation
>   /// `p_AQ(q) = X_AB(q)⋅p_BQ`.
> ```

I understand what `p_AQ(q) = X_AB(q)⋅p_BQ` means, but I think here we want to append 1 to `p_QA(q)` and `p_BQ`? Or  the dot in `X_AB(q)⋅p_BQ` is not a matrix multiplication, but represent the homogeneous transformation?

Also, does `p_BQ` depend on the posture `q`?

---

*[drake/multibody/multibody_tree/test/double_pendulum_test.cc, line 1268 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4dYWnMLrsAxkyFI9y:-Kz4dYWoK_Fr01tlq87S:bdhvd5w) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1268)):*
> ```cpp
>   p_LQi_set.col(0) << 0.0, -2.0, 0.0;  // At the end effector.
>   p_LQi_set.col(1) << 0.0, -1.0, 0.0;  // In the middle of the lower link.
>   p_LQi_set.col(2) << 0.0,  0.0, 0.0;  // At the elbow.
> ```

BTW, only the `y` component of `p_LQi_set` is non-zero. So if only the `y` column of the transformation `X_AB` were correct, the tests would still pass. Could you make `x` and `z` component of `p_LQi_set` also non-zero?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-:-Kz4eBP0-xuEtQ_0xRNE:b-8f54ih)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 543 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4d-BKubSuQn_-wiwV:-Kz4n1g0onQd16GW8voB:b-3kidcr) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.cc#L543)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For my own education purpose, is this check still necessary, as `p_BQi` is of type `Eigen::Ref<const Matrix3X<T>>`?
</blockquote></details>

Super good question. Actually I tried and I realized this didn't do what I expected. What it does:
- In Debug builds: Eigen asserts if you pass a matrix that doesn't have three rows.
- In Release builds: Eigen doesn't do anything and, the DRAKE_DEMAND below passes because the reference (or ptr) still returns 3 when you ask the number of rows! which is not what you want (what you want is that the test don't pass the demand when passing a matrix with other than 3 rows).

The solution: Now the argument is a `Ref<MatrixX>` so that even in Release builds I can DRAKE_DEMAND for the proper size. I added a new `DEATH` test verifying this.

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1008 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4bOO6E9e-qDCd-rlW:-Kz4uBOy40VBs1kiRfbF:b-24f89q) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.h#L1008)):*
> but I think here we want to append 1

I really don't understand what you mean by that.

> Also, does p_BQ depend on the posture q?

I see your point. I guess what I was trying to say is that even if `p_BQ` is fixed in B then your tranformed position vector `p_AQ` will, in general, depend on q. I can remove the `(q)` if that causes confusion.

---

*[drake/multibody/multibody_tree/test/double_pendulum_test.cc, line 1268 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4dYWnMLrsAxkyFI9y:-Kz4uneYaPkCNmDZLmgf:bc602gx) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1268)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, only the `y` component of `p_LQi_set` is non-zero. So if only the `y` column of the transformation `X_AB` were correct, the tests would still pass. Could you make `x` and `z` component of `p_LQi_set` also non-zero?
</blockquote></details>

BTW that would require me to do more math by hand. @mitiguy will be submitting a series of tests for the kuka arm for these methods that will go out of plane. Also my Jacobian tests soon to come tests this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.cc, line 543 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4d-BKubSuQn_-wiwV:-Kz5fWlBgmZe2nI5uRZt:b1oa0tp) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.cc#L543)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Super good question. Actually I tried and I realized this didn't do what I expected. What it does:
- In Debug builds: Eigen asserts if you pass a matrix that doesn't have three rows.
- In Release builds: Eigen doesn't do anything and, the DRAKE_DEMAND below passes because the reference (or ptr) still returns 3 when you ask the number of rows! which is not what you want (what you want is that the test don't pass the demand when passing a matrix with other than 3 rows).

The solution: Now the argument is a `Ref<MatrixX>` so that even in Release builds I can DRAKE_DEMAND for the proper size. I added a new `DEATH` test verifying this.
</blockquote></details>

Cool, that is good to learn, that we can pass a `MatrixXd` ad `Eigen::Ref<Matrix3Xd>`

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1008 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4bOO6E9e-qDCd-rlW:-Kz5eJnhR_SXJWZHH6B4:b-2ymdti) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.h#L1008)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> but I think here we want to append 1

I really don't understand what you mean by that.

> Also, does p_BQ depend on the posture q?

I see your point. I guess what I was trying to say is that even if `p_BQ` is fixed in B then your tranformed position vector `p_AQ` will, in general, depend on q. I can remove the `(q)` if that causes confusion.

</blockquote></details>

I mean `X_AB(q)` is a 4 x 4 matrix, representing the homogeneous transformation, `p_BQ` should be a a 4 x 1 vector, with the last entry being 1, to make the dimension of the matrix match.

I realized later here the dot operation is not a matrix multiplication, so there is no problem to write `X_AB(q)⋅p_BQ`. Please ignore that comment.

I think if you say it explicitly that `p_BQ` may or may not depend on `q`, it would make the meaning more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1054 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz5hsRBKIpnj4sBFY9z:-Kz5hsRCWyTBXNj7OMob:b3h4p1o) ([raw file](https://github.com/robotlocomotion/drake/blob/b9540e1dfc704f3a3678b7064e97954bc0c35607/drake/multibody/multibody_tree/multibody_tree.h#L1054)):*
> ```objc
>   void CalcPointsPositions(
>       const systems::Context<T>& context,
>       const Frame<T>& from_frame_B,
> ```

It seems a little odd that the order of the arguments `from_frame_B` and `to_frame_A` are swapped between this function and the one above it.

---

*[drake/multibody/multibody_tree/test/double_pendulum_test.cc, line 1333 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz5izzGz27dZH07NE-3:-Kz5izzHX-qMOqX7OTDk:bpne6y5) ([raw file](https://github.com/robotlocomotion/drake/blob/b9540e1dfc704f3a3678b7064e97954bc0c35607/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1333)):*
> ```cpp
>   // World positions of the set of points Qi:
>   Matrix3X<double> p_WQi_set(3, 3);
>   ASSERT_DEATH(model_->CalcPointsPositions(
> ```

I'd prefer that the code in `multibody_tree.cc` use `DRAKE_THROW_UNLESS` and this be `EXPECT_THROW` instead of writing a death test.  I believe this pattern is more common in the drake code, and death tests should generally be avoided if a better alternative is available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1008 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4bOO6E9e-qDCd-rlW:-Kz5p-zgM950BzSfp-Cm:bvuh65r) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.h#L1008)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I mean `X_AB(q)` is a 4 x 4 matrix, representing the homogeneous transformation, `p_BQ` should be a a 4 x 1 vector, with the last entry being 1, to make the dimension of the matrix match.

I realized later here the dot operation is not a matrix multiplication, so there is no problem to write `X_AB(q)⋅p_BQ`. Please ignore that comment.

I think if you say it explicitly that `p_BQ` may or may not depend on `q`, it would make the meaning more clear.
</blockquote></details>

Opted for removing `(q)` from that expression since I believe adding it would go outside the point I was trying to make and clearly added confusion. I think it is clear `X_AB` is a function of `(q)`?

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1054 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz5hsRBKIpnj4sBFY9z:-Kz5msM9ByV4U7j1H_Ga:b-xtgvs9) ([raw file](https://github.com/robotlocomotion/drake/blob/b9540e1dfc704f3a3678b7064e97954bc0c35607/drake/multibody/multibody_tree/multibody_tree.h#L1054)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems a little odd that the order of the arguments `from_frame_B` and `to_frame_A` are swapped between this function and the one above it.
</blockquote></details>

oh! there is a reason for it (or at least so I think). Let's see what you think:
For `CalcRelativeTransform()` I thought it made sense to have the input frames to match the order in which they appear in our monogram notation. Thus, if I want `X_AB`, I am passing `frame_A` first followed by `frame_B`.

For `CalcPointsPositions()` I liked the idea of having `FrameB` followed by `points_in_frame_B` and then `FrameA` followed by `output_points_in_frameA`. Notice that by style guide I am constrained to have the output `p_AQi` last.
Summarizing, I think it reads nicely; 
```c++
CalcPointsPositions(context, 
                    from_B, points_in_B, /* from */
                    from_A, &points_in_A); /* to */
``
of course I might be biased cause I wrote it myself :-). Let me know what you think.
```


---

*[drake/multibody/multibody_tree/test/double_pendulum_test.cc, line 1333 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz5izzGz27dZH07NE-3:-Kz5qXEnUlhzXXzz-Pwq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b9540e1dfc704f3a3678b7064e97954bc0c35607/drake/multibody/multibody_tree/test/double_pendulum_test.cc#L1333)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'd prefer that the code in `multibody_tree.cc` use `DRAKE_THROW_UNLESS` and this be `EXPECT_THROW` instead of writing a death test.  I believe this pattern is more common in the drake code, and death tests should generally be avoided if a better alternative is available.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/multibody_tree.h, line 1008 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-Kz4bOO6E9e-qDCd-rlW:-Kz7ZCx5gbi6M86roV-V:bnkv6ir) ([raw file](https://github.com/robotlocomotion/drake/blob/f8de8bc5eef051ee9a2ebd7b5bbcc3a75455406e/drake/multibody/multibody_tree/multibody_tree.h#L1008)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Opted for removing `(q)` from that expression since I believe adding it would go outside the point I was trying to make and clearly added confusion. I think it is clear `X_AB` is a function of `(q)`?
</blockquote></details>

Looks good. Now I don't think there is confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7485#-:-Kz9WL14jsUm09xXpM4F:bnfp4nl)*

**Pull request merged**
