### PR TITLE
Move functional_form from core to common

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This moves functional_form from `core/` to `common/`.  We don't want new code in `core`; it will be going away as System1 is removed.  Furthermore, this means that new code that wants functional form likely already has it linked in `libdrakeCommon`, instead of having to add `libdrakeCore` everywhere and then ripping it out later.

N.B. For review of these changes, the individual commits (browsed in github, not reviewable) may be easiest to review.  Still post comments in reviewable, though.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2993)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: Assuming this passes CI.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-:-KNtUnWnbdPjlr4xdO9F:-534171391)*

**Comment by jwnimmer-tri** [comment]
@sherm1 for platform review and merge, please.

**Comment by liangfok** [comment]
Reviewed 1 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993)*

**Comment by sherm1** [comment]
Platform: nice; some minor complaints.

---

Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/functional_form.h, line 187 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuTty-BkX-jG2DbQb5:-KNuTty-BkX-jG2DbQb6:2097013317) ([raw file](https://github.com/robotlocomotion/drake/blob/15a48c64be5006b8b5f4e132fc6b000fd7f158e2/drake/common/functional_form.h#L187)):*
> ```objc
>    * combined by the form.
>    */
>   friend DRAKECOMMON_EXPORT  // BR
> ```

I like the formatting, but not the `// BR`s. Those should be removed now that they've done their good work.

---

*[drake/common/functional_form.h, line 454 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuULiU55F0zRhdZ2Lb:-KNuULiVA-aLrne4INi7:-841602186) ([raw file](https://github.com/robotlocomotion/drake/blob/15a48c64be5006b8b5f4e132fc6b000fd7f158e2/drake/common/functional_form.h#L454)):*
> ```objc
>   /** Construct a variable identified by a non-negative numeric \p index.  */
>   // NOLINTNEXTLINE(runtime/explicit)
>   Variable(std::size_t index);
> ```

Shouldn't have `std::` here per style guide.

---

*[drake/common/functional_form.h, line 499 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuUWQUzf8mlz8le_HJ:-KNuUWQUzf8mlz8le_HK:-136085228) ([raw file](https://github.com/robotlocomotion/drake/blob/15a48c64be5006b8b5f4e132fc6b000fd7f158e2/drake/common/functional_form.h#L499)):*
> ```objc
> 
>   /** Print the variable's identifier, if any, to the given stream.  */
>   friend DRAKECOMMON_EXPORT  // BR
> ```

`// BR`, RIP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-:-KNuVH5SudIYgozOjSTp:976496271)*

**Comment by sherm1** [comment]
P.S. Wasn't a problem to review this in Reviewable.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-:-KNuVa62q7e5oDbP7T4q:1173878900)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/functional_form.h, line 187 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuTty-BkX-jG2DbQb5:-KNvZ8q6JzrV-4CalZa7:1675549142) ([raw file](https://github.com/robotlocomotion/drake/blob/f417af3583eb7cbcfb0e8526be2ee11f48bc6a1d/drake/common/functional_form.h#L187)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I like the formatting, but not the `// BR`s. Those should be removed now that they've done their good work.
</details>
Done.

The reason to live them in would be so that clang-format doesn't murder this file next time it's run.  But I'm content to defer the debate about "how to defend yourself from clang-format" until we decide to require it.

---

*[drake/common/functional_form.h, line 454 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuULiU55F0zRhdZ2Lb:-KNvZoxwkI72g2o0T_RW:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f417af3583eb7cbcfb0e8526be2ee11f48bc6a1d/drake/common/functional_form.h#L454)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Shouldn't have `std::` here per style guide.
</details>
Done.

---

*[drake/common/functional_form.h, line 499 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-KNuUWQUzf8mlz8le_HJ:-KNvZAJK4s5q1wqwP7Fz:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f417af3583eb7cbcfb0e8526be2ee11f48bc6a1d/drake/common/functional_form.h#L499)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `// BR`, RIP.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993)*

**Comment by liangfok** [comment]
Reviewed 1 of 12 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993)*

**Comment by jwnimmer-tri** [comment]
Looks like a matlab flake.
@drake-jenkins-bot retest this please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2993#-:-KNxLIbopE2Gw-FOlS2q:1417088721)*

**Pull request merged**
