### PR TITLE
Upgrade to Bazel 0.9.0 on Ubuntu

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I have already tested CLion compatibility a little bit, as part of #7843.

- [x] Do not merge until tested with CLion.
- [x] Do not merge until we test with -unprovisioned.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7846)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
Note there is a somewhat critical bug in 0.9.0 relating to the Mac toolchain per https://github.com/RobotLocomotion/drake-shambhala/issues/78.

**Comment by jwnimmer-tri** [comment]
> Note there is a somewhat critical bug in 0.9.0 relating to the Mac toolchain per RobotLocomotion/drake-shambhala#78.

Good point.  I'll update this to not touch the macOS info in `developers.rst` (leaving it at 0.6.1) within this PR.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7846#-:-L3hvDmqROv-4gNjyX_n:bnfp4nl)*

**Pull request merged**
