### PR TITLE
Added piecewise polynomial accessor for ppt

### PR DESCRIPTION
**Pull request by jefesaurus**
This is nice to be able to retrieve the complete polynomial output from the trajectory optimization routines without rewriting the `ReconstructTrajectory` functions in application code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4740)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Comment by Lucy-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4740#-KcyZlop3J9QvOSvLzep:-KcyZloq1FQRfA4_95eA:b14r17g) ([raw file](https://github.com/robotlocomotion/drake/blob/7f131afcc9fb4a2d95191370b41b5541520a101f/drake/common/trajectories/piecewise_polynomial_trajectory.h#L51)):*
> ```objc
>    * @return A reference to the underlying piecewise polynomial.
>    */
>   const PiecewisePolynomial<double>& piecewise_polynomial() const {
> ```

BTW consider naming this get_piecewise_polynomial()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4740)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4740)*

**Comment by jefesaurus** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/piecewise_polynomial_trajectory.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4740#-KcyZlop3J9QvOSvLzep:-KdJ9WWd6f82DE0lS5Sk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7f131afcc9fb4a2d95191370b41b5541520a101f/drake/common/trajectories/piecewise_polynomial_trajectory.h#L51)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

BTW consider naming this get_piecewise_polynomial()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4740)*

**Comment by jwnimmer-tri** [comment]
To @RussTedrake for a call on whether and how we want to accept this new API.

**Comment by RussTedrake** [comment]
:LGTM: -- This seems totally reasonable to me.  (Sorry I missed the original assignment)

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4740#-:-KeYmun3H0kS4ko6tiut:beyss5n)*

**Comment by jefesaurus** [comment]
okay, merged up to speed

**Pull request merged**
