### PR TITLE
discrete values: Avoid heap in non-converting SetFrom()

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #14802.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@damrongguoy for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbDAUKy-3WRzu91Ue8r:bh9uixl)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
FYI @edrumwri  -- does this answer the concern from #14802?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbDBcCd-The8EcvIaAr:b-jvwmld)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Comment by jwnimmer-tri** [comment]
___
*[systems/framework/discrete_values.h, line 154 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbDM-1X4_icfPEwDF4p:-MbDM-1X4_icfPEwDF4q:b180lxo) ([raw file](https://github.com/robotlocomotion/drake/blob/dd538759f8ff42bc0e1da82631ce1739d61a1b89/systems/framework/discrete_values.h#L154)):*
> ```objc
>     DRAKE_THROW_UNLESS(num_groups() == other.num_groups());
>     for (int i = 0; i < num_groups(); i++) {
>       if constexpr (std::is_same_v<T, U>) {
> ```

nit Here is a patch that avoids having different codepaths.  It passes the new unit test.

```patch
--- a/systems/framework/discrete_values.h
+++ b/systems/framework/discrete_values.h
@@ -151,13 +151,11 @@ class DiscreteValues {
   void SetFrom(const DiscreteValues<U>& other) {
     DRAKE_THROW_UNLESS(num_groups() == other.num_groups());
     for (int i = 0; i < num_groups(); i++) {
-      if constexpr (std::is_same_v<T, U>) {
-        data_[i]->set_value(other.get_vector(i).get_value());
-      } else {
-        data_[i]->set_value(
-            other.get_vector(i).get_value().unaryExpr(
-                scalar_conversion::ValueConverter<T, U>{}));
-      }
+      BasicVector<T>& this_i = *data_[i];
+      const BasicVector<U>& other_i = other.get_vector(i);
+      DRAKE_THROW_UNLESS(this_i.size() == other_i.size());
+      this_i.get_mutable_value() = other_i.get_value().unaryExpr(
+          scalar_conversion::ValueConverter<T, U>{});
     }
   }
 
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[systems/framework/test/discrete_values_limit_malloc_test.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbDoXFQ7g5SJwlZw6bk:-MbDoXFR-D1VfcBRE4CE:b8jgfjo) ([raw file](https://github.com/robotlocomotion/drake/blob/72aff9c1e16f7404afff79d10bb5f4dd1e512825/systems/framework/test/discrete_values_limit_malloc_test.cc#L26)):*
> ```cpp
> 
>     // Make a second object with the same "data shape".
>     b_.AppendGroup(std::make_unique<BasicVector<double>>(2));
> ```

buncha incorrect double types here that should be T.

**Review by edrumwri — COMMENTED** [review]
Absolutely addresses the issue I broached in #14802. Thanks @rpoyner-tri !!!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbDuVqUBrViS6MNlE3Z:bx8fn6o)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with minor questions.

Thank you for letting me learn about systems framework.

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbEzz3H4_aAkO_WS1Fm:b-yy3f95)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/analysis/BUILD.bazel, line 454 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbF-FL80E-nDlVWDrK8:-MbF-FL80E-nDlVWDrK9:b-84xmx7) ([raw file](https://github.com/robotlocomotion/drake/blob/c211c7cec802e6ffa7de34e10dac0da776ea84b9/systems/analysis/BUILD.bazel#L454)):*
> ```Starlark
>     name = "simulator_limit_malloc_test",
>     # TODO(#14901): This usage of LimitMalloc does not play nicely with Asan.
>     tags = ["no_asan"],
> ```

I confirm my understanding that this change in `analysis` is independent of the remaining change in `framework`, right?  I mean even without this change (removing `tags = ["no_asan"]`), this PR would still work, right?  I'm just curious.
___
*[systems/framework/BUILD.bazel, line 792 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbExPnV2FriLX6IkxVH:-MbExPnWBUUrBpmPG_Ad:bz2fs5d) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/BUILD.bazel#L792)):*
> ```Starlark
>         ":discrete_values",
>         "//common/test_utilities:limit_malloc",
>         "//systems/framework/test_utilities",
> ```

Nit: do we need this dependency?  I saw the `_test.cc` include `drake/systems/framework/test_utilities/my_vector.h`, but I didn't see `MyVector`.  It's possible that I didn't know enough `test_utilities` and missed something too.
___
*[systems/framework/test/discrete_values_limit_malloc_test.cc, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbEt0aDE-pOyJLMscam:-MbEt0aE4M4gu4Ru0wJ_:b-tixu2n) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/test/discrete_values_limit_malloc_test.cc#L7)):*
> ```cpp
> #include "drake/systems/framework/basic_vector.h"
> #include "drake/systems/framework/discrete_values.h"
> #include "drake/systems/framework/test_utilities/my_vector.h"
> ```

Nit: do we need `my_vector.h` here?  I searched for `MyVector` but couldn't find it.
___
*[systems/framework/test/discrete_values_limit_malloc_test.cc, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbEtuIOEo0zPiBWtJNq:-MbEtuIOEo0zPiBWtJNr:btezhaj) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/test/discrete_values_limit_malloc_test.cc#L20)):*
> ```cpp
> class DiscreteValuesLimitMallocFixture :public testing::Test {
>  public:
>   DiscreteValuesLimitMallocFixture() {
> ```

Question. Instead of `constructor()`, would `SetUp()` work too?  I read somewhere that SetUp() will allow error handling better, while the constructor might get into troubles if there're errors during initialization. I do not completely understand that argument though.

I'm fine with either way. I'm just curious.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @rpoyner-tri)

___
*[systems/analysis/BUILD.bazel, line 454 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbF-FL80E-nDlVWDrK8:-MbHEpT1CzXhlFlkf41s:b-ym3jgk) ([raw file](https://github.com/robotlocomotion/drake/blob/c211c7cec802e6ffa7de34e10dac0da776ea84b9/systems/analysis/BUILD.bazel#L454)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I confirm my understanding that this change in `analysis` is independent of the remaining change in `framework`, right?  I mean even without this change (removing `tags = ["no_asan"]`), this PR would still work, right?  I'm just curious.
</blockquote></details>

Correct. I just happened to notice that the old work-around was still there while preparing this patch. I can separate it if you like.
___
*[systems/framework/BUILD.bazel, line 792 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbExPnV2FriLX6IkxVH:-MbHF4FG-nGr_X1ogUSO:b6219n6) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/BUILD.bazel#L792)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit: do we need this dependency?  I saw the `_test.cc` include `drake/systems/framework/test_utilities/my_vector.h`, but I didn't see `MyVector`.  It's possible that I didn't know enough `test_utilities` and missed something too.
</blockquote></details>

Good call. I'll try without it.
___
*[systems/framework/test/discrete_values_limit_malloc_test.cc, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbEt0aDE-pOyJLMscam:-MbHFBTs4R9009xx5i3Q:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/test/discrete_values_limit_malloc_test.cc#L7)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Nit: do we need `my_vector.h` here?  I searched for `MyVector` but couldn't find it.
</blockquote></details>

ditto
___
*[systems/framework/test/discrete_values_limit_malloc_test.cc, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbEtuIOEo0zPiBWtJNq:-MbHFm1O0rMlzHgDul7J:bmqr54e) ([raw file](https://github.com/robotlocomotion/drake/blob/1daea894acc017d3bbd15ab790f50a96111db0fa/systems/framework/test/discrete_values_limit_malloc_test.cc#L20)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Question. Instead of `constructor()`, would `SetUp()` work too?  I read somewhere that SetUp() will allow error handling better, while the constructor might get into troubles if there're errors during initialization. I do not completely understand that argument though.

I'm fine with either way. I'm just curious.
</blockquote></details>

Either works in this  case, but SetUp is perhaps more idiomatic.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[systems/analysis/BUILD.bazel, line 454 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15118#-MbF-FL80E-nDlVWDrK8:-MbHH8QL8WE6S7PSP1S5:bsmzicp) ([raw file](https://github.com/robotlocomotion/drake/blob/c211c7cec802e6ffa7de34e10dac0da776ea84b9/systems/analysis/BUILD.bazel#L454)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Correct. I just happened to notice that the old work-around was still there while preparing this patch. I can separate it if you like.
</blockquote></details>

Separated. I'll push those lines as a single-reviewer patch separately.

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbHHS9j21uPVbbXr5Ah:b-8qo47q)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @DamrongGuoy and @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15118#-:-MbHLYpU9CrgIq2Jaz8I:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),DamrongGuoy (waiting on @rpoyner-tri)

**Pull request merged**
