### PR TITLE
Fixed Some Deprecated API Call Sites

### PR DESCRIPTION
**Pull request by liangfok**
This should be self explanatory.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3704)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

CC: @amcastro-tri  and @siyuanfeng-tri since you are the authors of the files touched by this PR.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3704#-:-KTPusJAB579MH8Em9bA:b4j1llh)*

**Comment by jwnimmer-tri** [comment]
:lgtm: jenkins likes it.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3704#-:-KTPzxMuJLwogWWeevdQ:bz32uti)*

**Comment by jwnimmer-tri** [comment]
(I meant to say, _assuming_ jenkins likes it.)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3704#-:-KTQ-2Qo7lHVB9yykXvc:birujo8)*

**Comment by liangfok** [comment]
I believe the MATLAB CI failures are due to the temporary disabling of MOSEK. @jwnimmer-tri can you force merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3704#-:-KTQT-Rn_w6vhnp4E0r9:b-g2nvq1)*

**Comment by jwnimmer-tri** [comment]
Yes: Jenkins was a test-only failure; this PR should only affect build or no-build.

Using override-merge.

**Pull request merged**
