### PR TITLE
Define and use a toolchain for Python and use rules_python for build rules

### LINKED ISSUE #11380: Obtain Python runtime from a toolchain rather than flag
Advance warning that bazelbuild/bazel#7899 will break Drake badly. WIP at https://github.com/RobotLocomotion/drake/compare/master...jamiesnape:incompatible-use-python-toolchains (last commit only, needs Bazel 0.25). FYI @EricCousineau-TRI.

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #12376 and closes #11380.

The following will need updating:

* https://github.com/RobotLocomotion/drake-external-examples/blob/master/drake_bazel_external/.bazelrc#L30-L35 - delete

* https://github.com/RobotLocomotion/drake-external-examples/blob/master/drake_bazel_external/WORKSPACE#L79-L80 - change to
```
load("@drake//tools/workspace:default.bzl", "add_default_workspace")
add_default_workspace()
```

* https://github.com/RobotLocomotion/drake-external-examples/blob/master/drake_bazel_external/apps/BUILD.bazel - add
```
load("@drake//tools/skylark:py.bzl", "py_binary", "py_test")
```

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12377)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Very neat!  Ping me anytime you'd like me to test vs Anzu for any early feedback.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@jwnimmer-tri I think is in good enough shape to try on Anzu. I am hoping it is as simple as adding something along the lines of the following to your `WORKSPACE`:
```python
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
register_toolchains("@drake//tools/py_toolchain:linux_toolchain")
```

**Comment by jwnimmer-tri** [comment]
FYI Good background reading for interested parties:
https://docs.bazel.build/versions/master/toolchains.html

**Comment by jamiesnape** [comment]
I had missed changing a few `native.py_*` to `py_*` in `drake_py.bzl` and fixing that has made life much more complicated - basically because of this function https://github.com/bazelbuild/rules_python/blob/94677401bc56ed5d756f50b441a6a5c7f735a6d4/python/defs.bzl#L37-L42
and how we manipulate tags in the `drake_py_*` rules.

**Comment by jwnimmer-tri** [comment]
> > No bzl code should ever try to modify its arguments, full stop.
>
> That is an oversimplification.

You're right.  I also forgot that we frequently do `kwargs.pop()` in our macros.

Anyway, I happened across https://github.com/bazelbuild/rules_cc/commit/cfe68f6bc79dea602f2f6a767797f94a5904997f so it looks like upstream agrees that the bzl definitions should be fixed.

**Comment by jamiesnape** [comment]
https://github.com/bazelbuild/rules_python/pull/262

**Comment by jamiesnape** [comment]
The `rules_python` tags fix merged. Switch to `master`?

**Comment by jwnimmer-tri** [comment]
Sure, sounds good to me.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please

**Pull request merged**
