### PR TITLE
[C-IRIS] move cspace_free_polytope_with_mosek_test.cc out of dev.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18909)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

The code has been feature-reviewed in the dev folder, could you do a platform review to move it out of dev?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-:-NPT0Z88BNIr2uftQ-lf:bl7frce)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok)  (since already feature reviewed)
Platform :lgtm: pending a few nits

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-:-NPUMrW9-ElZtXJ36j2L:b9mq3g9)* status: 6 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 64 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPU7yug2cbFoS4I5oQ2:-NPU7yuh5ItSNLOD0MIL:b-kx26r0) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L64)):*
> ```cpp
> }
> 
> // Solve a sos program to check if a polynomial is sos.
> ```

BTW not sure how you pronounce "sos". If it is S-O-S then it should be "_an_ SOS program". If you pronounce it like "soss" then "_a_ sos program" is right.
___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUANm8AjMFy3_qYq-l:-NPUANm8AjMFy3_qYq-m:b-5udb57) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L135)):*
> ```cpp
> 
> // @param a Maps the plane index to the separating plane parameter {x| aᵀx+b=0}
> // @param b Maps the plane index to the separating plane parameter {x| aᵀx+b=0}
> ```

BTW this seems to be an oddly abbreviated comment. Both comments are the same and the other 6 parameters (including C and d) are undocumented. Consider expanding some?
___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 209 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUD7GL6Oy8JOYwHiYR:-NPUD7GL6Oy8JOYwHiYS:biu59iy) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L209)):*
> ```cpp
> // Check if rationals are all positive in the C-space polytope. Note that for
> // some reason Mosek doesn't solve to a very high precision (the constraint
> // violation can be in the order of 1E-3, even if  Mosek reports success), so we
> ```

nit: extra space before Mosek
___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 250 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUDlOT5z7F08l-BUQW:-NPUDlOU66U3kbynMyxg:b5znv8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L250)):*
> ```cpp
>   C << 1, 1, 0,
>        -1, -1, 0,
>        -1, 0, 1,
> ```

BTW as long as you're nice formatting the matrix, consider lining up the (imaginary) decimal points as below.



_Suggestion:_
```cpp
  C <<  1,  1, 0,
       -1, -1, 0,
       -1,  0, 1,
```
___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 338 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUEsyVAP7niRllLnUt:-NPUEsyVAP7niRllLnUu:b3alzrw) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L338)):*
> ```cpp
>     s_samples << 1, 2, -1,
>                -0.5, 0.3, 0.2,
>                0.2, 0.1, 0.4,
> ```

BTW same suggestion here and below (line up decimal points)



_Suggestion:_
```cpp
    s_samples << 1,   2,  -1,
                -0.5, 0.3, 0.2,
                 0.2, 0.1, 0.4,
```
___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 790 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUJl8x-Xm-lKWWNr4u:-NPUJl8x-Xm-lKWWNr4v:b7f4bbp) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L790)):*
> ```cpp
>   }
> 
>   // Now test the public InitializePolytopeSearchProgram function
> ```

nit: missing period

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18909)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @hongkai-dai)

___
*[`geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc` line 135 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18909#-NPUANm8AjMFy3_qYq-l:-NPUnvIw8ew-W1ESkQme:b-iudpjk) ([raw file](https://github.com/RobotLocomotion/drake/blob/84efab0f3b59a7439ac08e9360967589ea7f6eaa/geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc#L135)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems to be an oddly abbreviated comment. Both comments are the same and the other 6 parameters (including C and d) are undocumented. Consider expanding some?
</blockquote></details>

Done. I added some documentation.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18909)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
