### PR TITLE
Unbreak python `import lcm` within the sandbox

### LINKED ISSUE #7712: bazel run @optitrack_driver//src:optitrack_client is broken
`bazel run @optitrack_driver//src:optitrack_client` is broken, with:
```console
jwnimmer@call-cc:~/jwnimmer-tri/drake$ bazel run @optitrack_driver//src:optitrack_client
...
INFO: Running command line: bazel-bin/external/optitrack_driver/src/optitrack_client
Traceback (most recent call last):
  File "/home/jwnimmer/.cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/drake/bazel-out/clang-4.0-linux-opt/bin/external/optitrack_driver/src/optitrack_client.runfiles/drake/../optitrack_driver/src/optitrack_client.py", line 11, in <module>
    import lcm
  File "/home/jwnimmer/.cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/drake/bazel-out/clang-4.0-linux-opt/bin/external/optitrack_driver/src/optitrack_client.runfiles/lcm/__init__.py", line 1, in <module>
    execfile(__path__[0] + "/lcm-python/lcm/__init__.py")
  File "/home/jwnimmer/.cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/drake/bazel-out/clang-4.0-linux-opt/bin/external/optitrack_driver/src/optitrack_client.runfiles/lcm/lcm-python/lcm/__init__.py", line 3, in <module>
    from ._lcm import LCM, LCMSubscription
ImportError: liblcm.so: cannot open shared object file: No such file or directory
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

Apparently f50d3b0041a5d5dfee73a3a6ef5035c615dc5592 was the culprit.  The work-around is to launch the optitrack client after running the install step -- the installed copy appears to work fine.

/CC @sammy-tri

### LINKED ISSUE #7779: ImportError: liblcm.so: cannot open shared object file: No such file or directory
```
~/Drake$ bazel build automotive:demo automotive:car_sim_lcm
INFO: Analysed 2 targets (1 packages loaded).
INFO: Found 2 targets...
INFO: Elapsed time: 18.599s, Critical Path: 2.79s
INFO: Build completed successfully, 32 total actions
aaron@aaron-VirtualBox:~/Drake$ bazel-bin/automotive/steering_command_driver
Traceback (most recent call last):
  File "/home/aaron/Drake/bazel-bin/automotive/steering_command_driver.runfiles/drake/automotive/steering_command_driver.py", line 18, in <module>
    import lcm
  File "/home/aaron/Drake/bazel-bin/automotive/steering_command_driver.runfiles/lcm/__init__.py", line 1, in <module>
    execfile(__path__[0] + "/lcm-python/lcm/__init__.py")
  File "/home/aaron/Drake/bazel-bin/automotive/steering_command_driver.runfiles/lcm/lcm-python/lcm/__init__.py", line 3, in <module>
    from ._lcm import LCM, LCMSubscription
ImportError: liblcm.so: cannot open shared object file: No such file or directory
```
Manually installing lcm is a workaround

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #7712.  Fixes #7779.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7788)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/lcm/package.BUILD.bazel, line 214 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7788#-L36Di4ic3GWWpCYxGzF:-L36Di4ic3GWWpCYxGzG:bx20q5u) ([raw file](https://github.com/robotlocomotion/drake/blob/db6ffd12c30548a486fb0fa47d02204bd0550096/tools/workspace/lcm/package.BUILD.bazel#L214)):*
> ```
> ctypes.cdll.LoadLibrary(os.path.realpath(__path__[0] + '/_lcm.so'))
> execfile(__path__[0] + \"/lcm-python/lcm/__init__.py\")
> """.format(repository = repository_name()[1:]),
> ```

Oops, the `.format()` piece here is vestigial; will remove in next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7788)*

**Comment by jwnimmer-tri** [comment]
Mac builds passed:
- https://drake-jenkins.csail.mit.edu/job/mac-highsierra-clang-bazel-experimental/56/
- https://drake-jenkins.csail.mit.edu/job/mac-sierra-clang-bazel-experimental/83/

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.  Let me know if you'd like a second reviewer.

**Comment by soonho-tri** [comment]
:lgtm: but I think it's worth have +@jamiesnape as another reviewer.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7788#-:-L38tJJGQSmumWG8WXOP:bcxl1zk)*

**Comment by jwnimmer-tri** [comment]
FYI I also meant to add -- at some point the better answer might be to rename the repository to not be `@lcm` anymore to avoid these problems, but _shrug_.

**Pull request merged**
