### PR TITLE
Mute Gurobi's warning on small coefficients.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Gurobi throws warning if the coefficients is less than 1E-13. We check the coefficients of our problem data, and do not add the coefficient entry if it is smaller than 1E-13.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-:-Nzji3vA-viUSwI0CeOD:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
You beat me to it :)
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-:-NzjkhgvAQbDbbfgGNtQ:b-95ticj)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/gurobi_solver_internal.cc` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-NzjkJZh3jfWNZgdoIe9:-NzjkJZh3jfWNZgdoIeA:b-cdt3ay) ([raw file](https://github.com/RobotLocomotion/drake/blob/4cfc40b659c11cc9db3a1cf7b2c1ed431dc368f5/solvers/gurobi_solver_internal.cc#L35)):*
> ```cpp
>   Eigen::SparseMatrix<double, Eigen::RowMajor> A_row_major(A.rows(), A.cols());
>   A_row_major.setFromTriplets(A_row_major_triplets.begin(),
>                               A_row_major_triplets.end());
> ```

btw: I think you can write this more simply as



_Suggestion:_
```cpp
Eigen::SparseMatrix<double, Eigen::RowMajor> A_row_major = A;
A_row_major.prune(kGurobiZeroTol);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/gurobi_solver_internal.cc` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-NzjkJZh3jfWNZgdoIe9:-NzjvAs658LjJaWHiXPa:bx04aw8) ([raw file](https://github.com/RobotLocomotion/drake/blob/4cfc40b659c11cc9db3a1cf7b2c1ed431dc368f5/solvers/gurobi_solver_internal.cc#L35)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

btw: I think you can write this more simply as
</blockquote></details>

I am unsure about the behavior of `Eigen::SparseMatrix::prune` function, according to its documentation https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#ab4b7ffe0c08f653f5c34b02b9b12e6bf
```
Suppresses all nonzeros which are much smaller than reference under the tolerance epsilon

```
what does "much smaller than" mean here? Does it remove all entries smaller than `reference * epsilon`?

**Comment by shaoyuancc** [comment]
Can confirm that this PR solves my gurobi warning problem. Thanks!

**Review by shaoyuancc — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/gurobi_solver_internal.cc` line 35 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-NzjkJZh3jfWNZgdoIe9:-NzoCnBWBvRSqaJ74GmV:boyexb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/4cfc40b659c11cc9db3a1cf7b2c1ed431dc368f5/solvers/gurobi_solver_internal.cc#L35)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Sorry it should be
`A.pruned(1,kGurobiZeroTol)`

See here: https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html#ac8d0414b56d9d620ce9a698c1b281e5d
</blockquote></details>

Done. Thanks!

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by AlexandreAmice — COMMENTED** [review]
+@ggould-tri for platform. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-:-O-4C-p16JGBWDclqCRR:bt95fqq)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-:-O-6kbaQ-r9ehj3nML00:bnfp4nl)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/gurobi_solver_internal.cc` line 23 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21540#-O-6khdFAoDCndICBC_B:-O-6khdFAoDCndICBC_C:b-1691la) ([raw file](https://github.com/RobotLocomotion/drake/blob/51447857926ca186db606a61ca64ade2d15cb201/solvers/gurobi_solver_internal.cc#L23)):*
> ```cpp
>   // Gurobi add the linear constraint row by row, so we will need a row-major
>   // sparse matrix. Besides, Gurobi will throw a warning if the coeffient is
>   // less than 1E-13, so we filter out these small entries.
> ```

minor:  "Gurobi will throw a warning if the coeffient is less than 1E-13"  is the explanation for the value of `kGurobiZeroTol` and so it should be the documentation of that constant.  That would also clarify to people that unlike other constants named "Tol" this one is a feature of an external component and should not be dialed up and down to make tests pass.



_Code quote:_
```cpp
  // sparse matrix. Besides, Gurobi will throw a warning if the coeffient is
  // less than 1E-13, so we filter out these small entries.
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21540)* status: missing label for release notes

**Pull request merged**
