### PR TITLE
[skylark] Set num_threads for test concurrency control

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Tests that do not opt-in to concurrency will be limited to 1 thread.

---

Reviewable r1 contains code copied from Anzu; r2 and onward contain Drake's integration changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18546)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: (obviously lifted from Anzu.  :)) I'd looked at this code before the break when I was getting the collision checker tests happy in Drake. Thanks for doing this. 

+@seancurtis-tri 

> Reviewed 1 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18546#-:-NLC69CP9i1E5_GmJO3R:b-lp30xc)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`tools/skylark/drake_py.bzl` line 180 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18546#-NLC4r2c5kocPizZYVn5:-NLC4r2c5kocPizZYVn6:b828le1) ([raw file](https://github.com/robotlocomotion/drake/blob/a875ac1b93f1e6ab389e0e52f504cd7074a010c8/tools/skylark/drake_py.bzl#L180)):*
> ```Starlark
>     to "small" to indicate a unit test.
> 
>     @param num_threads (optional, default is 1)
> ```

BTW There's a subtlety on this one. The "number of threads" defaults to one. But `num_threads` defaults to `None`. 

Given `incorporate_num_threads` is called unconditionally, why default this to `None` instead of 1? And, if there's a reason, why blur that reason in the documentation?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18546)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[`tools/skylark/drake_py.bzl` line 180 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18546#-NLC4r2c5kocPizZYVn5:-NLCHZqd1Rzw_E3wsSWK:b-7m3jzo) ([raw file](https://github.com/robotlocomotion/drake/blob/a875ac1b93f1e6ab389e0e52f504cd7074a010c8/tools/skylark/drake_py.bzl#L180)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW There's a subtlety on this one. The "number of threads" defaults to one. But `num_threads` defaults to `None`. 

Given `incorporate_num_threads` is called unconditionally, why default this to `None` instead of 1? And, if there's a reason, why blur that reason in the documentation?
</blockquote></details>

Done.

Some of the `drake_foo_bar` macros are somewhat inconsistent about argument handling.  Now that we have `amend()` in Drake, I plan to open another PR down the road that cleans up and simplifies the macros to (1) be phrased in terms of `amend` and (2) to very clearly document which argument names they inherit from Bazel's built-in rules, and what novel arguments they add on top of those.  I'd originally started do to that locally in this PR but it got too confusing to do it all at once.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18546)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18546#-:-NLMV_Mw6lxA0HpFFr7x:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Good point -- the flag only configures the environment's thread limits.  The overall build configuration and/or actual runtime hardware might end up further limiting the number of available threads.  I can work on a documentation update to clarity.

**Pull request merged**
