### PR TITLE
Port automotive_demo.py launcher to Bazel

### LINKED ISSUE #4574: Consider limiting drake/automotive CMake integration
Can anyone think of a good reason to keep the `CMakeLists.txt` support for `drake/automotive`?

I think I'm one PR from having all of `drake/automotive` tested and demo-able under the Bazel instructions.  In the future, once #4131 and #4303 are done we would end up shipping the library and message portions of `drake/automotive` as part of an overall `libDrake`.  Still, many demos would be documented and buildable only via Bazel.

So once we have Bazel ready, and confirmed working for the automotive development team, is there any reason I can't just delete the `CMakeLists.txt` support (and thus simplify our dev cycle to worry about one less build system most of the time)?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This PR is (1) build system changes, (2) source code changes at its touch-point with the build system, and (3) documentation updates.

I have tested it extensively locally, but reviewers should definitely pull this code and test for themselves as well.

Closes #4574.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4737)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Note to reviewers -- I will remove the "Try nerfing a warning for CTest" commit before final merge.  It's just there to get CI passing for now.

**Comment by jwnimmer-tri** [comment]
+@liangfok and +@rpoyner-tri both for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaDYSI4GVMdqhr95AiI:b-xlyhru)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/soft_failure.bzl, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDkEf_i5Zcpqd0egTD:-KaDkEfaToxlA2eyPYzR:b-c0l6yb) ([raw file](https://github.com/robotlocomotion/drake/blob/a6833cc0d19aad956f5fb41a2eb352049861998f/tools/soft_failure.bzl#L89)):*
> ```Python
>     # The sh_binary source code will be one of the two wrapper scripts above.
>     BUILD = """
>     data = glob(["{symlink_basename}"]) or print("{warning}")
> ```

Note to reviewers -- this change will not be merged, just a CI shim for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri will be platform.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaDkw50RCRmueN4Q3nE:b-qas205)*

**Comment by rpoyner-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDljiB5ejUwnYdeTkw:-KaDljiCX3WrzmOaGjUA:bpmnh1m) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/automotive_demo.py#L68)):*
> ```Python
>                 self.name, command[0])
>             sys.stdout.flush()
>             subprocess.call(["/usr/bin/find", "-L", "."])
> ```

Do we know what directory "." evaluates to here? Are we just going to get flooded with a ton of file names that run off the screen?

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaDftnxV1WWyZ9bOsLN:bh0ulol) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
> ```Markdown
> ```
> $ cd drake-distro
> $ bazel run /drake/automotive:demo
> ```

doesn't this need to start with 2 slashes: `//drake/automotive:demo` ? Or apparently 0 initial slashes, but 1 does not work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_demo.py, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDljiB5ejUwnYdeTkw:-KaDo7n_4apJdhKcVzFr:bt1unt0) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/automotive_demo.py#L68)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do we know what directory "." evaluates to here? Are we just going to get flooded with a ton of file names that run off the screen?
</blockquote></details>

It's the runfiles area, so just the jars, programs, and data.  Maybe 100 lines.  Hopefully this only happens during workstation development, though -- when the source code here and BUILD file dependencies disagree?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDljiB5ejUwnYdeTkw:-KaDr6eUo4ygGEJv3hcK:bm85fyr) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/automotive_demo.py#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's the runfiles area, so just the jars, programs, and data.  Maybe 100 lines.  Hopefully this only happens during workstation development, though -- when the source code here and BUILD file dependencies disagree?
</blockquote></details>

meh, ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Checkpoint. I'm still trying to get this work on my machine. (Tried and failed on Ubuntu Trusty: #4752, attempting on an Ubuntu Xenial now.)

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDlmyqGaG9vk0Tc6gc:-KaDlmyqGaG9vk0Tc6gd:b-2zlefq) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/automotive_demo.py#L200)):*
> ```Python
> 
>     try:
>         print "*** LCM logs will be in", os.getcwd()
> ```

BTW, consider adding a space after "in".

---

*[drake/automotive/BUILD, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDm_S5c3zER9NAxPhk:-KaDm_S5c3zER9NAxPhl:b-7o2c1) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L169)):*
> ```Python
>         ":models",
>     ],
>     deps = [
> ```

BTW, in Bazel, is there a need to declare that `car_sim_lcm` depends on ":speed_bump_genrule"`?

---

*[drake/automotive/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDmzxxFIPMl-m8387W:-KaDmzxxFIPMl-m8387X:b-9h9x03) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L10)):*
> ```Markdown
> system; only the demo is Bazel-specific.
> 
> Running the demo
> ```

BTW, consider capitalizing "Demo".

---

*[drake/automotive/README.md, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDnYLTCaz_hYhJ9IaC:-KaDnYLUUVCqEZFJbxnQ:bnwze72) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L38)):*
> ```Markdown
> ```
> 
> Running the dynamics
> ```

BTW, consider capitalizing "Dynamics".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaDwFKS5TbltaQ52Gu1:by4crz5)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/automotive/BUILD, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDvYXzoo3fj05R7867:-KaDvYY-yKNEZaxTQfsu:b-ontojq) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L189)):*
> ```Python
> java_binary(
>     name = "lcm-spy",
>     main_class = "lcm.spy.Spy",
> ```

FYI I'm not sure how I feel about scattering binaries called "lcm-spy" around the build directories which all know about different LCM types.

---

*[drake/automotive/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDmzxxFIPMl-m8387W:-KaDzznGPbANwoEEPtPC:bautu3f) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider capitalizing "Demo".
</blockquote></details>

BTW That seems like an odd word to capitalize to me...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaE-yF9YS6-2fvOB-5C:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDmzxxFIPMl-m8387W:-KaE0F8CQ5-MUGhTT84m:b-2okbsi) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW That seems like an odd word to capitalize to me...
</blockquote></details>

I'll leave it to the author's discretion.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaE0UGBODABkpp2oxUh:b-vmm1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

doesn't this need to start with 2 slashes: `//drake/automotive:demo` ? Or apparently 0 initial slashes, but 1 does not work.
</blockquote></details>

I confirm that this is a real issue:

```
$ bazel run /drake/automotive:demo
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/drake/automotive:demo'.
INFO: Elapsed time: 4.725s
ERROR: Build failed. Not running target.
```

When I run with zero slashes, I encounter a different error:

```
$ bazel run drake/automotive:demo
INFO: Found 1 target...
Target //drake/automotive:demo up-to-date:
  bazel-bin/drake/automotive/demo
INFO: Elapsed time: 1.076s, Critical Path: 0.07s

INFO: Running command line: bazel-bin/drake/automotive/demo
*** LCM logs will be in /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/demo.runfiles/drake
[automotive_demo.py] drake-visualizer exited 1
soft_failure.bzl: @drake_visualizer//:drake-visualizer does not work because /home/liang/dev/drake-distro-1/build/install/bin/drake-visualizer was missing
[automotive_demo.py] drake-visualizer failed to launch
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDlmyqGaG9vk0Tc6gc:-KaE0PN7H27KxQuBxlI4:b-4lgouy) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/automotive_demo.py#L200)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a space after "in".
</blockquote></details>

That's what the `,` does.

---

*[drake/automotive/BUILD, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDm_S5c3zER9NAxPhk:-KaE0ZR0tPigckTnCqnm:b-atxr4c) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L169)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, in Bazel, is there a need to declare that `car_sim_lcm` depends on ":speed_bump_genrule"`?
</blockquote></details>

Nope.  That is implied via `:models`, since the generated `obj` is listed in the `:models` sources, and Bazel understands the dependencies required to generate it.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaE0xQ64YPmYqrDFDtn:b-87h3lf) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I confirm that this is a real issue:

```
$ bazel run /drake/automotive:demo
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/drake/automotive:demo'.
INFO: Elapsed time: 4.725s
ERROR: Build failed. Not running target.
```

When I run with zero slashes, I encounter a different error:

```
$ bazel run drake/automotive:demo
INFO: Found 1 target...
Target //drake/automotive:demo up-to-date:
  bazel-bin/drake/automotive/demo
INFO: Elapsed time: 1.076s, Critical Path: 0.07s

INFO: Running command line: bazel-bin/drake/automotive/demo
*** LCM logs will be in /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/demo.runfiles/drake
[automotive_demo.py] drake-visualizer exited 1
soft_failure.bzl: @drake_visualizer//:drake-visualizer does not work because /home/liang/dev/drake-distro-1/build/install/bin/drake-visualizer was missing
[automotive_demo.py] drake-visualizer failed to launch
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
</blockquote></details>

Yes of course Rick is right.

The drake-visualizer message points out that I'm missing a documentation item -- that you either have to also build with CMake, or disable the visualizer.  Stay tuned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDvYXzoo3fj05R7867:-KaE1nOZiKXQ817K1jfa:bwckezq) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L189)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

FYI I'm not sure how I feel about scattering binaries called "lcm-spy" around the build directories which all know about different LCM types.
</blockquote></details>

Would a different name help?  This tool is known as either `//drake/automotive:lcm-spy` or `bazel-bin/drake/automotive/lcm-spy`.  I could have it be `:automotive-lcm-spy` if you felt that was important for clarity, even if a bit longer?  I think I would be easily convinced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDm_S5c3zER9NAxPhk:-KaE3STuTDBSbMSHYS99:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L169)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nope.  That is implied via `:models`, since the generated `obj` is listed in the `:models` sources, and Bazel understands the dependencies required to generate it.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaE3W6pxHAG5lMdOzJ7:b-vgjwvm) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes of course Rick is right.

The drake-visualizer message points out that I'm missing a documentation item -- that you either have to also build with CMake, or disable the visualizer.  Stay tuned.
</blockquote></details>

Done (for both defects).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDvYXzoo3fj05R7867:-KaE7iN4n2ZvmIlwAp45:b-yru88f) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/BUILD#L189)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Would a different name help?  This tool is known as either `//drake/automotive:lcm-spy` or `bazel-bin/drake/automotive/lcm-spy`.  I could have it be `:automotive-lcm-spy` if you felt that was important for clarity, even if a bit longer?  I think I would be easily convinced.
</blockquote></details>

Actually...  I think I originally thought that the lcm types would be part of the resulting binary.  Now that I realize they're runtime_deps and just along side it, I don't think I care.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaE9JhoCj0V7eXn3Dbm:bdy16m3) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (for both defects).
</blockquote></details>

Help! I'm encountering the following problem:

```
$ bazel run //drake/automotive:demo --no-visualizer
Unrecognized option: --no-visualizer
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaEBOm0h0mWg4_6-pqN:bk1s48r) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Help! I'm encountering the following problem:

```
$ bazel run //drake/automotive:demo --no-visualizer
Unrecognized option: --no-visualizer
```
</blockquote></details>

In `bazel run`, you use `--` to separate bazel args from the program's args, so `bazel run drake/automotive:demo -- --no-visualizer`.  If you run the problem without bazel, then `bazel-bin/automotive/demo --no-visualizer` directly just works tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
:lgtm: since it works on my Ubuntu Trusty workstation.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaECcqIcGe8FW9wsq-P:b398vb) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In `bazel run`, you use `--` to separate bazel args from the program's args, so `bazel run drake/automotive:demo -- --no-visualizer`.  If you run the problem without bazel, then `bazel-bin/automotive/demo --no-visualizer` directly just works tool.
</blockquote></details>

Thanks. I suppose this is expected to be common knowledge?

BTW, it now runs on my computer, but I'm seeing this error:

```
[lcm-spy] ClassDiscoverer: java.lang.NoClassDefFoundError: com/jidesoft/swing/RangeSlider
[lcm-spy]                  jar: /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/lcm-spy.runfiles/drake/../net_sf_jchart2d_jchart2d/jar/jchart2d-3.3.2.jar
[lcm-spy]                  class: info/monitorenter/gui/chart/controls/RangeChooserPanel.class
[lcm-spy] ClassDiscoverer: java.lang.NoClassDefFoundError: org/apache/xmlgraphics/java2d/ps/EPSDocumentGraphics2D
[lcm-spy]                  jar: /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/lcm-spy.runfiles/drake/../net_sf_jchart2d_jchart2d/jar/jchart2d-3.3.2.jar
[lcm-spy]                  class: info/monitorenter/gui/chart/events/Chart2DActionSaveEpsSingletonApacheFop$Chart2DActionSaveEps.class
```

Is this a known issue? Perhaps unrelated to this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaECzxpJddLomdyGcX4:b-p7muzi)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaEDVW6eecP3OrODWC8:bqbufe8) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Thanks. I suppose this is expected to be common knowledge?

BTW, it now runs on my computer, but I'm seeing this error:

```
[lcm-spy] ClassDiscoverer: java.lang.NoClassDefFoundError: com/jidesoft/swing/RangeSlider
[lcm-spy]                  jar: /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/lcm-spy.runfiles/drake/../net_sf_jchart2d_jchart2d/jar/jchart2d-3.3.2.jar
[lcm-spy]                  class: info/monitorenter/gui/chart/controls/RangeChooserPanel.class
[lcm-spy] ClassDiscoverer: java.lang.NoClassDefFoundError: org/apache/xmlgraphics/java2d/ps/EPSDocumentGraphics2D
[lcm-spy]                  jar: /home/liang/.cache/bazel/_bazel_liang/ede03c0a430a52111efe35db021d2956/execroot/drake-distro-1/bazel-out/local-opt/bin/drake/automotive/lcm-spy.runfiles/drake/../net_sf_jchart2d_jchart2d/jar/jchart2d-3.3.2.jar
[lcm-spy]                  class: info/monitorenter/gui/chart/events/Chart2DActionSaveEpsSingletonApacheFop$Chart2DActionSaveEps.class
```

Is this a known issue? Perhaps unrelated to this PR?
</blockquote></details>

Yes, `lcm-spy` always prints that when you decide not to use some of its optional poorly-licensed dependencies.  I haven't tried to look into suppressing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/README.md, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaDftnxV1WWyZ9bOsLM:-KaEDs1hNy4g8Wy06-CG:b-4ekr2m) ([raw file](https://github.com/robotlocomotion/drake/blob/ce129e32d79ca8eae8860a80b252ff5e002a54a2/drake/automotive/README.md#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, `lcm-spy` always prints that when you decide not to use some of its optional poorly-licensed dependencies.  I haven't tried to look into suppressing that.
</blockquote></details>

OK. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-:-KaEJG5sZapFtlTL0Ion:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaETpshe9aZNgG9ea7x:-KaETpsiMUMhPLgIw5Zy:b-de0kdk) ([raw file](https://github.com/robotlocomotion/drake/blob/823a88f38a878a0a3b23509e72ec8edf605a3d4d/drake/automotive/automotive_demo.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

*Meta* From kitchen chat -- remove this line, since it can't possibly work without its dependencies provided, which only happens when its compiled via `py_binary`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaETpshe9aZNgG9ea7x:-KaEYj_5Qd1kJ1hNAVTM:b-tag6ae) ([raw file](https://github.com/robotlocomotion/drake/blob/823a88f38a878a0a3b23509e72ec8edf605a3d4d/drake/automotive/automotive_demo.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

*Meta* From kitchen chat -- remove this line, since it can't possibly work without its dependencies provided, which only happens when its compiled via `py_binary`.
</blockquote></details>

Hm, do we get to remove the executable permissions as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_demo.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4737#-KaETpshe9aZNgG9ea7x:-KaFHeADtTTlBQtziSAF:b-z05y8j) ([raw file](https://github.com/robotlocomotion/drake/blob/823a88f38a878a0a3b23509e72ec8edf605a3d4d/drake/automotive/automotive_demo.py#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, do we get to remove the executable permissions as well?
</blockquote></details>

Yup.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4737)*

**Comment by jwnimmer-tri** [comment]
Using override-merge for automotive-only change and only the matlab build remains unfinished.

**Pull request merged**
