### PR TITLE
workspace: Upgrade fmt to latest release 7.1.3

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14413)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14413)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[common/text_logging.h, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14413#-MO--rGi8m2K35QrIq26:-MO--rGi8m2K35QrIq27:bv7nn1g) ([raw file](https://github.com/robotlocomotion/drake/blob/d7bde8f23b0a9204af1aa8aa2a6526e89ec83dbb/common/text_logging.h#L26)):*
> ```objc
> </pre>
> 
> The format string syntax is fmtlib; see https://fmt.dev/7.1.3/syntax.html.
> ```

Oddly this URL does not exist -- gives a 404. 7.1.2 does exist. Consider using that one or pounding on upstream?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14413)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[common/text_logging.h, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14413#-MO--rGi8m2K35QrIq26:-MO-3L-X3OBH5-huJ-I_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7bde8f23b0a9204af1aa8aa2a6526e89ec83dbb/common/text_logging.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oddly this URL does not exist -- gives a 404. 7.1.2 does exist. Consider using that one or pounding on upstream?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14413#-:-MO-837v1zX3E1U9NcbP:b4xzgsb)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
