### PR TITLE
Documents Meaning of Q, V, and X in KinematicsCache.

### PR DESCRIPTION
**Pull request by liangfok**
IMHO, the more documentation the better.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4662)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-:-K_a4-8KXnpF-Qs1lA22:b-uxw1os)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/kinematics_cache.h, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6UZ76rhAI6fxeC8n:-K_a6UZ76rhAI6fxeC8o:bvwttf8) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L132)):*
> ```objc
>                                      const std::string& method_name) const;
> 
>   /// Returns `Q`, the generalized position vector of the RigidBodyTree that was
> ```

we use `q` (lower case) for generalized positions

---

*[drake/multibody/kinematics_cache.h, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6Z3BxXmrJxJr-bzI:-K_a6Z3BxXmrJxJr-bzJ:bkpodho) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L138)):*
> ```objc
>   /// Returns `V`, the generalized velocity vector of the RigidBodyTree that was
>   /// used to compute this KinematicsCache.
>   const Eigen::Matrix<T, Eigen::Dynamic, 1>& getV() const;
> ```

we use `v` (lower case) for generalized velocities

---

*[drake/multibody/kinematics_cache.h, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6busPkBSYo7RED9B:-K_a6busPkBSYo7RED9C:bi6epg2) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L140)):*
> ```objc
>   const Eigen::Matrix<T, Eigen::Dynamic, 1>& getV() const;
> 
>   /// Returns `X`, the state vector of the RigidBodyTree that was used to
> ```

we use `x` (lower case) for continuous state vector.

---

*[drake/multibody/kinematics_cache.h, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a78iOKU91OUt2XACu:-K_a78iOKU91OUt2XACv:b-th3w5l) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L146)):*
> ```objc
>   Eigen::Matrix<T, Eigen::Dynamic, 1> getX() const;
> 
>   /// Returns true if this KinematicsCache object has a valid `V` vector. `V` is
> ```

`true`

---

*[drake/multibody/kinematics_cache.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a7DRLSLBkIP9CjkZ_:-K_a7DRLSLBkIP9CjkZa:bkpodho) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L147)):*
> ```objc
> 
>   /// Returns true if this KinematicsCache object has a valid `V` vector. `V` is
>   /// the generalized velocity vector of the RigidBodyTree that was used to
> ```

we use `v` (lower case) for generalized velocities

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/multibody/kinematics_cache.h, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6UZ76rhAI6fxeC8n:-K_a8yx6izZS2rKEktYi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L132)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we use `q` (lower case) for generalized positions
</blockquote></details>

Done.

---

*[drake/multibody/kinematics_cache.h, line 138 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6Z3BxXmrJxJr-bzI:-K_a8zrRTkE7EP5rRLEV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L138)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we use `v` (lower case) for generalized velocities
</blockquote></details>

Done.

---

*[drake/multibody/kinematics_cache.h, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a6busPkBSYo7RED9B:-K_a9-RWTepqxvwG2XbH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L140)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we use `x` (lower case) for continuous state vector.
</blockquote></details>

Done.

---

*[drake/multibody/kinematics_cache.h, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a78iOKU91OUt2XACu:-K_a90O49VDQbGQ2oWaX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L146)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`true`
</blockquote></details>

Done.

---

*[drake/multibody/kinematics_cache.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a7DRLSLBkIP9CjkZ_:-K_a91Q47Tx5NYxmgbS9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08291c7819f56fa58315b39cf2c25545ab65701/drake/multibody/kinematics_cache.h#L147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

we use `v` (lower case) for generalized velocities
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/multibody/kinematics_cache.h, line 144 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a9bCEQcePZJT9gE6e:-K_a9bCEQcePZJT9gE6f:b-85313f) ([raw file](https://github.com/robotlocomotion/drake/blob/385dd5dd4929e7293c94c83974e8e40f434c3714/drake/multibody/kinematics_cache.h#L144)):*
> ```objc
>   /// RigidBodyTree's generalized position vector, and `v` the RigidBodyTree's
>   /// generalized velocity vector into a single vector. Within `x`, `q` is
>   /// positioned first while `v` is positioned second.
> ```

BTW consider `q precedes v`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-:-K_a9g1YKdj9i7AQbsBU:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/kinematics_cache.h, line 144 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-K_a9bCEQcePZJT9gE6e:-K_aA18-gfpUf7J5aZ5v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/385dd5dd4929e7293c94c83974e8e40f434c3714/drake/multibody/kinematics_cache.h#L144)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW consider `q precedes v`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662)*

**Comment by amcastro-tri** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4662#-:-K_aDYEDlo-hHwxLTLm6:bg7igkv)*

**Pull request merged**
