### PR TITLE
Purge CMake not used by MATLAB

### LINKED ISSUE #3342: Use non-POD version of bot2-lcmgl
Fork: https://github.com/RobotLocomotion/libbot
Upstream: https://github.com/libbot2/libbot2

### LINKED ISSUE #3426: Feature request: make it easier to make an lcmtypes collection
I'd love to have a CMake function that takes a list of .lcm file names and a 'collection name', and then performs the tasks currently done in `drake/lcmtypes/CMakeLists.txt` for `drake_lcmtypes` (where what I'm calling the 'collection name' is 'drake').

My use case: I'd like to put new .lcm files specific to Valkyrie in `drake/examples/Valkyrie/lcmtypes`. I don't think they should be in `drake/lcmtypes`. So I need to do basically the same thing as in `drake/lcmtypes/CMakeLists.txt`, just in a different folder, with different .lcm files, and the generated headers should be installed to a different folder.

Related: https://github.com/RobotLocomotion/drake/issues/2486.

cc: @mwoehlke-kitware, could you let me know if you or someone else from Kitware has time for this within the next week? If not, I'll try to do it myself, or if you prefer, I'll just copy the code from `drake/lcmtypes/CMakeLists.txt` for now. Thanks!

### LINKED ISSUE #4113: Proliferation of Shared Libraries in KUKA IIWA Example Needs Consolidation
# Problem Definition

There is a proliferation of libraries in `drake-distro/drake/examples/kuka_iiwa_arm/`:

* `drakeKukaIiwaArmCommon`
* `drakeKukaIiwaArm`
* `drakeKukaIiwaWorld` (pending #4107)

We should reconsider whether having so many libraries is reasonable. For example, maybe all three can be consolidated into one library after System 1.0 is removed.

### LINKED ISSUE #4525: Mysterious LCM Error: Error copying file
# The Error

```
Error copying file "/Users/elcapitan/workspace/mac-clang-nightly-matlab-open-source-release/externals/lcm/lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar" to "/Users/elcapitan/workspace/mac-clang-nightly-matlab-open-source-release/build/externals/lcm/lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar".
make[5]: *** [lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar] Error 1
make[5]: *** Deleting file `lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar'
make[4]: *** [lcm-java/jchart2d-code/CMakeFiles/lcm-ext-jide-oss-jar.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
Error copying file "/Users/elcapitan/workspace/mac-clang-nightly-matlab-open-source-release/externals/lcm/lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar" to "/Users/elcapitan/workspace/mac-clang-nightly-matlab-open-source-release/build/externals/lcm/lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar".
make[5]: *** [lcm-java/jchart2d-code/ext/jide-oss-2.9.7.jar] Error 1
make[4]: *** [lcm-java/jchart2d-code/CMakeFiles/jchart2d.dir/all] Error 2
make[3]: *** [all] Error 2
```

# Example Logs

* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-clang-nightly-matlab-open-source-release/227/

### LINKED ISSUE #5356: Mysterious CI Error: Failed to Generate Java Binding for an LCM Message - Bad source File
# Example Error

```
23:28:07 /home/ubuntu/workspace/linux-xenial-gcc-experimental-open-source/build/drake/lcmtypes/drake/lcmt_viewer_link_data.java:17: error: cannot access lcmt_viewer_geometry_data
23:28:07     public drake.lcmt_viewer_geometry_data geom[];
23:28:07                 ^
23:28:07   bad source file: /home/ubuntu/workspace/linux-xenial-gcc-experimental-open-source/build/drake/lcmtypes/drake/lcmt_viewer_geometry_data.java
23:28:07     file does not contain class drake.lcmt_viewer_geometry_data
23:28:07     Please remove or make sure it appears in the correct subdirectory of the sourcepath.
```

# Initial Analysis

The error occurred at time 23:28:07. The missing file was generated one second earlier at time 23:28:06: 

```
23:28:06 [ 10%] Generating drake_lcmt_viewer_geometry_data.h, drake_lcmt_viewer_geometry_data.c, drake/lcmt_viewer_geometry_data.hpp, drake/lcmt_viewer_geometry_data.py, drake/lcmt_viewer_geometry_data.java
```

Oddly, in a [working build](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-open-source/1205), the generation of `lcmt_viewer_geometry_data.java` appears twice.

# Example logs

- https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-open-source/1204

### LINKED ISSUE #5572: cmake option WITH_ALL_SUPPORTED_EXTERNALS gives vtk target error
In a clean build directory, setting `WITH_ALL_SUPPORTED_EXTERNALS=ON` gives the following configuration error:

```
 CMake Error at cmake/modules/3.7/ExternalProject.cmake:2437 (add_custom_target):
   add_custom_target cannot create target "vtk" because an imported target
   with the same name already exists.
 Call Stack (most recent call first):
   cmake/externals.cmake:217 (ExternalProject_Add)
   cmake/externals.cmake:520 (drake_add_cmake_external)
   CMakeLists.txt:160 (drake_add_external)



 CMake Error at cmake/modules/3.7/ExternalProject.cmake:1175 (message):
   External project "vtk" has no stamp_dir
 Call Stack (most recent call first):
   cmake/modules/3.7/ExternalProject.cmake:1410 (ExternalProject_Get_Property)
   cmake/modules/3.7/ExternalProject.cmake:1452 (_ep_get_step_stampfile)
   cmake/externals.cmake:107 (ExternalProject_Add_Step)
   cmake/externals.cmake:529 (drake_forceupdate)
   CMakeLists.txt:160 (drake_add_external)
```

This is with cmake 3.5.2 on Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129. Closes #3342, closes #3426, closes #4113, closes #4525, closes #5356, and closes #5572.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6738)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
+@fbudin69500 and +@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
FYI I will trust that Spartan / Director are well in hand, so I've only focused on the in-tree repercussions, which :lgtm:.  You can count me as platform review also.

---

Reviewed 93 of 93 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738#-:-KqdNV7-_5ImzccyAu_C:b5968db)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738#-:-Kqhj9KeOlf-R6o7tEXs:bnfp4nl)*

**Comment by stonier** [comment]
As far as I understand, this should not go in before https://github.com/RobotLocomotion/spartan/pull/116 gets merged and has had a brief period of usage to resolve any hiccups.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738#-:-KqntjMJ7y8FATgCIIBV:b-kcd432)*

**Comment by patmarion** [comment]
> As far as I understand, this should not go in before RobotLocomotion/spartan#116 gets merged and has had a brief period of usage to resolve any hiccups.

There are no plans in spartan to update the required version of drake except via RobotLocomotion/spartan#116 so i don't think spartan needs to be a blocking issue.

**Comment by stonier** [comment]
I would prefer RobotLocomotion/spartan#116 to go in first so if Spartan users do suddenly want a bump of Drake, they don't have a blocking delay of unknown duration in getting it.

**Comment by jamiesnape** [comment]
Yes, note the "do not merge" tag. This will not merge until the Spartan PR is in.

**Comment by jamiesnape** [comment]
Fixing merge conflicts and consolidating with #6788 since ROS support is gone post-#6783.

**Comment by jwnimmer-tri** [comment]
Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738)*

**Comment by jamiesnape** [comment]
More merge conflicts.

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6738)*

**Pull request merged**
