### PR TITLE
Add gurobi_solver_internal.h/cc

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews.

There is no any change in this PR. I just moved the code from one place to another.

I will add the unit tests in the subsequent PRs.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-:-NuHo4wvD5zeRTh8yt4t:b-brb8g1)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
Over to +@SeanCurtis-TRI per schedule.

@hongkai-dai it would probably also help to explain the story of _why_ these functions are being moved, and why _these_ functions are being moved (vs the other ones that are not).

**Review by hongkai-dai — COMMENTED** [review]
I am adding some new features into GurobiSolver (for example, handling L2NormCost in my [dev branch](https://github.com/hongkai-dai/drake/tree/gurobi_l2norm_cost)), it becomes harder and harder to test these functions to parse different costs/constraints into Gurobi model, just by looking at whether the optimization problem obtained the right solution in gurobi_solver_test.cc. Hence I would like to create test on the internal functions in side GurobiSolver.

This is the first step for the internal testing, just to move the functions to its header file. I will add tests in subsequent PRs.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-:-NuPWtqmCGlT5fBmNkIT:bnuzsvu)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2 (with the request for one deletion).

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-:-NuQ3lA9BnoJ_SrGY8Pq:blkkk25)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`solvers/gurobi_solver_internal.cc` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-NuQ3auy1Sxe6Kdlcu36:-NuQ3auy1Sxe6Kdlcu37:bs68hga) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef0c6596ec621c313b4be5108509ceb6472d7505/solvers/gurobi_solver_internal.cc#L10)):*
> ```cpp
> namespace solvers {
> namespace internal {
> // Adds a constraint of one of the following forms :
> ```

nit: You don't need this function documentation in both the .h and .cc files.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
FYI This C++ code is too big for a header file.  Even though it's a template function, the set of types is _closed_ so we can explicitly instantiate both options in the cc file.  I can follow-up after this merges with the right spelling & move the code, if you like.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll defer to @hongkai-dai on that.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-:-NuR2XGK1bjmYZYRABvI:blharei)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Review by hongkai-dai — COMMENTED** [review]
Done. I moved the implementation to cc file and added explicit instantiation.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223#-:-NuS5VwT8y3SDp_I5vlN:b-hadm0z)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21223)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
