### PR TITLE
have to publish drakeUtil.h and lib now that more moved into them.

### PR DESCRIPTION
**Pull request by RussTedrake**

### CODE REVIEW

**Comment by avalenzu** [comment]
I think this needs to be rebased onto RobotLocomotion/master?

**Comment by RussTedrake** [comment]
@kuindersma gave me his blessing to merge (before the build servers finish). have to finish the non-trivial merge w/ drc.

**Comment by avalenzu** [comment]
I'm still confused about this. I thought our policy was to only merge from RobotLocomotion/master into mitdrc/master. This looks like it's going the other way.

**Comment by RussTedrake** [comment]
I (manually) took my changes over to a fresh checkout of drake and then did a force push onto the same fork.  You can see there is only a single commit in the history

- Russ

**Comment by avalenzu** [comment]
Sorry, that's what I get for reading my github updates on the phone - I saw the initial list of commits and then didn't realize that they'd disappeared.

**Pull request merged**
