### PR TITLE
Fix NaN spatial inertia tests.  New constructors for RotationalInertia, UnitInertia, SpatialInertia.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
This PR #17351 is one of several PRs for issue #17081.
The changes herein are with a view to future PR #17302 (which is currently a work in progress).
Note: Ignore the commit history as this was branched from a branch from a branch.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4-NRHD2HDTk9HYh3gA:bkscgi9)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:

I'd like to get +@russtedrake to do a second feature review. Note that we will no longer be able to accept urdf and mujoco files that fail to specify mass and inertia properties for terminal bodies since they default to zero. (sdf defaults to 1s so the defaults are at least functional) These will now be hard errors at Finalize() in MbP. That seems likely to prevent many downstream disasters but for example would prevent use of MbP for purely-kinematic purposes using default urdf/mujoco files. WDYT?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N43GtqE-vET_I16CoSQ:b-ijwzkf)* status: LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
The urdf changes are painful to see, but I admit that this is a limitation in the urdf spec.  I'm ok with it.

I admit that these particular mujoco changes are necessary, but i actually think that the mujoco parser defaults prevent the need to manually specify inertias in most cases (including the geometry-only workflow Sherm suggests).  The cases below are atypical because they were for very simple unit tests -- they made leaf bodies without any geometry to enable the default mass calculations. 

Actually, the thing that I dislike about this PR is the use of MakeTestCube.  See below.  

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N46ml_M3UQGfqfyntpZ:b-58srn8)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`bindings/pydrake/multibody/tree_py.cc` line 996 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N46oP7-2oUxH_INxUkI:-N46oP7-2oUxH_INxUkJ:bsgpi5r) ([raw file](https://github.com/robotlocomotion/drake/blob/0f37006c90dd088c975e4fdc347b5eac0979c32b/bindings/pydrake/multibody/tree_py.cc#L996)):*
> ```cpp
>             cls_doc.MakeFromCentralInertia.doc)
>         .def_static("MakeTestCube", &Class::MakeTestCube, py::arg("mass") = 2,
>             py::arg("length") = 3, cls_doc.MakeTestCube.doc)
> ```

This method is marked in its doxygen as (internal use only); I think it should not appear in the python bindings.  And encouraging users to call `MakeTestCube` to get reasonable behavior... even in our example code, seems just wrong.  Perhaps `MakeTestCube` needs to be changed to a function name / status that is appropriate for public consumption.  Even `MakeCube` is ok with me.

**Comment by RussTedrake** [comment]
*[`bindings/pydrake/multibody/tree_py.cc` line 996 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N46oP7-2oUxH_INxUkI:-N47HmR85PX6arfOxM8o:bwpn31a) ([raw file](https://github.com/robotlocomotion/drake/blob/0f37006c90dd088c975e4fdc347b5eac0979c32b/bindings/pydrake/multibody/tree_py.cc#L996)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

This method is marked in its doxygen as (internal use only); I think it should not appear in the python bindings.  And encouraging users to call `MakeTestCube` to get reasonable behavior... even in our example code, seems just wrong.  Perhaps `MakeTestCube` needs to be changed to a function name / status that is appropriate for public consumption.  Even `MakeCube` is ok with me.
</blockquote></details>

I now see that this was discussed in https://github.com/RobotLocomotion/drake/issues/17081#issuecomment-1150236102 .  But I still disagree with it as a public name that people should use; especially in example code (like the door hinge).

**Review by mitiguy — COMMENTED** [review]
Russ -- thanks for the feedback.  I changed MakeTestCube() to MakeSolidBox().

I agree that throwing an exception during Finalize() in MBP seems unnecessary for kinematics.
Perhaps it makes sense to create the error message during Finalize() for possible subsequent use.
More generally, it may not be wise to throw an exception at the instant we detect a _possible_ downstream numerical problem.  If the possible downstream numerical problem becomes a definite reality, it seems that it can be thrown then -- but with extra information that was detected and stored earlier.

For some reason, CI is having trouble starting.  I am heading home, hitting publish so you can see my comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N49LknUABePZNF8TZ6w:b-9rzaog)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @sherm1)

___
*[`bindings/pydrake/multibody/tree_py.cc` line 996 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N46oP7-2oUxH_INxUkI:-N49LSpC44Q68YaNsFqJ:b-2olhkp) ([raw file](https://github.com/robotlocomotion/drake/blob/0f37006c90dd088c975e4fdc347b5eac0979c32b/bindings/pydrake/multibody/tree_py.cc#L996)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I now see that this was discussed in https://github.com/RobotLocomotion/drake/issues/17081#issuecomment-1150236102 .  But I still disagree with it as a public name that people should use; especially in example code (like the door hinge).
</blockquote></details>

Yes -- I will replace MakeTestCube() with: 
SpatialInertia::MakeSolidBox(T mass = T(2), T Lx = T(3), Ly = T(3), T Lz = T(3));

**Review by RussTedrake — COMMENTED** [review]
Thanks!  I like it.

> Reviewed 11 of 14 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N47IR7z-nwyRA28SZW8:btpy16s)* status: LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4C2Cwa5q39yaOF3TNt:-N4C2Cwa5q39yaOF3TNu:b-4p7j50) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e78c702ca0494318a10e527feb81ef0cf32b93/multibody/tree/spatial_inertia.h#L139)):*
> ```objc
>   /// if mass is negative or any of Lx or Ly or Lz is negative.
>   /// @note The default parameters mass = 2 and Lx = Ly = Lz = 3 correspond to a
>   /// mass moment of inertia of 3 for any line that pass through Bcm.
> ```

btw -- those seem like unexpected defaults if I were just calling MakeSolidBox.  I would have thought all ones might be slightly more natural?  but if you think they are reasonable, I won't block.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4C2fHZ2RfXPozQdLee:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for monday platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4C2gzwCIMJQT9ylm1u:b3bht1v)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by mitiguy — COMMENTED** [review]
From f2f conversion with @sherm1  and @SeanCurtis-TRI, in this PR I will remove
SpatialInertia::MakeSolidBox( .... );     in favor of an enhanced default SpatialInertia constructor
SpatialInertia( InertiaValue someValue );

where InertiaValue is an enum that currently has two values, namely
InertiaValue::kNaN
InertiaValue::kSDF

Please let me know ASAP if you have objections.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4U-e5o7Ptc2osTYBy1:b-ihpq5l)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`multibody/tree/spatial_inertia.h` line 139 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4C2Cwa5q39yaOF3TNt:-N4U-nUMBmZZmDDHGrXG:b84bszq) ([raw file](https://github.com/robotlocomotion/drake/blob/f4e78c702ca0494318a10e527feb81ef0cf32b93/multibody/tree/spatial_inertia.h#L139)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- those seem like unexpected defaults if I were just calling MakeSolidBox.  I would have thought all ones might be slightly more natural?  but if you think they are reasonable, I won't block.
</blockquote></details>

From f2f with @seancurtis-tri  and @sherm1, there are changes that are more in accord with your expectations with a soon-to-be implemented constructor (in this PR)
SpatialInertia( InertiaValue::kSDF );

**Review by mitiguy — COMMENTED** [review]
@seancurtis-tri   Ready for another look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4ZYEq82oyduO9IaAyM:b-nvdvn0)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @SeanCurtis-TRI, and @sherm1)

___
*[`-- commits` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4TJp6sEVNE-IMJ7QiU):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Out of curiosity, what do you intend for this message when you finally squash?
</blockquote></details>

I am thinking of something like:

New non-NaN constructors for RotationalInertia, UnitInertia, SpatialInertia and replacement of many instances of NaN SpatialInertia constructors with non-NaN constructors.

**Comment by jwnimmer-tri** [comment]
The initialism SDF does not refer to SDFormat; typically, it stands for "signed distance field".  If the intention is to refer to SDFormat's default value, then spell out `kSdformat`.

**Review by mitiguy — COMMENTED** [review]
@seancurtis-tri   It would be great to get another review of this PR.  Although it failed CI, the failure was simply due to a whitespace error in UnitInertia.h.  I plan on fixing that in my next commit along with whatever other changes you suggest (if any).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4haOhK-hmTgqCkjYc6:b-p3xz84)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @SeanCurtis-TRI, and @sherm1)

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4i2bQTAcgjLkp5sHor:b-dtb74b) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
> ```cpp
>       <geometry><box size="1 1 1"/></geometry>
>     </collision>
>     <inertial>
> ```

Given that this is a unit test input file for code that I believe only does kinematics and collision checking (`iris`), it's not clear to my why we need to litter this model file with irrelevant mass and inertia details?

I thought the premise of the overall patch series was that a kinematics-only user should be free to omit the masses and such.

It seems to me like any unit test changes in this PR beyond fixes to MbP or MbT unit tests of dynamics should be viewed with skepticism, because they probably indicate that we are going to break users whose workflows resemble kinematics-only unit tests such as this one.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @SeanCurtis-TRI, and @sherm1)

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4i6Nw0D4QwodGPNxJr:b-cufm8d) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
> I thought the premise of the overall patch series was that a kinematics-only user should be free to omit the masses and such.

I believe this is a misunderstanding. From @sherm1 in the main conversation:

>  Note that we will no longer be able to accept urdf and mujoco files that fail to specify mass and inertia properties for terminal bodies since they default to zero.

This isn't about magically adapting to files that don't provide mass properties. It's about having the ability to yell when that happens. The changes to these files are so if/when auto-yelling is enabled, it doesn't do so w.r.t. Drake code.

There is supposed to be a follow-up PR in which yelling becomes engaged. When that turns on, we will have breaking changes.

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4i7LMG3cMM4QS-XOv5:b-2tlma8) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
I agree that when a user attempts to do dynamics on such a file (or other similar computations that rely on valid masses), they should receive an error.

I do not agree that a user who is only doing kinematics or collision checking should receive an exception when they leave out the masses.

Paul wrote:

> I agree that throwing an exception during Finalize() in MBP seems unnecessary for kinematics.

It should be extremely trivial to defer the exception such that it covers `Delta > 0` but does not yield a false positive when only doing kinematics.

I really must object to a breaking change on behalf of kinematics-only users.

**Review by mitiguy — COMMENTED** [review]
@seancurtis-tri   This is done with CI -- ready for you.
Note: This PR does not need to address Jeremy's objection.
I think his objection is worthy of further discussion.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351#-:-N4i9lQ7BIRIgU4mRvCv:b-rw4lhn)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @SeanCurtis-TRI, and @sherm1)

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4i6X85-XMO91F4hAys:b-tf3jwp) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I agree that when a user attempts to do dynamics on such a file (or other similar computations that rely on valid masses), they should receive an error.

I do not agree that a user who is only doing kinematics or collision checking should receive an exception when they leave out the masses.

Paul wrote:

> I agree that throwing an exception during Finalize() in MBP seems unnecessary for kinematics.

It should be extremely trivial to defer the exception such that it covers `Delta > 0` but does not yield a false positive when only doing kinematics.

I really must object to a breaking change on behalf of kinematics-only users.
</blockquote></details>

@jwnimmer-tri  @sherm1, @seancurtis-tri, and I had a f2f meeting about this Tuesday, with varying viewpoints.  For this PR, we do not need to resolve this question.  However, for the subsequent PR, the issue you raise will need to be addressed.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17351)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @SeanCurtis-TRI, and @sherm1)

___
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4i85FGAcwVh7IvHBff:bhbbilj) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

@jwnimmer-tri  @sherm1, @seancurtis-tri, and I had a f2f meeting about this Tuesday, with varying viewpoints.  For this PR, we do not need to resolve this question.  However, for the subsequent PR, the issue you raise will need to be addressed. 
</blockquote></details>

FTR This is the question of "when does the yelling happen". That belongs to the follow up PR.

We've talked about barking all the time (which many object to, but is straightforward) or trying to do it strategically. Which has its own challenges. Certainly, the braking all the time (for which kinematics users pick up a one-time cost, if they're not using SDF files) has been touched on by multiple people as "acceptable".

However, it's clear to me that figuring out the barking trigger is critical. Paul's effort to make sure Drake-internal uses don't get barked at -- at all -- may be premature if there's an alternative path forward for more strategic barking.

So, perhaps that needs to be nailed down concretely before this proceeds. We discussed it a fair amount, but a fresh perspective would be appreciated.

The central questions were:

1. How does leaf code where an error manifests itself, trigger the analysis it doesn't have any power to perform in crafting an exception message?
2. If we analyze the tree and observe "problematic" aspects, how certain do we have to be in blaming those  potential problems for this actual exception?
3. If we allow for broadcasting *possible* causes of the bug (with some measure of certainty), how wide a net should we be casting to detect "problematic" scenarios to inform the user of possible sources of eventually observed badness? (For example, Paul had alluded to detecting extreme acceleration as a signal of things going wrong.)

**Comment by sherm1** [comment]
We are trying for some simple Finalize-time checks with only true positives to prevent common errors. We're assuming that a uniform rule that says "Drake inputs must have valid mass properties" is not unreasonable in a code that primarily does dynamics. (Valid here means: no NaNs and no zero-mass terminal links.) Sdformat takes care of that by default and MuJoCo usually does. Urdf defaults to zero masses which are OK unless they are for terminal links. 

We don't know at Finalize() what are the intended uses of the system. If we don't require valid mass properties we can't issue any useful messages in Finalize(). Why do you think that adding some boilerplate to urdf files is too big a burden? I would think that a kinematics-only user of Drake is a rare beast.

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/test/iris_in_configuration_space_test.cc` line 41 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17351#-N4i2bQTAcgjLkp5sHoq:-N4iArXI3wwY46lO6pOL:becon86) ([raw file](https://github.com/robotlocomotion/drake/blob/94d8488621e4f7a529b88a0dc121fb16d8591f51/geometry/optimization/test/iris_in_configuration_space_test.cc#L41)):*
If the f2f meeting did not solicit the opinion of someone who writes motion planning code as part of its inputs, then it failed to collect sufficient evidence and its discussions are likely to be off-base.  If did you did not post the minutes of the meeting into the github issue associated with this work, then you have also failed to provide sufficient exposition for this pull request in order for reviewers to understand it.  Verbal conclusions that happen via the game-of-telephone are of no use.

>  For this PR, we do not need to resolve this question.

That's incorrect. We **do** need to resolve it here.  This PR is adding misleading bloat to unrelated unit test code.  It contaminates the overall quality of the codebase because it is approaching the work in the wrong order.

The error-reporting ticket that led to this work needs to be worked from the end-result going backwards.  Create a repro of the bad UX, then iterate to fixing it, where the final error message seen in the example code is the thing that matters.  That code will need a _first-pass review_ of that endpoint before you start introducing these intermediate lemma PRs that take steps along the way.  We have no idea if these are moving in the right direction until we can observe a working a prototype of the end goal.

**Comment by jwnimmer-tri** [comment]
> I would think that a kinematics-only user of Drake is a rare beast.

Certainly _some_ kinds of motion planning require meaningful mass properties.  However, many kinds of motion planning do _not_ need the mass properties.

Did you try running the proposed failure checks against Anzu, to estimate how impactful they might be to the overall community?

**Comment by mitiguy** [comment]
@jwnimmer-tri  
Yes, I agree with you and started with the end-result going backwards.
I put the workflow order in Issue #17081.
The relevant overarching PR is PR #17302.

**Comment by sherm1** [comment]
Russ made [this comment](https://github.com/RobotLocomotion/drake/issues/17081#issuecomment-1151030148) in #17081 which I'm not sure we answered. I rather like the idea of changing the urdf mass properties default in the Drake parser to match the sdformat default. Then no one has to edit their urdf files to do kinematics and urdf & sdf will behave similarly. We could also switch the SpatialInertia() default from NaN to Sdformat to make programmatic constructions behave the same way.

**Comment by jwnimmer-tri** [comment]
This pull request seems to have stalled out.  If we expect it to remain idle for a while longer before resuming, please consider closing it to conserve pull request resources.

**Comment by jwnimmer-tri** [comment]
Closing as abandoned.  When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
