### PR TITLE
Split rational_forward_kinematics_test.cc

### PR DESCRIPTION
**Pull request by hongkai-dai**
As discussed in https://drakedevelopers.slack.com/archives/C270MN28G/p1666874969442129

closes #18193

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197#-:-NFPFc4RArxtURXjjPzK:b79lg6w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197#-:-NFPJgrm2svZFnpqfZ_Q:b-knaohy)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-address-sanitizer please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Looks good. We'll wait for a mac build to churn through (to see the overall time). 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197#-:-NFPKqo270tIJZBC0-zL:bnvd80b)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

___
*[`multibody/rational/test/rational_forward_kinematics_test.cc` line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18197#-NFPK8ppDkVkzFgEKiDM:-NFPK8ppDkVkzFgEKiDN:b69470k) ([raw file](https://github.com/robotlocomotion/drake/blob/ab533318fdaa0b7245eea42e8d766ed1db79d8da/multibody/rational/test/rational_forward_kinematics_test.cc#L71)):*
> ```cpp
> }
> 
> TEST_F(FinalizedIiwaTest, CalcBodyPose1) {
> ```

nit A note explaining the decomposition would be nice. Otherwise maintainers may be unsure about what's being done here and why and that might lead to changes that undo or confound this effort.

And if this decomposition of tests is along meaningful semantic lines, that'd be even better to document.

That said, I've triggered a mac build -- don't push to this PR until that finishes. We'll let it run its course and then we can do a quick comment update and force merge it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
The test passed and it was *short*. 4 minutes instead of 20.

Feel free to add the documentation to the test and we'll merge.

:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197#-:-NFPvnyXBgUNFhYINzaZ:b-lpk7lw)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`multibody/rational/test/rational_forward_kinematics_test.cc` line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18197#-NFPK8ppDkVkzFgEKiDM:-NFQ3nBICMGudUm8IeS7:bc88kz7) ([raw file](https://github.com/robotlocomotion/drake/blob/ab533318fdaa0b7245eea42e8d766ed1db79d8da/multibody/rational/test/rational_forward_kinematics_test.cc#L71)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit A note explaining the decomposition would be nice. Otherwise maintainers may be unsure about what's being done here and why and that might lead to changes that undo or confound this effort.

And if this decomposition of tests is along meaningful semantic lines, that'd be even better to document.

That said, I've triggered a mac build -- don't push to this PR until that finishes. We'll let it run its course and then we can do a quick comment update and force merge it.
</blockquote></details>

Done. I added the documentation.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18197)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
