### PR TITLE
Update spotless submodule SHA

### PR DESCRIPTION
**Pull request by jamiesnape**
To include changes from RobotLocomotion/spotless-pod#9, RobotLocomotion/spotless-pod#10, RobotLocomotion/spotless-pod#11, and RobotLocomotion/spotless-pod#12 hence it bypasses the MEX compiler entirely.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3624)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by david-german-tri** [comment]
Thus far, this hasn't alleviated the following error for me.  Perhaps I have some other problem, but (as with #3186), I'm blocked from testing this PR.

```
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY
  Matlab_MEX_EXTENSION) (found version "9.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindMatlab.cmake:1434 (find_package_handle_standard_args)
  CMakeLists.txt:5 (find_package)
```

**Comment by jamiesnape** [comment]
Just realized I appended the module path. Fix coming up.

**Comment by jamiesnape** [comment]
RobotLocomotion/spotless-pod#10

**Comment by david-german-tri** [comment]
https://github.com/RobotLocomotion/spotless-pod/commit/7fabb1633ceb1455fb7446f4654685db3c937c9c is no better.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
It is still using `FindMatlab.cmake` from 3.5.2?

**Comment by david-german-tri** [comment]
Yes, I'll try nuking the world and starting over.

**Comment by david-german-tri** [comment]
Clean build makes no difference; it still dies a horrible death in `/usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148`

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
Not sure how that got closed...

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  windows-msvc-32-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jamiesnape** [comment]
SHA updated. This appears to fix the segfault on macOS / OS X builds.

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by jamiesnape** [comment]
Windows problems.

**Comment by jamiesnape** [comment]
RobotLocomotion/spotless-pod#12 should fix the Visual Studio issue.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental  please

**Comment by jamiesnape** [comment]
@david-german-tri please try this latest version and let me know if it fixes your issue.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
Trying now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3624#-:-KTBK7LIq15PcJmQtVdm:bxm09ho)*

**Comment by jamiesnape** [comment]
`mac-clang-experimental-matlab` failure is a license server flake. `mac-clang-ninja-experimental-matlab` passes in any case.

**Comment by david-german-tri** [comment]
Works now, :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3624#-:-KTBVVYIql16Md6Yqix-:bhkvjxv)*

**Pull request merged**
