### PR TITLE
[schema] Add Rotation::Sample

### LINKED ISSUE #21416: Some Drake stochastics are not closed under `Sample()`
**Is your feature request related to a problem? Please describe.**
`DistributionVariant` and `DistributionVectorVariant` sample to instances of themselves -- that is, given `DistributionVariant a`, `DistributionVariant(a.Sample())` is valid and `IsDeterministic`.  This has the effect of making these variants closed under `Sample`, which is very convenient for sampling a schema-defined class (e.g. a yaml scenario).

However,
 * The `Rotation` variant lacks this property:  `Rotation.Sample()` -> `RotationMatrix`, which is not a member of `Rotation`.
 * The `Transform` class is worse, since `Transform.Sample()`->`RigidTransform` not only means that the type isn't closed under `Sample()` but also causes #20754 (loss of base frame during sampling) because `RigidTransform` is semantically different from `Transform`.

The result of this is that generating a `IsDeterministic` instance from a schema-defined object requires special cases for each stochastic type rather than a single general-purpose mechanism.

**Describe the solution you'd like**

All Drake stochastic types, both classes and variants, should `Sample()` to deterministic versions of themselves rather than to separate types.  Given deprecation guarantees and styleguide rules on overloading, this should be done by creating a new method rather than by changing `Sample`.  I'd suggest `SampleToDeterministic` to express the invariant that this function returns the same type but guarantees that the result `IsDeterministic()`.

`SampleToDeterministic` would provide the clear invariants that:
 * if `x.IsDeterministic()` then `x.SampleToDeterministic() == x`
 * `x.SampleToDeterministic().IsDeterministic() == true`
 * `x.SampleToDeterministic().DeterministicValue()` is in distribution `x`

**Describe alternatives you've considered**

Because what I've described is more properly described as `Sample`, changing the existing `Sample` method would be cleaner.  But that would require deprecating the existing method, which is slow and disruptive, or else overloading on return type, which is forbidden.

Creating an all-in-one free function to sample any stochastic type to itself would be reasonable, but the correct way to implement that would probably be to build `SampleToDeterministic` on every type anyway, or the equivalent through a huge `visit`.  It would also possibly hide the solution to #20754 in a nonlocal place.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This brings it on par with `Transform::Sample`.

Closes #21416.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22113)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
This doesn't feel to me like it closes the original complaint in #21416, however since the issue's author agrees... :lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22113#-:-OB1ll_74gc1H7db2XaR:bxga1gw)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform)

**Comment by jwnimmer-tri** [comment]
FWIW this post was my attempt to explain this as a solution:
https://github.com/RobotLocomotion/drake/issues/21416#issuecomment-2105237718

**Pull request merged**
