### PR TITLE
Support MATLAB R2016b and R2017a in CMake build

### LINKED ISSUE #5793: FindMatlab.cmake does not work for MATLAB R2017a
When building with MATLAB R2017a, @RussTedrake and I receive the following error
```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Matlab: Found unsuitable version "unknown", but required is
  at least "7.7" (found /usr/local/MATLAB/R2017a/extern/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/3.7/FindMatlab.cmake:1529 (find_package_handle_standard_args)
  CMakeLists.txt:374 (find_package)


-- Configuring incomplete, errors occurred!
```
I do not see this error with MATLAB R2016a, or any previous versions.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #5793.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5795)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@hongkai-dai for testing and feature review. FYI @RussTedrake.

**Comment by RussTedrake** [comment]
just tried a quick test, and it did not resolve the issue.  (the error is the same, even after zapping build/externals/gurobi/CMakeCache.txt)

**Comment by jamiesnape** [comment]
I forgot about externals using MATLAB. Hopefully, the variable is passed down to Gurobi now.

**Comment by hongkai-dai** [comment]
I will test this when I get back home. Currently on my TRI laptop I do not have a MATLAB R2017 installed, and TRI only supports up to MATLAB R2016a.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-KiaL39yxv7tBBSBEsFQ:b-c5f81f)*

**Comment by hongkai-dai** [comment]
Just tested this on a machine with MATLAB R2017a, it compiles both MATLAB and gurobi. I am very sorry for the delay.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-Kikgk0qZJm8dIkIr8g9:b-kuhts4)*

**Comment by hongkai-dai** [comment]
:lgtm: +@soonho-tri for platform review please

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-Kiki_eU5CaA8rmsdNNs:b-s828vc)*

**Comment by soonho-tri** [comment]
+@russtedrake , could you test this PR with Matlab 2017a?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-Kikx3Lyw_QNzb-fGqlW:bn286ts)*

**Comment by stonier** [comment]
+@soonho-tri given Russ' limited bandwidth, is there anyone else who can test this with Matlab 2017a?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-KjIUCm1aBeUX-G3O8En:b-8ccnza)*

**Comment by soonho-tri** [comment]
:lgtm: 

Let's merge this now. @hongkai-dai tested it with Matlab R2017a. I wanted to have another test to make sure but now I think it's good enough. Anyway, it does not break the current support to Matlab R2016a so most of us should be fine in the worst case.

Separately, I'll look for a volunteer who can test it with Matlab R2017a in Slack.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-KjIfKIUwPhtjvQCjeIB:b-x6q4ww)*

**Comment by soonho-tri** [comment]
-@RussTedrake 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5795#-:-KjIfwPSwx1Vcr9Tfu0J:b-t7mwbl)*

**Pull request merged**
