### PR TITLE
Add python binding for RenderEngineGltfClient

### LINKED ISSUE #18347: RenderRpc: Pybind MakeRenderEngineGltfClient and RenderEngineGltfClientParams
`RenderEngineGltfClient` (and its config struct `RenderEngineGltfClientParams`) currently can only be instantiated in the C++ land. We should bind that to Python to aid testing and provide access to common use cases.

### PR DESCRIPTION
**Pull request by bhaq-tri**
Add python binding for RenderEngineGltfClient. 
Added tests. 

+@zachfang

Close #18347 

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387)

### CODE REVIEW

**Review by bhaq-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`geometry/render_gltf_client/BUILD.bazel` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NIDfKDM4FBBDsV_bqgF:-NIDfKDM4FBBDsV_bqgG:b-72qf7i) ([raw file](https://github.com/robotlocomotion/drake/blob/62f972284f3878ce4c69a0467284cef3281b9637/geometry/render_gltf_client/BUILD.bazel#L22)):*
> ```Starlark
> drake_cc_package_library(
>     name = "render_gltf_client",
>     # TODO(jwnimmer-tri) Make public once we add libcurl to the wheel builds.
> ```

@zachfang Please investigate this.

**Comment by zachfang** [comment]
@drake-jenkins-bot ok to test

I will look into that to-do and update here.

**Review by zachfang — COMMENTED** [review]
Fist pass done.

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387#-:-NI_kEyZEJLcL5qx7_5i:b-whlt9o)* status: 5 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @bhaq-tri)

___
*[`geometry/render_gltf_client/BUILD.bazel` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NIDfKDM4FBBDsV_bqgF:-NIEGS1D8duB_6n5RUMg:b-x6jyri) ([raw file](https://github.com/robotlocomotion/drake/blob/62f972284f3878ce4c69a0467284cef3281b9637/geometry/render_gltf_client/BUILD.bazel#L22)):*
<details><summary><i>Previously, bhaq-tri wrote…</i></summary><blockquote>

@zachfang Please investigate this. 
</blockquote></details>

Working.
___
*[`bindings/pydrake/BUILD.bazel` line 560 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_hob40aTA1nC8iseR:-NI_hob40aTA1nC8iseS:b-y67pgg) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/BUILD.bazel#L560)):*
> ```Starlark
> drake_py_unittest(
>     name = "geometry_render_engine_gltf_client_test",
>     flaky = True,
> ```

nit: why is this test marked as flaky?
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_k-De20qHog1bKmGU:-NI_k-De20qHog1bKmGV:b2uyr3n) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L13)):*
> ```Python
>         scene_graph = SceneGraph()
>         params = mut.render.RenderEngineGltfClientParams()
>         if 'darwin' in sys.platform:  # Not supported on macOS.
> ```

I don't think this is true though. `RenderEngineGl` is indeed not supported in macOS but it's not the case for GltfClient.



_Code quote:_
```Python
if 'darwin' in sys.platform:  # Not supported on macOS.
```
___
*[`bindings/pydrake/test/geometry_render_test.py` line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_i_8XAU1guOBRehgr:-NI_i_8XAU1guOBRehgs:bj399u4) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/test/geometry_render_test.py#L63)):*
> ```Python
>     def test_render_engine_gltf_client_params(self):
>         # A default constructor exists.
>         mut.render.RenderEngineGltfClientParams()
> ```

nit: maybe `self.assertEqual()` to check the default values of one or two fields are correct?  
___
*[`bindings/pydrake/test/geometry_render_test.py` line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_j5vC0iapTb0MHlBs:-NI_j5vC0iapTb0MHlBt:bd9wqbp) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/test/geometry_render_test.py#L68)):*
> ```Python
>         label = mut.render.RenderLabel(10)
>         params = mut.render.RenderEngineGltfClientParams(
>             default_label=label,
> ```

nit: similarly, maybe assign some gltf-client-specific params to test?



_Code quote:_
```Python
default_label=label
```

**Review by bhaq-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387)* status: 2 unresolved discussions, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`bindings/pydrake/BUILD.bazel` line 560 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_hob40aTA1nC8iseR:-NId1DHU82Qmsdr6-gTC:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/BUILD.bazel#L560)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: why is this test marked as flaky?
</blockquote></details>

Removed.
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NI_k-De20qHog1bKmGU:-NId1PYTBwPhyM7VhFFr:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/87a29c2e0ce14bc9aeebfc23644a2c6bef790ded/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L13)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I don't think this is true though. `RenderEngineGl` is indeed not supported in macOS but it's not the case for GltfClient.
</blockquote></details>

Removed.

**Comment by zachfang** [comment]
@bhaq-tri Just to ckeck in advance. Assuming #18480 can be expedited this early afternoon, are you available to rebase on top of it immediately (once it's merged) so that we can get this to platform review as well?

**Comment by bhaq-tri** [comment]
@zachfang Yes I can support this; please ping me on slack when ready.

**Comment by zachfang** [comment]
There is another issue with the macOS CI build, so it will probably not happen today but tomorrow (if there is still any platform-review resource :crossed_fingers:).

**Review by zachfang — COMMENTED** [review]
#18480 has been merged, please rebase on top of it, and we can bring this to the platform review (assuming no new CI issues).  

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387#-:-NLclIaS9NXt2_kd3KHE:bfs9vs6)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by jwnimmer-tri** [comment]
It looks like it already merges cleanly, so in theory it should just work to re-launch Jenkins and it'll build against the merge.

@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
@zachfang FYI we still need your `:lgtm:` emoji.

:lgtm: platform.

> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-:-NLcsrJCBzRxHqVip-6R:bmy4fml)* status: 5 unresolved discussions, LGTM missing from assignee zachfang (waiting on @bhaq-tri)

___
*[`geometry/render_gltf_client/render_engine_gltf_client_params.h` line 24 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-NLcsYMO-0oBFemdlNZq:-NLcsYMO-0oBFemdlNZr:bkrmkpv) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/geometry/render_gltf_client/render_engine_gltf_client_params.h#L24)):*
> ```objc
>     a->Visit(DRAKE_NVP(verbose));
>     a->Visit(DRAKE_NVP(cleanup));
>     GetUrl();
> ```

I don't see any reason to call `GetUrl()` here.  If there is a good reason, it should be documented with a comment here for clarity. (This call might be vestigial from when we used to have invariants / exceptions for the fields of this class?)
___
*[`bindings/pydrake/BUILD.bazel` line 562 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-NLcruf-C5g0HgV2ez47:-NLcruf-C5g0HgV2ez48:b5ajxzr) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/bindings/pydrake/BUILD.bazel#L562)):*
> ```Starlark
>     deps = [
>         ":geometry_py",
>         "//bindings/pydrake/common/test_utilities",
> ```

nit The `test_utilities` seems to be unused.
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-NLcqR_V4Eg5Z433fXYJ:-NLcqR_W4BVRKvQaJ6gs:b-hpdyt4) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L1)):*
> ```Python
> import pydrake.geometry as mut
> ```

nit This is a bit of pydrake arcana, but `mut` stands for "module under test".  In our case, the module we're testing is `pydrake.geometry.render` not `pydrake.geometry` so we need to switch this up.

Alternatively, I don't see any real reason we need a new file for this.  This test function could just as well live in `geometry_render_test.py`.  I know the `render_engine_gl_test.py` is separate but that is probably just vestigial baggage because that particular engine used to be phrased with odd build system corner cases to be Ubuntu-only.  If you do move this code to the other file, there's no need to change how the import of `mut` works there.



_Suggestion:_
```Python
import pydrake.geometry.render as mut
```
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-NLcqGYL4pe1bwgodrLu:-NLcqGYM-qamCUSltpIG:b9a5npo) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L3)):*
> ```Python
> import pydrake.geometry as mut
> 
> import sys
> ```

nit unused `import sys`
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 10 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18387#-NLcqccu6HAxrmpaZrxV:-NLcqccu6HAxrmpaZrxW:b-tn6ly7) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L10)):*
> ```Python
> 
>     def test_render_engine_gltf_client_api(self):
>         SceneGraph = mut.SceneGraph_[float]
> ```

nit Once the `mut` typo is fixed above, we'd need to spell this line differently.

Probably simplest would just be `from pydrake.geometry import SceneGraph` up around line 6.  There's no real need to invoke the more complicated `SceneGraph_[float]` syntax in this standalone test program.



_Code quote:_
```Python
SceneGraph = mut.SceneGraph_[float]
```

**Review by zachfang — COMMENTED** [review]
:lgtm: feature pending the platform's comments.

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387#-:-NLd-JAM2J-nBXUsN-BX:b-b0smra)* status: 5 unresolved discussions (waiting on @bhaq-tri and @jwnimmer-tri)

___
*[`geometry/render_gltf_client/render_engine_gltf_client_params.h` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NLcsYMO-0oBFemdlNZq:-NLczJJy9Qkb_3jikSnM:b-d8xf17) ([raw file](https://github.com/robotlocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/geometry/render_gltf_client/render_engine_gltf_client_params.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't see any reason to call `GetUrl()` here.  If there is a good reason, it should be documented with a comment here for clarity. (This call might be vestigial from when we used to have invariants / exceptions for the fields of this class?)
</blockquote></details>

I need to understand the `Serialize` function better, but I thought we need to include whatever the C++ struct has so that the data member or functions can be leveraged on the Python binding side.

**Review by bhaq-tri — COMMENTED** [review]
Thanks

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18387#-:-NLgff8TDWV0hWU9yq2e:b-ucfko4)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @zachfang)

___
*[`geometry/render_gltf_client/render_engine_gltf_client_params.h` line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NLcsYMO-0oBFemdlNZq:-NLgdaUq5lKaKqd6j_dV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/geometry/render_gltf_client/render_engine_gltf_client_params.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Only things mentioned in a `Visit()` callback have any effect on the serialization or bindings.

If you'd like to bind the `GetUrl` member function into pydrake that would be fine, but the tactic for that is just the usual `.def("GetUrl", &Class::GetUrl, ...)` like any other function.
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/geometry_render_engine_gltf_client_test.py` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18387#-NLcqR_V4Eg5Z433fXYJ:-NLgeUA1-Q9TNChyESrP:b8g92ga) ([raw file](https://github.com/robotlocomotion/drake/blob/3f896973b2c420456f1555b84c4f7391613106aa/bindings/pydrake/test/geometry_render_engine_gltf_client_test.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is a bit of pydrake arcana, but `mut` stands for "module under test".  In our case, the module we're testing is `pydrake.geometry.render` not `pydrake.geometry` so we need to switch this up.

Alternatively, I don't see any real reason we need a new file for this.  This test function could just as well live in `geometry_render_test.py`.  I know the `render_engine_gl_test.py` is separate but that is probably just vestigial baggage because that particular engine used to be phrased with odd build system corner cases to be Ubuntu-only.  If you do move this code to the other file, there's no need to change how the import of `mut` works there.
</blockquote></details>

Moved to `geometry_render_test.py`.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18387)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang (waiting on @bhaq-tri)

**Pull request merged**
