### PR TITLE
Added Doxygen to resolveFilename().

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2703)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review since this is just a documentation change.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-:-KLSeyZMkXTPJfubFzEp:-2074636678)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/xmlUtil.h, line 179 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-KLSi5uYghkU0dhF85y2:-KLSi5uYghkU0dhF85y3:912628478) ([raw file](https://github.com/robotlocomotion/drake/blob/3d71047fb881524c7f0eda89d4ae1c585e00f056/drake/systems/plants/xmlUtil.h#L179)):*
> ```objc
> /// @return The file's fully-qualified name or an empty string if the file is
> /// not found or does not exist.
> DRAKEXMLUTIL_EXPORT std::string resolveFilename(const std::string& file_name,
> ```

Empirically (grep), Drake pretty solidly believes that this should be called `filename` (one word) and not `file_name` (two words).  I think it should remain consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703)*

**Comment by liangfok** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/xmlUtil.h, line 179 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-KLSi5uYghkU0dhF85y2:-KLSrSSjUqkb3eMQYqWR:1392802796) ([raw file](https://github.com/robotlocomotion/drake/blob/3d71047fb881524c7f0eda89d4ae1c585e00f056/drake/systems/plants/xmlUtil.h#L179)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Empirically (grep), Drake pretty solidly believes that this should be called `filename` (one word) and not `file_name` (two words).  I think it should remain consistent.
</details>
Fixed.

FTR. I made the changed based on the fact that "filename" is not a word in [Merriam-Webster](http://www.merriam-webster.com/dictionary/suggestions/filename) and the style guide indicates a need to use variables names consisting of [words separated by underscores](https://google.github.io/styleguide/cppguide.html#Variable_Names).

I see now though that Wikipedia has an entry for [filename](https://en.wikipedia.org/wiki/Filename), so I suppose it is becoming a legit word now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/xmlUtil.h, line 166 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-KLTX4uUnQH9bThYfPzT:-KLTX4uUnQH9bThYfPzU:-847797715) ([raw file](https://github.com/robotlocomotion/drake/blob/209d0e5ca3387924059b5d8e8ff1e91a94bb4ce5/drake/systems/plants/xmlUtil.h#L166)):*
> ```objc
> /// Otherwise, @p filename is appended to the end of @p root_dir and checked
> /// for existence. If the file does not exist or is not found, an empty string
> /// is returned.
> ```

BTW Consider whether the API should also document that a message will be printed to `cerr`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-:-KLTXCMirNLESCxP66Q3:1417088721)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/xmlUtil.h, line 166 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-KLTX4uUnQH9bThYfPzT:-KLTf2MuNKukFMsNvJ_f:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/209d0e5ca3387924059b5d8e8ff1e91a94bb4ce5/drake/systems/plants/xmlUtil.h#L166)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider whether the API should also document that a message will be printed to `cerr`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703#-:-KLTf6RKs8JfgUji_lkC:-84625242)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2703)*

**Comment by jwnimmer-tri** [comment]
Jenkins passed except for an msvc flake.  Using override-merge.

**Pull request merged**
