### PR TITLE
Add wheels for Focal (Python 3.8 and 3.9)

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Refactor wheel provisioning to allow for different packages between Bionic and Focal. Update build script to add new targets for Focal, and to account for additional changes in the wheel name.

Refactor OS detection so that "manylinux" is a subset of "ubuntu". Particularly, this means that `is_ubuntu` is true if `is_manylinux` is true, and that `ubuntu_release` is set.

Tweak logic in various packages to account for this change.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16308#-Msf_TEv5TA9LT3ejifY:-Msf_TEv5TA9LT3ejifZ:bjxfzbw) ([raw file](https://github.com/robotlocomotion/drake/blob/d6383e5eb8b71a7344bd01ffd228d091045d7c53/tools/wheel/build-wheels#L38)):*
> ```
>     Target('37', 'ubuntu', '18.04', 'bionic'),
>     Target('38', 'ubuntu', '18.04', 'bionic'),
>     Target('38', 'ubuntu', '20.04', 'focal'),
> ```

Why do we have _two_ wheels being built for Python 3.8 now?  I would have thought that we should only be uploading one wheel per Python version?  I thought that the existing 3.8 wheel that was compiled using 'bionic' as a base would run correctly on Ubuntu 20?

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16308#-Msf_TEv5TA9LT3ejifY:-MsfjWr6CEXpUWx5MITZ:b-wybrrj) ([raw file](https://github.com/robotlocomotion/drake/blob/d6383e5eb8b71a7344bd01ffd228d091045d7c53/tools/wheel/build-wheels#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why do we have _two_ wheels being built for Python 3.8 now?  I would have thought that we should only be uploading one wheel per Python version?  I thought that the existing 3.8 wheel that was compiled using 'bionic' as a base would run correctly on Ubuntu 20?
</blockquote></details>

We may not need it, but it felt odd not building for the "default" Python. I take it you'd prefer to only build 3.9 on Focal? (BTW, this is another reason pip may need to keep Bionic around longer; there is no 3.6 or 3.7 available on Focal.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16308#-Msf_TEv5TA9LT3ejifY:-Msg274C2bkiJUIkywph:b7vqjq4) ([raw file](https://github.com/robotlocomotion/drake/blob/d6383e5eb8b71a7344bd01ffd228d091045d7c53/tools/wheel/build-wheels#L38)):*
>  I take it you'd prefer to only build 3.9 on Focal?

Mostly I'd like to understand the thought process.

This will build two 3.8 wheels.  What happens when we upload them both to PyPI?  Which one will be used under which circumstances?

What's the upside of building both?  It means waiting longer for the builds, so if there is no upside, we should skip it.

> This is another reason pip may need to keep Bionic around longer; there is no 3.6 or 3.7 available on Focal.

Most likely, we'll drop support for 3.6 and 3.7 concurrently with dropping support for Bionic.  If we really still need 3.7 at that point, then for wheel-building we can install Python 3.7 into Focal via non-deb means.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16308#-Msf_TEv5TA9LT3ejifY:-Msg6Y-f1vLxFkyY4dzW:buqzb5s) ([raw file](https://github.com/robotlocomotion/drake/blob/d6383e5eb8b71a7344bd01ffd228d091045d7c53/tools/wheel/build-wheels#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

>  I take it you'd prefer to only build 3.9 on Focal?

Mostly I'd like to understand the thought process.

This will build two 3.8 wheels.  What happens when we upload them both to PyPI?  Which one will be used under which circumstances?

What's the upside of building both?  It means waiting longer for the builds, so if there is no upside, we should skip it.

> This is another reason pip may need to keep Bionic around longer; there is no 3.6 or 3.7 available on Focal.

Most likely, we'll drop support for 3.6 and 3.7 concurrently with dropping support for Bionic.  If we really still need 3.7 at that point, then for wheel-building we can install Python 3.7 into Focal via non-deb means.
</blockquote></details>

Dropping 3.7 means (AFAIK) dropping colab... and I'm not sure "use 3.7 on Focal" is an option, either, due to the glibc version. (On that note, it appears we already don't support RH7. Or RH8 for that matter, as RH8 appears to be on Python 3.9 but also glibc 2.28.)

**Review by jwnimmer-tri — COMMENTED** [review]
This needs some buildifier de-linting, per Jenkins.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308#-:-MsgUjGl1nKXgkM0IgCB:b-wrz8yd)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgUARtD1y4VIx0vduA):*
Having is_manylinux be a subset of is_ubuntu goes against the design intent that I had in mind for the OS selection.  In general I would like to have `manylinux` steer towards being _less_ dependent on the details of Ubuntu, not more.

I would be OK with having the `ubuntu_release` detail be populated in the `is_manylinux == True` case for now (since we presumably need to branch on that in certain cases for the purposes of this pull request), but the `is_ubuntu` should remain `False` in that case.
___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16308#-Msf_TEv5TA9LT3ejifY:-MsgJwPMB5mrkcHhFo20:b-v31a4p) ([raw file](https://github.com/robotlocomotion/drake/blob/d6383e5eb8b71a7344bd01ffd228d091045d7c53/tools/wheel/build-wheels#L38)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Dropping 3.7 means (AFAIK) dropping colab... and I'm not sure "use 3.7 on Focal" is an option, either, due to the glibc version. (On that note, it appears we already don't support RH7. Or RH8 for that matter, as RH8 appears to be on Python 3.9 but also glibc 2.28.)
</blockquote></details>

OK yes, Colab viability would be the relevant question for 3.7.  However, per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) a lot of science stuff is dropping Python 3.7 support early this year (if not already), so having Drake's releases as of April stop supporting Colab until Colab upgrades to Ubuntu 20 is a plausible choice.  I've added a remark to #13391 about this.
___
*[tools/wheel/image/packages-focal, line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgSFHO2Vw79QumA4TW:-MsgSFHO2Vw79QumA4TX:b-qnuz4e) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/packages-focal#L2)):*
> ```
> # Build dependencies.
> libnlopt-cxx-dev
> ```

Once Bionic goes away, the "focal" vs "common" filename split will not make sense anymore.  In the `setup/ubuntu/**` scripts, we use separate files for bionic vs focal that are each independently comprehensive (and thus sometimes have duplicated content).  I think that duplication is fine, and for consistency and durability we should use the same approach here -- one file for bionic, one for focal, no common file.
___
*[tools/wheel/image/provision-base.sh, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgRIYw7U0MX7s-aDEr:-MsgRIYw7U0MX7s-aDEs:b-hoyrn4) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/provision-base.sh#L9)):*
> ```Shell
> 
> readonly DISTRO=$(grep UBUNTU_CODENAME /etc/os-release | \
>                   cut -f2 -d= | tr -d '"')
> ```

In the existing `setup/ubuntu/**` scripts, we do `codename=$(lsb_release -sc)`.  For consistency, I'd like use that same phrasing (i.e., shell out to `lsb_release`) in these scripts as well, unless there a some specific reason use a different query mechanism.  (I'm okay if the variable here is still named `DISTRO`, vs `codename`.)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgUARtD1y4VIx0vduA):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Having is_manylinux be a subset of is_ubuntu goes against the design intent that I had in mind for the OS selection.  In general I would like to have `manylinux` steer towards being _less_ dependent on the details of Ubuntu, not more.

I would be OK with having the `ubuntu_release` detail be populated in the `is_manylinux == True` case for now (since we presumably need to branch on that in certain cases for the purposes of this pull request), but the `is_ubuntu` should remain `False` in that case.
</blockquote></details>

To the extent we *have* `is_ubuntu` as opposed to `is_linux`, I'm not sure that makes sense. If manylinux were to become some non-Ubuntu platform, the places where we care about "Ubuntu" vs. "Linux" are likely to need that distinction for wheel builds.
___
*[tools/wheel/image/packages-focal, line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgSFHO2Vw79QumA4TW:-MskLwY92Stt1fICeaaM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/packages-focal#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Once Bionic goes away, the "focal" vs "common" filename split will not make sense anymore.  In the `setup/ubuntu/**` scripts, we use separate files for bionic vs focal that are each independently comprehensive (and thus sometimes have duplicated content).  I think that duplication is fine, and for consistency and durability we should use the same approach here -- one file for bionic, one for focal, no common file.
</blockquote></details>

Done.
___
*[tools/wheel/image/provision-base.sh, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgRIYw7U0MX7s-aDEr:-MskLksU1ABCNZ_Jdhxh:b-icg4o4) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/provision-base.sh#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In the existing `setup/ubuntu/**` scripts, we do `codename=$(lsb_release -sc)`.  For consistency, I'd like use that same phrasing (i.e., shell out to `lsb_release`) in these scripts as well, unless there a some specific reason use a different query mechanism.  (I'm okay if the variable here is still named `DISTRO`, vs `codename`.)
</blockquote></details>

I wasn't aware of that approach, and was copying what is done in `os.bzl`. That said, one reason is that `lsb_release` needs to be installed first. Is that worthwhile?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgUARtD1y4VIx0vduA):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

To the extent we *have* `is_ubuntu` as opposed to `is_linux`, I'm not sure that makes sense. If manylinux were to become some non-Ubuntu platform, the places where we care about "Ubuntu" vs. "Linux" are likely to need that distinction for wheel builds.
</blockquote></details>

The meaning of "is_ubuntu" not merely that we're using Ubuntu in some form, but rather to discriminate between which of the three workspace selection choices we're operating under (use ubuntu's dynamic libraries, use macos's dynamic libraries, or use manylinux-compatible static libraries).  By that measure, the three "is foo" predicates must be mutually exclusive and collectively exhaustive.

Perhaps we need better comments in os.bzl to explain that and avoid confusion, but it _is_ important that the three mode are exclusive.

If a repository.bzl wants to say "if is_ubuntu or is_manylinux" to treat the two options uniformly, that's fine.  And if we want to have "ubuntu_release" non-None even for is_manylinux, that's fine too.
___
*[tools/wheel/image/packages-focal, line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgSFHO2Vw79QumA4TW:-MskgfMe2awsoSqyg1Pr:bu0cvts) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/packages-focal#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this change maybe wasn't pushed yet?
___
*[tools/wheel/image/provision-base.sh, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgRIYw7U0MX7s-aDEr:-Mskga3wAA6rqAPJUYp6:bllfuy) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/provision-base.sh#L9)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I wasn't aware of that approach, and was copying what is done in `os.bzl`. That said, one reason is that `lsb_release` needs to be installed first. Is that worthwhile?
</blockquote></details>

OK I do think they should all be uniform, but I suppose we can save that for a follow-up change.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/image/packages-focal, line 2 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgSFHO2Vw79QumA4TW:-Mskhe4K4JK9N5Ods7Ku:be82snm) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/packages-focal#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this change maybe wasn't pushed yet?
</blockquote></details>

Yes, I'm trying to reproduce the linter report, and also fiddling with the "codename" detection.

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/image/provision-base.sh, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgRIYw7U0MX7s-aDEr:-MskiEkv89bJPEFSFocn:b-gsf1l0) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/provision-base.sh#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I do think they should all be uniform, but I suppose we can save that for a follow-up change.
</blockquote></details>

Should `os.bzl` be using `lsb_release -sr` then?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/image/provision-base.sh, line 9 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgRIYw7U0MX7s-aDEr:-MskiRitDiAPGZ-JgeLI:bfuom2) ([raw file](https://github.com/robotlocomotion/drake/blob/bc647edb42e78fe56e18accb2fee3ab104006af9/tools/wheel/image/provision-base.sh#L9)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Should `os.bzl` be using `lsb_release -sr` then?
</blockquote></details>

Yes, I think so (unless there is some roadblock that I'm not able to foresee).

**Comment by mwoehlke-kitware** [comment]
___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16308#-MsgUARtD1y4VIx0vduA):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The meaning of "is_ubuntu" not merely that we're using Ubuntu in some form, but rather to discriminate between which of the three workspace selection choices we're operating under (use ubuntu's dynamic libraries, use macos's dynamic libraries, or use manylinux-compatible static libraries).  By that measure, the three "is foo" predicates must be mutually exclusive and collectively exhaustive.

Perhaps we need better comments in os.bzl to explain that and avoid confusion, but it _is_ important that the three mode are exclusive.

If a repository.bzl wants to say "if is_ubuntu or is_manylinux" to treat the two options uniformly, that's fine.  And if we want to have "ubuntu_release" non-None even for is_manylinux, that's fine too.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

Did you want +(status: commits are properly curated)?

> Reviewed 1 of 13 files at r1, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308#-:-MskwpYK9G7bKNqqxarG:b7f5744)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

After that passes, it's ready for platform review.

**Comment by mwoehlke-kitware** [comment]
> Did you want +(status: commits are properly curated)?

Indeed; thanks!

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 13 files at r1, 2 of 6 files at r3, 4 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16308#-:-Mspv-fW7vPdblTUsBsp:b-vtj4vo)* status: LGTM missing from assignee jwnimmer-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
:lgtm: feature.

**Comment by jwnimmer-tri** [comment]
This is ready to merge after a rebase.

**Comment by jwnimmer-tri** [comment]
Needs another rebase.

**Pull request merged**
