### PR TITLE
Rename OutputPort to OutputPortValue

### PR DESCRIPTION
**Pull request by sherm1**
Renames OutputPort to OutputPortValue to more accurately reflect what it does and to free up the OutputPort name for later use. Will follow with a similar change to InputPort.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5496)

### CODE REVIEW

**Comment by sherm1** [comment]
+@david-german-tri for all review.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5496#-:-KfEzOtdGMxHoKh7q2Tr:b296g6v)*

**Comment by david-german-tri** [comment]
:lgtm: I'm not sure I agree this is an improvement, but it's not worse.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 1000 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5496#-KfHt1HRBIvzN9OmsYpY:-KfHt1HRBIvzN9OmsYpZ:b-8ybssr) ([raw file](https://github.com/robotlocomotion/drake/blob/26409d73e26ee04c593b8496cf496538983144aa/drake/systems/framework/diagram.h#L1000)):*
> ```objc
>           subsystem_output->get_mutable_port_value(port_index);
> 
>       // Then, put a pointer to that OutputPort in the DiagramOutput.
> ```

BTW, please grep for comment usages like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5496#-:-KfHtv2xNGRz8lBX4jwM:b-i1amcb)*

**Comment by sherm1** [comment]
If only for my own sanity, I need to make a clear distinction between the port concepts at the System level (as specified with DeclareInputPort, DeclareOutputPort) and the concepts associated with their run time values.

---

Review status: 8 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 1000 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5496#-KfHt1HRBIvzN9OmsYpY:-KfILTD0w_zhG5y4mzh7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/26409d73e26ee04c593b8496cf496538983144aa/drake/systems/framework/diagram.h#L1000)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, please grep for comment usages like this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5496#-:-KfILX01zpKV8pXbCVs4:b-3g357u)*

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
