### PR TITLE
Fix errant test in #8605 (Python binding for SetInitialGuess)

### PR DESCRIPTION
**Pull request by gizatt**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8615)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI can you review?

@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please

**Comment by EricCousineau-TRI** [comment]
Yup! Got distracted; before I give the go-ahead, I want to briefly confirm (in about ~15min) that there isn't an upstream issue (how we bind the methods).

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 295 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8615#-LAKhKxt8yCSAgLY2mGL:-LAKhKxt8yCSAgLY2mGM:b-mx6a7m) ([raw file](https://github.com/robotlocomotion/drake/blob/d195f76baa00986c33c6ef7b4b13c4a38677e0ab/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L295)):*
> ```Python
>     def test_set_initial_guess(self):
>         prog = mp.MathematicalProgram()
>         # Make the decision variable matrix explicitely
> ```

BTW Greg, if you end up rebasing vs. squashing and merging, can you mention #8620 here? (No worries if not.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8615)*

**Comment by EricCousineau-TRI** [comment]
Submitted chaser fix in #8621

**Comment by gizatt** [comment]
Will merge this to get master back to a good state when tests are good. Though I missed the output of everything-debug with revising that comment... can I do this? @drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 295 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8615#-LAKhKxt8yCSAgLY2mGL:-LALArlx7Nt6ppHCLh-E:beygvsy) ([raw file](https://github.com/robotlocomotion/drake/blob/d195f76baa00986c33c6ef7b4b13c4a38677e0ab/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L295)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Greg, if you end up rebasing vs. squashing and merging, can you mention #8620 here? (No worries if not.)
</blockquote></details>

Done -- I'm in support of the test format in PR #8621 taking over once this is stable. Looks like it's a little more thorough in testing the really-common 1d-decision-variable-array case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8615#-:-LALBX2a3C1a9QRkT-7j:b-146bb8)*

**Pull request merged**
