### PR TITLE
Add ComPositionConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
One step towards #14914

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918#-:-MYWzuMX-Y4wxLmyvKkD:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Thanks!  First pass done. 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918#-:-MYZume34Li0r0TczHf1:b-bsjyps)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/test/inverse_kinematics_test.py, line 466 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZr3037HKKxTdh4whR:-MYZr3037HKKxTdh4whS:b-c3wc4u) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/bindings/pydrake/multibody/test/inverse_kinematics_test.py#L466)):*
> ```Python
>             plant=variables.plant,
>             model_instances=None,
>             expressed_frame=variables.body1_frame,
> ```

nit: could we make this world_frame, since I think using a body_frame is clear, but world_frame might be more common and less obvious for users to find?
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrG5W2m1HTVwOtVip:-MYZrG5W2m1HTVwOtViq:blem8cn) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L14)):*
> ```objc
> /**
>  * Impose the constraint f(q) - r = 0, where f(q) computes the center-of-mass
>  * (COM) position from robot generalized position q. r is the variable
> ```

"r is the variable" ... can we make it clear that it's a 3x1 vector?
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrgfl87Qn5o2f6fL2:-MYZrgfl87Qn5o2f6fL3:b-avid2z) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L33)):*
> ```objc
>    *   `plant`. We will update the context when evaluating the constraint.
>    *   `plant_context` should be alive during the lifetime of this constraint.
>    * @throws std::invalid_argument if `plant` is nullptr.
> ```

also if plant_context is nullptr
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrmLxEI4J0CmTy90i:-MYZrmLxEI4J0CmTy90j:b6d3icn) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L41)):*
> ```objc
>       systems::Context<double>* plant_context);
> 
>   ComPositionConstraint(
> ```

btw -- i'm curious on your logic for supporting both workflows?  isn't the double workflow always to be preferred?  (I saw it in PositionConstraint, etc, but assumed it was just vestigial?)
___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsDUV9DkGfC4BNyG1:-MYZsDUV9DkGfC4BNyG2:b-xdhro9) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L58)):*
> ```cpp
>       context_autodiff_{plant_context} {
>   // TODO(hongkai.dai): allow model_instances to have value when #14916 is
>   // resolved.
> ```

btw, maybe it actually works ok in the autodiff case, since 14916 is only about the jacobian not taking the model_instances?
___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYZsh-51K7P0DizUJ23:b-bbxta6) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
> ```cpp
> }
> 
> // T can be either double or AutoDiffXd
> ```

I initially thought this would only get called for T=AutoDiffXd, but now see it's also getting called when `DoEvalGeneric` is <double, double>?

I think it's pretty confusing.  You call a method named `EvalConstraintGradient` even when you don't want it to compute the gradients, and it doesn't compute the gradients?  As a minimal change, perhaps we can call it `MaybeEvalConstraintGradient`, or something?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[multibody/inverse_kinematics/com_position_constraint.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrG5W2m1HTVwOtVip:-MYa16dL38_z79C_jnm6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L14)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"r is the variable" ... can we make it clear that it's a 3x1 vector?
</blockquote></details>

Done.
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrgfl87Qn5o2f6fL2:-MYa1CYx2f_VnXeJAigL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

also if plant_context is nullptr
</blockquote></details>

Done.
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZrmLxEI4J0CmTy90i:-MYa1ER453TlPqQhSsf1:b-h0y86u) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.h#L41)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i'm curious on your logic for supporting both workflows?  isn't the double workflow always to be preferred?  (I saw it in PositionConstraint, etc, but assumed it was just vestigial?)
</blockquote></details>

Yes if we would prefer the double workflow if both double and ADS are available. On the other hand, some other constraints might not support the double workflow yet (for example, we can only compute the centroidal momentum using MBP<ADS>). So if we want to solve an optimization problem with both center of mass constraint and centroidal momentum constraint, I think we would use the MBP<ADS>, and use the ADS workflow.

The alternative is that for the optimization program with both center-of-mass constraint and centroidal momentum constraint, we keep an MBP<double> and an MBP<ADS>. We construct the center-of-mass constraint with MBP<double>, and centroidal momentum constraint with MBP<ADS>. But then the user will have to make sure MBP<ADS> and MBP<double> are synchronized.
___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsDUV9DkGfC4BNyG1:-MYaIVO73u9LBX5BtXvt:b-23y1zn) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L58)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw, maybe it actually works ok in the autodiff case, since 14916 is only about the jacobian not taking the model_instances?
</blockquote></details>

Good call. I enabled this for AutoDiff version.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYaN6Y68_0ZFsahRImA:b-q6k18t) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I initially thought this would only get called for T=AutoDiffXd, but now see it's also getting called when `DoEvalGeneric` is <double, double>?

I think it's pretty confusing.  You call a method named `EvalConstraintGradient` even when you don't want it to compute the gradients, and it doesn't compute the gradients?  As a minimal change, perhaps we can call it `MaybeEvalConstraintGradient`, or something?
</blockquote></details>

Good call. I renamed it to `MaybeEvalConstraintGradient` for other classes as well.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYabVY_4gWv8mJURLj1:b-77x1j7) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call. I renamed it to `MaybeEvalConstraintGradient` for other classes as well.
</blockquote></details>

Done. I switched to using `if constexpr` for different scalar types, I think the code is more readable this way.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@seancurtis-tri for platform review, please.

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918#-:-MYbdM1CATAJBc-dR5DL:b-51dy6f)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYbczRk58QuXfRPgaX5:b-n7ec9y) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I switched to using `if constexpr` for different scalar types, I think the code is more readable this way.
</blockquote></details>

much nicer!

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of small cosmetic things.

> Reviewed 2 of 7 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918#-:-MYfdSau-SJpWKa5J3gi:btcw6dg)* status: 5 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/com_position_constraint.h, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYfXk-B3TzJKKIDSzTS:-MYfXk-B3TzJKKIDSzTT:b-xj8zyx) ([raw file](https://github.com/robotlocomotion/drake/blob/063949baf07dd77af0c8361dbc4fca6c2b042b56/multibody/inverse_kinematics/com_position_constraint.h#L3)):*
> ```objc
> #pragma once
> 
> #include <memory>
> ```

nit Not used in this file? Probably just belongs in the .cc file.
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYep49a0ymyVb-LGiDk:-MYep49a0ymyVb-LGiDl:b6b09ap) ([raw file](https://github.com/robotlocomotion/drake/blob/063949baf07dd77af0c8361dbc4fca6c2b042b56/multibody/inverse_kinematics/com_position_constraint.h#L13)):*
> ```objc
> namespace multibody {
> /**
>  * Impose the constraint CenterOfMass(q) - p_EC = 0, where CenterOfMass(q)
> ```

nit: Thoughts on notation:

You've got a very  mixed expression with `CenterOfMass(q)` and `p_EC`. It would be better if it all used notation. We have [documented notation](https://drake.mit.edu/doxygen_cxx/group__multibody__frames__and__bodies.html) for center of mass: e.g., center of mass of body `B` is `Bcm`. Perhaps `p_EScm(q) - p_EC = 0`, where `S` is the full system? And `Scm` is the center of mass of the system? 

Getting the notation consistent will reduce the burden on the prose.
___
*[multibody/inverse_kinematics/com_position_constraint.h, line 86 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYfXN-C0YwDESoDOuFn:-MYfXN-D9MgTj81SlOOl:byuy68l) ([raw file](https://github.com/robotlocomotion/drake/blob/063949baf07dd77af0c8361dbc4fca6c2b042b56/multibody/inverse_kinematics/com_position_constraint.h#L86)):*
> ```objc
>   }
> 
>   bool use_autodiff() const { return plant_autodiff_; }
> ```

BTW Your reader would benefit from not having to type conversion in their minds: `plant_autodiff_ != nullptr`. Not defective as is.
___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYfcx02DqoZDHP8BQOk:-MYfcx02DqoZDHP8BQOl:b-wqbj9) ([raw file](https://github.com/robotlocomotion/drake/blob/063949baf07dd77af0c8361dbc4fca6c2b042b56/multibody/inverse_kinematics/com_position_constraint.cc#L104)):*
> ```cpp
>       *context, plant.get_frame(expressed_frame_index), plant.world_frame());
>   const Vector3<T> p_EC = X_EW * p_WC;
>   if constexpr (std::is_same<T, S>::value) {
> ```

BTW The modern way to do this is:

`std::is_same_v<T, S>`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYfcx02DqoZDHP8BQOk:-MYg-GEY5Z5Y2fThws6M:bp2hx8e) ([raw file](https://github.com/robotlocomotion/drake/blob/063949baf07dd77af0c8361dbc4fca6c2b042b56/multibody/inverse_kinematics/com_position_constraint.cc#L104)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The modern way to do this is:

`std::is_same_v<T, S>`
</blockquote></details>

Done. TIL is_same_v.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYgLwlu7UyVq-t2_fI1:b9k3r8e) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

much nicer!
</blockquote></details>

@russtedrake are you OK to resolve this comment?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[multibody/inverse_kinematics/com_position_constraint.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14918#-MYZsh-51K7P0DizUJ22:-MYgMWr4CefOg-zT37kF:bxjk24f) ([raw file](https://github.com/robotlocomotion/drake/blob/9578fa2f7f707395c6447f82c439582f99dc8572/multibody/inverse_kinematics/com_position_constraint.cc#L79)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@russtedrake are you OK to resolve this comment?
</blockquote></details>

Given his "much nicer", I say we can remove him and merge.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14918)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
