### PR TITLE
Do not build tests in lcm external

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3927)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
...as much as I wouldn't mind keeping the tests, they can be a little flaky, so we probably don't want CI choking on them. That being the case... :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3927#-:-KV5qU79iMmxK22i5foj:bz4jh69)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3927#-:-KV6aznHpbsTT_qrtB7o:bnfp4nl)*

**Pull request merged**
