### PR TITLE
Saturating version of ConnectController

### PR DESCRIPTION
**Pull request by naveenoid**
Constant Saturation added to an alternative ConnectController Method. Needed to utilise input-saturating PID controller.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4872)

### CODE REVIEW

**Comment by naveenoid** [comment]
@sammy-tri : feature review.

**Comment by naveenoid** [comment]
Obviously, it needs saturation ( #4798 ) to land first.

**Comment by sammy-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbCZNXD3ZVWj89f1AKt:-KbCZNXESdZmJ9nbr7bi:b6iwmea) ([raw file](https://github.com/robotlocomotion/drake/blob/2b08ebed5ca6120bba5219f416fa1fbbcc72f37e/drake/systems/controllers/pid_controlled_system.cc#L74)):*
> ```cpp
>     std::unique_ptr<MatrixGain<T>> feedback_selector, const VectorX<T>& Kp,
>     const VectorX<T>& Ki, const VectorX<T>& Kd, DiagramBuilder<T>* builder) {
>   if (feedback_selector == nullptr) {
> ```

This feels like a lot of copied code...   Let me propose an alternative...  Couldn't the version which takes the limits do the following?

 * Create the Saturation system
 * Connect the output of the Saturation system to the plant_input argument
 * Pass the input port of the Saturation system to the existing version of ConnectController

(actually I'm not sure it's compelling to do that in an overload of ConnectController as opposed to in the caller before ever invoking ConnectController, but that would require some speculation about callers which don't exist yet as of this PR)

At any rate, my primary issue here is the significant amount of copied code for setting up a somewhat complex diagram, as I think it will be difficult both to read and to maintain effectively.  I'm not insisting that the solution be what I proposed above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872)*

**Comment by naveenoid** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/controllers/pid_controlled_system.cc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbCZNXD3ZVWj89f1AKt:-KbClVrFdw0uZvP0cwyy:b-iyo0tq) ([raw file](https://github.com/robotlocomotion/drake/blob/2b08ebed5ca6120bba5219f416fa1fbbcc72f37e/drake/systems/controllers/pid_controlled_system.cc#L74)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This feels like a lot of copied code...   Let me propose an alternative...  Couldn't the version which takes the limits do the following?

 * Create the Saturation system
 * Connect the output of the Saturation system to the plant_input argument
 * Pass the input port of the Saturation system to the existing version of ConnectController

(actually I'm not sure it's compelling to do that in an overload of ConnectController as opposed to in the caller before ever invoking ConnectController, but that would require some speculation about callers which don't exist yet as of this PR)

At any rate, my primary issue here is the significant amount of copied code for setting up a somewhat complex diagram, as I think it will be difficult both to read and to maintain effectively.  I'm not insisting that the solution be what I proposed above.
</blockquote></details>

I like this suggestion and will work on implementing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 213 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbGmUcV-8TWv7lP02tW:-KbGmUcWzaeDZ0go8l_e:b-5j2xer) ([raw file](https://github.com/robotlocomotion/drake/blob/bd3a92e975869300818e5c1300d11f8f2888c25e/drake/systems/controllers/test/pid_controlled_system_test.cc#L213)):*
> ```cpp
>         plant_input_port, plant_output_port, std::move(feedback_selector), Kp,
>         Ki, Kd, VectorX<double>::Constant(1, 0.0) /* u_min */,
>         VectorX<double>::Constant(1, 0.5) /* u_max */, &standardBuilder);
> ```

The 0.5 u_max constant is repeated below.  Perhaps it should be a named constant?

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 241 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbGmiSUeMygrOqP-SGv:-KbGmiSUeMygrOqP-SGw:b-layae1) ([raw file](https://github.com/robotlocomotion/drake/blob/bd3a92e975869300818e5c1300d11f8f2888c25e/drake/systems/controllers/test/pid_controlled_system_test.cc#L241)):*
> ```cpp
>     EXPECT_EQ(pid_input, calculated_input);
>   } else {
>     if (calculated_input > 0.5 /* u_max */) {
> ```

Shouldn't the calculated input always be above u_max when we're doing the saturation test? (otherwise we're not really testing anything)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbGnO9RICGRtBSSkSRF:b-s794vx)*

**Comment by naveenoid** [comment]
+@david-german-tri for platform review (since @sammy-tri is already on feature review). 

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 213 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbGmUcV-8TWv7lP02tW:-KbKYrQmbEu1z12O0tRa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bd3a92e975869300818e5c1300d11f8f2888c25e/drake/systems/controllers/test/pid_controlled_system_test.cc#L213)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The 0.5 u_max constant is repeated below.  Perhaps it should be a named constant?
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 241 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbGmiSUeMygrOqP-SGv:-KbKYs002z6kMuyqheNR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bd3a92e975869300818e5c1300d11f8f2888c25e/drake/systems/controllers/test/pid_controlled_system_test.cc#L241)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Shouldn't the calculated input always be above u_max when we're doing the saturation test? (otherwise we're not really testing anything)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbKZImPH1ptWE4qbDQ8:btd34eq)*

**Comment by david-german-tri** [comment]
I'll await feature LGTM.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbL-_YxJqLR4oeMN10i:bpppisp)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbLG2bY0HZjVc6GM7dI:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/pid_controlled_system.h, line 164 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM9dbPKXzQ_UPj7Hnv:-KbM9dbPKXzQ_UPj7Hnw:b-w711hl) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/pid_controlled_system.h#L164)):*
> ```objc
>   /// needed. Note that using input limits along with integral gain constant
>   /// may result in integral windup effects.
>   static ConnectResult ConnectController(
> ```

This shouldn't be an overload; it's not at all obvious from a call site what the two extra VectorX arguments do.  Please give it a different name.

https://google.github.io/styleguide/cppguide.html#Function_Overloading

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 179 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM9s4fxrnSxoTJcGFF:-KbM9s4gwKyM52y_a9zO:b8ivg4m) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L179)):*
> ```cpp
> // plant. The saturation_test flag can be set to enable testing the variant
> // of the ConnectController method that includes a Saturation in the input.
> void DoConnectControllerTest(bool saturation_test = false) {
> ```

I applaud the code reuse, but we should aim to distinguish shared logic from logic that is specific to just one code path.  I think rephrasing this as a test fixture with accessor methods would help.  Specific suggestions follow.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 184 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM8u74nEsRpGhgWY7e:-KbM8u75wLt2sfewPX1b:b-wp5c43) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L184)):*
> ```cpp
>       std::make_unique<MatrixGain<double>>(plant->get_output_port(0).size());
> 
>   DiagramBuilder<double> standardBuilder;
> ```

https://google.github.io/styleguide/cppguide.html#Variable_Names

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 200 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMAoyiEUF_P7cpDs7x:-KbMAoyiEUF_P7cpDs7y:b-jnm9ww) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L200)):*
> ```cpp
> 
>   // Sets the max input in the case of saturation_test.
>   const double saturation_max = 0.5;
> ```

Everything up to this point, and the `ExportOutput(plant_output_port)` below, can go in `SetUp`.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 204 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCT9ITrTv0_AtYqxk:-KbMAyYh9vtdtcJwcKO5:b-33segb) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L204)):*
> ```cpp
> 
>   if (!saturation_test) {
>     auto plant_pid_ports = PidControlledSystem<double>::ConnectController(
> ```

The actual call to `ConnectController` can go in the TEST_F body.  (Fixture data members are allowed to be `protected`, so all the inputs are readily available.)

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 208 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCZrQJmZvu9dJ7Ygq:-KbMB3WYygI-WSIuFp17:bq6i2bi) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L208)):*
> ```cpp
>         Ki, Kd, &standardBuilder);
> 
>     standardBuilder.Connect(input_source->get_output_port(),
> ```

These two lines (which are duplicated below) can go in a fixture member function `void ConnectControllerInputs(plant_pid_ports)`.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCk1td32A_1Q20SPf:-KbMCk1td32A_1Q20SPg:b-xoyhqo) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L227)):*
> ```cpp
>   standardBuilder.ExportOutput(plant_output_port);
> 
>   auto standard_diagram = standardBuilder.Build();
> ```

These next few lines are a fixture member function `double ComputePidInput()`

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCwnAp45C7-ROIZTC:-KbMCwnAp45C7-ROIZTD:bx9m83b) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L243)):*
> ```cpp
>                             (state[1] - output_vec->get_value()[1]) * Kd(0);
>   if (!saturation_test) {
>     EXPECT_EQ(pid_input, calculated_input);
> ```

And finally, the assertion goes in the body of the `TEST_F`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 164 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM9dbPKXzQ_UPj7Hnv:-KbMobmVEci_1q-Dfddd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/pid_controlled_system.h#L164)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This shouldn't be an overload; it's not at all obvious from a call site what the two extra VectorX arguments do.  Please give it a different name.

https://google.github.io/styleguide/cppguide.html#Function_Overloading
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 179 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM9s4fxrnSxoTJcGFF:-KbPmr8L-HkbYJYAxxWE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L179)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I applaud the code reuse, but we should aim to distinguish shared logic from logic that is specific to just one code path.  I think rephrasing this as a test fixture with accessor methods would help.  Specific suggestions follow.
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 184 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbM8u74nEsRpGhgWY7e:-KbMrarbRrRr35CGyWfz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L184)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Variable_Names
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 200 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMAoyiEUF_P7cpDs7x:-KbPMYsx7KkvuI8EPu27:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L200)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Everything up to this point, and the `ExportOutput(plant_output_port)` below, can go in `SetUp`.
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 204 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCT9ITrTv0_AtYqxk:-KbPMZkk8pBwhk9akpmQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L204)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

The actual call to `ConnectController` can go in the TEST_F body.  (Fixture data members are allowed to be `protected`, so all the inputs are readily available.)
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 208 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCZrQJmZvu9dJ7Ygq:-KbPO5Bp7XQ_-NwxnrVB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L208)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

These two lines (which are duplicated below) can go in a fixture member function `void ConnectControllerInputs(plant_pid_ports)`.
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCk1td32A_1Q20SPf:-KbPmp59dJMxVpbsKsBX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L227)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

These next few lines are a fixture member function `double ComputePidInput()`
</blockquote></details>

Done.

---

*[drake/systems/controllers/test/pid_controlled_system_test.cc, line 243 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-KbMCwnAp45C7-ROIZTC:-KbPmpNadTTiuZYvS90r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c230b93c3a4623663b8730c51f24d9ac1f032801/drake/systems/controllers/test/pid_controlled_system_test.cc#L243)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

And finally, the assertion goes in the body of the `TEST_F`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbQyQ9_tntCkfqvf13f:bnfp4nl)*

**Comment by david-german-tri** [comment]
(aside from CI complaints and commit curation)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbQySSGH6tqhWj9yYeh:bshoc3h)*

**Comment by naveenoid** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbSObj3jQb7XvI_VWJD:b-28mrlv)*

**Comment by naveenoid** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbSPuaH8StG4TkiysSE:b-rm2p6t)*

**Comment by naveenoid** [comment]
@sammy-tri : Could you please take a look at the failing bazel builds and suggest a fix. Im afraid I wont have time to resolve that..

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbSVI8P8kHJKbV0_zG_:bkciqh2)*

**Comment by jwnimmer-tri** [comment]
The BUILD files have been fixed.  Just needs a reviewer to check them over.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbSanbYKSkmXrWb2EN8:bwyeknd)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbVMA3jl_JyqG9rbDFZ:bnfp4nl)*

**Comment by sammy-tri** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4872#-:-KbX0jYVbRfNTnpZ0IZd:b-l70wzf)*

**Pull request merged**
