### PR TITLE
Adds AutomotiveSimulator::GetContextToString().

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards #5857. The resulting string currently only includes information about the SimpleCars' and MaliputRailcars' continuous state vectors (i.e., `SimpleCarState` and `MaliputRailcarState`) and numerical parameters (`SimpleCarParams` and `MaliputRailcarParams`). If this is the direction we want to go in, I will submit follow-up PRs that include additional information contained in the `Context`.

Here is an example string produced by the changeset in this PR:

```
AutomotiveSimulator Context:
  - Time: 0
  - Number of SimpleCars: 2
    - SimpleCar:
      - Name: Model1
      - Parameters:
        - wheelbase: 2.7
        - track: 1.521
        - max_abs_steering_angle: 0.471
        - max_velocity: 45
        - max_acceleration: 4
        - velocity_limit_kp: 10
      - State:
        - x: 0
        - y: 0
        - heading: 0
        - velocity: 0
    - SimpleCar:
      - Name: Model2
      - Parameters:
        - wheelbase: 2.7
        - track: 1.521
        - max_abs_steering_angle: 0.471
        - max_velocity: 45
        - max_acceleration: 4
        - velocity_limit_kp: 10
      - State:
        - x: 0
        - y: 0
        - heading: 0
        - velocity: 0
  - Number of Maliput Railcars: 1
    - MaliputRailcar:
      - Name: My Railcar
      - Parameters:
        - r: 1
        - h: 0
        - max_speed: 45
        - velocity_limit_kp: 10
      - State:
        - s: 0
        - speed: 0
```

The above text was obtained by printing the `result` string in the included "TestContextToString" unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5910)

### CODE REVIEW

**Comment by liangfok** [comment]
+@russtedrake for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-:-KiCuK9rVwm80QZgePFH:b-6sovui)*

**Comment by jwnimmer-tri** [comment]
*[drake/tools/lcm_vector_gen.py, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCvOr13oDQj-nds8EO:-KiCvOr13oDQj-nds8EP:bbiycv5) ([raw file](https://github.com/robotlocomotion/drake/blob/e800c69e0d470454dd83f0ff96bd5c1ac3d45180/drake/tools/lcm_vector_gen.py#L192)):*
> ```Python
> 
> TO_STRING_VARIABLE = """
>     result << prefix << \"- %(field)s = \" << %(field)s() << \"\\n\";
> ```

This hard-coded bullet format (e.g., no control of precision) is not so great for a general tool, maybe?  What do you think about a new method, e.g.:

```c++
class SimpleCarStateIndices {
  ...
  static const std::vector<std::string>& GetCoordinateNames();
};
```
This could be hidden in the `.cc` file and use latch-initialization (`never_destroyed` in Drake).

If we wanted, we could sugar it onto the vector itself:
```c++
class SimpleCarState {
  ...
  static const std::vector<std::string>& GetCoordinateNames() {
    return SimpleCarStateIndices::GetCoordinateNames();
  }
};
```

In any case, then calling code could decide how to zip up coordinate names with their real-number values for formatting and output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910)*

**Comment by liangfok** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/lcm_vector_gen.py, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCvOr13oDQj-nds8EO:-KiCx1PezzSWcv4f47fW:buhqaqh) ([raw file](https://github.com/robotlocomotion/drake/blob/e800c69e0d470454dd83f0ff96bd5c1ac3d45180/drake/tools/lcm_vector_gen.py#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This hard-coded bullet format (e.g., no control of precision) is not so great for a general tool, maybe?  What do you think about a new method, e.g.:

```c++
class SimpleCarStateIndices {
  ...
  static const std::vector<std::string>& GetCoordinateNames();
};
```
This could be hidden in the `.cc` file and use latch-initialization (`never_destroyed` in Drake).

If we wanted, we could sugar it onto the vector itself:
```c++
class SimpleCarState {
  ...
  static const std::vector<std::string>& GetCoordinateNames() {
    return SimpleCarStateIndices::GetCoordinateNames();
  }
};
```

In any case, then calling code could decide how to zip up coordinate names with their real-number values for formatting and output.
</blockquote></details>

I like that and will update this PR accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910)*

**Comment by jwnimmer-tri** [comment]
I am going to hold off on further review until @RussTedrake chimes in on the overall idea.

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCx4uW8k_EHRAS-c00:-KiCx4uW8k_EHRAS-c01:b-clubww) (no related file):*
In general, when we change `lcm_vector_gen`'s default output, we should do it in a separate PR, and regenerate _all_ of the uses at once in the same PR:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ find drake -name '*gen*.sh' | grep -v lcm_vector_gen
drake/tools/test/gen/_regenerate.sh
drake/automotive/simple_car_gen.sh
drake/examples/Pendulum/pendulum_gen.sh
drake/examples/Acrobot/acrobot_gen.sh
drake/examples/schunk_wsg/schunk_wsg_trajectory_generator_gen.sh
```

(Just run that through `| xargs bash`.)

I apologize that this is neither automated nor documented yet.

(Aside: before breaking that out into a preemptive PR, though, we should usually agree whether this PR is headed in the right direction first.  However, I think "give me the list of string names" discussed below seems fundamental to the `vector_gen` contract, so I would support that PR whether or not this PR happens.)

---

*[drake/tools/lcm_vector_gen.py, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCvOr13oDQj-nds8EO:-KiCx_KNCXfSGFZ07z_n:btojbfq) ([raw file](https://github.com/robotlocomotion/drake/blob/e800c69e0d470454dd83f0ff96bd5c1ac3d45180/drake/tools/lcm_vector_gen.py#L192)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

I like that and will update this PR accordingly.
</blockquote></details>

Great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-:-KiCxsmNFtHEuTfzVU3m:b-p4bwob)*

**Comment by liangfok** [comment]
SGTM.

---

Review status: 0 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCx4uW8k_EHRAS-c00:-KiDY2qwzTkTeU68Vp1T:b-j9s793) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In general, when we change `lcm_vector_gen`'s default output, we should do it in a separate PR, and regenerate _all_ of the uses at once in the same PR:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ find drake -name '*gen*.sh' | grep -v lcm_vector_gen
drake/tools/test/gen/_regenerate.sh
drake/automotive/simple_car_gen.sh
drake/examples/Pendulum/pendulum_gen.sh
drake/examples/Acrobot/acrobot_gen.sh
drake/examples/schunk_wsg/schunk_wsg_trajectory_generator_gen.sh
```

(Just run that through `| xargs bash`.)

I apologize that this is neither automated nor documented yet.

(Aside: before breaking that out into a preemptive PR, though, we should usually agree whether this PR is headed in the right direction first.  However, I think "give me the list of string names" discussed below seems fundamental to the `vector_gen` contract, so I would support that PR whether or not this PR happens.)
</blockquote></details>

Done. I extracted the lcm_vector_gen.py changes to #5912.

---

*[drake/tools/lcm_vector_gen.py, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-KiCvOr13oDQj-nds8EO:-KiDY49-ZAPcTqzhQsTC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e800c69e0d470454dd83f0ff96bd5c1ac3d45180/drake/tools/lcm_vector_gen.py#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Great.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-:-KiDY5_fGEHe34QoaDwn:b-81nlyc)*

**Comment by jwnimmer-tri** [comment]
Evidence suggests that the label "Priority: High" is not accurate.

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri for platform.  Without feature review happening, it's not worth keeping on my plate.  Feel free to re-assign per rotation or directly back to me, once feature review is done.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5910#-:-Kjj08gdhbBfkzdQ_QK8:bz1omo)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
I'm going to close this PR for now. It can always be re-opened in the future if the need arises. Most likely, this PR will be supplanted by a version that supports a to-string method for contexts in general, and not be specific to automotive applications.

**Pull request closed without merging**
