### PR TITLE
[geometry:meshcat] clean up pass on per-thread variables

### PR DESCRIPTION
**Pull request by RussTedrake**
Variables in WebSocketPublisher are documented for use in either the main thread or the websocket thread.  This cleans up that contract, and fixes some violations.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15827)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri   -- following up on your comment from the last PR.  I agree that I had some inconsistencies.

Unfortunately, these changes did not resolve the segfault (if I were to revert to the old `ws->close()` spelling).  And also did not resolve the mac asan issue.  But I hope you agree they are an improvement.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15827#-:-MkcHpTh1Mz2yDQ-9Z_M:b-dt0p3c)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Quick question -- are you sure you want me to review this? I didn't review the original inclusion of websockets and its implementation. If I do feature review, I'll have to bone up on all of those details I have so far ignored.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15827#-:-MkcyVPk6TGFPPLjrkEe:b5l0yz)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15827#-Mkcf4pT27Ml8QbnRez8):*
nit: Line breaks please.

Plus it would be really helpful if you characterized the nature of the clean up. For example. clean up could mean "enforcing restrictions" or "removing inappropriate restrictions". Two very different effects and right now, the reader has to dive through the code to figure this out.

And looking at the actual changes, it looks like this will require a fair amount of archaeology on my part.

**Review by RussTedrake — COMMENTED** [review]
-@seancurtis-tri for review.
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15827#-:-MkdtEKn97DzyURHyegd:brmwpnf)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15827#-:-MkhJSOPABHZJLIaIAgg:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15827#-MkhKmHH-ouOhqGE6tMd:-MkhKmHIEnvfiXjR_wiP:b-ue13lh) (no related file):*
I didn't try to read the diffs directly, instead I did some local code fiddling and tried to verify the member field properties.
 
First, I added more thread id checks (and a few others), just to clarify the flow for myself. See https://github.com/rpoyner-tri/drake/commit/8bdd0845962df1427a7866a1fc367284e31c3cf9 . If you want to steal that patch, feel free. If you want me to PR it, I can.

Then, I reran all of the relevant tests (dynamic analysis) to have some evidence the added assertions were true.

Finally, I went through each of the member variables and checked all the access sites (static analysis) to see that usage matched with the documented properties.

---

**Comment by RussTedrake** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15827#-MkhKmHH-ouOhqGE6tMd:-MkhUigH1bpWe6HqBWgy:bmsdbrf) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I didn't try to read the diffs directly, instead I did some local code fiddling and tried to verify the member field properties.
 
First, I added more thread id checks (and a few others), just to clarify the flow for myself. See https://github.com/rpoyner-tri/drake/commit/8bdd0845962df1427a7866a1fc367284e31c3cf9 . If you want to steal that patch, feel free. If you want me to PR it, I can.

Then, I reran all of the relevant tests (dynamic analysis) to have some evidence the added assertions were true.

Finally, I went through each of the member variables and checked all the access sites (static analysis) to see that usage matched with the documented properties.
</blockquote></details>

Thank you.  I had considered adding the thread check inside the loop->defers, and would be happy to have it.  It looks like you caught one check that I missed, too.  PR'ing that commit sounds great to me.

---

**Pull request merged**
