### PR TITLE
Monolithic pick and place demo - diagram factory

### PR DESCRIPTION
**Pull request by naveenoid**
Ongoing PR train towards #3910 .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5715)

### CODE REVIEW

**Comment by naveenoid** [comment]
-(status: do not review) 
+(priority: high) 
+@sammy-tri for feature and platform review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-:-Kh-89mcvolbshdiurgI:b-9srqmi)*

**Comment by sammy-tri** [comment]
Waiting on rebase after #5713 merge to review.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-:-Kh2iv592rKKN9woHzJ0:b-496t5j)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh84I91pdlDiFasmBA2:-Kh84I91pdlDiFasmBA3:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L41)):*
> ```Python
>     deps = [
>         ":iiwa_state_feedback_plan",
>         "//drake/common/trajectories:piecewise_quaternion",
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh847CNsZSCqD2x8afN:-Kh847CNsZSCqD2x8afO:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L42)):*
> ```Python
>         ":iiwa_state_feedback_plan",
>         "//drake/common/trajectories:piecewise_quaternion",
>         "//drake/examples/kuka_iiwa_arm:iiwa_plan_source",
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh84BTvu-0fadpYLXg0:-Kh84BTvu-0fadpYLXg1:buzc58k) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L43)):*
> ```Python
>         "//drake/common/trajectories:piecewise_quaternion",
>         "//drake/examples/kuka_iiwa_arm:iiwa_plan_source",
>         "//drake/systems/primitives:constant_vector_source",
> ```

unused?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh88Fovpvy7ANEruH18:-Kh88FowyH0jIqSQaZG_:bbj3quw) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.cc#L84)):*
> ```cpp
>       plant_->get_output_port_wsg_state().size(), 0, 0);
> 
>   pass_through_wsg_state_ = builder.template AddSystem<PassThrough<T>>(
> ```

It's not clear to me what this PassThrough is doing here.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh858HjoVgUd2mKdmUh:-Kh858HkuMtnoxBeWTu6:bb7twzu) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L17)):*
> ```objc
> 
> namespace drake {
> using systems::DrakeVisualizer;
> ```

We should not be "using" in header files, as it causes the new namespace for the used classes to be part of the exported API of this header.  https://google.github.io/styleguide/cppguide.html#Namespaces

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh86I__iKltoWrPf64-:-Kh86I__iKltoWrPf640:b59ydmt) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/demo_diagram_builder.h#L107)):*
> ```objc
>   /// Visualizer
>   IiwaWsgPlantGeneratorsEstimatorsAndVisualizer(
>       DrakeLcm* lcm, const double update_interval = 0.001);
> ```

Document what update_interval does?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-Kh84ce-p8tXo7llfpWq:-Kh84ce-p8tXo7llfpWr:b-i9izcy) ([raw file](https://github.com/robotlocomotion/drake/blob/f261a5736464dd55fa90aab7103dea432c7ac1b6/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L16)):*
> ```objc
> using systems::PassThrough;
> namespace examples {
> // using schunk_wsg::SchunkWsgStatusSender;
> ```

leftover commented out code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5715)*

**Comment by naveenoid** [comment]
After discussion with @siyuanfeng-tri I will proceed with just the monster #5753 . I will integrate the fixes for the defects you found here. Thanks! 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5715#-:-KhDvCcmA8jsIIeC5zOx:beb1bm6)*

**Comment by sammy-tri** [comment]
Closing since we don't intend to integrate this.

**Pull request closed without merging**
