### PR TITLE
[workspace] Upgrade googlebenchmark to v1.7.1

### LINKED ISSUE #18435: Upgrade googlebenchmark  from 1.7.0 to 1.7.1
Follow-up to #18379.

When attempting to update googlebenchmark, I get the following error:

```
~/develop/drake$ bazel-bin/tools/workspace/new_release --upgrade=googlebenchmark
Collecting bazel repository details...
INFO: All external dependencies fetched successfully.
Loading: 0 packages loaded
Upgrading googlebenchmark from v1.7.0 to v1.7.1
Downloading new archive...
Populating repository cache ...
ERROR: /home/local/KHQ/betsy.mcphail/.cache/bazel/_bazel_betsy.mcphail/4e753aaa1a8cee0cff3391e1459b0a22/external/googlebenchmark/BUILD.bazel:29:11: no such package '@libpfm//': The repository '@libpfm' could not be resolved: Repository '@libpfm' is not defined and referenced by '@googlebenchmark//:benchmark'
ERROR: Evaluation of query "deps(//...)" failed: errors were encountered while computing transitive closure
Loading: 8 packages loaded
Traceback (most recent call last):
  File "/home/local/KHQ/betsy.mcphail/develop/drake/bazel-bin/tools/workspace/new_release.runfiles/drake/tools/workspace/new_release.py", line 352, in <module>
    main()
  File "/home/local/KHQ/betsy.mcphail/develop/drake/bazel-bin/tools/workspace/new_release.runfiles/drake/tools/workspace/new_release.py", line 344, in main
    _do_upgrade(temp_dir, gh, args.upgrade, metadata)
  File "/home/local/KHQ/betsy.mcphail/develop/drake/bazel-bin/tools/workspace/new_release.runfiles/drake/tools/workspace/new_release.py", line 279, in _do_upgrade
    subprocess.check_call(["bazel", "fetch", "//...", f"--distdir={temp_dir}"])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'fetch', '//...', '--distdir=/tmp/drake_new_release_uc1dfdub']' returned non-zero exit status 2.
```

I found a related google/benchmark issue: https://github.com/google/benchmark/issues/1510

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes #18435.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.
</blockquote></details>

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for design review, at your leisure. I'm in no hurry.
+(priority: low) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457#-:-NJLihPj52SbvSqsFHmg:b-uy0fbw)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJHEwGaCnz-13FS6Vui:-NJLioOy6dRqjJJiYrQ5:bvth5rt) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.
</blockquote></details>

So far, so good.

___

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: fix) 

:lgtm: feature modulo discussions.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457#-:-NJW4q5g3LqUjAWKT5aK:b-2hd09d)* status: 6 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW4n3F0DT2ZHATT8Ko:-NJW4n3F0DT2ZHATT8Kp:byd4xwk) (no related file):*
nit The PR title (to be used as the subject when merging) needs improvement.

___
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW4O8k6fZav-tRCLcT):*
The commits are not independent. This PR should just be 1 commit, so that (1) it's easier to revert the whole thing if necessary and (2) your reviewer doesn't need to _manually_ test whether CI would have passed at the halfway point between the two commits.  (For multi-commit PRs, it's incumbent upon the reviewer to ensure that all commits build on their own, unless the author has disclaimed that they won't build on their own e.g. when trying to preserve git history tracking.)
___
*[`tools/workspace/libpfm/repository.bzl` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW5iB9BSvYrbOXoTv_:-NJW5iB9BSvYrbOXoTva:b-85qpcd) ([raw file](https://github.com/robotlocomotion/drake/blob/0dab9af312342932544075d5fc9fdd80e038881a/tools/workspace/libpfm/repository.bzl#L3)):*
> ```Starlark
> # -*- mode: python -*-
> # vi: set ft=python :
> ```

nit Either here, or in `package.BUILD.bazel` we should have a comment to explain what's going on.  (That googlebenchmark needs a definition of libpfm at analysis-time, but does not use it at build-time, so we're stubbing it out with something that will **load** correctly, but would fail to **build** in case it were actually used.)
___
*[`tools/workspace/libpfm/repository.bzl` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW4zIs5Sqc7JbeBbtw:-NJW4zIs5Sqc7JbeBbtx:b-4w09du) ([raw file](https://github.com/robotlocomotion/drake/blob/0dab9af312342932544075d5fc9fdd80e038881a/tools/workspace/libpfm/repository.bzl#L12)):*
> ```Starlark
> libpfm_repository = repository_rule(
>     attrs = {
>         "modname": attr.string(default = "libpfm"),
> ```

nit To my eye, "modname" here is dead code, and so the entire `attrs` stanza should be removed.
___
*[`tools/workspace/libpfm/repository.bzl` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW5G2KEJqRsKjWfsEO:-NJW5G2KEJqRsKjWfsEP:b-jeis7y) ([raw file](https://github.com/robotlocomotion/drake/blob/0dab9af312342932544075d5fc9fdd80e038881a/tools/workspace/libpfm/repository.bzl#L14)):*
> ```Starlark
>         "modname": attr.string(default = "libpfm"),
>     },
>     local = True,
> ```

nit "local=True" is wrong.  There is [no need to re-run this rule when the dependency graph changes](https://bazel.build/rules/lib/globals#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc)).  This line should be removed.
___
*[`tools/workspace/libpfm/repository.bzl` line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW5Sd43WS1-sQ7CQep:-NJW5Sd43WS1-sQ7CQeq:b-1m5ugd) ([raw file](https://github.com/robotlocomotion/drake/blob/0dab9af312342932544075d5fc9fdd80e038881a/tools/workspace/libpfm/repository.bzl#L15)):*
> ```Starlark
>     },
>     local = True,
>     configure = True,
> ```

nit "configure=True" is wrong.  This rule does not [inspect the host system](https://bazel.build/rules/lib/globals#repository_rule(implementation,%20attrs,%20local,%20environ,%20configure,%20remotable,%20doc)).  This line should be removed.

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review, please (as a follow-up from #18447).

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457#-:-NKsVqVe4i2ckM6nAmuD:b-7zeui4)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
FYI, I’m out of office this week with very limited access to internet. Please expect some delay on the review.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18457#-:-NLMVVEW1Pt2drvQzjhH:bzus18)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

___
*[`tools/workspace/libpfm/repository.bzl` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18457#-NJW5iB9BSvYrbOXoTv_:-NLMVPYE62PJMLPkjCqM:b4m8pkv) ([raw file](https://github.com/robotlocomotion/drake/blob/0dab9af312342932544075d5fc9fdd80e038881a/tools/workspace/libpfm/repository.bzl#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Either here, or in `package.BUILD.bazel` we should have a comment to explain what's going on.  (That googlebenchmark needs a definition of libpfm at analysis-time, but does not use it at build-time, so we're stubbing it out with something that will **load** correctly, but would fail to **build** in case it were actually used.)
</blockquote></details>

TIL, thanks.

**Pull request merged**
