### PR TITLE
[fem] FemSolver takes scratch as input on solve

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This replaces the scratch data kept as a mutable data member and allows FemSolver to be placed in a System.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N8zfnLm8iwU0UHDRGul:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thanks @xuchenhan-tri. Only a couple questions before the final LGTM

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N92yFPcAfgzmyVHHlqa:b5hh94y)* status: 4 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/fem/fem_solver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92w9PFAVO-DiaXW7Hr:-N92w9PGD8yMK-qAFiHv:bnyneme) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L21)):*
> ```objc
> class FemSolverScratchData {
>  public:
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(FemSolverScratchData);
> ```

question, wouldn't it be reasonable to make this class have value semantics? that is, to use the DRAKE_DEFAULT_COPY_AND_STUFF macro here instead?
___
*[`multibody/fem/fem_solver.h` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92wkaeBIBpG7HcVelu:-N92wkaeBIBpG7HcVelv:b8fx2bo) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L39)):*
> ```objc
>   }
> 
>   VectorX<T>& mutable_b() { return b_; }
> ```

minor, I wonder if you considred more generic names that'd allow you to use say `b` in some other comptation. For instance, something like `vec_num_dofs1()`, `vec_num_dofs2()`, etc. to indicate sractch vectors of size `num_dof()` that can be used for whatever you might need.
___
*[`multibody/fem/fem_solver.h` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92waiiEc-ypCqgXZFu:-N92waiiEc-ypCqgXZFv:bxpu91c) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L50)):*
> ```objc
> 
>   std::unique_ptr<internal::PetscSymmetricBlockSparseMatrix> tangent_matrix_;
>   /* Stores the residual of the model. */
> ```

minor, probably move these comments to the getters so it's more visible?
___
*[`multibody/fem/fem_solver.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92xA7_2J4jC3HDJsk4:-N92xA7_2J4jC3HDJsk5:bn4wvzh) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L96)):*
> ```objc
>    incompatible with the FEM model solved by this solver. */
>   int AdvanceOneTimeStep(const FemState<T>& prev_state, FemState<T>* next_state,
>                          FemSolverScratchData<T>* scratch) const;
> ```

question, to avoid modifying in this way any other APIs that might require the use of scratch data, have considered placing the scratch data in the state? we do this in other places in Drake; we place scratch storage in a cache entry in the context.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the quick turnaround. I have trouble understanding one of the comments. PTAL below, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N93EXeK10ftkBv_mLFT:b-fcecbl)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/fem/fem_solver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92w9PFAVO-DiaXW7Hr:-N93CIRs0GmEcBLstrbA:b-351zkt) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

question, wouldn't it be reasonable to make this class have value semantics? that is, to use the DRAKE_DEFAULT_COPY_AND_STUFF macro here instead?
</blockquote></details>

Having the tangent matrix as a data member makes things complicated.

1. The tangent matrix doesn't support the default copy assign.
2. Copy construction needs to take a little bit of care because we need to ensure that the source matrix is assembled.

Because of these complications, I chose not to bother with these until we know that we actually need the value semantics.
___
*[`multibody/fem/fem_solver.h` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92wkaeBIBpG7HcVelu:-N93CziI5Jwdome_9Bh8:bb9ymuh) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, I wonder if you considred more generic names that'd allow you to use say `b` in some other comptation. For instance, something like `vec_num_dofs1()`, `vec_num_dofs2()`, etc. to indicate sractch vectors of size `num_dof()` that can be used for whatever you might need.
</blockquote></details>

I have a hard time picturing any other use cases for this scratch pad other than the specific use outlined in this PR. I tried replacing b and dz with the proposed names and I'm not crazy about how they look at the call site (i.e. SolveWithInitialGuess()).
___
*[`multibody/fem/fem_solver.h` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92waiiEc-ypCqgXZFu:-N93DcCG0bEhfopACVbO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, probably move these comments to the getters so it's more visible?
</blockquote></details>

Done.
___
*[`multibody/fem/fem_solver.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92xA7_2J4jC3HDJsk4:-N93Dg_kEOEqV4IFxNf0:bsey080) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L96)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

question, to avoid modifying in this way any other APIs that might require the use of scratch data, have considered placing the scratch data in the state? we do this in other places in Drake; we place scratch storage in a cache entry in the context.
</blockquote></details>

I have a hard time parsing what you meant by this comment after reading it closely a few times. Could you try paraphrasing it?

FWIW, I do plan to place this scratch in a cache entry in the context.

**Review by amcastro-tri — COMMENTED** [review]
Thanks for the explanations @xuchenhan-tri. TBH I had a different use case in mind when I looked at it the first time and I confused myself. This looks great. 

:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N9761lQ8G1ffgem3YL6:bvus4fr)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/fem/fem_solver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92w9PFAVO-DiaXW7Hr:-N975eLo2rlnl5Wt7BGe:b-mljcic) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Having the tangent matrix as a data member makes things complicated.

1. The tangent matrix doesn't support the default copy assign.
2. Copy construction needs to take a little bit of care because we need to ensure that the source matrix is assembled.

Because of these complications, I chose not to bother with these until we know that we actually need the value semantics.
</blockquote></details>

I see... that makes sense. I guess cache entries do need value semantics, and in cases like this we accomplish that with the expensive clone under the hood. The nice thing is that (I believe) we don't use the value semantics of cache entries at simulation time, only probably at initialization time. Anyway, thanks again.
___
*[`multibody/fem/fem_solver.h` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92wkaeBIBpG7HcVelu:-N974hHn7-WHcGQtHdqQ:bdh7eut) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L39)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I have a hard time picturing any other use cases for this scratch pad other than the specific use outlined in this PR. I tried replacing b and dz with the proposed names and I'm not crazy about how they look at the call site (i.e. SolveWithInitialGuess()).
</blockquote></details>

I see, if the use is limited to the solver, which now I realize it is, then my suggestion is not a good one really. Thanks for the explanation.
___
*[`multibody/fem/fem_solver.h` line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92xA7_2J4jC3HDJsk4:-N975EUuCWCIXLmtLuts:b-m30w6i) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L96)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I have a hard time parsing what you meant by this comment after reading it closely a few times. Could you try paraphrasing it?

FWIW, I do plan to place this scratch in a cache entry in the context.
</blockquote></details>

nvm, I was thinking of the scratch as being used by the model. This is only used by the solver. I like this, thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review on Thursday per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N977v9n3uzt_hM_YZOR:bcrghdh)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/fem/fem_solver.h` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17706#-N92w9PFAVO-DiaXW7Hr:-N977ffnEdV9tcapQlRs:b2fi2dr) ([raw file](https://github.com/robotlocomotion/drake/blob/f08a10c7847eb4fca555e3b66c5ce16c5eef493e/multibody/fem/fem_solver.h#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I see... that makes sense. I guess cache entries do need value semantics, and in cases like this we accomplish that with the expensive clone under the hood. The nice thing is that (I believe) we don't use the value semantics of cache entries at simulation time, only probably at initialization time. Anyway, thanks again.
</blockquote></details>

Yes I believe that's the case too.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17706#-:-N9C-U-8A5Z8fugtjVUW:bhm0jc2)* status: 1 unresolved discussion (waiting on @amcastro-tri)

**Pull request merged**
