### PR TITLE
[workspace] Upgrade petsc to latest release v3.17.4

### LINKED ISSUE #17908: petsc needs update to latest
petsc needs to be updated to the latest release. Our patches need to be rebased (or possibly checked and dropped, if appropriate).

It might not hurt to update `petscconf.h` either.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #17908.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17953)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) 
+@mwoehlke-kitware for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17953#-:-NCN5VosElo4gMF2eIRM:b-frp5vv)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Comment by xuchenhan-tri** [comment]
-(release notes: none) +(release notes: fix)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17953#-:-NCQJOVWCBtl1b-fgiCR:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for on-deck platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17953#-:-NCQKqx82XmOdOY8oRSF:bu9hss6)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17953#-:-NCQYFbMCJYahjbj3Oi2:b-vtj4vo)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @mwoehlke-kitware)

**Pull request merged**
