### PR TITLE
Clean up and deprecation of SceneGraphInspector/QueryObject bindings

### LINKED ISSUE #14258: geometry_py bindings for SceneGraphInspector variables names don't match c++ variable names
we have a lot of instances of e.g. bindings of the form
```
GetFrameId(geometry_id=)
```
when the c++ is 
```
GetFrameId(id=)
```
Might require some annoying deprecation gymnastics.  :-(  marked as low priority.

cc @EricCousineau-TRI , @mpetersen94

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
As per issue 14258, we want all public APIs that take Identifiers as parameters to have names representing their id type (source_id and not simply id). This handles what is termed "Category 3" APIs in that issue. This includes deprecations of some APIs that have been renamed and some deprecations on only the bindings.

resolves #14258

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280#-:-ML92Pt27vxpG9Kq4AbM:b7kye1q)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with some nits - sweet!

> Reviewed 10 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280#-:-ML9ExBjAahyeZL5jSdm:btmzpft)* status: 8 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 466 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9CuwE7pkFPZmsOwlV:-ML9CuwE7pkFPZmsOwlW:b998yn9) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/geometry_py.cc#L466)):*
nit I believe this date should be `2021-03-01`, given that we have passed Nov. 1st.

> Absent any other particular need, we prefer to use a deprecation period of three months by default, often rounded up to the next first of the month. So for code announced as deprecated on 2018-01-22 the removal_date would nominally be set to 2018-05-01.

https://drake.mit.edu/code_review_checklist.html#is-the-code-the-minimal-set-of-what-you-want
https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html#a847d827d084f28e4ae1788a0ae75be96
___
*[bindings/pydrake/test/geometry_test.py, line 91 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9DYQO08ErvDoQMNjl:-ML9DYQO08ErvDoQMNjm:b-sheoco) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L91)):*
> ```Python
>         self.assertEqual(len(inspector.GetCollisionCandidates()), 0)
>         self.assertTrue(inspector.SourceIsRegistered(source_id=global_source))
>         # TODO(SeanCurtis-TRI) Remove this call at the sme time as deprecating
> ```

nit spelling "sme" => "same"
___
*[bindings/pydrake/test/geometry_test.py, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9Dc2Q82oDV8Jj3NG6:-ML9Dc2Q82oDV8Jj3NG7:b-mzd85a) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L692)):*
> ```Python
>             **{"geometry_id_A": mut.GeometryId.get_new_id(),
>                "geometry_id_B": mut.GeometryId.get_new_id()})
>         # TODO(SeanCurtis-TRI) Remove this call at the sme time as deprecating
> ```

nit sme spelling error as above ;)
___
*[bindings/pydrake/test/geometry_test.py, line 697 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9Dg2B2XrpMSvZ_s9Y:-ML9Dg2B2XrpMSvZ_s9Z:bof9a9) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L697)):*
> ```Python
>         self.assertRaisesRegex(
>             RuntimeError,
>             "The geometry given by id \\d+ does not reference a geometry"
> ```

nit Using double-escaped characters may be less robust than using raw-string literals:

See preamble in `re`'s docs:
https://docs.python.org/3/library/re.html#re.search
___
*[bindings/pydrake/test/geometry_test.py, line 704 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9E9oT3I9eEs4hKyjn:-ML9E9oU75S_5yhGenL9:bj3c12p) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L704)):*
> ```Python
>             self.assertRaisesRegex(
>                 RuntimeError,
>                 "The geometry given by id \\d+ does not reference a geometry"
> ```

nit Same as above.
___
*[bindings/pydrake/test/geometry_test.py, line 707 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9EEVTCxtjgkuTqDJS:-ML9EEVTCxtjgkuTqDJT:bc7d69j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L707)):*
> ```Python
>                 + " that can be used in a signed distance query",
>                 query_object.ComputeSignedDistancePairClosestPoints,
>                 **{"id_A": mut.GeometryId.get_new_id(),
> ```

BTW `**<literal>` smells too "cute".

I would suggest either (a) defining `kwargs = {"id_A": ...}` or (b) using them in-place `my_func(..., id_A=...)`
___
*[geometry/query_object.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9EgWu9z7j-TuHxM5L:-ML9EgWu9z7j-TuHxM5M:b-fcuua2) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/geometry/query_object.h#L127)):*
> ```objc
> 
>   /** Deprecated variant of GetPoseInParent().  */
>   DRAKE_DEPRECATED("2021-02-01", "Please use GetPoseInParent(FrameId) instead.")
> ```

nit Same as above, this date should be `2021-03-01`
___
*[geometry/query_object.h, line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9EpqZ0uH1ZhE3trFd:-ML9EpqZ0uH1ZhE3trFe:b-fcuua2) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/geometry/query_object.h#L136)):*
> ```objc
> 
>   /** Deprecated variant of GetPoseInWorld(GeometryId).  */
>   DRAKE_DEPRECATED("2021-02-01",
> ```

nit Same as above, this date should be `2021-03-01`
___
*[geometry/scene_graph_inspector.h, line 178 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9EtN51Vu_-Y5PZl-k:-ML9EtN51Vu_-Y5PZl-l:b-fcuua2) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/geometry/scene_graph_inspector.h#L178)):*
> ```objc
>   /** Reports the name for the source with the given `id`.
>    @throws std::logic_error if `id` does not map to a registered source. */
>   DRAKE_DEPRECATED("2021-02-01", "Please use GetName(SourceId) instead.")
> ```

nit Same as above, this date should be `2021-03-01`

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed.

+@rpoyner-tri for platform review, on Tuesday, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280#-:-MLAF3aJ6HoFKc_eAg15:br3cd60)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/geometry_py.cc, line 466 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9CuwE7pkFPZmsOwlV:-MLACXdp4FGJfS4e7xki:b-cq2066) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/geometry_py.cc#L466)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I believe this date should be `2021-03-01`, given that we have passed Nov. 1st.

> Absent any other particular need, we prefer to use a deprecation period of three months by default, often rounded up to the next first of the month. So for code announced as deprecated on 2018-01-22 the removal_date would nominally be set to 2018-05-01.

https://drake.mit.edu/code_review_checklist.html#is-the-code-the-minimal-set-of-what-you-want
https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html#a847d827d084f28e4ae1788a0ae75be96
</blockquote></details>

Done (I knew the guideline and conscientiously did the math...and was just wrong.)
___
*[bindings/pydrake/test/geometry_test.py, line 91 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9DYQO08ErvDoQMNjl:-MLACgUpBbtXPZcJCtkp:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L91)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit spelling "sme" => "same"
</blockquote></details>

Done
___
*[bindings/pydrake/test/geometry_test.py, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9Dc2Q82oDV8Jj3NG6:-MLAChAf2TCS6Shcsmpl:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L692)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit sme spelling error as above ;)
</blockquote></details>

Done
___
*[bindings/pydrake/test/geometry_test.py, line 697 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9Dg2B2XrpMSvZ_s9Y:-MLADGWr8BCXovYY-Qgp:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L697)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Using double-escaped characters may be less robust than using raw-string literals:

See preamble in `re`'s docs:
https://docs.python.org/3/library/re.html#re.search
</blockquote></details>

Done
___
*[bindings/pydrake/test/geometry_test.py, line 704 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9E9oT3I9eEs4hKyjn:-MLADHIq3kWxV1YjGimx:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L704)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above.
</blockquote></details>

Done
___
*[bindings/pydrake/test/geometry_test.py, line 707 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14280#-ML9EEVTCxtjgkuTqDJS:-MLAEOMa67YcHcyHlyKi:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f014ffa58ad57f3bba646d510c45a93bb9182dc5/bindings/pydrake/test/geometry_test.py#L707)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW `**<literal>` smells too "cute".

I would suggest either (a) defining `kwargs = {"id_A": ...}` or (b) using them in-place `my_func(..., id_A=...)`
</blockquote></details>

Done

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: test coverage question

> Reviewed 7 of 12 files at r1, 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280#-:-MLEisVBCpYjV7fzTXRb:b-q9rjy9)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[geometry/query_object.cc, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14280#-MLEiWQEABj3hGI3zFJK:-MLEiWQEABj3hGI3zFJL:b-n6jgzm) ([raw file](https://github.com/robotlocomotion/drake/blob/a8222c3c2b10aa567869e97f53e9feb6cbf4654d/geometry/query_object.cc#L73)):*
> ```cpp
>   ThrowIfNotCallable();
> 
>   FullPoseUpdate();
> ```

Should it worry me that unit tests fail to reach most of the actual implementations in this file? The majority appear to fail `ThrowIfNotCallable`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[geometry/query_object.cc, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14280#-MLEiWQEABj3hGI3zFJK:-MLEkseG4oR_S-i70Z3U:b9b73lv) ([raw file](https://github.com/robotlocomotion/drake/blob/a8222c3c2b10aa567869e97f53e9feb6cbf4654d/geometry/query_object.cc#L73)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should it worry me that unit tests fail to reach most of the actual implementations in this file? The majority appear to fail `ThrowIfNotCallable`.
</blockquote></details>

I can see why you'd be worried. But what is untested here is a very slight sliver. Essentially, the class is some glue to magically acquired `SceneGraph` and `Context`. All of the queries that get called are forwarded to other code that is already tested. What is tested is the glue semantics.

What *isn't* tested is that each invocation of `QueryObject::Foo` properly calls the correct function on `GeometryState` passing all arguments. However, that would be such a *huge* bug that it would quickly reveal itself and the cost of actually configuring and executing tests that would reveal the appropriate mapping would be a lot of code with a very small point.

So, as it is, we're making sure that each of these boiler-plate wrappers apear to have the right boiler plate and calling it good.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14280)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

___
*[geometry/query_object.cc, line 73 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14280#-MLEiWQEABj3hGI3zFJK:-MLElkth8_t1fE-6WQNt:bb7ohn6) ([raw file](https://github.com/robotlocomotion/drake/blob/a8222c3c2b10aa567869e97f53e9feb6cbf4654d/geometry/query_object.cc#L73)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I can see why you'd be worried. But what is untested here is a very slight sliver. Essentially, the class is some glue to magically acquired `SceneGraph` and `Context`. All of the queries that get called are forwarded to other code that is already tested. What is tested is the glue semantics.

What *isn't* tested is that each invocation of `QueryObject::Foo` properly calls the correct function on `GeometryState` passing all arguments. However, that would be such a *huge* bug that it would quickly reveal itself and the cost of actually configuring and executing tests that would reveal the appropriate mapping would be a lot of code with a very small point.

So, as it is, we're making sure that each of these boiler-plate wrappers apear to have the right boiler plate and calling it good.
</blockquote></details>

sgtm

**Comment by jwnimmer-tri** [comment]
This needs an Anzu patch to remove the deprecation warnings.

**Comment by EricCousineau-TRI** [comment]
Aye, filing now.

**Pull request merged**
