### PR TITLE
Cleaned up a couple LCM messages.

### PR DESCRIPTION
**Pull request by liangfok**
Removed extraneous lines and trailing white spaces.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
I have no idea why travis-ci isn't rebuilding when asked to retest.

**Comment by billhoffman** [comment]
FYI, The retest please stuff only works for jenkins and not travis-ci.

**Pull request merged**
