### PR TITLE
code style doc: remove one needless use of sudo.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4205)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@liangfok for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4205#-:-KX860ojVv_WgRQhdg6P:b-m6pkmk)*

**Comment by sherm1** [comment]
+@sherm1 in case you need a platform review: :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4205#-:-KX86bvMlx5yixxNo3cy:b-x9zm70)*

**Comment by rpoyner-tri** [comment]
thanks @sherm1! :)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4205#-:-KX86xxL87aA_GX_v-o1:b-bq0zko)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4205#-:-KX87cMP4P52vTQ52zYG:bnfp4nl)*

**Pull request merged**
