### PR TITLE
Add IPOPT build diagnostics, and a kill switch.

### PR DESCRIPTION
**Pull request by david-german-tri**
@naveenoid for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5477)

### CODE REVIEW

**Comment by naveenoid** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/BUILD, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-Kf8dP10GTzjeBgx3vHa:-Kf8dP10GTzjeBgx3vHb:by42iw6) ([raw file](https://github.com/robotlocomotion/drake/blob/e2bd331b7e9846ba7dfaec68fe8c8db9f3fb73ca/tools/BUILD#L184)):*
> ```Python
> # The IPOPT build is fragile, so we provide a hidden switch to shut it off for
> # developers who don't actually need it.  This is not a supported configuration.
> # Use at your own risk: --define=NO_IPOPT=ON
> ```

BTW: if this isnt a permanent supported configuration, perhaps you want to note how long it will stay active? i.e. until some issue is resolved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-:-Kf8dJ5bWYhsEDG8sBdC:bg7igkv)*

**Comment by david-german-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/BUILD, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-Kf8dP10GTzjeBgx3vHa:-Kf8e6a0RC2Ulk8sB1Dh:b-fuvzck) ([raw file](https://github.com/robotlocomotion/drake/blob/e2bd331b7e9846ba7dfaec68fe8c8db9f3fb73ca/tools/BUILD#L184)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: if this isnt a permanent supported configuration, perhaps you want to note how long it will stay active? i.e. until some issue is resolved?
</blockquote></details>

By "not supported", I just mean that we don't test it in CI.  I think that usage is pretty common across drake documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5477)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/BUILD, line 503 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCOs5tsHIS2NnWnsp8:-KfCOs5tsHIS2NnWnsp9:bk2bd4a) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/drake/solvers/BUILD#L503)):*
> ```Python
>     "snopt_solver.h",
>     "no_snopt.cc",
> ])
> ```

I think the `ipopt-related` sources are missing from here?

---

*[tools/ipopt.BUILD, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCPCwe9xuYpmqrPRR5:-KfCPCwe9xuYpmqrPRR6:b-o9ov7a) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/tools/ipopt.BUILD#L103)):*
> ```
> HALF_THE_CORES = "$$[($$(getconf _NPROCESSORS_ONLN)+1)/2]"
> 
> LOG = " 2>> /tmp/ipopt.log"
> ```

I'm not sure that genrules should be using `tmp` without at least salting the filename they are using?

I also think a simple pathless `ipopt.log` would work, since it will not be affected by cdexec?

---

*[tools/ipopt.BUILD, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCPSYMMd3p109E7YSl:-KfCPSYMMd3p109E7YSm:b-lf049n) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/tools/ipopt.BUILD#L109)):*
> ```
>     " && " + CDEXEC + " make -j " + HALF_THE_CORES + LOG +
>     " && " + CDEXEC + " make install" + LOG +
>     ") || (echo \"***IPOPT Build Output***\" && cat /tmp/ipopt.log && false)"
> ```

FYI Should we also dump the `config.log` in case the configure step failed (which we've seen somewhat often)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-:-KfCPZc0eOUYLbjYBbl2:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/BUILD, line 503 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCOs5tsHIS2NnWnsp8:-KfCyj5h8HkPxlUgcUUB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/drake/solvers/BUILD#L503)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the `ipopt-related` sources are missing from here?
</blockquote></details>

Done.

---

*[tools/ipopt.BUILD, line 103 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCPCwe9xuYpmqrPRR5:-KfCyuqfC_0Lv6lFkQQi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/tools/ipopt.BUILD#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure that genrules should be using `tmp` without at least salting the filename they are using?

I also think a simple pathless `ipopt.log` would work, since it will not be affected by cdexec?
</blockquote></details>

Done.

---

*[tools/ipopt.BUILD, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5477#-KfCPSYMMd3p109E7YSl:-KfD4BLCusCHyKJRSuoq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4a9cf18c784b1f82dcd909f9647a0944a98c5877/tools/ipopt.BUILD#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Should we also dump the `config.log` in case the configure step failed (which we've seen somewhat often)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5477)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5477)*

**Pull request merged**
