### PR TITLE
primitives: do not declare state variables in AffineSystem if num_states==0

### PR DESCRIPTION
**Pull request by RussTedrake**
I ran into a case where I couldn't linearize a discrete-time system that also had an LQR controller in the diagram (because there were multiple state groups), even though the LQR controller should have been stateless.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@avalenzu for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003#-:-MZsYjzI21RTfEdfdrr1:b-fcohnv)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
Feature :lgtm:. +@rpoyner-tri for platform review.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003#-:-MZsaLyj8mDMjJH3gYGh:bkuwljl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15003#-MZsbqXN5K8bqTXWkSR6:-MZsbqXOB6HO_MshNLjx:b-5zee88) (no related file):*
Numerous test failures.

---

**Review by RussTedrake — COMMENTED** [review]
(i'm looking into the test failure now)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003#-:-MZskZSO5llc7pDdIb4x:bmqsz89)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
should be fixed. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003#-:-MZszVqe1dyOEB58OtjS:b-6gxeof)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @avalenzu)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15003#-:-MZt6Lr59H3ik5E97URG:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu (waiting on @RussTedrake)

**Pull request merged**
