### PR TITLE
symbolic: Change #warning to #error

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai for feature-review, please.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

The error on CI seems real.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGHBcBv9jLKKeXiOtDU:b8nglcq)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape, needs platform reviewer assigned (waiting on @hongkai-dai and @jamiesnape)

___
*[tools/skylark/pybind.bzl, line 352 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14003#-MGHXLAVAb3T4D-2uab_:-MGHXLAVAb3T4D-2uaba:bpwt2jl) ([raw file](https://github.com/robotlocomotion/drake/blob/b889ae83023ce25e4661d3f08466b7bbd214474c/tools/skylark/pybind.bzl#L352)):*
> ```Starlark
> 
>     args = ctx.actions.args()
>     args.add("-DDRAKE_COMMON_SYMBOLIC_DETAIL_HEADER")
> ```

+@jamiesnape , could you check this line? I wonder if you have a better solution. 

Without this line, we have:

```
Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-dbg/bin/tools/install/libdrake/_virtual_includes/drake_headers/drake/common/symbolic_formula_cell.h:11:2: error: Do not include this file unless you implement symbolic libraries.
Traceback (most recent call last):
  File "/home/soonhokong/.cache/bazel/_bazel_soonhokong/3bc20a1de94737f9ba65be6eaf973da0/sandbox/linux-sandbox/12/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 841, in <module>
    main()
  File "/home/soonhokong/.cache/bazel/_bazel_soonhokong/3bc20a1de94737f9ba65be6eaf973da0/sandbox/linux-sandbox/12/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 805, in main
    severities.count(cindex.Diagnostic.Fatal)))
RuntimeError: Parsing headers using the clang library failed with 1 error(s) and 0 fatal error(s)
----------------
```

**Review by soonho-tri — COMMENTED** [review]
OK. CI is happy.

+@sammy-tri for platform-review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGIoWK9-15SSX9fQ6NJ:b88i9ha)* status: 1 unresolved discussion, LGTM missing from assignees jamiesnape,sammy-tri(platform) (waiting on @hongkai-dai, @jamiesnape, and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Holding final platform review for remaining open issue.

> Reviewed 17 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGJFmo85BWSfYZfZueo:bigqw1v)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),jamiesnape (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),jamiesnape (waiting on @soonho-tri)

___
*[tools/skylark/pybind.bzl, line 352 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14003#-MGHXLAVAb3T4D-2uab_:-MGi45_D9Y4EJHoBoNHF:b-gd5tpr) ([raw file](https://github.com/robotlocomotion/drake/blob/b889ae83023ce25e4661d3f08466b7bbd214474c/tools/skylark/pybind.bzl#L352)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

+@jamiesnape , could you check this line? I wonder if you have a better solution. 

Without this line, we have:

```
Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-dbg/bin/tools/install/libdrake/_virtual_includes/drake_headers/drake/common/symbolic_formula_cell.h:11:2: error: Do not include this file unless you implement symbolic libraries.
Traceback (most recent call last):
  File "/home/soonhokong/.cache/bazel/_bazel_soonhokong/3bc20a1de94737f9ba65be6eaf973da0/sandbox/linux-sandbox/12/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 841, in <module>
    main()
  File "/home/soonhokong/.cache/bazel/_bazel_soonhokong/3bc20a1de94737f9ba65be6eaf973da0/sandbox/linux-sandbox/12/execroot/drake/bazel-out/host/bin/tools/workspace/pybind11/mkdoc.runfiles/drake/tools/workspace/pybind11/mkdoc.py", line 805, in main
    severities.count(cindex.Diagnostic.Fatal)))
RuntimeError: Parsing headers using the clang library failed with 1 error(s) and 0 fatal error(s)
----------------
```
</blockquote></details>

There is an issue with `_collect_cc_header_info` in that it is including headers that appear in `srcs` (and possibly also textual headers). There are several more fields in `CompilationContext` that may help us fix the problem, but it is by no means a simple solution. I think this is fine for now and we create an issue (for me) to fix the root issue (reference the issue in a TODO here).

**Comment by jwnimmer-tri** [comment]
@soonho-tri Check https://drake.mit.edu/styleguide/cppguide.html#Self_contained_Headers.

Should these file should be named `*.inc` instead of `*.h`?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),jamiesnape (waiting on @soonho-tri)

___
*[tools/skylark/pybind.bzl, line 352 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14003#-MGHXLAVAb3T4D-2uab_:-MGiCQ75-HeCh5ldGoAG:b-bagidm) ([raw file](https://github.com/robotlocomotion/drake/blob/b889ae83023ce25e4661d3f08466b7bbd214474c/tools/skylark/pybind.bzl#L352)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

SGTM. Can you open an issue for this? I'll update this PR by adding a TODO mentioning it then.
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/14034. The fix is a little easier if the files to exclude have a specific extension.

**Review by soonho-tri — COMMENTED** [review]
@sammy-tri , I think this is ready for platform-review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGiF4J6CO2wYFpNDfSk:b-sk9ucx)* status: LGTM missing from assignees sammy-tri(platform),jamiesnape (waiting on @hongkai-dai and @sammy-tri)

___
*[tools/skylark/pybind.bzl, line 352 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14003#-MGHXLAVAb3T4D-2uab_:-MGiF1Oo1m_Ze3zlEgqU:b-7nq0ue) ([raw file](https://github.com/robotlocomotion/drake/blob/b889ae83023ce25e4661d3f08466b7bbd214474c/tools/skylark/pybind.bzl#L352)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/drake/issues/14034. The fix is a little easier if the files to exclude have a specific extension.
</blockquote></details>

Done (TODO added).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGihSn15soivDj7svJc:bnfp4nl)* status: LGTM missing from assignee jamiesnape

**Review by soonho-tri — COMMENTED** [review]
-@jamiesnape 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14003#-:-MGiiFeICvkaPgB-6Skf:b121o5n)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),hongkai-dai

**Pull request merged**
