### PR TITLE
Enable Wunused-parameter on all code except tests

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6051)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot  linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.bzl, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-KjcEp2KOxV64EQ1bC6J:-KjcEp2LcsIvHE_wqWb4:bcxmnpl) ([raw file](https://github.com/robotlocomotion/drake/blob/019550af8c43a0909e40dca3783de6e9c05706de/tools/drake.bzl#L23)):*
> ```Python
> ]
> 
> GCC_CC_TEST_FLAGS = [
> ```

Consistent with the flag lists above, an explanatory comment would be helpful.

---

*[tools/drake.bzl, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-KjcF3isv0y30Sjy5Mbd:-KjcF3isv0y30Sjy5Mbe:b-hl5i9c) ([raw file](https://github.com/robotlocomotion/drake/blob/019550af8c43a0909e40dca3783de6e9c05706de/tools/drake.bzl#L27)):*
> ```Python
> ]
> 
> def _platform_copts(rule_copts, cc_test=0):
> ```

The new parameter is undocumented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6051)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6051)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.bzl, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-KjcEp2KOxV64EQ1bC6J:-KjcGDPnsnKVlN4ALqEQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/019550af8c43a0909e40dca3783de6e9c05706de/tools/drake.bzl#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Consistent with the flag lists above, an explanatory comment would be helpful.
</blockquote></details>

Done.

---

*[tools/drake.bzl, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-KjcF3isv0y30Sjy5Mbd:-KjcGEf4vvuS8yeykoal:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/019550af8c43a0909e40dca3783de6e9c05706de/tools/drake.bzl#L27)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The new parameter is undocumented.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6051)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-:-KjcGKfXQnEqcrIhi0Dp:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6051#-:-KjcYsNIFtkyZmk5J6Xp:bnfp4nl)*

**Pull request merged**
