### PR TITLE
Add instructions on how to set up Mosek

### LINKED ISSUE #6612: Add instructions on how to set up Mosek
Add to http://drake.mit.edu/bazel.html#proprietary-solvers.

 - Save a license file at ~/mosek/mosek.lic.
 - To test it:
   - For CMake, run `ninja solvers/test/mosek_solver_test && solvers/test/mosek_solver_test`.
   - For Bazel, run `bazel test //drake/solvers:mosek_solver_test --config=mosek --test_tag_filters=mosek`.

/cc @FischerGundlach

### PR DESCRIPTION
**Pull request by soonho-tri**
Closes #6612.

screen shot 2017-07-20 at 11 45 14 pm

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6623)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@fischergundlach , feature-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-KpYFkwmkysbF8oHi1HC:b-f1wmp5)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-KpYJJ8MLEYQPDDHhw1c:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@seancurtis-tri , platform-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-Kp_J6kLrvR9vBYmkaH0:b-bgt2kp)*

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-Kp_LeD6JVWpFPGzwv7b:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@sherm1 for final platform review

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-Kp_g3Gf3tKI8xzyY0dd:bm3q4u)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6623#-:-KpaL1xSdFpgbGsMMKJw:bnfp4nl)*

**Pull request merged**
