### PR TITLE
symbolic_py: Bind and test symbolic::Variables

### PR DESCRIPTION
**Pull request by soonho-tri**
Part of #8098

Note that the first commit is to run clang-format over `symbolic_py.cc` file.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8124)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with one discussion point on test placement. Thanks!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5tz2wz-SbYoUZ25QWr:-L5tz2wz-SbYoUZ25QWs:bq77n1e) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/symbolic_py.cc#L235)):*
> ```cpp
>       .def("IsStrictSupersetOf", &Variables::IsStrictSupersetOf)
>       .def(py::self == py::self)
>       .def(py::self < py::self)
> ```

BTW Fancy! Did not know about that!

Can you add a TODO for me at the top of this file to use `py::self` for operator overloads?

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0HQraR1PXgmVDsRo:-L5u0HQsMRBju3lkDH1F:b-5nksp6) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L15)):*
> ```Python
> 
> 
> class TestSymbolicVariables(unittest.TestCase):
> ```

Would it be possible for you to add these tests to the `symbolic_variable_test` or `symbolic_test`?

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0VGM3fy91FN5w4Ln:-L5u0VGM3fy91FN5w4Lo:b-xepenm) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L19)):*
> ```Python
>         vars = sym.Variables()
>         self.assertEqual(vars.size(), 0)
>         self.assertEqual(vars.empty(), True)
> ```

BTW You can use` self.assertTrue`.

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0h5iq8JizFHOwT5S:-L5u0h5iq8JizFHOwT5T:b-jlnz2z) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L96)):*
> ```Python
>         vars1 = sym.Variables([x, y])
>         vars2 = sym.Variables([y, z])
>         vars3 = vars1 - vars2  # [x]
> ```

BTW Why not just check `self.assetEqual(vars4, [x])`? I believe it may implicitly cast; if not, just construct Variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-:-L5u0uFvOu-0YBEpbAmJ:b-wx6y1l)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u1-eIQjMBuSsjo1e1:-L5u1-eIQjMBuSsjo1e2:b2u3dll) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/BUILD.bazel#L233)):*
> ```Python
> )
> 
> # TODO(soonho-tri): Split the tests in this file into separate files.
> ```

BTW I'd actually prefer the opposite - it'd be nice if these could be compacted, and minimized (since some of the tests overlap with C++, and don't test anything too Python-specific).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8124)*

**Comment by soonho-tri** [comment]
+@ggould-tri for platform-review, please.

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u1-eIQjMBuSsjo1e1:-L5uAAHZjVRFbwtMElIE:bbt0aat) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/BUILD.bazel#L233)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I'd actually prefer the opposite - it'd be nice if these could be compacted, and minimized (since some of the tests overlap with C++, and don't test anything too Python-specific).
</blockquote></details>

Done.

I removed the TODOs. I'll do the merging after closing #8098 if you think that's fine.

---

*[bindings/pydrake/symbolic_py.cc, line 235 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5tz2wz-SbYoUZ25QWr:-L5uANyP8c0orq8Zav5i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/symbolic_py.cc#L235)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Fancy! Did not know about that!

Can you add a TODO for me at the top of this file to use `py::self` for operator overloads?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0HQraR1PXgmVDsRo:-L5uAPL-5sbhCU7o_0hD:b-oq2j1o) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L15)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be possible for you to add these tests to the `symbolic_variable_test` or `symbolic_test`?
</blockquote></details>

I'll do the merging later.

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0VGM3fy91FN5w4Ln:-L5uAVmyR41ehN-RNzFG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L19)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW You can use` self.assertTrue`.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/symbolic_variables_test.py, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u0h5iq8JizFHOwT5S:-L5uEzDAl-g2e12HEyrZ:bm8cnid) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/test/symbolic_variables_test.py#L96)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Why not just check `self.assetEqual(vars4, [x])`? I believe it may implicitly cast; if not, just construct Variables?
</blockquote></details>

Well.. `self.assetEqual(vars4, [x])` doesn't work so I added the explicit version of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-:-L5uHLhqcQGlW2jJFTTO:b-qfhg9t)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-L5u1-eIQjMBuSsjo1e1:-L5uY3s80Wge1CmvPTPa:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/9548380044428eb955aeca5df2f0caf0ec722d86/bindings/pydrake/BUILD.bazel#L233)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.

I removed the TODOs. I'll do the merging after closing #8098 if you think that's fine.
</blockquote></details>

OK Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8124)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8124#-:-L5y6xljX5jy3KcUn_-A:bnfp4nl)*

**Pull request merged**
