### PR TITLE
[framework] Update scalar conversion test utility

### PR DESCRIPTION
**Pull request by rpoyner-tri**
As of Xcode 16 or so, it is no longer safe to blithely dynamic_cast a system to a type that it has statically forbidden conversion support for. Instead, check (statically) for conversion support, and only then step through the dynamic conversion test steps. Give a nice error message if the conversion is forbidden statically.

While here, revert an obsolete compiler workaround, and fold the implementation code down from two copies to one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
Closes: #22176 .

+@jwnimmer-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-:-OBhHYstEDzoViM3Ur1e:b-6inbpe)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-:-OBhQoi_5G2zahNFRfgl:b-n37teh)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/framework/test_utilities/scalar_conversion.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBhQYdp7zt4x4nLVykX:-OBhQYdp7zt4x4nLVykY:b-krodc2) ([raw file](https://github.com/RobotLocomotion/drake/blob/66324b487c2ec3864619568e7e53a29c44efc869/systems/framework/test_utilities/scalar_conversion.h#L47)):*
> ```objc
>     return ::testing::AssertionFailure() << fmt::format(
>                "scalar conversion from 'double' to '{}' statically forbidden "
>                "for "
> ```

nit Weird line wrapping (line break) for this string literal.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBhHv-xEyPdks0qEjUM:-OBhzBjZ8CtYPIXGvtME:b-su8f32) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.
</blockquote></details>

Close. Everything built, and several python tests failed. Good enough to declare this patch to be progress.
___
*[`systems/framework/test_utilities/scalar_conversion.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBhQYdp7zt4x4nLVykX:-OBhzVh-1aQXNEaF5T0A:b-v0r8ya) ([raw file](https://github.com/RobotLocomotion/drake/blob/66324b487c2ec3864619568e7e53a29c44efc869/systems/framework/test_utilities/scalar_conversion.h#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Weird line wrapping (line break) for this string literal.
</blockquote></details>

courtesy of M-x clang-format-region. will touch up.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Close. Everything built, and several python tests failed. Good enough to declare this patch to be progress.
</blockquote></details>

@drake-jenkins-bot mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for platform review, Monday schedule.

For context, this is just one step in the long march to build and test clean for the first time with Xcode 16.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-:-OBi0-uSCmE2siojRCZ9:bhj6ajr)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

**Comment by jwnimmer-tri** [comment]
On second thought, let's do +@sherm1 as a subject-relevant platform reviewer, please (removing -@sammy-tri).  Also I'm going to dump tons of PRs on Sam on Monday, so this will help load-balance.

**Review by rpoyner-tri — COMMENTED** [review]
:heavy_check_mark: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-:-OBl1obcCbnatWs7d_xx:bevsic7)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 3 unresolved discussions

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBhHv-xEyPdks0qEjUM:-OBmRKWz4EUCNrCBGZtJ:b-42q2q8) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-sequoia-unprovisioned-clang-bazel-experimental-release please.
</blockquote></details>

Platform :lgtm: pending one added comment
___
*[`systems/framework/test_utilities/scalar_conversion.h` line 27 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBmR2hY4zYGCm6iseUa:-OBmR2hY4zYGCm6iseUb:btt9j5l) ([raw file](https://github.com/RobotLocomotion/drake/blob/150a65b819a642df755588e5bcecf545a076033a/systems/framework/test_utilities/scalar_conversion.h#L27)):*
> ```objc
> namespace internal {
> template <typename ToScalar, template <typename> class S, typename Callback>
> ::testing::AssertionResult is_convertible_to(
> ```

minor: this function needs a comment. Something like one of the ones below would be enough, I think
___
*[`systems/framework/test_utilities/scalar_conversion.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBmQq3z4NlFPt2Ez57U:-OBmQq3z4NlFPt2Ez57V:b-dwp695) ([raw file](https://github.com/RobotLocomotion/drake/blob/150a65b819a642df755588e5bcecf545a076033a/systems/framework/test_utilities/scalar_conversion.h#L59)):*
> ```objc
> /// can be passed via a lambda into @p callback.  The Callback must take an
> /// `const S<AutoDiffXd>&` and return void; a typical value would be a lambda
> /// such as `[](const auto& converted) { EXPECT_TRUE(converted.thing()); }`.
> ```

BTW this comment (or something like it) could be moved up to `is_convertible_to()`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 2 unresolved discussions

___
*[`systems/framework/test_utilities/scalar_conversion.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBmQq3z4NlFPt2Ez57U:-OBmUeQlCCxlTfc9yHmA:b-2h8yl8) ([raw file](https://github.com/RobotLocomotion/drake/blob/150a65b819a642df755588e5bcecf545a076033a/systems/framework/test_utilities/scalar_conversion.h#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this comment (or something like it) could be moved up to `is_convertible_to()`
</blockquote></details>

I don't agree.  This is the public API, which is the correct place to write down the contract.  The `is_convertible_to` function is an implementation detail, which our users (test developers) should never need to read.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 2 unresolved discussions

___
*[`systems/framework/test_utilities/scalar_conversion.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBmQq3z4NlFPt2Ez57U:-OBm_dNQ8swGrYi5w2yd:b-i72l26) ([raw file](https://github.com/RobotLocomotion/drake/blob/150a65b819a642df755588e5bcecf545a076033a/systems/framework/test_utilities/scalar_conversion.h#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't agree.  This is the public API, which is the correct place to write down the contract.  The `is_convertible_to` function is an implementation detail, which our users (test developers) should never need to read.
</blockquote></details>

The internal function is now where all the complicated stuff gets done. I agree the public APIs should have comments, but the internal function's contract is by no means straightforward to discern, unless you first read the public API comments and infer what the private must be doing. I don't think that's the right way to document it. As a reviewer of the code (as opposed to an API user) I encountered the internal function first and didn't understand it -- a `//` comment there would help.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 2 unresolved discussions

___
*[`systems/framework/test_utilities/scalar_conversion.h` line 59 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22188#-OBmQq3z4NlFPt2Ez57U:-OBmbt-BDs7JYcUCwvDw:bui73k8) ([raw file](https://github.com/RobotLocomotion/drake/blob/150a65b819a642df755588e5bcecf545a076033a/systems/framework/test_utilities/scalar_conversion.h#L59)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The internal function is now where all the complicated stuff gets done. I agree the public APIs should have comments, but the internal function's contract is by no means straightforward to discern, unless you first read the public API comments and infer what the private must be doing. I don't think that's the right way to document it. As a reviewer of the code (as opposed to an API user) I encountered the internal function first and didn't understand it -- a `//` comment there would help.
</blockquote></details>

Yes.  Your other discussion up above was okay, and is still open.  I only objected to the suggestion here to **move** this documentation.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22188)* status: 1 unresolved discussion

**Comment by rpoyner-tri** [comment]
-(release notes: fix) +(release notes: none)

**Pull request merged**
