### PR TITLE
Fix Wunused-parameter in solvers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5988)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please (platform review with domain expertise).

/CC @hongkai-dai @EricCousineau-TRI FYI

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5988#-:-Kj4Boytv7-XA1uMdpBO:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5988)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5988#-:-Kj4YTVCk3S8T2SpIzkA:bnfp4nl)*

**Pull request merged**
