### PR TITLE
Add python binding for SceneGraph::RegisterGeometry with context

### PR DESCRIPTION
**Pull request by allenzren**
cc @SeanCurtis-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17342)

### CODE REVIEW

**Comment by allenzren** [comment]
@EricCousineau-TRI for both reviews please, Thanks!

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot ok to test

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ericcousineau-tri +(status: single reviewer ok) +(release notes: yes) 
(keywords for reviewable)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17342#-:-N3usf2LDZfwHsHs828e:bk3eh5l)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17342#-:-N3utK5q7v4Bbs9whJz_:b4xzgsb)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @allenzren)

___
*[`bindings/pydrake/geometry_py_scene_graph.cc` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17342#-N3usxEtCUas7PEMluyH:-N3usxEtCUas7PEMluyI:b-dwpiur) ([raw file](https://github.com/robotlocomotion/drake/blob/6d54d3c0645991602c3c0c3e60a59e160a3129af/bindings/pydrake/geometry_py_scene_graph.cc#L204)):*
> ```cpp
>             py::arg("source_id"), py::arg("geometry_id"), py::arg("geometry"),
>             cls_doc.RegisterGeometry.doc_3args_source_id_geometry_id_geometry)
>         .def("RegisterGeometry",
> ```

BTW I think this might fail lint. However, the fix for it should be part of the error message.

**Comment by allenzren** [comment]
*[`bindings/pydrake/geometry_py_scene_graph.cc` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17342#-N3usxEtCUas7PEMluyH:-N3vDXBo4wcZVvyBLYsr:b-ybw447) ([raw file](https://github.com/robotlocomotion/drake/blob/6d54d3c0645991602c3c0c3e60a59e160a3129af/bindings/pydrake/geometry_py_scene_graph.cc#L204)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I think this might fail lint. However, the fix for it should be part of the error message.
</blockquote></details>

Fixed now.

**Review by allenzren — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17342#-:-N3zuNX67JQgbGshhAHS:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
