### PR TITLE
Add a dual arm iiwa simulation

### PR DESCRIPTION
**Pull request by sammy-tri**
A lot of the net number of lines changed are in the duplication of the director configuration files.  I'm not thrilled about this, but I think the end-to-end manual interaction is interesting enough to be worth it.  I'll pull that commit out of the PR if the reviewers disagree.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5996)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review  (I'll stop bombarding you with reviews soon, but this seemed like it might be relevant to your interests)

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-Kj4mQyiNbazYmDi_5VE:b-eeynwr)*

**Comment by naveenoid** [comment]
super happy to review :)  Just one documentation request and thats it.

---

Reviewed 19 of 23 files at r1, 3 of 3 files at r2.
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_fp_dual.csv, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjA1aBxn7E-o0_elCk7:-KjA1aBySOhR2ml6VZ2M:b8bzkvk) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/kuka_iiwa_fp_dual.csv#L1)):*
> ```CSV
> 0.000000000000000000e+00
> ```

BTW: is there anyway a comment can be left in this file as to its purpose (and not parsed)? I understand from parsing the code but the name doesnt indicate much and neither does a column of numbers.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjA3RoY6vQ0ewNA0L0Z:-KjA3RoY6vQ0ewNA0L0_:b-f81ujh) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L57)):*
> ```cpp
>   // TODO(sam.creasey) This implementation doesn't know how to
>   // calculate velocities/accelerations for differing numbers of
>   // positions and velocities.
> ```

I think this comment can instead be replaced by a class doxy comment of this form : 
"Note that this class assumes the robot is fully actuated, its position and velocity have the same dimension, it does not have a floating base. If violated, the program will abort."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-Kj5_3rCj6LjdaxdzV4f:bhw6tj1)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review (feature review still not totally done but I think the remaining issues are small enough to not affect platform review)

---

Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_iiwa_fp_dual.csv, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjA1aBxn7E-o0_elCk7:-KjDv40VMyKbjSxtt93N:br5vjyq) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/kuka_iiwa_fp_dual.csv#L1)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: is there anyway a comment can be left in this file as to its purpose (and not parsed)? I understand from parsing the code but the name doesnt indicate much and neither does a column of numbers.
</blockquote></details>

I tried it and it seemed to work with how director is parsing this file...   though looking for more information on comments and .csv's I'm not sure I want to wander into it: https://github.com/RobotLocomotion/drake/pull/6009

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjA3RoY6vQ0ewNA0L0Z:-KjDwLDSq6Jp6EJHMICx:bb6e3ko) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L57)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I think this comment can instead be replaced by a class doxy comment of this form : 
"Note that this class assumes the robot is fully actuated, its position and velocity have the same dimension, it does not have a floating base. If violated, the program will abort."
</blockquote></details>

I don't think there's a requirement on being fully actuated or having a fixed base...   fully actuated would be a requirement of the controller which is consuming the output positions/velocities/accelerations, and a floating base is fine as long as the position/velocity are both specified with euler angles.  I can still move the TODO on the sizes being equal to a class comment if you prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-KjDxNI0gR-Ylk2h8h8O:b-al41d5)*

**Comment by ggould-tri** [comment]
Very minor nits below.  :lgtm:

---

Reviewed 20 of 23 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 89 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjE7IVreKb73U45_4zs:-KjE7IVsVmFLE-t3tNrH:b-v6ud1m) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L89)):*
> ```cpp
>     iiwa_kd.conservativeResize(end);
>     iiwa_kd.segment(offset, kIiwaArmNumJoints) =
>         iiwa_kd.head(kIiwaArmNumJoints);
> ```

FYI this is rule-of-three but I can't see any way to factor it so I'll assume there is no defect.

---

*[drake/examples/kuka_iiwa_arm/stored_poses_dual.json, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjE8U3MzoYagBpxVmKX:-KjE8U3MzoYagBpxVmKY:b-1arvqk) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/stored_poses_dual.json#L14)):*
> ```JSON
>         "left_iiwa_joint_6": 0.5635,
>         "left_iiwa_joint_7": 0.0,
> 	"right_iiwa_joint_1": 0.0,
> ```

FYI indentation.

---

*[drake/examples/kuka_iiwa_arm/stored_poses_dual.json, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjE8WtKtjpeeA0NnIh2:-KjE8WtKtjpeeA0NnIh3:b-1arvqk) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/stored_poses_dual.json#L37)):*
> ```JSON
>         "left_iiwa_joint_6": 0.0,
>         "left_iiwa_joint_7": 0.0,
> 	"right_iiwa_joint_1": 0.0,
> ```

FYI indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-KjE8oNoW55uqafkru95:b-lwl68x)*

**Comment by sammy-tri** [comment]
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/stored_poses_dual.json, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjE8U3MzoYagBpxVmKX:-KjEAX5IfkmWHIvHS21W:b-hh434m) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/stored_poses_dual.json#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI indentation.
</blockquote></details>

woah, a literal tab crept in.  fixed.

---

*[drake/examples/kuka_iiwa_arm/stored_poses_dual.json, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjE8WtKtjpeeA0NnIh2:-KjEA_VkunIiivG0NhLt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/stored_poses_dual.json#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI indentation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-KjA3RoY6vQ0ewNA0L0Z:-KjEEOZgBruSGEc5NwIP:bjs9gxq) ([raw file](https://github.com/robotlocomotion/drake/blob/ea20f2216c5899b11cab5fb7678630230629b5ec/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L57)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think there's a requirement on being fully actuated or having a fixed base...   fully actuated would be a requirement of the controller which is consuming the output positions/velocities/accelerations, and a floating base is fine as long as the position/velocity are both specified with euler angles.  I can still move the TODO on the sizes being equal to a class comment if you prefer.
</blockquote></details>

Lets cross that bridge later when we look to make apply this to generic manipulators.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-KjEEYE1gSARrPwypZfo:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot   linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5996#-:-KjEYtBEHyMG58DS9ruP:b-vpmm0d)*

**Pull request merged**
