### PR TITLE
fix unitialized state in test.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6640)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@m-chaturvedi +@jwnimmer-tri for reviews. thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6640#-:-KppBNSBoJ2G4AkZamO8:b2x8eot)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by jwnimmer-tri** [comment]
+(priority: emergency) :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/frame_visualizer_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6640#-KppCayVzINB0d1sG3kd:-KppCayWSMfyNxoe7iPO:brrjllm) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c8b7af89784d01ea3be7d093d09acec4f0cb43/drake/multibody/rigid_body_plant/test/frame_visualizer_test.cc#L56)):*
> ```cpp
>   KinematicsCache<double> cache = tree.CreateKinematicsCache();
>   auto q = x.head(tree.get_num_positions());
>   auto v = x.head(tree.get_num_velocities());
> ```

FYI Its weird to use `head` for both q and v, but I guess its all zeros anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6640#-:-KppCNcMXlEMxP0mWwOr:bxahb14)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6640#-:-KppEGZMyolQetWc7zUC:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6640)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source please
[ Re-running because it looks like a flake ]

**Pull request merged**
