### PR TITLE
[doc] Add release notes v1.18.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for both reviews per schedule, please.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-:-NY-4gDv3im6e_72-W02:bfrghqa)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_pages/from_binary.md` line 36 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-NY-4b-nAVjA3wocZL5G:-NY-4b-nAVjA3wocZL5H:bn7m9my) ([raw file](https://github.com/RobotLocomotion/drake/blob/938b1b4f5469d9a942258de57293225edcb2fe05/doc/_pages/from_binary.md#L36)):*
> ```Markdown
> [v1.18.0](https://github.com/RobotLocomotion/drake/releases/tag/v1.18.0):
> 
> * [https://github.com/RobotLocomotion/drake/releases/download/v1.18.0/drake-20990601-focal.tar.gz](https://github.com/RobotLocomotion/drake/releases/download/v1.18.0/drake-20990601-focal.tar.gz)
> ```

Working

Adjust for actual date.
___
*[`doc/_release-notes/v1.18.0.md` line 4 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-NY-46Xv-sDLF_ztj2mq:-NY-46Xv-sDLF_ztj2mr:bn7m9my) ([raw file](https://github.com/RobotLocomotion/drake/blob/49263059b3d63e45551c26996184a86d121670ed/doc/_release-notes/v1.18.0.md#L4)):*
> ```Markdown
> title: Drake v1.18.0
> date: 2099-06-01
> released: 2099-06-01
> ```

Working

Adjust for actual date.
___
*[`doc/_release-notes/v1.18.0.md` line 188 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-NY-4AWh5edOwCDjRAnL:-NY-4AWh5edOwCDjRAnM:bn7m9my) ([raw file](https://github.com/RobotLocomotion/drake/blob/49263059b3d63e45551c26996184a86d121670ed/doc/_release-notes/v1.18.0.md#L188)):*
> ```Markdown
> 
> This release provides [pre-compiled binaries](https://github.com/RobotLocomotion/drake/releases/tag/v1.18.0) named
> ``drake-YYYYMMDD-{focal|jammy|mac|mac-arm64}.tar.gz``. See [Stable Releases](/from_binary.html#stable-releases) for instructions on how to use them.
> ```

Working

Adjust for actual date.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-:-NY-riah4oQds8bXqGJd:b4xzh7c)* status: 4 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`doc/_release-notes/v1.18.0.md` line 42 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19534#-NY-ptvq4yr1DYFgKYkt:-NY-ptvq4yr1DYFgKYku:bsqa8a1) ([raw file](https://github.com/RobotLocomotion/drake/blob/938b1b4f5469d9a942258de57293225edcb2fe05/doc/_release-notes/v1.18.0.md#L42)):*
> ```Markdown
> New features
> 
> * Add binary operator overloads for Polynomial bop Expression ([#19457][_#19457])
> ```

nit `bop` isn't immediately understandable.

Consider replacing with `Polynomial binary operation Expression`?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534)* status: 3 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534)* status: 3 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19534)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
