### PR TITLE
Add CsdpSolver. Currently it can solve positive semidefinite program without free variables.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is the first PR to support CSDP as an external solver in Drake. This PR allows we call CSDP if there is no free variables in `MathematicalProgram`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11489)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-address-sanitizer please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-address-sanitizer please

**Comment by jamiesnape** [comment]
Might be quicker (for me) to solve #11501 rather than add further workarounds. I will check now.

**Comment by jamiesnape** [comment]
We should be free of the BLAS bundled with SNOPT now. Not sure how this PR is going to proceed, but some variation of rebasing on master, fixing the conflicts and running Everything and SNOPT Fortran builds without any workarounds for the previous BLAS problem would be good.

**Comment by hongkai-dai** [comment]
I restructured the dev branch. I will close this PR and file new PRs instead.

**Pull request closed without merging**
