### PR TITLE
Add ParseQuadraticConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8198)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-:-L6OnSU33-R5bgVaONYC:bvhsv4m)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with some minor comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/create_constraint.cc, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzwsWuO1Px8gpuhFH:-L6XzwsXnAjXsQR2wdJJ:barz7an) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.cc#L372)):*
> ```cpp
> Binding<QuadraticConstraint> ParseQuadraticConstraint(
>     const symbolic::Expression& e, double lower_bound, double upper_bound) {
>   // First build an Eigen vector, that contains all the bound variables.
> ```

BTW grammar Extra ","

---

*[solvers/create_constraint.cc, line 377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XztTToY3-0d52osSi:-L6XztTUDYkwqFJmDgM2:b375p71) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.cc#L377)):*
> ```cpp
>   const auto& map_var_to_index = p.second;
> 
>   // Now decomposes the expression into coefficients and monomials.
> ```

BTW grammar "Now decompose the ..." (should use imperative here, which is fine for non-doxygen descriptions)

---

*[solvers/create_constraint.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzDHFFQ3ZUuWAJyD_:-L6XzDHFFQ3ZUuWAJyDa:bmcq210) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.h#L205)):*
> ```objc
> 
> /**
>  * Assist MathematicalProgram::AddConstraint(...) to create a quadratic
> ```

BTW grammar Can you use non-imperative, "Assist**s** MathematicalProgram..."?

---

*[solvers/test/create_constraint_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzXlfe9dUJUvtRh_N:-L6XzXlfe9dUJUvtRh_O:b-xk1hw3) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L14)):*
> ```cpp
> namespace solvers {
> namespace {
> void CheckParseQuadraticConstraint(const Expression& e, double lb, double ub) {
> ```

BTW Can you add a newline here (before func def)?

---

*[solvers/test/create_constraint_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6Y-LHAFatU6xd0Jcd0:-L6Y-LHAFatU6xd0Jcd1:by1xf4s) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L45)):*
> ```cpp
> class ParseQuadraticConstraintTest : public ::testing::Test {
>  public:
>   ParseQuadraticConstraintTest() : x0_{"x0"}, x1_{"x1"}, x2_{"x2"}, x3_{"x3"} {
> ```

BTW You could initialize these below in the declarations, like
`symbolic::Variable x0_{"x0"};`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-:-L6Y-YssfWDKrfsAog-r:b-xln5uw)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[solvers/create_constraint.cc, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzwsWuO1Px8gpuhFH:-L6crJyILCW7ekeKTYPV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.cc#L372)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW grammar Extra ","
</blockquote></details>

Done.

---

*[solvers/create_constraint.cc, line 377 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XztTToY3-0d52osSi:-L6crM-O1JBJ3tIqIH5e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.cc#L377)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW grammar "Now decompose the ..." (should use imperative here, which is fine for non-doxygen descriptions)
</blockquote></details>

Done.

---

*[solvers/create_constraint.h, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzDHFFQ3ZUuWAJyD_:-L6crRn-1XPh0H4mx29J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/create_constraint.h#L205)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW grammar Can you use non-imperative, "Assist**s** MathematicalProgram..."?
</blockquote></details>

Done.

---

*[solvers/test/create_constraint_test.cc, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6XzXlfe9dUJUvtRh_N:-L6crWpFINW25-hekf52:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you add a newline here (before func def)?
</blockquote></details>

Done.

---

*[solvers/test/create_constraint_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6Y-LHAFatU6xd0Jcd0:-L6crgmOT-zv3cDg-xBj:b-yem07d) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW You could initialize these below in the declarations, like
`symbolic::Variable x0_{"x0"};`
</blockquote></details>

`x0_` is a member of `ParseQuadraticConstraintTest` class, I think I should call the constructor of `symbolic::Variable x0_`, in the initializer list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-:-L6cs_OLRjYFCmRQn4LL:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm: with a few BTWs.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/create_constraint.cc, line 383 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6czreMUdYgkA59aC2c:-L6czreNvgag2vCEvnqp:brzwlsq) ([raw file](https://github.com/robotlocomotion/drake/blob/ae8274fd9a7f842c02ee48ffcc703df5e5523d1c/solvers/create_constraint.cc#L383)):*
> ```cpp
>   Eigen::VectorXd b(vars_vec.size());
>   double constant_term;
>   DecomposeQuadraticPolynomial(poly, map_var_to_index, &Q, &b, &constant_term);
> ```

BTW although I'm sure this seems obvious to you, it would have helped me here to have a comment like `// Write polynomial as bᵀQb+k.`

---

*[solvers/create_constraint.cc, line 385 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6d-G_g6w6csfUKZ1ID:-L6d-G_g6w6csfUKZ1IE:b-jgu3w) ([raw file](https://github.com/robotlocomotion/drake/blob/ae8274fd9a7f842c02ee48ffcc703df5e5523d1c/solvers/create_constraint.cc#L385)):*
> ```cpp
>   DecomposeQuadraticPolynomial(poly, map_var_to_index, &Q, &b, &constant_term);
>   return CreateBinding(
>       make_shared<QuadraticConstraint>(Q, b, lower_bound - constant_term,
> ```

BTW and here: `// Constraint is lb <= bᵀQb+k <= ub.`

---

*[solvers/test/create_constraint_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6Y-LHAFatU6xd0Jcd0:-L6d3876el8vMVK40Fag:bxtzuw4) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L45)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`x0_` is a member of `ParseQuadraticConstraintTest` class, I think I should call the constructor of `symbolic::Variable x0_`, in the initializer list?
</blockquote></details>

BTW I agree with @ericcousineau-tri -- nicer to put the initializers on the data members when you can. Then you don't need an initializer list here, just the setting of x.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-:-L6d3QdCDI03r8kAszkX:bv2dux7)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/create_constraint.cc, line 383 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6czreMUdYgkA59aC2c:-L6d67rtmW7QKqJ-I2cg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae8274fd9a7f842c02ee48ffcc703df5e5523d1c/solvers/create_constraint.cc#L383)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW although I'm sure this seems obvious to you, it would have helped me here to have a comment like `// Write polynomial as bᵀQb+k.`
</blockquote></details>

Done.

---

*[solvers/create_constraint.cc, line 385 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6d-G_g6w6csfUKZ1ID:-L6d69j3NyWHSLLJHUT3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ae8274fd9a7f842c02ee48ffcc703df5e5523d1c/solvers/create_constraint.cc#L385)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW and here: `// Constraint is lb <= bᵀQb+k <= ub.`
</blockquote></details>

Done.

---

*[solvers/test/create_constraint_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6Y-LHAFatU6xd0Jcd0:-L6d6ATcU582qQOSbEoX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ab71008a0058c3397a01c238ac57b27740ae7ff/solvers/test/create_constraint_test.cc#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I agree with @ericcousineau-tri -- nicer to put the initializers on the data members when you can. Then you don't need an initializer list here, just the setting of x.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198)*

**Comment by sherm1** [comment]
A couple of new BTWs ...

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/create_constraint.cc, line 383 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6dJQXiXOe8hIQxMMzF:-L6dJQXiXOe8hIQxMMzG:bgs24p0) ([raw file](https://github.com/robotlocomotion/drake/blob/2f187529a491237feee4a10e765c1851113e9e2b/solvers/create_constraint.cc#L383)):*
> ```cpp
>   Eigen::VectorXd b(vars_vec.size());
>   double constant_term;
>   // Decompose the polynoimial 0.5xᵀQx + bᵀx + k.
> ```

BTW typo

---

*[solvers/test/create_constraint_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6dJe96QWJW1k6OqYRK:-L6dJe96QWJW1k6OqYRL:b-lg8rtu) ([raw file](https://github.com/robotlocomotion/drake/blob/2f187529a491237feee4a10e765c1851113e9e2b/solvers/test/create_constraint_test.cc#L53)):*
> ```cpp
> 
>  protected:
>   symbolic::Variable x0_;
> ```

BTW per f2f -- initializers go here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-:-L6dJjuImsInluiyR0zr:b-j7ey53)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/create_constraint.cc, line 383 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6dJQXiXOe8hIQxMMzF:-L6dK52ARLlLhM_n935M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f187529a491237feee4a10e765c1851113e9e2b/solvers/create_constraint.cc#L383)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW typo
</blockquote></details>

Done.

---

*[solvers/test/create_constraint_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8198#-L6dJe96QWJW1k6OqYRK:-L6dK663ZmK1T4Ngm_ba:bmwpa8w) ([raw file](https://github.com/robotlocomotion/drake/blob/2f187529a491237feee4a10e765c1851113e9e2b/solvers/test/create_constraint_test.cc#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f -- initializers go here.
</blockquote></details>

Done. Sorry I misunderstood the comment in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8198)*

**Pull request merged**
