### PR TITLE
Solution summary for MathematicalProgram

### LINKED ISSUE #3817: `SolutionResult` should also contain the optimal cost
Currently to get the optimal cost (objective) of an optimization problem, I will need to loop through all costs, and evaluate each costs at the optimal solution. On the other hand, in most solvers (actually all solvers I know), we can get the optimal solution directly from the solver. I suggest to modify the `SolutionResult`, which is the return argument of `MathematicalProgram::Solve()` function, such that this is no longer an enum in its current form

```
enum SolutionResult {
    kSolutionFound = 0,
    kInvalidInput = -1,
    kInfeasibleConstraints = -2,
    kUnknownError = -3,
  };
```

But instead, it looks like

```
struct SolutionResult {
  enum status {
    kSolutionFound = 0,
    kInvalidInput = -1,
    kInfeasibleConstraints = -2,
    kUnknownError = -3,
  }
  double objective_value;
}
```

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Introduce a new base class `MathematicalProgramSolutionResult`, as the return type for `MathematicalProgram::Solve`. Each solver can derive its own class of result.
2. Use a non-virtual interface in `MathematicalProgramSolverInterface`.

resolves #3817

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4545)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri  for feature review.

---

Review status: 0 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-:-KZNxm9BcRos_x1xYOYA:b-bsdnga)*

**Comment by jwnimmer-tri** [comment]
Be sure to disable copy and assignment on `MathematicalProgramSolverResult`.  The PR doesn't seem to do that yet.

**Comment by sammy-tri** [comment]
left some initial comments, still a lot to review

---

Reviewed 11 of 43 files at r1, 1 of 3 files at r2.
Review status: 12 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program_solver_interface.h, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-KZO96HYo4M56CPz9Fv8:-KZO96HYo4M56CPz9Fv9:b-95a4nf) ([raw file](https://github.com/robotlocomotion/drake/blob/b8da049dd6fac474f1d82f00146a5b784395ceb5/drake/solvers/mathematical_program_solver_interface.h#L70)):*
> ```objc
> 
>  protected:
>   virtual bool available_impl() const = 0;
> ```

BTW, I'm curious why we moved to having impl() functions which are virtual being called from non-virtual wrapper functions.

---

*[drake/solvers/moby_lcp_solver.h, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-KZO9djopj_U-YNiGZ37:-KZO9djopj_U-YNiGZ38:bi4173i) ([raw file](https://github.com/robotlocomotion/drake/blob/b8da049dd6fac474f1d82f00146a5b784395ceb5/drake/solvers/moby_lcp_solver.h#L17)):*
> ```objc
> namespace solvers {
> 
> class MobyLCPSolverResult : public MathematicalProgramSolverResult {
> ```

Why create a derived class with no new members/functionality instead of just returning an instance of the base class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-:-KZOAbjtiiraVIlgCxD-:b-4zteit)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 43 files at r1, 1 of 3 files at r3.
Review status: 14 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4545)*

**Comment by hongkai-dai** [comment]
Review status: 14 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program_solver_interface.h, line 70 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-KZO96HYo4M56CPz9Fv8:-KZOAo05JeAqc66x7jnh:bppatz8) ([raw file](https://github.com/robotlocomotion/drake/blob/b8da049dd6fac474f1d82f00146a5b784395ceb5/drake/solvers/mathematical_program_solver_interface.h#L70)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW, I'm curious why we moved to having impl() functions which are virtual being called from non-virtual wrapper functions.
</blockquote></details>

per discussion with @sherm1 , we decide to use non-virtual interface

---

*[drake/solvers/moby_lcp_solver.h, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4545#-KZO9djopj_U-YNiGZ37:-KZOAxVI2AVruHvffBE2:b-1lmiy1) ([raw file](https://github.com/robotlocomotion/drake/blob/b8da049dd6fac474f1d82f00146a5b784395ceb5/drake/solvers/moby_lcp_solver.h#L17)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Why create a derived class with no new members/functionality instead of just returning an instance of the base class?
</blockquote></details>

As a place holder. I should add a TODO here, that we should add more contents to this class, such as the constraint values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4545)*

**Comment by hongkai-dai** [comment]
Closing this PR. I want to re-structure the whole `MathematicalProgramSolverInterface` instead. Will write a design doc.

**Pull request closed without merging**
