### PR TITLE
Add smarts to the bazel wrapper to help gdb compatibility

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This detects if it is appropriate to force clang to make gdb-friendly
symbols available for debugging.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@jwnimmer-tri for feature review, please. (Particularly flag anything I did that was not particularly pythonic.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBXkyhXCNkv3lkq0nRw:bbobfja)*

**Comment by SeanCurtis-TRI** [comment]
-@jwnimmer-tri +@jamiesnape for feature review (unless you can think of someone better)

Question: I have a version of this where I don't do the "Detect-the-compiler" logic at all, relying on compilers to ignore macros that it doesn't care about. It simplifies this code and (empirically) works. Is it dangerous to run with that -- what happens if some compiler uses the macro for some other purpose?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBXoRLV04HKomuj2aBZ:b-vs6h56)*

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBaSLVtA4U3Llsg4lUo:b-j9ui69)*

**Comment by SeanCurtis-TRI** [comment]
ping @jamiesnape for feature lgtm...

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBflMOD1rJ5Q7q6Kfpp:brxzix)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/clion/bazel_wrapper, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8747#-LBflbmi5_6HpKILQjCH:-LBflbmjA5geIBdHASA6:b5k6gtz) ([raw file](https://github.com/robotlocomotion/drake/blob/76ae9151535286a9afadcb6f7ad3bb6c02cb7525/tools/clion/bazel_wrapper#L19)):*
> ```
>     to compile gdb-friendly STL symbols. Modifies the args in place.'''
>     # Inject the macro regardless of compiler, relying on non-clang compilers
>     # to simply ignore it.
> ```

BTW Technically it is not ignored, you just see the same end result for this particular issue with GCC regardless. I would just say in the docstring that you are injected the flag in debug builds the benefit of non-GCC compilers to compile GDB friendly STL symbols.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBfmes6E84d0cJ787rc:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/clion/bazel_wrapper, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8747#-LBfmkX3C8R48jS6bEUC:-LBfmkX3C8R48jS6bEUD:b-3vfixf) ([raw file](https://github.com/robotlocomotion/drake/blob/76ae9151535286a9afadcb6f7ad3bb6c02cb7525/tools/clion/bazel_wrapper#L7)):*
> ```
> import subprocess
> import sys
> import warnings
> ```

BTW Is this used anywhere?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747)*

**Comment by SeanCurtis-TRI** [comment]
+@sherm1 for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/clion/bazel_wrapper, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8747#-LBfmkX3C8R48jS6bEUC:-LBfro394nXqDW3rTj8j:bqvuv49) ([raw file](https://github.com/robotlocomotion/drake/blob/76ae9151535286a9afadcb6f7ad3bb6c02cb7525/tools/clion/bazel_wrapper#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Is this used anywhere?
</blockquote></details>

OK Oops. Forgot to cut it.

---

*[tools/clion/bazel_wrapper, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8747#-LBflbmi5_6HpKILQjCH:-LBfsFuA6tgo_FD4nlGx:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/76ae9151535286a9afadcb6f7ad3bb6c02cb7525/tools/clion/bazel_wrapper#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Technically it is not ignored, you just see the same end result for this particular issue with GCC regardless. I would just say in the docstring that you are injected the flag in debug builds the benefit of non-GCC compilers to compile GDB friendly STL symbols.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBfsNV47BGPAVZM51Pn:bppyoqq)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747)*

**Comment by sherm1** [comment]
Platform :lgtm_strong:. Can't wait to look at some strings!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBg32k7B2P430CVzla5:b-e7lsje)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8747#-:-LBgKcrNAlq5TA5fLvxS:b-l70wzf)*

**Pull request merged**
