### PR TITLE
[common] Remove filesystem shim

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For code whose primary purpose is file manipulation, we use the conventional `namespace fs` alias for brevity. For files where developers might not have seen that abbreviation yet, we stick with the `std::filesystem` spelled out in full.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18159)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-big-sur-clang-bazel-experimental-release please

**Review by ggould-tri — COMMENTED** [review]
:lgtm: both.  I agree with the `using` alias decision.

> Reviewed 60 of 60 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18159#-:-NF9Az-a7ebYTcBK3uZy:bxi42gu)* status: 5 unresolved discussions (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18159)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18159)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
