### PR TITLE
[fix] Speedup continuity test

### PR DESCRIPTION
**Pull request by wrangelvid**
Hotfix for #21480.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21494)

### CODE REVIEW

**Review by wrangelvid — COMMENTED** [review]
@drake-jenkins-bot](https://github.com/drake-jenkins-bot) linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21494#-:-Nz1GyhY5PddoQBRoYSB:bn8wmzb)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews pending CI.

**Comment by SeanCurtis-TRI** [comment]
The everything-asan test passed. The mac failure seems simply to be connectivity problems (unable to fetch repositories). Seems to me we can simply merge this.

**Pull request merged**
