### PR TITLE
Adds MaliputRailcar::DoCalcNextUpdateTime() That Does Not Consider Acceleration.

### PR DESCRIPTION
**Pull request by liangfok**
This applies the [KISS Principle](https://en.wikipedia.org/wiki/KISS_principle) to #5532.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5534)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@ggould-tri for platform review please.
+@jwnimmer-tri for car review please.

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-:-KfRh2i4qyOBhdVaUrep:b-8j094s)*

**Comment by jwnimmer-tri** [comment]
:car: approved

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-:-KfRic6L9_U_QZZmUyLA:b-wrjbb8)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-KfScXAHxXVYngdGq77E:-KfScXAIuH29TgTTovmn:b-51f4hc) ([raw file](https://github.com/robotlocomotion/drake/blob/c9676319af000af93558f8e78dbb57a7a17caf27/drake/automotive/maliput_railcar.cc#L299)):*
> ```cpp
> // following computes an estimate of when the vehicle will reach the end of
> // its lane. This estimate will be off when r != 0 and the lane is very
> // curvey because the scale factors used in Lane::EvalMotionDerivatives() will
> ```

BTW, spelling troll: s/curvey/curvy/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-:-KfSdPR2RDJlj4Nx3-S8:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-:-KfSqrONJTW3Mm1YjTkv:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks for all of the reviews. This PR should be ready to be merged once it passes CI.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput_railcar.cc, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-KfScXAHxXVYngdGq77E:-KfSvK2QYErkZqxujvUj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9676319af000af93558f8e78dbb57a7a17caf27/drake/automotive/maliput_railcar.cc#L299)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, spelling troll: s/curvey/curvy/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534#-:-KfSvL8Zjd8VzqfXiafr:b-4a5kr1)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5534)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.

**Pull request merged**
