### PR TITLE
Revert "Update eigen submodule SHA"

### PR DESCRIPTION
**Pull request by jadecastro**
Reverts RobotLocomotion/drake#4495

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4512)

### CODE REVIEW

**Comment by jadecastro** [comment]
@drake-jenkins-bot linux-gcc-continuous-matlab-documentation please

**Comment by jadecastro** [comment]
+@jwnimmer-tri for both review levels.

**Comment by jwnimmer-tri** [comment]
Per discussion #4514 will trump this so :lgtm_cancel: but please to post a link to a build of PR passing `runAtlasDynamics` so that we confirm it was the Eigen sha bump that broke the test.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4512#-:-KZ2Fm0jelPMi3jbgkhc:b1w0ikk)*

**Comment by jwnimmer-tri** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/1807/ confirms that this PR is a valid alternative fix vs #4514, so the Eigen bump is indeed at fault.  With the revert, the test goes back to passing in ~2m30s.

**Pull request closed without merging**
