### PR TITLE
Added a README to Acrobot/test. Updated README in Cars.

### PR DESCRIPTION
**Pull request by liangfok**
Mostly polishing changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2111)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2111#-:-KFQnc0SBFPuUqPpxv3W:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2111)*

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/Acrobot/test/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2111#-KFdvN-jpwVnm-dzs5n-:-KFdvN-jpwVnm-dzs5n0:603101849) ([raw file](https://github.com/robotlocomotion/drake/blob/d953dd0384106a665fb006a4f58caaf1ee39c683/drake/examples/Acrobot/test/README.md#L1)):*
this is fine, but a better readme would link to the textbook (http://underactuated.csail.mit.edu/underactuated.html?chapter=3) and include instructions for running the simulator + visualizer, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2111)*

**Comment by liangfok** [comment]
To reduce the clutter in the PR list, I will close this for now.

**Pull request closed without merging**
