### PR TITLE
Add a link to the hydroelastic blog post to the user guide

### PR DESCRIPTION
**Pull request by sherm1**
Per suggestion by Russ, adds a link to the Medium Hydroelastic blog post to the Hydroelastic User Guide.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@joemasterjohn for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875#-:-NBTSavd0McoFNgm5Aic:b-i3ejks)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: great idea! +@ericcousineau-tri for a nice easy platform review, please.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875#-:-NBTVW4WBq2pA38UqL-H:b-wxlwm0)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with small nit on Doxygen directive usage and consistency - great idea indeed!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875#-:-NBTe6sMEugwkDBu85kj:bh5d0fg)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17875#-NBTdhCIACzFf1jNpoaA:-NBTdhCIACzFf1jNpoaB:bu0e0fw) ([raw file](https://github.com/robotlocomotion/drake/blob/e91bd9791cc86067f062c7c94a76fd292161942d/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L22)):*
> ```objc
> contacts. Hydroelastic contact instead attempts to approximate the patch and
> pressure distribution to provide much richer and more realistic contact
> behavior. For a high-level overview, see [this blog post]
> ```

nit Introduction of anchor below without usage was slightly confusing.

Consider staying in line with usage of other anchors, e.g. "Masterjohn 2022". I think it'd look like this:
```
For a high-level overview, see @ref Sherman2022 "this blog post"
```

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @sherm1)

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17875#-NBTdhCIACzFf1jNpoaA:-NBTlA5G4UdPBKj64sfg:b-dwxq1s) ([raw file](https://github.com/robotlocomotion/drake/blob/e91bd9791cc86067f062c7c94a76fd292161942d/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Introduction of anchor below without usage was slightly confusing.

Consider staying in line with usage of other anchors, e.g. "Masterjohn 2022". I think it'd look like this:
```
For a high-level overview, see @ref Sherman2022 "this blog post"
```
</blockquote></details>

OK, that's what I tried first but then the link doesn't take the reader directly to the blog post which is what I wanted. Instead it takes the reader to the anchor point where they have to look at an extremely ugly URL and select that. I agree it is slightly weird to see the anchor there with no reference but on balance I thought it was better to be consistent in the ref section at the end.

**Review by sherm1 — COMMENTED** [review]
Eric, LMK if you disagree with my reasoning below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875#-:-NBTm2H51nm8hdlUEhR5:bqlk32l)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
Nope, no disagreement here!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17875#-:-NBTnjoO79ZTGtP0PRFj:b-2t27ab)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),joemasterjohn (waiting on @sherm1)

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17875#-NBTdhCIACzFf1jNpoaA:-NBTngLS14uMCbya64Na:b-ya0p8c) ([raw file](https://github.com/robotlocomotion/drake/blob/e91bd9791cc86067f062c7c94a76fd292161942d/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L22)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

OK, that's what I tried first but then the link doesn't take the reader directly to the blog post which is what I wanted. Instead it takes the reader to the anchor point where they have to look at an extremely ugly URL and select that. I agree it is slightly weird to see the anchor there with no reference but on balance I thought it was better to be consistent in the ref section at the end.
</blockquote></details>

Ah, OK, works for me!

**Pull request merged**
