### PR TITLE
Add Python binding for RigidBody.get_center_of_mass()

### PR DESCRIPTION
**Pull request by gizatt**
@EricCousineau-TRI (though I wouldn't be surprised if you already have this in a staged PR...)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7795)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Nope, hadn't yet!

+@ericcousineau-tri for feature review.
+@soonho-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7795#-:-L39WEzvszwvtAI4AmCA:b-49aw3a)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7795#-:-L39WSE17DyudR19B_Ht:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7795)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7795#-:-L39t9iDWf0WKmRzqb_5:bnfp4nl)*

**Pull request merged**
