### PR TITLE
Squash StateVector into VectorBase.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@jwnimmer-tri for both levels of review.  (Most of the diff is cut-and-paste, and most of the rest is clang-format.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3393)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Checkpoint of partial review.

Please confirm for me that a grep for `StateVector` is empty in the whole tree, and case-insensitive grep for `state_?vector` (or similar?) contains only appropriate mentions (e.g., the one in `state_subvector_test.cc`) in the whole tree.

---

Reviewed 14 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram_context.h, line 233 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-KRAE89MldyGxtKNf734:-KRAE89Nc5piA2YviFMU:b8y3lyf) ([raw file](https://github.com/robotlocomotion/drake/blob/69d72350a817ac2e896f0410d508933415053db3/drake/systems/framework/diagram_context.h#L233)):*
> ```objc
>     PortIndex port_index = id.second;
>     GetMutableSubsystemContext(system_index)
>         ->SetInputPort(port_index, std::move(port));
> ```

BTW Really, clang-format wants this?  Its a bit awful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAERnLzOVoJHv3js-N:bo64ok6)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/vector_base.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-KRAG59ZCr7m4A81TOpI:-KRAG59_nZRbC3Ps_VCT:bthtetx) ([raw file](https://github.com/robotlocomotion/drake/blob/69d72350a817ac2e896f0410d508933415053db3/drake/systems/framework/vector_base.h#L25)):*
> ```objc
> /// @tparam T Must be a Scalar compatible with Eigen.
> template <typename T>
> class VectorBase : public StateVector<T> {
> ```

Inheriting from a deleted file?  Whee!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393)*

**Comment by jwnimmer-tri** [comment]
:lgtm: given the obvious fix.

---

Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAGRq5WK7zwSjkG65H:b-dcoibx)*

**Comment by david-german-tri** [comment]
> Please confirm for me that a grep for StateVector is empty in the whole tree

Can't do that, since `StateVector` was a popular typedef in System1, but I did skim the list and decide all the remaining files appear System1-flavored.

> case-insensitive grep for state_?vector (or similar?) contains only appropriate mentions (e.g., the one in state_subvector_test.cc) in the whole tree

Done.

---

Review status: 13 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_base.h, line 25 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-KRAG59ZCr7m4A81TOpI:-KRAMNB0l9AkOqHx-egz:b-vs3hja) ([raw file](https://github.com/robotlocomotion/drake/blob/69d72350a817ac2e896f0410d508933415053db3/drake/systems/framework/vector_base.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Inheriting from a deleted file?  Whee!
</details>
Sigh.  `install` FTW.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRALvphRCKhZ5xkH_bv:bjclaw4)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

---

Review status: 13 of 20 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAOLLYzIBrfISSnFeJ:b-m1j5af)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: 13 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAUuL5IyPiYCUShpwb:bzdwe9o)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAd0OZWPWzihyiNQCE:bmripy1)*

**Comment by david-german-tri** [comment]
Jenkins is out to lunch, so I'm going to merge this without waiting for the ROS build.  I'll keep an eye on continuous.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3393#-:-KRAhWLEABJHmMvHws4-:b-jb4nma)*

**Pull request merged**
