### PR TITLE
Update Ubuntu 16.04 install script

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
* Check for CMake before installing (the CI scripts require a newer version of CMake than drake)
* Add missing packages

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3806)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
+@jamiesnape for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-:-KU3NeoG3hIr7bOgLsea:b9itq1i)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3OeNTa40pTTs0_b83:-KU3OeNTa40pTTs0_b84:b-y0yq2w) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L41)):*
> ```Shell
> done
> 
> # Check if CMake is already installed
> ```

Probably should say why we are checking.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3Olrw-yn6n3N8Sikq:-KU3Olrw-yn6n3N8Sikr:b-kmub3r) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L42)):*
> ```Shell
> 
> # Check if CMake is already installed
> if command -v cmake 2>/dev/null; then
> ```

Should we check the version? I guess it is unlikely someone would have lower than the version apt installs.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3P9mdaM3-Q94tgCd3:-KU3P9meYBnW7-NVID2E:brab213) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
> ```Shell
> default-jdk
> doxygen
> flex
> ```

We still need flex? For SWIG?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3P9mdaM3-Q94tgCd3:-KU3cVi-Sg8s5LW7rhdr:b-by6r2g) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> We still need flex? For SWIG?
</details>
It looks like the error was trying to build dReal --> https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=147116

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3P9mdaM3-Q94tgCd3:-KU3iT_ysaLNYCZO4ok_:b9uqppo) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary>
> It looks like the error was trying to build dReal --> https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=147116
</details>
Do you have a link to a clean build?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3P9mdaM3-Q94tgCd3:-KU3isaI1sYp9mDu9-AB:bps7b3i) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L58)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Do you have a link to a clean build?
</details>
With no errors? https://drake-cdash.csail.mit.edu/buildSummary.php?buildid=147228

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3OeNTa40pTTs0_b83:-KU4FvLBlDTfzdkLrmXQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L41)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Probably should say why we are checking.
</details>
Done.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KU3Olrw-yn6n3N8Sikq:-KU4Fvvz5ztr1hSD7THm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/486f60974419131f90656efa7ce2b7b9a921fb66/setup/ubuntu/16.04/install_prereqs.sh#L42)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Should we check the version? I guess it is unlikely someone would have lower than the version apt installs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by BetsyMcPhail** [comment]
@jamiesnape ready for another review please.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-:-KUXH_GYbHHouunNJZ0a:bkz3p0p)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-:-KUXJ_2mAeyn7oF7CmWO:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
+@sammy-tri  for platform review please

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-:-KUXK57w5lC5VMEr9yN8:b-zbgj4l)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KUXiwpjjPRkLQJXYyQ1:-KUXiwpjjPRkLQJXYyQ2:bj9gy2c) ([raw file](https://github.com/robotlocomotion/drake/blob/fd0a8b98ee2856c0743f9790091f1afe7b28fa88/setup/ubuntu/16.04/install_prereqs.sh#L47)):*
> ```Shell
>   cmake_version=$(cmake --version) &>/dev/null
>   cmake_version=${cmake_version:14:3}
>   if [[ $cmake_version > "3.5" || $cmake_version == "3.5" ]]; then
> ```

FYI This lexical compare scares me, but I guess it's not a problem until cmake 3.10 exists and sorts lower than 3.5 (I'm guessing at the bash sort rules from memory here).  I can't actually think of a better idea offhand unfortunately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-:-KUXjG-jEk2tzjt-55jE:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KUXiwpjjPRkLQJXYyQ1:-KUXjqQbCYqBJ_p7BH7N:b-ltncsj) ([raw file](https://github.com/robotlocomotion/drake/blob/fd0a8b98ee2856c0743f9790091f1afe7b28fa88/setup/ubuntu/16.04/install_prereqs.sh#L47)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> FYI This lexical compare scares me, but I guess it's not a problem until cmake 3.10 exists and sorts lower than 3.5 (I'm guessing at the bash sort rules from memory here).  I can't actually think of a better idea offhand unfortunately.
</details>
I guess you could do something with `sort -V` on the two version numbers and then see which is first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KUXiwpjjPRkLQJXYyQ1:-KUXkF1xk1klT464Gfrv:boabzhx) ([raw file](https://github.com/robotlocomotion/drake/blob/fd0a8b98ee2856c0743f9790091f1afe7b28fa88/setup/ubuntu/16.04/install_prereqs.sh#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I guess you could do something with `sort -V` on the two version numbers and then see which is first.
</details>
Though it is just major.minor so it would not make the expression two much longer to compare component-wise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KUXiwpjjPRkLQJXYyQ1:-KUXlK6Ydjm5Eo9mF8QY:b-ooqq1i) ([raw file](https://github.com/robotlocomotion/drake/blob/fd0a8b98ee2856c0743f9790091f1afe7b28fa88/setup/ubuntu/16.04/install_prereqs.sh#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Though it is just major.minor so it would not make the expression two much longer to compare component-wise.
</details>
I forgot, this is always Ubuntu:

`dpkg --compare-versions $cmake_version ge 3.5`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by BetsyMcPhail** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3806#-KUXiwpjjPRkLQJXYyQ1:-KUYiTRgtRxlQutzenk4:b-qfp7ij) ([raw file](https://github.com/robotlocomotion/drake/blob/fd0a8b98ee2856c0743f9790091f1afe7b28fa88/setup/ubuntu/16.04/install_prereqs.sh#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I forgot, this is always Ubuntu:
> 
> `dpkg --compare-versions $cmake_version ge 3.5`
</details>
Thanks for the suggestion @jamiesnape. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3806)*

**Pull request merged**
