### PR TITLE
Make the pick and place state machine implementation common between demos

### PR DESCRIPTION
**Pull request by sammy-tri**
Also moves the state machine out of dev.

I know this PR looks really massive, and it is.  The code in dev/ went in with nearly no review.  Platform reviewers may skip it entirely, in which case inspecting the non-dev/ files  (pick_and_place_state_machine and test)  as new is "only" a still inappropriate 600-ish lines.  

I think it's probably fine for the feature reviewer to go light on the dev/ stuff for now too.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6264)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ericcousineau-tri for feature review

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-Km24cBoYehJfQlnPCIt:by4pfea)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, aside from two very minor nit-picks.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km284joE8GNcKZ13fFi:-Km284joE8GNcKZ13fFj:b-3h7221) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b1a3c3bfd95fe89d38b25296cb486a15fa136d/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc#L165)):*
> ```cpp
> }
> 
>   // @return the state of the pick and place world.
> ```

nit Extra leading whitespace? Does this hidden dox comment belong elsewhere?

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km28PPJdFweR7NS42gp:-Km28PPLWNjhOyEGpBJs:b-hy2jc) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b1a3c3bfd95fe89d38b25296cb486a15fa136d/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.h#L41)):*
> ```objc
>       const Isometry3<double>& iiwa_base,
>       const std::vector<Isometry3<double>>& place_locations,
>       const double update_interval = 0.01);
> ```

BTW nit We use `update_interval` here, but we use `period_sec` or other names in the `lcm` systems and the simulator. 
Would it be possible for us to nail down common terminology so we don't have twenty different names for the same thing, like `dt`, `update_dt`, `period_sec`, `inv_freq`, `step_time`, etc.?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-Km2Rk_W9985ZCTteWLD:bige3ew)*

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review of the non-dev/ portions (I know you have limited availability, but I'm also out for the rest of the week after today, so no rush on this.  Also feel free to punt to the next reviewer if you need.)

---

Review status: 25 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km284joE8GNcKZ13fFi:-Km2_almlY7CcQGrznpb:b-n4v1xm) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b1a3c3bfd95fe89d38b25296cb486a15fa136d/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc#L165)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Extra leading whitespace? Does this hidden dox comment belong elsewhere?
</blockquote></details>

Seems to have been a cut and paste error...  The header already has a doxygen comment.  (removed the one here)

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km28PPJdFweR7NS42gp:-Km2a9Un_OHGCF2PAshe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b1a3c3bfd95fe89d38b25296cb486a15fa136d/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.h#L41)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW nit We use `update_interval` here, but we use `period_sec` or other names in the `lcm` systems and the simulator. 
Would it be possible for us to nail down common terminology so we don't have twenty different names for the same thing, like `dt`, `update_dt`, `period_sec`, `inv_freq`, `step_time`, etc.?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-Km2aNNdgzZyKlt4nORG:bwb31pc)*

**Comment by ggould-tri** [comment]
Yeah, this is going to be a little while before I get into it.  Small monitor and large packet loss are not the best for reviewable at all, much less for reviewable of a big thing.

---

Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-Km2dfG90kfbt1R6eT-2:b3w80qz)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 27 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7yOpeKMZATh5aQjFj:-Km7yOpfsgSKIHNmlluJ:bt67649) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L77)):*
> ```cpp
>         waypoints[i].pose.translation().transpose(),
>         math::rotmat2rpy(waypoints[i].pose.rotation()).transpose());
>     if (true || i != num_via_points) {
> ```

Um, what?  `true ||` needs at least a comment.  More likely it needs to go away.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7zjRKZEM72OXmPIjD:-Km7zjRKZEM72OXmPIjE:b-m64696) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.h#L23)):*
> ```objc
> 
> /// Different states for the pick and place task.
> enum PickAndPlaceState {
> ```

All the enum names below should be kConsts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264)*

**Comment by ggould-tri** [comment]
Checkpoint:  Part way through state machine; have to leave for JFT work.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km80iyAzwJix7irWgvk:-Km80iyBjJinv8vz4CTQ:b1iuytx) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L64)):*
> ```cpp
>   std::vector<
>     ConstraintRelaxingIk::IkCartesianWaypoint> waypoints(num_via_points + 1);
>   const double dt = duration / (num_via_points + 1);
> ```

I am somewhat confused by the sequence of times.  As I read it you area setting dt as if the time of waypoint 0 is not 0.  Is this intended?  If so, this is surprising and should be in the function comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-Km81ZlfnkYAK_qeN0kN:b-2m8drd)*

**Comment by ggould-tri** [comment]
Finished review.  :lgtm: pending (numerous but mostly small) comments below.

---

Reviewed 2 of 27 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmRzuIf7TtL9ApPsTVu:-KmRzuIghaP2l1LGbX3-:b-obxl9q) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L96)):*
> ```cpp
>       loop_(loop),
>       state_(OPEN_GRIPPER),
>       // Position and rotation tolerances.  These should be adjusted
> ```

"Should be adjusted" by whom, and when?  Is this a todo comment?  An instruction for users of the demo?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS-b73jTSjd2ImnZ7r:-KmS-b73jTSjd2ImnZ7s:btd0vl1) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L107)):*
> ```cpp
> PickAndPlaceStateMachine::~PickAndPlaceStateMachine() {}
> 
> void PickAndPlaceStateMachine::Update(
> ```

BTW -- This is an extremely long method, and might be clearer if you factored the individual cases into their own methods.  Those could then be unit tested at finer granularity than the current test.

Author's discretion.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS163k0jxcNGWQqk8m:-KmS163k0jxcNGWQqk8n:bwrf35v) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L24)):*
> ```cpp
> 
> struct TestStep {
>   int iiwa_expected;
> ```

This needs a comment, or a clearer name. What does it mean to expect an int value from an iiwa?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS1CG3mqjc7S2i8x-C:-KmS1CG3mqjc7S2i8x-D:bdarevo) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L25)):*
> ```cpp
> struct TestStep {
>   int iiwa_expected;
>   int wsg_expected;
> ```

This needs a comment, or a clearer name. What does it mean to expect an int value from a wsg?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS0qTS3HtlcSiu8hhM:-KmS0qTS3HtlcSiu8hhN:b9sux4x) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L29)):*
> ```cpp
> };
> 
> GTEST_TEST(PickAndPlaceStateMachineTest, StateMachineTest) {
> ```

You really need a function comment on this test explaining what it does and justifying the magic numbers below with some sort of narrative of the scene being created and acted out.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS0VFk71zCN27aIIm5:-KmS0VFk71zCN27aIIm6:b-hfun8h) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L141)):*
> ```cpp
>     world_state.HandleWsgStatus(wsg_msg);
> 
>     if (step.state_expected == APPROACH_PLACE_PREGRASP) {
> ```

This needs a comment -- it is not clear why you are fiddling with the `object_msg` in these steps specifically, or why it is correct to do so, or why this particular `y` value is desirable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-KmS1iwKXpvFUtiXdL08:b-temb8y)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 27 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264)*

**Comment by sammy-tri** [comment]
Comments (mostly) addressed.

---

Review status: 21 of 27 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7qUh2bljzNPyBwKY8:-KmWno9oVgeOJzpSQHkQ:b33rl6j) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/state_machine_system.cc#L30)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- I believe you already have a named constant for this value in `gripper_action` or some similar wsg place.
</blockquote></details>

It looks like I actually just have `110` twice...

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7t5O53rKmndEL-Yhy:-KmWunajU_JxdXlj__Z5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/BUILD#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI indentation here seems wrong.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/BUILD, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7tB1ZX80lVryxa-Un:-KmWuo4yRezHXY4rnW6f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/BUILD#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI indentation here seems wrong.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km80iyAzwJix7irWgvk:-KmWogYoajtc1ciyNYtB:bwc3aq) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L64)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I am somewhat confused by the sequence of times.  As I read it you area setting dt as if the time of waypoint 0 is not 0.  Is this intended?  If so, this is surprising and should be in the function comment above.
</blockquote></details>

The size of `times` is eventually `num_via_points + 1` so I think this is right?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 77 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7yOpeKMZATh5aQjFj:-KmWoYrKEpAjaeMVCqTS:bfayixx) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L77)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Um, what?  `true ||` needs at least a comment.  More likely it needs to go away.
</blockquote></details>

Whoops, leftover debugging code.  Removed.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmRzuIf7TtL9ApPsTVu:-KmWoykstFR5ujiApjgB:b-3vppik) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L96)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

"Should be adjusted" by whom, and when?  Is this a todo comment?  An instruction for users of the demo?
</blockquote></details>

I changed the tense/wording slightly under the theory that this comment actually described how we got here.  I'm not sure it improved much.  Considered deleting entirely.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 107 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS-b73jTSjd2ImnZ7r:-KmWpP6prSpNjQbeO1p2:b-enxcf5) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L107)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- This is an extremely long method, and might be clearer if you factored the individual cases into their own methods.  Those could then be unit tested at finer granularity than the current test.

Author's discretion.
</blockquote></details>

I thought about it, and agree it would simplify unit testing.  Not sure it's worth it now.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km7zjRKZEM72OXmPIjD:-KmWqgULnGZyOxMVFy4z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.h#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

All the enum names below should be kConsts.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS163k0jxcNGWQqk8m:-KmWr2GCBVysEYHoAYZG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This needs a comment, or a clearer name. What does it mean to expect an int value from an iiwa?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS1CG3mqjc7S2i8x-C:-KmWr2j48-wmXImo_WTA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L25)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This needs a comment, or a clearer name. What does it mean to expect an int value from a wsg?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS0qTS3HtlcSiu8hhM:-KmWuqdZnGo7wv5A4iYO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

You really need a function comment on this test explaining what it does and justifying the magic numbers below with some sort of narrative of the scene being created and acted out.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-KmS0VFk71zCN27aIIm5:-KmWuZE3fjmP8DNkDQpe:bucbrzs) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc#L141)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This needs a comment -- it is not clear why you are fiddling with the `object_msg` in these steps specifically, or why it is correct to do so, or why this particular `y` value is desirable.
</blockquote></details>

Done.  The transition was actually one step earlier than it needed to be, which I think heightened the confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-KmWv9s1_BHCvWPid90M:bf4ovgj)*

**Comment by ggould-tri** [comment]
I'm still a bit uncertain that the time logic is what you want, but I leave it to your understanding.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-Km80iyAzwJix7irWgvk:-KmXOtCLg9zYdME9ms1y:b-5bj1zf) ([raw file](https://github.com/robotlocomotion/drake/blob/066734784585e6d6d620e3757eeb74dd33773d7f/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L64)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The size of `times` is eventually `num_via_points + 1` so I think this is right?
</blockquote></details>

OK, If it is your intention that `times[0] != 0` then no defect.  I'm just not sure that that is what you want.  I would have expected the times to start at zero.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-KmXSvtWBMpP5j7SR_Hi:b-osir47)*

**Comment by sammy-tri** [comment]
(from f2f, we've come to an agreement about the time logic)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6264#-:-KmY9oivRjorZXLSkz20:b-ermfe9)*

**Pull request merged**
