### PR TITLE
Toward #2852: enforce -Werror=shadow in systems/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from systems/** cmake files.
 * Rename private members with '_' suffix per style guide.
 * Fix some ctors of classes with protected/public data.
 * Generally kill 'this->' with fire in touched files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2898)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
A *big* hunk of #2852.

**Comment by rpoyner-tri** [comment]
... and now we play the guess-howto-fix-unbuildable code game. Whee, Jenkins.

**Comment by liangfok** [comment]
left a few comments

---

Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 390 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKVIhF3nq0z0vdlHUB:-KNKVIhF3nq0z0vdlHUC:129135449) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/parser_urdf.cc#L390)):*
> ```cpp
>       XMLElement* color_node = material_node->FirstChildElement("color");
>       if (color_node) {
>         Vector4d zomg;
> ```

Maybe delete this variable?

---

*[drake/systems/plants/test/benchmarkRigidBodyTree.cpp, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKWRMJSNXteDfbc_q-:-KNKWRMJSNXteDfbc_q0:1503153543) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/benchmarkRigidBodyTree.cpp#L18)):*
> ```cpp
> 
> //default_random_engine generator;
> //uniform_real_distribution<> uniform(0, 1);
> ```

Remove commented out code?

---

*[drake/systems/plants/test/urdfCollisionTest.cpp, line 25 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKWjHs-3WexsoMD0Vs:-KNKWjHs-3WexsoMD0Vt:1739653878) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/urdfCollisionTest.cpp#L25)):*
> ```cpp
> 
>   if (argc >= 2 + model->number_of_positions()) {
>     for (i = 0; i < model->number_of_positions(); i++)
> ```

How about make this `int i = 0` and delete the `int i;` line above?

Then we can keep the `int i = 0`in the for loops below.

---

*[drake/systems/plants/test/urdfKinTest.cpp, line 34 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKX18DMsG1vt1bVzFc:-KNKX18EFescm9wJtvHv:-358578191) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/urdfKinTest.cpp#L34)):*
> ```cpp
>   //  const Vector4d zero(0, 0, 0, 1);
>   Eigen::Vector3d zero = Eigen::Vector3d::Zero();
>   //Eigen::Matrix<double, 6, 1> pt;
> ```

why not remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNKY-TFllDhOnpnTfWq:-627530001)*

**Comment by rpoyner-tri** [comment]
You saw the label, right? :)

---

Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 390 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKVIhF3nq0z0vdlHUB:-KNKZ2ZxeMpENlSP3bd6:85448944) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/parser_urdf.cc#L390)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Maybe delete this variable?
</details>
I'll do something with, sure. If you have any clue as to intent of either the inner or outer copy of rgba, let me know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNKazosnPaWpnBO_nrg:-1480806256)*

**Comment by rpoyner-tri** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 390 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKVIhF3nq0z0vdlHUB:-KNKe80FXyjlVFb1BJGm:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/parser_urdf.cc#L390)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> I'll do something with, sure. If you have any clue as to intent of either the inner or outer copy of rgba, let me know.
</details>
Done.

---

*[drake/systems/plants/test/benchmarkRigidBodyTree.cpp, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKWRMJSNXteDfbc_q-:-KNKdKNrUER4rfRNHdd7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/benchmarkRigidBodyTree.cpp#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Remove commented out code?
</details>
Done.

---

*[drake/systems/plants/test/urdfCollisionTest.cpp, line 25 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKWjHs-3WexsoMD0Vs:-KNKf7WMNf1LQbyZfnAC:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/urdfCollisionTest.cpp#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> How about make this `int i = 0` and delete the `int i;` line above?
> 
> Then we can keep the `int i = 0`in the for loops below.
</details>
Done.

---

*[drake/systems/plants/test/urdfKinTest.cpp, line 34 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKX18DMsG1vt1bVzFc:-KNKg9P2rMKVxzC-PhyF:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/test/urdfKinTest.cpp#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> why not remove?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by rpoyner-tri** [comment]
+@liangfok for feature review -- there is only a bit more! :)
+@sherm1 for platform review -- I expect this will just wait til Monday now.

---

Review status: 14 of 23 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNL0NanIR-pb_Qg_K5I:51956438)*

**Comment by liangfok** [comment]
Oops. I didn't see the label. Oh well, a premature review shouldn't _hurt_ right?

---

Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.h, line 120 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNMT3tdYmpH_by94XVQ:-KNMT3tdYmpH_by94XVR:-390425778) ([raw file](https://github.com/robotlocomotion/drake/blob/ddfb448c5046827458d2d137b0bed903d4dc16f9/drake/systems/controllers/InstantaneousQPController.h#L120)):*
> ```objc
>   void initialize();
>   void loadConfigurationFromYAML(const std::string& control_config_filename);
>   const QPControllerParams& findParams(const std::string& param_set_name);
> ```

Since the purpose of this method must be fresh in your mind, perhaps add a quick Doxygen comment for it?

---

*[drake/systems/plants/parser_urdf.cc, line 390 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNKVIhF3nq0z0vdlHUB:-KNMSKDVfgQ8bpe17vrS:-110543687) ([raw file](https://github.com/robotlocomotion/drake/blob/d6b37f2da38d4bdd9e6878c09ae47d449285d3c8/drake/systems/plants/parser_urdf.cc#L390)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Done.
</details>
Yes, I touched this code recently and the inner `rgba` is a bug I introduced. The outer `rbga` is supposed to hold the color specification of the material, which is added to the material map on line 422.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNMTAxkEapEWEiQZmI7:-1372759112)*

**Comment by rpoyner-tri** [comment]
All's well. I would have been quite sad to increase the amount of comented-out code in Drake. ;)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/InstantaneousQPController.h, line 120 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNMT3tdYmpH_by94XVQ:-KNNGYi6QPAxpWzD9DXp:773672273) ([raw file](https://github.com/robotlocomotion/drake/blob/ddfb448c5046827458d2d137b0bed903d4dc16f9/drake/systems/controllers/InstantaneousQPController.h#L120)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Since the purpose of this method must be fresh in your mind, perhaps add a quick Doxygen comment for it?
</details>
Sure.  I don't recall if we reached a consensus around documenting private methods, but happy to since I'm the one who extracted it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNNGCdged1XnPFsT2i0:4650882)*

**Comment by rpoyner-tri** [comment]
Review status: 21 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/InstantaneousQPController.h, line 120 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNMT3tdYmpH_by94XVQ:-KNNI3KZjRR-Wd9exFLM:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ddfb448c5046827458d2d137b0bed903d4dc16f9/drake/systems/controllers/InstantaneousQPController.h#L120)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Sure.  I don't recall if we reached a consensus around documenting private methods, but happy to since I'm the one who extracted it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/InstantaneousQPController.h, line 120 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNMT3tdYmpH_by94XVQ:-KNNMJvv-cDnXRjjXUNP:-1090450253) ([raw file](https://github.com/robotlocomotion/drake/blob/ddfb448c5046827458d2d137b0bed903d4dc16f9/drake/systems/controllers/InstantaneousQPController.h#L120)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Done.
</details>
Oh I did not realize this was a private method. I believe the consensus is private methods and member variables will have documentation but not in Doxygen format. Thus, they should use two forward slashes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by rpoyner-tri** [comment]
Review status: 22 of 23 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/controllers/InstantaneousQPController.h, line 120 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNMT3tdYmpH_by94XVQ:-KNSDsZVi-aHdLJ6ICfU:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ddfb448c5046827458d2d137b0bed903d4dc16f9/drake/systems/controllers/InstantaneousQPController.h#L120)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Oh I did not realize this was a private method. I believe the consensus is private methods and member variables will have documentation but not in Doxygen format. Thus, they should use two forward slashes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: 22 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNSXX5IT89WzIIMuGqK:1417088721)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by sherm1** [comment]
Platform review: partial.

---

Reviewed 6 of 20 files at r1, 3 of 9 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 585 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXdNIaaes48_9U9lLK:-KNXdNIaaes48_9U9lLL:-464889258) ([raw file](https://github.com/robotlocomotion/drake/blob/ce77210bf9b26bd4d59e5890f457712b623d8fde/drake/systems/controllers/InstantaneousQPController.cpp#L585)):*
> ```cpp
> }
> 
> const QPControllerParams& InstantaneousQPController::findParams(
> ```

+1 for making this a separate method. Better to follow style guide here and call this new method `FindParams()`. I realize it is inconsistent with the other method names here but I think the inconsistency creates some tension that will encourage someone to fix the rest. 

---

*[drake/systems/plants/RigidBodySystem.cpp, line 769 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXfNyGQeb7Qaa43Eu1:-KNXfNyHAR8PZiNE3gEr:1526950532) ([raw file](https://github.com/robotlocomotion/drake/blob/ce77210bf9b26bd4d59e5890f457712b623d8fde/drake/systems/plants/RigidBodySystem.cpp#L769)):*
> ```cpp
> 
>     Isometry3d transform_sensor_to_model = transform_link_to_model;
>     pose = elnode->FirstChildElement("pose");
> ```

Reusing this variable isn't a good fix because it violates RAII. This `pose` is meaningful only for these few lines, and the previous one was valid for only a few lines there. With this change it appears that these are related somehow. A better fix would be to make the previous `pose` go out of scope after it is no longer needed. I believe you can actually declare it in the `if` statement (above and here) as you would in a `for`:
```c++
if (XMLElement* pose = node->FirstChildElement("pose") {
  poseValueToTransform(pose, pose_map, transform_link_to_model);
    pose_map.insert(
        std::pair<string, Isometry3d>(body->name_, transform_link_to_model));
}
// name `pose` is out of scope here
```
If that doesn't work you could surround the code with `{}` to open an close a scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNXgzh8t12Y9YqrS0T2:-1652815917)*

**Comment by sherm1** [comment]
Platform review pass done -- PTAL. Rico, thanks for this heroic sacrifice!

---

Reviewed 8 of 20 files at r1, 4 of 9 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 114 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXvsHanC67WqhGSTvj:-KNXvsHanC67WqhGSTvk:2130735219) ([raw file](https://github.com/robotlocomotion/drake/blob/ce77210bf9b26bd4d59e5890f457712b623d8fde/drake/systems/plants/RigidBodyTree.cpp#L114)):*
> ```cpp
> 
>   // Reasign body_index to be the i-th entry in RBT::bodies
>   for (i = 0; i < bodies.size(); i++) {
> ```

This violates RAII -- shouldn't reuse the `i` from an earlier scope unless you mean for it to be accessed from that scope after the loop. The problem is actually that the *previous* use of `i` is in too big of a scope. I think you could fix it easily by changing from `while` to `for` like this:
```c++
for (size_t i=0; i < bodies.size()-1;) {
}
```
The odd increment/decrement logic could remain as is but the scope would shrink.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNXxlKX1NrWfQRBrZVC:-115449153)*

**Comment by rpoyner-tri** [comment]
Thanks for the review, @sherm1. Sadly, I probably have to table this one until I finish fixing my snopt-mex shadowing debacle. See #2915, #2920, #2925, ...

I will be back. ;)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNYmEoY77BIpuuOaLv-:879839233)*

**Comment by rpoyner-tri** [comment]
Review status: 14 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 585 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXdNIaaes48_9U9lLK:-KNZluP2nGNlxlPHtZrZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/controllers/InstantaneousQPController.cpp#L585)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> +1 for making this a separate method. Better to follow style guide here and call this new method `FindParams()`. I realize it is inconsistent with the other method names here but I think the inconsistency creates some tension that will encourage someone to fix the rest. 
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 769 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXfNyGQeb7Qaa43Eu1:-KNZlr1079lfz6q4JnDn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/plants/RigidBodySystem.cpp#L769)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Reusing this variable isn't a good fix because it violates RAII. This `pose` is meaningful only for these few lines, and the previous one was valid for only a few lines there. With this change it appears that these are related somehow. A better fix would be to make the previous `pose` go out of scope after it is no longer needed. I believe you can actually declare it in the `if` statement (above and here) as you would in a `for`:
> ```c++
> if (XMLElement* pose = node->FirstChildElement("pose") {
>   poseValueToTransform(pose, pose_map, transform_link_to_model);
>     pose_map.insert(
>         std::pair<string, Isometry3d>(body->name_, transform_link_to_model));
> }
> // name `pose` is out of scope here
> ```
> If that doesn't work you could surround the code with `{}` to open an close a scope.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 114 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXvsHanC67WqhGSTvj:-KNZlsU-FqklEnmgfAZf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/plants/RigidBodyTree.cpp#L114)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This violates RAII -- shouldn't reuse the `i` from an earlier scope unless you mean for it to be accessed from that scope after the loop. The problem is actually that the *previous* use of `i` is in too big of a scope. I think you could fix it easily by changing from `while` to `for` like this:
> ```c++
> for (size_t i=0; i < bodies.size()-1;) {
> }
> ```
> The odd increment/decrement logic could remain as is but the scope would shrink.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by rpoyner-tri** [comment]
Marked Do not merge since the current branch subsumes #2925.

---

Review status: 14 of 27 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KNZlzZdOWnGZKGCOqYE:338829505)*

**Comment by rpoyner-tri** [comment]
Review status: 14 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 585 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXdNIaaes48_9U9lLK:-KNZpwNq-OL9GZsNtNUw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/controllers/InstantaneousQPController.cpp#L585)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Done.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 769 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXfNyGQeb7Qaa43Eu1:-KNZpyLeSmSJoENEMQNe:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/plants/RigidBodySystem.cpp#L769)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Done.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 114 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-KNXvsHanC67WqhGSTvj:-KNZpzNVzA4_T0A02JEQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/70541b62f80c53bad1583e79c5e9f68a67ee727c/drake/systems/plants/RigidBodyTree.cpp#L114)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 9 of 13 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2898#-:-KN_Aj5JeRM8uGsjhKcA:1058782226)*

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Pull request merged**
