### PR TITLE
Use FindBLAS and fix Bullet include paths for MEX

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3510)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review and @jwnimmer-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
Hmm... seems okay to me, but I can't build it and am not really familiar with most of the parts involved in this or what issue this is fixing...

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/CMakeLists.txt, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3510#-KS2sX9ttVH3DATwl8og:-KS2sX9wb6CfC0NR8VEJ:bs2ojn5) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d24a6bf4c2a86d8853d0cbde38dc86474c09ef/drake/systems/trajectories/CMakeLists.txt#L36)):*
> ```CMake
>       ${BLAS_LIBRARIES} ${BULLET_LIBRARIES})
>     set_property(TARGET shiftFunnel_snopt_mex APPEND_STRING PROPERTY
>       LINK_FLAGS "${BLAS_LINKER_FLAGS}")
> ```

Hmm... there is no such thing as `target_link_options`, is there? I wonder if there should be...?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3510#-:-KS2sjDhpA7Pwt2EhJD-:bg6aizr)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/CMakeLists.txt, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3510#-KS2sX9ttVH3DATwl8og:-KS2tUxrFgMOL88otzmD:b-dni4qt) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d24a6bf4c2a86d8853d0cbde38dc86474c09ef/drake/systems/trajectories/CMakeLists.txt#L36)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Hmm... there is no such thing as `target_link_options`, is there? I wonder if there should be...?
</details>
Correct, no `target_link_options`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3510)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

I confirmed that this PR's builds mention `replanFunnels_mex` in their console output, while other current PRs do not.  That confirms that this PR re-enables the files under CI.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3510#-:-KS2t1d4BFhrtZdUMDjc:b-yhcmc0)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectories/CMakeLists.txt, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3510#-KS2sX9ttVH3DATwl8og:-KS2vOHkvrWD8IbU3UJK:blwciaw) ([raw file](https://github.com/robotlocomotion/drake/blob/f0d24a6bf4c2a86d8853d0cbde38dc86474c09ef/drake/systems/trajectories/CMakeLists.txt#L36)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Correct, no `target_link_options`.
</details>
The first question was rhetorical :smile:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3510)*

**Comment by jwnimmer-tri** [comment]
Tagging for github linking: this is work towards #2754.

**Comment by jwnimmer-tri** [comment]
As soon as the mac build rolls around, we can merge.  And look, it just finished as I was typing this!

**Comment by jwnimmer-tri** [comment]
(While I think the reviewable discussion of "should we add sugar to CMake?" is a good question, I'm agree we should not hold up this PR for it.)

**Comment by mwoehlke-kitware** [comment]
> While I think the reviewable discussion of "should we add sugar to CMake?" is a good question, I'm agree we should not hold up this PR for it.

Since we'd be holding the PR until CMake 3.7 or quite possibly 3.8, I'd have to concur :smile:. (That discussion was never intended to be blocking...)

**Pull request merged**
