### PR TITLE
SimpleCar support for TaylorVarXd

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add SimpleCar support for TaylorVarXd:
- Express the minimal scalar type concept for simple car.
- Remove the modulus on steering_angle, in preparation for TaylorVarXd.
- Add pre-compiled TaylorVarXd support.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2523)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review.

The TaylorVarXd isn't strictly needed yet for Cars, but serves as a good forcing example to constrain the arithmetic.

My guess was this PR by itself is enough of an increment, but I would be willing to consider adding TaylorVarXd-using tests if that helps.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### SimpleCar support for TaylorVarXd
> 
> Add SimpleCar support for TaylorVarXd:
> 
> - Express the minimal scalar type concept for simple car.
> 
> - Remove the modulus on steering_angle, in preparation for TaylorVarXd.
> 
> - Add pre-compiled TaylorVarXd support.
> 
> 
> 
</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJmOe57RDo7pj0aT-S5:667627157)*

**Comment by liangfok** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJmQ6-8o4L1jE0vrr3p:-KJmQ6-8o4L1jE0vrr3q:1764800838) ([raw file](https://github.com/robotlocomotion/drake/blob/f2f7d1086521c40d944dc263272513ebc7dc66e6/drake/examples/Cars/test/simple_car_scalartype_test.cc#L1)):*
> ```cpp
> g#include "drake/examples/Cars/simple_car-inl.h"
> ```

Is there an extra "g" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJmQ6-8o4L1jE0vrr3p:-KJmYiIr4IBYnPlN1YqE:1509032450) ([raw file](https://github.com/robotlocomotion/drake/blob/f2f7d1086521c40d944dc263272513ebc7dc66e6/drake/examples/Cars/test/simple_car_scalartype_test.cc#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Is there an extra "g" ?
</details>
Derp.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523)*

**Comment by rpoyner-tri** [comment]
nits, but it looks solid.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@rpoyner-tri for feature review.
> 
> The TaylorVarXd isn't strictly needed yet for Cars, but serves as a good forcing example to constrain the arithmetic.
> 
> My guess was this PR by itself is enough of an increment, but I would be willing to consider adding TaylorVarXd-using tests if that helps.
</details>


---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 49 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJpXkLl6Rw4Sfn6A5HS:-KJpXkLms2uNMrXfoIUT:492918330) ([raw file](https://github.com/robotlocomotion/drake/blob/b04976be8eb87d0644ac771c9d1a7086160f68b6/drake/examples/Cars/test/simple_car_scalartype_test.cc#L49)):*
> ```cpp
> 
>   // If we compiled, declare victory.
>   EXPECT_EQ(0, 0);
> ```

consider GTEST_SUCCEED() ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJpYCZ7YKG-BpSAgwY-:1250389874)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 49 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJpXkLl6Rw4Sfn6A5HS:-KJpi_eKzVPDl2aLwGlQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/b04976be8eb87d0644ac771c9d1a7086160f68b6/drake/examples/Cars/test/simple_car_scalartype_test.cc#L49)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> consider GTEST_SUCCEED() ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review -- low priority.

<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> nits, but it looks solid.
</details>


---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJpimSk8mb28LwWdEeZ:1195781561)*

**Comment by rpoyner-tri** [comment]
:lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@david-german-tri for platform review -- low priority.
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJpjiXSmkIOtnbtk0aO:1417088721)*

**Comment by david-german-tri** [comment]
:lgtm: with or without suggested change

<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJplekv99RLXFg9k57H:-KJplekv99RLXFg9k57I:187715082) ([raw file](https://github.com/robotlocomotion/drake/blob/565893cc4f1fbf15f90f4a4588a6abddca6b9faa/drake/examples/Cars/test/simple_car_scalartype_test.cc#L10)):*
> ```cpp
> namespace {
> /// An expression of the minimal ScalarType (MST) concept for SimpleCar.
> struct MST {
> ```

This seems to me like it has potentially widespread value - both for other test cases like this one, and for documenting/proving the operations a ScalarType must support.  Consider moving to drake/common.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJplsEqPEKcBZMUAIFr:1851361879)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/test/simple_car_scalartype_test.cc, line 10 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-KJplekv99RLXFg9k57H:-KJpoa8gYEKIXcwbTrVc:976850563) ([raw file](https://github.com/robotlocomotion/drake/blob/565893cc4f1fbf15f90f4a4588a6abddca6b9faa/drake/examples/Cars/test/simple_car_scalartype_test.cc#L10)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This seems to me like it has potentially widespread value - both for other test cases like this one, and for documenting/proving the operations a ScalarType must support.  Consider moving to drake/common.
</details>
I definitely agree!  This is a first step.  I tend to like developing novel work in the leaves of a tree, and then promoting to base classes once it has proved its use.

In this case, I also want to bake off FunctionalForm vs MST, as well as other systems like TrajectoryCar vs MST, before moving MST into common/test or similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523)*

**Comment by jwnimmer-tri** [comment]
I've marked the optional code hoist as resolved, to make reviewable happy.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm: with or without suggested change
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2523#-:-KJqBFIjbJRgJvip0v_5:-1486405894)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to out-of-date-with-master.

**Pull request merged**
