### PR TITLE
[pybind11] Avoid deprecated pandas API in coverage tool

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) +(status: single reviewer ok) +@jwnimmer-tri for both reviews.

Needs to re-test the CI variants that previously broke. Manual testing on in-house mac Monterey was successful.

FYI @mwoehlke-kitware fix for buildcop failures.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-:-NSCQ6Ot75uoygTkCiWc:bkb8h9u)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Ah, looks like #18573 missed one of these.  Oh well.

**Review by rpoyner-tri — COMMENTED** [review]
The deprecation issue in pandas: https://github.com/pandas-dev/pandas/issues/35407

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-:-NSCaUTg40jgSSzvkiCI:b-1z2859)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please.
</blockquote></details>

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
 @drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: pending CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-:-NSD25ar-NosSFugGLgP:bwo9p68)* status: 1 unresolved discussion (waiting on @drake-jenkins-bot)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSCQuFF7V0TV5sRNxPr:-NSD21D90gC1XmPgDyR5:b-pc95hg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please.
 @drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please.

</blockquote></details>

CI shows test case failures that seem on point.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 1 unresolved discussion (waiting on @drake-jenkins-bot)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSCQuFF7V0TV5sRNxPr:-NSH2CBz50xsX7-RzgeA:b-nurq31) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

CI shows test case failures that seem on point.
</blockquote></details>

It is frustrating that the patch that fixes focal breaks macos. Still investigating.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSCQuFF7V0TV5sRNxPr:-NSH2yst22uaYz-tD-Zh:b5j6886) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

It is frustrating that the patch that fixes focal breaks macos. Still investigating.
</blockquote></details>

I basically consider the bindings coverage report a failed experiment at this point.  I'd toyed with the idea of deleting it.  If it's being a huge pain here, now might be the time.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 2 unresolved discussions (waiting on @rpoyner-tri)

___
*[`tools/workspace/pybind11/pybind_coverage_xml_parser.py` line 348 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSHX0_FCrf7odF2P7o3:-NSHX0_FCrf7odF2P7o4:b-r701kg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b13a46e85db01560a15108d5f0559158f938b8c4/tools/workspace/pybind11/pybind_coverage_xml_parser.py#L348)):*
> ```Python
>         final_row["FileName"] = "TOTAL"
>         kwargs = dict(ignore_index=True)
>         if version.parse(pandas.__version__) >= version.parse('1.0'):
> ```

BTW as you've probably noticed, the new dependency is problematic.



_Suggestion:_
```Python
if pandas.__version__[0] != '0':
```

**Review by rpoyner-tri — COMMENTED** [review]
`r4` is still wrong; don't bother launching mac CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-:-NSHP0tVEFBhEcnbny-T:b-i3mxwb)* status: 2 unresolved discussions (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSCQuFF7V0TV5sRNxPr:-NSHhoQA82_a12Sv2vmR:bky1lh3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I basically consider the bindings coverage report a failed experiment at this point.  I'd toyed with the idea of deleting it.  If it's being a huge pain here, now might be the time.
</blockquote></details>

Removal is looking better and better. AFAICT, that would allow dropping pandas as a drake dependency as well.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19128)* status: 2 unresolved discussions (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19128#-NSCQuFF7V0TV5sRNxPr:-NSHkTyh77hXgTCTdvw4:b-xcvdek) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Removal is looking better and better. AFAICT, that would allow dropping pandas as a drake dependency as well.
</blockquote></details>

In that case the ideal buildcop response would be adding a couple "manual" tags and land that to stop the bleeding, then I can do another pass later to purge it entirely.

___

**Comment by rpoyner-tri** [comment]
pandas 2 breaks this file in other ways that are not trivial. Time to abandon this patch.

**Pull request closed without merging**
