### PR TITLE
Adding A Valgrind Suppression For Gurobi

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Failing build:
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/40/consoleText

https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=663929

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6393)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/valgrind.supp, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6393#-KnA1XZz5QjLEfzEUxGJ:-KnA1XZz5QjLEfzEUxGK:bo3pjw3) ([raw file](https://github.com/robotlocomotion/drake/blob/b61b75415ee8b6b9547e36f92eed5ead9e13c5af/tools/valgrind.supp#L80)):*
> ```
> }
> 
> {
> ```

Add comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6393)*

**Comment by m-chaturvedi** [comment]
This started happening after Gurobi was updated to 7.0.2.
https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/

**Comment by jamiesnape** [comment]
With no other related code changes?

**Comment by m-chaturvedi** [comment]
No. One of the tests failing is `test_approximate_ik`.  It calls Gurobi in `approximate_ik.cc`:177.  Both weren't changed in the last two days.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6393#-:-KnBd3D1yLTcB00ec2eE:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
Sad but :lgtm:.  Have we notified Gurobi upstream?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6393#-:-KnFLegbBRtebljeXlON:b-5jwlyo)*

**Comment by m-chaturvedi** [comment]
No, we haven't.  I don't have access to Gurobi in order to create a minimal example on which the problem can be reproduced.
I couldn't find any bug reporting platform by them.  Only a Google group:
https://groups.google.com/forum/#!forum/gurobi

**Pull request merged**
