### PR TITLE
systems: Deprecate context.FixInputPort()

### PR DESCRIPTION
**Pull request by mpetersen94**
Changes remaining public usages of `context.FixInputPort()` to `port.FixValue()`, deprecates all versions of FixInputPort in python and deprecates all vector versions of FixInputPort in C++ (AbstractValue version required internally for implementation of FixValue).

Towards #11341

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@sherm1 for feature review

**Comment by mpetersen94** [comment]
___
*[systems/framework/context.h, line 438 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MHX-mID79QcAjiUXqC8:-MHX-mIEAEx0B_OLjG2M:b-byerj0) ([raw file](https://github.com/robotlocomotion/drake/blob/5a8012b9fbbbf56b246fa2176a3ca9a0bf6bee2f/systems/framework/context.h#L438)):*
> ```objc
> 
>   // Allow access to the base class method (takes an AbstractValue).
>   using ContextBase::FixInputPort;
> ```

Not sure the best way to deprecate this/move it to internal.  Should I deprecate the same way I did below but with a comment that we will move this to internal instead of deleting it when deprecation expires?

**Comment by sherm1** [comment]
FYI @xuchenhan-tri

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 11 of 28 files at r1, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending resolution of open discussions

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MHqyN888joJF3pEgRPK:b-x2updq)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
I've confirmed the jupyter notebooks work (and reconfirmed after the rebase and changes).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MHX-ag5CWDChe215JU5:b-nc8pwb)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[systems/framework/context.h, line 438 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MHX-mID79QcAjiUXqC8:-MIVXGDS7ROiGT7d4tHC:b-hd91bx) ([raw file](https://github.com/robotlocomotion/drake/blob/5a8012b9fbbbf56b246fa2176a3ca9a0bf6bee2f/systems/framework/context.h#L438)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My inclination is to leave the primary base class method public (not internal) but update the comment in ContactBase::FixInputPort to start with "(Advanced)" and clearly recommend port.FixValue() as the preferred method. The utility of that method is that it can be used in the rare case where all you have is a Context without a handy System.

The second ContextBase::FixInputPort "sugar" signature should be deprecated leaving just the primary one (the one that takes a unique_ptr).

I'd be happy to see the `using` here deprecated since an Advanced user can be expected to access it through the base class (might then have to prefix the call with `this->` which is not currently required).
</blockquote></details>

Updated the comment PTAL.  Also deprecated the sugar method.  I don't know how to deprecate the using.  Can it just be removed?
___
*[systems/framework/test/diagram_context_test.cc, line 156 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MHqcOouCtsvJdCDiP1M:-MIVY9rO31aLUe0uFtB3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c0f09f1adedde1fb761ad4d78f86170263f15d6/systems/framework/test/diagram_context_test.cc#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW these will have to change to call the primary signature (using make_unique probably).
</blockquote></details>

Done.
___
*[systems/framework/test/leaf_system_test.cc, line 1106 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MHqdQfJ1QxA2cJjAPyF:-MIXRTJKBuwFOZSXkXXy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9c0f09f1adedde1fb761ad4d78f86170263f15d6/systems/framework/test/leaf_system_test.cc#L1106)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: can these two be converted to FixValue? I think the same error message should be produced.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Changes look great, thanks Mark! CI failed however in Debug and leak sanitizer builds. Doesn't look like a flake -- reported failure was in leaf_system_test.cc around line 1113 I think and changes were made there. When that's fixed this is ready to merge.

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MIXdBRTCFQxEhPNE5OS:b-q6gddd)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

___
*[systems/framework/context_base.h, line 210 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MIXbmar5cLTHig9PQNR:-MIXbmar5cLTHig9PQNS:b-93w967) ([raw file](https://github.com/robotlocomotion/drake/blob/1885122dde0fe72ec575d651a837a78541b52261/systems/framework/context_base.h#L210)):*
> ```objc
>   This is the most general way to provide a value (type-erased) for an
>   unconnected input port. Using the `FixValue` method of the input port to set
>   is the preferred workflow due to its additional sugar.
> ```

nit: "to set" -> "to set the value"?

btw also conventional to write `FixValue()` (with empty parens) so that the function name doesn't look like a class name.

**Review by mpetersen94 — COMMENTED** [review]
I think it might be issue of lifetime of objects.  I know `Context`s can outlive the system that creates them but can `InputPorts`?  If not, I think I have to change `leaf_system_test.cc` back to use `FixInputPort()` since the test intentionally deletes the system before setting input ports.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MI_g89W9CgYSGu0yXCh:b-h1j6yr)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[systems/framework/context_base.h, line 210 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MIXbmar5cLTHig9PQNR:-MI_b8fc4hCdCyRYwPFB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1885122dde0fe72ec575d651a837a78541b52261/systems/framework/context_base.h#L210)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "to set" -> "to set the value"?

btw also conventional to write `FixValue()` (with empty parens) so that the function name doesn't look like a class name.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Right -- InputPorts are part of the System so die when it does.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MI_ntKu6KIlze4flls_:b-lcyaf9)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[systems/framework/context_base.h, line 210 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MIXbmar5cLTHig9PQNR:-MI_nnjYDMqpJ-XZABO9:b-4jaauf) ([raw file](https://github.com/robotlocomotion/drake/blob/1885122dde0fe72ec575d651a837a78541b52261/systems/framework/context_base.h#L210)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing the changes?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by mpetersen94 — COMMENTED** [review]
Rolled backed the changes to `leaf_system_test.cc` to use `context.FixInputPort()` due to lifetime of `InputPort`s.  PTAL

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MI_wwC_BSLxEjanSCb9:b7goldj)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri and @sherm1)

___
*[systems/framework/context_base.h, line 210 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14093#-MIXbmar5cLTHig9PQNR:-MI_x9Ac27P-p4L0f6bX:b65gnr4) ([raw file](https://github.com/robotlocomotion/drake/blob/1885122dde0fe72ec575d651a837a78541b52261/systems/framework/context_base.h#L210)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm not seeing the changes?
</blockquote></details>

I didn't want to push just comment changes and start a slew of builds. Waited to push changes until the other piece was fixed too.

**Review by sherm1 — COMMENTED** [review]
Looks good, thanks.

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MIaGSRN9OPVMZPgA3kO:br06oxv)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sherm1 — COMMENTED** [review]
Note: Anzu has five uses I could find of FixInputPort that may cause warnings there. Those should be replaced with FixValue in a quick follow up PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MIaahGR4yjllMNXCtsq:bf5tpcj)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by mpetersen94 — COMMENTED** [review]
I don't have access to Anzu so someone else will have to take care of that change.  If someone can merge this now that all the tests have passed, that would be great!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14093#-:-MIbWaXZ9Z2YEcKAtiGA:b-md61qd)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
Offline, Sherm mentioned that he's working on the Anzu PR.

**Comment by sherm1** [comment]
FYI Anzu PR #5573 submitted to avoid deprecation warnings.

**Pull request merged**
