### PR TITLE
Update FCL version.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Update FCL version, February 2019.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10701)

### CODE REVIEW

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-debug please

**Comment by jamiesnape** [comment]
(Please don't retrigger the Mac debug build, we don't really have the resources to run that during the day.)

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please.
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please.
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-python3-release please.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-release please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-release please.
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-release please.
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please.

**Comment by jamiesnape** [comment]
FYI You can use `@drake-jenkins-bot XXX retest XXX this XXX please` (without the `XXX`) to retrigger all the required builds.

**Pull request merged**
