### PR TITLE
[geometry/optimization] Change GCS SolveShortestPath to take configuration options

### PR DESCRIPTION
**Pull request by mpetersen94**
Switches the default behavior of SolveShortestPath to `convex_relaxation=true`.

cc @RussTedrake @TobiaMarcucci

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@russtedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396#-:-N4Yl2345vQneZ-hrCH8:b-e8hf3g)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17396#-N8xWyNo3BDgShV9c_Yq:-N8xWyNo3BDgShV9c_Yr:by71toh) ([raw file](https://github.com/robotlocomotion/drake/blob/7be20724911e8d0bf73135d34bce2456f68e7b79/geometry/optimization/graph_of_convex_sets.h#L25)):*
> ```objc
> namespace optimization {
> 
> struct SppOptions {
> ```

Do you think this is specific to SPP, or might it be more general for GCS?  So far, they all seem more general (the source and the target are the main things that are specific to SPP?)

And I think we need to call it "ShortestPathOptions" to avoid the abbreviation.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 325 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17396#-N8xYNTk6u_JPatw8svY:-N8xYNTk6u_JPatw8svZ:b-kjx546) ([raw file](https://github.com/robotlocomotion/drake/blob/7be20724911e8d0bf73135d34bce2456f68e7b79/geometry/optimization/test/graph_of_convex_sets_test.cc#L325)):*
> ```cpp
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> TEST_F(ThreePoints, DeprecatedSolveShortestPath) {
> ```

It is more standard to duplicate the entire batch of tests using the old API (leaving the old API behind the GCC_diagnostic).  As it stands, I think you still have coverage for the solver_optional, but perhaps not convex_relaxation?

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17396#-N8xWyNo3BDgShV9c_Yq:-NAFmxME2bj-ciA-4Y2W:br9g8lc) ([raw file](https://github.com/robotlocomotion/drake/blob/7be20724911e8d0bf73135d34bce2456f68e7b79/geometry/optimization/graph_of_convex_sets.h#L25)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Do you think this is specific to SPP, or might it be more general for GCS?  So far, they all seem more general (the source and the target are the main things that are specific to SPP?)

And I think we need to call it "ShortestPathOptions" to avoid the abbreviation.
</blockquote></details>

Since we currently only have the use case of GCS for SPP, I'm not sure. Once we add the rounding options I could see it becoming more specific to SPP but I haven't thought about whether the rounding strategy would work for other graph problems. For a TSP, I think the rounding strategy would need to change slightly but the parameters probably wouldn't.

For now I've changed it to `GraphOfConvexSetsOptions` but I'm open to changing that as we discuss.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 325 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17396#-N8xYNTk6u_JPatw8svY:-NAFmfUP3SYTlQx1GWo7:byvejek) ([raw file](https://github.com/robotlocomotion/drake/blob/7be20724911e8d0bf73135d34bce2456f68e7b79/geometry/optimization/test/graph_of_convex_sets_test.cc#L325)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

It is more standard to duplicate the entire batch of tests using the old API (leaving the old API behind the GCC_diagnostic).  As it stands, I think you still have coverage for the solver_optional, but perhaps not convex_relaxation?
</blockquote></details>

I went ahead and increased the coverage without adding back every test. I didn't think testing every cost and every constraint with both interfaces was worthwhile. LMK if this feels like sufficient coverage.

**Review by mpetersen94 — COMMENTED** [review]
+@ericcousineau-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396#-:-NAjoyJA43oswpvOCyBD:b-6jso97)* status: 2 unresolved discussions, LGTM missing from assignees RussTedrake(platform),EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396#-:-NAk2Dt658tdyA2KCwoJ:bnfp4nl)* status: 6 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @mpetersen94)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: pending resolution of below comments

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396#-:-NAk2yQaASIDmvjBw5ze:b-nwdf74)* status: 6 unresolved discussions, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
+(release notes: breaking change) default behavior of SolveShortestPath as mentioned in the PR description.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396#-:-NAk4NlaBj6Xmkap2TZn:bbes5hj)* status: 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 348 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjqsGF92YeAmNQ3Rqv:-NAk1Pm-ENGd3_y5Wai_:bbcnj0e) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/bindings/pydrake/geometry_py_optimization.cc#L348)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Usage a bit odd.

Why not use `DefReadWriteKeepAlive()`?
It's admittedly oddly placed in `wrap_pybind.h`, but still motivates the construct moreso than what is presently here.
</blockquote></details>

Because I didn't know that existed! Thanks for the pointer!
___
*[`geometry/optimization/graph_of_convex_sets.h` line 32 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjrkJz8zFNAQ2ns669:-NAk36Fn2ovyKWsK2fwj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Do other config structs tend to use brace initializers? e.g.
`bool convex_relaxation{true};`
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjrgo-ACSgnpORxBLX:-NAk3C4T4BlvYKryWpHB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Spelling "Optimizer"
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjrx5ZBRCsM96HHzdh:-NAk3S4DDMaTBw1OIRPi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `it` is ambiguous.

Consider qualifying as "the calling solve method"
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjs2Z-8O8gJT62TFPh:-NAk3lp0Clp29PLCOpei:b-bjpj7a) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (grammar) Flow is a bit odd.

Consider shortening: "Options passed to solver the problem is generated."
</blockquote></details>

Better?
___
*[`geometry/optimization/graph_of_convex_sets.h` line 381 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjsCqECVzFGMuOm90s:-NAk4DNL1T6vcSBG43v4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L381)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "for all ..." seems important; consider removing parentheses surrounding it.
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 427 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjsZvZ97r62IELGMDK:-NAk226Z8OyvBqyqsaQN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L427)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Boundary of deprecation has shifted since start of PR.

Per https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html#a847d827d084f28e4ae1788a0ae75be96, can you bump this up (once PR is ready to merge)?
(here and elsewhere)
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17396)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @mpetersen94)

___
*[`bindings/pydrake/geometry_py_optimization.cc` line 348 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjqsGF92YeAmNQ3Rqv:-NAk6XxA7FFXWhHmhsUe:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/bindings/pydrake/geometry_py_optimization.cc#L348)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Because I didn't know that existed! Thanks for the pointer!
</blockquote></details>

OK Sweet!
___
*[`geometry/optimization/graph_of_convex_sets.h` line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17396#-NAjs2Z-8O8gJT62TFPh:-NAk6be989nDb363A8oC:bnle8ss) ([raw file](https://github.com/robotlocomotion/drake/blob/7a2143d586a23944d7cb9b3bd3191f29dd216fc9/geometry/optimization/graph_of_convex_sets.h#L40)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Better?
</blockquote></details>

OK Yup!

**Comment by jwnimmer-tri** [comment]
+(release notes: newly deprecated)

**Pull request merged**
