### PR TITLE
Change equality check to a GE check (since that's what we really meant).

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes the current build failure in linux-gcc-continuous-matlab-open-source

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3108)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by david-german-tri** [comment]
:lgtm: I don't have a deep understanding of the behavior being tested, but it at least makes sense superficially.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3108#-:-KOq30Uh64zAVlxODxTe:b-81lr7s)*

**Comment by liangfok** [comment]
Since this is an update to #3098, I recommend that it get a feature review by @lucy-tri, @hongkai-dai, or @ggould-tri.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3108#-:-KOq2c4L23bHEWXQpLQY:b-hzic4s)*

**Comment by sammy-tri** [comment]
Well, your're the buildcop, and thus the primary person who will be annoyed if the build stays broken, so...

+@lucy-tri for additional feature review

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3108#-:-KOq4ruRj_Cljx9A31ux:b33509a)*

**Comment by liangfok** [comment]
Yeah, I just wanted to make sure this change doesn't introduce a bug that's not detected by CI since I only superficially understand the code.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3108#-:-KOq5n3jesf_MhB9YEzW:b-psjan4)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3108#-:-KOq7GgSlotlDgtYhiIN:bnfp4nl)*

**Pull request merged**
