### PR TITLE
Add tolerance to check zero off-diagonal elements of a rotational inertia.  Return identity matrix if all principal moments of inertia are equal.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NYuDkJq-y50dDzRKQti:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
Feature pass done, PTAL.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZ2H7Vd2YU9SQoJFOFR:b-7uzwif)* status: 7 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rotational_inertia.cc` line 37 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2D9ef-CH-llVQm_9v:-NZ2D9ef-CH-llVQm_9w:bq2l2gv) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L37)):*
> ```cpp
>   // inertia, so compare products of inertia to a tolerance (rather than 0.0)
>   // informed by machine epsilon multiplied by largest moment of inertia.
>   const double kTolerance = 4 * std::numeric_limits<double>::epsilon() *
> ```

nit: this shouldn't be named like a constant since it is a runtime calculated value. Call it `inertia_tolerance` or something like that.
___
*[`multibody/tree/rotational_inertia.cc` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2Da9c38QzWoNXuH4A:-NZ2Da9c38QzWoNXuH4B:bpn5bph) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L122)):*
> ```cpp
>   if (principal_directions != nullptr) {
>     const double &Imin = principal_moments(0);
>     const double &Imax = principal_moments(2);
> ```

nit: `&` formatting
___
*[`multibody/tree/rotational_inertia.cc` line 125 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2FqpO3vjM2lyBkJby:-NZ2FqpO3vjM2lyBkJbz:b-x3gvrj) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L125)):*
> ```cpp
>     // Case: Triaxially symmetric moments of inertia (all 3 are ≈ equal).
>     if (Imax - Imin <= kTolerance) {
>       *principal_directions = math::RotationMatrix<double>::Identity();
> ```

(Per f2f) This would be wrong if there were products of inertia as well as the three equal diagonals. We need some proof that that can't happen (and a comment here) or if it can happen then we need a fix.
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 518 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2E86F7bEnXN3dRIgV:-NZ2E86F7bEnXN3dRIgW:bylzh74) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L518)):*
> ```cpp
> 
>   // Verify principal moments against their expected value.
>   const double kTolerance = 4 * std::numeric_limits<double>::epsilon() *
> ```

nit: fix name
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 533 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2EQ5IBGvxP6dZZPJU:-NZ2EQ5IBGvxP6dZZPJV:b122cxh) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L533)):*
> ```cpp
>                               kTolerance, MatrixCompareType::absolute));
>   EXPECT_FALSE(CompareMatrices(products_of_inertia, Vector3<double>::Zero(),
>                               0.0, MatrixCompareType::absolute));
> ```

BTW this seems odd since it will fail if some machine produces an exact answer. Why do you want to reject that possibility?
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 547 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2ExSh8-LEpmI-FgLh:-NZ2ExSh8-LEpmI-FgLi:b-v9wdi5) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L547)):*
> ```cpp
>   // intermediate, and largest moments of inertia (commented above).
>   // Note: Before July 2023, CalcPrincipalMomentsAndAxesOfInertia() did not use
>   // a "tolerance", so the general eignvalue/eigenvector routine was called if
> ```

typo: eign -> eigen
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 589 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2Gmjk3zScT413co7O:-NZ2Gmjk3zScT413co7P:bj0lip3) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L589)):*
> ```cpp
>                 0, 0, 1;  // principal axes is the identity matrix..
>   EXPECT_TRUE(CompareMatrices(R_QP.matrix(), m_expected,
>                               0.0, MatrixCompareType::absolute));
> ```

minor: probably need a test case with equal diagonals and some products. Is there also a test that covers the general full-inertia case (if so might be good to point that out in a comment)

**Review by mitiguy — COMMENTED** [review]
Ready for another pass (assuming it passes CI).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZ3x1vY1-Ub1oFlV0lv:b-16at6p)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/rotational_inertia.cc` line 37 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2D9ef-CH-llVQm_9v:-NZ3ATsd8Cw-EpREQuJm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this shouldn't be named like a constant since it is a runtime calculated value. Call it `inertia_tolerance` or something like that.
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.cc` line 122 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2Da9c38QzWoNXuH4A:-NZ3A_lP06sH2x_6-qGH:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L122)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: `&` formatting
</blockquote></details>

Done.
___
*[`multibody/tree/rotational_inertia.cc` line 125 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2FqpO3vjM2lyBkJby:-NZ3WCBh3Ospr4S6LKbk:b-lzuih0) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L125)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

(Per f2f) This would be wrong if there were products of inertia as well as the three equal diagonals. We need some proof that that can't happen (and a comment here) or if it can happen then we need a fix.
</blockquote></details>

Added a proof.   Perhaps helpful?
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 518 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2E86F7bEnXN3dRIgV:-NZ3Wu8d9pjaWRR9CKiL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L518)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: fix name
</blockquote></details>

Done.
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 533 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2EQ5IBGvxP6dZZPJU:-NZ3kxAw6sWf8WiwPhLo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L533)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems odd since it will fail if some machine produces an exact answer. Why do you want to reject that possibility?
</blockquote></details>

Done.
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 547 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2ExSh8-LEpmI-FgLh:-NZ3XARqE_lFgf2Qrbuh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L547)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: eign -> eigen
</blockquote></details>

Done.
___
*[`multibody/tree/test/rotational_inertia_test.cc` line 589 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ2Gmjk3zScT413co7O:-NZ3wIXEDfUE8kMaNbCq:b-md4frx) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/test/rotational_inertia_test.cc#L589)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: probably need a test case with equal diagonals and some products. Is there also a test that covers the general full-inertia case (if so might be good to point that out in a comment)
</blockquote></details>

TODO added.

**Review by sherm1 — COMMENTED** [review]
Thanks -- feature :lgtm:
+@xuchenhan-tri for platform review per schedule, please

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZ77mqJDWtA6EXIC1_6:boaihml)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform review done with a question.

> Reviewed 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZ7SPPy72AbRfABtPmx:b-3xfy5v)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7SShdD6730MVQnNq9:-NZ7SSheAQwKS08zZ1yH:b-ncrnqa) (no related file):*
This PR adds a lot of complexity to a function with no change in documented behavior. That left me wondering about the purpose of the change. The change in implementation is aimed at providing a canonical set of principal directions, but the documentation of the function doesn't promise unique principal directions for equivalent inertia. 

The newly added tolerance for determining whether a matrix is diagonal is also a little suspicious. The eigenvalue solver already performs a similar check under the hood. Are we certain that the hand-crafted checks actually provide additional value?

It seems to me this function should be as simple as performing an eigendecomposition and potentially flipping the last column of the eigenvectors to ensure right handedness. To be convinced of this PR, I'd like to see some evidence on

1. this function used in performance critical code to justify the extra work (and potentially discontinuity) introduced by the diagonal special case;
2. the value of a canonical set of principal directions in an application.

___
___
*[`multibody/tree/rotational_inertia.cc` line 123 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7NTXjDMabb58NNGxU:-NZ7NTXjDMabb58NNGxV:bqttgcc) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L123)):*
> ```cpp
>     const double &Imin = principal_moments(0);
>     const double &Imax = principal_moments(2);
>     // Case: Triaxially symmetric moments of inertia (all 3 are ≈ equal).
> ```

BTW, Why is this case not already handled in the diagonal case? The tolerance added in this PR muddies the water a bit, but without it, if Imax==Imin, then we should have already treated this case in the diagonal case above?
___
*[`multibody/tree/rotational_inertia.cc` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7BSkmCxqVhW3ffUbm:-NZ7BSkmCxqVhW3ffUbn:bsb9b4i) ([raw file](https://github.com/RobotLocomotion/drake/blob/02cf116af4b2fe8481a5ce70c44c83baaa713a62/multibody/tree/rotational_inertia.cc#L29)):*
> ```cpp
>   I_double(1, 0) = ExtractDoubleOrThrow(I_BP_E(1, 0));  // (1, 0) not (0, 1).
>   I_double(2, 0) = ExtractDoubleOrThrow(I_BP_E(2, 0));  // (2, 0) not (0, 2).
>   I_double(2, 1) = ExtractDoubleOrThrow(I_BP_E(2, 1));  // (2, 1) not (1, 2).
> ```

BTW, out of scope so feel free to disregard: why don't we use something like 

`const Matrix3<double>& I_double = math::DiscardGradient(I_BP_E);` here?



_Code quote:_
```cpp
  const Matrix3<T>& I_BP_E = get_matrix();
  Matrix3<double> I_double = Matrix3<double>::Constant(NAN);
  I_double(0, 0) = ExtractDoubleOrThrow(I_BP_E(0, 0));
  I_double(1, 1) = ExtractDoubleOrThrow(I_BP_E(1, 1));
  I_double(2, 2) = ExtractDoubleOrThrow(I_BP_E(2, 2));

  // Since the inertia matrix is symmetric, only the lower-triangular part of
  // the matrix is used (its upper-triangular elements are NaN).
  I_double(1, 0) = ExtractDoubleOrThrow(I_BP_E(1, 0));  // (1, 0) not (0, 1).
  I_double(2, 0) = ExtractDoubleOrThrow(I_BP_E(2, 0));  // (2, 0) not (0, 2).
  I_double(2, 1) = ExtractDoubleOrThrow(I_BP_E(2, 1));  // (2, 1) not (1, 2).
```
___
*[`multibody/tree/rotational_inertia.cc` line 129 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7SJM-3ApV86gqFv_w:-NZ7SJM-3ApV86gqFv_x:bk4lbt3) ([raw file](https://github.com/RobotLocomotion/drake/blob/02cf116af4b2fe8481a5ce70c44c83baaa713a62/multibody/tree/rotational_inertia.cc#L129)):*
> ```cpp
>     // I_BP_A = | 0  Imed  0 | = J | 0  1  0 |  where J ≈ Imin ≈ Imed ≈ Imax.
>     //          ⎣ 0    0 Imax⎦     ⎣ 0  0  1 ⎦
>     // We show: I_BP_E = I_BP_A, where E is any right-handed orthonormal basis.
> ```

nit, all equality here should be ≈.



_Code quote:_
```cpp
    //          ⎡Imin  0   0 ⎤     ⎡ 1  0  0 ⎤
    // I_BP_A = | 0  Imed  0 | = J | 0  1  0 |  where J ≈ Imin ≈ Imed ≈ Imax.
    //          ⎣ 0    0 Imax⎦     ⎣ 0  0  1 ⎦
    // We show: I_BP_E = I_BP_A, where E is any right-handed orthonormal basis.
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
Ready for another look (assuming it passes CI).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZ937iZA3_qDIUxqFC-:b-vnt8gf)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7SShdD6730MVQnNq9:-NZ8bLvE37wUMgkg42Ob:bi1h8r1) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This PR adds a lot of complexity to a function with no change in documented behavior. That left me wondering about the purpose of the change. The change in implementation is aimed at providing a canonical set of principal directions, but the documentation of the function doesn't promise unique principal directions for equivalent inertia. 

The newly added tolerance for determining whether a matrix is diagonal is also a little suspicious. The eigenvalue solver already performs a similar check under the hood. Are we certain that the hand-crafted checks actually provide additional value?

It seems to me this function should be as simple as performing an eigendecomposition and potentially flipping the last column of the eigenvectors to ensure right handedness. To be convinced of this PR, I'd like to see some evidence on

1. this function used in performance critical code to justify the extra work (and potentially discontinuity) introduced by the diagonal special case;
2. the value of a canonical set of principal directions in an application.
</blockquote></details>

Thank you for taking copious time to discuss this f2f.  Comments have been updated to help clarify some of the issues that are raised, including the long legacy of the is_diagonal check and why it may be useful in many situations (for primitives). 

To address this comment:
"The newly added tolerance for determining whether a matrix is diagonal is also a little suspicious. The eigenvalue solver already performs a similar check under the hood. Are we certain that the hand-crafted checks actually provide additional value?"

The following comment was added:
  // Note: It seems reasonable to guess that an inertia tolerance based on known 
  // properties of moment and product of inertia are generally better than 
  // generic matrix tolerances used in Eigen's eigenvalue solver.

This PR is a first step in providing a canonical set of principal directions.  It addresses the "principal of minimal astonishment" for a rotational inertia that is (for practical purposes) triaxially symmetric (i.e., all the principal moments of inertia are equal or within a tiny tolerance of equal).  For that case, the returned rotation matrix is the identity matrix. 

Concomitantly, for now, the documentation in RotationalInertia::CalcPrincipalMomentsAndAxesOfInertia() only claims that if all 3 principal moments of inertia are equal, the returned rotation matrix R_EP is the identity matrix.  The other two cases will be addressed if it seems useful to have a canonical set of principal directions. Currently, I think "canonical" directions are used in drawing an ellipsoid to represent a body's mass distribution.

___
___
*[`multibody/tree/rotational_inertia.cc` line 123 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7NTXjDMabb58NNGxU:-NZ8_5HXAavZR0HxxjKG:byu6mf5) ([raw file](https://github.com/RobotLocomotion/drake/blob/70068bf3f6253a093d124759ac69cef3cdfb3bb1/multibody/tree/rotational_inertia.cc#L123)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, Why is this case not already handled in the diagonal case? The tolerance added in this PR muddies the water a bit, but without it, if Imax==Imin, then we should have already treated this case in the diagonal case above?
</blockquote></details>

Added a comment to highlight why this is needed.
___
*[`multibody/tree/rotational_inertia.cc` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7BSkmCxqVhW3ffUbm:-NZ8Nyks8s5lodOGoaEh:b-ldvxn7) ([raw file](https://github.com/RobotLocomotion/drake/blob/02cf116af4b2fe8481a5ce70c44c83baaa713a62/multibody/tree/rotational_inertia.cc#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, out of scope so feel free to disregard: why don't we use something like 

`const Matrix3<double>& I_double = math::DiscardGradient(I_BP_E);` here?
</blockquote></details>

Done.  Changed the code deals with the entire matrix in a single line.
___
*[`multibody/tree/rotational_inertia.cc` line 129 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-NZ7SJM-3ApV86gqFv_w:-NZ8aQfD3wUThQUIgaQm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/02cf116af4b2fe8481a5ce70c44c83baaa713a62/multibody/tree/rotational_inertia.cc#L129)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, all equality here should be ≈.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZap1858rGVg2vHX-aA:b-cxwtpw)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19656#-:-NZblhevBbWjrTfV8vSH:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform)

**Pull request merged**
