### PR TITLE
Add hash and divide to GenericPolynomial.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@soonho-tri for feature review please, thanks!

To reviewers: I would recommend to review the difference between r1 and the latest revision. From the base to r1 it just moves the code from Polynomial class to GenericPolynomial class. The later revisions made actual changes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100#-:-MHh6jVjATFhG6R7QLLR:bqadqhw)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm: 

+@SeanCurtis-TRI for platform-review, please.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100#-:-MHlhmH8BjjgyknLzcNq:b415d7a)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[common/symbolic_generic_polynomial.h, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlKFEl3UG_xeVh9Tnf:-MHlKFEl3UG_xeVh9Tng:bk46pz8) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L104)):*
> ```objc
>   /** Sets the indeterminates to `new_indeterminates`.
>    *
>    * Changing the indeterminates would change `monomial_to_coefficient_map()`,
> ```

`monomial_to_coefficient_map()` => `basis_element_to_coefficient_map`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @soonho-tri)

___
*[common/symbolic_generic_polynomial.h, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlKFEl3UG_xeVh9Tnf:-MHlyBHT26XrOUGAp126:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L104)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`monomial_to_coefficient_map()` => `basis_element_to_coefficient_map`
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
A few typos, few suggestions, and a request to clarify the testing strategy.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100#-:-MHmCUWwBHlxzjK_gUGq:b-ovwui2)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[common/symbolic_generic_polynomial.h, line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHmAziBEq4d-18ebrV5:-MHmAziBEq4d-18ebrV6:b-q2lvsv) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L102)):*
> ```objc
>   }
> 
>   /** Sets the indeterminates to `new_indeterminates`.
> ```

BTW Based on the tests, it seems there's a semantic significance that would be worthwhile to underscore. The effect of calling this is like constructing a new polynomial from *this* polynomial's *expression*, but with the new indeterminates.
___
*[common/symbolic_generic_polynomial.h, line 104 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlKFEl3UG_xeVh9Tnf:-MHlo-Gk2apuH1uTkARO:bwy6712) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L104)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also not clear that "would" is the right word. Surely "will" should be preferred. (With particular emphasis that the statement "Changing the indeterminates" is not synonymous with "calling this function".)
___
*[common/symbolic_generic_polynomial.h, line 108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHloH3w1SATPmaxDJ7C:-MHloH3w1SATPmaxDJ7D:be56it4) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L108)):*
> ```objc
>    *
>    * @code
>    * // p is a quadratic polynomial with x being the indeterminates.
> ```

nit Perhaps better phrased as:

"...with x as the only indeterminate."
___
*[common/symbolic_generic_polynomial.h, line 253 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHloosj-qDOM5pUbThS:-MHloosj-qDOM5pUbThT:b-iizj30) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L253)):*
> ```objc
>   Formula operator!=(const GenericPolynomial<BasisElement>& p) const;
> 
>   /** Implements the @ref hash_append concept.*/
> ```

nit Probably a missing space between "." and "*/".
___
*[common/symbolic_generic_polynomial.h, line 259 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlpgvR5wvcFTzPYhEu:-MHlpgvR5wvcFTzPYhEv:b3pmhu6) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.h#L259)):*
> ```objc
>       const GenericPolynomial<BasisElement>& item) noexcept {
>     using drake::hash_append;
>     for (const auto& p : item.basis_element_to_coefficient_map_) {
> ```

BTW You could apply structured binding here something like:

```c++
for (const auto& [basis_element, coefficient] : 
    item.basis_element_to_coefficient_map_) {
  hash_append(hasher, basis_element);
  hash_append(hasher, coefficient);
}
```
___
*[common/symbolic_generic_polynomial.cc, line 675 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlyabU3TgbgChqdLVX:-MHlyabU3TgbgChqdLVY:bcwxg1m) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.cc#L675)):*
> ```cpp
> GenericPolynomial<BasisElement>& GenericPolynomial<BasisElement>::operator/=(
>     double c) {
>   for (auto& item : basis_element_to_coefficient_map_) {
> ```

BTW Another case to consider structured binding -- `coefficient /= c` reads better than `item.second /= c`. However, because you don't use the basis element it would require an `unused()`. So, I merely suggest the possibility in passing.
___
*[common/symbolic_generic_polynomial.cc, line 837 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHm9OKxBQ5MA0cSITy5:-MHm9OKy9hrbLDzYgYt9:b-egl0zy) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.cc#L837)):*
> ```cpp
>        diff.basis_element_to_coefficient_map_) {
>     const Expression& coeff{item.second};
>     ret = ret && (coeff == 0.0);
> ```

BTW Presumably, this isn't subject to the normal C++ tricks of `bool expression && bool expression` where a `false` value for the first expression precludes evaluation of the second expression, yes? If so, probably worth noting here.
___
*[common/test/symbolic_generic_polynomial_test.cc, line 1735 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHmBKrNAfWSYdXLBall:-MHmBKrNAfWSYdXLBalm:b-yzp8x4) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/test/symbolic_generic_polynomial_test.cc#L1735)):*
> ```cpp
> 
>   {
>     // {x, a} -> {x}
> ```

I'm really no clear on the significance on this particular collection of test cases.
I'd characterize the tests you have as:

1. Grow the set of indeterminates with an existing variable.
2. Grow the set of indeterminates with a new variable.
3. Shrink the indeterminates by removing a single variable. (This happens twice.)
4. Shrink the indeterminates by removing multiple variables.

So, you've got number 3 twice and number four once. Number four doesn't seem particularly more interesting than 3. (And if it is interesting, how come we didn't *grow* the set by multiple variables?)

Can you comment on the significance of *this* set of cases or clean them up?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @soonho-tri)

___
*[common/symbolic_generic_polynomial.cc, line 675 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHlyabU3TgbgChqdLVX:-MHmMaYv7m_dlwoRKKjx:b-i5a7gb) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.cc#L675)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Another case to consider structured binding -- `coefficient /= c` reads better than `item.second /= c`. However, because you don't use the basis element it would require an `unused()`. So, I merely suggest the possibility in passing.
</blockquote></details>

Thanks, I will dismiss this.
___
*[common/symbolic_generic_polynomial.cc, line 837 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHm9OKxBQ5MA0cSITy5:-MHmVSwa7gTUEDDn4wik:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/symbolic_generic_polynomial.cc#L837)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Presumably, this isn't subject to the normal C++ tricks of `bool expression && bool expression` where a `false` value for the first expression precludes evaluation of the second expression, yes? If so, probably worth noting here.
</blockquote></details>

Done
___
*[common/test/symbolic_generic_polynomial_test.cc, line 1735 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHmBKrNAfWSYdXLBall:-MHmW_136EBfNZsL96-Y:b-ewbwtg) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6ee47288c058b5aa3a4ede6c49943ca1ca72c3/common/test/symbolic_generic_polynomial_test.cc#L1735)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm really no clear on the significance on this particular collection of test cases.
I'd characterize the tests you have as:

1. Grow the set of indeterminates with an existing variable.
2. Grow the set of indeterminates with a new variable.
3. Shrink the indeterminates by removing a single variable. (This happens twice.)
4. Shrink the indeterminates by removing multiple variables.

So, you've got number 3 twice and number four once. Number four doesn't seem particularly more interesting than 3. (And if it is interesting, how come we didn't *grow* the set by multiple variables?)

Can you comment on the significance of *this* set of cases or clean them up?
</blockquote></details>

I don't think it is significant for test 4. But it doesn't hurt with more tests. I also added a test to grow the set of indeterminates with multiple variables.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one typo, I think.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100#-:-MHmb5WJ7L_B_MaRY0qo:b7cs9hs)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[common/symbolic_generic_polynomial.h, line 121 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14100#-MHmaa94-oUJIhZ3nJ0O:-MHmaa94-oUJIhZ3nJ0P:b-77ygi) ([raw file](https://github.com/robotlocomotion/drake/blob/3ccfb9e1524e11e6198c417369d8983e89bdf1cb/common/symbolic_generic_polynomial.h#L121)):*
> ```objc
>    * @endcode
>    * This function can be expensive, as it potentially reconstructs the
>    * polynomial (using the new indeterminates) from the expression.V
> ```

nit: Is "V" a typo?

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14100)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Pull request merged**
