### PR TITLE
doc: Add release notes v0.26.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review (at least, for the code changes outside of the v0.26 doc itself; if you'd like to tap platform on-call for a review of the v0.26 proper text instead of you, we can do that).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
non-notes changes :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545#-:-MRVmD5M0aSszuIUfoUW:bjbskxf)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for proofreading of the notes text, per schedule please.

There will be a few small edits to add new changes later today or tomorrow morning, but the majority of the text should be done now.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545#-:-MRW-RrU-2dHBfwenjR-:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/release_notes/v0.26.0.rst, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14545#-MRWdaaA6p3jrI5TRj6n:-MRWdaaB6BbAlaHyMTKF:b-9tpusq) ([raw file](https://github.com/robotlocomotion/drake/blob/84386ee42baa40f7f5fe7abf5275f9846dcf6bfb/doc/release_notes/v0.26.0.rst#L12)):*
> ```reStructuredText
> 
>   * To insulate your code from this change, we now offer a C++ alias
>     ``drake::geometry::DrakeVizualierd`` (i.e., with a "d" suffix) that matches
> ```

nit: Vizualierd -> Visualizerd

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14545)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
