### PR TITLE
Install vector.h

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This fixes the ROS build (and any other downstream consumers of Drake).
Follow-up to #3032.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3039)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
@david-german-tri for platform review, please -- since he and I were the two who missed this in #3032.

**Comment by jwnimmer-tri** [comment]
I am having trouble seeing whether the error in `linux-gcc-experimental-ros` is just CDash blowing up, or if there is something more serious going on.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3039#-:-KOG3JcWIT6Skg_G5sSW:1417088721)*

**Comment by jwnimmer-tri** [comment]
The only outstanding build is linux-matlab.  Using override-merge.

**Comment by liangfok** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3039#-:-KOGJS4D29v62cWCO5AP:1417088721)*

**Pull request merged**
