### PR TITLE
update AddL2NormCost docs

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for review.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvHYT3O36qPxJGXsin8:brz1e44)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-NvHYEUU4_1DerLO6JsR:-NvHYEUU4_1DerLO6JsS:b-newmo7) ([raw file](https://github.com/RobotLocomotion/drake/blob/87906444b649874066dbe9edefe8b5cf9bff9bf9/solvers/mathematical_program.h#L1162)):*
> ```objc
>    * @note Currently kL2NormCost is supported by the non-linear solvers
>    * SnoptSolver and IpoptSolver as well as the convex solvers Gurobi, Mosek,
>    * Clarabel, and SCS.
> ```

So, are there solvers that *don't* support `kL2NormCost`? I lack sufficient context to fully understand the significance of what this list communicates.
___
*[`solvers/mathematical_program.h` line 1194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-NvHY6Mr2BLWWbRDx0NK:-NvHY6Mr2BLWWbRDx0NL:b74xz3t) ([raw file](https://github.com/RobotLocomotion/drake/blob/87906444b649874066dbe9edefe8b5cf9bff9bf9/solvers/mathematical_program.h#L1194)):*
> ```objc
>    * on `s`, and `lorentz_cone_constraint` is the constraint s≥|Ax+b|₂
>    */
>    // TODO(hongkai.dai) Decide whether to deprecate this.
> ```

nit: This todo has to go *before* the `/** */` comment. Putting anything between the `/** */` comment and the function declaration breaks the automatic python documentation generation.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/mathematical_program.h` line 1162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-NvHYEUU4_1DerLO6JsR:-NvHZ7KoCD89GNWKlnwB:by218yw) ([raw file](https://github.com/RobotLocomotion/drake/blob/87906444b649874066dbe9edefe8b5cf9bff9bf9/solvers/mathematical_program.h#L1162)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

So, are there solvers that *don't* support `kL2NormCost`? I lack sufficient context to fully understand the significance of what this list communicates.
</blockquote></details>

This is correct. The only solvers which support this are the ones listed above.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-NvHYEUU4_1DerLO6JsR:-NvHd96ZAyhGjY5lHL_r:bkjifkh) ([raw file](https://github.com/RobotLocomotion/drake/blob/87906444b649874066dbe9edefe8b5cf9bff9bf9/solvers/mathematical_program.h#L1162)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is correct. The only solvers which support this are the ones listed above.
</blockquote></details>

This is where my ignorance enters in. Drake supports ten solvers, this lists six of them. The way its phrased suggests that the listed categories (non-linear/convex) are somehow *correlated* with support of the cost. That further implies that the missing solvers: CLP, CSDP, OSQP, and NLopt are neither non-linear nor convex solvers.

I'm largely ignorant of the solvers. However, its pretty apparent that NLopt is a non-linear solver. So, regardless of whether the other three qualify as "convex", NLopt is enough to suggest that the categories are *not* dispositive for predicting support.

So, a few questions: 

1. Do those categories directly contribute to support for this cost? And do the omitted solvers belong to different categories?
    - If so, we're done and this documentation is phrased perfectly and you can happily ignore the remaining questions. But I already suspect the answer here is "no".
2. If the answer to (1) is "no", is there some other unifying property/category that distinguishes between the solvers that support this cost and those that don't?
    - If so, let's use *that* property instead of non-linearity and convexity.
    - If not, we shouldn't imply correlation between property/category and support by listing categories unhelpfully. It'd be better to simply enumerate the solvers. We can assume anyone who cares about this documentation knows which solver they're using and why they're using it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvHgDj2DWztcclc0ctZ:bdl0rty)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvHkjIZD-EfopBv4sx3:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/mathematical_program.h` line 1162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-NvHYEUU4_1DerLO6JsR:-NvHkX53B06w0w4P28gg:b-e67xi7) ([raw file](https://github.com/RobotLocomotion/drake/blob/87906444b649874066dbe9edefe8b5cf9bff9bf9/solvers/mathematical_program.h#L1162)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is where my ignorance enters in. Drake supports ten solvers, this lists six of them. The way its phrased suggests that the listed categories (non-linear/convex) are somehow *correlated* with support of the cost. That further implies that the missing solvers: CLP, CSDP, OSQP, and NLopt are neither non-linear nor convex solvers.

I'm largely ignorant of the solvers. However, its pretty apparent that NLopt is a non-linear solver. So, regardless of whether the other three qualify as "convex", NLopt is enough to suggest that the categories are *not* dispositive for predicting support.

So, a few questions: 

1. Do those categories directly contribute to support for this cost? And do the omitted solvers belong to different categories?
    - If so, we're done and this documentation is phrased perfectly and you can happily ignore the remaining questions. But I already suspect the answer here is "no".
2. If the answer to (1) is "no", is there some other unifying property/category that distinguishes between the solvers that support this cost and those that don't?
    - If so, let's use *that* property instead of non-linearity and convexity.
    - If not, we shouldn't imply correlation between property/category and support by listing categories unhelpfully. It'd be better to simply enumerate the solvers. We can assume anyone who cares about this documentation knows which solver they're using and why they're using it.
</blockquote></details>

My reasoning was that the SnoptSolver and IpoptSolver solvers support L2NormCost **because** they are non-linear solvers (though I haven't looked into why NLopt doesn't). The convex solvers don't natively handle L2NormCosts but can be made to support it, as is now the case for our interfaces for Gurobi, Mosek, Clarabel, and SCS. 

I changed the documentation to enumerate the solvers that **do** support L2NormCost.

**Comment by jwnimmer-tri** [comment]
FYI https://drake.mit.edu/doxygen_cxx/group__solvers.html has our canonical tables of solver capabilities.  I haven't looked in detail, but possibly this information belongs there also / instead.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd started there. That call depends on understanding the semantics of costs and constraints. Do they generally apply straight across the board or is it patchwork support? If patchwork, it has always been that way and that page hasn't bothered documenting it and I don't see that this documentation changes anything.

If, however, it's generally been supported and this one cost is the exception, that might be worth adding.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvHvRaxClKIMCg7KF8W:b-qxk13x)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
`L2NormCost` sits in a bit of a weird place. Most people **think** of the `L2Norm` as being convex and so expect that adding it to the program will result in a convex solver being called. However, handling the `L2Norm` using a convex solver requires a bit of backend work, and so originally we did not handle this case, hence the documentation that only certain non-convex solvers supported the cost (see also #20552).

As far as I can tell, the `L2NormCost` is the only cost that has the special case handling.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvJ4a-u8OdGgIo3AREM:b-mwwu4r)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Sounds good to me.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvXPYe51vtrRR0i0UuX:b-ba7jcz)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21299#-:-NvXPog43fNBPJwNCDut:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
