### PR TITLE
Added Doxygen Comments To RigidBodyLoop and RigidBodyActuator

### PR DESCRIPTION
**Pull request by liangfok**
I believe these descriptions are correct but would like others to confirm.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2901)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please since this touches `RigidBody*`.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNNBzg6O9yaYaWmvvse:-902202037)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNSQlF6aJ3m6B5kfc3Z:-KNSQlF6aJ3m6B5kfc3_:216587966) ([raw file](https://github.com/robotlocomotion/drake/blob/8596bab92eb963390a0d72a159de48a02061f3c6/drake/systems/plants/rigid_body_actuator.h#L11)):*
> ```objc
> 
> /**
>  * Defines certain properties of an actuator that operates on a joint.
> ```

It not only defines properties but an actual physical actuator. IMO the doc should reflect this.
Rephrase to something like: "Class representing an actuator like a for instance an electric motor operating on a joint."

---

*[drake/systems/plants/rigid_body_actuator.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNSSgFValU-UhQbRM6q:-KNSSgFValU-UhQbRM6r:2002072896) ([raw file](https://github.com/robotlocomotion/drake/blob/8596bab92eb963390a0d72a159de48a02061f3c6/drake/systems/plants/rigid_body_actuator.h#L29)):*
> ```objc
>    * @param[in] reduction_in The gear reduction ratio of the actuator.
>    *
>    * @param[in] effort_limit_min_in The actuator's minimum effort limit. This
> ```

I would remove the second sentence. This is not assuming the actuation is on effort. Actuation from the physics engine point of view is **always** effort. This will be even true if your control strategy passes say, angles directly. In that case you will have a small PI loop with an encoder controlling the actuator's torque given your target angle. 
What I am trying to say is that `Actuator` here represents something like an electric motor that transmits mechanical effort through its shaft (linear actuators are also be allowed). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL @amcastro-tri . Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNSQlF6aJ3m6B5kfc3Z:-KNT1YqH6F4R_KLU72Gk:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8596bab92eb963390a0d72a159de48a02061f3c6/drake/systems/plants/rigid_body_actuator.h#L11)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> It not only defines properties but an actual physical actuator. IMO the doc should reflect this.
> Rephrase to something like: "Class representing an actuator like a for instance an electric motor operating on a joint."
</details>
Done.

---

*[drake/systems/plants/rigid_body_actuator.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNSSgFValU-UhQbRM6q:-KNT1lPnN9q_w2rr40Av:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/8596bab92eb963390a0d72a159de48a02061f3c6/drake/systems/plants/rigid_body_actuator.h#L29)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would remove the second sentence. This is not assuming the actuation is on effort. Actuation from the physics engine point of view is **always** effort. This will be even true if your control strategy passes say, angles directly. In that case you will have a small PI loop with an encoder controlling the actuator's torque given your target angle. 
> What I am trying to say is that `Actuator` here represents something like an electric motor that transmits mechanical effort through its shaft (linear actuators are also be allowed). 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNT1tVyLllkzayYtvrQ:-611603276)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNXZUGjBlfflcEMTVhg:1417088721)*

**Comment by liangfok** [comment]
Thanks! +@sherm1 for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNX_77-G1bPcY5hpM3T:790985146)*

**Comment by sherm1** [comment]
Platform review pass done -- PTAL.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXzyLz4UbYUzGPjSi1:-KNXzyM-51_KAvkV7IGG:1625343609) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L16)):*
> ```objc
>  * For more information, see:
>  *  - http://wiki.ros.org/urdf/XML/Transmission#A.3Ctransmission.3E_Elements
>  *  - http://sdformat.org/spec?ver=1.6&elem=joint
> ```

These references are to ROS/Gazebo documents that don't apply here. The URDF transmission element has many features that can't be represented here (e.g. "hardware interface", multiple joints/actuators), as does the SDF joint specification (e.g. "gearbox"). I think a user trying to understand Drake's RigidBodyActuator would be confused by these references. Please remove. 

---

*[drake/systems/plants/rigid_body_actuator.h, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY-p8EzfznRzqozqlP:-KNY-p8EzfznRzqozqlQ:-2065790523) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L32)):*
> ```objc
>    * @param[in] effort_limit_min_in The actuator's minimum effort limit.
>    *
>    * @param[in] effort_limit_max_in The actuator's maximum effort limit.
> ```

Can you describe the units for the effort limits (are they in generalized forces units as defined by the joint?) Also, what happens if the joint has more than one dof? Is RBActuator limited to 1-dof joints?

---

*[drake/systems/plants/rigid_body_actuator.h, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E:-KNXymWyP7H-j3K9N1_F:690608443) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L38)):*
> ```objc
>       double reduction_in = 1.0,
>       double effort_limit_min_in = -std::numeric_limits<double>::infinity(),
>       double effort_limit_max_in = std::numeric_limits<double>::infinity());
> ```

It's not appropriate for the `_in` suffix (which is an internal trick) to leak into the user documentation for the API. The names here should be `name`, `body`, `reduction`, etc. If you want to call them something else in the implementation, that's fine!

---

*[drake/systems/plants/rigid_body_loop.h, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1OCYAdsdY64D4AHt:-KNY1OCYAdsdY64D4AHu:1815269243) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L9)):*
> ```objc
> 
> /**
>  * Defines a special "loop joint" that models a kinematic loop formed by a chain
> ```

delete "special"

---

*[drake/systems/plants/rigid_body_loop.h, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0vqXkE44tVYTwdQv:-KNY0vqXkE44tVYTwdQw:-656778456) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L14)):*
> ```objc
>  * objects. The coordinate frames defined by the two `RigidBodyFrame` objects
>  * are constrained to be in the same in terms of both position and orientation,
>  * which thus forms the loop joint.
> ```

This comment seems inconsistent with the one below. Here I think you are saying that the two frames are constrained to be coincident, meaning the loop joint is like a weld between the frames (6 constraints). Below, there is an "axis of rotation" indicating that the loop joint permits rotation about that axis (5 constraints). Please clarify.

---

*[drake/systems/plants/rigid_body_loop.h, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1dJmnW3vxR1okmlB:-KNY1dJmnW3vxR1okmlC:-534923613) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L20)):*
> ```objc
>   /**
>    * Constructs a kinematic loop by constraining the origins and orientations
>    * of two frames. The two frames are defined relative to two rigid bodies that
> ```

*Partially* constrains the orientation?

---

*[drake/systems/plants/rigid_body_loop.h, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1ZMIKWU29RXoLYvI:-KNY1ZMIKWU29RXoLYvJ:1815269243) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L21)):*
> ```objc
>    * Constructs a kinematic loop by constraining the origins and orientations
>    * of two frames. The two frames are defined relative to two rigid bodies that
>    * should be connected via a special loop joint.
> ```

delete "special"

---

*[drake/systems/plants/rigid_body_loop.h, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1kJdjel0HKpqYoLM:-KNY1kJdjel0HKpqYoLN:770025756) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L31)):*
> ```objc
>    * @param[in] axis_in The loop joint's axis of rotation. The loop joint's
>    * coordinate frame is equal to the coordinate frame defined by
>    * @p frameA_in and @p frameB_in.
> ```

The second sentence doesn't make sense. But an important piece of information would be the frame in which the rotation axis is expressed. Do you know which frame that is?

---

*[drake/systems/plants/rigid_body_loop.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0YZTjOp8Pk4-rKdM:-KNY0YZTjOp8Pk4-rKdN:91545452) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L35)):*
> ```objc
>   RigidBodyLoop(std::shared_ptr<RigidBodyFrame> frameA_in,
>                 std::shared_ptr<RigidBodyFrame> frameB_in,
>                 const Eigen::Vector3d& axis_in);
> ```

Again the `_in` kludge should not show up in a user-visible API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNY2KaXEHMBsYZFhPJB:-842199122)*

**Comment by liangfok** [comment]
@sherm1 I addressed all comments. PTAL. Thanks!

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXzyLz4UbYUzGPjSi1:-KNY4eiC7qKI64-2-TvV:-966665738) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These references are to ROS/Gazebo documents that don't apply here. The URDF transmission element has many features that can't be represented here (e.g. "hardware interface", multiple joints/actuators), as does the SDF joint specification (e.g. "gearbox"). I think a user trying to understand Drake's RigidBodyActuator would be confused by these references. Please remove. 
</details>
Done (removed).

---

*[drake/systems/plants/rigid_body_actuator.h, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY-p8EzfznRzqozqlP:-KNY5C-bGsq77OwINOpq:1482422288) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Can you describe the units for the effort limits (are they in generalized forces units as defined by the joint?) Also, what happens if the joint has more than one dof? Is RBActuator limited to 1-dof joints?
</details>
Added units. Yes, they are generalized. I added a note to the description of the class saying the assumption is the actuator is a single DOF.

---

*[drake/systems/plants/rigid_body_actuator.h, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E:-KNY5NmkMBP1uLOsxeRT:2072747997) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> It's not appropriate for the `_in` suffix (which is an internal trick) to leak into the user documentation for the API. The names here should be `name`, `body`, `reduction`, etc. If you want to call them something else in the implementation, that's fine!
</details>
This was inherited from [what's on master](https://github.com/RobotLocomotion/drake/blob/539faa7bcb9e682b091f7ea388bca9c2133e2be4/drake/systems/plants/rigid_body_actuator.h#L13). I'm afraid if I change it in this PR, this PR will explode due to modifying publicly accessible mutable member variables. I've created the following issue to track this fix in a future PR.

https://github.com/RobotLocomotion/drake/issues/2922

---

*[drake/systems/plants/rigid_body_loop.h, line 9 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1OCYAdsdY64D4AHt:-KNY6PZeGJ9WcdLfDbse:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> delete "special"
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0vqXkE44tVYTwdQv:-KNY75TplDNRxqI27NuZ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This comment seems inconsistent with the one below. Here I think you are saying that the two frames are constrained to be coincident, meaning the loop joint is like a weld between the frames (6 constraints). Below, there is an "axis of rotation" indicating that the loop joint permits rotation about that axis (5 constraints). Please clarify.
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1dJmnW3vxR1okmlB:-KNY7O3r77VOAj5WLv7o:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> *Partially* constrains the orientation?
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1ZMIKWU29RXoLYvI:-KNY7R1kiOx12et8bgwE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> delete "special"
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1kJdjel0HKpqYoLM:-KNY7V5CPcBAJE7MjHK0:698544416) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The second sentence doesn't make sense. But an important piece of information would be the frame in which the rotation axis is expressed. Do you know which frame that is?
</details>
I _believe_ it does not matter which frame the axis of rotation is expressed in since the two frames are constrained to be the same.  I've updated to text to reflect this belief.

---

*[drake/systems/plants/rigid_body_loop.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0YZTjOp8Pk4-rKdM:-KNY6C_Pj9zR0u8ZgRpY:-1569051276) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Again the `_in` kludge should not show up in a user-visible API.
</details>
I'll address this in a future PR: 

https://github.com/RobotLocomotion/drake/issues/2922

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNY83929IvIOypEE96w:1661569327)*

**Comment by sherm1** [comment]
Another platform pass done -- PTAL.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E:-KNYGFSGm-y9zMQcIxJm:59594214) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L38)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This was inherited from [what's on master](https://github.com/RobotLocomotion/drake/blob/539faa7bcb9e682b091f7ea388bca9c2133e2be4/drake/systems/plants/rigid_body_actuator.h#L13). I'm afraid if I change it in this PR, this PR will explode due to modifying publicly accessible mutable member variables. I've created the following issue to track this fix in a future PR.
> 
> https://github.com/RobotLocomotion/drake/issues/2922
</details>
I don't understand your objection. Just change the names in the header file -- you don't have to change the implementation to match. These are just formal parameters -- the names don't mean anything to the compiler, just to the human reader.

---

*[drake/systems/plants/rigid_body_loop.h, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0vqXkE44tVYTwdQv:-KNYGd6Thv1qi0S8ZotU:-1858865829) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
I'm still not sure this is right. It suggests that the axis of rotation must be one of the three frame axes, but the signature of the method does not require that. It looks to me that the rotation axis can be any direction, in which case *none* of the orientation axes will remain aligned, although there will still only be 1 rotational DOF.

---

*[drake/systems/plants/rigid_body_loop.h, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1dJmnW3vxR1okmlB:-KNYGyO6NbUZ-uNPnx8S:1517052212) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
"Partially" should apply to the orientation only, the origins appear to be fully constrained to remain coincident.

---

*[drake/systems/plants/rigid_body_loop.h, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1kJdjel0HKpqYoLM:-KNYHBzJEhu_OLPZ83DQ:-1786815077) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L31)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I _believe_ it does not matter which frame the axis of rotation is expressed in since the two frames are constrained to be the same.  I've updated to text to reflect this belief.
</details>
That can't be right, Liang. The rotation axis is a physical property (meaning it affects actual motion). There are 3 measure numbers in that `axis_in` vector -- they have to be measured in some frame, and changing that frame would mean the direction of allowed rotation would change. It's true that the vector will remain fixed in both frames A and B, but it won't have the same measure numbers if expressed in one or the other.

---

*[drake/systems/plants/rigid_body_loop.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0YZTjOp8Pk4-rKdM:-KNYI0Sxyz-S8q3x5vFG:-1650268393) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L35)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'll address this in a future PR: 
> 
> https://github.com/RobotLocomotion/drake/issues/2922
</details>
Again, just change the names in the header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNYI6XFM3Cw7RTijeXM:46810457)*

**Comment by liangfok** [comment]
@sherm1 I addressed all comments. PTAL. Thanks!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E:-KNYIy-YOeqLftW9gCBU:-283895508) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't understand your objection. Just change the names in the header file -- you don't have to change the implementation to match. These are just formal parameters -- the names don't mean anything to the compiler, just to the human reader.
</details>
I changed the parameter names in #2923. This is to avoid conflicting with https://github.com/RobotLocomotion/drake/issues/2852.

---

*[drake/systems/plants/rigid_body_loop.h, line 14 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0vqXkE44tVYTwdQv:-KNYRMOBP5-zq26kX6X_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm still not sure this is right. It suggests that the axis of rotation must be one of the three frame axes, but the signature of the method does not require that. It looks to me that the rotation axis can be any direction, in which case *none* of the orientation axes will remain aligned, although there will still only be 1 rotational DOF.
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1dJmnW3vxR1okmlB:-KNYQTfzrLYT5LIsLMrE:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "Partially" should apply to the orientation only, the origins appear to be fully constrained to remain coincident.
</details>
Done.

---

*[drake/systems/plants/rigid_body_loop.h, line 31 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY1kJdjel0HKpqYoLM:-KNYQn0KFkWo66EFO2pk:2042390702) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L31)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> That can't be right, Liang. The rotation axis is a physical property (meaning it affects actual motion). There are 3 measure numbers in that `axis_in` vector -- they have to be measured in some frame, and changing that frame would mean the direction of allowed rotation would change. It's true that the vector will remain fixed in both frames A and B, but it won't have the same measure numbers if expressed in one or the other.
</details>
Done. I believe it's defined in `FrameA_in`'s coordinate frame.

---

*[drake/systems/plants/rigid_body_loop.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0YZTjOp8Pk4-rKdM:-KNYJijroHSjwEDcubDO:1815591437) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Again, just change the names in the header file.
</details>
Fixed in #2923.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNYRQz2w-EgOLCoTxBT:1661569327)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901)*

**Comment by liangfok** [comment]
@sherm1 ready for another platform review. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNXymWyP7H-j3K9N1_E:-KNYitEk28KK3jSmKn7C:-1183049648) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_actuator.h#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> So should #2923 go in first? If you want this one to go in you can just change the parameter names in the header file. That shouldn't conflict at all with #2923 or if it does the merge will be very easy. I don't want this one to go in with documentation for the wrong parameter names.
</details>
I updated the parameter names to not end with "_in".

---

*[drake/systems/plants/rigid_body_loop.h, line 35 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNY0YZTjOp8Pk4-rKdM:-KNYiweD8ICCmNvD9Ts-:506484320) ([raw file](https://github.com/robotlocomotion/drake/blob/92c3da48f823007949e31ae6152466e777581e13/drake/systems/plants/rigid_body_loop.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Let's land #2923 first then and merge, or you can change the names just in the header file here and we can merge this one first.
</details>
I changed the names in just the header files in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNYj04bX2Ss_n7qyvBt:699524337)*

**Comment by sherm1** [comment]
Platform: :lgtm:. Feel free to merge when CI is green.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNYjmhg1fU2y3Mp-glL:-1813096842)*

**Comment by liangfok** [comment]
CI is red due to https://github.com/RobotLocomotion/drake/issues/2924. I'm thus begging someone with bits to override merge this PR. @sherm1 do you have these bits? If not, maybe @david-german-tri?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-:-KNYoZjFtCpoIGNuFnzv:1429864318)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/rigid_body_actuator.h, line 13 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNYrbiS5zX-GeRMkqxH:-KNYrbiS5zX-GeRMkqxI:312699576) ([raw file](https://github.com/robotlocomotion/drake/blob/37c7bba50940c2f8ff55e5ff648af5f2c315ec3b/drake/systems/plants/rigid_body_actuator.h#L13)):*
> ```objc
>  public:
>   RigidBodyActuator(
>       const std::string& name_in, const RigidBody* body_in,
> ```

There should be corresponding changes in the .cc files.

---

*[drake/systems/plants/rigid_body_loop.h, line 13 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNYre_REI9Lmn_Ahkix:-KNYre_REI9Lmn_Ahkiy:312699576) ([raw file](https://github.com/robotlocomotion/drake/blob/37c7bba50940c2f8ff55e5ff648af5f2c315ec3b/drake/systems/plants/rigid_body_loop.h#L13)):*
> ```objc
>   // Constructs a RigidBodyLoop between two frames. Is this the correct API?
>   // TODO(amcastro-tri): review the correctness of this API
>   RigidBodyLoop(std::shared_ptr<RigidBodyFrame> frameA_in,
> ```

There should be corresponding changes in the .cc files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 13 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNYrbiS5zX-GeRMkqxH:-KNYtNnWcX45gsIF2jZB:1110632599) ([raw file](https://github.com/robotlocomotion/drake/blob/37c7bba50940c2f8ff55e5ff648af5f2c315ec3b/drake/systems/plants/rigid_body_actuator.h#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> There should be corresponding changes in the .cc files.
</details>
I didn't make that change since it's being handled in #2923.

---

*[drake/systems/plants/rigid_body_loop.h, line 13 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNYre_REI9Lmn_Ahkix:-KNYtXqiGBUsuBmdhWSU:1110632599) ([raw file](https://github.com/robotlocomotion/drake/blob/37c7bba50940c2f8ff55e5ff648af5f2c315ec3b/drake/systems/plants/rigid_body_loop.h#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> There should be corresponding changes in the .cc files.
</details>
I didn't make that change since it's being handled in #2923.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_loop.h, line 13 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2901#-KNYre_REI9Lmn_Ahkix:-KNYuTbnCcOXsPa0xTKW:404001355) ([raw file](https://github.com/robotlocomotion/drake/blob/37c7bba50940c2f8ff55e5ff648af5f2c315ec3b/drake/systems/plants/rigid_body_loop.h#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I didn't make that change since it's being handled in #2923.
</details>
OK.  Ideally, it wouldn't also be here, but given that this PR is part of a whole fusillade let's not worry about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2901)*

**Pull request merged**
