### PR TITLE
[tutorials] Taking derivatives of MultibodyPlant with respect to mass

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@EricCousineau-TRI  for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-:-NVqEr8xEB1NBDlu8VGS:b-k00e1c)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @EricCousineau-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
Do we have a guidance how to review tutorials like this somewhere?
```
"Code review of tutorials is typically done either by running the tutorial locally and/or running it in deepnote. The interactive experience is what matters, not the json storage format of a notebook. Reviewable is used to discuss changes, but not actually read the "code" during a review."
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-:-NVqFDEg2yKCaFmCiTS-:b9vcqmy)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @DamrongGuoy and @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

I'm OK serving as platform too, if you'd like!

Yup! See https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-:-NW2kPMD-SfjPpYTyBm5:bs7tdue)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[`tutorials/index.ipynb` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-NW2kRvmCNJIEFPTXWWc:-NW2kRvmCNJIEFPTXWWd:b1xfgqy) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a298a745f5b232c9fa47f86a179a4029cc936d7/tutorials/index.ipynb#L28)):*
> ```
>     "- [PyPlot animation](./pyplot_animation_multibody_plant.ipynb)\n",
>     "- [Rendering MultibodyPlant](./rendering_multibody_plant.ipynb)\n",
>     "- [Taking Derivatives of MultibodyPlant Computations w.r.t. Mass](./multibody_plant_autodiff_mass.ipynb)\n",
> ```

nit Would you be OK narrowing your changes to only this line?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439)* status: needs at least two assigned reviewers

___
*[`tutorials/index.ipynb` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-NW2kRvmCNJIEFPTXWWc:-NW3Du4U4lhye53C7qUZ:b-x718sh) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a298a745f5b232c9fa47f86a179a4029cc936d7/tutorials/index.ipynb#L28)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'll try that.  I'm not sure how.  Any tips?  Jupyter just decided to change the other lines by itself without consulting me.  I do agree that we want to keep the changed lines minimal.
</blockquote></details>

Done.  Instead of Jupyter, I went into a text editor to keep the change to one line.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439)* status: 1 unresolved discussion, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-NW3Eh8dD4Fc8WNmvRx0:-NW3Eh8dD4Fc8WNmvRx1:b-1amk7j) (no related file):*
@EricCousineau-TRI Thanks for pointing to [tutorials/_developers.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md).

I'm not sure that I understand this part:

  - In the pull request overview, include a nbviewer link to the directory on your fork and branch, e.g., 
  - https://nbviewer.jupyter.org/github/{user}/drake/blob/{branch}/tutorials/

Is it like this?
https://nbviewer.jupyter.org/github/DamrongGuoy/drake/blob/tutorials_link_multibody_autodiff_mass/tutorials/

___

**Review by DamrongGuoy — COMMENTED** [review]
Provide nbviewer link:

- https://nbviewer.org/github/DamrongGuoy/drake/tree/tutorials_link_multibody_autodiff_mass/tutorials/

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-:-NW3GBoU8vEALNblpPm6:bj252ez)* status: 1 unresolved discussion

**Comment by EricCousineau-TRI** [comment]
Yup, perfect!
>

**Comment by EricCousineau-TRI** [comment]
*[`tutorials/index.ipynb` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19439#-NW2kRvmCNJIEFPTXWWc:-NW3GP7aCU34nC7-Dzcm:b-603ydj) ([raw file](https://github.com/RobotLocomotion/drake/blob/6a298a745f5b232c9fa47f86a179a4029cc936d7/tutorials/index.ipynb#L28)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  Instead of Jupyter, I went into a text editor to keep the change to one line.
</blockquote></details>

OK Thanks!

I would've recommend just amending your commit and either unstage all + stage hunks you want, or the converse (unstage what you don't want).

I normally use `git gui`, e.g. https://drakedevelopers.slack.com/archives/C0JNB2E3S/p1652193315716209
There are probably analogous ways with VS Code, or `tig` (https://github.com/jonas/tig), etc.

**Pull request merged**
