### PR TITLE
Port drake/manipulation to FindResource

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Relates #5893.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6438)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@siyuanfeng-tri feature review please. Thanks!

cc @jwnimmer-tri

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6438#-:-KneHJDI50fNceQeYLLv:b-m02nz2)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: wondering how come cmake is not affected at all? 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6438#-:-KneIaE4u9I0HD22EU6C:b-9kfyxb)*

**Comment by kunimatsu-tri** [comment]
Thanks @siyuanfeng-tri.

In CMake world, both `drake_path` and `find_resource` are in the same library, namely `drakeCommon`.
https://github.com/RobotLocomotion/drake/blob/master/drake/common/CMakeLists.txt#L94

+@sammy-tri platform review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6438#-:-KneJdVGtdKrFBUeNeoV:b-ij3iez)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6438#-:-KneojQoIYmtAoso5g5Y:bnfp4nl)*

**Pull request merged**
