### PR TITLE
[pydrake] Overhaul logging configuration

### LINKED ISSUE #16554: Don't redirect spdlog to Python logging when using embedded Python
When a user imports any `pydrake` module that uses native C++ code, for convenience we switch Drake's text logging to route messages into the python [logging](https://docs.python.org/3/library/logging.html) module, instead of printing directly to `std::cerr`.

This is especially useful for online Python notebooks, where `std::cerr` often is not visible to the user anywhere.

For reference, this is the code that implements the feature:

https://github.com/RobotLocomotion/drake/blob/ca94c5010600cadc30b9c9f5d2b4faa25f8e1a51/bindings/pydrake/common/text_logging_pybind.cc#L57-L64

The redirection makes sense when the `main()` program being run is a Python interpreter.  However, users sometimes choose to _embed_ the Python interpreter as a subroutine within their C++ program (e.g., for easy user-scripting, while leaving the bulk of the code in C++).  This kind of embedding has many sharp edges in general (and so, I always recommend against it).  However, if the user _is_ doing this, and is using `pydrake`, then it no longer makes sense to redirect to the python `logging` module; we should stick with C++ logging directly to `std::cerr` (or wherever the user sent spdlog to go).

Ideally, we could automatically detect whether we are embedded, and skip the redirect in that case.  Failing that, maybe we could offer some runtime configuration knob to opt-out of the redirection.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add a new function `pydrake.common.configure_logging()` that will set up a nice formatter style, somewhat like Drake C++ offers by default.

Don't perform metadata formatting (e.g., times and severities) in C++ when logging via Python. Allow the Python user's configuration to handle that.

Rewrite the unit test to be comprensive.

Update meldis to use the new infrastructure.

When pydrake's native code is being initialized, only re-route logging to Python if the C++ logging configuration is unchanged vs its defaults. If the user has customized C++ logging already, then don't change anything. This should only make any difference in the case of embedding pydrake as a scripting language. Closes #16554.

- [x] This PR depends on #16578 merging first, to we can use its efficient testing infrastructure.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3ijev773KCMabSkEX:-Mw3ijev773KCMabSkEY:b-yhdu7k) (no related file):*
Working

Needs extra testing on macOS, prior to merge.

---

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI please have a look (at minimum) at the commit message and any curiosities in the code it raises for you.  This changes our pydrake logger to rely more on Python's built-in logging module.  I'd welcome any design comments before I get busy with feature review.

You can decide if you'd like to continue through to feature review, or defer that to someone else.

**Review by EricCousineau-TRI — COMMENTED** [review]
Concept + approach seems good to me!

:lgtm: feature

> Reviewed 2 of 7 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577#-:-Mw3xgv67jQKCTpYTAQH:b-inzuec)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3xlc4BBFi6eTLGfUB:-Mw3xZafAIlElv0EqJq3:b-nk7ru0) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/__init__.py#L19)):*
> ```Python
>     is no requirement to call it prior to using Drake or generating messages.
>     We offer it as a convenience only because Python's logging defaults are
>     relatively unhelpful (e.g., they do not publish any message timestamps).
> ```

nit "relatively unhelpful" sounds a bit too opinionated. (I generally like less-noisy logging on console when possible).

Consider "defaults do not provide as much information"?
___
*[bindings/pydrake/common/__init__.py, line 24 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3xd507SDOlY1DJplZ:-Mw3xd507SDOlY1DJpl_:b-rikpic) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/__init__.py#L24)):*
> ```Python
>        :py:func:`pydrake.common.set_log_level`
>     """
>     import logging as _logging
> ```

nit Benefit from importing `logging` here is unclear.

Consider hoisting?
___
*[bindings/pydrake/common/text_logging_pybind.h, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3x7Ps8UB-Z14jTulC:-Mw3x7Ps8UB-Z14jTulD:b-du2kqk) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.h#L8)):*
> ```objc
> 
> /* If possible, redirects Drake's C++ logs to Python's `logging` module. */
> void RedirectPythonLogging();
> ```

nit Consider renaming to `MaybeRedirectPythonLogging()`?
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 112 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wGowAdkHfwCKwTx0:-Mw3wGowAdkHfwCKwTx1:b-2h55ro) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L112)):*
> ```cpp
>   }
> 
>   std::atomic<bool> is_configured_{false};
> ```

nit Unclear why thread-safety is attempted.

Is this thread-safe at all?
I assume not since it calls into Python w/o acquiring GIL?

(Consider adding TODO to testing - to bind a multi-threaded C++ function that logs in each thread?)
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 128 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wgP497YgZdjk7l4d:-Mw3wgP5DNtLvFk9gHMu:bpdifrc) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L128)):*
> ```cpp
>       drake::log()->sinks();
>   if (log_sinks.size() != 1) {
>     return;
> ```

nit When bailing, consider logging this result as debug / trace? e.g.
```
drake::log()->trace("Detected non-default spdlog sinks. Not adding a pydrake spdlog sink.");
```

Also, consider wrapping default-check logic into function, `IsDefautlConfigured()`, and printing the message then?
(or log specific messages otherwise)
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 148 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wsf129nj8KHXFCYg:-Mw3wsf129nj8KHXFCYh:b-w9s2z5) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L148)):*
> ```cpp
>   // Replace the stderr sink with a python sink.
>   auto python_sink = std::make_shared<pylogging_sink>();
>   dist_sink->set_sinks({python_sink});
> ```

nit Consider adding log statement here?
```
drake::log()->trace("Adding pydrake spdlog sink");
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/common/text_logging_pybind.cc, line 112 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wGowAdkHfwCKwTx0:-Mw4CDWbC1V1cY_25Kf6:btiub50) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L112)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why thread-safety is attempted.

Is this thread-safe at all?
I assume not since it calls into Python w/o acquiring GIL?

(Consider adding TODO to testing - to bind a multi-threaded C++ function that logs in each thread?)
</blockquote></details>

Interesting ... the `sink_it_` is called from Drake's C++ code, isn't it?

Usually our pybind-related code is wrapping a C function into Python, in which case pybind11 locks the GIL before calling us and we're easily safe.  Here, however, it's Drake C++ code posting into spdlog which calls into here.  I think usually the Drake C++ code would be running on behalf of a pydrake binding, so would have the GIL, but I suppose that isn't guaranteed.

Here, I was just threw in the atomic because I figured we don't know who is calling us, so might as well be safe.  I didn't consider the fact that calling `self.handle(...)` might not even be safe!

That isn't a new defect (lacking the GIL when posting log messages), but probably deserves some more thought.  Happy to hear any of your ideas.
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 128 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wgP497YgZdjk7l4d:-Mw4AyFa9r9JxarK3UH0:bb71pro) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L128)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit When bailing, consider logging this result as debug / trace? e.g.
```
drake::log()->trace("Detected non-default spdlog sinks. Not adding a pydrake spdlog sink.");
```

Also, consider wrapping default-check logic into function, `IsDefautlConfigured()`, and printing the message then?
(or log specific messages otherwise)
</blockquote></details>

PTAL

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/text_logging_pybind.cc, line 112 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wGowAdkHfwCKwTx0:-Mw4HFSt2QWcDunkjNyH:b-e34kqk) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Interesting ... the `sink_it_` is called from Drake's C++ code, isn't it?

Usually our pybind-related code is wrapping a C function into Python, in which case pybind11 locks the GIL before calling us and we're easily safe.  Here, however, it's Drake C++ code posting into spdlog which calls into here.  I think usually the Drake C++ code would be running on behalf of a pydrake binding, so would have the GIL, but I suppose that isn't guaranteed.

Here, I was just threw in the atomic because I figured we don't know who is calling us, so might as well be safe.  I didn't consider the fact that calling `self.handle(...)` might not even be safe!

That isn't a new defect (lacking the GIL when posting log messages), but probably deserves some more thought.  Happy to hear any of your ideas.
</blockquote></details>

Simplest thing is to just add TODO (esp. since it's pre-existing!)

Next simplest would be to write a stress test if we want to catch a potential issue ahead of us.

It may reveal we're OK, or need something like `gil_scoped_acquire` in `sink_it_()`:
https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil

I think by default that pybind11 will not acquire GIL when calling Python from C++ since it can be expensive. Code looks like it only checks for GIL on debug mode:
https://github.com/RobotLocomotion/pybind11/blob/5df3c002/include/pybind11/cast.h#L1543-L1552
(I also don't know exact interplay when dealing with GIL interlock among competing C++ threads)
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 128 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw4Gqum9iUeTzIErXnI:-Mw4Gqum9iUeTzIErXnJ:beusyks) ([raw file](https://github.com/robotlocomotion/drake/blob/8fb8a303486c7a472f6a69805d53c4d2d6b7de79/bindings/pydrake/common/text_logging_pybind.cc#L128)):*
> ```cpp
>       drake::log()->sinks();
>   if (log_sinks.size() != 1) {
>     drake::log()->debug("Cannot redirect C++ logs to Python (sinks != 1)");
> ```

nit "Cannot" doesn't seem accurate.

Perhaps "Will not" better reflects the situation? (user did something, we don't want to screw them up, even though we could)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/text_logging_pybind.cc, line 112 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw3wGowAdkHfwCKwTx0:-Mw5ER9y4QXiuOBBHZrk:b-j3fr4k) ([raw file](https://github.com/robotlocomotion/drake/blob/53ded7d293d08f278b170435c6e0e5913f7ea5bd/bindings/pydrake/common/text_logging_pybind.cc#L112)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Simplest thing is to just add TODO (esp. since it's pre-existing!)

Next simplest would be to write a stress test if we want to catch a potential issue ahead of us.

It may reveal we're OK, or need something like `gil_scoped_acquire` in `sink_it_()`:
https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil

I think by default that pybind11 will not acquire GIL when calling Python from C++ since it can be expensive. Code looks like it only checks for GIL on debug mode:
https://github.com/RobotLocomotion/pybind11/blob/5df3c002/include/pybind11/cast.h#L1543-L1552
(I also don't know exact interplay when dealing with GIL interlock among competing C++ threads)
</blockquote></details>

Done (via TODO).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: festival of nittery

> Reviewed 1 of 7 files at r1, 6 of 9 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577#-:-Mw90SAoA28UlkRYMejA:b-q5wpr3)* status: 6 unresolved discussions (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/__init__.py, line 28 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8veYo7R1aAsIAVUBe:-Mw8veYo7R1aAsIAVUBf:b-j50moa) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/__init__.py#L28)):*
> ```Python
>     format = "[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s"
>     _logging.basicConfig(level=_logging.INFO, format=format)
>     _logging.getLogger("drake").setLevel(_logging.NOTSET)
> ```

nit Not reached by unit tests (specifically //bindings/pydrake/common/...). Should I worry?
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8u4Xk4OKeahGt6GVT:-Mw8u4Xk4OKeahGt6GVU:bvh52tv) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/text_logging_pybind.cc#L44)):*
> ```cpp
> 
>  protected:
>   void sink_it_(const spdlog::details::log_msg& msg) final {
> ```

To quote a sage:

```
nit The argument here is probably not the is the sodium salt of glutamic acid.

"Do not abbreviate by deleting letters within a word."
-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
``
```




_Code quote:_
```cpp
msg
```
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 144 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8uLwaDZd2BK4RrIn7:-Mw8uLwaDZd2BK4RrIn8:b5cbrb8) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/text_logging_pybind.cc#L144)):*
> ```cpp
>   if (dist_sink == nullptr) {
>     drake::log()->debug(
>         "Will not redirect C++ logging to Python (no dist sink)");
> ```

I had to look up what the type `dist_sink_mt` was to understand that dist_sink contracts "distribution sink". Maybe fine for code, but possibly too inside-baseball for an error message.



_Code quote:_
```cpp
dist sink
```
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 167 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8xGKOCD1J10i_LnuI:-Mw8xGKOCD1J10i_LnuJ:b-724bsr) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/text_logging_pybind.cc#L167)):*
> ```cpp
>   drake::log()->trace("Successfully redirected C++ logs to Python");
> }
> #else
> ```

BTW, consider decorating the `#else` and `#endif` with comments, since they are far from the condition that they serve.
___
*[bindings/pydrake/common/test/text_logging_example.py, line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8sFVK5XnI5iMZ0JzY:-Mw8sFVK5XnI5iMZ0JzZ:beoxiu6) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_example.py#L14)):*
> ```Python
>         "--python_level", metavar="INT", type=int, required=True,
>         help="Set Python Drake logger to this level, or use 0 as a no-op.")
>     parser.add_argument(
> ```

BTW, I had to read source code to select values for this. Maybe it doesn't matter.

If it does, it's not a bad place to apply https://docs.python.org/3/library/argparse.html#choices .
___
*[bindings/pydrake/common/test/text_logging_example.py, line 31 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8qzKr2Sq3-J-Amx5S:-Mw8qzKr2Sq3-J-Amx5T:bfda1jm) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_example.py#L31)):*
> ```Python
>             logging.getLogger("drake").setLevel(logging.NOTSET)
>     else:
>         assert args.use_nice_format == 0
> ```

Should I worry?

```
rico@puget-161804-10:~/checkout/drake$ bazel run //bindings/pydrake/common:text_logging_example -- --spdlog_level_name=trace --python_level=0 --use_nice_format=1
INFO: Analyzed target //bindings/pydrake/common:text_logging_example (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //bindings/pydrake/common:text_logging_example up-to-date:
  bazel-bin/bindings/pydrake/common/text_logging_example
INFO: Elapsed time: 0.279s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/common/text_logging_example.runfiles/drake/bindings/pydrake/common/test/text_logging_example.py", line 43, in <module>
    main()
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/common/text_logging_example.runfiles/drake/bindings/pydrake/common/test/text_logging_example.py", line 31, in main
    assert args.use_nice_format == 0
AssertionError
```
BTW,  ` --python_level=-1 --use_nice_format=1` works fine.
___
*[bindings/pydrake/common/test/text_logging_test.py, line 111 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw9-VryE3Ue_0wZfGBT:-Mw9-VryE3Ue_0wZfGBU:b293ljk) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_test.py#L111)):*
> ```Python
>             pattern = r"\[.{23}\] \[drake\] \[(.*?)\] (.*)"
>         else:
>             pattern = r"(.*?):drake:(.*)"
> ```

nit kcov surprised me a few times in this file. Apparently this line is not reached? I won't swear kcov is not wrong, but the result didn't *look* obviously wrong.
___
*[bindings/pydrake/common/test/text_logging_test.py, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw9-dyS1MJuko3Ne15Q:-Mw9-dyTD6ihrY_6cdNb:bhtl53p) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_test.py#L135)):*
> ```Python
>         expected_levels = set()
>         if expected_level <= DRAKE_TRACE:
>             expected_levels.add("Level 5")
> ```

nit similarly, this branch and all the following through ERROR are reported not reached.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw97M8f7WyqVdZ2oFpg:-Mw97M8f7WyqVdZ2oFph:b-ty8oh8) (no related file):*
Oops.  ValueParameterizedTest seems to be running the final test configuration over and over again, instead of all of the permutations.  Stay tuned.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw97M8f7WyqVdZ2oFpg:-Mw99wtv0uloX2bsxqKQ:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  ValueParameterizedTest seems to be running the final test configuration over and over again, instead of all of the permutations.  Stay tuned.
</blockquote></details>

Done.

---
___
*[bindings/pydrake/common/__init__.py, line 28 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8veYo7R1aAsIAVUBe:-Mw9A73J7OSFDP9ILcgW:bifkwcr) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/__init__.py#L28)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Not reached by unit tests (specifically //bindings/pydrake/common/...). Should I worry?
</blockquote></details>

Reached now.
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8u4Xk4OKeahGt6GVT:-Mw94N5K7iB-u4HaxMBu:b-uy2bcf) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/text_logging_pybind.cc#L44)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

To quote a sage:

```
nit The argument here is probably not the is the sodium salt of glutamic acid.

"Do not abbreviate by deleting letters within a word."
-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
``
```

</blockquote></details>

I'll claim that staying true to upstream's API signature outweighs the abbreviation convention for first-party code.

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/sinks/base_sink.h#L36
___
*[bindings/pydrake/common/text_logging_pybind.cc, line 144 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8uLwaDZd2BK4RrIn7:-Mw9Asda5uwvgMQccxPk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/text_logging_pybind.cc#L144)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I had to look up what the type `dist_sink_mt` was to understand that dist_sink contracts "distribution sink". Maybe fine for code, but possibly too inside-baseball for an error message.
</blockquote></details>

Done.
___
*[bindings/pydrake/common/test/text_logging_example.py, line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8sFVK5XnI5iMZ0JzY:-Mw94cOy3rpy0jgKfb29:b7rwikn) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_example.py#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, I had to read source code to select values for this. Maybe it doesn't matter.

If it does, it's not a bad place to apply https://docs.python.org/3/library/argparse.html#choices .
</blockquote></details>

I'll call it sufficiently intertwined with the matching test code, such that duplicating the list of values here would be a net negative.  Maybe the new docs will help slightly.
___
*[bindings/pydrake/common/test/text_logging_example.py, line 31 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw8qzKr2Sq3-J-Amx5S:-Mw9BRiYAvM-f3dibKrp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_example.py#L31)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should I worry?

```
rico@puget-161804-10:~/checkout/drake$ bazel run //bindings/pydrake/common:text_logging_example -- --spdlog_level_name=trace --python_level=0 --use_nice_format=1
INFO: Analyzed target //bindings/pydrake/common:text_logging_example (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //bindings/pydrake/common:text_logging_example up-to-date:
  bazel-bin/bindings/pydrake/common/text_logging_example
INFO: Elapsed time: 0.279s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/common/text_logging_example.runfiles/drake/bindings/pydrake/common/test/text_logging_example.py", line 43, in <module>
    main()
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/common/text_logging_example.runfiles/drake/bindings/pydrake/common/test/text_logging_example.py", line 31, in main
    assert args.use_nice_format == 0
AssertionError
```
BTW,  ` --python_level=-1 --use_nice_format=1` works fine.
</blockquote></details>

Done.
___
*[bindings/pydrake/common/test/text_logging_test.py, line 111 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw9-VryE3Ue_0wZfGBT:-Mw9ANHhCjYeQTs7JWbw:bifkwcr) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_test.py#L111)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit kcov surprised me a few times in this file. Apparently this line is not reached? I won't swear kcov is not wrong, but the result didn't *look* obviously wrong.
</blockquote></details>

Reached now.
___
*[bindings/pydrake/common/test/text_logging_test.py, line 135 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16577#-Mw9-dyS1MJuko3Ne15Q:-Mw9AP3U8BuTO4voZ-OA:bifkwcr) ([raw file](https://github.com/robotlocomotion/drake/blob/4be4a015ac4960f027875e84c07924a8dfa37f0f/bindings/pydrake/common/test/text_logging_test.py#L135)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit similarly, this branch and all the following through ERROR are reported not reached.
</blockquote></details>

Reached now.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16577)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
