### PR TITLE
Fixed off by one error in MakeMononomialUnique, added test

### PR DESCRIPTION
**Pull request by jefesaurus**
Running that test before this change fails with 4 coefficients because MakeMononomialsUnique was skipping the last term comparison in each inner loop.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4851)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@jefesaurus -- i sent you an invite to get you on the build server whitelist (so that jenkins stops spamming you/us).  let me know if I need to resend.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  test this please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb38wyoAxXkqZUwQut0:bt2zp4j)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb39B0SxEjMFLK7MPTK:b-fcupkv)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb39MyHbyxYvsufS8IW:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@russtedrake for platform review.
:lgtm except minor change.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/polynomial_test.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb3A6-bhIvURHdCq7hY:-Kb3A6-bhIvURHdCq7hZ:b15oao0) ([raw file](https://github.com/robotlocomotion/drake/blob/2d551919edcd66d1e5e3f20e88350a193cba2b7c/drake/common/test/polynomial_test.cc#L185)):*
> ```cpp
> 
> GTEST_TEST(PolynomialTest, TestMakeMonomialsUnique) {
>   VectorXd coefficients(2);
> ```

Prefer `Vector2d coefficients{}` to `VectorXd` to avoid dynamic memory allocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb3AVy4i47vGHTMPAeI:b-lspexl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb3AetbvPuRJekb0Uzm:bnfp4nl)*

**Comment by jefesaurus** [comment]
I ran into two more issues: Unimplemented recursive case in TrigPoly and a recursive unary minus operator in TrigPoly

I fixed them here, but it killed the scope of this change.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/polynomial_test.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb3A6-bhIvURHdCq7hY:-Kb4K0O0cyNDTGXo0b_c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2d551919edcd66d1e5e3f20e88350a193cba2b7c/drake/common/test/polynomial_test.cc#L185)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Prefer `Vector2d coefficients{}` to `VectorXd` to avoid dynamic memory allocation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb4VbZ8-ivW-K98NO2S:bav9t6)*

**Comment by RussTedrake** [comment]
Looks really good again.  Thanks.  Some comments below.

FYI - The reason that TrigPoly, and to some extent Poly has not gotten much attention is because @soonho-tri wrote a more general symbolic engine that supersets this behavior.  You can now extract a polynomial from the symbolic expression class (and soon also trig poly).   

Based on previous discussions, our plan was to evaluate how many polynomial- and trig-poly- specific methods we end up liking in the code that uses this, and based on that to either keep these as intermediate classes (obtained primarily from symbolic expressions, but used as the API that we write, e.g. sums-of-squares optimization programs agains), or zap them.  If you have a use case or opinion, it would be great to hear it.

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trig_poly.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb55PADkseXYTbGvWTu:-Kb55PAENKeWDRnmwH1e:baxgb0e) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L134)):*
> ```objc
>     if (m.empty()) {
>       TrigPoly ret;
>       ret.poly_ = Polynomial<CoefficientType>(sin(CoefficientType(0)));
> ```

`return ret;`  here?

---

*[drake/common/trig_poly.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb56bs7-rO1OK1bBXoX:-Kb56bs7-rO1OK1bBXoY:bdrcc8f) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L141)):*
> ```objc
> 
>     // Base case of recursion is one mononomial with coefficient of 1.
>     if (m.size() == 1 && std::abs(m[0].coefficient) == CoefficientType(1)) {
> ```

prefer `using std::abs` above, then just `abs(coeff)` in the call. (same for `floor`, even `copy_sign`, below).  If CoefficientType != double, then `std::abs` might not be defined (even if `abs` is).

---

*[drake/common/trig_poly.h, line 192 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb5701y00uKglOfTFL1:-Kb5701y00uKglOfTFL2:b-10gin0) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L192)):*
> ```objc
>     if (m.empty()) {
>       TrigPoly ret;
>       ret.poly_ = Polynomial<CoefficientType>(cos(CoefficientType(0)));
> ```

return value here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb5788yGVeuucXqBUKh:b-npbckm)*

**Comment by jefesaurus** [comment]
Okay. Good to know you're actively evaluating and iterating these libs. For reference, I've been playing around with the PiecewisePolynomial library as a path/trajectory representation. It works well, and the symbolic polynomial functionality underneath allows me to do a few steps analytically before resorting to numerical approximations. The derivatives, integrals, and the `roots() `polynomial solver interface were pretty sweet for finding a closest time parameter on a trajectory to an arbitrary point. Speaking of which, using `roots` on an autodiff polynomial would probably not give meaningful derivatives, right?

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/trig_poly.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb55PADkseXYTbGvWTu:-Kb7sZ5IeNXMQLhwNdRW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L134)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

`return ret;`  here?
</blockquote></details>

Done.

---

*[drake/common/trig_poly.h, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb56bs7-rO1OK1bBXoX:-Kb7s_mguuAu-_k68MQF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L141)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

prefer `using std::abs` above, then just `abs(coeff)` in the call. (same for `floor`, even `copy_sign`, below).  If CoefficientType != double, then `std::abs` might not be defined (even if `abs` is).
</blockquote></details>

Done.

---

*[drake/common/trig_poly.h, line 192 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-Kb5701y00uKglOfTFL1:-Kb7sb-jta3_5qcxfZgh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/41af5e7941eb5c3cf40b6246fcf6115ae5c697c0/drake/common/trig_poly.h#L192)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

return value here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb7snX32ix3SNVlxb32:b61nnk6)*

**Comment by RussTedrake** [comment]
:lgtm:

It would be good to try roots() on an autodiff.  On quick inspection, it looks like it is wired up sufficiently well.  I'm not sure it would be fast, but I think it might work.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4851#-:-Kb88-ctsckqOXkYCEoK:bou91hq)*

**Pull request merged**
