### PR TITLE
Add some more LCM message conversion utils

### PR DESCRIPTION
**Pull request by tkoolen**
Possibly controversial: also changes `eigenVectorToCArray` and `eigenVectorToStdVector` to work when the scalar type of the destination doesn't match the scalar type of the source (a common case when working with LCM messages, which often have `float` array or `vector` fields).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3532)

### CODE REVIEW

**Comment by tkoolen** [comment]
@liangfok could you do the feature review since you need this functionality?

**Comment by liangfok** [comment]
Yes of course. +@liangfok 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KS84KnQuYLT49QasE1h:b-gxi3oy)*

**Comment by tkoolen** [comment]
@david-german-tri, could you do a platform review?

**Comment by david-german-tri** [comment]
Today is @sammy-tri's day for oncall platform review (we swapped).

**Comment by sammy-tri** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/util/drakeUtil.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8EyIwZQOTXri3OTIT:-KS8EyIwZQOTXri3OTIU:bnpl14y) ([raw file](https://github.com/robotlocomotion/drake/blob/470412edce658cd8008325f18fa547465c0072c5/drake/util/drakeUtil.h#L62)):*
> ```objc
> // can only be used when the dimension information of the array is known at
> // compile time
> template <typename DestScalar, size_t Size, typename Derived>
> ```

I'm not sure the purpose of DestScalar would be obvious to someone who hadn't read the PR comments above.  Suggest adding some documentation?

---

*[drake/util/drakeUtil.h, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8EeZsXlkKxY2iIF5V:-KS8EeZxldh62bYxgTUU:bhcct58) ([raw file](https://github.com/robotlocomotion/drake/blob/470412edce658cd8008325f18fa547465c0072c5/drake/util/drakeUtil.h#L75)):*
> ```objc
> // this function is not Matlab related
> template <typename DestScalar, typename Derived>
> static void eigenVectorToStdVector(const Eigen::MatrixBase<Derived>& source,
> ```

Why did this grow the "static" keyword?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532)*

**Comment by liangfok** [comment]
One with first pass. Looks good overall! Just a few minor comments.

Just to confirm, this PR does not include a method that allows me to convert an`Eigen::Quaternion` into a `std::vector<float>` right?

---

Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/CMakeLists.txt, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS84rdwzFfLEYVZSESD:-KS84rdwzFfLEYVZSESE:bcxrfiu) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/CMakeLists.txt#L181)):*
> ```CMake
>   add_subdirectory(lcmtypes)
>   include_directories(${drake_BINARY_DIR} ${drake_BINARY_DIR}/lcmtypes)
>   include_directories(${CMAKE_INSTALL_PREFIX}/include/lcmtypes) #TODO(#3351)
> ```

BTW, this is not a defect since we don't have a style guide for CMakeLists.txt, but to be consistent with the C++ style guide, this TODO comment should be:

```
#TODO(tkoolen) #3351.
```

---

*[drake/util/drakeUtil.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8JOxMXq_v2hzIEJy3:-KS8JOxNPRnFNUcDct55:b-5o34p7) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/drakeUtil.h#L68)):*
> ```objc
>     throw std::runtime_error("Size of source doesn't match destination");
>   for (size_t i = 0; i < Size; ++i) {
>     destination[i] = static_cast<DestScalar>(source(i));
> ```

Can you elaborate on why this may be controversial? Is it because it's a `static_cast` and thus can potentially hide conversion problems that result in undefined behavior?

---

*[drake/util/test/testLCMUtil.cpp, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8IcBhnTbflPRXI7i-:-KS8IcBhnTbflPRXI7i0:b5z41py) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/test/testLCMUtil.cpp#L66)):*
> ```cpp
>   bot_core::vector_3d_t msg;
>   EncodeVector3d(vec, msg);
>   Eigen::Vector3d vec_back = DecodeVector3d(msg);
> ```

BTW: These unit tests perform an encode / decode operation before executing `EXPECT_TRUE()`. What is the chance that bugs in both methods coincidentally cancel each other out and thus escape detection?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KS8JGx1M0XlrpuuKLoq:b-j8gm4q)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/CMakeLists.txt, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS84rdwzFfLEYVZSESD:-KS8LM0RANDcUQWqU03J:b-kab6y7) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/CMakeLists.txt#L181)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, this is not a defect since we don't have a style guide for CMakeLists.txt, but to be consistent with the C++ style guide, this TODO comment should be:
> 
> ```
> #TODO(tkoolen) #3351.
> ```
</details>
Never mind. The C++ style guides allows:

```
TODO(#3351)
```

https://google.github.io/styleguide/cppguide.html#TODO_Comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532)*

**Comment by tkoolen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/util/drakeUtil.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8JOxMXq_v2hzIEJy3:-KS8Oa4Ki2OVzr8cPWsE:b-u2k5o9) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/drakeUtil.h#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Can you elaborate on why this may be controversial? Is it because it's a `static_cast` and thus can potentially hide conversion problems that result in undefined behavior?
</details>
Yeah, exactly that.

---

*[drake/util/drakeUtil.h, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8EyIwZQOTXri3OTIT:-KS8OFF-j7oJFPPYqFwJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/470412edce658cd8008325f18fa547465c0072c5/drake/util/drakeUtil.h#L62)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I'm not sure the purpose of DestScalar would be obvious to someone who hadn't read the PR comments above.  Suggest adding some documentation?
</details>
Done.

---

*[drake/util/drakeUtil.h, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8EeZsXlkKxY2iIF5V:-KS8OfhCVC8lF_lThicm:bqikd9j) ([raw file](https://github.com/robotlocomotion/drake/blob/470412edce658cd8008325f18fa547465c0072c5/drake/util/drakeUtil.h#L75)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Why did this grow the "static" keyword?
</details>
Oops. I copied this over from a static method of a class. Good catch.

---

*[drake/util/test/testLCMUtil.cpp, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8IcBhnTbflPRXI7i-:-KS8PTtJ8UG4ClNCv0iN:b8sj1mi) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/test/testLCMUtil.cpp#L66)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: These unit tests perform an encode / decode operation before executing `EXPECT_TRUE()`. What is the chance that bugs in both methods coincidentally cancel each other out and thus escape detection?
</details>
No real chance, because the `Encode` methods take a const reference to the source data, so they can't modify the input data. To be extra careful, I made the source data const in this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532)*

**Comment by sammy-tri** [comment]
It looks like there are still some build issues, but I'm comfortable delegating the rest of the review to @liangfok (particularly since I'm out tomorrow) since I don't see any major platform issues holding this up.  :lgtm: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KS8_3LroizQemtYv1ta:b-evva7f)*

**Comment by tkoolen** [comment]
Thanks Sammy. @liangfok, I addressed your comments, you have a couple of blocking ones.

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KS8g8FKPAa8x_7_Rllc:bamnkuq)*

**Comment by liangfok** [comment]
I finished another round of review. Just a few remaining comments. PTAL. Thanks.

---

Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/util/drakeUtil.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8JOxMXq_v2hzIEJy3:-KS9GREU_fmaDDpnT1vT:bfylbps) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/drakeUtil.h#L68)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> Yeah, exactly that.
</details>
Thanks! Would this be a good application of explicit template instantiation to guarantee that the types are compatible with `static_cast`?

---

*[drake/util/drakeUtil.h, line 63 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9QTv95zIBzl38oTE3:-KS9QTv95zIBzl38oTE4:b6bl36u) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L63)):*
> ```objc
>  *
>  * Can only be used when the dimension information of the array is known at compile time.
>  * Note that the scalar type of @p source need not match the scalar type of @p destination (@p DestScalar). A static_cast will be performed to convert to elements of @p source to @p DestScalar.
> ```

These lines appear to exceed 80 characters in width.

---

*[drake/util/drakeUtil.h, line 80 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9L5DHBW68KCdOb9dG:-KS9L5DHBW68KCdOb9dH:bldms2c) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L80)):*
> ```objc
> // note for if/when we split off all Matlab related stuff into a different file:
> // this function is not Matlab related
> /** Copies the elements of a (row or column) Eigen vector to a std::vector
> ```

Missing period at end of sentence.

---

*[drake/util/drakeUtil.h, line 80 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9LuZNQfn79MWktexn:-KS9LuZNQfn79MWktexo:b-7h77vs) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L80)):*
> ```objc
> // note for if/when we split off all Matlab related stuff into a different file:
> // this function is not Matlab related
> /** Copies the elements of a (row or column) Eigen vector to a std::vector
> ```

BTW. Since autobrief is enabled, this line can go the next line after the opening `/**`.

---

*[drake/util/drakeUtil.h, line 82 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9KIjjBBI0zUDTFby0:-KS9KIjjBBI0zUDTFby1:b6bl36u) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L82)):*
> ```objc
> /** Copies the elements of a (row or column) Eigen vector to a std::vector
>  *
>  * Note that the scalar type of @p source need not match the scalar type of @p destination (@p DestScalar). A static_cast will be performed to convert to elements of @p source to @p DestScalar.
> ```

These lines appear to exceed 80 characters in width.

---

*[drake/util/drakeUtil.h, line 89 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9Kuv0faDsN-KTCjjo:-KS9Kuv0faDsN-KTCjjp:b2uafj3) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L89)):*
> ```objc
> template <typename DestScalar, typename Derived>
> void eigenVectorToStdVector(const Eigen::MatrixBase<Derived>& source,
>                                    std::vector<DestScalar>& destination) {
> ```

Strange spacing. Is this `clang-format` compliant?

---

*[drake/util/test/testLCMUtil.cpp, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8IcBhnTbflPRXI7i-:-KS9M9411rCa64-8UZXc:b89smko) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/test/testLCMUtil.cpp#L66)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> No real chance, because the `Encode` methods take a const reference to the source data, so they can't modify the input data. To be extra careful, I made the source data const in this test.
</details>
Actually, I wasn't worried about the `Encode()` method modifying the input data. Instead, I was wondering whether the two methods could cancel each others bugs out. For example, the following two methods are both buggy but they cancel each other out when executing `subtract_one(add_one(10))`:

```
int add_one(int foo) {
  return foo + 2;
}

int subtract_one(int foo) {
  return foo - 2;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KS9Q_48r0dH0xnYyY-x:b-mcn645)*

**Comment by liangfok** [comment]
The following CI failure appears to be a MATLAB flake.

@drake-jenkins-bot retest this please.

**Comment by tkoolen** [comment]
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/util/drakeUtil.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8JOxMXq_v2hzIEJy3:-KSD-Iq7YoiHnlDPkfOG:b-n6mbi3) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/drakeUtil.h#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks! Would this be a good application of explicit template instantiation to guarantee that the types are compatible with `static_cast`?
</details>
I think explicit template instantiation is not a good solution. It would result in uninformative linker errors if you're not using the right types. I think this is a case where we should assume that the user is an adult.

---

*[drake/util/drakeUtil.h, line 63 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9QTv95zIBzl38oTE3:-KSD-HKnBv0dq--TSJp4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L63)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> These lines appear to exceed 80 characters in width.
</details>
Done.

---

*[drake/util/drakeUtil.h, line 80 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9L5DHBW68KCdOb9dG:-KSD-xn219va_ucFaoVo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L80)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing period at end of sentence.
</details>
Done.

---

*[drake/util/drakeUtil.h, line 80 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9LuZNQfn79MWktexn:-KSD09ZMJrJ3ca-qHMTV:b6qao8c) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L80)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW. Since autobrief is enabled, this line can go the next line after the opening `/**`.
</details>
Sure, either way.

---

*[drake/util/drakeUtil.h, line 82 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9KIjjBBI0zUDTFby0:-KSD04eVKr-cC6iRiDLp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L82)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> These lines appear to exceed 80 characters in width.
</details>
Done.

---

*[drake/util/drakeUtil.h, line 89 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS9Kuv0faDsN-KTCjjo:-KSD0Io0-9rrj3ekbDrR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ef9549a65931651a752e15d820cf2fa0c22f55/drake/util/drakeUtil.h#L89)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Strange spacing. Is this `clang-format` compliant?
</details>
Done.

---

*[drake/util/test/testLCMUtil.cpp, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8IcBhnTbflPRXI7i-:-KSD0T4E-qhOJRCWsRxt:b-hvvxxy) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/test/testLCMUtil.cpp#L66)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Actually, I wasn't worried about the `Encode()` method modifying the input data. Instead, I was wondering whether the two methods could cancel each others bugs out. For example, the following two methods are both buggy but they cancel each other out when executing `subtract_one(add_one(10))`:
> 
> ```
> int add_one(int foo) {
>   return foo + 2;
> }
> 
> int subtract_one(int foo) {
>   return foo - 2;
> }
> ```
> 
> 
</details>
I see your point, but I see no way to test that the fields of the LCM messages get set correctly that doesn't involve basically copying the exact code of the methods being tested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/util/drakeUtil.h, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8JOxMXq_v2hzIEJy3:-KSD39gVtr8IDtbErh3g:b-j072k) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/drakeUtil.h#L68)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I think explicit template instantiation is not a good solution. It would result in uninformative linker errors if you're not using the right types. I think this is a case where we should assume that the user is an adult.
</details>
OK. SGTM. :smile: 

Yeah, the linker errors will be something like `undefined symbol class Foo<type>`. I'm not sure this is "uninformative" but I can definitely see how the message can become extremely convoluted when templated Eigen classes are involved.

---

*[drake/util/test/testLCMUtil.cpp, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-KS8IcBhnTbflPRXI7i-:-KSD2UsCtVAxJ3-Ly4vW:batrzap) ([raw file](https://github.com/robotlocomotion/drake/blob/3a8431d75e1c06c37f33ba030dacf1ae9eb21548/drake/util/test/testLCMUtil.cpp#L66)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> I see your point, but I see no way to test that the fields of the LCM messages get set correctly that doesn't involve basically copying the exact code of the methods being tested.
</details>
In #3494, I use literals to define the expected values. I realize that'll take a lot of time / code and will thus mark this thread as "satisfied" while leaving this to your discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3532#-:-KSD3isl84nppIvhoM2C:bnfp4nl)*

**Comment by tkoolen** [comment]
Thanks for the reviews guys!

**Pull request merged**
