### PR TITLE
add convenience overloads for AddIndeterminates

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-:-NQVDIEy9w2CGdqwerYu:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-:-NQYskKM4IpOMymUl-fR:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 843 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQYsUyW5SepKtahMZRf:-NQYsUyW5SepKtahMZRg:b2cbrjd) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/mathematical_program.h#L843)):*
> ```objc
> 
>   /** Adds indeterminates.
>    * This method appends some indeterminates to the end of the program's old
> ```

Do you want to promise that the newly added indeterminates is stored in the same order as `new_indeterminates`?

**Review by AlexandreAmice — COMMENTED** [review]
+@xuchenhan-tri for plaform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-:-NQ_DfWy4s2in3pHffw5:basne46)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @xuchenhan-tri)

___
*[`solvers/mathematical_program.h` line 843 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQYsUyW5SepKtahMZRf:-NQ_CbRz5yqmHrJyqJvw:b-pn8m5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/mathematical_program.h#L843)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you want to promise that the newly added indeterminates is stored in the same order as `new_indeterminates`?
</blockquote></details>

It does add the indeterminants to the end of the current indeterminants, but I don't want to promise a specific order as this is dependent on the implementation of `Variables` which is not necessarily ordered.

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: feature) 
platform :lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-:-NQaBJkM3KZujlzK0i_C:b-jw8vv4)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`solvers/test/mathematical_program_test.cc` line 539 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQa9P7a9BMf45KQ37HC:-NQa9P7a9BMf45KQ37HD:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/test/mathematical_program_test.cc#L539)):*
> ```cpp
> 
> GTEST_TEST(TestAddIndeterminate, AddIndeterminate1) {
>   // Call AddIndeterminates on an empty program.
> ```

nit



_Suggestion:_
```cpp
// Call AddIndeterminate on an empty program.
```
___
*[`solvers/test/mathematical_program_test.cc` line 554 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQa9K1x2H9Zv1ZVesJT:-NQa9K1x2H9Zv1ZVesJU:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/test/mathematical_program_test.cc#L554)):*
> ```cpp
> 
> GTEST_TEST(TestAddIndeterminate, AddIndeterminate2) {
>   // Call AddIndeterminates on a program with some indeterminates
> ```

nit



_Suggestion:_
```cpp
// Call AddIndeterminate on a program with some indeterminates
```
___
*[`solvers/test/mathematical_program_test.cc` line 581 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQa9fE18qoFlsv91mkF:-NQa9fE18qoFlsv91mkG:be2uwb8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/test/mathematical_program_test.cc#L581)):*
> ```cpp
>   // Call AddIndeterminate with an input that intersects with old
>   // indeterminates.
>   EXPECT_THROW(prog.AddIndeterminate(y(0)), std::runtime_error);
> ```

BTW, you could use DRAKE_EXPECT_THROWS_MESSAGE macro for a more precise test. 

e.g.
```cpp
DRAKE_EXPECT_THROWS_MESSAGE(prog.AddIndeterminate(y(0)), ".*already exist.*");
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 843 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-NQYsUyW5SepKtahMZRf:-NQaDFPg-EF5PHc4j_pi:b-gt3f68) ([raw file](https://github.com/RobotLocomotion/drake/blob/ee372d91a43a2899e859847f6dd4b5a5c626831b/solvers/mathematical_program.h#L843)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

It does add the indeterminants to the end of the current indeterminants, but I don't want to promise a specific order as this is dependent on the implementation of `Variables` which is not necessarily ordered.
</blockquote></details>

That is fine. BTW, `Variables` is ordered based on the documentation https://github.com/RobotLocomotion/drake/blob/91e3dccea12c6b5fa73ec215d8af0ff4ee7f1876/common/symbolic/expression/variables.h#L23
`std::set` is ordered.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18992#-:-NQcNOl0-ngdNAVgijd6:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,xuchenhan-tri(platform) (waiting on @AlexandreAmice)

**Pull request merged**
