### PR TITLE
Load namespace from the proto

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7302)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@sherm1 for platform review per rotation, please.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7302#-:-KwrUonUTMhrsS0J9ZPU:bnfp4nl)*

**Comment by sherm1** [comment]
Are there unit tests somewhere that are sufficient to ensure that these changes are working? Assuming yes, platform :lgtm:.

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7302#-:-KwrlqO-WhMk6TkCn2Oj:b-l98cdb)*

**Comment by jwnimmer-tri** [comment]
Always a good question.

One part of the answer is that `lcm_vector_gen` has a unit test, https://github.com/RobotLocomotion/drake/blob/master/drake/tools/test/lcm_vector_gen_test.sh, that confirms that the one specific `named_vector` in its test folder codegens correctly.  In this PR, that codegen output is unchanged.

The second part of the answer is that for all of the other `named_vectors` that been edited, a reviewer has to manually re-run all of their codegen steps, and see what the PR has changed:
```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ find drake -name '*gen.sh' |
  grep -v lcm_vector | xargs -n1 bash
```
For this PR, I've already run that manually, and confirmed that the codegen output is unchanged.

The eventual goal of this sub-series of PRs (`...-pr27{a,b,c,d,e,f,g,h}`) is actually to bake the codegen into the build system, so that we can modify it with confidence.  (Which then means that we can hoist the `drake` folder up a level with confidence.)

**Pull request merged**
