### PR TITLE
doc: Add third-party images (GitHub, Python)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14657

\cc @BetsyMcPhail @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)

### CODE REVIEW

**Comment by sherm1** [comment]
Do you have a feature reviewer in mind for this, @EricCousineau-TRI ?

**Review by EricCousineau-TRI — COMMENTED** [review]
Oops, I do! +@iantheengineer for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MScATTQ-2h3aWqGk7_E:b-j69ti2)* status: LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
Thanks for the PR. I have a few nits, but more importantly want to know if the licenses and the associated files can exist in the Drake repository.

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MSdFLC3-YcRkJevkJg7:br1i0i7)* status: 7 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[doc/third_party/README.md, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd7XXMCSE89wxzSVhO:-MSd7XXNBftqf1Dn2X5a:b76l1s9) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/README.md#L2)):*
> ```
> was
> ```
Grammar: Replace with "are" or "were" depending on your intended tense.
___
*[doc/third_party/README.md, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd8-QZ4wx_qsfSLvI0:-MSd8-QZ4wx_qsfSLvI1:bm4a1cq) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/README.md#L4)):*
> ```
> has
> ```
SP: have
___
*[doc/third_party/README.md, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd5gJx4zAKBZJal9bH:-MSd5gJy0oJPhp8ZtPMx:b-6ld8dn) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/README.md#L6)):*
> ```
> those terms should be obviously associated
> with those artifacts.
> ```
Nit: I think it makes sense to explicitly state here that information about the license and terms can be found in the associated README.md files alongside the logos (removing ambiguity of "obvious").
___
*[doc/third_party/images/GitHub-Mark.README.md, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd6KpV50Sc1FS0AEvM:-MSd6KpV50Sc1FS0AEvN:bnczy1p) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/GitHub-Mark.README.md#L7)):*
> ```
> sha256sum ./GitHub-Mark.zip·
> ```
Nit: Remove EOL whitespace.
___
*[doc/third_party/images/GitHub-Mark.README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd7JPfC0DZZ-Kl2CiQ:-MSd7JPfC0DZZ-Kl2CiR:boxq3sk) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/GitHub-Mark.README.md#L18)):*
> ```Markdown
>     ├── GitHub-Mark-64px.png
>     └── GitHub-Mark-Light-64px.png
> ```
> ```

FYI, followed the instructions and things look correct.
___
*[doc/third_party/images/julia.README.md, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdAa580RZ84zCHA8Ci:-MSdAa580RZ84zCHA8Cj:btau9ms) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L12)):*
> ```Markdown
> Copyright (c) 2012-2019: Stefan Karpinski <stefan@karpinski.org>.
> 
> These designs are licensed under the Creative Commons "BY-NC-SA" 4.0 License. This means that you are free to:
> ```

I would like you to verify that Drake can contain "Creative Commons "BY-NC-SA" 4.0 License" content.
___
*[doc/third_party/images/julia.README.md, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd9I_X4KyzU4NsWQL9:-MSd9I_X4KyzU4NsWQLA:bh37lsu) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L19)):*
> ```
> provide a link to the license
> ```
Although this is a copy of the license, it seems like you need to provide a link to the license as well:
https://github.com/JuliaLang/julia-logo-graphics/blob/master/LICENSE.md
___
*[doc/third_party/images/python.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdEa8o4lydUKChBIwG:-MSdEa8o4lydUKChBIwH:brq08ep) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/python.README.md#L3)):*
> ```
> https://www.python.org/community/logos
> ```
The Python language on this site seems quite permissive. But again, I would like explicit confirmation that content under these guidelines can be added to Drake.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)* status: 7 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[doc/third_party/images/julia.README.md, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdAa580RZ84zCHA8Ci:-MShvmWw5P4-UEsJ5Ghe:b-iti8hl) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L12)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

I would like you to verify that Drake can contain "Creative Commons "BY-NC-SA" 4.0 License" content.
</blockquote></details>

My suggestion here would simply be to drop mention of Julia from the Drake website entirely.  I'm not sure that anyone involved with Drake maintainership ever uses that avenue, so we can't really support it in the first place, and I'm not sure that the relatively rudimentary instructions we have right now are actually helping anyone in the first place.

If nothing else, the Julia logo doesn't seem like it's MVP for getting this website out the door.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)* status: 7 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[doc/third_party/images/julia.README.md, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdAa580RZ84zCHA8Ci:-MT0wILo5VwvTLef5bmV:b-7e3quj) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My suggestion here would simply be to drop mention of Julia from the Drake website entirely.  I'm not sure that anyone involved with Drake maintainership ever uses that avenue, so we can't really support it in the first place, and I'm not sure that the relatively rudimentary instructions we have right now are actually helping anyone in the first place.

If nothing else, the Julia logo doesn't seem like it's MVP for getting this website out the door.
</blockquote></details>

The NC part basically makes the logo non-open source. Since no one is likely to be actively selling the something related to Julia here and incorporating the logo into marketing material, it is probably fine, and many open source themes use NC content in a minor part (see caveat), but if we are keeping the bar high with respect to open source, you do not want that, so Jeremy's advice is perfect.

Caveat, US copyright laws would probably say this is fair use, regardless of whether it were a commercial company. Sometimes, the license is not the whole story.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)* status: 5 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

___
*[doc/third_party/README.md, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd7XXMCSE89wxzSVhO:-MTbScsn1nUr2ldQyn1B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/README.md#L2)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> was
> ```
Grammar: Replace with "are" or "were" depending on your intended tense.
</blockquote></details>

Done.
___
*[doc/third_party/README.md, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd8-QZ4wx_qsfSLvI0:-MTbSd9J6N0vtyrTXW01:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/README.md#L4)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> has
> ```
SP: have
</blockquote></details>

Done.
___
*[doc/third_party/images/julia.README.md, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdAa580RZ84zCHA8Ci:-MTbSgXIA-F_Vj3Z-Hrr:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L12)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The NC part basically makes the logo non-open source. Since no one is likely to be actively selling the something related to Julia here and incorporating the logo into marketing material, it is probably fine, and many open source themes use NC content in a minor part (see caveat), but if we are keeping the bar high with respect to open source, you do not want that, so Jeremy's advice is perfect.

Caveat, US copyright laws would probably say this is fair use, regardless of whether it were a commercial company. Sometimes, the license is not the whole story.
</blockquote></details>

Done. Removed.
___
*[doc/third_party/images/julia.README.md, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSd9I_X4KyzU4NsWQL9:-MTbSefPDVnCfmMiSgno:b-m9ofxw) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/julia.README.md#L19)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> provide a link to the license
> ```
Although this is a copy of the license, it seems like you need to provide a link to the license as well:
https://github.com/JuliaLang/julia-logo-graphics/blob/master/LICENSE.md
</blockquote></details>

Done. Removed per Jeremy's suggestion.
___
*[doc/third_party/images/python.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdEa8o4lydUKChBIwG:-MTbSiEl6JKV7IlG-qyA:b-na91hd) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/python.README.md#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> https://www.python.org/community/logos
> ```
The Python language on this site seems quite permissive. But again, I would like explicit confirmation that content under these guidelines can be added to Drake.
</blockquote></details>

Per DM's, I don't know what the concrete concern is here (what makes it "explicit"?)
The wording in the website is permissive, and there are no artifacts surrounding this images that would indicate that we will violate any license terms, and I believe we've supplied sufficient attribution.

Can you expand, or can we ignore it for now?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)* status: 5 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

___
*[doc/third_party/images/python.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdEa8o4lydUKChBIwG:-MTbWSomB4w5lNc2vspN:b-6a3tc) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/python.README.md#L3)):*
> Uses that Never Require Approval
>
> ...
>
> As such, stating accurately that software is written in the Python programming language, that it is compatible with the Python programming language, or that it contains the Python programming language, is always allowed. In those cases, you may use the word "Python" or the unaltered logos to indicate this, without our prior approval. This is true both for non-commercial and commercial uses.
>
> This clause overrides other clauses of this policy.
>
> ....
>
> Use of unaltered PSF-provided logos on websites, brochures, and product packaging. The "intertwined snakes" graphic alone is an unaltered version, whether or not accompanied by the words in PSF-provided logos. Non-commercial uses to promote the Python programming language are allowed, as are all nominative uses as described in the section "Uses that Never Require Approval". 

Seems pretty clear. The logo is unaltered, I take it.

**Review by EricCousineau-TRI — COMMENTED** [review]
Increase priority to merge: +(priority: high) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MTkVMJ35DiW6eYPsp4Y:b-ul8skk)* status: 5 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: Thanks for the updates here. Looks good now.

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MTmF1BC9B1mAnzFjr9O:b-4fg33r)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[doc/third_party/images/python.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdEa8o4lydUKChBIwG:-MTmEqNC0rxRh2-sk7fX:bjflh2b) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/python.README.md#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> Uses that Never Require Approval
>
> ...
>
> As such, stating accurately that software is written in the Python programming language, that it is compatible with the Python programming language, or that it contains the Python programming language, is always allowed. In those cases, you may use the word "Python" or the unaltered logos to indicate this, without our prior approval. This is true both for non-commercial and commercial uses.
>
> This clause overrides other clauses of this policy.
>
> ....
>
> Use of unaltered PSF-provided logos on websites, brochures, and product packaging. The "intertwined snakes" graphic alone is an unaltered version, whether or not accompanied by the words in PSF-provided logos. Non-commercial uses to promote the Python programming language are allowed, as are all nominative uses as described in the section "Uses that Never Require Approval". 

Seems pretty clear. The logo is unaltered, I take it.


</blockquote></details>

After checking with folks, the Python logo is approved.

**Review by IanTheEngineer — COMMENTED** [review]
+@soonho-tri for Platform Review please. These changes are simple, but I'm not a Platform Reviewer at this point.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MTmGDBD-Gosd9oR5LVD:b50t6ql)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by IanTheEngineer — COMMENTED** [review]
Thinking about it, it's late in the evening to assign you, sorry! -@soonho-tri 
+@jwnimmer-tri for Platform Review tomorrow please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MTmJpJwEDH9rfzUVVK_:b-kqd2xf)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

Truth, beauty.

> Reviewed 4 of 8 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614#-:-MTmMWSP01xV8bndzXdz:blkvy1r)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),IanTheEngineer

**Comment by EricCousineau-TRI** [comment]
Ignoring debug/sanitizer builds (see Slack: https://drakedevelopers.slack.com/archives/C270MN28G/p1613608490118600)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14614)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),IanTheEngineer

___
*[doc/third_party/images/python.README.md, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14614#-MSdEa8o4lydUKChBIwG:-MTmbDKZ3xbwdjWXSLzN:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/a5cc8ca94e189f1cbb21f574c9ea1805f1931e35/doc/third_party/images/python.README.md#L3)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

After checking with folks, the Python logo is approved.
</blockquote></details>

OK Sweet!

**Pull request merged**
