### PR TITLE
Fixup executables on Linux

### PR DESCRIPTION
**Pull request by fbudin69500**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7571)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/BUILD.bazel, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-mSNdWnNYYCkQog7ss:-L-mSNdWnNYYCkQog7st:bhvy3bc) ([raw file](https://github.com/robotlocomotion/drake/blob/5a9ca438778fa821b793b48ac610f8509f098d46/tools/install/BUILD.bazel#L13)):*
> ```
> )
> 
> py_library(
> ```

Should this be `testonly = 1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-:-L-mSdgkMKiWkdkpul9a:bnfp4nl)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/BUILD.bazel, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-mSNdWnNYYCkQog7ss:-L-mUcj-w8skAGqdvpgD:bo6apac) ([raw file](https://github.com/robotlocomotion/drake/blob/5a9ca438778fa821b793b48ac610f8509f098d46/tools/install/BUILD.bazel#L13)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should this be `testonly = 1`?
</blockquote></details>

Indeed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-n2KZpV7vgdHyXsoUB:-L-n2KZq2YXKB4LytYro:bqmz06n) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
> ```
> # lcm-gen still works. Cannot be run on its own, needs to be
> # run as part of all the drake tests to have access to //:install
> drake_py_test(
> ```

Do you need `drake_py_test`, or would `py_test` on its own work?  My general impression is that we should only use `drake_` for Drake code; third-party build system re-implementations should generally not use it.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-nGgN3aRBRc1JTtZPK:be9qdpp) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
> ```
> # lcm-gen still works. Cannot be run on its own, needs to be
> # run as part of all the drake tests to have access to //:install
> drake_py_test(
> ```

Is this test run in CI?  I don't think `@foo//:bar` tests would be run by default.  Maybe the test _should_ live in Drake?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
First pass done.

---

Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[drake/bindings/pydrake/test/testCommonInstall.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nuYsOEE6dEUIfNbag:-L-nuYsPt61vHTWMRQ_I:b-d0g9oy) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/drake/bindings/pydrake/test/testCommonInstall.py#L3)):*
> ```Python
> from __future__ import absolute_import, division, print_function
> 
> import install_test_helper
> ```

"
Imports should be grouped in the following order:
- standard library imports
- related third party imports
- local application/library specific imports
"
-- https://www.python.org/dev/peps/pep-0008/#imports

---

*[tools/install/BUILD.bazel, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvGuI1mQVhv4B5cAw:-L-nvGuI1mQVhv4B5cAx:b-4shy1e) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/BUILD.bazel#L19)):*
> ```
>     imports = ["."],
>     visibility = ["//visibility:public"],
> )
> ```

BTW Do we want `data = ["//:install"]`?

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nw1_Ngq70BQKC7M3w:-L-nw1_Ngq70BQKC7M3x:b-l9glmv) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
> ```
> dylib_match = r"(.*\.so)(\.\d+)*$|(.*\.dylib)$"
> 
> def check_file_type(dst):
> ```

Missing API documentation.

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nwPoDK_WdIZAyQJ6e:-L-nwPoDK_WdIZAyQJ6f:b-7vtqep) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
> ```
> dylib_match = r"(.*\.so)(\.\d+)*$|(.*\.dylib)$"
> 
> def check_file_type(dst):
> ```

FYI The verb "check" and return type "True vs False" seem mismatched.

---

*[tools/install/install.py.in, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nwV-cHYjeS8wB5Y7v:-L-nwV-cHYjeS8wB5Y7w:bpimwoz) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L22)):*
> ```
> def check_file_type(dst):
>     # Checking file type with command `file` is the safest way to find executables. Files
>     # without an extension are likely to be executables, but it is not always the case.
> ```

BTW line too long (same with prior line)

---

*[tools/install/install.py.in, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvqN-6TfoPcfTi3dD:-L-nvqN-6TfoPcfTi3dE:bpwd20v) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L28)):*
> ```
>     re_result = re.match(executable_match, file_output)
>     if re_result is not None:
>       return True
> ```

BTW wrong indent

---

*[tools/install/install_test_helper.py, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nu3GeUKXEOjp9q-zW:-L-nu3GeUKXEOjp9q-zX:boqqlx9) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L8)):*
> ```Python
> 
> 
> def install(installation_folder="tmp", installed_subfolders=[]):
> ```

Missing function documentation.

---

*[tools/install/install_test_helper.py, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nuJ6bBcBGwTXd4Zq9:-L-nuJ6c_isrurjx6LPt:bcshl32) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L34)):*
> ```Python
>     if content_install_folder != [installation_folder]:
>         return "Bazel build artifact not removed in test folder: "\
>             + str(content_install_folder)
> ```

"The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, ... These should be used in preference to using a backslash for line continuation."
-- https://www.python.org/dev/peps/pep-0008/#maximum-line-length

---

*[tools/install/install_test_helper.py, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nunsOwoHxj_EeAivR:-L-nunsPVbBPLPyHfzbJ:b-vo1og4) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L34)):*
> ```Python
>     if content_install_folder != [installation_folder]:
>         return "Bazel build artifact not removed in test folder: "\
>             + str(content_install_folder)
> ```

I suggest `return None` at the end of the function, since callers are using the return value to gauge success, being explicit seems like a good idea.

---

*[tools/workspace/lcm/test/install_test.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nv0igPfRS4moBqglZ:-L-nv0igPfRS4moBqgl_:bcaej5y) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/test/install_test.py#L3)):*
> ```Python
> from __future__ import absolute_import, division, print_function
> 
> import install_test_helper
> ```

Ditto "Imports should be grouped in the following order:"...

---

*[tools/workspace/lcm/test/install_test.py, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvY7mglOjI9q0i60f:-L-nvY7mglOjI9q0i60g:bi7a640) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/test/install_test.py#L12)):*
> ```Python
>     def testInstall(self):
>         tmp_folder = "tmp"
>         result = install_test_helper.install(tmp_folder, ['lib', 'share'])
> ```

Why not `bin`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-:-L-nwjWax1C3LLhJY-ei:b-te4kzy)*

**Comment by fbudin69500** [comment]
Review status: 1 of 7 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[drake/bindings/pydrake/test/testCommonInstall.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nuYsOEE6dEUIfNbag:-L-qckPAAKyPpVMjag1h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/drake/bindings/pydrake/test/testCommonInstall.py#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

"
Imports should be grouped in the following order:
- standard library imports
- related third party imports
- local application/library specific imports
"
-- https://www.python.org/dev/peps/pep-0008/#imports
</blockquote></details>

Done.

---

*[tools/install/BUILD.bazel, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvGuI1mQVhv4B5cAw:-L-qdBFLcrosAOFu-fop:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/BUILD.bazel#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do we want `data = ["//:install"]`?
</blockquote></details>

Done.

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nwPoDK_WdIZAyQJ6e:-L-qhIFXNkalw60xCXrF:b-66mdo3) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The verb "check" and return type "True vs False" seem mismatched.
</blockquote></details>

renamed `check_file_type` to `is_executable`.

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nw1_Ngq70BQKC7M3w:-L-qhsQX7jpT3kExT36q:byyxwgo) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing API documentation.
</blockquote></details>

There is no API documentation for any of the functions in this code. It could be added as comments, as docstrings, but maybe it should be added when this code is refactored (to be able to test the code independently from the installation process).

---

*[tools/install/install.py.in, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nwV-cHYjeS8wB5Y7v:-L-qhPvY8LnjId5xLBVg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW line too long (same with prior line)
</blockquote></details>

Done.

---

*[tools/install/install.py.in, line 28 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvqN-6TfoPcfTi3dD:-L-qfKb9qGSn5LczuVDY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW wrong indent
</blockquote></details>

Done.

---

*[tools/install/install_test_helper.py, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nu3GeUKXEOjp9q-zW:-L-qjhwCQrg53IBF4zFM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing function documentation.
</blockquote></details>

Done.

---

*[tools/install/install_test_helper.py, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nunsOwoHxj_EeAivR:-L-qexn3_zasiiIf-Ezo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I suggest `return None` at the end of the function, since callers are using the return value to gauge success, being explicit seems like a good idea.
</blockquote></details>

Done.

---

*[tools/install/install_test_helper.py, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nuJ6bBcBGwTXd4Zq9:-L-qeyjnz0xEjvriqV-G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install_test_helper.py#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

"The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, ... These should be used in preference to using a backslash for line continuation."
-- https://www.python.org/dev/peps/pep-0008/#maximum-line-length
</blockquote></details>

Done.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-qkN4m5TKTMFJo-4DB:b-dj6alu) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is this test run in CI?  I don't think `@foo//:bar` tests would be run by default.  Maybe the test _should_ live in Drake?
</blockquote></details>

I was under the impression that `BUILD.bazel` was used in Drake, and `lcm.BUILD.bazel` was used in the workspace.

---

*[tools/workspace/lcm/test/install_test.py, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nv0igPfRS4moBqglZ:-L-qjzPN4vlyRXubQUNB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/test/install_test.py#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto "Imports should be grouped in the following order:"...
</blockquote></details>

Done.

---

*[tools/workspace/lcm/test/install_test.py, line 12 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nvY7mglOjI9q0i60f:-L-qjzobcQj6o_Yh0WLC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/test/install_test.py#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why not `bin`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by fbudin69500** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-qnCGHy3wRDw4oSV9r:b9qldqj) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

I was under the impression that `BUILD.bazel` was used in Drake, and `lcm.BUILD.bazel` was used in the workspace.
</blockquote></details>

```bazel test //...
...
//tools/workspace/lcm:install_test                              (cached) PASSED in 25.6s
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by fbudin69500** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-qnTVPna6ITH9q1qzZ:b-fhjxfr) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

```bazel test //...
...
//tools/workspace/lcm:install_test                              (cached) PASSED in 25.6s
...
```
</blockquote></details>

missing
```
bazel test //...
```
in the comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-quaky_3sk7y1I9iKm:b-9yldq0) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

missing
```
bazel test //...
```
in the comment above.
</blockquote></details>

You're right, I misread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 6 files at r3.
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-n2KZpV7vgdHyXsoUB:-L-qulSYavmawbc5qArK:b-kw0rwz) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do you need `drake_py_test`, or would `py_test` on its own work?  My general impression is that we should only use `drake_` for Drake code; third-party build system re-implementations should generally not use it.
</blockquote></details>

Give my other misreading, I retract this comment; drake_py_test should probably remain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
LGTM pending rebase.

---

Reviewed 4 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nw1_Ngq70BQKC7M3w:-L-quyNzDNHKLuwODwDT:b-y38lmw) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

There is no API documentation for any of the functions in this code. It could be added as comments, as docstrings, but maybe it should be added when this code is refactored (to be able to test the code independently from the installation process).
</blockquote></details>

That the prior code is defective is not justification for this code to be so.  It should be clear to a reader what this function does; in the prior revision, I had to read the entire method body to infer the function's meaning.  Now that the function name is improved, probably a simple one-sentence overview here is going to be enough for future readers to understand the code.  Something like "Returns True iff the given pathname `dst` refers to an ELF or Mach-O executable or shared library." or whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-:-L-qvwTFXRGmR0QvDeOS:bsdtire)*

**Comment by fbudin69500** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tools/install/install.py.in, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nw1_Ngq70BQKC7M3w:-L-rLJAV0srDltq4M3EL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/install/install.py.in#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That the prior code is defective is not justification for this code to be so.  It should be clear to a reader what this function does; in the prior revision, I had to read the entire method body to infer the function's meaning.  Now that the function name is improved, probably a simple one-sentence overview here is going to be enough for future readers to understand the code.  Something like "Returns True iff the given pathname `dst` refers to an ELF or Mach-O executable or shared library." or whatever.
</blockquote></details>

Done.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-n2KZpV7vgdHyXsoUB:-L-rLNAOMB7sX0MkMuxN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Give my other misreading, I retract this comment; drake_py_test should probably remain.
</blockquote></details>

Done.

---

*[tools/workspace/lcm/BUILD.bazel, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-nGgN2WWhLYt_YoETf:-L-rLNceTVoAAuGHhWkF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d2e18a554b44dc19321f8a7c83a62bfac679d165/tools/workspace/lcm/BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You're right, I misread.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/install/install.py.in, line 22 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-rtr7C376hBTcJiEcs:-L-rtr7C376hBTcJiEct:bc1el8h) ([raw file](https://github.com/robotlocomotion/drake/blob/095d7e56bda6fbbf7003407f5f8dc8e201d75517/tools/install/install.py.in#L22)):*
> ```
> def is_executable(dst):
>     """Checks if given executable is an ELF or Mach-O executable
>     
> ```

BTW trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-:-L-ru5DEMDiB15Gn_2ye:bnfp4nl)*

**Comment by fbudin69500** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/install.py.in, line 22 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7571#-L-rtr7C376hBTcJiEcs:-L-s3yTSzPDgEoZZvMFL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/095d7e56bda6fbbf7003407f5f8dc8e201d75517/tools/install/install.py.in#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW trailing whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7571)*

**Comment by jwnimmer-tri** [comment]
@fbudin69500 Shall I merge this?  (I don't recall if you have merge bits or not; I thought you did.)  Or @jamiesnape did you want a last look?

**Pull request merged**
