### PR TITLE
[symbolic] Unify comment formatting in Polynomial and Monomial

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20202.

During reviews of prior changes to these files, we failed to detect the diverging comment formatting styles, so the classes were mixes of all different styles.  Repave both files entirely, using our modern comment formatting style.  This will make future changes go more smoothly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai would you like to either feature review?  Or at least, weigh in on the idea and we can delegate the full review to just a platform reviewer.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-:-NejF_I9Ab89waB71U6_:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/symbolic/monomial.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NejEydS6C_sIZlLZer0:-NejEydS6C_sIZlLZer1:b-kalfzi) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/monomial.h#L47)):*
> ```objc
>   /** Constructs a monomial from a vector of variables `vars` and their
>   corresponding integer exponents `exponents`.
>   For example, `%Monomial([x, y, z], [2, 0, 1])` constructs a monomial `x²z`.
> ```

May I ask what `%` does here? ChatGPT says `%` acts as an escape symbol, so that doxygen won't treat `Monomial` as a special symbol, is that right?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/symbolic/monomial.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NejEydS6C_sIZlLZer0:-NejM9cHBxXRvKJ3cqur:bsodmu7) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/monomial.h#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

May I ask what `%` does here? ChatGPT says `%` acts as an escape symbol, so that doxygen won't treat `Monomial` as a special symbol, is that right?
</blockquote></details>

Yes, see [last night's output](https://drake.mit.edu/doxygen_cxx/classdrake_1_1symbolic_1_1_monomial.html#aebb1af59c0da61e7a8904f10dbeb2384) for what it looks like without the `%`.

In short, Doxygen aggressively tries to hyperlink words to classes or functions.  If the **RedBold** style does more harm that good, we should opt-out of it with `%`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/symbolic/monomial.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NejEydS6C_sIZlLZer0:-NejMPcjA4E7sD94rRFO:bli44ab) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/monomial.h#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, see [last night's output](https://drake.mit.edu/doxygen_cxx/classdrake_1_1symbolic_1_1_monomial.html#aebb1af59c0da61e7a8904f10dbeb2384) for what it looks like without the `%`.

In short, Doxygen aggressively tries to hyperlink words to classes or functions.  If the **RedBold** style does more harm that good, we should opt-out of it with `%`.
</blockquote></details>

In this case, I opted out not only to fix the color/font, but also because the hyperlink was to the wrong overload.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review (tomorrow) per schedule, please.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`common/symbolic/monomial.h` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NejEydS6C_sIZlLZer0:-NekQil2A2i3olQnErs0:bcr5s2o) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/monomial.h#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In this case, I opted out not only to fix the color/font, but also because the hyperlink was to the wrong overload.
</blockquote></details>

Got it, thanks!

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot retest this please

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-:-NenW9ba9lW-mLXMJxr0:bg7igkv)* status: 5 unresolved discussions

___
*[`common/symbolic/monomial.h` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NenVW-NEvhF4s6nvz48:-NenVW-NEvhF4s6nvz49:b8vsvhu) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/monomial.h#L92)):*
> ```objc
>   `vars`.
>   @throw std::exception if `vars` doesn't contain all the variables in
>   this->GetVariables. */
> ```

nit. Also we should try to be more consistent about what gets typeset as Foo and what gets typeset as `Foo`.



_Suggestion:_
```objc
`this->GetVariables()`
```
___
*[`common/symbolic/polynomial.h` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NenVcsP67e8xtcbLWzn:-NenVcsP67e8xtcbLWzo:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/polynomial.h#L208)):*
> ```objc
> 
>   /** Evaluates the polynomial at a batch of indeterminates values.
>   @param[in] indeterminates Must include all this->indeterminates()
> ```

nit



_Suggestion:_
```objc
`this->indeterminates()`
```
___
*[`common/symbolic/polynomial.h` line 234 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NenUx6NAd9LvJt6eRat:-NenUx6O1YSt1G-QPLtH:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/polynomial.h#L234)):*
> ```objc
>   Each column of `indeterminates_values` stores one specific value of
>   `indeterminates`, where indeterminates_values.rows() ==
>   indeterminates.rows().
> ```

nit



_Suggestion:_
```objc
  `indeterminates`, where `indeterminates_values.rows() ==
  indeterminates.rows()`.
```
___
*[`common/symbolic/polynomial.h` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20213#-NenW0pl7nWj-Zwbo8Dt:-NenW0pl7nWj-Zwbo8Du:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aa3d4d484c8587e176bcffa6cae4e3e30a70953/common/symbolic/polynomial.h#L365)):*
> ```objc
> 
>   /** Returns true if this polynomial and `p` are almost equal (the difference
>   in the corresponding coefficients are all less than `tolerance),` after
> ```

nit



_Suggestion:_
```objc
`tolerance`),
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20213)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,xuchenhan-tri(platform)

**Pull request merged**
