### PR TITLE
Enable CLP to solve QP.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As discussed in https://github.com/RussTedrake/manipulation/issues/140#issuecomment-817383407

@hjsuh94

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894#-:-MY83tp1B-SBp4LArTs1:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Comment by jwnimmer-tri** [comment]
___
*[solvers/choose_best_solver.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYFwd1y6AZh6MhwWcgw:-MYFwd1z3dZanfykG6PO:bqjzqk5) ([raw file](https://github.com/robotlocomotion/drake/blob/14c3254b7f97789275e3763ca8cf5cd93b554919/solvers/choose_best_solver.cc#L41)):*
> ```cpp
>   } else if (IsMatch<GurobiSolver>(prog)) {
>     return GurobiSolver::id();
>   } else if (IsMatch<OsqpSolver>(prog)) {
> ```

nit The heuristics for the priority order in ChooseBestSolver are often obscure.  At a minimum, when you make changes here, I think you need to document your rationale or thought process in the commit message.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu and @jwnimmer-tri)

___
*[solvers/choose_best_solver.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYFwd1y6AZh6MhwWcgw:-MYG6Avn1luwmte4ZZQA:b-x6cq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/14c3254b7f97789275e3763ca8cf5cd93b554919/solvers/choose_best_solver.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The heuristics for the priority order in ChooseBestSolver are often obscure.  At a minimum, when you make changes here, I think you need to document your rationale or thought process in the commit message.
</blockquote></details>

This change intends to retain the selected solver prior to this PR.

Before this PR, CLP only solves LP, and OSQP only solves QP. Hence if the problem is QP, it selects OSQP; if the problem is LP, it selects CLP.

In this PR, we allow CLP to solve a QP. But we still want to select OSQP for a QP by default. Hence after this change, if the problem is QP, it would choose OSQP. If the problem is LP, then it first check `IsMatch<OsqpSolver>(prog)` (and OSQP doesn't because we don't allow OSQP to solve LP), then it would check `IsMatch<ClpSolver>(prog)` and select CLP.

In the future I might change the default behavior to prioritize CLP over OSQP for a QP, but I would like to make that change in a separate PR.

I added some documentation.

**Review by avalenzu — COMMENTED** [review]
:lgtm: with a couple nits.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894#-:-MYkRTkb9E8ScCC3NYX5:b5gbef2)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/choose_best_solver.cc, line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkLs795wx-EmjClbHO:-MYkLs7A9fdWQk6Mjtf9:b-8fylw2) ([raw file](https://github.com/robotlocomotion/drake/blob/df2e1d8a1c02018326e947b5e1fdf8d65c23cad9/solvers/choose_best_solver.cc#L43)):*
> ```cpp
>   } else if (IsMatch<OsqpSolver>(prog)) {
>     // For a QP, we prioritize OSQP over CLP.
>     // For an LP, we priortize CLP, and dont' allow solving LP with OSQP.
> ```

nit: s/dont'/don't/
___
*[solvers/test/clp_solver_test.cc, line 100 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkPpVO-dm9Z4m2F3-w:-MYkPpVO-dm9Z4m2F3-x:bftlrh1) ([raw file](https://github.com/robotlocomotion/drake/blob/df2e1d8a1c02018326e947b5e1fdf8d65c23cad9/solvers/test/clp_solver_test.cc#L100)):*
> ```cpp
>   // Add linear costs.
>   prog.AddLinearCost(4 * x(0) + 5);
>   // Now the cost is (x₀ + 2)² + (x₁ + x₂-2)² + 1
> ```

nit: missing spaces around the "-" sign in "x₂-2"

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894#-:-MYka9VQ8rKO2ahtNsC-:b8asji7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @avalenzu, @jwnimmer-tri, and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkiGBB1XE8bwEF41Tt:-MYkiGBB1XE8bwEF41Tu:bvrm62b) (no related file):*
FTR, a manual test of `bazel test //solvers/...` passed when executed manually on `macsim`.

---
___
*[solvers/choose_best_solver.cc, line 43 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkfqpQ8lINEYUYjypS:-MYkfqpQ8lINEYUYjypT:b-p58kbh) ([raw file](https://github.com/robotlocomotion/drake/blob/dcb717d244828744b7971add93fce7978ea27591/solvers/choose_best_solver.cc#L43)):*
> ```
> priortize
> ```
typo
___
*[solvers/clp_solver.cc, line 260 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkgGQH8anmQa7saaj4:-MYkgGQH8anmQa7saaj5:bmv0end) ([raw file](https://github.com/robotlocomotion/drake/blob/dcb717d244828744b7971add93fce7978ea27591/solvers/clp_solver.cc#L260)):*
> ```cpp
>                                    &Q_lower, &quadratic_vars, &linear_coeff,
>                                    &linear_vars, constant_cost);
>   // We need to convert 0.5*quadratic_var.dot(Q_lower * quadratic_var) to
> ```

BTW, is it typical and/or clear enough to skip the spaces around '*' for multiplication by 0.5 here? Also another one in the next line.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894#-:-MYkkNz95fCj35104uYt:bnfp4nl)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[solvers/choose_best_solver.cc, line 43 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkfqpQ8lINEYUYjypS:-MYkm_UG5wT6VNeZ26d7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcb717d244828744b7971add93fce7978ea27591/solvers/choose_best_solver.cc#L43)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> priortize
> ```
typo
</blockquote></details>

Done.
___
*[solvers/clp_solver.cc, line 260 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYkgGQH8anmQa7saaj4:-MYkmgT6CJqPBkjynWrN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dcb717d244828744b7971add93fce7978ea27591/solvers/clp_solver.cc#L260)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, is it typical and/or clear enough to skip the spaces around '*' for multiplication by 0.5 here? Also another one in the next line.
</blockquote></details>

Done.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[solvers/choose_best_solver.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYFwd1y6AZh6MhwWcgw:-MYlIXwu2t_wLDGy36QS:b-be1p4j) ([raw file](https://github.com/robotlocomotion/drake/blob/14c3254b7f97789275e3763ca8cf5cd93b554919/solvers/choose_best_solver.cc#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This change intends to retain the selected solver prior to this PR.

Before this PR, CLP only solves LP, and OSQP only solves QP. Hence if the problem is QP, it selects OSQP; if the problem is LP, it selects CLP.

In this PR, we allow CLP to solve a QP. But we still want to select OSQP for a QP by default. Hence after this change, if the problem is QP, it would choose OSQP. If the problem is LP, then it first check `IsMatch<OsqpSolver>(prog)` (and OSQP doesn't because we don't allow OSQP to solve LP), then it would check `IsMatch<ClpSolver>(prog)` and select CLP.

In the future I might change the default behavior to prioritize CLP over OSQP for a QP, but I would like to make that change in a separate PR.

I added some documentation.
</blockquote></details>

@jwnimmer-tri are you OK with this comment?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14894)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),avalenzu (waiting on @hongkai-dai)

___
*[solvers/choose_best_solver.cc, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14894#-MYFwd1y6AZh6MhwWcgw:-MYlJXwKCXu4pr_2ucdr:b-upd3s4) ([raw file](https://github.com/robotlocomotion/drake/blob/14c3254b7f97789275e3763ca8cf5cd93b554919/solvers/choose_best_solver.cc#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@jwnimmer-tri are you OK with this comment?
</blockquote></details>

Yes, thanks!

(Sorry I missed this, I have my dashboard configured to only show me PRs that are assigned to me.)

**Pull request merged**
