### PR TITLE
Remove GradientVar

### PR DESCRIPTION
**Pull request by tkoolen**
Part of https://github.com/RobotLocomotion/drake/issues/1476
Based off of https://github.com/RobotLocomotion/drake/pull/1648.

Removes GradientVar after replacing anything that used GradientVar (mostly expmap related stuff) by an equivalent AutoDiff implementation.

Also:
* reimplemented the expmap mex functions using mexify
* extracted our make_function implementations to their own file.
* added a toMex conversion for std::tuples.

As I said in https://github.com/RobotLocomotion/drake/issues/1476, this will be the last of the cleanup list issues I plan to do for a while.

### CODE REVIEW

**Comment by tkoolen** [comment]
Undefined M_PI on windows: we need to define _USE_MATH_DEFINES before including cmath everywhere now. I'm considering adding 
```
add_definitions(_USE_MATH_DEFINES)
```
to our top level CMakeLists.txt. Any reason not to?

**Comment by tkoolen** [comment]
Don't know what's up with drake006. I just rebased onto master. Error messages:
```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by tkoolen** [comment]
Now drake005 is doing the same thing.

**Comment by tkoolen** [comment]
* drake004: out of heap space, probably due to updating to eigen 3.3 beta; http://eigen.tuxfamily.org/index.php?title=3.3 mentions "Slight increase of compiler memory consumption" as a known issue.
* drake006: runDircolWObs timeout is not my fault I don't think. Completes in 82 seconds on my machine (OS X boot).

**Comment by RussTedrake** [comment]
the code looks good to me.  i assume that all of the trig code (e.g. for exponential maps) are copied from their previous locations?  it's hard to tell from the diff (and impossible for me to code review carefully).  

should we accept that drake004 is dying and merge despite the inability to compile?

**Comment by tkoolen** [comment]
Yes, the code for the expmap stuff needed to be moved from cpp files to the header.

Not having drake004 is unfortunate. Unless you want to spend the time to increase heap size somehow, we're going to have to accept pull requests without it...

I closed and reopened to see if the unexplained test failure on drake001 reappears.

**Comment by tkoolen** [comment]
drake001: runAtlasDynamics fails, but it also fails on master: http://kobol.csail.mit.edu/cd/viewTest.php?onlyfailed&buildid=21313. I'll open an issue.

I don't see any way this pull request could cause additional issues with simulating Atlas passive dynamics.

**Comment by tkoolen** [comment]
See https://github.com/RobotLocomotion/drake/issues/1702

**Pull request merged**
