### PR TITLE
py common: Deprecate bad alises for Tolerance Type

### LINKED ISSUE #14591: pydrake: Tolerance type shouldn't use special aliases
@josephsnyder, in #14265 and related upstream discussions, he noted that `ToleranceType` bindings use `absolute`, `relative`, whereas the C++ symbols are `kAbsolute`, `kRelative`, and are nested.

I want them to reflect C++.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Do dumb deferred deprecation gymnastics for pydrake.common._module_py
Make assertion error for descriptor deprecator more useful

Resolves #14591
Relates #7912 due to pulling hair out

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for feature review, please!
+@ggould-tri for platform review, please!

Soz for crappy gymnastics; should address the root issue, but I don't wanna do that just yet

This took about 30min longer than expected (10min originally) due to that :crying_cat_face: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS8Tq4BBbv_Nygkur4U:b5828eo)* status: LGTM missing from assignees SeanCurtis-TRI(platform),ggould-tri(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/module_py.cc, line 208 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS8V-RE06yifQUwcthx:-MS8V-RE06yifQUwcthy:bza6qpo) ([raw file](https://github.com/robotlocomotion/drake/blob/cd37acaafeca9027f8198fd86e22313cdf82f760/bindings/pydrake/common/module_py.cc#L208)):*
> ```cpp
>             "absolute",
>             [](py::handle /* cls */) {
>               WarnDeprecated(absolute_deprecated);
> ```

BTW Thinking about this now, these gymnastic aren't necessary for this current setup. They were necessary when I wanted to use stuff that *immediately* needed `pydrake.common.deprecation` (e.g. `DeprecateAttribute`, which wasn't the right solution here for a static property).

However, I would like to keep it, if possible, as a model for future deprecations.

**Review by SeanCurtis-TRI — COMMENTED** [review]
In order for me to *feature* review this, I'm going to have to take a significant run up on this corner of the code. Are you alright with that?

(And you've got CI woes.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS8Xg8qDv1iYU8KR03C:bz19chq)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Only rush is seeing if we can land this before 2021-02-01 so we don't lose 30 days to deprecation ;)

If you want you really hate what this looks like, at least this form of deprecation can be simplified.
Want me to simplify it? (git remembers, so I can just come back to this)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS8YeOQ5vOfNA_9qhoj:b-a6ifje)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI, @ggould-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS8ZTcjD-Fo50Z8Wt41:-MS8ZTcjD-Fo50Z8Wt42:bbnl38b) (no related file):*
Working: Setting a new revision to show diff between current gymnastics and simplified stuff.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS8ZTcjD-Fo50Z8Wt41:-MS8_4J_-lTz8PeZaDqf:biw5x2e) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Setting a new revision to show diff between current gymnastics and simplified stuff.
</blockquote></details>

OK This PR has been simplified. See r2 -> r3 for simplification.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
This isn't a question of love/hate. It's a question of the code involved. Looking at the code changes, I don't have a full appreciation of what is achieved or that the mechanism is correct. Those are two basic requirements in a feature reviewer. Given the meeting load today and the kaizen nature of tomorrow, the 2/1 deadline may be too tight.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS8_PSn6wCRbPpxVkSs:br31ruw)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
'aighty, I guess it's a hopeful "don't let it slip", but yes, I can wait til a 6/1 deprecation removal.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS8bUmp2uU3WwVaSxHB:by6nmbf)* status: LGTM missing from assignees ggould-tri(platform),SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
From my platform perspective, :lgtm:.  I don't love the code, but honestly I'm more impressed that it's even possible to deprecate a constant than I am sad at the implementation details.

> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MS9B6ES-no6RAnljEnM:b-ifq5ee)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/module_py.cc, line 99 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS9A9y972DfStWKHycK:-MS9A9y972DfStWKHycL:br0b2m1) ([raw file](https://github.com/robotlocomotion/drake/blob/fe5665dddd7e23bb7b625fe268873deb108eea61/bindings/pydrake/common/module_py.cc#L99)):*
> ```cpp
>   // cyclic dependencies (#7912). If you need functions that immediately import
>   // `pydrake.common.deprecation` (e.g. DeprecateAttribute, WrapDeprecated),
>   // please ping EricC.
> ```

nit:  github username or email address would be more helpful here as a contact method.
___
*[bindings/pydrake/common/module_py.cc, line 115 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS9AOAQ4AWL82aDdbyB:-MS9AOARCpQIpZ-yI1a0:brjfpsr) ([raw file](https://github.com/robotlocomotion/drake/blob/fe5665dddd7e23bb7b625fe268873deb108eea61/bindings/pydrake/common/module_py.cc#L115)):*
> ```cpp
>       .value("kRelative", drake::ToleranceType::kRelative,
>           doc.ToleranceType.kRelative.doc);
>   // Define these as properties so we can deprecate them
> ```

nit: Complete sentence needs a period.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/common/module_py.cc, line 99 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS9A9y972DfStWKHycK:-MSVbVeX37gpQQSp3eNG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fe5665dddd7e23bb7b625fe268873deb108eea61/bindings/pydrake/common/module_py.cc#L99)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  github username or email address would be more helpful here as a contact method.
</blockquote></details>

Done.
___
*[bindings/pydrake/common/module_py.cc, line 115 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14592#-MS9AOAQ4AWL82aDdbyB:-MSVbWVpDK7cJ7CTBhvH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fe5665dddd7e23bb7b625fe268873deb108eea61/bindings/pydrake/common/module_py.cc#L115)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit: Complete sentence needs a period.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Sorry about the slippage. I won't say that I understand the circular dependencies in play, but otherwise, I get it. 

:LGTM:

> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14592#-:-MSZgizf6y7XJ6JLi-4i:b-3tzmn9)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
