### PR TITLE
Make ViewerDrawTranslator accept position or state vectors.

### PR DESCRIPTION
**Pull request by avalenzu**
This cleans up a lot of our interactions with the class. Also modifies
DrakeVisualizer::PlaybackTrajectory() to accept either position or
(position, velocity) trajectories.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jwnimmer-tri for feature review.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686#-:-LB1ug56BztHWuR1jTT6:b-1tks9q)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@soonho-tri for platform review, please.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/rigid_body_plant/test/viewer_draw_translator_test.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8686#-LB1zU7o5j_HgtN-iK_D:-LB1zU7o5j_HgtN-iK_E:bjz197z) ([raw file](https://github.com/robotlocomotion/drake/blob/51ad85dec2d724773cd0e3b851fff1d7fb62d86c/multibody/rigid_body_plant/test/viewer_draw_translator_test.cc#L65)):*
> ```cpp
>   // Instantiates the generalized position vector corresponding to
>   // generalized_state.
>   BasicVector<double> generalized_position{
> ```

BTW `const` here might add clarity.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686#-:-LB1zatR372kTQg9YIZL:bz1ribg)*

**Comment by avalenzu** [comment]
Addressed @jwnimmer-tri's BTW.

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/test/viewer_draw_translator_test.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8686#-LB1zU7o5j_HgtN-iK_D:-LB234U19Jub0cE2ykvE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/51ad85dec2d724773cd0e3b851fff1d7fb62d86c/multibody/rigid_body_plant/test/viewer_draw_translator_test.cc#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `const` here might add clarity.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686#-:-LB235VSEuZhYXT7yy5K:b1kdp30)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8686#-:-LB2U9Iv6sr9Ipv0DdyV:bnfp4nl)*

**Pull request merged**
