### PR TITLE
[doc] Website enhancements

### LINKED ISSUE #14770: Website main page layout is bad on narrow/mobile browsers
To reproduce this, visit drake.mit.edu and narrow your browser window until the top menu vanishes and is replaced by the hamburger icon.  Now try to click on the install button.  Either nothing will happen or you'll go to a random page.  This is because the logic to show and hide the menu when you click the hamburger is merely hiding the menu but leaving it taking up room in the layout and leaving it clickable.

The issue appears to be that the css logic in `main.css` to show/hide the menu is using `visibility: hidden` (which makes the menu invisible) rather than `display:none` (which makes the menu not exist at all for rendering purposes.).  If you use devtools to set `display:none` on the `site-menu` element, it all seems to work correctly.

cc: @jamiesnape  

See also #14757.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Specifically:
- Add search box to landing page.
- Add "Learn More" to landing page.
- Fix invisible menu bar shadowing page elements.
- Clarify landing page display of library / API boxes.
- Fix italics to actually work.

Towards #14757.
Closes #14770.

FYI https://drake.mit.edu/documentation_instructions.html#previewing-changes to try it locally.

The merge plan is to squash everything, but for now I'm leaving separate commits to help make the history clear during review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Will do feature review! +@ericcousineau-tri 
(helps me w/ Platform Reviewer Checklist too :grimacing: )

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-Mwhljdy1cJiWDqtn5fk:b-aroslx)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass; only reviewing code. Unclear what's necessary and what may be redundant.
With lack of comments / commit info (from Echo Charlie?), hard to judge all of this as one lump fix. Also, very hard to delineate the lump of bullet points.

That being said, I'll only add nits for code; will do some very brief manual testing and say if anything looks crazy.

In the future, from reviewer perspective, it'd be nice to see video recording of what specifically to check.
Is that possible to request from Echo Charlie?

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-Mwhn_U27tl9kYWb41fj:b199qhz)* status: 7 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/_includes/header.html, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhnmR37r8sjrkIixcJ:-MwhnmR37r8sjrkIixcK:b-6m7ob3) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/_includes/header.html#L28)):*
> ```HTML
>           <div class="search-icon">
>             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 374.9 374.84">
>               <path d="M235 270a148.74 148.74 0 1 1 35-35l97.74 97.74a24.37 24.37 0 0 1 0 34.58l-.4.4a24.47 24.47 0 0 1-34.58 0L235 270Zm-86.22-7.47A113.75 113.75 0 1 0 35 148.75 113.75 113.75 0 0 0 148.75 262.5Z"/>
> ```

nit Should have comment stating what this is?

(is it a hamburger, an x, or something else?)
___
*[doc/_includes/header.html, line 38 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhnrDFBcyxwvw2s3ZG:-MwhnrDFBcyxwvw2s3ZH:b-6m7ob3) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/_includes/header.html#L38)):*
> ```HTML
>             <div class="search-close">
>               <svg height="20" width="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 373.61 373.57">
>                 <path d="M219.71 186.77 366.71 40a23.43 23.43 0 1 0-33.13-33.13l-146.77 147-146.77-147A23.43 23.43 0 0 0 6.9 40l147 146.77-147 146.77a23.43 23.43 0 1 0 33.14 33.13l146.77-147 146.77 147a23.43 23.43 0 1 0 33.13-33.13Z"/>
> ```

nit Should have comment stating what this is?

(is it a hamburger, an x, or something else?)
___
*[doc/assets/css/main.css, line 127 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhntiDAAau0F2bYPlQ:-MwhntiDAAau0F2bYPlR:b1qq3y4) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L127)):*
> ```CSS
> }
> 
> @media screen and (max-width: 600px) {
> ```

nit Unclear what this is doing at high level.
___
*[doc/assets/css/main.css, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-Mwho2DgE6uXFxefOtpu:-Mwho2DgE6uXFxefOtpv:b-pw36b6) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L336)):*
> ```CSS
> }
> 
> .site-menu li:not([class^="github-link"]) a:after {
> ```

Working: I don't get what `:not([class^=...])` is, nor if it's the simplest way to express the logic.
___
*[doc/assets/css/main.css, line 430 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhpQqTCMt4XtwpLaAR:-MwhpQqTCMt4XtwpLaAS:b-leyz0v) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L430)):*
> ```CSS
>   .site-menu {
>     opacity: 0;
>     visibility: hidden;
> ```

nit This doesn't seem to leverage @ggould-tri's suggested solution in #14770, using `display: none`.

Without more information in commit / comments, I can't tell if that omission is on purpose or on accident.
___
*[doc/assets/css/main.css, line 928 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhrP5T05u32VSwTotI:-MwhrP5T05u32VSwTotJ:b-433xfa) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L928)):*
> ```CSS
> }
> 
> .markdown-body i,
> ```

nit Unclear why this is necessary. It seems like we (or upstream markdown styling) broke this.

If hard to justify, at least denote this as mystery hack?
___
*[doc/assets/css/main.css, line 954 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhqcAGB0embfxq8dA-:-MwhqcAGB0embfxq8dA0:b5xq0l3) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L954)):*
> ```CSS
>   visibility: hidden;
> 
>   transition: all 0s cubic-bezier(0.2, 0.3, 0, 1) 0s;
> ```

nit I don't understand why we use `transiton-duration: 0s` here; why do we specify transition for no animation? Is this a mystery hack, or just old code?

https://developer.mozilla.org/en-US/docs/Web/CSS/transition
https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665)* status: 7 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[doc/assets/css/main.css, line 954 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhrsrS2SztcaHBkF42:-MwhrsrS2SztcaHBkF43:b-7sezmn) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L954)):*
> ```CSS
>   visibility: hidden;
> 
>   transition: all 0s cubic-bezier(0.2, 0.3, 0, 1) 0s;
> ```

BTW No idea what `all` implies for discrete values, like `visibility`.

**Review by EricCousineau-TRI — COMMENTED** [review]
Did local preview on 95559091fd, comparing against currently deployed website.
Comparison on Firefox 97.0 on Ubuntu 20.04.

- Search box
  - Old: No search.
  - New: Fancy animated search bar!
- "Learn More"
  - Old: Not there.
  - New: It's there!
- Phantom div preventing clicking on links:
  - Old: Still problem for narrow window.
  - New: Fixed!
- Landing page API boxes
  - Old: Just URLs and stuff.
  - New: Boxes! Font!
- Italics, checking on `/clion.html`, for text "single clickable link" (had to search for this tho)
  - Old: `*single*` did not render as italic
  - New: It renders italic!

:lgtm: feature per above bullet points, with minor code nits

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-MwhtadK5aiZsWUHH66U:b-wlqz60)* status: 7 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I don't have any answers for you on the CSS questions -- I received some new files, and I pushed them up here (with fixes for whitespace / diff-minimization).  As long as the site empirically tests on fine while browsing, I am not going to bother trying to understand the CSS.  You are welcome to further investigate those discussions as you deem worthwhile.

**Comment by EricCousineau-TRI** [comment]
Request for review was originally unclear, but fair points. I have no desire to investigate beyond what I've mentioned, so feel free to dismiss nits.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665)* status: 4 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[doc/assets/css/main.css, line 336 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-Mwho2DgE6uXFxefOtpu:-MwiDQr3-CqqhgoXNI29:byd47yj) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L336)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I don't get what `:not([class^=...])` is, nor if it's the simplest way to express the logic.
</blockquote></details>

OK Dismissing this blocking item. (not going to investigate)

**Review by jwnimmer-tri — COMMENTED** [review]
You're right, I should have said that my main interest is in testing and visual conformation, and an overall sanity check; less so the details of the implementation changes.  Thanks for your help checking it out.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-MwlYogCETtwGqbEk1yV:b95e7tu)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[doc/assets/css/main.css, line 928 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhrP5T05u32VSwTotI:-Mwl_Jir4V0OjOv_YxD3:bvupi0r) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L928)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this is necessary. It seems like we (or upstream markdown styling) broke this.

If hard to justify, at least denote this as mystery hack?
</blockquote></details>

OK checking in Firefox inspector and disabling this markdown-body rule, it's this stanza from `main.css:L16` that defeats the italics by otherwise:
```css
* {
  /* ... */
  font: inherit;
}
```
___
*[doc/assets/css/main.css, line 954 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16665#-MwhqcAGB0embfxq8dA-:-Mwlf7Xr7LVIddbMW_36:b-35j8rm) ([raw file](https://github.com/robotlocomotion/drake/blob/95559091fd64664d87b1e51b28b86a35ab77f387/doc/assets/css/main.css#L954)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't understand why we use `transiton-duration: 0s` here; why do we specify transition for no animation? Is this a mystery hack, or just old code?

https://developer.mozilla.org/en-US/docs/Web/CSS/transition
https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration

</blockquote></details>

OK These specify how quickly the menu bar disappears when you click the magnifying glass icon.

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-Mwlso-u4xWGH_Bw3AzC:bk7giky)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Checked for the items mentioned in the commit message.
Clicked around the website trying to break it.
Did not look at the code.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16665#-:-Mwm1ZOW5D-a8tSNWBFr:b-8zaaev)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
Thanks!
I'll call this good enough for now (I have also tested it).
We can submit fix-forwards if others find any problems.

I'll squash it now.

**Pull request merged**
