### PR TITLE
minor tweaks to make cpp urdf more useful

### PR DESCRIPTION
**Pull request by RussTedrake**

### CODE REVIEW

**Comment by avalenzu** [comment]
Looks good to me.

**Comment by avalenzu** [comment]
A heads up for @RussTedrake and @patmarion: Unfortunately, ccfed7b breaks ddapp, which overloads `addURDF` and uses the `_urdf_model` argument. `_urdf_model` now exists only inside `addURDFFromXML`. We'll need to resolve this befoire we can merge RobotLocomotion/drake into mitdrc/drake again.

**Comment by RussTedrake** [comment]
Good to know.  Let's chat about it today.

**Comment by RussTedrake** [comment]
@avalenzu - please go ahead and revert the change to URDFRigidBodyManiplator if this is blocking you.  I have a much more substantial change that is almost ready to go ( https://github.com/RussTedrake/drake/commits/no_boost ), so we should probably defer worrying about the relationship to ddapp until that's ready.

**Pull request merged**
