### PR TITLE
Add MultibodyTree::CalcJacobianSpatialVelocity().

### PR DESCRIPTION
**Pull request by avalenzu**
Moves the guts of `CalcRelativeFrameGeometricJacobian()` into a new private method `CalcRelativeFrameJacobian()` which is called by both the geometric and analytical public methods.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10122)

### CODE REVIEW

**Comment by avalenzu** [comment]
___
*[multibody/multibody_tree/multibody_tree.h, line 2108 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10122#-LSoYzSjCtd9wZVI4CXY:-LSoiTuCEg4itneAZp7s:brh6wfx) ([raw file](https://github.com/robotlocomotion/drake/blob/aed3ae22f44e796057dfe86d242603f13e7ac5b2/multibody/multibody_tree/multibody_tree.h#L2108)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This first sentence doesn't seem necessary given you explain what Bp is two sentences later. I would rather use this sentence for a "brief" description of what this method does. Something as brief and simple like "Computes the geometric Jacobian for a point instantaneously moving with a given frame." would suffice I think.
</blockquote></details>

Wouldn't "Computes the geometric Jacobian for a point" imply a 3 x nz result, since points don't have angular velocity?

**Comment by avalenzu** [comment]
___
*[multibody/multibody_tree/multibody_plant/test/multibody_plant_jacobians_test.cc, line 220 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10122#-LSobfJ-D0BxjWOWo7gz:-LSojcr_AGp7iUPyWugV:b-bhhreg) ([raw file](https://github.com/robotlocomotion/drake/blob/aed3ae22f44e796057dfe86d242603f13e7ac5b2/multibody/multibody_tree/multibody_plant/test/multibody_plant_jacobians_test.cc#L220)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit: maybe worth setting arbitrary non-zero velocities for this test. 
</blockquote></details>

Just to verify that they don't have any effect on the calculations?

**Comment by avalenzu** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/10122#-LT4FzTo5kUpneZumqYn:-LT4FzTp0yMG5Vax_EBV:b-ao8uo6) (no related file):*
Temporarily withdrawing platform LGTM until I can review the rework.

---

**Pull request merged**
