### PR TITLE
Install automotive models

### PR DESCRIPTION
**Pull request by clalancette**
This PR fixes up the command:

`bazel run //:install /path/to/dir`

So that it installs the automotive models along with everything else; we'll want to use the installed models in Delphyne.  The models end up in the subdirectory `share/drake/automotive/models`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7043)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This should probably use the https://github.com/RobotLocomotion/drake/blob/ff6b7a5852721d24fcc2ba16f1e74bf015b16fcd/drake/examples/BUILD#L42-L58 listing and target naming for choosing which examples' models go into Drake's release.  Ideally it would also use the `install_data()` helper macro as per other examples, though that could be a follow up.  The `examples/BUILD` inventory is the important part.

I am happy to take feature review of this, unless you or Daniel have someone else in mind.

**Comment by clalancette** [comment]
@jwnimmer-tri I don't think we had anyone else lined up for review, so thanks for volunteering.  I'll take another look at `drake/examples/BUILD`, and modify this PR accordingly.

**Comment by clalancette** [comment]
@jwnimmer-tri Please take a look at my latest commit.  I think it is more like what is going on in `drake/examples/BUILD`; let me know if this is what you were envisioning.  Thanks.

**Comment by jwnimmer-tri** [comment]
It's closer (and probably close enough to start a review).  I'll look in more detail sometime later today.

**Comment by jwnimmer-tri** [comment]
So yeah, I misled you somewhat.  Sorry!  Somehow I had in my head that `drake/automotive` was really `drake/examples/automotive` which would have meant that merely adding it to the list of examples would be the goal.  But of course automotive is top-level, not an example, so shouldn't go into that same list.  I've made a few notes below where I steered you in the wrong direction.

---

Reviewed 1 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/BUILD, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLPGb3B8Jrbbv0kLja:-KuLPGb3B8Jrbbv0kLjb:b-sh4roy) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/BUILD#L457)):*
> ```Python
> INSTALLED_MODEL_PACKAGES = [
>     "//drake/automotive/models",
> ]
> ```

You probably put this here because of my bad advice.  Given that there's only one models folder, and unlikely to be a list of them, I don't think this listvar is doing us any good.

---

*[drake/automotive/models/BUILD, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuL7pqkYQVOJ7GDWqjr:-KuL7pqkYQVOJ7GDWqjs:bvs2w18) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

It's not clear why the `:install_data` (and the model filegroup(s)) rules are put into an `automotive/models/BUILD` file, whereas most `drake/examples` and other folders keep it in the top-level folder, such as `automotive/BUILD`.

(I suspect this was also me misleading you.)
((But if there is a good reason, please add a comment.))

---

*[drake/automotive/models/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLCDLY6vfaHfvazNN_:-KuLCDLZmMMGyu_WU2RM:bkcomut) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L22)):*
> ```Python
>     ]),
>     tools = ["//drake/automotive/maliput/utility:yaml_to_obj"],
> )
> ```

If we're anyway not going to put this genrule into the `automotive/BUILD` directory (and I support carving it out of there into its own BUILD file), it should live at `automotive/models/speed_bump/BUILD` to be as close to its source files as possible.

---

*[drake/automotive/models/BUILD, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuL88Ru8MeVeoG9oGU0:-KuL88Ru8MeVeoG9oGU1:b-8h7vre) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L24)):*
> ```Python
> )
> 
> install_data(additional_prod_models = [
> ```

BTW Probably a newline after the `(` would be more conventional.

---

*[tools/install_data.bzl, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLDLdnVPqEogjZh13J:-KuLDLdnVPqEogjZh13K:b1j4che) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/tools/install_data.bzl#L9)):*
> ```Python
>     prod_models_prefix = "prod_",
>     test_models_prefix = "test_",
>     additional_prod_models = [],
> ```

Missing API documentation (in the below docstring).

---

*[tools/install_data.bzl, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLDg35nK-0pWBqCoNc:-KuLDg35nK-0pWBqCoNd:b-jyifoq) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/tools/install_data.bzl#L9)):*
> ```Python
>     prod_models_prefix = "prod_",
>     test_models_prefix = "test_",
>     additional_prod_models = [],
> ```

FYI In other bzl rules, we have used `extra_` as the adjective for things to tack on the end.  Consider using that name here for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-:-KuLMI-mX9MpO3muqISn:b-988245)*

**Comment by clalancette** [comment]
No problem :).  I have responses below, I'll do another update here and see if we can get closer to what is going on in `drake/examples`

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/BUILD, line 457 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLPGb3B8Jrbbv0kLja:-KuLX8OiYCKi9rO3Wdwt:b-5n0l8l) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/BUILD#L457)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

You probably put this here because of my bad advice.  Given that there's only one models folder, and unlikely to be a list of them, I don't think this listvar is doing us any good.
</blockquote></details>

Yeah, will fix.

---

*[drake/automotive/models/BUILD, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuL7pqkYQVOJ7GDWqjr:-KuLT53mxlnPwKG6h7s8:bwpym2i) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's not clear why the `:install_data` (and the model filegroup(s)) rules are put into an `automotive/models/BUILD` file, whereas most `drake/examples` and other folders keep it in the top-level folder, such as `automotive/BUILD`.

(I suspect this was also me misleading you.)
((But if there is a good reason, please add a comment.))
</blockquote></details>

There is a reason, but not a very strong one.  I originally modeled this after what is going on in `drake/manipulation`, where there are BUILD files down in the `models` and `models/**` subdirectories.  However, I really don't have a strong preference, so if you think it is better at the `drake/automotive` level, I'm happy to do that.

---

*[drake/automotive/models/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLCDLY6vfaHfvazNN_:-KuLWfrpRF8w3jerMgV6:b-usffwr) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If we're anyway not going to put this genrule into the `automotive/BUILD` directory (and I support carving it out of there into its own BUILD file), it should live at `automotive/models/speed_bump/BUILD` to be as close to its source files as possible.
</blockquote></details>

Sorry, I'm not sure I understand this comment in combination with the previous one.  Could you elaborate a bit more on what you mean here?

---

*[drake/automotive/models/BUILD, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuL88Ru8MeVeoG9oGU0:-KuLXOuLWoUO1MHd1xAV:b-bqivcu) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Probably a newline after the `(` would be more conventional.
</blockquote></details>

Will fix.

---

*[tools/install_data.bzl, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLDLdnVPqEogjZh13J:-KuLU0K4tY4ydKGSoq-G:b-a5bvkr) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/tools/install_data.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing API documentation (in the below docstring).
</blockquote></details>

Thanks, will fix.

---

*[tools/install_data.bzl, line 9 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLDg35nK-0pWBqCoNc:-KuLU1MHrDlVZWn7GCkl:b-emvm5o) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/tools/install_data.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI In other bzl rules, we have used `extra_` as the adjective for things to tack on the end.  Consider using that name here for consistency.
</blockquote></details>

Sounds good, I'll switch to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-:-KuLX9_q7KpZL0DGJV4f:baqsy1c)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/models/BUILD, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuL7pqkYQVOJ7GDWqjr:-KuLYHfPQb0WDpaqOqcK:bj9z976) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L1)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

There is a reason, but not a very strong one.  I originally modeled this after what is going on in `drake/manipulation`, where there are BUILD files down in the `models` and `models/**` subdirectories.  However, I really don't have a strong preference, so if you think it is better at the `drake/automotive` level, I'm happy to do that.
</blockquote></details>

I think if we were going to try to carve up `automotive/models` models into distinct pieces, with their own BUILD files, then we could do it that way.  But until such a time, it'd be more similar to other in-tree stuff if this were moved up a level (possibly with the exception of the speed_bump).

---

*[drake/automotive/models/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLCDLY6vfaHfvazNN_:-KuLY_EdgFW7Io1YZwA6:bdt3pn2) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L22)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Sorry, I'm not sure I understand this comment in combination with the previous one.  Could you elaborate a bit more on what you mean here?
</blockquote></details>

I'm suggesting that the `:install_data` and `:prod_models` and such live one level higher, where they used to be.  But, you could argue that `speed_bump` folder should gain a `BUILD` file (with this genrule) in order to put the genrule closer to the files its related to, and I'd be fine with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043)*

**Comment by clalancette** [comment]
I've updated based on the feedback below; another review would be appreciated.  Thanks!

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/models/BUILD, line 22 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuLCDLY6vfaHfvazNN_:-KuQKKy_5h7CUQi0CEed:bj6mjx4) ([raw file](https://github.com/robotlocomotion/drake/blob/78d31faec0f7e53267b3ab4405e9d018695d4996/drake/automotive/models/BUILD#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm suggesting that the `:install_data` and `:prod_models` and such live one level higher, where they used to be.  But, you could argue that `speed_bump` folder should gain a `BUILD` file (with this genrule) in order to put the genrule closer to the files its related to, and I'd be fine with that.
</blockquote></details>

I see, thanks for the clarification.  For now, I've opted for the simpler thing, which is to just keep everything in automotive/BUILD.  Let me know what you think about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-:-KuQKT_n2enpmJTwm_FW:bcsit8k)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/BUILD, line 458 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQO-DjyRHMGhM8UYbs:-KuQO-DjyRHMGhM8UYbt:bf3005a) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6119fc8b6cf1053216461ff22c89bb4629ff66/drake/automotive/BUILD#L458)):*
> ```Python
>     name = "speed_bump_genrule",
>     srcs = ["models/speed_bump/speed_bump.yaml"],
>     outs = ["models/speed_bump/speed_bump.obj", "models/speed_bump/speed_bump.mtl"],
> ```

FYI Line too long (I think CI will ding you for this).  Your `bazel test //...` should be showing this to you locally, but for faster turnaround try `bazel test --config lint //...`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQOsD8NpRs1mtLMQrs:-KuQOsD8NpRs1mtLMQrt:bakzdns) (no related file):*
Hmm.  I should probably test running the demo locally before merging.  Stay tuned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-:-KuQOoT7ieUhJHSxxtyj:b-blc83)*

**Comment by clalancette** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQOsD8NpRs1mtLMQrs:-KuQQkZwBaTAm8Q-DFQs:b-9a049y) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  I should probably test running the demo locally before merging.  Stay tuned.
</blockquote></details>

Yeah, good point.  I ran a couple of different demos (automotive_demo and car_sim_lcm, mostly), but more testing would be better.

---

*[drake/automotive/BUILD, line 458 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQO-DjyRHMGhM8UYbs:-KuQQhdKlptGIYqUhKOX:bglyryc) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6119fc8b6cf1053216461ff22c89bb4629ff66/drake/automotive/BUILD#L458)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Line too long (I think CI will ding you for this).  Your `bazel test //...` should be showing this to you locally, but for faster turnaround try `bazel test --config lint //...`.
</blockquote></details>

Ah, thanks.  I forgot to re-run that, will do that now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043)*

**Comment by clalancette** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 458 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQO-DjyRHMGhM8UYbs:-KuQY-721JMmrAjmneVQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aa6119fc8b6cf1053216461ff22c89bb4629ff66/drake/automotive/BUILD#L458)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Ah, thanks.  I forgot to re-run that, will do that now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043)*

**Comment by sammy-tri** [comment]
:lgtm: (pending resolution of the remaining open issues)

---

Reviewed 1 of 4 files at r1, 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-:-KuQ_Q-w6AvRcFvxdUpH:buroo95)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7043#-KuQOsD8NpRs1mtLMQrs:-KuRrJhxCYzFmkWLdOTS:bq77ce0) (no related file):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Yeah, good point.  I ran a couple of different demos (automotive_demo and car_sim_lcm, mostly), but more testing would be better.
</blockquote></details>

OK I tried out a few demos from the README.md.

The `bazel run //drake/automotive:demo` seem fine.

I also tried the speed_bump demo.  The good news is that this PR making things better.  The bad news is that master was already broken.

Before this PR:
```
INFO: Running command line: bazel-bin/drake/automotive/car_sim_lcm --with_speed_bump
...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing file "/home/jwnimmer/.cache/bazel/_bazel_jwnimmer/4bbd761eea63e78e142bda3817e31ec0/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/automotive/car_sim_lcm.runfiles/drake/drake/automotive/models/speed_bump/speed_bump.obj" : WARN: Material file [ /home/jwnimmer/.cache/bazel/_bazel_jwnimmer/4bbd761eea63e78e142bda3817e31ec0/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/automotive/car_sim_lcm.runfiles/drake/drake/automotive/models/speed_bump/speed_bump.mtl ] not found.
WARN: Failed to load material file(s). Use default material.
```

After this PR:
```
INFO: Running command line: bazel-bin/drake/automotive/car_sim_lcm --with_speed_bump
...
[2017-09-19 21:18:16.169] [console] [warning] Unable to compute normal. Triangle with OBJ indices: 8041, 8042, 8043 is too small.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to triangulate face number 6670 in '/home/jwnimmer/.cache/bazel/_bazel_jwnimmer/4bbd761eea63e78e142bda3817e31ec0/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/automotive/car_sim_lcm.runfiles/drake/drake/automotive/models/speed_bump/speed_bump.obj'. See log for details.
```

So yeah, we have some regression coverage missing.  But I don't think it should hold up this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7043)*

**Comment by clalancette** [comment]
Excellent, thank you @jwnimmer-tri

**Pull request merged**
