### PR TITLE
[parsing,sensors,visualization] Remove deprecated code 2023-02

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from:
- #18160
- #17251
  - #18226
- #18069
  - #18228

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18689)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please. (Tuesday on-call is fine; this can't land until Tuesday night anyway.)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:
+(status: do not merge) 

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18689#-:-NN83tWR-1ST6jfvUxjQ:b-lj1xfp)* status: labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18689#-:-NN84Cmk8ah_kx2Xq_kB:b-b9fcpn)* status: labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: removal of deprecated) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18689#-:-NN84HCF8xmdX2Pv1kDK:b-bk6sdp)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
