### PR TITLE
Enable snopt when building wheels

### LINKED ISSUE #15961: Enable SNOPT in pip wheel
For the https://github.com/RobotLocomotion/pip-drake build, we should build Drake using ` --define=WITH_SNOPT=ON` so that the binaries contain SNOPT, just like all of our other pre-built binaries.

This means that the build will require credentials, which will affect both the developer documentation (whl playbook) as well as #15960.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Modify wheel build scripts to enable snopt, using ssh agent forwarding from the build host for authentication. Modify provisioning to enable ssh and to permit accessing github.

Note that this requires BuildKit or a recent version of Podman. It also requires that the builds are run in an environment with an active ssh agent which is able to fetch snopt from Github without additional configuration (i.e. must work without `.ssh/config`).

Fixes #15961.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16079)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16079)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16079#-MoFlK-c8YUGVUz64fxQ:-MoFlK-dEpIZ4Vgow9Nc:b-i2s75c) (no related file):*
Could you add a regression test for this (to `test-wheel.sh`, probably)?

My best guess:

```python
assert pydrake.all.SnoptSolver().available()
```

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: this passed for me locally.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16079#-:-MoGSSiC33fNtX1dDe_I:bb0wpgq)* status: 2 unresolved discussions, missing label for release notes (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16079#-MoFlK-c8YUGVUz64fxQ:-MoGSkuyBko_BUab2pgy:b-u8jak0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Could you add a regression test for this (to `test-wheel.sh`, probably)?

My best guess:

```python
assert pydrake.all.SnoptSolver().available()
```

</blockquote></details>

This one seemed like the right idea, from my testing.

```python
assert pydrake.all.SnoptSolver().available(), "Missing SNOPT"
```

---

**Comment by jwnimmer-tri** [comment]
(I should also note for the record that during my local testing, I didn't need to customize any settings, e.g., ssh stuff.  Whatever Ubuntu 20.04 is doing out-of-the-box seems to work just fine.)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16079)* status: 2 unresolved discussions, missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16079#-MoFlK-c8YUGVUz64fxQ:-MoJrG4a6j7-Bqw2ifon:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This one seemed like the right idea, from my testing.

```python
assert pydrake.all.SnoptSolver().available(), "Missing SNOPT"
```
</blockquote></details>

Done.

---

**Comment by mwoehlke-kitware** [comment]
I'm sure you had to do something, but probably something you did a long time ago. If it works for you, you a) must already have ssh-agent set up such that you can clone snopt using ssh authentication to github, and b) don't have a more exotic setup where ssh tries to send a key that causes a rejection without additional configuration.

"Left to its own devices", ssh sends the key to my *personal* user account (i.e. not this one) first, which does not (and shouldn't) have permission to clone snopt, resulting in a rejection. However, since the *key* was accepted, the clone stops at that point rather than continuing to try other keys. My `.ssh/config` has rules to "fix" this, but that doesn't work inside Docker.

Many users probably won't have that problem, but I don't believe Ubuntu provides you with an ssh key by default, and I don't know that it adds keys to your agent by default either. I suspect non-GUI logins don't even have `ssh-agent` running, though GUI logins probably do. At minimum, you'd need to tell Github about your key. Granted, someone who routinely use SSH to access Github may well have everything already set up, but someone that typically uses HTTPS might not.

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: yes) 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16079#-:-MoK3XB10Bo3YqUZcTBh:b-c7f1bi)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), exempt from platform review (waiting on @mwoehlke-kitware)

**Pull request merged**
