### PR TITLE
[tools] Add opt-in build flags (and unit test) for OpenMP

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14858.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Interesting, lots of timeouts.  Perhaps one of our third-party dependencies has OpenMP parallelization directives lying dormant.

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri for feature review of the C++ code please (the new unit test).
+@rpoyner-tri for feature review of the everything else, please (the build system & doc changes).

(Either of you should feel free to comment on anything in the pull request, but please cover those areas specifically.)

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),calderpg-tri (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`common/test/openmp_test.cc` line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lNnC1E4pb6sNb_p-h:-N0lNnC1E4pb6sNb_p-i:b-dtc7hz) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L20)):*
> ```cpp
> #else
> constexpr bool kHasOpenmp = false;
> // TODO(jwnimmer-tri) This should probably be a Drake helper function wrapper
> ```

fyi you can use or wrap equivalent helpers from `common_robotics_utilities/openmp_helpers.hpp`
___
*[`common/test/openmp_test.cc` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lO7e23L26uvwnq0_w:-N0lO7e23L26uvwnq0_x:b-ioa3ry) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L34)):*
> ```cpp
> 
>   // Populate the storage, in parallel.
>   constexpr int num_threads = 4;
> ```

Is there a reason for manually specifying the number of threads here and the number of cpus for the test, versus specifying `OMP_NUM_THREADS=4` for the test and letting the `omp parallel` use all available threads? Or, alternatively something like  CRU's`ChangeOmpNumThreadsWrapper(4)`/an explicit call to `omp_set_num_threads(4)`?
___
*[`common/test/openmp_test.cc` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lPtih3QRU6plmXjIM:-N0lPtih3QRU6plmXjIN:bp5oksm) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L42)):*
> ```cpp
>   }
> 
>   // Confirm how many threads were used.
> ```

btw This seems to be testing both that the expected number of threads were used, _and_ that their thread numbers were the expected [0] or [0, 1, 2, 3]. If that is intended, perhaps the comment should reflect this. (If we only cared about number of threads run, presumably something more direct like
```
EXPECT_EQ(std::unordered_set<int>(outputs.begin(), outputs.end()).size(), kHasOpenmp ? num_threads : 1)
```
would be enough)
___
*[`tools/workspace/csdp/package.BUILD.bazel` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lNEKJ6JzlUhckHNJh:-N0lNEKJ6JzlUhckHNJi:b25sc1) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/tools/workspace/csdp/package.BUILD.bazel#L57)):*
> ```
>     ],
>     copts = [
>         "-fno-openmp",
> ```

It looks like OpenMP was already disabled in these copts due to the use of `longjmp`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),calderpg-tri (waiting on @calderpg-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[`common/test/openmp_test.cc` line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lNnC1E4pb6sNb_p-h:-N0lS-MS8-IW3LPNr4Mo:b-a5c8nf) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L20)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

fyi you can use or wrap equivalent helpers from `common_robotics_utilities/openmp_helpers.hpp`
</blockquote></details>

Yup, I had that in mind but should have written it down, too.
___
*[`common/test/openmp_test.cc` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lO7e23L26uvwnq0_w:-N0lU6PF4GKNX7AMSoEU:b-hiwl8m) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L34)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Is there a reason for manually specifying the number of threads here and the number of cpus for the test, versus specifying `OMP_NUM_THREADS=4` for the test and letting the `omp parallel` use all available threads? Or, alternatively something like  CRU's`ChangeOmpNumThreadsWrapper(4)`/an explicit call to `omp_set_num_threads(4)`?
</blockquote></details>

That would probably be an improvement.  I'll take it for a spin; stay tuned.
___
*[`common/test/openmp_test.cc` line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lPtih3QRU6plmXjIM:-N0lSs2X-AaC5HF-etZM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L42)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

btw This seems to be testing both that the expected number of threads were used, _and_ that their thread numbers were the expected [0] or [0, 1, 2, 3]. If that is intended, perhaps the comment should reflect this. (If we only cared about number of threads run, presumably something more direct like
```
EXPECT_EQ(std::unordered_set<int>(outputs.begin(), outputs.end()).size(), kHasOpenmp ? num_threads : 1)
```
would be enough)
</blockquote></details>

Done.
___
*[`tools/workspace/csdp/package.BUILD.bazel` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lNEKJ6JzlUhckHNJh:-N0lRg_g3DQucxJ_dQr4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/tools/workspace/csdp/package.BUILD.bazel#L57)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

It looks like OpenMP was already disabled in these copts due to the use of `longjmp`
</blockquote></details>

Done.

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),calderpg-tri (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),calderpg-tri (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 3 of 9 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606#-:-N0lYh_GCxA4dAK76iSq:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri (waiting on @calderpg-tri and @jwnimmer-tri)

___
*[`common/test/openmp_test.cc` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lO7e23L26uvwnq0_w:-N0larPICV-pnrriRyyt:bbrmt5k) ([raw file](https://github.com/robotlocomotion/drake/blob/11a4490fb86c4ff16a418c8d1c6fa27837a92590/common/test/openmp_test.cc#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That would probably be an improvement.  I'll take it for a spin; stay tuned.
</blockquote></details>

Done.

I also reduced this test to just 2 threads, in case anyone ever runs it on a potato that doesn't have 4 cpus.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri (waiting on @calderpg-tri and @jwnimmer-tri)

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606#-:-N0ldJri88vyeO3TcxbS:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

I expect the CI failure to resolve on its own with some infrastructure changes, no more code changes planned for this PR.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 

> Reviewed 2 of 7 files at r1, 2 of 9 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606#-:-N15uTkt85aomEaV3qU0:bzus18)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16606)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),calderpg-tri,xuchenhan-tri(platform) (waiting on @calderpg-tri, @rpoyner-tri, and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16606#-N0lT2k9Bi-BZ8JzEUBm:-N1KHIFDDK1Amhstabwf:b6cdlm2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

The CI error `/usr/bin/ld.gold: error: cannot find -lomp` is because the Clang 12 transition is still in flight.  (We can only have one of Ubuntu Clang's OMP development packages installed concurrently, and for the moment that's omp-12.)
</blockquote></details>

Given the current state of Clang in CI, there is no good way to deal with it in this PR.  I'm going to add a GCC-specific hack to drake-ci shortly, so that we can at least have CI coverage of that starting point.

---

**Pull request merged**
