### PR TITLE
Add ODR test for pydrake.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
See comments in `odr_test.py` in this pull request for more details.
Relates #6465.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7605)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@soonho-tri for platform review, please.

\cc @jamiesnape @fbudin69500 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0Kkm5Ir-hWMUm2Da-x:b-ai8m04)*

**Comment by soonho-tri** [comment]
I got a build error in my local machine.
```
$ bazel test //bindings/pydrake:odr_test
'//bindings/pydrake:odr_test_module.so' failed (Exit 1)
bindings/pydrake/test/odr_test_module_py.cc:3:10: fatal error: 'drake/bindings/pydrake/symbolic_types_py.h' file not found
#include "drake/bindings/pydrake/symbolic_types_py.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0KmZsl4vhfkfXKbIKP:br9rzwo)*

**Comment by soonho-tri** [comment]
@ericcousineau-tri , could you check why CI does not detect the problem that I mentioned above? I checked that I can reproduce the problem in an Ubuntu box.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0KqPr7SqluTQJ46IT8:b-yucb9f)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/BUILD.bazel, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0KqNlUWoC8dJi8aTcR:-L0KqNlVu0Le5gEEwt9G:bh4k26u) ([raw file](https://github.com/robotlocomotion/drake/blob/8cd861be5030a740fa14b410391bd43309230320/bindings/pydrake/BUILD.bazel#L142)):*
> ```Python
>     cc_so_name = "odr_test_module",
>     cc_srcs = ["test/odr_test_module_py.cc"],
> )
> ```

BTW Can we do `testonly = 1` here?

---

*[bindings/pydrake/test/odr_test.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0Kr2frEIsX8GUEJAAu:-L0Kr2frEIsX8GUEJAAv:b2fev1f) ([raw file](https://github.com/robotlocomotion/drake/blob/8cd861be5030a740fa14b410391bd43309230320/bindings/pydrake/test/odr_test.py#L19)):*
> ```Python
> import pydrake.symbolic as sym
> # This module also uses `//drake/common:symbolic`, but in a separate *.so.
> # If we violate ODR, then this should link in a new definition.
> ```

s/should/might/; in general, we can violate ODR but still luck out at runtime.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by soonho-tri** [comment]
OK. never mind. It was just the case that bazel builds didn't finish.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0Ksf4vdKeh8v5pSnpe:b-iq4erb)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0KqNlUWoC8dJi8aTcR:-L0KzFJ_gE_lNVSVLmTf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8cd861be5030a740fa14b410391bd43309230320/bindings/pydrake/BUILD.bazel#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Can we do `testonly = 1` here?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/odr_test.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0Kr2frEIsX8GUEJAAu:-L0KzGa7tHMXRpyKVtd-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8cd861be5030a740fa14b410391bd43309230320/bindings/pydrake/test/odr_test.py#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

s/should/might/; in general, we can violate ODR but still luck out at runtime.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0L1BVPv0co2_ePwGwI:-L0L1BVPv0co2_ePwGwJ:bxv5ynd) ([raw file](https://github.com/robotlocomotion/drake/blob/1e1ed3dd6cad4267d90f3071f252635664f4ada1/bindings/pydrake/BUILD.bazel#L142)):*
> ```Python
>     testonly = 1,
>     cc_deps = [
>         ":symbolic_types_py",
> ```

FYI Not a new defect, but it took me a while to understand this.  It is a header-only cc_library by its name `_py` implies that its a python target, not a C++ target.  Maybe worth a rename, now or future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0L1RrcHwi94ieK5Khn:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0L3nmfoyW3V4r0rV45:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/BUILD.bazel, line 140 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0LKAWdGUD7wr65Cs22:-L0LKAWdGUD7wr65Cs23:b28tums) ([raw file](https://github.com/robotlocomotion/drake/blob/1e1ed3dd6cad4267d90f3071f252635664f4ada1/bindings/pydrake/BUILD.bazel#L140)):*
> ```Python
> drake_pybind_library(
>     name = "odr_test_module_py",
>     testonly = 1,
> ```

BTW Needs add_install = False.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 140 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0LKAWdGUD7wr65Cs22:-L0LRWVWxlDtDrpx0vjw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e1ed3dd6cad4267d90f3071f252635664f4ada1/bindings/pydrake/BUILD.bazel#L140)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Needs add_install = False.
</blockquote></details>

Done.

---

*[bindings/pydrake/BUILD.bazel, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-L0L1BVPv0co2_ePwGwI:-L0LRWFfx-wVU7YMXoWh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e1ed3dd6cad4267d90f3071f252635664f4ada1/bindings/pydrake/BUILD.bazel#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Not a new defect, but it took me a while to understand this.  It is a header-only cc_library by its name `_py` implies that its a python target, not a C++ target.  Maybe worth a rename, now or future.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Comment by soonho-tri** [comment]
FYI, CI failed with the following message:
```
14:24:13 ERROR: /home/ubuntu/workspace/linux-xenial-gcc-bazel-experimental/src/bindings/pydrake/solvers/BUILD.bazel:43:1: no such target '//bindings/pydrake:symbolic_types_py': target 'symbolic_types_py' not declared in package 'bindings/pydrake' (did you mean 'symbolic_types_py.h'?) defined by /home/ubuntu/workspace/linux-xenial-gcc-bazel-experimental/src/bindings/pydrake/BUILD.bazel and referenced by '//bindings/pydrake/solvers:_mathematicalprogram_py.so'
```

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605#-:-L0OV3_BcfLxQzSjTnUz:b-h0dmmg)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7605)*

**Pull request merged**
