### PR TITLE
kcov support: Add explicit failure for kcov:#339 situations

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FYI @ggould-tri is something like this worth doing to save buildcop effort?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhnbDpS3aQ60IvcM7UM:bpjomxw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by ggould-tri — COMMENTED** [review]
Ooh, probably!  It would certainly save Nimmer from having to initiate every new buildcop into the cult of 339.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhnbiZy9eF9Mn2dmPB2:b1qj4i0)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for feature review.
FYI @jwnimmer-tri @ericcousineau-tri  script/tooling expertise

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhndwjjAv-DTLTsHcbi:btwkxym)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnenOCAmuuz7bX5-sF:-MhnenOD3sf9NU7Ddk7K:bfvaaw1) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.

---

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnenOCAmuuz7bX5-sF:-Mhnew0pC3vrRnmLibbA:b-59x08n) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.

---

**Review by ggould-tri — COMMENTED** [review]
:lgtm: as to the implementation, but one major design discussion below.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhnwszHB2HbNLLhfZV9:bieepta)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnwE302sl239q3-STv:-MhnwE302sl239q3-STw:b-pd1k7n) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L30)):*
> ```Shell
> if  is_kcov_339_vulnerable "$1"; then
>     echo "$ERROR_339"
>     exit 1
> ```

This is really the interesting question:  `exit 1` to force the caller to turn of kcov on this test, or `exit 0` to allow the CI run to proceed without checking the current file?

My inclination is that we should `exit 0` since the modal kcov outcome is success anyway and the test might go back to passing without mention in the future anyway.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnwE302sl239q3-STv:-Mho4iOC9vv2nykKeJhR:bk97c3n) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L30)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is really the interesting question:  `exit 1` to force the caller to turn of kcov on this test, or `exit 0` to allow the CI run to proceed without checking the current file?

My inclination is that we should `exit 0` since the modal kcov outcome is success anyway and the test might go back to passing without mention in the future anyway.
</blockquote></details>

I tried exit 0, but I couldn't figure out any way to smubble a warning into the log files. Maybe pointy wizards have a trick that I have missed.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnwE302sl239q3-STv:-Mho4tV31LPXgwtWEHkZ:b-tw7xjd) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L30)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I tried exit 0, but I couldn't figure out any way to smubble a warning into the log files. Maybe pointy wizards have a trick that I have missed.
</blockquote></details>

s/smubble/smuggle/

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-Mho5VU9-Dl91XQZ5T8f:-Mho5VU9-Dl91XQZ5T8g:b-eoas2i) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L23)):*
> ```Shell
> read -r -d '' ERROR_339 <<- eof
> Error: $1 is vulnerable to kcov issue #339; coverage analysis would
> misinterpret the binary as a shell script and then segfault.
> ```

minor:  This error message should give some guidance for resolving the issue, for example., "Make a trivial change (e.g. by reordering tests) or add `tags = ['no_kcov']` to the test target".
___
*[tools/dynamic_analysis/kcov.sh, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnwE302sl239q3-STv:-Mho5IxMD2Bb2UriZXWx:b-yrkjyn) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L30)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

s/smubble/smuggle/
</blockquote></details>

Hm, I guess some error is better than none.  That being the case I'm adding a request above.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJN3MDIcXojjVue_4:-MhoJN3MDIcXojjVue_5:b7c8xu) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> me=$(python3 -c 'import os; print(os.path.realpath("'"$0"'"))')
> ```

BTW Overall, these changes smell like they'd appear better as pure Python?
___
*[tools/dynamic_analysis/kcov.sh, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJIvp9HVHWJ5OUVHi:-MhoJIvp9HVHWJ5OUVHj:bnz0ar) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L17)):*
> ```Shell
> # leading to segfault. See https://github.com/SimonKagstrom/kcov/issues/339
> is_kcov_339_vulnerable () {
>     file -b $(readlink -f "$1") | grep -q ELF \
> ```

BTW Mixed used of `readlink -f` and `os.path.realpath`. Consider making consistent.

Also, not sure if `readlink -f` is Mac-friendly.
I don't believe we support Mac+kcov, but it'd be confusing to see another error.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJN3MDIcXojjVue_4:-MhoTvIV8xEBzO-8LAyI:brqok5d) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Overall, these changes smell like they'd appear better as pure Python?
</blockquote></details>

_fills his Eric bingo card_. Maybe? Can you cite any specifics? The line above is probably a scar from $BACKWHEN there was an attempt to support mac; that seems to have expired with release 0.19 or so.

**Comment by rpoyner-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnenOCAmuuz7bX5-sF:-Mhtzi24DRupXpe3e1gq:b-59x08n) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
</blockquote></details>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJN3MDIcXojjVue_4:-Mhtzmlb1HWpNLWaMTJC:b-wqjqon) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Free space!

The mixture of Python stuff (`realpath`) and `readlink` smell awkward. Ideally, use one?
Also, the chain of commands for bash function for `is_kcov_339_vulnerable` seem rather special, as well as `read -r -d` craft for capturing heredoc string.
</blockquote></details>

Maybe I've squeaked in under the threshold with r2; readlink is gone , and I've reduced the number of read options to the bare minimum to allow a multiline message. PTAL
___
*[tools/dynamic_analysis/kcov.sh, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJIvp9HVHWJ5OUVHi:-Mhu-5IZAR7hcMzRkeHi:ba0klyt) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Mixed used of `readlink -f` and `os.path.realpath`. Consider making consistent.

Also, not sure if `readlink -f` is Mac-friendly.
I don't believe we support Mac+kcov, but it'd be confusing to see another error.
</blockquote></details>

I did some testing and docs-reading on Mac; the r2 formulation `file -b -L` will do the right thing on both platforms.

As for mac support, I don't know that it is explicitly shut off with an assertion or similar anywhere; I just don't think installing the tool is particularly supported or documented. As a counter-example, on of the in-house machines we have ('macsim') does happen to have kcov installed, and the drake integration appears to work. The kcov tool itself does not appear to work very well.

 So, for this particular script, I think it is fair game assert that it should run on Mac, and at least give *correct* errors, i.e. "kcov not found" or so.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/dynamic_analysis/kcov.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJN3MDIcXojjVue_4:-Mhu4btzA-8Bb8saHJk5:bphdmf7) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L3)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Maybe I've squeaked in under the threshold with r2; readlink is gone , and I've reduced the number of read options to the bare minimum to allow a multiline message. PTAL
</blockquote></details>

OK Looks better! And 
___
*[tools/dynamic_analysis/kcov.sh, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhoJIvp9HVHWJ5OUVHi:-Mhu4YBIDi1LwNvqwfDa:bl00cdx) ([raw file](https://github.com/robotlocomotion/drake/blob/087601e3925a2e9237a2d60a7625b91ea40c06d9/tools/dynamic_analysis/kcov.sh#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I did some testing and docs-reading on Mac; the r2 formulation `file -b -L` will do the right thing on both platforms.

As for mac support, I don't know that it is explicitly shut off with an assertion or similar anywhere; I just don't think installing the tool is particularly supported or documented. As a counter-example, on of the in-house machines we have ('macsim') does happen to have kcov installed, and the drake integration appears to work. The kcov tool itself does not appear to work very well.

 So, for this particular script, I think it is fair game assert that it should run on Mac, and at least give *correct* errors, i.e. "kcov not found" or so.
</blockquote></details>

OK SGTM!

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review, since I'm on call today *and* tomorrow.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhuFR-sBGfASj1gYOKK:b-9t11fk)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15651#-MhnenOCAmuuz7bX5-sF:-MhuFXxR4y8oMW_YD5gW:bbl2maf) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-coverage please.
</blockquote></details>

seems to be going fine, not going to necessarily wait for it to finish.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15651#-:-MhuLDl67yj3lSzLJO-E:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
