### PR TITLE
Parallelize pointcloud operations with OpenMP and use CRU DSHVG for voxel filter

### PR DESCRIPTION
**Pull request by calderpg-tri**
@RussTedrake do you have examples of pointcloud voxel filter and normal estimation that would be good for benchmarking?

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Review by RussTedrake — COMMENTED** [review]
cool!

i don't know that i have anything that will really stress test it.  This notebook drops random ycb objects into a bin and runs the point cloud processing on that:
https://github.com/RussTedrake/manipulation/blob/master/clutter/grasp_selection.ipynb

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216#-:-NFf1FjfEQxMSlz_JmBC:b-llaidl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`perception/point_cloud.cc` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NFf0taZ6u5NFkJEgbd0:-NFf0taZ6u5NFkJEgbd1:b-9bmnci) ([raw file](https://github.com/robotlocomotion/drake/blob/066877fb1c42e41ca77fa5169ed7c88fcd5da65c/perception/point_cloud.cc#L9)):*
> ```cpp
> #include <vector>
> 
> #include <drake_vendor/nanoflann.hpp>
> ```

note: i believe this was the only use of nanoflann in the code so far.  i would think it still has value, especially in higher dof, but it won't be exercised?

**Review by calderpg-tri — COMMENTED** [review]
Thanks for the pointer to the class notebook!

As I somewhat expected, on denser pointcloud data the DSHVG approach of (1) get points in radius then (2) select K nearest is much slower than the nanoflann approach of (1) get K nearest then (2) select in radius for the high-radius (in terms of # of points contained), low-K queries needed for normal estimation. Performance is closer when using a lower radius, but that's not ideal. So I've returned `EstimateNormals` to use nanoflann with optional OpenMP.

> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216#-:-NFgDCZ151Tx8KSuy1J8:b8rts9s)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

___
*[`perception/point_cloud.cc` line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NFf0taZ6u5NFkJEgbd0:-NFgD5xoCPQQQ4baHlRG:bp3aow6) ([raw file](https://github.com/robotlocomotion/drake/blob/066877fb1c42e41ca77fa5169ed7c88fcd5da65c/perception/point_cloud.cc#L9)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

note: i believe this was the only use of nanoflann in the code so far.  i would think it still has value, especially in higher dof, but it won't be exercised?
</blockquote></details>

Reverted.

**Review by calderpg-tri — COMMENTED** [review]
-(status: do not merge) -(status: do not review) 

I think using a DSHVG for the voxel filter is still a useful improvement, especially since I've been planning to allow certain operations on the DSHVG to be performed in parallel and when this is available it would allow the first pass of points->voxels to be parallelized as well.

+@russtedrake for feature review, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216#-:-NFlbgzN8PFpqlPHXM4F:b1ad76)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Review by RussTedrake — COMMENTED** [review]
Sorry for the delay.  :lgtm:    Thank you!
+@ggould-tri for platform review, per rotation.

> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216#-:-NGDJDFu7Yr1yD0hEoT0:bkzrt65)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri and @ggould-tri)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGCYrUhEKnEPHqpaY3m):*
just to be clear, is the plan to squash merge, or are you trying to curate the commits?
___
*[`perception/point_cloud.cc` line 418 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGDH-z50sKMP8OnBTbG:-NGDH-z50sKMP8OnBTbH:bd7xoep) ([raw file](https://github.com/robotlocomotion/drake/blob/344535adba985cf5f49cbc8a9d3666a61d05373f/perception/point_cloud.cc#L418)):*
> ```cpp
> PointCloud PointCloud::VoxelizedDownSample(
>     const double voxel_size, const bool parallelize) const {
>   // This is a simple, narrow, no-frills implementation of the
> ```

btw -- would you still consider it simple, narrow, and no-frills?  i guess you've made it a bit better.  ;-)
___
*[`perception/point_cloud.cc` line 426 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGDGn8T23SlKvMo3ilm:-NGDGn8UAT0DTlq_z7v4:b-bhgqug) ([raw file](https://github.com/robotlocomotion/drake/blob/344535adba985cf5f49cbc8a9d3666a61d05373f/perception/point_cloud.cc#L426)):*
> ```cpp
>   // Create a dynamic-spatial-hashed voxel grid (DSHVG) to bin points. While a
>   // DSHVG usually has each dynamic "chunk" contain multiple voxels, by setting
>   // the chunk size to (voxel_size, 1, 1, 1) each chunk contain a single voxel
> ```

nit: contain => contains

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @RussTedrake)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGCYrUhEKnEPHqpaY3m):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

just to be clear, is the plan to squash merge, or are you trying to curate the commits?
</blockquote></details>

Squash merge
___
*[`perception/point_cloud.cc` line 418 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGDH-z50sKMP8OnBTbG:-NGECDEa3CpimY-UAPCx:b-a2zt9a) ([raw file](https://github.com/robotlocomotion/drake/blob/344535adba985cf5f49cbc8a9d3666a61d05373f/perception/point_cloud.cc#L418)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- would you still consider it simple, narrow, and no-frills?  i guess you've made it a bit better.  ;-)
</blockquote></details>

I've moved the reference to Open3d and PCL to the header documentation.
___
*[`perception/point_cloud.cc` line 426 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGDGn8T23SlKvMo3ilm:-NGECAum42g5WLE_NBzk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/344535adba985cf5f49cbc8a9d3666a61d05373f/perception/point_cloud.cc#L426)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: contain => contains
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[`perception/point_cloud.cc` line 426 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHy0-A-pVFw2sdp1mf:-NGHy0-A-pVFw2sdp1mg:b4d2ers) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L426)):*
> ```cpp
>   // and the whole DSHVG behaves as a sparse voxel grid.
>   const common_robotics_utilities::voxel_grid::GridSizes chunk_sizes(
>       voxel_size, INT64_C(1), INT64_C(1), INT64_C(1));
> ```

nit `INT64_C` is not a GSG-valid macro name ("project-specific prefix") and is anyway probably a violation of "don't use macros" general rule.

https://drake.mit.edu/styleguide/cppguide.html#Preprocessor_Macros
___
*[`perception/point_cloud.cc` line 511 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHyOh77pfDmg6JHgRJ:-NGHyOh77pfDmg6JHgRK:b-cseibd) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L511)):*
> ```cpp
>   // Since we specify chunks contain a single voxel, a chunk's lone voxel can be
>   // retrieved with index (0, 0, 0).
>   const common_robotics_utilities::voxel_grid::GridIndex kSingleVoxel(0, 0, 0);
> ```

nit The verbosity of these humongous namespace qualifiers now littered throughout the file poses an acute readability hurdle.

In many/most of the case throughout, a `using` statement atop the file is called for instead.



_Code quote:_
```cpp
common_robotics_utilities::voxel_grid::
```
___
*[`bindings/pydrake/perception_py.cc` line 130 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHxrAQ2yBcaXoi_f5Z:-NGHxrAQ2yBcaXoi_f5_:bgk0po2) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/bindings/pydrake/perception_py.cc#L130)):*
> ```cpp
>             cls_doc.VoxelizedDownSample.doc)
>         .def("EstimateNormals", &Class::EstimateNormals, py::arg("radius"),
>             py::arg("num_closest"), py::arg("parallelize") = false,
> ```

nit Missing unit tests for new kwarg names.  We can pass `parallelize=False` (i.e., we don't need to pass a non-default) but we _do_ need to prove that that kwarg exists with that name.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`perception/point_cloud.cc` line 426 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHy0-A-pVFw2sdp1mf:-NGITa28BT_hCv32nvvb:b-2mnte5) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L426)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit `INT64_C` is not a GSG-valid macro name ("project-specific prefix") and is anyway probably a violation of "don't use macros" general rule.

https://drake.mit.edu/styleguide/cppguide.html#Preprocessor_Macros
</blockquote></details>

`INT64_C` is the standard way to portably declare a `int64_t` constant. This could instead be written
```
const GridSizes chunk_sizes(voxel_size, static_cast<int64_t>(1), static_cast<int64_t>(1), static_cast<int64_t>(1));
```
but I don't think that would be any better.

**Comment by jwnimmer-tri** [comment]
*[`perception/point_cloud.cc` line 426 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHy0-A-pVFw2sdp1mf:-NGIUegm6FWpBlY-Y0iI:ba8jj3g) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L426)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

`INT64_C` is the standard way to portably declare a `int64_t` constant. This could instead be written
```
const GridSizes chunk_sizes(voxel_size, static_cast<int64_t>(1), static_cast<int64_t>(1), static_cast<int64_t>(1));
```
but I don't think that would be any better.
</blockquote></details>

What's the problem with a simple `1` (int)?  We aren't overloading the constructor based on on integer width, are we?

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`perception/point_cloud.cc` line 426 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHy0-A-pVFw2sdp1mf:-NGIVXjN1ZAprg_03RMs:b-byvele) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L426)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What's the problem with a simple `1` (int)?  We aren't overloading the constructor based on on integer width, are we?
</blockquote></details>

The constructor takes either `(double, int64_t, int64_, int64_t)` or `(double, double, double, double)`. A simple `1` is ambiguous and will not compile.

**Comment by jwnimmer-tri** [comment]
*[`perception/point_cloud.cc` line 426 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHy0-A-pVFw2sdp1mf:-NGIXFVP65Tjq44NN_4-:b15hav6) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L426)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The constructor takes either `(double, int64_t, int64_, int64_t)` or `(double, double, double, double)`. A simple `1` is ambiguous and will not compile.
</blockquote></details>

OK, I guess this is the best we can do.

That constructor's overloading is defectively brittle though.  Numbers passed as positional arguments need to have the same semantics whether or not they are integral or floating-point.  It's too easy to mess it up (as we see here).

Please add a TODO or issue somewhere to fix CRU.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHoIA51jYgsrZ61IpD:-NGJlX-r1AKc-n1RMoOl:bptyy7j) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The PR comment will need to be rewritten before/when you squash this, as the existing PR headline says "Try" (there is no try, only do, in this PR). and the per-commit messages include revert text.
</blockquote></details>

PR title updated, other parts will be updated when squashing

___
___
*[`perception/point_cloud.cc` line 511 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHyOh77pfDmg6JHgRJ:-NGJkmR6DfRbpZxOanwh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/point_cloud.cc#L511)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The verbosity of these humongous namespace qualifiers now littered throughout the file poses an acute readability hurdle.

In many/most of the case throughout, a `using` statement atop the file is called for instead.
</blockquote></details>

Done.
___
*[`perception/test/point_cloud_test.cc` line 68 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHw_qFECckfC88_VaE:-NGJkrr1DVlad90vfgLL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/perception/test/point_cloud_test.cc#L68)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It might be worth noting that this magic number "2" comes from the `BUILD.bazel` file.
</blockquote></details>

Done.
___
*[`bindings/pydrake/perception_py.cc` line 130 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18216#-NGHxrAQ2yBcaXoi_f5Z:-NGJl0He38fFpFCO9fgW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/837133032ed7d9d037f7f4dd3c9bb148fdeaa675/bindings/pydrake/perception_py.cc#L130)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing unit tests for new kwarg names.  We can pass `parallelize=False` (i.e., we don't need to pass a non-default) but we _do_ need to prove that that kwarg exists with that name.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18216)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
