### PR TITLE
workspace: Update gtest to latest release

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Previously attempted in #9966 but experienced a strange CI error.  I'm unable to reproduce it locally, so will try again in CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10130)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
(The new iteration of Jenkins has `-release` and `-debug` configurations.)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all review, please.

**Comment by jwnimmer-tri** [comment]
CI is happy (including the macOS build).  Merging now.

**Pull request merged**
