### PR TITLE
diff ik: Change alpha to live on [0, 1] vs. [0, V_mag]

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Reduces need to call V.normalize() and V.norm()
Does change weighting of optimization problem just a bit

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17809)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Working: Bad solver tolerance? Current failure:
https://drake-cdash.csail.mit.edu/test/817968948
```
Expected: ((*result.joint_velocities)(i)) >= (v_bounds.first(i)), actual: -1.30965 vs -1.309
...
[  FAILED  ] DifferentialInverseKinematicsTest.PositiveTest (69 ms)
```

**Comment by EricCousineau-TRI** [comment]
labeled, thanks!

**Comment by jwnimmer-tri** [comment]
This pull request seems to have stalled out. If we expect it to remain idle for a while longer before resuming, please consider closing it to conserve pull request resources.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17809)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`manipulation/planner/differential_inverse_kinematics.h` line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17809#-NWwe9BPEJ3YaFrGbNoz:-NWwe9BQ4n7KtaPlf5p2:bodnvbz) ([raw file](https://github.com/robotlocomotion/drake/blob/6989c3e31e674423ea4d1d64559e22648d78c080/manipulation/planner/differential_inverse_kinematics.h#L239)):*
> ```objc
>  *                          + | q_current + v_next*dt - q_nominal |^2
>  *
>  *   s.t. J*v_next = alpha * V / |V|  // J*v_next has the same direction as V
> ```

fwiw -- i like this change. 

The |V|^2 scaling in the objective seems a bit arbitrary, but may serve to put the two objectives in the same units.  If we assume a characteristic time constant of \sqrt(g/l), w/ g=10, l=1, then I guess this is saying that the first objective is 10 times more important than the second.

**Comment by jwnimmer-tri** [comment]
What's the plan for proceeding with this PR?

**Comment by RussTedrake** [comment]
I think we can safely close this. We have an updated formulation on the way.

**Pull request closed without merging**
