### PR TITLE
add callbacks to mathematical program (for visualization, etc)

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8477)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-:-L8nPO8m0MLdHdvnN-Uk:b-81zjv5)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[solvers/mathematical_program.h, line 2487 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L8ndMZo8Y8mIRHPdqli:-L8xrmEW31anWIb5nfpw:b-31c9k0) ([raw file](https://github.com/robotlocomotion/drake/blob/18bd4d8dd9d0ce562a183af3928d00e39c31ed39/solvers/mathematical_program.h#L2487)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We have a function `EvalBinding(binding, prog_var_vals)` that can replace the rest of this function.
</blockquote></details>

this one is slightly different (doesn't allocate the zero-sized output unnecessarily).  I could go either way (keep this or dispatch to EvalBinding).

---

*[solvers/mathematical_program.h, line 2492 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L8ndAZX2Gh5TCizMGli:-L8xs9hdARcYNNuCYjw4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18bd4d8dd9d0ce562a183af3928d00e39c31ed39/solvers/mathematical_program.h#L2492)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW,`int` -> `const int`
</blockquote></details>

Done.

---

*[solvers/test/nonlinear_program_test.cc, line 405 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L8ne7axEcAIpj7wDG0E:-L8xs_4gBav3wNo9nrVj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18bd4d8dd9d0ce562a183af3928d00e39c31ed39/solvers/test/nonlinear_program_test.cc#L405)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, we have a function `internal::ParseQuadraticConstraint(x.cast<symbolic::Expression>().dot(x), 0, 1)`, if you think the symbolic expression is cleaner. The reader might not know why there is a factor of 2 in the Hessian of the constraint.
</blockquote></details>

Done.

---

*[solvers/test/nonlinear_program_test.cc, line 438 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L8nedtD2Qb_fuMbnYSf:-L8xs_yd4IJuKpJcC4iv:bv6rrdi) ([raw file](https://github.com/robotlocomotion/drake/blob/18bd4d8dd9d0ce562a183af3928d00e39c31ed39/solvers/test/nonlinear_program_test.cc#L438)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should this be `EXPECT_GT`? Otherwise even if the callback is not called, this check is still satisfied.
</blockquote></details>

:man_facepalming: .  thanks.  done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review please.

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-:-L93N4FK7_sNvnTkVd7Z:b-os5xp3)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[solvers/evaluator_base.h, line 255 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95qzzP75iGAAeTS1le:-L95qzzP75iGAAeTS1lf:bs4txym) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L255)):*
> ```objc
>  * results during an optimization (for solvers that support it).
>  */
> class Callback : public EvaluatorBase {
> ```

FYI Perhaps the name `drake::solvers::Callback` is claiming a bit too much territory?

---

*[solvers/evaluator_base.h, line 260 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95rC8s223HVLsHHI7S:-L95rC8s223HVLsHHI7T:b-oa2usj) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L260)):*
> ```objc
> 
>   typedef std::function<void(const Eigen::Ref<const
>   Eigen::VectorXd>&)> CallbackFnc;
> ```

BTW `Fnc` abbreviation
http://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

---

*[solvers/evaluator_base.h, line 281 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95xRp91NiXWarxOhdL:-L95xRp91NiXWarxOhdM:b-swi0ge) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L281)):*
> ```objc
>     y.resize(0);
>     callback_(math::autoDiffToValueMatrix(x));
>   }
> ```

This function is never called by anything in this PR, so I can't tell if its correct.  It either needs testing added, or change to `throw runtime_error("not implemented");`, or etc.

---

*[solvers/mathematical_program.h, line 770 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sA0y8KUunaDAXXtE:-L95sA0y8KUunaDAXXtF:bii6mvt) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L770)):*
> ```objc
>    *
>    * @param callback a std::function that accepts an Eigen::Vector of doubles
>    * representing the for the bound decision variables.
> ```

BTW typo `the for the`

---

*[solvers/mathematical_program.h, line 2256 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sNxZ-nLkm0CslW3I:-L95sNxZ-nLkm0CslW3J:brck95m) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2256)):*
> ```objc
> 
>   /**
>    * Getter for all generic costs.
> ```

This comment seems stale.

---

*[solvers/mathematical_program.h, line 2260 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sRJZ88D958b_SFgm:-L95sRJZ88D958b_SFgn:b-um9huf) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2260)):*
> ```objc
>   const std::vector<Binding<Callback>>& callbacks() const {
>     return callbacks_;
>   }  // e.g. for snopt_user_fun
> ```

FYI I am not sure the comment is adding much?

---

*[solvers/mathematical_program.h, line 2479 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sr5P1rCf6WRtw-o-:-L95sr5P1rCf6WRtw-o0:b2awghd) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2479)):*
> ```objc
>   }
> 
>   /** Evaluates all callbacks registered with the MathematicalProgram.
> ```

I think this is pushing the bounds of clarity.  Aren't most cost functions etc also easily understood as "callbacks".  Perhaps the PR needs a global rename to "visualization callback" or something?  Or at least, if not a rename then a prose such at this should be clarified (_Meta_).

---

*[solvers/mathematical_program.cc, line 328 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95visq3FIB-2BpKWDm:-L95visq3FIB-2BpKWDn:bow32qc) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.cc#L328)):*
> ```cpp
> }
> 
> Binding<Callback> MathematicalProgram::AddCallback(
> ```

To my reading, if we have a MathemathticalProgram that is Linear or QP, and we add a visualization, it will kick it over to Snopt instead of the direct method? 

(1) Is that what we want, and
(2) Should the MP.h header warn users about this?

---

*[solvers/nlopt_solver.cc, line 60 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95vASLALKk-LFdaHfr:-L95vASLALKk-LFdaHfs:b6nxnn9) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/nlopt_solver.cc#L60)):*
> ```cpp
>   Eigen::VectorXd xvec = MakeEigenVector(x);
> 
>   prog->EvalCallbacks(xvec);
> ```

FYI _Meta_ Without having the detailed background of how all of the solvers work, I am unable to tease out why EvalCallbacks sometimes happen during cost-evaluation and sometimes during constraint-evaluation.  Is it worth adding a sentence or two explaining the thought process, for each of the three solvers where they call it?

---

*[solvers/test/nonlinear_program_test.cc, line 410 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95uGORDLa_wnDM3yBI:-L95uGORDLa_wnDM3yBJ:b-dizyf7) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/test/nonlinear_program_test.cc#L410)):*
> ```cpp
>   auto my_callback = [&num_calls](const Eigen::Ref<const Eigen::VectorXd>& v) {
>     EXPECT_EQ(v.size(), 3);
>     num_calls++;
> ```

Given that we have the whole `this_x(j) = prog_var_vals(FindDecisionVariableIndex(binding.variables()(j)));` stuff going on, it seems like we should be testing that `x` contains what we want it to contain, and I _think_ here is the correct place to do it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[solvers/test/mathematical_program_test.cc, line 2849 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L97sFaP8kdN3C8MhxDd:-L97sFaP8kdN3C8MhxDe:be7aa2m) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/test/mathematical_program_test.cc#L2849)):*
> ```cpp
>   auto x = prog.NewContinuousVariables<2>();
>   bool was_called = false;
>   auto my_callback = [&was_called](const Eigen::Ref<const Eigen::VectorXd>& x) {
> ```

BTW GCC wants you to rename either this `x`, or the prior `x`, to not shadow each other.   I agree in any case, for readability reasons.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by RussTedrake** [comment]
Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[solvers/evaluator_base.h, line 255 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95qzzP75iGAAeTS1le:-L9AOXvnBUWEKZ2KwD_k:bvqjf1m) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L255)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Perhaps the name `drake::solvers::Callback` is claiming a bit too much territory?
</blockquote></details>

i thought about that at first, but was ok since it was behind the namespace.  but i've updated it now.

---

*[solvers/evaluator_base.h, line 260 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95rC8s223HVLsHHI7S:-L9APMJ-8Gd_xfaV6DGS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L260)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `Fnc` abbreviation
http://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.

---

*[solvers/evaluator_base.h, line 281 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95xRp91NiXWarxOhdL:-L9ARAmnB9-4iOigHjAC:bqaa9t) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/evaluator_base.h#L281)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This function is never called by anything in this PR, so I can't tell if its correct.  It either needs testing added, or change to `throw runtime_error("not implemented");`, or etc.
</blockquote></details>

added coverage.

---

*[solvers/mathematical_program.h, line 770 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sA0y8KUunaDAXXtE:-L9ARRAI-qY3QdgNuRnn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L770)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW typo `the for the`
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2256 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sNxZ-nLkm0CslW3I:-L9ARWts-Bbev2Brbzx-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2256)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment seems stale.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2260 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sRJZ88D958b_SFgm:-L9ARZb83qVlAdMcmEa2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2260)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I am not sure the comment is adding much?
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2479 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95sr5P1rCf6WRtw-o-:-L9ATMp33ECxewJZXo1n:beexffm) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.h#L2479)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this is pushing the bounds of clarity.  Aren't most cost functions etc also easily understood as "callbacks".  Perhaps the PR needs a global rename to "visualization callback" or something?  Or at least, if not a rename then a prose such at this should be clarified (_Meta_).
</blockquote></details>

indeed, it was called VisualizationCallback in matlab.  I've made the change (everywhere).

---

*[solvers/mathematical_program.cc, line 328 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95visq3FIB-2BpKWDm:-L9AU1NLCjublLS4cVm_:b-sz433q) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.cc#L328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To my reading, if we have a MathemathticalProgram that is Linear or QP, and we add a visualization, it will kick it over to Snopt instead of the direct method? 

(1) Is that what we want, and
(2) Should the MP.h header warn users about this?
</blockquote></details>

that is correct.  my initial implementation instead documented that "your callback may not be called, if the invoked solver does not support it".  but in writing that doc, I decided that this broke the contract sufficiently that it would be cleaner to implement it this way.

another alternative would be to have it not change the solver type, but produce a log console warning if the solver that gets called does not support callbacks?  Or take an optional boolean about whether you want to mandate that the callback gets used.

i'll clean up the doc/implementation for whichever we think is best.

---

*[solvers/nlopt_solver.cc, line 60 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95vASLALKk-LFdaHfr:-L9AV5a_1Ts-XNmLblN3:b-64kjnp) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/nlopt_solver.cc#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ Without having the detailed background of how all of the solvers work, I am unable to tease out why EvalCallbacks sometimes happen during cost-evaluation and sometimes during constraint-evaluation.  Is it worth adding a sentence or two explaining the thought process, for each of the three solvers where they call it?
</blockquote></details>

moved it to be next to costs in all examples for consistency.  I don't *think* it should matter?  @hongkai-dai ?

---

*[solvers/test/mathematical_program_test.cc, line 2849 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L97sFaP8kdN3C8MhxDd:-L9AVFHU-eqP_l6q1pit:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/test/mathematical_program_test.cc#L2849)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW GCC wants you to rename either this `x`, or the prior `x`, to not shadow each other.   I agree in any case, for readability reasons.
</blockquote></details>

Done.

---

*[solvers/test/nonlinear_program_test.cc, line 410 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95uGORDLa_wnDM3yBI:-L9AVZ1W5OUM56MBvlUx:bciswj9) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/test/nonlinear_program_test.cc#L410)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given that we have the whole `this_x(j) = prog_var_vals(FindDecisionVariableIndex(binding.variables()(j)));` stuff going on, it seems like we should be testing that `x` contains what we want it to contain, and I _think_ here is the correct place to do it?
</blockquote></details>

Did it in the mathematical_program_test version, which just tests the callback by calling it directly (here it gets called many times by the solvers, with intermediate results as well as the numerical solution).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.cc, line 328 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95visq3FIB-2BpKWDm:-L9Aba6u82OecRNJNS0t:b-s4z9ir) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.cc#L328)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that is correct.  my initial implementation instead documented that "your callback may not be called, if the invoked solver does not support it".  but in writing that doc, I decided that this broke the contract sufficiently that it would be cleaner to implement it this way.

another alternative would be to have it not change the solver type, but produce a log console warning if the solver that gets called does not support callbacks?  Or take an optional boolean about whether you want to mandate that the callback gets used.

i'll clean up the doc/implementation for whichever we think is best.
</blockquote></details>

My best guess is that the current behavior is correct as a default, but that we should add a little more cautionary text to MP.h about the consequences of adding vis callbacks.

Later, we could add a "but don't change the solver backend" hint to the Add methods, if we find we need it.

I'll defer to you and @hongkai-dai on the final choice, though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-:-L9AcDqBBZJl8DLmvLyR:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 328 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95visq3FIB-2BpKWDm:-L9B7-Q_Bm2ph5D98NC1:b-c4nwvs) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.cc#L328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My best guess is that the current behavior is correct as a default, but that we should add a little more cautionary text to MP.h about the consequences of adding vis callbacks.

Later, we could add a "but don't change the solver backend" hint to the Add methods, if we find we need it.

I'll defer to you and @hongkai-dai on the final choice, though.
</blockquote></details>

I do not object the current implementation. When I use optimization, and if I want to visualize something, it is always in the nonlinear optimization, or mixed-integer optimization. I do not think I will visualize the intermediate result, when I solve an LP.

There is a tangential issue, that now we only check if the solver satisfies the requirement of `MathematicalProgram`, inside `MathematicalProgram::Solve`. This leaves a loop hole in our program, that we can call `solver::Solve()` function, and do not check the satisfiability of the solver. Should we move the check to each solver? I am thinking of a static function like `solver::IsProgramSatisfied`, that will be called inside `MathematicalProgram::Solve`, and also in the debug mode of `solver::Solve`.

---

*[solvers/nlopt_solver.cc, line 60 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95vASLALKk-LFdaHfr:-L9B7LMW3M_qEXBZXhBK:b-90o33y) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/nlopt_solver.cc#L60)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

moved it to be next to costs in all examples for consistency.  I don't *think* it should matter?  @hongkai-dai ?
</blockquote></details>

I do not think it should matter either.

For future maintenance, could you add call back to an optimization program, that has 0 cost, and check if the callback is actually invoked? So that in the future, we do not accidentally change our code to bypass the cost evaluation, if the cost is 0.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.cc, line 328 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477#-L95visq3FIB-2BpKWDm:-L9BEPN93vLNhzFfNePM:b-rj3165) ([raw file](https://github.com/robotlocomotion/drake/blob/670525a2278b017c2df698a8777a88b7e3f8d104/solvers/mathematical_program.cc#L328)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I do not object the current implementation. When I use optimization, and if I want to visualize something, it is always in the nonlinear optimization, or mixed-integer optimization. I do not think I will visualize the intermediate result, when I solve an LP.

There is a tangential issue, that now we only check if the solver satisfies the requirement of `MathematicalProgram`, inside `MathematicalProgram::Solve`. This leaves a loop hole in our program, that we can call `solver::Solve()` function, and do not check the satisfiability of the solver. Should we move the check to each solver? I am thinking of a static function like `solver::IsProgramSatisfied`, that will be called inside `MathematicalProgram::Solve`, and also in the debug mode of `solver::Solve`.
</blockquote></details>

I suggest opening an issue about that -- or I thought there might already be one.  In general, making the capabilities matrix more explicit and checked on both sides is one part of making the solver backends more decoupled from the MP declarations (a long-running, stalled project).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 9 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8477)*

**Pull request merged**
