### PR TITLE
Find test resources in runfiles

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The ability to write a regression test for this will be vastly improved after #7774 merges; thus, my proposal for this PR is to test by hand and if this merges first then open an issue to add a regression test after #7774 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8255)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for feature and platform review, please.  I'll grab Eric tomorrow to also do a feature + platform review on it.  With this patch, the final comment from the Anzu PR you just saw can be reverted.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI also for feature and platform review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8255#-:-L6w2T6xUmWOgX_7oVWp:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, did a quick local test using `bazel test //examples/kuka_iiwa_arm/...`

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/find_resource.cc, line 171 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8255#-L6wEJLVAmjsbASOmbdJ:-L6wEJLVAmjsbASOmbdK:b9epcyp) ([raw file](https://github.com/robotlocomotion/drake/blob/d7dbd95df8da43dd6f6ea25183166ce2c0ab5cb7/common/find_resource.cc#L171)):*
> ```cpp
>   // These environment variables are documented at:
>   // https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions
>   if (::getenv("TEST_TMPDIR") == nullptr) {
> ```

BTW Is there a reason to also check `TEST_TMPDIR` if `TEST_SRCDIR` is what's ultimately needed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8255#-:-L6wIKxDDqtP3sxWRYLf:bzf45dg)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8255)*

**Pull request merged**
