### PR TITLE
Mosek parse PSD constraint on 2x2 matrices as RotatedLorentzCone.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231)* status: 5 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/non_convex_optimization_util_test.cc` line 74 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf1EMvAV7YIY7EyCT0:-OCf1EMvAV7YIY7EyCT1:b58qlee) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/test/non_convex_optimization_util_test.cc#L74)):*
> ```cpp
>       CompareMatrices(Q1, Q1_expected, 3E-5, MatrixCompareType::absolute));
>   EXPECT_TRUE(
>       CompareMatrices(Q2, Q2_expected, 3E-5, MatrixCompareType::absolute));
> ```

This change seems unrelated.



_Code quote:_
```cpp
  EXPECT_TRUE(
      CompareMatrices(Q1, Q1_expected, 3E-5, MatrixCompareType::absolute));
  EXPECT_TRUE(
      CompareMatrices(Q2, Q2_expected, 3E-5, MatrixCompareType::absolute));
```
___
*[`solvers/mosek_solver_internal.h` line 620 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf-YpM4KGdK_mmqWeD:-OCf-YpM4KGdK_mmqWeE:beq848p) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/mosek_solver_internal.h#L620)):*
> ```objc
>         continue;
>       }
>     }
> ```

~~Won't this cause you to skip all the other psd constraints?~~

Could you add a comment that `PositiveSemidefiniteConstraint` is only treated as an affine expression in a cone if it is a 2x2 matrix. The other dual solutions are treated in `SetVariableBoundsDualSolution`



_Code quote:_
```objc
    if constexpr (std::is_same_v<C, PositiveSemidefiniteConstraint>) {
      if (binding.evaluator()->matrix_rows() != 2) {
        continue;
      }
    }
```
___
*[`solvers/test/mosek_solver_test.cc` line 539 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf16Ku5y4ltqFm08LC:-OCf16Ku5y4ltqFm08LD:b7p8an5) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/test/mosek_solver_test.cc#L539)):*
> ```cpp
>   MosekSolver solver;
>   if (solver.available()) {
>     TestTrivial2x2SDP(solver, 1E-5, /*check_dual=*/true, /*dual_tol=*/1E-8);
> ```

This change makes the psd constraint less accurate? That seems very odd to me.
___
*[`solvers/test/mosek_solver_internal_test.cc` line 191 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf0hlg1rPq6nx7mJKd:-OCf0hlg1rPq6nx7mJKe:b9zgd0e) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/test/mosek_solver_internal_test.cc#L191)):*
> ```cpp
>   EXPECT_FALSE(F_subi.empty());
>   EXPECT_FALSE(F_subj.empty());
>   EXPECT_FALSE(F_valij.empty());
> ```

I think that this no longer tests what we want it to test anymore. I would completely remove the 2x2 matrix from this test so that these can stay EXPECT_TRUE



_Code quote:_
```cpp
  EXPECT_FALSE(F_subi.empty());
  EXPECT_FALSE(F_subj.empty());
  EXPECT_FALSE(F_valij.empty());
```
___
*[`solvers/test/mosek_solver_internal_test.cc` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf0tj9-NWEDiohycb7:-OCf0tj9-NWEDiohycb8:b-5w8fsf) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/test/mosek_solver_internal_test.cc#L205)):*
> ```cpp
>   auto y = prog.NewContinuousVariables<4>();
>   auto X1 = prog.NewSymmetricContinuousVariables<2>();
>   auto X2 = prog.NewSymmetricContinuousVariables<3>();
> ```

I think here we likely want to add an `X3` that is constrained to be in the PSD cone of size 3 or 4. Otherwise this test no longer tests the same thing.



_Code quote:_
```cpp
auto X2 = prog.NewSymmetricContinuousVariables<3>();
```

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231)* status: 1 unresolved discussion, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-:-OCySB-912YjOHOE_4T1:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for Tuesday's platform review please, thanks! 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-:-OD8LNpW2n4QBOqzYeIy:b1fj3hk)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/test/non_convex_optimization_util_test.cc` line 74 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-OCf1EMvAV7YIY7EyCT0:-OD8TtM82yrQTyJ9nQY_:b-c73m1w) ([raw file](https://github.com/RobotLocomotion/drake/blob/7285d2018febad53638e09a593445f13f2d89c3b/solvers/test/non_convex_optimization_util_test.cc#L74)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It actually does. I decompose an indefinite matrix into the difference of two PSD matrices. Here the matrix is of size 2 x 2, so the PSD constraints are substituted by the rotated Lorentz cone constraint in this PR.
</blockquote></details>

I see. I missed that we were solving an optimization problem in `DecomposeNonConvexQuadraticForm`.

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 
:lgtm: 

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22231#-:-ODDGeRy9QAke0G5Bfat:bdobo2z)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

**Pull request merged**
