### PR TITLE
Add GraphOfConvexSets::LockEdge()

### PR DESCRIPTION
**Pull request by avalenzu**
This allows the user to specify that particular edges of the graph ought to be active/inactive.

This PR also makes the order of constraints deterministic in `GraphOfConvexSets::Solve()`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@tobiamarcucci for feature review.

cc. @russtedrake

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-MgMVwYp3fgVX48Ue8CE:bxom3um)* status: LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @TobiaMarcucci)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 2 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMX9dqBXdlZnE3tnAq:-MgMX9dqBXdlZnE3tnAr:b-4muyv3) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L277)):*
> ```objc
>  private:
>   std::map<VertexId, std::unique_ptr<Vertex>> vertices_{};
>   std::vector<std::unique_ptr<Edge>> edges_{};
> ```

when you raised this in slack, I imagined making this set (not vector), by creating EdgeId and the operator<.  That seems like a more natural representation for a graph, no?  and more performant if/when we start removing edges?
___
*[geometry/optimization/graph_of_convex_sets.h, line 278 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMWrWk3FS72-K7spHD:-MgMWrWl2_9j3uIUFeBv:bboa6ex) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L278)):*
> ```objc
>   std::map<VertexId, std::unique_ptr<Vertex>> vertices_{};
>   std::vector<std::unique_ptr<Edge>> edges_{};
>   std::map<const Edge*, bool> locked_edges_{};
> ```

btw, I think we probably want to (eventually) support more general constraints on phi.  I guess this hidden behind the API, so is ok for now.
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 693 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMYN81ERGdFNIlUKNK:-MgMYN82CdTk_T-uu34k:babk4rl) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/test/graph_of_convex_sets_test.cc#L693)):*
> ```cpp
>   // higher cost.
>   spp.LockEdge(*source_to_p2, true);
>   auto new_result = spp.SolveShortestPath(source->id(), target->id(), false);
> ```

I agree with you... i don't see any reason why/how the MIP should report success with the binaries being satisfied only to 1e-3.

**Comment by avalenzu** [comment]
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 693 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMYN81ERGdFNIlUKNK:-MgMZ-IL71F3zkiVKS27:b-i1xu8z) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/test/graph_of_convex_sets_test.cc#L693)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I agree with you... i don't see any reason why/how the MIP should report success with the binaries being satisfied only to 1e-3.
</blockquote></details>

Sorry, what you're seeing here is the modified version of the test that checks the binary variable values. This one passes. If I check the costs (ell) instead, that's when I see values > 1e-3.

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 693 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMYN81ERGdFNIlUKNK:-MgMZMuR-oyVenojn48_:b-lq4y70) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/test/graph_of_convex_sets_test.cc#L693)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Sorry, what you're seeing here is the modified version of the test that checks the binary variable values. This one passes. If I check the costs (ell) instead, that's when I see values > 1e-3.
</blockquote></details>

I realized it must be that way, that just after publishing. ;-)

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 3 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-MgN7A_81tJQfzRL-cA3:b-x12j1b) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
> ```objc
> 
>   /** Requires that @p edge be active (phi == 1) or inactive (phi == 0). */
>   void LockEdge(const Edge& edge, bool active);
> ```

Do we like `LockEdge` or `LockFlow` better? Maybe the second describes more precisely what this method does?
___
*[geometry/optimization/graph_of_convex_sets.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN4ZUP10GjnFCRymd8:-MgN4ZUP10GjnFCRymd9:b-h69vpy) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.cc#L195)):*
> ```cpp
>     if (locked_edge != locked_edges_.end()) {
>       double phi_value = locked_edge->second ? 1.0 : 0.0;
>       prog.AddBoundingBoxConstraint(phi_value, phi_value, phi);
> ```

One minor question. Here you add a new constraint, but if `convex_relaxation` is 1 a bounding box constraint on the `phi` variables has been added a few lines above. I guess modifying the coefficient of the previous constraint would be more efficient in case of `convex_relaxation `, but the `if` part would make the code a little ugly. I just don't know what's preferable.

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 3 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-Mgf2-Sr8coYaZlLyIpp:bxbma8l) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

Do we like `LockEdge` or `LockFlow` better? Maybe the second describes more precisely what this method does?
</blockquote></details>

If we went with `LockFlow` would you still want a `bool active` argument, or should it be `double flow`?
___
*[geometry/optimization/graph_of_convex_sets.h, line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMX9dqBXdlZnE3tnAq:-Mgf1sSf6cYAA9zmgdnp:b-dflkk6) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L277)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

when you raised this in slack, I imagined making this set (not vector), by creating EdgeId and the operator<.  That seems like a more natural representation for a graph, no?  and more performant if/when we start removing edges?
</blockquote></details>

Yes, that's a good idea.
___
*[geometry/optimization/graph_of_convex_sets.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN4ZUP10GjnFCRymd8:-Mgf2_XX9oXi118pomnq:b5vhoq5) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.cc#L195)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

One minor question. Here you add a new constraint, but if `convex_relaxation` is 1 a bounding box constraint on the `phi` variables has been added a few lines above. I guess modifying the coefficient of the previous constraint would be more efficient in case of `convex_relaxation `, but the `if` part would make the code a little ugly. I just don't know what's preferable.
</blockquote></details>

I'm inclined to go with readability here, since we only have to loop through the bounding box constraints once at the start of a `Solve` call.

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-Mgf8HUv4lPgiigGcZex:bnfp4nl)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-Mgf7hCf4TK-DuCCGNLg:b-410m92) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

If we went with `LockFlow` would you still want a `bool active` argument, or should it be `double flow`?
</blockquote></details>

Mmm I see, it'd suggest we could lock the flow to a fractional value, which I think it's something that should not be supported. I'm happy with `LockEdge` then.
___
*[geometry/optimization/graph_of_convex_sets.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN4ZUP10GjnFCRymd8:-Mgf8ArN2iZIFyT5khXo:b-pbdqz3) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.cc#L195)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I'm inclined to go with readability here, since we only have to loop through the bounding box constraints once at the start of a `Solve` call.
</blockquote></details>

Agreed.

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-MglpwGu0CAVEoQO2w4z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

Mmm I see, it'd suggest we could lock the flow to a fractional value, which I think it's something that should not be supported. I'm happy with `LockEdge` then.
</blockquote></details>

Done.
___
*[geometry/optimization/graph_of_convex_sets.h, line 277 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgMX9dqBXdlZnE3tnAq:-MggS7-wCJ5ZfcUjWm8P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L277)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Yes, that's a good idea.
</blockquote></details>

Done.
___
*[geometry/optimization/graph_of_convex_sets.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN4ZUP10GjnFCRymd8:-MgfGvhM2KooPrBeB1q2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.cc#L195)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.

**Review by avalenzu — COMMENTED** [review]
+@soonho-tri for platform review as part of the geometry/optimization train.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-MglrD_r-V1lYZ0XzsqM:b-7j1p37)* status: 3 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @soonho-tri, and @TobiaMarcucci)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 9 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu, @RussTedrake, and @TobiaMarcucci)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmbRKO8RWaUnPr0GjW:-MgmbRKO8RWaUnPr0GjX:b-ygezxz) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/-- commits#L1)):*
Can you update this commit message before merging it?
___
*[geometry/optimization/graph_of_convex_sets.h, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmgjwb4UKWx6TXnCj7:-Mgmgjwb4UKWx6TXnCj8:b-mlmqoj) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L237)):*
> ```objc
>   Edge* AddEdge(const Vertex& u, const Vertex& v, std::string name = "");
> 
>   /** Requires that @p edge be active (phi == 1) or inactive (phi == 0). */
> ```

nit, internally `LockEdge(e, b)` overwrites an existing active/inactive flag for the edge `e`. Do you want to mention it in the doc?
___
*[geometry/optimization/graph_of_convex_sets.h, line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmgBPe9_4nnzEVqc7_:-MgmgBPf8J-4P6YMbfNc:b-94pc09) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L282)):*
> ```objc
>       bool convex_relaxation = false) const;
> 
>   /** Custom comparator for sorting edges based on their identifiers. */
> ```

nit, we can mark this custom comparator `private` as long as you do not expose the `std::set<std::unique_ptr<Edge>, decltype(&GraphOfConvexSets::CompareEdges)>` (, which is the case for now).
___
*[geometry/optimization/graph_of_convex_sets.h, line 288 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmfufw8merzf3eh6tK:-Mgmfufw8merzf3eh6tL:b-apeyd5) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L288)):*
> ```objc
>  private:
>   std::map<VertexId, std::unique_ptr<Vertex>> vertices_{};
>   std::set<std::unique_ptr<Edge>, decltype(&GraphOfConvexSets::CompareEdges)>
> ```

Now we are adding `edges_` member field, I think we can revise the existing `GraphOfConvexSets::Edges()` (which creates a set every time for now).
___
*[geometry/optimization/graph_of_convex_sets.cc, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmf3OX5N3JoqKSJR-2:-Mgmf3OYCMsl6PPuCUpG:bwodobv) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.cc#L61)):*
> ```cpp
> }
> 
> Edge::Edge(const EdgeId& id, const Vertex* u, const Vertex* v, std::string name)
> ```

I think it's better to encapsulate `EdgeId` part from this constructor. What do you think about the following?

```c++
Edge::Edge(const Vertex* u, const Vertex* v, std::string name)
    : id_{EdgeId::get_new_id()},
      u_{u},
```
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmhLkR2coA9jNVink2:-MgmhLkR2coA9jNVink3:b-rpt02j) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/test/graph_of_convex_sets_test.cc#L692)):*
> ```cpp
>   // Test that forcing an edge not on the shortest path to be active yields a
>   // higher cost.
>   spp.LockEdge(*source_to_p2, true);
> ```

Can we add a test case using `LockEdge(e, false)`?

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 10 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu, @RussTedrake, and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 194 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmi6hk5TBbwxdP4jYn:-Mgmi6hk5TBbwxdP4jYo:b-9uupbd) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L194)):*
> ```objc
> 
>    private:
>     // Constructs a new edge.
> ```

nit, if you choose to remove `EdgeId` from this constructor, please mention that a new ID is generated and assigned internally.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 10 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu, @soonho-tri, and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-MgmjQr8-tmyuwhxQFtn:b-rhv0mq) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think of this as sugar for `edge.AddConstraint(e.phi == active)`, even though our current AddConstraint doesn't handle the more general case yet (except with the subtlety that soonho mentioned that it overwrites any previous constraint).  

What do you think about `edge.AddPhiConstraint(bool)` instead of `LockEdge` which doesn't fit the existing patterns?  
___
*[geometry/optimization/graph_of_convex_sets.h, line 288 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmfufw8merzf3eh6tK:-MgmlfFa6FHRJzIZayFf:bxgnpgc) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L288)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Now we are adding `edges_` member field, I think we can revise the existing `GraphOfConvexSets::Edges()` (which creates a set every time for now).
</blockquote></details>

but we don't want to hand back the unique_ptr to the edges in `Edges()`.  I think we still need to make a copy of the set with the raw pointers?
___
*[geometry/optimization/graph_of_convex_sets.h, line 289 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmmG2Y9LfWLcZd8N7m:-MgmmG2Y9LfWLcZd8N7n:b-gifm0c) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L289)):*
> ```objc
>   std::map<VertexId, std::unique_ptr<Vertex>> vertices_{};
>   std::set<std::unique_ptr<Edge>, decltype(&GraphOfConvexSets::CompareEdges)>
>       edges_{&GraphOfConvexSets::CompareEdges};
> ```

@avalenzu -- sorry for this.  but seeing it like this, shouldn't we just do `std::map<EdgeId, std::unique_ptr<Edge>>` ?  That would have the perfect parity with the vertices (and i don't see why it shouldn't), and would get rid of CompareEdges, since it happens automatically.
___
*[geometry/optimization/graph_of_convex_sets.cc, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmf3OX5N3JoqKSJR-2:-MgmmavN79cQe1az2ILr:bsvjrzu) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.cc#L61)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it's better to encapsulate `EdgeId` part from this constructor. What do you think about the following?

```c++
Edge::Edge(const Vertex* u, const Vertex* v, std::string name)
    : id_{EdgeId::get_new_id()},
      u_{u},
```
</blockquote></details>

i thought this too.  the reason I didn't do it for the vertices is because i was using them in std::map.  i recommended above that we do it again here.

**Comment by avalenzu** [comment]
___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-MgpSdaR3Hpl-6uTV0T-:bjtyokg) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Let me give that a shot.
</blockquote></details>

Are you OK with `Edge::AddPhiConstraint(bool)` being `void` rather than returning a binding? It wouldn't match the `Edge::AddConstraint()` pattern in that case, but I'm pretty sure we don't want users to be able to modify the constraint on phi?

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 8 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @TobiaMarcucci)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmbRKO8RWaUnPr0GjW:-MgpTf341oppxJtvr8X3:bquxqq5) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/-- commits#L1)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

That can still be done as part of the squash-merge process, right?
</blockquote></details>

OK. Yup.
___
*[geometry/optimization/graph_of_convex_sets.h, line 288 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmfufw8merzf3eh6tK:-MgpTks05nF_ebbYIBjC:b2nhktp) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L288)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Yup. Especially given the churn we've gone through on the `edges_` implementation, I think copying the raw pointers is better.
</blockquote></details>

OK.

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: 5 unresolved discussions, LGTM missing from assignee soonho-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake, @soonho-tri, and @TobiaMarcucci)

___
*[geometry/optimization/graph_of_convex_sets.h, line 237 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmgjwb4UKWx6TXnCj7:-Mgq08x3AaEw7qYlXhFk:bszw9d2) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L237)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, internally `LockEdge(e, b)` overwrites an existing active/inactive flag for the edge `e`. Do you want to mention it in the doc?
</blockquote></details>

Moot due to removal of `LockEdge`.
___
*[geometry/optimization/graph_of_convex_sets.h, line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmgBPe9_4nnzEVqc7_:-Mgq0ExaBSy8e3ebdHkk:b-dfqkex) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L282)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, we can mark this custom comparator `private` as long as you do not expose the `std::set<std::unique_ptr<Edge>, decltype(&GraphOfConvexSets::CompareEdges)>` (, which is the case for now).
</blockquote></details>

Moot due to removal.
___
*[geometry/optimization/graph_of_convex_sets.h, line 289 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmmG2Y9LfWLcZd8N7m:-MgpRioY5BTO1FsPf1iP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L289)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Yes, that's certainly do-able (in fact I started there since I had the most confidence that it would work).
</blockquote></details>

Done.
___
*[geometry/optimization/graph_of_convex_sets.cc, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-Mgmf3OX5N3JoqKSJR-2:-Mgper6JEL_SVpPPMSd5:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.cc#L61)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

As discussed above, I'm going to change things so that `Edge` and `Vertex` follow the same patterns.
</blockquote></details>

Done
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 692 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmhLkR2coA9jNVink2:-Mgq0-K-Dec6qIIO5ACe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/test/graph_of_convex_sets_test.cc#L692)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-Mgq7WIX3b4dw1QpCP2M:bnfp4nl)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake and @TobiaMarcucci)

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-Mgqf8D5ATPRRRunmPXO:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/graph_of_convex_sets.h, line 231 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgN7A_81tJQfzRL-cA2:-Mgql1z05W9lbkCiYNJq:b-723k11) ([raw file](https://github.com/robotlocomotion/drake/blob/2f292d7ecabc63dda1bbd2ff6a0c9b06eba75ca9/geometry/optimization/graph_of_convex_sets.h#L231)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Are you OK with `Edge::AddPhiConstraint(bool)` being `void` rather than returning a binding? It wouldn't match the `Edge::AddConstraint()` pattern in that case, but I'm pretty sure we don't want users to be able to modify the constraint on phi?
</blockquote></details>

Yes, I'm ok with it.  But I also don't *think* users can modify the binding in the normal workflow?  Isn't the binding returned by copy?

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-Mgqlewx4tz9y6PpMvGf:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

___
*[geometry/optimization/graph_of_convex_sets.h, line 289 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15572#-MgmmG2Y9LfWLcZd8N7m:-MgqfzASBOm7GvRU9MgE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e25b56378539d95c8b388ae1fc32143af793e81/geometry/optimization/graph_of_convex_sets.h#L289)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by avalenzu — COMMENTED** [review]
I will squash merge this later tonight if CI passes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-Mgr-nCwBFy_RVypyodt:bf5fjme)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu)

**Review by avalenzu — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15572#-:-MgsCKp-ACi9cnILyCab:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees TobiaMarcucci,soonho-tri(platform) (waiting on @avalenzu)

**Pull request merged**
