### PR TITLE
[multibody] Clean up some helper file structure

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards simplifying https://github.com/RobotLocomotion/drake/pull/21623 by reducing things we need to efficiently copy and memorize, and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21692)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2 -- with one more note on the whole class/struct snafu.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21692#-:-O1IuhTH3Ea7sKqVcjQ-:bxwhkle)* status: 1 unresolved discussion

___
*[`multibody/plant/geometry_contact_data.h` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21692#-O1IsR-iE6jh5z_a0RP_:-O1IsR-iE6jh5z_a0RPa:bfo92u1) ([raw file](https://github.com/RobotLocomotion/drake/blob/8b4f5c754996954f8460f3562cd6b32cb9d8fdc9/multibody/plant/geometry_contact_data.h#L53)):*
> ```objc
> 
> DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
>     class ::drake::multibody::internal::GeometryContactData);
> ```

nit: Why doesn't the declaration also need to be `struct`? At the very least, it would be consistent with the definition and probably serve as a good pattern.



_Code quote:_
```objc
class
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21692)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

___
*[`multibody/plant/geometry_contact_data.h` line 53 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21692#-O1IsR-iE6jh5z_a0RP_:-O1IvX7o7NSBDRYkfU43:b-s8hk9c) ([raw file](https://github.com/RobotLocomotion/drake/blob/8b4f5c754996954f8460f3562cd6b32cb9d8fdc9/multibody/plant/geometry_contact_data.h#L53)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Why doesn't the declaration also need to be `struct`? At the very least, it would be consistent with the definition and probably serve as a good pattern.
</blockquote></details>

Good catch.  I guess clang doesn't care (it cares about everything else), but as you say -- it's best to be consistent.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21692)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
