### PR TITLE
Update to latest SDFormat and use upstream system_util.hh 

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Now supports SDFORMAT_STATIC_DEFINE

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8458)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Will need to update **tools/workspace/sdformat/repository.bzl** once [sdformat PR](https://bitbucket.org/osrf/sdformat/pull-requests/421/add-support-for-sdformat_static_define/diff) has been merged

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage-everything please

**Comment by BetsyMcPhail** [comment]
Clean coverage builds!

+@jamiesnape for feature review please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8458#-:-L9Aj6iC1aQOzMX8Qkmf:b-jbygtt)*

**Comment by jamiesnape** [comment]
:lgtm:

+@sammy-tri for platform review.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8458#-:-L9AjCrX2jqWpELVdOgX:b-ewgrsz)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8458#-:-L9BCo1mEtT8u_3d1yqM:bnfp4nl)*

**Pull request merged**
