### PR TITLE
Adds Documentation Comments to the Generated LCM Messages.

### LINKED ISSUE #4472: lcmt_driving_command_t Should Document the Semantics of Throttle / Brake
# Problem Definition

`drake/lcmtypes/lcmt_driving_command_t.lcm` includes `throttle` and `brake` reference values, as shown below:

```
struct lcmt_driving_command_t {
  // The timestamp in milliseconds.
  int64_t timestamp;

  double steering_angle;
  double throttle;
  double brake;
}
```

The semantics of these two variables is subtle and there is currently no documentation included in the message definition.

# Proposed Solution

Let's add the following documentation to `throttle` and `brake`:

```
  // The normalized desired acceleration of the vehicle. It has a value between [0, 1].
  double throttle;

  // The normalized desired deceleration of the vehicle. It has a value between [0, 1].
  double brake;
```

Given the above documentation, the simulator should compute the desired acceleration as follows:

```
double desired_acceleration = (throttle * kMaxAcceleration) - (brake * kMaxDeceleration)
```

# Old Problem Definition From 2016/12/15

~~`drake/lcmtypes/lcmt_driving_command_t.lcm` includes both `throttle` and `brake` reference values.~~

```
struct lcmt_driving_command_t {
  // The timestamp in milliseconds.
  int64_t timestamp;

  double steering_angle;
  double throttle;
  double brake;
}
```

~~The meaning of these values is unclear to the casual reader. Based on the way `SimpleCar` uses them, they are in fact normalized jerk (i.e., change in acceleration) values. Thus, for clarity, we should consider replacing them with a single `normalized_jerk` field.~~

# Old Problem Definition From 2016/12/13
~~In reality, the `car_sim_lcm` system only provides two control inputs: (1) desired steering angle and (2) desired velocity. We should thus modify `lcmt_driving_command_t` to specify the desired velocity rather than the desired state of the `throttle` and `brake`. Once this is done, `car_sim_lcm` can be simplified since it no longer needs to combine `throttle` and `brake` reference values into a single reference `velocity` for the controller to follow. Likewise, `steering_command_driver.py` can be simplified.~~

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4472.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4579)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sammy-tri for platform review please.

Thanks!

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-:-KZY8czDw0Pq_v-pyQso:bjege30)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 13 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/driving_command_parameters.yaml, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYB26Sl0MgDFPGXAZm:-KZYB26Sl0MgDFPGXAZn:b-cq75cv) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/driving_command_parameters.yaml#L4)):*
> ```YAML
> -
>      name: steering_angle
>      doc: The desired steering angle, positive is to the left.
> ```

The reference frame / context of the angle is ambiguous.  SimpleCar says "virtual center wheel angle".  (Or if this is meant to be open to have different semantics depending on the application, comment that explicitly.)

---

*[drake/automotive/driving_command_parameters.yaml, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYBW_8nyr8-WXJ7kvQ:-KZYBW_9Kk6QrK-Utdpa:bgw5a6n) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/driving_command_parameters.yaml#L7)):*
> ```YAML
> -
>      name: throttle
>      doc: The normalized desired acceleration.
> ```

BTW for both of these consider `(in the range [0.0..1.0])` or similar, for extra clarity.

---

*[drake/automotive/simple_car_gen.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYAPVMObm_EILsYML_:-KZYAPVMObm_EILsYMLa:bqzwr0y) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/simple_car_gen.sh#L14)):*
> ```Shell
> source $drake/tools/lcm_vector_gen.sh
> 
> gen_lcm_and_vector_from_yaml "driving command" $drake/automotive/driving_command_parameters.yaml
> ```

This message (and vector) are not "parameters" (the filename's claim is wrong).

---

*[drake/tools/lcm_vector_gen.py, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYAGh7iMOZPIKuqIff:-KZYAGh7iMOZPIKuqIfg:b2nh7rl) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/tools/lcm_vector_gen.py#L372)):*
>80

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-:-KZYBgl7S673Y5KFssD6:by96gdd)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-:-KZYIahurWo7wR3OhAvQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579)*

**Comment by liangfok** [comment]
I address all reviewer comments. PTAL. Thanks.

---

Review status: 9 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/simple_car_gen.sh, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYAPVMObm_EILsYML_:-KZYz5A620SJSpCReW81:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/simple_car_gen.sh#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This message (and vector) are not "parameters" (the filename's claim is wrong).
</blockquote></details>

Done.

---

*[drake/tools/lcm_vector_gen.py, line 372 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYAGh7iMOZPIKuqIff:-KZYzJbUlcVrZ3LcBTHN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/tools/lcm_vector_gen.py#L372)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

>80
</blockquote></details>

Done.

---

*[drake/automotive/driving_command_parameters.yaml, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYB26Sl0MgDFPGXAZm:-KZYxTLjersa26LAliEa:bmfjqkr) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/driving_command_parameters.yaml#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The reference frame / context of the angle is ambiguous.  SimpleCar says "virtual center wheel angle".  (Or if this is meant to be open to have different semantics depending on the application, comment that explicitly.)
</blockquote></details>

Done. I currently believe the semantics should remain the same regardless of application.

---

*[drake/automotive/driving_command_parameters.yaml, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-KZYBW_8nyr8-WXJ7kvQ:-KZYxaceUwJ4sSrM1ieT:b-qcvq5s) ([raw file](https://github.com/robotlocomotion/drake/blob/f537d95761b56b34838bd388473b88c662cf2ab2/drake/automotive/driving_command_parameters.yaml#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW for both of these consider `(in the range [0.0..1.0])` or similar, for extra clarity.
</blockquote></details>

Done.> (in the range [0.0..1.0])

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-:-KZYzKc9jPA1T70283sU:b7h4bhm)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4579#-:-KZYzyVvpOxU-8dfJfUa:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Pull request merged**
