### PR TITLE
Add an optional RGB image input port to DepthImageToPointCloud

### PR DESCRIPTION
**Pull request by kmuhlrad**
Adds an optional input port to the DepthImageToPointCloud system to take in an RGB image and ouput a PointCloud with both kXYZs and kRGBs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10601)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@kunimatsu-tri would you like to do feature review here?

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review (will look soon, but probably not tonight).

**Comment by jwnimmer-tri** [comment]
___
*[perception/depth_image_to_point_cloud.h, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10601#-LYHbZGi04LYqnX4Ciui:-LYHbZGi04LYqnX4Ciuj:b25muyg) ([raw file](https://github.com/robotlocomotion/drake/blob/b7fa46e0e6cabdfee48ff28a96c0da9735ee7238/perception/depth_image_to_point_cloud.h#L59)):*
> ```objc
>   explicit DepthImageToPointCloud(
>       const systems::sensors::CameraInfo& camera_info,
>       systems::sensors::PixelType depth_pixel_type =
> ```

@EricCousineau-TRI do you have any pydrake API advice for this case?  Here, we're clarifying the C++ argument name, in light of the new color image capabilities added in this PR.  The API documentation mentions the new name (only), of course.  The pre-existing pydrake binding is left unchanged -- there, this argument is still named "pixel_type".  That's good in that existing code that calls using kwargs will keep working, but bad in that help() on this pydrake method will lie about its kwargs.  Any suggestions?

**Comment by kmuhlrad** [comment]
Thank you!

**Pull request merged**
