### PR TITLE
[geometry/optimization] remove problematic shortest path problem test for ipopt

### PR DESCRIPTION
**Pull request by RussTedrake**
it was introduced in the original PR only to document IPOPT's bad behavior.  turns out the behavior was worse than expected, and the test failed on mac CI https://drake-cdash.csail.mit.edu/test/320932067 .  Russ, Soonho, and Betsy were unable to reproduce it on our local macs.  I've simply removed the test, adding a textual documentation of the problem instead.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15509)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot +mac-catalina-clang-bazel-continuous-release please

**Review by soonho-tri — COMMENTED** [review]
+@soonho-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15509#-:-MfjLu3O2Kn6PfG37h2a:b-v3eqt6)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm: :crossed_fingers: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15509#-:-MfjM4iZ8YML0BwxFYt0:bejbbxh)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by RussTedrake** [comment]
Resolves #15504

**Review by soonho-tri — COMMENTED** [review]
FTR, I was able to reproduce the problem on my mac by using the ipopt version that our CI servers are using (ipopt-3.13.4_1). The problem goes away when I use the latest ipopt (ipopt-3.14.2).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15509#-:-MfjPj3qBml7_C_73DgX:b-5oaee3)* status: :shipit: complete! all discussions resolved, LGTM from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
