### PR TITLE
zap all matlab utils that are not currently being used.

### PR DESCRIPTION
**Pull request by RussTedrake**
there are lots of useful tools in here; we should bring them back at the first opportunity.  but this feels like the only way to have our clean start.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6705)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@avalenzu , +@hongkai-dai for platform review (e.g., confirmation of the concept)

---

Review status: 0 of 308 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqE2SsYQmM4c5aJ9aVh:b-oz9tg1)*

**Comment by hongkai-dai** [comment]
:lgtm: we also need to remove the test `matlab/check_dependency_unknown`

---

Review status: 0 of 308 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqEa1fJcEcifbmg55gY:b-1kzq83)*

**Comment by avalenzu** [comment]
:lgtm: I agree that it's better to just bring back what we need.

---

Review status: 0 of 309 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqOfPhcq5xcIeE8LB70:bea1prg)*

**Comment by jamiesnape** [comment]
Note that `getDrakePath` and the other path related utilities are going to need to be retooled when the CMake build of Drake goes away, so you may consider removing them here.

**Comment by RussTedrake** [comment]
@jamiesnape -- i needed getDrakePath to stay only for the single matlab test (now reintroduced in matlab/solvers/test).  definitely want to update it with the build system.  and was going to ask you to nuke the pods_path scripts as appropriate (i don't believe anyone uses them).

**Comment by RussTedrake** [comment]
+@EricCousineau-TRI for platform review, please.  (please go ahead and merge if you're happy)

---

Review status: 0 of 309 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqPXgnp-ZAh0ZDZvIXJ:bu3wu0a)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: 0 of 309 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqP_7JCOeMmkXiVye55:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 309 of 309 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705)*

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for final platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqP_K9m3ljR65lRqNAq:b-w3iept)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 309 of 309 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6705#-:-KqPsGYI4D8fDDKZB6Se:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For the record: relates #6369.

**Pull request merged**
