### PR TITLE
Slightly improve the SimpleCar documentation

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2195)

### CODE REVIEW

**Comment by liangfok** [comment]
I left some comments. See the conventional robotics coordinate frame definition here: http://www.ros.org/reps/rep-0103.html#axis-orientation

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/SimpleCar/simple_car.h, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-KGNLkP_rWjIoOFWKdm3:-KGNLkP_rWjIoOFWKdm4:2101073036) ([raw file](https://github.com/robotlocomotion/drake/blob/0cb79f9c5d37207a8474ac4a0b51d583248696db/drake/examples/SimpleCar/simple_car.h#L23)):*
FWIW. In robotics, the Z-axis is up and the right-hand rule is used. Thus, assuming this is true, a positive heading angle typically results in the vehicle turning left.

---

*[drake/examples/SimpleCar/simple_car.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-KGNMA-nuE04ghazQDHZ:-KGNMA-nuE04ghazQDH_:202228832) ([raw file](https://github.com/robotlocomotion/drake/blob/0cb79f9c5d37207a8474ac4a0b51d583248696db/drake/examples/SimpleCar/simple_car.h#L29)):*
Hmm, in robotics, the Y axis points left and the X axis points forward, so a heading of 0 is typically when it is pointing along the +X axis and is 90 degrees when pointing left along the +Y axis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-:-KGNMOdBHDMTaTXxt7QT:-2033297451)*

**Comment by jwnimmer-tri** [comment]
The "axis orientation" appears to be describing body-relative coordinates.  The x and y in SimpleCar are the car's world coordinates, not body-relative.  (Basically, ENU without the U.)

Perhaps I need to clarify that in the comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/SimpleCar/simple_car.h, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-KGNLkP_rWjIoOFWKdm3:-KGNOXZPRzqnwpfL33Tn:-792618834) ([raw file](https://github.com/robotlocomotion/drake/blob/0cb79f9c5d37207a8474ac4a0b51d583248696db/drake/examples/SimpleCar/simple_car.h#L23)):*
I don't think this is true for ENU?

---

*[drake/examples/SimpleCar/simple_car.h, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-KGNMA-nuE04ghazQDHZ:-KGNOdj7I_A2t5xFk_b8:-1028162309) ([raw file](https://github.com/robotlocomotion/drake/blob/0cb79f9c5d37207a8474ac4a0b51d583248696db/drake/examples/SimpleCar/simple_car.h#L29)):*
Also not true for ENU?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-:-KGNNuUqED6ZE1pp5iuu:985968004)*

**Comment by liangfok** [comment]
Isn't ENU used for aviation? Since a car is not an airplane, I would recommend adopting the robotics world's coordinate frame convention.

Can you clarify what you mean by "body-relative"?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-:-KGNP9zZuA7U7xZfAWjh:933633365)*

**Comment by liangfok** [comment]
Oh, interesting, quote from [this page](https://en.wikipedia.org/wiki/Axes_conventions#Ground_reference_frames:_ENU_and_NED):

> In case of land vehicles like cars, tanks etc., which use the ENU-system (East-North-Up) as external reference (world frame), the vehicle's positive y- or pitch axis always points to its left, and the positive z- or yaw axis always points up.

So does the X axis point backwards?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-:-KGNQLEJWFWMrZVvwWvA:-1936627259)*

**Comment by liangfok** [comment]
Nevermind. I think ENU actually describes the conventional robotics coordinate frame where X = forward, Y = left, and Z = up.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2195#-:-KGNR4WTlV5EPDJ03oKj:1124369165)*

**Comment by jwnimmer-tri** [comment]
Update: Apparently I've destroyed the world by opening a can of worms.  I am discussing internally within TRI and will post an update later.

**Pull request closed without merging**
