### PR TITLE
Improve wheel testing instructions

### LINKED ISSUE #18968: Documentation for wheel PR local testing
If a code reviewer on a wheel-related PR would like to test it in `pip` locally, there's no easy / clear instructions for this.  We should write some.  Probably the new doc would live in the `tools/wheel/README`.

The idea would be to test using the experimental wheels built from CI, rather than building locally.

General gist:
* Offer a copy-paste command(s) for the jenkins bot to run some (or all) wheel builds on a PR.
* Explain how to find the whl download links in the PR output.
* Explain how to install and run it locally for testing (basically https://drake.mit.edu/pip.html#nightly-releases but with a different URL).

The primary focus would be for running-on-Jammy developers (manylinux cp310).  It's fine to document other platforms also, but the most important thing is for the Jammy workflow to be clear and obvious.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update the instructions for how to find the URL of a wheel built as part of a pull request experimental build (the links are now easier to find). Add instructions for how to locally install the wheel.

Fixes #18968.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for (feature? both?) review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: for my part.

The ticket here was motivated by #18919, so I'll tag +@SeanCurtis-TRI and +@xuchenhan-tri to also please review this new documentation.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-:-NlVDG-y97_kwrCeQTYW:b-s33wl8)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform)

___
*[`doc/_pages/jenkins.md` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-NlVDzjj5ls3apN2Y9Rt:-NlVDzjk41ItkT-m22Ly:bobmy3l) ([raw file](https://github.com/RobotLocomotion/drake/blob/d478a53508756ebc3f4f295e59bbd292841430e3/doc/_pages/jenkins.md#L186)):*
> ```Markdown
> To download the wheel, simply click the link or use your favorite HTTP
> retrieval too (e.g. ``wget`` or ``curl``).  To install a wheel for local
> testing:
> ```

BTW When I was running through this locally, I almost accidentally downloaded the link even though I didn't need to.  Possibly the docs could highlight the either/or nature here, like so:



_Suggestion:_
```Markdown
To download the wheel, simply click the link or use your favorite HTTP
retrieval too (e.g. ``wget`` or ``curl``).

Or, to install a wheel for local testing (no download required):
```

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/jenkins.md` line 186 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-NlVDzjj5ls3apN2Y9Rt:-NlYdWjrDXqVqSA8yz70:bpu21ym) ([raw file](https://github.com/RobotLocomotion/drake/blob/d478a53508756ebc3f4f295e59bbd292841430e3/doc/_pages/jenkins.md#L186)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW When I was running through this locally, I almost accidentally downloaded the link even though I didn't need to.  Possibly the docs could highlight the either/or nature here, like so:
</blockquote></details>

Done. (Slightly different wording; the wheel must still be downloaded, but `pip` is doing so.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-:-NlYkyFg6UqGSeVHlq4u:bmxilld)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-:-NlZEonp3vWamuSZx3M9:bg7igkv)* status: 1 unresolved discussion

___
*[`doc/_pages/jenkins.md` line 185 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-NlZEmH11nMvUnHKaRi1:-NlZEmH11nMvUnHKaRi2:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/84542595560578af4c205c91d3560dbe8d2d8e70/doc/_pages/jenkins.md#L185)):*
> ```Markdown
> 
> To download the wheel, simply click the link or use your favorite HTTP
> retrieval too (e.g. ``wget`` or ``curl``).
> ```

typo?



_Suggestion:_
```Markdown
To download the wheel, simply click the link or use your favorite HTTP
retrieval tool (e.g. ``wget`` or ``curl``).
```

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/jenkins.md` line 185 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20661#-NlZEmH11nMvUnHKaRi1:-NlZTROH4jSabKfdfKyf:biesicp) ([raw file](https://github.com/RobotLocomotion/drake/blob/84542595560578af4c205c91d3560dbe8d2d8e70/doc/_pages/jenkins.md#L185)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Indeed; thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20661)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),xuchenhan-tri(platform)

**Pull request merged**
