### PR TITLE
[releng] Don't sign individual files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18659.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19496)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@BetsyMcPhail to kick off review, please.  \CC @mwoehlke-kitware

There are two commits.

The first commit is definitely wanted.  It removes tgz signing.

The second commit is probably wanted, as best I understand.  I don't think uploading to aptly requires each deb to be signed individually.  Rather, only the releases files is signed.  So, this removes the sign/no-sign option entirely, by turning off all signing.  (You could test the equivalent thing by running the current push_release with the --no-sign flag.)

Note that the GPG key is still required.  The information we were using in the meeting to base our decisions on was wrong, I think.  The crux of the matter was the key passed to aptly, not gpg.

I propose the new goal is these three, separate, scripts:

(1) `release_aptly` does the aptly reindexing and release signing.  It should fetch the current S3 aptly data, download the new debs from the GitHub release page, merge them into the site ("switch").  This is very much like the `push_apt` stanza of the current script, but not GPG-signing each individual deb file.

(2) `release_docker` does the image push + pull tagging.  This is very much like the `push_docker` stanza of the current script.

(3) `release_mirror` syncs the GitHub attachments into S3 storage.

I think trying to bite off all three at once into a single unified program rewritten in big-bang style is slowing us down.  We should be able to create each new script one by one and start using it.  Once all three items are rewritten, we can delete the old script.

From the sound of it, the `release_aptly` is the most painful step currently so that should be the focus of the next tool to be written.

Given the above, if this PR is still useful then feel free to review it to be merged.  If the only thing we needed was clearer requirements, and we're going to write new programs entirely from scratch, maybe just reading this PR is enough and we can close is unmerged.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19496#-:-NWKBxjf-z_kG08yjbxe:bmfbwri)* status: LGTM missing from assignee BetsyMcPhail, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail and @jwnimmer-tri)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm:

I feel sort of weird about removing signing. Signing, done properly, is good, as it ensures (so long as no attacker gains access to the private signing key) that the files we distribute are as built and haven't been replaced with maliciously altered copies.

That said, long term that logic should be happening when the packages are built, and the artifacts should land in GitHub along with the packages themselves. (And the signature files should be properly documented.) So, while this may be worth revisiting, I think it's acceptable for the sake of being able to make progress to remove those actions from `push_release`.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19496#-:-NWiJj8cA2kr6BbQXzYp:b-to7rrf)* status: LGTM missing from assignee BetsyMcPhail, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail and @jwnimmer-tri)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: I'm happy for both of these changes to go in. 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19496#-:-NWiNV__22aaed6SEnyt:b-m5pq8r)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
I don't have knowledge on the pros and cons of requiring a signature, but with two feature reviewers I feel I'm in good hands.
:lgtm: platform.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19496#-:-NWmiT3u9UBDo4UrKbut:bcgd7du)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> Signing, done properly, is good, as it ensures (so long as no attacker gains access to the private signing key) that the files we distribute are as built and haven't been replaced with maliciously altered copies.

This https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/ says it better than I could.

**Pull request merged**
