### PR TITLE
Allow Geometry inspector to read SDFs outside of the the Drake build environment.

### PR DESCRIPTION
**Pull request by edrumwri**
This PR does a number of things toward accomplishing that goal (and then some):

(1) Addresses Issue #10099 by allowing AddModelFromSdfFile(.) to accept PackageMap arguments, and modifies geometry_inspector.py to accept a package path on the command line. 
(2) Adds relevant python bindings.
(3) More correctly parses URI attributes in SDF and URDF files and renames the corresponding function from ResolveFilename(.) to ResolveUri(.)
(4) Adds missing unit tests for ResolveUri(.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10156)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> I'm halfway through preparing a PR that also adds the deprecation annotations to the C++ AddModelFromSdfFile ...

Posted now at #10157.  I still have a little cleanup and self-review to do before assigning it out, but it should give the rough idea.

**Comment by jwnimmer-tri** [comment]
On the question of the mutable_package_map vs new-arg-on-Parser-constructor, please let me weigh in (tomorrow) on the topic before revising anything here.  My guess is that I prefer not having the ctor argument, but I want to review the way the code turned out before saying for sure.  No matter what, we'll still need the get_mutable -- so that library code has the ability to amend the package mappings but not necessarily own either the Parser or the PackageMap.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/parsing/detail_path_utils.cc, line 108 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LTZ2P1uCk3zFQRXflWy:-LTbqEjN6QYbfnXYvyKf:b-abwpls) ([raw file](https://github.com/robotlocomotion/drake/blob/2f56a8b764ab23b723894f3a144bac912de7c506/multibody/parsing/detail_path_utils.cc#L108)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you check the invariant on index 1? Otherwise, I could do something like `model:/boo/package_name/...`.
</blockquote></details>

There is a lot wrong with this method body (much of it from master, not this PR).  I am going to submit a PR to Evan's branch with rework.

**Comment by EricCousineau-TRI** [comment]
BTW @edrumwri A workflow that I've found useful is to maintain two separate branches when working on a longer-term PR: a WIP branch that I do my merge commits and have a dirty history in, and then the actual branch for the PR where I rebase frequently to ensure I only have the bits I want.

**Comment by jwnimmer-tri** [comment]
___
*[manipulation/util/geometry_inspector.py, line 86 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LTZ1Qgt3x5nQ2NYPBH3:-LTyZC_X8FxbI__VJfX9:b-63zvyu) ([raw file](https://github.com/robotlocomotion/drake/blob/2f56a8b764ab23b723894f3a144bac912de7c506/manipulation/util/geometry_inspector.py#L86)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Thanks for pointing me to the os utilities!

AFA parser.error, I'm not sure what you're referring me to. The Parser class does not have an error method?


</blockquote></details>

Yikes!  The confusion here is that at the start of this function, there is `parser = argparse.ArgumentParser(...)`, and then here we _reassign_ that name to a new object.  Eric wants us to use argument parser's error method (which does exist).  I think the model parser need to have a different variable name.

**Comment by EricCousineau-TRI** [comment]
___
*[manipulation/util/geometry_inspector.py, line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LTZ0stpEUuA1Ub9ZsrF:-LU1wtxh1JM3Wd3geRVV:btg1juy) ([raw file](https://github.com/robotlocomotion/drake/blob/2f56a8b764ab23b723894f3a144bac912de7c506/manipulation/util/geometry_inspector.py#L13)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What's wrong with $HOME?
</blockquote></details>

(a) It implies that we have a prescribed location for drake and (b) no other example usages use it, either in their doc or in our documentation.
Non-prescribed directories are better on the whole, especially for examples.

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/parsing/detail_path_utils.cc, line 76 at r5](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LTcxrT0AeHg77NzPKSX:-LU2685B9j_UiNbia1IU:baj81f) ([raw file](https://github.com/robotlocomotion/drake/blob/63d017b7071a05ff97772477ebdac92071e20605/multibody/parsing/detail_path_utils.cc#L76)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Sorry, Eric, I'm not sure what you're asking for here. 
</blockquote></details>

OK Was trying to see if there was a way to show the URI format, but it's pretty standard, and not very clear to generalize, so will redact. Sorry!

**Comment by EricCousineau-TRI** [comment]
___
*[manipulation/util/geometry_inspector.py, line 10 at r10](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LU2gfY7BwOxMkUzP7Rv:-LU2h1OI0ebshrl7Pi1z:b-rv4a50) ([raw file](https://github.com/robotlocomotion/drake/blob/288f1d7bdd3b4cf368c4945d45d9120b68ed73ce/manipulation/util/geometry_inspector.py#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Please use absolute paths for targets, or just remove this.

TBH, it's simpler just to have the "Build everything necessary" line.
</blockquote></details>

(e.g. `//manipulation/util:geometry_inspector`)

**Comment by jwnimmer-tri** [comment]
___
*[multibody/parsing/parser.h, line 35 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10156#-LTZpdN-70p6KeunDwxn:-LU2l7Jo7XaLn9bczyHy:b-3gsx5l) ([raw file](https://github.com/robotlocomotion/drake/blob/ff5e4a377d1a207d72a05c2361fd4e9f51e24ae7/multibody/parsing/parser.h#L35)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Crap. Your request that we populate upstream from Drake in Parser means that I'll have to construct this "package" in an unorthodox manner (not "upwards" from the SDF). Do you have a suggestion? 
</blockquote></details>

I believe that the path returned by https://github.com/RobotLocomotion/drake/blob/master/common/temp_directory.h will be insulated from any interaction from PopulateUpstreamToDrake.

We could spruce::copy the test case's xml, sdf, and obj from the FindResource path into the tmpdir path, and then test the package_map interaction with respect to that tmpdir.

Or, we could have C++ code write out (ofstream) the literal file contents to the tmpdir, instead of storing the test case data in git as separate files.

**Pull request merged**
