### PR TITLE
introduce BarycentricMeshSystem

### PR DESCRIPTION
**Pull request by RussTedrake**
adds utility to create a barycentric mesh function from a std::function

make BarycentricMesh copyable etc

adds BarycentricMeshSystem (a vector system defined by a barycentric mesh + values)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8030)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review
+@jwnimmer-tri for platform review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-:-L50eaNOnBfu8uZT9fAg:buadczj)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[math/barycentric.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50iZefD-vlPsP-aylF:-L50iZeg9yvpuVemGfIC:b7iudmd) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/barycentric.h#L116)):*
> ```objc
>   ///
>   /// Example usages:
>   ///    Eigen::VectorXd vector_func(const Eigen::Ref<const Eigen::VectorXd)
> ```

I don't understand what this line is trying to say.

---

*[math/barycentric.h, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50ijTKJlK39Q1PqvXH:-L50ijTKJlK39Q1PqvXI:bv30ui5) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/barycentric.h#L118)):*
> ```objc
>   ///    Eigen::VectorXd vector_func(const Eigen::Ref<const Eigen::VectorXd)
>   MatrixX<T> MeshValuesFrom(
>       const std::function<VectorX<T>(const Eigen::Ref<const VectorX<T>>&)>
> ```

BTW Missing `&` at end of line here (we don't want to copy the function).

---

*[math/test/barycentric_test.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50jNGgF-03u_00CIpR:-L50jNGgF-03u_00CIpS:b-1rsopv) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/test/barycentric_test.cc#L143)):*
> ```cpp
> }
> 
> Vector1d my_sine(const Eigen::Ref<const Vector1d> x) {
> ```

BTW Missing `& ` for `x`.

---

*[systems/primitives/barycentric_system.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50l4sqoyIQSn5x1fwu:-L50l4sqoyIQSn5x1fwv:bw2krtk) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L33)):*
> ```objc
>   /// @p output_values is a matrix with each column representing the value to
>   /// output if the input is the associated mesh point.  It must have the same
>   /// number of columns as mesh->get_num_mesh_points().
> ```

FYI You could hint in the docs that `output_values` can come from `mesh.MeshValuesFrom(function)`.  (Or offer an overloaded delegating constructor that does that.)

---

*[systems/primitives/barycentric_system.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50klmPMRn4RT4ZWur3:-L50klmPMRn4RT4ZWur4:b1uh3yd) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L35)):*
> ```objc
>   /// number of columns as mesh->get_num_mesh_points().
>   BarycentricMeshSystem(math::BarycentricMesh<T> mesh,
>                         const Eigen::Ref<const MatrixX<T>> output_values)
> ```

BTW Missing `& ` for output_values.

---

*[systems/primitives/barycentric_system.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50ltgbJbYztrZWO2UC:-L50ltgcQtxc7WHP4E9-:beyfo5u) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L55)):*
> ```objc
> 
>  private:
>   math::BarycentricMesh<T> mesh_;
> ```

BTW I think `mesh_` could be const.

---

*[systems/primitives/BUILD.bazel, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50kJfs49wXglk55XJ0:-L50kJfs49wXglk55XJ1:bypwdfr) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/BUILD.bazel#L62)):*
> ```Python
>     hdrs = ["barycentric_system.h"],
>     deps = [
>         "//drake/math:barycentric",
> ```

BTW Missing `//systems/framework:vector_system`.

FYI Adding an empty `.cc` file would catch this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-:-L50mUxlqUfdqxZ9fhDv:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 1 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[math/barycentric.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50iZefD-vlPsP-aylF:-L50nZ63n-hsicNxqtBg:b50b27t) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/barycentric.h#L116)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand what this line is trying to say.
</blockquote></details>

fixed.  (that was an unfinished thought)

---

*[math/barycentric.h, line 118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50ijTKJlK39Q1PqvXH:-L50nkWh7qyxjFy7aObL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/barycentric.h#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing `&` at end of line here (we don't want to copy the function).
</blockquote></details>

Done.

---

*[math/test/barycentric_test.cc, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50jNGgF-03u_00CIpR:-L50nqY42aimWDYfLQBm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/math/test/barycentric_test.cc#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing `& ` for `x`.
</blockquote></details>

Done.

---

*[systems/primitives/barycentric_system.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50l4sqoyIQSn5x1fwu:-L50oPCFlvjwoH3IwF2x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI You could hint in the docs that `output_values` can come from `mesh.MeshValuesFrom(function)`.  (Or offer an overloaded delegating constructor that does that.)
</blockquote></details>

Done.

---

*[systems/primitives/barycentric_system.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50klmPMRn4RT4ZWur3:-L50oTMuQ_jcQbYRL_wh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing `& ` for output_values.
</blockquote></details>

Done.

---

*[systems/primitives/barycentric_system.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50ltgbJbYztrZWO2UC:-L50oZoo5AN0ItqFaVZs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/barycentric_system.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think `mesh_` could be const.
</blockquote></details>

Done.

---

*[systems/primitives/BUILD.bazel, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50kJfs49wXglk55XJ0:-L50pB_wFYLQ1G6N5h4I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9fb2522d760dd0c2ebffd809f47bcf422640d9c6/systems/primitives/BUILD.bazel#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Missing `//systems/framework:vector_system`.

FYI Adding an empty `.cc` file would catch this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-:-L50uvv-AisGrkCz-ksl:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 6 files at r1, 2 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[systems/primitives/test/barycentric_system_test.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8030#-L50wtDPmNR3HM3D5Hsw:-L50wtDPmNR3HM3D5Hsx:b7mh104) ([raw file](https://github.com/robotlocomotion/drake/blob/eabe05d6391623e85745a581de810c11d5072085/systems/primitives/test/barycentric_system_test.cc#L25)):*
> ```cpp
> 
>   // Create a BarycentricMesh in 2d.
>   math::BarycentricMesh<double> bary({{-1., 1.},  // BR
> ```

What does `BR` mean here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8030)*

**Pull request merged**
