### PR TITLE
Added dependency list to testLidar build target.

### PR DESCRIPTION
**Pull request by liangfok**
Fixes https://github.com/RobotLocomotion/drake/issues/2330#issuecomment-218856929

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2331) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by liangfok** [comment]
+@jamiesnape for feature review after CI tests pass

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added dependency list to testLidar build target\.
> 
> Fixes https://github.com/RobotLocomotion/drake/issues/2330#issuecomment-218856929
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2331#-:-KHaQOjrxzVgCkUy7LWl:1363039068)*

**Comment by liangfok** [comment]
The CI build test successfully completed. Thus +@jwnimmer-tri for platform review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@jamiesnape for feature review after CI tests pass</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2331#-:-KHaYJjbD85yW77340o6:-383203708)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

I would of course prefer that we didn't have to mumble this line everywhere (since likely many more examples are missing this incantation), but that's for another issue / PR to fix.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The CI build test successfully completed. Thus +@jwnimmer-tri for platform review.</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2331#-:-KHaYn0BiVcCNaWmFhTr:1671551253)*

**Comment by liangfok** [comment]
Agreed. Shall we wait for a separate feature reviewer or can you override/merge?

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> :lgtm:
> 
> I would of course prefer that we didn't have to mumble this line everywhere (since likely many more examples are missing this incantation), but that's for another issue / PR to fix.</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2331#-:-KHaZi1HRHx2FDxhnM_N:-1514640414)*

**Pull request merged**
