### PR TITLE
Move parsing utilities

### PR DESCRIPTION
**Pull request by amcastro-tri**
In preparation for MBT parsing this PR moves some useful code using the `sdformat` library from `examples/double_pendulum` to `multibody/parsing/sdf`. Besides namespaces changes, the code was not modified at all, just moved.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7441)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXdCVktANB694kjiDl:b-4269ug)*

**Comment by SeanCurtis-TRI** [comment]
This all seems relatively straightforward. A couple of questions:

1. is the extra directory level `parsing/sdf` there because we imagine having *other* parsers?
2. Is the directory name `sdf` slightly misleading because it will parse both urdf and sdf?

I'm going to defer my lgtm until after this passes CI.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXktFbd_94l-bfDQ1x:bmox2s2)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXloU6aG5KengPLcfV:b-s794vx)*

**Comment by amcastro-tri** [comment]
1. Yes, that is the reason I created the `sdf` directory. `urdf`? though I know you know a way to parse urdf's using the sdformat library?
2. Are you asking? I guess you have a better answer than I do at this point.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXlownq736dNlgDLOE:b-oaylv9)*

**Comment by SeanCurtis-TRI** [comment]
You give me more credit than I deserve.

1. I haven't parsed a urdf file, but I understand that's part of the `sdformat` library.
2. I don't have a better answer yet; I just don't like the fact that the directory name suggests something that isn't true. Plus, if someone goes looking for URDF parsing, they won't see anything. Is there a name we can apply to both URDF and SDF and use *that* for the directory? `robot_descriptor`, maybe?  `sdf_urdf`?

:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXmr37_qFGYHAGyA55:b-m6o6sq)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXp5DN0TwG29VaUJEF:b-v3eqt6)*

**Comment by amcastro-tri** [comment]
To be honest I don't have a well formed answer at this point. My plan was to push the bare minimum parsing code and find an owner from OSRC to decide what to do with it.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXp5TT4KdTmmfLWt1g:bh74070)*

**Comment by SeanCurtis-TRI** [comment]
Sorry @soonho-tri , I was delaying pinging you in case we decided to move it to some other directory/namespace.

@amcastro-tri So, your ultimate dream is for all of this to disappear into `libsdformat`? Still, having a good plan for if that *doesn't* happen is nicely conservative.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXpYsmYGkEz13rl1Rr:b309z2g)*

**Comment by soonho-tri** [comment]
platform :lgtm: for the fact that the refactoring preserves functionalities.

Having both of `drake/multibody/parsers` and `drake/multibody/parsing` seems to be a bit duplicative though.

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXpj_rt-aVn0thlmMP:b-xisg0y)*

**Comment by soonho-tri** [comment]
Sorry, just found that there is a discussion at #dynamics.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXr9W2KsrOWUgHDbtz:bpzh5aq)*

**Comment by amcastro-tri** [comment]
> So, your ultimate dream is for all of this to disappear into libsdformat? 

That is a good way to put it, yes, that'd be my ultimate dream :-)

> Having both of drake/multibody/parsers and drake/multibody/parsing seems to be a bit duplicative though

I agree, in the same way we have `multibody` and `multibody_tree`. `drake/multibody/parsers` will eventually go away with RBT.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXrL_jgli5nKlRR_29:b-krzvdh)*

**Comment by sherm1** [comment]
How about just `multibody/parsing` (no subdirectory), assuming we'll just be doing sdf and urdf (both hopefully through sdformat)? We could move it later if some other parsing need shows up.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyXzbVnukUyBeCca8XD:bvx4meb)*

**Comment by SeanCurtis-TRI** [comment]
I'd accept that.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyY1O-05ehABX3neHa8:b-mjplgy)*

**Comment by soonho-tri** [comment]
SGTM

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyY1uMwEAwR_RhZGvjF:bb73djm)*

**Comment by amcastro-tri** [comment]
ok, I moved everything one level up to `drake/multibody/parsing`, no `sdf` directory.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441#-:-KyaLlRuIi7FxYMcI_F8:bcf11s5)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 13 files at r1, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7441)*

**Pull request merged**
