### PR TITLE
[geometry] Add Meshcat API for directly testing message handling

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20548)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

If you like, you could wait to review until I post the patch that uses this.  (Though possibly this is convincing enough on its own merit.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: Its purpose and implementation are clear.

You've carved out a space for the slider command in the documentation. Is it possible to pass a mock websocket so that it doesn't require the carve out? (I haven't looked at the websocket API, but I can easily imagine there is no virtual interface. But I thought I'd ask for the sake of completeness.)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20548#-:-NjP0uY-0SFGwq1LqTrU:b-4a8rr3)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/meshcat.h` line 912 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20548#-NjP0Wgw2FyhdGFscsqL:-NjP0Wgx5iDGQuWNRAcf:b6mw5pj) ([raw file](https://github.com/RobotLocomotion/drake/blob/6d639c74e283dcb759f3ff59d8610a8928b9197f/geometry/meshcat.h#L912)):*
> ```objc
>   controls) do not allow a null pointer. This function blocks until the message
>   has been handled. */
>   void InjectWebsocketMessage(std::string_view message);
> ```

BTW Creating a valid string for this input is non-intuitive. It might be worth indicating such and pointing them toward a set of unit tests that illustrate how it is done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> Is it possible to pass a mock websocket so that it doesn't require the carve out?

That crossed my mind as well.  I only poked around with it for a minute or two before I gave up.  It did not seem obvious how to do it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20548#-:-NjP3LL79j2BAcMzdvlm:b89yufx)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20548#-:-NjPGrmh9tuxn_9y6VO8:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
