### PR TITLE
Download and install drake-visualizer built with static libraries

### LINKED ISSUE #6680: Install drake_visualizer
It seems to me that `bazel run :install` should install a copy of `drake-visualizer` (maybe named `drake_visualizer`; whatever).   Drake's binary release will be much more usable if the built-in visualization tool works out of the box.

(Alternatively, our binary release could document how to download and install `drake-visualizer` from the Director binary releases, but that seems like it would not always like up with what our binary release of `pydrake` would be providing.  That seems worse.)

As a related benefit even for from-source users, installation might be a good way to solve the "Bazel runfiles sometimes vanish when I rebuild something else" headache.  A quick `bazel run //tools:install_drake_visualizer` would put the tool into known place that would not change until the user asked it to.  That may help people who like to keep the visualizer running for a long time while rebuilding other parts of the tree during development, and best matches the long-standing workflow.

### PR DESCRIPTION
**Pull request by jamiesnape**
Resolves #6680. This also makes the Drake and RobotLocomotion LCM types available to drake-visualizer.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6843)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source  please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot  linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot  linux-xenial-clang-experimental please
@drake-jenkins-bot  linux-xenial-clang-experimental-debug please
@drake-jenkins-bot  linux-xenial-clang-ninja-experimental-open-source please
@drake-jenkins-bot  linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot  linux-xenial-gcc-experimental-open-source please
@drake-jenkins-bot  linux-xenial-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
+@stonier and +@soonho-tri for feature review.

**Comment by soonho-tri** [comment]
I first checked `bazel run //tools:drake_visualizer` and got the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/drakevisualizerapp.py", line 36, in main
    applicationName=appName)
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/componentgraph.py", line 148, in construct
    self.initComponent(name, defaultFields)
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/componentgraph.py", line 164, in initComponent
    newFields = initFunction(inputFields)
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/mainwindowapp.py", line 421, in initDrakeVisualizer
    from director import drakevisualizer
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/drakevisualizer.py", line 3, in <module>
    from director import lcmUtils
  File "/private/var/tmp/_bazel_soonhok/51e1ef8bb59598000e1968965dd33f03/external/drake_visualizer/lib/python2.7/dist-packages/director/lcmUtils.py", line 1, in <module>
    import lcm
ImportError: No module named lcm
```

---

Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrbLbYDyeiNETBJOoOc:b4yafg4)*

**Comment by jamiesnape** [comment]
Sorry, should be fixed now.

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krb_EUyr74Yo7Y-TBmm:b-qy3734)*

**Comment by soonho-tri** [comment]
Thanks. It fixed the issue and `bazel run //tools:drake_visualizer` works on my macs.

But, here is another problem. After running `bazel run install <install_path>`,  I set up `LD_LIBRARY_PATH` properly and ran `./bin/drake-visualizer` but I got the following error:
```
$ ./bin/drake-visualizer
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/soonhok/tmp/drake/lib/python2.7/dist-packages/director/drakevisualizerapp.py", line 3, in <module>
    from director import mainwindowapp
  File "/Users/soonhok/tmp/drake/lib/python2.7/dist-packages/director/mainwindowapp.py", line 2, in <module>
    from director.componentgraph import ComponentFactory
  File "/Users/soonhok/tmp/drake/lib/python2.7/dist-packages/director/componentgraph.py", line 2, in <module>
    from director.fieldcontainer import FieldContainer
  File "/Users/soonhok/tmp/drake/lib/python2.7/dist-packages/director/fieldcontainer.py", line 1, in <module>
    import vtk
ImportError: No module named vtk
```

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrbeE4Pm3qkLig3fey_:b-m9w3qg)*

**Comment by jamiesnape** [comment]
I guess we are going to need a wrapper script to set the `PYTHONPATH`. Does something like export `PYTHONPATH=/Users/soonhok/tmp/drake/lib/python2.7/dist-packages:/Users/soonhok/tmp/drake/lib/python2.7/site-packages` fix it?

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrbiwJujAj4zfHW1MoU:b-homzya)*

**Comment by soonho-tri** [comment]
I found that the following makes it working:
```
export PYTHONPATH=/usr/local/Cellar/vtk@8.0/8.0.0/lib/python2.7/site-packages
./bin/drake-visualizer
```

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrcMvkdniIdqVvcvPF8:bbjswl1)*

**Comment by soonho-tri** [comment]
My understanding is that `vtk@8.0` is keg-only and not sym-linked under `/usr/local/lib/python2.7/site-packages/`. As a result, we need to set `PYTHONPATH` manually? (as `tools/drake_visualizer_apple.sh` does)

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrcNHsIwfbfkVb5jYQT:bq3ci4)*

**Comment by jamiesnape** [comment]
Yes, exactly.

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrcPB6Xg1kvjOrsAXJF:btih660)*

**Comment by soonho-tri** [comment]
:lgtm: (:apple: portion)

As we discussed above, please either document the `PYTHONPATH` step or provide a wrapper script for mac.

---

Reviewed 1 of 7 files at r1, 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-KrdBlZ8ECsIHuOpcJJy:-KrdBlZ8ECsIHuOpcJJz:b-wi71pc) ([raw file](https://github.com/robotlocomotion/drake/blob/278967c64a0627bfed88483055df616527033b82/tools/drake_visualizer.bzl#L44)):*
> ```Python
> 
>     repository_ctx.download_and_extract(url, root_path, sha256 = sha256)
> ```

@stonier , FYI, I've checked that up to this point, this file is a copy of the deleted `director.bzl` with the updates on qt archives and hashes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrdCPpkXknzuOzvS5zp:b-fkljl2)*

**Comment by jamiesnape** [comment]
Rebuilding the packages now to void having to set `PYTHONPATH`.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything  please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by jamiesnape** [comment]
@soonho-tri please try the latest version. You should not need to set `DYLD_LIBRARY_PATH` or `PYTHONPATH` at all.

**Comment by soonho-tri** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-KrhfWbdc2yJUU4THHz9:-KrhfWbdc2yJUU4THHzA:bm5hik6) ([raw file](https://github.com/robotlocomotion/drake/blob/482c6c81ae8311fd6048f42456febe16503b08b1/tools/drake_visualizer.bzl#L6)):*
> ```Python
> def _impl(repository_ctx):
>     if repository_ctx.os.name == "mac os x":
>         archive = "dv-0.1.0-171-g8752fcd-qt-5.9.1-mac.tar.gz"
> ```

@jamiesnape : I have
```
Error downloading [https://d2mbb5ninhlpdu.cloudfront.net/director/dv-0.1.0-171-g8752fcd-qt-5.9.1-mac.tar.gz] 
to /private/var/tmp/_bazel_soonho.kong/c11e5985260ea661cd5a496c449c8e9c/external/drake_visualizer/dv-0.1.0-171-g8752fcd-qt-5.9.1-mac.tar.gz: 
GET returned 403 Forbidden and referenced by '//:install'.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jamiesnape** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 6 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-KrhfWbdc2yJUU4THHz9:-Kri0BmvFmkUhCmbWj3d:b-6xynjd) ([raw file](https://github.com/robotlocomotion/drake/blob/482c6c81ae8311fd6048f42456febe16503b08b1/tools/drake_visualizer.bzl#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@jamiesnape : I have
```
Error downloading [https://d2mbb5ninhlpdu.cloudfront.net/director/dv-0.1.0-171-g8752fcd-qt-5.9.1-mac.tar.gz] 
to /private/var/tmp/_bazel_soonho.kong/c11e5985260ea661cd5a496c449c8e9c/external/drake_visualizer/dv-0.1.0-171-g8752fcd-qt-5.9.1-mac.tar.gz: 
GET returned 403 Forbidden and referenced by '//:install'.
```
</blockquote></details>

I fixed the permissions in S3. Try again now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by soonho-tri** [comment]
It works. FYI, I still need to set `LD_LIBRARY_PATH=<install_dir>/lib` (otherwise I have `dyld: Library not loaded: @rpath/libddApp.dylib`).

---

Reviewed 2 of 3 files at r3.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Kri7cB8cm_VT5tKrEmQ:b-vp98fq)*

**Comment by jamiesnape** [comment]
Interesting. I ran it locally and did not need to set anything.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrkFqLa2z4vAA_jxxNG:bi2juik)*

**Comment by soonho-tri** [comment]
Do you have `libddApp.dylib` under `/usr/local/lib` (or other system directories)? It is not the case for my machines.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrkLnFXeYmUv1bjsyy0:beexlr9)*

**Comment by jamiesnape** [comment]
No, it is under `/tmp/drake`.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrkMAPWJVH4qTPHkzIl:b-nwhjsf)*

**Comment by soonho-tri** [comment]
FYI, I have the following. Does it indicate any problem?
```bash
$ otool -L ./bin/drake-visualizer | grep "rpath"
	@rpath/libddApp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libPythonQt.dylib (compatibility version 0.0.0, current version 0.0.0)
```

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrkMdsI6itjMQUSRIh2:b-o6wbh3)*

**Comment by jamiesnape** [comment]
I see the problem. The `rpath` itself was set incorrectly. I will create another binary.

**Comment by jamiesnape** [comment]
Per @stonier, reassigning Linux feature review to @jadecastro.

**Comment by soonho-tri** [comment]
> I see the problem. The rpath itself was set incorrectly. I will create another binary.

Thank you!

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrklHo8r2IjizOXpeCp:b99c07a)*

**Comment by jamiesnape** [comment]
@soonho-tri new binary has been uploaded.

**Comment by soonho-tri** [comment]
@jamiesnape , the new version works (without setting up any env vars).

---

Reviewed 1 of 1 files at r4.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrkwOB0wIWzAX6jmMsB:b-aujq1a)*

**Comment by jadecastro** [comment]
Nope.  Running `bazel run //tools:drake_visualizer` gives me: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/drakevisualizerapp.py", line 36, in main
    applicationName=appName)
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/componentgraph.py", line 148, in construct
    self.initComponent(name, defaultFields)
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/componentgraph.py", line 164, in initComponent
    newFields = initFunction(inputFields)
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/mainwindowapp.py", line 172, in initView
    applogic.setCameraTerrainModeEnabled(view, True)
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/applogic.py", line 143, in setCameraTerrainModeEnabled
    if getCameraTerrainModeEnabled(view) == enabled:
  File "/home/jon/.cache/bazel/_bazel_jon/b1604f1aafc3d4e0c35495eaeac3f9f9/execroot/drake-distro/bazel-out/clang-3.9-linux-opt/bin/tools/drake_visualizer.runfiles/drake/external/drake_visualizer/lib/python2.7/dist-packages/director/applogic.py", line 138, in getCameraTerrainModeEnabled
    return isinstance(view.renderWindow().GetInteractor().GetInteractorStyle(), vtk.vtkInteractorStyleTerrain2)
AttributeError: 'vtkCommonCorePython.vtkObject' object has no attribute 'GetInteractor'
```

I'm building on Trusty.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krlz54FAWxSp3NF4TMp:b1odep7)*

**Comment by jamiesnape** [comment]
Uninstall vtk5.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krlzw3bH46OGebG9IKB:b-xe2th9)*

**Comment by jadecastro** [comment]
Did `sudo apt-get remove --purge vtk5`, and it had no effect.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krm-kB91ArsJDY2jl5g:b-7xlcrr)*

**Comment by jamiesnape** [comment]
Can you `echo $PYTHONPATH` here: https://github.com/jamiesnape/drake/blob/cbea0adeac287fa8270cdc6aec5c5bfcf741485f/tools/drake_visualizer_linux.sh#L19 and let me know the output.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krm01X4a0iVH8TEQMYK:bctunwv)*

**Comment by jadecastro** [comment]
Sure. Here is the output just before the I get the traceback: 
```
drake/bindings/python:drake/lcmtypes:external:external/drake_visualizer/lib/python2.7/dist-packages:external/lcmtypes_bot2_core/lcmtypes:external/lcmtypes_robotlocomotion/lcmtypes:external/vtk/lib/python2.7/site-packages:drake/bindings/python:drake/lcmtypes:external:external/drake_visualizer/lib/python2.7/dist-packages:external/lcmtypes_bot2_core/lcmtypes:external/lcmtypes_robotlocomotion/lcmtypes:external/vtk/lib/python2.7/site-packages
```

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Krm1uX27pgndlQS6Y7i:bho3ht0)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r5.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jamiesnape** [comment]
@jadecastro Try again with the latest revision.

**Comment by jamiesnape** [comment]
This needs a small update to the mac binary and on CI before merging.

**Comment by jadecastro** [comment]
Sorry for the delay (my day was full of meetings). 

I tried it just now, and the update works just fine for me. 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-KrqtC8Her5SUfGgtOIE:b-lkoho5)*

**Comment by jadecastro** [comment]
Reviewed 3 of 7 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jadecastro** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Ks4OcSpTsbnQxX-hSJa:bg7igkv)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5UPWNMDiPHu2YY4vV:b-la6nwj) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
> ```Python
> # -*- mode: python -*-
> # vi: set ft=python :
> ```

Since this and VTK are custom-built, can I ask where we have the scripts to reproduce these artifacts?
Is it in `drake-ci`, or in some sort of Docker image?
If so, can we add a link to the script (and possibly the source SHA) that was used to produce this artifact?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5VO5YIkz4Bdg7ASAB:bnkb2zk) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Since this and VTK are custom-built, can I ask where we have the scripts to reproduce these artifacts?
Is it in `drake-ci`, or in some sort of Docker image?
If so, can we add a link to the script (and possibly the source SHA) that was used to produce this artifact?
</blockquote></details>

They will be on CI eventually. The SHA is embedded in the filename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by EricCousineau-TRI** [comment]
Added a request for documenting artifact generation steps, if possible.

Works on Ubuntu with:
```
bazel run //:install -- ~+/build_install
env-extend ~+/build_install  # Will expose appropriate variables for FHS
drake-visualizer --script ./drake/multibody/rigid_body_plant/visualization/show_frames.py &
bazel run //drake/perception/estimators/dev:pose_closed_form_test
```
Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Ks5UkpYeJgFU4Gz_qXi:bas1i36)*

**Comment by jamiesnape** [comment]
Cleaning up the scripts and setting up CI is not going to happen quickly, unfortunately, given priorities and current staffing.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Ks5W8qo8paVzm44m__P:beoi49f)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, simplifying the request to just some high-level comments, if possible.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5Vl2Aquj5cUjS0FAZ:b9qe7uz) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

They will be on CI eventually. The SHA is embedded in the filename.
</blockquote></details>

Could a comment be added describing the file name format? (Though partially obvious, it would be very helpful.)

Pending the build script, could a 3-5 line comment be added that indicates the main build flags used, with a link to the remote repository?

And could that be added as a `TODO`, to indicate that a Dockerfile or something will be made that can reproduce these images on another developer's machine?
(e.g. if they wish to switch it to a `new_local_repository`, they could have that option?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Ks5XFRRvVvB7wYEKKyK:b-wfx560)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5YBO4m6LrVwlnonM_:beispnn) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could a comment be added describing the file name format? (Though partially obvious, it would be very helpful.)

Pending the build script, could a 3-5 line comment be added that indicates the main build flags used, with a link to the remote repository?

And could that be added as a `TODO`, to indicate that a Dockerfile or something will be made that can reproduce these images on another developer's machine?
(e.g. if they wish to switch it to a `new_local_repository`, they could have that option?)
</blockquote></details>

There will be a job on CI that developers can request. Probably unlikely there will be a Docker image given we build binaries for Mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5dUPv_rwe3meGjTB1:brm5xql) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

There will be a job on CI that developers can request. Probably unlikely there will be a Docker image given we build binaries for Mac.
</blockquote></details>

Sounds good. Could that be added as a `TODO` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jamiesnape** [comment]
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5pDELGQifAuPVUEwo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Sounds good. Could that be added as a `TODO` here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/drake_visualizer.bzl, line 3 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-Ks5UPWNMDiPHu2YY4vU:-Ks5y623bhMTIbD2JoPe:b556ppi) ([raw file](https://github.com/robotlocomotion/drake/blob/7bfaf0c1220af26c58c5044a62d8b90799103cbe/tools/drake_visualizer.bzl#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843)*

**Comment by jamiesnape** [comment]
@soonho-tri Could you check the new mac binary? You will need to do a `brew update && brew upgrade vtk@8.0`.

**Comment by soonho-tri** [comment]
@jamiesnape , it works!

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6843#-:-Ks9QgrVphdwGCVF_Rt4:b9bxgpw)*

**Pull request merged**
