### PR TITLE
[doc] Update installation instruction for pip

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18443)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@mwoehlke-kitware for feature review please, thanks.

If the change is more nuanced than this, feel free to open a replacement PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18443#-:-NJ7qfRd1gAg65Hk0-Xq:b-rljvx2)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/pip.md` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18443#-NJB938j4ykjC2xRHKmZ:-NJB938j4ykjC2xRHKm_:bnn627r) ([raw file](https://github.com/robotlocomotion/drake/blob/7b65003748d525a3a53317e835730bed19e981d0/doc/_pages/pip.md#L75)):*
> ```Markdown
>

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18443)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

___
*[`doc/_pages/pip.md` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18443#-NJB938j4ykjC2xRHKmZ:-NJBYk-PDxIc7MtjMv4I:b3fh4ff) ([raw file](https://github.com/robotlocomotion/drake/blob/7b65003748d525a3a53317e835730bed19e981d0/doc/_pages/pip.md#L75)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

This ("point to INSTALLATION instead") seems to be missing?
</blockquote></details>

The line immediately below already points to the quick start section of installation. Is that enough?

**Comment by mwoehlke-kitware** [comment]
*[`doc/_pages/pip.md` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18443#-NJB938j4ykjC2xRHKmZ:-NJCMAda1UjybI9jieAR:b-vwpqhg) ([raw file](https://github.com/robotlocomotion/drake/blob/7b65003748d525a3a53317e835730bed19e981d0/doc/_pages/pip.md#L75)):*
No, because that is a webpage that can be out of sync with what is actually installed. That approach is in fact directly opposite the goal of #16383. To wit:

> At minimum, a text file with the list of packages to install for that version of Drake should be shipped as part of the wheel, rather the website documentation (we don't version the website). The documentation (and runtime failure message) can refer to that file.

The TO-DO here is not to simply remove this text. It is to point the user at the *installed* documentation (`INSTALLATION`) instead of a web page.

Besides, unless I am missing something, the information being removed isn't present in the quick start anyway? (Which I think is deliberate, considering the above.)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18443)* status: 1 unresolved discussion, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

___
*[`doc/_pages/pip.md` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18443#-NJB938j4ykjC2xRHKmZ:-NJCT8X-15bmvb5zSv9Y:bdx3v67) ([raw file](https://github.com/robotlocomotion/drake/blob/7b65003748d525a3a53317e835730bed19e981d0/doc/_pages/pip.md#L75)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

No, because that is a webpage that can be out of sync with what is actually installed. That approach is in fact directly opposite the goal of #16383. To wit:

> At minimum, a text file with the list of packages to install for that version of Drake should be shipped as part of the wheel, rather the website documentation (we don't version the website). The documentation (and runtime failure message) can refer to that file.

The TO-DO here is not to simply remove this text. It is to point the user at the *installed* documentation (`INSTALLATION`) instead of a web page.

Besides, unless I am missing something, the information being removed isn't present in the quick start anyway? (Which I think is deliberate, considering the above.)
</blockquote></details>

Ok, I clearly didn't understand the TODO well enough to finish it. I'll close this PR and defer to you for a proper resolution.

**Comment by jwnimmer-tri** [comment]
There is no such thing as INSTALLATION file anymore.  The call to action is only to delete step 2.  (Unlike r1 of this PR, we should keep step (3) for "activate".)  That's all that needs to happen.

**Pull request closed without merging**
