### PR TITLE
Add AutoDiff overload for math::saturate()

### PR DESCRIPTION
**Pull request by jadecastro**
Currently, authors are required to manage limits values of `math::saturate()` when the arguments passed in are of type `AutoDiffXd` and the return value is expected to have AutoDiffXd values that have derivatives of compatible dimension.  It would be helpful to have a convenient method for doing this in the special case where the limits are known to be constant values (e.g. in a System where the saturation bounds are not functions of Context values) and hence the derivatives can be correctly assigned as zeros.

For instance,
```
const double value = 0.5;
const T x(value, Vector1<double>{1});
const T y = saturate(x, T(0.), T(1.));
```
would result in `y.value(): 0.5` and `y.derivatives().size(): 1`, but setting `value = 2.` would result in `y.value(): 1` and `y.derivatives().size(): 0`.

The proposal allows one to specify `double`-valued limits and hence `const T y = saturate(x, 0., 1.);` would result in `y.derivatives().size(): 1`, `y.derivatives()(0): 0`. 

This solution is similar to Eigen's overloads for `std::min()` and `std::max()` (line 548 here: https://eigen.tuxfamily.org/dox/unsupported/AutoDiffScalar_8h_source.html), but this is intended to work also for dynamically-sized derivative containers (i.e. `AutoDiffXd` variables).

One alternative to this PR is to use a function like the following that creates the derivatives for AutoDiffXd variables:
```
AutoDiffXd InitializeWithPartials(double x, int num_zeroed_derivatives) {
  AutoDiffXd result(x);
  result.derivatives().resize(num_zeroed_derivatives);
  result.derivatives().setZero();
  return result;
}
double InitializeWithPartials(double x, int) {x};
```
which would allow us to do, for instance:
```
const T y = saturate(x, InitializeWithPartials(0., 1), InitializeWithPartials(1., 1));
``` 
I'm open to hearing other alternatives if we'd rather not pollute the source tree with more overloads.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6782)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
To my understanding, having a numeric double constant promote into an `AutoDiff` with an empty derivatives vector is entirely normal and expected, and does not defeat the differentiation pipeline in any way.  The link in the description above only shows a request to pull some code into its own PR; it does not justfity why `saturate` is a special case versus all other `AutoDiff` arithmetic related to constants in the source tree.

**Comment by jadecastro** [comment]
(comment updated, links removed)

**Comment by jwnimmer-tri** [comment]
The fundamental premise still seems flawed to me.  It's not the `saturate` that's in question, its the low and high arguments passed to saturate, right?  It seems to be like developers should be able to say `T{3.14}` and get a valid scalar with derivatives implied to be zero.  The entire systems framework, primitives library, and integrator toolbox assume that passing a `double` into `T::T(double)` produces a valid scalar.  Why should `saturate` be any different?

**Comment by jadecastro** [comment]
Right, but when you do something like `T{3.14}`, when `T = AutoDiffXd` and then poll the derivatives, the derivative vector not zero; it is empty.  It's not a problem specific to `saturate()` at all. I suppose the alternative would be a type-specific function (like `InitializeWithPartials()` above) that fills in the zeros to be of the same dimension as the un-saturated value?  I expect I would have to do this at several call sites of `saturate()`, hence the reason for the proposed sugar.

**Comment by jwnimmer-tri** [comment]
The problem is with whoever is calling `.derivatives()` and assuming it is non-empty.

**Comment by jadecastro** [comment]
Alright, I'll close this PR and I'll leave it to the caller to resize any zeroed derivatives for the constants. Thanks.

**Pull request closed without merging**
