### PR TITLE
[setup] Upgrade sanitizer builds to clang-14 on Ubuntu

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #19030.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please.
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-thread-sanitizer please.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19064#-NRYpgYR16UO3C5VPdV-:-NRYpgYR16UO3C5VPdV0:buj6kij) (no related file):*
I think `valgrind.sh` also will need a similar update?  For reference, #16937 updated to clang-12.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @BetsyMcPhail)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19064#-NRYpgYR16UO3C5VPdV-:-NRYrHfg9ovqDCZ_9aiD:btzza0a) (no related file):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I think `valgrind.sh` also will need a similar update?  For reference, #16937 updated to clang-12.
</blockquote></details>

Done.

Note however that it's not the cause of (most of) the valgrind errors in the CI job -- at least as best I can tell.

___

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by BetsyMcPhail — COMMENTED** [review]
Links to successful jobs:

https://drake-jenkins.csail.mit.edu/view/AddressSanitizer/job/linux-jammy-clang-bazel-experimental-everything-address-sanitizer/2/
https://drake-jenkins.csail.mit.edu/view/LeakSanitizer/job/linux-jammy-clang-bazel-experimental-everything-leak-sanitizer/3/
https://drake-jenkins.csail.mit.edu/view/UndefinedBehaviorSanitizer/job/linux-jammy-clang-bazel-experimental-everything-undefined-behavior-sanitizer/3/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064#-:-NRYsdnV3_lTKAT9q7MY:bj281zm)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer

**Comment by jwnimmer-tri** [comment]
I think probably Memcheck will need its own separate PR.  Whether or not the experimental build passes, I think we should still merge this PR as long as the result isn't _worse_ than what's on master.

+@rpoyner-tri for both reviews, please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by BetsyMcPhail — COMMENTED** [review]
I confirmed that this reduces the number of tsan failures. The jammy provisioned image has been updated in Jenkins, so this PR does not have to wait for any CI updates.

:lgtm:

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064#-:-NRZ3mWf94XHffbhbs7i:b-48hxdo)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19064#-:-NRZjqyR3IplTHTUeDVF:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),BetsyMcPhail (waiting on @jwnimmer-tri)

**Pull request merged**
