### PR TITLE
[workspace] Bump pybind11 fork to latest commit

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Incorporates https://github.com/RobotLocomotion/pybind11/pull/57

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16140)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for both reviews, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16140#-:-MqH5nMHAnlEid_AK1-5:b-3q8wnk)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Valgrind CI failed.
:lgtm: x 2 assuming that's addressed

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16140#-:-MqHBGjC5WFP2LK-nU_B:bivoym)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Thanks! And sorry; valgrind failure was b/c it's not yet supported (I didn't check first :facepalm:)

Will do Bionic valgrind now, though (it won't clear that failed build, but it will all be re-done once upstream fork PR is merged)
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by EricCousineau-TRI** [comment]
Above link for valgrind passed; just letting CI redux run, and will then merge - thanks!

**Comment by EricCousineau-TRI** [comment]
:facepalm: Forgot to test on Anzu. Whelp, :crossed_fingers:

**Comment by EricCousineau-TRI** [comment]
Anzu CI passed

**Pull request merged**
