### PR TITLE
[geometry/render_gltf_client] Add glTF integration test

### LINKED ISSUE #17786: RenderRpc: glTF verification test(s) for vtkGLTFExporter
Unit testing the SceneGraph-to-glTF creation by comparing it with a pre-generated "ground truth" glTF file.

### PR DESCRIPTION
**Pull request by zachfang**
Close #17786

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)

### CODE REVIEW

**Comment by zachfang** [comment]
@jwnimmer-tri This is the skeleton for the glTF test I am working on. Two implementation details I would like to have your input. 

- As discussed, we will compare the generated glTF files with ground truth. However, the size of the glTFs can be large (14 or 3 MB depending on the image type), and my understanding is we only commit small files into Drake. Is the alternative to store them in an external repo or storage space?
- My current thought is to get one glTF file for each image type since they are not identical, e.g., depth and label glTFs don't have `textures` and `images` keys. By doing that, we will have three standard glTFs instead of one, and I wonder if this is too excessive.

Thanks!

**Comment by jwnimmer-tri** [comment]
(1) We already talked about doing a fuzzy (non-exact) comparison of the GLTF trees.  Under that premise, the "goal" files could have a placeholder node for the image instead of the full image data, and the test would use fuzzy-compare for that node.

(2) I can't really say in the hypothetical.  Push your best guess in to the PR and then we can discuss.

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-release please

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-m1-monterey-provisioned-clang-bazel-experimental-release please

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NF2Xxp52K1I4B6aQwMs:b-aqwq0s)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)* status: 8 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4IahK-HesjFQY3tW-:-NF4IahK-HesjFQY3tW0:b-bk4htw) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L59)):*
> ```Python
>         while self.server_port is None:
>             line = self.server_proc.stdout.readline().decode("utf-8")
>             print(f"[server] {line}", file=sys.stderr)
> ```

nit Not new in this PR, but we've ended up with duplicated newlines here.



_Suggestion:_
```Python
print(f"[server] {line}", file=sys.stderr, end='')
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4EUroB9f5DWKwNqzV:-NF4EUroB9f5DWKwNqzW:bo7n61p) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L95)):*
> ```Python
>         return result
> 
>     def get_demo_images(self, renderer):
> ```

nit Consider if a slightly longer name would end up being more clear.



_Suggestion:_
```Python
get_demo_image_paths
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4EZL_3n0LHye5izf1:-NF4EZL_3n0LHye5izf2:b-v2ofjh) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L112)):*
> ```Python
>         return image_sets
> 
>     def get_gltf_files(self, save_dir):
> ```

nit Consider ...



_Suggestion:_
```Python
get_gltf_paths
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4Fspx8xtp5rvr6flB:-NF4Fspx8xtp5rvr6flC:bde5r3i) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L112)):*
> ```Python
>         return image_sets
> 
>     def get_gltf_files(self, save_dir):
> ```

The `save_dir` here is misleading.  Elsewhere we use `save_dir` to refer to the render-specific output directory for images within `tmp_dir`.  Here, it's something else (not necessarily within `tmp_dir`).

I suggest naming this arg `gltf_file_dir` to match its call sites.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4FAOJ3-bYDT2DaY6X:-NF4FAOJ3-bYDT2DaY6Y:b-bevaqj) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L174)):*
> ```Python
>         the test's scope and is covered in the integration test above.
>         """
>         result = self.run_render_client("client", False)
> ```

nit Magic "False" unclear when used without a name.



_Suggestion:_
```Python
cleanup=False
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 197 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4GHoN8sCdidhandfY:-NF4GHoN8sCdidhandfZ:bv008by) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L197)):*
> ```Python
>             ground_truth_gltf = json.load(gt)
> 
>             for gltf_file in gltf_files:
> ```

The `for` loop doesn't need to be nested within the `with`; we can close the file before starting to loop.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4Ga4_A_edvhUAQ8lP:-NF4Ga4_A_edvhUAQ8lQ:b539flu) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L201)):*
> ```Python
>                     gltf = json.load(f)
> 
>                     # These entries define the basic hierarchical structure of
> ```

The checking doesn't need to be nested within the second `with`; we can close the file before starting to compare.

Once both of the redundant nestings are fixed, we'll have a lot more room to reflow the comments and such so they are so smooshed.

In fact, I think the test can be much more clear (in both source code and runtime output) if the per-gltf comparison was a helper function.  It would look like this:

```py
        ...
        # Iterate through each gltf file to compare against the ground truth.
        with open(ground_truth_gltf_file, "r") as gt:
            ground_truth_gltf = json.load(gt)
        for gltf_file in self.get_gltf_files(gltf_file_dir):
            is_color_image = "color.gltf" in gltf_file
            with open(gltf_file, "r") as f:
                gltf = json.load(f)
            with self.subTest(gltf_file=os.path.basename(gltf_file)):
                self._check_one_gltf(gltf, ground_truth_gltf, is_color_image)

    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        # These entries define the basic hierarchical structure of a glTF,
        # the poses of the included geometries, and the camera properties
        # (intrinsics and extrinsics).
        for entry in [
            ...
```
___
*[`geometry/render_gltf_client/test/integration_test.py` line 212 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4J_KT2HW4cYv3fbEC:-NF4J_KT2HW4cYv3fbED:b23rpw7) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L212)):*
> ```Python
>                         "asset",
>                     ]:
>                         self.assertEqual(gltf[entry], ground_truth_gltf[entry])
> ```

One property we need for this test case is that _everything_ in the file is either compared for correctness (is under test) or is _explicitly_ ignored by the test code (so that someone reading the test knows what is _not_ under test and so that newly-added fields to the gltf data will show up).  By listing out _only_ the fields that will be tested, and leaving the untested fields implicit, we've failed to meet that bar.

There a bunch of ways to implement logic like that.  The one I like most is to have a helper function that fuzzes away the "don't care" data.  That is, a function that is given a gltf tree and returns a copy of it while replacing any don't-care nodes with a placeholder, e.g., `"IGNORED"`.  Then we'll call it with the under-test gltf as well as the ground_truth_gltf each in turn.  Then we can assert that two the fuzzed trees are _exactly_ equal.

Something like this:

```py
    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        actual = self._fuzz_irrelevant_data(gltf_file, gltf)
        expected = self._fuzz_irrelevant_data(gltf_file, ground_truth_gltf)
        self.assertDictEqual(expected, actual)

    def _fuzz_irrlevant_data(self, gltf, is_color_image):
        ...
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4DWnY0YS_HRjtKNHM:-NF4DWnZ3g8ajMbvJTYi:bv0hzj2) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L93)):*
> ```Python
>             encoding="utf-8",
>         )
>         return result
> ```

In case the client fails, it's very important that we dump its error message back to the test console so that we have any hope of debugging errors in CI.

```patch
--- a/geometry/render_gltf_client/test/integration_test.py
+++ b/geometry/render_gltf_client/test/integration_test.py
@@ -85,11 +85,14 @@ class TestIntegration(unittest.TestCase):
         ]
         result = subprocess.run(
             render_args,
-            check=True,
             stdout=subprocess.PIPE,
             stderr=subprocess.STDOUT,
             encoding="utf-8",
         )
+        if result.returncode != 0:
+            for line in result.stdout.splitlines():
+                print(f"[client] {line}", file=sys.stderr)
+        result.check_returncode()
         return result
 
     def get_demo_images(self, renderer):
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 212 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4J_KT2HW4cYv3fbEC:-NF4Ng9HAQxNyUFLlb85:bgh61dt) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One property we need for this test case is that _everything_ in the file is either compared for correctness (is under test) or is _explicitly_ ignored by the test code (so that someone reading the test knows what is _not_ under test and so that newly-added fields to the gltf data will show up).  By listing out _only_ the fields that will be tested, and leaving the untested fields implicit, we've failed to meet that bar.

There a bunch of ways to implement logic like that.  The one I like most is to have a helper function that fuzzes away the "don't care" data.  That is, a function that is given a gltf tree and returns a copy of it while replacing any don't-care nodes with a placeholder, e.g., `"IGNORED"`.  Then we'll call it with the under-test gltf as well as the ground_truth_gltf each in turn.  Then we can assert that two the fuzzed trees are _exactly_ equal.

Something like this:

```py
    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        actual = self._fuzz_irrelevant_data(gltf_file, gltf)
        expected = self._fuzz_irrelevant_data(gltf_file, ground_truth_gltf)
        self.assertDictEqual(expected, actual)

    def _fuzz_irrlevant_data(self, gltf, is_color_image):
        ...
```
</blockquote></details>

Oops, that suggestion was halfway between my pivot from passing the filename vs passing the is_color.  Here's an updated outline:

```py
    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        actual = self._fuzz_irrelevant_data(gltf, is_color_image)
        expected = self._fuzz_irrelevant_data(ground_truth_gltf, is_color_image)
        self.assertDictEqual(expected, actual)

    def _fuzz_irrlevant_data(self, gltf, is_color_image):
        result = copy.deepcopy(gltf)
        ...
        return result
```

**Review by zachfang — COMMENTED** [review]
Thanks for the review; all the comments are addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NF5yuyP8RGtM1g0Gex9:b34j24w)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`geometry/render_gltf_client/test/integration_test.py` line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4DWnY0YS_HRjtKNHM:-NF5UNzN7Yfni7GhU9cI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L93)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

In case the client fails, it's very important that we dump its error message back to the test console so that we have any hope of debugging errors in CI.

```patch
--- a/geometry/render_gltf_client/test/integration_test.py
+++ b/geometry/render_gltf_client/test/integration_test.py
@@ -85,11 +85,14 @@ class TestIntegration(unittest.TestCase):
         ]
         result = subprocess.run(
             render_args,
-            check=True,
             stdout=subprocess.PIPE,
             stderr=subprocess.STDOUT,
             encoding="utf-8",
         )
+        if result.returncode != 0:
+            for line in result.stdout.splitlines():
+                print(f"[client] {line}", file=sys.stderr)
+        result.check_returncode()
         return result
 
     def get_demo_images(self, renderer):
```
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4Fspx8xtp5rvr6flB:-NF5URMq2c26cpDWoA5f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `save_dir` here is misleading.  Elsewhere we use `save_dir` to refer to the render-specific output directory for images within `tmp_dir`.  Here, it's something else (not necessarily within `tmp_dir`).

I suggest naming this arg `gltf_file_dir` to match its call sites.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 197 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4GHoN8sCdidhandfY:-NF5UT9-3S8FgcEv4cuv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L197)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `for` loop doesn't need to be nested within the `with`; we can close the file before starting to loop.
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4Ga4_A_edvhUAQ8lP:-NF5UURoEYTD1Afuehpf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The checking doesn't need to be nested within the second `with`; we can close the file before starting to compare.

Once both of the redundant nestings are fixed, we'll have a lot more room to reflow the comments and such so they are so smooshed.

In fact, I think the test can be much more clear (in both source code and runtime output) if the per-gltf comparison was a helper function.  It would look like this:

```py
        ...
        # Iterate through each gltf file to compare against the ground truth.
        with open(ground_truth_gltf_file, "r") as gt:
            ground_truth_gltf = json.load(gt)
        for gltf_file in self.get_gltf_files(gltf_file_dir):
            is_color_image = "color.gltf" in gltf_file
            with open(gltf_file, "r") as f:
                gltf = json.load(f)
            with self.subTest(gltf_file=os.path.basename(gltf_file)):
                self._check_one_gltf(gltf, ground_truth_gltf, is_color_image)

    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        # These entries define the basic hierarchical structure of a glTF,
        # the poses of the included geometries, and the camera properties
        # (intrinsics and extrinsics).
        for entry in [
            ...
```
</blockquote></details>

Done.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 212 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NF4J_KT2HW4cYv3fbEC:-NF5ysiX50J6V8f0WgH_:b-qsvnoa) ([raw file](https://github.com/robotlocomotion/drake/blob/c04122f37b5977f0edba5a6727564ea29dbdc475/geometry/render_gltf_client/test/integration_test.py#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, that suggestion was halfway between my pivot from passing the filename vs passing the is_color.  Here's an updated outline:

```py
    def _check_one_gltf(self, gltf, ground_truth_gltf, is_color_image):
        actual = self._fuzz_irrelevant_data(gltf, is_color_image)
        expected = self._fuzz_irrelevant_data(ground_truth_gltf, is_color_image)
        self.assertDictEqual(expected, actual)

    def _fuzz_irrlevant_data(self, gltf, is_color_image):
        result = copy.deepcopy(gltf)
        ...
        return result
```
</blockquote></details>

Done. PTAL.

**Review by jwnimmer-tri — COMMENTED** [review]
The testing framework looks good now.  The remaining question for feature review is whether the ground truth gltf file is actually the correct answer for the input scene.  I don't know very much at all about gltf on its own.  Do you have any tips for how a reviewer can know that the file is a gold standard?  How did you convince yourself that its correct?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NF6JGFQ-YhN8lCGV-H6:bbzh8u3)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
It's probably not perfect, but this is my best answer.

Two resources I found most useful are:
(1) [glTF-Tutorials](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_002_BasicGltfStructure.md)
(2) [Property Reference](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#properties-reference)

I follow the hierarchy of a glTF file, examining each section and then its child sections.

These are the breakdown and what I have checked.

`scene` is the entry point, and the array of `scenes` specifies how many nodes the scene contains. In our case, we should have 13 nodes, i.e., 11 meshes, a camera node, and a summarized node the scene points to.

The `nodes` section specifies the index of the mesh for each node and its GLOBAL transformation. I verified the transformations with the SDFormat file. Additionally, I removed some meshes in the SDFormat file and ensured the corresponding nodes in the glTF file disappeared as they should be. The order in the section is backward from the SDFformat file, except for the mustard bottle.

The `cameras` section contains the CameraInfo, which matches the values we set in the `client_demo.cc`.

The `meshes` section declares the information of the mesh vertices via `attributes.POSITION`(vertice 3D position), `attributes.TEXCOORD_0` (texture coordinate), and `indices` (vertice indices). They all point to `accessors` indicating how to interpret the data. Note that `mesh6` and `mesh7` don't have `TEXCOORD_0`. Those meshes are the capsules, and I believe it's related to Sean's comment.
```
// NOTE: Apparently, we don't have texture coordinates for capsules.
```

The `materials` section specifies the base RGBA color and the index of the texture if applicable. Its children, i.e., `textures`, and `images`, contain indices that point to different `accessors` (and then `buffers` for the actual raw data). `samplers` section is for filtering and wrapping properties which all seem reasonable (LINEAR, CLAMP_TO_EDGE).

`accessors` is the most difficult to interpret. However, from a high-level sense, the type is correct (VEC3 for vertice positions, VEC2 for texture coordinates, and SCALAR for vertice indices). Each accessor points to a `bufferView`; in our simple case, the `byteOffset` is always zero. The missing bufferView indices, e.g., 3 and 10, are pointed by texture images.

I think the above covers all the sections in the golden glTF file.

The only two things I haven't figured out are the transformations of the camera and the mustard bottle. The y and z axis is flipped from the RigidTransform we specified in `client_demo`. I suspect the camera coordinate is defined differently in VTK.

I tried to query the world-to-mustard TF in Drake, and I think, somehow, the transformation is referring to another link or body.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NFy5FyuE0ANAjqj2CRY:b-vxlwol)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
FYI I think the remaining work here is:

(1) Finish the investigation into the camera and mustard bottle transforms.  Looking into json on paper is useful, but you could also just do cross-checking -- if you load the golden file into each of Godot and Blender and the scene looks correct in their UIs, that's good evidence that the data is correct, even if you can't quite read the json by hand.

(2) As part of the PR's code (documentation) in git, explain to the _next_ developer how to deal with test failures.  If the test starts failing, how should they know whether the render client has a bug that needs fixing, versus that the golden-file needs to change because it was actually wrong (or incomplete)?  You explanation text above is basically that information, but we can put a different spin on it by imagining the "future developer" as the intended audience.

**Comment by zachfang** [comment]
Re (1):  I got to the bottom of the issue.
-  Drake and glTF have different local camera coordinate systems, and that causes the y and z axis to be 180 degrees off.
-  The transformation of the mustard bottle is X_WMustard * X_MustardVisual.

In terms of a high-level visual inspection for the glTF file, I loaded the glTF file (non-stripped version) to Blender and compared the scene side-by-side. The different color of the capsules is due to the `no texture coordinate` issue, and the color becomes renderer-dependant.
Screenshot from 2022-11-08 21-30-32

Re (2): I added a new section in the README file covering the overall testing structure. Inside the section, I put some paragraphs explaining both integration tests. Let me know what you think!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

+@sammy-tri for platform review per schedule, please.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NGXDRYd0RL797tM_QH7:b-zfiiwp)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDVe0Euk2Y65C_IOc:-NGXDVe0Euk2Y65C_IOd:b-d76hvw) (no related file):*
> In terms of a high-level visual inspection for the glTF file, I loaded the glTF file (non-stripped version) to Blender and compared the scene side-by-side. The different color of the capsules is due to the no texture coordinate issue, and the color becomes renderer-dependant.

Is there an issue opened for that yet?

___
___
*[`geometry/render_gltf_client/test/example_scene.sdf` line 133 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDFBw7CP2RgemHHcD:-NGXDFBxCFayVhJr8qph:b-3uye66) ([raw file](https://github.com/robotlocomotion/drake/blob/eb5228a98c8a218d6d4d309f4c6b8a37eabfcd15/geometry/render_gltf_client/test/example_scene.sdf#L133)):*
> ```
>         <geometry>
>           <sphere>
>             <radius>0.05 0.025 0.0375</radius>
> ```

Wow!  FYI the higher-dimensional sphere here made me think of https://en.wikipedia.org/wiki/Time_Cube.
___
*[`geometry/render_gltf_client/test/integration_test.py` line 160 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDx7BDMNUOGm6Ky1s:-NGXDx7BDMNUOGm6Ky1t:b-9q0app) ([raw file](https://github.com/robotlocomotion/drake/blob/d7fdc3f36d2513486d6f0c839a13b251867d19c5/geometry/render_gltf_client/test/integration_test.py#L160)):*
> ```Python
>             ground_truth_gltf, is_color_image
>         )
>         self.assertDictEqual(expected, actual)
> ```

nit I think this `DictEqual` is what would trigger in case of a gltf comparison failure in CI.  Right here nearby we should have a comment pointing the developer at either the README, or the file-level docstring.  I don't think they would necessarily think to read the file-level docstring on their own.

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDVe0Euk2Y65C_IOc:-NGXmYXkANRypT30sPLZ:b7u5cgs) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> In terms of a high-level visual inspection for the glTF file, I loaded the glTF file (non-stripped version) to Blender and compared the scene side-by-side. The different color of the capsules is due to the no texture coordinate issue, and the color becomes renderer-dependant.

Is there an issue opened for that yet?
</blockquote></details>

https://github.com/RobotLocomotion/drake/issues/18296 has been created, but I am not sure if it's in the right category.

___
___
*[`geometry/render_gltf_client/test/example_scene.sdf` line 133 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDFBw7CP2RgemHHcD:-NGXmQfZEy0NmLfZJu64:bcoppek) ([raw file](https://github.com/robotlocomotion/drake/blob/eb5228a98c8a218d6d4d309f4c6b8a37eabfcd15/geometry/render_gltf_client/test/example_scene.sdf#L133)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Wow!  FYI the higher-dimensional sphere here made me think of https://en.wikipedia.org/wiki/Time_Cube.
</blockquote></details>

:exploding_head: 
___
*[`geometry/render_gltf_client/test/integration_test.py` line 160 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18126#-NGXDx7BDMNUOGm6Ky1s:-NGXmPM82ZkBNlzVHepe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7fdc3f36d2513486d6f0c839a13b251867d19c5/geometry/render_gltf_client/test/integration_test.py#L160)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think this `DictEqual` is what would trigger in case of a gltf comparison failure in CI.  Right here nearby we should have a comment pointing the developer at either the README, or the file-level docstring.  I don't think they would necessarily think to read the file-level docstring on their own.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by zachfang — COMMENTED** [review]
With the updated README, I don't have any documentation-related tasks planned. Do you think #16750 can also be closed by this PR?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NGXuyvI6richeDZ1LXf:b-xylmiw)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
> Do you think https://github.com/RobotLocomotion/drake/issues/16750 can also be closed by this PR?

Yes, sure.  I think the protocol still isn't _correct_ (cf the magic label image snafu), but the documentation covers the implementation such as we have today.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NGXxLBm-ciOTX9BoYWK:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18126#-:-NGXxPyL6IfR34EwXXPQ:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @zachfang)

**Pull request merged**
