### PR TITLE
Python bindings for a few simulator/integrator controls

### PR DESCRIPTION
**Pull request by gizatt**
Exposes a little more control of the simulator in Python -- e.g., encouraging longer timesteps or fixed step mode to speed up simulations when accuracy isn't critical.

@EricCousineau-TRI, would you mind taking a look once I see that this works with CI?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8226)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending some discussion items.

+@sherm1 for platform review please.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-L6bs3aINXylqT7nKbvx:-L6bs3aINXylqT7nKbvy:bghnrxs) ([raw file](https://github.com/robotlocomotion/drake/blob/5e5c735bf72ceee7aa0fc645130453ca8efca60d/bindings/pydrake/systems/analysis_py.cc#L48)):*
> ```cpp
>     .def("StepTo", &Simulator<T>::StepTo)
>     .def("get_context", &Simulator<T>::get_context, py_reference_internal)
>     .def("get_integrator", &Simulator<T>::get_integrator, py_reference_internal)
> ```

Can you group `get_integrator` and `get_mutable_integrator` together here?

---

*[bindings/pydrake/systems/test/general_test.py, line 174 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-L6brq3jFBoXWgQQoCBN:-L6brq3jFBoXWgQQoCBO:blct94z) ([raw file](https://github.com/robotlocomotion/drake/blob/5e5c735bf72ceee7aa0fc645130453ca8efca60d/bindings/pydrake/systems/test/general_test.py#L174)):*
> ```Python
> 
>         const_integrator = simulator.get_integrator()
>         self.assertRaises(const_integrator.set_fixed_step_mode(True))
> ```

Er... Pardon my naivete, but how does this currently throw?
I haven't instrumented anything to be `const`-sensitive just yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-:-L6bs7qRxAxpH5YFfhsF:bi00clx)*

**Comment by gizatt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-L6bs3aINXylqT7nKbvx:-L6bu4wMwoFiDBwzTG0I:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5e5c735bf72ceee7aa0fc645130453ca8efca60d/bindings/pydrake/systems/analysis_py.cc#L48)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you group `get_integrator` and `get_mutable_integrator` together here?
</blockquote></details>

Done

---

*[bindings/pydrake/systems/test/general_test.py, line 174 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-L6brq3jFBoXWgQQoCBN:-L6buJAePO3eNguYvpqK:b-nlc7zi) ([raw file](https://github.com/robotlocomotion/drake/blob/5e5c735bf72ceee7aa0fc645130453ca8efca60d/bindings/pydrake/systems/test/general_test.py#L174)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Er... Pardon my naivete, but how does this currently throw?
I haven't instrumented anything to be `const`-sensitive just yet.
</blockquote></details>

Ooh, good point. I don't think I was even invoking assertRaises correctly, as this was passing the test anyway. Removed this line. Turns out I've been using the (secretly const) integrator reference to alter the integrator parameters in my python work anyway... oops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8226)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/general_test.py, line 174 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226#-L6brq3jFBoXWgQQoCBN:-L6c-sUWB1AyLeY48g9R:b-8kzypn) ([raw file](https://github.com/robotlocomotion/drake/blob/5e5c735bf72ceee7aa0fc645130453ca8efca60d/bindings/pydrake/systems/test/general_test.py#L174)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Ooh, good point. I don't think I was even invoking assertRaises correctly, as this was passing the test anyway. Removed this line. Turns out I've been using the (secretly const) integrator reference to alter the integrator parameters in my python work anyway... oops.
</blockquote></details>

OK No worries! I have some code that just needs to be stitched together to make it an (optional) error when that happens, which will be more important once caching comes online.

---

*[bindings/pydrake/systems/test/general_test.py, line 173 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226#-L6c03IpCMKdh5X4RMAF:-L6c03Iq69MhQihvWyWu:b-9nbevd) ([raw file](https://github.com/robotlocomotion/drake/blob/f1eed3afba448a6687b78e5fd67d0269409e0b77/bindings/pydrake/systems/test/general_test.py#L173)):*
> ```Python
>         self.assertTrue(integrator.get_fixed_step_mode())
> 
>         const_integrator = simulator.get_integrator()
> ```

BTW Can still add a test like `self.assertTrue(const_integrator is integrator)`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226)*

**Comment by gizatt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/test/general_test.py, line 173 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226#-L6c03IpCMKdh5X4RMAF:-L6c0X3p2RbeGM1mYacT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f1eed3afba448a6687b78e5fd67d0269409e0b77/bindings/pydrake/systems/test/general_test.py#L173)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can still add a test like `self.assertTrue(const_integrator is integrator)`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226#-:-L6cH2sAATjIDrr75Nv3:bnfp4nl)*

**Comment by sherm1** [comment]
Just needs a squash-merge now, @gizatt. Please edit the squashed commit comment for clarity.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8226#-:-L6cHA_y8oIHEBCLFgxt:bj9v8gu)*

**Comment by gizatt** [comment]
Will do, thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8226#-:-L6cIR6htE5bXu3diRn4:b9ba0xc)*

**Pull request merged**
