### PR TITLE
Add visualization for trajectory cars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This integrates BotViz2 into automotive.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3602)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by rpoyner-tri** [comment]
I'll bite. +@rpoyner-tri if i may.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KShCOEt4bTiF55RluTu:btutwmw)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KShGLI7mhewBNe7sFw3:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KShGktDRFj-59ee7wU5:bdph6cr)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KShL3qW-dl9LyfCyFz5:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShNyaBa-WudV-6_UQT:-KShNyaBa-WudV-6_UQU:b2o3an0) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L27)):*
> ```cpp
> 
> namespace {
> // Iterate over a collection, passing both the index and value to a functor.
> ```

Why not just use `std::for_each`?

---

*[drake/automotive/automotive_simulator.cc, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShP6zFk7_--3Nk198N:-KShP6zGhrp4zpVtg8rT:bgq9ldn) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L190)):*
> ```cpp
>   DRAKE_DEMAND(!started_);
> 
>   if (!rigid_body_tree_publisher_inputs_.empty()) {
> ```

Does RigidBodyTree guarantee the order of the bodies matches up in the way you want here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by david-german-tri** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShNyaBa-WudV-6_UQT:-KShVTrzDVDhpJ1e_KrQ:bnfoz4v) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why not just use `std::for_each`?
</details>
I can't think of a way to use for_each (or range-for) that produces both the index and the element?

---

*[drake/automotive/automotive_simulator.cc, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShP6zFk7_--3Nk198N:-KShVoCeAo8DlOmAD-xM:b-7oh1l0) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L190)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Does RigidBodyTree guarantee the order of the bodies matches up in the way you want here?
</details>
I thought it did, but I also see now that I could rework this to add assertions to that effect.  New push on its way in a little while with that improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShNyaBa-WudV-6_UQT:-KShWzxCfF2WLSTOkerl:byg86dj) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I can't think of a way to use for_each (or range-for) that produces both the index and the element?
</details>
OK, I guess all the ways to capture the index are about as bulky as this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_simulator.cc, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShNyaBa-WudV-6_UQT:-KShXwwASyP2J2_GL0Ts:by23g9c) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK, I guess all the ways to capture the index are about as bulky as this.
</details>
I may eventually promote this to common, with better documentation and examples.  It should help convert many for-int loops to for-range loops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KShP6zFk7_--3Nk198N:-KShgOI8dYz3kxHI5r4n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fbe1463507eae02c36cec05e85a5d9209e011e6/drake/automotive/automotive_simulator.cc#L190)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I thought it did, but I also see now that I could rework this to add assertions to that effect.  New push on its way in a little while with that improvement.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KShgPejITLNkDZJJmFY:b-83330m)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by jwnimmer-tri** [comment]
Jenkins was a matlab flake `Unrecognized MATLAB option "wait".`  We can override-merge pending review completion. @david-german-tri PTAL?

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri PTAL?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 97 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-KSr6qsDxuZ6kP7x1aIa:-KSr6qsDxuZ6kP7x1aIb:b-gip6as) ([raw file](https://github.com/robotlocomotion/drake/blob/c75bcc760ad062913bf16da331989a3fc1c6010a/drake/automotive/automotive_simulator.cc#L97)):*
> ```cpp
>       parsers::urdf::AddModelInstanceFromUrdfFile(
>           urdf_filename, rigid_body_tree_.get());
>   DRAKE_DEMAND(table.size() == 1);
> ```

BTW, consider adding some comment narrative about why these assertions are true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3602#-:-KSr6v_wovaqSL8KnokD:bnfp4nl)*

**Pull request merged**
