### PR TITLE
 Fix Python binding for LeafSystems::DeclareAbstractOutputPort().

### PR DESCRIPTION
**Pull request by mitiguy**
PR #21478 resolves issue #18768

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 
Platform review +@jwnimmer-tri   (for both reviews). 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-:-NycDIur-Yx-vtLCn0s4:bss856a)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-Nyf5XtHEauy-vVzI203:-Nyf5XtHEauy-vVzI204:b-shfoj2) (no related file):*
When a C++ argument name and Python argument name accidentally disagree, we have four options for fixing it:
- rename the Python argument to match the C++ argument, or
- rename the C++ argument to match the Python argument, or
- rename both arguments to a new name (when neither existing name was good), or
- remove the C++ argument name from the declaration (when the argument's meaning is clear from the type alone).

Could you please explain your thought process for why the first option is the best choice in this case?  I wasn't able to follow along, yet.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-Nyf5YQt9CL7nESq3tWI:-Nyf5YQt9CL7nESq3tWJ:b-5dnyip) (no related file):*
The issue #21478 has two calls to action:
(1) Fix this specific argument name mismatch.
(2) Look for other mismatches nearby and fix those also.

This PR is set up to close the issue, so let me double-check: have you looked for other mismatches nearby, and nothing else was wrong?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-Nyf5XtHEauy-vVzI203:-Nz15BbaD7XRLiV7Xsc6:bheu16a) (no related file):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

The relevant function arguments that differed in Python bindings vs C++ are "alloc" vs. "alloc_function" and "calc" vs. "calc_function".  I discussed this with Rico briefly last Wednesday and he said one way was to rename the Python argument to match the C++ argument.  I talked to Hongkai briefly today and he regarded changing the C++ argument names as easier to avoid deprecation.

I chose a path forward for this PR, namely to rename the Python argument to match the C++ argument.  My decision was shaped 
 by the inconsistency of the use of the argument "alloc", "allocate" and "allocate_function".  I regard "allocate" as a generic C++ word and "alloc" as a poor abbreviation whereas "allocate_function" more explicitly communicates the argument's purpose.

You have a better top-level view than me on this.
I would like to proceed as you deem best. Let me know.

Here is some of the data that I used in my decision.

The relevant function is declared/defined in leaf_system.h and leaf_system.cc as:
```
   LeafOutputPort<T>& LeafSystem<T>::DeclareAbstractOutputPort(
    std::variant<std::string, UseDefaultName> name,
    typename LeafOutputPort<T>::AllocCallback alloc_function,
    typename LeafOutputPort<T>::CalcCallback calc_function,
    std::set<DependencyTicket> prerequisites_of_calc) 
```

A similar function is declared/defined in physical_model.h and physical_model.cc as:
```
    systems::LeafOutputPort<T>& PhysicalModel<T>::DeclareAbstractOutputPort(
    std::string name,
    typename systems::LeafOutputPort<T>::AllocCallback alloc_function,
    typename systems::LeafOutputPort<T>::CalcCallback calc_function,
    std::set<systems::DependencyTicket> prerequisites_of_calc);
```

A similar function is declared/defined in multibody_plant_model_attorney.h as:
```
     systems::LeafOutputPort<T>& DeclareAbstractOutputPort(
      MultibodyPlant<T>* plant, std::string name,
      typename systems::LeafOutputPort<T>::AllocCallback alloc_function,
      typename systems::LeafOutputPort<T>::CalcCallback calc_function,
      std::set<systems::DependencyTicket> prerequisites_of_calc;
```
Note: There are approximately 30 uses of the name AllocCallback in Drake, with the ones above using "alloc_function" whereas Pydrake uses "alloc". There are approximately 33 uses of the name CalcCallback in Drake with the ones above using "calc_function" as well as others, e.g., in witness_function.h
  
  ```
   // The witness function calculator function pointer.
  const CalcCallback calc_function_;
```

The files value_producer.h and value_producer.cc uses "allocate" (NOT "alloc") and "calc", e.g., as
 ``` 
  AllocateCallback allocate_;
  CalcCallback calc_;
```
as does the ValueProducer py::arg("allocate") and py::arg("calc") in framework_py_semantics.cc

I like consistency and explicit.  So, left to me, I would probably redo nearly all of these more consistently e.g., as "alloc_function" and "calc_function".
</blockquote></details>

For myself, I would weigh the options like this:

(1) Cost:
* Renaming the Python side forces our users to edit their code that was already working just fine.  This is one of the worst costs we can imagine, second only to "computed incorrect results".
* Renaming the C++ side is extremely easy and does not affect users.  It should take about 5 minutes.

(2) Benefit:
* All of the possible naming candidates are equally good; none of them are misleading or confusing.

That unambiguously ends up on the side of "don't spam our users with pointless renames".  Deprecation is a tool in our toolbox for reducing the pain of a transition.  The preceding question is  "should we introduce any pain in the first place" and I don't think the current names are bad enough to send any amount of pain downstream to our users.

If the bug had been assigned to me, I would have just closed it as "won't fix", but if we are fixing it then we should do the 5-minute thing and choose the smallest, quickest fix.

___

**Comment by jwnimmer-tri** [comment]
FYI I'm going to be unavailable for reviews for the rest of this week, so please pass this PR along to the next on-call reviewer once it's ready for review again.

**Review by mitiguy — COMMENTED** [review]
Feature review -@jwnimmer-tri 
Platform review -@jwnimmer-tri 

Feature review +@EricCousineau-TRI 
Platform review +@EricCousineau-TRI   (for both reviews).

Eric -- I made the small changes as Jeremy suggested.  This PR will resolve issue #18768   

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-:-NzAypIoCM7fNgVszkOn:bkcdhti)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2, thanks!

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-:-NzB0Qls0BLMigG88vgl:b-9wquo5)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Dismissed @jwnimmer-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21478)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21478#-Nyf5XtHEauy-vVzI203:-NzB0d0I7eSTXzB2A95-:bqfq2in) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For myself, I would weigh the options like this:

(1) Cost:
* Renaming the Python side forces our users to edit their code that was already working just fine.  This is one of the worst costs we can imagine, second only to "computed incorrect results".
* Renaming the C++ side is extremely easy and does not affect users.  It should take about 5 minutes.

(2) Benefit:
* All of the possible naming candidates are equally good; none of them are misleading or confusing.

That unambiguously ends up on the side of "don't spam our users with pointless renames".  Deprecation is a tool in our toolbox for reducing the pain of a transition.  The preceding question is  "should we introduce any pain in the first place" and I don't think the current names are bad enough to send any amount of pain downstream to our users.

If the bug had been assigned to me, I would have just closed it as "won't fix", but if we are fixing it then we should do the 5-minute thing and choose the smallest, quickest fix.
</blockquote></details>

Latest revision shows renaming the C++ side to just `alloc` and `calc`, thus I will mark this as resolved.

___

**Comment by jwnimmer-tri** [comment]
Documentation changes do not appear in release notes, so +(release notes: none) -(release notes: fix).

**Pull request merged**
