### PR TITLE
Update supported Clang to 6.0 and add support for Bionic and Mojave

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9483)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-documentation please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-mosek please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-mosek please
@drake-jenkins-bot linux-xenial-clang-cmake-experimental-snopt please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-lsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-mosek please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-gurobi please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-gurobi please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-mosek please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab-snopt please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-mosek please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-snopt please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-tsan please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
SNOPT has undefined behavior. Great.

**Comment by jwnimmer-tri** [comment]
We have a few SNOPT updates in the queue, that replace Drake master revision of SNOPT.  I would guess about two weeks until we'd have a proposal for one we think is good enough for master.  Not sure how long you want to wait.  We could add a suppression for the moment, instead?

**Comment by jamiesnape** [comment]
I think I will just turn off `-fsanitize=pointer-overflow` on "everything" builds for now. Since we build SNOPT from source, it would have to be blacklisted or suppressed inline within SNOPT.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
Definitely not going to merge this before or during the weekend, but we can get the reviews started now, I think.

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI +@jwnimmer-tri +@soonho-tri for feature review.

**Comment by jamiesnape** [comment]
As far as logistics go, I have to simultaneously make changes to drake-ci for Linux and on Jenkins for Mac, so the "do not merge" tag needs to stay until the last minute.

**Comment by jamiesnape** [comment]
Should this need to be reverted, https://github.com/RobotLocomotion/drake-ci/commit/937ee5baeeecbef5edd51f49c42dfb66724c80bc would also need to be reverted.

**Pull request merged**
