### PR TITLE
[doc] Highlight Anaconda incompatibility in the installation docs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Demote the "known issues" warning to be later in the list; we have many of them fixed already.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16649)

### CODE REVIEW

**Comment by buoyancy99** [comment]
I am wondering whether drake can be installed and work once anaconda env is deactivated. If that's the case, asking users to deactivate conda env seems easier than editing $PATH

**Comment by jwnimmer-tri** [comment]
> I am wondering whether drake can be installed and work once anaconda env is deactivated.

I don't know anaconda much at all, so I can't say unless I do more experimentation.

I asked about this on Drake's `#python` slack, and the consensus seemed to be that deactivating would not be sufficient, but I'm not sure if that was proven one way or the other.

**Comment by jwnimmer-tri** [comment]
Upon further discussion, it sounds like the trick is if you `conda deactivate` enough times so that even the conda _base_ environment disappears, then yes that would be sufficient.  I'll plan to update this PR to say that, instead.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.
+@ggould-tri for platform review, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16649#-:-Mx-gnPo-JeQmBz0rXy_:bnfp4nl)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with BTW

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16649#-:-Mx-mFq39R2yABdC2khF:b-xv71ra)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[doc/_pages/installation.md, line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16649#-Mx-m51a5b2_Fd-CAcEZ:-Mx-m51a5b2_Fd-CAcE_:b-ncns96) ([raw file](https://github.com/robotlocomotion/drake/blob/9393c1889d9c4de804170a60ac71c906539f7ae6/doc/_pages/installation.md#L39)):*
> ```Markdown
> 
> ⁽³⁾ CPython is the only Python implementation supported.
> Drake does not support the Python environment supplied by Anaconda. Before
> ```

BTW (here and in other stanzas)
As alternative for advanced users, consider mentioning "silent installation" as a way to have more control:
https://docs.anaconda.com/anaconda/install/silent-mode/#linux-macos

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16649)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
