### PR TITLE
Reduce documentation size

### PR DESCRIPTION
**Pull request by jamiesnape**
Using SVG reduces size considerably and is much more Git-friendly. A version of this PR is live now. The old JPEG- and PNG-based documentation is too large to push in a single revision.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6911)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@stonier for feature review. High priority.

**Comment by stonier** [comment]
3.0G -> 710M!

Loaded up old and new in chrome, doxygen graphs still seem ok, so :lgtm:

+@sherm1 for platform review please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6911#-:-KsOTJc-_ptpk6NaSdV_:b6cll61)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6911)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6911#-:-KsP9zq9eQ0VU2NnBlqv:b8qx53o)*

**Pull request merged**
