### PR TITLE
py mbp: Fix bindings for plant test

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
- Ensure we cover T for deprecated MultibodyPlant_[T].WeldFrames
- Use unittest.subTest to trace back to joint factories

Follow-up to #14805

Fixes buildcop failures. One such failure:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-catalina-clang-bazel-continuous-release/291/console

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14813)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews, please!
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14813#-:-MWU0ZzG80i7suVFuafx:b33bm6)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by EricCousineau-TRI** [comment]
Per Slack, this also fixes the buildcop relevant failure :shrug: 
https://drakedevelopers.slack.com/archives/C270MN28G/p1616503008012300?thread_ts=1616500538.010200&cid=C270MN28G

```
$ git log -n 1 --oneline --no-decorate
dcf0e7a42b Add ClpSolver (#14776)
$ bazel run //bindings/pydrake/multibody:py/plant_test
...
======================================================================
FAIL [0.028s]: test_multibody_add_joint (plant_test.TestPlant)
Tests joint constructors, `AddJoint`, `AddJointActuator` and
----------------------------------------------------------------------
Traceback (most recent call last):
  File "{runfiles}/drake/bindings/pydrake/common/test_utilities/numpy_compare.py", line 255, in wrapper
    check_func(*args, T=AutoDiffXd, **kwargs)
  File "{runfiles}/drake/bindings/pydrake/multibody/test/plant_test.py", line 1608, in test_multibody_add_joint
    self.assertIs(joint, joint_out)
AssertionError: <WeldJoint_[AutoDiffXd] name='weld' index=0 model_instance=1> is not <WeldJoint_[AutoDiffXd] name='weld' index=0 model_instance=1>


$ git log -n 1 --oneline --no-decorate
29606f3e75 py mbp: Fix bindings for plant test
$ bazel run //bindings/pydrake/multibody:py/plant_test
...
Ran 33 tests in 2.025s

OK
```

**Comment by EricCousineau-TRI** [comment]
See Slack for limited attempt to root-cause why this scope change fixes it.

**Comment by EricCousineau-TRI** [comment]
Note that mac testing was done on macsim. However, for completeness' sake:
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14813#-:-MWUjcSe8PtADXddnl38:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
