### PR TITLE
Remove ccd, octomap, fcl, ignition_* from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6471)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6471#-KnommIhNLserc49a-_I:-KnommIhNLserc49a-_J:b-me2sj1) (no related file):*
People are still using `cpplint_wrapper.py`; is there a sensible way to keep it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6471)*

**Comment by jamiesnape** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6471#-KnommIhNLserc49a-_I:-KnonUSaeMGdX_zQdfkN:b-5f0zd7) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

People are still using `cpplint_wrapper.py`; is there a sensible way to keep it?
</blockquote></details>

I can just roll back that part, though I would strongly advise them not to use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6471)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6471#-KnommIhNLserc49a-_I:-KnopFbkCgsAuMPRViJX:b-i5axf8) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I can just roll back that part, though I would strongly advise them not to use it.
</blockquote></details>

Yeah, I think we can pivot away from it pretty quickly and then remove it, but we need to flesh out a little more glue and docs first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6471)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@soonho-tri for platform review, please.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6471#-:-Knotqn0g6t24Owz5lMg:bz1ribg)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6471#-:-KnqjEpfajU9fsC9uNcu:bnfp4nl)*

**Pull request merged**
