### PR TITLE
[doc] Clarify what "support" means a bit

### LINKED ISSUE #18802: Clarify "supported" configurations
Sometimes, Drake users do not completely understand what platforms and version Drake can run on, and what "supported" means.

We have these pages:
- https://drake.mit.edu/installation.html#supported-configurations
- https://drake.mit.edu/from_source.html#supported-configurations

Those explain pretty well which configurations Drake has _official_ support for.  In this case we should clarify that official "support" or "supported" means that (1) we have CI coverage to notice regressions and (2) if it doesn't work, that should be a bug report.

It's also true that Drake can run on more than just what's listed there.  For example, we ship `pip` wheels for many more CPython versions than just those listed. Also, when building from source via CMake the user can customize their settings beyond exactly what is listed there (i.e., different compiler, or amd64 arch on Ubuntu (#13514), or eventually (#18719) the Python version, etc.).

We should make it clear that those kinds of builds will _probably_ work (so in that sense they are "supported"), but that we don't have CI coverage for them so they are "at your own risk".  If there is a problem, you'll need to PR a fix, not file a bug.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18802.

+@BetsyMcPhail for feature review, please.

+@SeanCurtis-TRI for feature & platform review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`doc/_pages/installation.md` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18853#-NOvLdGe47x3Cy9T9K3p:-NOvLdGe47x3Cy9T9K3q:bxtclar) ([raw file](https://github.com/RobotLocomotion/drake/blob/de6f75606991b3bef26222ddd1b01a41e1772a19/doc/_pages/installation.md#L44)):*
> ```Markdown
> has caused problems for some users.
> 
> ⁽³⁾ On Ubuntu when installing via ``pip``, CPython versions 3.8 through 3.11
> ```

nit: Given this comment, the corresponding entry in the table becomes a bit trickier to interpret.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @SeanCurtis-TRI)

___
*[`doc/_pages/installation.md` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18853#-NOvLdGe47x3Cy9T9K3p:-NOvLtk76npBnf1zMd_4:bur47qx) ([raw file](https://github.com/RobotLocomotion/drake/blob/de6f75606991b3bef26222ddd1b01a41e1772a19/doc/_pages/installation.md#L44)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Given this comment, the corresponding entry in the table becomes a bit trickier to interpret.
</blockquote></details>

The table shows what is supported for all other installation channels other than pip.

Any suggestions on a rephrasing here?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`doc/_pages/installation.md` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18853#-NOvLdGe47x3Cy9T9K3p:-NOvQ06N2E-5F48mA8BJ:b-9jbpd8) ([raw file](https://github.com/RobotLocomotion/drake/blob/de6f75606991b3bef26222ddd1b01a41e1772a19/doc/_pages/installation.md#L44)):*
I'd go with that.

> Version noted is for all installation channels _except_ via ``pip`` on Ubuntu, where CPython versions 3.8 through 3.11, inclusive, are supported.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853)* status: LGTM missing from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853#-:-NOykMm-6vwtjdDRmjcM:bnfp4nl)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18853#-:-NOyviP8088Xewq976gv:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),BetsyMcPhail (waiting on @jwnimmer-tri)

**Pull request merged**
