### PR TITLE
[ad] Add AutoDiff replacement class for AutoDiffXd

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/pull/17492.

This is private for now; it is not used outside of its unit tests.

See #17622 for how we'll start to add actual operations (and their unit tests).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @sherm1 FYI.  If you'd like this to pause until you have time to review it, feel free to assign yourself for review here.

**Comment by sherm1** [comment]
I'd love to review this but hate to be a bottleneck -- I'm out for another week. @rpoyner-tri could certainly give it a solid once-over.

**Comment by jwnimmer-tri** [comment]
I think for this PR (which is "So what is AutoDiff anyway, and how's this look for a new subdirectory home?"), let's do +@rpoyner-tri  for feature review, please -- in the background.  For the future PRs that build on it (e.g., adding math functions) we can cycle through others.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621#-:-N7vUqQE6stbsmPhOkZ2:bnfp4nl)* status: 8 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vUoET514YqjcazEcy:-N7vUoET514YqjcazEcz:boogyrg) (no related file):*
'common/ad' is a bit clipped, but maybe justified by frequency of use. FWIW 'common/autodiff' is the same length as 'common/symbolic', and subtly reinforces the parallelism.

I'm not against 'common/ad', but might lobby for a directory README.md if we go with the short name.

___
___
*[`common/ad/auto_diff.h` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vMx3U3Ut1p6vYwHzv:-N7vMx3U3Ut1p6vYwHzw:b-ri1hda) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/auto_diff.h#L61)):*
> ```objc
> 
>   /** (Advanced) Returns the value part of this %AutoDiff (mutable).
>   Operations on this value will NOT alter the dervatives. */
> ```

typo, here and elsewhere



_Code quote:_
```objc
dervative
```
___
*[`common/ad/auto_diff.h` line 97 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vNApb2wcpmaL4hm_j:-N7vNApb2wcpmaL4hm_k:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/auto_diff.h#L97)):*
> ```objc
> 
> /* clang-format off to disable clang-format-includes */
> // These futher refine our AutoDiff type and must appear in exactly this order.
> ```

typo



_Code quote:_
```objc
futher
```
___
*[`common/ad/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vQGFc-Dxw-26EJuY9:-N7vQGFc-Dxw-26EJuYA:bvr3gp2) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/BUILD.bazel#L55)):*
> ```Starlark
> drake_cc_googletest(
>     name = "standard_operations_test",
>     # The test is split into multiple source files to improve compilation time.
> ```

Is this comment premature?
___
*[`common/ad/internal/partials.h` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vQfWI5_TxTmcpqJWO:-N7vQfWI5_TxTmcpqJWP:b9cxkzc) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.h#L12)):*
> ```objc
> 
> Partials are dynamically sized, and can have size() == 0.
> When adding two non-zero Partials, both must be of the same size(). */
> ```

This seems a little bit short, assuming:
* 0-sized partial stands in for a partial filled with zeros, of any size.
* "non-zero" means non-zero-sized.
*  there is no invariant prohibiting non-zero-sized zero-valued vectors.



_Code quote:_
```objc
Partials are dynamically sized, and can have size() == 0.
When adding two non-zero Partials, both must be of the same size(). */
```
___
*[`common/ad/internal/partials.h` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vPGoU6V5Z_L2cuzQU:-N7vPGoU6V5Z_L2cuzQV:b-m7i6n7) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.h#L58)):*
> ```objc
>   /* Returns the underlying storage vector (readonly).
>   TODO(jwnimmer-tri) Use a more Xpr-like return type. */
>   const Eigen::VectorXd& make_const_xpr() const {
> ```

`xpr` could use some explanation, or a respelling.



_Code quote:_
```objc
xpr
```
___
*[`common/ad/internal/partials.cc` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vRyFb8Wg-rRbcfCX5:-N7vRyFb8Wg-rRbcfCX6:bd404k3) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.cc#L48)):*
> ```cpp
> 
> void Partials::AddScaled(double scale, const Partials& other) {
>   if (other.size() == 0) {
> ```

maybe doesn't matter yet, but we could also shortcut "scale == 0.0"
___
*[`common/ad/test/auto_diff_basic_test.cc` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vNM9ADG5UZG3EqnBY:-N7vNM9ADG5UZG3EqnBZ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/test/auto_diff_basic_test.cc#L7)):*
> ```cpp
> 
> // This file contains only the very most basic unit tests for AutoDiffXd, e.g.,
> // construction and assignment. Tests for the derivatative math are elsewhere.
> ```

typo



_Code quote:_
```cpp
derivatative
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vUoET514YqjcazEcy:-N7vjeNu1KkdMqgh72uU:b271xqz) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

'common/ad' is a bit clipped, but maybe justified by frequency of use. FWIW 'common/autodiff' is the same length as 'common/symbolic', and subtly reinforces the parallelism.

I'm not against 'common/ad', but might lobby for a directory README.md if we go with the short name.


</blockquote></details>

Added README.

___
___
*[`common/ad/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vQGFc-Dxw-26EJuY9:-N7vVnOPB-PHvOHgAh13:b-enju7b) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/BUILD.bazel#L55)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Is this comment premature?
</blockquote></details>

It's certainly forward-looking.  In this PR overview, I've linked to #17622 which shows the additional test files appearing.
___
*[`common/ad/internal/partials.h` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vQfWI5_TxTmcpqJWO:-N7vmN3pBLaK84pDKyuq:b-wcqzou) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.h#L12)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This seems a little bit short, assuming:
* 0-sized partial stands in for a partial filled with zeros, of any size.
* "non-zero" means non-zero-sized.
*  there is no invariant prohibiting non-zero-sized zero-valued vectors.
</blockquote></details>

Done.

Yup, the "sticky size" thing (even after a `.Mul(0.0)`) is actually important, and breaks some downstream tests in case it goes away.
___
*[`common/ad/internal/partials.h` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vPGoU6V5Z_L2cuzQU:-N7vkT7C7icN_CwHNR85:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.h#L58)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`xpr` could use some explanation, or a respelling.
</blockquote></details>

Done.
___
*[`common/ad/internal/partials.cc` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vRyFb8Wg-rRbcfCX5:-N7vkXMbC9hZlyZkmLZ1:b5d175l) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.cc#L48)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

maybe doesn't matter yet, but we could also shortcut "scale == 0.0"
</blockquote></details>

It's coming down the road (https://github.com/jwnimmer-tri/drake/blob/autodiff-repave/common/ad/internal/partials.h).

Even with scale == 0, I think we will still want to do matching-size checking in Debug builds, and getting that coded up and probed with Debug-only unit testing is more than this PR can hold.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/ad/README.md` line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vyc2E8SbuEwO6bpZn:-N7vyc2E8SbuEwO6bpZo:b-70izkc) ([raw file](https://github.com/robotlocomotion/drake/blob/25fb7b24139094d7894f219c8b7e3e7a27041aa8/common/ad/README.md#L9)):*
> ```Markdown
> 
> The `namespace ad { ... }` is chosen for it's compact size in debugging traces,
> but is not otherwise exposed to uses
> ```

Did you mean `users`? Also, punc.



_Code quote:_
```Markdown
uses
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`common/ad/README.md` line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vyc2E8SbuEwO6bpZn:-N7vza0x4MZtHv19Ow-Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25fb7b24139094d7894f219c8b7e3e7a27041aa8/common/ad/README.md#L9)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Did you mean `users`? Also, punc.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with a few comments.

> Reviewed 6 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621#-:-N7wiymm3GEuSNEfDaLS:b-2cmql7)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wisR_1Ay3dToYnydz:-N7wisR_1Ay3dToYnye-:b-3hapan) (no related file):*
nit missing test coverage on mutable getters.

___
___
*[`common/ad/internal/partials.h` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7vQfWI5_TxTmcpqJWO:-N7wg7mD5DLyjkjIG6-s:b-ek0t3h) ([raw file](https://github.com/robotlocomotion/drake/blob/feaa9b55ef65b727a38ee7d4607f263740d8b382/common/ad/internal/partials.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

Yup, the "sticky size" thing (even after a `.Mul(0.0)`) is actually important, and breaks some downstream tests in case it goes away.
</blockquote></details>

I think it's also worth mentioning that when you call `a.Add(b)` where `a.size() == 0` and `b.size() != 0`, `a` assumes the size of `b`.
___
*[`common/ad/internal/partials.h` line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wdkd2BV63DIwUX2In:-N7wdkd2BV63DIwUX2Io:bjhgdv2) ([raw file](https://github.com/robotlocomotion/drake/blob/091f2920deb334d4f702721dbeb6107d3ed5e0e6/common/ad/internal/partials.h#L7)):*
> ```objc
> 
> namespace drake {
> namespace internal {
> ```

BTW, why not `drake::ad::internal` instead of `drake::internal`?
___
*[`common/ad/test/partials_test.cc` line 111 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wiQj0CB65EwPVPGFm:-N7wiQj0CB65EwPVPGFn:bvb3q97) ([raw file](https://github.com/robotlocomotion/drake/blob/091f2920deb334d4f702721dbeb6107d3ed5e0e6/common/ad/test/partials_test.cc#L111)):*
> ```cpp
> }
> 
> TEST_F(PartialsTest, Div) {
> ```

nit, consider a test to lock in the behavior of division by zero.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wisR_1Ay3dToYnydz:-N7wo8MQED6T-X764kNr:b-5vydiv) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit missing test coverage on mutable getters.
</blockquote></details>

Done.

It was tested indirectly in `AutodiffBasicTest.AssignConstant`, but now it's directly tested in `PartialsTest.DefaultCtorMutableGetter`.

___
___
*[`common/ad/internal/partials.h` line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wdkd2BV63DIwUX2In:-N7wpLjoEJvIW54QnvIO:b-3dey75) ([raw file](https://github.com/robotlocomotion/drake/blob/091f2920deb334d4f702721dbeb6107d3ed5e0e6/common/ad/internal/partials.h#L7)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why not `drake::ad::internal` instead of `drake::internal`?
</blockquote></details>

OK let's try that for now.  If during the full branch there comes a time where dropping the extra namespace would help, I'll revert it at that point.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17621)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`common/ad/internal/partials.h` line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17621#-N7wdkd2BV63DIwUX2In:-N7wrAh9ADVt--Sci5rZ:b-81nlyc) ([raw file](https://github.com/robotlocomotion/drake/blob/091f2920deb334d4f702721dbeb6107d3ed5e0e6/common/ad/internal/partials.h#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK let's try that for now.  If during the full branch there comes a time where dropping the extra namespace would help, I'll revert it at that point.
</blockquote></details>

SGTM.

**Pull request merged**
