### PR TITLE
Update sedumi submodule SHA

### PR DESCRIPTION
**Pull request by jamiesnape**
To hopefully reduce the segfaults during build.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3714)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3714#-:-KTVNVy_Krimldc9F8Ng:bnfp4nl)*

**Pull request merged**
