### PR TITLE
[docker] Enable Jammy docker builds

### PR DESCRIPTION
**Pull request by svenevs**
Follow-up to https://github.com/RobotLocomotion/drake/issues/16217#issuecomment-1178416097

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging please.

**Review by svenevs — COMMENTED** [review]
+@mwoehlke-kitware for feature review please.  I took a look at `drake-ci` but AFAICT there should not be changes needed there until drake adopts jammy as the main distribution (like during the bionic => focal transition).  However, the experimental build will likely reveal something.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546#-:-N6jIFozE7yoSWx9mJZF:bo86sbf)* status: 3 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/install/dockerhub/jammy/Dockerfile` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIz8-2gxUc111tm5e:-N6jIz8-2gxUc111tm5f:b-4x5ywc) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/Dockerfile#L12)):*
> ```Dockerfile
> # Make python and pip available to meet the requirements for deepnote.com:
> # https://docs.deepnote.com/environment/custom-environments#custom-image-requirements
>     python3-pip python-is-python3 \
> ```

Working, the `focal` one has something in there to shim out `drake-visualizer`.  That's not supported on Jammy so currently I removed it, but it seems like we may want to do a related followup to disable installing `drake-visualizer` on jammy.  Currently the `drake-visualizer` python script is installed and then quickly crashes saying it cannot find `.drake-visualizer-real` (since it does not exist for jammy).
___
*[`tools/install/dockerhub/jammy/README.md` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIXxSAjYEtIBmchAz:-N6jIXxSAjYEtIBmchB-:b-t2a77o) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L17)):*
> ```Markdown
> 
> ```bash
> docker run -it robotlocomotion/drake:jammy
> ```

Working, should we fix these directions (and the `focal` one) to include `--rm`?  The above means that it hangs around (`docker ps -a`).
___
*[`tools/install/dockerhub/jammy/README.md` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIg7q1LVZgCFFW9bm:-N6jIg7q1LVZgCFFW9bn:byjrpon) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L20)):*
> ```Markdown
> ```
> 
> The environment variables `LD_LIBRARY`, `PATH`, and `PYTHONPATH` are preset to
> ```

Working, somebody with better docker skills can please illuminate?  The `ENV` vars set at the end of the `Dockerfile` are not set when I `docker run` the container.  Am I just doing something silly or is this statement not really accurate?  (E.g., it's only accurate for derivative images but not actually for the drake images)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546)* status: 3 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/install/dockerhub/jammy/README.md` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIXxSAjYEtIBmchAz:-N6nCSyvAKWmmGqlQCz7:b-ku2a1s) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L17)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, should we fix these directions (and the `focal` one) to include `--rm`?  The above means that it hangs around (`docker ps -a`).
</blockquote></details>

I'm inclined to say 'no'; I'd prefer to err on the side of naïve users getting cruft vs. losing their work because they don't realize that `--rm` destroys the container on exit. At least, if we add `--rm`, it should be accompanied by a note that the container will be destroyed on exiting the shell.
___
*[`tools/install/dockerhub/jammy/README.md` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIg7q1LVZgCFFW9bm:-N6nHdwS8czL1JjqVTDz:bdivtsz) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L20)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, somebody with better docker skills can please illuminate?  The `ENV` vars set at the end of the `Dockerfile` are not set when I `docker run` the container.  Am I just doing something silly or is this statement not really accurate?  (E.g., it's only accurate for derivative images but not actually for the drake images)
</blockquote></details>

That is... not expected? If I take the following `Dockerfile`:
```dockerfile
FROM ubuntu:jammy
ENV FOOBAR=none
ENV LD_LIBRARY_PATH=/tmp
```
...and run the container, both variables are set as expected.

**Review by svenevs — COMMENTED** [review]
Looks good, -(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546#-:-N6n_g4O9YKNAAh0BWJG:bjpopr6)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`tools/install/dockerhub/jammy/Dockerfile` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIz8-2gxUc111tm5e:-N6n_BXpE6AnZ-qMkygh:b-qfobym) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/Dockerfile#L12)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, the `focal` one has something in there to shim out `drake-visualizer`.  That's not supported on Jammy so currently I removed it, but it seems like we may want to do a related followup to disable installing `drake-visualizer` on jammy.  Currently the `drake-visualizer` python script is installed and then quickly crashes saying it cannot find `.drake-visualizer-real` (since it does not exist for jammy).
</blockquote></details>

OK, it's getting removed in https://github.com/RobotLocomotion/drake/pull/17553 and does not need to block this PR (they can merge independently from one another).
___
*[`tools/install/dockerhub/jammy/README.md` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIXxSAjYEtIBmchAz:-N6n_LbABRb35nowDcYq:bre892m) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L17)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm inclined to say 'no'; I'd prefer to err on the side of naïve users getting cruft vs. losing their work because they don't realize that `--rm` destroys the container on exit. At least, if we add `--rm`, it should be accompanied by a note that the container will be destroyed on exiting the shell.
</blockquote></details>

OK works for me :+1:
___
*[`tools/install/dockerhub/jammy/README.md` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIg7q1LVZgCFFW9bm:-N6n_O6u6vCrCiHXWrOh:b-8zeuun) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L20)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

That is... not expected? If I take the following `Dockerfile`:
```dockerfile
FROM ubuntu:jammy
ENV FOOBAR=none
ENV LD_LIBRARY_PATH=/tmp
```
...and run the container, both variables are set as expected.
</blockquote></details>

OK thanks for confirming!  It's been fixed, the preceding line in the `Dockerfile` had a `\` at the end so the statement was part of `rm` :interrobang: Current revision now has the environment variables set and you can e.g., launch `python` and execute `from pydrake.all import *` without error.

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: (relying on your own local testing...)

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546#-:-N6nc9aGAtNq4_pAySup:bnn6w55)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @svenevs)

___
*[`tools/install/dockerhub/jammy/README.md` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17546#-N6jIg7q1LVZgCFFW9bm:-N6naisf0kK4swBKXJyg:bvb2dsb) ([raw file](https://github.com/robotlocomotion/drake/blob/3f8442ab18c4a43719eee382c436e870e2e2726c/tools/install/dockerhub/jammy/README.md#L20)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

OK thanks for confirming!  It's been fixed, the preceding line in the `Dockerfile` had a `\` at the end so the statement was part of `rm` :interrobang: Current revision now has the environment variables set and you can e.g., launch `python` and execute `from pydrake.all import *` without error.
</blockquote></details>

D'oh. That would do it :blush:.

**Review by svenevs — COMMENTED** [review]
+@rpoyner-tri for platform review please.  Context: the `jammy` packaging job was previously failing because these files were missing, in the status checks of this PR the jammy packaging job succeeds.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546#-:-N6nccbd663h_J-m9wOC:b6juny5)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17546#-:-N6nuV9U8NVtaRVXETuC:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),mwoehlke-kitware (waiting on @svenevs)

**Pull request merged**
