### PR TITLE
Fix typo in automotive/steering_command_driver.py

### PR DESCRIPTION
**Pull request by soonho-tri**
See https://github.com/RobotLocomotion/drake/blob/master/automotive/driving_command.named_vector#L10

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8745)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for all reviews, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8745#-:-LBXerYO-u6334so3i9v:b-g6fe9u)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/steering_command_driver.py, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8745#-LBXf6h-DA5mhcpAhsbY:-LBXf6h-DA5mhcpAhsbZ:bhaevfk) ([raw file](https://github.com/robotlocomotion/drake/blob/66e153056af03f876c73332cb1ec17a6ad679731/automotive/steering_command_driver.py#L222)):*
> ```Python
>     lc = lcm.LCM()
>     last_msg = lcm_msg()
>     last_msg.acceleration = throttle
> ```

BTW Needs a unit or regression test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8745#-:-LBXf69D5OvOyLjskpxe:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[automotive/steering_command_driver.py, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8745#-LBXf6h-DA5mhcpAhsbY:-LBvpAs_3gPknJRjwSwv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66e153056af03f876c73332cb1ec17a6ad679731/automotive/steering_command_driver.py#L222)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Needs a unit or regression test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8745)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[automotive/BUILD.bazel, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8745#-LBzwHIN9dyRkLbswkiR:-LBzwHIN9dyRkLbswkiS:b-46xlxp) ([raw file](https://github.com/robotlocomotion/drake/blob/13d971b743eb38551d50109f1a533e96daa0c4db/automotive/BUILD.bazel#L19)):*
> ```Python
> )
> load(
>     "@drake//tools/skylark:drake_py.bzl",
> ```

BTW Consolidate the new `load` into here instead, for consistency.

---

*[automotive/test/steering_command_driver_test.py, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8745#-LBzwwOVAIYf76FeeZKG:-LBzwwOVAIYf76FeeZKH:b-4z8uur) ([raw file](https://github.com/robotlocomotion/drake/blob/13d971b743eb38551d50109f1a533e96daa0c4db/automotive/test/steering_command_driver_test.py#L21)):*
> ```Python
> 
>     def test_make_driving_command(self):
>         receiver = lcm.LCM()
> ```

BTW Since this test uses real LCM, it needs to be marked as flaky in the BUILD file.

---

*[automotive/test/steering_command_driver_test.py, line 28 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8745#-LBzx52FE1qxTJ9OTu1k:-LBzx52FE1qxTJ9OTu1l:b-ohhamz) ([raw file](https://github.com/robotlocomotion/drake/blob/13d971b743eb38551d50109f1a533e96daa0c4db/automotive/test/steering_command_driver_test.py#L28)):*
> ```Python
>                                             self.steering_angle).encode())
>         receiver.handle()
>         receiver.unsubscribe(subscription)
> ```

BTW I think if `self.handler` never ends up being called, the test would still pass?  It seems like we need an assertion that the handler was run.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8745)*

**Comment by jwnimmer-tri** [comment]
Oops.  This PR transmits the steering as throttle, and throttle as steering.  The make_driving_command positional arguments are swapped at the call sites.

**Comment by soonho-tri** [comment]
🤦‍♂️ 

I will open a PR to fix it.

**Pull request merged**
