### PR TITLE
Remove drake-distro from doxygen and sphinx

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also remove the flag-day dev tool.

Relates #6996.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7881)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for all review, please.

**Comment by sherm1** [comment]
:lgtm: with a BTW and FYI.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/from_source.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-L3ou4IIDCBClHh2VcaP:-L3ou4IIDCBClHh2VcaQ:bdkvevz) ([raw file](https://github.com/robotlocomotion/drake/blob/b4d1a4674df39f47bb8485a29ad45f4d8523483c/doc/from_source.rst#L19)):*
> ```reStructuredText
> Now run::
> 
>     git clone git@github.com:RobotLocomotion/drake.git
> ```

BTW I _think_ it is now mandatory to call the drake root directory "drake"? If so this might be a good place to say so.

---

*[multibody/rigid_body_plant/images/simple_contact.svg, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-L3ovE99vMw-GzRoOZjE:-L3ovE99vMw-GzRoOZjF:b-pbwb2o) ([raw file](https://github.com/robotlocomotion/drake/blob/b4d1a4674df39f47bb8485a29ad45f4d8523483c/multibody/rigid_body_plant/images/simple_contact.svg#L18)):*
> ```SVG
>    inkscape:version="0.48.4 r9939"
>    sodipodi:docname="simple_contact.svg"
>    inkscape:export-filename="/home/username/drake/multibody/rigid_body_plant/images/simple_contact.png"
> ```

FYI this is certainly an improvement over `/home/seanc` but seems unlikely to work! I'm not complaining though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-:-L3ovhTuwQXdbMoqKPEi:bhyo5t2)*

**Comment by jwnimmer-tri** [comment]
*[doc/from_source.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-L3ou4IIDCBClHh2VcaP:-L3ovxcyjEqJoraNN9mo:b3qvfbw) ([raw file](https://github.com/robotlocomotion/drake/blob/b4d1a4674df39f47bb8485a29ad45f4d8523483c/doc/from_source.rst#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I _think_ it is now mandatory to call the drake root directory "drake"? If so this might be a good place to say so.
</blockquote></details>

Its only mandatory for CLion users who use the smart navigation features.  We mention the "must be named `drake`" requirement in `clion.rst` docs already at http://drake.mit.edu/clion.html#installing-the-bazel-plugin.

I am also happy to mention it here, but wanted to get your thoughts in case that info changes your mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7881)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/from_source.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-L3ou4IIDCBClHh2VcaP:-L3p0XRUWTOAmAZmSvGU:b-4b1oxp) ([raw file](https://github.com/robotlocomotion/drake/blob/b4d1a4674df39f47bb8485a29ad45f4d8523483c/doc/from_source.rst#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its only mandatory for CLion users who use the smart navigation features.  We mention the "must be named `drake`" requirement in `clion.rst` docs already at http://drake.mit.edu/clion.html#installing-the-bazel-plugin.

I am also happy to mention it here, but wanted to get your thoughts in case that info changes your mind.
</blockquote></details>

Thanks, Jeremy -- I would still say something here since I expect that people execute this part of the instructions before they get to IDE specifics. Maybe something indirect and noncommittal like "Some IDEs may restrict the allowable Drake root directory name. Please check Drake's instructions for your IDE."
Or if it is really only CLion the comment could be more specific.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7881)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---

*[doc/from_source.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7881#-L3ou4IIDCBClHh2VcaP:-L3sIWk1xKZvPo3nrkKn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4d1a4674df39f47bb8485a29ad45f4d8523483c/doc/from_source.rst#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Thanks, Jeremy -- I would still say something here since I expect that people execute this part of the instructions before they get to IDE specifics. Maybe something indirect and noncommittal like "Some IDEs may restrict the allowable Drake root directory name. Please check Drake's instructions for your IDE."
Or if it is really only CLion the comment could be more specific.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7881)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7881)*

**Pull request merged**
