### PR TITLE
[pydrake] Fix ODR violations in get_new_id bindings

### LINKED ISSUE #15846: [pydrake] Bindings of Identifier types are not necessarily unique
The `Identifier` type has a static method `get_new_id()` that guarantees that, over the lifespan of the process, every invocation of that method returns a unique identifier that cannot be returned by any other invocation. This provides a process-global, typed unique identifier. This contract is backed up by a function-local static variable (the counter of ids produced which gets incremented and returned on each invocation).

The problem observed is that the python bindings have access to multiple instances of the same identifier type. This is illustrated by using two different public APIs that should draw from a common identifier pool, but, nevertheless draw from unique pools.

#15845 provides some code that exposes the bug (and provides further insight by dumping run-time information about the various Identifier types).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15846.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.
+@rpoyner-tri for platform review, please.

The thesis here is that, because it is our pydrake build system that is doing skeevy things with ODR, a pydrake-specific workaround seems like the best alternative.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending any observations from feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-Mkt-Aho4cQKwB2XCAdQ:bltqxgj)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I have one concern, see below.

> Reviewed 4 of 4 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-Mkt9acX2_Mm-Z2aR9LC:bufoa94)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/geometry_py.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MksXaMT7rFuSEczFMyL:-MksXaMT7rFuSEczFMyM:b-3rutc0) ([raw file](https://github.com/robotlocomotion/drake/blob/2d1a1b2a1e6ead32e10a5daa27182284c083efae/bindings/pydrake/geometry_py.cc#L89)):*
> ```cpp
> // For any Identifier<FooTag> class bound using this helper, its non-pydrake
> // *.cc file must contain an explicit class template instantiation.  Refer to
> // the existing bound Identifier<FooTag> classes for examples.
> ```

I tried breaking the requirement on the identifier to see what would happen if I bound it anyways. I got this:

```
...
  File "/home/seancurtis/.cache/bazel/_bazel_seancurtis/c482a09839de82c7b8c8a508d26ab2c3/sandbox/linux-sandbox/1629/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/test/geometry_test.py", line 1, in <module>
    import pydrake.geometry as mut
ImportError: /home/seancurtis/.cache/bazel/_bazel_seancurtis/c482a09839de82c7b8c8a508d26ab2c3/sandbox/linux-sandbox/1629/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/geometry.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5drake10IdentifierINS_8geometry8DummyTagEE10get_new_idEv
```

That's the first concrete feedback they get that they've done something wrong. That's really regrettable. I'd hope we could do better than that.
___
*[bindings/pydrake/test/frame_id_test.py, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MksYD0xCdFEkle9AG2c:-MksYD0xCdFEkle9AG2d:b37xofq) ([raw file](https://github.com/robotlocomotion/drake/blob/2d1a1b2a1e6ead32e10a5daa27182284c083efae/bindings/pydrake/test/frame_id_test.py#L18)):*
> ```Python
>         g = mut.GeometryFrame("geometry").id().get_value()
>         w = scene_graph.world_frame_id().get_value()
>         self.assertNotEqual(f, g)
> ```

BTW If you wanted to go really crazy, you could assert w < f < g. It's not documented, but it's secret behavior that is partially relied on (at least in some unit tests to simplify articulating the "true" answers.) It would be a slightly stronger statement. But the test, as is, certainly validates the test condition from earlier.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MksXaMT7rFuSEczFMyL:-MktBQ1yBDKvtJCtH3G-:bamkzr1) ([raw file](https://github.com/robotlocomotion/drake/blob/2d1a1b2a1e6ead32e10a5daa27182284c083efae/bindings/pydrake/geometry_py.cc#L89)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I tried breaking the requirement on the identifier to see what would happen if I bound it anyways. I got this:

```
...
  File "/home/seancurtis/.cache/bazel/_bazel_seancurtis/c482a09839de82c7b8c8a508d26ab2c3/sandbox/linux-sandbox/1629/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/test/geometry_test.py", line 1, in <module>
    import pydrake.geometry as mut
ImportError: /home/seancurtis/.cache/bazel/_bazel_seancurtis/c482a09839de82c7b8c8a508d26ab2c3/sandbox/linux-sandbox/1629/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/py/geometry_test.runfiles/drake/bindings/pydrake/geometry.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5drake10IdentifierINS_8geometry8DummyTagEE10get_new_idEv
```

That's the first concrete feedback they get that they've done something wrong. That's really regrettable. I'd hope we could do better than that.
</blockquote></details>

I agree that a nicer message would be better, but I also think the set of people who PR changes to this file is relatively small, and they would probably ping you or I (or Eric) for help were this to come up?

**Comment by jwnimmer-tri** [comment]
Another option would be to have a single `std::atomic<int64_t>` for all Identifiers, no matter their tag.  (It could easily live in one cc file, in that case.)  Maybe that's better?

**Review by SeanCurtis-TRI — COMMENTED** [review]
I can't think of any real issue with that very simple solution. Sure, for a brief period of time, anyone out there looking at id values might be mildly surprised in changes of some of the values. But I can't imagine there's much of that going on.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkvtZVi6cdTKhC_TF5P:b8n5jty)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
I'll put this one on hold while we try that.

**Review by SeanCurtis-TRI — COMMENTED** [review]
What we're talking about is a slight variation of my other branch. Instead of a `mutex` around an `unordered_map`, we just put in the `atomic<int>` there and call it good. Let me know if you'd like me to take this. But I'm equally content to let you wrap it up. No fire.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkwHoL70mR3aXyGAUmp:b-dhiati)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Although: This relates to #15860. `geometry_optimization_test.py` has a TODO referring to the issue this closes. So, depending on which one merges first (this or that), I'd like to coordinate the removal of that TODO.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkwI5RN1SnrTxY02j2D:b-5yxojv)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkwYZ2096aFiiC0Efca:b-b9fcpn)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @rpoyner-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MkwYZwb0isl7AlviW28:-MkwYZwb0isl7AlviW29:bjcenc8) (no related file):*
@rpoyner-tri please have another look, to re-up your LGTM (and/or add comments).

---
___
*[bindings/pydrake/geometry_py.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MksXaMT7rFuSEczFMyL:-MkwYdUK4Bjm7OiGeOvs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2d1a1b2a1e6ead32e10a5daa27182284c083efae/bindings/pydrake/geometry_py.cc#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I agree that a nicer message would be better, but I also think the set of people who PR changes to this file is relatively small, and they would probably ping you or I (or Eric) for help were this to come up?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/test/frame_id_test.py, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MksYD0xCdFEkle9AG2c:-MkwbNp56sajytxf1A-0:bqk61x2) ([raw file](https://github.com/robotlocomotion/drake/blob/2d1a1b2a1e6ead32e10a5daa27182284c083efae/bindings/pydrake/test/frame_id_test.py#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW If you wanted to go really crazy, you could assert w < f < g. It's not documented, but it's secret behavior that is partially relied on (at least in some unit tests to simplify articulating the "true" answers.) It would be a slightly stronger statement. But the test, as is, certainly validates the test condition from earlier.
</blockquote></details>

If other tests rely on the ordering, those tests are the ones that should be cross-checking it.  This test only checks for the acute problem of duplicated IDs.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkwiJP6CPlVKWsGZbuo:bmxilld)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[common/identifier.cc, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MkwhXSdAW_6eOJCe20k:-MkwhXSdAW_6eOJCe20l:bwgp5xh) ([raw file](https://github.com/robotlocomotion/drake/blob/97b3a94e42c1a378cade69e73d34a8de7c0d1b13/common/identifier.cc#L13)):*
> ```cpp
> // object code for initialization, so it is safe to use even without being
> // wrapped within a never_destroyed<>.
> static std::atomic<int64_t> g_prior_identifier;
> ```

BTW: How do you feel about being absolute explicit that this is initialized to zero (so `get_new_identifier()` does the *right* thing?

Either documenting that it defaults to zero, or explicitly initializing it to zero?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pedantry

> Reviewed 6 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857#-:-MkwqaPG5tCJtstxWqAz:b-huuxua)* status: 2 unresolved discussions (waiting on @jwnimmer-tri, @rpoyner-tri, and @SeanCurtis-TRI)

___
*[common/identifier.cc, line 19 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MkwqG5i8Zc7tfcAfBJn:-MkwqG5i8Zc7tfcAfBJo:b-lby7z5) ([raw file](https://github.com/robotlocomotion/drake/blob/97b3a94e42c1a378cade69e73d34a8de7c0d1b13/common/identifier.cc#L19)):*
> ```cpp
> int64_t get_new_identifier()  {
>   // Note that 0 is reserved for the uninitialized Identifier created by the
>   // default constructor, so we have an invariant that get_new_identifier() > 0.
> ```

The overflow boundary is distant, but still finite. Do we ever test our invariant, state that we are confident we can ignore it, or just pass over it in silence?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @rpoyner-tri)

___
*[common/identifier.cc, line 13 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MkwhXSdAW_6eOJCe20k:-Mkws_Ue8JdkYYBFPpGF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97b3a94e42c1a378cade69e73d34a8de7c0d1b13/common/identifier.cc#L13)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW: How do you feel about being absolute explicit that this is initialized to zero (so `get_new_identifier()` does the *right* thing?

Either documenting that it defaults to zero, or explicitly initializing it to zero?
</blockquote></details>

Done.
___
*[common/identifier.cc, line 19 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15857#-MkwqG5i8Zc7tfcAfBJn:-MkwrBtVAtLCYsCez0C6:b-do7ck7) ([raw file](https://github.com/robotlocomotion/drake/blob/97b3a94e42c1a378cade69e73d34a8de7c0d1b13/common/identifier.cc#L19)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

The overflow boundary is distant, but still finite. Do we ever test our invariant, state that we are confident we can ignore it, or just pass over it in silence?
</blockquote></details>

In my book, it is common knowledge that int64 counters that increment one at a time will not overflow during the lifetime of a process.

```
jwnimmer@call-cps:~$ units
You have: 2**63 nanoseconds
You want: years
	* 292.27727
	/ 0.0034214088
```

But, I added a comment anyway.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15857)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
