### PR TITLE
Add section on notation for vector derivatives

### PR DESCRIPTION
**Pull request by sherm1**
As part of the spatial acceleration derivation for the multibody tree in PR #6429, @amcastro-tri, @mitiguy, and I extended monogram notation for code that must deal with vector derivatives of spatial quantities taken in moving frames. This documents the results and prescribes this notation for anyone else who wants to do this (not likely to be many takers, I know!).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6483)

### CODE REVIEW

**Comment by sherm1** [comment]
Documentation only. @amcastro-tri for all review, please.
Attn: @mitiguy.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-KnqRY7caWIIHx38mf-F:b-uw0xze)*

**Comment by sherm1** [comment]
@amcastro-tri I know your doxygen is broken -- I generated it and it *looks* fine, so I think only the content needs review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-KnqS_-bVj1VreX9-BhM:bb6tklg)*

**Comment by amcastro-tri** [comment]
A few thoughts. Let me know what you think

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knqxu5YQigwKTSIiPFY:-Knqxu5YQigwKTSIiPFZ:bulv3vd) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L314)):*
> ```objc
> 
> //------------------------------------------------------------------------------
> /** @defgroup deriv_multibody_quantities Derivatives of Multibody Quantities
> ```

A few comments:
 1. I would say "Time Derivatives". Derivatives alone could signify gradients.
 2. I would introduce the topic first for 3D vectors, for which the simple "transport theorem" apply (and then you can reference `drake::math::ConvertTimeDerivativeToOtherFrame()`) and then, I would say that the time derivative of a spatial vector is the time derivative of each 3D vector component separately for which the transport theorem applies.
 3. Maybe this section could be titled "Time Derivatives" and then have a subsection for 3D vectors and a small section for spatial vectors? (for which everything said in the 3D vectors section can be applied to each component separately)

---

*[drake/multibody/multibody_doxygen.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqyiXX37vCkVuaPesm:-KnqyiXX37vCkVuaPesn:b-cyjtiv) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L324)):*
> ```objc
> our mathematical notation, a vector derivative operator with respect to time
> @f$ t @f$, taken in frame @f$ F @f$, and applied to some vector quantity
> @f$ Q @f$, is written @f$ \frac{^Fd}{dt}\,Q @f$. Our monogram notation for this
> ```

For a vector I would use a lower case letter, not upper case. Why not just `v` as a generic vector? Also, I'd say these are 3D vectors.

---

*[drake/multibody/multibody_doxygen.h, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzoEdqnW0qbBhl8vM:-KnqzoEdqnW0qbBhl8vN:b-t1uvy1) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L325)):*
> ```objc
> @f$ t @f$, taken in frame @f$ F @f$, and applied to some vector quantity
> @f$ Q @f$, is written @f$ \frac{^Fd}{dt}\,Q @f$. Our monogram notation for this
> is `DtF_Q`. When computing with these derived quantities (which are themselves
> ```

I would add that in code comments we use the operator `DtE(v)` to represent the time derivative in frame E of a vector v.

---

*[drake/multibody/multibody_doxygen.h, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knr-0w5SmuA5UurmR6b:-Knr-0w5SmuA5UurmR6c:b-91ejz8) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L332)):*
> ```objc
> quantity, _not_ the computational representation of that quantity. Thus it is
> not correct to include an expressed-in frame for the physical quantity Q in
> the symbol name; the expressed-in frame applies only to the final derived
> ```

I would here add the math to be specific like: "i.e DtA(v_E) has no meaning, [DtA(v)]_E is the correct quantity."

---

*[drake/multibody/multibody_doxygen.h, line 339 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzO_qOPZSduAuNceu:-KnqzO_qOPZSduAuNcev:b-aboyfi) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L339)):*
> ```objc
> lets say the world frame W here. It does not matter what expressed-in frame you
> were using for `V_PB`. So the symbol for the derivative would be `DtP_V_PB_W`
> which should be interpreted @f$ [\frac{^Pd}{dt}\,^PV^B]_W @f$; the `_W` goes
> ```

BTW, Why the switch to W? why not to keep using E for the expressed-in frame for consistency?

---

*[drake/multibody/multibody_doxygen.h, line 341 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzIkz_Safir4-sQ5u:-KnqzIkz_Safir4-sQ5v:b-d2id0u) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L341)):*
> ```objc
> which should be interpreted @f$ [\frac{^Pd}{dt}\,^PV^B]_W @f$; the `_W` goes
> with the result, not the quantity being differentiated. Of course in that case
> a better notation is `A_PB`! But that is only because we took the derivative
> ```

BTW, A_PB_W.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-Knr0oHAF5TcSPRxPfGl:bj7tayn)*

**Comment by sherm1** [comment]
Thanks, Alejandro. I realized I need to add a section on shifting frames so that the "Pb" stuff shows up somewhere. Doing that now. I want to keep this strictly about notation -- I'm not going to put in anything about *how* to differentiate vectors in odd frames, just how to write them down if you did it. This notation should work for any multibody quantities for which we can take derivatives, I think, not just 3d vectors. Works on spatial vectors we know, but should also be fine for rotation matrices and transforms, right? (And I would hope we can extend it to partials but I'm not sure.) Will respond to your comments along with Pb stuff.  

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-Knr22e9_gPx5HVuufao:b-yxixu3)*

**Comment by sherm1** [comment]
Ready for another round, @amcastro-tri. I added the offset frame section and responded to your comments. PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knqxu5YQigwKTSIiPFY:-Knr9W8488ioEOlQA-GR:b-qlrdz9) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L314)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

A few comments:
 1. I would say "Time Derivatives". Derivatives alone could signify gradients.
 2. I would introduce the topic first for 3D vectors, for which the simple "transport theorem" apply (and then you can reference `drake::math::ConvertTimeDerivativeToOtherFrame()`) and then, I would say that the time derivative of a spatial vector is the time derivative of each 3D vector component separately for which the transport theorem applies.
 3. Maybe this section could be titled "Time Derivatives" and then have a subsection for 3D vectors and a small section for spatial vectors? (for which everything said in the 3D vectors section can be applied to each component separately)
</blockquote></details>

Done. (Point 1)
2. This is just about notation -- I don't want to discuss at all *how* one differentiates these quantities; just how to name the results. Also I don't want any references *from* this document *to* the code; this should stand alone (for example, the driving guys in Ann Arbor were using it).
3. I changed the title but the notation applies equally to all multibody quantities for which time derivatives make sense. There is nothing special about 3d vectors.

---

*[drake/multibody/multibody_doxygen.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqyiXX37vCkVuaPesm:-KnrAfpUUegd9f4DWIrM:b-rsgn2s) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L324)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

For a vector I would use a lower case letter, not upper case. Why not just `v` as a generic vector? Also, I'd say these are 3D vectors.
</blockquote></details>

I clarified that these are intended to be *vector-containing* multibody quantities, not vectors. And in keeping with the ongoing notation in this document I denote arbitrary quantities "Q" so that they can include vectors, spatial vectors, rotation matrices, transforms, etc. I don't see a need to call out 3d vectors separately although that could be a good way to introduce a document on *how* to differentiate vector quantities. PTAL

---

*[drake/multibody/multibody_doxygen.h, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzoEdqnW0qbBhl8vM:-KnrCSO4XRCOfJv9JPR9:b-m77ub7) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L325)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would add that in code comments we use the operator `DtE(v)` to represent the time derivative in frame E of a vector v.
</blockquote></details>

Done. Still using Q but mentioned comments here. There is already a section below with more info about writing comments. I had to change the frame name because "F" is one of those missing Unicode superscripts! PTAL

---

*[drake/multibody/multibody_doxygen.h, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knr-0w5SmuA5UurmR6b:-KnrDrxSefCJjBDwwWNx:b4vzqm4) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L332)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would here add the math to be specific like: "i.e DtA(v_E) has no meaning, [DtA(v)]_E is the correct quantity."
</blockquote></details>

Done. Added in the next paragraph.

---

*[drake/multibody/multibody_doxygen.h, line 339 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzO_qOPZSduAuNceu:-KnrF0vXXr1-m61DFOtH:b3rkd92) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L339)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, Why the switch to W? why not to keep using E for the expressed-in frame for consistency?
</blockquote></details>

I didn't want to imply that the final frame had to match the quantity frame. Now I've switched it to a more-generic frame F so it doesn't mention World. PTAL

---

*[drake/multibody/multibody_doxygen.h, line 341 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzIkz_Safir4-sQ5u:-KnrFDS7uF-xxo9sKP9P:bekq30w) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L341)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, A_PB_W.
</blockquote></details>

Done. A_PB_F

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-KnrIVocCndg53x3KjGK:b8ock0r)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/multibody_doxygen.h, line 325 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqzoEdqnW0qbBhl8vM:-KnrIzM7pcIg-ILj1wnu:b-nzrvwy) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L325)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. Still using Q but mentioned comments here. There is already a section below with more info about writing comments. I had to change the frame name because "F" is one of those missing Unicode superscripts! PTAL
</blockquote></details>

(see last sentence of this paragraph, and then the comment paragraph below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483)*

**Comment by amcastro-tri** [comment]
Thanks for writing this down @sherm1. We'll have to ask Paul if this notation actually makes sense for things like rotation matrices. I'd say no, in the same way for say, a generalized coordinate `q(t)`, you would not say `DtA(q)`.
Anyways, :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knt4h51V6u1St0qFUKb:-Knt4h51V6u1St0qFUKc:b-jboup5) (no related file):*
>  Works on spatial vectors we know, but should also be fine for rotation matrices and transforms, right? 

I was gonna just comment on that. I'd so no? what would it mean to do DtW(X_AB)? or even DtW(X_WB)? I think these concepts only work for things that are invariant (a tensor theory term), independent of the particular coordinate system you choose to express them in. In the case of transforms they are intimately related to the coordinate systems they transform. I see a transform or rotation matrix just as a function of time into ℝ³ˣ³ (or ℝ⁴ˣ⁴). Anyways, I won't hold up this PR on this (that we might discuss with Paul later) as long as it doesn't explicitly mention transforms for now.

---

*[drake/multibody/multibody_doxygen.h, line 314 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knqxu5YQigwKTSIiPFY:-Knt5nVvm6tXfNfOpO0q:b8xzuta) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done. (Point 1)
2. This is just about notation -- I don't want to discuss at all *how* one differentiates these quantities; just how to name the results. Also I don't want any references *from* this document *to* the code; this should stand alone (for example, the driving guys in Ann Arbor were using it).
3. I changed the title but the notation applies equally to all multibody quantities for which time derivatives make sense. There is nothing special about 3d vectors.
</blockquote></details>

I agree, I looked at this with the wrong eye last night. I realized this morning that what you tried to do is to document the Dt() operator and no how it transforms. Well, exactly what you said at the top :-) Good to see we agree at least.

---

*[drake/multibody/multibody_doxygen.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqyiXX37vCkVuaPesm:-Knt6DLw_BQHTpTDmUNP:b-17ksf2) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L324)):*
> rotation matrices, transforms, 

I am not sure those belong here though.... Paul may know I'm sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-:-Knt71xjpOeOoEMPUFrY:b-5o87dz)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-Knt4h51V6u1St0qFUKb:-Kntj59JfHrtbuYRAa1k:bqyihys) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

>  Works on spatial vectors we know, but should also be fine for rotation matrices and transforms, right? 

I was gonna just comment on that. I'd so no? what would it mean to do DtW(X_AB)? or even DtW(X_WB)? I think these concepts only work for things that are invariant (a tensor theory term), independent of the particular coordinate system you choose to express them in. In the case of transforms they are intimately related to the coordinate systems they transform. I see a transform or rotation matrix just as a function of time into ℝ³ˣ³ (or ℝ⁴ˣ⁴). Anyways, I won't hold up this PR on this (that we might discuss with Paul later) as long as it doesn't explicitly mention transforms for now.

</blockquote></details>

I looked through to make sure it doesn't claim anything about differentiating transforms. I will discuss with Paul later, but I think the notation is usable for rotations and transforms since they are built from vectors. (The usual time derivative of a rotation matrix R_AB is w_AB x R_AB, columnwise.) So I guess you could call that DtA(R_AB) and you *could* differentiate in another frame (not sure if that every makes sense though).

---

*[drake/multibody/multibody_doxygen.h, line 324 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6483#-KnqyiXX37vCkVuaPesm:-KntkeZWh3K5CSK4JHLm:bycthx8) ([raw file](https://github.com/robotlocomotion/drake/blob/9b22ba3335c1611ee4d001f820f186d81db25352/drake/multibody/multibody_doxygen.h#L324)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> rotation matrices, transforms, 

I am not sure those belong here though.... Paul may know I'm sure.

</blockquote></details>

I won't make any claims about those here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6483)*

**Comment by sherm1** [comment]
Override merge for doc-only changes.

**Pull request merged**
