### PR TITLE
disable the rotation_constraint_limit_test on Mac

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5592)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-ninja-continuous-release please
@drake-jenkins-bot mac-clang-ninja-continuous-debug please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqqZ2qHvrxSwe1Oqq0:b-oyw8x3)*

**Comment by hongkai-dai** [comment]
@jwnimmer-tri for both review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqqknR7BR-w3AWhGLt:b83azde)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  mac-clang-continuous-debug please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqqyrE2Swy6M7CcBnR:b-j5o3eg)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental-debug please.
@drake-jenkins-bot mac-clang-ninja-experimental-release please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-Kfqr6Ch5S6G4uRtOWmw:b-dw0qlu)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqrKuuPWtaYg_PKFj0:b-2uekdi)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-experimental please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqrXM5Uc49bbui_a4Y:b-ixvtlv)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-KfqsZk9X-Z4JxKKL5Ve:bjwebpu)*

**Comment by liangfok** [comment]
I confirm that `rotation_constraint_limit_test` did not run here:

https://drake-cdash.csail.mit.edu/viewTest.php?onlypassed&buildid=483209

Thus, :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-Kfs18UG7nSbOmuQ0R0W:b-trlif8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-:-Kfs2Ku3UW2su7ffQlkh:bnfp4nl)*

**Comment by soonho-tri** [comment]
*[drake/solvers/test/CMakeLists.txt, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-Kfs2V4_-agH8uHxaZmG:-Kfs2V4_-agH8uHxaZmH:b-h7t5p4) ([raw file](https://github.com/robotlocomotion/drake/blob/4261f585e3c3df42bbb2ce11522f0b957f75c179/drake/solvers/test/CMakeLists.txt#L85)):*
> ```CMake
> if (gurobi_FOUND)
>   if(NOT APPLE)
> 	  drake_add_cc_test(rotation_constraint_limit_test)
> ```

Oops. @hongkai-dai , could you remove these `TAB` in your next PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/CMakeLists.txt, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-Kfs2V4_-agH8uHxaZmG:-Kfs31bSZg4r89giTz2D:bt1x36r) ([raw file](https://github.com/robotlocomotion/drake/blob/4261f585e3c3df42bbb2ce11522f0b957f75c179/drake/solvers/test/CMakeLists.txt#L85)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Oops. @hongkai-dai , could you remove these `TAB` in your next PR?
</blockquote></details>

Sure, will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592)*

**Comment by liangfok** [comment]
*[drake/solvers/test/CMakeLists.txt, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5592#-Kfs2V4_-agH8uHxaZmG:-Kfs3R3ZvJVcq00UXxTD:bfhtgzr) ([raw file](https://github.com/robotlocomotion/drake/blob/4261f585e3c3df42bbb2ce11522f0b957f75c179/drake/solvers/test/CMakeLists.txt#L85)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sure, will do.
</blockquote></details>

Heh. I saw the tabs but figured they weren't a style guide violation since there is no style guide for CMakeLists.txt, which is why I didn't leave a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5592)*

**Pull request merged**
