### PR TITLE
Parse joints actuation for MBP.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Adds joint actuators to an MBP model by default unless a user says `<effort>0</effort>` on the joint limits.
That is ` <effort>0</effort>` means an un-actuated joint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@avalenzu for feature review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799#-:-LCFzbxUDB3U6lpd9WK_:bxshoqm)*

**Comment by amcastro-tri** [comment]
cc'ing @nkoenig

**Comment by amcastro-tri** [comment]
+@avalenzu (sry for forgetting the `+`)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799#-:-LCZ6RrBCjUCa7xdU0sQ:bdw1w5h)*

**Comment by avalenzu** [comment]
:lgtm:. +@sammy-tri  for platform review.

---

Reviewed 7 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[examples/multibody/acrobot/run_lqr.cc, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8799#-LCZ4v7x9K4CFcHtVq9z:-LCZ4v7x9K4CFcHtVqA-:b-s6uqz8) ([raw file](https://github.com/robotlocomotion/drake/blob/24fffc37984d26a43d24aaef5c800abbc556bbe3/examples/multibody/acrobot/run_lqr.cc#L61)):*
> ```cpp
>   // Therefore we create a new model that meets this requirement. (a model
>   // created along with a SceneGraph for simulation would also have input ports
>   // to interact with that SceneGraph).
> ```

BTW, should there be a `TODO` in `LinearQuadraticRegulator()` to relax this requirement? Or even an issue?

---

*[examples/multibody/acrobot/run_lqr.cc, line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8799#-LCZ5EeM9HupBCDUIMmX:-LCZ5EeM9HupBCDUIMmY:b-mdhqle) ([raw file](https://github.com/robotlocomotion/drake/blob/24fffc37984d26a43d24aaef5c800abbc556bbe3/examples/multibody/acrobot/run_lqr.cc#L113)):*
> ```cpp
>   // Add gravity to the model.
>   acrobot.AddForceElement<UniformGravityFieldElement>(
>       -9.81 * Vector3<double>::UnitZ());
> ```

BTW, I don't anticipate Earth gravity changing much in the future, but if we suddenly decided to use another digit of precision for it, we'd have to change a lot of spots in the code. Consider adding a static `earth_gravity()` method to `UniformGravityElement` in the future.

---

*[multibody/benchmarks/acrobot/acrobot.sdf, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8799#-LCZ6IJyDY8lrVgjHetw:-LCZ6IJyDY8lrVgjHetx:bp59k1g) ([raw file](https://github.com/robotlocomotion/drake/blob/24fffc37984d26a43d24aaef5c800abbc556bbe3/multibody/benchmarks/acrobot/acrobot.sdf#L9)):*
> ```
>       
>       <pose>0 0.15 0 0 0 0</pose>
> ```

BTW, wouldn't all the elements of the pose need to be zero for this to be true? Maybe mention that the Y-axis offset is for visualization purposes only.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799#-:-LCZ7KCl73-yQk6erbG-:bkl779t)*

**Comment by amcastro-tri** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/multibody/acrobot/run_lqr.cc, line 61 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8799#-LCZ4v7x9K4CFcHtVq9z:-LCdA4Ao1bZ-5CpB6Hiu:b31atnn) ([raw file](https://github.com/robotlocomotion/drake/blob/24fffc37984d26a43d24aaef5c800abbc556bbe3/examples/multibody/acrobot/run_lqr.cc#L61)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, should there be a `TODO` in `LinearQuadraticRegulator()` to relax this requirement? Or even an issue?
</blockquote></details>

BTW what would that even mean? that is, if your plant has two input ports, what would `LinearQuadraticRegulator()` do? fix the other input port? with what values? does that even make sense? I believe the requirement is correct but correct me if I'm wrong.

---

*[multibody/benchmarks/acrobot/acrobot.sdf, line 9 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8799#-LCZ6IJyDY8lrVgjHetw:-LCdBytb1IM-4dNFybeW:b6wnma2) ([raw file](https://github.com/robotlocomotion/drake/blob/24fffc37984d26a43d24aaef5c800abbc556bbe3/multibody/benchmarks/acrobot/acrobot.sdf#L9)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, wouldn't all the elements of the pose need to be zero for this to be true? Maybe mention that the Y-axis offset is for visualization purposes only.
</blockquote></details>

BTW. I updated the comment. However, if we actually were interested in the reaction forces at the joints, that pose would have an effect, it's not only visual. I see your point though, but since I am trying to replicate the old Drake demos, I'll leave it like this with a clarifying comment per your observation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8799#-:-LCdMUsI8HfnzLKNAZpC:bnfp4nl)*

**Pull request merged**
