### PR TITLE
[Dev-only] Add protobuf messages for pick-and-place config.

### PR DESCRIPTION
**Pull request by avalenzu**
This PR provides functions that parse text-format protobuf files into the pick-and-place configuration structs added in #7437. These will be used in subsequent `dev`-only PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7466)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@siyuanfeng-tri (since you've worked with protobuf config files in the past). Sorry for the length!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-KyrCnJP415UCq9MsQpZ:b1qqbfv)*

**Comment by siyuanfeng-tri** [comment]
High level comments, can you doc in the .proto file which fields are mandatory and what assumptions they hold? otherwise :lgtm: 
I didn't look at the test super carefully though. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTH7SxMFjfWNgtwVf:-KyrTH7TVkn7Brv720iW:bqzdkvn) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L3)):*
> ```protobuf
> syntax = "proto3";
> 
> package drake.examples.kuka_iiwa_arm.pick_and_place.proto;
> ```

BTW i don't really know if proto is the best package name, maybe confi? or something similar? 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrXgWIpWc8QVhO16AB:-KyrXgWIpWc8QVhO16AC:b-g93gf6) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L15)):*
> ```protobuf
> // Next ID: 3
> message OptitrackInfo {
>     int32 id = 1;
> ```

id should be unique right? 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrX7YRi_Bml_i-O_dA:-KyrX7YRi_Bml_i-O_dB:bja8et1) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L24)):*
> ```protobuf
>     // Path to the model file for simulation (relative to DRAKE_RESOURCE_ROOT).
>     string simulation_model_path = 1;
>     // Path to the model file for planning (relative to DRAKE_RESOURCE_ROOT).
> ```

can you add a comment saying if not specified defaults to sim? 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTiljXcWQLtMhN17G:-KyrTilkBPVTpoXkkOAn:b5j6xrw) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L56)):*
> ```cpp
>   DRAKE_THROW_UNLESS(configuration.model().find(model_instance.name()) !=
>                      configuration.model().end());
>   return configuration.model().at(model_instance.name());
> ```

BTW I think if you just do .at it would throw if the map doesn't have it. 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrUIIERhuOz7rhH0Dw:-KyrUIIERhuOz7rhH0Dx:b-odefa8) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L77)):*
> ```cpp
>     std::vector<Isometry3<double>>* poses) {
>   DRAKE_DEMAND(poses != nullptr);
>   std::transform(models.cbegin(), models.cend(), std::back_inserter(*poses),
> ```

BTW is there any advantages here to use transform rather than a for loop? just curious. 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVPShp_NUI8228GIC:-KyrVPShp_NUI8228GID:btx2i75) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L132)):*
> ```cpp
> 
>   // Extract target dimensions
>   WorldSimTreeBuilder<double> tree_builder;
> ```

It's not clear to me why you are using a worl sim tree builder here.. Why not just make a rbt and load the model? 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrV4gyVtG4lZlM81f0:-KyrV4gyVtG4lZlM81f1:bm8rjwc) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L140)):*
> ```cpp
>   auto target = tree_builder.Build();
>   Vector3<double> max_corner{-std::numeric_limits<double>::infinity() *
>                              Vector3<double>::Ones()};
> ```

BTW I think you can do Vector3d::Constants

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVu8754ZELPG-zqUv:-KyrVu8754ZELPG-zqUw:b-hdyhn4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L165)):*
> ```cpp
> pick_and_place::PlannerConfiguration ParsePlannerConfigurationOrThrow(
>     const std::string& filename, TaskIndex task_index) {
>   pick_and_place::PlannerConfiguration planner_configuration;
> ```

not used?

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVs9FSLu4Zq9sUVte:-KyrVs9FSLu4Zq9sUVtf:b-hdyhn4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L184)):*
> ```cpp
>     const std::string& filename, const std::string& end_effector_name,
>     RobotBaseIndex robot_index, TargetIndex target_index) {
>   pick_and_place::PlannerConfiguration planner_configuration;
> ```

not used?

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVys2Y838V043c2XA:-KyrVys2Y838V043c2XB:b-hdyhn4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L200)):*
> ```cpp
> std::vector<pick_and_place::PlannerConfiguration>
> ParsePlannerConfigurationsOrThrow(const std::string& filename) {
>   pick_and_place::PlannerConfiguration planner_configuration;
> ```

not used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-Kyr_MDCwDqFESJkkG4b:bffanhv)*

**Comment by avalenzu** [comment]
Addressed comments. @siyuanfeng-tri could you take a look at the comments in the `pick_and_place_configuration.proto` and see if they're satisfactory?

---

Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTH7SxMFjfWNgtwVf:-KyvMcBHgXZHd25eAwSa:b-ah27qu) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L3)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i don't really know if proto is the best package name, maybe confi? or something similar? 
</blockquote></details>

I'm going to stick with `pick_and_place::proto` as the namespace for protobuf messages in the pick-and-place demo.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrXgWIpWc8QVhO16AB:-Kyv58sS46tRXQu78DdY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L15)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

id should be unique right? 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrX7YRi_Bml_i-O_dA:-KyvMmyiXYGR4vwp0niJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration.proto#L24)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you add a comment saying if not specified defaults to sim? 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTiljXcWQLtMhN17G:-Kyv4Hj29qaqNlx_5pkm:bgn62l4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L56)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW I think if you just do .at it would throw if the map doesn't have it. 
</blockquote></details>

True. @ericcousineau-tri , would that be preferable?

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrUIIERhuOz7rhH0Dw:-Kyv2kiGSUxKUqjfwnBL:b-e22flj) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L77)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW is there any advantages here to use transform rather than a for loop? just curious. 
</blockquote></details>

Not from a performance standpoint that I'm aware of. I like it for cases like this where it lets you create one vector base on another without messing around with indices.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVPShp_NUI8228GIC:-Kyv0zWpYph6NBrMTovV:bewwo92) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L132)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

It's not clear to me why you are using a worl sim tree builder here.. Why not just make a rbt and load the model? 
</blockquote></details>

I didn't want to have to think about SDF vs URDF. `WorldSimTreeBuilder` already has all that logic.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 140 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrV4gyVtG4lZlM81f0:-Kyv2bven4-TGM-KU6M7:b6eg241) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L140)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW I think you can do Vector3d::Constants
</blockquote></details>

Nice. Thanks.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVu8754ZELPG-zqUv:-Kyv1a5edLlaxnLqg7_l:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L165)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

not used?
</blockquote></details>

Removed.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVs9FSLu4Zq9sUVte:-Kyv1aPw9LhMLMpHhA3V:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L184)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

not used?
</blockquote></details>

Removed.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrVys2Y838V043c2XA:-Kyv1af4MfYLjydT2qEv:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L200)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

not used?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-KyvO5or9VvOshABGfyz:b-yayyia)*

**Comment by avalenzu** [comment]
+@ericcousineau-tri for platform review. Note that all files in this PR are in a `dev` directory.

---

Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-KyvOGfUY5VehlVs590h:bgl5akn)*

**Comment by EricCousineau-TRI** [comment]
Giving :lgtm: as this is `dev/` code and has passed feature review.

---

Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-KyvOx37BkP3sqoAx_74:b-dcyd4x)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTiljXcWQLtMhN17G:-KyvP6WSleZzI38ZcQiV:beqm07q) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L56)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

True. @ericcousineau-tri , would that be preferable?
</blockquote></details>

Yup, sounds good. You could remove the `DRAKE_THROW_UNLESS` as it's redundant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466)*

**Comment by avalenzu** [comment]
Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-KyrTiljXcWQLtMhN17G:-KyvPIWUPaM-xLGSWUme:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f6773241adb9095869b62ab60e728d779b5e34d/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_configuration_parsing.cc#L56)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yup, sounds good. You could remove the `DRAKE_THROW_UNLESS` as it's redundant.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466)*

**Comment by avalenzu** [comment]
Woah ... 

---

Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466#-:-KyvQNbD621Ld8rjAJuG:b-26cnte)*

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake-ci/wiki/reviewable.io-review-completion-condition has the full recipe, FWIW.

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7466)*

**Pull request merged**
