### PR TITLE
[doc] Use ™ on MOSEK and always capitalize it

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This changes Drake's published documentation and API help to follow the preferred trademark spelling. Various buried mentions in our private source files are unchanged.

For the website, automatically hyperlink ™ to a trademarks page.

Towards #16439.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16576)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16576)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16576#-:-MvuOk6p1keVEXiYHbIj:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16576)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[tools/install/check_licenses.bzl, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16576#-MvyaD_o8eA8vOgpZWTg:-Mvyrral1niapk73fB69:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/1fcaf32aee9c01ee8930b6391d3b90c5cb3808d1/tools/install/check_licenses.bzl#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nothing functional.  By adding them, I was trying to indicate that these are Bazel labels (ala `deps = ["@ccd"]` in a BUILD file), not the actual project's names.
</blockquote></details>

Thanks!

**Pull request merged**
