### PR TITLE
Suppressing Data Races In MOSEK

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Relevant build : https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=130522

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6143)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-nightly-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot  linux-xenial-gcc-bazel-nightly-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-:-KklKzKGNKE5oxUEajYU:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-tsan please

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/tsan.supp, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkm87-IDG1ipEJFgqRi:-Kkm87-IDG1ipEJFgqRj:biu4q0p) ([raw file](https://github.com/robotlocomotion/drake/blob/4ba8f06f6200f2b6fe4950d209a355a7ce936dc2/tools/tsan.supp#L18)):*
> ```
> # data race (libiomp5.*) in __kmp_launch_monitor
> race:__kmp_launch_monitor
> ```

It is not clear to me from the comments here whether these additions are are (1) false positives that we will never care about, (2) true positives that we can ignore for some reason, or (3) true positives that we need to suppress in order to turn on CI but would prefer to fix soon.

If course that's true for the other stuff in this file and other related files, but its still defective.  Suppressing errors should be done with clear purpose so that all future developers can (re)assess the merit.  Usually that means either a full paragraph comment for each one, or a link to a github issue that explains in more detail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/tsan.supp, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkm87-IDG1ipEJFgqRi:-KkmByR-x6kiRxs3BwV5:b-a6y8qx) ([raw file](https://github.com/robotlocomotion/drake/blob/4ba8f06f6200f2b6fe4950d209a355a7ce936dc2/tools/tsan.supp#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is not clear to me from the comments here whether these additions are are (1) false positives that we will never care about, (2) true positives that we can ignore for some reason, or (3) true positives that we need to suppress in order to turn on CI but would prefer to fix soon.

If course that's true for the other stuff in this file and other related files, but its still defective.  Suppressing errors should be done with clear purpose so that all future developers can (re)assess the merit.  Usually that means either a full paragraph comment for each one, or a link to a github issue that explains in more detail.
</blockquote></details>

Could be (1) or (2). These are buried deep in MOSEK, such that they are not fixable even if they are (2).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/tsan.supp, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkm87-IDG1ipEJFgqRi:-KkmDL4tzwdierjqSbzY:b-5lstdz) ([raw file](https://github.com/robotlocomotion/drake/blob/4ba8f06f6200f2b6fe4950d209a355a7ce936dc2/tools/tsan.supp#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Could be (1) or (2). These are buried deep in MOSEK, such that they are not fixable even if they are (2).
</blockquote></details>

Note also https://reviews.llvm.org/D13072.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jwnimmer-tri** [comment]
*[tools/tsan.supp, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkm87-IDG1ipEJFgqRi:-Kkrwb1a42HXL12wYAZj:bmj97xw) ([raw file](https://github.com/robotlocomotion/drake/blob/4ba8f06f6200f2b6fe4950d209a355a7ce936dc2/tools/tsan.supp#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Note also https://reviews.llvm.org/D13072.
</blockquote></details>

That is good info, but needs to be provided in comments within this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/tsan.supp, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkm87-IDG1ipEJFgqRi:-KkuZCh3GvFvMByhcB0o:baet4he) ([raw file](https://github.com/robotlocomotion/drake/blob/4ba8f06f6200f2b6fe4950d209a355a7ce936dc2/tools/tsan.supp#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That is good info, but needs to be provided in comments within this file.
</blockquote></details>

Indeed. @m-chaturvedi?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/tsan.supp, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkuzy84svCpTJ4vf8Qj:-Kkuzfp9zSeEUL7q0Abo:bj673qg) ([raw file](https://github.com/robotlocomotion/drake/blob/b182014c088ccc87acbad6b10e36e964dede0a20/tools/tsan.supp#L10)):*
> ```
> mutex:lc_checkout
> 
> # The OpenMP runtime bundled with MOSEK has not been generated with TSan support on. https://reviews.llvm.org/D13072
> ```

Comment applies to all the `*:_kmp_*` entries. Block them together and add one comment at the start of the block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by m-chaturvedi** [comment]
*[tools/tsan.supp, line 10 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-Kkuzy84svCpTJ4vf8Qj:-Kkv1anzDQIzrIrlCmqE:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/b182014c088ccc87acbad6b10e36e964dede0a20/tools/tsan.supp#L10)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Comment applies to all the `*:_kmp_*` entries. Block them together and add one comment at the start of the block.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6143#-:-Kkv2z2dAVoNgaIa53aH:bnfp4nl)*

**Pull request merged**
