### PR TITLE
[render_vtk] Nerf a few test cases on macOS

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #18327. See #19424 for the tracking issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19425)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review, please.  Mostly I'm just asking you to vet the premise that we should disable this few test cases (with a tracking issue) in order to move Ventura into Production.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19425#-:-NVjar2s-qLKX0C4-_dh:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`geometry/render_vtk/BUILD.bazel` line 116 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19425#-NVjaa7D0W6PxukHR52n:-NVjaa7E7CPyL_wJUkTC:b-wfcdij) ([raw file](https://github.com/RobotLocomotion/drake/blob/26bc72634c06879e1fd76073e39a66217d471709/geometry/render_vtk/BUILD.bazel#L116)):*
> ```Starlark
>                 "RenderEngineVtkTest.HorizonTest",
>                 "RenderEngineVtkTest.SphereTest",
>                 "RenderEngineVtkTest.TerrainTest",
> ```

BTW the experimental job on this PR is now failing on `RenderEngineVtkTest.EllipsoidTest` and `RenderEngineVtkTest.MeshTest` - might need to extend this list?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19425)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`geometry/render_vtk/BUILD.bazel` line 116 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19425#-NVjaa7D0W6PxukHR52n:-NVjg_LA4nvDeX__Cctd:b-r0tdok) ([raw file](https://github.com/RobotLocomotion/drake/blob/26bc72634c06879e1fd76073e39a66217d471709/geometry/render_vtk/BUILD.bazel#L116)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW the experimental job on this PR is now failing on `RenderEngineVtkTest.EllipsoidTest` and `RenderEngineVtkTest.MeshTest` - might need to extend this list?
</blockquote></details>

Yeah, it's a bit of a whack-a-mole.  Every time I nerf one test another one starts failing.  I'm hoping to reach a fixed point prior to disabling *all* of the tests.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

Note that the CI failure in mac-arm-ventura-clang-bazel-experimental-release doesn't indicate problem with this PR. The test case changed in this PR is passing in that build. It shows that one other test case is still failing as we work to spin up Ventura.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform w/ small BTW

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19425#-:-NVjukldDYHMJdvgYHWw:b-6dnq72)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`geometry/render_vtk/BUILD.bazel` line 107 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19425#-NVjudxX79BHVPrgl2PO:-NVjudxX79BHVPrgl2PP:b-al90m) ([raw file](https://github.com/RobotLocomotion/drake/blob/d0368299d882d8e10b0f7542c67d134a58802856/geometry/render_vtk/BUILD.bazel#L107)):*
> ```Starlark
>     name = "internal_render_engine_vtk_test",
>     args = select({
>         # TODO(#19424) Disable test cases that break on Mac M1 CI.
> ```

BTW Given this TODO, should this be reworded to "Should re-enable test cases [...]"?

**Pull request merged**
