### PR TITLE
[doc] Add more release instructions for Drake-owned externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Per #15673.

Also add more checklist items for release notes wordsmithing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15780)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

If you would be so kind, once this new text is approved, please try _doing_ the two new releases (optitrack-driver, styleguide) implied by this change on the Drake=v0.34.0 revisions.  That will confirm that someone besides me knows how to do this.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15780#-:-MjjHDGC-2DoKfGa57Kj:b-7vdkkg)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[doc/_pages/release_playbook.md, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15780#-MjjGbX11pvD8KB-2hG8:-MjjGbX11pvD8KB-2hG9:b49aam0) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ba0e7307d842929525b86072413b92883a33c5/doc/_pages/release_playbook.md#L62)):*
> ```Markdown
> 
> * Many commit messages can be cut down to their summary strings and used as-is.
> * Note geometry/optimization changes under the "Mathematical Program" heading,
> ```

s/changes under/changes belong under/

sidebar: can we teach the tooling to do this? Not blocking for this patch.
___
*[doc/_pages/release_playbook.md, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15780#-MjjGoBv6mTwHpD6qXIj:-MjjGoBv6mTwHpD6qXIk:b-in103x) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ba0e7307d842929525b86072413b92883a33c5/doc/_pages/release_playbook.md#L85)):*
> ```
> depdency
> ```
typo

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @rpoyner-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15780)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[doc/_pages/release_playbook.md, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15780#-MjjGbX11pvD8KB-2hG8:-MjjInkx5NrMMMvfXv3I:b2g5hk7) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ba0e7307d842929525b86072413b92883a33c5/doc/_pages/release_playbook.md#L62)):*
> s/changes under/changes belong under/

I changed the verb to better match my intent.

> sidebar: can we teach the tooling to do this? Not blocking for this patch.

Sure; any and all manual steps in the document are ripe for automation.  Capturing the rules in prose is just a finger in the dam.  Slightly better than posting review defects in every relntoes PR, but should probably be shored up even more in the future.
___
*[doc/_pages/release_playbook.md, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15780#-MjjGoBv6mTwHpD6qXIj:-MjjIjmDEbhztpv_v7Uf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e2ba0e7307d842929525b86072413b92883a33c5/doc/_pages/release_playbook.md#L85)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> depdency
> ```
typo
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15780)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15780)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by rpoyner-tri** [comment]
Styleguide done. As for optitrack, I seem to lack some relevant access bits.

**Pull request merged**
