### PR TITLE
[doc] Update Hydroelastic Contact User Guide

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Deepnote does not support attached images within the ipynb file (discussed in issue #19641), so we copy images from the hydroelastic tutorial to the user guide in this PR.  After it lands, another PR will change the tutorial to use images in this PR.

Additionally, add a list of examples and tutorials to the user guide. Plus, make a reference to 19320.

- Copy images from the hydroelastic tutorial
- Link to examples and tutorials
- Refer to SAP issue 19320 for Hunt-Crossley dissipation

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@mitiguy for feature review, please.

For simplicity, you can get my branch, for example,
```
git fetch DamrongGuoy copy_images_from_HydroTutorial_to_UserGuide
git checkout copy_images_from_HydroTutorial_to_UserGuide
```
Then, generate local doxygen:
```
bazel run //doc/doxygen_cxx:build -- --serve --quick drake.multibody
```
Then, it should print links like this:
```
  http://127.0.0.1:8000/doxygen_cxx/modules.html
```
After that, you can go to: http://127.0.0.1:8000/doxygen_cxx/group__hydroelastic__user__guide.html

See https://drake.mit.edu/documentation_instructions.html

Thank you for helping.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYV6wSjDtEKRni_nubR:b-a3wo4b)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
After this PR 19652 lands, I'll have the follow-up PR #19660 for the tutorial to use images in this PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYZBKJ91coL3WuIDLWn:b-q6xx04)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by mitiguy — COMMENTED** [review]
@DamrongGuoy   Looks good. Suggestions below. PTAL.

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYuAinV-I5ZsGXyV2bg:b-2f19nf)* status: 17 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtj1N_6GQKum6l_UTG:-NYtj1N_6GQKum6l_UTH:bhhql5c) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L27)):*
> ```objc
> Drake implements two models for resolving contact to forces: point contact and
> hydroelastic contact. See @ref hydro_appendix_a for a fuller discussion of the
> theory and practice of contact models. For notes on implementation status, see
> ```

BTW  Consider changing  hydro_appendix_c  to 
 hydro_appendix_examples_and_tutorials. 
Through years of using Latex, I frequently find good reason to add more appendices, split an appendix into two appendices, or reorder appendices.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYthS1j5gh4dEAF_ory:-NYthS1j5gh4dEAF_orz:b-1truz5) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L29)):*
> ```objc
> theory and practice of contact models. For notes on implementation status, see
> @ref hydro_appendix_b. For the list of examples and tutorials, see
> @ref hydro_appendix_c.
> ```

BTW  The new text seems redundant as it shows up as:
For the list of examples and tutorials, see Appendix C: Examples and Tutorials.

Perhaps change it to either:
For examples and tutorials, see @ref hydro_appendix_c.
-- which I think renders as   
For examples and tutorials, see Appendix C: Examples and Tutorials. 

or more simply:
Also see @ref hydro_appendix_c.
-- which I think renders as   
Also see Appendix C: Examples and Tutorials. 

or if you employ the previous renaming suggestion:
Also see @ref hydro_appendix_examples_and_tutorials.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtkWRKCGUZS3eK9z-l:-NYtkWRKCGUZS3eK9z-m:bh2fa9b) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L48)):*
> ```objc
> "compliant-hydroelastic" with tetrahedral meshes describing an
> internal pressure field or "rigid-hydroelastic" with triangle
> surface meshes and regarded as infinitely stiff.
> ```

BTW  I think the "and" is out of place.



_Suggestion:_
```objc
surface meshes that are regarded as infinitely stiff.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtm7C-BlTB-fIz6O42:-NYtm7C-BlTB-fIz6O43:b-jml0yb) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L54)):*
> ```objc
> @image html "multibody/hydroelastics/images/HydroelasticTutorialCompliantRigidOutsideInside800x669.jpg"
> 
> The figure below shows contact surface between a compliant-hydroelastic cylinder
> ```

BTW missing "a" or "the"



_Suggestion:_
```objc
The figure below shows a contact surface between a compliant-hydroelastic cylinder
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtmtz612EGf-HrqQY1:-NYtmtz612EGf-HrqQY2:bhykbeo) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L61)):*
> ```objc
> 
> As pictured below, two hydroelastic-compliant ellipsoidal bubble fingers are in
> contact with a rigid-hydroelastic cylindrical spatula handle.
> ```

BTW fingers -> grippers ?



_Suggestion:_
```objc
Pictured below, a rigid-hydroelastic cylindrical spatula handle is grasped by two hydroelastic-compliant ellipsoidal bubble grippers.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtnnAz5nTX7Uu_6PMv:-NYtnnAz5nTX7Uu_6PMw:bweyd8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L64)):*
> ```objc
> The contact surface between a compliant-hydroelastic geometry and a
> rigid-hydroelastic geometry is on the surface of the rigid-hydroelastic
> geometry.
> ```

BTW start with rigid_hydroelastic since it seems to be what sets to contact surface to be on the surface?



_Suggestion:_
```objc
The contact surface between the spatula handle's rigid-hydroelastic geometry and either gripper 
is on the <b>surface</b> of the rigid-hydroelastic geometry.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 659 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtpFyZEEVd134kgpb6:-NYtpFyZEEVd134kgpb7:bep8to6) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L659)):*
> ```objc
>   configuration.
> 
> @section hydro_appendix_c Appendix C: Examples and Tutorials
> ```

BTW Consider changing appendix name



_Suggestion:_
```objc
@section hydro_appendix_examples_and_tutorials Appendix C: Examples and Tutorials
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 661 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtvR7z1V0ot04Ta3TX:-NYtvR7z1V0ot04Ta3TY:b1fmiyo) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L661)):*
> ```objc
> @section hydro_appendix_c Appendix C: Examples and Tutorials
> - Example
>   [Rolling ball on a dinner plate on a floor]
> ```

BTW  In the associated readme.md, it seems the ball could be sliding (not necessarily rolling).



_Suggestion:_
```objc
  [Contact between a ball, dinner plate, and floor in C++]
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 664 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtvo6Q6sAoIIXh8LXG:-NYtvo6Q6sAoIIXh8LXH:b7t9iea) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L664)):*
> ```objc
>   (https://github.com/RobotLocomotion/drake/tree/master/examples/hydroelastic/ball_plate)
>   uses the hydroelastic contact model with a non-convex geometry loaded from
>   an SDFormat file of a dinner plate in C++.
> ```

BTW Some possible wordsmithing.



_Suggestion:_
```objc
  uses the hydroelastic contact model for a convex ball and non-convex dinner plate.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 667 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtyNfjArzDKJYs3nbx:-NYtyNfjArzDKJYs3nby:b4io10b) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L667)):*
> ```objc
> 
> - Example
>   [Ball and Paddle in Python]
> ```

BTW  Paddle is linguistically generous.



_Suggestion:_
```objc
  [Contact between a ball and paddle (box) in Python]
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 669 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtzP9dBtpczQoN0nh0:-NYtzP9dBtpczQoN0nh1:b-e8o5pg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L669)):*
> ```objc
>   [Ball and Paddle in Python]
>   (https://github.com/RobotLocomotion/drake/tree/master/examples/hydroelastic/python_ball_paddle)
>   is a simple example of using the hydroelastic contact model in Python.
> ```

BTW  Parallel wording for each example?



_Suggestion:_
```objc
uses the hydroelastic contact model for a ball on stationary paddle (box).
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 672 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu0TbE05OMuTgmkpbU:-NYu0TbF35KT8I2KFLlO:b-jdaz2c) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L672)):*
> ```objc
> 
> - Example
>   [Drop a bell pepper]
> ```

BTW Parallel wording for each example?



_Suggestion:_
```objc
 [Contact between a bell pepper, dinner bowl, and floor in Python]
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 674 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu0xM9AozSq7j2icff:-NYu0xMA6VYSycevrZ4o:b-hjwvog) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L674)):*
> ```objc
>   [Drop a bell pepper]
>   (https://github.com/RobotLocomotion/drake/tree/master/examples/hydroelastic/python_nonconvex_mesh)
>   uses non-convex meshes with the hydroelastic contact model in Python.
> ```

BTW Parallel wording? 



_Suggestion:_
```objc
  uses the hydroelastic contact model for a non-convex bell pepper in a non-convex dinner bowl.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 677 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu1Zgn8gZJ1HHMFjfK:-NYu1Zgn8gZJ1HHMFjfL:b-ebb4w0) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L677)):*
> ```objc
> 
> - Example
>   [Spatula Slip Control]
> ```

BTW Parallel wording?



_Suggestion:_
```objc
  [Slip control for a spatula handle between finger grippers in C++]
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 680 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu2-7A9TkxjI50Zxdu:-NYu2-7A9TkxjI50Zxdv:bb6ssg0) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L680)):*
> ```objc
>   (https://github.com/RobotLocomotion/drake/tree/master/examples/hydroelastic/spatula_slip_control)
>   uses the hydroelastic contact model with a robot gripper with compliant
>   bubble fingers and a spatula handle in C++.
> ```

BTW 



_Suggestion:_
```objc
  uses the hydroelastic contact model for a spatula handle between finger grippers.
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 683 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu9Ru00OmOCNB_fa7v:-NYu9Ru00OmOCNB_fa7w:b-u4q6uc) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L683)):*
> ```objc
> 
> - Tutorial
>   [Hydroelastic Contact: Basics]
> ```

BTW remove colon?



_Suggestion:_
```objc
  [Hydroelastic Contact Basics with Jupyter Python notebook]
```
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYuAHyG9W_9Fgf_WUTc:-NYuAHyG9W_9Fgf_WUTd:b-orsq0a) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L689)):*
> ```objc
>   It uses a compliant block dropped onto a rigid rectangular plate.
>   The below-left picture shows one frame of the block's contact with
>   the force as a red arrow and the torque as a blue arrow.
> ```

BTW wordsmithing?



_Suggestion:_
```objc
  shows how to simulate hydroelastic contact for a compliant block dropped on a rigid rectangular plate.
  The below-left picture shows one frame of the block's contact with
  the contact force as a red arrow and the contact torque as a blue arrow.
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtj1N_6GQKum6l_UTG:-NYyVGlg0y6u7gPvttBT:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L27)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  Consider changing  hydro_appendix_c  to 
 hydro_appendix_examples_and_tutorials. 
Through years of using Latex, I frequently find good reason to add more appendices, split an appendix into two appendices, or reorder appendices.
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYthS1j5gh4dEAF_ory:-NYyVzP30ZEMFA9mux9Y:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L29)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  The new text seems redundant as it shows up as:
For the list of examples and tutorials, see Appendix C: Examples and Tutorials.

Perhaps change it to either:
For examples and tutorials, see @ref hydro_appendix_c.
-- which I think renders as   
For examples and tutorials, see Appendix C: Examples and Tutorials. 

or more simply:
Also see @ref hydro_appendix_c.
-- which I think renders as   
Also see Appendix C: Examples and Tutorials. 

or if you employ the previous renaming suggestion:
Also see @ref hydro_appendix_examples_and_tutorials.




</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtkWRKCGUZS3eK9z-l:-NYyWD70DIDwQq9VuskO:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L48)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  I think the "and" is out of place.
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtm7C-BlTB-fIz6O42:-NYyWaA43DiMPcwbNdQS:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L54)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW missing "a" or "the"
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtmtz612EGf-HrqQY1:-NYyWvXO6zqiQ4jborQk:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L61)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW fingers -> grippers ?
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtnnAz5nTX7Uu_6PMv:-NYyXIMMDrP8sJI4moa4:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L64)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW start with rigid_hydroelastic since it seems to be what sets to contact surface to be on the surface?
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 659 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtpFyZEEVd134kgpb6:-NYyYNem2IvMqJV49Evw:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L659)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW Consider changing appendix name
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 661 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtvR7z1V0ot04Ta3TX:-NYyYe4t9qQw3JqDckGm:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L661)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  In the associated readme.md, it seems the ball could be sliding (not necessarily rolling).
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 664 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtvo6Q6sAoIIXh8LXG:-NYyYcbLDCW-vqyMB3m_:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L664)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW Some possible wordsmithing.
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 667 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtyNfjArzDKJYs3nbx:-NYyZ-nwCyXA8ZgL1uD9:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L667)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  Paddle is linguistically generous.
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 669 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYtzP9dBtpczQoN0nh0:-NYyZD_F4WsiHwM-ooc3:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L669)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  Parallel wording for each example?
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 672 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu0TbE05OMuTgmkpbU:-NYyZMjX3R6OoujCqFE3:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L672)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW Parallel wording for each example?
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 674 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu0xM9AozSq7j2icff:-NYyZaIt6KVnbuELHtgY:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L674)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW Parallel wording? 
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 677 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu1Zgn8gZJ1HHMFjfK:-NYyZi186NJSRpUeosRn:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L677)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW Parallel wording?
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 680 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu2-7A9TkxjI50Zxdu:-NYyZt9mDaL3QMf3LPBd:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L680)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW 
</blockquote></details>

Done. Thanks.
___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYuAHyG9W_9Fgf_WUTc:-NYy_S7Q44u9O-55tlhZ:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L689)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW wordsmithing?
</blockquote></details>

Done. Thanks.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/hydroelastics/hydroelastic_user_guide_doxygen.h` line 683 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-NYu9Ru00OmOCNB_fa7v:-NYybdoR0MuqUePlRJ6w:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/4c3b9a6829f80d7148f8299184b0cc4700b9f821/multibody/hydroelastics/hydroelastic_user_guide_doxygen.h#L683)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW remove colon?
</blockquote></details>

Done. Thanks.

**Review by mitiguy — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYyd-tt5VzCFRpIVVtF:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYyd9iAE-WfsNR3oqIQ:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652#-:-NYz2N-XBMXDwuGjmbwJ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),mitiguy

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19652)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),mitiguy

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy I just clicked the documentation deploy button, so in ~1 hour the new URLs will be available so you can start testing the real version of #19660.

**Comment by DamrongGuoy** [comment]
Thank you!  I'll wait for https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html and then update 19660.

**Pull request merged**
