### PR TITLE
Minor refactor on the pick and place example

### PR DESCRIPTION
**Pull request by naveenoid**
Enroute to spiral 3 of #5371. Breaking up the task into smaller chunks to be passed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5424)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@siyuanfeng-tri for feature review
+@sammy-tri for quick platform review

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_PTgCl_-nng5viKm_:-Ke_PTgCl_-nng5viKma:booc9q6) ([raw file](https://github.com/robotlocomotion/drake/blob/18ee2ccc46c710cba4366f864ce6735547ba04fd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc#L9)):*
> ```cpp
> //#include <lcm/lcm-cpp.hpp>
> 
> //#include "bot_core/robot_state_t.hpp"
> ```

dead includes 

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_PMHBCCNzlG6aLq6H:-Ke_PMHBCCNzlG6aLq6I:b-2c77in) ([raw file](https://github.com/robotlocomotion/drake/blob/18ee2ccc46c710cba4366f864ce6735547ba04fd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.h#L18)):*
> ```objc
> //#include "drake/lcmt_iiwa_status.hpp"
> 
> //#include "drake/lcmt_schunk_wsg_command.hpp"
> ```

people will complain about dead includes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-:-Ke_PiohI0lcLE8GC_rN:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
fyi. you don't need platform iff everything is in dev. it's automatic. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-:-Ke_PmjL_98DbXpOLvoQ:b-34j8fd)*

**Comment by sammy-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_gB_qA2OaW-b6asca:-Ke_gB_qA2OaW-b6ascb:b-g27p6f) ([raw file](https://github.com/robotlocomotion/drake/blob/e8e370dfa9a18c6f60eb0d24fb53335c03862c67/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc#L7)):*
> ```cpp
> #include <memory>
> 
> //#include <lcm/lcm-cpp.hpp>
> ```

Ok, I know we're in dev/, but we can probably at least remove the commented out headers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424)*

**Comment by naveenoid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_PTgCl_-nng5viKm_:-Ke_iBxfwulxqWHMTX9o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18ee2ccc46c710cba4366f864ce6735547ba04fd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc#L9)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

dead includes 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_gB_qA2OaW-b6asca:-Ke_iBG-9LIZtzjf5mPC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e8e370dfa9a18c6f60eb0d24fb53335c03862c67/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.cc#L7)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Ok, I know we're in dev/, but we can probably at least remove the commented out headers.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-Ke_PMHBCCNzlG6aLq6H:-Ke_iCnrkFh_gD_ekrjS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18ee2ccc46c710cba4366f864ce6735547ba04fd/drake/examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_common.h#L18)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

people will complain about dead includes. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424)*

**Comment by sammy-tri** [comment]
:lgtm: assuming this is a pure cut-and-paste job with no significant changes.  (I didn't read in detail).

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-:-Ke_kMWBP8bxK2Jig_OT:btu92av)*

**Comment by naveenoid** [comment]
yeap. Its simply reducing the stuff I need to replicate unnecessarily.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-:-Ke_ykBSQumnbFJcpdST:bqoypsc)*

**Comment by naveenoid** [comment]
Moving to squash-and-merge.

---

Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5424#-:-Kejg4tIyRo1B-JED-ok:bigsqua)*

**Pull request merged**
