### PR TITLE
set gurobi model parameters in the correct environment

### PR DESCRIPTION
**Pull request by rdeits**
This is necessary to actually pass parameters to gurobi (to do things like print console output, control tolerances, etc.). The gurobi FAQ entry 11 describes why this is necessary: http://www.gurobi.com/support/faqs

I'm open to suggestions about how to actually test this. I'm not sure how the mathematicalprogram testing framework works.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5337)

### CODE REVIEW

**Comment by rdeits** [comment]
+@hongkai-dai 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-:-Ke0dOP-R_7WsXZywaOi:b-e97kzc)*

**Comment by rdeits** [comment]
Thanks @gizatt for figuring this out.

**Comment by hongkai-dai** [comment]
Cool! Can you add a test on this? We have `gurobi_solver_test.cc`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-:-Ke0pKDXZ2YvSTNbOBEf:b-3ynutd)*

**Comment by RussTedrake** [comment]
instead of allocating a second env, could we have just moved the setters up to the top of the function (just after the terminal output is set to off by default)?

**Comment by rdeits** [comment]
No, check out the FAQ (`#11`) I linked to. Creating a model already allocates a copy of the environment. The only change is that now we're actually using that environment.

**Comment by RussTedrake** [comment]
in that case, then we should also move the initial set parameters call to use the new environment.  (it's doing nothing where it is)?

**Comment by rdeits** [comment]
I'm pretty sure it is working where it is (that's why I had no output to begin with). The problem was the other parameters were being set on the global env *after* creating the model's own copy. That's not the case here. 

But for consistency it probably is better to move it.

**Comment by rdeits** [comment]
@hongkai-dai I'll try

**Comment by rdeits** [comment]
(but given that I have no idea how to use gtest, this will take a while...)

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-:-Ke5tayKOvvrXzP0mgsX:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-:-Ke5tcGPtwcfqa6UK90m:bfvx2sg)*

**Comment by sherm1** [comment]
Platform review: one question, then :lgtm:.

---

Reviewed 5 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/inverse_kinematics_backend.cc, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-Ke6TrQMWyZqrRzIJWXQ:-Ke6TrQN0ZWWbxq5s-cE:bbb31uv) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe2ab7b12b5542fc1586c22d3a326aadb007013/drake/multibody/inverse_kinematics_backend.cc#L66)):*
> ```cpp
>     }
>     case SolutionResult::kInfeasible_Or_Unbounded: {
>       return 13;
> ```

BTW, why is this the same as `kInfeasibleConstraints`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-:-Ke6UNcokEteDw3PN0Hc:b-k3tfnr)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/inverse_kinematics_backend.cc, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-Ke6TrQMWyZqrRzIJWXQ:-Ke6VrdmDwR1eEMhpCfV:bjmi5s3) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe2ab7b12b5542fc1586c22d3a326aadb007013/drake/multibody/inverse_kinematics_backend.cc#L66)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, why is this the same as `kInfeasibleConstraints`?
</blockquote></details>

`kInfeasible_Or_Unbounded` is only used for Gurobi solver. Unless some solver option is specified, Gurobi does not differentiate whether the problem is infeasible or unbounded. In this specific case, the problem cannot be unbounded, since the cost for the inverse kinematics is a convex quadratic function.

This part of the code will be gone, as soon as we drop the MATLAB support. We will then return the solution result directly, instead of converting it to an integer like 13, 21, or 100.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/inverse_kinematics_backend.cc, line 66 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5337#-Ke6TrQMWyZqrRzIJWXQ:-Ke6WfJnIw-Y794XQaR-:bdac0mf) ([raw file](https://github.com/robotlocomotion/drake/blob/3fe2ab7b12b5542fc1586c22d3a326aadb007013/drake/multibody/inverse_kinematics_backend.cc#L66)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`kInfeasible_Or_Unbounded` is only used for Gurobi solver. Unless some solver option is specified, Gurobi does not differentiate whether the problem is infeasible or unbounded. In this specific case, the problem cannot be unbounded, since the cost for the inverse kinematics is a convex quadratic function.

This part of the code will be gone, as soon as we drop the MATLAB support. We will then return the solution result directly, instead of converting it to an integer like 13, 21, or 100.
</blockquote></details>

13 is the code used in MATLAB, to indicate that a problem is infeasible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5337)*

**Pull request merged**
