### PR TITLE
Shuffle CMakeLists.txt to partition matlab-specific code with comment delimiters

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A ~~third~~ _second_ portion of #3253.  Further commits in the PR train can be seen [here](https://github.com/jwnimmer-tri/drake/tree/the-great-matlab-relocation-of-aught-sixteen).

The purpose here is to make it machine-translatable to split a `CMakeLists.txt` in twain when we rip half of the code in a directory out into a new directory.  Reviewing the CMake edits alongside the code changes like this is mind-numbing, so it's important to pull this out first.  Relatedly, this also makes the upcoming matlab split more mergeable -- this PR gets the conflicts and interesting edits out of the way, so the subsequent PR is a rote relocation by script.

So not only should this PR review assess the correctness of the changes themselves, but it's an opportunity to assess any mis-categorized code (C++ shared vs matlab-only) as well.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3833)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
We should let #3681 merge first.

Also, I need to rework this to do _C++, Matlab, Both_ as the order, so that _Both_ code has all of its CMake prereqs at hand.

**Comment by jwnimmer-tri** [comment]
My plan is now to rework this PR to include the same changes to `util` (cherry-picking a patch already in the other PR), and get this one merged first.  That will at least make the future PRs avoid CMake hassles.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
-@jwnimmer +@david-german-tri for both reviews, please.

The changes should _only_ be:
 1. Adding special comment markers.
 2. Relocating CMakeLists code.
 3. Removing redundant if-else opening/closing lines.
 4. Removing win32 goop when it was easy and at hand.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUSLSY68nR7hRNDh5f1:b4wtkix)*

**Comment by david-german-tri** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSe_ONC4y3-LiqwDcM:-KUSe_OP5FPEQqYwjKqt:b-b3sg8z) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/CMakeLists.txt#L38)):*
> ```CMake
> add_subdirectory(frames)
> 
> # ==== Below this line is C++ and MATLAB joint code ====
> ```

META: consider s/joint/shared

---

*[drake/systems/plants/CMakeLists.txt, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSfthg52U_D-XJhY92:-KUSfthg52U_D-XJhY93:beyr20t) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/CMakeLists.txt#L79)):*
> ```CMake
> endif()
> if(drakeIK_SRC_FILES)
>   add_library_with_exports(LIB_NAME drakeIK SOURCE_FILES ${drakeIK_SRC_FILES})
> ```

drakeIK appears to be swigged for MATLAB.  That qualifies it as "joint code", right?

---

*[drake/systems/plants/test/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSgwsdeA60k7XjiU00:-KUSgwsdeA60k7XjiU01:b-uwkfjy) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/test/CMakeLists.txt#L103)):*
> ```CMake
> find_package(Bullet)
> if(BULLET_FOUND)
>   drake_add_cc_test(bullet_collision_zero_rad_sphere_test EXTENSION cpp)
> ```

This doesn't look MATLAB-specific.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSh4qd3ENxRawzXXsg:-KUSh4qd3ENxRawzXXsh:bp4zu3w) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/trajectories/CMakeLists.txt#L19)):*
> ```CMake
> find_package(Bullet)
> 
> if(BULLET_FOUND AND Matlab_FOUND)
> ```

now partially redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833)*

**Comment by david-german-tri** [comment]
I think this should have a second reviewer, but I'm not sure who to nominate.  

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUShSIPieaAfFLqOsBc:b-zbfw8b)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSe_ONC4y3-LiqwDcM:-KUSlN76JCxWrY5TaDZk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/CMakeLists.txt#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> META: consider s/joint/shared
</details>
Done.

---

*[drake/systems/plants/CMakeLists.txt, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSfthg52U_D-XJhY92:-KUSmJ6f4k83x47OnWYt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/CMakeLists.txt#L79)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> drakeIK appears to be swigged for MATLAB.  That qualifies it as "joint code", right?
</details>
Done.

---

*[drake/systems/plants/test/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSgwsdeA60k7XjiU00:-KUSlYtskYuhtz9mza15:b-8ghct0) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/test/CMakeLists.txt#L103)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This doesn't look MATLAB-specific.
</details>
It seemed of such minimal value (has no assertions) that I chose to put it in the trashbin.  It was the only user of several different model files that are otherwise only used by matlab code.

If you'd still rather I keep it in C++ land I'll do that.

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSh4qd3ENxRawzXXsg:-KUSlyhtKaPLAPDerKN8:b7upio8) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> now partially redundant
</details>
I'm not seeing why?  Do you mean I could collapse the two separate if-blocks into one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Sure.  I will assign a second reviewer once we wrap up your review cycle.

+@jwnimmer-tri placeholder in the meantime.

---

Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUSo27puZzFJp8CC6UA:b-v62ww7)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/test/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSgwsdeA60k7XjiU00:-KUTMjU1SImX2deddPCu:bbaio0v) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/test/CMakeLists.txt#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> It seemed of such minimal value (has no assertions) that I chose to put it in the trashbin.  It was the only user of several different model files that are otherwise only used by matlab code.
> 
> If you'd still rather I keep it in C++ land I'll do that.
</details>
Yeah, I think putting non-MATLAB stuff in MATLAB jail is pretty confusing.  From f2f, maybe delete?

---

*[drake/systems/trajectories/CMakeLists.txt, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSh4qd3ENxRawzXXsg:-KUTMpxkIYkToumxWmMF:b-26y4lh) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/trajectories/CMakeLists.txt#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I'm not seeing why?  Do you mean I could collapse the two separate if-blocks into one?
</details>
I'm just a lousy parser.  Sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUTNP8QWBaALOkYtBU8:bnfp4nl)*

**Comment by liangfok** [comment]
+@liangfok

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUTb6i69y_eOw4vEvQZ:b-2u70ip)*

**Comment by liangfok** [comment]
:lgtm: Just one minor issue.

---

Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/util/test/CMakeLists.txt, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUTeW8f80gjAId6sSwS:-KUTeW8f80gjAId6sSwT:bdtup7y) ([raw file](https://github.com/robotlocomotion/drake/blob/c4ce9d7f45b6cb745e309b07e14ef81a9d3ebb83/drake/util/test/CMakeLists.txt#L25)):*
> ```CMake
> if(Matlab_FOUND)
>   drake_add_mex(testQuatmex testQuatmex.cpp)
>   
> ```

BTW Spurious​ spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUTeqKUfNupjMo3vThe:bhybo73)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri since we've found a second reviewer.

---

Review status: 12 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/CMakeLists.txt, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUSgwsdeA60k7XjiU00:-KUUEGfrdvtn5elFI5Pm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c5b3ec8d73d09ecfab72f553ada821a6f66598/drake/systems/plants/test/CMakeLists.txt#L103)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yeah, I think putting non-MATLAB stuff in MATLAB jail is pretty confusing.  From f2f, maybe delete?
</details>
Done.

---

*[drake/util/test/CMakeLists.txt, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-KUTeW8f80gjAId6sSwS:-KUUEEhMYTn2Bs_TNCpc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4ce9d7f45b6cb745e309b07e14ef81a9d3ebb83/drake/util/test/CMakeLists.txt#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW Spurious​ spaces.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833#-:-KUUEK-8sNIwjuhewohR:bpze7fx)*

**Comment by liangfok** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3833)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Pull request merged**
