### PR TITLE
[solvers] Add PerspectiveQuadraticCost and include in GraphOfConvexSets cost options

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@hongkai-dai for feature review.

cc @RussTedrake @TobiaMarcucci

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679#-:-MwmeyklEF4lqtU0kuIO:b-b5nq9g)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

+@russtedrake would you like to do a platform review? I think we don't have a platform reviewer scheduled today, and hopefully this PR can get merged soon, in time for the paper submission?

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679#-:-MwmkBVuASmBErrpLRhg:b-d3odks)* status: LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

___
*[solvers/cost.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-MwmjM4R6KJYpOL6zsWU:-MwmjM4R6KJYpOL6zsWV:b-vauj7m) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.cc#L286)):*
> ```cpp
> }
> 
> void PerspectiveQuadraticCost::DoEval(
> ```

BTW, the DoEval does the same thing for the three scalar types. By rule of 3, you could consider to factor it out with a generic function
```cc
template <typename T>
void DoEvalGeneric(const Eigen::Ref<const VectorX<T>>& x, VectorX<T>* y) const {
}
```
And then call it with
```
DoEvalGeneric<double>(x, y);
DoEvalGeneric<AutoDiffXd>(x, y);
DoEvalGeneric<symbolic::Expression>(x.cast<symbolic::Expression>(), y);
```
inside each DoEval function.

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake for platform review
:lgtm: with one nit.
very nice!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679#-:-Mwms3g_0yesi8h3bE_g:b-o6evgu)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94)

___
*[solvers/cost.h, line 390 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwmr2tK3OupQeafOEyV:-Mwmr2tK3OupQeafOEyW:b-2rp08i) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.h#L390)):*
> ```objc
>  * If z = Ax + b, implements a cost of the form:
>  * (z_1^2 + z_2^2 + ... + z_{n-1}^2) / z_0.
>  *
> ```

i think you should make it clear here that the default implementation is as a non-convex objective (but special solvers may be able to provide a convex reformulation).  
___
*[solvers/test/cost_test.cc, line 590 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-MwmrShq3VU9ntXfxA_c:-MwmrShq3VU9ntXfxA_d:ban35ce) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/test/cost_test.cc#L590)):*
> ```cpp
>   const Vector4d x0{5.2, 3.4, -1.3, 2.1};
>   const Vector2d z = A * x0 + b;
>   std::cout << z.transpose() << std::endl;
> ```

nit: remove this.

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94 and @RussTedrake)

___
*[solvers/cost.h, line 390 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwmr2tK3OupQeafOEyV:-MwmstksCNDZAj87FLF2:b-wmiunu) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.h#L390)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think you should make it clear here that the default implementation is as a non-convex objective (but special solvers may be able to provide a convex reformulation).  
</blockquote></details>

If I understand correctly what you mean, I don't think that the "the default implementation is as a non-convex objective". The function that maps `z` to `(z_1^2 + z_2^2 + ... + z_{n-1}^2) / z_0` is convex for `z_0 >= 0` (its epigraph is the rotated SOC).

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 1 unresolved discussion (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/cost.h, line 390 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwmr2tK3OupQeafOEyV:-Mwo2dLVCs51suXDZATs:bdxfjro) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.h#L390)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

If I understand correctly what you mean, I don't think that the "the default implementation is as a non-convex objective ". The function that maps `z` to `(z_1^2 + z_2^2 + ... + z_{n-1}^2) / z_0` is convex for `z_0 >= 0` (its epigraph is the rotated SOC).
</blockquote></details>

Took a stab at addressing both comments. PTAL
___
*[solvers/cost.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-MwmjM4R6KJYpOL6zsWU:-Mwo3dI-3Op8qVK_Kk8r:bibkhb1) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.cc#L286)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, the DoEval does the same thing for the three scalar types. By rule of 3, you could consider to factor it out with a generic function
```cc
template <typename T>
void DoEvalGeneric(const Eigen::Ref<const VectorX<T>>& x, VectorX<T>* y) const {
}
```
And then call it with
```
DoEvalGeneric<double>(x, y);
DoEvalGeneric<AutoDiffXd>(x, y);
DoEvalGeneric<symbolic::Expression>(x.cast<symbolic::Expression>(), y);
```
inside each DoEval function.
</blockquote></details>

Done. Thanks for reminding me of that templating magic!
___
*[solvers/test/cost_test.cc, line 590 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-MwmrShq3VU9ntXfxA_c:-Mwo3t_jE0FnHgiqVKCS:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/test/cost_test.cc#L590)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: remove this.
</blockquote></details>

Done. Thanks for catching that!

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 2 unresolved discussions (waiting on @hongkai-dai, @mpetersen94, and @RussTedrake)

___
*[solvers/cost.h, line 438 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwowkop4S_46SkUqdft:-Mwowkop4S_46SkUqdfu:b-ad5zpy) ([raw file](https://github.com/robotlocomotion/drake/blob/be806ddb352b1cfdb6c278db075c655c39c9891f/solvers/cost.h#L438)):*
> ```objc
>  private:
>   template <typename DerivedX, typename U>
>   void DoEvalGeneric(const Eigen::MatrixBase<DerivedX>& x, VectorX<U>* y) const;
> ```

Curious why using Eigen::MatrixBase<DerivedX> here instead of const Eigen::Ref<const VectorX<T>>&. Since the DoEval function uses const Eigen::Ref<const Eigen::VectorXd>& , I would think it is more natural to use the Eigen::Ref version? You do need to instantiate the template explicitly by calling
```
DoEvalGeneric<double>
DoEvalGeneric<AutoDiffXd>
DoEvalGeneric<symbolic::Expression>
```

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 2 unresolved discussions (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/cost.h, line 438 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwowkop4S_46SkUqdft:-MwsCkD4AaBfB9DcggDM:b-uwggvq) ([raw file](https://github.com/robotlocomotion/drake/blob/be806ddb352b1cfdb6c278db075c655c39c9891f/solvers/cost.h#L438)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why using Eigen::MatrixBase<DerivedX> here instead of const Eigen::Ref<const VectorX<T>>&. Since the DoEval function uses const Eigen::Ref<const Eigen::VectorXd>& , I would think it is more natural to use the Eigen::Ref version? You do need to instantiate the template explicitly by calling
```
DoEvalGeneric<double>
DoEvalGeneric<AutoDiffXd>
DoEvalGeneric<symbolic::Expression>
```
</blockquote></details>

I just replicated the DoEvalGeneric that all other Costs/Constraints that have a generic eval function use.  Do those need to be changed as well?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 2 unresolved discussions (waiting on @hongkai-dai and @TobiaMarcucci)

___
*[solvers/cost.h, line 390 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwmr2tK3OupQeafOEyV:-Mwx_AQKAMx0Cwk1f9Q0:b7tsic4) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.h#L390)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Took a stab at addressing both comments. PTAL
</blockquote></details>

Can we say instead
"Note that this cost is convex when we additionally constrain z_0 > 0.  It is treated as a generic nonlinear objective by most solvers."

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 2 unresolved discussions (waiting on @hongkai-dai and @RussTedrake)

___
*[solvers/cost.h, line 390 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwmr2tK3OupQeafOEyV:-MwyN0vPBhxd-MuSkyY6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7bf93f2a8323aa258d2e7a1f68059cbe65ef848/solvers/cost.h#L390)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Can we say instead
"Note that this cost is convex when we additionally constrain z_0 > 0.  It is treated as a generic nonlinear objective by most solvers."
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[solvers/cost.h, line 438 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwowkop4S_46SkUqdft:-MwyPrhG7DWWQyVQ4c0Q:b-nx4260) ([raw file](https://github.com/robotlocomotion/drake/blob/be806ddb352b1cfdb6c278db075c655c39c9891f/solvers/cost.h#L438)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I just replicated the DoEvalGeneric that all other Costs/Constraints that have a generic eval function use.  Do those need to be changed as well?
</blockquote></details>

I see. I mark myself as satisfied.

@jwnimmer-tri I am not sure if there is any difference when we define the template through these one of the following two different ways
```cc
template <typename Derived>
void Foo(const Eigen::MatrixBase<Derived>& x) {}
```
and
```cc
template <typename T>
void Foo(const Eigen::Ref<const VectorX<T>>& x) {}
```
and instantiate them with an argument of type `const Eigen::Ref<const Eigen::VectorXd>&` as
```cc
void Bar(const Eigen::Ref<const Eigen::VectorXd>& x) {
  Foo(x);
}
```
do you know if one performs different/better than the other?

**Review by mpetersen94 — COMMENTED** [review]
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16679)* status: :shipit: complete! all discussions resolved, LGTM from assignees hongkai-dai,RussTedrake(platform) (waiting on @RussTedrake)

___
*[solvers/cost.h, line 438 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16679#-Mwowkop4S_46SkUqdft:-Mx6bb6N5aVRmNlqgu3M:b-6uxkmb) ([raw file](https://github.com/robotlocomotion/drake/blob/be806ddb352b1cfdb6c278db075c655c39c9891f/solvers/cost.h#L438)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see. I mark myself as satisfied.

@jwnimmer-tri I am not sure if there is any difference when we define the template through these one of the following two different ways
```cc
template <typename Derived>
void Foo(const Eigen::MatrixBase<Derived>& x) {}
```
and
```cc
template <typename T>
void Foo(const Eigen::Ref<const VectorX<T>>& x) {}
```
and instantiate them with an argument of type `const Eigen::Ref<const Eigen::VectorXd>&` as
```cc
void Bar(const Eigen::Ref<const Eigen::VectorXd>& x) {
  Foo(x);
}
```
do you know if one performs different/better than the other?
</blockquote></details>

If @jwnimmer-tri thinks the `Eigen::Ref<const VectorX<T>>` generic method is better than the `Eigen::MatrixBase<Derived>` one, I will follow up with a PR that fixes this across all the costs and constraints.

**Pull request merged**
