### PR TITLE
Add Jekyll framework

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Generates or serves reworked website

Working toward #13832 

`bazel run //doc:serve_jekyll` will serve pages locally at `http://127.0.0.1:4000`

`bazel run //doc:gen_jekyll -- --out_dir <output directory>` will generate output in specified `<output directory>`

Note: It is not necessary to build drake prior to running either command above.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479#-:-MPAy1S9EdYSBBpn5Pxc:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jamiesnape** [comment]
Not your fault, but things like

```
---
links: 
     - title: My Title
       slug: my-slug
 ---

 #### {{page.links[0].title}} {#{{page.links[0].slug}}}
```

are going to be tough on developers writing pages.

**Comment by jamiesnape** [comment]
Needs a `pycodestyle` fixup.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_config.yml, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD7LHp8iAGhg-esspr:-MQD7LHp8iAGhg-essps:bcg3ym9) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L3)):*
> ```YAML
> site: Robot Locomotion Group (MIT).
> 
> url:
> ```

BTW I think we are looking at

```yaml
url:  https://drake.mit.edu
```
and maybe

```yaml
baseurl: /jekyll/
```

at the moment, I forget if adding the latter may break local preview. The former is certainly fine.
___
*[doc/_config.yml, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD9BaFCGk7ozp7MD5y:-MQD9BaFCGk7ozp7MD5z:b-v5ai6g) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L12)):*
> ```YAML
>   release-notes:
>     output: true
>     permalink: /release_notes/:name
> ```

BTW I am guessing this may need tweaking to be exactly the same as the current.
___
*[doc/_config.yml, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD8dWOD5yezMmdGt3b:-MQD8dWOD5yezMmdGt3c:b-lxoa7r) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L38)):*
> ```YAML
>       layout: "page-release"
> 
> exclude: [gen_jekyll, gen_jekyll.py, jekyll_base.py, serve_jekyll, serve_jekyll.py]
> ```

BTW I think

```yaml
exclude:
  - gen_jekyll
  - gen_jekyll.py
  ...
```

works just as well and is a little easier to read and for `git blame`?
___
*[doc/_config.yml, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD2-NaC0eKFlds1Ki9:-MQD2-Nb39aLhG3R6ynx:bi2f49d) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L55)):*
> ```YAML
>   style: compressed
> 
> plugins_dir:
> ```

BTW I would have expected this to be 

```yaml
plugins:
  - jekyll-paginate
```

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/images/Untitled.gif, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD9ec4-S0bHwWRdsvW:-MQD9ec4-S0bHwWRdsvX:bc4kae) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/images/Untitled.gif#L0)):*
BTW Is this used?
___
*[doc/js/plugins.js, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQDA5VZ3GMNqy9uvkeh:-MQDA5VZ3GMNqy9uvkei:b7egq9k) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/js/plugins.js#L11)):*
> ```JavaScript
> // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Plugins
> 
> // @codekit-prepend "/plugins/history.js"
> ```

BTW This only works on Mac and for a very specific program. Eventually, we should probably use an OSS tool for the concatenation and minification (like CDash does, for instance), otherwise making even trivial changes gets tricky.

**Comment by jwnimmer-tri** [comment]
On first glance, it seems like this PR does more than just #13832's bullet for "(4) create a (shadow, non-hyperlinked) page or two in parallel with the live site to stand up the tools and deploy pipeline".  It's fine to have a fully-worked, integration test example to refer to as we iterate toward the goal, but for code review purposes we still _do_ need to have a standalone PR that _only_ adds support for the new framework (and a canary page or two), separate from converting the whole site.

That PR will need a few things to be super clear in its presentation:
- Of the files in the commit(s), which were typed in by hand by you, vs which were created by automated tooling, vs which were pulled from any other sources (e.g., the website contractors' original work).
- For the files created by tools, a rough outline of what tools were run using what steps or options, and what any special copyright status is for any of the generated files.

It's up to you whether you rewind this PR to an earlier stage, or open a new PR with just a subset of these changes.

**Review by BetsyMcPhail — COMMENTED** [review]
PR #14488 has been opened with a subset of these changes. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479#-:-MQEGiN36BXVeDxZwgOT:b-yj65vu)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_config.yml, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD7LHp8iAGhg-esspr:-MQDdh_vCfvgDKjy_LzU:b-pp9vhi) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I think we are looking at

```yaml
url:  https://drake.mit.edu
```
and maybe

```yaml
baseurl: /jekyll/
```

at the moment, I forget if adding the latter may break local preview. The former is certainly fine.
</blockquote></details>

Confirmed that ``baseurl: /jekyll/`` breaks the local preview
___
*[doc/_config.yml, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD2-NaC0eKFlds1Ki9:-MQDe4Ky0Eq2ljv-NWBD:bp2xzle) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L55)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I would have expected this to be 

```yaml
plugins:
  - Jekyll-paginate
```

</blockquote></details>

I think ``- jekyll-paginate``is correct ... but do we actually use it?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14479)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_config.yml, line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14479#-MQD2-NaC0eKFlds1Ki9:-MQEHv1U86vXqvDvFzNn:b-9zys2k) ([raw file](https://github.com/robotlocomotion/drake/blob/16d3613e83f38231346495944847d936e7c65255/doc/_config.yml#L55)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I think ``- jekyll-paginate``is correct ... but do we actually use it?
</blockquote></details>

Sorry, I was querying `plugins_dir` vs. `plugins`. Looks like autocorrect capitalized `Jekyll` to confuse things. But do we use it? Probably not, so you can try removing the whole section and the `paginate_path` entry below.

**Comment by sherm1** [comment]
What is the status of this PR? Currently it doesn't have a reviewer assigned.

**Comment by jamiesnape** [comment]
@BetsyMcPhail Should we close this and push the Markdown to a new PR once #14488 merges?

**Comment by BetsyMcPhail** [comment]
Closing in favor of smaller PRs

**Pull request closed without merging**
