### PR TITLE
Log Explanation of Why Two Matrices Are Unequal.

### PR DESCRIPTION
**Pull request by liangfok**
This helps to debug failing unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4040)

### CODE REVIEW

**Comment by liangfok** [comment]
The [CI failure](https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-ros/542/console) was due to https://github.com/RobotLocomotion/drake/issues/3429.

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
This PR passed all CI builds:

https://github.com//RobotLocomotion/drake/pull/4040/commit/d79d81bef62adc6310b44d731249560af71b0526/show_partial?partial=commit%2Fpull_condensed

Thus:

+@hongkai-dai for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4040#-:-KVqpzx66Nd9p2ChgQ8V:b3773xq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4040#-:-KVqtsNOBk6ph-lbC4ZD:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4040#-:-KVrz2IC04p9d-2OnDPf:bnfp4nl)*

**Pull request merged**
