### PR TITLE
Add targets for vtkIOXML module to `vtk.bzl`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This adds `vtkIOXML` to `vtk.bzl` for using a concrete `vtkPolyDataReader`.

Tested link failures briefly with the following script:
```bash
#!/bin/bash
set -e -u

mkdir -p tmp
cd tmp

cat > BUILD <<EOF
cc_test(
    name = "vtk_io_test",
    srcs = ["vtk_io_test.cc"],
    deps = [
        "@vtk//:vtkIOXML",
    ],
)
EOF

cat > vtk_io_test.cc <<EOF
int main() {}
EOF

bazel run :vtk_io_test
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6825)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
(If there is a more intelligent way to automatically extract this information from CMake, please let me know!)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrHfh-a2DS_MfDTyTWk:b-acyis1)*

**Comment by jamiesnape** [comment]
Each module has a `module.cmake` file that helps:

https://github.com/Kitware/VTK/blob/master/IO/XMLParser/module.cmake
https://github.com/Kitware/VTK/blob/master/IO/XML/module.cmake

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/vtk.bzl, line 379 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVv7Ff-1Y6ZfkweQoU:-KrVv7Ff-1Y6ZfkweQoV:b-2ckt90) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L379)):*
> ```Python
>         "vtkIOXMLParser",
>         hdrs = [
>             "vtkIOXMLModule.h",
> ```

Should be in `vtkIOXML`.

---

*[tools/vtk.bzl, line 382 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVzgwzcjaaYDtx3qTg:-KrVzgwzcjaaYDtx3qTh:b-vgxxxg) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L382)):*
> ```Python
>         ],
>         deps = [
>             ":vtkIOCore",
> ```

```
":vtkCommonCore",
":vtkCommonDataModel",
":vtkexpat",
":vtkIOCore",
":vtksys",
```


---

*[tools/vtk.bzl, line 397 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVvWuhKWIJbZhjG702:-KrVvWuhKWIJbZhjG703:bojou9j) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L397)):*
> ```Python
>         deps = [
>             ":vtkIOCore",
>             ":vtkIOXMLParser",
> ```

```
":vtkCommonCore",
":vtkCommonDataModel",
":vtkCommonExecutionModel",
":vtkIOCore",
":vtkIOXMLParser",
":vtksys",
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrVuZTeMNQxV9uV53vv:bkpv0zg)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by EricCousineau-TRI** [comment]
Had to add a "header only" version of `vtkexpat` since it was statically linked (I believe). Let me know if there is a better alternative. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/vtk.bzl, line 379 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVv7Ff-1Y6ZfkweQoU:-KrWkicLageYsYxDVrGV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L379)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Should be in `vtkIOXML`.
</blockquote></details>

Done.

---

*[tools/vtk.bzl, line 382 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVzgwzcjaaYDtx3qTg:-KrWkixjxHlfDDU9vX9B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L382)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

```
":vtkCommonCore",
":vtkCommonDataModel",
":vtkexpat",
":vtkIOCore",
":vtksys",
</blockquote></details>

Done.

---

*[tools/vtk.bzl, line 397 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrVvWuhKWIJbZhjG702:-KrWkkGnbLD7ouEvjo-v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35f6b7ef1ca83443f369fe29cb910561b3299a61/tools/vtk.bzl#L397)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

```
":vtkCommonCore",
":vtkCommonDataModel",
":vtkCommonExecutionModel",
":vtkIOCore",
":vtkIOXMLParser",
":vtksys",
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrWkmYGkIGbUqmekdVT:b1a1wug)*
<!-- Sent from Reviewable.io -->

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/vtk.bzl, line 551 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrWnZ53tEIC6emakNiR:-KrWnWRi3akyj9-OxyG-:b1vuhil) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2f123b17c8a72b30ea533fecf8c5f96e487c3d/tools/vtk.bzl#L551)):*
> ```Python
>     # The present build of VTK statically links vtkexpat.
>     file_content += _vtk_cc_library(repository_ctx.os.name, "vtkexpat",
>                                     header_only = True)
> ```

It may be using the system expat. If there is a pkg-config file, then add expat to the workspace, otherwise you would need to do something similar to `vtkglew`, but for both platforms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/vtk.bzl, line 551 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrWnZ53tEIC6emakNiR:-KrX8su0x1pfcn55Nux3:b-bwplq0) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2f123b17c8a72b30ea533fecf8c5f96e487c3d/tools/vtk.bzl#L551)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It may be using the system expat. If there is a pkg-config file, then add expat to the workspace, otherwise you would need to do something similar to `vtkglew`, but for both platforms.
</blockquote></details>

Should this be dependent on how we package, and not on whether or not `expat` is available to the system?
As an example, I have VTK 7.0.0 built on my system (Ubuntu 16.04), and it has a dynamically linked `vtkexpat`, even though I had `expat` present; however, the version incorporated here depends on the system version.

I think it'd be best just to analyze the build itself - if `vtkexpat` is present as a shared library, add it via `_vtk_cc_library`, otherwise, assume that we must use `-lexpat`. (I would like to avoid the need to parse `pkg-config` in this package for different include files.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vtk.bzl, line 551 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrWnZ53tEIC6emakNiR:-KrXCHGF7neMVLj9CSvc:b-m8lew2) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2f123b17c8a72b30ea533fecf8c5f96e487c3d/tools/vtk.bzl#L551)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Should this be dependent on how we package, and not on whether or not `expat` is available to the system?
As an example, I have VTK 7.0.0 built on my system (Ubuntu 16.04), and it has a dynamically linked `vtkexpat`, even though I had `expat` present; however, the version incorporated here depends on the system version.

I think it'd be best just to analyze the build itself - if `vtkexpat` is present as a shared library, add it via `_vtk_cc_library`, otherwise, assume that we must use `-lexpat`. (I would like to avoid the need to parse `pkg-config` in this package for different include files.)
</blockquote></details>

The packages that we create always use the system expat and we only support VTK using our own packages. We do not support an arbitrary system VTK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vtk.bzl, line 551 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrWnZ53tEIC6emakNiR:-KrXHiY5TD_BCtLHJso3:biskjuw) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2f123b17c8a72b30ea533fecf8c5f96e487c3d/tools/vtk.bzl#L551)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The packages that we create always use the system expat and we only support VTK using our own packages. We do not support an arbitrary system VTK.
</blockquote></details>

Done. Sorry, I had misread your initial response, thanks!
I have not used `pkg-config`, as this is not used for `vtkglew`, and would like to defer this to another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/vtk.bzl, line 551 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrWnZ53tEIC6emakNiR:-KrXI_ox9ZPMUp-14b3k:b-r9sz8) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2f123b17c8a72b30ea533fecf8c5f96e487c3d/tools/vtk.bzl#L551)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. Sorry, I had misread your initial response, thanks!
I have not used `pkg-config`, as this is not used for `vtkglew`, and would like to defer this to another PR.
</blockquote></details>

That's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrXJHAWnUA-CTy4fQEo:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.

However, note that this PR isn't telling us much under CI -- by declaring more labels but not referring to them anywhere, CI is not going to try to build them.  I would slightly prefer if there were a using-binary added somewhere else in the tree as part of the same PR, but I guess that's author's discretion.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrXKMI0p-7qJQ_qTicH:bbg1o8l)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
@jwnimmer-tri I had wanted to separate this from the original PR to narrow the scope, but did not think on the CI angle.
However, I can close this PR and incorporate this commit directly in the next PR.

I will start preparing the other PR, and will close this one if there are no objections.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrXiJR1ExhBVJCmY815:b-o0d8jb)*

**Comment by jwnimmer-tri** [comment]
I definitely don't want this mixed in with a multi-hundred-line new component, I would rather just merge this than do that.  But a hello-world 10-line program would be great.

**Comment by EricCousineau-TRI** [comment]
Ah, I see.
It feels kind of weird to have this test in place. For now, I've placed it in `drake/thirdParty` - should I instead make a temp, no-op program where I plan to use the library, to be removed once there is actually a target that consumes this directly?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrXusCIz_YICmJO-szP:bqieyls)*

**Comment by jamiesnape** [comment]
Yes.

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrY0DVcD1Kgd79KL3sQ:bb77ufg)*

**Comment by jwnimmer-tri** [comment]
Once you feel like it's ready in final form, be sure to opt-in to a `mac` Bazel build.

---

Reviewed 2 of 4 files at r4.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/thirdParty/README.md, line 7 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrYLQNJwZcGiMpeanRB:-KrYLQNJwZcGiMpeanRC:b-bjol70) ([raw file](https://github.com/robotlocomotion/drake/blob/9b9b15a4a65d6cdc52817f6b8ed8452b336ff3ba/drake/thirdParty/README.md#L7)):*
> ```Markdown
> 
> The thirdParty/test sub-directory contains tests that ensure third-party
> libraries are appropriately incorporated.
> ```

I agree with @jamiesnape that the test shouldn't live in this folder.  (This folder is for other-party code.)

I would be okay putting the test either the final home, or else `drake-distro/tools/test` to match where the `vtk.bzl` logic lives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-KrYLoWJ9dG0ImdhOGZT:b-6ps5kq)*

**Comment by EricCousineau-TRI** [comment]
Done. Just moved the existing program, since the work was already done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-Kra7Q7wEpNPqhilNjfP:bomxugd)*

**Comment by EricCousineau-TRI** [comment]
*[drake/thirdParty/README.md, line 7 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-KrYLQNJwZcGiMpeanRB:-Kra7d67B1j3680aW7Kb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b9b15a4a65d6cdc52817f6b8ed8452b336ff3ba/drake/thirdParty/README.md#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I agree with @jamiesnape that the test shouldn't live in this folder.  (This folder is for other-party code.)

I would be okay putting the test either the final home, or else `drake-distro/tools/test` to match where the `vtk.bzl` logic lives.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-:-Kra8R4YaYGUqWLtgEWI:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 7 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/estimators/dev/test/tmp_vtk_io_xml_test.cc, line 13 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/6825#-Kra8qRH-CZVSRWb3gEP:-Kra8qRIzCqWJbO8qPfD:bildcdz) ([raw file](https://github.com/robotlocomotion/drake/blob/adab9ace68bd2c6dd8fce5ff5b72d98dd6c8614c/drake/perception/estimators/dev/test/tmp_vtk_io_xml_test.cc#L13)):*
> ```cpp
> int main() {
>   // Read a file that was generated with a random point cloud.
>   const char* filename = "tmp_vtk_io_xml_test.vtp";
> ```

FYI I would not expect this filename to be at `$CWD` in Bazel.  (I would expect `drake/perception/estimators/dev/test/tmp_vtk_io_xml_test.vtp` to find it.)  But I think it's good enough for a linker test anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6825)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Pull request merged**
