### PR TITLE
[pydrake] Add proxy feature for MeshCat on Deepnote

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #13683.

Requires:
- [x] #16638

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/_geometry_extra.py, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwSupFsD33rz7bDEtog:-MwSupFsD33rz7bDEtoh:bu5ier9) ([raw file](https://github.com/robotlocomotion/drake/blob/c2023ce642091c7ae974a62b79eb5939e367024b/bindings/pydrake/_geometry_extra.py#L40)):*
> ```Python
> def _setup_deepnote_nginix():
>     print("Setting up Deepnote MeshCat NginX server...")
>     _run(["apt-get", "update"])
> ```

Working

I might as well just make this a bash script that we can just shell out to.  That would make it easier for users to incorporate into their `init.ipynv` or Docker image, if they so wished.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

___
*[bindings/pydrake/_geometry_extra.py, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwSupFsD33rz7bDEtog:-MwTT4pQ30esCWIQyWNO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c2023ce642091c7ae974a62b79eb5939e367024b/bindings/pydrake/_geometry_extra.py#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I might as well just make this a bash script that we can just shell out to.  That would make it easier for users to incorporate into their `init.ipynv` or Docker image, if they so wished.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
I _think_ this might be finished.  Now I need to figure out how to test it.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri to begin feature review, please.  I think it makes sense to start reviewing at least the _readability_ of the current code here, even if questions about how to demonstrate its correctness are still up in the air.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending test plan and/or results

> Reviewed 4 of 7 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639#-:-MwYQcPi8bziwMVJqN2H:bt9jz0y)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Testing (manually in the cloud works) well in most cases, but I think I still need to fiddle with some timeout settings in the proxy so that it doesn't timeout when the simulation is paused for a while.

How would you feel about this PR abandoning the `StartMeshcat()` changes (such the all prior behavior remains intact), but leaving in all of the other infra and helper functions intact (with a TODO), and merging that?  That would make it easiser to test in the cloud (we could call `_start_meshcat_deepnote` manually) from scratch, using tonight's nightlies?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639#-:-MwYWF8Z4X4hzw-7YarN:bv5lpyc)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Works for me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639#-:-MwYXVK7-5qRqy_rxnfF:b-bk5ip0)* status: needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Now that it's disarmed by default, -(release notes: yes) +(release notes: none) -(status: do not merge).

+@xuchenhan-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639#-:-MwY_3C3CTuGlG8KLpPd:bhv89jo)* status: LGTM missing from assignee xuchenhan-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri and @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 7 files at r2, 3 of 8 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639#-:-MwYl26VDTyOHGtymx_O:bg7igkv)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[setup/deepnote/install_nginx, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwYhaM92mOxyyZy_AWP:-MwYhaM92mOxyyZy_AWQ:bssqpio) ([raw file](https://github.com/robotlocomotion/drake/blob/af1d2436ead2ed0e8d47dea80cae1821449362c5/setup/deepnote/install_nginx#L3)):*
> ```
> #!/bin/bash
> #
> # Installs and runs nginx as an Ubuntu system daemon, and adds our
> ```

If this is only supposed to run on Ubuntu, why isn't it under the Ubuntu folder?
Also, does this mean we can't run multiple meshcat in deepnote on mac?
___
*[setup/deepnote/install_nginx, line 6 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwYerXJ2W46M-H0Vi_t:-MwYerXJ2W46M-H0Vi_u:bfutd5y) ([raw file](https://github.com/robotlocomotion/drake/blob/af1d2436ead2ed0e8d47dea80cae1821449362c5/setup/deepnote/install_nginx#L6)):*
> ```
> # nginx-meshcat-proxy.conf as a site to be served.
> #
> # These is intended for use by pydrake.geometry.SetupMeshcat() to configure a
> ```

nit, s/These is/This is.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @xuchenhan-tri)

___
*[setup/deepnote/install_nginx, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwYhaM92mOxyyZy_AWP:-MwYoTzG5qLWWQSdZoik:bya8tbl) ([raw file](https://github.com/robotlocomotion/drake/blob/af1d2436ead2ed0e8d47dea80cae1821449362c5/setup/deepnote/install_nginx#L3)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

If this is only supposed to run on Ubuntu, why isn't it under the Ubuntu folder?
Also, does this mean we can't run multiple meshcat in deepnote on mac?
</blockquote></details>

Hopefully the new README text helps?

I don't think the Deepnote cloud supports macOS images.  Or at least, we don't need that for our tutorials.  We get to select with OS our tutorials hyperlinks will point to from our docs.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[setup/deepnote/install_nginx, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwYhaM92mOxyyZy_AWP:-MwYqM4ED5qPH-K9d2ok:b-lg05o9) ([raw file](https://github.com/robotlocomotion/drake/blob/af1d2436ead2ed0e8d47dea80cae1821449362c5/setup/deepnote/install_nginx#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hopefully the new README text helps?

I don't think the Deepnote cloud supports macOS images.  Or at least, we don't need that for our tutorials.  We get to select with OS our tutorials hyperlinks will point to from our docs.
</blockquote></details>

I see, thanks for the explanation.
___
*[setup/deepnote/install_nginx, line 7 at r8](https://reviewable.io/reviews/robotlocomotion/drake/16639#-MwYqTfk-O_dKj8V7fZM:-MwYqTfk-O_dKj8V7fZN:b-5olcjb) ([raw file](https://github.com/robotlocomotion/drake/blob/4bca47610b5ec72a0bd0e977e460b108491778ad/setup/deepnote/install_nginx#L7)):*
> ```
> #
> # This is intended for use by pydrake.geometry.SetupMeshcat() to configure a
> # Deepnote notebook to allow for MeshCat traffic to flow. Refer to the 
> ```

nit trailing spaces.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16639)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'm glad we didn't deploy this as-is.  It turns out that our Docker deployment pipeline had some `rm -rf` magic buried inside that made this fail (=> #16658).

**Pull request merged**
