### PR TITLE
py systems: Add keep_alive cycle to DiagramBuilder.AddSystem

### LINKED ISSUE #14355: py systems: `DiagramBuilder.AddSystem()` may not propagate existing keep-alive "edges"
See Slack convo:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1605703451063400

Currently, we have this for `DiagramBuilder.AddSystem` (which is *locally* correct):
https://github.com/RobotLocomotion/drake/blob/6d56ea0bf744be43c8453650e149c3772318b88d/bindings/pydrake/systems/framework_py_semantics.cc#L454-L461

But @RussTedrake ran into an edge case where the following code would segfault without the workaround to keep `controller_plant` alive:
https://github.com/RussTedrake/manipulation/blob/805d4c582268b3803e90125266803e13dbc9ddbc/manipulation_station.ipynb

This `keep_alive` on the ID looks fine:
https://github.com/RobotLocomotion/drake/blob/6d56ea0bf744be43c8453650e149c3772318b88d/bindings/pydrake/systems/controllers_py.cc#L95

But most likely, the `PyObject` for the `InverseDynamics` evaporates since it's inside the `MakeManipulationStation()` function, so the `keep_alive` "graph" evaporates, so nothing is there to keep the `controller_plant` alive.

Hack solution is to just add a reference cycle for now, and reap the issues later :(
Something like:
```
AddSystem ...
// Keep alive, ownership: `self` keeps `return` alive
// HACKHACHKACHKHACK
keep_alive<1, 0>(),
```

\cc @SeanCurtis-TRI

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is a workaround to ensure we propagate keep_alive relationships

Resolves #14355

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@russtedrake for feature review, please!
+@sammy-tri for platform review, please!

On the whole, my feelings for this PR: :vomiting_face: 
But it works, so my more dominant feelings as well: :shrug: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356#-:-MMR6Avx2MuPK77eAC4g:bg9rfa5)* status: LGTM missing from assignees RussTedrake(platform),sammy-tri(platform) (waiting on @RussTedrake and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356#-:-MMTC7fR-GSKaMc-OWBy:btapcqv)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[bindings/pydrake/systems/framework_py_semantics.cc, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14356#-MMTBtuK-zhyJZUo7pAN:-MMTBtuL6cC80_kozf3u:b-29no6r) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d58083f570cb252d46c0ea355b9f0a75520506/bindings/pydrake/systems/framework_py_semantics.cc#L461)):*
> ```cpp
>             py::arg("system"),
>             // TODO(eric.cousineau): These two keep_alive's purposely form a
>             // reference cycle as a workaround or #14355. We should find a
> ```

nit: or => for

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @RussTedrake and @sammy-tri)

___
*[bindings/pydrake/systems/framework_py_semantics.cc, line 461 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14356#-MMTBtuK-zhyJZUo7pAN:-MMTLW4n38FsJD11RPNG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c6d58083f570cb252d46c0ea355b9f0a75520506/bindings/pydrake/systems/framework_py_semantics.cc#L461)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: or => for
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Not a huge fan of this "workaround" myself but after spelunking in the issues/discussions I guess I could l live with it.  Holding off final review until CI is happy.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356#-:-MMWikqaCauAc8sjEEuW:bcxzwri)* status: LGTM missing from assignee sammy-tri(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
Fixed CI error - had to propagate new expectations due to the hack

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356#-:-MMX9NJN6-OxLGsWg1nF:b-jmkavh)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @RussTedrake and @sammy-tri)

**Comment by EricCousineau-TRI** [comment]
Yup, looks like it's good to go!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14356#-:-MMXTyB-3U7YBlfZB2J5:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Pull request merged**
