### PR TITLE
Adding bindings for several MultibodyTree getters

### PR DESCRIPTION
**Pull request by caelan**
I added python bindings to expose several getter methods that are useful for pick-and-place planning.

Let me know if I missed a step in the drake code review pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9592)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
In light of the conclusion for #9366 (deprecating `MultibodyTree`), can I ask if these are things that you can bind in Python for `MultibodyPlant`, rather than `MultibodyTree`?
If not, we can certainly add them to MBT for the time being.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I thought about that, but I figured multibody's current inadequacies were no reason to hold up this contribution.  We're going to have to keep around pydrake's MBT deprecation forwarders for a while no matter what, so a few more added to that set wasn't a big deal.  In other words, this PR doesn't have any defects -- it's MBP that's broken, and it doesn't seem to me like @caelan should be responsible for fixing that.  We (the Drake Developers) should endeavor to make MBP correct, not offload that duty to users who are just trying to make forward progress.  The sooner we do that, the sooner the pydrake APIs can begin to migrate to suit.

**Comment by EricCousineau-TRI** [comment]
Sounds good - sorry for muddying the waters!

**Comment by caelan** [comment]
Great! Thanks everyone.

**Pull request merged**
