### PR TITLE
toward #1070: fix for make -j8 in drake/ dir.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This patch follow the pattern established in the superbuild Makefile.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
+1 LGTM.

Perhaps worth asking @RussTedrake if kitware needs to also review it first.

**Comment by liangfok** [comment]
+1

**Comment by RussTedrake** [comment]
@RobotLocomotion/kitware -- please review?

**Comment by jamiesnape** [comment]
retest this please

**Comment by jhoare** [comment]
The issue I could see is that this assumes that cmake is being ran with the ``Makefile`` generator on non-windows systems.  Of course, as mentioned, the superbuild Makefile has already made this assumption.

**Comment by mwoehlke-kitware** [comment]
If you are building via the pods `Makefile`, that is going to run `cmake`
with no generator specified (i.e. default, which is `UNIX Makefiles`), so
this seems safe enough.

**Comment by rpoyner-tri** [comment]
@jhoare: if you decide that the generator spec is an issue, please note that the dist-level makefile likely has the same issue, since I adapted the present patch from there.

**Comment by rpoyner-tri** [comment]
esting/**/Test.xml' relative to '/home/ubuntu/workspace/experimental/compiler/gcc/label/linux' for the testing framework 'CTest-Version N/A (default)'.
[xUnit] [ERROR] - Test reports were found but not all of them are new. Did all the tests run?
  * /home/ubuntu/workspace/experimental/compiler/gcc/label/linux/drake/pod-build/Testing/20160326-1714/Test.xml is 1 day 21 hr old
  * /home/ubuntu/workspace/experimental/compiler/gcc/label/linux/drake/pod-build/Testing/20160328-1503/Test.xml is 7 min 58 sec old
===

[xUnit] [ERROR] - Test reports were found but not all of them are new. Did all the tests run?
  * /home/ubuntu/workspace/experimental/compiler/clang/label/linux/drake/pod-build/Testing/20160326-1714/Test.xml is 1 day 21 hr old


I have no idea what the above failures mean, and doubt they have anything to do with the patch in question. Help please?

**Comment by jamiesnape** [comment]
Which build?

**Comment by rpoyner-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/experimental/448/ , linux(clang,gcc) .

**Comment by jamiesnape** [comment]
Definitely a Jenkins issue, which should be resolved now. You current build will not have that problem.

**Comment by rpoyner-tri** [comment]
I'm not sure how code review is supposed to proceed for this PR, or who is supposed to drive it. AIUI, I would need a properly blessed gitcolony invite from @RussTedrake to participate in the review?

**Comment by jwnimmer-tri** [comment]
Mechanism: use githib PR code review unless specifically told otherwise (for this issue, github PR review is fine).

In this case, Russ tagged it as needing review, because he wanted kitware specifically to look at it.

**Comment by rpoyner-tri** [comment]
I am happy with a pure PR review, but the afaict the PR will not appear as merge-green until someone closes the the gitcolony widget that has been attached.

**Comment by jwnimmer-tri** [comment]
This is showing as merge-green just fine for me now, at least.

**Comment by jwnimmer-tri** [comment]
@RobotLocomotion/kitware We are waiting for your input on this PR.  Please give either a definitive "+1 yes to be merged", or else list specific defects to fix.

**Comment by jamiesnape** [comment]
LGTM.

**Comment by jwnimmer-tri** [comment]
Thank you!

**Comment by patmarion** [comment]
This pull request has removed the install step from the pod Makefile `drake/Makefile`.  That means drake's Makefile is not pod compatible anymore.  This breaks downstream projects that are using drake as a pod, namely, the openhumanoids project.

I see that this pull request was referenced by issue #1070.  Removing the install step does not seem necessary to resolve #1070.  To be pod compliant, can we change the non-Windows command to match the standard pod Makefile:

    $(MAKE) -C pod-build all install

**Comment by patmarion** [comment]
I opened #1970 to re-add the install step to the pod makefile.

**Pull request merged**
