### PR TITLE
[inverse_kinematics] Rename kinematic_constraint => kinematic_evaluators

### PR DESCRIPTION
**Pull request by RussTedrake**
I'm about to add a number of kinematic *costs* alongside the kinematic
constraints.  I've separated out this trivial (but high-touch) change
to keep the next PR content clean.

+@EricCousineau-TRI for both reviews, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17575)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[`multibody/inverse_kinematics/kinematic_evaluator_utilities.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17575#-N6wrjWcDRf2bvtlvKhd:-N6wuZuk4RbVnGpBPkUx:bey5668) ([raw file](https://github.com/robotlocomotion/drake/blob/fd47507d55a60ea8d8c0ef8ac152e3f42b6a8d6d/multibody/inverse_kinematics/kinematic_evaluator_utilities.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This header is presently installed. While it only contains `namespace internal`, the file itself is still accessible via install tree.
Per https://drake.mit.edu/stable.html as written, this *seems* like it needs deprecation.

Can I ask your thoughts?
If no deprecation is deemed necessary, then should we amend `stable.md` to say something like this to clarify the case in the future?
```
Headers that are installed, but are clearly utilities have only ever contained `namespace internal` code are exempt from Stable API.
```

(\cc @jwnimmer-tri )
</blockquote></details>

See "Exemptions" section in the linked doc: "do not include headers that you don’t use".

Since this code is all in internal namespace, nobody should be calling it.  Since nobody is calling it, nobody is allowed to `#include` it.  Thus, no need for deprecation.

**Comment by jwnimmer-tri** [comment]
The header was internal, but the bazel label name was public and breaking change (broke Anzu).  I'll add back a deprecation alias in a fix-forward.

**Comment by RussTedrake** [comment]
ugh.  Sorry.

**Comment by jwnimmer-tri** [comment]
Rejoice, the deprecation timeout 2022-11-01 has arrived!  Please open a PR that completes this process.

**Pull request merged**
