### PR TITLE
Use SelectFirstAvailableSolver instead of SolveWithFirstAvailableSolver

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in https://github.com/RobotLocomotion/drake/pull/15319#issuecomment-875043969

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

The input argument to `SelectFirstAvailableSolver` is a vector of <b> const </b> SolverInterface pointers. I want to emphasize that this function doesn't change SolverInterface, hence use a const pointer. Is it better to use a non-const pointer?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-Mdx_Yc85Rig9No_xsLD:bc3yb0j)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yes, `const SolverInterface*` is better vs `SolverInterface*`.

I was also wondering -- would using a `const std::vector<SolverId>&`  as the argument be even better?  Perhaps:

```c++
std::unique_ptr<SolverInterface> MakeFirstAvailableSolver(const std::vector<SolverId>& ids);
```

This would allow the user to construct the exactly one SolverInterface that was useful, instead of creating a handful and then throwing them away.  For example:

```c++
MathematicalProgramResult result =
    MakeFirstAvailableSolver({GurobiSolver::id(), ScsSolver::id()})->Solve(prog);
```

The examples in this PR are all very basic functional tests, so it's difficult for me to tell whether the Id or Interface is best.  If you can share some sample the uses that motivated this feature, maybe we can decide.

**Review by hongkai-dai — COMMENTED** [review]
Good call, I think it is better to use `SolverId` in this function instead of `SolverInterface`. Previously in `SolveWithFirstAvailableSolver` I use `SolverInterface` instead of SolverId, because after creating the solver from SolverId, the user might need to make some modifications to the solver (for example, mosek_solver.set_stream_logging(true, "");). But now we can create and return the SolverInterface from SolverId. I will make that change in the next commit.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxcAfJ3enCc6e4_gF0:bbmtv6b)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
Using SolverId works better in C++, where we can create a SolverId using the static function GurobiSolver::id(). In pydrake, it is less ideal as we don't bind that static function, so we need GurobiSolver().solver_id(). As a result, we create the solver for twice, the first time to get its solver_id(), the second time inside MakeFirstAvailableSolver.

We should add the binding for the static `id` function.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxedUe-nkzeHFhaanj:bnaputo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
We have a helper file `solvers_pybind.h`.  We would probably add a new helper in that file which bound the static methods `id`, `is_available`, and `is_enabled`.

> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxnAK2-jxrzOBcTOil:bdhwqcv)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/choose_best_solver.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdxcyN33wjTyuqfuyj0:-MdxcyN33wjTyuqfuyj1:b-h1csjk) ([raw file](https://github.com/robotlocomotion/drake/blob/e9d73dd50ec1399147e42e0b7ad02f306e157227/solvers/choose_best_solver.h#L34)):*
> ```objc
> /**
>  * Selects the first available and enabled solver. If no solvers are available,
>  * throw a runtime error.
> ```

nit s/runtime error/exception/

_"When documenting exceptions in an API, only state that the function will throw std::exception, never promise a more specific subclass."_

-- https://drake.mit.edu/styleguide/cppguide.html#Exceptions

**Review by RussTedrake — COMMENTED** [review]
i very much like the solver_id version.  i was sad to allocate all of the solvers in my c++ example.  it also felt a bit heavy to have to include all of their include files.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxriMO-xQUNxyNM7cG:bg9v9f4)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
@russtedrake I think you still need to include the header files like `gurobi_solver.h` etc, as we will need the header file to use `GurobiSolver::id()`. But I agree it is better with SolverId as the user doesn't need to allocate the solvers.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxuJ4D8SJbMBVSLgGG:bxqzkgy)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
In the future if we want to reduce the number of includes, we could collect all of Drake's well-known ids into a single header.  I kind of prefer listing the includes out one by one to be clear about the dependency footprint, but offering some sugar for prototyping would be fine too.

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxufKCAwkUKgqbcmkS:b3qogeh)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 1166 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdxuLM9-5GOicUQqtqK:-MdxuLM9-5GOicUQqtqL:b-wyze0f) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L1166)):*
> ```Python
> 
>     def test_solve_with_first_available_solver(self):
>         prog = mp.MathematicalProgram()
> ```

nit `prog` is dead code now (as is `solver`).  You could call `solver.Solve(prog)`, but my vote would be to remove it entirely.
___
*[solvers/choose_best_solver.h, line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-Mdxu8wNEEOzYf11XDlZ:-Mdxu8wNEEOzYf11XDl_:b-h0ocnh) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/choose_best_solver.h#L34)):*
> ```objc
> /**
>  * Makes the first available and enabled solver. If no solvers are available,
>  * throw a std::exception.
> ```

nit s/throw/throws/ verb tense to agree with "Makes".
___
*[solvers/choose_best_solver.cc, line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdxtyDG6FeXFvRGmh-P:-MdxtyDG6FeXFvRGmh-Q:bfhleim) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/choose_best_solver.cc#L120)):*
> ```cpp
>     const std::vector<SolverId>& solver_ids) {
>   for (const auto& solver_id : solver_ids) {
>     auto solver = MakeSolver(solver_id);
> ```

FYI This implementation is somewhat inefficient -- we don't need to create a new instance here, we can use the id to know which static functions to check.  I can push that in a separate PR, though.  This PR is correct, just inefficient.
___
*[solvers/test/choose_best_solver_test.cc, line 198 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdxsQbz6paqHkzh8avs:-MdxsQc--LudZr7IWwBR:b-zb57gq) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/test/choose_best_solver_test.cc#L198)):*
> ```cpp
> }
> 
> GTEST_TEST(SelectFirstAvailableSolver, Test) {
> ```

nit s/Select/Make/
___
*[solvers/test/choose_best_solver_test.cc, line 200 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-Mdxt-n7883_wETyxOYU:-Mdxt-n80EN3JAgwfwGm:beplcxk) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/test/choose_best_solver_test.cc#L200)):*
> ```cpp
> GTEST_TEST(SelectFirstAvailableSolver, Test) {
>   GurobiSolver gurobi_solver{};
>   ScsSolver scs_solver{};
> ```

nit I wonder if this test would be clearer if we used the static `is_available` and `is_enabled` methods, instead of creating solver objects, and also captured named locals for the concepts the test cares about:

```c++
const bool has_gurobi = GurobiSolver::is_available() && GurobiSolver::is_enabled();
const bool has_scs = ScsSolver::is_available() && ScsSolver::is_enabled();

if (has_gurobi && has_scs) {
  auto solver = ...;
  if (has_gurobi) {
    ...;
  }  else {
    ...;
  }

  if (!has_gurobi) {
    ...;
  }
}
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/choose_best_solver.cc, line 120 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdxtyDG6FeXFvRGmh-P:-MdxwLxG8cIkKm2dFzjL:b3f4jjm) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/choose_best_solver.cc#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This implementation is somewhat inefficient -- we don't need to create a new instance here, we can use the id to know which static functions to check.  I can push that in a separate PR, though.  This PR is correct, just inefficient.
</blockquote></details>

Yeah I think it is better to do that in a separate PR, so that we don't block PR #15315 
___
*[solvers/test/choose_best_solver_test.cc, line 200 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15325#-Mdxt-n7883_wETyxOYU:-MdxxAzeAtsnnbGkReQp:b-ohdo8) ([raw file](https://github.com/robotlocomotion/drake/blob/64f56e8bdfbda7b76a5ee38d215a10a74bd80158/solvers/test/choose_best_solver_test.cc#L200)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I wonder if this test would be clearer if we used the static `is_available` and `is_enabled` methods, instead of creating solver objects, and also captured named locals for the concepts the test cares about:

```c++
const bool has_gurobi = GurobiSolver::is_available() && GurobiSolver::is_enabled();
const bool has_scs = ScsSolver::is_available() && ScsSolver::is_enabled();

if (has_gurobi && has_scs) {
  auto solver = ...;
  if (has_gurobi) {
    ...;
  }  else {
    ...;
  }

  if (!has_gurobi) {
    ...;
  }
}
```
</blockquote></details>

Done, good call.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxyxRLCcuipjAbrrpu:buer3go)* status: LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdxzQrCDRCTKqYy0NrO:b-n37teh)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one minor fix.
Note that public function SolveWithFirstAvailableSolver() is removed but not deprecated in this PR -- I deem that OK for a function whose lifetime was measured in hours!

> Reviewed 3 of 8 files at r1, 2 of 5 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325#-:-MdyA4xvChOKXj4PWdEY:b-vx9mtn)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/choose_best_solver.cc, line 130 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15325#-Mdy9VBB3-lqM7d5uanb:-Mdy9VBB3-lqM7d5uanc:b9pousd) ([raw file](https://github.com/robotlocomotion/drake/blob/6e178c151865d85be8629ca3e3e90ef2afeb9047/solvers/choose_best_solver.cc#L130)):*
> ```cpp
>   }
>   throw std::runtime_error("MakeFirstAvailableSolver(): none of the solvers " +
>                            solver_names + "is available or enabled.");
> ```

minor: "available _and_ enabled"
___
*[solvers/test/choose_best_solver_test.cc, line 216 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15325#-Mdy9pDF7FDZ0fLfvymM:-Mdy9pDF7FDZ0fLfvymN:b3a7g5r) ([raw file](https://github.com/robotlocomotion/drake/blob/6e178c151865d85be8629ca3e3e90ef2afeb9047/solvers/test/choose_best_solver_test.cc#L216)):*
> ```cpp
>     DRAKE_EXPECT_THROWS_MESSAGE(MakeFirstAvailableSolver({GurobiSolver::id()}),
>                                 std::runtime_error,
>                                 ".* is available or enabled.");
> ```

minor: or -> and

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15325)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
___
*[solvers/choose_best_solver.cc, line 117 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15325#-MdyoVif0U45AbARscNH:-MdyoVif0U45AbARscNI:b-ul5tws) ([raw file](https://github.com/robotlocomotion/drake/blob/067eb0a98e58d0c31adc070c735cab621fd1f552/solvers/choose_best_solver.cc#L117)):*
> ```cpp
> }
> 
> std::unique_ptr<SolverInterface> MakeFirstAvailableSolver(
> ```

Now that i'm putting it into use, I wonder if we can return a pointer to`SolverBase` instead of `SolverInterface`?  The `MathematicalProgramResult = Solve(...)` method is only on `SolverBase`; with this version I have to allocate my own `MathematicalProgramResult`.

**Comment by hongkai-dai** [comment]
I forgot why we have the separated class SolverInterface and SolverBase. @jwnimmer-tri could you remind me why we created `SolverBase`? I am reading the PR https://github.com/RobotLocomotion/drake/pull/10635, but still can't remember the motivation for `SolverBase`.

**Comment by jwnimmer-tri** [comment]
SolverInterface is the contract, with no implementation at all; SolverBase is a common implementation to inherit from, but is generally invisible to users.

I do understand the pain that Russ raises, but I am not sure if returning `SolverBase*` is the best answer.

Perhaps SolverInterface should gain more of the typical Solve overloads (the new overload(s) would all return the result by-value).  This is probably the best answer?

Or, perhaps the `Solve` free function overload set should gain the ability to pass a `const SolverInterface*` as an argument as well, in which case it doesn't need to "choose".  So `result = Solve(solver, prog)` instead of just `result = Solve(prog)`.

**Pull request merged**
