### PR TITLE
[py multibody] Add bindings for ScopedName

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #17482.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+(release notes: none) since the C++ feature was added subsequent to the most recent release.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both reviews per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2 with question about testing.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958#-:-NQ28OkJCd3xmcWvlFv3:bliob0o)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18958#-NQ28VCwCyJwPHFZ69UF:-NQ28VCwCyJwPHFZ69UG:b-qryje3) (no related file):*
BTW, why is there no test for the new binding?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18958#-NQ28VCwCyJwPHFZ69UF:-NQ29b0i8k2rvmNASBPX:b-x1g4hm) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why is there no test for the new binding?
</blockquote></details>

Oops.  Because I got so interested in Hongkai's talk that I forgot to write any.
I need to do that.

Working.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18958#-NQ28VCwCyJwPHFZ69UF:-NQ2ADIW10Wr1XNh56gS:b-9huwk9) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops.  Because I got so interested in Hongkai's talk that I forgot to write any.
I need to do that.

Working.
</blockquote></details>

Actually I did write them.  I just forgot to push.  Derp.

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18958#-NQ28VCwCyJwPHFZ69UF:-NQ2C_eLBrmD4Zxw7pv5:b-ve3yvb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually I did write them.  I just forgot to push.  Derp.
</blockquote></details>

:smile: 

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18958)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
