### PR TITLE
[manipulation] Port show_model to meshcat C++

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14702.

Related to #17214.

(When merging to master, we should squash down to a single commit.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review, please.

I've only run the automated tests, not any manual testing, but I think this along the lines of what we want.  Could you take a read over the code and see if it makes sense, and then also work on some manual testing?

Feel free to push fixes if you like.

**Review by svenevs — COMMENTED** [review]
With the current changes (adding `import webbrowser` at the top) you can run e.g., `bazel run //manipulation/util:geometry_inspector -- --find_resource drake/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf --position 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 --pyplot -w` without any problems (nothing breaks, meshcat, planar, and drake visualizer all show the same thing with updates from the tk JointSliders) -- this is good, the changeset here doesn't break `geometry_inspector` so can resolve updates independently.  Technically some docs get outdated but keeping the changes separate is best.

Some problems arise with running this file now, though, see below.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N30HH5E8ge66a7KQi7f:b-mhwgq)* status: 4 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DVVK6J2s9Tz5Jdyx:-N30DVVK6J2s9Tz5Jdyy:br3fp2x) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L24)):*
> ```Python
>     # Terminal 3 (wait for visualizers to start)
>     ./bazel-bin/manipulation/util/show_model \
>         --meshcat default \
> ```

Working, update docs (no more meshcat server etc).
___
*[`manipulation/util/show_model.py` line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DP7D2G_LdvWNlUCU:-N30DP7D2G_LdvWNlUCV:b-60i0tg) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L54)):*
> ```Python
> import argparse
> import os
> import warnings
> ```

Working, add `import webbrowser`.
___
*[`manipulation/util/show_model.py` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DeWPBQb5junCOYhc:-N30DeWPBQb5junCOYhd:brryyf2) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L146)):*
> ```Python
>             mapped_value = Role.kProximity
>         elif values == 'illustration':
>             mapped_value = Role.kIllustration
> ```

Working, having issues with meshcat need to test this after resolving.
___
*[`manipulation/util/show_model.py` line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30Dn8BCaVSKNTY85uP:-N30Dn8BCaVSKNTY85uQ:b-t68zzz) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L353)):*
> ```Python
>     # Use Simulator to dispatch initialization events.
>     # TODO(eric.cousineau): Simplify as part of #10015.
>     Simulator(diagram).Initialize()
> ```

Working, I think this is the problem.

When running `bazel run //manipulation/util:show_model -- --find_resource drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf -w` there is a problem where the meshcat server will spawn and then immediately shutdown (before the browser even opens).  In geometry inspector

https://github.com/RobotLocomotion/drake/blob/df41d02e0592f883a241a3c5673c02f35b3cc3ac/manipulation/util/geometry_inspector.py#L152-L159

advancing to `np.inf` seems to be what keeps the server alive, however for `show_model` the same cannot be done (it complains about joints not being connected).  I tried to `meshcat_vis_params.delete_on_initialization_event = False` since they seem related here?

@EricCousineau-TRI do you have any insight here?  I couldn't follow the discussion on #10015 and subsequent #13776.  My impression is that `Simulator(diagram).Initialize()` is a hack to get things connected up with the various visualizers (e.g., drake visualizer).  It doesn't seem to play well with the C++ meshcat server.  Sorry if you're the wrong person to tag, I'm not sure how to make C++ meshcat persist without advancing the simulator to infinity.

FYI the update going on here is moving python => c++ meshcat (python is deprecated and going away soonish), but the pressing matter is tkinter and JointSliders use in geometry inspector -- these changes are in support of that fix.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: 4 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @svenevs)

___
*[`manipulation/util/show_model.py` line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30Dn8BCaVSKNTY85uP:-N30Jgoe-tXatSQP51dL:b6862sg) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L353)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, I think this is the problem.

When running `bazel run //manipulation/util:show_model -- --find_resource drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf -w` there is a problem where the meshcat server will spawn and then immediately shutdown (before the browser even opens).  In geometry inspector

https://github.com/RobotLocomotion/drake/blob/df41d02e0592f883a241a3c5673c02f35b3cc3ac/manipulation/util/geometry_inspector.py#L152-L159

advancing to `np.inf` seems to be what keeps the server alive, however for `show_model` the same cannot be done (it complains about joints not being connected).  I tried to `meshcat_vis_params.delete_on_initialization_event = False` since they seem related here?

@EricCousineau-TRI do you have any insight here?  I couldn't follow the discussion on #10015 and subsequent #13776.  My impression is that `Simulator(diagram).Initialize()` is a hack to get things connected up with the various visualizers (e.g., drake visualizer).  It doesn't seem to play well with the C++ meshcat server.  Sorry if you're the wrong person to tag, I'm not sure how to make C++ meshcat persist without advancing the simulator to infinity.

FYI the update going on here is moving python => c++ meshcat (python is deprecated and going away soonish), but the pressing matter is tkinter and JointSliders use in geometry inspector -- these changes are in support of that fix.
</blockquote></details>

This probably has nothing to do with the initialization events.  More likely, the shared pointer lifetime management for pybind11 vs meshcat is going awry, given the factored-out we're dealing with argument processing here.  I'll see what I can figure out.

**Comment by jwnimmer-tri** [comment]
*[`manipulation/util/show_model.py` line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30Dn8BCaVSKNTY85uP:-N30KRWMCE10GByzI8NJ:b-ltaxt4) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L353)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This probably has nothing to do with the initialization events.  More likely, the shared pointer lifetime management for pybind11 vs meshcat is going awry, given the factored-out we're dealing with argument processing here.  I'll see what I can figure out.
</blockquote></details>

Oh -- the whole program is just ending, not anything about memory management.  Yeah, we just need to pause until the user cancels us.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: 4 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DP7D2G_LdvWNlUCU:-N30Mw_U3DyvWn07i5Gv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L54)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, add `import webbrowser`.
</blockquote></details>

Done.
___
*[`manipulation/util/show_model.py` line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30Dn8BCaVSKNTY85uP:-N30MvRc4NOJDPmIgaBw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L353)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oh -- the whole program is just ending, not anything about memory management.  Yeah, we just need to pause until the user cancels us.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: 5 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 375 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hsobE0vdYXB3uxY7:-N30hsoc47qAmbZpgxCj:b-j17ngl) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L375)):*
> ```Python
>     if args.meshcat:
>         print("Use Ctrl-C to quit")
>         while True:
> ```

This is the only one I'm not sure about -- does someone _really_ need more than 15 minutes to stare at a model file?  I would have thought not, and accidentally leaving a program running for hours on end is an annoying feature of "forever" daemon programs.

If we need this to be longer, we just add more exponents to the sleep (2 hours? 1 day? 1 week?) -- we don't need to loop.

**Review by svenevs — COMMENTED** [review]
Pending discussion of `--meshcat_role` I think this is good to go.  The `--visualize_frames` works with all visualizers, I don't know how to test `--visualize_collisions` though.  If we don't need to do anything for `--meshcat_role` then I will squash it all down, approve and add platform.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N30i0Zs74sl5j1zCyre:bhdpyjx)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DVVK6J2s9Tz5Jdyx:-N30hIJiBZfZTM_XBNd9:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L24)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, update docs (no more meshcat server etc).
</blockquote></details>

Done
___
*[`manipulation/util/show_model.py` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DeWPBQb5junCOYhc:-N30hMwPE0mz3x8f8kEt:b-3eqezn) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L146)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Working, having issues with meshcat need to test this after resolving.
</blockquote></details>

When I use `--meshcat_role proximity` nothing shows up.  What is supposed to happen?
___
*[`manipulation/util/show_model.py` line 353 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30Dn8BCaVSKNTY85uP:-N30ZGRfEDtIJYYNzo9f:b-ut5qq4) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L353)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK cool, it works!  I made it a loop, if you wait (or just `time.sleep(1)`) too long then it will still end.
___
*[`manipulation/util/show_model.py` line 332 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hXHY9g88CLJTFXVL:-N30hXHY9g88CLJTFXVM:b-fijpfo) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L332)):*
> ```Python
>         else:
>             if args.browser_new is not None:
>                 args_parser.error("-w / --open-window require --meshcat")
> ```

FYI this isn't strictly necessary but it's nice to error on them.
___
*[`manipulation/util/show_model.py` line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hbT_2XtcJz8qFWvU:-N30hbT_2XtcJz8qFWvV:busqg1h) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L338)):*
> ```Python
>             pyplot = ConnectPlanarSceneGraphVisualizer(builder, scene_graph)
> 
>         return meshcat
> ```

FYI the following diff allows geometry inspector to be functional, just showing why `meshcat` needs to be returned

```diff
diff --git a/manipulation/util/geometry_inspector.py b/manipulation/util/geometry_inspector.py
index edf9826747..a639965bdf 100644
--- a/manipulation/util/geometry_inspector.py
+++ b/manipulation/util/geometry_inspector.py
@@ -71,7 +71,7 @@ import argparse
 import numpy as np
 
 from pydrake.geometry import SceneGraph
-from pydrake.manipulation.simple_ui import JointSliders
+from pydrake.multibody.meshcat import JointSliders
 from pydrake.multibody.plant import MultibodyPlant
 from pydrake.systems.analysis import Simulator
 from pydrake.systems.framework import DiagramBuilder
@@ -114,6 +114,8 @@ def main():
         "--test", action='store_true',
         help="Disable opening the slider gui window for testing.")
     args = args_parser.parse_args()
+    # NOTE: the meshcat visualizer is required for this file.
+    args.meshcat = True
     filename, make_parser = parse_filename_and_parser(args_parser, args)
     update_visualization, connect_visualizers = parse_visualizers(
         args_parser, args)
@@ -132,18 +134,18 @@ def main():
     update_visualization(plant, scene_graph)
     plant.Finalize()
 
+    meshcat = connect_visualizers(builder, plant, scene_graph)
+
     # Add sliders to set positions of the joints.
-    sliders = builder.AddSystem(JointSliders(robot=plant))
+    sliders = builder.AddSystem(JointSliders(meshcat=meshcat, plant=plant))
     to_pose = builder.AddSystem(MultibodyPositionToGeometryPose(plant))
     builder.Connect(sliders.get_output_port(0), to_pose.get_input_port())
     builder.Connect(
         to_pose.get_output_port(),
         scene_graph.get_source_pose_port(plant.get_source_id()))
 
-    connect_visualizers(builder, plant, scene_graph)
-
     if len(args.position):
-        sliders.set_position(args.position)
+        sliders.SetPositions(args.position)
     elif len(args.joint_position):
         sliders.set_joint_position(args.joint_position)
```

Will do in a followup PR though, need to update docs there too etc.

**Review by jwnimmer-tri — COMMENTED** [review]
I'll check on the open threads in a moment.

> ... I will squash it all down ...

For shared PRs, I'd prefer that we never squash (i.e., no force-pushes) -- so that each of our local git trees can continue pushing.  Platform will squash during the merge operation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N30iSXZC7ZxcU0Pb-SW:b-k3jehs)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
OK perfect, works for me!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N30jZBk7f4iC-k6RdoX:bpjilea)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @svenevs)

___
*[`manipulation/util/show_model.py` line 375 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hsobE0vdYXB3uxY7:-N30j1H2-Z1gkaKXhTIZ:bnoab7) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L375)):*
Done, reverted

> does someone really need more than 15 minutes to stare at a model file?

Hehe.  Probably not.  It was a semantics concern, if you wait too long to open the window then it terminates.  You can still see the model in `drake-visualizer` and the `pyplot`, but meshcat will be left out.  But they have plenty of time to open the window before that is a problem.  And if not ... just run it again :p

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @svenevs)

___
*[`manipulation/util/show_model.py` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DeWPBQb5junCOYhc:-N30jPyN6CL_pns1mB5m:bsh92y0) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L146)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

When I use `--meshcat_role proximity` nothing shows up.  What is supposed to happen?
</blockquote></details>

Are you passing `iiwa7_no_collision` as the model file?  Is has no proximity geometry defined, so nothing is supposed to show up.

Try `examples/acrobot/Acrobot.urdf` (without `--find_resource`).
___
*[`manipulation/util/show_model.py` line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hbT_2XtcJz8qFWvU:-N30iyBW4htqdt7d2BHy:bg24l8a) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L338)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI the following diff allows geometry inspector to be functional, just showing why `meshcat` needs to be returned

```diff
diff --git a/manipulation/util/geometry_inspector.py b/manipulation/util/geometry_inspector.py
index edf9826747..a639965bdf 100644
--- a/manipulation/util/geometry_inspector.py
+++ b/manipulation/util/geometry_inspector.py
@@ -71,7 +71,7 @@ import argparse
 import numpy as np
 
 from pydrake.geometry import SceneGraph
-from pydrake.manipulation.simple_ui import JointSliders
+from pydrake.multibody.meshcat import JointSliders
 from pydrake.multibody.plant import MultibodyPlant
 from pydrake.systems.analysis import Simulator
 from pydrake.systems.framework import DiagramBuilder
@@ -114,6 +114,8 @@ def main():
         "--test", action='store_true',
         help="Disable opening the slider gui window for testing.")
     args = args_parser.parse_args()
+    # NOTE: the meshcat visualizer is required for this file.
+    args.meshcat = True
     filename, make_parser = parse_filename_and_parser(args_parser, args)
     update_visualization, connect_visualizers = parse_visualizers(
         args_parser, args)
@@ -132,18 +134,18 @@ def main():
     update_visualization(plant, scene_graph)
     plant.Finalize()
 
+    meshcat = connect_visualizers(builder, plant, scene_graph)
+
     # Add sliders to set positions of the joints.
-    sliders = builder.AddSystem(JointSliders(robot=plant))
+    sliders = builder.AddSystem(JointSliders(meshcat=meshcat, plant=plant))
     to_pose = builder.AddSystem(MultibodyPositionToGeometryPose(plant))
     builder.Connect(sliders.get_output_port(0), to_pose.get_input_port())
     builder.Connect(
         to_pose.get_output_port(),
         scene_graph.get_source_pose_port(plant.get_source_id()))
 
-    connect_visualizers(builder, plant, scene_graph)
-
     if len(args.position):
-        sliders.set_position(args.position)
+        sliders.SetPositions(args.position)
     elif len(args.joint_position):
         sliders.set_joint_position(args.joint_position)
```

Will do in a followup PR though, need to update docs there too etc.
</blockquote></details>

Does `geometry_inspector` still function correctly as of only the changes in this PR?  If not, we need to push its fixes into this PR as well.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30DeWPBQb5junCOYhc:-N30s4C58qIEooqZXbDj:b6zj2lv) ([raw file](https://github.com/robotlocomotion/drake/blob/b5077960e366a24a138f58d489e0ea38c1ce64af/manipulation/util/show_model.py#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Are you passing `iiwa7_no_collision` as the model file?  Is has no proximity geometry defined, so nothing is supposed to show up.

Try `examples/acrobot/Acrobot.urdf` (without `--find_resource`).
</blockquote></details>

Ok, acrobot shows things so the meshcat roles seem to be what we want.
___
*[`manipulation/util/show_model.py` line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hbT_2XtcJz8qFWvU:-N30sBYc11b_HB4k2CBr:b-ciqufs) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L338)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does `geometry_inspector` still function correctly as of only the changes in this PR?  If not, we need to push its fixes into this PR as well.
</blockquote></details>

Officially, it still functions as desired with the tk sliders.  The only thing this PR invalidates is the docstring at the top of the file, e.g., `--meshcat default` is no longer a thing.

That said, the diff on geometry inspector is very small now.  So I think it's OK to just add it here if you want.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[`manipulation/util/show_model.py` line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hbT_2XtcJz8qFWvU:-N30sopH90UGOHcxMfLl:bb57xu4) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L338)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Officially, it still functions as desired with the tk sliders.  The only thing this PR invalidates is the docstring at the top of the file, e.g., `--meshcat default` is no longer a thing.

That said, the diff on geometry inspector is very small now.  So I think it's OK to just add it here if you want.
</blockquote></details>

Enh, a docstring that's wrong by epsilon isn't worth fretting about here.  I'll let you work with it in the other PR.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by svenevs — COMMENTED** [review]
:lgtm: feature.  FYI @sammy-tri the updated examples at the top of the file are how to confirm it works as expected.  You can run `drake-visualizer` and provide `--meshcat --open-window --planar` to any call to `show_model` to see all three visualizers. 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N30tMj_-bIFUvpJmaz1:b-d3mnqz)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @svenevs)

___
*[`manipulation/util/show_model.py` line 338 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17274#-N30hbT_2XtcJz8qFWvU:-N30tD933qFKY8VODuwE:b-bujqgz) ([raw file](https://github.com/robotlocomotion/drake/blob/b710f0e6e0b4c6a39570f279bd66dea2a1d534b1/manipulation/util/show_model.py#L338)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Enh, a docstring that's wrong by epsilon isn't worth fretting about here.  I'll let you work with it in the other PR.
</blockquote></details>

Hehe ok, tally-ho then!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17274#-:-N319bDN60FfeoexS9hO:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Pull request merged**
