### PR TITLE
Add ignition_rndf_test to CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
To test (and fix) 34ba0c3bcf19dec09cebed8347c431b917eb9f0e.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5959)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5959#-:-KilKDTzYm_GnYMJNwNZ:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5959#-:-KimbOFHQkID2DEjskrE:bnfp4nl)*

**Pull request merged**
