### PR TITLE
lcm: Add publish_period option to ConnectLcmScope

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14062)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for review, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:, and yay!

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14062#-:-MHGeqPa-nZwQ63bZEEN:b-gatpj6)* status: needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14062#-:-MHHgCzECs5Ym0YTPRAA:b8qx53o)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/lcm/connect_lcm_scope.h, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14062#-MHHcySN89N5N1UMvVRx:-MHHcySO62NEs_pluXd9:b-mbxo7t) ([raw file](https://github.com/robotlocomotion/drake/blob/5d06aff942088e4d77e611282e279bc4652e042b/systems/lcm/connect_lcm_scope.h#L24)):*
> ```objc
> 
>  The optional @p publish_period specifies how often messages will be published.
>  If the period is zero, then the underlying LcmPublisherSystem will publish
> ```

nit: "If the period is zero or unspecified,"

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14062)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
