### PR TITLE
Fix the CI failure on linear_solve_test.cc

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #15745

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15748)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15748#-:-MjAFUg89W3Doe9ipW7p:b79lg6w)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15748#-:-MjAS9BNC3qfIaN3VX1R:bmxilld)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks for taking care of this so quickly.
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15748#-:-MjASC7F9y8L1nrdbuo6:b-imi5wu)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
