### PR TITLE
pybind11: Update to latest master

### LINKED ISSUE #11638: pybind11 build error under clang-6.0 --std=c++17
From a `@drake-jenkins-bot linux-bionic-clang-bazel-experimental-cxx17-release please` CI build:
```
In file included from bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/cpp_param_pybind/drake/bindings/pydrake/common/cpp_param_pybind.h:10:
external/pybind11/include/pybind11/pybind11.h:1005:9: error: no matching function for call to 'operator delete'
        ::operator delete(p, s, std::align_val_t(a));
        ^~~~~~~~~~~~~~~~~
```

Probably the same as pybind/pybind11#1604.

I wonder if we can fix it in our pybind11 fork, without having to add compiler flags?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #11638.  Incorporates RobotLocomotion/pybind11#30.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11650)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-cxx17-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
Sorry; the `pybind11` repo does have CI (subset of upstream's), but GitHub's UI for PRs hides it once it merges. Link from Jeremy's PR:
https://github.com/RobotLocomotion/pybind11/runs/148718821
> image

**Pull request merged**
