### PR TITLE
Add CspaceFreePolytope::GenerateRationals.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18400)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18400#-:-NITToVeCQcwD74yBbaV:b-kengf8)* status: LGTM missing from assignee AlexandreAmice (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18400)* status: 9 unresolved discussions, LGTM missing from assignee AlexandreAmice (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_Mm9L5x1WELlZTQ5E:-NI_Mm9L5x1WELlZTQ5F:bgh7get) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.h#L19)):*
> ```objc
>   kSphere,
>   kPolytope,
>   kCylinder,
> ```

We support reifying the Cylinder, but as of right now (as far as I understand) we don't support the cylinder as an actual collision body. Should we actually include this type?
___
*[`geometry/optimization/dev/collision_geometry.h` line 105 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_M3oh8tK1LqOt571n:-NI_M3oh8tK1LqOt571o:b-sqb9et) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.h#L105)):*
> ```objc
> 
>   /**
>    Returns the number of rationals to in the condition "this geometry is on one
> ```

nit: extra "to"
___
*[`geometry/optimization/dev/collision_geometry.cc` line 213 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_MJ_41WYgHzUFn8DY:-NI_MJ_41WYgHzUFn8DZ:b5qxlhj) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L213)):*
> ```cpp
> };
> 
> class TypeReifier : public ShapeReifier {
> ```

TypeReifier is not a very descriptive name. Perhaps something like `CollisionBodyReifier`?
___
*[`geometry/optimization/dev/collision_geometry.cc` line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_M_JL0g--TaE_TnEd:-NI_M_JL0g--TaE_TnEe:b-evtkfh) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L253)):*
> ```cpp
> };
> 
> class NumPlaneSideRationalsReifier : public ShapeReifier {
> ```

As written this suggests a number of planes not a number of rationals. Could we switch this to `NumRationalsPerPlaneSideReifer`?
___
*[`geometry/optimization/dev/collision_geometry.cc` line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_NGZmCTC31XlRYKwE:-NI_NGZmCTC31XlRYKwF:b-aneycv) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L310)):*
> ```cpp
> }
> 
> int CollisionGeometry::num_plane_side_rationals() const {
> ```

ditto about this suggesting number of planes not number of rationals.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_NNz5AHoKQ_eB4LWU:-NI_NNz5AHoKQ_eB4LWV:brdwoyx) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/cspace_free_polytope.h#L24)):*
> ```objc
>  plane.
>  The conditions are that certain rational functions should be always positive,
>  and certain vector has length <= 1.
> ```

nit grammar: "a certain vector"
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_Q5E626Y6TOts_5F4:-NI_Q5E626Y6TOts_5F5:bujpulj) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/cspace_free_polytope.cc#L204)):*
> ```cpp
>               bool match = false;
>               if (vec.rows() == unit_length_vec->rows()) {
>                 for (int i = 0; i < vec.rows(); ++i) {
> ```

I believe this for loop does no computation besides exiting early. Perhaps `match = true` is in the wrong spot?
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_RaktER3j1MgnG6ds:-NI_RaktER3j1MgnG6dt:b-kos41v) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L94)):*
> ```cpp
>   CspaceFreePolytope dut(plant_, scene_graph_, SeparatingPlaneOrder::kAffine);
>   Eigen::Vector3d q_star(0, 0, 0);
>   CspaceFreePolytope::FilteredCollsionPairs filtered_collision_pairs = {};
> ```

We should include a test for when there are filtered collision pairs as this affect the number of planes.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_R9Hk5YMZEXxqYXqz:-NI_R9Hk5YMZEXxqYXr-:big5bh3) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L103)):*
> ```cpp
>     if (plane.positive_side_geometry->type() == GeometryType::kCylinder ||
>         plane.negative_side_geometry->type() == GeometryType::kCylinder) {
>       throw std::runtime_error("Has not implemented cylinder for C-IRIS yet.");
> ```

nit grammar: '"Cylinder has not been implement yet for C-IRIS."'

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18400)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_Mm9L5x1WELlZTQ5E:-NI_g__0DwBjeoSR4b1w:b-omrpc6) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.h#L19)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We support reifying the Cylinder, but as of right now (as far as I understand) we don't support the cylinder as an actual collision body. Should we actually include this type?
</blockquote></details>

I think it is OK to leave Cylinder here. If people call `OnPlaneSide` function, the reifier will throw an error saying it is not implemented.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 213 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_MJ_41WYgHzUFn8DY:-NI_h47-8C_Em4Z1W4H4:bb5wnqb) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L213)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

TypeReifier is not a very descriptive name. Perhaps something like `CollisionBodyReifier`?
</blockquote></details>

Done. I renamed it as `GeometryTypeReifier` as it returns a `GeometryType` object.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_M_JL0g--TaE_TnEd:-NI_hIpX-PFxVERZgFsd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L253)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

As written this suggests a number of planes not a number of rationals. Could we switch this to `NumRationalsPerPlaneSideReifer`?
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/collision_geometry.cc` line 310 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_NGZmCTC31XlRYKwE:-NI_hXmSAcfx6RUI4peP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/collision_geometry.cc#L310)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

ditto about this suggesting number of planes not number of rationals.
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_Q5E626Y6TOts_5F4:-NI_hpUS39ngihCdM2fP:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/cspace_free_polytope.cc#L204)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I believe this for loop does no computation besides exiting early. Perhaps `match = true` is in the wrong spot?
</blockquote></details>

Done. Good catch
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18400#-NI_RaktER3j1MgnG6ds:-NI_jAKB37rnPT-DgvoM:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/680b8c106663cd538a43adc1fd22e0cb528d2200/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L94)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We should include a test for when there are filtered collision pairs as this affect the number of planes.
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: except for one pending nit

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18400#-:-NIc3zoc3hquwh7zE3aG:bpomnmv)* status: 1 unresolved discussion (waiting on @hongkai-dai)

**Pull request merged**
