### PR TITLE
Fix Wunused-parameter in automotive/maliput

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5991)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for feature review, please.

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5991#-:-Kj4kOywZyie1gVeSeYH:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 9 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5991#-:-Kj4qKskBC-UZJFspM3k:bnfp4nl)*

**Pull request merged**
