### PR TITLE
[geometry] Define alphabetical order to Shapes by convention

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The ordering of the shapes has historically been chaotic (they were ordered according to introduction order). This makes it hard to find the desired shape and interferes with assessing if a shape implementation is missing in a reifier.
    
The declarations of shapes are now alphabetized as well as the in the `ShapeReifier` implementation. Tests and implementations have been updated to reflect the same order.

This incidentally cleans up a couple of outliers discovered during the process.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Notes to reviewer:

R1: This only moves existing code. It re-orders the Shape interface to be alphabetical; nothing new is added.
R2: This adds a small amount of new code.

I recommend reviewing the two revisions separately.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFUJ3bAAzOm4rP8YpGS:b-3lwk3q)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@damrongguoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFUJGVg7jMKFWZllkjI:b-4tfozp)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @DamrongGuoy)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: none) 
+(priority: low) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFUJNgMDIbfzIvk2o92:b7d6zf9)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

Thanks for working on this.

> Reviewed 26 of 26 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFk7mNP2YQU5jzFLZnM:b359mt7)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFkhzO047ebUQbiUOyN:b-ruv0ff)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 25 of 26 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18202#-:-NFl2vVK3aSbNTqKcqvm:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/shape_to_string_test.cc` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18202#-NFl2_ow3EqhAofEzePw:-NFl2_ow3EqhAofEzePx:b-ogpl2c) ([raw file](https://github.com/robotlocomotion/drake/blob/09d31b5aaa73112c53695750fb071ece3c13c90d/geometry/test/shape_to_string_test.cc#L37)):*
> ```cpp
> }
> 
> GTEST_TEST(ShapeToStringTest, Ellipsoid) {
> ```

This (Ellipsoid, in r1) was a new test, not an alpha-sort.

**Comment by SeanCurtis-TRI** [comment]
*[`geometry/test/shape_to_string_test.cc` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18202#-NFl2_ow3EqhAofEzePw:-NFng7kx8D0gjc94UZLs:b-ng3w4k) ([raw file](https://github.com/robotlocomotion/drake/blob/09d31b5aaa73112c53695750fb071ece3c13c90d/geometry/test/shape_to_string_test.cc#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This (Ellipsoid, in r1) was a new test, not an alpha-sort.
</blockquote></details>

Sorry about that; I was worried I missed something when I disentangled things. Thanks for accommodating it.

**Pull request merged**
