### PR TITLE
[solvers] ClarabelSolver obeys SolverOptions

### PR DESCRIPTION
**Pull request by hongkai-dai**
The users can modify the Clarabel solver settings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-:-NkNP2Qy-LwJ2AMQ_At1:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/clarabel_solver.cc` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNRJkaA4orZCUqi1Ch:-NkNRJkb063IK51yHGOB:bz2uhpm) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/clarabel_solver.cc#L175)):*
> ```cpp
>   std::unordered_map<std::string, int> solver_options_int =
>       solver_options.GetOptionsInt(ClarabelSolver::id());
>   // The options can be found in Clarabel upstream code DefaultSettings.h
> ```

When we upgrade Clarabel, we'll certainly forget to revisit this list of hard-coded options and so we'll start to bitrot.

I'll take a moment and I see if I can auto-generate this code.  Otherwise, we'll need to put a comment in the workspace file to remind us to manually check the list every time we upgrade.
___
*[`solvers/clarabel_solver.cc` line 246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNR2bW2oVOJ_bvN10m:-NkNR2bW2oVOJ_bvN10n:bi87l9h) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/clarabel_solver.cc#L246)):*
> ```cpp
>   SetClarabelSetting(&solver_options_int, "presolve_enable",
>                      &(settings.presolve_enable));
>   if (!solver_options_int.empty()) {
> ```

For other solvers, I'm pretty sure we treat unknown option names as exceptions.  (At least, in SCS we do.)  Why not do it the same way here?
___
*[`solvers/solver_options.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNRrf6DQtAW6bF1wmi:-NkNRrf6DQtAW6bF1wmj:b6qjnvb) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/solver_options.h#L61)):*
> ```objc
>  *
>  * "Clarabel" -- Parameter name and values as specified in Clarabel
>  * https://oxfordcontrol.github.io/ClarabelDocs/stable/api_settings/
> ```

nit We should document that `direct_solve_method` is not a supported option.
___
*[`solvers/solver_options.h` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNRvRL8npmHJdM1Ic8:-NkNRvRL8npmHJdM1Ic9:b9rs2hc) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/solver_options.h#L61)):*
> ```objc
>  *
>  * "Clarabel" -- Parameter name and values as specified in Clarabel
>  * https://oxfordcontrol.github.io/ClarabelDocs/stable/api_settings/
> ```

BTW Maybe we should mention that Clarabel's boolean options should be passed as integers (0 or 1).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/clarabel_solver.cc` line 246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNR2bW2oVOJ_bvN10m:-NkNel9A7sQ1M_2y8YHn:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/clarabel_solver.cc#L246)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For other solvers, I'm pretty sure we treat unknown option names as exceptions.  (At least, in SCS we do.)  Why not do it the same way here?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/clarabel_solver.cc` line 175 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkNRJkaA4orZCUqi1Ch:-NkNnuni3JgkuvPBdLDT:b66lf6b) ([raw file](https://github.com/RobotLocomotion/drake/blob/ed72ab50667f2072cf0575d273050367d22f68b1/solvers/clarabel_solver.cc#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When we upgrade Clarabel, we'll certainly forget to revisit this list of hard-coded options and so we'll start to bitrot.

I'll take a moment and I see if I can auto-generate this code.  Otherwise, we'll need to put a comment in the workspace file to remind us to manually check the list every time we upgrade.
</blockquote></details>

See https://github.com/hongkai-dai/drake/pull/33

**Review by jwnimmer-tri — COMMENTED** [review]
Let's treat this as co-author & co-feature-review, so we each review the other's parts of code we wrote.  Once we're both happy with the code, we can bring in a platform reviewer for a final pass.

I wrote my patch in about 30 minutes so it's a bit light on comments.  I'll push a few more comments later on tonight.

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-:-NkShtAq5CR2rVk3Zynq:bc4h99s)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature review.  Once you LGTM @hongkai-dai, please assign platform review.

Reminder: I pushed another patch to this branch.  Be sure to pull it locally if you have more changes to layer on top.

> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-:-NkSvw5x9DGzIBM7kCOx:bfbfily)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/clarabel_solver.cc` line 182 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-NkStyll1vSilWKOXicL:-NkStyll1vSilWKOXicM:b-1tydxo) ([raw file](https://github.com/RobotLocomotion/drake/blob/2be3bbdd2979382bbad820c0ef10ac91211c1498/solvers/clarabel_solver.cc#L182)):*
> ```cpp
>       throw std::logic_error(fmt::format(
>           "ClarabelSolver: unrecognized solver options {}. Please check "
>           "https://github.com/oxfordcontrol/Clarabel.cpp/blob/main/include/cpp/"
> ```

BTW It seems to me like the URL in this error message and URL in the SolverOptions overview would normally be the same.  Is there a reason they are different URLs?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platofrm, nice!

> Reviewed 2 of 4 files at r2, 2 of 7 files at r3, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20602#-:-NkXnYg5-uBubpRjKe5M:b-e1816o)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Pull request merged**
