### PR TITLE
[pydrake] Add YAML parsing for variant/union

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As additional regression testing, add yaml deserialization acceptance tests for the stochastic vector and rotation classes.

Towards #18566 and thus #17112.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-:-NM-snGh7kshIehqTnkt:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/yaml.py` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-NM-qn3pDEP62HRbhgUU:-NM-qn3pDEP62HRbhgUV:b-jodzhv) ([raw file](https://github.com/RobotLocomotion/drake/blob/20f520a0a0bb6173786bb3a35a499bdfd8127f9a/bindings/pydrake/common/yaml.py#L218)):*
> ```Python
>         setter = functools.partial(setattr, target, name)
> 
>     # Handle all of the plain YAML scalars:
> ```

nit consider moving this ref-comment about scalars to the definition site of `_PRIMITIVE_YAML_TYPES`

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri are you available for off-cycle platform review?  Rico (feature) is on call today.  I am also OK waiting for your normal Thursday morning on-call time.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-:-NM-y9ufBCqDJ-KKFqb9:b-aj5y6v)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

___
*[`bindings/pydrake/common/yaml.py` line 218 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-NM-qn3pDEP62HRbhgUU:-NM-xTjT9sd0U5xdfHdm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20f520a0a0bb6173786bb3a35a499bdfd8127f9a/bindings/pydrake/common/yaml.py#L218)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider moving this ref-comment about scalars to the definition site of `_PRIMITIVE_YAML_TYPES`
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Should be able to review today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-:-NM0C3DSBS41aKf03JR4:bale3tt)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18604#-:-NM0rlukBFJF6pv-VagL:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
