### PR TITLE
CompliantContactManager computes accelerations cache

### PR DESCRIPTION
**Pull request by amcastro-tri**
Manager must report accelerations to the plant so that we can compute reaction forces.
This PR implements that.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476#-:-N5khLc4CyJbcKnph51D:b-37uu3f)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 942 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17476#-N5kgLgG810-hGaut43H:-N5kgLgG810-hGaut43I:b-rirpxt) ([raw file](https://github.com/robotlocomotion/drake/blob/fa8181d940a295c25195426948b9908211c59c44/multibody/plant/compliant_contact_manager.cc#L942)):*
> ```cpp
>   ac->get_mutable_vdot() = (v_next - v0) / plant().time_step();
> 
>   // N.B. Pool of spatial accelerations indexed by BodyNodeIndex.
> ```

nit, this comment doesn't mean much standing alone here. Could you expand on it?
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1382 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17476#-N5kgygK7W7xbS67Iq5a:-N5kgygK7W7xbS67Iq5b:b-by8gyo) ([raw file](https://github.com/robotlocomotion/drake/blob/fa8181d940a295c25195426948b9908211c59c44/multibody/plant/test/compliant_contact_manager_test.cc#L1382)):*
> ```cpp
>       CompliantContactManagerTest::topology(*manager_));
>   manager_->CalcAccelerationKinematicsCache(*context_, &ac);
>   EXPECT_TRUE(CompareMatrices(ac.get_vdot(), a_expected, 5.0 * kEps,
> ```

BTW, I'm slightly surprised by the need to 5x `kEps`. I think they `ac.get_vdot()` and `a_expected` go through the exact same code path and thus should be identical?

**Review by amcastro-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review please (tomorrow)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476#-:-N5lCXA8Bxk_qeG1KwpF:bm1mdt3)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @amcastro-tri and @EricCousineau-TRI)

**Review by ggould-tri — COMMENTED** [review]
Eric is out today.  -@ericcousineau-tri +@ggould-tri as substitute reviewer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476#-:-N5okvDeBZSH-1UBl_gS:b-sy1kzv)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @amcastro-tri and @ggould-tri)

**Comment by ggould-tri** [comment]
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1382 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17476#-N5kgygK7W7xbS67Iq5a:-N5onIMV3rjwDfEqwiwe:b-bu184m) ([raw file](https://github.com/robotlocomotion/drake/blob/fa8181d940a295c25195426948b9908211c59c44/multibody/plant/test/compliant_contact_manager_test.cc#L1382)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm slightly surprised by the need to 5x `kEps`. I think they `ac.get_vdot()` and `a_expected` go through the exact same code path and thus should be identical?
</blockquote></details>

Indeed on my (bazel/gcc) environment it passes with zero tolerance.  Raising this to a real issue:  That 5.0 needs an explanatory signpost (if, e.g., this was needed on macsim or some other uncommon platform), or else this should be kEps (for consistency) or just zero (if the computational path is so obvious as to be a necessary feature of the class).

**Review by ggould-tri — COMMENTED** [review]
:lgtm: pending discussions below.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476#-:-N5p2lmnB-Taf_Ihys_J:b-3qds46)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 942 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17476#-N5kgLgG810-hGaut43H:-N5pPMU24gPheEeWacZt:brpmqc3) ([raw file](https://github.com/robotlocomotion/drake/blob/fa8181d940a295c25195426948b9908211c59c44/multibody/plant/compliant_contact_manager.cc#L942)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this comment doesn't mean much standing alone here. Could you expand on it?
</blockquote></details>

removed.
___
*[`multibody/plant/test/compliant_contact_manager_test.cc` line 1382 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17476#-N5kgygK7W7xbS67Iq5a:-N5pPuWt3oUX0rm2PrFB:bcg0l2f) ([raw file](https://github.com/robotlocomotion/drake/blob/fa8181d940a295c25195426948b9908211c59c44/multibody/plant/test/compliant_contact_manager_test.cc#L1382)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Indeed on my (bazel/gcc) environment it passes with zero tolerance.  Raising this to a real issue:  That 5.0 needs an explanatory signpost (if, e.g., this was needed on macsim or some other uncommon platform), or else this should be kEps (for consistency) or just zero (if the computational path is so obvious as to be a necessary feature of the class).
</blockquote></details>

I believe @xuchenhan-tri is right that this should be zero. I'll start the mac CI to verify.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: do not merge) wait for mac CI above.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17476#-:-N5pZHqH8UvQisZNLaco:b-hp63r5)* status: labeled "do not merge" (waiting on @amcastro-tri)

**Comment by amcastro-tri** [comment]
Mac CI passed. Merged.

**Pull request merged**
