### PR TITLE
geometry:optimization: small refactor to purge multibody dependency

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@damrongguoy for feature review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251#-:-MdIyKs_8YzOQsEaxkLn:btmqqqb)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251#-:-MdJmrit7oQ1ejOGJz5l:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15251#-MdJgep11SlmaEnvuG54:-MdJgep11SlmaEnvuG55:b16wnu9) (no related file):*
I have a minor question. I have just noticed that when I run `bazel-bin/geometry/optimization/convex_set_test`, I will see messages like these: 
```
[ RUN      ] HPolyhedronTest.UnitBoxTest
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999998 (2)
Clp0001I Primal infeasible - objective value 0
[       OK ] HPolyhedronTest.UnitBoxTest (9 ms)
[ RUN      ] HPolyhedronTest.ArbitraryBoxTest
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999997 (3)
Clp0001I Primal infeasible - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999997 (3)
Clp0001I Primal infeasible - objective value 0
[       OK ] HPolyhedronTest.ArbitraryBoxTest (5 ms)
...
[ RUN      ] HPolyhedronTest.InscribedEllipsoidTest
----------------------------------------------------------------------------
        SCS v2.1.3 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 87
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
...
----------------------------------------------------------------------------
c'x = -1.8544, -b'y = -1.8544
============================================================================
[       OK ] HPolyhedronTest.InscribedEllipsoidTest (22 ms)
...
```

I confirm that it is intentional.  There's nothing wrong with it.  I just want to confirm.

---

**Comment by hongkai-dai** [comment]
@DamrongGuoy That print out message is due to the CLP solver. I haven't figured out how to turn off that print out yet. I opened an issue on CLP upstream https://github.com/coin-or/Clp/issues/194, but haven't heard back from the authors.

**Comment by hongkai-dai** [comment]
The other print out message is from SCS, we can turn it off manually, but the default is to print out the SCS progress.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15251#-MdJgep11SlmaEnvuG54:-MdJrZ8E-D_8CtAaXSBA:b-rgi24h) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I have a minor question. I have just noticed that when I run `bazel-bin/geometry/optimization/convex_set_test`, I will see messages like these: 
```
[ RUN      ] HPolyhedronTest.UnitBoxTest
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999998 (2)
Clp0001I Primal infeasible - objective value 0
[       OK ] HPolyhedronTest.UnitBoxTest (9 ms)
[ RUN      ] HPolyhedronTest.ArbitraryBoxTest
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999997 (3)
Clp0001I Primal infeasible - objective value 0
Clp0006I 0  Obj 0 Primal inf 0.2999997 (3)
Clp0001I Primal infeasible - objective value 0
[       OK ] HPolyhedronTest.ArbitraryBoxTest (5 ms)
...
[ RUN      ] HPolyhedronTest.InscribedEllipsoidTest
----------------------------------------------------------------------------
        SCS v2.1.3 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 87
eps = 1.00e-05, alpha = 1.50, max_iters = 5000, normalize = 1, scale = 1.00
...
----------------------------------------------------------------------------
c'x = -1.8544, -b'y = -1.8544
============================================================================
[       OK ] HPolyhedronTest.InscribedEllipsoidTest (22 ms)
...
```

I confirm that it is intentional.  There's nothing wrong with it.  I just want to confirm.
</blockquote></details>

It is a defect for the `HPolyhedron::MaximumVolumeInscribedEllipsoid` implementation to print to cout or cerr when called by the user.  All of our console output must always happen via `drake::log()`.  Perhaps it's not a new defect as of this PR, so it shouldn't hold up this changeset, but it is a bug that should get fixed.

In cases where the user calls "Solve" directly themselves we've been lax about enforcing this, but anywhere we _programatically_ call Solve on behalf of the user, we should be sure that the solver will not spam the user.

---

**Comment by hongkai-dai** [comment]
I can change the default setting of SCS to turn off the print out. I don't know how to turn of the print out for CLP yet (I agree it is annoying)

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for platform review (tuesday or monday, as you prefer)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251#-:-MdJte7R4dZxmsn5elqH:blm3299)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
>  I don't know how to turn of the print out for CLP yet (I agree it is annoying)

=> https://github.com/RobotLocomotion/drake/pull/15254

**Review by RussTedrake — COMMENTED** [review]
@hongkai-dai -- will you follow through with the SCS change, please?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251#-:-MdKVgmE21dnB-nvq6Fc:bpknu4d)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by RussTedrake — COMMENTED** [review]
My SceneGraph comfort/skills are increasing.  No need to publicly comment about whether you think that is a good thing.  ;-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251#-:-MdNHxWrAukXwn6YzQf5:b-viyv23)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),DamrongGuoy (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[geometry/optimization/test/convex_set_test.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15251#-MdN54mO5H7AZAOiDs_o:-MdNHiYf2JHcLK0hh0I9:b-f9ot8i) ([raw file](https://github.com/robotlocomotion/drake/blob/5b9bda30102e0d925986e578c9342bf56792ac8d/geometry/optimization/test/convex_set_test.cc#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Perhaps a note that indicates that for the new frame F, `X_WF = X_WG`? This kind of bothered me in the previous incarnation as well. The *point* of picking this frame is so that points expressed in the geometry's canonical frame can be used to test inside/outside.

However, given the point variable names eschew monogram notation, and the polyhedron itself lacks an indication of what frame it is defined in (e.g., `poly_F` or `poly_W`), the ability for the reader to infer frames is strongly hampered.

(And I would take the opportunity to emphasize that the convex set documentation should emphasize that a convex set is a "quantity" and therefore subject to monogram notation: i.e., it should be associated with a frame and points queried against the set must likewise be measured/expressed in the same frame.)
</blockquote></details>

Done.  I've added that note.
I've been using monogram throughout for concepts that are bound to 3D.  I have not been using it for N-dimensions.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15251)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),DamrongGuoy (waiting on @RussTedrake)

___
*[geometry/optimization/test/convex_set_test.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15251#-MdN54mO5H7AZAOiDs_o:-MdNJ6llDsZ8b-HGXTId:b-yk7e85) ([raw file](https://github.com/robotlocomotion/drake/blob/5b9bda30102e0d925986e578c9342bf56792ac8d/geometry/optimization/test/convex_set_test.cc#L121)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I've added that note.
I've been using monogram throughout for concepts that are bound to 3D.  I have not been using it for N-dimensions. 
</blockquote></details>

I respectfully disagree.  This test gets a box from `SceneGraph` (it is in 3D). We have the initial polyhedron `H` (and not `H_W`). We have the polyhedron `H_P`. I *might* infer that `frame_id` identifies frame `P`, but that's meeting you more than half way. We also have point names `in*` and `out*` which indicate no frames (but, if we read carefully, we can know they are in the world frame).

In fact, the last lines about `in1` being *out* is only because you've carefully sized the box and posed the box such that any the points in the world, when interpreted as points in the frame, don't lie in any "common region" (if such a thing exists...I haven't looked at it carefully).

And this subject is larger -- the documentation of `ConvexSet` and `ConvexSet::PointInSet` should include this topic. A `ConvexSet` is measured and expressed in a particular frame by construction. Any point queried against it should be measured and expressed in that same frame.

That said, I'm not going to block on this. I wrote `btw` and I'll stand by that, but I felt it my duty to raise the issue.

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/test/convex_set_test.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15251#-MdN54mO5H7AZAOiDs_o:-MdNL5r65Cnq6_NjQzLn:b-jq2ivt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b9bda30102e0d925986e578c9342bf56792ac8d/geometry/optimization/test/convex_set_test.cc#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I respectfully disagree.  This test gets a box from `SceneGraph` (it is in 3D). We have the initial polyhedron `H` (and not `H_W`). We have the polyhedron `H_P`. I *might* infer that `frame_id` identifies frame `P`, but that's meeting you more than half way. We also have point names `in*` and `out*` which indicate no frames (but, if we read carefully, we can know they are in the world frame).

In fact, the last lines about `in1` being *out* is only because you've carefully sized the box and posed the box such that any the points in the world, when interpreted as points in the frame, don't lie in any "common region" (if such a thing exists...I haven't looked at it carefully).

And this subject is larger -- the documentation of `ConvexSet` and `ConvexSet::PointInSet` should include this topic. A `ConvexSet` is measured and expressed in a particular frame by construction. Any point queried against it should be measured and expressed in that same frame.

That said, I'm not going to block on this. I wrote `btw` and I'll stand by that, but I felt it my duty to raise the issue.
</blockquote></details>

I've got a bunch of methods/classes in this hierarchy waiting to PRs (I'm trying to break them up small for you, but it's definitely slowing things down).  I'll try to make improvements in this respect as I touch them up.

**Pull request merged**
