### PR TITLE
Removed "make options" from homebrew instructions

### PR DESCRIPTION
**Pull request by naveenoid**
Fixes https://github.com/RobotLocomotion/drake/issues/3581

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3582)

### CODE REVIEW

**Comment by naveenoid** [comment]
@liangfok for feature review
@sherm1 for platform review

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3582#-:-KSa6r4oj6hett5nVdfb:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
-@sherm1, +@david-german-tri, :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3582#-:-KSbD4csf1uEuO2-gmrV:bq8qsx0)*

**Pull request merged**
