### PR TITLE
[workspace] Remove scipy dependency.

### LINKED ISSUE #14691: Remove scipy dependency
It is barely used and the code that uses it really should be able to avoid doing so without too much more complexity. We are very disk space constrained on GitHub Actions so every megabyte counts with large dependencies, and Google Colab prefers certain versions of certain dependencies that may or may not align with an Ubuntu provided version.

FYI @RussTedrake @jwnimmer-tri.

### PR DESCRIPTION
**Pull request by svenevs**
Closes #14691.

Results from `grep -ri scipy . --exclude-dir=.git` from commit ee74dae71084726a6b9a44ba499e9792476dd866:

- [X] Comments / class names that can be ignored: `./math/test/bspline_basis_test.cc`
    - `./math/test/bspline_basis_test.cc:175:generated by scipy.interpolate.Bspline.basis_element():`
    - `./math/test/bspline_basis_test.cc:177:    from scipy.interpolate import BSpline`
    - `./math/test/bspline_basis_test.cc:194:NOTE(avalenzu): Scipy gives B[6](1.0) = 0.0, which is wrong. That value has`
    - `./math/test/bspline_basis_test.cc:198:TYPED_TEST(BsplineBasisTests, EvaluateBasisFunctionIScipyComparison) {`
 - [X] Vendored via #16592: `./bindings/pydrake/systems/_resample_interp1d.py` 
    - `./bindings/pydrake/systems/_resample_interp1d.py:1:# Copyright (c) 2001-2002 Enthought, Inc. 2003-2022, SciPy Developers.`
    - `./bindings/pydrake/systems/_resample_interp1d.py:35:# scipy.interpolate.interp1d for the purposes of animation in`
    - `./bindings/pydrake/systems/_resample_interp1d.py:45:    A linear interpolation only version of scipy.interpolate.interp1d.`
- [X] Removed in this PR: `./setup/mac/binary_distribution/Brewfile:29:brew 'scipy'` 
- [X] Removed in this PR: `./setup/ubuntu/binary_distribution/packages-focal.txt:59:python3-scipy`
- [X] Removed in this PR: `./setup/ubuntu/binary_distribution/packages-bionic.txt:58:python3-scipy`
- [X] Removed in this PR: `./setup/ubuntu/source_distribution/packages-bionic-test-only.txt:15:python3-scipy-dbg`
- [X] Removed in this PR: `./setup/ubuntu/source_distribution/packages-focal-test-only.txt:16:python3-scipy-dbg`
- [X] `fmin` stubbed via #16759: `./examples/acrobot/optimizer_demo.py`
    - `./examples/acrobot/optimizer_demo.py:23:    from scipy.optimize import fmin`
    - `./examples/acrobot/optimizer_demo.py:25:    print("WARNING: scipy not installed, using stubbed non-minimizing "`
    - `./examples/acrobot/optimizer_demo.py:29:        """Dummy version of scipy.optimize.fmin.`
    - `./examples/acrobot/optimizer_demo.py:30:        It allows scipy to be an optional dependency."""`
    - ``./examples/acrobot/optimizer_demo.py:70:    """Runs `scipy.optimize.fmin` over the `controller_params` of scenario``
- [X] Comment which can be ignored: `./common/proto/call_python_client.py:257:        @ref https://scipython.com/book/chapter-6-numpy/examples/creating-a-magic-square  # noqa`
- [ ] Removed in this PR: `./tools/wheel/image/setup.py:19:    'scipy',`
    - [ ] Confirm via CI it builds correctly (unprovisioned build).
- [ ] Drake visualizer.
    - [X] Removed in this PR: `./tools/workspace/drake_visualizer/image/prereqs:41:python3-scipy`
    - Via work on #16448 I discovered that #16185 broke the drake visualizer tarball build.  Since it needs to get fixed, I will be opening an unrelated PR to this with the fixes (and `rpath` fixes so we do not have to post-process in deb packaging).  As such, since it is currently broken, lets remove it here in this PR and fix it in a followup.  I have built the binaries using docker with this change (no `scipy` installed) and it builds succesfully.
    - [ ] https://github.com/RobotLocomotion/drake/issues/14691#issuecomment-1074213247 Dead code investigation is needed.
- [X] Comment which can be ignored: `./tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_image.py:311:    matplotlib, scipy).`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16836)

### CODE REVIEW

**Comment by svenevs** [comment]
Including release and debug builds due to tests using scipy-dbg, may be overkill but the mac jobs will dwarf this test anyway.

Wheel:

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.

Linux:

@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please.

macOS:
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

**Review by svenevs — COMMENTED** [review]
+@jwnimmer-tri for feature review please, main point of interest is `Dead code investigation is needed.` for `director`.

CC @BetsyMcPhail

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16836#-:-Mymomlk0bvWaKc9yZOz:blc5q5q)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Code is OK so far.  I'll look into `director` stuff soon.

Note that Unprovisioned CI has uncovered some lurking use of `scipy` somewhere.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16836#-:-Myn4Plo3Xyq-mWp0nmf:b-kp5ryh)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @svenevs)

**Comment by svenevs** [comment]
Going to update the main issue, this will need to be a new ticket to address and rebase this PR.

**Comment by jwnimmer-tri** [comment]
FYI It's from https://github.com/RobotLocomotion/pybind11/blob/5df3c0028c6278b96a1d2aec6f279c9543315282/include/pybind11/eigen.h#L715-L729.

**Comment by jwnimmer-tri** [comment]
Because of pydrake` uses `scipy` in earnest at the moment, we'll need to announce this removal via deprecation and wait for 3+ months before merging this PR.

I think it makes sense to work on getting it to pass CI now to prove that we've fully solved the problem, but once that's ready we should close it (to clear the dashboard) and then re-open it once the date expires (2022-07-01).

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-debug please.
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-monterey-unprovisioned-clang-cmake-experimental-release please.

Rerunning now to confirm stubs PR while CI is relatively quiet.

**Comment by svenevs** [comment]
> I think it makes sense to work on getting it to pass CI now to prove that we've fully solved the problem, but once that's ready we should close it (to clear the dashboard) and then re-open it once the date expires (2022-07-01).

Agreed, will close after CI results come in.

**Pull request closed without merging**
