### PR TITLE
Add NaN cell type to symbolic expression

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4718)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Related issue: https://github.com/RobotLocomotion/drake/issues/4660

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , both reviews please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-:-Ka3xqHtoY0q-reMx4qB:b-mbs47t)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka467AD6LxIE2TTFctS:-Ka467AEjP-tcFYt89uT:bsacekx) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression.cc#L84)):*
> ```cpp
> 
> Expression Expression::NaN() {
>   static const Expression e{make_shared<ExpressionNaN>()};
> ```

BTW *Meta* For a separate-PR ... shouldn't all of the `statics` in these factory methods be `drake::never_destroyed`?  They aren't trivial destroyable, so we don't want to run them on program exit.

---

*[drake/common/symbolic_expression_cell.cc, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka46rlOEJ7ZD37Rde7g:-Ka46rlOEJ7ZD37Rde7h:b-gflu4w) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression_cell.cc#L184)):*
> ```cpp
> }
> 
> ExpressionNaN::ExpressionNaN() : ExpressionCell{ExpressionKind::NaN, 41} {}
> ```

A comment why 41 was chosen?

---

*[drake/common/symbolic_expression_cell.cc, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka477prCUvhCRKwst_s:-Ka477prCUvhCRKwst_t:b-ciom25) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression_cell.cc#L205)):*
> ```cpp
> 
> ostream& ExpressionNaN::Display(ostream& os) const {
>   ostringstream oss;
> ```

Unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-:-Ka47mWTlMO6aRS9VLr1:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka467AD6LxIE2TTFctS:-Ka4FtZnZa0otxrgNYxE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression.cc#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW *Meta* For a separate-PR ... shouldn't all of the `statics` in these factory methods be `drake::never_destroyed`?  They aren't trivial destroyable, so we don't want to run them on program exit.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 184 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka46rlOEJ7ZD37Rde7g:-Ka4FwZd56AwWIlwJ-DQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression_cell.cc#L184)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

A comment why 41 was chosen?
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression_cell.cc, line 205 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4718#-Ka477prCUvhCRKwst_s:-Ka4Fx2Q_V4kr3mhH8J7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ce7645e72baec12567d1603d8dd23ec6bd194788/drake/common/symbolic_expression_cell.cc#L205)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4718)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4718)*

**Pull request merged**
