### PR TITLE
[geometry/optimization] Expose the costs and constraints of an Edge in GraphOfConvexSets

### PR DESCRIPTION
**Pull request by mpetersen94**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@russtedrake for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892#-:-MzWJyBu8FPB-AlRd_-n:b-nden6u)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892#-:-MzblDIw6a5DfH98W6XQ:b593w5t)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri platform review.
platform :lgtm: with a question and a couple of nits.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892#-:-MzcpOJKCrZ5SZht_MPL:b-nksn9w)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94)

___
*[geometry/optimization/graph_of_convex_sets.h, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-MzcogcIEplq7vVG8mw5:-MzcogcIEplq7vVG8mw6:b-8mf2hs) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/graph_of_convex_sets.h#L210)):*
> ```objc
> 
>     /** Returns all costs on this edge. */
>     std::vector<solvers::Binding<solvers::Cost>> GetCosts() const {
> ```

Why can't we return a const reference here?
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 238 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-Mzcokzd21pde6ykHaob:-Mzcokzd21pde6ykHaoc:b-9esle) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/test/graph_of_convex_sets_test.cc#L238)):*
> ```cpp
> 
>   // Confirm that they are all accessible.
>   auto edge_costs = e_->GetCosts();
> ```

nit, this can be const.
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-Mzcp5t47fVp3TzdJJKu:-Mzcp5t47fVp3TzdJJKv:beafee3) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/test/graph_of_convex_sets_test.cc#L239)):*
> ```cpp
>   // Confirm that they are all accessible.
>   auto edge_costs = e_->GetCosts();
>   EXPECT_TRUE(edge_costs[0] == b0);
> ```

BTW, you could do `EXPECT_EQ(edge_costs[0], b0);` here.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[geometry/optimization/graph_of_convex_sets.h, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-MzcogcIEplq7vVG8mw5:-MzdF1z1EkS9DUKWf1_h:bytv0gw) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/graph_of_convex_sets.h#L210)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Why can't we return a const reference here?
</blockquote></details>

I actually just had the same thought.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: 1 unresolved discussion, missing label for release notes (waiting on @xuchenhan-tri)

___
*[geometry/optimization/graph_of_convex_sets.h, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-MzcogcIEplq7vVG8mw5:-N-0-yzuD-Wob2sNQSZ5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/graph_of_convex_sets.h#L210)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I actually just had the same thought.
</blockquote></details>

Done.
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 238 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-Mzcokzd21pde6ykHaob:-N-00A2S-Mqz20YO21h6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/test/graph_of_convex_sets_test.cc#L238)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this can be const.
</blockquote></details>

Done.
___
*[geometry/optimization/test/graph_of_convex_sets_test.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-Mzcp5t47fVp3TzdJJKu:-N-008JrE-VjoN4vA9hw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/test/graph_of_convex_sets_test.cc#L239)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, you could do `EXPECT_EQ(edge_costs[0], b0);` here.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: 2 unresolved discussions, missing label for release notes (waiting on @mpetersen94 and @RussTedrake)

___
*[geometry/optimization/graph_of_convex_sets.h, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-MzcogcIEplq7vVG8mw5:-N-00eG_2LPxxwCpplXL:b-y5l9vf) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/graph_of_convex_sets.h#L210)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `const` in return by value doesn't do anything. We want to return a const reference here.



_Suggestion:_
```objc
    const std::vector<solvers::Binding<solvers::Cost>>& GetCosts() const {
```
___
*[geometry/optimization/graph_of_convex_sets.h, line 215 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16892#-N-01W271PMGIa2837eJ:-N-01W271PMGIa2837eK:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/3e4072495b353fbe1f3a9f459b287cf5398cfe0e/geometry/optimization/graph_of_convex_sets.h#L215)):*
> ```objc
> 
>     /** Returns all constraints on this edge. */
>     const std::vector<solvers::Binding<solvers::Constraint>> GetConstraints()
> ```





_Suggestion:_
```objc
const std::vector<solvers::Binding<solvers::Constraint>>& GetConstraints()
```

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892#-:-N-08flK2-JUKZMn1Q__:b-c7f1bi)* status: 2 unresolved discussions (waiting on @mpetersen94 and @RussTedrake)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[geometry/optimization/graph_of_convex_sets.h, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16892#-MzcogcIEplq7vVG8mw5:-N-0BcVY-mYizjZ9gXqJ:bc5a45h) ([raw file](https://github.com/robotlocomotion/drake/blob/20baea3ea9632c9bbcdfcc0110ca4af995aba584/geometry/optimization/graph_of_convex_sets.h#L210)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The `const` in return by value doesn't do anything. We want to return a const reference here.
</blockquote></details>

Oops! Done.
___
*[geometry/optimization/graph_of_convex_sets.h, line 215 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16892#-N-01W271PMGIa2837eJ:-N-0Be8O8-CJ3t1Sz6Uz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3e4072495b353fbe1f3a9f459b287cf5398cfe0e/geometry/optimization/graph_of_convex_sets.h#L215)):*
> ```objc
> 
>     /** Returns all constraints on this edge. */
>     const std::vector<solvers::Binding<solvers::Constraint>> GetConstraints()
> ```

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @mpetersen94)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16892)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @mpetersen94)

**Pull request merged**
