### PR TITLE
[multibody] Re-add an inverse kinematics benchmark resolving CI issues

### PR DESCRIPTION
**Pull request by aykut-tri**
This PR aims to resolve the CI issues of the reverted PR https://reviewable.io/reviews/robotlocomotion/drake/17299

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)

### CODE REVIEW

**Comment by aykut-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by aykut-tri — COMMENTED** [review]
This PR aims to fix the issues with https://reviewable.io/reviews/robotlocomotion/drake/17299 that fail the CI for the mac-big-sur build. The problem was identified and resolved by the build cop through a revert PR: https://reviewable.io/reviews/robotlocomotion/drake/17361.

To prevent such failures, the original problem has been further relaxed by larger tolerances, fewer initial guesses, and smaller range for random joint pose generation. The previously failing job has been confirmed to succeed for the updated version.

+@hongkai-dai for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4Ei7XjCmQC580q-HHP:b-8iayu9)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4Exol6AstMt3alyIjZ:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4T-FHeB2kJGj_zuPiX:b-qsst0j)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

For the record, it is your intent to squash these commits, right? Even more, I'd change the commit message to be what the original commit message was. Looking at the original PR, I can see the original commit message was a single line. However, the PR description was *beautiful*. I'd love it if the description made it in as part of the commit message. But this is optional: the most important part is squashing and having the commit message represent the *original* commit message.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4THrBi57a0usJDho--:bxlcnh7)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @aykut-tri)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @aykut-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @aykut-tri)

___
*[`multibody/benchmarking/iiwa_relaxed_pos_ik.cc` line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4boWwKELCcMLfXbygH:-N4boWwKELCcMLfXbygI:b9gwq3y) ([raw file](https://github.com/robotlocomotion/drake/blob/2e852bf52c9ba8b977c65d5a88741751120849c4/multibody/benchmarking/iiwa_relaxed_pos_ik.cc#L110)):*
> ```cpp
>         // we're rather interested in measuring the speed of constraint
>         // evaluation.
>         auto result = solvers::Solve(*prog);
> ```

BTW I'm surprised this isn't getting angry. Unused `result`?

**Review by aykut-tri — COMMENTED** [review]
@seancurtis-tri, thanks for the feedback and sorry for the delay. I've squashed the commits such that the resulting commit has the original single-line message as the title and the PR description in the description (as well as info on the squashed commits).

In addition, per our discussion with @hongkai-dai, I've removed the checks on the optimization result to make the code easier to maintain. The reasoning is that this benchmark is intended to measure the computation performance of constraint evaluation in nonlinear programming, and we aren't interested in optimality or feasibility.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4bmw2i-1-DaPOy6_J2:b1beeo4)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`multibody/benchmarking/iiwa_relaxed_pos_ik.cc` line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4boWwKELCcMLfXbygH:-N4btp0iDIL_2mnvhvbA:bntz81o) ([raw file](https://github.com/robotlocomotion/drake/blob/2e852bf52c9ba8b977c65d5a88741751120849c4/multibody/benchmarking/iiwa_relaxed_pos_ik.cc#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm surprised this isn't getting angry. Unused `result`?
</blockquote></details>

Good point (I also don't know why it doesn't complain), I removed `result` altogether as well as the redundant dependencies. Thanks!

**Comment by aykut-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @aykut-tri)

___
*[`-- commits` line 6 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4gnZX014ifLO8djuOr):*
nit: Is this still true? With the removal of snopt as a dependency (and exercise in the main code), this comment probably needs to be revisited.

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`-- commits` line 6 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4gnZX014ifLO8djuOr):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Is this still true? With the removal of snopt as a dependency (and exercise in the main code), this comment probably needs to be revisited.
</blockquote></details>

I think so, that library was used only for the following check. I've confirmed in a fresh build (i.e., after `bazel clean` & `bazel build //...`) that I can still run `bazel run --config snopt //multibody/benchmarking:iiwa_relaxed_pos_ik` successfully.

I've also updated the numerical results for the latest version of the benchmark, so thanks for bringing this up!



_Code snippet:_
```
        // Confirm that the optimization has succeeded.
        // This is done only for SNOPT b/c IPOPT exceeds the maximum number of
        // iterations in a few cases while still meeting the task constraints.
        if (result.get_solver_id() == solvers::SnoptSolver::id())
          DRAKE_DEMAND(result.is_success());
```

**Comment by jwnimmer-tri** [comment]
*[`-- commits` line 6 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4gnZX014ifLO8djuOr):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

I think so, that library was used only for the following check. I've confirmed in a fresh build (i.e., after `bazel clean` & `bazel build //...`) that I can still run `bazel run --config snopt //multibody/benchmarking:iiwa_relaxed_pos_ik` successfully.

I've also updated the numerical results for the latest version of the benchmark, so thanks for bringing this up!
</blockquote></details>

That might be true, but irrelevant.

Commit messages should describe the code that is being change.  This table of runtimes is a description of _your personal computer_, not this code.

For that reason, never place benchmark results in a commit message.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @aykut-tri and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

___
*[`-- commits` line 6 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17373#-N4gnZX014ifLO8djuOr):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That might be true, but irrelevant.

Commit messages should describe the code that is being change.  This table of runtimes is a description of _your personal computer_, not this code.

For that reason, never place benchmark results in a commit message.
</blockquote></details>

True that!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: 1 unresolved discussion, missing label for release notes (waiting on @aykut-tri and @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: missing label for release notes (waiting on @aykut-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: missing label for release notes (waiting on @aykut-tri)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373)* status: missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
A/B results -- using a newly added `drake_py_experiment_binary`, i.e., disabling CPU speed variations -- for running the benchmark w/ SNOPT (applying the changes with respect to c37e81c, i.e., w/o rebasing w/ the latest master):
 ```
    -------------------------------------------------------------------
    Derivative           Time            CPU            Iterations
    -------------------------------------------------------------------
    AlgoDiff          14525259 ns     14523719 ns           51
    Analytical        13453095 ns     13451967 ns           54
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4hvYuI3J875O8kLwbU:b-kd54ho)* status: missing label for release notes (waiting on @aykut-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
To merge this needs a release notes label. You're adding an accessible benchmark, so that seems to require release notes as a feature, yes? I've tentatively added this. Please confirm (and modify as necessary) before merging.

+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4iAPnYBS2-etx_lchF:b-236hmq)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
I've just assigned "release notes: none" as Hongkai did in the original PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17373#-:-N4iBIbeA4HQ37ju92kx:b8tb9kp)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @aykut-tri)

**Comment by SeanCurtis-TRI** [comment]
oops...why do we have folders `multibody/benchmarking` and `multibody/benchmarks`?

**Comment by jwnimmer-tri** [comment]
> multibody/benchmarking

This is for runtime performance metrics, and is our standard name for suchl

> multibody/benchmarks

This one is the output of Paul's job.  Writing out the "golden answers" for mechanics problems.

**Comment by SeanCurtis-TRI** [comment]
@jwnimmer-tri As long as you're around and commenting -- it is the standard that "benchmarking" stuff is not part of release notes? I have no certain knowledge but hypothesized why this might be the case.

**Comment by jwnimmer-tri** [comment]
The document at https://drake.mit.edu/reviewable.html#release-notes should explain.  If the answer is still unclear, then we should fix it by probing your confusion in slack (`#platform_review`) to understand where the language went wrong.

**Comment by SeanCurtis-TRI** [comment]
In this case the documentation is insufficient. It's partly tautological. Use "feature" or "fix" if you have a feature or a fix. Or possibly undefined -- use "none" if it doesn't "meaningfully affect the release". I don't know if creating a public build target that is a benchmark binary "affects the release". I suspect, no matter what, it's not a fix. I could define "meaningfully affect the release" as "apparent in an *installed* version of drake". I don't know if that definition is correct or complete. But even if I assume it's sufficient, I'd have to go spelunking to find out if this would satisfy that particular property.

So, the document gives guidance along the lines of: if you have properly classified the change, this is the tag you use. But it is sparse in terms of properly classifying the change.

**Pull request merged**
