### PR TITLE
Remove egregious error of removing from a set being range iterated over

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Addresses issue #9791

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9796)

### CODE REVIEW

**Comment by RussTedrake** [comment]
fwiw -- we managed to "figure out" a way to make the world_id consistently 1 for both python and c++, but there was still come confusion on why the apple object was being treated incorrectly (even if world_id == 2).

**Comment by RussTedrake** [comment]
the "fix" we figured out this afternoon is here:
https://github.com/RussTedrake/drake/commit/e2d71df02f2f3ddb07fcc4a29f58b93025c76626

**Comment by jwnimmer-tri** [comment]
The fix is an improvement, at least.  GSG prohibits non-POD globals, for good reason.  (The fix should use never_destroyed, though.)

If you are having problems with globals in python vs C++ though, I wonder if you're hitting the ODR problems?  Ah, yes -- depending on //examples/manipulation_station from a pydrake module as in https://github.com/RussTedrake/drake/blob/f62df45/bindings/pydrake/examples/BUILD.bazel#L66 is abusing the linker, and will give you multiple independent copies of your globals.  You should add the manipulation_station to the install/libdrake list of bazel packages to link into libdrake.so, not deps on it directly.

**Comment by sherm1** [comment]
FrameId is a POD (just an int64_t) so shouldn't require never_destroyed.

**Comment by jwnimmer-tri** [comment]
Its API contract does not promise that nobody will ever add a dtor (that is already trivially destructible).  You could imagine someone adding `value_ = 0;` in debug builds.  Better safe than sorry.  Better to always use never_destroyed for globals, so its easy to cargo-cult successfully without being a C++ expert.

**Pull request merged**
