### PR TITLE
Fixed OSX bazel debug instructions.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5818)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for all reviews please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818#-:-KhcYHAFvuW0LKBLUSap:b2l2vdx)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818#-:-KhcYdrW_v_QC89MPBXf:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818)*

**Comment by soonho-tri** [comment]
-@david-german-tri 
+@soonho-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818#-:-KhcYgoQgMNZbKZY1gKQ:b-ck8d84)*

**Comment by liangfok** [comment]
Thanks @soonho-tri!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818#-:-KhcYk2RnVU9ohlYm0Fv:bpg9igj)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5818#-:-KhckFW2_rTtV3gK8oHo:bnfp4nl)*

**Pull request merged**
