### PR TITLE
Add solver_type_converter; avoid solver_type in C++ code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See individual commit descriptions for more detail.

Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6462)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review please?  Or else ping me and I can re-assign.

**Comment by hongkai-dai** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6462)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6462#-:-Knm7Ot3-AkZ4xkihIXV:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review per on-call rotation, please.

**Comment by soonho-tri** [comment]
:lgtm: nice!

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6462#-:-Kno6ZTmPci-ZTYz8m0O:b-7yytuz)*

**Pull request merged**
