### PR TITLE
Remove DrivingCommand from IdmController and MobilPlanner

### PR DESCRIPTION
**Pull request by jadecastro**
Specifically:

- `IdmController` now outputs an acceleration value as a singleton `BasicVector` (instead of a `DrivingCommand` with zeroed-out steering value).
- `MobilPlanner` accepts an acceleration value as an additional input as a singleton `BasicVector` (instead of producing an acceleration command as an additional output via an internally-computed IDM equation).

+@liangfok for feature review, please.
+@jwnimmer-tri for platform review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5784)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/mobil_planner.h, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhODhppawIM6t2qAhAC:-KhODhpq031XAeqJ8EGu:b-or8uvn) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/mobil_planner.h#L113)):*
> ```objc
>                       const systems::rendering::FrameVelocity<T>& ego_velocity,
>                       const systems::rendering::PoseBundle<T>& traffic_poses,
>                       const systems::BasicVector<T>& driving_command,
> ```

BTW This should track the rename in the `.cc` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-:-KhOE9kmszJCM76vCeJh:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm: Just a few comments.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/mobil_planner.h, line 155 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOH8Bk4P_1WKja6aDb:-KhOH8Bk4P_1WKja6aDc:b-y9ahmy) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/mobil_planner.h#L155)):*
> ```objc
>   const bool with_s_{true};
> 
>   // Index for the lane output port.
> ```

BTW, this comment needs updating.

---

*[drake/automotive/test/mobil_planner_test.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOHuubdrc6wA_TNKhq:-KhOHuuc0hG1YRXr-j8B:b-eikcmr) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L101)):*
> ```cpp
>     context_->FixInputPort(ego_velocity_input_index_, std::move(ego_velocity));
> 
>     // Mock up an command acceleration for the ego car.
> ```

BTW: nit: "an" --> "a"

---

*[drake/automotive/test/mobil_planner_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOI0RbP0Cnc4X3k3uA:-KhOI0RbP0Cnc4X3k3uB:bsfxi8i) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L106)):*
> ```cpp
>     (*acceleration_command)[0] = kEgoAccelerationCommand;
>     context_->FixInputPort(ego_acceleration_input_index_,
>                            std::move(acceleration_command));
> ```

BTW, this could spelled more concisely:

```
    context_->FixInputPort(ego_acceleration_input_index_,
                           systems::BasicVector<T>::Make(0));

```

---

*[drake/automotive/test/mobil_planner_test.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOIqEowEsrr6vsBz5d:-KhOIqEowEsrr6vsBz5e:bqski94) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L129)):*
> ```cpp
>   std::unique_ptr<systems::Context<double>> context_;
>   std::unique_ptr<systems::SystemOutput<double>> output_;
>   std::unique_ptr<maliput::api::RoadGeometry> road_;
> ```

BTW, I believe `std_unique_ptr` member variables may need mustaches.

---

*[drake/automotive/test/mobil_planner_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOIdxxl0XbUl4-2hZC:-KhOIdxxl0XbUl4-2hZD:b-yzi3vz) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L137)):*
> ```cpp
>   int ego_acceleration_input_index_;
>   int traffic_input_index_;
>   int lane_output_index_;
> ```

BTW, missing mustaches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-:-KhOJ1I2nyEeg6jXlOIj:bra8l8u)*

**Comment by jadecastro** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/automotive/mobil_planner.h, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhODhppawIM6t2qAhAC:-KhOL78HWWWmVp95S4DU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/mobil_planner.h#L113)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This should track the rename in the `.cc` file.
</blockquote></details>

Done.

---

*[drake/automotive/mobil_planner.h, line 155 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOH8Bk4P_1WKja6aDb:-KhOLCuT1QZ9ltmIczDa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/mobil_planner.h#L155)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this comment needs updating.
</blockquote></details>

Done.

---

*[drake/automotive/test/mobil_planner_test.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOHuubdrc6wA_TNKhq:-KhOLKhsCeHp5FNSANUW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: "an" --> "a"
</blockquote></details>

Done.

---

*[drake/automotive/test/mobil_planner_test.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOIqEowEsrr6vsBz5d:-KhOLkiSFiezrL-r_CD6:b8vhtv) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L129)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I believe `std_unique_ptr` member variables may need mustaches.
</blockquote></details>

I'm not sure they do, since `unique_ptr` has a default constructor.

---

*[drake/automotive/test/mobil_planner_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOIdxxl0XbUl4-2hZC:-KhOMuuD2LCJ_A0Zx8mw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L137)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing mustaches.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5784)*

**Comment by jadecastro** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/mobil_planner_test.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5784#-KhOI0RbP0Cnc4X3k3uA:-KhONk4Kq7geDinIQ934:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b0924430ccba7b571971f3550a8abb855693498/drake/automotive/test/mobil_planner_test.cc#L106)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, this could spelled more concisely:

```
    context_->FixInputPort(ego_acceleration_input_index_,
                           systems::BasicVector<T>::Make(0));

```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5784)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5784)*

**Pull request merged**
