### PR TITLE
ScsSolver result reports dual solution.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Include dual solution for bounding-box, linear, second order cone constraints.
I will add the dual solution for linear equality constraints in the next PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@pangtao22 for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360#-:-NHg802_3_bfTDdk2c54:b-6b89ij)* status: LGTM missing from assignee pangtao22, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @pangtao22)

**Review by pangtao22 — COMMENTED** [review]
:lgtm: . Thanks Hongkai!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360#-:-NI3yz3R51aUbI2UAcBp:b-t3vrz0)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/scs_solver.cc` line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI3kEF53mGGuexH4GQd:-NI3kEF65fxw7Wl-Z3-0:blkbh7b) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L120)):*
> ```cpp
>   // A QuadraticCost encodes cost of the form
>   //   0.5 zᵀQz + pᵀz + r
>   // Since SCS only supports linear cost, we introduce a new slack variable y
> ```

It seems that SCS now supports quadratic costs as well? https://www.cvxgrp.org/scs/

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @pangtao22)

___
*[`solvers/scs_solver.cc` line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI3kEF53mGGuexH4GQd:-NI49R3Q5eYpf_e8oIcG:b-tc9is2) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L120)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

It seems that SCS now supports quadratic costs as well? https://www.cvxgrp.org/scs/
</blockquote></details>

Yes, I filed the github issue https://github.com/RobotLocomotion/drake/issues/18365 but haven't got time working on it yet.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360#-:-NI49fWrE3aTCDRizq7B:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @pangtao22 and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few minor issues

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360#-:-NI4xZEj4vQKhiQWtc14:b-mnjntr)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI4he-iCGRubRdxQ0d_):*
nit: the last sentence shouldn't be in the commit message
___
*[`solvers/scs_solver.cc` line 172 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI4sy2BATTWWodwga0R:-NI4sy2BATTWWodwga0S:b-st9k59) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L172)):*
> ```cpp
>     std::vector<Eigen::Triplet<double>>* A_triplets, std::vector<double>* b,
>     int* A_row_count, ScsCone* cone,
>     std::vector<std::vector<std::pair<int, int>>>* linear_con_dual_indices) {
> ```

minor: I found this abbreviation "con" confusing -- at first I thought it was a misspelling of "cone" but now I'm thinking it is short for "constraint"? Per [style guide](https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules) it is better to avoid abbreviations in general but IMO the cone/constraint adjacency here especially argues against "con" as an abbreviation.
___
*[`solvers/scs_solver.cc` line 997 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI4vlbHDfDDn4HzrQxU:-NI4vlbHDfDDn4HzrQxV:bd9tfwo) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L997)):*
> ```cpp
>   result->set_x_val(
>       (Eigen::Map<VectorX<scs_float>>(scs_sol->x, prog.num_vars()))
>           .cast<double>());
> ```

minor: this seems to be a significant change that wasn't mentioned in the PR description or commit message. The primal solution was set conditionally before (based on scs_status) but is now set unconditionally. This should be mentioned in the PR description and commit message. 

Two other requests:
- If there is an obvious place in user documentation, please note there that a (partial) solution is returned even on failure and that the dual solution is returned.
- If possible, please add a unit test that ensures that a solution is returned despite failure.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[`solvers/scs_solver.cc` line 172 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI4sy2BATTWWodwga0R:-NI9FZSABx9TtbzURifW:b-onzkld) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L172)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I found this abbreviation "con" confusing -- at first I thought it was a misspelling of "cone" but now I'm thinking it is short for "constraint"? Per [style guide](https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules) it is better to avoid abbreviations in general but IMO the cone/constraint adjacency here especially argues against "con" as an abbreviation.
</blockquote></details>

Done. I changed it to `constraint`.
___
*[`solvers/scs_solver.cc` line 997 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18360#-NI4vlbHDfDDn4HzrQxU:-NI9HqLV6oltEMcDw_KH:b8uczw4) ([raw file](https://github.com/robotlocomotion/drake/blob/e492c0a330a9f35fcfb5d8ed708e3da6d316985d/solvers/scs_solver.cc#L997)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this seems to be a significant change that wasn't mentioned in the PR description or commit message. The primal solution was set conditionally before (based on scs_status) but is now set unconditionally. This should be mentioned in the PR description and commit message. 

Two other requests:
- If there is an obvious place in user documentation, please note there that a (partial) solution is returned even on failure and that the dual solution is returned.
- If possible, please add a unit test that ensures that a solution is returned despite failure.

</blockquote></details>

Good call. I added a test in scs_solver_test to make sure the solution is set.

I haven't added it in the user documentation yet. Currently the behavior is not consistent across solvers. For some solvers, we set the solution unconditionally; for some other solvers we only set the solution at success. I think it is better if I change all solvers to return solution unconditionally, and then add it in the documentation.

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this, please.

@hongkai-dai I'm sorry, I had to restart jenkins  which interrupted your builds.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18360)* status: :shipit: complete! all discussions resolved, LGTM from assignees pangtao22,sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
