### PR TITLE
Fixed car_sim_lcm Demo

### LINKED ISSUE #3553: car_sim_lcm is broken
# The Error
The error is:

```
$ cd drake-distro/drake/automotive
$ ../../build/drake/bin/car_sim_lcm models/prius/prius.urdf models/stata_garage_p1.sdf
...
terminate called after throwing an instance of 'std::out_of_range'
  what():  Cannot set a BasicVector of size 3 with a value of size 0
Aborted (core dumped)
```

`gdb` reports a really messy backtrace due to templates:

```
gdb) bt
#0  0x00007ffff63ecc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff63f0028 in __GI_abort () at abort.c:89
#2  0x00007ffff69fda9d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff69fba76 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff69fbac1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff69fbd26 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000040a224 in __shared_count<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void>, std::allocator<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void> >, drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >&, std::shared_ptr<lcm::LCM>&> (__a=..., this=<synthetic pointer>) at /usr/include/c++/4.9/bits/shared_ptr_base.h:626
#7  __shared_ptr<std::allocator<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void> >, drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >&, std::shared_ptr<lcm::LCM>&> (__a=..., __tag=..., 
    this=<synthetic pointer>) at /usr/include/c++/4.9/bits/shared_ptr_base.h:1090
#8  shared_ptr<std::allocator<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void> >, drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >&, std::shared_ptr<lcm::LCM>&> (__a=..., __tag=..., 
    this=<synthetic pointer>) at /usr/include/c++/4.9/bits/shared_ptr.h:316
#9  allocate_shared<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void>, std::allocator<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void> >, drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >&, std::shared_ptr<lcm::LCM>&> (__a=...) at /usr/include/c++/4.9/bits/shared_ptr.h:588
#10 make_shared<drake::internal::LCMInputSystem<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >::InputVector, void>, drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> >&, std::shared_ptr<lcm::LCM>&> () at /usr/include/c++/4.9/bits/shared_ptr.h:604
#11 drake::runLCM<drake::CascadeSystem<drake::CascadeSystem<drake::Gain<drake::automotive::DrivingCommand1, drake::RigidBodySystem::StateVector>, drake::PDControlSystem<drake::RigidBodySystem> >, drake::BotVisualizer<drake::RigidBodySystem::StateVector> > > (sys=std::shared_ptr (count 2, weak 0) 0x6700c0, lcm=std::shared_ptr (count 3, weak 0) 0x62a940, t0=t0@entry=0, tf=tf@entry=inf, x0=..., options=...)
    at /home/liang/dev/drake_catkin_workspace/src/drake/drake/../drake/systems/LCMSystem.h:237
#12 0x0000000000403b39 in drake::automotive::(anonymous namespace)::do_main (argc=<optimized out>, argv=<optimized out>) at /home/liang/dev/drake_catkin_workspace/src/drake/drake/automotive/car_sim_lcm.cc:50
#13 0x00007ffff63d7f45 in __libc_start_main (main=0x4032a0 <main(int, char const**)>, argc=2, argv=0x7fffffffd6b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd6a8) at libc-start.c:287
#14 0x0000000000403307 in _start ()
```

# SHA
The above error was obtained using d26808c14c353a5f26d679ce110751dcb6f6ff5a.

### PR DESCRIPTION
**Pull request by liangfok**
This required:

1. Making `DrivingCommand1` a class.
2. Adding `LCMMessageType` and `channel()` to the class.

Resolves #3553.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3572)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri since I broke it originally.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/automotive/car_simulation.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-KSN6XF9-5u2Gzuo2QlI:-KSN6XFALi1eGkLOZ6T_:bkvk5yk) ([raw file](https://github.com/robotlocomotion/drake/blob/e90ac4a2cfdc3c6515f1c2fbb71c9b300a4ef5c1/drake/automotive/car_simulation.h#L22)):*
> ```objc
> namespace automotive {
> 
> /// Compatibility typedef for System 1 code.
> ```

BTW No longer a "typedef".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-:-KSN6kJsIzw28oHbRqx8:bbqq4ke)*

**Comment by liangfok** [comment]
Thanks. +@ggould-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-:-KSN7ZopHgTUYfJwzogf:b-7897i5)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/car_simulation.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-KSN6XF9-5u2Gzuo2QlI:-KSNIH1rJNys0kqm999V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e90ac4a2cfdc3c6515f1c2fbb71c9b300a4ef5c1/drake/automotive/car_simulation.h#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW No longer a "typedef".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572)*

**Comment by liangfok** [comment]
The Windows32 CI failure was a networking flake.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4981/ and is thus ready for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-:-KSamCy0shs86rAkAlzo:b-3wv4ql)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3572#-:-KSaoWrh7OPCPhahExWK:bnfp4nl)*

**Pull request merged**
