### PR TITLE
Changed "mpich2" to be "mpich" for Ubuntu since the "2" is vestigial.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2608)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review
+@david-german-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKoW-7GdG_N-IXZhMkj:1840062824)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKobiw5m9vN6BREpI7z:1417088721)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKoc4hcpo0Hl2PQQost:1417088721)*

**Comment by amcastro-tri** [comment]
Why do we need to install mpich? I dont see any MPI calls in drake. Shouldn't we just remove this dependency?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKoqzU1k1vJyNvSVSOX:-1113221916)*

**Comment by rpoyner-tri** [comment]
It could be a transitive dependency of some other libraries that drake depends on... that requires a bit more study.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKozGrzx3oyojVvsvXZ:-1132626800)*

**Comment by rpoyner-tri** [comment]
The first explicit mention of mpich I could find was at this commit -- I still don't know why it is needed:

commit ada9ac29a5629d9664a621b701a5d2b023bf1392
Author: Jamie Snape <jamie.snape@kitware.com>
Date:   Thu Mar 17 15:26:30 2016 -0400

    Update minimum CMake version and consolidate install_prereqs scripts

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKp2KmurrgMRENjjxaK:-1708120642)*

**Comment by amcastro-tri** [comment]
@rpoyner-tri: I see, thank you. I just wonder why apt-get does not install this dependency (and maybe others) automatically. :lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2608#-:-KKpHet96xZa9ke615mo:865350863)*

**Pull request merged**
