### PR TITLE
[install] Add shortcuts for meldis and model_visualizer

### LINKED ISSUE #18751: Add $bindir shortcut for meldis
The user question [here](https://stackoverflow.com/questions/75303201/drake-meshcat-visualizer-example-on-ubuntu-22-04-with-apt-installation) is a good one: after an `apt install drake-dev`, how should the user launch meldis?  (Especially on Jammy.)

Previously they could easily do `/opt/drake/bin/drake-visualizer`, but now they need to do `python3 -c pydrake.visualization.meldis` after setting their `$PYTHONPATH`.

We could probably add a little bash shim like we had for drake-visualizer to launch meldis.

We could be cute and on Jammy call it `/opt/drake/bin/drake-visualizer` ala Folgers crystals, but that is probably too confusing.  Probably that script should print instructions for the new script name though.

We could name it `/opt/drake/bin/meldis` I suppose?  Or a few people suggested `/opt/drake/bin/dvis` as an easier spelling to type out.

Discussed in slack [here](https://app.slack.com/client/T0JNB2DS4/C43KX47A9/thread/C43KX47A9-1675201370.357959).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18751.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18764)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18764#-:-NOC4n_n8jEkuxhJGrEd:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.  (Rico is on-call today.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one passing thought on an error message which will likely never be encountered.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18764#-:-NOGBBdS8fUYX4uAJAmN:b-fjeffu)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/visualization/run_installed_meldis.py.in` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18764#-NOGAYIxA0nJRWXkhZFF:-NOGAYIxA0nJRWXkhZFG:b-3qkplm) ([raw file](https://github.com/RobotLocomotion/drake/blob/710cc66b1f6ffc507107f3efb6cd110ab9a3a9be/bindings/pydrake/visualization/run_installed_meldis.py.in#L14)):*
> ```
>     # Ensure that we can import pydrake, accommodating symlinks.
>     prefix_dir = dirname(dirname(realpath(__file__)))
>     assert isdir(join(prefix_dir, "bin")), f"Bad location: {prefix_dir}"
> ```

BTW Is it possible for `prefix_dir` to exist, but not `prefix_dir/bin`? In that case, the assertion message may be misleading.

(Same on the other.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18764)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/visualization/run_installed_meldis.py.in` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18764#-NOGAYIxA0nJRWXkhZFF:-NOGebD8-1XJ764VsYqi:b-arlhez) ([raw file](https://github.com/RobotLocomotion/drake/blob/710cc66b1f6ffc507107f3efb6cd110ab9a3a9be/bindings/pydrake/visualization/run_installed_meldis.py.in#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is it possible for `prefix_dir` to exist, but not `prefix_dir/bin`? In that case, the assertion message may be misleading.

(Same on the other.)
</blockquote></details>

OK I'm not too worried.

If `bin` isn't there then in fact `prefix_dir` is definitely wrong.  The error doesn't say "no such prefix_dir", it says "bad location" which is technically true.  Something would need to be seriously wrong for this to trip, anyway.

**Pull request merged**
