### PR TITLE
[tutorials] Add hydro quick-start to a tutorial

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for review (maybe both?). FYI @zachfang 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-Nyg6FcP20f1X_OOF36q:b-5ftquv)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+none

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-Nyv7m3gBb6-TT_Qpdk3:b-8mxwci)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-Nyv9uEw52vHsFWT14je:b-om6exd)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 482 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-NzTUNCs3ezM78HjoTCC:-NzTtksR89I8yuagsTcX:b-55qvrl) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dbd92297301d48fdb1769ea9316a4e3af444910/tutorials/authoring_multibody_simulation.ipynb#L482)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> This method applies reasonable defaults everywhere ...

This particular example is not reasonable.  The proximity model of the cylinder is a triangular solid:



Also, having the box fall down off the table is not OK.  We carefully tuned this demo to stay on the table, so this new simulation needs to do likewise.
</blockquote></details>

Let's see if https://github.com/RobotLocomotion/drake/pull/21511 can pass CI and land first.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`tutorials/authoring_multibody_simulation.ipynb` line 482 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-NzTUNCs3ezM78HjoTCC:-NzVI4GLD8Zmpzt8waRW:b-radeek) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dbd92297301d48fdb1769ea9316a4e3af444910/tutorials/authoring_multibody_simulation.ipynb#L482)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Let's see if https://github.com/RobotLocomotion/drake/pull/21511 can pass CI and land first.
</blockquote></details>

As of `r2`, the simulation sets rez hint explicitly; that could perhaps go.
___
*[`tutorials/authoring_multibody_simulation.ipynb` line 496 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-NzVHuemDeA5J0zsRqMO:-NzVHuemDeA5J0zsRqMP:boz7yjs) ([raw file](https://github.com/RobotLocomotion/drake/blob/31d7b0b0642709f4c6d2b78699b082990b0741be/tutorials/authoring_multibody_simulation.ipynb#L496)):*
> ```
>     "    config = SceneGraphConfig()\n",
>     "    config.default_proximity_properties.compliance_type = \"compliant\"\n",
>     "    config.default_proximity_properties.resolution_hint = 0.02\n",
> ```

explicit resolution hint could maybe get deleted once #21511 lands.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

I wish our default visualization had the alpha sliders so that we could see the hydro contact patches better, but oh well.  That will come later.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-NzVKOON0FP-r6KaCgyE:bl7b7gv)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-NzYFQ1ZAVg2jxWG-P0J:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21481#-:-NzZI2pYAgwTA_XWQIr1:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
