### PR TITLE
Faster lcp solve

### PR DESCRIPTION
**Pull request by edrumwri**
Replaces the householder QR factorization, which is necessary for AutoDiff, with a LU factorization when templatized on double. Yields a 40% speedup on the Schunk lift test on timestepping!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7607)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0L3LZ28VeBMRgoUJxX:brbsdox)*

**Comment by amcastro-tri** [comment]
:lgtm:. Just a small question regarding the re-use of the factorization whenever possible.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/moby_lcp_solver.cc, line 304 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0Lc92xBLBfgfm7ivSH:-L0Lc92xBLBfgfm7ivSI:b-l4gf36) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc5a4fe32fd8525d175c010112e9302f3c254ec/solvers/moby_lcp_solver.cc#L304)):*
> ```cpp
>     // example. The algorithm would ideally terminate at this point, but
>     // compilation with AutoDiff currently generates template errors.
>     zz = LinearSolve(Msub, zz.eval());
> ```

I didn't look through the math carefully but, is there a chance here within these loops to reuse the factorization? Maybe you'd like to declare within this scope a `PartialPivLU` object?

---

*[solvers/moby_lcp_solver.cc, line 786 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0Lew9S75mpUBFesOw7:-L0Lew9S75mpUBFesOw8:b-bd8tn9) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc5a4fe32fd8525d175c010112e9302f3c254ec/solvers/moby_lcp_solver.cc#L786)):*
> ```cpp
> 
>     // See comments above on the possibility of this solve failing.
>     dl = LinearSolve(Bl, dl.eval());
> ```

Again, just a quick scan. Is `B1` changing withing this scope? maybe the factorization can be reused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0Lf2YFSU9Apyh_mxjw:b-esn6ny)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/moby_lcp_solver.cc, line 304 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0Lc92xBLBfgfm7ivSH:-L0LfWWFpA27yl9_8ysJ:b9jbzzx) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc5a4fe32fd8525d175c010112e9302f3c254ec/solvers/moby_lcp_solver.cc#L304)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I didn't look through the math carefully but, is there a chance here within these loops to reuse the factorization? Maybe you'd like to declare within this scope a `PartialPivLU` object?
</blockquote></details>

PartialPivLu is not AutoDiff'able, which is why I'm using a generic "solve" method. Also, there is no way to reuse the factorization, since the indices that are used to form Msub change on every iteration.

---

*[solvers/moby_lcp_solver.cc, line 786 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0Lew9S75mpUBFesOw7:-L0LfHwWySkjBdkHqFin:bvifcw4) ([raw file](https://github.com/robotlocomotion/drake/blob/dbc5a4fe32fd8525d175c010112e9302f3c254ec/solvers/moby_lcp_solver.cc#L786)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Again, just a quick scan. Is `B1` changing withing this scope? maybe the factorization can be reused?
</blockquote></details>

Yes, Bl changes within this scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607)*

**Comment by hongkai-dai** [comment]
How is the accuracy of `PartialPivLu` in our example? According to Eigen, it is less accurate the `ColPivHouseHolderQr`

https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0LsLUUaHZMLMUF5103:b-5np6gh)*

**Comment by edrumwri** [comment]
@sherm1 for platform review please

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0Pvg95-KJx6pvXl6va:by34l6j)*

**Comment by edrumwri** [comment]
@hongkai-dai: I really don't know what the Eigen docs mean by "accuracy" here. There's no reason that partial pivoting LU should be worse than any QR factorization for solving systems of linear equations, barring near singular matrices, and we actually don't want better performance on those, because it indicates that the basis has become degenerate and the solver should fail. Accuracy of the tests was not impacted by this change (I examined this by racheting down epsilon as tightly as possible).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0Q2YnAte7lXt2HtM5S:b-gu1tnd)*

**Comment by amcastro-tri** [comment]
> barring near singular matrices, and we actually don't want better performance on those, because it indicates that the basis has become degenerate and the solver should fail.

This triggered two questions:
1. why is it that you had QR in the first place if you were expecting these systems to be well conditioned (no barring near singular matrices).
2. I think we should check if the solver is successful and report accordingly in case it is not?

 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0QCBoGahZTQGJLgDOH:b-c1yee8)*

**Comment by edrumwri** [comment]
@amcastro-tri:

1. AutoDiff doesn't work with LU factorizations. QR allowed us to get the correct results, albeit slowly, for double scalar types.
2. It does.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0QGeO5UnRLW0b7yO6e:b3gp1g3)*

**Comment by sherm1** [comment]
+@sherm1 

Platform :lgtm: pending a few BTW comment fixes, ptal.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[solvers/moby_lcp_solver.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QhR3__QwKkpIas0uS:-L0QhR3__QwKkpIas0uT:bchehiy) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L38)):*
> ```cpp
> }
> 
> // Linear system solver, generic (and slower).
> ```

BTW should mention the motivation for this method and its specialization. As I understand it the LU would be sufficient for everything here but you had to use the QR for AutoDiffability.

---

*[solvers/moby_lcp_solver.cc, line 310 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QhttuXtqmHJJbvfLc:-L0QhttuXtqmHJJbvfLd:by8n9kh) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L310)):*
> ```cpp
>     zz *= -1;
> 
>     // Solve for nonbasic z. If the QR factorization reveals that the matrix
> ```

BTW this comment isn't right any more since there is not necessarily a QR. Also it isn't clear to me what's meant by "reveals a singularity" here since there doesn't appear to be any code checking for singularity.

---

*[solvers/moby_lcp_solver.cc, line 711 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QiX3X4vHO9MCaaNjF:-L0QiX3YFP4mFYQpYBKg:bq2z7q4) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L711)):*
> ```cpp
>     // See http://www.optimization-online.org/DB_FILE/2011/03/2948.pdf, for
>     // example. The algorithm would ideally terminate at this point, but
>     // compilation of householderQr().rank() with AutoDiff currently generates
> ```

BTW same comment here but this seems even further off since it specifically mentions householderQr() that isn't being called.

Consider how to avoid duplicating comments -- can you discuss this in one place and reference? Duplication leads to maintenance problems, with this small change being a tidy illustration of exactly that!

---

*[solvers/moby_lcp_solver.cc, line 797 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QiwC9FSnUmGA9HzEu:-L0QiwC9FSnUmGA9HzEv:b-biw1fn) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L797)):*
> ```cpp
>     dl = Be;
> 
>     // See comments above on the possibility of this solve failing.
> ```

BTW yay! No need to update this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-:-L0Qh8PRACfCzILui9w_:b-4dh7rl)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/moby_lcp_solver.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QhR3__QwKkpIas0uS:-L0eCNLnvFTHFWnB-7ye:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L38)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should mention the motivation for this method and its specialization. As I understand it the LU would be sufficient for everything here but you had to use the QR for AutoDiffability.
</blockquote></details>

Done.

---

*[solvers/moby_lcp_solver.cc, line 711 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0QiX3X4vHO9MCaaNjF:-L0eG0uv3a8XTWovwpoc:b-368f58) ([raw file](https://github.com/robotlocomotion/drake/blob/ec42338b8ec9cd0bebaef6710c23736780f92576/solvers/moby_lcp_solver.cc#L711)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW same comment here but this seems even further off since it specifically mentions householderQr() that isn't being called.

Consider how to avoid duplicating comments -- can you discuss this in one place and reference? Duplication leads to maintenance problems, with this small change being a tidy illustration of exactly that!
</blockquote></details>

Done. And, lesson learned!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/moby_lcp_solver.cc, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0eX068uP9rpUoAzvlr:-L0eX068uP9rpUoAzvls:b4op2c0) ([raw file](https://github.com/robotlocomotion/drake/blob/53c63b3f8ad0cbe3366e674af817bcf3e873b71e/solvers/moby_lcp_solver.cc#L60)):*
> ```cpp
> 
> // Linear system solver, specialized for double types. This method is faster
> // than the QR factorization necesary for AutoDiff support. It is assumed that
> ```

BTW necesary->necessary 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/moby_lcp_solver.cc, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7607#-L0eX068uP9rpUoAzvlr:-L0ez9NtdNzxrXhp9wc5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53c63b3f8ad0cbe3366e674af817bcf3e873b71e/solvers/moby_lcp_solver.cc#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW necesary->necessary 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7607)*

**Pull request merged**
