### PR TITLE
[workspace] Upgrade nanoflann_internal to latest release v1.5.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #19715

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19775)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Per #17914, delegating to +@RussTedrake to please push the code fixes for the build error(s) to this PR.  Alternatively, you can open a new PR with all of the changes to replace this PR (in case pushing to this remote is too awkward).

**Review by RussTedrake — COMMENTED** [review]
Done.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19775#-:-N_Qc6UR85ls0IMmX3PG:b-896fix)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19775#-:-N_QcJZ88vmmqktfWTN2:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19775#-:-N_V48-r0dIv9XPzmHIW:b-vtj4vo)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Pull request merged**
