### PR TITLE
Adds support for <include> tags in the mujoco parser.

### LINKED ISSUE #20683: Parsing include tags in xml doesn't seem to work
### What happened?

When parsing Mujoco xmls, [`<include>`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#include) tags are apparently not parsed.
Maybe as a solutiuon, could you temporarily build the full xml and then parse this temporary xml?

### Version

1.23.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

Unknown / Other

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20683.

+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nittery, a node deleting bug, and questions

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-:-Ns9N9VMBtEYb_32xjhn:b-k80ilx)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/benchmarks/acrobot/acrobot.xml` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9MMmD3MYGEc2oysii:-Ns9MMmD3MYGEc2oysij:b-1j5f02) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/benchmarks/acrobot/acrobot.xml#L17)):*
> ```XML
>     <motor name="elbow" joint="elbow"/>
>   </actuator>
> </mujoco>
> ```

nit Old habits die hard. I'm in favor of text input files having a terminating newline character. here and a few below.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1392 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9GNgh25b-BIAMhfIc:-Ns9GNgh25b-BIAMhfId:b-siaany) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1392)):*
> ```cpp
>     DRAKE_DEMAND(node != nullptr);
> 
>     // Process the current node if it's an <include> tag
> ```

Complete sentence comments should end with a period (.) , here and several below.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1423 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9Cei91bxBgsw3QCxu:-Ns9Cei91bxBgsw3QCxv:b-ngjrbq) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1423)):*
> ```cpp
> 
>       // Insert the children of the root element of the included file
>       tinyxml2::XMLDocument* xml_doc = node->GetDocument();
> ```

nit other uses of these types in the same scope don't use the `tinyxml2::` prefix -- surely we can drop it here as well? Threre are a few more occurrences below as well.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1444 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9EfNtD4h1w8Rwdzlp:-Ns9EfNu0B181NiKG5UG:bmytgix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1444)):*
> ```cpp
>       ProcessIncludeTags(child, parent_mjcf_path);
>       tinyxml2::XMLElement* to_delete =
>           (std::string(node->Value()) == "include") ? child : nullptr;
> ```

This should be `child`, maybe? It doesn't seem sound to delete `child` based on whether `node` (always the first sibling) is an include tag.

FWIW, `ProcessIncludeTags` knew the answer, and dropped it on the floor. Maybe the function should have a return value, something like `@returns bool node_argument_was_include_tag` ?



_Code quote:_
```cpp
node
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1449 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9KHq88pY6XKU2M3ur:-Ns9KHq88pY6XKU2M3us:bwkqpqv) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1449)):*
> ```cpp
>       if (to_delete) {
>         // Remove the include node from the main document
>         node->GetDocument()->DeleteNode(to_delete);
> ```

minor This line is unreached by unit tests. Probably a consequence of the defect noted above.

FWIW there's argument to be made in favor of not bothering to delete the include nodes, since the rest of the parse will ignore them. Thoughts?

I'm slightly in favor of deleting them, but I could be swayed.

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-:-NsBT4Ty6DtHK9l2nQk0:bcav8r0)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[`multibody/benchmarks/acrobot/acrobot.xml` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9MMmD3MYGEc2oysii:-NsBRUMM8AV3chFTlhqL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/benchmarks/acrobot/acrobot.xml#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Old habits die hard. I'm in favor of text input files having a terminating newline character. here and a few below.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1392 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9GNgh25b-BIAMhfIc:-NsBRV6f41PR2UOmxOQ7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1392)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Complete sentence comments should end with a period (.) , here and several below.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1423 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9Cei91bxBgsw3QCxu:-NsBR_t0BFTMh9HNm5pG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1423)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit other uses of these types in the same scope don't use the `tinyxml2::` prefix -- surely we can drop it here as well? Threre are a few more occurrences below as well.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1444 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9EfNtD4h1w8Rwdzlp:-NsBRsEE3VZhEFnP6XSX:b-dxlhjq) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1444)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This should be `child`, maybe? It doesn't seem sound to delete `child` based on whether `node` (always the first sibling) is an include tag.

FWIW, `ProcessIncludeTags` knew the answer, and dropped it on the floor. Maybe the function should have a return value, something like `@returns bool node_argument_was_include_tag` ?
</blockquote></details>

Done.  Good catch.

Re: your fwiw. I started with the return value, but decided that this was cleaner (and not enough overhead to merit the clutter).  
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1449 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9KHq88pY6XKU2M3ur:-NsBSKWVEHyQn_eqJ3CL:b9040wu) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1449)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor This line is unreached by unit tests. Probably a consequence of the defect noted above.

FWIW there's argument to be made in favor of not bothering to delete the include nodes, since the rest of the parse will ignore them. Thoughts?

I'm slightly in favor of deleting them, but I could be swayed.
</blockquote></details>

Done. Clearly my intention was to delete them.  I think that's cleaner.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:;  the comments below are picky details.  Mostly matters of opinion; feel free to dismiss any you think are not worth the trouble.

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-:-NsEJYJzATTw6Y2UcIbQ:b46vgl7)* status: 6 unresolved discussions

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1392 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9GNgh25b-BIAMhfIc:-NsE9P8Q6Jf94gF9jyxn:b-v724qq) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1392)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Still a few that you missed, I see lll. 1422, 1430, 1438, 1448
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsECuQN1ESZ0EaphxqO:-NsECuQN1ESZ0EaphxqP:b74wnqm) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1388)):*
> ```cpp
>   }
> 
>   void ProcessIncludeTags(XMLElement* node,
> ```

minor:  Because this function alters its argument, it really needs either a brief comment or a clearer verb than "Process"
Consider, e.g. `ExpandIncludeTags`, or a comment "Updates `node` by recursively replacing any `<include>` elements under it with the children of the named file's root element." or both.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsEFag7DTUFgpTVt2f6:-NsEFag7DTUFgpTVt2f7:b-8oc6wm) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1388)):*
> ```cpp
>   }
> 
>   void ProcessIncludeTags(XMLElement* node,
> ```

nit:  I found it slightly confusing that `node` is `XMLElement` rather than `XMLNode`.  Since you are deliberately avoiding touching non-element nodes, consider calling this `element` rather than `node`.



_Code quote:_
```cpp
node
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE62Pi1jBoxVlA5QcF:-NsE62Pi1jBoxVlA5QcG:b-gyqytk) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1403)):*
> ```cpp
>       location is relative to the directory of the main MJCF file. If the file
>       is not in the same directory, it should be prefixed with a relative
>       path.*/
> ```

nit:  inconsistent comment formatting.  Everywhere else you use `//` comments.
(https://drake.mit.edu/styleguide/cppguide.html#Comment_Style "Use either the `//` or `/* */` syntax, as long as you are consistent.")



_Code quote:_
```cpp
      /* From the MJCF docs: The name of the XML file to be included. The file
      location is relative to the directory of the main MJCF file. If the file
      is not in the same directory, it should be prefixed with a relative
      path.*/
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE7QRR-p8_Eo8Teg37:-NsE7QRR-p8_Eo8Teg38:boqpt9j) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1403)):*
> ```cpp
>       location is relative to the directory of the main MJCF file. If the file
>       is not in the same directory, it should be prefixed with a relative
>       path.*/
> ```

minor:  It is not clear to me what this is documenting.  "The file location" seems to refer to the `file` variable, which is also the thing that needs to be prefixed with a relative path?
Consider rewriting this to actually name which variables are subject to which of these restrictions, and then testing (e.g. demanding `!std::filesystem::absolute()` of whichever ones are supposed to be relative).



_Code quote:_
```cpp
      /* From the MJCF docs: The name of the XML file to be included. The file
      location is relative to the directory of the main MJCF file. If the file
      is not in the same directory, it should be prefixed with a relative
      path.*/
```
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1405 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE88-JDggJmdvSCSXx:-NsE88-K2fnbCZVCBtHq:brng2y4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1405)):*
> ```cpp
>       path.*/
>       std::filesystem::path filename = parent_mjcf_path / file;
>       filename = std::filesystem::weakly_canonical(filename);
> ```

minor:  Why `weakly_canonical` when you are about to open the file for reading (i.e. it must exist)?  Is the assumption that it's safe to ignore the error code from the "weakly" version (ie we don't fear encoding mismatch between XML and HFS)?  Or do we expect better file-not-found error behaviour from tinyxml?

Alternatively, if we don't care about the path existing, why not `absolute`, which will leave symlinks unexpanded and so probably give the user a more recognizable path in any error messages?



_Code quote:_
```cpp
weakly_canonical
```
___
*[`multibody/parsing/test/mujoco_parser_test/nested.xml` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsEBPQiE-6UZHcxVdCD:-NsEBPQiE-6UZHcxVdCE:bgv33un) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/test/mujoco_parser_test/nested.xml#L3)):*
> ```XML
> <mujoco model="nested">
>   <include file="pendulum.xml"/>
> </mujoco>
> ```

BTW  These example files are mixed as to whether they have a trailing newline or not.  We generally prefer trailing newline, although this does not strictly apply to XML.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21087)* status: 1 unresolved discussion

___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1392 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-Ns9GNgh25b-BIAMhfIc:-NsGkzSc27laikzezNx5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e8501e8c7dcde7049279ecf1725bb21beda7b7e/multibody/parsing/detail_mujoco_parser.cc#L1392)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW Still a few that you missed, I see lll. 1422, 1430, 1438, 1448
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsECuQN1ESZ0EaphxqO:-NsGkg9j4FpId65Zd5ui:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1388)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Because this function alters its argument, it really needs either a brief comment or a clearer verb than "Process"
Consider, e.g. `ExpandIncludeTags`, or a comment "Updates `node` by recursively replacing any `<include>` elements under it with the children of the named file's root element." or both.
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1388 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsEFag7DTUFgpTVt2f6:-NsGkmmmC6qfrfnDmGJv:b-sivzmv) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1388)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  I found it slightly confusing that `node` is `XMLElement` rather than `XMLNode`.  Since you are deliberately avoiding touching non-element nodes, consider calling this `element` rather than `node`.
</blockquote></details>

We're using XMLElement* node everywhere else in the file.  So I'll decline this one.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE62Pi1jBoxVlA5QcF:-NsGlN5e1Sr7CkmVuTwS:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1403)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  inconsistent comment formatting.  Everywhere else you use `//` comments.
(https://drake.mit.edu/styleguide/cppguide.html#Comment_Style "Use either the `//` or `/* */` syntax, as long as you are consistent.")
</blockquote></details>

Done.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1403 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE7QRR-p8_Eo8Teg37:-NsGlL8xDMlipSJ1D2fd:bzdr5qu) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1403)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It is not clear to me what this is documenting.  "The file location" seems to refer to the `file` variable, which is also the thing that needs to be prefixed with a relative path?
Consider rewriting this to actually name which variables are subject to which of these restrictions, and then testing (e.g. demanding `!std::filesystem::absolute()` of whichever ones are supposed to be relative).
</blockquote></details>

This is a quote from the MJCF docs.  I've added quotes to make it more clear.
___
*[`multibody/parsing/detail_mujoco_parser.cc` line 1405 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsE88-JDggJmdvSCSXx:-NsGm1Lj7QNnbz6TZCUh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/detail_mujoco_parser.cc#L1405)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Why `weakly_canonical` when you are about to open the file for reading (i.e. it must exist)?  Is the assumption that it's safe to ignore the error code from the "weakly" version (ie we don't fear encoding mismatch between XML and HFS)?  Or do we expect better file-not-found error behaviour from tinyxml?

Alternatively, if we don't care about the path existing, why not `absolute`, which will leave symlinks unexpanded and so probably give the user a more recognizable path in any error messages?
</blockquote></details>

Done.
___
*[`multibody/parsing/test/mujoco_parser_test/nested.xml` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21087#-NsEBPQiE-6UZHcxVdCD:-NsGm84t2CePBqs2kn9B:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c97a43fafcc4bd07bcd0ee2f498e862e84d3f62a/multibody/parsing/test/mujoco_parser_test/nested.xml#L3)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW  These example files are mixed as to whether they have a trailing newline or not.  We generally prefer trailing newline, although this does not strictly apply to XML.
</blockquote></details>

Done.

**Pull request merged**
