### PR TITLE
Document the behavior of Environment::insert() when the key already exists

### LINKED ISSUE #16284: Document symbolic::Environment.insert when the key already exists
When we call `env.insert(var, value)` and `var` already exists in `env`, this function doesn't change `var`'s value (same as in std::unordered_map). It would be good to document this behavior as one might not know that symbolic::Environment emulates std::unordered_map.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #16284 

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16288)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 
+@sherm1 for both reviews
:lgtm: x 2 with one comment

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16288#-:-Mrx6RoM4MG77yN1Al3N:bj7uh1l)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[common/symbolic_environment.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16288#-Mrx5rab5WmCKh3FSzJh:-Mrx5racAaYD1GXvXJxX:b-t6788g) ([raw file](https://github.com/robotlocomotion/drake/blob/20b9134fc319aa681833ac27022a94226de2d35f/common/symbolic_environment.h#L108)):*
> ```objc
> 
>   /** Inserts a pair (@p key, @p elem) if this environment doesn't contain @p
>    * key. Similar to std::unordered_map::insert() function, if the key already
> ```

BTW this is a property of a "map", regardless of whether it is ordered or unordered. Consider just saying "std::map::insert()" to remove the emphasis on the internal implementation, which is not relevant here.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Sherm for the holiday review, much appreciated!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16288#-:-MrxG_0dAsIYxYCxRxnZ:b-g4nwex)* status: missing label for release notes (waiting on @sherm1)

___
*[common/symbolic_environment.h, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16288#-Mrx5rab5WmCKh3FSzJh:-MrxGPkf0pg85NMeMOkE:b-mk6oio) ([raw file](https://github.com/robotlocomotion/drake/blob/20b9134fc319aa681833ac27022a94226de2d35f/common/symbolic_environment.h#L108)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is a property of a "map", regardless of whether it is ordered or unordered. Consider just saying "std::map::insert()" to remove the emphasis on the internal implementation, which is not relevant here.
</blockquote></details>

Done, good call.

I think `std::map::insert()` might emphasize an ordered map, so I reworded a bit.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16288)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16288#-:-MrxRAvkCKvgWzi8Vpzq:b-safpmt)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
