### PR TITLE
Added LcmSubscriberSystem.WaitForMessageTimeout

### PR DESCRIPTION
**Pull request by mposa**
`LcmSubscriberSystem.WaitForMessageTimeout` is a version of ``LcmSubscriberSystem.WaitForMessage` with a specified timeout. I'm very open to the API and precise implementation here, but this functionality would be useful to avoid indefinite blocking on a bad call to `WaitForMessage`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10871)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
I haven't yet combed through the PR, but the leaky scope of `LcmSubscriberSystem` is making me sad... However, if this provides immediate value, I'll give it a go.

Will read more and provide more thoughtful comments.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I wouldn't worry about the API growth too much.  I am going to remove all mutex / condition variables / threads from LcmSubscriberSystem and trash LcmDrivenLoop in the next month or so (with a replacement that has the same functionality but with much better separation of concerns).

**Comment by EricCousineau-TRI** [comment]
Please let me know if you'd like me to take a whack at applying my own suggestions.

**Comment by EricCousineau-TRI** [comment]
I'm OK with the introduction of timeout; but I'd prefer it be simpler / more amenable to Python.

**Comment by EricCousineau-TRI** [comment]
Going to squash merge.

**Pull request merged**
