### PR TITLE
Cleanup mex code to be closer to style guide

### PR DESCRIPTION
**Pull request by jamiesnape**
Still some way to go, but this at least keeps the automated style checkers happy.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6653)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-open-source  please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@EricCousineau-TRI for platform review, please.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/mex_util.cc, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-KpuzdfmOLe0gDD2hvxN:-KpuzdfmOLe0gDD2hvxO:bj4ahyi) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_util.cc#L3)):*
> ```cpp
> #include <limits>
> 
> #include "drake/matlab/util/mex_util.h"
> ```

This should be first, per the "related header" rule?

---

*[drake/matlab/util/mex_util.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-KpuzImiKT9tLlDAJ_0Q:-KpuzImjexzHNh9eXeCp:ba6qajq) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_util.h#L10)):*
> ```objc
> #include <vector>
> 
> #include <mex.h>
> ```

FYI For some reason, I thought that `<mex.h>` had to precede all other headers ever, based on some tutorial I read in the mists of time.  But writing that out now, that's sounds dumb -- how could that ever work?  Anyway, I guess if CI likes it, I like it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-:-Kpv-2kt3qckmcmhmEn9:b-nbay8p)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv11lJtNHfz3LuL4_Y:b1pyhrj) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
> ```cpp
> 
> #include <cstdio>
> ```

nit Extra line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-:-Kpv1Huk8S2cjY1iJl8U:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv2urhXIZEgVbWwZI2:b-d7w7ne) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Extra line?
</blockquote></details>

According to the style guide C system headers and C++ system headers are different categories and each category should be separated with a blank line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653)*

**Comment by jwnimmer-tri** [comment]
*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv3ZeSvn9Hg1E9JWZX:b71tot2) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

According to the style guide C system headers and C++ system headers are different categories and each category should be separated with a blank line.
</blockquote></details>

Correct, but `<stdio.h>` is the C header; `<cstdio>` is the C++ header:
https://github.com/RobotLocomotion/drake/blob/0092bdde07c74a18795d1f386a9b0eb6e988c50b/.clang-format#L34-L35

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653)*

**Comment by jamiesnape** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv3TeAF6BivhVcgbDN:b-ulnsxi) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Correct, but `<stdio.h>` is the C header; `<cstdio>` is the C++ header:
https://github.com/RobotLocomotion/drake/blob/0092bdde07c74a18795d1f386a9b0eb6e988c50b/.clang-format#L34-L35
</blockquote></details>

True, I therefore wonder whether `<dlfcn.h>` should be above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 15 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv5qU8obG3Ds4QL_x9:b-1l6bxi) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

True, I therefore wonder whether `<dlfcn.h>` should be above.
</blockquote></details>

OK I think we've been putting extensions (dlfcn) as-if they were third party includes, and only putting standardized C99 / C++14 includes up top.  In any case, `bazel-bin/drake/tools/clang-format-includes myfile.cc` should probably be your one true god, so I would be fine admitting whatever it says.  (I believe it will leave this file unchanged as it looks now.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/util/mex_wrapper.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6653#-Kpv11lH9hgRDHu6cPvr:-Kpv72gPN9A-FmqOPOdD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c17364bb568a62c02059179d22f0f4527b1f55d2/drake/matlab/util/mex_wrapper.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I think we've been putting extensions (dlfcn) as-if they were third party includes, and only putting standardized C99 / C++14 includes up top.  In any case, `bazel-bin/drake/tools/clang-format-includes myfile.cc` should probably be your one true god, so I would be fine admitting whatever it says.  (I believe it will leave this file unchanged as it looks now.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6653)*

**Pull request merged**
