### PR TITLE
Explicitly permit doxygen markup in non-Doxgen comments

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
As discussed in #4539 -- @sherm1 for first review; does this capture the point well?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4739)

### CODE REVIEW

**Comment by sherm1** [comment]
Yes, :lgtm: Jeremy -- thanks. One BTW suggestion.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-KaAr1h9S0NWKbr6R4Jn:-KaAr1h9S0NWKbr6R4Jo:bdda5zo) ([raw file](https://github.com/robotlocomotion/drake/blob/768a40d78b6cfc21b59ebefdccde2cdaed0b9e5e/drake/doc/code_style_guide.rst#L68)):*
> ```reStructuredText
>     block format.  However, note that markup such as ``@return`` may still be
>     used for non-Doxygen (``//`` or ``/*``) comment blocks when it improves
>     readability of the source code for developers.
> ```

BTW, add "... developers, even though it will never be processed by Doxygen."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaArLc6MGtDATwha4ji:b-fjnola)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-KaAr1h9S0NWKbr6R4Jn:-KaB0LiabUO2KdSxqWi6:b-ftow0a) ([raw file](https://github.com/robotlocomotion/drake/blob/768a40d78b6cfc21b59ebefdccde2cdaed0b9e5e/drake/doc/code_style_guide.rst#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, add "... developers, even though it will never be processed by Doxygen."
</blockquote></details>

I like it.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri +@sammy-tri +@ggould-tri for review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaClQUPNlqos2yb3O3g:b6lzyw5)*

**Comment by RussTedrake** [comment]
:lgtm:

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-KaCoywGusjeBS1R8exm:-KaCoywHHmvCJi_s5JK7:b-ay75jz) ([raw file](https://github.com/robotlocomotion/drake/blob/99cf2acf3b41b169c51c1f222920ddfeb3d4b84f/drake/doc/code_style_guide.rst#L68)):*
> ```reStructuredText
>     block format.  However, note that markup such as ``@return`` may still be
>     used for non-Doxygen (``//`` or ``/*``) comment blocks when it improves
>     readability of the source code for developers, even though it will never be
> ```

BTW, consider replacing "readability of the source code for developers" with "code readability"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaCpAVpAQLRQD8-OyZc:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:  I hadn't even realized this was controversial.

Someone (possibly me) should look in on the pre-commit checklist document to see if it needs revision from all of the style guide changes made since it was written.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaD2AXm8_hJYnz_4AuI:bbsq1d2)*

**Comment by jwnimmer-tri** [comment]
Yes.  This is more clarifying a sometimes-consensus, rather than a strong overturn.  It was coming up as a defect sometimes, and now we have a doc that it's okay.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaD3Lkg1UbL52ffJwbL:bys4da2)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaD47ma2iwt43GlGgyr:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4739#-:-KaDe4moWd7SwMX1B9ro:bnfp4nl)*

**Pull request merged**
