### PR TITLE
Update lcm codegen to be cpplint compliant

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Update the LCM codegen to be cpplint compliant -- either outputting better code, or adding suppressions for items that are "intentional" (like using references for output parameters, requiring an implicit Eigen constructor, etc.).

We are going to be making many new LCM messages soonish, so let's get them correct from day one.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2091)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri PTAL for feature code review.

(Obviously, looking at the python changes and then only one of the three generated-file diffs should be good enough.  No need to eyebleed on all three vectors.)

**Comment by jwnimmer-tri** [comment]
The jenkins msvc errors appear to be false positives relating to snopt.

**Comment by rpoyner-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/SimpleCar/simple_car_gen.sh, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFK4K1rZc8jU6-QEAoV:-KFK4K1rZc8jU6-QEAoW:272841250) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2c9fe297f2715dba19798ebd558348699777fd/drake/examples/SimpleCar/simple_car_gen.sh#L27)):*
I am sympathetic with the idea of ensuring formatting here, but do we really want to specify and maintain the exact version of  the tool in this script?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by rpoyner-tri** [comment]
i'm mostly good with it, just one grump about clang-format...

**Comment by jwnimmer-tri** [comment]
*[drake/examples/SimpleCar/simple_car_gen.sh, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFK4K1rZc8jU6-QEAoV:-KFK57EhRBUrO7HbVgn5:-1370272866) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2c9fe297f2715dba19798ebd558348699777fd/drake/examples/SimpleCar/simple_car_gen.sh#L27)):*
Once developers.rst has proper advice for how to run clang-format, I would support changing this to match.  But for now, I figured that for a script that is run only occasionally by hand, this could be satisfactory.

Would it be better if a reduced the repetition and used a $CLANG_FORMAT, that the user could override?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by rpoyner-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/SimpleCar/simple_car_gen.sh, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFK4K1rZc8jU6-QEAoV:-KFK6L2W3hneCHrdi9Vb:-1254586887) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2c9fe297f2715dba19798ebd558348699777fd/drake/examples/SimpleCar/simple_car_gen.sh#L27)):*
Yes, I believe you can feed it all files at once (even with -i) and having an overrideable app name would satisfy me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by rpoyner-tri** [comment]
probably out of scope for this PR, but consider adding some row/column size assertions in the constructor and operator=() that take MatrixBase<Derived> .

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri PTAL at the fix.

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/SimpleCar/simple_car_gen.sh, line 27 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFK4K1rZc8jU6-QEAoV:-KFKS7eqlbsldaMPWvHT:705537920) ([raw file](https://github.com/robotlocomotion/drake/blob/2d2c9fe297f2715dba19798ebd558348699777fd/drake/examples/SimpleCar/simple_car_gen.sh#L27)):*
looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-:-KFKSDrqcY2lisSAqQc-:1417088721)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri Looks like this is going to pass CI (modulo false positives), so over to you to merge.

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/SimpleCar/lcm_vector_gen.py, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFKyze7MOtK4Y6ck4CS:-KFKyze7MOtK4Y6ck4CT:381814908) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/lcm_vector_gen.py#L17)):*
Do we use these as implicit conversions somewhere?  Sadness, if so.

---

*[drake/examples/SimpleCar/lcm_vector_gen.py, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFKzIrBs9pAfUH8sC7r:-KFKzIrBs9pAfUH8sC7s:102939188) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/lcm_vector_gen.py#L21)):*
What does // BR do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/SimpleCar/lcm_vector_gen.py, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFKzIrBs9pAfUH8sC7r:-KFL1wmWLc51jSQCMTSy:1104747503) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/lcm_vector_gen.py#L21)):*
Any `//` comment prevents clang-format from moving the following line up onto the current line (in this case, so that each item in the initializer list gets its own line for clarity).  The "BR" is just an abbreviation to tell the reader that "this is for linebreak purporses" ala `<BR/>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/SimpleCar/lcm_vector_gen.py, line 17 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFKyze7MOtK4Y6ck4CS:-KFL1dfdoiK8lzSMNFjd:1582021130) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/lcm_vector_gen.py#L17)):*
Yes.  All (most?) Vector concepts must be implicitly convertible from Eigen for some reason that I haven't bothered to dig out yet.  Hopefully System2 will solve that, so I was just planning on suppressing this for all of the System1 Vector concepts for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/SimpleCar/driving_command.h, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFL6sOG5VCxLIT--SQ9:-KFL6sOH9RRabVEueWKj:1476499098) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/driving_command.h#L1)):*
Where did this come from?

Sorry for the extra iteration - I meant to send this comment last time but it fell through the cracks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/SimpleCar/driving_command.h, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-KFL6sOG5VCxLIT--SQ9:-KFL7KcHwxdYDFSwENh_:376292077) ([raw file](https://github.com/robotlocomotion/drake/blob/bd1d05a57d9571e3207c5f3ba43d26a854c11e54/drake/examples/SimpleCar/driving_command.h#L1)):*
No problem.  It's derived from the line in the LICENSE.TXT statement.  I figured when #1805 happens, it would replace this if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2091#-:-KFL8cmxkhPa4N8-voko:1417088721)*

**Comment by david-german-tri** [comment]
Merging despite unrelated Bertini errors on drake005.

**Pull request merged**
