### PR TITLE
retrieve dual solution for positive semidefinite constraint in Mosek.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106)

### CODE REVIEW

**Review by aykut-tri — COMMENTED** [review]
I left some nits and just want to make sure we've considered the following:
- Does it make sense to address [this TODO](https://github.com/RobotLocomotion/drake/blob/4b59d0dd1fa9964c1880994d7990d9af341177e8/solvers/test/mosek_solver_test.cc#L571) within this PR as well?
- Is there any python interface implications?

Otherwise, :lgtm:

+@ericcousineau-tri for platform review please, thanks!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106#-:-N1JaLz64sYlfY2aiWnd:b-pvc4ts)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`solvers/mathematical_program_result.h` line 316 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JfTvq2UnQuOveRReU:-N1JfTvq2UnQuOveRReV:bve52dt) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L316)):*
> ```objc
>    * the dual cone. Here the dual variable DOESN'T have the interpretation of
>    * "shadow price", but should satisfy the KKT condition, while the dual
>    * variable stays inside the dual cone.
> ```

BTW, consider adding a new line here
___
*[`solvers/mathematical_program_result.h` line 317 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jg-Oa-N0bFBu56BNm:-N1Jg-Oa-N0bFBu56BNn:b5oz5zl) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L317)):*
> ```objc
>    * "shadow price", but should satisfy the KKT condition, while the dual
>    * variable stays inside the dual cone.
>    * When K is a PSD cone, the returned dual solution is the lower triangle of
> ```

BTW, consider noting it's because the dual is symmetric



_Code quote:_
```objc
the lower triangle
```
___
*[`solvers/mathematical_program_result.h` line 320 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JelYI2WunKYxDjo0o:-N1JelYI2WunKYxDjo0p:br4jwt2) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L320)):*
> ```objc
>    * the dual PSD matrix. Namely for the primal problem
>    *
>    *    min trace(CX)
> ```

nit, C*X?



_Code quote:_
```objc
CX
```
___
*[`solvers/mathematical_program_result.h` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JezFF5bJk9chLJGnh:-N1JezFF5bJk9chLJGni:b-7vyj07) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L322)):*
> ```objc
>    *    min trace(CX)
>    *    s.t A(X) = b
>    *        X is psd
> ```

nit, consider using PSD as above



_Code quote:_
```objc
psd
```
___
*[`solvers/mathematical_program_result.h` line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jf9PRCSB9CXScX1GC:-N1Jf9PRCSB9CXScX1GD:bb5cd35) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L328)):*
> ```objc
>    *    max b'*y
>    *    s.t A'(y) - C = Z
>    *        Z is psd.
> ```

nit, same as above



_Code quote:_
```objc
psd
```
___
*[`solvers/mosek_solver.cc` line 1547 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jk5GUAZeCQWoxJLCm:-N1Jk5GUAZeCQWoxJLCn:b7nmvup) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1547)):*
> ```cpp
>     std::vector<MSKrealt> barsj(
>         psd_constraint.evaluator()->matrix_rows() *
>         (psd_constraint.evaluator()->matrix_rows() + 1) / 2);
> ```

BTW, just curious does it make sense to round/cast this into `int`?



_Code quote:_
```cpp
        psd_constraint.evaluator()->matrix_rows() *
        (psd_constraint.evaluator()->matrix_rows() + 1) / 2);
```
___
*[`solvers/mosek_solver.cc` line 1552 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JmYBD6fOloOgCAuZ1:-N1JmYBD6fOloOgCAuZ2:bcf78zz) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1552)):*
> ```cpp
>       return rescode;
>     }
>     // Copy barsj to dual_lower. I don't use barsj directly since MSKrealt might
> ```

nit, consider using "we" instead



_Code quote:_
```cpp
I
```

**Review by hongkai-dai — COMMENTED** [review]
Good call

> Is there any python interface implications?

The `ToSymmetricMatrixFromLowerTriangularColumns` is not included in pybind. I will add it in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106#-:-N1JzVPDDzI2hYQS3Bq5:bqojcqf)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[`solvers/mathematical_program_result.h` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JezFF5bJk9chLJGnh:-N1Jst4Y-tnkAIogZftv:bx3qpul) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L322)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

nit, consider using PSD as above
</blockquote></details>

I am following the notation in https://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15859-f11/www/notes/lecture12.pdf, they use lower-case `psd`. They use upper-case `PSD` in `PSD-ness`. 

I changed the other upper case PSD to the lower case psd in this PR.
___
*[`solvers/mathematical_program_result.h` line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jf9PRCSB9CXScX1GC:-N1JtW47BZW27sKhwwMx:b-89a4l7) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L328)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

nit, same as above
</blockquote></details>

Ditto
___
*[`solvers/mosek_solver.cc` line 1547 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jk5GUAZeCQWoxJLCm:-N1K-ims5HepzD6bsOUr:b-rpx19h) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1547)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, just curious does it make sense to round/cast this into `int`?
</blockquote></details>

`matrix_rows()` already returns an `int`. I don't think we need to round/cast to int again?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[`solvers/mathematical_program_result.h` line 322 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1JezFF5bJk9chLJGnh:-N1K0_ug3dcVFL1BEOSY:bjz8nrd) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mathematical_program_result.h#L322)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am following the notation in https://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15859-f11/www/notes/lecture12.pdf, they use lower-case `psd`. They use upper-case `PSD` in `PSD-ness`. 

I changed the other upper case PSD to the lower case psd in this PR.
</blockquote></details>

And thanks for catching this. I probably need another PR to change the upper-case PSD to the lower case in Drake.

**Comment by aykut-tri** [comment]
*[`solvers/mosek_solver.cc` line 1547 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jk5GUAZeCQWoxJLCm:-N1KA8AEE9QoeZF6rTSi:b-w4gd4l) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1547)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`matrix_rows()` already returns an `int`. I don't think we need to round/cast to int again?
</blockquote></details>

but we have `/2` afterwards?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @aykut-tri and @EricCousineau-TRI)

___
*[`solvers/mosek_solver.cc` line 1547 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jk5GUAZeCQWoxJLCm:-N1KAMLOEuozx5g_9fAl:bk9v99j) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1547)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

but we have `/2` afterwards?
</blockquote></details>

It is `n * (n+1) / 2`, so guaranteed to be an integer after divided by 2.

**Comment by aykut-tri** [comment]
*[`solvers/mosek_solver.cc` line 1547 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1Jk5GUAZeCQWoxJLCm:-N1KAVng--Lpw-2FWiTO:b-vggqj5) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa8a8a76b9e1bf42d608976ca3be5c4df4a73b4/solvers/mosek_solver.cc#L1547)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is `n * (n+1) / 2`, so guaranteed to be an integer after divided by 2.
</blockquote></details>

I noticed that but I was (mistakenly) thinking the divide operator could map to float (but I just realized that's not the case if your operands are already ints). Sorry my bad, resolving.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, with some small nits!

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17106#-:-N1KIe0Z-_tyagWMB7M0:b-c1ce56)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver.cc` line 1538 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1KHr2K-nTjV31SYLXR:-N1KHr2K-nTjV31SYLXS:b-7qyuf0) ([raw file](https://github.com/robotlocomotion/drake/blob/2eba7e2880eae28cbc133c160f5161d511b60720/solvers/mosek_solver.cc#L1538)):*
> ```cpp
>       throw std::runtime_error(
>           "SetPositiveSemidefiniteConstraintDualSolution: this positive "
>           "semidefinite constraint has not"
> ```

nit grammar "has not *been* registered"
___
*[`solvers/mosek_solver.cc` line 1540 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17106#-N1KHwKgDV8lA_oKhbDq:-N1KHwKgDV8lA_oKhbDr:b5fdf97) ([raw file](https://github.com/robotlocomotion/drake/blob/2eba7e2880eae28cbc133c160f5161d511b60720/solvers/mosek_solver.cc#L1540)):*
> ```cpp
>           "semidefinite constraint has not"
>           "registered in Mosek as a matrix variable. This should not happen, "
>           "please report a bug on drake github.");
> ```

nit Consider rewording more explicitly:
```
Please post an issue on Drake: https://github.com/RobotLocomotion/drake/issues/new
```

**Pull request merged**
