### PR TITLE
Introduces some computational methods in MBP

### PR DESCRIPTION
**Pull request by amcastro-tri**
In this PR, a number of methods that we'll need for IK.
 - `MakeKukaIiwaPlant()`, factory to create an MBP model of a Kuka Iiwa arm,
 - `CalcAllBodyPosesInWorld()` and `CalcAllBodySpatialVelocitiesInWorld()`
 - `CalcPointsPositions()` to compute the position of a set of points from their position in a given frame.
 - `CalcPointsGeometricJacobianExpressedInWorld()` geometric Jacobian for the method above.
 - unit testing in `multibody_plant_test.cc` using the Kuka model.
 - Tests on scalar conversion with `AutoDiffXd` to compute Jacobians by differentiation as a means of verifying the results.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7947)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@siyuanfeng-tri for feature review please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-:-L4OOHrtwwSQP8ZepTNT:bakb6i6)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OPQmZthGQaQSGKQ3V:-L4OPQmZthGQaQSGKQ3W:b-s10rqs) (no related file):*
Per Slack discussion. Change notation to use `Jv` and `Jq ` for geometric and analytic Jacobians respectively so that subscript indicates the variable with respect to which the differentiation is being made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947)*

**Comment by siyuanfeng-tri** [comment]
great start, just confirming, the jacobian here only has the position part? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-:-L4ORjs9rWKXcRbUxa_H:b-k2xn0c)*

**Comment by amcastro-tri** [comment]
Correct, it is the geometric Jacobian so that the translational velocity `v_WQi(q, v)` of a point `Qi` is `v_WQi = Jv_WQi(q) * v`. I will push the analytical Jacobian and orientation Jacobians in different PR's (since otherwise it goes beyond our lines limit). 

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-:-L4OWrqhQlLLEYb5tsqA:b-fv4wzi)*

**Comment by siyuanfeng-tri** [comment]
sounds good, i'd prefer angular part first. many thanks.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-:-L4OXYlu48JSJIuIpDbZ:bad71dx)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OPQmZthGQaQSGKQ3V:-L4OfY3yImwg4pI25iPj:bscakl7) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Per Slack discussion. Change notation to use `Jv` and `Jq ` for geometric and analytic Jacobians respectively so that subscript indicates the variable with respect to which the differentiation is being made.
</blockquote></details>

highlevel: i was thinking more about asking for a mbt factory class, as the use case i had in mind was more on the tree + position and velocity cache level rather than plant. since the particular differential ik thing essentially only needs to get Jv and setup a mathematical program, i'd rather keep it simple without introducing system dependencies. 

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OWcL21DFI7uidZHqd:-L4OWcL21DFI7uidZHqe:b-fvf5a3) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc#L70)):*
> ```cpp
>   // Newtonian reference frame (linkN) is the world body.
>   auto plant = make_unique<MultibodyPlant<T>>();
>   const Body<T>& linkN = plant->get_world_body();
> ```

BTW can you move this alias closer to where it's used?

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OVrhGf9d6j7S03AFJ:-L4OVrhGf9d6j7S03AFK:byfaif9) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc#L114)):*
> ```cpp
>   AddRevoluteJointFromSpaceXYZAnglesAndXYZ(
>       "iiwa_joint_1",
>       linkN, Vector3d(0, 0, 0), Vector3d(0, 0, 0.1575),
> ```

can you hard code these in the header as well? so all the magic numbers are in the same place. 

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4Ob3cWTFEqYGy1Lc86:-L4Ob3cWTFEqYGy1Lc87:b-xr6zmb) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h#L34)):*
> ```objc
>   /// world upward z-unit vector (which is correct -- gravity is downward).
>   std::unique_ptr<drake::multibody::multibody_plant::MultibodyPlant<T>>
>   Build() const;
> ```

BTW doesn't have to be this pr, but can you add a TODO here to take in a pose input, which is the offset between the base link and the world? that would be super useful. 

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OTiU_cxTODXPZ9T4s:-L4OTiU_cxTODXPZ9T4t:bnc068u) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h#L39)):*
> ```objc
>   // Helper method to add revolute joint from Body A to Body B.
>   // @param[in] A     Joint's parent  body (frame Ab will be welded to A).
>   // @param[in] q123A SpaceXYZ angles describing the rotation matrix relating
> ```

BTW, why q123? what's SpaceXYZ angles? euler? 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OY0liwjNpp-j4SYnD:-L4OY0liwjNpp-j4SYnE:bbo1kao) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L157)):*
> ```cpp
>   }
>   // TODO(amcastro-tri): Eval these from the context.
>   PositionKinematicsCache<T> pc(model_->get_topology());
> ```

BTW if i were you, i would put these as mutable member variables to avoid keeping making there temp obj. 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OZZ3ghAYdUtOf5r0s:-L4OZZ3ghAYdUtOf5r0t:bb6ykz6) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L185)):*
> ```cpp
>     const systems::Context<T>& context,
>     const Frame<T>& frame_B, const Eigen::Ref<const MatrixX<T>>& p_BQi_set,
>     EigenPtr<MatrixX<T>> p_WQi_set, EigenPtr<MatrixX<T>> Jg_WQi) const {
> ```

Jv? 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OZqx4CDw1tSTp9Xb3:-L4OZqx4CDw1tSTp9Xb4:b-edr0cn) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.h#L410)):*
> ```objc
>   /// @{
> 
>   /// Computes the world pose `X_WB(q)` of each body B in the model as a
> ```

BTW curious why separate these two? instead of just calckinematics? or just rename the velocity one to calc kinematics, and also return a vector of poses? 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 486 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OaIl4E9u3DmqlPhvP:-L4OaIl4E9u3DmqlPhvQ:bb6ykz6) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.h#L486)):*
> ```objc
>   /// this method computes the geometric Jacobian `Jg_WQi` defined by:
>   /// <pre>
>   ///   v_WQi(q, v) = Jg_WQi(q)⋅v
> ```

Jv? 

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4ObVfadjmpamK97qB9:-L4ObVfadjmpamK97qBA:bi45snx) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L206)):*
> ```cpp
> 
>     // Keep pointers to the modeling elements.
>     linkG_ = &plant_->GetBodyByName("iiwa_link_7");
> ```

BTW i wonder you call it linkg. 

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 366 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OeZw-3MRb-ypnZy6F:-L4OeZw-3MRb-ypnZy6G:b-soetm) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L366)):*
> ```cpp
> 
>   // Verify that CalcPointsPositions() computes the same value of p_NG.
>   Vector3<double> p2_NG = CalcEndEffectorPosition(*plant_, *context_);
> ```

BTW I suspect these two code path all boils down to MBT::CalcPointsPositions, anyway. not sure if this comparison is meaningful. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OPQmZthGQaQSGKQ3V:-L4h4ifwNjLDALM63CuN:bts8b82) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

highlevel: i was thinking more about asking for a mbt factory class, as the use case i had in mind was more on the tree + position and velocity cache level rather than plant. since the particular differential ik thing essentially only needs to get Jv and setup a mathematical program, i'd rather keep it simple without introducing system dependencies. 
</blockquote></details>

As discussed in Slack. We provide `MultibodyPlant` as our main entry point for now since MBP can provide caching through the system infrastructure. We'll also provide enough sugar to enhance user experience so that you don't have to worry about input/outputs, declarations, geometry registration, etc. 

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc, line 114 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OVrhGf9d6j7S03AFJ:-L4gwxXuJaaWN2IDtTkA:bcvjgzp) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.cc#L114)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you hard code these in the header as well? so all the magic numbers are in the same place. 
</blockquote></details>

Good idea. Done.

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4Ob3cWTFEqYGy1Lc86:-L4gxCwq0pn4zuZmvaje:b-k7yn24) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h#L34)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW doesn't have to be this pr, but can you add a TODO here to take in a pose input, which is the offset between the base link and the world? that would be super useful. 
</blockquote></details>

BTW No problem. But I was really hoping parsing would land before that is needed.

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OTiU_cxTODXPZ9T4s:-L4gxMJF5xgIVuqTH3Dx:becd08y) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h#L39)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, why q123? what's SpaceXYZ angles? euler? 
</blockquote></details>

BTW Euler angles can take the shape of a number of different combinations depending on what order you decide to perform your rotations (12 distinct combinations) and, on top of that, you can decide whether to take those rotations with body fixed axes (intrinsic) or space fixed axes (extrinsic), for a total of 24 different Euler angles conventions!!. SpaceXYZ is short for "rotate in the order X-Y-Z with space fixed axes". It turns out, this is equivalent to the BodyZYX convention (rotate in the reverse order but now using body fixed axes). That is the unambiguous way to describe it.
Of course, URDF people are used to what in URDF you call rpy (I say URDF specifically because on top of that there could even be different sign conventions). So, it turns out URDF rpy is equivalent to SpaceXYZ (roll about X, pitch about Y, yaw about Z, with space fixed axes!!). I have to say however it is more intuitive to think in BodyZTX though (I imagine that's what you do as well).
Anyway, I added a little clarification comment. 

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OY0liwjNpp-j4SYnD:-L4h-e6cmbcaxwXIMoaO:b-qtu3bc) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L157)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW if i were you, i would put these as mutable member variables to avoid keeping making there temp obj. 
</blockquote></details>

BTW I know..... I think more important is how it reads. I think writing `const PositionKinematics<T>& pc = this->EvalPositionKinematics(context);` is what makes sense (Eval of course could be using mutables, recomputing or using our new cache system)

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OZZ3ghAYdUtOf5r0s:-L4h1aRBRvjDkiK8-2RT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L185)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Jv? 
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 410 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OZqx4CDw1tSTp9Xb3:-L4h1kXnKvSKrUnsn6__:b7cpt) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.h#L410)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW curious why separate these two? instead of just calckinematics? or just rename the velocity one to calc kinematics, and also return a vector of poses? 
</blockquote></details>

BTW what if you are only doing stuff with q's, not v's? for instance inverse kinematics? you wouldn't want to call a method to compute velocities in that case if you don't need to. 
BTW I can add that API if it proves useful. What signature exactly would you want? `CalcAllBodyPosesAndVelocitiesInWorld(context, vector<Isometry3>* X_WB, vector<SpatialVelocity>* V_WB)`?

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 486 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OaIl4E9u3DmqlPhvP:-L4h2Rj4r2O23gMNT5Ck:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/multibody_plant.h#L486)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Jv? 
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4ObVfadjmpamK97qB9:-L4h32SWUaxz4ROFfkAF:b4wttcv) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L206)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i wonder you call it linkg. 
</blockquote></details>

BTW sry, borrowing from Paul's notation where he uses a letter from A to G for each link frame. I renamed it to something hopefully more friendly.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 366 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OeZw-3MRb-ypnZy6F:-L4h4LoHOgalqNf7QbjY:bd0vi9b) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L366)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW I suspect these two code path all boils down to MBT::CalcPointsPositions, anyway. not sure if this comparison is meaningful. 
</blockquote></details>

BTW true, but the unit test also ensures the API is stable as well. Maybe then the value comparison is useless but I just thought I'd perform it since I had the values handy anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7947#-L4OTiU_cxTODXPZ9T4s:-L4iXpgo4zjc7VSW00zM:bqgl46i) ([raw file](https://github.com/robotlocomotion/drake/blob/4734399d5139b5bc2ee0fdea9e2b2794c6d8f175/multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_plant.h#L39)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

ah ok. i would have called it worldxyz.
is spacexyz a thing you guys made up or a common thing? this is the first time i have heard about it. 
</blockquote></details>

We should ask @mitiguy where "Space-fixed" came from. It's in Thomas Kane's books like 40 years ago. I suspect it may have come from Aerospace originally. But [here](https://physics.stackexchange.com/questions/33851/euler-angle-space-fixed-vs-body-fixed-axes) it is in physics.stackexchange with some citations. There is even a guy named Siyuan there using the term :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7947)*

**Comment by amcastro-tri** [comment]
I think I might close this one. So far I think the only new thing here after #8009 are the scalar conversion tests on the MBP. Stay tuned.

**Pull request closed without merging**
