### PR TITLE
Add a subset of VTK 7.1.1+ to the Bazel build

### PR DESCRIPTION
**Pull request by jamiesnape**
`ImageTest.MeshBoxRenderingTest` is failing under VTK 7.1.1, so is temporarily disabled for VTK >= 6.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6152)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Of course, we need to install `vtk@8.0` on Mac...

**Comment by jamiesnape** [comment]
We need an upgrade to the Trusty image before this can pass on CI.

**Comment by BetsyMcPhail** [comment]
The Trusty image has been updated.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@kunimatsu-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 7 of 13 files at r1.
Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 300 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPg2Hx2_m6PHX3TcWM:-KlPg2Hx2_m6PHX3TcWN:b-hlit8i) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L300)):*
> ```Python
> 
> drake_cc_binary(
>     name = "rgbd_camera_binary",
> ```

Using a name of `rgbd_camera_test_binary` would be slightly more clear; this is not useful in general as a camera demo, it's just a private testing detail, so "test" in the name is probably better.

---

*[drake/systems/sensors/BUILD, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPgclRoIirKG6jnRHZ:-KlPgclRoIirKG6jnRH_:b-q7w7mk) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L332)):*
> ```Python
>     args = ["$(location :rgbd_camera_binary)"],
>     tags = ["exclusive"],
> )
> ```

IIRC there was a prior discussion that we should just use `DISPLAY` (because starting xvfb repeatedly was not going to be reliable) and then require that the test environment provide it somehow.  We already admit it into our `tools/bazel.rc` in this PR.

Has this been discussed and this PR's proposal chosen, or should we resurface those old discussions, or ...?

---

*[drake/systems/sensors/rgbd_camera.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlP_gTxwxQvWGdClXsG:-KlP_gTyVVv0rwXfAs-0:bmighxi) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/rgbd_camera.cc#L42)):*
> ```cpp
> 
> #if VTK_MAJOR_VERSION >= 6
> VTK_MODULE_INIT(vtkRenderingOpenGL2)
> ```

Google Styleguide disprefers non-pod constructors and destructors: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

Ideally, the `CONSTRUCT` should happen deterministically, e.g., the first time `RgbdCamera` constructor is called; and the `DESTRUCT` should only be called if we can do so deterministically (which doesn't seem worth it).

What about just doing the GL initialization the first time a RgbdCamera is constructed?  (Untested.)

```c++
namespace {
struct EnsureVtkIsInitialized {
  EnsureVtkIsInitialized() {
    VTK_AUTOINIT_CONSTRUCT(vtkRenderingOpenGL2)
  }
};
}  // namespace

class RgbdCamera::Impl : private EnsureVtkIsInitialized {
  ...
```

This would AUTOINIT for every camera -- but presumably its idempotent anyway given the conventional use?  If its expensive, the EnsureVtkIsInitialized ctor could instead have a `static const drake::never_destroyed<ReallyInitialize>` file-scoped static to call the `AUTOINIT_CONSTRUCT` just once per this file.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPeo6D2_x4mdkBiYqI:-KlPeo6D2_x4mdkBiYqJ:b-ts0y0l) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/test/rgbd_camera_test.cc#L390)):*
> ```cpp
>                                  const sensors::ImageDepth32F& depth_image,
>                                  int expected_horizon) {
>     drake::unused(depth_image);
> ```

The dead argument seems like a bug.  At least could we have a TODO indicating so?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlPl8fgEW-P0wYDbKnb:by96gdd)*

**Comment by jamiesnape** [comment]
Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPgclRoIirKG6jnRHZ:-KlPna4lDDTWPalevDvY:ben0m3f) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L332)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

IIRC there was a prior discussion that we should just use `DISPLAY` (because starting xvfb repeatedly was not going to be reliable) and then require that the test environment provide it somehow.  We already admit it into our `tools/bazel.rc` in this PR.

Has this been discussed and this PR's proposal chosen, or should we resurface those old discussions, or ...?
</blockquote></details>

Starting up and reusing one xvfb instance would probably be better, but the way CI is currently structured, the cmake build, the director build, and this would all need to use the same method, so this would be blocked for a while.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/sensors/BUILD, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPgclRoIirKG6jnRHZ:-KlPs-iLmN3WRFRUNMd2:b-vz8tb1) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L332)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Starting up and reusing one xvfb instance would probably be better, but the way CI is currently structured, the cmake build, the director build, and this would all need to use the same method, so this would be blocked for a while.
</blockquote></details>

Aha, I see my confusion now.  This test is not run in CI right now even under CMake; I hadn't yet read `test/CMakeLists.txt` changes to notice that it's also run under `xvfb` there.

I am concerned that this huge PR simultaneously adding xfvb-run tests at the same time is going to get finicky in CI for buildcop and our PRs.

What do you think about leaving the test (without an xvfb wrapper) as manual-only mode in both CMake and Bazel in this PR -- with a goal of just getting it _building_ in CI and then the reviewers manually test it locally?  Then subsequently we can enable the test in CI and deal with the fallout of that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by kunimatsu-tri** [comment]
Thanks @jamiesnape for making this PR.

Good to know how to run rgbd_camera_test with and widhout xvfb-run.

I've left two comments. PTAL.

---

Reviewed 5 of 13 files at r1.
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPgclRoIirKG6jnRHZ:-KlQCUorB3k2kcJdp5Bl:bqjflih) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L332)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aha, I see my confusion now.  This test is not run in CI right now even under CMake; I hadn't yet read `test/CMakeLists.txt` changes to notice that it's also run under `xvfb` there.

I am concerned that this huge PR simultaneously adding xfvb-run tests at the same time is going to get finicky in CI for buildcop and our PRs.

What do you think about leaving the test (without an xvfb wrapper) as manual-only mode in both CMake and Bazel in this PR -- with a goal of just getting it _building_ in CI and then the reviewers manually test it locally?  Then subsequently we can enable the test in CI and deal with the fallout of that later.
</blockquote></details>


+1 for separating this PR to two PRs, bazel build and xvfb-run.

---

*[tools/vtk.bzl, line 246 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPsR6ptGxij_wPeKUZ:-KlPsR6qraqQ8I2DMPsS:b-rj7q5b) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/tools/vtk.bzl#L246)):*
> ```Python
>     )
> 
>     file_content += _vtk_cc_library(repository_ctx.os.name, "vtkCommonMisc",
> ```

Just to make sure, the arguments of `_vtk_cc_library` for`vtkCommonMisc` here is the same as `vtkCommonMath`'s.  Is this correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlQLSz-y3WYNP3e3Fvp:b-d9otpg)*

**Comment by jamiesnape** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 300 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPg2Hx2_m6PHX3TcWM:-KlQOClaEgfLtqn5p9Bg:b-f8ijsg) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L300)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Using a name of `rgbd_camera_test_binary` would be slightly more clear; this is not useful in general as a camera demo, it's just a private testing detail, so "test" in the name is probably better.
</blockquote></details>

Just renamed to `rgbd_camera_test` since I do not need to resolve a conflict anymore.

---

*[drake/systems/sensors/BUILD, line 332 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPgclRoIirKG6jnRHZ:-KlQO97i-uVsfOWDu-B2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/BUILD#L332)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

+1 for separating this PR to two PRs, bazel build and xvfb-run.
</blockquote></details>

Done.

---

*[tools/vtk.bzl, line 246 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPsR6ptGxij_wPeKUZ:-KlQO2d2Rs2NGddbkewQ:bi12gxt) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/tools/vtk.bzl#L246)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Just to make sure, the arguments of `_vtk_cc_library` for`vtkCommonMisc` here is the same as `vtkCommonMath`'s.  Is this correct?
</blockquote></details>

Good catch. It is not correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jamiesnape** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/test/rgbd_camera_test.cc, line 390 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlPeo6D2_x4mdkBiYqI:-KlQOzGwZE3Kqxxaipfx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/test/rgbd_camera_test.cc#L390)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The dead argument seems like a bug.  At least could we have a TODO indicating so?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---

Reviewed 5 of 13 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlQQoHnbPzsud7LL_jf:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
We should probably get an OSX developer (@soonho?) to test this on OSX per the`mac.rst` edits.

---

Reviewed 1 of 13 files at r1, 5 of 8 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 286 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQQF2z8Ouz6m5dM6sp:-KlQQF2z8Ouz6m5dM6sq:b-bc15lh) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/systems/sensors/BUILD#L286)):*
> ```Python
> 
> # TODO(jamiesnape): Convert this to a drake_cc_googletest when Xvfb is
> # available on CI.
> ```

FYI This is fine, but `tags = ["manual"]` would let you still declare it as a `drake_cc_googletest` if you prefer.

---

*[drake/systems/sensors/BUILD, line 315 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQSmJb6OWLqC5bNjfI:-KlQSmJcPHpQTzWs9Mvn:b7gqh8i) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/systems/sensors/BUILD#L315)):*
> ```Python
> drake_cc_googletest(
>     name = "vtk_util_test",
>     local = 1,
> ```

Could you add a comment why `local = 1` is required for this test?

---

*[tools/vtk.bzl, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQTnLoQ0z2Z4RxPj6v:-KlQTnLpu0BFnAqVTxQl:bptnf6b) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L81)):*
> ```Python
>     if repository_ctx.os.name == "mac os x":
>         # TODO(jamiesnape): Use VTK_MAJOR_MINOR_VERSION instead of hard-coding.
>         repository_ctx.symlink("/usr/local/opt/vtk@8.0/include", "include")
> ```

The MAJOR_MINOR_VERSION says 7.1 but this says @8.0.  Is that right?

---

*[tools/vtk.bzl, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQVNbkC8TET2Yvwv-F:-KlQVNbkC8TET2Yvwv-G:b-myo0xf) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L112)):*
> ```Python
> 
>     # Note that we only create library targets for enough of VTK to support
>     # those used directly or indirectly by Drake.
> ```

BTW Given the work to reach this point, do you have any tips to help future maintainers update this list of libraries and their headers and dependencies?  Like instructions for trying a new VTK version, or finding out the correct answer for what "deps" or "hdrs" should be (do I somehow look in a vtkFoo.cmake file?)  Should we consider a python tool that parses vtkFoo.cmake and emits BUILD files?  (If there's useful advice, please add comments somewhere in here.)

---

*[tools/vtk.bzl, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQV1ZS5c2r0awzvmkf:-KlQV1ZTF3ucVwrL1L8T:b-h586uc) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L464)):*
> ```Python
> 
>     file_content += _vtk_cc_library(repository_ctx.os.name, "vtkmetaio",
>         deps = ["@zlib//:lib"],
> ```

FYI I think `@zlib` works and would be more in line with Drake current habits?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlQTLqYIYer8TXpmAIm:bmm4g1x)*

**Comment by soonho-tri** [comment]
+@soonho-tri , I will test it tomorrow morning.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlQjwD-aa0nT2MqFVpA:b-jv0m8v)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 286 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQQF2z8Ouz6m5dM6sp:-KlTbLNzIa3wwXHLfy2z:bclfppg) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/systems/sensors/BUILD#L286)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is fine, but `tags = ["manual"]` would let you still declare it as a `drake_cc_googletest` if you prefer.
</blockquote></details>

Although my understanding is that `manual` tests do not build and we want to build it by default.

---

*[drake/systems/sensors/BUILD, line 315 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQSmJb6OWLqC5bNjfI:-KlTbtt1WmZ7pP5IRddc:bmmcxfg) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/systems/sensors/BUILD#L315)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Could you add a comment why `local = 1` is required for this test?
</blockquote></details>

It is not anymore. Will remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 286 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQQF2z8Ouz6m5dM6sp:-KlTdf1ZFk9521cXV4O_:b-7y4f3s) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/systems/sensors/BUILD#L286)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I just did a quick spike: adding `tags = ["manual"],` and then putting a syntax error in the test gave a compile error when it tried to build it.

(Still no defect, just FYI.)
</blockquote></details>

I think I will go back to reading the Bazel source code instead of the documentation...

---

*[tools/vtk.bzl, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQTnLoQ0z2Z4RxPj6v:-KlTdFmICU0LMm4-xNp3:b-awatso) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The MAJOR_MINOR_VERSION says 7.1 but this says @8.0.  Is that right?
</blockquote></details>

The 8.0 release has not been cut yet, so they have not updated the version number.

---

*[tools/vtk.bzl, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQV1ZS5c2r0awzvmkf:-KlTdTpTtGKaCxxszF07:b-cwxc8k) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L464)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think `@zlib` works and would be more in line with Drake current habits?
</blockquote></details>

`@zlib` should be equivalent to to `@zlib//:zlib` rather than `@zlib//:lib`, but I am starting to not believe documentation anymore.

Aside: Personally, I think it would be an improvement if the externals found by pkg-config created `@package//:package`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jwnimmer-tri** [comment]
*[tools/vtk.bzl, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQV1ZS5c2r0awzvmkf:-KlThF4pebhzi_CpIZE4:b-oi0qv4) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L464)):*
> @zlib should be equivalent to to @zlib//:zlib ...

Agree.  (That was my expectation as well.)  It turns out I was wrong when I thought that `@zlib//:zlib` already existed.

> I think it would be an improvement if the externals found by pkg-config created @package//:package.

Oops.  I thought that the `pkg_config_package` already did that, which is why I suggested this change.  My mistake.

If you wanted to change `pkg_config_package` to do that, I'd support it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/vtk.bzl, line 464 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQV1ZS5c2r0awzvmkf:-KlTiF8ER9Edohbcpn2p:b-p6hm5c) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L464)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> @zlib should be equivalent to to @zlib//:zlib ...

Agree.  (That was my expectation as well.)  It turns out I was wrong when I thought that `@zlib//:zlib` already existed.

> I think it would be an improvement if the externals found by pkg-config created @package//:package.

Oops.  I thought that the `pkg_config_package` already did that, which is why I suggested this change.  My mistake.

If you wanted to change `pkg_config_package` to do that, I'd support it.
</blockquote></details>

I will open a PR to do so once this has merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/mac.rst, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlTwfKmL-5_zxBuv1pK:-KlTwfKmL-5_zxBuv1pL:bsrkuid) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/doc/mac.rst#L23)):*
> ```reStructuredText
>     brew install autoconf automake bazel boost clang-format cmake doxygen gcc \
>       glib graphviz gtk+ jpeg libpng libtool libyaml mpfr ninja numpy python \
>       qt qt@4 qwt-qt4 scipy tinyxml vtk5 vtk@8.0 wget
> ```

I just want to confirm if we need to install
 - both of `qt` and `qt@4`
 - both of `vtk5` and `vtk@8.0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/mac.rst, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlTwfKmL-5_zxBuv1pK:-KlTyY63N0uA1H_70_lQ:b-oyuut2) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/drake/doc/mac.rst#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I just want to confirm if we need to install
 - both of `qt` and `qt@4`
 - both of `vtk5` and `vtk@8.0`.

</blockquote></details>

Yes, until Director moves to VTK 8 we have to support VTK 5 by default on the CMake builds.

---

*[tools/vtk.bzl, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQTnLoQ0z2Z4RxPj6v:-KlTnuH9aCOdblY_G3ea:b-90y47t) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess I'm confused by why we are consuming VTK 7.1 (per the include path, and the PR description) but the path here contains `@8.0`?  Is that just some weird homebrew thing?  I guess I'm just looking for some comments so that other Drake developers could successfully update these files.  (On the other hand, in reality that's unlikely to be tractable anyway -- few know how to make OSX work in the first place -- so meh.  Do what you think is required for Kitware staff to be able to maintain this piece of the code.  If that's no change, fine by me.)
</blockquote></details>

We are consuming master between VTK 7.1.1 and VTK 8.0. It will need a one-off change once the release is cut.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by soonho-tri** [comment]
:lgtm: 
It works for me.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlU2RrOB3y3KZ_VRuVc:b2e2ykn)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jamiesnape** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlP_gTxwxQvWGdClXsG:-KlUXUmya4HQrGx5nOeD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/rgbd_camera.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Google Styleguide disprefers non-pod constructors and destructors: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

Ideally, the `CONSTRUCT` should happen deterministically, e.g., the first time `RgbdCamera` constructor is called; and the `DESTRUCT` should only be called if we can do so deterministically (which doesn't seem worth it).

What about just doing the GL initialization the first time a RgbdCamera is constructed?  (Untested.)

```c++
namespace {
struct EnsureVtkIsInitialized {
  EnsureVtkIsInitialized() {
    VTK_AUTOINIT_CONSTRUCT(vtkRenderingOpenGL2)
  }
};
}  // namespace

class RgbdCamera::Impl : private EnsureVtkIsInitialized {
  ...
```

This would AUTOINIT for every camera -- but presumably its idempotent anyway given the conventional use?  If its expensive, the EnsureVtkIsInitialized ctor could instead have a `static const drake::never_destroyed<ReallyInitialize>` file-scoped static to call the `AUTOINIT_CONSTRUCT` just once per this file.
</blockquote></details>

Done.

---

*[tools/vtk.bzl, line 112 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlQVNbkC8TET2Yvwv-F:-KlUXAOmwoISeUTvLxpk:b9wg031) ([raw file](https://github.com/robotlocomotion/drake/blob/19f486c9978175a1c4c7b5422dc9c0037f1c76c2/tools/vtk.bzl#L112)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Given the work to reach this point, do you have any tips to help future maintainers update this list of libraries and their headers and dependencies?  Like instructions for trying a new VTK version, or finding out the correct answer for what "deps" or "hdrs" should be (do I somehow look in a vtkFoo.cmake file?)  Should we consider a python tool that parses vtkFoo.cmake and emits BUILD files?  (If there's useful advice, please add comments somewhere in here.)
</blockquote></details>

Added a TODO. I have a partial script for determining which headers are required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-KlP_gTxwxQvWGdClXsG:-KlUYkXHZ_n3MTz62IZ6:b-83sjo4) ([raw file](https://github.com/robotlocomotion/drake/blob/033d6e26a427acbd3dd23ced131f801bbb2cc0a0/drake/systems/sensors/rgbd_camera.cc#L42)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6152#-:-KlUYrZ57jAyOX9XKy3e:bnfp4nl)*

**Pull request merged**
