### PR TITLE
Change Python shebangs to point to python3, etc.

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #11692 and #10606.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12146)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-high-sierra-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-mojave-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
No, "it is set to combine commits for review" and always has been.

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by jwnimmer-tri** [comment]
(FWIW, I'm OK calling Eric's and my review sufficient.)

**Pull request merged**
