### PR TITLE
Determine certain properties of linear dynamical systems

### LINKED ISSUE #19227: Determining More Linear System Properties (Beyond Controllability)
It's useful to check if a linear system (A,B) is controllable (with `drake::systems::IsControllable`) before attempting to construct certain controllers. There are other conditions one might also want to check

- Stabilizability. See [this lecture](https://solmaz.eng.uci.edu/Teaching/MAE270A/Lec/Lec15.pdf), slide 3 for a necessary and sufficient condition.
- Observability. One checks the rank of the [observability matrix](https://en.wikipedia.org/wiki/Observability#Observability_matrix). It is also [equivalent](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf) to the controllability of  (B',A').
- Detectability. Is is [equivalent](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf) to the stabilizibility of (B',A').

As examples of their usefulness, [this source](https://www.egr.msu.edu/classes/me851/mukherji/09-LQR.pdf). notes that stabilizability and detectability serve as necessary and sufficient conditions for the existence of a stabilizing LQR solution

Note that these each of these conditions can be checked with some relatively straightforward linear algebra. I'm not sure what the threshold for something to be included in Drake is, but this seems pretty similar to `IsControllable`. Feel free to close the issue if this is insignificant.

(Related to #19191)

### PR DESCRIPTION
**Pull request by hongkai-dai**
Including controllability, observability, stabilizability and detectability

Resolves #19227 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19289)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@cohnt for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-:-NU0UWFH3pP-RUO-O3a6:bhsqy6j)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

**Review by hongkai-dai — COMMENTED** [review]
Thanks @cohnt for the review. I re-wrote the PR to add `IsDetectable` and `IsStabilizable` to `LinearSystem` class, and removed the free functions I added in my previous commit. PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-:-NU3EiB77qP3umiBYvHN:b8jeq0y)* status: 3 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @cohnt)

___
*[`systems/analysis/linear_system_property.cc` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-NU288X5C1n_sYI4q_jj:-NU3EZYvDdMz4qT0fUBT:bcpw8ne) ([raw file](https://github.com/RobotLocomotion/drake/blob/d155345b4d7ea045438c7a8b33cf77b1ddf211a2/systems/analysis/linear_system_property.cc#L14)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I believe this is already implemented in `systems::primitives::linear_system`. Not sure what the best way to handle the redundancy is.
</blockquote></details>

Done. Good call, thanks a lot!
___
*[`systems/analysis/linear_system_property.cc` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-NU26m8M177qAP4CrY_S:-NU3EdQCDOfqgbTVYKv1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d155345b4d7ea045438c7a8b33cf77b1ddf211a2/systems/analysis/linear_system_property.cc#L33)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

According to [this reference](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf), the duality condition requires flipping the position of the matrices as well. I.e., (C, A) is observable if (A',C') is controllable.
</blockquote></details>

Done.
___
*[`systems/analysis/linear_system_property.cc` line 72 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-NU27VDV4ACuSwtKW2lm:-NU3EeacBy8ke3LmG4rj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d155345b4d7ea045438c7a8b33cf77b1ddf211a2/systems/analysis/linear_system_property.cc#L72)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Similar to before, according to [this reference](https://aswani.ieor.berkeley.edu/teaching/SP17/265/lecture_notes/ieor265_lec10.pdf), the duality condition requires flipping the position of the matrices as well. I.e., (C, A) is detectable if (A',C') is stabilizable.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
+@sammy-tri for platform review per rotation

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-:-NU3dv8yAEHRTNUpBxry:b-y97dh8)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19289#-:-NU3fyoq3BNHBz6PFpxy:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
