### PR TITLE
Set IPOPT nonlinear constraint sparsity.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #18292

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-:-Nz5vG1B5lHo_w7MhJQd:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-:-Nz8S3ud6snd06GpMEaA:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/ipopt_solver_internal.cc` line 639 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-Nz8QUSe0WxHk9-mbax6:-Nz8QUSe0WxHk9-mbax7:bwxnb3m) ([raw file](https://github.com/RobotLocomotion/drake/blob/410aec286b6f8c85b2e04159d9b3a207e35a9b21/solvers/ipopt_solver_internal.cc#L639)):*
> ```cpp
>   SetBoundingBoxConstraintDualSolution(*problem_, z_L, z_U,
>                                        bb_con_dual_variable_indices_, result_);
>   SetAllConstraintDualSolution(*problem_, lambda_, constraint_dual_start_index_,
> ```

nit: spurious whitespace change but I am fine letting it through if that is what clang prefers.

**Review by AlexandreAmice — COMMENTED** [review]
+@EricCousineau-TRI for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-:-Nz8pz-k1_myrpPeRkPK:b-2ku30v)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-:-Nz98rak5fprQCjRBV0F:b-vtj4w1)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21499)* status: missing label for release notes

___
*[`solvers/ipopt_solver_internal.cc` line 639 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21499#-Nz8QUSe0WxHk9-mbax6:-Nz9T-WT5AxBhnUeDXix:b-nbdhjd) ([raw file](https://github.com/RobotLocomotion/drake/blob/410aec286b6f8c85b2e04159d9b3a207e35a9b21/solvers/ipopt_solver_internal.cc#L639)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: spurious whitespace change but I am fine letting it through if that is what clang prefers.
</blockquote></details>

Yeah I did a `clang-format` and it reformated this line.

**Pull request merged**
