### PR TITLE
doc: Update code style guide for Python 3 and docstrings

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Realized I hadn't updated this when reviewing #12218.

Requires:
- [x] https://github.com/RobotLocomotion/styleguide/pull/21

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12236)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by EricCousineau-TRI** [comment]
Marking as `pydrake`, since it has the most relevant impact.

**Comment by ToffeeAlbina-TRI** [comment]
What's the status here - it's marked as in-progress but @jamiesnape is not currently working on it.  @jwnimmer-tri are you?

**Comment by EricCousineau-TRI** [comment]
This was stalled by me; there are review comments in the styleguide PR that I have not yet addressed yet. Sorry!

**Pull request merged**
