### PR TITLE
Adds Energy Cost to KinematicTrajectoryOptimization

### PR DESCRIPTION
**Pull request by cohnt**
Implements a cost to minimize the energy of a trajectory. The global optimum of this cost is equivalent to the optimum for path length, in the limit of infinitely many control points, and it has the benefit of yielding a convex quadratic objective (which is much easier for optimizers to handle). See [here](https://en.wikipedia.org/wiki/Geodesic#Riemannian_geometry) for further discussion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)

### CODE REVIEW

**Comment by cohnt** [comment]
Note that this doesn't currently work with OSQP or Mosek, due to #21579. It does pass with Gurobi.

@drake-jenkins-bot linux-jammy-clang-bazel-experimental-gurobi-release please

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-gurobi-release please

**Review by rpoyner-tri — COMMENTED** [review]
Good day,  @cohnt . This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, then please label it “status: do not review”.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-:-O-hdKy77wr6KS9e8udX:b-izg0fr)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review

:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-:-O-hoUULBf64MN5XqTlM:bw6y04m)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 210 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hnn6n91dDKaX53I9m:-O-hnn6n91dDKaX53I9n:bq0d4ey) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L210)):*
> ```objc
>       double weight = 1.0, bool use_conic_constraint = false);
> 
>   /** Adds a cost on an upper bound on the energy of the path, ∫₀ᵀ |q̇(t)|₂² dt,
> ```

I don't think this is still qdot on the inside? Now it is rdot?  In the function above, they work out to be equivalent, but here they do not?
___
*[`planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 425 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hpcaw-NXcYVww_ZUl:-O-hpcaw-NXcYVww_ZUm:bxzpxov) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L425)):*
> ```cpp
>   // No initial guess is necessary, because the underlying optimization problem
>   // is a (convex) QP.
>   auto result = Solve(trajopt_.prog());
> ```

the duration of this problem is unconstrained (and is probably being driven to zero?) .  consider calling trajopt_.AddDurationConstraint(4.0, 4.0) or something similar, with the duration != 1.0, to highlight the difference between qdot and rdot.
___
*[`planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 428 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hpIwUEYtP7lWmOjm4:-O-hpIwUEYtP7lWmOjm5:b-1a9oie) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L428)):*
> ```cpp
>   ASSERT_TRUE(result.is_success());
> 
>   // For n control points (i.e. n-1 segments), evenely spaced between (0,0,0)
> ```

nit: typo "evenely"

**Review by cohnt — COMMENTED** [review]
Wasn't sure who would make sense as a feature reviewer, so I left it empty. In the future, should I post on Drake Developers to ask for a reviewer if I'm unsure? Thanks Russ for taking it!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-:-O-kuE348OG0TyYUpbV1:b-503c58)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 210 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hnn6n91dDKaX53I9m:-O-kvTyr973BqFs8D4WV:b-nzy8h1) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L210)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't think this is still qdot on the inside? Now it is rdot?  In the function above, they work out to be equivalent, but here they do not?
</blockquote></details>

Yes, it should be ṙ on the inside -- I've updated the documentation. We want to minimize the energy of the path, independent of how fast that path is traveled. Minimum-energy paths will always be constant-speed, and any constant-speed traversal of such a path will minimize the energy functional. In this case, because we're squaring the speed of the trajectory, the two values would differ by a factor of the duration. (I can also separately add a AddTrajectoryEnergyCost that penalizes the energy of q̇ if you want.)

Separately, I've also updated the docstring for AddPathLengthCost to note the equivalence for the q̇ and ṙ formulations of arc length, but I can remove that if you don't like it.
___
*[`planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 425 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hpcaw-NXcYVww_ZUl:-O-kyzyoEkN2l2gBHZ89:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L425)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the duration of this problem is unconstrained (and is probably being driven to zero?) .  consider calling trajopt_.AddDurationConstraint(4.0, 4.0) or something similar, with the duration != 1.0, to highlight the difference between qdot and rdot.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc` line 428 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-hpIwUEYtP7lWmOjm4:-O-kz0y729_N2Gt1jSp8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/20050b042dc097194244bd8eeb7c211d45c88d01/planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc#L428)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: typo "evenely"
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
> Wasn't sure who would make sense as a feature reviewer, so I left it empty. In the future, should I post on Drake Developers to ask for a reviewer if I'm unsure? Thanks Russ for taking it!

(1) The primary purpose of the ping message from the platform reviewer is to make sure nothing gets left behind accidentally.  It's fine to move at whatever pace works best for you.

(2) As a PR author, the things you can do to help steer a PR:
- Be clear whether or not the PR is ready for a feature reviewer.  If not ready, the "do not review" tag can be used to communicate that.
- Be clear whether you already have a reviewer in mind (or plan to talk to your friends to find one), or whether you'd like the Drake team to choose a reviewer.

So for example if a PR is ready for review, but you don't have anyone chosen to review it, you can post a message to that effect on the PR and the Drake team will take it from there (often, yes, by posting to slack to see who's around).

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-:-O-l7fK35gwYEvVzbsU7:b223nro)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by xuchenhan-tri — COMMENTED** [review]
-(component: planning and control) The component tag is used for issues.

Platform :lgtm: with a few minor comments.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-:-O-nsFJsCGrhy8BOutVl:b-7g04ri)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`-- commits` line 18 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nsRL69rC35eKenyUm):*
BTW, friendly reminder to curate your commit message before merging.



_Code quote:_
```
- 93307f4: Merge branch 'master' into trajopt-energy-cost
```
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 199 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nqc2L8N4r6pSppeBq:-O-nqc2L8N4r6pSppeBr:btueubn) ([raw file](https://github.com/RobotLocomotion/drake/blob/93307f491598cdd47cfac2de5f281beafaa82d8a/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L199)):*
> ```objc
>   solvers::Binding<solvers::LinearCost> AddDurationCost(double weight = 1.0);
> 
>   /** Adds a cost on an upper bound of the length of the path, ∫₀ᵀ |q̇(t)|₂ dt,
> ```

BTW, should "weight" be part of this expression somehow?
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nsAUI6pSQ_trsakXQ:-O-nsAUI6pSQ_trsakXR:b-bdpnxf) ([raw file](https://github.com/RobotLocomotion/drake/blob/64d2eb5e4178af54dbde18ee0ddea59591500bdb/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L225)):*
> ```objc
>   symbolic::Variable duration_;
> 
>   /* TODO(russt): Minimize the use of symbolic to construct the constraints.
> ```

BTW, is this todo addressed by this PR?



_Code quote:_
```objc
  - Support a cost on an upper bound on "energy" of the path, ∫₀ᵀ |q̇(t)|₂² dt.
      void AddEnergyCost(double weight = 1.0);
```
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.cc` line 520 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nrRzd8eWE5MRzgff4:-O-nrRzd8eWE5MRzgff5:bpp4e0y) ([raw file](https://github.com/RobotLocomotion/drake/blob/93307f491598cdd47cfac2de5f281beafaa82d8a/planning/trajectory_optimization/kinematic_trajectory_optimization.cc#L520)):*
> ```cpp
>   // the matrix, since AddQuadraticCost multiplies by a factor of 0.5.
>   MatrixXd A(2 * num_positions_, 2 * num_positions_);
>   A.block(0, 0, num_positions_, num_positions_) =
> ```

BTW, this is equivalent to `A.topLeftCorner(num_positions_, num_positions_)` and some might find that easier to read.



_Code quote:_
```cpp
A.block(0, 0, num_positions_, num_positions_)
```

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`-- commits` line 18 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nsRL69rC35eKenyUm):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, friendly reminder to curate your commit message before merging.
</blockquote></details>

Updated the message of the last commit to be the desired commit message. When platform review is done, I can squash and merge with that message.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 199 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nqc2L8N4r6pSppeBq:-O-po2an0jgdPs9G7JLc:b-c01ioz) ([raw file](https://github.com/RobotLocomotion/drake/blob/93307f491598cdd47cfac2de5f281beafaa82d8a/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L199)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, should "weight" be part of this expression somehow?
</blockquote></details>

My preference is to keep it separate. The expression listed gives the length of the path; the user can separately adjust the weight of this cost in the optimization problem.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nsAUI6pSQ_trsakXQ:-O-poSpSCG_ES9u3IP2k:b-owgkg2) ([raw file](https://github.com/RobotLocomotion/drake/blob/64d2eb5e4178af54dbde18ee0ddea59591500bdb/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L225)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is this todo addressed by this PR?
</blockquote></details>

I'll defer to @RussTedrake on this one. The energy of the trajectory (which is described here) is precisely the duration times the energy of the path (the cost which I have added). So although they're not quite the same, they do very similar things.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.cc` line 520 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nrRzd8eWE5MRzgff4:-O-powA8BiccjquGE8Hv:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/93307f491598cdd47cfac2de5f281beafaa82d8a/planning/trajectory_optimization/kinematic_trajectory_optimization.cc#L520)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this is equivalent to `A.topLeftCorner(num_positions_, num_positions_)` and some might find that easier to read.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 225 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-nsAUI6pSQ_trsakXQ:-O-vUmOG1gOkXupZoHr-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/64d2eb5e4178af54dbde18ee0ddea59591500bdb/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L225)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I do think this PR is enough to remove the TODO; we can implement the other if we find that it's needed.
(btw -- the comment is about a different TODO than the one about symbolics that this is attached to in reviewable)
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/kinematic_trajectory_optimization.h` line 210 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21587#-O-uL8rA6rAgZ8l5Xgxf:-O-vUhfp8D4ahgprEt_N:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49eb51853998eca72d792e2d87d0dc2f9a7859ee/planning/trajectory_optimization/kinematic_trajectory_optimization.h#L210)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

based on https://stackoverflow.com/questions/78645004/clarification-on-the-distinction-between-addpathvelocityconstraint-and-addveloci , perhaps it's good to call out that this is a convex cost...

suggestion:
"Adds a cost" => "Adds a convex quadratic cost"
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21587)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by xuchenhan-tri** [comment]
+(status: squashing now)

**Pull request merged**
