### PR TITLE
Add a program to run robot plans on the iiwa arm

### PR DESCRIPTION
**Pull request by sammy-tri**
Update LCM, add robotlocomotion_lcmtypes, and add a program to run robot plans on the arm.

Also converts kuka_ik_demo to send an LCM plan message instead of commanding the arm directly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3928)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-:-KV5t-Gp6jTM0wDX9dzB:b-psw9ws)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-:-KV5yfUP_QpjbWYn4mn7:b-ykw85)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by sammy-tri** [comment]
note: the update of lcmtypes was split out into #3930 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-:-KV6jXObaSmN96mGyQ9T:b-h7w80k)*

**Comment by jwnimmer-tri** [comment]
Sorry for the slow.  Lots of PRs today.  Partial checkpoint.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7FRz_w7l7tnZ9gusv:-KV7FRzaYZUf4aeeL78T:b-k6v18h) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L1)):*
> ```cpp
> #include <iostream>
> ```

BTW I file-level comment or directory-level README explaining what this program does and how to run it, would be nice.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7E78wzMK2gsKRuA45:-KV7E78wzMK2gsKRuA46:b3sl0v1) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L30)):*
> ```cpp
> using drake::Vector1d;
> 
> const char* kLcmPlanChannel = "COMMITTED_ROBOT_PLAN";
> ```

`const char* const`, for literal strings, I think?

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7EJPvZ8gNCW6g7ARn:-KV7EJPwr7aYZMY0-SwS:b-ghimk0) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L119)):*
> ```cpp
>   }
> 
>   robotlocomotion::robot_plan_t plan;
> ```

BTW, I've taken to putting `{}` after LCM objects, to ensure they are value-initialized with zeros, even if we forget to set some of the fields.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7F4FjrwlsO_HIqU79:-KV7F4Fk3iChA556Z8Bk:b-blnyuw) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L128)):*
> ```cpp
>     bot_core::robot_state_t& step = plan.plan[i];
>     step.utime = t[i] * 1e6;
>     memset(&step.pose, 0 , sizeof(step.pose));
> ```

BTW Instead of all of the memsets, would assigning a value-initalized `robot_state_t` earlier be more concise / less brittle?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-:-KV7FhijV8538LjySjUS:bmkvbj5)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7RY38hMK-md2S1bwN:-KV7RY38hMK-md2S1bwO:b-37tub2) (no related file):*
FYI A non-blocking discussion, but this PR is an (admittedly small) pile of code that's not tested and kind of just dumped into a few functions threaded though a main routine.  I can't really understand it as I read through it, and if other folks' PRs break it (other that compile failures) nobody will be the wiser (until you want to run it again, I guess)?  For a thing in `examples` I guess that's fine as a stepping stone to refactoring and building up better tools.  I hope the future has smaller, better-tested, and well-documented classes on the way.  In particular, a System 2.0 phrasing of this code should be entirely possible, and lead to easier test and validation.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7P8Ek3NLsFspZgZKK:-KV7P8Ek3NLsFspZgZKL:b5vabtf) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L29)):*
> ```cpp
> namespace {
> 
> const char* kLcmStatusChannel = "IIWA_STATUS";
> ```

`const char* const` for literal strings, I think?

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7PcYj0nZxtl7ZYaM_:-KV7PcYkD5_QczC4AMBH:b-p046xj) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L174)):*
> ```cpp
>   std::shared_ptr<lcm::LCM> lcm_;
>   const RigidBodyTree& tree_;
>   int plan_number_;
> ```

Required `{}` per code_style_guide.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7PNIRFOU-8gLwqZBh:-KV7PNIRFOU-8gLwqZBi:b-rdn6nl) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L180)):*
> ```cpp
> 
> int do_main(int argc, const char* argv[]) {
>   std::shared_ptr<lcm::LCM> lcm = std::make_shared<lcm::LCM>();
> ```

A shared_ptr seems like overkill here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-:-KV7RXpTj2I3tRqVCbGI:bnfp4nl)*

**Comment by naveenoid** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7RY38hMK-md2S1bwN:-KVANzERD0eirxwn-5iy:b-37kybz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI A non-blocking discussion, but this PR is an (admittedly small) pile of code that's not tested and kind of just dumped into a few functions threaded though a main routine.  I can't really understand it as I read through it, and if other folks' PRs break it (other that compile failures) nobody will be the wiser (until you want to run it again, I guess)?  For a thing in `examples` I guess that's fine as a stepping stone to refactoring and building up better tools.  I hope the future has smaller, better-tested, and well-documented classes on the way.  In particular, a System 2.0 phrasing of this code should be entirely possible, and lead to easier test and validation.
</details>
Seconding the comment above : This code itself does not have a test and I think it is meant to be used in conjunction with  a real robot / LCM input simulation. That needs to be mentioned in a comment. Apart from this documentation request, :lgtm: 

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KVAN0hJg3txEToJ1YV2:-KVAN0hKalpAFuqij-uv:bq7e0hn) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L124)):*
> ```cpp
>   plan.num_states = kNumTimesteps;
>   plan.plan.resize(kNumTimesteps);
>   plan.plan_info.resize(kNumTimesteps);
> ```

BTW: If I get it right, the following bit of code basically packs the q_sol into a convenient data structure right on robot_state_t right? Maybe this can be explained a bit better before this section?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928)*

**Comment by sammy-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7RY38hMK-md2S1bwN:-KVArjz15qeVNxfUS_L6:b6k22e1) (no related file):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> Seconding the comment above : This code itself does not have a test and I think it is meant to be used in conjunction with  a real robot / LCM input simulation. That needs to be mentioned in a comment. Apart from this documentation request, :lgtm: 
</details>
I felt that a system2 formulation would have been needlessly verbose and tedious to construct (the LCM message parsing in #3936 is one example here).

I guess the robot_plan_t to PiecewisePolynomial part of this code might be generic enough to factor out and write a test for?  I'm not at all sure it would actually work for another robot, but it seems plausible.

I suppose it would be feasible to test the code which calls PiecewisePolynomial::value() and packs the result into an iiwa_command_t if it were pulled out of the main loop.  I suspect it is not particularly reusable, but I may be incorrect.

This class is 139 lines for the declaration + implementation.  Personally I think that's actually a little on the small side.

Frankly, with the exception of System2-ification, I'm not clear on your vision for "better tools".  I would like to know more.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7FRz_w7l7tnZ9gusv:-KVAoZLiQcXlEcf3wfPE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I file-level comment or directory-level README explaining what this program does and how to run it, would be nice.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7E78wzMK2gsKRuA45:-KVApB3iJcsMhP1hT14l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `const char* const`, for literal strings, I think?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7EJPvZ8gNCW6g7ARn:-KVApIN0zvduIlNITF1w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW, I've taken to putting `{}` after LCM objects, to ensure they are value-initialized with zeros, even if we forget to set some of the fields.
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KVAN0hJg3txEToJ1YV2:-KVApZtob2UdcuhoIVQW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L124)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW: If I get it right, the following bit of code basically packs the q_sol into a convenient data structure right on robot_state_t right? Maybe this can be explained a bit better before this section?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7F4FjrwlsO_HIqU79:-KVAq6KJe4v9-uNzHhQ-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_ik_demo.cc#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Instead of all of the memsets, would assigning a value-initalized `robot_state_t` earlier be more concise / less brittle?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7P8Ek3NLsFspZgZKK:-KVAotsDNEPt8L7Rzp3O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `const char* const` for literal strings, I think?
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 174 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7PcYj0nZxtl7ZYaM_:-KVAqOD0M5pMlmCOoYl_:b-z59hko) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Required `{}` per code_style_guide.
</details>
I must have been sleeping when this became mandatory for members which are also set in the static initializer list.  Maybe I should set it a third time in the body of the constructor just to be *really* sure?

(I actually do think that I understand the reasoning behind it, and I'm not going to try to get it pulled from the style guide)

Done. 

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 180 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7PNIRFOU-8gLwqZBh:-KVAr22Hw_JqLjU2HYX7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e78481a7693baccaa88fd1a83da01def7df3c2f9/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L180)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> A shared_ptr seems like overkill here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3928#-KV7RY38hMK-md2S1bwN:-KVBJzJuSJbQzVaZ58xK:b4ztnia) (no related file):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I felt that a system2 formulation would have been needlessly verbose and tedious to construct (the LCM message parsing in #3936 is one example here).
> 
> I guess the robot_plan_t to PiecewisePolynomial part of this code might be generic enough to factor out and write a test for?  I'm not at all sure it would actually work for another robot, but it seems plausible.
> 
> I suppose it would be feasible to test the code which calls PiecewisePolynomial::value() and packs the result into an iiwa_command_t if it were pulled out of the main loop.  I suspect it is not particularly reusable, but I may be incorrect.
> 
> This class is 139 lines for the declaration + implementation.  Personally I think that's actually a little on the small side.
> 
> Frankly, with the exception of System2-ification, I'm not clear on your vision for "better tools".  I would like to know more.
</details>
I agree on the uncertainty of winning by porting the LCM bits to System2.  I agree that factoring / generalizing this in order to reuse it would be speculative & premature.

I think my main point is that for for something like kuka_plan_runner, the while-loop body and HandlePlan logic would benefit from factoring (to be outside of a main-program component) so that the code could be unit / regression tested, even with a simple few cases.  That could take the form of helper methods with specific contracts, or just taking the whole class as one piece and doing it using DrakeMockLcm.

The secondary "tools" point relates, as you guessed, to the PP / traj / message conversion logic.  I would love for us to have more powerful tooling for making that kind of boilerplate go away, whether that be an ExtractMethod refactoring from the code in this PR, or just a better LCM / C++ / PP ecosystem in the first place.

(FYI This thread is still marked resolved on my end.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3928)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Pull request merged**
