### PR TITLE
[automated refactor] Add a clang-format file, and format all C++ files in drake/ to comply with the Google style guide.

### PR DESCRIPTION
**Pull request by david-german-tri**
#1741 

Tested by make && make test.  @tkoolen, please take a look when you get a chance?

### CODE REVIEW

**Comment by tkoolen** [comment]
Looks very reasonable, from a quick glance.

Now there are 12 other pull requests open that are going to have lots of merge conflicts after this goes in. So we'll have to make a decision about how to handle those. Maybe we should first try to get https://github.com/RobotLocomotion/drake/pull/1678 in at least?

**Comment by tkoolen** [comment]
@rdeits

**Comment by david-german-tri** [comment]
The pull request authors can (relatively) easily use --ours and re-run clang-format afterwards.  That said, I agree #1678 looks like it would be painful, and perhaps the follow-up #1683 also.  @rdeits,@mwoehlke-kitware, how far are those from merge?

**Comment by rdeits** [comment]
#1678 was probably ready yesterday, but has acquired new merge conflicts since then, so we're waiting for a cleanup there. #1683 is still blocked by #1678, but should be pretty trivial once 1678 is in. I would like to try to get at least #1678 in before we do this.

**Comment by david-german-tri** [comment]
The command for this cleanup is:

find drake -regextype posix-extended -regex ".*\.(h|cc|cpp)" | xargs clang-format -i

**Comment by david-german-tri** [comment]
I've re-run the formatter post #1678 and #1683.

**Comment by RussTedrake** [comment]
the last important idea was to have the actual reformat commit happen by a robot user.  is that tough to do?

**Comment by david-german-tri** [comment]
According to the [GitHub docs](https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/), bot accounts are just user accounts that happen to be automated.  If the goal is just to leave something distinctive in the git blame, I could squash all the commits into one with "[automated refactor]" or something similar at the beginning of the commit string.  That seems more straightforward than maintaining a separate account just for its name.

**Comment by RussTedrake** [comment]
We already have some bot accounts (like jenkins and drake-build).  I propose we use one of them?

**Comment by david-german-tri** [comment]
Superseded by PR #1776.

**Pull request closed without merging**
