### PR TITLE
Make MathematicalProgramSolverInterface an interface again

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6307)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri for volunteer feature review.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-:-KmCETYpXYzhB-O_Xo6N:b-gk0e4q)*

**Comment by rpoyner-tri** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCQ8-6mkBV258dHnbH:-KmCQ8-75FelLIgS5AUJ:bdevikh) ([raw file](https://github.com/robotlocomotion/drake/blob/24d08a3eef5629b3581bbabcb60f611439ab2b21/drake/systems/estimators/dev/pose_estimation_test.cc#L192)):*
> ```cpp
>   std::cout << "Solver type " << static_cast<int>(solver_type)
>             << " solution result " << static_cast<int>(solution_result)
>             << " solver result " << static_cast<int>(solver_result)
> ```

Why does this need a static_cast? It's already an int.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/estimators/dev/pose_estimation_test.cc, line 192 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCQ8-6mkBV258dHnbH:-KmCU-YtGGd46jQz6GOl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/24d08a3eef5629b3581bbabcb60f611439ab2b21/drake/systems/estimators/dev/pose_estimation_test.cc#L192)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Why does this need a static_cast? It's already an int.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-:-KmCUwCy_gUC9utV72wj:bppyoqq)*

**Comment by jwnimmer-tri** [comment]
The jchart build flake happened.
@drake-jenkins-bot linux-clang-experimental-debug please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-:-KmCdhYluWu4Q6nJHXXU:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm:. A couple of BTWs, ptal.

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program_solver_interface.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCdvye_8m0MJ_qcCjh:-KmCdvye_8m0MJ_qcCji:b1be386) ([raw file](https://github.com/robotlocomotion/drake/blob/c461756cf34b30ec1921f48b23f59065ffa011b6/drake/solvers/mathematical_program_solver_interface.cc#L4)):*
> ```cpp
> 
> #include <sstream>
> #include <stdexcept>
> ```

BTW unused

---

*[drake/solvers/mathematical_program_solver_interface.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCd_HsFgVuXeK8cTks:-KmCd_HsFgVuXeK8cTkt:b-xllbj1) ([raw file](https://github.com/robotlocomotion/drake/blob/c461756cf34b30ec1921f48b23f59065ffa011b6/drake/solvers/mathematical_program_solver_interface.cc#L10)):*
> ```cpp
> 
> MathematicalProgramSolverInterface::MathematicalProgramSolverInterface() {}
> MathematicalProgramSolverInterface::~MathematicalProgramSolverInterface() {}
> ```

BTW why do you want these in the .cc ? Without that the interface would be header only (and these could be =default).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-:-KmChDzs4lVsLYWCBuRQ:bnh55n3)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program_solver_interface.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCdvye_8m0MJ_qcCjh:-KmCi6A0Xav8GsLsQsSX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c461756cf34b30ec1921f48b23f59065ffa011b6/drake/solvers/mathematical_program_solver_interface.cc#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unused
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program_solver_interface.cc, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6307#-KmCd_HsFgVuXeK8cTks:-KmCicd-YbH1NKJ--G4S:bvk9h7j) ([raw file](https://github.com/robotlocomotion/drake/blob/c461756cf34b30ec1921f48b23f59065ffa011b6/drake/solvers/mathematical_program_solver_interface.cc#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why do you want these in the .cc ? Without that the interface would be header only (and these could be =default).
</blockquote></details>

I think its a best practice to give classes some kind of required linkage when possible, to ensure that the build system is passing the correct object libraries around in the right places.  Also, in general unless methods are thought to be performance-critical, I try to put them into cc files.

_However_, going back and looking at the build rules, I see that we have an unusual `:mathematical_program_api` circular dependency thing -- which means I _shouldn't_ give this class linkage -- it needs to stay all-inline.

So I've changed it (for now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6307)*

**Pull request merged**
