### PR TITLE
[geometry] Repeated Meshcat::AddButton calls reset the click count

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #16726.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  Thanks for doing it!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808#-:-MyK91PP7gQkaPQoXOjb:bv5boa8)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyK8tow9lePrrbD6YUv:-MyK8tox0qV9FCytSomF:b-qgftak) ([raw file](https://github.com/robotlocomotion/drake/blob/bea61e8dbf5129cd0ade3582a3892f82e089294a/geometry/test/meshcat_test.cc#L598)):*
> ```cpp
>   // Adding the button anew starts with a zero count again.
>   meshcat.AddButton("alice");
>   EXPECT_EQ(meshcat.GetButtonClicks("alice"), 0);
> ```

btw -- obviously it would be nice to test that the count actually resets, but I understand we don't have the mechanism to do that right now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808)* status: needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/test/meshcat_test.cc, line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyK8tow9lePrrbD6YUv:-MyKALfN04TJwnp9NQbe:b-xyiekj) ([raw file](https://github.com/robotlocomotion/drake/blob/bea61e8dbf5129cd0ade3582a3892f82e089294a/geometry/test/meshcat_test.cc#L598)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- obviously it would be nice to test that the count actually resets, but I understand we don't have the mechanism to do that right now.
</blockquote></details>

Done.

Now the deleted button had a count==1 when it was deleted, and here we confirm it's zero when it re-appears.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyK8tow9lePrrbD6YUv:-MyKAnHsAsjjwkZtoWmo:b-55yljb) ([raw file](https://github.com/robotlocomotion/drake/blob/bea61e8dbf5129cd0ade3582a3892f82e089294a/geometry/test/meshcat_test.cc#L598)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

Now the deleted button had a count==1 when it was deleted, and here we confirm it's zero when it re-appears.
</blockquote></details>

Awesome.  But then we should also have a test where alice has a count of 1, then is added again (without deletion), and gets a count of zero.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/test/meshcat_test.cc, line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyK8tow9lePrrbD6YUv:-MyKBBIw-6BbItuhEfIX:b3asehg) ([raw file](https://github.com/robotlocomotion/drake/blob/bea61e8dbf5129cd0ade3582a3892f82e089294a/geometry/test/meshcat_test.cc#L598)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Awesome.  But then we should also have a test where alice has a count of 1, then is added again (without deletion), and gets a count of zero.
</blockquote></details>

That's the "// Adding using an existing button name resets its count." case about 25 lines prior, I think.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 598 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyK8tow9lePrrbD6YUv:-MyKBLw620F8dj29_Z6f:b-i6zmg2) ([raw file](https://github.com/robotlocomotion/drake/blob/bea61e8dbf5129cd0ade3582a3892f82e089294a/geometry/test/meshcat_test.cc#L598)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That's the "// Adding using an existing button name resets its count." case about 25 lines prior, I think.
</blockquote></details>

Ah, yes.  Thanks.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808#-:-MyKH8dCAz0gtvggFtbu:bcpz082)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[geometry/test/meshcat_test.cc, line 662 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16808#-MyKGXGk00hDN5TTBgZL:-MyKGXGk00hDN5TTBgZM:bg2vfi7) ([raw file](https://github.com/robotlocomotion/drake/blob/b82ad779b888a38a1340f398dd2103eb2c48aec5/geometry/test/meshcat_test.cc#L662)):*
> ```cpp
>   meshcat.AddSlider("slider", 0.2, 1.5, 0.1, 0.5);
> 
>   // We must reject adding controls with duplicated names.
> ```

nit, this comment could use an update now that we allow duplicated named button.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri platform

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16808#-:-MyKJZMQ9c37h7BxIH6u:bdyvkhx)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
