### PR TITLE
fix the eigen align problem on Windows 32 machine

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also rename `val` to `value`, prefer more meaningful name

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3099)

### CODE REVIEW

**Comment by liangfok** [comment]
:lgtm: I hope this fixes the [Win32 CI continuous builds](https://drake-jenkins.csail.mit.edu/view/Continuous/job/windows-msvc-32-continuous-minimal-debug/)!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3099#-:-KOkcPFBETGhDe-D6V6r:b62yh0x)*

**Comment by david-german-tri** [comment]
Build #61: https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-32-experimental/

**Comment by liangfok** [comment]
Bummer! The error persists.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/test/simulation_trajectory_logger_test.cc, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3099#-KOko4pkW9NEDraCxWhq:-KOko4pl2VUjx8LObjnW:bn26s89) ([raw file](https://github.com/robotlocomotion/drake/blob/57058022067ba642ff3794cca9ae64f152a04c49/drake/systems/test/simulation_trajectory_logger_test.cc#L21)):*
> ```cpp
>   const size_t kTrajDim = 2;
>   auto traj_logger =
>       std::make_shared<TrajectoryLogger<EigenVector<kTrajDim>::type>>(kTrajDim);
> ```

I'm completely guessing but could this be the problem? Maybe you need to pass in an aligned allocator too?

Also, can this be a `std::unique_ptr<TrajectoryLogger<EigenVector<kTrajDim>::type>>`? 

I believe our style guide discourages the use of `std::shared_ptr`.

https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3099)*

**Comment by hongkai-dai** [comment]
Thank @liangfok @david-german-tri @jwnimmer-tri for the help. It looks Jenkins is OK on the Windows 32 machine https://drake-jenkins.csail.mit.edu/job/windows-msvc-32-experimental/62/

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_logger.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3099#-KOkoHtDkU2nHH11Qp5w:-KOkoHtDkU2nHH11Qp5x:b-yklj9i) ([raw file](https://github.com/robotlocomotion/drake/blob/57058022067ba642ff3794cca9ae64f152a04c49/drake/systems/trajectory_logger.h#L18)):*
> ```objc
>   std::vector<double> time;
>   std::vector<Vector<double>, Eigen::aligned_allocator<Vector<double>>> value;
>   TimeSampleTrajectory() : time(0), value(0) {}
> ```

BTW, this constructor is unnecessary.

---

*[drake/systems/test/simulation_trajectory_logger_test.cc, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3099#-KOko4pkW9NEDraCxWhq:-KOldTdTHXdCfzAMidUp:bvd7d4z) ([raw file](https://github.com/robotlocomotion/drake/blob/57058022067ba642ff3794cca9ae64f152a04c49/drake/systems/test/simulation_trajectory_logger_test.cc#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I'm completely guessing but could this be the problem? Maybe you need to pass in an aligned allocator too?
> 
> Also, can this be a `std::unique_ptr<TrajectoryLogger<EigenVector<kTrajDim>::type>>`? 
> 
> I believe our style guide discourages the use of `std::shared_ptr`.
> 
> https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers
</details>
Hooray, looks like it's fixed below!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3099#-:-KOldb1uDc3beEV1ucfj:bnfp4nl)*

**Pull request merged**
