### PR TITLE
[geometry] Parameter to choose output format in hydroelastic_callback.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Another step for  [implementation plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123).  After this PR #15200(hydroelastic_callback), the next PR is #15204(ProximityEngine).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15200)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15200#-:-McH1mxZ2e1aKfflvqr1:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with a few nits. +@seancurtis-tri for platform review, please.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15200#-:-McjthF_54jLo6jMvHeo:b8v6hxw)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @DamrongGuoy and @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 718 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-McjtYKJE0K2gg0UugiU:-McjtYKJE0K2gg0UugiV:blpxaix) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity_engine.cc#L718)):*
> ```cpp
>       const unordered_map<GeometryId, RigidTransform<T>>& X_WGs) const {
>     vector<ContactSurface<T>> surfaces;
>     // All these quantities are aliased in the callback data.
> ```

nit: all quantities, except `ContactPolygonRepresentation`, are aliased.
___
*[geometry/proximity/hydroelastic_callback.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-Mcjsd0oDEMl86jHmgtV:-Mcjsd0oDEMl86jHmgtW:b-k7p122) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/hydroelastic_callback.h#L54)):*
> ```objc
>    @param geometries_in           The set of all hydroelastic geometric
>                                   representations. Aliased.
>    @param polygon_representation  The choice of representation of contact
> ```

nit: missing the "_in" in the parameter name ->`polygon_representation_in`

**Comment by DamrongGuoy** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15200)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 718 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-McjtYKJE0K2gg0UugiU:-MckyHWMBAYeZWPSiFMg:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity_engine.cc#L718)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: all quantities, except `ContactPolygonRepresentation`, are aliased.
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/hydroelastic_callback.h, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-Mcjsd0oDEMl86jHmgtV:-MckxkSGDvlmH69e0x1E:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/hydroelastic_callback.h#L54)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: missing the "_in" in the parameter name ->`polygon_representation_in`
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/hydroelastic_callback.h, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-Mck8Jim3Nfv2XHCgix_:-Mckuv9qCHaNNuMU6P3A:b-xhjxgu) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/hydroelastic_callback.h#L114)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In your development plan, where do these TODOs get resolved? They should *definitely* get resolved prior to changing the public API.
</blockquote></details>

They are in the plan [(link to the plan)](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123) like this:
- [ ] Switch between two representations of output from three geometric intersection codes:
    - [X] PRs [15131](https://github.com/RobotLocomotion/drake/pull/15131): mesh_intersection,
    - [ ] mesh_plane_intersection,
    - [ ] mesh_half_space_intersection. 

The public API (QueryObject) is still an early draft PR. I'll work on `mesh_plane_intersection` and `mesh_half_space_intersection` before starting the review of QueryObject.

I'm not sure that I understand your question correctly. Did I answer your question?  Please kindly let me know, otherwise.
___
*[geometry/proximity/test/hydroelastic_callback_test.cc, line 319 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-Mck8cYZ2TCW9tE8wjmP:-Mckstpf-zL-7_S6DS66:b-v6br5p) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/test/hydroelastic_callback_test.cc#L319)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: Are you aware that this trace will look like "representation = 0"? As such, if a bug were to come up, the trace would require decoding for this message to be helpful. If you wrote a function that would turn your enumeration into strings, this would be far more user friendly.
</blockquote></details>

Thanks for pointing that out. Yes, I have seen it before.  Sorry for inconvenience.
___
*[geometry/proximity/test/hydroelastic_callback_test.cc, line 325 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-Mck9lYn9XKVQESoNX8n:-MckrrMPEpYuyTJw1RuN:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/test/hydroelastic_callback_test.cc#L325)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

While I see all the call sites of `DispatchRigidSoftCalculation` have been updated to take the enum, I don't see any test that makes sure that the returned mesh actually has the expected properties - i.e., the two meshes should have the same total area but different triangle counts.

You don't have to do more extensive tests, you just need a modicum of proof that the input parameter is being passed down (as manifest by the different in return value).
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 972 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15200#-MckAUvS25frZ6hwWUtW:-MckjU1K0FLpVz4qmW8B:b76n1hf) ([raw file](https://github.com/robotlocomotion/drake/blob/41cc411dd433bc74b71f767878ae895fe5725f22/geometry/proximity/test/mesh_intersection_test.cc#L972)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: An invariant between these two meshes (based on the representation choice) is that the *total area* should match. That got missed in the previous PR.

Ideally, it would test other invariants, (i.e., the centroid of a representative triangle matches a vertex in the other mesh (such that all adjacent triangles are planar and have the same normal as the representative triangle). These other invariants are heavier and I'm open to skipping those. But comparing total area is cheap and easy to do here in the test (a small price to pay for increased confidence).
</blockquote></details>

The previous PR already had `VerifySampleVolumeFieldOnSurface()` to check the total area to be 0.25 * 0.25 for both meshes (it also checked field values, face normals, and field gradients).   Would that be enough please?

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15200#-:-McnzL4u44_2GcWDVMi5:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),joemasterjohn (waiting on @joemasterjohn)

**Comment by DamrongGuoy** [comment]
Thank you @seancurtis-tri @joemasterjohn .

**Pull request merged**
