### PR TITLE
Added World Link to Prius.urdf

### LINKED ISSUE #2247: Add World Link to Prius.urdf to Avoid Externally Specified Root Link Offset
Once PR https://github.com/RobotLocomotion/drake/pull/2171 is merged, we should update `prius.urdf` to have a world link and proper offset between the world and the root link (`chassis_floor`). This will eliminate the need to encode the necessary offset for `prius.urdf` in `drake-distro/drake/drake/examples/Cars/car_simulation.cc`.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #2247 

Modified `prius.urdf` to have a world link so it can be correctly offset in the world. Updated `car_simulation.cc` to not specify a `weld_to_frame` parameter since this information is now contained within the URDF and SDF files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2580)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review since he has recent knowledge about the car simulation.
+@ggould-tri for platform review since it's a Friday.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKV0kJTxwb0Ir5FJ66k:-329063995)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/Cars/car_simulation.cc, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV5L8AMMjS1WioIl21:-KKV5L8BS4nJYmiWAfL1:-1547761319) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L30)):*
> ```cpp
> 
>   // The Z-axis offset between Drake's world frame and the vehicle's world
>   // frame.
> ```

I'm not sure what is meant here by two different world frames.  The feature reviewer should evaluate if this is clear to someone who knows the feature better.

---

*[drake/examples/Cars/car_simulation.cc, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV5zcStQWLChmGoDyA:-KKV5zcStQWLChmGoDyB:-949538519) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L37)):*
> ```cpp
>   // see: https://github.com/RobotLocomotion/drake/pull/2171 and
>   // https://github.com/RobotLocomotion/drake/issues/2247
>   if (std::string(argv[1]).find("prius.urdf") != std::string::npos)
> ```

Special-casing files name "prius.urdf" seems like an extreme solution (it doesn't, for instance, capture the very similar "prius_rear_wheel_drive.urdf" in the same directory).  Is there a more general way to do this?

---

*[drake/examples/Cars/car_simulation.cc, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV6ejGdNYeuJXg0ATR:-KKV6ejGdNYeuJXg0ATS:-1510122667) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L38)):*
> ```cpp
>   // https://github.com/RobotLocomotion/drake/issues/2247
>   if (std::string(argv[1]).find("prius.urdf") != std::string::npos)
>     z_offset = 0.378326;
> ```

Is there a reason to duplicate this constant here and not draw it from the same value in the urdf?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580)*

**Comment by ggould-tri** [comment]
Ignore my last comments -- they were a misreading of the diff

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKV6wrTpkQj_FK3eHGu:336471627)*

**Comment by ggould-tri** [comment]
*[drake/examples/Cars/car_simulation.cc, line 38 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV6ejGdNYeuJXg0ATR:-KKV7BOayAyBV5eGJPh-:-567172144) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Is there a reason to duplicate this constant here and not draw it from the same value in the urdf?
</details>
This comment was wrong; removing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/Cars/car_simulation.cc, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV5L8AMMjS1WioIl21:-KKV7MsuSK9QI9q3izZF:-402467270) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L30)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> I'm not sure what is meant here by two different world frames.  The feature reviewer should evaluate if this is clear to someone who knows the feature better.
</details>
This comment was wrong; removing.

---

*[drake/examples/Cars/car_simulation.cc, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-KKV5zcStQWLChmGoDyA:-KKV7HIZg2LVCfUQcXW5:-402467270) ([raw file](https://github.com/robotlocomotion/drake/blob/efa2bc935370c1aef824c55d3025518f1c17deed/drake/examples/Cars/car_simulation.cc#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Special-casing files name "prius.urdf" seems like an extreme solution (it doesn't, for instance, capture the very similar "prius_rear_wheel_drive.urdf" in the same directory).  Is there a more general way to do this?
</details>
This comment was wrong; removing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580)*

**Comment by ggould-tri** [comment]
Now that I actually can tell the difference between removed code and new code (oops!), this is :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKV7Uy9KVIms6ZWxG5_:1724192897)*

**Comment by liangfok** [comment]
Looks like I broke a unit test: https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=36647
Will fix it soon.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKV8AJEo3EZGw1Mjk3v:-1069978432)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKW5lIq4syWTDQa75G4:1417088721)*

**Comment by liangfok** [comment]
CI clang-mac suffered a known flake:

```
22:49:18 FATAL: java.io.IOException: Unexpected termination of the channel
22:49:18 hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
```

@drake-jenkins-bot retest this please

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580#-:-KKYamkEmQtD6PlrOpDT:-1282129911)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2580)*

**Pull request merged**
