### PR TITLE
Adds RgbdCameraDiscrete zero order hold wrapper.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is a portion taken from #6906 to simplify the PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6942)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-:-KsobK3nu4L2e4lA_UmI:b-1actl4)*

**Comment by kunimatsu-tri** [comment]
Thanks for creating this PR!

:lgtm:  with two BTW comments.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 885 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Kssppz51K9AMEVCwy3Y:-Kssppz51K9AMEVCwy3Z:bnq3pit) ([raw file](https://github.com/robotlocomotion/drake/blob/e98d8ac618124374d07dc5def528ad32710ceac3/drake/systems/sensors/rgbd_camera.cc#L885)):*
> ```cpp
>   DiagramBuilder<double> builder;
>   builder.AddSystem(std::move(camera));
>   input_port_state_ = builder.ExportInput(camera_->get_input_port(0));
> ```

BTW, this is fine but you can also call `camera_->state_input_port()`.

---

*[drake/systems/sensors/rgbd_camera.h, line 266 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KssoqEohNndzxHELH5V:-KssoqEohNndzxHELH5W:bashd1i) ([raw file](https://github.com/robotlocomotion/drake/blob/e98d8ac618124374d07dc5def528ad32710ceac3/drake/systems/sensors/rgbd_camera.h#L266)):*
> ```objc
>   /// Returns reference to RgbdCamera intsance.
>   const RgbdCamera& camera() const { return *camera_; }
>   /// Returns reference to RgbdCamera intsance.
> ```

BTW, would you mind to put a blank line ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-:-KsssMtKYbBthpZT2uNU:b-c6ktu6)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review, please. Thanks!

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/rgbd_camera.cc, line 885 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Kssppz51K9AMEVCwy3Y:-KstGBd9dVnHi061y57P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e98d8ac618124374d07dc5def528ad32710ceac3/drake/systems/sensors/rgbd_camera.cc#L885)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, this is fine but you can also call `camera_->state_input_port()`.
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.h, line 266 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KssoqEohNndzxHELH5V:-KstGCEP4rD_QjSQOUH0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e98d8ac618124374d07dc5def528ad32710ceac3/drake/systems/sensors/rgbd_camera.h#L266)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, would you mind to put a blank line ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-:-KstGDw9T2CBwiVqabu2:bai31ts)*

**Comment by soonho-tri** [comment]
:lgtm: (marked a few places where we can add `const`s).

:apple: tested + memchecked.

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 332 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Ksts2lk2gkkcsOZcJHS:-Ksts2llWMlTk-cUPZHV:bu4hbc0) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/BUILD#L332)):*
> ```Python
>     name = "test_models",
>     testonly = 1,
>     srcs = glob([
> ```

FYI, it seems that we don't need `glob()` here. The following is sufficient:

```
    srcs = [
        "test/models/box.sdf",
        "test/models/cylinder.sdf",
        "test/models/mesh_box.sdf",
        "test/models/meshes/box.obj",
        "test/models/meshes/box.png",
        "test/models/multiple_visuals.sdf",
        "test/models/nothing.sdf",
        "test/models/sphere.sdf",
        "test/models/three_boxes.sdf",
    ],
```

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-KstuiTs1q9SRCaGJuMM:bt2js7m) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
> ```cpp
> 
> RgbdCameraDiscrete::RgbdCameraDiscrete(std::unique_ptr<RgbdCamera> camera,
>                                        double period)
> ```

BTW, -> `const double period`

---

*[drake/systems/sensors/rgbd_camera.cc, line 888 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Kstw4bTQF_VIp8KQEG_:-Kstw4bTQF_VIp8KQEGa:bvazx6a) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L888)):*
> ```cpp
> 
>   // Color image.
>   Value<ImageRgba8U> image_color(kWidth, kHeight);
> ```

BTW, possible `const`s:
```
  const Value<ImageRgba8U> image_color(kWidth, kHeight);
  const auto* const zoh_color =
```
Ditto for the other two cases below.

---

*[drake/systems/sensors/rgbd_camera.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuCSr8LW9oZgHtAuB:-KstuCSsqRqM8k5wVqmW:bj733d4) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.h#L299)):*
> ```objc
> 
>  private:
>   RgbdCamera* camera_{};
> ```

BTW, we can have:
```c++
  RgbdCamera* const camera_{};
  const double period_{};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-:-KstwmCeXmPTnD-Gw47N:bdon8xb)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/BUILD, line 332 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Ksts2lk2gkkcsOZcJHS:-Ksz8ZuS6iiK-4fBkZWN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/BUILD#L332)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, it seems that we don't need `glob()` here. The following is sufficient:

```
    srcs = [
        "test/models/box.sdf",
        "test/models/cylinder.sdf",
        "test/models/mesh_box.sdf",
        "test/models/meshes/box.obj",
        "test/models/meshes/box.png",
        "test/models/multiple_visuals.sdf",
        "test/models/nothing.sdf",
        "test/models/sphere.sdf",
        "test/models/three_boxes.sdf",
    ],
```
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-Ksz6r2zsHIJjDPYBlVz:bwmdsoa) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
BTW Given that this is a POD, is that still necessary?
Per Drake's exceptions:
http://drake.mit.edu/code_style_guide.html#c-style

> That occurs in pass-by-value parameter declarations, where const int i and int i mean the same thing

(Though FTR, it does have a difference, in that it can be modified...)

---

*[drake/systems/sensors/rgbd_camera.cc, line 888 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-Kstw4bTQF_VIp8KQEG_:-Ksz8_pbpSLOg9ySmxLA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L888)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, possible `const`s:
```
  const Value<ImageRgba8U> image_color(kWidth, kHeight);
  const auto* const zoh_color =
```
Ditto for the other two cases below.
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_camera.h, line 299 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuCSr8LW9oZgHtAuB:-Ksz8aVT-Iy6EmF3wox9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.h#L299)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, we can have:
```c++
  RgbdCamera* const camera_{};
  const double period_{};
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-KszqvcgyqYg3Y2_r2D6:b9dnqst) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Given that this is a POD, is that still necessary?
Per Drake's exceptions:
http://drake.mit.edu/code_style_guide.html#c-style

> That occurs in pass-by-value parameter declarations, where const int i and int i mean the same thing

(Though FTR, it does have a difference, in that it can be modified...)
</blockquote></details>

AFAIK, the guideline is applied to the 'declarations' (i.e. `.h`) but not to the definition (`.cc`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-KszrJ52P5nlI9kTUhU6:br5to3x) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

AFAIK, the guideline is applied to the 'declarations' (i.e. `.h`) but not to the definition (`.cc`).
</blockquote></details>

If the CI failure is real and you need to push another commit, feel free to handle this one. Otherwise, I'm fine with as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942)*

**Comment by EricCousineau-TRI** [comment]
I believe the CI failure was just a flake; will re-test.

@drake-jenkins-bot linux-xenial-gcc-ninja-experimental

BTW, could you point an example in Drake using `const` in the definition but not the declaration for a POD?
If it's useful, I think we should update our style guide to at least suggest it, and perhaps provide a small example.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please.

(Trying one more time.)

**Comment by EricCousineau-TRI** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-KtEm9a3TzNnWI275hTg:b-obo8yy) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

If the CI failure is real and you need to push another commit, feel free to handle this one. Otherwise, I'm fine with as it is.
</blockquote></details>

BTW Will keep it as-is for now, but if you have a chance, could you point me to a usage like this within the Drake source code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/sensors/rgbd_camera.cc, line 879 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6942#-KstuiTs1q9SRCaGJuML:-KtH0cZn2Z__fEpozDmj:b-33px4s) ([raw file](https://github.com/robotlocomotion/drake/blob/354e586d6d008fb1698ce7a95d843ee2188bc07d/drake/systems/sensors/rgbd_camera.cc#L879)):*
I've been doing this so there are many cases in `common` and `solvers` directories. I've found that there are many cases in `automotive/maliput`. For example, see https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/maliput/monolane/arc_lane.cc#L68-L69 . I didn't spend much time in the search though.

FYI, in [our coding style](http://drake.mit.edu/code_style_guide.html), it says:

> You may add `const` to such parameter declarations in the function **definition**, where it does indicate that the implementation will not modify its own copy of the parameter value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6942)*

**Pull request merged**
