### PR TITLE
Fix IBEX on ARM

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Adjust IBEX build options to only enable SSE on x86_64 platforms. Re-enable IBEX (and dReal) on macOS M1.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17150)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please.

**Comment by jwnimmer-tri** [comment]
The challenge with IBEX/dReal for M1 is not whether or not it compiles, but whether the interval arithmetic library it's using is sound given the ARM64 floating-point instruction semantics along with the compiler's allow behaviors.  The SSE filib back-end was specifically tuned to maintain soundness even in the presence of C++'s `double` semantics.  It's not clear to me whether or not the General filib back-end is sound when run on ARM64.

**Comment by mwoehlke-kitware** [comment]
OTOH, at least it *does* compile. Without this patch, the build fails because it's trying to build IBEX tests when IBEX is disabled.

**Comment by jwnimmer-tri** [comment]
(Maybe the TODO would be better placed in the rcfile where we disable dreal, rather than in the `package.BUILD.bazel`?)

**Comment by mwoehlke-kitware** [comment]
> fix the test to be non-compiled as well

As I recall, I tried that several months back with no success; the only way I was able to stop the tests from trying to build was to excise them entirely.

> land the `package.BUILD.bazel` change here but not land the rcfile change yet.

I think that would have the same problem? The tests fail not because IBEX is broken, but because it wasn't built at all (which is expected with `NO_DREAL=1`). The first option seems like the correct approach if we can't just fix IBEX, but as noted, I never got it to work.

FYI:
```
ERROR: /Users/matthew.woehlke/drake/solvers/BUILD.bazel:1373:20: Compiling solvers/test/ibex_converter_test.cc failed: (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 165 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
solvers/test/ibex_converter_test.cc:1:10: fatal error: 'drake/solvers/ibex_converter.h' file not found
#include "drake/solvers/ibex_converter.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

IIRC, there are two tests in that directory that have problems, and previous attempts to disable the tests used tags. Perhaps we need instead something like:
```
    copts = select({
        "//conditions:default": [
            "-DDRAKE_IBEX_SOLVER_TEST_HAS_IBEX=1",
        ],
        "//tools:no_dreal": [
        ],
    }),
```

**Comment by jwnimmer-tri** [comment]
Okay, I should be able to reproduce that on Linux (by disabling dReal and then building).  I'll propose a patch (likely in a separate PR).  In any case, #17009 is _not_ a priority on the project board ("To do"), you there is no need for you to keep spending any time on this until the other, more highly-ranked cards on the board have been completed.

**Comment by jwnimmer-tri** [comment]
On Ubuntu locally, doing `bazel test //solvers/... --define=NO_REAL=ON` passes for me.  I think #17164 resolved the build problem, so this PR can be closed now?

**Comment by mwoehlke-kitware** [comment]
> this PR can be closed now?

I guess that depends on whether the criteria is "the M1 build does not fail due to IBEX" vs. "IBEX *works* on M1". I believe we've achieved the former. AFAIK we have not achieved the latter?

**Comment by jwnimmer-tri** [comment]
> I guess that depends on whether the criteria is "the M1 build does not fail due to IBEX" vs. "IBEX works on M1". I believe we've achieved the former.  AFAIK we have not achieved the latter?

Correct on both counts.

However, #17009 is still not a priority on the project board (and never was), and this PR is not ready to merge at the moment anyway due to https://github.com/RobotLocomotion/drake/pull/17150#issuecomment-1122919461.

Once we have #16380 done (so that we have CI) and once we've re-prioritized #17009 (so that this topic becomes relevant again) and once we've fixed all of the _other_ problems first (so that M1 CI is passing before we try to re-enable features), _then_ we can revisit turning on IBEX again, at which point someone can do the homework about the interval arithmetic correctness, and only then can we can revisit this commit.  Given that very long sequence of prerequisites, I don't see value in keeping the PR open.  It will be easy to retrieve the commit later for re-submission anytime we want it.

**Pull request closed without merging**
