### PR TITLE
Updates @system doxygen tag to use yaml; use it in body doxygen and sphinx

### PR DESCRIPTION
**Pull request by RussTedrake**
First 3/4 of #12590

This provides a new @system @endsystem tag; previous definitions of @system{ } still work (for backwards compatibility).  I have only updated a handful of the @system tags so far... i didn't want to edit too many before my reviewers have a chance to critique the format.

zap unused mcode.sty

image

cc @jpsaenz

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13642)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[doc/mk_system_doc.py, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/13642#-MBeeUJhEzEHthWBaxoq:-MBeeUJhEzEHthWBaxor:b-o7o274) ([raw file](https://github.com/robotlocomotion/drake/blob/3a346540a2f53f676f8f847733801c8eb2814e09/doc/mk_system_doc.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

nit `mk_` in the filename runs afoul of the "Don't abbreviate by omitting interior letters" rule from GSG.

**Comment by sherm1** [comment]
Thanks, I'm able to generate doxygen successfully now.

Can you explain what's going on with the new Python Yaml syntax in the .py files? I see three different labels for it here: "System YAML:", "System YAML", and "SystemYAML". I don't see where that is being processed and wonder what's happening with these. I was expecting to see @system / @endsystem tags there and formatted output.

**Comment by ToffeeAlbina-TRI** [comment]
@RussTedrake should this be closed?  If not, what's left to do?

**Comment by RussTedrake** [comment]
@ToffeeAlbina-TRI  -- I assume you mean the corresponding issue (this one is the PR)?  This fixes the way people create the system tag in c++ code (for documentation in c++ and python).  We will need to do it for systems *authored* in python.

**Comment by jamiesnape** [comment]
This one (the PR) is marked as "in progress" on the project board, so you probably want to move it to a different column or remove it from the board?

**Pull request merged**
