### PR TITLE
[tools] Port tests to use runfiles properly

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In Bazel 8, we can't just assume runfiles are in the cwd with well-known names.

Towards #22182.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22186)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22186#-:-OBlxtbj4OwcVbQMHpTO:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/lint/buildifier.py` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22186#-OBlxfRo-1MFbu_LNGP4:-OBlxfRo-1MFbu_LNGP5:busyena) ([raw file](https://github.com/RobotLocomotion/drake/blob/44b86bfb9d258dc237ed36b54fbae053627542ca/tools/lint/buildifier.py#L24)):*
> ```Python
>     """Returns a list starting with the buildifier executable, followed by any
>     required default arguments."""
>     manifest = runfiles.Create()
> ```

BTW, is `runfiles.Create()` a new functionality from Bazel? This looks a lot cleaning than the `find_data` script. Wonder why we don't use it before.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22186#-:-OBm-38P6TQSDIBOs7yc:b-1krawd)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`tools/lint/buildifier.py` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22186#-OBlxfRo-1MFbu_LNGP4:-OBlyqM25TH7njgX8m9n:bk5ya7k) ([raw file](https://github.com/RobotLocomotion/drake/blob/44b86bfb9d258dc237ed36b54fbae053627542ca/tools/lint/buildifier.py#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is `runfiles.Create()` a new functionality from Bazel? This looks a lot cleaning than the `find_data` script. Wonder why we don't use it before.
</blockquote></details>

I suppose it is "new" relative to when find_data was originally written in 2017, but it has been around for 5 years (#10659) or probably even earlier.  This buildifier wrapper some of the oldest code in Drake, and just never got revisited after we learned about the Rlocation function offered by Bazel.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22186#-:-OC-s3iS2b8qWQAijH5Z:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
