### PR TITLE
Fix various whitespace related lint errors

### PR DESCRIPTION
**Pull request by jamiesnape**

### CODE REVIEW

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
@RussTedrake PTAL.

**Comment by RussTedrake** [comment]
Looks fine.  Why does it say that it is out of date?

**Comment by jamiesnape** [comment]
The travis-ci fix was merged since the build.

**Comment by RussTedrake** [comment]
Ok.

**Pull request merged**
