### PR TITLE
[workspace] Upgrade curl_internal to latest release 7.88.1

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #18914.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18929)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18929#-:-NPcBFzNC3WVFRkj-ccu:b9krqcj)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Comment by svenevs** [comment]
FYI `mac-arm` jobs are disabled.  If this needs a mac job, the `mac-x86` jobs (non-beta) are the only ones available for the day until after the orka update.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18929)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/curl_internal/package.BUILD.bazel` line 120 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18929#-NPcaLCnEdZSYfH6wn9E:-NPcaLCo66ZIV-FnpejE:b-n5z5an) ([raw file](https://github.com/RobotLocomotion/drake/blob/1d74baa84b47499199aca3a87b196c6049f50462/tools/workspace/curl_internal/package.BUILD.bazel#L120)):*
> ```
>     "lib/vauth/digest.c",
>     "lib/vauth/vauth.c",
>     "lib/vquic/vquic.c",
> ```

FYI, curious, AFAIK the upgrade did not report that this source was missing. Any idea why?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18929)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/curl_internal/package.BUILD.bazel` line 120 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18929#-NPcaLCnEdZSYfH6wn9E:-NPcfH_hBjvtPceki1Zg:b3bkyls) ([raw file](https://github.com/RobotLocomotion/drake/blob/1d74baa84b47499199aca3a87b196c6049f50462/tools/workspace/curl_internal/package.BUILD.bazel#L120)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

FYI, curious, AFAIK the upgrade did not report that this source was missing. Any idea why?
</blockquote></details>

See the glob_include on line 154.  Only sources in the root directory are cross-checked, not sub-directories.  The stuff in the subdirs is _mostly_ unused for our use case.

**Pull request merged**
