### PR TITLE
[planning] Revise CollisionChecker parallel edge checks

### PR DESCRIPTION
**Pull request by calderpg-tri**
From discussion with @tomstewart-woven and @aochiai, `CollisionChecker`'s parallel edge checks can be improved by using the range-based parallel-for loops rather than the naive index-based versions. Using the range-based loops means less work is performed once a colliding configuration is found, since it allows the entire rest of a thread's range to be skipped.

Also contains two other revisions:
- `MeasureEdgeCollisionFreeParallel` now uses an implementation of the behavior of `std::atomic<T>::fetch_min` instead of separate `std:atomic<double>` + `std::mutex`.
- `CheckEdgeCollisionFreeParallel` now special-cases the `q1` check so that it is performed before parallel dispatch.

+@jwnimmer-tri for review, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I don't have a lot of free time these days.  Maybe the users who are interested in this feature would like to feature-review it?

**Comment by tomstewart-woven** [comment]
@jwnimmer-tri I'm happy to feature-review this if that's alright with you

**Comment by jwnimmer-tri** [comment]
Thank you!

**Comment by calderpg-tri** [comment]
Thanks!

**Review by tomstewart-woven — COMMENTED** [review]
Nice work! I left one small suggestion but otherwise this LGTM

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-:-O0mUmSy5tHuXGz1dC0J:bg3fn4m)* status: 2 unresolved discussions, LGTM missing from assignee tomstewart-woven, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri)

___
*[`planning/collision_checker.cc` line 813 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-O0mV0Xp8CZ1xw1-3lQ3:-O0mV0Xp8CZ1xw1-3lQ4:b-evjqpf) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db171f1f6f232ddde7f3651c88a518b8aa5ac93/planning/collision_checker.cc#L813)):*
> ```cpp
> }
> 
> EdgeMeasure CollisionChecker::MeasureEdgeCollisionFreeParallel(
> ```

Not for this PR but in reading the documentation for this function I noticed a small typo here: https://github.com/RobotLocomotion/drake/blob/8780ea075f80f2a8235b17a15f034cdf1931e434/planning/edge_measure.h#L22

I guess that should read "from q1 to qα"?
___
*[`planning/collision_checker.cc` line 853 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-O0mUP7H0ReGREfDHfYC:-O0mUP7H0ReGREfDHfYD:b-dcc1k5) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db171f1f6f232ddde7f3651c88a518b8aa5ac93/planning/collision_checker.cc#L853)):*
> ```cpp
>             // fetch_min once available.
>             double stored_alpha = alpha.load();
>             while (possible_alpha < stored_alpha) {
> ```

Can I suggest moving this `fetch_min` implementation into a separate function? I think that'd improve the readability of this function and easier to replace when C++26 comes along

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645)* status: 2 unresolved discussions, LGTM missing from assignee tomstewart-woven, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`planning/collision_checker.cc` line 813 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-O0mV0Xp8CZ1xw1-3lQ3:-O0op7pR72Cl6rKMIzBL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db171f1f6f232ddde7f3651c88a518b8aa5ac93/planning/collision_checker.cc#L813)):*
<details><summary><i>Previously, tomstewart-woven wrote…</i></summary><blockquote>

Not for this PR but in reading the documentation for this function I noticed a small typo here: https://github.com/RobotLocomotion/drake/blob/8780ea075f80f2a8235b17a15f034cdf1931e434/planning/edge_measure.h#L22

I guess that should read "from q1 to qα"?
</blockquote></details>

Done.
___
*[`planning/collision_checker.cc` line 853 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-O0mUP7H0ReGREfDHfYC:-O0oT0DbD6KDD6QU1TUe:b-x6zzyd) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db171f1f6f232ddde7f3651c88a518b8aa5ac93/planning/collision_checker.cc#L853)):*
<details><summary><i>Previously, tomstewart-woven wrote…</i></summary><blockquote>

Can I suggest moving this `fetch_min` implementation into a separate function? I think that'd improve the readability of this function and easier to replace when C++26 comes along
</blockquote></details>

I've moved it to a lambda to be a bit clearer, but since this is a bit of a simplification of the intended behavior of `fetch_min` specific to this case, I don't think moving it to a completely separate function would be that useful.

**Comment by tomstewart-woven** [comment]
:lgtm: thanks for the changes!

**Comment by tomstewart-woven** [comment]
*[`planning/collision_checker.cc` line 853 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-O0mUP7H0ReGREfDHfYC:-O1L0FFMEMwEL1EFnLIQ:b-sb4ovl) ([raw file](https://github.com/RobotLocomotion/drake/blob/7db171f1f6f232ddde7f3651c88a518b8aa5ac93/planning/collision_checker.cc#L853)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

I've moved it to a lambda to be a bit clearer, but since this is a bit of a simplification of the intended behavior of `fetch_min` specific to this case, I don't think moving it to a completely separate function would be that useful.
</blockquote></details>

Fair enough, a lambda works too :thumbsup:

**Review by calderpg-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review (or delegate), thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-:-O1MqKwf-y6JuCRJmZEK:b-4iduxa)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

To make sure I fully understand this, the savings is based on the fact that the remaining, superfluous interations that would test the shared semaphore value and abort no longer have to read and test? 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-:-O1NlTClBpcVKAvq3O-l:bldwb8h)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
> the savings is based on the fact that the remaining, superfluous interations that would test the shared semaphore value and abort no longer have to read and test

Yes

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-:-O1NmhMiBbMWvEcY7NUh:bkkbd78)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Dismissed @tomstewart-woven from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm not sure if you mean to squash or curate. I leave it up to you.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21645#-:-O1OFusS7FWrTszkq6tv:b-u09vky)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Pull request merged**
