### PR TITLE
Remove LittleDog example

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This depends on parts of Drake's MATLAB support that are going to be replaced, so we don't want this under CI anymore.  We can add it back later if we choose to forward-port it.  Its code (and models) remain at https://github.com/RobotLocomotion/LittleDog/.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6231)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.  I'll wait to assign feature / platform review until after that.

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6231#-:-KldCEbZoUKfqMpq_ZeC:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware for feature review of the CMake change, please.

**Comment by mwoehlke-kitware** [comment]
:lgtm: ...and can't say I'm sorry to see that odd "external examples" stuff go away... :smile:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6231#-:-KldJJISzop-QYRDrhK2:b-xkxi3e)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge)
+@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6231#-:-Klt_43cKXfgiAKtW8cs:bnfp4nl)*

**Pull request merged**
