### PR TITLE
common: Remove all dynamic_casts from Value<T>

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hopefully this speeds things up.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10649)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review please (having already looked, per f2f).

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review please (no hurry).

**Comment by jwnimmer-tri** [comment]
The implementation of `typeid()` is [here, for libstdc++](https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libstdc%2B%2B-v3/libsupc%2B%2B/typeinfo#L120-L125).  It's either just a pointer comparison (which is what happens in our C++ code), or sometimes falls back to the strcmp depending on how symbols get loaded (e.g., in pydrake).  Usually the dynamic_cast implementation would be doing the same thing (or worse, with fallbacks for type lattices).  We'll anyway wait for Alejandro's benckmarks, but I'll see if I can fire up godbolt as well to convince you.  Stay tuned (probably tomorrow).

**Comment by jwnimmer-tri** [comment]
The new object code looks pretty solid to me: https://godbolt.org/z/uB8vyK.

The FastCalcThing has a cmp/je with a `this`-relative pointer (the `static_type_info_`) and a `typeinfo for double`-relative pointer (a relocation for the `typeid(T)`), with the fallback to strcmp.

The SlowCalcThing calls a `__dynamic_cast` function, which does a 20-ish instructions prologue and _then_ crawls off info a `__cxxabiv1::__si_class_type_info::__do_dyncast` thing.

**Comment by jwnimmer-tri** [comment]
So given that I think my bid would be _only_ to have `get_value()` for now.  If we really need to avoid the strcmp in release builds, we could add `unchecked_get_value()` in the future and use it in a few places where it really mattered.

**Comment by sherm1** [comment]
Thanks for doing that Jeremy. It does make feel a little better. That typeid implementation looks like it _ought_ to be fast most of the time. However, it has an ugly worst case, and a mysterious middle case:
```asm
  mov rdi, qword ptr [rip + typeinfo for double+8]
  mov rsi, qword ptr [rax + 8]
  cmp rdi, rsi
  je .LBB0_6 // return
  cmp byte ptr [rdi], 42  // wtf?
  je .LBB0_3 // error
  call strcmp
  test eax, eax
  jne .LBB0_3 // error
```
I think that says: "if the character pointers don't match, then if the one for T points to an `*` then fail, otherwise compare the mangled type names"? I guess a mangled name beginning with `*` means something -- maybe an anonymous type that can't match anything else?

I can see that for `double` the compiler is likely to have used the same typeid() address for both, but is that true for types we commonly use? Would BasicVector or a BasicVector subtype fall back to the strcmp()? In a matching case that could be _very_ expensive since mangled names tend to be long.

With the strcmp-vs-dynamic_cast lurking there, and (mis)quoting your advice back to you, I think we need to have a performance benchmark that represents what we're interested in to make sure this is a good fix. A reasonable alternative to that would be to provide the unchecked versions now so that we can compare in actual use the cost of the typeids vs. doing no checks at all (@amcastro-tri has a test that should be able to measure this).

**Comment by jwnimmer-tri** [comment]
I was satisfied with not understanding the middle case.  I didn't go digging what typenames start with `*`, but yes I figured it was something internal.

> I can see that for `double` the compiler is likely to have used the same typeid() address for both, but is that true for types we commonly use?

Yes.  In my testing, the only place that fell back to the strcmp was in pydrake.  I don't mind adding an `unchecked_get_value` here for completeness if that's what it takes, but I would reject the idea that it be widely used (e.g., Port::Eval should not offer sugar that skips the check).  Users should basically never know about it.  Though I could see using `unchecked_get_value` locally in some framework guts, e.g., if we had already checked the type a few lines higher and wanted to avoid the re-check.

> In a matching case that could be very expensive since mangled names tend to be long.

Maybe?  We probably just have different definitions for "very".

> ... to make sure this is a good fix.

My bid is that this is better than dynamic_cast, and that's _all_ we should assess before merging.  Whether we need additional speed beyond this does not (to me) play into whether this PR's conceptual simplification ("use static typing for AbstractValue") should be prevented from reaching master.

**Comment by jwnimmer-tri** [comment]
FWIW If we really care, we could optimize it to be a single 64-bit integer comparison, using one of the constexpr typeid libraries that provide a hash(T).

**Comment by sherm1** [comment]
> My bid is that this is better than dynamic_cast, and that's _all_ we should assess before merging.

I agree that the use of typeid is an improvement over dynamic_cast. But the PR also changes the AbstractValue API contract to eliminate the "possibly unchecked" methods that were there before. I don't want to promise validation there until we know we can afford to do Release checking, and we don't have measurements to establish that yet.

> we could optimize it to be a single 64-bit integer comparison, using one of the constexpr typeid libraries that provide a hash(T)

Unless there's a unique-hash guarantee, this would be optimized to detect mismatches (exceedingly rare for us) while for matches I think we'd have to execute the existing code to ensure the match wasn't spurious?

So I'm happy with this change if it doesn't yet alter the contract for the unchecked methods or threaten deprecation of the "OrThrow" methods. I think it is premature to make that change until we know we can't benefit from unchecked access (I'm thinking about inlining as well as the cost of checking).

**Comment by jwnimmer-tri** [comment]
The reason I wasn't concerned about that yet is because the unchecked methods have terrible names now.  They should use snake_case to convey that they are fast, and should use some_kind_of_really_scary_long_name to dissuade users from using them as the default choice.  So, when we _actually_ deprecate the unchecked names, at _that_ point we can decide whether or not they receive a non-deprecated replacement, and what it's new name is.

Anyway, I think we're only arguing about the promises in the TODOs at this point.  I guess I'll try to rework them to be more nebulous in order to get this merged.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
I've confirmed that the ctti hash checking boils down to be very small:
```asm
drake::FastCalcThing(drake::AbstractValue const&):
  movabs rax, 1132292092900833548
  cmp QWORD PTR [rdi+8], rax
  jne .L8
  lea rax, [rdi+16]
  ret
```

https://godbolt.org/z/Yirklc

**Comment by sherm1** [comment]
I hadn't seen `ctti` before -- it's like NiceTypeName on steroids!
A few comments:
- It's not clear to me how ctti ensures that the hash is unique. I didn't see any mention of that scanning the docs. Does it just play the odds and assume every type hashes differently?
- In Simbody I found about a 20% _overall_ speed difference depending on whether access to concrete-typed objects in the cache was inlined or not. A method like FastCalcThing() above is unlikely to inline because it is too large (due to the logic_error code in the failed case). Some engineering would be required to ensure that basic, successful access gets inlined.

**Comment by jwnimmer-tri** [comment]
It uses fnv1a hash algorithm.  Pretty good but as with any hash there can be collisions.  My proposal would be to use the hash as an always-enabled, best-effort check for _mismatches_ that would catch 99+% of user mistakes (using the single cmp + je like above).  I've started to draft that in #10678.

The inline question is a fair point.  I wonder if #10678 will provide an answer there or not.

**Comment by sherm1** [comment]
Another question is whether this is solving a problem we actually have. The typeid checks you put in are likely to be an improvement over dynamic_cast, for which we did have a measured cost (5%-ish for one particular use I think). AFAIK we don't yet have any measured problem with the typeid check installed.

**Comment by jwnimmer-tri** [comment]
That's a good topic.  I am not sure if we have a performance problem.  The problem we _do_ have is that there are two of every AbstractValue method (Foo, FooOrThrow).  I want there to be only one version, which is right for all use cases.  Upthread, it sounded like you would be unwilling to accept a design where `typeinfo == typeinfo` was in the hot path for `get_value`, because it falls back to strcmp.  By using ctti, there is no more strcmp so perhaps it's suitable for the one-and-only get_value path -- fast (assuming it get inlined?) to satisfy you, and safe (>99.99%) to satisfy me (there is no "unchecked" flavor).

**Comment by jwnimmer-tri** [comment]
=> #10678 for further discussion

**Comment by amcastro-tri** [comment]
FYI. I merged my benchmarks branch with master today. I was not able to measure any impact of caching on the computation cost of ID or mass matrix anymore, yaii!

**Comment by sherm1** [comment]
Woo hoo! Thanks for the fix Jeremy and the confirmation Alejandro!

**Pull request merged**
