### PR TITLE
Fixed bug in instructions on how to enable long running unit tests.

### PR DESCRIPTION
**Pull request by liangfok**
I tested this on my OS X machine using Ninja.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2575)

### CODE REVIEW

**Comment by liangfok** [comment]
Since tomorrow is a Friday and this is such a small change, +@ggould-tri for feature + platform reviews.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2575#-:-KKRRMyUthYp9hFQdVTW:-1318041769)*

**Comment by liangfok** [comment]
CI OS X Build server failed with the "Slave went offline during the build" error:
https://drake-jenkins.csail.mit.edu/job/experimental/2117/compiler=clang,label=mac/

@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2119/ and is thus ready for review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2575#-:-KKT86bBZyy555t8n4WN:-2018233357)*

**Comment by ggould-tri** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2575#-:-KKT_Lwqxpfq5uo2mgf2:980077423)*

**Pull request merged**
