### PR TITLE
Factor pkg_config_repository calls into bzl helpers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7738)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per schedule, please.

I will test on macOS CI prior to merging, after #7733 lands first.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7738#-L2aurgGeU7hMLweBjGV:-L2aurgGeU7hMLweBjGW:b-jxl19g) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ec4af7e32c15cab613c711d2cc2786b6fa5d/WORKSPACE#L47)):*
> ```Python
> 
> # This local repository imports the protobuf build rules for Bazel (based on
> # the upstream protobuf.bzl build rules); in constrast, the protobuf runtime is
> ```

I think this one (`@libprotobuf`) and the one below (`@com_google_protobuf`) were swapped by accident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7738#-:-L2av5cmo_1IKp2NNaeZ:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[WORKSPACE, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7738#-L2aurgGeU7hMLweBjGV:-L2avJ30fL2Z5WCbmv7Z:bojuc9l) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ec4af7e32c15cab613c711d2cc2786b6fa5d/WORKSPACE#L47)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think this one (`@libprotobuf`) and the one below (`@com_google_protobuf`) were swapped by accident?
</blockquote></details>

Never mind. I just got confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7738)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7738#-L2aurgGeU7hMLweBjGV:-L2azUvhTDqW6EP9MIAr:bl60z03) ([raw file](https://github.com/robotlocomotion/drake/blob/d352ec4af7e32c15cab613c711d2cc2786b6fa5d/WORKSPACE#L47)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Never mind. I just got confused.
</blockquote></details>

OK Yeah, diff tools really struggle with PRs like this (I have a few more in the queue that are similarly scattered.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7738)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Pull request merged**
