### PR TITLE
Remove deprecated 2021-11 geometry legacy collision filters

### PR DESCRIPTION
**Pull request by joemasterjohn**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@seancurtis-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029#-:-MnW4MDK4oSSiErJJtmk:b-qb6q7i)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
It appears the `geometry_py_scenegraph.cc` needs a bit more scrubbing for CI to be happy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029#-:-MnW7lTnDeHLEbi5XUdm:b-ei5py2)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py_scene_graph.cc, line 245 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16029#-MnW7vTf6Z4vlNutYHZH:-MnW7vTf6Z4vlNutYHZI:b-qq7vy9) ([raw file](https://github.com/robotlocomotion/drake/blob/26aa2d98f9a907ceda53a1c64d4fb819333c9ebe/bindings/pydrake/geometry_py_scene_graph.cc#L245)):*
> ```cpp
>             overload_cast_explicit<CollisionFilterManager>(
>                 &Class::collision_filter_manager),
>             cls_doc.collision_filter_manager.doc_0args);
> ```

nit: This semi-colon seems to be the cause of the offense.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: once the semi-colon is removed.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029#-:-MnW8mTwDejsi_5mOc8_:b-10w3h9)* status: 1 unresolved discussion (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16029)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py_scene_graph.cc, line 245 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16029#-MnW7vTf6Z4vlNutYHZH:-MnWB71k-Y0GqBOzDfzX:balyhv7) ([raw file](https://github.com/robotlocomotion/drake/blob/26aa2d98f9a907ceda53a1c64d4fb819333c9ebe/bindings/pydrake/geometry_py_scene_graph.cc#L245)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This semi-colon seems to be the cause of the offense.
</blockquote></details>

:facepalm: that one slipped by me. Done.

**Pull request merged**
