### PR TITLE
doc: Relocate bindings/pydrake/doc to doc/pydrake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We want all of the website generation to live inside the doc folder.

Towards #14803.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14806)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI can I get your overall sign-off on this move?  If you are curious to do full feature review that's fine too, but a high-level approval is find too.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: high- and low-level! Nice and simple, scope is clear given issue.

I'm also fine w/ being a single reviewer - up to you!

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14806#-:-MWPcZuk7Pn5PPzxgWmQ:b9ryxnm)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

I just read through the diffs to confirm, and yes I think I'm okay with single reviewer.  I'll let CI chew on this before we merge.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14806)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14806#-MWPitTfAxqrQqK5qnSz:-MWPitTfAxqrQqK5qnT-:b-uqu0s8) (no related file):*
Working: Will preview locally just to ensure that the plugin still activates (e.g. if it gets lost but in such a way that doesn't trigger an error in the test?)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14806)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14806#-MWPitTfAxqrQqK5qnSz:-MWPjSmS581I2Z85NhVx:bteo2yq) (no related file):*
OK Confirmed locally: `{output_dir}/pydrake.multibody.plant.html#pydrake.multibody.plant.ContactResults`

> 

---

**Pull request merged**
