### PR TITLE
Add pydrake bindings for model directives.

### PR DESCRIPTION
**Pull request by ggould-tri**
* Weld error support omitted for simplicity.
* Follow-up to #14038
* Completes #13282

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14144)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@ericcousineau-tri 
Follow-up to previous PR:  Manual port of python bindings.
I am not a bindings expert and expect you will have plenty of objections here.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14144#-:-MIPPR2X8MX8CFx3OUoK:bhwgz4r)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with a couple of nits - thanks!

I'm fine with serving as both feature and platform

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14144#-:-MIPViUe0RA2rr6nDFAf:bdn6ghu)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @ggould-tri)

___
*[bindings/pydrake/multibody/parsing_py.cc, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIPSrXrAA_kxOjwe-ZM:-MIPSrXrAA_kxOjwe-ZN:bu83d7q) ([raw file](https://github.com/robotlocomotion/drake/blob/1af8df6737cc5dc38e469d87a0a6beae967e3779/bindings/pydrake/multibody/parsing_py.cc#L91)):*
> ```cpp
>         py::arg("directives"), py::arg("plant"), py::arg("parser"),
>         (std::string(parsing_doc.ProcessModelDirectives.doc) +
>          "\nNOTE:  pydrake does not support `ModelWeldErrorFunction`.")
> ```

nit This should be compatible with Sphinx Napoleon:
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections

See example for a warning directive used in Drake here:
https://github.com/RobotLocomotion/drake/blob/ae0623875f556a65e5b6915224373a31a9e305f9/bindings/pydrake/systems/lcm_py.cc#L72-L80

See GSG styling (though not very comprehensive for directives...):
https://drake.mit.edu/styleguide/pyguide.html

(Will make a PR to try and link that in)
___
*[multibody/parsing/BUILD.bazel, line 272 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIPVMYb4Upvdl1L3Ovi:-MIPVMYcBkDc-kGlQPGx:b-azbmeu) ([raw file](https://github.com/robotlocomotion/drake/blob/1af8df6737cc5dc38e469d87a0a6beae967e3779/multibody/parsing/BUILD.bazel#L272)):*
> ```Starlark
>     data = glob(["test/process_model_directives_test/**"]),
>     visibility = [
>         "//visibility:public",
> ```

nit `//visibility:public` means other downstream consumer (e.g. Anzu, etc) can use this.

Consider the following options:
- `//:__subpackages__` - Drake only (slightly more conservative)
- `//bindings/pydrake:__subpackages__` - Bindings only (more conservative)
- `//bindings/pydrake:multibody:__pkg__` - Multibody bindings only (most conservative).

**Review by ggould-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14144#-:-MIPWyxnEYyViwyY-JW8:b3dcro0)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/multibody/parsing_py.cc, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIPVqyW6DdEobF7bqpg:-MIPZld87drChPLiHRvF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1af8df6737cc5dc38e469d87a0a6beae967e3779/bindings/pydrake/multibody/parsing_py.cc#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

All of these bindings should have docstrings available.

Can you add them in everywhere?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/parsing_py.cc, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIPW8MZ8WK-QF25DBKC:-MIPZmKS3HG2vUZngk__:bxslgzw) ([raw file](https://github.com/robotlocomotion/drake/blob/1af8df6737cc5dc38e469d87a0a6beae967e3779/bindings/pydrake/multibody/parsing_py.cc#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Per above defect, it'll be simpler if you just do a per-class alias:
Please consider aliasing using the provided template:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeDoc

Currently, you're breaking existing precedents (no alias or fully aliasing), I believe.
</blockquote></details>

Not quite sure what you mean here, but I think I have done it now?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14144)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

___
*[bindings/pydrake/multibody/parsing_py.cc, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIPW8MZ8WK-QF25DBKC:-MIP_qdH-SRfw3oHLEzb:b-xu9y5i) ([raw file](https://github.com/robotlocomotion/drake/blob/1af8df6737cc5dc38e469d87a0a6beae967e3779/bindings/pydrake/multibody/parsing_py.cc#L69)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Not quite sure what you mean here, but I think I have done it now?
</blockquote></details>

OK Yup - thanks!
___
*[bindings/pydrake/multibody/parsing_py.cc, line 88 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14144#-MIP_vTs3IwO0fSoDBo1:-MIP_vTs3IwO0fSoDBo2:bc1k51b) ([raw file](https://github.com/robotlocomotion/drake/blob/5b83c184f81830c75444c3bccd6b13720bec683e/bindings/pydrake/multibody/parsing_py.cc#L88)):*
> ```cpp
> 
>   constexpr char kWeldErrorDisclaimer[] = R"""(
>     Note:
> ```

BTW Not sure if this will render well with the extra whitespace (given that it's getting appended, rather than being the docstring itself), but it's not a huge deal for me atm.

**Pull request merged**
