### PR TITLE
[common] Fix hangs with MaybePauseForUser

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@RussTedrake for feature review.

Closes: #20029.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-:-NcJlI0yDu3uRN4Wc-r3:b-3vykpl)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  Thank you.  As @jwnimmer-tri says, it's a strict improvement.

I've confirmed that 
- `bazel test //common/test_utilities:maybe_pause_for_user_test` doesn't pause
- `bazel run //common/test_utilities:maybe_pause_for_user_test` doesn't pause
- `bazel-bin/common/test_utilities:maybe_pause_for_user_test` does pause
- `bazel run //common/test_utilities:maybe_pause_for_user_manual_test` does pause
- `bazel-bin/common/test_utilities:maybe_pause_for_user_manual_test` does pause

I will say, thought, that the different behaviors for `bazel run` depending on the cc_binary or cc_test is potentially confusing?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-:-NcXDE5K0jl8TuALzU7G:b-ez44t3)* status: needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
Sure, that is confusing. But as nimmer points out, we are way out over our skis depending on behavior of `cin` in test programs.

+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-:-NcXt0e09c1DMzVPpAYr:b-39lftj)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: with one question.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-:-NcYRYxE1yeezZbYBjOK:b-j6g7ls)* status: 1 unresolved discussion

___
*[`common/test_utilities/test/maybe_pause_for_user_test.cc` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-NcYRJnR32l42OHmsZN0:-NcYRJnR32l42OHmsZN1:btltsf0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef349ce483f0fe93efd53458597d53c056416e48/common/test_utilities/test/maybe_pause_for_user_test.cc#L6)):*
> ```cpp
> 
> // Manual test users should verify that:
> // - the program does not pause when invoked with "bazel-run".
> ```

The program doesn't pause when invoked with "bazel test" either. Is that intended? If so, it should be made clear.



_Code quote:_
```cpp
the program does not pause when invoked with "bazel-run"
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031)* status: 1 unresolved discussion

___
*[`common/test_utilities/test/maybe_pause_for_user_test.cc` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20031#-NcYRJnR32l42OHmsZN0:-NcYhtKq4j5TtW8RLhel:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ef349ce483f0fe93efd53458597d53c056416e48/common/test_utilities/test/maybe_pause_for_user_test.cc#L6)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The program doesn't pause when invoked with "bazel test" either. Is that intended? If so, it should be made clear.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20031)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

**Pull request merged**
