### PR TITLE
py math: Expose scalars for RotationMatrix, RollPitchYaw, RigidTransform

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards #11240
`RotationMatrix`, `RigidTransform` and `RollPitchYaw`.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11563)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/test/math_test.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSs8VJ8ofBCny4INSc:-LgTeeus-Xu8XmLuOBJ-:bukb40q) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/test/math_test.py#L228)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can I ask why only `float` here?
</blockquote></details>

Because it fails in the other two cases:
[`Expression`](https://gist.github.com/m-chaturvedi/0e517d0ef53e314745575f199a9ba1f5), [`AutoDiffXd`](https://gist.github.com/m-chaturvedi/423c38dd3ab924dbe43e2ff7143673c4)

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/math_py.cc, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSsDtkA_L2A1NVYhmz:-LgTNuo2546TNCVszlrS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/math_py.cc#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hoisting to nit: Can you add a reference to #11566 here and in `eigen_geometry_py.cc`?
</blockquote></details>

Done.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/math_py.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSqhXT4AyCYC9iEjfu:-LgTN6jV6vCsxDBTFByN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/math_py.cc#L42)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you wrap this in `namespace {`?
</blockquote></details>

Done.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/math_py.cc, line 266 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSrsiqAGx1RisErSX2:-LgTV6zT9cEXg8Jar-XY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/math_py.cc#L266)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This should really live in `DoDefinitions` to keep parity with `Class_[T]`

(This can be satisfied by hoisting everything to `DoDefinitions`.)
</blockquote></details>

Done.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/test/math_test.py, line 112 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSrIEb70W2yXbJC876:-LgTMMYU50CymMC5u7SE:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/test/math_test.py#L112)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Instead of doing `Isometry3_1`, can you just shadow the alias?
```
Isometry3 = Isometry3_[T]
```
</blockquote></details>

Done

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/test/math_test.py, line 135 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSrSmA9hmAsv5ioEX2:-LgTbYsI2slPsRwA5h9y:b-djzc15) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/test/math_test.py#L135)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can I ask why this is necessary?
</blockquote></details>

Sorry, removed it.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/test/math_test.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgSs8VJ8ofBCny4INSc:-LgTpKgVBKvDHV5k2KaL:bwb0k7c) ([raw file](https://github.com/robotlocomotion/drake/blob/b068e064fd8109208465f6e283e4b4493e43f50d/bindings/pydrake/test/math_test.py#L228)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

You can make this work by using `npc.to_float(q_I.wxyz())`.
Can you make that change here and elsewhere?

(Been meaning to change the function to permit` a` and `b` to both be non-float, but haven't done so yet...)
</blockquote></details>

OK, I made a similar change at four other places.

**Comment by m-chaturvedi** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgTr0Jt7jmZAPKPkyw-:-LgTw4M71m6Pkd8aBwY0:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per f2f, this will be the case. Raising to blocking.
</blockquote></details>

Done.

---

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/test/math_test.py, line 116 at r3](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgUutGt9gyDwz7a_x2Q:-LgYDQxyEsVn9ez-U3Lh:bnle8ss) ([raw file](https://github.com/robotlocomotion/drake/blob/1e95f59d3f63c4ee2c9c733a00b471b8cb9a5e21/bindings/pydrake/test/math_test.py#L116)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

Removed. +@EricCousineau-TRI do you agree?
</blockquote></details>

OK Yup!

**Pull request merged**
