### PR TITLE
Add a sos1 constraint using logarithmic number of binary variables

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6502)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoDm9ER9LIJys8Fxaxx:biagjkq)*

**Comment by gizatt** [comment]
Had to spend a bit convincing myself that this works for any set of codes, and I've got one suggestion for a maybe-useful-sanity-check, but otherwise looks great!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoJjK9JvkQI3LefylhH:-KoJhvL5BjwXcRyZqDhp:b-974sfq) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa3890d7707e99b9f4db041d68a3683b56f5622/drake/solvers/mixed_integer_optimization_util.cc#L55)):*
> ```cpp
>     MathematicalProgram* prog,
>     const Eigen::Ref<const VectorX<symbolic::Expression>>& lambda,
>     const Eigen::Ref<const VectorXDecisionVariable>& y,
> ```

There's an opportunity for subtle user error here if they pass a `y` that has continuous variables -- can that be checked for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoJipjp3tlNO5kr-cIU:bv23klc)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoJjK9JvkQI3LefylhH:-KoKiwC4HiWaJ7cZcaPO:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa3890d7707e99b9f4db041d68a3683b56f5622/drake/solvers/mixed_integer_optimization_util.cc#L55)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

There's an opportunity for subtle user error here if they pass a `y` that has continuous variables -- can that be checked for?
</blockquote></details>

Done. Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502)*

**Comment by gizatt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoJjK9JvkQI3LefylhH:-KoL62sK9CrujE6ClbJz:b-kj7mbl) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa3890d7707e99b9f4db041d68a3683b56f5622/drake/solvers/mixed_integer_optimization_util.cc#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Good call.
</blockquote></details>

Sweet, looks great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoL6CSp3Pi3JHr8C7uu:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoL6RaVGAHivW7OQeMu:b-vt9vbo)*

**Comment by soonho-tri** [comment]
:lgtm: (aside cosmetic minor issues)

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNVNKT4Jga6oxAC9jA:-KoNVNKT4Jga6oxAC9jB:beegc8) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.cc#L62)):*
> ```cpp
>     const Eigen::Ref<const Eigen::MatrixXi>& codes) {
>   const int num_lambda = lambda.rows();
>   int num_digits = CeilLog2(num_lambda);
> ```

BTW, nit, this can be `const int` .

---

*[drake/solvers/mixed_integer_optimization_util.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPT1VgBzcbzUQCHCW:-KoNPT1VgBzcbzUQCHCX:b4laqeu) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L15)):*
> ```objc
>  * @return The minimal integer no smaller than log₂(n).
>  */
> constexpr int CeilLog2(int n) {
> ```

BTW, this function can be fit in a line:

```c++
constexpr int CeilLog2(int n) { return n == 1 ? 0 : 1 + CeilLog2((n + 1) / 2); }
```

---

*[drake/solvers/mixed_integer_optimization_util.h, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPP_P7s0k_udAzI8f:-KoNPP_P7s0k_udAzI8g:beivvdp) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L44)):*
> ```objc
>     const std::string& binary_variable_name = "y");
> 
> /** Adds the special ordered set 2 (sos2) constraint, @see AddLogarithmicSOS2Constraint.
> ```

BTW, this line is 88-char long.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPuFYV8js810wf9dm:-KoNPuFYV8js810wf9dn:b-kqhukt) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L52)):*
> ```objc
> 
> /**
>  * Adds the special ordered set of type 1 (sos1) constraint. Namely
> ```

We need a `<pre>` tag to render this correctly in doxygen.

```
 * <pre>
 *     λ(0) + ... + λ(n-1) = 1
 *     λ(i) >= 0
 * </pre>
``` 

---

*[drake/solvers/mixed_integer_optimization_util.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNRY4jstWIZutbIEeF:-KoNRY4jstWIZutbIEeG:b-19u90i) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L67)):*
> ```objc
>  * integer M in `codes`, then only λ(M) is positive. Namely, if
>  * (y(0), ..., y(⌈log₂(n)⌉) equals to codes.row(M), then λ(M) = 1
>  * @param codes. A n x ⌈log₂(n)⌉ matrix. code.row(i) represents integer i.
> ```

BTW, nit, no `.` in `@param codes.`

---

*[drake/solvers/mixed_integer_optimization_util.h, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNUXdkQG5YPCUBVOAz:-KoNUXdkQG5YPCUBVOB-:b-otke77) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L69)):*
> ```objc
>  * @param codes. A n x ⌈log₂(n)⌉ matrix. code.row(i) represents integer i.
>  * No two rows of `codes` can be the same.
>  */
> ```

FYI, consider adding:

```
@throws std::runtime_error if @p codes has a non-binary entry (0, 1).
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoNVczIGaC9TB4iIt_e:b-nzqp8s)*

**Comment by soonho-tri** [comment]
+(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoNVqp4JKT7DRv8Ga4x:b-s794vx)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/mixed_integer_optimization_util.cc, line 62 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNVNKT4Jga6oxAC9jA:-KoNmYoNkWX1mmeesB6v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.cc#L62)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, this can be `const int` .
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPT1VgBzcbzUQCHCW:-KoNmeRk0NF1oTToPuqp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this function can be fit in a line:

```c++
constexpr int CeilLog2(int n) { return n == 1 ? 0 : 1 + CeilLog2((n + 1) / 2); }
```
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPP_P7s0k_udAzI8f:-KoNmlXQ4Sn-IM5xaTgb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L44)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this line is 88-char long.
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNPuFYV8js810wf9dm:-KoNncRNQa8hZUblmTkF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We need a `<pre>` tag to render this correctly in doxygen.

```
 * <pre>
 *     λ(0) + ... + λ(n-1) = 1
 *     λ(i) >= 0
 * </pre>
``` 
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 67 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNRY4jstWIZutbIEeF:-KoNnjsj55hYnO2O2LJe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L67)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit, no `.` in `@param codes.`
</blockquote></details>

Done.

---

*[drake/solvers/mixed_integer_optimization_util.h, line 69 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-KoNUXdkQG5YPCUBVOAz:-KoNoI1WZ-1ZHtj6iEUD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fb5eb101b72f2a8674dee9e3760f9941f94d532f/drake/solvers/mixed_integer_optimization_util.h#L69)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, consider adding:

```
@throws std::runtime_error if @p codes has a non-binary entry (0, 1).
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6502#-:-KoNyQ4CI2r546os_zyP:b-l70wzf)*

**Pull request merged**
