### PR TITLE
Add a function to merge another basis element in place.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@soonho-tri for feature review please, thaks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023#-:-MGW_pOJ1V2Wx6Kcturo:b-5b34ol)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023#-:-MGifJcbCSm8Muam-V47:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/symbolic_chebyshev_basis_element.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGi_P8GA0O6ZhvlIXeZ:-MGi_P8GA0O6ZhvlIXe_:b-dcxtco) ([raw file](https://github.com/robotlocomotion/drake/blob/8e92415ab4c9ec75236cff495aec5b932633b565/common/symbolic_chebyshev_basis_element.h#L84)):*
> ```objc
>   std::map<ChebyshevBasisElement, double> Integrate(const Variable& var) const;
> 
>   /** Merge this Chebyshev basis element with another Chebyshev basis element by
> ```

nit, META (please check the other files)
 - `Merge` => `Merges`
 - ... another Chebyshev basis element `@p other` ...
___
*[common/symbolic_polynomial_basis_element.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGifExuEtc5JscUPmGp:-MGifExuEtc5JscUPmGq:b-9j1pkd) ([raw file](https://github.com/robotlocomotion/drake/blob/8e92415ab4c9ec75236cff495aec5b932633b565/common/symbolic_polynomial_basis_element.h#L42)):*
> ```objc
>  * - bool Derived::operator<(const Derived& other) const;
>  * - std::pair<double, Derived> EvaluatePartial(const Environment& e) const;
>  *
> ```

I think we need to update this list?

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023#-:-MGimzDoEQAdj0zF0dov:b8asji7)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[common/symbolic_polynomial_basis_element.h, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGifExuEtc5JscUPmGp:-MGim_48A8AI0ob43Akt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e92415ab4c9ec75236cff495aec5b932633b565/common/symbolic_polynomial_basis_element.h#L42)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we need to update this list?
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typos

> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023#-:-MGizNN326PON1PZSYgQ:b-7vdkkg)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[common/symbolic_chebyshev_basis_element.h, line 86 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwV9j33b2eSkKIQmx:-MGiwV9j33b2eSkKIQmy:bhrsbtv) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_chebyshev_basis_element.h#L86)):*
> ```
> rasied
> ```
typo
___
*[common/symbolic_monomial_basis_element.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwgse9kFTxZ_qsbGX:-MGiwgse9kFTxZ_qsbGY:b8662ts) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_monomial_basis_element.h#L127)):*
> ```
> lement
> ```
typo
___
*[common/symbolic_polynomial_basis_element.h, line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwoih8N_m8Uz1ShHT:-MGiwoih8N_m8Uz1ShHU:bhrsbtv) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_polynomial_basis_element.h#L137)):*
> ```
> rasied
> ```
typo

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023)* status: 3 unresolved discussions (waiting on @rpoyner-tri)

___
*[common/symbolic_chebyshev_basis_element.h, line 86 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwV9j33b2eSkKIQmx:-MGj4RYr066vvpB_flDI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_chebyshev_basis_element.h#L86)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> rasied
> ```
typo
</blockquote></details>

Done.
___
*[common/symbolic_monomial_basis_element.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwgse9kFTxZ_qsbGX:-MGj4FmG7YQsa5u4fgJg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_monomial_basis_element.h#L127)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> lement
> ```
typo
</blockquote></details>

Done.
___
*[common/symbolic_polynomial_basis_element.h, line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14023#-MGiwoih8N_m8Uz1ShHT:-MGj4Lp64EaoPeTYxjB1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b665974b5ab95c6f45e8c9232ac588aef0528582/common/symbolic_polynomial_basis_element.h#L137)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> rasied
> ```
typo
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14023)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform)

**Pull request merged**
