### PR TITLE
Changes for newer ignition-rndf and ignition-math.

### PR DESCRIPTION
**Pull request by clalancette**
Here we update to a newer version of ignition-math4 and a
newer version of ignition-rndf (since they end up being
coupled).  Along with that, we fix up the ignition-rndf
build file to look substantially like the ignition-math
one for consistency.  While we are at it, we make
ignition-rndf a shared object.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7749)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Apologies, but I stomped on this to get a large PR in first; you'll need to rebase and place the changes into the new workspace layout (see tools/workspace/ignition...).

**Comment by clalancette** [comment]
> Apologies, but I stomped on this to get a large PR in first; you'll need to rebase and place the changes into the new workspace layout (see tools/workspace/ignition...).

Will do, thanks for the heads up.

**Comment by jamiesnape** [comment]
+@jamiesnape for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/ignition_rndf/package.BUILD.bazel, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-odemTU6ZxLOO5UZI:-L3-odemTU6ZxLOO5UZJ:b3zezw7) ([raw file](https://github.com/robotlocomotion/drake/blob/d29a42889cf06251d6e0d6351ffe210b41b8dba2/tools/workspace/ignition_rndf/package.BUILD.bazel#L39)):*
> ```
>         "PROJECT_NAME=ignition-rndf",
>         "PROJECT_NAME_LOWER=ignition-rndf",
>         "PROJECT_MAJOR_VERSION=0",
> ```

Can you define some constants and use them in place of hardcoding repeated and composite values?

---

*[tools/workspace/ignition_rndf/package.bzl, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-p2IsxYMEu_Pxf3sO:-L3-p2IsxYMEu_Pxf3sP:b6i076p) ([raw file](https://github.com/robotlocomotion/drake/blob/d29a42889cf06251d6e0d6351ffe210b41b8dba2/tools/workspace/ignition_rndf/package.bzl#L9)):*
> ```Python
>         name = name,
>         repository = "ignitionrobotics/ign-rndf",
>         commit = "0e7c72e6f5f4",
> ```

Maybe define a constant with the value of this commit and use it below also instead of repeating the value. Same goes for ignition-math.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-:-L3-pQbu1II48RaUfaSX:bnfp4nl)*

**Comment by clalancette** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/ignition_rndf/package.BUILD.bazel, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-odemTU6ZxLOO5UZI:-L33PohD6-bkoZEYa0RW:b-g8ht8q) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd9ecfb9723445fc052e97bed47f5b61c70577d/tools/workspace/ignition_rndf/package.BUILD.bazel#L39)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Can you define some constants and use them in place of hardcoding repeated and composite values?
</blockquote></details>

Good call.  Fixed now.

---

*[tools/workspace/ignition_rndf/package.bzl, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-p2IsxYMEu_Pxf3sO:-L33QJy2pPvE7I7ZLVNv:b-p5jxry) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd9ecfb9723445fc052e97bed47f5b61c70577d/tools/workspace/ignition_rndf/package.bzl#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Maybe define a constant with the value of this commit and use it below also instead of repeating the value. Same goes for ignition-math.
</blockquote></details>

Also done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749)*

**Comment by clalancette** [comment]
+@ggould-tri for platform review

---

Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-:-L33QV8nQWER5DBFOHbB:b-gbk9vg)*

**Comment by clalancette** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/workspace/ignition_rndf/package.BUILD.bazel, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-odemTU6ZxLOO5UZI:-L33QeMbNDb8i4SVZKU7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd9ecfb9723445fc052e97bed47f5b61c70577d/tools/workspace/ignition_rndf/package.BUILD.bazel#L39)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Good call.  Fixed now.
</blockquote></details>

Done.

---

*[tools/workspace/ignition_rndf/package.bzl, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-L3-p2IsxYMEu_Pxf3sO:-L33QeqLa6VLsIeC_Fzp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1fd9ecfb9723445fc052e97bed47f5b61c70577d/tools/workspace/ignition_rndf/package.bzl#L9)):*
<details><summary><i>Previously, clalancette (Chris Lalancette) wrote…</i></summary><blockquote>

Also done now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7749#-:-L33Yo1llcQzwjmnSkPI:bnfp4nl)*

**Pull request merged**
