### PR TITLE
[drake_visualizer] Warn on glTF meshes instead of crashing

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See #19624 for manual testing instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19692)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both(?) reviews per schedule, please.

**Comment by jwnimmer-tri** [comment]
I am OK if you want to leave it untested during review, and assume that my own local testing was sufficient.

If you wanted to test it, the instructions would be:
1. Run on Focal somewhere that `drake_visualizer` works.  (Certain kinds of virtual containers will not work.)
2. Fetch #19624 locally.
3. `bazel run //tools:drake_visualizer &`
4. `bazel run //examples/scene_graph:run_solar_system_dynamics`

Before this PR: the visualizer spew an exception message and doesn't show anything.
After this PR: the visualizer spews a warning message and shows the planets but with no sun.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19692)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19692#-NZ1txWGC0qWNEjU91Zp:-NZ1txWGC0qWNEjU91Zq:b5n982f) (no related file):*
Working: Gonna briefly try and test (timebox to ~5min)

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19692)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19692#-NZ1txWGC0qWNEjU91Zp:-NZ1w1RH8rFF_-Wyw8Ac:b-vr58o1) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Gonna briefly try and test (timebox to ~5min)
</blockquote></details>

Done. I was able to run `#19624` A-OK on a Focal container w/o this PR
Cherry-picking this PR didn't show any appreciable difference: 581ebfd627

Exact commands:
```
git fetch upstream pull/19624/head && git checkout FETCH_HEAD
bazel run //tools:drake_visualizer &
bazel run //examples/scene_graph:solar_system_run_dynamics

git fetch upstream pull/19692/head
git cherry-pick FETCH_HEAD
bazel run //tools:drake_visualizer &
bazel run //examples/scene_graph:solar_system_run_dynamics
```

Maybe I messed up, but at a minimum, I'm still fine with merging this forward!

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19692)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19692#-NZ1txWGC0qWNEjU91Zp:-NZ28F6S99xdwxXzDrZc:bp3pb5y) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. I was able to run `#19624` A-OK on a Focal container w/o this PR
Cherry-picking this PR didn't show any appreciable difference: 581ebfd627

Exact commands:
```
git fetch upstream pull/19624/head && git checkout FETCH_HEAD
bazel run //tools:drake_visualizer &
bazel run //examples/scene_graph:solar_system_run_dynamics

git fetch upstream pull/19692/head
git cherry-pick FETCH_HEAD
bazel run //tools:drake_visualizer &
bazel run //examples/scene_graph:solar_system_run_dynamics
```

Maybe I messed up, but at a minimum, I'm still fine with merging this forward!
</blockquote></details>

Sorry, my mistake.  I pasted in the wrong number for the repro.

Fetching #19691 locally is what would show the error.

___

**Comment by EricCousineau-TRI** [comment]
Ah, cool, that works! Saw the crash + the warning now, thanks!

**Pull request merged**
