### PR TITLE
Made RigidBody::name_ private. Renamed accessor to be get_name()

### PR DESCRIPTION
**Pull request by liangfok**
Public access to mutable class member variables is a big no-no since it violates state encapsulation.

All accessors are being named `get_foo()`. I thus rename the accessor for consistency and increased semantic meaning.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2900)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please since this touches `RigidBody`*.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNKkt9xlY72T2n7W6PP:-902151817)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2947/ and is thus ready for feature review @amcastro-tri.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNMlbYZYvTB4ijoeQqb:-1005331616)*

**Comment by amcastro-tri** [comment]
Reviewed 9 of 16 files at r1, 4 of 7 files at r2, 2 of 5 files at r3.
Review status: 14 of 23 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 533 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOZvrBnZBwBPEQkp0i:-KNOZvrBnZBwBPEQkp0j:-1427029855) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/parser_urdf.cc#L533)):*
> ```cpp
> 
>   // World links are handled by parseWorldJoint().
>   body->set_name(std::string(attr));
> ```

why couldn't we just do `body->set_name(attr))`; That should work since `set_name` takes a const string.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 318 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_LwA00RM85-MEca8:-KNO_LwA00RM85-MEca9:-366424145) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L318)):*
> ```cpp
>       constraints.push_back(RelativePositionConstraint(
>           sys.tree.get(), loop.axis, loop.axis, loop.axis,
>           loop.frameA->frame_index, loop.frameB->frame_index, bTbp, tspan));
> ```

unrelated space change. 

---

*[drake/systems/plants/RigidBodySystem.cpp, line 892 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_pmYdh7ZEySidBjX:-KNO_pmYdh7ZEySidBjY:1530621413) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L892)):*
> ```cpp
>   drake::parsers::urdf::AddRobotFromURDFString(urdf_string, root_dir,
>                                                floating_base_type, tree.get());
> ```

Why does reviewable show a little squared symbol here at the beginning of the line?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 76 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOa2jvRpXk1RgkSRVd:-KNOa2jvRpXk1RgkSRVe:1838124243) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodyTree.cpp#L76)):*
> ```cpp
>   // Adds the rigid body representing the world.
>   std::unique_ptr<RigidBody> b(new RigidBody());
>   b->set_name(std::string(RigidBodyTree::kWorldLinkName));
> ```

Do we need `std::string` here?

---

*[drake/systems/plants/test/testIKtraj.cpp, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOb-tvBv_MN0ThNnuM:-KNOb-tvBv_MN0ThNnuN:-1780960878) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L6)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "../constraint/RigidBodyConstraint.h"
> ```

why the change here? shouldn't these by the way be alphabetically ordered? and is it ok to use relative paths?

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObA3Swxb1AZi2N-mj:-KNObA3TBj1yw7Kz59xq:1183550199) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L21)):*
> ```cpp
> GTEST_TEST(testIKtraj, testIKtraj) {
>   RigidBodyTree model(getDrakePath() +
>                       "/examples/Atlas/urdf/atlas_minimal_contact.urdf");
> ```

unrelated change of spacing.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 62 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObFLdSg6oKw3PBFV0:-KNObFLdSg6oKw3PBFV1:-1442905440) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L62)):*
> ```cpp
>   tspan_end << t[nT - 1], t[nT - 1];
>   WorldPositionConstraint kc_rhand(&model, r_hand, r_hand_pt, rhand_pos_lb,
>                                    rhand_pos_ub, tspan_end);
> ```

unrelated spacing change

---

*[drake/util/yaml/yamlUtil.cpp, line 82 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObcPKIJToR5J1w8Jy:-KNObcPKIJToR5J1w8Jz:-1346861823) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/util/yaml/yamlUtil.cpp#L82)):*
> ```cpp
>   }
> 
>   // for (auto config_it = config.begin(); config_it != config.end();
> ```

while at it. Remove this dead code.

---

*[drake/util/yaml/yamlUtil.cpp, line 134 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObjZ85QJPUoc9G4lV:-KNObjZ9w0GFdctAPIM-:-1901104634) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/util/yaml/yamlUtil.cpp#L134)):*
> ```cpp
>          ++body_it) {
>       if (disable_body_name == (*body_it)->get_name()) {
>         // if (std::regex_match((*body_it)->get_name(), disable_body_regex)) {
> ```

Remove comment.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNObtcELzTR2NO_t8_R:-614501512) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
> ```objc
>         auto translation = joint.getTransformToParentBody().translation();
>         auto quat =
>             drake::math::rotmat2quat(joint.getTransformToParentBody().linear());
> ```

unrelated formatting change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900)*

**Comment by amcastro-tri** [comment]
I should add that while a good number of space changes are a clear format improvement (like aligning method arguments) some others seams like they just leaked accidentally in there. I would just undo the accidental ones. Thanks!

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 14 of 23 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 533 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOZvrBnZBwBPEQkp0i:-KNOghJpPe1qvzC2Solx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/parser_urdf.cc#L533)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> why couldn't we just do `body->set_name(attr))`; That should work since `set_name` takes a const string.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 318 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_LwA00RM85-MEca8:-KNOg34nuRDhGVCVEqqU:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L318)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> unrelated space change. 
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 892 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_pmYdh7ZEySidBjX:-KNOf4LrL_n7O2UhHhmN:891016995) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L892)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Why does reviewable show a little squared symbol here at the beginning of the line?
</details>
It indicates that the changes were only white space.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 76 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOa2jvRpXk1RgkSRVd:-KNOgFyCP68XI17k55Nm:-478420467) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodyTree.cpp#L76)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Do we need `std::string` here?
</details>
Removed the explicit `std::string` instantiation.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOb-tvBv_MN0ThNnuM:-KNOgODjXMH0pGuHuQys:-1826806145) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L6)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> why the change here? shouldn't these by the way be alphabetically ordered? and is it ok to use relative paths?
</details>
It is not OK to use relative paths. This change was made by clang-format.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObA3Swxb1AZi2N-mj:-KNOgvKdYPA8zFv35Kkv:-1398239750) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> unrelated change of spacing.
</details>
This was done by clang-format. At your request, I've reverted it.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 62 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObFLdSg6oKw3PBFV0:-KNOhCG55qQN21RTJIKv:-1398239750) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L62)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> unrelated spacing change
</details>
This was done by clang-format. At your request, I've reverted it.

---

*[drake/util/yaml/yamlUtil.cpp, line 82 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObcPKIJToR5J1w8Jy:-KNOhXrHsyWc24mGQ1y7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/util/yaml/yamlUtil.cpp#L82)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> while at it. Remove this dead code.
</details>
Done.

---

*[drake/util/yaml/yamlUtil.cpp, line 134 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObjZ85QJPUoc9G4lV:-KNOhhNNB7wKIDBLWRbL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/util/yaml/yamlUtil.cpp#L134)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Remove comment.
</details>
Done.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNOiH7mbINUNIjr-CiL:1984966795) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> unrelated formatting change
</details>
This cannot be undone because it will then violate the 80 character-wide rule.  I'm surprised CI did not catch this previously. Maybe because it's a Drake/ROS system?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNOkWr08zpC_6XLkk1i:-84625242)*

**Comment by liangfok** [comment]
Possible Win64 flake: https://drake-jenkins.csail.mit.edu/job/experimental/2951/

```
18:04:21 FATAL: Remote call on drake-windows-2016-07-22-c4.8xlarge (i-3585ffa5) failed
18:04:21 java.io.IOException: Remote call on drake-windows-2016-07-22-c4.8xlarge (i-3585ffa5) failed
18:04:21 	at hudson.remoting.Channel.call(Channel.java:789)
18:04:21 	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:953)
18:04:21 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:540)
18:04:21 	at hudson.model.Run.execute(Run.java:1738)
18:04:21 	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
18:04:21 	at hudson.model.ResourceController.execute(ResourceController.java:98)
18:04:21 	at hudson.model.Executor.run(Executor.java:410)
18:04:21 Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
18:04:21 	at hudson.util.ProcessKillingVeto.all(ProcessKillingVeto.java:77)
18:04:21 	at hudson.util.ProcessTree$OSProcess.getVeto(ProcessTree.java:237)
18:04:21 	at hudson.util.ProcessTree$Windows$1.killRecursively(ProcessTree.java:421)
18:04:21 	at hudson.util.ProcessTree$Windows.killAll(ProcessTree.java:486)
18:04:21 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:965)
18:04:21 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:956)
18:04:21 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
18:04:21 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
18:04:21 	at hudson.remoting.Request$2.run(Request.java:326)
18:04:21 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
18:04:21 	at java.util.concurrent.FutureTask.run(Unknown Source)
18:04:21 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
18:04:21 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
18:04:21 	at java.lang.Thread.run(Unknown Source)
18:04:21 	at ......remote call to drake-windows-2016-07-22-c4.8xlarge (i-3585ffa5)(Native Method)
18:04:21 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
18:04:21 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
18:04:21 	at hudson.remoting.Channel.call(Channel.java:781)
```

@drake-jenkins-bot retest this please.

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2953/ and is thus ready for another round of review @amcastro-tri .

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: 15 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 892 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_pmYdh7ZEySidBjX:-KNSMoowVM-spBktBo01:662206134) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L892)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> It indicates that the changes were only white space.
</details>
Oh, I see. Would you know why sometimes (most of the times I think) it shows you those changes as highlighted in green instead. I was wondering if the little squared cap meant something like a strange character or something like that. 

---

*[drake/systems/plants/test/testIKtraj.cpp, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOb-tvBv_MN0ThNnuM:-KNSNGf98kHC9jUfn-zN:1865013354) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> It is not OK to use relative paths. This change was made by clang-format.
</details>
clang-format changed the order of includes? wow! I didn't know it could do that. In any case, we do not need to accept changes made by clang-format if we are not happy with them. I usually run clang-format and then do a `git add -p` to select the "useful" changes. Otherwise clang-format tends to make a lot of white space formatting . Since you are modifying this anyway, make sure it follows the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) (order of includes, no relative paths, and sort alphabetically within each section of includes).

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObA3Swxb1AZi2N-mj:-KNSOLl8Yj_cTYxCUj1a:-1482183116) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This was done by clang-format. At your request, I've reverted it.
</details>
Thanks!. We do not need to abide by clang-format rules. We do however by cppling rules.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNSOqaGyRyZH1mYNQNl:-1127111161) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This cannot be undone because it will then violate the 80 character-wide rule.  I'm surprised CI did not catch this previously. Maybe because it's a Drake/ROS system?
</details>
Oh, wow, thank you for finding that @liangfok. Interesting. Would @jwnimmer-tri or @david-german-tri know why CI didn't catch this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL @amcastro-tri . Thanks.

---

Review status: 15 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 892 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNO_pmYdh7ZEySidBjX:-KNSuQVkd7mTlzt36NKS:-1310495445) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/RigidBodySystem.cpp#L892)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Oh, I see. Would you know why sometimes (most of the times I think) it shows you those changes as highlighted in green instead. I was wondering if the little squared cap meant something like a strange character or something like that. 
</details>
That's a good question. Unfortunately I have no idea! I just doubled checked and there are no strange characters like a tab on this line. Everything appears legit.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 6 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNOb-tvBv_MN0ThNnuM:-KNSuYyhSTAbsgzFuSwP:776412200) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L6)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> clang-format changed the order of includes? wow! I didn't know it could do that. In any case, we do not need to accept changes made by clang-format if we are not happy with them. I usually run clang-format and then do a `git add -p` to select the "useful" changes. Otherwise clang-format tends to make a lot of white space formatting . Since you are modifying this anyway, make sure it follows the [style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) (order of includes, no relative paths, and sort alphabetically within each section of includes).
</details>
Yes, clang-format can change the order of includes. See: https://github.com/RobotLocomotion/drake/pull/1977

Thanks for the advice on the `git add -p`. Maybe it should be added to http://drake.mit.edu/code_style_tools.html#usage. 

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObA3Swxb1AZi2N-mj:-KNSv-pkz0AVUxGXmyz_:1269805762) ([raw file](https://github.com/robotlocomotion/drake/blob/f2cd04e155db0ed37416c0985016e5e73541490f/drake/systems/plants/test/testIKtraj.cpp#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Thanks!. We do not need to abide by clang-format rules. We do however by cppling rules.
</details>
OK SGTM.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNSvAziEIJBFi66gcMx:-843399925) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Oh, wow, thank you for finding that @liangfok. Interesting. Would @jwnimmer-tri or @david-german-tri know why CI didn't catch this?
</details>
Ah, I see. The change actually fixed the >80 char length. That is why CI did not complain; the problem did not exist.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNSvKYX9gkfJLcVuc7R:-611603263)*

**Comment by amcastro-tri** [comment]
Review status: 15 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNTAlDN_8V_Uow44gRx:-1032740295) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Ah, I see. The change actually fixed the >80 char length. That is why CI did not complain; the problem did not exist.
</details>
I don't mean how it passed CI now  but how it passed CI before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900)*

**Comment by liangfok** [comment]
Review status: 15 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h, line 123 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNObtcELzTR2NO_t8_Q:-KNTBlL7MrY3YFAqPzCB:1161553943) ([raw file](https://github.com/robotlocomotion/drake/blob/b1d699383907d5209edd4d3a97acc10af144e022/ros/drake_ros_systems/include/drake_ros/ros_tf_publisher.h#L123)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I don't mean how it passed CI now  but how it passed CI before
</details>
I believe the version in `r3` had the white space change that reduced the line length to be less than 80 characters.  This is why CI did not complain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 1 of 16 files at r1, 2 of 5 files at r3, 4 of 5 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNX_TChRLny-qJ949ui:1417088721)*

**Comment by amcastro-tri** [comment]
would this PR need a platform review @liangfok?

**Comment by liangfok** [comment]
Thanks @amcastro-tri. +@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNX_tWVmXjO979IBAXo:-409440205)*

**Comment by sherm1** [comment]
Platform: :lgtm:. One missing newline -- I marked it "BTW" but you should add it, then feel free to merge.

---

Reviewed 8 of 16 files at r1, 3 of 7 files at r2, 4 of 5 files at r3, 4 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 86 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-KNY39a4dgLGHnYVTdOJ:-KNY39a5Bei4YdaNt9M3:-904542935) ([raw file](https://github.com/robotlocomotion/drake/blob/ba89f42f65ad276cf1a99793050c534b1a75a88c/CHANGELOG.md#L86)):*
> ```Markdown
> [#2666]: https://github.com/RobotLocomotion/drake/issues/2666
> [#2779]: https://github.com/RobotLocomotion/drake/issues/2779
> [#2900]: https://github.com/RobotLocomotion/drake/issues/2900
> ```

BTW, newline missing at eof

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNY4UgUENn6zH0IvpGs:-1895193108)*

**Comment by liangfok** [comment]
Thanks. Since this PR is part of a long sequence of related PRs. I will merge this and fix the problem in the subsequent PR.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2900#-:-KNY9t4kakLiwyWju8R4:-666466219)*

**Pull request merged**
