### PR TITLE
basic piecewise affine system design/implementation

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6833)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@rdeits and @TobiaMarcucci for (first) feature reviews.  

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-:-KrNypgh_XyZvYIvsJP_:b-gmdg9r)*

**Comment by rdeits** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXgmnplfqPykBq0553:-KrXgmnplfqPykBq0554:b-vuoi87) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L49)):*
> ```cpp
> 
> template <typename T>
> void PiecewiseAffineSystem<T>::DoCalcVectorTimeDerivatives(
> ```

Since discrete and continuous systems are the same C++ type, is there some enforcement mechanism to make sure that the correct one of {TimeDerivatives | DiscreteVariableUpdates} is begin called?

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrX_WVxgZZrYNbU1eTp:-KrX_WVxgZZrYNbU1eTq:b-ejsnov) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L92)):*
> ```cpp
> 
> template <typename T>
> int PolytopicListPiecewiseAffineSystem<T>::AddPiece(
> ```

9 different positional arguments seems like way too many. Do we actually want to support this method in addition to the much more clear method above that takes an AffineSystem and a Domain?

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXa2p2n5pvfpayPGFf:-KrXa2p2n5pvfpayPGFg:beutg5i) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L120)):*
> ```cpp
>     const Eigen::VectorBlock<const VectorX<T>>& input,
>     const Eigen::VectorBlock<const VectorX<T>>& state) const {
>   unused(context);
> ```

Can you explain this? Why have the argument and then not use it?

---

*[drake/systems/primitives/piecewise_affine_system.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbqEiqXLL-Qh9pLN6:-KrXbqEiqXLL-Qh9pLN7:b-2hnyje) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L42)):*
> ```objc
>  */
> template <typename T>
> class PiecewiseAffineSystem : public VectorSystem<T> {
> ```

Are the piecewise affine systems inherently just vector-in and vector-out? That is, is there no way to attach any information about what each coordinate means? 

---

*[drake/systems/primitives/piecewise_affine_system.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbQdHfNNkj-7n-y-l:-KrXbQdHfNNkj-7n-y-m:b-b53pqn) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L57)):*
> ```objc
>   /// 0...{num_pieces-1}.  Derived classes should implement
>   /// %DoGetSystemAtIndex%.
>   const AffineSystem<T>& GetSystemAtIndex(int index) const {
> ```

I'm not sure how a (hypothetical) future implicitly-defined piecewise affine class will implement this method. For example, if evaluating my dynamics involves solving an LCP, it's not really clear if it's easy or useful to define a unique indexing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833)*

**Comment by RussTedrake** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXgmnplfqPykBq0553:-KrY7bILuW365Dz3a153:bl13tig) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L49)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Since discrete and continuous systems are the same C++ type, is there some enforcement mechanism to make sure that the correct one of {TimeDerivatives | DiscreteVariableUpdates} is begin called?
</blockquote></details>

Yes.  This is part of the role that the VectorSystem parent class plays.  

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrX_WVxgZZrYNbU1eTp:-KrY7xvtEebonxLREByl:b-iz3jo0) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L92)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

9 different positional arguments seems like way too many. Do we actually want to support this method in addition to the much more clear method above that takes an AffineSystem and a Domain?
</blockquote></details>

The only advantage that this has over the cleaner version is that it does not require time_period (a redundant argument in the first version which MUST match the time_period for the PWA).  I'd be ok zapping this one.

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXa2p2n5pvfpayPGFf:-KrY7lND_wE5lNfBps6V:b-kbp40d) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L120)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Can you explain this? Why have the argument and then not use it?
</blockquote></details>

This is an implementation of a virtual method from the parent class.  The context contains other information, if a derived class chooses to use it... such as time and parameters.  

---

*[drake/systems/primitives/piecewise_affine_system.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbqEiqXLL-Qh9pLN6:-KrY8JoNcj-oiUyiND_D:bmtt9c9) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L42)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Are the piecewise affine systems inherently just vector-in and vector-out? That is, is there no way to attach any information about what each coordinate means? 
</blockquote></details>

The vectors can be typed... they simply have to be derived from BasicVector (so convertable to Eigen::Vectors).   We use dynamic_casts to downcast to a known type throughout the code.

---

*[drake/systems/primitives/piecewise_affine_system.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbQdHfNNkj-7n-y-l:-KrY8XnVtv8YK1LDCZml:b-53daep) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L57)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

I'm not sure how a (hypothetical) future implicitly-defined piecewise affine class will implement this method. For example, if evaluating my dynamics involves solving an LCP, it's not really clear if it's easy or useful to define a unique indexing. 
</blockquote></details>

That's a good question.  I think it's definitely not the most natural interface in your example, but it seems like it would be reasonable to provide it (e.g. binary encoding of the complementarity conditions => integer).  I would have thought that this would be the way that some of the planning classes would want to access it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833)*

**Comment by RussTedrake** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/piecewise_affine_system.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbqEiqXLL-Qh9pLN6:-KrYA8mKI_0KV7QdfF83:b-rhsx29) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L42)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The vectors can be typed... they simply have to be derived from BasicVector (so convertable to Eigen::Vectors).   We use dynamic_casts to downcast to a known type throughout the code.
</blockquote></details>

if we think that this is the more usual case (it might actually be -- the state of a RigidBodyPlant is our prime example), then I should derive directly from LeafSystem instead of VectorSystem, simply to avoid the cost of copying to the Eigen::Vector on every evaluation.  Perhaps that's the right call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833)*

**Comment by RussTedrake** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/piecewise_affine_system.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbqEiqXLL-Qh9pLN6:-KreyIh_HIvP3u4kfBgZ:b5f92l8) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L42)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

if we think that this is the more usual case (it might actually be -- the state of a RigidBodyPlant is our prime example), then I should derive directly from LeafSystem instead of VectorSystem, simply to avoid the cost of copying to the Eigen::Vector on every evaluation.  Perhaps that's the right call.
</blockquote></details>

thinking more about this, i think that a common use case it to use symbolic to generate a new PWA from the e.g. rigidbodyplant.  the only danger of leaving it as is is minor inefficiency.  i think we should wait and adjust as the use cases call for it.

---

*[drake/systems/primitives/piecewise_affine_system.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbQdHfNNkj-7n-y-l:-KreyZhtgMuBUnHG9-73:b2o3s4c) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L57)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

That's a good question.  I think it's definitely not the most natural interface in your example, but it seems like it would be reasonable to provide it (e.g. binary encoding of the complementarity conditions => integer).  I would have thought that this would be the way that some of the planning classes would want to access it?
</blockquote></details>

thinking more about this, too... i think it's a reasonable and natural requirement for every PWA to have to be able to report an integer mode that it's in.  i vote to keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833)*

**Comment by rdeits** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/piecewise_affine_system.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrX_WVxgZZrYNbU1eTp:-KrfzlxIHAPJKSJtqohH:b-okdsdw) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.cc#L92)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The only advantage that this has over the cleaner version is that it does not require time_period (a redundant argument in the first version which MUST match the time_period for the PWA).  I'd be ok zapping this one.
</blockquote></details>

Yeah, that's awkward. But, realistically, is manually inputting the dynamics and domain matrices actually a thing you want users to do? I can see someone doing that for a unit test or a trivial example, but it seems like the wrong level of abstraction to expose. I think we should get rid of this signature, and if the other one is hard to use we should fix that. 

---

*[drake/systems/primitives/piecewise_affine_system.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbqEiqXLL-Qh9pLN6:-Krg0eo2A5rhLqusQ8_F:bs3204d) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L42)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

thinking more about this, i think that a common use case it to use symbolic to generate a new PWA from the e.g. rigidbodyplant.  the only danger of leaving it as is is minor inefficiency.  i think we should wait and adjust as the use cases call for it.
</blockquote></details>

I guess if it's always returning affine systems, which themselves contain matrices, then this only really makes sense if there coordinates are vectorizable. 

---

*[drake/systems/primitives/piecewise_affine_system.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-KrXbQdHfNNkj-7n-y-l:-Krg-xICjEwCBx3SDudj:bncik44) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb8d9458595b4af07abe7d06a5f83ebd7fed8e/drake/systems/primitives/piecewise_affine_system.h#L57)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

thinking more about this, too... i think it's a reasonable and natural requirement for every PWA to have to be able to report an integer mode that it's in.  i vote to keep it.
</blockquote></details>

Yeah, it's definitely possible to create that mapping, although many of the resulting indices will correspond to modes with empty domains. I guess this is OK. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833)*

**Comment by RussTedrake** [comment]
since @rdeits and @tobiamarcucci aren't pining for this, and since @rdeits is solving all of the architecture design issues, i will close this for now.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6833#-:-KudoRiHBGNrmRUicTZt:b-ypz7k6)*

**Pull request closed without merging**
