### PR TITLE
Fix all C++17 build errors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a feature branch only used for CI testing.

Note that macOS build errors are not fixed by this PR; only Ubuntu errors.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11622)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-cxx17-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-cxx17-release please
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-cxx17-release please

(out of interest, does not matter if you push changes that cancel the builds...)

**Comment by jamiesnape** [comment]
We have a remote caching issue. The key on the C++14 and C++17 builds is identical so C++17 is using C++14 artifacts. I will disable the cache for C++17 for now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-cxx17-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-cxx17-release please

**Comment by jwnimmer-tri** [comment]
It looks like the one remaining Bionic Clang-6.0 issue is https://github.com/pybind/pybind11/issues/1604, \CC @EricCousineau-TRI.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-cxx17-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-cxx17-release please

**Comment by jwnimmer-tri** [comment]
> It looks like the one remaining Bionic Clang-6.0 issue ...

Now filed as #11638 for tracking / discussion.

**Comment by jwnimmer-tri** [comment]
As of #11650, all Ubuntu errors are resolved.

**Pull request closed without merging**
