### PR TITLE
MathematicalProgram reports optimal cost when the problem is infeasible or unbounded.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Solves two issues in this PR.

1. When the problem is unbounded, then the optimal cost should be negative infinity; when the problem is globally infeasible, then the optimal cost should be positive infinity.
2. Solves #7687 , now NLopt can detect infeasibility and unboundedness. Ipopt can detect unboundedness.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7688)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1uvhOM1HHTDuO37xUf:bjquaum)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/equality_constrained_qp_solver.cc, line 254 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1wm9hEWwn-I_QqimMN:-L1wm9hGq5wCiGuOFZoA:bge9p6z) ([raw file](https://github.com/robotlocomotion/drake/blob/e56e2384d23374d68d07fe5f2b7fb03e19b82abb/solvers/equality_constrained_qp_solver.cc#L254)):*
> ```cpp
>       optimal_cost = 0.5 * x.dot(G * x) + c.dot(x) + constant_term;
>       break;
>                                          }
> ```

This seems like a strange indentation for the closing brace.

---

*[solvers/mathematical_program.h, line 2000 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1wZKfVlTlUAmss0iMj:-L1wZKfWHpKQdT1jkHlY:bc8ppjn) ([raw file](https://github.com/robotlocomotion/drake/blob/e56e2384d23374d68d07fe5f2b7fb03e19b82abb/solvers/mathematical_program.h#L2000)):*
> ```objc
>    * If the program is unbounded, then the optimal cost is -∞.
>    * If the program is globally infeasible, then the optimal cost is +∞ 
>    * If the program is locally infeasible, and the solver (e.g. SNOPT) finds some values for the decision variables, such as the solution with least constraint violation, then return the cost evaluated at that solution.
> ```

BTW we could add an assertion in `MathematicalProgram::Solve()` that the optimal cost matches the `SolutionResult` in the unbounded and globally infeasible cases.  (this wouldn't catch cases where the specific solver's `Solve()` function is invoked directly).  I'll leave it up to the author if it's worth making the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1wnskYbAVU1tczByHN:bvb1a6z)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/equality_constrained_qp_solver.cc, line 254 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1wm9hEWwn-I_QqimMN:-L1wtwt6ZAIbWM4QXMmB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e56e2384d23374d68d07fe5f2b7fb03e19b82abb/solvers/equality_constrained_qp_solver.cc#L254)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems like a strange indentation for the closing brace.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 2000 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1wZKfVlTlUAmss0iMj:-L1wv6B-x0A8P5Vztl7_:b-cyzbwa) ([raw file](https://github.com/robotlocomotion/drake/blob/e56e2384d23374d68d07fe5f2b7fb03e19b82abb/solvers/mathematical_program.h#L2000)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW we could add an assertion in `MathematicalProgram::Solve()` that the optimal cost matches the `SolutionResult` in the unbounded and globally infeasible cases.  (this wouldn't catch cases where the specific solver's `Solve()` function is invoked directly).  I'll leave it up to the author if it's worth making the change.
</blockquote></details>

I think a potential solution is to add a function 
```
void SetOptimalCostAndResult(double optimal_cost, SolutionResult result);
```
and remove the current function `SetOptimalCost`. Then we add that check inside `SetOptimalCostAndResult`. This will make sure that when the optimal cost and the result are set in each solver, they were set correctly.

I will add the change to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688)*

**Comment by hongkai-dai** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2000 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1wZKfVlTlUAmss0iMj:-L1x5cY0GqONw1fpuV7o:bl69zse) ([raw file](https://github.com/robotlocomotion/drake/blob/e56e2384d23374d68d07fe5f2b7fb03e19b82abb/solvers/mathematical_program.h#L2000)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think a potential solution is to add a function 
```
void SetOptimalCostAndResult(double optimal_cost, SolutionResult result);
```
and remove the current function `SetOptimalCost`. Then we add that check inside `SetOptimalCostAndResult`. This will make sure that when the optimal cost and the result are set in each solver, they were set correctly.

I will add the change to this PR.
</blockquote></details>

I realize this is not the right solution. The issue is that when the problem is globally infeasible, then the optimal cost should be positive infinity; when the problem is only locally infeasible, the optimal cost can be a finite number, evaluated at the solution. But in `MathematicalProgram`, it does not know if the problem is solved locally or globally, only the solver knows that (SNOPT vs Mosek, for example).

I will leave the code as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: pending CI issues.  +@seancurtis-tri for platform review per rotation

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1xIfQ6YbRksLf_pj05:be2llhr)*

**Comment by SeanCurtis-TRI** [comment]
There's a part of my soul that would *love* to see `MathematicalProgram::kUnboundedValue` and `MathematicalProgram::kInfeasibleValue` defined and set to -/+ infinity, respectively. Then, rather than seeing invocations of numeric limits everywhere, you'd be assigning nicely human readable values.

Some subtle cosmetic things.

---

Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[solvers/mathematical_program.h, line 2000 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xN3ihRsAuVNsNm7Wq:-L1xN3ihRsAuVNsNm7Wr:b-s56535) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/mathematical_program.h#L2000)):*
> ```objc
>    * If the program is unbounded, then the optimal cost is -∞.
>    * If the program is globally infeasible, then the optimal cost is +∞ 
>    * If the program is locally infeasible, and the solver (e.g. SNOPT) finds some values for the decision variables, such as the solution with least constraint violation, then return the cost evaluated at that solution.
> ```

BTW Line length (this isn't caught by cpplint because it's inside a `/** ... */` block.

---

*[solvers/nlopt_solver.cc, line 318 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xYKWcTKnP6wyruVLr:-L1xYKWcTKnP6wyruVLs:b-qopy5n) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L318)):*
BTW More line length issues.
BTW The [in/out] is appended to `@param`.
BTW The comment is unclear, I'd suggest something along the lines of:

> @param[in/out] all_constraints_satisfied If true, the constraint test is performed and this bool is updated to the test's result. Otherwise, no work is done.

---

*[solvers/nlopt_solver.cc, line 323 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xZFnB1bl_zw5ewayT:-L1xZFnB1bl_zw5ewayU:b-v4jt8l) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L323)):*
> ```cpp
> void CheckConstraintsSatisfied(const MathematicalProgram& prog,
>                                const std::vector<Binding>& bindings, double tol,
>                                bool* all_constraints_satisfied) {
> ```

BTW Given that this returns `void`, why have this be an out rather than returning the boolean?

The alternative would be:

```c++
return all_constraints_satisified && IsVectorOfConstraintsSatisifiedAtSolution(prog, bindings, tol);
```

---

*[solvers/nlopt_solver.cc, line 440 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xaJcViV8fzvYoU9nw:-L1xaJcViV8fzvYoU9nx:b-nwb14n) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L440)):*
> ```cpp
>         const double constraint_tol = 1E-6;
>         bool all_constraints_satisfied = true;
>         CheckConstraintsSatisfied(prog, prog.generic_constraints(),
> ```

FYI I admit that *this* code would get a bit longer by returning the bool.  E.g., 

```c++
all_constraints_satisfied = CheckConstraintSatisfied(prog, prog.generic_constraints(), constraint_tol, all_constraints_satisfied);
```

You could get around that by shortening the variable name, perhaps? Or create a lambda:

```C++
auto constraint_test = [&prog, constraint_tol, &all_constraints_satisfied](auto constraints) {
  all_constraints_satisfied = all_constraints_satisfied &&
                              IsVectorOfConstraintsSatisifiedAtSolution(prog, constraints, constraint_tol);
};
constraint_test(prog.generic_constraints());
constraint_test(prog.bounding_box_constraints());
...
constraint_test(prog.rotated_lorentz_cone_constraints());
if (!all_constraints_satisfied) { ... }
```
(And this eliminates the method `CheckConstraintsSatisfied` entirely.

---

*[solvers/nlopt_solver.cc, line 470 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xeogF2X9LW3lvzQV9:-L1xeogGKj0iU5Q1oBXu:b-jae6c1) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L470)):*
> ```cpp
>           result = SolutionResult::kUnbounded;
>           minf = -std::numeric_limits<double>::infinity();
>           break;
> ```

BTW Multiple `break`s in a single case block can be confusing. How about an "else" and a single, terminal `break`?  (Like in the try/catch block you've added below.)

---

*[solvers/test/gurobi_solver_test.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xg-nKit9RCXxGak8A:-L1xg-nKit9RCXxGak8B:bhb3sca) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/test/gurobi_solver_test.cc#L38)):*
> ```cpp
>     result = solver.Solve(*prog_);
>     EXPECT_EQ(result, SolutionResult::kInfeasibleConstraints);
>     EXPECT_TRUE(std::isinf(prog_->GetOptimalCost()));
> ```

FYI If you had infeasible and unbounded as const static member somewhere, then you could simply compare the result against that variable.  Nicely readable!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1xf7J_sK57CajdL7GT:buu61ld)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[solvers/mathematical_program.h, line 2000 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xN3ihRsAuVNsNm7Wq:-L1y5FA9TNIBynCc_xm5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/mathematical_program.h#L2000)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Line length (this isn't caught by cpplint because it's inside a `/** ... */` block.
</blockquote></details>

Done.

---

*[solvers/nlopt_solver.cc, line 318 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xYKWcTKnP6wyruVLr:-L1y5wpcbXZZDG-4ttj9:b-xq7qc) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L318)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW More line length issues.
BTW The [in/out] is appended to `@param`.
BTW The comment is unclear, I'd suggest something along the lines of:

> @param[in/out] all_constraints_satisfied If true, the constraint test is performed and this bool is updated to the test's result. Otherwise, no work is done.
</blockquote></details>

Done. Thanks for writing the documentation.

---

*[solvers/nlopt_solver.cc, line 323 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xZFnB1bl_zw5ewayT:-L1y7WwbwVV6Cem8lwNn:bv9wrzy) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L323)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given that this returns `void`, why have this be an out rather than returning the boolean?

The alternative would be:

```c++
return all_constraints_satisified && IsVectorOfConstraintsSatisifiedAtSolution(prog, bindings, tol);
```
</blockquote></details>

Done. I removed this function I think it is cleaner now.

---

*[solvers/nlopt_solver.cc, line 440 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xaJcViV8fzvYoU9nw:-L1y80_i21dWl35dSgLf:bd8eebk) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L440)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I admit that *this* code would get a bit longer by returning the bool.  E.g., 

```c++
all_constraints_satisfied = CheckConstraintSatisfied(prog, prog.generic_constraints(), constraint_tol, all_constraints_satisfied);
```

You could get around that by shortening the variable name, perhaps? Or create a lambda:

```C++
auto constraint_test = [&prog, constraint_tol, &all_constraints_satisfied](auto constraints) {
  all_constraints_satisfied = all_constraints_satisfied &&
                              IsVectorOfConstraintsSatisifiedAtSolution(prog, constraints, constraint_tol);
};
constraint_test(prog.generic_constraints());
constraint_test(prog.bounding_box_constraints());
...
constraint_test(prog.rotated_lorentz_cone_constraints());
if (!all_constraints_satisfied) { ... }
```
(And this eliminates the method `CheckConstraintsSatisfied` entirely.
</blockquote></details>

Cool! The use of lambda is really neat.

---

*[solvers/nlopt_solver.cc, line 470 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xeogF2X9LW3lvzQV9:-L1y9GDYl_rUHX_TZmZF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/nlopt_solver.cc#L470)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Multiple `break`s in a single case block can be confusing. How about an "else" and a single, terminal `break`?  (Like in the try/catch block you've added below.)
</blockquote></details>

Done.

---

*[solvers/test/gurobi_solver_test.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1xg-nKit9RCXxGak8A:-L1yCF8RviICVGLQInJw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/729a86cf86429485de297698f37e7e2d35e47afc/solvers/test/gurobi_solver_test.cc#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI If you had infeasible and unbounded as const static member somewhere, then you could simply compare the result against that variable.  Nicely readable!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Thanks for humoring me.  It's now very pretty.

---

Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.cc, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1yMaVlO0HgtdPxKd2Z:-L1yMaVlO0HgtdPxKd2_:b-l79exg) ([raw file](https://github.com/robotlocomotion/drake/blob/37c2349dbcd56c0204e0e397f9f318c58c9eccc7/solvers/mathematical_program.cc#L115)):*
> ```cpp
> // https://gcc.gnu.org/wiki/VerboseDiagnostics#missing_static_const_definition)
> 
> const double MathematicalProgram::kGlobalInfeasibleCost =
> ```

FYI You could make these `constexpr`. Won't make a difference in your current code, but ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1yOZlFzHCn2nGJbmrM:b-8cr2cz)*

**Comment by hongkai-dai** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.cc, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-L1yMaVlO0HgtdPxKd2Z:-L1yYymxGLrnASoRdHOf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/37c2349dbcd56c0204e0e397f9f318c58c9eccc7/solvers/mathematical_program.cc#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI You could make these `constexpr`. Won't make a difference in your current code, but ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688)*

**Comment by SeanCurtis-TRI** [comment]
Thanks

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1yyW_nz54T7OiAY_pr:b-zcjvte)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7688#-:-L1yzki9wokTQWWqTtSL:b-l70wzf)*

**Pull request merged**
