### PR TITLE
workspace: Upgrade tinyobjloader to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy or @SeanCurtis-TRI can you check why `bazel test //geometry/proximity:obj_to_surface_mesh_test` is failing here when we upgrade tinyobjloader?  Low priority.

The only functional change across the upgrade range appears to be https://github.com/tinyobjloader/tinyobjloader/commit/7ba4b652ee0c5175ec8abf66199e84d88adf11f1.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've got it.

+@seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXbi9_NAPryXjBChhzN:b-wzprdd)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge" (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've pushed what I believe is the fix.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXbp4gR3Gxe_yJSbif4:b8b8p7c)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by DamrongGuoy — COMMENTED** [review]
Thank you @seancurtis-tri .  Also thanks to @jwnimmer-tri for pointing to that 7ba4b65 commit.  It led me to [this line](https://github.com/tinyobjloader/tinyobjloader/blob/15bc2685b51612748bcfdb820bb4d42087a7dce1/tiny_obj_loader.h#L1430) in the new tiny_obj_loader.h.

```
1430          // Choose the shortest edge.
1431          // TODO: Is it better to determine the edge to split by calculating
1432          // the area of each triangle?
```
I agree with @seancurtis-tri that they might change the triangulation algorithm again in the future.

Actually I'm already worried that choosing the shortest edge on a perfect rectangle is numerically unstable.  Rounding errors may flip the coin arbitrarily between two equal-length diagonals.  Let's cross our fingers that it will make the same decisions on all platforms. :crossed_fingers: 

I'll be on vacation tomorrow and be back on Monday.  If we have the Weekly Test failure, I can create another obj file to replace the quad_cube.obj, so we have a clear shortest edge winner in every quad face.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXcxqwI30nLOIdmJAdj:b16m892)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I assume we'll be ok for this test as all vertex positions are at positions like (1, 0, 0). All ones and zeros. They are values that are perfectly represented on every machine and whose solution should suffer from no rounding. So, I have every expectation that we'll experience consistent results across all machines.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXd7anCDqEWfXmNBA-r:bk9p8jo)* status: LGTM missing from assignee SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXhzb0bBEE8O52U642D:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14866#-:-MXhzmtX4iGsUvDXx7lE:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
