### PR TITLE
Updates SAP's reference year

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17513)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17513#-:-N6KVkmoDVQ1_G5SjkFi:bsu6fmf)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 pending two equation number changes

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17513#-:-N6K_ZOq3NOXB4UsYPk-:bbz2qny)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 399 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17513#-N6K_PIK59WTBRJLqsjo:-N6K_PIK59WTBRJLqsjp:brcd0hy) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b6a151a307548f160ff88fbf8db8da48147812/multibody/contact_solvers/sap/test/sap_solver_test.cc#L399)):*
> ```cpp
>       Vector4d(0.0, 0.0, problem.mass() * problem.g(), -Mz);
> 
>   // Maximum expected slip. See Castro et al. 2022 for details (Eq. 22).
> ```

nit: should be Eq. 31
___
*[`multibody/contact_solvers/sap/test/sap_solver_test.cc` line 600 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17513#-N6K_TOe5K6JSmV4qHDi:-N6K_TOe5K6JSmV4qHDj:brcd0hy) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b6a151a307548f160ff88fbf8db8da48147812/multibody/contact_solvers/sap/test/sap_solver_test.cc#L600)):*
> ```cpp
>                             -dt * Mz);
> 
>   // Maximum expected slip. See Castro et al. 2022 for details (Eq. 22).
> ```

nit: should be Eq. 31

**Review by amcastro-tri — COMMENTED** [review]
Nice! thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17513#-:-N6Nov5L8H50H0wh3-lv:bcb8rt0)* status: needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 

There is a conflict with master so this needs a manual merge or rebase.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17513#-:-N6OUGSUCTHehMcZEzzJ:bowoofa)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @amcastro-tri)

**Pull request merged**
