### PR TITLE
[contact_solvers] Opt-in to clang-format linting

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards the ongoing effort to clang-format everything as discussed in platform reviewer meeting.

See https://github.com/RobotLocomotion/drake/pull/18175 for prior art. That PR has a long explanation for the motivation here.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19180)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri, owner of the directory, for feature review please.
This PR requires that all future changes to `drake/multibody/contact_solvers` to abide clang-format.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19180#-:-NSmiZwF1qgntEDCRnqA:b-9bespy)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thank you for cleaning up all these files! :lgtm: 

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19180#-:-NSpdbUv7x77Prprjo22:bful3f)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@SeanCurtis-TRI for Monday platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19180#-:-NSwzwHOClzp4slJxiyw:bjzy0l7)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19180#-:-NTEhvSE00Mj1QN5mdiu:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,SeanCurtis-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
