### PR TITLE
Run clang-format on multibody tree tests

### PR DESCRIPTION
**Pull request by sherm1**
Towards making multibody tree clang-format idempotent, this PR reformats all the multibody/tree test code.
There are many other files that need formatting, but I'm holding off to avoid merge nightmares with WIPs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21928)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@jwnimmer-tri for both reviews please per rotation (no rush)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-:-O76nLG30n0A04DgBnYM:b-9vsc5l)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: thank you!

> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-:-O77Q7QC1lOCt_nDc_5S:bro3093)* status: 2 unresolved discussions

___
*[`multibody/tree/test/rotational_inertia_test.cc` line 887 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-O77PkI_2VUHpunEIByW:-O77PkI_2VUHpunEIByX:b91rli1) ([raw file](https://github.com/RobotLocomotion/drake/blob/d73d0659b91c11a583636b5dbae7c792ac3355e7/multibody/tree/test/rotational_inertia_test.cc#L887)):*
> ```cpp
>   Matrix3<double> wcross = Rdot_WB * Rvalue_WB.transpose();
>   Matrix3<double> wcross_expected;
>   wcross_expected << 0.0, -wz, 0.0, wz, 0.0, 0.0, 0.0, 0.0, 0.0;
> ```

nit This matrix got clobbered.
___
*[`multibody/tree/test/tree_from_joints_test.cc` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-O77P64R-U0cRyoHqfDE:-O77P64R-U0cRyoHqfDF:b-cgksky) ([raw file](https://github.com/RobotLocomotion/drake/blob/d73d0659b91c11a583636b5dbae7c792ac3355e7/multibody/tree/test/tree_from_joints_test.cc#L143)):*
> ```cpp
>     shoulder_ = &model->template AddJoint<RevoluteJoint>(
>         "ShoulderJoint", *world_body_,
>         {}, /* Default to Identity; frame Si IS the world frame W. */
> ```

BTW You are okay with the new comment arrangement here?  Ditto about 10 lines down.  I think it's fine, but borderline so wanted to check.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21928)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

___
*[`multibody/tree/test/rotational_inertia_test.cc` line 887 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-O77PkI_2VUHpunEIByW:-O7A70w43_IeCuFClgZC:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/d73d0659b91c11a583636b5dbae7c792ac3355e7/multibody/tree/test/rotational_inertia_test.cc#L887)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This matrix got clobbered.
</blockquote></details>

Done
___
*[`multibody/tree/test/tree_from_joints_test.cc` line 143 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21928#-O77P64R-U0cRyoHqfDE:-O7A72xMEV4FJ1Rj4UFr:b-m3a2ch) ([raw file](https://github.com/RobotLocomotion/drake/blob/d73d0659b91c11a583636b5dbae7c792ac3355e7/multibody/tree/test/tree_from_joints_test.cc#L143)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW You are okay with the new comment arrangement here?  Ditto about 10 lines down.  I think it's fine, but borderline so wanted to check.
</blockquote></details>

Done. I found a prettier way.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21928)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
