### PR TITLE
Reduce use of Isometry3 in multibody parsing folder

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9742)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@amcastro-tri Can you please file a PR to remove the dead code?  It's a constant tax on everyone else to co-maintain it with you, if its useless.

**Comment by amcastro-tri** [comment]
I think you might have just chosen the one directory with this property, code deprecation tracked in #9781.

The code that must be migrated is the one living in `multibody/multibody_tree/`, with preference to most used APIs, I can put a list together for you. Parsing code is low in the priority list unless there is some user-facing API that takes an `Isometry3` instead of a `RigidTransform`, needless to say that for now we do not care about migrating to `RigidTransform` implementation internals of the parsers.

**Comment by jwnimmer-tri** [comment]
FYI I would defect a `using Isometry3 = drake::math::Something` shortcut, if that's what you mean.  When a user sees "Isometry3", they should be able to safely assume it means Eigen.  We should _not_ steal Eigen's names and make them be something different.

**Comment by jwnimmer-tri** [comment]
That seems like strictly more total work, to me.

**Comment by sherm1** [comment]
Agreed -- Paul has a process he's happy with. Rote change is not appropriate here in any case since the point of RigidTransform is to improve the API and impose rigor where Isometry3d lacks it. That requires at least a quick in-person check of each use case.

**Comment by jwnimmer-tri** [comment]
These files have been deleted now, on master.  This PR should probably be closed.

**Comment by mitiguy** [comment]
PR is closed because underlying files have been deleted.

**Pull request closed without merging**
