### PR TITLE
[C-IRIS] bring InitializePolytopeSearchProgram to public.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for review please, thanks!

As we discussed in slack, the user might want to construct the program to search for the C-space polytope, but with a different objective function.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-:-NNPoKDE7OmkLtPjQUlx:b-hoges7)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

Thanks for the change! 
BTW: on slack I was actually talking about making the program in the lambda `solve_small_sos` of `FindSeparationCertificateGivenPolytope` but I can get around to that soon.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-:-NNSWg-40sPQbYxu7BMG:bgo29sx)* status: missing label for release notes

**Review by hongkai-dai — COMMENTED** [review]
Oops, sorry I misunderstood our slack discussion.

I suppose you mean that we want to check if an individual pair of geometry can be certified to be collision free, for a given C-space polytope? I can add that function in a separate PR.

Do you think this PR is still worthwhile?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-:-NNSl4OXC_1dEqcCCZ2F:bm7gu36)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Yes I still think its worthwhile to expose these publically as you could imagine adding additional constraints in the future. I added one comment I thought of last night.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-:-NNXkzaG57qpHBQ2GRdL:b-x45kyd)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1723 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-NNXkd2F9t0CUuStrzjx:-NNXkd2F9t0CUuStrzjy:b5npcws) ([raw file](https://github.com/RobotLocomotion/drake/blob/c80a7991e89ecacfeec8d11af2be6d3bf2a542d7/geometry/optimization/dev/cspace_free_polytope.cc#L1723)):*
> ```cpp
> std::unique_ptr<solvers::MathematicalProgram>
> CspaceFreePolytope::InitializePolytopeSearchProgram(
>     const IgnoredCollisionPairs& ignored_collision_pairs, int C_rows,
> ```

Quick question actually: Can't you get `C_rows` from the `SeparationCertificateResult`? It's buried a bit deep but:
`separation_certificate_result -> positive_side_lagrangians -> polytope.rows()`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 1723 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-NNXkd2F9t0CUuStrzjx:-NNZ1iqu4MpCq0b0LUyo:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/c80a7991e89ecacfeec8d11af2be6d3bf2a542d7/geometry/optimization/dev/cspace_free_polytope.cc#L1723)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Quick question actually: Can't you get `C_rows` from the `SeparationCertificateResult`? It's buried a bit deep but:
`separation_certificate_result -> positive_side_lagrangians -> polytope.rows()`
</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18739#-:-NNbVX6aDF4IcqIceILW:bnfp4nl)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
