### PR TITLE
doc: Update buildcop instructions for dev failures

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275#-:-MrU0-DK2KRFTd2eWVQV:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275#-:-MrU1t35BngblYxK5d3T:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

___
*[doc/_pages/buildcop.md, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16275#-MrU1IWO3xmE0dIZOvx5:-MrU1IWO3xmE0dIZOvx6:b-wqw66e) ([raw file](https://github.com/robotlocomotion/drake/blob/c12581d64f6a5c3f2faf5e86f1c318a6c160a888/doc/_pages/buildcop.md#L46)):*
> ```Markdown
> 
> In the case of failures in a ``dev`` directory, the build cop should disable the
> failing test instead of reverting the entire commit.
> ```

nit Consider adding even more guidance here for the cop.  Something along these lines:

To disable the test, add a `tags = []` attribute to its BUILD rule.  If it only fails in certain configurations, you can add tags for just those, e.g., `"no_asan"`.  It it fails in the the default configuration or too many to configuration to list one by one, use the tag `"manual"` to disable the test under all configurations.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/_pages/buildcop.md, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16275#-MrU1IWO3xmE0dIZOvx5:-MrU3harExOQJGmXYYv0:b-4xb37t) ([raw file](https://github.com/robotlocomotion/drake/blob/c12581d64f6a5c3f2faf5e86f1c318a6c160a888/doc/_pages/buildcop.md#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider adding even more guidance here for the cop.  Something along these lines:

To disable the test, add a `tags = []` attribute to its BUILD rule.  If it only fails in certain configurations, you can add tags for just those, e.g., `"no_asan"`.  It it fails in the the default configuration or too many to configuration to list one by one, use the tag `"manual"` to disable the test under all configurations.
</blockquote></details>

Good suggestion, updated.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275#-:-MrU7DJp8oISzN-AZEBi:bybe5xg)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a typo fix

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275#-:-MrUHuq31-nhwTCrp84X:bpaxzv1)* status: 1 unresolved discussion (waiting on @BetsyMcPhail)

___
*[doc/_pages/buildcop.md, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16275#-MrUHX5g7DnWy9q6AXeH:-MrUHX5h-MXrMOI0uExJ:b-jkbanc) ([raw file](https://github.com/robotlocomotion/drake/blob/407fd84ced1f80f4235a3b41571ffd7a6d652484/doc/_pages/buildcop.md#L49)):*
> ```Markdown
> ``tags = []`` attribute to its BUILD rule. If it only fails in certain
> configurations, you can add tags for just those, e.g., "no_asan". If it fails in
> the default configuration or too many to configuration to list one by one, use the
> ```

typo: "too many to configuration" -> "too many configurations"
(also looks like the line is currently too long)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[doc/_pages/buildcop.md, line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16275#-MrUHX5g7DnWy9q6AXeH:-MrYTplq8kIIYHhHNSAN:b-4tqtz9) ([raw file](https://github.com/robotlocomotion/drake/blob/407fd84ced1f80f4235a3b41571ffd7a6d652484/doc/_pages/buildcop.md#L49)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: "too many to configuration" -> "too many configurations"
(also looks like the line is currently too long)
</blockquote></details>

Good catch, Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16275)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
