### PR TITLE
Disable IPOPT on Apple until a matlab issue is resolved there.

### PR DESCRIPTION
**Pull request by sammy-tri**
Turn off IPOPT on Mac until the issue which caused #2572 is resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2573)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-experimental-matlab/38/

**Comment by sammy-tri** [comment]
Ironically, this patch is being held up in Jenkins because all of the mac builders are doing matlab builds which are probably doomed without this patch.  Should we consider killing those builds to expedite this change?

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Why all the retests?

**Comment by sammy-tri** [comment]
Dead windows builds, mostly.

**Comment by sammy-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/experimental/2111/compiler=msvc-ninja-64,label=windows/console for one example

**Comment by ggould-tri** [comment]
+@ggould-tri platform

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-:-KKTY01RVoooIqepHnOm:-1952420227)*

**Comment by ggould-tri** [comment]
One request below (should be a one-liner, I hope).  Will LGTM once that is addressed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-KKTY8DWJ7xND9WPW6yR:-KKTY8DWJ7xND9WPW6yS:1421409014) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa5ea7d697e98e60c0e95f2ecfcdfe12dbb3041/CMakeLists.txt#L96)):*
> ```CMake
>   option(WITH_LIBBOT "simple open-gl visualizer + lcmgl for director" ON) # there is hope, but i spent a long time cleaning up c/c++ language errors trying to make msvc happy.. and still had a long way to go.
>   option(WITH_NLOPT "nonlinear optimization solver" ON)
>   if (NOT APPLE)
> ```

Please comment the reason for this (eg, a link to the issue, creating the issue if necessary) so that future us will know when it can go away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-:-KKTYMWr19KxAuQ2zK9t:518977806)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-KKTY8DWJ7xND9WPW6yR:-KKTdmWlGvT1sk9OUPis:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa5ea7d697e98e60c0e95f2ecfcdfe12dbb3041/CMakeLists.txt#L96)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Please comment the reason for this (eg, a link to the issue, creating the issue if necessary) so that future us will know when it can go away.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-KKTY8DWJ7xND9WPW6yR:-KKTewmW6T0elWTPxBX2:-1956713963) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa5ea7d697e98e60c0e95f2ecfcdfe12dbb3041/CMakeLists.txt#L96)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Done.
</details>
No change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-KKTY8DWJ7xND9WPW6yR:-KKTfND6buTIToGY07SQ:860778468) ([raw file](https://github.com/robotlocomotion/drake/blob/9fa5ea7d697e98e60c0e95f2ecfcdfe12dbb3041/CMakeLists.txt#L96)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> No change?
</details>
Done.  (for real this time)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-:-KKTgqhtrzmSKORK_rQH:-1868698381)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573#-:-KKTgwasnUfGTLEtdyaE:1417088721)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2573)*

**Pull request merged**
