### PR TITLE
[geometry] Add context validation to SceneGraph

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: https://github.com/RobotLocomotion/drake/issues/19586

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews, off-cycle.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-:-NXqdmZy2kvEmdve2AW3:bpiofc0)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
Closes: #19586 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-:-NXqdwRN1-ENbOLc3FFs:b-msjgvi)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
Jenkins is unhappy.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-:-NXqrVHl0WisjESJhnbC:b1en35a)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`geometry/test/scene_graph_test.cc` line 776 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-NXqqzQRCRf5yITtPl_K:-NXqqzQRCRf5yITtPl_L:b-649q3h) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fa6c18fa3d39878182a25d85e430d6d57482bc/geometry/test/scene_graph_test.cc#L776)):*
> ```cpp
>       scene_graph->collision_filter_manager(&ms_context),
>       ".*\n.*context-system-mismatch.*");
>   // Check updates to exercise cache entries; glass-box knowledge shows that
> ```

I'm not entirely sure what these second two test cases are for.  I assume that unless an API is public, there's no need to confirm that it protects its arguments from user mistakes, but here we're using the private SceneGraphTester.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

___
*[`geometry/test/scene_graph_test.cc` line 776 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-NXqqzQRCRf5yITtPl_K:-NXuR6x90_bBFy5MjVu-:b-bsunj5) ([raw file](https://github.com/RobotLocomotion/drake/blob/f9fa6c18fa3d39878182a25d85e430d6d57482bc/geometry/test/scene_graph_test.cc#L776)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not entirely sure what these second two test cases are for.  I assume that unless an API is public, there's no need to confirm that it protects its arguments from user mistakes, but here we're using the private SceneGraphTester.
</blockquote></details>

When I wrote the second set, I was trying to trace down whether to add ValidateContext to the const version of the internal geometry_state() accessor. My results here argue that it is not necessary for scene graph public API, so I guess I'll just remove them.

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) if you are game.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-:-NXuddU98LOhKOifIYdk:b-p3trd0)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19587#-:-NXueL2r3N-rRySVokHW:b-85g6de)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
