### PR TITLE
Add Doxygen overview for system scalar conversion

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is preparatory work for #6743.

This retroactively adds more user documentation for #6684.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6982)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.
+@sherm1 for feature and platform review, please.  Feel free to wait until tomorrow's on-call to begin.

**Comment by RussTedrake** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVtnQwZQRXGb5L6ILc:-KtVtnQwZQRXGb5L6ILd:b51hyol) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L46)):*
> ```objc
>   // Differentiate with respect to theta by setting dtheta/dtheta = 1.0.
>   auto& xc = *autodiff_context->get_mutable_continuous_state_vector();
>   xc[PendulumStateIndices::kTheta].derivatives() = Vector1d::Ones(1);
> ```

I would replace `Ones()` with `Identity()`.  Although they are obviously the same in the `Vector1d` case, `Ones` is incorrect in the vector (matrix derivatives) case... and this code might get copied / morphed by non-experts.

---

*[drake/systems/framework/system_scalar_converter.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVvSpJEYx_RRDYxVaI:-KtVvSpJEYx_RRDYxVaJ:b662epx) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_converter.h#L58)):*
> ```objc
>   /// - double
>   /// - drake::AutoDiffXd
>   /// - symbolic::Expression
> ```

odd to write drake::AutoDiffXd, but not drake::symbolic::Expression?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982)*

**Comment by sherm1** [comment]
Checkpoint.

---

Reviewed 12 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtX4xnDgxMYuhLEX8jJ:-KtX4xnDgxMYuhLEX8jK:bkkjwpa) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L2)):*
> ```objc
> //------------------------------------------------------------------------------
> /** @defgroup system_scalar_conversion System Scalar Conversion
> ```

BTW glad to have you here in the 1990's with me, Jeremy! I'm so happy to be able to review this without filtering out 200 lines of `/// `. (Hint: works in real code, too! :)

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXLGJXhTnZttXPozPN:-KtXLGJXhTnZttXPozPO:bmz5snp) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L33)):*
> ```objc
>   auto plant = std::make_unique<PendulumPlant<double>>();
>   auto context = plant->CreateDefaultContext();
>   context->FixInputPort(0, Vector1d::Zero());
> ```

BTW add: `// tau` here (took me a while to figure out where tau went)

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXM2ZzAtlUi5W_E1zL:-KtXM2ZzAtlUi5W_E1zM:b-mr4p71) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L42)):*
> ```objc
>   auto autodiff_plant = System<double>::ToAutoDiffXd(*plant);
>   auto autodiff_context = autodiff_plant->CreateDefaultContext();
>   autodiff_context->SetTimeStateAndParametersFrom(*context);
> ```

This seems to leave the `tau` input port unset. I'm surprised it works. I believe this has to be followed by:
```c++
autodiff_plant->FixInputPortsFrom(*plant, *context, autodiff_context.get());
```
(There is no reason I can see that SetTimeStateAndParametersFrom() couldn't also copy any already-fixed input ports since the values are in the cache. We should fix this asap. But better to document as-is for now.)

---

*[drake/systems/framework/system_scalar_converter.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVvSpJEYx_RRDYxVaI:-KtX87q1iaTHkpY4fmqN:b9tadzx) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_converter.h#L58)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

odd to write drake::AutoDiffXd, but not drake::symbolic::Expression?
</blockquote></details>

BTW Our in-code boilerplate for this has been `double, AutoDiffXd, symbolic::Expression` with no leading `drake::`. I think that's better since `drake::` is understood when using Drake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-:-KtXPijsXYl8mQGEMx6X:by96gdd)*

**Comment by sherm1** [comment]
Feature & platform :lgtm:. I generated the doxygen and it looked nice in Chrome. A few BTWs below.

---

Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXM2ZzAtlUi5W_E1zL:-KtXax69lXJcOkWVkMLU:b3m1xoh) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems to leave the `tau` input port unset. I'm surprised it works. I believe this has to be followed by:
```c++
autodiff_plant->FixInputPortsFrom(*plant, *context, autodiff_context.get());
```
(There is no reason I can see that SetTimeStateAndParametersFrom() couldn't also copy any already-fixed input ports since the values are in the cache. We should fix this asap. But better to document as-is for now.)
</blockquote></details>

BTW I meant to say "values are in the *context*".

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXhr89wvvrznLm_ssS:-KtXhr89wvvrznLm_ssT:b279f9y) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L137)):*
> ```objc
> 
> TODO(jwnimmer-tri) Document how to write a class hierarchy of Systems that
> support scalar conversion.
> ```

BTW consider an anonymous TBD here rather than an internal TODO with your name in it.

---

*[drake/systems/framework/test/system_scalar_conversion_doxygen_test.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXPqckvVsJK_2WKkSO:-KtXPqckvVsJK_2WKkSP:b-ekb8il) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/test/system_scalar_conversion_doxygen_test.cc#L28)):*
> ```cpp
>   auto autodiff_plant = System<double>::ToAutoDiffXd(*plant);
>   auto autodiff_context = autodiff_plant->CreateDefaultContext();
>   autodiff_context->SetTimeStateAndParametersFrom(*context);
> ```

BTW needs FixInputPortsFrom() here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-:-KtXiG-6Zl3X2ITsQPdw:bvphi49)*

**Comment by sherm1** [comment]
(Pending fix for the input ports.)

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-:-KtXih6sLPVy4zDhX3Tf:bwtkn6i)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVtnQwZQRXGb5L6ILc:-KtYqV2oQm4zTjdSXMhZ:btyvjzf) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L46)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I would replace `Ones()` with `Identity()`.  Although they are obviously the same in the `Vector1d` case, `Ones` is incorrect in the vector (matrix derivatives) case... and this code might get copied / morphed by non-experts.
</blockquote></details>

a little after I typed this, i realized that Identity is not great either (derivatives is at most a vector, never a matrix).  New recommendation: set derivatives()[0] = 1.0 instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXLGJXhTnZttXPozPN:-Ktks1PQGE_p7edvJX21:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW add: `// tau` here (took me a while to figure out where tau went)
</blockquote></details>

Done.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtXM2ZzAtlUi5W_E1zL:-KtksaNhuYL0RU73oJ07:b-pbtjr4) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I meant to say "values are in the *context*".
</blockquote></details>

Done.

It worked because the energy doesn't depend on the input at all, but you're right that we should provide the full incantation for users as an example.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVtnQwZQRXGb5L6ILc:-KtksYWfOimbdUM4YA6k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L46)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

a little after I typed this, i realized that Identity is not great either (derivatives is at most a vector, never a matrix).  New recommendation: set derivatives()[0] = 1.0 instead.
</blockquote></details>

Done.

---

*[drake/systems/framework/system_scalar_converter.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVvSpJEYx_RRDYxVaI:-KtkuYxyoQUn4GMK2vg7:b-vux2at) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_converter.h#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Our in-code boilerplate for this has been `double, AutoDiffXd, symbolic::Expression` with no leading `drake::`. I think that's better since `drake::` is understood when using Drake.
</blockquote></details>

The `AutoDiffXd` wasn't correctly hyperlinking without the `drake::`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982)*

**Comment by jwnimmer-tri** [comment]
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system_scalar_conversion_doxygen.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVtnQwZQRXGb5L6ILc:-KtpyrwoXIIcrZjGlOYd:b-xsrvvs) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_conversion_doxygen.h#L46)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done (take two) -- I think Identity().col() is actually what we want in general.

---

*[drake/systems/framework/system_scalar_converter.h, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-KtVvSpJEYx_RRDYxVaI:-Ktq-AA7yrVbxXyv6zI8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd28f34f1a5215083d5ab220d264c1220af6def3/drake/systems/framework/system_scalar_converter.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `AutoDiffXd` wasn't correctly hyperlinking without the `drake::`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6982#-:-KtrdnH5CYzKH9iyynXY:bnfp4nl)*

**Pull request merged**
