### PR TITLE
[tools] Allow repack_deb to run on a different distro

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18102)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review please.  These changes allow us to _run_ the script, but unless we can figure out a way to get it to stop running `dpkg-shlibdeps` it crashed for me trying to repackage the jammy archive from focal...  Not clear if we want this change, it seems I misremembered -- the `packages-${codename}.txt` was not the only motivator.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18102#-:-NEGpz0L5ctdEde4E-ow:b-och3e8)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
Yeah.  Given the shlibsdeps reminder, I think the safe bet here is to require that stable release Jammy debs need to be created by running on Jammy (e.g., running under Docker).  I think adding the argparse flags override will be too risky.

We'll need to do the Docker thing by hand for now, but if it's painful we could add a Staging build to be used for stable debs.

**Review by svenevs — COMMENTED** [review]
OK I pushed up the changes that would be needed to make it possible in case we want it.  I don't really know how I feel about it, but the upshot is that we'll be able to keep the existing `push_release` script more or less as is (just have it add `--codename` argument).

Doing it through docker, we'll hit the same thing.  `push_release` just does a `for distro in ["focal", "jammy"]` kind of loop.

But staging may be the smartest / most resilient plan and have those be input files instead.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18102#-:-NEHAjw86L1GxyYmc02y:b3l3sze)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail)

**Comment by BetsyMcPhail** [comment]
We're not going to implement this solution, see #17736

**Pull request closed without merging**
