### PR TITLE
Bump styleguide version to f9fb03

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7730)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@seancurtis-tri for all review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-:-L2X-UH2_08GnciLAQ1b:bvalrth)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Confirmed the commit, trusting the sha256.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-L2X0WuPPIaGNHiSuW6w:-L2X0WuPPIaGNHiSuW6x:b-sqwxgq) ([raw file](https://github.com/robotlocomotion/drake/blob/b66640198460864144912c3085677b59869cf975/WORKSPACE#L142)):*
> ```Python
>     commit = "f9fb031554d398431bc0efcb511102d41bbed089",
>     sha256 = "1e40f4595406e208de8bde66bc3425e6c0dce4ea96254cc2c7e4105316df9a31",
>     build_file = "tools/workspace/styleguide/styleguide.BUILD.bazel",  # noqa
> ```

FYI If you *really* wanted to, you could kill this `# noqa` as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-:-L2X0R2OYEbnlJGmXxIB:b-56659w)*

**Comment by ggould-tri** [comment]
Looks like the new linter actually caught something.  I will fix it in this PR at low priority.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-:-L2_UEyo4TcwfBkyfel2:b1b03x5)*

**Comment by jwnimmer-tri** [comment]
To me it just looks like the `# noqa` that got removed was in fact still required.

**Comment by ggould-tri** [comment]
Yup, you're right.  Removed the wrong one.  Surprised it passed locally -- I guess Drake doesn't lint in the default build.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[WORKSPACE, line 142 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-L2X0WuPPIaGNHiSuW6w:-L2_Yy7jIrSnna-53WBk:bl2o9em) ([raw file](https://github.com/robotlocomotion/drake/blob/b66640198460864144912c3085677b59869cf975/WORKSPACE#L142)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI If you *really* wanted to, you could kill this `# noqa` as well.
</blockquote></details>

As @jwnimmer-tri points out, this noqa is just in the wrong place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7730#-:-L2_Z1H0bi4bHUf3ANAj:bi6k6pj)*

**Comment by jwnimmer-tri** [comment]
FWIW all tests including lint should be on by default.  If you find some gap there let me know and I'll repair it.

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7730)*

**Pull request merged**
