### PR TITLE
mbp: Permit accessing geometry ports pre-Finalize()

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves an item in #9754

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9787)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Investigating failure of `//multibody/multibody_tree/multibody_plant:box_test`...

**Comment by jwnimmer-tri** [comment]
I'll also do a review.  Probably interesting enough to have two folks.

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 1636 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9787#-LPYcfkPAJoHfJSFyg0V:-LPaWSDo16so_SFuNI2q:b3bq3h7) ([raw file](https://github.com/robotlocomotion/drake/blob/5837be4da436914dfb70f61b3126cda8bd68c2b0/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L1636)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If Sean likes it, its probably just worth doing it now.  It increases the scope of the PR slightly, but does seem like its worth starting to move in this direction now.
</blockquote></details>

I would like to place it as TODO for now.

My understanding is that a non-default model value minimizes dynamic allocation.
Your suggestion, which is simpler on the allocation side, moves the population logic from allocation to computation. I'm not sure why I should simplify it for now and pay a performance penalty that we may end up wanting to resolve later?

**Comment by EricCousineau-TRI** [comment]
___
*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 1636 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9787#-LPYcfkPAJoHfJSFyg0V:-LPa_2CsD07mnbSfTnRk:blfxc1g) ([raw file](https://github.com/robotlocomotion/drake/blob/5837be4da436914dfb70f61b3126cda8bd68c2b0/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L1636)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is so much premature optimization going to in the geometry and multibody code already that its crazy.  I don't think we should micro-optimize allocations, when the APIs are not even right.

My PR is an improvement because it moves the relevant code into its final home, where the fixup is clear (changing the FKV api).  If you like, you could amend my TODO to mention that there is also a probable performance hazard.

The code (both master, and this PR in r1) is a problem because it _assumes_ that the ids populated during alloc are always present during calc --and that nobody else ever messes with the data.  That's not a valid assumption to make.  So my PR removes a correctness problem as well.

In any case, as I said though, its fine if you want to leave my PR aside and mark a TODO here, since this PR moves us more forward than back, even though its worse in some ways.  I'll just file my PR myself immediately after this PR merges in that case.
</blockquote></details>

If this is a larger issue, can we file it as such?
I would prefer to keep the code as-is, and we address at the larger level, and have the relevant discussion.

**Comment by jwnimmer-tri** [comment]
FYI Needs a rebase now.

**Comment by EricCousineau-TRI** [comment]
Done - thanks!

**Pull request merged**
