### PR TITLE
py mbp: Bind RotationalInertia and UnitInertia's ReExpress

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
For use in Anzu

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14111)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews, please! +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14111#-:-MHr_OmQDsL9hdVCMv5L:b-ec9v4s)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14111)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[bindings/pydrake/multibody/tree_py.cc, line 654 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14111#-MHragfEEIq5Ejm2G5ei:-MHragfEEIq5Ejm2G5ej:b-98k0hc) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd904a45b7ac8c95b3d8227c58ed2ca4bdc3afd/bindings/pydrake/multibody/tree_py.cc#L654)):*
> ```cpp
>         .def(py::init<const T&, const T&, const T&>(), py::arg("Ixx"),
>             py::arg("Iyy"), py::arg("Izz"), cls_doc.ctor.doc_3args)
>         .def("ReExpress", &Class::ReExpress, py::arg("R_FE"),
> ```

@amcastro-tri Do you care if I change the code / doxygen for C++ `UnitInertia::ReExpress` to use `R_AE` instead of `R_FE`?

That way, it would be consistent with `RotationalInertia` and `SpatialInertia`.

https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_rotational_inertia.html#a08eb5284c5ec57a645aee167798a1f2c
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html#a87068d58ff4a71b1d3d9795e9fed4aa6
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_unit_inertia.html#ab8231314dc085af878e5ff89cd36b40a

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: not sure if you consider the question to @amcastro-tri blocking for this PR. I'll let you push the button if you think this one is ready.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14111#-:-MHrtZWRDrUOAbyLraEO:bvel0i8)* status: 1 unresolved discussion

**Comment by EricCousineau-TRI** [comment]
I'll go ahead and make the change to the code, leave it up til tomorrow PM, then just merge it if there're no objections. It can always be reverted later if it's horrible?

**Comment by EricCousineau-TRI** [comment]
Actually, I'll just do it as a follow-up PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14111)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

___
*[bindings/pydrake/multibody/tree_py.cc, line 654 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14111#-MHragfEEIq5Ejm2G5ei:-MHsEogv1LGc7GGiOyAg:b-5azkuk) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd904a45b7ac8c95b3d8227c58ed2ca4bdc3afd/bindings/pydrake/multibody/tree_py.cc#L654)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@amcastro-tri Do you care if I change the code / doxygen for C++ `UnitInertia::ReExpress` to use `R_AE` instead of `R_FE`?

That way, it would be consistent with `RotationalInertia` and `SpatialInertia`.

https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_rotational_inertia.html#a08eb5284c5ec57a645aee167798a1f2c
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html#a87068d58ff4a71b1d3d9795e9fed4aa6
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_unit_inertia.html#ab8231314dc085af878e5ff89cd36b40a
</blockquote></details>

OK Will do as a follow-up PR. I don't think deprecation should be necessary.

**Pull request merged**
