### PR TITLE
Add and use drake_find_package macro

### LINKED ISSUE #2754: Some systems/trajectories code isn't built by jenkins
In #2743, we found a latent compile error that wasn't exposed by Jenkins.  It looks like some mex-related & blas-related & snopt-related & bullet-related trajectories code is only built conditionally, but for some reason the Jenkins builds aren't satisfying those conditions.

First, I would like to fix Jenkins so that it's covering this code.

Second, I would like to make it impossible to add built code to the tree unless the all-everything Jenkins built is covering it.  (Why isn't there a way to have the build fail, rather than downgrade its capabilities, when dependencies are unmet?)

### PR DESCRIPTION
**Pull request by jamiesnape**
If a package is not `REQUIRED`, the find will be `QUIET` by default.  Moreover if `WITH_<PACKAGE>` is set to `ON` and <PACKAGE> is not found, then a fatal error will be thrown if `FIND_PACKAGE_STRICT` is `ON` (the default).

Fixes #2754.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3718)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[CMakeLists.txt, line 238 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9SuMlhz_4NRPjzzK:-KUZ9SuMlhz_4NRPjzzL:b-4ho0s8) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/CMakeLists.txt#L238)):*
> ```CMake
>     -DDISABLE_MATLAB:BOOL=${DISABLE_MATLAB}
>     -DWITH_AVL:BOOL=${WITH_AVL}
>     -DWITH_BOT_CORE_LCMTYPES:BOOL=${WITH_BOT_CORE_LCMTYPES}
> ```

These are for completeness, even though some of them aren't used?

---

*[CMakeLists.txt, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9L7DJlmigzziANoj:-KUZ9L7EahRHxhBh9ggk:bb7r2f0) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/CMakeLists.txt#L295)):*
> ```CMake
>     swig_matlab
>     swigmake
>     textbook
> ```

why?

---

*[cmake/packages.cmake, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9pWhKKP_xioN4Pre:-KUZ9pWiTCBkdMtemam8:bny4m3a) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L11)):*
> ```CMake
> #
> #   drake_find_package(<PACKAGE> [REQUIRED] [QUIET | NO_QUIET]
> #                      [CONFIG | MODULE | PKG_CONFIG])
> ```

Please also mention somewhere that the unparsed arguments are forwarded to find_package (unless we're using PKG_CONFIG).

---

*[cmake/packages.cmake, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ8pGj2QU1pbpvBdnQ:-KUZ8pGkHNopvJRRvytt:baj2ez0) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L21)):*
> ```CMake
> #     Disable warning messages if the package cannot be found. The default for
> #     packages that are not REQUIRED.
> #   NO_QUIET
> ```

Is this actually necessary?  Doesn't seem to be used anywhere.

---

*[cmake/packages.cmake, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZB6uyclVb4IobCVaU:-KUZAvIg0OIgFuaSofZ6:b8ysbw4) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L24)):*
> ```CMake
> #     Enable messages if the package cannot be found. The default for packages
> #     that are REQUIRED.
> #   CONFIG
> ```

Is there any way we can avoid making these explicit?

---

*[cmake/packages.cmake, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZAzfl5u39dR8BYc0U:-KUZAzfl5u39dR8BYc0V:b-qp0igv) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L25)):*
> ```CMake
> #     that are REQUIRED.
> #   CONFIG
> #     Use config mode to find the package.
> ```

find_package in config mode

---

*[cmake/packages.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZB0hq48Ge4n8jqXFy:-KUZB0hq48Ge4n8jqXFz:boab1xz) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L27)):*
> ```CMake
> #     Use config mode to find the package.
> #   MODULE
> #     Use module mode to find the package.
> ```

find_package in module mode

---

*[cmake/packages.cmake, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ85CktBfKGracfSR8:-KUZ85CktBfKGracfSR9:b-oe8fjj) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L38)):*
> ```CMake
>   endif()
> 
>   if(NOT DFP_NO_QUIET AND (DFP_QUIET OR NOT DFP_REQUIRED))
> ```

So boolean.  Much complexity.  Wow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3718)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[CMakeLists.txt, line 238 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9SuMlhz_4NRPjzzK:-KUbSKSJJ5Rdhwe1mRbS:bswbon4) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/CMakeLists.txt#L238)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> These are for completeness, even though some of them aren't used?
</details>
They either are or will be. MATLAB tests use this too. Not sure people will remember to add them when they call `drake_find_package` on an external for the first time either.

---

*[CMakeLists.txt, line 295 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9L7DJlmigzziANoj:-KUbRAW55V0yulkLKhP2:b-2y0r76) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/CMakeLists.txt#L295)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> why?
</details>
It is nested in the Drake build tree, so should download before drake starts building.

---

*[cmake/packages.cmake, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9pWhKKP_xioN4Pre:-KUbRTWrBJ7lcGMmcRFg:b2nhll9) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L11)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please also mention somewhere that the unparsed arguments are forwarded to find_package (unless we're using PKG_CONFIG).
</details>
Ok.

---

*[cmake/packages.cmake, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ8pGj2QU1pbpvBdnQ:-KUbRlHhxBSl9mcsMEnj:bx9yv75) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is this actually necessary?  Doesn't seem to be used anywhere.
</details>
Allows for easier debugging, especially when you add a new package. I strongly suggest it stays.

---

*[cmake/packages.cmake, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZB6uyclVb4IobCVaU:-KUbRWJaFxvo8suRITc2:b-f4o3bj) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L24)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Is there any way we can avoid making these explicit?
</details>
They are optional, but it is better to be explicit. That is one reason you get so many warnings now when a package is not found.

---

*[cmake/packages.cmake, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ85CktBfKGracfSR8:-KUbS02lws32XjuK1F26:bojq2nd) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> So boolean.  Much complexity.  Wow.
</details>
People hate warnings on optional packages, apparently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3718)*

**Comment by david-german-tri** [comment]
:lgtm: aside from open threads requesting documentation

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-:-KUbUmDwOQAoyO6W9MiF:b-m65tid)*

**Comment by jamiesnape** [comment]
Review status: 23 of 24 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/packages.cmake, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZ9pWhKKP_xioN4Pre:-KUbajwRC2F-3tNgRGVu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Ok.
</details>
Done.

---

*[cmake/packages.cmake, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZAzfl5u39dR8BYc0U:-KUbaiqH0Uzh4b8P-Yqd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L25)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> find_package in config mode
</details>
Done.

---

*[cmake/packages.cmake, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-KUZB0hq48Ge4n8jqXFy:-KUbajACQOd13PzylwV2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6ef6856819b2138ac65e4c7e5bd786aba61c02e0/cmake/packages.cmake#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> find_package in module mode
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3718)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3718#-:-KUbeFsOeuBHd1kHSimr:bnfp4nl)*

**Pull request merged**
