### PR TITLE
Add implicit dynamics binding

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17032)

### CODE REVIEW

**Comment by AlexandreAmice** [comment]
@RussTedrake

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks

Alex can't assign reviewers, maybe @jwnimmer-tri can give him access?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17032#-:-N0XFWOu9kp51J27V00D:bxfm88m)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
Sure.  I just sent an invitation to join the https://github.com/orgs/RobotLocomotion/teams/drake_contributors group.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17032#-:-N0YUeARAwi-THrGkYt1:b-f6mqjh)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform review.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17032#-:-N0YVy0rDWHK6qGt92Fn:b-a5n9m0)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/systems/test/analysis_test.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17032#-N0YVjZG5ziLfVKXBiWk:-N0YVjZH20UZBl3M03sg:b-l803bd) ([raw file](https://github.com/robotlocomotion/drake/blob/c614a0da6d6b28aad369a419b44d3a49bfe4a971/bindings/pydrake/systems/test/analysis_test.py#L37)):*
> ```Python
>         options = RegionOfAttractionOptions()
>         options.lyapunov_candidate = x*x
>         options.state_variables = [x]
> ```

nit To test the newly-added binding and prevent a future developer from accidentally removing it, we need to exercise the `options.use_implicit_dynamics` attribute in some way from within this test case.

Even something like assigning `options.use_implicit_dynamics = False` here should suffice.  It doesn't need to probe the correctness of the bindings code (since the bindings code is rote), it just needs to confirm that the new binding has been declared in the first place.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17032)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`bindings/pydrake/systems/test/analysis_test.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17032#-N0YVjZG5ziLfVKXBiWk:-N0Ymp-LAJth9DbQOrxy:bvcn6vm) ([raw file](https://github.com/robotlocomotion/drake/blob/c614a0da6d6b28aad369a419b44d3a49bfe4a971/bindings/pydrake/systems/test/analysis_test.py#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit To test the newly-added binding and prevent a future developer from accidentally removing it, we need to exercise the `options.use_implicit_dynamics` attribute in some way from within this test case.

Even something like assigning `options.use_implicit_dynamics = False` here should suffice.  It doesn't need to probe the correctness of the bindings code (since the bindings code is rote), it just needs to confirm that the new binding has been declared in the first place.
</blockquote></details>

Done.  (I pushed the fix.)

**Comment by RussTedrake** [comment]
*[`bindings/pydrake/systems/test/analysis_test.py` line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17032#-N0YVjZG5ziLfVKXBiWk:-N0Yn8Mb3QUow5CPsTDq:bqb0ieh) ([raw file](https://github.com/robotlocomotion/drake/blob/c614a0da6d6b28aad369a419b44d3a49bfe4a971/bindings/pydrake/systems/test/analysis_test.py#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  (I pushed the fix.)
</blockquote></details>

Thanks.  I was just doing the same. ;-)

**Pull request merged**
