### PR TITLE
Global ik collision avoidance

### PR DESCRIPTION
**Pull request by hongkai-dai**
Without collision avoidance:
without_collision_avoidance

With collision avoidance:
with_collision_avoidance

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5919)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@russtedrake for feature review please. @russtedrake could you run this test on your Mac machine? Since gurobi is disabled on the CI, I cannot test this program on Mac.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiHT7Y8YIbQuo7g8V0t:b-jlq6e5)*

**Comment by RussTedrake** [comment]
small edits to comments, but otherwise it looks beautiful.  very nice.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/global_inverse_kinematics.cc, line 415 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-KiX_HGCdUApYrIo2ur0:-KiX_HGCdUApYrIo2ur1:b-3370dl) ([raw file](https://github.com/robotlocomotion/drake/blob/c3a7ff66611daac59d26058ced68410de4b247bb/drake/multibody/global_inverse_kinematics.cc#L415)):*
> ```cpp
>   AddLinearConstraint(z.cast<symbolic::Expression>().sum() == 1);
> 
>   // p_WQ can also be computed from the body pose, as p_WQ = p_WBo + R_WB * p_BQ
> ```

"can also be computed from the body pose" -> "must match the body pose"

---

*[drake/multibody/global_inverse_kinematics.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-KiXZbFe6IbY8bhL2TV_:-KiXZbFf9bngtiF069iO:bdxfos8) ([raw file](https://github.com/robotlocomotion/drake/blob/c3a7ff66611daac59d26058ced68410de4b247bb/drake/multibody/global_inverse_kinematics.h#L224)):*
> ```objc
>    * Note this approach also works if the region Pᵢ overlaps with each other.
>    * @param body_index The index of the body to on which point `Q` is attached.
>    * @param p_BQThe position of point `Q` in the body frame `B`.
> ```

missing space?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiXa5Ptr0iivpmJW-Yg:b9lhl1e)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/global_inverse_kinematics.cc, line 415 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-KiX_HGCdUApYrIo2ur0:-KiXh00BkyianuypxH4l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3a7ff66611daac59d26058ced68410de4b247bb/drake/multibody/global_inverse_kinematics.cc#L415)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"can also be computed from the body pose" -> "must match the body pose"
</blockquote></details>

Done.

---

*[drake/multibody/global_inverse_kinematics.h, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-KiXZbFe6IbY8bhL2TV_:-KiXh4tHNXJJp6cAumvt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3a7ff66611daac59d26058ced68410de4b247bb/drake/multibody/global_inverse_kinematics.h#L224)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

missing space?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919)*

**Comment by RussTedrake** [comment]
:lgtm:
(still trying to get gurobi up on my new mac, but will test when I can)

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiXhZeJxTluFnWb6j_H:b-36z0x)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiXj1R7reULaappPkJA:b-1zm1j3)*

**Comment by RussTedrake** [comment]
```
FAIL: //drake/multibody/dev:global_inverse_kinematics_collision_avoidance_test (see /private/var/tmp/_bazel_russt/3e477aa1673e9c80e91d410bb65d1970/execroot/drake-distro/bazel-out/osx-opt/testlogs/drake/multibody/dev/global_inverse_kinematics_collision_avoidance_test/test.log).
INFO: From Testing //drake/multibody/dev:global_inverse_kinematics_collision_avoidance_test:
==================== Test output for //drake/multibody/dev:global_inverse_kinematics_collision_avoidance_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from KukaTest
[ RUN      ] KukaTest.CollisionAvoidanceTest
Welding joint iiwa_joint_ee
Welding joint tool0_joint
Welding joint iiwa_joint_ee
Welding joint tool0_joint
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Optimize a model with 59425 rows, 1366 columns and 341311 nonzeros
Model has 169 quadratic constraints
Coefficient statistics:
  Matrix range    [2e-13, 2e+00]
  Objective range [0e+00, 0e+00]
  Bounds range    [5e-01, 1e+00]
  RHS range       [5e-01, 6e+00]
Presolve removed 22987 rows and 570 columns
Presolve time: 0.98s
Presolved: 36438 rows, 796 columns, 205173 nonzeros
Variable types: 575 continuous, 221 integer (221 binary)
Presolve removed 76 rows and 152 columns
Presolved: 720 rows, 37082 columns, 205741 nonzeros


Root relaxation: objective 0.000000e+00, 1887 iterations, 0.16 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.00000    0   50          -    0.00000      -     -    2s
     0     0    0.00000    0   70          -    0.00000      -     -    2s
     0     0    0.00000    0   48          -    0.00000      -     -    4s
     0     0    0.00000    0   48          -    0.00000      -     -    6s
     0     0    0.00000    0   12          -    0.00000      -     -    9s
     0     0    0.00000    0   13          -    0.00000      -     -   10s
     0     0    0.00000    0   12          -    0.00000      -     -   11s
     0     0    0.00000    0   24          -    0.00000      -     -   13s
     0     0    0.00000    0   12          -    0.00000      -     -   14s
     0     0    0.00000    0   17          -    0.00000      -     -   15s
     0     0    0.00000    0   11          -    0.00000      -     -   16s
     0     2    0.00000    0    2          -    0.00000      -     -   18s
*   16    13               3       0.0000000    0.00000  0.00%  81.9   19s

Cutting planes:
  Learned: 4
  Cover: 25
  Implied bound: 14
  Clique: 1
  MIR: 1

Explored 18 nodes (23889 simplex iterations) in 19.80 seconds
Thread count was 4 (of 8 available processors)

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0%
drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc:125: Failure
Value of: CompareMatrices(ee_pose_ik_without_collision_avoidance.translation(), ee_pos, 0.01, MatrixCompareType::absolute)
  Actual: false (Values at (0, 0) exceed tolerance: -0.73777185496079623 vs. -0.69999999999999996, diff = 0.037771854960796269, tolerance = 0.01
m1 =
-0.73777185496079623
0.024069607830211392
 0.45445787989349018
m2 =
-0.69999999999999996
                   0
 0.45000000000000001
delta=
-0.037771854960796269
 0.024069607830211392
0.0044578798934901687)
Expected: true
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Optimize a model with 59445 rows, 1474 columns and 341677 nonzeros
Model has 169 quadratic constraints
Coefficient statistics:
  Matrix range    [2e-13, 2e+00]
  Objective range [0e+00, 0e+00]
  Bounds range    [5e-01, 1e+00]
  RHS range       [5e-01, 6e+00]
Presolve removed 22993 rows and 608 columns
Presolve time: 1.00s
Presolved: 36452 rows, 866 columns, 205434 nonzeros
Variable types: 639 continuous, 227 integer (227 binary)
Presolve removed 76 rows and 152 columns
Presolved: 790 rows, 37166 columns, 206072 nonzeros


Root relaxation: objective 0.000000e+00, 1707 iterations, 0.15 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.00000    0   57          -    0.00000      -     -    3s
     0     0    0.00000    0   70          -    0.00000      -     -    3s
     0     0    0.00000    0   49          -    0.00000      -     -    6s
     0     0    0.00000    0   47          -    0.00000      -     -    8s
     0     0    0.00000    0   49          -    0.00000      -     -   10s
     0     0    0.00000    0   27          -    0.00000      -     -   14s
     0     0    0.00000    0   37          -    0.00000      -     -   16s
     0     0    0.00000    0   40          -    0.00000      -     -   18s
     0     0    0.00000    0   43          -    0.00000      -     -   23s
     0     0    0.00000    0   35          -    0.00000      -     -   24s
     0     2    0.00000    0   33          -    0.00000      -     -   27s
    16    20    0.00000    7   54          -    0.00000      -   147   30s
   224   151    0.00000   40    8          -    0.00000      -  49.6   35s
   482   228 infeasible   39               -    0.00000      -  40.7   40s
   758   287    0.00000   21   36          -    0.00000      -  39.0   45s
  1230   308    0.00000   32   26          -    0.00000      -  34.5   50s
  1629   302 infeasible   52               -    0.00000      -  31.6   55s
  2045   356 infeasible   29               -    0.00000      -  30.4   60s
  2398   366 infeasible   30               -    0.00000      -  29.5   65s
  2783   353    0.00000   30   34          -    0.00000      -  29.7   71s
  3006   372 infeasible   31               -    0.00000      -  29.7   75s
  3428   385 infeasible   33               -    0.00000      -  29.6   81s
  3729   367    0.00000   31   20          -    0.00000      -  29.7   85s
  4147   384    0.00000   27   59          -    0.00000      -  29.2   90s
  4485   472    0.00000   23   35          -    0.00000      -  29.5   96s
  4487   473    0.00000   42   72          -    0.00000      -  29.5  104s
  4488   474    0.00000   34   33          -    0.00000      -  29.4  109s
  4489   475    0.00000   21   55          -    0.00000      -  29.4  113s
  4490   475    0.00000   23   40          -    0.00000      -  29.4  116s
  4491   476    0.00000   23   38          -    0.00000      -  29.4  121s
  4492   477    0.00000    9   34          -    0.00000      -  29.4  125s
  4493   477    0.00000   10   55          -    0.00000      -  29.4  130s
  4495   479    0.00000   37   40          -    0.00000      -  29.4  136s
  4496   479    0.00000   21    6          -    0.00000      -  29.4  143s
  4497   480    0.00000   12   14          -    0.00000      -  29.4  147s
  4500   484    0.00000   16   24          -    0.00000      -  38.3  154s
  4501   485    0.00000   16   16          -    0.00000      -  38.3  156s
  4503   486    0.00000   17   33          -    0.00000      -  38.4  161s
  4505   487    0.00000   18   26          -    0.00000      -  38.5  165s
  4507   491    0.00000   19   20          -    0.00000      -  38.5  172s
  4510   491    0.00000   20   18          -    0.00000      -  38.5  178s
  4515   498    0.00000   21   53          -    0.00000      -  38.6  183s
  4522   508    0.00000   22   78          -    0.00000      -  38.9  188s
  4534   503    0.00000   23   33          -    0.00000      -  39.1  194s
  4550   513    0.00000   25   15          -    0.00000      -  40.1  200s
  4570   526    0.00000   26   31          -    0.00000      -  40.7  206s
  4591   539    0.00000   29   24          -    0.00000      -  41.6  212s
  4625   548    0.00000   35   21          -    0.00000      -  42.4  218s
  4683   568    0.00000   33   40          -    0.00000      -  43.5  224s
  4750   581    0.00000   39   34          -    0.00000      -  44.5  230s
  4803   595    0.00000   48   37          -    0.00000      -  45.9  237s
H 4895   342                       0.0000000    0.00000  0.00%  46.4  245s

Cutting planes:
  Learned: 4
  Gomory: 1
  Cover: 21
  Implied bound: 1
  Clique: 6
  GUB cover: 2
  Zero half: 1

Explored 4997 nodes (263078 simplex iterations) in 245.23 seconds
Thread count was 4 (of 8 available processors)

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0%
[  FAILED  ] KukaTest.CollisionAvoidanceTest (265542 ms)
[----------] 1 test from KukaTest (265542 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (265542 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] KukaTest.CollisionAvoidanceTest
```

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiYv77bJoJ3P6Si8dZo:b9ib0gb)*

**Comment by hongkai-dai** [comment]
Thanks for testing! Gurobi behaves differently on OSX and Linux. I will relax that tolerance.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiYxR1rHGGNsXY9Dnbm:b-kgxk3n)*

**Comment by RussTedrake** [comment]
confirmed that the test now passes on my mac (with the new tolerances)

**Comment by sammy-tri** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/dev/BUILD, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_bd4O0EuGY41WqvS0:-Ki_bd4PBjilK1CJLMx6:b-9bavyg) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/BUILD#L21)):*
> ```Python
>     ],
>     deps = [
>         "@gtest//:main",
> ```

Why did this move?  I think buildifier is going to fight you and move it back.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_c8_YoztYM_1UMxfJ:-Ki_c8_Z7Im1iPvlGXhx:b-xnd8jt) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L45)):*
> ```cpp
>   // Suppose there is a box with length 0.1m, located at [0.5, 0, 0.4]
>   // The goal is to reach the goal position, without colliding with the box
>   Eigen::Vector3d box_size(0.15, 0.15, 0.15);
> ```

It seems like the dimensions of the box here don't match the description in the comment?

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_cDfGXYM5qs3tMf76:-Ki_cDfHX-l1Nt6le36K:bwc7185) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L46)):*
> ```cpp
>   // The goal is to reach the goal position, without colliding with the box
>   Eigen::Vector3d box_size(0.15, 0.15, 0.15);
>   Eigen::Vector3d box_pos(-0.5, 0, 0.4);
> ```

The comment has 0.5 as the x position, not -0.5

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_cc5KsDZVlZVuwnM4:-Ki_cc5KsDZVlZVuwnM5:bng52oc) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L50)):*
> ```cpp
> 
>   // Now first partition the free space into 6 regions.
>   std::vector<Eigen::Matrix3Xd> region_vertices(6);
> ```

BTW populating this free space region vector is a pretty complicated API for avoiding a box in the environment, but I suppose we can add sugar later if we want.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 129 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_d5wFnkMym1BCbYHZ:-Ki_d5wFnkMym1BCbYH_:b4xvta3) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L129)):*
> ```cpp
>   int link6_idx = rigid_body_tree_->FindBodyIndex("iiwa_link_6");
>   int link5_idx = rigid_body_tree_->FindBodyIndex("iiwa_link_5");
>   std::vector<Eigen::Vector3d> link5_pts;
> ```

We've got a lot of size 1 vectors here, it seems like?  And a lot of loops over vectors which will only have a size of 1?  This seems like a strange choice, or I'm missing something.  (maybe this is for future expansion and just a comment would be OK?)

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 158 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_dXUI_xM8OaTtdTk3:-Ki_dXUI_xM8OaTtdTk4:b-q95aw2) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L158)):*
> ```cpp
>             0.06);
> 
>   // Now check to make sure the points are collision free.
> ```

Is it worth checking that the initial solution did collide to make sure that the test had an effect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919)*

**Comment by hongkai-dai** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/dev/BUILD, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_bd4O0EuGY41WqvS0:-Ki_uEE2gsFdYIH6Pj_E:bd8zly8) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/BUILD#L21)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Why did this move?  I think buildifier is going to fight you and move it back.
</blockquote></details>

Done. I do not know why it is moved. I blame Clion.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_c8_YoztYM_1UMxfJ:-Ki_uJJQcHK_WnMo1wpt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L45)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It seems like the dimensions of the box here don't match the description in the comment?
</blockquote></details>

Done.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 46 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_cDfGXYM5qs3tMf76:-Ki_uJkDNLASUbyYOCbd:b-yh10tr) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L46)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The comment has 0.5 as the x position, not -0.5
</blockquote></details>

Done. Good catch

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_cc5KsDZVlZVuwnM4:-Ki_uM0XZxcgZuizORkM:bamiv6e) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW populating this free space region vector is a pretty complicated API for avoiding a box in the environment, but I suppose we can add sugar later if we want.
</blockquote></details>

I agree in the future we can add sugar. We have some code to automatically segment the free space, but it is beyond the scope of this PR to integrate that code.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 129 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_d5wFnkMym1BCbYHZ:-Ki_uay35LUL1eM3STMw:b-6oyiy1) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L129)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

We've got a lot of size 1 vectors here, it seems like?  And a lot of loops over vectors which will only have a size of 1?  This seems like a strange choice, or I'm missing something.  (maybe this is for future expansion and just a comment would be OK?)
</blockquote></details>

You are right, it is for future expansion, to add more points on the body, so as to make sure the whole body is collision free. I just added some documentation.

---

*[drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc, line 158 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_dXUI_xM8OaTtdTk3:-Ki_v27pb4s5h2DdWQeV:b6gnsi7) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc#L158)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is it worth checking that the initial solution did collide to make sure that the test had an effect?
</blockquote></details>

That test would be brittle. If we change the global inverse kinematics implementation slightly, or even upgrade the gurobi solver, it is likely the initial solution is also collision free, since there is no constraint on the initial problem, to say the posture HAS TO collide with the box.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919)*

**Comment by jwnimmer-tri** [comment]
*[drake/multibody/dev/BUILD, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-Ki_bd4O0EuGY41WqvS0:-Ki_xHRtMB6RLsZ-iwfb:byvtyiq) ([raw file](https://github.com/robotlocomotion/drake/blob/151e074eae1a7c549e15cec1a7eae4a635880219/drake/multibody/dev/BUILD#L21)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I do not know why it is moved. I blame Clion.
</blockquote></details>

FYI #5151.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-Ki_yiVDO1ZRbmKJ9TCK:bsf2vkf)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5919#-:-KiaqaiUqMcPLr7y3t8x:b-l70wzf)*

**Pull request merged**
