### PR TITLE
[hotfix] Fix bug in MLP binding test

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Use slicing to update output variable in place.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@rpoyner-tri for both reviews please.
\cc @russtedrake FYI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443#-:-MuNRL7PBXS5dXU8wA9U:br4k30x)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[bindings/pydrake/systems/test/primitives_test.py, line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16443#-MuNWql2ASIN6rQ2_HkQ:-MuNWql2ASIN6rQ2_HkR:bzfnzg8) ([raw file](https://github.com/robotlocomotion/drake/blob/fe59f451be605a33e5c9a054f6f627ddf01ac087/bindings/pydrake/systems/test/primitives_test.py#L538)):*
> ```Python
>             global called_loss
>             called_loss = True
>             dloss_dY[:] = 1
> ```

I'm having a tough time teasing out the consequences here. I'm guessing that the old code was not effective as a test technique, but the overall test passed?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[bindings/pydrake/systems/test/primitives_test.py, line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16443#-MuNWql2ASIN6rQ2_HkQ:-MuNYEqj87Tjbl5Ul22D:b-6fl3ku) ([raw file](https://github.com/robotlocomotion/drake/blob/fe59f451be605a33e5c9a054f6f627ddf01ac087/bindings/pydrake/systems/test/primitives_test.py#L538)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm having a tough time teasing out the consequences here. I'm guessing that the old code was not effective as a test technique, but the overall test passed?
</blockquote></details>

This is a bug in the test. `dloss_dY` should act as an output parameter here, but it's not modified in place.
https://drakedevelopers.slack.com/archives/C270MN28G/p1643130367050900
This slack thread should provide some context.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443#-:-MuNYGW42w4mymlAg9X5:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443#-:-MuNZS4S1kd5Xz5HDm9z:bxgvrp6)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/systems/test/primitives_test.py, line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16443#-MuNWql2ASIN6rQ2_HkQ:-MuNYwEg3h-4pJ7bBZxi:ba29x1h) ([raw file](https://github.com/robotlocomotion/drake/blob/fe59f451be605a33e5c9a054f6f627ddf01ac087/bindings/pydrake/systems/test/primitives_test.py#L538)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is a bug in the test. `dloss_dY` should act as an output parameter here, but it's not modified in place.
https://drakedevelopers.slack.com/archives/C270MN28G/p1643130367050900
This slack thread should provide some context.
</blockquote></details>

The code is non-obvious (confusing) so needs a comment.  Perhaps:

```py
# We must be careful to update the dloss in place, rather than bind
# a new matrix to the same variable name.
dloss_dY[:] = 1
# dloss_dY = np.array(...etc...)  # <== wrong
```

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[bindings/pydrake/systems/test/primitives_test.py, line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16443#-MuNWql2ASIN6rQ2_HkQ:-MuNZaed6mYw0Soz0vNZ:bl0uak5) ([raw file](https://github.com/robotlocomotion/drake/blob/fe59f451be605a33e5c9a054f6f627ddf01ac087/bindings/pydrake/systems/test/primitives_test.py#L538)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The code is non-obvious (confusing) so needs a comment.  Perhaps:

```py
# We must be careful to update the dloss in place, rather than bind
# a new matrix to the same variable name.
dloss_dY[:] = 1
# dloss_dY = np.array(...etc...)  # <== wrong
```
</blockquote></details>

Done, thanks!
(Close one.. Just in time to block the PR :)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16443)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Pull request merged**
