### PR TITLE
Update LCM to fix Python mismatch

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Same story as #2766; just running it through CI for now. This employs a slightly different approach to resolving the issue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2775)

### CODE REVIEW

**Comment by RussTedrake** [comment]
no -- this did not resolve the issue for me.
```
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.12")
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10")
-- Found Python: /usr/local/bin/python
CMake Warning at lcm-python/CMakeLists.txt:46 (message):
  epydoc was not found; Python documentation will not be generated


-- Could NOT find Lua (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/russt/drake-distro/externals/lcm/pod-build
drake008% git status
HEAD detached at 17c38ee
nothing to commit, working directory clean
```

**Comment by mwoehlke-kitware** [comment]
That's... interesting... I would not have expected that even without the patch. Rather, I would have expected that `/usr/local` is already a searched prefix and takes precedence over `/usr`. The expected library is `/usr/local/lib/libpython2.7.dylib`?

Even more interestingly, there is *already* logic in `FindPythonLibs.cmake` to use the location of `PYTHON_EXECUTABLE` if known. I'm getting the feeling that `find_library` is rejecting the expected library for some reason...

I'm going to do some more testing...

**Comment by mwoehlke-kitware** [comment]
Ah... *Curse you trailing whitespace!!* :unamused:

Please try again :smile:; new SHA is ff03196. I was able to debug/test this on a colleague's OS X machine and it seems to be working now.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by mwoehlke-kitware** [comment]
Changes submitted to upstream: lcm-proj/lcm#85.

**Comment by mwoehlke-kitware** [comment]
lcm-proj/lcm#85 was accepted; branch has been updated accordingly and do-not-merge / do-not-review tags removed.

**Comment by RussTedrake** [comment]
this does NOT fix the problem for me.  and might have broken upstream LCM.

first of all, when did everything start getting installed to drake-distro/build/install/bin instead of drake-distro/build/bin?  I just lost an hour to that one. 

but now director cannot find lcm, failing with
```
Russs-MBP% ./install/bin/drake-visualizer
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/russt/drake-distro/build/install/lib/python2.7/dist-packages/director/drakevisualizer.py", line 3, in <module>
    from director import lcmUtils
  File "/Users/russt/drake-distro/build/install/lib/python2.7/dist-packages/director/lcmUtils.py", line 1, in <module>
    import lcm
ImportError: No module named lcm
```

upon inspection, that is because lcm is now publishing the python files to the wrong directory (notice the python. instead of python2.7):
```
-- Installing: /Users/russt/drake-distro/build/install/lib/python./site-packages/lcm/_lcm.so
-- Up-to-date: /Users/russt/drake-distro/build/install/lib/python./site-packages/lcm/__init__.py
```

i'm afraid https://github.com/lcm-proj/lcm/pull/85 probably should not have been accepted.

are you running drake-visualizer on a clean build to test these?

**Comment by david-german-tri** [comment]
> first of all, when did everything start getting installed to drake-distro/build/install/bin instead of drake-distro/build/bin? I just lost an hour to that one.

My best guess is that this a side effect of #2099 for build workflows that don't use the top-level `Makefile`.

**Comment by mwoehlke-kitware** [comment]
> first of all, when did everything start getting installed to `drake-distro/build/install/bin` instead of `drake-distro/build/bin`? I just lost an hour to that one.

Since April: 51befe39bffa.

I take it `drake-distro/build` is your build tree? If not, I don't know how your `CMAKE_INSTALL_PREFIX` would have gotten set to `drake-distro/build/install`. If yes, well, I don't recommend having `CMAKE_BINARY_DIR` and `CMAKE_INSTALL_PREFIX` be the same :smile:.

> upon inspection, that is because lcm is now publishing the python files to the wrong directory (notice the `python.` instead of `python2.7`)

Grr... lcm-proj/lcm#88.

**Comment by RussTedrake** [comment]
> first of all, when did everything start getting installed to drake-distro/build/install/bin instead of drake-distro/build/bin? I just lost an hour to that one.
> 
> Since April: 51befe3.
> 
> I take it drake-distro/build is your build tree? If not, I don't know how your CMAKE_INSTALL_PREFIX would have gotten set to drake-distro/build/install. If yes, well, I don't recommend having CMAKE_BINARY_DIR and CMAKE_INSTALL_PREFIX be the same 😄.
> 

Yes.  I am following the from source installation instructions exactly (except for not setting the build for debug mode).

Having the extra install directory might break other things (like the addpath_ scripts in matlab).  I don't know if it's been properly tested.

To be clear, we've always had the superbuilds binary dir being the install dir for the externals (the superbuild doesn't actually produce binary artifacts).  More worrisome, i think some folks' workflows have been generating files into build/bin, and others into build/install/bin

**Comment by mwoehlke-kitware** [comment]
> To be clear, we've always had the superbuilds binary dir being the install dir for the externals (the superbuild doesn't actually produce binary artifacts).

TTBOMK that has never been the case. "Traditionally", the *install* prefix was (mis)named `build` (with some bizarre and sometimes broken logic to try to "guess" where this directory should be), and the actual build directory was `pod-build`. I'm not aware that we have ever installed externals into the superbuild's `CMAKE_BINARY_DIR`.

> I am following the from source installation instructions exactly

Assuming you mean these:

    cd drake-distro
    mkdir build
    cd build
    cmake ../ -DCMAKE_BUILD_TYPE:STRING=Debug
    make

This will result in a `CMAKE_INSTALL_PREFIX` of `.../drake-distro/build/install`. Again, this has been the case since mid-April.

**Comment by RussTedrake** [comment]
Correct.  In the old system, we had drake-distro/pod-build as the binary dir and build as the install dir.  

Nite that we also have textual instructions in places which would now be inconsistent - eg in from_source and/or telling people to run build/bin/drake-visualizer.

**Comment by david-german-tri** [comment]
FYI, I can now reproduce the exact error reported in https://github.com/RobotLocomotion/drake/pull/2775#issuecomment-232505587.  I'm working on how to test lcm-proj/lcm#88, and then I'll move on to how to cover this in CI.

**Comment by david-german-tri** [comment]
I can confirm that lcm-proj/lcm#88 is a fix on my Mac.

**Comment by RussTedrake** [comment]
@mwoehlke-kitware -- please update this PR to point to your fork of lcm until it is accepted upstream, so we can test and accept this?

**Comment by RussTedrake** [comment]
Also confirmed that this works for me.  I recommend that we merge as is, and point back to lcm head as soon as possible (but in a separate PR)

---

Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2775#-:-KMvXjRYJAa-SENPVgZc:1552976633)*

**Comment by david-german-tri** [comment]
In that case, :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2775#-:-KMy7ewd3wjTyAeWrizu:-1343886477)*

**Pull request merged**
