### PR TITLE
Deprecate old names for autodiff utilities

### PR DESCRIPTION
**Pull request by sherm1**
New names for the AutoDiff utility functions were made available in #15699 and all Drake call sites were upgraded in #15615. Anzu was also updated to use the new names. However, the old names were not actually deprecated.

Now deprecate the old non-styleguide-compliant names.

_Edit: Relates to #15604._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for feature review, please

I managed to deprecate all the Python wrappers. However, one function `initializeAutoDiffTuple()` is just a Python alias to another Python function and my attempts to deprecate it are not producing a warning. (Marked with TODO(sherm1).) Please advise if you can.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875#-:-MlCw8cb9txI5WPTYg1N:b-usvxfx)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Made a start on advice; not entirely satisfied with the state of play, but got something to work.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875#-:-MlDLCCs2v1tlNxTeouG:b-tfgs1a)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15875#-MlDKpJx4Z2ylj0DXGaS:-MlDKpJy9fPES5ezDwba:b-s9r34a) ([raw file](https://github.com/robotlocomotion/drake/blob/3ca8e048620bd39f3331cd778ce5bc5a868940e6/bindings/pydrake/_autodiffutils_extra.py#L5)):*
> ```Python
> 
> import numpy as np
> from pydrake.common.deprecation import deprecated
> ```

given ramblings below, this import line would name `_warn_deprecated` instead of `deprecated`.
___
*[bindings/pydrake/_autodiffutils_extra.py, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15875#-MlDD2DG8mIyZvw-mJ0n:-MlDD2DG8mIyZvw-mJ0o:b-qhtj4x) ([raw file](https://github.com/robotlocomotion/drake/blob/3ca8e048620bd39f3331cd778ce5bc5a868940e6/bindings/pydrake/_autodiffutils_extra.py#L43)):*
> ```Python
> 
> # TODO(sherm1) This doesn't seem to produce a warning. What's wrong?
> deprecated("Use InitializeAutoDiffTuple()", date="2022-02-01")
> ```

We are in a maze of twisty passages, all @ericcousineau-tri .

The first thing that jumps out is that `deprecated` is meant to be a decorator, so should use the `@deprecated` syntax.  I tried decorator syntax with the alias, and got syntax error. I tried `@deprecated` with an actual function definition, and got further internal errors; eventually leading me to read comments about ModuleShim. My brief inquiries into ModuleShim made it seem like overkill. Instead, I got things working with an explicit call to `_warn_deprecated`:

```                                                                               |                                                                                                                        
def initializeAutoDiffTuple(*args, **kwargs):                                  |                                                                                                                        
    _warn_deprecated("Use InitializeAutoDiffTuple()", date="2022-02-01")       |                                                                                                                        
    return InitializeAutoDiffTuple(*args, **kwargs)                            |                                                                                                                        
 
```

I welcome any advice that makes any of this less opaque.

It's surprising to me that `@deprecated` doesn't work with free functions; perhaps I'm doing it wrong, or there is some other issue.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15875#-MlDD2DG8mIyZvw-mJ0n:-MlFWWWL8azQcT7adDwx:b8473zo) ([raw file](https://github.com/robotlocomotion/drake/blob/3ca8e048620bd39f3331cd778ce5bc5a868940e6/bindings/pydrake/_autodiffutils_extra.py#L43)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

We are in a maze of twisty passages, all @ericcousineau-tri .

The first thing that jumps out is that `deprecated` is meant to be a decorator, so should use the `@deprecated` syntax.  I tried decorator syntax with the alias, and got syntax error. I tried `@deprecated` with an actual function definition, and got further internal errors; eventually leading me to read comments about ModuleShim. My brief inquiries into ModuleShim made it seem like overkill. Instead, I got things working with an explicit call to `_warn_deprecated`:

```                                                                               |                                                                                                                        
def initializeAutoDiffTuple(*args, **kwargs):                                  |                                                                                                                        
    _warn_deprecated("Use InitializeAutoDiffTuple()", date="2022-02-01")       |                                                                                                                        
    return InitializeAutoDiffTuple(*args, **kwargs)                            |                                                                                                                        
 
```

I welcome any advice that makes any of this less opaque.

It's surprising to me that `@deprecated` doesn't work with free functions; perhaps I'm doing it wrong, or there is some other issue.
</blockquote></details>

Ah, yup. `@deprecated` was designed for *descriptors*. Sorry for that being unclear / twisty.

This one should be hoisted:
https://github.com/RobotLocomotion/drake/blob/7f2d507a576a2375cd17a4d29236c6c619bf9e77/bindings/pydrake/common/deprecation.py#L237-L247

Will file brief PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15875#-MlDD2DG8mIyZvw-mJ0n:-MlFaiHWC6j33A8Zh8bX:beq6ikj) ([raw file](https://github.com/robotlocomotion/drake/blob/3ca8e048620bd39f3331cd778ce5bc5a868940e6/bindings/pydrake/_autodiffutils_extra.py#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, yup. `@deprecated` was designed for *descriptors*. Sorry for that being unclear / twisty.

This one should be hoisted:
https://github.com/RobotLocomotion/drake/blob/7f2d507a576a2375cd17a4d29236c6c619bf9e77/bindings/pydrake/common/deprecation.py#L237-L247

Will file brief PR.
</blockquote></details>

See #15877

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/_autodiffutils_extra.py, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15875#-MlDD2DG8mIyZvw-mJ0n:-MlGEKzxAQMse4LO-ctz:bbszr4p) ([raw file](https://github.com/robotlocomotion/drake/blob/3ca8e048620bd39f3331cd778ce5bc5a868940e6/bindings/pydrake/_autodiffutils_extra.py#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

See #15877
</blockquote></details>

Rest of the thing looks good. Are we going to wait for #15877 and rebase/rework on top of it?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875#-:-MlH6daI6mxoJVYdTn2L:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @sherm1)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 4 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15875#-:-MlLCn1O6sIIONo7YOo6:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @sherm1)

**Pull request merged**
