### PR TITLE
Bind RigidBodyTree::geometricJacobian().

### PR DESCRIPTION
**Pull request by avalenzu**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8624)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@ericcousineau-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-:-LAOMz5d6egLY6q4sGnr:b-7eskas)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items

BTW Some `pycodestyle` checks are failing on the test file.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 143 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-LAORu7x5thKIsZYDTgn:-LAORu7x5thKIsZYDTgo:b-fd6z94) ([raw file](https://github.com/robotlocomotion/drake/blob/66c5f394f233c398eef65429ad5bc3dbcedf5e37/bindings/pydrake/multibody/rigid_body_tree_py.cc#L143)):*
> ```cpp
>                cache, base_body_or_frame_ind, end_effector_body_or_frame_ind,
>                expressed_in_body_or_frame_ind, in_terms_of_qdot, &v_indices);
>            return std::make_pair(J, v_indices);
> ```

Rather than `std::make_pair`, can you just return `py::make_tuple`? (which would avoid additional type casting on Pybind's side)

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 90 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-LAORHQ4-cqkerGHPG8F:-LAORHQ6EARfYukFaqDR:b-9uczp0) ([raw file](https://github.com/robotlocomotion/drake/blob/66c5f394f233c398eef65429ad5bc3dbcedf5e37/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L90)):*
> ```Python
>         self.assertEqual(tree.number_of_velocities(), num_v)
> 
>         np.set_printoptions(linewidth=120, formatter={'float_kind':lambda x: "% .2f" % x})
> ```

BTW Can you add a space on the right side of `:` for the dictionary entry?

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 90 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-LAORPqrASgAXwiPyorM:-LAORPqrASgAXwiPyorN:br26xcc) ([raw file](https://github.com/robotlocomotion/drake/blob/66c5f394f233c398eef65429ad5bc3dbcedf5e37/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L90)):*
> ```Python
>         self.assertEqual(tree.number_of_velocities(), num_v)
> 
>         np.set_printoptions(linewidth=120, formatter={'float_kind':lambda x: "% .2f" % x})
> ```

Given that this is a global setting that shouldn't be changed by `unittest`s running, can you just set this at the top of the test file, to ensure that the side effects are invariant of if/when a test is executed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-:-LAOS4k8CmrauPgadO32:bxbu5zh)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624)*

**Comment by soonho-tri** [comment]
:lgtm:, tested on :apple: as well.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8624#-:-LATX0tN4lY94GVdjqPU:bioy6yj)*

**Pull request merged**
