### PR TITLE
[solvers] Upgrade to Mosek 9.3.20

### PR DESCRIPTION
**Pull request by RussTedrake**
As proposed in #17237.

Note: I did check all of the links.  (Even the non-link that says the documentation from 8.1 disappeared).
+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri -- assuming that @hongkai-dai confirms this is compatible with TRI's current license.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238#-:-N2WmSf2DcTdnfJVBgO1:b-b0gs3e)* status: LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Unfortunately TRI's mosek license doesn't support Mosek 9.3. A few weeks ago I have asked IT to upgrade the Mosek license, but they got busy with Woven transition. I will ping them again.

> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238#-:-N2X0QYy2SWzC6n-Hy2s:b-evguci)* status: LGTM missing from assignee hongkai-dai (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238)* status: LGTM missing from assignee hongkai-dai (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238#-:-N2Xoxj403za7yDiQ9Ew:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
@hongkai-dai kindly said that he's ok with Mosek on a branch until IT does the upgrade, and recommended I merge.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17238#-:-N2XpGYWAAjC4N1wuP5e:bhqtgs)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
