### PR TITLE
Add support for macOS Big Sur 11.x

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #13648. Will close out the issue once all the continuous and nightly Jenkins jobs are created and running.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14632)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-debug please
@drake-jenkins-bot mac-big-sur-clang-cmake-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-cmake-experimental-release please

**Comment by jwnimmer-tri** [comment]
___
*[doc/developers.rst, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14632#-MT81dzr8tMK0R-YfOS8:-MT81dzr8tMK0R-YfOS9:bikp5jf) ([raw file](https://github.com/robotlocomotion/drake/blob/e9d8d8677024386d633f9f19c9802d0dee38754b/doc/developers.rst#L88)):*
> ```reStructuredText
> |                                  |       |       | | Clang 9           |                   |        |
> +----------------------------------+       +-------+---------------------+-------------------+        |
> | macOS Catalina (10.15)           |       | 3.19  | | Apple LLVM 12.0.0 | | AdoptOpenJDK 15 |        |
> ```

nit As best I can tell, both provisioned and unprovisioned macOS CI is running bazel 4.0.0 now from homebrew, not 3.7.  Possibly worth changing that here as part of this PR?

**Review by jamiesnape — COMMENTED** [review]
`//examples/manipulation_station:end_effector_teleop_sliders_test` still causing issues. Fixed the `tcl-tk` issue with it, but looks like this issue may be of our own making.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14632#-:-MT82OlfE40PrtrI_JJ8:b-z3f2ei)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[doc/developers.rst, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14632#-MT81dzr8tMK0R-YfOS8:-MT828yy0vxH_ZLN6acg:bxoamxj) ([raw file](https://github.com/robotlocomotion/drake/blob/e9d8d8677024386d633f9f19c9802d0dee38754b/doc/developers.rst#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit As best I can tell, both provisioned and unprovisioned macOS CI is running bazel 4.0.0 now from homebrew, not 3.7.  Possibly worth changing that here as part of this PR?
</blockquote></details>

It would be, yes. I will certainly change that. Looks like one failing test, though, so still make to go.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Comment by jamiesnape** [comment]
We are good with CMake (Release and Debug), ASan, and Bazel Debug. Just Bazel Release with issues.

**Comment by jwnimmer-tri** [comment]
FYI I'd be okay if you'd prefer to mark that test as expected-fail for now and then land this, in order to capture and hold this progress vs any new pull request's possible regressions.

**Comment by jamiesnape** [comment]
Probably so, that is a non-obvious failure to me at the moment, and plenty of people are waiting on this to upgrade their Macs:
```
FAIL: //examples/manipulation_station:end_effector_teleop_sliders_test
==================== Test output for //examples/manipulation_station:end_effector_teleop_sliders_test:
Traceback (most recent call last):
  File ".../bazel-out/darwin-opt/bin/examples/manipulation_station/end_effector_teleop_sliders_test.runfiles/drake/examples/manipulation_station/end_effector_teleop_sliders.py", line 10, in <module>
    from pydrake.examples.manipulation_station import (
ImportError: ImportError: ImportError: ImportError: C++ type is not registered in pybind: NSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE
================================================================================
```
I think `NSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE` is basically `std::string`, which should be registered?

**Comment by jwnimmer-tri** [comment]
That teleop uses `Tk`, which I think has been a problem on homebrew recently?  Anyway, IIRC there are two `std::string` ABIs (C++03, C++11) so it's possible there's a string-ABI problem biting us through dynamic loading with Tk somehow.

**Comment by jamiesnape** [comment]
Yes, I might have fixed one issue and caused another.

**Comment by jamiesnape** [comment]
We do not have a particularly elegant way to skip a smoke test on a particular OS and version? The ugly way I have is within the Python, check the OS version (which is also ugly in Python) and then `sys.exit(0)`.

**Comment by jwnimmer-tri** [comment]
Right, that's one of the reasons why I dislike the `add_test_rule` style in the first place.  It's an easy way to be lazy and bootstrap a test, but it tends to make the longer-term sustaining work more difficult.

Anyway, if you check `end_effector_teleop_dualshock4.py` in the same folder, it has a darwin exemption already.  I'd say we should use the same for `..._teleop_sliders` -- an inline Python check, as you mention.  That has the benefit that _both_ the program _and_ its test will be disabled on Big Sir, which is actually want we want -- if it's not tested in CI, we should pretend that its working.

**Comment by jamiesnape** [comment]
Yes, my "solution" looks about that bad. Not even going to try the import, though, since there is not much the user can do. If a passing Pythonista has a better way of checking for Big Sur than `int(platform.release().split(".")[0]) >= 20` (or something even worse with `platform.mac_ver`, I would love to know. Maybe I just disable for all Darwin and feel sad.

**Comment by jamiesnape** [comment]
I will create an issue before I merge this.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+(status: commits are properly curated)

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature assuming CI likes it.

+@ggould-tri for platform review per schedule, please.  Note the docs change which will need to merge into the md flavor later on.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14632#-:-MTDHIFi-V32wc97T3WH:b-hvez67)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Comment by jamiesnape** [comment]
CI is already happy; do not think there is any reason to think that has changed, but continuous Big Sur will probably not start in production just in case.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; I will manually update #14612 when this PR lands.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14632#-:-MTGD1-X3BwPHNc22r0E:bi7jg5g)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
