### PR TITLE
throws a runtime error in GetSolution is the variable is not found

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5287)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@rdeits for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-:-KdgSF4YxFoWhY2LnWwx:b-o6l8os)*

**Comment by rdeits** [comment]
:lgtm: thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-:-KdgSqpaqe89KcHWL7Ct:brfqlux)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-:-KdgSxZsua4vNGdZBq6I:b-trzqz1)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-:-Kdgs8aQ1BY0kvAef8JR:b-iahtjr)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 972 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-KdgyvklpJFewMPFX12m:-KdgyvkmgGka8lE3Io7D:bgr7lro) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf763e2385fd2bef19e524987fb3383af5088a3/drake/solvers/mathematical_program.cc#L972)):*
> ```cpp
>     oss << var << " is not a decision variable in the mathematical program, "
>                   "when calling GetSolution."
>         << std::endl;
> ```

BTW two things:
(1) I think it is unusual for a one-line exception message to embed a newline at the end; but if you decide to keep a newline then:
(2) `endl` means "please flush this stream so the user can see it" which doesn't make sense for exception text; you just want `\n` if all you need is a line break.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-:-Kdh-1a3s8qnX4em8eUE:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 972 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5287#-KdgyvklpJFewMPFX12m:-KdhARcs3B0nxBGiXxxT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf763e2385fd2bef19e524987fb3383af5088a3/drake/solvers/mathematical_program.cc#L972)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW two things:
(1) I think it is unusual for a one-line exception message to embed a newline at the end; but if you decide to keep a newline then:
(2) `endl` means "please flush this stream so the user can see it" which doesn't make sense for exception text; you just want `\n` if all you need is a line break.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5287)*

**Pull request merged**
