### PR TITLE
Rename "@xxx/:lib" labels

### PR DESCRIPTION
**Pull request by jamiesnape**
See, in part, https://github.com/RobotLocomotion/drake/pull/6028#issuecomment-300176547 for context. Also makes https://github.com/RobotLocomotion/drake/pull/6072 a little more tractable for the few shared objects that we need.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6075)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
:lgtm: conceptually, I only skimmed it.

+@soonho-tri for platform review -- can you please review line by line to catch any typos?  Also make sure buildifier likes it?

---

Review status: 0 of 48 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6075#-:-KjsibNF_hOm2W10dme3:b-lcbf4m)*

**Comment by soonho-tri** [comment]
:lgtm: 

> Also make sure buildifier likes it?

`tools/buildifier` only sorts a few files, no significant changes at all.

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6075#-:-KjtCy8E8S6R0jojZF4c:b-p4z8ef)*

**Pull request merged**
