### PR TITLE
Add show_model helper utility 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8856)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@avalenzu for feature review, please?  This is mean to be a more generic (but slightly less capable) version of some helpers you've shared with me.  Apparently, nothing like this exists on Drake master, so it seemed worth adding this as a user convenience here directly.

**Comment by avalenzu** [comment]
:lgtm: +@seancurtis-tri for platform review.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8856#-:-LDCtCpSDVo9_sWA5m9m:b362zgh)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with one passing remark

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[manipulation/util/show_model.py, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8856#-LDCw-NG2rtJ8WPKe1lm:-LDCw-NG2rtJ8WPKe1ln:b-o7bzfb) ([raw file](https://github.com/robotlocomotion/drake/blob/38f2e6fa40cc01da62dc032f590ce32a16b362b8/manipulation/util/show_model.py#L16)):*
> ```Python
>     RigidBodyTree,
> )
> from pydrake.lcm import DrakeLcm
> ```

BTW Should these be alphabetized?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8856#-:-LDCwTocEtKCS92462ve:bvuim50)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/util/show_model.py, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8856#-LDCw-NG2rtJ8WPKe1lm:-LDCxAbMCl_OrcW7eFCS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38f2e6fa40cc01da62dc032f590ce32a16b362b8/manipulation/util/show_model.py#L16)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Should these be alphabetized?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8856)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8856)*

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI please don't squash my PRs (unless there is a curate tag).

**Comment by SeanCurtis-TRI** [comment]
Sorry - that was a thoughtless act. I usually don't merge other people's PRs. It seems I'm best served by sticking to that policy.

**Pull request merged**
