### PR TITLE
Updates SpringMassSystem to override AllocateOutputVector instead of AllocateOutput.

### PR DESCRIPTION
**Pull request by liangfok**
Might as well make use of the API sugar now that it exists.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4674)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for feature review as dynamics team lead.
+@sammy-tri for platform review since it's Wednesday.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4674#-:-K_drCLWZRSi0jKz0JEI:b-6lihmh)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4674)*

**Comment by sherm1** [comment]
Feature review: :lgtm: -- thanks, Liang.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4674#-:-K_eQj4F1nMObyMs0aT7:bgio5lz)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4674#-:-K_eRiwttAg1DadQVyec:bnfp4nl)*

**Pull request merged**
