### PR TITLE
(WIP) [geometry] refine_mesh warns too small tetrahedral volume

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Experiment with ideas to give a warning if refine_mesh creates a very flat tetrahedron.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20934)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20934)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20934#-NqVLZWC6lzPfgp3mtFt:-NqVLZWD5m3XLFB_VXlP:b-nogbvf) (no related file):*
@dmcconachie-tri I'm experimenting with a warning message "...has very low minimum volume..." like this:
```
bazel-bin/geometry/proximity/refine_mesh test.vtk out.vtk
[2024-02-12 18:41:59.794] [console] [info] Found 533 bad tets, 870 bad triangles, and 333 bad edges.The mesh has 619 tets and 244 vertices.
[2024-02-12 18:41:59.794] [console] [warning] The 502-th tetrahedron (0-based index) has very low minimum volume 2.9443585058925387e-16 m^3 less than 1e-14 m^3. Its centroid is at (0.02232522375, -0.01069999725, 0.0048093993750000005).
[2024-02-12 18:41:59.974] [console] [info] wrote refined mesh to file 'out.vtk' with 2433 tets and 579 vertices.
[2024-02-12 18:41:59.974] [console] [warning] The 2412-th tetrahedron (0-based index) has very low minimum volume 1.2123193575781052e-16 m^3 less than 1e-14 m^3. Its centroid is at (0.019562503125000002, 0.003936035875, 0.006435730650000001).
```

Is it too much or too little?

___

**Review by dmcconachie-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20934)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20934#-NqVLZWC6lzPfgp3mtFt:-NqdW0iy7FjE9RhqZZ63:b5lqd69) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@dmcconachie-tri I'm experimenting with a warning message "...has very low minimum volume..." like this:
```
bazel-bin/geometry/proximity/refine_mesh test.vtk out.vtk
[2024-02-12 18:41:59.794] [console] [info] Found 533 bad tets, 870 bad triangles, and 333 bad edges.The mesh has 619 tets and 244 vertices.
[2024-02-12 18:41:59.794] [console] [warning] The 502-th tetrahedron (0-based index) has very low minimum volume 2.9443585058925387e-16 m^3 less than 1e-14 m^3. Its centroid is at (0.02232522375, -0.01069999725, 0.0048093993750000005).
[2024-02-12 18:41:59.974] [console] [info] wrote refined mesh to file 'out.vtk' with 2433 tets and 579 vertices.
[2024-02-12 18:41:59.974] [console] [warning] The 2412-th tetrahedron (0-based index) has very low minimum volume 1.2123193575781052e-16 m^3 less than 1e-14 m^3. Its centroid is at (0.019562503125000002, 0.003936035875, 0.006435730650000001).
```

Is it too much or too little?
</blockquote></details>

When I was inspecting these previously I was regularly doing math to figure out what line number "the 2412-th tet" corresponded to. If practical perhaps output the line number or something searchable within the input/output files? For example the vertex list for that tet with the appropriate spaces? Something like `  48   1135     47     33`? Presumably that is unique?

I don't know what I would do with the centroid information without an extra affordance to draw that point inside the mesh in some way. Maybe I would use it to do exactly that in a notebook or something similar.

___

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20934)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20934#-NqVLZWC6lzPfgp3mtFt:-NqdYFww1HCLOB4ipQmw:bca7htr) (no related file):*
<details><summary><i>Previously, dmcconachie-tri (Dale McConachie) wrote…</i></summary><blockquote>

When I was inspecting these previously I was regularly doing math to figure out what line number "the 2412-th tet" corresponded to. If practical perhaps output the line number or something searchable within the input/output files? For example the vertex list for that tet with the appropriate spaces? Something like `  48   1135     47     33`? Presumably that is unique?

I don't know what I would do with the centroid information without an extra affordance to draw that point inside the mesh in some way. Maybe I would use it to do exactly that in a notebook or something similar.
</blockquote></details>

What is the significance of `1e-14`? Is that a minimum threshold of sorts?

___

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy What's the plan for proceeding with this PR?  Is this something we aim to return to soon, or else we should close it until we do.

**Comment by DamrongGuoy** [comment]
Thanks for asking @jwnimmer-tri. I won't return to this PR yet.  I'll close it for now.

**Pull request closed without merging**
