### PR TITLE
Bind copyability of schema types

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+(release notes: yes)
+@jwnimmer-tri is this the correct idiom?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261#-:-MrNxMtQBGF8lH_S8fQU:bbto728)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Yup!

:lgtm: both.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261#-:-MrO2Ax91oDWrqNXEdem:b64up9n)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri)

___
*[bindings/pydrake/common/test/schema_test.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16261#-MrO2G5V56uYWkKhdjma:-MrO2G5V56uYWkKhdjmb:bbikcoo) ([raw file](https://github.com/robotlocomotion/drake/blob/78656e910a9207c24996879d5a17db55a0002254/bindings/pydrake/common/test/schema_test.py#L15)):*
> ```Python
>         self.assertIsInstance(dut, mut.Distribution)
>         copy.copy(dut)
>         copy.deepcopy(dut)
> ```

This code is slightly at odds with this helper method's docstring.

The abstract base class's "base methods" do not offer any help for copy-ability.  However, we expect that all concrete subclasses must be copyable.  Changing the docstring to clarify this should suffice.

Ditto for similar docstrings, throughout.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/common/test/schema_test.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16261#-MrO2G5V56uYWkKhdjma:-MrO5XURD50W5LQb8wqY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/78656e910a9207c24996879d5a17db55a0002254/bindings/pydrake/common/test/schema_test.py#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This code is slightly at odds with this helper method's docstring.

The abstract base class's "base methods" do not offer any help for copy-ability.  However, we expect that all concrete subclasses must be copyable.  Changing the docstring to clarify this should suffice.

Ditto for similar docstrings, throughout.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261)* status: needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16261#-:-MrOUUs-972P5BPLgssi:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @ggould-tri)

**Pull request merged**
