### PR TITLE
Add pygame to setup scripts

### PR DESCRIPTION
**Pull request by jamiesnape**
For [drake/automotive/steering_command_driver.py](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/steering_command_driver.py#L13).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6789)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Oops, sorry I overlooked this in #6719.  :lgtm: for ubuntu parts.

+@soonho-tri for feature review of the mac change, please.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6789#-:-Kr19VAypA_jwSaePjvl:bb0gf5u)*

**Comment by soonho-tri** [comment]
mac :lgtm: 

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6789#-:-Kr1DdLuJvzpnWXHQyyJ:b-j3cc82)*

**Comment by jwnimmer-tri** [comment]
I think we can count us as platform review, without bothering Sherm.

**Comment by soonho-tri** [comment]
@jamiesnape , FYI, I think http://drake.mit.edu/development_on_osx.html#pygame section can be purged as we include `pygame` in the `install_prereqs.sh` script.

**Comment by jamiesnape** [comment]
Ok, I will PR something doing that momentarily.

**Comment by jamiesnape** [comment]
#6815

**Pull request merged**
