### PR TITLE
Refactor symbolic::Monomial class

### PR DESCRIPTION
**Pull request by soonho-tri**
- Use `Variable → int` instead of `Variable::Id → int` as an internal representation.
 - Add `Monomial::operator*=(const Monomial&)`.
 - Re-implement `Monomial::operator==`.
 - Add `pow(Monomial, Monomial)`.
 - Add more tests. (100% coverage for Monomial class)

Related issue: #6218.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6275)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@fischergundlach , feature-review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-:-Km2gqMmLWcdrMnCNcZn:b7qk0pt)*

**Comment by soonho-tri** [comment]
+@hongkai-dai , another feature-review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-:-Km2tOD4V_kl3kolTSNh:b-2xw504)*

**Comment by FischerGundlach** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km2g_SjATAGVwAt2BtO:-Km2g_Skbyt_Em3voa9d:b-8uh0vv) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.cc#L52)):*
> ```cpp
>   } else if (is_constant(e)) {
>     throw runtime_error(
>         "A constant not equal to to 1, this is not a monomial.");
> ```

to to -> to

---

*[drake/common/monomial.cc, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km2i6qdVT_3DkK_XYlO:-Km2i6qeF15cHiwFUKFC:b6awap6) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.cc#L100)):*
> ```cpp
>     const int exponent{p.second};
>     if (exponent > 0) {
>       powers_.insert(p);
> ```

Maybe it is good to catch the return of `insert(p)` to make sure that nothing was overwritten. For example, if someone passes the map `p` with `p[0] = <x,1>` and `p[1]=<x,1>`instead of  `p[0] = <x,2>`. Or add documentation to it, which says that it is prohibited.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 100 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km2i6qdVT_3DkK_XYlO:-Km36fvywOu95PmUWjiq:b-b4vlhb) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.cc#L100)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

Maybe it is good to catch the return of `insert(p)` to make sure that nothing was overwritten. For example, if someone passes the map `p` with `p[0] = <x,1>` and `p[1]=<x,1>`instead of  `p[0] = <x,2>`. Or add documentation to it, which says that it is prohibited.  
</blockquote></details>

We have `p : pair<Variable, int>` from `map<Variable, int>`. As a result, we have: `i ≠ j => pᵢ.first ≠ pⱼ.first`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km2g_SjATAGVwAt2BtO:-Km3GGyw_GkH8mBn39NS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.cc#L52)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

to to -> to
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by soonho-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/monomial.cc, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km3R4zL4QQEUgoSeVTR:-Km3R4zL4QQEUgoSeVTS:b-801djw) ([raw file](https://github.com/robotlocomotion/drake/blob/569222e4ce7335692f590d1680e2be8a996fd6ce/drake/common/monomial.cc#L119)):*
> ```cpp
> 
> bool Monomial::operator==(const Monomial& m) const {
>   // TODO(soonho-tri): simplify this function to `return powers_ == m.powers_`.
> ```

FYI, https://github.com/RobotLocomotion/drake/pull/6281 addresses the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by hongkai-dai** [comment]
Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/monomial.h, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km348pKm8XqKoBrkHrT:-Km348pKm8XqKoBrkHrU:b-uaaagm) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.h#L220)):*
> ```objc
>  */
> template <int rows>
> Eigen::Matrix<Expression, rows, 1> ComputeMonomialBasis(const Variables& vars,
> ```

Do you plan to change the return type to `Eigen::Matrix<Monomial, rows, 1>` in the future?

---

*[drake/common/test/monomial_test.cc, line 460 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km3Ta9KaESJBtVynEyC:-Km3Ta9KaESJBtVynEyD:b-kzl3eh) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/test/monomial_test.cc#L460)):*
> ```cpp
> // x^0 is a monomial (1).
> TEST_F(MonomialTest, ToMonomial7) {
>   const Monomial m1(var_x_, 0);
> ```

Maybe add `m3{pow(x_, 0)}` here?

---

*[drake/solvers/test/mathematical_program_test.cc, line 1930 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km3Y3zwwaAL8KWytnZC:-Km3Y3zwwaAL8KWytnZD:biy1ju) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/solvers/test/mathematical_program_test.cc#L1930)):*
> ```cpp
> // → Variable). Consider an example where monomial is "x³y⁴" and var_id_to_var
> // is {x.get_id() ↦ z, y.get_id() ↦ w}. We have transform(x³y⁴, {x.get_id() ↦ z,
> // y.get_id() ↦ w}) = z³w⁴.
> ```

Should we add a check to exclude the chain `{x.get_id() -> y, y.get_id() -> z}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by soonho-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/monomial.h, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km348pKm8XqKoBrkHrT:-Km3cB1BkoWJszpeSFhc:b-8ywm84) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.h#L220)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you plan to change the return type to `Eigen::Matrix<Monomial, rows, 1>` in the future?
</blockquote></details>

Done (added a TODO). 

I'll open another PR to make `symbolic::Monomial` compatible with `Eigen::Matrix`. I'll resolve this TODO in the same PR.

---

*[drake/common/test/monomial_test.cc, line 460 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km3Ta9KaESJBtVynEyC:-Km3cehXRNksYXpjhKka:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/test/monomial_test.cc#L460)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe add `m3{pow(x_, 0)}` here?
</blockquote></details>

Done.

---

*[drake/solvers/test/mathematical_program_test.cc, line 1930 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km3Y3zwwaAL8KWytnZC:-Km3lOPeWxafPez1-GMz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/solvers/test/mathematical_program_test.cc#L1930)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we add a check to exclude the chain `{x.get_id() -> y, y.get_id() -> z}`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-:-Km4L4tHq-CRn8YqYL69:bnfp4nl)*

**Comment by FischerGundlach** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-:-Km6y2sTi_nN8euSLuKI:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km2g_SjATAGVwAt2BtO:-Km6yOcNN-ALeLs_hqqj:b-fvtpo4) ([raw file](https://github.com/robotlocomotion/drake/blob/0892661410efc8d3df6c55578703165844ef5033/drake/common/monomial.cc#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@fischergundlach , could you check the change and resolve this discussion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/monomial.cc, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km78ErUlK5UUZFLhhyg:-Km78ErUlK5UUZFLhhyh:bgkhlr7) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.cc#L60)):*
> ```cpp
>     const double exponent_val = get_constant_value(exponent);
>     powers = ToMonomialPower(get_first_argument(e));
>     // pow(pow(xᵢ, kᵢ), n) = pow(xᵢ, kᵢ * n)
> ```

FYI It seems like this could be an Expression simplification rule already?

---

*[drake/common/monomial.cc, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km78UIfDHkoR4YKb0kL:-Km78UIfDHkoR4YKb0kM:bbjmwbd) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.cc#L62)):*
> ```cpp
>     // pow(pow(xᵢ, kᵢ), n) = pow(xᵢ, kᵢ * n)
>     for (auto& p : powers) {
>       p.second *= exponent_val;
> ```

FYI Consider making the double->int conversion of exponent_val explicit to readers?

---

*[drake/common/monomial.h, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75XeIP_xxy4Hv_jNj:-Km75XeIP_xxy4Hv_jNk:boyusht) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L25)):*
> ```objc
> 
> /** Represents a monomial, a product of powers of variables with non-negative
>  * integer exponents.
> ```

FYI I guess feature review was okay losing the "Note that it does not include the coefficient part" statement?  I guess I can go along with that.

(Losing the map representational detail was fine, of course.)

---

*[drake/common/monomial.h, line 92 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75oHuyTwZt32PhkPQ:-Km75oHuyTwZt32PhkPR:b8c0a6u) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L92)):*
> ```objc
> 
>   /** Returns this monomial raised to @p p.
>    * @throws if @p is negative.
> ```

FYI _Meta_ Did you check if this formats correctly?  I would expect it to need `exception` after `@throws`, but maybe not.

---

*[drake/common/monomial.h, line 94 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75yOOwyV5maJrQEg9:-Km75yOOwyV5maJrQEgA:b-w0d2qf) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L94)):*
> ```objc
>    * @throws if @p is negative.
>    */
>   Monomial& pow(int p);
> ```

Wait, what?  A member function named `pow` mutates  _this_?  I would have expected a fresh result, given that name.  Maybe change this to `pow_assign` or `raise_to_pow` or `exponentiate` or something, and/or don't `return this;` so that call sites are obviously just `my_mono.exponentiate(2);`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/monomial.h, line 94 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75yOOwyV5maJrQEg9:-Km7kAeYtDzV93heHW7z:b8crnvb) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Wait, what?  A member function named `pow` mutates  _this_?  I would have expected a fresh result, given that name.  Maybe change this to `pow_assign` or `raise_to_pow` or `exponentiate` or something, and/or don't `return this;` so that call sites are obviously just `my_mono.exponentiate(2);`?
</blockquote></details>

(FWIW -- My subconscious just suggested `pow_in_place` as a good name.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/monomial.cc, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km78ErUlK5UUZFLhhyg:-KmCLUQLu5vgYe3UpbgJ:b9wqkx1) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.cc#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI It seems like this could be an Expression simplification rule already?
</blockquote></details>

Yes, given a symbolic expression `e = pow(base, n)`, it is the case that `base` is not in the form of `pow` because of the simplification in symbolic expression.

Here what we're doing is to convert `base` into a monomial `∏ᵢ xᵢ` and process `(∏ᵢ xᵢ)^n` into `∏ᵢ (xᵢ^n)`. A way to take care of this case at once is to extend this function, `ToMonomialPower`, to take an extra argument `int n`. But I think it looks the code more complicated. Anyway, I will revisit this code to use a polynomial visitor. I will check if I can simplify this further.

BTW, please note that I mixed `pow(x, y)` and `x^y` above to distinguish the `pow` in symbolic expression from the mathematical power function `^`.

For now, I've updated the documentation in the hope that it could help understand what the code is doing here.

---

*[drake/common/monomial.cc, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km78UIfDHkoR4YKb0kL:-KmCKpjZaTOlWduOmiU5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.cc#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider making the double->int conversion of exponent_val explicit to readers?
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 25 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75XeIP_xxy4Hv_jNj:-KmCSLTN6lzqjW5c9Kgc:b9cedjm) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I guess feature review was okay losing the "Note that it does not include the coefficient part" statement?  I guess I can go along with that.

(Losing the map representational detail was fine, of course.)
</blockquote></details>

Done. Thanks for catching it!

---

*[drake/common/monomial.h, line 92 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75oHuyTwZt32PhkPQ:-KmCTtF675HyV6G5JD04:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ Did you check if this formats correctly?  I would expect it to need `exception` after `@throws`, but maybe not.
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 94 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6275#-Km75yOOwyV5maJrQEg9:-KmCTvEEjXZxccp1fQg6:b-mqd1kk) ([raw file](https://github.com/robotlocomotion/drake/blob/d5d7f50e55b54d2c624bbf85324d072ff7c559b4/drake/common/monomial.h#L94)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(FWIW -- My subconscious just suggested `pow_in_place` as a good name.)
</blockquote></details>

Done.

 - Changed its name to the suggested `pow_in_place`. 
 - Added tests. 
 - Also needed to add missing `operator!=` to use `EXPECT_NE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6275)*

**Comment by jwnimmer-tri** [comment]
Sorry, I for the emojiness :lgtm:

**Pull request merged**
