### PR TITLE
Add userscalar_acceptance_test 

### LINKED ISSUE #8640: Add tests for openness of framework scalar types
Right now, the `//systems/framework` notionally supports user-defined scalar types, because we (try to) place all of the code in header files templated on `T`.  However, in practice possibly we have made mistakes and do not in fact support user-defined scalars.  We should add unit test(s) that prove the framework works with non-default scalars.

(Alternatively, we could give up and just lock down the scalars to those we care about, but that would be a separate discussion.)

Relates #6691 and #3741 as this also touches on code organization and compile times and etc.

\CC @sherm1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #8640.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

Note that the first commit is just the code move, the second commit is changes required to make it compile again, and the third commit is the new test.  I suspect that looking at the second commit on its own might be helpful to understand exactly what I had to change to break the circular dependency.

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8685#-LB1fTgL8HcFIq9u8Xef:-LB1fTgN6o4mpPoAjvMp:b-k67z2n) (no related file):*
In the issue thread, @sherm1 writes:
> ... we should be careful to avoid leaving the impression that anything good will happen using float as the scalar type.

That is a good point.  I'll update this PR to do avoid that, probably by not using `float` as my example anymore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685)*

**Comment by sherm1** [comment]
Fair enough -- thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685#-:-LB1qlZwAsfsDlJeFuaQ:b-w0aupb)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review per schedule, please.  Note that the first commit is just relocating code plus small whitespace adjustments.  The second commit is meaningful changes.

**Comment by ggould-tri** [comment]
:lgtm:; one suggestion below.  Thanks for the two-commit suggestion -- that made the review much easier.

---

Reviewed 2 of 10 files at r1, 4 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/test/userscalar_acceptance_test.cc, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8685#-LCEMlHq33m3LzSNyuif:-LCEMlHr66GkwHWFWvYp:b-xvpy66) ([raw file](https://github.com/robotlocomotion/drake/blob/1f2b6a537ce5bff249f701cc97d6cde87bab7f9a/systems/framework/test/userscalar_acceptance_test.cc#L35)):*
> ```cpp
> using UserScalar = Eigen::AutoDiffScalar<Eigen::Matrix<double, 11, 1>>;
> 
> GTEST_TEST(UserscalarAcceptanceTest, LeafSystemTest) {
> ```

By using typed tests, https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#typed-tests , you could make this test generic on its scalar; then you could apply it to the Big Three standard Drake scalars and demonstrate that they pass as well.  This would validate that your acceptance test is not over-demanding.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685#-:-LCEN6cg3ZR81GpXvART:b-w1v505)*

**Comment by jwnimmer-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/test/userscalar_acceptance_test.cc, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8685#-LCEMlHq33m3LzSNyuif:-LCEuEn1B02JfJ6UcIMJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f2b6a537ce5bff249f701cc97d6cde87bab7f9a/systems/framework/test/userscalar_acceptance_test.cc#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

By using typed tests, https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#typed-tests , you could make this test generic on its scalar; then you could apply it to the Big Three standard Drake scalars and demonstrate that they pass as well.  This would validate that your acceptance test is not over-demanding.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8685)*

**Pull request merged**
