### PR TITLE
Google Benchmark 2-step update, revised

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This reverts commit d735ad725492253b9dbd71d8aeef6702178b2dfb.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18451)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please.
</blockquote></details>

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.
</blockquote></details>

@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-debug please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.

**Review by rpoyner-tri — COMMENTED** [review]
-(status: do not merge) -(status: do not review) +(status: commits are properly curated) 
+@betsymcphail for feature review.
+@xuchenhan-tri for platform review.
FYI @svenevs thanks for buildcop work!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18451#-:-NJGNqbn52kz7nE9YS8p:b4ga16e)* status: 1 unresolved discussion, LGTM missing from assignees BetsyMcPhail,xuchenhan-tri(platform), labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail and @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
The `libpfm4-dev` is absolutely **not** a binary prerequisite.  (We never install benchmarks, and in any case if we did install them, only the runtime library would be a dependency, not the headers.)  I don't know what was going on with the CI failures, but using `binary_distribution` instead of `source_distribution` is not a valid fix.

Note the `no such package '@libpfm//` in the original CI error message.  This PR's workspace entry calls it `libpfm4` which is probably why things aren't working; it should be named `libpfm` (without the `4`).  I have no idea why it's passing even our normal CI, given that typo.  I suppose it's because we never opt-in to enable pfm for benchmarks, so we only need it at load-time, not build-time.  To make this whole thing less brittle, it's probably worth exploring whether we can put `--define=pfm=1` in our [Ubuntu-specific rcfile](https://github.com/RobotLocomotion/drake/blob/master/tools/ubuntu-jammy.bazelrc) so that the new dependency is actually used in earnest.

**Comment by svenevs** [comment]
>  I have no idea why it's passing even our normal CI, given that typo.

We were confused by this, as far as we could tell provisioned builds _should_ be failing here.  Hence we are not very confident in the utility of `@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please.`

> it's probably worth exploring whether we can put --define=pfm=1 in our [Ubuntu-specific rcfile](https://github.com/RobotLocomotion/drake/blob/master/tools/ubuntu-jammy.bazelrc) so that the new dependency is actually used in earnest.

If that ends up not being the decision, an alternative for just testing this PR, experimental builds can be parameterized with a `drake-ci` "dummy PR" that stuffs it in say https://github.com/RobotLocomotion/drake-ci/blob/main/user.bazelrc .

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not merge) +(status: do not review) while adjustments are made.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18451#-:-NJGkslL0tVWft171LmR:b-n4ryq9)* status: 1 unresolved discussion, LGTM missing from assignees xuchenhan-tri(platform),BetsyMcPhail, labeled "do not merge", missing label for release notes (waiting on @BetsyMcPhail and @xuchenhan-tri)

**Comment by rpoyner-tri** [comment]
Closing. I'll try to go the no-libpfm route instead.

**Pull request closed without merging**
