### PR TITLE
List out specific runtime/references warnings in math

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Work towards #2274.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3897)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Add DNM (unless done carefully).  Be sure this has been rebased to latest master under Jenkins before merging.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3897#-:-KUva6dvEqTXCfLvPwDz:b-7ewwmf)*

**Comment by jwnimmer-tri** [comment]
-@david-german-tri +@sammy-tri for all review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3897#-:-KV0HvZe2Kk2cpCv4rfy:b-dzmit1)*

**Comment by david-german-tri** [comment]
:lgtm: -@sammy-tri +@david-german-tri apologies for the delay

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3897#-:-KV0IkQKOvzOeOyg8_EK:b-zb2jid)*

**Comment by jwnimmer-tri** [comment]
Rebased to master, to removing DNM.

**Pull request merged**
