### PR TITLE
MBT method to compute tau_g(q)

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR implements `UniformGravityFieldElement::CalcGravityGeneralizedForces()`, a method to compute the generalized forces `tau_g(q)` due to gravity.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7800)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@edrumwri for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3AJCDleUQmZcjATQ1X:b-a98c4g)*

**Comment by edrumwri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmSofJ_osD9zTy3oX:-L3BmSofJ_osD9zTy3oY:b6fy2br) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L29)):*
> ```cpp
>   vc.InitializeToZero();
> 
>   MultibodyForces<T> forces(model);
> ```

These two lines seem important. Assuming I'm right, please document it.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BlRPpl6c1cN5hMmRm:-L3BlRPts4EOo1xJmlIs:b3dd4sx) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L46)):*
> ```cpp
> 
>   // Try first using different arrays for input/ouput:
>   // Initialize output to garbage, it should not affect the results.
> ```

What do you mean by "Initialize output to garbage"? Do you simply mean to say that the output is not expected to be initialized?

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmFCJHEJRKDQuZSF9:-L3BmFCJHEJRKDQuZSFA:b9brh3f) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L47)):*
> ```cpp
>   // Try first using different arrays for input/ouput:
>   // Initialize output to garbage, it should not affect the results.
>   model.CalcInverseDynamics(
> ```

I don't expect the casual reader to understand why inverse dynamics would be called. Would you document that?

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BlcbNWV1w8dLrj9O-:-L3BlcbNWV1w8dLrj9O0:b-jrt2qt) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L55)):*
> ```cpp
>       &tau_g /* Output, the generalized forces. */);
> 
>   // We want to return the generalized forces as they appear in M
> ```

What do you mean by "as they appear in M"? Also: it's not clear to me, much less the average reader, why tau_g should be negated.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmjiJZS9X5uOlrUvl:-L3BmjiJZS9X5uOlrUvm:b-5rp3il) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.h#L52)):*
> ```objc
>   ///   A vector containing the generalized forces due to this gravity field
>   ///   force element. The generalized forces are consistent with the vector of
>   ///   generalized velocities for the parent MultibodyTree model so that the
> ```

Suggest saying "generalized velocities `v`".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmSofJ_osD9zTy3oX:-L3EB4ljFtbR6owXXCSZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L29)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

These two lines seem important. Assuming I'm right, please document it.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BlRPpl6c1cN5hMmRm:-L3EBxZHkxJm2JSl0-dt:bo2nksy) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L46)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What do you mean by "Initialize output to garbage"? Do you simply mean to say that the output is not expected to be initialized?
</blockquote></details>

sorry, copy/pasta. I updated this comment to something more meaningful in this context.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmFCJHEJRKDQuZSF9:-L3EC4TPTn4kltk2YO_t:b-pjjdpy) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L47)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't expect the casual reader to understand why inverse dynamics would be called. Would you document that?
</blockquote></details>

Agree. Done per request above.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BlcbNWV1w8dLrj9O-:-L3EC8mo_ytWdgGfcU9l:b-63kg73) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L55)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What do you mean by "as they appear in M"? Also: it's not clear to me, much less the average reader, why tau_g should be negated.
</blockquote></details>

I was trying to make `tau_g` appear on the rhs of our equations of motion. However, per our email conversation with Russ, I got convinced that we should define it to be on the left hand side. I updated the docs in `uniform_gravity_field_element.h` (and the sign here) to reflect that.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmjiJZS9X5uOlrUvl:-L3ECsOxRNJS4a5E608E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.h#L52)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Suggest saying "generalized velocities `v`".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800)*

**Comment by amcastro-tri** [comment]
Thanks @edrumwri, I addressed your comments. Also notice I changed `tau_g(q)`'s sign convention per email discussion with Russ.

---

Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3EG8Zs0gvk86WYTVdj:bv0vai6)*

**Comment by amcastro-tri** [comment]
+@sherm1 for platform please.

---

Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3EGIFunqVFgmc7FCu3:b-af1gxe)*

**Comment by edrumwri** [comment]
:lgtm: but for a small documentation issue.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BlRPpl6c1cN5hMmRm:-L3FuawY4RnSGODiUGiQ:b7viife) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.cc#L46)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sorry, copy/pasta. I updated this comment to something more meaningful in this context.
</blockquote></details>

Ok, definitely steps in the right direction. What do you mean by J_WB though? Your description in the header of the ID process does not match btw.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3BmjiJZS9X5uOlrUvl:-L3Fv61cNJ-kgLFcURQs:bp32kh6) ([raw file](https://github.com/robotlocomotion/drake/blob/b27e872ac825622ef194741b69b3748151eccc45/multibody/multibody_tree/uniform_gravity_field_element.h#L52)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW I forgot to tell you that I like that you pointed out that would yield the work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3FvIFiLjifO_frKF2g:b-g78d2g)*

**Comment by sherm1** [comment]
Platform pass done. The sign convention handling is very tricky - comments below. We should definitely not use tau with two different sign conventions. If you want tau for generalized forces I propose a hard rule that it must always be used on the right hand side. That has the side benefit that generalized forces and generalized velocities have the same sign, in the sense that a positive generalized force produces a positive joint acceleration about its dof.

Then if we want to put gravity on the left we need a non-tau symbol for it.

---

Reviewed 2 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[multibody/benchmarks/acrobot/acrobot.h, line 82 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3FjWks1wTwKcJzF-RM:-L3FjWks1wTwKcJzF-RN:b-au2az) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/benchmarks/acrobot/acrobot.h#L82)):*
> ```objc
>   /// side of the equations of motion, that is;
>   /// `Mv̇ + C(q, v)v + tau_g(q) = tau_app`, where `tau_app` might include any
>   /// other forces applied on the pendulum.
> ```

BTW Alejandro, this uses tau on both sides but with different sign conventions. Per email discussion we need different symbols to avoid trouble. If you like tau for the rhs generalized forces, I suggest f_g(q) for force due to gravity. (Even better would be grav(q) to avoid using up `f`!)

Another possibility would be to use -tau_g() on the left and tau on the right. Then we can define f_g(q)=-tau_g(q) if we need something positive to put on the left.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 47 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3FuhEPyMejjBk2SjCo:-L3FuhEPyMejjBk2SjCp:b1pw7bv) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.cc#L47)):*
> ```cpp
>   VectorX<T> tau_g(model.get_num_velocities());
> 
>   // Compute inverse dynamics with zero generalized velocities and zero
> ```

BTW is this because you don't have a JᵀF operator yet? That would be a _lot_ more efficient. A TODO to replace this would be good.

---

*[multibody/multibody_tree/uniform_gravity_field_element.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3FtGPqnMwHZBSgkUcc:-L3FtGPqnMwHZBSgkUcd:b-usz17w) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.cc#L49)):*
> ```cpp
>   // Compute inverse dynamics with zero generalized velocities and zero
>   // generalized accelerations. Since inverse dynamics computes:
>   // tau_g = M(q)v̇ + C(q, v)v - ∑ J_WBᵀ(q) Fgrav_Bo_W
> ```

BTW this is the gravity _compensation_ torque! That is, it has the opposite sign from gravity.

I think it is important to be very clear about that here. If tau_g is the gravity compensation torque, then -tau_g is the torque due to gravity. Then our sign convention requires putting it on the left so it gets negated again.

If you want tau_g to mean "generalized forces due to gravity", using the rhs sign convention like all other generalized forces tau (which I think is good), then I suggest writing the above equation with a minus sign, e.g.
```
−tau_g = M(q)v̇ + C(q, v)v − ∑ J_WBᵀ(q) Fgrav_Bo_W
```
Alternatively you could introduce a different term for gravity compensation (just locally), say `tau_g_comp` and write:
```
tau_g_comp = M(q)v̇ + C(q, v)v − ∑ J_WBᵀ(q) Fgrav_Bo_W
tau_g =−tau_g_comp   // rhs convention
f_g = −tau_g         // lhs convention
```

What a mess!

BTW consider using unicode minus sign − rather than hyphen - for negation and subtraction.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3FoCB25ySZ_jUC-EoA:-L3FoCB25ySZ_jUC-EoB:b-8ub3bz) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.h#L43)):*
> ```objc
>   /// `tau_g(q)` is defined such that it appears on the left hand side of the
>   /// equations of motion, like so: <pre>
>   ///   Mv̇ + C(q, v)v + tau_g(q) = tau_app
> ```

BTW inconsistent sign conventions for taus is asking for trouble (and generally ugly). I'd like to define tau_g like any other sign, but use some other symbol with a different sign convention for more-conventional robot equations. So:
```
Mv̇ + C(q, v)v - tau_g(q) = tau_app
  or
Mv̇ + C(q, v)v + f_g(q) = tau_app
  with f_g = -tau_g.
```

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3Fq1OdRJzs-xT_QqFU:-L3Fq1OdRJzs-xT_QqFV:b-tv1o05) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.h#L55)):*
> ```objc
>   ///   force element. The generalized forces are consistent with the vector of
>   ///   generalized velocities `v` for the parent MultibodyTree model so that
>   ///   the inner product `v⋅tau_g` corresponds to the work carried out by the
> ```

BTW work->power. Regarding sign convention, for tau appearing on the _right_ the force is the negative gradient of the potential energy so negative power does positive work (I think!). So if we use f_g for gravity on the left, then power v⋅f_g is positive for positive work. Definitely don't want to mix taus and fs here. Power = v⋅tau should mean the same thing wherever it appears.

Note that generalized forces on the right have the same sign as generalized velocities, in the sense that a positive tau produces a positive v̇. Another reason putting forces on the left is awkward! 

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 262 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3Fl79I1cZB--Jjwu7w:-L3Fl79I1cZB--Jjwu7x:b-cn85xk) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/test/tree_from_joints_test.cc#L262)):*
> ```cpp
>   // For the double pendulum model under test, it verifies the result returned
>   // by UniformGravityFieldElement::CalcGravityGeneralizedForces() which
>   // computes the generalized forces tau_g due to a uniform gravity field force
> ```

BTW f_g ? Since you are emphasizing generalized forces here, you could also describe this as f_g=-JᵀF_g where F_g is the stacked vector of body spatial forces expressing the gravitational force on each body at that body's frame origin (m𝗴 shifted from com to origin). Not sure if that clarifies or obfuscates.

---

*[multibody/multibody_tree/test/tree_from_mobilizers_test.cc, line 690 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3FkgkHZ41W67FcytZ4:-L3FkgkHZ41W67FcytZ5:b-kupqee) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/test/tree_from_mobilizers_test.cc#L690)):*
> ```cpp
>         *context_, pc, vc, vdot, Fapplied_Bo_W_array, tau_applied,
>         &A_WB_array, &F_BMo_W_array, &tau);
>     // The result from inverse dynamics must be tau_g(q) as in our benchmark.
> ```

BTW f_g(q) ? (and below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3FwkA4mU7Btad-9PVa:b1l5vlj)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3Fq1OdRJzs-xT_QqFU:-L3Fxg1tv7xdNCv9XSeh:b-b9wh6z) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.h#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW work->power. Regarding sign convention, for tau appearing on the _right_ the force is the negative gradient of the potential energy so negative power does positive work (I think!). So if we use f_g for gravity on the left, then power v⋅f_g is positive for positive work. Definitely don't want to mix taus and fs here. Power = v⋅tau should mean the same thing wherever it appears.

Note that generalized forces on the right have the same sign as generalized velocities, in the sense that a positive tau produces a positive v̇. Another reason putting forces on the left is awkward! 
</blockquote></details>

BTW Shame on me for not catching that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3Fq1OdRJzs-xT_QqFU:-L3G6mSKgmg27co04ewn:b-y7eqcw) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.h#L55)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Shame on me for not catching that.
</blockquote></details>

@edrumwri -- I'm not sure there was actually anything wrong here that you missed, just that the sign conventions are not crisply defined so it is kind of hard to tell!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800)*

**Comment by amcastro-tri** [comment]
Before moving forward. Are we good with `Mv̇ + f_g = τ_applied` for notation/sign convention? @edrumwri, @sherm1, @russtedrake. 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3T4O3siHsV6WkJtF8V:b-hsy4sh)*

**Comment by sherm1** [comment]
:+1:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L3Tj0HH8xiARbTYRnOr:bb6mt9b)*

**Comment by sherm1** [comment]
@amcastro-tri, not sure if this was waiting for the MBTree email notation discussion to settle down. I think we at least converged on using τ_g for gravity (with same sign as any other τ), and putting  Mv̇+Cv on the left. I don't think anyone has a strong urge to put -τ_g on the left now, but it doesn't matter much now that it has the right sign! Is that enough for this to go forward?

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L4OA72oeEKDGpI3HZiK:b-8gqfzo)*

**Comment by RussTedrake** [comment]
I had the same thought this afternoon (testing the equations on the blackboard for class).  I decided to move it to the right hand side, and figured i didn’t need permission since we’d agreed on the sign.  The comment about M and Cqdot going together (as mass times acceleration) was enough for me to want it on the right.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L4OMnydFgCEPpojPSL8:bu39jni)*

**Comment by amcastro-tri** [comment]
I completely forgot I had this one still open. I'll update soon. Thank you all for your feedback.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L4OQGVpNTkEPXPNXibi:b-ilzeeo)*

**Comment by amcastro-tri** [comment]
I updated this PR to follow our new convention defining `tau_g(q)` to be on the right hand side of the equations of motion. PTAL.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L3Fq1OdRJzs-xT_QqFU:-L4ah4QFn9MUk3pIMDKk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/77ab9c7f594adc7394e4766b65e8d9df96b886cd/multibody/multibody_tree/uniform_gravity_field_element.h#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@edrumwri -- I'm not sure there was actually anything wrong here that you missed, just that the sign conventions are not crisply defined so it is kind of hard to tell!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L4akICMpVK9srOs7bSJ:byiwcx3)*

**Comment by sherm1** [comment]
Platform :lgtm: after CI failure repair (+ one BTW).

---

Reviewed 2 of 6 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[multibody/multibody_tree/uniform_gravity_field_element.h, line 56 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-L4b7hPBCYAAlb6UZtTn:-L4b7hPBCYAAlb6UZtTo:bo9x4nx) ([raw file](https://github.com/robotlocomotion/drake/blob/9c8ec86365aa4fb5508ba1a398e3b980d79657b9/multibody/multibody_tree/uniform_gravity_field_element.h#L56)):*
> ```objc
>   ///   force element. The generalized forces are consistent with the vector of
>   ///   generalized velocities `v` for the parent MultibodyTree model so that
>   ///   the inner product `v⋅tau_g` corresponds to the power carried out by the
> ```

BTW consider "carried out by" -> "applied by"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800#-:-L4b82N3_LbdtMdq1dD6:b9eb45i)*

**Comment by sherm1** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7800)*

**Pull request merged**
