### PR TITLE
workspace: Upgrade osqp and qdldl

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Upgrade osqp to latest release 0.6.2
Upgrade qdldl to latest release 0.1.5

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14714)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by hongkai-dai — COMMENTED** [review]
:LGTM: on OSQP upgrade.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14714#-:-MUZez4w2u8kjymaV8yH:b-bq21ab)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by hongkai-dai — COMMENTED** [review]
And also on qdldl

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14714#-:-MUZf71c5F0qk1p57qqI:b-yf94r9)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14714#-:-MUhw1BPCv2kairCpXb0:bnfp4nl)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Pull request merged**
