### PR TITLE
[doc] Add release notes v1.35.0

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
bazel-bin/tools/release_engineering/relnotes --action=create --version=v1.35.0 --prior_version=v1.34.0

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OB2nqqLESCEgd_24_nc:bfjxlll)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
bazel-bin/tools/release_engineering/relnotes --action=update --version=v1.35.0

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OB2qdUg6JcB5uuVHeGE:b-b5r9xy)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OB2r7Ox1ytB16Jdx5rX:b58m54h) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
> ```Markdown
> title: Drake v1.35.0
> date: 2099-12-31
> released: YYYY-MM-DD
> ```

Set to Working. Remind myself to update the date when it's ready.



_Code quote:_
```Markdown
date: 2099-12-31
released: YYYY-MM-DD
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 54 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB3_xt8-2RrGdT8XoW1:-OB3_xt8-2RrGdT8XoW2:b-dpv6r3) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e89493dee480af6603475bbef1749ab9210a6c3/doc/_release-notes/v1.35.0.md#L54)):*
> ```Markdown
> * Fix `GraphOfConvexSets` when passing in a trivially-infeasible upper bound ([#22090][_#22090])
> 
> ## Multibody Dynamics and Geometry
> ```

`Multibody Dynamics and Geometry` is next. Working.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 136 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBTScpp0SXmS6CKbCKO:-OBTScpp0SXmS6CKbCKP:b-rcbb4t) ([raw file](https://github.com/RobotLocomotion/drake/blob/14341f651405bf0cac8bc699080a443b0651eb1c/doc/_release-notes/v1.35.0.md#L136)):*
> ```Markdown
> * [fix] TBD [workspace] Upgrade rules_rust to latest release 0.53.0 ([#22119][_#22119])
> * [fix] TBD [workspace] Upgrade abseil_cpp_internal to latest commit ([#22118][_#22118])
> * TBD
> ```

Next is "Build dependencies."



_Code quote:_
```Markdown
* [fix] TBD [workspace] Force-disable CoinUtils debugging hooks ([#22063][_#22063])
* [fix] TBD [workspace] Upgrade openusd_internal to latest release 24.11 ([#22082][_#22082])
* [fix] TBD [workspace] Upgrade drake_models to latest commit ([#22103][_#22103])
* [fix] TBD [workspace] Upgrade crate_universe to latest ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade dm_control_internal to latest release 1.0.24 ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade msgpack_internal to latest release cpp-7.0.0 ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade mujoco_menagerie_internal to latest commit ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade mypy_internal to latest release v1.13.0 ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade statsjs to latest commit ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade suitesparse_internal to latest release v7.8.3 ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade tinyobjloader_internal to latest commit ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade vtk_internal to latest commit ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade rules_rust to latest release 0.53.0 ([#22119][_#22119])
* [fix] TBD [workspace] Upgrade abseil_cpp_internal to latest commit ([#22118][_#22118])
* TBD
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 136 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBTScpp0SXmS6CKbCKO:-OBY8pddC4YJGo-krLx-:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/14341f651405bf0cac8bc699080a443b0651eb1c/doc/_release-notes/v1.35.0.md#L136)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Next is "Build dependencies."
</blockquote></details>

Done

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBYCdaA-TXV9NdR2ybr:-OBYCdaA-TXV9NdR2ybs:b-capz6k):*
I'm ready to do `--action=update` again and merge upstream/master without rebase.



_Code quote:_
```
New commits in r5 on 11/12/2024 at 5:44 PM:

- 73b8c5e: Sort "Build system", "Build dependencies", "Removal of deprecated items"

- e90c69c: Fix typo
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`-- commits` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBYCdaA-TXV9NdR2ybr:-OBYExM60s21Y4vt2QG3:b-896fix):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm ready to do `--action=update` again and merge upstream/master without rebase.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OBYUR1u-cEnHFjOWXox:b6pu7ap) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to Working. Remind myself to update the date when it's ready.
</blockquote></details>

We're on November 12 now.

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBYZmSm3gPf3trmBJO7:ba0k9zt)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 151 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBaCRiG3-fQtICXBwwA:-OBaCRiH4Ode234Kxhfm:b-ynk7oy) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L151)):*
> ```Markdown
> 
> * `drake::geometry::MeshcatVisualizer::ResetRealtimeRateCalculator()` ([#22086][_#22086])
> * `drake::multibody::CalcSpatialInertia()` with the default density value ([#22086][_#22086])
> ```

Blocking until we merge #22166.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 151 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBaCRiG3-fQtICXBwwA:-OBae31B0hTF5I_Yfqp6:b6qp4f2) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L151)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking until we merge #22166.
</blockquote></details>

It's merged.

**Review by DamrongGuoy — COMMENTED** [review]
@cohnt , @hongkai-dai , @SeanCurtis-TRI , @sadraddini , @samzapo , @jwnimmer-tri , @AlexandreAmice please help me verify that we have good descriptions of your PRs.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBaf6NKANLqqbaRKH9B:b-giv47w)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 97 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBai87P6SE3_2xavTQN:-OBai87P6SE3_2xavTQO:b-hm6fkg) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L97)):*
> ```Markdown
> * Add requires clause to `drake::math::RigidTransform` and `drake::math::RotationMatrix` cast ([#22094][_#22094])
> * Add `drake::schema::Rotation::Sample()` ([#22113][_#22113])
> * Trim `drake::trajectories::PiecewisePolynomial` ([#22099][_#22099])
> ```

nit  update to ` SliceByTime for PiecewisePolynomials`

**Review by cohnt — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBauywcERzle_KK6Jx0:bnfp4nl)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 9 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB_nDcvEZaO1XHO2Bjq:-OBbLQXK62oggiNQW1-y:bp8ha0f) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Also, don't forget to update these TBDs "None" before the final version.
</blockquote></details>

Done. Thanks. I changed all the TBDs to None.
___
*[`doc/_release-notes/v1.35.0.md` line 62 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBaAXocDTcxOfMvZj_Y:-OBbLvUW8SEf9uAodBQ0:b2si3vl) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L62)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I almost wonder if this didn't get the wrong tag. Technically, it expands public API (which is why it got the "feature" tag). However, explaining what that feature is is difficult.

Let's try this phrase:

> Allow GeometryInstance to be registered through MultibodyPlant with clarifications on the related semantics
</blockquote></details>

Done. Thank you!  I appreciate the writing.
___
*[`doc/_release-notes/v1.35.0.md` line 97 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBai87P6SE3_2xavTQN:-OBbMxuh6fvOekLmgF6C:b-ci06kj) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L97)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit  update to ` SliceByTime for PiecewisePolynomials`
</blockquote></details>

Done. Thank you!  I hope this is good now.  Please let me know if we should change it more.

May I please say something about commit messages?  Now I can see the title of PR [22099](https://reviewable.io/reviews/RobotLocomotion/drake/22099) was `SliceByTime for PiecewisePolynomials`; however, the [merged commit 2a39984](https://github.com/RobotLocomotion/drake/commit/2a39984743a2fd47652b9f6fa30627cedfc83248) into master  was `Trim PiecewisePolynomials (#22099)`.  The commit message was the one that got pulled into the release notes automatically.

When a PR is near ready for merging into master, we might want to `rebase squash` the 12 commits into one commit with the appropriate message for release notes.  I hope this is useful to know.  It's just my two cents.
___
*[`doc/_release-notes/v1.35.0.md` line 118 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBaBK7g5UWNyuAwRNsq:-OBbTkud8F8HC6lEmKDT:b-d4pny8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L118)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: In alphabetical order, `bazelisk` would come after `bazel`
</blockquote></details>

Done. Thanks. `bazel` then `bazelisk`.
___
*[`doc/_release-notes/v1.35.0.md` line 118 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBaBcJ96JbAE2JdIM8w:-OBbTspU6RYzIxLL0l5g:b4fnoaa) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L118)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: These "upgrade to latest..." lines all belong under the next block: "Build dependencies".
</blockquote></details>

Done. Thanks.  I moved them to "Build dependencies".

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBbXST18AxjIAcr6IVY:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 9 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBbcG2X3XnE30pxaoY0:-OBbcG2X3XnE30pxaoY1:b-du5txy) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc67fc736e25a4c0a95871311149c5f330f4dbcd/doc/_release-notes/v1.35.0.md#L9)):*
> ```Markdown
> # Announcements
> 
> * None
> ```

I'd like to announce the RpyFloatingJoint feature from #21973. Something like:
```
MultibodyPlant now provides function SetBaseBodyJointType() which can be called pre-Finalize to control what type of joint is used for connecting unattached bodies to World. The default choice remains QuaternionFloatingJoint but RpyFloatingJoint and WeldJoint are options that can be set globally or for particular Model Instances. The Joint API is extended to permit setting pose and velocity generically without knowing the underlying joint type. See the description of PR #21973 for more information.
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 9 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBbcG2X3XnE30pxaoY0:-OBbnCStA17RNPIEiGd5:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/bc67fc736e25a4c0a95871311149c5f330f4dbcd/doc/_release-notes/v1.35.0.md#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'd like to announce the RpyFloatingJoint feature from #21973. Something like:
```
MultibodyPlant now provides function SetBaseBodyJointType() which can be called pre-Finalize to control what type of joint is used for connecting unattached bodies to World. The default choice remains QuaternionFloatingJoint but RpyFloatingJoint and WeldJoint are options that can be set globally or for particular Model Instances. The Joint API is extended to permit setting pose and velocity generically without knowing the underlying joint type. See the description of PR #21973 for more information.
```
</blockquote></details>

Done. Thanks.

**Review by samzapo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBc4swmAUIEdwNbws4M:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 45 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBcCs5HEMtp2nNqpcNg:-OBcHmOq4JrKINLG6Io8:b-9gdnve) ([raw file](https://github.com/RobotLocomotion/drake/blob/b141b84b44b8d0834af91bedf39b45502f9ad804/doc/_release-notes/v1.35.0.md#L45)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

It might be good to emphasize the use of this PR a bit more in these notes.
</blockquote></details>

Done. Thanks.  I appreciate the exact wording. It makes my job easier.

By the way, please click on :heavy_check_mark: (Satisfied), so this comment doesn't block this PR.  Right now your status is Blocking (:no_entry: ).

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OBcVeqGD8AGGpS0iH85:b-55pjbl) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

We're on November 12 now.
</blockquote></details>

We're at 6:30 PM PST, November 13, now.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OBfyJg58d5HrYOH4Idw:b8oj8dm) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

We're at 6:30 PM PST, November 13, now.
</blockquote></details>

Last night, there was one more PR (([commit: 3613367](https://github.com/RobotLocomotion/drake/commit/36133672b4e2ba86e89157828a80207abe488234))) merged into master before the Nightly started.  

I'll run `relnotes --action=update --version=v1.35.0 --target_commit=3613367` and cut the release.

**Review by DamrongGuoy — COMMENTED** [review]
All the Nightly passed except [linux-jammy-gcc-bazel-nightly-coverage/409/](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-gcc-bazel-nightly-coverage/409/) with a coverage timeout in one unit test.  We can still release v1.35.0 today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBg-L4YAvPiTdwq_SU7:bn5x5yc)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBg1daDBUqR3ziacd8m:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_release-notes/v1.35.0.md` line 97 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBai87P6SE3_2xavTQN:-OBg1VVo6HohTleVAfDV:b-x3phrl) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L97)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done. Thank you!  I hope this is good now.  Please let me know if we should change it more.

May I please say something about commit messages?  Now I can see the title of PR [22099](https://reviewable.io/reviews/RobotLocomotion/drake/22099) was `SliceByTime for PiecewisePolynomials`; however, the [merged commit 2a39984](https://github.com/RobotLocomotion/drake/commit/2a39984743a2fd47652b9f6fa30627cedfc83248) into master  was `Trim PiecewisePolynomials (#22099)`.  The commit message was the one that got pulled into the release notes automatically.

When a PR is near ready for merging into master, we might want to `rebase squash` the 12 commits into one commit with the appropriate message for release notes.  I hope this is useful to know.  It's just my two cents.
</blockquote></details>

Right. I changed the function name per reviewer suggestion but didn't update the message. My bad.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OBg1HZI7CVJy4yT6Gxi:bgi8a82) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Last night, there was one more PR (([commit: 3613367](https://github.com/RobotLocomotion/drake/commit/36133672b4e2ba86e89157828a80207abe488234))) merged into master before the Nightly started.  

I'll run `relnotes --action=update --version=v1.35.0 --target_commit=3613367` and cut the release.
</blockquote></details>

Actually, I had to use the 40-character SHA1.

```
bazel-bin/tools/release_engineering/relnotes --action=update --version=v1.35.0 --target_commit=36133672b4e2ba86e89157828a80207abe488234
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 97 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBai87P6SE3_2xavTQN:-OBg4Hpo5n574ar39Gfw:b4iuimw) ([raw file](https://github.com/RobotLocomotion/drake/blob/c5aef08b161a225319fba04fef2ea0b9539cf4ef/doc/_release-notes/v1.35.0.md#L97)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Right. I changed the function name per reviewer suggestion but didn't update the message. My bad.
</blockquote></details>

Thank you for your explanation.  All is well.

**Review by DamrongGuoy — COMMENTED** [review]
```
bazel run //tools/release_engineering:download_release_candidate -- --find-git-sha 20241114
```
Done on my Puget.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBg7gup4FlRcGGcywSK:bq0lclz)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
I have started the staging builds (Linux Wheel, macOS arm Wheel, Jammy Packaging, Noble Packaging, macOS arm Packaging).

I'll try to finish the release notes now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBgE8_--pAXP-nz8dPY:bibw3ra)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBgEvuzCDyLaaA-xAGm:-OBgEvuzCDyLaaA-xAGn:b-wnrjmk) (no related file):*
Make sure to wait for the five staging builds to finish before merging. Set to Working.

**Review by DamrongGuoy — COMMENTED** [review]
I did `git revert c1f13a1` to enable CI.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBgd72vDa1azqmYwJ7k:buxvqy9)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
Officially assign reviewers so that I can merge this PR. +@sherm1 +@hongkai-dai 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBgdI-22rp3hHnRH5K8:bm6b786)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.35.0.md` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OB2r7Ox1ytB16Jdx5rW:-OBgeBKA3QwWQLO32vjk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3d9fe3ecb16d49ed8452a4b88c48e96829839bbc/doc/_release-notes/v1.35.0.md#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Actually, I had to use the 40-character SHA1.

```
bazel-bin/tools/release_engineering/relnotes --action=update --version=v1.35.0 --target_commit=36133672b4e2ba86e89157828a80207abe488234
```
</blockquote></details>

Done.

**Comment by DamrongGuoy** [comment]
Previously the `mac-*-experimental-*` job was aborted to let the staging job start first.  I'll start it again.

@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-OBgEvuzCDyLaaA-xAGm:-OBh-9gx4UcBv5Z2S__7:bsqdy2p) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Make sure to wait for the five staging builds to finish before merging. Set to Working.
</blockquote></details>

Done. The five staging builds have finished successfully.

**Review by DamrongGuoy — COMMENTED** [review]
`bazel run //tools/release_engineering:download_release_candidate -- --version v1.35.0`

It was done on my Puget.  Ready to merge this PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBh0Jff-Pf3DCkfsR5o:b-chq0we)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22137#-:-OBh1CJz5TjwN-xE0pHr:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai

**Comment by DamrongGuoy** [comment]
It's merged now. Thank you very much, everybody!

**Pull request merged**
