### PR TITLE
Update Eigen, second attempt

### PR DESCRIPTION
**Pull request by tkoolen**
Second shot at updating Eigen to a recent commit on Eigen's default branch.

First attempt: https://github.com/RobotLocomotion/drake/pull/3227
Revert of first attempt: https://github.com/RobotLocomotion/drake/pull/3244.

See RobotLocomotion/eigen-pod#7.
Fixes https://github.com/RobotLocomotion/drake/issues/3211.
Fixes https://github.com/RobotLocomotion/drake/issues/2106.

Worked around [this Eigen bug](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1283), which I just filed.
Made sure that IKTest.m passes (which failed on Matlab release earlier), both on OSX and on Linux.
Now only running testIKMoreConstraints when SNOPT is present (see discussion [here](https://github.com/RobotLocomotion/drake/pull/3244)).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3300)

### CODE REVIEW

**Comment by tkoolen** [comment]
Is there a way to run the full matlab-release build on Jenkins before merging?

**Comment by jwnimmer-tri** [comment]
Yes, details that still work okay are at http://drake.mit.edu/jenkins.html#running-an-on-demand-build but it's even easier now (our docs are stale).  Here's an example (that actually runs a build, so no need to post this again unless you need more builds) ...

@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please

**Comment by tkoolen** [comment]
Great, thanks.

**Comment by liangfok** [comment]
Looks like the tests passed. Congratulations!

**Comment by jwnimmer-tri** [comment]
I suggest @sammy-tri for review of `testIKMoreConstraints` change, and @david-german-tri for review of `RigidBodyConstraint.cpp` change (and platform merge) -- if you folks want to self-assign a review?  The other changes are identical to #3227 and already reviewed.

**Comment by sammy-tri** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 1074 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4gYTYVALoR2rJLEn:-KQR4gYUDyviBsDiaa_h:b-7ofsu6) ([raw file](https://github.com/robotlocomotion/drake/blob/29d949e080af7af6ed113b08e0d7dd558c39f3d6/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L1074)):*
> ```cpp
>     auto daxis_err = e_autodiff.derivatives().transpose().eval();
> 
>     MatrixXd daxis_err_dq(1, nq);
> ```

We should probably reference the Eigen issue this is working around.

---

*[drake/systems/plants/test/CMakeLists.txt, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4pzDWyj6okWAj6oJ:-KQR4pzDWyj6okWAj6oK:b-oed0vt) ([raw file](https://github.com/robotlocomotion/drake/blob/e37b5991a448cae881e9bd745aea1e0195e007d6/drake/systems/plants/test/CMakeLists.txt#L49)):*
> ```CMake
> endif()
> if (snopt_c_FOUND)
>   add_ik_gtest(testIKMoreConstraints)
> ```

Do we understand why the input to IPOPT changed?  I still don't like the idea of turning off a test because a solver which doesn't use Eigen isn't doing the same thing with a newer Eigen version.

Do you think the Eigen issue which you opened could also relate to uses of .segment() (and not just block())?  If so, I've found one small difference between the SNOPT and IPOPT wrappers which could potentially be relevant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300)*

**Comment by sammy-tri** [comment]
+@sammy-tri for the reasons mentioned above

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-:-KQR5rJhPoL7JEYxC70G:bqt438e)*

**Comment by tkoolen** [comment]
> We should probably reference the Eigen issue this is working around

I did, in the commit message. I think for this the reference should be with the change, not with the code. I'll put in a comment if you prefer that.

> Do you think the Eigen issue which you opened could also relate to uses of .segment() (and not just block())? If so, I've found one small difference between the SNOPT and IPOPT wrappers which could potentially be relevant.

`segment` is basically syntactic sugar for `block`, so yeah that's possible. I'll switch to Ubuntu and compile in debug mode to make sure (should trigger an assertion error if it is an instance of that bug).

**Comment by tkoolen** [comment]
Just compiled in debug mode on GCC without SNOPT (so that Ipopt is used in testIKMoreConstraints). There is no assertion error, so it's not a case of the bug I reported. 

Again, note that this test passes when SNOPT is used instead of Ipopt.

**Comment by sammy-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 1074 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4gYTYVALoR2rJLEn:-KQRn5MO5KBvmcIUnNL_:bizonh0) ([raw file](https://github.com/robotlocomotion/drake/blob/29d949e080af7af6ed113b08e0d7dd558c39f3d6/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L1074)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> We should probably reference the Eigen issue this is working around.
</details>
I think I would prefer a comment as well.  My fear is that someone could be working in this code and modify it in a way which would bring back the bug if they don't know about the problem.  (btw, are you viewing my PR comments in reviewable?  It has a feature to leave responses at the site of the comment)

---

*[drake/systems/plants/test/CMakeLists.txt, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4pzDWyj6okWAj6oJ:-KQRnT_Q0xMMPOjWCAqf:b-mrk8ro) ([raw file](https://github.com/robotlocomotion/drake/blob/e37b5991a448cae881e9bd745aea1e0195e007d6/drake/systems/plants/test/CMakeLists.txt#L49)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Do we understand why the input to IPOPT changed?  I still don't like the idea of turning off a test because a solver which doesn't use Eigen isn't doing the same thing with a newer Eigen version.
> 
> Do you think the Eigen issue which you opened could also relate to uses of .segment() (and not just block())?  If so, I've found one small difference between the SNOPT and IPOPT wrappers which could potentially be relevant.
</details>
It still bothers me that we don't have any idea what changed.  I guess I'd be willing to not hold up this PR by requiring that testIKMoreConstraints pass with ip IPOPT provided that we open an issue indicating that the Eigen upgrade caused a regression in this functionality.

Regressions which are this non-obvious are not a good smell to me, and I fear other problems coming up down the road (something changed when no change was expected and we don't know why), but it seems like enough other people want the newer Eigen that maybe it's worth the risk here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300)*

**Comment by tkoolen** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/constraint/RigidBodyConstraint.cpp, line 1074 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4gYTYVALoR2rJLEn:-KQSGbIZDmQv1S96EsNp:b-f8sf1p) ([raw file](https://github.com/robotlocomotion/drake/blob/29d949e080af7af6ed113b08e0d7dd558c39f3d6/drake/systems/plants/constraint/RigidBodyConstraint.cpp#L1074)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think I would prefer a comment as well.  My fear is that someone could be working in this code and modify it in a way which would bring back the bug if they don't know about the problem.  (btw, are you viewing my PR comments in reviewable?  It has a feature to leave responses at the site of the comment)
</details>
Added a comment.

---

*[drake/systems/plants/test/CMakeLists.txt, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4pzDWyj6okWAj6oJ:-KQSFHWIsnHvajjZSQra:b-bn82gi) ([raw file](https://github.com/robotlocomotion/drake/blob/e37b5991a448cae881e9bd745aea1e0195e007d6/drake/systems/plants/test/CMakeLists.txt#L49)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> It still bothers me that we don't have any idea what changed.  I guess I'd be willing to not hold up this PR by requiring that testIKMoreConstraints pass with ip IPOPT provided that we open an issue indicating that the Eigen upgrade caused a regression in this functionality.
> 
> Regressions which are this non-obvious are not a good smell to me, and I fear other problems coming up down the road (something changed when no change was expected and we don't know why), but it seems like enough other people want the newer Eigen that maybe it's worth the risk here.
</details>
Some evidence supporting my claim that it's just Ipopt being finicky:
* start with current master
* perturb `dc` in `QuasiStaticConstraint::eval` by uniformly adding 1e-16
* run testIKMoreConstraints with Ipopt

Result: inverseKinBackend info code 100 (Ipopt return code 4, [Diverging_Iterates](https://projects.coin-or.org/Ipopt/browser/trunk/Ipopt/src/Interfaces/IpReturnCodes_inc.h)). Result passes `CompareMatrices` check at the end though. 

The same things happen on this pull request (Ipopt return code 4, result passes `CompareMatrices` check).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/CMakeLists.txt, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4pzDWyj6okWAj6oJ:-KQSMGKHheW93gLJer5K:b-4oveat) ([raw file](https://github.com/robotlocomotion/drake/blob/e37b5991a448cae881e9bd745aea1e0195e007d6/drake/systems/plants/test/CMakeLists.txt#L49)):*
<details><summary><i>Previously, tkoolen (Twan Koolen) wrote…</i></summary>
> Some evidence supporting my claim that it's just Ipopt being finicky:
> * start with current master
> * perturb `dc` in `QuasiStaticConstraint::eval` by uniformly adding 1e-16
> * run testIKMoreConstraints with Ipopt
> 
> Result: inverseKinBackend info code 100 (Ipopt return code 4, [Diverging_Iterates](https://projects.coin-or.org/Ipopt/browser/trunk/Ipopt/src/Interfaces/IpReturnCodes_inc.h)). Result passes `CompareMatrices` check at the end though. 
> 
> The same things happen on this pull request (Ipopt return code 4, result passes `CompareMatrices` check).
</details>
OK.  If you can open an issue and assign it to me, that works.  Then it's my problem for just being excessively picky and I can figure it out or close the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-:-KQSMYWS598qOvFNA7EP:bnfp4nl)*

**Comment by tkoolen** [comment]
*[drake/systems/plants/test/CMakeLists.txt, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3300#-KQR4pzDWyj6okWAj6oJ:-KQSPFeOv5kNLqd_OMfq:b-aypwwm) ([raw file](https://github.com/robotlocomotion/drake/blob/e37b5991a448cae881e9bd745aea1e0195e007d6/drake/systems/plants/test/CMakeLists.txt#L49)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> OK.  If you can open an issue and assign it to me, that works.  Then it's my problem for just being excessively picky and I can figure it out or close the issue.
</details>
Issue: https://github.com/RobotLocomotion/drake/issues/3128 (you were already assigned).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3300)*

**Comment by jamiesnape** [comment]
> Yes, details that still work okay are at http://drake.mit.edu/jenkins.html#running-an-on-demand-build but it's even easier now (our docs are stale). Here's an example (that actually runs a build, so no need to post this again unless you need more builds) ...

Not entirely stale. The `@drake-jenkins-bot ... please` command does not run long running tests.

**Pull request merged**
