### PR TITLE
Adds a xacro-generated dual iiwa arm URDF model.

### PR DESCRIPTION
**Pull request by liangfok**
This builds upon #5636 and is an incremental step towards #5267.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5660)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ericcousineau-tri for feature review please. Thanks!

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgUvjJ470GZUeHmjbxF:bua8qfi)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: Good stuff!

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgWKh9GzzBB2tUpC1xd:b-m6xbb3)*

**Comment by liangfok** [comment]
+@soonho-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgWKuvZ5BqbVHz3FMBL:b-lnsuqk)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgXkXvMEvBci0cephFE:bnfp4nl)*

**Comment by soonho-tri** [comment]
Can we mark those generated `.urdf`  as 'generated' in reviewable by using one of the options presented at https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed ?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgXkZI-06ke6BqZ2VST:b8v2vfl)*

**Comment by liangfok** [comment]
Done (see commit 2). Here's how it looks now:



---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgYwknpkPoAqjbqoJG9:b63p7xc)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660#-:-KgZ2k2ts_IBQKDODlAU:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5660)*

**Pull request merged**
