### PR TITLE
sdf, urdf: Add/canonicalize xmlns: declarations

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #13314

This patch makes it possible to interrogate drake-extended model files
with standard XML tools, which is useful when composing and verifying
documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16446)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +(release notes: none) +@ericcousineau-tri for both reviews.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16446#-:-MuP2y-J7PC_3psfHRez:bs9csrb)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with minor nit

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16446#-:-MuRVN3o6NDdM3_aAEAt:b-acpx4p)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16446#-MuRVQ4R306Va9qFhKxV):*
nit This allows us to use `drake:` namespace; however, the `xmlns:drake` at the top may not actually refer to a machine digestible (or quickly human digestible) specification for the schema.

Consider mentioning that here?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16446)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16446#-MuRVQ4R306Va9qFhKxV):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This allows us to use `drake:` namespace; however, the `xmlns:drake` at the top may not actually refer to a machine digestible (or quickly human digestible) specification for the schema.

Consider mentioning that here?
</blockquote></details>

From what I've read of the specs for namespaces, I don't think that there is even an expectation that the "uri" points to anything any more. It's more like just a unique identifier that's too long and syntax-hobbled to use within the document.

But, if you like, I can ramble about all that in the commit message.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16446)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16446#-MuRVQ4R306Va9qFhKxV):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

From what I've read of the specs for namespaces, I don't think that there is even an expectation that the "uri" points to anything any more. It's more like just a unique identifier that's too long and syntax-hobbled to use within the document.

But, if you like, I can ramble about all that in the commit message.
</blockquote></details>

OK Ah, I naively assumed the URI was meant to be more useful, e.g. https://www.w3.org/1999/xhtml/ - but yeah, that all makes sense, no need to update message then.

**Pull request merged**
