### PR TITLE
Fixed typo.

### PR DESCRIPTION
**Pull request by liangfok**
...in the name of establishing a culture of small PRs :grinning:

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2096)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2096#-:-KFKUGpukdXORpmwuXzS:1417088721)*

**Comment by sherm1** [comment]
Nice!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2096#-:-KFKnTdLMCGd95leRzGh:-490100129)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2096#-:-KFKndIDQ2l3B_mjlNgI:1417088721)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2096#-:-KFL78c_Jkx0lqegJWLy:1417088721)*

**Pull request merged**
