### PR TITLE
Polynomial degree

### LINKED ISSUE #5048: Add Symbolic::Polynomial class
This class should store a map `unordered_map<Monomial::ID, double>` monomial_to_coeff_map_. It should support following functions

1. Return the degree of the polynomial.
2. Return the degree of the polynomial for a subset of variables.
3. Return the Newton polytope.
4. Return the set of variables in the polynomial.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Partially resolves #5048

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5073)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@soonho-tri for feature review.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcKgnxSCucjdzoDNdxg:b-hll8wg)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcKgrrWTlm4ObDfjQMx:bboswjz)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcOMI2QxlNqCg7Q_odx:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcONU9sA244-oEp62Zf:-KcONU9sA244-oEp62Zg:bhzc3oa) ([raw file](https://github.com/robotlocomotion/drake/blob/5fefca2de201728c49dd5d7fa1e2e17aceea668e/drake/common/symbolic_expression.cc#L158)):*
> ```cpp
> int Expression::Degree(const Variables& vars) const {
>   DRAKE_ASSERT(ptr_ != nullptr);
>   return ptr_->Degree(vars);
> ```

Let's have `DRAKE_DEMAND(is_polynomial())` here.

---

*[drake/common/symbolic_expression.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcONacySGxCIvP30pWa:-KcONacySGxCIvP30pWb:b6nnsa5) ([raw file](https://github.com/robotlocomotion/drake/blob/5fefca2de201728c49dd5d7fa1e2e17aceea668e/drake/common/symbolic_expression.cc#L163)):*
> ```cpp
> int Expression::Degree() const {
>   DRAKE_ASSERT(ptr_ != nullptr);
>   return ptr_->Degree(GetVariables());
> ```

and `DRAKE_DEMAND(is_polynomial())` here.

I think the two are enough and the rest of `DRAKE_DEMAND(is_polynomial())` can be removed since it's guaranteed by construction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by hongkai-dai** [comment]
+@david-german-tri for platform review.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcONU9sA244-oEp62Zf:-KcObu8g_lAfv5xkP3hL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fefca2de201728c49dd5d7fa1e2e17aceea668e/drake/common/symbolic_expression.cc#L158)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Let's have `DRAKE_DEMAND(is_polynomial())` here.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.cc, line 163 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcONacySGxCIvP30pWa:-KcObuaCR2_Xtb6Ho4xJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5fefca2de201728c49dd5d7fa1e2e17aceea668e/drake/common/symbolic_expression.cc#L163)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

and `DRAKE_DEMAND(is_polynomial())` here.

I think the two are enough and the rest of `DRAKE_DEMAND(is_polynomial())` can be removed since it's guaranteed by construction.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcOdh92oy9BaZTw89iv:b93ll5)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_cell.cc, line 650 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOeflqr_rAotf6nU05:-KcOebTt4Fn7wLE3ZX7E:blh8xge) ([raw file](https://github.com/robotlocomotion/drake/blob/2f60c68b31cc22338360ace46d1833f0f6c4274b/drake/common/symbolic_expression_cell.cc#L650)):*
> ```cpp
>         const Expression& base{p.first};
>         const Expression& expnt{p.second};
>         DRAKE_DEMAND(is_constant(expnt));
> ```

nitpick: this one can be removed as well...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by hongkai-dai** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_cell.cc, line 650 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOeflqr_rAotf6nU05:-KcOglS0BWu1tPQKOZlT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f60c68b31cc22338360ace46d1833f0f6c4274b/drake/common/symbolic_expression_cell.cc#L650)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nitpick: this one can be removed as well...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcOhuyepZ1ryHEziOl4:b-s794vx)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOneQ5Dmt0KcSXLj61:-KcOneQ6eo5bTTLvHJPI:b-piccrn) (no related file):*
I've flagged a few specific concerns below.  More generally, I think the desired semantics of `Degree` are just not clear

---

*[drake/common/symbolic_expression_cell.cc, line 810 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOivp_DkGte0uX6g20:-KcOivp_DkGte0uX6g21:b-xvmfqb) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L810)):*
> ```cpp
> 
> int ExpressionDiv::Degree(const Variables& vars) const {
>   return get_first_argument().Degree(vars) - get_second_argument().Degree(vars);
> ```

Am I correctly understanding that the degree of `x^2 / y` in `(x, y)` is `1`?  Is that really what you want?

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcOkC_AdlH3Eiwb7v8r:b-hd3fq6) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
> ```cpp
> 
> int ExpressionPow::Degree(const Variables &vars) const {
>   const int expnt{static_cast<int>(get_constant_value(get_second_argument()))};
> ```

1. What if the second argument isn't a constant value?  My best guess is that it leads to a debug-mode-only assert failure here: https://github.com/RobotLocomotion/drake/blob/56d5e6b41cf4a57daac2d01ec0918502a7031893/drake/common/symbolic_expression_cell.cc#L1307

Is that right?  If so, it (and any other such nonobvious failure cases) should be documented on `Degree` in `symbolic_expression.h`.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOllwmfjWhnlP8Qnek:-KcOllwmfjWhnlP8Qnel:bj2844z) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
> ```cpp
> 
> int ExpressionPow::Degree(const Variables &vars) const {
>   const int expnt{static_cast<int>(get_constant_value(get_second_argument()))};
> ```

2. Is this the right behavior for constant but non-integer expressions?  The degree of `pow(x, 1.5)` isn't really `1` in `x`, nor is the degree of `pow(pow(x, 2), 0.5)` really `0`.

On further examination, I think the `is_polynomial` assertion earlier in the call graph protects against non-integer exponents.  If so, please at least mention that in a comment here.

---

*[drake/common/test/symbolic_expression_test.cc, line 639 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkTDPKrJL7npCoxXP:-KcOkTDPKrJL7npCoxXQ:bkwx0az) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/test/symbolic_expression_test.cc#L639)):*
> ```cpp
>   EXPECT_EQ(e9.Degree(), 3);
> 
>   const Expression e10{pow(pow(x_, 3), 1.0 / 3)};
> ```

Yikes!! If I'm understanding correctly, this only works because of a simplification: https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L532

If we had instead written

`pow(x_ * x_ * x_, 1.0 / 3)` would this test pass?  I don't think so, and that seems like an indication something is wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 810 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOivp_DkGte0uX6g20:-KcOrJXHOTfdtVn0ZSnf:b-qwuewf) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L810)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Am I correctly understanding that the degree of `x^2 / y` in `(x, y)` is `1`?  Is that really what you want?
</blockquote></details>

`x^2 / y` is not a polynomial. Calling `Degree` will fail for `x^2 / y`, when we call `symbolic::Expression.Degree`, due to the check `DRAKE_DEMAND(is_polynomial())` in `symbolic::Expression.Degree`.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcOruDzJtFQbfUNKPI2:b-g821ac) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

1. What if the second argument isn't a constant value?  My best guess is that it leads to a debug-mode-only assert failure here: https://github.com/RobotLocomotion/drake/blob/56d5e6b41cf4a57daac2d01ec0918502a7031893/drake/common/symbolic_expression_cell.cc#L1307

Is that right?  If so, it (and any other such nonobvious failure cases) should be documented on `Degree` in `symbolic_expression.h`.
</blockquote></details>

If the second argument isn't a constant value, it should fail the assertion at https://github.com/hongkai-dai/drake/blob/polynomial/drake/common/symbolic_expression.cc#L158. `symbolic_expression_cell.h` is not exposed to the user, only `symbolic_expression.h` is exposed to the user, so we add the assertion in `symbolic_expression.cc`.

I had the check `is_polynomial()` in each `Degree()` function in `symbolic_expression_cell.cc`, later @soonho-tri  and I agreed it should be enough to check whether the expression is a polynomial just in the `symbolic_expression.cc`.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOllwmfjWhnlP8Qnek:-KcOswjWFeua2FCHyDoQ:b5gah5n) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

2. Is this the right behavior for constant but non-integer expressions?  The degree of `pow(x, 1.5)` isn't really `1` in `x`, nor is the degree of `pow(pow(x, 2), 0.5)` really `0`.

On further examination, I think the `is_polynomial` assertion earlier in the call graph protects against non-integer exponents.  If so, please at least mention that in a comment here.
</blockquote></details>

It is checked in `symbolic_expression.cc`.

---

*[drake/common/test/symbolic_expression_test.cc, line 639 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkTDPKrJL7npCoxXP:-KcOt9CT2EjhjuOrJL2O:bfddfjr) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/test/symbolic_expression_test.cc#L639)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Yikes!! If I'm understanding correctly, this only works because of a simplification: https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L532

If we had instead written

`pow(x_ * x_ * x_, 1.0 / 3)` would this test pass?  I don't think so, and that seems like an indication something is wrong.
</blockquote></details>

I agree we have a problem `pow(x_ * x_ * x_, 1.0 / 3)`, the check `is_polynomial()` will fail, and the call to `Degree()` will throw an error. But this is a separate issue, that we have not provided all the desirable simplification yet.

@soonho-tri shall we create a github issue to track all the simplification we should add?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOneQ5Dmt0KcSXLj61:-KcOyiPNPIBEOxUCa58K:br94620) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I've flagged a few specific concerns below.  More generally, I think the desired semantics of `Degree` are just not clear
</blockquote></details>

Whoops, accidental comment.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcOwRmDwKnsNCK5rffv:bbt4cob) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If the second argument isn't a constant value, it should fail the assertion at https://github.com/hongkai-dai/drake/blob/polynomial/drake/common/symbolic_expression.cc#L158. `symbolic_expression_cell.h` is not exposed to the user, only `symbolic_expression.h` is exposed to the user, so we add the assertion in `symbolic_expression.cc`.

I had the check `is_polynomial()` in each `Degree()` function in `symbolic_expression_cell.cc`, later @soonho-tri  and I agreed it should be enough to check whether the expression is a polynomial just in the `symbolic_expression.cc`.
</blockquote></details>

That makes sense.  I think a comment on the nontrivial implementations of Degree  would be useful, just to remind readers that, as a precondition, the expression is polynomial.

---

*[drake/common/test/symbolic_expression_test.cc, line 639 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkTDPKrJL7npCoxXP:-KcOxA2rMXd9Zw9KMHwm:b-vkleje) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/test/symbolic_expression_test.cc#L639)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I agree we have a problem `pow(x_ * x_ * x_, 1.0 / 3)`, the check `is_polynomial()` will fail, and the call to `Degree()` will throw an error. But this is a separate issue, that we have not provided all the desirable simplification yet.

@soonho-tri shall we create a github issue to track all the simplification we should add?
</blockquote></details>

OK, that makes sense.  Thanks.

---

*[drake/common/test/symbolic_expression_test.cc, line 639 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOxBn8nUzw8hvN30Zl:-KcOxBn8nUzw8hvN30Zm:bvsquhg) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/test/symbolic_expression_test.cc#L639)):*
> ```cpp
>   EXPECT_EQ(e9.Degree(), 3);
> 
>   const Expression e10{pow(pow(x_, 3), 1.0 / 3)};
> ```

BTW Follow-up question here about floating-point error: it looks to me like the constants are "flattened" here: https://github.com/RobotLocomotion/drake/blob/master/drake/common/symbolic_expression.cc#L395

Is it guaranteed that `q * (1.0 / q) == 1.0` for all values `q` of a double?   It seems to have worked out for `3` but I suspect it's not true in general.  If so, that might be an argument for cancelling numbers symbolically when possible.  Definitely not needed for this PR, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcOytA5eHUFmWZKUI3u:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcP1jl_dhnkGblBDrxc:bz8iamq) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

That makes sense.  I think a comment on the nontrivial implementations of Degree  would be useful, just to remind readers that, as a precondition, the expression is polynomial.
</blockquote></details>

https://github.com/hongkai-dai/drake/blob/polynomial/drake/common/symbolic_expression.h#L186 Is this comment OK?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcP2flegRMg54ueDkEu:b-jmd6wh) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

https://github.com/hongkai-dai/drake/blob/polynomial/drake/common/symbolic_expression.h#L186 Is this comment OK?
</blockquote></details>

It's kind of far away.  I was suggesting something like the following, right here:

```
// As a precondition, this expression `is_polynomial`, so the exponent is an
// integer and this cast does not change its value.
```

and similar remarks for multiplication and division

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 639 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOxBn8nUzw8hvN30Zl:-KcP9axKKU5iADf20Ipt:bpagdst) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/test/symbolic_expression_test.cc#L639)):*
You're right. There are many `q`s which violate the assertion.

>  If so, that might be an argument for cancelling numbers symbolically when possible. Definitely not needed for this PR, though.

I'll think about how to implement the symbolic cancellation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression_cell.cc, line 963 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-KcOkC_AdlH3Eiwb7v8q:-KcPNfiHMwaLUjV_9hfn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ccbdff634cf4d65f9b25f1ef8836d438b646918d/drake/common/symbolic_expression_cell.cc#L963)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

It's kind of far away.  I was suggesting something like the following, right here:

```
// As a precondition, this expression `is_polynomial`, so the exponent is an
// integer and this cast does not change its value.
```

and similar remarks for multiplication and division
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcPX-KV2phORNIjj5VP:bnfp4nl)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5073#-:-KcPf5MjJOY78agasCs8:b-l70wzf)*

**Pull request merged**
