### PR TITLE
multibody: Use spatial_algebra.h as the sole header for the package

### LINKED ISSUE #14097: spatial_algebra: `Class::dot` implementations cause dependency cycles
From merge-base 9b7cae4c56e, when writing bindings for some of the `SpatialVector` derived classes, I got the following runtime error when running the Python unittest:
```
    from pydrake.multibody.math import (                                                               
ImportError: ...runfiles/drake/bindings/pydrake/multibody/math.so: undefined symbol: _ZNK5drake9multibody15SpatialVelocityIdE3dotERKNS0_12SpatialForceIdEE
```

Looking into it, it's because the `::dot` definitions are defined in `spatial_algebra.h`???
https://github.com/RobotLocomotion/drake/blob/19a15cd364efe6ef8d23ece115375948b546810c/multibody/math/spatial_algebra.h

EDIT (2020-09-22):

Two issues:
- [x] #14113 The symbols are not compiled into `//:drake_shared_library`
- [ ] The dependency cycles may mean that partial includes could happen (compile time) or some symbols may not be linked (linking time)

FYI @jwnimmer-tri

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Including the individual headers one at a time might leave the dot product operations undefined.

Use DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS.

Closes #14097.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.
+@sammy-tri for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: pending one assurance: that the addition of DRAKE_DECLARE_... in the headers does not _prevent_ the compilers from inlining the small methods that should be inlined. I don't think it does but I realize I'm uncertain about that. If you know for sure, please say so or let me know if you want me to check empirically.

> Reviewed 35 of 39 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117#-:-MI-v-H36eASinAn90u4:b8gu6v4)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
That's also my understanding from everything I've read, but I don't know that I've ever tried to disprove it.  I can locally A/B the cassie benchmark vs this PR if you like?

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with faith in the compiler to still inline small methods.  Not pressing the merge button though, I'll let Jeremy and Sherm decide if they feel the need to prove inlining is still working.

> Reviewed 35 of 39 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117#-:-MI03Rlk5sFoGArkVDJG:b-5ptpg6)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Since I've been studying inlining problems in MBP I'll pull this and verify inlining directly. Hold for results ...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117#-:-MI05w5JDxK4wWyLuLN9:b-eljb7e)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Here is the somewhat-disturbing result: putting the DECLAREs in the header **does** prevent inlining, at least sometimes, in gcc 7.5. The particular case I explored in depth was this:
- I found that MBTree's CalcKineticEnergy() method uses SpatialMomentum::dot(SpatialVelocity).
- I added a CalcKineticEnergy() call to cassie_bench so that it would show up in kcachegrind.
- I looked at this in master and the call to dot was inlined (it is only 8 instructions).
- I looked at this in the present pr and the call was not inlined.
- I edited the source to remove the DECLAREs at the end of all of the spatial_* headers. (I still left the DEFINEs in the .cc file.)
- Reran and kcachegrind now shows the dot() is inlined.

Please remove the DECLAREs and then this is all good. Cassie benchmark times were not noticeably affected either way. 

I'd suggest leaving a comment where the DECLAREs were saying not to add them back to avoid discouraging inlining for the methods defined in the header.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117#-:-MI0SF1U02mXPWaTjdR6:bxaozyp)* status: labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
> I added a CalcKineticEnergy() call to cassie_bench so that it would show up in kcachegrind.

Please post this patch somewhere (gist, or branch, or ...) so that others can replicate your experiment in perpetuity.

**Comment by jwnimmer-tri** [comment]
From reading up in more detail, the extra function call may be because I did not say `inline` on the four out-of-class method definitions for `dot`.  Once you post the reproduction details, I can try adding `inline` and see what happens.

**Comment by sherm1** [comment]
Good thought -- I tried adding `inline` to the dot() definitions (in spatial_velocity.h). That had no effect. So I removed those and instead put the inline on the declarations (in three files). That worked! TIL it matters where that `inline` goes. Repro instructions to follow.

**Comment by sherm1** [comment]
This is the only change required to the benchmark:
```
diff --git a/examples/multibody/cassie_benchmark/test/cassie_bench.cc b/examples/multibody/cassie_benchmark/test/cassie_bench.cc
index 5c4157c2f..c1e19e9c3 100644
--- a/examples/multibody/cassie_benchmark/test/cassie_bench.cc
+++ b/examples/multibody/cassie_benchmark/test/cassie_bench.cc
@@ -140,6 +140,7 @@ BENCHMARK_F(CassieDoubleFixture, DoubleMassMatrix)(benchmark::State& state) {
     InvalidateState();
     plant_->CalcMassMatrix(*context_, &M);
     tracker.Update(guard.num_allocations());
+    plant_->CalcKineticEnergy(*context_);
   }
 }
```

Then run it with this command:
```
bazel run --copt=-g --strip=never --run_under='valgrind --tool=callgrind --callgrind-out-file=/tmp/xxx.out --dump-instr=yes --collect-jumps=yes' //examples/multibody/cassie_benchmark:cassie_bench
```
and invoke kcachegrind with ` kcachegrind /tmp/xxx.out`.

Once in kcachegrind, search for CalcKineticEnergy. You should see three; pick MBTree::CalcKineticEnergy(). You can display the source code in the upper right window. The "dot()" line is second-to-last. You will see the call to the non-inlined method there, and you can look at the machine code in the lower right window.

If you add the `inline` keywords to the dot _declarations_ and repeat the above, you'll see the source code no longer shows the call. Click on the "dot()" line while the machine code is displayed and it will take you right to the inlined 8 instructions.

**Review by sherm1 — COMMENTED** [review]
My thought now is that you can leave in the DECLAREs if you like as long as the declarations for the deferred methods are marked `inline`. That seems preferable since it avoids special treatment for these files. It does suggest that we should advise placement of inline with declarations rather than definitions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117#-:-MI0seeV4i8MJKHXjnxf:b8mgoob)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @sherm1)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @sherm1)

**Comment by jwnimmer-tri** [comment]
I'll need to dig more into the `inline` consequences for a styleguide / default_scalars follow-up.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14117)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Pull request merged**
