### PR TITLE
dualshock: Update example to use Logitech controller

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Confirmed using demo program from:
https://www.pygame.org/docs/ref/joystick.html#controller-mappings

---

Playing with this for some Anzu work, using a slightly ancient controller that I've had for 10 years: `Logitech G-UF13A`

Their website ain't too informative: https://support.logi.com/hc/en-us/articles/360024782693

\cc @darshanhegde 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sammy-tri for both reviews, please
+(status: single reviewer ok) 

\cc @siyuanfeng-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388#-:-MNKJxrs7UpyVoyunmky:bbjlj8i)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI and @sammy-tri)

___
*[examples/manipulation_station/end_effector_teleop_dualshock4.py, line 137 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14388#-MNOWBRUCRJe4PTTgcGT:-MNOWBRUCRJe4PTTgcGU:b264v0q) ([raw file](https://github.com/robotlocomotion/drake/blob/c28b9d177d226c7a8671231ff7a9769fc9890e3e/examples/manipulation_station/end_effector_teleop_dualshock4.py#L137)):*
> ```Python
>         # https://www.pygame.org/docs/ref/joystick.html#controller-mappings
>         if self._name == "Logitech Logitech Dual Action":
>             events[DS4Axis.LEFTJOY_UP_DOWN] = self._axis_data[0]
> ```

Working: Er, found that I needed to swap these. Will do so.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[examples/manipulation_station/end_effector_teleop_dualshock4.py, line 137 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14388#-MNOWBRUCRJe4PTTgcGT:-MNQGucvDyMh2eA5cbo_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c28b9d177d226c7a8671231ff7a9769fc9890e3e/examples/manipulation_station/end_effector_teleop_dualshock4.py#L137)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Er, found that I needed to swap these. Will do so.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14388#-:-MNQIRVtCHKYU6v7vcg3:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Pull request merged**
