### PR TITLE
drake_py: Remove alias from isolated targets; rename prefix from `_isolated/` to `py/`

### LINKED ISSUE #8557: Labels (names) for python tests are confusing
Bazel's test output looks like this (taken from CI, for example):
```
//bindings/pydrake/examples:_isolated/acrobot_test                       PASSED in 6.1s
//bindings/pydrake/examples:acrobot_test                                 PASSED in 6.1s
```
However, this is really just one test (its `alias`ed).

The problem is that only one of the labels is actually usable for developers:
```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel test //bindings/pydrake/examples:acrobot_test
...
ERROR: No test targets were found, yet testing was requested

jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel test //bindings/pydrake/examples:_isolated/acrobot_test
...
INFO: Found 1 test target...
...
Executed 1 out of 1 test: 1 test passes.
```

Having labels that don't work seems unhelpful.  Can we remove the `alias()` calls?

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8557

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724#-:-LBNgvDsBDOQI8dg0oer:b-qf68jg)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBNnN954z3-L2isKets:-LBNnN954z3-L2isKett:b-u9n826) (no related file):*
Per #8557 discussion, I did not realize that the auto-complete would only find the wrong-named version (without `_isolated`).  If that's true, what do you think about having the unadorned `name` really still exist, but instead of an alias be a test marked "manual" that errors out telling the user the correctly adorned name?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBNnN954z3-L2isKets:-LBNwcAj5_WjDiDHo56v:bfxicz8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Per #8557 discussion, I did not realize that the auto-complete would only find the wrong-named version (without `_isolated`).  If that's true, what do you think about having the unadorned `name` really still exist, but instead of an alias be a test marked "manual" that errors out telling the user the correctly adorned name?
</blockquote></details>

That'd would work! I had briefly tried to think about how to intercept that at the Bazel macro level, but making a test itself makes much more sense. Will put that together.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBNnN954z3-L2isKets:-LBOa7wD9HLgar-Ygw8R:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

That'd would work! I had briefly tried to think about how to intercept that at the Bazel macro level, but making a test itself makes much more sense. Will put that together.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by jwnimmer-tri** [comment]
:lgtm:  Tested locally with tab-completion and etc.

+@sammy-tri for platform review, please.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/skylark/drake_py.bzl, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQgS99-0tz-I_aS6uC:-LBQgS99-0tz-I_aS6uD:b7v5l3f) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L21)):*
> ```Python
>     )
>     content = """#!/bin/bash
> echo "Label '{bad_target}' is deprecated; please use '{good_target}'." >&2
> ```

BTW It would help to print the word error here, for better grepping.  To be consistent with Bazel output, perhaps `ERROR: ` as a prefix here would be good.

---

*[tools/skylark/drake_py.bzl, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQgzAJBKxATTrNFthx:-LBQgzAJBKxATTrNFthy:b-9ak7ry) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L39)):*
> ```Python
>     },
>     test = True,
>     implementation = _deprecated_target_impl,
> ```

BTW Rule name and impl here are inconsistent on `_test` vs `_target`.

---

*[tools/skylark/drake_py.bzl, line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQfyG1ADzSaz3fpBcy:-LBQfyG1ADzSaz3fpBcz:beuxd2e) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L71)):*
> ```Python
>             visibility = visibility,
>             **kwargs)
>         # Deprecate alias.
> ```

BTW I don't think "deprecate" makes sense here, and "alias" might not really mean anything to the reader either.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724#-:-LBQhKy97_8W7KCpzSTa:b-fqsyl3)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/skylark/drake_py.bzl, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQgS99-0tz-I_aS6uC:-LBQzi-K-866gGJTIIbt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW It would help to print the word error here, for better grepping.  To be consistent with Bazel output, perhaps `ERROR: ` as a prefix here would be good.
</blockquote></details>

Done.

---

*[tools/skylark/drake_py.bzl, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQgzAJBKxATTrNFthx:-LBQziajDdwU1QV20UfD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Rule name and impl here are inconsistent on `_test` vs `_target`.
</blockquote></details>

Done.

---

*[tools/skylark/drake_py.bzl, line 71 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQfyG1ADzSaz3fpBcy:-LBQzj4v-LMVqydWr2si:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I don't think "deprecate" makes sense here, and "alias" might not really mean anything to the reader either.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/skylark/drake_py.bzl, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8724#-LBQgS99-0tz-I_aS6uC:-LBR-hIU5XJXBTXARckD:b-ioniwx) ([raw file](https://github.com/robotlocomotion/drake/blob/368874c25832fb8452d9730eca6df39bc54bb616/tools/skylark/drake_py.bzl#L21)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Good for CDash too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8724#-:-LBRjexeB6rxIfvPnWeR:bnfp4nl)*

**Pull request merged**
