### PR TITLE
[geometry] Promote RenderEngineGltfClient to public

### LINKED ISSUE #18423: RenderRpc: Add the libcurl external to wheel builds
- [x] Add `libcurl` to the wheel builds (Done by #17755)
- [ ] Revert #17697

### PR DESCRIPTION
**Pull request by zachfang**
Closes #18423.
Reverts #17697.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18480)

### CODE REVIEW

**Comment by zachfang** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by zachfang** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
To me, that looks like the Wheel build of VTK contains a mistake which makes the `<vtkGLTFExporter.h>` unusable (unable to link it's required JSON dependency).

\CC @mwoehlke-kitware @svenevs

**Comment by mwoehlke-kitware** [comment]
It looks like something wants libvtkjsoncpp, but nothing links it. AFAIK nothing has changed on the VTK side recently; did Drake stop linking that at some point?

As the only shared library, *libdrake.so* needs to link it explicitly. Maybe that happens in `tools/workspace/vtk/repository.bzl` but in any case, I suspect the fix needs to be in Bazel, not in the wheel VTK build.

**Comment by jwnimmer-tri** [comment]
> ... did Drake stop linking that at some point?

The new change as of this PR is that we now depend on calling code in `<vtkGLTFExporter.h>`, which presumably now _adds_ vtkjsoncpp as an actual dependency, whereas it was not so previously.  For the non-wheel builds, we use the plain `jsoncpp` Ubuntu library (`./tools/workspace/vtk/image/vtk-args\0261:VTK_MODULE_USE_EXTERNAL_VTK_jsoncpp:BOOL=ON`).  For the wheel builds, we build the vendored copy statically.

In any case, I agree the probable fix is to `drake/tools/workspace/vtk/repository.bzl` to link `vtkjsoncpp` in `vtkIOExport` when in the wheel configuration.

**Comment by zachfang** [comment]
~~From the above assessment, this is what I found:
In `tools/wheel/image/vtk-args`, we have `VTK_MODULE_USE_EXTERNAL_VTK_jsoncpp:BOOL=OFF`.
But in `tools/workspace/vtk/image/vtk-args`, we have `VTK_MODULE_USE_EXTERNAL_VTK_jsoncpp:BOOL=ON`.
Can that be the difference? (I am not too familiar with the Wheel build process.)~~

To help debug a similar issue next time, how do you spot `libvtkjsoncpp` to be the problem? I didn't see anything obvious from the CI log.

**Comment by jwnimmer-tri** [comment]
> ... how do you spot libvtkjsoncpp to be the problem?

The missing symbol is `undefined symbol: _ZN7vtkJson5ValueC1ENS_9ValueTypeE`.  Matthew just happened to know that that symbol comes from `libvtkjsoncpp`.

**Comment by mwoehlke-kitware** [comment]
> Matthew just happened to know that that symbol comes from `libvtkjsoncpp`.

Not "just happened". I hopped into a docker image that already had Drake built and did a `grep -R _ZN7vtkJson5ValueC1ENS_9ValueTypeE /opt`. (You can obtain such an image locally using the `-s` option when building a wheel.) Of the several hits, `libvtkjsoncpp` looked most likely to be the provider, with the others appearing more likely to be consumers.

> the probable fix is to `drake/tools/workspace/vtk/repository.bzl` to link `vtkjsoncpp` in `vtkIOExport` when in the wheel configuration

Agreed. (Note that it looks like a `_vtk_cc_library` for `vtkjsoncpp` will also be needed.)

**Comment by zachfang** [comment]
@mwoehlke-kitware Can you help me unpack what you meant in your previous comment?
This is what I have after looking through the relevant files.

```
+    file_content += _vtk_cc_library(
+        os_result,
+        "vtkjsoncpp",
+        hdrs = [
+            "vtk_jsoncpp.h",
+        ],
+        deps = [
+            ":vtkCommonCore",
+            ":vtksys",
+        ],
+    )
+
     # Indirect dependency: omit headers.
     file_content += _vtk_cc_library(
         os_result,
@@ -624,6 +636,7 @@ licenses([
             ":vtkRenderingCore",
             ":vtkRenderingFreeType",
             ":vtkRenderingVtkJS",
+            ":vtkjsoncpp",   # In vtkIOExport section.
             ":vtklibharu",
         ],
     )

zachfang@91308-ZFang:~/drake$ bazel build //geometry/render_gltf_client/...
INFO: Invocation ID: c661d37c-e983-4be6-aaae-7b374d73a47d
INFO: Analyzed 92 targets (60 packages loaded, 8641 targets configured).
INFO: Found 92 targets...
ERROR: /home/zachfang/.cache/bazel/_bazel_zachfang/a6b58412806f8cea4c40b3f87d2b264e/external/vtk/BUILD.bazel:181:11: SolibSymlink _solib_k8/_U@vtk_S_S_Cvtkjsoncpp___Ulib/libvtkjsoncpp-9.1.so.1 failed: missing input file 'external/vtk/lib/libvtkjsoncpp-9.1.so.1', owner: '@vtk//:lib/libvtkjsoncpp-9.1.so.1'
ERROR: /home/zachfang/.cache/bazel/_bazel_zachfang/a6b58412806f8cea4c40b3f87d2b264e/external/vtk/BUILD.bazel:181:11: SolibSymlink _solib_k8/_U@vtk_S_S_Cvtkjsoncpp___Ulib/libvtkjsoncpp-9.1.so.1 failed: 1 input file(s) do not exist
ERROR: /home/zachfang/.cache/bazel/_bazel_zachfang/a6b58412806f8cea4c40b3f87d2b264e/external/vtk/BUILD.bazel:181:11 SolibSymlink _solib_k8/_U@vtk_S_S_Cvtkjsoncpp___Ulib/libvtkjsoncpp-9.1.so.1 failed: 1 input file(s) do not exist
INFO: Elapsed time: 2.396s, Critical Path: 0.06s
INFO: 6 processes: 6 internal.
FAILED: Build did NOT complete successfully
```

**Comment by jwnimmer-tri** [comment]
The deps on `vtkjsoncpp` should _only_ be added for the wheel builds (i.e., it should be guarded by `os_result.is_manylinux or os_result.is_macos_wheel` within `repository.bzl`); it should _not_ be part of the regular builds.

See https://github.com/RobotLocomotion/drake/tree/master/tools/wheel for instructions on how to build the wheel locally.

**Comment by EricCousineau-TRI** [comment]
FYI for tool:
```sh
echo _ZN7vtkJson5ValueC1ENS_9ValueTypeE | c++filt
vtkJson::Value::Value(vtkJson::ValueType)
```

**Comment by EricCousineau-TRI** [comment]
Suggested patch per f2f:
```diff
diff --git a/tools/workspace/vtk/repository.bzl b/tools/workspace/vtk/repository.bzl
index 4762dcf1f2..75bf3582b1 100644
--- a/tools/workspace/vtk/repository.bzl
+++ b/tools/workspace/vtk/repository.bzl
@@ -600,6 +600,21 @@ licenses([
         ],
     )
 
+    maybe_vtk_io_export_deps = []
+    if os_result.is_manylinux or os_result.is_macos_wheel:
+        file_content += _vtk_cc_library(
+            os_result,
+            "vtkjsoncpp",
+            hdrs = [
+                "vtk_jsoncpp.h",
+            ],
+            deps = [
+                ":vtkCommonCore",
+                ":vtksys",
+            ],
+        )
+        maybe_vtk_io_export_deps.append(":vtkjsoncpp")
+
     file_content += _vtk_cc_library(
         os_result,
         "vtkIOExport",
@@ -625,7 +640,7 @@ licenses([
             ":vtkRenderingFreeType",
             ":vtkRenderingVtkJS",
             ":vtklibharu",
-        ],
+        ] + maybe_vtk_io_export_deps,
     )
 
     file_content += _vtk_cc_library(
```

**Comment by zachfang** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

Tested locally on my Focal Ubuntu. Added `vtkfreetype` due to the error messages when without it.
```
#21 24.14 ImportError: /root/.cache/bazel/_bazel_root/9c657d4c689a350936e2c881814ca8d6/sandbox/processwrapper-sandbox/2904/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/stubgen.runfiles/drake/bindings/pydrake/common/../../../_solib_k8/_U_S_Stools_Sinstall_Slibdrake_Cdrake_Ushared_Ulibrary___Utools_Sinstall_Slibdrake/libdrake.so: undefined symbol: vtkfreetype_FTC_Manager_New
```

**Comment by zachfang** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by zachfang** [comment]
@mwoehlke-kitware Would you be available to feature review this PR?

**Comment by jwnimmer-tri** [comment]
@zachfang You should also ask Jenkins to run both of the macOS experimental wheel builds (x86 and arm).

**Comment by zachfang** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18480)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

___
*[`tools/workspace/vtk/repository.bzl` line 614 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18480#-NJpmPKn6wLJv5c_BQV4:-NJpmPKn6wLJv5c_BQV5:b-4v570d) ([raw file](https://github.com/robotlocomotion/drake/blob/2003ead76299bd5be4dd60ee87312ee14f99ab48/tools/workspace/vtk/repository.bzl#L614)):*
> ```Starlark
>         )
>         file_content += _vtk_cc_library(os_result, "vtkjsoncpp")
>         maybe_include_vtkjsoncpp = [":vtkjsoncpp", ":vtkfreetype"]
> ```

It's probably worth repeating the comment about static linking here. We also don't seem to use "maybe_" names anywhere else, and... well, the suggested refactoring *is* used elsewhere. (This will require a corresponding change below. Note also I swapped the list items so they are in lexicographical order, though it might be better to use `.append` after each `_vtk_cc_library`.)



_Suggestion:_
```Starlark
    vtk_io_export_deps = [
        ":vtkCommonCore",
        ":vtkCommonDataModel",
        ":vtkCommonMath",
        ":vtkCommonTransforms",
        ":vtkFiltersGeometry",
        ":vtkImagingCore",
        ":vtkIOCore",
        ":vtkIOGeometry",
        ":vtkIOImage",
        ":vtkIOXML",
        ":vtkRenderingContext2D",
        ":vtkRenderingCore",
        ":vtkRenderingFreeType",
        ":vtkRenderingVtkJS",
        ":vtklibharu",
    ]

    if os_result.is_manylinux or os_result.is_macos_wheel:
        # Normally these would be a private dependencies, but no such thing
        # when VTK is built static.
        file_content += _vtk_cc_library(
            os_result,
            "vtkfreetype",
            deps = [
                ":vtkkwiml",
                "@zlib",
            ],
        )
        file_content += _vtk_cc_library(os_result, "vtkjsoncpp")
        vtk_io_export_deps += [":vtkfreetype", ":vtkjsoncpp"]
```
___
*[`tools/workspace/vtk/repository.bzl` line 641 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18480#-NJppZhG5eVJawK0lAnM:-NJppZhG5eVJawK0lAnN:b-7333pu) ([raw file](https://github.com/robotlocomotion/drake/blob/2003ead76299bd5be4dd60ee87312ee14f99ab48/tools/workspace/vtk/repository.bzl#L641)):*
> ```Starlark
>             ":vtkRenderingVtkJS",
>             ":vtklibharu",
>         ] + maybe_include_vtkjsoncpp,
> ```

(To match the above suggestion...)



_Suggestion:_
```Starlark
        deps = vtk_io_export_deps,
```

**Comment by zachfang** [comment]
The macOS CIs failed with:
```
[1:23:56 PM]  INFO: From Linking external/spdlog/libdrake_spdlog.so [for host]:
[1:23:56 PM]  ld: warning: -undefined dynamic_lookup may not work with chained fixups
[1:23:56 PM]  [5,685 / 6,032] Compiling src/spdlog.cpp; 1s darwin-sandbox ... (4 actions, 3 running)
[1:23:58 PM]  INFO: From Linking external/spdlog/libdrake_spdlog.so:
[1:23:58 PM]  ld: warning: -undefined dynamic_lookup may not work with chained fixups
[1:25:22 PM]  [5,764 / 6,034] Compiling multibody/plant/tamsi_driver.cc; 8s darwin-sandbox ... (4 actions, 3 running)
[1:27:01 PM]  [5,866 / 6,034] Compiling systems/sensors/accelerometer.cc; 6s darwin-sandbox ... (4 actions, 3 running)
[1:27:29 PM]  ERROR: /Users/admin/workspace/mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release/src/tools/install/libdrake/BUILD.bazel:67:10: Linking tools/install/libdrake/libdrake.so failed: (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/tools/install/libdrake/libdrake.so-2.params
[1:27:29 PM]  
[1:27:29 PM]  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
[1:27:29 PM]  ld: file not found: SystemConfiguration
[1:27:29 PM]  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1:27:29 PM]  Error in child process '/usr/bin/xcrun'. 1
[1:27:29 PM]  external/local_config_cc/cc_wrapper.sh: line 69: 44131 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
[1:27:29 PM]  Target //:install failed to build
[1:27:29 PM]  Use --verbose_failures to see the command lines of failed build steps.
[1:27:29 PM]  INFO: Elapsed time: 762.288s, Critical Path: 34.20s
[1:27:29 PM]  INFO: 5923 processes: 3098 internal, 2819 darwin-sandbox, 6 worker.
[1:27:29 PM]  FAILED: Build did NOT complete successfully
[1:27:29 PM]  ERROR: Build failed. Not running target
```

I see many warnings but no undefined reference this time, though. This line seems the most suspicious (to me): `[1:27:29 PM]  ld: file not found: SystemConfiguration`. Investigating.

**Review by sherm1 — COMMENTED** [review]
+@mwoehlke-kitware for feature review (to make Reviewable happy)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18480#-:-NJrK8s05Uw6WgNRMMsB:bgzn5c7)* status: 2 unresolved discussions, LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware and @zachfang)

**Review by zachfang — COMMENTED** [review]
I am a bit stuck on fixing the macOS wheel CI since the error messages seem vague (to me). I reproduced the same error on a local mac machine and added different `deps` (somehow arbitrarily), which yielded the same result. Any pointer to debug this would be appreciated :thinking:. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18480#-:-NJrnuVWBvhb0s7iMO6g:bci3biw)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/vtk/repository.bzl` line 614 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18480#-NJpmPKn6wLJv5c_BQV4:-NJrn39-7WNO1M27HcpV:bfw9uhy) ([raw file](https://github.com/robotlocomotion/drake/blob/2003ead76299bd5be4dd60ee87312ee14f99ab48/tools/workspace/vtk/repository.bzl#L614)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

It's probably worth repeating the comment about static linking here. We also don't seem to use "maybe_" names anywhere else, and... well, the suggested refactoring *is* used elsewhere. (This will require a corresponding change below. Note also I swapped the list items so they are in lexicographical order, though it might be better to use `.append` after each `_vtk_cc_library`.)
</blockquote></details>

Done. I also changed to append each `cc_library` as suggested.
___
*[`tools/workspace/vtk/repository.bzl` line 641 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18480#-NJppZhG5eVJawK0lAnM:-NJrnsch3jEM_fJOfkG5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2003ead76299bd5be4dd60ee87312ee14f99ab48/tools/workspace/vtk/repository.bzl#L641)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

(To match the above suggestion...)
</blockquote></details>

Done.

**Review by mwoehlke-kitware — COMMENTED** [review]
FWIW, that link may be coming from `tools/workspace/curl_internal/package.BUILD.bazel:139`? I wonder if that's out-of-date?

:lgtm: otherwise...

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18480#-:-NJub2h9CvPU7v1_ciJ5:bya397j)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @zachfang)

**Comment by zachfang** [comment]
After some tinkering, I confirmed the current error messages are from that line, `curl_internal/package.BUILD.bazel:139`.

The macOS wheel was built successfully without it, but then the normal build failed, i.e., `bazel build //geometry/render_gltf_client/...`.

Failure during a normal Bazel build. 
```
zachfang@macsim-m1-0 drake % bazel build //geometry/render_gltf_client/...        
INFO: Analyzed 92 targets (1 packages loaded, 258 targets configured).
INFO: Found 92 targets...
INFO: From Linking geometry/render_gltf_client/internal_http_service_curl_test:
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ERROR: /Users/zachfang/drake/geometry/render_gltf_client/BUILD.bazel:243:16: Linking geometry/render_gltf_client/client_demo failed: (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/geometry/render_gltf_client/client_demo-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Undefined symbols for architecture arm64:
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in liblibcurl.a(hostip.pic.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 96417 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
INFO: Elapsed time: 4.866s, Critical Path: 0.84s
INFO: 11 processes: 9 internal, 2 darwin-sandbox.
FAILED: Build did NOT complete successfully
zachfang@macsim-m1-0 drake %
```
The wheel build succeeded after removing the two lines.
```
zachfang@macsim-m1-0 drake % git diff
diff --git a/tools/workspace/curl_internal/package.BUILD.bazel b/tools/workspace/curl_internal/package.BUILD.bazel
index 3cbecd4282..afcd2b81bb 100644
--- a/tools/workspace/curl_internal/package.BUILD.bazel
+++ b/tools/workspace/curl_internal/package.BUILD.bazel
@@ -135,8 +135,6 @@ _LINKOPTS = select({
     "@drake//tools/cc_toolchain:apple": [
         "-Wl,-framework",
         "-Wl,CoreFoundation",
-        "-Wl,-framework",
-        "-Wl,SystemConfiguration",
     ],
     "//conditions:default": [],
 })
zachfang@macsim-m1-0 drake % git status
On branch feature/revert-17697-sandbox
Your branch is up to date with 'zach/feature/revert-17697-sandbox'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tools/workspace/curl_internal/package.BUILD.bazel

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	drake-1.10.0-cp310-cp310-macosx_12_0_arm64.whl
```

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

we're taking a look, thinking maybe arm vs x86

**Comment by jwnimmer-tri** [comment]
To me, the error message reads like a string quoting / grouping problem when passing arguments to the linker, not a missing library problem.

**Comment by mwoehlke-kitware** [comment]
> the error message reads like a string quoting / grouping problem

Um. That could be... something elsewhere in the logic that is wheel-specific and breaks things later?

**Comment by jwnimmer-tri** [comment]
The error message mentions `bazel-out/darwin_arm64-opt/bin/tools/install/libdrake/libdrake.so-2.params` (i.e., the linker manifest file).  As a next debugging step, I suggest that someone who can run both the wheel build and non-wheel build on macOS investigate the contents of that file in both cases.

**Comment by mwoehlke-kitware** [comment]
Huh. This is odd:
```
-Wl,-framework
-Wl,CoreFoundation
-Wl,SystemConfiguration
```

I wonder if something is removing "duplicate" `-Wl` arguments? I notice that `-Wl` doesn't seem to be used for other frameworks... In fact, I see stuff like `linkopts = ["-framework OpenCL"]` which makes me think splitting must be happening somewhere downstream as well...

**Comment by mwoehlke-kitware** [comment]
Well, I think I'm at a loss. It seems something is removing the second "[-Wl,]-framework" from `_LINKOPTS` in `workspace/curl_internal/package.BUILD.bazel`. But it's beyond my Bazel knowledge to guess *what*.

**Comment by jwnimmer-tri** [comment]
Everywhere else in Drake specifies a `-framework Foo` flag a single string, instead of split in two.  Have you attempted either of these two spellings?

```py
_LINKOPTS = select({
    "@drake//tools/cc_toolchain:apple": [
        "-Wl,-framework -Wl,CoreFoundation",
        "-Wl,-framework -Wl,SystemConfiguration",
    ],
    "//conditions:default": [],
})
```

or

```py
_LINKOPTS = select({
    "@drake//tools/cc_toolchain:apple": [
        "-framework CoreFoundation",
        "-framework SystemConfiguration",
    ],
    "//conditions:default": [],
})
```

**Comment by mwoehlke-kitware** [comment]
I already tried that, yes. There was no change. (Well, no "-Wl"s, but the second "-framework" still goes missing.)

**Comment by mwoehlke-kitware** [comment]
Okay, so... `-Wl,-framework,SystemConfiguration` works. That can get this PR unstuck, but doesn't answer what's doing the deduplication in the first place, or why it only affects this library, or why it seems to only happen on wheel builds.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please
@drake-jenkins-bot mac-arm-monterey-unprovisioned-clang-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
The macOS wheels passed.  I'll check the Ubuntu one as well to be on the safe side.

@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-:-NLb0DX39OfhQ5fS3jWe:b-vtj4vo)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform w/ nit for clarified wording, nice!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-:-NLbBRzv4lSG9fmofW0A:bywg1xr)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`tools/workspace/vtk/repository.bzl` line 622 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-NLbB4kf1KjpFF4bj0Fb:-NLbB4kg65utuwRs7Rcy:bbxebw5) ([raw file](https://github.com/RobotLocomotion/drake/blob/6574c0556ea326c0cff6ca9be2c18dca386653fb/tools/workspace/vtk/repository.bzl#L622)):*
> ```Starlark
> 
>     if os_result.is_manylinux or os_result.is_macos_wheel:
>         # Normally these would be private dependencies, but no such thing when
> ```

nit "no such thing" doesn't make it immediately clear to me what it means; also, I don't understand in what sense they're private.

Is it possible to better specify the wording and the context of "private"? (Bazel private, link-time private, etc.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18480)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`tools/workspace/vtk/repository.bzl` line 622 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-NLbB4kf1KjpFF4bj0Fb:-NLbLhkM2xDsenLEdq1u:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6574c0556ea326c0cff6ca9be2c18dca386653fb/tools/workspace/vtk/repository.bzl#L622)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "no such thing" doesn't make it immediately clear to me what it means; also, I don't understand in what sense they're private.

Is it possible to better specify the wording and the context of "private"? (Bazel private, link-time private, etc.)
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18480)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[`tools/workspace/vtk/repository.bzl` line 622 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-NLbB4kf1KjpFF4bj0Fb:-NLbRqTO7MOQBKTLogi4:b-w196av) ([raw file](https://github.com/RobotLocomotion/drake/blob/6574c0556ea326c0cff6ca9be2c18dca386653fb/tools/workspace/vtk/repository.bzl#L622)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
It's not easy for me to posit what should make it to commit message.
@zachfang can you take point on merging, polishing the commit message when squash merge?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18480#-:-NLbRwt6-bN1hAdXcSpQ:b-w1bjn5)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

**Pull request merged**
