### PR TITLE
Continue deprecating rpy2rotmat

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969#-:-LF-JZls4v9suGkBM2Zp:b9rqlek)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969#-:-LF3lEVnBvyxieWEMQy_:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969#-:-LF3lFsS-sGp0Gq9aKJB:b6vi582)*

**Comment by sherm1** [comment]
Platform pass done. Very nice! I have a few suggestions re API, ptal.

---

Reviewed 23 of 23 files at r1.
Review status: 7 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing

---

*[math/roll_pitch_yaw.h, line 137 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4FTMVCs7rq-Oiq3gB:-LF4FTMW2njkaKUpUhgR:bl4fj3v) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/math/roll_pitch_yaw.h#L137)):*
> ```objc
>   void set_pitch_angle(const T& p)  { roll_pitch_yaw_(1) = p; }
> 
>   /// Set the yaw-angle underlying a %RollPitchYaw.
> ```

Nit: comments are slightly inconsistent. Most say `this` but these two say `a`.

---

*[math/roll_pitch_yaw.h, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4FnJ32krX5hl10EmW:-LF4FnJ32krX5hl10EmX:bfeowot) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/math/roll_pitch_yaw.h#L163)):*
> ```objc
>   RotationMatrix<T> ToRotationMatrix() const;
> 
>   /// Returns the 3x3 matrix representation of `this` %RollPitchYaw.
> ```

Should say that this is the 3x3 matrix representation of the _RotationMatrix_ that corresponds to this rpy sequence. (As opposed to, say, a matrix with rpy on the diagonal.) I think the documentation here should be clear that this is an expensive-but-convenient "sugar" method that is exactly equivalent to RotationMatrix(rpy).ToMatrix3().

I have mixed feelings about this existing at all. It would be better for people to work directly with Rotation matrices, where the ToMatrix3() method is free, than to think they can work with rpy but interpret it as a matrix. Would it be bad to write RotationMatrix(RollPitchYaw(rpy)).ToMatrix3() instead so that the computational cost is visible? 

---

*[math/roll_pitch_yaw.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4GAb78BEatejqzJos:-LF4GAb78BEatejqzJot:bqxodqw) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/math/roll_pitch_yaw.cc#L23)):*
> ```cpp
> 
> template <typename T>
> Matrix3<T> RollPitchYaw<T>::ToMatrix3() const {
> ```

Nit: better to make this one inline (it doesn't require RotationMatrix definitions).

---

*[multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 315 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4K3C2-pkIFUdFzyTa:-LF4K3C2-pkIFUdFzyTb:bz1bnc1) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L315)):*
> ```cpp
>       const drake::math::RollPitchYaw<double> rpy(Eigen::Vector3d::Zero());
>       const Eigen::Vector3d xyz(1, 0, 0);
>       joint_transform.matrix() << rpy.ToMatrix3(), xyz, 0, 0, 0, 1;
> ```

Nit: could be just RotationMatrix().ToMatrix3() right? (Here and several cases below)

---

*[multibody/test/rigid_body_tree/rigid_body_tree_creation_test.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4LHixDvk4NMNaGwoL:-LF4LHixDvk4NMNaGwoM:b17a9hu) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/multibody/test/rigid_body_tree/rigid_body_tree_creation_test.cc#L126)):*
> ```cpp
>     const Eigen::Vector3d xyz = Eigen::Vector3d::Ones();
>     const math::RollPitchYaw<double> rpy(Eigen::Vector3d::Zero());
>     T_r1and2_to_world.matrix() << rpy.ToMatrix3(), xyz, 0, 0, 0, 1;
> ```

Nit: could be just `RotationMatrix().ToMatrix3()` (and below).

(Also consider putting the final row on the next line!)

---

*[solvers/rotation_constraint.h, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4QWIHC26bU2tVpJpE:-LF4QWIHC26bU2tVpJpF:bh33udg) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/solvers/rotation_constraint.h#L71)):*
> ```objc
> /// because it adds one more constraint (when combined with constraints on roll
> /// and yaw).
> /// Note: The Roll-Pitch-Yaw angles follow the convention in @RollPitchYaw,
> ```

Nit:  I don't think the `@` should be here.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 282 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4R0gxDmWNaDVi5Ve1:-LF4R0gxDmWNaDVi5Ve2:b-l4z6eg) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/systems/sensors/test/rgbd_camera_test.cc#L282)):*
> ```cpp
>                                 actual.translation().matrix(), kTolerance));
>     const math::RollPitchYaw<double> rpy(orientation);
>     const math::RotationMatrix<double> R(rpy);
> ```

Minor: consider providing an alias RollPitchYawd and RotationMatrixd in the header files (ugly but conventional). Then this could be:
```c++
const math::RotationMatrixd(math::RollPitchYawd(orientation)) R;
```
You could also do using at top of file to get rid of the math::, then this would be
```c++
const RotationMatrixd(RollPitchYawd(orientation)) R;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969#-:-LF4S7IQ1Y7SAvL_nsJ8:b-56cg6o)*

**Comment by mitiguy** [comment]
Review status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing

---

*[math/roll_pitch_yaw.h, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LF4FnJ32krX5hl10EmW:-LF4fKy81E0Xg4rBZ3KQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3171c6b098e249e620ff5185408137234e3579b0/math/roll_pitch_yaw.h#L163)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Should say that this is the 3x3 matrix representation of the _RotationMatrix_ that corresponds to this rpy sequence. (As opposed to, say, a matrix with rpy on the diagonal.) I think the documentation here should be clear that this is an expensive-but-convenient "sugar" method that is exactly equivalent to RotationMatrix(rpy).ToMatrix3().

I have mixed feelings about this existing at all. It would be better for people to work directly with Rotation matrices, where the ToMatrix3() method is free, than to think they can work with rpy but interpret it as a matrix. Would it be bad to write RotationMatrix(RollPitchYaw(rpy)).ToMatrix3() instead so that the computational cost is visible? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a few minor doc comments and a squash-merge with curated commit comment.

---

Reviewed 20 of 20 files at r2.
Review status: 2 unresolved discussions, platform LGTM from [sherm1]

---

*[math/roll_pitch_yaw.h, line 608 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LFInjf691M-T5DDXata:-LFInjf7BnE0LHBONwUH:bcy0ffe) ([raw file](https://github.com/robotlocomotion/drake/blob/5c938dba594c73df5645a2f595483dc5be9a9d31/math/roll_pitch_yaw.h#L608)):*
> ```objc
> 
> // Abbreviation (alias/typedef) for a RollPitchYaw double scalar type.
> using RollPitchYawd = RollPitchYaw<double>;
> ```

Minor: Should have `///` for doxygen. Also, please consider this:
```c++
/// Abbreviation (alias/typedef) for a RollPitchYaw double scalar type.
/// @relates RollPitchYaw
using RollPitchYawd = RollPitchYaw<double>;
```
That moves the documentation from the drake::math namespace to the RollPitchYaw class which I think makes a lot more sense. The heading says "Related functions" or "Friends and related functions" but is much more likely to be noticed this way.

(Similarly for other officially-sanctioned abbreviations.) 

---

*[math/rotation_matrix.h, line 682 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8969#-LFIouSf3R2F_QnKn_th:-LFIouSf3R2F_QnKn_ti:b2o0l3e) ([raw file](https://github.com/robotlocomotion/drake/blob/5c938dba594c73df5645a2f595483dc5be9a9d31/math/rotation_matrix.h#L682)):*
> ```objc
> 
> // Abbreviation (alias/typedef) for a RotationMatrix double scalar type.
> using RotationMatrixd = RotationMatrix<double>;
> ```

Minor: Needs doxygen comment, and consider 
```c++
/// Abbreviation (alias/typedef) for a RotationMatrix double scalar type.
/// @relates RotationMatrix
using RotationMatrixd = RotationMatrix<double>;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8969#-:-LFIptsNDlGi0Ucc0nOa:b-yccycf)*

**Pull request merged**
