### PR TITLE
Move lcm_vector_gen.py to drake/tools.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@jwnimmer-tri for both levels of review

@RussTedrake @sammy-tri FYI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3686)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm: but perhaps consider waiting until #3680 to merge first?

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3686#-:-KTKupIMk2laLokfmHbb:b-p2tb9p)*

**Comment by jwnimmer-tri** [comment]
Thanks for waiting!  This has conflicts now, but ping me and I'll re-ack anything.

**Comment by david-german-tri** [comment]
Done.

---

Review status: 16 of 27 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3686#-:-KTL32mRleBS05wgbl6m:b-896fix)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 28 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3686)*

**Comment by david-german-tri** [comment]
BTW, a follow-up PR will generalize this to work in namespaces and directories other than `automotive`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3686#-:-KTL5h6YXnrfuv5aZXEz:b-yuht31)*

**Comment by jwnimmer-tri** [comment]
I figured as much.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3686#-:-KTL7naN0ys_zRuds4AS:bgiv1gv)*

**Pull request merged**
