### PR TITLE
Initialize QPController class members.

### PR DESCRIPTION
**Pull request by david-german-tri**
@siyuanfeng-tri for feature review, @sammy-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4501)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4501#-:-KYyWrxj8iWr1HphTpV1:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4501#-:-KYygvTDFlrlXGQG-gB2:bnfp4nl)*

**Comment by RussTedrake** [comment]
could this possibly have resolved #3147?

**Comment by siyuanfeng-tri** [comment]
most likely unrelated. this is fixing the init in my code, not in inst qp.

**Pull request merged**
