### PR TITLE
[multibody] Fix many dtors to not be inline

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We audit and fix a bunch of destructors to be non-defaulted.

Fixing that also points out that some of our "nonsymbolic" docs were lying -- we were compiling for symbolic even though we claimed it was out of scope, so we also fix the docs / macros to add symbolic in a few places.

Towards #21605 and therefore towards #20545.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-:-O09c-mLElSGmF0Sdy2l:b95uado)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 119 of 119 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-:-O09kkEqA8XNsPazS9_J:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`multibody/test_utilities/robot_model.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-O09hVRW2x_R4aHTE9ae:-O09hVRW2x_R4aHTE9af:b-jmvnbc) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3066c22575a6a4886c98db42348095652dce406/multibody/test_utilities/robot_model.cc#L172)):*
> ```cpp
>                plant_->get_name()));
> 
>   // Make and add a manager so that we have access to it and its driver.
> ```

nit This comment looks a bit stale now -- we are not actually making anything in the new spelling?

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-:-O09mHTi28Eo0YIjuZH9:bbnvyd5)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`multibody/test_utilities/robot_model.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-O09hVRW2x_R4aHTE9ae:-O09lxyB1AcHLOKvgaht:bzb60fl) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3066c22575a6a4886c98db42348095652dce406/multibody/test_utilities/robot_model.cc#L172)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit This comment looks a bit stale now -- we are not actually making anything in the new spelling?
</blockquote></details>

I don't yet follow what you're getting at.

Previously, this was a two-prong predicate, both of which were evaluated at runtime.  It's still the same two prongs, but now one of them is evaluated at compile-time.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`multibody/test_utilities/robot_model.cc` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-O09hVRW2x_R4aHTE9ae:-O09o2drA4BOJsrsuubD:bqggxqy) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3066c22575a6a4886c98db42348095652dce406/multibody/test_utilities/robot_model.cc#L172)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't yet follow what you're getting at.

Previously, this was a two-prong predicate, both of which were evaluated at runtime.  It's still the same two prongs, but now one of them is evaluated at compile-time.
</blockquote></details>

nm, I misread the diff. side-by-side cleared it up for me.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 117 of 119 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21604#-:-O0A3SfKAtVCOmFfaXLL:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
