### PR TITLE
Formatted XML model files in drake/automotive/models.

### PR DESCRIPTION
**Pull request by liangfok**
This was done using an XML formatting tool called [Sublime Text Indent Plugin](https://github.com/alek-sys/sublimetext_indentxml).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4374)

### CODE REVIEW

**Comment by liangfok** [comment]
Since this PR modifies automotive models:

+@maddog-tri for feature review please.
+@jwnimmer-tri for platform review please

Thanks.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4374#-:-KYFi1F3fZBg9eCgRo6I:b-y13pod)*

**Comment by jwnimmer-tri** [comment]
:lgtm: pending CI, because only model files changed.  But why do we care how machine-readable-only files are formatted?

**Comment by jwnimmer-tri** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4374)*

**Comment by liangfok** [comment]
Sometimes humans need to read these files to since URDFs have no visual editor and Gazebo's visual editor is lacking in some respects as described here: https://github.com/RobotLocomotion/drake/issues/4355#issuecomment-264869076.

**Comment by jwnimmer-tri** [comment]
Sure.  I would argue that this PR makes the XML data neither more nor less readable, though.

**Comment by liangfok** [comment]
I was reading `stata_garage_p1.sdf` and got distracted by the odd locations of the `</box>` tags, so I decided to format it using a tool. I then figured I'd go ahead and format _all_ of the URDF / SDF files in `drake/automotive/models` for consistency.

**Pull request merged**
