### PR TITLE
Remove automotive from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3129.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6445)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6445#-:-KnjhqXmie3maId2OWMO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6445#-:-KnjhyG7GPEIfVQpGDUn:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6445#-:-KnjmJFLb2XMYZqSUsZ8:bnfp4nl)*

**Pull request merged**
