### PR TITLE
Fix csdp_solver_test on mac.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18906)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@BetsyMcPhail for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18906#-:-NPOrkxBCNcarURdOZzj:bakj438)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-continuous-release please.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: pending CI 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18906#-:-NPP1Tvo1tetK5ZBdgEQ:bwo9p5u)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18906#-:-NPP2DnRAG7pH-HxWjey:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: (pending CI)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18906#-:-NPP2qE7Ei6G5YscuYOV:b6l8f6m)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),BetsyMcPhail (waiting on @hongkai-dai)

**Pull request merged**
