### PR TITLE
doc: Update example asan command

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Relates to #14928

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276#-:-MrU0K5F2pbTMTDk1wyz:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276#-:-MrU2dUX0NoIni3WR3Q6:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

___
*[doc/_pages/bazel.md, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16276#-MrU2Rjz-B0-2h00hVWC:-MrU2Rjz-B0-2h00hVWD:b-5wa39u) ([raw file](https://github.com/robotlocomotion/drake/blob/c5d7b4c1308b712ffd765bafa778fc16e5754493/doc/_pages/bazel.md#L92)):*
> ```Markdown
>   gdb bazel-bin/common/polynomial_test               # Run one test under gdb.
> 
> CC=clang-9 CXX=clang++-9 bazel test -c dbg --config=asan common:polynomial_test # Run one test under AddressSanitizer.
> ```

nit For readability, we need a minimum of two spaces between the sample command and the `#`  comment marker.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/_pages/bazel.md, line 92 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16276#-MrU2Rjz-B0-2h00hVWC:-MrU4GSx5n6j_DBGAyB9:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/c5d7b4c1308b712ffd765bafa778fc16e5754493/doc/_pages/bazel.md#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For readability, we need a minimum of two spaces between the sample command and the `#`  comment marker.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276)* status: needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16276#-:-MrU6Qy39Vvd-s_dnb66:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
