### PR TITLE
[sap] Enable kinematic AutoDiffXd simulation with SAP

### LINKED ISSUE #17647: Improve autodiff experience when using SAP.
**Is your feature request related to a problem? Please describe.**
At the moment, we don't support autodiff with the SAP solver. If SAP is turned on, scalar converting a MultibodyPlant from double to autodiff throws. Any autodiff MultibodyPlant with SAP enabled also throws if one attempts to advance a time step. However, we can make the experience for using autodiff a little smoother when SAP is enabled.

**Describe the solution you'd like**
1. We should clearly document the caveat that autodiff is not fully supported at the moment.
2. We should enable the SAP solver when no constraint is ever added throughout the simulation. This is true when the user only runs kinematics with autodiff + SAP. We should allow `CompliantContactManager` to scalar convert to autodiff and enable the solver to early exit when the scalar type is autodiff and no constraint is added instead of **always** throwing.

**Describe alternatives you've considered**
N/A

**Additional context**
See this slack post for the motivation: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1658959942674469

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- Allow CompliantContactManager to scalar convert to double and AutoDiffXd.
- SapSolver supports AutoDiffXd for solving trivial contact problems (zero constraints).

With these two items, we enable kinematic simulation with SAP + AutoDiffXd.

Closes #17647

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651#-:-N85kpKY3TuCUG8o1W6C:bhg9nc0)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
+@ggould-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651#-:-N8Om8Mr-HXpzMao8VWz:b-irfx5k)* status: 7 unresolved discussions, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @xuchenhan-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651)* status: 7 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: do not merge) for now until all threads below are properly resolved.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651#-:-N8PcnU79Um54vCZCfMK:b-yltsuq)* status: 5 unresolved discussions, labeled "do not merge" (waiting on @amcastro-tri and @ggould-tri)

___
*[`multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8OiwmuBqCrKhl5DXnm:-N8Pa-bo1CCLYmJcP3qY:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

The test description says we do test that the result is v* (and that j=0), but we do not do that here. I think we should.
Also, you might want to use an arbitrary non-zero guess (even NAN?) to verify it does not even participate in the computation.
</blockquote></details>

Done
___
*[`multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Oire02AtPk3aXVpI8:-N8Pa0bj5TztbQD12IYm:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, kNumConstraintEquations
since the number of constraints is one for this case.
</blockquote></details>

Done
___
*[`multibody/plant/compliant_contact_manager.cc` line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Ojacj8fKnPNSl6r21:-N8PaGBV2ddtdxaHwDHz:b-gojm52) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/compliant_contact_manager.cc#L937)):*
> So ideally this implementation would look like return std::make_unique<CompliantContactManager<double>>();

I assume you meant `return std::make_unique<CompliantContactManager<double>>(*this);` instead.

The reason I kept them separate is to future-proof anything we do differently for double and AutoDiffXd. I imagine with handcrafted derivatives for AutoDiffXd there would be additional things to copy for autodiff. Or would that happen only on the solver level but not on the manager level.

If you think that's an unjustified concern, I will fallback to a scalar conversion constructor.
___
*[`multibody/plant/multibody_plant.h` line 107 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Ok-vyCGktnNCcdIeF:-N8Pb1eW8jNo8jmKzohR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/multibody_plant.h#L107)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

You can also run dynamics, for as long as you don't have contact nor other constraints. 
</blockquote></details>

Done.
___
*[`multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8OkpNJ1cywpyWOURSx:-N8Pb_ZfB0b7Okm3XZcs:b-5psaqm) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc#L52)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, maybe move to withing scope of the particular unit test? given that it's only used there.
</blockquote></details>

It's used in two free functions below, so I moved it up here.
___
*[`multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc` line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8OlVwt6_eW0q9L0Nxh:-N8PbUA3DyYpsVuV7lR6:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc#L65)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, "Kinematic" means "there are not units of Kilogram in my model, everything is meters and seconds"
Here your actually do allow models with mass, so I'd say "... and that simulations results for models without constraints stay the same."
</blockquote></details>

Done, thanks.
___
*[`multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8OlNhS531zidNYvi8M:-N8PbEmB6dBNMq9WeXr3:b-cobtyp) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc#L86)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, `10 * kTimeStep`?
</blockquote></details>

Hmm, I have 10 * kTimeStep on my local branch. Perhaps I forgot to push? Anyway, done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651)* status: labeled "do not merge" (waiting on @ggould-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Ojacj8fKnPNSl6r21:-N8PqQzcDGkR53Q8e7N4:b5f9f43) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/compliant_contact_manager.cc#L937)):*
> ... there would be additional things to copy for autodiff.


I might be wrong, but I don't think that'd be the case? For handcrafted derivatives the manager would be converted from `double` to `autodiff` (here) and then when going through the discrete update the manager would try to create a solver/model with `double`.
So for transmogrifying the SapModel, I think you are correct. At the manager level though I don't see this need.

Anyway, marking myself satisfied here.
___
*[`multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8OlNhS531zidNYvi8M:-N8Pr16k7CDFkX7BmAgp:b-cr56zw) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I have 10 * kTimeStep on my local branch. Perhaps I forgot to push? Anyway, done.
</blockquote></details>

I see it now! (before I didn't....)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651#-:-N8QIJR5EOqDvGoi9_b_:b-b9fcpn)* status: labeled "do not merge" (waiting on @amcastro-tri and @ggould-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Ojacj8fKnPNSl6r21:-N8QGEsm7WUSRUzhJivA:btdrsba) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/compliant_contact_manager.cc#L937)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> ... there would be additional things to copy for autodiff.


I might be wrong, but I don't think that'd be the case? For handcrafted derivatives the manager would be converted from `double` to `autodiff` (here) and then when going through the discrete update the manager would try to create a solver/model with `double`.
So for transmogrifying the SapModel, I think you are correct. At the manager level though I don't see this need.

Anyway, marking myself satisfied here.
</blockquote></details>

I see. I added a TODO hear o avoid the additional churn. We can pick this up again when we can meaningfully perform useful autodiff simulation.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17651)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[`multibody/plant/compliant_contact_manager.cc` line 937 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17651#-N8Ojacj8fKnPNSl6r21:-N8QK1g603xye9OWBAGi:bb73djm) ([raw file](https://github.com/robotlocomotion/drake/blob/7f80a77cf0835459200a9bdd27b928048f3cab32/multibody/plant/compliant_contact_manager.cc#L937)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I see. I added a TODO hear o avoid the additional churn. We can pick this up again when we can meaningfully perform useful autodiff simulation.
</blockquote></details>

SGTM

**Pull request merged**
