### PR TITLE
Unrevised lemke solver stub

### PR DESCRIPTION
**Pull request by edrumwri**
Contains stubs for the LCP solver and tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8422)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@hongkai-dai for feature review please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8422#-:-L89Og5ebJPgB0iAsskq:b-8gls7r)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/unrevised_lemke_solver.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8422#-L89SGtMV0w4USyMh0uh:-L89SGtMV0w4USyMh0ui:b1m255g) ([raw file](https://github.com/robotlocomotion/drake/blob/e40e68dba79c5c0390951d6b2205a0afe88df3f7/solvers/unrevised_lemke_solver.h#L27)):*
> ```objc
>   /// @return same as MathematicalProgramSolverInterface::solver_id()
>   static SolverId id();
> };
> ```

BTW we do not really need `UnrevisedLemkeSolverId` class. For example, `id()` can be constructed through https://github.com/RobotLocomotion/drake/blob/master/solvers/nlopt_solver.h#L24~L27

---

*[solvers/test/unrevised_lemke_solver_test.cc, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8422#-L89TsVo4w2sWcnywWWT:-L89TsVo4w2sWcnywWWU:b547g71) ([raw file](https://github.com/robotlocomotion/drake/blob/e40e68dba79c5c0390951d6b2205a0afe88df3f7/solvers/test/unrevised_lemke_solver_test.cc#L66)):*
> ```cpp
> 
> GTEST_TEST(testUnrevisedLCP, testTrivial) {
>   Eigen::Matrix<double, 9, 9> M;
> ```

In case this helps, you could write 
```
M = (Eigen::Matrix<double, 9, 1>() << 1, 2, 3, 4, 5, 6, 7, 8, 9).finished.asDiagonal();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8422#-:-L89UQAZU936csUacgEi:bnfp4nl)*

**Comment by edrumwri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/unrevised_lemke_solver.h, line 27 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-L89SGtMV0w4USyMh0uh:-L89dww95pF9WciPMtXe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e40e68dba79c5c0390951d6b2205a0afe88df3f7/solvers/unrevised_lemke_solver.h#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW we do not really need `UnrevisedLemkeSolverId` class. For example, `id()` can be constructed through https://github.com/RobotLocomotion/drake/blob/master/solvers/nlopt_solver.h#L24~L27
</blockquote></details>

Done.

---

*[solvers/test/unrevised_lemke_solver_test.cc, line 66 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-L89TsVo4w2sWcnywWWT:-L89cVYE0tXBYdaaUBJP:bmggev5) ([raw file](https://github.com/robotlocomotion/drake/blob/e40e68dba79c5c0390951d6b2205a0afe88df3f7/solvers/test/unrevised_lemke_solver_test.cc#L66)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In case this helps, you could write 
```
M = (Eigen::Matrix<double, 9, 1>() << 1, 2, 3, 4, 5, 6, 7, 8, 9).finished.asDiagonal();
```
</blockquote></details>

Done. (I learned this recently from Michel Hidalgo, but this code was just copypasta).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422)*

**Comment by edrumwri** [comment]
+@ggould-tri for platform review please

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-:-L89e4Xo40CGGUXe4IZ4:bffmgsm)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8422)*

**Comment by edrumwri** [comment]
I don't actually want to do factor the tests, because the MobyLcpSolver will be removed once this solver is fully in place. It is to be a feature-complete replacement.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[solvers/unrevised_lemke_solver.cc, line 48 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-L8Coie82Vrykfr-22dE:-L8Dfqq_A_tg-Fi221Ae:b16r5ue) ([raw file](https://github.com/robotlocomotion/drake/blob/dd754fe78476deaef1bf47587410159805963883/solvers/unrevised_lemke_solver.cc#L48)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- I'm not sure you really want to be todo'ing this to me?
</blockquote></details>

Done. I don't think there is anything "to be done" here.

---

*[solvers/unrevised_lemke_solver.cc, line 94 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-L8Cpa4Z6IJy5J6tnmwB:-L8DfypA1fQEGQQpwPCF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd754fe78476deaef1bf47587410159805963883/solvers/unrevised_lemke_solver.cc#L94)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- here again, I don't think I'm the person you want to TODO?
</blockquote></details>

Done.

---

*[solvers/test/unrevised_lemke_solver_test.cc, line 29 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-L8CrQJM71K_eVB5q9jV:-L8DgNZO1W3Oz1FTe8SH:bsmad6y) ([raw file](https://github.com/robotlocomotion/drake/blob/dd754fe78476deaef1bf47587410159805963883/solvers/test/unrevised_lemke_solver_test.cc#L29)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I believe you test the same problem below, in the section copied from the other test.
</blockquote></details>

Done. (Thanks for pointing this out- I didn't realize that the problem was a duplicate. I got it from Cottle's book and used it to test the pivoting sequence of the LCP solver).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-:-L8DgfuR2to9VTHCIDz6:b-r26pal)*

**Comment by ggould-tri** [comment]
Ah!  That clarifies it!
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8422#-:-L8E2An7DNf8ewTy5O2p:bt9caec)*

**Comment by edrumwri** [comment]
Thanks Grant and Hongkai!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8422#-:-L8E8zV-LDhog5BYhJGf:b-bv9df)*

**Pull request merged**
