### PR TITLE
SapContactProblem reports multibody forces.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards fixing https://github.com/RobotLocomotion/drake/pull/18748 , https://github.com/RobotLocomotion/drake/issues/18749 and https://github.com/RobotLocomotion/drake/issues/19068.
Design in https://github.com/RobotLocomotion/drake/issues/19435.

Only specific constraint types know how to compute forces given a set of impulses.
This PR adds the needed minimum infrastructure.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
I made a pass. PTAL, thanks.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-:-NXMYHCy943X5DysvbBn:bj6awcx)* status: 18 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 176 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXM8Mno18p1bHSsIIiL:-NXM8Mno18p1bHSsIIiM:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L176)):*
> ```objc
>    of the two points being constrained. These forces are applied on the objects
>    being constrained, e.g. a rigid body, deformable body or particle. It is the
>    specify constraint type that knows how to map these impulses to physical
> ```

typo



_Suggestion:_
```objc
specific
```
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXM8nyQBNtGcP5tbgOL:-NXM8nyQBNtGcP5tbgOM:bwj0skm) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L178)):*
> ```objc
>    specify constraint type that knows how to map these impulses to physical
>    generalized and/or spatial forces.
>    Constraints will register indexes associated with physical objects at
> ```

FYI, a platform reviewer would tell you to use `indices` over `indexes` in public APIs. We might as well start adopting that spelling in comments/variable names/etc.



_Code quote:_
```objc
indexes
```
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 191 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXM9sxo73FhOK-6yQvC:-NXM9sxo73FhOK-6yQvD:byr0qio) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L191)):*
> ```objc
> 
>   /* Returns the vector of object indexes register with RegisterObjects(). */
>   const std::vector<int>& objects() const { return objects_; }
> ```

It's hard for me to tell what the returned "object indices" index into. Are they indices for `BodyIndex` for rigid and `DeformableBodyIndex` for deformable? A more detailed explanation here is welcome.

Reading more at `SapContactProblem::CalcConstraintMultibodyForces`, it appears it's neither and it's closer to tree indices that the manager understands?
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 225 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMBBBF41HGgzzKVEsD:-NXMBBBF41HGgzzKVEsE:b-se44ku) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L225)):*
> ```objc
>    impulse applied by this constraint on the o-th object.
> 
>    @throws if c < 0 or if c >= num_cliques().
> ```

nit, copypasta



_Code quote:_
```objc
@throws if c < 0 or if c >= num_cliques().
```
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 241 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMU1fj9xhmKEv7Q0ez:-NXMU1fj9xhmKEv7Q0f-:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L241)):*
> ```objc
> 
>   /* Derived constraints must register the indexes of the objects they
>    constraint. After this call, num_objects() will equal objects.size(). See
> ```

typo



_Suggestion:_
```objc
constrain
```
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 243 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMC9u89bIiCIh2dTjp:-NXMC9u96JguSs_ZJTxb:bqvf7cy) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L243)):*
> ```objc
>    constraint. After this call, num_objects() will equal objects.size(). See
>    @ref sap_physical_forces.
>    @throws if called more than once. */
> ```

minor, this is not strictly true. One can call this with `{}` more than once.
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXMUh8T730IlGai-pDl:b3ye58i) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
> ```objc
>    @ref sap_physical_forces.
>    @throws if called more than once. */
>   void RegisterObjects(std::vector<int> objects) {
> ```

I don't understand why this function needs to be `protected`. It seems to me that this should be a private helper for the constructor of the base class because this is only ever done at construction (based on the toy example in the unit test).
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 274 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMCS4l6IkGTqXQYhk8:-NXMCS4l6IkGTqXQYhk9:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L274)):*
> ```objc
>   virtual void DoAccumulateGeneralizedImpulses(
>       int, const Eigen::Ref<const VectorX<T>>&, EigenPtr<VectorX<T>>) const {
>     // TODO(amcastro-tri): Temporarily, the default implementation is a no-op
> ```

nit



_Suggestion:_
```objc
throw
```
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 283 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMCV6k4Ga9PL7xi3ZY:-NXMCV6k4Ga9PL7xi3ZZ:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L283)):*
> ```objc
>                                            const Eigen::Ref<const VectorX<T>>&,
>                                            SpatialForce<T>*) const {
>     // TODO(amcastro-tri): Temporarily, the default implementation is a no-op
> ```

nit



_Suggestion:_
```objc
throw
```
___
*[`multibody/contact_solvers/sap/sap_constraint.cc` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMCfTJDAwXGxrlnTBa:-NXMCfTJDAwXGxrlnTBb:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.cc#L70)):*
> ```cpp
>     int o, const Eigen::Ref<const VectorX<T>>& gamma,
>     SpatialForce<T>* F) const {
>   DRAKE_THROW_UNLESS(o < num_objects());
> ```

nit



_Suggestion:_
```cpp
DRAKE_THROW_UNLESS(0 <= o && o < num_objects());
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 134 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMD2uv8EhRRLtziy-P:-NXMD2uv8EhRRLtziy-Q:b70cpli) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.h#L134)):*
> ```objc
>   int AddConstraint(std::unique_ptr<SapConstraint<T>> constraint);
> 
>   /* Sets the number of physical objects associated with this problem.
> ```

BTW, is it recommended that we set this before any calls to `AddConstraint()`?



_Code quote:_
```objc
Sets the number of physical objects associated with this problem.
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 136 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMCvu40lf0oQcdNS7Q:-NXMCvu40lf0oQcdNS7R:b-wibtfs) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.h#L136)):*
> ```objc
>   /* Sets the number of physical objects associated with this problem.
>    Constraints (added with AddConstraint()) that register objects will be
>    required to register object indices strictly lower than  num_objects().
> ```

nit extraneous space



_Suggestion:_
```objc
required to register object indices strictly lower than num_objects()
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 150 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMDGpADJXoJuOTs-V4:-NXMDGpADJXoJuOTs-V5:b3pr29) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.h#L150)):*
> ```objc
>   int num_velocities() const { return nv_; }
> 
>   int velocities_start(int clique_index) const {
> ```

nit this function needs some documetation.
___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMESZb91iRTmnOphA0:-NXMESZb91iRTmnOphA1:bv5w3qm) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.cc#L53)):*
> ```cpp
>     DRAKE_THROW_UNLESS(Ac.size() >= 0);
>     DRAKE_THROW_UNLESS(Ac.rows() == Ac.cols());
>     velocities_start_.push_back(Ac.rows());
> ```

This looks suspicious. Should `velocities_start_[0] == 0`?
I'd like to see the unit test for Reset cover this.



_Code quote:_
```cpp
velocities_start_.push_back(Ac.rows());
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 104 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMEyCz3SAIkdrrrR7M:-NXMEyCz3SAIkdrrrR7N:b-qrf9xs) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.cc#L104)):*
> ```cpp
>     if (object_index < 0 || object_index >= num_objects())
>       throw std::runtime_error(
>           "Constraint object indices must be in the range [0; num_objects()).");
> ```

nit typo



_Suggestion:_
```cpp
[0, num_objects())
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMXTmw6GMnZtjO_QfP:-NXMXTmw6GMnZtjO_QfQ:bglvofe) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.cc#L127)):*
> ```cpp
>   DRAKE_THROW_UNLESS(generalized_forces->size() == num_velocities());
>   DRAKE_THROW_UNLESS(spatial_forces != nullptr);
>   DRAKE_THROW_UNLESS(ssize(*spatial_forces) == num_objects());
> ```

I think we need to clear the existing values in `generalized_forces` and `spatial_forces` before accumulating into them.
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 75 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMWy-_3-59BPBKeXnX:-NXMWy-_3-59BPBKeXnY:bge9nhl) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L75)):*
> ```cpp
>   TestConstraint(const TestConstraint&) = default;
> 
>   // Accumulates an arbitrary functional form for testing.
> ```

nit, it'd be nice to mention that this isn't arbitrary in the sense that one can choose any function form and expect the test to still pass. The unit test below depends on this particular form.
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 164 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMVRUtEZDXxQLbyVpO:-NXMVRUtEZDXxQLbyVpP:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L164)):*
> ```cpp
> 
> /* We test ContactProblem with the graph setup sketched below where each
>  box corresponds to a clique (a node in the graph) an edges correspond to a
> ```

typo



_Suggestion:_
```cpp
and
```
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMVvV3D9WPCcgOALay:-NXMVvV3D9WPCcgOALaz:bb4r8ta) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L205)):*
> ```cpp
>   // In this test, constraints will register one object per clique for testing.
>   // Therefore we know we have four objects.
>   problem->set_num_objects(4);
> ```

This contradicts the claim that there are 3 objects from 15 lines above.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)* status: 7 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 191 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXM9sxo73FhOK-6yQvC:-NXQ9Ih1C5Q-39bsTCw8:b-8i5f8h) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L191)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's hard for me to tell what the returned "object indices" index into. Are they indices for `BodyIndex` for rigid and `DeformableBodyIndex` for deformable? A more detailed explanation here is welcome.

Reading more at `SapContactProblem::CalcConstraintMultibodyForces`, it appears it's neither and it's closer to tree indices that the manager understands?
</blockquote></details>

I expanded the text under `@anchor sap_physical_forces`. See if that helps.

You might want to see what the contact constraint constructor will look like [here](https://github.com/amcastro-tri/drake/blob/1b5e788deb8347e599978977c7e4433163b61564/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L198), with the new [`ContactConfiguration` parameter.](https://github.com/amcastro-tri/drake/blob/1b5e788deb8347e599978977c7e4433163b61564/multibody/contact_solvers/contact_configuration.h#L15)
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 243 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMC9u89bIiCIh2dTjp:-NXQAdba3VkM3sQGKCq_:bbfsiuf) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L243)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, this is not strictly true. One can call this with `{}` more than once.
</blockquote></details>

Good call. Actually, no reason to enforce this.
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXQAr2O7jrqS8pe_unX:b-7lmcig) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't understand why this function needs to be `protected`. It seems to me that this should be a private helper for the constructor of the base class because this is only ever done at construction (based on the toy example in the unit test).
</blockquote></details>

In the toy example, this method is called from within the constructor of the **derived class**. Therefore it must be protected?
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 134 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMD2uv8EhRRLtziy-P:-NXQCSwgD5bZpvcpd8rd:bsg7mji) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.h#L134)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is it recommended that we set this before any calls to `AddConstraint()`?
</blockquote></details>

good point. Definitely it must be called before constraints are added.
___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMESZb91iRTmnOphA0:-NXQFI-e0rxlzW9IqKWy:b-yel6nl) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.cc#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This looks suspicious. Should `velocities_start_[0] == 0`?
I'd like to see the unit test for Reset cover this.
</blockquote></details>

That is definitely a bug. 
Actually my dev branch no longer uses `Reset()`. Therefore I decided to remove it in this revision.
___
*[`multibody/contact_solvers/sap/sap_contact_problem.cc` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMXTmw6GMnZtjO_QfP:-NXQGOfS1euosrg1W51Y:bvjbxs3) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_contact_problem.cc#L127)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think we need to clear the existing values in `generalized_forces` and `spatial_forces` before accumulating into them.
</blockquote></details>

good catch. My deve branch accumulates but I decided to go with Calc in this PR instead. But clearly I forgot to zero out values.
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMVvV3D9WPCcgOALay:-NXQI6X59tJv6X7pFmSN:b95xz10) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L205)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This contradicts the claim that there are 3 objects from 15 lines above.
</blockquote></details>

Good point. I rephrased the comment. Not all object need to be referenced by a constraint (with a resulting zero force)

**Review by xuchenhan-tri — COMMENTED** [review]
There are a couple of unit tests not building due to the change in the spelling of SapContactProblem's constructor.

Otherwise, :lgtm: with a few parting thoughts. Please assign platform reviewer after fixing the unit tests.

+(release notes: none) (Internal changes only; feature not yet complete)

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-:-NXQlQbAERITq5Ej0Lgb:bialwrv)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXQjaeC4j0LYR9s3WJv:beuwzy4) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

In the toy example, this method is called from within the constructor of the **derived class**. Therefore it must be protected?
</blockquote></details>

From the SapFrictionConstraint example you provided (as well as the toy example), it seems like the job of registering objects can be done completely from the constructor of the SapConstraint base class. Therefore, it seems more natural to me to have `RegisterObjects` be a private helper of the constructor
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 182 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXQjFyQ5DmZQIIx5Z_8:-NXQjFyQ5DmZQIIx5Z_9:b-7s8hi3) ([raw file](https://github.com/RobotLocomotion/drake/blob/905a93b01270e6898cae3d445808380366295265/multibody/contact_solvers/sap/sap_constraint.h#L182)):*
> ```objc
>    physical objects with indices, arbitrarily defined to uniquely identify
>    distinct physical objects. With these labels defined, the constraint will be
>    able to report physical forces (or rather impulses) on these objects via
> ```

BTW, is it more accurate to just say "impulses"?



_Code quote:_
```objc
able to report physical forces (or rather impulses) on these objects via
```
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 159 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXQkPc22WbhPqF5YYUL:-NXQkPc22WbhPqF5YYUM:b-qxwpzo) ([raw file](https://github.com/RobotLocomotion/drake/blob/905a93b01270e6898cae3d445808380366295265/multibody/contact_solvers/sap/sap_contact_problem.h#L159)):*
> ```objc
>   /* Returns the index to the first velocity for a given clique, within the
>    full vector of generalized velocities for the entire problem.
>    That is, with v the full vector of generalized velocities for this problem,
> ```

BTW, it might be useful to remind readers that this generalized velocities is not the generalized velocities in MbP.



_Code quote:_
```objc
That is, with v the full vector of generalized velocities for this problem,
```

**Review by sammy-tri — COMMENTED** [review]
Unfortunately I'm not going to be able to review today, but I can come back to int on Monday.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-:-NXS8FwxBODulZnLMv7M:bmvg6at)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXVLJJO3Gmx_6D3oHFj:b-20wwej) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

From the SapFrictionConstraint example you provided (as well as the toy example), it seems like the job of registering objects can be done completely from the constructor of the SapConstraint base class. Therefore, it seems more natural to me to have `RegisterObjects` be a private helper of the constructor
</blockquote></details>

Are you thinking of a base class with this constructor?:
```c++
SapConstraint(SapConstraintJacobian<T> J, std::vector<int> objects);
```

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks Sammy!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-:-NXkIds976BelZIeORcf:be4ycjs)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXkIij68eH_wFZ3OKkI:b-pkk2rb) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Are you thinking of a base class with this constructor?:
```c++
SapConstraint(SapConstraintJacobian<T> J, std::vector<int> objects);
```
</blockquote></details>

Yes. Based on the examples I see, I think this would make sense, especially if we want to enforce that objects are registered only once.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXMUh8T730IlGai-pDk:-NXpOA6p-do2uNdr8z3D:be7zjn3) ([raw file](https://github.com/RobotLocomotion/drake/blob/fb47fb057230338d54a7baf007701840624a8ef7/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes. Based on the examples I see, I think this would make sense, especially if we want to enforce that objects are registered only once. 
</blockquote></details>

That's a nicer solution. Done.
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 182 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXQjFyQ5DmZQIIx5Z_8:-NXpNtAXAHXvwNCEVHul:b-gcubhs) ([raw file](https://github.com/RobotLocomotion/drake/blob/905a93b01270e6898cae3d445808380366295265/multibody/contact_solvers/sap/sap_constraint.h#L182)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, is it more accurate to just say "impulses"?
</blockquote></details>

I wasn't trying to be accurate. I like to refer to "forces" as the general term. SAP constraints work on impulses, but for a general description I still like to say "forces" rather than impulses. I do say impulses when I want to be specific. 
___
*[`multibody/contact_solvers/sap/sap_contact_problem.h` line 159 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXQkPc22WbhPqF5YYUL:-NXpNkKE7ihtovV-tcxm:b-taqc6i) ([raw file](https://github.com/RobotLocomotion/drake/blob/905a93b01270e6898cae3d445808380366295265/multibody/contact_solvers/sap/sap_contact_problem.h#L159)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, it might be useful to remind readers that this generalized velocities is not the generalized velocities in MbP.
</blockquote></details>

Client code could be MBP or some other system. So I guess there is no need to mention specify client code?

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with some comment/doc nits

> Reviewed 8 of 9 files at r2, 2 of 2 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-:-NXpptYhDCdl4ehq_kux:bol858z)* status: 3 unresolved discussions

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 226 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXpnmx913lFzwRLycmp:-NXpnmx913lFzwRLycmq:b-axa2xm) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a2d93f2a071a0a1b1b9b577f1ee8b5b0a9d95db/multibody/contact_solvers/sap/sap_constraint.h#L226)):*
> ```objc
>                                      EigenPtr<VectorX<T>> tau) const;
> 
>   /* Accumulates generalized impulses applied by this constraint the o-th
> ```

nit: should this still say "generalized impulses" or "spatial impulses"?
___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 231 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXpnwWj98tJvVDAIKUS:-NXpnwWj98tJvVDAIKUT:b-9zgs9i) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a2d93f2a071a0a1b1b9b577f1ee8b5b0a9d95db/multibody/contact_solvers/sap/sap_constraint.h#L231)):*
> ```objc
>    @param[in] gamma Impulses for this constraint, of size
>    num_constraint_equations().
>    @param[out] tau On output this function will accumulate the spatial
> ```

nit: the output parameter is not named 'tau' anymore
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 88 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXppJR_ACe0enhCHxqM:-NXppJR_ACe0enhCHxqN:b-xcrryi) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a2d93f2a071a0a1b1b9b577f1ee8b5b0a9d95db/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L88)):*
> ```cpp
>                                    const Eigen::Ref<const VectorXd>& gamma,
>                                    SpatialForce<double>* F) const final {
>     // Vector6d v6 = o * gamma.sum() *
> ```

nit: I'm not sure what this comment is for, it looks like a dead version of the code?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 226 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXpnmx913lFzwRLycmp:-NXqRziz9a8TplOpGEXi:b-yomekc) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a2d93f2a071a0a1b1b9b577f1ee8b5b0a9d95db/multibody/contact_solvers/sap/sap_constraint.h#L226)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: should this still say "generalized impulses" or "spatial impulses"?
</blockquote></details>

nice catch!
___
*[`multibody/contact_solvers/sap/test/sap_contact_problem_test.cc` line 88 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19557#-NXppJR_ACe0enhCHxqM:-NXqSBXN2y4uWpqjuBpX:byz0qll) ([raw file](https://github.com/RobotLocomotion/drake/blob/4a2d93f2a071a0a1b1b9b577f1ee8b5b0a9d95db/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L88)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: I'm not sure what this comment is for, it looks like a dead version of the code?
</blockquote></details>

very dead

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19557)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
