### PR TITLE
Stop suppressing cpplint whitespace/parens

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all the current errors, then stop suppressing cpplint whitespace/parens.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake005 you are broken, I am going to ignore you.

**Comment by jwnimmer-tri** [comment]
Explosions!

@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@maddog-tri up for a first-pass code review, please?

**Comment by maddog-tri** [comment]
Done - looks fine, no defects/suggestions.

**Comment by jwnimmer-tri** [comment]
@david-german-tri This is ready to merge, modulo three #2024 trips on OS X, which I propose you ignore.

**Pull request merged**
