### PR TITLE
New method to calculate angular velocity of D in A, expressed in D (not A).

### PR DESCRIPTION
**Pull request by mitiguy**
This is a near-repeat to last PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8822)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8822#-:-LCeZJuY4lPe4tt34KDK:b9rqlek)*

**Comment by SeanCurtis-TRI** [comment]
Please edit your comment and provide a reference to the "last pr".

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8822#-:-LCeZpJp2VkwyQkq3Sa2:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8822#-:-LCealRP01dDW9bIsBtc:b-irfx5k)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8822#-:-LCi5WLo7UMQTQd8xz7c:bnfp4nl)*

**Pull request merged**
