### PR TITLE
Add manip plan eval block for humanoids. 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
1. Replaced the old "moving pelvis up and down" plan eval block with a new one that listens to a lcm message of robotlocomotion::robot_plan_t. 
2. I put the new plan eval block in dev. 
3. Switched the param file from tracking COM height to tracking pelvis height. Had to tweak some tolerance settings in the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6607)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review, thanks. 

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-KpVcnZ-CPqP0NyGE-B1:b-9drkvx)*

**Comment by naveenoid** [comment]
I would recommend a README.md explaining launching of the demo added with this PR. Since my comments are all BTWs, please address accordingly. :lgtm:

---

Reviewed 19 of 20 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpa1aE0arRXxTZg6MNb:-Kpa1aE0arRXxTZg6MNc:beiz8k5) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc#L1)):*
> ```cpp
> #include "drake/examples/Valkyrie/valkyrie_constants.h"
> ```

BTW: Consider adding an @brief explaining what one is expected to see with this demo.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpa1Q4oR-So8OlN_Gw8:-Kpa1MuYq65u25dAARBK:bv5md2y) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc#L34)):*
> ```cpp
>   // the desired trajectories.
>   //
>   // A couple things:
> ```

BTW: nit "A couple 'of' things"; I would also suggest reformulating this comment to say "Some notes on the message:"

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-KpadZdx6PkRsMcJBg1j:-KpadZdx6PkRsMcJBg1k:b-ipa333) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L161)):*
> ```cpp
>       case ConstraintType::Soft:
>         EXPECT_NEAR(qp_input.desired_dof_motions().value(i), qp_output.vd()[i],
>                     1e-2);
> ```

BTW: why is this relaxation of test tolerance needed?

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-KpadkHSOF3hiM8XUzXN:-KpadkHSOF3hiM8XUzXO:b59egsu) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc#L163)):*
> ```cpp
>   EXPECT_TRUE(robot_status.foot(Side::LEFT).velocity().norm() < 1e-6);
>   EXPECT_TRUE(robot_status.foot(Side::RIGHT).velocity().norm() < 1e-6);
>   EXPECT_TRUE(drake::CompareMatrices(q, q_ini, 1e-3,
> ```

BTW: why relaxed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-KpaeINBwRJze_jzW7Ng:bppw11m)*

**Comment by siyuanfeng-tri** [comment]
+@jwnimmer-tri for platform review. thanks! 

---

Review status: 13 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpa1aE0arRXxTZg6MNb:-Kpon8lmCTl3DNL5jIFp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc#L1)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Consider adding an @brief explaining what one is expected to see with this demo.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpa1Q4oR-So8OlN_Gw8:-Kpp2ce9EVOymmx1HF_v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/dev/humanoid_manipulation_demo.cc#L34)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: nit "A couple 'of' things"; I would also suggest reformulating this comment to say "Some notes on the message:"
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 161 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-KpadZdx6PkRsMcJBg1j:-Kpp2dp_HHJbAggF5iyL:b-w543m2) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L161)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: why is this relaxation of test tolerance needed?
</blockquote></details>

because I changed the parameter settings to the QP (weights, and what to track). With the new parameters, the controller is more liberal with the leg joints, so I had to relaxed the tolerance more. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-KpadkHSOF3hiM8XUzXN:-Kpp2zCoeFvhk6-LmIOc:brx2yk6) ([raw file](https://github.com/robotlocomotion/drake/blob/543be7c018726544000352557fd605932d5881d6/drake/examples/QPInverseDynamicsForHumanoids/test/valkyrie_balancing_test.cc#L163)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: why relaxed?
</blockquote></details>

same as above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-Kpp3eMLQP-6WmzX_yMT:b-xupxfv)*

**Comment by naveenoid** [comment]
Reviewed 2 of 6 files at r3.
Review status: 15 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by naveenoid** [comment]
Reviewed 4 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 13 of 20 files at r2, 3 of 6 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 212 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp785BvkcfKb_-siT5:-Kpp785Cugj07x6u76N1:b-xfgc8r) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L212)):*
> ```objc
>    * checks.
>    */
>   virtual bool IsRigidBodyTreeAliasGroupsCompatible(
> ```

FYI Consider whether https://google.github.io/styleguide/cppguide.html#Function_Overloading applies to this case.  Is it really true that call sites do not need to figure out which overload is being called in order to make sense of this call vs the prior method?

FYI It's also the case that overloading virtual methods can get sticky (sometimes the compiler will yell because some overloads become "hidden" if only one of the two functions is overridden).

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 316 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp8c6RX0VkpMCcG0n4:-Kpp8c6RX0VkpMCcG0n5:bax62zu) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L316)):*
> ```objc
>    * std::logic_error if any is incompatible.
>    */
>   void CheckCompatibilityAndThrow(
> ```

On first read, it seems like this is not covered by unit testing.  Should it be @naveenoid?

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp855BMeLawtLvqyr4:-Kpp855CeNbD7E2ddx6L:bhwfyb2) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L41)):*
> ```cpp
>   unused(paramset);  // TODO(jwnimmer-tri) This seems bad.
> 
>   const auto& msg = plan.GetValue<lcmt_manipulator_plan_move_end_effector>();
> ```

FYI Is this called from an innermost loop, e.g., repeatedly mid-step during one integration timestep?  If not, always prefer `GetValueOrThrow` over `GetValue` per `AbstractValue`'s API docs.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp7xI26M3OucDKjByp:-Kpp7xI3SRlRxMcxn99c:b-lnmmva) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L39)):*
> ```objc
> 
>   /**
>    * This function assumes that the bytes in @p plan_bytes encodes a valid
> ```

BTW _Meta_ nit Typo `plan_bytes` -- the argument is `plan`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp9FbSTujQOf7N3yBt:-Kpp9FbSTujQOf7N3yBu:b7smcc3) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc#L49)):*
> ```cpp
>   // Decodes the message into q and v.
>   const bot_core::robot_state_t& raw_msg =
>       first_msg.GetValue<bot_core::robot_state_t>();
> ```

FYI Same as above... prefer GetValueOrThrow when possible.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp9POyhNWSt3YSc5L-:-Kpp9POyhNWSt3YSc5L0:bc75r1x) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc#L59)):*
> ```cpp
>   VectorX<double> v(robot.get_num_velocities());
>   manipulation::RobotStateLcmMessageTranslator translator(robot);
>   translator.DecodeMessageKinematics(raw_msg, q, v);
> ```

FYI I assume q, v are output parameters here?  If so, at some point in a future PR, please refactor to use pointers not references.

---

*[drake/systems/controllers/zmp_planner.h, line 285 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp5Hy-s9PeAGkOr1SQ:-Kpp5Hy-s9PeAGkOr1SR:b4mhtj2) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/systems/controllers/zmp_planner.h#L285)):*
> ```objc
>   // stationary or not in CheckStationaryEndPoint. This number is currently
>   // arbitrarily chosen.
>   double kStationaryThreshold = 1e-8;
> ```

FYI This should be `const` since its named `kFoo`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-Kpp9ePzGLCmnQk-2aXK:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Review status: 11 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 212 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp785BvkcfKb_-siT5:-KppRN8Oh5ScDFOi53L5:b-jtr7ac) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L212)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider whether https://google.github.io/styleguide/cppguide.html#Function_Overloading applies to this case.  Is it really true that call sites do not need to figure out which overload is being called in order to make sense of this call vs the prior method?

FYI It's also the case that overloading virtual methods can get sticky (sometimes the compiler will yell because some overloads become "hidden" if only one of the two functions is overridden).
</blockquote></details>

Face palm. This is a copy and paste fail... 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h, line 316 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp8c6RX0VkpMCcG0n4:-KppMijf5rqVJj1nwivb:be5rgl9) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/generic_plan.h#L316)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On first read, it seems like this is not covered by unit testing.  Should it be @naveenoid?
</blockquote></details>

it is not since the defaults are all true. 
Let me add a quick one. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc, line 41 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp855BMeLawtLvqyr4:-KppN07ho-cwFuasdquq:b-7rl0jd) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.cc#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Is this called from an innermost loop, e.g., repeatedly mid-step during one integration timestep?  If not, always prefer `GetValueOrThrow` over `GetValue` per `AbstractValue`'s API docs.
</blockquote></details>

done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp7xI26M3OucDKjByp:-KppOULTKWqH5LxMjZmx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/plan_eval/manipulator_move_end_effector_plan.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ nit Typo `plan_bytes` -- the argument is `plan`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp9FbSTujQOf7N3yBt:-KppP7wJjfB65Ny_m1jT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Same as above... prefer GetValueOrThrow when possible.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp9POyhNWSt3YSc5L-:-KppOfAcpXYTF8PobJZ7:b-8t8b7m) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I assume q, v are output parameters here?  If so, at some point in a future PR, please refactor to use pointers not references.
</blockquote></details>

Yes q and v are outputs. But they are Eigen::Ref<VectorX<double>>, which should be fine?

---

*[drake/systems/controllers/zmp_planner.h, line 285 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp5Hy-s9PeAGkOr1SQ:-KppP5HO_VItZREiz0wk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/systems/controllers/zmp_planner.h#L285)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This should be `const` since its named `kFoo`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 8 files at r4.
Review status: 17 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-Kpp9POyhNWSt3YSc5L-:-Kppo-IRMaLb6VMT-1Q0:bf8coat) ([raw file](https://github.com/robotlocomotion/drake/blob/65ef085f0503c32e91b7d83d31c38ce670df3ee6/drake/examples/QPInverseDynamicsForHumanoids/system/valkyrie_balancing_controller_system.cc#L59)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Yes q and v are outputs. But they are Eigen::Ref<VectorX<double>>, which should be fine?
</blockquote></details>

OK Ugh, I hate non-const `Eigen::Ref` with a fiery passion.  Withdrawn for now, only because there is _one_ place in drake::systems framework that uses this pattern, so it's difficult to hold examples code to a higher standard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by jwnimmer-tri** [comment]
Platform good, but please make sure that @naveenoid refreshes his headshot (eyeball) on the new test cases.

---

Review status: 17 of 19 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-KpppD_ctjFLJLdds99g:b9qsysq)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by naveenoid** [comment]
Reviewed 2 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by naveenoid** [comment]
Reviewed 6 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607)*

**Comment by jwnimmer-tri** [comment]
I was going to merge this, but the first commit has a weird history.  Maybe look into that before merging?

**Comment by siyuanfeng-tri** [comment]
hmm, that is weird indeed.. I fixed it. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6607#-:-KpqJvPVTrcXQK8MSW-F:bwb0rpw)*

**Pull request merged**
