### PR TITLE
OBJ files for proximity can have multiple objects

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Currently, Mesh objects are (generally) replaced with their convex hull in most proximity roles (with notable exceptions related to hydroelastic contact).

Historically, there has been a requirement that the .obj file contain only a single object. For this particular domain, the requirement is no longer relevant, so we've removed it. This entails the following:

- Rename an .obj file to more directly reflect its new role (also stripping out geometry data that was unhelpful).
- Update the read_obj_test.cc to make the test less redundant and to eliminate some extant TODOs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 
+@edrumwri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-:-O2aITZL8KkAKP06Jj_Q:bm325ll)* status: LGTM missing from assignee edrumwri, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by edrumwri — COMMENTED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-:-O2ad8m17DEgCSgK14ru:bg7igkv)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`geometry/read_obj.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2a_zPp2GuMfC346BVI:-O2a_zPp2GuMfC346BVJ:b-rsl4tb) ([raw file](https://github.com/RobotLocomotion/drake/blob/02ffc45ee458bb969b8aae452730efc6f697d928/geometry/read_obj.h#L23)):*
> ```objc
>  @return (vertices, faces, num_faces) vertices[i] is the i'th vertex in the
>  mesh. faces is interpreted as
>     faces = { n0, v0_0,v0_1,...,v0_n0-1,
> ```

BTW Hate this data structure. So much room for misinterpretation.
___
*[`geometry/read_obj.cc` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2aad-x7zPleqNuQJVA:-O2aad-x7zPleqNuQJVB:b-mt1ai7) ([raw file](https://github.com/RobotLocomotion/drake/blob/3c17fc15e5a296b40035d9684b6372f8ee330607/geometry/read_obj.cc#L83)):*
> ```cpp
> std::vector<int> TinyObjToFclFaces(const tinyobj::mesh_t& mesh) {
>   std::vector<int> faces;
>   faces.reserve(mesh.indices.size() + mesh.num_face_vertices.size());
> ```

Is it no longer worth trying to reserve the size of this vector?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-:-O2ai4yI52X8FMmYri6D:b223nro)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2aixG2B3vhCyqJA1Zm:-O2aixG3BMzLYKJWJn5U:b-3la17x) (no related file):*
BTW @edrumwri. The fastest way to put an obj with multiple objects through current Drake master is to go through your .obj file and remove the lines that start with `o `. Ninety-nine times out of a hundred, you're probably not benefiting from the wavefront definition of "object".

___
___
*[`geometry/read_obj.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2a_zPp2GuMfC346BVI:-O2air2I088rubAXBFfz:b47guuk) ([raw file](https://github.com/RobotLocomotion/drake/blob/02ffc45ee458bb969b8aae452730efc6f697d928/geometry/read_obj.h#L23)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Hate this data structure. So much room for misinterpretation.
</blockquote></details>

I know what you mean. Polygons are generally nasty.
___
*[`geometry/read_obj.cc` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2aad-x7zPleqNuQJVA:-O2aiAvB0CYLRNi2cTzG:b-nt4668) ([raw file](https://github.com/RobotLocomotion/drake/blob/3c17fc15e5a296b40035d9684b6372f8ee330607/geometry/read_obj.cc#L83)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Is it no longer worth trying to reserve the size of this vector?
</blockquote></details>

A couple of thoughts:

1. The original reservation size was a conservative floor. So, we generally relied on the standard library to reallocate.
2. The actual size will be a function of multiple shapes. We do have options:
    - Iterate through the shapes first and create a floor across all shapes akin to the old floor.
    - Reserve the original amount (with the assumption that a single shape is the most common case), and allow the standard library to grow it for the other cases.

Thoughts?

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`geometry/read_obj.cc` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2aad-x7zPleqNuQJVA:-O2akgdB2cU9d9ehIJ0x:b-on2axc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3c17fc15e5a296b40035d9684b6372f8ee330607/geometry/read_obj.cc#L83)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

A couple of thoughts:

1. The original reservation size was a conservative floor. So, we generally relied on the standard library to reallocate.
2. The actual size will be a function of multiple shapes. We do have options:
    - Iterate through the shapes first and create a floor across all shapes akin to the old floor.
    - Reserve the original amount (with the assumption that a single shape is the most common case), and allow the standard library to grow it for the other cases.

Thoughts?
</blockquote></details>

I was thinking of the first option as well as some documentation that the reservation size is a conservative floor. The way that I read the code was consistent with the output (i.e., return) documentation for this function, meaning that you were reserving exactly how much you needed.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform)

___
*[`geometry/read_obj.cc` line 83 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-O2aad-x7zPleqNuQJVA:-O2an4zpDmVtO4D9se1b:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/3c17fc15e5a296b40035d9684b6372f8ee330607/geometry/read_obj.cc#L83)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I was thinking of the first option as well as some documentation that the reservation size is a conservative floor. The way that I read the code was consistent with the output (i.e., return) documentation for this function, meaning that you were reserving exactly how much you needed.
</blockquote></details>

Done

**Review by edrumwri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21745#-:-O2bEFGe4iMIOfxK0zOJ:b-cxwtpw)* status: 1 unresolved discussion

**Pull request merged**
