### PR TITLE
[visualization] Auto reconnect to meshcat server

### LINKED ISSUE #17085: Meshcat browser auto-reconnect
Currently, if a user has a browser window open and connected to a live `geoemtry::Meshcat` service, but then re-starts their simulation program (or similarly, destroys the `Meshcat` object and recreates it within the same program), the browser window will no longer see any updates -- it is stuck on the old socket connection, which is no longer in service.

When the websocket goes down, the browser code should attempt to reconnect to the same websocket URL, in case the server comes back up.

It will probably need to resync some state at that point (possibly as-if it were a new window in the first place, setting everything up from scratch?).

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The client will automatically attempt to reconnect to the meshcat url at a default 1-second cadence. The reconnect period can be tweaked by changing the url.

   http://localhost:7000/?reconnect_ms=10000

sets the reconnect period to 10,000 ms.

The C++ `MeshCat` server adds the following to facilitate reconnection:
  - When connecting to a client, it deletes everything in the `prefix_` path.
  - While the server broadcasts the current state to a new connection, any value not *explicitly* stored in the current state doesn't get broadcast. Properties related to changing render mode have been explicitly added to the state. Previously, the initial values were implicit.

What this does *not* do: overwrite the lighting.

Closes #17085

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
cc @jwnimmer-tri @rpoyner-tri @russtedrake 

I'd like some feedback on what I've done here.

In playing with this functionality, I did `bazel run geometry:meshcat_manual_test` over and over, killing it at arbitrary stages and restarting it to see the reconnection and definition of state.

 - Killing it when changing the view (to 2d) and then restarting should restore the 3D view upon restoration.
 - Killing it after the Kuka is loaded and then restarting should show, again, the original initial condition.
 - Killing it after the lighting changes (it is dimmed) and restarting it will *not* reset the lighting. This is one of the points for conversation -- how wide a net do we want to cast in setting lighting and anything else outside of `/drake`.

Also, play with the reconnect period and let me know:
 - what the right default should be,
 - whether the url parameter configuration is good/bad, and
 - how best to document this for users.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N8_2SoH194rroy7IywV:b-wvjrhi)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`geometry/meshcat.cc` line 573 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8_3V6u9_ddx2-SrKUZ:-N8_3V6u9_ddx2-SrKU_:bsj3xfe) ([raw file](https://github.com/robotlocomotion/drake/blob/b3d73d6e7b1d21e4076d98469636db610e8da25c/geometry/meshcat.cc#L573)):*
> ```cpp
>     // mode, it will get updated, but only if the properties are stored in the
>     // tree.
>     ResetRenderMode();
> ```

BTW It might be nice to have a toggle button by default that controls whether the view is in 2D or not. It would allow to manipulate it in viewer and, as a control, it will automatically get restored in the control broadcast upon new connection.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8_3uouD3J3IK0jE9sL:-N8_3uouD3J3IK0jE9sM:b-bmeaz4) (no related file):*
The issue had suggested pushing something up to meshcat, itself.

Because we're already *not* using `viewer.connect()` (to facilitate the time rate stats), it seems to achieve this effect in meshcat would also require having some callbacks so we can customize the various connection callbacks. If you feel strongly about that, let me know.

___

**Review by RussTedrake — COMMENTED** [review]
Let me make sure I understand:
The most common workflow we are trying to support, I think, is when someone runs a binary (which terminates or otherwise deletes the meshcat object) multiple times and wants to see the results in the same browser window. 

So when you say "killing it when changing the view (to 2D) and then restarting should restore the 3D view upon restoration", what I should understand is... Let's say I run a c++ program which calls `meshcat.Set2DRenderMode(...)` and then I connect in a browser.  The c++ code terminates, and I run it again.  You're saying that the viewer will reset to 3D mode on reconnect. But when the C++ executes the `Set2DRenderMode(...)` the meshcat window will once again transition to 2D mode.  That seems good to me.

I agree that a challenge is that some of the state in the browser can be manipulated through GUI elements, and others can typically only be manipulated by "commands"; most often via the websocket connection but occasionally through direct javascript calls.  For instance if I position/point the camera via the mouse, then it does seem nice to not reset that state on reconnect.  Adding geometry into the tree (e.g. under `/drake`) is typically only done via the websocket, so it makes sense to reset that and expect the binary to set them again.

The grey area is the other "state", like whether the grid is visible (or the background, ...).  That can be toggled in the browser, but is also often set via the websockets.  As I understand it, currently these are NOT reset on reconnect, so if I manually disable the grid in the browser, then it will stay off *unless* my binary calls e.g. `meshcat.SetProperty('/Grid','visible',True)`.  That seems like a very reasonable user experience to me.

If I were to run one c++ code that liked the grid visible, and then afterwords run a second different c++ code that likes the grid on (but does not turn it on explicitly, because it is normally on by default), then the experience might be slightly jarring.  But I guess the user always has the ability to completely reset the meshcat state by doing a hard "refresh" in the browser.

So the closest thing that I can extract as a "principle" for what state gets reset is perhaps "could the user have changed this state via GUI interactions in the browser window?"  If yes, then ideally we don't reset?  If no, then we do reset?  That is not quite what you have here; for instance I could uncheck the visibility of a subtree under `/drake`, but that will become visible again when the binary publishes.  I still like your version as an initial implementation, but is this the right "principle" to eventually try to work towards?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N8cFqID5eGXWFg3sWxw:blf2olq)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Without having tried this yet, my naive expectation was that when we detect a reconnect, we just `page.reload()` (or however it's spelled in JS), giving a 100% clean slate -- basically just automating the "reload" button as we currently use it in this situation.

I can see the case for keeping the viewpoint the same across the reload, though.  I'm not sure I buy keeping any other settings the same.  I'll play with the demo here to see what I think in practice.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'd started writing the below treatise and was getting ready to hit publish when I read @jwnimmer-tri's response. 

## Thoughts in response to Jeremy

The newest revision does a simple reload. On the one hand, it doesn't preserve any of the visualizer state. On the other hand, it doesn't preserve any of the visualizer state.  :)  So, it resolves the clean up of all artifacts listed below.

## Thoughts in response to Russ

Ok, there's a lot in there. Let's see if I can explain my position well.

The baseline expectation is that a browser MeshCat session would behave like a `drake_visualizer` session in the following way:

  1. I can start a visualizer.
  2. I can run some process that "broadcasts" visualization data.
  3. It appears in the visualizer.
  4. If the "broadcasting" process ends, I can start a *different* process and it'll draw itself to the same visualizer.
  5. The visual contents of the two processes are different and they don't interfere with each other.

So, to meet the baseline, MeshCat has some special cases:

  - One MeshCat server instance can have a different prefix than another prefix. That means the new server can only clean up data that belongs to its known prefix.
       - This isn't *generally* a problem as most users will use the default prefix. If they're not, they're advanced users and are on their own.
  - In addition to everything handled by MbP and SG, MeshCat adds some MeshCat specific things: controls and animations. These should be treated like the scene graph data -- when the visualizer connects to a server, the server should seek to clear out animations and controls.
      - Right now, controls and animations added by MeshCat are not sequestered in a unique path like the MbP/SG data is ("drake/"). That means, deleting any *previous* Drake-added animations/controls might be a bit tricky.
          - It would be reasonable to simply stomp on the `/Animations/default` folder. That doesn't seem to work.
          - It looks like this will require a patch to MeshCat to remove/clear animations.
      - Controls seem to be in a similar boat. There is no way, generally, to remove a control. One can be replaced (if you happen to "set" a new control with the same name). But one `Meshcat` server cannot discover controls that may have been created by a previous `Meshcat` server (without some coordinating convention).  (Just some metadata tag that items could be selected by would be sufficient).

Finally, the last weirdness is that the Drake process can control certain rendering aspects of the visualizer. We can't do that with `drake_visualizer`. So, we need to account for the fact that one Drake process may have modified rendering parameters in a way that is incompatible with another. Of those changes, most are *directly* addressable through the MeshCat gui: visibility of grid lines, background, axes, etc. can all be toggled by hand. Likewise, light intensity can be twiddled. The only thing we *don't* have is control over the projection matrix.

So, the current state of affairs is trying to reset that which *can* be reset (MbP/SG contents and render properties). I can't touch animations or controls and haven't bothered with lights.

The simple solution may simple be to document the limitations of the auto-reconnect and rely on the user to recognize when it is to their benefit and when they should just hit F5. The documentation can say, if the program *cares* about things like 2D vs 3D view and lighting, it should set it explicitly rather than relying on defaults. Then they'll get what they want in that regard, every time (whether a fresh browser or a reconnect).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N8dJfwz38VX--C7KPhE:b-upn3uw)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8dbkIzCpP43DGYqW0d:-N8dbkJ--_RoeouzDf3X:bcq4wyi) (no related file):*
One thought that occurred to me is that it might be nice if there was some visual feedback.

1. Simple feedback that it has no connection would be a nice minimum.
2. Some kind of count-down timer indicating when it will next attempt to connect might be nice.

Thoughts?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8_3uouD3J3IK0jE9sL:-N8dhjK69RuZA6blBuAl:b-camfv8) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The issue had suggested pushing something up to meshcat, itself.

Because we're already *not* using `viewer.connect()` (to facilitate the time rate stats), it seems to achieve this effect in meshcat would also require having some callbacks so we can customize the various connection callbacks. If you feel strongly about that, let me know.
</blockquote></details>

It can be future work.  The fact that we don't use viewer.connect() anymore is a bug that we intend to fix (`// TODO(#16486): Replace this function with more robust custom command handling in Meshcat`).  Once that's finished, we can try to upstream the reconnect logic.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8dbkIzCpP43DGYqW0d:-N8dhxUjAx7cc8AdTS_v:bv5l4h4) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

One thought that occurred to me is that it might be nice if there was some visual feedback.

1. Simple feedback that it has no connection would be a nice minimum.
2. Some kind of count-down timer indicating when it will next attempt to connect might be nice.

Thoughts?
</blockquote></details>

I do think a spinner would make sense ("Reconnecting..." or "Connecton lost..." or something).  It shouldn't disable the viewport though; the user should still be able to browse the last-known scene.  It's OK to defer that for Todd to look into later if we like.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8_3uouD3J3IK0jE9sL:-N8dj9yw5d6z952bk2x9:b-pbdqz3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It can be future work.  The fact that we don't use viewer.connect() anymore is a bug that we intend to fix (`// TODO(#16486): Replace this function with more robust custom command handling in Meshcat`).  Once that's finished, we can try to upstream the reconnect logic.
</blockquote></details>

Agreed.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8dbkIzCpP43DGYqW0d:-N8dj2Z6-BF-2hZSR6iu:b9s8xtd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I do think a spinner would make sense ("Reconnecting..." or "Connecton lost..." or something).  It shouldn't disable the viewport though; the user should still be able to browse the last-known scene.  It's OK to defer that for Todd to look into later if we like.
</blockquote></details>

Revision 3 adds the dirt simplest version of this. No spinner, just a message indicating state and effort.



___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8esQga4tPnRmg-xGqb:-N8esQga4tPnRmg-xGqc:bibiys1) (no related file):*
One more topic -- the current implementation uses a successful reconnection to trigger a reload. The `Meshcat` server in C++, sends the entire scene tree (and animations and controls) to every new connection.

This means that it will attempt to send the description of the world to a client that is about to reset itself. Hard. Wasted effort on both parts. The system still works, but it does do work that is just thrown away.

On the client side, the only way to discover if a server is active is to actually *connect*. So, creating a vaild connection is the only viable signal for determining that a server is available.

How dissatisfying is this?

If we bemoan the loss of effort, we could introduce a client-server message where the client (after connecting) says, "Ok! I'm ready" and the server uses that signal as the trigger for sending everything. The client would only send the signal after reloading, so we wouldn't waste the communication where the client is just going to blindly reload.

Thoughts?

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by RussTedrake — COMMENTED** [review]
I agree that the user can hit F5 if they are worried about resetting the 2d vs 3d.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N8jyLb_6sZtbQiCTCtj:b-p1bm1x)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Ready for real review, I think.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N8xZ2BnB3t_ashOtRUA:b-rshqw)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N8esQga4tPnRmg-xGqb:-N8xYhe51Hh5Jg7DaHJx:b9wu5ux) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

One more topic -- the current implementation uses a successful reconnection to trigger a reload. The `Meshcat` server in C++, sends the entire scene tree (and animations and controls) to every new connection.

This means that it will attempt to send the description of the world to a client that is about to reset itself. Hard. Wasted effort on both parts. The system still works, but it does do work that is just thrown away.

On the client side, the only way to discover if a server is active is to actually *connect*. So, creating a vaild connection is the only viable signal for determining that a server is available.

How dissatisfying is this?

If we bemoan the loss of effort, we could introduce a client-server message where the client (after connecting) says, "Ok! I'm ready" and the server uses that signal as the trigger for sending everything. The client would only send the signal after reloading, so we wouldn't waste the communication where the client is just going to blindly reload.

Thoughts?
</blockquote></details>

While this would be considered "regrettable", it's not particularly problematic. For large, complex scenes, it is likely the reload action will sever the connection early enough that the whole scene isn't broadcast. Furthermore, it is difficult to imagine that reconnection happens so frequently that the one time costs impact any workflows.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri This has moved from draft to reviewable.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N96v15vDGBFQYqfTWN3:b-kofffb)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yup, my apologies; I know this is waiting on me, I just need to find time to explore in various local build scenarios.

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW If, when you're done, you could document the breadth of your testing methodology, it might be good to have that captured here so that we can reference it in future PRs ans a good feature-review practice for this corner of Drake.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N97U0L203n5R1CchDYN:b-2yu8wv)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

(1) I tested running //tools:meldis and //examples/hardware_sim:demo, then killing them, then relaunching them and observing the browser reload in response.

(2) I tested running //tutorials:authoring_multibody_simulation.  "Run all" cells, open the meshcat hyperlink to watch it in another tab.  Then choose the notebook menu item "Restart and run all...", watch the other meshcat tab show a discussion yellow bar and then automatically reconnect.

I think it would be fine in the future to consider whether and how we preserve user-configured state.  I think this PR is an improvement, because:

(a) It shows the nice yellow bar indicating that the server is gone.  This would be a great win even without auto-reconnect.

(b) When the server dies and restarts, we've automated the "F5" button on behalf of the user.  The only possible downside here is if the user _wanted_ to keep browsing through the dead scene, as some kind of reference even in case the server restarted.  That doesn't seem likely, but one way to keep supporting that would be allow for `?reconnect_ms=...` to disable the auto-refresh, by passing something like `0` or `-1` for the argument.

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9CE37EE3n2OO_c2tlq:b-q4xfn3)* status: 7 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.cc` line 1393 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CBOT3D0x5VaeU0hHZ:-N9CBOT3D0x5VaeU0hH_:bqi6hxt) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.cc#L1393)):*
> ```cpp
>     // Note: If the html code changes, the DRAKE_DEMAND will fail, and the code
>     // string here will need to be updated to once again match the html.
>     const std::string html_connect = R"""(// The lifespan of the server may be much shorter than this visualizer
> ```

I think we've outgrown this implementation technique at this point.  The amount of copied code, while somewhat easy to maintain in replica, is an ongoing drag where unrelated parts of the software need to evolved in sync.

My suggestion is to have html comment markers ...

```html
<!-- Begin connection excerpt -->
...
<!-- End connection excerpt -->
```

... and then use those to anchor what to snip out.
___
*[`geometry/meshcat.html` line 12 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CD7ux2RicVqPyVeKZ:-N9CD7ux2RicVqPyVeK_:b-hgytqv) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L12)):*
> ```HTML
> <body>
>   <div id="status-message">
>     No connection to server. Attempting to find a new connection...
> ```

nit I'm not in love with the term "find" here.  To me, that conveys that we're exploring a space of possibilities (e.g., scanning for different default ports 7000-7099), when really, we're only trying one specific connection.

I'd suggest "Attempting to reconnect..." as more clear.
___
*[`geometry/meshcat.html` line 81 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CIqen9Rv6Wv1o2Kjb:-N9CIqen9Rv6Wv1o2Kjc:bpx1khy) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L81)):*
> ```HTML
>     // connection from a clean client state versus a reconnection after the
>     // original connection was lost.
>     var fresh_connection = true;
> ```

nit For whatever reason, my brain likes "first" better than "fresh" for readability.  I can't quite articulate why, so I'm fine either way.



_Suggestion:_
```HTML
first_connection 
```
___
*[`geometry/meshcat.html` line 90 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CJ6OO7bWI0J6Q-V2t:-N9CJ6OO7bWI0J6Q-V2u:b3sqwn7) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L90)):*
> ```HTML
>         connection.onmessage = (msg) => handle_message(msg);
>         connection.onopen = (evt) => {
>           if (!fresh_connection) location.reload(); };
> ```

nit For my taste, resetting `fresh_connection` to "false" makes the most sence as part of `onopen`, the place where we test for it and the place that has first-hand knowledge of connection counts.  If there's a reason why it _needs_ to be in onclose instead of onopen, that should be commented.
___
*[`geometry/meshcat.html` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CEcfe6WUT5y96ZxUI:-N9CEcfe6WUT5y96ZxUJ:b-u7t7cu) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L106)):*
> ```HTML
>     const queryString = window.location.search;
>     const urlParams = new URLSearchParams(queryString);
>     reconnect_ms = parseInt(urlParams.get('reconnect_ms')) || 1000;
> ```

For my part, I don't see any particular need to make this configurable, but on the other hand it doesn't hurt anything.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I opted for the ability to turn of auto-F5 using a negative (well, technically, non-positive) reconnect time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9Ds6FR70s-SwR0d05S:b4cqocc)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat.cc` line 1393 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CBOT3D0x5VaeU0hHZ:-N9DsHehBOOUuLCA2-TJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.cc#L1393)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we've outgrown this implementation technique at this point.  The amount of copied code, while somewhat easy to maintain in replica, is an ongoing drag where unrelated parts of the software need to evolved in sync.

My suggestion is to have html comment markers ...

```html
<!-- Begin connection excerpt -->
...
<!-- End connection excerpt -->
```

... and then use those to anchor what to snip out.
</blockquote></details>

Done.
___
*[`geometry/meshcat.html` line 90 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CJ6OO7bWI0J6Q-V2t:-N9Dw6jy08c65sSGhieY:b-j73jyx) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L90)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For my taste, resetting `fresh_connection` to "false" makes the most sence as part of `onopen`, the place where we test for it and the place that has first-hand knowledge of connection counts.  If there's a reason why it _needs_ to be in onclose instead of onopen, that should be commented.
</blockquote></details>

Done -- I renamed it to something else.
___
*[`geometry/meshcat.html` line 106 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9CEcfe6WUT5y96ZxUI:-N9DsK0b4J0jBQ51Am4k:b-f74l2q) ([raw file](https://github.com/robotlocomotion/drake/blob/ad1cbe248ff1957913ad5ce9579c7a20a3e04915/geometry/meshcat.html#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For my part, I don't see any particular need to make this configurable, but on the other hand it doesn't hurt anything.
</blockquote></details>

It now serves double duty -- it allows you to turn it off.

Any thoughts on how we want to communicate this functionality to the end user?

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM re-reading, but I haven't re-tested locally.  If you've done so, then I think we're OK for platform review.

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9IRm3l02SskBFrwSwG:b339z5h)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/meshcat.cc` line 1393 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9IRJ_xDBnK_F63LN0Z:-N9IRJ_xDBnK_F63LN0_:b-ldw1uq) ([raw file](https://github.com/robotlocomotion/drake/blob/120a55493e39869ee079506df03b8f3ca0911dc4/geometry/meshcat.cc#L1393)):*
> ```cpp
>     std::regex block_re(
>         "\n");
>     html = std::regex_replace(html, block_re, f.get());
> ```

nit If the regex fails to match (e.g., due to a typo) will a unit test report a failure?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ggould-tri for platform review.

+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9Wt-hk0IRGPT0MZLXS:bnmtmva)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @jwnimmer-tri)

___
*[`geometry/meshcat.cc` line 1393 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9IRJ_xDBnK_F63LN0Z:-N9WsJYO8HO-dqeG2lBk:b-31wzea) ([raw file](https://github.com/robotlocomotion/drake/blob/120a55493e39869ee079506df03b8f3ca0911dc4/geometry/meshcat.cc#L1393)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If the regex fails to match (e.g., due to a typo) will a unit test report a failure?
</blockquote></details>

Done

It has the closest thing to a unit test possible. Testing for the *meaningful* absence of something is always a bit...tricky.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

___
*[`geometry/meshcat.cc` line 1393 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9IRJ_xDBnK_F63LN0Z:-N9WzsajArJhQow9BJww:b-rayyio) ([raw file](https://github.com/robotlocomotion/drake/blob/120a55493e39869ee079506df03b8f3ca0911dc4/geometry/meshcat.cc#L1393)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

It has the closest thing to a unit test possible. Testing for the *meaningful* absence of something is always a bit...tricky.
</blockquote></details>

OK the other option would be to throw an exception _here_ in case the regex failed to match, in which case the unit test only needs statement coverage, not any specific new test case.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9X7ngYCQFvOZ5GYnjU:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`geometry/test/meshcat_test.cc` line 912 at r8](https://reviewable.io/reviews/robotlocomotion/drake/17685#-N9X7vLoAdL0dWi5Uov_:-N9X7vLoAdL0dWi5Uova:bqoxq49) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d6b18f9eb462449e2ce21e671429f1b2c6ce80/geometry/test/meshcat_test.cc#L912)):*
> ```cpp
>   // this appears to have happened by testing for the presence of the injected
>   // tree (base64 content) and the absence of what is *believed* to be the
>   // delimiting text of the connection block.
> ```

BTW:  You fixed this before I could hit publish on my comment on it!  :ninja:

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17685#-:-N9XFS7999tcnA32elS9:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
