### PR TITLE
tools: Trim FCL to only compile the parts we need

### LINKED ISSUE #13227: Improve build footprint by trimming FCL
Drake depends on FCL, octomap, and CCD.  We currently appear to compile _all_ of the code from those libraries, but in fact we only need some of it.  By pruning away unused cc files, we should be able to improve build times and reduce the installation footprint.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13227.

On my laptop, a `bazel build @fcl//:fcl` went from:

Release mode:
- total child process down from 130 to 71
- total cpu-seconds down from 315 to 170 (so -46%)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13230)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for initial feature review, please.  I'll add Jamie for a bazel review once your first pass is complete.

**Comment by jwnimmer-tri** [comment]
Ah, the debug builds are showing ODR errors, I was worried about that.  I'll work to fix locally.

**Comment by jwnimmer-tri** [comment]
I retconned the compile numbers into the top post this morning.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
So far so good!  One last check:
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for review, please.

**Comment by jwnimmer-tri** [comment]
(I'll file the upstream follow-up shortly.)

**Comment by jwnimmer-tri** [comment]
@jamiesnape 

> BTW We should probably clean up the config.h.in upstream so this is not necessary (harmless but just looks awkward).

Looking at upstream now, it actually seems okay to me?
https://github.com/flexible-collision-library/fcl/blob/43f9805445e73397077127556165f8af822c0383/include/fcl/config.h.in#L70-L73

It's just because we're re-implementing the substitution statically instead of with dynamic evaluation that we have this wart.

If you have an idea on an improvement I'm happy to run with it, but I don't know what issue to file now.

**Comment by jamiesnape** [comment]
Should be `#cmakedefine` there, I think, but not a big deal. I will clean it up if/when I next touch the file.

**Pull request merged**
