### PR TITLE
[doc] Add DDG searches to our Doxygen header

### LINKED ISSUE #7559: Drake docs appear searchable but really aren't
Liang helpfully pointed me to Drake's graphviz support today; this was especially helpful because it is nearly impossible to discover that Drake has graphviz support.

For instance, if you search Drake doxygen for "graphviz" it finds nothing.
no-gv
If you search Drake's top-level docs it finds nothing
no-gv2
In fact if you search google it finds nothing
no-gv3

A similar situation applies to other Drake concepts that are not exact class names; for example "algebraic loop" or "inverse kinematics".

The underlying issue is probably in part that (1) the search at drake.mit.edu does not reach the doxygen, and (2) the doxygen search only matches exact class and method names, not doxygen comment content or words appear in class or method names.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7559.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Here's a sample screenshot.

The "Quick jump..." is the same as what the search currently does.  The two new rectangular boxes are the DDG searches.

image

**Comment by sherm1** [comment]
Assign a feature reviewer?

**Review by RussTedrake — COMMENTED** [review]
+@russtedrake for both reviews, if you like.

:lgtm:

my only question is whether we can make the role of "Search C++ API only" vs "Quick Jump" more clear.  Now that I understand it, the words "quick jump" do seem reasonable to me.  But I didn't understand until I messed with it a bit, and that is coming with extensive experience using the doxygen search.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491#-:-MuuJvZlB4K0Z_Xct7Ej:b-2sn14p)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/header.html.patch, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16491#-MuuJki863D5YA9AlcoM:-MuuJki90p31UGdon92x:b-3atf9s) ([raw file](https://github.com/robotlocomotion/drake/blob/97d4bad8dd867e1597d03a6787c917ee12d743f4/doc/doxygen_cxx/header.html.patch#L8)):*
> ```Diff
> +   <td>
> +    <div id="DDGSearch">
> +     <form id="ddg-search-form" class="wy_form" action="https://duckduckgo.com/" method="get">
> ```

btw -- do you use duckduckgo here just for the anonymity?  Or does it make the search easier?

**Review by jwnimmer-tri — COMMENTED** [review]
I agree. I struggled with finding even this phrasing, though, so I'm out of ideas.  I'll see if anyone else can come up with something.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491#-:-MuuwK-SCrl4KTthFkkB:bxv9ie0)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/header.html.patch, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16491#-MuuJki863D5YA9AlcoM:-MuuvdFmCCDmy66TvsAe:b-1u8m8d) ([raw file](https://github.com/robotlocomotion/drake/blob/97d4bad8dd867e1597d03a6787c917ee12d743f4/doc/doxygen_cxx/header.html.patch#L8)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- do you use duckduckgo here just for the anonymity?  Or does it make the search easier?
</blockquote></details>

I did have the anonymity angle in mind, but mainly it was the low-infrastructure angle -- avoiding the need to maintain account details in our project infrastructure.  (I don't know if the search results are better or worse vs Google.  The results I got in a few test searches seemed OK though.)

**Review by rpoyner-tri — COMMENTED** [review]
I think you may have got what can be achieved in that small space. The only alternative I would offer is some kind of link or affordance to additional help text somewhere else?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491#-:-Muv4uXt05MZcCED7oBp:b-ayy4wz)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> If I use one of the DDG boxes, once I select a link and go there only the old Quick jump box is visible. Is it possible to keep all the boxes on screen either way?

That's because the search took you to the internet instead of 127.0.0.1, and the extra boxes aren't deployed yet.

**Comment by sherm1** [comment]
🤦 nvm!

**Comment by sherm1** [comment]
Here's what it looks like with the alternate name and no dots:
image

**Review by jwnimmer-tri — COMMENTED** [review]
I've pushed "Go to name" (instead of "Quick jump").

The dots match up the style with https://drake.mit.edu/pydrake/index.html.  We can nuke them throughout if we like, but that can be a follow-up.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491#-:-MuvuTfd889Ry2UX6Bmc:b-91f28z)* status: needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16491)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
