### PR TITLE
[schunk_wsg] Fix trajectory bug with initial zero target

### LINKED ISSUE #21920: Cannot close Schunk gripper to 0 position
# Symptom 1
If the Schunk gripper is initialized to a non-zero position, and commanded to close the gripper to 0 position, then the gripper will just stay at the current position, as shown in my [branch](https://github.com/hongkai-dai/drake/tree/schunk_gripper_close_init). To reproduce this error, run the test
```
bazel test //manipulation/schunk_wsg:build_schunk_wsg_control_test
```
Note that if we command the gripper to close to 10mm, it works fine. Only 0mm position command causes problem.

The reason is that the context of the schunk gripper` context.get_discrete_state(0).last_target_position()` is initialized to 0. So if the target position is also 0, then in this if-else branch https://github.com/RobotLocomotion/drake/blob/b5c15082fe608f7f49fe779757ce53cdfe97148c/manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc#L91-L101
`last_traj_state->last_target_position() - target_position` = 0, and the code will not enter into the `if` branch that updates the trajectory, but jumps to the `else` branch. As a result, in `OutputTarget` function, since `trajectory_` is empty (because `UpdateTrajectory()` was not called), the schunk will just set the last position as the target position, as in https://github.com/RobotLocomotion/drake/blob/b5c15082fe608f7f49fe779757ce53cdfe97148c/manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc#L48-L55

One quick fix is to force calling `UpdateTrajectory()`. But I think a better solution is to default-initialize the context gripper `context.get_discrete_state(0).last_target_position()` to a non-zero value, like kInf?

cc @IanTheEngineer , this is why in the slack discussion https://tri-internal.slack.com/archives/C05N7QM7GGL/p1726093498365569 the gripper doesn't close at the beginning.

# Symptom 2
A closely related symptom happens when I try to re-produce a simulation of the gripper. In the initial simulation, the gripper grasps an object and tries to close the gripper to commanded position 0mm. Because the object is in its way, the finger cannot completely close, and hence the finger position is at 70mm. Now I would like to re-simulate this gripper motion. I set the initial gripper position to 70mm, and set the command position to 0mm. But because `trajectory_` is empty at the start of the simulation, the gripper would just output the current position (70mm) as the target position. The gripper would not apply a gripping force if it wants to keep its current position, and hence the object would fall from the grasp.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Update trajectory when trajectory_ is empty, so that the gripper can close its fingers at the beginning of the simulation.

resolves #21920

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925#-:-O708PWz02fXHNF9ogST:b8uusp0)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

+@xuchenhan-tri for platform review (rotation)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925#-:-O74jFrK88fhZjNp37v2:b-u9py6l)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925#-:-O74yW7LEOtFjqoRyoC-:bg7igkv)* status: 1 unresolved discussion

___
*[`manipulation/schunk_wsg/test/build_schunk_wsg_control_test.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21925#-O74xv9IBca1rn7p6SGj:-O74xv9IBca1rn7p6SGk:bb7lc4s) ([raw file](https://github.com/RobotLocomotion/drake/blob/26416531fce027393f47681f6c30b94d78391973/manipulation/schunk_wsg/test/build_schunk_wsg_control_test.cc#L80)):*
> ```cpp
> TEST_F(BuildSchunkWsgControlTest, CommandToCloseAtBeginning) {
>   // The schunk gripper is open at the begin, and is command to close at the
>   // start.
> ```

nit 



_Suggestion:_
```cpp
  // The schunk gripper is initially open and is commanded to close.
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21925)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
