### PR TITLE
Fix sign-compare warnings in collision

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #2372.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2873)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
Very nice how you got rid of the sign/unsigned comparisons using range-based for's! :lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2873#-:-KNChIm_dYAUYc8bI18A:-217699816)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri for platform review and merge, please.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2873#-:-KND8S7tLOSoyWABAF_2:1417088721)*

**Pull request merged**
