### PR TITLE
sensors_py: Add RgbdCamera, RgbdCameraDiscrete, and CameraInfo

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
A step towards #7753

NOTE: I may end up seeing if I can squirrel in a `dev` shader API into `RgbdCamera`, rather than try to spend time splitting out classes, just to save time.
\cc @gizatt @ChristopherSweeney

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8235)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8235#-:-L6dmwHZuZ_T3Lqk-fSa:bv42ksy)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235#-:-L6qzrOP4hPsvcXt60hr:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235)*

**Comment by EricCousineau-TRI** [comment]
+@ggould-tri for platform review, please (since I'm on call tomorrow)

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235#-:-L6tQwBnA-NrKlRr5UXo:b-w7574u)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 5 files at r2.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[bindings/pydrake/systems/sensors_py.cc, line 136 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235#-L6w6-CbC3iU_KhjoK_r:-L6w6-CbC3iU_KhjoK_s:b19tj81) ([raw file](https://github.com/robotlocomotion/drake/blob/d3aa24df881b0b2ca486f7ceb50fb4e98b42db9a/bindings/pydrake/systems/sensors_py.cc#L136)):*
> ```cpp
>       m.attr(("Image" + enum_names[i].substr(1)).c_str()) = image;
>       // Add abstract values.
>       AddValueInstantiation<ImageT>(m);
> ```

FYI this is what the build failures are complaining about.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8235#-:-L6w952WBmkODxeCqzaS:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/sensors_py.cc, line 136 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8235#-L6w6-CbC3iU_KhjoK_r:-L6xiRZBDRBaqM_H8ACF:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/d3aa24df881b0b2ca486f7ceb50fb4e98b42db9a/bindings/pydrake/systems/sensors_py.cc#L136)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI this is what the build failures are complaining about.
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8235)*

**Pull request merged**
