### PR TITLE
Add renaming support to install framework

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add support for passing a map of install destinations to alternate file names to the install framework. This allows files to be renamed on install, which will be helpful for e.g. Java libraries, which Bazel insists on prefixing with "lib", and which we often want to have named the same as C++ libraries (which isn't otherwise possible because the build labels must be unique).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6389)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install.bzl, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5C5ORNE55bhWkrmSs:-Kn5C5ORNE55bhWkrmSt:bn6iy7h) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L87)):*
> ```Python
>         strip_prefix = strip_prefixes
> 
>     p = join_paths(dest, _output_path(ctx, artifact, strip_prefix))
> ```

FYI `p` as a variable name does not help a reader understand this code.

---

*[tools/install.bzl, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn57R-3Db6whjO_FhGz:-Kn57R-4URtTmIKAdSgc:buyu5zd) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L89)):*
> ```Python
>     p = join_paths(dest, _output_path(ctx, artifact, strip_prefix))
>     if p in rename:
>         print(p)
> ```

Debugging print?

---

*[tools/install.bzl, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn57PyGxkWE2PPLflnb:-Kn57PyGxkWE2PPLflnc:buyu5zd) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L92)):*
> ```Python
>         renamed = rename[p]
>         p = join_paths(dirname(p), renamed)
>         print(p)
> ```

Debugging print?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-:-Kn5CFwytrLEUha5Z_ps:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install.bzl, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5C5ORNE55bhWkrmSs:-Kn5HJDWgHJmBGmuUrhW:b-d7tnrs) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `p` as a variable name does not help a reader understand this code.
</blockquote></details>

→ `file_dest`

---

*[tools/install.bzl, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn57R-3Db6whjO_FhGz:-Kn5HMqOfsmqFq36mAnj:b-43q0x1) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Debugging print?
</blockquote></details>

Indeed. Fixed; thanks!

---

*[tools/install.bzl, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn57PyGxkWE2PPLflnb:-Kn5HP-TW5vHThD1NKv3:b-43q0x1) ([raw file](https://github.com/robotlocomotion/drake/blob/f36e4ec37a6dfb5c54b301a5d71763d1d39e4d91/tools/install.bzl#L92)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Debugging print?
</blockquote></details>

Indeed. Fixed; thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-:-Kn5TFBob2QDG2z3h3Hw:bnfp4nl)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5VXXS_o71Uc4lxZ51:-Kn5VXXS_o71Uc4lxZ52:b-uxyol9) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2e5a1fc62f06163046a24fd12a655243dd12ce/tools/install.bzl#L88)):*
> ```Python
> 
>     file_dest = join_paths(dest, _output_path(ctx, artifact, strip_prefix))
>     if file_dest in rename:
> ```

The map relies on file_dest. For excluded files, we rely on input path. Would it make sense to be consistent and always rely on input path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5VXXS_o71Uc4lxZ51:-Kn5euvZ-5tlOyboWmDp:bmthinz) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2e5a1fc62f06163046a24fd12a655243dd12ce/tools/install.bzl#L88)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

The map relies on file_dest. For excluded files, we rely on input path. Would it make sense to be consistent and always rely on input path?
</blockquote></details>

Possibly, but then I'd have to call `_output_path` a *third* time...

If bazelbuild/bazel#3227 ever gets fixed, this will get a lot easier...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Comment by fbudin69500** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5VXXS_o71Uc4lxZ51:-Kn6-XGehNH3UGNXVCJq:b-x03qqu) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2e5a1fc62f06163046a24fd12a655243dd12ce/tools/install.bzl#L88)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Possibly, but then I'd have to call `_output_path` a *third* time...

If bazelbuild/bazel#3227 ever gets fixed, this will get a lot easier...
</blockquote></details>

I leave that choice up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-:-Kn6-bux_odxm7ahyLkX:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install.bzl, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6389#-Kn5VXXS_o71Uc4lxZ51:-Kn653L7AN2135Y6Ocsl:b9e60m) ([raw file](https://github.com/robotlocomotion/drake/blob/eb2e5a1fc62f06163046a24fd12a655243dd12ce/tools/install.bzl#L88)):*
<details><summary><i>Previously, fbudin69500 (Francois Budin) wrote…</i></summary><blockquote>

I leave that choice up to you.
</blockquote></details>

Leaving it for now; added a TODO to refactor later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6389)*

**Pull request merged**
