### PR TITLE
[workspace] Deprecate the ccd and fcl externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17231.  In the near future, we can adjust the build recipes for `..._internal` to better suit our needs, but doing that here was too much churn.  Here we just fork the rule largely unchanged, in support of deprecation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18611)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

Note that the commits are curated and in Reviewable as r1 and r2.  Reviewing them one-at-a-time might be easiest.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 19 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18611#-:-NM5Ujg1DEt9tBXH9BdE:bnfp4nl)* status: needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.  Note my comment above about reviewing commits one-at-a-time.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 19 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18611#-:-NM66GEv7fo00ZG6xVoF:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Pull request merged**
