### PR TITLE
fix c_iris tests

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Closes #18759.

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18760)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@BetsyMcPhail +@svenevs  There was one more error in that test

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18760#-:-NNqn7ixDx2lI7GxSVZK:bujcj4c)* status: LGTM missing from assignees BetsyMcPhail,svenevs, missing label for release notes (waiting on @BetsyMcPhail and @svenevs)

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-debug please.

**Review by svenevs — COMMENTED** [review]
:lgtm_strong: +@EricCousineau-TRI for platform review please.  There's been [some excitement in #buildcop](https://drakedevelopers.slack.com/archives/C270MN28G/p1675953863786089) related to this, TL;DR: macOS debug CI has some unrelated issues we're tracking in #18762 , the code in question is in `dev/` and otherwise setup correctly as far as we know.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18760#-:-NNr_8TE8YOevvmxYwMS:b-p6gjac)* status: LGTM missing from assignees BetsyMcPhail,EricCousineau-TRI(platform), missing label for release notes (waiting on @BetsyMcPhail and @EricCousineau-TRI)

**Review by svenevs — COMMENTED** [review]
+(release notes: none) -@BetsyMcPhail 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18760#-:-NNraU86-rpPPpjzdYpT:b-bpjzh)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
-@EricCousineau-TRI no platform review required on dev code.

**Pull request merged**
