### PR TITLE
Fold the two abstract car demos into one

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3557)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-:-KSEGaIkt2dxJIxnCoWo:b-4zoj1h)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-:-KSHiQmLhML5w3E3BMed:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@maddog-tri Thanks!  But you need to mark the green eyeball on files as you go (or else hit "Mark as reviewed" atop).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-:-KSHjOYCLpingJNDPHl2:bff8408)*

**Comment by david-german-tri** [comment]
+@david-german-tri for platform review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-:-KSHkwP1i6997AJkQEDs:b-rhk18b)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-KSHlcHAygyo2FGxy2L1:-KSHlcHAygyo2FGxy2L2:bc2mf81) ([raw file](https://github.com/robotlocomotion/drake/blob/7c3e186126d31c5358b66e9a3093dc52dcbc1eb9/drake/automotive/automotive_demo.cc#L113)):*
> ```cpp
>   // TODO(jwnimmer-tri) Allow for multiple simple cars.
>   if (FLAGS_num_simple_car > 1) {
>     std::cerr << "ERROR: Only one simple car is supported (for now)."
> ```

BTW, can/should this be done with spdlog?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-:-KSHln84MAZRFbeY8vvB:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_demo.cc, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3557#-KSHlcHAygyo2FGxy2L1:-KSHmHaxbD1vjtr5JnMe:bwwq8k3) ([raw file](https://github.com/robotlocomotion/drake/blob/7c3e186126d31c5358b66e9a3093dc52dcbc1eb9/drake/automotive/automotive_demo.cc#L113)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, can/should this be done with spdlog?
</details>
Good idea, I didn't consider that.  But will defer to future, because (1) hope to remove this TODO soon, and (2) I don't feel like fighting more `#undef GetMessageA` battles if I can help it for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3557)*

**Pull request merged**
