### PR TITLE
toward #1749: fix a stray lint error.

### PR DESCRIPTION
**Pull request by rpoyner-tri**

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+1 LGTM.

**Comment by david-german-tri** [comment]
LGTM as well

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by liangfok** [comment]
Who does the retest?  Owner of thus PR? Upstream repo dictator?  CI daemon?

Just trying to understand the protocol...

**Comment by liangfok** [comment]
+1 for merge

**Comment by jwnimmer-tri** [comment]
> Who does the retest?

A magic CI command; see [jenkins.html](http://drake002.csail.mit.edu/drake/sphinx/jenkins.html).

**Pull request merged**
