### PR TITLE
Convert kuka_demo to use PidControlledSystem

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3785)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@liangfok for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-:-KTuKop61XAay6LjM9A_:b-ui3opy)*

**Comment by liangfok** [comment]
:lgtm: A great reduction in the amount of code needed. Just one question.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTuLOXghStVNWcQgU91:bxieu1u) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
> ```objc
> /// * The first output port must be of size N * 2, where the first N
> /// * elements are the positions of the elements of the controlled
> /// * system, and the second N elements are the velocities.
> ```

BTW. Does this mean this PID control system doesn't support  [quaternion floating joints](http://drake.mit.edu/doxygen_cxx/class_quaternion_floating_joint.html) since they have 7 position and 6 velocity states?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-:-KTuNPJd-cRYJyWnW5Bu:b6kpwzb)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTuNr809sVuD62bNlJ7:bxgqejg) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW. Does this mean this PID control system doesn't support  [quaternion floating joints](http://drake.mit.edu/doxygen_cxx/class_quaternion_floating_joint.html) since they have 7 position and 6 velocity states?
</details>
Ouch.  Yes, it does.  This would have been a problem even with the longer formulation for a couple of reasons.  

Demultiplexer (which is used to split the positions and velocities) requires that its outputs all be the same size.  Additionally, PidController requires that the derivative errors (which in the case of PidControlledSystem is the difference between the target velocities and the observed velocities) be of the same size as the position errors...  We're also assuming that the output of the PidController (which is the same size of the number of positions) is the same size as the input to the controlled system, which doesn't sound like the case for a quaternion floating joint either?   The first is fixable, though the only formulation I can think of is kinda convoluted in terms of the actual code.  The remaining issues seem like a considerably bigger deal, since the number of positions may not be related to the input size of the system or the number of velocities.  Hmm....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-:-KTuSvxWC2vhE1cH7R3T:b-ykw85)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTuTjvLI4ldtqm9IWPf:b9mctn5) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Ouch.  Yes, it does.  This would have been a problem even with the longer formulation for a couple of reasons.  
> 
> Demultiplexer (which is used to split the positions and velocities) requires that its outputs all be the same size.  Additionally, PidController requires that the derivative errors (which in the case of PidControlledSystem is the difference between the target velocities and the observed velocities) be of the same size as the position errors...  We're also assuming that the output of the PidController (which is the same size of the number of positions) is the same size as the input to the controlled system, which doesn't sound like the case for a quaternion floating joint either?   The first is fixable, though the only formulation I can think of is kinda convoluted in terms of the actual code.  The remaining issues seem like a considerably bigger deal, since the number of positions may not be related to the input size of the system or the number of velocities.  Hmm....
</details>
This sounds related to the problem that `System<T>::MapVelocityToConfigurationDerivatives` solves.  Perhaps, to be controllable in (future generalizations of) this wrapper, a system should expose `q` and `qdot = f(v)` in its outputs, rather than `q` and `v`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTuYkEZlODQsGT6iU9O:bxlq7h5) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This sounds related to the problem that `System<T>::MapVelocityToConfigurationDerivatives` solves.  Perhaps, to be controllable in (future generalizations of) this wrapper, a system should expose `q` and `qdot = f(v)` in its outputs, rather than `q` and `v`?
</details>
How about redefining the controller so that it is only usable on systems having only 1-dof joints for which qdot=v? Controlling orientation directly with a PID controller doesn't sound straightforward to me and isn't likely to decompose into uncoupled scalar PID controllers. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTvQwijMD6wdXEWS0vI:-KTvQwijMD6wdXEWS0vJ:br5whh2) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L200)):*
> ```cpp
> 
>     // Instantiates a RigidBodyPlant from an MBD model of the world.
>     std::unique_ptr<RigidBodyPlant<T>> plant =
> ```

BTW Consider `auto` for brevity, and consistency with the make-RBT above.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 275 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTvQ9imA8iFQP5q63pL:-KTvQ9imA8iFQP5q63pM:b-en1xad) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L275)):*
> ```cpp
>  private:
>   RigidBodyPlant<T>* plant_;
>   PidControlledSystem<T>* controller_;
> ```

Missing value-initialization (`{}`) per code_style_guide on this pointer.  (I guess also all the other pointers.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-:-KTuZyK4BsFcEjKkjp6B:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 275 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTvQ9imA8iFQP5q63pL:-KTyFQ_Q3MF7-NlJv_jY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L275)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing value-initialization (`{}`) per code_style_guide on this pointer.  (I guess also all the other pointers.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by liangfok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTv_SPgiAhXR3Ad8TuO:b1b30fz) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> How about redefining the controller so that it is only usable on systems having only 1-dof joints for which qdot=v? Controlling orientation directly with a PID controller doesn't sound straightforward to me and isn't likely to decompose into uncoupled scalar PID controllers. 
</details>
Thanks for the advice! I'll keep these ideas in mind as I make progress on porting `car_sim_lcm` to System 2.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc, line 275 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTvQ9imA8iFQP5q63pL:-KTyM5Uj5Acl66-FWwu5:b6bc95h) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L275)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Done.
</details>
Heh, I guess everyone but me hates the plain `foo_{};` for "don't care".  Anyway, LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/controllers/pid_controlled_system.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3785#-KTuLOXfWbj4ulE9QM7s:-KTyMPW_EYOtUJkSI4jT:b53ec5k) ([raw file](https://github.com/robotlocomotion/drake/blob/1e0804d2d19e2bac5240b25d83648aa9f9ae1748/drake/systems/controllers/pid_controlled_system.h#L27)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks for the advice! I'll keep these ideas in mind as I make progress on porting `car_sim_lcm` to System 2.0.
</details>
I am dismissing @sherm1 here, because future improvements are beyond the scope of a port-this-demo PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3785)*

**Pull request merged**
