### PR TITLE
Added Sphinx and Doxygen Instructions.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves https://github.com/RobotLocomotion/drake/issues/2344

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2349) &emsp; Multiple assignees:&emsp;@amcastro-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/amcastro-tri">amcastro-tri</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please
+@david-german-tri for platform review please

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added Sphinx and Doxygen Instructions\.
> 
> Resolves https://github.com/RobotLocomotion/drake/issues/2344
> 
> 
> </details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHfywpJRN5Ze8Xydjar:-2009898159)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/doc/doxygen_instructions.rst, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtnH9Gq2uKhBkXl_9w:-KHtnH9Gq2uKhBkXl_9x:-1351604540) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L7)):*
> ```reStructuredText
> ********************
> 
> This section contains instructions on how to use `Doxygen <http://www.stack.nl/~dimitri/doxygen/>`_ with Drake.
> ```

It looks like we are trying to stick to the 80 characters limit in most of the docs (though there are exceptions). Should we try to stick to this limit on new doc?

---

*[drake/doc/doxygen_instructions.rst, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtnff5hfh7arihy5Gm:-KHtnff5hfh7arihy5Gn:1204305031) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L15)):*
> ```reStructuredText
> 
> Coming soon. See issue
> `#2051 <https://github.com/RobotLocomotion/drake/issues/2051>`_.
> ```

Maybe worth mentioning #2359 also?

---

*[drake/doc/doxygen_instructions.rst, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtpF7qNd6hz6cRVYNb:-KHtpF7qNd6hz6cRVYNc:-297360536) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L32)):*
> ```reStructuredText
> To view the generated website, open ``index.html`` using your favorite web
> browser.
> ```

I would add a comment here that the above set of commands will activate the building of the documentation even when we are just trying to build the source only. 
And then you introduce the `BUILD_DOCUMENTATION=OFF` as a solution for that.

---

*[drake/doc/doxygen_instructions.rst, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtqO0fLA0QM2kibDCM:-KHtqO0fLA0QM2kibDCN:1392142806) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L41)):*
> ```reStructuredText
>     $ cd [build artifacts directory]
>     $ cmake -DBUILD_DOCUMENTATION=OFF ..
>     $ make
> ```

Missing CR at the end of file

---

*[drake/doc/sphinx_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtqRtKPHZeWiy6PCI0:-KHtqRtKPHZeWiy6PCI1:1392142806) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/sphinx_instructions.rst#L20)):*
> ```reStructuredText
> The generated website will be in ``[build artifacts directory]/doc/sphinx/``.
> To view the generated website, open ``index.html`` using your favorite web
> browser.
> ```

Missing CR at the end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by liangfok** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[drake/doc/doxygen_instructions.rst, line 7 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtnH9Gq2uKhBkXl_9w:-KHtsoVZPWOKuAjReG34:-1298593185) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> It looks like we are trying to stick to the 80 characters limit in most of the docs (though there are exceptions). Should we try to stick to this limit on new doc?</details>
That's a good idea. Fixed.

---

*[drake/doc/doxygen_instructions.rst, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtnff5hfh7arihy5Gm:-KHtsqXvIzZ4BEfyBv14:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Maybe worth mentioning #2359 also?</details>
Done.

---

*[drake/doc/doxygen_instructions.rst, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtpF7qNd6hz6cRVYNb:-KHtw83b9-NpHoohV0Mg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I would add a comment here that the above set of commands will activate the building of the documentation even when we are just trying to build the source only. 
> And then you introduce the `BUILD_DOCUMENTATION=OFF` as a solution for that.</details>
Done.

---

*[drake/doc/doxygen_instructions.rst, line 41 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtqO0fLA0QM2kibDCM:-KHtwC-xJ8xQWjtAvz7Q:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/doxygen_instructions.rst#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Missing CR at the end of file</details>
Done.

---

*[drake/doc/sphinx_instructions.rst, line 20 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHtqRtKPHZeWiy6PCI0:-KHtwHJ1RCMrOEWDqaqr:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/a0093e5df2b5ff7eac28e388fdae88dd3f8b33ed/drake/doc/sphinx_instructions.rst#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Missing CR at the end of file</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/CMakeLists.txt, line 66 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8b1L89hgEOxx6DIe:-KHu8b1L89hgEOxx6DIf:-214352165) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/CMakeLists.txt#L66)):*
> ```CMake
> 
> if (CMAKE_COMPILER_IS_GNUCC)
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wreturn-type -Wuninitialized -Wunused-variable")
> ```

oops! how did this get here?

---

*[drake/doc/sphinx_instructions.rst, line 20 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8gH_PbKXKyit_2jG:-KHu8gH_PbKXKyit_2jH:854105969) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/doc/sphinx_instructions.rst#L20)):*
> ```reStructuredText
> The generated website will be in ``[build artifacts directory]/doc/sphinx/``.
> To view the generated website, open ``index.html`` using your favorite web
> browser.
> ```

Is the CR here? Maybe reviewable does not show it?....

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8euHMIgjK1-Pf_s0:-KHu8euHMIgjK1-Pf_s1:-214352165) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/systems/plants/test/testIKtraj.cpp#L21)):*
> ```cpp
>   Vector2d tspan;
>   tspan << 0, 1;
>   int l_hand{};
> ```

oops! how did this get here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by liangfok** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/CMakeLists.txt, line 66 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8b1L89hgEOxx6DIe:-KHu9tjJnLZW_IxvbKPW:1208732756) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/CMakeLists.txt#L66)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> oops! how did this get here?</details>
Somehow this PR got mixed up with another PR that was already merged:

https://github.com/RobotLocomotion/drake/pull/2353/files

@david-german-tri or @jwnimmer-tri: I've seen this behavior in the past. It seems to resolve itself over time. Do you know what causes it?

---

*[drake/doc/sphinx_instructions.rst, line 20 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8gH_PbKXKyit_2jG:-KHuA7cRcP4airq3nsqB:-286539755) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/doc/sphinx_instructions.rst#L20)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Is the CR here? Maybe reviewable does not show it?....</details>
Yes, if it's missing a CR, Reviewable will be an "angry red arrow with a circle" icon indicating a missing CR.

---

*[drake/systems/plants/test/testIKtraj.cpp, line 21 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHu8euHMIgjK1-Pf_s0:-KHuAU4HOYf-p_m4QbCe:1482670563) ([raw file](https://github.com/robotlocomotion/drake/blob/6ecd65ca7c09c1856e6f79aba6d11a6baa0b357d/drake/systems/plants/test/testIKtraj.cpp#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> oops! how did this get here?</details>
See comment above about how this PR was mixed with another PR that was already merged. :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by amcastro-tri** [comment]
Besides the strange mix up with commit #2353 this :lgtm_strong: 

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@amcastro-tri for feature review please
> +@david-german-tri for platform review please</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHuBXbHYB2bCEZBxMnP:-430196543)*

**Comment by liangfok** [comment]
I saw some emails saying @sherm1 is the platform reviewer for Mondays. Thus +@sherm1 for platform review. (Please correct me if I'm jumping the gun.)

<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Besides the strange mix up with commit #2353 this :lgtm_strong: </details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHuC_lz3QtZSgzP3xhu:1803111557)*

**Comment by sherm1** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/doxygen_instructions.rst, line 40 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvISNa4IUYX_UcBCp8:-KHvISNa4IUYX_UcBCp9:1978529030) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L40)):*
> ```reStructuredText
> 
> ** Note 2:** By enabling the ``BUILD_DOCUMENTATION`` cmake option, the
> documentation will be build *every* time you compile Drake. To stop this, see
> ```

build -> built

---

*[drake/doc/doxygen_instructions.rst, line 42 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvJHwA526d-RxbXK-1:-KHvJHwA526d-RxbXK-2:-255687216) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L42)):*
> ```reStructuredText
> documentation will be build *every* time you compile Drake. To stop this, see
> instructions below on how to disable documentation generation.
> ```

This isn't how I build documentation on Windows. I use the Visual Studio IDE. WIth the BUILD_DOCUMENTATION option on, there is a `documentation` target visible: 

When I want to update the documentation I just build that target in the IDE; it doesn't build when I build other targets. Very convenient!

Unless this documentation is intended only for Linux users, I think the free and very useful Visual Studio IDE deserves a mention here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by sherm1** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349)*

**Comment by liangfok** [comment]
I just updated this PR with major changes. PTAL. Thanks!

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I saw some emails saying @sherm1 is the platform reviewer for Mondays. Thus +@sherm1 for platform review. (Please correct me if I'm jumping the gun.)</details>


---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/doxygen_instructions.rst, line 40 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvISNa4IUYX_UcBCp8:-KHvNEUFGQlfmCV24UB9:-795674665) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L40)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> build -> built</details>
Fixed. Thanks!

---

*[drake/doc/doxygen_instructions.rst, line 42 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvJHwA526d-RxbXK-1:-KHvKFW3f36_G106GHnW:1181070905) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This isn't how I build documentation on Windows. I use the Visual Studio IDE. WIth the BUILD_DOCUMENTATION option on, there is a `documentation` target visible: 
> 
> When I want to update the documentation I just build that target in the IDE; it doesn't build when I build other targets. Very convenient!
> 
> Unless this documentation is intended only for Linux users, I think the free and very useful Visual Studio IDE deserves a mention here.</details>
Thanks for the review. I modified this PR to include Visual Studio instructions. I didn't add them before because I actually haven't used Visual Studio with Drake yet! 

As an aside, we should update [this wiki page](http://drake.mit.edu/windows.html) with instructions on how to load Drake into Visual Studio. Is it as simple as "Launch Visual Studio, then open the Visual Studio solution (`.sln`) file generated by CMake"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHvTRI3R6Wokj5LRG3t:-1865917462)*

**Comment by sherm1** [comment]
One comment. :lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I just updated this PR with major changes. PTAL. Thanks!</details>


---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/doxygen_instructions.rst, line 42 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvJHwA526d-RxbXK-1:-KHveFg-6ibXrXOsYm3H:-823543579) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Thanks for the review. I modified this PR to include Visual Studio instructions. I didn't add them before because I actually haven't used Visual Studio with Drake yet! 
> 
> As an aside, we should update [this wiki page](http://drake.mit.edu/windows.html) with instructions on how to load Drake into Visual Studio. Is it as simple as "Launch Visual Studio, then open the Visual Studio solution (`.sln`) file generated by CMake"?</details>
The first time through I have to click on `[build_dir]/drake-superbuild.sln` then do an `ALL_BUILD` in the VS GUI. When that finishes (a long time later!) I close that and click on `[build_dir]/drake/drake.sln` where I can make changes and rebuild frequently; that's where I see the project list I posted above. Setting PATH properly is required before that second step but I think that's already in the instructions. Currently both builds must be Debug, or both must be Release; I haven't been able successfully to switch between them on the fly (though that should be possible on Windows).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHvfvvEca2nUh_Caykj:-656881122)*

**Comment by liangfok** [comment]
I believe this PR is ready for final review / merge.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> One comment. :lgtm:</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/doxygen_instructions.rst, line 42 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-KHvJHwA526d-RxbXK-1:-KHz2L60VLkqoEDt2C8G:1531870812) ([raw file](https://github.com/robotlocomotion/drake/blob/20dc9552f75c0c25b8338c5c6b2e1db188b66f86/drake/doc/doxygen_instructions.rst#L42)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> The first time through I have to click on `[build_dir]/drake-superbuild.sln` then do an `ALL_BUILD` in the VS GUI. When that finishes (a long time later!) I close that and click on `[build_dir]/drake/drake.sln` where I can make changes and rebuild frequently; that's where I see the project list I posted above. Setting PATH properly is required before that second step but I think that's already in the instructions. Currently both builds must be Debug, or both must be Release; I haven't been able successfully to switch between them on the fly (though that should be possible on Windows).</details>
Thanks @sherm1. I've updated https://github.com/RobotLocomotion/drake/issues/2204 with your notes and will update the wiki after replicating what you're doing on my local windows machine. For now, let's mark this thread as satisfied so this PR can be merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2349#-:-KHz2_go9DJdBPu6PUQ0:-2046366401)*

**Pull request merged**
