### PR TITLE
Toward #2852: enforce -Werror=shadow in solvers/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove the excuse from the build rules.
 * Fix the shadowing cases found.
 * Fix a few other easy style guide violations;
   * numerous others remain unfixed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2880)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
This is another step toward #2852, but much more remains.

**Comment by rpoyner-tri** [comment]
+@naveenoid for feature review;
+@sammy-tri for platform review and merge.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-:-KNDn46qV5ScSQz6CMPM:314749824)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/QP.cpp, line 146 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNDsBvXARtMBcq1NV9M:-KNDsBvYk-zv1VqosBlW:2103713351) ([raw file](https://github.com/robotlocomotion/drake/blob/ba1940bb9fad182044f8cf87f243bae13bdf284d/drake/solvers/QP.cpp#L146)):*
> ```cpp
> 
>       if (n_active > 0) {
>         int start_row = 0;
> ```

I think having variables named startrow and start_row in the same function might be a bit confusing...  Is there a reason not to reuse the existing variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/QP.cpp, line 146 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNDsBvXARtMBcq1NV9M:-KNDt8aPO5c9mQWba8F8:-1718455638) ([raw file](https://github.com/robotlocomotion/drake/blob/ba1940bb9fad182044f8cf87f243bae13bdf284d/drake/solvers/QP.cpp#L146)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think having variables named startrow and start_row in the same function might be a bit confusing...  Is there a reason not to reuse the existing variable?
</details>
I would have felt a little more confident about doing that if I could run the test locally</gurobi-license>. I'll take another look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by rpoyner-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/QP.cpp, line 146 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNDsBvXARtMBcq1NV9M:-KNDwIZz7tCOJNZmu2oc:-2047746956) ([raw file](https://github.com/robotlocomotion/drake/blob/ba1940bb9fad182044f8cf87f243bae13bdf284d/drake/solvers/QP.cpp#L146)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> I would have felt a little more confident about doing that if I could run the test locally</gurobi-license>. I'll take another look.
</details>
Testing a new version now...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by rpoyner-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/QP.cpp, line 146 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNDsBvXARtMBcq1NV9M:-KNDzXGD499E-ZONY017:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ba1940bb9fad182044f8cf87f243bae13bdf284d/drake/solvers/QP.cpp#L146)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> Testing a new version now...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-:-KNE3UIsvEgVa5p48h9W:1417088721)*

**Comment by naveenoid** [comment]
Reviewed 5 of 7 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/solvers/MosekLP.cpp, line 163 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNE-7HteLEIRKuEt324:-KNE-7Hu5nUkDlXF4tZr:141553599) ([raw file](https://github.com/robotlocomotion/drake/blob/f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333/drake/solvers/MosekLP.cpp#L163)):*
> ```cpp
>   for (auto&& con : prog.GetAllLinearConstraints()) {
>     // check to see if the constraint references a single variable,
>     // which is handles as a variable bound by mosek
> ```

typo : handled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/QP.cpp, line 470 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNE3gBLwx-Hp2BLQVZs:-KNE3gBLwx-Hp2BLQVZt:480928489) ([raw file](https://github.com/robotlocomotion/drake/blob/f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333/drake/solvers/QP.cpp#L470)):*
> ```cpp
>   int offset = 0;
>   active.clear();
>   for (int k = 0; k < Ain.rows(); k++) {
> ```

BTW : why this refactor of 'i'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/MosekLP.cpp, line 163 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNE-7HteLEIRKuEt324:-KNE44v8ry7rwJN3UY23:-195024001) ([raw file](https://github.com/robotlocomotion/drake/blob/f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333/drake/solvers/MosekLP.cpp#L163)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> typo : handled
</details>
BTW : might as well fix some glaring grammatical omissions on comments. Perhaps a quick followup PR can handle that as well..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/MosekLP.cpp, line 163 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNE-7HteLEIRKuEt324:-KNE4ZOJyFEpkOSaCA3R:-18395308) ([raw file](https://github.com/robotlocomotion/drake/blob/f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333/drake/solvers/MosekLP.cpp#L163)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : might as well fix some glaring grammatical omissions on comments. Perhaps a quick followup PR can handle that as well..
</details>
Hm. I would certainly rather handle such defects in a separate PR. If you *really* want me to go grammar-cop on this code which I can't even test locally, I can, but you'll certainly be on the hook to review it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/QP.cpp, line 470 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-KNE3gBLwx-Hp2BLQVZs:-KNE5xRge6Auj7Edv-vC:1687490490) ([raw file](https://github.com/robotlocomotion/drake/blob/f2c4d53d0ed636cf482fe23e4ca0775e1a7e2333/drake/solvers/QP.cpp#L470)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary>
> BTW : why this refactor of 'i'?
</details>
Another 'i' is in scope already. Rather than reuse it (which I didn't bother to try to verify was safe), I chose another name, so at least the distinction would be clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2880#-:-KNE6Rgej1pvSJvOD6ev:1417088721)*

**Pull request merged**
