### PR TITLE
[workspace] Remove vestigial jupyter package

### PR DESCRIPTION
**Pull request by svenevs**
- https://jupyter.org/install#jupyter-notebook
- https://pypi.org/project/jupyter/ (very old...)
- https://pypi.org/project/notebook/ (what we want...)

Note that `notebook` is already installed via binary_distribution/requirements.txt.

Via https://github.com/RobotLocomotion/drake/pull/21013#pullrequestreview-1912144495

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please.

To make sure...

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: none) since this is a test-only change.

+@jwnimmer-tri :lgtm: both +(status: single reviewer ok).

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-:-Nrw2UKK54uVWzp2HIGs:b-ytnac5)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-Nrw2cfB2a5iKss3YNlV:-Nrw2cfC8PjOuoHhnz9t:buj3ax6) (no related file):*
Don't we need the patch to `jupyter_notebook_test.py` in this PR, too?

___

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-Nrw2cfB2a5iKss3YNlV:-Nrw3-IgEyjYGsCx_rXy:b-m1phxx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Don't we need the patch to `jupyter_notebook_test.py` in this PR, too?
</blockquote></details>

TBH I'm not sure... why I wanted to re-run unprovisioned CI.  However, my understanding is the `jupyter` command will still exist...

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-Nrw2cfB2a5iKss3YNlV:-Nrw3n8I8gS-9SWbYvuQ:b-qua3s4) (no related file):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

TBH I'm not sure... why I wanted to re-run unprovisioned CI.  However, my understanding is the `jupyter` command will still exist...
</blockquote></details>

Fair enough.  I guess we'll see!

___

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-unprovisioned-clang-bazel-experimental-release please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-Nrw2cfB2a5iKss3YNlV:-NrwFePf15GCxzgpU-9y:b-fqdy0t) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fair enough.  I guess we'll see!
</blockquote></details>

OK, it makes more sense to have both here.  Re-pushed and relaunched, having this cherry-picked on the other PR makes it easier for me to build the mac images right now.

___

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: 1 unresolved discussion

___
*[`tools/jupyter/test/jupyter_notebook_test.py` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-NrwHdctDa3ggaOY4gXm:-NrwHdcu7XFHQrtWYdEo:b-defupw) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9c22234f2f54e040c3d7289c2a7f1099f2ef3d0/tools/jupyter/test/jupyter_notebook_test.py#L10)):*
> ```Python
>         """Ensures that `jupyter notebook` is installed (#12042)."""
>         status = subprocess.call(
>             args=[sys.executable, "-m", "notebook", "--help"])
> ```

Actually, looking at this more closely, I think we've defeated the purpose of this test.

See #12043.  The purpose of this test is to ensure that after the user runs the `setup` scripts, that `jupyter notebook` in the terminal works.  We should _not_ be changing this test at all.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085)* status: 1 unresolved discussion

___
*[`tools/jupyter/test/jupyter_notebook_test.py` line 10 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-NrwHdctDa3ggaOY4gXm:-NrwIFMC1z4R99yMAqdI:b-8wwfsk) ([raw file](https://github.com/RobotLocomotion/drake/blob/c9c22234f2f54e040c3d7289c2a7f1099f2ef3d0/tools/jupyter/test/jupyter_notebook_test.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually, looking at this more closely, I think we've defeated the purpose of this test.

See #12043.  The purpose of this test is to ensure that after the user runs the `setup` scripts, that `jupyter notebook` in the terminal works.  We should _not_ be changing this test at all.
</blockquote></details>

The docs at https://jupyter.org/install#jupyter-notebook still say that `jupyter notebook` is the right way do to things, so this test should have been fine as-is.  If it is not passing with python 3.12 setup scripts, then the setup scripts are still broken.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm_cancel: per DMs, we plan to cancel this one.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21085#-:-NrwPqW3DogpkrPJjj3Q:b4ff133)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Comment by svenevs** [comment]
It ended up being a different problem.

**Pull request closed without merging**
