### PR TITLE
common: provides ExtractDoubleOrThrow for Eigen::MatrixBase

### PR DESCRIPTION
**Pull request by RussTedrake**
Revives and completes #13003.

I needed this method again, and my c++ foo has grown, so I decided to slay the old dragon.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@soonho-tri for feature review, please.  (based on our history with #13003) and the fact that I touch symbolic.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518#-:-MfmOvJv4gQpLuwabo-4:brqe1fp)* status: LGTM missing from assignee soonho-tri(platform), needs at least two assigned reviewers (waiting on @soonho-tri)

**Comment by RussTedrake** [comment]
fwiw @mitiguy -- you had a comment on #13003 and I do see that RigidTransform and friends could benefit from this.  Hopefully it will be available soon if you want to switch to using it.

**Review by soonho-tri — COMMENTED** [review]
:lgtm: 
+@ericcousineau-tri for platform-review per schedule, please.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518#-:-MfmXay73ya8sEj9EAOL:btmgzpe)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[common/autodiff_overloads.h, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmXpvO0iFrhUXjWJOP:-MfmXpvO0iFrhUXjWJOQ:b-z76rs3) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/autodiff_overloads.h#L166)):*
> ```objc
> /// allocation as @p matrix.  Calls ExtractDoubleOrThrow on each element of the
> /// matrix, and therefore throws if any one of the extractions fail.
> template <typename DerType, int RowsAtCompileTime, int ColsAtCompileTime,
> ```

nit, 

1) We can also add `int Options` as template parameter.
2) Using `auto` in return-type makes it easier to read?

```c++
 template <typename DerType, int RowsAtCompileTime, int ColsAtCompileTime,
          int Options, int MaxRowsAtCompileTime, int MaxColsAtCompileTime>
 auto ExtractDoubleOrThrow(
     const Eigen::MatrixBase<Eigen::Matrix<
         Eigen::AutoDiffScalar<DerType>, RowsAtCompileTime, ColsAtCompileTime,
         Options, MaxRowsAtCompileTime, MaxColsAtCompileTime>>& matrix) {
   return matrix
       .unaryExpr([](const typename Eigen::AutoDiffScalar<DerType>& value) {
         return ExtractDoubleOrThrow(value);
       })
       .eval();
 }
```
___
*[common/extract_double.h, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmZ90BAQD8mFpptsYV:-MfmZ90BAQD8mFpptsYW:b-i4rxh4) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/extract_double.h#L46)):*
> ```objc
>     std::is_same_v<typename Derived::Scalar, double>,
>     Eigen::Matrix<double, Derived::RowsAtCompileTime,
>                   Derived::ColsAtCompileTime, 0, Derived::MaxRowsAtCompileTime,
> ```

nit, `0 => Derived::Options`
___
*[common/symbolic_expression.h, line 1488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmZFoi6nSp_97Q2FbL:-MfmZFoi6nSp_97Q2FbM:bt2tk1c) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/symbolic_expression.h#L1488)):*
> ```objc
>     std::is_same_v<typename Derived::Scalar, symbolic::Expression>,
>     Eigen::Matrix<double, Derived::RowsAtCompileTime,
>                   Derived::ColsAtCompileTime, 0, Derived::MaxRowsAtCompileTime,
> ```

nit, `0 => Derived::Options`

I will take care of the other occurrences in this file in another PR.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @soonho-tri)

___
*[common/autodiff_overloads.h, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmXpvO0iFrhUXjWJOP:-MfmawcL9P3ztaFz6dR7:b-7piamb) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/autodiff_overloads.h#L166)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, 

1) We can also add `int Options` as template parameter.
2) Using `auto` in return-type makes it easier to read?

```c++
 template <typename DerType, int RowsAtCompileTime, int ColsAtCompileTime,
          int Options, int MaxRowsAtCompileTime, int MaxColsAtCompileTime>
 auto ExtractDoubleOrThrow(
     const Eigen::MatrixBase<Eigen::Matrix<
         Eigen::AutoDiffScalar<DerType>, RowsAtCompileTime, ColsAtCompileTime,
         Options, MaxRowsAtCompileTime, MaxColsAtCompileTime>>& matrix) {
   return matrix
       .unaryExpr([](const typename Eigen::AutoDiffScalar<DerType>& value) {
         return ExtractDoubleOrThrow(value);
       })
       .eval();
 }
```
</blockquote></details>

Done.  Good call.  I had an intermediate enable_if that (I believe) precluded my use of auto, but it's available again now!
___
*[common/extract_double.h, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmZ90BAQD8mFpptsYV:-MfmbEeW8ghnJQV_qY9w:bm425h4) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/extract_double.h#L46)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `0 => Derived::Options`
</blockquote></details>

Done.  (Here is a case where I couldn't use auto, i think).
___
*[common/symbolic_expression.h, line 1488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MfmZFoi6nSp_97Q2FbL:-MfmbPOsDpvl-TEo0aAr:b-l5r1db) ([raw file](https://github.com/robotlocomotion/drake/blob/b1710e33857f8f5381f3dbaabea1488f9743c152/common/symbolic_expression.h#L1488)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `0 => Derived::Options`

I will take care of the other occurrences in this file in another PR.
</blockquote></details>

Done.  Thanks!

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15518#-:-MfnhJoC9vDKo0b8n40O:b-vtj4w1)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
___
*[common/extract_double.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15518#-MkNCbQ568MqgghCjHhi:-MkNCbQ568MqgghCjHhj:b-hlcgqd) ([raw file](https://github.com/robotlocomotion/drake/blob/539772ac41aa42c77dafe8be38766231ceb0b267/common/extract_double.h#L26)):*
> ```objc
> /// See symbolic_expression.h to use this with symbolic::Expression.
> template <typename T>
> DRAKE_DEPRECATED("2020-08-01",
> ```

FYI This date was wrong; now fixed in #15809.

**Pull request merged**
