### PR TITLE
Updated Style Guide to Allow #pragma once

### PR DESCRIPTION
**Pull request by liangfok**
This resolves https://github.com/RobotLocomotion/drake/issues/2104

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2120) &emsp; Multiple assignees:&emsp;@RussTedrake&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/RussTedrake">RussTedrake</a>,&emsp;@david-german-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/david-german-tri">david-german-tri</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri +@jwnimmer-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2120#-:-KFiMM9fRcMvmFBK12aT:-329503185)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2120#-:-KFilUaNijekaEy4MDUa:1417088721)*

**Comment by jwnimmer-tri** [comment]
... with the obvious caveat that the documentation is confusing now, because it disagrees with the code.  We should have a PR in the wings to switch to pragma-once ready to merge, before we push the green button on this one.

**Comment by liangfok** [comment]
Anyone know of a good tool that can make the change across every header file in Drake in one go?

**Comment by jwnimmer-tri** [comment]
I would usually do it using perl (or possibly python, depending on how complex it became).

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2120#-:-KFj-lq6RED6_yjvYK-T:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/2120#-KFj1IxnZzXUne3Q-cFy:-KFj1IxnZzXUne3Q-cFz:-984191903) (no related file):*
+@russtedrake 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2120)*

**Comment by jwnimmer-tri** [comment]
I've opened #2104 again for the actual work of switching to use pragma-once.

**Comment by liangfok** [comment]
@jwnimmer-tri, now that https://github.com/RobotLocomotion/drake/pull/2125 is merged, I believe this PR can be merged too.

**Comment by jwnimmer-tri** [comment]
This is a documentation-only change, for which CI will not tell us anything useful.  The current CI is still in-progress, while the prior one failed on windows for what looks like a flake.  I'm going to override-merge this one now anyway.

**Pull request merged**
