### PR TITLE
Remove PODS RPATH stuff

### LINKED ISSUE #2482: Replace PODs with conventional CMake workflow
Note: This is an epic on our [ZenHub](https://www.zenhub.io) board. Please do not remove or rename the [Epic](https://github.com/RobotLocomotion/drake/labels/Epic) label.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove broken PODS logic to "abuse RPATH". This is trying to do the same thing as 2a0a566694cb, and is thus no longer needed, but was treating `CMAKE_INSTALL_RPATH` as a `:`-separated list (which it isn't), which resulted in a corrupt RPATH entry that was breaking the install (by producing binaries that newly don't run due to missing libraries) on at least macOS.

Fixes #2482.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4902)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/pods.cmake, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4902#-KbL1p7lcwWrpSsC9ycj:-KbL1p7lcwWrpSsC9yck:bjzdyvw) ([raw file](https://github.com/robotlocomotion/drake/blob/38f4845873e7417d892c0e128dd64df15dcf0a20/cmake/pods.cmake#L30)):*
> ```CMake
> 
>       # for OS X, which uses "install name" path rather than rpath
>       set(CMAKE_INSTALL_NAME_DIR ${CMAKE_INSTALL_RPATH})
> ```

I have a feeling that you will need this still, but I may be wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4902)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/pods.cmake, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4902#-KbL1p7lcwWrpSsC9ycj:-KbL2LGOgbrO2bbxZj_M:bom8ike) ([raw file](https://github.com/robotlocomotion/drake/blob/38f4845873e7417d892c0e128dd64df15dcf0a20/cmake/pods.cmake#L30)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I have a feeling that you will need this still, but I may be wrong.
</blockquote></details>

I have a feeling you may be right :smile:, but I want to see what happens without it, first... if it (still) breaks, I'll twiddle the branch to keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4902)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please

**Comment by david-german-tri** [comment]
:lgtm: if CI approves

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4902#-:-KbL94cVSmCn2arnVdkI:b-i4fjf8)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4902#-:-KbLO6oVC-hT_GB_o5jW:bnfp4nl)*

**Pull request merged**
