### PR TITLE
Add a light-weight test version of contact model example

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This assures that the example will get routinely exercised to confirm that
it doesn't fall out of sync with the rest of drake.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5400)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@liangfok for feature review (nice reality check)  +@david-german-tri for platform review because he's bored.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeLG1iZy-c7nSWkVSrX:b-ul8gkn)*

**Comment by david-german-tri** [comment]
C'mon, I didn't say I was bored, I said my other work was temporarily blocked.  Nonetheless, I'll review this for you because I'm nice like that.  :lgtm: but the race is on, see below.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/contact_model/BUILD, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-KeLRljuATSVSdfpM8dp:-KeLRljuATSVSdfpM8dq:b92tsj1) ([raw file](https://github.com/robotlocomotion/drake/blob/8b7342d2a52ee2dc3944928efe04c111c059a26c/drake/examples/contact_model/BUILD#L32)):*
> ```Python
> sh_test(
>     name = "sliding_bricks_test",
>     srcs = ["//tools:exec.sh"],
> ```

BTW, I think this pattern is wrong; @jwnimmer-tri and I are reopening #5238 to remove it.  However, if you merge this before we delete `exec.sh`, you win and we'll fix it for you.

---

*[drake/examples/contact_model/sliding_bricks.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-KeLS7AflK2cj1uXvNhd:-KeLS7AflK2cj1uXvNhe:bq7ji3r) ([raw file](https://github.com/robotlocomotion/drake/blob/8b7342d2a52ee2dc3944928efe04c111c059a26c/drake/examples/contact_model/sliding_bricks.cc#L47)):*
> ```cpp
> DEFINE_double(dissipation, 1.0, "The contact model's dissipation");
> DEFINE_double(sim_duration, 3, "The simulation duration");
> DEFINE_bool(no_playback, false, "Set to false to avoid looping playback");
> ```

BTW, I'd advise against negative-phrased boolean flags - that tends to be a road to a confusing place.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeLQqq2u3VuI-N3RNhV:b-sljdzf)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeLYgpvPUy055S3q1mb:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Updated; waiting on CI.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/contact_model/BUILD, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-KeLRljuATSVSdfpM8dp:-KeZM1Z62bVre5ALQoTd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8b7342d2a52ee2dc3944928efe04c111c059a26c/drake/examples/contact_model/BUILD#L32)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I think this pattern is wrong; @jwnimmer-tri and I are reopening #5238 to remove it.  However, if you merge this before we delete `exec.sh`, you win and we'll fix it for you.
</blockquote></details>

Done

---

*[drake/examples/contact_model/sliding_bricks.cc, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-KeLS7AflK2cj1uXvNhd:-KeLUtw6QsI6CRYdoV0n:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/8b7342d2a52ee2dc3944928efe04c111c059a26c/drake/examples/contact_model/sliding_bricks.cc#L47)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I'd advise against negative-phrased boolean flags - that tends to be a road to a confusing place.  
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeZMDivPxrgD39yXc5S:b-gr34p7)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeZOoiqzrBHYQH9U4sj:b-s794vx)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeZPB9AxY3AJf7J9mIj:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400)*

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400)*

**Comment by SeanCurtis-TRI** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5400#-:-KeZX_eX-qd4DntIBiCx:b-l70wzf)*

**Pull request merged**
