### PR TITLE
[py solvers] Fix branch and bound test vs solution ordering

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
On Mac Ventura Arm, this was [spuriously failing](https://drake-cdash.csail.mit.edu/test/1051758745).  Towards #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19403)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@AlexandreAmice for feature review, please.  \CC @hongkai-dai FYI.

Note that the CI failure in `mac-arm-ventura-clang-bazel-experimental-release` doesn't indicate problem with this PR.  The test case changed in this PR is passing in that build.  It shows that other test cases are still failing as we work to spin up Ventura.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19403)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @AlexandreAmice and @jwnimmer-tri)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19403#-:-NVG7nVz174UETqKktUm:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

Note that the CI failure in `mac-arm-ventura-clang-bazel-experimental-release` doesn't indicate problem with this PR.  The test case changed in this PR is passing in that build.  It shows that other test cases are still failing as we work to spin up Ventura.

**Pull request merged**
