### PR TITLE
Better schunk models in manipulation station

### PR DESCRIPTION
**Pull request by hjsuh94**
A fix to #13875 , adds two more realistic looking Schunk grippers for better visualization (+ perhaps some improvements to modeling collision geometry for the real schunk) 

The first model consists of real-looking schunk without the fingertip. 
Screenshot from 2020-08-22 22-52-40

The second model includes fingertip with some collision spheres.
Screenshot from 2020-08-22 23-09-06

Includes changes to manipulation_station, its bindings, and end_effector_teleop codes so that different schunks can be called at runtime. 

`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=box_schunk`
`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=real_schunk_no_tip`
`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=real_schunk_with_tip`

Same function is added to `end_effector_teleop_sliders.py` and `end_effector_teleop_dualshock4.py`
Available for manipulation class and clutter clearing setups, not available for planar iiwa. 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13922)

### CODE REVIEW

**Comment by hjsuh94** [comment]
@RussTedrake  I'm not sure who I should ask for code review, but the feature is here if you need better visualization - I would appreciate some feature-level feedback.

**Comment by RussTedrake** [comment]
+@russtedrake for feature review

**Comment by RussTedrake** [comment]
@seancurtis-tri -- I considered that, but actually our docs say "If your model’s files are small enough (<100KB in a given directory), then you may add them directly to Git in a PR to master."  https://drake.mit.edu/model_version_control.html?highlight=models

these are less that 40kb each.  no?

**Comment by RussTedrake** [comment]
oh.  perhaps the directory adds up to just barely over 100KB.  wow.. it's close.

**Comment by hjsuh94** [comment]
I wanted to follow up on what the next step is - personally I feel like the files are small enough to keep them in this PR (the newly committed files are 104.8kB in total, I can try to bring the number down further).

Perhaps I can submit a separate issue for cleaning the directory after merging this PR? The other three mesh files are much less 'efficient' than the new mesh files, and is being used for what seems like an outdated urdf file. But I'm not sure if I should edit those files since I'm not sure who is using them. 

If @SeanCurtis-TRI says it should go into the models repo, then I can PR the obj files to the models repo and keep the rest of the PR as is.

**Comment by sammy-tri** [comment]
https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/wsg_50_description/README.md says: "WARNING All of the *.urdf models and *.obj meshes in this package are deprecated and will be removed on 2020-11-01."

I woudn't worry about the contributions of the existing files since they're going away anyways.

**Comment by RussTedrake** [comment]
@sammy-tri -- i'm confused.  what was the plan for replacing those models if they were to be deleted?

**Comment by hjsuh94** [comment]
this is interesting - the urdf model had a more realistic mesh from the ROS package with a 'real' collision geometry. 

I wouldn't say the existing sdf files replace the urdf files, since the sdf files were based on primitive geometries, but this PR should be a true replacement.

**Comment by jwnimmer-tri** [comment]
> ... README.md says: "WARNING ...

As of this PR now, that README is overly broad in its claim of deprecation (the new stuff isn't deprecated).  This PR should amend the README to clarify that.

> ... the newly committed files are 104.8kB in total, I can try to bring the number down further ...

Trying to barely sqeak in under the 100kB limit isn't the right game to play.  It leaves no room for evolution when we need a third new fingtertip variant, etc.  The intention of allowing _some_ objs directly into Drake git is to be used for things like `box.obj` for unit tests with only a few vertices, or other similarly unremarkable data.  The purpose of the size restriction is so that `git clone` doesn't grow crazy large.  Even if we add the objs now and then delete them right after, they are forevermore part of the clone.

For things like gripper meshes, which are large-ish and will change or grow new variations over time thus accumulating in the clone, it's often smartest to just place them into `models` from the get-go.  It might be possible to squash the meshes down to maybe 50 KiB total in which case they are unobjectionable per the guidelines, but just doing the `models` PR is only a few minutes.

If we like these new model in general, then those of us who have done `models` PRs in the past can help guide this one.

**Comment by jwnimmer-tri** [comment]
Oops, of course the very next email was the RobotLocomotion/models#13 with the meshes.  As part of reviewing that PR, we'd like to see this PR rebased against the new meshes git sha in `drake/tools/workspace/meshes/...` to prove that the meshes PRs is satisfactory for use here.

**Comment by hjsuh94** [comment]
While we still wait for https://github.com/RobotLocomotion/models/pull/13 (might take a while due to licensing issues), I have made the following updates to the Drake PR. 

1. As @jwnimmer-tri suggested, the `README.md` is updated to clarify which files are being deprecated (urdf ones) and which ones are not. 
2. As suggested [here](https://drake.mit.edu/model_version_control.html?highlight=models), `drake/tools/workspace/models/repository.bzl` has been modified to point to the PR commit in https://github.com/RobotLocomotion/models/pull/13, and the other files (`files.bzl`, `package.BUILD.bazel`, `forward_files`) were accordingly changed. 
3. As suggested in the guidelines, I've added a unittest `manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_collision_test.cc` to check if MBPs can be built successfully out of the sdfs.

**Comment by hjsuh94** [comment]
@amcastro-tri Thank you for the review! It's a good point and I will reverify the numbers on the inertias - some of them are likely wrong. 

On the rest of the comments, I based the new files (`schunk_wsg_50_no_tip.sdf` and `schunk_wsg_50_with_tip.sdf`) on the old sdf file that we've been using for a while (`manipulation/models/wsg_50_description/sdf/schunk_wsg_50.sdf`), which also contains the exact same lines you are referring to. I don't have good answers to how the numbers were set or if the lines are necessary / parsed by Drake.

I think if we're removing these lines from the new files, then we should also remove the lines from the old files. But I'm not sure if cleaning the original SDF is within the scope of this PR.

**Comment by jwnimmer-tri** [comment]
The https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/wsg_50_description/LICENSE.TXT says that we copied the files from a different repository.

**Comment by hjsuh94** [comment]
The `*urdf` files and the `*obj` meshes are from another repository, but on the `*sdf` file it says: 

https://github.com/RobotLocomotion/drake/blob/5642ccd38c73a5ba848a4769693de827364c1790/manipulation/models/wsg_50_description/LICENSE.TXT#L12-L13

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13922#-MFf66XHDxIXfniep2m1:-MFmf0uA0WzclqetFn_W:b-8c2txu) (no related file):*
The reply was misfiled in Reviewable.  Here it is for the record:

> @amcastro-tri Thank you for the review! It's a good point and I will reverify the numbers on the inertias - some of them are likely wrong.
>
> On the rest of the comments, I based the new files (schunk_wsg_50_no_tip.sdf and schunk_wsg_50_with_tip.sdf) on the old sdf file that we've been using for a while (manipulation/models/wsg_50_description/sdf/schunk_wsg_50.sdf), which also contains the exact same lines you are referring to. I don't have good answers to how the numbers were set or if the lines are necessary / parsed by Drake.
>
> I think if we're removing these lines from the new files, then we should also remove the lines from the old files. But I'm not sure if cleaning the original SDF is within the scope of this PR.

---

**Pull request merged**
