### PR TITLE
Import matlab_pods.cmake, pods.cmake, procman.cmake

### PR DESCRIPTION
**Pull request by jamiesnape**
I am going to have fix some compiler flags in pods.cmake for #3154 so this makes it easier. Also importing  matlab_pods.cmake and procman.cmake so we can remove the dependency on the cmake repo once FindMatlab.cmake is upstreamed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3190)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-please
@drake-jenkins-bot mac-clang-ninja-experimental-please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review, @david-german-tri for platform review.

**Comment by mwoehlke-kitware** [comment]
It seems like you've imported most of RobotLocomotion/cmake. Should we go ahead and remove that as an external?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPYuqNetaBqFEt6wEdN:b-l7ahef)*

**Comment by jamiesnape** [comment]
I would need to import FindMatlab. Where should that go for now.

**Comment by mwoehlke-kitware** [comment]
> I would need to import FindMatlab. Where should that go for now?

Ah, right... https://gitlab.kitware.com/cmake/cmake/merge_requests? :wink:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPYwPymqaFV00q4hb0i:b-dukqy5)*

**Comment by david-german-tri** [comment]
There are some diffs in `pods.cmake`, but it looks to all be Cygwin related.  Is that right?  If so, :lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPYzPsgoG3QJ-uogDlU:b-bx6wcx)*

**Comment by jamiesnape** [comment]
I am guessing you diff-ed against the HEAD of that repo? We are referencing a previous commit for some reason, so this pods.cmake is a copy of that.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPZ0S4MSrINNcsHdZcn:bu5ul4f)*

**Comment by mwoehlke-kitware** [comment]
I see only whitespace changes, so :lgtm:

(Note: I copied my local copies of `drake/cmake/<files...>` into `cmake/` after checking out the branch and looked at the changes; `git diff -w` said there were none, so...)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPZ1c8stY_k_eyVeAdq:b-42folm)*

**Comment by david-german-tri** [comment]
Oh, I see.  Too bad that we're forking before https://github.com/RobotLocomotion/cmake/commit/6c15efb06bee6804a3552b85aa82b809c753f7e5, but :lgtm: regardless; I don't want to block you on it.

@jonathan-owens FYI

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3190#-:-KPZ2banWZan-RSAnPqx:bpl0av4)*

**Comment by jamiesnape** [comment]
Looks like that commit broke something as the reference changed to that SHA and then back to the current one.

**Comment by jonathan-owens** [comment]
Yes, I was a little over-zealous with some of my pruning and it wrecked everything, which is why it was reverted.

**Pull request merged**
