### PR TITLE
[install] Deprecate drake_bazel_installed support

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This downstream use of Drake binaries via Bazel is characterized by a line like this in your `WORKSPACE` file:

```bzl
load("@drake_binary//:share/drake/repo.bzl", "drake_repository")
```

Companion PR: https://github.com/RobotLocomotion/drake-external-examples/pull/286.

Towards #21054.

I'm marking "breaking change" because the lack of CI probably means this will bitrot at some point, and we really want to flag users to deal with that hazard ASAP.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21057)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for high-level feature sign-off, please.

As far as I can tell, you're no longer using this machinery in any of your course notes.  Is that correct?

**Comment by RussTedrake** [comment]
Whenever i'm actively developing a feature in Drake which I test in my notes, I do currently use
```
bazel build $OPTIONS //tools/install/libdrake:libdrake.so //bindings/pydrake
rm -rf $DRAKE_INSTALL_DIR
bazel run $OPTIONS //:install $DRAKE_INSTALL_DIR
```
and point my virtualenv at the DRAKE_INSTALL_DIR.  I thought that the cmake install workflow called this? Is that now going away?

**Comment by jwnimmer-tri** [comment]
That's still fine.  What this is removing is a `WORKSPACE` file that looks like this:

```
# Load and run the repository rule that knows how to provide the @drake
# repository based on a Drake binary release.
load("@drake_artifacts//:share/drake/repo.bzl", "drake_repository")

drake_repository(name = "drake")
```

In other words, using a Drake binary release in Bazel via repository rules.  Anything using pip / venv / cmake is unaffected.

**Review by RussTedrake — COMMENTED** [review]
In that case, it's aok for me.  Signing off on the high level.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21057#-:-NrhZYK08Wz0CAnMXvPt:b2iwjha)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
FYI I got some feedback in slack.  I'm going to try one more thing in drake-external-examples before I rip off this band-aid.

**Comment by jwnimmer-tri** [comment]
FYI for those following along -- the https://github.com/RobotLocomotion/drake-external-examples/pull/286 will be the new recommendation (however it turns out after code review finishes, and it merges).

**Review by RussTedrake — COMMENTED** [review]
-@RussTedrake for the remainder.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21057#-:-NsGbTm3A4-sJ-TNrejO:b46db7y)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 16 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21057)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21057#-:-NsK2n0p5cadX6BU0ZjI:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
