### PR TITLE
Updates documentation generation instructions.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4984)

### CODE REVIEW

**Comment by liangfok** [comment]
+@lucy-tri for feature review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-:-KbpU7mAcYJHSz8VVwn3:b-kykn05)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-Kbp_Zb-mxRnxFuqMCs7:-Kbp_Zb-mxRnxFuqMCs8:bb7noei) ([raw file](https://github.com/robotlocomotion/drake/blob/5436ebf81cc46b632050b6f316746f22d27bc8d5/drake/doc/documentation_instructions.rst#L19)):*
> ```reStructuredText
> 
> Drake's documentation is built using the ``documentation`` build target. First
> build Drake like normal, otherwise the ``documentation`` build target will not
> ```

Your change is covered by the Note at the top, so is not needed. However, apparently you didn't notice the note. How about moving it to just above this paragraph?  I think it works better there. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-Kbp_Zb-mxRnxFuqMCs7:-KbpbTiERpGiqlJpU9Kh:b-ttuuzf) ([raw file](https://github.com/robotlocomotion/drake/blob/5436ebf81cc46b632050b6f316746f22d27bc8d5/drake/doc/documentation_instructions.rst#L19)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary><blockquote>

Your change is covered by the Note at the top, so is not needed. However, apparently you didn't notice the note. How about moving it to just above this paragraph?  I think it works better there. 
</blockquote></details>

Ah. Good point! Done. I moved the note to be in the first paragraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-:-Kbpn8nsVg4-1AHKUxvd:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. +@jwnimmer-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-:-Kbpo8V6ImCxduhD2OeH:b-okxbfq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

This is fine.  It will get 10x simpler in the Bazel port, but might as well document the current state for now.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4984#-:-Kbq4RQeTCFb214QjqbU:b8494w9)*

**Pull request merged**
