### PR TITLE
Provide Google Test comparators for Maliput and Ignition types

### PR DESCRIPTION
**Pull request by agalbachicar**
This PR includes Google Test [idioms](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#using-a-function-that-returns-an-assertionresult) to compare Maliput's types. It also adds one function to compare Ignition's Vector3d type. In addition, `drake/automotive/maliput/monolane/test/monolane_test_utils.h` file is removed in favor of these new functions.

Tests from Dragway, Monolane and RNDF have been refactored so as to use the new functions.

Functionality was proposed in #6349, this [comment](https://github.com/RobotLocomotion/drake/pull/6349#issuecomment-312285133).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6506)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@maddog-tri +@jwnimmer-tri for feature review please.

**Comment by jwnimmer-tri** [comment]
@maddog-tri Let me know if you can handle this one on your own; otherwise let me know what fraction (or all) that I should look at.

**Comment by maddog-tri** [comment]
@jwnimmer-tri : I've got this (hold my beer...).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KoOfoeqCvFJgar6I2zx:bm3q5mj)*

**Comment by maddog-tri** [comment]
The random whitespace/indent changes sprinkled everywhere are _really_ annoying to this reviewer.  They distract from the substantive changes that need review,  and just about all of them yield a worse code layout than the original.

Review pass complete; please take a look.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP1dXCjipPFqpj0OCq:-KoP1dXCjipPFqpj0OCr:bz76kg7) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L1)):*
> ```objc
> #pragma once
> ```

META:  Function implementations should be moved to a corresponding `.cc` file.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP7mfaV4YVRqKEVEwK:-KoP7mfbfHLtmUzuj-TQ:b1icnty) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L13)):*
> ```objc
> namespace maliput {
> namespace api {
> ```

These test predicates belong in a `test` namespace (i.e., `drake::maliput::api::test`).

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOnJxQuWOxwbppxheN:-KoOmOrikcFKRf35UnWz:bgpraa) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L14)):*
> ```objc
> namespace api {
> 
> // Compares equality within @p tolerance deviation of two GeoPositions objects.
> ```

Typo:  extraneous `s` on `GeoPositions`.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOla1JbYE1lJn873ZW:-KoOla1KjlWqrRc61QTE:bkxcq8a) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L17)):*
> ```objc
> // @param pos1 A GeoPosition object to compare.
> // @param pos2 A GeoPosition object to compare.
> // @param tolerance An allowable deviation for each GeoPosition's coordinate.
> ```

META:  Should document that this is an absolute tolerance (as opposed to a relative tolerance).

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOncsWIkSKNWeOeZm3:-KoOncsWIkSKNWeOeZm4:b66vs7j) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L19)):*
> ```objc
> // @param tolerance An allowable deviation for each GeoPosition's coordinate.
> // @return ::testing::AssertionFailure() When GeoPosition objects are different.
> // @return ::testing::AssertionSuccess() When GeoPosition objects are equal or
> ```

Extraneous text: "equal or" is subsumed by "within the tolerance deviation" (so having it called out specifically is a confusing).

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOj2YN0NxDOIZc3NlQ:-KoOj2YO96WvMMPksc2_:bf2b19b) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L21)):*
> ```objc
> // @return ::testing::AssertionSuccess() When GeoPosition objects are equal or
> // within the @p tolerance deviation.
> ::testing::AssertionResult CompareGeoPositions(const GeoPosition& pos1,
> ```

META:  The names of these comparison functions should identify the assertion they are making.  Suggestions: `IsGeoPositionClose()`, `IsRotationClose()`, `IsRBoundsClose()`, etc.

There is nothing specific in the style guide about this, but this is the style used in the gtest documentation.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOoMuy5R3jqFYwea8g:-KoOoMuy5R3jqFYwea8h:bqwjd6f) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L23)):*
> ```objc
> ::testing::AssertionResult CompareGeoPositions(const GeoPosition& pos1,
>                                                const GeoPosition& pos2,
>                                                double tolerance = 0.0) {
> ```

META:  No default values, please!  It makes code less clear at the call site, and more difficult to refactor later on.  (Also, `0.0` is almost always the wrong value anyhow.)

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOkXvemdjtjBBNL4QG:-KoOkXvfeyGg-XnEMhsg:b-h67m8a) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L26)):*
> ```objc
>   double delta = std::abs(pos1.x() - pos2.x());
>   if (delta > tolerance) {
>     return ::testing::AssertionFailure()
> ```

META:  The comparison should not short-circuit at the first failure.  All components should be inspected, and all failed comparisons should be collected and reported together.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOn4pCZ4-ZbTewu9zD:-KoOn4pCZ4-ZbTewu9zE:b-stxrfx) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L51)):*
> ```objc
>                                        << pos1
>                                        << "\nis approximately equal to pos2 =\n"
>                                        << pos2;
> ```

META:  `tolerance` should be emitted, too (since the purpose of this is to provide diagnostics for the `EXPECT_FALSE(...)` usage).

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP3xZK8C2Kj9LiXI6W:-KoP3xZLiNWY_J_wOxtp:b-4fpewl) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L96)):*
> ```objc
> 
> // Compares equality within @p tolerance deviation of two Rotation objects.
> // Comparison will evaluate the inner Rotation's Quaternion.
> ```

Simply comparing the quaternions component-wise is not necessarily the best way to test "IsRotationClose()" in general. One reason is that quaternions are a double-cover of SO(3), so `-q` represents the same rotation at `q`.  Another reason is that `tolerance` doesn't have a simple-for-humans geometrical meaning in terms of quaternion components.

The original comparisons that this is replacing were on Roll/Pitch/Yaw angles; it would probably be better to just stick to that for now (i.e., a drop-in replacement).

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOr2lY0uVFv1qwx1uD:-KoOr2lZRXIfzejyzZDr:b78ioj6) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L150)):*
> ```objc
> // @param rbounds1 A RBounds object to compare.
> // @param rbounds2 A RBounds object to compare.
> // @param tolerance An allowable deviation for each IsoLaneVelocity's
> ```

Typo:  "IsoLaneVelocity's" ???

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOrAsmHqHH-YTth93A:-KoOrAsnk7RZwvbb7_rt:b-vuf5wo) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L185)):*
> ```objc
> // @param hbounds1 A HBounds object to compare.
> // @param hbounds1 A HBounds object to compare.
> // @param tolerance An allowable deviation for each IsoLaneVelocity's
> ```

Typo:  "IsoLaneVelocity's" ???

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP15vrNB9jqDZ2qLmC:-KoP15vrNB9jqDZ2qLmD:bq3oft8) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/rndf/test/ignition_types_compare.h#L11)):*
> ```objc
> namespace maliput {
> namespace rndf {
> ```

("META" comments from `maliput_types_compare.h` apply to this file, too.)

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP88TrLnh2lf8LqfMt:-KoP88TsACmyJ_JGCZy3:b-wshyw) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/rndf/test/ignition_types_compare.h#L11)):*
> ```objc
> namespace maliput {
> namespace rndf {
> ```

These test predicates belong in a `test` namespace (i.e., `drake::maliput::rndf::test`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KoPqvOrbRkM375fHETD:b6lcmkp)*

**Comment by agalbachicar** [comment]
Comments were addressed. Sorry for the whitespace/indent changes, I've run clang-format to check/correct styling and all those changes were introduced.

---

Review status: 3 of 13 files reviewed at latest revision, 14 unresolved discussions.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP1dXCjipPFqpj0OCq:-KoSWme9RH2qaFDQEfWS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L1)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  Function implementations should be moved to a corresponding `.cc` file.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP7mfaV4YVRqKEVEwK:-KoSWo9Cygi60uVGQkDk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L13)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

These test predicates belong in a `test` namespace (i.e., `drake::maliput::api::test`).
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOnJxQuWOxwbppxheN:-KoSWxOxk35ThMiomKdC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L14)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Typo:  extraneous `s` on `GeoPositions`.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOla1JbYE1lJn873ZW:-KoSX5snRTTd69dIM7S0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L17)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  Should document that this is an absolute tolerance (as opposed to a relative tolerance).
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOncsWIkSKNWeOeZm3:-KoSXOUdNcqztv-_6-y4:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L19)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Extraneous text: "equal or" is subsumed by "within the tolerance deviation" (so having it called out specifically is a confusing).
</blockquote></details>

Done. Removed.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOj2YN0NxDOIZc3NlQ:-KoSZg-iQiiiIiztU0RC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L21)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  The names of these comparison functions should identify the assertion they are making.  Suggestions: `IsGeoPositionClose()`, `IsRotationClose()`, `IsRBoundsClose()`, etc.

There is nothing specific in the style guide about this, but this is the style used in the gtest documentation.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOoMuy5R3jqFYwea8g:-KoSc-PboR6vQA5ITlPp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L23)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  No default values, please!  It makes code less clear at the call site, and more difficult to refactor later on.  (Also, `0.0` is almost always the wrong value anyhow.)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOkXvemdjtjBBNL4QG:-KoTKTlP-lMaArbNsB0l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L26)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  The comparison should not short-circuit at the first failure.  All components should be inspected, and all failed comparisons should be collected and reported together.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOn4pCZ4-ZbTewu9zD:-KoSd8zCAtlwZu1RzCOb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L51)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

META:  `tolerance` should be emitted, too (since the purpose of this is to provide diagnostics for the `EXPECT_FALSE(...)` usage).
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP3xZK8C2Kj9LiXI6W:-KoSf1rvGnqZOzoNGXE6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L96)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Simply comparing the quaternions component-wise is not necessarily the best way to test "IsRotationClose()" in general. One reason is that quaternions are a double-cover of SO(3), so `-q` represents the same rotation at `q`.  Another reason is that `tolerance` doesn't have a simple-for-humans geometrical meaning in terms of quaternion components.

The original comparisons that this is replacing were on Roll/Pitch/Yaw angles; it would probably be better to just stick to that for now (i.e., a drop-in replacement).
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOr2lY0uVFv1qwx1uD:-KoSf6H4-mawd4cti4jI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L150)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Typo:  "IsoLaneVelocity's" ???
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 185 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoOrAsmHqHH-YTth93A:-KoSfDcTZ5H6F9HtKhKN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/api/test/maliput_types_compare.h#L185)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Typo:  "IsoLaneVelocity's" ???
</blockquote></details>

Done.

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP15vrNB9jqDZ2qLmC:-KoTMV4xUo38NfjnYm13:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/rndf/test/ignition_types_compare.h#L11)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

("META" comments from `maliput_types_compare.h` apply to this file, too.)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KoP88TrLnh2lf8LqfMt:-KoStkNPoP7TD2XdSsGR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/427cc6b2aa78cb0b0eb3544d29469ab68e918a4b/drake/automotive/maliput/rndf/test/ignition_types_compare.h#L11)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

These test predicates belong in a `test` namespace (i.e., `drake::maliput::rndf::test`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-Koh9EPbIA_UdYxdR0pJ:b-ha5t9q)*

**Comment by agalbachicar** [comment]
FYI, just added a change in libraries dependencies based on #6538 .

**Comment by maddog-tri** [comment]
:lgtm: -- A couple of spelling errors and misplaced includes, but otherwise ready for platform review.

Thank you for reverting the whitespace changes; the platform reviewer will surely appreciate it, too.  In the future: with a modern clang-format install, you can do something like `git clang-format ...` to clang-format only the lines which have already been modified in a branch/diff/etc.

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KonBTDU3ybBeD9oKi6N:-KonBTDU3ybBeD9oKi6O:bmgrpqe) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.cc#L4)):*
> ```cpp
> #include <string>
> 
> #include "drake/automotive/maliput/api/test/maliput_types_compare.h"
> ```

Belongs at top of its .cc file.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-Kon3SuXsv-_czuPM5zV:-Kon3SuYl-ftRf_oVs4x:b-b3bbx9) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.h#L33)):*
> ```objc
> // @return ::testing::AssertionSuccess() When LanePosition objects are equal or
> // within the @p tolerance deviation.
> ::testing::AssertionResult IsLanePositionsClose(const LanePosition& pos1,
> ```

`IsLanePositionsClose` ---> `IsLanePositionClose` (should be singular)

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-Kon3f53fFYOh_Eo5B3-:-Kon3f53fFYOh_Eo5B30:b4ffa1d) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.h#L46)):*
> ```objc
> // @return ::testing::AssertionSuccess() When Rotation objects are equal or
> // within the @p tolerance deviation.
> ::testing::AssertionResult IsRotationsClose(const Rotation& rot1,
> ```

`IsRotationsClose` ---> `IsRotationClose` (should be singular)

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KonBGpWTNKqZfA01vuZ:-KonBGpXkN79f_nMP7lz:bmgrpqe) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/rndf/test/ignition_types_compare.cc#L4)):*
> ```cpp
> #include <string>
> 
> #include "drake/automotive/maliput/rndf/test/ignition_types_compare.h"
> ```

Belongs at top of its .cc file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KonG3xUpIrh4xljugb2:bskfnji)*

**Comment by sammy-tri** [comment]
+@sammy-tri for platform review by rotation

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KonaQ1DqGIFnROR9386:baowjxg)*

**Comment by agalbachicar** [comment]
Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KonBTDU3ybBeD9oKi6N:-KonWFt_hvQ3RufImVI2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.cc#L4)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Belongs at top of its .cc file.
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-Kon3SuXsv-_czuPM5zV:-KonWmTewNnNQFKWMtXE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.h#L33)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

`IsLanePositionsClose` ---> `IsLanePositionClose` (should be singular)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-Kon3f53fFYOh_Eo5B3-:-KonWz_hgkW9tKQT-9no:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/api/test/maliput_types_compare.h#L46)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

`IsRotationsClose` ---> `IsRotationClose` (should be singular)
</blockquote></details>

Done.

---

*[drake/automotive/maliput/rndf/test/ignition_types_compare.cc, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KonBGpWTNKqZfA01vuZ:-Kon_Zi2oLCR9xJ_JCQN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/132cf7374c4519af41990027f795484f21a957f0/drake/automotive/maliput/rndf/test/ignition_types_compare.cc#L4)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Belongs at top of its .cc file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506)*

**Comment by agalbachicar** [comment]
Addressed @maddog-tri 's comments. PTAL.

---

Review status: 7 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KooK_lo1yW3sij6zDm6:b-ruyyj7)*

**Comment by maddog-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506)*

**Comment by sammy-tri** [comment]
:lgtm: (with one formatting nitpick)

---

Reviewed 3 of 11 files at r1, 4 of 10 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KorLiYhdMJWcTLrMuRc:-KorLiYip6k1T15HTQ8B:bedzs41) ([raw file](https://github.com/robotlocomotion/drake/blob/5cfe24e5c35e4beaa57da1ba31599d002127d324/drake/automotive/maliput/api/test/maliput_types_compare.h#L47)):*
> ```objc
> // within the @p tolerance deviation.
> ::testing::AssertionResult IsRotationClose(const Rotation& rot1,
>                                             const Rotation& rot2,
> ```

This indentation looks a bit odd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KorNJsxT2ubxiCfkj1r:b-bm0hkh)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506)*

**Comment by agalbachicar** [comment]
Comments were addressed. Thanks for the reviews.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/automotive/maliput/api/test/maliput_types_compare.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-KorLiYhdMJWcTLrMuRc:-KorjYkHyGE5aJTUDqj3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5cfe24e5c35e4beaa57da1ba31599d002127d324/drake/automotive/maliput/api/test/maliput_types_compare.h#L47)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This indentation looks a bit odd.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6506#-:-KortAHf-23oxQM0fYyC:bs8ae77)*

**Pull request merged**
