### PR TITLE
Refactor trajectory optimization by using NVI pattern

### PR DESCRIPTION
**Pull request by soonho-tri**
- `AddRunningCost` methods are public/non-virtual in `DirectTrajectoryOptimization` class.
 - `DoAddRunningCost` methods are private/abstract which should be implemented by a derived class of `DirectTrajectoryOptimization` (such as `DircolTrajectoryOptimization`).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5643)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@russtedrake , platform-review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5643#-:-KgJ3H03H_bdEkwsC8Ep:bzhlren)*

**Comment by RussTedrake** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5643#-KgJLiPkNhCrJQJqVaoR:-KgJLiPkNhCrJQJqVaoS:b-jqetrg) ([raw file](https://github.com/robotlocomotion/drake/blob/e315856c82cfbf8bfc7123f93df24adac21023b7/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L143)):*
> ```objc
>    */
>   virtual void AddRunningCost(
>       std::shared_ptr<solvers::Constraint> constraint) = 0;
> ```

you've forgotten to leave the AddRunningCost(Constraint) version.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5643)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/trajectory_optimization/direct_trajectory_optimization.h, line 143 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5643#-KgJLiPkNhCrJQJqVaoR:-KgJo0xJ2rlE9C7D7NWH:b-ccpi55) ([raw file](https://github.com/robotlocomotion/drake/blob/e315856c82cfbf8bfc7123f93df24adac21023b7/drake/systems/trajectory_optimization/direct_trajectory_optimization.h#L143)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

you've forgotten to leave the AddRunningCost(Constraint) version.  
</blockquote></details>

Done. (added below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5643)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5643#-:-KgK0fv9e0u84Mm0Qfs4:bnfp4nl)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5643#-:-KgLdVLtxW341WEAnbXI:bnfp4nl)*

**Pull request merged**
