### PR TITLE
[hydro] Refine contact surface visualization

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Polish hydro surface visualization

1. Modify control for displaying surface edges
    - width can now be controlled.
2. The intensity map creates its complementary color more generically.
    - Changed the default colors of the intensity map to provide better color contrast.
3. Some function documentation cleaned up.
4. Python-ized Qt slot-signal connection.

Relates #15796

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

Ignore revision 1. It is the contents of #16102 which you've already reviewed. R2 has the new code, I just wanted to get this under review as soon as possible (without cluttering up the previous PR). When #16102 merges, I'll rebase this and those changes will evaporate.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-Moi9o9Y1xNYms8Ah14-:bmq2p4w)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. One potential defect and some questions.

+(status: do not merge) for now. This should be merged after #16102.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-Moj1-Ie0fNXqihJtdN6:b-wnk5f8)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI and @xuchenhan-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 179 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Moj0ebN3s10Zi9y4yeX:-Moj0ebN3s10Zi9y4yeY:b-pfzeff) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L179)):*
> ```Python
>         self.edge_width.value = visualizer.edge_width
>         self.edge_width.minimum = 0
>         self.edge_width.maximum = 10
> ```

I think you may want a setTickInterval(1) here. The current set up doesn't really allow people to slide. 
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 393 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiziHKD7HGSaYwCFvt:-MoiziHKD7HGSaYwCFvu:b-ujkibf) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L393)):*
> ```Python
>     def _do_get_color(self, norm_data):
>         # TODO(drum) Make the color configurable.
>         return self._high_intensity() * norm_data
> ```

FYI, I tested it out and in my personal opinion, the new default color doesn't stand out more. I still go to the flame map if I want to actually see the colors stand out.
Taking a step back, why do we have these different color maps to start with again?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 903 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiwzPU2y0w9UbHR8--:-MoiwzPU2y0w9UbHR8-0:bf87etd) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L903)):*
> ```Python
> 
>         # Connect all of the widgets in the dialog to callbacks
>         self.dlg.color_map_mode.currentIndexChanged.connect(self.set_color_map)
> ```

I'm not getting this syntax here. What's the type of `currentIndexChanged`/`toggled`/`clicked`/etc? Couldn't find these on Qt's doc page. Could you explain or point me to the right reference?
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1032 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoixkBvEUSS13EiGSCJ:-MoixkBvEUSS13EiGSCK:b-w91lu3) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1032)):*
> ```Python
> 
>     def toggle_show_pressure(self, state):
>         """Slot for dialog widget"""
> ```

nit, These repeated docs don't make much sense to me. I understand these methods as callbacks to when users interact with the widgets. How are they "slots"?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-MojIVQXAaWw5AcseCJ0:bu9a4i4)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 179 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Moj0ebN3s10Zi9y4yeX:-Moj5l9NCtF13-gX80ha:b-c3lfji) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L179)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think you may want a setTickInterval(1) here. The current set up doesn't really allow people to slide. 
</blockquote></details>

I think you're partially right and partially mistaken.

I assume you're referring to the behavior of clicking on the slider *bar* (and not the little knob). As you click on the bar, the handle jumps to one of the two extreme ends (and not where you click). Furthermore, the edge width value doesn't update to reflect even that obnoxious behavior.

*Partial* solutions:
    - Set the "page step" so the handle jumps one space (instead of to the end).
    - Connect the `valueChanged` and not `sliderMoved` signal to the edge width behavior.
    - Add a tool tip indicating that left/right arrow keys allow you to set edge width.

The solution I *wanted* and didn't get:
    - Click on bar, handle moves to mouse.
    - I attempted to apply [this solution](https://stackoverflow.com/questions/11132597/qslider-mouse-direct-jump?rq=1) by introducing a custom slider. However, it failed miserably. Attempts to call the parent's implementation of `styleHint` resulted in summary seg faults.

I went ahead and captured it all so someone can resolve it in the future, if they really care.

(FTR "tick interval" is purely a cosmetic thing. It indicates where ticks on the line would be drawn, if you were drawing them.)
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 393 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiziHKD7HGSaYwCFvt:-Moj48SI9joYFCraWOLQ:bqa4j19) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L393)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, I tested it out and in my personal opinion, the new default color doesn't stand out more. I still go to the flame map if I want to actually see the colors stand out.
Taking a step back, why do we have these different color maps to start with again?
</blockquote></details>

Lots of questions:

1. The old colors were red pressure and blue edges. 
    - Red and blue are *not* compementary colors. Contrast is best achieved when the colors are complementary. 
    - The human vision does its worst job with blue. So, picking a line color that is blue is likewise bad.
    - The complementary color for the old red, would be much closer to green (turquoise, actually), but I try to stay away from red-green schemes so we don't alienate [8% of the male population](https://www.colourblindawareness.org/colour-blindness/#:~:text=Colour%20(color)%20blindness%20(colour,most%20of%20whom%20are%20male.).
    - Orange and teal are classic contrasts (used extensively in film).
    - At the end of the day, I'd argue that the orange-teal combo provides better contrast between pressure and edges than the former.
2. Multiple color maps. A fine question. The answer may be a marvelous opportunity to eliminate code in favor of saying: "you get a single color map." It was done at the time because it wasn't clear what kind of color map would be most appealing/successful. I, likewise, prefer the flame map.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 903 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiwzPU2y0w9UbHR8--:-Moj3tqy0Wv5Ozfp0yqp:b-xudig1) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L903)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not getting this syntax here. What's the type of `currentIndexChanged`/`toggled`/`clicked`/etc? Couldn't find these on Qt's doc page. Could you explain or point me to the right reference?
</blockquote></details>

Those are "signals" in Qt parlance. Connecting signals to slots is how you wire up independent widgets to affect each other (or affect the model). This doesn't represent a change in functionality, merely a nicer spelling for python. It should've been done this way from the beginning.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1032 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoixkBvEUSS13EiGSCJ:-Moj3c1YAlSXy2zHjiWT:bndtzok) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1032)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, These repeated docs don't make much sense to me. I understand these methods as callbacks to when users interact with the widgets. How are they "slots"?
</blockquote></details>

If this were C++ code, they would be decorated with a Qt pre-compiler making them usable as "slots". Qt uses a slot-signal architecture. In the python bindings, the hoops you have to jump through and significantly relaxed, but, as consistent with the Qt design philosophy, I call them "slots" so it's clear they they are intended to be connected to signals.

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not merge) #16102 has merged and this has been rebased.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-MojIwnm8zHV1dcR3dfI:b-heyd8f)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:
+@ericcousineau-tri for hydro visualization platform review encore.

> Reviewed 1 of 1 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-MojMhyR6GXUKSPejxGk:b-ameqh1)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 179 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Moj0ebN3s10Zi9y4yeX:-MojLgF69xizZg_sb_K4:b5ue1kj) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L179)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think you're partially right and partially mistaken.

I assume you're referring to the behavior of clicking on the slider *bar* (and not the little knob). As you click on the bar, the handle jumps to one of the two extreme ends (and not where you click). Furthermore, the edge width value doesn't update to reflect even that obnoxious behavior.

*Partial* solutions:
    - Set the "page step" so the handle jumps one space (instead of to the end).
    - Connect the `valueChanged` and not `sliderMoved` signal to the edge width behavior.
    - Add a tool tip indicating that left/right arrow keys allow you to set edge width.

The solution I *wanted* and didn't get:
    - Click on bar, handle moves to mouse.
    - I attempted to apply [this solution](https://stackoverflow.com/questions/11132597/qslider-mouse-direct-jump?rq=1) by introducing a custom slider. However, it failed miserably. Attempts to call the parent's implementation of `styleHint` resulted in summary seg faults.

I went ahead and captured it all so someone can resolve it in the future, if they really care.

(FTR "tick interval" is purely a cosmetic thing. It indicates where ticks on the line would be drawn, if you were drawing them.)
</blockquote></details>

Hmm, I'm not convinced that the tick interval thing is purely cosmetic. I tried adding setTickInterval() and it does enable changing updating the edge width value.

Anyway, I like this solution too and it alleviates the obnoxious behavior you mentioned. The reference is a plus. Thanks!
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 393 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiziHKD7HGSaYwCFvt:-MojJeQO2zUpnPDS_7LQ:bpexgbb) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L393)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Lots of questions:

1. The old colors were red pressure and blue edges. 
    - Red and blue are *not* compementary colors. Contrast is best achieved when the colors are complementary. 
    - The human vision does its worst job with blue. So, picking a line color that is blue is likewise bad.
    - The complementary color for the old red, would be much closer to green (turquoise, actually), but I try to stay away from red-green schemes so we don't alienate [8% of the male population](https://www.colourblindawareness.org/colour-blindness/#:~:text=Colour%20(color)%20blindness%20(colour,most%20of%20whom%20are%20male.).
    - Orange and teal are classic contrasts (used extensively in film).
    - At the end of the day, I'd argue that the orange-teal combo provides better contrast between pressure and edges than the former.
2. Multiple color maps. A fine question. The answer may be a marvelous opportunity to eliminate code in favor of saying: "you get a single color map." It was done at the time because it wasn't clear what kind of color map would be most appealing/successful. I, likewise, prefer the flame map.
</blockquote></details>

TIL, 8%! That's a lot. For that alone, I'd say this is an improvement :)
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 903 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiwzPU2y0w9UbHR8--:-MojJ6pABvR412Q5FurZ:b-km81rb) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L903)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Those are "signals" in Qt parlance. Connecting signals to slots is how you wire up independent widgets to affect each other (or affect the model). This doesn't represent a change in functionality, merely a nicer spelling for python. It should've been done this way from the beginning.
</blockquote></details>

I see. I'm asking because, unlike the previous iteration, I failed to find the documentation for this syntax.
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 1032 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoixkBvEUSS13EiGSCJ:-MojMQ2iEcdvVMKVnRoO:b-4875hy) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L1032)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

If this were C++ code, they would be decorated with a Qt pre-compiler making them usable as "slots". Qt uses a slot-signal architecture. In the python bindings, the hoops you have to jump through and significantly relaxed, but, as consistent with the Qt design philosophy, I call them "slots" so it's clear they they are intended to be connected to signals.
</blockquote></details>

Thanks for the explanation. Searching slot signal on google reveals more references.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 179 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Moj0ebN3s10Zi9y4yeX:-MojNNHuB-sqyGTB7Au3:b-kgp9w5) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L179)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I'm not convinced that the tick interval thing is purely cosmetic. I tried adding setTickInterval() and it does enable changing updating the edge width value.

Anyway, I like this solution too and it alleviates the obnoxious behavior you mentioned. The reference is a plus. Thanks!
</blockquote></details>

I tried it and it didn't do anything. Plus, the documentation suggests its purely cosmetic.  :)
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 903 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiwzPU2y0w9UbHR8--:-MojNYMK1aN6iF_v4tYJ:br4sqta) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L903)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I see. I'm asking because, unlike the previous iteration, I failed to find the documentation for this syntax.
</blockquote></details>

Finding python binding documentation is much harder than C++.  :(  It's a constant source of frustration for me.

**Review by EricCousineau-TRI — COMMENTED** [review]
Encore received! :lgtm: platform, with FYI about z-fighting

> Reviewed 1 of 1 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16115#-:-Mok6Ogd63RfsgcwQzRZ:b-qaash8)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Mok7yLx2r6_lRFJpQnM:-Mok7yLx2r6_lRFJpQnN:b6j9z15) (no related file):*
FYI Y'all may already be aware, but it seems like rendering contact patch directly onto same surface yields some z-fighting, e.g.:


---

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Mok7yLx2r6_lRFJpQnM:-MokBg219NGwfwUADpbR:bi2eqki) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Y'all may already be aware, but it seems like rendering contact patch directly onto same surface yields some z-fighting, e.g.:

</blockquote></details>

Yeah we are aware of it. We are going to have to live with it for now :(

---

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Mok7yLx2r6_lRFJpQnM:-MokEEriAqLiC1RBuJXa:bgfy9cm) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yeah we are aware of it. We are going to have to live with it for now :(
</blockquote></details>

Yup yup, makes sense!
Perhaps it could be fixed by shifting the surface mesh points by some epsilon according to the normal (if available), but yeah, prolly not worth the effort for now.

---

**Comment by EricCousineau-TRI** [comment]
___
*[tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, line 903 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16115#-MoiwzPU2y0w9UbHR8--:-MokEZEU6Mdv9FX9eqWI:blttnab) ([raw file](https://github.com/robotlocomotion/drake/blob/0cc97a75cbd3423a95f5663e6a30c5b548ae8d47/tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py#L903)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Finding python binding documentation is much harder than C++.  :(  It's a constant source of frustration for me.
</blockquote></details>

I also tried briefly looking... egad. I guess tutorials kinda hint at it?
https://build-system.fman.io/pyqt5-tutorial (see "Signals / slots")

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16115#-Mok7yLx2r6_lRFJpQnM:-MokFdp41GcEFzrgdXEH:bpw9to) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup yup, makes sense!
Perhaps it could be fixed by shifting the surface mesh points by some epsilon according to the normal (if available), but yeah, prolly not worth the effort for now.
</blockquote></details>

In fact, we used to have that feature, but it doesn't work very well.

---

**Pull request merged**
