### PR TITLE
Add finer Bazel granularity

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3925)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-:-KV5jnd8tzLKci1CR8GL:b-7ewwmf)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wf3OQTBM-a9AKVML:-KV5wf3OQTBM-a9AKVMM:bg5mspg) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L35)):*
> ```Python
> )
> 
> cc_library(
> ```

BTW, this and the following target strike me as odd library granularities - I probably would have made four libraries in this situation - but, up to you.

---

*[drake/automotive/BUILD, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wzXXcUmbGmv7Cq_j:-KV5wzXXcUmbGmv7Cq_k:bb7heiq) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L39)):*
> ```Python
>     srcs = [
>         "idm_with_trajectory_agent_autodiff.cc",
>         "simple_car_autodiff.cc",
> ```

hdrs

---

*[drake/automotive/BUILD, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5x-eykRPzF05bc75N:-KV5x-eykRPzF05bc75O:bb7heiq) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L50)):*
> ```Python
>         "idm_with_trajectory_agent_symbolic.cc",
>         "simple_car_symbolic.cc",
>     ],
> ```

hdrs

---

*[drake/common/BUILD, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5yUiPe95usDVObqUq:-KV5yUiPe95usDVObqUr:bqxy1rz) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/common/BUILD#L30)):*
> ```Python
>         "drake_throw.h",
>         "eigen_autodiff_types.h",
>         "eigen_matrix_compare.h",
> ```

BTW, this should possibly be in a separate testonly target.

---

*[drake/math/BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5xqAM7jLZytgD4X0a:-KV5xqAM7jLZytgD4X0b:bvch85t) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/math/BUILD#L42)):*
> ```Python
> # These require bleeding-edge Eigen.
> cc_library(
>     name = "fancy_eigen",
> ```

BTW, this name is kind of unhelpful, but I don't have a concrete suggestion to improve it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by david-german-tri** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wf3OQTBM-a9AKVML:-KV6pGd1d_Owpr7zs6zD:b-ud1vzq) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L35)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this and the following target strike me as odd library granularities - I probably would have made four libraries in this situation - but, up to you.
</details>
By that you mean one library per cc file?

---

*[drake/automotive/BUILD, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wzXXcUmbGmv7Cq_j:-KV6pZnSI2JDEIicL5o4:b-9zzezn) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L39)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> hdrs
</details>
Are you asking for an empty hrds list for clarity, so people don't wonder where they went?  I don't think we need an entries in hrds because all of the headers come from our deps.

---

*[drake/common/BUILD, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5yUiPe95usDVObqUq:-KV6r-Q7GwF90VxPOXEm:b-k9kxg7) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/common/BUILD#L30)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this should possibly be in a separate testonly target.
</details>
You would think that.  Except production code calls it.  Will add a TODO.

---

*[drake/math/BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5xqAM7jLZytgD4X0a:-KV6rTINi4jf-JgaQ5cR:b-1pgvwn) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/math/BUILD#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, this name is kind of unhelpful, but I don't have a concrete suggestion to improve it
</details>
`requires_modern_eigen` maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wf3OQTBM-a9AKVML:-KV6u8oK8GMMvh0kM-wW:b2nhswy) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> By that you mean one library per cc file?
</details>
Yes

---

*[drake/automotive/BUILD, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wzXXcUmbGmv7Cq_j:-KV6u9wVTKHX60vq2JMo:bf09aig) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Are you asking for an empty hrds list for clarity, so people don't wonder where they went?  I don't think we need an entries in hrds because all of the headers come from our deps.
</details>
OK, I retract the request.  It makes me uneasy that the headers you need to use this library at all are not mentioned, but I agree it's not necessary to mention them.

---

*[drake/math/BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5xqAM7jLZytgD4X0a:-KV6vA_Fjec3KgnYwWuT:bk8t6vu) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/math/BUILD#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> `requires_modern_eigen` maybe?
</details>
OK, that helps.  It bugs me to group libraries by dependency instead of by purpose, though.  Consider just splitting into three pieces with the obvious names, and pointing out the bleeding-edge requirement in a comment on each.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 1 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wf3OQTBM-a9AKVML:-KVAeMQyVhOPm3mPAKYT:b-kpw2y0) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L35)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Yes
</details>
So I've backed away from "let the supplemental cc files bloom"; I think it is a bit more complicated than my first attempt, given the upcoming system-transmogrify discussion (email my my drafts folder).  Instead, I've just made individual components here.

---

*[drake/automotive/BUILD, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wzXXcUmbGmv7Cq_j:-KVAefGR2uyX4oxaaiVd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L39)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK, I retract the request.  It makes me uneasy that the headers you need to use this library at all are not mentioned, but I agree it's not necessary to mention them.
</details>
Done.

---

*[drake/math/BUILD, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5xqAM7jLZytgD4X0a:-KVAejUxDONu2htlT2Mb:boafwx2) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/math/BUILD#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> OK, that helps.  It bugs me to group libraries by dependency instead of by purpose, though.  Consider just splitting into three pieces with the obvious names, and pointing out the bleeding-edge requirement in a comment on each.
</details>
Done.  I've split it up into separate components.  Good call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-:-KVAepp18UdveG5Te3nz:b-83330m)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 2 of 15 files at r2.
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-:-KVBYufmb4h7rymyHtMU:b-s794vx)*

**Comment by jwnimmer-tri** [comment]
I am going to rework this a bit to avoid premature generalization.  DNR in the meantime.

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/BUILD, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-KV5wf3OQTBM-a9AKVML:-KVPj_AazqhZ4HsiObUb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f5313f253d7326b1dba1eec59afeb5246687b73c/drake/automotive/BUILD#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> So I've backed away from "let the supplemental cc files bloom"; I think it is a bit more complicated than my first attempt, given the upcoming system-transmogrify discussion (email my my drafts folder).  Instead, I've just made individual components here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-:-KVPjazaMzPubUe5DE_f:b-83330m)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Re-ping @david-german-tri for all review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3925#-:-KVV2FUdE0sx9XvTvxCi:bnfp4nl)*

**Pull request merged**
