### PR TITLE
[examples] Remove cassie AutoDiffXd change detector tests

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The AutoDiffXd heap use experiments that led to these regression tests were an incomplete, aborted experiment.

The counters were useful at the time while exploring the solution space, but now only add developer friction -- decreasing our development speed, rather than improving it.

There is no direct correlation between our computation throughout (the metric we care about) and whether we have 31,000 vs 40,000 allocations.  A guard for LimitMalloc is useful when in the process of driving the limit to zero (with incremental PRs) -- this is the case for the T==double benchmark cases.  Limits that only reflect an empirical reality rather than any algorithmic principle are change detector tests, and will tend to bog down development.

To the extent we care about having LimitMalloc test coverage of #13988 changes to the AutoDiffXd implementation itself, that should have been a unit test in the common folder where we enforce few (or zero!) allocations on the move-aware functions one by one, not as part of a highly-volatile (#17399, #15874, #15495, #14167, #14296, #14115) change-detector regression test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17487)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

\CC @sherm1 for awareness.

---

\CC @mitiguy as related to #17399.  The AutoDiffXd change detector tests here were a mistake.  Don't double-down on that mistake in new code:

https://github.com/RobotLocomotion/drake/blob/c9c3fd3485daf27779150704b86463f182900057/math/test/rotation_matrix_test.cc#L1298-L1308

A test for LimitMalloc where the limit is zero is a meaningful statement.  A LimitMalloc test that hard-codes a magic number from your computer is a ticking time bomb.

**Comment by mitiguy** [comment]
A few thoughts:
1. To make progress, I removed the LimitMalloc test in PR #17399.  In case helpful, I stored the LimitMalloc test in a new uncommitted branch.   

2. I do not understand the general principles that guide progress (perhaps your opinion is evolving). The LimitMalloc test for the AutoDiffXd RotationMatrix constructor from a quaternion seems to use a reasonably countable number of plus (+), times (*), divide (/), equals (=) operations.  

3. From what I know, it seems some end-users occasionally have speed issues when using AutoDiff.  If that is true, it may be generally useful to have a cross-section of metrics to see when we degrade _or_ improve Drake's speed or its use of memory.  

4. The conversations at HQ with @xuchenhan-tri and @sherm1 associated with that now-removed LimitMalloc test were enlightening to all of us.  That does not mean the test should be part of the code base -- but maybe there is more to think about.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:


My .02: I agree this has become a mere change detector. The original hypothesis that led to allocation counting (allocations dominate among performance problems) was falsified; at this scale of heap thrash, a few thousand one way or other make no difference. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17487#-:-N5rVxta2VCKv0zAnhrL:b-vqqwz8)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Exactly.  We had good reasons to explore this path at the time, but now we have new ideas like #17335 to try out instead.

**Comment by sherm1** [comment]
The one thing Rico found that really improved AutoDiff performance was reducing the number of allocated temporaries (through judicious use of moves rather than copies). This LimitMalloc counter is a near-perfect proxy for the number of temporary AutoDiffScalars allocated, as evidenced by its catching Paul's surprise allocation of temporaries in the innocuous-appearing Eigen isZero() function. That is not merely a "change detector" as claimed in this PR.

I object to the rushed removal of this counter and do not agree that this should have been a single-reviewer PR. Please revert it.

**Comment by jwnimmer-tri** [comment]
> The one thing Rico found that really improved AutoDiff performance was reducing the number of allocated temporaries (through judicious use of moves rather than copies).

Yes, those were nice improvements.  Those fixes have [AutoDiffXd unit tests](https://github.com/RobotLocomotion/drake/blob/master/common/test/autodiffxd_heap_test.cc) still in place.  He didn't make corrections to MultibodyPlant code, he made corrections to AutoDiffXd.  The appropriate place for testing those fixes is in `common`, not `examples`.

> This LimitMalloc counter is a near-perfect proxy for the number of temporary AutoDiffScalars allocated ...

Allocations are only an approximate analogy for throughput.  The difference between 38049 allocations and 39000 allocations falls into the noise when measuring throughput.  Asking developers to go spelunking through a huge example anytime they get unlucky takes time away from Drake developers' more important tasks.  Just look at some of the **linked PRs in the original posting** where we needed to flail around with the limit for no good reason.

The "test" was not focused enough to pay debugging dividends, and has actively caused lost effort.  Limits in the tens of thousands that are fine-tuned down to the granularity of a single allocation make no sense.  It's still fine for the benchmark to _count_ the allocations, as a kind of additional telemetry to report.  (I have an improvement underway to this end.)  It's the **imprecise** regression testing (i.e., false positives) which is the problem.

If there are places in the code where we want a `LimitMalloc` guard of zero (or near-zero), let's add those tests -- ideally, adjacent to the class they are guarding.

Alternatively, it's sometimes possible to have a useful LimitMalloc test even when number of allocations is large and somewhat unpredictable.  Here's one example:

https://github.com/RobotLocomotion/drake/blob/32e1c6fd3baf1c41782af5e997a9a1b7584590a5/common/yaml/test/yaml_performance_test.cc#L77-L86

The regression being checked there is for a _linear_ number of allocations vs a _quadratic_ number of allocations.  The limit is set ~20x higher than the empirical count, and it was added in specific response to an acute performance bug (#12830).  It has never failed spuriously.  It's probable that the only time it will trip is in case someone re-introduces a super-linear number of allocations.

If we thought that MbP was a risk of doing insane numbers of heap operations (i.e., regressing by a factor of >10x or >20x), it would be acceptable to encode that limit into a regression test.  That would no longer be a change-detector test.

> Paul's surprise allocation of temporaries in the innocuous-appearing Eigen isZero() ...

The exploration was an interesting novelty for professional learning, but ultimately was not relevant to Drake's performance.  That time you all spent huddled at your desks in HQ on the topic last week would have been better spent fixing bugs, adding features, or _actually_ improving performance.  It's a waste of time to micro-optimize a function that has no measurable impact on performance, and the fact that the test failure send you down that rabbit hole is exactly why the test needs to go away.

Here's [a gist](https://gist.github.com/jwnimmer-tri/8e23666eccc2d8330e182dd0a65a7473) with benchmarking results:
1. Drake master (32e1c6f)
2. [17399](https://github.com/RobotLocomotion/drake/pull/17399) merged up to master
3. [17399](https://github.com/RobotLocomotion/drake/pull/17399) merged up to master with the `DiscardGradient` removed.

There is no measurable effect from the lack of `DiscardGradient`.  There was no performance regression.  The fact that the "performance test" failed was a false positive.  It's a change detector test, not an automated performance regression test.

In any case, the best fix for the `isZero()` situation in particular is _not_ to nickle and dime our way through LimitMalloc change detector tests.  It's to rewrite AutoDiffScalar from the ground up so that it does not allocate when being copied, so that we fix it once and for all across the entire codebase.

I've already rewritten it and I'll post the PR next week with the improvements.  So far, on the cassie autodiff benchmarks it's showing a reduction in the computation time by 35-60%.

> I object to the rushed removal of this counter ... Please revert it.

Rico is the subject matter expert here; I'll defer to him on the question of a revert.

I stand my by opinion that these limits were a time sink for the development team (https://github.com/RobotLocomotion/drake/pull/17399, https://github.com/RobotLocomotion/drake/pull/15874, https://github.com/RobotLocomotion/drake/pull/15495, https://github.com/RobotLocomotion/drake/pull/14167); that Rico as the subject matter expert was the most appropriate feature reviewer; and that there was no style or readability novelty that indicated the need for a separate platform reviewer to look.

If my notes above don't answer your questions, then maybe we can set up a vcon next week to discuss.  It's still not clear to me why a performance regression test that has only ever reported false positives is supposed to be valuable.

**Comment by jwnimmer-tri** [comment]
FYI I've filed #17518 to add back heap usage reports to the summary output.  I do think the reports are still useful information.

**Comment by sherm1** [comment]
That sounds good -- thanks.

**Pull request merged**
