### PR TITLE
Rename foo_tests to foo_test per convention

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6650)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by amcastro-tri** [comment]
Thank you for cleaning up my mess @jwnimmer-tri. :lgtm: 

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6650#-:-KptuP_-FJittZVkKUcW:bbin8ok)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-tri for platform review, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6650#-:-Kpu0DCQXWcOoLvpU7gb:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for final pass.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6650#-:-Kpu0bhB90rNT14cHn-z:bt4pl1n)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6650#-:-Kpu7CaxkDTz225E3h9Y:bnfp4nl)*

**Pull request merged**
