### PR TITLE
BUILDCOP: Modify MATLAB test timeouts and disable flaky test

### PR DESCRIPTION
**Pull request by jamiesnape**
`mac-clang-continuous-matlab` is still failing on occasion.

@david-german-tri @jwnimmer-tri PTAL

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2304)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/CMakeLists.txt, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2304#-KHQAto4FzDO_G6D3pCt:-KHQAto4FzDO_G6D3pCu:-776870464) ([raw file](https://github.com/robotlocomotion/drake/blob/88d9603597c578a41adbfa7cdeea9fcf63b49393/drake/examples/Pendulum/CMakeLists.txt#L43)):*
> ```CMake
> 
> if (LONG_RUNNING_TESTS)
>   # add_matlab_test(NAME examples/Pendulum/runTrajectorySwingUpAndBalance COMMAND runTrajectorySwingUpAndBalance PROPERTIES TIMEOUT 1500)  # FIXME
> ```

I don't see how this is related to fixing -continuous, nor why disabling a test without a breadcrumb is a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2304)*

**Comment by jamiesnape** [comment]
Since it is failing on mac continuous then it is unambiguously connected to it.

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/CMakeLists.txt, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2304#-KHQAto4FzDO_G6D3pCt:-KHQCktJCgU6loLIQSu7:-325432403) ([raw file](https://github.com/robotlocomotion/drake/blob/88d9603597c578a41adbfa7cdeea9fcf63b49393/drake/examples/Pendulum/CMakeLists.txt#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't see how this is related to fixing -continuous, nor why disabling a test without a breadcrumb is a good idea.</details>
Ah, I forgot that `LONG_RUNNING_TESTS` is turned on for -continuous; somehow I thought it was only nightly.

The test doesn't seem to fail _too_ often, but looking in CDash I do see the same error a few times in the past.

At a minimum, could you please open an issue about that particular flaky test, and cite it in the FIXME?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2304)*

**Comment by jamiesnape** [comment]
Sure.

**Comment by jamiesnape** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Pendulum/CMakeLists.txt, line 43 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2304#-KHQAto4FzDO_G6D3pCt:-KHQMfmimjEHhGcZVKJo:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/88d9603597c578a41adbfa7cdeea9fcf63b49393/drake/examples/Pendulum/CMakeLists.txt#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Ah, I forgot that `LONG_RUNNING_TESTS` is turned on for -continuous; somehow I thought it was only nightly.
> 
> The test doesn't seem to fail _too_ often, but looking in CDash I do see the same error a few times in the past.
> 
> At a minimum, could you please open an issue about that particular flaky test, and cite it in the FIXME?
> 
> </details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2304)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Since it is failing on mac continuous then it is unambiguously connected to it.</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2304#-:-KHQNGqXEM7Kb032tYxy:1417088721)*

**Pull request merged**
