### PR TITLE
Toward #2852: enforce -Werror=shadow in systems/robotInterfaces/.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* Remove excuse from systems/robotInterfaces/ cmake file.
 * Rename private members with '_' suffix per style guide.
 * Fix assorted white space issues:
   * indents.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2895)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
another step toward #2852.

**Comment by rpoyner-tri** [comment]
+@david-german-tri for feature review.
+@ggould-tri  for platform review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2895#-:-KNJ7z7HTth0YFcREhzG:1415798639)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2895#-:-KNJ8_vMFqX29zjF6WsB:1417088721)*

**Comment by ggould-tri** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2895#-:-KNJ9aY2rjj0p8tFc1yw:980077423)*

**Pull request merged**
