### PR TITLE
Tidy up some scalar conversion declarations and documentation.

### LINKED ISSUE #8798: Conflict between default_scalars and system_scalar_converter
In a recent PR (#8778) a confusing compiler error arose.

Problem Statement
==============
The `QuadrotorPlant` uses the `SystemScalarConverter` to get its transmogrification for free. In `quadrotor_plant.cc` it uses `default_scalars` to instantiate on *nonsymbolic* scalars. Prior to the PR in question, both of those features were fine.

In the PR, some functionality was changed such that some of the underlying components of `QuadrotorPlant` no longer supported the `symbolic::Expression` scalar. (In this case, it's the new `RotationMatrix` class.)

The compiler warned that it couldn't instantiate a `RotationMatrix<Expression>` type (which is fair because such a thing does not exist.) However, the author of the PR was mystified why this error was even coming up. The `QuadrotorPlant` was only being instantiated on `double` so it wasn't obvious why the compiler was even looking for `Expression`-valued types.

THe solution, of course, was to specialize the conversion traits for the plant in question to be `NonSymbolicTraits`. Now compilation proceeded apace.

__It seems odd that the conversion table can be set up to include instantiations of a class that don't actually exist (in this case the `QuadrotorPlant<Expression>`).__

Solution(?)
======

__Option 1:__ It would be *great* if it wasn't possible to convert to an unsupported scalar type. I.e., if I only instantiate it on numeric scalar types, it will only convert to those same supported types. This would happen with a single declaration without my having to coordinate two different calls.

__Option 2:__ An error message that can better direct users who are less versed in the ways of transmogrifcation would mitigate the personal cost of otherwise addressing inscrutable errors.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See commit messages for details.

Closes #8798.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for sole review, please.  (Or LMK if you'd like a second reviewer.)

**Comment by SeanCurtis-TRI** [comment]
Great! Thanks for cleaning house. 

I have some pedantic thoughts on the documentation. This is a public enough API that I feel it should be spelled out for the average Drake user rather than relying on a user who is steeped in the framework.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/scalar_conversion_traits.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LCpV4jiEDpHVddL58EV:-LCpV4jiEDpHVddL58EW:b-c0e1co) ([raw file](https://github.com/robotlocomotion/drake/blob/6617d5a40be0268540590f8f11812f7c2bfe9e12/systems/framework/scalar_conversion_traits.h#L14)):*
> ```objc
> /// the framework should support conversion for a combination of S, T, and U.
> ///
> /// When Traits::supported is true, the "scalar-converting copy constructor"
> ```

BTW I feel there's a slight disconnect between "Traits::supported __is__ true" and "__those__ types". Implicit in this is that, for a given `S`, there is a different `supported` for every `T, U` combination. Can this be spelled out more clearly?

---

*[systems/framework/scalar_conversion_traits.h, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LCpUZMvEbQgtds99nTN:-LCpUZMvEbQgtds99nTO:b-7nbpvm) ([raw file](https://github.com/robotlocomotion/drake/blob/6617d5a40be0268540590f8f11812f7c2bfe9e12/systems/framework/scalar_conversion_traits.h#L15)):*
FYI How do you feel about elaborating the implications of "Traits::supported is true" as:

> The author of the corresponding class S is responsible for confirming that S supports construction on all "supported" scalar types.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833#-:-LCpVd6c1zW3wCNTkQVx:bk7bujw)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/scalar_conversion_traits.h, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LCpV4jiEDpHVddL58EV:-LD1xc3PDIaDqQzLSDyj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6617d5a40be0268540590f8f11812f7c2bfe9e12/systems/framework/scalar_conversion_traits.h#L14)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I feel there's a slight disconnect between "Traits::supported __is__ true" and "__those__ types". Implicit in this is that, for a given `S`, there is a different `supported` for every `T, U` combination. Can this be spelled out more clearly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With one last linguistic request.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/scalar_conversion_traits.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LD20_VG1WRC-MEGMIvs:-LD20_VG1WRC-MEGMIvt:bx82jy5) ([raw file](https://github.com/robotlocomotion/drake/blob/24efb11092b3dd2217af5d563e8f09382b9a99d7/systems/framework/scalar_conversion_traits.h#L12)):*
BTW "any given" doesn't feel quite right. Ping me if you want my reasons, but the short version is that I would recommend:

> "... whether the framework should support conversions of class `S<T>` to class `S<U>` for arbitrary scalar types `T` and `U`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833#-:-LD22AxO0vnm1J4_xwUc:b8x1dud)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/scalar_conversion_traits.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LD20_VG1WRC-MEGMIvs:-LD264tj4juzOieRa0B2:b-lwkn3) ([raw file](https://github.com/robotlocomotion/drake/blob/24efb11092b3dd2217af5d563e8f09382b9a99d7/systems/framework/scalar_conversion_traits.h#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "any given" doesn't feel quite right. Ping me if you want my reasons, but the short version is that I would recommend:

> "... whether the framework should support conversions of class `S<T>` to class `S<U>` for arbitrary scalar types `T` and `U`.
</blockquote></details>

If you are posing a defect to be fixed, you will have to more clearly state what the problem is.  I do not understand what is defective about the current text, from the above post. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/scalar_conversion_traits.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LD20_VG1WRC-MEGMIvs:-LD27IVo9fqOrX8WcdKu:bheq3gl) ([raw file](https://github.com/robotlocomotion/drake/blob/24efb11092b3dd2217af5d563e8f09382b9a99d7/systems/framework/scalar_conversion_traits.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you are posing a defect to be fixed, you will have to more clearly state what the problem is.  I do not understand what is defective about the current text, from the above post. 
</blockquote></details>

Fair enough.

The issue is one of imprecision. The phrase "any given combination" is not strictly true. The combinations are, in fact, constrained; one can't do U<T, S>. Now, the logical rejoinder is that the compiler will prevent such an invalid combination. The defect I was hoping to correct was one of whether the language could stand on its own, or if its correctness depended on a larger contextual understanding of intent. What's written is concise and can be argued to be correct, "from a certain point of view". I'm hoping to expend a bit more verbiage to embed the context and, hopefully, reduce the odds of misinterpretation.

More particularly, you've defined `S` at the beginning of the sentence as a "particular scalar-dependent [class]". As long as we start the sentence with at least some syntactic knowledge, I felt the sentence would benefit from ending in the same way - so let's clearly indicate that where `S` is the scalar-dependent class, `T` and `U` are the scalar types where `T` is the source scalar and `U` is the destination scalar.  

All of those details *feel* like they contradict the phrase "any given combination".

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/scalar_conversion_traits.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LD20_VG1WRC-MEGMIvs:-LD2Y5S15MCT7aDPGApc:bnjexe7) ([raw file](https://github.com/robotlocomotion/drake/blob/24efb11092b3dd2217af5d563e8f09382b9a99d7/systems/framework/scalar_conversion_traits.h#L12)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Fair enough.

The issue is one of imprecision. The phrase "any given combination" is not strictly true. The combinations are, in fact, constrained; one can't do U<T, S>. Now, the logical rejoinder is that the compiler will prevent such an invalid combination. The defect I was hoping to correct was one of whether the language could stand on its own, or if its correctness depended on a larger contextual understanding of intent. What's written is concise and can be argued to be correct, "from a certain point of view". I'm hoping to expend a bit more verbiage to embed the context and, hopefully, reduce the odds of misinterpretation.

More particularly, you've defined `S` at the beginning of the sentence as a "particular scalar-dependent [class]". As long as we start the sentence with at least some syntactic knowledge, I felt the sentence would benefit from ending in the same way - so let's clearly indicate that where `S` is the scalar-dependent class, `T` and `U` are the scalar types where `T` is the source scalar and `U` is the destination scalar.  

All of those details *feel* like they contradict the phrase "any given combination".
</blockquote></details>

Done, I think?  It sounds like `S` there was just confusing the issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/scalar_conversion_traits.h, line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8833#-LD20_VG1WRC-MEGMIvs:-LD2aC8V8lQ_owL3TBe_:bm8bcg9) ([raw file](https://github.com/robotlocomotion/drake/blob/24efb11092b3dd2217af5d563e8f09382b9a99d7/systems/framework/scalar_conversion_traits.h#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done, I think?  It sounds like `S` there was just confusing the issue.
</blockquote></details>

I can buy that. Not as explicit as the pedantic part of my soul would like, but I agree that the small edit does address the core of the issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8833)*

**Comment by jwnimmer-tri** [comment]
The `linux-xenial-clang-bazel-experimental-memcheck-lsan` seems like a fluke:
```
//systems/controllers:dynamic_programming_test TIMEOUT in 305.4s
```
I will force-merge this in.

**Pull request merged**
