### PR TITLE
Implements hybrid direct collocation for multibody systems

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19404)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-packaging please

**Comment by RussTedrake** [comment]
+@vincekurtz for feature review, please.  
cc @mposa (would love comments if you have time!)

**Comment by RussTedrake** [comment]
*[`planning/trajectory_optimization/hybrid_multibody_collocation.cc` line 413 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVbPgKD7t4xrxSlYYEY:-NVbPgKD7t4xrxSlYYEZ:b-cup9u) ([raw file](https://github.com/RobotLocomotion/drake/blob/7c3420e0296992a1a787aaf9cf224798dbbee918/planning/trajectory_optimization/hybrid_multibody_collocation.cc#L413)):*
> ```cpp
> 
>     y->head(plant.num_velocities()) =
>         M * (vplus - vminus) - J.transpose() * Lambda;
> ```

fyi - I realized that i need to have forces for all active contacts here (not just the new contact).  i'll adjust it first thing in the morning.

**Review by vincekurtz — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19404)* status: 4 unresolved discussions, LGTM missing from assignee vincekurtz, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVZfLEx-Bd4D6HjXKzI:-NVZfLEx-Bd4D6HjXKzJ:b-pdmxz4) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.h#L27)):*
> ```objc
> */
> 
> /** Implements hybrid trajectory optimization using a MultibodyPlant, where the
> ```

nit, it might be nice to specify more clearly what is given by the user and what is optimized over, since "hybrid trajectory optimization" could mean several things IMO. E.g., the mode sequence is fixed by the user, but are contact timings and locations also fixed?
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 108 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVZgvbU3mjMDA5MiW12:-NVZgvbU3mjMDA5MiW13:bgujjs6) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.h#L108)):*
> ```objc
>     /** Returns decision variables associated with the contact
>     forces for all contacts. */
>     solvers::VectorXDecisionVariable AllContactForces(int index) const;
> ```

nit, what is index? (time-index, I guess)
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.cc` line 111 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVbHS2O3Tt5aYNX2duT:-NVbHS2O3Tt5aYNX2duU:b4gdzl7) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.cc#L111)):*
> ```cpp
>     for (const ContactPair& contact_pair : in_contact_) {
>       geometry::SignedDistancePair<AutoDiffXd> distance_pair =
>           query_object.ComputeSignedDistancePairClosestPoints(
> ```

nit, I can imagine users getting frustrated because this only supports sphere-box, sphere-sphere, and sphere-halfspace. It might be helpful to do some checks in the constructor for unsupported geometries and give an informative error message earlier
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 492 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVbP9laCqOjAVGQVInZ:-NVbP9laCqOjAVGQVIn_:b-o3d7ja) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/bindings/pydrake/planning/test/trajectory_optimization_test.py#L492)):*
> ```Python
>         diagram = builder.Build()
>         context = diagram.CreateDefaultContext()
>         plant_context = diagram.plant().GetMyContextFromRoot(context)
> ```

nit, plant_context is never used

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19404)* status: 1 unresolved discussion, LGTM missing from assignee vincekurtz, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @vincekurtz)

___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVZfLEx-Bd4D6HjXKzI:-NVdXCzX3F87pCdF4X3b:bs7wumx) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.h#L27)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, it might be nice to specify more clearly what is given by the user and what is optimized over, since "hybrid trajectory optimization" could mean several things IMO. E.g., the mode sequence is fixed by the user, but are contact timings and locations also fixed?
</blockquote></details>

Done. 
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 108 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVZgvbU3mjMDA5MiW12:-NVdY-j8C4YOcWspoFwP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.h#L108)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, what is index? (time-index, I guess)
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.cc` line 111 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVbHS2O3Tt5aYNX2duT:-NVdY9nd7chN-Fw589A6:b-rrxus1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/planning/trajectory_optimization/hybrid_multibody_collocation.cc#L111)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, I can imagine users getting frustrated because this only supports sphere-box, sphere-sphere, and sphere-halfspace. It might be helpful to do some checks in the constructor for unsupported geometries and give an informative error message earlier
</blockquote></details>

I agree it will be frustrating (and that we should widen our support).  But I think the message generated by the proximity engine is actually pretty good, and I would not want to duplicate it here in a way that could get out of sync if/when we do broaden that support in the proximity engine?
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 492 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVbP9laCqOjAVGQVInZ:-NVdYUTiAMqdCeJaRckl:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e67e1440daaffac464919e54d3a82f49921ffde9/bindings/pydrake/planning/test/trajectory_optimization_test.py#L492)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, plant_context is never used
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
i've made the last change I mentioned and finished updating the tests.  should be good to go.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-:-NVg_6Fx9brI0H3BOSfP:b-y581p9)* status: LGTM missing from assignee vincekurtz, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @vincekurtz)

**Review by hongkai-dai — COMMENTED** [review]
Sorry for being late for the party (and thanks for implementing this class). I left a few comments here.

Sorry for blocking the PR with my comments. I am still travelling and will be back to US on Friday night so I might not be able to respond to the comments today and tomorrow. Feel free to dismiss the comments if you want to merge the PR.

> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-:-NVherkf4A9zgknD2YUn:b-y72lpq)* status: 4 unresolved discussions, LGTM missing from assignee vincekurtz, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @vincekurtz)

___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 74 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVhclXkBLmWzbDl4LjU:-NVhclXkBLmWzbDl4LjV:b-83do4o) ([raw file](https://github.com/RobotLocomotion/drake/blob/de131092e72ef82cff37929970363499198b9750/planning/trajectory_optimization/hybrid_multibody_collocation.h#L74)):*
> ```objc
> 
>   /** Implements a specialized version of Constrained Direct Collocation
>    (DIRCON) with contact forces as additional sequential decision variables. */
> ```

BTW, maybe also mention that the contact mode is unchanged within each ConstrainedDirectCollocation class? In Michael's DIRCON paper he presents the trajectory optimization across contact modes, so I was a bit confused initially when I read the code of this class.
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 99 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVhdD9-3EZeIBn4ix-u:-NVhdD9-3EZeIBn4ix-v:b-aobkvh) ([raw file](https://github.com/RobotLocomotion/drake/blob/de131092e72ef82cff37929970363499198b9750/planning/trajectory_optimization/hybrid_multibody_collocation.h#L99)):*
> ```objc
>     @throws std::exception if @p contact is not in_contact(). */
>     solvers::VectorXDecisionVariable ContactForce(
>         const ContactPair& contact) const;
> ```

If we have multiple contacts, then I assume that we stack their corresponding contact force variable into one column vector, and return that column vector here. By stacking the variables, we lose the mapping between the contact to each of the force variables, namely it is hard to know what is the meaning of each individual entry in the returned stack force variable.

Do you think it makes sense to return the mapping from each contact wrench evaluator to their corresponding force variables?
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 154 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVheXrg4iyxeP70UXzW:-NVheXrg4iyxeP70UXzX:b8nl220) ([raw file](https://github.com/RobotLocomotion/drake/blob/de131092e72ef82cff37929970363499198b9750/planning/trajectory_optimization/hybrid_multibody_collocation.h#L154)):*
> ```objc
>     std::string name_{};
>     const RobotDiagram<AutoDiffXd>* robot_diagram_;
>     std::unique_ptr<systems::Context<AutoDiffXd>> context_w_collisions_;
> ```

Is it OK to document why we differentiate between these two contexts, with and without collisions? Also for the `sample_contexts_` variable below, are they with or without collision?
___
*[`planning/trajectory_optimization/hybrid_multibody_collocation.h` line 161 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19404#-NVhds6g-cc9jdSgY5dG:-NVhds6h4Uxve4F2i1q1:b-bv3kc8) ([raw file](https://github.com/RobotLocomotion/drake/blob/de131092e72ef82cff37929970363499198b9750/planning/trajectory_optimization/hybrid_multibody_collocation.h#L161)):*
> ```objc
> 
>     std::vector<
>         std::unique_ptr<multibody::ContactWrenchFromForceInWorldFrameEvaluator>>
> ```

Curious why we use `ContactWrenchFromForceInWorldFrameEvaluator` here instead of the base class `ContactWrenchEvaluator`, it is probably more general to use the base class, which can also handle force measured in the body frame?

**Comment by RussTedrake** [comment]
I've been hammering the new implementation with tests and saw something I can't explain yet.  Will add "do not review" "do not merge" tags until I resolve it.

**Pull request closed without merging**
