### PR TITLE
[common] Extract remaining symbolic files into smaller libraries

### LINKED ISSUE #13833: Restructure symbolic files in drake/common
From https://github.com/RobotLocomotion/drake/pull/13796#issuecomment-667980543

Observation:

 - We have `drake/common/symbolic_*.{h,cc}` files which uses namespace `drake::symbolic` but not in `drake/common/symbolic` directory. This is against GSG.

 - We consolidate all `symbolic_*.{h,cc}` files into a single target, `//common:symbolic` which is used by `//common:default_scalars` and most of Drake code transitively. However,  `//:common:default_scalars` target only needs `symbolic::Expression` and its dependencies.

Plan:

 - Create `drake/common/symbolic` directory and move symbolic files to it.
 - Provide a smaller bazel target which only includes `symbolic::Expression` and its dependencies (including `Variable`, `Formula`, etc).
 - Provide bazel targets for other symbolic files (such as `PolynomialBasisElement`).
 - In the first PR, I will find a way to keep `drake/common/symbolic.h` and `//common:symbolic` target to minimize the changes outside of `common` directory.

/cc @jwnimmer-tri 
/cc @hongkai-dai

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13833.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@hongkai-dai for feature review please and +@ggould-tri for platform review please.  I think perhaps it makes sense to do both at once, for a more boilerplate-like PR?

Hongkai please look at my cc_library names choices for drake/common/symbolic/BUILD.  Some of them are slightly different than what was in drake/common/BUILD prior.

---

For both Hongkai and Grant:

As it currently stands as of r1, this PR represents what Drake will look like after the deprecation window closes -- this is the "flag day" version of the file moves.

I'd like to review this and edit / cycle it until we are happy with it.  **Then** once that's ready, I'll add a second (curated) commit with the deprecation backfill, and we will review those diffs.  I think that two-stage review cycle will be easier for both you and me.

That also opens the door to ease the future cleanup after deprecation window closes.  I can simply revert the second commit after 3 months.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479#-:-N5p8v_H8YBoXHqQpGFb:bb3qowg)* status: 2 unresolved discussions, LGTM missing from assignees hongkai-dai,ggould-tri(platform) (waiting on @ggould-tri, @hongkai-dai, and @jwnimmer-tri)

___
*[`common/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5p8VrX4wWfMhWcqyxw:-N5p8VrX4wWfMhWcqyxx:bd4aex2) ([raw file](https://github.com/robotlocomotion/drake/blob/8dd26b6d496e19976f7545e985599f7b32cf2fc1/common/BUILD.bazel#L55)):*
> ```Starlark
>         ":scoped_singleton",
>         ":sorted_pair",
>         ":symbolic",
> ```

Working

These four label names will need deprecation stubs.
___
*[`common/BUILD.bazel` line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5p8Za20VNiOMSUvKHK:-N5p8Za20VNiOMSUvKHL:b-73u5zd) ([raw file](https://github.com/robotlocomotion/drake/blob/8dd26b6d496e19976f7545e985599f7b32cf2fc1/common/BUILD.bazel#L232)):*
> ```Starlark
>         # TODO(#13833) We should split out this header into its own library,
>         # once we have the new subdirectory established.
>         "symbolic_decompose.h",
> ```

Working

These two header file names will need deprecation stubs.

**Comment by ggould-tri** [comment]
That seems like a good plan to manage the complexity and it has my vote.  :+1:

**Review by hongkai-dai — COMMENTED** [review]
Cool! The names in the `common/symbolic/BUILD.bazel` look good to me.

> Reviewed 78 of 79 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479#-:-N5pMZkp2rd5soWyNiTF:b8zzl3m)* status: 3 unresolved discussions, LGTM missing from assignees ggould-tri(platform),hongkai-dai (waiting on @ggould-tri, @hongkai-dai, and @jwnimmer-tri)

___
*[`common/symbolic/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5pHs_M-mCfKVtlCc6E:-N5pHs_M-mCfKVtlCc6F:byx8d6t) ([raw file](https://github.com/robotlocomotion/drake/blob/67c8b7ef4445243f1fafde0298b571577fa2feb6/common/symbolic/BUILD.bazel#L39)):*
> ```Starlark
> )
> 
> drake_cc_library(
> ```

I think in many other BUILD.bazel files, we put all the drake_cc_library before all the drake_cc_googletest. In this BUILD.bazel file, we follow a different pattern, that we put drake_cc_library in the alphabetic order, but follow each drake_cc_library with the `drake_cc_googletest` that directly depends on that library. Is this the new pattern that we should follow in `BUILD.bazel` file?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479)* status: 3 unresolved discussions, LGTM missing from assignees ggould-tri(platform),hongkai-dai (waiting on @ggould-tri, @hongkai-dai, and @jwnimmer-tri)

___
*[`common/symbolic/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5pHs_M-mCfKVtlCc6E:-N5pPzV8EFmgxKBq82zj:b-1y7bmp) ([raw file](https://github.com/robotlocomotion/drake/blob/67c8b7ef4445243f1fafde0298b571577fa2feb6/common/symbolic/BUILD.bazel#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I think in many other BUILD.bazel files, we put all the drake_cc_library before all the drake_cc_googletest. 

That's correct.

> In this BUILD.bazel file, we follow a different pattern, that we put drake_cc_library in the alphabetic order, but follow each drake_cc_library with the drake_cc_googletest that directly depends on that library.

Exactly!

> Is this the new pattern that we should follow in BUILD.bazel file?

It's a style I've been trying out for some of my newer directories.  If people like it they should feel free to adopt it, but I'm not at the point yet where I'd definitively recommend it.

My expectation is that when updating a BUILD file with new code or tests, the developer follows the local conventions of that file, whatever that might be.
</blockquote></details>

I see. I guess I am curious what if a test directly depends on two libraries. It might not be a good design as it is not "unit test", but if it happens, should we put the test right after library A or library B?

**Review by jwnimmer-tri — COMMENTED** [review]
It at least makes `bazel test //common:*` a lot faster.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479#-:-N5putEM7BrX9qbx0ilz:b-8kg7dv)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, labeled "do not merge" (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/symbolic/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5pHs_M-mCfKVtlCc6E:-N5puxOD1M_FeysCzf1U:bezs6f1) ([raw file](https://github.com/robotlocomotion/drake/blob/67c8b7ef4445243f1fafde0298b571577fa2feb6/common/symbolic/BUILD.bazel#L39)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see. I guess I am curious what if a test directly depends on two libraries. It might not be a good design as it is not "unit test", but if it happens, should we put the test right after library A or library B?
</blockquote></details>

I would probably put it next to which of the two is higher in the dependency stack -- so if B uses A, then I would put the test near B.

Note, however "depends on" in the sense of `deps` isn't the qualifier I'm using here.  Tests will `deps` on lots of things.  In my mind, the important organizational question is which items they are checking for correctness.  If they call other code as part of that, so be it.  That other code can (will) still be unit tested elsewhere.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @hongkai-dai)

___
*[`common/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5p8VrX4wWfMhWcqyxw:-N6JLtTz8skZ4OoeiT72:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8dd26b6d496e19976f7545e985599f7b32cf2fc1/common/BUILD.bazel#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

These four label names will need deprecation stubs.
</blockquote></details>

Done.
___
*[`common/BUILD.bazel` line 232 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5p8Za20VNiOMSUvKHK:-N6JLuW836wI7JgpSv7W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8dd26b6d496e19976f7545e985599f7b32cf2fc1/common/BUILD.bazel#L232)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

These two header file names will need deprecation stubs.
</blockquote></details>

Done.
___
*[`common/symbolic/BUILD.bazel` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17479#-N5pHs_M-mCfKVtlCc6E:-N6J5oxnBD6c8BURoeoa:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/67c8b7ef4445243f1fafde0298b571577fa2feb6/common/symbolic/BUILD.bazel#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would probably put it next to which of the two is higher in the dependency stack -- so if B uses A, then I would put the test near B.

Note, however "depends on" in the sense of `deps` isn't the qualifier I'm using here.  Tests will `deps` on lots of things.  In my mind, the important organizational question is which items they are checking for correctness.  If they call other code as part of that, so be it.  That other code can (will) still be unit tested elsewhere.
</blockquote></details>

Done?

**Comment by jwnimmer-tri** [comment]
For reviewing the `common/BUILD.bazel` shims, I suggest looking versus r_base, not r_1.

Comparing `bazel run //:install -- --list /tmp/nothing` for master versus this PR, we see that the only change to the installed image is the _addition_ of new files.  That proves that all of the deprecation headers have been provided.

```patch
--- master.txt	2022-07-06 09:24:02.955803714 -0700
+++ pr.txt	2022-07-06 09:24:11.811920208 -0700
@@ -56,6 +56,10 @@
 include/drake/common/scoped_singleton.h
 include/drake/common/sorted_pair.h
 include/drake/common/symbolic.h
+include/drake/common/symbolic/chebyshev_basis_element.h
+include/drake/common/symbolic/chebyshev_polynomial.h
+include/drake/common/symbolic/codegen.h
+include/drake/common/symbolic/decompose.h
 include/drake/common/symbolic/expression.h
 include/drake/common/symbolic/expression/all.h
 include/drake/common/symbolic/expression/environment.h
@@ -68,6 +72,17 @@
 include/drake/common/symbolic/expression/ldlt.h
 include/drake/common/symbolic/expression/variable.h
 include/drake/common/symbolic/expression/variables.h
+include/drake/common/symbolic/generic_polynomial.h
+include/drake/common/symbolic/latex.h
+include/drake/common/symbolic/monomial.h
+include/drake/common/symbolic/monomial_basis_element.h
+include/drake/common/symbolic/monomial_util.h
+include/drake/common/symbolic/polynomial.h
+include/drake/common/symbolic/polynomial_basis.h
+include/drake/common/symbolic/polynomial_basis_element.h
+include/drake/common/symbolic/rational_function.h
+include/drake/common/symbolic/simplification.h
+include/drake/common/symbolic/trigonometric_polynomial.h
 include/drake/common/symbolic_chebyshev_basis_element.h
 include/drake/common/symbolic_chebyshev_polynomial.h
 include/drake/common/symbolic_codegen.h
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
@hongkai-dai I've finished the updates here now.  Please have a look when you are able (missing the "lgtm" so far).

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17479#-:-N6KWFxi4tlgNqv1hRQM:bg7igkv)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Pull request merged**
