### PR TITLE
Before Updating Eigen, A Consideration

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6294)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Why is this a comment in a PR and not a question in an issue?

**Comment by m-chaturvedi** [comment]
I spoke with @stonier if this warrants creating an issue or not.  He said that we should add it as a comment, that an issue will get lost in the noise.

**Comment by jwnimmer-tri** [comment]
If we were to switch to an Eigen version that has this specialization, our code would stop compiling:
```
./drake/common/eigen_autodiff_limits.h:14:7: error: redefinition of 'numeric_limits<AutoDiffScalar<type-parameter-0-0> >'
class numeric_limits<Eigen::AutoDiffScalar<T> >
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Given that, I don't think a build system comment is worthwhile.

**Comment by jamiesnape** [comment]
Really the comment would therefore need to be "you must" rather than "consider".

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-Km8OcWFt81n9_VsnZ2m:b-8nn7wb)*

**Comment by jamiesnape** [comment]
But I agree that it would be obvious.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-Km8PJX6N3AFzEkduV7I:b-34t8pe)*

**Comment by m-chaturvedi** [comment]
"You must" can be used if we're _sure_ that the commit is taken in the next tag.  They may choose to ignore it for some reason?

**Comment by jwnimmer-tri** [comment]
In any case, the build system is the wrong place for a comment.  If we place a comment at all (which I don't think we need to), it would be in the header file at the point of our own specialization, saying:

    If you see a 'duplicate specialization' compiler error here, then Eigen must have
    started providing this itself; conditionalize or remove Drake's own specialization.

**Comment by jamiesnape** [comment]
Agreed (to both sentiments).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-Km8Q9rTnnWIGv_pompX:b-t8a5bs)*

**Comment by jamiesnape** [comment]
@stonier Do you have any objections to closing this PR without merging (my preference) or would you be happier with a comment in the `eigen_autodiff_limits.h` header file?

**Comment by stonier** [comment]
My advice was the header. Code should have a comment illuminating what it is and why it is there if it is not trivially obvious. Adding Jeremy's info on what is likely to go wrong and what the fix will be would complete the story. Right now it's a bare file that only raises questions.

An issue would be adding a tentative plan to act on something that might become necessary. Noise. Having the story with the code also makes the story more robust against forks, or code migrations to different repositories.

So yes, fine with closing the PR and moving it to the header unless @jwminner-tri has a strenous objection (he does wear the software core hat).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-KmOjStsFyThYkXy4XgP:b-5pfm15)*

**Comment by jwnimmer-tri** [comment]
I would not object to a header file comment.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_autodiff_limits.h, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-KmWa8v9Ks99AsIfBXpD:-KmWa8v9Ks99AsIfBXpE:b-ae4ns2) ([raw file](https://github.com/robotlocomotion/drake/blob/ea8e9cc4363ad7fcf7ec75be07d241ae670c1f2e/drake/common/eigen_autodiff_limits.h#L7)):*
> ```objc
> If you see a 'duplicate specialization' compiler error here, then Eigen must have
> started providing this itself; conditionalize or remove Drake's own specialization.
> */
> ```

BTW I would add to a link to the Eigen pull request on Bitbucket, but it is not essential.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-KmWaSMr10Uy8rvMFH-m:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review (assuming I am remembering the rotation correctly).

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/eigen_autodiff_limits.h, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-KmX56LAxzAA7KVKzQX_:-KmX56LBgdnLrEztm14p:b-s5ythn) ([raw file](https://github.com/robotlocomotion/drake/blob/ea8e9cc4363ad7fcf7ec75be07d241ae670c1f2e/drake/common/eigen_autodiff_limits.h#L5)):*
> ```objc
> #include <limits>
> /*
> If you see a 'duplicate specialization' compiler error here, then Eigen must have
> ```

long lines?  (maybe?  It's wrapping in reviewable but seems to be passing cpplint?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/eigen_autodiff_limits.h, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-KmX56LAxzAA7KVKzQX_:-KmX5tnyClPn76Q1bsEf:bo3fdfu) ([raw file](https://github.com/robotlocomotion/drake/blob/ea8e9cc4363ad7fcf7ec75be07d241ae670c1f2e/drake/common/eigen_autodiff_limits.h#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

long lines?  (maybe?  It's wrapping in reviewable but seems to be passing cpplint?)
</blockquote></details>

FYI `cpplint` only checks C++ comments, not C comments.  (Yes, this is super annoying, but hey, that's what we get for allowing an old bad comment format.)

Code review has to enforce this by hand until / unless we fix our linter(s).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294)*

**Comment by m-chaturvedi** [comment]
*[drake/common/eigen_autodiff_limits.h, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-KmWa8v9Ks99AsIfBXpD:-KmX8FS5Yo6EaYtXLkLt:brtq237) ([raw file](https://github.com/robotlocomotion/drake/blob/ea8e9cc4363ad7fcf7ec75be07d241ae670c1f2e/drake/common/eigen_autodiff_limits.h#L7)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW I would add to a link to the Eigen pull request on Bitbucket, but it is not essential.
</blockquote></details>

They declined the PR and merged it manually. 
Declined PR: https://bitbucket.org/eigen/eigen/pull-requests/308/auto-diff-scalar-bug/activity
Commit: https://bitbucket.org/eigen/eigen/commits/043c847d2c34/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294#-:-KmXBLAR-VrNfQCxocX5:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6294)*

**Pull request merged**
