### PR TITLE
Move ParsePositiveSemidefiniteConstraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Move it to aggregate_costs_constraints.h/cc, and the test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

This is going to be used for supporting PSD constraint in Clarabel.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-:-NisFgNy7iRot_2lsdAA:bjd9wui)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
I think a test where you parse the PSD/LMI constraints after having already parsed another constraint would be good since currently we don't check that the vectors A_triplets and b grow as expected.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-:-NitjJUICgnsftmJ7rqv:be7nzur)* status: 6 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 287 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-Nitg-SNDQaxBj97nZIy:-Nitg-SO60r-lEfbctG8:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.h#L287)):*
> ```objc
> // A * x + s = b
> // s in K
> // Note that SCS/Clarabel solver defines its psd cone with a √2 scaling on the
> ```

nit



_Suggestion:_
```objc
the SCS/Clarabel solver
```
___
*[`solvers/aggregate_costs_constraints.h` line 289 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NitgY9X7zcDCkXi5Jpw:-NitgY9X7zcDCkXi5Jpx:b-oix176) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.h#L289)):*
> ```objc
> // Note that SCS/Clarabel solver defines its psd cone with a √2 scaling on the
> // off-diagonal terms in the positive semidefinite matrix. Refer to
> // https://github.com/cvxgrp/scs for an explanation.
> ```

Can you make this point to a more explicit spot in the Scs documentation?

I found where this is explained in the Clarabel documentation here: https://oxfordcontrol.github.io/ClarabelDocs/stable/examples/example_sdp/



_Code quote:_
```objc
https://github.com/cvxgrp/scs
```
___
*[`solvers/aggregate_costs_constraints.h` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-Nith4k9E_vz6B7kJmuP:-Nith4k9E_vz6B7kJmuQ:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.h#L293)):*
> ```objc
> // prog.positive_semidefinite_constraints() and
> // prog.linear_matrix_inequality_constraints() will be appended to A_triplets.
> // @param[in/out] b THe righthand side of A*x+s=b.
> ```

nit



_Suggestion:_
```objc
The
```
___
*[`solvers/aggregate_costs_constraints.cc` line 646 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NithxlDAQNDkGxdmaQq:-NithxlE7bSIIJ1zy4bR:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L646)):*
> ```cpp
>     // ⎢    ...            ⎥
>     // ⎣-√2 -√2 -√2 ...  -1⎦
>     // The √2 scaling factor in the off-diagonal entries are required by SCS,
> ```





_Suggestion:_
```cpp
SCS and Clarabel
```
___
*[`solvers/aggregate_costs_constraints.cc` line 648 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-Niti44g78Ok1wfEfRnU:-Niti44g78Ok1wfEfRnV:ba9tiqd) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L648)):*
> ```cpp
>     // The √2 scaling factor in the off-diagonal entries are required by SCS,
>     // as it uses only the lower triangular part of the symmetric matrix, as
>     // explained in https://github.com/cvxgrp/scs
> ```

Ditto on pointing to a more specific link.



_Code quote:_
```cpp
https://github.com/cvxgrp/scs
```
___
*[`solvers/aggregate_costs_constraints.cc` line 658 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NitiW5H6kVWhRgfR29V:-NitiW5H6kVWhRgfR29W:b-poc49b) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L658)):*
> ```cpp
>     for (int j = 0; j < X_rows; ++j) {
>       A_triplets->emplace_back(
>           *A_row_count + x_index_count,
> ```

Should we be checking that `*A_row_count == *A_triplets.size()` at the beginning of this method? It seems that you rely on this fact in the emplace back?



_Code quote:_
```cpp
         *A_row_count + x_index_count,
```

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/aggregate_costs_constraints.h` line 289 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NitgY9X7zcDCkXi5Jpw:-NiuXN7q74ms2gpdnEnD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.h#L289)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can you make this point to a more explicit spot in the Scs documentation?

I found where this is explained in the Clarabel documentation here: https://oxfordcontrol.github.io/ClarabelDocs/stable/examples/example_sdp/
</blockquote></details>

Done.
___
*[`solvers/aggregate_costs_constraints.cc` line 646 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NithxlDAQNDkGxdmaQq:-NiuXayO2GMh-m58zz1j:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L646)):*
> ```cpp
>     // ⎢    ...            ⎥
>     // ⎣-√2 -√2 -√2 ...  -1⎦
>     // The √2 scaling factor in the off-diagonal entries are required by SCS,
> ```

Done.
___
*[`solvers/aggregate_costs_constraints.cc` line 648 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-Niti44g78Ok1wfEfRnU:-NiuXbQ535zmxvq6P3rB:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L648)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto on pointing to a more specific link.
</blockquote></details>

Done.
___
*[`solvers/aggregate_costs_constraints.cc` line 658 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-NitiW5H6kVWhRgfR29V:-NiuY4eL-7ecFvFzhXPM:b-whxfyt) ([raw file](https://github.com/RobotLocomotion/drake/blob/9e8f14b3ad56688b22c100b5c8bc8e4f3ee60025/solvers/aggregate_costs_constraints.cc#L658)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Should we be checking that `*A_row_count == *A_triplets.size()` at the beginning of this method? It seems that you rely on this fact in the emplace back?
</blockquote></details>

Done.

We actually want to know if the rows in A_triplets and size of `b` matches with A_row_count.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-:-Niuf3UHBOFrwlr-9Ijh:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-:-Nj8ipq17izDXaDUOsYn:bycyfct)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one small nit.

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-:-Nj97WZH6tuB9YbcW88z:bfgk9jn)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.cc` line 633 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/20517#-Nj94dqGD0SRBVMsWkI8:-Nj94dqGD0SRBVMsWkI9:bh8wzze) ([raw file](https://github.com/RobotLocomotion/drake/blob/41f308120483c4f8333cffd3ba0e68fb02ed76b4/solvers/aggregate_costs_constraints.cc#L633)):*
> ```cpp
>     std::vector<Eigen::Triplet<double>>* A_triplets, std::vector<double>* b,
>     int* A_row_count, std::vector<int>* psd_cone_length) {
>   DRAKE_ASSERT(ssize(*b) == *A_row_count);
> ```

nit: `DRAKE_DEMAND(psd_cone_length != nullptr);`

**Comment by SeanCurtis-TRI** [comment]
+(release notes: none)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20517)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),AlexandreAmice

**Pull request merged**
