### PR TITLE
multibody: implements DoCalcImplicitTimeDerivativesResidual for MBP

### LINKED ISSUE #13164: MultibodyPlant should override DoCalcImplicitTimeDerivativesResidual()
When PR #13068 lands, the System class will support CalcImplicitTimeDerivativesResidual(). The default implementation makes use of the existing EvalTimeDerivatives(), which is fine for most Systems. However, that is particularly bad for MultibodyPlant (and in fact defeats the whole purpose of the implicit time derivatives feature). Instead, MBPlant should override the implementation and use inverse dynamics to calculate the residual. `examples/acrobot`  (in #13068) shows a hand-written version of this -- MBPlant should do the same thing but in general.

Assigning initially to @amcastro-tri -- could be a good intro-to-MBP project for @joemasterjohn ?
cc @RussTedrake

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #13164

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@amcastro-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-M_jqtlABgfD1LP6Ymya:b5xll3r)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thank you @russtedrake. This is great. My only worry here is that your specific choices are not documented anywhere. How could we make them appear in the MultibodyPlant's docs for people to have as a reference?

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-M_uClJ_4oUDSJmE5z1l:bplvesu)* status: 7 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8YTC76EMdC8L6r1Z:-M_u8YTC76EMdC8L6r1_:b2vrd9g) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/examples/multibody/cart_pole/test/cart_pole_test.cc#L165)):*
> ```cpp
>       cart_pole_.AllocateImplicitTimeDerivativesResidual();
>   cart_pole_.CalcImplicitTimeDerivativesResidual(*context_, *xc_dot, &residual);
>   EXPECT_TRUE(CompareMatrices(residual, Eigen::VectorXd::Zero(4), 1e-12));
> ```

 is this the tightest we can go? did we loose that much precision? Could we use something closer to machine epsilon?
___
*[multibody/plant/test/multibody_plant_forward_dynamics_test.cc, line 185 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u96uT4Y1vsksa3T2V:-M_u96uT4Y1vsksa3T2W:b-a7hsvf) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L185)):*
> ```cpp
>   plant.CalcImplicitTimeDerivativesResidual(*context, *derivatives, &residual);
>   EXPECT_TRUE(CompareMatrices(
>       residual, Eigen::VectorXd::Zero(plant.num_velocities() * 2), 1e-12));
> ```

nit, ditto and very loose precision.
___
*[multibody/plant/test/multibody_plant_test.cc, line 734 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8qyjDomdNvtF6Q3K:-M_u8qyjDomdNvtF6Q3L:b-a7hsvf) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/multibody_plant_test.cc#L734)):*
> ```cpp
>                                                   &residual);
>     EXPECT_TRUE(CompareMatrices(residual, VectorXd::Zero(4), 1e-12));
>   }
> ```

nit, ditto and very loose precision.
___
*[multibody/plant/test/propeller_test.cc, line 155 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8mLC-zlJusp3qqVA:-M_u8mLC-zlJusp3qqVB:b-a7hsvf) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/propeller_test.cc#L155)):*
> ```cpp
>   diagram->CalcImplicitTimeDerivativesResidual(*context, *derivatives,
>                                                &residual);
>   EXPECT_TRUE(CompareMatrices(residual, Eigen::VectorXd::Zero(12), 1e-12));
> ```

nit, ditto and very loose precision.
___
*[multibody/tree/multibody_tree_system.cc, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uBnLREQ-TSxPlWXTT:-M_uBnLS3AV0pkb_hF7w:bpr0ie8) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L147)):*
> ```cpp
>                                  tree_->num_velocities(),
>                                  0 /* num_z */);
>     this->DeclareImplicitTimeDerivativesResidualSize(2*tree_->num_velocities());
> ```

why this choice? why not to write the implicit residual on qdot instead of v?
I am ok with whatever option is the one that makes sense. But this choice must be documented somewhere.
It might be worth moving this to MBP so that we can place appropriate documentations for this?
The `systems::` default is to have the residual of size num_continuous_states, so this choice will definitely catch users of guard if not documented.
___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-M_uCFh-1ZTzrmdYfZLT:b-74mnv5) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
> ```cpp
>   DRAKE_ASSERT(qvdot_proposed.size() == nq+nv);
> 
>   // N⁺(q)⋅q̇_proposed - v
> ```

I wonder why not  `q̇_proposed - N(q)⋅v` instead, which would match the default documented in `systems::`
___
*[multibody/tree/multibody_tree_system.cc, line 346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uC_fIDlOvtzMH3XmE:-M_uC_fIDlOvtzMH3XmF:b-2l6rl8) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L346)):*
> ```cpp
> 
>   // N⁺(q)⋅q̇_proposed - v
>   auto head = residual->head(nv);
> ```

nit, maybe a name like `vdot_residual` is more descriptive?

**Review by RussTedrake — COMMENTED** [review]
I wouldn't mind moving it to MultibodyPlant, but this would still be a private method (so would not generate public documentation).  I'm not actually sure where the best place to document it would be?  @sherm1, any suggestions?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-M_vCnOC-FsorBZ6Li3c:b-yp06ou)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri, @hongkai-dai, and @sherm1)

___
*[examples/multibody/cart_pole/test/cart_pole_test.cc, line 165 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8YTC76EMdC8L6r1Z:-M_vE0-94k0zfFCxnewV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/examples/multibody/cart_pole/test/cart_pole_test.cc#L165)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

 is this the tightest we can go? did we loose that much precision? Could we use something closer to machine epsilon?
</blockquote></details>

Done.
___
*[multibody/plant/test/multibody_plant_forward_dynamics_test.cc, line 185 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u96uT4Y1vsksa3T2V:-M_vE6HR1CDK7HOAJSuZ:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L185)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, ditto and very loose precision.
</blockquote></details>

Done
___
*[multibody/plant/test/multibody_plant_test.cc, line 734 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8qyjDomdNvtF6Q3K:-M_vEBttDmrg8YFUzX-V:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/multibody_plant_test.cc#L734)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, ditto and very loose precision.
</blockquote></details>

Done
___
*[multibody/plant/test/propeller_test.cc, line 155 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_u8mLC-zlJusp3qqVA:-M_vEGCz7LfrbQXR1wgd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/plant/test/propeller_test.cc#L155)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, ditto and very loose precision.
</blockquote></details>

Done
___
*[multibody/tree/multibody_tree_system.cc, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uBnLREQ-TSxPlWXTT:-M_vEJ7C305PMV0ROvqo:b-89doiy) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why this choice? why not to write the implicit residual on qdot instead of v?
I am ok with whatever option is the one that makes sense. But this choice must be documented somewhere.
It might be worth moving this to MBP so that we can place appropriate documentations for this?
The `systems::` default is to have the residual of size num_continuous_states, so this choice will definitely catch users of guard if not documented.
</blockquote></details>

discussing below.
___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-M_vB8o_3GIeAN3nNHd7:b-abxee5) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I wonder why not  `q̇_proposed - N(q)⋅v` instead, which would match the default documented in `systems::`
</blockquote></details>

I would like us to agree on which is more correct for this application.  There should be a right answer.  In my mind, one should do the comparison in the lower-dimensional velocity space, not in the 4d quaternion space, which should really be constrained to a manifold (but our residuals would be ignoring that fact).

cc @hongkai-dai and @sherm1 , who were discussing this wrt to our QuaternionIntegrationConstraint the other day, in case they want to weigh in.
___
*[multibody/tree/multibody_tree_system.cc, line 346 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uC_fIDlOvtzMH3XmE:-M_vCI5a9iPXLuNNBrQX:b-l1rd30) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L346)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, maybe a name like `vdot_residual` is more descriptive? 
</blockquote></details>

done. i agree that's better.  (except this is the residual of v, not vdot)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-M_vJr7R35KTEm_m-A1k:b717cgs) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I would like us to agree on which is more correct for this application.  There should be a right answer.  In my mind, one should do the comparison in the lower-dimensional velocity space, not in the 4d quaternion space, which should really be constrained to a manifold (but our residuals would be ignoring that fact).

cc @hongkai-dai and @sherm1 , who were discussing this wrt to our QuaternionIntegrationConstraint the other day, in case they want to weigh in.
</blockquote></details>

If I read the code correctly, it seems that q̇_proposed can be set by the user, it doesn't have to be computed from MBP, and hence it doesn't have to satisfy the constraint q̇_proposed ⊥ q_proposed due to the unit quaternion constraint. Is this right?

If so, then I think it is better to use q̇_proposed - N(q)⋅v. The reason is that N⁺(q)⋅q̇_proposed - v = 0 is a 3-dimensional constraint (it has 3 rows) on the 4-dimensional vector q̇_proposed, so when this residue is 0, the vector q̇_proposed is not fully constrained, it still has one degree of freedom in the nullspace of N⁺(q). Hence even if we find a q̇_proposed that makes this residue zero, it doesn't mean that we find the correct q̇_proposed satisfying q̇_proposed  = N(q)v, which is the correct quaternion dot for that given quaternion q and angular velocity v.

BTW, is the following argument always true (not only for quaternion, but for general position/velocity)?
```
N(q) is always a full column rank matrix
```
If yes, then we can guarantee that given q̇_proposed, there is at most one v satisfying q̇_proposed = N(q)v.

**Comment by sherm1** [comment]
@hongkai-dai I think you could say `N(q) is always a full column rank matrix except at singularities`. For example, if we use angular velocity as the generalized velocities v, but use rpy as the generalized positions q, then N(q) is singular when the pitch is 90 degrees. In any case I think your point is valid since we require the velocity variables (for the tree) to be independent but allow position variables to be redundant (as quaternions). So the number of velocity variables (columns of N) is <= the number of position variables always.
@mitiguy might be able to say something more precise?

**Review by amcastro-tri — COMMENTED** [review]
great analysis @hongkai-dai and @sherm1!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-M_vjazf1FblmiFlOH4g:b2cf04m)* status: 3 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-Ma-Gofs7_GEBDRwHBHZ:b-ph72mn) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If I read the code correctly, it seems that q̇_proposed can be set by the user, it doesn't have to be computed from MBP, and hence it doesn't have to satisfy the constraint q̇_proposed ⊥ q_proposed due to the unit quaternion constraint. Is this right?

If so, then I think it is better to use q̇_proposed - N(q)⋅v. The reason is that N⁺(q)⋅q̇_proposed - v = 0 is a 3-dimensional constraint (it has 3 rows) on the 4-dimensional vector q̇_proposed, so when this residue is 0, the vector q̇_proposed is not fully constrained, it still has one degree of freedom in the nullspace of N⁺(q). Hence even if we find a q̇_proposed that makes this residue zero, it doesn't mean that we find the correct q̇_proposed satisfying q̇_proposed  = N(q)v, which is the correct quaternion dot for that given quaternion q and angular velocity v.

BTW, is the following argument always true (not only for quaternion, but for general position/velocity)?
```
N(q) is always a full column rank matrix
```
If yes, then we can guarantee that given q̇_proposed, there is at most one v satisfying q̇_proposed = N(q)v.
</blockquote></details>

@russtedrake not sure we ever finished this discussion. I agree with Alejandro and Hongkai that the simpler residual q̇_proposed - q̇_actual is better. One significant advantage is that it is easier to explain! I don't think the choice matters a lot because the v̇ residual is the important one -- since we know v we always have an efficient explicit formula for q̇.

It occurs to me that MBP users may have a good reason to want to work only with the v̇ portion of the residual. If so, it would be important to document how the MBP residual vector is organized. The generic documentation says there is no correspondence between the entries in the residual and the ordering of the state variables. But here you could propose to segregate the q̇ residuals into the first nq elements, followed by the v̇ residuals in the final nv elements.

**Review by sherm1 — COMMENTED** [review]
I don't think there is any particular advantage at the moment to moving the implementation from MultibodyTreeSystem to MultibodyPlant. I'd leave it for now since it would be easy to move later if we had such a reason.

Regarding documentation, the API is defined by System rather than MBP so we don't automatically get a nice place to add MBP-specific docs. If you switch to using the default q̇_proposed-q̇_actual residual the need for specific documentation is reduced but per my comment below I think we still need to provide enough info for a user to separate the q̇ residuals from the v̇ ones. My suggestion would be to add that to the [Kinematics and Dynamics group](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#mbp_kinematic_and_dynamic_computations) in MBP's class documentation. You would have to add the documentation to the group comments since there won't be a method declaration to hang the documentation on. (Not sure if there is a way to trick doxygen into providing documentation for local behavior of an inherited API -- maybe a `using`?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-Ma-KhYh3P5XFYZmlyHh:btdgodd)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
could we somehow have a fake method signature in MBP guarded by `#ifdef DRAKE_DOXYGEN_CXX` or similar?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-Ma-u-Y3BiK3JREckeDl:b7fwf0k)* status: 2 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by RussTedrake — COMMENTED** [review]
Done.  I like that. (see image in discussion below)

Thanks all. I think this one is now ready.  PTAL.
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-MaNnv4H0eBzuxYluM38:b-tgjig1)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[multibody/tree/multibody_tree_system.cc, line 147 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uBnLREQ-TSxPlWXTT:-MaNej1X55OwhNbx2qpY:b9csktc) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L147)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

discussing below.
</blockquote></details>

changed this, per discussion.
___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-MaNnbRxAkNbB1LY8UBx:b-7x0dzy) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@russtedrake not sure we ever finished this discussion. I agree with Alejandro and Hongkai that the simpler residual q̇_proposed - q̇_actual is better. One significant advantage is that it is easier to explain! I don't think the choice matters a lot because the v̇ residual is the important one -- since we know v we always have an efficient explicit formula for q̇.

It occurs to me that MBP users may have a good reason to want to work only with the v̇ portion of the residual. If so, it would be important to document how the MBP residual vector is organized. The generic documentation says there is no correspondence between the entries in the residual and the ordering of the state variables. But here you could propose to segregate the q̇ residuals into the first nq elements, followed by the v̇ residuals in the final nv elements. 
</blockquote></details>

Done.  I've added this documentation using `ifdef DRAKE_DOXYGEN_CXX` per @amcastro-tri 's suggestion.

**Review by amcastro-tri — COMMENTED** [review]
Thanks Russ. :lgtm: 

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-MaTYPk93M4pYiq7LCQ5:birlxql)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake)

___
*[multibody/plant/multibody_plant.h, line 2676 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaTVLcW7Kh3YAC93q5D:-MaTVLcW7Kh3YAC93q5E:bqx8gre) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/multibody_plant.h#L2676)):*
> ```objc
> #ifdef DRAKE_DOXYGEN_CXX
> // This method is a private overload, but the MultibodyPlant overload needs
> // specific documentation.
> ```

nit, I would probably say a bit more: "N.B. CalcImplicitTimeDerivativesResidual() is an NVI implemented in MultibodyTreeSystem::DoCalcImplicitTimeDerivativesResidual(). To provide non-trivial specifics we provided Doxygen guarded documentation to appear in MultibodyPlant's public API."
___
*[multibody/tree/multibody_tree_system.h, line 320 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaTY2Jm-ftM9zVjlMhl:-MaTY2Jm-ftM9zVjlMhm:b-alf8r1) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/tree/multibody_tree_system.h#L320)):*
> ```objc
>       systems::VectorBase<T>* qdot) const final;
> 
>   // Public documentation for this overload can be found in multibody_plant.h.
> ```

nit, maybe "Public documentation for the NVI this overload implements can be found in MultibodyPlant::CalcImplicitTimeDerivativesResidual()."
___
*[multibody/tree/multibody_tree_system.cc, line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15048#-M_uCFh-1ZTzrmdYfZLS:-MaTWzU_3K1GZNj3he3e:b-83sjoh) ([raw file](https://github.com/robotlocomotion/drake/blob/55f9f5a3a9789dbb3667c45f5f5fcd9762a16027/multibody/tree/multibody_tree_system.cc#L345)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  I've added this documentation using `ifdef DRAKE_DOXYGEN_CXX` per @amcastro-tri 's suggestion.



</blockquote></details>

Nice!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: w/minor comments.

> Reviewed 2 of 5 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048#-:-MaV1upn-FRu-Im6ZuUD:b-nzccr9)* status: 4 unresolved discussions (waiting on @RussTedrake)

___
*[multibody/plant/multibody_plant.h, line 2691 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaUPdXK99iNRFD2q8CX:-MaUPdXK99iNRFD2q8CY:bnrjwar) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/multibody_plant.h#L2691)):*
> ```objc
>   /// @see systems::System::CalcImplicitTimeDerivativesResidual for more
>   /// details.
>   void CalcImplicitTimeDerivativesResidual(
> ```

BTW the documentation looks great! Does this also result in good pydocs?
___
*[multibody/plant/test/multibody_plant_forward_dynamics_test.cc, line 185 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaUQ-sa-6pKYQkMKnY9:-MaUQ-sa-6pKYQkMKnYA:bgbg35n) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L185)):*
> ```cpp
>   plant.CalcImplicitTimeDerivativesResidual(*context, *derivatives, &residual);
>   EXPECT_TRUE(CompareMatrices(
>       residual, Eigen::VectorXd::Zero(plant.num_multibody_states()), 1e-13));
> ```

nit: is this looser (1e-13) tolerance and empirical necessity? If so please consider mentioning that here.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15048)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[multibody/plant/multibody_plant.h, line 2676 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaTVLcW7Kh3YAC93q5D:-MaaXBVp26duE6iB3MVI:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/multibody_plant.h#L2676)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, I would probably say a bit more: "N.B. CalcImplicitTimeDerivativesResidual() is an NVI implemented in MultibodyTreeSystem::DoCalcImplicitTimeDerivativesResidual(). To provide non-trivial specifics we provided Doxygen guarded documentation to appear in MultibodyPlant's public API."
</blockquote></details>

Done
___
*[multibody/plant/multibody_plant.h, line 2691 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaUPdXK99iNRFD2q8CX:-MaaZBTS7HUYBZpW5zni:b-gw8bbk) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/multibody_plant.h#L2691)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the documentation looks great! Does this also result in good pydocs?
</blockquote></details>

No.  It turns out that whoever implemented System::CalcImplicitTimeDerivativesResidual didn't add the python bindings.  :-)  I'll do that in a follow-up PR.
___
*[multibody/plant/test/multibody_plant_forward_dynamics_test.cc, line 185 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaUQ-sa-6pKYQkMKnY9:-MaaZAIl8zcu7ukKApj9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/test/multibody_plant_forward_dynamics_test.cc#L185)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: is this looser (1e-13) tolerance and empirical necessity? If so please consider mentioning that here.
</blockquote></details>

Done.

**Comment by sherm1** [comment]
___
*[multibody/plant/multibody_plant.h, line 2691 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15048#-MaUPdXK99iNRFD2q8CX:-MadFaO31hjdd8LU7I9A:b-834n6v) ([raw file](https://github.com/robotlocomotion/drake/blob/d231b3df8887fb3a66081fa52fd142794255d2ee/multibody/plant/multibody_plant.h#L2691)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

No.  It turns out that whoever implemented System::CalcImplicitTimeDerivativesResidual didn't add the python bindings.  :-)  I'll do that in a follow-up PR.
</blockquote></details>

Oops!

**Pull request merged**
