### PR TITLE
[doc] Add release notes v1.33.0

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6MavesEK3v01DkwlqL:-O6MavesEK3v01DkwlqM:b3hqgjf) (no related file):*
Still need to:

- Remove extraneous TBD
- Update dates at the end of the week.

___
___
*[`doc/_release-notes/v1.33.0.md` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6Mb3EeD8SVyzvemT6x:-O6Mb3EeD8SVyzvemT6y:bs0k5s2) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be02cc8b25c016e301b6a0920a757b714e3b4a9/doc/_release-notes/v1.33.0.md#L53)):*
> ```Markdown
> 
> 
> * [feature] TBD Replace BodyIndex with LinkIndex alias ([#21811][_#21811])
> ```

@sherm1 I commented on the PR, but this is where it's relevant.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6Mb3EeD8SVyzvemT6x:-O6N52S-08T37EiuE4AD:b-b8x0cx) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be02cc8b25c016e301b6a0920a757b714e3b4a9/doc/_release-notes/v1.33.0.md#L53)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@sherm1 I commented on the PR, but this is where it's relevant.
</blockquote></details>

You're right that this change is entirely internal and shouldn't be mentioned here. My bad!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.33.0.md` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6Mb3EeD8SVyzvemT6x:-O6NE__836L7hDveexvI:b-zcjvte) ([raw file](https://github.com/RobotLocomotion/drake/blob/5be02cc8b25c016e301b6a0920a757b714e3b4a9/doc/_release-notes/v1.33.0.md#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

You're right that this change is entirely internal and shouldn't be mentioned here. My bad!
</blockquote></details>

Thanks

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 124 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6ScQYW-8to4lhM5Nfl:-O6ScQYW-8to4lhM5Nfm:b-s6gux7) ([raw file](https://github.com/RobotLocomotion/drake/blob/f86069eb41c0f6a261b98278af421907ef9efafe/doc/_release-notes/v1.33.0.md#L124)):*
> ```Markdown
> * `pydrake.multibody.MultibodyPlant.SetDefaultFreeBodyPose` with parameter X_WB ([#21808][_#21808])
> * `pydrake.multibody.MultibodyPlant.SetFreeBodySpatialVelocity` with parameter V_WB ([#21808][_#21808])
> ```

#21807 deprecates `CalcPairwiseIntersections` and introduces a replacement `ComputePairwiseIntersections` with a different return signature. Not sure what message makes the most sense (and whether you also want to include it in "New features", or just in "Newly-deprecated APIs").

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.33.0.md` line 124 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6ScQYW-8to4lhM5Nfl:-O6Suep2-U0oFOGRDzQT:bay4ip) ([raw file](https://github.com/RobotLocomotion/drake/blob/f86069eb41c0f6a261b98278af421907ef9efafe/doc/_release-notes/v1.33.0.md#L124)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

#21807 deprecates `CalcPairwiseIntersections` and introduces a replacement `ComputePairwiseIntersections` with a different return signature. Not sure what message makes the most sense (and whether you also want to include it in "New features", or just in "Newly-deprecated APIs").
</blockquote></details>

Thanks for calling this out. I'll do a refresh on this branch tomorrow to pick up changes since Monday morning and that should get included. I'll leave this topic open to make sure I don't miss it.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 124 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6ScQYW-8to4lhM5Nfl:-O6WZaaQ6E3CbLzFrcCo:bjqilvg) ([raw file](https://github.com/RobotLocomotion/drake/blob/f86069eb41c0f6a261b98278af421907ef9efafe/doc/_release-notes/v1.33.0.md#L124)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Alrighty. Taken care of officially.
</blockquote></details>

Does `drake::geometry::CalcPairwiseIntersections` encompass the python bindings? (The corresponding bindings have also been deprecated.)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 14 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WZ0cUELbbe-eHOTTF:-O6WZ0cUELbbe-eHOTTG:bdm74no) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L14)):*
> ```Markdown
> 
> * Changed return values for GraphOfConvexSets SolveShortestPath and SolveConvexRestriction functions to resolve inconsistencies ([#21833][_#21833])
> * Changed return value of GraphOfConvexSets::GetSolution*() to return std::nullopt rather than NaN ([#21843][_#21843])
> ```

Neither 21833 nor 21843 are a breaking change, since the `GraphOfConvexSets` class is documented as `@experimental`.

It might be an important change that merits a stronger-than-usual highlight somewhere in the notes, but we should do ourselves the disservice of claiming that we broke the rules in cases where we didn't.
___
*[`doc/_release-notes/v1.33.0.md` line 70 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WYdTC6UQkwcRhcU8K:-O6WYdTC6UQkwcRhcU8L:b38h9pa) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L70)):*
> ```Markdown
> New features
> 
> * Add PathEnergyCost to GCSTrajectoryOptimization ([#21810][_#21810])
> ```

nit The class name is camel `GcsTrajectoryOptimization` not scream `GCSTrajectoryOptimization`.  (Ditto throughout.)
___
*[`doc/_release-notes/v1.33.0.md` line 109 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WYIePCKnO_U7aRbxN:-O6WYIePCKnO_U7aRbxO:bj07b0i) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L109)):*
> ```Markdown
> 
> 
> * [fix] TBD [third_party,workspace] [workspace] Upgrade bazelisk to latest release v1.21.0 ([#21888][_#21888])
> ```

nit I like how 21888 is listed beside 21884 down below.  That means we can delete this line.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 14 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WZ0cUELbbe-eHOTTF:-O6W_9-00PHcG0kVTUt-:bkt7wir) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Neither 21833 nor 21843 are a breaking change, since the `GraphOfConvexSets` class is documented as `@experimental`.

It might be an important change that merits a stronger-than-usual highlight somewhere in the notes, but we should do ourselves the disservice of claiming that we broke the rules in cases where we didn't.
</blockquote></details>

*shouldn't

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 6 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 15 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WbKtOC3nagECD1VdO:-O6WbKtOC3nagECD1VdP:b4chex5) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L15)):*
> ```Markdown
> * Changed return values for GraphOfConvexSets SolveShortestPath and SolveConvexRestriction functions to resolve inconsistencies ([#21833][_#21833])
> * Changed return value of GraphOfConvexSets::GetSolution*() to return std::nullopt rather than NaN ([#21843][_#21843])
> * drake::multibody::FrameBase class removed ([#21853][_#21853])
> ```

Blocking the release until https://github.com/RobotLocomotion/drake/pull/21891 is merged.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[`doc/_release-notes/v1.33.0.md` line 15 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6WbKtOC3nagECD1VdO:-O6XVFY0B3T7UgmJSpUZ:b9i80oc) ([raw file](https://github.com/RobotLocomotion/drake/blob/50e0aa5f2525146352f7c8c435f9a534dbfe162f/doc/_release-notes/v1.33.0.md#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Blocking the release until https://github.com/RobotLocomotion/drake/pull/21891 is merged.
</blockquote></details>

This has merged to master now, to feel free to close this thread once you merge that in here -- at which point, this bullet should relocate from "breaking changes" down into "newly deprecated".

**Review by SeanCurtis-TRI — COMMENTED** [review]
Last call. I've updated for this morning's clean CI and will be cutting a release today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-:-O6fiPEh9Xm399xguDWD:b-db2bbc)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) +@jwnimmer-tri both.

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-:-O6fk5pdD6ga9OYa_qzK:bh9ciof)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6fjyJ_8pPAgqTBClRN:-O6fjyJ_8pPAgqTBClRO:b9ropwp) (no related file):*
nit Reminder that this PR also should change `doc/_pages/from_binary.md` as you proceed through the playbook, before merging.

___
___
*[`doc/_release-notes/v1.33.0.md` line 108 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6fkj3WEj0uMsGtGdFf:-O6fkj3WEj0uMsGtGdFg:bkaz7p7) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8d79bfee98c6993de3448af7038a1f3bc212b1/doc/_release-notes/v1.33.0.md#L108)):*
> ```Markdown
> 
> * Add Python bindings for drake::geometry::optimization::ConvexHull ([#21849][_#21849])
> * Bind Joint.kTypeName constants ([#21896][_#21896])
> ```

BTW Not a big deal, but if you like these two bullets could use a more uniform phrasing.  "Bind (thing)" is generally my favorite spelling.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.33.0.md` line 108 at r9](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6fkj3WEj0uMsGtGdFf:-O6fu1xs2PPhYQFLow70:b-vt477n) ([raw file](https://github.com/RobotLocomotion/drake/blob/7d8d79bfee98c6993de3448af7038a1f3bc212b1/doc/_release-notes/v1.33.0.md#L108)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Not a big deal, but if you like these two bullets could use a more uniform phrasing.  "Bind (thing)" is generally my favorite spelling.
</blockquote></details>

I had the same thought but ended up on "meh". I'll get around to it once I'm done  my current pass on the `MeshSource` stuff.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6fjyJ_8pPAgqTBClRN:-O6gdykK3zWKW_hPxMi-:b-bu91xm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Reminder that this PR also should change `doc/_pages/from_binary.md` as you proceed through the playbook, before merging.
</blockquote></details>

Updated

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6gdzwi5gc5epXWKYto:-O6gdzwi5gc5epXWKYtp:bi184ps) (no related file):*
Blocking. Waiting on successful wheel builds.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-O6gdzwi5gc5epXWKYto:-O6gz1cbAvo5j1ZFdifG:b-w28fry) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking. Waiting on successful wheel builds.
</blockquote></details>

Wheels succsesfully built.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21885#-:-O6gzExB5xE7MC6V7-ui:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
