### PR TITLE
Implement PoseStampedTPoseVectorTranslator

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This is to publish robotlocomotion::pose_stamped_t lcmtype using lcm::LcmPublisherSystem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6200)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@siyuanfeng-tri feature review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-:-KlP3cG27DwKnnjFV-Ms:b-jqru8h)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPA6yDUjpe6zpi84EK:-KlPA6yE5FVnvwf5eFuE:b-ypxpmw) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc#L37)):*
> ```cpp
>       pose_msg.pose.orientation.x,
>       pose_msg.pose.orientation.y,
>       pose_msg.pose.orientation.z);
> ```

do you want to normalize this? 

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBGln58y_QqW6Kkxi:-KlPBGloEueB-KDKo3dp:b-dgewlp) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L6)):*
> ```cpp
> 
> #include "drake/systems/rendering/pose_vector.h"
> #include <Eigen/Dense>
> ```

you probably don't need this. 

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBJRomKIFeO_unYlK:-KlPBJRomKIFeO_unYlL:bg7msui) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L7)):*
> ```cpp
> #include "drake/systems/rendering/pose_vector.h"
> #include <Eigen/Dense>
> #include <gtest/gtest.h>
> ```

this should go above string.h 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-:-KlPBRrDNIL5SMUWVxaj:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Thanks @siyuanfeng-tri. Addressed your comments. PTAL.

+@sammy-tri platform review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-:-KlPQBkmUn-9HnJ6zpNl:b-u524y9)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPA6yDUjpe6zpi84EK:-KlPQ5Qkq-yFa6nHmchY:basuyww) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc#L37)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

do you want to normalize this? 
</blockquote></details>

Oh, that's a good point. Thanks.

Done.

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBGln58y_QqW6Kkxi:-KlPCd4ubgDgNZrIcrl3:b-2wvyw3) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L6)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

you probably don't need this. 
</blockquote></details>

I thought I need this since Eigen is used in this .cc file. Am I wrong?

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBJRomKIFeO_unYlK:-KlPDxea22hJk7s67a4L:b-y1cp6g) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L7)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

this should go above string.h 
</blockquote></details>

I believe gtest should be below string, but I reordered `drake/systems/rendering/pose_vector.h`to comply with [this](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPA6yDUjpe6zpi84EK:-KlPQ_tAXMqmKqmlXp7_:bqajjm2) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc#L37)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Oh, that's a good point. Thanks.

Done.
</blockquote></details>

You could just do 
Quaternion<double> quat(w, x, y, z); 
quat.normalize(); 

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBGln58y_QqW6Kkxi:-KlPQr3WyrfLWZILqlN0:b-s4p682) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L6)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I thought I need this since Eigen is used in this .cc file. Am I wrong?
</blockquote></details>

I would expect eigen to be included much earlier upstream. anyway it's not a big deal. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPA6yDUjpe6zpi84EK:-KlPcL278XgF0mp9liB1:bkjqmd4) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/pose_stamped_t_pose_vector_translator.cc#L37)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

You could just do 
Quaternion<double> quat(w, x, y, z); 
quat.normalize(); 
</blockquote></details>

Good to know. Thanks!

Done.

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPBGln58y_QqW6Kkxi:-KlPbN6ZpUUE3UgacBte:b-rahmxp) ([raw file](https://github.com/robotlocomotion/drake/blob/bc3a2788bfc0594af15d4e44e6703ae93c3a96cb/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L6)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I would expect eigen to be included much earlier upstream. anyway it's not a big deal. 
</blockquote></details>

[This rule](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) says "You should include all the headers that define the symbols you rely upon".

So, I think this is the right thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/CMakeLists.txt, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPhZstlab85lAZh_Hq:-KlPhZsupsbPG_GFiChi:bu61ot3) ([raw file](https://github.com/robotlocomotion/drake/blob/f7f1ae6246eccd44164cf8cf0cc2d1bf72e9fcf0/drake/systems/rendering/CMakeLists.txt#L45)):*
> ```CMake
>       TARGET drakeRenderingLcm
>       LIBS -ldrakeRenderingLcm
>       REQUIRES
> ```

We added drakeLcmSystem to target_link_libraries above but not here.  I think one of those is probably incorrect?

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPgjE0uxVFljPdXGcf:-KlPgjE1uKbbjIp0N6rf:bdk5z70) ([raw file](https://github.com/robotlocomotion/drake/blob/f7f1ae6246eccd44164cf8cf0cc2d1bf72e9fcf0/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L23)):*
> ```cpp
>  public:
>   PoseStampedTPoseVectorTranslatorTest()
>       : kFrameName("foo"),
> ```

I believe that kConstant naming should only apply to variables of static storage duration, which these are not.  https://google.github.io/styleguide/cppguide.html#Constant_Names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200)*

**Comment by kunimatsu-tri** [comment]
@sammy-tri addressed your comments. PTAL.

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/CMakeLists.txt, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPhZstlab85lAZh_Hq:-KlPlcHfiboAyBjxPFro:b-5zx7qz) ([raw file](https://github.com/robotlocomotion/drake/blob/f7f1ae6246eccd44164cf8cf0cc2d1bf72e9fcf0/drake/systems/rendering/CMakeLists.txt#L45)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

We added drakeLcmSystem to target_link_libraries above but not here.  I think one of those is probably incorrect?
</blockquote></details>

Thanks, good catch!

Done.

---

*[drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-KlPgjE0uxVFljPdXGcf:-KlPk9LFdwNgAgmTG1P8:bpvib1o) ([raw file](https://github.com/robotlocomotion/drake/blob/f7f1ae6246eccd44164cf8cf0cc2d1bf72e9fcf0/drake/systems/rendering/test/pose_stamped_t_pose_vector_translator_test.cc#L23)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I believe that kConstant naming should only apply to variables of static storage duration, which these are not.  https://google.github.io/styleguide/cppguide.html#Constant_Names
</blockquote></details>

Thanks. Done.

Also, removed unnecessary member variables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-:-KlPln4T91qYW0A4Q-14:b40cm97)*

**Comment by sammy-tri** [comment]
:lgtm: pending CI

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6200#-:-KlPmSFsCLuDsO8X8f9O:b3cfjge)*

**Pull request merged**
