### PR TITLE
Various Homebrew setup improvements

### PR DESCRIPTION
**Pull request by jamiesnape**
A subset of #14492, since I want to narrow the scope and simplify that PR.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14496)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release  please.

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14496#-:-MQNXmwX7zFiMOcq3mNJ:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with one minor comment on traceability. Feel free to ignore ofc.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14496#-:-MQNhvq55LD4oVhP3eHV:bj7cdl8)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform)

___
*[setup/mac/binary_distribution/install_prereqs.sh, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14496#-MQNheXr18WzIuwBpIm0:-MQNheXt-RMPYjh2kw9c:bc27a1r) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce9a16a3511882f3012a71325ff2ee1a10a4576/setup/mac/binary_distribution/install_prereqs.sh#L19)):*
> ```Shell
> if ! command -v brew &>/dev/null; then
>   /bin/bash -c \
>     "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
> ```

BTW As a non-Homebrew user, I'm not sure why `HEAD` is any more secure than `master` - why not a concrete git sha?

Can you include a brief cross-reference that motivated this change?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14496)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform)

___
*[setup/mac/binary_distribution/install_prereqs.sh, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14496#-MQNheXr18WzIuwBpIm0:-MQNkKxG74W5y45cnVwW:bwqdt5o) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce9a16a3511882f3012a71325ff2ee1a10a4576/setup/mac/binary_distribution/install_prereqs.sh#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW As a non-Homebrew user, I'm not sure why `HEAD` is any more secure than `master` - why not a concrete git sha?

Can you include a brief cross-reference that motivated this change?
</blockquote></details>

Because that is all they support: https://brew.sh. Probably they are preparing to rename `master` to `main`, but passing a specific SHA would not keep up with the syntax in the formula repos. Also, note that the install is interactive, so a user needs to affirm several questions.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14496)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),EricCousineau-TRI(platform)

___
*[setup/mac/binary_distribution/install_prereqs.sh, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14496#-MQNheXr18WzIuwBpIm0:-MQNlZ-X3UneJZKY-ujN:b-pao80c) ([raw file](https://github.com/robotlocomotion/drake/blob/3ce9a16a3511882f3012a71325ff2ee1a10a4576/setup/mac/binary_distribution/install_prereqs.sh#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Because that is all they support: https://brew.sh. Probably they are preparing to rename `master` to `main`, but passing a specific SHA would not keep up with the syntax in the formula repos. Also, note that the install is interactive, so a user needs to affirm several questions.
</blockquote></details>

OK SGTM. Thanks for the explanation.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Mac build was killed early to save Jenkins.

**Pull request merged**
