### PR TITLE
Adds diffstat to install_prereqs.sh

### PR DESCRIPTION
**Pull request by agalbachicar**
This PR adds `diffstat` to `install_prereqs.sh` script. Ubuntu 16.04 comes with it but base docker image does not. `drake/tools/prstat` is using it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7246)

### CODE REVIEW

**Comment by agalbachicar** [comment]
+@jwnimmer-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFnZ5CDGSMSkNTjcI8:bs3tquo)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-KwFtP7-ATh-sgALVI2F:-KwFtP7-ATh-sgALVI2G:b-tfc49t) (no related file):*
Waiting on CI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFtMwRPoKNcyb7DW4N:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@soonho-tri , platform :lgtm: in case you need it.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFwEyPc6YFTzyiWmaE:b-un7300)*

**Comment by soonho-tri** [comment]
BTW/FYI, `setup/mac/install_prereqs.sh` doesn't include `diffstat` either.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFwdNYENhDc9v2GJI_:b-3hh5zo)*

**Comment by agalbachicar** [comment]
Ah, I don't have any experience with mac. Adding it before doxygen is enough? 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFyJ96dEl5vq3D5SMF:b-orn3pk)*

**Comment by soonho-tri** [comment]
I think that should be good. Thank you.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwFzJhloEBpBImziyzV:bhn1h4j)*

**Comment by agalbachicar** [comment]
Done. PTAL.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwGTNJqQFYX_7IwdhHY:b-qsvnoa)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246#-:-KwGUK7Xzf0UI8zPLwr4:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
For the record, the `-unprovisioned` test passed https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-xenial-unprovisioned-clang-bazel-experimental/23/.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7246)*

**Pull request merged**
