### PR TITLE
[workspace] Add rust_toolchain externals

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19449.

Successfully tested locally against Anzu and `drake-external-examples/drake_bazel_external`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20325)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nittery

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-:-NgLf2fX0wKsx88xXLjn:bb62doi)* status: 4 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/rust_toolchain/upgrade.sh` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLae4lDmcYKGR17jdn:-NgLae4lDmcYKGR17jdo:bmp7jes) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

nit food for thought: as much as I love a good bash script, this one approaches the length and complexity where the @EricCousineau-TRI voice in my head says: "did you mean to write this in python?".

FWIW, I did a little exercise of trying to isolate the file-output statements in functions (effectively subshells) to reduce the `>> blah` spam. It might still be worth it, but I got fatigued trying to follow bash quoting rules. That's when I started thinking "hmm, maybe python".
___
*[`tools/workspace/rust_toolchain/upgrade.sh` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLcL042-oz2UTzmPAc:-NgLcL042-oz2UTzmPAd:b-j139lp) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade.sh#L30)):*
> ```Shell
>   echo 'name = "'${name}'",' >> ${bzl}
>   echo 'build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.'${name}'.bazel"),' >> ${bzl}
>   json=${external}/${name}/download_and_extract.json
> ```

nit I'm feeling like the quoting treatment of `${name}` is inconsistent -- I didn't study the input possibilities enough to decide if it is a real hazard.
___
*[`tools/workspace/rust_toolchain/upgrade.sh` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLeEhi9ossoX0dEcNx:-NgLeEhi9ossoX0dEcNy:btvlt3j) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade.sh#L45)):*
> ```Shell
> 
> # Clean up
> rm -rf upgrade.output_base
> ```

nit consider a `trap EXIT` cleanup mechanism. Developers can disable if needed during development.
___
*[`tools/workspace/rust_toolchain/upgrade/WORKSPACE.bazel` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLe5m95JBKB0JfH5eA:-NgLe5m95JBKB0JfH5eB:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade/WORKSPACE.bazel#L1)):*
> ```Starlark
> # Drake mainters use this repository to instrument the rust_toolchain
> ```

typo



_Suggestion:_
```Starlark
maintainers
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20325)* status: needs at least two assigned reviewers

___
*[`tools/workspace/rust_toolchain/upgrade.sh` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLae4lDmcYKGR17jdn:-NgMOLMYCzSg-X8AKhTf:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade.sh#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit food for thought: as much as I love a good bash script, this one approaches the length and complexity where the @EricCousineau-TRI voice in my head says: "did you mean to write this in python?".

FWIW, I did a little exercise of trying to isolate the file-output statements in functions (effectively subshells) to reduce the `>> blah` spam. It might still be worth it, but I got fatigued trying to follow bash quoting rules. That's when I started thinking "hmm, maybe python".
</blockquote></details>

Done.
___
*[`tools/workspace/rust_toolchain/upgrade.sh` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgLeEhi9ossoX0dEcNx:-NgMOHi-2zY8mY6DEJmU:b2cust) ([raw file](https://github.com/RobotLocomotion/drake/blob/759b75cfc5b52603dc9e94e9157e491d626da3fe/tools/workspace/rust_toolchain/upgrade.sh#L45)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider a `trap EXIT` cleanup mechanism. Developers can disable if needed during development.
</blockquote></details>

Done (via comment explaining why not).

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule (tomorrow), please.

**Review by sherm1 — COMMENTED** [review]
I looked through all the manually-written files. The complexity and maybe brittleness(?) of this surprised me. I trust that's appropriate but don't have sufficient build system expertise to evaluate that myself. If you think it needs a deeper big picture look, please find a more build-savvy platform reviewer. Otherwise, platform :lgtm:

> Reviewed 6 of 19 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-:-NgUjioU2r0DWOnGYjp4:b-6j72no)* status: 1 unresolved discussion

___
*[`tools/workspace/rust_toolchain/upgrade/BUILD.bazel` line 0 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-NgUjAQu4VO5fnteiTEL:-NgUjAQu4VO5fnteiTEM:b-6sflai) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1f619c8ffe1af0ee811fd6a3fab40b0ac9a4783/tools/workspace/rust_toolchain/upgrade/BUILD.bazel#L0)):*
BTW this file is empty. Is that intentional?

**Review by jwnimmer-tri — COMMENTED** [review]
Yeah.  Downloading a compiler suite on demand from the internet (because our operating system doesn't have a sufficiently new version) is somewhat burdensome.  There's no real way around that, though.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20325#-:-NgUmRia6HQ-qH9MZRvj:b-m1fvh4)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Comment by jwnimmer-tri** [comment]
The other thing I should have remarked was that the toolchain dependency is currently _optional_.  Only users who opt-in to beta test the Clarabel solver will be impacted by any problems here.

**Pull request merged**
