### PR TITLE
Fix for build errors introduced post #4370

### PR DESCRIPTION
**Pull request by naveenoid**
Simply fixes the Schunk PR code to comply with the changes in #4370 

+@liangfok For feature review

+@david-german-tri for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4384)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri -@liangfok -@david-german-tri :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4384#-:-KYJJs3wA2hhi--8nNTl:brhcna1)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4384#-:-KYJK9GjDZ-XERgQdpZS:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Jenkins might not be building -- everything is "triggered" but not started.  If it's not up in a few minutes, please fire off a retest.

**Comment by liangfok** [comment]
I'm not even seeing this PR in the queue for [linux-gcc-ninja-experimental](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental/). Should it at least appear?

screenshot from 2016-12-06 08 46 22

**Comment by naveenoid** [comment]
:( 

@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4384#-:-KYJNeD33vjuY5-JlbAb:b-a5lff0)*

**Comment by liangfok** [comment]
The "details" link for [linux-clang-ninja-experimental-open-source](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-clang-ninja-experimental-open-source/) hasn't appeared yet but at least this PR seems to be in the queue:

screenshot from 2016-12-06 08 49 09

**Comment by jwnimmer-tri** [comment]
The matlab build is still going, but is not relevant for this PR.  The open-source-debug build is running tests and almost done, but should be subsumed by the other green builds.  Using override-merge to get master working again.

**Pull request merged**
