### PR TITLE
Add BezierCurve::GetExpression()

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@RussTedrake for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NT5vBCdCst3wnveS49l:bn3gxtq)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: -- just a few small requests.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NT8Z3_UEiOVSjaRs_fz:bwrpabr)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.h` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NT8Y8CHA9uMw8GUpHpL:-NT8Y8CHA9uMw8GUpHpM:b5b0pkq) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1f9ea925fcbc0c44f800a05c82aada9fd0d14a8/common/trajectories/bezier_curve.h#L70)):*
> ```objc
> 
>   /** Evaluates the curve at the given time with the option to avoid the default
>    behavior of clamping time. This can be particularly useful when attempting
> ```

could we add just a little more detail / context here?  In the docstring for value it is more clear what "clamping time" means.  I think saying something more verbose like that will help the more casual readers.
___
*[`common/trajectories/test/bezier_curve_test.cc` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NT8YXyk9ZnP85W2_DnD:-NT8YXylEi9q2LMtgGTf:b-f1ldb0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1f9ea925fcbc0c44f800a05c82aada9fd0d14a8/common/trajectories/test/bezier_curve_test.cc#L92)):*
> ```cpp
>         CompareMatrices(curve.value(sample_time, false),
>                         Eigen::Vector2d((1 - sample_time) * (1 - sample_time),
>                                         sample_time * sample_time),
> ```

Could we add a few line test to check the behavior you wanted / promised in the doc string?  Show that for a `BezierCurve<Expression>` you can call `value(..., false)` and get an `Expression` for which `is_polynomial() == true`?  

(that will help ensure that this remains true even as others make changes to the code!)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`common/trajectories/bezier_curve.h` line 70 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NT8Y8CHA9uMw8GUpHpL:-NT9Pz9a7PsESeMfxWSx:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1f9ea925fcbc0c44f800a05c82aada9fd0d14a8/common/trajectories/bezier_curve.h#L70)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

could we add just a little more detail / context here?  In the docstring for value it is more clear what "clamping time" means.  I think saying something more verbose like that will help the more casual readers.
</blockquote></details>

Done.
___
*[`common/trajectories/test/bezier_curve_test.cc` line 92 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NT8YXyk9ZnP85W2_DnD:-NT9QHF22JBU07IL_Eof:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e1f9ea925fcbc0c44f800a05c82aada9fd0d14a8/common/trajectories/test/bezier_curve_test.cc#L92)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Could we add a few line test to check the behavior you wanted / promised in the doc string?  Show that for a `BezierCurve<Expression>` you can call `value(..., false)` and get an `Expression` for which `is_polynomial() == true`?  

(that will help ensure that this remains true even as others make changes to the code!)
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NT9YFT6CRDFXmqiWYkc:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
As I read this PR, it feels like the purpose is to be able to get the polynomial underlying Bezier curve and this particular implementation is a roundabout way of doing it that. Is that right?

I'd propose the following:

1. Move *most* of the body of `value()` into a private function: call it `EvaluateT()` (the clamping is left behind).
2. The current body of `value()` calls two things: `clamp()` and `EvaluateT()`.
3. Add a new public method called something like: `GetBezierExpression`.
    - It could be `SFINAE`'d into only supporting `T = Expression` or it could do a conversion under the hood to return an expression based on arbitrary T-valued `BezierCurve`s.
    - It could hard-code the variable `t` or it could request the independent variable (with a default value of a variable `t`).

This eliminates the weird semantics of unclamping `t` for the other cases and makes the use case of the new function abundantly clear (and possibly more general if you chose to support arbitrary T).

Let me know if these thoughts aren't clear or if you'd like some help as to what that might look like. I'm happy to push a PR against your PR so you can see what I mean in more concrete terms.

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTEcFFI5yCHy03y5DXX:b-oigj2e)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEdS2e5YRdlE4CuLXR:-NTEdS2f1tj29poa6eO0:be2nf9x) (no related file):*
BTW Do you have an *explicit* plan vis a vis python bindings? I'm not sure if its absence is part of a strategy or oversight.

___
___
*[`common/trajectories/bezier_curve.h` line 69 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEUTaI55CxIn9GoUTC:-NTEUTaI55CxIn9GoUTD:b-jtcebb) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/bezier_curve.h#L69)):*
> ```objc
>   MatrixX<T> value(const T& time) const override;
> 
>   /** Evaluates the curve at the given time. If clamp_time is true and t does
> ```

BTW this could be simplified and expressed in terms of the *other* implementation without duplicating documentation.

```c++
  /** Evaluates the curve at the given time.
   
   Calling `value(t, true)` is equivalent to calling `value(t)` (see above).

   If `T = symbolic::Expression`, passing `clamp_time = false` has the effect of
   extracting the underlying polynomial expression of this curve. */
```
___
*[`common/trajectories/bezier_curve.h` line 72 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEU-hP5fZFN3Ct9iHW:-NTEU-hP5fZFN3Ct9iHX:b-qqo1ev) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/bezier_curve.h#L72)):*
> ```objc
>    not lie in the range [start_time(), end_time()], the trajectory will silently
>    be evaluated at the closest valid value of time to `time`. For example,
>    `value(-1)` will return `value(0)` for a trajectory defined over [0, 1]. When
> ```

nit: You omitted the required argument. (Although, if you like my previous suggestion, this would simply evaporate.)



_Suggestion:_
```objc
value(-1, true)
```
___
*[`common/trajectories/bezier_curve.h` line 74 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEVI0V4SWpc90O9mQF:-NTEVI0V4SWpc90O9mQG:b-l45mnf) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/bezier_curve.h#L74)):*
> ```objc
>    `value(-1)` will return `value(0)` for a trajectory defined over [0, 1]. When
>    the curve is of type Expression, calling this method with time =
>    symbolic::Variable("t") and clamp_time = false enables the extraction of the
> ```

Extraction of the polynomial seems to be the *point* of this function.

1. Are there any warnings we should offer up when `T != symbolic::Expression`? Perhaps that the result is meaningless?
2. Had you considered making this a `T = symbolic::Expression` only sugar function that more directly just returns the polynomial expression in `t`? Or is there utility of this function beyond that application?
___
*[`common/trajectories/bezier_curve.cc` line 42 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEZ1_3C5m8yAuFnJW6:-NTEZ1_42wYeOHiqtenv:b-vbhcce) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/bezier_curve.cc#L42)):*
> ```cpp
> MatrixX<T> BezierCurve<T>::value(const T& time, bool clamp_time) const {
>   using std::clamp;
>   const T ctime = clamp_time ? clamp(time, T{start_time_}, T{end_time_}) : time;
> ```

The ternary operator is causing me mild concern. This may add more weight to the idea of rather than adding a general solution (stop clamping) to get a particular purpose (polynomial expression), the true answer may be to simply give a function that returns the polynomial expression without all of the concomitant traps of the general solution.
___
*[`common/trajectories/test/bezier_curve_test.cc` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTE_3a04dkN4yKbxmN5:-NTE_3a04dkN4yKbxmN6:b-f2i9ex) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/test/bezier_curve_test.cc#L38)):*
> ```cpp
>       curve_sym.value(symbolic::Variable("t"), false)};
>   for (int i = 0; i < curve_sym_expression.rows(); i++) {
>     EXPECT_TRUE(curve_sym_expression(i).is_polynomial());
> ```

BTW Is this test sufficient to support the documented purpose (polynomial expression of curve)? These properties are necessary, but are they sufficient? It feels like it would be nice if there were *one* test that actually looked at the expression and said, "Yep. That's the expected expression." (Coupled with arguments along the lines of, "if it worked for this simple, low-order example, we have a reasonable basis to believe it works equally well for high-order scenarios.")

However, I'm willing to stipulate that might be overly naive and there's a very cogent argument for why the correctness of these tested properties implies the correctness of the full assertion. If you're testing strategy relies on this kind of argument, you'd do your future readers a service in presenting it.
___
*[`common/trajectories/test/bezier_curve_test.cc` line 96 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTEaSPR-A8q2byFR-dc:-NTEaSPR-A8q2byFR-dd:b-aa8esl) ([raw file](https://github.com/RobotLocomotion/drake/blob/c91e025be51d6da61cef7eb3df4e511334b415f8/common/trajectories/test/bezier_curve_test.cc#L96)):*
> ```cpp
>                                 Eigen::Vector2d((1 - t) * (1 - t), t * t),
>                                 1e-14));
>     EXPECT_TRUE(CompareMatrices(curve.value(sample_time, true),
> ```

btw: This assertion is an equivalent spelling of the previous test. It would be really nice if the quantity `Eigen::Vector2d(1 - t) * (1 - t), t * t)` were captured in a local variable and used both times. That would strongly underscore the equivalency of the two calls.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTEeV2s6PsGKPihfVtM:b-l8xbmn)* status: 7 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Lookin' good. Probably worth getting a refresh on feature review with the significant changes. I'd also suggest curating your commits so we can see what the new commit message will be.

> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTPmXiy9tIg9XQExUx7:byr16rk)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`common/trajectories/test/bezier_curve_test.cc` line 143 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTPlnNd0XIfQnrgDZjQ:-NTPlnNd0XIfQnrgDZjR:b-asrsw5) ([raw file](https://github.com/RobotLocomotion/drake/blob/0baeb3f9d696477c3226519ababe1171d626a709/common/trajectories/test/bezier_curve_test.cc#L143)):*
> ```cpp
> 
>   // Tests that the call to GetExpression returns a polynomial of appropriate
>   // degree and that all scalar types return the same expression. Whether the
> ```

BTW Worth noting that this works because the times and control points of the Bezier curves don't include variables?
___
*[`common/trajectories/test/bezier_curve_test.cc` line 157 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTPlNUz7VD_ZFBjKmiL:-NTPlNUz7VD_ZFBjKmiM:b-yhpi5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/0baeb3f9d696477c3226519ababe1171d626a709/common/trajectories/test/bezier_curve_test.cc#L157)):*
> ```cpp
>             curve_sym.GetExpression(t)};
>         const VectorX<symbolic::Expression> curve_expression_double{
>             curve_sym.GetExpression(t)};
> ```

nit: some copypasta here. I'm pretty sure only one of these should invoke `curve_sym` and the others should be `curve` and `curve_ad`.
___
*[`bindings/pydrake/test/trajectories_test.py` line 106 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTPm7fA6Yw0bHNUgJpE:-NTPm7fA6Yw0bHNUgJpF:bchi8a) ([raw file](https://github.com/RobotLocomotion/drake/blob/ac84ac24de31f170a394564f122f2ad3217e2fc0/bindings/pydrake/test/trajectories_test.py#L106)):*
> ```Python
> 
>         curve_expression = curve.GetExpression(time=Variable("t"))
>         self.assertEqual(curve_expression.shape, (2,1))
> ```

BTW You don't have to test for the correctness of the `curve_expression`'s contents. You could simply assert that the return value *is* a matrix of expressions.

**Review by AlexandreAmice — COMMENTED** [review]
@RussTedrake could you refresh the feature review for this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTPvQr56IQ59HefLbP0:bso30qq)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTPxswt2her9YCoUASa:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/test/trajectories_test.py` line 106 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTPy2tx1PzUXQYp8T2H:-NTPy2tx1PzUXQYp8T2I:by1eyj0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5596793a61f9f47952492fd7c02a5c226d4f79c/bindings/pydrake/test/trajectories_test.py#L106)):*
> ```Python
> 
>         curve_expression = curve.GetExpression(time=Variable("t"))
>         self.assertEqual(curve_expression.shape, (2,1))
> ```

nit: A comma between 2 and 1 is what CI is complaining about.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.cc` line 66 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTQCcGB87XBNwbry1o_:-NTQCcGB87XBNwbry1oa:bqvlli9) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5596793a61f9f47952492fd7c02a5c226d4f79c/common/trajectories/bezier_curve.cc#L66)):*
> ```cpp
>     MatrixX<symbolic::Expression> ret{EvaluateT(symbolic::Expression(time))};
>     for (int i = 0; i < ret.rows(); ++i) {
>       for (int j = 0; j < ret.rows(); ++j) {
> ```

nit: I think this is your crash.



_Suggestion:_
```cpp
ret.cols();
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@hongkai-dai for follow up feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTVhM460k11TUKibhAW:b-j9yv1l)* status: LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r4, 1 of 3 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTVo3mR4wb17WgQZSyW:bg7igkv)* status: 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.h` line 71 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTVknvU2vEVgicb6H5J:-NTVknvU2vEVgicb6H5K:bm6vft5) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb5f3969af257e99722454427965e7c34422fdaf/common/trajectories/bezier_curve.h#L71)):*
> ```objc
>   /** Extracts the expanded underlying polynomial expression of this curve in
>    terms of variable `time`. */
>   MatrixX<symbolic::Expression> GetExpression(
> ```

Curious why this return `Matrix<symbolic::Expression>` instead of `VectorX<symbolic::Expression>`. My understanding is that the value is always an Eigen vector at each instance in time.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.h` line 73 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTVsTSx0OnEYnZS0dub:-NTVsTSx0OnEYnZS0duc:b-wxxuea) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb5f3969af257e99722454427965e7c34422fdaf/common/trajectories/bezier_curve.h#L73)):*
> ```objc
>   MatrixX<symbolic::Expression> GetExpression(
>       symbolic::Variable time = symbolic::Variable("t")) const;
> ```

BTW, why not to pass `time` by const reference here?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 1 unresolved discussion (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`common/trajectories/bezier_curve.h` line 71 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTVknvU2vEVgicb6H5J:-NTWlXhVE-PLG7QF9d1j:bv1fyjc) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb5f3969af257e99722454427965e7c34422fdaf/common/trajectories/bezier_curve.h#L71)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why this return `Matrix<symbolic::Expression>` instead of `VectorX<symbolic::Expression>`. My understanding is that the value is always an Eigen vector at each instance in time.
</blockquote></details>

It is so that it matches the return type of `value` and `EvaluateT`. Not sure if that is important or not.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.h` line 71 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTVknvU2vEVgicb6H5J:-NTZtlep0gWvpO-nNeTz:bh0ywo) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb5f3969af257e99722454427965e7c34422fdaf/common/trajectories/bezier_curve.h#L71)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

It is so that it matches the return type of `value` and `EvaluateT`. Not sure if that is important or not.
</blockquote></details>

I see, I think we want `value` to return MatrixX because it is inherited from the base class `Trajectory`. I am not sure if we want `EvaluateT` and `GetExpression` to return `MatrixX` as well? It seems more accurate to return `VectorX` for these two methods?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`common/trajectories/bezier_curve.h` line 71 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTVknvU2vEVgicb6H5J:-NTZwovn-T1ffu7KIcnZ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/bb5f3969af257e99722454427965e7c34422fdaf/common/trajectories/bezier_curve.h#L71)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, I think we want `value` to return MatrixX because it is inherited from the base class `Trajectory`. I am not sure if we want `EvaluateT` and `GetExpression` to return `MatrixX` as well? It seems more accurate to return `VectorX` for these two methods?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTZyFWzEt-yC-_R1INo:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai,RussTedrake(platform) (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
A bit of clean up due to the change of return type.

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-:-NTZzig8Eh9GhN_PKLLI:bqas8mh)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[`common/trajectories/bezier_curve.cc` line 65 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTZzEFR1Z0O1-_huDmU:-NTZzEFR1Z0O1-_huDmV:bl0dg9m) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3d1111331e26f4ecc4a4d7b3b8b23d4214a634f/common/trajectories/bezier_curve.cc#L65)):*
> ```cpp
>   } else {
>     VectorX<symbolic::Expression> ret{EvaluateT(symbolic::Expression(time))};
>     for (int i = 0; i < ret.rows(); ++i) {
> ```

nit: This shouldn't be rows *and* cols anymore. "Yes" for the control points. "No" for the return value.
___
*[`bindings/pydrake/test/trajectories_test.py` line 106 at r10](https://reviewable.io/reviews/RobotLocomotion/drake/19205#-NTZzccM43y4sQQG0EjZ:-NTZzccM43y4sQQG0Ej_:b-lveomt) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3d1111331e26f4ecc4a4d7b3b8b23d4214a634f/bindings/pydrake/test/trajectories_test.py#L106)):*
> ```Python
> 
>         curve_expression = curve.GetExpression(time=Variable("t"))
>         self.assertEqual(curve_expression.shape, (2, 1))
> ```

nit: Your CI failure is here. The shape is no longer (2, 1). Now it's simply (2, ).

**Pull request merged**
