### PR TITLE
Remove support for Ubuntu 18.04 Bionic

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Working towards #13391, related to #16929

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Review by BetsyMcPhail — COMMENTED** [review]
Assuming the unprovisioned builds pass, this is ready for a review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931#-:-N-U7jSV86jOmbvCPlQ1:bo30eid)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

As a final step prior to merge, it's probably worth checking an ubuntu wheel build in CI.  Some of the bzl files touched here are critical in that build.

> Reviewed 26 of 26 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931#-:-N-U8T6v7FdRo6mS1vvf:bxsb173)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 115 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16931#-N-U7d9FAASngqD907eb:-N-U7d9FAASngqD907ec:b-vjbxed) ([raw file](https://github.com/robotlocomotion/drake/blob/21fb18efcc82efa4f2ba2c06d6e0d83f0da1761a/setup/ubuntu/source_distribution/install_prereqs.sh#L115)):*
> ```Shell
> 
> 
> # TODO(svenevs): ideally we would have `packages-${codename}-satisfy.txt`, example
> ```

nit Line too long (>80).
___
*[tools/workspace/spdlog/repository.bzl, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16931#-N-U8HUe2cEXwy7U9e8c:-N-U8HUe2cEXwy7U9e8d:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/21fb18efcc82efa4f2ba2c06d6e0d83f0da1761a/tools/workspace/spdlog/repository.bzl#L24)):*
> ```Starlark
>         error = setup_github_repository(repo_ctx).error
>     else:
>         # On Ubuntu 20.04, we use the host-provided spdlog via pkg-config.
> ```

nit



_Suggestion:_
```Starlark
On Ubuntu, we use
```

**Comment by jwnimmer-tri** [comment]
CI is happy.

+@sherm1 for platform review per schedule, please.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[setup/ubuntu/source_distribution/install_prereqs.sh, line 115 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16931#-N-U7d9FAASngqD907eb:-N-VHnuH3KIuKTIju-82:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/21fb18efcc82efa4f2ba2c06d6e0d83f0da1761a/setup/ubuntu/source_distribution/install_prereqs.sh#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Line too long (>80).
</blockquote></details>

Done
___
*[tools/workspace/spdlog/repository.bzl, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16931#-N-U8HUe2cEXwy7U9e8c:-N-VHpPyEWbRr-IGAldh:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/21fb18efcc82efa4f2ba2c06d6e0d83f0da1761a/tools/workspace/spdlog/repository.bzl#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 25 of 26 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16931#-:-N-VuBTIB0pCuPnt1SRW:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
