### PR TITLE
doc: Add consolidated deployment tool

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This enables us to formulate the website layout within Drake itself, instead of by tweaking untestable CI scripts.

This will be used by https://github.com/RobotLocomotion/drake-ci/pull/122.

Towards #13832.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14587)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.  Note the link in the PR description to where this gets used, to help clarify the context here.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by ggould-tri — COMMENTED** [review]
Your TODO captures my only objection.  This looks sound, and I'll badge it once I've had a chance to run it locally.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14587#-:-MS49Y_J3io2gdC0ME07:b-2xtlqd)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.  (Hopefully any late-breaking changes will be small.)

**Review by ggould-tri — COMMENTED** [review]
Local smoke test results are boringly normal.  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14587#-:-MS4PmMECCfxiepPyOqY:b-bfq7rq)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Looks normal for me too.  :lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14587#-:-MS9fzU0E8cDePEW2KQv:b-dce101)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14587)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
