### PR TITLE
Add CheckSatisfiability and Minimize in DrealSolver

### PR DESCRIPTION
**Pull request by soonho-tri**
- CI will be expected to fail until the images are updated with #7600.
 - unprovisioned builds should succeed.
 - To test it locally, first run `install_prereqs.sh` in `setup` directory.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7631)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
+@nikos-tri for feature-review please. (This is a subset of the PR that you've reviewed before)

**Comment by soonho-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by nikos-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-:-L0ejfglgghIgUiWyJmy:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
I have checked that the failure on `mac-highsierra-unprovisioned-clang-bazel-experimental` is because of `mac //common/proto:call_python_full_test` and has nothing to do with this PR.

+@sammy-tri for platform-review (per rotation) please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-:-L0fpMQFP1ZUDDtud7jI:bn5vvtd)*

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/test/dreal_solver_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-L0jgMeKG8Cded5zgCWP:-L0jgMeLA1U9KXrUENMN:bryl97f) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f9417546228be349eab86586c4f83341b0ecd9/solvers/test/dreal_solver_test.cc#L189)):*
> ```cpp
> }
> 
> TEST_F(DrealSolverTest, CheckSatisfiabilityLog) {
> ```

BTW it would be nice to reduce some of this duplicated code, but it doesn't seem obvious to me that it's possible to parameterize a test on a function...  and my only other ideas involve things like macros with token pasting and I don't really think it's reasonable to fault someone for not choosing that option.

---

*[solvers/test/dreal_solver_test.cc, line 412 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-L0jhFdrn2g9gUWcO7P2:-L0jhFdrn2g9gUWcO7P3:b-fwq0h6) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f9417546228be349eab86586c4f83341b0ecd9/solvers/test/dreal_solver_test.cc#L412)):*
> ```cpp
> }
> 
> TEST_F(DrealSolverTest, UnsupportedFormulaPSD) {
> ```

It's not clear to me how this test is different from the one above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-:-L0jhPGVO32wvPlX4zzY:bvb1a6z)*

**Comment by soonho-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/test/dreal_solver_test.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-L0jgMeKG8Cded5zgCWP:-L0k2iYX-s8gOOGt-jwx:bxyrbeh) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f9417546228be349eab86586c4f83341b0ecd9/solvers/test/dreal_solver_test.cc#L189)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it would be nice to reduce some of this duplicated code, but it doesn't seem obvious to me that it's possible to parameterize a test on a function...  and my only other ideas involve things like macros with token pasting and I don't really think it's reasonable to fault someone for not choosing that option.
</blockquote></details>

I had thought about parameterizing it but couldn't find a good solution either. Now, I've already typed them up and I wish it was not a waste of my time... 

---

*[solvers/test/dreal_solver_test.cc, line 412 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-L0jhFdrn2g9gUWcO7P2:-L0k2P0VjOJtwe_UrTxB:bw6de9l) ([raw file](https://github.com/robotlocomotion/drake/blob/f3f9417546228be349eab86586c4f83341b0ecd9/solvers/test/dreal_solver_test.cc#L412)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's not clear to me how this test is different from the one above.
</blockquote></details>

Done.

(Removed. It was a wrong duplicate of `UnsupportedFormulaPositiveSemidefinite` below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7631)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7631#-:-L0k4QbRih4TaHtxGkVd:bnfp4nl)*

**Pull request merged**
