### PR TITLE
Fixed show_contact visualizer script to properly scale force arrows

### PR DESCRIPTION
**Pull request by mposa**
The existing script scales all arrows to a length of 0.1, destroying relative size of the force vectors. This version scales the largest to 0.1, preserving relative size.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11918)

### CODE REVIEW

**Comment by mposa** [comment]
I agree that a true fix would require some notion of scale in the scene--but to me, this is a clear improvement. The current approach gives *no* notion of relative scale, which led to me to grossly misinterpret what it was showing. 

Just to be clear, what I coded here maintains a fixed scale, but only for the largest vector. Others will be proportionally scaled down.

**Comment by mposa** [comment]
Numbers next to arrows is OK, but harder to visually interpret in real time as they change. If I really want numbers, I should pull up signal scope or LCM spy.

I agree that the antagonistic scenarios you both present are confusing, but absent some fixed scaling factor, I don't see a solution that preserves visual cues. Perhaps you'd be OK with maintaining some decaying history of what "max" means?

Also, I do maintain that the current visualization (showing only direction) is pretty useless.

**Comment by sherm1** [comment]
I agree that rescaling every frame is probably a bad idea, for reasons given above. But I've seen rescaling schemes that work using _occasional_ rescaling. I think those work something like this: choose a range of acceptable sizes (say .05 to .5) and rescale only when the vectors go off the top or off the bottom of the range. That produces hysteresis so that dynamic changes are visible most of the time, with an occasional major rescaling event.

**Comment by sherm1** [comment]
Per f2f w/Sean & Rick: 
- I've used log-thickness arrows where the force order of magnitude is indicated by thickness, with a 10:1 range indicated by length. I'm not sure whether that's a good idea but it does allow for a wide range and some dynamic variation.
- Sean thinks that using fixed-size vectors with a range of colors would be good. (Sorry, color blind folks!)
- In any scaling scheme we could hold the current scale factor in the visualizer and change it only occasionally when rescaling is desperately needed.

**Comment by mposa** [comment]
If that's the way you all want to go, sure, but I can't say that I agree. I'm sure my brain will adjust to associate colors with magnitude, but I don't find it very informative right now. Maybe it's just me, but the one showing arrow magnitude is much easier to follow. I'll also note that fixed magnitude arrows behave very poorly for small forces, where a small delta causes the arrow to move wildly.

Obviously this color approach has the same issue of absolute magnitude that the PR does, so I don't see how it helps the original complaints any.

If anything, I would go with Sherm's suggestion to dynamically (but in fixed increments, with hysteresis) re-scale the arrows.

**Comment by sherm1** [comment]
From this discussion I formed this not-very-surprising conclusion: people have different preferences for how best to view contact forces. So I endorse Sean's plan to figure out a way to allow a Drake visualizer user to choose their preferred option. Then we can explore different options without breaking anything!

**Pull request closed without merging**
