### PR TITLE
Remove support for Python 2 except Director

### LINKED ISSUE #12077: Should switch to require >= C++17
We gained official support via #11610, and have been using C++17 in Anzu, and it's been great.
We should eventually require C++17, esp. once we drop Xenial (#10606), 

Strawman date to require >= C++17: ~2019-11-15 ?~ 2019-10-25 (same as timeline issue)

\cc @jwnimmer-tri @jamiesnape

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #10606. Part of #12234.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12243)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mirror-to-s3 please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mirror-to-s3 please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mirror-to-s3 please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-cmake-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-clang-cmake-experimental-snopt-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-gurobi-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-gurobi-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-mosek-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-f2c-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-debug please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-cmake-experimental-snopt-release please

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature review.

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12243#-Ls3fH497GMvHbwnA8Y4:-Ls3fH4B3cqYx6D1vq8E:b-9fyr0h) (no related file):*
Er, should the title be "Remove support for **Python 2** except Director"?

---

**Comment by EricCousineau-TRI** [comment]
___
*[tools/jupyter/jupyter_py.bzl, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12243#-Ls3gPFP-SZi_SyaUIfg:-Ls3h90c1blkK2nfzNA0:bkb84qq) ([raw file](https://github.com/robotlocomotion/drake/blob/98d80ee68dc5d2015e61e608c84dd0a17a0dde72/tools/jupyter/jupyter_py.bzl#L59)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit All of this `is_supported` code can also be removed, since all platforms now support this!
(I can push those changes, if you'd like.)
</blockquote></details>

I'll just file a PR targeting your branch with the changes.

**Comment by sherm1** [comment]
___
*[tools/workspace/python3/BUILD.bazel, line 4 at r3](https://reviewable.io/reviews/robotlocomotion/drake/12243#-Ls3yBNxBs9zQtpUOdEc:-Ls4LK1kC_IrHNhMiVaD:bfg6f8a) ([raw file](https://github.com/robotlocomotion/drake/blob/775d43f7af48d51fe44ccb98c0de792b66f9ab53/tools/workspace/python3/BUILD.bazel#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

It was deleted.
</blockquote></details>

Oh, whoops -- sorry, Jamie!

**Pull request merged**
