### PR TITLE
Set --output_base instead of --output_user_root

### PR DESCRIPTION
**Pull request by jamiesnape**
I mixed the two up previously. This is mostly cosmetic.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8379)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@soonho-tri for feature and platform review.

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8379#-L7fY-YbbRnImeR_2XLg:-L7fY-YbbRnImeR_2XLh:bcikvj8) ([raw file](https://github.com/robotlocomotion/drake/blob/58b97230414b7b8d956f90319e43c34c23dcd22c/CMakeLists.txt#L89)):*
>  # that bazel uses by default for its --output_base.

To be precise, isn't it what bazel uses by default for `--output_user_root`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8379)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8379#-:-L7fYH-CNv1T6AMkPZj2:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8379#-L7fY-YbbRnImeR_2XLg:-L7fYWz6c1hwcxt8W7Wj:bujm3by) ([raw file](https://github.com/robotlocomotion/drake/blob/58b97230414b7b8d956f90319e43c34c23dcd22c/CMakeLists.txt#L89)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

>  # that bazel uses by default for its --output_base.

To be precise, isn't it what bazel uses by default for `--output_user_root`?
</blockquote></details>

The `output_user_root` is the directory `_bazel_$ENV{USER}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8379)*

**Pull request merged**
