### PR TITLE
Add BsplineTrajectoryThroughUnionOfHPolyhedra

### PR DESCRIPTION
**Pull request by avalenzu**
This still needs some tidying up, but I want to get feedback.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15609)

### CODE REVIEW

**Review by avalenzu — COMMENTED** [review]
+@russtedrake for design review. r1 is #15608, so don't worry about that here. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15609#-:-Mgw7pff5KBkEfngPwcP:bh7bhl)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by TobiaMarcucci** [comment]
One of the doubts I had concerned the way we ensure continuity of the path across neighboring polytopes. But I see that the approach taken is exactly what I'd do: when the edge `(u,v)` is selected, you ensure that the last `order - 1` control points in `X_u` also belong to `X_v`. (As opposed of making the last `order - 1` control points in `X_u` coincide with the first `order - 1` of `X_v`, which would need redundant decision variables.)

Two things that I still don't completely get are the role of the knot points (are they evenly spaced and then scaled uniformly? the `duration_scaling ` is common to all the regions?) and the definition of the edge lengths. Would it be possible to add some comments in the code? In particular this is [the block of code that I stubble most with](https://github.com/RobotLocomotion/drake/blob/c18b62facc81d371f713aa3d108d852c5135c767/geometry/optimization/bspline_graph_of_convex_sets.cc#L91-L185) :-)

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/bspline_graph_of_convex_sets.cc, line 185 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15609#-Mm4_iXL0XJ3z1feqUj3:-MmkAE6_2nAt6F-fz8W9:b-ymf60o) ([raw file](https://github.com/robotlocomotion/drake/blob/c18b62facc81d371f713aa3d108d852c5135c767/geometry/optimization/bspline_graph_of_convex_sets.cc#L185)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

In adding comments explaining this, I'm coming to see that this formulation is rather strange. I think it really ought to be either 
- sum_i(|cost_component_i|_2) or 
- sum_i(|cost_component_i|^2_2)
That is, the norm should be over each component, rather than over the concatenation of all the components. That being said, the second option above is equivalent to |cost_components|^2_2, so maybe it's fine as is?
</blockquote></details>

Right, I thought you were being clever by stacking them into one big vector and taking the norm squared.  I was hoping we could just hit that vector with a coefficient matrix to make it equivalent to sum_i(Q_i |cost_component_i|^2_2), where Q_i was the scaling for derviative level i.  That way we could even set some to zero.

**Comment by jwnimmer-tri** [comment]
@avalenzu @RussTedrake @TobiaMarcucci is there something that other Drake team members can do to move this PR forward?  Would you like us to merge the merge commit up to latest master?  (There is currently a merge conflict.)

**Comment by RussTedrake** [comment]
I discussed this with @avalenzu a little while back.  @mpetersen94 and I will carry this forward.  We're working with a python formulation that builds on this.  Let's close this PR and we'll reopen something when we're quite satisfied with the formulation.

**Pull request closed without merging**
