### PR TITLE
Improve documentation of PDControlSystem.

### PR DESCRIPTION
**Pull request by liangfok**
This PR was broken out of #3103.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3398)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3398#-:-KRCIghQFPPNEFEwxvlA:b-57wv7n)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3398#-:-KRJax95a8F9oGmh_W8n:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. +@sherm1 for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3398#-:-KRJezlBnlFRZPf_1I6Z:b8z1tcd)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3398#-:-KRKL2IxfRHP5mJgGhDG:bnfp4nl)*

**Pull request merged**
