### PR TITLE
Remove another line or two from pods.cmake

### PR DESCRIPTION
**Pull request by jamiesnape**
The test result to look for here is `matlab/check_dependency_lcm`.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4577)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-open-source please
@drake-jenkins-bot linux-clang-experimental-ros please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-open-source please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/checkDependency.m, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-KZYX-tqwibC7qRXT8yF:-KZYX-tqwibC7qRXT8yG:bb6foqi) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd71b678efd48bbfb7e49106d46e0b9ba504a02/drake/matlab/util/checkDependency.m#L78)):*
> ```objc
>           disp(' Added the lcm jar to your javaclasspath (found via cmake)');
>         catch err
>           if strcmp(err.identifier, 'Drake:CannotClearJava')
> ```

What's this about?  Comment please.

---

*[drake/matlab/util/checkDependency.m, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-KZYX2vnWyX3d-QNEE7O:-KZYX2vnWyX3d-QNEE7P:b-yf3van) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa387703f84e9f883441c2907965ca0600271e9/drake/matlab/util/checkDependency.m#L81)):*
> ```objc
> 
>         if (~conf.lcm_enabled)
>           [retval,cp] = system(['export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:',fullfile(getCMakeParam('CMAKE_INSTALL_PREFIX'),'lib','pkgconfig'),' && pkg-config --variable=classpath lcm-java']);
> ```

This is now redundant because CMake has already invoked pkg-config, and set the results in LCM_JAR_FILE if applicable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-:-KZYXBIMtUKfEw0du0bl:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/checkDependency.m, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-KZYX-tqwibC7qRXT8yF:-KZYXMfG9S-mwuiExbBh:bj88gha) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd71b678efd48bbfb7e49106d46e0b9ba504a02/drake/matlab/util/checkDependency.m#L78)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

What's this about?  Comment please.
</blockquote></details>

Honestly, I have no idea, but the lcmgl dependency did it.

---

*[drake/matlab/util/checkDependency.m, line 81 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-KZYX2vnWyX3d-QNEE7O:-KZYXYQa6mtVdkS7qT-J:bsd4a7h) ([raw file](https://github.com/robotlocomotion/drake/blob/eaa387703f84e9f883441c2907965ca0600271e9/drake/matlab/util/checkDependency.m#L81)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This is now redundant because CMake has already invoked pkg-config, and set the results in LCM_JAR_FILE if applicable?
</blockquote></details>

Yes. Similar logic to lcmgl.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4577)*

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/matlab/util/checkDependency.m, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-KZYX-tqwibC7qRXT8yF:-KZYYCUNCNizbJI2LYdy:bbjo49v) ([raw file](https://github.com/robotlocomotion/drake/blob/0fd71b678efd48bbfb7e49106d46e0b9ba504a02/drake/matlab/util/checkDependency.m#L78)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Honestly, I have no idea, but the lcmgl dependency did it.
</blockquote></details>

I would probably be better removing it, I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4577)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4577#-:-K_1PzJDKZis-TLAejxJ:bnfp4nl)*

**Pull request merged**
