### PR TITLE
added a ball joint to RBT.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Copied from quaternion_floating_joint. added a dummy kinematics unit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6489)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@edrumwri for feature review, thanks! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-:-KntWIpT50wHt5sJ7WH9:bfmh2l4)*

**Comment by edrumwri** [comment]
Just one tiny concern, then :lgtm: (such a shame to have to write code again rigidbodytree though!)

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/urdf_parser.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KntiRFgtXPUdH0qRxlP:-KntiRFgtXPUdH0qRxlQ:b-cutqp1) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/parsers/urdf_parser.cc#L734)):*
> ```cpp
>   } else if (type.compare("floating") == 0) {
>     joint = new RollPitchYawFloatingJoint(name, transform_to_parent_body);
>   } else if (type.compare("ball") == 0) {
> ```

I don't see in the URDF spec (http://wiki.ros.org/urdf/XML/joint) where "ball" is a valid type id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-:-Knv3L1ZHY7V68vWqMbo:bd39voy)*

**Comment by siyuanfeng-tri** [comment]
+@ggould-tri for platform review. This PR is motivated by need to supporting mobile base robots. The floating joint is used to create frictionless caster wheels at the base. This is also directly copy pasted from existing RBT code (front quaternion_floating_joint). 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/urdf_parser.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KntiRFgtXPUdH0qRxlP:-Ko3mhi7qax_FpaRja1y:buqwpe9) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/parsers/urdf_parser.cc#L734)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't see in the URDF spec (http://wiki.ros.org/urdf/XML/joint) where "ball" is a valid type id.
</blockquote></details>

hmm that's a good point.
It seems ball type exist in sdf. http://sdformat.org/spec?ver=1.6&elem=joint
I am not sure about urdf. @liangfok any ideas? thanks! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-:-Ko3oB7Eo304rIhdKhLR:b2luct8)*

**Comment by ggould-tri** [comment]
:lgtm: pending open discussions.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/joints/quaternion_ball_joint.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI62XBV0bd3nBzTaYw:-KoI62XBV0bd3nBzTaYx:bbell3n) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.cc#L46)):*
> ```cpp
> VectorXd QuaternionBallJoint::randomConfiguration(
>     std::default_random_engine& generator) const {
>   // orientation
> ```

BTW -- This comment doesn't really add anything not obvious from the names of the method and the function it dispatches to.

---

*[drake/multibody/joints/quaternion_ball_joint.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI6JYXfJKTKCyt88M4:-KoI6JYYfhNyjjB01Sp8:bqump3t) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.cc#L62)):*
> ```cpp
> std::unique_ptr<DrakeJoint> QuaternionBallJoint::DoClone() const {
>   auto joint = std::make_unique<QuaternionBallJoint>(get_name(),
>       get_transform_to_parent_body());
> ```

BTW -- double-check this indentation, it looks nonstandard to me.

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI7o8_NIHuaJHd1ZhZ:-KoI7o8_NIHuaJHd1Zh_:b-wwdfev) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L16)):*
> ```objc
> 
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Woverloaded-virtual"
> ```

This is a fairly serious thing to ignore -- the resulting class will not implement its superclass API contract.  It needs at least an explanation and possibly a todo.

I would also expect this to be easy to fix -- typically you can just `using` the missing overload case to forward it to the parent.  Is this not the case here?

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI8kZSb9SondqyKVVZ:-KoI8kZSb9SondqyKVV_:b24vsl4) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L17)):*
> ```objc
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Woverloaded-virtual"
> // TODO(sherm1,mitiguy) Verify that this is correct.
> ```

FYI -- Style guide discourages TODOs with other than the author's name.  It's a soft discourage, so feel free to wontfix this provided that @sherm1 and @mitiguy know that they've been handed the responsibility here.

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI9SwDQrHvvTBZ_S6O:-KoI9SwDQrHvvTBZ_S6P:bywvhik) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L64)):*
> ```objc
>  public:
>   QuaternionBallJoint(const std::string& name,
>                           const Eigen::Isometry3d& transform_to_parent_body)
> ```

BTW nonstandard indent.

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 267 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI79Zzb52CSP2BhYih:-KoI79Zzb52CSP2BhYii:b-zb55gd) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L267)):*
> ```objc
>   bool is_floating() const override { return false; };
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> ```

BTW nonstandard indent, here and other TODOs below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-:-KoID2BgZvGMbbj1MW3d:buvdl6p)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 14 files at r1.
Review status: 12 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/joints/quaternion_ball_joint.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI62XBV0bd3nBzTaYw:-KoIDYM1yQ91UDvPYURj:b6p80q5) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.cc#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- This comment doesn't really add anything not obvious from the names of the method and the function it dispatches to.
</blockquote></details>

removed. 

---

*[drake/multibody/joints/quaternion_ball_joint.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI6JYXfJKTKCyt88M4:-KoIDkabqyfRfkq4AAcs:biwfpi7) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.cc#L62)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- double-check this indentation, it looks nonstandard to me.
</blockquote></details>

I ran clang format on this. should be fine? 

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI7o8_NIHuaJHd1ZhZ:-KoIDw1xg7Z3gcUNVU_K:b-8zgulv) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L16)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is a fairly serious thing to ignore -- the resulting class will not implement its superclass API contract.  It needs at least an explanation and possibly a todo.

I would also expect this to be easy to fix -- typically you can just `using` the missing overload case to forward it to the parent.  Is this not the case here?
</blockquote></details>

I actually have no idea why these are here, I copied these from quaternion_floating_joint, and it appears that all drake joints have these. I am leaning towards leaving it as is. RBT will go away at some point, and I am hesitant to understand why this is here. 

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI8kZSb9SondqyKVVZ:-KoIEJHTFYVLbW0pVdvt:b-aipl9s) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L17)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Style guide discourages TODOs with other than the author's name.  It's a soft discourage, so feel free to wontfix this provided that @sherm1 and @mitiguy know that they've been handed the responsibility here.
</blockquote></details>

copy that. cc @sherm1 and @mitiguy. 

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI9SwDQrHvvTBZ_S6O:-KoIEV043Yje9CZ4DZqy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L64)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW nonstandard indent.
</blockquote></details>

Done.

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 267 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI79Zzb52CSP2BhYih:-KoIE_tFzEB6zMKBFO7l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L267)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW nonstandard indent, here and other TODOs below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/joints/quaternion_ball_joint.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoI7o8_NIHuaJHd1ZhZ:-KoIQbLrOTNC2AxNTLbx:b-y6qzio) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/joints/quaternion_ball_joint.h#L16)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I actually have no idea why these are here, I copied these from quaternion_floating_joint, and it appears that all drake joints have these. I am leaning towards leaving it as is. RBT will go away at some point, and I am hesitant to understand why this is here. 
</blockquote></details>

Heh.  Well, I guess I'll accept a wontfix on it, then.  Another reason to look forward to the death of RBT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by siyuanfeng-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/urdf_parser.cc, line 734 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KntiRFgtXPUdH0qRxlP:-KoNEgKAK0DuG2CxGKmC:b8hkpio) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e8b50e2a8ba16eaefd497515bd751c916af366/drake/multibody/parsers/urdf_parser.cc#L734)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

hmm that's a good point.
It seems ball type exist in sdf. http://sdformat.org/spec?ver=1.6&elem=joint
I am not sure about urdf. @liangfok any ideas? thanks! 
</blockquote></details>

added a printed warning in the urdf parser. I still want the ability to parse ball joints in urdf in drake. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNVLpgYWG4FywxzM6r:b-x6lf4g) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
> ```cpp
>     joint = new QuaternionBallJoint(name, transform_to_parent_body);
>     cerr << string(__FILE__) + ": " + __func__ + ": Warning: ball joint "
>       "is not a commonly supported urdf joint type." << endl;
> ```

Siyuan, would you just say that it's not an official part of the URDF standard?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNWMME6ElvKt1Okou6:b-meokx9) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW For what it's worth, our collision groups aren't official URDF but we don't think twice about including them.  :)  I don't *believe* we take any extraordinary steps in parsing them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by edrumwri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNWiiwdC0Q3nTcLiCG:b-5esip8) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW For what it's worth, our collision groups aren't official URDF but we don't think twice about including them.  :)  I don't *believe* we take any extraordinary steps in parsing them.
</blockquote></details>

BTW Good to know- we *should* think twice about any such extensions. If nothing else, we need to track them so that we might propose them for official modifications to the standard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoN_G0a829A_MADNAZ5:bn554e8) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW Good to know- we *should* think twice about any such extensions. If nothing else, we need to track them so that we might propose them for official modifications to the standard.
</blockquote></details>

BTW @jwnimmer-tri has made an excellent point that the *logical* place to resolve this is: https://github.com/RobotLocomotion/drake/blob/master/drake/doc/drakeURDF.xsd
I'd argue that this PR is the right time to do so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by edrumwri** [comment]
Agreed. Siyuan, if you do it the way that Sean suggested (modifying the
schema to point out our custom extensions), you can get rid of the ugly
warning message to cerr.


--------------------------------
Evan Drumwright
Senior Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Comment by siyuanfeng-tri** [comment]
*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNcONwt2sybgUsB0bo:b-d2fwnl) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW @jwnimmer-tri has made an excellent point that the *logical* place to resolve this is: https://github.com/RobotLocomotion/drake/blob/master/drake/doc/drakeURDF.xsd
I'd argue that this PR is the right time to do so.
</blockquote></details>

I can definitely add a ball type joint there, but I suspect that doc needs major revision. It hasn't been touched since Dec 2015. It also mentions about a planar joint, which is missing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNcyE4UJYpEqLshbUf:b-6ewi9e) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I can definitely add a ball type joint there, but I suspect that doc needs major revision. It hasn't been touched since Dec 2015. It also mentions about a planar joint, which is missing. 
</blockquote></details>

Well, I'd say add the ball joint, but I'll make an issue for the dynamics team to go over the xsd and make sure that it's correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by SeanCurtis-TRI** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNdktj-qjdWmruGxAI:b6u4abt) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Well, I'd say add the ball joint, but I'll make an issue for the dynamics team to go over the xsd and make sure that it's correct.
</blockquote></details>

Issue added: https://github.com/RobotLocomotion/drake/issues/6518

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by siyuanfeng-tri** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNeKsk_Ens6InBqKBb:bcvmxjq) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Issue added: https://github.com/RobotLocomotion/drake/issues/6518
</blockquote></details>

you beat me there. thanks sean. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/urdf_parser.cc, line 737 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6489#-KoNVLpgYWG4FywxzM6q:-KoNiP2MnX5XuK4OMqXL:bak0ecy) ([raw file](https://github.com/robotlocomotion/drake/blob/66c4cce4963c5fd8c0e8d2c0a56b56cabd079a8e/drake/multibody/parsers/urdf_parser.cc#L737)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

you beat me there. thanks sean. 
</blockquote></details>

touched drakeURDF.xsd. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6489)*

**Pull request merged**
