### PR TITLE
pydrake eigen: Add `mul` and `inverse` for Quaternion and Isometry3

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@avalenzu for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802#-:-LCGIlGp3faLnhJOavTO:b-fcohnv)*

**Comment by avalenzu** [comment]
:lgtm: with a BTW on naming. @sammy-tri for platform review (since he's next in the rotation).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8802#-LCTnGjs4I6Dr5V7-e9G:-LCTnGjs4I6Dr5V7-e9H:baop1e7) ([raw file](https://github.com/robotlocomotion/drake/blob/8c8f5c324cb74cc0248c2f05ae7cfd65186831fa/bindings/pydrake/util/eigen_geometry_py.cc#L149)):*
> ```cpp
>       // Do not define an operator until we have the Python3 `@` operator so
>       // that operations are similar to those of arrays.
>       .def("mul", [](const Class& self, const Class& other) {
> ```

BTW, is this a conventional Python-y name? If not, consider `multiply()`.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8802#-LCToopz90-ordxIObk7:-LCToopz90-ordxIObk8:bmp0kl4) ([raw file](https://github.com/robotlocomotion/drake/blob/8c8f5c324cb74cc0248c2f05ae7cfd65186831fa/bindings/pydrake/util/eigen_geometry_py.cc#L230)):*
> ```cpp
>       // Do not define an operator until we have the Python3 `@` operator so
>       // that operations are similar to those of arrays.
>       .def("mul", [](const Class& self, const Class& other) {
> ```

BTW, same question as above. Here you could get really fancy and name it `HamiltonProduct()` (don't do that though).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802#-:-LCTp55h2LJ2Eh7Fwjwe:b-7dnxc4)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/util/eigen_geometry_py.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8802#-LCTnGjs4I6Dr5V7-e9G:-LCUQrFvAXoaQiR79vu8:bxt3avj) ([raw file](https://github.com/robotlocomotion/drake/blob/8c8f5c324cb74cc0248c2f05ae7cfd65186831fa/bindings/pydrake/util/eigen_geometry_py.cc#L149)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, is this a conventional Python-y name? If not, consider `multiply()`.
</blockquote></details>

It's an explicit spelling of the `__mul__` operator overload, but looking at it again, it does look kinda bad. Will rename to `multiply`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802)*

**Comment by sammy-tri** [comment]
+@sammy-tri Will try to get to this soon.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802#-:-LCUce8KD3BW8kzvD0S6:b-683zx3)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 149 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8802#-LCTnGjs4I6Dr5V7-e9G:-LCUuwSZ-HlHDfB2NSa2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c8f5c324cb74cc0248c2f05ae7cfd65186831fa/bindings/pydrake/util/eigen_geometry_py.cc#L149)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's an explicit spelling of the `__mul__` operator overload, but looking at it again, it does look kinda bad. Will rename to `multiply`.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8802#-LCToopz90-ordxIObk7:-LCUuwwwEw99FIeYhcsn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c8f5c324cb74cc0248c2f05ae7cfd65186831fa/bindings/pydrake/util/eigen_geometry_py.cc#L230)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, same question as above. Here you could get really fancy and name it `HamiltonProduct()` (don't do that though).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8802)*

**Pull request merged**
