### PR TITLE
Fix wrong focal length calculation

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5721)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@liangfok feature review please +@sammy-tri platform review please. Thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5721#-:-Kgv0imRDbVAnCJHtIxK:b-2g4l7o)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5721#-:-Kgvt00edLndxBOnY282:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5721#-:-KgyV2bcpIGeS9LSe8Ro:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-debug please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5721#-:-KgyrF5GQZWQ8n6fJJYE:b-9h3zzq)*

**Pull request merged**
