### PR TITLE
Provide instructions for alternate linting tools

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Extends the linting configuration for CLion to provide an alternate formulation that allows for simultaneous linting and building.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6965)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@russtedrake for feature review
Let me know if this addresses your problem.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-:-KtHOvsyD3v5UUZSL05j:bym6ynx)*

**Comment by RussTedrake** [comment]
:lgtm:  perfect.  thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-:-KtJW3ysAiIJaLhzR4W3:b-mlp5m)*

**Comment by RussTedrake** [comment]
+@ggould-tri for platform

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-:-KtM-_I4GF4Ll12xSkNQ:bb7u9kk)*

**Comment by ggould-tri** [comment]
:lgtm: with one issue noted below.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 424 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-KtMHYnhvP9f2Zc1noVu:-KtMHYnhvP9f2Zc1noVv:byx5ns3) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9cc9ab009a6937706f734b0a4f88400be7c7f1/drake/doc/clion.rst#L424)):*
> ```reStructuredText
> The work around is to change the configurations to execute the binaries
> directly. This approach generally works but will fail if the corresponding bazel
> targets have not been built. The tools would need to be built
> ```

Missing punctuation, and possibly this last sentence isn't doing any semantic work anyway and could be removed or expanded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-:-KtMHuUq9yuQ-wyhVz4q:b-pxkzd5)*

**Comment by SeanCurtis-TRI** [comment]
Comment addressed. Also took the opportunity to address something that came up in the docs based on the change in #6979.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 424 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-KtMHYnhvP9f2Zc1noVu:-Ktldya7t11NhgbpSnd8:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/cc9cc9ab009a6937706f734b0a4f88400be7c7f1/drake/doc/clion.rst#L424)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Missing punctuation, and possibly this last sentence isn't doing any semantic work anyway and could be removed or expanded.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965#-:-KtleGinZf_8uLBIOFTx:bt6cpu9)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6965)*

**Pull request merged**
