### PR TITLE
Improve Parsing of PSD Expression Matrices

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not review) 

@RussTedrake This is the draft PR that would change it so that we parse Expression matrices as an LMI which would reduce the number of variables in the program. It's not a hard change to implement, but it is a nasty breaking change to the API.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-:-NrN85jF14jPjwdGffJT:b-eegpzh)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 2592 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-NsQyDghCa3sXIVffSjJ:-NsQyDghCa3sXIVffSjK:b-5itv5r) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c2fc6a0a47a57700d24eea80422f312bc604c45/solvers/mathematical_program.h#L2592)):*
> ```objc
> //  }
> 
>   Binding<LinearMatrixInequalityConstraint> AddPositiveSemidefiniteConstraint(
> ```

I think this method should be called AddLinearMatrixInequalityConstraint... (that's what it actually is, and should have been) and the AddPositiveSemidefiniteConstraint that takes an expression should be deprecated. 
___
*[`solvers/mathematical_program.h` line 2618 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-NsQydpP8MrM9hXaSp_9:-NsQydpP8MrM9hXaSp_A:b8yj3al) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c2fc6a0a47a57700d24eea80422f312bc604c45/solvers/mathematical_program.h#L2618)):*
> ```objc
>    * symmetric_matrix_var.rows() - 1].
>    * @param e Imposes constraint "e is positive semidefinite".
>    * @see AddPositiveSemidefiniteConstraint.
> ```

we'll want to point this comment to AddLMIConstraint now
___
*[`solvers/mathematical_program.h` line 2620 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-NsQyPMC10uvnfldslIN:-NsQyPMC10uvnfldslIO:bqvmkbv) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c2fc6a0a47a57700d24eea80422f312bc604c45/solvers/mathematical_program.h#L2620)):*
> ```objc
>    * @see AddPositiveSemidefiniteConstraint.
>    */
>   Binding<LinearMatrixInequalityConstraint> AddPrincipalSubmatrixIsPsdConstraint(
> ```

This one, I think, we just make the breaking change.  The name seems correct as is.
___
*[`solvers/mathematical_program.cc` line 1162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-NsQxu5p5mzY12QaM9cH:-NsQxu5p5mzY12QaM9cI:b-li1wpx) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c2fc6a0a47a57700d24eea80422f312bc604c45/solvers/mathematical_program.cc#L1162)):*
> ```cpp
>       &A, &b, &variables);
>   // A*variables + b represents the lower triangular part of the matrix which we
>   // want to make Psd. At this point, we write this as a standard form Lmi.
> ```

nit: caps for PSD and LMI?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.cc` line 1164 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-NsT93HC8_HVUZSYRXl2:-NsT93HC8_HVUZSYRXl3:b-o55xxo) ([raw file](https://github.com/RobotLocomotion/drake/blob/8c2fc6a0a47a57700d24eea80422f312bc604c45/solvers/mathematical_program.cc#L1164)):*
> ```cpp
>   // want to make Psd. At this point, we write this as a standard form Lmi.
>    vector<Eigen::Ref<const Eigen::MatrixXd>> F;
>    F.reserve(A.rows() +1);
> ```

I think it should be `F.reserve(A.cols() + 1)` here instead of `A.rows() + 1`?

**Review by hongkai-dai — COMMENTED** [review]
So far as I know, many of the solvers don't support LMI in a native way. For example, Mosek supports constraint in this form:

```
<A, X> + a' * x + c = 0
```
where `X` is a PSD matrix of decision variables, `x` is an array of scalar decision variables. We could convert LMI into this form, but you can see it will still add linear equality constraints `<A, X> + a' * x + c = 0` into Mosek.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-:-NsT9UyfCwOTeqlspk2h:bkyiw9)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
I am not sure this is quite right Mosek does support direct "affine in cone constraints" even for LMIs: https://docs.mosek.com/latest/pythonapi/tutorial-sdo-shared.html#example-sdo-lmi-linear-matrix-inequalities-and-the-vectorized-semidefinite-domain
(FWIW I think this was added in Mosek v10)

I suppose that for Clarabel and SCS, we are stuck with the conic standard form, so maybe this change isn't completely worth it. There are still some subspace dualization things that we could do to potentially make the problems a bit better, but this would be a lot of work. See https://jump.dev/Dualization.jl/dev/manual/ for examples

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-:-NsTXtHy9MF0R97gWkwa:bslpzev)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by RussTedrake — COMMENTED** [review]
To make sure I understand, I think we're saying that even if we make this change in MathematicalProgram, then at the level of the solvers, we'll still be creating the extra variables/constraints that we were hoping to avoid with this change?

For Mosek specifically, we could do only a little more at the solver interface level to pass the LMI directly to the solver?

If the new API is more correct then I still like making the change (I think that it's sort of wrong to have an expression go in and have a PsdContraint come out; i think it's cleaner to have an LMI come out). If we think it could work even for Mosek only in the shorter term, then I still think it could be useful computationally. But it _would_ be worth doing that extra step in MosekSolver in a follow-up PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21035#-:-NsXyd655dYsu5Qj50zY:b2iifap)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Comment by AlexandreAmice** [comment]
Closing since most solvers do not directly support LMIs and this is not on my roadmap anytime soon. Hongkai's #21117 does allow Mosek to natively support LMIs.

**Pull request closed without merging**
