### PR TITLE
manipulation_station: add package.xml

### PR DESCRIPTION
**Pull request by RussTedrake**
so that I can find the files in manipulation_station/models from outside of drake via the model directives.  (yeah!)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164#-:-MIjJhzXApZbUo02ueG8:bg7igkv)* status: needs platform reviewer assigned, needs at least one assigned reviewer

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164#-:-MIjJmbB5BiDIJLQDsQs:bz2trbr)* status: needs platform reviewer assigned

**Review by RussTedrake — COMMENTED** [review]
I've added one more here (keeping it as a separate commit in the same PR, so that I can make experimental binaries for colab if necessary)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164#-:-MIkTvuMC01o4_ezd3DT:bxqido0)* status: needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164)* status: needs platform reviewer assigned

**Review by sherm1 — COMMENTED** [review]
+@sherm1 platform :lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164#-:-MIkpV0w0S4CpIUYVvBW:bi7i2vt)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai

**Review by sherm1 — COMMENTED** [review]
I'll leave it to you to squash or merge as-is.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14164#-:-MIkpg6E6yumDcChdBA7:b3kq48r)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai

**Pull request merged**
