### PR TITLE
Add allow_nonconvex flag to QuadraticCost constructor.

### LINKED ISSUE #15008: ChooseBestSolver chooses a convex QP solver for a non-convex QP
As shown on stackoverflow https://stackoverflow.com/questions/67393784/linear-inequality-constraint-not-working-in-drake, currently when we call `solvers::Solve(prog)`, `ChooseBestSolver` will always incur the convex QP solver (Gurobi/Mosek/OSQP) even if the QP problem is non-convex.

We should check if the quadratic cost is convex before dispatching to a solver.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Throws an error if the cost is non-convex, and allow_nonconvex=false.

Resolves #15008

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15014)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15014#-:-M_-OMvz0ScLy0H82uYe:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15014#-:-M_1xiz32yUBiRXfD095:buxscyd)* status: LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
I'll mostly wait for feature review before looking further, but I did a quick skim of header file changes and left a few notes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15014#-:-M_MH-bw4qZ01OLaSG1g:bntp2in)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai, @jwnimmer-tri, and @RussTedrake)

___
*[solvers/cost.h, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15014#-M_MG4l85poSnAPHfoQ2:-M_MG4l85poSnAPHfoQ3:bsmaqd3) ([raw file](https://github.com/robotlocomotion/drake/blob/9bce26640ffe96e1dc193cf2ebf64855b6940c6a/solvers/cost.h#L122)):*
> ```objc
>   QuadraticCost(const Eigen::MatrixBase<DerivedQ>& Q,
>                 const Eigen::MatrixBase<Derivedb>& b, double c = 0.,
>                 bool allow_nonconvex = false)
> ```

The default of "false" here might be considered as a breaking change.  How likely is it that real-world users would be using non-convex constraints on purpose?  Given the enormous amount of unit test changes, I suspect this is too drastic of a change, and we need to use a transition period.

One way to handle the transition is to add the new argument here, but default it to "true" to retain the prior behavior, and document that the default will switch to "false" on 2021-09-01.  That lets users upgrade without changing their code, and then they can separately go through and annotate any opt-ins in places they want to have non-convex.
___
*[solvers/cost.h, line 130 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15014#-M_MFHbZ-UzbXrJioSDu:-M_MFHbZ-UzbXrJioSDv:beekwng) ([raw file](https://github.com/robotlocomotion/drake/blob/9bce26640ffe96e1dc193cf2ebf64855b6940c6a/solvers/cost.h#L130)):*
> ```objc
>     DRAKE_ASSERT(Q_.rows() == Q_.cols());
>     DRAKE_ASSERT(Q_.cols() == b_.rows());
>     if (!allow_nonconvex_) {
> ```

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

This new code pushes this constructor over the limit.  Ditto below.

I suspect the easiest fix would be a `ThrowIfNotPositiveSemidefinite` private function, defined in the cc file, that both places call.
___
*[solvers/create_cost.h, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15014#-M_MGaL00CYjiw1nYN6i:-M_MGaL00CYjiw1nYN6j:b-x5mq04) ([raw file](https://github.com/robotlocomotion/drake/blob/9bce26640ffe96e1dc193cf2ebf64855b6940c6a/solvers/create_cost.h#L25)):*
> ```objc
>  */
> Binding<QuadraticCost> ParseQuadraticCost(const symbolic::Expression& e,
>                                           bool allow_nonconvex);
> ```

nit Needs API documentation.  Ditto below.
___
*[solvers/mathematical_program.h, line 1019 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15014#-M_MGlEk4qhvDHbbPbH1:-M_MGlEk4qhvDHbbPbH2:b-k3q7b0) ([raw file](https://github.com/robotlocomotion/drake/blob/9bce26640ffe96e1dc193cf2ebf64855b6940c6a/solvers/mathematical_program.h#L1019)):*
> ```objc
>    * @param allow_nonconvex Whether we allow non-convex quadratic cost. If
>    * allow_nonconvex = false and `e` is not a convex quadratic function, then
>    * throw std::invalid_argument.
> ```

nit _"When documenting exceptions in an API, only state that the function will throw std::exception; never promise a more specific subclass."_

-- https://drake.mit.edu/styleguide/cppguide.html#Exceptions

**Comment by RussTedrake** [comment]
Perhaps you can help me understand this API decision.  Based on our previous discussion, I was thinking that QuadraticCost (and probably also QuadraticConstraint) would gait a boolean for PSD.  This flag would get set by evaluating the eigenvalues of the matrix in the constructor.

Then there were two cases that you were worried about:
1) one could write a program with an individual quadratic cost that is non-PSD, but the sum of the costs could still be PSD.  I thought we would do that more expensive check (on the sum of the matrices) only for the case when one or more of the individual constraints had PSD=false
2) The extra cost incurred from checking the PSD condition.  For this, we could pass an argument (e.g. std::optional<bool> is_psd) that would avoid the check.  But I'm wondering now if that is an unnecessary or premature optimization.  Probably one call like this is in the noise compared to the solvers' work?  Or at very least, we could add that argument later?

**Comment by jwnimmer-tri** [comment]
Do we need to do the checking as costs are being added?

Maybe all that's needed is `bool MathematicalProgram::AreAllQuadraticCostsPsd()`, which can do the per-cost psd check, falling back to checking the summation only when needed.

Then the solver back-ends that require convex qp can then enforce that, either in ProgramAttributesSatisfied or in DoSolve.

Having `QuadraticCost::IsPsd()` might make this nice to implement, and then could also help the user iterate through the costs to find problematic ones in case of an error.

If the user needs to skip the check, we can define `SolverOption` that allows them to disarm the sanity checking in the solver back-ends.

**Review by hongkai-dai — COMMENTED** [review]
Sorry this PR isn't correctly implemented, as both of you point out, there are two problems
1. This is an API-breaking PR.
2. It requires extra effort from the user to add a non-convex quadratic cost.

I have submitted another PR #15043 to replace this one.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15014#-:-M_cGqZFBku6Dqt_Jt3-:bfu5nt7)* status: 4 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai, @jwnimmer-tri, and @RussTedrake)

**Pull request closed without merging**
