### PR TITLE
Refactor IDM, MOBIL with speedup option

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7927)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@rpoyner-tri for feature review, please

/cc @maddog-tri for the small addition to `lane_data.h`

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4IJGypQG5FjuHJk9fk:b7804oy)*

**Comment by liangfok** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4LxUW7VPPUqw9yiV4S:-L4LxUW7VPPUqw9yiV4T:bev2imd) (no related file):*
BTW, just curious, any numbers quantifying how much this speeds things up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by rpoyner-tri** [comment]
Reviewed 18 of 18 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4LxUW7VPPUqw9yiV4S:-L4MSuIATBAsZPtay-PP:b-dkgxqh) (no related file):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, just curious, any numbers quantifying how much this speeds things up?
</blockquote></details>

I tried a quick benchmark experiment in <proprietary-project-with-bigger-test -case> and didn't see a huge speedup just from this change. It did help a little.

More to the point, I'd like to see a way to run this within drake that would run for a while in both stateless and stateful modes so we could compare performance.

---

*[automotive/idm_controller.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MSRzGvolDM15tqFdA:-L4MSRzH16q2SsiyGM7D:bn4n18r) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/idm_controller.h#L64)):*
> explicit
strictly speaking a 2-arg constructor doesn't have to be `explicit`. I'm not sure it's exactly wrong, but it does inhibit clients from using new-style initializer lists to make an object of this type.

---

*[automotive/mobil_planner.h, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MSjsYEKqqYccl8o6C:-L4MSjsYEKqqYccl8o6D:bu4730g) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/mobil_planner.h#L100)):*
> explicit
not sure explicit is necessary or wanted here.

---

*[automotive/mobil_planner.h, line 101 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MRedhqlxpUzn1dj6q:-L4MRedjGXKCcYwGOHow:b1tsksg) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/mobil_planner.h#L101)):*
> ```objc
>   /// RoadGeometry::ToRoadPosition().
>   explicit MobilPlanner(const maliput::api::RoadGeometry& road,
>                         bool initial_with_s, bool memorize_road_position);
> ```

sad to see another bool parameter here. consider an enum instead. On the bright side, all the doc comments you wrote in the five places this got added could just live in one place, on the enum definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4LxUW7VPPUqw9yiV4S:-L4MpHMDb7_dl0wXBBIR:bl71bre) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I tried a quick benchmark experiment in <proprietary-project-with-bigger-test -case> and didn't see a huge speedup just from this change. It did help a little.

More to the point, I'd like to see a way to run this within drake that would run for a while in both stateless and stateful modes so we could compare performance.
</blockquote></details>

I have a small doc linked to in our JIRA issue that has some profiler results without the patch, and highlighting where the most time is spent currently.

Regarding profiling - per our 1:1 - we agreed that there's no good mechanism in Drake yet to do this. I will do some profiling, however, in a separate repo and share the results internally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by jadecastro** [comment]
Note that I updated the logic to use ToRoadPosition if no valid lane is given.  I've also added some missing unit tests for `CalcUnrestrictedUpdate`.

---

Review status: 4 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[automotive/idm_controller.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MSRzGvolDM15tqFdA:-L4OwxVdMoU4298AaP6R:blthltv) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/idm_controller.h#L64)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> explicit
strictly speaking a 2-arg constructor doesn't have to be `explicit`. I'm not sure it's exactly wrong, but it does inhibit clients from using new-style initializer lists to make an object of this type.
</blockquote></details>

Done. (thanks for catching)

---

*[automotive/mobil_planner.h, line 100 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MSjsYEKqqYccl8o6C:-L4P9C_Tf86GGIH2XkxW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/mobil_planner.h#L100)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> explicit
not sure explicit is necessary or wanted here.
</blockquote></details>

Done.

---

*[automotive/mobil_planner.h, line 101 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4MRedhqlxpUzn1dj6q:-L4P9GaBDu7W86cucRBh:b-4127b8) ([raw file](https://github.com/robotlocomotion/drake/blob/b0ca854fe6f916547acc8f376c62b00747a4deee/automotive/mobil_planner.h#L101)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

sad to see another bool parameter here. consider an enum instead. On the bright side, all the doc comments you wrote in the five places this got added could just live in one place, on the enum definition.
</blockquote></details>

Much better. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4P9XmgpAKNfSZk2j52:bflgg0w)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4aorVNm2-RV_NZNjKP:bnfp4nl)*

**Comment by jadecastro** [comment]
+@ericcousineau-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4ap0-Lg77LHiQtMldB:b72l57d)*

**Comment by EricCousineau-TRI** [comment]
First pass done. PTAL.

---

Reviewed 4 of 18 files at r1, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atZOX4esT5jhzSOWe:-L4atZOX4esT5jhzSOWf:b-on15n7) (no related file):*
Is the intent to automatically register the `UnrestrictedUpdate` if `kMemorize` is being used?

If so, I'm not sure if I see anything in the code that declares an abstract update of any sort.
Did I miss that somewhere?

Additionally, the tests I see only test either (a) the output values or (b) manually trigger an abstract update, but nothing tests whether there is an abstract update registered and the speedup is actually being used.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atmQ_vAHX1Pse9doP:-L4atmQ_vAHX1Pse9doQ:blkwa3n) (no related file):*
At a high level, it seems like this provides a means to overcome a lack of caching in the Systems framework (since this option does not affect the output value, but rather just the computation time).

If so, could a TODO for #4364 be placed to update this once caching lands?
And can the goal of `CalcOngoingRoadPosition` be updated to explicitly mention the word "caching"?
Additionally, could `kMemorize` be renamed to `kCache`?

---

*[automotive/calc_ongoing_road_position.cc, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4aqTjq3IkzP8pPR4SQ:-L4aqTjq3IkzP8pPR4SR:b8625hv) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.cc#L48)):*
> ```cpp
>   // is moving.
>   const T s_dot = PoseSelector<T>::GetSigmaVelocity({rp->lane, lp, velocity});
>   for (const auto& end : {LaneEnd::kStart, LaneEnd::kFinish}) {
> ```

BTW Consider just passing by value? `auto end : ...`

---

*[automotive/calc_ongoing_road_position.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4aqX1jIKXtVzFPXAkM:-L4aqX1jIKXtVzFPXAkN:bt8wj81) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.cc#L49)):*
> ```cpp
>   const T s_dot = PoseSelector<T>::GetSigmaVelocity({rp->lane, lp, velocity});
>   for (const auto& end : {LaneEnd::kStart, LaneEnd::kFinish}) {
>     // Check only the relevent lane end.  If s_dot == 0, check both ends
> ```

BTW Spelling, `relevant`

---

*[automotive/calc_ongoing_road_position.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4ar3Am28ahJ_VVi02l:-L4ar3AngDnda3tu2PTm:b-c6bte5) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.h#L26)):*
> ```objc
> /// road.
> ///
> /// Instantiated templates for the following ScalarTypes are provided:
> ```

BTW Since `ScalarType` is not used as a symbol, can this be reworded to ``... scalar types `T` are provided``:

---

*[automotive/idm_controller.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4arXcCshXTCNqzprIW:-L4arXcCshXTCNqzprIX:b-16v10b) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/idm_controller.cc#L45)):*
> ```cpp
>               .get_index()} {
>   this->DeclareNumericParameter(IdmPlannerParameters<T>());
>   if (road_position_strategy == RoadPositionStrategy::kMemorize) {
> ```

Should this implementation change significantly when caching lands? If so, can this be documented?

---

*[automotive/test/calc_ongoing_road_position_test.cc, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4av8-WRmzkeRK-XUpU:-L4av8-XhSsHla_KqFsI:b-t6m381) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/calc_ongoing_road_position_test.cc#L52)):*
> ```cpp
> }
> 
> static const Lane* GetLaneFromId(const maliput::api::RoadGeometry& road,
> ```

BTW Redundant `static` modifiers for functions declared within an anonymous namespace.

---

*[automotive/test/calc_ongoing_road_position_test.cc, line 142 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4asvoJTtakoZr6Ya0l:-L4asvoK4FX8mDrq4Enc:b-3peuox) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/calc_ongoing_road_position_test.cc#L142)):*
> ```cpp
> 
> GTEST_TEST(CalcOngoingRoadPosition, TestAutoDiff) {
>   std::unique_ptr<maliput::dragway::RoadGeometry> rg(
> ```

BTW Since you do not transfer ownership of `rg`, could you just declare it on the stack?

---

*[automotive/test/mobil_planner_test.cc, line 206 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atD0Oi7iu9uWLRr6S:-L4atD0Oi7iu9uWLRr6T:b-z59isv) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/mobil_planner_test.cc#L206)):*
> ```cpp
>   InitializeMobilPlanner(true /* initial_with_s */);
> 
>   if (context_->get_num_abstract_state_groups() == 1) {
> ```

BTW Could this test be changed to check if the current strategy is using caching, and then  assert that `num_abstract_state_groups == 1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4avNbtp6xmH5W18nt0:b-1tzs3z)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atZOX4esT5jhzSOWe:-L4b-nA-QHB243qrMkBz:bi31dk) (no related file):*
> Is the intent to automatically register the UnrestrictedUpdate if kMemorize is being used?

The idea is to use an abstract state to memorize the last-computed abstract value.  I'm using this particular option within a separate project that doesn't make use of Drake's simulator at all, though I completely agree it should include a `DeclarePeriodicUnrestrictedUpdate`.

> If so, I'm not sure if I see anything in the code that declares an abstract update of any sort.
Did I miss that somewhere?

Additionally, the tests I see only test either (a) the output values or (b) manually trigger an abstract update, but nothing tests whether there is an abstract update registered and the speedup is actually being used.

You're right - these were missing. I'll add these in shortly.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atmQ_vAHX1Pse9doP:-L4bDglw_pbWmxqTH9tG:b-s0exbp) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

At a high level, it seems like this provides a means to overcome a lack of caching in the Systems framework (since this option does not affect the output value, but rather just the computation time).

If so, could a TODO for #4364 be placed to update this once caching lands?
And can the goal of `CalcOngoingRoadPosition` be updated to explicitly mention the word "caching"?
Additionally, could `kMemorize` be renamed to `kCache`?
</blockquote></details>

Really the fundamental issue this addresses is much simpler than a Systems-framework limitation: `ToRoadPosition` is expensive and we should use smarter queries to `ToLanePosition` whenever possible.  Until you mentioned it, I didn't consider this as a caching stop-gap, and after a quick read of #4364 it's not immediately clear how caching could help?

Taking it one step further, I would say that the this would become unnecessary once we have `PoseAggregator` compute `RoadPosition`s for systems to consume as inputs. Still, I'm not sure if caching could help in that direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by jadecastro** [comment]
Review status: 5 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atmQ_vAHX1Pse9doP:-L4cDqpEdVKnEovbBepB:b-k2gfjc) (no related file):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Really the fundamental issue this addresses is much simpler than a Systems-framework limitation: `ToRoadPosition` is expensive and we should use smarter queries to `ToLanePosition` whenever possible.  Until you mentioned it, I didn't consider this as a caching stop-gap, and after a quick read of #4364 it's not immediately clear how caching could help?

Taking it one step further, I would say that the this would become unnecessary once we have `PoseAggregator` compute `RoadPosition`s for systems to consume as inputs. Still, I'm not sure if caching could help in that direction.
</blockquote></details>

On a deeper read of caching, I think it makes sense here.  I've documented that in the functions CalcOngoingRoadPosition, IdmController, and MobilPlanner and also dropped in a TODO in those places to revisit caching when that lands. 

---

*[automotive/calc_ongoing_road_position.cc, line 48 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4aqTjq3IkzP8pPR4SQ:-L4cDm4pLJWRmQFO7jIH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.cc#L48)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Consider just passing by value? `auto end : ...`
</blockquote></details>

Done.

---

*[automotive/calc_ongoing_road_position.cc, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4aqX1jIKXtVzFPXAkM:-L4cDo6_N6Gql9_ycdD5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.cc#L49)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Spelling, `relevant`
</blockquote></details>

Done.

---

*[automotive/calc_ongoing_road_position.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4ar3Am28ahJ_VVi02l:-L4cFurd2p5gchdAqCZD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/calc_ongoing_road_position.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Since `ScalarType` is not used as a symbol, can this be reworded to ``... scalar types `T` are provided``:
</blockquote></details>

Done.

---

*[automotive/idm_controller.cc, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4arXcCshXTCNqzprIW:-L4cHDraiLN1M1wATma6:b-yk5nhs) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/idm_controller.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Should this implementation change significantly when caching lands? If so, can this be documented?
</blockquote></details>

Done. (here and in `mobil_planner.cc`)

---

*[automotive/test/calc_ongoing_road_position_test.cc, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4av8-WRmzkeRK-XUpU:-L4cH_ZrdOhjq08z3mse:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/calc_ongoing_road_position_test.cc#L52)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Redundant `static` modifiers for functions declared within an anonymous namespace.
</blockquote></details>

Done.

---

*[automotive/test/calc_ongoing_road_position_test.cc, line 142 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4asvoJTtakoZr6Ya0l:-L4cIkhX37ycqkRLDDMJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/calc_ongoing_road_position_test.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Since you do not transfer ownership of `rg`, could you just declare it on the stack?
</blockquote></details>

Done.

---

*[automotive/test/mobil_planner_test.cc, line 206 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atD0Oi7iu9uWLRr6S:-L4cHMW9T-rfrwFEqZdy:b22fsry) ([raw file](https://github.com/robotlocomotion/drake/blob/421344d55188e2e710c47b5fcbce5f2c0cd7d333/automotive/test/mobil_planner_test.cc#L206)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this test be changed to check if the current strategy is using caching, and then  assert that `num_abstract_state_groups == 1`?
</blockquote></details>

Done. (also included in `idm_controller_test.cc`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 13 of 13 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-L4atmQ_vAHX1Pse9doP:-L4cMYgnMz-3iZvkI0Ge:bsjq279) (no related file):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

On a deeper read of caching, I think it makes sense here.  I've documented that in the functions CalcOngoingRoadPosition, IdmController, and MobilPlanner and also dropped in a TODO in those places to revisit caching when that lands. 
</blockquote></details>

OK Sweet! (Sorry it took me so long to get back to you!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7927#-:-L4cMhoW3uowFgydvCYR:bnfp4nl)*

**Pull request merged**
