### PR TITLE
Fix a bug in DiscreteLyapunovEquation

### LINKED ISSUE #17634: discrete_lyapunov_equation.cc bug in solution of Equation 4.2
https://github.com/RobotLocomotion/drake/blob/4b98f4375f978a02182093b6dfabdcd3d499c236/math/discrete_lyapunov_equation.cc#L180

There is a possible bug in one of the steps for computing an intermediate term xbar. The factorization of the referenced equation 4.2 is missing an identity subtraction in the diagonal elements of MatrixXd lhs (line 199) 

It should in fact be 
MatrixXd lhs(2 * (m - 2), 2 * (m - 2));
    lhs << s_11(0, 0) * S_1.transpose() - **Identity**, s_11(1, 0) * S_1.transpose(),
        s_11(0, 1) * S_1.transpose(), s_11(1, 1) * S_1.transpose() - **Identity**;

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fixes #17634

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please.

I cannot generate a test case that fails with the previous implementation, but the math in the previous implementation is clearly wrong.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-:-NLwHroO4643dWUw6fuE:b-3v65ym)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
~~I cannot generate a test case that fails with the previous implementation, but the math in the previous implementation is clearly wrong.~~

I added the test that would fail with the old code but now succeed with the new code.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-:-NLyH3GW-RsP7xkls4m_:bw81q65)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NMTsMK_AZlZx0hwXlBS:b4ietm) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
> ```cpp
>     // solving equation 4.2
>     // The equation reads as S₁'x̅s₁₁ - x̅      = -q̅₁₁ - sx̅₁₁s₁,
>     // where S₁ ∈ ℝᵐ⁻²ˣᵐ⁻²; x̅, q̅, s ∈ ℝᵐ⁻²ˣ² and s₁₁, x̅₁₁ ∈ ℝ²ˣ².
> ```

 q̅ =>  q̅_11

s_1 must also be in R 2x2
___
*[`math/discrete_lyapunov_equation.cc` line 180 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTuQ2fA6FjKj11PQ41:-NMTuQ2fA6FjKj11PQ42:belbset) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L180)):*
> ```cpp
>     //  S₁'x̅s₁₁ - x̅ =
>     //
>     //  [ s₁₁(0,0)*S₁' - I,      s₁₁(1,0)*S₁₁] * [x̅[0]]
> ```

what is S_11 (capital?)

I see s11(0,0)*S1(0,*)' + s11(1,0)*S1(1,*)' as the first element?
and s11(0,1)*S1(0,*)' + s11(1,1)*S1(1,*)' as the second?

and this notation as you've changed it is vectorizing before the "this equation can be vectorized" in the line below...?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NMUhK1S7wB-7kThQw-Q:b7rgcha) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
> q̅ => q̅_11

Done

> s_1 must also be in R 2x2

I think S₁ ∈ ℝᵐ⁻²ˣᵐ⁻²? We have S₁'x̅, since x̅ ∈ ℝᵐ⁻²ˣ², S1 must have m-2 columns to match the number of rows in x̅ 
___
*[`math/discrete_lyapunov_equation.cc` line 180 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTuQ2fA6FjKj11PQ41:-NMUiOGZ4KLUMcnzVsF3:b-376vyb) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L180)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

what is S_11 (capital?)

I see s11(0,0)*S1(0,*)' + s11(1,0)*S1(1,*)' as the first element?
and s11(0,1)*S1(0,*)' + s11(1,1)*S1(1,*)' as the second?

and this notation as you've changed it is vectorizing before the "this equation can be vectorized" in the line below...?
</blockquote></details>

Done. Good catch.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks for catching/fixing this!

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-:-NMYhKc6-lGoWihonzpP:bmi2raz)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NMYfX92CiusxH8PQnVl:buxuvyi) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> q̅ => q̅_11

Done

> s_1 must also be in R 2x2

I think S₁ ∈ ℝᵐ⁻²ˣᵐ⁻²? We have S₁'x̅, since x̅ ∈ ℝᵐ⁻²ˣ², S1 must have m-2 columns to match the number of rows in x̅ 
</blockquote></details>

I was talking about the lowercase s_1.  (not the upper case one).  This notation is pretty sketchy!
___
*[`math/discrete_lyapunov_equation.cc` line 180 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTuQ2fA6FjKj11PQ41:-NMYgu5pDm5AF0YjG6qD:b-9l7akr) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L180)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Good catch.
</blockquote></details>

ok.  now that looks right to me.  thanks!
___
*[`math/discrete_lyapunov_equation.cc` line 187 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMYgzZl9y88LoUOOgBH:-NMYgzZl9y88LoUOOgBI:bov7asp) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe5a1b3d29f261d0f47dbdbc8cf166cd682f7ca1/math/discrete_lyapunov_equation.cc#L187)):*
> ```cpp
>     //  x_bar_vec = [x̅[0]' x̅[1]']' where [i] is the ith column
>     //
>     //  lhs = [s₁(0,0)*S₁' - I s₁₁(1,0)*S₁'; s₁₁(0,1)*S₁' s₁₁(1,1)*S₁' - I]
> ```

nit: add commas here between the columns?  the whitespace alone is not sufficiently legible.

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-:-NMZoOcM1uWOKClSeyTt:buxscyd)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NM_15xc33zHD5mziFpv:b-c4a8gg) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I was talking about the lowercase s_1.  (not the upper case one).  This notation is pretty sketchy!
</blockquote></details>

Done.

Agree, it is very confusing to use both lower and upper case S to denote matrices. But we inherit these notations from the cited paper.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-:-NM_AJnA3_oDpOm_hnlP:bnfp4nl)* status: 3 unresolved discussions (waiting on @hongkai-dai and @RussTedrake)

___
*[`math/discrete_lyapunov_equation.cc` line 200 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NM_A4_91_XiM0MEnCo4:-NM_A4_A0RI1biWNb2uF:bqphlrw) ([raw file](https://github.com/RobotLocomotion/drake/blob/bfa78bc69fcdb3f718dcaaea9ac202a5ea42ce19/math/discrete_lyapunov_equation.cc#L200)):*
> ```cpp
>     MatrixXd lhs(2 * (m - 2), 2 * (m - 2));
>     lhs << s_11(0, 0) * S_1.transpose() -
>                Eigen::MatrixXd::Identity(m - 2, m - 2),
> ```

nit This file is already `using Eigen::MatrixXd;` up top (line 15), so we should be consistent with the name throughout.



_Suggestion:_
```cpp
MatrixXd::Identity
```
___
*[`math/discrete_lyapunov_equation.cc` line 202 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NM_ACsbDeY36sEhTQYg:-NM_ACscDVjrixP7D2-8:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/bfa78bc69fcdb3f718dcaaea9ac202a5ea42ce19/math/discrete_lyapunov_equation.cc#L202)):*
> ```cpp
>                Eigen::MatrixXd::Identity(m - 2, m - 2),
>         s_11(1, 0) * S_1.transpose(), s_11(0, 1) * S_1.transpose(),
>         s_11(1, 1) * S_1.transpose() - Eigen::MatrixXd::Identity(m - 2, m - 2);
> ```

nit



_Suggestion:_
```cpp
MatrixXd::Identity
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NMaVbHA7prb_rtSnJD1:b5pa0hh) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.

Agree, it is very confusing to use both lower and upper case S to denote matrices. But we inherit these notations from the cited paper.
</blockquote></details>

no change?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`math/discrete_lyapunov_equation.cc` line 163 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18600#-NMTsMK_AZlZx0hwXlBR:-NMaWEGW-nmrhCryRPJo:b-nvftkw) ([raw file](https://github.com/RobotLocomotion/drake/blob/1c0b50a5344360840d034a2c810516bc8ccb18d0/math/discrete_lyapunov_equation.cc#L163)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

no change?
</blockquote></details>

Done for real.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: 1 unresolved discussion (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18600)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
