### PR TITLE
Make transformSpatialInertia more efficient

### PR DESCRIPTION
**Pull request by tkoolen**
Part of https://github.com/RobotLocomotion/drake/issues/1476.

Based off of https://github.com/RobotLocomotion/drake/pull/1584.

### CODE REVIEW

**Comment by tkoolen** [comment]
The remaining test failures occur because of RigidBodyAddedMasses resulting in nonstandard inertia matrices (direction dependent mass, non-skew-symmetric off-diagonal blocks). I think I'll just check for this special case and use the old way for that case.

**Comment by tkoolen** [comment]
Can't reproduce the testIK failure on my machine after rebasing; we'll see what the build servers say.

**Comment by tkoolen** [comment]
Still can't reproduce on OSX, but I can reproduce on Ubuntu. Same issue as in https://github.com/RobotLocomotion/drake/pull/1383, i.e. rng seed related. Again, the second time I run the test, it passes quickly. Again, if I set the rng seed to 1, the test passes quickly.

What should I do?

**Comment by hongkai-dai** [comment]
I would recommend to fix the seed in `testIK` to 1.

**Comment by tkoolen** [comment]
AppVeyor: Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by RussTedrake** [comment]
I could make a paid account, but I think we are moving to AWS shortly.

**Comment by tkoolen** [comment]
Yay, finally no test failures!

**Comment by RussTedrake** [comment]
I added some more known issues earlier this afternoon for the ones that have been nagging us.

**Comment by tkoolen** [comment]
I also fixed the random number seed to 1. No testIK failures on drake005 and drake006, even allowed ones.

**Comment by tkoolen** [comment]
Closed and reopened to re-trigger build servers after resolution of #1652. Should be good after that I think (didn't have failing unit tests anymore before).

**Comment by tkoolen** [comment]
appveyor just failed because it ran out of time. Good to go?

**Pull request merged**
