### PR TITLE
[optimization] Fix LimitMalloc vs MosekSolver fighting in unit tests

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20154.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20155)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-leak-sanitizer please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20155)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/test/convex_set_test.cc` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20155#-NdpLFyZEk5CXRhSvpHv:-NdpLFyZEk5CXRhSvpHw:bsaepj1) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f4f4df050d9cc56902b8ed62df16c4f27eb36a/geometry/optimization/test/convex_set_test.cc#L22)):*
> ```cpp
> using Eigen::Vector3d;
> 
> // N.B. See also convex_set_solving_test for additional unit test cases.
> ```

Working

Fix the other test program name here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI 

:LGTM: When you've resolved the test file reference.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20155#-:-NdpN9BF-9_q9Tzj1a6u:b23jiw4)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20155)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/test/convex_set_test.cc` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20155#-NdpLFyZEk5CXRhSvpHv:-NdpdEuI6rpBwPV61Q4Q:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/18f4f4df050d9cc56902b8ed62df16c4f27eb36a/geometry/optimization/test/convex_set_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Fix the other test program name here.
</blockquote></details>

Done

**Pull request merged**
