### PR TITLE
Add more tags to ignore to the new_release script

### LINKED ISSUE #21535: The `new_release` script reports the incorrect version for ros_xacro_internal
### What happened?

While doing the monthly external upgrades as part of #21507, `bazel-bin/tools/workspace/new_release` reported that: `ros_xacro_internal needs upgrade from 2.0.10 to xacro-1.7.5` The version to upgrade to should be 2.0.11.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves  #21535

Prior to these updates, the output from the `new_release` script was:
```
abseil_cpp_internal needs upgrade from ed34153e0d9cd15f9b9eb45e86b457e0a495aeea to 0ccc51f9ddbb407d579f8158d5421fbf3eea0524
crate_universe may need upgrade
gymnasium_py needs upgrade from v0.29.1 to v1.0.0a2
gz_math_internal needs upgrade from gz-math7_7.4.0 to gz-math7_7.5.0
msgpack_internal needs upgrade from cpp-6.1.1 to c-6.0.2
mypy_internal needs upgrade from v1.10.0 to v1.10.1
pycodestyle needs upgrade from 2.11.1 to 2.12.0
ros_xacro_internal needs upgrade from 2.0.10 to xacro-1.7.5
rules_python needs upgrade from 0.33.0 to 0.33.2
rust_toolchain may need upgrade
sdformat_internal needs upgrade from sdformat14_14.2.0 to sdformat14_14.4.0
Skipping prerelease 1.13.0rc3 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc3 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc2 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc1 for sympy_py_internal
typing_extensions_internal needs upgrade from 4.12.1 to 4.12.2
vtk_internal needs upgrade from 6bb2d8e2e06bd114707d75e2960f2f2a1493a5b9 to 67b5156276d0ddf234db58ee5faa7568a367755c
```

With the changes, the output is:
```
abseil_cpp_internal needs upgrade from ed34153e0d9cd15f9b9eb45e86b457e0a495aeea to 0ccc51f9ddbb407d579f8158d5421fbf3eea0524
crate_universe may need upgrade
gz_math_internal needs upgrade from gz-math7_7.4.0 to gz-math7_7.5.0
mypy_internal needs upgrade from v1.10.0 to v1.10.1
pycodestyle needs upgrade from 2.11.1 to 2.12.0
Skipping prerelease unstable for ros_xacro_internal
ros_xacro_internal needs upgrade from 2.0.10 to 2.0.11
rules_python needs upgrade from 0.33.0 to 0.33.2
rust_toolchain may need upgrade
sdformat_internal needs upgrade from sdformat14_14.2.0 to sdformat14_14.4.0
Skipping prerelease 1.13.0rc3 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc3 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc2 for sympy_py_internal
Skipping prerelease sympy-1.13.0rc1 for sympy_py_internal
typing_extensions_internal needs upgrade from 4.12.1 to 4.12.2
vtk_internal needs upgrade from 6bb2d8e2e06bd114707d75e2960f2f2a1493a5b9 to 2e9a7c71a29100eac41be37f4ade73b988db2a4d
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21635)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@mwoehlke-kitware for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21635#-:-O0P85OR5BFUxDAAClUY:bnyvoyh)* status: LGTM missing from assignee mwoehlke-kitware, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21635#-:-O0Q7YHi6Knjh8RFA_Wn:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@EricCousineau-TRI for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21635#-:-O0QATGd4hDICaWXeHST:bwu48t1)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21635#-:-O0QT4Kv9k-iC5sE9fp3:bcpz082)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),mwoehlke-kitware

**Pull request merged**
