### PR TITLE
Add remaining bindings for mathematical program.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also reorders `mathematical_program.h` to put the similar functions next to each other.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please, thanks!

cc @russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167#-:-MbnRB1a5AKXPgidSB05:bllpsel)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, nice!!!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167#-:-MboRUb58lyTKvByaCf7:b-ajni59)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 541 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15167#-MboRvnx5rSTXPCOAAwc:-MboRvnx5rSTXPCOAAwd:b-r1ydc4) ([raw file](https://github.com/robotlocomotion/drake/blob/5af901b984de810c3ca6a8b948a82f3fe2c143b9/bindings/pydrake/solvers/mathematicalprogram_py.cc#L541)):*
> ```cpp
>       m, "MathematicalProgram", doc.MathematicalProgram.doc);
>   prog_cls.def(py::init<>(), doc.MathematicalProgram.ctor.doc)
>       .def("Clone", &MathematicalProgram::Clone,
> ```

Working: I'd like this to also be avaialble via `__deepcopy__` and `__copy__`.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 501 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15167#-MboSvTHCB__0XX-cz6w:-MboSvTHCB__0XX-cz6x:b-wztdr7) ([raw file](https://github.com/robotlocomotion/drake/blob/5af901b984de810c3ca6a8b948a82f3fe2c143b9/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L501)):*
BTW This should be wrapped with parentheses:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length
> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15167)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 541 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15167#-MboRvnx5rSTXPCOAAwc:-MboV4_S44LbvW1CSieE:b5htaig) ([raw file](https://github.com/robotlocomotion/drake/blob/5af901b984de810c3ca6a8b948a82f3fe2c143b9/bindings/pydrake/solvers/mathematicalprogram_py.cc#L541)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I'd like this to also be avaialble via `__deepcopy__` and `__copy__`.
</blockquote></details>

Done. (Tested below)
___
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 501 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15167#-MboSvTHCB__0XX-cz6w:-MboV75n1_zkt_kJ-9bT:bb71ctv) ([raw file](https://github.com/robotlocomotion/drake/blob/5af901b984de810c3ca6a8b948a82f3fe2c143b9/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L501)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This should be wrapped with parentheses:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length
> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.
</blockquote></details>

OK Fixed minor formatting.

**Pull request merged**
