### PR TITLE
Implements caching in DirectCollocation.

### LINKED ISSUE #18937: DirectCollocation stores the context for each waypoint
Currently `DirectCollocation` class stores a single context, and re-use that context for all waypoints, when imposing the dynamics constraints. The cache stored in that context is wiped out, when DirectCollocation moves to impose the dynamics constraints for the next waypoint. But that context is very useful, if we later want to impose some constraint that can re-use the cache (for example a kinematic constraint). Here is a use case
```py
dircol = DirectCollocation(diagram, context, ...) # Impose the collocation constraint for all the waypoints.

# Now I want to impose some kinematic constraint on one waypoint, but I will need to re-compute the cache.
diagram_context_waypoint = diagram.CreateDefaultContext()
plant_context_waypoint = plant.GetMyMutableContextFromRoot(diagram_context_waypoint)
dircol.prog.AddConstraint(PositionConstraint(plant, ..., plant_context_waypoint), dircol.state(waypoint_index)[:plant.num_positions()]))
```

I think if DirectCollocation class stores a vector of contexts, then we could re-use the cache in that context for imposing the kinematic constraint.
```cc
class DirectCollocation {
  private:
    std::vector<std::unique_ptr<systems::Context<double>>> waypoints_context_;
};
```

What do you think? @RussTedrake

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #18937.

+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`planning/trajectory_optimization/direct_collocation.h` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQi1sOj-7zqLHYCH4QQ:-NQi1sOj-7zqLHYCH4QR:bo3m1w0) ([raw file](https://github.com/RobotLocomotion/drake/blob/2259904e6cf87b1469fb4d071f85b5dc939458fb/planning/trajectory_optimization/direct_collocation.h#L178)):*
> ```objc
>                 AutoDiffVecXd* xdot) const;
> 
>   std::unique_ptr<systems::System<AutoDiffXd>> owned_system_;
> ```

Could you document that owned_system_ and owned_context_ can both be nullptr?
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQi2y8V6JAkHM1l-oYn:-NQi2y8V6JAkHM1l-oYo:b-fr6pk2) ([raw file](https://github.com/RobotLocomotion/drake/blob/2259904e6cf87b1469fb4d071f85b5dc939458fb/planning/trajectory_optimization/direct_collocation.cc#L293)):*
> ```cpp
> 
>   // Provide a fixed value for the input port and keep an alias around.
>   const InputPort<double>* input_port =
> ```

Sorry I don't understand why we need the input_port_value if we just need the state trajectory.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`planning/trajectory_optimization/direct_collocation.h` line 178 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQi1sOj-7zqLHYCH4QQ:-NQwQ8xRBCFtQFUZntSt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2259904e6cf87b1469fb4d071f85b5dc939458fb/planning/trajectory_optimization/direct_collocation.h#L178)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document that owned_system_ and owned_context_ can both be nullptr?
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQi2y8V6JAkHM1l-oYn:-NQwQGYx7obyQuOtBoA5:bn3n5xp) ([raw file](https://github.com/RobotLocomotion/drake/blob/2259904e6cf87b1469fb4d071f85b5dc939458fb/planning/trajectory_optimization/direct_collocation.cc#L293)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't understand why we need the input_port_value if we just need the state trajectory.
</blockquote></details>

The code should make it pretty clear?  We evaluate the dynamics to get the derivatives and use CubicHermite for the splines.  (I think that is the correct thing to do...)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@SeanCurtis-TRI for platform review please, thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-:-NQwxSp08w0LNM8ZKhHu:btc9pyf)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`planning/trajectory_optimization/direct_collocation.cc` line 293 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQi2y8V6JAkHM1l-oYn:-NQwxLeg0bp90cK1Ggj2:b-45aw60) ([raw file](https://github.com/RobotLocomotion/drake/blob/2259904e6cf87b1469fb4d071f85b5dc939458fb/planning/trajectory_optimization/direct_collocation.cc#L293)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The code should make it pretty clear?  We evaluate the dynamics to get the derivatives and use CubicHermite for the splines.  (I think that is the correct thing to do...)
</blockquote></details>

Ah I missed the derivative is evaluated by x and u.

**Review by RussTedrake — COMMENTED** [review]
-@SeanCurtis-TRI for platform

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-:-NQz2G0E0TYO74Bq3bt3:b20otp3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`planning/trajectory_optimization/direct_collocation.cc` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQz1VJcASY4F2dM29x1:-NR49Rax0Cse7v5dpR8k:b5tyuff) ([raw file](https://github.com/RobotLocomotion/drake/blob/6aa04243fc174430255bd668c93be4c0ed06bb4e/planning/trajectory_optimization/direct_collocation.cc#L131)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

oops.  i realized that this will invalidate the cache... i need to check if the continuous state is already the right values and set it conditionally.  Like kniematic_evaluator_utilities::UpdateContextConfiguration.
</blockquote></details>

Done.  And added a test to confirm.  PTAL.
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 310 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NQz28wMAvq5KNHyeKBJ:-NR49MpxEYz9JZ1YWtR2:b-yxxahp) ([raw file](https://github.com/RobotLocomotion/drake/blob/6aa04243fc174430255bd668c93be4c0ed06bb4e/planning/trajectory_optimization/direct_collocation.cc#L310)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

as a bonus, I could use the cached contexts here, too.
</blockquote></details>

Turns out, that's not a great idea (this context is double, not autodiff).  It's cleaner as is.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; minor notes.

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-:-NR4g-pyCOni033RONLc:bclidda)* status: 6 unresolved discussions (waiting on @RussTedrake)

___
*[`math/autodiff_gradient.h` line 233 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4dLBpDNiJQd44FVbd:-NR4dLBq2aATNE-foTTa:b-y4oksi) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/math/autodiff_gradient.h#L233)):*
> ```objc
> }
> 
> /*
> ```

minor:  This is now a public function so it should have doxygen.



_Suggestion:_
```objc
/**
```
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 40 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4eHNIBB7bBbfDuhux:-NR4eHNIBB7bBbfDuhuy:b-hj8s5h) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L40)):*
> ```cpp
> 
> typedef std::pair<std::unique_ptr<System<AutoDiffXd>>,
>           std::unique_ptr<Context<AutoDiffXd>>> OwnedPair;
> ```

minor:  Not sure what indentation this is meant to be, but ten spaces isn't it.



_Suggestion:_
```cpp
typedef std::pair<std::unique_ptr<System<AutoDiffXd>>,
                  std::unique_ptr<Context<AutoDiffXd>>> OwnedPair;
```
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 43 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4eQMm2H-kysa8L1SE:-NR4eQMm2H-kysa8L1SF:b-mjvt52) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L43)):*
> ```cpp
> 
> OwnedPair MakeAutoDiffXd(const systems::System<double>& system,
>                        const systems::Context<double>& context) {
> ```

typo: indentation



_Suggestion:_
```cpp
OwnedPair MakeAutoDiffXd(const systems::System<double>& system,
                         const systems::Context<double>& context) {
```
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 60 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4enZB8mujMURqgRmw:-NR4enZB8mujMURqgRmx:b2m71xv) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L60)):*
> ```cpp
>     bool assume_non_continuous_states_are_fixed)
>     : DirectCollocationConstraint(
>           MakeAutoDiffXd(system, context), nullptr, nullptr, nullptr, nullptr,
> ```

minor:  Consider if commenting might be kinder to the reader here.



_Suggestion:_
```cpp
          MakeAutoDiffXd(system, context),
          nullptr,  // System
          nullptr, nullptr, nullptr,  // Contexts
```
___
*[`planning/trajectory_optimization/test/direct_collocation_test.cc` line 215 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4fvAt9dYRmatTQUuj:-NR4fvAt9dYRmatTQUuk:b-k7o8li) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/test/direct_collocation_test.cc#L215)):*
> ```cpp
>                                               sample_context[2].get(),
>                                               collocation_context.get());
>   x << 0.1, x[2], .52, x[4], 0.25;
> ```

nit: Inconsistent formatting.



_Suggestion:_
```cpp
  x << 0.1, x[2], 0.52, x[4], 0.25;
```
___
*[`planning/trajectory_optimization/test/direct_collocation_test.cc` line 217 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4fd9f9TrYxcGX4jDp:-NR4fd9f9TrYxcGX4jDq:b-q7dw7z) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/test/direct_collocation_test.cc#L217)):*
> ```cpp
>   x << 0.1, x[2], .52, x[4], 0.25;
>   // This should have a cache hit on sample_context[1], so only evaluation
>   // the dynamics 2 times instead of 3.
> ```

nit: Grammar.



_Suggestion:_
```cpp
  // This should have a cache hit on sample_context[1], and so will only
  // evaluate the dynamics 2 times instead of 3.
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @ggould-tri and @hongkai-dai)

___
*[`math/autodiff_gradient.h` line 233 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4dLBpDNiJQd44FVbd:-NR7pmWY-pBZbHsZKR3N:bkz5ckv) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/math/autodiff_gradient.h#L233)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This is now a public function so it should have doxygen.
</blockquote></details>

Done.  Good catch.
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 40 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4eHNIBB7bBbfDuhux:-NR7psd93RpkudeZEeSG:b-kny6sw) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L40)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Not sure what indentation this is meant to be, but ten spaces isn't it.
</blockquote></details>

Done.  (clang-format chose something slightly different, but hopefully still good)
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 43 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4eQMm2H-kysa8L1SE:-NR7q-yO3zgqtdK_iixO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L43)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

typo: indentation
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/direct_collocation.cc` line 60 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4enZB8mujMURqgRmw:-NR7q9mQA0yRGHGhkWA5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/direct_collocation.cc#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider if commenting might be kinder to the reader here.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/direct_collocation_test.cc` line 215 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4fvAt9dYRmatTQUuj:-NR7qHqP1yOZzG7vtL4d:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/test/direct_collocation_test.cc#L215)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit: Inconsistent formatting.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/direct_collocation_test.cc` line 217 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19019#-NR4fd9f9TrYxcGX4jDp:-NR7qPUM2fFGuyMbPPEU:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5531affff749e266bac7bf7ba601796699f39cb3/planning/trajectory_optimization/test/direct_collocation_test.cc#L217)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit: Grammar.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19019)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
