### PR TITLE
add eigen_matrix_compare.h to the installed header

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix the build error https://drake-jenkins.csail.mit.edu/job/linux-gcc-continuous-ros-debug/380/ for ROS integration

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3721)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-continuous-ros-debug please
@drake-jenkins-bot linux-gcc-continuous-matlab-ros please
@drake-jenkins-bot linux-clang-continuous-ros-debug please
@drake-jenkins-bot linux-clang-continuous-ros-release please

**Comment by hongkai-dai** [comment]
+@liangfok for feature review +@ggould-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3721#-:-KTVd5WDGR8kiEIfJ2U6:b381ft1)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3721#-:-KTVe-ykSpEOJiYYOAPs:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3721#-:-KTVjw8RUfFnvZvM1B97:bnfp4nl)*

**Pull request merged**
