### PR TITLE
[pydrake] Merge all visualization API into the top-level module

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Our design intention for the pydrake API moving forward is a single package "pydrake" with one level of modules (e.g., "visualization") under it.  See https://github.com/RobotLocomotion/drake/issues/11802.

The main programs like `pydrake.visualization.meldis` can remain as additionally-nested modules, but for users' imports we want to provide shorter paths with just a single dot in the module name.

Deprecate the older (longer) paths.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18160)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @trowell-tri this will affect the forthcoming `class ModelVisualizer`.  For that PR, we want the import path to be `pydrake.visualization.ModelVisualizer`.  The module main can still be `python3 -m pydrake.visualization.model_visualizer`.

\CC @EricCousineau-TRI FYI

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 12 of 12 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18160#-:-NF9foglAsu0HRRP-4Q-:bnfp4nl)* status: 6 unresolved discussions, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/visualization/_meldis.py` line 369 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9elHr31jmEEbEloec:-NF9elHr31jmEEbEloed:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/_meldis.py#L369)):*
> ```Python
> 
>     def __init__(self, *, meshcat_host=None, meshcat_port=None):
>         # Bookkeeping for update throtting.
> ```

typo



_Suggestion:_
```Python
throttling
```
___
*[`bindings/pydrake/visualization/_meldis.py` line 452 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9eugYCJJcxEKLGY4s:-NF9eugYCJJcxEKLGY4t:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/_meldis.py#L452)):*
> ```Python
>         # a high rate (e.g., if a sim is running much faster than realtime),
>         # then we should only pass some of them along to MeshCat to avoid
>         # flooding it. The hander merely records the message data; we'll
> ```

typo



_Suggestion:_
```Python
handler
```
___
*[`bindings/pydrake/visualization/meldis.py` line 33 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9fSQ40oQ0iX14kflF:-NF9fSQ40oQ0iX14kflG:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/meldis.py#L33)):*
> ```Python
> 
> class Meldis(_Meldis):
>     """(Deprecated.) The import path pydrake.visualiation.meldis.Meldis is
> ```

typo



_Suggestion:_
```Python
visualization
```
___
*[`bindings/pydrake/visualization/meldis.py` line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9fNUD3LzfE94YgN64:-NF9fNUD3LzfE94YgN65:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/meldis.py#L34)):*
> ```Python
> class Meldis(_Meldis):
>     """(Deprecated.) The import path pydrake.visualiation.meldis.Meldis is
>     deprecated. Use the import path pydrake.visualiation.Meldis instead.
> ```

typo



_Suggestion:_
```Python
visualization
```
___
*[`bindings/pydrake/visualization/meldis.py` line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9fWJJ4K-e091WvkNq:-NF9fWJJ4K-e091WvkNr:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/meldis.py#L40)):*
> ```Python
>     def __init__(self, **kwargs):
>         message = (
>             "The import path pydrake.visualiation.meldis.Meldis is deprecated."
> ```

typo



_Suggestion:_
```Python
visualization
```
___
*[`bindings/pydrake/visualization/meldis.py` line 41 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18160#-NF9fakiEVoul3hqyrYx:-NF9fakiEVoul3hqyrYy:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/125e4ced8b61a8757ef7539d01bbbc5fe57cab55/bindings/pydrake/visualization/meldis.py#L41)):*
> ```Python
>         message = (
>             "The import path pydrake.visualiation.meldis.Meldis is deprecated."
>             " Use the shorter import path pydrake.visualiation.Meldis instead."
> ```

typo



_Suggestion:_
```Python
visualization
```

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

Note that the first commit is just a file rename, with no other changes. The second commit has the only diffs.

In Reviewable, the second commit is shown as r2..r4 in the File Matrix.

The plan is to merge using a merge commit here to preserve history.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18160)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 12 of 12 files at r2, 10 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18160#-:-NFANdCLE2vspfeY9axk:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
At least one full builds has passed; forcing in now to avoid chasing the rebase dragon.

**Pull request merged**
