### PR TITLE
Refined Doxygen Usage Expectations

### PR DESCRIPTION
**Pull request by liangfok**
Added a note to the style guide saying Doxygen comment blocks must:

1. Render correctly.
2. Be readable in an un-rendered state.
3. be as informative as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3584)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-:-KSay270vjcSlYX59KQ0:bdfg11j)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSaz_b1KrGyhq9NiXSM:-KSaz_b1KrGyhq9NiXSN:b-ypht5i) ([raw file](https://github.com/robotlocomotion/drake/blob/91dd574f6e75f865477af9c76cf9f0730a7eea77/drake/doc/code_style_guide.rst#L56)):*
> ```reStructuredText
>     informative as possible when viewed directly in the code. This typically
>     precludes embedding LaTeX into Doxygen comment blocks and using "``@p foo``"
>     to denote a reference to parameter ``foo``.
> ```

Disagree.

"Must render correctly" is too broad.  I would prefer that _if_ the developer uses Doxygen formatting hints, _then_ those must render correctly (in other words, you can't make mistakes, but neither are you obligated to use the markup (other than the comment-opening hint such as `///` that tells Doxygen to render it)).

I see no justification for why `@p foo` should be a requirement.

I think that it should be up to the author whether inline LaTeX is the clearest way to meet their goal.  If the HTML output is super-important, why not allow the code to be slightly more obscure?

Finally, now that there's a PR number, this new style guide rule should cite the github issue (pull) number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by liangfok** [comment]
@jwnimmer-tri, I addressed your comments. PTAL. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSaz_b1KrGyhq9NiXSM:-KSb2GugTmoQ5WM6D71j:b-9xesdk) ([raw file](https://github.com/robotlocomotion/drake/blob/91dd574f6e75f865477af9c76cf9f0730a7eea77/drake/doc/code_style_guide.rst#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Disagree.
> 
> "Must render correctly" is too broad.  I would prefer that _if_ the developer uses Doxygen formatting hints, _then_ those must render correctly (in other words, you can't make mistakes, but neither are you obligated to use the markup (other than the comment-opening hint such as `///` that tells Doxygen to render it)).
> 
> I see no justification for why `@p foo` should be a requirement.
> 
> I think that it should be up to the author whether inline LaTeX is the clearest way to meet their goal.  If the HTML output is super-important, why not allow the code to be slightly more obscure?
> 
> Finally, now that there's a PR number, this new style guide rule should cite the github issue (pull) number.
</details>
Clearly, `@p foo` conveys more information than `foo`. Doesn't it go without saying that Doxygen comments should be as informative as possible?

I downgraded both the informative and readable guidelines to start with "Prefer". PTAL. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-:-KSb3EAexUSoej-fRecX:b-617z9l)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSb3cp0vD8UklVB62X1:-KSb3cp16DkT_GSqJpyO:b-b3n20v) ([raw file](https://github.com/robotlocomotion/drake/blob/2dadd55c7ca83f21482dc17498a4ecdaf00fe3e4/drake/doc/code_style_guide.rst#L56)):*
> ```reStructuredText
>     correctly. See
>     `PR #3584 <https://github.com/RobotLocomotion/drake/pull/3584>`_.
>   * Prefer Doxygen comment blocks that are as informative as possible.
> ```

This seems to broad as to be un-actionable.  How should a developer act on this mandate?  Don't the existing cppguide rules already encompass this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-:-KSb50hNrmp685vE7Djl:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSb3cp0vD8UklVB62X1:-KSb4_-Dlu0xaselEjQ9:b-jpoic3) ([raw file](https://github.com/robotlocomotion/drake/blob/2dadd55c7ca83f21482dc17498a4ecdaf00fe3e4/drake/doc/code_style_guide.rst#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This seems to broad as to be un-actionable.  How should a developer act on this mandate?  Don't the existing cppguide rules already encompass this?
</details>
Done. It's hard to tell whether the following guideline covers the "be as informative as possible" guideline.

https://google.github.io/styleguide/cppguide.html#Class_Comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc9eozOX5yrkuHoCwL:-KSc9eozOX5yrkuHoCwM:byvejz) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L55)):*
> ```reStructuredText
>   * If you decide to use Doxygen formatting hints, then those *must* render
>     correctly. See
>     `PR #3584 <https://github.com/RobotLocomotion/drake/pull/3584>`_.
> ```

I don't think this is the right PR to cite. It doesn't contain any additional information as best I can tell. Did you mean to cite a different one? Otherwise I think you should remove the link since it doesn't add anything.

---

*[drake/doc/code_style_guide.rst, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc7voC_03WACekHh46:-KSc7voC_03WACekHh47:b-ceh4ki) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L57)):*
> ```reStructuredText
>     `PR #3584 <https://github.com/RobotLocomotion/drake/pull/3584>`_.
>   * Prefer Doxygen comment blocks that are readable in both a rendered and
>     un-rendered state.
> ```

BTW,  this is fine but you could add some elaboration, like "This could mean foregoing the most beautiful LaTeX formatting for some serviceable text equations readable in the code. Or, you may want to augment beautiful-but-unreadable formatting with a simplified presentation of the same information to accommodate future programmers, who are likely to see only the header file."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by sherm1** [comment]
Platform review: one comment and a BTW, PTAL and resolve as you see fit. Then, :lgtm:.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-:-KScAAWA5ttSXYz6WZXq:bts6crw)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc9eozOX5yrkuHoCwL:-KScAXequqetW6PjBoU6:b-twngys) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L55)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't think this is the right PR to cite. It doesn't contain any additional information as best I can tell. Did you mean to cite a different one? Otherwise I think you should remove the link since it doesn't add anything.
</details>
FYI Every new rule should have a justification and discussion.  If we're not putting those inline (and we don't seem to be), we should instead cite an issue (including PRs) where it was debated and agreed.  If this PR discussion doesn't present enough justification, then we should add more notes until it does.

Thus, the second bullet in this PR should also cite this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by liangfok** [comment]
I addressed all reviewer comments and re-generated the Sphinx website to verify it looks good. Now waiting on CI to complete.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc9eozOX5yrkuHoCwL:-KSfTGU4cajW3dkCkzTS:b-kr4v71) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI Every new rule should have a justification and discussion.  If we're not putting those inline (and we don't seem to be), we should instead cite an issue (including PRs) where it was debated and agreed.  If this PR discussion doesn't present enough justification, then we should add more notes until it does.
> 
> Thus, the second bullet in this PR should also cite this PR.
</details>
Done. I added a citation to this PR in the second bullet.

---

*[drake/doc/code_style_guide.rst, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc7voC_03WACekHh46:-KSfTx6CG5BI4W5PkhJy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW,  this is fine but you could add some elaboration, like "This could mean foregoing the most beautiful LaTeX formatting for some serviceable text equations readable in the code. Or, you may want to augment beautiful-but-unreadable formatting with a simplified presentation of the same information to accommodate future programmers, who are likely to see only the header file."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-:-KSfTyQF5wsgJmaZjG8L:b75qte7)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc7voC_03WACekHh46:-KSg33R5MhXyc6--Rg75:b4z0nn7) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
</details>
FYI I think this entire second bullet is an over-reaction to a single PR.  Remember that every sentence in the rules document has substantial cost, because we insist that all developers read it and keep up to date.  Why isn't it enough to just write our comments the way we think its best, and others can learn by example, or by code review discussion when something odd happens?  Do we really expect this kind of defect to be so prevalent that we need to preemptively caution folks against it?  I think not, but I won't stand in the way if others feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc7voC_03WACekHh46:-KSgD1R1vYqKBkhjznP9:b-azwtwz) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI I think this entire second bullet is an over-reaction to a single PR.  Remember that every sentence in the rules document has substantial cost, because we insist that all developers read it and keep up to date.  Why isn't it enough to just write our comments the way we think its best, and others can learn by example, or by code review discussion when something odd happens?  Do we really expect this kind of defect to be so prevalent that we need to preemptively caution folks against it?  I think not, but I won't stand in the way if others feel strongly.
</details>
I suppose it's a trade-off between time spent defecting PRs and time spent reading the style guide. In my opinion, the more content in the style guide the better since anything in the style guide should reflect historical group consensus and wisdom and thus reduce the time spent bike shedding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc7voC_03WACekHh46:-KSgLRAoG-usKJI57wOT:b-voao4) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L57)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I suppose it's a trade-off between time spent defecting PRs and time spent reading the style guide. In my opinion, the more content in the style guide the better since anything in the style guide should reflect historical group consensus and wisdom and thus reduce the time spent bike shedding.
</details>
I think some mention of the dual audiences of the documentation is worthwhile -- I have found that programmers often get overly enthusiastic about doxygen's fancy formatting and forget about the fact that a large fraction of the readers will be looking directly at the header file. That dual-readability is a great feature of simple markup languages and we don't want to lose it inadvertently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/code_style_guide.rst, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3584#-KSc9eozOX5yrkuHoCwL:-KSgNljmtvmUMzKiCsQ0:bt0h2wk) ([raw file](https://github.com/robotlocomotion/drake/blob/9298a85c9d22d4530e66cc55721b584c50f0e94d/drake/doc/code_style_guide.rst#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I added a citation to this PR in the second bullet.
</details>
Since @sherm1 mentioned next to his LGTM above that I can resolve this issue as I see fit, I'm going to close this thread and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3584)*

**Pull request merged**
