### PR TITLE
Fix some maliput design doc typos and clarify what constitutes a world-frame.

### PR DESCRIPTION
**Pull request by maddog-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@seancurtis-tri for feature review.

"Why me?" you ask?  This is a precursor (pretext?) to politely asking for a thorough review of the entirety of the "Objectives" and "Geometry Model" sections.  (...which is not something you have to do here or now with this PR.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709#-:-LB7mF_4Dj37T9wBN2KF:b76su4f)*

**Comment by SeanCurtis-TRI** [comment]
Several thoughts:

1. Bring it!
2. You're doing some curious voodoo mashing up emacs org-mode and latex. I'll have to learn me some of that.
3. Some brief editorial thoughts below.

Otherwise: :LGTM:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/maliput/doc/maliput-design.org, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB81n6B-5iv1013Zx1H:-LB81n6B-5iv1013Zx1I:bqlo1l5) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L86)):*
> ```Org
> 
> In super-mathy terms:
>  * The world containing the road network is approximated by an inertial,
> ```

BTW Given the new header title, "inertial" doesn't seem to belong. It's a dynamics concept and not a strictly geometric concept.

---

*[automotive/maliput/doc/maliput-design.org, line 87 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB806EPCU6yiK1ifRV-:-LB806EPCU6yiK1ifRV0:biea9ti) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L87)):*
> ```Org
> In super-mathy terms:
>  * The world containing the road network is approximated by an inertial,
>    locally (if not globally) flat, 3-dimensional Cartesian space
> ```

FYI Typically, a single digit value like 3 would be spelled out as "three".

---

*[automotive/maliput/doc/maliput-design.org, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB80O_997VGaaXfPkzE:-LB80O_997VGaaXfPkzF:b-nadlwj) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L88)):*
> ```Org
>  * The world containing the road network is approximated by an inertial,
>    locally (if not globally) flat, 3-dimensional Cartesian space
>    referred to as the /world frame/.
> ```

FYI You're "referring" to a "space" as a "frame"? @mitiguy could provide more robust language.

---

*[automotive/maliput/doc/maliput-design.org, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB80Bsi413SAoOdETxd:-LB80Bsi413SAoOdETxe:bc7hqcl) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L126)):*
> ```Org
> are typically measured in units of meters.
> 
> The =World=-frame is any right-handed orthonormal inertial coordinate
> ```

FYI I wonder if the term `inertial` here is overkill. It's not a property of the frame, but of how the frame is interpreted (in a dynamics context). However, you *have* lost Cartesian and three-dimensional which do seem relevant.

---

*[automotive/maliput/doc/maliput-design.org, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB816z-Bg1w-bRsGkQ2:-LB816z-Bg1w-bRsGkQ3:bnpw68m) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L140)):*
> ```Org
> and $\hat{y}$ points /North/.
> 
> /In the future:/ the =maliput= API will be extended provide a
> ```

BTW "...extended __*to*__ provide a..."

---

*[automotive/maliput/doc/maliput-design.org, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB81Dqk3ryjmQSDnZU-:-LB81Dqk3ryjmQSDnZU0:b-8m73kd) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L142)):*
> ```Org
> /In the future:/ the =maliput= API will be extended provide a
> description of the geographic coordinate system (if any) used by a
> =RoadGeometry=, as well as the local gravity vector as a function of
> ```

BTW "..as well as __*a*__ local gravity vector..."

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709#-:-LB81TJy3Ot9U9ZZgb1_:b-ivba0w)*

**Comment by maddog-tri** [comment]
Thanks; comments addressed.  I will actually be in HQ on Tu-We-Th this coming week, so you have an opportunity to hand me a hardcopy that has been full-on marked up with red ink.

Oh, this is great:  I believe that it is still Friday enough that I can still summon +@sherm1 for platform review on this. 

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[automotive/maliput/doc/maliput-design.org, line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB81n6B-5iv1013Zx1H:-LB9XGc-53zVWTBeZF01:b-8lfgxd) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L86)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given the new header title, "inertial" doesn't seem to belong. It's a dynamics concept and not a strictly geometric concept.
</blockquote></details>

See longer reply below for why it is showing up (not that that justifies it).  Maybe this heading will expand into, e.g., "Geometry and Dynamics Model" in a future revision.

---

*[automotive/maliput/doc/maliput-design.org, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB80Bsi413SAoOdETxd:-LB9RNb65qCINf6fqDJX:b-tw33dx) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L126)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I wonder if the term `inertial` here is overkill. It's not a property of the frame, but of how the frame is interpreted (in a dynamics context). However, you *have* lost Cartesian and three-dimensional which do seem relevant.
</blockquote></details>

Hmm... what other properties does "Cartesian" imply?  I guess it is more than just orthonormal basis... Euclidean norm? Isotropic?  (I'll put Cartesian and 3d back in, but I want to make sure I understand what I am writing.)

The inertial aspect has appeared here because I would like to add some dynamics concepts to what is nominally "maliput's geometry API". One is calculation of gravity vectors. Another is calculation of curvatures and the accelerations involved to keep objects moving along paths on the road surface, e.g., in order to compute forces involved in cruising around banked turns.  So, it would be nice to just say that the world-frame should be "effectively inertial" (e.g., ECEF is ok, even though it is rotating with Earth, since the first order effects of the rotation would be included in the gravity vector (e.g., the geoid) and the rest could be assumed to be too small to matter).

---

*[automotive/maliput/doc/maliput-design.org, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB816z-Bg1w-bRsGkQ2:-LB9WfpOC5kzynEZcG40:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L140)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "...extended __*to*__ provide a..."
</blockquote></details>

Done.

---

*[automotive/maliput/doc/maliput-design.org, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB81Dqk3ryjmQSDnZU-:-LB9Wywa8rf3gohwWflU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L142)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW "..as well as __*a*__ local gravity vector..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709#-:-LB9YEu8A4YBxHPN3BS3:b54rm87)*

**Comment by sherm1** [comment]
What, do you think a party animal like me would be working at 10pm on a Friday night???
Lucky for you they have wifi here at Burning Man. Platform :lgtm: pending open comments.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[automotive/maliput/doc/maliput-design.org, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB80O_997VGaaXfPkzE:-LB9ajR1AJb7ZlHvwtJo:b-xvq937) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L88)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI You're "referring" to a "space" as a "frame"? @mitiguy could provide more robust language.
</blockquote></details>

FYI agreed -- "space" is what is parameterized by the frame. Consider "3 dimensional Cartesian coordinate system referred to as the /world frame/"

---

*[automotive/maliput/doc/maliput-design.org, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8709#-LB80Bsi413SAoOdETxd:-LB9bBTcCs84Ab3Ce1M5:bhp8kbi) ([raw file](https://github.com/robotlocomotion/drake/blob/ceb9e5eb79e2f3ecb25a4c8de7e6f059f715b5af/automotive/maliput/doc/maliput-design.org#L126)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

Hmm... what other properties does "Cartesian" imply?  I guess it is more than just orthonormal basis... Euclidean norm? Isotropic?  (I'll put Cartesian and 3d back in, but I want to make sure I understand what I am writing.)

The inertial aspect has appeared here because I would like to add some dynamics concepts to what is nominally "maliput's geometry API". One is calculation of gravity vectors. Another is calculation of curvatures and the accelerations involved to keep objects moving along paths on the road surface, e.g., in order to compute forces involved in cruising around banked turns.  So, it would be nice to just say that the world-frame should be "effectively inertial" (e.g., ECEF is ok, even though it is rotating with Earth, since the first order effects of the rotation would be included in the gravity vector (e.g., the geoid) and the rest could be assumed to be too small to matter).
</blockquote></details>

FYI (or FWIW) I find "inertial" fine here, meaning "non-accelerating, non-rotating frame" (or effectively so). That can still apply in a geometric world, it's just not as important.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709#-:-LB9boOI465qucVc_-70:bt5hbrc)*

**Comment by sherm1** [comment]
I don't think I'm blocking anything.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8709#-:-LBDv_8i0Dr1PFEEIzvU:bqxwf3g)*

**Pull request merged**
