### PR TITLE
[inverse_kinematics] Add PositionCost

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #17507.  This is the first half of supporting GlobalIK's
AddPostureCost in the nonlinear IK toolchain.

+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17587)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17587#-:-N79LWRW3ohiF1XK1R88:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`multibody/inverse_kinematics/position_cost.h` line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N79Inj3B_6qwDWD37lh:-N79Inj3B_6qwDWD37li:b-6xpbgr) ([raw file](https://github.com/robotlocomotion/drake/blob/080eca0ff6d7c656993d648f26544818b4e33230/multibody/inverse_kinematics/position_cost.h#L27)):*
> ```objc
>    * @param plant The MultibodyPlant on which the cost is implemented. `plant`
>    *   should be alive during the lifetime of this cost.
>    * @param frameA The frame in which point Q's position is measured.
> ```

nit, Document p_AP, FrameB, p_BQ, C, plant_context as well?

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for Monday platform review, per rotation, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17587#-:-N7B44Kk2khpFgdeodHB:b-jf39j8)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`multibody/inverse_kinematics/position_cost.h` line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N79Inj3B_6qwDWD37lh:-N7B3l0d7stVa10eapry:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/080eca0ff6d7c656993d648f26544818b4e33230/multibody/inverse_kinematics/position_cost.h#L27)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, Document p_AP, FrameB, p_BQ, C, plant_context as well?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17587#-:-N7HR6xH5VeAOHTPyvu2:b-vtj4vo)* status: 7 unresolved discussions (waiting on @RussTedrake)

___
*[`multibody/inverse_kinematics/position_cost.h` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HPF934Iegm1ZMrFd2:-N7HPF934Iegm1ZMrFd3:b11o2wi) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/position_cost.h#L4)):*
> ```objc
> 
> #include <memory>
> #include <optional>
> ```

nit Unused `<memory>` and unused `<optional>`.
___
*[`multibody/inverse_kinematics/position_cost.h` line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HPl8hBdWnzvHrCMQ1:-N7HPl8hBdWnzvHrCMQ2:b-pa6zr9) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/position_cost.h#L59)):*
> ```objc
>                systems::Context<AutoDiffXd>* plant_context);
> 
>   ~PositionCost() override {}
> ```

nit Both the destructor override and `DoEval<Expression>` override should not be inline (https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions).

However, this code is consistent with all of the other IK costs and constraints, so it might make sense to fix the entire folder in a separate PR, keeping the wrong pattern here for now for consistency (maybe with a TODO?).
___
*[`multibody/inverse_kinematics/position_cost.cc` line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HQHtl3Ey0gAc4nM9V:-N7HQHtl3Ey0gAc4nM9W:b-g3aakc) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/position_cost.cc#L56)):*
> ```cpp
> }
> 
> template <typename T, typename S>
> ```

nit Functions in the cc file only should be in the anonymous namespace so that they have private linkage.

https://drake.mit.edu/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables
___
*[`multibody/inverse_kinematics/test/position_cost_test.cc` line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HROql3BC-AdwSelfr:-N7HROql3BC-AdwSelfs:buglmvq) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/test/position_cost_test.cc#L31)):*
> ```cpp
>     std::unique_ptr<Context<T>> context;
>     const Body<T>* body1;
>     const Body<T>* body2;
> ```

nit GSG requires initializers on POD data.



_Suggestion:_
```cpp
    const Body<T>* body1{};
    const Body<T>* body2{};
```
___
*[`multibody/inverse_kinematics/test/position_cost_test.cc` line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HS23-AHvtgvpBx1YM:-N7HS23-AHvtgvpBx1YN:b-aliaoo) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/test/position_cost_test.cc#L73)):*
> ```cpp
> 
>     // MultibodyPlant AutoDiffXd, Eval double.
>     position_cost_ad.Eval(q, &y);
> ```

nit This is re-using the same output `y` from the prior case.  The test would be a slightly  better bug-catcher if it either didn't re-use the output storage, or else zeroed out `y` here prior to re-using it.



_Code quote:_
```cpp
&y
```
___
*[`multibody/inverse_kinematics/test/position_cost_test.cc` line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HSHQ288mi8d5ob-oO:-N7HSHQ288mi8d5ob-oP:b-caouez) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/test/position_cost_test.cc#L87)):*
> ```cpp
>     EXPECT_NEAR(y_ad_ad[0].value(), y_expected, 1e-12);
> 
>     // Check that the two gradients match.
> ```

It seems to me like it might be easy to make a mistake in the implementation where `derivatives().size() == 0` happens here, which the unit test would not detect?
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 430 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HOMql52kdM17LeZVc:-N7HOMql52kdM17LeZVd:b-9oltgl) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/bindings/pydrake/multibody/inverse_kinematics_py.cc#L430)):*
> ```cpp
>             py::keep_alive<1, 2>(),
>             // Keep alive, reference: `self` keeps `plant_context` alive.
>             py::keep_alive<1, 7>(), cls_doc.ctor.doc_double)
> ```

Isn't the `plant_context` the 8th argument, not the 7th?  At least, it's +6 more arguments beyond `plant` which is labeled as the 2nd.

Ditto below.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17587)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`multibody/inverse_kinematics/position_cost.h` line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HPl8hBdWnzvHrCMQ1:-N7HnjYHAxl4xKSjgKwr:bkopggb) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/position_cost.h#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Both the destructor override and `DoEval<Expression>` override should not be inline (https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions).

However, this code is consistent with all of the other IK costs and constraints, so it might make sense to fix the entire folder in a separate PR, keeping the wrong pattern here for now for consistency (maybe with a TODO?).
</blockquote></details>

Done.  I prefer to fix it here; I'm not convinced that a TODO will get it done.  ;-)
___
*[`multibody/inverse_kinematics/position_cost.cc` line 56 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HQHtl3Ey0gAc4nM9V:-N7HoBiA0lULDx5MTP-0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/position_cost.cc#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Functions in the cc file only should be in the anonymous namespace so that they have private linkage.

https://drake.mit.edu/styleguide/cppguide.html#Unnamed_Namespaces_and_Static_Variables
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/test/position_cost_test.cc` line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HS23-AHvtgvpBx1YM:-N7HoYe29tDmXVyUSin5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/test/position_cost_test.cc#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is re-using the same output `y` from the prior case.  The test would be a slightly  better bug-catcher if it either didn't re-use the output storage, or else zeroed out `y` here prior to re-using it.
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/test/position_cost_test.cc` line 87 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HSHQ288mi8d5ob-oO:-N7HoZxr8HL1x5diTBcU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/multibody/inverse_kinematics/test/position_cost_test.cc#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems to me like it might be easy to make a mistake in the implementation where `derivatives().size() == 0` happens here, which the unit test would not detect?
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/inverse_kinematics_py.cc` line 430 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17587#-N7HOMql52kdM17LeZVc:-N7Hof0MEhoveaQ0Nm9p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bdcee8c35b8bcaa29a9ca943e89bd88db4f13e40/bindings/pydrake/multibody/inverse_kinematics_py.cc#L430)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Isn't the `plant_context` the 8th argument, not the 7th?  At least, it's +6 more arguments beyond `plant` which is labeled as the 2nd.

Ditto below.
</blockquote></details>

Done.

**Pull request merged**
