### PR TITLE
Add mass/inertia parameters and gravity to Kuka robot inverse dynamics benchmark test.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6807)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@amcastro-tri 
Platform review +@sherm1 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-:-Kr7t1-nI3lFxa0KhQIK:b-re2b78)*

**Comment by mitiguy** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by amcastro-tri** [comment]
Cool stuff, thanks Paul. Just a few minor comments.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTJysrnAqUFyVCfV9:-KrBTJytzHhCJ2fg88Se:b-fqlkj6) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
> ```objc
>   /// is initialized to 0.0 m/s^2 (not 9.81 m/s^2).
>   ///
>   /// @param[in] gValue Earth's gravitational acceleration in m/s^2.
> ```

`gValue` doesn't follow style guide. Maybe `acceleration_of_gravity`? or just `g`?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTS_K5V2ZyAqGdZMn:-KrBTS_K5V2ZyAqGdZMo:bcgpair) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L161)):*
> ```objc
>   ///
>   /// @param[in] gValue Earth's gravitational acceleration in m/s^2.
>   void  SetEarthGravity(double gValue) { MG_kuka_auto_generated_.g = gValue; }
> ```

BTW, extra space between `void` and method name

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTWv7HZFdzz1tLWXH:-KrBTWv7HZFdzz1tLWXI:b-1fpzju) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L161)):*
> ```objc
>   ///
>   /// @param[in] gValue Earth's gravitational acceleration in m/s^2.
>   void  SetEarthGravity(double gValue) { MG_kuka_auto_generated_.g = gValue; }
> ```

doesn't follow style guide. Why capitalized? all lower separated by `_` for cheap setters/getters.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTfeDKjiBAr4RFIGe:-KrBTfeDKjiBAr4RFIGf:bn8y6n7) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L161)):*
> ```objc
>   ///
>   /// @param[in] gValue Earth's gravitational acceleration in m/s^2.
>   void  SetEarthGravity(double gValue) { MG_kuka_auto_generated_.g = gValue; }
> ```

BTW, I see a very near future of IIWA robots on Mars! why to make this Earth specific? maybe `set_acceleration_of_gravity()`?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBUNzMX9abvAsmZRKa:-KrBUNzMX9abvAsmZRKb:b-gutqst) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L215)):*
> ```cpp
>   // Expected solution for the motor torques to hold the robot static.
>   // Note: The expected solution is specific to this configuration.
>   const double mB = 6.35, mE = 3.5;
> ```

What are mB and mE here? how did you obtain these numbers?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBUJ16FWMBPh5-1wte:-KrBUJ16FWMBPh5-1wtf:b-6qbj5w) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L216)):*
> ```cpp
>   // Note: The expected solution is specific to this configuration.
>   const double mB = 6.35, mE = 3.5;
>   const double gravity_moment_B =  0.0003 * mB * g;
> ```

sry, where does this `0.0003` comes from? what is this math? I am super confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-:-KrBUT8ge6h_AF2uusMn:bqcjmtr)*

**Comment by mitiguy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTJysrnAqUFyVCfV9:-KsGUIpgPf3a5PlN4K-2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`gValue` doesn't follow style guide. Maybe `acceleration_of_gravity`? or just `g`?
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTWv7HZFdzz1tLWXH:-KsGU_tRunqbx8dBTPhV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L161)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

doesn't follow style guide. Why capitalized? all lower separated by `_` for cheap setters/getters.
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 215 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBUNzMX9abvAsmZRKa:-KsGjXE3u7HJ9Ta685aZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L215)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What are mB and mE here? how did you obtain these numbers?
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBUJ16FWMBPh5-1wte:-KsGjZOpDmrbF0RHGnpP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L216)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sry, where does this `0.0003` comes from? what is this math? I am super confused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by amcastro-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTJysrnAqUFyVCfV9:-KsJRne2n9oXqKUWZOsx:b3u3w96) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, "celestial body" excludes the Earth :-). Why not `@param[in] g Celestial body's gravitational acceleration in m/s².` (notice the use of unicode)

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSxBvCiRao_GfOsK8:-KsJSxBvCiRao_GfOsK9:b-tsqvif) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
> ```objc
>   /// is initialized to 0.0 m/s^2 (not 9.81 m/s^2).
>   ///
>   /// @param[in] g Celestial body's gravitational acceleration in m/s^2.
> ```

BTW Please add in this doc in what direction (z-axis I believe?) this gravity is acting.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSDmADu_H97u7c4M4:-KsJSDmADu_H97u7c4M5:b-ditbsq) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L163)):*
> ```objc
>   void set_surface_gravity(double g) { MG_kuka_auto_generated_.g = g; }
> 
>   /// These methods return the mass of links A, B, ... G in the robot.
> ```

I think what you want is an `@name` section here in order to share the same doc among all these methods.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSNFFJvvETRRWhy52:-KsJSNFFJvvETRRWhy53:bf8m0a3) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L164)):*
> ```objc
> 
>   /// These methods return the mass of links A, B, ... G in the robot.
>   /// @retval mass of link in kilograms.
> ```

As-is, this `@retval` will only appear on the first method. I don't really know what it'd do within an `@name`. I'd just remove it since you already explain in the line above that all these methods return the mass. 

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJT_hxXbWcpLiouLP6:-KsJT_hxXbWcpLiouLP7:b-6gey6f) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L217)):*
> ```cpp
>   // (with all joint-angles equal to 0).  The expected solution was calculated
>   // with a visual of the straight-up configuration and a "back-of-the-envelope"
>   // analysis.  The values 0.0003 and 0.0001 (below) are x values of the center
> ```

BTW meters right?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJTbbZJfbdEcu0-zPY:-KsJTbbZJfbdEcu0-zPZ:bjiv2n5) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L217)):*
> ```cpp
>   // (with all joint-angles equal to 0).  The expected solution was calculated
>   // with a visual of the straight-up configuration and a "back-of-the-envelope"
>   // analysis.  The values 0.0003 and 0.0001 (below) are x values of the center
> ```

BTW are these numbers withing the precision of the urdf file? I wonder if we should instead fix the urdf file to make these numbers zero.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJVqwdkv9LLrK1F8n9:-KsJVqwdkv9LLrK1F8nA:b9galat) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L220)):*
> ```cpp
>   // of masses of links B and E, respectively.  The x-values of the center of
>   // masses of links A, C, D, F, G are all 0.  These x-values are from:
>   // drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot-urdf.
> ```

BTW, This test is great but I wonder if we'd rather like a test that would result in larger torques and would not depend as much on these small offsets in the urdf file. Say, what about testing the configuration with the second joint at 90 degrees? an essentially the entire arm in a cantilever position?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by amcastro-tri** [comment]
oh! I almost forget. :lgtm: 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-:-KsJWGkFZL0ZPG7KlfqH:b-4zwi09)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTJysrnAqUFyVCfV9:-KsJWQq-9-5BHEFuzzf3:bntg5cz) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, "celestial body" excludes the Earth :-). Why not `@param[in] g Celestial body's gravitational acceleration in m/s².` (notice the use of unicode)
</blockquote></details>

sry, I meant to say: Why not just `@param[in] g Gravitational acceleration in m/s²`. (notice the use of unicode)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by mitiguy** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KrBTJysrnAqUFyVCfV9:-KsL2tnPn6nkAN5iRqIP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6a200079934cad62b900d95413668ec4e3c1d5fa/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L160)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

sry, I meant to say: Why not just `@param[in] g Gravitational acceleration in m/s²`. (notice the use of unicode)
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSDmADu_H97u7c4M4:-KsL4bORaNvE5fGEvLi6:by2npil) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L163)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think what you want is an `@name` section here in order to share the same doc among all these methods.
</blockquote></details>

Done.  Updated code/comment slightly -  I think the code is now self-documenting. 

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSNFFJvvETRRWhy52:-KsL5Px8851C6IivrMtB:bn64tac) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L164)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

As-is, this `@retval` will only appear on the first method. I don't really know what it'd do within an `@name`. I'd just remove it since you already explain in the line above that all these methods return the mass. 
</blockquote></details>

Done.  See previous comment.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJTbbZJfbdEcu0-zPY:-KsL42LnmqnBSM3wL1ut:bd2vhst) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L217)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW are these numbers withing the precision of the urdf file? I wonder if we should instead fix the urdf file to make these numbers zero.
</blockquote></details>

These x-offset values are also used in the related Solidworks, SimWise, MotionGenesis, and Drake files. I prefer to leave them as is - otherwise, I will need to go back through each of these four packages to fix each one.  

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc, line 220 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJVqwdkv9LLrK1F8n9:-KsL7frO5B15hRN59Qcu:b-dx9pl8) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc#L220)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, This test is great but I wonder if we'd rather like a test that would result in larger torques and would not depend as much on these small offsets in the urdf file. Say, what about testing the configuration with the second joint at 90 degrees? an essentially the entire arm in a cantilever position?
</blockquote></details>

I think we need to exhaustively test this MG code against the MBT results.
If there are differences between the MG results and MBT results, then it may be worthwhile to create another test of the MG results.  But if these two independent codes produce the same results, I think it unlikely that both are wrong.  Lets wait until it is clear that another unit test of the MG code is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by amcastro-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSDmADu_H97u7c4M4:-KsOj2V-a_GXTUTQKdYG:bwjmuly) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L163)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done.  Updated code/comment slightly -  I think the code is now self-documenting. 
</blockquote></details>

I was not commenting on the content of the documentation itself, but how it would get rendered with Doxygen. I recommend compiling the Doxygen documentation and taking a look at the rendered result. You'll see that only `get_mass_link_A()` gets a documentation block but not the other methods. That is why I suggested the `@name`. 

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSNFFJvvETRRWhy52:-KsOjPnJ55jGSJp0CcVP:bishyv1) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L164)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done.  See previous comment.
</blockquote></details>

ditto previous comment.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 166 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsOjSOvqOQxmRiHa8sP:-KsOjSOvqOQxmRiHa8sQ:b-1jdw5o) ([raw file](https://github.com/robotlocomotion/drake/blob/77f64a17b6fff682b718c8d4ede1db3536a41e6b/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L166)):*
> MG_kuka_auto_generated

Implementation internals should not leak into the user's documentation. Users must not know about `MG_kuka_auto_generated`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by mitiguy** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 163 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSDmADu_H97u7c4M4:-KsQLtZHDzCCUjVrPF3i:b-gqhc00) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L163)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I was not commenting on the content of the documentation itself, but how it would get rendered with Doxygen. I recommend compiling the Doxygen documentation and taking a look at the rendered result. You'll see that only `get_mass_link_A()` gets a documentation block but not the other methods. That is why I suggested the `@name`. 
</blockquote></details>

Done.  Thanks for double-checking and recommending that I look at the rendered Doxygen.
I implemented the @name.  Let me know what you think.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsJSNFFJvvETRRWhy52:-KsQQqfjyE0kzKOHNjlH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eabea0b5aaa330a8dd206ef17c558a666b449018/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L164)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto previous comment.
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, line 166 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-KsOjSOvqOQxmRiHa8sP:-KsQQmzibjZflzlFDhc-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/77f64a17b6fff682b718c8d4ede1db3536a41e6b/drake/multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h#L166)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> MG_kuka_auto_generated

Implementation internals should not leak into the user's documentation. Users must not know about `MG_kuka_auto_generated`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807)*

**Comment by sherm1** [comment]
Platform :lgtm:. We will definitely want some more tests when we compare with MultibodyTree -- at least one where the joints are not at 0 to make sure the zeroes aren't hiding any buts. Not needed for this PR though.

---

Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6807#-:-KsQfp1A3S5ZDZQVBMym:bsrsaxr)*

**Pull request merged**
