### PR TITLE
Bugfix attempt.

### PR DESCRIPTION
**Pull request by edrumwri**
Attempt to fix build on Mac.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6211)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-:-KlRTgH-RbGvjjKr9BAu:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-KlRUt6vNtu8KYZEsNmk:-KlRUt6wVQbyWHn-tp0A:b-nxc572) ([raw file](https://github.com/robotlocomotion/drake/blob/e1715916ac0c48b69ed508e8539fbb0fdc855fb2/drake/systems/framework/test/diagram_context_test.cc#L317)):*
> ```cpp
>   context_->set_accuracy(unity);
>   std::unique_ptr<Context<double>> clone = context_->Clone();
>   EXPECT_EQ(clone->get_accuracy().value_or(999), unity);
> ```

BTW, consider adding a comment explaining why 999 as opposed to some other number. Instead of 999, would any value not equal to 1.0 also work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211)*

**Comment by sherm1** [comment]
Is there a way to force Mac builds prior to merge?

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/test/leaf_context_test.cc, line 395 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-KlRYGIm76hDpG5GXSzQ:-KlRYGIm76hDpG5GXSzR:b4009v4) ([raw file](https://github.com/robotlocomotion/drake/blob/e1715916ac0c48b69ed508e8539fbb0fdc855fb2/drake/systems/framework/test/leaf_context_test.cc#L395)):*
> ```cpp
>   context_.set_accuracy(unity);
>   std::unique_ptr<Context<double>> clone = context_.Clone();
>   EXPECT_EQ(clone->get_accuracy().value_or(999), unity);
> ```

BTW should add a comment here and in diagram_context_test.cc saying that this is a hack to get the Mac to build so that no one will be tempted to clean it up later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-:-KlRY_yoX2frEWLD4iOv:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Sure, like this:
@drake-jenkins-bot mac-clang-experimental please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-:-KlRYLtDBYOfaiSuHgXR:bhkaxrd)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/test/leaf_context_test.cc, line 395 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-KlRYGIm76hDpG5GXSzQ:-KlRYngCDijmycM2vtST:b-son1mb) ([raw file](https://github.com/robotlocomotion/drake/blob/e1715916ac0c48b69ed508e8539fbb0fdc855fb2/drake/systems/framework/test/leaf_context_test.cc#L395)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should add a comment here and in diagram_context_test.cc saying that this is a hack to get the Mac to build so that no one will be tempted to clean it up later.
</blockquote></details>

FYI I actually think this is superior.  If the optional is empty, we'll get a tidy message using the not-found-in-nature 999, instead of some uncaught exception detritus.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_context_test.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6211#-KlRUt6vNtu8KYZEsNmk:-KlRcpcE5bSmCOJC_DcX:b-bahw7x) ([raw file](https://github.com/robotlocomotion/drake/blob/e1715916ac0c48b69ed508e8539fbb0fdc855fb2/drake/systems/framework/test/diagram_context_test.cc#L317)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding a comment explaining why 999 as opposed to some other number. Instead of 999, would any value not equal to 1.0 also work?
</blockquote></details>

BTW Started to do this and then I thought that the 999 is so random that any reading of the workings of the `value_or()` function should make the purpose clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6211)*

**Pull request merged**
