### PR TITLE
Homebrew python fix

### LINKED ISSUE #2731: drake-visualizer fails with `Fatal Python error: PyThreadState_Get: no current thread`
i haven't been able to run drake-visualizer on my mac on master.
```
drake008% ./build/bin/drake-visualizer
Fatal Python error: PyThreadState_Get: no current thread
zsh: abort      ./build/bin/drake-visualizer
```

The error seems likely to be related to python version mismatches:
http://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu

I did rerun all of the installation instructions to make sure homebrew was up to date, then do a completely clean build of drake and still got the same error.  Anybody else see this?  Any suggestions?

### PR DESCRIPTION
**Pull request by RussTedrake**
resolves #2731 

currently pointing to my fork, waiting on https://github.com/lcm-proj/lcm/pull/82
but I want to make sure it passes CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2766)

### CODE REVIEW

**Comment by liangfok** [comment]
I just tried this branch on my local machine and the problem persists. My `drake-distro/build/externals/lcm/CMakeCache.txt` contains the following incorrect paths:

```
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/usr/lib/libpython2.7.dylib

//Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND

//Dependencies for the target
lcm-python_LIB_DEPENDS:STATIC=general;lcm;general;/usr/lib/libpython2.7.dylib;
```

I will investigate more in tomorrow.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2766#-:-KMMjaTYCIq-6-Wqtz8f:-1028377372)*

**Comment by liangfok** [comment]
Never mind. It worked after I executed:

```
git submodule update --recursive
cd build
make
```

My new `drake-distro/build/externals/lcm/CMakeCache.txt` looks like:

```
//Path to a program.
PYTHON_CONFIG_EXECUTABLE:FILEPATH=/usr/local/bin/python-config

//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/usr/lib/libpython2.7.dylib

//Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND

//Dependencies for the target
lcm-python_LIB_DEPENDS:STATIC=general;lcm;general;/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib;
```

Since `drake-visualizer` worked on my local machine with this branch, :lgtm_strong: .

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2766#-:-KMMlDyVeWq8amuEFGjs:1060392364)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2766)*

**Comment by liangfok** [comment]
+@sherm1 for platform review since today's Monday.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2766#-:-KMPI5MNy2B6hz5sQ8v0:-955106541)*

**Comment by sherm1** [comment]
@RussTedrake, this PR still has "do not merge" and "do not review" tags. The build succeeded -- should the tags be removed?

**Comment by jamiesnape** [comment]
FYI @mwoehlke-kitware.

**Comment by RussTedrake** [comment]
@sherm1 -- i am waiting for the upstream lcm PR to be accepted, so I can change the pointer from my fork of LCM back to upstream.  then i will remove those tags.

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, does #2775 also fix the issue? If yes, I think it is a cleaner fix to LCM. (See also my comments in lcm-proj/lcm#82.) It passes CI, but I think that isn't a sufficient test?

**Comment by mwoehlke-kitware** [comment]
Upstream took my fix, so presumably we want to merge #2775 instead of this.

**Pull request closed without merging**
