### PR TITLE
Update dReal and ibex-lib

### PR DESCRIPTION
**Pull request by soonho-tri**
EDIT(eric): Resolves #11635

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11635)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for platform-review, please.
Could you also test if this PR fixes #11620 ?

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-cxx17-release please

**Comment by EricCousineau-TRI** [comment]
Added closing statement for issue (I think) to the top.

**Comment by soonho-tri** [comment]
OK. I've added "do not merge" label. I'll wait until the c++17 build finishes.

`CC=gcc-8 CXX=g++-8 bazel test //solvers:dreal_solver_test --cxxopt=-std=c++17 --host_cxxopt=-std=c++17` genererated no errors on my Xenial machine. So I expect it passes.

**Comment by soonho-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-bionic-gcc-bazel-experimental-everything-cxx17-release/6 is 🔵.

**Pull request merged**
