### PR TITLE
[lcm] Add LcmBuses and related config functions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17112.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17614)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@sammy-tri for platform review per schedule, please.

Note that r1 is the files copied from Anzu as-is, and r2 are the revisions to build inside Drake.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17614#-:-N7WiDa-EUdQ-ar_4C7A:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri and @sammy-tri)

___
*[`systems/lcm/lcm_buses.h` line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17614#-N7Wg-8j08pejc5F-xyo:-N7Wg-8j08pejc5F-xyp:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc106606e1e2253d2d93f208c8e5610c102170c/systems/lcm/lcm_buses.h#L18)):*
> ```objc
> 
> Note that this class is shallow-const.  A user of a const LcmBuses object
> cannot add or remove buses, but can retrive a non-const DrakeLcmInterface
> ```

typo



_Code quote:_
```objc
retrive
```
___
*[`systems/lcm/lcm_config_functions.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17614#-N7WeuNx26p6IvtrtQcs:-N7WeuNx26p6IvtrtQct:b-6slqbz) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc106606e1e2253d2d93f208c8e5610c102170c/systems/lcm/lcm_config_functions.h#L15)):*
> ```objc
> namespace lcm {
> 
> /** Given a list of LCM buses, adds an LcmInterfaceSystem for each bus within
> ```

BTW this seems either stale or incorrect. It's not a list, and they aren't buses, but rather parameters/descriptions/configurations.



_Code quote:_
```objc
a list of LCM buses
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17614)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @rpoyner-tri and @sammy-tri)

___
*[`systems/lcm/lcm_config_functions.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17614#-N7WeuNx26p6IvtrtQcs:-N7WmXOK44NVfDAIhcO1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7cc106606e1e2253d2d93f208c8e5610c102170c/systems/lcm/lcm_config_functions.h#L15)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW this seems either stale or incorrect. It's not a list, and they aren't buses, but rather parameters/descriptions/configurations.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17614)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17614#-:-N7XVZzp373wSah37oRS:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri)

**Pull request merged**
