### PR TITLE
make random source play better with system context initialization

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805#-:-LCHIe3TALX5CTyx4c2g:b-qf68jg)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[systems/primitives/random_source.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCTisC5DnDsrIuJjhBC:-LCYr84AE1-Lg9QJReMW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b77fb15a896fd6bb1be118a379756fe7ce3f8f8/systems/primitives/random_source.h#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing `DRAKE_DEFAULT_COPY...`
</blockquote></details>

Done.

---

*[systems/primitives/random_source.h, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCTib7h13vJ-AN4xMyG:-LCYs2YR2QbANQXLYVtI:bmw2xyi) ([raw file](https://github.com/robotlocomotion/drake/blob/4b77fb15a896fd6bb1be118a379756fe7ce3f8f8/systems/primitives/random_source.h#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The base class contract makes no promises about what value `state` will hold.  As such, this method should overwrite all elements of it.  Here, at least the `distribution` would carry forward any prior internal state; for the default mt generator setting the seed would clear all state, but its difficult to tell if that would apply to all possible template values for the generator.

To be as clear as possible I'd suggest just assigning a fresh RandomState here.  (Then we don't need set_random_seed anymore either.)
</blockquote></details>

Done.  (I believe this copy assignment was what you meant...)

---

*[systems/primitives/random_source.h, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCTlQuf3CKkB-8SPh_A:-LCYs3ErDtwRmHTQq0GW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b77fb15a896fd6bb1be118a379756fe7ce3f8f8/systems/primitives/random_source.h#L123)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto to above.
</blockquote></details>

Done.

---

*[systems/primitives/random_source.h, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCTiQTH9rzJHFxPeECe:-LCYrUsaAlDyxKGyDinJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b77fb15a896fd6bb1be118a379756fe7ce3f8f8/systems/primitives/random_source.h#L136)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This default value is misleading, because it is never used.

I suggest removing the `{}` entirely and marking this `const` instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review per schedule, please.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/random_source.h, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCTib7h13vJ-AN4xMyG:-LCYw88u8w9iG7SIDJN1:bso2xj2) ([raw file](https://github.com/robotlocomotion/drake/blob/4b77fb15a896fd6bb1be118a379756fe7ce3f8f8/systems/primitives/random_source.h#L110)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (I believe this copy assignment was what you meant...)
</blockquote></details>

Yes; thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805#-:-LCYwBjkDK9TyyOzWEgU:b-zfiiwp)*

**Comment by sammy-tri** [comment]
:lgtm: with one formatting issue

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/primitives/random_source.h, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCZR2446IM5p_mwMXQw:-LCZR2446IM5p_mwMXQx:baz754j) ([raw file](https://github.com/robotlocomotion/drake/blob/198abecab26dca89f9786ef3f847cf97cd7fdb8c/systems/primitives/random_source.h#L117)):*
> ```objc
> 
>   void SetRandomState(const Context<double>& context, State<double>* state,
>                               RandomGenerator* generator) const override {
> ```

odd indentation

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805#-:-LCZRPgM5c_rHk0Mkc1u:b-menq8t)*

**Comment by RussTedrake** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/primitives/random_source.h, line 117 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8805#-LCZR2446IM5p_mwMXQw:-LC_XsCo2ShTTOPVR98n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/198abecab26dca89f9786ef3f847cf97cd7fdb8c/systems/primitives/random_source.h#L117)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

odd indentation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8805)*

**Pull request merged**
