### PR TITLE
Enable multi-threading for `call_python_client`

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This implements Step 2 of #7487, enabling multi-threading for `call_python_client`, such that you can interact with plots while still being able to send additional commands.

~This is WIP until #7496 merges.~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7527)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-37lj87kkgX13Pi98j:bjg4c68)*

**Comment by sammy-tri** [comment]
Should WIP be removed from the title?  (also first pass complete)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3cK2iFBp3tcWfGlso:-L-3cK2iFBp3tcWfGlsp:b-sq1urc) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L102)):*
> ```Python
> 
> 
> def default_globals(set_interactive=True):
> ```

The newly added `set_interactive` argument is both undocumented and unused (among other things, this makes it difficult to figure out how to use in the future).

---

*[drake/common/proto/call_python_client.py, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3cb4j-e6dWDQGLEP8:-L-3cb4kUwdkMZXwVNuw:b-ul9pf5) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L115)):*
> ```Python
> 
>     # Where better to put this?
>     if set_interactive is not None:
> ```

It's not obvious from the rest of the code that `None` is a valid option here (or what the difference between `None` and `False` would be)

---

*[drake/common/proto/call_python_client.py, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3hj9pa38s2yJ5TB4V:-L-3hj9qceilWZ_zXPi-:b-wailzq) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L333)):*
> ```Python
>                     # Process all messages.
>                     for msg in queue:
>                         self._execute_message(msg)
> ```

BTW I'm guessing that executing the messages is sufficiently fast that we don't care about blocking the receiver while we do it?  (we could copy/clear the queue and then execute without holding the lock).  A comment to this effect could be helpful.

---

*[drake/common/proto/test/call_python_full_test.sh, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3ioI9Y90uDaxj6eKP:-L-3ioI9Y90uDaxj6eKQ:b-sjixjq) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/test/call_python_full_test.sh#L27)):*
> ```Shell
> 
> # Start Python binary in the background.
> ${py_client_cli} --no_threading --no_loop &
> ```

This seems like a bit of a hole in our test coverage.  Is it at least worth a comment or a TODO?  (I assume getting the test to work is tricky?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-3bgx3PQ1R_upp3D8E:b-orrev9)*

**Comment by kunimatsu-tri** [comment]
Sorry for delayed. PTAL.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFUd9peZLGtak0Fpu:-L-DFUd9peZLGtak0Fpv:b-g2d9gt) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L108)):*
> ```Python
>     with `matplotlib`.
>     """
>     import numpy as np
> ```

You've imported this at the top already.

---

*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-DFpxvhadSf61jc6cV:bk4bbo4) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
> ```Python
>     """
>     import numpy as np
>     from mpl_toolkits.mplot3d import Axes3D
> ```

Both [PEP8](https://www.python.org/dev/peps/pep-0008/#imports) and [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html#Imports_formatting) say "Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.".

If there wouldn't any particular reason like significant performance improvement, could you put these `import`s to the top of the file?

---

*[drake/common/proto/call_python_client.py, line 449 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DGqngXcz3TkBUZ49g:-L-DGqngXcz3TkBUZ49h:b-in9qpy) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L449)):*
> ```Python
> 
> def main(argv):
>     import argparse
> ```

Same as the comment about `import` above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-DH273gpOetSP_tE-0:bq35qdm)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3cK2iFBp3tcWfGlso:-L-E6zC_02QI34H5qMHY:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L102)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The newly added `set_interactive` argument is both undocumented and unused (among other things, this makes it difficult to figure out how to use in the future).
</blockquote></details>

Done. Removed.

---

*[drake/common/proto/call_python_client.py, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFUd9peZLGtak0Fpu:-L-DobwO0nME0V0ujkvs:bt2hny9) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L108)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

You've imported this at the top already.
</blockquote></details>

I would like to keep this section as-is. Doing the imports in this fashion gives precise control over the `globals()` that are available to the user (see the return statement), rather than having the globals tied to this file.
Additionally, it consolidates dependencies and relaxes them to be conditional dependencies.

For this reason, I re-import some symbols (such as `numpy`) to put them in `locals()`.

---

*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-DoyfzCP5hXYMfGWCM:b3u90g2) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Both [PEP8](https://www.python.org/dev/peps/pep-0008/#imports) and [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html#Imports_formatting) say "Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.".

If there wouldn't any particular reason like significant performance improvement, could you put these `import`s to the top of the file?

</blockquote></details>

Same rationale as stated above; the goal here is to consolidate what dependencies are needed for the user calls, not the client. If, for whatever reason, a user does not have `matplotlib` installed, but still wishes to use this functionality in their own client, they can simply swap out the globals returned by this function for another set of globals (e.g. from `IPython` session).

---

*[drake/common/proto/call_python_client.py, line 115 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3cb4j-e6dWDQGLEP8:-L-E78yaITFNS6bO12dM:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L115)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's not obvious from the rest of the code that `None` is a valid option here (or what the difference between `None` and `False` would be)
</blockquote></details>

Done. Removed.

---

*[drake/common/proto/call_python_client.py, line 333 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3hj9pa38s2yJ5TB4V:-L-E7CDTyM9KBecZBny9:b-ue78z1) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L333)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm guessing that executing the messages is sufficiently fast that we don't care about blocking the receiver while we do it?  (we could copy/clear the queue and then execute without holding the lock).  A comment to this effect could be helpful.
</blockquote></details>

Done. Actually ran into this issue when testing for errors (not all messages were consumed). Tested out using `Queue`, seems to let the test pass now.

---

*[drake/common/proto/call_python_client.py, line 449 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DGqngXcz3TkBUZ49g:-L-E7N3ti8P6MphdqooG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L449)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Same as the comment about `import` above.
</blockquote></details>

Done.

---

*[drake/common/proto/test/call_python_full_test.sh, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-3ioI9Y90uDaxj6eKP:-L-E7i6rcAxJYAvtsdHa:b62365j) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/test/call_python_full_test.sh#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This seems like a bit of a hole in our test coverage.  Is it at least worth a comment or a TODO?  (I assume getting the test to work is tricky?)
</blockquote></details>

Done. Added more comprehensive test coverage (albeit with odd little bash constructs).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by kunimatsu-tri** [comment]
*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-EAWm5RvSEGtGof5i4:b-4xlknp) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same rationale as stated above; the goal here is to consolidate what dependencies are needed for the user calls, not the client. If, for whatever reason, a user does not have `matplotlib` installed, but still wishes to use this functionality in their own client, they can simply swap out the globals returned by this function for another set of globals (e.g. from `IPython` session).
</blockquote></details>

I guess I'm confused by the terms of `user calls` and `client`. Could you briefly explain the architecture and the terminology you use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-ECBgPx2s71ay80WOa:bube56j) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

I guess I'm confused by the terms of `user calls` and `client`. Could you briefly explain the architecture and the terminology you use?
</blockquote></details>

Yup! "User calls" would be the Python code that the user calls from C++, e.g. "plot(x, y)" or "print(15)".
"Client" is the actual client code, e.g. "CallPythonClient".

Does that make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by kunimatsu-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-FdUBauDmtNeSYpuIA:bhlbegj) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yup! "User calls" would be the Python code that the user calls from C++, e.g. "plot(x, y)" or "print(15)".
"Client" is the actual client code, e.g. "CallPythonClient".

Does that make sense?
</blockquote></details>

Aha, I got it.  Then, could you leave a comment explaining why these imports exist here for future readers.

With the comment, I'll mark this as satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by EricCousineau-TRI** [comment]
There were some failures on `xenial-clang`, which looked like the client was not consuming all messages. Not sure why this is happening with the present usage of `Queue`...

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/proto/call_python_client.py, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-DFpxvhadSf61jc6cU:-L-JEWc8RBwMLcssH3Nq:bkhhc1r) ([raw file](https://github.com/robotlocomotion/drake/blob/99fa119cb96700e36c2780186818686a4ea85d44/drake/common/proto/call_python_client.py#L109)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

Aha, I got it.  Then, could you leave a comment explaining why these imports exist here for future readers.

With the comment, I'll mark this as satisfied.
</blockquote></details>

Done. Sorry for not including that earlier!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-JEiDFeNaezLvRjlKq:b-m8ggiy)*

**Comment by kunimatsu-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-JdPzGry_WORXY22a3:bnfp4nl)*

**Comment by kunimatsu-tri** [comment]
Reviewed 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by EricCousineau-TRI** [comment]
Er... The tests now pass on all CI machines. Will try once more, removing the extra sleeping in Python.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-VG3Rntpx9cY6rimsZ:b-kqboya)*

**Comment by sammy-tri** [comment]
Is the plan to merge this with `fifo_test.py` still enabled?  Or is that only  in this PR temporarily while you investigate CI?

---

Reviewed 1 of 3 files at r3, 3 of 4 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/proto/test/call_python_full_test.sh, line 104 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L-cLxLNbFY9PSOGU86V:-L-cLxLNbFY9PSOGU86W:b15qklp) ([raw file](https://github.com/robotlocomotion/drake/blob/30f8653db67a10911d01ffcc4a9ae2b9d8e788d7/drake/common/proto/test/call_python_full_test.sh#L104)):*
> ```Shell
> threading-loop() {
>     # Use `exec` so that we inherit SIGINT handlers.
>     # @ref https://stackoverflow.com/a/44538799/7829525
> ```

BTW thanks for this link!  I didn't know that `exec` with `&` was a special thing (or even a meaningful concept)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-cOyEoKrtYO-gGjtkL:by0z4s1)*

**Comment by EricCousineau-TRI** [comment]
The plan would be to remove `fifo_test` once this is debugged. I can re-include it if it's ever useful.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L-cj_BLBF7J1qz-OjdD:b-crr6od)*

**Comment by EricCousineau-TRI** [comment]
Found the wily bug - was just some simple synchronization on my side (effectively calling `queue.join()` - d'oh!).
Unfortunately, prior changes have been lost to Reviewable - sorry about that!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L06l8v8qv-ex6K6vHRM:b-8btwzb)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

Failure due to `install` timeouts - I noticed that the printouts from `install` also took a while on my machine.
Tagging for future reference: [Jenkins Build 5371](https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-debug/5371/)

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/call_python_client.py, line 117 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L09oU0sByCrfpKd38Ft:-L09oU0sByCrfpKd38Fu:brypfhc) ([raw file](https://github.com/robotlocomotion/drake/blob/791a078993c78a9d31cf80da69bb8d1727675159/common/proto/call_python_client.py#L117)):*
> ```Python
>     _old_vars = locals().keys()
>     # Execute with context.
>     exec _stmt
> ```

This actually won't update existing primitive-type variables. Need to fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by EricCousineau-TRI** [comment]
I believe I've simplified the problem by just making the "producer" thread a daemon, so that Python can simply ignore it when shutting down (even if it is blocking on a `read` or on some mutex).

As the comments below indicate, I kept on getting intermittent deadlocks when trying to use `queue.join()` in the producer thread (and clearing in the consumer), so I just went the simpler route.
Also removed the `select` statements as they should no longer needed.

(Commits are now separated and curated.)

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/call_python_client.py, line 117 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L09oU0sByCrfpKd38Ft:-L0CQPeNKNYzPfXsfMej:b7mbcvh) ([raw file](https://github.com/robotlocomotion/drake/blob/791a078993c78a9d31cf80da69bb8d1727675159/common/proto/call_python_client.py#L117)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

This actually won't update existing primitive-type variables. Need to fix.
</blockquote></details>

Done.
@sammy-tri Could you OK this comment? (Reviewable says it needs one more person.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L0CQmHKBHY1A442_fJ7:b-ld4y9a)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please.

(Due to unrelated failures in `//bindings/pydrake:common_install_test` and `//tools/workspace/lcm:install_test`.)

**Comment by sammy-tri** [comment]
:lgtm: with one BTW

---

Reviewed 1 of 8 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_full_test.sh, line 21 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L0FPEJM5tMbVCSW2NZ9:-L0FPEJM5tMbVCSW2NZA:b-goh17f) ([raw file](https://github.com/robotlocomotion/drake/blob/2129df0e584a78276484fb0de41883ae1ed22f14/common/proto/test/call_python_full_test.sh#L21)):*
> ```Shell
> cc_bin=${1}
> py_client_cli=${2}
> filename=/tmp/python_rpc
> ```

BTW I'd be happier if these were both unique filenames from `tempfile` rather than a fixed name which could be stale (e.g. previous run aborted and left the file around, executing multiple builds on the same machine, etc)  (admittedly you'd then need to pass `done_file` to `call_python_test` which doesn't immediately seem like a problem...)   

Oh, I just realized that `/tmp/python_rpc` is hardcoded in `call_python.cc` with a TODO about making it configurable.  I suppose I could live with a TODO here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-:-L0FRVzwwRM2Sm-nZGfy:byg1fkw)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_full_test.sh, line 21 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/7527#-L0FPEJM5tMbVCSW2NZ9:-L0FTi9im0D-aj6bsfQR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2129df0e584a78276484fb0de41883ae1ed22f14/common/proto/test/call_python_full_test.sh#L21)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'd be happier if these were both unique filenames from `tempfile` rather than a fixed name which could be stale (e.g. previous run aborted and left the file around, executing multiple builds on the same machine, etc)  (admittedly you'd then need to pass `done_file` to `call_python_test` which doesn't immediately seem like a problem...)   

Oh, I just realized that `/tmp/python_rpc` is hardcoded in `call_python.cc` with a TODO about making it configurable.  I suppose I could live with a TODO here too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7527)*

**Pull request merged**
