### PR TITLE
rename SymbolicSystemInspector -> SystemSymbolicInspector 

### PR DESCRIPTION
**Pull request by RussTedrake**
because I'm about to write a SymbolicSystem class, which is different in an important way

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6913)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@soonho-tri for both levels of review please.
this is a trivial change (just a refactor, no functionality changes)

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6913#-:-KsLSQd_eQWM3xJj0IHZ:bsz9r7r)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6913#-:-KsLU0eM58uL-T9rd2wK:bnfp4nl)*

**Comment by RussTedrake** [comment]
i'm still on the fence about the name.  asked for feedback on slack (#system_framework)

**Comment by soonho-tri** [comment]
@RussTedrake , I actually merged it before you put the label. Please let me know if you want to revert it.

**Pull request merged**
