### PR TITLE
Remove EulerFloatingJointState

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Its only current purposes are to:

(1) log to LCM that the roll, pitch, and elevation of a `SimpleCar` are all zero -- which useless; and

(2) offset the logged position to align with `prius.sdf` reference origin, instead of the (pose aggregator) origin that all of the, e.g., sensors use -- which is confusing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6787)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.
+@sherm1 for platform review per rotation, please.

/CC @liangfok

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-:-Kr0th2NG6qD7mKIprxs:bnfp4nl)*

**Comment by sherm1** [comment]
Platform :lgtm:, one FYI.

---

Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car_gen.sh, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-Kr27uUn1Q9AAcFZR3DK:-Kr27uUoXQ7Q7E6jDL73:b7yzc6f) ([raw file](https://github.com/robotlocomotion/drake/blob/698498d8732f6537a8df5dd3cfec4806809c6074/drake/automotive/simple_car_gen.sh#L25)):*
> ```Shell
> gen_lcm_and_vector_from_proto "simple car params" $drake/automotive/simple_car_params.named_vector
> gen_lcm_and_vector_from_proto "trajectory car state" $drake/automotive/trajectory_car_state.named_vector
> gen_vector_proto "trajectory car params" $drake/automotive/trajectory_car_params.named_vector
> ```

FYI this changed from "gen_vector_from_proto" to "gen_vector_proto". Is that related to the Euler state stuff somehow? (Just pointing it out in case it wasn't intentional.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-:-Kr28rm0hCFzJLM1gLKs:bmt000q)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car_gen.sh, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-Kr27uUn1Q9AAcFZR3DK:-Kr2CbBKeUo3Q9tVElvh:bn1ziz4) ([raw file](https://github.com/robotlocomotion/drake/blob/698498d8732f6537a8df5dd3cfec4806809c6074/drake/automotive/simple_car_gen.sh#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI this changed from "gen_vector_from_proto" to "gen_vector_proto". Is that related to the Euler state stuff somehow? (Just pointing it out in case it wasn't intentional.)
</blockquote></details>

OK Yes intentional, per the second commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6787)*

**Comment by jadecastro** [comment]
:lgtm: and the :demo runs fine on my machine.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/automotive_simulator.cc, line 21 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-Kr2Z-KU0P3A8WipYzns:-Kr2Z-KU0P3A8WipYznt:bd43xfb) ([raw file](https://github.com/robotlocomotion/drake/blob/9334bf94716533473a545c4557b1454b06ff1df1/drake/automotive/automotive_simulator.cc#L21)):*
> ```cpp
> #include "drake/lcm/drake_lcm.h"
> #include "drake/lcmt_viewer_draw.hpp"
> #include "drake/multibody/joints/floating_base_types.h"
> ```

BTW (probably unrelated): unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6787#-:-Kr2Udw0lykycsaL8z8l:b-wptjzi)*

**Comment by jwnimmer-tri** [comment]
I'll check on the includes in a separate PR.

**Comment by jwnimmer-tri** [comment]
> Unused `#include "drake/multibody/joints/floating_base_types.h"`

Actually, `GenerateAndLoadRoadNetworkUrdf` uses it at:
```c++
  parsers::urdf::AddModelInstanceFromUrdfFileToWorld(
      urdf_filepath,
      drake::multibody::joints::kFixed,
      tree_.get());
```

**Pull request merged**
