### PR TITLE
Introduce PoseVector, and add a PoseVector output to SimpleCar.

### PR DESCRIPTION
**Pull request by david-german-tri**
@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5308)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Oh, hey, CI says I need to write some CMake changes.  I'm pretty pleased I can get this far in the development process before CMake even crosses my mind...

I'll get that fixed up ASAP (along with the lint errors and one failing test on Bazel), but I don't think any of it blocks review.

**Comment by liangfok** [comment]
Completed first pass.

---

Reviewed 8 of 8 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[drake/automotive/simple_car.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlSMyM6Ym8Y5QBxz4L:-KdlSMyM6Ym8Y5QBxz4M:ba52h1d) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/automotive/simple_car.cc#L84)):*
> ```cpp
>   pose->set_translation(Eigen::Translation<T, 3>(state.x(), state.y(), 0));
>   const Vector3<T> z_axis{0.0, 0.0, 1.0};
>   Eigen::AngleAxis<T> rotation(state.heading(), z_axis);
> ```

BTW, can this be `const`?

---

*[drake/automotive/simple_car.cc, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlSlymWc5hoHTQ2Mb1:-KdlSlymWc5hoHTQ2Mb2:baff45u) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/automotive/simple_car.cc#L220)):*
> ```cpp
>       return std::make_unique<PoseVector<T>>();
>     default:
>       return nullptr;
> ```

BTW, is this actually an error condition? If so, should it abort instead?

---

*[drake/systems/rendering/pose_vector.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlVHVSSqIw3t7PD46f:-KdlVHVT6JYIt5RSuKqZ:b3wg89e) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/pose_vector.h#L13)):*
> ```objc
> /// A 7-vector representing the transform of frame A in the world frame, X_WA,
> /// in the form {R_WA, p_WA}, where R is represented as a quaternion, and p as
> /// an x-y-z translation.
> ```

BTW, consider documenting the ordering of the values in this `BasicVector`. I assume it's x, y, z, qw, qx, qy, qz? Maybe we can even copy/paste this:

https://github.com/RobotLocomotion/drake/blob/fe914e62f0193d5a92846925fe8abf8e6b53fa4b/drake/multibody/joints/quaternion_floating_joint.cc#L13

---

*[drake/systems/rendering/pose_vector.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlW2U-KpKGij4olYTl:-KdlW2U-KpKGij4olYTm:b-knhkr7) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/pose_vector.h#L14)):*
> ```objc
> /// in the form {R_WA, p_WA}, where R is represented as a quaternion, and p as
> /// an x-y-z translation.
> template <typename T>
> ```

BTW, should we document which `T` values are explicitly instantiated?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlWMnTij7CHSaIaU8m:-KdlWMnUItOc7MiyjdWU:bv4yin6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L24)):*
> ```cpp
> namespace {
> 
> /// Tests that the PoseVector is initialized to the identity.
> ```

BTW, consider replacing "to the" with "to be".

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXQQY4aLS-kD9f0EX:-KdlXQQY4aLS-kD9f0EY:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L26)):*
> ```cpp
> /// Tests that the PoseVector is initialized to the identity.
> GTEST_TEST(PoseVector, InitiallyIdentity) {
>   PoseVector<double> vec;
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlX0GZ7j6ov6G65e2S:-KdlX0GZ7j6ov6G65e2T:b-d2hli) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L31)):*
> ```cpp
> 
>   // Check that the underlying storage has the values we'd expect.
>   for (int i = 0; i < 3; i++) {
> ```

BTW, consider `++i`.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXMmAKA269D158qEw:-KdlXMmAKA269D158qEx:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L54)):*
> ```cpp
>   }
>   // Check that the isometry transforms the x-axis to the y-axis.
>   Isometry3<double> X_WA = vec.get_isometry();
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXVUT5LlgUlVUa2VL:-KdlXVUT5LlgUlVUa2VM:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L55)):*
> ```cpp
>   // Check that the isometry transforms the x-axis to the y-axis.
>   Isometry3<double> X_WA = vec.get_isometry();
>   Eigen::Vector3d p_in = {1.0, 0.0, 0.0};
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXWdxvT7nEmpWvBw9:-KdlXWdxvT7nEmpWvBwA:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L56)):*
> ```cpp
>   Isometry3<double> X_WA = vec.get_isometry();
>   Eigen::Vector3d p_in = {1.0, 0.0, 0.0};
>   Eigen::Vector3d p_out = X_WA * p_in;
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXL2mcOj6bIqFLLHf:-KdlXL2mcOj6bIqFLLHg:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L68)):*
> ```cpp
>   }
>   // Check that the isometry is a pure translation.
>   Isometry3<double> X_WA = vec.get_isometry();
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXZ418VOrQRcXTU5E:-KdlXZ418VOrQRcXTU5F:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L69)):*
> ```cpp
>   // Check that the isometry is a pure translation.
>   Isometry3<double> X_WA = vec.get_isometry();
>   Eigen::Vector3d p_in = {1.0, 2.0, 3.0};
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXZRDxCVTDP1kO7jv:-KdlXZRDxCVTDP1kO7jw:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L70)):*
> ```cpp
>   Isometry3<double> X_WA = vec.get_isometry();
>   Eigen::Vector3d p_in = {1.0, 2.0, 3.0};
>   Eigen::Vector3d p_out = X_WA * p_in;
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlX_dMbtj9qGLjrpkk:-KdlX_dNAUgtMUMcPsA_:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L76)):*
> ```cpp
> // Tests that PoseVector<T>::Clone has PoseVector type.
> GTEST_TEST(PoseVector, Clone) {
>   PoseVector<double> vec;
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXbc1FVe0PcSIkMyR:-KdlXbc1FVe0PcSIkMyS:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L92)):*
> ```cpp
> 
>   // Spot-check some terms from the output.
>   Isometry3<symbolic::Expression> X_WA = vec.get_isometry();
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXf3SAz1WGOLEmmS_:-KdlXf3SAz1WGOLEmmSa:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L93)):*
> ```cpp
>   // Spot-check some terms from the output.
>   Isometry3<symbolic::Expression> X_WA = vec.get_isometry();
>   auto matrix = X_WA.matrix();
> ```

BTW, `const`?

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXvNrIGFcccnzGf8j:-KdlXvNrIGFcccnzGf8k:bnyge28) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L111)):*
> ```cpp
>     vec[i].value() = 0.5;
> 
>     // Initialize the Jacobian to the identity matrix.
> ```

BTW, missing "be" after "to".

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlYU1YRhZuOlrnXY7z:-KdlYU1YRhZuOlrnXY8-:b-5tt6x6) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L119)):*
> ```cpp
> 
>   // Spot-check some terms from the output.
>   Isometry3<AutoDiffXd> X_WA = vec.get_isometry();
> ```

BTW, `const`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-:-KdlYx-NGGbHqfrms8cO:bl4rucz)*

**Comment by david-german-tri** [comment]
Review status: 6 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlSMyM6Ym8Y5QBxz4L:-Kdl_VGWjuFae5FqUkMU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/automotive/simple_car.cc#L84)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, can this be `const`?
</blockquote></details>

Done.

---

*[drake/automotive/simple_car.cc, line 220 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlSlymWc5hoHTQ2Mb1:-Kdl_sk4oSsFHVZ67I7j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/automotive/simple_car.cc#L220)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is this actually an error condition? If so, should it abort instead?
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_vector.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlVHVSSqIw3t7PD46f:-Kdla7tD-_1QYsuEAuLZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/pose_vector.h#L13)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider documenting the ordering of the values in this `BasicVector`. I assume it's x, y, z, qw, qx, qy, qz? Maybe we can even copy/paste this:

https://github.com/RobotLocomotion/drake/blob/fe914e62f0193d5a92846925fe8abf8e6b53fa4b/drake/multibody/joints/quaternion_floating_joint.cc#L13
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_vector.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlW2U-KpKGij4olYTl:-KdlaIaT9dfQwXmttH48:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/pose_vector.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should we document which `T` values are explicitly instantiated?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 24 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlWMnTij7CHSaIaU8m:-KdlaMHW-KRZZi1NLPt-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "to the" with "to be".
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXQQY4aLS-kD9f0EX:-KdlaQRmJgOorXm5Do4e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlX0GZ7j6ov6G65e2S:-KdlaQyJWzZL25L4bAvv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L31)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider `++i`.
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXMmAKA269D158qEw:-KdlaTZ3uVRamne2u8Si:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L54)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXVUT5LlgUlVUa2VL:-KdlaTugkLU_mXVeQMDr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L55)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXWdxvT7nEmpWvBw9:-KdlaUBAYwWV7_zeoAzS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L56)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 68 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXL2mcOj6bIqFLLHf:-KdlaWegMxyIZHG_fCFJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L68)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 69 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXZ418VOrQRcXTU5E:-KdlaWvg_TRgoN3EtDnx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L69)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXZRDxCVTDP1kO7jv:-KdlaX9QuwHiQsi9Jv9q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L70)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlX_dMbtj9qGLjrpkk:-Kdlaglkt4i0gfjPkCsR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L76)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXbc1FVe0PcSIkMyR:-KdlaZvLF9F93TrRNd1J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 93 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXf3SAz1WGOLEmmS_:-KdlaaEBb4WfcTZUM2bU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L93)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlYU1YRhZuOlrnXY7z:-KdlaeyXqmkRHRj2_GFK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L119)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, `const`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.h, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlbsOMSV0tlLnrSs1U:-KdlbsOMSV0tlLnrSs1V:bfbh8t8) ([raw file](https://github.com/robotlocomotion/drake/blob/1f73fb7a5e7241c38543f9c046f2f9e9a7817731/drake/systems/rendering/pose_vector.h#L14)):*
> ```objc
> /// in the form {p_WA, R_WA}, where p is represented as an x-y-z translation,
> /// and R is represented as a quaternion. The exact order of elements is
> /// {x, y, z, qw, qx, qy, qz}.
> ```

BTW, consider surrounding mathematical symbols with backticks:

  * `{p_WA, R_WA}`
  * `p`
  * `R`
  * `{x, y, z, qw, qx, qy, qz}`

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXbc1FVe0PcSIkMyR:-KdlcFcBoipWuiRGV3RT:b3qgb7o) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L92)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, no change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-:-KdlcO1E5LOYZSx87Xaa:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/rendering/pose_vector.h, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlbsOMSV0tlLnrSs1U:-KdlcwaOg4AKoQA9_0pV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f73fb7a5e7241c38543f9c046f2f9e9a7817731/drake/systems/rendering/pose_vector.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider surrounding mathematical symbols with backticks:

  * `{p_WA, R_WA}`
  * `p`
  * `R`
  * `{x, y, z, qw, qx, qy, qz}`
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_vector_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-KdlXbc1FVe0PcSIkMyR:-Kdlclgcq_jPsvY4egD2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/34baaecb4b049cccb2e8cca27ae53ac9757d32d6/drake/systems/rendering/test/pose_vector_test.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, no change?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308)*

**Comment by david-german-tri** [comment]
+@ggould-tri for platform review

---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-:-KdldCIjaxhhPXjJNvx6:b-gbk9vg)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308)*

**Comment by jwnimmer-tri** [comment]
:lgtm: automotive design review

---

Reviewed 1 of 8 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, 2 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-:-KdldroOsJfpUuQc6Te1:b8xgnlq)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 3 of 4 files at r2, 1 of 2 files at r3, 3 of 5 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5308#-:-KdlizfJNC7sglrtfaWu:bnfp4nl)*

**Pull request merged**
