### PR TITLE
Cleans up names of methods in URDF parser that load model instances from files.

### LINKED ISSUE #3545: Excessive Function Overloading in URDF Parser
From the [style guide](https://google.github.io/styleguide/cppguide.html#Function_Overloading):

> Use overloaded functions (including constructors) only if a reader looking at a call site can get a good idea of what is happening without having to first figure out exactly which overload is being called.

Two methods in the URDF parser that violate this are:

1. [AddModelInstanceFromUrdfString()](https://github.com/RobotLocomotion/drake/blob/ad24abbd7213876169e978fbb383d0561f99e199/drake/systems/plants/parser_urdf.h#L68)
2. [AddModelInstanceFromUrdfFile()](https://github.com/RobotLocomotion/drake/blob/ad24abbd7213876169e978fbb383d0561f99e199/drake/systems/plants/parser_urdf.h#L187)

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #3545. Builds upon #3576.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3824)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review since you reviewed #3576.
+@sherm1 for platform review per rotation.

Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUIrd2LRAvHrAU7Vs8a:b-er6vq2)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/5815/ and is thus ready for review.

**Comment by sherm1** [comment]
One comment, PTAL.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/parser_urdf.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUJRIxjogwvjCqpPiGn:-KUJRIxk87htAQP6pbJ2:b-hxdgz) ([raw file](https://github.com/robotlocomotion/drake/blob/64dd25b6f7d00f508baaa1a0b8ed13c849cbb430/drake/systems/plants/parser_urdf.h#L207)):*
> ```objc
>  * to @p tree. The model instance is connected to the world via a
>  * `kRollPitchYaw` joint. When this joint is at its zero position, the model
>  * instance's frame is coincident with the world's coordinate frame.
> ```

I don't understand this statement. Which body in the URDF model gets connected to world by this joint? I don't understand the phrase "model instance's frame". Does that mean the frame of a particular designated link? Please clarify precisely what happens when the new joint is added. I gather the joint's "fixed" (inboard) frame will be coincident with the world frame, but I don't understand where the joint's "moving" (outboard) frame gets connected.

This also applies to the other variants of this method below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUJSs_x_AKMX9lyGBsj:bwhegej)*

**Comment by liangfok** [comment]
@sherm1 I addressed your comment. PTAL.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUJRIxjogwvjCqpPiGn:-KUYZ51bJW22StwpWJOF:b-pyokbd) ([raw file](https://github.com/robotlocomotion/drake/blob/64dd25b6f7d00f508baaa1a0b8ed13c849cbb430/drake/systems/plants/parser_urdf.h#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't understand this statement. Which body in the URDF model gets connected to world by this joint? I don't understand the phrase "model instance's frame". Does that mean the frame of a particular designated link? Please clarify precisely what happens when the new joint is added. I gather the joint's "fixed" (inboard) frame will be coincident with the world frame, but I don't understand where the joint's "moving" (outboard) frame gets connected.
> 
> This also applies to the other variants of this method below.
</details>
I refined the text to be more clear regarding which body in the URDF is attached to the tree. PTAL. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUYZDJESy_M6AZLV05P:b-ax62tk)*

**Comment by sherm1** [comment]
A couple of comments - PTAL.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUYqoYtmT6tKswK3UEW:-KUYqoYtmT6tKswK3UEX:bip7cr) ([raw file](https://github.com/robotlocomotion/drake/blob/02012df813428ddac9a6f705319a9c3d87678333/drake/systems/plants/parser_urdf.h#L53)):*
> ```objc
>  * Reads a URDF model specified by @p urdf_string and adds an instance of it to
>  * @p tree. In a URDF model, the set of bodies and joints form a tree where
>  * there is exactly one body that does not have a parent joint. Let this body
> ```

@liangfok, from our earlier conversation with Nate Koenig I recall that there is no guarantee that the URDF file will have the structure you specified here. For example, there could be two links without parent joints. Seems reasonable if this method is *assuming* this structure but then the comment should say so and say what happens if it doesn't like what it sees in the file.

---

*[drake/systems/plants/parser_urdf.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUYrZFHz7a3oUOx_Apr:-KUYrZFIAApg_6Nwv4PU:bhcow7u) ([raw file](https://github.com/robotlocomotion/drake/blob/02012df813428ddac9a6f705319a9c3d87678333/drake/systems/plants/parser_urdf.h#L56)):*
> ```objc
>  * be called the "root body". The root body is connected to the world via a
>  * systems::plants::joints::kRollPitchYaw joint. When this joint is at its zero
>  * position, the root body's frame is coincident with the world's coordinate
> ```

BTW, we typically use the term "base body" for bodies whose parent joint connects them to world. That allows for the possibility of multiple trees. In this case you seem to be restricting the method to operator on a single tree, in which case "root body" makes sense. Consider using "base body" here anyway for compatibility with more general circumstances.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUYsGjTCaPKKbOgsmh3:bnlno25)*

**Comment by david-german-tri** [comment]
:lgtm: but @sherm1's comments

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUZ7ZIDCFdO6atC_RDy:bz1pn1s)*

**Comment by liangfok** [comment]
@sherm1, I addressed your comments, PTAL. Thanks!

---

Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUYqoYtmT6tKswK3UEW:-KUZQ_M41SbsjTu_g-uA:brv720c) ([raw file](https://github.com/robotlocomotion/drake/blob/02012df813428ddac9a6f705319a9c3d87678333/drake/systems/plants/parser_urdf.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> @liangfok, from our earlier conversation with Nate Koenig I recall that there is no guarantee that the URDF file will have the structure you specified here. For example, there could be two links without parent joints. Seems reasonable if this method is *assuming* this structure but then the comment should say so and say what happens if it doesn't like what it sees in the file.
</details>
Done. Thanks for reminding me of this fact. I checked the code and​ it supports URDFs with multiple base bodies. I've updated the documentation​ as needed.

---

*[drake/systems/plants/parser_urdf.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUYrZFHz7a3oUOx_Apr:-KUZQoh82VIcT6AHwwnp:b-3y0dk2) ([raw file](https://github.com/robotlocomotion/drake/blob/02012df813428ddac9a6f705319a9c3d87678333/drake/systems/plants/parser_urdf.h#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, we typically use the term "base body" for bodies whose parent joint connects them to world. That allows for the possibility of multiple trees. In this case you seem to be restricting the method to operator on a single tree, in which case "root body" makes sense. Consider using "base body" here anyway for compatibility with more general circumstances.
</details>
Done. I adopted the term "base body" in r3 of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUZQuhsb-FLYXdTongz:bo0yct7)*

**Comment by sherm1** [comment]
Add a few BTWs - PTAL. OK to merge after addressing or declining. :lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZZaNk2ht3thE3oBQW:-KUZZaNk2ht3thE3oBQX:b-f0vqp9) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L53)):*
> ```objc
>  * Reads a URDF model specified by @p urdf_string and adds an instance of it to
>  * @p tree. Let the "base bodies" be the bodies in the model that do not have
>  * parent joints. The base bodies bodies are connected to the world via
> ```

BTW "bodies bodies" -> "bodies"

---

*[drake/systems/plants/parser_urdf.h, line 125 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZZxqNO6aoRK869E6w:-KUZZxqNO6aoRK869E6x:b-8twtgm) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L125)):*
> ```objc
>  * body in @p tree via joints of type @p floating_base_type. The body in the
>  * tree to which to which these joints attach and the transform between this
>  * body and the base bodies's frames when the joints are in their zero positions
> ```

BTW, possessive of `bodies` is `bodies'`.

---

*[drake/systems/plants/parser_urdf.h, line 206 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZ_Lj34_JNgXeY5fzU:-KUZ_Lj34_JNgXeY5fzV:b-1ammsb) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L206)):*
> ```objc
>  * parent joints. This method connects the model instance's base bodies to the
>  * world via systems::plants::joints::kRollPitchYaw joints. When
>  * this joint is at its zero position, the base bodies's frames are coincident
> ```

BTW, `bodies'`

---

*[drake/systems/plants/parser_urdf.h, line 233 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZ_VbE5NEIdXaNVHnH:-KUZ_VbE5NEIdXaNVHnI:b-1ammsb) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L233)):*
> ```objc
>  * parent joints. This method connects the model instance's base bodies to the
>  * world via joints of type @p floating_base_type. When these joints are at
>  * their zero positions, the base bodies's frames are coincident with the
> ```

BTW, `bodies'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUZ_jqfw8Tq3o_jXARv:b-k5bksi)*

**Comment by liangfok** [comment]
Thanks. Now waiting on CI to complete.

---

Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.h, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZZaNk2ht3thE3oBQW:-KUZlB4eeXfQjeozmOBU:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L53)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW "bodies bodies" -> "bodies"
</details>
Done. Thanks.

---

*[drake/systems/plants/parser_urdf.h, line 125 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZZxqNO6aoRK869E6w:-KUZlK7FQXP-e9aANvKK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L125)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, possessive of `bodies` is `bodies'`.
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 206 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZ_Lj34_JNgXeY5fzU:-KUZlMLrPWKRMkWB5_Dy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L206)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `bodies'`
</details>
Done.

---

*[drake/systems/plants/parser_urdf.h, line 233 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-KUZ_VbE5NEIdXaNVHnH:-KUZlN8nLaJQ5m0TSbpG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/46dbce59b76cd0d0536998dd67f17c10f046ae26/drake/systems/plants/parser_urdf.h#L233)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, `bodies'`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3824#-:-KUZlf17IURcWsVQHR9X:b3pc2w6)*

**Pull request merged**
