### PR TITLE
Updated inertias for link 2 and link 4 for the kuka iiwa

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830)

### CODE REVIEW

**Review by AdityaBhat-TRI — COMMENTED** [review]
+@EricCousineau-TRI  For review (merge pending tests on the hardware)
+(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-:-N_tYaWNBRCqyC2qN55x:b-ag3fir)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @AdityaBhat-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: nice!

Before:
> 

After:
> 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-:-N_vJVOGErCFSXhjpiNI:b-lvt3ci)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @AdityaBhat-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-N_vIlCM63NRjaUJ4SjH:-N_vIlCN2PPInrF1vR1p:b-6ip9bq) (no related file):*
nit Models may be / become inconsistent.

Any chance you'd be able to update `iiwa14_variants_parsing_test.cc` to (hopefully) confirm similar inertias?

The best would be to get bodies outboard of the tested actuators, the test the spatial inertias.
Alternatively, simpler approach would be to compare the inertia matrix, at least for the 7-DoF variants.

___

**Comment by AdityaBhat-TRI** [comment]
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Models may be / become inconsistent.

Any chance you'd be able to update `iiwa14_variants_parsing_test.cc` to (hopefully) confirm similar inertias?

The best would be to get bodies outboard of the tested actuators, the test the spatial inertias.
Alternatively, simpler approach would be to compare the inertia matrix, at least for the 7-DoF variants.
</blockquote></details>

Done

**Comment by AdityaBhat-TRI** [comment]
-(status: do not merge)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-:-Na7gBG648DdtYJDHnvx:b-syrraa)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc` line 196 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-Na7fRth9RqCFIYvCnuc:-Na7fRtiBKPORnINOb2T:b5qroak) ([raw file](https://github.com/RobotLocomotion/drake/blob/46f92849c342d84ff1cda886797c2b339988a9eb/manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc#L196)):*
> ```cpp
>     parser.AddModels(FindResourceOrThrow(model_file));
>     plant.Finalize();
>     if (model_file.substr(model_file.find_last_of('/') + 1) ==
> ```

nit This if/else is a bit hard to fully follow.

Instead of trying to jam it in here, could you move it to a separate test point?
If you need to share setup, consider using a test fixture, like:

https://github.com/RobotLocomotion/drake/blob/3fdd74cae58f672fe16b1f305e5a606f7f85c2e3/common/symbolic/expression/test/environment_test.cc#L18-L41
___
*[`manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc` line 210 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-Na7fyLwCScVAn1ONu6s:-Na7fyLwCScVAn1ONu6t:b-vqfcvz) ([raw file](https://github.com/RobotLocomotion/drake/blob/46f92849c342d84ff1cda886797c2b339988a9eb/manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc#L210)):*
> ```cpp
>     } else {
>       for (size_t i = 0; i < link_names.size(); ++i) {
>         const multibody::Body<double>& canonical_body =
> ```

nit When there is a mismatch in inertia, it may be difficult to see which link it is exactly.

Consider denoting this using `SCOPED_TRACE`, e.g. at the start of the loop
```
SCOPED_TRACE(fmt::format("link: {}", link_names[i]));
```

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc` line 196 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-Na7fRth9RqCFIYvCnuc:-Na8BWFEAC3F2oK4sbFP:b-yxfyfc) ([raw file](https://github.com/RobotLocomotion/drake/blob/46f92849c342d84ff1cda886797c2b339988a9eb/manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc#L196)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This if/else is a bit hard to fully follow.

Instead of trying to jam it in here, could you move it to a separate test point?
If you need to share setup, consider using a test fixture, like:

https://github.com/RobotLocomotion/drake/blob/3fdd74cae58f672fe16b1f305e5a606f7f85c2e3/common/symbolic/expression/test/environment_test.cc#L18-L41

</blockquote></details>

Chose to maintain symmetry with other test cases instead.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830)* status: missing label for release notes (waiting on @AdityaBhat-TRI)

___
*[`manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc` line 196 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19830#-Na7fRth9RqCFIYvCnuc:-Na8DTXE0FMvbOkPqfwA:b-m37bit) ([raw file](https://github.com/RobotLocomotion/drake/blob/46f92849c342d84ff1cda886797c2b339988a9eb/manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc#L196)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

Chose to maintain symmetry with other test cases instead.
</blockquote></details>

OK Yup, sounds good! (Sorry, didn't realize this was existing pattern)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830)* status: missing label for release notes (waiting on @AdityaBhat-TRI)

**Comment by AdityaBhat-TRI** [comment]
+(release notes: fix)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19830)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
