### PR TITLE
Add Boolean variable to symbolic formula

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6126)

### CODE REVIEW

**Comment by soonho-tri** [comment]
It's the first PR to have Boolean variables in symbolic formula class. I'll open more PRs later to update `symbolic::Environment` and `{Expression,Formula}::Substitute}` method.

+@ericcousineau-tri , feature-review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-:-KkNPgypUHx-PJBDW5Pr:b-c8ia0j)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_formula.cc, line 309 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTD-PhwK-DGZl27QTl:-KkTD-PhwK-DGZl27QTm:b-8hk6p7) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula.cc#L309)):*
> ```cpp
> bool is_false(const Formula& f) { return is_false(*f.ptr_); }
> bool is_true(const Formula& f) { return is_true(*f.ptr_); }
> bool is_variable(const Formula& f) { return is_variable(*f.ptr_); }
> ```

While it is implicit that a `Formula` must be a boolean, should the name be `is_boolean_variable(...)` / `is_bool_variable(...)`, to make the intent more clear?

Will there be any advantage to have this named the same as `is_variable(Variable / Expression / ExpressionCell)`?

---

*[drake/common/symbolic_formula.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTC0RKxYOmZsPR-yyD:-KkTC0RKxYOmZsPR-yyE:bdluuww) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula.h#L103)):*
> ```objc
> 
>   /** Constructs a formula from a Boolean variable @p var.
>    * @pre @p var is not a dummy variable whose ID is 0.
> ```

*NOTE*: Made another comment about this below.

It seems that a valid variable being non-dummy is a universal pre-condition. Is there a way to minimize this repeated precondition, and either (a) eliminate it, or (b) inline it with other things, such as saying:

* `Constructs a formula from a valid Boolean variable variable @p var.`
* `@pre @p var is valid and of BOOLEAN type.`

and then defining what "valid" is in `Variable`?

I think this would make more sense for other people and would make it a little more natural to understand.

---

*[drake/common/symbolic_formula_cell.cc, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTFyrpsAFL1PrpGbXi:-KkTFyrpsAFL1PrpGbXj:b29itxp) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula_cell.cc#L175)):*
> ```cpp
>   // Dummy symbolic variable (ID = 0) should not be used in constructing
>   // symbolic formulas.
>   DRAKE_DEMAND(!var_.is_dummy());
> ```

Hmm... Coming across `!is_dummy()` again - might there be a way to rename this to something a little more clear, such as `is_valid()`?
(That could be moved to another PR, if need be.)

---

*[drake/common/test/symbolic_formula_test.cc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTGX7uWKxpSPTuKKdg:-KkTGX7vBBysrePDHExQ:b-5dx7zy) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/test/symbolic_formula_test.cc#L49)):*
> ```cpp
> 
> // Checks if a given 'formulas' is ordered by Formula::Less.
> void CheckOrdering(const vector<Formula>& formulas) {
> ```

BTW Was cross-referencing, and I noticed that `CheckOrdering` is still `static` in `symbolic_expression_test.cc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by soonho-tri** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/symbolic_formula.cc, line 309 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTD-PhwK-DGZl27QTl:-KkX19H_3CpZz16MzF0C:b-yfecpr) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula.cc#L309)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

While it is implicit that a `Formula` must be a boolean, should the name be `is_boolean_variable(...)` / `is_bool_variable(...)`, to make the intent more clear?

Will there be any advantage to have this named the same as `is_variable(Variable / Expression / ExpressionCell)`?
</blockquote></details>

I think it's fine. I'd like to keeping the same name, `is_variable`, for expression and formula to make it easy to remember.

---

*[drake/common/symbolic_formula.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTC0RKxYOmZsPR-yyD:-KkX6fnwITygjs8w4SrR:b2wh97e) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula.h#L103)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

*NOTE*: Made another comment about this below.

It seems that a valid variable being non-dummy is a universal pre-condition. Is there a way to minimize this repeated precondition, and either (a) eliminate it, or (b) inline it with other things, such as saying:

* `Constructs a formula from a valid Boolean variable variable @p var.`
* `@pre @p var is valid and of BOOLEAN type.`

and then defining what "valid" is in `Variable`?

I think this would make more sense for other people and would make it a little more natural to understand.
</blockquote></details>

I've reduced it to one `@pre`.

I think calling a "default-constructed variable whose `ID = 0`" *invalid* is too strong. I've spent some time trying to come up with a better name, but couldn't find one better than `dummy` to me.

---

*[drake/common/test/symbolic_formula_test.cc, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTGX7uWKxpSPTuKKdg:-KkX2ME2zEh2m6eAQHe_:b-rxqi07) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/test/symbolic_formula_test.cc#L49)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Was cross-referencing, and I noticed that `CheckOrdering` is still `static` in `symbolic_expression_test.cc`.
</blockquote></details>

Done.

(removed `static` in `CheckOrdering(const vector<Expression>& expressions)`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: - thanks!

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-:-KklZ2lZCYt74X7Jl3aa:b-hidk3u)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri, platform-review, please. Thank you!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-:-KklZOlW2-jfKFNJpDfG:bskz5kp)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/symbolic_formula_cell.cc, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkTFyrpsAFL1PrpGbXi:-KklmcKSjiU5YNp4wSH4:b-c1l28i) ([raw file](https://github.com/robotlocomotion/drake/blob/346bfd852618ed1135a48c84d630c52483a058f0/drake/common/symbolic_formula_cell.cc#L175)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Hmm... Coming across `!is_dummy()` again - might there be a way to rename this to something a little more clear, such as `is_valid()`?
(That could be moved to another PR, if need be.)
</blockquote></details>

Definitely separate PR, if anything.  The name "dummy" is widely used and would be a non-functional rename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklrjOnh7og2KVj0Iqk:-KklrjOnh7og2KVj0Iql:b-jd1zz6) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula.h#L83)):*
> ```objc
>     F1 ∨ F2        ->  True    (if either F1 or F2 is True)
> \endverbatim
> ```

Defect not new in this PR: The "nary" representational consolidations (that `((a && b) && c)` and `(a && (b && c))` are `equal_to` each other) are not documented here, but I think are important to users, so should be promised here or somewhere?

---

*[drake/common/symbolic_formula.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklrpFaStzCZNE0x1NH:-KklrpFaStzCZNE0x1NI:b-u9246g) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula.h#L83)):*
> ```objc
>     F1 ∨ F2        ->  True    (if either F1 or F2 is True)
> \endverbatim
> ```

It looks like `operator&&` and such don't simplify duplicate variables?  `x && x` is an NAry, not just a single `x` cell.  Should that be noted somewhere -- either a TODO if we want it, or a comment why we _don't_ want it, or ...?

---

*[drake/common/symbolic_formula_cell.cc, line 203 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklpO0pKZQPhrUrmYI7:-KklpO0pKZQPhrUrmYI8:bswnv7s) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula_cell.cc#L203)):*
> ```cpp
>     oss << "The following environment does not have an entry for the "
>            "variable "
>         << var_ << endl;
> ```

BTW nit `endl` means "flush", which you don't need here; you want just "\n".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by soonho-tri** [comment]
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklrjOnh7og2KVj0Iqk:-KkpaY00OB5fk8yqToEi:bcdnyo9) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula.h#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Defect not new in this PR: The "nary" representational consolidations (that `((a && b) && c)` and `(a && (b && c))` are `equal_to` each other) are not documented here, but I think are important to users, so should be promised here or somewhere?
</blockquote></details>

Done. (Added a paragraph)

---

*[drake/common/symbolic_formula.h, line 83 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklrpFaStzCZNE0x1NH:-KkpZ3H_qIi8eJUC-pDb:b-oka13u) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula.h#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It looks like `operator&&` and such don't simplify duplicate variables?  `x && x` is an NAry, not just a single `x` cell.  Should that be noted somewhere -- either a TODO if we want it, or a comment why we _don't_ want it, or ...?
</blockquote></details>

Done. Thanks for the catching this.

It was the case that we did *not* simplify `f1 && f2 => f1` where `f1` and `f2` are structurally equal. I've added the simplification to `operator&&` and `operator||` in `symbolic_formula.cc` file (+ tests).

---

*[drake/common/symbolic_formula_cell.cc, line 203 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklpO0pKZQPhrUrmYI7:-KkpdHX67E-6dCWrKxPp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula_cell.cc#L203)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit `endl` means "flush", which you don't need here; you want just "\n".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 4 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 89 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkpfOclCuYgFnZl3UbI:-KkpfOcmKAUgeKyoopQ9:b-ntmho2) ([raw file](https://github.com/robotlocomotion/drake/blob/f0dad1a469cfa5dd809a679619c31efe238cb864/drake/common/symbolic_formula.h#L89)):*
> ```objc
> (f2 && f1)` and `(f1 && f2) && f1` are flattened to `f1 && f2 && f1` and
> simplified into `f1 && f2`. As a result, the two are identified as the same
> formula.
> ```

Could you add a specific test case with three conjuncts, grouped with parens like above, having two are the same?  I am not immediately seeing in the implementation where the conjuncts _within_ an NAry are compared for structural equality and pruned.

---

*[drake/common/symbolic_formula_cell.cc, line 203 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklpO0pKZQPhrUrmYI7:-KkpesezXSzlBqDO9Pp2:b-eehb0s) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula_cell.cc#L203)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Heh, now its inconsistent.  There is still an "endl" immediately below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by soonho-tri** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 89 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KkpfOclCuYgFnZl3UbI:-KkpjT4JVhoyml0aSQ5J:b-ix4jer) ([raw file](https://github.com/robotlocomotion/drake/blob/f0dad1a469cfa5dd809a679619c31efe238cb864/drake/common/symbolic_formula.h#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Could you add a specific test case with three conjuncts, grouped with parens like above, having two are the same?  I am not immediately seeing in the implementation where the conjuncts _within_ an NAry are compared for structural equality and pruned.
</blockquote></details>

Added tests showing that the example holds (one for `&&` and another for `||`) -- `And5` and `Or5`.

---

*[drake/common/symbolic_formula_cell.cc, line 203 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-KklpO0pKZQPhrUrmYI7:-KkpkcRZlsAh6cdoEKQt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc15198617e91be73c4eb5b1380c95f6eeb4ecbf/drake/common/symbolic_formula_cell.cc#L203)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Heh, now its inconsistent.  There is still an "endl" immediately below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6126#-:-KkplB4iFZC0cwjCUzUO:bnfp4nl)*

**Pull request merged**
