### PR TITLE
support parameters in system symbolic inspector

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7090)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review, please 
(thrilled that @soonho-tri is on deck for platform)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-:-KuqXdWzZO6PWlIAqYMB:b9imjz8)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion item and some minor BTWs. Thanks!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_symbolic_inspector.cc, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutgGPSaNIv1_WPdib8:-KutgGPTJjFUXkBXJRoc:bfwi8x5) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/system_symbolic_inspector.cc#L159)):*
> ```cpp
>   }
> 
>   // TODO(david-german-tri): Check parameters once #5072 is resolved.
> ```

Since #5072 is resolved and this PR is handling parameters, should `context.num_abstract_parameters()` be incorporated into this check?

---

*[drake/systems/framework/system_symbolic_inspector.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-Kutnmc6MV9d_GBxhAEy:-Kutnmc6MV9d_GBxhAEz:b-np2uvr) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/system_symbolic_inspector.h#L21)):*
> ```objc
> ///
> /// A SystemSymbolicInspector is only interesting if the Context contains purely
> /// vector-valued elements. If any abstract-valued elements are present, the
> ```

BTW minor nit Inconsistency - one space after period, where two spaces are used elsewhere in this file.

---

*[drake/systems/framework/test/system_symbolic_inspector_test.cc, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutjJL_ZXU01vsICpe7:-KutjJLaDYtTHztGpZf4:btnb8um) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/test/system_symbolic_inspector_test.cc#L193)):*
> ```cpp
> 
> TEST_F(PendulumInspectorTest, HasAffineDynamics) {
>   EXPECT_FALSE(inspector_->HasAffineDynamics());
> ```

BTW Out of curiosity, along the lines of "HasAffineDynamics", can I ask if there will be a nonlinear state variant of this for `xdot = f(x)  + g(x)*u`? If so, what would the name be?

(I just have a small concern about potential ambiguity issues on how a somewhat fresh user would interpret the names.)

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutoEbWqrhOaUI-Zpe8:-KutoEbWqrhOaUI-Zpe9:bfnei7e) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/direct_transcription.cc#L189)):*
> ```cpp
>   }
> 
>   symbolic::Substitution sub;
> ```

Can I ask if the user is able to specify constraints / costs based on parameters via an accessor akin to `state(...)`? Or is that a TODO?

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutnDXTqgn8_j3AodRQ:-KutnDXTqgn8_j3AodRR:bbcani1) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L79)):*
> ```cpp
>     // Zero inputs, zero outputs.
>     this->DeclareDiscreteState(1);                     // One state variable.
>     this->DeclareNumericParameter(BasicVector<T>(1));  // One parameter.
> ```

BTW Could this be implemented using a non-trivial parameter, such as `2`?

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-Kutlqm9mGycXNm4pRKn:-Kutlqm9mGycXNm4pRKo:bfql54i) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L224)):*
> ```cpp
>   EXPECT_EQ(dynamic_constraints.size(), kNumSampleTimes - 1);
> 
>   for (int i = 0; i < (kNumSampleTimes - 1); i++) {
> ```

BTW Could you add a comment stating that this evaluates the dynamics constraints, checking that `x[N] == f(x[N-1], p)`?

(And could this incorporate a non-trivial coefficient as mentioned above, just to further clarify?)

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutlojLnJO64nguZRak:-KutlojLnJO64nguZRal:b-2ev4s9) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L227)):*
> ```cpp
>     EXPECT_EQ(prog.EvalBindingAtSolution(dynamic_constraints[i])[0],
>               prog.GetSolution(prog.state(i + 1)[0]) -
>                   -prog.GetSolution(prog.state(i)[0]));
> ```

BTW Odd indentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-:-KutnYykeBWMBd3qojgN:b-pqcfhv)*

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-:-KuuT2smSJRXnAoKcLcJ:b-v3eqt6)*

**Comment by RussTedrake** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/system_symbolic_inspector.cc, line 159 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutgGPSaNIv1_WPdib8:-KuuQHTi1lndFB2dsoav:b-kp8tjl) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/system_symbolic_inspector.cc#L159)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Since #5072 is resolved and this PR is handling parameters, should `context.num_abstract_parameters()` be incorporated into this check?
</blockquote></details>

Done.  nice catch.

---

*[drake/systems/framework/system_symbolic_inspector.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-Kutnmc6MV9d_GBxhAEy:-KuuR5bv6elg8wyaeRTG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/system_symbolic_inspector.h#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW minor nit Inconsistency - one space after period, where two spaces are used elsewhere in this file.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/system_symbolic_inspector_test.cc, line 193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutjJL_ZXU01vsICpe7:-KuuRCDfdTjn5EhgtOvl:bkggkww) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/framework/test/system_symbolic_inspector_test.cc#L193)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Out of curiosity, along the lines of "HasAffineDynamics", can I ask if there will be a nonlinear state variant of this for `xdot = f(x)  + g(x)*u`? If so, what would the name be?

(I just have a small concern about potential ambiguity issues on how a somewhat fresh user would interpret the names.)
</blockquote></details>

IsControlAffine().

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutoEbWqrhOaUI-Zpe8:-KuuRKgoYALdKFWmv5nK:b-jri4pj) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/direct_transcription.cc#L189)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can I ask if the user is able to specify constraints / costs based on parameters via an accessor akin to `state(...)`? Or is that a TODO?
</blockquote></details>

Adding more substitution sugar is definitely on my list (and is called out specifically with a TODO below).

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutnDXTqgn8_j3AodRQ:-KuuRZOWaIhil39Or-FE:bnbl65a) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L79)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could this be implemented using a non-trivial parameter, such as `2`?
</blockquote></details>

I used the -1.0 for the parameter value in the test.  1 is the number of parameters.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 224 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-Kutlqm9mGycXNm4pRKn:-KuuSe9BQ4dE2ZifM9tA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L224)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you add a comment stating that this evaluates the dynamics constraints, checking that `x[N] == f(x[N-1], p)`?

(And could this incorporate a non-trivial coefficient as mentioned above, just to further clarify?)
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 227 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutlojLnJO64nguZRak:-KuuSeSCcdHD5l8fO5rn:bwmjatq) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L227)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Odd indentation?
</blockquote></details>

it's what clang-format wants.  hopefully the kGain makes it more palatable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KuuZ8_AIoFgvmYR2FsT:-KuuZ8_AIoFgvmYR2FsU:b-wscbe4) ([raw file](https://github.com/robotlocomotion/drake/blob/dc57437c642a813a5d4bc348d4ff6d2a7ad71d49/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L212)):*
> ```cpp
>   const double kGain = -1.0;
>   context->get_mutable_numeric_parameter(0)->SetAtIndex(0, kGain);
>   int kNumSampleTimes = 3;
> ```

BTW, a nit, `const int`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-:-KuucEP3FnEmyR7HgtRz:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutoEbWqrhOaUI-Zpe8:-Kuua_QRyrMN0BDuTWyQ:b-kpnfh1) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/direct_transcription.cc#L189)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Adding more substitution sugar is definitely on my list (and is called out specifically with a TODO below).
</blockquote></details>

Gotcha!
I tried finding a TODO related to adding something like `MultipleShooting::p_vars_` to optimize on parameters, but could not find it - could I ask which one you're referring to? (I see the one below on implementation details - making substitution a little easier.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutoEbWqrhOaUI-Zpe8:-KuunZz2cbwlT3wf5oKK:b-t5wbst) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/direct_transcription.cc#L189)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Gotcha!
I tried finding a TODO related to adding something like `MultipleShooting::p_vars_` to optimize on parameters, but could not find it - could I ask which one you're referring to? (I see the one below on implementation details - making substitution a little easier.)
</blockquote></details>

the making substitution a little easier is the one I was referring to.  but i promise the broader substitution interfaces to symbolic inspector are coming.  (have some already in a dev branch)

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 212 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KuuZ8_AIoFgvmYR2FsT:-Kuunyeuki_y1QYEWSOi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dc57437c642a813a5d4bc348d4ff6d2a7ad71d49/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L212)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, a nit, `const int`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 189 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7090#-KutoEbWqrhOaUI-Zpe8:-Kuus9WfngjeYahDvNAj:brxp9sd) ([raw file](https://github.com/robotlocomotion/drake/blob/98ce82120b24a72e38030ec7f676af8d4364f08f/drake/systems/trajectory_optimization/direct_transcription.cc#L189)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

the making substitution a little easier is the one I was referring to.  but i promise the broader substitution interfaces to symbolic inspector are coming.  (have some already in a dev branch)
</blockquote></details>

Sounds good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7090)*

**Pull request merged**
