### PR TITLE
Use DRAKE_ASSERT instead of assert

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is the next step for #1935.

It also has the side-effect of adding a dependency on `libdrakeCommon` almost everywhere, which will make it easier to add and use common utilities there in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2620)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sherm1 for platform review, having been involved in #2602 review recently.

**Comment by sherm1** [comment]
Platform review done. Several nits but otherwise :lgtm_strong:. You are my hero for beating down these trolls.  (I'm giving myself partial-hero status for eyeballing all 48 files.)

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[drake/core/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYnT46ULGYTn_tOVa:-KKvYnT46ULGYTn_tOVb:-254848964) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/core/CMakeLists.txt#L14)):*
> ```CMake
> pods_install_libraries(drakeCore)
> pods_install_pkg_config_file(drake-core
>   LIBS -ldrakeCore -ldrakeCommon
> ```

BTW, Is adding this second library necessary? I think CMake embedded the dependency due to you `target_link_libraries` call above. If not necessary is it still advisable? There is a case I pointed out in another comment where there are more libraries but some ware not listed. 

---

*[drake/core/Gradient.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvVeHSoSoeUyMz33oQ:-KKvVeHSoSoeUyMz33oR:-345983358) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/core/Gradient.h#L6)):*
> ```objc
> #include <Eigen/Dense>
> #include <unsupported/Eigen/AutoDiff>
> #include "drake/common/drake_assert.h"
> ```

insert blank line to separate include groups

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvWd-vWU4ytrSJ4cVT:-KKvWd-vWU4ytrSJ4cVU:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/controllers/InstantaneousQPController.cpp#L5)):*
> ```cpp
> #include <map>
> #include <memory>
> #include "drake/Path.h"
> ```

insert blank line

---

*[drake/systems/plants/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvX69TQ_nFsQ1Pjno9:-KKvX69TQ_nFsQ1PjnoA:-1440499070) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/CMakeLists.txt#L9)):*
> ```CMake
> pods_install_libraries(drakeXMLUtil)
> pods_install_pkg_config_file(drake-xml-util
>   LIBS -ldrakeXMLUtil -ldrakeCommmon
> ```

`libdrakeXMLUtil` was already dependent on two libraries, but those didn't appear in the pkg_config LIBS line. Why does yours need to be listed here but the others do not?

---

*[drake/systems/plants/KinematicsCache.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXYBzkbdE28Pa4bvk:-KKvXYC-sRE7kN5ad6NZ:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/KinematicsCache.h#L11)):*
> ```objc
> #include <stdexcept>
> #include <utility>
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---

*[drake/systems/plants/RigidBodySystem.cpp, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXaz8SUaEgB6V21wu:-KKvXaz8SUaEgB6V21wv:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/RigidBodySystem.cpp#L5)):*
> ```cpp
> #include <list>
> #include <stdexcept>
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---

*[drake/systems/plants/rigidBodyTreeMexFunctions.cpp, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXgTjmEzH6euA5Lwx:-KKvXgTjmEzH6euA5Lwy:-2066088796) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/rigidBodyTreeMexFunctions.cpp#L4)):*
> ```cpp
> #include <Eigen/Sparse>
> #include "rigidBodyTreeMexFunctions.h"
> #include "drake/common/drake_assert.h"
> ```

insert blank line, er ... somewhere

---

*[drake/systems/plants/xmlUtil.cpp, line 211 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXuNBaWBEMf2bGwaX:-KKvXuNCpI2O0nMGXDA-:-1617375592) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/xmlUtil.cpp#L211)):*
> ```cpp
>     // This could cause problems with the default pose assumptions in
>     // the sdf parser, which I simply had to guess.
>     DRAKE_ASSERT(0 && "this has not been tested yet");
> ```

BTW, I would prefer "false" here rather than "0" as long as you're editing anyway ...

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvY3W3M86_kQZuIoTG:-KKvY3W3M86_kQZuIoTH:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L2)):*
> ```cpp
> #include "constructPtrRigidBodyConstraint.h"
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---

*[drake/systems/trajectories/ExponentialPlusPiecewisePolynomial.h, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYMGvwe9LgPUpLkKh:-KKvYMGvwe9LgPUpLkKi:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/trajectories/ExponentialPlusPiecewisePolynomial.h#L5)):*
> ```objc
> #include <Eigen/Core>
> #include <vector>
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---

*[drake/util/drakeGeometryUtil.h, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYYGLCNYsOEIfoK2G:-KKvYYGLCNYsOEIfoK2H:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/util/drakeGeometryUtil.h#L7)):*
> ```objc
> #include <cmath>
> #include <random>
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---

*[drake/util/drakeUtil.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYeRCsdj3LRb2CODd:-KKvYeRCsdj3LRb2CODe:2064027810) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/util/drakeUtil.h#L16)):*
> ```objc
> #include <Eigen/Dense>
> #include <unordered_map>
> #include "drake/common/drake_assert.h"
> ```

insert blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-:-KKvZHDseSbthLeIx-BN:-1226936241)*

**Comment by jwnimmer-tri** [comment]
*[drake/core/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYnT46ULGYTn_tOVa:-KKx7RYYTfsdIBD9uh1I:-639413066) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/core/CMakeLists.txt#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, Is adding this second library necessary? I think CMake embedded the dependency due to you `target_link_libraries` call above. If not necessary is it still advisable? There is a case I pointed out in another comment where there are more libraries but some ware not listed. 
</details>
I was attempting to follow the pattern that seemed prevalent throughout Drake -- library dependencies are listed twice, once in `target_link_libraries` and once in `pods_install_pkg_config_file`.  From my reading of what `pods_install_pkg_config_file` does, I don't think it interacts with `target_link_libraries` at all.  So likely, this code is correct, the other omission you found is a defect.

But before I go down that road, let's ask @billhoffman if he knows anyone at kitware who can confirm or deny my assessment in the prior paragraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620)*

**Comment by jwnimmer-tri** [comment]
Review status: 39 of 48 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/core/Gradient.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvVeHSoSoeUyMz33oQ:-KKxXlopdNxOTKjq2HhD:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/core/Gradient.h#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line to separate include groups
</details>
Done.

---

*[drake/systems/controllers/InstantaneousQPController.cpp, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvWd-vWU4ytrSJ4cVT:-KKxYsYqBbQ8DxhPk1ZQ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/controllers/InstantaneousQPController.cpp#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/systems/plants/KinematicsCache.h, line 11 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXYBzkbdE28Pa4bvk:-KKxXwOBjf0b5LcwYTgJ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/KinematicsCache.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXaz8SUaEgB6V21wu:-KKxY4Nuz-mPC84CigUK:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/RigidBodySystem.cpp#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/systems/plants/rigidBodyTreeMexFunctions.cpp, line 4 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvXgTjmEzH6euA5Lwx:-KKxYJbMbiGxlEB_6nig:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/rigidBodyTreeMexFunctions.cpp#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line, er ... somewhere
</details>
Done.

---

*[drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvY3W3M86_kQZuIoTG:-KKxYRT7a6eMz5Uhoz3A:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/constraint/constructPtrRigidBodyConstraintmex.cpp#L2)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/systems/trajectories/ExponentialPlusPiecewisePolynomial.h, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYMGvwe9LgPUpLkKh:-KKxYYVTHvkde4lurvK6:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/trajectories/ExponentialPlusPiecewisePolynomial.h#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/util/drakeGeometryUtil.h, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYYGLCNYsOEIfoK2G:-KKxYcAZ3h_wNIOxqRWf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/util/drakeGeometryUtil.h#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---

*[drake/util/drakeUtil.h, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYeRCsdj3LRb2CODd:-KKxYh2C9nG31pBq_vqB:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/util/drakeUtil.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> insert blank line
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620)*

**Comment by jwnimmer-tri** [comment]
Review status: 38 of 48 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/core/CMakeLists.txt, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvYnT46ULGYTn_tOVa:-KKxeYNOBu4HEpItIDCi:-1973129726) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/core/CMakeLists.txt#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I was attempting to follow the pattern that seemed prevalent throughout Drake -- library dependencies are listed twice, once in `target_link_libraries` and once in `pods_install_pkg_config_file`.  From my reading of what `pods_install_pkg_config_file` does, I don't think it interacts with `target_link_libraries` at all.  So likely, this code is correct, the other omission you found is a defect.
> 
> But before I go down that road, let's ask @billhoffman if he knows anyone at kitware who can confirm or deny my assessment in the prior paragraph.
</details>
Anyway, I've added the other library flags to the drake-xml-util.pc, so I'll posit that this PR is good enough now.

---

*[drake/systems/plants/CMakeLists.txt, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-KKvX69TQ_nFsQ1Pjno9:-KKxdyePT-S2eiB6RaH7:-496926666) ([raw file](https://github.com/robotlocomotion/drake/blob/7bf26976ef9c9c6c891207cf006e3bb0b60f3f5b/drake/systems/plants/CMakeLists.txt#L9)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `libdrakeXMLUtil` was already dependent on two libraries, but those didn't appear in the pkg_config LIBS line. Why does yours need to be listed here but the others do not?
</details>
Done.  (I have added the other libraries to the `*.pc` file now.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620)*

**Comment by amcastro-tri** [comment]
we should open the @jwnimmer-tri fan's club @sherm1. :lgtm_strong: 

---

Review status: 38 of 48 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-:-KKxh9r3aDnQUGR7zLBm:-289972721)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-:-KKxiz8xO2ajAZ4wV1pB:-1868698381)*

**Comment by sherm1** [comment]
OK, ready to go. Please see cpplint and a build failure; likely unrelated to this PR. Merge if so.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2620#-:-KKy2-EWCaMt4wPHlLTC:-1191533811)*

**Comment by jwnimmer-tri** [comment]
Both jenkins errors are true problems, will fix.

**Comment by jwnimmer-tri** [comment]
Using override-merge because jenkins isn't complete yet -- the mac builders are offline, but everything else passed.

**Pull request merged**
