### PR TITLE
doc: Remove the legacy sphinx website

### LINKED ISSUE #13832: Reworking Drake's website
We'd like to rework some of the content and style of https://drake.mit.edu/.  As part of this work, we'll probably need to tweak our workflow for hosting some static assets.  This is a tracking issue to explore that topic.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #13832.

Labeled "do not merge" for a few days, so we don't make it more difficult to rollback the website in case of emergency.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14758)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri 

:LGTM:

> Reviewed 84 of 84 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14758#-:-MVObiZ36vfS5JUjPQ5_:b-uh7ig9)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[doc/BUILD.bazel, line 27 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14758#-MVO_yVVCFPIH68Vagdq:-MVO_yVVCFPIH68Vagdr:b530ort) ([raw file](https://github.com/robotlocomotion/drake/blob/6523085e65408ca94ca091d58a8069141528273d/doc/BUILD.bazel#L27)):*
> ```Starlark
> _DEFAULT_TEST_TAGS = [
>     "manual",
>     # None our documentation tools should hit the internet, but their
> ```

nit: "None __*of*__ our..."

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per (laggy) schedule, please.  Today seemed pretty light, I don't want you to starve.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14758)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 83 of 84 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14758#-:-MVSeLRvDePSNP6Dk08k:bnfp4nl)* status: labeled "do not merge" (waiting on @jwnimmer-tri)

**Pull request merged**
