### PR TITLE
Add Python protobufs to the Bazel build

### PR DESCRIPTION
**Pull request by david-german-tri**
Migrate lcm_vector_gen (which now requires Bazel) from YAML to a new proto message called `NamedVector`.

Contributes to #4730.

@rpoyner-tri for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4912)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/lcm_vector_gen.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbQBjsCXqBZCX-Qd169:-KbQBjsCXqBZCX-Qd16A:b-c0aor3) ([raw file](https://github.com/robotlocomotion/drake/blob/3529b2edb2e29ed0f5532191c6d615b3e425670b/drake/tools/lcm_vector_gen.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

file meta: pep8 formatting. (I had this in a branch, but you win the race.)

---

*[drake/tools/lcm_vector_gen.py, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbQAjCxpcjj5iyemqT1:-KbQAjCyU6pX5d9zu5Xh:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/3529b2edb2e29ed0f5532191c6d615b3e425670b/drake/tools/lcm_vector_gen.py#L8)):*
> ```Python
> import argparse
> import os
> import subprocess
> ```

unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/tools/lcm_vector_gen.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbQBjsCXqBZCX-Qd169:-KbQJazMUHVG7u2T2CnB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3529b2edb2e29ed0f5532191c6d615b3e425670b/drake/tools/lcm_vector_gen.py#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

file meta: pep8 formatting. (I had this in a branch, but you win the race.)
</blockquote></details>

Done.

---

*[drake/tools/lcm_vector_gen.py, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbQAjCxpcjj5iyemqT1:-KbQI9900exx8zJCN0PI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3529b2edb2e29ed0f5532191c6d615b3e425670b/drake/tools/lcm_vector_gen.py#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-:-KbQL4zrRaa0P6IGZOFl:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-:-KbQOmR-q20lsj6kwBmk:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRP3ouKRG0AH5ufFLh:-KbRP3ov43fNxspu9qq5:bp0mzev) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/WORKSPACE#L145)):*
> ```
>     name = "six",
>     actual = "@six_archive//:six",
> )
> ```

BTW @rpoyner-tri Had discouraged me away from `bind` in the past, I think -- I don't recall why.  This this needed, versus just having the `new_http_archive` be `name = "six"` directly?

---

*[drake/automotive/driving_command_fields.named_vector, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRMGZbVcMDlm7OANK6:-KbRMGZbVcMDlm7OANK7:b-m1vlqb) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/automotive/driving_command_fields.named_vector#L3)):*
> ```
> element {
>      name: "steering_angle"
>      doc: "The desired steering angle of a virtual center wheel, positive results in the vehicle turning left."
> ```

BTW Is there a syntax for multi-line strings?   I could see us wanting to have long paragraphs for docs like this eventually.

---

*[drake/tools/lcm_vector_gen.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRNzURuKmlqW3kvSH9:-KbRNzURuKmlqW3kvSHA:b-gnjvkw) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/lcm_vector_gen.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

When files only work via Bazel (as I think this one does, now that it imports proto stuff), we remove the shebang line and remove the execute bits from the file in git.  Users should never invoke it by hand, only via `bazel run` or `bazel-bin` (neither of which use the shebang).

---

*[drake/tools/lcm_vector_gen.py, line 392 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRNttlPZWrk5RX29Pw:-KbRNttm7oE2_eRIfAKW:bikdscl) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/lcm_vector_gen.py#L392)):*
> ```Python
>         '--cxx-dir', help="output directory for cxx files", default=".")
>     parser.add_argument(
>         '--workspace', help="Drake WORKSPACE root.", default=".")
> ```

I'm not sure this default makes sense?

---

*[drake/tools/named_vector.proto, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRN2Fj5RAgUtOTmrxe:-KbRN2Fj5RAgUtOTmrxf:b-55azo8) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/named_vector.proto#L3)):*
> ```protobuf
> syntax = "proto3";
> 
> package tools;
> ```

Possibly `drake.tools`?  I think generally we namespace everything else that way.  (Or is that already implied somehow?)

---

*[tools/six.BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbROgfDA-ZNgoYWABt5:-KbROgfE9JNC9_eQW4up:b-6ugxh9) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/tools/six.BUILD#L6)):*
> ```
>   outs = ["six.py"],
>   cmd = "cp $< $(@)",
> )
> ```

BTW Do we need this genrule?  I would have suspected that `imports = ["six-1.10.0"]` on the `py_library` below would have done the job instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[WORKSPACE, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRP3ouKRG0AH5ufFLh:-KbRQyUhI8I-c2Izn_m2:b1iaq7f) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/WORKSPACE#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW @rpoyner-tri Had discouraged me away from `bind` in the past, I think -- I don't recall why.  This this needed, versus just having the `new_http_archive` be `name = "six"` directly?
</blockquote></details>

Dang, I don't remember what spooked me about `bind` now either.

---

*[drake/automotive/driving_command_fields.named_vector, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRMGZbVcMDlm7OANK6:-KbRRGPbrBvFGrXneCOm:bhdu1a9) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/automotive/driving_command_fields.named_vector#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there a syntax for multi-line strings?   I could see us wanting to have long paragraphs for docs like this eventually.
</blockquote></details>

https://github.com/google/protobuf/issues/1297

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[WORKSPACE, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRP3ouKRG0AH5ufFLh:-KbRYRVQ0A9eZwchn0Jd:bxj7cbm) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/WORKSPACE#L145)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Dang, I don't remember what spooked me about `bind` now either.
</blockquote></details>

This mimicks upstream; absent specific concerns I'm inclined to leave it as-is?

---

*[drake/tools/lcm_vector_gen.py, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRNzURuKmlqW3kvSH9:-KbRZ202wEg9n95Z6fcy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/lcm_vector_gen.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When files only work via Bazel (as I think this one does, now that it imports proto stuff), we remove the shebang line and remove the execute bits from the file in git.  Users should never invoke it by hand, only via `bazel run` or `bazel-bin` (neither of which use the shebang).
</blockquote></details>

Done.

---

*[drake/tools/lcm_vector_gen.py, line 392 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRNttlPZWrk5RX29Pw:-KbRZGvXPjKM09az79fW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/lcm_vector_gen.py#L392)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure this default makes sense?
</blockquote></details>

Done.

---

*[drake/tools/named_vector.proto, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRN2Fj5RAgUtOTmrxe:-KbRZKFrAJVHX7x0SaKP:b-es5o08) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/drake/tools/named_vector.proto#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Possibly `drake.tools`?  I think generally we namespace everything else that way.  (Or is that already implied somehow?)
</blockquote></details>

It is implied, see usage in lcm_vector_gen.

---

*[tools/six.BUILD, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbROgfDA-ZNgoYWABt5:-KbRZQDvVQlotrzTfG_R:b-3m66yi) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/tools/six.BUILD#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Do we need this genrule?  I would have suspected that `imports = ["six-1.10.0"]` on the `py_library` below would have done the job instead?
</blockquote></details>

Just mimicking upstream.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[WORKSPACE, line 145 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-KbRP3ouKRG0AH5ufFLh:-KbR_7ojuMK9eFMyKlEe:bkmlflx) ([raw file](https://github.com/robotlocomotion/drake/blob/75fd908c71d7208f209a2c0ec1db9ba24db19351/WORKSPACE#L145)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This mimicks upstream; absent specific concerns I'm inclined to leave it as-is?
</blockquote></details>

See bazelbuild/bazel#1952 and https://reviewable.io/reviews/robotlocomotion/drake/4235#-KXGWbt3_hE8CyMc14ef.  Possibly upstream is out of date a bit with modern practice?  I am marked OK here if you want to leave as-is, since it works, but that's the citation at least.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4912#-:-KbR_kbcKD5LHsz_3DIK:bnfp4nl)*

**Pull request merged**
