### PR TITLE
Simplify AddSolverIfAvailable; remove dead code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6159.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6424)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai for feature review, please.

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6424#-:-Kn_Di0dLi0bnStexV70:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review on-call, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6424#-:-Kn_IIAyoR7nw0KMpdqf:b-ik3eay)*

**Comment by sherm1** [comment]
That's a nice improvement! :lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6424#-:-KnaKL7JxY9tqattW1S6:b-k829vf)*

**Pull request merged**
