### PR TITLE
[Draft] SapSolver with sparsity analysis and constraints

### PR DESCRIPTION
**Pull request by amcastro-tri**
Prototype branch for design discussion of the full featured SapSolver.

cc'ing @xuchenhan-tri, @joemasterjohn

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[examples/simple_gripper/simple_gripper.cc, line 236 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-NUhfAgnY6obCdw8n:-Mv-NUhfAgnY6obCdw8o:buxim47) ([raw file](https://github.com/robotlocomotion/drake/blob/0229d11050669fcfc7662ff30cec4c66aae7b06c/examples/simple_gripper/simple_gripper.cc#L236)):*
> ```cpp
>       plant.GetJointByName<PrismaticJoint>("right_slider");
>   if (FLAGS_coupler_gear_ratio != 0.) {
>     contact_manager->AddCouplerConstraint(left_slider, right_slider,
> ```

FYI, this is how I was thinking we'd add constraints in the near future. The manager would provide sugar API for specific constraints; coupler, distance constraint, PD controllers, etc.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[multibody/plant/compliant_contact_manager.cc, line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-Nupd6PwBjkmjXWC-:-Mv-Nupd6PwBjkmjXWC0:bgnc0og) ([raw file](https://github.com/robotlocomotion/drake/blob/0229d11050669fcfc7662ff30cec4c66aae7b06c/multibody/plant/compliant_contact_manager.cc#L283)):*
> ```cpp
>       // Contat only involves a single tree (contact with the world or
>       // self-contact.)
>       const TreeJacobian<T>& tree_jacobian = tree_jacobian_pair.first.tree >= 0
> ```

FYI, this is the code that declares the contact constraints.
___
*[multibody/plant/compliant_contact_manager.cc, line 811 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-O5YP7lh2U55SNkKL:-Mv-O5YP7lh2U55SNkKM:b-venqji) ([raw file](https://github.com/robotlocomotion/drake/blob/0229d11050669fcfc7662ff30cec4c66aae7b06c/multibody/plant/compliant_contact_manager.cc#L811)):*
> ```cpp
>   // (heap allocation) of both A and v_star. Consider a constructor that keeps a
>   // reference to valid data in this scope.
>   auto problem = std::make_unique<SapContactProblem<T>>(
> ```

FYI, this is the code that makes the SapContactProblem. Below we instantiate a SapSolver out of this problem.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[multibody/contact_solvers/sap/sap_solver.h, line 510 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-aVA49RP0DsNuEzZ9:-Mv-aVA49RP0DsNuEzZA:b-c19yto) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/sap/sap_solver.h#L510)):*
> ```objc
>   mutable SolverStats stats_;
> 
>   std::unique_ptr<SapModel<T>> model_;
> ```

FYI, notice that effectively SapModel replaces the old PreProcessedData, though now it also encapsulates the math operations needed by SAP, without SAP needing to know specifics about the data stored in the model (before the solver had full access to PreProcessedData's internals).

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-oIzr2vUBG3h_Cwj7:-Mv-oIzr2vUBG3h_Cwj8:bbt8bd9) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/sap/sap_contact_problem.h#L57)):*
> ```objc
>   // Index of the second participating clique. It is negative is there is only a
>   // single clique that participates.
>   int clique1() const;
> ```

nit, @joemasterjohn recommended that whatever we do, it is consistent. That is, if clique1_jacobian() throws when not available, then clique1() should also throw.
Example, ContactSurface provides two different mesh representations, either mesh of triangles or mesh of polygons. In that case it uses nullptr semantics.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv-oIzr2vUBG3h_Cwj7:-Mv-pXc0CaCSGGlRDssS:b-oxjlb2) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/sap/sap_contact_problem.h#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, @joemasterjohn recommended that whatever we do, it is consistent. That is, if clique1_jacobian() throws when not available, then clique1() should also throw.
Example, ContactSurface provides two different mesh representations, either mesh of triangles or mesh of polygons. In that case it uses nullptr semantics.
</blockquote></details>

Joe: every time you give a negative index a meaning, you put the burden on the user code to check its validity. Vs, an exception would tell you explicitly you are doing the wrong thing.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-Mv0vKZ8Dzh054XG2c1w:b6z5ox0) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
> ```objc
> 
> // Represents a permutation p such that u[p(i)] = x[i].
> class PartialPermutation {
> ```

BTW, I need something like this class for deformables too, except that I'd like to permute block vectors of size 3. Do you think it could reuse some of this code?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-Mv102hYAy7h3Npfld08:bljhtcs) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I need something like this class for deformables too, except that I'd like to permute block vectors of size 3. Do you think it could reuse some of this code?
</blockquote></details>

I actually use it to permute the block diagonal matrix A, see [here](https://github.com/RobotLocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/sap/sap_model.cc#L114) when SapModel extracts participating DOFs dynamics.

I can do that because the `Apply()` and `ApplyInverse()` methods below are templated on a generic vector type. So thus far I've used it with `Eigen::VectorX` and `std::vector`. Is this what you need?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-Mv1P442D5vPJdpnPtbb:bjpl3wf) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I actually use it to permute the block diagonal matrix A, see [here](https://github.com/RobotLocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/sap/sap_model.cc#L114) when SapModel extracts participating DOFs dynamics.

I can do that because the `Apply()` and `ApplyInverse()` methods below are templated on a generic vector type. So thus far I've used it with `Eigen::VectorX` and `std::vector`. Is this what you need?
</blockquote></details>

I'll have to take a closer look, but glancing through the header, it seems like I can use this too.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-Mv3xiC-Brj4GhzR0CfM:bu30yqz) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'll have to take a closer look, but glancing through the header, it seems like I can use this too.
</blockquote></details>

That'd be great!. Do you have en example? we could probably add similar example to the unit tests to make sure we cover it.
Would this be a `std::vector<Vector3X<T>>` that needs to be permuted?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-MvKBaK35ahsR1XyJYXV:b-oqtgh6) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

That'd be great!. Do you have en example? we could probably add similar example to the unit tests to make sure we cover it.
Would this be a `std::vector<Vector3X<T>>` that needs to be permuted?
</blockquote></details>

It's actually a std::vector<VectorX<T>> -- The velocities of each body is stored in a flat vector. Feel free to assign me as the reviewer for this class, and I can add additional unit tests if needed.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16501)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/partial_permutation.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16501#-Mv0vKZ8Dzh054XG2c1v:-MvKrdkG4YKpN7OSHjqO:b7ec190) ([raw file](https://github.com/robotlocomotion/drake/blob/08fab53d7551e1c291079d6aeaaf594982defbdb/multibody/contact_solvers/partial_permutation.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's actually a std::vector<VectorX<T>> -- The velocities of each body is stored in a flat vector. Feel free to assign me as the reviewer for this class, and I can add additional unit tests if needed.
</blockquote></details>

perfect! then this class as-is would work for you!

**Pull request closed without merging**
