### PR TITLE
Provides (essentially) full matlab plotting capabilities from C++

### PR DESCRIPTION
**Pull request by RussTedrake**
Hopefully the inline documentation, and the example says it all.  
This is my first practical resolution to #3647 , and will make it much easier for me to port over (and debug) the more complex mathematical programs from matlab into C++.

+@hongkai-dai for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4088)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
One preemptory comment that might make the review flow easier...  IMO matlab-dependent code shall live in drake-distro/drake/matlab/..., and should not be allowed in drake-distro/drake/lcm.  If these files are going to relocate due do that rule, then it's often more convenient to do that before review begins.  In reviewable, the discussions sometimes come along with renamed files, but not always.

**Comment by RussTedrake** [comment]
@jwnimmer -- sounds reasonable.  Fwiw - only the client depends on matlab.

**Comment by hongkai-dai** [comment]
Reviewed 4 of 10 files at r1, 4 of 7 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/lcm/lcm_call_matlab.h, line 98 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4088#-KW8zkyuXLES9X59rkA4:-KW8zkyuXLES9X59rkA5:bwp6ncd) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0f081d48165cb1e3a9afa45c24dbad8829ab58/drake/lcm/lcm_call_matlab.h#L98)):*
> ```objc
> template <typename... Types>
> std::vector<LcmMatlabRemoteVariable> LcmCallMatlab(
>     const std::string &channel, const std::string &function_name,
> ```

I was told we prefer std::string& channel instead of std::string &channel, namely no space between type and "&"

---

*[drake/lcm/test/lcm_call_matlab_test.cc, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4088#-KW9-6qd4EEHnRWtMfMz:-KW9-6qeXhMdPx6cLrPH:b91bic4) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0f081d48165cb1e3a9afa45c24dbad8829ab58/drake/lcm/test/lcm_call_matlab_test.cc#L5)):*
> ```cpp
> #include "gtest/gtest.h"
> 
> #include "drake/lcm/lcm_call_matlab.h"
> ```

Include this first?

---

*[drake/lcm/test/lcm_call_matlab_test.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4088#-KW90Ami1T_tRVWPLaxP:-KW90Ami1T_tRVWPLaxQ:b6g4tbt) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0f081d48165cb1e3a9afa45c24dbad8829ab58/drake/lcm/test/lcm_call_matlab_test.cc#L34)):*
> ```cpp
>   }
> 
>   LcmCallMatlab("figure", 0, 1);
> ```

figure also returns a handle?

---

*[drake/matlab/util/lcm_call_matlab_client.cc, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4088#-KW92LhJlQXULQvQc2_U:-KW92LhK_5aAG3SKHV0L:b-tbxpyx) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0f081d48165cb1e3a9afa45c24dbad8829ab58/drake/matlab/util/lcm_call_matlab_client.cc#L27)):*
> ```cpp
>                  // will never actually be called.
> 
>   void handleMessage(const lcm::ReceiveBuffer* rbuf, const std::string& chan,
> ```

use `channel` instead of `chan`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4088)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/lcm/lcm_call_matlab.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4088#-KW97Pv9PfE_lUmiTVOT:-KW97Pv9PfE_lUmiTVOU:b-mh0hwm) ([raw file](https://github.com/robotlocomotion/drake/blob/6c0f081d48165cb1e3a9afa45c24dbad8829ab58/drake/lcm/lcm_call_matlab.cc#L44)):*
> ```cpp
>   memcpy(matlab_array->data.data(), &var, matlab_array->num_bytes);
> }
> ```

Probably also add Eigen sparse matrix as a future work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4088)*

**Comment by RussTedrake** [comment]
thanks @hongkai-dai .  will close while I resolve a few issues and reopen soon.

**Pull request closed without merging**
