### PR TITLE
Ensure pydrake tests do not run if C++ build fails

### PR DESCRIPTION
**Pull request by jamiesnape**
Related to #4383.

As a bonus, this removes a PODs function. I would fix the TODO, but I am hoping that SWIG will be disappearing soon.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4429)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review and +@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-:-KYVE0N4tUXOmji1_5Jo:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm: aside from requests for comments, and one point of clarification.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/python/CMakeLists.txt, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQ0atKi8XOczhl1ho:-KYVQ0auiA_Sf47vO0E2:b-i05uhn) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L21)):*
> ```CMake
> set(PYDRAKE_SOLVERS_SRCS
>   pydrake/solvers/__init__.py
>   pydrake/solvers/ik.py)
> ```

I see this file in my local build, but where does it even come from?  Since you've presumably already worked it out, please add a comment.

---

*[drake/bindings/python/CMakeLists.txt, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQ3OvjAIIkbPbGMhd:-KYVQ3Owzo7c4uB92n04:bz682r9) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L29)):*
> ```CMake
>   # TODO(jamiesnape): Fix swigmake, so we do not have to hard-code the paths.
>   set(PYDRAKE_REQUIRED_FILES
>     pydrake/_autodiffutils.so
> ```

Likewise, how do these get built (in the source tree?!)  Since you've presumably already worked it out, please add a comment.

---

*[drake/bindings/python/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQFChXve96l9bhytL:-KYVQFChXve96l9bhytM:bjtmqcf) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L38)):*
> ```CMake
>       WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")
>     set_tests_properties(test_python_${module_name} PROPERTIES
>       REQUIRED_FILES "${PYDRAKE_REQUIRED_FILES}")
> ```

This will cause the test to fail, not vanish, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-:-KYVQBJP5D9IiihhVV6B:b-rvojq4)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/python/CMakeLists.txt, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQ0atKi8XOczhl1ho:-KYVQe-Va0d9sxtzL6nd:b-ahzshp) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I see this file in my local build, but where does it even come from?  Since you've presumably already worked it out, please add a comment.
</blockquote></details>

They are python sources. They do not need to be built.

---

*[drake/bindings/python/CMakeLists.txt, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQ3OvjAIIkbPbGMhd:-KYVQlQ4d1ZG0wZcf-47:b9i6d2j) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L29)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Likewise, how do these get built (in the source tree?!)  Since you've presumably already worked it out, please add a comment.
</blockquote></details>

swig via swigmake. It is horrible. I will add a comment.

---

*[drake/bindings/python/CMakeLists.txt, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQFChXve96l9bhytL:-KYVQQIVZDsg17aLtqvV:b-c4j4s1) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This will cause the test to fail, not vanish, right?
</blockquote></details>

They will be reported as "Not Run", which is considered a failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429)*

**Comment by jamiesnape** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/python/CMakeLists.txt, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-KYVQ3OvjAIIkbPbGMhd:-KYVS8lS5_UCzzhqZYCk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba5ac45ab8e309b358658f2f2432038abd901c/drake/bindings/python/CMakeLists.txt#L29)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

swig via swigmake. It is horrible. I will add a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429#-:-KYV_fVIKRHl5IAjGKtE:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot  linux-gcc-experimental-open-source please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug  please
@drake-jenkins-bot linux-clang-experimental  please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-open-source please

**Comment by jamiesnape** [comment]
Resolved merge conflict.

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4429)*

**Pull request merged**
