### PR TITLE
Update cpplint_wrapper for Bazel

### LINKED ISSUE #6770: Modernize cpplint_wrapper.py
Right now, `cpplint_wrapper.py` calls out to the `git submodule` flavor of `google_styleguide`.  We want to stop using submodules, so at a minimum it needs to switch over Bazel's download of the tool.  Possibly the script should disappear entirely, now that "lint all the files" is part of the build system.  If so, we'll need to update `drake/doc/clion.rst` with the new recipe.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #6770.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6979)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6979#-:-KtMNKelJjR8wDzTOZrl:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI would you also like to do a feature review pass?

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
:lgtm:, one discretionary item below.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/cpplint_wrapper.py, line 125 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6979#-KtM_JYtGLY-A6tTm3oo:-KtMZrNfgpIP08ezIpOo:b-yxyi8c) ([raw file](https://github.com/robotlocomotion/drake/blob/31669dc71d16b397ab2de1e103ddf82d92ad57e5/drake/common/test/cpplint_wrapper.py#L125)):*
> ```Python
>         '--cpplint',
>         default=default_cpplint,
>         help='path to cpplint.py (default %(default)s)')
> ```

FYI:  This will give a rather confusing "default None" if no cpplint was found, implying that it is optional.  I don't see a good way to improve this, so feel free to wontfix if you also don't see a pleasant alternative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6979#-:-KtM_t1PRMmV_bztxlmO:b-h3w5d5)*

**Comment by SeanCurtis-TRI** [comment]
Is there an expectation that the following error message should contain absolute paths or relative paths (as shown below)?  I assume not. This is 99% about removing deprecated functionality, right? If that's the case :LGTM:

```
==================== Test output for //drake/geometry:geometry_state_cpplint:
drake/geometry/geometry_state.h:303:  At least two spaces is best between code and comments  [whitespace/comments] [2]
drake/geometry/geometry_state.h:305:  At least two spaces is best between code and comments  [whitespace/comments] [2]
Done processing drake/geometry/geometry_state.cc
Done processing drake/geometry/geometry_state.h
Total errors found: 2
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
================================================================================
```

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6979#-:-KtMdih_84jyGjNjEGyX:bn21m4s)*

**Comment by jwnimmer-tri** [comment]
> This is 99% about removing deprecated functionality, right?

Right-o.

> Is there an expectation that the following error message should contain absolute paths or relative paths (as shown below)?

My intent was to keep the build diagnostics with relative paths, but for the `$FilePath$` CLion tricks to end up with the absolute paths.

**Pull request merged**
