### PR TITLE
[doc] Remove extra quotation marks from Doxygen deprecation notes

### LINKED ISSUE #15619: DRAKE_DEPRECATED bleeds extra quotes into Doxygen
## Problem

To conform to style guide constrains (80 columns) it is common to spell a long deprecation message over several implicitly concatenated strings. For example, [`SceneGraph::get_pose_bundle_output_port()`](https://github.com/RobotLocomotion/drake/blob/5c7f033bdd492bcf239edfe2500fd5cbc342b666/geometry/scene_graph.h#L337-L344):

```c++
  DRAKE_DEPRECATED("2021-12-01",
                   "PoseBundle is no longer in use. Visualizers typically "
                   "connect to SceneGraph's QueryObject port.")
  const systems::OutputPort<T>& get_pose_bundle_output_port() const
```

It appears doxygen doesn't handle this practice with much elegance, producing the following result:

image

Note that it includes each string, with its enclosing double quotes in sequence.

(As a side note, the fact that it *also* includes quotes around the date is odd -- as if the date weren't a literal thing.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15619.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

A very elegant solution.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832#-:-MkgXjXbDeIrF-nrAcO9:b-w9rtgn)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/build.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh58lQ3ByAonIAHzuo:-Mkh58lR6K8Yyv0g_8PO:b8x9gw3) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L228)):*
> ```Python
> 
>     # Fix the formatting of deprecation text.
>     regexs = [
> ```

nit: this seems misnamed -- these are perl commands, not just regular expressions
___
*[doc/doxygen_cxx/build.py, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh5dMUATpVBvhBF85f:-Mkh5dMUATpVBvhBF85g:bicn60w) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L230)):*
> ```Python
>     regexs = [
>         # Remove quotes around the removal date.
>         r's#(removed from Drake on or after) "(....-..-..)" *\.#\1 \2.#g;',
> ```

BTW is the final `g` needed here? In my vague memory that means "everywhere on the line" but this should only occur once.
___
*[doc/doxygen_cxx/build.py, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh6plH78lf2U9ZN3Cu:-Mkh6plH78lf2U9ZN3Cv:bjhjykx) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L237)):*
> ```Python
>         # <dl class="deprecated"><dt><b><a class="el" href="deprecated.html#_deprecated000013">Deprecated:</a></b></dt><dd>"Use RotationMatrix::MakeFromOneVector()." <br />  # noqa
>         # <dd><a class="anchor" id="_deprecated000013"></a>"Use RotationMatrix::MakeFromOneVector()." <br />  # noqa
>         r'while (s#(?<=_deprecated\d{6}")([^"]*)"(.*?<br)#\1\2#g) {};',
> ```

minor: I'm having trouble figuring out how this gets rid of spurious quotes. It would help I think to have one of the examples above be a case in which there are spurious quotes to remove.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/build.py, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh6plH78lf2U9ZN3Cu:-Mkh9_CLALUnhXat6kGA:b-u95r8i) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L237)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I'm having trouble figuring out how this gets rid of spurious quotes. It would help I think to have one of the examples above be a case in which there are spurious quotes to remove.
</blockquote></details>

Working

It actually removes _all_ quotes from the text, under the presumption that all quotes are spurious.  I'll try work on clarifying that in the code.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/build.py, line 228 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh58lQ3ByAonIAHzuo:-MkhXhjJA-WSjCDAQa5a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L228)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this seems misnamed -- these are perl commands, not just regular expressions
</blockquote></details>

Done.
___
*[doc/doxygen_cxx/build.py, line 230 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh5dMUATpVBvhBF85f:-MkhXMQy1JZwekCd3x1U:b-jp5iua) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L230)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is the final `g` needed here? In my vague memory that means "everywhere on the line" but this should only occur once.
</blockquote></details>

Removed.  It's just a habit I have (because, why _wouldn't_ you always want a regexp to substitute all instances), but I agree in this case it's mostly just misleading.
___
*[doc/doxygen_cxx/build.py, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15832#-Mkh6plH78lf2U9ZN3Cu:-MkhYWcg2H2IMB1lV7rD:b-o4zmjv) ([raw file](https://github.com/robotlocomotion/drake/blob/5af3deeb1e223fbfa317f81b2090f7acb309d348/doc/doxygen_cxx/build.py#L237)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

It actually removes _all_ quotes from the text, under the presumption that all quotes are spurious.  I'll try work on clarifying that in the code.
</blockquote></details>

Done.

It didn't seem to me like changing the examples would help much; I tried to clarify the text instead.

**Review by sherm1 — COMMENTED** [review]
Great, thanks! Platform :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15832#-:-MkhlNRd5ZqEhKlVgxiw:b3ycjo5)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
