### PR TITLE
[tools/dev] Cleanup debian packaging script

### PR DESCRIPTION
**Pull request by svenevs**
- Add __doc__ with a brief example usage description.
- Update the default of --output-dir to be the path that the user ran bazel from ('.' refers to something in the bazel sandbox).
- Fail early if the input .tar.gz or output directory cannot be found.
- Remove stale comments.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17317)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for review please.  CC @jwnimmer-tri after these fixes this could get promoted out of `dev/` so that we can turn it on in CI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17317#-:-N3_RbU58vAeCt-6my-V:b1sm9mc)* status: LGTM missing from assignee BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail)

___
*[`tools/release_engineering/dev/repack_deb.py` line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3_QrlJ5GqOYWo6LuWx:-N3_QrlJ5GqOYWo6LuWy:b-cjunuu) ([raw file](https://github.com/robotlocomotion/drake/blob/e80d001876a8c14dbd46e8a5f8c0d1eaf0e7de1a/tools/release_engineering/dev/repack_deb.py#L14)):*
> ```Python
> # (*) Lots of shlibdebs spam during build. We should at least nerf the stuff
> # from drake-visualizer, for starters. Possibly we shouldn't be calling
> # shlibdeps at all, assuming that packages-focal.txt is authoritative.
> ```

FYI this is being tracked in #17161, the only high priority fixes are already in (`libpython` really).
___
*[`tools/release_engineering/dev/repack_deb.py` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3_R-80E40M2_xx3Aux:-N3_R-80E40M2_xx3Auy:bwl5dts) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L151)):*
> ```Python
>     # ran the bazel command from in their terminal.  See
>     # https://bazel.build/docs/user-manual
>     output_default = os.path.realpath(os.environ['BUILD_WORKING_DIRECTORY'])
> ```

FYI since we run this through bazel `.` goes somewhere deep in the bazel trenches, the `BUILD_WORKING_DIRECTORY` is set by `bazel` and refers to wherever the user's terminal is that ran the `bazel` command.  In development I just kept using e.g., `$PWD/drake_deb` but long term this is a nicer solution for the user -- the original output directory is never denoted to them and it'll appear like the script finished and nothing happened.
___
*[`tools/release_engineering/dev/repack_deb.py` line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3_RPiyDYF2PNYMo7Xt:-N3_RPiz6CoTrtYQGzSQ:b-vce32r) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L174)):*
> ```Python
>         parser.error(
>             f'{args.output_dir} is not a directory, please use absolute paths '
>             'for command line arguments.')
> ```

FYI just making life easier for the user, if `output_dir` doesn't exist the script crashes at the very end via `shutil.move` to something it cannot :upside_down_face:

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17317#-:-N3aDZ5c4fz6PE3rJDfc:bnfp4nl)* status: 1 unresolved discussion (waiting on @svenevs)

___
*[`tools/release_engineering/dev/repack_deb.py` line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3aC8Cf9KCpfe_nShxU:-N3aC8Cf9KCpfe_nShxV:b54kpgp) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L11)):*
> ```Python
>     bazel run //tools/release_engineering/dev/repack_deb -- \
>         --tgz "$PWD/drake-latest-focal.tar.gz" \
>         --output-dir "$PWD/drake_deb"
> ```

Nit Use the default option here? 
___
*[`tools/release_engineering/dev/repack_deb.py` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3_R-80E40M2_xx3Aux:-N3aBaEK3wjUOFnVklcQ:b6ujmyu) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L151)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI since we run this through bazel `.` goes somewhere deep in the bazel trenches, the `BUILD_WORKING_DIRECTORY` is set by `bazel` and refers to wherever the user's terminal is that ran the `bazel` command.  In development I just kept using e.g., `$PWD/drake_deb` but long term this is a nicer solution for the user -- the original output directory is never denoted to them and it'll appear like the script finished and nothing happened.
</blockquote></details>

Nit Don't need to refer to the bazel user manual in the comment, BUILD_WORKING_DIRECTORY is used elsewhere and is easy enough to look up, if needed.

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17317)* status: :shipit: complete! all discussions resolved, LGTM from assignee BetsyMcPhail, exempt from platform review (waiting on @svenevs)

___
*[`tools/release_engineering/dev/repack_deb.py` line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3aC8Cf9KCpfe_nShxU:-N47ygeZEbgTOwUvxUb5:b9doewq) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L11)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit Use the default option here? 
</blockquote></details>

Done, the `--help` displays the default output directory (which would be `$PWD`).  The example is using a different output-directory to emphasize the necessity for absolute paths when asking for something else.  If you just do `--output-dir drake_deb` it'll run, get created, save it there, then get deleted unless you have `--sandbox_debug`.  So I'd prefer to keep the example as is.
___
*[`tools/release_engineering/dev/repack_deb.py` line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17317#-N3_R-80E40M2_xx3Aux:-N47z7I_5cotRtuHfJRe:b-wros1c) ([raw file](https://github.com/robotlocomotion/drake/blob/35c61a947cfae3eae3ed4690444bd76cd92a1384/tools/release_engineering/dev/repack_deb.py#L151)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit Don't need to refer to the bazel user manual in the comment, BUILD_WORKING_DIRECTORY is used elsewhere and is easy enough to look up, if needed.
</blockquote></details>

OK, removed the link.

**Comment by jwnimmer-tri** [comment]
I took a quick skim.  I think this is fine to PR right away to move out of `dev`.  You can tag me as feature review (to rubber-stamp the merge), then we'll do on-call platform.

**Pull request merged**
