### PR TITLE
Linearize about a non-equilibrium point

### PR DESCRIPTION
**Pull request by jadecastro**
This enables linearization along a trajectory for purposes such as trajectory-tracking controller design.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7140)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@russtedrake for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvEEGpNbVFjvZ9whooI:b-e8hf3g)*

**Comment by RussTedrake** [comment]
"linearizing" at a non-equilibrium is aok (taking the first order taylor expansion), but the output should be an AffineSystem, not a LinearizationData.

linearizing along a trajectory is again a well-defined (but in my mind different) thing.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvEq9Nd96yVJierhgW9:by2vaaz)*

**Comment by jadecastro** [comment]
Agreed. I've made that change to employ an AffineSystem as return argument. PTAL at the change.

And, yes, I probably shouldn't have made mention of a trajectory, since we're merely using a point here. (The code, at least, doesn't mention it at all)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvV0bT6bpWjjGRnHMMp:bmghq2t)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.h, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVMPS_Rcj2Q_kqFsHs:-KvVMPSac48yd3r8_tBn:bi49j56) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L94)):*
> ```objc
> };
> 
> enum WhichAction { DoLinearize, DoThrow };
> ```

Maybe better to use `enum class` rather than `enum`, as suggested by https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum?

---

*[drake/systems/primitives/linear_system.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVNB9JXPxeAIqLcCH9:-KvVNB9JXPxeAIqLcCHA:b-83m3ea) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L134)):*
> ```objc
> ///   @f[ x[n+1] - x0[n+1] = A (x[n] - x0[n]) + B (u[n] - u0[n]), @f]
> /// for discrete time.  But, since @f$ \dot{x} = f0 @f$ (in CT) and
> /// @f$ x0[n+1] = f0 @f$ (in DT), the system is represented as an affine system.
> ```

It would help, if you could mention what is the state in the new linearized system. Here we have two options
1. `x` is the state of the new system, then the dynamics is affine.
2. `x_bar = x - x0` is the state of the new system, then the dynamics is linear.

I think it would help the user if you could mention that the state of the new system is `x` instead of `x_bar`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by jadecastro** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.h, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVMPS_Rcj2Q_kqFsHs:-KvYON0p1FXEaWcAnwDp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L94)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe better to use `enum class` rather than `enum`, as suggested by https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum?
</blockquote></details>

Done.

---

*[drake/systems/primitives/linear_system.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVNB9JXPxeAIqLcCH9:-KvYOOzeW3TXEKB9sAv4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L134)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It would help, if you could mention what is the state in the new linearized system. Here we have two options
1. `x` is the state of the new system, then the dynamics is affine.
2. `x_bar = x - x0` is the state of the new system, then the dynamics is linear.

I think it would help the user if you could mention that the state of the new system is `x` instead of `x_bar`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/linear_system.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVNB9JXPxeAIqLcCH9:-KvZ3FOjcwlEjl4xLMnO:b-15wxl8) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L134)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry I am slow here, but the equations do not seem right to me. We have
```
ẋ - ẋ₀ = A*(x - x₀) + B * (u - u₀)
```
which is equivalent to
```
ẋ = A * x + B * u + (ẋ₀ - A * x₀ - B * u₀)
```
namely the constant term in the affine dynamics is ẋ₀ - A * x₀ - B * u₀, instead of ẋ₀.

Moreover, whether the dynamics is affine or not, does not depend on whether the linearized point (x₀, u₀) is an equilibrium point or not, but whether the quantity ẋ₀ - A * x₀ - B * u₀ is zero.

I think it is more common, that people define the state of the linearized system as 
x̅ = x - x₀, u̅ = u - u₀, and the linearized dynamics is
```
x̅_dot = A * x̅ + B * u̅
```
a linear dynamical system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by jadecastro** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/linear_system.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVNB9JXPxeAIqLcCH9:-KvZxcawfRQhJ2R4Wj-g:b-8e30cy) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L134)):*
Typo fixed. Thanks. Note that the main point to be made here is the state/input variables are x, u and not x̅, u̅.

> Moreover, whether the dynamics is affine or not, does not depend on whether the linearized point (x₀, u₀) is an equilibrium point or not, but whether the quantity ẋ₀ - A * x₀ - B * u₀ is zero.

I'm not sure if I'm misunderstanding, but a system is at equilibrium at (x₀, u₀) if ẋ₀ = f(x₀, u₀) = 0.  Since both x₀, u₀ can be nonzero, ẋ₀ - A x₀ - B u₀ does not have to be zero.  When ẋ₀ is zero, then we have the usual x̅_dot = ẋ = A x̅ + B u̅ (note the derivative is taken on the absolute state).  Otherwise we have an affine form.

The reason why we're not using the form x̅_dot = A x̅ + B u̅ is that we lose the term f(x₀, u₀), since it becomes implicit within x̅_dot. To recover the actual dynamics (ẋ = A(x - x₀) + B(u - u₀) + ẋ₀), we need to either somehow store f(x₀, u₀) with the resultant LinearSystem using perturbed states (x̅) or else do that with AffineSystem by using absolute states (x). The latter is preferred.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/linear_system.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvVNB9JXPxeAIqLcCH9:-Kv_N6wyG5dNdWyY3HzH:buow0n1) ([raw file](https://github.com/robotlocomotion/drake/blob/234fed1f5d043d39556fa00877b91f4b407608d1/drake/systems/primitives/linear_system.h#L134)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

Typo fixed. Thanks. Note that the main point to be made here is the state/input variables are x, u and not x̅, u̅.

> Moreover, whether the dynamics is affine or not, does not depend on whether the linearized point (x₀, u₀) is an equilibrium point or not, but whether the quantity ẋ₀ - A * x₀ - B * u₀ is zero.

I'm not sure if I'm misunderstanding, but a system is at equilibrium at (x₀, u₀) if ẋ₀ = f(x₀, u₀) = 0.  Since both x₀, u₀ can be nonzero, ẋ₀ - A x₀ - B u₀ does not have to be zero.  When ẋ₀ is zero, then we have the usual x̅_dot = ẋ = A x̅ + B u̅ (note the derivative is taken on the absolute state).  Otherwise we have an affine form.

The reason why we're not using the form x̅_dot = A x̅ + B u̅ is that we lose the term f(x₀, u₀), since it becomes implicit within x̅_dot. To recover the actual dynamics (ẋ = A(x - x₀) + B(u - u₀) + ẋ₀), we need to either somehow store f(x₀, u₀) with the resultant LinearSystem using perturbed states (x̅) or else do that with AffineSystem by using absolute states (x). The latter is preferred.
</blockquote></details>

I think we are on the same page. I was mainly trying to make it clear that in the documentation
```
More precisely, let x be a state and u be an input.  This function returns
/// an AffineSystem of the form:
///   @f[ \dot{x} = A x + B u + f0, @f] (CT)
```
`f0` should be `ẋ₀ - A * x₀ - B * u₀`, instead of `f0 = ẋ`. As you have changed the documentation, that becomes clear now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-Kvhg3kipt1XI7esMsi8:bl5ccwd)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvhgkBk9jzfrTA38Qbl:-KvhgkBk9jzfrTA38Qbm:bkp4jhy) ([raw file](https://github.com/robotlocomotion/drake/blob/50ba15b15f01ec8fd7c1fdd4046c9bc116f801fb/drake/systems/primitives/linear_system.h#L134)):*
> ```objc
> ///   @f[ x[n+1] - x0[n+1] = A (x[n] - x0[n]) + B (u[n] - u0[n]), @f]
> /// for discrete time.  As above, we denote x0, u0 to be the nominal state and
> /// input at the provided @p context.  But, since the terms @f$ \dot{x} @f$
> ```

You mean `@f$ \dot{x0} @f$`? namely `x->x0`

---

*[drake/systems/primitives/linear_system.h, line 135 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvhgY8mNU2H4Ohob_8w:-KvhgY8mNU2H4Ohob_8x:bq5hitj) ([raw file](https://github.com/robotlocomotion/drake/blob/50ba15b15f01ec8fd7c1fdd4046c9bc116f801fb/drake/systems/primitives/linear_system.h#L135)):*
> ```objc
> /// for discrete time.  As above, we denote x0, u0 to be the nominal state and
> /// input at the provided @p context.  But, since the terms @f$ \dot{x} @f$
> /// and @f$ x0[n+1] @f$ are nonzero, we conclude that the system description is
> ```

I think the reason why the system is affine, is not that `ẋ0` is not zero, but `\dot{x0} - A*x0 - B * u0` is not 0. i.e., if we choose `x` as the state of the new linearized system, instead of the error state `x_bar = x - x0`, then even at the equilibrium point with `x0` not 0, the linearized dynamics
```
\dot{x} = A * x + B * u + \dot{x0} - A * x0 - B * u0
```
can still be an affine system, instead of a linear system (\dot{x0} is 0 in this case, but `A * x0 + B * u0` is not necessarily 0).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by RussTedrake** [comment]
I'm sorry that I've been slow on this.  It brings up all of the issues that I resolved once (in matlab) using CoordinateFrames and AffineTransforms.  Would be good to f2f about it (w/ hongkai, too, if he's interested)

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KviwCxqpoMJFxmE5owi:b-1c8cqh)*

**Comment by hongkai-dai** [comment]
I would love to attend the meeting.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvjfGPyBUP1slAaw_ST:b-5smkeu)*

**Comment by jadecastro** [comment]
Great! I'll schedule something during the cancelled Sim team meeting slot.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvkwWT_rR7pEE1Ti9sN:bd54je)*

**Comment by jadecastro** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvhgkBk9jzfrTA38Qbl:-Kvl5buTU-lYKJgrpHUD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50ba15b15f01ec8fd7c1fdd4046c9bc116f801fb/drake/systems/primitives/linear_system.h#L134)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You mean `@f$ \dot{x0} @f$`? namely `x->x0`
</blockquote></details>

Done.

---

*[drake/systems/primitives/linear_system.h, line 135 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-KvhgY8mNU2H4Ohob_8w:-KvlFklW8bUwqxUK2YaM:b-ao4pun) ([raw file](https://github.com/robotlocomotion/drake/blob/50ba15b15f01ec8fd7c1fdd4046c9bc116f801fb/drake/systems/primitives/linear_system.h#L135)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the reason why the system is affine, is not that `ẋ0` is not zero, but `\dot{x0} - A*x0 - B * u0` is not 0. i.e., if we choose `x` as the state of the new linearized system, instead of the error state `x_bar = x - x0`, then even at the equilibrium point with `x0` not 0, the linearized dynamics
```
\dot{x} = A * x + B * u + \dot{x0} - A * x0 - B * u0
```
can still be an affine system, instead of a linear system (\dot{x0} is 0 in this case, but `A * x0 + B * u0` is not necessarily 0).
</blockquote></details>

Fixed - thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by jadecastro** [comment]
Okay, I've reworked the naming scheme and documentation, which I think captures what we discussed. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KvyfqsNnRE3GWxBkgpA:b9kyqyb)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw0r8guhccHLZqfMUk7:-Kw0r8guhccHLZqfMUk8:bmb21vt) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L116)):*
> ```cpp
> }
> 
> void ThrowNonEquilibrium() {
> ```

Change the function name? The difference is not whether the linearization happens at a equilibrium or not, but whether it happens at an equilibrium at the origin.

---

*[drake/systems/primitives/linear_system.cc, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw0qroXTxchX61e7Ssn:-Kw0qroXTxchX61e7Sso:bmmqsk0) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L124)):*
> ```cpp
> 
> // Builds the A and B matrices of the system's discrete/continuous state
> // equation, along with the affine term f0 (nonzero when not at equilibrium).
> ```

I think `f0` is non-zero, not because it is not at equilibrium, but because the linearized state/control (x0, u0) is at the origin. For example, the upright position of a pendulum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw0qroXTxchX61e7Ssn:-Kw0xvvv4GOXpKp1CyqX:bgp2502) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L124)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think `f0` is non-zero, not because it is not at equilibrium, but because the linearized state/control (x0, u0) is at the origin. For example, the upright position of a pendulum.
</blockquote></details>

I am a bit unclear about the return argument in this function, could you explain it more clear in the documentation? It looks to me that the code actually returns both the gradient of xdot, and also the value of xdot. The value of the xdot is not necessarily the value of the affine term f0, as suggested in the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/linear_system.cc, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw0r8guhccHLZqfMUk7:-Kw0zw7eUzwndBV0PsGM:b-7vz2l3) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Change the function name? The difference is not whether the linearization happens at a equilibrium or not, but whether it happens at an equilibrium at the origin.
</blockquote></details>

Please ignore this comment. Resolved through f2f discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 3 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 173 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw15L7iZh3ixlz9duxM:-Kw15L7iZh3ixlz9duxN:b-34qqzy) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L173)):*
> ```cpp
> }
> 
> std::unique_ptr<AffineSystem<double>> Linearize(
> ```

Based on our discussion, the function should be renamed as `<AffineSystem<double>> DoFirstOrderTaylorSeriesApproximation()`

---

*[drake/systems/primitives/test/linear_system_test.cc, line 194 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw17PgR724MwgsqRSIC:-Kw17PgR724MwgsqRSID:bl983vt) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/test/linear_system_test.cc#L194)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(D_, affine_system->D(), tol,
>                               MatrixCompareType::absolute));
>   EXPECT_TRUE(CompareMatrices(A_ * x0_ + B_ * u0_ + f0_,
> ```

I thought the affine term is `f0 - A * x0 - B * u0`.

---

*[drake/systems/primitives/test/linear_system_test.cc, line 197 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw17ayvBnmdrDCJYJ55:-Kw17ayvBnmdrDCJYJ56:b-jj02x6) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/test/linear_system_test.cc#L197)):*
> ```cpp
>                               affine_system->f0(), tol,
>                               MatrixCompareType::absolute));
>   EXPECT_TRUE(CompareMatrices(C_ * x0_ + D_ * u0_ + y0_,
> ```

I thought the affine term is `y0 - C * x0 - D * u0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by jadecastro** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 124 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw0qroXTxchX61e7Ssn:-Kw6rPTgAdTqwgGUgZg8:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L124)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am a bit unclear about the return argument in this function, could you explain it more clear in the documentation? It looks to me that the code actually returns both the gradient of xdot, and also the value of xdot. The value of the xdot is not necessarily the value of the affine term f0, as suggested in the documentation.
</blockquote></details>

Done. 

---

*[drake/systems/primitives/linear_system.cc, line 173 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw15L7iZh3ixlz9duxM:-Kw6T2kL_1EekhVX6lRm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/linear_system.cc#L173)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Based on our discussion, the function should be renamed as `<AffineSystem<double>> DoFirstOrderTaylorSeriesApproximation()`
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/linear_system_test.cc, line 194 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw17PgR724MwgsqRSIC:-Kw6qeJft9uZMu4gmOIf:b3u0nez) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/test/linear_system_test.cc#L194)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I thought the affine term is `f0 - A * x0 - B * u0`.
</blockquote></details>

Thanks. This exposed an algebra error when making the `affine_system->f0()` and `affine_system->y0()` terms. I've fixed those, and now the AffineSystem should be in the correct coordinate system. Please have a look. 

---

*[drake/systems/primitives/test/linear_system_test.cc, line 197 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw17ayvBnmdrDCJYJ55:-Kw6rzV4sKEyTeOMz1WY:b4fx5xl) ([raw file](https://github.com/robotlocomotion/drake/blob/c1ca16f3539670a69bb2363497ef33d97148838d/drake/systems/primitives/test/linear_system_test.cc#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I thought the affine term is `y0 - C * x0 - D * u0`.
</blockquote></details>

(As above). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-Kw6tPK3psr34c5WBjZc:b-t6qajt)*

**Comment by sammy-tri** [comment]
Just a couple of minor issues.

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 230 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw7UOqKbT438-dgpOdk:-Kw7UOqKbT438-dgpOdl:b-po2p5z) ([raw file](https://github.com/robotlocomotion/drake/blob/9e37700ccac50df5a1a3e3a370cb1da3b841d94d/drake/systems/primitives/linear_system.cc#L230)):*
> ```cpp
> 
>   Eigen::MatrixXd AB;
>   Eigen::VectorXd f_at_basepoint = Eigen::VectorXd::Zero(num_states);
> ```

BTW It reads slightly strange that we initialize `f_at_basepoint` and not `AB`.  Doesn't the assignment below wipe out this initialization with zero?

---

*[drake/systems/primitives/linear_system.h, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw7TLclYLpWLREi-CLd:-Kw7TLclYLpWLREi-CLe:b-zdh4k0) ([raw file](https://github.com/robotlocomotion/drake/blob/9e37700ccac50df5a1a3e3a370cb1da3b841d94d/drake/systems/primitives/linear_system.h#L94)):*
> ```objc
> };
> 
> enum class WhichAction { DoLinearize, DoThrow };
> ```

Does this need to be declared in the header?  Or could we move it into the anonymous namespace in the `.cc` file?  It seems very implementation specific to be in the `drake::systems` namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-Kw7VZV98DeoIK9y0Ntn:b169f2q)*

**Comment by jadecastro** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/linear_system.cc, line 230 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw7UOqKbT438-dgpOdk:-Kw8Plb9rgPayzyzaPPK:b-ymuymn) ([raw file](https://github.com/robotlocomotion/drake/blob/9e37700ccac50df5a1a3e3a370cb1da3b841d94d/drake/systems/primitives/linear_system.cc#L230)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW It reads slightly strange that we initialize `f_at_basepoint` and not `AB`.  Doesn't the assignment below wipe out this initialization with zero?
</blockquote></details>

Oops - it absolutely does. Thanks for pointing this out. Done.

---

*[drake/systems/primitives/linear_system.h, line 94 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-Kw7TLclYLpWLREi-CLd:-Kw8PjjeJn03VrEi8M4q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e37700ccac50df5a1a3e3a370cb1da3b841d94d/drake/systems/primitives/linear_system.h#L94)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Does this need to be declared in the header?  Or could we move it into the anonymous namespace in the `.cc` file?  It seems very implementation specific to be in the `drake::systems` namespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KwAp1VY8XvJNRzXNa7K:bnfp4nl)*

**Comment by jadecastro** [comment]
-@RussTedrake 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7140#-:-KwApI7d4_VOQ40RODfD:b-t7mwbl)*

**Pull request merged**
