### PR TITLE
[yaml] Remove deprecated functions 2022-03

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16673)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for both reviews, please?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16673#-:-Mwm2UTu-jB6MkFNdfbT:b71iyt8)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16673#-Mwm2JaT5BHBL0ywqXkJ:-Mwm2JaU4J8ZrSyJb9WN:b-5o6oem) (no related file):*
Working

Do not merge until 2022-03-01.

---

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16673#-:-MwmByJJE2-MlivB1HRJ:b4xzh7p)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16673)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16673)* status: :shipit: complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16673#-Mwm2JaT5BHBL0ywqXkJ:-Mx1lom_BLwjaz4983L0:b-mgnqr5) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge until 2022-03-01.
</blockquote></details>

OK
```
jwnimmer@call-cps:~$ date -u -R
Tue, 01 Mar 2022 00:00:27 +0000
```

---

**Pull request merged**
