### PR TITLE
refactor plan eval part 1

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
0. added a base class for plan eval.
1. moved the old humanoid specific parts to humanoid plan eval. 
2. added a test for humanoid plan eval + qp controller.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5442)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-:-KeevJJqdcLgNz9Ul8fZ:b-gjuu32)*

**Comment by naveenoid** [comment]
I only have very minor nits. :lgtm: 

---

Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Ket0aIvEptp-bDVYo4D:-Ket0aIvEptp-bDVYo4E:b-n131kv) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L20)):*
> ```objc
>  * set point is set by Initialize().
>  */
> class HumanoidPlanEvalSystem : public PlanEvalBaseSystem {
> ```

BTW : This this particular PlanEvalSystem only does the torso sine wave thing, do you want to give it the generic name of "HumanoidPlanEvalSystem" and not a more task / demo specific name?

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Kesnzkj5ndttYbxZi8z:-Kesnzkj5ndttYbxZi9-:b-2b3wul) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.h#L117)):*
> ```objc
> 
>   /**
>    * Derived class need to implement this to computed custom outputs.
> ```

nit: "Derived classes" for each of these methods.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Kespvg5pgUJ5ER0TzZS:-Kespvg5pgUJ5ER0TzZT:b-l5ub66) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L25)):*
> ```cpp
> // valkyrie). Output is then evaluated with a measured state also set to the
> // same desired p. The expected behavior is that QpInput from
> // HumanoidPlanEvalSystem be zero desired accelereations, and the acceleration
> ```

nit: typo on "accelerations"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-:-Ket0xjXfA6IWjEeh1hg:bep2vv7)*

**Comment by siyuanfeng-tri** [comment]
+@ggould-tri for platform review, thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-:-KetO-UzRlM4LM4npiUz:b-1yt728)*

**Comment by ggould-tri** [comment]
:lgtm: pending open discussions. +(status: curate commits before merging) 

---

Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keturcd8EZ0Lcnob4G3:-Keturcevmz5W0F7VQ7D:btn2e5d) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L44)):*
> ```cpp
> HumanoidPlanEvalSystem::ExtendedAllocateOutputAbstract(
>     const systems::OutputPortDescriptor<double>& descriptor) const {
>   DRAKE_DEMAND(false);
> ```

FYI If you use `DRAKE_ABORT` or `DRAKE_ABORT_MSG` here you can skip the `return` below.  I would suggest the MSG variant with an explanatory string about why this is not expected.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetxlbtEJkkgqGtQXI3:-KetxlbtEJkkgqGtQXI4:b6pikqt) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L125)):*
> ```cpp
>   plan.joint_servo.mutable_desired_position() = q_d;
> 
>   // Sets the gains
> ```

FYI Sentence needs punctuation.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Ket0aIvEptp-bDVYo4D:-Keu0Jwb6cwduu3BxR_2:b-zchut0) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L20)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW : This this particular PlanEvalSystem only does the torso sine wave thing, do you want to give it the generic name of "HumanoidPlanEvalSystem" and not a more task / demo specific name?
</blockquote></details>

Well, it is under the `examples` directory, which sort of implies it is an example.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvWCQnC_W_JeUzLG1:-KetvWCQnC_W_JeUzLG2:b8ijtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L46)):*
> ```objc
> 
>  private:
>   int get_num_extended_abstract_states() const { return 1; }
> ```

Should be `override`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvYKDnq4atcrnlAdW:-KetvYKDnq4atcrnlAdX:b8ijtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L49)):*
> ```objc
> 
>   void DoExtendedCalcUnrestrictedUpdate(const systems::Context<double>& context,
>                                         systems::State<double>* state) const;
> ```

Should be `override`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvYncnh2POLiDyu7i:-KetvYncnh2POLiDyu7j:b8ijtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L52)):*
> ```objc
> 
>   void DoExtendedCalcOutput(const systems::Context<double>& context,
>                             systems::SystemOutput<double>* output) const;
> ```

Should be `override`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetveSrdhuyvsqJP2L0:-KetveSrdhuyvsqJP2L1:b8ijtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L55)):*
> ```objc
> 
>   std::vector<std::unique_ptr<systems::AbstractValue>>
>   ExtendedAllocateAbstractState() const;
> ```

Should be `override`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvfD19wbtGOwdaU_8:-KetvfD2IcxNq-p27Sei:b8ijtlx) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L58)):*
> ```objc
> 
>   std::unique_ptr<systems::AbstractValue> ExtendedAllocateOutputAbstract(
>       const systems::OutputPortDescriptor<double>& descriptor) const;
> ```

Should be `override`.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetzNOH8fBS0AWHcylB:-KetzNOIquBXlp89c61z:b-r6sqfi) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.cc#L46)):*
> ```cpp
>   qp_input = context.get_abstract_state<QpInput>(abs_state_index_qp_input);
> 
>   // Does extended CacOutput.
> ```

FYI typo "Cac"

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keu0fbd_UPOPbzQtfZN:-Keu0fbd_UPOPbzQtfZO:b53wg8v) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L31)):*
> ```cpp
> // many objectives, the results is not going to match the desired input exactly
> // unless set as hard constraints.
> class HumanoidPlanEvalAndQpInverseDyanmicsTest : public ::testing::Test {
> ```

FYI typo "Dyanmics"

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keu0kvka2VS2x-Ild9v:-Keu0kvka2VS2x-Ild9w:bbj6726) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L44)):*
> ```cpp
>         "config/valkyrie.alias_groups";
> 
>     const std::string kControllConfigPath =
> ```

FYI typo "Controll"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-:-Keu1woEiw1pieWnJJQv:b-tyvfjr)*

**Comment by siyuanfeng-tri** [comment]
Review status: 6 of 10 files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keturcd8EZ0Lcnob4G3:-KeuIXD47trZvDrBvMCr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L44)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI If you use `DRAKE_ABORT` or `DRAKE_ABORT_MSG` here you can skip the `return` below.  I would suggest the MSG variant with an explanatory string about why this is not expected.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetxlbtEJkkgqGtQXI3:-KeuIbJFQ2XgdkAKKCLE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.cc#L125)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI Sentence needs punctuation.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Ket0aIvEptp-bDVYo4D:-KetNDU1UyLmjAv8W5qX:bs4y9zv) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L20)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW : This this particular PlanEvalSystem only does the torso sine wave thing, do you want to give it the generic name of "HumanoidPlanEvalSystem" and not a more task / demo specific name?
</blockquote></details>

My intention was that this system wrapper would stay the same, and I will be generating different kind of plans during run time. The simple plan that's actually implemented here is only a stub. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvWCQnC_W_JeUzLG1:-KeuJ1VvJcK_SBW0rhej:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Should be `override`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvYKDnq4atcrnlAdW:-KeuJ1tvV2KcU1dXVj8o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L49)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Should be `override`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvYncnh2POLiDyu7i:-KeuJ2GoRt4FYFvI-QVa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L52)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Should be `override`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetveSrdhuyvsqJP2L0:-KeuJ3EwbF2HQDwWs7Mi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L55)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Should be `override`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h, line 58 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetvfD19wbtGOwdaU_8:-KeuJ3a068sMhnr63z0y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_plan_eval_system.h#L58)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Should be `override`.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-KetzNOH8fBS0AWHcylB:-KeuJAPvqGw9H50On7UE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.cc#L46)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "Cac"
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Kesnzkj5ndttYbxZi8z:-KetNj_yVmF4EpH1jZUl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/plan_eval_base_system.h#L117)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

nit: "Derived classes" for each of these methods.
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Kespvg5pgUJ5ER0TzZS:-KeuJJ8L4cqN4A5Rr_7J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b11c630600dff354b0e8132628b108884c8f4060/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L25)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

nit: typo on "accelerations"
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keu0fbd_UPOPbzQtfZN:-KeuJNmlT5iR-4b4V7s_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L31)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "Dyanmics"
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5442#-Keu0kvka2VS2x-Ild9v:-KeuJWqT5IKQgrmk0JDc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38fe8517d3f0646ee0996b934afb8c9b47baedec/drake/examples/QPInverseDynamicsForHumanoids/system/test/humanoid_plan_eval_system_test.cc#L44)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI typo "Controll"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442)*

**Comment by ggould-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5442)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Pull request merged**
