### PR TITLE
Fast downcast in release builds

### PR DESCRIPTION
**Pull request by amcastro-tri**
Extracted from #5947 per @sherm1's [request during reviw](https://reviewable.io/reviews/robotlocomotion/drake/5947#-KighsiwzRX_AYno9yAf).
PTAL the unit test for the desired functionality. 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5964)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for feature review please since `common` is your playground and I'm sure you have better ideas on how to implement this.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KipGAGGUDiiupgl6lWM:blmgvek)*

**Comment by sherm1** [comment]
+@sherm1 Platform review: I think this will be necessary at some point, but is likely to be a premature optimization especially during intense development. A few changes I think would help:
- change the name to something scary, like `dangerous_downcast` or `unsafe_downcast`
- trigger off a more-flexible compile-time option like DRAKE_ASSERT_IS_ARMED rather than NDEBUG, or provide a custom option like DRAKE_UNSAFE_DOWNCAST_IS_SAFE
- make the default for now be that dynamic cast gets used
- require a justifying comment whenever unsafe_downcast is used; everyone should favor dynamic_cast

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/fast_downcast.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KipRG2NlLI2Q-uFRfHz:-KipRG2NlLI2Q-uFRfI-:bssstvi) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L32)):*
> ```objc
> // NOLINTNEXTLINE(runtime/references): or non-const input references.
> static Derived fast_downcast(Base& from) {
>   static_assert(std::is_convertible<Derived, Base&>::value,
> ```

I believe this should be std::is_base_of(Base, Derived).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KipPe1M1-f2fWA0aAEu:be3uz6v)*

**Comment by jwnimmer-tri** [comment]
I agree with Sherm's comments in total.  I will hold off review until they are fixed.

Also, is there some profiling result in evidence that we need this?  I would prefer not to gold-plate things until we have evidence that we need to.  Please explain the motivation better before moving ahead with this PR.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KipsfsLv_5fEk5K-8hf:b2r5im6)*

**Comment by sherm1** [comment]
Not sure if this is @amcastro-tri's motivation, but I did have to do this in Simbody as a result of profiling which showed an  unreasonable amount of time spent dynamic casting AbstractValues in cache entries to their already-well-known concrete types. Cache access sped up dramatically (dynamic_cast is *very* slow compared to static_cast), with end-to-end simulation speedup ~20% IIRC. It will be very nice when we get to the point that 20% speedup matters!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KiqeRPpPGfJpM7FImMm:be430k9)*

**Comment by jwnimmer-tri** [comment]
Oh, I totally agree we will _eventually_ want this somewhere.  For `Value` at least we have `::GetValue()` which already has a seam ready for changing to `static_cast` without modifying call sites.  It seems to me like the right thing for now is to consolidate the number of places that have literal `dynamic_cast` in the new APIs coming in, so that we can later use a helper like this for speedup(s) by just changing a few places.  If we are writing dozens of `dynamic_cast`s literally, we already have problems beyond this PR's putative speed-ups.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-Kiqhvo3m-g1N0qi0oWB:bygpzdj)*

**Comment by liangfok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/fast_downcast.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-Kiqri1Ms4sKcrzsid0k:-Kiqri1NviNXqsMbaZNt:b-udmnfz) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L7)):*
> ```objc
> namespace drake {
> 
> /// Attempts to donwcast a reference of type `Base` to the requested type
> ```

BTW, typo: "downcast".

---

*[drake/common/fast_downcast.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-Kiqs525SZJepIZAZIe1:-Kiqs525SZJepIZAZIe2:b-udmnfz) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L42)):*
> ```objc
> }
> 
> /// Attempts to donwcast a pointer of type `Base` to the requested type
> ```

BTW, typo: "downcast".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/fast_downcast.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-Kiqri1Ms4sKcrzsid0k:-KjF2xwnRYO2M_RmkEYX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, typo: "downcast".
</blockquote></details>

Done.

---

*[drake/common/fast_downcast.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KipRG2NlLI2Q-uFRfHz:-KjF3CnBOBUbUZx6Vflu:b-cj46gx) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I believe this should be std::is_base_of(Base, Derived).
</blockquote></details>

Since the pointer version needs `is_convertible`, I prefer using it here as well to keep them consistent. Unless there is a much bigger reason to use `is_base_of`?

---

*[drake/common/fast_downcast.h, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-Kiqs525SZJepIZAZIe1:-KjF2yZHEzUvAePcC_yD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b933a14f4e19f98674d2296e394841aa4a66bee3/drake/common/fast_downcast.h#L42)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, typo: "downcast".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964)*

**Comment by amcastro-tri** [comment]
I addressed the reviews. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KjF3Zyf_6xPTgax6eFw:byyltd6)*

**Comment by sherm1** [comment]
Looking good -- some comments, PTAL.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[drake/common/unsafe_downcast.h, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFeMD72P_29-ftvUgz:-KjFeMD72P_29-ftvUh-:b79pw7) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L17)):*
> ```objc
> // The default is that unsafe_downcast behaves as dynamic_cast in both Release
> // and Debug builds.
> #if defined(DRAKE_UNSAFE_DOWNCAST_IS_SAFE) && \
> ```

BTW probably should have a TODO here to change the default to unsafe when we get a little further along.

---

*[drake/common/unsafe_downcast.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFfWYgUr2XiVkLQ69R:-KjFfWYhRVV6Mzhf5hCt:b-jr1srl) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L39)):*
> ```objc
> /// to profile the cost with and without dynamic casting), and the program can
> /// guarantee (through some other logic) that the `from` object is definitely of
> /// type `Derived`.
> ```

BTW please add an instruction that whenever this is used it should be accompanied by a comment explaining why the high-performance downcast is needed. Explain that users should favor `dynamic_cast` rather than `unsafe_downcast` wherever possible.

---

*[drake/common/unsafe_downcast.h, line 43 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFf9GV1JmpkqjCHQ_8:-KjFf9GV1JmpkqjCHQ_9:b-fds6dr) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L43)):*
> ```objc
> /// to type `Derived`. If the cast fails, and `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE`
> /// is not defined, it throws an exception that matches a handler of type
> /// std::bad_cast.
> ```

BTW I think the comment should read in a way that the user should expect the normal behavior to be *unsafe*. For now we may decide to leave it safe by default but eventually we'll be running it unsafe and users should always have that expectation.

The documentation should explain that DRAKE_UNSAFE_DOWNCAST_IS_SAFE can be used to suppress the default behavior and guarantee that you'll get runtime checking. People shouldn't ever have to set ..._UNSAFE though since that is the whole point of this.

---

*[drake/common/unsafe_downcast.h, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFgPbA6Vo9KVd2cJGF:-KjFgPbA6Vo9KVd2cJGG:b-9dl25r) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L49)):*
> ```objc
> ///
> /// @throws A std::bad_cast if `from` is cannot be downcasted to `Derived` when
> /// `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE` is not defined.
> ```

BTW should say it throws in Debug builds or if ..._SAFE has been defined. Don't promise anything about what it does in Release, so we can choose.

---

*[drake/common/unsafe_downcast.h, line 56 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFgrHlngu1zgVz0VdI:-KjFgrHmHSLe_UhQrTBD:b-rhclwy) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L56)):*
> ```objc
> // NOLINTNEXTLINE(runtime/references): we allow here to cast from either const
> // NOLINTNEXTLINE(runtime/references): or non-const input references.
> static Derived unsafe_downcast(Base &from) {
> ```

BTW `&` misplaced

---

*[drake/common/unsafe_downcast.h, line 57 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFgzrSik9qPhXf7mVz:-KjFgzrSik9qPhXf7mW-:b13lgph) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L57)):*
> ```objc
> // NOLINTNEXTLINE(runtime/references): or non-const input references.
> static Derived unsafe_downcast(Base &from) {
>   static_assert(std::is_convertible<Derived, Base&>::value,
> ```

I don't think `is_convertible` is right. An int is_convertible to a double, but can't be downcast this way because double is not its base class. I think you want `is_base_of`.

---

*[drake/common/unsafe_downcast.h, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFiLT6k_RxDdrnvv1q:-KjFiLT6k_RxDdrnvv1r:bgs24p0) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L74)):*
> ```objc
> /// `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE` is defined which makes it behave as a
> /// `static_cast`.
> /// It is meant to be used in places where perfomance is paramount and we wish
> ```

BTW typo

---

*[drake/common/unsafe_downcast.h, line 81 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFiN_NYSpvAXXTwun4:-KjFiN_NYSpvAXXTwun5:b-avnrnl) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L81)):*
> ```objc
> /// If the cast is successful, it returns the orignal `from` pointer downcasted
> /// to type `Derived`. If the cast fails, and `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE`
> /// is not defined, it returns `nullptr`.
> ```

BTW shouldn't duplicate all this text. Instead write it once and refer to the other implementation.

---

*[drake/common/unsafe_downcast.h, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFi617ooRUrrbOXVBE:-KjFi617ooRUrrbOXVBF:baer7w5) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L85)):*
> ```objc
> /// @param from Pointer to an object of type `Base` to be downcasted to type
> ///             `Derived` (which must be a pointer type.)
> /// @returns The `from` poiter downcasted to type `Derived`. It returns
> ```

BTW poiter->pointer

---

*[drake/common/unsafe_downcast.h, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFi9DmZ7mE9-4dmaOH:-KjFi9DmZ7mE9-4dmaOI:b-lts79a) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L87)):*
> ```objc
> /// @returns The `from` poiter downcasted to type `Derived`. It returns
> /// `nullptr` when unsuccessful and `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE` is not
> /// defined.
> ```

BTW same comments here about assuming unsafe.

---

*[drake/common/unsafe_downcast.h, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFiW8OckHrutKcH4Im:-KjFiW8OckHrutKcH4In:bckmgs4) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L92)):*
> ```objc
> /// @tparam Derived A pointer to a complete class type.
> template<class Derived, class Base>
> static Derived unsafe_downcast(Base *from) {
> ```

Couldn't this have been done using partial template specialization so that all pointer types lead here?

---

*[drake/common/unsafe_downcast.h, line 92 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFihqoLPAeP_f_9Y9b:-KjFihqoLPAeP_f_9Y9c:b-ixxugm) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L92)):*
> ```objc
> /// @tparam Derived A pointer to a complete class type.
> template<class Derived, class Base>
> static Derived unsafe_downcast(Base *from) {
> ```

BTW `*` misplaced

---

*[drake/common/unsafe_downcast.h, line 93 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFjvvh4tRdhlAPKCb4:-KjFjvvh4tRdhlAPKCb5:b-k36blq) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L93)):*
> ```objc
> template<class Derived, class Base>
> static Derived unsafe_downcast(Base *from) {
>   static_assert(std::is_convertible<Derived, Base*>::value,
> ```

Should use `is_base_of` here also. You might have to strip off the pointer but there is an `std::something<T>` that will do that for you.

---

*[drake/common/test/unsafe_downcast_test.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFizMcJwOg9SZ8tprq:-KjFizMcJwOg9SZ8tprr:bhwb5pn) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/test/unsafe_downcast_test.cc#L44)):*
> ```cpp
>   Base* base = &original;
>   // Attempts to retrieve the derived class as a pointer.
>   DerivedFromBase* derived = unsafe_downcast<DerivedFromBase *>(base);
> ```

BTW spurious space before `*` (META)

---

*[drake/common/test/unsafe_downcast_test.cc, line 65 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjF75crI6uNa9SGkTeN:-KjF75cs4pXsKuMx_1pK:bxb2knm) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/test/unsafe_downcast_test.cc#L65)):*
> ```cpp
>   Base& base = original;
>   // Attempts to retrieve the derived class as a mutable reference.
>   DerivedFromBase& derived = unsafe_downcast<DerivedFromBase &>(base);
> ```

BTW no space before `&`

---

*[drake/common/test/unsafe_downcast_test.cc, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjF7DL-w1J4MarEquzp:-KjF7DL-w1J4MarEquzq:bxb2knm) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/test/unsafe_downcast_test.cc#L76)):*
> ```cpp
>   // Attempts to retrieve the derived class as a reference.
>   const DerivedFromBase& derived =
>       unsafe_downcast<const DerivedFromBase &>(base);
> ```

BTW no space before `&`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KjFkFQvzelCtqTuQEpi:b-5o9cd2)*

**Comment by jwnimmer-tri** [comment]
I see Sherm did another round, so I'll hold off on my detailed review until those are also fixed up.

---

Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFu6-vYVEPTCujhAjf:-KjFu6-vYVEPTCujhAjg:b-4gfhp1) (no related file):*
I am not sure I buy the `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE` user toggle in this PR.  If we are bothering with (i.e., writing code for) the ability to turn on `static_cast` on at all, it must clearly because we care about performance for some casts.  I see no reason to commit the code but leave it disabled.  If it could remain disabled, we could instead write `dynamic_cast` and be no worse off.  At worst, a `TODO(...) Profile this; is the cast too much?` would be needed.

If this function does either dynamic or static depending on a configuration, I think it should just track DRAKE_ASSERT being armed, without any opportunity to diverge.  Whether or not assertions (internal consistentcy self-checks) are armed seems exactly like whether casts thought to be always-valid undergo consistency self-checks.

---

*[drake/common/unsafe_downcast.h, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFfWYgUr2XiVkLQ69R:-KjFvZtM6Ya9NBJyPTSs:b-gkyqcw) ([raw file](https://github.com/robotlocomotion/drake/blob/d44c1226258e11b8447daa9625ed7f0f98dd5e3e/drake/common/unsafe_downcast.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please add an instruction that whenever this is used it should be accompanied by a comment explaining why the high-performance downcast is needed. Explain that users should favor `dynamic_cast` rather than `unsafe_downcast` wherever possible.
</blockquote></details>

+1 on this.

I would also be curious to get a citation (hyperlink) for an example of using this function.  Because its use should be discouraged, we should not PR this function until such a time as we have a need for it.  Can you link a to the most convincing example code where this function would be used?  I assume there is something under development that induced this need, including some simple profiling results to back it up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-:-KjFu5b7QXYLdW2vDxYY:b-o3a9mg)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5964#-KjFu6-vYVEPTCujhAjf:-KjGHiVnESg8W8E9CeAd:b-ckhe40) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not sure I buy the `DRAKE_UNSAFE_DOWNCAST_IS_UNSAFE` user toggle in this PR.  If we are bothering with (i.e., writing code for) the ability to turn on `static_cast` on at all, it must clearly because we care about performance for some casts.  I see no reason to commit the code but leave it disabled.  If it could remain disabled, we could instead write `dynamic_cast` and be no worse off.  At worst, a `TODO(...) Profile this; is the cast too much?` would be needed.

If this function does either dynamic or static depending on a configuration, I think it should just track DRAKE_ASSERT being armed, without any opportunity to diverge.  Whether or not assertions (internal consistentcy self-checks) are armed seems exactly like whether casts thought to be always-valid undergo consistency self-checks.
</blockquote></details>

I like the idea of sponging off the existing DRAKE_ASSERT_IS_ARMED -- I agree that it would be likely that a person desperately trying to find a Release-only bug by enabling dynamic_cast would also want to enable asserts.   

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5964)*

**Comment by amcastro-tri** [comment]
We arrived to the conclusion that probably this is too much of a distraction for the development of MBT. I will therefore use `dynamic_cast` where needed and I will profile its cost in the future when MBT has more functionality in it.

**Comment by sherm1** [comment]
@edrumwri independently brought this up ...

**Comment by edrumwri** [comment]
Yes, I suggested to @sherm1 that:
* private (and possibly protected) functions could benefit from a DRAKE_ASSERT(dynamic_cast(x)) followed by y = static_cast(x); ensuring safety would require coverage for these private/protected functions in unit tests.
* public functions should use dynamic_cast

**Comment by sherm1** [comment]
That would quickly hit rule-of-3, so should be done with `unsafe_downcast` rather than with ad hoc code. The question is whether we ought to defer that until we can make performance measurements rather than risk unnecessary use of this "optimization" resulting in less bugcatching during development?

**Comment by edrumwri** [comment]
Agreed on the rule-of-three. The salient question: can anyone think of a way to break a proposed safe implementation of my strategy (unsafe_downcast in private/protected code + guaranteed test coverage)?

**Comment by jwnimmer-tri** [comment]
@edrumwri The access visibility really has little to do with whether the data manipulated at runtime is or is not of the correct subtype.  In other words: I don't understand what you're saying at all.

**Comment by edrumwri** [comment]
Ok, expanded form:

If I create a method in drake that is publicly accessible and takes a parameter that is a pointer of type X that should be of subtype Y, I must assume that the user could pass in a subtype Z s.t. Z != Y. Therefore, I should use dynamic_cast for safety.

OTOH, if I create a method that is privately accessible and takes a parameter that is a pointer of type X that should be of subtype Y, I test it for proper type using dynamic_cast in debug mode, and I have unit tests that  verify that the method works as advertised in debug mode, I could instead use static_cast in release mode.

**Comment by jwnimmer-tri** [comment]
That would depend on where the `X x` passed into the private method came from.  I think you are implying that whoever is calling the private method would / should have already confirmed that `x` is of type `Y`, but that was unstated.  Having private access makes it _easier_ to reason about what could get passed in, but we still have to audit (or possibly robustly test) the callers of the private method to ensure the type is always validated before calling the private method.

So another way or stating your ideas is "non-private methods _must never_ use `static_cast`" in any build variant, because its impossible to reason about what subtype is being passed in.  That could be a valid premise, but isn't really different from any other choice of DRAKE_ASSERT vs DRAKE_DEMAND -- how confident are we in presuming the invariant so that we can remove the check in release builds.  While the access modifier is part of that discussion, its not the only part.

But finally, I think its worth backing up and asking: if you have a private method that takes `X x` but always needs a subtype `Y` -- why not just declare it as taking `Y y` and let the compiler guarantee that callers have done the right thing?  It's a private method, so you should be able to choose any signature you wish.

**Comment by sherm1** [comment]
> if you have a private method that takes X x but always needs a subtype Y -- why not just declare it as taking Y y?

:smile: what?? -- that's so reasonable!

**Comment by edrumwri** [comment]
Jeremy, I agree with your points. I'd only retain my recommendation if it can be enforced in CI that methods that use a forced downcast method are validated. 

The private method in question in question is, in actuality, a protected method that was made private.

**Comment by jwnimmer-tri** [comment]
(Not really on topic anymore, but FYI reducing visibility in subclasses is an anti-pattern and should be a defect.)

**Comment by sherm1** [comment]
(Continuing off topic)
> reducing visibility in subclasses is an anti-pattern

I agree for public->private reduction, but protected->private makes sense to me for NVI virtuals since (a) it allows appropriately directed Doxygen on the protected virtual declaration, (b) it expresses that the override or (better) final is not to be invoked directly, and (c) unrelated classes can't call the base class method anyway so can't make it appear by upcasting the derived class. Do you think it is still a defect in that case?

**Comment by edrumwri** [comment]
Would someone explain how either case is a defect?


--------------------------------
Evan Drumwright
Senior Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Pull request closed without merging**
