### PR TITLE
Use DeclareNumericParameter helper everywhere in automotive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5691)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.

I think `single_lane_ego_and_agent` is okay to be removed now, but let me know if you disagree, and I can put it back and update it instead.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-:-KgbJGe15pRX5oljlHHS:be213mi)*

**Comment by jadecastro** [comment]
Yes I agree with removing it now.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car_params.named_vector, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-KgcPedpGICN5BnQWyQS:-KgcPedpGICN5BnQWyQT:be1hpc4) ([raw file](https://github.com/robotlocomotion/drake/blob/23f08526ace258e4eabb0a9d2ea56f8bcd870c22/drake/automotive/simple_car_params.named_vector#L26)):*
> ```
> element {
>     name: "max_velocity"
>     doc: "The limit on the car's forward speed, in meters per second."
> ```

BTW remove `in meters per second`.

---

*[drake/automotive/simple_car_params.named_vector, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-KgcNG8JnR-m_xFYCqHx:-KgcNG8KufvMDPB21KEj:bmmsryn) ([raw file](https://github.com/robotlocomotion/drake/blob/23f08526ace258e4eabb0a9d2ea56f8bcd870c22/drake/automotive/simple_car_params.named_vector#L27)):*
> ```
>     name: "max_velocity"
>     doc: "The limit on the car's forward speed, in meters per second."
>     doc_units: "m"
> ```

BTW `m/s`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-:-KgcLfAvRA4sJ9J4-BZZ:b-o94ujl)*

**Comment by jwnimmer-tri** [comment]
Review status: 19 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car_params.named_vector, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-KgcPedpGICN5BnQWyQS:-KgdEayGCnP82KEZ-S-k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23f08526ace258e4eabb0a9d2ea56f8bcd870c22/drake/automotive/simple_car_params.named_vector#L26)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW remove `in meters per second`.
</blockquote></details>

Done.

---

*[drake/automotive/simple_car_params.named_vector, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-KgcNG8JnR-m_xFYCqHx:-KgdEbGL0d4YeWil7dTq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/23f08526ace258e4eabb0a9d2ea56f8bcd870c22/drake/automotive/simple_car_params.named_vector#L27)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW `m/s`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691)*

**Comment by jadecastro** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-:-KgdSv3QgrcsqZWJDRXf:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@soonho-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-:-KgfSH_RuaIuc2X2TwMO:bxw8cpy)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 19 of 22 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5691#-:-Kggeo4SeGa2vX5-bAzt:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car:

**Pull request merged**
