### PR TITLE
[bindings] Only log to Python sink for main thread

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Implements workaround (3) mentioned in #19680

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19683)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
@jwnimmer-tri What do you think about this approach?
It would probably keep "90%" of pydrake code looking the same, and only deviate when there are threads involved.
I could also make this optional.

Alternatively, I can implement the environment variable approach if you think that's simplest.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19683#-:-NYtupmU9EMZMgvrXfEk:b-vfi3rs)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
I'm not sure why this is better than just turning off the Python redirection as a whole.  Could you clarify the pro/con as you see it?

On the 'con' side: Log messages will no longer be uniformly formatted within the process, and changes to the Python logging level will affect more than just the Python sink.  I also have the general impression that `thread_local` is a pretty expensive language construct, so I would want to benchmark this (myself) if you think this a worthwhile direction, as a sanity check.

**Comment by EricCousineau-TRI** [comment]
For this approach:
The pro would be that logging from the main thread (probably most use cases) would still function normally, such as in Jupyter notebooks, and something we could potentially turn "always on" in certain places like Anzu.
The cons would be as you mentioned - inconsistency and possibly performance.

For disabling everything:
The pro is simplicity.
The con is if you're say launching controllers from a Jupyter notebook (which IMO not sure if it's the best idea), then all of the logging will go to terminal stderr vs. the redirected stderr.

Given the above, though, I'm fine with going the route of disabling everything.

**Comment by jwnimmer-tri** [comment]
In the case where using Python `logging` is important (because stderr text gets discarded, or because it's hooked up to a network logger, or etc.), I think the better answer is to use our current default and eat the GIL slowdown.  (Possibly the user would set the log threshold to WARN in this case, no INFO.)  Log messages from worker threads are not any less important than log message from the main thread, so if there is an important use case for having the main thread stay on Python `logging`, it applies equally well for worker threads.  That argues against any per-thread policy variation.

**Comment by EricCousineau-TRI** [comment]
Aye, sgtm. Closing!

**Pull request closed without merging**
