### PR TITLE
workspace: Update pybind11 fork to latest commit (Python 3.8)

### LINKED ISSUE #13026: pybind: Mitigate change of internal GC structure in 3.8
EDIT: Whoops! Looks like it was already changed here:
https://github.com/python/cpython/commit/5ac9e6eee5ed18172d70d28cf438df0be4e3b83d

So yeah, now I have to spend time mitigating :(

---
# Old Issue
Title: "pybind: Should ask CPython API maintainers to make resurrection for 2+ times be public API"

Per convo with @jamiesnape, seems like Python 3.8 and 3.9 may start having some breakages, not sure if it will be some heavy CPython API breakages.

I should make sure I make this request sooner than later (would have been better to have made it ~2  years ago):
https://github.com/RobotLocomotion/pybind11/blob/cac3edd971c70469aa710c13d59f9c29c7f4651f/include/pybind11/pytypes.h#L1465-L1475

\cc @ToffeeAlbina-TRI

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #13026

Requires:
- [x] Merge of https://github.com/RobotLocomotion/pybind11/pull/39
- [x] Merge of #13035

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13027)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@jamiesnape If I ask for Mac CI on this PR, will I get actual testing of Python 3.8 and be able to hone in on those errors?
Or will it still choke on other packages, or other issues? (It's hard to tell from current CI results, as some of the `pydrake` errors seem kinda unrelated?)

**Comment by EricCousineau-TRI** [comment]
FTR Local testing of Drake changes, but using Ubuntu:

```bash
set -euxo pipefail

cd $(mktemp -d)

# Assumes you have access to fhs-extend from here:
# https://gist.github.com/EricCousineau-TRI/6870970d68f75d23061177a52932a5d1#file-bash_helper_functions-sh

# Build and install Python 3.8
install_prefix=~/.local/opt/cpython/3.8.2
jobs=4

(
  git clone https://github.com/python/cpython -b v3.8.2
  cd cpython
  ./configure --enable-shared \
        --prefix=${install_prefix} \
        LDFLAGS=-Wl,-rpath=${install_prefix}/lib \
        --with-ensurepip=upgrade
    make -j ${jobs} install
)

fhs-extend ${install_prefix}

# Install pybind stuff
pip3 install gnureadline==8.0.0 pytest==5.4.1 numpy==1.18.2

# Test pybind locally
(
  git clone https://github.com/RobotLocomotion/pybind11
  cd pybind11
  git fetch origin pull/39/head && git checkout FETCH_HEAD
  mkdir build && cd build
  cmake .. -DPYTHON_EXECUTABLE=$(which python3) -DDOWNLOAD_CATCH=1
  make -j ${jobs} cpptest pytest
)

# Test Drake
(
  git clone https://github.com/EricCousineau-TRI/drake -b feature-pybind-pr39-wip
  cd drake
  bazel test -j ${jobs} //bindings/pydrake/... //tutorials/... -k
  # Only failure should be sphinx, some weird StopIteration stuff
)
```

**Comment by jamiesnape** [comment]
> @jamiesnape If I ask for Mac CI on this PR, will I get actual testing of Python 3.8 and be able to hone in on those errors?

No, you need my draft PR #13031.

**Comment by jamiesnape** [comment]
> Or will it still choke on other packages, or other issues? (It's hard to tell from current CI results, as some of the pydrake errors seem kinda unrelated?)

Hard to say given this issue chokes part of the build early on locally, but I would expect this at least fix the build. Test we can worry about separately, if necessary.

**Comment by jamiesnape** [comment]
I can LGTM the pure python fixes separately if it makes life easier.

**Comment by EricCousineau-TRI** [comment]
@jamiesnape Should we merge our PRs (in either direction)?

**Comment by jamiesnape** [comment]
> @jamiesnape Should we merge our PRs (in either direction)?

Probably is not a great deal of harm getting the SHA bump into `master` first and alone, but I can at least cherry pick this if you want to wait to see if this is the definitive fix.

**Comment by EricCousineau-TRI** [comment]
Aye, in that case, Mac unprovisioned testing would not work. Should we just merge this, then?

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
> Aye, in that case, Mac unprovisioned testing would not work. Should we just merge this, then?

That is my preference, but it is Jeremy's call.

**Comment by jwnimmer-tri** [comment]
I guess we should just merge this without waiting, to keep making progress.  (Needs a rebase though.)

But to be clear, I suggested we try **non**-unprovisioned testing, e.g., to see if this still passes with 3.7

**Comment by EricCousineau-TRI** [comment]
Ah, my bad! Skipped over the "non" part!

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Since we are waiting, I would say wait until Monday to merge now, so I can finish testing the other PR.

It's a little late in the day now, but sometimes I would say it is fine to be 95% sure a change is going to fine on Mac and catch issues after continuous. It's one reason why we have build cops. That merge would need to be done by early afternoon, though.

**Comment by EricCousineau-TRI** [comment]
Sounds good to me. I will leave it up to you to merge this one.

**Comment by EricCousineau-TRI** [comment]
For self-record
Hacking with self-compiled versions of Python: https://github.com/EricCousineau-TRI/drake/commit/feature-pybind-pr39-wip-squash (commit: f74f1fb2ac)

**Pull request merged**
