### PR TITLE
Use *-config.cmake and *-config-version.cmake naming convention

### PR DESCRIPTION
**Pull request by jamiesnape**
Mitigates some case-sensitivity issues.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6402)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6402#-:-KnFFWJXfjz9dHfcGOkF:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by ggould-tri** [comment]
Death to capital letters!  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6402#-:-KnFLuiYleCX8zPUhKH_:b653kjw)*

**Pull request merged**
