### PR TITLE
[meshcat] Add option to disable SetTransform during recording

### PR DESCRIPTION
**Pull request by RussTedrake**
Related to #16265

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@xuchenhan-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271#-:-MrSHdCQC1WL6GWWlm9z:b-bpi9p7)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with one typo and one thought.

+@sherm1 for platform review per rotation please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271#-:-MrSvFAFCpb-yRFVBD_W:b-a3jtbn)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16271#-MrSuV1sAQuu80WZKCXl:-MrSuV1tEyOIRNZ6OrtJ:b7riywh) (no related file):*
Should the mass spring cloth example be modified to use this mechanism, or at least provide this as an option?

The long term solution though, should still be that SceneGraph owns deformable meshes and MeshCat visualizes them as suggested in #16265.

---
___
*[geometry/meshcat_visualizer.h, line 83 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16271#-MrSrEcd70T_1ZqWyyAc:-MrSrEcd70T_1ZqWyyAd:b30ju3e) ([raw file](https://github.com/robotlocomotion/drake/blob/cacb3eafcfde6f0354a3972221afbdbb55d76954/geometry/meshcat_visualizer.h#L83)):*
> ```objc
>   @param set_transforms_while_recording if true, then each Publish will set the
>   transform in Meshcat *and* record the transform in the animation.  Set to
>   false to avoid updating the visualization during recordiing.  Note that
> ```

nit s/recordiing/recording.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16271#-MrSuV1sAQuu80WZKCXl:-MrTDeol4_AgetoTX8Sr:b-w0avpg) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should the mass spring cloth example be modified to use this mechanism, or at least provide this as an option?

The long term solution though, should still be that SceneGraph owns deformable meshes and MeshCat visualizes them as suggested in #16265.
</blockquote></details>

I agree with your long term solution, and defer to your preference for if you want to use this in the mean time for your mass spring cloth example. I  do think it provides a much more satisfying experience, especially for firefox users.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16271#-:-MrTZ0YH4uhJ13FweEsL:b8qx53o)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri (waiting on @RussTedrake)

**Pull request merged**
