### PR TITLE
Symbolic variable check in mathematical program

### PR DESCRIPTION
**Pull request by hongkai-dai**
Check if the symbolic variables extracted from a symbolic expression, are actually decision variables in the optimization problem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4927)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbS8tJPCc-WcujvE7dt:bboswjz)*

**Comment by hongkai-dai** [comment]
Also move the test from `decision_variable_test.cc` to `mathematical_program_test.cc`, and refactored the tests.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbSEXhsjg8hS0Vanyad:bfaj69d)*

**Comment by soonho-tri** [comment]
checkpoint.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 2156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbSycxfDdqKvOQ4Gy0I:-KbSycxfDdqKvOQ4Gy0J:bl7u54s) ([raw file](https://github.com/robotlocomotion/drake/blob/5c74aad83928b80cb277363d2242259839c77988/drake/solvers/mathematical_program.h#L2156)):*
> ```objc
>    * variable using its index. This index is used when adding constraints
>    * and costs for each solver.
>    * @pre{ @p var is a decision variable in the mathematical program, otherwise
> ```

nitpick: please remove a whitespace in `@pre{ @p`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbSzzv80GTROsbjiKRU:b6o68ox)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.h, line 2156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbSycxfDdqKvOQ4Gy0I:-KbTi99aZJVkwaJn3_aR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5c74aad83928b80cb277363d2242259839c77988/drake/solvers/mathematical_program.h#L2156)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nitpick: please remove a whitespace in `@pre{ @p`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by hongkai-dai** [comment]
resolves #4873 

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbTidGVPS_bhyXp7aF8:bt5tgy9)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbViUr9rXlx1oOQyl_4:-KbViUr9rXlx1oOQyl_5:b-2jnzby) ([raw file](https://github.com/robotlocomotion/drake/blob/56dc687098e02b863e2db67e85f631212c1dd462/drake/solvers/test/mathematical_program_test.cc#L228)):*
> ```cpp
>                 "GetSolution does not return the right type of matrix");
>   EXPECT_TRUE(CompareMatrices(val, val_expected));
>   for (int i = 0; i < vars.rows(); ++i) {
> ```

What's the difference between the above `EXPECT_TRUE(CompareMatrices(val, val_expected))` and the check in the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by soonho-tri** [comment]
:lgtm: (aside one question)

---

Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbVieJoLLVkIEfswgq_:b-xk2i54)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mathematical_program_test.cc, line 228 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbViUr9rXlx1oOQyl_4:-KbVjv6gljpGhRUYIvBC:b72i8a3) ([raw file](https://github.com/robotlocomotion/drake/blob/56dc687098e02b863e2db67e85f631212c1dd462/drake/solvers/test/mathematical_program_test.cc#L228)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

What's the difference between the above `EXPECT_TRUE(CompareMatrices(val, val_expected))` and the check in the loop?
</blockquote></details>

We overloaded the function `MathematicalProgram::GetSolution()`. The `EXPECT_TRUE(CompareMatrices(val, val_expected)` checks getting solution for a matrix of symbolic variables.
```
GetSolution(Eigen::Matrix<symbolic::Variable>)
```
Inside the for loop, it checks the function with a single variable
```
GetSolution(symbolic::Variable)
```
I added a line of comment to explain this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by hongkai-dai** [comment]
+@ggould-tri for platform review.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbVkstbXHETJ5HuTWw4:b-8qo47q)*

**Comment by ggould-tri** [comment]
A couple of minor items below; otherwise :lgtm:.

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 2157 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbVnmjQK4YYY6ktt4Kg:-KbVnmjQK4YYY6ktt4Kh:bpegocf) ([raw file](https://github.com/robotlocomotion/drake/blob/4b0d7e2e7ca559b0303a3f6864c62a66f5c65581/drake/solvers/mathematical_program.h#L2157)):*
> ```objc
>    * and costs for each solver.
>    * @pre{@p var is a decision variable in the mathematical program, otherwise
>    * this functions throws an error.}
> ```

FYI -- Typo "functions throws".  Also "throw" will lead some readers to expect an exception; consider instead "asserts", "terminates", or "aborts".

---

*[drake/solvers/test/mathematical_program_test.cc, line 112 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbVp43DiTFSPgZ5G9Aq:-KbVp43DiTFSPgZ5G9Ar:b-7p611d) ([raw file](https://github.com/robotlocomotion/drake/blob/4b0d7e2e7ca559b0303a3f6864c62a66f5c65581/drake/solvers/test/mathematical_program_test.cc#L112)):*
> ```cpp
>     }
>   }
> }
> ```

FYI -- inconsistent vertical whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbVpLorfYIiHVq9hKZI:bt5ooe0)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 2157 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbVnmjQK4YYY6ktt4Kg:-KbVw5p3yAq-iJA1pkQQ:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/4b0d7e2e7ca559b0303a3f6864c62a66f5c65581/drake/solvers/mathematical_program.h#L2157)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- Typo "functions throws".  Also "throw" will lead some readers to expect an exception; consider instead "asserts", "terminates", or "aborts".
</blockquote></details>

Done. Good catch.

---

*[drake/solvers/test/mathematical_program_test.cc, line 112 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-KbVp43DiTFSPgZ5G9Aq:-KbVwGHi8jpV3T1Y_Z-a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4b0d7e2e7ca559b0303a3f6864c62a66f5c65581/drake/solvers/test/mathematical_program_test.cc#L112)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- inconsistent vertical whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbW032poJZO-wmQP_kW:b-4alp76)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-gcc-experimental-open-source please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbW1Y0rmKRf226ZUkpr:bux8x8g)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source-debug please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbW2W_xRIkHhU0qxDj8:b-4cyje8)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4927#-:-KbW6pr3KGF64oZog8wC:b92f7d)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-cpplint-experimental please

**Pull request merged**
