### PR TITLE
Do not install pybind11 headers

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7805)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7805#-:-L3FLgxoqbFR25CXPUBO:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 for platform review.

**Comment by sherm1** [comment]
@jamiesnape can you provide background for this or a pointer to the motivating discussion? Not clear to this ignorant platform reviewer why you are removing these headers.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7805#-:-L3FQEEO7REwom-kbASI:boc1ypt)*

**Comment by jamiesnape** [comment]
There is no need for them to be installed because they are not used in drake public headers, and since they only exist to produce python bindings they will never be used in drake public headers. Moreover, since they are never linked into drake libraries other than python modules we do not need to worry about a downstream project needing exactly the same version of the headers. In other words, they are redundant and should not have been installed in the first place,

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7805#-:-L3FeAw9l4yFhVNSjPgB:bsi7h8z)*

**Comment by sherm1** [comment]
Great, thanks Jamie! :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7805#-:-L3G2l6xtrrrSx0yv8Tq:btn7oiq)*

**Comment by clalancette** [comment]
Unfortunately, the removal of these headers broke downstream delphyne.  The problem is that delphyne was relying on the installation of the pybind11 headers from drake, since there is no pybind11 package in Ubuntu Xenial (it looks like it was added to Ubuntu in artful).  While we could get the headers other ways, it is way more convenient to get it either from a package (which doesn't exist) or from drake itself.  What do you think about reverting this?  @basicNew , FYI.

**Comment by jamiesnape** [comment]
I think it would be better to add an `ExternalProject_Add` call or similar to your project.

**Comment by jwnimmer-tri** [comment]
When he and I spoke months ago, I agreed with Daniel that using CMake for `delphyne-gui` made sense, given the ecosystem it had to interoperate with (`python-qt` was the important factor, as I hazily recall), and that it could be shipped as a prebuilt binary like we do with `drake-visualizer`, unlikely to change the rendering protocol very often.  However, I personally do not agree with using CMake for `delphyne`, especially given (unlike the GUI) the tight coupling it will have with the codebases that use it that don't speak CMake.

@clalancette Could I convince y'all to use Bazel for `delphyne`?  If you ever expect to integrate it with Driving, you are going to need to do that anyway IMO.  Then you would have access to all of Drake's `WORKSPACE`, as well as be primed to integrate with Driving's build system.

Failing that, I agree with Jamie that you should just do `ExternalProject_Add`.  If there are runtime reasons why Drake needs to ship compiled versions of its dependencies (e.g., load-time compatibility) then we should consider it, but failing that, Drake shouldn't responsible for shipping compiled dependencies to the world that it happens to use at the moment.

**Comment by clalancette** [comment]
> When he and I spoke months ago, I agreed with Daniel that using CMake for delphyne-gui made sense, given the ecosystem it had to interoperate with (python-qt was the important factor, as I hazily recall), and that it could be shipped as a prebuilt binary like we do with drake-visualizer, unlikely to change the rendering protocol very often. However, I personally do not agree with using CMake for delphyne, especially given (unlike the GUI) the tight coupling it will have with the codebases that use it that don't speak CMake.

There were a couple of reasons we ended up switching to CMake, the largest being that https://github.com/RobotLocomotion/drake/issues/7259 was not resolved at the time, and thus we had no good way to pull drake into the delphyne WORKSPACE.  I see a lot of PRs have been merged for that; is it done now?

> 
> @clalancette Could I convince y'all to use Bazel for delphyne? If you ever expect to integrate it with Driving, you are going to need to do that anyway IMO. Then you would have access to all of Drake's WORKSPACE, as well as be primed to integrate with Driving's build system.

While I agree with you at some level, this is where some other factors come into play.  The first factor is that the switch from bazel to CMake was pretty disruptive, even in a project as small as `delphyne` and `delphyne-gui`.  I don't relish the idea of doing it back the other way, with a now larger project.  The second factor is that all of the ignition libraries that delphyne depends upon use CMake.  Thus, we can just use that ecosystem as-is, without re-implementing a lot of their build systems in Bazel.  The third factor is that we were spending huge amounts of time getting Bazel to do what we wanted.  Some of this is related to the previous point, some of this is related to the fact that we (still) aren't really that familiar with Bazel.  Because of all of that, I think we'd have to have a really compelling reason to switch back to Bazel right now.  All of that being said, we should probably have another discussion with @stonier .

> 
> Failing that, I agree with Jamie that you should just do ExternalProject_Add. If there are runtime reasons why Drake needs to ship compiled versions of its dependencies (e.g., load-time compatibility) then we should consider it, but failing that, Drake shouldn't responsible for shipping compiled dependencies to the world that it happens to use at the moment.

Thanks for the ideas.  For now, I'll take a look at using an `ExternalProject_Add` for delphyne.

**Comment by jwnimmer-tri** [comment]
> There were a couple of reasons we ended up switching to CMake, the largest being that #7259 was not resolved at the time, and thus we had no good way to pull drake into the delphyne WORKSPACE. I see a lot of PRs have been merged for that; is it done now?

Mostly yes.  If you use the most generic entry point ...
```python
# In WORKSPACE ...
load("@drake//tools/workspace:default.bzl", "add_default_repositories")
add_default_repositories()
```
... then its done.

If you want to cherry-pick only specific externals then yes that's available now, but we are still deciding the final names for everything so there might still be some minimal churn for a little while, though it should be only 1- or 2-line rote patches to track along with it.

> Thus, we can just use that ecosystem as-is, without re-implementing a lot of their build systems in Bazel.

You could use precompiled libraries (`*.deb`) of the ignition stuff, though?  In Drake we are trying to stay Ubuntu & homebrew centric, but I don't think that constraint applies to Delphyne.
 
> For now, I'll take a look at using an ExternalProject_Add for delphyne.

That sounds like the right answer for today.

**Pull request merged**
