### PR TITLE
pydrake_pybind: Docs for conventions on binding overloads

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8301)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8301#-:-L75cO9KR0eJRTcGLxyV:b-t5m2ic)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: 

It would be cool if there were links in the docs pointing to examples in the drake code. However, that's dangerous if the code changes and this documentation doesn't. So, I leave it up to you.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/pydrake_pybind.h, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8301#-L77-txLWYBRIedIDOyv:-L77-txLWYBRIedIDOyw:b-8kvd6m) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe3050dc8473130204035c96064b25f41e1235b/bindings/pydrake/pydrake_pybind.h#L99)):*
> ```objc
> (using perfect forwarding when appropriate). This is more verbose, but gets the
> job done. For methods, ensure that you include the `self` argument.
> - If, for whatever reason, you wish to avoid lambads, then use the
> ```

BTW typo "lambads"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8301#-:-L770BbSZS1VLxkQgulB:b-rq0gdl)*

**Comment by EricCousineau-TRI** [comment]
Yeah, I'd prefer not to add explicit examples. I think just providing the symbols, so that people could search for them should be sufficient.

+@jwnimmer-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7QvgcC74XA9zVsbTv4:bixmcht)*

**Comment by SeanCurtis-TRI** [comment]
I want to make sure we're talking the same language: When you say "explicit examples", you mean even shying away from links to its use in drake (I'm certainly on board with excluding code snippets)? My primary concern was the *vagueness* in which the fallbacks would be used. That said, I'm still good as is.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7Qw4oT--hxOT_bgEih:b-pr4ee4)*

**Comment by EricCousineau-TRI** [comment]
Yup; I could provide an example, but the `pybind11` doc already has example usages for overloading.

W.r.t vagueness, it's vague because TBH I don't have an exact guide for when `py::overload_cast` is ambiguous to the compiler vs. `overload_cast_explicit` vs. explicit lambda / `static_cast`'ing, and I'd prefer not to mislead anyone.

I'd prefer not to spend time on routing out the exact situations until there's a clear need for it and I (or someone else) have more time to sit down and do it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7Qxfna5I2HSLLPSQxl:b1i3s0s)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/pydrake_pybind.h, line 99 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-L77-txLWYBRIedIDOyv:-L7QyMxp8ekv8u9eUX_z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fbe3050dc8473130204035c96064b25f41e1235b/bindings/pydrake/pydrake_pybind.h#L99)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW typo "lambads"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301)*

**Comment by SeanCurtis-TRI** [comment]
:SGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7RIG4b4d4U3bGjLyA1:bn1d5qw)*

**Comment by jwnimmer-tri** [comment]
:lgtm: on the text being properly formatted and readable.

I can think of reasons why I'd prefer `static_cast` (e.g., fails-fast instead of adding more copying as APIs evolve) but I'll assume feature vs author already covered that, and leave well-enough alone.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7RHu-QABvsHqw_RaJb:b-oz1bvn)*

**Comment by EricCousineau-TRI** [comment]
> (e.g., fails-fast instead of adding more copying as APIs evolve)

Just so I understand, can I ask what's being copied in the case of `overload_cast_explicit`?

It doesn't save that much real-estate, just the class name; however, I find it much easier to understand the intent of its usage with less-compact mixing of parentheses and pointers, even though it does make failure sometime a little harder to understand.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8301#-:-L7S2qct2vt9N6BNpSFN:b-28qnx3)*

**Comment by jwnimmer-tri** [comment]
> Just so I understand, can I ask what's being copied in the case of overload_cast_explicit?

I meant that lambdas' arguments don't necessarily need to match the called function's arguments -- they just need to be convertable (which might involve copying), so that would be a fair reason to prefer `static_cast` over `lambda`, if I'm understanding correctly.  I agree that the two built-in `overload{,_explicit}_cast` methods are the best choice when they work.

**Comment by EricCousineau-TRI** [comment]
Ah, gotcha. Made that change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8301#-:-L7SCtW2mf_yluPNuVZI:b-jrpvg2)*

**Comment by jwnimmer-tri** [comment]
LGTM still.

Looking back, I can see how my post was confusing, sorry!  I think what I was really after was having the rationale documented in the PR or commit text.  I think we're at that point now, given the discussions here so far.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8301#-:-L7SDgk8Qcc3sslDz_kW:b-c584gg)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8301)*

**Pull request merged**
