### PR TITLE
adds additional autodiff features related to the discussion in #8175

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8202)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for feature review, please.  (please pass to sean if/when you're happy)

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6R4sX3evcX8-MuVd89:b-khfxo7)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/autodiff_gradient.h, line 146 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RT-DQ7_4IKU2uYetd:-L6RT-DQ7_4IKU2uYete:bk2kmvc) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L146)):*
> ```objc
>  *   `B = A.cast<double>()`
>  * should (and does) fail to compile.  Use `CastToValueOrThrow(A)` if you want
>  * to
> ```

BTW Weird line break.

---

*[math/autodiff_gradient.h, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RVI8n-7Qgu6MIkVfP:-L6RVI8n-7Qgu6MIkVfQ:b-fduy4s) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L154)):*
> ```objc
>  *
>  * @throws std::runtime_error if the gradients were not empty nor zero as
>  * evaluated by Eigen's isZero(prec).
> ```

BTW typo `precision`, if you intended to refer to our function's argument.

---

*[math/autodiff_gradient.h, line 164 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RTwp13qg4iAZ_M4iX:-L6RTwp13qg4iAZ_M4iY:b-3yznph) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L164)):*
> ```objc
>                   Derived::ColsAtCompileTime, 0, Derived::MaxRowsAtCompileTime,
>                   Derived::MaxColsAtCompileTime>>::type
> CastToValueOrThrow(
> ```

I wonder if `CastToValueOrThrow` is going to make sense at call sites?  Most arguments to functions are already "values" of some sort, so I don't think this name conveys its purpose very well.  If I'm understanding this correctly, this is the same as `DiscardGradient` but with tolerancing.  Would `DiscardEmptyGradientOrThrow` be a clearer name, for example?

---

*[math/autodiff_gradient.h, line 167 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RUzri5WP8KKU8rvYw:-L6RUzri5WP8KKU8rvYx:bb4yvfw) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L167)):*
> ```objc
>     const Eigen::MatrixBase<Derived>& auto_diff_matrix,
>     const typename Eigen::NumTraits<
>         typename Derived::Scalar::Scalar>::Real& precision =
> ```

BTW `Real` is for the real part of a real+imag pair; in the past, uses of `Real` in drake were confusion / mistakes, since we don't usually have complex numbers.  I think just `const typename Derived::Scalar::Scalar& precision = ...` is what we want here?

Ditto below for the analogous Transform function.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI up to you if you want to read this now or wait until the next push.

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[math/autodiff_gradient.h, line 146 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RT-DQ7_4IKU2uYetd:-L6RbGIB83l9Jopc8Q33:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Weird line break.
</blockquote></details>

Done.

---

*[math/autodiff_gradient.h, line 154 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RVI8n-7Qgu6MIkVfP:-L6RbENH-oO5ttKNBkZ3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L154)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW typo `precision`, if you intended to refer to our function's argument.
</blockquote></details>

Done.

---

*[math/autodiff_gradient.h, line 164 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RTwp13qg4iAZ_M4iX:-L6RaakI1hxG8-KgPfFV:bfbhgjm) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L164)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I wonder if `CastToValueOrThrow` is going to make sense at call sites?  Most arguments to functions are already "values" of some sort, so I don't think this name conveys its purpose very well.  If I'm understanding this correctly, this is the same as `DiscardGradient` but with tolerancing.  Would `DiscardEmptyGradientOrThrow` be a clearer name, for example?
</blockquote></details>

I don't love the name and am happy to change.  DiscardEmptyGradient isn't quite right either, since it's really DiscardEmptyOrZeroGradientOrThrow.  But yikes.

---

*[math/autodiff_gradient.h, line 167 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202#-L6RUzri5WP8KKU8rvYw:-L6RaShY6dEstDRUeUH-:bm2p4iy) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L167)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `Real` is for the real part of a real+imag pair; in the past, uses of `Real` in drake were confusion / mistakes, since we don't usually have complex numbers.  I think just `const typename Derived::Scalar::Scalar& precision = ...` is what we want here?

Ditto below for the analogous Transform function.
</blockquote></details>

RealScalar is the argument that is being expected by isZero.  I agree we aren't passing in anything complex right now, but I feel that this is more correct for future applications?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8202)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/autodiff_gradient.h, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-L6RTwp13qg4iAZ_M4iX:-L6RfPTT3hP75wMSu37w:brmo85g) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L164)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't love the name and am happy to change.  DiscardEmptyGradient isn't quite right either, since it's really DiscardEmptyOrZeroGradientOrThrow.  But yikes.
</blockquote></details>

Maybe `DiscardZeroGradientOrThrow` or `DiscardZeroGradient`?  I think its fine to expect that the reader understands that empty gradients are inferred to be zero; or at least, I'm okay not using this function name to teach them.

---

*[math/autodiff_gradient.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-L6RUzri5WP8KKU8rvYw:-L6RfnmcaYueUzW1hap9:b-jcxzho) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L167)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

RealScalar is the argument that is being expected by isZero.  I agree we aren't passing in anything complex right now, but I feel that this is more correct for future applications?
</blockquote></details>

OK That's a good reason to use `::Real`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202)*

**Comment by SeanCurtis-TRI** [comment]
The changes in this PR are contained in #8175. What should the fate of this PR be?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6SGsUE4X9Ey9aRwq0K:b-61cyp1)*

**Comment by RussTedrake** [comment]
i was thinking we would get this in, and i would deal with the merge issues?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6Sj5zE11AG7t73JYJp:bkoaz9o)*

**Comment by SeanCurtis-TRI** [comment]
As it is, I feel like I'm reviewing this twice.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6Sk_YTOIEo8ELOx4FZ:be26ws1)*

**Comment by RussTedrake** [comment]
you LGTM'd the other version (which is the same).  can I take it as an LGTM here?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6SpS_gHzPfBRM0OddA:b7qucdc)*

**Comment by RussTedrake** [comment]
closing this, as it will come in with #8175.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/autodiff_gradient.h, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-L6RTwp13qg4iAZ_M4iX:-L6TNITOU-UHxrtCJKfL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd84d984882d35b53b384d57ce05a70591d546f8/math/autodiff_gradient.h#L164)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe `DiscardZeroGradientOrThrow` or `DiscardZeroGradient`?  I think its fine to expect that the reader understands that empty gradients are inferred to be zero; or at least, I'm okay not using this function name to teach them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8202#-:-L6TOAlPtxCcYEI0tbfO:b-4r549i)*

**Pull request closed without merging**
