### PR TITLE
[lcm] Exclude deprecated //lcm:real from build_components_refresh

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16151)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16151)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri any other comments?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nope, just forgot to apply the label.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16151#-:-MplzPe6EqMJ5HJ0eM-T:bpi6k72)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
