### PR TITLE
clean up pendulum swing up example and add it to bazel build.

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5236)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for both reviews.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-:-KdTDkogPxySPWuJH8Jq:b-kystnc)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/Pendulum/BUILD, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTEqYCHK7xI-Bdv0hA:-KdTEqYD7RVOd6mbU9ti:b-seqil) ([raw file](https://github.com/robotlocomotion/drake/blob/ef76a4754a899f2968c935cae9c0f0591059ac25/drake/examples/Pendulum/BUILD#L53)):*
> ```Python
>         "//drake/systems/primitives:trajectory_source",
>         "//drake/systems/trajectory_optimization:direct_collocation",
>         "//drake/util:app_util",
> ```

BTW The `#include` statement for this appears to be dead code; can we remove that line instead of adding this dependency?

---

*[drake/util/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTEyysAUJrCXo0qNO-:-KdTEyysAUJrCXo0qNO0:b-anrpiu) ([raw file](https://github.com/robotlocomotion/drake/blob/ef76a4754a899f2968c935cae9c0f0591059ac25/drake/util/BUILD#L47)):*
> ```Python
>     name = "app_util",
>     hdrs = ["drakeAppUtil.h"],
> )
> ```

BTW So this is fine, but can we add `deprecation = ...` like `name = 'util'` does above, because there should be no reason for any reasonably new code to still use this header -- gflags works and is prevalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-:-KdTFkD6mQ-jFY6AK3b8:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Pendulum/BUILD, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTEqYCHK7xI-Bdv0hA:-KdTGuqZVM1ax1F0JY43:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef76a4754a899f2968c935cae9c0f0591059ac25/drake/examples/Pendulum/BUILD#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The `#include` statement for this appears to be dead code; can we remove that line instead of adding this dependency?
</blockquote></details>

Done.

---

*[drake/util/BUILD, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTEyysAUJrCXo0qNO-:-KdTGypUO13dfBOKg64o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef76a4754a899f2968c935cae9c0f0591059ac25/drake/util/BUILD#L47)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW So this is fine, but can we add `deprecation = ...` like `name = 'util'` does above, because there should be no reason for any reasonably new code to still use this header -- gflags works and is prevalent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Pendulum/BUILD, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTKVJj6UZKVTq2wuaj:-KdTKVJkkdv3qCBlS7cq:bdobjkr) ([raw file](https://github.com/robotlocomotion/drake/blob/41f165618e15e631da065ba2a8b33514173052a0/drake/examples/Pendulum/BUILD#L53)):*
> ```Python
>         "//drake/systems/primitives:trajectory_source",
>         "//drake/systems/trajectory_optimization:direct_collocation",
>         "//externals/gflags",
> ```

This should be `@gflags//:gflags`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/examples/Pendulum/BUILD, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5236#-KdTKVJj6UZKVTq2wuaj:-KdTLPXw3iannK3bkcT8:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/41f165618e15e631da065ba2a8b33514173052a0/drake/examples/Pendulum/BUILD#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should be `@gflags//:gflags`.
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5236)*

**Pull request merged**
