### PR TITLE
Convert Drake ExpressionKind.Constant to Sympy Integer and Float

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
If you can find someone who actually _uses_ SymPy to be the feature reviewer (I don't), that would lead to a slightly better review coverage.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-Nr6Yvnz9jzz1emMZWyl:b-ew8pen)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/symbolic/_symbolic_sympy.py` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-Nr6YyDR8Mkizd2nrgQd:-Nr6YyDR8Mkizd2nrgQe:bl9w5f3) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d529afea98d92e488b8045140b5d73c251ec4b6/bindings/pydrake/symbolic/_symbolic_sympy.py#L52)):*
> ```Python
> # for that kind of term; this forms the core of `pydrake.symbolic.to_sympy()`.
> _SYMPY_CONSTRUCTOR = {
>     # Leave floats alone -- don't preemptively wrap them in sympy.Float.
> ```

nit This comment is no longer accurate.

It also begs the question -- should the new helper function return sympy objects, or just plain python `float` and `int`?

**Review by AlexandreAmice — COMMENTED** [review]
+@nepfaff Would you like to take this one?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-Nr6__9J3fGGTTSFK-Qr:b-v5dus0)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),nepfaff, missing label for release notes

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),nepfaff, missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/symbolic/_symbolic_sympy.py` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-Nr6aAGI-uSSOEbj09LU:-Nr6aAGI-uSSOEbj09LV:b-qtha0p) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d529afea98d92e488b8045140b5d73c251ec4b6/bindings/pydrake/symbolic/_symbolic_sympy.py#L33)):*
> ```Python
>     sympy type
>     """
>     if int(x) == x:
> ```

nit This can throw OverflowError (e.g., when given an infinity), and we don't want that to percolate up to the user.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),nepfaff, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`bindings/pydrake/symbolic/_symbolic_sympy.py` line 52 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-Nr6YyDR8Mkizd2nrgQd:-Nr6_z2z6olCvmNGSmPX:b-t3rkqy) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d529afea98d92e488b8045140b5d73c251ec4b6/bindings/pydrake/symbolic/_symbolic_sympy.py#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This comment is no longer accurate.

It also begs the question -- should the new helper function return sympy objects, or just plain python `float` and `int`?
</blockquote></details>

Sympy objects are better in this instance since when I call `to_sympy` I expect to **always** get back the sympy equivalent. In particular, sympy can (and should) throw if we attempt to do
```
sym.Expr(3) + 1
```
and so I think we would want the sympy object

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996)* status: LGTM missing from assignees jwnimmer-tri(platform),nepfaff, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by nepfaff** [comment]
> Sympy objects are better in this instance since when I call to_sympy I expect to always get back the sympy equivalent.

I agree. This required me to introduce additional type checking in the past

**Review by nepfaff — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-Nr7XJfo-h762vX22l2l:bnfp4nl)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-Nr7ag0Q5VapDKdIjGd6:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/symbolic/_symbolic_sympy.py` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-Nr7anYT5-QrMIadhj0w:-Nr7anYT5-QrMIadhj0x:b-ouhoik) ([raw file](https://github.com/RobotLocomotion/drake/blob/673ffb8d7da43a3762e51d1e6a3e5ec8158876d8/bindings/pydrake/symbolic/_symbolic_sympy.py#L31)):*
> ```Python
> def _handle_constant(x):
>     """This function is used to cast constant expressions to the appropriate
>     sympy type
> ```

typo Punctuate complete sentence.



_Suggestion:_
```Python
    sympy type.
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by ggould-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-NrB9AASCIqTzwgGTkOV:b-l8xbmn)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by ggould-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20996#-:-NrGBzd-2XNnM-61v2MO:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),nepfaff

**Pull request merged**
