### PR TITLE
Add new ctr, symbolic::Expression(const std::string& name)

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4935)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@david-german-tri , both-reviews please. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4935#-:-KbVgtX3d-eipBzVL5jG:bp8k4eo)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4935#-:-KbVh4nqPgWfoQ04PeL4:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4935)*

**Comment by david-german-tri** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4935#-:-KbVhF44rVpJ9CUtdTBG:b-ucfknh)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot retest linux-gcc-experimental-ros please.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by david-german-tri** [comment]
git failure is spurious, as noted on Slack.  Override-merging.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4935#-:-KbW-V_WOpMX5IhloymH:bil8v3s)*

**Pull request merged**
