### PR TITLE
Bind reset_integrator for Python

### PR DESCRIPTION
**Pull request by gizatt**
@EricCousineau-TRI, may I ask you for a feature review?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending discussion items.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/systems/analysis_py.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3bhIWDBnx4kpw_lB3:-LD3bhIX9J7ztr-zGFnD:b9b3c1s) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L54)):*
> ```cpp
>            // Keep alive, reference: `self` keeps `System` alive.
>            py::keep_alive<1, 2>(),
>            // Keep alive, ownership: `Context` keeps `self` alive.
> ```

This should actually be ``Keep alive, reference: `self`keeps `Context` alive``, since the `Context` is just a pointer (not a `unique_ptr`). The flag should also be reversed to `keep_alive<1, 3>`

---

*[bindings/pydrake/systems/analysis_py.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3bvfO5z_gveW7qqa2:-LD3bvfO5z_gveW7qqa3:b2nreh6) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L72)):*
> ```cpp
>            py::keep_alive<1, 2>(),
>            // Keep alive, ownership: `Context` keeps `self` alive.
>            py::keep_alive<4, 1>());
> ```

Same as above.

---

*[bindings/pydrake/systems/analysis_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3c-ZD-5ZZvAGU4X9b:-LD3c-ZD-5ZZvAGU4X9c:bdj28nm) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L100)):*
> ```cpp
>               std::unique_ptr<IntegratorBase<T>> integrator) {
>              return self->reset_integrator(std::move(integrator));
>            })
> ```

You'll want a `Keep alive, ownership ...` here, since we want to ensure that losing a reference to `Simulator` does not cause it to destruct, which may kill lingering references to `Context`.

---

*[bindings/pydrake/systems/test/general_test.py, line 295 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3dX-5AH6W6k7tvCgb:-LD3dX-68evfyuaKvd-c:bl9ij7q) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/test/general_test.py#L295)):*
> ```Python
> 
>         simulator.reset_integrator(
>             RungeKutta2Integrator(
> ```

Above this, can you test the other overloads for the integrator types? (the ones without specifying `context`)

You don't have to pass them to `reset_integrator`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844#-:-LD3cE3h3s694nkj3_Ut:b-2l0s3s)*

**Comment by gizatt** [comment]
Thanks! Does this go to Sammy or Jeremy at this hour?

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3bhIWDBnx4kpw_lB3:-LD3oKlS6ApBi1StdHv1:bz8skgd) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L54)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This should actually be ``Keep alive, reference: `self`keeps `Context` alive``, since the `Context` is just a pointer (not a `unique_ptr`). The flag should also be reversed to `keep_alive<1, 3>`
</blockquote></details>

Done. I didn't get the unique_ptr distinction on my first pass, but I think I do now -- thanks!

---

*[bindings/pydrake/systems/analysis_py.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3bvfO5z_gveW7qqa2:-LD3obZc0e9ZGsG4BZ2U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/analysis_py.cc, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3c-ZD-5ZZvAGU4X9b:-LD3ov92-8OF-DOPzweJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/analysis_py.cc#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

You'll want a `Keep alive, ownership ...` here, since we want to ensure that losing a reference to `Simulator` does not cause it to destruct, which may kill lingering references to `Context`.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/general_test.py, line 295 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD3dX-5AH6W6k7tvCgb:-LD3pSdLDhNCzboZccDU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/763dbb9729becb7658b2c8581ed19344006a6995/bindings/pydrake/systems/test/general_test.py#L295)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Above this, can you test the other overloads for the integrator types? (the ones without specifying `context`)

You don't have to pass them to `reset_integrator`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844#-:-LD3pixRD0keguVLcDsd:b-hhdwst)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD4PKDg2brkTjOdfJvn:-LD4PKDg2brkTjOdfJvo:bnbx2sk) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec273d58e1235347eeb6a92e122c86a475350c7/bindings/pydrake/systems/analysis_py.cc#L42)):*
> ```cpp
>            &IntegratorBase<T>::get_throw_on_minimum_step_size_violation);
> 
>     DefineTemplateClassWithDefault<RungeKutta3Integrator<T>,
> ```

FYI My small brain hurts to see RK3 listed before RK2 (I assumed alphabetical) but on the other hand I guess there is nothing wrong with it this way either.

---

*[bindings/pydrake/systems/primitives_py.cc, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD4O4Dj3xCMPpi8olQs:-LD4O4Dj3xCMPpi8olQt:b4gbkdx) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec273d58e1235347eeb6a92e122c86a475350c7/bindings/pydrake/systems/primitives_py.cc#L75)):*
> ```cpp
> 
>     DefineTemplateClassWithDefault<Gain<T>, LeafSystem<T>>(
>         m, "Gain", GetPyParam<T>())
> ```

This needs a couple new lines added to the unit test in `test/primitives_test.py`; see e.g. what `ConstantVectorSource` has and mimic it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844#-:-LD4PejR4YiNc4vD_iiB:bcpz082)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844)*

**Comment by gizatt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/analysis_py.cc, line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD4PKDg2brkTjOdfJvn:-LD4SUrYApB70pI-11Qh:b-e5ncug) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec273d58e1235347eeb6a92e122c86a475350c7/bindings/pydrake/systems/analysis_py.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI My small brain hurts to see RK3 listed before RK2 (I assumed alphabetical) but on the other hand I guess there is nothing wrong with it this way either.
</blockquote></details>

Ha, now that you point it out I feel the same! Fixed.

---

*[bindings/pydrake/systems/primitives_py.cc, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8844#-LD4O4Dj3xCMPpi8olQs:-LD4UaXr3ZKo2t6-iSUv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2ec273d58e1235347eeb6a92e122c86a475350c7/bindings/pydrake/systems/primitives_py.cc#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This needs a couple new lines added to the unit test in `test/primitives_test.py`; see e.g. what `ConstantVectorSource` has and mimic it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) will need a squash during merge.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8844#-:-LD4X0uk2rFquBGczjww:bcagjua)*

**Pull request merged**
