### PR TITLE
GurobiSolver throws errors when option is set incorrectly.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in the comment https://github.com/RobotLocomotion/drake/issues/15342#issuecomment-879038929

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please.

**Comment by sherm1** [comment]
Is this ready to have a feature reviewer assigned, @hongkai-dai ?

**Review by hongkai-dai — COMMENTED** [review]
Ah I forgot, thanks for the reminder Sherm.

+@seancurtis-tri could you review this PR as well, as you already did for the Mosek solver? Thanks a lot!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412#-:-Mf5e3rDDtMYfBqzpG6X:bu2b8i9)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
First pass done.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412#-:-Mf8LKcn1-Fqk544mkJr:b-te4kzy)* status: 4 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 773 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8JRumBq_0RXGRspIr:-Mf8JRumBq_0RXGRspIs:bu9b6vk) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/gurobi_solver.cc#L773)):*
> ```cpp
> 
> template <typename T>
> void SetGurobiOptionCheck(int error, const std::string& option, const T& val) {
> ```

nit: In mosek we called this `ThrowForInvalidOption1. It otherwise seems to have the same signature. Any reason we can't name it the same here?

It's in an anonymous namespace in a .cc file, so we don't have to worry about name collisions.
___
*[solvers/gurobi_solver.cc, line 777 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8JxGo4YCcDQoDFnw4:-Mf8JxGo4YCcDQoDFnw5:b2y29r8) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/gurobi_solver.cc#L777)):*
> ```cpp
>     if (error == GRB_ERROR_UNKNOWN_PARAMETER) {
>       throw std::runtime_error(fmt::format(
>           "GurobiSolver(): {} is an unknown parameter in Gurobi, check "
> ```

nit: Can we delimit the option name and value with '?  (e.g., "...'{}' is an unknown).

Again, the goal is to make this more closely resemble the behavior in mosek solver and applies to all three error messages.
___
*[solvers/gurobi_solver.cc, line 789 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8KL2qEBUsu584qV9o:-Mf8KL2qEBUsu584qV9p:b-fapivn) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/gurobi_solver.cc#L789)):*
> ```cpp
>         fmt::format("GurobiSolver(): error code {}, cannot set option {} to "
>                     "value {}, check "
>                     "https://www.gurobi.com/documentation/9.1/refman/"
> ```

nit: Does this introduce the same version issue we resolved in the mosek solver? Again, all things being equal, the more they resemble each other, the easier they'll all be to maintain.
___
*[solvers/gurobi_solver.cc, line 1030 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8Ky2d7ByRv-0c8ZL2:-Mf8Ky2d7ByRv-0c8ZL3:b-asbwpp) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/gurobi_solver.cc#L1030)):*
> ```cpp
>     if (!error) {
>       error = GRBsetdblparam(model_env, it.first.c_str(), it.second);
>       SetGurobiOptionCheck(error, it.first.c_str(), it.second);
> ```

nit: `it.first` is a `std::string`. `SetGurobiOptionCheck` takes a `std::string` as this parameter. You should eliminate the call to `c_str()`.
___
*[solvers/test/gurobi_solver_test.cc, line 363 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8LFlb6wXfxgZWe5Dz:-Mf8LFlc3bm0HO7pBEM-:b-5y8hhr) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/test/gurobi_solver_test.cc#L363)):*
> ```cpp
>     SolverOptions solver_options1;
>     // Report error when we set an unknown attribute to Gurobi.
>     solver_options1.SetOption(solver.solver_id(), "Foo", 1);
> ```

BTW You have three unique messages. Do you want to exercise all three?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[solvers/test/gurobi_solver_test.cc, line 363 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15412#-Mf8LFlb6wXfxgZWe5Dz:-MfEI4wmC4VKLzF7oArg:b28aoz4) ([raw file](https://github.com/robotlocomotion/drake/blob/00d1e8621f893a58ab0afe5c23fc797c44fd7eec/solvers/test/gurobi_solver_test.cc#L363)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You have three unique messages. Do you want to exercise all three?
</blockquote></details>

I haven't found how to trigger the last one when error != GRB_ERROR_VALUE_OF_OF_RANGE and error != GRB_ERROR_UNKNOWN_PARAMETER. I add that last error message just in case I missed something. I added the documentation.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

+@jwnimmer-tri for platform review, please.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412#-:-MfESDWWCFJIpLPAsdLN:b-2qsqpj)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/gurobi_solver.cc, line 791 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfES2IjCGEfsGhxGAG2:-MfES2IjCGEfsGhxGAG3:b-elq1n5) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L791)):*
nit: This is *great*. Could you extend it just a bit more with.

> This is untested because I don't know how to trigger an unknown error.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 792 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEVSyC6YW0wO1Ylcf5:-MfEVSyDD6PUftrkS4ip:br3f1t0) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L792)):*
> ```cpp
>     // case I missed something, I added this throw to capture any other possible
>     // error message.
>     throw std::runtime_error(
> ```

If I am reading the control flow correctly, then in case some earlier step like `ProcessLinearConstraints` sets an error code, we will throw this message about "cannot set option".

Because the `merged_options` handling code now throws, I think it _must never_ set the same `int error` as the rest of the program setup.

So something more like this:

```c++
...
GRBenv* model_env = GRBgetenv(model);

if (!error) {
  for (const auto& it : merged_options.GetOptionsDouble(id())) {
    int option_error = GRBsetdblparam(model_env, it.first.c_str(), it.second);
    ThrowForInvalidOption(option_error, it.first, it.second);
  }
  for (const auto& it : merged_options.GetOptionsInt(id())) {
   ...
}
...
```
___
*[solvers/gurobi_solver.cc, line 1030 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEWkG92WWdRuUQkTcs:-MfEWkG92WWdRuUQkTct:bo8v8ts) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L1030)):*
> ```cpp
>   // can be overridden by parameters set in the MathematicalProgram).
>   if (!error) {
>     error = GRBsetintparam(model_env, GRB_INT_PAR_OUTPUTFLAG, 0);
> ```

I'm not clear on why _this_ option change yields a MathematicalProgramResult failure, instead of throwing or asserting.  I'm not sure what the best choice is, but we almost certainly need to write an explanation here in a comment.
___
*[solvers/test/gurobi_solver_test.cc, line 365 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEXbW69J3S8bBSgFgQ:-MfEXbW69J3S8bBSgFgR:b-mwztqk) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/test/gurobi_solver_test.cc#L365)):*
> ```cpp
>     solver_options1.SetOption(solver.solver_id(), "Foo", 1);
>     DRAKE_EXPECT_THROWS_MESSAGE(solver.Solve(prog, {}, solver_options1),
>                                 std::runtime_error,
> ```

nit Remove the second argument here (`std::runtime_error,`).  There is no justification for checking the exception type here.

https://drake.mit.edu/styleguide/cppguide.html#Exceptions

Ditto below.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/gurobi_solver.cc, line 792 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEVSyC6YW0wO1Ylcf5:-MfGmh0E-cMpTBr4F2Yl:bjgjned) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L792)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If I am reading the control flow correctly, then in case some earlier step like `ProcessLinearConstraints` sets an error code, we will throw this message about "cannot set option".

Because the `merged_options` handling code now throws, I think it _must never_ set the same `int error` as the rest of the program setup.

So something more like this:

```c++
...
GRBenv* model_env = GRBgetenv(model);

if (!error) {
  for (const auto& it : merged_options.GetOptionsDouble(id())) {
    int option_error = GRBsetdblparam(model_env, it.first.c_str(), it.second);
    ThrowForInvalidOption(option_error, it.first, it.second);
  }
  for (const auto& it : merged_options.GetOptionsInt(id())) {
   ...
}
...
```
</blockquote></details>

I am not sure I agree. The code which calls this function is
```cc
  for (const auto& it : merged_options.GetOptionsDouble(id())) {
    if (!error) {
      error = GRBsetdblparam(model_env, it.first.c_str(), it.second);
      ThrowForInvalidOption(error, it.first, it.second);
    }
  }
```
So if previous code has error != 0, then this if branch would not be triggered, and we shouldn't call the function`ThrowForInvalidOption`.
___
*[solvers/gurobi_solver.cc, line 1030 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEWkG92WWdRuUQkTcs:-MfGn4tT9L-6ReA0gkq8:b-347bmc) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L1030)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not clear on why _this_ option change yields a MathematicalProgramResult failure, instead of throwing or asserting.  I'm not sure what the best choice is, but we almost certainly need to write an explanation here in a comment.
</blockquote></details>

Sorry I don't think I understand the comment. This line is not changed in this PR. And I don't think calling `GRBsetintparam(model_env, GRB_INT_PAR_OUTPUTFLAG, 0);` would cause a MathematicalProgramResutl failure. Do you suggest I should check if the returned `error` is not 0, and throw a runtime error here immediately?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412#-:-MfGsXCVD6oNniBp1Rbx:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 792 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEVSyC6YW0wO1Ylcf5:-MfGpS_n8EF7dwzgtXgi:b-kuwy37) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L792)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure I agree. The code which calls this function is
```cc
  for (const auto& it : merged_options.GetOptionsDouble(id())) {
    if (!error) {
      error = GRBsetdblparam(model_env, it.first.c_str(), it.second);
      ThrowForInvalidOption(error, it.first, it.second);
    }
  }
```
So if previous code has error != 0, then this if branch would not be triggered, and we shouldn't call the function`ThrowForInvalidOption`.

</blockquote></details>

Ah, yes, that sounds right; withdrawn.
___
*[solvers/gurobi_solver.cc, line 1030 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEWkG92WWdRuUQkTcs:-MfGpwNqDhCChYjGvp6n:b-xd0k3w) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L1030)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't think I understand the comment. This line is not changed in this PR. And I don't think calling `GRBsetintparam(model_env, GRB_INT_PAR_OUTPUTFLAG, 0);` would cause a MathematicalProgramResutl failure. Do you suggest I should check if the returned `error` is not 0, and throw a runtime error here immediately?
</blockquote></details>

The line is not changed in this PR, but maybe it's _supposed_ to be changed?

My starting premise is that since we are assigning the result of `GRBsetintparam` here to `error` rather than discarding the return value, we presume that Gurobi might generate an error code that we should pass along to the user via some means.

For all _other_ Gurobi option changes below, when Gurobi does not obey the option then we throw an exception with an explanation.  If this line errors out, though, it seems we leave it as a set `error` and return `kInvalidInput` on L1097.  In this situation though, the user's input was not invalid; rather, it was a problem with our solver wrapper being somehow incompatible with Gurobi.

Returning `kInvalidInput` when we are unable to configure the logging settings correctly here, rather than throwing like we do with any _other_ logging option change, seems inconsistent to me.  There might be a good reason for it (in which case it needs a comment here explaining why), but so far, I don't understand why it's a special case.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[solvers/gurobi_solver.cc, line 1030 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEWkG92WWdRuUQkTcs:-MfJRkjICKnziyhCiOfo:b-9e0isj) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L1030)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The line is not changed in this PR, but maybe it's _supposed_ to be changed?

My starting premise is that since we are assigning the result of `GRBsetintparam` here to `error` rather than discarding the return value, we presume that Gurobi might generate an error code that we should pass along to the user via some means.

For all _other_ Gurobi option changes below, when Gurobi does not obey the option then we throw an exception with an explanation.  If this line errors out, though, it seems we leave it as a set `error` and return `kInvalidInput` on L1097.  In this situation though, the user's input was not invalid; rather, it was a problem with our solver wrapper being somehow incompatible with Gurobi.

Returning `kInvalidInput` when we are unable to configure the logging settings correctly here, rather than throwing like we do with any _other_ logging option change, seems inconsistent to me.  There might be a good reason for it (in which case it needs a comment here explaining why), but so far, I don't understand why it's a special case.
</blockquote></details>

I see, that makes sense.

I think setting GRB_INT_PAR_OUTPUT_FLAG to 0 should never cause an error. But just in case I missed anything, or if in the future Gurobi changes its implementation such that this line could cause an error, I keep the returned `error`, and add a DRAKE_DEMAND(!error) below. Do you think this is reasonable?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/gurobi_solver.cc, line 1049 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfJZzAC3cersfKefcOf:-MfJZzAC3cersfKefcOg:btyplh0) ([raw file](https://github.com/robotlocomotion/drake/blob/0a68744498d3b776759be2212a0f0fe205b341c0/solvers/gurobi_solver.cc#L1049)):*
> ```cpp
>         compute_iis = static_cast<bool>(it.second);
>         if (!(it.second == 0 || it.second == 1)) {
>           throw std::runtime_error(fmt::format(
> ```

nit: This new throw doesn't seem to get tested.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 1030 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfEWkG92WWdRuUQkTcs:-MfJhpjR3CWaJ_OV86aS:b-ra74ya) ([raw file](https://github.com/robotlocomotion/drake/blob/90323a582cddf43ff2bd57f0bf735c5a444e13cc/solvers/gurobi_solver.cc#L1030)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, that makes sense.

I think setting GRB_INT_PAR_OUTPUT_FLAG to 0 should never cause an error. But just in case I missed anything, or if in the future Gurobi changes its implementation such that this line could cause an error, I keep the returned `error`, and add a DRAKE_DEMAND(!error) below. Do you think this is reasonable?
</blockquote></details>

Fine by me.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15412)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

___
*[solvers/gurobi_solver.cc, line 1049 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15412#-MfJZzAC3cersfKefcOf:-MfJiQEeCsgirMV-u5cC:b174wvn) ([raw file](https://github.com/robotlocomotion/drake/blob/0a68744498d3b776759be2212a0f0fe205b341c0/solvers/gurobi_solver.cc#L1049)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This new throw doesn't seem to get tested.
</blockquote></details>

OK That's a rebased line that is tested on master already.  (If you re-select diff bounds to base..final, nothing here is actually changed.)

**Pull request merged**
