### PR TITLE
Extend symbolic polynomial decompose to handle non-polynomial coefficients

### LINKED ISSUE #7089: DecomposePolynomialVisitor should use VisitExpression, not VisitPolynomial

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #7089

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7168)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@hongkai-dai , could you review this PR?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-KvZWilDLkLsmFE4vVlj:b-hcufa2)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai as feature reviewer

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-KvZWpxDNcRg9Cr-fBj7:b-q6trsb)*

**Comment by soonho-tri** [comment]
@hongkai-dai, Thank you!

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-KvZXcpgtzZuSgJg-Ypt:bvu7ebn)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZbPxW8hE2nyrNo-qH:-KvZbPxW8hE2nyrNo-qI:bl0v0vw) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L158)):*
> ```cpp
>       // Case: vars(baseᵢ) ∩ indeterminates ≠ ∅.
>       // exponentᵢ should be a positive integer.
>       if (!is_constant(exponent) ||
> ```

It is a bit tricky here, that if base = `x²`, exponent = 2.5, then `power(base, exponent) = x⁵` is still a polynomial, although `exponent` is not a positive integer. Just want to confirm that we want to rule out this case.

---

*[drake/common/symbolic_polynomial.cc, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZchZkx07EDO_rCWok:-KvZchZkx07EDO_rCWol:brsi0vh) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L169)):*
> ```cpp
>       Expression coeff{1.0};
>       Monomial m{};
>       if (!is_variable(base) && !is_multiplication(base)) {
> ```

If base = `x + y`, `exponent = 2`, then `power(x+y, 2)` should be a polynomial, although `base` is not a variable, nor a multiplication.

---

*[drake/common/symbolic_polynomial.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZdbj03pNBvTXlCxat:-KvZdbj03pNBvTXlCxau:btjlp4k) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L202)):*
> ```cpp
> 
>     // We require that the denominator e₂ is free of indeterminates for e to be
>     // a polynomial. This is because canceling a common factor is not a sound
> ```

typo, `canceling` -> `cancelling`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZbPxW8hE2nyrNo-qH:-KvZkMdkSU_VVjs04KXs:b-khudxm) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L158)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is a bit tricky here, that if base = `x²`, exponent = 2.5, then `power(base, exponent) = x⁵` is still a polynomial, although `exponent` is not a positive integer. Just want to confirm that we want to rule out this case.
</blockquote></details>

`pow(x², 2.5)` is simplified into `pow(x, 5)` by construction and shouldn't be a problem. I've added a test case for this.

---

*[drake/common/symbolic_polynomial.cc, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZchZkx07EDO_rCWok:-KvZkg8tRjCCRRJY-y5I:b912n0q) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L169)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If base = `x + y`, `exponent = 2`, then `power(x+y, 2)` should be a polynomial, although `base` is not a variable, nor a multiplication.
</blockquote></details>

`e` is a pre-expanded expression so it should be a product of variables for `e` to be a polynomial. I've added a testcase for `power(x+y, 2)`.

```c++
class DecomposePolynomialVisitor {
 public:
  Polynomial::MapType Decompose(const Expression& e,
                                const Variables& indeterminates) const {
    // Note that it calls `Expression::Expand()` here.
    return Visit(e.Expand(), indeterminates);
  }

 private:
  ...
```

---

*[drake/common/symbolic_polynomial.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZdbj03pNBvTXlCxat:-KvZgsQT_8jHAjN2uY-H:bb3ryto) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L202)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

typo, `canceling` -> `cancelling`.
</blockquote></details>

I found that American English uses `canceling` while British one uses `cancelling`.

https://en.wiktionary.org/wiki/cancelling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168)*

**Comment by soonho-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZbPxW8hE2nyrNo-qH:-KvZlve-LoAvglDbaAMU:b-36ix17) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L158)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`pow(x², 2.5)` is simplified into `pow(x, 5)` by construction and shouldn't be a problem. I've added a test case for this.
</blockquote></details>

Added another testcase,  `pow(x²y², 2.5) => pow(xy, 5)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ggould-tri for platform review please.

---

Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZbPxW8hE2nyrNo-qH:-Kv_O7idrDAMghEvEiU5:bpacn8i) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L158)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Added another testcase,  `pow(x²y², 2.5) => pow(xy, 5)`.
</blockquote></details>

Thanks for the explanation, and the test!

---

*[drake/common/symbolic_polynomial.cc, line 169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvZchZkx07EDO_rCWok:-Kv_OF8Uk6fDxyRSiegD:b9dzriy) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1b5c652b26affae91b5393833c3e521ba8fd0f/drake/common/symbolic_polynomial.cc#L169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`e` is a pre-expanded expression so it should be a product of variables for `e` to be a polynomial. I've added a testcase for `power(x+y, 2)`.

```c++
class DecomposePolynomialVisitor {
 public:
  Polynomial::MapType Decompose(const Expression& e,
                                const Variables& indeterminates) const {
    // Note that it calls `Expression::Expand()` here.
    return Visit(e.Expand(), indeterminates);
  }

 private:
  ...
```
</blockquote></details>

Got it, I forgot `e` has been expanded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-Kv_OML9ihKKDKON6ofl:b-9ir12m)*

**Comment by ggould-tri** [comment]
:lgtm: This is very nice and clear.  I like the `indeterminates` renaming in particular.

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.cc, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvbiUbXinco3eRRR-vj:-KvbiUbXinco3eRRR-vk:bfq4fop) ([raw file](https://github.com/robotlocomotion/drake/blob/caeaaa895a721f2b2c346f71f11c1daba24a32d6/drake/common/symbolic_polynomial.cc#L169)):*
> ```cpp
>       Expression coeff{1.0};
>       Monomial m{};
>       // base should be a product of indeterminates because `e` is a
> ```

FYI That "base" names a variable rather here would be clearer with backticks like `e` has.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-KvbjSMJNw5BtM9B9S24:bu59tom)*

**Comment by soonho-tri** [comment]
Thanks for all reviews!

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.cc, line 169 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-KvbiUbXinco3eRRR-vj:-KvboEnylAlwPYLlDHzR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/caeaaa895a721f2b2c346f71f11c1daba24a32d6/drake/common/symbolic_polynomial.cc#L169)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI That "base" names a variable rather here would be clearer with backticks like `e` has.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168#-:-KvboFDfL9gVqzSlN1I7:bdbdfhq)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7168)*

**Pull request merged**
