### PR TITLE
Allow python binding of SignalLogger to log autodiffxd data.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for feature review please.

I didn't add the python binding for the free function `LogOutput<AutoDiffXd>` as I don't know how to bind a templated free function.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWeKYxO0SxsbK-p0Uvj:b-vzad5s)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
No worries on not binding free-function; however, if you're curious, can you do so like this:

C++ code/test:
https://github.com/RobotLocomotion/drake/blob/v0.28.0/bindings/pydrake/common/test/cpp_template_pybind_test.cc#L144-L145
```
  AddTemplateMethod(py_class, "Method", &Class::Method<T>, GetPyParam<T>());
```
Python usage:
```
MyClass().Method[T]()
```

Python unittest:
https://github.com/RobotLocomotion/drake/blob/v0.28.0/bindings/pydrake/common/test/cpp_template_test.py#L203-L225

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWet9yBC3EdTGbJL2SU:bpqemtk)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/systems/primitives_py.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetjgX4WIf7676yy0u:-MWetjgYA3Re_eTP_tdJ:b18rdz6) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L44)):*
> ```cpp
> namespace {
> 
> Eigen::VectorBlock<const VectorX<double>> CopyIfNotPodType(
> ```

BTW Could you add a `TODO(eric.cousineau): Consolidate these methods?` here?
___
*[bindings/pydrake/systems/test/primitives_test.py, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWeu4437sh4CM_mSHis:-MWeu4437sh4CM_mSHit:b-2vs9f4) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L121)):*
> ```Python
>         # Add a redundant logger via the helper method.
>         if T == float:
>             logger_per_step_2 = LogOutput(
> ```

Working: I'll briefly try out binding templated method and give you a meta-PR if that works.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetzWa52iMiPYZZN4I:-MWetzWa52iMiPYZZN4J:bomiov5) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L142)):*
> ```Python
>         self.assertTrue(t.shape[0] > 2)
>         self.assertTrue(t.shape[0] == x.shape[1])
>         if T == float:
> ```

Working: I'm not sure if I understand why this is necessary... lemme try locally.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 148 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWettiv-GsEyJwicsAc:-MWettiwAttJAO3Sjmqv:b-wabb1h) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L148)):*
> ```Python
>                 x[0, -1].value(), (t[-1] * kValue).value(), places=2)
>         if T == float:
>             np.testing.assert_array_equal(x, logger_per_step_2.data())
> ```

Can you change this to use `numpy_compare.assert_float_equal()`?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/systems/primitives_py.cc, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWeuBpA3mK5qJrSes_X:-MWeuBpA3mK5qJrSes_Y:b-tnwuy1) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L288)):*
> ```cpp
>             return_value_policy_for_scalar_type<T>(),
>             // Keep alive, ownership: `return` keeps `self` alive.
>             pybind11::keep_alive<0, 1>(), doc.SignalLogger.data.doc)
> ```

nit `keep_alive` seems redundant here.

Is it possible to remove this?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWf55_QBi7UxITq3vLS:-MWf55_SAAsx9CMMrCmd:bb5i9rs) (no related file):*
Please review: https://github.com/hongkai-dai/drake/pull/22

This addresses my comments, as well as binds free-func `LogOutput`

---

**Review by EricCousineau-TRI — COMMENTED** [review]
See also opinion in stated on Slack:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1616704567017200?thread_ts=1616653855.015600&cid=C3YB3EV5W
> In retrospect, and from a picky perspective, I think this was worth it you're doing intense multi-rate discrete+continuous things.
> If this was for all discrete fixed-rate stuff (e.g. MBP in discrete mode, or a simple plant), then just doing a controlled `Simulator.AdvanceTo()` + concat'ing stuff to a Python list may've been easier?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWf5_sOErmWFk4z9p9I:bvnsy7)* status: 5 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[bindings/pydrake/systems/primitives_py.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetjgX4WIf7676yy0u:-MWh5Dmh0KOyKsOTvJYh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Could you add a `TODO(eric.cousineau): Consolidate these methods?` here?
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/primitives_py.cc, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWeuBpA3mK5qJrSes_X:-MWh5QCDBZe411zHHAjP:bqoq1vu) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L288)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `keep_alive` seems redundant here.

Is it possible to remove this?
</blockquote></details>

Done. I removed `keep_alive`. 

But I don't quite understand why it is redundant. If `T=double`, then the returned data is a block matrix from this SignalLogger. I thought that if the returned block matrix is alive, then it requires the original data (which is SignalLogger.log_.data_) also alive? 
___
*[bindings/pydrake/systems/test/primitives_test.py, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWeu4437sh4CM_mSHis:-MWh6G3x2xAxfdRiHHwZ:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L121)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I'll briefly try out binding templated method and give you a meta-PR if that works.
</blockquote></details>

Thanks!
___
*[bindings/pydrake/systems/test/primitives_test.py, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetzWa52iMiPYZZN4I:-MWh6Ks62nLGg2CUvl-_:bhznjxh) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L142)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I'm not sure if I understand why this is necessary... lemme try locally.
</blockquote></details>

This was because assertAlmostEqual works for float, but not quite for AutoDiffXd. Your `numpy_compare.assert_allclose` resolves the issue.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 148 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWettiv-GsEyJwicsAc:-MWh6YVAARrme4sqb5vD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L148)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you change this to use `numpy_compare.assert_float_equal()`?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWf55_QBi7UxITq3vLS:-MWh8_Ei5QUPeO51Jmg0:b-ek0rh5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Please review: https://github.com/hongkai-dai/drake/pull/22

This addresses my comments, as well as binds free-func `LogOutput`
</blockquote></details>

Thanks for the PR!

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: (with some bias hehe)
+@sherm1 for platform review on Monday, please! (since I am on duty Monday)

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWjVeyuBN7jHR4yCkAW:b-3eafil)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWf55_QBi7UxITq3vLS:-MWjUae86hwPOrT9MhHS:b-m78k76) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks for the PR!
</blockquote></details>

OK Welcome!

---
___
*[bindings/pydrake/systems/primitives_py.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetjgX4WIf7676yy0u:-MWjUhWwEYW8hFlydbqj:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L44)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK Sweet!
___
*[bindings/pydrake/systems/primitives_py.cc, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWeuBpA3mK5qJrSes_X:-MWjUsiu3nKWsmim496C:b-abyah5) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/primitives_py.cc#L288)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I removed `keep_alive`. 

But I don't quite understand why it is redundant. If `T=double`, then the returned data is a block matrix from this SignalLogger. I thought that if the returned block matrix is alive, then it requires the original data (which is SignalLogger.log_.data_) also alive? 
</blockquote></details>

OK For `T=double`, the policy *should* cover it (and I believe, but this unittest, it does).
See: https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeReturnValuePolicy
(be sure to visit link to upstream docs)
___
*[bindings/pydrake/systems/test/primitives_test.py, line 142 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWetzWa52iMiPYZZN4I:-MWjVbqm6OLNXJIMuQmn:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake/blob/35c4f2b0e8605da0dce7324b0fe40c76204a84bf/bindings/pydrake/systems/test/primitives_test.py#L142)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This was because assertAlmostEqual works for float, but not quite for AutoDiffXd. Your `numpy_compare.assert_allclose` resolves the issue.
</blockquote></details>

OK Sweet!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one minor comment.

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWzefKxCjxhnOjphINc:b-40zb13)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[bindings/pydrake/systems/primitives_py.cc, line 56 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWze1q06FLIfv36S4Ei:-MWze1q06FLIfv36S4Ej:bgug6h1) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3344457cd70d06453ebd9810767c038d5d66ef/bindings/pydrake/systems/primitives_py.cc#L56)):*
> ```cpp
>   // N.B. This references the existing vector's data, and does not perform a
>   // copy.
>   return x;
> ```

minor: I think this _is_ copying the data since it is going from a block to a data-owning VectorX (just like the MatrixX method below). Fix comment?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[bindings/pydrake/systems/primitives_py.cc, line 56 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14823#-MWze1q06FLIfv36S4Ei:-MWzi3iQAZBsJemqyGhB:brz8zn2) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3344457cd70d06453ebd9810767c038d5d66ef/bindings/pydrake/systems/primitives_py.cc#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think this _is_ copying the data since it is going from a block to a data-owning VectorX (just like the MatrixX method below). Fix comment?
</blockquote></details>

OK Would prefer we do that by culling it out. Will try it, timeboxing to 5min.

Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
Merging; will try to address TODO on factoring `CopyIf*` functions as well as Sherm's comment.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14823#-:-MWzivmc6fWuBl55pl-D:b-j59rt2)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by EricCousineau-TRI** [comment]
Filed #14839 (exceeded timebox by 15min :grimacing:)

**Pull request merged**
