### PR TITLE
workspace: Upgrade lcm to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14418)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri I'm curious to get your thoughts on this update.  It incorporates https://github.com/lcm-proj/lcm/pull/342, a fix for fragmentation reassembly.  Do you think we should burn-in test this change on a camera station before we commit it?

**Comment by jamiesnape** [comment]
Can we defer this one until #14395 is in?

**Comment by jwnimmer-tri** [comment]
This is "priority: low" and that one is "priority: high" so yes, we can sequence them accordingly.

I would not have thought that the two PRs are related, though.  However, looking more, I guess that's because `libddApp.so` depends on `libdrake_lcm.so` to be provided by the Drake source tree?  In other words, that the tarball we precompile from upstream is not standalone?  That seems like a bug.  It should be self-contained, and incorporate its own shared library, adjacenent to libddApp.so.

**Comment by jamiesnape** [comment]
There is actually a lot that we don't duplicate, since there would be lot of conflicting Python, as well as VTK on Linux. I was going to finally add the script (#10729) in #14395, but there is a lot in that PR already. Most of the C++ dependencies are statically linked, but LCM is LGPL.

I think we already talked about using whatever system VTK is available for Drake Visualizer, so fixing up an independent LCM should probably happen as well, so I am not disagreeing with you in any way that it could be a bug.

**Review by sammy-tri — COMMENTED** [review]
>  Do you think we should burn-in test this change on a camera station before we commit it?

I looked at lcm-proj/lcm#342 and while it's not obviously wrong  to me, I think we should do some sort of burn-in test.  Our camera setups do use fragmented LCM messages, so this change is relevant to our interests, even if we haven't experienced this issue.  I'll think for a bit on what would be a not-super-complicated before/after test.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14418#-:-MNy_I6j3OHMXtz3r8YT:b-el0k0y)* status: LGTM missing from assignee sammy-tri(platform), labeled "do not merge" (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
I don't see any significant difference in LCM performance before/after this change.  I doubted we'd be hitting this case often anyway (though it would be possible), so no real surprise there.  As it doesn't make things any worse, anyway, :lgtm:.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14418#-:-MO3Dmh1Dk686P4GaeYj:bqocykr)* status: labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
> Can we defer this one until #14395 is in?

@jamiesnape Now that #14395 has merged, what else (if anything) should we do about this PR?  I just triggered a rebuild.  Is CI a sufficient check, or did you have something else in mind?

**Comment by jamiesnape** [comment]
CI will be a sufficient check.

**Pull request merged**
