### PR TITLE
Add GraphOfConvexSets::SolveConvexRestriction()

### PR DESCRIPTION
**Pull request by RussTedrake**
+@TobiaMarcucci for feature review, please
cc @wrangelvid

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)* status: 2 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JK3Y0EMDRYPwmJ0NU:-N_JK3Y13VK5iCwoOYQ_:b-onigp4) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.h#L515)):*
> ```objc
>   vertices associated with at least one of the active edges. Decision variables
>   for all other convex sets will be set to NaN. */
>   solvers::MathematicalProgramResult SolveWithActiveEdges(
> ```

btw -- do we like the name?  i'm open to suggestions.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JJjFu-9_OFyHH4fOM:-N_JJjFu-9_OFyHH4fON:b-huew1) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.cc#L1246)):*
> ```cpp
>   MathematicalProgramResult result = Solve(prog, options, false);
> 
>   // Add any excluded vertices to the result.
> ```

btw -- i debated whether to add these or simply leave them out.  (or potentially to have an optional argument `bool set_excluded_vertex_results=true`.  We'll pay a very small price for this if we're calling the method repeatedly during rounding.

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)* status: 3 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JK3Y0EMDRYPwmJ0NU:-N_KMDWN0tsAf2iERNX3:bpzn7jd) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.h#L515)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- do we like the name?  i'm open to suggestions.
</blockquote></details>

In my current work I'm trying to think about these as subgraphs (the SPP is looking for a path subgraph of the original graph, the MST is looking for a spanning tree, etc). In this sense, an alternative name might be SolveOnSubgraph or something like that. Note that the subgraph is uniquely defined by the edges -- no need to also specify the vertices, except for weird subgraphs where one has isolated vertices. This function should work fine if one passes, e.g., the edges of a spanning tree or a tour, correct?
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JJjFu-9_OFyHH4fOM:-N_KOLeF-IKHNhDdh2EI:bmaa2tp) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.cc#L1246)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i debated whether to add these or simply leave them out.  (or potentially to have an optional argument `bool set_excluded_vertex_results=true`.  We'll pay a very small price for this if we're calling the method repeatedly during rounding.
</blockquote></details>

This is setting the position of the other vertices to NaN? I'm happy either way, I don't see any particular disadvantage of setting also the the values for the other vertices.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1775 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_KPIgS35popC8vnPID:-N_KPIgS35popC8vnPIE:b-bkospv) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/test/graph_of_convex_sets_test.cc#L1775)):*
> ```cpp
>   // Test that solving with the known shortest path returns consistent results.
>   // The solution to this problem is not actually unique, so we cannot demand
>   // that they return exactly the same results.
> ```

This is the case with the cost Euclidean distance *not* squared, right? If yes, I agree that the solution is not unique, since if you look at the figure in the paper you see that the trajectory is stepping in the interior of a set, and moving that point along the line connecting the previous and the next vertex does not change the cost. Maybe a more robust test is with the Euclidean distance squared? In that case the minimizer should always be unique.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)* status: 3 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JK3Y0EMDRYPwmJ0NU:-N_L7OKi2slqe-koteE3:b-nrvhcx) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.h#L515)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

In my current work I'm trying to think about these as subgraphs (the SPP is looking for a path subgraph of the original graph, the MST is looking for a spanning tree, etc). In this sense, an alternative name might be SolveOnSubgraph or something like that. Note that the subgraph is uniquely defined by the edges -- no need to also specify the vertices, except for weird subgraphs where one has isolated vertices. This function should work fine if one passes, e.g., the edges of a spanning tree or a tour, correct?
</blockquote></details>

Yes, I believe it should work correctly if one passes the edges of a spanning tree or tour.  But I don't love SolveOnSubgraph, because that doesn't make it clear that all of the binaries are fixed and the problem becomes convex.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JJjFu-9_OFyHH4fOM:-N_L7e0t2pLnDZRpD1Zx:bhm0xui) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.cc#L1246)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

This is setting the position of the other vertices to NaN? I'm happy either way, I don't see any particular disadvantage of setting also the the values for the other vertices.
</blockquote></details>

My only concern is that it adds an extremely modest amount of computational cost to what I envision might be a frequently called subroutine.  My thought was that it's better to have it and remove it if/when it shows up in a profiler.  

If we don't think it adds much value, (and the absence of those values in the result would not be unclear to the user) then i would prefer to simply remove it now.
___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1775 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_KPIgS35popC8vnPID:-N_LDADv6U7TNlpcoLRS:b-hlzxed) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/test/graph_of_convex_sets_test.cc#L1775)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

This is the case with the cost Euclidean distance *not* squared, right? If yes, I agree that the solution is not unique, since if you look at the figure in the paper you see that the trajectory is stepping in the interior of a set, and moving that point along the line connecting the previous and the next vertex does not change the cost. Maybe a more robust test is with the Euclidean distance squared? In that case the minimizer should always be unique.
</blockquote></details>

Done.  I went ahead and switched the the squared norm cost.

**Review by TobiaMarcucci — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)* status: 2 unresolved discussions, LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JK3Y0EMDRYPwmJ0NU:-N_LPrbJ05QByy1m-rNC:b-xmyrk2) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.h#L515)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Yes, I believe it should work correctly if one passes the edges of a spanning tree or tour.  But I don't love SolveOnSubgraph, because that doesn't make it clear that all of the binaries are fixed and the problem becomes convex.
</blockquote></details>

As by our discussion, one other term could be `SolveConvexRestriction`
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JJjFu-9_OFyHH4fOM:-N_LQ4p1C-b-N2E463yG:b4kcyo4) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.cc#L1246)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

My only concern is that it adds an extremely modest amount of computational cost to what I envision might be a frequently called subroutine.  My thought was that it's better to have it and remove it if/when it shows up in a profiler.  

If we don't think it adds much value, (and the absence of those values in the result would not be unclear to the user) then i would prefer to simply remove it now.
</blockquote></details>

I think the first make sense. I don't think it'll ever show up in a profiler, but it might save some minor headaches/bugs.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785)* status: LGTM missing from assignee TobiaMarcucci, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 515 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JK3Y0EMDRYPwmJ0NU:-N_LZHmZ3j5yc591NJ5O:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.h#L515)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

As by our discussion, one other term could be `SolveConvexRestriction`
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 1246 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_JJjFu-9_OFyHH4fOM:-N_LZJbx0KKBNoWqLgCo:b-g4p7ox) ([raw file](https://github.com/RobotLocomotion/drake/blob/83a3f239ae33de7165e3344352a74003fa4aa2bc/geometry/optimization/graph_of_convex_sets.cc#L1246)):*
<details><summary><i>Previously, TobiaMarcucci (Tobia Marcucci) wrote…</i></summary><blockquote>

I think the first make sense. I don't think it'll ever show up in a profiler, but it might save some minor headaches/bugs.
</blockquote></details>

Done.  Agreed.

**Review by TobiaMarcucci — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-:-N_LZc9vAnnxaj6MGN8p:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri 
platform :lgtm: 
+(release notes: feature) 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-:-N_M0lbi9BOQSYAFQ1zT:ba06zzb)* status: :shipit: complete! all discussions resolved, LGTM from assignees TobiaMarcucci,xuchenhan-tri(platform)

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/graph_of_convex_sets.cc` line 1269 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19785#-N_k-BBe-4XHmRZZkKBQ:-N_k-BBf5I3D_hYqz_pH:b-gx0k69) ([raw file](https://github.com/RobotLocomotion/drake/blob/1ff75b28bba4ab4278e377df5ca1bef59c684ff8/geometry/optimization/graph_of_convex_sets.cc#L1269)):*
> ```cpp
>   }
>   result.set_decision_variable_index(decision_variable_index);
>   result.set_x_val(x_val);
> ```

BTW If the `result` contained suboptimal solutions, I think they would be the wrong size now?  Is that relevant / do we care?

**Comment by RussTedrake** [comment]
Can you say more?  The results returned are different, I agree.  But I don't understand anything to be the wrong size?  (are you saying it would error)?

**Comment by jwnimmer-tri** [comment]
I have in mind the invariant that `result.x_val_.size() == result.suboptimal_x_val_[*].size()` for all suboptimal results.

The code in this PR nan-padded the `x_val` for the unused vertices, but did not nan-pad the `suboptimal_x_val_`.

**Comment by jwnimmer-tri** [comment]
Probably the best fix would be to add a function on `MathematicalProgramResult` that takes in a `VectorXDecisionVariable` and appends it to the index, filling in the new `x_val` positions with NaNs across the board.  Trying to get those details right at GCS call site violates encapsulation.

**Comment by RussTedrake** [comment]
i see.  I believe that suboptimal_x_val should be empty here .... since this codepath is always solving the convex optimization (the suboptimal pools are only for mixed-integer problems)

**Pull request merged**
