### PR TITLE
Polishes test_ik.cc.

### PR DESCRIPTION
**Pull request by liangfok**
For increased readability and safety.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5283)

### CODE REVIEW

**Comment by liangfok** [comment]
Nonfunctional cleanup changes. +@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5283#-:-Kdfp7l3sCR8S68YAtCV:b-p666t4)*

**Comment by jwnimmer-tri** [comment]
Not sure why this test is something anyone is ever looking at anymore, but sure, why not.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/test/test_ik.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5283#-Kdfq_tUK2eRuZaS9yPu:-Kdfq_tVXi0gtPOtVx1U:bqipqzj) ([raw file](https://github.com/robotlocomotion/drake/blob/8205e8931573aca5f94488d8f3a9fa336f61d0bb/drake/multibody/test/test_ik.cc#L40)):*
> ```cpp
>   const WorldCoMConstraint com_kc(model.get(), com_lb, com_ub, tspan);
> 
>   const std::vector<const RigidBodyConstraint*> constraint_array = {&com_kc};
> ```

BTW _Meta_ nit: the `=` is weird here; conventional phrasing would be just `...array{&com...};`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5283#-:-KdfqteXZGx7NtERduRg:bo1shen)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/test/test_ik.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5283#-Kdfq_tUK2eRuZaS9yPu:-Kdfs_WuMtiYvZ9o7dUl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8205e8931573aca5f94488d8f3a9fa336f61d0bb/drake/multibody/test/test_ik.cc#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ nit: the `=` is weird here; conventional phrasing would be just `...array{&com...};`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5283)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5283)*

**Pull request merged**
