### PR TITLE
Test IPOPT superbuild on mac

### PR DESCRIPTION
**Pull request by sammy-tri**
Test PR to what issues my current IPOPT build integration has on Mac.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2429)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
Something in this PR is deeply broken.  I'm closing it until github starts showing me a sane state for the branch it's based on.

**Comment by jamiesnape** [comment]
https://status.github.com

**Pull request closed without merging**
