### PR TITLE
[pydrake] Restore history to geometry bindings

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
In PR #15859, an accident killed the history of `pydrake/geometry_py.cc` and `pydrake/test/geometry_test.py`. This contains multiple commits  (including multiple merge commits) whose purpose is to create `pydrake/geometry_py_all.cc` and `pydrake/test/geometry_all_test.py` which carry that lost history.

The last commit finishes the work of replacing the old files with the new in the build system. Moving forward, the new files carry inheritable history that can contribute to the decomposition.

Incidentally, this also restores the changes from #15856. The superfluous `FakeId` in the bindings had been restored during the breakout and this restores it to the post #15856 state.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15879)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Update:

One more change in the diff:

in `geometry_all_test.py` the `#include` for `geometry_py.h` had to move in file location to make the `drakelint`er happy. It'll move back up when all is said and done and `geometry_py_all.cc` becomes `geometry_py.cc` again.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15879#-:-MlG4u3A4TCxA7LUAPhK:bvfineb)* status: needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
+(status: commits are properly curated)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I find that particularly amusing as Reviewable clearly treats this operation as a `git mv` of the original file. In the name of moving on with life, I'm going to run with the blame and give up on the follow. I'm going to chalk that up as the cost of screwing up in #15860. At least the blame will report shas.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15879#-:-MlGALM89oJ-fsFNtfG3:b3x7mc7)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), base commit is latest master (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
> At least the blame will report shas.

Yup, that was my thought as well.

**Pull request merged**
