### PR TITLE
Add InCollisionConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As mentioned in #20109, currently when we want to find an in-collision posture, we use the MinimumDistanceConstraint which impose `minimum_distance_upper`. The formulation of this constraint isn't correct. It ignores any distance that is larger than `influence_distance`, which is good if we want to impose not-in-collision constraint because a pair of geometry with distance larger than `influence_distance` automatically satisfies the not-in-collision constraint, and hence can be safely ignored. On the other hand, if we want to find an in-collision posture, then we should consider the pair of geometry if the distance is larger than `influence_distance`.

This PR introduces InCollisionConstraint. I also tested it in some nonlinear optimization problem and it performs better than the old MinimumDistanceConstraint when I want to find in-collision posture.

I will deprecate the old `MinimumDistanceConstraint` with `minimum_distance_upper` in a separate PR.

Relates to #18830

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NdNAlBk7LldPJ7DdFVb:b-7vq6ss)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
@RussTedrake if you don't mind, may I delegate this to other reviewers?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NdfLIqc6aZJPKoSabMV:bk5fyd1)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
Sorry Hongkai.  I didn't forget, but it's the first week of the term.  Please do reassign.

**Review by hongkai-dai — COMMENTED** [review]
No worries!

-@RussTedrake +@calderpg-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NdgHtCL1DEO9_TnUmCo:b-ed61v4)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 262 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-NdkxA5M6ss_Bf-4KMvN:-NdkxA5M6ss_Bf-4KMvO:b-uk04pj) ([raw file](https://github.com/RobotLocomotion/drake/blob/26e15fe49d5a278f953a9067416670bb988be031/multibody/inverse_kinematics/minimum_distance_constraint.h#L262)):*
> ```objc
>  is in collision.
>  */
> class InCollisionConstraint final : public solvers::Constraint {
> ```

I think this class should be in its own file (and this should be true for the tests as well). I'm going to hold off on more detailed review comments for now so they aren't associated with code that's been moved.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/minimum_distance_constraint.h` line 262 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-NdkxA5M6ss_Bf-4KMvN:-NdmiC2NAH-EMlIE0AEC:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/26e15fe49d5a278f953a9067416670bb988be031/multibody/inverse_kinematics/minimum_distance_constraint.h#L262)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

I think this class should be in its own file (and this should be true for the tests as well). I'm going to hold off on more detailed review comments for now so they aren't associated with code that's been moved.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
@calderpg-tri , the Woven Alpha team would like to use IRIS and CollisionChecker for their robot. This PR is the first one of a series of PR to enable this feature for them. Do you think the PR is ready for review?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NeONSpkEncxUN0fCZeW:bnw1uns)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
Yes, I plan to get back to my review soon.

I've been thinking about the effects of using a high `influence_distance` on `CollisionChecker` queries. I _think_ it will probably be OK with all of the existing implementations, although it's important to check. Next week I'm going to put together a complement of the `collision_avoidance_benchmark` in anzu to see how well this constraint works with all of the checker implementations we have.

> Reviewed 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NeOXJge4b9ar-o4uxi2:b-4wh0og)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/minimum_value_constraint.h` line 304 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-NeOZr5b06OrxjtJgq2B:-NeOZr5b06OrxjtJgq2C:b-6y33ig) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff295a17a9feecc8bf628c07ffc515c850f2a98b/solvers/minimum_value_constraint.h#L304)):*
> ```objc
>   const double normalizer_;
> 
>   std::function<AutoDiffVecXd(const AutoDiffVecXd&)> value_function_;
> ```

nit I believe these could be `const` as well?

**Review by hongkai-dai — COMMENTED** [review]
Is it possible to use `influence_distance=inf` in `CollisionChecker`? If that is not possible, and we only report distances 
 less than influence_distance (ignoring the distance larger than `influence_distance`), then this `InCollision` constraint will have issues, that it is discontinuous when one of the distance crosses `influence_distance`. We better switch back to `MinimumDistanceConstraint` if CollisionChecker ignores any distance greater than `influence_distance`.

To make it more concrete. If we have a scenario with these pairwise distances
```
distances = [1, 2, 3, 4]
```
and our influence_distance is 2.5. Would it make sense to for CollisionChecker to return
```
[1, 2, 2.5, 2.5]
```
? Currently it just returns `[1, 2]`. 

If we want to keep the current CollisionChecker API (always use a finite `influence_distance`, always ignore the distance larger than `influence_distance`), then I think the solution is not to introduce `InCollisionConstraint` (we can still keep `MinimumValueUpperBoundConstraint`) in this PR. Instead, I will change `MinimumDistanceConstraint` API, to remove its constructor https://github.com/RobotLocomotion/drake/blob/0ffed7e976bcc4de73eb27875c9708560ec83cbb/multibody/inverse_kinematics/minimum_distance_constraint.h#L150-L155
which takes both `minimum_distance_lower` and `minimum_distance_upper`, but uses the same `influence_distance`. In practice, I think when we have both `minimum_distance_lower` and `minimum_distance_upper`, they should use different `influence_distance`. For `minimum_distance_lower` we would want very small `influence_distance`; for `minimum_distance_upper` we should use a much larger `influence_distance`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NeQGMGCAaZgFzDIxfYd:b-zfopke)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by calderpg-tri — COMMENTED** [review]
There are a couple issues here about how `CollisionChecker` implementations behave around `influence_distance`. `influence_distance` serves two roles:

1. As a bound on which potential collision distances are returned (i.e. potential collisions farther away than `influence_distance` + padding are ignored)
2. As part of the gradient blending in `SphereRobotModelCollisionChecker` to consolidate the collision distances returned

Specifically (2) is the reason `influence_distance` is required to be finite, since the blending wouldn't work with non-finite weights. That said, for any realistic environment there is a high finite `influence_distance` value which would work fine. We could simply leave setting the threshold up to the user (e.g. if they have a robot arm like an Iiwa or Panda, a threshold of 2 meters would be more than enough to consider any possible collision).

**However**, there is a problem with interpreting (1) to mean "consider _all_ possible collisions within `influence_distance` + padding" - that's not how all `CollisionChecker` implementations work. `SceneGraphCollisionChecker` and `MbpEnvironmentCollisionChecker` (in anzu) do work that way; potential collisions can be considered at arbitrary distances. `VoxelizedEnvironmentCollisionChecker` (in anzu) does not; if a query point on the robot is outside the bounds of a voxelized signed distance field, there's no way to evaluate collision distance against that signed distance field. So unless the user has been careful to either (a) cover the entire workspace of the robot in a single signed distance field or (b) produce a consistent covering of the environment with multiple signed distance fields, there's still the risk of discontinuity with an arbitrarily high `influence_distance` as the robot moves in and out of signed distance fields that cover different parts of the workspace.

My intuition is that for anything like a robot arm, the user can provide a reasonable value for `influence_distance` and it will probably work fine. For something on a much larger scale, like a mobile robot in a large workspace, it will require more care and/or an alternate approach entirely (e.g. they probably want to consider generating IRIS regions from a visibility graph or the workspace directly).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NefHnXd9EazICaGria0:b-ple6u3)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
I see, thanks Calder for the explanation.

Then I would propose we do the following:
1. In `InCollisionConstraing`, we remove the constructor with CollisionChecker, as the distance from CollisionChecker needs to have a finite influence_distance. I can do it in this PR.
2. In `MinimumDistanceConstraint`, remove the constructor https://github.com/RobotLocomotion/drake/blob/0ffed7e976bcc4de73eb27875c9708560ec83cbb/multibody/inverse_kinematics/minimum_distance_constraint.h#L150-L155 which takes both minimum_distance_lower and minimum_distance_upper, but use a single `influence_distance`. I will do this in my next PR.
3. In `MinimumDistanceConstraint`, add a constructor that takes only `minimum_distance_upper` and a `influence_distance`. Namely if the users want to impose both a lower and an upper bound on the minimum distance, then they have to create two MinimumDistanceConstraint objects, one with `minimum_distance_lower` and `influence_distance1`, another with `minimum_distance_upper` and `influence_distance2`. I will do this in my next PR.

What do you think?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NeiODGcC6wXFxoSON12:ba02hyg)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by calderpg-tri — COMMENTED** [review]
I think having effectively two different minimum distance constraints, one intended for minimum distance `>= lower_bound` and the other intended for `<= upper_bound` is reasonable. I am a little concerned that two forms with the same name and signature, yet different behavior would be confusing. Maybe the right approach is to have the names reflect the behavior (e.g. `MinimumDistanceLowerBoundConstraint` + `MinimumDistanceUpperBoundConstraint`).

If we have both of these forms of minimum distance constraint, do we still need a separate `InCollisionConstraint`?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NejWFxJ8mNwBSNWig9L:b-7ic63g)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> If we have both of these forms of minimum distance constraint, do we still need a separate `InCollisionConstraint`?

I still would like to have `InCollisionConstraint`. The reason is that `MinimumDistanceUpperBoundConstraint` will use a different math. `InCollisionConstraint` doesn't take in `influence_distance`, and hence it doesn't need to use the penalty function as in https://github.com/RobotLocomotion/drake/blob/aa91c8f60e79459bf576d27f5ba04ed05be0acb0/solvers/minimum_value_constraint.h#L12-L22. As a result, InCollisionConstraint is simpler to evaluate and less nonlinear. So I think for cases where we can set `influence_distance` to infinity, I would like to use `InCollisionConstraint`.

> Maybe the right approach is to have the names reflect the behavior (e.g. `MinimumDistanceLowerBoundConstraint` + `MinimumDistanceUpperBoundConstraint`).

That is a good idea, I would like to do that in a separate PR, as this PR is already quite big. Would that be OK with you?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-Nek0Mvm66c1eI0uxeqn:bhal5p)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
@calderpg-tri, please hold off the review on this PR. I am re-creating a new PR that will add MinimumValueUpperBoundConstraint and MinimumDistanceUpperBoundConstraint.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20120#-:-NeoO1WZEu00DY3m7zBh:bjxew8b)* status: LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Pull request closed without merging**
