### PR TITLE
Fix Bug Where Infeasible HPolyhedron with Few Constraints is Tagged as Unbounded

### PR DESCRIPTION
**Pull request by cohnt**
If an HPolyhedron has fewer inequalities than the dimension of the ambient space, it's generally unbounded. The only exception to this case is when a subset of the inequalities are mutually exclusive; then the HPolyhedron is empty, and hence, bounded.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OArv4nX1HMDIJr8PIae:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by sadraddini — COMMENTED** [review]
Left a question on when `dim(A)>0` but you may still have infeasibility. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OArvxab45I_zK5RqCmy:bttpmzb)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.cc` line 683 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArv7Wl2bgpbBoE8WLc:-OArv7Wl2bgpbBoE8WLd:b-4ctb6j) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L683)):*
> ```cpp
> std::optional<bool> HPolyhedron::DoIsBoundedShortcut() const {
>   if (A_.rows() < A_.cols()) {
>     // If A_ has fewer rows than columns, then either the HPolyhedron is
> ```

nit  can you add the comment that this is because the union of rows can be infeasible? 
___
*[`geometry/optimization/hpolyhedron.cc` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArurapC4Zx5XkINeWE:-OArurapC4Zx5XkINeWF:bbd2s42) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L689)):*
> ```cpp
>   Eigen::ColPivHouseholderQR<MatrixXd> qr(A_);
>   if (qr.dimensionOfKernel() > 0) {
>     return false;
> ```

Wouldn't we have the same bug here? Say I create mutually exclusive constraints and make enough copies of them. The dimension of Kernel would be still > 0, but is not really unbounded - it is empty. 
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1760 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArvjHMDgJkjR_o9rG4:-OArvjHN0CSWpS_8zTD7:bxw3pkk) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/test/hpolyhedron_test.cc#L1760)):*
> ```cpp
> 
> GTEST_TEST(HPolyhedronTest, EmptyWithFewConstraints) {
>   // An empty HPolyhedron in R^5, defined by x1 <= -1 and x1 >= 0
> ```

nit Did you mean R^3? and end the comment with period. 
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1767 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArvcaQ3YtqGM0Ea6my:-OArvcaQ3YtqGM0Ea6mz:b-oqpsxh) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/test/hpolyhedron_test.cc#L1767)):*
> ```cpp
>   b(0) = -1;
>   HPolyhedron h(A, b);
>   ASSERT_TRUE(h.IsEmpty());
> ```

nit  replace with `EXPECT_TRUE` as this will not block the rest of the test.

**Review by sadraddini — COMMENTED** [review]
Oops I meant `dim(ker(A))`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OArw9DWE2fbzuiui1JV:b-650jwx)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by cohnt — COMMENTED** [review]
+@sadraddini for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OAs6udTADxTDkaKOsls:b-q6ft4w)* status: 2 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.cc` line 683 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArv7Wl2bgpbBoE8WLc:-OAs6yFV3OtYBhQxYgid:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L683)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit  can you add the comment that this is because the union of rows can be infeasible?
</blockquote></details>

Done.
___
*[`geometry/optimization/hpolyhedron.cc` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArurapC4Zx5XkINeWE:-OAs6z1a0kSZ_XFVoAp6:bb9l5yx) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L689)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Wouldn't we have the same bug here? Say I create mutually exclusive constraints and make enough copies of them. The dimension of Kernel would be still > 0, but is not really unbounded - it is empty.
</blockquote></details>

Good catch. Added a test case for this as well, and fixed the bug here.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1760 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArvjHMDgJkjR_o9rG4:-OAs72kL5YI8f2y2zaAf:bt2vr1b) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/test/hpolyhedron_test.cc#L1760)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit Did you mean R^3? and end the comment with period.
</blockquote></details>

Fixed.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1767 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArvcaQ3YtqGM0Ea6my:-OAs73gZ9z4CCp8BnTic:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/test/hpolyhedron_test.cc#L1767)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit  replace with `EXPECT_TRUE` as this will not block the rest of the test.
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
See the comment on checking IsEmpty for the generic case as well. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OAuEzio9XCJoQ3JACPI:b-shxzl3)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.cc` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArurapC4Zx5XkINeWE:-OAuEUn766Bg6w2IO_51:b9dtjbl) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L689)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Good catch. Added a test case for this as well, and fixed the bug here.
</blockquote></details>

I guess the same bug would still exist for `Stiemke's theorem` as well - note it does not use `b`. You need to check `IsEmpty` no matter what at the beginning. It may be beneficial to restructure the code and add the case to the unit test.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117)* status: 1 unresolved discussion, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/hpolyhedron.cc` line 689 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OArurapC4Zx5XkINeWE:-OAx8hmjBPLs0TvUgQVF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/72249c32f64000f3623b871ad58f8631a0159a99/geometry/optimization/hpolyhedron.cc#L689)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

I guess the same bug would still exist for `Stiemke's theorem` as well - note it does not use `b`. You need to check `IsEmpty` no matter what at the beginning. It may be beneficial to restructure the code and add the case to the unit test.
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by sadraddini** [comment]
+@rpoyner-tri for platform review, please.  

@cohnt Can you remove the "do not merge" label? Is there anything holding you from declaring this as ready to merge?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OAxW52r9TbfPhmCD_Sf:bnfp4nl)* status: 2 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1760 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OAxUJzQ8EfHNqHpZyUc:-OAxUJzQ8EfHNqHpZyUd:b-ri62vy) ([raw file](https://github.com/RobotLocomotion/drake/blob/28a026a518b65da423c2eecbcd150cd5ef460b9f/geometry/optimization/test/hpolyhedron_test.cc#L1760)):*
> ```cpp
> 
> GTEST_TEST(HPolyhedronTest, BoundednessCheckEmptyEdgeCases) {
>   // An empty HPolyhedron in R^3, defined by x1 <= -1 and x1 >= 0. This checks
> ```

nit perhaps we could use fancy unicode for this, but I don't know the correct characters off-hand. Nice, but not a requirement.



_Code quote:_
```cpp
R^3
```
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1778 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OAxSwQe86ae5tqSoTbo:-OAxSwQe86ae5tqSoTbp:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/28a026a518b65da423c2eecbcd150cd5ef460b9f/geometry/optimization/test/hpolyhedron_test.cc#L1778)):*
> ```cpp
>   EXPECT_TRUE(h.IsBounded());
> 
>   // An empty polyheron in R^2, defined by the constraints x1 <= -1, x1 >= 0,
> ```

typo



_Suggestion:_
```cpp
polyhedron
```

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117)* status: 2 unresolved discussions, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1760 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OAxUJzQ8EfHNqHpZyUc:-OAxa_PH2YBwfnXerpxe:b8sk1w6) ([raw file](https://github.com/RobotLocomotion/drake/blob/28a026a518b65da423c2eecbcd150cd5ef460b9f/geometry/optimization/test/hpolyhedron_test.cc#L1760)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit perhaps we could use fancy unicode for this, but I don't know the correct characters off-hand. Nice, but not a requirement.
</blockquote></details>

https://www.compart.com/en/unicode/U+211D

I did `git grep  ℝ` on drake and found quite a few examples. Still, your call.

**Review by cohnt — COMMENTED** [review]
I applied the "do not merge" label because I plan to squash and merge myself -- I want to clean up the commit message when I do so.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-:-OAxuTqiAVLJRidK5sWV:b-maw6pa)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1760 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OAxUJzQ8EfHNqHpZyUc:-OAxulhk6ZMRiRGNkLS7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/28a026a518b65da423c2eecbcd150cd5ef460b9f/geometry/optimization/test/hpolyhedron_test.cc#L1760)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

https://www.compart.com/en/unicode/U+211D

I did `git grep  ℝ` on drake and found quite a few examples. Still, your call.
</blockquote></details>

Done.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 1778 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22117#-OAxSwQe86ae5tqSoTbo:-OAxus4f5z1gi07HLxXw:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/28a026a518b65da423c2eecbcd150cd5ef460b9f/geometry/optimization/test/hpolyhedron_test.cc#L1778)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

**Pull request merged**
