### PR TITLE
[fix_inertia] Add --geom_inertia_role_order flag

### LINKED ISSUE #20691: [fix_inertia] Geometry role order preference unclear from docs; would be nice to specify
**Is your feature request related to a problem? Please describe.**
At present, this is the code that determines order of preference for `fix_inertia`:
https://github.com/RobotLocomotion/drake/blob/e855fbc084ee161ecf5e100bb9f810b9f5789a3c/bindings/pydrake/multibody/_inertia_fixer.py#L575

The docstring / `--help` string is a bit vague on how this resolution works:
https://github.com/RobotLocomotion/drake/blob/e855fbc084ee161ecf5e100bb9f810b9f5789a3c/bindings/pydrake/multibody/fix_inertia.py#L4-L6

It looks like collision geometries have precedence, which may not always be ideal.

**Describe the solution you'd like**
Allow users to specify something like `--geom_inertia_role_order proximity illustration perception` (the current behavior), or better specify (e.g. `--geom_inertia_role_order illustration` to only use visual geometry).

**Describe alternatives you've considered**
To change order, comment out geometry.

**Additional context**
Just for making models.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #20691

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm2Y-L882pvV5K7mCbM:blnryw1)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm3HvJ_7e-TDRdjvWYm:bnfp4nl)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm3Pmnz38aplY0S9z2b:-Nm3Pmnz38aplY0S9z2c:bvryuci) (no related file):*
nit: CI is sad; I don't yet know what went wrong.

___

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm3o_Tk-2JfoJUcQKmb:b-l8xbmn)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/multibody/test/fix_inertia_test.py` line 512 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm3ot9D1D3jOeYsnxxK:-Nm3ot9D1D3jOeYsnxxL:b4ydogw) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/test/fix_inertia_test.py#L512)):*
> ```Python
>             del os.environ[k]
>         for k in self._old_env.keys():
>             os.environ[k] = self._old_env[k]
> ```

I pushed this patch to fix a subtle bug latent in my original code.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm4NSN0E4mf4HLPfTfg:bfvx2sg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm3Pmnz38aplY0S9z2b:-Nm79NWB9BPJj5PS6gkX:by14we1) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit: CI is sad; I don't yet know what went wrong.
</blockquote></details>

Sweet, thanks!

___
___
*[`bindings/pydrake/multibody/test/fix_inertia_test.py` line 512 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm3ot9D1D3jOeYsnxxK:-Nm79Uao7ae8ZAp04Yg0:b-zfh9kw) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/test/fix_inertia_test.py#L512)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I pushed this patch to fix a subtle bug latent in my original code.
</blockquote></details>

OK Awesome, thanks!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending two nits

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm7JSOSEI_r20Lwsrmx:btiv7wj)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/multibody/fix_inertia.py` line 75 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm7HdWp-T6GFs4-sKCG:-Nm7HdWqEFSoqx8QVzpS:bm8m6c9) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/fix_inertia.py#L75)):*
> ```Python
>         for x in _inertia_fixer.GEOM_INERTIA_ROLE_ORDER_DEFAULT
>     ]
>     geom_role_choices_str = ["proximity", "illustration", "perception"]
> ```

nit: not clear why this duplicates the role names -- should initialize from geom_inertia_role_order_str_default or at least use role_to_str() ?
___
*[`bindings/pydrake/multibody/test/fix_inertia_test.py` line 357 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm7ISjn4PI6cB_FhhzI:-Nm7ISjn4PI6cB_FhhzJ:b6gq62n) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/test/fix_inertia_test.py#L357)):*
> ```Python
>         visual geometries.
> 
>         Note that the com
> ```

nit: sentence died prematurely

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`bindings/pydrake/multibody/fix_inertia.py` line 75 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm7HdWp-T6GFs4-sKCG:-Nm7TeS22luJAV18OFeI:b-630g5a) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/fix_inertia.py#L75)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: not clear why this duplicates the role names -- should initialize from geom_inertia_role_order_str_default or at least use role_to_str() ?
</blockquote></details>

Done. I think it's important to distinguish, but switched to using string conversion here + cleaned it up a bit.
___
*[`bindings/pydrake/multibody/test/fix_inertia_test.py` line 357 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-Nm7ISjn4PI6cB_FhhzI:-Nm7TiSeEXf8oucCAPmd:b-qsx7uj) ([raw file](https://github.com/RobotLocomotion/drake/blob/be4dadc1d90b884670a927ad11d77e226b372bb0/bindings/pydrake/multibody/test/fix_inertia_test.py#L357)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: sentence died prematurely
</blockquote></details>

Done. Oops!

**Review by sherm1 — COMMENTED** [review]
Thanks, Eric -- perfect now.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20693#-:-Nm7gW1hCA3LhNkKcwac:b3ucewk)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Pull request merged**
