### PR TITLE
[geometry/dev] rename RenderClientGltf => RenderEngineGltfClient

### PR DESCRIPTION
**Pull request by svenevs**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16609)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: +@zachfang for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16609#-:-Mw3RyPT1i2goCdTEtYy:b2eh109)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

___
*[geometry/render/dev/render_client.h, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16609#-Mw3S8nh32Xj3Vt_LqZv:-Mw3S8nh32Xj3Vt_LqZw:bes1qfl) ([raw file](https://github.com/robotlocomotion/drake/blob/2e9fddfcd2bb08d4bd4d82d8fbdb8bf361396a78/geometry/render/dev/render_client.h#L29)):*
> ```objc
> #ifdef DRAKE_DOXYGEN_CXX
>   // Note: the copy constructor operator is actually protected to serve as the
>   // basis for implementing the DoClone() method of derived classes.
> ```

FYI sneaking this in since I noticed it, `RenderClient` does not have `DoClone`, but this is required for the current structure of multiply inheriting.  If that changes in the future we can update and/or delete this comment.
___
*[geometry/render/dev/render_engine_gltf_client.cc, line 85 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16609#-Mw3Sd5FAJ9nztPFuGMi:-Mw3Sd5FAJ9nztPFuGMj:boyfrsa) ([raw file](https://github.com/robotlocomotion/drake/blob/2e9fddfcd2bb08d4bd4d82d8fbdb8bf361396a78/geometry/render/dev/render_engine_gltf_client.cc#L85)):*
> ```cpp
>   throw std::runtime_error(fmt::format(
>       "RenderEngineGltfClient: unspported internal ImageType of '{}'.",
>       image_type));
> ```

FYI this and most of the other changes are a result of `clang-format-9` but otherwise, it's just renaming things and then format due to name size change.
___
*[geometry/render/dev/render_engine_gltf_client_factory.cc, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16609#-Mw3SttuCUnr8Ve9ypI2:-Mw3SttuCUnr8Ve9ypI3:b-lckcqr) ([raw file](https://github.com/robotlocomotion/drake/blob/2e9fddfcd2bb08d4bd4d82d8fbdb8bf361396a78/geometry/render/dev/render_engine_gltf_client_factory.cc#L11)):*
> ```cpp
> std::unique_ptr<RenderEngine> MakeRenderEngineGltfClient(
>     const RenderEngineGltfClientParams& params) {
>   return std::make_unique<RenderEngineGltfClient>(params);
> ```

FYI locally and on GH git reports this as a file deletion of `geometry/render/dev/render_client_gltf_factory.cc` and addition of `geometry/render/dev/render_engine_gltf_client_factory.cc` I suspect because of the amount of changes, even though it was achieved via `git mv`.

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: Thanks, Stephen!

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16609#-:-Mw52PEk37Nj3G5E-zUb:but8hm4)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

___
*[geometry/render/dev/render_engine_gltf_client_factory.cc, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16609#-Mw3SttuCUnr8Ve9ypI2:-Mw52EYfEqGVYNdntkIY:blm3lds) ([raw file](https://github.com/robotlocomotion/drake/blob/2e9fddfcd2bb08d4bd4d82d8fbdb8bf361396a78/geometry/render/dev/render_engine_gltf_client_factory.cc#L11)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI locally and on GH git reports this as a file deletion of `geometry/render/dev/render_client_gltf_factory.cc` and addition of `geometry/render/dev/render_engine_gltf_client_factory.cc` I suspect because of the amount of changes, even though it was achieved via `git mv`.
</blockquote></details>

OK. Reviewable seems to handle that nicely.

**Review by svenevs — COMMENTED** [review]
+@sammy-tri for platform review please (the change outside of `dev/`) is `RenderEngineVtk`'s friend class name changes as a result.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16609#-:-Mw7C_xjEcs1zICrgmAB:bsisy8c)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform on friendship changes.

+@jwnimmer-tri -@sammy-tri 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16609#-:-Mw7IoPoAsi5VWpfrHNg:bwdz9o4)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang (waiting on @svenevs)

**Pull request merged**
