### PR TITLE
Remove linkstatic boilerplate ala 5157

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5259)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review please, as you are familiar with the #5157 idea already.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5259#-:-Kda6tfNEg9KmhB4mvdW:b-e97lia)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5259#-:-KdaUwIqVhinlIHjmuZD:bnfp4nl)*

**Comment by david-german-tri** [comment]
"automotive LGTM missing" - WAI!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5259#-:-KdaV5i1PRGOgrwfazEh:b-swdxmt)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5259)*

**Comment by jwnimmer-tri** [comment]
:lgtm: Ship it!

**Pull request merged**
