### PR TITLE
MathematicalProgram get solution from MathematicalProgramResult

### PR DESCRIPTION
**Pull request by hongkai-dai**
As we discussed in #9633 , `MathematicalProgram` will be const during `Solve`. So the decision variable values cannot be stored inside `MP`, but will be stored in `MPResult`. Hence we need a function to retrieve the value of variable(s) from `MPResult`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9840)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Did you mean to "Squash and merge" button after removing the label?

**Comment by hongkai-dai** [comment]
@jwnimmer-tri yes I just squashed and merged. Should I change the squash the commits locally on my machine and push it to the origin, instead of squashing it on github?

**Comment by jwnimmer-tri** [comment]
What you did is fine.  The 40-minute gap between removing the label and merging was unusual.  It means that any Drake Developer passing by could accidentally merge it without squashing.

**Comment by hongkai-dai** [comment]
Got it. I was trying to merge the PR when I removed the label, and then I realized that the CI hasn't finished yet. I will remove the label just before merging next time.

**Pull request merged**
