### PR TITLE
Fix pow() AutoDiff overload logic

### LINKED ISSUE #7427: Fix and re-enable PowEmptyExponentDerivative case
PR #7425 disabled a test, because it broken the Mac Sierra builds.  (Notably did _not_ break Ubunutu nor El Capitan.)  We should revisit what was failing on Sierra, and re-enable the test with an appropriate fix.

### PR DESCRIPTION
**Pull request by jadecastro**
Resolves #7427.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7426)

### CODE REVIEW

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-continuous-release please

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-continuous-everything-release-bazel please

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by jadecastro** [comment]
+@jwnimmer-tri for all review, please - pending the CI result.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7426#-:-KyTL83E7tYTFQRM1e-m:b-mc8c2l)*

**Comment by soonho-tri** [comment]
Just tested it locally on my mac (running 10.13). Test target is `//drake/common:autodiff_overloads_test`.

Debug build: no problem.
Release build: A test failure.
```
[ RUN      ] AutodiffOverloadsTest.PowEmptyExponentDerivative
drake/common/test/autodiff_overloads_test.cc:132: Failure
Value of: CompareMatrices(Vector1d{0.}, z.derivatives())
  Actual: false (NaN missmatch at (0, 0):
m1 =
0
m2 =
nan)
Expected: true
```

**Comment by jwnimmer-tri** [comment]
Aha.  `ygrad` is not initialized by the unit test.  It needs to be forced to zero.

**Comment by jadecastro** [comment]
Thanks @jwnimmer-tri! Let's try this.

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
@jadecastro , I think the problem is gone now. 👍

**Comment by jadecastro** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7426#-:-KyTR6r6Uz5aMDsXI6OR:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Three of the four Mac variants have passed, the other one fell behind in the queue and will be a while.  I'm going to call us good enough to merge onto master.  I'd like to have all of the nightlies pick this up.

**Pull request merged**
