### PR TITLE
Revert "Check that GRB_LICENSE_FILE and MOSEKLM_LICENSE_FILE are set"

### PR DESCRIPTION
**Pull request by avalenzu**
This reverts commit 41ec0bfb9562635e9895a0fa32612288d1402436 (the second commit in #8619). The first commit in that PR is needed for CI.

Dear @jamiesnape ,

The on-call build cop, @avalenzu, believes that your PR #8619 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failure under investigation is:
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-xenial-clang-bazel-nightly-memcheck-ubsan-everything/254/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8646)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jamiesnape for review.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8646#-:-LAYPKC22BjHzJuO64JD:bjno0iw)*

**Comment by jamiesnape** [comment]
@hongkai-dai We should probably revert the revert before adding your commit. Maybe open a new PR?

**Comment by hongkai-dai** [comment]
Just reverted my commit. 
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
#8647 should fix this issue.

**Comment by avalenzu** [comment]
+@sherm1  for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8646#-:-LAZBmiO1koQJZ_fLTII:bsmjgg)*

**Comment by sherm1** [comment]
Platform rubber stamp for revert :( :lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8646#-:-LAZChWT3Py35q6kvyVg:b1cfyn2)*

**Pull request merged**
