### PR TITLE
[examples] Finish documenting the hardware_sim example

### LINKED ISSUE #17112: Add hardware_station_simulation capability
Details to follow.

(Cross-reference for Anzu issue 8760.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fold the sample data into a single file. Nested model directives are interesting, but not the purpose of this example.

Switch the sample files to MIT-0 license, so that people who copy it don't need to preserve our BSD-3-Clause license text.

---

Closes #17112.

You can see a preview of the README here:

https://github.com/jwnimmer-tri/drake/blob/hardware-sim-example/examples/hardware_sim/README.md#standalone-robot-simulations

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

**Review by zachfang — COMMENTED** [review]
:lgtm: ran the example locally.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-:-NPlvu020tszBIXdhQmU:bqdq1e3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/README.md` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPltzgB-hJUsERoMDRf:-NPltzgCCp52QGmumMuM:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L7)):*
> ```Markdown
> configuration fragments to set up and run your own robot simulation.
> 
> The example shows how to simulate a robot where joint commands message arrive
> ```

nit.



_Suggestion:_
```Markdown
joint command messages
```
___
*[`examples/hardware_sim/README.md` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPlu9NpD2VZwBlT6nBv:-NPlu9NpD2VZwBlT6nBw:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L11)):*
> ```Markdown
> messages and simulated camera image messages.
> 
> The same demo is implemented both Python and C++, for reference.
> ```

nit.



_Suggestion:_
```Markdown
The same demo is implemented in both Python and C++, for reference.
```
___
*[`examples/hardware_sim/README.md` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPluk7fDIRHy257HG4H:-NPluk7fDIRHy257HG4I:b-2fbrse) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L16)):*
> ```Markdown
> ## Running the demo
> 
> The demo is not installed as part of Drake releases. We expect and encourage you
> ```

FYI. I wonder if we should move this down to the `Running the Python demo from a Drake binary release` section as it's only relevant for people with an installed Drake.



_Code quote:_
```Markdown
The demo is not installed as part of Drake releases. We expect and encourage you
to copy these files into your own projects and customize them there.
```
___
*[`examples/hardware_sim/README.md` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPlvFEQ-7h1suW-7H-b:-NPlvFEQ-7h1suW-7H-c:b-u50tky) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L55)):*
> ```Markdown
> 
> Note that the demo its pretty boring on its own! The robot is uncommanded, so
> nothing is happening. All you'll see is the scene geometry, along with a display
> ```

FYI. Similarly, should we bubble this up to the top, i.e., the `Running the demo` section?



_Code quote:_
```Markdown
Note that the demo its pretty boring on its own! The robot is uncommanded, so
nothing is happening. All you'll see is the scene geometry, along with a display
of the contact forces (green arrows).
```

**Review by zachfang — COMMENTED** [review]
One observation when running the example. I need to use `kill PID` to terminate the `demo_py` process in the terminal, while it's not the case for `demo_cc`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-:-NPmCvI33V9KQzmgT7jc:b-3ur3f3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-:-NPmim_nBenv4aIqjmoD:b-6cxuoj)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @zachfang)

___
*[`examples/hardware_sim/README.md` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPluk7fDIRHy257HG4H:-NPmiY5u0wBkrBM3Z1DY:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L16)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

FYI. I wonder if we should move this down to the `Running the Python demo from a Drake binary release` section as it's only relevant for people with an installed Drake.
</blockquote></details>

Done.
___
*[`examples/hardware_sim/README.md` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPlvFEQ-7h1suW-7H-b:-NPmiciF7zR7V89IXZgm:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d3d7d3f3fdeae326836113fd445e683ec876b1d5/examples/hardware_sim/README.md#L55)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

FYI. Similarly, should we bubble this up to the top, i.e., the `Running the demo` section?
</blockquote></details>

Done.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`examples/hardware_sim/README.md` line 13 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPn8bEXAeemAb6JyOyp:-NPn8bEY2nbqtl8D_TMW:b37o6kt) ([raw file](https://github.com/RobotLocomotion/drake/blob/6786835a1353fc9d109888c3eaeb33e9f87dc017/examples/hardware_sim/README.md#L13)):*
> ```Markdown
> The same demo is implemented in both Python and C++, for reference.
> 
> Note that the demo its pretty boring on its own! The robot is uncommanded, so
> ```

nit. Just spotted this one.



_Suggestion:_
```Markdown
is
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-:-NPsM0fp-y8-bv4IpiPU:bmxilld)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`examples/hardware_sim/README.md` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPsLpCB6gnxzlc7Nnhh:-NPsLpCC1DkqlkAM1KHT:b-rnoq24) ([raw file](https://github.com/RobotLocomotion/drake/blob/6786835a1353fc9d109888c3eaeb33e9f87dc017/examples/hardware_sim/README.md#L2)):*
> ```Markdown
> 
> # Standalone Robot Simulations
> ```

BTW: Everything except the README file is mit-0? Any reason to omit this file?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18908)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),zachfang (waiting on @SeanCurtis-TRI and @zachfang)

___
*[`examples/hardware_sim/README.md` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18908#-NPsLpCB6gnxzlc7Nnhh:-NPsMejwCc23rjYkGB2l:b-8me9oy) ([raw file](https://github.com/RobotLocomotion/drake/blob/6786835a1353fc9d109888c3eaeb33e9f87dc017/examples/hardware_sim/README.md#L2)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW: Everything except the README file is mit-0? Any reason to omit this file?
</blockquote></details>

The files that users should copy are MIT-0.
The files that users should not copy (BUILD, README, test/**) are not.

**Pull request merged**
