### PR TITLE
Updates Acrobot Spong demo to use new libdrakeLcmSystem library.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4996)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4996#-:-KbqM_PnYqZjrOqmYJtr:bcv4nxl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4996#-:-KbqNUELBCq-GCT9p3Hj:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
We can override-merge as soon as one relevant build runs to completion.

**Comment by liangfok** [comment]
I believe this PR is ready for override merge since it passed `linux-gcc-ninja-experimental` among others.

**Comment by jwnimmer-tri** [comment]
Right-o.

**Pull request merged**
