### PR TITLE
buildifier: Permit running from anywhere (namely its own parent directory)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Super small change, had just ran into this when testing out `buildifier.sh`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6106)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature / platform review (since it's small)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-:-KkD96pWSZUnLosRMy6Q:bos1tkt)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Adding ` $(pwd)` would have also worked, but this should be

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkDIvqCzKXQQeHH7DaG:bskkg1n) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
> ```Shell
> else
>   echo "Applying buildifier to everything! This may take a moment..."
>   find "$workspace" \
> ```

I have been thinking about this line a lot recently.

By default, should we fix all files under the `bazel info workspace` of this script, or the `bazel info workspace` of the user's current working directory?  Or fail-fast if they differ (but don't complain when cwd is not a workspace).  Or take a workspace path on the command-line, but when absent default to "current workspace" when cwd and $0 agree?

It seems like an appropriate time to fix that now, since the line this PR changes is tied up in the correctness of the UX we choose.

I _think_ my preference is that we have `$buildifier_workspace` and `$target_workspace` as separate concepts:
- No matter what, the `$buildifier_workspace` is as per this PR's repair -- chdir into `$0` and ask. 
- The user can still pass specific filenames to reformat, in which case `$target_workspace`  is irrelevant (not computed) .
- Otherwise, the `$target_workspace` can be passed as a single positional argument, and we'll reformat everything within it without any other directory-interlock checks.  (Possibly it should accept a non-root directory name, and reformat only the files withing that subdirectory tree?)
- Otherwise (when there are no arguments passed to this script), we try to provide a reasonable default.  If the cwd `$(bazel info workspace)` exists and is identical to `$buildifier_workspace`, then we default `$target_workspace` to it; otherwise, error.

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-:-KkDIgzGkET4Qg00PkxG:b-wmjsw5)*

**Comment by EricCousineau-TRI** [comment]
*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkDNDy5FhOgxJGSfh3m:bh8s3g1) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I have been thinking about this line a lot recently.

By default, should we fix all files under the `bazel info workspace` of this script, or the `bazel info workspace` of the user's current working directory?  Or fail-fast if they differ (but don't complain when cwd is not a workspace).  Or take a workspace path on the command-line, but when absent default to "current workspace" when cwd and $0 agree?

It seems like an appropriate time to fix that now, since the line this PR changes is tied up in the correctness of the UX we choose.

I _think_ my preference is that we have `$buildifier_workspace` and `$target_workspace` as separate concepts:
- No matter what, the `$buildifier_workspace` is as per this PR's repair -- chdir into `$0` and ask. 
- The user can still pass specific filenames to reformat, in which case `$target_workspace`  is irrelevant (not computed) .
- Otherwise, the `$target_workspace` can be passed as a single positional argument, and we'll reformat everything within it without any other directory-interlock checks.  (Possibly it should accept a non-root directory name, and reformat only the files withing that subdirectory tree?)
- Otherwise (when there are no arguments passed to this script), we try to provide a reasonable default.  If the cwd `$(bazel info workspace)` exists and is identical to `$buildifier_workspace`, then we default `$target_workspace` to it; otherwise, error.

Thoughts?

</blockquote></details>

Hmm... So the different invocations could look something like this?

```bash
$ cd $DRAKE
$ ./tools/buildifier.sh                 # Reformat Bazel files under $DRAKE
$ ./tools/buildifier.sh drake/solvers   # Reformat Bazel files  under $DRAKE/drake/solvers
$ ./tools/buildifier.sh WORKSPACE       # Murder $DRAKE/WORKSPACE
$ cd ~/outside/bazel-repo
$ $DRAKE/buildifier.sh                  # ERROR: Need directory or arguments specified
$ $DRAKE/buildifier.sh .                # Reformat Bazel files under $PWD
$ $DRAKE/buildifier.sh //...            # Reformat Bazel files under $(bazel info workspace)
$ $DRAKE/buildifier.sh WORKSPACE        # Reformat specific file
```
Seems like it could be done - if `[[ $# -eq 1 && -d $1 ]]`, then we can set `workspace=$1` and `shift`.
If `[[ $# -eq 1 && $1 = "//..." ]]`, then we can set `workspace=$(bazel info workspace)` and `shift`.

Otherwise, things operate as normal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by jwnimmer-tri** [comment]
*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkDaqLl-Hm_ZwbcRJBT:b-hs3gi0) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
I agree with the first half.  My mental model though only accepts filepaths, not labels, so:

> $ $DRAKE/buildifier.sh                  # ERROR: Need directory or arguments specified

Yup.

> $ $DRAKE/buildifier.sh .                # Reformat Bazel files under $PWD

If an only if `$(cd . && bazel info workspace)` succeeds.  In other words, only if `.` has a Bazel WORKSPACE file to anchor it.  If no WORKSPACE, then error.

> $ $DRAKE/buildifier.sh //...            # Reformat Bazel files under $(bazel info workspace)

Error (not a filename or pathname).

> $ $DRAKE/buildifier.sh WORKSPACE        # Reformat specific file

Succeeds, without even checking `$(bazel info workspace)` on the argument, because the argument is a file, not  a directory.

Also one more case to call out:
> $ cd $DRAKE/drake/common
> $ .../../tools/buildifier.sh

Should this reformat only files under common, or all files in the workspace?  On master, its the latter, which I guess is OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by EricCousineau-TRI** [comment]
*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkDgTYim3B86zT-Crl-:b4e71cy) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
> If an only if $(cd . && bazel info workspace) succeeds. In other words, only if . has a Bazel WORKSPACE file to anchor it. If no WORKSPACE, then error.

TBH, I think it may be confusing (and permit less control, make things more complex, etc.) to constrain things to jump to a `bazel` workspace root when explicitly given an argument.
(Thinking of how `git` does things, e.g., `git checkout [<REV_SPEC>]` changes the entire repository branch, while `git checkout [<PATH_SPEC>]` only affects the supplied paths.

If the scope of `buildifier.sh` is to (a) wrap the original `buildifier` with `find` to discriminate what files to use, and (b) by default reformat all of `drake`, then I think the easiest route would have the syntax form be:
```bash
$ buildifier.sh <OPTS>             # Operate on `drake-distro`'s workspace root, ONLY if PWD == drake-distro root)
    # Equivalent to: $ buildifier.sh $(bazel info workspace)   # (within drake-distro)
$ buildifier.sh <OPTS> <FILES>     # Operate on supplied directory, using `find`.
```

This permits a mixture of files and directories, since it is passed through to `find`.

It also permits something like:

```bash
$ tools/buildifier.sh -mode=check   # Check, rather than fix, drake stuff (not that the output is easy to parse)
```

And sorry for the code dump, but can't think of a good pseudo-code explanation:

```bash
# Collect options
buildifier_opts=
while [[ $# -gt 0 && $1 -eq -* ]]; do
    buildifier_opts=$buildifier_opts $1
    shift
done
if [[ -z $buildifier_opts ]]; then
    buildifier_opts="-mode=fix"
fi

find_exclude=""
find_include="\( -name BUILD -o -name '*.BUILD' -o -name '*.bzl' \) -print"
if [[ $# -eq 0 ]]; then
    # Prune third_party/ and externals/ only when run when no files are specified
    buildifier_workspace=$(cd $(dirname $0) && bazel info workspace)
    if [[ $PWD != $buildifier_workspace ]]; then
        echo "Some informative message with usage options"
        exit 1;
    fi
    find_exclude="\( -name third_party -o -name externals \) -prune -o"
    files=$(bazel info workspace)
else
    # Sort into files and directories
    # That way, `find` does not filter out explicitly supplied file names.
    dir_list=""
    file_list="$*" # Or whatever the right syntax is, if we care about spaces.
    for f in "$*"; do
        if [[ -d $f ]]; then
            dir_list="$dir_list $f"
        elif [[ -f $f ]]; then
            file_list="$file_list $f"
        else
            # Add some warning about it being a bad file / dir name
        fi
    done
fi

xargs $(find $dir_list $find_exclude $find_include && echo $file_list) | bazel run .../buildifier $buildifier_opts 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by jwnimmer-tri** [comment]
*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkDzAms60B2VJ4UHo4l:b-xhqtes) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

> If an only if $(cd . && bazel info workspace) succeeds. In other words, only if . has a Bazel WORKSPACE file to anchor it. If no WORKSPACE, then error.

TBH, I think it may be confusing (and permit less control, make things more complex, etc.) to constrain things to jump to a `bazel` workspace root when explicitly given an argument.
(Thinking of how `git` does things, e.g., `git checkout [<REV_SPEC>]` changes the entire repository branch, while `git checkout [<PATH_SPEC>]` only affects the supplied paths.

If the scope of `buildifier.sh` is to (a) wrap the original `buildifier` with `find` to discriminate what files to use, and (b) by default reformat all of `drake`, then I think the easiest route would have the syntax form be:
```bash
$ buildifier.sh <OPTS>             # Operate on `drake-distro`'s workspace root, ONLY if PWD == drake-distro root)
    # Equivalent to: $ buildifier.sh $(bazel info workspace)   # (within drake-distro)
$ buildifier.sh <OPTS> <FILES>     # Operate on supplied directory, using `find`.
```

This permits a mixture of files and directories, since it is passed through to `find`.

It also permits something like:

```bash
$ tools/buildifier.sh -mode=check   # Check, rather than fix, drake stuff (not that the output is easy to parse)
```

And sorry for the code dump, but can't think of a good pseudo-code explanation:

```bash
# Collect options
buildifier_opts=
while [[ $# -gt 0 && $1 -eq -* ]]; do
    buildifier_opts=$buildifier_opts $1
    shift
done
if [[ -z $buildifier_opts ]]; then
    buildifier_opts="-mode=fix"
fi

find_exclude=""
find_include="\( -name BUILD -o -name '*.BUILD' -o -name '*.bzl' \) -print"
if [[ $# -eq 0 ]]; then
    # Prune third_party/ and externals/ only when run when no files are specified
    buildifier_workspace=$(cd $(dirname $0) && bazel info workspace)
    if [[ $PWD != $buildifier_workspace ]]; then
        echo "Some informative message with usage options"
        exit 1;
    fi
    find_exclude="\( -name third_party -o -name externals \) -prune -o"
    files=$(bazel info workspace)
else
    # Sort into files and directories
    # That way, `find` does not filter out explicitly supplied file names.
    dir_list=""
    file_list="$*" # Or whatever the right syntax is, if we care about spaces.
    for f in "$*"; do
        if [[ -d $f ]]; then
            dir_list="$dir_list $f"
        elif [[ -f $f ]]; then
            file_list="$file_list $f"
        else
            # Add some warning about it being a bad file / dir name
        fi
    done
fi

xargs $(find $dir_list $find_exclude $find_include && echo $file_list) | bazel run .../buildifier $buildifier_opts 
```

</blockquote></details>

The simplification of not supporting multiple workspaces is fine; it doesn't meet one of my odd use cases, but I think you're right that my proposal would just confuse everyone else.

The only complaint I have is that I don't think we should accept directory names and hunt through them; it should just accept filenames.  If the user wants hunting behavior, they can write the hunt they care about.  I think "everything" and "the exact files I listed" are plain and clear semantics.

So I think we're back to something like the current PR, just with a slight tweak to the error-checking to fail-fast if you're in some weird current-working-directory unrelated to the tool you've run?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by EricCousineau-TRI** [comment]
*[tools/buildifier.sh, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-KkDIvqCzKXQQeHH7DaF:-KkGtbBwQikyxbf7VEFf:bora6u8) ([raw file](https://github.com/robotlocomotion/drake/blob/9ba2629fad10e04dbaf95a1f1bd7d8bcf0024c7f/tools/buildifier.sh#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The simplification of not supporting multiple workspaces is fine; it doesn't meet one of my odd use cases, but I think you're right that my proposal would just confuse everyone else.

The only complaint I have is that I don't think we should accept directory names and hunt through them; it should just accept filenames.  If the user wants hunting behavior, they can write the hunt they care about.  I think "everything" and "the exact files I listed" are plain and clear semantics.

So I think we're back to something like the current PR, just with a slight tweak to the error-checking to fail-fast if you're in some weird current-working-directory unrelated to the tool you've run?
</blockquote></details>

Yup, that makes sense!

And rather than try to figure out whether or not `$PWD` is under the workspace, I've added a prompt to try and avoid users inadvertently kludging their workspace.

Examples:
```bash
$ ./buildifier.sh                       # Get a prompt
$ ./buildifier.sh -f                    # Reformat without a prompt
$ ./buildifier.sh -h                    # Get help
$ ./buildifier.sh -- -h                 # Get buildifier help
$ ./buildifier.sh -mode=fix WORKSPACE   # Explicitly reformat file
```

This changes the default behavior to permit people to use `-mode=fix` vs `-mode=check`.
I can change that or the overarching opts if you don't like 'em.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by jwnimmer-tri** [comment]
:lgtm: +(status: curate commits before merging) 

I imagine a future where our linting is even more integrated into the build system, that will change this UX, but the ad-hoc questioning is okay until then.

With the new extent of this change, please also get a second reviewer.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-:-KkHHOAVLAS6nIbOGP9F:b-yfsbay)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by EricCousineau-TRI** [comment]
+@rpoyner-tri for additional review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-:-KkTU5ihBubsNnnZNxbK:b-f6oie9)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/buildifier.sh, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-Kkk0khiEiqQfUBUtHGF:-Kkk0khj9GtLIaFHVOxw:bscdfmn) ([raw file](https://github.com/robotlocomotion/drake/blob/4651799793a8b479b0d2be8dac38b30a1a88c2bb/tools/buildifier.sh#L26)):*
> ```Shell
> 
> workspace=$(cd $(dirname $0) && bazel info workspace)
> if [ ! -f "$workspace"/WORKSPACE ]; then
> ```

BTW, this is now the only single-brace condition in the whole file; consider updating it for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-:-Kkk0uwS1_WQo3WVCCli:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/buildifier.sh, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6106#-Kkk0khiEiqQfUBUtHGF:-KklaTx1IJGg7mg-LCvs:boyexb3) ([raw file](https://github.com/robotlocomotion/drake/blob/4651799793a8b479b0d2be8dac38b30a1a88c2bb/tools/buildifier.sh#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, this is now the only single-brace condition in the whole file; consider updating it for consistency.
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6106)*

**Pull request merged**
