### PR TITLE
geometry:optimization Implements IRIS algorithm

### PR DESCRIPTION
**Pull request by RussTedrake**
for compute large convex regions of obstacle-free space.
A big step towards #6243 !

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
This has the commit from #15314 in it, too.  Please only review the second commit here. (e.g. from r1 to r2)
+@hongkai-dai for feature review, please.  I appreciate you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-MdnHaNq6wDjUeBCCJIL:b-ilx5ms)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Hooray! Just a few minor comments.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-MdnjZrO3Bb6L3yijLp3:b-rbn3qe)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @RussTedrake)

___
*[geometry/optimization/iris.cc, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-MdnenpG5NV-eA-vsSox:-MdnenpG5NV-eA-vsSoy:bjuc103) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L33)):*
> ```cpp
> 
>   // Pre-allocate matrices of the maximum size:
>   Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> A(
> ```

I would suggest to document what `A`, `b` matrices represent. The collision-free polytope is represented as `{x | A * x <= b}`
___
*[geometry/optimization/iris.cc, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdng3nj3w8qZ8De3XD_:-Mdng3nj3w8qZ8De3XDa:b-x5fm15) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L58)):*
> ```cpp
>     for (int i = 0; i < N; ++i) {
>       const VectorXd point = closest_points.col(scaling[i].second);
>       // Only add a constraint if this point is still the set that has been
> ```

Should "still the set" be "still within the set"?
___
*[geometry/optimization/iris.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdng_apDH7ltRJubwmY:-Mdng_apDH7ltRJubwmZ:b-c7jt3f) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L67)):*
> ```cpp
>         A.row(num_constraints) =
>             2.0 * E.A().transpose() * E.A() * (point - E.center());
>         A.row(num_constraints).normalize();
> ```

BTW, why do we normalize this vector? I would think the unnormalized version also describes the same halfspace?
___
*[geometry/optimization/test/iris_test.cc, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdnhzf--MezG5yHCSQS:-Mdnhzf--MezG5yHCSQT:b-smdpd8) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/test/iris_test.cc#L51)):*
> ```cpp
> 
>   // The algorithm converges with only the domain defining the region.
>   EXPECT_TRUE(CompareMatrices(region.A(), domain.A()));
> ```

After normalizing each row in the IRIS polytope, region.A() shouldn't be equal to domain.A()?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[geometry/optimization/iris.cc, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-MdnenpG5NV-eA-vsSox:-Mdnstbd5-nlrhWV2NSS:bc4sjck) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L33)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I would suggest to document what `A`, `b` matrices represent. The collision-free polytope is represented as `{x | A * x <= b}`
</blockquote></details>

Done.  Good call.
___
*[geometry/optimization/iris.cc, line 58 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdng3nj3w8qZ8De3XD_:-MdnszjUArRNcklFOIpc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L58)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should "still the set" be "still within the set"?
</blockquote></details>

Done.
___
*[geometry/optimization/iris.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdng_apDH7ltRJubwmY:-MdntTAZ1wtRKFrxFo6x:bsf5weq) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/iris.cc#L67)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, why do we normalize this vector? I would think the unnormalized version also describes the same halfspace?
</blockquote></details>

I agree.  I noticed that Robin had done it here: https://github.com/rdeits/iris-distro/blob/master/src/cxx/iris.cpp#L24 .  So thought he might have run into some numerical reasons to do it.  But looking back at his code, he also avoided multiplying the matrices repeatedly; i've made that tweak here, too.
___
*[geometry/optimization/test/iris_test.cc, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdnhzf--MezG5yHCSQS:-MdnwdDB-Wzgu2stxwP1:bmnqbqz) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/test/iris_test.cc#L51)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

After normalizing each row in the IRIS polytope, region.A() shouldn't be equal to domain.A()?
</blockquote></details>

The first n rows of A,b are the bounding box (for all iterations).  The loop through N possible obstacles adds additional normalized rows to A and b.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @RussTedrake)

___
*[geometry/optimization/test/iris_test.cc, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Mdnhzf--MezG5yHCSQS:-MdnzpI98wsIWWV9bkaX:bqndy1i) ([raw file](https://github.com/robotlocomotion/drake/blob/7d8d2cd105e452fbbc9631a49c395f31f6af8ddd/geometry/optimization/test/iris_test.cc#L51)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The first n rows of A,b are the bounding box (for all iterations).  The loop through N possible obstacles adds additional normalized rows to A and b.
</blockquote></details>

Ah right, I forgot that the first n rows are un-normalized.

**Comment by RussTedrake** [comment]
ftr -- using #15319 and listing mosek, gurobi, then scs (for the conic case) resolves the ipopt issues for me.  I will push that fix here once #15319 lands.

**Review by RussTedrake — COMMENTED** [review]
Just grabbed the new `MakeFirstAvailableSolver` and tests should all pass now with the default solvers.  Hopefully it's ready for tomorrow's platform?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-MdypRyp7vgns2ga_ju7:bjljti0)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 7 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
+@soonho-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-Me-eaxy4G3553V1dcjs:bxwr5c8)* status: LGTM missing from assignees hongkai-dai,soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 3 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315)* status: LGTM missing from assignees soonho-tri(platform),hongkai-dai (waiting on @hongkai-dai and @soonho-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-Me0Ty0l2J4W8CxAkneq:bg7igkv)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 15 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15315#-:-Me0Vbg02XGxAb18DZBU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

___
*[geometry/optimization/test/iris_test.cc, line 87 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15315#-Me0ViJUDyGLmBt99SHq:-Me0ViJUDyGLmBt99SHr:bgdvh8y) ([raw file](https://github.com/robotlocomotion/drake/blob/9720d3f00974ef6358f3251b744741df557a03c0/geometry/optimization/test/iris_test.cc#L87)):*
> ```cpp
> 
> /* Unit ball inside the unit box; IRIS finds a region in the top corner. */
> GTEST_TEST(IrisTest, BallInBox) {
> ```



I love these test cases!

**Pull request merged**
