### PR TITLE
[visualization] Allow adding triad to multibody Frame

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review, please

Minor sugar to add for triad viz

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-:-NrkhpPN-5p6e4d1lbGJ:b-rcp2qv)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
Thanks!  It looks like this might resolve #19983.  I'll take a look as part of my review.

**Comment by EricCousineau-TRI** [comment]
Welcome! I think this only adds the `frame=` argument, but does not attempt to make the names unique.
One option is to make `name: Optional[str] = None`, and have it back out the name according to the passed element:
- if `body`, use the `body.scoped_name().to_string()`
- if `frame`, use `frame.scoped_name().to_string()`
- if `frame_id`, use the equivalent for scoped geom name

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@SeanCurtis-TRI for platform review (de-confliction) please.

> This only adds the `frame=` argument, but does not attempt to make the names unique ...

I _think_ that facet of the issue was re: the `manipulation` repo version of this code, and doesn't apply to Drake.

In any case, I'll take on the remaining work to finish this issue, sometime later.  One other part of the remaining work is to change `model_visualizer` to show the triad on all MbP (offset) frames rather than only MbP bodies.  This PR is a prereq for that feature, but doesn't change those default visualizations yet.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-:-NrkotDI7zjqrDJ3_sBG:b8k3kru)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/visualization/_triad.py` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-NrknxkSC--h_7cpkvcH:-NrknxkSC--h_7cpkvcI:btmdrby) ([raw file](https://github.com/RobotLocomotion/drake/blob/aee2eadd78b6589528082aca3d55c34a3f97d9a9/bindings/pydrake/visualization/_triad.py#L38)):*
> ```Python
>       scene_graph: the SceneGraph where geometry will be added.
>       body: when provided, illustrates the frame of the given body;
>         only of body=, frame=, or frame_id= must be provided.
> ```

typo "only of ..." is not grammatically correct.

I think probably "exactly one of" is the language we're aiming for?

Ditto throughout this file, including the error message on line 59.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Gotcha, sounds good!

> I _think_ that facet [...]

I had to add `name="frame 2"` in `test_redundant_plant_arg` to avoid having conflicting names, so I think it applies in Drake too.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-:-NrkusBaElITGh70k6He:bdici28)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/visualization/_triad.py` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-NrknxkSC--h_7cpkvcH:-NrktLJ07tBkxBCnunJe:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/aee2eadd78b6589528082aca3d55c34a3f97d9a9/bindings/pydrake/visualization/_triad.py#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo "only of ..." is not grammatically correct.

I think probably "exactly one of" is the language we're aiming for?

Ditto throughout this file, including the error message on line 59.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
For MbP, IIRC it already requires that frame names (inclusive of body frame names) must be unique, so I have some home that it will be easy.  _Shrug._

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-:-NrpkYtv3EzCYhU2cKRL:bmxilld)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/visualization/_triad.py` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-NrpjO5yAtMN-yDewh9m:-NrpjO5yAtMN-yDewh9n:b-l1ngb2) ([raw file](https://github.com/RobotLocomotion/drake/blob/938615f17f5df41966a343a809a856c98f2bc9f5/bindings/pydrake/visualization/_triad.py#L45)):*
> ```Python
>         exactly one of body=, frame=, or frame_id= must be provided.
>       plant: MultibodyPlant associated with the given frame_id;
>         required if and only if a frame_id= is being used (not body= or
> ```

BTW This comment doesn't suggest the implemented semantics below. That if you specify body= or frame= *and* a plant=, we're not simply going to ignore the plant, but we're going to require it be the right one.

Seems to me that it should say that if provided, it must match the frame specification (frame_id=, body=, or frame=) and it is *required* for frame_id=.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)* status: 1 unresolved discussion, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)* status: missing label for release notes

___
*[`bindings/pydrake/visualization/_triad.py` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21064#-NrpjO5yAtMN-yDewh9m:-NrpnyhX7VwR6HKjyDWE:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/938615f17f5df41966a343a809a856c98f2bc9f5/bindings/pydrake/visualization/_triad.py#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This comment doesn't suggest the implemented semantics below. That if you specify body= or frame= *and* a plant=, we're not simply going to ignore the plant, but we're going to require it be the right one.

Seems to me that it should say that if provided, it must match the frame specification (frame_id=, body=, or frame=) and it is *required* for frame_id=.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)* status: missing label for release notes

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21064)* status: missing label for release notes

**Pull request merged**
