### PR TITLE
Revert "Add linting for dangling install rules"

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @jwnimmer-tri ,

The on-call build cop, @betsymcphail, believes that your PR #9395 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-highsierra-clang-bazel-continuous-release/1041/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-highsierra-clang-bazel-continuous-everything-release/982/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9418)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by soonho-tri** [comment]
I think the problem is that the added `install_lint` script will run the following bazel-query which fails:

```
bazel query "somepath(//:install, //tools/workspace/dreal:install)"
...
DEBUG: /private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/external/drake/tools/lint/install_lint.bzl:36:9: somepath(//:install, //tools/workspace:install_external_packages)
ERROR: /Users/soonhok/work/drake/tools/workspace/dreal/BUILD.bazel:18:1: no such target '@dreal//:install': target 'install' not declared in package '' defined by /private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/external/dreal/BUILD.bazel and referenced by '//tools/workspace/dreal:install'
ERROR: /Users/soonhok/work/drake/tools/workspace/dreal/BUILD.bazel:18:1: no such target '@dreal//:install': target 'install' not declared in package '' defined by /private/var/tmp/_bazel_soonhok/a9a9c5be1fd1cb3f2dee812ac07be937/external/dreal/BUILD.bazel and referenced by '//tools/workspace/dreal:install'
...
```

I thought that the `@dreal//:install` dependency is hidden in Mac. But it's leaked by the query.

https://github.com/RobotLocomotion/drake/blob/463e95e3c55dd04ea1045650b05628c42cd9072e/tools/workspace/dreal/BUILD.bazel#L16-L24

**Comment by soonho-tri** [comment]
From https://docs.bazel.build/versions/master/query.html#bazel-cquery

> Notably, this means it does not correctly resolve select statements and rather returns all possible resolutions of selects. A newer query environment, cquery, properly handles configurations but doesn't provide all of the functionality of this original query.

**Comment by jamiesnape** [comment]
Closing since we have disabled the tests temporarily in #9421.

**Pull request closed without merging**
