### PR TITLE
Added guard that prevents rigid_body_plant_test from being built if B…

### PR DESCRIPTION
**Pull request by liangfok**
…ullet is not found.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3442)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3442#-:-KRaYXQR_svaHlsvSGB9:bat39iv)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-minimal please

**Comment by liangfok** [comment]
Win32 CI suffered the same flake all other PRs are having tonight. But all tests passed within it:

```
23:17:58 100% tests passed, 0 tests failed out of 100
```

Thus, I believe this PR is ready to be merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3442#-:-KRahJMmXsnzMiddZnqS:bzdvyt8)*

**Comment by jwnimmer-tri** [comment]
Agreed.

**Pull request merged**
