### PR TITLE
Remove DRAKE_EXPORT from util

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Remove DRAKE_EXPORT from util.  This is a portion of #3973.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4063)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
My voice is my passport verify me.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4063#-:-KW16HUyXx_rqTR2Ek4_:b-7ewwmf)*

**Comment by jwnimmer-tri** [comment]
Fixing a flake @drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
I wonder why Jenkins is complaining.

**Comment by jwnimmer-tri** [comment]
-@david-german-tri +@sammy-tri has accepted my invitation to review these.  Thanks!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4063#-:-KW3esjJcp-D4fyPZI5b:b5hsvkr)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4063#-:-KW4524Tnp3qx45Ev0Cw:bnfp4nl)*

**Pull request merged**
