### PR TITLE
doc: Switch website to use Jekyll

### LINKED ISSUE #13832: Reworking Drake's website
We'd like to rework some of the content and style of https://drake.mit.edu/.  As part of this work, we'll probably need to tweak our workflow for hosting some static assets.  This is a tracking issue to explore that topic.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Part of #13832.

Marked "do not merge" until #14695 is done and we want to pull the trigger.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please (next week) -- this is a follow-up to #14587.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: that this correctly alters the documentation build process; opening a discussion item for when to pull the trigger.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708#-:-MUhzTnT9OYMqNhveQy2:bjc7xmr)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14708#-MUi-Db23xOP2cksfDbv:-MUi-Db23xOP2cksfDbw:b3s3jsq) (no related file):*
This interlocks with choosing and completing the necessary parts of #14695 .
(If there are other issues in this interlock set we should note them here as well)

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge" (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14708#-MUi-Db23xOP2cksfDbv:-MUiO0OiA09ufHLszS8m:b-lj1aoc) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This interlocks with choosing and completing the necessary parts of #14695 .
(If there are other issues in this interlock set we should note them here as well)
</blockquote></details>

To my knowledge, the only blocker is the beta testing fixes (#14695).

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14708#-MUi-Db23xOP2cksfDbv:-MUidjjf1EGGfXRtiiM5:b-4ycclq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To my knowledge, the only blocker is the beta testing fixes (#14695).
</blockquote></details>

That is the extent of my knowledge as well.  [this is a trivial comment to try to make reviewable flair happy]

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @ggould-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708)* status: needs at least two assigned reviewers, labeled "do not merge"

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14708#-MUi-Db23xOP2cksfDbv:-MUieMrs1EguWol4OjPM:bpbh47b) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

That is the extent of my knowledge as well.  [this is a trivial comment to try to make reviewable flair happy]
</blockquote></details>

In that case, the "do not merge" label will suffice.

---

**Review by ToffeeAlbina-TRI — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708#-:-MVOM9azE6Npt6WRi5br:bg7igkv)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by ToffeeAlbina-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14708)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Pull request merged**
