### PR TITLE
Kinova j2s6s300 arm

### PR DESCRIPTION
**Pull request by mpatalberta**
The jaco_simulator jaco_controller simulator seems to work with the new j2s6s300_sphere_collision.urdf

The test needs to be added

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14586)

### CODE REVIEW

**Comment by sherm1** [comment]
GitHub says this is > 200,000 lines, presumably due to mesh files. Probably not suited for merging into Drake in its current form.
What is the status and ultimate intention for this PR?

**Comment by mpatalberta** [comment]
Mr. Sherman,
The mesh files are not needed. They are used in ROS.
I ought to have deleted.
Thanks
Patrick

**Comment by mpatalberta** [comment]
Mr. Sherman,

The goal is to get the Kinova driver to correctly work with the Drake system.
I put into my pull all the changed files.
At this point the URDF files work for two of the Kinova robot.
Remaining problem is some where in the path planner in the Kinova example.

Pat,

**Comment by jwnimmer-tri** [comment]
@mpatalberta thanks for your interest here.

What you're done here is open a "pull request", which is an offer to contribute some of your improvements back into the main Drake project.

In this case, we have to decline your offer.  In Drake, we offer a library of tools for analyzing the dynamics of our robots and building control systems for them.

For the jaco arm, Drake incorporates an _example_ that shows how to use the 7dof model.  (Notice that the code changes in this pull request sit within the "examples" top-level folder.)  The purpose of that example is to demonstrate how to interact with a Kinova Jaco arm.  For that purpose, showing only the one robot model is sufficient.  As you worked out on your own, the changes to interact with the 6dof model are straightforward.  Including the 6dof robot model and its demonstration within Drake itself would increase our maintenance cost, without providing much instructional advantage.

We expect that most users of Drake will have their own robot urdf models, own controller programs, etc. as part of their own source code.  Drake is only the building blocks and modeling tools; the actual robot-specific details are mostly up to you.  The "examples" folder in our tree is only for illustration purposes; it is not intended for direct use in production.

**Pull request closed without merging**
