### PR TITLE
[workspace] Build OpenUSD in macOS CI

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20898.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20990)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20990)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
