### PR TITLE
Move caching design document to doxygen

### LINKED ISSUE #7671: Images are not displaying in Drake doxygen
For example: http://drake.mit.edu/doxygen_cxx/group__contact__model.html

This may be due to the drake/drake rename; I'm not sure. In Drake's Doxyfile the image location is given as
```
IMAGE_PATH             = "@DRAKE_WORKSPACE_ROOT@"/drake
```
but doxygen `@image` specifications in current code are given without path names, for example [here](https://github.com/RobotLocomotion/drake/blob/master/multibody/rigid_body_plant/contact_model_doxygen.h#L115):
```
@image html simple_contact.png "Figure 1: Illustration of contact between two spheres."
```
 (The image itself is located in `./images/simple_contact.png` where the doxygen source file is in `./`.) I'm not sure how that used to work (@SeanCurtis-TRI ?).

__Proposal__
- change the IMAGE_PATH to just `"@DRAKE_WORKSPACE_ROOT@"`.
- list the workspace-relative pathname in full, so the above would be
```
@image html multibody/rigid_body_plant/images/simple_contact.png "Figure 1: Illustration of contact between two spheres."
```

### PR DESCRIPTION
**Pull request by sherm1**
(Replaces #7673 -- sorry!)
Per discussion at the on-site with @jwnimmer-tri re PR strategy for caching, I am checking in the caching design and implementation notes document as reviewable doxygen text (it was formerly a Google doc). The idea is that this will make it easier for reviewers, will give us a visible place to reflect design and implementation changes over time, and can be linked to from code to serve as extended "big picture" documentation.

In this PR, I am not looking for a review of the text (which will get updated substantially) but rather the way this is being injected into Drake. I added a mainpage heading "Technical Notes" and a link to this one and an earlier one. To get a figure to show, I modified the Doxygen IMAGE_PATH as discussed in issue #7671, and fixed up all the other @image commands I could find.

Fixes #7671. Relates to #4364.

/cc @jwnimmer-tri @SeanCurtis-TRI @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7674)

### CODE REVIEW

**Comment by sherm1** [comment]
Needs a platform review -- +@jwnimmer-tri please if you are willing and available.

+@SeanCurtis-TRI, I changed how your image files are named in doxygen -- did I break something?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-:-L1UvNSjmREm5Tbpg2e9:bqmd5vw)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/cache_doxygen.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1rNZOztND5LmI3LVhr:-L1rNZOztND5LmI3LVhs:b-i12mrw) ([raw file](https://github.com/robotlocomotion/drake/blob/2a3f7f847b4073afd923c3ee95dfc16275ac68a6/systems/framework/cache_doxygen.h#L1)):*
> ```objc
> //------------------------------------------------------------------------------
> ```

With platform hat on, I am OK with this going into master in draft form, for the reasons cited in the PR overview.  However, it should be clearly labeled as such so that readers know that it is an un-reviewed draft, and there should be a tracking item (open issue) that the document needs (re-)review before considering it done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-:-L1rOFddXQNZyoXb2OvB:bcpz082)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: I noted that you made a particular effort to make sure the cache entities produced valid, readable links. However, that leaves all of the `Context`, `System`, `LeafSystem`, etc., entities out in the cold. Is that what you want to do? Also, do you plan on making them clickable links all the way through?

---

Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/framework/cache_doxygen.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1rZ8X0j2u1W4nHNr3c:-L1rZ8X0j2u1W4nHNr3d:b-yvwrep) ([raw file](https://github.com/robotlocomotion/drake/blob/2a3f7f847b4073afd923c3ee95dfc16275ac68a6/systems/framework/cache_doxygen.h#L110)):*
> ```objc
> /* Looks something like this ...
> 
>                             drake::LeafSystem
> ```

FYI Both here and in the diagram `drake::LeafSystem` is a lie.  I know this spills into "don't review the content", but as I was looking for doxygen-style kinds of things, that jumped out atme.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-:-L1rYqABGwtX6gefahEp:bssaumh)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674)*

**Comment by sherm1** [comment]
I realized that the reason the links don't work is that this pure-doc header is in the global namespace while all the related code is in `drake::systems`. I put the documentation in the right namespace and now all the links work without any `@link` shenanigans. Links to as-yet-nonexistent caching objects don't work, but they will once those are in master.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/framework/cache_doxygen.h, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1rNZOztND5LmI3LVhr:-L1s25Hvs3gniSl5K6kx:b-m7yejw) ([raw file](https://github.com/robotlocomotion/drake/blob/2a3f7f847b4073afd923c3ee95dfc16275ac68a6/systems/framework/cache_doxygen.h#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

With platform hat on, I am OK with this going into master in draft form, for the reasons cited in the PR overview.  However, it should be clearly labeled as such so that readers know that it is an un-reviewed draft, and there should be a tracking item (open issue) that the document needs (re-)review before considering it done.
</blockquote></details>

Warning added at the top, and issue #7681 opened for tracking.

---

*[systems/framework/cache_doxygen.h, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1rZ8X0j2u1W4nHNr3c:-L1s2HljpJs29FnDVSgZ:b8wyghx) ([raw file](https://github.com/robotlocomotion/drake/blob/2a3f7f847b4073afd923c3ee95dfc16275ac68a6/systems/framework/cache_doxygen.h#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI Both here and in the diagram `drake::LeafSystem` is a lie.  I know this spills into "don't review the content", but as I was looking for doxygen-style kinds of things, that jumped out atme.
</blockquote></details>

Done. (Here and in the figure)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-:-L1s2Ns3f3sNzASOHmeJ:b-v0ta0o)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[systems/framework/images/system_context_cache.png, line 0 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1s3EXR2C_dkDpY_Rei:-L1s3EXS7uVoUkJPNdZh:bvgrre9) ([raw file](https://github.com/robotlocomotion/drake/blob/443b1c85f2a8f6351f5c39fa2545adebf74975a6/systems/framework/images/system_context_cache.png#L0)):*
Hmm.  I guess we can wait until the doc review, but this is a raster image.  Shouldn't we be committing the source format into git as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/images/system_context_cache.png, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1s3EXR2C_dkDpY_Rei:-L1s5CunuKMhh3yf7JLe:b1tfk87) ([raw file](https://github.com/robotlocomotion/drake/blob/443b1c85f2a8f6351f5c39fa2545adebf74975a6/systems/framework/images/system_context_cache.png#L)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm.  I guess we can wait until the doc review, but this is a raster image.  Shouldn't we be committing the source format into git as well?
</blockquote></details>

Good point. But ... I drew this in Google Doc's image drawing app. That's also a binary format but can be converted to .svg (which makes it 150K vs the 40K png).  With help from @seancurtis-tri and Inkscape I was able to determine that Google's export-to-.svg produces uneditable text, though that could be repaired (and that should make the .svg smaller also). So currently there is no usable source - I'll add making one as a task in #7681.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/framework/images/system_context_cache.png, line  at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7674#-L1s3EXR2C_dkDpY_Rei:-L1sLvR0zRFZSjHQ3-q2:bply353) ([raw file](https://github.com/robotlocomotion/drake/blob/443b1c85f2a8f6351f5c39fa2545adebf74975a6/systems/framework/images/system_context_cache.png#L)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Good point. But ... I drew this in Google Doc's image drawing app. That's also a binary format but can be converted to .svg (which makes it 150K vs the 40K png).  With help from @seancurtis-tri and Inkscape I was able to determine that Google's export-to-.svg produces uneditable text, though that could be repaired (and that should make the .svg smaller also). So currently there is no usable source - I'll add making one as a task in #7681.
</blockquote></details>

Seemed better to do this now. So Done -- and the .svg is much smaller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7674)*

**Pull request merged**
