### PR TITLE
Mosek also print solution summary.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As explained in https://docs.mosek.com/latest/capi/debugging-tutorials.html#debugging-tutorials to print the solution summary after solving mosek.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528#-:-MvHKYvU63_BiJQp1mbR:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mosek_solver.cc, line 1907 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvKU4r-2_0s8klB4Rkm:-MvKU4r-2_0s8klB4Rkn:bhozoll) ([raw file](https://github.com/robotlocomotion/drake/blob/aac27019c6686010287d4f1e542a192b5d6b3ab5/solvers/mosek_solver.cc#L1907)):*
> ```cpp
>         "file.");
>   } else if (print_to_console) {
>     rescode = MSK_linkfunctotaskstream(task, MSK_STREAM_LOG, nullptr, printstr);
> ```

These will clobber the `rescode` from `AddConeConstraints` (or any of the other helper functions) above.  Do you want to fix that in this PR, or should I open an issue?
___
*[solvers/mosek_solver.cc, line 1952 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvKUb6Y5BFmz0DXx37F:-MvKUb6Y5BFmz0DXx37G:b-82phlc) ([raw file](https://github.com/robotlocomotion/drake/blob/aac27019c6686010287d4f1e542a192b5d6b3ab5/solvers/mosek_solver.cc#L1952)):*
> ```cpp
>     // on printing the solution summary.
>     if (print_to_console || !print_file_name.empty()) {
>       MSK_solutionsummary(task, MSK_STREAM_LOG);
> ```

The `MSK_solutionsummary` returns a rescode.  If we are going to ignore it, then we should do that explicitly for the reader of this code, so it's a clear decision to preserve for the future, rather than a possible accident that might be "corrected".

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[solvers/mosek_solver.cc, line 1907 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvKU4r-2_0s8klB4Rkm:-MvLcFZ47cprbbSp-Q55:b-86tod1) ([raw file](https://github.com/robotlocomotion/drake/blob/aac27019c6686010287d4f1e542a192b5d6b3ab5/solvers/mosek_solver.cc#L1907)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These will clobber the `rescode` from `AddConeConstraints` (or any of the other helper functions) above.  Do you want to fix that in this PR, or should I open an issue?
</blockquote></details>

Done. I added the check on rescode.
___
*[solvers/mosek_solver.cc, line 1952 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvKUb6Y5BFmz0DXx37F:-MvLcPQ_7pK_wZ3FFHfX:b-h1o3ku) ([raw file](https://github.com/robotlocomotion/drake/blob/aac27019c6686010287d4f1e542a192b5d6b3ab5/solvers/mosek_solver.cc#L1952)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `MSK_solutionsummary` returns a rescode.  If we are going to ignore it, then we should do that explicitly for the reader of this code, so it's a clear decision to preserve for the future, rather than a possible accident that might be "corrected".
</blockquote></details>

Done. Good call, I added the check on `rescode`.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528#-:-MvLjafS59WN85RMbFAY:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[solvers/mosek_solver.cc, line 1908 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvLizixEfLtnac-fELG:-MvLizixEfLtnac-fELH:b-id4hee) ([raw file](https://github.com/robotlocomotion/drake/blob/21f9345319d0ebdd06637914c0cda5d2a485c4ec/solvers/mosek_solver.cc#L1908)):*
> ```cpp
>   } else if (print_to_console) {
>     if (rescode == MSK_RES_OK) {
>     rescode = MSK_linkfunctotaskstream(task, MSK_STREAM_LOG, nullptr, printstr);
> ```

nit Needs +2 indentation now that it's surrounded by an if-check



_Suggestion:_
```cpp
      rescode = MSK_linkfunctotaskstream(task, MSK_STREAM_LOG, nullptr, printstr);
```
___
*[solvers/mosek_solver.cc, line 1912 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvLj4f1BNmO1MgUwM-x:-MvLj4f2CrlfFwXzNVf8:b-id4hee) ([raw file](https://github.com/robotlocomotion/drake/blob/21f9345319d0ebdd06637914c0cda5d2a485c4ec/solvers/mosek_solver.cc#L1912)):*
> ```cpp
>   } else if (!print_file_name.empty()) {
>     if (rescode == MSK_RES_OK) {
>     rescode = MSK_linkfiletotaskstream(task, MSK_STREAM_LOG,
> ```

nit Needs +2 indentation now that it's surrounded by an if-check



_Suggestion:_
```cpp
      rescode = MSK_linkfiletotaskstream(task, MSK_STREAM_LOG,
                                         print_file_name.c_str(), 0);
```
___
*[solvers/mosek_solver.cc, line 1957 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16528#-MvLjWpf-H6J-jubHSbT:-MvLjWpf-H6J-jubHSbU:b-id4hee) ([raw file](https://github.com/robotlocomotion/drake/blob/21f9345319d0ebdd06637914c0cda5d2a485c4ec/solvers/mosek_solver.cc#L1957)):*
> ```cpp
>     if (print_to_console || !print_file_name.empty()) {
>       if (rescode == MSK_RES_OK) {
>       rescode = MSK_solutionsummary(task, MSK_STREAM_LOG);
> ```

nit Needs +2 indentation now that it's surrounded by an if-check



_Suggestion:_
```cpp
        rescode = MSK_solutionsummary(task, MSK_STREAM_LOG);
```

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528#-:-MvN8Cfp37rvf3GSUOFK:b8asji7)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16528)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

**Pull request merged**
