### PR TITLE
Don't rely on `system('export ...; cmd')` working

### LINKED ISSUE #1675: Confusion over whether lcmgl can be found
Here's my session:

```
>> addpath_drake
>> testTaskSpaceRRT
 Added the lcm jar to your javaclasspath (found via cmake)
Warning: Currently all of your LCM traffic will be broadcast to the network, because:
'export' is not recognized as an internal or external command,
operable program or batch file.
 
> In checkDependency (line 89)
  In checkDependency (line 100)
  In LCMGLClient (line 3)
  In MotionPlanningTree/setLCMGL (line 305)
  In SE3MotionPlanningTree/setLCMGL (line 65)
  In SE3MotionPlanningTree (line 12)
  In TaskSpaceMotionPlanningTree (line 14)
  In testTaskSpaceRRT (line 133) 
 
 LCMGL not found.  LCMGL support will be disabled.
 To re-enable, add bot2-lcmgl.jar to your matlab classpath using javaaddpath.
 
Error using checkDependency (line 450)
Cannot find required dependency: lcmgl

Error in LCMGLClient (line 3)
  checkDependency('lcmgl');

Error in MotionPlanningTree/setLCMGL (line 305)
      obj.lcmgl = LCMGLClient(name);

Error in SE3MotionPlanningTree/setLCMGL (line 65)
      obj = setLCMGL@CompositeVertexArrayTree(obj, varargin{:});

Error in SE3MotionPlanningTree (line 12)
      obj = obj.setLCMGL('SE3MotionPlanningTree',[0, 0, 0]);

Error in TaskSpaceMotionPlanningTree (line 14)
      obj = obj@CompositeVertexArrayTree({SE3MotionPlanningTree(), ...

Error in testTaskSpaceRRT (line 133)
TA = TaskSpaceMotionPlanningTree(r, 'l_hand', point_in_link_frame);
```

Apparently, lcmgl is both `found via cmake` and also `not found`.

My guess would be the missing `export` command on windows, used in `systemWCmakeEnv`

### PR DESCRIPTION
**Pull request by eric-wieser**
Tries to fix #1675, but only does half the job

### CODE REVIEW

**Comment by tkoolen** [comment]
How did this issue come up?

**Comment by eric-wieser** [comment]
Installation on windows

**Comment by tkoolen** [comment]
Not sure, but I think that Windows doesn't even do anything with LD_LIBRARY_PATH though. Still, I suppose it's better to use the builtin setenv command.

**Comment by eric-wieser** [comment]
Good point, delegating to system directly on windows would have been an easier fix

**Comment by RussTedrake** [comment]
actually, i am pretty certain that this will NOT work.  i played around with this a lot (a long time ago).  setenv will set the path for matlab, but will not set the path for the shell that spawned matlab, and will not effect subsequent system calls.  calling export inline was the only solution.

**Comment by RussTedrake** [comment]
as a simple test, try
```
setenv('foo','bar')
system('echo $bar')
```

**Comment by eric-wieser** [comment]
Shouldn't that read `echo $foo`?

**Comment by RussTedrake** [comment]
yes, of course

**Comment by eric-wieser** [comment]
Works on my machine:

```
>> setenv('foo','bar')
>> system('echo %foo%')
bar
```

But perhaps matlab messes with specifically the variables concerned here

**Comment by RussTedrake** [comment]
I also tried it on my mac, and it worked.  The build servers seem aok with it (despite being generally in bad shape right now); and I agree that windows does not use it.  Any objections to me pulling this in?

**Comment by tkoolen** [comment]
I still don't understand why this is necessary if it fixes an installation issue on Windows while not doing anything on Windows, but I guess it doesn't hurt so I don't object.

**Comment by eric-wieser** [comment]
Does `system` invoke the users shell? With a sufficient wierd (presumably non-posix-compliant) shell, this would also fail

**Comment by tkoolen** [comment]
OK, can we first clear up what this is trying to fix?

**Comment by eric-wieser** [comment]
It's not ok to call `export` on windows, because that command doesn't exist.

Even on another platform, it's not absolutely guaranteed that the user is using a sane shell. Unfortunately, matlab leaves no option but to go via the shell, having not exposed `exec(exe, argc, argv)`

I'm ok with the argument that there should be another conditional branch here for windows, but using setenv still feels cleaner.

**Comment by RussTedrake** [comment]
i think the current version is better.  (going to java directly is the kind of api that does not stay consistent between matlab versions).

**Pull request merged**
