### PR TITLE
Minor fixes to iiwa7 urdf; use iiwa7 in manipulation_station

### LINKED ISSUE #9732: Replace iiwa14 sdf with iiwa7 urdf/sdf in ManipulationStation
And/or optionally take the sdf as an argument in the constructor (since we might want to use different collision model versions, etc)

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #9732

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9857)

### CODE REVIEW

**Comment by Sproulx** [comment]
@RussTedrake I took a closer look at the SDF yesterday to feel more confident about the changes I proposed. The iiwa14 SDF doesn't use the visual offsets that I moved to the link pose in iiwa7. The other thing I noticed is that the inertias in iiwa7 don't look aligned properly when compared to iiwa14. I'm working on getting that sorted out.

**Comment by RussTedrake** [comment]
Resolves #9732

**Comment by Sproulx** [comment]
@RussTedrake the 0.0127m offset is for the mounting plate.

**Comment by Sproulx** [comment]
I overhauled the SDFs for the iiwa7 yesterday using the SDF for the iiwa14 as a template. Just gave it all one more glance to make sure everything looked right.

https://www.dropbox.com/sh/9d3hwu6sq8tihl9/AAATHnnYwlrgz9Wcxp9lq2aha?dl=0

**Comment by RussTedrake** [comment]
@Sproulx -- i've brought in your changes (they are indeed significant changes to inertial props, etc, but you convinced me that you like these better).  I had to change the paths to the mesh files, but otherwise took your changes as-is.

**Pull request merged**
