### PR TITLE
Stop suppressing cpplint whitespace/tab

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix all the current errors, then stop suppressing cpplint whitespace/tab.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri wanted this, so he gets first-pass code review.

**Comment by jwnimmer-tri** [comment]
@drake005 you are broken, I am going to ignore you.

**Comment by rpoyner-tri** [comment]
LGTM.

**Comment by RussTedrake** [comment]
poor drake005 -- you guys are filling up the disk (gets cleared every night).  will work again now, for a least a few hours....

**Pull request merged**
