### PR TITLE
[yaml] Add filename, line, and column to error messages

### LINKED ISSUE #18930: More informative error messages when loading YAML files
**Is your feature request related to a problem? Please describe.**
I am frequently frustrated when loading from YAML files and there is a schema mismatch somewhere. For example:
```
what():  YAML node of type Mapping (with size 2 and keys {foo,bar}) is missing entry for SubSchema foo while accepting YAML node of type Mapping (with size 1 and keys {bar}) while visiting SomeSchema sub_schema.
```

**Describe the solution you'd like**
I would like 2 things:
1. The error message tells me what file is being loaded when this happened.
2. The error message tells me the parse chain where this happened. I.e.; the list of parent nodes traversed to get to this bad node.

**Describe alternatives you've considered**
For part 1; I've sprinkled
```c++
drake::log()->info("Loading schema <identifier I will recognize> from [{}]", file);
```
all over the place so that I see that immediately before the exception text.
For part 2: I don't have a good solution, though often it isn't necessary. Except when it is needed it's often because there are 10+ candidates to look through, once I have the right file.

**Additional context**
The call signature I am using is:
```c++
drake::yaml::LoadYamlFile<Schema>(filename);
```

FYI @ggould-tri per our Slack conversation.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #18930.

+@dmcconachie-tri you get right of first refusal for feature review.  Let me know if you'd like to defer.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952)

### CODE REVIEW

**Review by dmcconachie-tri — COMMENTED** [review]
I'm relatively loaded this week; if you want a quick turn around, that won't be me. Otherwise, I'll get to it next week.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-:-NPwqfrVE2z0uvoUds-y:bfntikn)* status: LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
I'm OK with waiting.  At minimum, I think I'd like your OK that it meets the need, even if you don't take the code review.

**Comment by svenevs** [comment]
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
For the record, the sample from #18930 produces this now:

`.../_tmp/71050efec85ebf33ba9c4b120931b1bc/schema.yaml:3:5: YAML node of type Mapping (with size 1 and keys {int1}) is missing entry for int int2 while accepting YAML node of type Mapping (with size 1 and keys {bottom}) while visiting drake::yaml::test::(anonymous)::BottomLevel bottom while accepting YAML node of type Mapping (with size 1 and keys {middle}) while visiting drake::yaml::test::(anonymous)::MidLevel middle.`

**Review by dmcconachie-tri — COMMENTED** [review]
This meets my needs, but I'd like to defer doing the feature review itself. There is enough going on here that it would take me more time than I feel I have this quarter to properly review these changes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-:-NQXbBwE1IEYPzzMgPsf:b271mb6)* status: LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
No problem!  Thanks for the feedback.

All of @ggould-tri and @sammy-tri and @xuchenhan-tri know this code.  If any if you would like to take over feature review to unlock better yaml error messages, please go ahead.

Otherwise, I'll hand it over to @rpoyner-tri for review next week.

**Review by xuchenhan-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-:-NQbp88LEslvh8_Y2PAc:b-i95o8t)* status: LGTM missing from assignees xuchenhan-tri(platform),dmcconachie-tri (waiting on @dmcconachie-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature :lgtm: with a question about missing marks.

> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-:-NQc-YfGCdl2gqltnZ2h:bsio3mj)* status: 4 unresolved discussions, LGTM missing from assignee dmcconachie-tri (waiting on @dmcconachie-tri and @jwnimmer-tri)

___
*[`common/yaml/yaml_node.h` line 165 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbpOnU-hSTusljkvfD:-NQbpOnU-hSTusljkvfE:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L165)):*
> ```objc
> 
>   /* Sets the filename where this Node was read from. A nullopt indicates that
>   the filename not known. */
> ```

nit



_Suggestion:_
```objc
the filename is not known. */
```
___
*[`common/yaml/yaml_node.h` line 166 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbr9Hs7fDMZP-nK0Ix:-NQbr9Hs7fDMZP-nK0Iy:ba2l800) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L166)):*
> ```objc
>   /* Sets the filename where this Node was read from. A nullopt indicates that
>   the filename not known. */
>   void SetMarkFilename(std::optional<std::string> filename);
> ```

This function name confuses me. Why is it not just `GetFileName`? Is "mark file" the term of art?

Same for the getter.
___
*[`common/yaml/yaml_node.h` line 178 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbpslRAkZHiIyK00QO:-NQbpslSBE_yqpbED6TE:b-rwvs96) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L178)):*
> ```objc
>     int column{};
> 
>     friend bool operator==(const Mark&, const Mark&);
> ```

nit, is this friend declaration needed?
___
*[`common/yaml/yaml_read_archive.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbzUjM4npjruGlp0sm:-NQbzUjM4npjruGlp0sn:btujrnm) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_read_archive.cc#L360)):*
> ```cpp
>   for (auto* archive = this; archive != nullptr; archive = archive->parent_) {
>     if ((archive->root_ != nullptr) &&
>         (archive->root_->GetMark().has_value())) {
> ```

Is it true that the only time the root node isn't marked is when the corresponding YAML node is the of the NodeType Null? 

My concern is that this loop goes far up enough that the mark is far from where the error actually happen. But if the mark is only missing when the node is null, then you can't really go very far without hitting a mark?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`common/yaml/yaml_read_archive.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbzUjM4npjruGlp0sm:-NQc6koR-oN1_hnWLDPo:b89z7sg) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_read_archive.cc#L360)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is it true that the only time the root node isn't marked is when the corresponding YAML node is the of the NodeType Null? 

My concern is that this loop goes far up enough that the mark is far from where the error actually happen. But if the mark is only missing when the node is null, then you can't really go very far without hitting a mark?
</blockquote></details>

My recollection is that the only thing missing a mark is when we're partway through a map, we might localize the error to the opening of the map, instead of the item we're on.

I'll go back and double-check now, though.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-:-NQfqMDZ3E1SFiw8nGpd:b-1krawd)* status: 3 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`common/yaml/yaml_node.h` line 166 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbr9Hs7fDMZP-nK0Ix:-NQfodms85oSqkzQ1XqD:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L166)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This function name confuses me. Why is it not just `GetFileName`? Is "mark file" the term of art?

Same for the getter.
</blockquote></details>

Done.
___
*[`common/yaml/yaml_node.h` line 178 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbpslRAkZHiIyK00QO:-NQfolIoDwpt4LBBrAd9:b-opd6uu) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L178)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, is this friend declaration needed?
</blockquote></details>

Yes.  It's a common way to declare a namespace-scoped binary operator.

https://en.cppreference.com/w/cpp/language/friend#Template_friend_operators
___
*[`common/yaml/yaml_read_archive.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbzUjM4npjruGlp0sm:-NQfq9iM5SNnliC2iSO1:b-1awf3k) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_read_archive.cc#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My recollection is that the only thing missing a mark is when we're partway through a map, we might localize the error to the opening of the map, instead of the item we're on.

I'll go back and double-check now, though.
</blockquote></details>

Done.  I clarified the logic a little bit.  Only "mapish item" archives do not have a mark.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`common/yaml/yaml_node.h` line 178 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbpslRAkZHiIyK00QO:-NQgLwaWDorCrQdjuv8U:b-io9h9k) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L178)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  It's a common way to declare a namespace-scoped binary operator.

https://en.cppreference.com/w/cpp/language/friend#Template_friend_operators
</blockquote></details>

I suppose this is unnecessary (but still customary) as this is a struct not a class? Thanks for reference.
___
*[`common/yaml/yaml_read_archive.cc` line 360 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbzUjM4npjruGlp0sm:-NQgI9FPC9OxpeTMjEi5:b-54avj1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_read_archive.cc#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  I clarified the logic a little bit.  Only "mapish item" archives do not have a mark.
</blockquote></details>

Ok, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18952)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`common/yaml/yaml_node.h` line 178 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18952#-NQbpslRAkZHiIyK00QO:-NQgOnjPDHVCXyIdKgNz:b-z681u0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14792495a2d6c0c41c9c115d7d8097179cfe54f/common/yaml/yaml_node.h#L178)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I suppose this is unnecessary (but still customary) as this is a struct not a class? Thanks for reference.
</blockquote></details>

Yeah.  We don't need the _friendship_ per se, but being able to place the function name at this position in the header file is nicer (IMO).  Otherwise it would buried down near line L300 where it's harder to find.

**Pull request merged**
