### PR TITLE
[multibody] Promote MultibodyPlantConfig out of dev

### LINKED ISSUE #15565: Add MultibodyPlantConfig structure and functions
Similar to [SimulatorConfig](https://drake.mit.edu/doxygen_cxx/structdrake_1_1systems_1_1_simulator_config.html), TRI has a MultibodyPlantConfig to enable for plant configuration via YAML (or similar), instead of multiple direct API calls.

We intend to upstream this utility back into Drake.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #15565.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

+@ggould-tri for extra feature review, as a sanity check from someone involved in the full train of changes.

+@sherm1 for platform review per schedule (tomorrow), please.  Note that this is moving a bunch of files out of `dev`.  Please review those files as if they were newly added from scratch.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826#-:-Mkckr8-ArtieuFJ1tBE:b-n37teh)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826#-:-MkdL3QW7n-KReMQDO02:bg7igkv)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
@sherm1 please have a look?  I could punt this to the next on-call reviewer, but I think it's useful for you to become familiar with these new files / pattern.

**Comment by sherm1** [comment]
Will do.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with some minor requests. Sorry for missing this one earlier.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826#-:-MkmYIT_4BueJbo3zWQs:b-5wuekp)* status: 6 unresolved discussions (waiting on @jwnimmer-tri)

___
*[multibody/plant/multibody_plant.h, line 4802 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmW00J1owb8ImuB7HO:-MkmW00K57UP8Fr8UvmP:bflxaon) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant.h#L4802)):*
> ```objc
>   // The model used by the plant to compute contact forces.
>   // Keep this in sync with the default value in multibody_plant_config.h.
>   ContactModel contact_model_{ContactModel::kPoint};
> ```

minor: consider instead using GetContactModelFromString(). Either make that public or just invoke internal::GetContactModelFromString() here. I'd like to see all four values initialized from the config.
___
*[multibody/plant/multibody_plant_config.h, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmSZTW4gxImUZYr8go:-MkmSZTW4gxImUZYr8gp:b-8ul45e) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant_config.h#L28)):*
> ```objc
>   /// we choose a nominal value as a reasonably conservative estimate that
>   /// works in many cases.
>   double time_step{0.001};
> ```

minor: should note that this default puts MbP in discrete mode and that a time_step of zero is used as a flag to select continuous mode.
___
*[multibody/plant/multibody_plant_config_functions.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmXVYREZQz8VUyJAwh:-MkmXVYREZQz8VUyJAwi:b7fpvr6) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant_config_functions.h#L24)):*
> ```objc
> // Valid string names are listed in MultibodyPlantConfig's class overview.
> // @throws std::exception if an invalid string is passed in.
> ContactModel GetContactModelFromString(std::string_view contact_model);
> ```

minor: per comment in multibody_plant.h I'd like to see this used for initializing the contact model. You could make it public or leave it internal.
___
*[multibody/plant/multibody_plant_config_functions.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmVYxn2wqhVCuhHO_F:-MkmVYxn2wqhVCuhHO_G:bnyqxex) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant_config_functions.cc#L64)):*
> ```cpp
> }
> 
> std::string ContactModelToString(ContactModel contact_model) {
> ```

nit: rename `GetStringFromContactModel()` for consistency with previous function
___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmTOUV-5D-i3bwSMok:-MkmTOUW5MQe23cZGZpj:b-p74mol) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/test/multibody_plant_config_functions_test.cc#L25)):*
> ```cpp
>             ContactModel::kHydroelasticsOnly);
>   // There is no getter for penetration_allowance nor stiction_tolerance, so we
>   // can't test them.
> ```

BTW consider adding those getters in this PR or separately with a TODO here so this can be fully tested (and since they should exist anyway).
___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmX-gk1JTByp3ey5rj:-MkmX-gk1JTByp3ey5rk:bbjyybk) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/test/multibody_plant_config_functions_test.cc#L43)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(GetContactModelFromString("foobar"),
>                               ".*Unknown.*foobar.*");
> }
> ```

Is there a reasonable way to test the Serialize() method?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: 2 unresolved discussions (waiting on @amcastro-tri, @ggould-tri, @jwnimmer-tri, and @sherm1)

___
*[multibody/plant/multibody_plant.h, line 4802 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmW00J1owb8ImuB7HO:-MkmxDWK8vwEN8pTpGq4:bw2rpe0) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant.h#L4802)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: consider instead using GetContactModelFromString(). Either make that public or just invoke internal::GetContactModelFromString() here. I'd like to see all four values initialized from the config.
</blockquote></details>

Working

That introduces a dependency cycle.  I'll need to cycle back later to see if I can fix that.  Most likely, I'll end up with a TODO here and then in a separate PR, move `ContactModel` into its own file, alongside its utilities.
___
*[multibody/plant/multibody_plant_config.h, line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmSZTW4gxImUZYr8go:-MkmuSGk88L8d6lsoWve:b-6oioq0) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant_config.h#L28)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should note that this default puts MbP in discrete mode and that a time_step of zero is used as a flag to select continuous mode.
</blockquote></details>

Done.  (Clarifying the default here is good.  Trying to copy-pasta the constructor documentation that explains the semantics is bad.  There is a Doxygen hyperlink to the constructor.)
___
*[multibody/plant/multibody_plant_config_functions.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmVYxn2wqhVCuhHO_F:-MkmwgwR0l5ueuD2kSKb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant_config_functions.cc#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: rename `GetStringFromContactModel()` for consistency with previous function
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri,sherm1(platform) (waiting on @amcastro-tri, @ggould-tri, and @sherm1)

___
*[multibody/plant/multibody_plant.h, line 4802 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmW00J1owb8ImuB7HO:-MknZpgi07u5aoxqQlj3:b-1o5meb) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/multibody_plant.h#L4802)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

That introduces a dependency cycle.  I'll need to cycle back later to see if I can fix that.  Most likely, I'll end up with a TODO here and then in a separate PR, move `ContactModel` into its own file, alongside its utilities.
</blockquote></details>

Done via TODO.
___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmX-gk1JTByp3ey5rj:-MknZrGhCsDcjI68oV_S:b3owm4z) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/test/multibody_plant_config_functions_test.cc#L43)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Is there a reasonable way to test the Serialize() method?
</blockquote></details>

Oops!  Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri,sherm1(platform) (waiting on @jwnimmer-tri)

___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmTOUV-5D-i3bwSMok:-MknjEug9Oc3Yp6dB5QY:b-3xdg79) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/test/multibody_plant_config_functions_test.cc#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding those getters in this PR or separately with a TODO here so this can be fully tested (and since they should exist anyway).
</blockquote></details>

No comment on this?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15826)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),amcastro-tri,sherm1(platform) (waiting on @jwnimmer-tri)

___
*[multibody/plant/test/multibody_plant_config_functions_test.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15826#-MkmTOUV-5D-i3bwSMok:-MknkBFk3HF4UqS-6qCC:b-79x154) ([raw file](https://github.com/robotlocomotion/drake/blob/697db7fd6ec31763298bc6e932875f68907fa383/multibody/plant/test/multibody_plant_config_functions_test.cc#L25)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No comment on this?
</blockquote></details>

I did consider it, and decided it was well outside my scope.

(Between the "BTW" and "consider", it didn't seem to me like a reply was necessary; if it was "nit", I would have replied.)

**Pull request merged**
