### PR TITLE
Make PublishLoadRobot() public and bind it in pydrake

### PR DESCRIPTION
**Pull request by avalenzu**
This PR is a step towards supporting workflows that want to use DrakeVisualizer to visualize trajectories generated by planners or other non-simulation sources.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8400)

### CODE REVIEW

**Comment by avalenzu** [comment]
@seancurtis-tri  for feature review.
@ericcousineau-tri for ***platform*** review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-:-L7yyEmbHBaXmNn49cQZ:bkmhl40)*

**Comment by avalenzu** [comment]
+@SeanCurtis-TRI  for feature review.
+@EricCousineau-TRI for platform review

Darn, syntax.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-:-L7yyNyXngm-pgx_77gZ:b2nkgws)*

**Comment by EricCousineau-TRI** [comment]
*[multibody/rigid_body_plant/drake_visualizer.h, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-L7z25KWhbvYkdBc4mJM:-L7z25KYFal6KkRyQxIC:bnt7h31) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e471abfdffa5e641be448b1d77966d74b00de3/multibody/rigid_body_plant/drake_visualizer.h#L113)):*
> ```objc
>   // Publishes a lcmt_viewer_load_robot message containing a description
>   // of what should be visualized. The message is intended to be received by the
>   // Drake Visualizer.
> ```

Can you add a comment indicating that this called at initialization called when executed via an analysis tool like `Simulator`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-L7z2P0x39mQOE0ganlU:-L7z2P0x39mQOE0ganlV:b-h8uj9w) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e471abfdffa5e641be448b1d77966d74b00de3/bindings/pydrake/multibody/rigid_body_plant_py.cc#L181)):*
> ```cpp
>              py::arg("period"))
>         .def("ReplayCachedSimulation", &Class::ReplayCachedSimulation)
>         .def("PublishLoadRobot", &Class::PublishLoadRobot);
> ```

Can you make a call to this method in `rigid_body_plant_test`, to check the API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400)*

**Comment by avalenzu** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/multibody/rigid_body_plant_py.cc, line 181 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-L7z2P0x39mQOE0ganlU:-L7z9Ph45MUohEbMr-8G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e471abfdffa5e641be448b1d77966d74b00de3/bindings/pydrake/multibody/rigid_body_plant_py.cc#L181)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you make a call to this method in `rigid_body_plant_test`, to check the API?
</blockquote></details>

Done.

---

*[multibody/rigid_body_plant/drake_visualizer.h, line 113 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-L7z25KWhbvYkdBc4mJM:-L7z9QJJJkLbUBM-BjQq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e471abfdffa5e641be448b1d77966d74b00de3/multibody/rigid_body_plant/drake_visualizer.h#L113)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you add a comment indicating that this called at initialization called when executed via an analysis tool like `Simulator`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-:-L7zAO0FrDLdzUQOX-pE:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: (One documentation clarification request.)

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/drake_visualizer.h, line 114 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-L7z_PJyc7YcdP20Ki1R:-L7z_PJyc7YcdP20Ki1S:bxg91np) ([raw file](https://github.com/robotlocomotion/drake/blob/07e88fce8919c5719b9fd0a98e151eb15f182f56/multibody/rigid_body_plant/drake_visualizer.h#L114)):*
> ```objc
>    * Publishes a lcmt_viewer_load_robot message containing a description
>    * of what should be visualized. The message is intended to be received by the
>    * Drake Visualizer. When a DrakeVisualizer is simulated, this method is
> ```

BTW I find this confusing.

1. "Drake Visualizer" and "DrakeVisualizer" are one whitespace typo away from being the same thing.
2. I don't know what it means for this class to be "simulated".  It seems like unique terminology introduced here. Could you elaborate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400#-:-L7z_isg4q1ow0YOB1n8:bjg5851)*

**Comment by avalenzu** [comment]
@ericcousineau-tri , could you sign off on the changes to `DrakeVisualizer.h` in r3? I've changed the doc in `DrakeVisualizer.h` to use `drake-visualizer` for the executable and `DrakeVisualizer` for the class.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/drake_visualizer.h, line 114 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8400#-L7z_PJyc7YcdP20Ki1R:-L7zlTnmCSo63s8gLdXT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e88fce8919c5719b9fd0a98e151eb15f182f56/multibody/rigid_body_plant/drake_visualizer.h#L114)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I find this confusing.

1. "Drake Visualizer" and "DrakeVisualizer" are one whitespace typo away from being the same thing.
2. I don't know what it means for this class to be "simulated".  It seems like unique terminology introduced here. Could you elaborate?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8400#-:-L7zlWZ87EKtntpNnNo4:b-hpa6f8)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8400)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8400)*

**Pull request merged**
