### PR TITLE
[geometry] Meshcat's server returns 404 (not 200) on failures

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19598.

Returning cacheable 200 responses with empty bodies is seriously misleading to the browser-side code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20790)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

It seems that this PR is predominantly introducing and apply the `ReadFile` functions. Neither the PR title nor the commit even hints at it.

+@sherm1 for platform review.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20790#-:-NoOp1gUCB5IgqB6mtNd:b-w507xh)* status: LGTM missing from assignee sherm1(platform)

**Comment by jwnimmer-tri** [comment]
To my eye, "start to carve helper functions" at least _hints_ at it.  I guess I could add the new function name to the commit body on the next rebase, if you think it helps?

**Comment by jwnimmer-tri** [comment]
I found a lint error so I pushed a rebase anyway with a new note.

**Review by sherm1 — COMMENTED** [review]
Nice cleanup! There are a few CI errors. Platform :lgtm: pending CI

> Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20790#-:-NoPGRdW5nOoFLWw5e-5:bs0l54p)* status: 1 unresolved discussion

___
*[`geometry/meshcat_internal.h` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20790#-NoPFP_z2R30CSlELdmn:-NoPFP_z2R30CSlELdmo:b-8uv0by) ([raw file](https://github.com/RobotLocomotion/drake/blob/fbc27532f24048cfc289585b3b7ec04ee0bddb68/geometry/meshcat_internal.h#L11)):*
> ```objc
> namespace internal {
> 
> /* Returns the static content for the given URL, or an nullopt when the URL is
> ```

typo: "an nullopt" -> "a nullopt"

**Pull request merged**
