### PR TITLE
[geometry] Exempt a long test from kcov

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21642)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21642#-:-O0VPGC69di2dfvOIk16:b-6es8oq)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @rpoyner-tri)

**Comment by sherm1** [comment]
Please assign a feature reviewer if this is ready.

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for off-cycle both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21642#-:-O0l1VUc4N3v6JOHka8F:b8p4o6d)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21642#-:-O0o6ifw3M6TEp_uv0GL:b4xzgsb)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
