### PR TITLE
[doc] Clarify stability policy for struct aggregate initialization

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://github.com/RobotLocomotion/drake/pull/19105 and https://github.com/RobotLocomotion/drake/pull/19144.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

After you're done, I expect to tag all/most of the core review team for feedback.

FYI @calderpg-tri

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSMK0vn6uwEBKxStS4e:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Platform reviewers please have a look here as you have time:
+@EricCousineau-TRI
+@ggould-tri
+@sammy-tri
+@sherm1
+@xuchenhan-tri
@RussTedrake

Once I have enough LGTMs here for quorum (2-3 more people), then I'll plan to merge.

**Review by sherm1 — COMMENTED** [review]
I'm not grokking this yet, ptal.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSMYWbF8K6ait5wfCRN:bpb3w06)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),sammy-tri(platform),EricCousineau-TRI(platform),sherm1(platform),xuchenhan-tri(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @jwnimmer-tri, @sammy-tri, and @xuchenhan-tri)

___
*[`doc/_pages/stable.md` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSMXcJx7pevAYBekdYV:-NSMXcJx7pevAYBekdYW:b-n9wcg4) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f5a04b5f7b3e951166ffce9b83ec56f6c3f982/doc/_pages/stable.md#L194)):*
> ```Markdown
>   [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization),
>   always use designated initializers (i.e., field names) when referring to
>   struct fields. It is OK to depend on the relative order of struct fields.
> ```

This says "do not depend on the exact order of struct fields" and "it is OK to depend on the relative order of struct fields". I don't understand what distinction you are making here. I know designated initializers must be in the same order as the struct members, but that's a language requirement rather than a style issue. Can you clarify?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),sammy-tri(platform),EricCousineau-TRI(platform),sherm1(platform),xuchenhan-tri(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @sammy-tri, @sherm1, and @xuchenhan-tri)

___
*[`doc/_pages/stable.md` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSMXcJx7pevAYBekdYV:-NSMaBRaB8R3-4cmw9sJ:b-rzkxem) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f5a04b5f7b3e951166ffce9b83ec56f6c3f982/doc/_pages/stable.md#L194)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This says "do not depend on the exact order of struct fields" and "it is OK to depend on the relative order of struct fields". I don't understand what distinction you are making here. I know designated initializers must be in the same order as the struct members, but that's a language requirement rather than a style issue. Can you clarify?
</blockquote></details>

My aim is that we promise not to **re-order** the fields, so the user can depend on their "relative" order, e.g., `foo` will always precede `bar`.

On the other hand, we are allowed to add new fields anywhere; the user cannot depend on that field `foo` is the 3rd field.

Is there a phrasing that would explain it better?

Maybe "exact order" is the problem.  "Exact index" or something is more what I mean, though it's not strictly an index.

**Review by sherm1 — COMMENTED** [review]
:lgtm: pending adoption of Xuchen's rewording or equivalent

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSMecCI4sWYwyg5Q-SK:b-vcztwk)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @jwnimmer-tri, @sammy-tri, and @xuchenhan-tri)

___
*[`doc/_pages/stable.md` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSMXcJx7pevAYBekdYV:-NSMeWHu7MtikiUnDglp:b-tvaa6t) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f5a04b5f7b3e951166ffce9b83ec56f6c3f982/doc/_pages/stable.md#L194)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The current wording is a bit confusing to me until I read the referenced PR. Here is my attempt:

>* In C++, do not depend on the exact order of struct fields. While the relative order of struct fields is guaranteed, new member fields could potentially be inserted between existing ones. Consequently, when using [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization), always use designated initializers (i.e., field names) when referring to struct fields. 
</blockquote></details>

Xuchen's proposed wording resolves my confusion -- thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @sammy-tri, @sherm1, and @xuchenhan-tri)

___
*[`doc/_pages/stable.md` line 194 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSMXcJx7pevAYBekdYV:-NSMkkGN3BGm7uA-sP-s:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a7f5a04b5f7b3e951166ffce9b83ec56f6c3f982/doc/_pages/stable.md#L194)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Xuchen's proposed wording resolves my confusion -- thanks!
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri and @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri and @sammy-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSfBftOCC3mk6C0ZKlW:bnfp4nl)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri and @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with nit on assumptions of default construction

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSfZ9SRAXbk1TtBBn8d:bxpk7o2)* status: 1 unresolved discussion, LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri, @jwnimmer-tri, and @sammy-tri)

___
*[`doc/_pages/stable.md` line 196 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSfYQ168nEKK_7dn3jS:-NSfYQ178KprAI4qel3B:boga5oc) ([raw file](https://github.com/RobotLocomotion/drake/blob/fba9a361405fa36463ed7551423940c828780ec5/doc/_pages/stable.md#L196)):*
> ```Markdown
>   [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization)
>   always use designated initializers (i.e., field names) when referring to
>   struct fields.
> ```

nit It's still unclear to me that the insertion of a new field won't cause a breakage.

AFAICT, we generally do this (for archive `Serialize()` usage). But is this well understood / stated?
Consider stating this briefly, e.g.

```
For most ``struct`` definitions that you interface with, they should be overall default constructible, so the addition of a new field should not cause compilation errors.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145)* status: LGTM missing from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @ggould-tri and @sammy-tri)

___
*[`doc/_pages/stable.md` line 196 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-NSfYQ168nEKK_7dn3jS:-NSf_fW87ElE8GMMX8U4:b-fhea6n) ([raw file](https://github.com/RobotLocomotion/drake/blob/fba9a361405fa36463ed7551423940c828780ec5/doc/_pages/stable.md#L196)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's still unclear to me that the insertion of a new field won't cause a breakage.

AFAICT, we generally do this (for archive `Serialize()` usage). But is this well understood / stated?
Consider stating this briefly, e.g.

```
For most ``struct`` definitions that you interface with, they should be overall default constructible, so the addition of a new field should not cause compilation errors.
```
</blockquote></details>

This document explains what's incumbent upon _users_ -- so that particular suggestion would be out of scope here.

For the Drake Developer side of it, I've now added a reminder in my "deprecation playbook" draft re: the need to provide default values for newly-added struct fields.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:
The implied prospect of deprecating the order of struct fields is very puzzling; let's never do that.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19145#-:-NSfa4O9A8qLG1GBvWQI:bnsppo0)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Pull request merged**
