### PR TITLE
Refactoring Objective to Cost

### PR DESCRIPTION
**Pull request by naveenoid**
All usages of "Objective" refactored to "Cost" to fit with https://github.com/RobotLocomotion/drake/issues/2639

+@sammy-tri Feature review
+@sherm1 Platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2649)

### CODE REVIEW

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLDzVzsrQ8pLZ72jDWg:1058782226)*

**Comment by sherm1** [comment]
Whoops -- sorry, I take that back @naveenoid. Build problems, for example:
```
18:45:30 /home/ubuntu/workspace/experimental/9111c4bf/drake/solvers/SnoptSolver.cpp:195:47: error: no member named 'generic_objectives' in 'drake::solvers::OptimizationProblem'
18:45:30   for (auto const& binding : current_problem->generic_objectives()) {
18:45:30                              ~~~~~~~~~~~~~~~  ^
18:45:30 /home/ubuntu/workspace/experimental/9111c4bf/drake/solvers/IpoptSolver.cpp:406:42: error: no member named 'generic_objectives' in 'drake::solvers::OptimizationProblem'
18:45:30     for (auto const& binding : problem_->generic_objectives()) {
18:45:30                                ~~~~~~~~  ^
18:45:31 1 error generated.
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLE-0ZU8gqFr7QPk4g1:520946661)*

**Comment by naveenoid** [comment]
ready for review.

**Comment by naveenoid** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/solvers/NloptSolver.cpp, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-KLHF6tEtvTDARFHXbFR:-KLHF6tEtvTDARFHXbFS:-1490444896) ([raw file](https://github.com/robotlocomotion/drake/blob/30e5f30524f4c60ec7c4a86216d6ef7e66f25980/drake/solvers/NloptSolver.cpp#L46)):*
> ```cpp
> // This function meets the signature requirements for nlopt::vfunc as
> // described in
> // http://ab-initio.mit.edu/wiki/index.php/NLopt_C-plus-plus_Reference#ObjectCostive_function
> ```

The URL for the NLopt documentation should not change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---

*[drake/solvers/NloptSolver.cpp, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-KLHF6tEtvTDARFHXbFR:-KLHKG5A3pCGLe9bTT5z:-1834867277) ([raw file](https://github.com/robotlocomotion/drake/blob/30e5f30524f4c60ec7c4a86216d6ef7e66f25980/drake/solvers/NloptSolver.cpp#L46)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> The URL for the NLopt documentation should not change.
</details>
Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLHKMekKKFAde-KcqBd:1417088721)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649)*

**Comment by david-german-tri** [comment]
@sherm1 FYI, you can use :lgtm_cancel: in situations like this!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLHMN3z8NHVMfBmXdKY:1660542448)*

**Comment by sherm1** [comment]
Thanks, @david-german-tri -- I'll :lgtm_cancel: until the build finishes.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLHaPPWGq336aF1rOGm:-2021340686)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2649#-:-KLKEuRsk7rcO4kQB52k:1417088721)*

**Pull request merged**
