### PR TITLE
Trim PiecewisePolynomials 

### PR DESCRIPTION
**Pull request by sadraddini**
Part of https://github.com/RobotLocomotion/drake/issues/22100

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22099)

### CODE REVIEW

**Comment by sadraddini** [comment]
@jwnimmer-tri or @RussTedrake Do you mind reviewing this or assigning someone?

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-:-OAxQIkA9wJTC7hWv3qe:b1ikduc)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

___
*[`common/trajectories/piecewise_polynomial.h` line 766 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxRJju9aOyxIUlsC6a:-OAxRJju9aOyxIUlsC6b:b-8qwfg2) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/piecewise_polynomial.h#L766)):*
> ```objc
>    *        trajectory's time range.
>    */
>   PiecewisePolynomial Trim(const T& start_time, const T& end_time) const;
> ```

I mildly worry that "trim" sounds like it's changing the current object, whereas this is a const method returning a new object.

we already have "slice" method which does the same thing, except by segment index instead of by time.  I actually prefer the name "slice" because it _slightly_ sounds more like it's making the new object?  In either case, i'd like this method to be connected to that method.

perhaps "SliceByTime()". I don't love that, but it's clear.  Having two overloads for slice, one that takes two ints, and the other that takes two doubles seems too risky.
___
*[`common/trajectories/test/piecewise_polynomial_test.cc` line 215 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxTy752zlqtZdS5EFL:-OAxTy768qTrjWYkiZO8:b-nsksak) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/test/piecewise_polynomial_test.cc#L215)):*
> ```cpp
>                                 piecewise1.value(t), 1e-8,
>                                 MatrixCompareType::absolute));
>     // Pick 10 random samples and check that the sampled values are the same.
> ```

btw -- the use of random samples in here is vestigial.  it's better to use arbitrary but fixed sample times.
___
*[`common/trajectories/test/piecewise_polynomial_test.cc` line 221 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxUGyF0Z0rN2lySuFF:-OAxUGyF0Z0rN2lySuFG:b4g75au) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/test/piecewise_polynomial_test.cc#L221)):*
> ```cpp
>                                   piecewise1.value(t_sample), 1e-8,
>                                   MatrixCompareType::absolute));
>     }
> ```

we don't actually have any guarantee that the impacted segment is being checked in here.  we should definitely have that. (it's also good to check the other segments).

**Review by sadraddini — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22099)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`common/trajectories/piecewise_polynomial.h` line 766 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxRJju9aOyxIUlsC6a:-OBAfyEFAwaac0QCyUDY:b-xkyxp5) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/piecewise_polynomial.h#L766)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I mildly worry that "trim" sounds like it's changing the current object, whereas this is a const method returning a new object.

we already have "slice" method which does the same thing, except by segment index instead of by time.  I actually prefer the name "slice" because it _slightly_ sounds more like it's making the new object?  In either case, i'd like this method to be connected to that method.

perhaps "SliceByTime()". I don't love that, but it's clear.  Having two overloads for slice, one that takes two ints, and the other that takes two doubles seems too risky.
</blockquote></details>

Done  changed it to `SliceByTime`
___
*[`common/trajectories/test/piecewise_polynomial_test.cc` line 215 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxTy752zlqtZdS5EFL:-OBAg9MD6boIYWWPexrR:b-9m8994) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/test/piecewise_polynomial_test.cc#L215)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- the use of random samples in here is vestigial.  it's better to use arbitrary but fixed sample times.
</blockquote></details>

Done  See the response to your next comment. 
___
*[`common/trajectories/test/piecewise_polynomial_test.cc` line 221 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-OAxUGyF0Z0rN2lySuFF:-OBAijZWAcHNcg8jiW8b:bczgpqj) ([raw file](https://github.com/RobotLocomotion/drake/blob/5eb776f72622842f3b9c6bcbf74c315fe889d11a/common/trajectories/test/piecewise_polynomial_test.cc#L221)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we don't actually have any guarantee that the impacted segment is being checked in here.  we should definitely have that. (it's also good to check the other segments).
</blockquote></details>

Done  made one sample at every segment.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-:-OBClJqgE03mK3f4IvQu:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sadraddini)

**Comment by sadraddini** [comment]
+@sammy-tri for platform review, per schedule, please!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22099#-:-OBRqLsJ0PHlbZFL5VTw:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Pull request merged**
