### PR TITLE
[solvers] Increase tolerance for constraint_test

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19377)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please.

**Review by svenevs — COMMENTED** [review]
+@hongkai-dai via #11147 please, see also https://github.com/RobotLocomotion/drake/issues/18327#issuecomment-1535537588

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-:-NUoCB3m-Y4nFKjKZ9pG:b-kkdvhn)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @svenevs)

___
*[`solvers/test/constraint_test.cc` line 797 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-NUoC2ZH22lMxwO-ALim:-NUoC2ZH22lMxwO-ALin:b-mpbw2y) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4b5c73681d61b0c678ba3a4bb6ae089ded941db/solvers/test/constraint_test.cc#L797)):*
> ```cpp
>   y_expected(0) = z(0) - z(1) * std::exp(z(2) / z(1));
>   y_expected(1) = z(1);
>   const double tol = 8.0 * std::numeric_limits<double>::epsilon();
> ```

working, success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //solvers:constraint_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //solvers:constraint_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
FAIL: //solvers:constraint_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/solvers/constraint_test/test.log)
INFO: From Testing //solvers:constraint_test:
==================== Test output for //solvers:constraint_test:
Using drake_cc_googletest_main.cc

[==========] Running 17 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from TestConstraint
[ RUN      ] TestConstraint.BoundSizeCheck
[       OK ] TestConstraint.BoundSizeCheck (0 ms)
[ RUN      ] TestConstraint.LinearConstraintSparse
[       OK ] TestConstraint.LinearConstraintSparse (0 ms)
[ RUN      ] TestConstraint.LinearEqualityConstraintSparse
[       OK ] TestConstraint.LinearEqualityConstraintSparse (0 ms)
[ RUN      ] TestConstraint.testLinearConstraintUpdate
[       OK ] TestConstraint.testLinearConstraintUpdate (0 ms)
[----------] 4 tests from TestConstraint (0 ms total)

[----------] 13 tests from testConstraint
[ RUN      ] testConstraint.testRemoveTinyCoefficient
[       OK ] testConstraint.testRemoveTinyCoefficient (0 ms)
[ RUN      ] testConstraint.testQuadraticConstraintHessian
[       OK ] testConstraint.testQuadraticConstraintHessian (0 ms)
[ RUN      ] testConstraint.testLorentzConeConstraint
[       OK ] testConstraint.testLorentzConeConstraint (0 ms)
[ RUN      ] testConstraint.testLorentzConeConstraintAtZeroZ
[       OK ] testConstraint.testLorentzConeConstraintAtZeroZ (0 ms)
[ RUN      ] testConstraint.LorentzConeConstraintUpdateCoefficients
[       OK ] testConstraint.LorentzConeConstraintUpdateCoefficients (0 ms)
[ RUN      ] testConstraint.testRotatedLorentzConeConstraint
[       OK ] testConstraint.testRotatedLorentzConeConstraint (0 ms)
[ RUN      ] testConstraint.RotatedLorentzConeConstraintUpdateCoefficients
[       OK ] testConstraint.RotatedLorentzConeConstraintUpdateCoefficients (0 ms)
[ RUN      ] testConstraint.testPositiveSemidefiniteConstraint
[       OK ] testConstraint.testPositiveSemidefiniteConstraint (0 ms)
[ RUN      ] testConstraint.testLinearMatrixInequalityConstraint
[       OK ] testConstraint.testLinearMatrixInequalityConstraint (0 ms)
[ RUN      ] testConstraint.testExpressionConstraint
[       OK ] testConstraint.testExpressionConstraint (0 ms)
[ RUN      ] testConstraint.testSimpleLCPConstraintEval
[       OK ] testConstraint.testSimpleLCPConstraintEval (0 ms)
[ RUN      ] testConstraint.testEvaluatorConstraint
[       OK ] testConstraint.testEvaluatorConstraint (0 ms)
[ RUN      ] testConstraint.testExponentialConeConstraint
solvers/test/constraint_test.cc:812: Failure
Value of: CompareMatrices(math::ExtractValue(y_autodiff), y_expected, tol)
  Actual: false (Values at (0, 0) exceed tolerance: -14.490882129572938 vs. -14.490882129572936, diff = 1.7763568394002505e-15, tolerance = 1.1102230246251565e-15
m1 =
-14.49088212957294
                14
m2 =
-14.49088212957294
                14
delta=
-1.77635683940025e-15
                    0)
Expected: true
[  FAILED  ] testConstraint.testExponentialConeConstraint (0 ms)
[----------] 13 tests from testConstraint (0 ms total)

[----------] Global test environment tear-down
[==========] 17 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] testConstraint.testExponentialConeConstraint

 1 FAILED TEST
================================================================================
Target //solvers:constraint_test up-to-date:
  bazel-bin/solvers/constraint_test
INFO: Elapsed time: 0.185s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//solvers:constraint_test                                                FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.

```

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-:-NUrDvoA2BotcC8xiQHA:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri.

> Reviewed 1 of 1 files at r1, all commit messages.
> Dismissed @svenevs from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-:-NUrSRzg0J0-Jlh4VlEA:b-udyqyg)* status: 1 unresolved discussion

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-NUrSbK20DY4rjdkfb6F):*
nit Remove issue number when merging.
___
*[`solvers/test/constraint_test.cc` line 797 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19377#-NUoC2ZH22lMxwO-ALim:-NUrSgPi9XQ9FzX0iu9s:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/e4b5c73681d61b0c678ba3a4bb6ae089ded941db/solvers/test/constraint_test.cc#L797)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //solvers:constraint_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //solvers:constraint_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
FAIL: //solvers:constraint_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/solvers/constraint_test/test.log)
INFO: From Testing //solvers:constraint_test:
==================== Test output for //solvers:constraint_test:
Using drake_cc_googletest_main.cc

[==========] Running 17 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from TestConstraint
[ RUN      ] TestConstraint.BoundSizeCheck
[       OK ] TestConstraint.BoundSizeCheck (0 ms)
[ RUN      ] TestConstraint.LinearConstraintSparse
[       OK ] TestConstraint.LinearConstraintSparse (0 ms)
[ RUN      ] TestConstraint.LinearEqualityConstraintSparse
[       OK ] TestConstraint.LinearEqualityConstraintSparse (0 ms)
[ RUN      ] TestConstraint.testLinearConstraintUpdate
[       OK ] TestConstraint.testLinearConstraintUpdate (0 ms)
[----------] 4 tests from TestConstraint (0 ms total)

[----------] 13 tests from testConstraint
[ RUN      ] testConstraint.testRemoveTinyCoefficient
[       OK ] testConstraint.testRemoveTinyCoefficient (0 ms)
[ RUN      ] testConstraint.testQuadraticConstraintHessian
[       OK ] testConstraint.testQuadraticConstraintHessian (0 ms)
[ RUN      ] testConstraint.testLorentzConeConstraint
[       OK ] testConstraint.testLorentzConeConstraint (0 ms)
[ RUN      ] testConstraint.testLorentzConeConstraintAtZeroZ
[       OK ] testConstraint.testLorentzConeConstraintAtZeroZ (0 ms)
[ RUN      ] testConstraint.LorentzConeConstraintUpdateCoefficients
[       OK ] testConstraint.LorentzConeConstraintUpdateCoefficients (0 ms)
[ RUN      ] testConstraint.testRotatedLorentzConeConstraint
[       OK ] testConstraint.testRotatedLorentzConeConstraint (0 ms)
[ RUN      ] testConstraint.RotatedLorentzConeConstraintUpdateCoefficients
[       OK ] testConstraint.RotatedLorentzConeConstraintUpdateCoefficients (0 ms)
[ RUN      ] testConstraint.testPositiveSemidefiniteConstraint
[       OK ] testConstraint.testPositiveSemidefiniteConstraint (0 ms)
[ RUN      ] testConstraint.testLinearMatrixInequalityConstraint
[       OK ] testConstraint.testLinearMatrixInequalityConstraint (0 ms)
[ RUN      ] testConstraint.testExpressionConstraint
[       OK ] testConstraint.testExpressionConstraint (0 ms)
[ RUN      ] testConstraint.testSimpleLCPConstraintEval
[       OK ] testConstraint.testSimpleLCPConstraintEval (0 ms)
[ RUN      ] testConstraint.testEvaluatorConstraint
[       OK ] testConstraint.testEvaluatorConstraint (0 ms)
[ RUN      ] testConstraint.testExponentialConeConstraint
solvers/test/constraint_test.cc:812: Failure
Value of: CompareMatrices(math::ExtractValue(y_autodiff), y_expected, tol)
  Actual: false (Values at (0, 0) exceed tolerance: -14.490882129572938 vs. -14.490882129572936, diff = 1.7763568394002505e-15, tolerance = 1.1102230246251565e-15
m1 =
-14.49088212957294
                14
m2 =
-14.49088212957294
                14
delta=
-1.77635683940025e-15
                    0)
Expected: true
[  FAILED  ] testConstraint.testExponentialConeConstraint (0 ms)
[----------] 13 tests from testConstraint (0 ms total)

[----------] Global test environment tear-down
[==========] 17 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] testConstraint.testExponentialConeConstraint

 1 FAILED TEST
================================================================================
Target //solvers:constraint_test up-to-date:
  bazel-bin/solvers/constraint_test
INFO: Elapsed time: 0.185s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//solvers:constraint_test                                                FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.

```
</blockquote></details>

Done

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
