### PR TITLE
Revert "Fix error message when user sets a bad SpatialInertia."

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @mitiguy ,

 The on-call build cop, @BetsyMcPhail , believes that your PR #16065 may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-big-sur-clang-bazel-continuous-release/962/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-monterey-clang-bazel-continuous-release/50/

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16186)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please.

**Comment by sherm1** [comment]
This is due to too-specific number matching in expected error messages. It appears that Ubuntu and Mac don't agree on whether to put a ".0" after an integer-valued floating point number:
```
multibody/tree/test/spatial_inertia_test.cc:356: Failure
matcher(err.what(), expected_msg) evaluates to false, where
err.what() evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid().\n mass = 1\n Center of mass = [0  0  0]\n Inertia about point P, I_BP =\n[  -2, -0.1, -0.2]\n[-0.1,   -3, -0.3]\n[-0.2, -0.3,   -4]\n Principal moments of inertia about Bcm (center of mass) =\n[-4.105976670111365  -2.9188291125626042  -1.9751942173260322]\n"
expected_msg evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n mass = 1.0\n Center of mass = \\[0.0  0.0  0.0\\]\n Inertia about point P, I_BP =\n\\[  -2, -0.1, -0.2\\]\n\\[-0.1,   -3, -0.3\\]\n\\[-0.2, -0.3,   -4\\]\n Principal moments of inertia about Bcm \\(center of mass\\) =\n\\[-4.105976670111\\d+  -2.9188291125626\\d+  -1.9751942173260\\d+\\]\n"
[  FAILED  ] SpatialInertia.IsPhysicallyValidWithBadInertia (0 ms)
[ RUN      ] SpatialInertia.IsPhysicallyValidWithCOMTooFarOut
multibody/tree/test/spatial_inertia_test.cc:379: Failure
matcher(err.what(), expected_msg) evaluates to false, where
err.what() evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid().\n mass = 1\n Center of mass = [2  0  0]\n Inertia about point P, I_BP =\n[0.4,   0,   0]\n[  0, 0.4,   0]\n[  0,   0, 0.4]\n Inertia about center of mass, I_BBcm =\n[ 0.4,    0,    0]\n[   0, -3.6,    0]\n[   0,    0, -3.6]\n Principal moments of inertia about Bcm (center of mass) =\n[-3.6  -3.6  0.4]\n"
expected_msg evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n mass = 1.0\n Center of mass = \\[2.0  0.0  0.0\\]\n Inertia about point P, I_BP =\n\\[0.4,   0,   0\\]\n\\[  0, 0.4,   0\\]\n\\[  0,   0, 0.4\\]\n Inertia about center of mass, I_BBcm =\n\\[ 0.4,    0,    0\\]\n\\[   0, -3.6,    0\\]\n\\[   0,    0, -3.6\\]\n Principal moments of inertia about Bcm \\(center of mass\\) =\n\\[-3.6  -3.6  0.4\\]\n"
[  FAILED  ] SpatialInertia.IsPhysicallyValidWithCOMTooFarOut (0 ms)
[ RUN      ] SpatialInertia.IsPhysicallyValidThrowsNiceExceptionMessage
multibody/tree/test/spatial_inertia_test.cc:425: Failure
matcher(err.what(), expected_msg) evaluates to false, where
err.what() evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid().\n mass = 0.634\n Center of mass = [0  0.016  -0.02]\n Inertia about point P, I_BP =\n[  0.0023989,    0.000245,     1.3e-05]\n[   0.000245,   0.0023566,  0.00020438]\n[    1.3e-05,  0.00020438, 0.000570304]\n Inertia about center of mass, I_BBcm =\n[0.001983, 0.000245,  1.3e-05]\n[0.000245, 0.002103,  1.5e-06]\n[ 1.3e-05,  1.5e-06, 0.000408]\n Principal moments of inertia about Bcm (center of mass) =\n[0.0004078925412357755  0.0017908225928030743  0.002295284865961151]\n"
expected_msg evaluates to "Spatial inertia fails SpatialInertia::IsPhysicallyValid\\(\\).\n mass = 0.634\n Center of mass = \\[0.0  0.016  -0.02\\]\n Inertia about point P, I_BP =\n\\[  0.0023989,    0.000245,     1.3e-05\\]\n\\[   0.000245,   0.0023566,  0.00020438\\]\n\\[    1.3e-05,  0.00020438, 0.000570304\\]\n Inertia about center of mass, I_BBcm =\n\\[0.001983, 0.000245,  1.3e-05\\]\n\\[0.000245, 0.002103,  1.5e-06\\]\n\\[ 1.3e-05,  1.5e-06, 0.000408\\]\n Principal moments of inertia about Bcm \\(center of mass\\) =\n\\[0.0004078925412\\d+  0.001790822592803\\d+  0.00229528486596\\d+\\]\n"
[  FAILED  ] SpatialInertia.IsPhysicallyValidThrowsNiceExceptionMessage (0 ms)
```

**Comment by mitiguy** [comment]
Hi Betsy -- I would like to quickly make a fix-forward PR.  Could you hold off on reverting.

**Comment by BetsyMcPhail** [comment]
> Hi Betsy -- I would like to quickly make a fix-forward PR. Could you hold off on reverting.

Sure, no problem.

**Pull request closed without merging**
