### PR TITLE
Add systems/framework detail::ModelValues

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A first step to #5431.  See https://github.com/jwnimmer-tri/drake/tree/framework-model-io-ports for how it gets applied.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5432)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for review please.
I haven't figured out a second reviewer yet.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-:-KedTv_s-RKZ3tkHhhXk:b-90jieg)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/model_values.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYXig0x38jGktfcFk:-KedYXihJ8XYUVj1SDzn:bm47tql) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L33)):*
> ```objc
> 
>   /// Returns zero iff all values are nullptr; otherwise, returns one greater
>   /// than the largest non-nullptr index.  (This is akin to a vector, where
> ```

Isn't it the case that the largest index is always non-nullptr?

---

*[drake/systems/framework/model_values.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYi9VFMmltWP4TKGj:-KedYi9VFMmltWP4TKGk:bcshprn) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L40)):*
> ```objc
>   ///
>   /// @pre index >= size()
>   /// @pre model_value != nullptr
> ```

It's a little odd to allow any index except the last to be nullptr.   What's the thinking there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by david-german-tri** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/model_values.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYXig0x38jGktfcFk:-KedawigernGTj_DW-4i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L33)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Isn't it the case that the largest index is always non-nullptr?
</blockquote></details>

Done.

---

*[drake/systems/framework/model_values.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYi9VFMmltWP4TKGj:-Keday-OjnLjkmt5ntbn:b2ody5s) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L40)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

It's a little odd to allow any index except the last to be nullptr.   What's the thinking there?
</blockquote></details>

Good point.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by david-german-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/model_values.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedhK7iDvjhgYIdQ05e:-KedhK7j0nI8NZCI-GKM:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/84364fb72c6e306c1d7f67df78717c0ba2a3fe87/drake/systems/framework/model_values.h#L45)):*
> ```objc
>   ///
>   /// @pre index >= size()
>   /// @pre model_vector != nullptr
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/model_values.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedhK7iDvjhgYIdQ05e:-Kedi1VitE6X8MZXsdtA:b-3d7dfh) ([raw file](https://github.com/robotlocomotion/drake/blob/84364fb72c6e306c1d7f67df78717c0ba2a3fe87/drake/systems/framework/model_values.h#L45)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I guess it seemed weird to me to have `VectorValue<T>{nullptr}` as an allowed model entry, versus just `nullptr`.  But reading the future PRs that build on this, it doesn't seem to hurt anything, so I'll widen this contract....

... and it was quite a slog, but all for the better.  I inserted a`value.h` bugfix commit in the stream before the model_values code, because the it hated nullptr and had a broken subtype Clone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by sherm1** [comment]
Not sure where this is going, so I'll make a few random comments in case they are useful: I love the idea of using model values to specify allocation type for output ports. For input ports we need a definition of *acceptable* types; a model can be used as a very specific requirement but it's not good for an input port that can accept a variety of sources (e.g. pass-through or sampling Systems). But a model could be used to provide default values for input ports, in which case the model is really specifying "output" values that the input ports are to receive.

One thing I don't love is treating the input ports as a collection and the output ports as a collection. Each port is independent and it is awkward to treat them together since (for example) it obfuscates their dependencies. It isn't clear to me whether the ModelValues class is for a single port (good) or for a collection of ports treated together (not so good, IMO).

---

Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-:-KeetP5CE-I1FTHjj_Pi:b-rg2kck)*

**Comment by david-german-tri** [comment]
:lgtm_strong: good catch!

---

Reviewed 1 of 6 files at r3.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/model_values.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedhK7iDvjhgYIdQ05e:-KeexAbtUtaOdZjvEvlf:b-y65u2d) ([raw file](https://github.com/robotlocomotion/drake/blob/84364fb72c6e306c1d7f67df78717c0ba2a3fe87/drake/systems/framework/model_values.h#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess it seemed weird to me to have `VectorValue<T>{nullptr}` as an allowed model entry, versus just `nullptr`.  But reading the future PRs that build on this, it doesn't seem to hurt anything, so I'll widen this contract....

... and it was quite a slog, but all for the better.  I inserted a`value.h` bugfix commit in the stream before the model_values code, because the it hated nullptr and had a broken subtype Clone.
</blockquote></details>

BTW, this comment is now out-of-date?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-:-KeezqTafYNS4_xcHvPw:b-62snre)*

**Comment by david-german-tri** [comment]
Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/model_values.h, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedhK7iDvjhgYIdQ05e:-Kef3xJZkOb9Mx-PRXvL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/84364fb72c6e306c1d7f67df78717c0ba2a3fe87/drake/systems/framework/model_values.h#L45)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, this comment is now out-of-date?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri @sherm1 Do we have others are are ramped up to able to do review of framework changes?  I think a second review is probably a good idea, but perhaps not worth Sherm's time.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-:-KefOOASd4rscF-Rdzz-:b78fl7x)*

**Comment by ggould-tri** [comment]
+@ggould-tri for feature review.

**Comment by ggould-tri** [comment]
:lgtm: pending items below.

---

Reviewed 2 of 6 files at r1, 1 of 2 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/model_values.cc, line 15 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-Kejeeq4FDBt99Q02gSP:-Kejeeq4FDBt99Q02gSQ:bpdoo6h) ([raw file](https://github.com/robotlocomotion/drake/blob/ab02d717ea1db20d57019b20c0dd56e8edc9df1e/drake/systems/framework/model_values.cc#L15)):*
> ```cpp
> 
> void ModelValues::AddModel(
>     int index, std::unique_ptr<AbstractValue> model_value) {
> ```

BTW -- Can the `AbstractValue` be `const` here (and throughout except in the return of `Clone*`)?

---

*[drake/systems/framework/model_values.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYXig0x38jGktfcFk:-Kejcs__zx2o7RczuhFy:b-u2l350) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, what? I don't think that's true at all.  `AddModel(5, nullptr), size()` (or similar) would yield 5 as written.  So neither David's comment nor the documentation of this method is correct.

Am I missing something?  It seems like the class documentation implies that `nullptr` is a valid thing to `AddModel` with, and it doesn't seem to be documented or checked nonnull.

---

*[drake/systems/framework/model_values.h, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-Kej_fN4sZwnpe1Vh_8D:-Kej_fN4sZwnpe1Vh_8E:b-ybfcqi) ([raw file](https://github.com/robotlocomotion/drake/blob/ab02d717ea1db20d57019b20c0dd56e8edc9df1e/drake/systems/framework/model_values.h#L19)):*
> ```objc
> /// either input or output ports).  The models are the "prototype" design
> /// pattern (https://en.wikipedia.org/wiki/Prototype_pattern).  When creating
> /// elements in new Context, these models values are cloned to establish the
> ```

FYI grammar:  "these models values" needs an apostrophe somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-:-KejYuboHoxOKXVfxrdg:bvv10lx)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/model_values.cc, line 15 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-Kejeeq4FDBt99Q02gSP:-KekPxLjWlViTsrVN7sh:b-m98zrg) ([raw file](https://github.com/robotlocomotion/drake/blob/ab02d717ea1db20d57019b20c0dd56e8edc9df1e/drake/systems/framework/model_values.cc#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- Can the `AbstractValue` be `const` here (and throughout except in the return of `Clone*`)?
</blockquote></details>

Do you mean `std::unique_ptr<const AbstractValue>`?  I assume yes.

In `values_`, that makes a lot of sense (we don't want _this_ class to ever edit the prototypical model value), so I've changed it there.

Arguably `AddModel(int, std::unique_ptr<const AbstractValue>)` is a wider contract, so that people who happen to have `u_p<const AV>` at hand can still call the Add functions.  However, I think in practice such objects will be exceedingly rare, so it's not a huge benefit.  And perhaps the extra `const` there would confuse some readers , because `make_unique` returns a non-const wrapped type?  On the other hand, this is a `detail` class used only by ~4 places in one class (`LeafSystem`), so either way is likely to be fine.  I guess for me the "fewer keystrokes" will rule the and I'll leave `Add...` alone.

---

*[drake/systems/framework/model_values.h, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-KedYXig0x38jGktfcFk:-KekPGKPphzdl0fQ5t89:b8ked5f) ([raw file](https://github.com/robotlocomotion/drake/blob/a4f6284f3190d5621e70b327000a0de77e5b4b25/drake/systems/framework/model_values.h#L33)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Wait, what? I don't think that's true at all.  `AddModel(5, nullptr), size()` (or similar) would yield 5 as written.  So neither David's comment nor the documentation of this method is correct.

Am I missing something?  It seems like the class documentation implies that `nullptr` is a valid thing to `AddModel` with, and it doesn't seem to be documented or checked nonnull.
</blockquote></details>

Ah sorry; the abstraction function changed during the PR review and we missed this comment being lies.  Yay for second review!

Done.

---

*[drake/systems/framework/model_values.h, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-Kej_fN4sZwnpe1Vh_8D:-KekP05N-xw2akIqCA-x:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ab02d717ea1db20d57019b20c0dd56e8edc9df1e/drake/systems/framework/model_values.h#L19)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI grammar:  "these models values" needs an apostrophe somewhere?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/model_values.cc, line 15 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5432#-Kejeeq4FDBt99Q02gSP:-KenDOyV4SaHDMmKyerQ:b-kocrc6) ([raw file](https://github.com/robotlocomotion/drake/blob/ab02d717ea1db20d57019b20c0dd56e8edc9df1e/drake/systems/framework/model_values.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do you mean `std::unique_ptr<const AbstractValue>`?  I assume yes.

In `values_`, that makes a lot of sense (we don't want _this_ class to ever edit the prototypical model value), so I've changed it there.

Arguably `AddModel(int, std::unique_ptr<const AbstractValue>)` is a wider contract, so that people who happen to have `u_p<const AV>` at hand can still call the Add functions.  However, I think in practice such objects will be exceedingly rare, so it's not a huge benefit.  And perhaps the extra `const` there would confuse some readers , because `make_unique` returns a non-const wrapped type?  On the other hand, this is a `detail` class used only by ~4 places in one class (`LeafSystem`), so either way is likely to be fine.  I guess for me the "fewer keystrokes" will rule the and I'll leave `Add...` alone.
</blockquote></details>

OK, that seems like a reasonably use of author's discretion to me.
Mostly I just don't want what aspires to be a purely informational class to be a mechanism or vehicle for monkeying with values.  But the danger here seems small.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5432)*

**Pull request merged**
