### PR TITLE
Remove n_ary state and system

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3478)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3478#-:-KRnCwozDLRlDOnbDM5o:b-ew96m)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3478#-:-KRo3s0bpuO0HBgQRM5m:bnfp4nl)*

**Comment by maddog-tri** [comment]
Ashes to ashes, dust to dust; even the brilliantest code, soon turns to cruft.  :lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3478#-:-KRoeODyx7ziPjrtfRsV:b-y9sstf)*

**Pull request merged**
