### PR TITLE
Port automotive to model-based declarations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This uses #5431's sugar for the benefit of `automotive`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5484)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Unstable due to git failures
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
+@liangfok feature review please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5484#-:-Kf9e-QMhB9U5uviNQss:b-69ns55)*

**Comment by liangfok** [comment]
:lgtm: Very nice!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5484#-:-Kf9iz-LoBBjpk9JCixx:b-kerl87)*

**Comment by jwnimmer-tri** [comment]
:lgtm: automotive

+@david-german-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5484#-:-Kf9jK1p3tgwdKk-s6Zv:b-yfkpjo)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5484#-:-KfCReoKyEB1QbYH4n1F:bnfp4nl)*

**Pull request merged**
