### PR TITLE
[py systems] Allow simulator monitor to return None

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Similar to / derived from #17859

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18696)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review if you have time, please!
\cc @sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18696#-:-NN2v57L4732d1BxvRjH:b-ovpy92)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: fix) 

:lgtm: both +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18696#-:-NN2whG_70d1zMdvQc2H:b-5bv2ru)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/systems/test/analysis_test.py` line 183 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18696#-NN2xjbi084CxgA40eL6:-NN2xjbj8gNIfw8XnU1R:bu0xpf) ([raw file](https://github.com/RobotLocomotion/drake/blob/2c9836d2304fffa8d906eaa08b109670bf016776/bindings/pydrake/systems/test/analysis_test.py#L183)):*
> ```Python
>         def monitor_no_return(root_context):
>             nonlocal monitor_called_count
>             monitor_called_count += 10
> ```

nit The trick with "+10" here vs "+1" is a bit too subtle.

One fix would be to explain in a comment, but it's probably just as easy to use a different counter for each monitor.



_Suggestion:_
```Python
            nonlocal monitor_noreturn_called_count
            monitor_noreturn_called_count += 10
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18696)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/systems/test/analysis_test.py` line 183 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18696#-NN2xjbi084CxgA40eL6:-NN3Be3M4YZcK1CSeh2x:b-dtkds3) ([raw file](https://github.com/RobotLocomotion/drake/blob/2c9836d2304fffa8d906eaa08b109670bf016776/bindings/pydrake/systems/test/analysis_test.py#L183)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The trick with "+10" here vs "+1" is a bit too subtle.

One fix would be to explain in a comment, but it's probably just as easy to use a different counter for each monitor.
</blockquote></details>

Done, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18696)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
