### PR TITLE
Add Multiplexer primitive

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is a Multiplexer in the Simulink sense, not the EE sense.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3575)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSRzG1denC5gHWnXwJI:b-vawmhb)*

**Comment by RussTedrake** [comment]
:lgtm: (happy to count as a platform review) 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/multiplexer.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSXwZYEk2e6xuIp20fa:-KSXwZYEk2e6xuIp20fb:bdtmmt5) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L32)):*
> ```objc
>   /// ports where the i-th input has size `input_sizes[i]`, and one vector-
>   /// valued output port of size `sum(input_sizes)`.
>   explicit Multiplexer(std::vector<int> input_sizes);
> ```

:ok: 
would you imagine adding additional constructors / support for passing type information from the ports through to the output?  e.g. if the one of the inputs is a named vector that can be accessed with port.theta, is the output port going to simply be a vector, or could it still be a named vector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSXwzof5sxxB8b_PMql:b-rjxpf8)*

**Comment by soonho-tri** [comment]
lgtm. FYI, `get_input_vector` needs to be replaced by `EvalEigenVectorInput` because of the recent update in master branch.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KS_XqcCbBFQKGvbxmzo:b-i4siiu)*

**Comment by soonho-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KS_Y77U9pwnPmc1DPhe:bnfp4nl)*

**Comment by liangfok** [comment]
I performed a quick skim out of curiosity. Just one comment and non question, both non-blocking.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa7lx_-yKUStDbr3mb:-KSa7lx_-yKUStDbr3mc:b-bo6pmx) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
> ```objc
> class Multiplexer : public LeafSystem<T> {
>  public:
>   /// Constructs a %Multiplexer with `num_scalar_inputs` scalar-valued input
> ```

BTW: consider replacing "`num_scalar_inputs`" with "@p num_scalar_inputs" so the reader knows it's a parameter and not just a thing.

(Same comment below.)

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa88XrEBN_yAw2ycWw:-KSa88XrEBN_yAw2ycWx:b-yby2o5) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
> ```objc
> class Multiplexer : public LeafSystem<T> {
>  public:
>   /// Constructs a %Multiplexer with `num_scalar_inputs` scalar-valued input
> ```

BTW, are the inputs actually scalar values or vectors of scalar values where each vector is size 1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSa9j9gDpshEggoxf8y:b-xd6pwz)*

**Comment by jwnimmer-tri** [comment]
Thanks, +@russtedrake assigned as platform review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSYhq_08Lwjcj7Gce7g:b-naff0d)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa7lx_-yKUStDbr3mb:-KSaq6QVf7kJsKSEQXzX:b-8tmnco) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: consider replacing "`num_scalar_inputs`" with "@p num_scalar_inputs" so the reader knows it's a parameter and not just a thing.
> 
> (Same comment below.)
</details>
Rejected. The two markups format identically.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa88XrEBN_yAw2ycWw:-KSaqDvCMtZ0rgydPB1w:b-gmv8g9) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, are the inputs actually scalar values or vectors of scalar values where each vector is size 1?
</details>
The answer to this question is obvious in the code.

---

*[drake/systems/framework/primitives/multiplexer.h, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSXwZYEk2e6xuIp20fa:-KSYhwAnN6mw19OJtQ9D:bpo9v0i) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L32)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> :ok: 
> would you imagine adding additional constructors / support for passing type information from the ports through to the output?  e.g. if the one of the inputs is a named vector that can be accessed with port.theta, is the output port going to simply be a vector, or could it still be a named vector?
</details>
TTBOMK there is no great way to support that in System 2.0 in a general primitive like this one.  I can think of a few hacks to do it, but I think unless we add support for Subvector/Supervector in Output ports, any implementation of that here would be substandard.  If System 2.0 gains support for (string) signal names, we could certainly pass those names through here, but AIUI passing types through primitive blocks is not a feature.

Also, I don't know of a particular use case for preserving fluent vector types through a block like this.  Do we know of any yet?  Most cases I've thought of that would want that require a custom System already (perhaps it would subclass this System).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa7lx_-yKUStDbr3mb:-KSaqs55MTH2aGXjcoY2:bn94gap) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Rejected. The two markups format identically.
</details>
FTR, yes they format identically, but coders who read the code can tell the difference. This relates to @sherm1's comment about human LaTeX parsers.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa88XrEBN_yAw2ycWw:-KSar0g7tXWgdIvOQVpL:b-f86qn2) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The answer to this question is obvious in the code.
</details>
But it is not obvious from reading the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa88XrEBN_yAw2ycWw:-KSarJpicD0CwhS8zech:b-my2x63) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> But it is not obvious from reading the documentation.
</details>
One could argue that "scalar valued input ports" is a defect since it is in fact a vector that of scalar types of length 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa7lx_-yKUStDbr3mb:-KSarHrj_eVtEpreya0n:b-8wib1e) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> FTR, yes they format identically, but coders who read the code can tell the difference. This relates to @sherm1's comment about human LaTeX parsers.
</details>
Our verbal team agreement (which I can't seem to find in our style guide?) was that doxygen styling is optional, but if you use it, you must ensure that it formats correctly in the HTML output.  I believe that is code consistent with every rule we have.  If you want a different rule, feel free to propose one in a separate PR.  Otherwise, let's please keep the distracting noise in PRs to a minimum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by jwnimmer-tri** [comment]
Rebased to track System 2.0 API change.  PTAL.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSasrYjCTsB73-UR01X:b-ql194h)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/primitives/multiplexer.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-KSa7lx_-yKUStDbr3mb:-KSayT28MNhEq9hFDjN6:b-9ldl5y) ([raw file](https://github.com/robotlocomotion/drake/blob/ecb30962033457199cec04181e7b932662ad5701/drake/systems/framework/primitives/multiplexer.h#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Our verbal team agreement (which I can't seem to find in our style guide?) was that doxygen styling is optional, but if you use it, you must ensure that it formats correctly in the HTML output.  I believe that is code consistent with every rule we have.  If you want a different rule, feel free to propose one in a separate PR.  Otherwise, let's please keep the distracting noise in PRs to a minimum.
</details>
Done: #3584.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by jwnimmer-tri** [comment]
@soonho-tri please "mark all as reviewed" (the green eyeballs) when you are done.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSb5K4kVm-YsJRGOtvf:b-btiubf)*

**Comment by soonho-tri** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575#-:-KSb6r42V83dAaLu4CNW:b-896fix)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3575)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
ZOMG windows build finally finished after 93 minutes.

**Pull request merged**
