### PR TITLE
Mosek SOCP programming

### PR DESCRIPTION
**Pull request by alexdunyak**
As discussed in #3072, this adds an explicit option for second order conic programming, as well as a test for it.

Thanks,
Alex

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3144)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
Thanks for adding this type. 

I notice that you have added second order cone, but not the rotated second order cone yet. Do you plan to include that in the next PR?

In MosekWrapper.h, you create a wrapper for linear programming, quadratic programming, and semi-definite programming. Do you want to create a separate wrapper function for second-order cone programming? If I understand correctly, you want to treat second-order cone programming as a special case of semi-definite programming. But linear programming and quadratic programming are also special cases of semi-definite programming, and they have their specific wrapper. In my opinion, it is better to keep a separate MosekWrapper for second-order cone programming. SOC problem can use some special solver. It would also be cleaner for the user if you have a wrapper for each type of optimization problem, so the user can choose the right wrapper for their problem.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/constraint.h, line 155 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPK_uHXyStcJKlTaakA:-KPK_uHXyStcJKlTaakB:bfooilm) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/constraint.h#L155)):*
> ```objc
> /** A second order conic constraint that is a specific case of semidefinite
>  programming.
>  <pre>
> ```

Is this the right formulation? I thought second order cone constraint is like
x_0>=sqrt(sum_i x_i^2)

---

*[drake/solvers/mosek_wrapper.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPKapRTW02z0Z8utd96:-KPKapRTW02z0Z8utd97:b2t127f) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/mosek_wrapper.h#L31)):*
> ```objc
>  - "maxormin" -- must be set to "max" or "min"
>  - "problemtype" -- must be set to "linear", "quadratic", "sdp" or "soc"
>     + For "sdp", you also have to set "numbarvar", or the number of indices in
> ```

If I do not read the mosek documentation on http://docs.mosek.com/7.1/capi/Semidefinite_optimization.html, I find it hard to understand the meaning of "matrix term". Could you replace it as "the number of indices in the lower triangular part of your positive semidefinite matrix. So for n x n positive semidefinite matrix, numbarvar = n*(n+1)/2"

---

*[drake/solvers/optimization.h, line 617 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPKbX8JU5lRrQy5Z0Ph:-KPKbX8JU5lRrQy5Z0Pi:by62zb5) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/optimization.h#L617)):*
> ```objc
>    * - "numbarvar"
>        + Only for applicable for "sdp", it is the number of elements in the
>          lower triangle of your matrix component. Consider each index a separate
> ```

consider to replace this with "of your positive semidefinite matrix variable"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-:-KPKceWBw35QV3pqtS64:b6u5i5g)*

**Comment by alexdunyak** [comment]
I added a separate wrapper for SOCP, as well as rotated cones.

---

Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/constraint.h, line 155 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPK_uHXyStcJKlTaakA:-KPNxIBtF4HnSsQH0YQk:b-nqx26j) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/constraint.h#L155)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Is this the right formulation? I thought second order cone constraint is like
> x_0>=sqrt(sum_i x_i^2)
</details>
That is the more mathematically useful formulation, but practically speaking there's no check on that inside the constraint. I added a note anyways.

---

*[drake/solvers/mosek_wrapper.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPKapRTW02z0Z8utd96:-KPNy-dHLY9zaqkSKv81:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/mosek_wrapper.h#L31)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> If I do not read the mosek documentation on http://docs.mosek.com/7.1/capi/Semidefinite_optimization.html, I find it hard to understand the meaning of "matrix term". Could you replace it as "the number of indices in the lower triangular part of your positive semidefinite matrix. So for n x n positive semidefinite matrix, numbarvar = n*(n+1)/2"
</details>
Done.

---

*[drake/solvers/optimization.h, line 617 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPKbX8JU5lRrQy5Z0Ph:-KPNy8m_e6-Ovq19NGPW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/optimization.h#L617)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> consider to replace this with "of your positive semidefinite matrix variable"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-:-KPOe8pMW96pteMMMUgV:bepl3mk)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 5 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/solvers/constraint.h, line 155 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPK_uHXyStcJKlTaakA:-KPiLqtHZ3mgjtxl4SeE:b-3jutxn) ([raw file](https://github.com/robotlocomotion/drake/blob/d4f009a4821b40f69be938c4b815491cb84b423b/drake/solvers/constraint.h#L155)):*
<details><summary><i>Previously, alexdunyak wrote…</i></summary>
> That is the more mathematically useful formulation, but practically speaking there's no check on that inside the constraint. I added a note anyways.
</details>
Sorry, I do not understand the constraint lb <= b'*x <= ub. This is a linear constraint ,not a second order conic constraint. I think the definition of second order conic constraint is
```
x_0 >= sqrt(sum_i x_i^2)
```

For a constraint `lb<=b'*x<=ub`, we already have `LinearConstraint` to encode it, why you want to create the second order cone constraint the same as a linear constraint?

In fact, you can write the eval function of the second order cone constraint as
`eval(x) = x_0-sqrt(sum_i x_i^2)`, and the lower bound of this constraint is 0. If we add a second order conic constraint to a non-convex nonlinear optimization, we will need to evaluate this constraint.

---

*[drake/solvers/mosek_wrapper.cc, line 170 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPiNBcYroRm0LwdPGUh:-KPiNBcYroRm0LwdPGUi:ba3mc3r) ([raw file](https://github.com/robotlocomotion/drake/blob/552aefff446f4662ef9f59651bd3da19918f2153/drake/solvers/mosek_wrapper.cc#L170)):*
> ```cpp
>     const std::vector<double>& lower_variable_bounds,
>     double constant_eqn_term,
>     const SecondOrderConicConstraint& soc_objective,
> ```

I think the objective function for a second order conic programming is a linear function, not a second order conic constraint. In your `SecondOrderConicConstraint` class, you used a linear function, which I disagree on that formulation.

---

*[drake/solvers/mosek_wrapper.cc, line 193 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPiODE-JXKMj6TXAuR5:-KPiODE0zRPQ9sMNdUUv:bmihy8k) ([raw file](https://github.com/robotlocomotion/drake/blob/552aefff446f4662ef9f59651bd3da19918f2153/drake/solvers/mosek_wrapper.cc#L193)):*
> ```cpp
>   }
>   // add the equation to maximize to the environment.
>   AddSDPObjective(static_cast<SemidefiniteConstraint>(soc_objective));
> ```

Again, for second order conic programming, the objective function is just a linear constraint.

---

*[drake/solvers/mosek_wrapper.cc, line 757 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPiPTsTYegFEHl3JuZo:-KPiPTsTYegFEHl3JuZp:b-274lhu) ([raw file](https://github.com/robotlocomotion/drake/blob/552aefff446f4662ef9f59651bd3da19918f2153/drake/solvers/mosek_wrapper.cc#L757)):*
> ```cpp
>     DRAKE_ASSERT(prog.generic_costs().size() == 1);
>     SecondOrderConicConstraint *soc_objective =
>         dynamic_cast<SecondOrderConicConstraint *>(
> ```

Avoid RTTI with dynamic_cast, check the google style guide
https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_. Same as below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144)*

**Comment by jwnimmer-tri** [comment]
The windows build error looks like a CDash flake.
@drake-jenkins-bot retest this please.

**Comment by hongkai-dai** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/mosek_wrapper.cc, line 757 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-KPiPTsTYegFEHl3JuZo:-KQEt7BPmsJMP_sHIxUe:b32w0x) ([raw file](https://github.com/robotlocomotion/drake/blob/552aefff446f4662ef9f59651bd3da19918f2153/drake/solvers/mosek_wrapper.cc#L757)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Avoid RTTI with dynamic_cast, check the google style guide
> https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_. Same as below
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144)*

**Comment by ggould-tri** [comment]
Per email discussion:  @alexdunyak is no longer available due to school starting back up.  I will reassign this to someone in the manipulation team once people begin to return from vacation.

---

Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-:-KR-ESTdvfXbp5e0E7D3:b-as4ueb)*

**Comment by hongkai-dai** [comment]
I would like to take this. @RussTedrake and I talked to add mixed integer conic programming into Drake. And we aim to write the interface more like spotless.

**Comment by ggould-tri** [comment]
Excellent!  We don't have permissions to @alexdunyak 's fork, so you will need to fork his fork into a fork of your own.  Let me know if this gives you any trouble.

Once you have done that, and handled any of the outstanding review comments here, I think the best way forward is to close this PR and open a new one with your changes.

---

Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3144#-:-KR-Nvft2SzUV5mcMXYi:b-tbqba0)*

**Comment by hongkai-dai** [comment]
Will incorporate this PR while we solve the issue #3367

**Pull request closed without merging**
