### PR TITLE
fix a counter mismatch bug in lcm_driven_loop

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6824)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri +@naveenoid 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6824#-:-KrHajmXXyTrmRRvQUXJ:b-lc4m55)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6824#-:-KrHcX0yCyoLKuVHe00B:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6824#-:-KrHgeEgKYWBk3U3t298:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
I thought code not in `dev` required unit testing?

**Comment by siyuanfeng-tri** [comment]
There are two ways to look at this. The shorter excuse was that it's causing @sammy-tri and @naveenoid unhappiness, and this merge is no worse than the current. 
The longer excuse is that I don't have a reliable way to reproduce the unhappiness on CI. I need real lcm traffic, and the particular bug is also dependent on the polling thread's real-time-ness vs the publishing side. I will make an issue for this.

**Comment by jwnimmer-tri** [comment]
A fine solution might be to just document here in this PR why there wasn't any testing.  Sometimes there can't be, but it should be written down why for the record.

**Comment by siyuanfeng-tri** [comment]
Will do next time. Here is the issue https://github.com/RobotLocomotion/drake/issues/6828

**Comment by jwnimmer-tri** [comment]
So I think a stress test is good.  But really, with appropriate stubbing, you should be able to 100% deterministically reproduce any kind of data race you want in a focused unit test.

**Pull request merged**
