### PR TITLE
SDF parsing of meshes for visuals

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LCk8XVwAS8ufnmdi_Ti:b-4269ug)*

**Comment by SeanCurtis-TRI** [comment]
First pass

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpMxJmEEIUPS8CfjaU:-LCpMxJn55sH57XoqIez:bhp2l2s) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L38)):*
> ```cpp
> // Helper to return the value of a child of `element` named `child_name`.
> // An std::logic_error is thrown if `child_name` does not exist or if no value
> // was provided by the user that is, if `<child_name></child_name>` is empty.
> ```

BTW This is a very interesting use case -- logic error vs runtime error.

Logic error: a programmer invokes this method and selects a `child_name` whose value is to be extracted from the parsed file. A logic error would be justified if the programmer asked for the wrong child (or if they should've known not to look for that child).

Runtime error: if the caller has a published interface that says, "I deal with sdf files that have tag `child_name` and those tags must have a file. Then calling this becomes a file error. Certainly, if the tag exists in the file but there's no value, the programmer can't really modify their code to call this correctly or not call this -- it's a runtime error in the file.

Finally, the phrase "if no value was provided by the user" seems a bit misleading. The language suggests the "user of this method" and not the "creator of the file". But in reality, a tag with no value is the fault of the creator of the file.

Moral of the story:

1. I'd advocate throwing runtime errors (which is usually a good rule of thumb for parsers).
2. I'd suggest changing the phrase "if child_name does not exist or no value was provided by the user" to "if the <child_name> tag is missing from the sdf file, or the tag has a bad or missing value."

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpOxtF1KZ164UngwwD:-LCpOxtF1KZ164UngwwE:b3qb7dm) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L46)):*
> ```cpp
>             "<" + element->GetName() + ">.");
>   }
>   std::pair<T, bool> value_pair = element->Get<T>(child_name, T());
> ```

BTW I suspect this `bool` can be false for more reasons than "missing value". For example, if it's a vector 3 but only has two values. You probably want to change the error message to indicate an unknown problem with the value rather than simply stating that it's missing -- and change the doxygen as well.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpOH3h7WR-yB034sXy:-LCpOH3h7WR-yB034sXz:b6xwufe) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L49)):*
> ```cpp
>   if (value_pair.second == false) {
>     throw std::logic_error(
>         "No value provide for <" + child_name + "> within element "
> ```

FYI I don't suppose the ElementPtr has any backward reference to where in the file it came from? (E.g., line number.) It would be really helpful if this error included the line number of the valueless tag and if the previous error provided the line number of the `element` that didn't have the child tag.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpPXkcETk4vQfuyBLk:-LCpPXkcETk4vQfuyBLl:b-74v3gm) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L72)):*
> ```cpp
>         GetValueOrThrow<std::string>(mesh_element, "uri");
>     double scale = 1.0;
>     if (mesh_element->HasElement("scale")) {
> ```

FYI You do this test twice in quick succession. Once here and once inside `GetValueOrThrow`. That feels exceptionally odd. I'm not sure if this is a defect, just odd.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 77 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpRdeq8GUr1NNVJ6LA:-LCpRdeq8GUr1NNVJ6LB:bnb7n1a) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L77)):*
> ```cpp
>       // geometry::Mesh only supports isotropic scaling and therefore we enforce
>       // it.
>       DRAKE_DEMAND(scale_vector.X() == scale_vector.Y() &&
> ```

BTW This shouldn't be  DRAKE_DEMAND. This should be a `runtime_error` because it's a result of the sdf spec expressing semantics Drake doesn't support and, as such, the user should be informed appropriately.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpPvM953Nxqjv8dCNc:-LCpPvM953Nxqjv8dCNd:b8kbgo4) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L136)):*
> ```cpp
>   // We deal with the <mesh> case separately since sdf::Geometry still does not
>   // support it and marks <mesh> geometry with type sdf::GeometryType::EMPTY.
>   // TODO(amcastro-tri): get rid of all sdf::ElementPtr once
> ```

FYI "__all__ sdf::ElementPtr"? What if between now and when mesh is supported, you need to do this trick again to get a different piece of data?

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 139 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpQFjs9tzyE-G_h0U_:-LCpQFjs9tzyE-G_h0Ua:bl0apnp) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L139)):*
> ```cpp
>   // sdf::GeometryType::MESH is available.
>   sdf::ElementPtr geometry_element = sdf_geometry.Element();
>   DRAKE_ASSERT(geometry_element != nullptr);
> ```

BTW Consider making this a `DRAKE_DEMAND` -- this is parsing so the extra test isn't particularly going to hurt anyone, and we might as well get this feedback in release build.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpQVAO-0Ml2TtN0Vl5:-LCpQVAO-0Ml2TtN0Vl6:b-4du2v0) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L145)):*
> ```cpp
>   }
> 
>   // Nothing left to do, return nullptr signaling this is an empty visual.
> ```

BTW This comment doesn't match the code. Typically "nothing left to do" implies, just return a default value. But you do a test. So, there is something left to do; it's test and possibly return `nullptr`.

Also, given the documentation above, you indicated that the element for a mesh will be labeled "EMPTY". Probably worth putting a note that says its not *inside* this test to facilitate having a legitimate mesh block later. (Although, I'd still advocate putting that code *inside* this test and then when Mesh is properly supported, moving it outside.

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpR6Td7iHL377ZJsEn:-LCpR6Td7iHL377ZJsEo:b-6ue5b1) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L176)):*
> ```cpp
>   const Mesh* mesh = dynamic_cast<const Mesh*>(shape.get());
>   ASSERT_NE(mesh, nullptr);
>   EXPECT_EQ(mesh->filename(), absolute_file_path);
> ```

FYI This test will fail when you resolve the TODO in the parser detail. Not a defect, merely an observation. Although, if changes are made and this test *doesn't* fail, then you've got a much bigger problem -- it means your change didn't really do what it should. And it would be easy for someone to remove the TODO and think, because the unit tests pass, that everything is good.

It isn't immediately obvious to me how best to do that. If you think of one, great.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LCpSC4z7KZbW9MZD7Gz:b5snyhy)*

**Comment by amcastro-tri** [comment]
Thanks!, +@jwnimmer-tri for platform review please.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LCpiIbm9_EXIBXI_MAp:b-40h0in)*

**Comment by jwnimmer-tri** [comment]
FYI I'll wait to read until the next push, since there are several open discussions still.

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LCsOmi-5m-cWXT-CNmv:b-twgrwu)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpMxJmEEIUPS8CfjaU:-LCyEbnj40CUqAgFwq2Q:b7zqjor) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This is a very interesting use case -- logic error vs runtime error.

Logic error: a programmer invokes this method and selects a `child_name` whose value is to be extracted from the parsed file. A logic error would be justified if the programmer asked for the wrong child (or if they should've known not to look for that child).

Runtime error: if the caller has a published interface that says, "I deal with sdf files that have tag `child_name` and those tags must have a file. Then calling this becomes a file error. Certainly, if the tag exists in the file but there's no value, the programmer can't really modify their code to call this correctly or not call this -- it's a runtime error in the file.

Finally, the phrase "if no value was provided by the user" seems a bit misleading. The language suggests the "user of this method" and not the "creator of the file". But in reality, a tag with no value is the fault of the creator of the file.

Moral of the story:

1. I'd advocate throwing runtime errors (which is usually a good rule of thumb for parsers).
2. I'd suggest changing the phrase "if child_name does not exist or no value was provided by the user" to "if the <child_name> tag is missing from the sdf file, or the tag has a bad or missing value."
</blockquote></details>

Great, very thoughtfull, thanks for the detailed elaboration and suggestions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpOH3h7WR-yB034sXy:-LCyO-L881psT4ITClrP:b3qox7v) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I don't suppose the ElementPtr has any backward reference to where in the file it came from? (E.g., line number.) It would be really helpful if this error included the line number of the valueless tag and if the previous error provided the line number of the `element` that didn't have the child tag.
</blockquote></details>

I don't really know. I'll add a TODO for now. cc'ing @nkoenig, he's the expert.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 72 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpPXkcETk4vQfuyBLk:-LCyOikM0zugQj-BvpM6:b13osla) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L72)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI You do this test twice in quick succession. Once here and once inside `GetValueOrThrow`. That feels exceptionally odd. I'm not sure if this is a defect, just odd.
</blockquote></details>

I see your point. I think it is ok within this context but open to ideas.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpPvM953Nxqjv8dCNc:-LCyPpzpAZ4Brh_4gMAe:bwtmxr7) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L136)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI "__all__ sdf::ElementPtr"? What if between now and when mesh is supported, you need to do this trick again to get a different piece of data?
</blockquote></details>

@nkoenig is extending sdformat to provide semantically more meaningful returns for us (like say, meshes, frames, inertial properties, etc.). That will transfer the burden of types checking, format checking, error messages, etc. to sdformat. Within the scope of these files we should be assuming all the `sdf::` objects were properly error checked and are safe to use.
Of course we'll still need `ElementPtr` code when processing Drake custom tags. 

---

*[multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc, line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LCpR6Td7iHL377ZJsEn:-LCyTCoE-3vYoSI5P88N:b-hborjm) ([raw file](https://github.com/robotlocomotion/drake/blob/10173f97a8633b2ad475a8d96773897f7e444e99/multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc#L176)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI This test will fail when you resolve the TODO in the parser detail. Not a defect, merely an observation. Although, if changes are made and this test *doesn't* fail, then you've got a much bigger problem -- it means your change didn't really do what it should. And it would be easy for someone to remove the TODO and think, because the unit tests pass, that everything is good.

It isn't immediately obvious to me how best to do that. If you think of one, great.
</blockquote></details>

For now I added a TODO. I wouldn't worry much about the case "it might not break when we update the functionality to allow relative paths". I assure you many other things break when you try that with a real SDF file containing real paths. We'll see it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by jwnimmer-tri** [comment]
*[tools/workspace/sdformat/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1i3axBBUzq3oZzvuw:-LD1i3axBBUzq3oZzvux:bqbtuq) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/tools/workspace/sdformat/repository.bzl#L11)):*
> ```Python
>         name = name,
>         repository = "osrf/sdformat",
>         commit = "e5fd14d953aa",
> ```

When you update an external, you need to test on macOS CI. Please do so.

FYI I also usually advise to do this bump in a separate PR, merged first, so that you can immediately get it into CI and tested on all variants, before you add parsing code that depends on it -- its less to revert then if something fails.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1psZg4yLNgbf-uHpx:-LD1psZg4yLNgbf-uHpy:b-dz451r) (no related file):*
FYI As an aside...

The sdformat abbreviation `using ElementPtr = std::shared_ptr<Element>;` is an abomination.  It is very important to distinguish `std::shared_ptr<Element>` and `std::shared_ptr<const Element>`, and typedef obscures that reasoning and encourages the wrong default choice.  The `const` (second) one is a relatively safe and efficient way to pass readonly data to multiple consumers; the non-`const` (first) one is relatively dangerous a design choice that should be shunned.  To the extent possible, I would advocate that our parsing code use either `std::shared_ptr<const Element>` or even just the simple `const Element&` when processing the _read-only_ parse tree of an SDF.  It will prevent an entire class of mistakes where somebody accidentally modifies something that shouldn't be modified.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1ufP90wo_utBvKatY:-LD1ufPA0dt4t36OKYHD:bddjpsx) (no related file):*
None of the error paths appear to be unit tested.  Testing parser errors is one of the most important aspects of writing a parser.  Please at least add TODOs and/or issues.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1qcpdAq7jO3j8HjwR:-LD1qcpdAq7jO3j8HjwS:b-3p9mkn) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L26)):*
> ```cpp
> // Helper to return the child element of `element` named `child_name`.
> // Returns nullptr if not present.
> sdf::ElementPtr GetElementPointerOrNullPtr(
> ```

FYI The world "child" in the function name might help clarity.  (Personally I would call it `MaybeGetChildElement`, which is concise yet descriptive.)

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 67 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1tsWz8clDzJzWiG8N:-LD1tsWz8clDzJzWiG8O:b-29zxd3) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L67)):*
> ```cpp
>   // sdf::GeometryType::MESH is available.
>   sdf::ElementPtr geometry_element = sdf_geometry.Element();
>   DRAKE_ASSERT(geometry_element != nullptr);
> ```

BTW Surely this isn't part of an inner loop?  (`DEMAND`)

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 80 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1uNvr37jsHw-avWpq:-LD1uNvsD1r-IFzogHGn:byqonsf) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L80)):*
> ```cpp
>       // it.
>       if (!(scale_vector.X() == scale_vector.Y() &&
>           scale_vector.X() == scale_vector.Z())) {
> ```

BTW Wrong indent.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by SeanCurtis-TRI** [comment]
I concur with @jwnimmer-tri's comments.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD22l1s0yLAubjH-Fk4:-LD22l1s0yLAubjH-Fk5:b-i83hgj) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L144)):*
> ```cpp
>   // Therefore, there are two reasons we can have an EMPTY type:
>   //   1) The file does specify a mesh.
>   //   2) The file truly specifies and EMPTY geometry.
> ```

BTW typo s/and/an

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LCsZ7WJ0nAHKFg5VgcC:b-mjd58b)*

**Comment by amcastro-tri** [comment]
Thanks for the reviews guys. Back to you.

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1psZg4yLNgbf-uHpx:-LD2V0Xk72aQNT6_4ewK:bo6egos) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI As an aside...

The sdformat abbreviation `using ElementPtr = std::shared_ptr<Element>;` is an abomination.  It is very important to distinguish `std::shared_ptr<Element>` and `std::shared_ptr<const Element>`, and typedef obscures that reasoning and encourages the wrong default choice.  The `const` (second) one is a relatively safe and efficient way to pass readonly data to multiple consumers; the non-`const` (first) one is relatively dangerous a design choice that should be shunned.  To the extent possible, I would advocate that our parsing code use either `std::shared_ptr<const Element>` or even just the simple `const Element&` when processing the _read-only_ parse tree of an SDF.  It will prevent an entire class of mistakes where somebody accidentally modifies something that shouldn't be modified.
</blockquote></details>

Thanks, I was wondering about what was best in this case. I'm glad we agree on this.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1ufP90wo_utBvKatY:-LD2V8Hb5j5p-GT_lgXv:bxmdum0) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

None of the error paths appear to be unit tested.  Testing parser errors is one of the most important aspects of writing a parser.  Please at least add TODOs and/or issues.
</blockquote></details>

I completely agree with you on this one, though I'll add TODO's for now. My days only have a finite number of hours for me to also tackle writing a parser and its unit tests. I am trying to encourage users of this new functionality to improve this parser and also its unit testing.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1qcpdAq7jO3j8HjwR:-LD2Z-eZ149F5AFeHM6O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The world "child" in the function name might help clarity.  (Personally I would call it `MaybeGetChildElement`, which is concise yet descriptive.)
</blockquote></details>

Done.

---

*[tools/workspace/sdformat/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1i3axBBUzq3oZzvuw:-LD2_pmL0qmikhF2vvCq:bbq75gk) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/tools/workspace/sdformat/repository.bzl#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When you update an external, you need to test on macOS CI. Please do so.

FYI I also usually advise to do this bump in a separate PR, merged first, so that you can immediately get it into CI and tested on all variants, before you add parsing code that depends on it -- its less to revert then if something fails.
</blockquote></details>

#8842 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LD2aT5c2XufTCBw2-AT:b-bzmhn2)*

**Comment by jwnimmer-tri** [comment]
:lgtm: after #8842 merges first.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1ufP90wo_utBvKatY:-LD2c5_sAiIJvS6Ps8SA:b-h6ncpd) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I completely agree with you on this one, though I'll add TODO's for now. My days only have a finite number of hours for me to also tackle writing a parser and its unit tests. I am trying to encourage users of this new functionality to improve this parser and also its unit testing.
</blockquote></details>

Yup, I definitely support working incrementally.  But then its super-important to track what is incomplete / what shortcuts got taken.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 34 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD2bp_9--hRPdZXTAQL:-LD2bp_9--hRPdZXTAQM:b-1rns1a) ([raw file](https://github.com/robotlocomotion/drake/blob/3f409242b9743765107233c06d6ab3e0d85a0708/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L34)):*
> ```cpp
>     // a const version of GetElement(). However, the snippet below still
>     // guarantees "element" is not changed as promised by this method's
>     // signature.
> ```

BTW Could you please open an issue to have SDFormat add such a method?  We should (eventually) get rid of this cast.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LD2cLGF9tOI-2_OyxaI:borxoj5)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/parsing/scene_graph_parser_detail.cc, line 34 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD2bp_9--hRPdZXTAQL:-LD3BMebCU_vFFrsA7zy:b-ldh77x) ([raw file](https://github.com/robotlocomotion/drake/blob/3f409242b9743765107233c06d6ab3e0d85a0708/multibody/multibody_tree/parsing/scene_graph_parser_detail.cc#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Could you please open an issue to have SDFormat add such a method?  We should (eventually) get rid of this cast.
</blockquote></details>

BTW https://bitbucket.org/osrf/sdformat/issues/188/const-accessors-in-sdformat

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/sdformat/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1i3axBBUzq3oZzvuw:-LD3C68FEkv-32Vexr_o:baw0rit) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/tools/workspace/sdformat/repository.bzl#L11)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

#8842 
</blockquote></details>

Great.  This PR just needs a rebase / merge up to master, so that it shows up as no changes to this file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/sdformat/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8828#-LD1i3axBBUzq3oZzvuw:-LD3KZYA3LgRL4jQJVNp:b-z2beg1) ([raw file](https://github.com/robotlocomotion/drake/blob/454691ed896ee6b9d20dc50629e52ca703e53f37/tools/workspace/sdformat/repository.bzl#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Great.  This PR just needs a rebase / merge up to master, so that it shows up as no changes to this file.
</blockquote></details>

Woops, I forgot to do that. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8828#-:-LD3dGpZ0WokfL-Ytcwc:bmxilld)*

**Pull request merged**
