### PR TITLE
Rename workspace files for consistency

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The conventional new names within `tools/workspace/foo` are now:
- `package.bzl` for the repository_rule;
- `package.BUILD.bazel` for the repository build_file;
- `package.cps` or `package-create-cps.py` for the cmake install.

Relates #7259.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7733)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per schedule, please.

@jamiesnape if you want to spot-check a few files for sanity, that might also make sense?

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 135 of 135 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/README.md, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7733#-L2aNKPJsW0_icR6aSsZ:-L2aNKPKu-z865ELt29d:b39r09d) ([raw file](https://github.com/robotlocomotion/drake/blob/32679624dc571ad15ae0d3bdc1cb68da8d4c8f3a/tools/workspace/README.md#L30)):*
> ```Markdown
>   https://docs.bazel.build/versions/master/skylark/repository_rules.html
> 
> Files named `package.cps` are written the in Common Package Specification
> ```

BTW, I think adding a hyperlink to https://mwoehlke.github.io/cps/ is helpful for readers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7733#-:-L2aNTXbOqqPW9upeV-h:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 79 of 80 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/README.md, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7733#-L2aNKPJsW0_icR6aSsZ:-L2aP0VNuUNr3wpU-XHV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32679624dc571ad15ae0d3bdc1cb68da8d4c8f3a/tools/workspace/README.md#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think adding a hyperlink to https://mwoehlke.github.io/cps/ is helpful for readers.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7733)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7733)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-cmake-experimental please

**Comment by soonho-tri** [comment]
Reviewed 3 of 135 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7733)*

**Comment by jwnimmer-tri** [comment]
@mac-sierra-clang-cmake-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-cmake-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
This can merge now once the default builds pass.

The macOS build of the prior push passed.  I've since rebased for conflicts and confirmed in reviewable that only base commit changes happened.  Since master on macOS is broken right now I'm not going to retest it here in this PR.

**Comment by soonho-tri** [comment]
Testing a macOS build locally. Will merge it when it passes.

---

Reviewed 4 of 135 files at r1, 5 of 11 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7733#-:-L2bd8t5B-dXJYypzSkz:b-im5nee)*

**Pull request merged**
