### PR TITLE
[setup] Upgrade from clang-12 to clang-14 on Ubuntu

### LINKED ISSUE #19024: Upgrade to clang-14 on Jammy
In general, we always want to be using the latest Clang to get the best language diagnostics, and so that Ubuntu will flag LLVM compatibility problems before our post-merge macOS builds start exploding.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19024.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19030)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

**Comment by calderpg-tri** [comment]
Nothing obvious stands out. I can reproduce locally, will update when I know more.

**Comment by calderpg-tri** [comment]
Fixed in CRU, update to commit `89435ebf4621f4e92d3b4c2a18aec7fa91e0cb75` for the fix.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@ggould-tri for platform review, please.

\CC @SeanCurtis-TRI @hongkai-dai FYI

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19030#-:-NR3sIQY2CSM1z65-AvR:bnfp4nl)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19030#-:-NR4CUg95dTsjmiZPj3K:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
