### PR TITLE
Add drake-visualizer dependencies to install scripts

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6810)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@soonho-tri for feature and platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm:

The 16.04 is just a shuffle, so I don't need to re-test locally.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6810#-:-KrBTLi2QBN99ZWKEe87:b6fj9gz)*

**Comment by soonho-tri** [comment]
:lgtm: 
@jamiesnape , I tested the `install_prereqs.sh` but couldn't test `drake_visualizer` on my macs because of https://github.com/RobotLocomotion/drake/issues/6784.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6810#-:-KrBeCkgScI7WdPU9EH9:b-pfuuzh)*

**Comment by soonho-tri** [comment]
I just added "do not merge". Let's wait for the outcome of `mac-sierra-unprovisioned-clang-bazel-experimental`.

**Pull request merged**
