### PR TITLE
[example] Change deformable box to a torus

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Change the deformable geometry to be grasped in our only deformable example to a non-convex torus to showcase the ability to handle non-convex geometries.

This PR introduces two new data files
- simple_gripper.sdf is the same as the one in the simple_gripper example except that it's weld to the world so that the fingers point in -z direction to allow grasping the torus through the hold in the middle.
- torus.vtk replaces box.vtk.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@damrongguoy for feature review please.
\cc @russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305#-:-NGcu1CsEUVNRI2jWEVQ:b-qdklym)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGi0Sie89sYGsD_E1a2:-NGi0Sie89sYGsD_E1a3:b-7ubrkj) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L4)):*
> ```
> <sdf version="1.7">
>

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with some nits mostly about changing the word `box` to `torus`.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305#-:-NGsUejF1eAa2dBIVjd5:bq2ghxn)* status: 9 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake and @xuchenhan-tri)

___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGsSE14CXnN1ciVOwdM:-NGsSE1546IcMEdFUI2-:bh6zoqk) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L1)):*
BTW, I checked the diff between this file and the original one
```
diff examples/simple_gripper/simple_gripper.sdf examples/multibody/deformable_torus/simple_gripper.sdf
```
and saw minor diffs, so I approved this file without reading much in details.

```
(pr/18305)$ diff examples/simple_gripper/simple_gripper.sdf examples/multibody/deformable_torus/simple_gripper.sdf 
4,5c4
<        simple_gripper.cc and deformable_box.cc and therefore these files must
<        be kept in sync.
---
>        deformable_box.cc and therefore these files must be kept in sync.
15,22c14
<        geometry but not contact geometry, allowing the demo in
<        simple_gripper.cc to add contact geometry programmatically.
< 
<        simple_gripper.cc adds pads to the model programatically. Including the
<        thickness of these pads, 6 mm, and the offset from the center of the
<        corresponding finger, 4.6 mm, each finger is positioned along the x-axis
<        such that at q=0 the pads from each finger barely touch. This is 6 mm +
<        4.6 mm = 10.5 mm.
---
>        geometry but not contact geometry.
26c18
<     <pose>0.0555 0 0.0505 0 0 1.57</pose>
---
>     <pose>0.0 0.06 0.08 -1.57 0 1.57</pose>
48c40
<         <xyz expressed_in="__model__">0 0 1</xyz>
---
>         <xyz expressed_in="__model__">0 -1 0</xyz>

```
___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGsT0td1BRNuzyKER52:-NGsT0td1BRNuzyKER53:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L4)):*
> ```
> <sdf version="1.7">
>

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305#-:-NGsaoj5EphVn1NlK5zl:b3yut2i)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @DamrongGuoy, @jwnimmer-tri, and @RussTedrake)

___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGsSE14CXnN1ciVOwdM:-NGsa1x_0UAO7v6cdTea:b-tamr7d) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L1)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, I checked the diff between this file and the original one
```
diff examples/simple_gripper/simple_gripper.sdf examples/multibody/deformable_torus/simple_gripper.sdf
```
and saw minor diffs, so I approved this file without reading much in details.

```
(pr/18305)$ diff examples/simple_gripper/simple_gripper.sdf examples/multibody/deformable_torus/simple_gripper.sdf 
4,5c4
<        simple_gripper.cc and deformable_box.cc and therefore these files must
<        be kept in sync.
---
>        deformable_box.cc and therefore these files must be kept in sync.
15,22c14
<        geometry but not contact geometry, allowing the demo in
<        simple_gripper.cc to add contact geometry programmatically.
< 
<        simple_gripper.cc adds pads to the model programatically. Including the
<        thickness of these pads, 6 mm, and the offset from the center of the
<        corresponding finger, 4.6 mm, each finger is positioned along the x-axis
<        such that at q=0 the pads from each finger barely touch. This is 6 mm +
<        4.6 mm = 10.5 mm.
---
>        geometry but not contact geometry.
26c18
<     <pose>0.0555 0 0.0505 0 0 1.57</pose>
---
>     <pose>0.0 0.06 0.08 -1.57 0 1.57</pose>
48c40
<         <xyz expressed_in="__model__">0 0 1</xyz>
---
>         <xyz expressed_in="__model__">0 -1 0</xyz>

```
</blockquote></details>

Yes, I made a local copy to change the pose of the gripper since there's no way to unweld and reweld.
___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGi0Sie89sYGsD_E1a2:-NGsaBDO-M-JlQhQHZel:b9lupxm) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L4)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I didn't know about it before. Does it also come with a wrist dof as does this simple gripper? I didn't find that in the SDF. Or do I have to attach it to an arm to pick up the object?
</blockquote></details>

I'll punt and add a TODO for now.
___
*[`examples/multibody/deformable_torus/simple_gripper.sdf` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGsT0td1BRNuzyKER52:-NGsaI0v-ORUCDDmAbMU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/simple_gripper.sdf#L4)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`examples/multibody/deformable_torus/deformable_torus.cc` line 209 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGsFIsP09rzNMGq6EYh:-NGs_xGX3_Hfnf8yv1OK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8fbe6ecf36f4e2e94146f25537529de6e4b8ebff/examples/multibody/deformable_torus/deformable_torus.cc#L209)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit, consider "Thickness" or "Minor diameter"?  I wasn't sure which cross sections.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305#-:-NGvnto4-PUdspkmicxh:b-vtj4vo)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGvmyvMCnJ7S3U_WOXS:-NGvmyvMCnJ7S3U_WOXT:b9jah84) (no related file):*
> simple_gripper.sdf is the same as the one in the simple_gripper example except that it's weld to the world so that the fingers point in -z direction to allow grasping the torus through the hold in the middle.

It's okay to defer fixing this to a TODO comment for now, but this copy-paste of model files only to change their posture is _not_ a best practice.  The `simple_gripper.sdf` should _not_ hard-code a weld joint to the world.  We should be loading the gripper file using a `dmd.yaml` file (or more likely, inline string) that postures the weld as part of the _example program itself_.

___
___
*[`examples/multibody/deformable_torus/deformable_torus.cc` line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGvmSXcCmzh-DIF0lxq:-NGvmSXcCmzh-DIF0lxr:b-jdujdp) ([raw file](https://github.com/robotlocomotion/drake/blob/25bb0d9df5500076c923dd065f10a218d36febb4/examples/multibody/deformable_torus/deformable_torus.cc#L55)):*
> ```cpp
> namespace examples {
> namespace multibody {
> namespace deformable_torus {
> ```

FYI There's no need for such long namespaces; `drake::example::{anonyomous}` is generally sufficient.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGvmyvMCnJ7S3U_WOXS:-NGwddiy03Ca0DI--zhd:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> simple_gripper.sdf is the same as the one in the simple_gripper example except that it's weld to the world so that the fingers point in -z direction to allow grasping the torus through the hold in the middle.

It's okay to defer fixing this to a TODO comment for now, but this copy-paste of model files only to change their posture is _not_ a best practice.  The `simple_gripper.sdf` should _not_ hard-code a weld joint to the world.  We should be loading the gripper file using a `dmd.yaml` file (or more likely, inline string) that postures the weld as part of the _example program itself_.
</blockquote></details>

Done.

___
___
*[`examples/multibody/deformable_torus/deformable_torus.cc` line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18305#-NGvmSXcCmzh-DIF0lxq:-NGwdc_PESENOxBl5fNR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25bb0d9df5500076c923dd065f10a218d36febb4/examples/multibody/deformable_torus/deformable_torus.cc#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI There's no need for such long namespaces; `drake::example::{anonyomous}` is generally sufficient.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18305)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),DamrongGuoy (waiting on @xuchenhan-tri)

**Pull request merged**
