### PR TITLE
Use completeOrthogonalDecomposition instead of jacobiSvd when solving with position constraints

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8834)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@hongkai-dai for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8834#-:-LCoJjZ6AbhsJPpCmw6G:b-fcupkv)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8834#-:-LCoa53R-NPIiVZFGMpv:bozh2sc)*

**Comment by sherm1** [comment]
Platform :lgtm: assuming this actually _does_ improve performance. Does it?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8834#-:-LCoqg8309vwPYPQ-MRe:b-o3kcas)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8834#-:-LD1sJzA6IQx6qpfueBj:b-rxj27t)*

**Pull request merged**
