### PR TITLE
Add instructions and profile program for computing contact surface

### PR DESCRIPTION
**Pull request by tehbelinda**
Use `perf` to record and report profiling data, and add docs on how to run and interpret the program. Based off the simple contact vis in scene graph examples.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12771)

### CODE REVIEW

**Comment by tehbelinda** [comment]
@seancurtis-tri for feature review please

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/simple_contact_surface_profile.cc, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M119Lln8tScxCAHnOEs:-M1YLao93Bx-vf-Hkm3Y:b5uqmuv) ([raw file](https://github.com/robotlocomotion/drake/blob/13e2ff02aa33f7fe843232bbac482c3437331bec/geometry/benchmarking/simple_contact_surface_profile.cc#L111)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The results you got on your laptop are quite different from what I got on my desktop (and I'll try it again on my laptop). My single biggest culprit was  `DependencyTracker::NotifySubscriber`. That accounted for 15.62% and the two geometry calculations you allude to were around 8% each. 

We'll want to consider the variability there and think about the type of analysis we do  and how we report it. It strongly suggests that detailed analysis doesn't belong in this file.
</blockquote></details>

I think I might have done this with the sphere edge length at 0.5, so the ratios were a little different - are they more similar if you do that?

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/simple_contact_surface_profile.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M116lKT6fZn4t7ugDbb:-M1eBGD1B-Xc2ssrMId_:b2uvfoo) ([raw file](https://github.com/robotlocomotion/drake/blob/13e2ff02aa33f7fe843232bbac482c3437331bec/geometry/benchmarking/simple_contact_surface_profile.cc#L42)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Two things -- 

1. The real time flag can be documented as having no effect if visualization is not enabled.
2. The suggestion of making the visualization optional is based on the fact that at every time step, we convert the SG state into an LCM message and broadcast it. It doesn't seem worthwhile to measure that cost as it has nothing to do with what we're actually trying to assess. However, that act is currently the *only* operation that causes contact to get evaluated. So, you'd have to replace it with a system that has a similar publish rate and evaluates contact. (i.e., the minimum amount of functionality to guarantee we're evaluating contact).
</blockquote></details>

Hmm ok, re 2. I may not fully understand how Systems work... but doesn't the ContactResultMaker system (not just the ConnectDrakeVisualizer System) also trigger evaluation since it's connected to SG's output port? ie in this section:
```
  auto& contact_results = *builder.AddSystem<ContactResultMaker>();
  builder.Connect(scene_graph.get_query_output_port(),
                  contact_results.get_geometry_query_port());
```
It already produces the type `lcmt_contact_results_for_viz`. Or are you saying to replace that system too?

I was trying to find other examples of simple systems and was looking at Acrobot, but that still produces lcm messages...do you know of any examples that don't? Would something like just logging it out suffice?

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/simple_contact_surface_profile.cc, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M116lKT6fZn4t7ugDbb:-M1f_vg327oS-_m6JG6z:bax6ctb) ([raw file](https://github.com/robotlocomotion/drake/blob/13e2ff02aa33f7fe843232bbac482c3437331bec/geometry/benchmarking/simple_contact_surface_profile.cc#L42)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It's a chain reaction:

The LCM publisher has a periodic public event. When that fires, it pulls its input, which is the `ContactResultMaker` which, in turn, pulls *its* input, which is SG. So, if LCM publisher wasn't actively attempting to publish at 60 Hz, we would never compute any contact.

I'd say let's just put the whole "optional visualization" on the back burner. The more I think about it, the less I'm convinced it'll be worth it. So, I'm marking myself satisfied and we'll chalk this up as a pedagogical moment for you to learn a bit more about the system framework; yeah. That was the plan the whole time.
</blockquote></details>

Haha alright, that sounds good to me, it'd be helpful to learn more :P I'll at least put a todo in there so I don't forget about it

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M11DQ5o-0TFfd0KA6DZ:-M1frw3KCVbgrV_4sl77:b2329bx) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

We've got two big challenges to consider:

1. Variability from machine to machine (see notes below).
2. When reporting *percentages* like perf does, we end up with some difficulty in doing apples-to-apples comparisons. At the very least we need to make sure we're well correlated with how big the pie is that we're slicing up. One can make a change in code and recognize that the code I touched is now a much smaller percentage of the whole, but has the whole improved? How much has it improved? This will still require consideration.
</blockquote></details>

For overall time details, the user can run perf stat, I'll add that as an option in the docs

---

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M11DQ5o-0TFfd0KA6DZ:-M1hSCt8EPBu4dECBiY4:blmweg2) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't think you're allowed to solve an entire *paragraph* of problem statement with just a couple of words. Can you dress that up a bit more?  ;)
</blockquote></details>

Oh I wrote a bunch in the file itself, pushed now! Let me know what you think of that?

---

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M1kypk1EZuYyxZathzH:-M1mCwSqBzBa2g6oVte3:brubrfl) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

From conversation we started in Slack. I'll paste here per @seancurtis-tri's request.

what's the difference between the "perf" tool here vs. Valgrind? Wondering if I should use that instead? 

</blockquote></details>

There's a nice summary here: http://euccas.github.io/blog/20170827/cpu-profiling-tools-on-linux.html 
It sounds like the main difference is perf uses sampling whereas valgrind uses instrumentation. As for why you might want to use one over the other, this thread sums it up well: https://news.ycombinator.com/item?id=12060362 
So I guess the answer depends on what you want to dig into further :)

---

**Comment by tehbelinda** [comment]
___
*[geometry/benchmarking/simple_contact_surface_profile.cc, line 111 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M119Lln8tScxCAHnOEs:-M2-DhbX9EDfsPHg_lzF:b-abc581) ([raw file](https://github.com/robotlocomotion/drake/blob/13e2ff02aa33f7fe843232bbac482c3437331bec/geometry/benchmarking/simple_contact_surface_profile.cc#L111)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

It might suggest something else -- maybe this documentation shouldn't do too much deep analysis if the result is going to be so variable. The analysis should be just enough that anything that isn't obvious about *how* to interpret the data should be illustrated. But the conclusions for a particular run shouldn't necessarily be carved in stone (or given too much weight).
</blockquote></details>

It's pretty consistent if I re-run it now. How about I just change the wording to `One of the top culprits` and just mention the ClipXXX functions?

**Comment by tehbelinda** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/12771#-M2-79ZL7xyjbYOtwDbN:-M25EH9iAVhOgZmGEBDX:btwkmr1) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Here's a meta question. Ultimately, the point of profiling is to compare two variations of something (with all other aspects held constant). And, generally, we're assuming for a fixed computer and OS, what is the impact of a code change. Have you considered what that workflow might look like? I.e., how to use this to assess the impact of an algorithm change?
</blockquote></details>

I think running perf stats with repetitions in between each algorithm change gives a quantifiable assessment? Then perf record/report can be used to dig into why the times have changed

---

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI should this still be open?  Are you going to push fixes here, or open it as a new PR?

**Comment by SeanCurtis-TRI** [comment]
We'll close it for now.

**Pull request closed without merging**
