### PR TITLE
[pydrake] Implement __repr__ for RollPitchYaw

### PR DESCRIPTION
**Pull request by RussTedrake**
+@SeanCurtis-TRI for both reviews, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18020)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[`bindings/pydrake/_math_extra.py` line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18020#-NDQE2WtEME0z7aQq2JQ:-NDQE2WtEME0z7aQq2JR:b-2bdjd8) ([raw file](https://github.com/robotlocomotion/drake/blob/92379ce0de00e024ef1c85d7e06ee26ff4eeeaea/bindings/pydrake/_math_extra.py#L119)):*
> ```Python
> 
> def _roll_pitch_yaw_repr(rpy):
>     return (f"RollPitchYaw(r={rpy.roll_angle()}, p={rpy.pitch_angle()}, "
> ```

nit This formats the r=,p=,y= arguments using their `str()` format, instead of their `repr()` format.

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review.  We can leave Sean as platform -(status: single reviewer ok).

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18020#-:-NDTB6-EBgycyoDMNqDt:bj5fuoe)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[`bindings/pydrake/_math_extra.py` line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18020#-NDQE2WtEME0z7aQq2JQ:-NDTBAS2AYyCAz4R5sH1:b3tthh7) ([raw file](https://github.com/robotlocomotion/drake/blob/92379ce0de00e024ef1c85d7e06ee26ff4eeeaea/bindings/pydrake/_math_extra.py#L119)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Thanks.  I hadn't appreciated that they were different for the basic types.

Might you be willing to serve as the reviewer, since you've come this far?
</blockquote></details>

Oops, I also just noticed a second problem: RollPitchYaw does not offer any constructor that takes `r`, `p`, `y` individually.  It has either `rpy` as a vector or `roll`, `pitch`, `yaw` one by one.

Apparently this is tricky enough that we really need a unit test.  See the existing `roundtrip` for case `RotationMatrix` for an example.  In essence, we need to check the `eval(repr(roll_pitch_yaw))` to prove the repr invariant -- that eval'ing a repr gives you back something equal to the original object.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18020)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/_math_extra.py` line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18020#-NDQE2WtEME0z7aQq2JQ:-NDU0TudDWVBc4HUyF0-:b-fxy4sg) ([raw file](https://github.com/robotlocomotion/drake/blob/92379ce0de00e024ef1c85d7e06ee26ff4eeeaea/bindings/pydrake/_math_extra.py#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, I also just noticed a second problem: RollPitchYaw does not offer any constructor that takes `r`, `p`, `y` individually.  It has either `rpy` as a vector or `roll`, `pitch`, `yaw` one by one.

Apparently this is tricky enough that we really need a unit test.  See the existing `roundtrip` for case `RotationMatrix` for an example.  In essence, we need to check the `eval(repr(roll_pitch_yaw))` to prove the repr invariant -- that eval'ing a repr gives you back something equal to the original object.
</blockquote></details>

I agree with all of the above.

**Review by jwnimmer-tri — COMMENTED** [review]
(We'll squash-merge after badging.)

:lgtm: feature.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18020#-:-NDYIaLf1fS_H5TTzqfZ:b-govfcv)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18020#-:-NDYTr2p8I43pVAYzbAw:bmxilld)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request merged**
