### PR TITLE
Slightly reduce test code verbosity

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5203)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdCoU1f6fzXKhTyjJ42:b-qkkrqr)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdDlgGWuNwqZOwHz4R6:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/dragway/test/dragway_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-KdDlqrMA4oD5V64A9S4:-KdDlqrMA4oD5V64A9S5:bkmwq6n) ([raw file](https://github.com/robotlocomotion/drake/blob/adc95ac316f384f7df329055ed7613b02e74a3ec/drake/automotive/maliput/dragway/test/dragway_test.cc#L33)):*
> ```cpp
>     ExpectedLaneParameters result{};
>     if (num_lanes == 1) {
>       result.y_offset = 0.0;
> ```

BTW, perhaps including the ASCII art here would help future readers understand why these values are correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/maliput/dragway/test/dragway_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-KdDlqrMA4oD5V64A9S4:-KdDm5CkjiJaLlJpzkIw:bsum7pu) ([raw file](https://github.com/robotlocomotion/drake/blob/adc95ac316f384f7df329055ed7613b02e74a3ec/drake/automotive/maliput/dragway/test/dragway_test.cc#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, perhaps including the ASCII art here would help future readers understand why these values are correct.
</blockquote></details>

If that's true (and probably it is; I will ponder it a bit), then it should appear in the Dragway class overview (RoadGeometry, I guess) and not here.  Stay tuned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/dragway/test/dragway_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-KdDlqrMA4oD5V64A9S4:-KdDnPMwvCdi-CDlKc_r:b-8bco7o) ([raw file](https://github.com/robotlocomotion/drake/blob/adc95ac316f384f7df329055ed7613b02e74a3ec/drake/automotive/maliput/dragway/test/dragway_test.cc#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If that's true (and probably it is; I will ponder it a bit), then it should appear in the Dragway class overview (RoadGeometry, I guess) and not here.  Stay tuned.
</blockquote></details>

Maybe this ASCII art should be moved to `dragway::RoadGeometry`?

https://github.com/RobotLocomotion/drake/blob/1bc3190cc5e1cf1c020f0914ab466b06bd216445/drake/automotive/maliput/dragway/segment.h#L26

Then, maybe we can add a "For example, here are the parameters for one-lane and two-lane dragways."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/dragway/test/dragway_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-KdDlqrMA4oD5V64A9S4:-KdMRbdAKmu3xzzwk5wa:bryz9h9) ([raw file](https://github.com/robotlocomotion/drake/blob/adc95ac316f384f7df329055ed7613b02e74a3ec/drake/automotive/maliput/dragway/test/dragway_test.cc#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Maybe this ASCII art should be moved to `dragway::RoadGeometry`?

https://github.com/RobotLocomotion/drake/blob/1bc3190cc5e1cf1c020f0914ab466b06bd216445/drake/automotive/maliput/dragway/segment.h#L26

Then, maybe we can add a "For example, here are the parameters for one-lane and two-lane dragways."
</blockquote></details>

Done.  Added comment atop this file, as well as `dragway::RoadGeometry` API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdMurcLccQOhOsDumkU:b8g60cr)*

**Comment by jwnimmer-tri** [comment]
Switching from -@sherm1 to +@soonho-tri +@david-german-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdVscaRgIi-xbo2gpdu:b-yzty4e)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdW6iVHue_QYUnvLEDz:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5203#-:-KdW6x1lD8xA6GoDPceQ:bnfp4nl)*

**Pull request merged**
