### PR TITLE
Framework model params

### LINKED ISSUE #5465: LeafSystem should support model-value based parameter allocation
Just like #5431, but for parameters.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #5465.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5684)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 platform review, please.
+@liangfok feature review, please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5684#-:-KgaaVAj_sw_wsShznht:b-hfwgk9)*

**Comment by sherm1** [comment]
Platform :lgtm: -- nice to see code disappearning. Pending feature review.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5684#-:-KgalZ92tjA1BbtIgLD4:b-sm4ye)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5684#-:-KgaquC3bfXMyhpt9Jry:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:car:

**Pull request merged**
