### PR TITLE
old: [geometry] Make Cylinder's tetrahedral mesh with medial axis.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
A big `draft` PR that will be replaced by two smaller PRs (#14421 and another one) for easier review. Partially fix issue #12128.

Cc: @joemasterjohn You might find this draft useful.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335)

image
image
image

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
I am about to commit a refactor of a part of one long function `MakeCylinderVolumeMeshWithMa()` into three subroutines in make_cylinder_mesh.cc.  Hopefully publishing this comment will force Reviewable to advance to r2 for comparison with r1.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MMTeHUaDp94egj6Hs1q:btvtqsr)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[geometry/proximity/make_cylinder_mesh.cc, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMTf2C46SjUfkmd0OaG:-MMTf2C46SjUfkmd0OaH:b-w2y474) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L13)):*
> ```cpp
> namespace internal {
> 
> template <typename T>
> ```

Revision1 has this one long function of 162 lines.

**Review by DamrongGuoy — COMMENTED** [review]
I refactor it into three separated cases of long cylinder, short cylinder, and medium cylinder. It makes the code longer but hopefully easier to understand. The combined lines of code is longer but more efficient because each subroutine targets each specific case.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MMTiSlVAZtBC2sK3G87:b-9m2wz9)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
@joemasterjohn  @seancurtis-tri when you have time, please take a look at both revisions r1 and r2.  Please let me know which one you'd prefer: the more generic algorithm r1, or the more specific algorithm r2.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MMYljVb13z1MyHk4NJr:b-kdrw1g)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've placed various comments. Some of them are tagged to R1 and some to R2. I'd recommend processing them in that order (i.e., select R1 and then visit the comments, then select R2 and visit).

First, I have to offer you my congratulations on such a succinct and consistent representation of the problem. It's very elegant that a small for loop with a few calls builds all of the topology. However, the elegance in writing it doesn't translate well to elegance in reading it. 

The conclusion I've come to is this:

The difference between having switch statements vs separate functions doesn't change things one way or the other, clarity-wise. The *hardest* part is making the topology clear. What is being constructed, what are their relationships, how to interpret the soup of indices.

It's clear to me that you've made a solid first attempt to make clarify, but I think we can take the effort further.

1. The description of the topology is the tersest documentation; it merely counts the expected number of tetrahedra. Let's expend more words there so that a more average Drake developer would have hopes for understanding this (imagine if someone else had to come in and modify this so that we created a finer tessellation).
2. Vertex indices are referenced by very terse, secretly-encoded names (e.g., `v[0][i]`). Simply looking through the code, you'd be hard-pressed to offer up any kind of semantic interpretation for what it is you are looking at. And when you also have `m`, `cm`, `cv`, it becomes difficult to fully understand without being an initiate. So, we should revisit how we *spell* the topology so that even if someone understood the principle they could more easily map it to the code. (see comments to this effect I've scattered around).
3. Pictures would be best -- even 2D representations of a 3D concept I think would be an improvement (although I may be wrong). It's well worth trying but may prove impossible.

I think that increased clarity of the topology can be equally applied to R1 or R2.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MMbl6v_BJsb3PuH5US-:bqyv5kz)* status: 14 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbfzvG9heXP6QXKfQv:-MMbfzvH6bxJ2p_CE299:buh24g3) (no related file):*
You've got a great deal of careful encoding of different indices by their semantic interpretation. That's different from what I broached in the meeting on Thursday.  There's multiple structures and lots of inscrutable indices in order to construct the logical box. I think it can be greatly simplified by creating the *full* set of logical indices.



In this case, there are 18 vertices on the surface of the cylinder. So, my set of indices that I operate on to create tetrahedra has one unique index for each of those. Then I create *another* index for each of those vertices. In the image, I've suggested that they're all stored in a single array. But it could also be two arrays: `surface_indices` and `axis_vertices` -- in which case, the `ith` surface vertex would have its corresponding medial axis vertex at `surface_indices[i]` and `axis_vertices[i]`, respectively.

That would change calls like:

```c++
append(SplitToTetrahedra(m[0][j], v[0][j], v[0][i], m[0][i], cm[0], cv[0],
                             cv[0], cm[0]));
```

to
```
append(SplitToTetrahedra(a[i], a[j], a[k], a[l], s[i], s[j], s[k], s[l]);
```

Admittedly, this displaces the work into defining `i`, `j`, `k`, and `l` and I don't know if that's a net improvement. But I think it would segregate things more reasonably. I present this, not to suggest a change, but to offer something for consideration.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbmwOREsqUwBug0ESb:-MMbmwOREsqUwBug0ESc:b-tsduqi) (no related file):*
I don't think R2 goes far enough; I'd really rather not see *multiple* switch statements in `MakeCylinderVolumeMeshWithMa`.  It should do just enough work to know how to call the right custom mesher based on the cylinder's aspect ratio and little more than that. There is a risk of duplicate code, but I believe that can be refactored into a base utility function that the Long, Short, and Medium variants can call.

---
___
*[geometry/proximity/make_cylinder_mesh.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb6DA2C2W1xwIGw8es:-MMb6DA2C2W1xwIGw8et:b-2cknf4) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L18)):*
> ```cpp
>   const double top_z = cylinder.length() / 2.;
>   const double bottom_z = -top_z;
>   enum class CylinderClass {
> ```

You've got an extra layer of abstraction your code. You've classified cylinders as long, medium, and short. The implication of this is the geometry of the medial axis. What if you simply classified them by the type of medial axis they had?  I.e.,

`enum class MaShape { kLine, kPoint, kDisk };`

Then all of the switch statements on it have the geometric work directly reflected by the name of the enumeration.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb6evG5iCoPJSng-wT:-MMb6evG5iCoPJSng-wU:b-ma2to0) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L23)):*
> ```cpp
>     kShort
>   };
>   const double shorter_half = std::min(top_z, cylinder.radius());
> ```

"shorter half" doesn't communicate much and it's particularly opaque because you're comparing a measure of the cylinder with a position along the z-axis. Your intent and the comparison may be more clear with something like:

```c++
// Determine which is smaller: cylinder length or diameter.
const double smaller_measure = std::min(cylinder.length(), 2 * cylinder.radius());
```

Or something like that. Admittedly, I'm using the full measure and your calculations are predicated on the half measure. But if you do something like that, it'll read more clearly than comparing radius with z-position. and calling that "shorter half".
___
*[geometry/proximity/make_cylinder_mesh.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb7owK8_KjcFZvWqh-:-MMb7owK8_KjcFZvWqh0:b-pwsw1o) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L25)):*
> ```cpp
>   const double shorter_half = std::min(top_z, cylinder.radius());
>   const double tolerance = DistanceToPointRelativeTolerance(shorter_half);
>   const CylinderClass cylinder_class =
> ```

What is the real value of this tolerance? If you didn't have tolerance and checked strictly for the two values being equal, it means you'd get the point-shaped medial axis only for very specific results. But is that bad? Really? Generally, cylinders will be specified by humans, and it's difficult to imagine that a human will specify a cylinder to being "symmetric" in this regard but miss by epsilon. It seems this adds complexity without value.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbBA0n85s6KIq86JiM:-MMbBA0n85s6KIq86JiN:bvj7389) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L50)):*
> ```cpp
>   }
> 
>   // For convenience, we always add one vertex at the center of each of the
> ```

Generally I find the names `v`, `cv`, `m`, and `cm` difficult to think about while reading through. The names are never documented, the reader is left to infer what they mean. While the abbreviations aren't of themselves unacceptable, a bit more overview comments that collects them up and explains what they mean and how they relate would be a huge help to the reader.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb92fwDgKV0_Hv4ISn:-MMb92fwDgKV0_Hv4ISo:b-trvunb) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L79)):*
> ```cpp
>   // vertices point to the same mesh vertex at the center of the central
>   // medial circular disk for convenience. For a medium cylinder, both virtual
>   // vertices point to the same mesh vertex at the origin of the frame of
> ```

nit: the trait "at the origin of the frame of the cylinder" is accurate but seems to be secondary to the fact that it's at the center of the medial axis disk. That would seem to be more relevant to document here.

Nevermind, I see that you corrected it in R2.  :)
___
*[geometry/proximity/make_cylinder_mesh.cc, line 150 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbC-UY3u-htJR7V7hA:-MMbC-UY3u-htJR7V7hB:beaj7lh) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L150)):*
> ```cpp
>   int i = num_vertices_per_circle - 1;
>   for (int j = 0; j < num_vertices_per_circle; ++j) {
>     append(SplitToTetrahedra(m[0][j], m[1][j], m[1][i], m[0][i],    // medial
> ```

This is the *hardest* part of the code to understand. Doubly-indexed arrays with single- (or double)-letter names make understanding this logic *very* difficult for a reader.

Generally, the hardest part of all of these algorithms (box, cylinder, capsule, whatever), is understanding the topological relationships between the surface vertices. We can make mapping them to their logical axis counterparts mindless and easy. This seems to suffer from mixing the two into something difficult to reason about.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMblZJ4EZmtXlhIS-vI:-MMblZJ534y3LolJlxwz:bswczf8) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L18)):*
> ```cpp
>     const int num_vertices_per_circle,
>     const VolumeVertexIndex cv[2],
>     const std::vector<VolumeVertexIndex> v[2],
> ```

the choice of `v[2]` is compact, but not particularly readable.

If you actually passed in *two* vectors: `top` and `bottom`, then, rather than having things like `v[0][i]` and `v[1][i]`, you'd get `top[i]` and `bottom[i]` which is immediately more readable.

Alternatively, you could keep the signature as is and simply alias them locally:

`const vector<VolumeVertexIndex>& top = v[0];`, etc.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbiqnr8V50elHTnZAW:-MMbiqnsCvZEFfqF5tsw:bygy6g1) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L55)):*
> ```cpp
>   for (int j = 0; j < num_vertices_per_circle; ++j) {
>     // Bottom cone.
>     mesh_elements.emplace_back(cv[0], v[0][i], v[0][j], cm[0]);
> ```

Things aren't any easier to read here with the `cv`, `v`, `cm` symbols. The most important part to make clear doesn't necessarily get clearer for the division. Just isolated.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbjv375oX6F2h06x7l:-MMbjv375oX6F2h06x7m:bd29c28) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L106)):*
> ```cpp
>   // bottom frustum: n triangular prisms => 3n tetrahedra.
>   // top frustum: n triangular prisms => 3n tetrahedra.
>   // side co-frustum: ring of n triangular prisms => 3n tetrahedra.
> ```

nit: "co-frustum" here, "anti-frustm" below. I'm not familiar with *either* term. Probably worth defining. Surely, it's just a frustm, yes?
___
*[geometry/proximity/make_cylinder_mesh.cc, line 152 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbl-JcCw4wwDuwiyIE:-MMbl-JcCw4wwDuwiyIF:b-wnpcg6) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L152)):*
> ```cpp
>   std::vector<VolumeElement> mesh_elements;
>   // n = num_vertices_per_circle.
>   // bottom cone: n tetrahedra, top cone: n tetrahedra.
> ```

nit missing "top cone". (Although your math accounts for it).
___
*[geometry/proximity/meshing_utilities.h, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb5LUMEOXIzVwpcO2G:-MMb5LUMEOXIzVwpcO2H:b-sygy64) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/meshing_utilities.h#L11)):*
> ```objc
> namespace internal {
> 
> /* Subdivides a virtual cube to have up to six tetrahedra such that they
> ```

In the case of revision 2, is there value in this operating on a *virtual* cube? Given that you're enumerating the three polytopes you expect to work on, this could simply become a legitimate cube (as a `@pre`) and you could throw out the expensive set construction.
___
*[geometry/proximity/meshing_utilities.h, line 14 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb357f5wT7iQFq2rxI:-MMb357f5wT7iQFq2rxJ:bwhyut7) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/meshing_utilities.h#L14)):*
> ```objc
>  share the diagonal v0v6 (see ordering below). We allow repeated vertices in
>  the virtual cube and will skip tetrahedra with repeated vertices.
> ```

nit: A couple of other prerequisites worth being explicit about:

1. unique index values imply non-coincident points.
2. v0 != v6
___
*[geometry/proximity/meshing_utilities.h, line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb4tHS40n3k8jHSvX_:-MMb4tHS40n3k8jHSvXa:b-xgpz4u) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/meshing_utilities.h#L37)):*
> ```objc
> 
>  Examples of cases with repeated vertices.
>  - If v0 == v3 and v1 == v2, we will have a prism instead of a cube and will
> ```

BTW These example suggest intent -- i.e., you expect that if there *is* duplication, it would be in vertices 0, 1, 2, & 3. However, this algorithm will still work if there are duplicates among others (i.e., v0 == v4). I *believe* the only case where it wouldn't work is the aforementioned v6 = v0 case.

**Review by DamrongGuoy — COMMENTED** [review]
@seancurtis-tri Thank you for your comments and being the canary in the coal mine.

I added documentation and pictures. The consensus was to continue from R2 (separate into three specific subroutines).

I'm hoping to switch from Draft PR to real PR and start the review this week after completing unit tests.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MNWU0P466Ie21BW9j21:b-8r9k5t)* status: 13 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+@joemasterjohn for feature review please.

I hope `SplitTriangularPrismToTetrahedra()` in `meshing_utilities.cc` and `CalcLongCylinderVolumeMeshWithMa()` in `make_cylinder_mesh.cc` are good examples for you to look at.

Please start reviewing from revision r5.  I have trimmed down the PR a bit, so it only generates the mesh without the pressure field yet.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MNyE3Wg3zwhBqugBN5y:b-9spfce)* status: 13 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @joemasterjohn)

**Review by DamrongGuoy — COMMENTED** [review]
@seancurtis-tri we have just started the review process from r5 (status=do-not-review was set for r1-r4).

Could you please unblock the comments for pre-r5?  I did use your earlier comments towards r5, but I can't respond one by one.

You're certainly welcome to comment on r5 and later.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MNyG-3n5DNF3b4JCMZa:b-qrvb5f)* status: 13 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @joemasterjohn)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335)* status: 10 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbfzvG9heXP6QXKfQv:-MNyHtdI5MivVLzE6JWz:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You've got a great deal of careful encoding of different indices by their semantic interpretation. That's different from what I broached in the meeting on Thursday.  There's multiple structures and lots of inscrutable indices in order to construct the logical box. I think it can be greatly simplified by creating the *full* set of logical indices.



In this case, there are 18 vertices on the surface of the cylinder. So, my set of indices that I operate on to create tetrahedra has one unique index for each of those. Then I create *another* index for each of those vertices. In the image, I've suggested that they're all stored in a single array. But it could also be two arrays: `surface_indices` and `axis_vertices` -- in which case, the `ith` surface vertex would have its corresponding medial axis vertex at `surface_indices[i]` and `axis_vertices[i]`, respectively.

That would change calls like:

```c++
append(SplitToTetrahedra(m[0][j], v[0][j], v[0][i], m[0][i], cm[0], cv[0],
                             cv[0], cm[0]));
```

to
```
append(SplitToTetrahedra(a[i], a[j], a[k], a[l], s[i], s[j], s[k], s[l]);
```

Admittedly, this displaces the work into defining `i`, `j`, `k`, and `l` and I don't know if that's a net improvement. But I think it would segregate things more reasonably. I present this, not to suggest a change, but to offer something for consideration.

</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbmwOREsqUwBug0ESb:-MNyHun705-cTkSqItkt:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't think R2 goes far enough; I'd really rather not see *multiple* switch statements in `MakeCylinderVolumeMeshWithMa`.  It should do just enough work to know how to call the right custom mesher based on the cylinder's aspect ratio and little more than that. There is a risk of duplicate code, but I believe that can be refactored into a base utility function that the Long, Short, and Medium variants can call.
</blockquote></details>

Done.

---
___
*[geometry/proximity/make_cylinder_mesh.cc, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb6DA2C2W1xwIGw8es:-MNyI2BK9ySiHsz1qZSJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You've got an extra layer of abstraction your code. You've classified cylinders as long, medium, and short. The implication of this is the geometry of the medial axis. What if you simply classified them by the type of medial axis they had?  I.e.,

`enum class MaShape { kLine, kPoint, kDisk };`

Then all of the switch statements on it have the geometric work directly reflected by the name of the enumeration.
</blockquote></details>

Done.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb6evG5iCoPJSng-wT:-MNyI5RkDY7gqPrwbdUY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

"shorter half" doesn't communicate much and it's particularly opaque because you're comparing a measure of the cylinder with a position along the z-axis. Your intent and the comparison may be more clear with something like:

```c++
// Determine which is smaller: cylinder length or diameter.
const double smaller_measure = std::min(cylinder.length(), 2 * cylinder.radius());
```

Or something like that. Admittedly, I'm using the full measure and your calculations are predicated on the half measure. But if you do something like that, it'll read more clearly than comparing radius with z-position. and calling that "shorter half".
</blockquote></details>

Done.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb7owK8_KjcFZvWqh-:-MNyI73RB3haVdC6uvXs:bv43udf) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What is the real value of this tolerance? If you didn't have tolerance and checked strictly for the two values being equal, it means you'd get the point-shaped medial axis only for very specific results. But is that bad? Really? Generally, cylinders will be specified by humans, and it's difficult to imagine that a human will specify a cylinder to being "symmetric" in this regard but miss by epsilon. It seems this adds complexity without value.
</blockquote></details>

I'd like to keep it.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbBA0n85s6KIq86JiM:-MNyIDgN3uNqkp_arKl-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L50)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Generally I find the names `v`, `cv`, `m`, and `cm` difficult to think about while reading through. The names are never documented, the reader is left to infer what they mean. While the abbreviations aren't of themselves unacceptable, a bit more overview comments that collects them up and explains what they mean and how they relate would be a huge help to the reader.
</blockquote></details>

Done.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 150 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbC-UY3u-htJR7V7hA:-MNyIGqn-QZbtrMkgBDX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0b80bcbca3c5e658c1f10330183d95145b28b16a/geometry/proximity/make_cylinder_mesh.cc#L150)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is the *hardest* part of the code to understand. Doubly-indexed arrays with single- (or double)-letter names make understanding this logic *very* difficult for a reader.

Generally, the hardest part of all of these algorithms (box, cylinder, capsule, whatever), is understanding the topological relationships between the surface vertices. We can make mapping them to their logical axis counterparts mindless and easy. This seems to suffer from mixing the two into something difficult to reason about.
</blockquote></details>

Done.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMblZJ4EZmtXlhIS-vI:-MNyI0gN4y4MHchjtGHS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

the choice of `v[2]` is compact, but not particularly readable.

If you actually passed in *two* vectors: `top` and `bottom`, then, rather than having things like `v[0][i]` and `v[1][i]`, you'd get `top[i]` and `bottom[i]` which is immediately more readable.

Alternatively, you could keep the signature as is and simply alias them locally:

`const vector<VolumeVertexIndex>& top = v[0];`, etc.
</blockquote></details>

Done.
___
*[geometry/proximity/make_cylinder_mesh.cc, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMbiqnr8V50elHTnZAW:-MNyHz43-nraoVVWl0rB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/make_cylinder_mesh.cc#L55)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Things aren't any easier to read here with the `cv`, `v`, `cm` symbols. The most important part to make clear doesn't necessarily get clearer for the division. Just isolated.
</blockquote></details>

Done.
___
*[geometry/proximity/meshing_utilities.h, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14335#-MMb5LUMEOXIzVwpcO2G:-MNyIK6JCztWgVZ0FwRt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1a6b00fb669c01fff9034d5a01424bfc4218fa79/geometry/proximity/meshing_utilities.h#L11)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the case of revision 2, is there value in this operating on a *virtual* cube? Given that you're enumerating the three polytopes you expect to work on, this could simply become a legitimate cube (as a `@pre`) and you could throw out the expensive set construction.
</blockquote></details>

Done.

**Review by DamrongGuoy — COMMENTED** [review]
I have just learnt a new technique from @jwnimmer-tri to split a big PR like this into smaller ones.  I'll close-without-merge this PR momentarily.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MO-MahmEHLet3soAbwE:bc7ai8b)* status: 10 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
Changed to `status: do not review`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MO-Nq96EiwynIgqjooX:b-ezoi8s)* status: 10 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
-@joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MO-U-Fg1WzVgAXQAgYb:b-80amlx)* status: 10 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
-@seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14335#-:-MO-U9in3v1VGxtoYFFX:bnhhpu5)* status: 10 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Pull request closed without merging**
