### PR TITLE
[parsing] Cleanup detail_urdf_geometry

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #16229

Move the anonymous namespace to the top of the cc file, as is
customary. Move a doomed legacy function into the anonymous namespace;
since it is not declared in the header, it should not leak its symbol at
link time.

This patch should have 0 functional change, other than hiding the stray
link symbol.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16764)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews.
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16764#-:-Mxu71ri7JXOHOn-vKaV:b-9dgq4i)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16764)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16764#-MxuzHJ4Cm5c_lUPmZ7y:-MxuzHJ56bzRP9ksaBoB:bt77iwy) (no related file):*
> Move the anonymous namespace to the top of the cc file, as is
> customary.

When an anoymous function is used by several different public functions, then I agree that it make sense to introduce it at the top of the file, kind of like a preamble.

When an anonymous function is used by _exactly one_ public function, I find it more tasteful to define it immediately above its sole user, so that someone perusing the implementation has a nice storyboard to follow, without tracing the call sequence back and forth through the whole file merely on the basis of linker visibility.

With that in mind, the relocation of `ParseCoulombFrictionFromDrakeCompliance` seems like a net neagative to me.  Do you feel strongly about that change?

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16764)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16764#-MxuzHJ4Cm5c_lUPmZ7y:-Mxv0QqYCQnrWvqbceUB:bf03m4s) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Move the anonymous namespace to the top of the cc file, as is
> customary.

When an anoymous function is used by several different public functions, then I agree that it make sense to introduce it at the top of the file, kind of like a preamble.

When an anonymous function is used by _exactly one_ public function, I find it more tasteful to define it immediately above its sole user, so that someone perusing the implementation has a nice storyboard to follow, without tracing the call sequence back and forth through the whole file merely on the basis of linker visibility.

With that in mind, the relocation of `ParseCoulombFrictionFromDrakeCompliance` seems like a net neagative to me.  Do you feel strongly about that change?
</blockquote></details>

My strongest feeling is that I would like to delete it.

Short of that, the move is motivated by the need to do significant type-signature damage to all the non-exported functions (likely folding them into some internal class) to enable diagnostics policy. That will be easier when all of the supporting cast is in one place.

But, I suppose all of that can wait until more pieces are in place. The main goal of this patch was to reduce the line-count of future patches, but maybe that's not a good enough reason.

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16764#-MxuzHJ4Cm5c_lUPmZ7y:-Mxv1x7X7wNnx5kQwyh4:b-jzv0f6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My strongest feeling is that I would like to delete it.

Short of that, the move is motivated by the need to do significant type-signature damage to all the non-exported functions (likely folding them into some internal class) to enable diagnostics policy. That will be easier when all of the supporting cast is in one place.

But, I suppose all of that can wait until more pieces are in place. The main goal of this patch was to reduce the line-count of future patches, but maybe that's not a good enough reason.
</blockquote></details>

Even if the public (though internal) functions into into class methods on a public (though internal) header file class, the anonymous helper can still appear intermingled with their definitions, though?

---

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16764#-MxuzHJ4Cm5c_lUPmZ7y:-Mxv2BV-2mCecNZD_YjD:bfccpp8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Even if the public (though internal) functions into into class methods on a public (though internal) header file class, the anonymous helper can still appear intermingled with their definitions, though?
</blockquote></details>

s/into into/turn into/

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16764)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16764#-MxuzHJ4Cm5c_lUPmZ7y:-Mxv2v-Z59S0K2oUwSlD:b-5b3o68) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

s/into into/turn into/
</blockquote></details>

Very well. I'll just close this and adjust the prototype.

---

**Pull request closed without merging**
