### PR TITLE
Update libbot and director

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by RussTedrake** [comment]
can you also pass in the arguments as recommended in https://github.com/RobotLocomotion/director/issues/41 as the defaults?

**Comment by RussTedrake** [comment]
fwiw - the link error in drake001 is 
```
Linking CXX shared library ../../../lib/libvtkDRCFilters.dylib
Undefined symbols for architecture x86_64:
  "_bot_lcmgl_decode", referenced from:
      vtkLCMGLProp::RenderOpaqueGeometry(vtkViewport*) in vtkLCMGLProp.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

fwiw - I just pushed a fix to libbot master to quiet the most offensive of those cmake warning spews (which made that log file almost impossible to parse).  grab it if you like.

**Comment by patmarion** [comment]
The link error is due to this issue when configuring director:

-- checking for module 'bot2-lcmgl-client'
--   found bot2-lcmgl-client, version 0.0.1
-- checking for module 'bot2-lcmgl-renderer'
--   package 'bot2-lcmgl-renderer' not found

So it seems the libbot build didn't complete its install, or something else has gone wrong. bot2-lcmgl-client was found but bot2-lcmgl-renderer was not.  I'll see what I can find.

**Comment by patmarion** [comment]
I think this is the problem: is /opt/X11/lib/pkgconfig in the PKG_CONFIG_PATH?


$ export PKG_CONFIG_PATH=/tmp/drake-1245-11320/build/lib/pkgconfig
$ pkg-config --libs bot2-lcmgl-client
-L/tmp/drake-1245-11320/build/lib -L/usr/local/Cellar/glib/2.44.1/lib -L/usr/local/opt/gettext/lib -lbot2-lcmgl-client -llcmtypes_bot2-lcmgl -llcm -lgthread-2.0 -lglib-2.0 -lintl 

$ pkg-config --libs bot2-lcmgl-renderer
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gl', required by 'bot2-vis', not found

If you add  /opt/X11/lib/pkgconfig to PKG_CONFIG_PATH then the call to pkg-config to find bot2-lcmgl-renderer succeeds.

**Comment by RussTedrake** [comment]
I believe that x11 is found by the rest of bot-vis using
```
find_package( X11 REQUIRED )
```
You could add this to the PKG_CONFIG_PATH directly from the cmake files.  I think this would be preferable to having to add it on every machine.

**Comment by patmarion** [comment]
The issue is finding gl.pc, not X11.  It appears user russt on drake001 has a modified ~/.zshrc file which adds /opt/X11/lib/pkgconfig to the PKG_CONFIG_PATH.  In the build log, I can see evidence that this modified path is available when configuring drake, but perhaps missing when configuring director.  I'm not sure why that would be.  I'll dig more.

**Comment by RussTedrake** [comment]
Fyi - the build servers run off a cronjob, so the environment would be set in the crontab (not .zshrc)

**Comment by patmarion** [comment]
That's a good hint.  Maybe it's possible that something in drake's Make actually sources the .zshrc file, (like using cmake --build) so drake has the PKG_CONFIG_PATH but other projects don't.

**Comment by patmarion** [comment]
Ah I think I found the issue, typo in director!  It was accidentally overwriting the PKG_CONFIG_PATH environment variable.

**Comment by patmarion** [comment]
Hmm, this failed with a clang segfault while building drake.  Unrelated?

clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
make[7]: *** [../util/cartesian2cylindricalmex.mexmaci64] Error 254
make[6]: *** [util/CMakeFiles/cartesian2cylindricalmex.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [drake-prefix/src/drake-stamp/drake-build] Error 2
make[2]: *** [CMakeFiles/drake.dir/all] Error 2

**Comment by RussTedrake** [comment]
If you close and reopen you can force the build servers to try again

**Pull request merged**
