### PR TITLE
[workspace] Disable PETSc's malloc games

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We want this condition to be the one used by Drake:

https://github.com/petsc/petsc/blob/v3.16.1/src/sys/memory/mal.c#L44-L49

On x86_64, a call to `malloc` always returns multiples of 16 already (the platform alignment is 16 bytes).  However, PETSc doesn't seem to have any pre-processor way to express that, so instead we'll tell it to require only 8 byte alignment to disable the pointer-arithmetic games, but in practice it will always be 16 bytes anyway, so there should be no performance impacts.

The key observation in the valgrind reports is the phrase "possibly lost" (see https://valgrind.org/docs/manual/mc-manual.html#mc-manual.leaks).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16210)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review (or any re-benchmarking you're interested in), please -- assuming that the memcheck CI build passes.  It passed for me locally on Focal.

**Review by xuchenhan-tri — COMMENTED** [review]
:LGTM: if the CI build passes.

This is actually the first thing I tried when I was trying to fix the memcheck test. For some reason, it didn't work for me, which led me to believe there's a deeper issue and PetscFinalize() is the easiest fix. In hindsight, I may have messed up the test and missed the easy fix.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16210#-:-MqpdtVd6droGZBuoV5I:bbsd929)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16210#-:-Mqpk06H1Tcu3MVP1CiG:bnfp4nl)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Pull request merged**
