### PR TITLE
Split autodiffxd_test.cc into multiple translation units

### LINKED ISSUE #7433: Split //drake/common:autodiffxd_test into multiple files
@jwnimmer-tri found that it takes `>=80` secs in CI  (`linux-xenial-clang-bazel-continuous-release`). Let's split the test into multiple translation units.

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #7433

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7438)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Reduced build time for `autodiffxd_test` target: 169 sec => 20.596 sec

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for all reviews, please. Please add another reviewer if you think it's necessary.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-:-KyWftbBuxdP6WznTOYJ:bybdezl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: I confirmed that each `CASE` in the old file has a matching new filename.  I didn't diff the text, but seems like that's not useful.

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/BUILD.bazel, line 378 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWilKd4A-NbRLPco02:-KyWilKd4A-NbRLPco03:bmltsoj) ([raw file](https://github.com/robotlocomotion/drake/blob/b7d494df69d173769077aaea860892b6b266b264/drake/common/BUILD.bazel#L378)):*
> ```
> 
> # === test/ ===
> ```

FYI Probably better to leave the blank line.

---

*[drake/common/BUILD.bazel, line 380 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWifpeI2XdSEaVSvCz:-KyWifpeI2XdSEaVSvD-:bi09f0f) ([raw file](https://github.com/robotlocomotion/drake/blob/4be1f22ce2908154bd402578205b05fdd026b35d/drake/common/BUILD.bazel#L380)):*
> ```
> drake_cc_googletest(
>     name = "autodiffxd_test",
>     srcs = [
> ```

Please add a comment explaining why we have chosen this unusual formulation of the compile.

---

*[drake/common/test/autodiffxd_test.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWiz4v_AXNvAt80Hjh:-KyWiz4v_AXNvAt80Hji:b-vv567l) ([raw file](https://github.com/robotlocomotion/drake/blob/4be1f22ce2908154bd402578205b05fdd026b35d/drake/common/test/autodiffxd_test.h#L7)):*
> ```objc
> #include "drake/common/autodiff.h"
> 
> namespace drake {
> ```

FYI Consider adding `namespace test {` here as well, out of an abundance of caution?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-:-KyWjiNCChT7zLwZgVRT:baeqzfa)*

**Comment by soonho-tri** [comment]
Review status: 1 of 24 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/BUILD.bazel, line 378 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWilKd4A-NbRLPco02:-KyWmATYKipC2y1Yh2-q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b7d494df69d173769077aaea860892b6b266b264/drake/common/BUILD.bazel#L378)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Probably better to leave the blank line.
</blockquote></details>

Done.

---

*[drake/common/BUILD.bazel, line 380 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWifpeI2XdSEaVSvCz:-KyWmB0SPLTcJ14MRrtp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4be1f22ce2908154bd402578205b05fdd026b35d/drake/common/BUILD.bazel#L380)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add a comment explaining why we have chosen this unusual formulation of the compile.
</blockquote></details>

Done.

---

*[drake/common/test/autodiffxd_test.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7438#-KyWiz4v_AXNvAt80Hjh:-KyWmrPpFQg8PpPnHWAh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4be1f22ce2908154bd402578205b05fdd026b35d/drake/common/test/autodiffxd_test.h#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider adding `namespace test {` here as well, out of an abundance of caution?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7438)*

**Comment by jwnimmer-tri** [comment]
Reviewed 23 of 23 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7438)*

**Pull request merged**
