### PR TITLE
Irb140 urdf

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. Add IRB140 urdf and xacro
2. Add "package" to Atlas folder and IRB140 folder, so that I can combine the urdfs in each folder.

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@RussTedrake @gizatt , could you review the code?

**Comment by gizatt** [comment]
Works fine and looks good to me -- cool to have a proper URDF for the f/t sensor. (However, I don't see the URDF being used anywhere yet -- it would be neat to have it added to the xacro-generated irb140_robotiq urdf to get it visualized as well.)

Only qualm is that in IRB140.m, the hand attachment script uses a spacing between the end of the arm and the hand itself that disagrees with the xacro (and so the simulated arm probably disagrees with reality). I did what I think is the right fix as the last commit on [https://github.com/gizatt/drake/tree/IRB140-urdf-fix-hand-offset].

**Comment by hongkai-dai** [comment]
@gizatt Thanks! I just added ATI sensor to the arm in my newest commit

**Comment by gizatt** [comment]
Nice! To keep this clean do you want to merge in the fix from my branch?

**Comment by RussTedrake** [comment]
i see now what you meant when you asked about the package:// fields.  (i didn't quite understand from the email).  it seems gross to hard-code them in our version of rospack.m.  

the urdf parser should always look for the mesh files relative to the urdf file location (when there is no package://).  So i *think* you could have accomplished the same thing by doing two addRobotFromURDF calls to load the irb140 first, then weld the hand (loaded from examples/Atlas/urdf/robotiq.urdf ) to the last joint in matlab.  that would also have the benefit of not duplicating the urdf code for the robotiq hand (if we have two copies, they will inevitably go out of date).

alternatively, we could support a tag in the urdf to insert another urdf.  that's certainly supported in the sdf format.

what do others think?  did you confirm that this does not break visualization in the director?

**Comment by RussTedrake** [comment]
ah - i see now that the robotiq hand is only included via the xacro.  that's better.  maybe it's aok?

**Comment by hongkai-dai** [comment]
@gizatt merged your branch.

**Comment by hongkai-dai** [comment]
I agree hard coding rospack is gross, but I think the benefit of putting both the hand and the arm in one urdf, is that the user does not need to remember what the transformation from the arm to the hand is. If we use `addRobotFromURDF`, then when we construct the ABB arm/hand, we always need to hard code the transformation, and that seems error-prone to me. 

I ran the viewer and it can visualize the arm, the arm and the hand, and arm+hand+sensor, in the Drake viewer. I will use a DRC machine tomorrow to test if it works fine with DRC code.

**Comment by RussTedrake** [comment]
i guess i agree with that, too.  the other advantage is that we will be able to load the merged urdf in the c++ code directly if we like, too.  perhaps that's a better policy in general.

**Pull request merged**
