### PR TITLE
workspace: Update pybind11 fork to latest commit

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires:
- [x] RobotLocomotion/pybind11#43

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14028)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14028)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14028#-MGZJUceC-KZnIG2uByf:-MGZJUceC-KZnIG2uByg:bopi2lk) ([raw file](https://github.com/robotlocomotion/drake/blob/1ec8273a5e159377345ebd5d7c9310476ae6b65f/tools/workspace/pybind11/repository.bzl#L9)):*
> ```Starlark
> _REPOSITORY = "RobotLocomotion/pybind11"
> 
> # DNM: Requires merge.
> ```

Working: Requires merge of upstream PR.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
+@rpoyner-tri for both reviews please (as Platform Reviewer on Tues)
+(status: single reviewer ok) 

Note that macOS CI has also passed, mentioned above.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14028#-:-MGaPHQMEdU13C_R7ApI:b-g680h9)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14028)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[tools/workspace/pybind11/repository.bzl, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14028#-MGZJUceC-KZnIG2uByf:-MGiVxRq8HdtnZX1Dkcg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1ec8273a5e159377345ebd5d7c9310476ae6b65f/tools/workspace/pybind11/repository.bzl#L9)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Requires merge of upstream PR.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14028#-:-MGiWgG044SJpPUq0Heq:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
