### PR TITLE
add helpers to extract input and state blocks

### PR DESCRIPTION
**Pull request by RussTedrake**
Although there is only one use of the `GetVectorState` method here, I am also using it in my WIP PWA system (which derives from `VectorSystem`)

N.B. - The existing vector_system_test actually already covered the cases I was starting to type in.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6780)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for feature review (a version of this was recommended in your previous code review).  

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-:-KqmsN8PS_YU2aCJvpax:bq36w6h)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

The extracted methods are covered in the unit test already via calls to the public System APIs.  This is fine in terms of correctness.

However, consider if you want to further lock in the method signatures (for users to depend on) by calling the new methods directly from the unit test along with a comment such as https://github.com/RobotLocomotion/drake/blob/d62ba8084102d4f65a3685e58edec9415863c3bd/drake/systems/framework/test/vector_system_test.cc#L36-L37.  I am OK either way.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_system.h, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-KqxbZXcod3rfM8y4CYH:-KqxbZXcod3rfM8y4CYI:b-ck3e0a) ([raw file](https://github.com/robotlocomotion/drake/blob/8fae9875894572887b3a9bbb5c503a9f41b5a295/drake/systems/framework/vector_system.h#L124)):*
> ```objc
>       return this->EvalEigenVectorInput(context, 0);
>     }
>     static const VectorX<T> empty_vector{0};
> ```

The `empty_vector` has a destructor that is run at the conclusion of the program, but GSG prohibits that; see https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.

The easiest solution is to use `never_destroyed<VectorX<T>>` to disable the destructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-:-KqxdQ16b5pncp28N2VJ:b4g70rd)*

**Comment by RussTedrake** [comment]
did not add the comment, but did add a bunch of direct coverage tests.  (i didn't know about the trick for exposing protected methods in a derived class... nice!).  

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/vector_system.h, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-KqxbZXcod3rfM8y4CYH:-Kr0ODstDcOOvhmejjve:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8fae9875894572887b3a9bbb5c503a9f41b5a295/drake/systems/framework/vector_system.h#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `empty_vector` has a destructor that is run at the conclusion of the program, but GSG prohibits that; see https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.

The easiest solution is to use `never_destroyed<VectorX<T>>` to disable the destructor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-:-Kr0UC532R1D8GKJM6bv:bazifyk)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/framework/test/vector_system_test.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-Kr0efQ56F7GM1l2G02C:-Kr0efQ67lEGYzV3HpR1:bkmer1u) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c0f76c76b467e4fe7ed045e8eabe48eb5bfcf9/drake/systems/framework/test/vector_system_test.cc#L49)):*
> ```cpp
>       *output = input;
>     } else {
>       *output = input + state;
> ```

Merge error?  (Duplicated line.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per rotation, please.

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/vector_system_test.cc, line 49 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-Kr0efQ56F7GM1l2G02C:-Kr0iCSHw6WUf2_suJHF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3c0f76c76b467e4fe7ed045e8eabe48eb5bfcf9/drake/systems/framework/test/vector_system_test.cc#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Merge error?  (Duplicated line.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780)*

**Comment by sherm1** [comment]
Platform :lgtm:.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6780#-:-Kr2C5Nb70SCXyLnYBmI:b-cxwtpi)*

**Pull request merged**
