### PR TITLE
[tools] Remove all uses of pycps

### LINKED ISSUE #15754: Remove dependency on PyCPS
We use [PyCPS](https://github.com/mwoehlke/pycps) during [build time](https://github.com/RobotLocomotion/drake/tree/v0.33.0/tools/workspace/pycps) to help [create](https://github.com/RobotLocomotion/drake/blob/v0.33.0/tools/workspace/spdlog/package-create-cps.py) our install `*.cmake` files.  However, PyCPS uses an LGPL license, which causes problems for some of our users.

To alleviate that pain, either PyCPS will need to offer a different license (either switch licenses, or dual-license) without copyleft, or Drake will need to stop using PyCPS.

(To be clear, we would not want to change the installed footprint, we'd still ship `*.cmake` files.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
PyCPS uses an LGPL license, which causes problems for some of our users.

Closes #15754.

Breaking changes:
- Remove macro `cmake_config()` from `install.bzl`
- Remove `py_library` named `@drake//tools/install:cpsutils`
- Remove workspace external `@pycps`

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/pybind11/pybind11-config.cmake, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15756#-MjG_n_1-vZHVxxWpc4Q:-MjG_n_25fo-TKbh6nqV:bkbfpcz) ([raw file](https://github.com/robotlocomotion/drake/blob/7dcff27b5f3f8b5a58a5558de3f200472b424f0c/tools/workspace/pybind11/pybind11-config.cmake#L63)):*
> ```CMake
> set_target_properties(pybind11::module PROPERTIES
>   INTERFACE_LINK_LIBRARIES "pybind11::pybind11"
>   # TODO(jwnimmer-tri) On Darwin, we need "-undefined dynamic_lookup" here.
> ```

Working

This passes CI without it, but maybe `drake-external-examples` needs it.  I will test on `macsim` next week.

**Comment by ggould-tri** [comment]
Good day, @jwnimmer-tri . This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, then please label it “status: do not review”.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri to begin feature review, please.

Note that (per the reviewable thread) I still need to perform additional testing on macOS.  It has passed Drake CI, but I also want to check drake-external-examples.

**Review by rpoyner-tri — COMMENTED** [review]
overview pass done.

> Reviewed 40 of 44 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756#-:-MjUmU179hJQdKC_URTc:b-5m86bl)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15756#-MjUmFeg5NbGUw_nLROS:-MjUmFeg5NbGUw_nLROT:b-s6kr14) (no related file):*
I guess we consider "generated and subsequently edited by hand" to not be encumbered by license tentacles?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15756#-MjUmFeg5NbGUw_nLROS:-MjUoZzHCqnL50YCaDt2:b-3lfh67) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I guess we consider "generated and subsequently edited by hand" to not be encumbered by license tentacles?
</blockquote></details>

OK The https://github.com/mwoehlke/pycps#license has an explicit disclaimer about this.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756#-:-MjUrraX3cerWXul-_eP:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by mwoehlke-kitware** [comment]
> I guess we consider "generated and subsequently edited by hand" to not be encumbered by license tentacles?

Correct (and explicitly stated, as mentioned elsewhere).

I guess Bazel doesn't easily support the notion of having steps that aren't part of the build and modify files in the source tree? (Or that might be an issue for customers, anyway.)

Is there any expectation that these might change in the future? Would it make sense to continue to generate the `.cps`s (maybe not by default, but not ripped out entirely) and have a script (not integrated with the build) to regenerate the `.cmake`s? (I wish I'd thought of that earlier; it's the obvious "best" solution...)

**Comment by jwnimmer-tri** [comment]
Rather than try to play games with where to draw the line about what is a derivative work, I think that the simple "Don't depend on PyCPS at all, even if only manually invoked" is the best solution for our users that have licensing concerns.

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
___
*[tools/workspace/pybind11/pybind11-config.cmake, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15756#-MjG_n_1-vZHVxxWpc4Q:-MjVYMwk9zlMaEIZDfG2:bplow3w) ([raw file](https://github.com/robotlocomotion/drake/blob/7dcff27b5f3f8b5a58a5558de3f200472b424f0c/tools/workspace/pybind11/pybind11-config.cmake#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This passes CI without it, but maybe `drake-external-examples` needs it.  I will test on `macsim` next week.
</blockquote></details>

I can confirm that this is a regression on macOS, caught only by `drake-external-examples`.  I'm working on a fix.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri and @rpoyner-tri)

___
*[tools/workspace/pybind11/pybind11-config.cmake, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15756#-MjG_n_1-vZHVxxWpc4Q:-MjV_Upp7eCWCgcjGO3r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9b7a693fcc09d3d30c8d9786c542d7dcc396792/tools/workspace/pybind11/pybind11-config.cmake#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can confirm that this is a regression on macOS, caught only by `drake-external-examples`.  I'm working on a fix.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: -- it looks good as best I can discern and CI will know more than I possibly can about the details.  Thanks for retriggering the mac experimental!

> Reviewed 40 of 44 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15756#-:-MjVaBG95NiObgi0kGKL:b-9nconi)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Comment by mwoehlke-kitware** [comment]
Did you hand write all of the `.cmake`s in this PR? If not, then saying we don't "depend" on PyCPS feels morally questionable. It's also *irrelevant*, because what matters is that the repository is not "tainted" by PyCPS¹; not in contents, not in code executed.

We can still say that if we keep the `.cps`s, which would give us the option to use those to maintain the `.cmake`s. (The script doesn't need to live in the Drake repo. `@pycps`, in particular, doesn't need to remain part of the Drake repo.) Otherwise, we're stuck forevermore maintaining the `.cmake`s directly.

If, OTOH, the tools we use to produce code are an issue, well, don't ask what editor I've been using this whole time...

(¹ We might have *other* [L]GPL stuff, but that's orthogonal. A build *definitely* runs *GPL* code, but... don't get me started.)

**Comment by jwnimmer-tri** [comment]
> We're stuck forevermore maintaining the .cmakes directly.

Yes, that will be the status quo moving forward.  If we find that to be particularly difficult, then we can seek out a more automated solution at a later date.

**Comment by jwnimmer-tri** [comment]
Note to users: if you experience any breaking changes _beyond_ the three items mentioned in the commit message, please comment here (or open an issue).  The breaking changes only affect _Bazel_ users; if you only use CMake, then this should be a no-op.

**Pull request merged**
