### PR TITLE
[geometry] Factor recording implementation out of Meshcat

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The user-facing API is unchanged.

Towards #21279.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@DamrongGuoy for feature review, please.
+@rpoyner-tri for platform review, please.

> Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-:-NxJT_bk0KFM6tPrfQc5:b-i69msr)* status: LGTM missing from assignees DamrongGuoy,rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 7 files at r2, 3 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-:-NxJdTuZAB4PY09KAAS5:bnfp4nl)* status: LGTM missing from assignee DamrongGuoy

**Review by DamrongGuoy — COMMENTED** [review]
Checkpoint.  Next, I'll check the unit tests. I should finish it within an hour.

> Reviewed 2 of 5 files at r3, 1 of 1 files at r4, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-:-NxKI6gw3QLu568TmUHN:ben1zra)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy

___
*[`geometry/meshcat_recording_internal.h` line 5 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-NxK1LWc7QwuOotz3wZn:-NxK1LWc7QwuOotz3wZo:b-np6fv9) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e650db9f856ab0065e928c6f7c49b105bc6070c/geometry/meshcat_recording_internal.h#L5)):*
> ```objc
> #include <memory>
> #include <optional>
> #include <string>
> ```

Unused `<string>`?

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-:-NxKZiEB975Di8TWxnz7:bnfp4nl)* status: 2 unresolved discussions

___
*[`geometry/test/meshcat_recording_internal_test.cc` line 87 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-NxKRn9P1G7iQ3Y5qRVm:-NxKRn9P1G7iQ3Y5qRVn:bsce3s3) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e650db9f856ab0065e928c6f7c49b105bc6070c/geometry/test/meshcat_recording_internal_test.cc#L87)):*
> ```cpp
>       auto delta = animation.get_key_frame<double>(frame, "path", "delta");
>       auto victor = animation.get_key_frame<Vec>(frame, "path", "victor");
>       auto position = animation.get_key_frame<Vec>(frame, "path", "position");
> ```

BTW, I think here we use the knowledge that `SetTransform()` would have set the properties "position" and "quaternion." Should we explain that this line is for `SetTransform()` not `SetProperty()`?



_Suggestion:_
```cpp
      // The "position" property came from SetTransform()
      auto position = animation.get_key_frame<Vec>(frame, "path", "position");
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy

___
*[`geometry/test/meshcat_recording_internal_test.cc` line 87 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/21362#-NxKRn9P1G7iQ3Y5qRVm:-NxKcd0B491mQ2QyTfZ1:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e650db9f856ab0065e928c6f7c49b105bc6070c/geometry/test/meshcat_recording_internal_test.cc#L87)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, I think here we use the knowledge that `SetTransform()` would have set the properties "position" and "quaternion." Should we explain that this line is for `SetTransform()` not `SetProperty()`?
</blockquote></details>

Done

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21362)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),DamrongGuoy

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

**Pull request merged**
