### PR TITLE
[py systems] Allow scalar conversion for subclassed diagrams

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Helpful for debugging some MultibodyPlant stuff in pydrake

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@RussTedrake for feature review (if you have time), please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-:-NOWxXdj3tZAbkG28yJc:b-ecl6xv)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 289 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOXDqWGBGDB6tfV2PkD:-NOXDqWGBGDB6tfV2PkE:b-tel2n2) ([raw file](https://github.com/RobotLocomotion/drake/blob/21c65187dbddfccd1e850b32428c0163993ab795/bindings/pydrake/systems/test/scalar_conversion_test.py#L289)):*
> ```Python
>         for T in SystemScalarConverter.SupportedScalars:
>             diagram = MyDiagram_[T]()
>             diagram.CreateDefaultContext()
> ```

this doesn't actually do the scalar conversion (only allocates with different scalars)?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOjcfUj51dzijAsHtab:-NOjcfUj51dzijAsHtac:bfbmc2v) ([raw file](https://github.com/RobotLocomotion/drake/blob/87c0d2a44260d20ab20a0fd399bc65c3d1dc6d83/bindings/pydrake/systems/test/scalar_conversion_test.py#L283)):*
> ```Python
> 
>                 def _construct_copy(self, other, *, converter=None):
>                     self._construct(converter=converter)
> ```

The logic to scalar-convert the constituent systems one by one is already implemented in the Diagram base class (at least for the C++ case).

In `_construct_copy`, unless there is something odd going on with Python that I don't understand yet, here we should simply be calling the base class conversion constructor with the given `converter=converter`, and nothing else.  (If we had extra data in `self.` we would copy it here, but we don't in this example.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 289 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOXDqWGBGDB6tfV2PkD:-NOjg-Av7MJve_EkJsBz:b-qz5atz) ([raw file](https://github.com/RobotLocomotion/drake/blob/21c65187dbddfccd1e850b32428c0163993ab795/bindings/pydrake/systems/test/scalar_conversion_test.py#L289)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this doesn't actually do the scalar conversion (only allocates with different scalars)?
</blockquote></details>

Done. Derp!
___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOjcfUj51dzijAsHtab:-NOjg0ECDRIpI9rnvMrA:bd3idi2) ([raw file](https://github.com/RobotLocomotion/drake/blob/87c0d2a44260d20ab20a0fd399bc65c3d1dc6d83/bindings/pydrake/systems/test/scalar_conversion_test.py#L283)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The logic to scalar-convert the constituent systems one by one is already implemented in the Diagram base class (at least for the C++ case).

In `_construct_copy`, unless there is something odd going on with Python that I don't understand yet, here we should simply be calling the base class conversion constructor with the given `converter=converter`, and nothing else.  (If we had extra data in `self.` we would copy it here, but we don't in this example.)
</blockquote></details>

Done. Added extra data.
I'm concerned about allowance for short-cutting explicit definition of `_construct_copy`, so I prefer to not consider that in this PR.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOjcfUj51dzijAsHtab:-NOjhMDU7ef6GV8JE6Bd:b-y9yk8c) ([raw file](https://github.com/RobotLocomotion/drake/blob/87c0d2a44260d20ab20a0fd399bc65c3d1dc6d83/bindings/pydrake/systems/test/scalar_conversion_test.py#L283)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Added extra data.
I'm concerned about allowance for short-cutting explicit definition of `_construct_copy`, so I prefer to not consider that in this PR.
</blockquote></details>

It is _actively wrong_ to reconstruct the child systems, instead of converting them each in turn. In the case that an original child system was modified somehow (e.g., reconfigured) after constructing the diagram, we'll lose that information if we start from scratch.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @RussTedrake)

___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOjcfUj51dzijAsHtab:-NOjyBxq8LYM6cu6IMU7:ba6382v) ([raw file](https://github.com/RobotLocomotion/drake/blob/87c0d2a44260d20ab20a0fd399bc65c3d1dc6d83/bindings/pydrake/systems/test/scalar_conversion_test.py#L283)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is _actively wrong_ to reconstruct the child systems, instead of converting them each in turn. In the case that an original child system was modified somehow (e.g., reconfigured) after constructing the diagram, we'll lose that information if we start from scratch.
</blockquote></details>

Working: Derp, had typo in my testing that would've highlighted this.

Fixing `[T, U]` pairing for conversion in bindings (that's why linker fails and stuff)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @RussTedrake)

___
*[`bindings/pydrake/systems/scalar_conversion.py` line 8 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOkCqPz94BPKfAxRiUL:-NOkCqPz94BPKfAxRiUM:b6lqv2v) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd9ca4d4049c8d6f344d69c3d42f107925bbf62f/bindings/pydrake/systems/scalar_conversion.py#L8)):*
> ```Python
> from pydrake.common import pretty_class_name
> from pydrake.systems.framework import (
>     LeafSystem_,
> ```

nit From a quick skim, it seems like `LeafSystem_` is unused now.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`bindings/pydrake/systems/scalar_conversion.py` line 8 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOkCqPz94BPKfAxRiUL:-NOkGhgs0QybuZ0F5Z6O:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fd9ca4d4049c8d6f344d69c3d42f107925bbf62f/bindings/pydrake/systems/scalar_conversion.py#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit From a quick skim, it seems like `LeafSystem_` is unused now.
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/test/scalar_conversion_test.py` line 283 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-NOjcfUj51dzijAsHtab:-NOkGiNV3oxGytWNaSNt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87c0d2a44260d20ab20a0fd399bc65c3d1dc6d83/bindings/pydrake/systems/test/scalar_conversion_test.py#L283)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Derp, had typo in my testing that would've highlighted this.

Fixing `[T, U]` pairing for conversion in bindings (that's why linker fails and stuff)
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

We could get someone other than me to count as platform review, though -- to prove that someone other than me can read and understand this code.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-:-NOkK-iN0LPxyB1gjzIq:bfmj9w6)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
sgtm!
+@SeanCurtis-TRI for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-:-NOkLHlz7AVC2FjyREbf:b-zaemd2)* status: 1 unresolved discussion, LGTM missing from assignees RussTedrake(platform),SeanCurtis-TRI(platform), missing label for release notes (waiting on @RussTedrake and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: Seems reasonable to me.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-:-NOkUGzlCby5leZM5V9f:bgfr7vh)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: feature)
Removing -@RussTedrake since we have two other reviewers now.

> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18813#-:-NOklbv91M_nWoM9jLB7:b-5pm520)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
-(release notes: feature) +(release notes: none) due to revert.

**Pull request merged**
