### PR TITLE
pydrake autodiff, symbolic: Add initial tests for scalar and vectorized math

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates #8116 and #8315 

The purpose of this PR is to (a) ~lock down~ elucidate behavior with NumPy arrays and (b) provide a basis for seeing how the solution to #8315 will affect the behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8427)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please.
(Will add either Sherm or Jeremy for platform review.)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-:-L8AvEzJ9OhZvgcojaCf:b55csvi)*

**Comment by soonho-tri** [comment]
Check point.

---

Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/autodiffutils_py.cc, line 69 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CzNWJ1oVmP456D0JF:-L8CzNWJ1oVmP456D0JG:b99d5t5) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/autodiffutils_py.cc#L69)):*
> ```cpp
>          }, py::is_operator());
> 
>     // Add overloads for `sin` and `cos`.
> ```

BTW, this comment is outdated now.

---

*[bindings/pydrake/symbolic_py.cc, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CzoIc1ubfzF1de_ao:-L8CzoIc1ubfzF1de_ap:b-5nozil) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/symbolic_py.cc#L40)):*
> ```cpp
>       .def("__hash__",
>            [](const Variable& self) { return std::hash<Variable>{}(self); })
>       .def("__copy__",
> ```

Could you explain why we need this? If it's necessary, I will update other classes here (i.e. `Monomial`, `Polynomial`) to have `__copy__`.

---

*[bindings/pydrake/util/wrap_pybind.h, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8Cxa6mDv70wMLrpPVE:-L8Cxa6mDv70wMLrpPVF:bj6liv3) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L14)):*
> ```objc
> namespace pydrake {
> 
> // Defines a function in module `m`, and mirrors to module `mirror` for
> ```

Could you update the description to include `From` and `To`?

---

*[bindings/pydrake/util/wrap_pybind.h, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CyR0gBgC6CpIUTHvJ:-L8CyR0gBgC6CpIUTHvK:bar35ow) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L15)):*
> Throws an error...

I think we do not do this anymore? Is it worth documenting why we stopped doing the check?
Also, can we have a Doxygen section for `def` method?

---

*[bindings/pydrake/util/wrap_pybind.h, line 22 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CyaVmAQeZrEn3IURl:-L8CyaVmAQeZrEn3IURm:bvj8l8h) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L22)):*
> ```objc
>   MirrorDef(From* m, To* mirror)
>       : m_(m), mirror_(mirror) {}
> ```

BTW, missing `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN` or `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN`.

---

*[bindings/pydrake/util/wrap_pybind.h, line 31 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D-s613TDi2l6qR9OE:-L8D-s613TDi2l6qR9OF:b3d6rvx) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L31)):*
> ```objc
> 
>  private:
>   From* m_{};
> ```

BTW, make those pointers to be `const`?
```c++
  From* const m_{};
  To* const mirror_{};
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-:-L8D-nkgBoxWxTo_M09q:bubalwb)*

**Comment by soonho-tri** [comment]
First pass complete. Also please assign it to a platform-reviewer.

---

Reviewed 4 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/test/autodiffutils_test.py, line 37 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DJe6PBFYLSWKgHJso:-L8DJe6PBFYLSWKgHJsp:b-wflxeq) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/autodiffutils_test.py#L37)):*
> ```Python
>                 self._check_scalar(a, b)
>         else:
>             self.assertTrue(np.allclose(actual, expected))
> ```

I'm not sure that the use of `np.allclose` is appropriate when it's (always?) the case that the type of `actual` and `expected` is `np.array of np.bool_`.

---

*[bindings/pydrake/test/math_test_util.py, line 12 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DKtaY5qIHQLXnzo4c:-L8DKtaY5qIHQLXnzo4d:b-ygm65q) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L12)):*
> ```Python
> 
>     def reformat(self, scalar):
>         # Reformats a scalar to the given form.
> ```

BTW, to my standard, changing `2` => `[2, 2]` is something more than reformatting. I'd be great if we can find a better name (i.e. `make_T`.. but it's too C++-ish?) with a proper documentation.

---

*[bindings/pydrake/test/math_test_util.py, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D47wv25OI1wvq5CBP:-L8D47wv25OI1wvq5CBQ:bty1j7l) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L15)):*
> ```Python
>         raise NotImplemented
> 
>     def check_value(self, actual, expected_scalar):
> ```

Could you add a documentation for this?
```python
# Checks if `actual` is `expected_scalar`.
```

---

*[bindings/pydrake/test/math_test_util.py, line 18 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D3hdEAVA7TjHim0vv:-L8D3hdEAVA7TjHim0vw:bfk811r) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L18)):*
> ```Python
>         raise NotImplemented
> 
>     def check_logical(self, actual, expected_scalar):
> ```

I guess the signature should be `def check_logical(self, func, a, b, expected_scalar)` instead? Can you add a documentation for this? I think the name `check_logical` is not so much self-explanatory.

---

*[bindings/pydrake/test/math_test_util.py, line 52 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DAsLp9lavw6_hXLbz:-L8DAsLp9lavw6_hXLc-:b-kji3aj) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L52)):*
> ```Python
>         expected = self.reformat(expected_scalar)
>         self._check_value_impl(func(a, b), expected)
>         self._check_value_impl(func(a, b.value()), expected)
> ```

From `.value()`, I assume that `a` and `b` are of `numpy array of AutoDiffXd`. Can we still use `ScalarMath` and `VectorizedMath` classes with `symbolic`? Maybe it's because of my lack of understanding of what `check_logical` is supposed to do.

---

*[bindings/pydrake/test/math_test_util.py, line 80 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DDZvAAK2tdfG0rlQF:-L8DDZvAAK2tdfG0rlQG:b-1nwt0e) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L80)):*
> ```Python
>         self._check_value_impl(actual, expected)
> 
>     def _array_to_float(self, a):
> ```

This method converts an array of `AutoDiffXd` to an array of `float`, correct? Then, I think the name `_array_to_float` is misleading.

---

*[bindings/pydrake/test/math_test_util.py, line 84 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D5VLY03vBcRpXQ5m4:-L8D5VLY03vBcRpXQ5m5:b-wxy1lx) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L84)):*
> ```Python
> 
>     def check_logical(self, func, a, b, expected_scalar):
>         # See above.
> ```

BTW, meant `# See check_logical in ScalarMath`?

---

*[common/test/autodiff_overloads_test.cc, line 55 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DGFLc07Wk4pe44vSm:-L8DGFLc07Wk4pe44vSn:bsnvpzc) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/common/test/autodiff_overloads_test.cc#L55)):*
> ```cpp
>   AutoDiffXd y(3);
>   EXPECT_EQ((x * y).value(), 6);
> ```

Is it worth adding `  EXPECT_EQ((x * y).derivatives().size(), 3);` as well here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-:-L8DL_9h9MEfZbuOmj4C:b-mckek3)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/symbolic_py.cc, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CzoIc1ubfzF1de_ao:-L8Db1JFAOiFJq6fxL5T:b-rp14vw) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/symbolic_py.cc#L40)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you explain why we need this? If it's necessary, I will update other classes here (i.e. `Monomial`, `Polynomial`) to have `__copy__`.
</blockquote></details>

OK It was just a local need for testing.
In the in-place operator tests, you had assigned a value by reference (not value), e.g.:
```
e = e_x   # Mutates global `e_x`
e += e_y
self.assertEquals(e, x + y)  # Works

# Some other test
self.assertEquals(e_x + e_y, x+ y)  # Now fails, because `e_x` has been mutated via an alias in `e`
```

I believe this worked before because either (a) `unittest` was restoring local values or (b) when I changed the scoping, `+=` allowed some sort of reassignment (e.g. for type changes, `x += e_y` might have promoted `x` from `Variable` to `Expression`).

Didn't really try tracking down why specifically, but the issue was solvable by using `e = copy(e_x)` to ensure unique instances.

I'm not sure if it's necessary for other things, but perhaps it would be useful?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CzoIc1ubfzF1de_ao:-L8DcdXy5KWCKCNW8gG8:b-gogwve) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/symbolic_py.cc#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK It was just a local need for testing.
In the in-place operator tests, you had assigned a value by reference (not value), e.g.:
```
e = e_x   # Mutates global `e_x`
e += e_y
self.assertEquals(e, x + y)  # Works

# Some other test
self.assertEquals(e_x + e_y, x+ y)  # Now fails, because `e_x` has been mutated via an alias in `e`
```

I believe this worked before because either (a) `unittest` was restoring local values or (b) when I changed the scoping, `+=` allowed some sort of reassignment (e.g. for type changes, `x += e_y` might have promoted `x` from `Variable` to `Expression`).

Didn't really try tracking down why specifically, but the issue was solvable by using `e = copy(e_x)` to ensure unique instances.

I'm not sure if it's necessary for other things, but perhaps it would be useful?
</blockquote></details>

Yeah, I had the issue. Good to know that it's mainly for the testing. I'll add more if I find use cases in the future. Thank you.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[bindings/pydrake/autodiffutils_py.cc, line 69 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CzNWJ1oVmP456D0JF:-L8Dj7J-0aliqW6bnhK1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/autodiffutils_py.cc#L69)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this comment is outdated now.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/autodiffutils_test.py, line 37 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DJe6PBFYLSWKgHJso:-L8DmXaX5kjghHXS9n0b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/autodiffutils_test.py#L37)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I'm not sure that the use of `np.allclose` is appropriate when it's (always?) the case that the type of `actual` and `expected` is `np.array of np.bool_`.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/wrap_pybind.h, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8Cxa6mDv70wMLrpPVE:-L8DmZk31vipq5N4DSAk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L14)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you update the description to include `From` and `To`?
</blockquote></details>

Done.

---

*[bindings/pydrake/util/wrap_pybind.h, line 22 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CyaVmAQeZrEn3IURl:-L8Dm_JmAgQntvQrlcbU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L22)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, missing `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN` or `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN`.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/wrap_pybind.h, line 31 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D-s613TDi2l6qR9OE:-L8Dm_eu4OCmSvLNOoVc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L31)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, make those pointers to be `const`?
```c++
  From* const m_{};
  To* const mirror_{};
```
</blockquote></details>

Done.

---

*[common/test/autodiff_overloads_test.cc, line 55 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DGFLc07Wk4pe44vSm:-L8DmasX0A5cDDelaGPW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/common/test/autodiff_overloads_test.cc#L55)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is it worth adding `  EXPECT_EQ((x * y).derivatives().size(), 3);` as well here?
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test_util.py, line 12 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DKtaY5qIHQLXnzo4c:-L8Dj9Xi2nPgtoFo_oge:b-ec1ftw) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L12)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, to my standard, changing `2` => `[2, 2]` is something more than reformatting. I'd be great if we can find a better name (i.e. `make_T`.. but it's too C++-ish?) with a proper documentation.
</blockquote></details>

Done. Figgered that `algebra` may be a bit more descriptive. Wasn't sure whether to state array or vectorized algebra, though.

---

*[bindings/pydrake/test/math_test_util.py, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D47wv25OI1wvq5CBP:-L8DjH7BE4SMY42AJheI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you add a documentation for this?
```python
# Checks if `actual` is `expected_scalar`.
```
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test_util.py, line 18 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D3hdEAVA7TjHim0vv:-L8DjHXFAwz-DTr56GVA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L18)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I guess the signature should be `def check_logical(self, func, a, b, expected_scalar)` instead? Can you add a documentation for this? I think the name `check_logical` is not so much self-explanatory.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test_util.py, line 52 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DAsLp9lavw6_hXLbz:-L8DjJUP-kwkLppucIMN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

From `.value()`, I assume that `a` and `b` are of `numpy array of AutoDiffXd`. Can we still use `ScalarMath` and `VectorizedMath` classes with `symbolic`? Maybe it's because of my lack of understanding of what `check_logical` is supposed to do.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test_util.py, line 80 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8DDZvAAK2tdfG0rlQF:-L8DjKXc9Q7GjlQA2jaU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L80)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

This method converts an array of `AutoDiffXd` to an array of `float`, correct? Then, I think the name `_array_to_float` is misleading.
</blockquote></details>

Done.

---

*[bindings/pydrake/test/math_test_util.py, line 84 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8D5VLY03vBcRpXQ5m4:-L8DjKso9Y8O4J29esYo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/test/math_test_util.py#L84)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, meant `# See check_logical in ScalarMath`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427)*

**Comment by EricCousineau-TRI** [comment]
+@sherm1 for platform review, please (given that Soonho is feature reviewing)

---

Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-:-L8DmcS34Ll-DfM0f38f:b-carq0t)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/util/wrap_pybind.h, line 15 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-L8CyR0gBgC6CpIUTHvJ:-L8DmkOa49oUNMubh86_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53f02fa0bbab620459b5e8461252ffe63360c891/bindings/pydrake/util/wrap_pybind.h#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> Throws an error...

I think we do not do this anymore? Is it worth documenting why we stopped doing the check?
Also, can we have a Doxygen section for `def` method?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8427)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/test/algebra_test_util.py, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8427#-L8Dtnh0_rrO7ZIkiwsE:-L8Dtnh0_rrO7ZIkiwsF:b-ku65wm) ([raw file](https://github.com/robotlocomotion/drake/blob/910f248cf4547348dc02ba639c79b99369d2fa12/bindings/pydrake/test/algebra_test_util.py#L11)):*
> ```Python
> class BaseAlgebra(object):
>     # Base class for defining scalar or vectorized (array) algebra and math.
>     # checks on custom types that have numeric relations to `float`.
> ```

BTW, nit, capitalize `checks` -> `Checks`.

---

*[bindings/pydrake/test/algebra_test_util.py, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8427#-L8Du3YGX1bZH5CjB-xf:-L8Du3YGX1bZH5CjB-xg:b-6qvqyd) ([raw file](https://github.com/robotlocomotion/drake/blob/910f248cf4547348dc02ba639c79b99369d2fa12/bindings/pydrake/test/algebra_test_util.py#L54)):*
> ```Python
>     def __init__(self, check_value_impl, scalar_to_float):
>         BaseAlgebra.__init__(self, check_value_impl, scalar_to_float)
>         # Math functions:
> ```

BTW, missing `self.log = drake_math.log`? If this is the case, we need one for the below `VectorizedAlgebra.__init__` (+ tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8427)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8427#-:-L8EEkMA4GUGMj_hZ2e2:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
BTW @RussTedrake Can I ask if there are any other expressions that you're finding that you would like me to guarantee behavior for? (scalar and array algebra-wise)

**Comment by sherm1** [comment]
Platform :lgtm:. Reviewed C++ parts, cursory look at Python code but since we've got four platform reviewers on this I'll deem it adequately reviewed!

---

Reviewed 3 of 8 files at r2, 1 of 4 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8427#-:-L8IZjsDuXz_fDHDh6gQ:bi681xc)*

**Pull request merged**
