### PR TITLE
Loop orientation constraint

### PR DESCRIPTION
**Pull request by RussTedrake**
This is reopened version of #1303 -- after updating based on the code reviews and a pretty painful merge.  :)

### CODE REVIEW

**Comment by RussTedrake** [comment]
closing and reopening now since it wasn't running all the tests.

**Comment by RussTedrake** [comment]
@hongkai-dai -- could I get your help with the failing BMI test?  i've changed the representation in RigidBodyLoop to use RigidBodyFrames, hopefully that's an easy fix for your kinematics code?

**Comment by hongkai-dai** [comment]
Yes, will work on it.

**Comment by hongkai-dai** [comment]
I get the following error when I try to construct RigidBodyManipulator for ABB with robotiq URDF. Will look more closely tomorrow.
```
------------------------------------------------------------------------
       Segmentation violation detected at Sun Sep 13 22:19:29 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Current Visual      : 0x21 (class 4, depth 24)
  Default Encoding    : UTF-8
  GNU C Library       : 2.19 stable
  Host Name           : hongkai-ThinkPad-W530
  MATLAB Architecture : glnxa64
  MATLAB Root         : /usr/local/MATLAB/R2015a
  MATLAB Version      : 8.5.0.197613 (R2015a)
  OpenGL              : hardware
  Operating System    : Linux 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64
  Processor ID        : x86 Family 6 Model 58 Stepping 9, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11501000), display :0

Fault Count: 1


Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 0000000000000009
  RCX = 0000000000000000  RDX = 00007f75b14e4d50
  RSP = 00007f75be1514b8  RBP = 00007f75be151860
  RSI = 0000000000000000  RDI = 0000000000000000

   R8 = 0000000000000000   R9 = 00007f748a7ccbc0
  R10 = 0000000000000000  R11 = 00007f75d33adc70
  R12 = 0000000000000000  R13 = 00007f748993d160
  R14 = 00007f74899fed20  R15 = 00007f759382c1e0

  RIP = 00007f75d53cc1f0  EFL = 0000000000010206

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f75d53cc1f0      /usr/local/MATLAB/R2015a/bin/glnxa64/libmx.so+00766448 _ZN6matrix6detail10noninlined12mx_array_api11mxGetScalarEPK11mxArray_tag+00000000
[  1] 0x00007f75c8e49cea     /usr/local/MATLAB/R2015a/bin/glnxa64/libmex.so+00150762 mexRunMexFile+00000090
[  2] 0x00007f75c8e46a74     /usr/local/MATLAB/R2015a/bin/glnxa64/libmex.so+00137844
[  3] 0x00007f75c8e47684     /usr/local/MATLAB/R2015a/bin/glnxa64/libmex.so+00140932
[  4] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[  5] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[  6] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[  7] 0x00007f75c739f432 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03859506
[  8] 0x00007f75c73a1612 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03868178
[  9] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 10] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 11] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 12] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 13] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[ 14] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 15] 0x00007f75b7c6dedd /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02473693
[ 16] 0x00007f75b7c035c2 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02037186
[ 17] 0x00007f75b7c04ddf /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02043359
[ 18] 0x00007f75b7c0a8e0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02066656
[ 19] 0x00007f75b7c06053 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02048083
[ 20] 0x00007f75b7cf9ef0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03047152
[ 21] 0x00007f75c8128744 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00456516 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 22] 0x00007f75b7cf7451 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03036241
[ 23] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[ 24] 0x00007f75c739f432 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03859506
[ 25] 0x00007f75c73a1612 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03868178
[ 26] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 27] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 28] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 29] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 30] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[ 31] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 32] 0x00007f75b7c6dedd /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02473693
[ 33] 0x00007f75b7c035c2 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02037186
[ 34] 0x00007f75b7c04ddf /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02043359
[ 35] 0x00007f75b7c0a8e0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02066656
[ 36] 0x00007f75b7c06053 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02048083
[ 37] 0x00007f75b7cf9ef0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03047152
[ 38] 0x00007f75c8128744 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00456516 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 39] 0x00007f75b7cf7451 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03036241
[ 40] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[ 41] 0x00007f75c739f432 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03859506
[ 42] 0x00007f75c73a1612 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03868178
[ 43] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 44] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 45] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 46] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 47] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[ 48] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 49] 0x00007f75b7c6dedd /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02473693
[ 50] 0x00007f75b7c035c2 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02037186
[ 51] 0x00007f75b7c04ddf /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02043359
[ 52] 0x00007f75b7c0a8e0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02066656
[ 53] 0x00007f75b7c06053 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02048083
[ 54] 0x00007f75b7cf9ef0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03047152
[ 55] 0x00007f75c8128744 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00456516 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 56] 0x00007f75b7cf7451 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03036241
[ 57] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[ 58] 0x00007f75c739f432 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03859506
[ 59] 0x00007f75c73a1612 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03868178
[ 60] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 61] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 62] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 63] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 64] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[ 65] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 66] 0x00007f75b7c6dedd /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02473693
[ 67] 0x00007f75b7c6e152 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02474322
[ 68] 0x00007f75b7c02edb /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02035419
[ 69] 0x00007f75b7c0354e /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02037070
[ 70] 0x00007f75b7c04ddf /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02043359
[ 71] 0x00007f75b7c0a8e0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02066656
[ 72] 0x00007f75b7c05d20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02047264
[ 73] 0x00007f75b7c05e39 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02047545
[ 74] 0x00007f75b7c0643c /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02049084
[ 75] 0x00007f75b7c06608 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02049544
[ 76] 0x00007f75b7c77e27 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+02514471
[ 77] 0x00007f75b7cf9ccb /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03046603
[ 78] 0x00007f75c8128744 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00456516 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 79] 0x00007f75b7cf7451 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcos_impl.so+03036241
[ 80] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[ 81] 0x00007f75c739f432 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03859506
[ 82] 0x00007f75c73a1612 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03868178
[ 83] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 84] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 85] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 86] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 87] 0x00007f75c817faea /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00813802 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000762
[ 88] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 89] 0x00007f75c73efd20 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04189472
[ 90] 0x00007f75c73704b3 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03667123
[ 91] 0x00007f75c73a06ee /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03864302
[ 92] 0x00007f75c73a7597 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03892631
[ 93] 0x00007f75c73a2cff /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03874047
[ 94] 0x00007f75c73a3934 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03877172
[ 95] 0x00007f75c74192ce /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04358862
[ 96] 0x00007f75c817fc39 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00814137 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00001097
[ 97] 0x00007f75c817ffb0 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_dispatcher.so+00815024 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000032
[ 98] 0x00007f75c73d8495 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+04093077
[ 99] 0x00007f75c7398fb9 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03833785
[100] 0x00007f75c73953f5 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03818485
[101] 0x00007f75c7395ad3 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwm_interpreter.so+03820243
[102] 0x00007f75c908bb6c /usr/local/MATLAB/R2015a/bin/glnxa64/libmwbridge.so+00228204
[103] 0x00007f75c908c751 /usr/local/MATLAB/R2015a/bin/glnxa64/libmwbridge.so+00231249 _Z8mnParserv+00000737
[104] 0x00007f75d478d3af   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00799663 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000031
[105] 0x00007f75d476d133   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00667955
[106] 0x00007f75d476efd9   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00675801 _ZN5boost6detail11task_objectIvNS_3_bi6bind_tIvPFvRKNS_8functionIFvvEEEENS2_5list1INS2_5valueIS6_EEEEEEE6do_runEv+00000025
[107] 0x00007f75d476f9a7   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00678311 _ZN5boost6detail9task_baseIvE3runEv+00000071
[108] 0x00007f75d476fa07   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00678407
[109] 0x00007f75d476ad8a   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00658826
[110] 0x00007f75c672ba56   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwuix.so+00334422
[111] 0x00007f75c67133a2   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwuix.so+00234402
[112] 0x00007f75d4f5bf1f /usr/local/MATLAB/R2015a/bin/glnxa64/libmwservices.so+02621215
[113] 0x00007f75d4f5c08c /usr/local/MATLAB/R2015a/bin/glnxa64/libmwservices.so+02621580
[114] 0x00007f75d4f5dbdf /usr/local/MATLAB/R2015a/bin/glnxa64/libmwservices.so+02628575
[115] 0x00007f75d4f5e61c /usr/local/MATLAB/R2015a/bin/glnxa64/libmwservices.so+02631196 _Z25svWS_ProcessPendingEventsiib+00000092
[116] 0x00007f75d476b408   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00660488
[117] 0x00007f75d476b724   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00661284
[118] 0x00007f75d4757b0d   /usr/local/MATLAB/R2015a/bin/glnxa64/libmwmcr.so+00580365
[119] 0x00007f75d35f3182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
[120] 0x00007f75d332047d                    /lib/x86_64-linux-gnu/libc.so.6+01025149 clone+00000109
[121] 0x0000000000000000                                   <unknown-module>+00000000


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.
```

**Comment by RussTedrake** [comment]
i've verified that drake001 compiles fine when i run make again in the same directory.  no idea why the linker crashed on lcm-logger.  solar flare?  
totally bizarre -- but I've also seen lcm-logger cause a (repeatable) segfault in msvc 2015.  what's going on with that code?

**Comment by RussTedrake** [comment]
yikes.  please do let me know.  hopefully it’s an old version on something lying around in your system?

**Comment by RussTedrake** [comment]
@hongkai-dai  -- did you figure out the crash?

**Comment by hongkai-dai** [comment]
I zapped the old pod-build directory and build again. The crash does not
happen.

**Comment by RussTedrake** [comment]
i can't explain the segfault on drake003: http://drake003.csail.mit.edu/drake/pull-RussTedrake-loop_orientation_constraint-into-RobotLocomotion-master_20150915-1026-Continuous 

nothing here should have gone near that test.

**Pull request merged**
