### PR TITLE
[workspace] Build tinyxml2 from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Deprecate the repository rule for the OS library.

Towards #17231.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17830)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 22 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17830#-:-NBIchIS62B_qBBVfrfK:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review tomorrow, please.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: with a question.

> Reviewed 22 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17830#-:-NBIr9z_92cpuqoNKj69:bbzz5zv)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/workspace/default.bzl` line 355 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17830#-NBIqOsd7UrtxZbGvEvq:-NBIqOsd7UrtxZbGvEvr:b-29dhnn) ([raw file](https://github.com/robotlocomotion/drake/blob/9585b5ee0259509ab4d6f77e167ce41181688342/tools/workspace/default.bzl#L355)):*
> ```Starlark
>     if "tinyobjloader" not in excludes:
>         tinyobjloader_repository(name = "tinyobjloader", mirrors = mirrors)
>     if "tinyxml2" not in excludes:
> ```

question: do we still need this?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17830)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`tools/workspace/default.bzl` line 355 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17830#-NBIqOsd7UrtxZbGvEvq:-NBIrPPb5JxKorHI-_Xg:bvdrlxv) ([raw file](https://github.com/robotlocomotion/drake/blob/9585b5ee0259509ab4d6f77e167ce41181688342/tools/workspace/default.bzl#L355)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

question: do we still need this?
</blockquote></details>

Yes, per the [Stable API](https://drake.mit.edu/stable.html#build-system) section about `default.bzl` _"... we will deprecate it prior to removing our definition of the dependency"_.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17830)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/workspace/default.bzl` line 355 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17830#-NBIqOsd7UrtxZbGvEvq:-NBIwf0H7xQgsFPHOWNs:b-qhc895) ([raw file](https://github.com/robotlocomotion/drake/blob/9585b5ee0259509ab4d6f77e167ce41181688342/tools/workspace/default.bzl#L355)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, per the [Stable API](https://drake.mit.edu/stable.html#build-system) section about `default.bzl` _"... we will deprecate it prior to removing our definition of the dependency"_.
</blockquote></details>

I see. Thanks for the reference.

**Pull request merged**
