### PR TITLE
[trajectories] Add PiecewisePose::MakeLinear

### PR DESCRIPTION
**Pull request by RussTedrake**
Helper method when the goal is to have a first-order position trajectory.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@siyuanfeng-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803#-:-MkCBtjw4duIk7AV9DY2:b-1z9bi2)* status: LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @siyuanfeng-tri)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803#-:-MkCl8Yt5_mYPodQhutU:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by SeanCurtis-TRI — COMMENTED** [review]
You have a typo and an under-tested function.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803#-:-MkD4vSp4M3A8oPMx7X8:brleruj)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[common/trajectories/piecewise_pose.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD3q1TAJvCNRFmPGD6:-MkD3q1TAJvCNRFmPGD7:bd8hb2k) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/piecewise_pose.h#L41)):*
> ```objc
> 
>   /**
>    * Constructs a PiecewisePose from given @p time and @p poses. The positions
> ```

nit s/time/times
___
*[common/trajectories/test/piecewise_pose_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD4KY18Hrz7DOrELEt:-MkD4KY18Hrz7DOrELEu:b-6n13rd) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/test/piecewise_pose_test.cc#L222)):*
> ```cpp
> GTEST_TEST(PiecewisePoseMakeTest, MakeLinear) {
>   const std::vector<double> times = {1., 2., 3.};
>   const std::vector<RigidTransformd> poses{
> ```

nit: These transforms fail to test the orientation slerp. It's the identity orientation in all poses. The documentation clearly promises slerp, that promise should be validated here.
___
*[common/trajectories/test/piecewise_pose_test.cc, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD4eFj6wn7gOqDxJ35:-MkD4eFj6wn7gOqDxJ36:b-dtiqg) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/test/piecewise_pose_test.cc#L237)):*
> ```cpp
>   EXPECT_EQ(position.end_time(), 3.);
>   EXPECT_EQ(position.get_number_of_segments(), 2);
>   EXPECT_EQ(position.getSegmentPolynomialDegree(0), 1);
> ```

nit: While this proves the first-order hold documented for the function, it doesn't show that it's a first-order hold *on the inputs*. Nothing in these tests depends on the values passed into poses -- only on the counts.

**Review by RussTedrake — COMMENTED** [review]
Done.  PTAL.  Would love to land this in time for it to make it into the nightly docker images.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803#-:-MkFSgZo5WT6JZ-jrydm:b-i2lze1)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @siyuanfeng-tri)

___
*[common/trajectories/test/piecewise_pose_test.cc, line 222 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD4KY18Hrz7DOrELEt:-MkFS64JB-c5z_BSm8P8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/test/piecewise_pose_test.cc#L222)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: These transforms fail to test the orientation slerp. It's the identity orientation in all poses. The documentation clearly promises slerp, that promise should be validated here.
</blockquote></details>

Done.
___
*[common/trajectories/test/piecewise_pose_test.cc, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD4eFj6wn7gOqDxJ35:-MkFSH3xDIKA5lk6hL1P:b-g6ph57) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/test/piecewise_pose_test.cc#L237)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: While this proves the first-order hold documented for the function, it doesn't show that it's a first-order hold *on the inputs*. Nothing in these tests depends on the values passed into poses -- only on the counts.
</blockquote></details>

The last line of this test depends on the values passed into poses, and tests the linear interpolation.  I've added one more for the second segment.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15803#-:-MkFhQOs5ZwmDwE6INcU:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees siyuanfeng-tri,SeanCurtis-TRI(platform) (waiting on @RussTedrake)

___
*[common/trajectories/test/piecewise_pose_test.cc, line 237 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15803#-MkD4eFj6wn7gOqDxJ35:-MkFhKAq4JMenmc1Q3RC:bw4b0gb) ([raw file](https://github.com/robotlocomotion/drake/blob/99de512f8bb46bd701b5c603fb8e9f6452aca782/common/trajectories/test/piecewise_pose_test.cc#L237)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The last line of this test depends on the values passed into poses, and tests the linear interpolation.  I've added one more for the second segment.
</blockquote></details>

Yes. Of course. You're absolutely right.

**Pull request merged**
