### PR TITLE
Proposal to allow implicit one-arg ctors

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2231)

### CODE REVIEW

**Comment by liangfok** [comment]
Left some comments in initial review.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnQKYQwdJTX86VrqL:-KGlnQKZ6KuImKfQjd8p:886775104) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Add a note saying this is an exception to [Implicit Conversions](https://google.github.io/styleguide/cppguide.html#Implicit_Conversions) rule.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnfi8igUVWlwiV8vG:-KGlnfi8igUVWlwiV8vH:-24596675) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
To be more clear, consider changing:

```
a majority of arithmetic operators
```
to be:

```
the following arithemetic operators: AAA, BBB, CCC,...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-:-KGlo0bzkCwg5eQuMWu5:-290758285)*

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnfi8igUVWlwiV8vG:-KGloH-DzVOZYZ6JE9VI:-1052686714) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
I suspect that classes that omit one or two arithmetic operators will be common, and will omit different ones.  For instance Polynomial omits `/`, Eigen omits the inequality operators, and so forth.  I updated this to require `+`, both `-`s, `*`, and `==`; I am not quite sure that's right but it seems pretty good.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnQKYQwdJTX86VrqL:-KGlsRCOlRugf-v8TEtc:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by liangfok** [comment]
Left a minor comment.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnfi8igUVWlwiV8vG:-KGlt7mbNWECbRu0g1QH:347198834) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
OK we can refine these mathematical operator details over time. I think the minimal set you've listed is a good start. 

Another option is to go ahead and provide every mathematical operator including `/` and the inequality operators and to simply throw an exception if someone tries to use one that doesn't make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-:-KGlt_FxJJyipIJsrdtf:-1877026227)*

**Comment by liangfok** [comment]
*[drake/doc/code_style_guide.rst, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGluTST2jT08EUexNQ9:-KGluTSUteBtZdGSVKrb:710295836) ([raw file](https://github.com/robotlocomotion/drake/blob/ec4f1c9c33964400fa67eb480418500683a8692c/drake/doc/code_style_guide.rst#L45)):*
"Implicity" --> "Implicit".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by liangfok** [comment]
*[drake/doc/code_style_guide.rst, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlud63aO9fXM_K2fLK:-KGlud63aO9fXM_K2fLL:-449477659) ([raw file](https://github.com/robotlocomotion/drake/blob/ec4f1c9c33964400fa67eb480418500683a8692c/drake/doc/code_style_guide.rst#L45)):*
What does "both of `-`" mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlnfi8igUVWlwiV8vG:-KGlv-_4-_jhBx-4wnAk:-2113963215) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
No!  The compiler should tell you that your algebra is unsupported, not waiting until runtime.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGlv7O4q3C6_8ckjqCY:-795647116) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Add a hyperlink back to this PR, to provide context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGlwAP-rgPhmZaK1LQw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Done.

---

*[drake/doc/code_style_guide.rst, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGluTST2jT08EUexNQ9:-KGlw5AfWNsctItc6XdT:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ec4f1c9c33964400fa67eb480418500683a8692c/drake/doc/code_style_guide.rst#L45)):*
Done.

---

*[drake/doc/code_style_guide.rst, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlud63aO9fXM_K2fLK:-KGlw6dVEuqJATNR6dk1:79684479) ([raw file](https://github.com/robotlocomotion/drake/blob/ec4f1c9c33964400fa67eb480418500683a8692c/drake/doc/code_style_guide.rst#L45)):*
Both unary and binary.  Clarified in the text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-:-KGlwJB0WGFMQboge4tL:-1868698381)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGlx29wog0T8de9SKhr:822076737) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Link should be to github (like all the other links that precede it), not reviewable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGlxwNs6kTeAG2FjnGx:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGlz9BRBPHNEhkvkzzf:-84261305) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
/me hums a circus song.

The canonical URL is `RobotLocomotion` not `robotlocomotion`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 45 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-KGlv7O4q3C6_8ckjqCX:-KGm0ax6jju5xvazyVCc:1023773071) ([raw file](https://github.com/robotlocomotion/drake/blob/dd339082852c4ecc2a7fce20c861ee58a5f0a1bf/drake/doc/code_style_guide.rst#L45)):*
I literally copy-pasted that from the link at the top of this reviewable.  Perhaps reviewable is out of range of your canon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2231#-:-KGm3w8qOC1JSdxl29Hi:1417088721)*

**Comment by jwnimmer-tri** [comment]
Doc-only change, which is not covered by jenkins.
Using override-merge bits now.

**Pull request merged**
