### PR TITLE
Change comment openers and replace int32_t with int

### PR DESCRIPTION
**Pull request by zachfang**
Per discussion in Slack-

- Replace comment openers `/**` with `/*` for all the internal classes.
- Replace `int32_t` with `int` for `http_code` and `port` variables.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16827)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, thanks!

cc @svenevs

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16827#-:-MygnYuF0t8ejIEtWm9M:b-axkma4)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16827#-:-MygpVubCFmYF0tIYPPY:bnfp4nl)* status: 5 unresolved discussions, missing label for release notes (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16827#-MygpmWe9wUshrMQw4-j:-MygpmWe9wUshrMQw4-k:b-1vdg4h) (no related file):*
nit The `class RenderEngineGltfClient` should be within `namespace internal`, and thus also change the comment openers.  The factory function `MakeRenderEngineGltfClient` and its helper `struct RenderEngineGltfClientParams` should be the only public API.

---
___
*[geometry/render/dev/http_service_curl.h, line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16827#-Mygpd93CneTRkck_WKz:-Mygpd93CneTRkck_WL-:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e0b6f6deee01eb798f4fdd165ee5ba95f1c150e/geometry/render/dev/http_service_curl.h#L17)):*
> ```objc
> namespace internal {
> 
> /** An HttpService that uses libcurl to communicate with the server. */
> ```

nit



_Suggestion:_
```objc
/* An
```
___
*[geometry/render/dev/http_service_curl.h, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16827#-MygpfHN7yDStzMoIwPS:-MygpfHN7yDStzMoIwPT:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e0b6f6deee01eb798f4fdd165ee5ba95f1c150e/geometry/render/dev/http_service_curl.h#L24)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(HttpServiceCurl);
> 
>   /** @see HttpService::PostForm */
> ```

nit



_Suggestion:_
```objc
/* @see
```
___
*[geometry/render/dev/render_client.cc, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16827#-MygozgF2I1yCldVKmcT:-MygozgF2I1yCldVKmcU:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e0b6f6deee01eb798f4fdd165ee5ba95f1c150e/geometry/render/dev/render_client.cc#L134)):*
> ```cpp
> /* Return '{url}' if port is <= 0, '{url}:{port}' otherwise.  Used for
>  populating error messages. */
> std::string UrlWithPort(const std::string& url, int32_t port) {
> ```

nit



_Suggestion:_
```cpp
int port
```
___
*[geometry/render/dev/render_client.cc, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16827#-Mygp39ICe3_ojzbMDE9:-Mygp39J1B-TBK2KZgN7:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e0b6f6deee01eb798f4fdd165ee5ba95f1c150e/geometry/render/dev/render_client.cc#L141)):*
> ```cpp
> }  // namespace
> 
> RenderClient::RenderClient(const std::string& url, int32_t port,
> ```

nit



_Suggestion:_
```cpp
int port
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16827)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16827#-MygpmWe9wUshrMQw4-j:-MyhD4GuCQdEUyIsw9wi:b-brp3lq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The `class RenderEngineGltfClient` should be within `namespace internal`, and thus also change the comment openers.  The factory function `MakeRenderEngineGltfClient` and its helper `struct RenderEngineGltfClientParams` should be the only public API.
</blockquote></details>

Thanks. Will resolve `RenderEngineGltfClient` namespacing and [related issue](https://github.com/RobotLocomotion/drake/blob/master/geometry/render/dev/render_engine_gltf_client.h#L14_L16) in another PR.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16827)* status: missing label for release notes (waiting on @zachfang)

**Pull request merged**
