### PR TITLE
Value: fix types in bad cast message

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #15434

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +@jwnimmer-tri for both reviews.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089#-:-MoKa27C6wTnjsjDLaJM:b-cunuh9)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoKpVUg9cZXlj4UzhG5:-MoKpVUg9cZXlj4UzhG6:b-j4n3uh) (no related file):*
I am not sure that this change is responsive to the issue.

The issue confusion revolves around what type within an inheritance hierarchy should be used when erasing and then retrieving an abstract value.

When that kind of confusion is in play, printing out only either the static type or dynamic type on its own is probably not sufficient.  We'll say "cast to MyVector failed because it was actually a BasicVector" but that's somehow both true and false at the same time -- the value _is_ a BasicVector and _is_ a MyVector, and the user still has no idea what's wrong.

How about saying something like this: _"a request to cast to '{requested_type}' failed because the value was created using the static type '{nice_static_type_info}' (with a dynamic type of '{nice_dynamic_type_info}')"_, and to avoid confusion in the common case of no subtyping, the parenthetical should only appear in case where the static and dynamic types differ.

So, for this test case, we'd see _"a request to cast to 'MyVector' failed because the value was created using the static type 'BasicVector' (with a dynamic type of 'MyVector')"_, which seems better to me.

WDYT?

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoKpVUg9cZXlj4UzhG5:-MoL89_2EWURi6pWotx-:b-3zpynq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am not sure that this change is responsive to the issue.

The issue confusion revolves around what type within an inheritance hierarchy should be used when erasing and then retrieving an abstract value.

When that kind of confusion is in play, printing out only either the static type or dynamic type on its own is probably not sufficient.  We'll say "cast to MyVector failed because it was actually a BasicVector" but that's somehow both true and false at the same time -- the value _is_ a BasicVector and _is_ a MyVector, and the user still has no idea what's wrong.

How about saying something like this: _"a request to cast to '{requested_type}' failed because the value was created using the static type '{nice_static_type_info}' (with a dynamic type of '{nice_dynamic_type_info}')"_, and to avoid confusion in the common case of no subtyping, the parenthetical should only appear in case where the static and dynamic types differ.

So, for this test case, we'd see _"a request to cast to 'MyVector' failed because the value was created using the static type 'BasicVector' (with a dynamic type of 'MyVector')"_, which seems better to me.

WDYT?
</blockquote></details>

Too much is always better than not enough. PTAL

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoKpVUg9cZXlj4UzhG5:-MoL9o0bB-ZP64-9sQHP:bcqr7nc) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Too much is always better than not enough. PTAL
</blockquote></details>

Whee. further-afield tests to fix up.

---

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089#-:-MoLFfYf1oWe26oLPygD:bgm2fo4)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

___
*[common/test/value_test.cc, line 560 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoLEkO4E5y7qlCDnkoZ:-MoLEkO5CHbu7QFnOduR:b-hn5quc) ([raw file](https://github.com/robotlocomotion/drake/blob/fdd9a33a3d01f5dfd094861735457f340d957619/common/test/value_test.cc#L560)):*
> ```cpp
>     // Make a base-typed value container with a more-derived value inside.
>     auto value =
>         std::make_unique<Value<BasicVector<double>>>(MyVector<double, 1>{});
> ```

nit Consider `using MyVector1d = systems::MyVector<double, 1>;` atop this function, instead.  That would simplify some of the line noise in this code that follows (like the extra parens here).
___
*[common/test/value_test.cc, line 582 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoLEzs38YN6tuMlTgx2:-MoLEzs38YN6tuMlTgx3:b-w3rk5k) ([raw file](https://github.com/robotlocomotion/drake/blob/fdd9a33a3d01f5dfd094861735457f340d957619/common/test/value_test.cc#L582)):*
> ```cpp
>     DRAKE_EXPECT_THROWS_MESSAGE(
>         abstract.get_value<double>(),
>         ".*request.*double.*static.*int'.$");
> ```

nit It took me a minute to deduce that "singlequote somechar EOL" was a magic anchor that proves which throw statement happened, because there is no closing-paren allowed here.  That's probably worth a comment here of some kind.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoKpVUg9cZXlj4UzhG5:-MoLGN2iC3Zjtzq38zJe:b-896fix) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Whee. further-afield tests to fix up.
</blockquote></details>

Done.

---
___
*[common/test/value_test.cc, line 582 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoLEzs38YN6tuMlTgx2:-MoLG9574nmDBvMd8Oct:b-16pdvt) ([raw file](https://github.com/robotlocomotion/drake/blob/fdd9a33a3d01f5dfd094861735457f340d957619/common/test/value_test.cc#L582)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a minute to deduce that "singlequote somechar EOL" was a magic anchor that proves which throw statement happened, because there is no closing-paren allowed here.  That's probably worth a comment here of some kind.
</blockquote></details>

erm, could be `\\.' to indicate actually matching period.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

___
*[common/test/value_test.cc, line 582 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoLEzs38YN6tuMlTgx2:-MoLHwmb8S8yvqqeS3uP:b-egrwqp) ([raw file](https://github.com/robotlocomotion/drake/blob/fdd9a33a3d01f5dfd094861735457f340d957619/common/test/value_test.cc#L582)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

erm, could be `\\.' to indicate actually matching period.
</blockquote></details>

The extra escaping is good, but the _purpose_ of the regex still isn't clear enough on first reading unless it has a comment explaining to the reader what's going on in terms of the glass-box locking down the branching within the implementation.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

___
*[common/test/value_test.cc, line 582 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16089#-MoLEzs38YN6tuMlTgx2:-MoLKDeK9NxK-XMfpwhz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fdd9a33a3d01f5dfd094861735457f340d957619/common/test/value_test.cc#L582)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The extra escaping is good, but the _purpose_ of the regex still isn't clear enough on first reading unless it has a comment explaining to the reader what's going on in terms of the glass-box locking down the branching within the implementation.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16089#-:-MoLKzZhCAYuoACZImxu:bnfp4nl)* status: missing label for release notes (waiting on @rpoyner-tri)

**Pull request merged**
