### PR TITLE
[DRAFT] SapSolver with sparsity analysis and constraints

### PR DESCRIPTION
**Pull request by amcastro-tri**
Prototype branch for design discussion of the full featured SapSolver.
(Sorry, I accidentally deleted #16501. This is an exact clone). 

cc'ing @xuchenhan-tri, @joemasterjohn

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16543)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Ouch, accidental `-d` instead of `-f`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16543#-:-MvPRqrX8-JuJ9R8N6v9:b-945p5q)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Review by amcastro-tri — COMMENTED** [review]
yeap, that was the one :-( 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16543#-:-MvPUEP94k-lAkjwLZsV:b-y3z68)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

**Comment by jwnimmer-tri** [comment]
FYI the "unused" in the label name "unused status: skip ci" means that the label is vestigial and should never be used.

**Review by amcastro-tri — COMMENTED** [review]
@jwnimmer-tri, is there another way to skip CI for these draft PRs?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16543#-:-MxZjELiET_zmJnOkgme:be7j541)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Comment by jwnimmer-tri** [comment]
There is no way to disable CI.

If you like, you can change your PR so that it fails more quickly.  See step (3) at https://drake.mit.edu/release_playbook.html for one example.

**Comment by jwnimmer-tri** [comment]
@amcastro-tri do you still need this PR open?  It hasn't been updated in a couple of months.

**Comment by amcastro-tri** [comment]
nope, this has diverged from master quite a bit and what we have in master is actually better.
No need to keep it open. Thanks @jwnimmer-tri

**Pull request closed without merging**
