### PR TITLE
adding a opt-out flag for the "Welding ..." printout in RBT.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9554)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
I would be not be sad at all if this were changed to opt-in; I've never found any of these diagnostics to be useful and I always ignore them. For joint ordering, there are other, less invasive-by-default ways to handle that.

W.r.t. the objections in #5678, I mainly see them as useful to people who are debugging constructing new trees, in which case I'd say opting in is sufficient for all messages.

**Comment by siyuanfeng-tri** [comment]
i'd be more happy to opt-in as well, @sherm1 what do you think?

**Comment by jwnimmer-tri** [comment]
@sherm1 Previously discussed in #928, #7701, #5678, #7544 as to why this message is (sometimes) required.

**Comment by sherm1** [comment]
OK, thanks for the background Jeremy. After reading those I have to say I remain skeptical that anyone will opt to turn on the Info-level messages, but I don't see any real harm in having it here.

**Comment by jwnimmer-tri** [comment]
(Yup, I'm pretty much the same.  But Grant, who spent many days fighting with RBT back in the day as a user, was burned pretty hard and felt strongly about it, so I'm generally happy to defer to that experience.)

**Pull request merged**
