### PR TITLE
Add '--verify' flag to kcov

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8384)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-coverage-everything please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-coverage-everything please

**Comment by BetsyMcPhail** [comment]
This reduced the number of failing tests on gcc-coverage builds from [85](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-gcc-bazel-nightly-coverage-everything-64&field2=buildstarttime&compare2=84&value2=now) to [3](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-gcc-bazel-experimental-coverage-everything-debug-3&field2=buildstarttime&compare2=84&value2=now).

**Comment by BetsyMcPhail** [comment]
+@jamiesnape for feature review and +@sammy-tri  for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8384#-:-L8bdnY7-Hi3wiONn3Vs:b99uoub)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8384)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8384#-:-L8be35J5CmMctPmp3jp:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8384#-:-L8bfKnW18Z0ihn7q0pw:bg7igkv)*

**Pull request merged**
