### PR TITLE
trajectory: Add documentation about time clamping

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #17934
(can resolve if so desired)

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for review, please!
\cc @calderpg-tri

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935#-:-NC5nFgEBjkx5CaKWwMI:b-twybka)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC5pfVd8z9J4wdEZvSh:b-1sezfo) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
> ```objc
>    * Evaluates the trajectory at the given time \p t.
>    * @param t The time at which to evaluate the trajectory. This value will be
>    * clamped to be within [start_time, end_time].
> ```

`DiscreteTimeTrajectory` is already a counter-example to the proposed new contract of:

```
   * @param t The time at which to evaluate the trajectory. This value will be
   * clamped to be within [start_time, end_time].
```

(It throws when out-of-range, it doesn't clamp to a terminal value.)

I don't think we can mandate clamping in the base class, nor forbid extrapolation.  We can make it clear in the base class that interpretation the time arg semantics are up to the subclass, and make each subclass clear about what it does in case of out-of-range times.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC5rJpXCmsXphGYNhdQ:b-2ah30j) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`DiscreteTimeTrajectory` is already a counter-example to the proposed new contract of:

```
   * @param t The time at which to evaluate the trajectory. This value will be
   * clamped to be within [start_time, end_time].
```

(It throws when out-of-range, it doesn't clamp to a terminal value.)

I don't think we can mandate clamping in the base class, nor forbid extrapolation.  We can make it clear in the base class that interpretation the time arg semantics are up to the subclass, and make each subclass clear about what it does in case of out-of-range times.
</blockquote></details>

I find the inconsistency to be a defect w/ that implementation, but yes, as interface is written, I guess it admits it.
However, that makes the consumer's life kind of hard, no?
Any interface accepting `Trajectory` can basically trust nothing in terms of behavior w/ time, and thus must perform their own clamping.

Is that practical? (maybe it is, and if so, I'd like to document it.)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC5t_NdAtSF5T-8GD8C:bj9xklc) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
> ... thus must perform their own clamping.

Only if they actually want clamping (saturation) as their semantics.  If they want extrapolation, then they'll need to do something different.  Ditto in case they want to throw or otherwise fail-fast for certain times (e.g., throw when `< start`; saturate when `> end`).  Many users will not attempt to evaluate the trajectory out-of-range in the first place, so it's generally moot.

I think the semantics for out-of-range times should be up to the user, and I don't think Drake is getting in the way of them reaching any particular semantics.  All of those options could all be implemented as decorators (in the C++ sense) around a Trajectory object.  If we think there's need to sugar that up by providing those decorators out of the box, we could do so.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC5yQAK6Hv8sCy8mAEo:bp7oo3r) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... thus must perform their own clamping.

Only if they actually want clamping (saturation) as their semantics.  If they want extrapolation, then they'll need to do something different.  Ditto in case they want to throw or otherwise fail-fast for certain times (e.g., throw when `< start`; saturate when `> end`).  Many users will not attempt to evaluate the trajectory out-of-range in the first place, so it's generally moot.

I think the semantics for out-of-range times should be up to the user, and I don't think Drake is getting in the way of them reaching any particular semantics.  All of those options could all be implemented as decorators (in the C++ sense) around a Trajectory object.  If we think there's need to sugar that up by providing those decorators out of the box, we could do so.
</blockquote></details>

Makes sense to me. I'd like to hear Hongkai and Calder's thoughts, then I am happy to put forward a simple version of the sugar.

In my mind, the simplest sugar is adding `ClampTime(t)` and `ThrowIfExtrapolating(t)`, which I have stake in.
Then I'd route this through usages of `Trajectory<>` in Anzu.

After that, perhaps wrapper trajectory such as `ClampedTrajectory`.
However, I have no current stake in this solution, as it may also be annoying to plumb for hierarchical polynomial types like our piecewise pose stuff.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC6TR465mnyTB3yWG7e:b-mmkusm) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Makes sense to me. I'd like to hear Hongkai and Calder's thoughts, then I am happy to put forward a simple version of the sugar.

In my mind, the simplest sugar is adding `ClampTime(t)` and `ThrowIfExtrapolating(t)`, which I have stake in.
Then I'd route this through usages of `Trajectory<>` in Anzu.

After that, perhaps wrapper trajectory such as `ClampedTrajectory`.
However, I have no current stake in this solution, as it may also be annoying to plumb for hierarchical polynomial types like our piecewise pose stuff.
</blockquote></details>

I don't object in principle to having (presumably non-virtual) sugar functions on Trajectory that provide easy way to interface some `double time` that the user has in hand with the `[start, end]` range of the `this` object -- either clamping and/or range-checking that time.

(We have `PieceswiseTrajectory::is_time_in_range()` already; perhaps it should move up to the base class.)

However, I guess I still don't understand the problem those would solve; I don't understand where they would be used?  I went looking for logic that is already doing this which would be abstracted with this sugar, and I only found two places -- the `TrajectorySource<T>::DoCalcVectorOutput` and `PiecewisePose<T>::GetVelocity` do a range check on the time and hard-code zero velocities in that case (instead of differentiating).  That would be sufficiently sugared by promoting `is_time_in_range` to the base class.

Any Trajectory subclass should specify what happens for times outside of `[start, end]` -- in other words, the trajectory's value beyond the range is well-defined: either some specific math, or an exception.  In most cases, the using-code shouldn't need to call the sugar functions to edit/check the time -- the user should be able to just evaluate the trajectory `value()` without any guard.

Are there cases where code needs to check that a time value it has in-hand falls within the `[start, end]` particularly?  Maybe in case it is using a Trajectory subclass that would throw on out-of-range, and but it doesn't want it to throw?  If you could provide a concrete practical example, that might help clarify what you're getting at.

If the big picture here is just that "concrete subclasses of Trajectory should take care choose and document useful semantics when evaluated outside of [start, end]", I would certainly buy that.  It sounds like the maybe the CRU TOTP trajectory didn't do that, which was the source of your pain.

I might even buy that subclasses should nominally either clamp the time (i.e., hold the start/final sample) or else throw when time is out-of-range.  I'm just not sure what making that an API _requirement_ would buy us.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC6_Bcy6VlKSjBQS3sq:b-x6t5bb) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't object in principle to having (presumably non-virtual) sugar functions on Trajectory that provide easy way to interface some `double time` that the user has in hand with the `[start, end]` range of the `this` object -- either clamping and/or range-checking that time.

(We have `PieceswiseTrajectory::is_time_in_range()` already; perhaps it should move up to the base class.)

However, I guess I still don't understand the problem those would solve; I don't understand where they would be used?  I went looking for logic that is already doing this which would be abstracted with this sugar, and I only found two places -- the `TrajectorySource<T>::DoCalcVectorOutput` and `PiecewisePose<T>::GetVelocity` do a range check on the time and hard-code zero velocities in that case (instead of differentiating).  That would be sufficiently sugared by promoting `is_time_in_range` to the base class.

Any Trajectory subclass should specify what happens for times outside of `[start, end]` -- in other words, the trajectory's value beyond the range is well-defined: either some specific math, or an exception.  In most cases, the using-code shouldn't need to call the sugar functions to edit/check the time -- the user should be able to just evaluate the trajectory `value()` without any guard.

Are there cases where code needs to check that a time value it has in-hand falls within the `[start, end]` particularly?  Maybe in case it is using a Trajectory subclass that would throw on out-of-range, and but it doesn't want it to throw?  If you could provide a concrete practical example, that might help clarify what you're getting at.

If the big picture here is just that "concrete subclasses of Trajectory should take care choose and document useful semantics when evaluated outside of [start, end]", I would certainly buy that.  It sounds like the maybe the CRU TOTP trajectory didn't do that, which was the source of your pain.

I might even buy that subclasses should nominally either clamp the time (i.e., hold the start/final sample) or else throw when time is out-of-range.  I'm just not sure what making that an API _requirement_ would buy us.
</blockquote></details>

The practical example of running into this behavior is the various `MotionPrimitive` implementations in anzu that use trajectories. Because of how the control loop works (although I don't think this is specific to RobotBridge per se, anything with a flow like it would encounter the same issue) the control flow looks like

1. At `t == traj_duration - epsilon` the control loop calls `primitive_->Control(&tmp_output)` that returns `(q, v)` for just before the end of the trajectory and `MotionStatus::EXECUTING`
2. Control loop updates `primitive_output_ = tmp_output` (which updates saved desired position)
3. Commands sent to the robot
4. Time advances beyond `traj_duration`
5. At `t == traj_duration + epsilon` the control loop calls `primitive_->Control(&tmp_output)` and the trajectory is queried slightly beyond the end of the trajectory (because that's what it was asked to do) and `MotionStatus::DONE`
6. Control loop kills the primitive
7. Control loop updates `primitive_output_ = tmp_output` (which updates saved desired position)

TOTP happens to extrapolate, which is how this behavior was noticed, but it would have been equally problematic (although presumably caught much sooner) if one of the trajectory types used was `DiscreteTimeTrajectory` and it threw.

We could obviously implement a separate `query time = min(traj_duration, t)` at each of these calls, but it would be nice to have a consistent way of expressing that we want the the query time clamped to `[0, traj_duration]`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri, @EricCousineau-TRI, and @hongkai-dai)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC6r5Hl4wVh3bt39J74:b-uclb4k) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The practical example of running into this behavior is the various `MotionPrimitive` implementations in anzu that use trajectories. Because of how the control loop works (although I don't think this is specific to RobotBridge per se, anything with a flow like it would encounter the same issue) the control flow looks like

1. At `t == traj_duration - epsilon` the control loop calls `primitive_->Control(&tmp_output)` that returns `(q, v)` for just before the end of the trajectory and `MotionStatus::EXECUTING`
2. Control loop updates `primitive_output_ = tmp_output` (which updates saved desired position)
3. Commands sent to the robot
4. Time advances beyond `traj_duration`
5. At `t == traj_duration + epsilon` the control loop calls `primitive_->Control(&tmp_output)` and the trajectory is queried slightly beyond the end of the trajectory (because that's what it was asked to do) and `MotionStatus::DONE`
6. Control loop kills the primitive
7. Control loop updates `primitive_output_ = tmp_output` (which updates saved desired position)

TOTP happens to extrapolate, which is how this behavior was noticed, but it would have been equally problematic (although presumably caught much sooner) if one of the trajectory types used was `DiscreteTimeTrajectory` and it threw.

We could obviously implement a separate `query time = min(traj_duration, t)` at each of these calls, but it would be nice to have a consistent way of expressing that we want the the query time clamped to `[0, traj_duration]`.
</blockquote></details>

If you evaluate a `DiscreteTimeTrajectory` at a time other than one of its provided times (within an epsilon), then it _should_ throw -- not clamp.  It's entire purpose in life is to provide canned values, with no wiggle room.  Presumably if you're using a `DiscreteTimeTrajectory` in a motion primitive, then you've set your motion primitive timestep to exactly match the trajectory's timestep, so there will be no problem in any case.  I don't think that the `DiscreteTrajectory` use case has any relevance to what we decide to do about clamping.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC6vIxRCype9yN_57LI:b-bycfji) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you evaluate a `DiscreteTimeTrajectory` at a time other than one of its provided times (within an epsilon), then it _should_ throw -- not clamp.  It's entire purpose in life is to provide canned values, with no wiggle room.  Presumably if you're using a `DiscreteTimeTrajectory` in a motion primitive, then you've set your motion primitive timestep to exactly match the trajectory's timestep, so there will be no problem in any case.  I don't think that the `DiscreteTrajectory` use case has any relevance to what we decide to do about clamping.
</blockquote></details>

Sorry, `DiscreteTimeTrajectory` above is a proxy for "any trajectory that throws on query time outside of `[0, duration]`", not a specific "what if we had a `MotionPrimitive` with this specific trajectory type".

I agree that `DiscreteTimeTrajectory` is special, and throwing is the right answer there.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @calderpg-tri, @EricCousineau-TRI, and @hongkai-dai)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NC6womH648au3hGPoW_:b-ayt9wr) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Sorry, `DiscreteTimeTrajectory` above is a proxy for "any trajectory that throws on query time outside of `[0, duration]`", not a specific "what if we had a `MotionPrimitive` with this specific trajectory type".

I agree that `DiscreteTimeTrajectory` is special, and throwing is the right answer there.
</blockquote></details>

So if the intended use of MotionPrimitive allows for passing in trajectories that throw, then it's the job of MotionPrimitive deal with that.

I can understand the desire to try to push that logic upstream to Trajectory, but I don't see it being practical, and it's not that difficult to handle within MotionPrimitive.  One could even argue that it's _important_ for the motion primitive to explicitly handle the case of reaching its end time, rather than delegate its assumptions to others.  If it wants its final q output to always be always and exactly traj(t_final), it can implement that very directly, instead of relying on a far-away trajectory class to participate in that invariant.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17935)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[`common/trajectories/trajectory.h` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17935#-NC5pfVcCagtw1FEj2BN:-NClqtQ6EdDwPIuXBL10:b2i9zce) ([raw file](https://github.com/robotlocomotion/drake/blob/7eb8f9dd1cf28d4a74abb9e867ea0207ad8069d3/common/trajectories/trajectory.h#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So if the intended use of MotionPrimitive allows for passing in trajectories that throw, then it's the job of MotionPrimitive deal with that.

I can understand the desire to try to push that logic upstream to Trajectory, but I don't see it being practical, and it's not that difficult to handle within MotionPrimitive.  One could even argue that it's _important_ for the motion primitive to explicitly handle the case of reaching its end time, rather than delegate its assumptions to others.  If it wants its final q output to always be always and exactly traj(t_final), it can implement that very directly, instead of relying on a far-away trajectory class to participate in that invariant.
</blockquote></details>

I am very sorry that I am late to the discussion. I somehow missed this email.

I agree most of the trajectories are ill-defined outside of [start_time, end_time], with one exception. May I ask how you plan to handle zero-order hold? I can see that we have two options for t > end_time in zero order hold
1. Zap it, then the last segment of the zero order hold trajectory is only meaningful at the single time instance of end_time.
2. Allow zero_order_hold(t) = zero_order_hold(end_time) if t > end_time.

With the proposal to clamp the time, we will use option 1.

**Comment by jwnimmer-tri** [comment]
Closing as abandoned.  When the work unpauses, feel free to reopen it, or open a new PR.

**Pull request closed without merging**
