### PR TITLE
Python bindings for methods of GcsTrajectoryOptimization::Subgraph for adding generic costs and constraints.

### PR DESCRIPTION
**Pull request by cohnt**
Towards #21981. Adds python bindings to the methods introduced in #22091.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22156)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
Hi @cohnt, is this PR ready to be reviewed yet? (asking per https://drake.mit.edu/platform_reviewer_checklist.html)

**Comment by cohnt** [comment]
Yes, I need a feature reviewer. I asked in slack, but didn't get any responses yet.

**Comment by xuchenhan-tri** [comment]
I see @sadraddini lurking in this PR. Would you like to review it? If not, I'll kick this PR to Russ to review/delegate per platform reviewer checklist.

**Comment by cohnt** [comment]
Per Jeremey's comment in the Drake Developers Slack, since this is just adding python bindings, we can send this directly to platform review.

So +@xuchenhan-tri for review, please!

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a couple of comments

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-:-OBfsUFnA7n-QrkNVGB-:b-iwggwp)* status: 2 unresolved discussions

___
*[`bindings/pydrake/planning/planning_py_trajectory_optimization.cc` line 435 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-OBfrjwKCf1k2jzqtI15:-OBfrjwKCf1k2jzqtI16:b-p1xnyu) ([raw file](https://github.com/RobotLocomotion/drake/blob/466a636ee0712a2d98ddd783821e6404e9d63998/bindings/pydrake/planning/planning_py_trajectory_optimization.cc#L435)):*
> ```cpp
>                 -> const MatrixX<symbolic::Variable> {
>               return self.vertex_control_points();
>             },
> ```

What's the point of the const qualifier if we are returning a copy?

Ditto for the same pattern below.



_Suggestion:_
```cpp
            [](const GcsTrajectoryOptimization::Subgraph& self)
                -> MatrixX<symbolic::Variable> {
              return self.vertex_control_points();
            },
```
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-OBfsFH57Q3es_-NRAic:-OBfsFH57Q3es_-NRAid:b-1ik9wo) ([raw file](https://github.com/RobotLocomotion/drake/blob/466a636ee0712a2d98ddd783821e6404e9d63998/bindings/pydrake/planning/test/trajectory_optimization_test.py#L365)):*
> ```Python
>         regions.AddEdgeCost(edge_cost)
>         regions.AddEdgeConstraint(edge_constraint)
> ```

We should add some tests that exercises the keyword arguments (with and without the default arg).

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22156)* status: 2 unresolved discussions

___
*[`bindings/pydrake/planning/planning_py_trajectory_optimization.cc` line 435 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-OBfrjwKCf1k2jzqtI15:-OBgNZXq1nWcwibAjofL:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/466a636ee0712a2d98ddd783821e6404e9d63998/bindings/pydrake/planning/planning_py_trajectory_optimization.cc#L435)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What's the point of the const qualifier if we are returning a copy?

Ditto for the same pattern below.
</blockquote></details>

Done.
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-OBfsFH57Q3es_-NRAic:-OBgOMSPEoKUbixHowNb:b-fk16dd) ([raw file](https://github.com/RobotLocomotion/drake/blob/466a636ee0712a2d98ddd783821e6404e9d63998/bindings/pydrake/planning/test/trajectory_optimization_test.py#L365)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should add some tests that exercises the keyword arguments (with and without the default arg).
</blockquote></details>

Like so?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22156)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 365 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22156#-OBfsFH57Q3es_-NRAic:-OBgR05wEOfKa1wWaWCw:b-wtkc5u) ([raw file](https://github.com/RobotLocomotion/drake/blob/466a636ee0712a2d98ddd783821e6404e9d63998/bindings/pydrake/planning/test/trajectory_optimization_test.py#L365)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Like so?
</blockquote></details>

Yes, thank you!

**Pull request merged**
