### PR TITLE
added a util class to log different output ports in a diagram.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
@sherm1 for feature and platform review. thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4864)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sherm1 for both reviews

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-:-KbBKwaShA24ZBrC23pA:bolge2b)*

**Comment by sherm1** [comment]
@siyuanfeng-tri, a few platform review comments:
- I'm unclear about the motivation for this class (not skeptical, it just isn't obvious to me). I think class documentation might help. Why wouldn't someone use SignalLogger directly? Is the functionality here making up for a deficiency in SignalLogger, and if so should the improvements go there rather than in a separate class?
- This does need feature review by someone more qualified to understand its utility, how about @liangfok or @russtedrake?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/primitives/diagram_logger.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD29zC5bu2ShQcHvPT:-KbD29zC5bu2ShQcHvPU:bjxxxos) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L12)):*
> ```objc
> namespace systems {
> 
> template <typename T>
> ```

Needs class documentation. What is this for? When should I use it vs. SignalLogger? Are there performance or memory issues I should worry about? Also, needs to reference SignalLogger and explain the relationship.

---

*[drake/systems/primitives/diagram_logger.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD2R56Ie8IQW1nxVWG:-KbD2R56Ie8IQW1nxVWH:bszfutt) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L15)):*
> ```objc
> class DiagramLogger {
>  public:
>   explicit DiagramLogger(int batch_allocation_size = 1000)
> ```

Public method needs a doxygen comment. What is the significance of "batch_allocation_size"?

---

*[drake/systems/primitives/diagram_logger.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD2TquwWIeK3lYIVU1:-KbD2TquwWIeK3lYIVU2:b-spcdb8) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L18)):*
> ```objc
>     : batch_allocation_size_(batch_allocation_size) {}
>   DiagramLogger(const DiagramLogger<T>&) = delete;
>   DiagramLogger& operator=(const DiagramLogger<T>&) = delete;
> ```

Should use one of Jeremy's [new macros](https://github.com/RobotLocomotion/drake/blob/master/drake/common/drake_copyable.h), unless you are doing something custom. Here I think you want `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(DiagramLogger)`.  

---

*[drake/systems/primitives/test/CMakeLists.txt, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD22QEtGraBnINluuM:-KbD22QEtGraBnINluuN:b-tqs03k) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/CMakeLists.txt#L50)):*
> ```CMake
> 
> drake_add_cc_test(diagram_logger_test)
> target_link_libraries(diagram_logger_test drakeSystemPrimitives drakeSystemAnalysis)
> ```

BTW, linelength.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD8OWvsv04IUqzrs3I:-KbD8OWvsv04IUqzrs3J:bni3is9) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L16)):*
> ```cpp
> 
> // Adds two systems (a linear system and a gain block with gain = 0.5) to a
> // diagram, log both systems' outputs using a DiagramLogger.
> ```

BTW, please briefly document equations and expected solution.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbD797xm5Mq723ffMNt:-KbD797xm5Mq723ffMNu:b-7aor3k) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L18)):*
> ```cpp
> // diagram, log both systems' outputs using a DiagramLogger.
> GTEST_TEST(TestDiagramLogger, Test) {
>   systems::DiagramBuilder<double> builder;
> ```

BTW, should have `using std::exp;` here for ADL and `#include <cmath>` above for IWYU although it is probably doing the right thing anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-:-KbD3iispeW7xRoOgNMK:b4qojga)*

**Comment by siyuanfeng-tri** [comment]
The main motivation is to not have the main diagram building part be cluttered with a bunch of allocating and wiring loggers, which is already pretty messy for a bit more complex diagrams. Just looking at the PID controlled system, I lose track of what's going on pretty quickly. 

A step forward is to take an existing diagram and tap into subsystems' output ports and log them. I also think it would be nice to have the ability to directly tap into and log subsystem's state directly without explicitly making an output port for it. 

Adding +@russtedrake for feature review. 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-:-KbD9v3OUxcwQf0JtrsX:b-aue3mo)*

**Comment by liangfok** [comment]
+@liangfok - completed first pass; PTAL.

I can kind of see the purpose of the `DiagramLogger`. It's basically performing bookkeeping duties for organizing `SignalLogger` systems within a `Diagram`. See discussion below regarding possible re-design.

---

Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDY96Qrsr0KRu2hUwg:-KbDY96Qrsr0KRu2hUwh:b2reyj8) (no related file):*
The name `DiagramLogger` may be confusing because it sounds similar to `SignalLogger` and yet only one of them, `SignalLogger`, is actually a `System`. Also, I'm not sure about the value of specializing `DiagramLogger` to only hold the `SignalLogger` instances within a particular `Diagram`. Why not have one bookkeeping class that can manage _all_ `SignalLogger` instances in an application, even those that are in deeply nested `Diagram` objects?

Consider renaming `DiagramLogger` to be `SignalLoggerRegistry` and generalizing it to hold _all_ `SignalLogger` instances in an appliction. It could provide the following two methods:

```C++
/// Adds a SignalLogger to this registry.
///
/// @param[in] name The user-provided name of the SignalLogger. This name can be any
/// user-selectable value but must not match the name of any existing SignalLogger that
/// already exists within this registry.
///
/// @param[in] signal_logger The SignalLogger to add to this registry.
///
/// @throws std::runtime_error if a SignalLogger with name @p name already exists in
/// this registry.
template <typename T>
void AddSignalLogger(const std::string& name, const SignalLogger<T>* signal_logger);

/// Obtains a SignalLogger from this registry.
///
/// @param[in] name The name of the logger.
///
/// @return The SignalLogger within this registry that was added using name @p name.
///
/// @throws std::runtime_error if no SignalLogger with name @p name exists in this registry.
///
template <typename T>
const SignalLogger<T>* GetSignalLogger(const std::string& name) const;
```

---

*[drake/systems/primitives/diagram_logger.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDQDsQbbuvoSicUt17:-KbDQDsQbbuvoSicUt18:b-k5269j) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L21)):*
> ```objc
> 
>   /**
>    * Add a SignalLogger system to @p diagram_builder that is connected to
> ```

BTW, per style guide, "Add" should be "Adds".

---

*[drake/systems/primitives/diagram_logger.h, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDQll_DnFGv0J31VuE:-KbDQll_DnFGv0J31VuF:b1ibiut) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L25)):*
> ```objc
>    * @param trace_name Name for this logger.
>    * @param src Output source to be logged.
>    * @param diagram_builder Diagram builder
> ```

BTW, consider "the DiagramBuilder to which a SignalLogger is to be added"

---

*[drake/systems/primitives/diagram_logger.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDR06F_4NxXPlXxS3m:-KbDR06F_4NxXPlXxS3n:bqvw9rf) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L27)):*
> ```objc
>    * @param diagram_builder Diagram builder
>    * @return true if a SignalLogger is successfully added. False if
>    * @p trace_name already exists, or @p src is not vector valued.
> ```

BTW, is this return value necessary? Why not just throw an exception?

---

*[drake/systems/primitives/diagram_logger.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDU7A3URz-TeAa07Ba:-KbDU7A3URz-TeAa07Bb:btv0x6c) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L35)):*
> ```objc
>   /**
>    * Returns a const pointer to the SignalLogger whose name is @p trace_name.
>    * nullptr is returned if @p trace_name cannot be found.
> ```

BTW, consider throwing an exception if @p trace_name is not found.

---

*[drake/systems/primitives/diagram_logger.h, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDRV8PpBDMXRO33DC9:-KbDRV8PpBDMXRO33DCA:b-r98195) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/diagram_logger.h#L40)):*
> ```objc
> 
>  private:
>   int batch_allocation_size_{1000};
> ```

This member variable does not appear to be used.

---

*[drake/systems/primitives/test/CMakeLists.txt, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDUFcqi1Lw_4bKgsZx:-KbDUFcqi1Lw_4bKgsZy:b-gd2n7f) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/CMakeLists.txt#L50)):*
> ```CMake
> 
> drake_add_cc_test(diagram_logger_test)
> target_link_libraries(diagram_logger_test drakeSystemPrimitives drakeSystemAnalysis)
> ```

BTW, consider alpha sorting the dependencies.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDXMsBYadWHyUT2Ry4:-KbDWHRwUfN6usIqr2ku:btf3nmx) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L30)):*
> ```cpp
> 
>   DiagramLogger<double> loggers;
>   loggers.LogOutputPort("lin_sys", plant->get_output_port(), &builder);
> ```

BTW, should the return value of this method call be checked?

```
ASSERT_TRUE(loggers.LogOutputPort("lin_sys", plant->get_output_port(), &builder));
```

Alternatively, consider modifying `LogOutputPort()` to throw an exception upon error and verifying that no exception is thrown here:

```
ASSERT_NO_THROW(loggers.LogOutputPort("lin_sys", plant->get_output_port(), &builder));
```

(Same comment below.)

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDWIoKFHOC2nFuqqCz:-KbDWIoKFHOC2nFuqqD-:bty5ojp) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L31)):*
> ```cpp
>   DiagramLogger<double> loggers;
>   loggers.LogOutputPort("lin_sys", plant->get_output_port(), &builder);
>   loggers.LogOutputPort("gain", gain->get_output_port(), &builder);
> ```

BTW, consider defining string constants for these names.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDVxGwXFtH6x5WOPX5:-KbDVxGwXFtH6x5WOPX6:b7gqgyp) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L45)):*
> ```cpp
>   const SignalLogger<double>* logger;
>   {
>     logger = loggers.get_logger("lin_sys");
> ```

BTW, since `get_loger()` may return nullptr, shouldn't we check that `logger` is not `nullptr`?

```
ASSERT_NE(logger, nullptr);
```

Alternatively, if `get_logger()` is modified to throw an exception, consider adding the following check:

```
ASSERT_NO_THROW(logger = loggers.get_logger("lin_sys"))";
```

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDVrXwGcU_myldKK79:-KbDVrXwGcU_myldKK7A:b2u608a) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L46)):*
> ```cpp
>   {
>     logger = loggers.get_logger("lin_sys");
>     const auto& t = logger->sample_times();
> ```

BTW, consider spelling out the "auto" for increased readability.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDWnk1YmbtgrIrw0_l:-KbDWnk1YmbtgrIrw0_m:b3res49) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L55)):*
> ```cpp
>     const Eigen::MatrixXd desired_x = exp(-t.transpose().array());
> 
>     double tol = 1e-6;  // Not bad for numerical integration!
> ```

BTW, `const double`?

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDWZM9tpLvUpSUXffW:-KbDWZM9tpLvUpSUXffX:b-z6aqg6) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L60)):*
> ```cpp
> 
>   {
>     logger = loggers.get_logger("gain");
> ```

Same comment here about checking that `logger` is not nullptr.

---

*[drake/systems/primitives/test/diagram_logger_test.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-KbDWtHJo1-W3qJbc8VH:-KbDWtHJo1-W3qJbc8VI:b3res49) ([raw file](https://github.com/robotlocomotion/drake/blob/2b78a393fa71a7cdf09414e3b9ecfa73dcd0eae2/drake/systems/primitives/test/diagram_logger_test.cc#L70)):*
> ```cpp
>     const Eigen::MatrixXd desired_x = exp(-t.transpose().array());
> 
>     double tol = 1e-6;  // Not bad for numerical integration!
> ```

BTW, `const double`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-:-KbDXgtMy2AK8nlyKVoR:bfjgwin)*

**Comment by RussTedrake** [comment]
fwiw -- i think the comments you've received so far are good, and will be happy to review the next round.

---

Review status: all files reviewed at latest revision, 20 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4864#-:-Kbj7ziZWdIpphSWwnZ1:b-iz3vy5)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request closed without merging**
