### PR TITLE
[multibody] Add unit inertia for capsule

### LINKED ISSUE #16342: `UnitInertia::SolidCapsule(...)`
We support the Capsule shape, but don't offer the helper method for computing it's unit inertia.  I need it for the mujoco parser.
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_unit_inertia.html

I hope this is a quick request.  It should be simple!  @sherm1 -- could you please delegate so we can knock it out?

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Fixes #16342

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@mitiguy for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtAOKAU-OLVXMV_n4bF:b-sj99ot)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@xuchenhan-tri   Got it.  I'll look at it shortly.  I am reviewing another PR right now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtAiHRwDBL43Fp6y2FH:b-ga6dbi)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@xuchenhan-tri   I made a few comments.  I'll restart tomorrow morning.  I also need to check the formulas.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtBdYn88pwM3Y2Q8pop:b2ki6f5)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy and @xuchenhan-tri)

___
*[multibody/tree/unit_inertia.h, line 304 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtAv2nf9-5TTPo8Sbdd:-MtAv2nf9-5TTPo8Sbde:b-4ts0ji) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.h#L304)):*
> ```objc
>   }
> 
>   /// Computes the unit inertia for a unit-mass capsule C of uniform density,
> ```

BTW  This is so nit-picky, so feel free to ignore this.

Computes the unit inertia for a uniform density unit-mass capsule C whose axis of revolution is along the z-axis.
___
*[multibody/tree/unit_inertia.h, line 307 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtAvwXu2PrkWwvOUIUB:-MtAvwXu2PrkWwvOUIUC:b4nwx28) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.h#L307)):*
> ```objc
>   /// which has its axis of revolution along the z-axis.
>   /// @param[in] r The radius of the the cylinder/half-sphere part of the
>   /// capsule, it must be non-negative.
> ```

Please clarify what is meant by the length of the capsule.
Perhaps, you could change this to:

@param[in] L The length of the cylindrical part of the capsule.

Since you have already specified the exception below, I do not think you need to say "it must be non-negative".
___
*[multibody/tree/test/unit_inertia_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtBdvuGAibeJ412_m2a:-MtBdvuGAibeJ412_m2b:b5btbjj) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L286)):*
> ```cpp
>                               I_capsule_expected.get_products(), kEpsilon));
> }
> ```

BTW   Also consider testing a degenerate capsule that appears like a long thin cylindrical rod.  If  r << L, then the ratio of the inertia of the capsule to the inertia of the cylinder should be a 1 + smallNumber, where smallNumber is 0.01 (or so).

**Review by xuchenhan-tri — COMMENTED** [review]
I addressed the existing comments. PTAL, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtFGDrCEltM-CiSYyP4:b-wg5dmp)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy and @param)

___
*[multibody/tree/unit_inertia.h, line 304 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtAv2nf9-5TTPo8Sbdd:-MtFAq90-A60aEi7JSfC:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.h#L304)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW  This is so nit-picky, so feel free to ignore this.

Computes the unit inertia for a uniform density unit-mass capsule C whose axis of revolution is along the z-axis.
</blockquote></details>

Done, thanks.
___
*[multibody/tree/unit_inertia.h, line 307 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtAvwXu2PrkWwvOUIUB:-MtFB0V0-CVFgeMBoxWH:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.h#L307)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Please clarify what is meant by the length of the capsule.
Perhaps, you could change this to:

@param[in] L The length of the cylindrical part of the capsule.

Since you have already specified the exception below, I do not think you need to say "it must be non-negative".
</blockquote></details>

Done, thanks.
___
*[multibody/tree/test/unit_inertia_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtBdvuGAibeJ412_m2a:-MtFFgTKApGxf6IGX9af:biwijhd) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L286)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW   Also consider testing a degenerate capsule that appears like a long thin cylindrical rod.  If  r << L, then the ratio of the inertia of the capsule to the inertia of the cylinder should be a 1 + smallNumber, where smallNumber is 0.01 (or so).
</blockquote></details>

Good catch! I didn't consider the r==0 case which would have caused a division by 0. 
PTAL at the changes.

**Review by mitiguy — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357)* status: 5 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/tree/unit_inertia.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGcViE-AAwcyiam0oS:-MtGcViE-AAwcyiam0oT:b8sblwu) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.cc#L20)):*
> ```cpp
>   // Shift the inertia (of the lower half sphere) from about the center of the
>   // sphere to the center of the capsule. Notice that the inertia of the other
>   // half-sphere is the same.
> ```

Consider replacing the line below with this.  
I_half_sphere.ShiftToThenAwayFromCenterOfMassInPlace(
      mass_half_sphere, p_HoHcm_C, p_HcmCcm_C);
___
*[multibody/tree/unit_inertia.cc, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGZCb39XKclJfjsdHl:-MtGZCb39XKclJfjsdHm:bi8gj2j) ([raw file](https://github.com/robotlocomotion/drake/blob/802e078bc67ad3e9b3acaaaafa903353a4d3ccda/multibody/tree/unit_inertia.cc#L10)):*
> ```cpp
>   DRAKE_THROW_UNLESS(r >= 0);
>   DRAKE_THROW_UNLESS(L >= 0);
>   // The capsule degenerates into a thin rod if the radius is zero.
> ```

It would help to provide a reason why this degenerate case is handled where L = 0 is not.  Consider something like:

// A special case is required for r = 0 because r = 0 corresponds to a zero volume capsule.  The assumption of density per unit volume needs to change to density per unit length (or else the code below has a divide-by-zero error).  No special case for L = 0 is needed because the capsule degenerates into a sphere (non-zero volume). 
___
*[multibody/tree/unit_inertia.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGa_hQD9g6V_RrFWMo:-MtGa_hQD9g6V_RrFWMp:b-wccx4a) ([raw file](https://github.com/robotlocomotion/drake/blob/802e078bc67ad3e9b3acaaaafa903353a4d3ccda/multibody/tree/unit_inertia.cc#L21)):*
> ```cpp
>   // of the sphere.
>   RotationalInertia<T> I_half_sphere =
>       mass_half_sphere * UnitInertia<T>::SolidSphere(r);
> ```

More details would be helpful here.
Consider something like

// Denoting the half-sphere as H and point Ho as the geometrically significant point at the center of the connection between the half-sphere and the cylinder, the position vector from Ho to Hcm (H's center of mass), expressed-in the capsule frame C as:

const Vector3<T> p_HoHcm_C (0, 0, -3.0 * r / 8.0);

// The position vector from Hcm to CCm (the capsule's center of mass) is
const Vector3<T> p_HcmCcm_C(0, 0, 3.0 * r / 8.0 + 0.5 * L);
___
*[multibody/tree/test/unit_inertia_test.cc, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGd_P3CV8828rQfMVP:-MtGd_P4Bupv3bCNA22r:b-341sqv) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L270)):*
> ```cpp
>   const RotationalInertia<double> I_capsule = mass_capsule * G_capsule;
> 
>   // Calculate inertia of capsule with method 2.
> ```

I like this analytical expression and your typesetting (very nice).  It would be helpful to provide some kind of hint as to from whence it comes.
___
*[multibody/tree/test/unit_inertia_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtBdvuGAibeJ412_m2a:-MtGeFJ-6qK52wrwH69l:b90iao4) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L286)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good catch! I didn't consider the r==0 case which would have caused a division by 0. 
PTAL at the changes.
</blockquote></details>

I like the updated code.  Perhaps I am missing it, but could you create a test such as 
GTEST_TEST(UnitInertia, SolidCapsuleDegenerateIntoThinRod) {

**Review by mitiguy — COMMENTED** [review]
@xuchenhan-tri   Ready for another round.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtGq_fq86n9tu5lnFfu:bsf26v8)* status: 5 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357)* status: 5 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

___
*[multibody/tree/unit_inertia.cc, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGcViE-AAwcyiam0oS:-MtJf_Kl43XUyB1W7RS4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/unit_inertia.cc#L20)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Consider replacing the line below with this.  
I_half_sphere.ShiftToThenAwayFromCenterOfMassInPlace(
      mass_half_sphere, p_HoHcm_C, p_HcmCcm_C);

</blockquote></details>

Done.
___
*[multibody/tree/unit_inertia.cc, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGZCb39XKclJfjsdHl:-MtJfFSZCUrU7h8LqZ0k:b-3cbce) ([raw file](https://github.com/robotlocomotion/drake/blob/802e078bc67ad3e9b3acaaaafa903353a4d3ccda/multibody/tree/unit_inertia.cc#L10)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

It would help to provide a reason why this degenerate case is handled where L = 0 is not.  Consider something like:

// A special case is required for r = 0 because r = 0 corresponds to a zero volume capsule.  The assumption of density per unit volume needs to change to density per unit length (or else the code below has a divide-by-zero error).  No special case for L = 0 is needed because the capsule degenerates into a sphere (non-zero volume). 
</blockquote></details>

Done. I slightly reworded.
___
*[multibody/tree/unit_inertia.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGa_hQD9g6V_RrFWMo:-MtJfY9e02dwFPd7KGfO:b7jum90) ([raw file](https://github.com/robotlocomotion/drake/blob/802e078bc67ad3e9b3acaaaafa903353a4d3ccda/multibody/tree/unit_inertia.cc#L21)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

More details would be helpful here.
Consider something like

// Denoting the half-sphere as H and point Ho as the geometrically significant point at the center of the connection between the half-sphere and the cylinder, the position vector from Ho to Hcm (H's center of mass), expressed-in the capsule frame C as:

const Vector3<T> p_HoHcm_C (0, 0, -3.0 * r / 8.0);

// The position vector from Hcm to CCm (the capsule's center of mass) is
const Vector3<T> p_HcmCcm_C(0, 0, 3.0 * r / 8.0 + 0.5 * L);


</blockquote></details>

Done. Much clearer, thanks!
___
*[multibody/tree/test/unit_inertia_test.cc, line 270 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtGd_P3CV8828rQfMVP:-MtJpMGl5_gAYyrQUIJL:b-x4udh5) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L270)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I like this analytical expression and your typesetting (very nice).  It would be helpful to provide some kind of hint as to from whence it comes.
</blockquote></details>

Done, PTAL, thanks.
___
*[multibody/tree/test/unit_inertia_test.cc, line 286 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtBdvuGAibeJ412_m2a:-MtJfe6NDL_2NKXbgik3:b7uri5o) ([raw file](https://github.com/robotlocomotion/drake/blob/54a8fc7aa7d1254f83b54ffe866fff3c6cccbdaa/multibody/tree/test/unit_inertia_test.cc#L286)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I like the updated code.  Perhaps I am missing it, but could you create a test such as 
GTEST_TEST(UnitInertia, SolidCapsuleDegenerateIntoThinRod) {
</blockquote></details>

There is already such a test 10 lines below.

**Review by xuchenhan-tri — COMMENTED** [review]
I addressed the existing comments. PTAL, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtJpRFA5H7wEtveadhH:b-wg5dmp)* status: 5 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@xuchenhan-tri   Looks good.  It seems near completion.  PTAL.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtKF6kaDu93jkaFdHCt:bvial6j)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/tree/test/unit_inertia_test.cc, line 274 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKDB_sED_yqVAAbHiQ:-MtKDB_sED_yqVAAbHiR:b-e9hqjh) ([raw file](https://github.com/robotlocomotion/drake/blob/7e520e53ae513da2af7a4a89fcac78ec0a9d516b/multibody/tree/test/unit_inertia_test.cc#L274)):*
> ```cpp
>   //
>   // Suppose m₁ is the mass of the cylinder part and m₂ is the mass of the
>   // cylinder part and the spherical part (sum of the two half-spheres)
> ```

I may be confused.

The previous wording was:
 m₁ and m₂ are the mass of the cylinder part and
the spherical part (sum of the two half-spheres) respectively.

The new wording seems conceptually difference
... and m₂ is the mass of the cylinder part and the spherical part (sum of the two half-spheres)
___
*[multibody/tree/test/unit_inertia_test.cc, line 283 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKDaCB6gts9BbA5nJo:-MtKDaCB6gts9BbA5nJp:b-pzhmj1) ([raw file](https://github.com/robotlocomotion/drake/blob/7e520e53ae513da2af7a4a89fcac78ec0a9d516b/multibody/tree/test/unit_inertia_test.cc#L283)):*
> ```cpp
>   // Is = diag(Is_xx, Is_yy, Is_zz).
>   // Is_xx = Is_yy = m₂(2r²/5 + L²/4 + 3Lr/8), which is calculated by shifting
>   // each half of the sphere twice (first from the center of the sphere to COM
> ```

I am confused by "the center of the sphere".  I thought there was only half-spheres.  Is this point Ho, the geometrically relevant point at the connection between the cylinder and half-sphere?  Perhaps it would be good to introduce H for half-sphere, point Ho, point Hcm, cylinder C, CCm, etc.

Since there is so many center of masses here (each of the spheres, the cylinder, and the capsule), it may help to replace COM with either "the capsule's center of mass" or "the half-sphere's center of mass" -- depending on what you intended.

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtKH5wo6IXT5bk_kosg:b-i35568)* status: 2 unresolved discussions, LGTM missing from assignees mitiguy,EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @mitiguy)

___
*[multibody/tree/test/unit_inertia_test.cc, line 274 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKDB_sED_yqVAAbHiQ:-MtKGxdC5MSbQskNBv3t:b-a3d620) ([raw file](https://github.com/robotlocomotion/drake/blob/7e520e53ae513da2af7a4a89fcac78ec0a9d516b/multibody/tree/test/unit_inertia_test.cc#L274)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I may be confused.

The previous wording was:
 m₁ and m₂ are the mass of the cylinder part and
the spherical part (sum of the two half-spheres) respectively.

The new wording seems conceptually difference
... and m₂ is the mass of the cylinder part and the spherical part (sum of the two half-spheres)



</blockquote></details>

Done, this is a typo from moving text around. I fixed it.
___
*[multibody/tree/test/unit_inertia_test.cc, line 283 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKDaCB6gts9BbA5nJo:-MtKGrCWBfqUcHH_wyhM:b-cspqw1) ([raw file](https://github.com/robotlocomotion/drake/blob/7e520e53ae513da2af7a4a89fcac78ec0a9d516b/multibody/tree/test/unit_inertia_test.cc#L283)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I am confused by "the center of the sphere".  I thought there was only half-spheres.  Is this point Ho, the geometrically relevant point at the connection between the cylinder and half-sphere?  Perhaps it would be good to introduce H for half-sphere, point Ho, point Hcm, cylinder C, CCm, etc.

Since there is so many center of masses here (each of the spheres, the cylinder, and the capsule), it may help to replace COM with either "the capsule's center of mass" or "the half-sphere's center of mass" -- depending on what you intended.  
</blockquote></details>

I reworded to mimic the wording in the .cc file.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with nit on unrelated whitespace change

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtKJ_7b4jI2pugEY8m5:b-n35ypl)* status: 3 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @mitiguy and @xuchenhan-tri)

___
*[multibody/tree/test/unit_inertia_test.cc, line 140 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKJ2oqC7OCX1XJBglV:-MtKJ2oqC7OCX1XJBglW:b-xijcqy) ([raw file](https://github.com/robotlocomotion/drake/blob/93e38f5e0b96efa03c47ca8ce3ef0bfca53e819d/multibody/tree/test/unit_inertia_test.cc#L140)):*
> ```cpp
> 
> // Tests the static method to obtain the unit inertia of a solid sphere.
> GTEST_TEST(UnitInertia, SolidSphere) {
> ```

nit Unclear why unrelated whitespace changes were made.

Consider reverting changes, making a separate PR, or mentioning whitespace change in commit message.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @EricCousineau-TRI and @mitiguy)

___
*[multibody/tree/test/unit_inertia_test.cc, line 140 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKJ2oqC7OCX1XJBglV:-MtKLkBD8-7oRtgz3TFO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93e38f5e0b96efa03c47ca8ce3ef0bfca53e819d/multibody/tree/test/unit_inertia_test.cc#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ah crap. I accidentally hit the formatter in vscode that reformatted globally. Working.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @mitiguy)

___
*[multibody/tree/test/unit_inertia_test.cc, line 140 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16357#-MtKJ2oqC7OCX1XJBglV:-MtKMemE4ymFTU3P15PL:b-igip50) ([raw file](https://github.com/robotlocomotion/drake/blob/93e38f5e0b96efa03c47ca8ce3ef0bfca53e819d/multibody/tree/test/unit_inertia_test.cc#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK No worries, and thanks!

**Review by RussTedrake — COMMENTED** [review]
@mitiguy -- this is a high priority PR.  it's blocking me and just waiting on your review.  can you please help finish it?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtPBCK48SJxHPxkBBuQ:b70dd4n)* status: 2 unresolved discussions, LGTM missing from assignee mitiguy (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
:lgtm: 
I think the best thing is for me to :LGTM it, and push another PR thereafter to address my concern that on of the underlying tests uses an analytical solution with numbers that are not immediately obvious.  I confirmed that they worked, but they need more documentation.  I am almost finished with that, but no need to hold this up.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16357#-:-MtPjwg51PRnuvNGXPAG:bdilchs)* status: 1 unresolved discussion (waiting on @mitiguy)

**Pull request merged**
