### PR TITLE
setup: Update recommended Bazel version to 3.4

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13743)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
FYI We don't need macOS builds to show this works -- they've already been running since the release, e.g. [mac-mojave-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Mojave%20Unprovisioned/job/mac-mojave-unprovisioned-clang-bazel-nightly-release/377) last night.

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for sole review please; feel free to merge once the AMI updates are lined up.

**Comment by BetsyMcPhail** [comment]
@jamiesnape Ubuntu and Mac images have been updated.

**Pull request merged**
