### PR TITLE
call_python_client: Make termination behavior more non-FIFO friendly.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is a quick fix for #7830.

NOTE: I'd prefer not to spend time on refactoring `call_python_full_test.sh` to Python right now (#7703), as that'd involve at least another 2-3 hours, blocking a relatively simple fix.
However, if the changes are incomprehensible, I can consider it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7831)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug, please.
@drake-jenkins-bit mac-sierra-clang-bazel-experimental-everything-debug, please.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything-debug, please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything-debug, please.

**Comment by EricCousineau-TRI** [comment]
+@jadecastro for feature review, please.
+@sammy-tri for platform review, please.

Main emphasis is for the functionality change in Python, and the high-level details of the Bash script - given prior comment, nothing is needed in depth for the internals of the Bash script.
If it gets too time consuming / confusing, please let me know.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7831#-:-L3VW5AE1ce8rVQzxIqr:btwib1w)*

**Comment by jadecastro** [comment]
The functionality works for me -- tested on Ubuntu. :lgtm: 

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7831#-:-L3Z6wc8vZUhkRGOJvC3:bguuydv)*

**Comment by jadecastro** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7831)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7831#-:-L3cszFwbywKqqISy1_b:bnfp4nl)*

**Pull request merged**
