### PR TITLE
Update plan runner to start moving from the last commanded position.

### PR DESCRIPTION
**Pull request by sammy-tri**
(this seems to help with steady state errors in actual vs. commanded
positions when starting a new plan).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4863)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbAzuIFRShjZi5ECpQC:b-psw9ws)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbC2cFWRvMiunk50u6G:bnfp4nl)*

**Comment by sammy-tri** [comment]
Thanks!  +@sherm1 for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbC2wseeIA6u2EmG5FW:b-wky47i)*

**Comment by sherm1** [comment]
A couple of BTWs below including a question. Also, I'm wondering if there is a possible unit test for this new functionality? If so, please consider adding one. However, platform :lgtm: once you have considered.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCHZR_RYi8xgBT4N7G:-KbCHZR_RYi8xgBT4N7H:b-hbu4eg) ([raw file](https://github.com/robotlocomotion/drake/blob/a848fea5a003f97c4f60a79b6b3f70923b12e713/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L129)):*
> ```cpp
>           // Always start moving from the position which we're
>           // currently commanding.
>           knots[i](name_to_idx[state.joint_name[j]], 0) =
> ```

BTW, `knots[0]` would be clearer, I think.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCHgSQxlPPzyjk5dUt:-KbCHgSQxlPPzyjk5dUu:b-g727aj) ([raw file](https://github.com/robotlocomotion/drake/blob/a848fea5a003f97c4f60a79b6b3f70923b12e713/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L130)):*
> ```cpp
>           // currently commanding.
>           knots[i](name_to_idx[state.joint_name[j]], 0) =
>               iiwa_status_.joint_position_commanded[j];
> ```

BTW, if this is the first time through, does this "commanded" value contain something meaningful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbCHzJPyLbVLr1PY6jx:b-2m1yof)*

**Comment by sammy-tri** [comment]
A unit test would be tricky since it's a standalone program which communicates using LCM.  I could use the drake mocking framework and make the build a bit more elaborate to build the tested code separately from the output executable, but I'm going to defer for now.

If we get to the point where this gets much bigger, I think it probably would be a good idea to split it up and accept the complexity...   but I suspect if the controller gets much more complex we'll be scrapping this code and going to torque control anyway.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 129 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCHZR_RYi8xgBT4N7G:-KbCOnB-2GAQvtQ4GFZ-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a848fea5a003f97c4f60a79b6b3f70923b12e713/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L129)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, `knots[0]` would be clearer, I think.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCHgSQxlPPzyjk5dUt:-KbCP5lhNc0E_3SmKBjH:bs1pt9h) ([raw file](https://github.com/robotlocomotion/drake/blob/a848fea5a003f97c4f60a79b6b3f70923b12e713/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L130)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, if this is the first time through, does this "commanded" value contain something meaningful?
</blockquote></details>

I was in the process of explaining why it was a really hard to trigger startup race condition when I realized it's actually an easy to trigger startup race if your robot/simulator hasn't started sending status messages yet.  Fixed by adding an assertion and code to ignore plans which arrive before status messages.  (unlikely under normal operation because the status messages come in at 200hz).

FWIW, before this change the program would have crashed anyway if this happened due to the assert in Run() which I replaced with a check that the status was received.

Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbCU99gEptoIyrPTeKc:b-7kj02k)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 136 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCZ5-7EZLzRE1Qa8WP:-KbCZ5-8wNb3mc24TzTT:bfrrej4) ([raw file](https://github.com/robotlocomotion/drake/blob/4985a62ce2899afec9cf2bee53d654c722e50161/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L136)):*
> ```cpp
>           // Always start moving from the position which we're
>           // currently commanding.
>           DRAKE_ASSERT(iiwa_status_.utime != -1);
> ```

BTW, do you want to make this a `DRAKE_DEMAND()` so it is always in place? Doesn't look like it would be a performance burden!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc, line 136 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-KbCZ5-7EZLzRE1Qa8WP:-KbCcciZT_9_M72DgsiH:b-z50nbk) ([raw file](https://github.com/robotlocomotion/drake/blob/4985a62ce2899afec9cf2bee53d654c722e50161/drake/examples/kuka_iiwa_arm/kuka_plan_runner.cc#L136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, do you want to make this a `DRAKE_DEMAND()` so it is always in place? Doesn't look like it would be a performance burden!
</blockquote></details>

Done.  (agreed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863)*

**Comment by sherm1** [comment]
:lebtm: (looks even better to me!) :lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4863#-:-KbCiXFKrKbqh-rtl7dZ:b5joigi)*

**Pull request merged**
