### PR TITLE
Updates scrip for multi-car demo

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR just updates some of the paths in `run_demo_multi_car.sh` given now we are compiling into `drake-distro/build`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2884)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for platform (/feature) review.
+@maddog-tri for feature review since you worked on this file.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2884#-:-KNEKedRtmXgba1EwFL4:-1703964411)*

**Comment by jwnimmer-tri** [comment]
Paths seem to match my local build.  I suspect there's more wrongness still in the directory for other scripts and docs, but this is a strict improvement.

:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2884#-:-KNEtbU-31V85jRcWiNg:-517132788)*

**Comment by amcastro-tri** [comment]
@jwnimmer-tri: you were right. The simple car demo paths were wrong also. I just pushed the fix for that also. PTAL.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2884#-:-KNHjBP2RslsN5D5lmUm:-1597374901)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2884)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2884#-:-KNI14qRsBugXOUNpche:1417088721)*

**Pull request merged**
