### PR TITLE
Handle /path/to/*.so libs from pkg-config

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Some `*.pc` files are odd (probably buggy) by declaring the `--libs` to be, e.g., `/usr/lib/x86_64-linux-gnu/libopencv_core.so`.  We rewrite those to be just, e.g., `-lopencv_core` so that they can make it to the `cc_library` in at least some usable form.

We could try to add the literal `*.so`'s to srcs instead (after adding appropriate symlinking), but at least for opencv the `-lfoo` flags are already (also) in the `--libs` output, so this is at least consistent now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7778)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for all review per schedule, please.  Let me know if you'd also like me to assign a build-system-related feature reviewer.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/workspace/pkg_config.bzl, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7778#-L33k9Of5K9HfTtSLHv9:-L33k9Of5K9HfTtSLHvA:bs5otp) ([raw file](https://github.com/robotlocomotion/drake/blob/069c9bba1ea61025cde311c0862e1150452890ac/tools/workspace/pkg_config.bzl#L67)):*
> ```Python
>             possible_libdirs = [
>                 "/usr/lib",
>                 "/usr/lib/x86_64-linux-gnu",
> ```

This seems very linux-specific.  How does it correspond to mac behavior?

---

*[tools/workspace/pkg_config.bzl, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7778#-L33kmhMKNmybWObTWBZ:-L33kmhMKNmybWObTWB_:b-vc6kqv) ([raw file](https://github.com/robotlocomotion/drake/blob/069c9bba1ea61025cde311c0862e1150452890ac/tools/workspace/pkg_config.bzl#L73)):*
> ```Python
>                 prefix = dir + "/lib"
>                 if linkopt.startswith(prefix):
>                     name = linkopt[len(prefix):-3]
> ```

FYI this would be clearer with a comment or other indication that the magic number `-3` is `-len(".so")`

---

*[tools/workspace/pkg_config.bzl, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7778#-L33l7P6-rj8tgKroury:-L33l7P6-rj8tgKrourz:b1xfvme) ([raw file](https://github.com/robotlocomotion/drake/blob/069c9bba1ea61025cde311c0862e1150452890ac/tools/workspace/pkg_config.bzl#L76)):*
> ```Python
>                     if "/" not in name:
>                         linkopts[i] = "-l" + name
>                         matched = True
> ```

FYI Instead of this whole `matched` mechanism, you could updated `linkopt`.   Then the handling of switch args below would do the job for you.  Author's discretion as to readability, but I think the control flow simplification might be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7778#-:-L33mQc1VxBFm454J22t:bnfp4nl)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7778)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 67 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7778#-L33k9Of5K9HfTtSLHv9:-L33n3K_aIt7IF7rU-JU:b57tp5) ([raw file](https://github.com/robotlocomotion/drake/blob/069c9bba1ea61025cde311c0862e1150452890ac/tools/workspace/pkg_config.bzl#L67)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems very linux-specific.  How does it correspond to mac behavior?
</blockquote></details>

Done (with comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7778)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7778)*

**Comment by jwnimmer-tri** [comment]
macOS builds passed:
- https://drake-jenkins.csail.mit.edu/view/Mac%20Sierra/job/mac-sierra-clang-bazel-experimental/82/
- https://drake-jenkins.csail.mit.edu/view/Mac%20High%20Sierra/job/mac-highsierra-clang-bazel-experimental/54/

**Pull request merged**
