### PR TITLE
Propagate CMAKE_EXPORT_NO_PACKAGE_REGISTRY to external projects

### PR DESCRIPTION
**Pull request by jamiesnape**
We already set `CMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON` in the parent project.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6115)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Um... I don't see the actual propagation? (Did you forget to commit changes to `cmake/externals.cmake`?)

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/drake/pull/6115/files#diff-86448322b77ea7f85f7b89bb357268bfR159

**Comment by mwoehlke-kitware** [comment]
:lgtm:

Curious; I swear the first time I looked at this there was only one file changed...

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6115#-:-KkHnEPXqWalS4FwapOi:bfmr018)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6115#-:-KkHp4F_26pluzbmMRvi:bnfp4nl)*

**Pull request merged**
