### PR TITLE
Set shard_count in monolithic_p&p_system_test.

### PR DESCRIPTION
**Pull request by avalenzu**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7606)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@jwnimmer-tri for feature review
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0KmpdwFdqW4kqYJxPj:bgg7rma)*

**Comment by jwnimmer-tri** [comment]
Pending any edits, we should then also test on macOS CI, just in case there's something weird there.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0Knj2EKxSAUj3AThl1:-L0Knj2EKxSAUj3AThl2:bxwe698) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L70)):*
> ```Python
>     # this test into shard_count separate pieces which will be exectuted in
>     # parallel, subject to the availability of resources. There are 31 test
>     # points in this test.
> ```

BTW Is there any easy way to report the count, so that others can help maintain this constant?  Like a googletest flag to list the cases?

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KnalSehIUOO9seJP5:-L0KnalUOFm1qsOkjCU-:b-yy43vd) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569bbe1165322f0e1b66d63759d492e6c028a8/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc#L239)):*
> ```cpp
>                                           std::make_tuple(1, 3),  // Scenario 4
>                                           std::make_tuple(2,
>                                                           0)));  // Scenario 5;
> ```

Probably the commit message should say why these are removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0Kns6PxzqWUkrBYd0n:bhccsnq)*

**Comment by soonho-tri** [comment]
+@soonho-tri for platform-review & local mac test.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0KoHU4Ho0o0hi3wAcc:b-i3pjan)*

**Comment by soonho-tri** [comment]
It's `dev` code and does not require platform. But I'll do it anyway..

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0KoOguXzJKRJnBZSr1:b7mk6ut)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KulZ7dzHRsTWDZGvs:-L0KulZ7dzHRsTWDZGvt:b-3hn8ez) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L71)):*
> ```Python
>     # parallel, subject to the availability of resources. There are 31 test
>     # points in this test.
>     shard_count = 31,
> ```

FYI, CI fails and asks for running `bazel-bin/tools/lint/buildifier examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel`.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KuudVBa_z_htgghIS:-L0KuudVBa_z_htgghIT:b-4c1zp6) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L72)):*
> ```Python
>     # points in this test.
>     shard_count = 31,
>     # TODO(avalenzu) The gtest_filter argument below is required because the
> ```

Could you check if this TODO can be removed with this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by soonho-tri** [comment]
I've checked that it works on mac machines. In `macsim` (12-core), I've observed about 10x speed up.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LFARp0XUdg87PRQPI:b-1bemoz)*

**Comment by avalenzu** [comment]
Huzzah!!!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LHgvHucNBRBjlNqgD:b16zf9k)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LJVGK7ukWNaCV7YJB:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by avalenzu** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0Knj2EKxSAUj3AThl1:-L0LT6ZhwvaRXMiIwXwG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is there any easy way to report the count, so that others can help maintain this constant?  Like a googletest flag to list the cases?
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KulZ7dzHRsTWDZGvs:-L0LT6B1BnlY9g4QMYdM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L71)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, CI fails and asks for running `bazel-bin/tools/lint/buildifier examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel`.
</blockquote></details>

Done.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel, line 72 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KuudVBa_z_htgghIS:-L0LUKoPSLdCAHgFCpJg:b3yg4ha) ([raw file](https://github.com/robotlocomotion/drake/blob/69b41d4f4d0417f4fefe4fe1a0bdbd2e1ac02bf0/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel#L72)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you check if this TODO can be removed with this PR?
</blockquote></details>

I've taken this out in the newest revision. If it fails in debug mode I'll put it back in.

---

*[examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc, line 239 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-L0KnalSehIUOO9seJP5:-L0LT83rQhjmzs8vgAr6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f3569bbe1165322f0e1b66d63759d492e6c028a8/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc#L239)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Probably the commit message should say why these are removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LUW0rnKNl4niv0-tM:b1dzxh3)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LVL7UIeDJ_LhCBiNm:b-s794vx)*

**Comment by avalenzu** [comment]
Manually started debug builds for:
- [linux-xenial-clang-bazel-experimental-everything](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-xenial-clang-bazel-experimental-everything/3510/)
- [mac-highsierra-clang-bazel-experimental-everything](https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-highsierra-clang-bazel-experimental-everything/) - Job (#6) not yet started.
- [linux-xenial-gcc-bazel-experimental-everything](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-xenial-gcc-bazel-experimental-everything/) - Job (#39) not yet started.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LWDgr5vV9Rz1gcIyJ:bssxcj0)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0LYAfqyxQhgL4gi3nu:bnfp4nl)*

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0Lc9XJczZ5CrTHkAc1:b-rz6899)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by jwnimmer-tri** [comment]
The `linux-xenial-gcc-bazel-experimental-everything` failed with `//examples/kuka_iiwa_arm/dev/monolithic_pick_and_place:monolithic_pick_and_place_system_test TIMEOUT in 1 out of 31 in 60.1s` which suggests that each shard is individually limited to the timeout.  So I guess we want "medium" here now.

The mac failure looks like a unrelated flakes.

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0N7QwSHWzmyz7LoKZ3:b1dzxh3)*

**Comment by avalenzu** [comment]
Spun up debug jobs to test with `size="medium"`:
- [linux-xenial-clang-bazel-experimental-everything (#3528)](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-xenial-clang-bazel-experimental-everything/3528)
- [linux-xenial-gcc-bazel-experimental-everything (#42)](https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-xenial-gcc-bazel-experimental-everything/42)
- [mac-sierra-clang-bazel-experimental-everything (#32)](https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-sierra-clang-bazel-experimental-everything/32)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606#-:-L0N8M4Tt9i6l3PjyXkt:b-adjwi9)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7606)*

**Comment by soonho-tri** [comment]
`mac-sierra-clang-bazel-experimental-everything` fails because of `//common/proto:call_python_full_test (TIMEOUT)` and `//common:find_loaded_library_test  (FAILED)`. I've checked that neither of them is caused by this PR.

**Pull request merged**
