### PR TITLE
[workspace] Upgrade bazelisk to latest release v1.19.0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #20594.

----
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20631)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
```
[8:22:59 AM]  To update Drake's vendored copy of bazelisk:
[8:22:59 AM]  $ cd drake
[8:22:59 AM]  $ bazel fetch @bazelisk//:LICENSE
[8:22:59 AM]  $ cp bazel-drake/external/bazelisk/LICENSE      bazel-drake/external/bazelisk/bazelisk.py      third_party/com_github_bazelbuild_bazelisk/
```

**Comment by mwoehlke-kitware** [comment]
```
cp: cannot stat 'bazel-drake/external/bazelisk/LICENSE': No such file or directory
cp: cannot stat 'bazel-drake/external/bazelisk/bazelisk.py': No such file or directory
```

**Comment by mwoehlke-kitware** [comment]
...and the instructions belong in `repository.bzl`, and in `upgrade_advice` more specifically, not hidden in test output. I updated the PR accordingly. However, as noted above, the instructions aren't working for me; `bazel-drake/external/bazelisk` does not exist.

**Comment by mwoehlke-kitware** [comment]
BTW, let me know if you'd prefer for me to change the test failure to *only* say "mind the upgrade_advice" if you don't like the duplication; I'd be happy to do that.

**Comment by jwnimmer-tri** [comment]
> ... if you don't like the duplication ...

I'm happy to defer either way to you.  Whatever way you think works best.

In terms of making the instructions actually work, if you like you can open a ticket for me to circle back to that later, if you like.  There is a `bazel_skylib` helper that I just learned about that I think can make it a lot smoother.

**Comment by jwnimmer-tri** [comment]
> cp: cannot stat 'bazel-drake/external/bazelisk/LICENSE': No such file or directory
> cp: cannot stat 'bazel-drake/external/bazelisk/bazelisk.py': No such file or directory

Please try to figure out what's going wrong, and either work around it or fix it.  In the extreme, you can download the files by hand and update our vendored copy.

Once Jenkins is passing, I'll start my review.

**Comment by mwoehlke-kitware** [comment]
I have no idea what's wrong; it's beyond my Bazel knowledge. What I know is what I said previously; `bazel fetch @bazelisk//:LICENSE` did not result in `bazel-drake/external/bazelisk` existing.

FYI:
```
$ find -L . -name LICENSE | grep bazelisk
./bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/external/bazelisk/LICENSE
./bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/third_party/com_github_bazelbuild_bazelisk/LICENSE
./bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/bazelisk/LICENSE
./bazel-drake/external/bazelisk/LICENSE
./bazel-drake/bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/external/bazelisk/LICENSE
./bazel-drake/bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/third_party/com_github_bazelbuild_bazelisk/LICENSE
./bazel-drake/bazel-out/k8-opt/bin/tools/workspace/bazelisk/py/lint_test.runfiles/bazelisk/LICENSE
./bazel-drake/third_party/com_github_bazelbuild_bazelisk/LICENSE
./bazel-bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/external/bazelisk/LICENSE
./bazel-bin/tools/workspace/bazelisk/py/lint_test.runfiles/drake/third_party/com_github_bazelbuild_bazelisk/LICENSE
./bazel-bin/tools/workspace/bazelisk/py/lint_test.runfiles/bazelisk/LICENSE
./third_party/com_github_bazelbuild_bazelisk/LICENSE
```

Should I change the instructions to refer to one of those?

**Comment by mwoehlke-kitware** [comment]
Additionally... I cloned bazelbuild/bazelisk@c7c6c19799ff408c48bdce6b7557217ad0050b17 (i.e. [v1.19.0](https://github.com/bazelbuild/bazelisk/releases/tag/v1.19.0)) and copied `bazelisk.py` (`LICENSE` has not changed) from there to `third_party/com_github_bazelbuild_bazelisk/`, but I still get the same test failure.

**Comment by mwoehlke-kitware** [comment]
Oh, I see, there's a patch that needs to be manually applied...

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for review (both?) please.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) +(release notes: fix) 

> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20631#-:-NlcoIWq2hUQQNPKGPyA:b-29nyiz)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
