### PR TITLE
Allocate extra memory to copy our data pointer into.

### LINKED ISSUE #3226: SNOPT-related valgrind issues
The linux-clang-nightly-memcheck-valgrind build is flagging a lot of SNOPT interactions as memory misuse (bad pointers and uninitialized accesses).  Some of this may be real; much is likely a result of SNOPT's interface and implementation being awful in their use of memory.

All of these issues should be addressed (where real) or suppressed (where, more likely, spurious).

See, eg: https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=88438

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #3226

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3434)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@ggould-tri for feature review, +@jwnimmer-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3434#-:-KRZSNYZcuc_EZAWiNwD:b5s68wd)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/snopt_solver.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3434#-KRZW6jG1CoZYqckZOov:-KRZW6jHJyiw7u_NMmzh:bd800uo) ([raw file](https://github.com/robotlocomotion/drake/blob/ffad360512f38a50e59c886e2a49d99396752051/drake/solvers/snopt_solver.cc#L121)):*
> ```cpp
>     // Set the "maxcu" value to tell snopt to reserve one 8-char entry of user
>     // workspace.  We are then allowed to use cw(snopt_mincw+1:maxcu), as
>     // expressed in Fortran array slicing.   Use the space to pass our problem
> ```

BTW: whitespace (three spaces after period).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3434#-:-KRZWXfwQ4UWBp_--jKm:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/snopt_solver.cc, line 121 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3434#-KRZW6jG1CoZYqckZOov:-KRZYGuxgA1-3bQTJ_a3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffad360512f38a50e59c886e2a49d99396752051/drake/solvers/snopt_solver.cc#L121)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW: whitespace (three spaces after period).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3434)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3434)*

**Comment by jwnimmer-tri** [comment]
Sorry, I keep coming back to this and then getting distracted.

It's a strict improvement, but that's not saying much.
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3434#-:-KRZbSGdTpjXlH82W-9R:b-yh9otu)*

**Pull request merged**
