### PR TITLE
[bazel] Tweak drake_py.bzl for clarity

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This improves clarity in several senses:

1. Cleans up comments to developers.
2. Changes names to be more suggestive of what the rule is (i.e., "disable_test" actually redirects users, so it is a "redirect_test".
3. Reformats the redirection error message so that the bazel labels are easier to see and select.

Without the format change, the message could look like (depending on window width):
```
ERROR: Please use '//bindings/pydrake/systems:py/planar_scenegraph_visualiz
er_test'; the label '//bindings/pydrake/systems:planar_scenegraph_visualize
r_test' has been removed.
```

With the change it looks like this:

```
ERROR: Please use
    //bindings/pydrake/systems:py/planar_scenegraph_visualizer_test
  The label
    //bindings/pydrake/systems:planar_scenegraph_visualizer_test
  has been removed.
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17874)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri for feature review.

(I'm educating myself on the build infastructure and had difficulty grokking this file. This is my attempt to make it clearer for future readers. If you feel it's frivolous, let me know and we'll close it.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17874#-:-NBTNkQ7DUdJNCwiKDag:b-51ps0e)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, two small nits, but regardless this is strict improvement for the experience (and for the learning ;)
Also happy to serve as single reviewer if you want.

Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17874#-:-NBTcst31w26rArhRstC:bqe5wob)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`tools/skylark/drake_py.bzl` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17874#-NBTc2g0AvUAbZKpAUqn:-NBTc2g0AvUAbZKpAUqo:bol4snt) ([raw file](https://github.com/robotlocomotion/drake/blob/95fb73556caf0f6077d076e2a1f6093cf6cc1e7a/tools/skylark/drake_py.bzl#L26)):*
> ```Starlark
>     )
>     content = """#!/bin/bash
> echo "ERROR: Please use\n    {good_target}\n  The label\n    {bad_target}\n" \
> ```

nit (pre-exsting) Any chance you'd be able to change those to change `{bad_target} does not exist` vs. `{bad_target} has been removed`?

"has been removed" has been true for >4 years since #8724
(feel free to dismiss)
___
*[`tools/skylark/drake_py.bzl` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17874#-NBTbtSQB4dIWaSlmlWb:-NBTbtSQB4dIWaSlmlWc:b-deffrq) ([raw file](https://github.com/robotlocomotion/drake/blob/95fb73556caf0f6077d076e2a1f6093cf6cc1e7a/tools/skylark/drake_py.bzl#L86)):*
> ```Starlark
>         package_prefix = "//" + native.package_name() + ":"
> 
>         # N.B. Make sure that a test (visible to both bazel run and bazel test)
> ```

nit Consider keeping backticks `` `bazel run` and `bazel test` `` to denote them as compound code-like nouns.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17874#-:-NBTj7Gj0BofteOPcQvR:bdl0rty)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`tools/skylark/drake_py.bzl` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17874#-NBTc2g0AvUAbZKpAUqn:-NBTiuoF36jrJsjnjU1f:bbtvtj0) ([raw file](https://github.com/robotlocomotion/drake/blob/95fb73556caf0f6077d076e2a1f6093cf6cc1e7a/tools/skylark/drake_py.bzl#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (pre-exsting) Any chance you'd be able to change those to change `{bad_target} does not exist` vs. `{bad_target} has been removed`?

"has been removed" has been true for >4 years since #8724
(feel free to dismiss)
</blockquote></details>

Done

I'm glad you suggested that. I toyed with it, but wasn't quite willing to take that last step.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17874)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`tools/skylark/drake_py.bzl` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17874#-NBTc2g0AvUAbZKpAUqn:-NBTnvg13sJpvdDCKxxW:b-1bjphp) ([raw file](https://github.com/robotlocomotion/drake/blob/95fb73556caf0f6077d076e2a1f6093cf6cc1e7a/tools/skylark/drake_py.bzl#L26)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

I'm glad you suggested that. I toyed with it, but wasn't quite willing to take that last step.
</blockquote></details>

thanks!!!

**Pull request merged**
