### PR TITLE
Mesh filename publishing

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by patmarion** [comment]
In this pull request, mesh filenames are always published with absolute paths.  Previously, mesh filenames were published as relative paths or absolute paths depending on whether the urdf command line argument was given as a relative or absolute path.

This pull request also converts prius.urdf to use package:// syntax.  This makes lcm logs with DRAKE_VIEWER_LOAD messages portable between computers and verifies that drake-visualizer is handling package:// correctly.

Note, drake-visualizer imports pydrake in order to call pydrake.getDrakePath().  The pydrake module prints a warning, perhaps @rdeits could silence that.

**Comment by patmarion** [comment]
This pull request triggers new tests failures when running urdf parsers that do not support the package:// syntax I added to prius.urdf.  I guess these are not using RigidBodyTreeURDF c++ parser?  I could remove package:// from prius.urdf, but maybe it's better to fix the missing package support?

**Comment by RussTedrake** [comment]
awesome. thanks! but i suspect this will conflict badly with my open PR (which
has just been waiting for a code review)

On Tue, Feb 16, 2016 at 5:49 PM, Pat Marion <notifications@github.com> wrote:

--------------------------------------------------------------------------------

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/RobotLocomotion/drake/pull/1721
[https://github.com/RobotLocomotion/drake/pull/1721]

COMMIT SUMMARY
 * when computing resolved paths convert relative paths to absolute
 * publish package:// urls if the urdf specifies them
 * convert prius.urdf to use package syntax for the mesh filename
 * update director external

FILE CHANGES
 * M CMakeLists.txt
   [https://github.com/RobotLocomotion/drake/pull/1721/files#diff-0] (2)
 * A drake/examples/Cars/prius/package.xml
   [https://github.com/RobotLocomotion/drake/pull/1721/files#diff-1] (0)
 * M drake/examples/Cars/prius/prius.urdf
   [https://github.com/RobotLocomotion/drake/pull/1721/files#diff-2] (4)
 * M drake/systems/plants/BotVisualizer.h
   [https://github.com/RobotLocomotion/drake/pull/1721/files#diff-3] (9)
 * M drake/systems/plants/RigidBodyTreeURDF.cpp
   [https://github.com/RobotLocomotion/drake/pull/1721/files#diff-4] (10)

PATCH LINKS:
 * https://github.com/RobotLocomotion/drake/pull/1721.patch
   [https://github.com/RobotLocomotion/drake/pull/1721.patch]
 * https://github.com/RobotLocomotion/drake/pull/1721.diff
   [https://github.com/RobotLocomotion/drake/pull/1721.diff]

**Comment by patmarion** [comment]
Ok no problem.  I will rebase this after #1711 is merged.  No rush to merge this one, I will reopen after rebase.

**Pull request closed without merging**
