### PR TITLE
Exclude VTK headers from rgbd_renderer.h

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This PR is to avoid spreading the need of including VTK headers by making use of pimpl pattern in `RgbdRenderer`.

Relates: #7258

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7308)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@EricCousineau-TRI feature review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-Kwv6TXiA9t9GcN80LGf:be8wqbj)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/sensors/rgbd_renderer.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-Kx9E62Tk-2H0GtAiXt2:-Kx9E62Tk-2H0GtAiXt3:ba573y1) ([raw file](https://github.com/robotlocomotion/drake/blob/d87e2f4f3cac365b805b79a406066e3766d03ce3/drake/systems/sensors/rgbd_renderer.cc#L70)):*
> ```cpp
> struct ModuleInitVtkRenderingOpenGL2 {
>   ModuleInitVtkRenderingOpenGL2() {
> #if VTK_MAJOR_VERSION >= 6
> ```

BTW You can remove the `#if VTK_MAJOR_VERSION >= 6 ... #endif` wrappers here and above since we no longer support VTK 5.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308)*

**Comment by kunimatsu-tri** [comment]
*[drake/systems/sensors/rgbd_renderer.cc, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-Kx9E62Tk-2H0GtAiXt2:-Kx9qWcWUp3Cu_bgDId9:b-6x6jk7) ([raw file](https://github.com/robotlocomotion/drake/blob/d87e2f4f3cac365b805b79a406066e3766d03ce3/drake/systems/sensors/rgbd_renderer.cc#L70)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW You can remove the `#if VTK_MAJOR_VERSION >= 6 ... #endif` wrappers here and above since we no longer support VTK 5.
</blockquote></details>

Thanks!

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308)*

**Comment by EricCousineau-TRI** [comment]
Did your most recent push incorporate non-`master` code?
I'm seeing new additions for the Jaco arm here...

---

Reviewed 2 of 2 files at r2.
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/rgbd_renderer.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDpw7skyZOqyrHBmzL:-KxDpw7trKt84yE38lRe:bsnep6r) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L36)):*
> ```cpp
> #include "drake/systems/sensors/vtk_util.h"
> 
> VTK_AUTOINIT_DECLARE(vtkRenderingOpenGL2)
> ```

BTW Can you add a comment connecting this to the `VTK_AUTOINIT_CONSTRUCT(...)` statement below?

---

*[drake/systems/sensors/rgbd_renderer.cc, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDuWeS1CaejORh0_gZ:-KxDuWeTzPkRV3XVCSgw:bpmjlvh) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L90)):*
> ```cpp
> }
> ```

FYI Stray blank newline?

---

*[drake/systems/sensors/rgbd_renderer.cc, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDv1GoJjQpcxb1HPI_:-KxDv1GoJjQpcxb1HPIa:b-enm96g) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L146)):*
> ```cpp
>   float CheckRangeAndConvertToMeters(float z_buffer_value) const;
> 
>   const int width_;
> ```

BTW Given this usage of `const`, can you use the no-copy-no-move-no-assign macro?
(Well, keeping copying if you believe you need it.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxDvkfJKuqh4MxYZ-b2:b-40gqmv)*

**Comment by kunimatsu-tri** [comment]
Sorry for the confusion. Yup, so to clean up commit history, I was doing `git push --force`.  It seems ok now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxE7HMZKeiHkQI-8Jig:b-c9pr38)*

**Comment by EricCousineau-TRI** [comment]
Thanks!
:lgtm: with minor BTWs

---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxE9C-xd8r42DvA86KY:b-od10dm)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308)*

**Comment by kunimatsu-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/rgbd_renderer.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDpw7skyZOqyrHBmzL:-KxECBZLtP6XBsxPYVFH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you add a comment connecting this to the `VTK_AUTOINIT_CONSTRUCT(...)` statement below?
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_renderer.cc, line 90 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDuWeS1CaejORh0_gZ:-KxE9qwfOL0ijwLsTK9I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L90)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

FYI Stray blank newline?
</blockquote></details>

Done.

---

*[drake/systems/sensors/rgbd_renderer.cc, line 146 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-KxDv1GoJjQpcxb1HPI_:-KxEA2I5x-4Gn8oA7ANk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a76b5d2b81f603994825bfa49fc5eaac1ac8638b/drake/systems/sensors/rgbd_renderer.cc#L146)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Given this usage of `const`, can you use the no-copy-no-move-no-assign macro?
(Well, keeping copying if you believe you need it.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308)*

**Comment by kunimatsu-tri** [comment]
Thanks @EricCousineau-TRI for the feature review.


+@sammy-tri platform review please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxECwhyMJ1CXOhnQNPT:b-1m327o)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxET_vOW7h0vFOlE6be:bsf2vkf)*

**Comment by kunimatsu-tri** [comment]
Thanks @sammy-tri for your review!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7308#-:-KxEW6exZ5DcIOXd_2Tt:b1pczaw)*

**Pull request merged**
