### PR TITLE
GetSubsystemContext / State is now recursive.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5740)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@david-german-tri for feature review. thanks

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-:-Kh-ucSkC2SMSNMetkoz:b-ytzdcz)*

**Comment by david-german-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 783 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh3C_mJCI2ftf2gL9pl:-Kh3C_mJCI2ftf2gL9pm:bgm9ujt) ([raw file](https://github.com/robotlocomotion/drake/blob/80eb07328b0ae641e1b17c547b4df0424e4ca5cc/drake/systems/framework/diagram.h#L783)):*
> ```objc
>     DRAKE_DEMAND(derived_ptr != nullptr);
> 
>     // target_system is my direct child.
> ```

BTW what if `target_system` is me myself?  (This can only happen at the top of the recursion tree, so it's an edge case, but still.  The design I suggest below would fix that.)

---

*[drake/systems/framework/diagram.h, line 790 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh3Aabz6dv5btdQAoWr:-Kh3Aabz6dv5btdQAoWs:b-1sje3v) ([raw file](https://github.com/robotlocomotion/drake/blob/80eb07328b0ae641e1b17c547b4df0424e4ca5cc/drake/systems/framework/diagram.h#L790)):*
> ```objc
> 
>     for (const auto& pair : sorted_systems_map_) {
>       const Diagram<T>* child = dynamic_cast<const Diagram<T>*>(pair.first);
> ```

The style guide says this recursion should bottom out based on dispatch, not RTTI.

https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_

 i.e. make this a `virtual` method on System, with a default implementation that calls does the `get` if it's the target system, and returns nullptr otherwise.

Of course, if it's `virtual` it can't be a template method; you'll need three.  (Really, two, since you can just delete `GetMutableSubsystemState` if you like.  It only has one user.)  You could promote the existing ones to `System` instead of adding new signatures.  The names won't be ideal but I'm willing to live with it.

This incidentally eliminates the need for the lambda argument, which is clever but a little obscure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-:-Kh3CyuKWblf1OZcrmNg:b-s794vx)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 783 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh3C_mJCI2ftf2gL9pl:-Kh4mJbeSMxtKRYY5ihn:b8uvmsk) ([raw file](https://github.com/robotlocomotion/drake/blob/80eb07328b0ae641e1b17c547b4df0424e4ca5cc/drake/systems/framework/diagram.h#L783)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW what if `target_system` is me myself?  (This can only happen at the top of the recursion tree, so it's an edge case, but still.  The design I suggest below would fix that.)
</blockquote></details>

handled in the DoGetFoo 

---

*[drake/systems/framework/diagram.h, line 790 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh3Aabz6dv5btdQAoWr:-Kh4mK4oK43WXDoJJSc4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/80eb07328b0ae641e1b17c547b4df0424e4ca5cc/drake/systems/framework/diagram.h#L790)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

The style guide says this recursion should bottom out based on dispatch, not RTTI.

https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_

 i.e. make this a `virtual` method on System, with a default implementation that calls does the `get` if it's the target system, and returns nullptr otherwise.

Of course, if it's `virtual` it can't be a template method; you'll need three.  (Really, two, since you can just delete `GetMutableSubsystemState` if you like.  It only has one user.)  You could promote the existing ones to `System` instead of adding new signatures.  The names won't be ideal but I'm willing to live with it.

This incidentally eliminates the need for the lambda argument, which is clever but a little obscure.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by david-german-tri** [comment]
:lgtm: aside from some BTWs and one commented-out test

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 601 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gJkPv6ZRqls_KTV0:-Kh8gJkPv6ZRqls_KTV1:bqgnrfm) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L601)):*
> ```objc
>       const System<T>* target_system, Context<T>* context) const final {
>     auto target_context =
>         System<T>::DoGetMutableTargetSystemContext(target_system, context);
> ```

BTW (meta x4) this is fine, but IMO it would be clearer and less verbose just to check `this == target_system`.  Up to you.

---

*[drake/systems/framework/diagram.h, line 626 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8fjuW_q5Nqoc7mvpx:-Kh8fjuXxMof0kT0IPZZ:b5addrt) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L626)):*
> ```objc
>   }
> 
>   /// Returns a pointer to mutable state if @p target_system is a sub system
> ```

BTW, do you actually want these two?  If not, I'll delete them in a follow-up PR.

---

*[drake/systems/framework/diagram.h, line 840 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gdLNy7NfykMG4DM5:-Kh8gdLNy7NfykMG4DM6:b-4fy5i8) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L840)):*
> ```objc
>   /// @p recursive_getter A member function of System that returns sub context
>   /// or state. Should be one of the four functions listed above.
>   /// @p get_child_stuff A member function of DiagramContext of DiagramState
> ```

BTW s/of/or?

---

*[drake/systems/framework/system.h, line 666 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8fMdXigRdJ59b8ZaI:-Kh8fMdYsX_IzhfKL2m1:bl2cbqy) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/system.h#L666)):*
> should really be protected

While I agree in spirit, C++ doesn't, so I'm not sure this comment is helpful.  Consider either elaborating or deleting.

---

*[drake/systems/framework/test/diagram_test.cc, line 235 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gtytPy-ml0vorbTr:-Kh8gtytPy-ml0vorbTs:bb7r2f0) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/test/diagram_test.cc#L235)):*
> ```cpp
> // Tests that both variants of GetMutableSubsystemState do what they say on
> // the tin.
> /*
> ```

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-:-Kh8hz52fkZGxXM6TJ3H:b6gtdzv)*

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri for platform review. thanks!

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 601 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gJkPv6ZRqls_KTV0:-Kh8iZUVD3KXNo3LOF1w:b-o0iwyu) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L601)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW (meta x4) this is fine, but IMO it would be clearer and less verbose just to check `this == target_system`.  Up to you.
</blockquote></details>

oh! i thought you'd be happier this way. i like this == target_system much better for the same reason. 

---

*[drake/systems/framework/diagram.h, line 626 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8fjuW_q5Nqoc7mvpx:-Kh8j5FTK0YDYZvuTJt3:bmo1ozu) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L626)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, do you actually want these two?  If not, I'll delete them in a follow-up PR.
</blockquote></details>

it sort of is useful. Suppose somebody really wants to override Diagrams' SetDefaultState. i think it makes life easier. there is one in /home/sfeng/code/drake4/drake/examples/Quadrotor/run_quadrotor_dynamics.cc
why do you want to rm these? 

---

*[drake/systems/framework/diagram.h, line 840 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gdLNy7NfykMG4DM5:-Kh8kHxRdODqhnSE8hE8:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L840)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW s/of/or?
</blockquote></details>

Done. 

---

*[drake/systems/framework/system.h, line 666 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8fMdXigRdJ59b8ZaI:-Kh8kk-LYNmimzQZQAkD:b-8e68qq) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/system.h#L666)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> should really be protected

While I agree in spirit, C++ doesn't, so I'm not sure this comment is helpful.  Consider either elaborating or deleting.
</blockquote></details>

added a bit more. 

---

*[drake/systems/framework/test/diagram_test.cc, line 235 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8gtytPy-ml0vorbTr:-Kh8kszh3LBZFu-Er9Ci:b-mfo3fp) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/test/diagram_test.cc#L235)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

why?
</blockquote></details>

opps. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-:-Kh8lb2M4vy4g0EXjXVI:buvypxa)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 626 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-Kh8fjuW_q5Nqoc7mvpx:-Kh8w-nfVMooifXEB_EB:b2a6kys) ([raw file](https://github.com/robotlocomotion/drake/blob/a87f145eaf5ecec3f0a2981c01e7a901c22aa9d0/drake/systems/framework/diagram.h#L626)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

it sort of is useful. Suppose somebody really wants to override Diagrams' SetDefaultState. i think it makes life easier. there is one in /home/sfeng/code/drake4/drake/examples/Quadrotor/run_quadrotor_dynamics.cc
why do you want to rm these? 
</blockquote></details>

Only because they're kind of bulky, not very popular (so far), and don't provide much syntactic sweetness over and above getting the context.  I don't feel too strongly about it; if you want to keep them we can keep them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 828 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNIRHiTk5qd1jusz8s:-KhNIRHiTk5qd1jusz8t:b-hhc5y8) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L828)):*
> ```objc
>   /// DoGetTargetSystemContext(), DoGetMutableTargetSystemState(), and
>   /// DoGetTargetSystemState().
>   /// @p target_system The sub system of interest.
> ```

FYI, this and the following `@p`s should be replaced with `@param`.

---

*[drake/systems/framework/diagram.h, line 845 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNOwZPSctkontn_73A:-KhNOwZQQ3VzPLYO2zk0:b-194juy) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L845)):*
> ```objc
>                                  BaseStuffPtr)>
>           recursive_getter,
>       std::function<BaseStuffPtr(DerivedStuffPtr, int)> get_child_stuff) const {
> ```

Can we say that we have the following invariant here?
```c++
typeid(my_stuff) == typeid(BaseStuffPtr)
```
That is, the dynamic type of `my_stuff` is always actually `BaseStuffPtr`. At least, this is the case for all use cases so far.

If so, we can do the following to avoid `dynamic_cast`:

```c++
    static_assert(std::is_convertible<DerivedStuffPtr, BaseStuffPtr>::value,
                  "DerivedStuffPtr is not convertible to BaseStuffPtr.");
    DerivedStuffPtr my_stuff_as_derived =
        static_cast<DerivedStuffPtr>(my_stuff);
    // DRAKE_DEMAND(my_stuff_as_derived != nullptr); <- remove this.
```

---

*[drake/systems/framework/diagram.h, line 850 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNPgx_ignD0INBep29:-KhNPgx_ignD0INBep2A:bet90b4) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L850)):*
> ```objc
>     DRAKE_DEMAND(my_stuff_as_derived != nullptr);
>     DRAKE_DEMAND(target_system != nullptr);
>     DRAKE_DEMAND(target_system != this);
> ```

BTW, consider documenting this precondition (i.e. `@pre ...`).

---

*[drake/systems/framework/diagram.h, line 854 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNPowXMaIVl4qYCNZz:-KhNPowXMaIVl4qYCN_-:b-6pkswt) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L854)):*
> ```objc
>     int index = 0;
>     for (const System<T>* child : sorted_systems_) {
>       BaseStuffPtr child_stuff = get_child_stuff(my_stuff_as_derived, index);
> ```

BTW, this and the following definitions can be marked as `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 845 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNOwZPSctkontn_73A:-KhNQFqonjSzOdbK7_wb:bk4d7ny) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L845)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Can we say that we have the following invariant here?
```c++
typeid(my_stuff) == typeid(BaseStuffPtr)
```
That is, the dynamic type of `my_stuff` is always actually `BaseStuffPtr`. At least, this is the case for all use cases so far.

If so, we can do the following to avoid `dynamic_cast`:

```c++
    static_assert(std::is_convertible<DerivedStuffPtr, BaseStuffPtr>::value,
                  "DerivedStuffPtr is not convertible to BaseStuffPtr.");
    DerivedStuffPtr my_stuff_as_derived =
        static_cast<DerivedStuffPtr>(my_stuff);
    // DRAKE_DEMAND(my_stuff_as_derived != nullptr); <- remove this.
```
</blockquote></details>

FYI, `std::is_convertible` in `<type_traits>` header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 845 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNOwZPSctkontn_73A:-KhNRnbbcKWoWEXD5-CL:bkcz9kw) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L845)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, `std::is_convertible` in `<type_traits>` header.
</blockquote></details>

Oops nevermind. I got confused. Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 828 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNIRHiTk5qd1jusz8s:-KhNT0odc50rYHXxA62b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L828)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this and the following `@p`s should be replaced with `@param`.
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 850 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNPgx_ignD0INBep29:-KhNTOJOeUe5RAfs4VNT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L850)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, consider documenting this precondition (i.e. `@pre ...`).
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 854 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-KhNPowXMaIVl4qYCNZz:-KhNTuT3bwjWkR0fnPiO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/efe235151e8ad33dffc7946808e9dc39b4480cd4/drake/systems/framework/diagram.h#L854)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this and the following definitions can be marked as `const`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5740#-:-KhNWAIBvL51Jpr8GMFh:bnfp4nl)*

**Pull request merged**
