### PR TITLE
Improve code and tests for UnitInertia for a capsule.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MtkBfJ8B4a_KPfvCcsA:b-lo2zh8)* status: LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +(release notes: none) 
:lgtm: Beautiful! Thanks for the clean up.
+@sammy-tri for platform review per rotation please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MtnQ_7lEIVPQxYPDWXJ:b-vre8z5)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy, @sammy-tri, and @sherm1)

___
*[multibody/tree/unit_inertia.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtnVJAS7aRtDx31Rlri:-MtnhI435VGEa-dhd-j5:bkpg9nl) ([raw file](https://github.com/robotlocomotion/drake/blob/018a0fa660fb8485e4fcffb5480b12d329e7a70e/multibody/tree/unit_inertia.cc#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this note seems wrong -- isn't it diag(Ih_xx, Ih_yy, Ih_zz) ? Those aren't all the same. (The code below looks right though)
</blockquote></details>

This is the inertia about Ho whereas diag(Ih_xx, Ih_yy, Ih_zz) is the inertia about Hcm.

**Review by sammy-tri — COMMENTED** [review]
No issues from me for platform review, waiting on discussion of the outstanding item.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-Mto6Run1xF4h0p4XpDP:bqyd25n)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/unit_inertia.cc, line 51 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtoGPOqAu0eKYXQ6lyy:-MtoGPOqAu0eKYXQ6lyz:bgnj0wk) ([raw file](https://github.com/robotlocomotion/drake/blob/72dfc0a69c57331ec1e488a539792d94b3ded99f/multibody/tree/unit_inertia.cc#L51)):*
> ```cpp
>   // Ih_xx = Ih_yy = 83/320 mh r²      From [Kane, Figure A23, pg. 369].
>   // Ih_zz = 2/5 mh r²                 From [Kane, Figure A23, pg. 369].
>   // Pegagogical note: H's inertia matrix about Ho (as compared with about Hcm)
> ```

nit, s/Pegagogical/Pedagogical

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
All good now!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MtoJM_FAvf9QpWBRxNb:b4ta47e)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/unit_inertia.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtnVJAS7aRtDx31Rlri:-MtoJ9W987B1idtyHlx5:bcr5s2o) ([raw file](https://github.com/robotlocomotion/drake/blob/018a0fa660fb8485e4fcffb5480b12d329e7a70e/multibody/tree/unit_inertia.cc#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is the inertia about Ho whereas diag(Ih_xx, Ih_yy, Ih_zz) is the inertia about Hcm.
</blockquote></details>

Got it, thanks!

**Review by mitiguy — COMMENTED** [review]
@sammy-tri   After passing CI, think should be ready for you.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-Mtoci2_C01eBtV7ZqxZ:bi3mh1c)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/tree/unit_inertia.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtnVJAS7aRtDx31Rlri:-Mtnjw1hEqOwP4G3nhnk:b2bgr6b) ([raw file](https://github.com/robotlocomotion/drake/blob/018a0fa660fb8485e4fcffb5480b12d329e7a70e/multibody/tree/unit_inertia.cc#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is the inertia about Ho whereas diag(Ih_xx, Ih_yy, Ih_zz) is the inertia about Hcm.
</blockquote></details>

I'll add clarification as suggested by Xuchen. 
___
*[multibody/tree/unit_inertia.cc, line 51 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtoGPOqAu0eKYXQ6lyy:-MtocH1e-mN56lWmCsYv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/72dfc0a69c57331ec1e488a539792d94b3ded99f/multibody/tree/unit_inertia.cc#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, s/Pegagogical/Pedagogical
</blockquote></details>

Done.
___
*[multibody/tree/test/unit_inertia_test.cc, line 312 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16401#-MtnWubHD_Q3tpCwrh03:-MtnlFfnENYfZPj8b6vD:b1u818k) ([raw file](https://github.com/robotlocomotion/drake/blob/018a0fa660fb8485e4fcffb5480b12d329e7a70e/multibody/tree/test/unit_inertia_test.cc#L312)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the method called "Calculation 2" in this test looks simpler and more efficient than the one implemented in SolidCapsule() above. Why not use this as the main approach rather than the more complicated one?
</blockquote></details>

FYI: I rearranged the results on the updated algorithm in unit_inertia.cc so it is factored on mh and mc to save a few more flops.  It was significantly more efficient than its predecessor and appears slightly better than the Calculation 2 algorithm in the test (depending on compiler optimizations).

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@sammy-tri PTAL

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MtsqPr-9aNkxyZLrBzD:bel6l0h)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MttPo5d0E7ckttmTZ9A:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16401#-:-MttPrk10y2Jf8SPRH2J:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),xuchenhan-tri (waiting on @mitiguy)

**Pull request merged**
