### PR TITLE
Lock down the MPLBACKEND setting for a few demo programs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14702. See #17438 for the big picture.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review, please.

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake @EricCousineau-TRI FYI

**Review by svenevs — COMMENTED** [review]
This :lgtm: with really only small nits about explicitly saving to `.png` if you are going to assert that.  Since `MPLBACKEND` gets overwritten I don't think it will ever be different, but since the file extension can be specified I think it's best to do so.

+@sherm1 for platform review please.  Context: `bazel test` sets `MPLBACKEND=Template` which disables all plotting functionality, the changes in this PR make it so that plotting is _actually_ being tested.  However, ubuntu is configured in a way where by default it tries to use `TkAgg` even though `python3-tk` is not a hard requirement of the `python3-matplotlib` package -- we seek to remove tk as a drake dependency.  The `Agg` backend [is builtin to matplotlib](https://matplotlib.org/stable/users/explain/backends.html#the-builtin-backends) whereas `TkAgg` is officially an "add-on". 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437#-:-N5CGgFF-9z6trESzfq8:b3ozj16)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[`examples/van_der_pol/plot_limit_cycle.py` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CEm4z1g07TNxjUUmj:-N5CEm4z1g07TNxjUUmk:by2inip) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/examples/van_der_pol/plot_limit_cycle.py#L5)):*
> ```Python
> # Users should feel free to use a different back-end in their own code.
> import os
> os.environ['MPLBACKEND'] = 'Agg'  # noqa
> ```

BTW, this seems fine to me (`Agg` can be relied upon in the absence of graphical backends), but this does explicitly override things if a user is doing `bazel run` and they have their own environment setup to use a different plotting backend.  I don't think we should worry about this, but if we do care it would be something like

```py
import os
if 'TEST_TMPDIR' in os.environ or 'MPLBACKEND' not in os.environ:
    os.environ['MPLBACKEND'] = 'Agg'
```

I don't think it is worth changing though, just pointing out you'd overwrite in the event of `bazel run`.  That said, the likelihood of anyone even ever noticing is very small.
___
*[`examples/van_der_pol/plot_limit_cycle.py` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CDJqb3n3vpR_i3AcJ:-N5CDJqb3n3vpR_i3AcK:byoxwf8) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/examples/van_der_pol/plot_limit_cycle.py#L22)):*
> ```Python
> ax.set_ylabel('qdot')
> 
> plt.savefig('plot_limit_cycle')
> ```

nit: be explicit, `plt.savefig('plot_limit_cycle.png')`
___
*[`bindings/pydrake/math_example.py` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CDSv0AW4EKukWn1US:-N5CDSv0AW4EKukWn1UT:bln2z9) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/bindings/pydrake/math_example.py#L42)):*
> ```Python
> ax.set_ylabel('y')
> 
> plt.savefig('math_example')
> ```

nit: be explicit, `plt.savefig('math_example.png')`
___
*[`bindings/pydrake/systems/drawing_graphviz_example.py` line 39 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CE_DZ0QmemKi38Z0S:-N5CE_DZ0QmemKi38Z0T:bwoa0o5) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/bindings/pydrake/systems/drawing_graphviz_example.py#L39)):*
> ```Python
> Parser(plant=cart_pole).AddModelFromFile(file_name)
> 
> plt.figure(figsize=(11, 8.5), dpi=300)
> ```

Minor, why does this example get an explicit figure size but the others do not?
___
*[`bindings/pydrake/systems/drawing_graphviz_example.py` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CDXFzCR0RV6ywSV9w:-N5CDXG-2LgNNMdevZ-z:b-sj5x0v) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/bindings/pydrake/systems/drawing_graphviz_example.py#L41)):*
> ```Python
> plt.figure(figsize=(11, 8.5), dpi=300)
> plot_graphviz(cart_pole.GetTopologyGraphvizString())
> plt.savefig('cart_pole_topology')
> ```

nit: be explicit, `plt.savefig('cart_pole_topology.png')`
___
*[`bindings/pydrake/systems/drawing_graphviz_example.py` line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CD_jX-WdlnHT8PpUQ:-N5CD_jX-WdlnHT8PpUR:b-6phxq5) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/bindings/pydrake/systems/drawing_graphviz_example.py#L62)):*
> ```Python
> plt.figure(figsize=(11, 8.5), dpi=300)
> plot_system_graphviz(diagram, max_depth=2)
> plt.savefig('drawing_graphviz_example')
> ```

nit: be explicit, `plt.savefig('drawing_graphviz_example.png')`

**Review by sherm1 — COMMENTED** [review]
These work fine on my Puget.
Platform :lgtm: pending resolution of feature review comments

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437#-:-N5C_RX01IN5By71bS9C:bbhrjfw)* status: 5 unresolved discussions (waiting on @jwnimmer-tri and @svenevs)

___
*[`common/proto/call_python_client.py` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CWdrq4tT2hsDFA5L8:-N5CWdrq4tT2hsDFA5L9:bcxbagb) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/common/proto/call_python_client.py#L187)):*
> ```Python
>     from mpl_toolkits.mplot3d import Axes3D
>     import matplotlib
>     # If the pyplot import fails, try `sudo apt install python3-tk`.
> ```

BTW I'm not sure to whom this comment is addressed. It seems at odds with my (limited) understanding of the overall purpose being to prevent this from failing due to tk not being installed? Can you clarify?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437)* status: 1 unresolved discussion (waiting on @sherm1 and @svenevs)

___
*[`common/proto/call_python_client.py` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CWdrq4tT2hsDFA5L8:-N5CbZBo9u0KHjHcxoaa:bdrti2s) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/common/proto/call_python_client.py#L187)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm not sure to whom this comment is addressed. It seems at odds with my (limited) understanding of the overall purpose being to prevent this from failing due to tk not being installed? Can you clarify?
</blockquote></details>

Done.

(Coming back here a second time, I also found the verb mood here problematic.  Instead, I've replaced it with some improved error handling.)
___
*[`examples/van_der_pol/plot_limit_cycle.py` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CEm4z1g07TNxjUUmj:-N5CbkOT1qrK1nuznDQY:bb7m3ed) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/examples/van_der_pol/plot_limit_cycle.py#L5)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

BTW, this seems fine to me (`Agg` can be relied upon in the absence of graphical backends), but this does explicitly override things if a user is doing `bazel run` and they have their own environment setup to use a different plotting backend.  I don't think we should worry about this, but if we do care it would be something like

```py
import os
if 'TEST_TMPDIR' in os.environ or 'MPLBACKEND' not in os.environ:
    os.environ['MPLBACKEND'] = 'Agg'
```

I don't think it is worth changing though, just pointing out you'd overwrite in the event of `bazel run`.  That said, the likelihood of anyone even ever noticing is very small.
</blockquote></details>

OK I think I'm going to err on the side of less complexity to maintain / reason about.  If the user wants to try a different backend, they can hack this file.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),svenevs (waiting on @svenevs)

___
*[`common/proto/call_python_client.py` line 187 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17437#-N5CWdrq4tT2hsDFA5L8:-N5ClCni1HApUxGH2Oa0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f902f63e8288879c9d74f68beb758461884c54e5/common/proto/call_python_client.py#L187)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Officially this statement `On Ubuntu when using the default pyplot configuration of MPLBACKEND=TkAgg you must 'sudo apt install python3-tk'` is not fully accurate.  The `MPLBACKEND` environment variable is not set on ubuntu, but what they do (annoyingly) is set `backend=TkAgg` in a [matplotlib _rc file_](https://matplotlib.org/stable/tutorials/introductory/customizing.html#customizing-with-matplotlibrc-files) shipped in `/etc`.  The `MPLBACKEND` environment variable overrides this.

If we want this to be formally correct, it might be best to just say `On Ubuntu the default pyplot configuration uses the TkAgg backend, you must ...` aka don't claim the default is `MPLBACKEND=TkAgg` explicitly.  Trying to explain anything else (available backends, `MPLBACKEND` vs rcfile) in the message is too much, they have a command they can run to blindly succeed.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17437)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),svenevs (waiting on @jwnimmer-tri)

**Pull request merged**
