### PR TITLE
Update iris (remove pods_find_pkg_config way of finding eigen).

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes https://github.com/RobotLocomotion/drake/issues/3511.
See https://github.com/rdeits/iris-distro/pull/45.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3534)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Really this should be `EIGEN_INCLUDE_DIRS`, but I guess the value is always the same:

https://github.com/tkoolen/iris-distro/blob/5e36d399aac38bbb7cd575e310bf74bacc473b52/iris/CMakeLists.txt#L46

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3534#-:-KSBpd0fvk5y1nBI3jMQ:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3534#-:-KSCTNWP_D9A0A30x-Lm:bnfp4nl)*

**Pull request merged**
