### PR TITLE
[common] Refactor FindRunfile error handling for clarity

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #22269.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22293)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for both reviews per schedule (tomorrow), please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: x2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22293#-:-ODn6M3B1XeikBrN5a9V:bks4n6x)* status: 2 unresolved discussions

___
*[`common/find_runfiles.cc` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22293#-ODn5CIi-9c0bv0j16Ba:-ODn5CIi-9c0bv0j16Bb:bl5xrz) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca4b57c89217553e7d572d629de6e75e6531d94a/common/find_runfiles.cc#L53)):*
> ```cpp
>   RunfilesSingleton singleton;
> 
>   // Chose a mechanism based on environment variables.
> ```

nit, grammar



_Suggestion:_
```cpp
// Choose a mechanism based on environment variables.
```
___
*[`common/find_runfiles.cc` line 137 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22293#-ODn4wbB2570qtoa7Ho8:-ODn4wbB2570qtoa7Ho9:b-u9ydn4) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca4b57c89217553e7d572d629de6e75e6531d94a/common/find_runfiles.cc#L137)):*
> ```cpp
> 
> // Returns the RunfilesSingleton for the current process, latch-initializing it
> // first if necessary.
> ```

nit, this comment needs an update.



_Code quote:_
```cpp
// Returns the RunfilesSingleton for the current process, latch-initializing it
// first if necessary.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22293)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

___
*[`common/find_runfiles.cc` line 137 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22293#-ODn4wbB2570qtoa7Ho8:-ODn9mGG86dYJKqUnHvk:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca4b57c89217553e7d572d629de6e75e6531d94a/common/find_runfiles.cc#L137)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this comment needs an update.
</blockquote></details>

Done

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22293)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee xuchenhan-tri(platform)

**Pull request merged**
