### PR TITLE
Re-enable all tests that require Gurobi, consolidate Gurobi test tags, and fix latent renames.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per #5862, this reverts the commit in #5863 but still disables Gurobi in CI (via https://github.com/RobotLocomotion/drake-ci/commit/88555be). This permits developers to run tests locally without having to uncomment the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6110)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for all reviews.
(I believe this reversion can still be used once the renewed CI license can be installed.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-:-KkGh7TTSfg0iWcjqc8w:b-ajsn4t)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Do we need to revert #5865 too?

**Comment by EricCousineau-TRI** [comment]
Oops, I incidentally had already reverted #5865:
```
$ git revert c518fd09a36bbb1958e1de53c4bae2729d860921
On branch feature/5864_revert
nothing to commit, working directory clean
```
I had seen this commented out portion when resolving a merge conflict (see [here](https://github.com/RobotLocomotion/drake/pull/6110/files#diff-7da33b58122440f71e3539141e1d40ccR462)), and ended up taking the uncommenting portion (thinking there was something odd with the `git merge`). That makes more sense, then.

**Comment by EricCousineau-TRI** [comment]
Looking at the errors, it seems that these are due to changes that I had created during a refactor (that was not covered by the disabled tests on my machine locally).

I will fix those.

**Comment by EricCousineau-TRI** [comment]
Seems that we still have failures, including these tests (which are either Gurobi or MOSEK):
```
convex_optimization_test
global_inverse_kinematics_collision_avoidance_test
global_inverse_kinematics_reachable_test
global_inverse_kinematics_test
gurobi_solver_test
mixed_integer_optimization_test
rotation_constraint_limit_test
rotation_constraint_test
test_python_pydrake.test.testGurobiSolver
```

@jamiesnape It seems like some of these might be license procurement issues, possibly between concurrent test sessions.
Is this what the `exclusive` tag is for? Does it take effect in CI? And is there an analog for CMake?
If so, should we ensure that each potential Gurobi / MOSEK test has this tag?

**Comment by jamiesnape** [comment]
We have 4096 licenses, so concurrency is not an issue. The issue was a supposedly bad password on the license server. Try retesting.

**Comment by jamiesnape** [comment]
The MOSEK license is local and has no technical restrictions.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
My understanding is that the `exclusive` tag is to limit the load on the TRI Gurobi license server. It is technically unnecessary for CI (unless we write several hundred more Gurobi tests and max out our EC2 quotas).

**Comment by EricCousineau-TRI** [comment]
Hmm... I am still getting intermitten / sporadic test failures on my machine. For instance, `mosek_solver_test` has just failed, where normally it runs fine. Will do some RCA.

**Comment by EricCousineau-TRI** [comment]
To elaborate on the sporadic nature, I just ran the following command (5 tests) for a total of 3 times with no changes to the code, within the timespan of ~20 minutes:
```bash
$ bazel test $(echo "//drake/solvers:rotation_constraint_test
//drake/multibody/dev:global_inverse_kinematics_collision_avoidance_test
//drake/multibody/dev:global_inverse_kinematics_reachable_test
//drake/solvers:mosek_solver_test
//drake/systems/trajectory_optimization:trajectory_optimization_test
")
```

Failures for each run:

1. (5 tests) All.
2. (3 tests) `//drake/solvers:rotation_constraint_test, //drake/multibody/dev:global_inverse_kinematics_collision_avoidance_test, //drake/multibody/dev:global_inverse_kinematics_reachable_test`
3. (2 tests) `//drake/solvers:rotation_constraint_test, //drake/multibody/dev:global_inverse_kinematics_reachable_test`

**Comment by jamiesnape** [comment]
For your local tests, you are definitely going to want to have the `exclusive` tag.

**Comment by EricCousineau-TRI** [comment]
Refactored the obvious Gurobi-tagged tests to be consistent and always include `"exclusive"` and `"local"` tags.
Those same five tests passed on a first try. Will clear my test cache (somehow...) and retry.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please.

**Comment by EricCousineau-TRI** [comment]
Seems that only `linux-gcc-experimental-matlab` needs a longer time to run `global_inverse_kinematics_collision_avoidance_test`. Increased the size from `medium` to `large`.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything please
@drake-jenkins-bot linux-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-:-KkS7wqLyYLySg9fwGmE:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review, please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-:-KkS8Qi5AuR0BuQ-zUJp:bxwr5c8)*

**Comment by jwnimmer-tri** [comment]
I think this is no longer a pure revert?  If so, the PR title should probably be revised to be more precise.

**Comment by EricCousineau-TRI** [comment]
Done. Thanks!

**Comment by soonho-tri** [comment]
Reviewed 2 of 8 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-KkSIVaOv3-_uBF2Mwxq:-KkSIVaOv3-_uBF2Mwxr:b-mv5sse) ([raw file](https://github.com/robotlocomotion/drake/blob/f55418fdc7a079cc9dd0f4cb0c939d4f8039a2d8/tools/bazel.rc#L28)):*
> ```
> # -- Gurobi checks a license file, and may need to contact a license server to
> # -- check out a license. Therefore, tests that use Gurobi must have the tag
> # -- "local", because they are non-hermetic. For the moment, we also require
> ```

BTW, mosek is also accessing its license file located at `~/mosek/mosek.lic`. Does that mean we need to add `local` tag to mosek-related tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110)*

**Comment by EricCousineau-TRI** [comment]
Review status: 11 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-KkSIVaOv3-_uBF2Mwxq:-KkTMHF9hH9eyaq_cx8o:bf6szra) ([raw file](https://github.com/robotlocomotion/drake/blob/f55418fdc7a079cc9dd0f4cb0c939d4f8039a2d8/tools/bazel.rc#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, mosek is also accessing its license file located at `~/mosek/mosek.lic`. Does that mean we need to add `local` tag to mosek-related tests?
</blockquote></details>

Done. Thanks for pointing that out, and asking on Slack!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-KkSIVaOv3-_uBF2Mwxq:-KkTbeYiz90ceD0YK9Se:b7m5l5j) ([raw file](https://github.com/robotlocomotion/drake/blob/f55418fdc7a079cc9dd0f4cb0c939d4f8039a2d8/tools/bazel.rc#L28)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. Thanks for pointing that out, and asking on Slack!
</blockquote></details>

Nice! Thank you!

BTW, this documentation is outdated because of this PR. One way to update the documentation is to mention the following here:

```
... tests that use Gurobi must have `gurobi_test_tags()` in the `tags` field.
```

and move the parts explaining `local` and `exclusive` tags to `tools/gurobi.bzl` file.

(and the same thing for the mosek part in this file and `tools/mosek.bzl`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110)*

**Comment by EricCousineau-TRI** [comment]
Review status: 11 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/bazel.rc, line 28 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-KkSIVaOv3-_uBF2Mwxq:-KklmX38JIV8S5Et6mEa:bt4ox15) ([raw file](https://github.com/robotlocomotion/drake/blob/f55418fdc7a079cc9dd0f4cb0c939d4f8039a2d8/tools/bazel.rc#L28)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Nice! Thank you!

BTW, this documentation is outdated because of this PR. One way to update the documentation is to mention the following here:

```
... tests that use Gurobi must have `gurobi_test_tags()` in the `tags` field.
```

and move the parts explaining `local` and `exclusive` tags to `tools/gurobi.bzl` file.

(and the same thing for the mosek part in this file and `tools/mosek.bzl`)

</blockquote></details>

Done. Thanks for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110)*

**Comment by jamiesnape** [comment]
Reviewed 2 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-:-KkmQ3EA9kYfsjgq5MhB:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6110#-:-KkmQDAO097rAEswzjSI:b1l9vqf)*

**Pull request merged**
