### PR TITLE
Use named port instead of numbered port for Schunk status sender. Also set the size of the Schunk torque input port.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7937)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7937#-:-L4MJB2kxkJJOCJUfRL8:bjquaum)*

**Comment by sammy-tri** [comment]
:lgtm: with one minor note.  +@sherm1 for platform review

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7937#-L4MVSxqdz_qAs9OWnoZ:-L4MVSxre2HroFVHV2d3:b-idbikm) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e26db3d8bc0da10cc4c994cf5244d204514494/manipulation/schunk_wsg/schunk_wsg_lcm.h#L95)):*
> ```objc
> class SchunkWsgStatusSender : public systems::LeafSystem<double> {
>  public:
>   SchunkWsgStatusSender(int input_state_size, int input_torque_size,
> ```

BTW I'm not sure adding `input_torque_size` adds much since the code always just reads the first element from the vector?  I guess it could eventually be the first element of a larger vector?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7937#-:-L4MYTmp2gzGpMkGCf0Q:b2xys6t)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[manipulation/schunk_wsg/schunk_wsg_lcm.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7937#-L4MVSxqdz_qAs9OWnoZ:-L4MjE5TkthE5V0jKjts:b-b57pqs) ([raw file](https://github.com/robotlocomotion/drake/blob/e0e26db3d8bc0da10cc4c994cf5244d204514494/manipulation/schunk_wsg/schunk_wsg_lcm.h#L95)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I'm not sure adding `input_torque_size` adds much since the code always just reads the first element from the vector?  I guess it could eventually be the first element of a larger vector?
</blockquote></details>

I was thinking that there are two prismatic joints in the schunk gripper, so we might eventually want to get some information about the forces in both joints.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7937)*

**Comment by sherm1** [comment]
Per f2f this is making another change besides using named ports -- it allows setting of the size of one of the ports also. Platform :lgtm: but should update the description before merging.

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7937#-:-L4MuOHO8ZIQtDpTs77S:b-3air2d)*

**Pull request merged**
