### PR TITLE
Symbolic Direct Transcription

### PR DESCRIPTION
**Pull request by RussTedrake**
uses the symbolic inspector to check if a system is affine or not.  If yes, then it adds linear constraints to enforce the dynamics instead of the general nonlinear dynamic constraints.  the result:  if you pass in a system that is affine (or linear) that supports DoToSymbolic, add only quadratic costs and linear constraints, then dirtran ends up as a QP instead of an NLP. 

this makes me so happy inside.  ;-)

NB - this PR contains the two commits from #6887 which is about ready to go in.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6921)

### CODE REVIEW

**Comment by RussTedrake** [comment]
fyi @stonier, @jadecastro ; this checks another box in #6858, and should be everything you need.  (the constraints parsing will help, but should not be blocking you).

**Comment by RussTedrake** [comment]
#6887 has landed and I've rebased.  Should be clean now.

**Comment by soonho-tri** [comment]
Thanks for the patience. :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsXFafAJtUoWUVNUspJ:-KsXFafAJtUoWUVNUspK:b-2ylqjg) ([raw file](https://github.com/robotlocomotion/drake/blob/00a0523f9c1e04416879c0482751617c01cbdc53/drake/systems/trajectory_optimization/direct_transcription.cc#L130)):*
> ```cpp
>         symbolic::Substitution sub;
>         sub.emplace(inspector->time(), i * fixed_timestep());
>         // TODO(russt/soonho): Can we make a cleaner way to do substitutions
> ```

Please reflow this TODO comment and add #6925 to it.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsXHFd9-awmQLnCB48f:-KsXHFd9-awmQLnCB48g:b3gf90t) ([raw file](https://github.com/robotlocomotion/drake/blob/00a0523f9c1e04416879c0482751617c01cbdc53/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L37)):*
> ```cpp
> 
> // Cubic Polynomial System:
> //   ẋ = -x + x³
> ```

BTW, I think these two lines (for ẋ and y) should be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-:-KsXFzj09K5OsntE0C_d:b8xek0p)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsXFafAJtUoWUVNUspJ:-KsYLYFMrMrVk04ucqzZ:b-l5r1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/00a0523f9c1e04416879c0482751617c01cbdc53/drake/systems/trajectory_optimization/direct_transcription.cc#L130)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please reflow this TODO comment and add #6925 to it.
</blockquote></details>

Done.  Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 37 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsXHFd9-awmQLnCB48f:-KsYLaiYMANjEPyMYkeQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00a0523f9c1e04416879c0482751617c01cbdc53/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L37)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think these two lines (for ẋ and y) should be removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-:-Ks_9CBKysG5p9blB6v_:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdJLF_9yWroGv4_1_l:-KsdJLF_9yWroGv4_1_m:b-bz869v) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L23)):*
> ```cpp
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(DiscreteTimeSystemConstraint)
> 
>  public:
> ```

BTW nit Redundant `public`.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdGqRR7Jp0hslFRN3C:-KsdGqRSXTT-gfzhd1VL:b-b3lrgf) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L85)):*
> ```cpp
>   const System<AutoDiffXd>& system_;
>   Context<AutoDiffXd>* const context_;
>   FreestandingInputPortValue* const input_port_value_;
> ```

That this field is sometimes-null is too obscure (requires too much code tracing to discern.)  Assuming this variable remains here, it should be commented that it is nullptr exactly when `(num_inputs_ == 0)`.  (Alternatively, asserting that in our constructor above would also be a fine resolution.)

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-Ksd9hQiLXa6H_7CgWZs:-Ksd9hQiLXa6H_7CgWZt:br6um8) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L119)):*
> ```cpp
>   // First try symbolic dynamics.
>   bool added_symbolic_dynamic_constraints = false;
>   const auto symbolic_system = System<double>::ToSymbolic(*system);
> ```

FYI This phrasing is slightly strange (usually the static method would be used to use a System subtype).  Consider `auto symbolic_system = system->ToSymbolic();` for brevity.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 151 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdFBLzSbDTJakWVFOC:-KsdFBLzSbDTJakWVFOD:bnvl66s) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L151)):*
> ```cpp
>     DRAKE_DEMAND(system_ != nullptr);
>     context_ = system_->CreateDefaultContext();
>     discrete_state_ = system_->AllocateDiscreteVariables();
> ```

Now that these are sometimes-null member-fields, I think the member data of class is pushing the limits of readability.

If you were to gather all of these fields into a named sub-struct within this class, then there could just be a single member field `unique_ptr<DiscreteTimeSystemConstraintHelper>` with a comment indicating when it is nullptr vs not.  Furthermore, the existing `DirectTimeSystemConstraint` class above could then be changed to merely alias the `DiscreteTimeSystemConstraintHelper` struct, instead of repeating all of its fields (it would probably change to be a forward-declared nested class, instead of anonymous).

Absent that change, we'd need more comments at the declaration point of the member fields explaining when they are null.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdEkmqmY5rWVKNk3Lg:-KsdEkmqmY5rWVKNk3Lh:bygn40a) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L200)):*
> ```cpp
>     AddLinearConstraint(input(N() - 2) == input(N() - 1));
>   }
> }
> ```

FYI _"If a function exceeds about 40 lines, think about whether it can be broken up without harming the structure of the program."_  -- https://google.github.io/styleguide/cppguide.html#Write_Short_Functions.  To my eye, it seems like `bool MaybeAddAffineDynamicsConstraints(...)` would be useful, and then if it returns false we do `AddDiscreteTimeSystemConstraints(...)`, or something.

I think the linear vs system constraint blocks here are reasonable candidates for helper functions.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdLWr2Rg87tnYzwTU_:-KsdLWr2Rg87tnYzwTUa:bkeit4x) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L37)):*
> ```cpp
> 
> template <typename T>
> class CubicPolynomialSystem : public systems::LeafSystem<T> {
> ```

FYI Systems that do `SystemTypeTag` into `LeafSystem` should be marked `final` (this will be part of my forthcoming documentation push).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KseVch3alLk7Sk8n26K:-KseVch3alLk7Sk8n26L:b-ospv13) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L88)):*
> ```cpp
> 
>   // Constructor should add dynamic constraints, and these are the
>   // only generic constraints that should be in the program so far.
> ```

BTW, this comment should be updated to say something like: "... and these are identified as linear equality constraints."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KseVch3alLk7Sk8n26K:-KseWqFB6bc_9juM0Cjj:b1wpto8) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L88)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, this comment should be updated to say something like: "... and these are identified as linear equality constraints."
</blockquote></details>

(disregard - I meant for this to appear below)

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 126 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KseWhHb0wHYFkYNmai3:-KseWhHb0wHYFkYNmai4:b-ospv13) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L126)):*
> ```cpp
> 
>   // Constructor should add dynamic constraints, and these are the
>   // only generic constraints that should be in the program so far.
> ```

BTW, this comment should be updated to say something like: "... and these are identified as linear equality constraints."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdJLF_9yWroGv4_1_l:-Ksf24Xk8GSaQO3IKEUw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW nit Redundant `public`.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 85 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdGqRR7Jp0hslFRN3C:-Ksf2OdoxfjdCagwZGBO:bux0jt1) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That this field is sometimes-null is too obscure (requires too much code tracing to discern.)  Assuming this variable remains here, it should be commented that it is nullptr exactly when `(num_inputs_ == 0)`.  (Alternatively, asserting that in our constructor above would also be a fine resolution.)
</blockquote></details>

done.  added the check in the constraint constructor. 

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 119 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-Ksd9hQiLXa6H_7CgWZs:-Ksf2cgyr8Pw-4k_4lUl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This phrasing is slightly strange (usually the static method would be used to use a System subtype).  Consider `auto symbolic_system = system->ToSymbolic();` for brevity.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 151 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdFBLzSbDTJakWVFOC:-Ksf49-LTOLKCjBlaKDD:b-fmau01) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L151)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Now that these are sometimes-null member-fields, I think the member data of class is pushing the limits of readability.

If you were to gather all of these fields into a named sub-struct within this class, then there could just be a single member field `unique_ptr<DiscreteTimeSystemConstraintHelper>` with a comment indicating when it is nullptr vs not.  Furthermore, the existing `DirectTimeSystemConstraint` class above could then be changed to merely alias the `DiscreteTimeSystemConstraintHelper` struct, instead of repeating all of its fields (it would probably change to be a forward-declared nested class, instead of anonymous).

Absent that change, we'd need more comments at the declaration point of the member fields explaining when they are null.
</blockquote></details>

Added a comment to the member variable declarations.  Let me know if you think it's sufficient.  

---

*[drake/systems/trajectory_optimization/direct_transcription.cc, line 200 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdEkmqmY5rWVKNk3Lg:-Ksf72-q99wvkeun9eFI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/direct_transcription.cc#L200)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _"If a function exceeds about 40 lines, think about whether it can be broken up without harming the structure of the program."_  -- https://google.github.io/styleguide/cppguide.html#Write_Short_Functions.  To my eye, it seems like `bool MaybeAddAffineDynamicsConstraints(...)` would be useful, and then if it returns false we do `AddDiscreteTimeSystemConstraints(...)`, or something.

I think the linear vs system constraint blocks here are reasonable candidates for helper functions.
</blockquote></details>

Done.

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KsdLWr2Rg87tnYzwTU_:-Ksf7h_rkxcEkn6KCMQc:b-am2p9h) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Systems that do `SystemTypeTag` into `LeafSystem` should be marked `final` (this will be part of my forthcoming documentation push).
</blockquote></details>

Done.  (looks like there are a lot of examples in the code that do not)

---

*[drake/systems/trajectory_optimization/test/direct_transcription_test.cc, line 126 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-KseWhHb0wHYFkYNmai3:-Ksf84JgYfGtJwzLHwiX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e578214fe299f075e86d8d1e73b19f3107cb6e87/drake/systems/trajectory_optimization/test/direct_transcription_test.cc#L126)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, this comment should be updated to say something like: "... and these are identified as linear equality constraints."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921#-:-KsfMCYOca80HcAYL_PZ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
CI's GCC `Werror`s are real.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6921)*

**Pull request merged**
