### PR TITLE
Add a CROSSTOOL file for clang on Ubuntu.

### PR DESCRIPTION
**Pull request by david-german-tri**
Please test this locally!  Works for me on Trusty.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4322)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
WFM locally on Xenial with Bazel 0.3.1.  Has the usual `Wundefined-var-template` complaints that Clang-3.9 emits, even.

I am going to spend a bit longer code reviewing the crosstool stuff, though.

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-:-KXrhbKYIzH66FjG0BNZ:bjmomb)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

The cc_toolchain stuff is still unsupported so I'm not going to get too picky about how this is all done.  If you look in the `CROSSTOOL` files from upstream, they appear to have many more flags be toyed with, but we can start here and iterate.

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXrrZcQuDXJm0phlrd0:-KXrrZcQuDXJm0phlrd1:b-cpx7ud) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/drake/doc/bazel.rst#L76)):*
> ```reStructuredText
> 
>   bazel build --compiler=clang-3.9 --crosstool_top=//tools:default-toolchain ...
> ```

BTW Adding the below to `bazel.rc` allows for `bazel build --config clang` which is a bit more user-friendly?

```bash
# Clang support.
build:clang --compiler=clang-3.9
build:clang --crosstool_top=//tools:default-toolchain
```

It still appears to work even as `bazel build --config clang --config asan ...` (the config option merge).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-:-KXrsu4tbKhWVNeXsAiL:be6cm5e)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/CROSSTOOL, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUmYimKx1dN1h8e4O:-KXsUmYimKx1dN1h8e4P:bf22xgm) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L40)):*
> ```
>     mode: DBG
>     cxx_flag: "-g3"
>   }
> ```

consider also -O0 here?

---

*[tools/CROSSTOOL, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUf5S9ppNFcfU9JBf:-KXsUf5TezVmCsndiKwk:b-zavmd1) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L48)):*
> ```
>     compiler_flag: "-DNDEBUG"
>     compiler_flag: "-fno-omit-frame-pointer"
>     compiler_flag: "-O2"
> ```

Why are some things keyed as 'compiler_flag' and others as 'cxx_flag'? does it matter?

---

*[tools/CROSSTOOL, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUsQjxg7-h1306Lxr:-KXsUsQmJxoIiXDlnYN1:b-3xqfjq) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L60)):*
> ```
>   cxx_builtin_include_directory: "/usr/lib/llvm-3.9/lib/clang/3.9.1/include"
> 
>   tool_path { name: "gcov" path: "/usr/bin/gcov" }
> ```

I'll declare my doubt that gcov works with clang, but I don't actually know. How do we test this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/CROSSTOOL, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUsQjxg7-h1306Lxr:-KXvHYWl2R-wjiMby1yn:b-rw1qgv) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L60)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll declare my doubt that gcov works with clang, but I don't actually know. How do we test this?
</blockquote></details>

It works or you can use llvm-cov.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322)*

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/bazel.rst, line 76 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXrrZcQuDXJm0phlrd0:-KY01KeuCU64bGf15w1o:buv40uw) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/drake/doc/bazel.rst#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Adding the below to `bazel.rc` allows for `bazel build --config clang` which is a bit more user-friendly?

```bash
# Clang support.
build:clang --compiler=clang-3.9
build:clang --crosstool_top=//tools:default-toolchain
```

It still appears to work even as `bazel build --config clang --config asan ...` (the config option merge).
</blockquote></details>

Done.  Nifty!

---

*[tools/CROSSTOOL, line 40 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUmYimKx1dN1h8e4O:-KY01j8qDCE-Eld6AtYY:b-l2tt7p) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L40)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

consider also -O0 here?
</blockquote></details>

Done, good catch.

---

*[tools/CROSSTOOL, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-KXsUf5S9ppNFcfU9JBf:-KY01boS5oOHWpb7TUf7:b-dcdmsu) ([raw file](https://github.com/robotlocomotion/drake/blob/7722ffe262005e23a378dbc76810e575ff2f40d9/tools/CROSSTOOL#L48)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Why are some things keyed as 'compiler_flag' and others as 'cxx_flag'? does it matter?
</blockquote></details>

https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/crosstool_config.proto#L34

Not sure I've got it perfect, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-:-KY0JzNYBOXVLMDRPqjW:bnfp4nl)*

**Comment by david-german-tri** [comment]
Bazel build passed, not waiting for the others.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4322#-:-KY0NQ5a5OU4TxD1qXRX:befd2bw)*

**Pull request merged**
