### PR TITLE
Fixed 32-bit windows bug in rigid_body_tree_test.cc.

### PR DESCRIPTION
**Pull request by liangfok**
Closes https://github.com/RobotLocomotion/drake/issues/2151.

Note that the changes made in this PR are to fix a bug when running rigid_body_tree_test in 32-bit Windows and in debug mode, which I think only runs after the PR is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2162) &emsp; Multiple assignees:&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by liangfok** [comment]
@sherm1, can you please review this?

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0dv4lieFjz6ULTuSW:-KG0dv4lieFjz6ULTuSX:1820149248) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L17)):*
Consider using `std::allocate_shared()` instead, although this might be cleaner as-is. However, in either case it is critical to document why you are doing this or the next person through this code will change it to `std::make_shared()` to tidy it up!

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KG0eIfna2UqPpCItwbH:642384598) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
Why does this test class have to have an aligned allocator?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0dv4lieFjz6ULTuSW:-KG0f0Zyy0JUJASYEiwZ:1403102223) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L17)):*
P.S. There is a (usually ignorable) performance cost to the solution you have here, which is that two heap allocations occur (one for RigidBody and one for shared_ptr's reference counter). make_shared and allocate_shared do a single heap allocation that handles both at once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 17 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0dv4lieFjz6ULTuSW:-KG22dsjS8-ZQ88sB-mb:305179591) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L17)):*
I tried using `std::allocated_shared()` with Eigen's aligned allocator but couldn't get it to compile. 

I've added documentation indicating the increased allocation overhead and our justification of why it is OK. This is perhaps due to time constraints on my part: While I would love to learn how to write a custom aligned allocator, I think prioritizing an OKR deliverable is more important for now.

I think https://github.com/RobotLocomotion/drake/issues/1854 is sufficient to track this problem. Let me know if this is correct and OK.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KG1yHiRqw5vKHR7ysom:-1744426373) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
This was needed because of the `RigidBodyTree` member variable defined below. When I remove it, the memory alignment issue returns. I think this hints at a deeper problem somewhere within RigidBodyTree that placing an aligned allocator at this level happens to fix. Since `RigidBodyTree` is very complicated and is about to be refactored (see: https://github.com/RobotLocomotion/drake/issues/2074), I think we should hold off fixing this problem in this PR. Is issue https://github.com/RobotLocomotion/drake/issues/1854 sufficient to track its resolution or should I create a new one specific to `RigidBodyTree`?

To avoid needing an aligned allocator within the Google Text Fixture, I changed the member variable to be from:

```
RigidBodyTree tree;
```

to be:

```
std::shared_ptr<RigidBodyTree> tree;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by RussTedrake** [comment]
We have aligned_allocator examples in the code already.

**Comment by liangfok** [comment]
Thanks. I updated the unit test to use `aligned_allocator`.

**Comment by liangfok** [comment]
@sherm1: this PR is ready for another round of review.

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KGDFnlVIfDTQUfP4ung:-2141910179) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
If you need the indirection but the tree isn't actually shared, this should be a unique_ptr. Oddly, there is no `allocate_unique` since there is no overhead associated with just using new.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KGDHW3dIf5Be_GNOLXs:1468602246) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
Thanks for the info. I was, in fact, wondering where the missing `allocate_unique()` went. There's no need for indirection in this case.

I still need to use `std::shared_ptr` for the various rigid body objects because that's required by the `RigidBodyTree` API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
@jwnimmer-tri: since the only CI failure appears to be due to https://github.com/RobotLocomotion/drake/issues/2154, I'll assign this to you for final review / merge.

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KGDkRtpswiJP4fJCfM1:1402892968) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
So can you change here to `std::unique_ptr<RigidBodyTree> tree;`? That seems better than shared_ptr if it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KGDvHCFX2PRt42JhCZP:-1087859467) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
Yes, I've made the change and am recompiling now. Will issue git push to update this PR soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by jwnimmer-tri** [comment]
It sounds like a code update in in flight; I am going to wait to review until then, unless I hear otherwise.

**Comment by liangfok** [comment]
@jwnimmer-tri: Yes, I will ping you when it's ready for you to review. Having compiler issues switching to `unique_ptr<RigitdBodyTree>`.

**Comment by liangfok** [comment]
*[drake/systems/plants/test/rigid_body_tree_test.cc, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KG0eIfna2UqPpCItwbG:-KGECarvtbqLk2jk2lTI:1749577778) ([raw file](https://github.com/robotlocomotion/drake/blob/f90bbd4d8f164c06a6cbd15bd5a7bae28bfe5073/drake/systems/plants/test/rigid_body_tree_test.cc#L35)):*
@sherm1: I modified the unit test to use `unique_ptr<RigidBodyTree>`. I'm afraid it may not be the most efficient way of doing it, but it's the one way I've been able to get it to compile. Can you please take a look?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
+@sherm1  +@jwnimmer-tri 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-:-KGECsOdoAbchiwwZ0tS:-1256324904)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-:-KGEFlj0chWllOUYjkmw:1417088721)*

**Comment by liangfok** [comment]
@jwnimmer-tri: This PR is ready for you to review / merge.

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 16 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEPqEsBtYOQbHXnFZU:-KGEPqEsBtYOQbHXnFZV:1280425232) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L16)):*
As far as I can tell, this comment states the obvious.

"Do not state the obvious." -- https://google.github.io/styleguide/cppguide.html#Implementation_Comments

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 19 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEQBjXHlmZvhZBzXeD:-KGEQBjXHlmZvhZBzXeE:-829219371) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L19)):*
Grammar error, 'a four'.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 36 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEQIyFu2hvR-Ei3FDb:-KGEQIyFu2hvR-Ei3FDc:-210360805) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L36)):*
I hate that the magic spell has to appear 4 times repetitively (brittle duplication), but I suppose I will wait for #1854 for a better solution.  For now I will rejoice that builds of master go green.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
@jwnimmer-tri: PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 16 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEPqEsBtYOQbHXnFZU:-KGEZ8qxpRsVILMKpx1x:1447085320) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L16)):*
This of course opens the following gigantic, highly philosophical, and highly political question: 

> "What is the definition of obvious?"

:grin: 

In this particular context, I can see how a C++ guru with 20+ years of programming experience could view the line below as "obvious." However, to someone with less C++ experience or to a Java developer, the following line could be confusing since the actual instantiation (`new RigidBodyTree()`) is surrounded by a mysterious `std::unique_ptr<RigidBodyTree>` nonsense. A Java developer would mistaken that to be a call to a method called `std::unique_ptr<RigidBodyTree()`.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 19 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEQBjXHlmZvhZBzXeD:-KGEc6sLf35VIYNk3nqa:-795674665) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L19)):*
Fixed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-:-KGEcPVthHYIf-ylp5J3:1812511779)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/test/rigid_body_tree_test.cc, line 16 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEPqEsBtYOQbHXnFZU:-KGEdCURMqMg-lRFQVaw:499488150) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L16)):*
Would `tree.reset(new RigidBodyTree())` be a compromise that requires no extra comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/test/rigid_body_tree_test.cc, line 16 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEPqEsBtYOQbHXnFZU:-KGEdyL1BlMBC6D061ni:-2075855875) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L16)):*
Or (sorry for the spam), I guess `tree.reset(new RigidBodyTree)` would be even more conventional.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_tree_test.cc, line 16 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-KGEPqEsBtYOQbHXnFZU:-KGEekLj7HL3Gvc4n2pO:-1305466348) ([raw file](https://github.com/robotlocomotion/drake/blob/6c407531be7c4d0acaa19f18fa1d14c740764d95/drake/systems/plants/test/rigid_body_tree_test.cc#L16)):*
Aha! So that's the magic incantation for initializing a `unique_ptr` outside of of a constructor's initializer list!

I've updated the call and removed the obvious comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2162#-:-KGEfua1N9TeFlkpxjAU:1417088721)*

**Comment by jwnimmer-tri** [comment]
Jenkins is green except for OSX, which seems to be #2154 as best I can tell.  Using override-merge now to get this in.

**Comment by jwnimmer-tri** [comment]
Happy to report that [windows-msvc-32-continuous-debug](https://drake-jenkins.csail.mit.edu/view/Continuous/job/windows-msvc-32-continuous-debug/) is passing now.

**Comment by liangfok** [comment]
FTR:
trend

**Pull request merged**
