### PR TITLE
[doc] Add release notes v1.27.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Thanks!  I've pushed the build system part.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.27.0.md` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NszKUpc1WaURxtc5Rj8:-NszKUpc1WaURxtc5Rj9:b-hmfkxd) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L132)):*
> ```Markdown
> * [feature] TBD [planning,solvers] Implement wraparound edges together with the subspace machinery ([#20886][_#20886])
> * [feature] TBD enable removal of subgraphs ([#21006][_#21006])
> * [] TBD Add comment that IrisInConfigurationSpaceFromCliqueCover does not obe… ([#21033][_#21033])  # Add comment that IrisInConfigurationSpaceFromCliqueCover does not obey collision checker padding
> ```

nit 21033 was non-notable, but we forgot to mark that in the PR.  You can remove this line.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.27.0.md` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHZSjTDXrPyV5V1c6T:-NtHZSjTDXrPyV5V1c6U:b-hx7pb3) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L97)):*
> ```Markdown
> 
> 
> * [fix] TBD [geometry] Fix lights expressed in camera frame for RenderEngineVtk ([#20930][_#20930])  # * Fixes VTK illumination bugs See the documentation in fix_illumination_bugs.patch for details. But this corrects: 1. Missing tests on the "positionality" of a light, 2. Computation using uninitialized memory. * Fix lights expressed in camera frame for RenderEngineVtk The old code misrepresented the device frame; it was incomplete. It flipped to left-handed when it is more accurate to rotate the around Cx 180 deg. This also changes the light direction vector semantics. The input value need not be unit length, just normalizable. RenderEngineVtk had to change what it was doing, but RenderEngineGl was already doing this. Only its test was expanded to explicitly cover normalization.
> ```

+@SeanCurtis-TRI Can I ask for you to polish this section?
___
*[`doc/_release-notes/v1.27.0.md` line 154 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHZdby327Gd_BUTGMq:-NtHZdby327Gd_BUTGMr:b6f86qr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L154)):*
> ```Markdown
> 
> 
> * [feature] TBD [common,geometry,workspace] [yaml] Improve variant support for primitive types ([#20937][_#20937])
> ```

+@rpoyner-tri Can I ask for you to polish this section?
___
*[`doc/_release-notes/v1.27.0.md` line 165 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHZgqJ6uMBkOcOfzqm:-NtHZgqJ6uMBkOcOfzqn:b6f86qr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L165)):*
> ```Markdown
> 
> 
> * [fix] TBD [py visualization] Avoid runpy warning due to import order ([#20968][_#20968])  # When downstream code invokes meldis (or similar) using runpy, they would see this warning: `RuntimeWarning: 'pydrake.visualization.meldis' found in sys.modules after import of package 'pydrake.visualization', but prior to execution of 'pydrake.visualization.meldis'; this may result in unpredictable behaviour`. We can avoid that by importing the command-line modules during all.py instead of during their parent module's import.
> ```

+@rpoyner-tri Can I ask for you to polish this section?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`doc/_release-notes/v1.27.0.md` line 132 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NszKUpc1WaURxtc5Rj8:-NtHagWc2-ZrNB2u995M:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 21033 was non-notable, but we forgot to mark that in the PR.  You can remove this line.
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHalAzCumFxCYVlEIX:-NtHalAzCumFxCYVlEIY:b-ewqm6t) (no related file):*
Working: Will aim to use tomorrow AM's CI results for release candidate.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHalAzCumFxCYVlEIX:-NtHei7EBmrUnt46XV1F:b4impv2) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will aim to use tomorrow AM's CI results for release candidate.
</blockquote></details>

Given the goal of releasing by 3/15, I'd much prefer if we could use last night's sha as the target, and merge the release ASAP (i.e., today).

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.27.0.md` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHZSjTDXrPyV5V1c6T:-NtHrEdQ96Rb-Sh8BQ2x:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea74dc9e43602a4d5e3a17864b28af030d5fdf8b/doc/_release-notes/v1.27.0.md#L97)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

+@SeanCurtis-TRI Can I ask for you to polish this section?
</blockquote></details>

Done

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[`doc/_release-notes/v1.27.0.md` line 40 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHyQxB-AqZxSWakCOF:-NtHyQxB-AqZxSWakCOG:b401tg7) ([raw file](https://github.com/RobotLocomotion/drake/blob/7cab4294a82ca13d50fe993f7a64d2c22a609c3d/doc/_release-notes/v1.27.0.md#L40)):*
> ```Markdown
>   * This particular workflow for using Drake binaries via Bazel is characterized
>     by a line like this in your ``WORKSPACE`` file:
>     ```py
> ```

This markup breaks Github markdown, which is useful for reviewing pushed changes so far. Can we do something else here?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHalAzCumFxCYVlEIX:-NtI29MQDilYkEMXYR52:b5b80ui) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Given the goal of releasing by 3/15, I'd much prefer if we could use last night's sha as the target, and merge the release ASAP (i.e., today).
</blockquote></details>

Gotcha. I can't put much more time towards this today, unfortunately.
Would you be able to land the release?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHalAzCumFxCYVlEIX:-NtIU4vvCPaU2bWwTQXT:bizle5m) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. I can't put much more time towards this today, unfortunately.
Would you be able to land the release?
</blockquote></details>

I guess I'll try to see how well the WiFi around here works.  Hopefully everyone can finish their edits and review in the next approx 90 minutes.

___
___
*[`doc/_release-notes/v1.27.0.md` line 40 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHyQxB-AqZxSWakCOF:-NtITvGo1Wcdh3KgKwwf:b37tkuh) ([raw file](https://github.com/RobotLocomotion/drake/blob/7cab4294a82ca13d50fe993f7a64d2c22a609c3d/doc/_release-notes/v1.27.0.md#L40)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This markup breaks Github markdown, which is useful for reviewing pushed changes so far. Can we do something else here?
</blockquote></details>

GitHub markdown is not a supported preview tool.  See https://drake.mit.edu/documentation_instructions.html for how to run the `//doc:pages --serve` locally.

**Comment by jwnimmer-tri** [comment]
@SeanCurtis-TRI for platform review per schedule, please.  I'll also cross-check it myself before I merge.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @EricCousineau-TRI from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21141)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21141#-NtHalAzCumFxCYVlEIX:-NtIpXOW-bVDZOHl8_N_:bgume2d) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I guess I'll try to see how well the WiFi around here works.  Hopefully everyone can finish their edits and review in the next approx 90 minutes.
</blockquote></details>

Done.  Staging builds have been launched.  I'll take it from here.

___

**Comment by jwnimmer-tri** [comment]
:lgtm: emergency stamping to finish this ASAP.  Waiting for Staging to finish before I merge it.

**Comment by jwnimmer-tri** [comment]
I'm going to merge this without waiting for review, because we're several days overdue.  If you see things wrong, please go ahead and file PRs to fix it after the fact.

**Pull request merged**
