### PR TITLE
[Inverse Kinematics] Add PointToLineDistanceConstraint.

### LINKED ISSUE #18790: Request for AddDistanceFromLineConstraint for Drake IK
**Is your feature request related to a problem? Please describe.**
I am currently working on an IK problem where I would like to add a constraint that stops the center of a frame from being in a certain cylinder. The only way to do it with the current IK that I can think is say that the point must be farther than the radius of the cylinder away from a bunch of points on the axis of the cylinder.

**Describe the solution you'd like**
 I would love an `AddDistanceFromLineConstraint`, making the line the axis of the cylinder, and the distance the radius of the cylinder. 

**Describe alternatives you've considered**
Alternatively, `AddExcludeFromPolyhedronConstraint` would also be sufficient as I could approximate the cylinder with a number of surfaces. That said, I imagine that would be much harder to throw a solver at for convexity reasons.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Constrain the distance between a point and a line to be within certain range.

Resolves #18790

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-:-NOY8o-g7uNyw3DuWkOA:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
Just added a few minor comments

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-:-NOovtIE3iI5Ivqw84_h:b-j6cjt7)* status: 4 unresolved discussions, LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 350 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOocVJM8X81ynp2XNgc:-NOocVJM8X81ynp2XNgd:b-xnmzj2) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/inverse_kinematics.h#L350)):*
> ```objc
>    * @param distance_lower The lower bound on the distance.
>    * @param distance_upper The upper bound on the distance.
>    */
> ```

FYI, the frame names are inconsistent between the descriptions and the parameter names. That is, frames 1 and 2 express the point and line frames in the descriptions, whereas the corresponding parameters are named `frame_point` and `frame_line`.

A possible fix could be the following. Though, a drawback of this option is that `frame_point` and `frame_line` are still represented by `B1` and `B2` in the frame notation, e.g.,` p_B1P`. Alternatively, you could stick to the numeric frame names at the cost of clarity in the parameter name level. I'll leave it up to you but, if accepted, this change should be extended to the rest of the PR.



_Suggestion:_
```objc
   * Add a constraint that the distance between point P attached to frame_point and
   * a line attached to frame_line is within the range [distance_lower,
   * distance_upper].
   * The line passes through a point Q with a directional vector n.
   * @param frame_point The frame to which P is attached.
   * @param p_B1P The position of P measured and expressed in frame_point.
   * @param frame_line The frame to which the line is attached.
   * @param p_B2Q The position of Q measured and expressed in frame_line, the line
   * passes through Q.
   * @param n_B2 The direction vector of the line measured and expressed in
   * frame_line.
   * @param distance_lower The lower bound on the distance.
   * @param distance_upper The upper bound on the distance.
   */
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOomP9-D39lUl9vEyth:-NOomP9-D39lUl9vEyti:b-k9yy06) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.h#L23)):*
> ```objc
>   /**
>    Constrain the distance between a point P attached to a frame B1 and the line
>    L attached to frame B2 is within the range [distance_lower, distance_upper].
> ```

Relating to my comment above, here, frame B1 and B2 are used instead.



_Code quote:_
```objc
   Constrain the distance between a point P attached to a frame B1 and the line
   L attached to frame B2 is within the range [distance_lower, distance_upper].
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.h` line 36 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOol53TAOmyiSLHMZFj:-NOol53TAOmyiSLHMZFk:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.h#L36)):*
> ```objc
> 
>    @param plant The MultibodyPlant on which the constraint is imposed. `plant`
>    should be alive during the lifetime of this constraint.
> ```

nit



_Suggestion:_
```objc
 must be alive
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.h` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOol2O8B_xnYeIi8pv8:-NOol2O8B_xnYeIi8pv9:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.h#L50)):*
> ```objc
>    @param plant_context The Context that has been allocated for this
>      `plant`. We will update the context when evaluating the constraint.
>      `plant_context` should be alive during the lifetime of this constraint.
> ```

nit



_Suggestion:_
```objc
`plant_context` must be alive 
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOooO3h30tJ4UeCRM8Y:-NOooO3h30tJ4UeCRM8Z:bn8qzmv) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.cc#L41)):*
> ```cpp
>   DRAKE_DEMAND(distance_lower >= 0);
>   DRAKE_DEMAND(distance_upper >= distance_lower);
>   DRAKE_DEMAND(n_B2.norm() > 100 * kEps);
> ```

FYI, since the normal is normalized at initialization, couldn't this be a more strict check validating the norm is almost 1?



_Code quote:_
```cpp
n_B2.norm() > 100 * kEps
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.cc` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOopq36BDoGmBnhZ03v:-NOopq36BDoGmBnhZ03w:bqdk2m5) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.cc#L82)):*
> ```cpp
>   // The squared distance from a point P to a line is uᵀ(I-nnᵀ)u, where u = QP,
>   // Q being a point on the line, n being the unit-length vector along the line,
>   // project_matrix = I-nnᵀ
> ```

nit, this is great but just missing a period in the end.



_Suggestion:_
```cpp
  // The squared distance from a point P to a line is uᵀ(I-nnᵀ)u, where u = QP,
  // Q being a point on the line, n being the unit-length vector along the line,
  // project_matrix = I-nnᵀ.
```
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.cc` line 115 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOoqYAo8VtaIl-WBgLR:-NOoqYAo8VtaIl-WBgLS:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.cc#L115)):*
> ```cpp
>   const Frame<T>& frame_point = plant.get_frame(frame_point_index);
>   const Frame<T>& frame_line = plant.get_frame(frame_line_index);
>   // Compute p_B2P
> ```

nit



_Suggestion:_
```cpp
 // Compute p_B2P.
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 350 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOocVJM8X81ynp2XNgc:-NOqS0u3Co8iKvxLyTsQ:b87bgk3) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/inverse_kinematics.h#L350)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

FYI, the frame names are inconsistent between the descriptions and the parameter names. That is, frames 1 and 2 express the point and line frames in the descriptions, whereas the corresponding parameters are named `frame_point` and `frame_line`.

A possible fix could be the following. Though, a drawback of this option is that `frame_point` and `frame_line` are still represented by `B1` and `B2` in the frame notation, e.g.,` p_B1P`. Alternatively, you could stick to the numeric frame names at the cost of clarity in the parameter name level. I'll leave it up to you but, if accepted, this change should be extended to the rest of the PR.
</blockquote></details>

Done. I also modified the documentation in point_to_line_distance_constraint.h
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOooO3h30tJ4UeCRM8Y:-NOqSM9b9EYb1-rQ1Jzb:b-58er10) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.cc#L41)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

FYI, since the normal is normalized at initialization, couldn't this be a more strict check validating the norm is almost 1?
</blockquote></details>

This actually checks if the user-supplied n_B2 is zero or not. The normalization is meaningful if n_B2 is non-zero.

**Review by aykut-tri — COMMENTED** [review]
:lgtm:

+@EricCousineau-TRI for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-:-NOt_ZKB3zDGPTdo_VIF:b-nbay8p)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`multibody/inverse_kinematics/inverse_kinematics.h` line 350 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOocVJM8X81ynp2XNgc:-NOtZzqt7btuvktVX4iP:b-6mhyx0) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/inverse_kinematics.h#L350)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I also modified the documentation in point_to_line_distance_constraint.h
</blockquote></details>

Great, thanks!
___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.cc` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOooO3h30tJ4UeCRM8Y:-NOt_QqIDXoAkFqsPrzk:b-ggi05o) ([raw file](https://github.com/RobotLocomotion/drake/blob/990dc2b2ed432e081dcb293f965cf4180e68d48e/multibody/inverse_kinematics/point_to_line_distance_constraint.cc#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This actually checks if the user-supplied n_B2 is zero or not. The normalization is meaningful if n_B2 is non-zero.
</blockquote></details>

Oh, I see, thanks for the explanation.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

(I'd like to be sure that some of my recent commits didn't break this PR.)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform w/ minor BTW; will defer to ya for merging

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-:-NOtwckkCLlcJdf1CIBV:b6qq89w)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.h` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOtvPeE9HOPskefNYls:-NOtvPeE9HOPskefNYlt:bonea0f) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5477cf0f742d416813e5052a7c541b386353196/multibody/inverse_kinematics/point_to_line_distance_constraint.h#L39)):*
> ```objc
>    must be alive during the lifetime of this constraint.
>    @param frame_point The frame B1 to which the point P is attached.
>    @param p_B1P The position of point P measured and expressed in B1.
> ```

BTW "measured" seems redundant for a position-based quantities (point and line)?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18817)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[`multibody/inverse_kinematics/point_to_line_distance_constraint.h` line 39 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18817#-NOtvPeE9HOPskefNYls:-NOtyNUA21b4UbvWfPsD:b-kzsbwp) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5477cf0f742d416813e5052a7c541b386353196/multibody/inverse_kinematics/point_to_line_distance_constraint.h#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW "measured" seems redundant for a position-based quantities (point and line)?
</blockquote></details>

Derp. Nevermind :facepalm:

**Pull request merged**
