### PR TITLE
Update minimum bazel and java versions on Mac

### PR DESCRIPTION
**Pull request by jamiesnape**
Depends on #9296. Note that Bazel now bundles Java so we are no longer tied to Java 8, which is no longer updated  by Oracle (neither is Java 9).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9298)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri for feature-review

**Comment by jamiesnape** [comment]
Just noticed, I am missing a `tap-pin`.

**Comment by jamiesnape** [comment]
https://github.com/bazelbuild/homebrew-tap/issues/2 in case it is bug.

**Comment by jamiesnape** [comment]
Ideally we need this, though I can workaround fairly easily:

https://github.com/Homebrew/homebrew-bundle/issues/358

Maybe I just implement it myself.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
(The tap-pin may not be necessary soon: https://github.com/Homebrew/homebrew-core/pull/31396.)

**Comment by jamiesnape** [comment]
I think this might actually be breaking Jenkins itself. I need to investigate.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
Looks like the Bazel tap will either be short lived, or there will be a fork, so this is going to get very messy.

**Pull request merged**
