### PR TITLE
Make RobotPlanInterpolator output zero velocities and accelerations at the end of a plan

### PR DESCRIPTION
**Pull request by sammy-tri**
Add a midpoint to two-knot plans to achieve this effect.  Also reject
single-knot plans.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6510)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-:-KoJNznbM2g9zUOePp5v:blt30i2)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-KoJOfBnOR_7T065SmqQ:-KoJOfBoJoPK8FH6Gjda:b408kj) ([raw file](https://github.com/robotlocomotion/drake/blob/94ae4f083d0675acddf975bd9bfe4ebe5a894d01/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L213)):*
> ```cpp
>       }
> 
>       if (knots.size() == 2) {
> ```

i don't think you need to add another point. it should work with just 2. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-KoJOfBnOR_7T065SmqQ:-KoJQs57GKWXGrL6BWxS:bpvokcy) ([raw file](https://github.com/robotlocomotion/drake/blob/94ae4f083d0675acddf975bd9bfe4ebe5a894d01/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L213)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i don't think you need to add another point. it should work with just 2. 
</blockquote></details>

Removed.  Did that form of `Cubic()` always work with only two knot points?  I feel like the old FOH special case must have been there for a reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-KoJOfBnOR_7T065SmqQ:-KoJROxGd4mIJcgFtlSJ:b-59ys0o) ([raw file](https://github.com/robotlocomotion/drake/blob/94ae4f083d0675acddf975bd9bfe4ebe5a894d01/drake/examples/kuka_iiwa_arm/robot_plan_interpolator.cc#L213)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Removed.  Did that form of `Cubic()` always work with only two knot points?  I feel like the old FOH special case must have been there for a reason.
</blockquote></details>

nah, i changed it at some point. as long as you also specify the end point velocities + position, cubic works fine with 2 knots. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-:-KoJRaqBEZcl5rZ93_sf:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510)*

**Comment by sammy-tri** [comment]
+@soonho-tri for platform review (tomorrow's reviewer, I believe today's is out for the rest of the day)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-:-KoJUOUNLIY4Ka5SokXM:bj0yjsp)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6510#-:-KoNCa4Kf3ZIihEs6QQj:bnfp4nl)*

**Pull request merged**
