### PR TITLE
remove duplicate definition of constraint_tol.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix #7693

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7694)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@m-chaturvedi for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694#-:-L1zg2_4LJ9Kzz9C42lj:b-lcl2w6)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694#-:-L1zgMNPTYHHJOzT0vKX:b-cza96f)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694#-:-L1zlNIkp_DXR3yhLtrT:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694)*

**Comment by hongkai-dai** [comment]
+@soonho-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694#-:-L2-HjLzVOCo4SJC9LCA:b-vt9vbo)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7694#-:-L2-V4KA3MvWWYKvqVDc:bnfp4nl)*

**Pull request merged**
