### PR TITLE
math: Fix BsplineBasis<Expression>::operator==()

### PR DESCRIPTION
**Pull request by avalenzu**
Hotfix to avoid #13154.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13158)

### CODE REVIEW

**Comment by avalenzu** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by avalenzu** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
___
*[math/bspline_basis.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13158#-M6-qVjN6lw8trwHrP68:-M6-vspt3-3OsQaIx8Qz:bdxp8ce) ([raw file](https://github.com/robotlocomotion/drake/blob/2f2bd37f9bb43ab8f5be9f4a650c93d42b28ed93/math/bspline_basis.cc#L126)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW You're accumulating booleans despite the fact the first false is a sufficient exit condition. Try this on for size:


```c++
  if (this->order() != other.order() ||
      this->num_basis_functions() != other.num_basis_functions()) {
    return boolean<T>{false};
  }
  const int num_knots{num_basis_functions() + order()};
  for (int i = 0; i < num_knots; ++i) {
    const boolean<T> result(this->knots()[i] == other.knots()[i]);
    if (std::equal_to<boolean<T>>{}(result, boolean<T>{false})) {
      return boolean<T>{false};
    }
  }
  return boolean<T>{true};
```
</blockquote></details>

That's incorrect when `boolean<T>` is a Formula.  If it's a literal `false` then we can bail, but otherwise something like `x == y` is not a literal `true` so we can't round it up to "true".

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

FTR, `bazel test //math/... --config=asan` passed on my local mac (running macOS-10.15).

**Comment by jwnimmer-tri** [comment]
___
*[math/bspline_basis.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/13158#-M6-qVjN6lw8trwHrP68:-M6-yKWa4Lhidzu8MJGJ:bfq83im) ([raw file](https://github.com/robotlocomotion/drake/blob/2f2bd37f9bb43ab8f5be9f4a650c93d42b28ed93/math/bspline_basis.cc#L126)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think I see. What you're saying is that if the two are equal, we should return an expression that consists of the && of a bunch of Expressions that evaluate to `Formula<bool>` and not a literal. If they're *not* equal, a literal `false` is sufficient.

However, this function is inconsistent in how it returns `false`. Sometimes it's a literal and sometimes it's an Expression.
</blockquote></details>

I am not spotting the inconsistency?  Every return statement or returned object is of type `boolean<T>` AFAICT.

**Pull request merged**
