### PR TITLE
Moves SDF and URDF Parsers Into libdrakeMultibodyParsers

### LINKED ISSUE #4091: Move RBT parsing files into `drake/multibody/parsers`
Once #4058 is merged, move parsing files into their own directory.
What do you think @liangfok?

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4091.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4482)

### CODE REVIEW

**Comment by liangfok** [comment]
I'm marking this "do not review" until after all pre-merge CI tests pass.

**Comment by liangfok** [comment]
This PR passed all pre-merge checks. Thus:

+@amcastro-tri for feature review please.
+@david-german-tri for platform review please.

Thanks!

---

Review status: 0 of 115 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-:-KYrqg1cVyGn3CgBc2Sk:bbnlv6p)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 118 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-:-KYsrV-PVLsM93EeG5X2:b-s794vx)*

**Comment by david-german-tri** [comment]
Reviewed 129 of 138 files at r1, 8 of 8 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYsrcF76FnA5ITN4fNV:-KYsrcF76FnA5ITN4fNW:b-fqsjnr) ([raw file](https://github.com/robotlocomotion/drake/blob/a73572bc38b86baf4dd052bbab42679757c05f25/.gitmodules#L21)):*
> ```
> [submodule "externals/director"]
> 	path = externals/director
> 	url = https://github.com/liangfok/director.git
> ```

Is this intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYsrcF76FnA5ITN4fNV:-KYt-CoOq41k1E7uRyZ0:b-uo1v66) ([raw file](https://github.com/robotlocomotion/drake/blob/a73572bc38b86baf4dd052bbab42679757c05f25/.gitmodules#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

Yes, I will revert this change once https://github.com/RobotLocomotion/director/pull/401 is merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYsrcF76FnA5ITN4fNV:-KYt1xLRDgdpWhfcIHXA:bno1kzy) ([raw file](https://github.com/robotlocomotion/drake/blob/a73572bc38b86baf4dd052bbab42679757c05f25/.gitmodules#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, I will revert this change once https://github.com/RobotLocomotion/director/pull/401 is merged.
</blockquote></details>

I'd rather hold this PR until that's done, but I understand that would leave you at risk for merge conflicts.  What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitmodules, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYsrcF76FnA5ITN4fNV:-KYt7H5PxFiHUcKS5rmZ:b8khxvl) ([raw file](https://github.com/robotlocomotion/drake/blob/a73572bc38b86baf4dd052bbab42679757c05f25/.gitmodules#L21)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I'd rather hold this PR until that's done, but I understand that would leave you at risk for merge conflicts.  What do you think?
</blockquote></details>

OK about waiting for https://github.com/RobotLocomotion/director/pull/401 to be merged before this PR. I will prioritize that PR into Director, and apply the "do not merge" tag to this in the mean time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks and is thus ready for review.

**Comment by amcastro-tri** [comment]
Thank you @liangfok. One small BTW, :lgtm: 

---

Reviewed 97 of 141 files at r1, 2 of 8 files at r2, 2 of 5 files at r3, 23 of 41 files at r4, 20 of 26 files at r5.
Review status: 119 of 142 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/CMakeLists.txt, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYyRdR5EMOg3AbNTVJx:-KYyRdR6IGpxEFc6ZaTO:b-bmfqpf) ([raw file](https://github.com/robotlocomotion/drake/blob/c846dfae5712ceebcb98d75b8908e1e4f576d9f9/drake/multibody/parsers/CMakeLists.txt#L1)):*
> ```CMake
> add_library_with_exports(LIB_NAME drakeParsers SOURCE_FILES
> ```

BTW, these parsers are very RBT specific. Should this be named something more like `drakeRigidBodyTreeParsers`? or `drakeMultibodyParsers`?
Parsers for other systems (say sensor systems) would most likely be in another directory I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-:-KYyVD_rNeoznfuS5Ghd:b-l7obfb)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by liangfok** [comment]
Review status: 93 of 142 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/parsers/CMakeLists.txt, line 1 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-KYyRdR5EMOg3AbNTVJx:-KYyfiY4H5uLSrbjyZ8Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c846dfae5712ceebcb98d75b8908e1e4f576d9f9/drake/multibody/parsers/CMakeLists.txt#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, these parsers are very RBT specific. Should this be named something more like `drakeRigidBodyTreeParsers`? or `drakeMultibodyParsers`?
Parsers for other systems (say sensor systems) would most likely be in another directory I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 32 files at r6.
Review status: 94 of 142 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 30 of 32 files at r6, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4482#-:-KYz3gThiEztnwZZKVFP:bnfp4nl)*

**Pull request merged**
