### PR TITLE
Adding Specializations For AutoDiffScalar

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Ref:
https://github.com/RobotLocomotion/eigen-mirror/pull/2
https://github.com/RobotLocomotion/drake/issues/5815

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5930)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind-open-source please

**Comment by jamiesnape** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/CMakeLists.txt, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhRHsr9UwdWJ-Cd2z:-KifhRHsr9UwdWJ-Cd3-:b-vkp1jx) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/CMakeLists.txt#L55)):*
> ```CMake
>   dummy_value.h
>   eigen_autodiff_types.h
>   eigen_autodiff_limits.h
> ```

alphabetize?

---

*[drake/common/eigen_autodiff_limits.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhZP_jJvveHFZFYwp:-KifhZP_jJvveHFZFYwq:b-hvbrl4) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L3)):*
> ```objc
> #pragma once
> 
> #include <limits>
> ```

add new line

---

*[drake/common/eigen_autodiff_limits.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhtG-VzwkDtaSk1Bh:-KifhtG-VzwkDtaSk1Bi:b-kpmj7d) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L9)):*
> ```objc
> class numeric_limits<Eigen::AutoDiffScalar<T> > {
>  public:
>   static const bool is_specialized = true;
> ```

Is this really `true` if `std::numeric_limits<T::Scalar>::is_specialized = false`?

---

*[drake/common/eigen_autodiff_limits.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-Kifhimuo1iZcck8BWEc:-Kifhimuo1iZcck8BWEd:b-l041r5) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L11)):*
> ```objc
>   static const bool is_specialized = true;
>   static const bool is_signed =
>           std::numeric_limits<typename T::Scalar>::is_signed;
> ```

check indent (and for similar lines below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/eigen_autodiff_limits.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KififfRCDKfc06snfPp:-KififfRCDKfc06snfPq:b-yyf65d) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L16)):*
> ```objc
>   static const bool is_exact =
>           std::numeric_limits<typename T::Scalar>::is_exact;
>   static const int  radix =
> ```

remove extra space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by m-chaturvedi** [comment]
*[drake/common/eigen_autodiff_limits.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhZP_jJvveHFZFYwp:-Kifqciku2muj52pFY17:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L3)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by m-chaturvedi** [comment]
*[drake/common/eigen_autodiff_limits.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-Kifhimuo1iZcck8BWEc:-KifqfGkOX0WMogF1sQA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L11)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

check indent (and for similar lines below)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by m-chaturvedi** [comment]
*[drake/common/eigen_autodiff_limits.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KififfRCDKfc06snfPp:-Kifqg_4_xd8-PMId0L1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L16)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

remove extra space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by m-chaturvedi** [comment]
*[drake/common/CMakeLists.txt, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhRHsr9UwdWJ-Cd2z:-KifqjdSRdAXMBpuU7Vi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/CMakeLists.txt#L55)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

alphabetize?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by m-chaturvedi** [comment]
*[drake/common/eigen_autodiff_limits.h, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-KifhtG-VzwkDtaSk1Bh:-Kifqlg4EK-z5p7i7pv_:b-rj8vm6) ([raw file](https://github.com/robotlocomotion/drake/blob/dbd68c8e32c5816aaa1d82702f9d0142e33f539f/drake/common/eigen_autodiff_limits.h#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Is this really `true` if `std::numeric_limits<T::Scalar>::is_specialized = false`?
</blockquote></details>

I changed it to take it to `std::numeric_limits<T::Scalar>::is_specialized` but unless we change the code on Householder.h we need this to be true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930)*

**Comment by jamiesnape** [comment]
If I use `Eigen::AutoDiffScalar<Eigen::Vector2d>` is this an improvement?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-Kiftqu_K-MrSzYLxtKF:b-30odkf)*

**Comment by m-chaturvedi** [comment]
If by "this" you mean the whole specialization thing.  Yes, it does.  The following seems to produce valgrind conditional jump without our specialization:
https://gist.github.com/m-chaturvedi/8f7568cc2eb27c5896a7791eb6c8fd1d

I just checked it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-KifyIoBztUMpm5PVmho:b-b5x0xg)*

**Comment by jamiesnape** [comment]
Where is the specialization of `std::numeric_limits` for `Eigen::Vector2d` defined?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-Kig-isqaUAX1TifT9uh:b-3933wq)*

**Comment by jamiesnape** [comment]
Never mind. I missed the `T::Scalar`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-Kig0YSICiqHC_QJua1I:bw7wfke)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-Kig0e0vq-b3_SgmMWSF:bnfp4nl)*

**Comment by ggould-tri** [comment]
Nice solution to the problem. :lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5930#-:-KijYzVtEct_aYWq-P7g:b-vx1hqm)*

**Pull request merged**
