### PR TITLE
Document DecomposePositiveQuadraticForm function.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Add a numerical example, also clarify the number of rows in the return.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15363)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for both reviews please, thanks!

resolves #15361 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15363#-:-MeH4EI49nrLPz_kzeXi:b-pnfv9u)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15363)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[math/quadratic_form.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15363#-MeIG3572xaVKzFA6Rv_:-MeIG3572xaVKzFA6Rva:baolbhg) ([raw file](https://github.com/robotlocomotion/drake/blob/42afff8813ad43e597ea94463991a3d41a1f9098/math/quadratic_form.h#L33)):*
> ```objc
>  * where
>  * RᵀR = Q
>  * Rᵀd = b / 2
> ```

can we add a line here about c?  I think that's where the confusion started for me.  If you can say that d[-1] = c - d[:n]^Td[:n] or something, that would have basically solved the problem for me.  
___
*[math/quadratic_form.h, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15363#-MeIGc1R7Cf3ks4VrrTj:-MeIGc1R7Cf3ks4VrrTk:bu1e2l0) ([raw file](https://github.com/robotlocomotion/drake/blob/42afff8813ad43e597ea94463991a3d41a1f9098/math/quadratic_form.h#L47)):*
> ```objc
>  * ⌈Q     b/2⌉
>  * ⌊bᵀ/2    c⌋
>  * </pre>
> ```

if Q is full rank and b=0, c=0, do you really return R the same size as Q?  based on your example x² + 2x + 1 below, it seems that you do.  cool.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15363)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[math/quadratic_form.h, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15363#-MeIG3572xaVKzFA6Rv_:-MeILf613AKVI_IoAnVu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/42afff8813ad43e597ea94463991a3d41a1f9098/math/quadratic_form.h#L33)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

can we add a line here about c?  I think that's where the confusion started for me.  If you can say that d[-1] = c - d[:n]^Td[:n] or something, that would have basically solved the problem for me.  
</blockquote></details>

Done.
___
*[math/quadratic_form.h, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15363#-MeIGc1R7Cf3ks4VrrTj:-MeILkwd1y69aln7Rchq:b-q18fd7) ([raw file](https://github.com/robotlocomotion/drake/blob/42afff8813ad43e597ea94463991a3d41a1f9098/math/quadratic_form.h#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

if Q is full rank and b=0, c=0, do you really return R the same size as Q?  based on your example x² + 2x + 1 below, it seems that you do.  cool.
</blockquote></details>

Done. It is actually better, it returns R such that R.rows() = Q.rank() when b and c = 0. So when Q is positive semidefinite but with some eigen values equal to 0, R can have less rows than Q. The code tries to return the "minimal" size of `R`. (I added another test to emphasize this).

**Review by RussTedrake — COMMENTED** [review]
:lgtm: both.  thanks!

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15363#-:-MeIWkAF7lkpfDQG99tm:b-qgciva)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[math/quadratic_form.h, line 43 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15363#-MeIWTye2dhDhSIy4M30:-MeIWTye2dhDhSIy4M31:b-i53hci) ([raw file](https://github.com/robotlocomotion/drake/blob/0a5d6b7d7c44a466050447f0fd691ea9f339bac4/math/quadratic_form.h#L43)):*
> ```objc
>  * ⌊bᵀ/2    c⌋
>  * </pre>
>  * being positive semidefinite.
> ```

nit: "being" => "to be"

**Pull request merged**
