### PR TITLE
PositionConstraint can update lower and upper bounds

### PR DESCRIPTION
**Pull request by hongkai-dai**
As requested in stackoverflow question https://stackoverflow.com/questions/71157985/how-to-update-bound-of-positionconstraint

I will add the constraint to update other kinematic constraints, these constraints are more complicated as their upper and lower bounds are computed from the kinematic parameter (like angle tolerance), so instead of using UpdateLower/UpperConstraint function, I will probably add `UpdateAngleTolerance` for example.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks! (No rush).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631#-:-MwIJSKaEu82hDzBg3RB:blz89u6)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(priority: low) :lgtm: feature.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631#-:-MwIt81cBQsCxH2_JvXD:b-okwaqb)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16631#-MwItv8O6p-Bknixd3ca:-MwItv8P1I60x2xPTeAt:bp6qmk4) ([raw file](https://github.com/robotlocomotion/drake/blob/8f17cf7037a4eba59603552cac282ce74316ddd2/bindings/pydrake/multibody/inverse_kinematics_py.cc#L340)):*
> ```cpp
>             py::keep_alive<1, 8>(), ctor_doc_ad)
>         .def("set_bounds", &Class::set_bounds, py::arg("lower_bound"),
>             py::arg("upper_bound"))
> ```

The existing binding for `LinearConstraint::set_bounds` is inconsistent about whether these should be named "lower_bound" or "new_lb":  the documentation says "lower_bound" but the kwarg name is "new_lb".  (Ditto for upper.)

https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.LinearConstraint.set_bounds

Now might be a good time to choose which argument name convention you'd like to use from now on, and make sure the new binding here obeys that convention.

If you think "lower_bound" is correct, then maybe add a TODO to the LinearConstraint binding that it should be updated to match.  If you think "new_lb" is correct, they you can adjust this PR to match.
___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16631#-MwIv7O33rELejS8wnwH:-MwIv7O49p8olKz2Y1BA:bcjhwut) ([raw file](https://github.com/robotlocomotion/drake/blob/8f17cf7037a4eba59603552cac282ce74316ddd2/bindings/pydrake/multibody/inverse_kinematics_py.cc#L342)):*
> ```cpp
>             py::arg("upper_bound"))
>         .def("UpdateLowerBound", &Class::UpdateLowerBound, py::arg("new_lb"))
>         .def("UpdateUpperBound", &Class::UpdateUpperBound, py::arg("new_ub"));
> ```

All three new bindings here are missing pydrake docstrings.  Since the C++ code is inheriting the functions from the base class, I believe you'll need to use to the base class's docstring constant here as well.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 340 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16631#-MwItv8O6p-Bknixd3ca:-MwK4hxR8Yt7peipKLWA:b-hhg5cn) ([raw file](https://github.com/robotlocomotion/drake/blob/8f17cf7037a4eba59603552cac282ce74316ddd2/bindings/pydrake/multibody/inverse_kinematics_py.cc#L340)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The existing binding for `LinearConstraint::set_bounds` is inconsistent about whether these should be named "lower_bound" or "new_lb":  the documentation says "lower_bound" but the kwarg name is "new_lb".  (Ditto for upper.)

https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.LinearConstraint.set_bounds

Now might be a good time to choose which argument name convention you'd like to use from now on, and make sure the new binding here obeys that convention.

If you think "lower_bound" is correct, then maybe add a TODO to the LinearConstraint binding that it should be updated to match.  If you think "new_lb" is correct, they you can adjust this PR to match.
</blockquote></details>

Good call.

1. In the python binding for PyFunctionConstraint::set_bounds we use lower_bound and upper_bound as kwargs.
2. In LinearConstraint::set_bounds we use new_lb and new_ub as kwargs.
3. In all UpdateLowerBound and UpdateUpperBound we use new_lb and new_ub as kwargs.

I think it is better to be consistent and use new_lb and new_ub everywhere.
___
*[bindings/pydrake/multibody/inverse_kinematics_py.cc, line 342 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16631#-MwIv7O33rELejS8wnwH:-MwK808k06T692bQMzF-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8f17cf7037a4eba59603552cac282ce74316ddd2/bindings/pydrake/multibody/inverse_kinematics_py.cc#L342)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

All three new bindings here are missing pydrake docstrings.  Since the C++ code is inheriting the functions from the base class, I believe you'll need to use to the base class's docstring constant here as well.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631#-:-MwKHycE6wBtVYDiA548:b2xa7ij)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16631#-:-MwRfyfw0YNzqSqADbQQ:bcpz082)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1658 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16631#-MwRfdyz6w-_R7yWGe4-:-MwRfdyz6w-_R7yWGe40:b-ii4urr) ([raw file](https://github.com/robotlocomotion/drake/blob/fbc8271a9842f6a078429505f81ae2ad6745b308/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1658)):*
> ```cpp
>       .def("UpdateUpperBound", &PyFunctionConstraint::UpdateUpperBound,
>           py::arg("new_ub"), "Update the upper bound of the constraint.")
>       .def("set_bounds", &PyFunctionConstraint::set_bounds,
> ```

BTW For deprecating binding-only kwarg rename:

https://github.com/RobotLocomotion/drake/blob/7e50c5d9c51e4c7373d393916857e8f278c678f2/bindings/pydrake/common/test/deprecation_example/cc_module_py.cc#L92-L109

**Pull request merged**
