### PR TITLE
Add explicit nullptr checks to assertions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Refer to #15513 for the motivations.  While "throw" vs "abort" are slightly different semantics in terms of error message, I think the reasoning shown there applies sufficiently well to ASSERT and DEMAND.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15574)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15574#-:-MgQTl5rCEF3iNuAr3KC:b-l9yj1x)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a typo, a passing whinge, and some missing examples.

Huge congratulations on catching the `foo.get()` cases -- my regex would've missed those.

> Reviewed 71 of 71 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15574#-:-MgQmwcw0VsCXF7oEGQ3:b-af7urd)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15574#-MgQlQ_Q9P7I3lAhwfdw:-MgQlQ_Q9P7I3lAhwfdx:b-dizwoi) (no related file):*
I did my own search and found two additional cases:

  - scene_graph.h:l632 - example code in comment shows `DRAKE_DEMAND(old_props);`
  - gurobi_solver.cc:l1039 `DRAKE_DEMAND(model_env);`

---
___
*[common/yaml/yaml_read_archive.cc, line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15574#-MgQjxG87Jv_hw3gp706:-MgQjxG87Jv_hw3gp707:b4tke9i) ([raw file](https://github.com/robotlocomotion/drake/blob/712bebc306b202fbebc3909a87b0f92026924765/common/yaml/yaml_read_archive.cc#L204)):*
> ```cpp
> 
> void YamlReadArchive::PrintVisitNameType(std::ostream& s) const {
>   if (!debug_visit_name_) {
> ```

BTW I completely subscribe to the position that *error* messages should be communicative. And modifying the tests in asserts/demands is the perfect low bar. It is a bit disappointing to see tests on pointers in such close proximity be treated inconsistently.  :(

(And I'm not suggesting this be touched in this PR, or even that it's a fight I'd want to have.)
___
*[systems/framework/system.h, line 1642 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15574#-MgQmmXq17fhmGWuwpK-:-MgQmmXq17fhmGWuwpK0:b-cxfrtj) ([raw file](https://github.com/robotlocomotion/drake/blob/712bebc306b202fbebc3909a87b0f92026924765/systems/framework/system.h#L1642)):*
> ```objc
> 
>   EventCollection<PublishEvent<T>>& get_mutable_forced_publish_events() {
>     DRAKE_DEMAND(forced_publish_events_  != nullptr);
> ```

nit: extra white space.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15574)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15574#-MgQlQ_Q9P7I3lAhwfdw:-MgRCu1HELmWV8Pq9LzA:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I did my own search and found two additional cases:

  - scene_graph.h:l632 - example code in comment shows `DRAKE_DEMAND(old_props);`
  - gurobi_solver.cc:l1039 `DRAKE_DEMAND(model_env);`
</blockquote></details>

Done.

---
___
*[common/yaml/yaml_read_archive.cc, line 204 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15574#-MgQjxG87Jv_hw3gp706:-MgRCfCN9qRXM-IvXrlB:b-af54ae) ([raw file](https://github.com/robotlocomotion/drake/blob/712bebc306b202fbebc3909a87b0f92026924765/common/yaml/yaml_read_archive.cc#L204)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I completely subscribe to the position that *error* messages should be communicative. And modifying the tests in asserts/demands is the perfect low bar. It is a bit disappointing to see tests on pointers in such close proximity be treated inconsistently.  :(

(And I'm not suggesting this be touched in this PR, or even that it's a fight I'd want to have.)
</blockquote></details>

OK I might as well fix this one since you mentioned it, and it's "my" code.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15574)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
