### PR TITLE
[symbolic] Support half-angle formulas in sin/cos substitution.

### PR DESCRIPTION
**Pull request by RussTedrake**
+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)

### CODE REVIEW

**Comment by RussTedrake** [comment]
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N34PlUU5JPgdCULtmo4:b-dhj6dn) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
> ```objc
> */
> Expression Substitute(const Expression& e, const SinCosSubstitution& subs,
>                       bool half_angle = false);
> ```

We should decide if this is the right API.  It does not provide the flexibility to use half-angle for some trig variables, but not for others (I've not come across a case where that is needed yet).  And I don't want to corrupt the interprettability of SinCosSubsitution.  But this was the cleanest implementation that handles all of my use cases so far.

**Comment by RussTedrake** [comment]
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N34fyBZ2u5wnk__pqTc:bhnh2er) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

We should decide if this is the right API.  It does not provide the flexibility to use half-angle for some trig variables, but not for others (I've not come across a case where that is needed yet).  And I don't want to corrupt the interprettability of SinCosSubsitution.  But this was the cleanest implementation that handles all of my use cases so far.  
</blockquote></details>

Reflecting on this a little more... if this is sufficient for your use cases, also, @hongkai-dai , then I think it's a pretty good choice for now.  It will not be hard to support this entry point if we make a more expressive API later.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N35F0ON5iPZ8aydHhm9:b-71c453) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Reflecting on this a little more... if this is sufficient for your use cases, also, @hongkai-dai , then I think it's a pretty good choice for now.  It will not be hard to support this entry point if we make a more expressive API later.
</blockquote></details>

Agreed. I think we could support at least 3 cases in the future
1. sin(theta) -> s, cos(theta) -> c
2. Half angle formulation sin(theta/2)->s, cos(theta/2) -> c
3. Stereographic projection sin(theta) -> 2t/(1+t^2), cos(theta) -> (1-t^2)/(1+t^2)

We could add some enum class in the future
```cc
enum class TrigPolyMethod {
  kStandard,
  kHalfAngle,
  kStereographic,
}
```
The stereographic case is tricky as we won't use SinCosSubstitution (with `s` and `c`) any more, but will use the new variable `t`.

Also I think there is ambiguity in the half angle case. There are two approaches to replace cos(theta) with half angle
1. cos(theta) = 1 - 2sin(theta/2)², as used in this PR
2. cos(theta) = 2cos(theta/2)² - 1.

So maybe for the halfangle case we need to support two different substitution in the future? Namley `kHalfAngleSin` (which uses cos(theta) = 1-2sin(theta/2)²) and `kHalfAngleCos` (which uses cos(theta) = 2cos(theta/2)²-1).

What do you think if we add this enum class for now (but only has kStandard and kHalfAngleSin), it probably makes it easier to extend to other methods in the future?

**Comment by RussTedrake** [comment]
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N35Wlwv9z-osOoPxYAN:b-mnloqa) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Agreed. I think we could support at least 3 cases in the future
1. sin(theta) -> s, cos(theta) -> c
2. Half angle formulation sin(theta/2)->s, cos(theta/2) -> c
3. Stereographic projection sin(theta) -> 2t/(1+t^2), cos(theta) -> (1-t^2)/(1+t^2)

We could add some enum class in the future
```cc
enum class TrigPolyMethod {
  kStandard,
  kHalfAngle,
  kStereographic,
}
```
The stereographic case is tricky as we won't use SinCosSubstitution (with `s` and `c`) any more, but will use the new variable `t`.

Also I think there is ambiguity in the half angle case. There are two approaches to replace cos(theta) with half angle
1. cos(theta) = 1 - 2sin(theta/2)², as used in this PR
2. cos(theta) = 2cos(theta/2)² - 1.

So maybe for the halfangle case we need to support two different substitution in the future? Namley `kHalfAngleSin` (which uses cos(theta) = 1-2sin(theta/2)²) and `kHalfAngleCos` (which uses cos(theta) = 2cos(theta/2)²-1).

What do you think if we add this enum class for now (but only has kStandard and kHalfAngleSin), it probably makes it easier to extend to other methods in the future?
</blockquote></details>

Because of this different (it takes a variable t instead of s and c), I think the sterographic projection would be similar, but would probably justify a separate visitor class?  Or at least a separate entry point.

Do you really think that kHalfAngleSin and kHalfAngleCos is worth different entry points?  (We could also do c^2 - s^2, or ...)?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N35Y6fv5N6jJhzFsjhu:b695eq5) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
> Because of this different (it takes a variable t instead of s and c), I think the sterographic projection would be similar, but would probably justify a separate visitor class? Or at least a separate entry point.

Agreed, probably a different visitor class is better, as stereographic projection would produce rational functions instead of polynomials.

> Do you really think that kHalfAngleSin and kHalfAngleCos is worth different entry points? (We could also do c^2 - s^2, or ...)?

I feel for the half angle case there are so many different combination on replacing cos(theta), and it is not clear to me that we will always use cos(theta) = 1 - 2sin(theta/2)^2. So we should be at least clear in the public documentation about which one we choose. And I am inclined to provide different options in the enum class to make it easier for future extension, maybe we do
```cc
enum class TrigPolyMethod {
  kStandard,
  kHalfAngleSin,
};
```
for now. What do you think?

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`common/symbolic_trigonometric_polynomial.cc` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N36dqeV37_ExQRzxOas:-N36dqeV37_ExQRzxOat:b-5z6jha) ([raw file](https://github.com/robotlocomotion/drake/blob/16c5442b7572210de56809de3e34a5f923035e79/common/symbolic_trigonometric_polynomial.cc#L140)):*
> ```cpp
>           return -iter->second.s;
>         }
>         // TODO(russt): Handle the cases where c is an odd multiple of 0.5.
> ```

If half_angle_ = true, and e = 1 * x or 2 * x, namely c is an even number of 0.5, then it seems we just ignore it here?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`common/symbolic_trigonometric_polynomial.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N34PlUU5JPgdCULtmo3:-N43f_fN7xh-6LUJM2zY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/557a6a3466d84bf6c2dd85b17f0cc86796e3dd96/common/symbolic_trigonometric_polynomial.h#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> Because of this different (it takes a variable t instead of s and c), I think the sterographic projection would be similar, but would probably justify a separate visitor class? Or at least a separate entry point.

Agreed, probably a different visitor class is better, as stereographic projection would produce rational functions instead of polynomials.

> Do you really think that kHalfAngleSin and kHalfAngleCos is worth different entry points? (We could also do c^2 - s^2, or ...)?

I feel for the half angle case there are so many different combination on replacing cos(theta), and it is not clear to me that we will always use cos(theta) = 1 - 2sin(theta/2)^2. So we should be at least clear in the public documentation about which one we choose. And I am inclined to provide different options in the enum class to make it easier for future extension, maybe we do
```cc
enum class TrigPolyMethod {
  kStandard,
  kHalfAngleSin,
};
```
for now. What do you think?

</blockquote></details>

Done.
___
*[`common/symbolic_trigonometric_polynomial.cc` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N36dqeV37_ExQRzxOas:-N43h2bWDr_-TuAOPwLx:bnlpqmj) ([raw file](https://github.com/robotlocomotion/drake/blob/16c5442b7572210de56809de3e34a5f923035e79/common/symbolic_trigonometric_polynomial.cc#L140)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If half_angle_ = true, and e = 1 * x or 2 * x, namely c is an even number of 0.5, then it seems we just ignore it here?
</blockquote></details>

That's not true; those cases are supported. I've added an additional test to prove it.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[`common/symbolic_trigonometric_polynomial.h` line 30 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N44mkuU0iFTxc5Kx9Uy:-N44mkuV69bx16makkT1:blhyhjb) ([raw file](https://github.com/robotlocomotion/drake/blob/77dcb66c6d8dc34876f59be3905ff3a20e64ab62/common/symbolic_trigonometric_polynomial.h#L30)):*
> ```objc
>   SinCos(Variable s_var, Variable c_var,
>          SinCosSubstitutionType type = SinCosSubstitutionType::kAngle)
>       : s(std::move(s_var)), c(std::move(c_var)), type(type) {}
> ```

CI fails here, consider using a different variable name other than `type` to avoid shadowing the variable?
___
*[`common/symbolic_trigonometric_polynomial.cc` line 140 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N36dqeV37_ExQRzxOas:-N44lNCkECgmYJ5IuU3E:b-34n42q) ([raw file](https://github.com/robotlocomotion/drake/blob/16c5442b7572210de56809de3e34a5f923035e79/common/symbolic_trigonometric_polynomial.cc#L140)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

That's not true; those cases are supported. I've added an additional test to prove it.  
</blockquote></details>

I see, I somehow missed that you used the multi-angle formula below. Retract.

**Comment by RussTedrake** [comment]
*[`common/symbolic_trigonometric_polynomial.h` line 30 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17282#-N44mkuU0iFTxc5Kx9Uy:-N46hr3e1x2jLBR9HD8b:b-jld7h7) ([raw file](https://github.com/robotlocomotion/drake/blob/77dcb66c6d8dc34876f59be3905ff3a20e64ab62/common/symbolic_trigonometric_polynomial.h#L30)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

CI fails here, consider using a different variable name other than `type` to avoid shadowing the variable?
</blockquote></details>

Done.  This gets me every time.  Everything I read says this syntax should be legal (and works fine on clang), and I don't like to mess up the name for the class variable nor the constructor (because they appear in the python bindings).  I think the underscore is an appropriate compromise.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ericcousineau-tri for platform review please, thanks!

> Reviewed 1 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17282#-:-N4879fe9sOESjGbpug6:bfacy11)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
