### PR TITLE
Fix LCM types includes

### LINKED ISSUE #3351: Can't include bot_core LCM types that refer to other bot_core LCM types
I'll use `systems/plants/test/lidarTest.cpp` as an example. In this file, we include `planar_lidar_t.hpp` as follows:
```C++
#include "lcmtypes/bot_core/planar_lidar_t.hpp"
```

This works. However, if I pattern match this to include `position_3d_t.hpp` right below, using
```C++
#include "lcmtypes/bot_core/position_3d_t.hpp"
```
then I get the following error:
```
In file included from /Users/twan/code/drake-distro/drake/systems/plants/test/lidarTest.cpp:9:
/Users/twan/code/drake-distro/build/install/include/lcmtypes/bot_core/position_3d_t.hpp:12:10: fatal error: 'bot_core/vector_3d_t.hpp' file not found
#include "bot_core/vector_3d_t.hpp"
         ^
1 error generated.
make[5]: *** [systems/plants/test/CMakeFiles/testLidar.dir/lidarTest.cpp.o] Error 1
make[4]: *** [systems/plants/test/CMakeFiles/testLidar.dir/all] Error 2
```

This is because `position_3d_t` has a `vector_3d_t` field, and (generated) bot_core LCM type hpp files include other bot_core LCM types as
```C++
#include "bot_core/$SOME_TYPE.hpp"
```

Please advise on the right way to fix this. This is currently a blocking issue for me.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update bot_core_lcmtypes, and actually look for it, so we can leverage it's interface include directories for consumers of the C++ bindings. Add an `INTERFACE` library with interface include directories for Drake's own C++ LCM type bindings. Use this instead of `add_dependencies` for consumers of the same (the `INTERFACE` library now propagates the dependency on the bindings being generated before trying to build code that uses them). Remove addition of drake's LCM types include directory as a global include. Fix a couple of spots where someone was using LCMSystem headers but not linking to the library (resulting in said consumers being unable to find headers). Normalize inclusion of LCM type headers to omit `lcmtypes/` in the `#include`d header name.

Fixes #3351.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3550)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
The merge conflicts look sufficiently non-trivial that I'm not going to try to resolve them this instant (hopefully tomorrow); meanwhile, posting this anyway to invite comments.

Possibly @tkoolen for feature review?

**Comment by tkoolen** [comment]
Sure, thanks for taking care of this.

**Comment by tkoolen** [comment]
This all looks good to me, no comments. I'll take one more look after merging.

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3550#-:-KSHgFt0cNz8DPwPT-lV:b4pzv3n)*

**Comment by mwoehlke-kitware** [comment]
> I'll take one more look after merging.

Needs merge conflicts resolved first...

**Comment by tkoolen** [comment]
Sorry, that's what I meant.

**Comment by mwoehlke-kitware** [comment]
@tkoolen for feature (re)review, @ggould-tri for platform review... as always, feel free to pass the ball as works best...

**Comment by tkoolen** [comment]
Looks good to me. :lgtm:

---

Review status: 20 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3550#-:-KSNVHW8MIOAiVvm5suz:bluty4p)*

**Comment by david-german-tri** [comment]
+@david-german-tri, -@ggould-tri 

---

Review status: 20 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3550#-:-KSNWJ3-MilIyuS0kAcF:blqw0li)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

---

Review status: 20 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3550#-:-KSNXqs8elUnS4yIQuIz:b-2uekdi)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 20 of 40 files at r1, 16 of 24 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3550#-:-KSNZHKFuz7NwdCmzOou:bnfp4nl)*

**Pull request merged**
