### PR TITLE
[systems/lcm] Use shared_ptr for LCM serializers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19250.  Undoes #15394.

- [x] Anzu CI passed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI do you have time for feature review?  (Or at least, design review?)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature + design!
+@sherm1 for platform review, please!

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-:-NV4xi3bAoP72BFu6_su:b-nfuxvf)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-NV4xIiT9qYA3Lmc1Nip):*
BTW I'm not sure if it'd be completely useless, but yeah, I can't think of a workflow that would merit it for now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-NV4xIiT9qYA3Lmc1Nip):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I'm not sure if it'd be completely useless, but yeah, I can't think of a workflow that would merit it for now.
</blockquote></details>

I should amend the commit message when we merge.

My main reason to deprecate is that our "is cloneable" signature `class Foo { virtual unique_ptr<Foo> Clone() = 0; }` is extremely difficult to override correctly in Python, where unique ownership requires dangerous games with identifying shared_ptr use_count == 1 and then stealing the object.

So the reasoning for removal is more like "very little value + very high complexity".

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending one request for clarification.

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-:-NV5PJYUDJmQ2BLt4BoV:b-16ef3z)* status: 2 unresolved discussions

___
*[`systems/lcm/serializer.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-NV5N2hl45dbR7H8sFwM:-NV5N2hl45dbR7H8sFwN:b2rwq7p) ([raw file](https://github.com/RobotLocomotion/drake/blob/b81a91c2f7908d9d75f0bfafcda2feabcc8b4114/systems/lcm/serializer.h#L20)):*
> ```objc
>  * %SerializerInterface translates between LCM message bytes and
>  * drake::AbstractValue objects that contain LCM messages, e.g., a
>  * Value<lcmt_drake_signal>.  All `const` methods should be threadsafe.
> ```

minor: not clear how to interpret this sentence. Is it an instruction to developers about how to write const methods ("_must be_ threadsafe") or a promise to users of the class ("const methods _are_ threadsafe")? Please clarify.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369)* status: 2 unresolved discussions

___
*[`systems/lcm/serializer.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-NV5N2hl45dbR7H8sFwM:-NV5nHQH17kzwnx-1eva:bnm9w0r) ([raw file](https://github.com/RobotLocomotion/drake/blob/b81a91c2f7908d9d75f0bfafcda2feabcc8b4114/systems/lcm/serializer.h#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not clear how to interpret this sentence. Is it an instruction to developers about how to write const methods ("_must be_ threadsafe") or a promise to users of the class ("const methods _are_ threadsafe")? Please clarify.
</blockquote></details>

Hmm, it's both.  I tried some working that is hopefully better.  WDYT?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19369)* status: 1 unresolved discussion

___
*[`systems/lcm/serializer.h` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19369#-NV5N2hl45dbR7H8sFwM:-NV5qVupCQl7UMRIiFUT:b-m5kawi) ([raw file](https://github.com/RobotLocomotion/drake/blob/b81a91c2f7908d9d75f0bfafcda2feabcc8b4114/systems/lcm/serializer.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, it's both.  I tried some working that is hopefully better.  WDYT?
</blockquote></details>

This is good, thanks. The contract term for the user is all you need -- developers are automatically bound to deliver it.

**Pull request merged**
