### PR TITLE
Drop PODS include dir from build tree

### PR DESCRIPTION
**Pull request by bradking**
We no longer require a PODS layout in the build tree (it was broken anyway because we were not adding the export headers to it).  Replace use of the `pods_install_headers` function with a direct invocation of `install(FILES)`.  This avoids re-running CMake every time a header is changed.

Closes: #2307

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3416)

### CODE REVIEW

**Comment by bradking** [comment]
Assigning to @mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
Looks like @mwoehlke-kitware is on vacation. :lgtm: assuming the outstanding build passes.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3416#-:-KRTtUsBS3wTMEqOw5ci:b3hiwd3)*

**Comment by bradking** [comment]
@jamiesnape thanks.  It looks like the builds passed.  Assigning to @david-german-tri for platform review and integration.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3416#-:-KRU5RPQgV_K2px4cI8k:bnfp4nl)*

**Pull request merged**
