### PR TITLE
Fix BUILD file to track master

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The Symbolic changes to build system needed an update in Bazel.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4156)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/BUILD, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoIB0ENDw6S4X7oS9S:-KWoIB0Fqb1SXgco81RC:b-cjodqw) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L31)):*
> ```Python
>     linkstatic = 1)
> 
> # The generic base for all specific ScalarType-providing libraries.
> ```

I don't understand what this comment is trying to say.

---

*[drake/common/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoINjke6EPiXoVoNQH:-KWoINjke6EPiXoVoNQI:bqs3hj7) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L36)):*
> ```Python
>     name = "scalar_type_common",
>     hdrs = [
>         "cond.h",
> ```

These two things seem only loosely related to each other; why not two separate targets?

---

*[drake/common/BUILD, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoHoKTjrphFEfLecZV:-KWoHoKTjrphFEfLecZW:bh0i9jt) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L43)):*
> ```Python
> 
> # Drake's specific ScalarType-providing libraries.
> DEPS = [":common", ":scalar_type_common"]
> ```

The evolving-DEPS paradigm is kind of hard to read.  Consider naming this SCALARTYPE_DEPS or similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4156)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4156)*

**Comment by jwnimmer-tri** [comment]
PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/BUILD, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoIB0ENDw6S4X7oS9S:-KWrlGAsfo-RX_C_cmDH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L31)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I don't understand what this comment is trying to say.
</details>
Done.

---

*[drake/common/BUILD, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoINjke6EPiXoVoNQH:-KWrlHLXc_8CNjv0e8dq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L36)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> These two things seem only loosely related to each other; why not two separate targets?
</details>
Done.

---

*[drake/common/BUILD, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-KWoHoKTjrphFEfLecZV:-KWrlI8k92oxBsNcxRxa:b-damazd) ([raw file](https://github.com/robotlocomotion/drake/blob/ccb06627fb91b8d86bd05035a786fa0897133472/drake/common/BUILD#L43)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> The evolving-DEPS paradigm is kind of hard to read.  Consider naming this SCALARTYPE_DEPS or similar.
</details>
Yeah.  For `common/` I think the DEPS pattern is net-negative value.  Removed entirely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-:-KWrlWJ8J0Y7xVeXDqxD:b-83330m)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4156#-:-KWrxJah1ifyf2BGCvkL:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4156)*

**Comment by jwnimmer-tri** [comment]
Using override-merge on Bazel-only changes, without waiting for MATLAB™.

**Pull request merged**
