### PR TITLE
[SAP] ContactProblemGraph provides participating cliques

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR updates ContactProblemGraph so that it can provide the permutation to participating cliques.

Towards landing the [SapSolver](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in https://github.com/RobotLocomotion/drake/pull/16543.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-Mx5ZDXp3jLBKi828-xp:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: with some minor suggestions. +@sammy-tri for platform review, please.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-MxAVXia8mJQSwVLXVw1:b-pcwhwd)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @sammy-tri)

___
*[multibody/contact_solvers/sap/partial_permutation.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16694#-MxATkYP-pDlaBE-9gdl:-MxATkYP-pDlaBE-9gdm:b18q52t) ([raw file](https://github.com/robotlocomotion/drake/blob/df1906ac1467309573fd01b4779d2c8aa11b83c5/multibody/contact_solvers/sap/partial_permutation.h#L67)):*
> ```objc
> 
>   // If participates(i) = false, defines P(i) = permuted_domain_size() and
>   // further increases the permuted domain size.
> ```

nit: Maybe a small statement here like "If participates(i) = true, does nothing and returns P(i)". I know it is stated in the `@returns` statement, but my first thought was that a call `push(i)` on an already participating index `i` would probably fail instead of quietly doing nothing.

Another thing that could help is renaming the method `maybe_push()` or something like that to make sure the behavior is upfront.
___
*[multibody/contact_solvers/sap/partial_permutation.h, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16694#-MxATbs4B2MD-OoLKFkj:-MxATbs4B2MD-OoLKFkk:b-nc9x3b) ([raw file](https://github.com/robotlocomotion/drake/blob/df1906ac1467309573fd01b4779d2c8aa11b83c5/multibody/contact_solvers/sap/partial_permutation.h#L69)):*
> ```objc
>   // further increases the permuted domain size.
>   // @throws exception if i is not in [0, domain_size()).
>   // @returns P(i), ie. permuted_index(i).
> ```

nit: "ie." -> "i.e."

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-MxBoqDC32sWfA3TODZn:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Review by sammy-tri — COMMENTED** [review]
I'm a little unclear if the original two commits were supposed to be curated into two commits or intended to be squashed.  I'm going to assume squash since the review fixes are in a 3rd commit.

+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-MxBp9Hu43GLtreW7dQO:bp1q60o)* status: missing label for release notes (waiting on @amcastro-tri)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: none) because all changes are in the internal namespace

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-MxBpZxXC1UF2WbkzJ6G:b-ilcldn)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Sorry about the commit history @sammy-tri. With this PR train I keep my commits till the very last minute so I can easily cherry-pick them on top of my dev branch (I of course do have them locally).
I've been squashing them all before merging so you did what I do anyways. Thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16694#-:-MxF7IiA7v5aua4PsWg1:b-dg4ti8)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn

**Pull request merged**
