### PR TITLE
Option to Leverage Axis-Aligned Bounding Boxes when Computing Pairwise Intersections for GCS

### PR DESCRIPTION
**Pull request by cohnt**
By computing the axis-aligned bounding box of each set, we can confirm two sets to be disjoint without having to solve an optimization problem. Given a large graph of convex sets, the computational cost of constructing these bounding boxes may be outweighed by the time savings of solving fewer intersection checks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593)

### CODE REVIEW

**Comment by cohnt** [comment]
+@sadraddini for feature review?

**Review by sadraddini — COMMENTED** [review]
Checkpoint. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1J0Tkb776fJ-b5DhDf:b-3k4q3l)* status: 4 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1Izx4rAbCCZK07VDQL:-O1Izx4rAbCCZK07VDQM:b-pqz1oq) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L146)):*
> ```objc
> @param continuous_revolute_joints is a list of joint indices corresponding to
> continuous revolute joints.
> @param preprocess_bbox is a flag for whether the function should precompute
> ```

Why not give the boxes as an optional argument instead? In our applications we pre-compute those boxes and save them. A user may not want this function to recompute them every time. 
___
*[`geometry/optimization/geodesic_convexity.h` line 149 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1IznuG3fusXzNit3Wf:-O1IznuG3fusXzNit3Wg:b-v69y80) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L149)):*
> ```objc
> axis-aligned bounding boxes for every set. This can speed up the pairwise
> intersection checks, by determining some sets to be disjoint without needing
> to solve an optimization problem.
> ```

nit Also add that pre-computing boxes introduces a small overhead. 
___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1J-xv712AGSFP52TtH:bs5glbw) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
> ```cpp
>       std::vector<std::pair<double, double>> bbox_values =
>           internal::GetMinimumAndMaximumValueAlongDimension(*convex_sets_A[i],
>                                                             all_indices);
> ```

1- Why do you call this function for all indices not only the revolute indices?
2- Why don't you call `MaybeCalcAxisAlignedBoundingBox` if you need the hyperrectangle?
___
*[`geometry/optimization/geodesic_convexity.cc` line 300 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J0IayBKvo3O_HWrTY:-O1J0IayBKvo3O_HWrTZ:bq6g45a) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L300)):*
> ```cpp
> 
>   // Compute bounding boxes for convex_sets_B if distinct from convex_sets_A.
>   bool convex_sets_A_and_B_are_identical = convex_sets_A == convex_sets_B;
> ```

The similar script is repeated here. Maybe make a method from it?

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593)* status: 3 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1Izx4rAbCCZK07VDQL:-O1MzyUX8LDcrYF4DS0Y:b-nulss1) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L146)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Why not give the boxes as an optional argument instead? In our applications we pre-compute those boxes and save them. A user may not want this function to recompute them every time.
</blockquote></details>

Great idea! But let's leave this for a followup PR, since I'll have to add a bunch of test cases to check that the argument is correctly validated.
___
*[`geometry/optimization/geodesic_convexity.h` line 149 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1IznuG3fusXzNit3Wf:-O1N-Vx1A2L3pcVF84BP:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L149)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit Also add that pre-computing boxes introduces a small overhead.
</blockquote></details>

Done.
___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1N12mt-Ph2oZJqRY9C:bd9mjht) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

1- Why do you call this function for all indices not only the revolute indices?
2- Why don't you call `MaybeCalcAxisAlignedBoundingBox` if you need the hyperrectangle?
</blockquote></details>

In this case, we want to get the upper and lower limits for everything (to do the bounding box preprocessing). I've changed the code flow around so we can use `MaybeCalcAxisAlignedBoundingBox` for this case. Long-term, it would be nice to incorporate `internal::GetMinimumAndMaximumValueAlongDimension` within `Hyperrectangle` somehow -- maybe an option in the constructor to skip certain dimensions? But that can be left for another time.
___
*[`geometry/optimization/geodesic_convexity.cc` line 300 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J0IayBKvo3O_HWrTY:-O1N3DJa4S1k19Eblsf1:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L300)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

The similar script is repeated here. Maybe make a method from it?
</blockquote></details>

Done.

**Review by sadraddini — COMMENTED** [review]
Need to make a decision on the usage of the flag. See the comments. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1TMXkI2GAQ6f-nuRWi:b-z47y04)* status: 5 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1Izx4rAbCCZK07VDQL:-O1TJYJ92iWvm9BWECJ5:b-jqd598) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L146)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Great idea! But let's leave this for a followup PR, since I'll have to add a bunch of test cases to check that the argument is correctly validated.
</blockquote></details>

Can you add a to do message? 
___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1TJkBwBE7RUPvVWC77:b-2nodjz) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

In this case, we want to get the upper and lower limits for everything (to do the bounding box preprocessing). I've changed the code flow around so we can use `MaybeCalcAxisAlignedBoundingBox` for this case. Long-term, it would be nice to incorporate `internal::GetMinimumAndMaximumValueAlongDimension` within `Hyperrectangle` somehow -- maybe an option in the constructor to skip certain dimensions? But that can be left for another time.
</blockquote></details>

I like hyperrectangle taking certain dimensions and let others be +-inf (or zero?, or skip those dimensions and obtain lower dimensional hyper rectangles). Can you also add that as a ToDo? 
___
*[`geometry/optimization/geodesic_convexity.cc` line 248 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKzFz4Q3iKvoJUe9V:-O1TKzFz4Q3iKvoJUe9W:b-madvz8) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L248)):*
> ```cpp
> }
> 
> std::vector<Hyperrectangle> BoundingBoxesForListOfSets(
> ```

Please add some comments on what this function does. 
___
*[`geometry/optimization/geodesic_convexity.cc` line 250 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKP2pESIcmneO8HYf:-O1TKP2pESIcmneO8HYg:b-bgcru7) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L250)):*
> ```cpp
> std::vector<Hyperrectangle> BoundingBoxesForListOfSets(
>     const ConvexSets& sets, const std::vector<int>& continuous_revolute_joints,
>     bool all_dimensions) {
> ```

here `all_dimensions` is redundant. If `continous_revolute_joints.size() == sets[0]->ambient_dimensions()`, this is already verified, right? 
___
*[`geometry/optimization/geodesic_convexity.cc` line 301 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TM1AZ2GQ8XmfSSyGg:-O1TM1AZ2GQ8XmfSSyGh:bumk03w) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L301)):*
> ```cpp
> 
>   // Compute bounding boxes for convex_sets_A.
>   bboxes_A = BoundingBoxesForListOfSets(
> ```

This is called even if `preprocess_bbox=false`? It does not make sense to have the flag then. You already paid the overhead cost for computing the boxes.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593)* status: 5 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.h` line 146 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1Izx4rAbCCZK07VDQL:-O1TSuT158nRa-O7pJ-a:bhl4pck) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.h#L146)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Can you add a to do message?
</blockquote></details>

Added to the `.cc` file. (I don't think we usually put TODOs in the docstrings?)

Either way, I'll plan to get that done pretty immediately after this PR merges. Happy to create an issue to track it, but it's already in my personal todo list.
___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1U8BaP-SiTkSsHcjC0:b82rgt2) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

I like hyperrectangle taking certain dimensions and let others be +-inf (or zero?, or skip those dimensions and obtain lower dimensional hyper rectangles). Can you also add that as a ToDo?
</blockquote></details>

I think we should make an issue to discuss that sort of change, rather than burying it in a todo somewhere. I'm not clear what the default behavior should be.
___
*[`geometry/optimization/geodesic_convexity.cc` line 248 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKzFz4Q3iKvoJUe9V:-O1U7bUxAFin9pfBS_o2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L248)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Please add some comments on what this function does.
</blockquote></details>

Done.
___
*[`geometry/optimization/geodesic_convexity.cc` line 250 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKP2pESIcmneO8HYf:-O1U8a-h5wJSyL-W8ZAJ:b-ngziz) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L250)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

here `all_dimensions` is redundant. If `continous_revolute_joints.size() == sets[0]->ambient_dimensions()`, this is already verified, right?
</blockquote></details>

I've changed the logic around so it just takes in a list of dimensions, and computes the bounding box along those dimensions. Now, no flag is necessary.
___
*[`geometry/optimization/geodesic_convexity.cc` line 301 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TM1AZ2GQ8XmfSSyGg:-O1U8fwq3vGHLRlxfpWy:bl3y8d) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L301)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

This is called even if `preprocess_bbox=false`? It does not make sense to have the flag then. You already paid the overhead cost for computing the boxes.
</blockquote></details>

Removed the flag (see above).

**Review by sadraddini — COMMENTED** [review]
Another checkpoint on the true meaning of the introduced flag. 

I still believe this change makes more sense if instead of the flag, the method takes the AABB of the sets instead. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1cA-ndEnKPrPcrQHWU:b6vt55o)* status: 5 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1c9PyM0IKjKnhQMWUp:b-8ayu6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

I think we should make an issue to discuss that sort of change, rather than burying it in a todo somewhere. I'm not clear what the default behavior should be.
</blockquote></details>

Agree
___
*[`geometry/optimization/geodesic_convexity.cc` line 248 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKzFz4Q3iKvoJUe9V:-O1c7u-iBZT2SKAP3wWO:b-i5t1lc) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L248)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit Make comments in cc files with `//` and avoid empty lines. 
___
*[`geometry/optimization/geodesic_convexity.cc` line 303 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c8wV65sR7fvooTC7j:-O1c8wV65sR7fvooTC7k:bnydo5g) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L303)):*
> ```cpp
>   // Bounding boxes along all dimensions (including joints which are not
>   // continuous revolute). If preprocess_bbox is true, all lower and upper
>   // limites will be computed and stored. Otherwise, only the entries
> ```

nit limites -> limits
___
*[`geometry/optimization/geodesic_convexity.cc` line 317 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c9Vx5AYsq_LA4LaD-:-O1c9Vx5AYsq_LA4LaD0:b-cffzi0) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L317)):*
> ```cpp
>     bboxes_A =
>         BoundingBoxesForListOfSetsSomeDimensions(convex_sets_A, all_joints);
>   } else {
> ```

This does not feel right. If the flag is not true, you still compute the (partial) boxes and use them to speed up the intersection checks. In this case, there is no benefit to have the preprocess box flag at all.

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/geodesic_convexity.cc` line 248 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1TKzFz4Q3iKvoJUe9V:-O1cB3hz85bP4s9xCz_q:b-q6o83y) ([raw file](https://github.com/RobotLocomotion/drake/blob/323cc76d1c3fbc142ea48476cd1e5c186c06ab57/geometry/optimization/geodesic_convexity.cc#L248)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit Make comments in cc files with `//` and avoid empty lines.
</blockquote></details>

The `/*` here is perfect.  There is no style rule to use `//`.

**Review by cohnt — COMMENTED** [review]
I do not want to require the user to pass in AABBs of the sets to take advantage of this functionality.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1cDaid6SobuX5WZKp8:bqo5xsa)* status: 4 unresolved discussions, LGTM missing from assignee sadraddini, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 279 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1J-xv712AGSFP52TtG:-O1cFQYRAhGkHVvCFgAL:b-2o0kmi) ([raw file](https://github.com/RobotLocomotion/drake/blob/6606d87a951e9e8a90276be6b93704b5f1a00156/geometry/optimization/geodesic_convexity.cc#L279)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

I'll create the issue after this PR merges.
___
*[`geometry/optimization/geodesic_convexity.cc` line 303 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c8wV65sR7fvooTC7j:-O1cDxvp9GxfMpcao3_u:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L303)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

nit limites -> limits
</blockquote></details>

Done.
___
*[`geometry/optimization/geodesic_convexity.cc` line 317 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c9Vx5AYsq_LA4LaD-:-O1cDz2g74xmRxi16sdV:b4f0kqb) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L317)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

This does not feel right. If the flag is not true, you still compute the (partial) boxes and use them to speed up the intersection checks. In this case, there is no benefit to have the preprocess box flag at all.
</blockquote></details>

Whether or not the bbox preprocessing is done, upper and lower limits are still needed along all dimensions corresponding to continuous revolute joints, in order to compute the edge offset between them (and determine whether sets intersect).

Once that offset has been computed, we then check to see if the `preprocess_bbox` flag has been set. If so, we know the full bounding boxes have been computed, so we do the cheap AABB intersection check, in order to maybe skip the full intersection check. If `preprocess_bbox` is false, then we go straight to the full intersection check.

I've added a TODO to note that we should probably still be able to use the subset of dimensions that have computed upper and lower limits when `preprocess_bbox` is false to do a conservative check.

**Review by sadraddini — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1cP3nB2EvySuVzPrNP:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 317 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c9Vx5AYsq_LA4LaD-:-O1cNwaW3VsSbkgIlFJ0:b97c32i) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L317)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Whether or not the bbox preprocessing is done, upper and lower limits are still needed along all dimensions corresponding to continuous revolute joints, in order to compute the edge offset between them (and determine whether sets intersect).

Once that offset has been computed, we then check to see if the `preprocess_bbox` flag has been set. If so, we know the full bounding boxes have been computed, so we do the cheap AABB intersection check, in order to maybe skip the full intersection check. If `preprocess_bbox` is false, then we go straight to the full intersection check.

I've added a TODO to note that we should probably still be able to use the subset of dimensions that have computed upper and lower limits when `preprocess_bbox` is false to do a conservative check.
</blockquote></details>

Let me get this straight.

If preprocess_bbox is true: you pre-compute AABBs first (some overhead) and skip the intersection check if AABBs don't intersect.

If preprocess_bbox is false: you still pre-compute the AABB components on the continuous joints, but you cannot skip the intersections if the AABBs are not disjoint.

Right? You want to take advantage of  `HyperrectangleOffsetIntersection(bbox_A, bbox_B, offset))` returning false.

In this case, I see the benefit and we can proceed.

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/geodesic_convexity.cc` line 317 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-O1c9Vx5AYsq_LA4LaD-:-O1cUwCj0wRL4KPoCDaw:btj10ph) ([raw file](https://github.com/RobotLocomotion/drake/blob/87b234def59722e2a59dd66891edfc9a42c21669/geometry/optimization/geodesic_convexity.cc#L317)):*
<details><summary><i>Previously, sadraddini (Sadra Sadraddini) wrote…</i></summary><blockquote>

Let me get this straight.

If preprocess_bbox is true: you pre-compute AABBs first (some overhead) and skip the intersection check if AABBs don't intersect.

If preprocess_bbox is false: you still pre-compute the AABB components on the continuous joints, but you cannot skip the intersections if the AABBs are not disjoint.

Right? You want to take advantage of  `HyperrectangleOffsetIntersection(bbox_A, bbox_B, offset))` returning false.

In this case, I see the benefit and we can proceed.
</blockquote></details>

Yep! All sounds good to me.

**Comment by cohnt** [comment]
+@jwnimmer-tri for platform review

**Comment by jwnimmer-tri** [comment]
Offloading to +@rpoyner-tri (please) for platform to stay balanced.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1s7dAd0ABQ1l6_3iFm:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21593#-:-O1s8PZh4LmZX0ZIhGpe:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sadraddini

**Pull request merged**
