### PR TITLE
Implements symbolic::Polynomial::Roots()

### PR DESCRIPTION
**Pull request by RussTedrake**
For finding the roots of univariate polynomials.
Towards #20159.

+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-:-Ndv2YQxBOYk4YgYJG7j:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`common/symbolic/polynomial.h` line 349 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ndv1ztoAkLJ3nVbtgQt:-Ndv1ztpDEfTVq_PGf2J:b-4kstf8) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e3b6101651c2adeafef57b0b8eb14b64041cab4/common/symbolic/polynomial.h#L349)):*
> ```objc
>   /// Returns the roots of a _univariate_ polynomial with constant coefficients
>   /// as a column vector.
>   ///
> ```

nit. Maybe add a note that we don't guarantee a specific ordering of the roots in the returned value?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[`common/symbolic/polynomial.h` line 349 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ndv1ztoAkLJ3nVbtgQt:-Ndv3kBa8oa8VQktbvu7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0e3b6101651c2adeafef57b0b8eb14b64041cab4/common/symbolic/polynomial.h#L349)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit. Maybe add a note that we don't guarantee a specific ordering of the roots in the returned value?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

See https://github.com/RussTedrake/drake/pull/55 for some fixes.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-:-Ne0qw3OEHU3hoiLJkdB:b4jld5t)* status: 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ne0qrFN0FRvhHzYUHiN:-Ne0qrFN0FRvhHzYUHiO:b-ls9o6p) (no related file):*
BTW The macOS CI failure is real (tolerance failure).  Be sure macOS is happy before merging this PR.

___
___
*[`common/symbolic/polynomial.cc` line 1061 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ne0yhYP4dVNkivxKL9A:-Ne0yhYP4dVNkivxKL9B:bsh1ov1) ([raw file](https://github.com/RobotLocomotion/drake/blob/e47bc2016ec48b207b8c27e155237cd1dfeb8689/common/symbolic/polynomial.cc#L1061)):*
> ```cpp
>     throw std::runtime_error(fmt::format(
>         "{} is not a univariate polynomial; it has indeterminates {}.",
>         ToExpression().to_string(), indeterminates().to_string()));
> ```

nit The formatting has a lot more syntax than necessary.  See my PR.
___
*[`common/symbolic/test/polynomial_test.cc` line 1515 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ne0rdDa-yMIy0ZOZVdW:-Ne0rdDb9b2K18aCeknE:b-b6ckzn) ([raw file](https://github.com/RobotLocomotion/drake/blob/e47bc2016ec48b207b8c27e155237cd1dfeb8689/common/symbolic/test/polynomial_test.cc#L1515)):*
> ```cpp
>   // Note: the order of the roots is not guaranteed. Sort them here by real,
>   // then imaginary.
>   auto sort = [](const Eigen::VectorXcd& v) {
> ```

nit Verb vs adjective confusion.  (Fixed in my PR.)



_Suggestion:_
```cpp
sorted
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20161#-Ne0qrFN0FRvhHzYUHiN:-Ne2wI47D7cQpxidzaPg:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The macOS CI failure is real (tolerance failure).  Be sure macOS is happy before merging this PR.
</blockquote></details>

Done.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20161)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai

**Pull request merged**
