### PR TITLE
Adds wsg_50_hydro_bubble_description

### PR DESCRIPTION
**Pull request by joemasterjohn**
Adds an SDF file for the Schunk WSG 50 gripper with hydroelastic finger bubbles.

Depends on RobotLocomotion/models#17.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16669)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@jwnimmer-tri for feature review, please. I will need some additional help if we require a LICENSE.txt here. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16669#-:-MwhkAm43zMQGOnSkZXx:b40dft7)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16669#-MwhjtEtAuSfuHd2N1sc:-MwhjtEtAuSfuHd2N1sd:b-b3ul4y) (no related file):*
Working temporary SHA1 until the models PR RobotLocomotion/models#17 is merged.

---

**Comment by jwnimmer-tri** [comment]
Most examples have example-specific model files that are housed in the examples folder alongside the demonstration.  The files in `//manipulation/models` are more often used for common models shared across multiple different examples, or shared across sundry unit tests as a canonical robot arm, etc.

Is there a plan for places where this gripper model would be used, besides the one example in #16668?

**Review by joemasterjohn — COMMENTED** [review]
I am not aware of any future possible use of the gripper model. For now it is only used in that example. If you prefer I can migrate the SDF and forward_files into the full example PR #16668.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16669#-:-Mwhlnpp8um9-yuuEDdP:bsyzfno)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yup, if it only has one planned user so far, then it should move to be adjacent.

**Review by jwnimmer-tri — COMMENTED** [review]
I'll pause for now; some of the content here will change with the shuffle.

> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16669#-:-Mwhom3lB9yqnLzh4ue9:b-fkct1g)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @joemasterjohn and @jwnimmer-tri)

___
*[tools/workspace/models/files.bzl, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16669#-MwhnIqvBEcW-Rs9MUO-:-MwhnIqw-9AwoMDm_-BL:bx16wb) ([raw file](https://github.com/robotlocomotion/drake/blob/99805074ad445dfb9c6ebe3275601659f3045344/tools/workspace/models/files.bzl#L4)):*
> ```Starlark
> 
> # Keep the macros sorted alphabetically by macro name.
> # Keep the lists of files sorted alphabetically by filename.
> ```

nit The newly-added list should be alpha-sorted.
___
*[tools/workspace/models/package.BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16669#-MwhoBcSE5PRS298LzYk:-MwhoBcSE5PRS298LzYl:b-xuzv3t) ([raw file](https://github.com/robotlocomotion/drake/blob/99805074ad445dfb9c6ebe3275601659f3045344/tools/workspace/models/package.BUILD.bazel#L13)):*
> ```
>         "skydio_2/**",
>         "wsg_50_description/**",
>         "wsg_50_hydro_bubble_description/**",
> ```

Up to you, but FYI we don't need "_description" here by rote.  The other robots folders use "description" because that's what those ROS packages are called, but we aren't mimicing a ROS package here.

**Review by joemasterjohn — COMMENTED** [review]
Should I proceed by closing this PR and making the changes all in #16668? Or setup the example directory here and merge with #16668 when this is finished?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16669#-:-MwhrkVB-tszSNFBpesC:b-49s4gq)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @joemasterjohn and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Either way is fine by me.

**Comment by joemasterjohn** [comment]
Closing. Moving model files to example PR #16668.

**Pull request closed without merging**
