### PR TITLE
Use angle brackets for gtest include; clang-format-includes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The first two commits are hand-written; the third commit is the automated tool.
Relates #5550.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5911)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for all review please (does not need platform).

:lgtm: to merge once that review is complete.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5911#-:-KiD9z6Hle-awLV0toCS:bwo2bsy)*

**Comment by jwnimmer-tri** [comment]
Some random `examples/Acrobot/runTrigLQR` timeout.
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Unstable due to git failures.
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by jwnimmer-tri** [comment]
-@amcastro-tri +@naveenoid for all review, please.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5911#-:-KiGGc7UMoCJlkmS6X0E:bui4bsa)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5911#-:-KiVIFNf9U1a7dHDpZRo:bnfp4nl)*

**Pull request merged**
