### PR TITLE
[geometry] Refactor ClipPolygonByHalfSpace() for code reuse.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Related to #16040.

- Move ClipPolygonByHalfSpace() from being a static member of SurfaceVolumeIntersector
  to be a free function.
- Move its helper CalcIntersection() as well.

Once this PR merges, I'll use it in #16365.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

In rigid-compliant code, I change `ClipPolygonByHalfSpace()` to be a free function, so I can re-use it in compliant-compliant contact.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374#-:-MtKdRpa6Cch-Zgb-Y32:b4db4x9)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374#-:-MtPACtf7XJE_TGeFErL:bnfp4nl)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/mesh_intersection.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP6XZK3kG8JpzY1GCr:-MtP6XZK3kG8JpzY1GCs:b-n2uuaw) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/mesh_intersection.h#L37)):*
> ```objc
>  @pre
>      One of A and B is outside the half space, and the other is inside or
>      on the boundary of the half space.
> ```

BTW Maybe I'm missing something: if the object to be clipped is an infinite line, why do the points have to lie on either side of the boundary? Wouldn't it be sufficient for AB to be not parallel to H?

I'm fine if the algorithm is limited in some way; we should just be careful not to over-claim in the comments in that case.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP9oIwEycQrMlRiV5U:-MtP9oIwEycQrMlRiV5V:b-p2xaqm) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/test/mesh_intersection_test.cc#L81)):*
> ```cpp
> // TODO(DamrongGuoy): More comprehensive tests.
> /* This test is independent of ContactSurface mesh representation; so we'll
>  simply use TriangleSurfaceMesh. */
> ```

Is this comment stale now?
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtPA-BU1ywqes1JapDg:-MtPA-BU1ywqes1JapDh:brj4l8o) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/test/mesh_intersection_test.cc#L125)):*
> ```cpp
> // treated correctly by this function, they are not tested as being a
> // meaningless operation. This test is independent of ContactSurface mesh
> // representation; so we'll simply use TriangleSurfaceMesh.
> ```

Is this comment stale now we don't need a mesh?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/proximity/mesh_intersection.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP6XZK3kG8JpzY1GCr:-MtaJWMP3MwyLExohSL3:b-txq1um) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/mesh_intersection.h#L37)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW Maybe I'm missing something: if the object to be clipped is an infinite line, why do the points have to lie on either side of the boundary? Wouldn't it be sufficient for AB to be not parallel to H?

I'm fine if the algorithm is limited in some way; we should just be careful not to over-claim in the comments in that case.
</blockquote></details>

You're right.  I updated the prerequisite here and the DRAKE_DEMAND in the .cc.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP9oIwEycQrMlRiV5U:-MtaM10g9pdHsTGkdM0h:b-wm20f8) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/test/mesh_intersection_test.cc#L81)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Is this comment stale now?
</blockquote></details>

Yes.  I removed these TODOs and comments that are not relevant anymore.  This test uses no mesh.
___
*[geometry/proximity/test/mesh_intersection_test.cc, line 125 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtPA-BU1ywqes1JapDg:-MtaM8GaDIE8fC33oLc7:bf7cbw3) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/test/mesh_intersection_test.cc#L125)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Is this comment stale now we don't need a mesh?
</blockquote></details>

Correct. This test uses no mesh.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[geometry/proximity/mesh_intersection.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP6XZK3kG8JpzY1GCr:-MtdTNGLDftdA78eXrmS:b-pfyg5s) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/mesh_intersection.h#L37)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

You're right.  I updated the prerequisite here and the DRAKE_DEMAND in the .cc.
</blockquote></details>

Cool. I don't want to go down the rathole on a vacation day, but the next question is: do we have test coverage for the expanded possible set of geometry cases now?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374#-:-MtjMx65CfZfxEMQg195:bppyoqq)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[geometry/proximity/mesh_intersection.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP6XZK3kG8JpzY1GCr:-MtjMf7H3Yaxq-rtNbBY:b-68fft8) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/mesh_intersection.h#L37)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Cool. I don't want to go down the rathole on a vacation day, but the next question is: do we have test coverage for the expanded possible set of geometry cases now?
</blockquote></details>

Done.  Please let me know if I go overboard expanding the unit test.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[geometry/proximity/mesh_intersection.h, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16374#-MtP6XZK3kG8JpzY1GCr:-MtjNBKjAdspTFIfDBB9:b8j0dhm) ([raw file](https://github.com/robotlocomotion/drake/blob/df62fe2a23d11d0cf0a8eb4847c89bf2cfeb57b6/geometry/proximity/mesh_intersection.h#L37)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  Please let me know if I go overboard expanding the unit test.
</blockquote></details>

I'm not sure whether I made the unit tests harder to read or easier to read?

**Review by sherm1 — COMMENTED** [review]
+@sammy-tri -@sherm1 Punting to Sam for platform review due to reviewer out of gas. Thanks, Sam!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374#-:-MtkU0V90MeVAyWhsPQa:btckozy)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16374#-:-MtnkZUb3G-4YU-YXcsR:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @DamrongGuoy)

**Comment by DamrongGuoy** [comment]
Thank you!  Another :heavy_check_mark: in #16040. :smile:

**Pull request merged**
