### PR TITLE
Add iiwa 7 acceleration limits

### PR DESCRIPTION
**Pull request by nepfaff**
Towards https://github.com/RobotLocomotion/drake/issues/20907

The methodology for computing these limits is described in the `README`.

For reference, I used the following code to compute them:
```python
from manipulation import ConfigureParser
from pydrake.all import MultibodyPlant, Parser, inv


def create_arm(file: str):
    plant = MultibodyPlant(0.0)
    parser = Parser(plant)
    ConfigureParser(parser)
    arm = parser.AddModelsFromString(file, "dmd.yaml")[0]
    plant.Finalize()
    return plant, arm


iiwa14_scenario = """
directives:
    - add_model:
        name: iiwa
        file: package://drake/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
    - add_weld:
        parent: world
        child: iiwa::iiwa_link_0
"""

iiwa7_scenario = """
directives:
    - add_model:
        name: iiwa
        file: package://drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
    - add_weld:
        parent: world
        child: iiwa::iiwa_link_0
"""

iiwa14_torque_limits = [320, 320, 176, 176, 110, 40, 40]
iiwa14_acc_limits = [8.57, 8.57, 8.74, 11.36, 12.23, 15.72, 15.72]
iiwa7_torque_limits = [176, 176, 110, 110, 110, 40, 40]

iiwa14_plant, iiwa14_arm = create_arm(iiwa14_scenario)
iiwa7_plant, iiwa7_arm = create_arm(iiwa7_scenario)

iiwa14_plant_context = iiwa14_plant.CreateDefaultContext()
iiwa14_mass_matrix = iiwa14_plant.CalcMassMatrix(iiwa14_plant_context)
iiwa14_mass_matrix_inv = inv(iiwa14_mass_matrix)

iiwa7_plant_context = iiwa7_plant.CreateDefaultContext()
iiwa7_mass_matrix = iiwa7_plant.CalcMassMatrix(iiwa7_plant_context)
iiwa7_mass_matrix_inv = inv(iiwa7_mass_matrix)

iiwa7_acc_limits = (
    iiwa14_acc_limits
    * (iiwa7_mass_matrix_inv @ iiwa7_torque_limits)
    / (iiwa14_mass_matrix_inv @ iiwa14_torque_limits)
)
print(iiwa7_acc_limits)
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20921)

### CODE REVIEW

**Comment by nepfaff** [comment]
@AdityaBhat-TRI @RussTedrake, would you mind reviewing this one?

**Review by RussTedrake — COMMENTED** [review]
+@AdityaBhat-TRI for feature review, please
+@RussTedrake for platform review.  :LGTM:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20921#-:-NqVLEpl7KGvTvfixJil:bbbbvyg)* status: LGTM missing from assignee AdityaBhat-TRI

**Comment by AdityaBhat-TRI** [comment]
If I understand this correctly, does this approach underestimate the acceleration limit? 

The accelerations for the IIWA 14 were obtain experimentally according to the referenced doc. Given that torque limits are configuration dependent and given that the kinematic and mass properties of the IIWA 7and IIWA 14 are different, I don't know if you can ignore/cancel the gravity torque from the manipulator equations (as the torque limits of actuators are dictated by the motor power and gear ratio).

If you don't ignore the gravity torque, you end up getting:
acc_limits_iiwa7 = acc_limits_iiwa14 * (mass_matrix_inverse_iiwa7 @ (effort_limits_iiwa7 - gravity_iiwa_7))
/ (mass_matrix_inverse_iiwa14 @ (effort_limits_iiwa14- gravity_iiwa_14))

Maybe I'm missing something here, but is it reasonable to ignore the gravity torque to compute acceleration limits?

**Review by AdityaBhat-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20921)* status: LGTM missing from assignee AdityaBhat-TRI

**Comment by AdityaBhat-TRI** [comment]
*acceleration limits are configuration dependent

**Comment by nepfaff** [comment]
That is fair. The current calculation assumes zero joint positions.

I'm getting the following for a configuration of `[0, pi/2, 0, 0, 0, 0, 0]`, which should be maximum torques due to gravity:
`[ 8.00624744  5.30375312  5.74095776 11.28351933 11.77435139 13.76883454 13.15690567]`

Some limits are slightly bigger, while some are slightly smaller. As Drake doesn't support configuration-dependent acceleration limits, we will want to use conservative limits to prevent demanding accelerations that are too high.
Do you think it would be reasonable to sample configurations and take the minimum limits joint-wise?

**Comment by nepfaff** [comment]
For the iiwa14 limits, the docs say `The average acceleration limits are used, and rounded to second decimal place for radians`.
Taking the average seems weird to me. Do you think that this is more reasonable?

**Comment by AdityaBhat-TRI** [comment]
Typically, when other parameters such as payload are specified, it's an underestimate of the maximum value. I recommend doing the same with acceleration limits. Putting in a comment in the readme saying that it's an underestimate and the limits are configuration dependent should suffice.

**Comment by nepfaff** [comment]
Couldn't gravity also reduce the acceleration limits, depending on the direction of movement? In this case, the limits are both configuration and sign(q_ddot) dependent.

I agree with adding a comment to the README. In this case, the limits should be good enough for most applications. If someone really cares, they will want to determine configuration- and movement direction-dependent acceleration limits and add them to their trajectory optimization problem directly.

**Comment by AdityaBhat-TRI** [comment]
Agree!

**Review by AdityaBhat-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20921)* status: LGTM missing from assignee AdityaBhat-TRI

**Comment by nepfaff** [comment]
I added a comment

**Comment by AdityaBhat-TRI** [comment]
:lgtm:

**Pull request merged**
