### PR TITLE
[fem] Support Schur complement in PETSc

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16250)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrA7su8834VKUXJfk5y:-MrA7su92W_YTRntEOsY:b-ujq5mk) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please

---

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for encore review please. Sorry for the inconvenience.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16250#-:-MrAGAeR7XWj4y3nQ9Eg:b-ruvgm0)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrAGWhLCZvwF0lANBZH:-MrAGWhLCZvwF0lANBZI:b5537nl) ([raw file](https://github.com/robotlocomotion/drake/blob/e90a8ded00756832ac8b4848dc4127ed2bd57fb9/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L238)):*
> ```cpp
>   MatrixXd B = MatrixXd::Zero(6, 3);
>   B.topLeftCorner<3, 3>() = M_eigen.block<3, 3>(3, 0);
>   B.bottomLeftCorner<3, 3>() = M_eigen.block<3, 3>(3, 6);
> ```

FYI, this is where I messed up earlier. 

I did `B.topRightCorner<3,3>()` instead of `B.bottomLeftCorner<3,3>()`, thinking B is 3x6. 

I now initialize the matrix at construction to avoid undefined behavior.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-continuous-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16250#-:-MrOVVAe4I37TuA0tYUV:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrAGWhLCZvwF0lANBZH:-MrOUyKCA34AhXFHwxBW:b-oof4co) ([raw file](https://github.com/robotlocomotion/drake/blob/e90a8ded00756832ac8b4848dc4127ed2bd57fb9/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L238)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, this is where I messed up earlier. 

I did `B.topRightCorner<3,3>()` instead of `B.bottomLeftCorner<3,3>()`, thinking B is 3x6. 

I now initialize the matrix at construction to avoid undefined behavior.
</blockquote></details>

this solves the original issue.
However, notice that B is zero. I wonder if you'd like to update the test to have a non-zero B matrix.
Non-blocking.

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrOjvPnDR5yJeqHHLOZ:-MrOjvPnDR5yJeqHHLO_:b-ekyx7i) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16250)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrAGWhLCZvwF0lANBZH:-MrOk62h98TpJ-v-sX6X:b3vpl7q) ([raw file](https://github.com/robotlocomotion/drake/blob/e90a8ded00756832ac8b4848dc4127ed2bd57fb9/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L238)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this solves the original issue.
However, notice that B is zero. I wonder if you'd like to update the test to have a non-zero B matrix.
Non-blocking.
</blockquote></details>

That'd be nice. But it would require a new nonzero structure that'll affect other tests. I feel it's a bit not worth the effort.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16250)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc, line 238 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16250#-MrAGWhLCZvwF0lANBZH:-MrOlEqFCdJIPhh-nOwl:balbgad) ([raw file](https://github.com/robotlocomotion/drake/blob/e90a8ded00756832ac8b4848dc4127ed2bd57fb9/multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc#L238)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

That'd be nice. But it would require a new nonzero structure that'll affect other tests. I feel it's a bit not worth the effort.
</blockquote></details>

true, lest merge this now. Definitely an improvement.

**Pull request merged**
