### PR TITLE
Add MathematicalProgram::RemoveDecisionVariable.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Remove a decision variable from the MathematicalProgram. The decision variable cannot be bound with any cost/constraint.

Towards #20842 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-:-Nx11C-nBHtKe3isvz6j:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 3625 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx33AfEA3EAlKbDF6mj:-Nx33AfF9Iy8jOEHNKoA:b-l6hhkc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.h#L3625)):*
> ```objc
>    * @note after removing the variable, the indices of some remaining variables
>    * inside this MathematicalProgram will change.
>    * @return the index of `var` in this optimization program. return -1 if `var`
> ```

nit We try to avoid magic numbers.  We should return `optional<int>` here instead of a magic number.
___
*[`solvers/mathematical_program.h` line 3628 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx32mwl3kn8W2XUUdju:-Nx32mwm6E-Hc1-Z4A0R:b3kxac3) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.h#L3628)):*
> ```objc
>    * is not a decision variable.
>    * @throw exception if `var` is bound with any cost or constraint.
>    * @throw exception if `var` is an indeterminate of the program.
> ```

We throw when var is indeterminate, but we return a failure value when var is totally unknown?  That seems somewhat inconsistent.

It seems to me that either we should throw on all errors (my preference), or else never throw (instead, we expect the user to check the return value if they care about whether it existed or not).
___
*[`solvers/mathematical_program.cc` line 1849 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx37w9z3YgQZzuK033T:-Nx37w9z3YgQZzuK033U:b-m2le4o) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1849)):*
> ```cpp
> namespace {
> template <typename C>
> [[nodiscard]] bool IsVariableBound(const symbolic::Variable& var,
> ```

This is the same as `Binding::ContainsVariable`.  We should just call that member function, instead.
___
*[`solvers/mathematical_program.cc` line 1868 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx34BxX8X_W2u-Q6sAe:-Nx34BxX8X_W2u-Q6sAf:b65xohr) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1868)):*
> ```cpp
>           NiceTypeName::Get(*(binding.evaluator())));
>       if (!binding.evaluator()->get_description().empty()) {
>         binding_description->append(binding.evaluator()->get_description());
> ```

Why not use `*binding_description = binding.to_string()` here?  It already does all of the work of nice formatting.
___
*[`solvers/mathematical_program.cc` line 1881 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx33ROS0zLFZ3XmuZJF:-Nx33ROT6QEMmXcHMwuM:b-sjjk61) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1881)):*
> ```cpp
>                                    const MathematicalProgram& prog,
>                                    std::string* binding_description) {
>   if (IsVariableBound(var, prog.generic_costs(), binding_description)) {
> ```

The big list of all types seems brittle.  (We could easily add a new one and forget to change this function.)   Could we loop over `prog.GetAllCosts()` and `prog.GetAllConstraints()`, instead?

Broadly, the goal should be for only _one_ place in the cc file to write down the list of member field names that contain costs (or constraints).
___
*[`solvers/mathematical_program.cc` line 1960 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx352dr1TjnPtWR83TB:-Nx352dr1TjnPtWR83TC:bs4aepc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1960)):*
> ```cpp
>        it != decision_variable_index_.end();) {
>     // Remove the entry that maps var.get_id() to its index.
>     if (it->first == var.get_id()) {
> ```

There is no need to do the erase inside the loop, and doing so make the code more complicated than necessary.  A few lines up above we have `var_it` which is exactly the iterator we need.  We can just do ...

```c++
  const int var_index = var_it->second;
  decision_variables_index_.erase(var_it);
```

... and then this loop will only have the job of adjusting the values.  In that case, the loop can be a `for (auto& [var, index] : decision_variable_index_)` for readability, and the decrement is just `--index`.

(In general, anytime we say `first` or `second` should be a signal that the code might not be using the best C++ API available.)
___
*[`solvers/mathematical_program.cc` line 1971 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx368F86BfBw_NhgqLY:-Nx368F86BfBw_NhgqLZ:butjykl) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1971)):*
> ```cpp
>   }
>   // Remove the variable from decision_variables_.
>   for (auto it = decision_variables_.begin();
> ```

We don't need to loop here.  We already know var's exact index (`var_index`) so the iterator we want to erase will be `decision_variables_.begin() + var_index`.
___
*[`solvers/mathematical_program.cc` line 1981 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx36vtG3mHBq1rFbN98:-Nx36vtG3mHBq1rFbN99:bnkawf7) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1981)):*
> ```cpp
>   // Remove from var_scaling_map_.
>   std::unordered_map<int, double> new_var_scaling_map;
>   for (auto it = var_scaling_map_.begin(); it != var_scaling_map_.end(); ++it) {
> ```

Use structured binding here (e.g. `const auto& [var, index]`) for readability.
___
*[`solvers/mathematical_program.cc` line 1988 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx3727t3JX1x5NFRuH2:-Nx3727u3jlGiNhD3NCj:b-7l5cpp) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1988)):*
> ```cpp
>     }
>   }
>   var_scaling_map_ = new_var_scaling_map;
> ```

nit Use `std::move` to avoid a copy.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 3628 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx32mwl3kn8W2XUUdju:-Nx4BS-MEh6dusG0kyZj:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.h#L3628)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We throw when var is indeterminate, but we return a failure value when var is totally unknown?  That seems somewhat inconsistent.

It seems to me that either we should throw on all errors (my preference), or else never throw (instead, we expect the user to check the return value if they care about whether it existed or not).
</blockquote></details>

Done.
___
*[`solvers/mathematical_program.cc` line 1849 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx37w9z3YgQZzuK033T:-Nx4Bh0o6hmDGAxZbXyj:b-h5g1tk) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1849)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is the same as `Binding::ContainsVariable`.  We should just call that member function, instead.
</blockquote></details>

Done. Good call
___
*[`solvers/mathematical_program.cc` line 1868 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx34BxX8X_W2u-Q6sAe:-Nx4Bowg4YwGWkxoM0fg:b-h5g1tk) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1868)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why not use `*binding_description = binding.to_string()` here?  It already does all of the work of nice formatting.
</blockquote></details>

Done. Good call
___
*[`solvers/mathematical_program.cc` line 1881 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx33ROS0zLFZ3XmuZJF:-Nx4BvhT6ZzJITpeoGeP:b-7ti5p) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1881)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The big list of all types seems brittle.  (We could easily add a new one and forget to change this function.)   Could we loop over `prog.GetAllCosts()` and `prog.GetAllConstraints()`, instead?

Broadly, the goal should be for only _one_ place in the cc file to write down the list of member field names that contain costs (or constraints).
</blockquote></details>

`prog.GetAllCosts()` and `prog.GetAllConstraints()` will create new std::vector on the heap, so I was concerned about the computation time. Potentially we could call `RemoveDecisionVariable` for many times, if we want to remove a set of variables.

Maybe I can create something like
```cc
void MathematicalProgram::DoForAllCosts(std::function fun);
void MathematicalProgram::DoForAllConstraints(std::function fun);
```
and which just loops over all costs/constraints and call `fun`? These two functions can be re-used.i
___
*[`solvers/mathematical_program.cc` line 1960 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx352dr1TjnPtWR83TB:-Nx5qbWD9_uLIl7LjY3S:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1960)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is no need to do the erase inside the loop, and doing so make the code more complicated than necessary.  A few lines up above we have `var_it` which is exactly the iterator we need.  We can just do ...

```c++
  const int var_index = var_it->second;
  decision_variables_index_.erase(var_it);
```

... and then this loop will only have the job of adjusting the values.  In that case, the loop can be a `for (auto& [var, index] : decision_variable_index_)` for readability, and the decrement is just `--index`.

(In general, anytime we say `first` or `second` should be a signal that the code might not be using the best C++ API available.)
</blockquote></details>

Done. Good call.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.cc` line 1881 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx33ROS0zLFZ3XmuZJF:-Nx7yHYt1UzP8BFDIkBR:b-a2z89l) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1881)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`prog.GetAllCosts()` and `prog.GetAllConstraints()` will create new std::vector on the heap, so I was concerned about the computation time. Potentially we could call `RemoveDecisionVariable` for many times, if we want to remove a set of variables.

Maybe I can create something like
```cc
void MathematicalProgram::DoForAllCosts(std::function fun);
void MathematicalProgram::DoForAllConstraints(std::function fun);
```
and which just loops over all costs/constraints and call `fun`? These two functions can be re-used.i
</blockquote></details>

We could try to find ways to make this code more efficient, but I don't really think the `std::vector` will matter.  If we care about speed, then we start by creating a relevant benchmark and go from there.  The other parts of this new function are not necessarily speedy, either, so it's entirely possible that the vector-copy is not the relevant part which would be the bottleneck.
___
*[`solvers/mathematical_program.cc` line 21 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx7yc0t5utV3gO50SHe:-Nx7yc0t5utV3gO50SHf:bg11tc) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/mathematical_program.cc#L21)):*
> ```cpp
> #include "drake/common/eigen_types.h"
> #include "drake/common/fmt_eigen.h"
> #include "drake/common/nice_type_name.h"
> ```

nit Unused `nice_type_name`
___
*[`solvers/mathematical_program.cc` line 26 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx7yeRSClyvedyus_Ve:-Nx7yeRSClyvedyus_Vf:bugaftd) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/mathematical_program.cc#L26)):*
> ```cpp
> #include "drake/common/symbolic/latex.h"
> #include "drake/common/symbolic/monomial_util.h"
> #include "drake/common/text_logging.h"
> ```

nit Unused `text_logging`
___
*[`solvers/mathematical_program.cc` line 1943 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx7yVhy4gNk0LG0PoVN:-Nx7yVhy4gNk0LG0PoVO:b-qg59x3) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/mathematical_program.cc#L1943)):*
> ```cpp
>     // Decrement the index of the variable after `var`.
>     if (variable_index > var_index) {
>       variable_index--;
> ```

nit GSG wants `--variable_index` pre-decrement.

https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement
___
*[`solvers/test/mathematical_program_test.cc` line 4399 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx87Q8q535lPeeIDVxC:-Nx87Q8rClPmURaMdAGm:b-9r5b7m) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/test/mathematical_program_test.cc#L4399)):*
> ```cpp
>   EXPECT_EQ(prog.FindDecisionVariableIndex(x(0)), 0);
>   EXPECT_EQ(prog.FindDecisionVariableIndex(x(2)), 1);
>   EXPECT_EQ(prog.decision_variables().size(), 2);
> ```

When checking an accessor that returns a collection, readability suffers when we write out several checks all on different lines -- we're relying on the reader to realize that the multiple lines are all inter-related.

There's nearly always a way using [matchers](http://google.github.io/googletest/reference/matchers.html) to check a collection for a hard-coded value in a single test.  I wrote up the changes here: https://github.com/hongkai-dai/drake/pull/34
___
*[`solvers/test/mathematical_program_test.cc` line 4428 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx808Op7wOlAyGZl5vs:-Nx808Op7wOlAyGZl5vt:b2d3t4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/test/mathematical_program_test.cc#L4428)):*
> ```cpp
>   prog.AddLinearCost(x(0));
>   DRAKE_EXPECT_THROWS_MESSAGE(prog.RemoveDecisionVariable(x(0)),
>                               ".* is associated with a LinearCost..*");
> ```

nit The double dot isn't doing anything useful here.



_Suggestion:_
```cpp
LinearCost.*
```
___
*[`solvers/test/mathematical_program_test.cc` line 4434 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx80DFJ03tSNr-3f_e8:-Nx80DFJ03tSNr-3f_e9:b-6fk04k) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/test/mathematical_program_test.cc#L4434)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       prog.RemoveDecisionVariable(x(1)),
>       ".* is associated with a LinearConstraint\n.*\n.");
> ```

BTW Do we care how many newlines the error has?  If not:



_Suggestion:_
```cpp
LinearConstraint[^]*
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.cc` line 1881 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx33ROS0zLFZ3XmuZJF:-NxBQA1b4VR59hjUMSsh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3122078abd7082f1a8e8e990fe6bb294d7a66c9c/solvers/mathematical_program.cc#L1881)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We could try to find ways to make this code more efficient, but I don't really think the `std::vector` will matter.  If we care about speed, then we start by creating a relevant benchmark and go from there.  The other parts of this new function are not necessarily speedy, either, so it's entirely possible that the vector-copy is not the relevant part which would be the bottleneck.
</blockquote></details>

Done.
___
*[`solvers/test/mathematical_program_test.cc` line 4399 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-Nx87Q8q535lPeeIDVxC:-NxBQMeS8kLKXZ-cXzZ0:b-t3dckq) ([raw file](https://github.com/RobotLocomotion/drake/blob/c300c64f170ec6f95d72e4c23def44dd22f600a4/solvers/test/mathematical_program_test.cc#L4399)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When checking an accessor that returns a collection, readability suffers when we write out several checks all on different lines -- we're relying on the reader to realize that the multiple lines are all inter-related.

There's nearly always a way using [matchers](http://google.github.io/googletest/reference/matchers.html) to check a collection for a hard-coded value in a single test.  I wrote up the changes here: https://github.com/hongkai-dai/drake/pull/34
</blockquote></details>

Done.

Thanks, TIL matches in gtest.

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: feature) 

:lgtm: feature review.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-:-NxCz8D23dYpeG0W_D4X:bstqscn)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.cc` line 1869 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-NxCzkCfAnCwm8fhdQ_q:-NxCzkCfAnCwm8fhdQ_r:b-o95z37) ([raw file](https://github.com/RobotLocomotion/drake/blob/7a39dcda75cdae924384e3115b69dc2ca0975640/solvers/mathematical_program.cc#L1869)):*
> ```cpp
>   if (IsVariableBound(var, prog.GetAllConstraints(), binding_description)) {
>     return true;
>   }
> ```

We also need to check if any `visualization_callbacks()` binding has this variable.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending resolution of open discussions.

> Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-:-NxDhHb3A3mPZG5dcrLz:b-v0v34k)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/mathematical_program.cc` line 1869 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21392#-NxCzkCfAnCwm8fhdQ_q:-NxDqrY495LiYGA7I3kI:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/7a39dcda75cdae924384e3115b69dc2ca0975640/solvers/mathematical_program.cc#L1869)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We also need to check if any `visualization_callbacks()` binding has this variable.
</blockquote></details>

Done. Good call.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21392)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
