### PR TITLE
Create RollPitchYaw class and start implementing.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8606)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@ggould-tri 

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-:-LAL7ZxaALFle4qMzkqd:bguppra)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/roll_pitch_yaw.h, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LATzTRF-HSiMP5gNJME:-LATzTRF-HSiMP5gNJMF:b-tjskq4) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw.h#L116)):*
> ```objc
>   /// @param[in] rpy allegedly valid roll, pitch, yaw angles.
>   /// @note an angle is invalid if it is NaN or infinite.
>   static bool IsValid(const Vector3<T>& rpy) { return rpy.allFinite(); }
> ```

Should we also require that roll is within range [-PI, PI], pitch in [-PI/2, PI/2] and roll in [-PI, PI]?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-:-LAU-0El0mzF1Z4y0HMp:bnfp4nl)*

**Comment by mitiguy** [comment]
Platform review -@ggould-tri 
Platform review +@soonho-tri 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/roll_pitch_yaw.h, line 116 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LATzTRF-HSiMP5gNJME:-LAU40EG1EgiHM7_X11k:b-bjjdyz) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw.h#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we also require that roll is within range [-PI, PI], pitch in [-PI/2, PI/2] and roll in [-PI, PI]?
</blockquote></details>

Resolved f2f.  Done.  Only needed when converting from RotationMatrix to RollPitchYaw.  This is already done in rotmat2rpy which will soon be deprecated as this functionality will be moved to this RollPitchYaw class in a subsequent PR.
Note:  There are many follow-up TODO(mitiguy) which could be sprinkled through the code - but effectively they are all marked by being part of the files:
rotation_matrix_deprecated.h
roll_pitch_yaw_using_quaternion.h
roll_pitch_yaw_not_using_quaternion.h

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-:-LAU4S0TActcDvAHhI-x:bwb9pbr)*

**Comment by soonho-tri** [comment]
:lgtm: 

 - I have a few suggestions to make the doxygen part better.
 - Can we have test cases in `math/test/roll_pitch_yaw_test.cc`? I understand that it's replacing the old/deprecated code but it's not clear we have full test coverage for the newly introduced class. For example, I am not sure `IsNearlyEqualTo` method is tested.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[math/roll_pitch_yaw.h, line 46 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LAUBB6pD8XTN86NYoLA:-LAUBB6pD8XTN86NYoLB:blg2be3) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw.h#L46)):*
> ```objc
> /// Note: B and A are no longer aligned.
> /// The monogram notation for the rotation matrix relating A to D is `R_AD`.
> /// See @ref multibody_quantities for monogram notation for dynamics.
> ```

FYI, you might want to have a newline here. See the attached doc:
 


---

*[math/roll_pitch_yaw.h, line 67 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LAUCCoF3fpv9lQtjmzB:-LAUCCoF3fpv9lQtjmzC:b68e2xk) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw.h#L67)):*
> ```objc
>   /// Constructs a %RollPitchYaw from a 3x1 array of angles.
>   /// @param[in] rpy roll, pitch, yaw angles (units of radians).
>   /// @throws exception std::logic_error in debug builds if !IsValid(rpy).
> ```

FYI, META, we prefer `@throws std::logic_error` because Doxygen only highlights the first word after `@throws`:



Related discussion: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1520817375000174

---

*[math/roll_pitch_yaw_not_using_quaternion.h, line 25 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LAUDQy-BDLeflB9_45D:-LAUDQy-BDLeflB9_45E:b-ffkbzh) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw_not_using_quaternion.h#L25)):*
> ```objc
> 
> /// (Deprecated), use @ref math::RollPitchYaw(rpy).ToQuaternion().
> // TODO(mitiguy) Delete this code that was deprecated on April 16, 2018.
> ```

BTW, can we use `DRAKE_DEPRECATED` provided in https://github.com/RobotLocomotion/drake/blob/master/common/drake_deprecated.h ? (also in `roll_pitch_yaw_using_quaternion.h`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-:-LAUH-g87d3ItvASVBOW:b-bzx8ed)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[math/roll_pitch_yaw.h, line 46 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LAUBB6pD8XTN86NYoLA:-LAUd1Zn1T9AGbhmWep-:bhbynsp) ([raw file](https://github.com/robotlocomotion/drake/blob/81fe280aaf3b51e97dc186a75d75aa8d52d5bd1b/math/roll_pitch_yaw.h#L46)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, you might want to have a newline here. See the attached doc:
 


</blockquote></details>

BTW using `@see` rather than just `See` might also produce nice output.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606)*

**Comment by mitiguy** [comment]
Thanks for the review Soonho.  Much appreciated and great feedback.  roll_pitch_yaw_test.cc added.

---

Review status: 11 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-:-LAVmvCE4b2_SfnMmMNA:b7l9dk1)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/test/roll_pitch_yaw_test.cc, line 15 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606#-LAYYz1G7mJm11FTJvoI:-LAYYz1H7xtWG4pOGmDR:bgiqi24) ([raw file](https://github.com/robotlocomotion/drake/blob/0069d0558b1cbd2fc8d76f705dfa19923051a05b/math/test/roll_pitch_yaw_test.cc#L15)):*
> ```cpp
> namespace roll_pitch_yaw_test {
> 
> const double kepsilon = std::numeric_limits<double>::epsilon();
> ```

`kepsilon` -> kEpsilon`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606)*

**Comment by hongkai-dai** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8606)*

**Comment by jwnimmer-tri** [comment]
Hi @hongkai-dai.  When merging PRs with the http://drake.mit.edu/reviewable.html#curated-commits tag onto master, please note the _"being careful to tweak the the commit message in the github edit box to be a sensible description of the change"_ advice on the first bullet option.  Message like "Fix bugs" and "Update per review" are not sensible descriptions.  Usually, the contents of the top post of the PR (the "Description") is best, though in this case the author didn't provide one.  If you're not sure, you can ask the author to post a commit message to be used, as part of the review.

**Comment by hongkai-dai** [comment]
Thanks @jwnimmer-tri , I will do it next time.

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8606#-:-LApHI2gB-xHEuOVDmHe:bfl5a2g)*

**Pull request merged**
