### PR TITLE
[geometry] Deprecate the "is grad unique" flag from query results

### LINKED ISSUE #14781: Distance to point reports partial information vis a vis non-unique gradients
## Problem

The method `QueryObject::ComputeSignedDistanceToPoint`  returns results in type `SignedDistanceToPoint`. Part of that declared `struct` is the field `SignedDistanceToPoint::is_grad_W_unique`, which, if `true`, indicates that the stored gradient vector is unique for the signed distance field at the query point.

In support of that, we have code like this, to [compute signed distance and gradient in a *box*](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L542-L578). Particular care is used to determine if the query point lies at one of the box's vertices or on its edges. In these cases, the signed distance does *not* have a unique gradient and the returned result reflects that. 

*However*, those are not the *only* cases where the gradient is not unique. If the point lies inside the box anywhere on its medial axis, the gradient is likewise not unique. The same is true for a cylinder ([and has been explicitly called out](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L435-L437)) and all shapes, generally. The signed distance field has a discontinuity in its spatial gradient on the medial axis. The *problem* is that the code in `distance_to_point_callback.h` is ignoring the internal medial axis.

 - For spheres, [we detect distance to the medial axis (the sphere center) based on a tolerance](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L122-L125).
 - Half spaces [have no such problems; the gradient is always unique](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L156-L174).
 - The capsule makes use of the sphere's logic in [whether near the sphere](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L215-L221) or [near the barrel](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/distance_to_point_callback.h#L255-L258).
 - Box and cylinder ignore medial axis as discussed above.

Essentially, the flag is an inconsistent lie.

## Solution

Naively, the solution is to directly correct this so that the flag is always meaningful. Detect the points proximity to all shapes' medial axes with comparable tolerance.

There's a problem with this solution:

1. Reporting that a gradient is not unique has very little utility. We currently don't have any algorithms that make use of this knowledge. But, even if we did, there's very little meaningful action that could be taken given such limited information.
2. It would be far better if in addition to the knowledge that a gradient wasn't unique, that we could communicate the space of valid gradient vectors. For spheres, it would be the unit sphere. For cylinders, it could be a pair of vectors (near the circular edge) or a ring (on the central axis of the cylinder). For capsules, either a hemisphere or ring. For discrete surfaces (e.g., boxes), this would usually be a finite set of vectors (the normal of each equidistant face) or, if *on* the surface, a contiguous portion of the unit sphere (at the box's vertex) or unit circle (on the box's edge). Etc. To fully communicate the space of gradient vectors will require some careful design. However, as with the previous item, we currently have no code that would exercise it.

So, we are left with several options:

1. Leave the code alone (albeit with a sprinkling of TODOs referencing this issue).
2. Clean out the flag reporting uniqueness entirely (as no one can actually use it at this point). Cull it entirely (via deprecation) until we have a pressing need to distinguish non-unique gradients. Just so long as the gradient always be drawn from the set of valid gradients.
3. Fill in the code so that the flag is correct in all cases (the "naive" solution indicated above). This would arguably be pushing the code toward a full solution where we also define the space of non-unique gradient vectors, but, however such a thing would be implemented, it *feels* like that putative implementation *plus* this bool field would be redundant.
4. Devise the means for communicating the valid space of gradient vectors and simply implement that, replacing the current mechanism. At this point, we still don't have any users of this functionality, and it's not clear what the API should be -- how would the end user want to interact with the space of valid gradient vectors considering it can take so many different forms?

## Conclusions

The code, as is, lies. That's not a good thing. The logical step to take is to make it stop lying. That can be done by adding or removing code. Given the presumption that no one cares about the current promise, the code would be simpler if we go with option 2 and clean it out.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
The signed distance to point and signed distance pair query results had a flag indicating whether the returned gradient value was unique or not. While motivated by the best of intentions, it is not used and not correctly implemented (as extensively documented in #14781). The agreed-upon resolution is to simply deprecate that field.

This deprecates the fields in the two structs (and handles the downstream ramifcations).

It is authored as *two* commits -- one for each query result type, to afford the reviewer some convenience in mentally separating the two tasks. The idea is that there is value in keeping all the deprecations in the same PR (as they have enough in common to share mental context), but keep the two slices separate to provide locality). The commits will be treated as curated upon completion.

Closes #14781.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MXnT-iU1yi4KBx48M4e:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[geometry/query_results/signed_distance_pair.h, line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXrkFH929oi1bppYL2_:-MXrkFH929oi1bppYL2a:bdimqal) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_pair.h#L34)):*
> ```objc
> template <typename T>
> struct SignedDistancePair{
>   // Note: While deprecating the is_grad_W_unique, we cannot use the standard
> ```

BTW should this paragraph also contain the deprecation date for easy grepping later?
___
*[geometry/query_results/signed_distance_pair.h, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXrkRX96aPrAznYxx5f:-MXrkRX96aPrAznYxx5g:bdimqal) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_pair.h#L59)):*
> ```objc
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> /* Deprecation note: This constructor is wrapped in a deprecation silencer
> ```

BTW should this paragraph also contain the deprecation date for easy grepping later?
___
*[geometry/query_results/signed_distance_to_point.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshX_-4I4mMrVfiR7h:-MXshX_02lgPG1jbiAFQ:btdldea) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L26)):*
> ```objc
> template <typename T>
> struct SignedDistanceToPoint{
>   // Note: While deprecating the is_grad_W_unique, we cannot use the standard
> ```

BTW same as above -- deprecation date for easy grepping
___
*[geometry/query_results/signed_distance_to_point.h, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshih9-oz4h4YoopvE:-MXshih9-oz4h4YoopvF:btdldea) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L51)):*
> ```objc
> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> /* Deprecation note: This constructor is wrapped in a deprecation silencer
> ```

BTW same as above -- deprecation date for easy grepping
___
*[geometry/query_results/signed_distance_to_point.h, line 145 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshl981UFOKt8B_d07:-MXshl981UFOKt8B_d08:btdldea) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L145)):*
> ```objc
>   Vector3<T> grad_W;
> 
>   // TODO(SeanCurtis-TRI) When it comes time to deprecate, ping the listed
> ```

BTW same as above -- deprecation date for easy grepping

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MY5pWrX4q_FW809RnRV:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MY5pbAt6j0mhwWwNd7P:bwjee3b)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
To confirm my read on linked issue, this implements Solution (2) - "Clean out flag entirely".

:lgtm_strong: platform, with minor nits

> Reviewed 2 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MY6pOXv1KFJhhKr_8oL:b4evw3f)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/test/geometry_test.py, line 825 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MY6qlzK0L2cmNkbfw68:-MY6qlzK0L2cmNkbfw69:b-81jmk2) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/bindings/pydrake/test/geometry_test.py#L825)):*
> ```Python
>     def test_deprecated_struct_member(self):
>         """Tests successful deprecation of struct member"""
>         with catch_drake_warnings(expected_count=1) as w:
> ```

nit `w` is unused. Delete `as w`?
___
*[bindings/pydrake/test/geometry_test.py, line 830 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MY6ql51D4KT5Kcauwuy:-MY6ql51D4KT5Kcauwuz:b-81jmk2) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/bindings/pydrake/test/geometry_test.py#L830)):*
> ```Python
> 
>         data = mut.SignedDistancePair()
>         with catch_drake_warnings(expected_count=1) as w:
> ```

nit `w` is unused. Delete `as w`?
___
*[bindings/pydrake/test/geometry_test.py, line 832 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MY6qV4HBWMeQ-4gqWhT:-MY6qV4HBWMeQ-4gqWhU:bh4afvf) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/bindings/pydrake/test/geometry_test.py#L832)):*
> ```Python
>         with catch_drake_warnings(expected_count=1) as w:
>             # Setting the deprecated field warns.
>             data.is_nhat_BA_W_unique = False
> ```

nit Does not test reading the field.

Consider adding here. (I think you'd just need to set `expected_count=2` since it uses `always` for warning catch...)
___
*[geometry/query_results/signed_distance_pair.h, line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXrkFH929oi1bppYL2_:-MY6pwyO8HySSCNcwx3I:b-qjt2s0) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_pair.h#L34)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW should this paragraph also contain the deprecation date for easy grepping later?
</blockquote></details>

Raising to nit
___
*[geometry/query_results/signed_distance_pair.h, line 59 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXrkRX96aPrAznYxx5f:-MY6plZG010mByK1jez9:b-qjt2s0) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_pair.h#L59)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW should this paragraph also contain the deprecation date for easy grepping later?
</blockquote></details>

Raising to nit
___
*[geometry/query_results/signed_distance_to_point.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshX_-4I4mMrVfiR7h:-MY6q2vj9z8pcSX2lE1X:b-qjt2s0) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW same as above -- deprecation date for easy grepping
</blockquote></details>

Raising to nit
___
*[geometry/query_results/signed_distance_to_point.h, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshih9-oz4h4YoopvE:-MY6q4x09gZWVhPXyzzK:b-qjt2s0) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L51)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW same as above -- deprecation date for easy grepping
</blockquote></details>

Raising to nit
___
*[geometry/query_results/signed_distance_to_point.h, line 145 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MXshl981UFOKt8B_d07:-MY6q6DGDAr-LLwSdA5k:b-qjt2s0) ([raw file](https://github.com/robotlocomotion/drake/blob/ec03a3b38f1519b17cb25af936684729a2fb2b0c/geometry/query_results/signed_distance_to_point.h#L145)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW same as above -- deprecation date for easy grepping
</blockquote></details>

Raising to nit

**Review by SeanCurtis-TRI — COMMENTED** [review]
time stamps spread around.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MY6xfr3DkxEZoXtEHMU:b-tw2x9m)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/test/geometry_test.py, line 833 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14875#-MY782TE3Ce7VOAFOmON:-MY782TE3Ce7VOAFOmOO:b-cfoe1e) ([raw file](https://github.com/robotlocomotion/drake/blob/e74c549c9f3749d35a3a651fdbb8e8c5dffbd324/bindings/pydrake/test/geometry_test.py#L833)):*
> ```Python
>             # Setting the deprecated field warns.
>             data.is_nhat_BA_W_unique = False
>             _ = data.is_nhat_BA_W_unique
> ```

BTW `self.assertFalse(data.is_nhat_BA_W_unique)` was also an option ;)

Not worth extra CI churn tho.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14875#-:-MY7Qu54058XB-2UEKFR:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
