### PR TITLE
Improve scalar-conversion unit tests for affine systems

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Details are in individual commits:
- Add `unique_ptr` support to `is_dynamic_castable`.  Add explicit `nullptr` diagnostic.
- Improve `vector_system_test` conciseness.
- Add scalar conversion tests for `AffineSystem`.
- Add expected-fail scalar conversion tests for `LinearSystem`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6778)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for first review, please.

I think the two CI failures are just git flakes.

**Comment by EricCousineau-TRI** [comment]
:lgtm:
Presently, the failures only look like NumPy compilation warnings...

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6778#-:-Kqi6-Y7MV-xia8Tse5-:bfnryq)*

**Comment by jwnimmer-tri** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test_utilities/scalar_conversion.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6778#-KqiJ1SHZFkeCjAeNPd6:-Kqj-6Mjq0B-BMip5krf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/64bc2b3bc0f78cfd9c6cfbf444af56554bb76c6a/drake/systems/framework/test_utilities/scalar_conversion.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should give a suitable signature for the Callback here (and below).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6778)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6778)*

**Pull request merged**
