### PR TITLE
Remove scs from drake.cps

### PR DESCRIPTION
**Pull request by jamiesnape**
Not needed because `scsdir` is a shared library and its headers are not used within public headers of drake. `scsindir` is unused.

FYI @hongkai-dai.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7581)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7581#-:-L0AF4PHP7etQkoNmTuF:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7581#-:-L0AP31wJe0M-KUB9eRP:bnfp4nl)*

**Pull request merged**
