### PR TITLE
[examples] Update examples to make use of AddMultibodyPlantSceneGraph

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
In various locations, MultibodyPlants and SceneGraphs were being created and connected by hand. This updates many of those examples to the preferred mechanism.

There are different categories of changes:
 - Simple
   - A large number of locales was a simple API change. Individually instantiated Mbp and SG simply get replaced.
 - MultibodyPlant factories
   - In examples/multibody, there were a couple of functions that would create and populate the plant. These factory methods are not compatible with AddMultibodyPlantSceneGraph.
   - The factories have been changed to populating existing plants.
   - This allows for the call sites to be upgraded.
   - The examples were also unified in their semantics; the examples are now more consistent.
     - The example files have been renamed to be consistent.

This doesn't address all cases where plants and scene graphs get managed by hand. The following remain untouched:
  - ManipulationStation: maintains its own instances of MbP and SG so that it can be populated before being built into a diagram.
  - examples/scene_graph/bouncing_ball_plant.*
    - This is a bespoke plant with its own dynamics. It connected to SG for visualization. This must still register and connect to SceneGraph by hand.

relates #11448

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17580)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17580#-:-N6xzz6b3CeNyyF-Ytff:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17580#-:-N734Sn1-mG_WaOFrwhe:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17580#-:-N7HiL1q4EKEpVx9JP45:bnfp4nl)* status: 9 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`examples/kinova_jaco_arm/jaco_simulation.cc` line 66 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HeR5VC6vL33XciK_H:-N7HeR5W5HYsCUcZjsqK:b-kvoynw) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/kinova_jaco_arm/jaco_simulation.cc#L66)):*
> ```cpp
> 
>   const multibody::ModelInstanceIndex jaco_id =
>       Parser(&jaco_plant, &scene_graph)
> ```

nit To my understanding, passing the `scene_graph` to the `Parser` here is not required, and thus our custom should be to omit it.
___
*[`examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HghoD4sUsPsDJwc17:-N7HghoD4sUsPsDJwc18:bnxvf3f) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc#L122)):*
> ```cpp
> 
>   PopulateBallPlant(radius, mass, FLAGS_hydroelastic_modulus,
>                       FLAGS_dissipation, coulomb_friction,
> ```

nit Bad indentation.  FLAGS should align with radius at +0, not +2.
___
*[`multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7Hi3EO3mZ_YnBn2MuF:-N7Hi3EPAVztYIDY4B0M:bf78qao) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc#L41)):*
> ```cpp
>     // Create the plant.
>     systems::DiagramBuilder<double> builder;
>     auto [plant, scene_graph] =
> ```

nit Since we don't need the scene_graph for anything, we should use the simpler assignment overload that just assigns only to a `plant_` (no square brackets).
___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.h` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HgAOg95R--bg9Q9hV:-N7HgAOg95R--bg9Q9hW:biplm7o) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.h#L36)):*
> ```objc
> ///   geometry for contact modeling.
> /// @pre `plant` is unfinalized and registered with a SceneGraph.
> /// @throws std::exception if plant is nullptr.
> ```

nit This is not accurate.  (It doesn't throw, it aborts.)  I'd just delete the comment here entirely.  The prior line already implies non-nullness.
___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.h` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HgBh53EkUGUphDwFW:-N7HgBh53EkUGUphDwFX:b-r1ai2k) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.h#L43)):*
> ```objc
>     const drake::multibody::CoulombFriction<double>&
>     surface_friction, const Vector3<double>& gravity_W,
>     drake::multibody::MultibodyPlant<double>* plant = nullptr);
> ```

nit The plant is not allowed be null.  Defaulting it to null here serves no purpose.
___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HgN_f0DAHRtVESumm:-N7HgN_f0DAHRtVESumn:b-d84its) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc#L64)):*
> ```cpp
>   DRAKE_DEMAND(plant != nullptr);
>   DRAKE_ASSERT(!plant->is_finalized());
>   DRAKE_ASSERT(plant->get_source_id().has_value());
> ```

nit There is no reason to use `DRAKE_ASSERT` in an example program.  The computational performance here has no bearing on anything.
___
*[`examples/multibody/rolling_sphere/populate_ball_plant.h` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HfuS6CK89OC_4hJJr:-N7HfuS6CK89OC_4hJJs:bggqmlm) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/rolling_sphere/populate_ball_plant.h#L48)):*
> ```objc
> ///   If 'true', the ground will have a _soft_ hydroelastic representation
> ///   (rigid otherwise).
> /// @param plant
> ```

nit Seems worth noting, for clarity?



_Suggestion:_
```objc
@param[in,out] plant
```
___
*[`examples/multibody/rolling_sphere/populate_ball_plant.h` line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7Hg0EbCqXJc9o7w3P4:-N7Hg0EbCqXJc9o7w3P5:biplm7o) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/rolling_sphere/populate_ball_plant.h#L52)):*
> ```objc
> ///   geometry for contact modeling.
> /// @pre `plant` is unfinalized and registered with a SceneGraph.
> /// @throws std::exception if plant is nullptr.
> ```

nit This is not accurate.  (It doesn't throw, it aborts.)  I'd just delete the comment here entirely.  The prior line already implies non-nullness.
___
*[`examples/multibody/rolling_sphere/populate_ball_plant.cc` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17580#-N7HgWGtCWWlHdRGKrt7:-N7HgWGtCWWlHdRGKrt8:b-d84its) ([raw file](https://github.com/robotlocomotion/drake/blob/32841c95717acd2618f65cd4357576fae61e49ca/examples/multibody/rolling_sphere/populate_ball_plant.cc#L33)):*
> ```cpp
>   DRAKE_DEMAND(plant != nullptr);
>   DRAKE_ASSERT(!plant->is_finalized());
>   DRAKE_ASSERT((plant->get_source_id().has_value()));
> ```

nit There is no reason to use `DRAKE_ASSERT` in an example program.  The computational performance here has no bearing on anything.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17580)* status: missing label for release notes (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
For release notes, there would be an argument for "none" as a kind of "documentation-only" change.  However, since some bazel-public (but neither installed nor Stable) header files have changed names and signatures, I'll say +(release notes: fix).

**Pull request merged**
