### PR TITLE
Fix a Bug in GCS When Passing in a Trivially-Infeasible Upper Bound

### PR DESCRIPTION
**Pull request by cohnt**
There was a slight logic error, where we were checking the lower bound instead of the upper bound. The current test cases didn't cover it because they didn't make sure that code path was tested. This PR adds test cases to reveal the bug, and implements the fix.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090)

### CODE REVIEW

**Comment by cohnt** [comment]
+@russtedrake mind taking this one? Hopefully it should be pretty quick, but I think it ought to merge before #22091.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  (i had already reviewed it as a part of #22091, but I like that you've separated it out)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-:-OAxUwc73HAN6sgHeBx1:b-ye0ucn)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-:-OAxV6g-53W9jgtfDMpi:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-:-OAxYHG4BGykA7lbVUTO:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1773 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-OAxYl0A72RYYWcS8hqk:-OAxYl0A72RYYWcS8hql:b3rbhse) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e2a8c0ff4dc4421e9a0eafa4656bd7b49939853/geometry/optimization/test/graph_of_convex_sets_test.cc#L1773)):*
> ```cpp
>   // trivially-infeasible constraint, so solving should throw an error.
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       g_.SolveShortestPath(*source_, *target_, options_), ".*inf.*");
> ```

minor: this test clause should probably match on a bit more of the expected error text -- we have other throws in the same module with either "inf" for infinity or "infeasible".

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1773 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-OAxYl0A72RYYWcS8hqk:-OAyBGP7CstTBJ4X50f-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e2a8c0ff4dc4421e9a0eafa4656bd7b49939853/geometry/optimization/test/graph_of_convex_sets_test.cc#L1773)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor: this test clause should probably match on a bit more of the expected error text -- we have other throws in the same module with either "inf" for infinity or "infeasible".
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1819 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-OAyhpAN-8ogN5FuvxBZ:-OAyhpAN-8ogN5FuvxB_:b-mvpy9e) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea3d82f8032d6de918537d9aa46a6783df822f0a/geometry/optimization/test/graph_of_convex_sets_test.cc#L1819)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       g_.SolveShortestPath(*source_, *target_, options_),
>       ".*trivially-infeasible.*");
> ```

nit this is better; thanks. My last question is this: there are two error mesages in the implementation that match this pattern. One is for lower-bound failure, the other for upper-bound failure. Given that we are here fixing a lower-upper bound confusion already, is it worth having the test be able to sense which message actually got thrown?

**Review by cohnt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22090)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`geometry/optimization/test/graph_of_convex_sets_test.cc` line 1819 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22090#-OAyhpAN-8ogN5FuvxBZ:-OAzE-jV6NJRoqWKiPM3:bjinqhd) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea3d82f8032d6de918537d9aa46a6783df822f0a/geometry/optimization/test/graph_of_convex_sets_test.cc#L1819)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this is better; thanks. My last question is this: there are two error mesages in the implementation that match this pattern. One is for lower-bound failure, the other for upper-bound failure. Given that we are here fixing a lower-upper bound confusion already, is it worth having the test be able to sense which message actually got thrown?
</blockquote></details>

I made it also match `x >= +inf` or `x <= -inf`, so we can tell which case it's hitting.

**Pull request merged**
