### PR TITLE
Comment code to temporarily ignore Valgrind error

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards #8779

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8780)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by soonho-tri** [comment]
:lgtm:

/cc @ggould-tri , it seems that valgrind doesn't like the lambdas in `INSTANTIATE_TEST_CASE_P`. I'll uncomment them by adding the boilerplates.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/test/symbolic_simplification_test.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8780#-LC4aI8MDYllwRuILqwP:-LC4aI8MDYllwRuILqwQ:b-wouyyd) ([raw file](https://github.com/robotlocomotion/drake/blob/b5eff18ec517a6d0f597a32d27c7121aaea87e85/common/test/symbolic_simplification_test.cc#L289)):*
> ```cpp
> 
> // TODO(soonho-tri) Unroll this
> //INSTANTIATE_TEST_CASE_P(
> ```

BTW, I guess the code-linter complain about no space between `//` and `IN...`? If not, please ignore this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8780#-:-LC4aR-kDtF8KlB2pTAY:bo1irzt)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please

**Comment by m-chaturvedi** [comment]
*[common/test/symbolic_simplification_test.cc, line 289 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8780#-LC4aI8MDYllwRuILqwP:-LC4c7iq2hfmRYTX5ddO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5eff18ec517a6d0f597a32d27c7121aaea87e85/common/test/symbolic_simplification_test.cc#L289)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I guess the code-linter complain about no space between `//` and `IN...`? If not, please ignore this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8780)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8780)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot   linux-xenial-gcc-bazel-experimental-memcheck-valgrind please.

**Comment by m-chaturvedi** [comment]
+@SeanCurtis-TRI for platform review, please

**Comment by m-chaturvedi** [comment]
Alternatively, https://github.com/RobotLocomotion/drake/pull/8784

**Comment by soonho-tri** [comment]
Closed by https://github.com/RobotLocomotion/drake/pull/8784

**Pull request closed without merging**
