### PR TITLE
Rename StateSupervector to Supervector and StateSubvector to Subvector.

### PR DESCRIPTION
**Pull request by david-german-tri**
Contributes to #3208.

+@amcastro-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3606)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3606#-:-KSlKRct9fwVAIMqG2EH:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3606#-:-KSl_zer4exmZ4O8K0tz:bzdwe9o)*

**Comment by david-german-tri** [comment]
+@sammy-tri for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3606#-:-KSla_0iEljcjKo1k6xw:bq11ftp)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3606#-:-KSlgIxqtHlHVB7cFKnI:bnfp4nl)*

**Pull request merged**
