### PR TITLE
doc: Move Jekyll Markdown pages to `_pages`, hoist headings

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14657

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14658)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ggould-tri for feature review, please!

\cc @iantheengineer @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14658#-:-MTkOcks7F-YdTY7pbuh:b-2c574p)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14658)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14658#-MTkOkIv-cyNKDPskWaJ:-MTkOkIv-cyNKDPskWaK:b-8b3gsp) (no related file):*
Working: I would like to ensure that I can do a merge commit, not a squash-merge.
Will try to rebase onto latest master to avoid "long forks".

---

**Comment by EricCousineau-TRI** [comment]
(Make that both reviews, since this is purty simple?)

**Comment by jamiesnape** [comment]
The `_pages` directory is for blog post functionality, usually. Any reason why we are using it for general web pages?

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; I agree single reviewer is fine.

> Reviewed 54 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14658#-:-MTkU2qMAFz_rrauAbJL:b733fsw)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14658)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14658#-MTkOkIv-cyNKDPskWaJ:-MTlAMV4CsBKnS0WOrR0:b-8b14oz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I would like to ensure that I can do a merge commit, not a squash-merge.
Will try to rebase onto latest master to avoid "long forks".
</blockquote></details>

OK Rebased. Now going to do a merge commit.

---

**Comment by EricCousineau-TRI** [comment]
Confirmed pretty graph:
```
$ git log HEAD~2..HEAD --graph --oneline --no-decorate
*   a0327e7a87 Merge pull request #14658 from EricCousineau-TRI/issue-14575-breakoff-pr3
|\  
| * a7dc79185a doc: Hoist all Jekyll markdown headings to h1 level
| * d64be807a5 doc: Move all Jekyll Markdown pages under `_pages` collection
|/  
* def7d592c4 getting_help: Add hints for Binder / Colab (#14660)
```

\cc @jwnimmer-tri

**Pull request merged**
