### PR TITLE
change test valkyrie balancing test size to medium.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4029)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-continuous-matlab-debug please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jamiesnape** [comment]
Only just over the "small" timeout.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4029#-:-KVko0FDRkvDwn8wnL4e:bnfp4nl)*

**Comment by jamiesnape** [comment]
@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4029#-:-KVlCpnKq14UeZK02mhu:bnfp4nl)*

**Pull request merged**
