### PR TITLE
Render __init__ docstrings in pydrake Sphinx documentation

### LINKED ISSUE #9651: python sphinx is missing LeafSystem._DeclareAbstractOutputPort and related methods
The documentation here:
http://drake.mit.edu/pydrake/pydrake.math.html?highlight=rigidtransform#pydrake.math.RigidTransform

does not capture the constructor bindings I see here:
https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/math_py.cc#L69

Not sure how wide spread the issue is.  Just wanted to capture the instance I observed.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #9651.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9652)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for feature and platform review. FYI @RussTedrake.

**Comment by EricCousineau-TRI** [comment]
Ran it on my machine, but do not see constructor docs for `RigidTransform` on f383e0f; documentation for `RigidTransform`:
```
+ RigidTransform.__doc__
This class represents a proper rigid transform between two frames
which can be regarded in [...]

+ RigidTransform.__init__.__doc__
__init__(*args, **kwargs)
Overloaded function.

1. __init__(self: pydrake.math.RigidTransform) -> None

[...]
```

What I'm seeing:
> 
image

**Comment by EricCousineau-TRI** [comment]
My system:
```
$ sphinx-build --version
Sphinx (sphinx-build) 1.3.6
```

**Comment by jamiesnape** [comment]
This is what I get with sphinx 1.8.0:
image

**Comment by EricCousineau-TRI** [comment]
Seems that it was introduced in `v1.5`:
https://github.com/sphinx-doc/sphinx/commit/f77fc625#diff-58b8e2d8df3a9dbfa0340765df1e0b0cR227

Should we just add `github_repository` for `sphinx` the RTD theme?

**Comment by EricCousineau-TRI** [comment]
If you'd like, I can do that. I'd like to factor `//doc` and `//bindings/pydrake/doc` to share code; had to duplicate stuff when doing `py3` migration stuff, would be nice to fix that before then.

**Comment by jamiesnape** [comment]
I imagine we could. For now moving the documentation generation to a Bionic instance would be a workaround.

**Comment by jamiesnape** [comment]
> If you'd like, I can do that. I'd like to factor //doc and //bindings/pydrake/doc to share code; had to duplicate stuff when doing py3 migration stuff, would be nice to fix that before then.

Sure, feel free to do so.

**Comment by jamiesnape** [comment]
Can we merge this is in the interim and I fire up a Bionic instance to fix the online docs? It is isn't going to break anything on Xenial.

**Pull request merged**
