### PR TITLE
Rename :multi_body_parsers to :parsers by convention

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4533)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@liangfok for all review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4533#-:-KZ8mKw-3BEBjarIk7Bj:bhbkg2p)*

**Comment by liangfok** [comment]
:lgtm: also CC @amcastro-tri since I just recalled he recommended the switch from parsers to MultibodyParsers.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4533#-:-KZ8tiAf37fJjlzqYEmK:b-2qdemk)*

**Comment by jwnimmer-tri** [comment]
I just went back and looked at that discussion in #4482.  It was referring to the CMake library name, which is globally scoped (and thus I agree should include Multibody).  Here, we are already scoped within `//drake/multibody/parsers` so using `:parsers` seems consistent with the spirit of that request.

:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4533#-:-KZ90LoJGTikRl965f45:bvliu8)*

**Comment by liangfok** [comment]
Great! SGTM.

**Pull request merged**
