### PR TITLE
[fem] Add Rayleigh damping model

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #16492

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@mitiguy for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-MuwVztS4EgGmX4fPNGX:b-zte3n)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
Thanks for making the changes per f2f / peer coding.  

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-Mv0lqgZ96nIjgMSYpAy:b-bhr3hk)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by xuchenhan-tri — COMMENTED** [review]
Addressed the f2f comments. PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-Mv0nCGn16t3Frpa8i9p:bvf447c)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-Mv0xYUt74yglVsGPP4X:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by mitiguy — COMMENTED** [review]
Platform review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-Mv0xbgu3AayGTBAonH2:b-sh0554)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496#-:-Mv12q7rEJkSsvo9vkkt:b-vtj4vo)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[multibody/fem/damping_model.h, line 32 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv12FZt7zMAlthzCEEc:-Mv12FZt7zMAlthzCEEd:b-jroz97) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L32)):*
> ```objc
>   /** Constructs a Rayleigh damping model by storing the mass coefficient α and
>    the stiffness coefficient β that appears in the damping matrix D = αM + βK.
>    @throw std::exception if either `mass_coeff_alpha` or `stiffness_coeff_beta_`
> ```

nit The trailing underscore here isn't relevant to the reader of the docs.



_Suggestion:_
```objc
stiffness_coeff_beta
```
___
*[multibody/fem/damping_model.h, line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10aPV7sFRKvrZZGNR:-Mv10aPW5Kfbnby_FXSH:bppw8m4) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L34)):*
> ```objc
>    @throw std::exception if either `mass_coeff_alpha` or `stiffness_coeff_beta_`
>    is negative. */
>   DampingModel(T mass_coeff_alpha, T stiffness_coeff_beta)
> ```

nit Either pass-by-const-reference, or std::move into the members fields.
___
*[multibody/fem/damping_model.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10DRA-mcqeEOj5Ud5:-Mv10DRA-mcqeEOj5Ud6:b-xnrqia) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L36)):*
> ```objc
>   DampingModel(T mass_coeff_alpha, T stiffness_coeff_beta)
>       : mass_coeff_alpha_(mass_coeff_alpha),
>         stiffness_coeff_beta_(stiffness_coeff_beta) {
> ```

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

This constructor body should live the cc file.  Throwing error messages or copying autodiff quantities on the heap is machine-code costly, and this constructor does not appear to be a performance-critical item.
___
*[multibody/fem/damping_model.h, line 37 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv118rr6r534dXafxYg:-Mv118rr6r534dXafxYh:b58ua13) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L37)):*
> ```objc
>       : mass_coeff_alpha_(mass_coeff_alpha),
>         stiffness_coeff_beta_(stiffness_coeff_beta) {
>     if (mass_coeff_alpha < 0.0 || stiffness_coeff_beta < 0.0) {
> ```

nit Did you want to reject NaNs here?

Aside: throwing carefully-crafted prose texual messages has the benefit of being florid, but is always extra work and isn't really that helpful unless you're echoing back the invalid values anyway.  The boring answer here is still pretty readable in the error text, and handles NaNs in the usual way:

```c++
DRAKE_THROW_UNLESS(mass_coeff_alpha >= 0.0);
```

It will also work with Expression in the future, whereas the bespoke error-checks will not.
___
*[multibody/fem/damping_model.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10yUy2Y7RtJqDvHYQ:-Mv10yUz3H1WkeSv4B8Z:b-hlw66j) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L49)):*
> ```objc
>  private:
>   T mass_coeff_alpha_;
>   T stiffness_coeff_beta_;
> ```

nit https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization



_Suggestion:_
```objc
  T mass_coeff_alpha_{};
  T stiffness_coeff_beta_{};
```
___
*[multibody/fem/test/damping_model_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv12_T1-6NI9ly-4U8S:-Mv12_T1-6NI9ly-4U8T:b-fg569o) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/test/damping_model_test.cc#L22)):*
> ```cpp
> GTEST_TEST(DampingModelTest, InvalidModel) {
>   /* Negative coefficients are not allowed. */
>   DRAKE_EXPECT_THROWS_MESSAGE(DampingModel<double>(1.0, -1.0), std::exception,
> ```

nit _Only test for a specific subtype of std::exception when the subtype is necessary to determine whether the code behaved correctly, e.g., in cases where the code may throw several different types of exception and the subtype fully disambiguates which condition was triggered. (This is rare.)_

-- https://drake.mit.edu/styleguide/cppguide.html#Exceptions

Ditto below.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @mitiguy)

___
*[multibody/fem/damping_model.h, line 34 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10aPV7sFRKvrZZGNR:-Mv1ElsS7WeT5geokwPe:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Either pass-by-const-reference, or std::move into the members fields.
</blockquote></details>

Done, thanks.
___
*[multibody/fem/damping_model.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10DRA-mcqeEOj5Ud5:-Mv1CL_b4kQKv9Gh-bJw:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

This constructor body should live the cc file.  Throwing error messages or copying autodiff quantities on the heap is machine-code costly, and this constructor does not appear to be a performance-critical item.
</blockquote></details>

Done, thanks.
___
*[multibody/fem/damping_model.h, line 37 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv118rr6r534dXafxYg:-Mv1CHq72TWV-s5Af3lO:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Did you want to reject NaNs here?

Aside: throwing carefully-crafted prose texual messages has the benefit of being florid, but is always extra work and isn't really that helpful unless you're echoing back the invalid values anyway.  The boring answer here is still pretty readable in the error text, and handles NaNs in the usual way:

```c++
DRAKE_THROW_UNLESS(mass_coeff_alpha >= 0.0);
```

It will also work with Expression in the future, whereas the bespoke error-checks will not.
</blockquote></details>

Done, thanks.
___
*[multibody/fem/damping_model.h, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv10yUy2Y7RtJqDvHYQ:-Mv1E_FC8Ado2wfn4HVX:b-pksan3) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/damping_model.h#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization
</blockquote></details>

Strike two for today :(
___
*[multibody/fem/test/damping_model_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv12_T1-6NI9ly-4U8S:-Mv1EHUt1BcLl0SiatJd:bex64hf) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/test/damping_model_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit _Only test for a specific subtype of std::exception when the subtype is necessary to determine whether the code behaved correctly, e.g., in cases where the code may throw several different types of exception and the subtype fully disambiguates which condition was triggered. (This is rare.)_

-- https://drake.mit.edu/styleguide/cppguide.html#Exceptions

Ditto below.
</blockquote></details>

I don't understand this comment. The specific subtype is not tested here. Could you clarify the defect?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mitiguy (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/damping_model_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv12_T1-6NI9ly-4U8S:-Mv1Ff5-CxnIhbnW4wpJ:b-883mag) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/test/damping_model_test.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't understand this comment. The specific subtype is not tested here. Could you clarify the defect?
</blockquote></details>

OK That's true.  On the other hand, the middle argument to DRAKE_EXPECT_THROWS_MESSAGE is not required, so saying "std::exception" when you were already checking the text was just extra line noise for no benefit.  In any case, the new code here is fine, and I'm working on deprecating the middle macro argument now, in any case.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16496)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mitiguy (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/damping_model_test.cc, line 22 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16496#-Mv12_T1-6NI9ly-4U8S:-Mv1GHouCRTElfse_fTc:b-9yh4ov) ([raw file](https://github.com/robotlocomotion/drake/blob/045c9544ba35f5b6fc41db11e89c85a8ae4214ec/multibody/fem/test/damping_model_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK That's true.  On the other hand, the middle argument to DRAKE_EXPECT_THROWS_MESSAGE is not required, so saying "std::exception" when you were already checking the text was just extra line noise for no benefit.  In any case, the new code here is fine, and I'm working on deprecating the middle macro argument now, in any case.
</blockquote></details>

I see. The confusion comes from that I thought the middle argument is required  in DRAKE_EXPECT_THROWS_MESSAGE. Good to know that it's going away.

**Pull request merged**
