### PR TITLE
Implements mesh inflation for non-convex meshes

### PR DESCRIPTION
**Pull request by amcastro-tri**
Towards #21514 and related wobbling in our sims.

The "2-days" work discussed in #21528.  
I believe the docs already explain well what this does.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review please.
FYIm, this is the same code I run in Anzu.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-:-O2_uWAC1OgdwwGNWvLA:bv8yutc)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some small stuff.

I like this.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-:-O2aWcerBKIreUNyksTd:b-m5sgdq)* status: 11 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aQ7zZDURqzSfXo-jZ:-O2aQ7zZDURqzSfXo-j_:b-o3kb7w) (no related file):*
Because of the inseparable nature of the problem you're solving, the normals of the inflated mesh can deviate from their original direction. Do you have an intuition for how much they can deviate and what the worst case would be?

Obviously, for vertices in a nearly planar regime (or even in a radially symmetrical regime), there probably wouldn't be much perturbation, but near sharp creases in the mesh, it seems there's a much greater possibility for that. Have you given any concrete time to consider what the resultant mesh might look like in the adversarial cases?

___
___
*[`geometry/proximity/inflate_mesh.h` line 0 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aNFdC94icnVFVED1V:-O2aNFdC94icnVFVED1W:bopd5x6) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.h#L0)):*
nit: You should put some notes about the assumption of the input mesh being "watertight". For volume meshes, "watertight" means something a bit different, but nevertheless analogous with a surface mesh. Hydroelastic doesn't require a "connected" topology of the volume mesh. If a user passed in a tet soup, hydro wouldn't worry (because the result is likewise a tri soup).

However, the result of *this* algorithm very much cares. If I gave you a tet soup:

- all vertices would be 'external" when, originally, they weren't.
- If you have cracks in the "watertightness" at the surface, this algorithm will likely expand the cracks.

We need to document this clearly. We should also add something in hydroelastic notes somewhere about the additional requirements on the vtk tet mesh if we use a non-zero margin.

(On the other hand, the pressure field calculation would also get really cranky, and if Damrong's validation software runs, it'll also complain about the fact that all vertices lie on the surface.) So, having a connected topology isn't a requirement *unique* to this function, but it is a requirement.
___
*[`geometry/proximity/inflate_mesh.h` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKACv79avV0ZvUcIj:-O2aKACw8oAoE5D9nL7G:b-ntmvit) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.h#L21)):*
> ```objc
> it is relaxed so that the margin layer is at least of thickness δ.
> 
> This problem is formulated in terms of a QP with guaranteed solution.
> ```

BTW The language as is is *arguably* correct, but stilted. A slight edit makes it more easily accepted.



_Suggestion:_
```objc
with a guaranteed
```
___
*[`geometry/proximity/inflate_mesh.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKV3kBZupxN3kvtGJ:-O2aKV3kBZupxN3kvtGK:bm1y6gh) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L23)):*
> ```cpp
> /* Implements the QP program to inflate a mesh by a given margin amount.
>  This can be written as:
>    min 1/2‖u‖|²
> ```

BTW Is the 1/2 constant worth keeping, given that you're minimizing? Both functions minimize with the same `u`.
___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKjByB9KtE5-qeA0F:-O2aKjByB9KtE5-qeA0G:b-chn067) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
> ```cpp
> 
>   // Crate an optimization program to inflate `mesh` and amount `margin.`
>   explicit InflateProgram(VolumeMesh<double> mesh, double margin);
> ```

nit: Not necessary; you have two required parameters.



_Code quote:_
```cpp
explicit
```
___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKsvlDcABdJIXobKl:-O2aKsvlDcABdJIXobKm:bwygwy5) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
> ```cpp
> 
>   // Crate an optimization program to inflate `mesh` and amount `margin.`
>   explicit InflateProgram(VolumeMesh<double> mesh, double margin);
> ```

btw do you really mean to copy the mesh in secret? If, for example, margin is zero, you copy this mesh *twice* instead of just once. In the case of non-zero margin, you copy this and then create a brand new mesh. One copy is completely unnecessary.

Recommendation:

1. Pass by const pointer.
2. Capture it in a const reference in the constructor.
3. Document that the mesh gets aliased and has to stay alive, blah, blah, blah.



_Code quote:_
```cpp
VolumeMesh<double> mesh
```
___
*[`geometry/proximity/inflate_mesh.cc` line 116 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aOYE-8w79zDD3KyS2:-O2aOYE-8w79zDD3KyS3:b98hwfv) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L116)):*
> ```cpp
>     throw std::runtime_error(
>         "Failure to inflate mesh. Unless there is a bug, the procedure to "
>         "apply margins to non-convex meshes is guaranteed succeed. You might "
> ```

nit grammar



_Suggestion:_
```cpp
is guaranteed to succeed.
```
___
*[`geometry/proximity/inflate_mesh.cc` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aOhKr1A1s269dk8t_:-O2aOhKr1A1s269dk8ta:b-6ju494) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L121)):*
BTW The second comment contradicts the first comment.  How about:

> The solution corresponds to the dimensionless displacements ũ for each vertex of the input volume mesh. Scaling by the margin, gives us the displacements u.
___
*[`geometry/proximity/inflate_mesh.cc` line 133 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aPizN5VNE88hzYE5d:-O2aPizN5VNE88hzYE5e:b-8ge4xh) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L133)):*
> ```cpp
>   for (int s = 0; s < ssize(surface_to_volume_vertices_); ++s) {
>     const int v = surface_to_volume_vertices_[s];
>     vertices[v] += u.segment<3>(3 * v);
> ```

nit: v is a volume vertex index, s is a surface index, but s doesn't appear in this expression. However, `u` includes only surface vertices; we should be indexing into it using `s` and not `v`.

N.B. Your test isn't sensitive to whether I use `s` on the right side or not. This is because the mesh you're using in the test has only a single interior vertex, and it is the *last* one. So, the mapping from surface to vertex indices is, in fact, the identity. When I modify the file (by moving the interior vertex to be index 0), the test fails. But changing the `v` to an `s` on the right side, the test passes again.

Here's the diff to apply to `non_convex_mesh.vtk` to reveal the bug. I'd suggest applying it in this PR so the input mesh is generally more interesting for all applications.

```diff
--- a/geometry/test/non_convex_mesh.vtk
+++ b/geometry/test/non_convex_mesh.vtk
@@ -3,20 +3,20 @@ Example of non-convex tetrahedral mesh
 ASCII
 DATASET UNSTRUCTURED_GRID
 POINTS 6 double
+0.1 0.1 0.1
 0.0 0.0 0.0
 1.0 0.0 0.0
 0.0 1.0 0.0
 0.0 0.0 1.0
 0.2 0.2 0.2
-0.1 0.1 0.1
 
 CELLS 6 30
-4   5 4 1 2
-4   5 4 2 3
-4   5 4 3 1
-4   5 0 3 2
-4   5 0 2 1
-4   5 0 1 3
+4   0 5 2 3
+4   0 5 3 4
+4   0 5 4 2
+4   0 1 4 3
+4   0 1 3 2
+4   0 1 2 4
 
 CELL_TYPES 6
 10
```



_Suggestion:_
```cpp
    vertices[v] += u.segment<3>(3 * s);
```
___
*[`geometry/proximity/test/inflate_mesh_test.cc` line 78 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aVRcn-JQnJ2SsGKRo:-O2aVRcn-JQnJ2SsGKRp:bgomnmo) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/test/inflate_mesh_test.cc#L78)):*
> ```cpp
>       const Vector3d u = p_inflated - p;
> 
>       EXPECT_GE(u.dot(n), margin);
> ```

BTW This is the last thing the test does. If something happens and this code breaks, you're going to flood the log with a *billion* messages that this failed for (e, v) combos. Probably friendlier to make it `ASSERT_GE` so you can fail on the first one (and maybe even indicate the quantities that made the test angry).
___
*[`geometry/proximity/test/inflate_mesh_test.cc` line 97 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aUO-lClqWFmGILhZx:-O2aUO-lClqWFmGILhZy:b-mi5wq1) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/test/inflate_mesh_test.cc#L97)):*
nit:.

> ...not even for large margin values.

Is it clear to a passive reader that 0.1 is large?  The reader has no context.

Looking at the mesh in question, I can see that its bounding box is 1m on the side, but, even then, it's not clear that a margin of 0.1 is "large". Probably better to provide a bit more elaboration on the reasoning here.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: 2 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aQ7zZDURqzSfXo-jZ:-O2e62Q7EXvR_RgFjATt:b-7vxz3e) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Because of the inseparable nature of the problem you're solving, the normals of the inflated mesh can deviate from their original direction. Do you have an intuition for how much they can deviate and what the worst case would be?

Obviously, for vertices in a nearly planar regime (or even in a radially symmetrical regime), there probably wouldn't be much perturbation, but near sharp creases in the mesh, it seems there's a much greater possibility for that. Have you given any concrete time to consider what the resultant mesh might look like in the adversarial cases?
</blockquote></details>

I did think about this. However I was not able to come up with a good example and no, I do not have a good intuition on how normals could depart from their original normals.

Now, from a practical point of view, you've seen the meshes that I stressed tested this with (with large margin values), and the method seems to do very well. From that practical point of view I am very satisfied with this.

As you, I'd love to have some other example or even unit test to highlight this particular property of the method. I'll keep thinking about it. If you do happen to come up with something let me know. 

___
___
*[`geometry/proximity/inflate_mesh.h` line  at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aNFdC94icnVFVED1V:-O2e75Kx79xvzHMkiJZq:b-fc7pk8) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.h#L)):*
I updated the docs for this function. PTAL.

> Damrong's validation software runs

Are those in Drake? Maybe we could ask that software to require "watertight" volume meshes when margin is non-zero?
___
*[`geometry/proximity/inflate_mesh.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKV3kBZupxN3kvtGJ:-O2e9DPZDdwTOR7zH9zh:bto08y2) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is the 1/2 constant worth keeping, given that you're minimizing? Both functions minimize with the same `u`.
</blockquote></details>

I keep it for two reasons:
1. it is standard for quadratic programs
2. it actually is what MP implements.

Though you are right  that mathematically it makes no difference.
___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKsvlDcABdJIXobKl:-O2e9lwN6l5I0I1P8Kx8:bu658vl) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw do you really mean to copy the mesh in secret? If, for example, margin is zero, you copy this mesh *twice* instead of just once. In the case of non-zero margin, you copy this and then create a brand new mesh. One copy is completely unnecessary.

Recommendation:

1. Pass by const pointer.
2. Capture it in a const reference in the constructor.
3. Document that the mesh gets aliased and has to stay alive, blah, blah, blah.
</blockquote></details>

the constructor is moving into `mehs_`. Calling code has the option to move into the ctor.
Now, I should probably allow moving into the public function argument as well. When I used this in proximity engine I  was force to make copies anywa. But I'll revisit this when we land that piece separately. 
___
*[`geometry/proximity/inflate_mesh.cc` line 133 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aPizN5VNE88hzYE5d:-O2eB29r7OXI682vxjRW:b-3itsmv) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L133)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: v is a volume vertex index, s is a surface index, but s doesn't appear in this expression. However, `u` includes only surface vertices; we should be indexing into it using `s` and not `v`.

N.B. Your test isn't sensitive to whether I use `s` on the right side or not. This is because the mesh you're using in the test has only a single interior vertex, and it is the *last* one. So, the mapping from surface to vertex indices is, in fact, the identity. When I modify the file (by moving the interior vertex to be index 0), the test fails. But changing the `v` to an `s` on the right side, the test passes again.

Here's the diff to apply to `non_convex_mesh.vtk` to reveal the bug. I'd suggest applying it in this PR so the input mesh is generally more interesting for all applications.

```diff
--- a/geometry/test/non_convex_mesh.vtk
+++ b/geometry/test/non_convex_mesh.vtk
@@ -3,20 +3,20 @@ Example of non-convex tetrahedral mesh
 ASCII
 DATASET UNSTRUCTURED_GRID
 POINTS 6 double
+0.1 0.1 0.1
 0.0 0.0 0.0
 1.0 0.0 0.0
 0.0 1.0 0.0
 0.0 0.0 1.0
 0.2 0.2 0.2
-0.1 0.1 0.1
 
 CELLS 6 30
-4   5 4 1 2
-4   5 4 2 3
-4   5 4 3 1
-4   5 0 3 2
-4   5 0 2 1
-4   5 0 1 3
+4   0 5 2 3
+4   0 5 3 4
+4   0 5 4 2
+4   0 1 4 3
+4   0 1 3 2
+4   0 1 2 4
 
 CELL_TYPES 6
 10
```
</blockquote></details>

Good catch Sean! and thanks for the diff!

**Review by amcastro-tri — COMMENTED** [review]
Thanks Sean.

+@EricCousineau-TRI for platform review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-:-O2eRyEO27fc9MYGBqsY:b-gksksf)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with tiny spelling nit

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-:-O2f0wo87bIz3HAZ0mlh:bsb3g8n)* status: 6 unresolved discussions

___
*[`geometry/proximity/inflate_mesh.cc` line 31 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2f-Q8R2eaqPh-H-FxM:-O2f-Q8R2eaqPh-H-FxN:b1ecmp0) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.cc#L31)):*
> ```cpp
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(InflateProgram);
> 
>   // Crate an optimization program to inflate `mesh` and amount `margin.`
> ```

nit "Crate" is misspelled?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aQ7zZDURqzSfXo-jZ:-O2f6v8K45IjUPg9LAUy:b-ucfkn4) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'll ponder this.
</blockquote></details>

Thanks.

___
___
*[`geometry/proximity/inflate_mesh.h` line 30 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2emwhP5FvPQC6Nuyla:-O2f51jk0EJ-E80IQ22i:b-ks153m) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.h#L30)):*
> If we invert a tet and attempt to compute the pressure field, we'll throw.

I am not convinced of that. I'll wait till the Anzu tests are done. @joemasterjohn is working on that. 

For now I limited myself to state the true state of things. As written, it is true. Also, this and all code in this PR train is very `internal::`. These pieces of docs are for the eyes of people with very field specific knowledge. I am sure those of us in that group can piece together what the implications are from these docs. 
___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKsvlDcABdJIXobKl:-O2f5uvH-lY0_svK6NFM:b8n7krr) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
I do not, but sorry, but I still do not see the gain in the refactor. Is this a blocking comment?

> Either of those would reduce the burden of the caller to know if this function is being called efficiently.

Yes, I am okay with placing this burden to people writting code in `internal::`. Everytime I see a big object passed by "copy", I assume the efficent thing to do is `std::move()` into that argument. Those are the  tyipical C++ rules (obviously assuming an actual move happens under the hood, but yes, I assume best C++ practices)

Once again, I don't see the the defect you are trying to point out and therefore I wouldn't even know how to address it.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: 1 unresolved discussion

___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKsvlDcABdJIXobKl:-O2fIcUG8Mig9JcpuArm:bh6nl7d) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I do not, but sorry, but I still do not see the gain in the refactor. Is this a blocking comment?

> Either of those would reduce the burden of the caller to know if this function is being called efficiently.

Yes, I am okay with placing this burden to people writting code in `internal::`. Everytime I see a big object passed by "copy", I assume the efficent thing to do is `std::move()` into that argument. Those are the  tyipical C++ rules (obviously assuming an actual move happens under the hood, but yes, I assume best C++ practices)

Once again, I don't see the the defect you are trying to point out and therefore I wouldn't even know how to address it.
</blockquote></details>

I just realized what you were asking here. I'll push in the next iteration

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aQ7zZDURqzSfXo-jZ:-O2fW5kTBdROf2J4c6yB:b-osjy16) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

But, for now, I'll mark this as resolved.

___
___
*[`geometry/proximity/inflate_mesh.h` line 30 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2emwhP5FvPQC6Nuyla:-O2fDMsG0D7XlR7wjWPR:bk7327m) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.h#L30)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> If we invert a tet and attempt to compute the pressure field, we'll throw.

I am not convinced of that. I'll wait till the Anzu tests are done. @joemasterjohn is working on that. 

For now I limited myself to state the true state of things. As written, it is true. Also, this and all code in this PR train is very `internal::`. These pieces of docs are for the eyes of people with very field specific knowledge. I am sure those of us in that group can piece together what the implications are from these docs.
</blockquote></details>

I think you're right. I just refreshed my understanding of the code and tets only throw if the volume is sufficiently small in magnitude. Not if the volume is negative. So, it's *possible* that margins could take the volume near zero and that *would* throw. But merely flipping it inside out, won't necessarily throw.

That said, it feels irresponsible that we don't have a unit test where we actually invert a tet and compute its pressure field. 

But for now, I'll mark myself as satisfied.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: 1 unresolved discussion

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: 1 unresolved discussion

___
*[`geometry/proximity/inflate_mesh.h` line 30 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2emwhP5FvPQC6Nuyla:-O2yq385C8p0NILdi9kA:bh7pp1t) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.h#L30)):*
> That said, it feels irresponsible that we don't have a unit test where we actually invert a tet and compute its pressure field.

I like this idea. Maybe I can do it as a follow up to #21726. I want to make incremental progress on this now Epic. I believe that for as long that each PR unit tests the code pushed we are in a good path. 
Once all internal pieces are in, I could then write a unit test like the one you suggest.
___
*[`geometry/proximity/inflate_mesh.cc` line 32 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2aKsvlDcABdJIXobKl:-O2ysv4a7fmptkw8vaK1:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/86def6798936d58b7332af867832d97ffe09f1cf/geometry/proximity/inflate_mesh.cc#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I just realized what you were asking here. I'll push in the next iteration
</blockquote></details>

Done

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

___
*[`geometry/proximity/inflate_mesh.h` line 30 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2emwhP5FvPQC6Nuyla:-O2zU5iL4313jtGXMRfL:blsr2fv) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.h#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

We don't have an issue that corresponds to the epic, right? So, there's no dumping ground for outstanding clean up tasks?
</blockquote></details>

Not yet. Right now we still didn't decide on what to do with those negative tets. We'll decide based on the Anzu sims results. If we do decide to keep them, then such a unit test is in order.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21743)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

___
*[`geometry/proximity/inflate_mesh.h` line 30 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21743#-O2emwhP5FvPQC6Nuyla:-O2zVSlq2TXMi9dRuwGW:b-nue38j) ([raw file](https://github.com/RobotLocomotion/drake/blob/a996119674ecd17cd0e9e5806c04caac59c37517/geometry/proximity/inflate_mesh.h#L30)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Not yet. Right now we still didn't decide on what to do with those negative tets. We'll decide based on the Anzu sims results. If we do decide to keep them, then such a unit test is in order.
</blockquote></details>

I've made the case for why throwing out the tets (my initial idea) is an objectively bad thing. No matter what we decide, we'll inevitably have a test based on inverting tets -- the only question is what that test expects as a result.

**Pull request merged**
