### PR TITLE
improve the error message when attempting to solve GCS problems with convex quadratic constraints

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@cohnt for feature review please! Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3DNFSPB4Y_3-kbNrhP:bizi7og)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by cohnt — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764)* status: 1 unresolved discussion, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 965 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-O3ENKhX7cSI3V0vTecr:-O3ENKhX7cSI3V0vTecs:b-clz814) ([raw file](https://github.com/RobotLocomotion/drake/blob/931038f1a3f78d8750b9cc38cc83cf3367ae65ad/geometry/optimization/graph_of_convex_sets.cc#L965)):*
> ```cpp
>     // new variables).
>     prog->AddConstraint(binding.evaluator(), vars.tail(vars.size() - 1));
>   } else if (dynamic_cast<solvers::QuadraticConstraint*>(constraint) !=
> ```

nit Do we need a test case for the error message?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764)* status: 1 unresolved discussion, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 965 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-O3ENKhX7cSI3V0vTecr:-O3EUGolEczN1oIhAMsu:b5a8736) ([raw file](https://github.com/RobotLocomotion/drake/blob/931038f1a3f78d8750b9cc38cc83cf3367ae65ad/geometry/optimization/graph_of_convex_sets.cc#L965)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

nit Do we need a test case for the error message?
</blockquote></details>

No we do not. We don't test the text of error messages usually.

**Review by cohnt — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3EUYs62KsULLWP8119:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@ggould-tri  for platform review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3d8yZ53Hw9Hso2oYI8:b-6gtwya)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 972 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-O3dC3AY3ay_hRWWTgtS:-O3dC3AY3ay_hRWWTgtT:bwiyr21) ([raw file](https://github.com/RobotLocomotion/drake/blob/931038f1a3f78d8750b9cc38cc83cf3367ae65ad/geometry/optimization/graph_of_convex_sets.cc#L972)):*
> ```cpp
>         "ShortestPathProblem::Edge does not support this "
>         "binding type: {}. Please add convex quadratic constraints in conic "
>         "form by using the function AddQuadraticAsRotatedLorentzConeConstraint",
> ```

If we know that this is what they should have done, why don't we just do it for them?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 972 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-O3dC3AY3ay_hRWWTgtS:-O3h83mY3JcpSiytftyG:bxkkz6y) ([raw file](https://github.com/RobotLocomotion/drake/blob/931038f1a3f78d8750b9cc38cc83cf3367ae65ad/geometry/optimization/graph_of_convex_sets.cc#L972)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

If we know that this is what they should have done, why don't we just do it for them?
</blockquote></details>

We can do it, similar to how `QuadraticCost` is handled. I am happy to add a TODO here, but putting the true fix in would take more time, and this may help people less familiar with Drake in the meantime

**Review by ggould-tri — COMMENTED** [review]
:lgtm:, with a recommendation for TODO below, author's discretion.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3hAIi_30tEn13W296U:b1km5jy)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 972 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-O3dC3AY3ay_hRWWTgtS:-O3hAEXS14MIsOv5o-g4:b-ufuvh5) ([raw file](https://github.com/RobotLocomotion/drake/blob/931038f1a3f78d8750b9cc38cc83cf3367ae65ad/geometry/optimization/graph_of_convex_sets.cc#L972)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We can do it, similar to how `QuadraticCost` is handled. I am happy to add a TODO here, but putting the true fix in would take more time, and this may help people less familiar with Drake in the meantime
</blockquote></details>

Thanks; TODO is always a valid resolution :-)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3riiEaEgQnPZrf0PJd:bm9o57a)* status: missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21764#-:-O3sGKqM3EYGKkBeFbxJ:b-safpmt)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),cohnt

**Pull request merged**
