### PR TITLE
Add L1NormCost and LInfNormCost to GraphOfConvexSets cost options

### PR DESCRIPTION
**Pull request by mpetersen94**
Also binds the creation of `Bindings` from a cost/constraint and decision variables to enable adding these costs in Python.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@hongkai-dai for feature review (or delegation)

cc @TobiaMarcucci (feel free to review if you would like)

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for feature review.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Msrcu-I9vG2T-jHzZ9v:bl5ccwd)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

___
*[geometry/optimization/graph_of_convex_sets.cc, line 372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16334#-MsreZ7E2LSzDwWaLqLU:-MsreZ7E2LSzDwWaLqLV:bs8c62u) ([raw file](https://github.com/robotlocomotion/drake/blob/b974c8cb28a6dfc3e65891e2ef454bf1f4dce697/geometry/optimization/graph_of_convex_sets.cc#L372)):*
> ```cpp
>       } else if (L1NormCost* l1c = dynamic_cast<L1NormCost*>(cost)) {
>         // |Ax + b|₁ becomes ℓ ≥ Σᵢ δᵢ and δᵢ ≥ |Aᵢx+bᵢϕ|.
>         int c_rows = l1c->A().rows();
> ```

Why it is named as `c_rows` instead of `A_rows`? I don't think we have a variable named `c` in this case, does `c` stands for `cost`?
___
*[geometry/optimization/graph_of_convex_sets.cc, line 389 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16334#-MsrfEbK93JhLZBiEPFI:-MsrfEbK93JhLZBiEPFJ:b-pa0p66) ([raw file](https://github.com/robotlocomotion/drake/blob/b974c8cb28a6dfc3e65891e2ef454bf1f4dce697/geometry/optimization/graph_of_convex_sets.cc#L389)):*
> ```cpp
>             -MatrixXd::Identity(c_rows, c_rows);  // -δ.
> 
>         A_linear(2 * c_rows, 1) = -1;
> ```

Document this as `ℓ ≥ Σᵢ δᵢ`?
___
*[solvers/cost.h, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16334#-MsrfvipCCTMgD3qbbv1:-MsrfvipCCTMgD3qbbv2:b-849o9a) ([raw file](https://github.com/robotlocomotion/drake/blob/b974c8cb28a6dfc3e65891e2ef454bf1f4dce697/solvers/cost.h#L234)):*
> ```objc
> 
> /**
>  * Implements a cost of the form @f[ |Ax + b|₁ @f].
> ```

Could you document that this cost is non-differentiable when any row of Ax+b equals to 0?

I would like to remind the potential users that this cost is not how people usually handle L1 norm cost, namely to use the slack variable with additional constraints. I almost want to put a warning in the documentation that it is better not to use this cost, but the users should consider the slack variable + constraint approach.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  +@sherm1 for platform review please, thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Mt4Bw8QAmjQsy1OJfRD:buohg44)* status: LGTM missing from assignee sherm1(platform), missing label for release notes (waiting on @sherm1)

___
*[solvers/cost.h, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16334#-MsrfvipCCTMgD3qbbv1:-Mt4BoatCOQgawZBjSSK:bldcnql) ([raw file](https://github.com/robotlocomotion/drake/blob/b974c8cb28a6dfc3e65891e2ef454bf1f4dce697/solvers/cost.h#L234)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I added the non-differentiable warning as well as a similar one for LInfNorm.

As for the suggestion to use a slack variable + constraint instead, I feel like if we add that here, we should also add a similar one for all of the Lp norms.  Since the L1 and LInf Norms can't currently be added to a MathematicalProgram I think the warning is not needed.  We can add warnings to the MathematicalProgram documentation the same way you did for L2.  This way the warning is more user facing.
</blockquote></details>

Cool, I think a warning in this class's documentation is sufficient.

**Review by sherm1 — COMMENTED** [review]
Checkpoint.
+@xuchenhan-tri for platform review shadowing

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Mt4W46AAdWparXmL7cU:bnk6p22)* status: 1 unresolved discussion, LGTM missing from assignees sherm1(platform),xuchenhan-tri, missing label for release notes (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[geometry/optimization/graph_of_convex_sets.cc, line 407 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt4WEvE81fSBlwkEbSO:-Mt4WEvF-UANEv6PXZtC:b-tkw4kh) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/geometry/optimization/graph_of_convex_sets.cc#L407)):*
> ```cpp
>         prog.AddLorentzConeConstraint(A_cone, VectorXd::Zero(A_cone.rows()),
>                                       vars);
>       } else if (LInfNormCost* linfc = dynamic_cast<LInfNormCost*>(cost)) {
> ```

BTW this way of using dynamic type info is an egregious violation of the style guide's [RTTI rules](https://drake.mit.edu/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_). Not your fault since you are just extending the original code, and in fact there is a TODO above noting that it should be fixed. (That would have to be done in a different PR.)

No action required -- I'm just mentioning this so my lgtm won't be taken as approval of this technique! Most likely the right design would be for the Cost base class to have a virtual method (`ImplementAsASetOfConstraints(prog)` or something like that) that could be implemented by each of the concrete Cost classes to invoke the code seen here.

A PR to fix that technical debt would be most welcome!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few ignorable comments.

@xuchenhan-tri please take a platform review look and lgtm when ready

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Mt5DSYR63iaUOYh9vM1:b-63a04e)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri, missing label for release notes (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[solvers/cost.h, line 234 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt58hJc28zAOlmbfY_r:-Mt58hJc28zAOlmbfY_s:b-jcrvf9) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/solvers/cost.h#L234)):*
> ```objc
> 
> /**
>  * Implements a cost of the form @f[ |Ax + b|₁ @f]. Note that this cost is
> ```

BTW consider using ‖x‖₁ rather than |x|₁ as more conventional norm notation
___
*[solvers/cost.h, line 244 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt5Ab1P5rn7tHl1owWv:-Mt599b_126U7KKt424_:b-i5w1ut) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/solvers/cost.h#L244)):*
> ```objc
> 
>   /**
>    * Construct a cost of the form @f[ |Ax + b|₁ @f].
> ```

BTW the Latex line noise isn't helpful here. Consider writing ‖Ax + b‖₁ in Unicode making it just as readable here as in Doxygen.

However, I see it is done this way because the older norms are written like this. Fine to leave as is.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Mt5Umxf9r57zw6_5Xhz:bnfp4nl)* status: 3 unresolved discussions, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai and @sherm1)

___
*[geometry/optimization/graph_of_convex_sets.cc, line 407 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt4WEvE81fSBlwkEbSO:-Mt9136kCJVi7C2mDpZ7:b-yfxeln) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/geometry/optimization/graph_of_convex_sets.cc#L407)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this way of using dynamic type info is an egregious violation of the style guide's [RTTI rules](https://drake.mit.edu/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_). Not your fault since you are just extending the original code, and in fact there is a TODO above noting that it should be fixed. (That would have to be done in a different PR.)

No action required -- I'm just mentioning this so my lgtm won't be taken as approval of this technique! Most likely the right design would be for the Cost base class to have a virtual method (`ImplementAsASetOfConstraints(prog)` or something like that) that could be implemented by each of the concrete Cost classes to invoke the code seen here.

A PR to fix that technical debt would be most welcome!
</blockquote></details>

Agreed that this is bad and that the recommendation you made would be a better implementation.  Thanks for allowing the PR despite this defect.
___
*[solvers/cost.h, line 234 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt58hJc28zAOlmbfY_r:-Mt92UywC-TcQLDvZrv0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/solvers/cost.h#L234)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider using ‖x‖₁ rather than |x|₁ as more conventional norm notation
</blockquote></details>

Done.
___
*[solvers/cost.h, line 244 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16334#-Mt5Ab1P5rn7tHl1owWv:-Mt92W8kBBaMpY8fZPLU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43176af479e21ddb558ebaae4e1f7c0c85d270ca/solvers/cost.h#L244)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the Latex line noise isn't helpful here. Consider writing ‖Ax + b‖₁ in Unicode making it just as readable here as in Doxygen.

However, I see it is done this way because the older norms are written like this. Fine to leave as is.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334)* status: 1 unresolved discussion, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16334#-:-Mt9B8Ae2tlQrQ_UL7Ed:b-c7f1bi)* status: 1 unresolved discussion (waiting on @sherm1)

**Pull request merged**
