### PR TITLE
MosekSolver sets logging using CommonSolverOption

### LINKED ISSUE #15359: MosekSolver doesn't respect CommonSolverOptions
Related to #15342.

Turning on printing for mosek requires a different path than the one advertised, and requires a special `MosekSolver` object and a call to `set_stream_logging()`.  

@hongkai-dai -- I'm assigning these issues to you as I consider you the owner of this component.  But we need to find ways for you to recruit help.  You shouldn't have to address everything yourself!

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #15359

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

I decided to deprecate `set_stream_logging` function, as it requires MosekSolver to store the field `stream_logging_` and `log_file_`. This is inconsistent with most other solvers, which don't have a data field.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360#-:-MeCqSov0XHDNRsF6zx6:bfpn26w)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360#-:-MeD64Wg-hVoVZLaw6XR:b-e7bejd)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360#-:-MeD7ajg8sTrkvUs4Soj:bhcma3h)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@seancurtis-tri +@ggould-tri (platform review switcheroo).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360#-:-MePphW36u44Ar7W1cPr:b-sbf15l)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15360#-:-MeQ0bYx97HEdV7y50cG:bnfp4nl)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/mosek_solver.cc, line 1880 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15360#-MeQ07it5jUtgDeoamkM:-MeQ07it5jUtgDeoamkN:bajywmm) ([raw file](https://github.com/robotlocomotion/drake/blob/38ba2832a88bb8f7967663a0f758d8cc4f26abbc/solvers/mosek_solver.cc#L1880)):*
> ```cpp
>   }
>   // TODO(hongkai.dai) remove stream_logging_ and log_file_ once
>   // set_stream_logging() is deprecated.
> ```

minor:  If you include the string "2021-10-01" here then it will be noticed during the deprecation workflow for that month and the deprecation-deleter might remind you about it.

**Comment by jwnimmer-tri** [comment]
FYI the nominal deprecation cutoff date for any changes landing this month would be 2021-11-01.

**Pull request merged**
