### PR TITLE
Stop using drake_export.h and DRAKE_EXPORT from within Drake

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is the major portion of #3973.  This PR leaves `drake_export.h` intact and installed (but with a deprecation warning) for any downstream code or feature branches that happened to start using it.

For reviewers: the first commit was perl pie, the rest were manual.

See prior discussion in #3668.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4037)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 185 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 72 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVomIORJeVJyZmAeojn:-KVomIORJeVJyZmAeojo:bl84ou3) ([raw file](https://github.com/robotlocomotion/drake/blob/b2846a32f1628c52d5a70a9be75e6408fb9d1681/CHANGELOG.md#L72)):*
> ```Markdown
> ### Removed / Deprecated
> 
>  - [#4035][] The common/drake_export.h header is deprecated and will be removed.
> ```

The PR number is wrong here; fix before merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4037)*

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri 

---

Review status: 0 of 185 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-:-KVp9Exu7Vd5jEG5_nfQ:bbpa3zd)*

**Comment by rpoyner-tri** [comment]
lots of whitespace damage still; some, but not all, called out in discussion comments. Probably would benefit from an encounter with clang-format.

---

Reviewed 179 of 179 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/common/nice_type_name.h, line 57 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpErpiiecAw1NSm2UB:-KVpErpjehoJ0uODzfVX:b-hsqzys) ([raw file](https://github.com/robotlocomotion/drake/blob/b2846a32f1628c52d5a70a9be75e6408fb9d1681/drake/common/nice_type_name.h#L57)):*
> ```objc
>   meaningful display to a human. The result is compiler-dependent.
>   @see Canonicalize() **/
> ```

The added/preserved empty line is odd (here and below).

---

*[drake/common/symbolic_environment.h, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpF6sCSs0t9JpaEK8C:-KVpF6sDwu09FlXeKzM7:b-g3vrru) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/common/symbolic_environment.h#L91)):*
> ```objc
>   std::string to_string() const;
> 
>   friend std::ostream& operator<<(std::ostream& os,
> ```

This change spoils the indentation of the next line. AFAICT all of the friend ostream& operator<<() have this problem.

---

*[drake/common/symbolic_expression.h, line 152 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpFQcCYbMgldgYr4oT:-KVpFQcCYbMgldgYr4oU:b-e6gf19) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/common/symbolic_expression.h#L152)):*
> ```objc
>   static Expression E();
> 
>   friend Expression operator+(Expression lhs,
> ```

More spoiled parameter indents (here and below).

---

*[drake/examples/Atlas/atlasUtil.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpFgpcHjeMnlhl5Rta:-KVpFgpcHjeMnlhl5Rtb:b-q7m947) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/examples/Atlas/atlasUtil.h#L11)):*
> ```objc
>  * A*[akx;aky]-b is greater than -tol
>  */
> bool ankleCloseToLimits(double akx, double aky,
> ```

more spoiled parameter indent.

---

*[drake/matlab/util/cylindrical.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpFzmC0A1dqzHD1Lx2:-KVpFzmC0A1dqzHD1Lx3:b-q7m947) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/matlab/util/cylindrical.h#L21)):*
> ```objc
> /// Writes that matrix into @p M, its derivative into @p dM, and its second
> /// derivative into @p ddM.
> void rotz(double theta, Eigen::Matrix3d* M,
> ```

more spoiled parameter indent.

---

*[drake/systems/controllers/controlUtil.cpp, line 521 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpGGZUPeauoujsXz4G:-KVpGGZUPeauoujsXz4H:b1q6rb7) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/systems/controllers/controlUtil.cpp#L521)):*
> ```cpp
> }
> 
> template void getRows(std::set<int>&,
> ```

more spoiled parameter indents (here and below).

---

*[drake/systems/controllers/controlUtil.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpGUety48vnCgQBH4C:-KVpGUety48vnCgQBH4D:b1ydhwa) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/systems/controllers/controlUtil.h#L63)):*
> ```objc
> template <typename DerivedA, typename DerivedB>
> // TODO(#2274) Fix NOLINTNEXTLINE(runtime/references).
> void getRows(std::set<int>& rows,
> ```

more spoiled parameter indent (here and below).

---

*[drake/systems/plants/RigidBodyTree.h, line 1193 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpH_GXoV5-rI_h4tiv:-KVpH_GXoV5-rI_h4tiw:b7dmios) ([raw file](https://github.com/robotlocomotion/drake/blob/d424123f81af9580e2ee34f344d0024c328d921f/drake/systems/plants/RigidBodyTree.h#L1193)):*
> ```objc
> #endif
> 
>   // The following was required for building w/ DRAKE_EXPORT on windows (due
> ```

This whole comment looks like it needs to be revisited. Probably delete the whole thing and undo whatever hackery it was describing?

---

*[drake/systems/plants/xmlUtil.h, line 190 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpHoUExzZ0M52nIqWu:-KVpHoUExzZ0M52nIqWv:b-q7m947) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/systems/plants/xmlUtil.h#L190)):*
> ```objc
> /// @return The file's fully-qualified name or an empty string if the file is
> /// not found or does not exist.
> std::string resolveFilename(const std::string& filename,
> ```

more spoiled parameter indent.

---

*[drake/util/yaml/yamlUtil.h, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-KVpIeJqfg3_93Okn6ko:-KVpIeJqfg3_93Okn6kp:b1ydhwa) ([raw file](https://github.com/robotlocomotion/drake/blob/972a75f870a23a2107938a9595da694f8e4841dc/drake/util/yaml/yamlUtil.h#L12)):*
> ```objc
> #include "drake/systems/plants/RigidBodyTree.h"
> 
> YAML::Node applyDefaults(const YAML::Node& node,
> ```

more spoiled parameter indent (here and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-:-KVpIrfc2GA080ucEeK5:bxos2e)*

**Comment by jwnimmer-tri** [comment]
Huh.  In retrospect I should have replaced `DRAKE_EXPORT` with `/* INDENT */` (same number of characters) in cases where spacing was important, and then fixed those in follow-up PR(s).  As it is, I think I'll hand-curate some fixes.  I'm loathe to clang-format all the things, because it will do more than I want (until we get everyone on the clang-format and/or clang-tidy train).  Anyway, I'll try a few things and post an update.

This should be squashed when merging.
+(status: curate commits before merging)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4037#-:-KVtbCdOfSIiLqbC1KVY:bng1avc)*

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri Thanks for the slog of a review.  I guess my spot-checking of the perl pie wasn't careful enough.  Results here indicate that subtleties exist, so I will close this PR and break into more bite-sized PRs coming up soon.

**Pull request closed without merging**
