### PR TITLE
Updated URDFs for Franka with the reflected rotor inertia values

### PR DESCRIPTION
**Pull request by AdityaBhat-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19500)

### CODE REVIEW

**Comment by AdityaBhat-TRI** [comment]
+@sammy-tri 
CC @eric-cousineau

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19500)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @AdityaBhat-TRI and @sammy-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19500#-NWmRGHx17w4qWYjIkF_:-NWmRGHx17w4qWYjIkFa:b-26bpem) (no related file):*
Blocking discussion for internal testing (details offline)

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19500)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19500#-NWmRGHx17w4qWYjIkF_:-NXMTy9D-kxqYCQN4fzm:baywieq) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Blocking discussion for internal testing (details offline)
</blockquote></details>

Anzu CI looks good w/ my small Anzu fix

___

**Review by sammy-tri — COMMENTED** [review]
:lgtm: +@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19500#-:-NXMd18SAwQCm2_FkfOf:bc8zi0o)* status: LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19500#-NWmRGHx17w4qWYjIkF_:-NXMcx5V9eDdrzlJDxyX:b-yf0iy2) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Anzu CI looks good w/ my small Anzu fix
</blockquote></details>

Passed for me too, thanks!

___

**Pull request merged**
