### PR TITLE
Add explicit instantiations for RigidBodyTree::doKinematics.

### PR DESCRIPTION
**Pull request by david-german-tri**
Also delete a smattering of dead code.

Contributes to #2074.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2610)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FTR, David and I spoke offline about any performance hazards from this PR.  Our estimation was that the biggest risk was that some `compute_JdotV=false` cases could previously be dead-code-eliminated at compile time, but now it will sometimes be a runtime branch.  That seemed unlikely enough to matter that we don't think it needs pre-emptive benchmarking prior to merging this PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKp1erlJbykbkBmgOH8:-942806299)*

**Comment by jwnimmer-tri** [comment]
:lgtm: with some optional review comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2382 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2iLhlT6ei0Q7j5gy:-KKp2iLiYGP9Cqmgrkop:952179701) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2382)):*
> ```cpp
>     Eigen::MatrixBase<VectorXd> const&) const;
> template DRAKERBM_EXPORT KinematicsCache<double> RigidBodyTree::doKinematics(
>     Eigen::MatrixBase<Eigen::Block<MatrixXd const, -1, 1, true>> const&) const;
> ```

BTW It seems like the `Eigen...MatrixBase...Block...-1...etc.` type appears frequently enough that a little using-statement nearby here might make it more readable?  Though now that I look more closely I guess true vs false is different here and below, but I guess that could be a parameter still?

---

*[drake/systems/plants/RigidBodyTree.h, line 162 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp274OdhmnAGDdWWvA:-KKp274PL1libeRdUFuz:-2056683394) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L162)):*
> ```objc
> 
>   /// Initializes a KinematicsCache with the given configuration @p q,
>   /// computes the kinematics, and returns the cache.
> ```

BTW Consider documenting the limited set of DerivedQ types that are available for use by calling code, or perhaps just refer readers to the cc file, or otherwise caution that not all types are supported?

---

*[drake/systems/plants/RigidBodyTree.h, line 168 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2JLL8ddFlGhxl7vN:-KKp2JLL8ddFlGhxl7vO:-205740661) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L168)):*
> ```objc
> 
>   /// Initializes a KinematicsCache with the given configuration @p q
>   /// and velocity @p v, computes the kinematics, and returns the cache.
> ```

BTW Consider documenting the limited set of types...

---

*[drake/systems/plants/RigidBodyTree.h, line 174 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2Le5GQQy6Ryq9lpm:-KKp2Le5GQQy6Ryq9lpn:-205740661) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L174)):*
> ```objc
>       const Eigen::MatrixBase<DerivedV>& v, bool compute_JdotV = true) const;
> 
>   /// Computes the kinematics on the given @p cache.
> ```

BTW Consider documenting the limited set of types...

---

*[drake/systems/plants/RigidBodyTree.h, line 345 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp3en5jCSO4TbaNgTe:-KKp3en6u3dLf1-ZfeYs:56485264) ([raw file](https://github.com/robotlocomotion/drake/blob/eac0c6ac21aa8ea6a43af5b084c9518592f64b7a/drake/systems/plants/RigidBodyTree.h#L345)):*
> ```objc
>       const KinematicsCache<typename Derived::Scalar>& cache,
>       Eigen::MatrixBase<Derived>& pos,
>       const std::set<int>& body_idx) const;  // = emptyIntSet);
> ```

BTW Do these need a CHANGELOG entry?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKp3zcaOePiEx1_QPRc:1730552657)*

**Comment by liangfok** [comment]
:lgtm: with some optional review comments and questions.

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2378 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq22qIDK5lJ3vcvzp9:-KKq22qIDK5lJ3vcvzpA:-1738216557) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2378)):*
> ```cpp
>     KinematicsCache<AutoDiffUpTo73d>&, bool) const;
> 
> // Explicit template instantiations for doKinematics(q).
> ```

BTW, how did you decide which explicit template instantiations to include? Are these the minimal set to get Drake as it stands to compile?

---

*[drake/systems/plants/RigidBodyTree.h, line 161 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq2J_Ur9KPD8O6EvAZ:-KKq2J_Ur9KPD8O6EvA_:-1158421384) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L161)):*
> ```objc
>   void drawKinematicTree(std::string graphviz_dotfile_filename) const;
> 
>   /// Initializes a KinematicsCache with the given configuration @p q,
> ```

BTW, since `KinematicsCache` is the name of a class, consider surrounding it with back ticks so it appears in a monospace font.

---

*[drake/systems/plants/RigidBodyTree.h, line 167 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq2W1vZZ5hy584c4QH:-KKq2W1vZZ5hy584c4QI:-1024773026) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L167)):*
> ```objc
>       const Eigen::MatrixBase<DerivedQ>& q) const;
> 
>   /// Initializes a KinematicsCache with the given configuration @p q
> ```

BTW, same comment here about `KinematicsCache`.

---

*[drake/systems/plants/RigidBodyTree.h, line 342 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq3bv2AJlmLnPIgp4l:-KKq3bv2AJlmLnPIgp4m:-1959167690) ([raw file](https://github.com/robotlocomotion/drake/blob/eac0c6ac21aa8ea6a43af5b084c9518592f64b7a/drake/systems/plants/RigidBodyTree.h#L342)):*
> ```objc
> 
>   template <typename Derived>
>   void getContactPositions(
> ```

BTW, if I understand correctly, `RigidBodyTree::getContactPositions()` and `RigidBodyTree::getContactPositionsJac()` are being removed because they are not used anywhere else within Drake, its examples, and its unit tests. Is this correct?

I'm slightly worried about removing them because I may need them to satisfy the "contact occurred" feature request mentioned in https://github.com/RobotLocomotion/drake/issues/2606 (see the third high priority item).

I suppose I could always dig into the git history and recover these methods should they be necessary. Is this the expected best practice?

This API change is related to the conversation in https://github.com/RobotLocomotion/drake/pull/2597#issuecomment-227622877. We need to clarify how much effort we should assert ensuring downstream users experience a gradual transition to the new API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKq4rYllptVQFaHGHLJ:1120779373)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2389 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKqADy8qCH-98h8ZJHa:-KKqADy9koaTpAv0GkDc:2141867032) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2389)):*
> ```cpp
> template DRAKERBM_EXPORT KinematicsCache<AutoDiffXd>
> RigidBodyTree::doKinematics(
>     Eigen::MatrixBase<VectorX<AutoDiffXd>> const&) const;
> ```

Wouldn't we like to have here a specialization of doKinematics with AutoDiffUpTo73d?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2396 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKqAOWSsuwrBiEZDIwD:-KKqAOWSsuwrBiEZDIwE:317671013) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2396)):*
> ```cpp
>     bool) const;
> template DRAKERBM_EXPORT KinematicsCache<double> RigidBodyTree::doKinematics(
>     Eigen::MatrixBase<Eigen::Block<VectorXd const, -1, 1, false>> const&,
> ```

Uff, all these block and map specializations are so annoying! (complaining about templates' hell, not your solution @david-german-tri). Actually I am wondering if these arguments could be an [`Eigen::Ref`](https://eigen.tuxfamily.org/dox/classEigen_1_1Ref.html), which could potentially cut down the number of options.
I'll play tomorrow with it and I'll let you know what I find out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610)*

**Comment by liangfok** [comment]
I believe the CI error `ld: symbol(s) not found for architecture x86_64` is real; I can replicate it on my OS X machine.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKqD6hsqlhFCQEXmSeB:-2129075995)*

**Comment by david-german-tri** [comment]
Yeah, that's definitely real.  I've pushed a possible fix; we'll see what Jenkins says.

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2378 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq22qIDK5lJ3vcvzp9:-KKsKXkbz0E5VH_nVm2l:677251276) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2378)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, how did you decide which explicit template instantiations to include? Are these the minimal set to get Drake as it stands to compile?
</details>
Yes.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2382 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2iLhlT6ei0Q7j5gy:-KKsKITP6krpPnxXqX93:1956464928) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2382)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW It seems like the `Eigen...MatrixBase...Block...-1...etc.` type appears frequently enough that a little using-statement nearby here might make it more readable?  Though now that I look more closely I guess true vs false is different here and below, but I guess that could be a parameter still?
</details>
Yeah, I considered this, but there's enough variation that I don't think it pans out.  Also, I can't figure out what the `InnerPanel` boolean template parameter means, so I'd rather not have to document it.  ;-)

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2389 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKqADy8qCH-98h8ZJHa:-KKsKbjTqp5hXeEVHKjr:-1656584762) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2389)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Wouldn't we like to have here a specialization of doKinematics with AutoDiffUpTo73d?
</details>
Very possibly, but we don't appear to need it right now.  Feel free to add it later!

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2396 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKqAOWSsuwrBiEZDIwD:-KKsNAwnJJZYITq98KmR:513408749) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.cpp#L2396)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Uff, all these block and map specializations are so annoying! (complaining about templates' hell, not your solution @david-german-tri). Actually I am wondering if these arguments could be an [`Eigen::Ref`](https://eigen.tuxfamily.org/dox/classEigen_1_1Ref.html), which could potentially cut down the number of options.
> I'll play tomorrow with it and I'll let you know what I find out.
</details>
My guess is that won't work, but I'd be delighted to be proven wrong!  I won't block this PR on it, though.

---

*[drake/systems/plants/RigidBodyTree.h, line 161 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq2J_Ur9KPD8O6EvAZ:-KKsL-RMAOKaiEInzXPK:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L161)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, since `KinematicsCache` is the name of a class, consider surrounding it with back ticks so it appears in a monospace font.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 162 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp274OdhmnAGDdWWvA:-KKsN2OztZQwRo6WSVD9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider documenting the limited set of DerivedQ types that are available for use by calling code, or perhaps just refer readers to the cc file, or otherwise caution that not all types are supported?
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 167 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq2W1vZZ5hy584c4QH:-KKsL0-F1qKO6plqKeE1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L167)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, same comment here about `KinematicsCache`.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 168 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2JLL8ddFlGhxl7vN:-KKsN1kT-iMu-x5OPkMY:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L168)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider documenting the limited set of types...
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 174 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp2Le5GQQy6Ryq9lpm:-KKsN3szY6f_cN7RG9N9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/08cd953993a2a7c92fde76f87ecb24129b1322f2/drake/systems/plants/RigidBodyTree.h#L174)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Consider documenting the limited set of types...
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 342 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKq3bv2AJlmLnPIgp4l:-KKsNel1qo0W7a3W-Lt_:-607476454) ([raw file](https://github.com/robotlocomotion/drake/blob/eac0c6ac21aa8ea6a43af5b084c9518592f64b7a/drake/systems/plants/RigidBodyTree.h#L342)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, if I understand correctly, `RigidBodyTree::getContactPositions()` and `RigidBodyTree::getContactPositionsJac()` are being removed because they are not used anywhere else within Drake, its examples, and its unit tests. Is this correct?
> 
> I'm slightly worried about removing them because I may need them to satisfy the "contact occurred" feature request mentioned in https://github.com/RobotLocomotion/drake/issues/2606 (see the third high priority item).
> 
> I suppose I could always dig into the git history and recover these methods should they be necessary. Is this the expected best practice?
> 
> This API change is related to the conversation in https://github.com/RobotLocomotion/drake/pull/2597#issuecomment-227622877. We need to clarify how much effort we should assert ensuring downstream users experience a gradual transition to the new API.
</details>
That's correct.  Added CHANGELOG entry.  

Yes, the best practice is to revive dead code from source control when you need it.

---

*[drake/systems/plants/RigidBodyTree.h, line 345 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-KKp3en5jCSO4TbaNgTe:-KKsNcfMPVEOGQAN9esB:-966883997) ([raw file](https://github.com/robotlocomotion/drake/blob/eac0c6ac21aa8ea6a43af5b084c9518592f64b7a/drake/systems/plants/RigidBodyTree.h#L345)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Do these need a CHANGELOG entry?
</details>
Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKsOnJCcARgXksrqptk:201543264)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610)*

**Comment by amcastro-tri** [comment]
@david-german-tri: why is it that I don't see the new commit with your fix? did you `push -f`?

**Comment by amcastro-tri** [comment]
never mind. super clear in reviewable. :lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKscqJQoM22v0iDdLVu:-1960833992)*

**Comment by liangfok** [comment]
I received an e-mail notification at 9:58 AM this morning.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2610#-:-KKscj28coSVdvEQi5_z:1686485003)*

**Pull request merged**
