### PR TITLE
[multibody] Bookkeeping for MbP's scalar converting constructor

### LINKED ISSUE #15168: MultibodyPlant's scalar converting constructor needs better book-keeping
This came up in the review for #15135. 

Quoting the reviewer @jwnimmer-tri:

> The MbP conversion constructor here is extremely difficult to audit.
> ...
> One way to make it easier to audit would be if this constructor stepped through every member field one by one, in the exact order they are declared in the header, so that a reader could mindlessly compare this function to the private fields, and check that every single field got a mention.
> 
> For each field, this function would either:
> (1) Copy the field directly.
> (2) Place a forward-reference comment like "We initialize geometry_query_port_ during DeclareSceneGraphPorts, below."
> (3) Place a disclaimer comment why that field does not need to be copied.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
In addition, remove an unused data memeber in MbP.

Closes #15168.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708#-:-N943KCs9RWewDF7azhF:bs3tquo)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
FYI I'll have time to look at this as of ~Tuesday next week.

**Review by xuchenhan-tri — COMMENTED** [review]
SGTM, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708#-:-N97pznh685Ov6aeEg77:b-vmrj4e)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`multibody/plant/constraint_specs.h` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YHWLd3GLNfdfhVSrE:-N9YHWLeD1oIVikBGOTV:busor81) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L20)):*
> ```objc
> // gear ratio and Δq a fixed offset. Per equation above, ρ has units of q₀/q₁
> // and Δq has units of q₀.
> // tparam_nonsymbolic_scalar
> ```

For my taste, we'd still use the `@` here even for non-Doxygen comments, just to indicate to the reader that it's a wpecial symbol instead of some weird identifier typo.



_Suggestion:_
```objc
@tparam_nonsymbolic_scalar
```
___
*[`multibody/plant/constraint_specs.h` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YIkccEOQacBITecJB:-N9YIkccEOQacBITecJC:b-tninsu) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L33)):*
> ```objc
> 
>   template <typename U>
>   CouplerConstraintSpecs(const CouplerConstraintSpecs<U>& other) {
> ```

I'm surprised that this seemingly-featureful new function does not require any new unit test cases or test conditions to be added.  Can you talk me through that?
___
*[`multibody/plant/constraint_specs.h` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YIBwh0lMMlL03zvUO:-N9YIBwh0lMMlL03zvUP:b-s2har2) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L36)):*
> ```objc
>     joint0_index = other.joint0_index;
>     joint1_index = other.joint1_index;
>     if constexpr (std::is_same_v<T, double> && std::is_same_v<U, AutoDiffXd>) {
> ```

I don't know why the U==AutoDiffXd check needs to be here?

The function `ExtractDoubleOrThrow` is overloaded for all scalar types (including double), so is valid to call no matter what `U` would be:



_Suggestion:_
```objc
    if constexpr (std::is_same_v<T, double>) {
```
___
*[`multibody/plant/multibody_plant.cc` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YJ15E1hWWQd3abr8Z:-N9YJ15E1hWWQd3abr8_:blrpqu2) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/multibody_plant.cc#L491)):*
> ```cpp
>     // symbolic either.
>     if constexpr (!std::is_same_v<T, symbolic::Expression> &&
>                   !std::is_same_v<U, symbolic::Expression>) {
> ```

I'm surprised that this seemingly-featureful change does not require any new unit test cases or test conditions to be added.  Can you talk me through that?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/plant/constraint_specs.h` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YHWLd3GLNfdfhVSrE:-N9YeU4U8hQSeRJE1sMp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For my taste, we'd still use the `@` here even for non-Doxygen comments, just to indicate to the reader that it's a wpecial symbol instead of some weird identifier typo.
</blockquote></details>

Done.
___
*[`multibody/plant/constraint_specs.h` line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YIkccEOQacBITecJB:-N9Yh5qTA8MpJNQzrNxc:be4ubp6) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm surprised that this seemingly-featureful new function does not require any new unit test cases or test conditions to be added.  Can you talk me through that?
</blockquote></details>

I added a unit test. PTAL.
___
*[`multibody/plant/constraint_specs.h` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YIBwh0lMMlL03zvUO:-N9Yh2UBBKKMI93MkJcq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/constraint_specs.h#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't know why the U==AutoDiffXd check needs to be here?

The function `ExtractDoubleOrThrow` is overloaded for all scalar types (including double), so is valid to call no matter what `U` would be:
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 491 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9YJ15E1hWWQd3abr8Z:-N9YnypuEVZAMSCRZEzV:be4ubp6) ([raw file](https://github.com/robotlocomotion/drake/blob/ffaabbf0896561373f2cb51882c8f90a21c193d3/multibody/plant/multibody_plant.cc#L491)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm surprised that this seemingly-featureful change does not require any new unit test cases or test conditions to be added.  Can you talk me through that?
</blockquote></details>

I added a unit test. PTAL.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708#-:-N9b9ufaCCmhvSPUd0xl:bnfp4nl)* status: 7 unresolved discussions, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.cc` line 454 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b3xAcE3eChy_2zmL9:-N9b3xAcE3eChy_2zmLA:b-38yc3s) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L454)):*
> ```cpp
>     //   -instance_generalized_contact_forces_output_ports_
> 
>     // Copy multibody_graph_.
> ```

This only _partially_ copies the MultibodyGraph.  The looped calls to `RegisterJointInGraph` below copy the second half.

At minimum, the comments here need to explain the split-brain copying.

Even better, if there's no reason it needs to happen post-finalize then move the `RegisterJointInGraph` copying up to this point in the code.

Even better, add a TODO here that MultibodyGraph should offer a public function (or constructor) for scalar conversion, so that MbP can just delegate the copying to MbG, instead of leaking knowledge of what kind of data MbG holds into MbP's converting constructor.
___
*[`multibody/plant/multibody_plant.cc` line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b4HkAAJdF5Coqc_Ti:-N9b4HkAAJdF5Coqc_Tj:bcprbdr) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L483)):*
> ```cpp
> 
>     // Copy over coupler_constraints_specs_
>     coupler_constraints_specs_.clear();
> ```

It's not clear to me how `coupler_constraint_specs_` could be anything other than empty at this point, so I don't understand the call to `clear()` here -- it seems like a no-op?

To lock in the assertion that it's always initialized empty in the list of member fields and never touched prior to this point, we could write `DRAKE_DEMAND(coupler_constraint_specs_.empty());` here as a kind of runnable documentation.
___
*[`multibody/plant/multibody_plant.cc` line 489 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b5pIXBaJN4KqR-RrP:-N9b5pIY-e6gP-2cfr8F:b-roidkk) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L489)):*
> ```cpp
>     // the compliant contact manager, which would preclude scalar conversion to
>     // symbolic. Thus we don't need to worry about the destination being
>     // symbolic either.
> ```

nit I believe the assumptions in this documentation are _currently_ accurate, but I worry about them bitrotting.  I would feel more comfortable if the conditions were also double-checked at runtime; something like ...

```c++
DRAKE_DEMAND(coupler_constraints_specs_.empty());
```

... when U = Expression or T = Expression, i.e, as part of an `else` clause of the if-constexpr check.
___
*[`multibody/plant/multibody_plant.cc` line 498 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b54Oc0lYDZOA2j3bZ:-N9b54Oc0lYDZOA2j3b_:b-h4zbd3) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L498)):*
> ```cpp
>     }
>     // cache_indexes_ is set in DeclareCacheEntries() in
>     // DeclareStateCacheAndPorts().
> ```

nit Probably worth spelling out the actual function name that we call below, so the reader doesn't need to hunt for it.



_Suggestion:_
```cpp
    // cache_indexes_ is set in DeclareCacheEntries() in
    // DeclareStateCacheAndPorts() in FinalizePlantOnly().
```
___
*[`multibody/plant/test/constraint_specs_test.cc` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b2RO1--c9F83lnCb-:-N9b2RO1--c9F83lnCb0:b-29tc81) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/constraint_specs_test.cc#L11)):*
> ```cpp
> 
> const JointIndex j0(3);
> const JointIndex j1(5);
> ```

nit Static global constants must be named like `kCamelCase` not `j0` or `j1`.  (Alternatively, move the constants into the test case as locals.)
___
*[`multibody/plant/test/multibody_plant_scalar_conversion_test.cc` line 250 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b2cyn67CrzfbXp3nI:-N9b2cyn67CrzfbXp3nJ:b-29tc81) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L250)):*
> ```cpp
> 
> const JointIndex j0(3);
> const JointIndex j1(5);
> ```

nit Static global constants must be named like `kCamelCase` not `j0` or `j1`.  (Alternatively, move the constants into the test case as locals.)
___
*[`multibody/plant/test/multibody_plant_scalar_conversion_test.cc` line 267 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b8hR0Cg7YFLCJFVkY:-N9b8hR0Cg7YFLCJFVkZ:b-gv7fzr) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L267)):*
> ```cpp
>             plant_double.num_constraints());
>   const internal::CouplerConstraintSpecs<AutoDiffXd>& spec_ad =
>       MultibodyPlantTester::get_specs(*plant_double_to_autodiff)[0];
> ```

Are we acceptance testing using friendship only because MbP lacks getters to interrogate the coupler constraints?

Plant configuration data that's hidden from the user is a defect[1] the MbP API, that we should fix by adding appropriate getters, instead of using friendship for acceptance testing.

(On the other hand, we might be able to finesse that issue off the critical path by testing _only_ that `EXPECT_EQ(original_plant.num_constraints(), new_plant.num_constraints())` to provide that the constraints are copied _at all ever_.  By induction we know that the `CouplerConstraintSpecs` unit test has already checked the memberwise copying for correctness, so the fact that they were copied at all is a sufficient test of MbP's code.  In which case, the getter could be part of a future PR, instead of blocking this one.)

---

[1] In general, having a setter with no corresponding getter will always present usability hurdles for users.  Unless there's an acute reason why a getter needs to be missing, every setter should have a matching getter.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/plant/multibody_plant.cc` line 454 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b3xAcE3eChy_2zmL9:-N9geFj1ExRUZZ9uBQ-1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L454)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This only _partially_ copies the MultibodyGraph.  The looped calls to `RegisterJointInGraph` below copy the second half.

At minimum, the comments here need to explain the split-brain copying.

Even better, if there's no reason it needs to happen post-finalize then move the `RegisterJointInGraph` copying up to this point in the code.

Even better, add a TODO here that MultibodyGraph should offer a public function (or constructor) for scalar conversion, so that MbP can just delegate the copying to MbG, instead of leaking knowledge of what kind of data MbG holds into MbP's converting constructor.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b4HkAAJdF5Coqc_Ti:-N9geMqDEbKT-yER9CTR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L483)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's not clear to me how `coupler_constraint_specs_` could be anything other than empty at this point, so I don't understand the call to `clear()` here -- it seems like a no-op?

To lock in the assertion that it's always initialized empty in the list of member fields and never touched prior to this point, we could write `DRAKE_DEMAND(coupler_constraint_specs_.empty());` here as a kind of runnable documentation.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 489 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b5pIXBaJN4KqR-RrP:-N9geb112BeQP8Qjg0r2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L489)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I believe the assumptions in this documentation are _currently_ accurate, but I worry about them bitrotting.  I would feel more comfortable if the conditions were also double-checked at runtime; something like ...

```c++
DRAKE_DEMAND(coupler_constraints_specs_.empty());
```

... when U = Expression or T = Expression, i.e, as part of an `else` clause of the if-constexpr check.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 498 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b54Oc0lYDZOA2j3bZ:-N9gegIKC3LIgVi-Z9Dn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/multibody_plant.cc#L498)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Probably worth spelling out the actual function name that we call below, so the reader doesn't need to hunt for it.
</blockquote></details>

Done.
___
*[`multibody/plant/test/constraint_specs_test.cc` line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b2RO1--c9F83lnCb-:-N9gemP691l5aopgnzDh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/constraint_specs_test.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Static global constants must be named like `kCamelCase` not `j0` or `j1`.  (Alternatively, move the constants into the test case as locals.)
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_scalar_conversion_test.cc` line 250 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b2cyn67CrzfbXp3nI:-N9gesNDBNi_kAFgdujT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L250)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Static global constants must be named like `kCamelCase` not `j0` or `j1`.  (Alternatively, move the constants into the test case as locals.)
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_scalar_conversion_test.cc` line 267 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9b8hR0Cg7YFLCJFVkY:-N9gg--d7FqOBy_-fFwE:b-jof9wl) ([raw file](https://github.com/robotlocomotion/drake/blob/53ed7f26ce44b40b4f337d42e8e6beb3abd0a0e0/multibody/plant/test/multibody_plant_scalar_conversion_test.cc#L267)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Are we acceptance testing using friendship only because MbP lacks getters to interrogate the coupler constraints?

Plant configuration data that's hidden from the user is a defect[1] the MbP API, that we should fix by adding appropriate getters, instead of using friendship for acceptance testing.

(On the other hand, we might be able to finesse that issue off the critical path by testing _only_ that `EXPECT_EQ(original_plant.num_constraints(), new_plant.num_constraints())` to provide that the constraints are copied _at all ever_.  By induction we know that the `CouplerConstraintSpecs` unit test has already checked the memberwise copying for correctness, so the fact that they were copied at all is a sufficient test of MbP's code.  In which case, the getter could be part of a future PR, instead of blocking this one.)

---

[1] In general, having a setter with no corresponding getter will always present usability hurdles for users.  Unless there's an acute reason why a getter needs to be missing, every setter should have a matching getter.
</blockquote></details>

I modified the test and added a TODO to add getters. PTAL.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm_strong:. Still an ugly mess but much improved!

> Reviewed 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708#-:-N9ht2Np1GshyzcOnADM:bnpi3vr)* status: 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.h` line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hobRM4pYT_jmoHrJw:-N9hobRM4pYT_jmoHrJx:b-s81qc3) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.h#L83)):*
> ```objc
>   // An estimated time scale in which objects come to a relative stop during
>   // contact.
>   double time_scale{-1.0};
> ```

minor: I'm assuming -1.0 is an illegal value used as some kind of a flag? If so, why not use std::optional here as you did for gravity? If this does need a special flag value the comment should explain that. Is any negative number a flag? Zero?
___
*[`multibody/plant/multibody_plant.h` line 4877 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hpWyRDF8pdW7OdlVg:-N9hpWyRDF8pdW7OdlVh:b-4xlj4u) ([raw file](https://github.com/robotlocomotion/drake/blob/42e131ca0d69c664002d6bd240d27dde849e1f34/multibody/plant/multibody_plant.h#L4877)):*
> ```objc
>   // Map provided at construction that tells how bodies (referenced by name),
>   // map to frame ids.
>   std::unordered_map<std::string, geometry::FrameId> body_name_to_frame_id_;
> ```

BTW was this a dead field now being removed? If so should update the PR description to include both bookkeeping and removal of dead stuff.
___
*[`multibody/plant/multibody_plant.cc` line 401 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqAiiBGS_-09r3C4i:-N9hqAij4TsVP04OyUrn:b-chua5l) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L401)):*
> ```cpp
>   DRAKE_THROW_UNLESS(other.is_finalized());
> 
>   // Here we stepped through every member field one by one, in the exact order
> ```

BTW consider stepped -> step
___
*[`multibody/plant/multibody_plant.cc` line 402 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hsrIA5Vf17FaSP_cR:-N9hsrIA5Vf17FaSP_cS:b-33jrq3) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L402)):*
> ```cpp
> 
>   // Here we stepped through every member field one by one, in the exact order
>   // they are declared in the header, so that a reader could mindlessly compare
> ```

BTW I mindlessly compared this with multibody_plant.h and found every field accounted for!
___
*[`multibody/plant/multibody_plant.cc` line 405 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqLRt3tpXFuny-cCj:-N9hqLRt3tpXFuny-cCk:bjx69q4) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L405)):*
> ```cpp
>   // this function to the private fields, and check that every single field got
>   // a mention.
>   // For each field, this function would either:
> ```

nit: would -> will
___
*[`multibody/plant/multibody_plant.cc` line 417 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqmqe4TSXEooJ6xFd:-N9hqmqe4TSXEooJ6xFe:b-1fgv0t) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L417)):*
> ```cpp
>     // Copy over the friction model if it is initialized. Otherwise, a default
>     // value will be set in FinalizePlantOnly().
>     if (other.friction_model_.stiction_tolerance() > 0) {
> ```

nit: should mention that stiction_tolerance is the only field in friction_model_. I was expecting to see something like `friction_model_ = other.friction_model_` rather than setting of one of its fields. By looking at the class I could see that setting just this field is equivalent to a full copy but that's not obvious.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 2 unresolved discussions (waiting on @amcastro-tri, @jwnimmer-tri, and @sherm1)

___
*[`multibody/plant/multibody_plant.h` line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hobRM4pYT_jmoHrJw:-N9hwZsoBtE8-ZcS6mSB:b-58vn73) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.h#L83)):*
>  If so, why not use std::optional here as you did for gravity?

Hmm, I'm not sure. I only moved this struct out so that it doesn't depend on template parameter. @amcastro-tri could you comment on this?

> Is any negative number a flag? Zero?

Yes, only positive numbers are valid.
___
*[`multibody/plant/multibody_plant.h` line 4877 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hpWyRDF8pdW7OdlVg:-N9i-NAZ-TMSK5k1ZIvA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/42e131ca0d69c664002d6bd240d27dde849e1f34/multibody/plant/multibody_plant.h#L4877)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW was this a dead field now being removed? If so should update the PR description to include both bookkeeping and removal of dead stuff.
</blockquote></details>

Done.
___
*[`multibody/plant/multibody_plant.cc` line 401 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqAiiBGS_-09r3C4i:-N9hxJPu6daWKbsC3yhO:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L401)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider stepped -> step
</blockquote></details>

Done
___
*[`multibody/plant/multibody_plant.cc` line 402 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hsrIA5Vf17FaSP_cR:-N9hxBPVBow2DznGnIJV:b-m8d9dl) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L402)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I mindlessly compared this with multibody_plant.h and found every field accounted for!
</blockquote></details>

Isn't it nice to be able to turn off your brain once in a while!
___
*[`multibody/plant/multibody_plant.cc` line 405 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqLRt3tpXFuny-cCj:-N9hxK1D01EhkhLFZiAW:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L405)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: would -> will
</blockquote></details>

Done
___
*[`multibody/plant/multibody_plant.cc` line 417 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hqmqe4TSXEooJ6xFd:-N9hxzO_Ec8x2e71GyvH:bmwg8p7) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.cc#L417)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: should mention that stiction_tolerance is the only field in friction_model_. I was expecting to see something like `friction_model_ = other.friction_model_` rather than setting of one of its fields. By looking at the class I could see that setting just this field is equivalent to a full copy but that's not obvious.
</blockquote></details>

Done, I added a note.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 1 unresolved discussion (waiting on @amcastro-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/plant/multibody_plant.h` line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hobRM4pYT_jmoHrJw:-N9lNy4M1HK_Bj0xtM-K:bv2yu3o) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.h#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

>  If so, why not use std::optional here as you did for gravity?

Hmm, I'm not sure. I only moved this struct out so that it doesn't depend on template parameter. @amcastro-tri could you comment on this?

> Is any negative number a flag? Zero?

Yes, only positive numbers are valid.
</blockquote></details>

Maybe add a TODO and keep this as out-of-scope for the scalar-conversion PR, since it merely relocated the confusing code, and no changes here depend on how this sentinel works?

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`multibody/plant/multibody_plant.h` line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hobRM4pYT_jmoHrJw:-N9lgXOm0BLx9sCjzrZf:b-ox1a1v) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.h#L83)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe add a TODO and keep this as out-of-scope for the scalar-conversion PR, since it merely relocated the confusing code, and no changes here depend on how this sentinel works?
</blockquote></details>

Fine with me.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

___
*[`multibody/plant/multibody_plant.h` line 83 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17708#-N9hobRM4pYT_jmoHrJw:-NA5GYD37EnvAjJ7UPTs:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9990f173adf7c499597cba8c202cd02db69a45/multibody/plant/multibody_plant.h#L83)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Fine with me.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17708)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
