### PR TITLE
Faster bilateral constraints.

### PR DESCRIPTION
**Pull request by edrumwri**
The mixed linear complementarity problem with potentially rank-deficient bilateral constraint Jacobian had been addressed by determining a minimum set of nonredundant constraints using repeated Cholesky factorizations. The time complexity was not problematic- particularly if we were to use rank-1 Cholesky updates, which we were not- but it was certainly less efficient than desired to do repeated Cholesky factorizations from scratch. 

This PR uses the complete orthogonal factorization instead, thereby simplifying the code considerably and conferring the side benefit of determining a minimum-norm bilateral constraint solution. We hadn't adopted this approach previously because it appeared that we would have to do a full factorization of the blocked saddle point matrix containing the generalized inertia (which would thus preclude the speedup from the O(N) time dynamics algorithms). This new strategy allows our block inversion strategy to make use of the fact that all necessary computations are of the form (GM⁻¹Gᵀ)⁻¹G, meaning that the less-than-full row rank of G is inconsequential.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7263)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
some minor comments, looks nice! 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuVERERqavK2eFue_P:-KwuVERERqavK2eFue_Q:bihexpt) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L309)):*
> ```objc
> //        velocities.
> // @param problem_data The constraint problem data.
> // @param indep_constraints The indices of the independent constraints out of
> ```

probably need to update these. 

---

*[drake/multibody/constraint/constraint_solver.h, line 373 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuUPu5RMo7ROaz74ho:-KwuUPu5RMo7ROaz74hp:bihexpt) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L373)):*
> ```objc
> //        velocities.
> // @param problem_data The constraint problem data.
> // @param indep_constraints The indices of the independent constraints out of
> ```

probably need to update these. 

---

*[drake/multibody/constraint/constraint_solver.h, line 636 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuUylNwEGbu5lPErz9:-KwuUylNwEGbu5lPErzA:bx7k5pm) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L636)):*
> ```objc
> 
>   // Compute the complete orthogonal factorization.
>   std::unique_ptr<Eigen::CompleteOrthogonalDecomposition<MatrixX<T>>> Del_QR;
> ```

This doesn't look right, or I just get blinded by reviewable. 
If you have zero eq constraints, isn't Del_QR a nullptr? and you pass it to DetermineNewFullInertiaSolveOperator and DetermineNewPartialInertiaSolveOperator, which doesn't do any checks or if statements, why isn't this segfaulting?
I think this is because of the fast exit stuff at the very top?? Then maybe this is conditional is unnecessary? 

---

*[drake/multibody/constraint/constraint_solver.h, line 897 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuXD7CkFiQ0XLjG2k0:-KwuXD7CkFiQ0XLjG2k1:b-7ropln) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L897)):*
> ```objc
> 
>   // Compute the complete orthogonal factorization.
>   std::unique_ptr<Eigen::CompleteOrthogonalDecomposition<MatrixX<T>>> Del_QR;
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-:-KwuY0-0lwvp4bsfih47:be19faa)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuVERERqavK2eFue_P:-KwvRXlRG0t0sxR0uI2h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L309)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably need to update these. 
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_solver.h, line 373 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuUPu5RMo7ROaz74ho:-KwvR_o5ZtG8uVM3Zh_C:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L373)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

probably need to update these. 
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_solver.h, line 636 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuUylNwEGbu5lPErz9:-KwvRmxGZ6UpHW6sz6ok:b-eodglp) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L636)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

This doesn't look right, or I just get blinded by reviewable. 
If you have zero eq constraints, isn't Del_QR a nullptr? and you pass it to DetermineNewFullInertiaSolveOperator and DetermineNewPartialInertiaSolveOperator, which doesn't do any checks or if statements, why isn't this segfaulting?
I think this is because of the fast exit stuff at the very top?? Then maybe this is conditional is unnecessary? 
</blockquote></details>

Eigen is pretty silly here. If you try constructing the factorization on an empty matrix, it complains. PTAL now- I've prettified it.

---

*[drake/multibody/constraint/constraint_solver.h, line 897 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuXD7CkFiQ0XLjG2k0:-KwvWpi8MbsiZu3S2C0I:b5qjmk2) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L897)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto response.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 636 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwuUylNwEGbu5lPErz9:-KwveD_PPnWJ5EJG4Nw6:bo5o6m3) ([raw file](https://github.com/robotlocomotion/drake/blob/af8640c74c2d1ff6bf6a75217e46a70aa3287904/drake/multibody/constraint/constraint_solver.h#L636)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Eigen is pretty silly here. If you try constructing the factorization on an empty matrix, it complains. PTAL now- I've prettified it.
</blockquote></details>

looks much nicer! thanks

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwvdxY66Xv027qyZ8Z5:-KwvdxY66Xv027qyZ8Z6:b-jx0rgv) ([raw file](https://github.com/robotlocomotion/drake/blob/e08d597d1cbd8f4a160e6bafb249c00f88aaf2c6/drake/multibody/constraint/constraint_solver.h#L309)):*
> ```objc
> //        velocities.
> // @param problem_data The constraint problem data.
> // @param Del The factorization of the Delassus Matrix GM⁻¹Gᵀ,
> ```

BTW might call it Del_QR

---

*[drake/multibody/constraint/constraint_solver.h, line 367 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-Kwve2llCYBOZ0oOa1zs:-Kwve2lmxZHdmf55sAIV:bmoytl6) ([raw file](https://github.com/robotlocomotion/drake/blob/e08d597d1cbd8f4a160e6bafb249c00f88aaf2c6/drake/multibody/constraint/constraint_solver.h#L367)):*
> ```objc
> //        velocities.
> // @param problem_data The constraint problem data.
> // @param Del The factorization of the Delassus Matrix GM⁻¹Gᵀ,
> ```

BTW ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-:-KwveNOtmOTCPIrVe62x:bnfp4nl)*

**Comment by edrumwri** [comment]
+@sherm1 for platform review please

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-:-KwvexNQTmkss4WuUD6l:bu0bkqk)*

**Comment by edrumwri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwvdxY66Xv027qyZ8Z5:-KwvfNQtIPLrM38wOgk9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e08d597d1cbd8f4a160e6bafb249c00f88aaf2c6/drake/multibody/constraint/constraint_solver.h#L309)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW might call it Del_QR
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_solver.h, line 367 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-Kwve2llCYBOZ0oOa1zs:-KwvfZILhOCfzqKxRNy0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e08d597d1cbd8f4a160e6bafb249c00f88aaf2c6/drake/multibody/constraint/constraint_solver.h#L367)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263)*

**Comment by sherm1** [comment]
Cool! Platform :lgtm: except for one variable name, ptal.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 278 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwwIv0MATHSPs93ASjO:-KwwIv0MATHSPs93ASjP:boxuke7) ([raw file](https://github.com/robotlocomotion/drake/blob/67956ef8dd281dda652b658c982b50ab8080cd56/drake/multibody/constraint/constraint_solver.h#L278)):*
> ```objc
>     const ProblemData* problem_data,
>     int num_generalized_velocities,
>     const Eigen::CompleteOrthogonalDecomposition<MatrixX<T>>* Del_QR,
> ```

BTW complete orthogonal decomp is not a QR. It is a three-matrix decomposition Lapack (and Eigen) denotes QTZ (that's the same Q as in QR but Z is orthogonal and T is a triangular matrix different from R).

I found the `Del` here confusing (I thought it might be an oddly-capitalized "delta"). I understand now it stands for "Delassus", but it shouldn't be capitalized since it is a variable and not a math symbol. Could you call it `delassus_QTZ` here?

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwwOByjNzj4a_Ndnwj0:-KwwOByjNzj4a_Ndnwj1:b-aeiss5) ([raw file](https://github.com/robotlocomotion/drake/blob/67956ef8dd281dda652b658c982b50ab8080cd56/drake/multibody/constraint/constraint_solver.h#L309)):*
> ```objc
> //        velocities.
> // @param problem_data The constraint problem data.
> // @param Del_QR The factorization of the Delassus Matrix GM⁻¹Gᵀ,
> ```

BTW `delassus_QTZ`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-:-KwwVfsAQ8v3Us6DpPOD:bz74l7k)*

**Comment by edrumwri** [comment]
Thanks for the fast platform review, Sherm!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/constraint/constraint_solver.h, line 278 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwwIv0MATHSPs93ASjO:-Kwwgkxq8pXfuLjICrmz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67956ef8dd281dda652b658c982b50ab8080cd56/drake/multibody/constraint/constraint_solver.h#L278)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW complete orthogonal decomp is not a QR. It is a three-matrix decomposition Lapack (and Eigen) denotes QTZ (that's the same Q as in QR but Z is orthogonal and T is a triangular matrix different from R).

I found the `Del` here confusing (I thought it might be an oddly-capitalized "delta"). I understand now it stands for "Delassus", but it shouldn't be capitalized since it is a variable and not a math symbol. Could you call it `delassus_QTZ` here?
</blockquote></details>

Done.

---

*[drake/multibody/constraint/constraint_solver.h, line 309 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-KwwOByjNzj4a_Ndnwj0:-KwwglbKCWptoJXHb5Gt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67956ef8dd281dda652b658c982b50ab8080cd56/drake/multibody/constraint/constraint_solver.h#L309)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `delassus_QTZ`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7263#-:-KwwgmOEZxLHje4oDkV7:b-mg0ry5)*

**Pull request merged**
