### PR TITLE
call_python: Ensure that the client is killed only when both C++ programs finish.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Address failure in Mac due to race condition when testing multiple consecutive executions of `call_python_client`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7645)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature and platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-:-L0kBTzI3XpPdRfPezbo:b-waowit)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please.

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_full_test.sh, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-L0kRu-qgoPP5-tGUMIG:-L0kRu-qgoPP5-tGUMIH:b9gq61k) ([raw file](https://github.com/robotlocomotion/drake/blob/e2888bc9b2e912f0517cacf21f314ed7cbd405ba/common/proto/test/call_python_full_test.sh#L56)):*
> ```Shell
>     echo -e "\n\n\n[ ${func}: with_error + stop_on_error ]"
>     do-setup 1 1
>     ${func}
> ```

BTW, does it make sense to have the following line here?
```
    rm ${done_file}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/proto/test/call_python_full_test.sh, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-L0kRu-qgoPP5-tGUMIG:-L0kdTZr3sbZGTvoTGRt:b-sqntec) ([raw file](https://github.com/robotlocomotion/drake/blob/e2888bc9b2e912f0517cacf21f314ed7cbd405ba/common/proto/test/call_python_full_test.sh#L56)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, does it make sense to have the following line here?
```
    rm ${done_file}
```
</blockquote></details>

Shouldn't be necessary; the updated `call_python_test` file will always overwrite the file with whatever count it has, since it's a persistent counter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645)*

**Comment by soonho-tri** [comment]
:lgtm:

With this PR, I can't reproduce test failure anymore locally.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-:-L0kkl0-QzyVafQ87ZPo:bav7pb1)*

**Comment by soonho-tri** [comment]
:lgtm_cancel: per f2f.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-:-L0ks1e-SeQjOJG20DYq:b-kjqks3)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please.

(seeing if I can keep most of the test in place, just ignore the threaded + looping setup on Mac.)

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7645#-:-L0mVutpoXPYqDS_eNNV:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Fingers crossed!

**Pull request merged**
