### PR TITLE
Added parameter time to LcmPublisherSystem::TranslateVectorBaseToLcm().

### PR DESCRIPTION
**Pull request by liangfok**
This is necessary since `BasicVector` does not always contain the time within it and many LCM messages include a timestamp. I discovered this need while working on an LCM translator for `drake::lcmt_viewer_draw` messages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3460)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please.
+@jwnimmer-tri for platform review please.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-:-KRieBwHwBbv3Dw_iye4:bgaxkvb)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please.

**Comment by jwnimmer-tri** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/gen/driving_command_translator.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRij0LzZ713whdNCbLt:-KRij0M-pWsyGfbOqGka:b-dbb4at) ([raw file](https://github.com/robotlocomotion/drake/blob/7e649d87f2d1abecd51b9a4631f0475acf31b27d/drake/automotive/gen/driving_command_translator.cc#L4)):*
> ```cpp
> 
> // This file is generated by a script.  Do not edit!
> // See drake/automotive/lcm_vector_gen.py.
> ```

Do not edit these by hand.  Please update the `lcm_vector_gen.py` and re-run it, and then commit its edits.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRihen6eYoIk_sS3ps-:-KRihen6eYoIk_sS3ps0:bmm6oco) ([raw file](https://github.com/robotlocomotion/drake/blob/7e649d87f2d1abecd51b9a4631f0475acf31b27d/drake/systems/lcm/lcm_and_vector_base_translator.h#L79)):*
> ```objc
>   virtual void TranslateVectorBaseToLcm(
>       const VectorBase<double>& vector_base,
>       double time,
> ```

BTW This is fine, but my instinct would have been to place `time` first (before the vector data), because (I think?) most messages often place it first in their definitions.

---

*[drake/systems/lcm/translator_between_lcmt_drake_signal.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRii1xQG_HVIMqcNr_I:-KRii1xROYvE5DyuqviM:b-xsg1l7) ([raw file](https://github.com/robotlocomotion/drake/blob/7e649d87f2d1abecd51b9a4631f0475acf31b27d/drake/systems/lcm/translator_between_lcmt_drake_signal.cc#L64)):*
> ```cpp
>   message.val.resize(message.dim);
>   message.coord.resize(message.dim);
>   message.timestamp = static_cast<int64_t>(time);
> ```

It's not documented in the message, but I believe `drake_signal.timestamp` is understood to be in milliseconds.  Can you see if you can find an answer one way or another?

Same goes for all of the `automotive/gen` translators.

---

*[drake/systems/lcm/translator_between_lcmt_drake_signal.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRiiQw3NapEWAfNrdwe:-KRiiQw3NapEWAfNrdwf:bu4k4m9) ([raw file](https://github.com/robotlocomotion/drake/blob/7e649d87f2d1abecd51b9a4631f0475acf31b27d/drake/systems/lcm/translator_between_lcmt_drake_signal.cc#L64)):*
> ```cpp
>   message.val.resize(message.dim);
>   message.coord.resize(message.dim);
>   message.timestamp = static_cast<int64_t>(time);
> ```

Should the unit test cover this statement?  On a first read, it seems like no test would fail if it's incorrect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks.

---

Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/gen/driving_command_translator.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRij0LzZ713whdNCbLt:-KRin2BvH-x9FPZkHTd2:b-fcygej) ([raw file](https://github.com/robotlocomotion/drake/blob/703b5bf935890122c7d89dec675788d97bbba196/drake/automotive/gen/driving_command_translator.cc#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Do not edit these by hand.  Please update the `lcm_vector_gen.py` and re-run it, and then commit its edits.
</details>
Doh! I forgot about that. Fixed.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 79 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRihen6eYoIk_sS3ps-:-KRiq0So2YF9qX0h-l7v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/703b5bf935890122c7d89dec675788d97bbba196/drake/systems/lcm/lcm_and_vector_base_translator.h#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This is fine, but my instinct would have been to place `time` first (before the vector data), because (I think?) most messages often place it first in their definitions.
</details>
Done.

---

*[drake/systems/lcm/translator_between_lcmt_drake_signal.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRii1xQG_HVIMqcNr_I:-KRisXERcyn5uWqCIzUO:byowbez) ([raw file](https://github.com/robotlocomotion/drake/blob/703b5bf935890122c7d89dec675788d97bbba196/drake/systems/lcm/translator_between_lcmt_drake_signal.cc#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> It's not documented in the message, but I believe `drake_signal.timestamp` is understood to be in milliseconds.  Can you see if you can find an answer one way or another?
> 
> Same goes for all of the `automotive/gen` translators.
</details>
I searched and did not find any documentation. However, I looked in `LcmSystem.h` and saw that the time was multiplied by 1000 prior to being saved as an `int_64`, which I consider enough evidence to assume that variable `timestamp` is by default in milliseconds.

https://github.com/RobotLocomotion/drake/blob/2abef6973d416d84ccc2ef16fcf09ba62544b774/drake/systems/LCMSystem.h#L44

I added documentation to reflect this in #3464.

---

*[drake/systems/lcm/translator_between_lcmt_drake_signal.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-KRiiQw3NapEWAfNrdwe:-KRnQugLB2WCN99Na3S1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/703b5bf935890122c7d89dec675788d97bbba196/drake/systems/lcm/translator_between_lcmt_drake_signal.cc#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Should the unit test cover this statement?  On a first read, it seems like no test would fail if it's incorrect?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-:-KRnQybddocBDbzQ247X:bblnx7v)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-:-KRo_rvJTWXZJz4zIM_Q:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. Now waiting on review from @amcastro-tri .

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-:-KRoaCV9aMY9D3vEpcVN:bsm83j6)*

**Comment by amcastro-tri** [comment]
:lgtm:. Thank you for the VC conversation @liangfok 

---

Reviewed 20 of 20 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3460#-:-KRohI6wTzsj0F1kDb_P:bd200f9)*

**Pull request merged**
