### PR TITLE
Added instructions on how to pipe Doxygen generation output to a file…

### PR DESCRIPTION
**Pull request by liangfok**
… that can then be manually searched.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2547)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for both levels of review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Added instructions on how to pipe Doxygen generation output to a file…
> 
> … that can then be manually searched.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2547#-:-KK6XohIkytvmYtH7PZ4:1454177270)*

**Comment by sherm1** [comment]
I don't think this is helpful, @liangfok. There are two problems: (1) we are running doxygen in "verbose" mode so lots of useless stuff comes out obscuring the warnings; that can easily be fixed by changing the Doxyfile to make it quiet (set `QUIET=YES`; (2) there are a lot of unnecessary doxygen warnings produced by bad doxygen comments in the code; those should be fixed so that new ones are visible.

Also the instructions you provide (a) don't work on Windows, and (b) are just the basics of output redirection that any Linux user should know about. I don't think we should provide Linux documentation.

I suggest replacing this PR with one that puts Doxygen in QUIET mode instead.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> +@sherm1 for both levels of review.
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2547#-:-KK6mBfmgORct5PPG-QE:-965336983)*

**Comment by liangfok** [comment]
Done. PTAL. Please ignore all files except for DoxyFile_CXX.in and doxygen_instructions.rst. All other files are not part of this commit and their changes were already merged into master. I think it's a bug in Reviewable or an incompatibility between my merge-only workflow and Reviewable.

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I don't think this is helpful, @liangfok. There are two problems: (1) we are running doxygen in "verbose" mode so lots of useless stuff comes out obscuring the warnings; that can easily be fixed by changing the Doxyfile to make it quiet (set `QUIET=YES`; (2) there are a lot of unnecessary doxygen warnings produced by bad doxygen comments in the code; those should be fixed so that new ones are visible.
> 
> Also the instructions you provide (a) don't work on Windows, and (b) are just the basics of output redirection that any Linux user should know about. I don't think we should provide Linux documentation.
> 
> I suggest replacing this PR with one that puts Doxygen in QUIET mode instead.
</details>


---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2547#-:-KK9LuiP-88kGigmvh8M:2118177368)*

**Comment by jwnimmer-tri** [comment]
@liangfok Can you close and reopen the PR, or redo the branch, or something?  Having to ignore the commits and reviewable changes is deeply unsatisfactory -- moreso since the original PR has nothing to do with this new PR.

**Comment by liangfok** [comment]
OK will do.

**Pull request closed without merging**
