### PR TITLE
clang-format-includes on multibody

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Changes (almost?) all `#include` statements in `drake/multibody` to obey `cppguide` and `code_style_guide`.

Relates #2269.

I have a tool that generates these changes, but it's not good enough for master yet (it requires fixing-by-hand of a few nits).  However, pushing its true-positive fixes to master in the meantime (1) helps us have cleaner code, and (2) allows me to more easily iterate on the remaining diffs that the tool wants to make.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5535)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
Just a few comments. PTAL

---

Reviewed 65 of 65 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/approximate_ik.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSDbgSn3csZhrX0x8i:-KfSDbgSn3csZhrX0x8j:b-t84j9w) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/approximate_ik.cc#L2)):*
> ```cpp
> #include <math.h>
> ```

Are blank line spaces intentional?

---

*[drake/multibody/rigid_body_tree.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSEHOEgMZmKrk1NVtp:-KfSEHOEgMZmKrk1NVtq:b-8de2z5) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/rigid_body_tree.h#L22)):*
> ```objc
> #include "drake/multibody/collision/drake_collision.h"
> #include "drake/multibody/collision/element.h"
> #include "drake/multibody/force_torque_measurement.h"
> ```

BTW, actually, I like it better how it was before. I see then the alphabetization is the one strong rule we follow, regardless of how deep the include directory is?

---

*[drake/multibody/collision/bullet_model.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSEx77YFGoIPFEVej6:-KfSEx77YFGoIPFEVej7:bnprkjt) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/collision/bullet_model.h#L11)):*
> ```objc
> #include "BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h"
> #include "BulletCollision/NarrowPhaseCollision/btPointCollector.h"
> #include "btBulletCollisionCommon.h"
> ```

Why does this file end at the bottom?

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSIQikffRmlVGmqHOv:-KfSIQikffRmlVGmqHOw:bnqcunh) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L5)):*
> ```cpp
> #include <memory>
> 
> #include <gtest/gtest.h>
> ```

I just realize saw while reviewing this PR the form "gtest/gtest.h" (between quotes instead of brackets). Which one should we adopt?x

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_face_extraction_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSIrSWghLtS4XRDe75:-KfSIrSWghLtS4XRDe76:b-gk6zh0) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/test/rigid_body_tree/rigid_body_tree_face_extraction_test.cc#L5)):*
> ```cpp
> #include <memory>
> 
> #include "gtest/gtest.h"
> ```

Here you are, an example using quotes instead.

---

*[drake/systems/analysis/test/simulator_test.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSJ9Te6I1pmFm1cjxT:-KfSJ9TfHClI2upwvoxT:b-3lt908) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/systems/analysis/test/simulator_test.cc#L8)):*
> ```cpp
> #include <map>
> 
> #include <unsupported/Eigen/AutoDiff>
> ```

Should we change these to `#include "drake/common/eigen_autodiff_types"`? here and other occurrences. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-:-KfSJmFfc0nNrE6ioUPh:byk8jor)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/multibody/approximate_ik.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSDbgSn3csZhrX0x8i:-KfSKpz2N-fvfciBG9aC:b-kb80ls) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/approximate_ik.cc#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Are blank line spaces intentional?
</blockquote></details>

Yes.

 _"For the order of includes style rule, separate each category of #include statements with a blank line. Then, accept whatever clang-format enforces."_ 
-- http://drake.mit.edu/code_style_guide.html#clarifications

The `math.h` is a C system header; the `<set>` is a C++ system header, thus the blank line.

---

*[drake/multibody/rigid_body_tree.h, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSEHOEgMZmKrk1NVtp:-KfSKyZwgdIBTRqf25FC:b-s3k3bn) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/rigid_body_tree.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, actually, I like it better how it was before. I see then the alphabetization is the one strong rule we follow, regardless of how deep the include directory is?
</blockquote></details>

_" ...accept whatever clang-format enforces"_ which is this alphabetization.

---

*[drake/multibody/collision/bullet_model.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSEx77YFGoIPFEVej6:-KfSLGipmpy2AqjPVn66:b-5b5v94) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/collision/bullet_model.h#L11)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Why does this file end at the bottom?
</blockquote></details>

_" ...accept whatever clang-format enforces"_ which is this alphabetization.

ASCII `B` is 66, ASCII `b` is  98.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSIQikffRmlVGmqHOv:-KfSLWOgSuS99sQk4N2f:bfptm76) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/test/rigid_body_tree/rigid_body_tree_completeness_test.cc#L5)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I just realize saw while reviewing this PR the form "gtest/gtest.h" (between quotes instead of brackets). Which one should we adopt?x
</blockquote></details>

Right now, both are acceptable.

---

*[drake/multibody/test/rigid_body_tree/rigid_body_tree_face_extraction_test.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSIrSWghLtS4XRDe75:-KfSL_Nj5NMUujkfY6sE:bs4q9op) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/test/rigid_body_tree/rigid_body_tree_face_extraction_test.cc#L5)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Here you are, an example using quotes instead.
</blockquote></details>

Ditto.

---

*[drake/systems/analysis/test/simulator_test.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSJ9Te6I1pmFm1cjxT:-KfSLfSt0bHDK0Jpzhtn:bm55xq) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/systems/analysis/test/simulator_test.cc#L8)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Should we change these to `#include "drake/common/eigen_autodiff_types"`? here and other occurrences. 
</blockquote></details>

Probably both are fine?  I haven't thought about it.  In this PR, I am only focused on _sorting_ the include statements to follow the rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5535)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/multibody/approximate_ik.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-KfSDbgSn3csZhrX0x8i:-KfSN2KKkcv8KDqONSFe:b-zcjvte) ([raw file](https://github.com/robotlocomotion/drake/blob/ee5fa53ee423c4ea145f00b0cfa922673dc9d5cb/drake/multibody/approximate_ik.cc#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.

 _"For the order of includes style rule, separate each category of #include statements with a blank line. Then, accept whatever clang-format enforces."_ 
-- http://drake.mit.edu/code_style_guide.html#clarifications

The `math.h` is a C system header; the `<set>` is a C++ system header, thus the blank line.
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-:-KfSNGsyuVws8OoWgZWY:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-:-KfSNbOtys2-P6s6OqD0:bcav8r0)*

**Comment by ggould-tri** [comment]
:lgtm:; for future automated changes strongly consider posting a link to the tool used and separating the automated changes from the manual fixups into separate commits so that reviewers can concentrate on the tool and fixups rather than the net result.

---

Reviewed 14 of 65 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5535#-:-KfSnyd2YyGWBeTXlw0s:b-bau3)*

**Comment by jwnimmer-tri** [comment]
FTR the tool is WIP at https://github.com/jwnimmer-tri/drake/tree/clang-format-includes

**Pull request merged**
