### PR TITLE
[geometry] Provide deformable-deformable contact data

### LINKED ISSUE #19704: [geometry] Support deformable-deformable contact
**Is your feature request related to a problem? Please describe.**
We want to extend the deformable simulation to support contacts between two deformable geometries. Currently, we only support contacts between a deformable geometry and a rigid geometry.

**Describe the solution you'd like**

- [X] 1. Add a new member function of DeformableContact in `//geometry/query_results:deformable_contact`:
```C++
class drake::geometry::internal::DeformableContact {
    void AddDeformableDeformableContactSurface(
      GeometryId id0, GeometryId id1,
      const std::unordered_set<int>& participating_vertices0,
      const std::unordered_set<int>& participating_vertices1,
      PolygonSurfaceMesh<T> contact_mesh_W, std::vector<T> signed_distances,
      std::vector<Vector4<int>> contact_vertex_indexes0,
      std::vector<Vector4<int>> contact_vertex_indexes1,
      std::vector<Vector4<T>> barycentric_coordinates0,
      std::vector<Vector4<T>> barycentric_coordinates1);
};
```
- [X] 2. Add the corresponding free function in a new module `//geometry/proximity:deformable_field_intersection`:
```C++
void
drake::geometry::internal::AddDeformableDeformableContactSurface(
    const deformable::DeformableGeometry& deformable0_W,  GeometryId deformable0_id,
    const deformable::DeformableGeometry& deformable1_W,  GeometryId deformable1_id,
    DeformableContact<double>* deformable_contact);
```
This function will compute the deformable contact surface and add it to the given DeformableContact output parameter.

- [ ] 3. Call the new function from `//geometry/proximity:deformable_contact_internal`:
```C++
namespace drake {
namespace geometry {
namespace internal {
namespace deformable {

DeformableContact<double> Geometries::ComputeDeformableContact() const {
  DeformableContact<double> result;
...
  for (auto it0 = deformable_geometries_.begin(); it0 != deformable_geometries_.end(); ++it0) {
  ...
    for (auto it1 = std::next(it0, 1); it1 != deformable_geometries_.end(); ++it2) {
      AddDeformableDeformalbeContactSurface(
          deformable_geometry0_W, deformable0_id,
          deformable_geometry1_W, deformable1_id,
          &result);
    }
  }
...
  return result;
}

}  // namespace deformable
}  // namespace internal
}  // namespace geometry
}  // namespace drake
```

@xuchenhan-tri has created a prototype in his commit [xuchenhan-tri@d89faa7](https://github.com/xuchenhan-tri/drake/commit/d89faa76d63d966aeaf2a4347b5def58d257edaf). It's very helful.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Resolve #19704

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
@xuchenhan-tri has finished the unit tests. This PR is back to me.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-:-Nl0hA1a4MwVJ4ziiTOQ:b-cpcac5)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-:-Nl0nuqhCS6Cqtpv1Bsg:b-pjyba6)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: 3 unresolved discussions, needs at least two assigned reviewers

**Comment by xuchenhan-tri** [comment]
*[`geometry/query_object.h` line 417 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-Nl4cX0K2LeRwbW5jcST:-Nl6EDd_CPs8VMVPqCYw:b3y7u0x) ([raw file](https://github.com/RobotLocomotion/drake/blob/c96f6746069c34ba56f254fd14edfe61a72bae5e/geometry/query_object.h#L417)):*
The "rigid geometry" in this context refers to any geometry that's not associated with a deformable body.

> I think if users set up a compliant-hydroelastic geometry, it will get another rigid representation (triangle mesh) (in addition to a tetrahedral mesh for hydro contact) to make contact with deformable geometries. 

Correct! And I think as long as this rigid representation (triangle mesh) agrees with the tet mesh for hydro contact (i.e. it is the surface of the tet mesh), the distinction will be immaterial for an end user.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`geometry/proximity/test/deformable_contact_internal_test.cc` line 444 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-Nl4m_6g-1z063vlbrTp:-NlQuSCO5ElrweXlesXE:blhkk1) ([raw file](https://github.com/RobotLocomotion/drake/blob/c96f6746069c34ba56f254fd14edfe61a72bae5e/geometry/proximity/test/deformable_contact_internal_test.cc#L444)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to Working.  I'll set up a test fixture. Thanks.
</blockquote></details>

Done.  We have a test fixture now.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`geometry/query_object.h` line 417 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-Nl4cX0K2LeRwbW5jcST:-NlQvFXA3q9hCT0x8han:bkz5nhk) ([raw file](https://github.com/RobotLocomotion/drake/blob/c96f6746069c34ba56f254fd14edfe61a72bae5e/geometry/query_object.h#L417)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The "rigid geometry" in this context refers to any geometry that's not associated with a deformable body.

> I think if users set up a compliant-hydroelastic geometry, it will get another rigid representation (triangle mesh) (in addition to a tetrahedral mesh for hydro contact) to make contact with deformable geometries. 

Correct! And I think as long as this rigid representation (triangle mesh) agrees with the tet mesh for hydro contact (i.e. it is the surface of the tet mesh), the distinction will be immaterial for an end user.
</blockquote></details>

Done.  Use the word "non-deformable" instead of "rigid".

**Review by DamrongGuoy — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-:-NlTZKlEA2c1XMCv8Qts:bcav8r0)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

___
*[`geometry/proximity/deformable_contact_internal.h` line 107 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-NlTvXql45vBE8z1IcCM:-NlVF2Xx6PK977QVBYFY:bavgphp) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab27a52f6abb9be8134a8ffa00b9c0ff42ce73d1/geometry/proximity/deformable_contact_internal.h#L107)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  See below; in the test you are going to rely on the order of the members of each contact of this return value.  You need to document here either what the invariant is on the returned contacts or that they are arbitrary.
</blockquote></details>

Done.  I changed the test to not rely on the order of the members of each contact. Thanks for the suggestion in the test.
___
*[`geometry/proximity/deformable_contact_internal.cc` line 110 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-NlTr0bFCUesCfGkS-gx:-NlVJVjC4ut_DHzin5yw:b1ycjlz) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab27a52f6abb9be8134a8ffa00b9c0ff42ce73d1/geometry/proximity/deformable_contact_internal.cc#L110)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  It was very difficult for me to prove that `std::next` is sound here.
The crucial facts are:
 * `std::next` requires `LegacyInputIterator` which is guaranteed multipass-safe, and
 * This method is `const`, so the underlying collection will not change.

I'm not sure there's a way to convey this in a comment without being even more confusing, though.
</blockquote></details>

Done.  Hopefully this helps. I added more comments for the nested loops and changed to const_iterator to emphasize read-only.
___
*[`geometry/proximity/deformable_contact_internal.cc` line 110 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-NlTreZ_CFpshwLU1DGT:-NlVK1HV6j2q1AzgmdiU:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab27a52f6abb9be8134a8ffa00b9c0ff42ce73d1/geometry/proximity/deformable_contact_internal.cc#L110)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  IMO it's a bit clearer to omit the default increment when it's 1, since that's what a reader will infer that "next" means.
</blockquote></details>

Done. Thanks.
___
*[`geometry/proximity/test/deformable_contact_internal_test.cc` line 491 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20614#-NlTuEjS2Aj3xclWJ1cP:-NlVXCsaCKlA0fHetdg5:b-n7aduj) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab27a52f6abb9be8134a8ffa00b9c0ff42ce73d1/geometry/proximity/test/deformable_contact_internal_test.cc#L491)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems like an abstraction violation to me -- it's relying on knowing internal details of `Geometries` that are not part of its documented API.

If you want to test that the order is precisely right, you need to document the order as part of the API (i.e., that `contact_surfaces()` returns surfaces whose geometries are ordered with respect to some documented principle); alternatively, if you want to test that a contact of two bodies is present, you need to test both possible orders.

You could do this by constructing both possible `expect`s, checking which one has the same `id_A` as the return value, and asserting against that one.
</blockquote></details>

Done.  I constructed both possible `expect01` and `expect10`.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20614)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform)

**Pull request merged**
