### PR TITLE
separates Build() from Start() and adds accessor to the automotive simulator diagram

### PR DESCRIPTION
**Pull request by RussTedrake**
This will enable optimization on the simulator diagram (coming in the next PR)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5849)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@liangfok for feature review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-:-Kho8HmzmpnVw2BWeZ4d:b-ui3opy)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-:-KhoUjOWQTPgPaBxrRYb:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review, please

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-:-KhoW7CJgSICxrl_XOga:b-5s300q)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-KhrK1hzBV3gdWIM2yPM:-KhrK1hzBV3gdWIM2yPN:b-sejnzf) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec518abe66ad9d7a2b9dd4234807e13d6c1ba96/drake/automotive/automotive_simulator.h#L207)):*
> ```objc
>   }
> 
>   /// Calls Build() on the diagram (if it has not been build already) and
> ```

FYI, reflow this paragraph please:

```c++
  /// Calls Build() on the diagram (if it has not been build already) and
  /// initializes the Simulator. No further changes to the diagram may occur
  /// after this has been called.
```

---

*[drake/automotive/automotive_simulator.h, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-KhrKX0PdjyamLgaAgd_:-KhrKX0PdjyamLgaAgda:bjhqoul) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec518abe66ad9d7a2b9dd4234807e13d6c1ba96/drake/automotive/automotive_simulator.h#L216)):*
> ```objc
>   /// systems::Simulator::set_target_realtime_rate().
>   //
>   // TODO(jwnimmer-tri) Perhaps this should be Build(), that returns an
> ```

BTW, do we need to remove or update this `TODO`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-:-KhrOB5BdHggwjobi53t:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.h, line 207 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-KhrK1hzBV3gdWIM2yPM:-KhrR8VXgFd3w2C0fMrb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec518abe66ad9d7a2b9dd4234807e13d6c1ba96/drake/automotive/automotive_simulator.h#L207)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, reflow this paragraph please:

```c++
  /// Calls Build() on the diagram (if it has not been build already) and
  /// initializes the Simulator. No further changes to the diagram may occur
  /// after this has been called.
```
</blockquote></details>

Done.

---

*[drake/automotive/automotive_simulator.h, line 216 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-KhrKX0PdjyamLgaAgd_:-KhrRM3B9PJjvPU_neR4:blk22gf) ([raw file](https://github.com/robotlocomotion/drake/blob/4ec518abe66ad9d7a2b9dd4234807e13d6c1ba96/drake/automotive/automotive_simulator.h#L216)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, do we need to remove or update this `TODO`?
</blockquote></details>

updated. (the second half of the comment remains valid)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5849#-:-Khy7QZDbg_PQu8kP9l9:bvi7gpa)*

**Comment by jwnimmer-tri** [comment]
@RussTedrake Please do not PR `clang-format` reformatting of unrelated lines concurrently with functional changes.  It makes it difficult to review the functional changes.

**Comment by david-german-tri** [comment]
`clang-format-diff` is a useful tool in this situation.

**Comment by RussTedrake** [comment]
Good to know.

I don't understand why clang-format needs to make changes to the other code --- shouldn't it all be compliant by now?

**Comment by jwnimmer-tri** [comment]
> I don't understand why clang-format needs to make changes to the other code --- shouldn't it all be compliant by now?

Definitely not.  People disliked some of its choices enough that we stopped requesting it / using it globally, and there is no automatic enforcement (other than the few major defects that cpplint identifies), so now most code is formatted a least a little differently than what `clang-format` wants to see.  See #4843 for slightly-related background.  I think the current best practice is to use `clang-format` in an advisory role when you don't know what code should look like (which is sometimes easier with `clang-format-diff`), but to always sanity-check its changes.

We can probably do better, but that's the status right now.

**Pull request merged**
