### PR TITLE
Simplified LCM Translator Method Names

### LINKED ISSUE #3483: Consider Generalizing LCM Translator Method Names
# Current Proposal
LCM Translators have the following two methods:

1. `LcmAndVectorBaseTranslator::TranslateLcmToVectorBase()`
2. `LcmAndVectorBaseTranslator::TranslateVectorBaseToLcm()`

I'm thinking about simplifying them to be:

1. `LcmAndVectorBaseTranslator::DeSerialize()`
2. `LcmAndVectorBaseTranslator::Serialize()`

There are several motivations:

1. The method names will be easier to read.
2. The intent of the methods will be easier to understand.
3. The same method names can be used by translators for other middleware systems like ROS. This consistency will aid in understanding due to familiarity.

Thoughts?

# Older Proposals

I'm thinking about simplifying it to be:

1. `LcmAndVectorBaseTranslator::FromLcm()`
2. `LcmAndVectorBaseTranslator::ToLcm()`

### PR DESCRIPTION
**Pull request by liangfok**
Renamed "TranslateVectorBaseToLcm" to be "Serialize" and "TranslateLcmToVectorBase" to be "Deserialize".

Resolves #3483.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3497)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-:-KRxpxaMPL3JmMXncN_h:bcv4nxl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 11 of 16 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/lcm_vector_gen.py, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRz0_g7j0rLy9NYJ3QA:-KRz0_g8N2xy7x_g9oYf:b-6u50mc) ([raw file](https://github.com/robotlocomotion/drake/blob/918e7409e9f5e92b5587a33a1bdede3315e4a8e0/drake/automotive/lcm_vector_gen.py#L303)):*
> ```Python
> 
> 
> def generate_lcm_to_vector_base(cc, caller_context, fields):
> ```

This name of this "generate" method (and the next one) and the preceding NAMED_CONSTANTs (and next ones) are stale with respect to the (de)serialize rename.

---

*[drake/systems/lcm/lcm_publisher_system.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRz05bMOjKoFwrbk0jy:-KRz05bMOjKoFwrbk0jz:bixzgh4) ([raw file](https://github.com/robotlocomotion/drake/blob/918e7409e9f5e92b5587a33a1bdede3315e4a8e0/drake/systems/lcm/lcm_publisher_system.cc#L48)):*
> ```cpp
>   // Translates the input vector into LCM message bytes.
>   std::vector<uint8_t> lcm_message;
>   translator_.Serialize(context.get_time(), *input_vector,
> ```

BTW Fit this onto one line now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497)*

**Comment by liangfok** [comment]
@jwnimmer-tri, I addressed your comments. PTAL. Thanks.

---

Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/lcm_vector_gen.py, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRz0_g7j0rLy9NYJ3QA:-KRzLl9MEWhRZQt4odSN:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/918e7409e9f5e92b5587a33a1bdede3315e4a8e0/drake/automotive/lcm_vector_gen.py#L303)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This name of this "generate" method (and the next one) and the preceding NAMED_CONSTANTs (and next ones) are stale with respect to the (de)serialize rename.
</details>
Done. Thanks.

---

*[drake/systems/lcm/lcm_publisher_system.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRz05bMOjKoFwrbk0jy:-KRzLydhswmXgCcB88_U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/918e7409e9f5e92b5587a33a1bdede3315e4a8e0/drake/systems/lcm/lcm_publisher_system.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Fit this onto one line now?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-:-KRzMELo6glpVKSKkpbR:b-617z9l)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/lcm_vector_gen.py, line 292 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRzcLH_Ny0QdEE9zymr:-KRzcLHaYTtlHMqa-Mwc:b-5p322u) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd477ecf096b220dad027176d53b9d2a524771/drake/automotive/lcm_vector_gen.py#L292)):*
> ```Python
>   message.timestamp = static_cast<int64_t>(time * 1000);
> """
> DESERIALIZE = """
> ```

BTW Maybe `DESERIALIZE_FIELD`?   The other "per field" literals all have `FIELD` in their name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-:-KRzccWkw0MwS6jqDFB8:bnfp4nl)*

**Comment by liangfok** [comment]
Just waiting on CI now.

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/lcm_vector_gen.py, line 292 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-KRzcLH_Ny0QdEE9zymr:-KRzfjgPAr07bL81X--C:b-qu6n94) ([raw file](https://github.com/robotlocomotion/drake/blob/24cd477ecf096b220dad027176d53b9d2a524771/drake/automotive/lcm_vector_gen.py#L292)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Maybe `DESERIALIZE_FIELD`?   The other "per field" literals all have `FIELD` in their name.
</details>
Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497#-:-KRzg21VZBC2Od1gRcVx:biq4u0j)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3497)*

**Comment by liangfok** [comment]
@jwnimmer-tri, the CI failure was due to #2798. Can you override merge?

**Comment by jwnimmer-tri** [comment]
Yes, prior build was okay, and the recent edit was just to python code not run by jenkins.  Using override-merge.

**Pull request merged**
