### PR TITLE
Prototype [geometry,lcmtypes,multibody,tools] visualization of polygonal contact patches.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Draft PR. Do not review yet.

Combine Joe's (see Joe's polygon_contact_surface branch) and
Sean's code (see closed draft PR #15749) and mine.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15753)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
Hm...it's weird that the commit message has Joe as the author even though I'm the one who `force push`.  I guess it's because we use Joe's PolygonalSurfaceMesh data structure.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15753#-:-MjGB_J48fSZn8STgeae:b-fmaf7w)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by DamrongGuoy** [comment]
___
*[multibody/plant/contact_results_to_lcm.cc, line 176 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15753#-MjGCop1AqO69O-lq8Mi:-MjGCop20-Yh8EwtFxwk:bri58r0) ([raw file](https://github.com/robotlocomotion/drake/blob/5d4fd411bc7eb5f997f530201627be5edd0337d9/multibody/plant/contact_results_to_lcm.cc#L176)):*
> ```cpp
>   // However, you might want to switch `#if 1` to `#if 0` when visualizing
>   // the polygonal contact patches instead of the triangulated contact patches.
> #if 1
> ```

If you want to stop sending to LCM the triangulated contact patches, you can flip `1` to `0` here.

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy what's your development plan for this feature?  I might need to account for this idea while working on #15738.

**Review by DamrongGuoy — COMMENTED** [review]
Sorry. I should close this prototype already.  It's not going anywhere.  Close now.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15753#-:-MuwODr_0Odi5Cr9iPUj:b7kxjmh)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request closed without merging**
