### PR TITLE
[trajectories] Cleanup PiecewisePose and add python bindings

### PR DESCRIPTION
**Pull request by RussTedrake**
- Fix: PiecewisePose was not properly initializing its base class.
- Updates the non-virtual public methods to be style-guide compliant (and deprecates the old names).
- Adds python bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15786)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@siyuanfeng-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15786#-:-Mjl4d6TBMmRcQ6EeM6c:b-1z9bi2)* status: LGTM missing from assignee siyuanfeng-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @siyuanfeng-tri)

**Review by siyuanfeng-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15786#-:-MjlGKds4tYPZ3FaTjbs:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for platform thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

FWIW I guess the base / constituent classes, e.g. `PiecewisePolynomial`, `PiecewiseTrajectory`, may need style guide upgrades at some point.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15786#-:-MjofksE-ZoIe_x2mEqM:b-wwsdm3)* status: :shipit: complete! all discussions resolved, LGTM from assignees siyuanfeng-tri,EricCousineau-TRI(platform) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
Somehow, this didn't make it into the v0.35.0 "newly deprecated" notes.

**Pull request merged**
