### PR TITLE
[multibody] Add SapFixedConstraint

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-Nd7FiEw2OFhU3uuCz3J:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
OK I took a look over the constraint class, still have to look at the test. Some questions on making sure we have the right symbols for which vertices are which and some questions about what the right spatial impulses to report are. PTAL. 

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-NdlDTtXDw6iF1L63VoL:b-631pg3)* status: 7 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl74Sg7AbmWYHzRPzW:-Ndl74Sg7AbmWYHzRPzX:bxt5hoq) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
> ```objc
>    num_constraint_equations().
>    @param[out] F On output this function will accumulate the spatial impulse
>    applied by this constraint on the o-th object about its body origin.
> ```

While this is true for  existing constraints that report spatial impulses (contact, ball, weld, distance), I think I had a discussion with @amcastro-tri that it might not be true always. Will need him to report in on this.

For instance when object `o` corresponds to the deformable object reporting a single spatial impulse on the body doesn't exactly make sense, correct? 



_Code quote:_
```objc
   applied by this constraint on the o-th object about its body origin.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl98FtBRsnNQVw4nAj:-Ndl98FtBRsnNQVw4nAk:b-opfkxy) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L25)):*
> ```objc
>                 Must be non-negative.
>      @param[in] p_APs_W
>                 Positions of point Ps in A, expressed in the world frame.
> ```

These will be the positions of the deformable body's vertices under constraint, right? I think we have control so WLOG object A can always be either the deformable body, or one of the deformable bodies. I think it makes more sense to then call these `p_WPs` and document that these are the deformable body's vertex positions at the current timestep.



_Code quote:_
```objc
     @param[in] p_APs_W
                Positions of point Ps in A, expressed in the world frame.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAAgh1dP84iIzYNpa:-NdlAAgh1dP84iIzYNpb:be4v8u3) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L30)):*
> ```objc
>                 Must be non-negative.
>      @param[in] p_BQs_W
>                 Positions of point Qs in B, expressed in the world frame.
> ```

Likewise these may be vertices of another deformable body, or material points of a rigid body. So they may be `p_BQs_W` or `p_WQs` depending on the context. Maybe a bit more documentation here to express that. 



_Code quote:_
```objc
     @param[in] p_BQs_W
                Positions of point Qs in B, expressed in the world frame.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl9oCm-_vpVfr9X312:-Ndl9oCm-_vpVfr9X313:b-46t2v) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L33)):*
> ```objc
>      @param[in] p_PQs_W
>                 Displacements from point Ps to point Qs, expressed in the
>                 world frame.
> ```

Are you going to require the calling code (`SapDriver` presumably) to precompute these? You could have the kinematics class do it because it has `p_APs_W` and `p_BQs_W`, but I'm not sure if you need these in another context since I haven't seen the code that hooks up the constraints to the driver.



_Code quote:_
```objc
     @param[in] p_PQs_W
                Displacements from point Ps to point Qs, expressed in the
                world frame.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAtCpBmVzc-bCGo5I:-NdlAtCpBmVzc-bCGo5J:bgb0ajf) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L85)):*
> ```objc
>  constraint lacks frame-invariance. It is unclear at this time if choosing a
>  particular frame leads to a better approximation, conditioning, etc. We choose
>  the world frame for convenience.
> ```

I have the frame invariant and angular momentum conserving formulation written up in the weld constraint (#19608) stablized now.

I haven't reformulated the ball constraint, but plan on doing that next. Since this mirrors the ball constraint a lot, we could push this in as is with the frame dependence and non angular momentum conserving formulation and then do a pass later to reformulate this and the ball constraint. Or I could help you reformulate it based on the translational part of the weld constriant. I'll leave it up to you.



_Code quote:_
```objc
 N.B. Only when Pᵢ and Qᵢ are coincident is their relative velocity independent
 of which frame it is measured in. This means that the way we model this
 constraint lacks frame-invariance. It is unclear at this time if choosing a
 particular frame leads to a better approximation, conditioning, etc. We choose
 the world frame for convenience.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlBhhv7B1t9fLs2WIA:-NdlBhhv7B1t9fLs2WIB:b-9gkg4u) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L99)):*
> ```objc
>  DoAccumulateSpatialImpulses() shifts these impulses to the body frame origins,
>  reporting the total spatial impulses Γ_Bo_W and Γ_Ao_W from all n point pairs,
>  respectively.
> ```

nit: Body frame origins only make sense for rigid bodies, right? I think we have to consider what we're reporting for deformable objects.



_Code quote:_
```objc
 DoAccumulateSpatialImpulses() shifts these impulses to the body frame origins,
 reporting the total spatial impulses Γ_Bo_W and Γ_Ao_W from all n point pairs,
 respectively.
```
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.cc` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlCl6D889ShHQ0mmll:-NdlCl6D889ShHQ0mmlm:b486qb4) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.cc#L64)):*
> ```cpp
>       const SpatialForce<T> gamma_Ap_W(Vector3<T>::Zero(),
>                                        -gamma.template segment<3>(3 * c));
>       *F += gamma_Ap_W.Shift(-p_APs_W_.template segment<3>(3 * c));
> ```

It is unclear to me what `Ao` will mean when `A` is a deformable body. Presumably you'll be passing in `p_WPs` into what you're calling `p_APs_W`, the positions of the constraint vertices in world. So this will construct one big spatial impulse applied at the world origin? I think we have to consider what makes the most sense to report for deformable bodies. When one is rigid (presumable B wlog) this shift makes sense. 



_Code quote:_
```cpp
    // Shift gamma_Ap_W = to Ao and add in.
    for (int c = 0; c < num_constrained_point_pairs_; ++c) {
      const SpatialForce<T> gamma_Ap_W(Vector3<T>::Zero(),
                                       -gamma.template segment<3>(3 * c));
      *F += gamma_Ap_W.Shift(-p_APs_W_.template segment<3>(3 * c));
```

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the review. I see that many comments have a common theme about the body frame of deformable bodies. 

Right now, we are operating under the assumption that the body frames of all deformable bodies are equal to the world frame, but we are leaving open the option to have non-world local frames for deformable bodies.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-NdlrQHSCLXI9JO29ZMQ:bqmianm)* status: 7 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl74Sg7AbmWYHzRPzW:-NdltUdT6TUdRp_owdZ2:b-dpyrac) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

While this is true for  existing constraints that report spatial impulses (contact, ball, weld, distance), I think I had a discussion with @amcastro-tri that it might not be true always. Will need him to report in on this.

For instance when object `o` corresponds to the deformable object reporting a single spatial impulse on the body doesn't exactly make sense, correct?
</blockquote></details>

I agree the spatial impulse isn't particularly useful for dynamics purpose but I think it'd still be useful to report it for example to visualize constraint forces.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl98FtBRsnNQVw4nAj:-NdltoK5-2Dv1rTpdm_v:b-bhj82j) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L25)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

These will be the positions of the deformable body's vertices under constraint, right? I think we have control so WLOG object A can always be either the deformable body, or one of the deformable bodies. I think it makes more sense to then call these `p_WPs` and document that these are the deformable body's vertex positions at the current timestep.
</blockquote></details>

See the comment in the main thread.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAAgh1dP84iIzYNpa:-Ndlu7_X4dopq2ofeDzy:b-z4a88i) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L30)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Likewise these may be vertices of another deformable body, or material points of a rigid body. So they may be `p_BQs_W` or `p_WQs` depending on the context. Maybe a bit more documentation here to express that.
</blockquote></details>

I think the current notation is general enough to cover both the rigid and deformable cases.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl9oCm-_vpVfr9X312:-NdlqpjU6ixOAcimmUv5:b-5wjwpl) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L33)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Are you going to require the calling code (`SapDriver` presumably) to precompute these? You could have the kinematics class do it because it has `p_APs_W` and `p_BQs_W`, but I'm not sure if you need these in another context since I haven't seen the code that hooks up the constraints to the driver.
</blockquote></details>

I don't think the `kinematics` can compute p_PQ from p_AP and p_BQ because it doesn't have information on A and B.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAtCpBmVzc-bCGo5I:-Ndlr5AsE0zMCQqQL7uK:b63etnj) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L85)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I have the frame invariant and angular momentum conserving formulation written up in the weld constraint (#19608) stablized now.

I haven't reformulated the ball constraint, but plan on doing that next. Since this mirrors the ball constraint a lot, we could push this in as is with the frame dependence and non angular momentum conserving formulation and then do a pass later to reformulate this and the ball constraint. Or I could help you reformulate it based on the translational part of the weld constriant. I'll leave it up to you.
</blockquote></details>

Working.

Let's get it right on the first try.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlBhhv7B1t9fLs2WIA:-NdluJl98AVsMAwwQQTl:b-1tv29y) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L99)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: Body frame origins only make sense for rigid bodies, right? I think we have to consider what we're reporting for deformable objects.
</blockquote></details>

Currently, the deformable bodies' origins are all equal to the world origin. 
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.cc` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlCl6D889ShHQ0mmll:-NdluY0F9293VEJ0C3i8:b-1tv29y) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.cc#L64)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

It is unclear to me what `Ao` will mean when `A` is a deformable body. Presumably you'll be passing in `p_WPs` into what you're calling `p_APs_W`, the positions of the constraint vertices in world. So this will construct one big spatial impulse applied at the world origin? I think we have to consider what makes the most sense to report for deformable bodies. When one is rigid (presumable B wlog) this shift makes sense.
</blockquote></details>

Currently, the deformable bodies' origins are all equal to the world origin.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098)* status: 7 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAtCpBmVzc-bCGo5I:-Ne4fPfpAxbcmVu0VCCh:b-ss0aiy) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Working.

Let's get it right on the first try.
</blockquote></details>

I changed the formulation to express the impulse at a common frame. This does not affect the implementation though. PTAL and see if you agree.

**Review by joemasterjohn — COMMENTED** [review]
Thanks for your patience. :lgtm: with a little reversion to the initial formulation. Thanks!

> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-NeEIXVs2Njz_lFyBUHM:b-5xgacd)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl74Sg7AbmWYHzRPzW:-NeEAsPmDS2iQJ8KKAHA:b-2439de) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
Oh I still believe it to be useful, I just disagree with this comment change:
> about its body origin.

The contact constraints report the spatial impulses at points `Ap` on body `A` and `Bq` on body `B` from the `ContactConfiguration` and makes note that `p` and `q` are not necessarily the body origin. From my reading of the deformable driver `Ap` is the centroid of the contact surface. So I think we need to keep this comment agnostic about the spatial impulse's applied at point. 
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 25 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl98FtBRsnNQVw4nAj:-NeEEe-c5SmUQsTUoup-:b-locel6) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

See the comment in the main thread.
</blockquote></details>

Ok thanks.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAAgh1dP84iIzYNpa:-NeEEivm61CfMYg2SMcG:b-6dv9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think the current notation is general enough to cover both the rigid and deformable cases.
</blockquote></details>

Ok I agree, given the deformable bodies' origins are always the world origin.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl9oCm-_vpVfr9X312:-NeEDw7FEvoevCEWVJQS:b6l6ww8) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think the `kinematics` can compute p_PQ from p_AP and p_BQ because it doesn't have information on A and B.
</blockquote></details>

Ah yes, ok thanks.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 85 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlAtCpBmVzc-bCGo5I:-NeEEuQnBZX0QL2vgooG:b-flkyt2) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L85)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I changed the formulation to express the impulse at a common frame. This does not affect the implementation though. PTAL and see if you agree.
</blockquote></details>

per f2f: Let's leave this as is (without the intermediate expressed-in frame `N`) and reconsider the application point at another time so we can think out defining the jacobian of a point exterior to a deformable surface. Maybe just a little TODO as a reminder for that.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.h` line 99 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlBhhv7B1t9fLs2WIA:-NeEEOsSBPgdeqrtF7yM:bcr5s31) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.h#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Currently, the deformable bodies' origins are all equal to the world origin.
</blockquote></details>

Got it, thanks.
___
*[`multibody/contact_solvers/sap/sap_fixed_constraint.cc` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-NdlCl6D889ShHQ0mmll:-NeEESbYDgoVK37oiXBw:b-54avio) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_fixed_constraint.cc#L64)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Currently, the deformable bodies' origins are all equal to the world origin.
</blockquote></details>

Ok, thanks.

**Review by joemasterjohn — COMMENTED** [review]
+@sammy-tri for platform review, please.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-NeJ1b8S4dLCK_2laFrv:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform)

___
*[`multibody/contact_solvers/sap/sap_constraint.h` line 244 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-Ndl74Sg7AbmWYHzRPzW:-NeIx-eC4YZ426-WPr8r:b7y8aw9) ([raw file](https://github.com/RobotLocomotion/drake/blob/10dc040c8ebf8dc46b83ecbd7521a04a9b5b1726/multibody/contact_solvers/sap/sap_constraint.h#L244)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done.

Sorry I misunderstood the comment. You are right that the contact constraint is an outlier. I think it's a defect that the "about point" of the spatial impulse is not defined in the base class and there's no way to retrieve that information other than an understanding of the implementation.
</blockquote></details>

I agree, we should revisit this.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20098#-:-NeJGh8MBt_Y3pPXd_72:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),joemasterjohn

**Pull request merged**
