### PR TITLE
EqualityConstrainedQPSolver solves a const program.

### PR DESCRIPTION
**Pull request by hongkai-dai**
As listed in #9633.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9981)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for feature review please, thanks!

@jwnimmer-tri I can't open reviewable. I don't know if reviewable is down, or just I cannot access it in China. One problem I encountered in this PR is that we could set solver options in two ways, one is to store the option in `MathematicalProgram`, the other is to pass the option in the `Solve` function. How shall we handle when we set the same option in both ways? In this PR, I make the options in `Solve` function to take priority over the option stored in `prog`. Should we apply this principle to all solvers?

**Comment by jwnimmer-tri** [comment]
> How shall we handle when we set the same option in both ways? In this PR, I make the options in Solve function to take priority over the option stored in prog.

Yes, I agree.

> Should we apply this principle to all solvers?

Yes.

**Comment by hongkai-dai** [comment]
> To ensure users can opt-in to more compile-time checking of options keys, the "FeasibilityTol" string should be available in programmatic form (a constant, or static getter) as part of EqualityConstrainedQPSolver's public API.

Sorry I don't completely follow this. Do you suggest that `EqualityConstrainedQPSolver` to have a private field `FeasibilityTol_`, and a public API `get_feasibility_tol() const`? I think adding the private field would violate the constness of `Solve()` function. If we want to run `Solve` in multiple threads, then this function has to be a const function, and hence I cannot set the private field `FeasibilityTol_` inside `Solve` function.

**Comment by jwnimmer-tri** [comment]
You are right that having an _instance_ method on the solver would be overkill (though, it would not be related to threading at all -- since the field would be read-only, it could be used by multiple threads).  I imagine either a public static field (of `char*`-based type, to remain POD), or a public static method (returning either `const char*` or `std::string`) would be fine.  Basically we just want a named constant for the user, so they don't copy-pasta `"FeasibilityTol"` everywhere, and then wonder why it stopped working when we renamed the string to `"feasibility_tol"` during some API upgrade.

**Comment by hongkai-dai** [comment]
> You are right that having an instance method on the solver would be overkill (though, it would not be related to threading at all -- since the field would be read-only, it could be used by multiple threads). I imagine either a public static field (of char*-based type, to remain POD), or a public static method (returning either const char* or std::string) would be fine. Basically we just want a named constant for the user, so they don't copy-pasta "FeasibilityTol" everywhere, and then wonder why it stopped working when we renamed the string to "feasibility_tol" during some API upgrade.

I see, I misread your comment as adding `double feasibility_tol_` to store the **value** of the feasibility tolerance. I added a static method to return the string.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I addressed the some of the comments (except for these related to solver options), could you take a look? There is a PR #9996 addressing merging solver options. I will address the issues related to solver options in this PR, once #9996 is merged.

**Comment by hongkai-dai** [comment]
@jwnimmer-tri I have addressed your comments related to SolverOptions. Could you take a look after the Thanksgiving holiday? Thanks!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
