### PR TITLE
New Frame methods CalcRelativeSpatialVelocity(), CalcRelativeSpatialVelocityInWorld().

### PR DESCRIPTION
**Pull request by mitiguy**
This PR helps with part of issue #16189.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review @samzapo  (followed by @sherm1)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-Mx6Y8sbDi6Gng3Df-Zi:boipns6)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by samzapo — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691)* status: 1 unresolved discussion, LGTM missing from assignee samzapo, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16691#-MxAu4gx55B2f3tFaUNu:-MxAu4gy9V1qWr8e3RUu:b-hk9lao) ([raw file](https://github.com/robotlocomotion/drake/blob/fa1ea7455cdbc6fb8959f92a85681c721a0f6364/multibody/plant/test/frame_kinematics_test.cc#L123)):*
> ```cpp
>       V_HL3_E.get_coeffs(), V_HL3_E_expected.get_coeffs(),
>       kTolerance, MatrixCompareType::relative));
> ```

Nit: I'd like to see these tests duplicated for `C` as a `FixedOffsetFrame` (i.e., not a `BodyFrame`), as a differing `ω_MD_E = ω_MC_E` of a body frame, `D`, to which Frame `C` is affixed, will affect the relative translational velocity, `v_M_BoCo_E`, only if `Co` is offset from its parent body frame origin, `Do` (i.e. `|p_DoCo| > 0`).

**Review by mitiguy — COMMENTED** [review]
@sherm1  I think this is ready for you to do a 2nd-pass feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-MxBtcGy0LorF2lddeU_:b-oufuxs)* status: 1 unresolved discussion, LGTM missing from assignee samzapo, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@sherm1 -- I finished the tests, so it is ready for a full look.
@samzapo -- thanks for the review.  Hopefully the new tests highlight the fixed offset frame H.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-MxHsRmp3GB6XlwYOSEy:b7ckkgt)* status: LGTM missing from assignee samzapo, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @samzapo)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16691#-MxAu4gx55B2f3tFaUNu:-MxHl42n7UgJrKNa4x7c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa1ea7455cdbc6fb8959f92a85681c721a0f6364/multibody/plant/test/frame_kinematics_test.cc#L123)):*
<details><summary><i>Previously, samzapo (Samuel Zapolsky) wrote…</i></summary><blockquote>

Nit: I'd like to see these tests duplicated for `C` as a `FixedOffsetFrame` (i.e., not a `BodyFrame`), as a differing `ω_MD_E = ω_MC_E` of a body frame, `D`, to which Frame `C` is affixed, will affect the relative translational velocity, `v_M_BoCo_E`, only if `Co` is offset from its parent body frame origin, `Do` (i.e. `|p_DoCo| > 0`).
</blockquote></details>

Done.

**Review by samzapo — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-MxLJrd_BAXC-ARWDAMz:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16691#-MxAu4gx55B2f3tFaUNu:-MxLKrdfCVlYqKiKeve0:bvvdwx6) ([raw file](https://github.com/robotlocomotion/drake/blob/fa1ea7455cdbc6fb8959f92a85681c721a0f6364/multibody/plant/test/frame_kinematics_test.cc#L123)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good, 
BTW, I had to pull up drake and do some diggin got see that `frame_H_` was a fixed offset frame.

I suppose the lines
```
  const Vector3<double> p_EH =
      frame_H_->GetFixedPoseInBodyFrame().translation();
```
(above) help elucidate that, but it's not immediately obvious.

**Review by sherm1 — COMMENTED** [review]
Nice -- feature :lgtm: with a few minor comments.
+@sammy-tri for platform review per rotation, please

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-MxWv3XMBWMABVtyfM97:b-ujtzpr)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sammy-tri)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16691#-MxWr5FjAh7LjTDFs9Vm:-MxWr5FjAh7LjTDFs9Vn:bmoidty) ([raw file](https://github.com/robotlocomotion/drake/blob/38dcd3b65d55a1c636d981a7669da0383ffa0b8c/multibody/plant/test/frame_kinematics_test.cc#L45)):*
> ```cpp
>       plant_->CalcRelativeRotationMatrix(*context_, *frame_H_, *frame_H_);
>   EXPECT_TRUE(CompareMatrices(R_HH.matrix(), Matrix3<double>::Identity(),
>                               kTolerance, MatrixCompareType::relative));
> ```

BTW not clear why these two tests were added in this PR. Were they just some missing tests, or are they related to the new methods somehow? OK either way but should mention these in the commit message if they are independent of the relative spatial velocity methods.
___
*[multibody/plant/test/frame_kinematics_test.cc, line 146 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16691#-MxWrjZl0raqoVjqaV4j:-MxWrjZl0raqoVjqaV4k:b4ojv12) ([raw file](https://github.com/robotlocomotion/drake/blob/38dcd3b65d55a1c636d981a7669da0383ffa0b8c/multibody/plant/test/frame_kinematics_test.cc#L146)):*
> ```cpp
>   const SpatialVelocity<double> V_WL3_W =
>       frame_L3.CalcSpatialVelocityInWorld(*context_);
>   const SpatialVelocity<double> V_W_L3H_W_expected = V_WH - V_WL3_W;
> ```

BTW the redundant `_W`s in your variable names add clutter and inconsistency. They make every line harder to read, and don't play well with the pre-existing cleaner symbols like V_WH. Why not save those for where they actually mean something, like in `w_L3H_W` below? By adding them to every symbol, it is easy for the reader to miss the few cases where the `_W` is actually conveying something important.

Anyone familiar with monogram notation understands the expressed-in frame default -- it is always there explicitly as the first symbol. If your goal is clarity for the reader, making the reader wade through unnecessary redundancies does not improve it!

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  (one of the rare cases where I get to see an update for the PR while I'm reading it).  Waiting on CI.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16691#-:-Mx_zMso5mvjivIUZG_Z:bka9utq)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Pull request merged**
