### PR TITLE
Adding a model of the heavy duty metal table used with the iiwa arm.

### PR DESCRIPTION
**Pull request by Lucy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3265)

### CODE REVIEW

**Comment by Lucy-tri** [comment]
+@liangfok for feature review, please.

**Comment by Lucy-tri** [comment]
@ggould-tri may be interested.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-:-KQ2TaPic2HqHH6afHh4:b-z6arw4)*

**Comment by liangfok** [comment]
Completed first round of feature review. PTAL.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2U3-puCZacfsBzOhN:-KQ2U3-q8e2vQ9eA0t1A:bpwcqo5) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L7)):*
> ```
>       <pose frame=''>-0.243716 -0.625087 0 0 -0 0</pose>
>       <inertial>
>         <mass>12</mass>
> ```

Please add the following comment above the `<mass>` tag:

```
<!--
TODO(lucy): Update this mass to be the correct mass. Update the spatial inertia
below once this mass changes.
-->
```

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2S3LTDREpy3bWXHBE:-KQ2S3LTDREpy3bWXHBF:b6wqyi7) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L9)):*
> ```
>         <mass>12</mass>
>         <pose frame=''>0 0 0 0 -0 0</pose>
>         <inertia>
> ```

Please add the following comment above the `<inertia>` explaining how these numbers were derived:

```
<!--
The spatial inertia values given below were derived based on the
equation for a cuboid:

https://en.wikipedia.org/wiki/List_of_moments_of_inertia#List_of_3D_inertia_tensors.

Obviously, the table is not a cuboid, meaning the inertia matrix is
imperfect. Having an accurate spatial inertia specification may be
important for us to know when / if a robot mounted on top of the
table will cause the table to tip over. It will also be necessary to model
what happens when a mobile robot bumps into the table.

TODO(lucy): Compute a more accurate spatial inertia of this table.
-->
```

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2USHyFwau5EyRSDuS:-KQ2USHyFwau5EyRSDuT:b2fez71) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L29)):*
> ```
>         <material>
>           <script>
>             <uri>file://media/materials/scripts/gazebo.material</uri>
> ```

Note everyone will have this installed. Maybe add a comment saying "one must install Gazebo to have this file"?

This comment applies to all similar instances below.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 273 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2UmJCYy6wtdJ_vp-j:-KQ2UmJCYy6wtdJ_vp-k:b-b6yuji) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L273)):*
> ```
>             <bullet>
>               <split_impulse>1</split_impulse>
>               <split_impulse_penetration_threshold>-0.01</split_impulse_penetration_threshold>
> ```

Line is over 80 characters wide.

(same comment to all instance below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-:-KQ2UsoJPt9zdPZBZvC-:bt9qbi6)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 273 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2UmJCYy6wtdJ_vp-j:-KQ6GAnSMuFBmgzSW43d:b-9xvvg2) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L273)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Line is over 80 characters wide.
> 
> (same comment to all instance below)
</details>
Enforcing 80 characters in XML files is impractical.  This should probably be author's discretion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265)*

**Comment by Lucy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 7 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2U3-puCZacfsBzOhN:-KQ6DlvUo8DZrmq-mtab:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L7)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Please add the following comment above the `<mass>` tag:
> 
> ```
> 
> ```
</details>
Done.

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 9 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2S3LTDREpy3bWXHBE:-KQ6EUqVNXIae1nNK6co:b1yju74) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Please add the following comment above the `<inertia>` explaining how these numbers were derived:
> 
> ```
> 
> ```
</details>
Done.  Thanks for writing that all out for me. 

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2USHyFwau5EyRSDuS:-KQ6IdVH4KSJ7t9tOmSH:b-3cfhoc) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Note everyone will have this installed. Maybe add a comment saying "one must install Gazebo to have this file"?
> 
> This comment applies to all similar instances below.
</details>
SDF documentation of script element: "this will override the color element if the script exists". Meaning, it will override the ambient, diffuse, and other color tags under material. So I think this is well documented in SDF and doesn't need further doc here. 

---

*[drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf, line 273 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-KQ2UmJCYy6wtdJ_vp-j:-KQ6JZagfIycWtAzqaOt:bhu7p79) ([raw file](https://github.com/robotlocomotion/drake/blob/2a8076838fa7ab26d698116aecc7f3dab00f2aaa/drake/examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf#L273)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Enforcing 80 characters in XML files is impractical.  This should probably be author's discretion.
</details>
OK, I'm going to leave it alone. It doesn't really help readability  in this case, to wrap the lines. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265)*

**Comment by Lucy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-:-KQ6MtRwvZHRAKDpJ5oo:b-gbk9vg)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-:-KQ6OD_KTRbDYt32TBEf:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3265#-:-KQ6ONVnJWJklUANcpLo:bnfp4nl)*

**Comment by liangfok** [comment]
CC: @hongkai-dai

**Pull request merged**
