### PR TITLE
Add IPOPT to the Bazel build

### PR DESCRIPTION
**Pull request by david-german-tri**
Linux only for now, I'm timeboxing the toxic swamp of OS X problems.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4905)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@rpoyner-tri for feature review

**Comment by rpoyner-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/BUILD, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbM_LCjxBLs6uLNyM26:-KbMV-PuBbAL-O8-oP65:b-40lcpj) ([raw file](https://github.com/robotlocomotion/drake/blob/3cc95d53699a9724bd7d2fb0998e9d68f8419a8e/tools/BUILD#L70)):*
> ```Python
>     name = "apple",
>     values = {"cpu": "darwin"},
> )
> ```

final newline please.

---

*[tools/ipopt.BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbM_ikybToUwSl3WgCU:-KbM_ikzxFtfVLykqtHR:b-i4lhko) ([raw file](https://github.com/robotlocomotion/drake/blob/3cc95d53699a9724bd7d2fb0998e9d68f8419a8e/tools/ipopt.BUILD#L14)):*
> ```
> # find include/coin -name "*.h" -o -name "*.hpp" -o -name "*.hdd" | sort |
> # sed 's/$/",/g'| sed 's/^/"/g'
> IPOPT_HDRS = [
> ```

BTW, I don't know if it's defectable yet, but please run this file through buildifier.sh. It changes some things, but the result works and does not appear to wreck the .a file ordering below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by david-german-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/BUILD, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbM_LCjxBLs6uLNyM26:-KbMdE8Rvj7uFT423ta8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3cc95d53699a9724bd7d2fb0998e9d68f8419a8e/tools/BUILD#L70)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

final newline please.
</blockquote></details>

Done.

---

*[tools/ipopt.BUILD, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbM_ikybToUwSl3WgCU:-KbMdOWugJrj7Dopb_RB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3cc95d53699a9724bd7d2fb0998e9d68f8419a8e/tools/ipopt.BUILD#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, I don't know if it's defectable yet, but please run this file through buildifier.sh. It changes some things, but the result works and does not appear to wreck the .a file ordering below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-:-KbMnSHBNLcvjl6DKfyt:bnfp4nl)*

**Comment by david-german-tri** [comment]
-(status: do not merge) -(status: do not review) 

+@jwnimmer-tri for platform review

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-:-KbMo2RJQK7OKvx_A8TV:b-gjwwvl)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.  I still need to read the ipopt.BUILD, but looks good on the rest.

---

Reviewed 6 of 8 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-:-KbMzvdirNTR4JeR3dHG:bh1iqz4)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/ipopt.BUILD, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNBSGBugYjdORoHTft:-KbNBSGCqCBgK8dY4y0O:b-233dxv) ([raw file](https://github.com/robotlocomotion/drake/blob/30366b3094049dbab4e57bba74a66e054d3fba0b/tools/ipopt.BUILD#L110)):*
> ```
>     srcs = glob([
>         "*",
>         "**/*",
> ```

BTW I am surprised that this second line doesn't subsume the first?

---

*[tools/ipopt.BUILD, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNAu6fBTMCHdr93i-4:-KbNAu6fBTMCHdr93i-5:btrymy6) ([raw file](https://github.com/robotlocomotion/drake/blob/30366b3094049dbab4e57bba74a66e054d3fba0b/tools/ipopt.BUILD#L134)):*
> ```
>     visibility = ["//visibility:public"],
>     alwayslink = 1,
> )
> ```

BTW For other externals with a clear single output library, we have been providing a `:lib` target by convention (this is what our pkg-config repository rule does, for example).  Maybe add an https://bazel.build/versions/master/docs/be/general.html#alias here for `:lib`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by david-german-tri** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/ipopt.BUILD, line 110 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNBSGBugYjdORoHTft:-KbNDoP1QlR0HnuNBYg8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30366b3094049dbab4e57bba74a66e054d3fba0b/tools/ipopt.BUILD#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I am surprised that this second line doesn't subsume the first?
</blockquote></details>

Done.

---

*[tools/ipopt.BUILD, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNAu6fBTMCHdr93i-4:-KbNEDn_K0_El3cMmJe8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/30366b3094049dbab4e57bba74a66e054d3fba0b/tools/ipopt.BUILD#L134)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For other externals with a clear single output library, we have been providing a `:lib` target by convention (this is what our pkg-config repository rule does, for example).  Maybe add an https://bazel.build/versions/master/docs/be/general.html#alias here for `:lib`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by jwnimmer-tri** [comment]
Still doing some local testing, but so far so good.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-:-KbNEom2M1Hghn2iFtLz:b-tllzri)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 87 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNHaHsCkkv1LX_-Qjq:-KbNHaHsCkkv1LX_-Qjr:btqda3c) ([raw file](https://github.com/robotlocomotion/drake/blob/0c21747be00aeac22e7f66c127eb11ce2c2c9432/tools/ipopt.BUILD#L87)):*
> ```
>     "lib/libipoptamplinterface.a",
>     "lib/libcoinmumps.a",
>     "lib/libcoinmetis.a",
> ```

We should not be using Metis due to licensing.  I'm okay merging this PR to just match CMake -- iff there's a TODO comment added here citing #4913 and a note posted to 4913 reminding us to fix this BUILD file also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-:-KbNKBEpkiGbDrkhCl21:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/BUILD, line 325 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbQ8U2HV8x9mLatHN3w:-KbQ8U2HV8x9mLatHN3x:be55v8i) ([raw file](https://github.com/robotlocomotion/drake/blob/0c21747be00aeac22e7f66c127eb11ce2c2c9432/drake/solvers/BUILD#L325)):*
> ```Python
>         "test/mathematical_program_test_util.h",
>         "test/nonlinear_program_test.cc",
>         "test/optimization_examples.cc",
> ```

BTW are we building this module twice now -- here and in the prior test rule?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/BUILD, line 325 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbQ8U2HV8x9mLatHN3w:-KbQ8kQlbxQmGPJOkp_U:b-3mre81) ([raw file](https://github.com/robotlocomotion/drake/blob/0c21747be00aeac22e7f66c127eb11ce2c2c9432/drake/solvers/BUILD#L325)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW are we building this module twice now -- here and in the prior test rule?
</blockquote></details>

Yup.  (Though not a _new_ defect as of this PR.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ipopt.BUILD, line 87 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4905#-KbNHaHsCkkv1LX_-Qjq:-KbQGRaTx9k8crKCVW4m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0c21747be00aeac22e7f66c127eb11ce2c2c9432/tools/ipopt.BUILD#L87)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We should not be using Metis due to licensing.  I'm okay merging this PR to just match CMake -- iff there's a TODO comment added here citing #4913 and a note posted to 4913 reminding us to fix this BUILD file also.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4905)*

**Comment by david-german-tri** [comment]
Not sure if the bazel failure is real.

@drake-jenkins-bot linux-gcc-bazel-experimental please

**Pull request merged**
