### PR TITLE
Add bindings for IiwaCommand/Status Sender/Receivers

### PR DESCRIPTION
**Pull request by hjsuh94**
The bindings for IiwaCommandSender, IiwaStatusReceiver, etc. are missing, and are added in this PR. 

These bindings allow the user to export the ports in their own python version of the `manipulation_station` to LCM, allowing them to make their own python version of `mock_station_simulation`.

@mpetersen94 could I request a review from you since this is mostly derived from #13470?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature and platform review +(status: single reviewer ok), modulo the below comments.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987#-:-MZeq98Q9HKPNYRsoGqN:b-h8g21u)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hjsuh94)

___
*[bindings/pydrake/manipulation/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeopVMCAcGh6U5qB8A:-MZeopVMCAcGh6U5qB8B:b-tivco1) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/BUILD.bazel#L96)):*
> ```Starlark
>     deps = [
>         ":kuka_iiwa_py",
>         "//bindings/pydrake/multibody",
> ```

nit The test program does not `import ... multibody` -- so this line seems either incorrect or misplaced.
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZepU_FELm42-LZpRCK:-MZepU_FELm42-LZpRCL:bk6kxdr) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L3)):*
> ```cpp
> #include "pybind11/eigen.h"
> #include "pybind11/pybind11.h"
> #include "pybind11/stl.h"
> ```

nit I don't think these classes use any stl types in their bound methods.  Can you try removing this include statement?
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeqR3W2VXXnW4DCBa-:-MZeqR3W2VXXnW4DCBa0:b-ulnyl5) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L26)):*
> ```cpp
> 
>   {
>     using Class = manipulation::kuka_iiwa::IiwaCommandReceiver;
> ```

nit This is up to you, but I'll note one things you could do here, if you like.

If you search in other bindings folders for "Emulate placement in namespace", you'll find examples for how import a C++ namespace within the `PYBIND11_MODULE` function, so that you don't need to say `manipulation::kuka_iiwa` here and everywhere below, you could just say `IiwaCommandReceiver` or `kIiwaArmNumJoints` directly.

I see that nothing else in the "pydrake/manipulation" folder does this already, so it's fine to leave this alone if you like.
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeprIR2HYhZz3uAZBX:-MZeprIR2HYhZz3uAZBY:b-hofemi) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L57)):*
> ```cpp
>         .def("get_position_input_port", &Class::get_position_input_port,
>             py_rvp::reference_internal, cls_doc.get_position_input_port.doc)
>         .def("get_torque_input_port", &Class::get_position_input_port,
> ```

` &Class::get_torque_input_port`

Ditto on the next line as well.
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeox5sECVaII8gzYjE:-MZeox5sECVaII8gzYjF:b-2kwmcd) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L19)):*
> ```cpp
> void BindCppSerializers() {
>   // N.B. At least one type should be bound to ensure the template is defined.
>   // N.B. These should be placed in the same order as the headers.
> ```

nit This (somewhat hidden) comment explains how to sort the lines below.  Please adjust the new lines to match this advice.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hjsuh94)

___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZes-gH7pcM6rqSijwS:-MZes-gIA4Sb1zsfqPaM:bmc1iq4) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L10)):*
> ```cpp
> #include "drake/lcmt_quaternion.hpp"
> #include "drake/lcmt_schunk_wsg_command.hpp"
> #include "drake/lcmt_schunk_wsg_status.hpp"
> ```

nit In the `BUILD.bazel` rule for this target (`drake_pybind_library(name = "lcm_py", ...)`), it lists `cc_deps` for the three messages that were already bound.  Could you add explicit deps for these four new include statements?  The build is passing because we're picking them up transitively, but to be on the safe side and for consistency its probably worth adding them directly.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hjsuh94 and @jwnimmer-tri)

___
*[bindings/pydrake/manipulation/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeopVMCAcGh6U5qB8A:-MZeyCmC1pnTH_y5OgGO:ba0inpp) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/BUILD.bazel#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The test program does not `import ... multibody` -- so this line seems either incorrect or misplaced.
</blockquote></details>

Done. what I needed was `systems`!
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeqR3W2VXXnW4DCBa-:-MZeyJdU7QVDTd7EB18Z:b-z1g5hl) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This is up to you, but I'll note one things you could do here, if you like.

If you search in other bindings folders for "Emulate placement in namespace", you'll find examples for how import a C++ namespace within the `PYBIND11_MODULE` function, so that you don't need to say `manipulation::kuka_iiwa` here and everywhere below, you could just say `IiwaCommandReceiver` or `kIiwaArmNumJoints` directly.

I see that nothing else in the "pydrake/manipulation" folder does this already, so it's fine to leave this alone if you like.
</blockquote></details>

Done. I think it made the code cleaner :) 
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeprIR2HYhZz3uAZBX:-MZeyMa656p714ruxF0e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

` &Class::get_torque_input_port`

Ditto on the next line as well.
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZes-gH7pcM6rqSijwS:-MZeyQ-g36Z6P5RsTgep:bsb9k3r) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In the `BUILD.bazel` rule for this target (`drake_pybind_library(name = "lcm_py", ...)`), it lists `cc_deps` for the three messages that were already bound.  Could you add explicit deps for these four new include statements?  The build is passing because we're picking them up transitively, but to be on the safe side and for consistency its probably worth adding them directly.
</blockquote></details>

Done. Added `//lcmtypes::iiwa` and `lcmtypes::schunk` in the `BUILD.bazel` file! 
___
*[bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeox5sECVaII8gzYjE:-MZeyY669-c40gyo_ggJ:b-m5qhzu) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This (somewhat hidden) comment explains how to sort the lines below.  Please adjust the new lines to match this advice.
</blockquote></details>

Done. Alphabetically reordered like the header files.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hjsuh94)

___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeprIR2HYhZz3uAZBX:-MZf3SUW6-Y1h_Tk6VwJ:b-11f1f2) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L57)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done yet.
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZf3Uyu06WSq60E2B8V:-MZf3Uyu06WSq60E2B8W:b107oko) ([raw file](https://github.com/robotlocomotion/drake/blob/9b590ca3450e927b26cef0a17f96662710505dcf/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L21)):*
> ```cpp
>   using drake::manipulation::kuka_iiwa::IiwaStatusReceiver;
>   using drake::manipulation::kuka_iiwa::IiwaStatusSender;
>   using drake::manipulation::kuka_iiwa::kIiwaArmNumJoints;
> ```

nit Instead of listing these out one by one, the pattern goes like this:

```cxx
// NOLINTNEXTLINE(build/namespaces): Emulate placement in namespace.
using namespace drake::manpulation::kuka_iiwa;
```

That would appear directly before L26:
```
constexpr auto& doc = pydrake_doc.drake.solvers;
```

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZeprIR2HYhZz3uAZBX:-MZfH16N-s8yRffH9cNr:b-s5tguo) ([raw file](https://github.com/robotlocomotion/drake/blob/511878e92332885447e89c62fddb6ef63639d12d/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Not done yet.
</blockquote></details>

Done. Good catch! 
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 21 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZf3Uyu06WSq60E2B8V:-MZfGp0S4NLxfbBzmV7C:b4cd84y) ([raw file](https://github.com/robotlocomotion/drake/blob/9b590ca3450e927b26cef0a17f96662710505dcf/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L21)):*
> // NOLINTNEXTLINE(build/namespaces): Emulate placement in namespace.

Done. I understand now! 
___
*[bindings/pydrake/manipulation/kuka_iiwa_py.cc, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14987#-MZfF7PJ39nsicIriScF:-MZfF7PJ39nsicIriScG:btce2ie) ([raw file](https://github.com/robotlocomotion/drake/blob/9b590ca3450e927b26cef0a17f96662710505dcf/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L60)):*
> Ditto on the next line as well.
>           1 hour ago
>         hjsuh94Hyung Ju Suh (Terry)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14987)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hjsuh94)

**Pull request merged**
