### PR TITLE
py common: Move AbstractValue and Value here

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is intended to reflect the C++ API change in #10357
Deprecate old spellings

Revived as part of #13162

~FYI @jwnimmer-tri - after watching compile times on AWS, I wanna slowly creep towards #6760.~

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12430)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI would you like me to start to review this tomorrow?  Priority low or medium?

**Comment by EricCousineau-TRI** [comment]
Tomorrow would be great!

**Comment by jwnimmer-tri** [comment]
___
*[common/test_utilities/drake_py_unittest_main.py, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12430#-M6AEIm56kay_IDbun5u:-M6AEIm56kay_IDbun5v:bju3642) ([raw file](https://github.com/robotlocomotion/drake/blob/ec5310414a82313fe185909331063ee62f80f14a/common/test_utilities/drake_py_unittest_main.py#L62)):*
> ```Python
>         sys.exit(1)
> 
>     # On import, force all drake deprecation warnings to trigger an error.
> ```

How about putting this in a preemptive PR?  It's a big conceptual change and deserves a good commit message and CI spins, before we do all of the big path shuffling in this PR.

**Comment by EricCousineau-TRI** [comment]
> BTW The generated API reference for `pydrake.common.value.Value[]` is quite the spectacular sight!

Hehe, yeah. Should be addressed via #12231

**Comment by jwnimmer-tri** [comment]
CI shows a couple of missing `import`.

**Comment by EricCousineau-TRI** [comment]
Forgot my `mut`!

**Pull request merged**
