### PR TITLE
Add Bazel code style config. Update documentation for code style checking

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This adds `--config pycodestyle` for running Python code-style checks, and adds `--config lint` for C++ and Python style checking.

This updates the documentation:
1. Adds usage of the general code style check.
2. Adds usage of Python code style check.
3. Replace usage of `pep8` with `pycodestyle` (per [note on pypi page](https://pypi.python.org/pypi/pycodestyle#pycodestyle-formerly-called-pep8-python-style-guide-checker))
4. Moves `pylint` to the bottom, as it does not appear to be part of CI.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6076)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@soonho-tri for platform review, please.

Let me know if you think the general name should be changed from `lint` to something like `codestyle` or what not.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-:-KjstDnmdEq4pfewudSS:b-ea0p7q)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_tools.rst, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-Kjt6dDbl4rtclL_HzyX:-Kjt6dDbl4rtclL_HzyY:b-ct04j9) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/drake/doc/code_style_tools.rst#L109)):*
> ```reStructuredText
> ``pycodestyle``, which used to be ``pep8``, is the primary code style checker used within Drake.
> 
> On Ubuntu, install via ``pip``::
> ```

BTW For CMake builds only, not needed for Bazel builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_tools.rst, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-Kjt6dDbl4rtclL_HzyX:-KjtKD9-1gWxF9If8tJX:biozj62) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/drake/doc/code_style_tools.rst#L109)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW For CMake builds only, not needed for Bazel builds.
</blockquote></details>

Done. Thanks for the tip!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_tools.rst, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtSazM6-IV449oge7b:-KjtSazNTXlDp2ebwcwg:bxboowo) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/drake/doc/code_style_tools.rst#L21)):*
> ```reStructuredText
> .. _code-style-tools-general:
> 
> When using the Bazel build system, code style tests are run by default during ``bazel
> ```

_Meta_ This file was wrapped to <= 80; please keep that intact in the prose (here, the following paragraph, and a few others).  (The literal blocks have to be overwide, of course, since they don't reflow.)

---

*[tools/bazel.rc, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtGZriPHnoOQOeWz3u:-KjtGZriPHnoOQOeWz3v:bb65ytt) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/tools/bazel.rc#L99)):*
> ```
> 
> ### Lint. ###
> # Code style compliance for C++ and Python, merging both cpplint and pycodestyle.
> ```

BTW When possible, keep lines in this rcfile to <= 80 characters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-:-KjtSzgGpssQIFHdSinq:by96gdd)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_tools.rst, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtSazM6-IV449oge7b:-Kjtfrb-OLotmNQL5uzU:bs4s46w) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/drake/doc/code_style_tools.rst#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ This file was wrapped to <= 80; please keep that intact in the prose (here, the following paragraph, and a few others).  (The literal blocks have to be overwide, of course, since they don't reflow.)
</blockquote></details>

Done. Modified lines outside the scope of this PR, for consistency, but can revert those changes if need be.

---

*[tools/bazel.rc, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtGZriPHnoOQOeWz3u:-KjtfwjaTMK5DzFzT916:b-4oo82p) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/tools/bazel.rc#L99)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW When possible, keep lines in this rcfile to <= 80 characters.
</blockquote></details>

Done. Also modified lines outside the scope of PR; let me know if you'd like me to keep to this scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076)*

**Comment by jwnimmer-tri** [comment]
:lgtm: on the non-python parts.  +@rpoyner-tri was the author of the python instructions, so should be the one to feature-review those changes.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_tools.rst, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtmorU54_U00LFaymP:-KjtmorU54_U00LFaymQ:bpdymct) ([raw file](https://github.com/robotlocomotion/drake/blob/2c621fd124349d2b1aaa64ad6df3c45b805b09c7/drake/doc/code_style_tools.rst#L17)):*
> ```reStructuredText
>    :local:
> 
> General
> ```

BTW I think by "General" you mean "For all languages" or similar?  Would a more specific title be helpful?

---

*[tools/bazel.rc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtmNDJi-CRYhmOKpoV:-KjtmNDJi-CRYhmOKpoW:b-wg2d6f) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/tools/bazel.rc#L74)):*
> ```
> ### Unsupported Crosstool ###
> # Use the default Bazel-generated CROSSTOOL.
> # This may be useful for developers with unsupported workstation configurations.
> ```

FYI This was ==80 which was not a problem, but wrapping it is fine too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-:-KjtnG6qnG9_Q8PaUFTH:bfzfeug)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_style_tools.rst, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtmorU54_U00LFaymP:-Kjtq4ELqerqNQdzGEzG:b-1upp9v) ([raw file](https://github.com/robotlocomotion/drake/blob/2c621fd124349d2b1aaa64ad6df3c45b805b09c7/drake/doc/code_style_tools.rst#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think by "General" you mean "For all languages" or similar?  Would a more specific title be helpful?
</blockquote></details>

Done. Changed to "All Languages" - thanks!

---

*[tools/bazel.rc, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-KjtmNDJi-CRYhmOKpoV:-KjtqCVis2ovATSFc-TW:b-5g6quu) ([raw file](https://github.com/robotlocomotion/drake/blob/25e91603bcfa3eb1ebf9c0ea1dd74d05c4955a57/tools/bazel.rc#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This was ==80 which was not a problem, but wrapping it is fine too.
</blockquote></details>

Done. Hmm... Seems like Sublime's wrapping definition is < DESIRED_WIDTH, rather than <= DESIRED_WIDTH. I've set my column width to 81.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-:-Kju8FCyUbkwb-Sitoda:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
:lgtm: I am a little concerned about not being able to nerf pycodestyle errors inline, but we can deal with that as it arises.

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6076#-:-KkBxgsseY2-5mZJyMmV:bbpi2i0)*

**Pull request merged**
