### PR TITLE
default_scalars_pybind: Consolidate CopyIfNotPodType functions

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Add doxygen group
Switch docstrings from /// to use /** */
Fix minor typos in helper functions

Follow-up to #14823

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!
+@sherm1 for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839#-:-MWzniEs3oC8_hGklJFf:b-xeda8e)* status: LGTM missing from assignees hongkai-dai,sherm1(platform) (waiting on @hongkai-dai and @sherm1)

**Comment by EricCousineau-TRI** [comment]
For documentation, pics or it didn't happen!

```sh
$ git log -n 1 --oneline --no-decorate
64709ce818 default_scalars_pybind: Consolidate CopyIfNotPodType functions
$ bazel build //doc/doxygen_cxx:build
$ bazel-bin/doc/doxygen_cxx/build --quick ./bindings/
$ firefox ./build/drake/doc/doxygen_cxx/html/namespacedrake_1_1pydrake.html
```

> image

**Comment by jwnimmer-tri** [comment]
The overloads here are probably not something we want to introduce to the public API?  I suspect that code could be much more clear and compact with a simple `if constexpr T == double` in a single template function without overloads.

**Comment by EricCousineau-TRI** [comment]
I'm fine w/ it being public API (paying depr. cost) pending seeing a concrete rendering / redux.
I'm also fine with this PR stalling for a bit if you want.

**Comment by jwnimmer-tri** [comment]
Filed https://github.com/EricCousineau-TRI/drake/pull/14.

**Comment by EricCousineau-TRI** [comment]
That's awesome - thank you!!!

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839#-:-MX-K-uw1W1EXBBaj71w:bg7igkv)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @hongkai-dai, and @sherm1)

___
*[bindings/pydrake/common/default_scalars_pybind.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14839#-MX-JrIGAC1CpJhlvTh2:-MX-JrIGAC1CpJhlvTh3:bvn1bm1) ([raw file](https://github.com/robotlocomotion/drake/blob/ea9fa912c91fb2f2f380d119a8a73d3e6d24fb5e/bindings/pydrake/common/default_scalars_pybind.h#L70)):*
> ```objc
>   } else {
>     constexpr int ColsAtCompileTime = NestedExpression::ColsAtCompileTime;
>     return Eigen::Matrix<T, Eigen::Dynamic, ColsAtCompileTime>(x);
> ```

Just curious, why  RowsAtCompileTime here is Eigen::Dynamic instead of NestedExpression::RowsAtCompileTime?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai and @sherm1)

___
*[bindings/pydrake/common/default_scalars_pybind.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14839#-MX-JrIGAC1CpJhlvTh2:-MX-xJJl9_8OqHg_Yf2w:bit4god) ([raw file](https://github.com/robotlocomotion/drake/blob/ea9fa912c91fb2f2f380d119a8a73d3e6d24fb5e/bindings/pydrake/common/default_scalars_pybind.h#L70)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious, why  RowsAtCompileTime here is Eigen::Dynamic instead of NestedExpression::RowsAtCompileTime?
</blockquote></details>

OK My guess is that Jeremy used `Eigen::Dynamic` covered the concrete usages of `VectorX<double>` and `MatrixX<double>`. (Also, it's Python bindings, so fixed-size things only matter for size-checking; speed's already punted for small things haha.)

However, I don't see any harm in generalizing it further. Changed.

**Comment by jwnimmer-tri** [comment]
___
*[bindings/pydrake/common/default_scalars_pybind.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14839#-MX-JrIGAC1CpJhlvTh2:-MX07Wc70SNHZtbeXzX0:b-mojbhg) ([raw file](https://github.com/robotlocomotion/drake/blob/ea9fa912c91fb2f2f380d119a8a73d3e6d24fb5e/bindings/pydrake/common/default_scalars_pybind.h#L70)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK My guess is that Jeremy used `Eigen::Dynamic` covered the concrete usages of `VectorX<double>` and `MatrixX<double>`. (Also, it's Python bindings, so fixed-size things only matter for size-checking; speed's already punted for small things haha.)

However, I don't see any harm in generalizing it further. Changed.
</blockquote></details>

Yes, AFAICT only thing we needed in pydrake is to know whether it is vector shape, e.g., `(7,)` or matrix shape, e.g., `(7,1)` and for that passing along cols as 1 or -1 alone was sufficient.  This new revision is probably better, though, by virtue of being more straightforward to read.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839#-:-MX3JmL68haeCdMuGrqr:b8qx53o)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/common/default_scalars_pybind.h, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14839#-MX3JMuTCx00LATpYiEu:-MX3JMuTCx00LATpYiEv:b-ilh9mn) ([raw file](https://github.com/robotlocomotion/drake/blob/3f43571723c8561032d923124b3c9745402bacc6/bindings/pydrake/common/default_scalars_pybind.h#L61)):*
> ```objc
> /** A no-op for builtin dtypes (e.g., T == double), but then switches to copying
> for custom dtypes (T ∈ {AutoDiffXd, Expression}).
> @param SomeBlock an Eigen::Block or Eigen::VectorBlock. */
> ```

minor: should be `@tparam`

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai (waiting on @hongkai-dai and @sherm1)

___
*[bindings/pydrake/common/default_scalars_pybind.h, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14839#-MX3JMuTCx00LATpYiEu:-MX3Ku_P8BCPr60CN0Bn:b-896fja) ([raw file](https://github.com/robotlocomotion/drake/blob/3f43571723c8561032d923124b3c9745402bacc6/bindings/pydrake/common/default_scalars_pybind.h#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should be `@tparam`
</blockquote></details>

Done!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14839)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Skipping slow builds!

**Pull request merged**
