### PR TITLE
Adds ability to place stalled SimpleCar vehicles at the end of a dragway.

### PR DESCRIPTION
**Pull request by liangfok**
By placing stalled vehicles at the end of a dragway, IDM-controlled railcars will stop prior to colliding with them. To run a simple demo:

```
$ bazel run //drake/automotive:demo -- --num_dragway_lanes=2 --num_idm_controlled_maliput_railcar=2 --with_stalled_cars
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5833)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR is blocked on #5756.

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@soonho-tri for platform review please.
Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5833#-:-KhhwrAsu_8iG9nxy_Bm:b-794vk7)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5833#-:-KhiQA2o-2bd_w4dd-FT:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5833#-:-KhjckVCJC6DmVS9-dSj:bnfp4nl)*

**Pull request merged**
