### PR TITLE
Expose piecewise quat slerp's orientation getters.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
Relates to #14561

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585)

### CODE REVIEW

**Review by siyuanfeng-tri — COMMENTED** [review]
+@ericcousineau-tri for feature. thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585#-:-MS14WyGE8iguiwlW3lG:b-s2vrk0)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585#-:-MS2kx7gEB17Eq-0epW8:b-v6scke)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @siyuanfeng-tri)

___
*[bindings/pydrake/trajectories_py.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lC-XArU7kkI456zg:-MS2lC-XArU7kkI456zh:b-vghi82) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/trajectories_py.cc#L239)):*
> ```cpp
>           doc.PiecewiseQuaternionSlerp.Append.doc_2args_time_angle_axis)
>       .def("orientation", &PiecewiseQuaternionSlerp<T>::orientation,
>           py::arg("time"), doc.PiecewiseQuaternionSlerp.orientation.doc)
> ```

nit Nuts... This argument is `t` in C++, not `time`:
https://github.com/RobotLocomotion/drake/blob/a3bab528ea421251075b33ed4d1f1c0314eff35f/common/trajectories/piecewise_quaternion.h#L86-L95

Can you reconcile one of the two? (maybe easiest to change `PiecewiseQuaternion` in the C++ code?)
___
*[bindings/pydrake/test/trajectories_test.py, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lJYhB1aYUQphNPjs:-MS2lJYiCfJag9YPQZCL:b-391owt) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/test/trajectories_test.py#L235)):*
> ```Python
>         )
>         np.testing.assert_equal(
>             np.array([1, 0, 0, 0]), pq.orientation(0).wxyz()
> ```

nit Can you test the kwargs for the getters here?

e.g. `pq.orientation(time=0)`, and other functions?

**Review by siyuanfeng-tri — COMMENTED** [review]
+@rpoyner-tri for platform review. thanks! 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585#-:-MS30aWCEiE0RQ6u9CIQ:b2t709r)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),rpoyner-tri(platform) (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[bindings/pydrake/trajectories_py.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lC-XArU7kkI456zg:-MS30UnP-75Yeco_-VYt:b9k5jwh) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/trajectories_py.cc#L239)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Nuts... This argument is `t` in C++, not `time`:
https://github.com/RobotLocomotion/drake/blob/a3bab528ea421251075b33ed4d1f1c0314eff35f/common/trajectories/piecewise_quaternion.h#L86-L95

Can you reconcile one of the two? (maybe easiest to change `PiecewiseQuaternion` in the C++ code?)
</blockquote></details>

changed. 
___
*[bindings/pydrake/test/trajectories_test.py, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lJYhB1aYUQphNPjs:-MS30TSD9kLzgmRJImVV:b-hjjwg) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/test/trajectories_test.py#L235)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you test the kwargs for the getters here?

e.g. `pq.orientation(time=0)`, and other functions?
</blockquote></details>

like these?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585)* status: LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

___
*[bindings/pydrake/trajectories_py.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lC-XArU7kkI456zg:-MS352bk9FjZI-qTq6bo:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/trajectories_py.cc#L239)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

changed. 
</blockquote></details>

OK Thanks!
___
*[bindings/pydrake/test/trajectories_test.py, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14585#-MS2lJYhB1aYUQphNPjs:-MS350qrCj1HSzO-lMUW:bfa7tck) ([raw file](https://github.com/robotlocomotion/drake/blob/41eb6a01dbe0104f9ef4162d7661fddf67c8f3af/bindings/pydrake/test/trajectories_test.py#L235)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

like these? 
</blockquote></details>

OK Yuhhh!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585#-:-MS356Ig191hAcWSQzKl:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14585#-:-MS3YDTo5A0lIkesm0xx:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
