### PR TITLE
[parsing] Introduce multibody parser manual test program

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #16229

For now, this is just a quick way to experiment with parser changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743#-:-Mxk-9Ow8iNOydzZP4gB:bnfp4nl)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[multibody/parsing/BUILD.bazel, line 331 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjzvcqEDAzRnkL97o2:-MxjzvcqEDAzRnkL97o3:b-hj9zvy) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/BUILD.bazel#L331)):*
> ```Starlark
> )
> 
> drake_cc_binary(
> ```

We should cover this program in CI.  Probably an easy way to do that would be `add_test_rule = True` (with `test_rule_args` pointing to a sample file to parse).
___
*[multibody/parsing/BUILD.bazel, line 337 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjydKb4Iy4KqTRpIdJ:-MxjydKb4Iy4KqTRpIdK:b-dqhcxk) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/BUILD.bazel#L337)):*
> ```Starlark
>     deps = [
>         ":parser",
>         "@gflags",
> ```

nit It'd be nice to deps on `"//common:add_text_logging_gflags"` here as well.  I enjoy being able to turn on tracing without rebuilding.
___
*[multibody/parsing/test/parser_manual_test.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-Mxjzp5t82f1SUNsFy2B:-Mxjzp5t82f1SUNsFy2C:bbyv2r8) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/test/parser_manual_test.cc#L5)):*
> ```cpp
> #include <gflags/gflags.h>
> 
> #include "drake/common/filesystem.h"
> ```

nit Unused include `filesystem`?
___
*[multibody/parsing/test/parser_manual_test.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjzFpGD6OK2Nmiwsiv:-MxjzFpH4Oz3FTpQQmSU:b1z11u1) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/test/parser_manual_test.cc#L31)):*
> ```cpp
>   Parser parser{&plant};
> 
>   std::cerr << "parsing...\n";
> ```

nit Could we use `drake::log()->info(...)` to encourage good habits?
___
*[multibody/parsing/test/parser_manual_test.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjzP6IAAkW1Y3OMIWa:-MxjzP6IAAkW1Y3OMIWb:blatvq1) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/test/parser_manual_test.cc#L33)):*
> ```cpp
>   std::cerr << "parsing...\n";
>   auto models = parser.AddAllModelsFromFile(argv[1]);
>   std::cout << "Parsed " << models.size() << " models.\n";
> ```

nit Is this going to cout because a test driver will scrape it?  For programmatic output, I'd much rather see us write a json output file (with a path given on the command line), for developer sanity.

Or if it's just for users, then `drake::log()` seems more apt?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743)* status: 5 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[multibody/parsing/BUILD.bazel, line 337 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjydKb4Iy4KqTRpIdJ:-MxkCQIC-uePtq7j9Ywk:b2nhoia) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/BUILD.bazel#L337)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It'd be nice to deps on `"//common:add_text_logging_gflags"` here as well.  I enjoy being able to turn on tracing without rebuilding.
</blockquote></details>

TIL

**Review by rpoyner-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743#-:-MxkFdAm7-Zf3mbSAHGe:bt1x5ma)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[multibody/parsing/BUILD.bazel, line 331 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxjzvcqEDAzRnkL97o2:-MxkFP_42Hxu9LKmu_oa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/50c85a94d6f7c85282084b095ab372b7a33ed98d/multibody/parsing/BUILD.bazel#L331)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We should cover this program in CI.  Probably an easy way to do that would be `add_test_rule = True` (with `test_rule_args` pointing to a sample file to parse).
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743#-:-MxkHrhPDXoRTY_amBOW:b-cxwtpw)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[multibody/parsing/test/parser_manual_test.cc, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16743#-MxkHGYqB7oq-276EACu:-MxkHGYqB7oq-276EACv:b-fkrzig) ([raw file](https://github.com/robotlocomotion/drake/blob/8e237ae41c53a87f4f4eacd5bba965c432d8eaa9/multibody/parsing/test/parser_manual_test.cc#L29)):*
> ```cpp
> 
>   drake::log()->info("parsing {}", argv[1]);
>   auto models = parser.AddAllModelsFromFile(argv[1]);
> ```

nit obscure auto.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16743)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),xuchenhan-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
