### PR TITLE
fix an initialized mem bug in pid_controller_test

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6832)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@liangfok for reviews. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6832#-:-KrMX7T-0NA995GhHsjY:b-qjv5u3)*

**Comment by siyuanfeng-tri** [comment]
@liangfok how do I start the memcheck builds? thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6832#-:-KrMXEqt3rse7k6Ia9ae:b-6te8wi)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please.
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-snopt please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-everything please.
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-valgrind-snopt please.

**Comment by liangfok** [comment]
:lgtm:

+@jwnimmer-tri for platform review please. Thanks.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/test/pid_controller_test.cc, line 223 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6832#-KrOollpbpSyOW-ygXJd:-KrOollpbpSyOW-ygXJe:bmjj7uz) ([raw file](https://github.com/robotlocomotion/drake/blob/f27795a89b30130b15476c48b607c6195ee546fb/drake/systems/controllers/test/pid_controller_test.cc#L223)):*
> ```cpp
>   VectorX<double> x_d(2 * num_controlled_q);
>   x_d.head(num_controlled_q) = q_d;
>   v_d.head(num_controlled_q) = v_d;
> ```

BTW (non blocking), should this have been the following?

```
x_d.tail(num_controlled_q) = v_d;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6832#-:-KrOp8HhL5Sr9aeWZ-zu:b23sdow)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6832#-:-KrQKRHyZVilyUmPUl50:bnfp4nl)*

**Pull request merged**
