### PR TITLE
pydrake: Add `pydrake_pybind`, with beginning documentation for conventions.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This provides an alternative to #7818 (that I prefer much more), and provides a start to #7819.

\cc @jwnimmer-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7829)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review, please.
+@sammy-tri for platform review, please.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-:-L3V1aRMRQeiF9GQBn45:b-q29v7d)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything, please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything, please.

**Comment by EricCousineau-TRI** [comment]
Getting a local error with `--compiler=gcc-5`:
ImportError: ${bazel_cache}/execroot/drake/bazel-out/gcc-5-linux-dbg/bin/bindings/pydra
ke/forward_diff_test.runfiles/drake/bindings/pydrake/../../_solib_k8/_U_S_Sbindings_Spydrake_C_Ucommon_Upy.so___Utools_Sinstall_Slibdrake/libdrake.so: undefined symbol: _ZN17btConvexHullSha
peC1EPKdii

Not sure if this is related to changes that I have made, or it's elsewhere. Will try to figure it out.

**Comment by soonho-tri** [comment]
First pass completed.

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YgibsjPUe9QiylMdD:-L3YgibsjPUe9QiylMdE:btk529n) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/BUILD.bazel#L40)):*
> ```Python
>     name = "pydrake_pybind",
>     hdrs = ["pydrake_pybind.h"],
>     # NOTE: We must violate IWYU and not list "autodiff" in "deps" here because
> ```

`pydrake_pybind.h` doesn't include autodiff-related headers. Do you mean we should violate IWYU even if it does include in the future?

---

*[bindings/pydrake/pydrake_pybind.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YdRR-nh0tb3F7yqN3:-L3YdRR-nh0tb3F7yqN4:b-e491n) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L5)):*
> ```objc
> #include <pybind11/pybind11.h>
> 
> // N.B. Avoid including other heads, such as `pybind11/eigen.sh` or
> ```

BTW, heads` -> `headers`?

---

*[bindings/pydrake/pydrake_pybind.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YdpisLRJ3KU_GxGSR:-L3YdpisLRJ3KU_GxGSS:bf2zmww) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L41)):*
> ```objc
> Given that `libdrake.so` relies on static linking for components,
> any common headers should be robust against ODR violations. This can
> be normally be achieved by using header-only libraries.
> ```

BTW,  `be normally be achieved` -> `be normally achieved`

---

*[bindings/pydrake/pydrake_pybind.h, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YedlVflM40Rl6pc1x:-L3YedlVflM40Rl6pc1y:b-panx9y) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L92)):*
> ```objc
> 
> If you would like to interactively debug binding code (using IPython for
> general Python behavior, or GDB for C++ behavior), debug C++ behavior from a Python binary, while using Bazel, you may expose Bazel's development
> ```

BTW, consider reflowing this line.

---

*[bindings/pydrake/symbolic_types_pybind.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YhCfcd_HZbklrbxgp:-L3YhCfcd_HZbklrbxgq:b-82nd4h) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/symbolic_types_pybind.h#L8)):*
> ```objc
> #include "drake/bindings/pydrake/pydrake_pybind.h"
> #include "drake/common/symbolic.h"
> ```

No need to wrap the followings with `namespace drake::pydrake`?

---

*[bindings/pydrake/systems/test/lifetime_test_util_py.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3Yhf9Ctaqh6C3uOE70:-L3Yhf9Ctaqh6C3uOE71:b-bmyo2m) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/systems/test/lifetime_test_util_py.cc#L12)):*
> ```cpp
> namespace drake {
> 
> using drake::systems::BasicVector;
> ```

BTW, no need `drake::` prefixes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-:-L3Yhugp6Qg1LiOz0Zso:b-nxgybn)*

**Comment by EricCousineau-TRI** [comment]
Review status: 15 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[bindings/pydrake/BUILD.bazel, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YgibsjPUe9QiylMdD:-L3_n1MN4v9I1IFWZiq9:b-54jcoe) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/BUILD.bazel#L40)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`pydrake_pybind.h` doesn't include autodiff-related headers. Do you mean we should violate IWYU even if it does include in the future?
</blockquote></details>

Done.
Sorry, had moved a comment and did not change it afterwards. Thanks for catching it!

---

*[bindings/pydrake/pydrake_pybind.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YdRR-nh0tb3F7yqN3:-L3_n4k1J4CztPep0-mN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L5)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, heads` -> `headers`?
</blockquote></details>

Done.

---

*[bindings/pydrake/pydrake_pybind.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YdpisLRJ3KU_GxGSR:-L3_n5V6NqLc_Rf3MYDo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW,  `be normally be achieved` -> `be normally achieved`
</blockquote></details>

Done.

---

*[bindings/pydrake/pydrake_pybind.h, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YedlVflM40Rl6pc1x:-L3_n6UjKxhpK3LI2sjG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/pydrake_pybind.h#L92)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, consider reflowing this line.
</blockquote></details>

Done.

---

*[bindings/pydrake/symbolic_types_pybind.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3YhCfcd_HZbklrbxgp:-L3_n7nncJepA6LPY2MS:b-e5taya) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/symbolic_types_pybind.h#L8)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

No need to wrap the followings with `namespace drake::pydrake`?
</blockquote></details>

Done. Added explanation.

---

*[bindings/pydrake/systems/test/lifetime_test_util_py.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-L3Yhf9Ctaqh6C3uOE70:-L3_nLytTI6QSDwxwgxV:b-62vvpf) ([raw file](https://github.com/robotlocomotion/drake/blob/e9b8c10ce827040c25cd5e56d8c48d654fb15f05/bindings/pydrake/systems/test/lifetime_test_util_py.cc#L12)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, no need `drake::` prefixes.
</blockquote></details>

Done. (In `test_util_py.cc`, since it was renamed on `master`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-:-L3a7KpUtWV39cfYt1f3:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
-@sammy-tri
+@ggould-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-:-L3e8-8evspLuz_4eeAt:btbrst4)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything, please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything, please.

**Comment by ggould-tri** [comment]
:lgtm:; I really like the readability improvement here.

---

Reviewed 12 of 24 files at r1, 8 of 11 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7829#-:-L3hmI41ZaYnHZheL31y:bmpog2g)*

**Pull request merged**
