### PR TITLE
Make multibody/plant clang-format compliant

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 68 of 68 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) 
+@amcastro-tri for feature review please
+@jwnimmer-tri for platform review please.

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-NfrC2e1DS9thVdC7-Sg:bjj8quh)* status: LGTM missing from assignees amcastro-tri,jwnimmer-tri(platform)

___
*[`multibody/plant/contact_model_doxygen.h` line 4 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrMoPy8jAIajUcmsA5:-NfrMoPy8jAIajUcmsA6:b-rtkzit) ([raw file](https://github.com/RobotLocomotion/drake/blob/d1aa712744bc2af5610f976a5de1580a05aee993/multibody/plant/contact_model_doxygen.h#L4)):*
> ```objc
>  Doxygen-only documentation for @ref drake_contacts.  */
> 
> // clang-format off (to preserve link to images)
> ```

FYI, I turned off clang-format for this file entirely
___
*[`multibody/plant/multibody_plant.h` line 533 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrN1BeDdvPdyw_MlUK:-NfrN1BeDdvPdyw_MlUL:byur5y1) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ffdade9e37f95c0356a876656821e8b97f937c5/multibody/plant/multibody_plant.h#L533)):*
> ```objc
> |material|point_contact_stiffness|no²|T| Penalty method stiffness.|
> |material|hunt_crossley_dissipation |no²⁴|T| Penalty method dissipation.|
> |material|relaxation_time|yes³⁴|T|Linear Kelvin–Voigt model parameter.|
> ```

FYI, I made wording changes here to fit within 80 characters.

**Comment by jwnimmer-tri** [comment]
This is over the 1500 LOC [hard limit](https://drake.mit.edu/developers.html#review-process).  Could you split it into 2 (or 3?) pieces, so that reviewers can keep their eyeballs in their sockets?  One obvious split would be test vs non-test.  It's OK to have the first PR just format files, without adding linter enforcement.

**Review by xuchenhan-tri — COMMENTED** [review]
Ok, I changed the PR to only include non-test files.

> Reviewed 44 of 44 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-Nfrb_jy0dhBQMrfT3bF:b-4rwwe1)* status: LGTM missing from assignees jwnimmer-tri(platform),amcastro-tri

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 23 of 68 files at r1, 1 of 4 files at r3, 1 of 1 files at r5, 44 of 44 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-Nfrceeg2lFcewhUtgvv:bcpz082)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri

___
*[`multibody/plant/tamsi_solver.cc` line 565 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrcW8K4tE-vd6VpoIE:-NfrcW8K4tE-vd6VpoIF:bmpfpsy) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/tamsi_solver.cc#L565)):*
> ```cpp
>   // generalized velocities) as Gt = −diag(dft_dvt) Jt and use the fact that
>   // diag(dft_dvt) is block diagonal.
>   MatrixX<T> Gt(nf, nv);             // −∇ᵥfₜ
> ```

BTW Are you happy with this new indentation?  It seems less than ideal.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri

___
*[`multibody/plant/tamsi_solver.cc` line 565 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrcW8K4tE-vd6VpoIE:-NfrejY11IeNu6ZyIEx6:b1rur4t) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/tamsi_solver.cc#L565)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Are you happy with this new indentation?  It seems less than ideal.
</blockquote></details>

It's not the best but it doesn't bother me enough to special case it.

**Review by amcastro-tri — COMMENTED** [review]
wow, I'm impressed by the large amount of changes.
In particular, I tend to clang format with my editor every change I make (or I try).
I tried my editors clan formatter on top of master and I realize it produces these same changes. Did we recently change a config file or simply these mistakes accumulated over time?

> Reviewed 23 of 68 files at r1, 1 of 4 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-Nfv4TlK--qdvu3k7TIv:bhjai3d)* status: 6 unresolved discussions, LGTM missing from assignee amcastro-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5QuH0BYbLBATiPqq:-Nfv5QuI3UREFalNtimX:b-g58h48) (no related file):*
Thanks for the cleanup, @xuchenhan-tri!

I mostly have questions on a few places about some of the decisions the formatter takes. Not sure if we like them or something better could be done. So I just pointed them out.

The only thing I feel strong about is the one table in the plant's docs. IMO the formatting should read nice in ASCII format.

___
___
*[`multibody/plant/contact_results.cc` line 77 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv3LaY5P3CjsyGQrKq:-Nfv3LaY5P3CjsyGQrKr:b-ey90e2) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/contact_results.cc#L77)):*
> ```cpp
> 
> template <typename T>
> const PointPairContactInfo<T>& ContactResults<T>::point_pair_contact_info(
> ```

IMO this line breaks look weird, I much rather prefer the previous version. 
Is this clang format's preference?n
___
*[`multibody/plant/multibody_plant.h` line 533 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrN1BeDdvPdyw_MlUK:-Nfv1Z8H1dNrKu5R1ngU:b-8edwkc) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ffdade9e37f95c0356a876656821e8b97f937c5/multibody/plant/multibody_plant.h#L533)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, I made wording changes here to fit within 80 characters.
</blockquote></details>

IMO this degraded over the years. You can tell that as rows were added, we didn't pay attention to the orginal nicely indendented table.
My preference is to allow this to go beyond 80 characters and to align this columns nicely so that they read well even for those of us who only browse docs within the source itself.
___
*[`multibody/plant/multibody_plant.h` line 1215 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv24Qc0UcXvTlkOxY8:-Nfv24Qc0UcXvTlkOxY9:bvesl1a) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.h#L1215)):*
> ```objc
>     return result;
>   }
>   // clang-format on
> ```

the comment right before to turn clang formatting off says we do it for the image link only. However we turn it on much later. Either update the comment or turn on sooner right after the image link?
___
*[`multibody/plant/multibody_plant.cc` line 56 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2X1T1ZREmXAkGzNS:-Nfv2X1U58aEXdPJzuTI:b-w8c4dw) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L56)):*
> ```cpp
> using geometry::SceneGraph;
> using geometry::SourceId;
> using geometry::render::RenderLabel;
> ```

interesting. So clang format gives prefernece to upper cased characters? is that why the flip?
___
*[`multibody/plant/multibody_plant.cc` line 3518 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2uB90NHl919wTqZV:-Nfv2uB90NHl919wTqZW:bpme7js) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L3518)):*
> ```cpp
>     throw std::logic_error("Pre-finalize calls to '" +
>                            std::string(source_method) +
>                            "()' are "
> ```

IMO this reads strange. I'd probably try to break into a long string followed by a short string, rather than the other way around.
___
*[`multibody/plant/tamsi_solver.cc` line 295 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv50f3-S5FMtDp1sZ2:-Nfv50f4-k4KzJPjIjft:b-g3wbam) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/tamsi_solver.cc#L295)):*
> ```cpp
>     EigenPtr<const VectorX<T>> dissipation, EigenPtr<const VectorX<T>> mu) {
>   DRAKE_DEMAND(M && Jn && Jt && p_star && fn0 && stiffness && dissipation &&
>                mu);
> ```

Personally I'd prefer something like:
```c++
DRAKE\_DEMAND(
  M && Jn && Jt && p\_star && fn0 && stiffness && dissipation && mu);
```

but yeah, that's what my editor says also. Is there some config we could change?
___
*[`multibody/plant/test_utilities/rigid_body_on_compliant_ground.h` line 114 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5HYU8ndrzS64eR_E:-Nfv5HYU8ndrzS64eR_F:b-mt73li) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/test_utilities/rigid_body_on_compliant_ground.h#L114)):*
> ```objc
>     geometry::ProximityProperties body_props;
>     geometry::AddContactMaterial(0.0, 1e40, CoulombFriction<double>(kMu_, kMu_),
>                                  &body_props);
> ```

this is another instance where IMO the previous version looks better. 
Do we really like this? can we edit some config for these special cases?

**Review by jwnimmer-tri — COMMENTED** [review]
> Did we recently change a config file or simply these mistakes accumulated over time?

Not everyone has their editor set up like yours, and historically we have not enforced auto-formatting in CI.  Xuchen is working on enabling the auto-formatting linter for `multibody/plant` -- in a subsequent PR, he will remove the `enable_clang_format = False` from `multibody/plant/BUILD.bazel` and CI will keep us honest by enforcing formatting.

> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-NfvGaBy3eNAIZeyfk_s:b6wbarj)* status: 5 unresolved discussions, LGTM missing from assignee amcastro-tri

___
*[`multibody/plant/contact_results.cc` line 77 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv3LaY5P3CjsyGQrKq:-NfvGlP268kPjZCr64Uk:b-31nwx0) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/contact_results.cc#L77)):*
> Is this clang format's preference?

Yes.

Clang-format gives a stronger preference to fitting the return type on the same line as the function name (and spilling the arguments), instead of fitting the arguments on the same line as the function name (and spilling the return type) -- usually there are a lot more arguments and it works better.

If you want the return type on its own line, we could add a comment like `// BR` after the return type to force the class name onto its own line:

```c++
template <typename T>
const PointPairContactInfo<T>&  // BR
ContactResults<T>::point_pair_contact_info(int i) const {
```

Would you prefer that here?
___
*[`multibody/plant/multibody_plant.cc` line 56 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2X1T1ZREmXAkGzNS:-NfvHLVj37wHq3fj3wZS:b50va80) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L56)):*
> So clang format gives prefernece to upper cased characters?

Since it's all just boilerplate, I don't think we need to try to discern what ordering clang-format uses to sort this.  We can just happily lean on whatever it does, without bothering ourselves with it ever again.
___
*[`multibody/plant/multibody_plant.cc` line 3518 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2uB90NHl919wTqZV:-NfvHZ-UBrEphfhhvbGx:bual6wm) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L3518)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

IMO this reads strange. I'd probably try to break into a long string followed by a short string, rather than the other way around.
</blockquote></details>

The question is do you want this clang-format PR to go beyond whitespace changes, into actual code changes?  The real fix here is to use fmt::format instead of string::operator+.  Should that change be part of this PR, or saved for later?
___
*[`multibody/plant/tamsi_solver.cc` line 295 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv50f3-S5FMtDp1sZ2:-NfvI35s6Y9CPoJTTQ-0:bsgbg03) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/tamsi_solver.cc#L295)):*
> Is there some config we could change?

Possibly there's one I haven't seen yet, but probably not.

If we want the code to be more readable, we should just write better code in the first place:

```c++
DRAKE_DEMAND(M != nullptr);
DRAKE_DEMAND(Jn != nullptr);
DRAKE_DEMAND(Jt != nullptr);
DRAKE_DEMAND(p_star != nullptr);
DRAKE_DEMAND(fn0 != nullptr);
DRAKE_DEMAND(stiffness != nullptr);
DRAKE_DEMAND(dissipation != nullptr);
DRAKE_DEMAND(mu != nullptr);
```

Using implicit boolean conversion for null checks is needlessly obscure, and cramming multiple checks onto one line fails communicate _which_ one failed in case the assertion ever trips.

(I don't think this PR should try to adjust the assertions; the snippet above is for future reference.)
___
*[`multibody/plant/test_utilities/rigid_body_on_compliant_ground.h` line 114 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5HYU8ndrzS64eR_E:-NfvJRq_AT3rbMoJMyCC:b-we1444) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/test_utilities/rigid_body_on_compliant_ground.h#L114)):*
> Can we edit some config for these special cases?

There are _some_ config knobs that affect this.  Here's your menu of choices:

https://releases.llvm.org/12.0.0/tools/clang/docs/ClangFormatStyleOptions.html

The options are set in our `drake/.clang-format` config file.

If you find a configuration that you like better, you are invited to propose the change in a pull request.  My experience to date is that this is the best setting on average across the whole codebase, but I'd love it if you found a better one.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: 5 unresolved discussions, LGTM missing from assignee amcastro-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5QuH0BYbLBATiPqq:-NfvTeTCCNInArXF9A3a:b-fe8n64) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Thanks for the cleanup, @xuchenhan-tri!

I mostly have questions on a few places about some of the decisions the formatter takes. Not sure if we like them or something better could be done. So I just pointed them out.

The only thing I feel strong about is the one table in the plant's docs. IMO the formatting should read nice in ASCII format.
</blockquote></details>

Feel free to push your preferred format to this PR. I'm not picky about formatting choices as long as when I run clang-format, it doesn't introduce unnecessary diffs as in https://github.com/RobotLocomotion/drake/pull/20297.

___
___
*[`multibody/plant/contact_results.cc` line 77 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv3LaY5P3CjsyGQrKq:-NfvTXZE7jaCQzKWvmQM:b-hblend) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/contact_results.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Is this clang format's preference?

Yes.

Clang-format gives a stronger preference to fitting the return type on the same line as the function name (and spilling the arguments), instead of fitting the arguments on the same line as the function name (and spilling the return type) -- usually there are a lot more arguments and it works better.

If you want the return type on its own line, we could add a comment like `// BR` after the return type to force the class name onto its own line:

```c++
template <typename T>
const PointPairContactInfo<T>&  // BR
ContactResults<T>::point_pair_contact_info(int i) const {
```

Would you prefer that here?
</blockquote></details>

Please feel free to push the format you like to see to this PR.
___
*[`multibody/plant/multibody_plant.h` line 533 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrN1BeDdvPdyw_MlUK:-NfvUIzV-0yETlMSyCWB:b3sy1lg) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ffdade9e37f95c0356a876656821e8b97f937c5/multibody/plant/multibody_plant.h#L533)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

IMO this degraded over the years. You can tell that as rows were added, we didn't pay attention to the orginal nicely indendented table.
My preference is to allow this to go beyond 80 characters and to align this columns nicely so that they read well even for those of us who only browse docs within the source itself.
</blockquote></details>

I haven't found a way to allow doxygen comment to go beyond 80 characters without breaking the rendering of the table. If you can figure out a way, please push the change to the PR. Documenting your solution [here](https://drakedevelopers.slack.com/archives/C2ETTRXT7/p1696357629904509) is also welcome. I know that other people have run into this issue as well.
___
*[`multibody/plant/multibody_plant.h` line 1215 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv24Qc0UcXvTlkOxY8:-NfvUsxA1Eves82i9ZbF:b-hf4sgq) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.h#L1215)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

the comment right before to turn clang formatting off says we do it for the image link only. However we turn it on much later. Either update the comment or turn on sooner right after the image link?
</blockquote></details>

Similar to above, I haven't found a way to opt out of clang-format within a doxygen comment without breaking rendering.
___
*[`multibody/plant/multibody_plant.cc` line 3518 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2uB90NHl919wTqZV:-NfvT2nREUN_Xt5jAQIc:bkxaun8) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L3518)):*
> Should that change be part of this PR, or saved for later?

I'm fine either way. Feel free to push the format you want to see to this PR.

**Review by xuchenhan-tri — COMMENTED** [review]
+(priority: low) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-:-NfvVUZs5XLWtKVTRkdm:b-nzc0ap)* status: 5 unresolved discussions, LGTM missing from assignee amcastro-tri

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5QuH0BYbLBATiPqq:-Ng0k2iGAfz5UdSzpIc1:by2mrq7) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Feel free to push your preferred format to this PR. I'm not picky about formatting choices as long as when I run clang-format, it doesn't introduce unnecessary diffs as in https://github.com/RobotLocomotion/drake/pull/20297.
</blockquote></details>

All rigth, I just realize the spirit of this PR is "run clang-format and let it do its thing". A few places might look odd, but the big gain here is that now the entire code base is consistently checked for formatting. So, a few outliers is definitely worth the price.

:lgtm: 

___
___
*[`multibody/plant/contact_results.cc` line 77 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv3LaY5P3CjsyGQrKq:-Ng0fWec3dgWFhz5FW_q:b-aopajo) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/contact_results.cc#L77)):*
> Would you prefer that here?

Not really. I pointed it out in case it was a bug in one of our config files (if any).
If this is the desired behavior, I'm ok with it (it'd seem an unnecessary use of `// BR ` in this case)
___
*[`multibody/plant/multibody_plant.h` line 533 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-NfrN1BeDdvPdyw_MlUK:-Ng0g4oc-y2UJh12igVT:b-pxol21) ([raw file](https://github.com/RobotLocomotion/drake/blob/0ffdade9e37f95c0356a876656821e8b97f937c5/multibody/plant/multibody_plant.h#L533)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I haven't found a way to allow doxygen comment to go beyond 80 characters without breaking the rendering of the table. If you can figure out a way, please push the change to the PR. Documenting your solution [here](https://drakedevelopers.slack.com/archives/C2ETTRXT7/p1696357629904509) is also welcome. I know that other people have run into this issue as well.
</blockquote></details>

oh.... I didn't realize clang format and Doxygen comments didn't play well.
A quick search didn't reveal anything that'd seem to fix the problem. Some people talk about `CommentPragmas`, for instance [here](https://github.com/dealii/dealii/issues/6752).
I guess this it the best we can do until we find a solution.
___
*[`multibody/plant/multibody_plant.h` line 1215 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv24Qc0UcXvTlkOxY8:-Ng0jHsD4cDUH9ovEaQm:b32wtd) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.h#L1215)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Similar to above, I haven't found a way to opt out of clang-format within a doxygen comment without breaking rendering.
</blockquote></details>

ok
___
*[`multibody/plant/multibody_plant.cc` line 56 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv2X1T1ZREmXAkGzNS:-Ng0jMZn-M3vJ9Vt6KnD:b-vpi46b) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/multibody_plant.cc#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> So clang format gives prefernece to upper cased characters?

Since it's all just boilerplate, I don't think we need to try to discern what ordering clang-format uses to sort this.  We can just happily lean on whatever it does, without bothering ourselves with it ever again.
</blockquote></details>

fair, I still found it interesting :-) 
___
*[`multibody/plant/tamsi_solver.cc` line 295 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv50f3-S5FMtDp1sZ2:-Ng0jdFs70b76XRKJqlC:botgu0w) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/tamsi_solver.cc#L295)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Is there some config we could change?

Possibly there's one I haven't seen yet, but probably not.

If we want the code to be more readable, we should just write better code in the first place:

```c++
DRAKE_DEMAND(M != nullptr);
DRAKE_DEMAND(Jn != nullptr);
DRAKE_DEMAND(Jt != nullptr);
DRAKE_DEMAND(p_star != nullptr);
DRAKE_DEMAND(fn0 != nullptr);
DRAKE_DEMAND(stiffness != nullptr);
DRAKE_DEMAND(dissipation != nullptr);
DRAKE_DEMAND(mu != nullptr);
```

Using implicit boolean conversion for null checks is needlessly obscure, and cramming multiple checks onto one line fails communicate _which_ one failed in case the assertion ever trips.

(I don't think this PR should try to adjust the assertions; the snippet above is for future reference.)
</blockquote></details>

ok, yes, I agree with this observation. Thanks.
___
*[`multibody/plant/test_utilities/rigid_body_on_compliant_ground.h` line 114 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20306#-Nfv5HYU8ndrzS64eR_E:-Ng0jo-ED8kC0mqqqLIg:b-mebrx7) ([raw file](https://github.com/RobotLocomotion/drake/blob/5efd3affde8a829397181e9d98c60fc278f83754/multibody/plant/test_utilities/rigid_body_on_compliant_ground.h#L114)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> Can we edit some config for these special cases?

There are _some_ config knobs that affect this.  Here's your menu of choices:

https://releases.llvm.org/12.0.0/tools/clang/docs/ClangFormatStyleOptions.html

The options are set in our `drake/.clang-format` config file.

If you find a configuration that you like better, you are invited to propose the change in a pull request.  My experience to date is that this is the best setting on average across the whole codebase, but I'd love it if you found a better one.
</blockquote></details>

sounds good. I have no experience with it. But I mentioned the places that seemed odd to me in case you guys were still adjusting these knobs.

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @amcastro-tri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20306)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Pull request merged**
