### PR TITLE
Adds support for a custom simulation termination condition.

### LINKED ISSUE #2192: Drake's simulate() Method Needs to Support Externally Specified Termination Condition
Currently, the termination condition is when the simulation time `t` exceeds the final time `tf`. The relevant source code is in [drake/systems/Simulation.h#L118](https://github.com/RobotLocomotion/drake/blob/b406d8403ea3f835e7931b275c2eeb974ef77e34/drake/systems/Simulation.h#L118) and is replicated below:

```C++
while (t < tf) {
  //...
}
```

This is not sufficiently flexible when integrating Drake within a larger framework like ROS since ROS is multithreaded and [installs its own SIGINT handler](http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown#Shutting_Down). When running Drake with ROS, typing `ctrl+c` will no longer shutdown the simulation. We need to design a mechanism for the above `while` loop to effectively implement the following logic:

```C++
while (t < tf && ros::ok()) {
  // ...
}
```

The ability to achieve the above logic will return the normal ability to terminate the simulation when `ctrl+c` is typed.

Without this fix, the only way to shut down Drake + ROS is to type `ctr+\`, which is potentially dangerous since it does not shut things down cleanly (it may result in zombie processes that you will then need to pick off one-by-one using something like `kill -9`).

### PR DESCRIPTION
**Pull request by liangfok**
Closes #2192.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2660)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review
+@sherm1 for platform review

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLIQ3x76yICCN9uGfi2:-2113636303)*

**Comment by sherm1** [comment]
There is a lint fail:
```
16:10:34 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/test/simulation_test.cc:42: warning: At least two spaces is best between code and comments  [whitespace/comments] [2]
16:10:34 /home/ubuntu/workspace/experimental/ae7636ba/drake/systems/test/simulation_test.cc:43: warning: At least two spaces is best between code and comments  [whitespace/comments] [2]
```

**Comment by liangfok** [comment]
Fixed. Thanks for the note.

**Comment by sherm1** [comment]
Platform review pass done. A few minor comments.

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/Simulation.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLIdDqO8leEJ7FWpqHi:-KLIdDqO8leEJ7FWpqHj:-525761108) ([raw file](https://github.com/robotlocomotion/drake/blob/96434f5973f05822a92f16ee3cfea3466873eb51/drake/systems/Simulation.h#L37)):*
> ```objc
>    * Enables a custom simulation termination condition. This function is called
>    * each cycle of the simulation loop. If the function returns true, the
>    * simulation is terminated.
> ```

Add: "The default for this is a function that always returns `false`."

---

*[drake/systems/test/CMakeLists.txt, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLIf6iYsaK0rChAV8oz:-KLIf6iZstG7t6h5ODqm:1772333638) ([raw file](https://github.com/robotlocomotion/drake/blob/96434f5973f05822a92f16ee3cfea3466873eb51/drake/systems/test/CMakeLists.txt#L21)):*
> ```CMake
> add_test(NAME n_ary_system_test COMMAND n_ary_system_test)
> 
> add_executable(simulation_test simulation_test.cc)
> ```

Better to call this `termination_test` or something like that; `simulation_test` seems too broad and we might want that name for a more fundamental test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLIfL62xXU_d0Z9eMc4:1368600485)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. This is ready for another round of review.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/Simulation.h, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLIdDqO8leEJ7FWpqHi:-KLIkk71pkIqQz6wVLLI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/96434f5973f05822a92f16ee3cfea3466873eb51/drake/systems/Simulation.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Add: "The default for this is a function that always returns `false`."
</details>
Done.

---

*[drake/systems/test/CMakeLists.txt, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLIf6iYsaK0rChAV8oz:-KLIkxYE9TTfJZd3qQ0p:-80995486) ([raw file](https://github.com/robotlocomotion/drake/blob/96434f5973f05822a92f16ee3cfea3466873eb51/drake/systems/test/CMakeLists.txt#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Better to call this `termination_test` or something like that; `simulation_test` seems too broad and we might want that name for a more fundamental test.
</details>
Done. I renamed the binary to be `simulation_termination_test`. I also updated the category of the individual unit tests to be "SimulationTerminationTest".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLIn_l5NVqGJbIo99_g:-1280828387)*

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLIzrLT65-yw95LKjjj:-1446635318)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[drake/systems/test/simulation_termination_test.cc, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJAJYucEq9I-Hcqr4d:-KLJAJYucEq9I-Hcqr4e:-298002906) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L19)):*
> ```cpp
> using Drake::EigenVector;
> 
> class SimulationTerminationTest : public ::testing::Test {
> ```

META All four member fields of this class must end with an underscore.

---

*[drake/systems/test/simulation_termination_test.cc, line 42 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJAjmX2dL6ZifpkGlk:-KLJAjmX2dL6ZifpkGll:-1957506819) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L42)):*
> ```cpp
>   Drake::SimulationOptions options;
> 
>   double ti;  // The initial simulation time.
> ```

META These two POD member fields are left uninitialized by the constructor.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJB33St8464PONkHRK:254986250) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
> ```cpp
> TEST_F(SimulationTerminationTest, TerminationConditionTrue) {
>   options.should_stop = []() { return true; };
>   EXPECT_NO_THROW(Drake::simulate(*sys_ptr, ti, tf, xi, options));
> ```

Missing any correctness check that the simulation loop actually exited early.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJBuQF7FeqjxLRa3Dc:-KLJBuQGB_5oCqScibXO:864313613) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L63)):*
> ```cpp
> // Tests whether Drake::simulate() can be called using simulation options
> // customized with a different termination function. This function throws an
> // exception, which should be caught.
> ```

I am not convinced that this test is (1) useful, or (2) a design that we want to support.  I am not sure in what case an exception would occur from a `should_stop` functor, that has any chance of being caught, or why we would want to catch it in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJNLF0AMo0Ybw7TeC8:821741106) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing any correctness check that the simulation loop actually exited early.
</details>
I noticed this also and didn't say anything because I couldn't figure out a way to get it to terminate early in a reliable way! Now I'm thinking it might be worth passing the current time into the function signature. That could be somewhat useful and would make it possible to test that the function works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJOLf_sELdQCVIMQHE:1013611153) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I noticed this also and didn't say anything because I couldn't figure out a way to get it to terminate early in a reliable way! Now I'm thinking it might be worth passing the current time into the function signature. That could be somewhat useful and would make it possible to test that the function works.
</details>
That would be fine.

A few other options:
- The unit test Functor has mutable state, and returns true only after, e.g., 5 invocations.
- The unit test Functor returns true only after the Output of the System Under Test crosses some threshold.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJRuLL4sF7A-0RhA3t:568144638) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> That would be fine.
> 
> A few other options:
> - The unit test Functor has mutable state, and returns true only after, e.g., 5 invocations.
> - The unit test Functor returns true only after the Output of the System Under Test crosses some threshold.
</details>
These are great ideas for testing if we don't add a time argument. I prefer adding the argument now, but not strongly. Any objections to that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJU23eTjFHvUuniPFm:-1720722031) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> These are great ideas for testing if we don't add a time argument. I prefer adding the argument now, but not strongly. Any objections to that?
</details>
I have no opinion.  System1's `simulate()` is something I want to cease using as fast as possible, so really care very little what its API is there for the next few weeks that it's still alive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJAJYucEq9I-Hcqr4d:-KLJ_4WbWwwR_3YGtkKX:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> META All four member fields of this class must end with an underscore.
</details>
Done.

---

*[drake/systems/test/simulation_termination_test.cc, line 42 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJAjmX2dL6ZifpkGlk:-KLJajqjnGUbCIpaWvny:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> META These two POD member fields are left uninitialized by the constructor.
</details>
Done.

---

*[drake/systems/test/simulation_termination_test.cc, line 58 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJB33St8464PONkHRJ:-KLJb-ez1sG_leStaTmO:53771506) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I have no opinion.  System1's `simulate()` is something I want to cease using as fast as possible, so really care very little what its API is there for the next few weeks that it's still alive.
</details>
I added the current system time as an input parameter to the functor. I also modified `simulate()`'s API to return the final simulation time so it can be checked.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJBuQF7FeqjxLRa3Dc:-KLJkYHClqrIh4PGRAFs:1640714767) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am not convinced that this test is (1) useful, or (2) a design that we want to support.  I am not sure in what case an exception would occur from a `should_stop` functor, that has any chance of being caught, or why we would want to catch it in the first place.
</details>
Coincidentally, I included this unit test just to ensure that the termination function was being called and having an effect.

Since (I believe) there's no way to prevent someone from throwing an exception within the function, isn't it best practice to include unit test coverage for such a scenario?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLL_3Zw-8lrqO2DmjCG:-84625242)*

**Comment by jwnimmer-tri** [comment]
Feature :lgtm:.

---

Reviewed 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJBuQF7FeqjxLRa3Dc:-KLLvIhTH0bnUAlHUA3r:142072137) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L63)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Coincidentally, I included this unit test just to ensure that the termination function was being called and having an effect.
> 
> Since (I believe) there's no way to prevent someone from throwing an exception within the function, isn't it best practice to include unit test coverage for such a scenario?
</details>
I am not sure what realistically-plausible defect we would expect it to uncover.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLLvn3dKYHGU3T_XdQX:-194594509)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLMYOCo7gsOvf7B9V-G:-KLMYOCpKuPiqauCt81g:1509355724) ([raw file](https://github.com/robotlocomotion/drake/blob/6e0523ec4914d8fd72c7695f100a1bbe726bfb36/drake/systems/test/simulation_termination_test.cc#L63)):*
> ```cpp
>   };
>   EXPECT_GE(Drake::simulate(*sys_ptr_, ti_, tf_, xi_, options_),
>     termination_time);
> ```

This test would succeed even if the termination function didn't work at all. You should check to see that it terminated early -- maybe `termination_time <= final_time <= termination_time+0.1`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLMZPSUXejQjrPaXih-:1417088721)*

**Comment by sherm1** [comment]
One test needs modifying and one pending comment from @jwnimmer-tri.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLMZ_9_19jJIhXE78JL:31819098)*

**Comment by liangfok** [comment]
Ready for another round of review. 

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLJBuQF7FeqjxLRa3Dc:-KLMZZSbP9gdoN22GWnr:844108307) ([raw file](https://github.com/robotlocomotion/drake/blob/15698e6554518e3ea15b96900df8ec205479a5d3/drake/systems/test/simulation_termination_test.cc#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am not sure what realistically-plausible defect we would expect it to uncover.
</details>
Now that we've modified simulate(...) to return the final simulation time, I suppose there's no longer any question anymore whether the termination function makes a difference. I shall thus remove this unit test.

---

*[drake/systems/test/simulation_termination_test.cc, line 63 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-KLMYOCo7gsOvf7B9V-G:-KLMbvE0Yfzd22TtOLA-:-1622819128) ([raw file](https://github.com/robotlocomotion/drake/blob/6e0523ec4914d8fd72c7695f100a1bbe726bfb36/drake/systems/test/simulation_termination_test.cc#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This test would succeed even if the termination function didn't work at all. You should check to see that it terminated early -- maybe `termination_time <= final_time <= termination_time+0.1`?
</details>
Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLMbtDSSfTs3q2s3764:2117088811)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 4 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660)*

**Comment by sherm1** [comment]
Merge after successful CI.

---

Reviewed 1 of 4 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLMgPUucrwjynQcB4oO:176803987)*

**Comment by liangfok** [comment]
OK will do. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2660#-:-KLMhwEH1hFNXBV2EIN_:1297268108)*

**Comment by jwnimmer-tri** [comment]
It looks like this hit some kind of #2660-related runtime error.  Whee!

**Comment by mwoehlke-kitware** [comment]
@liangfok, this appears to have broken CI on Windows; can you look at it, or does it need to be reverted?

**Comment by liangfok** [comment]
I created this PR, which will hopefully solve this problem:

https://github.com/RobotLocomotion/drake/pull/2679

It's being tested here:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/14/

**Comment by jwnimmer-tri** [comment]
The ninja-msvc-32 build that passed pre-merge Jenkins had this warning:
```
11:31:19 C:\projects\workspace\experimental\a99ae8ad\build\include\gtest/internal/gtest-internal.h(484): warning C4316: 'drake::systems::test::`anonymous-namespace'::SimulationTerminationTest_TerminationConditionTrue_Test': object allocated on the heap may not be aligned 16
```

This suggests that #2498 is even more important to fix now.

**Pull request merged**
