### PR TITLE
Allocate input

### LINKED ISSUE #5343: Provide System-level mechanism for Allocating inputs
For motivation, see:
https://github.com/RobotLocomotion/drake/blob/master/drake/systems/trajectory_optimization/direct_collocation.cc#L28

This toolchain needs to be able to create inputs to supply to the provided System*, and currently simply creates BasicVector's because it doesn't know any better.  This is insufficient for systems that expect typed input, e.g.,
https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/simple_car.cc#L109

### PR DESCRIPTION
**Pull request by RussTedrake**
As discussed with @jwnimmer-tri and @david-german-tri.  Resolves #5343

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5357)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@david-german-tri or @sherm1 for feature review, please.  

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-Ke9BLj6rU5qwhlvskGQ:b-45bkd4)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9dZ3Qc786qh4to33X:-Ke9dZ3Qc786qh4to33Y:bsjs21y) (no related file):*
#4843 has bitten this PR.

Russ, if you want to tick the "grant contributors push access" I will push a whitespace-shuffle revert.  But your commits seem to be set up for merge-without-squash in which case I shouldn't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 2 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/system.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iF9nrg3tnHa9_KDb:-Ke9iF9oxUmYgOCggcpF:b-muj5ct) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L117)):*
> ```objc
>   virtual std::unique_ptr<BasicVector<T>> AllocateInputVector(
>       const InputPortDescriptor<T>& descriptor) const {
>     return std::make_unique<BasicVector<T>>(descriptor.size());
> ```

We should fail-fast if the descriptor is invalid, either if its out-of-range, or not a vector-valued port.  (The `AllocateOutputVector` doesn't check that either, but it probably should.)

---

*[drake/systems/framework/system.h, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iczxUfO7i7sCOfV-:-Ke9iczxUfO7i7sCOfV0:bjm0kjy) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L130)):*
> ```objc
>         "override AllocateInputAbstract.");
>   }
> ```

For both of these methods, since they are overridden in Diagram, and these implementations and (most of the) comments only apply to leaf systems, I think these methods should become abstract, and then these implementations move into LeafSystem.

---

*[drake/systems/framework/system.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9j1SjHnA6VKtjrH7_:-Ke9j1SjHnA6VKtjrH7a:bxf44h4) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L175)):*
> ```objc
> 
>   /// Allocates uninitialized input vectors and/or abstract data for all
>   /// registered input ports.
> ```

The code allocates _all_ input ports, not just the uninitialized ones.  Either the code or docs are wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-Ke9krUeE5IQgh9OeQw8:by96gdd)*

**Comment by jwnimmer-tri** [comment]
First pass done.

---

Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/test/system_test.cc, line 280 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeA3CJ8TpPlbzCeo0Mc:-KeA3CJ8TpPlbzCeo0Md:b1m2fma) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/test/system_test.cc#L280)):*
> ```cpp
>  public:
>   explicit TestTypedVector(int size) : BasicVector(size) {}
> };
> ```

Subclasses of BasicVector should override `DoClone` and declare `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`.

There are already a few examples of test-sample vectors throughout the framework test code, maybe we should centralize that.  (Or just fix this one and we'll consolidate later.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-KeA4KX8MwuPl0YSsizz:b-te4kzy)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9dZ3Qc786qh4to33X:-KeAIrs98VXoyBuQmhb_:bxohfbz) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

#4843 has bitten this PR.

Russ, if you want to tick the "grant contributors push access" I will push a whitespace-shuffle revert.  But your commits seem to be set up for merge-without-squash in which case I shouldn't.
</blockquote></details>

just enabled this.  thx!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9dZ3Qc786qh4to33X:-KeA__sUtJeYFesljZvF:b-896fix) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

just enabled this.  thx!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by sherm1** [comment]
First, per discussion in #5343 can this be accomplished using only EvalVectorInput(context,port) to extract a representative value? That would require someone to connect or free-stand all the inputs first, with full information about which of the many acceptable types for an input port would be appropriate.

Assuming that doesn't work, I'm not wild about introducing new System API methods when the Input Port is the object we should be talking with. `iport.AllocateAnAcceptableDefaultValue()` seems preferable to me over `system.AllocateAnAcceptableDefaultValue(iport)` which I think is a step towards an unnecessarily bloated API. 

Currently the System input and output ports are second class citizens but I want to see them promoted to InputPort and OutputPort objects on which we can hang growing functionality with bloating System's API. (I'm not referring to the Context-related classes with those names -- those need to be demoted to something like InputPortConnection and OutputPortValue.)

If a shorter term workaround is needed, I'm not opposed to the current proposal, with some further hacks PTAL.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeAtXlkeFbFHRiusQBJ:bk8s3xp) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
> ```objc
>   /// ports must override. The descriptor must match a port declared via
>   /// DeclareOutputPort.
>   virtual std::unique_ptr<AbstractValue> AllocateInputAbstract(
> ```

These methods should use the NVI pattern to allow the base class to error check and then invoke `protected: virtual AbstractValue* DoAllocateInputAbstract(descriptor) const;` which can be implemented covariantly to safely return a naked pointer the actual type. Then the many implementations do not have to error check their arguments and do not have to mess with unique_ptr and ownership issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-KeAnqjtErLpRsMCjWUo:b5rw5o)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeAxpFZIVu594lJSrsk:b-xx2n04) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

These methods should use the NVI pattern to allow the base class to error check and then invoke `protected: virtual AbstractValue* DoAllocateInputAbstract(descriptor) const;` which can be implemented covariantly to safely return a naked pointer the actual type. Then the many implementations do not have to error check their arguments and do not have to mess with unique_ptr and ownership issues.
</blockquote></details>

The NVI discussion aside, over time I've become less and less of a fan of returning a bare owned pointer.  I don't think the covariance is buying us much (approximately nobody is calling the naked DoAllocation spelling since its protected anyway), and leaking allocations is really bad.  I think this PR should stick with unique_ptr, whatever else happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeB6zo9m8a8h1ifZ_wX:bty1dfq) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The NVI discussion aside, over time I've become less and less of a fan of returning a bare owned pointer.  I don't think the covariance is buying us much (approximately nobody is calling the naked DoAllocation spelling since its protected anyway), and leaking allocations is really bad.  I think this PR should stick with unique_ptr, whatever else happens.
</blockquote></details>

I like the raw pointers here to minimize the amount of boiler plate that has to be done correctly in the derived-class implementations. Covariance comes for free with that approach but I agree we aren't doing anything useful with it currently. I feel strongly that we should use the NVI pattern here but don't care much about the signature details of the protected virtual.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by RussTedrake** [comment]
@sherm1 -- had a long discussion with @david-german-tri about his comments, and we agreed that the approach here was better than the `EvalVectorInput`.

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/system.h, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iczxUfO7i7sCOfV-:-KeELuSsKLPT3HsaHcz6:b-1rl8eu) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L130)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For both of these methods, since they are overridden in Diagram, and these implementations and (most of the) comments only apply to leaf systems, I think these methods should become abstract, and then these implementations move into LeafSystem.
</blockquote></details>

Update: if Sherm's request to make these two methods use NVI is granted, then my discussion here need to be modified.

My defect here would have been better phrased as "these method bodies should be LeafSystem implementations; there should be no default System implementation", rather than a more specific solution.

If `AllocateInput{Vector,Abstract}` turns into a non-virtual public method that calls a pure virtual`DoAllocateInput{Vector,Abstract}` method, then the resolution here would be do override `DoAllocateInput{Vector,Abstract}` in LeafSystem and Diagram only.  (Plus the few test-stub classes that directly inherit from System, I guess.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by david-german-tri** [comment]
+@david-german-tri It turns out I have a direct stake in this: we need it for `SparsityMatrix` to function properly on direct-feedthrough systems that use derived types.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-KeKZWeZsYInWo_x28Yp:b-9etjdq)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKaBG7dAGHSn6eFIpL:-KeKaBG8L5mMQXF9XQkW:b-il1u1e) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/diagram.h#L303)):*
> ```objc
>     // Ask the subsystem to perform the allocation.
>     DRAKE_DEMAND(descriptor.get_index() <
>                  static_cast<int>(input_port_ids_.size()));
> ```

`get_num_input_ports` (Ditto below.)

---

*[drake/systems/framework/diagram.h, line 305 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeK_vldq6uQDR6LGW8I:-KeK_vlehP3Ze8nDdj3n:bnuokbt) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/diagram.h#L305)):*
> ```objc
>                  static_cast<int>(input_port_ids_.size()));
>     const PortIdentifier& id = input_port_ids_[descriptor.get_index()];
>     const InputPortDescriptor<T> subsystem_descriptor(
> ```

Why not just say `id.first->get_input_port(id.second)`?  (Ditto below.)

---

*[drake/systems/framework/system.h, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iczxUfO7i7sCOfV-:-KeKbKsG5Oh43OY3voNW:b-ll4gy8) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L130)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Update: if Sherm's request to make these two methods use NVI is granted, then my discussion here need to be modified.

My defect here would have been better phrased as "these method bodies should be LeafSystem implementations; there should be no default System implementation", rather than a more specific solution.

If `AllocateInput{Vector,Abstract}` turns into a non-virtual public method that calls a pure virtual`DoAllocateInput{Vector,Abstract}` method, then the resolution here would be do override `DoAllocateInput{Vector,Abstract}` in LeafSystem and Diagram only.  (Plus the few test-stub classes that directly inherit from System, I guess.)
</blockquote></details>

FYI I agree with this.

---

*[drake/systems/framework/system.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9j1SjHnA6VKtjrH7_:-KeKbUN2S3q_nrmiY7g2:b-mde105) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The code allocates _all_ input ports, not just the uninitialized ones.  Either the code or docs are wrong.
</blockquote></details>

BTW The way I read it, "uninitialized" means that this function does not assign any particular values to any of the inputs.  It does not imply that the function leaves in place inputs that were previously connected.  So, I think it's correct as is, but could perhaps be rewritten for clarity.

---

*[drake/systems/framework/system.h, line 114 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKabQsogjioBe4Z1dW:-KeKabQsogjioBe4Z1dX:b-iwhizn) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L114)):*
> ```objc
>   /// Given a port descriptor, allocates the vector storage.  The default
>   /// implementation in this class allocates a BasicVector.  Subclasses can
>   /// override to use output vector types other than BasicVector.  The
> ```

s/output/input

---

*[drake/systems/framework/system.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKadb2mmV0v6zM5Bx9:-KeKadb2mmV0v6zM5BxA:b-83cp1v) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L123)):*
> ..must override

Is this really true?  The framework doesn't call this function, and neither does the Simulator, so I think Systems for many uses can get away without overriding.

---

*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeKaU6c1DhxJPiY_Cx4:bdv0m03) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I like the raw pointers here to minimize the amount of boiler plate that has to be done correctly in the derived-class implementations. Covariance comes for free with that approach but I agree we aren't doing anything useful with it currently. I feel strongly that we should use the NVI pattern here but don't care much about the signature details of the protected virtual.
</blockquote></details>

FYI, I agree with @sherm1 that NVI would be better.  I also think the `Do` function should return bare pointers just for consistency with other code, even though I agree with @jwnimmer-tri that it hasn't turned out to be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by david-german-tri** [comment]
Since it turns out my automotive forward progress is blocked on this PR, I'm going to try to resolve the pending threads by pushing additional commits to this branch today.

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/system.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9j1SjHnA6VKtjrH7_:-KeKiV4J1yASyLNNscqz:bfla15x) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L175)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW The way I read it, "uninitialized" means that this function does not assign any particular values to any of the inputs.  It does not imply that the function leaves in place inputs that were previously connected.  So, I think it's correct as is, but could perhaps be rewritten for clarity.
</blockquote></details>

Yes, per f2f with Russ that's how he meant it as well, and we agree it just needs a little wordsmithing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeKitqXNp1YP2QRT7gF:b-3aogr1) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

FYI, I agree with @sherm1 that NVI would be better.  I also think the `Do` function should return bare pointers just for consistency with other code, even though I agree with @jwnimmer-tri that it hasn't turned out to be useful.
</blockquote></details>

SGTM.  But I think we could consider a follow-up PR to turn bare pointers into owned across the board, and see if the syntax burden is really as large as claimed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by david-german-tri** [comment]
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 303 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKaBG7dAGHSn6eFIpL:-KeKiWlVuofkaLO5d5_v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/diagram.h#L303)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

`get_num_input_ports` (Ditto below.)
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 305 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeK_vldq6uQDR6LGW8I:-KeKiXNE2yRYua526L79:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/diagram.h#L305)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Why not just say `id.first->get_input_port(id.second)`?  (Ditto below.)
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iF9nrg3tnHa9_KDb:-KeKm32JvGORuBtgsnK1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L117)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We should fail-fast if the descriptor is invalid, either if its out-of-range, or not a vector-valued port.  (The `AllocateOutputVector` doesn't check that either, but it probably should.)
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9iczxUfO7i7sCOfV-:-KeKm97mhk3vZSp5NU4_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L130)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

FYI I agree with this.
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-Ke9j1SjHnA6VKtjrH7_:-KeKmWoL_HTNhlffDE8l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/system.h#L175)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, per f2f with Russ that's how he meant it as well, and we agree it just needs a little wordsmithing.
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 114 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKabQsogjioBe4Z1dW:-KeKinq1r0TyNSdCQ45C:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L114)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

s/output/input
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 123 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeKadb2mmV0v6zM5Bx9:-KeKm4OrxND9HOHw9puR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L123)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> ..must override

Is this really true?  The framework doesn't call this function, and neither does the Simulator, so I think Systems for many uses can get away without overriding.
</blockquote></details>

Done.

---

*[drake/systems/framework/system.h, line 125 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeAtXljoCy9bwzyXd8R:-KeKm7S6Ut-5DwxfffbL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e8242281abb9bb0e2c8748068b40a4851fd13f7/drake/systems/framework/system.h#L125)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

SGTM.  But I think we could consider a follow-up PR to turn bare pointers into owned across the board, and see if the syntax burden is really as large as claimed.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/system_test.cc, line 280 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeA3CJ8TpPlbzCeo0Mc:-KeKmiprjMbG1IeNOsZZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/968525014a3a57a889f8b6c2f84bb5d5539c66ee/drake/systems/framework/test/system_test.cc#L280)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Subclasses of BasicVector should override `DoClone` and declare `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`.

There are already a few examples of test-sample vectors throughout the framework test code, maybe we should centralize that.  (Or just fix this one and we'll consolidate later.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeLJlf3QLsXPC-4RNuG:-KeLJlf4bPQprYlQ2zFV:bk1tshw) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e954f2ad58e3675bdddd49af33f559a0067142/drake/systems/framework/system.h#L115)):*
> ```objc
>   /// Given a port descriptor, allocates the vector storage.  The default
>   /// implementation in this class allocates a BasicVector.  Subclasses can
>   /// override to use input vector types other than BasicVector. The
> ```

BTW Is "subclasses can override" too misleading?  They override the NVI `Do` method, not this one.  (Ditto for abstract, below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-KeLKfIWqMrHqc4QfXif:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 115 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-KeLJlf3QLsXPC-4RNuG:-KeLTio8JlcQgm1dLMG_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5e954f2ad58e3675bdddd49af33f559a0067142/drake/systems/framework/system.h#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is "subclasses can override" too misleading?  They override the NVI `Do` method, not this one.  (Ditto for abstract, below.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357)*

**Comment by david-german-tri** [comment]
-@david-german-tri -@sherm1 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5357#-:-KeLdPlmtvU-d3kP7a75:b-e2erqc)*

**Pull request merged**
