### PR TITLE
[framework] Add ValueProducer constructor sugar

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Refer to the overall changesets in #15161 to see how this gets used, especially the "Use new ValueCalcFunction sugar".

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review, please.

**Review by sherm1 — COMMENTED** [review]
Checkpoint (just through the docs and public section in value_producer.h).
A random thought: are we sorry that we chose `(allocator, calculator)` in that order in argument lists? Given that the allocator rarely appears, `(calculator [, allocator])` seems more natural. I'm not sure it's worth changing but if it is this would be the time.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MdY-gwF2X2UOiesc-GH:blk96rm)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[systems/framework/value_producer.h, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXknTICjhJBil-prpS:-MdXknTICjhJBil-prpT:bux96pu) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L17)):*
> ```objc
> 
> /** %ValueProducer computes an AbstractValue output based on a ContextBase
> input.
> ```

BTW a hint about usage would be good here, e.g. "This is commonly used for declaring output ports and cache entries."
___
*[systems/framework/value_producer.h, line 125 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXiZDwBJHOEvq1EzsX:-MdXiZDwBJHOEvq1EzsY:b64i4f9) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L125)):*
> ```objc
> 
>   - (1) `calc` is a member function pointer with an output argument
>   - (2) `calc` is a member function pointer with a return value &dagger;
> ```

nit: prefer Unicode † to `&dagger;` for local readability.
___
*[systems/framework/value_producer.h, line 128 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXihrs7TOdF5kuLTD7:-MdXihrs7TOdF5kuLTD8:b-2vuj71) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L128)):*
> ```objc
>   - (3) `calc` is a std::function with an output argument
>   - (4) `calc` is a std::function with a return value &dagger;
>   - (5) `calc` is a generic CalcCallback
> ```

BTW consider a period at the end of the final list item.
___
*[systems/framework/value_producer.h, line 130 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXiq2N7UT65bx6WS2P:-MdXiq2N7UT65bx6WS2Q:b-9hnkqx) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L130)):*
> ```objc
>   - (5) `calc` is a generic CalcCallback
> 
>   &dagger; Do not (2) or (4) use unless SomeOutput is cheap to copy.
> ```

minor: "Do not _use_ (2) or (4) ~use~ unless ..."
___
*[systems/framework/value_producer.h, line 148 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXo_FhAiXwO45T4k3G:-MdXo_FhAiXwO45T4k3H:b-u49289) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L148)):*
> ```objc
>   - The `instance` pointer (iff member function callback(s) are used).
>   - The `model_value` example or `allocate` callback (may be omitted).
>   - The `calc` callback (required).
> ```

FYI oddly, the list items in the above three lists format in italics while the list in the class documentation does not.
___
*[systems/framework/value_producer.h, line 338 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXzV2A2taO5XCslOx0:-MdXzV2A2taO5XCslOx1:b-2r3n4x) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L338)):*
> ```objc
>       const SomeOutput& model_value, CalcCallback calc,
>       // NOLINTNEXTLINE(whitespace/line_length)
>       std::enable_if_t<!std::is_convertible_v<SomeOutput, AllocateCallback>>* = 0)
> ```

nit: I don't think a line length exception is warranted here. (Definitely ugly in Reviewable!) Either of these would be better IMO:
```c++
std::enable_if_t<!std::is_convertible_v<SomeOutput, 
                                        AllocateCallback>>* = 0)
std::enable_if_t<
    !std::is_convertible_v<SomeOutput, AllocateCallback>>* = 0)
```

**Review by jwnimmer-tri — COMMENTED** [review]
For my taste, I like having the `model_value` appear prior to the `calc`.  We could still place the`allocate` callback after `calc` when not using a model value, but my inclination is to leave it alone.  (When prototyping this work, I did toy with trying to organize things to allow for default arguments, but I found it to be too confusing to help explain the overloads.  Writing everything out repetitively seemed like it would be clearest over the long term.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MdY73r6CEcDSG_fhf34:bf8yc4m)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[systems/framework/value_producer.h, line 148 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXo_FhAiXwO45T4k3G:-MdY6qzWA8YppsOtOL6Y:b-7xf1fo) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L148)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI oddly, the list items in the above three lists format in italics while the list in the class documentation does not.
</blockquote></details>

Done (via css fix).

**Review by sherm1 — COMMENTED** [review]
Checkpoint 2. Finished value_producer.h. I like the elegant way the voluminous cross product of methods is organized.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MdYGQ9y4evkU6TLZFcH:bcuf0yu)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[systems/framework/value_producer.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYFVyWC9SCIUpTbc83:-MdYFVyWC9SCIUpTbc84:b-avtmhc) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L127)):*
> ```objc
>   - (2) `calc` is a member function pointer with a return value &dagger;
>   - (3) `calc` is a std::function with an output argument
>   - (4) `calc` is a std::function with a return value &dagger;
> ```

minor: Do (3) and (4) require an explicit `std::function`? That is, is it correct that I can write `ValueProducer(&MyClass::MyMethod)` but I can't write `ValueProducer(&MyFreeFunction)`? That seems awkward if so.

**Review by jwnimmer-tri — COMMENTED** [review]
Yup.  From reading foonathan and learning a bit about https://github.com/standardese/standardese, the idea that we should not document _functions_ but rather document _overload sets_ (e.g., like cppreference does) has stuck with me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MdYL9a6ElgGESH2VkTU:b5frh2d)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @sherm1)

___
*[systems/framework/value_producer.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYFVyWC9SCIUpTbc83:-MdYKLN6ASht-yeFaVxj:b-pm0xit) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L127)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: Do (3) and (4) require an explicit `std::function`? That is, is it correct that I can write `ValueProducer(&MyClass::MyMethod)` but I can't write `ValueProducer(&MyFreeFunction)`? That seems awkward if so.
</blockquote></details>

Yes, the compiler does seem to require some guidance in order to choose the desired overload.  With just the plain `&MyFreeFunction`, it was "template argument deduction / substitution failed".

Yes, I agree it is awkward.

I don't 100% remember what led me to incorporate these options 3 and 4 into the overload sets in the first place.  I think perhaps it was useful with lambdas, and not so much with free functions?

I will go back to the full branch and try to better understand the motivation for these, and then maybe we can adjust / amend them to better meet the need.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: pending a few open discussions.

> Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MdYQm0eD7Gw7fJMtz1m:bvj1prg)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/doxygen_extra.css, line 60 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYMayM4hPYpJnsAJ6O:-MdYMayM4hPYpJnsAJ6P:b-kqrpz9) ([raw file](https://github.com/robotlocomotion/drake/blob/8d12ac5d4ffd795e59a00d61876203de1dd5df59/doc/doxygen_cxx/doxygen_extra.css#L60)):*
> ```CSS
> div.groupText {
>   font-style: inherit;
> }
> ```

BTW magic! It's amazing to me that you knew how to fix that.
___
*[systems/framework/value_producer.h, line 148 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdXo_FhAiXwO45T4k3G:-MdYQaTb0tQAhP5jr221:bnats8d) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done (via css fix).
</blockquote></details>

:clap:
___
*[systems/framework/test/value_producer_test.cc, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYNGeiChCM6l0nvU9C:-MdYNGeiChCM6l0nvU9D:bvvtz0m) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/test/value_producer_test.cc#L35)):*
> ```cpp
> // of these options, so that we can easily mix and match them in test cases.
> 
> // For readability, we'll spell out (1) as "one" and (a) as "alpha", etc.
> ```

BTW consider adding "All combinations are tested below except for 5a which doesn't make sense."
___
*[systems/framework/test/value_producer_test.cc, line 312 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYQBxfBdPas4cnGtD3:-MdYQBxfBdPas4cnGtD4:bjx6ew6) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/test/value_producer_test.cc#L312)):*
> ```cpp
> }
> 
> #undef DRAKE_CHECK_CTOR_NULL
> ```

BTW polite, but not actually needed at the end of a .cc file.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[doc/doxygen_cxx/doxygen_extra.css, line 60 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYMayM4hPYpJnsAJ6O:-MdYR2aY9TR-IWufs3L4:b-2191cm) ([raw file](https://github.com/robotlocomotion/drake/blob/8d12ac5d4ffd795e59a00d61876203de1dd5df59/doc/doxygen_cxx/doxygen_extra.css#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW magic! It's amazing to me that you knew how to fix that.
</blockquote></details>

FYI the first step is to right-click on the thing that you don't like (e.g., italic bullet) in your browser, and choose "Inspect" or "Inspect element' or etc.  That shows the details of _why_ it's italic.  If the CSS to blame is _our_ css (i.e., a file in drake's git repo) then it's usually easy to fix.  In this case it was in Doxygen's built-in CSS, though, which I had to override here.
___
*[systems/framework/value_producer.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYFVyWC9SCIUpTbc83:-Mdx0nc6-IrX82OglrXD:b-4rfkue) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, the compiler does seem to require some guidance in order to choose the desired overload.  With just the plain `&MyFreeFunction`, it was "template argument deduction / substitution failed".

Yes, I agree it is awkward.

I don't 100% remember what led me to incorporate these options 3 and 4 into the overload sets in the first place.  I think perhaps it was useful with lambdas, and not so much with free functions?

I will go back to the full branch and try to better understand the motivation for these, and then maybe we can adjust / amend them to better meet the need.
</blockquote></details>

Update:

For the calc function, I took the prototyping branch at #15161 and removed overloads (3) and (4).   Besides the value_producer unit test, they were not yet used _anywhere_ else.

On that branch, the one place they _should_ still be used is `deformable_rigid_manager` to sugar away some of the casting (I just haven't refactored it yet to do so), but in that case they are either going to be a lambda, or a member function pointer -- not a bare function pointer.

Given that, my inclination would be to re-jigger the documentation to highlight the use of lambdas, demonstrate the explicit std::function conversion, and call it a day.

We could _imagine_ adding more overloads for a bare function pointer, but I'm wondering if anyone would ever use it?

WDYT?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/framework/value_producer.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYFVyWC9SCIUpTbc83:-MdxVNyVB0-OkzVfD7bL:b-5qvbh6) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Update:

For the calc function, I took the prototyping branch at #15161 and removed overloads (3) and (4).   Besides the value_producer unit test, they were not yet used _anywhere_ else.

On that branch, the one place they _should_ still be used is `deformable_rigid_manager` to sugar away some of the casting (I just haven't refactored it yet to do so), but in that case they are either going to be a lambda, or a member function pointer -- not a bare function pointer.

Given that, my inclination would be to re-jigger the documentation to highlight the use of lambdas, demonstrate the explicit std::function conversion, and call it a day.

We could _imagine_ adding more overloads for a bare function pointer, but I'm wondering if anyone would ever use it?

WDYT?
</blockquote></details>

:+1: I'm happy with that approach. We can add more overloads in the future if warranted.

**Review by jwnimmer-tri — COMMENTED** [review]
+@soonho-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-Mdx_K-30xe_RG52xHLb:b-583msa)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @sherm1 and @soonho-tri)

___
*[systems/framework/value_producer.h, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYFVyWC9SCIUpTbc83:-MdxZv0xB5R7uQwubJ_2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/value_producer.h#L127)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

:+1: I'm happy with that approach. We can add more overloads in the future if warranted.
</blockquote></details>

Done.
___
*[systems/framework/test/value_producer_test.cc, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MdYNGeiChCM6l0nvU9C:-MdxXCuR2I57b57Z3Fj5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ef0e14bf5f8c82dfcb08747625b6620b068e1e44/systems/framework/test/value_producer_test.cc#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding "All combinations are tested below except for 5a which doesn't make sense."
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
-@soonho-tri . Sorry I couldn't start reviewing this one due to large volume of PRs yesterday.
+@ggould-tri for platform-review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-Me56CAmBZQSFYUYU3_M:b2mey2o)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sherm1)

**Review by soonho-tri — COMMENTED** [review]
-@ggould-tri , my mistake (I thought next Monday is your on-call day).
+@SeanCurtis-TRI for platform-review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-Me5dxOB4Uz8tK8uCbcC:b-t08ffc)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @sherm1)

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@seancurtis-tri +@ggould-tri (platform review switcheroo).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MePps0m9fEoab0fUCQx:b-sbf15l)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sherm1)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: This is a huge improvement and very clear.  Minor items below.

> Reviewed 2 of 4 files at r2, 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MeQCtS4BXWGPgIUgYzK:bijqsz5)* status: 4 unresolved discussions (waiting on @jwnimmer-tri)

___
*[systems/framework/value_producer.h, line 34 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ6Tq_Co9Y6i7S89n4:-MeQ6Tqa6aIjuW3cyYlG:b-uky6wq) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L34)):*
> ```objc
> 
> @code
>   ValueProducer producer(calc);
> ```

nit:  You called it`my_calc`above and `calc` here.
___
*[systems/framework/value_producer.h, line 130 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ9evHDTASHUR0bsQ6:-MeQ9evHDTASHUR0bsQ7:b-55dlg0) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L130)):*
> ```objc
>   - (5) `calc` is a generic CalcCallback.
> 
>   † Do not use (2) nor (4) unless SomeOutput is cheap to copy.
> ```

minor:  The name `SomeOutput` has not been used before this point.  Consider "the output type" or else moving this dagger to a point later than line 170.
___
*[systems/framework/value_producer.h, line 161 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQAzHHAc6JcEABi4b5:-MeQAzHHAc6JcEABi4b6:b-8faj34) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L161)):*
> ```objc
>   If either `allocate` or `calc` is a member function pointer, then the class
>   `instance` to bind must be the first argument. This `instance` pointer is
>   aliased by the ValueProducer, so must outlive this object.
> ```

minor:  It's a little hard to reason about how to meet this restriction in practice since `SomeClass` and the owner of `this` are going to be used in situations where they don't control their own lifetimes (eg via builders); consider (author's discretion) noting that `instance` should typically be the owner of `this`.
___
*[systems/framework/test/value_producer_test.cc, line 18 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ7lexAjIV0p7ySnr_:-MeQ7lexAjIV0p7ySnra:b-1n4gbu) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/test/value_producer_test.cc#L18)):*
> ```cpp
> using AllocateCallback = ValueProducer::AllocateCallback;
> using CalcCallback = ValueProducer::CalcCallback;
> ```

nit: It would be good to test the literal code from the documentation example here.  That would also mean that there's a tested example with a lambda.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @ggould-tri)

___
*[systems/framework/value_producer.h, line 34 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ6Tq_Co9Y6i7S89n4:-MeQ_EV44zclgrs_9Zgn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L34)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  You called it`my_calc`above and `calc` here.
</blockquote></details>

Done.
___
*[systems/framework/value_producer.h, line 130 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ9evHDTASHUR0bsQ6:-MeQZtf10y2ccahMFHSW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L130)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The name `SomeOutput` has not been used before this point.  Consider "the output type" or else moving this dagger to a point later than line 170.
</blockquote></details>

Done.
___
*[systems/framework/value_producer.h, line 161 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQAzHHAc6JcEABi4b5:-MeQaW_S6ghCM8so2U5K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/value_producer.h#L161)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It's a little hard to reason about how to meet this restriction in practice since `SomeClass` and the owner of `this` are going to be used in situations where they don't control their own lifetimes (eg via builders); consider (author's discretion) noting that `instance` should typically be the owner of `this`.
</blockquote></details>

Done.
___
*[systems/framework/test/value_producer_test.cc, line 18 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15271#-MeQ7lexAjIV0p7ySnr_:-MeQfCkj-H9tEsjGd8mr:bpw41qf) ([raw file](https://github.com/robotlocomotion/drake/blob/a527b56204a9c4b831ce13bf935db670d5f38e60/systems/framework/test/value_producer_test.cc#L18)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit: It would be good to test the literal code from the documentation example here.  That would also mean that there's a tested example with a lambda.
</blockquote></details>

Done (below).

**Comment by jwnimmer-tri** [comment]
(FYI I'm going to wait for Grant or Sherm to look at the small new diff, before I merge.)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
lgtm on the new diff, and I'm glad actually compiling the doc code gave some useful improvements :-)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15271#-:-MeRBnrV5yD_ZgARlM3T:b-cuit5n)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yes, and I am thrilled to finally use CTAD!  A couple years ago, we had to support >= C++14 still.

**Pull request merged**
