### PR TITLE
expose the playback method for trajectories in DrakeVisualizer.

### PR DESCRIPTION
**Pull request by RussTedrake**
will be very useful for upcoming work on trajectory optimization.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5241)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@seancurtis-tri for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-:-KdVlBCzIw8fYbQ8uHp0:b-t5m2ic)*

**Comment by SeanCurtis-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-:-KdW6_PDXGhEbM75pv5v:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-KdWaUphuOJf1vyezp2t:-KdWaUphuOJf1vyezp2u:b-flctqu) ([raw file](https://github.com/robotlocomotion/drake/blob/4ff4fa4d321d1a46fcc97b7240417ee0073a4579/drake/multibody/rigid_body_plant/drake_visualizer.cc#L73)):*
> ```cpp
> 
> void DrakeVisualizer::PlaybackTrajectory(
> const PiecewisePolynomial<double>& input_trajectory) const {
> ```

BTW, a method's parameter list should be indented by four spaces per style guide.

https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241)*

**Comment by RussTedrake** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-KdWaUphuOJf1vyezp2t:-KdXhomJyxEQPEckTcBF:bxwva7u) ([raw file](https://github.com/robotlocomotion/drake/blob/4ff4fa4d321d1a46fcc97b7240417ee0073a4579/drake/multibody/rigid_body_plant/drake_visualizer.cc#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, a method's parameter list should be indented by four spaces per style guide.

https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions
</blockquote></details>

hrm.  pretty sure I ran clang-format.  done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241)*

**Comment by RussTedrake** [comment]
+@david-german-tri +@soonho-tri for platform review please

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-:-KdXlvCffdHoOmTK0JsA:b-x0nxuq)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-KdWaUphuOJf1vyezp2t:-KdXr--lEKl7g9zef66s:bjkbd8s) ([raw file](https://github.com/robotlocomotion/drake/blob/4ff4fa4d321d1a46fcc97b7240417ee0073a4579/drake/multibody/rigid_body_plant/drake_visualizer.cc#L73)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

hrm.  pretty sure I ran clang-format.  done.
</blockquote></details>

Odd. Maybe there is a version difference between Ubuntu vs. OSX. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.h, line 104 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-KdYAIhlyxROUH3K5muN:-KdYAIhlyxROUH3K5muO:b-lo4l18) ([raw file](https://github.com/robotlocomotion/drake/blob/def57e78db9b16396fd294a4261c50b466dfc4ab/drake/multibody/rigid_body_plant/drake_visualizer.h#L104)):*
> ```objc
> 
>   /**
>    * Play back (at real time) a trajectory representing the input signal.
> ```

nit: `Play` => `Plays` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-:-KdYAx4jttXrp268d6ZG:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5241#-:-KdYCzSgtYbvxhXWFHtM:bnfp4nl)*

**Pull request merged**
