### PR TITLE
Expose AddPerspectiveCost and AddPerspectiveConstraint to Python API.

### PR DESCRIPTION
**Pull request by richardrl**
@RussTedrake for review please

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20214)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20214)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 577 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20214#-Nf1QHH5ACeTq7urET4L:-Nf1QHH5ACeTq7urET4M:btl7xsb) ([raw file](https://github.com/RobotLocomotion/drake/blob/44de1b8e96c8b6690c18db0af9e89aedc36fa642/geometry/optimization/graph_of_convex_sets.h#L577)):*
> ```objc
>   void AddPerspectiveCost(solvers::MathematicalProgram* prog,
>                           const solvers::Binding<solvers::Cost>& binding,
>                           const solvers::VectorXDecisionVariable& vars) const;
> ```

If we want to make these public, then we should move them to MathematicalProgram.  It seems fine to me to make them public, but not here.  With the current API, GCS users should never be working with the `prog` directly.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20214)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),RussTedrake(platform)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 711 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20214#-Nf1Q_8XB0Wp5pvKIFNo:-Nf1Q_8XB0Wp5pvKIFNp:b-qb9u2o) ([raw file](https://github.com/RobotLocomotion/drake/blob/44de1b8e96c8b6690c18db0af9e89aedc36fa642/bindings/pydrake/geometry/geometry_py_optimization.cc#L711)):*
> ```cpp
>         .def("AddPerspectiveCost", &GraphOfConvexSets::AddPerspectiveCost,
>             py::arg("prog"), py::arg("binding"), py::arg("vars"),
>             py_rvp::reference_internal, cls_doc.AddPerspectiveCost.doc)
> ```

If we also promote AddPerspectiveConstraint to public (in MathematicalProgram) then we should add the binding for it here, too.

**Comment by jwnimmer-tri** [comment]
Thanks, Russ.  I definitely agree that the functions should be a feature of MathematicalProgram (or at least, live in `drake/solvers` somwhere), rather than changing the GCS spelling of these to be public.

In good news, these two functions could have (should have) been marked `static`, since they do not use any of the member fields of the `GraphOfConvexSets` object.  That removes one impediment to moving them.

So, the work needed here is to relocate the two functions to `solvers` and change `GraphOfConvexSets` to call the functions from their new home.  Since the functions would become public, we also need unit test(s) in the `solvers` folder to check that they operate correctly.

I did not immediate see any GCS unit tests that could easily be ported to cover these functions, so my best guess is that the tests would need to be developed from scratch.

The other question is setting the API design.  The functions currently take a `const Binding<Cost>& binding` but they don't use the `binding.variables()` at all.  Should they instead directly take a `std::shared_ptr<Cost>`?  If we keep the Binding around, we'll need a comment to explain why (and remind callers that we're throwing away the existing variables), since it's not obvious.

@richardrl would you like to work on changing this PR per the above advice?  Let us know if there are questions we can help us.  Or if you, instead you could consider closing this PR and opening a feature request issue instead.

**Comment by richardrl** [comment]
Hi @jwnimmer-tri @RussTedrake yes I can look into this, I'm not able to gauge how much work is necessary so it might be some time / might need to feature request it if others want it sooner or its more work than expected.

For the unit test, would this suffice, for example for the AddPerspectiveConstraint:
Only adding a unit test for the linear case:
1. Create some constant constraint matrix A, vector b for a linear constraint.
2. Call AddPerspectiveConstraint on the binding of the linear constraint to create a new constraint for a `prog`.
3. Pull the new constraint from the prog, evaluate it over some explicit (x, lambda) tuples that should be in the perspective, but not in the original polyhedron.

**Comment by jwnimmer-tri** [comment]
Thanks!

I realized there might be an easy way to search for existing GCS test cases that could help bootstrap any new tests.

If you change the implementation of e.g. `AddPerspectiveConstraint` to call `DRAKE_THROW_UNLESS(false);` as its first line and then run the existing `graph_of_convex_sets_test` program, any tests that (indirectly) called that function would show up as FAIL in the output.  You could peruse those pieces of the test code to see if they are a good starting point.

> For the unit test, would this suffice, ...

I'm not super familiar with the code, but there are some key principles that might help:
- Every line of the code in the new functions should be run by its unit test.  That means if a function has if-else branches, it will need more than one test case (so that each branch body clause will be run).
- The tests should check for a correct implementation.  Your (3) seems a fine starting point.  Possibly I could see just testing the `A` matrix (or whatever) of the newly-added constraint directly for the simpler cases, but evaluating some sample points seems pretty good, too.  Maybe also check 1 sample outside the constraint as well, to demonstrate that the constraint can return both true and false.

> ... others want it sooner ...

To the best of my knowledge, I haven't heard anyone else asking for this, so I think it's okay to take our time.

**Comment by RussTedrake** [comment]
I will close this until we make further progress.  Please re-open if and when we proceed.

**Pull request closed without merging**
