### PR TITLE
[geometry] Introduce AddDeformableDeformableContactSurface()

### PR DESCRIPTION
**Pull request by DamrongGuoy**
- Introduce query_result's AddDeformableDeformableContactSurface().
- Introduce proximity's AddDeformableDeformableContactSurface().
- Refactor field_intersection to support both hydroelastics and deformables.

Relates #19704

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please.

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

+@xuchenhan-tri for feature review, please.

The major refactoring is in `field_intersection.`  Now it looks like this:
```
class VolumeIntersector {
  IntersectFields():  for both deformables and hydroelastics
  IntersectCompliantVolumes(): for hydroelastics
}
ComputeContactSurfaceFromCompliantVolumes(): for hydroelastics
```
and `deformable_field_intersection` has only one function (compared to multiple functions in the first prototype):
```
AddDeformableDeformableContactSurface(): calls IntersectFields()
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-:-NjA_RaE07D0djHywTa8:bd1qi2d)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

**Review by xuchenhan-tri — COMMENTED** [review]
Feature pass done with mostly minor comments. PTAL, thanks!

> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-:-NjFMnbR1SFWyAWM-x6g:bj1sj9s)* status: 8 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers

___
*[`geometry/proximity/deformable_field_intersection.cc` line 73 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjF84Bw8EditWvYLKRB:-NjF84Bw8EditWvYLKRC:bxen86u) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/proximity/deformable_field_intersection.cc#L73)):*
> ```cpp
>   for (int f = 0; f < num_faces; ++f) {
>     signed_distances_at_contact_points.push_back(
>         contact_field_W->EvaluateCartesian(
> ```

BTW, probably worth noting here that the gradient of the field has been computed so this is cheap.
___
*[`geometry/proximity/field_intersection.h` line 145 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjF1UJn5Ztcs6-7wckO:-NjF1UJn5Ztcs6-7wckP:b-1ladun) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/proximity/field_intersection.h#L145)):*
> ```objc
>    @param[out] surface_01_M  The output mesh of the contact surface between
>                         the two geometries expressed in frame M. The surface
>                         normal is in the direction of increasing field0 and
> ```

This comment about surface normal reads ambiguous to me in the abstract. It could very well be that the increasing direction of field 0 and the decreasing direction of 1 are opposite in certain cases. It's probably better to be precise when giving the definition and then provide an example for intuition.
___
*[`geometry/proximity/field_intersection.h` line 188 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjFEbjS7sjbJf1zTiMP:-NjFEbjS7sjbJf1zTiMQ:b850hmi) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/proximity/field_intersection.h#L188)):*
> ```objc
>                          MeshBuilder. It is expressed in World frame.
>                          If there is no contact, nullptr is returned.  */
>   void IntersectCompliantVolumes(
> ```

I think that this function doesn't belong to this class because it is specific to hydroelastics and the class itself generic and is agnostic of what the scalar fields are. I wonder if it makes more sense to kick this function to a derived class specific to hydro, like `HydroelasticVolumeIntersector`.
___
*[`geometry/proximity/field_intersection.cc` line 224 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjFIgKb6Eopd3diKQhX:-NjFIgKb6Eopd3diKQhY:b-wiujed) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/proximity/field_intersection.cc#L224)):*
> ```cpp
>   }
>   const int num_new_faces = builder_M->AddPolygon(
>       polygon_vertex_indices, polygon_nhat_M, field0_M.EvaluateGradient(tet0));
> ```

BTW, per f2f, this is contradicting the expectation from the documentation of `AddPolygon`. Obviously out of the scope of this PR. Putting a note here in case you want to address this in a future PR.



_Code quote:_
```cpp
  const int num_new_faces = builder_M->AddPolygon(
      polygon_vertex_indices, polygon_nhat_M, field0_M.EvaluateGradient(tet0));
```
___
*[`geometry/query_results/deformable_contact.h` line 338 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjEzqm46jQq1GyYyhbz:-NjEzqm46jQq1GyYyhc-:bk1ik9f) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/query_results/deformable_contact.h#L338)):*
> ```objc
>      These values are non-positive. Note that there is one signed distance
>      value per contact point and the i-th signed distance corresponds to the
>      i-th element in the contact mesh.
> ```

nit, it's not clear from this doc what the definition of "penetration distance is. It's also not clear where the sdf is being sampled (at the contact point defined as the centroid of each polygon in `contact_mesh_W`. These should be elaborated.

Once you defined "contact points", then you can use it instead of "centroids of contact polygons" later in the doc.



_Code quote:_
```objc
     _Approximate_ signed distances of penetration sampled on `contact_mesh_W`.
     These values are non-positive. Note that there is one signed distance
     value per contact point and the i-th signed distance corresponds to the
     i-th element in the contact mesh.
```
___
*[`geometry/query_results/deformable_contact.h` line 367 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjEz9DE-Vuav41tYCtm:-NjEz9DE-Vuav41tYCtn:bbco8bm) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/query_results/deformable_contact.h#L367)):*
> ```objc
>       const std::unordered_set<int>& participating_vertices1,
>       PolygonSurfaceMesh<T> contact_mesh_W, std::vector<T> signed_distances,
>       std::vector<Vector4<int>> contact_vertex_indexes0,
> ```

nit Prefer "indices" over "indexes". It hasn't made into the styleguide yet, but it is now the agreed-upon spelling of the word.



_Suggestion:_
```objc
contact_vertex_indices0
```
___
*[`geometry/query_results/deformable_contact.cc` line 158 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjF-srXEzZl9sSUlICI:-NjF-srXEzZl9sSUlICJ:bb6ssgc) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/query_results/deformable_contact.cc#L158)):*
> ```cpp
>     std::vector<Vector4<T>> barycentric_coordinates0,
>     std::vector<Vector4<T>> barycentric_coordinates1) {
>   DRAKE_DEMAND(static_cast<int>(signed_distances.size()) ==
> ```

BTW,



_Suggestion:_
```cpp
ssize(signed_distances)
```
___
*[`geometry/query_results/deformable_contact.cc` line 166 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjF0FRPCcmxsB24AARp:-NjF0FRPCcmxsB24AARq:beghmac) ([raw file](https://github.com/RobotLocomotion/drake/blob/079b9e348c26aecf07d330083c63ed9010a775fd/geometry/query_results/deformable_contact.cc#L166)):*
> ```cpp
>   DRAKE_DEMAND(static_cast<int>(barycentric_coordinates0.size()) ==
>                contact_mesh_W.num_faces());
>   DRAKE_DEMAND(static_cast<int>(barycentric_coordinates1.size()) ==
> ```

BTW, can we add the assertion that id0 and id1 are registered?

**Review by xuchenhan-tri — COMMENTED** [review]
-(release notes: feature) +(release notes: none)  Deformable is still not mentioned yet for release notes.
:lgtm: 
+@EricCousineau-TRI for platform review per rotation please.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-:-NjOXoja52RIlglGWZq5:b43887a)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`geometry/proximity/field_intersection.h` line 211 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjOX7hk8tXc-EFbhktA:-NjOX7hk8tXc-EFbhktB:bw966k8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e697bfca51c01aafa2438bd1a33b65d939a16af3/geometry/proximity/field_intersection.h#L211)):*
> ```objc
>  @tparam BvType
>    The type of bounding volumes for the tetrahedra. It can be Obb
>    for hydroelastics or Aabb for deformables.  */
> ```

minor, Deformable is no longer relevant in the context of this class.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform!

> Reviewed 1 of 10 files at r1, 3 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-:-NjOtQixCQdNnL48rBaM:b-vtj4w1)* status: 1 unresolved discussion

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20514)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform)

___
*[`geometry/proximity/field_intersection.h` line 211 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjOX7hk8tXc-EFbhktA:-NjPWtfx-5xiX1b9jhOo:bfubra0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e697bfca51c01aafa2438bd1a33b65d939a16af3/geometry/proximity/field_intersection.h#L211)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

minor, Deformable is no longer relevant in the context of this class.
</blockquote></details>

Done.  Thanks. I forgot about it.

Ideally, I should remove this tparam.  I'll do that in a subsequent PR.

**Comment by DamrongGuoy** [comment]
*[`geometry/proximity/field_intersection.h` line 211 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20514#-NjOX7hk8tXc-EFbhktA:-NjPleWUAYHVRKzBYPPN:b9gdkks) ([raw file](https://github.com/RobotLocomotion/drake/blob/e697bfca51c01aafa2438bd1a33b65d939a16af3/geometry/proximity/field_intersection.h#L211)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  Thanks. I forgot about it.

Ideally, I should remove this tparam.  I'll do that in a subsequent PR.
</blockquote></details>

Subsequent PR #20555

**Pull request merged**
