### PR TITLE
sensors: Add/update doxygen block diagrams

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #9496

Add missing diagrams, update others for consistency, and fix a text wrapping
problem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(priority: low) +@RussTedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194#-:-MqRH9838sMU0H5486iX:b-53jbcg)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194#-:-Mr7NzoU9aW2txRldznV:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Comment by RussTedrake** [comment]
___
*[systems/sensors/beam_model.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16194#-Mr7Pkc2CpH7kYTOI-tv:-Mr7Pkc32sTil4DbbzBE:b-xorzg) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcff6aed1e76eef9fe6a43b732c08c493f55415/systems/sensors/beam_model.h#L51)):*
> ```objc
> /// - hit
> /// - short
> /// - uniform
> ```

btw  -- these are random input ports.  it might be worth denoting them as such here?  (we expect them to be connected to a RandomSource, potentially automatically with AddRandomInputs: https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1systems.html#a0545ab65838b464875abb7385495531a

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/sensors/beam_model.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16194#-Mr7Pkc2CpH7kYTOI-tv:-Mr8XsjT12rOPr6JeP5q:b-1o4gxm) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcff6aed1e76eef9fe6a43b732c08c493f55415/systems/sensors/beam_model.h#L51)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw  -- these are random input ports.  it might be worth denoting them as such here?  (we expect them to be connected to a RandomSource, potentially automatically with AddRandomInputs: https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1systems.html#a0545ab65838b464875abb7385495531a
</blockquote></details>

There's a some description of the ports in the previous paragraphs. Maybe I should add a @code example showing use of AddRandomInputs? I don't have all the details ready to hand, but could add that as a follow-up pr.

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review, Monday schedule.

Here's a link to the guidelines I'm trying to follow: https://github.com/RobotLocomotion/drake/issues/9496#issuecomment-989274411

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194#-:-Mr8Yi4tD1vGP8MP5gke:b139s9n)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194#-:-Mr8wfjc-z6fQ-jnhzmd:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

___
*[systems/sensors/beam_model.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16194#-Mr7Pkc2CpH7kYTOI-tv:-Mr8v3wY3i_PDCllmhGs:bqht0g0) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcff6aed1e76eef9fe6a43b732c08c493f55415/systems/sensors/beam_model.h#L51)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

There's a some description of the ports in the previous paragraphs. Maybe I should add a @code example showing use of AddRandomInputs? I don't have all the details ready to hand, but could add that as a follow-up pr.
</blockquote></details>

My $2e-2 is to agree with @rpoyner-tri about a `@code` block being the best way the show the intended use case of features.  We don't have enough code examples in our documentation.

The disadvantage is that when the code sneaks into the pydrake docs it looks weird.  But too much code is a problem we can address when we have it :-)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194)* status: 1 unresolved discussion (waiting on @rpoyner-tri)

___
*[systems/sensors/beam_model.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16194#-Mr7Pkc2CpH7kYTOI-tv:-Mr8ycbQ380T2RnyRGTz:blokxii) ([raw file](https://github.com/robotlocomotion/drake/blob/8dcff6aed1e76eef9fe6a43b732c08c493f55415/systems/sensors/beam_model.h#L51)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

My $2e-2 is to agree with @rpoyner-tri about a `@code` block being the best way the show the intended use case of features.  We don't have enough code examples in our documentation.

The disadvantage is that when the code sneaks into the pydrake docs it looks weird.  But too much code is a problem we can address when we have it :-)
</blockquote></details>

I'll add a TODO here for "AddRandomInputs() @code example"  and come back around in another PR.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16194)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri)

**Pull request merged**
