### PR TITLE
Changes constructors of NotSoGoodVector and NoteQuiteGoodVector to be `{}` instead of `= default`.

### LINKED ISSUE #5327: Mysterious Build Error on OS X:  default initialization of an object of const type Foo without a user-provided default constructor
I am using 839b6e017bba05f92aaf6dc95f308c374f99d333 on OSX and building using `bazel`.

# The Error

```
ERROR: /Users/liang/dev/drake-distro-3/drake/systems/framework/BUILD:491:1: C++ compilation of rule '//drake/systems/framework:value_checker_test' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_liang/3302fbe3d4d2eae8487460393c40acaf/bazel-sandbox/8bbfb44b-02d0-4354-8ae2-f5e5a3578d43-7/sandbox.sb ... (remaining 70 argument(s) skipped).
drake/systems/framework/test/value_checker_test.cc:66:25: error: default initialization of an object of const type 'const drake::systems::(anonymous namespace)::NotSoGoodVector' without a user-provided default constructor
  const NotSoGoodVector not_so_good;
                        ^
                                   {}
drake/systems/framework/test/value_checker_test.cc:67:28: error: default initialization of an object of const type 'const drake::systems::(anonymous namespace)::NotQuiteGoodVector' without a user-provided default constructor
  const NotQuiteGoodVector not_quite_good;
                           ^
                                         {}
2 errors generated.
```

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #5327.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5328)

### CODE REVIEW

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.

**Comment by jwnimmer-tri** [comment]
:lgtm: if it passed the mac build.

Though FWIW, I don't think the comments are necessary.  "If you change this, the compiler will barf" is a statement for CI to enforce, not comments.

**Comment by liangfok** [comment]
Alright, I'll remove the comments after the current CI completes. Whoa...historically, `mac-clang-bazel-experimental` could take up to 4 hours to complete!

https://drake-jenkins.csail.mit.edu/view/Experimental/job/mac-clang-bazel-experimental/buildTimeTrend

**Comment by liangfok** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please.

**Pull request merged**
