### PR TITLE
py perception: Update point set notation for point cloud concatenation

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Minor Python tweaks / fixes

Follow-up to #11932

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11947)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
(Adding `low` priority because it's not an urgent matter, but would be nice to have some level of resolution - even if brief - for nested indexing / lists...)

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI this is six month stale -- can we either push it over the finish line, or close it?

**Comment by EricCousineau-TRI** [comment]
Thank you! I've responded to your mtg invite, and will be able to dig in a bit more on Friday.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/perception.py, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11947#-M3ED0Sv2ffCoj16pxYF:-M3Sal72Eoxm56mXBj4B:b-wllh4h) ([raw file](https://github.com/robotlocomotion/drake/blob/43fbe96e903a2a97803bc00cf3206c4a745cabe2/bindings/pydrake/systems/perception.py#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

AFAICT, this addresses the separate clouds and frames via (Unicode) subscripts, transformations using the final frame `F`, and concatenation by removing the subscript.

I think that addresses this use case; however, it won't really help in the future when the *sets of points* change (e.g. I remove 5 points from cloud A and add them to cloud B; what do I call the clouds now?).

I think the question for me is, do we care about that case? If not, then I'm cool with the current rendition -- possibly even using Sean's abbreviate `cloud` (since I wouldn't really distinguish `point_cloud` vs `cloud` anyways).
</blockquote></details>

Per f2f with Sean + Paul, mutating `cloud`s A and B just needs to be documented, or renamed.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/perception.py, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11947#-M3ED0Sv2ffCoj16pxYF:-M3SbD0w8CU043TaNL1Q:b-bq6a91) ([raw file](https://github.com/robotlocomotion/drake/blob/43fbe96e903a2a97803bc00cf3206c4a745cabe2/bindings/pydrake/systems/perception.py#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per f2f with Sean + Paul, mutating `cloud`s A and B just needs to be documented, or renamed.
</blockquote></details>

For `point_cloud` vs `cloud`: Keep `point_cloud` for public API / docs (where the type is not specifically called `PointCloud`), but do not penalize usage of `cloud` for internal stuff.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/perception.py, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11947#-M3Sc7O08ZvjlJfWPt3N:-M3Sc7O11K5cEyad-4tv:b-v5xjp4) ([raw file](https://github.com/robotlocomotion/drake/blob/43fbe96e903a2a97803bc00cf3206c4a745cabe2/bindings/pydrake/systems/perception.py#L60)):*
> ```Python
> 
>         @system{
>           @input_port{point_cloud_CiSi_id0}
> ```

Possible example rendition for current discussion:
```
@input_port{point_cloud0_C0} --  or -- {point_cloudi_Ci_id0} ???
```

Though per f2f, @seancurtis-tri's wants to avoid polluting caller's frame names (making abstract collide with concrete), and rely on documentation to define context. (Python is a counter-example, but... meh)
Per that, should genericize port names:

```
@input_port{point_cloud_id0}
@input_port{rigid_transform_id0}
...
@output_port{point_cloud}
```

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/perception.py, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11947#-M3Sj6f45cW4EhY8o_Y3:-M3Sj6f45cW4EhY8o_Y4:bn0wsg4) ([raw file](https://github.com/robotlocomotion/drake/blob/6f5ea0d6d2363d200d74327fde8bbbdb68325d12/bindings/pydrake/systems/perception.py#L51)):*
Original wording:

> The RGB color of each point in point_cloud_F depends on the color of the associated point in point_cloudₒ_Bₒ. If absent, a default color is provided.

Suggested reword:

> The output point cloud will be guaranteed to have per-point RGB colors: each output point's color will either be the corresponding input point's color or the default color (if none is provided).

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/systems/perception.py, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/11947#-M3ED0Sv2ffCoj16pxYF:-M3Sk4V70IZLsUppSde_:b-lzoloa) ([raw file](https://github.com/robotlocomotion/drake/blob/43fbe96e903a2a97803bc00cf3206c4a745cabe2/bindings/pydrake/systems/perception.py#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For `point_cloud` vs `cloud`: Keep `point_cloud` for public API / docs (where the type is not specifically called `PointCloud`), but do not penalize usage of `cloud` for internal stuff.
</blockquote></details>

Also, could strip out (or put in parenthesis):
`where point_cloud₁_F is measured and expressed in frame F`

**Comment by EricCousineau-TRI** [comment]
@mitiguy Might you have time to review this in the next week?

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
This PR is six months stale. If it's no longer being worked, please close it.

**Comment by jwnimmer-tri** [comment]
Thanks for your interest in contributing to Drake! Since this PR has not received any updates over the past 6+ months, we are closing it automatically. To resume the PR again, you may reopen it with updates (be sure to reopen before you push any changes), or open a new one.

**Pull request closed without merging**
