### PR TITLE
Added a System 2.0 Vector Interface for LCM messages and a Concrete Instantiation of It.

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards supporting LCM Input and Output Systems based on the System 2.0 framework. For now I placed `lcm_vector_interface.h` inside the spring_mass demo's directory since this is still experimental code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2729)

### CODE REVIEW

**Comment by liangfok** [comment]
From now till Tuesday +@russtedrake for both levels of review.
Starting on Wednesday +@jwnimmer-tri for both levels of review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLhRRG0z0CahcQz6F5Q:1417243982)*

**Comment by liangfok** [comment]
Actually, +@sherm1 for feature review (no rush).

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLhSl_R8-nvSQHtFCa6:-702637366)*

**Comment by liangfok** [comment]
Clang-MAC CI failed with the following error:

```
17:17:20 [ 89%] Linking C executable ../../bin/bot-param-dump
17:17:20 ld: file too small (length=0) file '/Users/yosemite/workspace/experimental/5403bcc7/build/lib/liblcmtypes_bot2-core.a' for architecture x86_64
17:17:20 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here is the log:
https://drake-jenkins.csail.mit.edu/job/experimental/2460/compiler=clang,label=mac/consoleFull

Investigating...

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLmpmKvqk9J3lOQ41Pn:-197432851)*

**Comment by liangfok** [comment]
The `clang-mac` failure is due to #2736. Thus, this PR is ready for review.

**Comment by RussTedrake** [comment]
Looks really nicely done! 

---

Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/lcmtypes/CMakeLists.txt, line 35 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-KLuWjv2d7mryXrcI-KR:-KLuWjv3uZMCJukJxyur:656077489) ([raw file](https://github.com/robotlocomotion/drake/blob/99a07e7e55f82ce83f75b9e0b351679a03f6e6e5/drake/lcmtypes/CMakeLists.txt#L35)):*
> ```CMake
>   lcmt_simple_car_state_t.lcm
>   lcmt_simulation_command.lcm
>   lcmt_spring_mass_state_t.lcm
> ```

Note that I also provided https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_drake_signal.lcm as a generic signal which can be used by our simple examples to avoid having to make a brand new lcm type everytime.  We might consider using that here.

In fact, I think that a vast majority of signals flying around in drake could get away with this interface.  It's only the rare cases when we need more speed or readability in the lcm type that it's useful to generate a robot-specific message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLuXPrctVKswnVKjksX:601114227)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
I have several design-level defects with this PR:

(1) Poor separation of concerns.  With this class design, LCM-ness of a _Vector_ type is intrinsic to that type, for all users of that type.  Instead, we should be able to layer on LCM-ness over existing `VectorInterface` subclasses, without having to reimplement the entirety of the type.  This is evident in `SpringMassLCMVector` copy-pasting almost the entirety of `BasicVector`.

(2) Bloated code in header files.  By putting method bodies in header files, we are going to hurt compile times.  It is not difficult to rephrase this design so that the set of types is closed under compilation, so that we can move things into `.cc` files.

(3) Useless virtual / template mix-n-match complexity.  There are virtual Encode/Decode methods, template'd on `LCMMessageType` -- why?  For a given `LCMMessageType`, will there really ever be multiple, runtime-selectable implementations of Encode and Decode?  In other words, why does `LCMVectorInterface` exist at all in its current form?

Also a meta-style nit:

(4) Per https://google.github.io/styleguide/cppguide.html#Function_Names, all types and functions and etc here should be named as `Lcm` not `LCM`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLwWZC19PJfzVy9h7eY:1912356390)*

**Comment by jwnimmer-tri** [comment]
Also,

(5) That we need a `spring_mass_lcm_vector_test` indicates an imposing forecast of technical debt, if we elect to keep this design.  It seems unsustainable to have to write that level of test for such simple, frequently-occurring code (every single signal in every single system).  It is a consequence of (1) and (3) above, I think.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLwYyuKc7Z5lhBkGSsE:306079253)*

**Comment by jwnimmer-tri** [comment]
I'm unclear on what you're trying to ask, but #2737 provides the larger design picture for this PR, in case that helps.

**Comment by liangfok** [comment]
@jwnimmer-tri: My immediate plan is to replace `SpringMassLCMVector` with a newly defined `LcmSignalVector` that specializes `LcmVectorInterface` to the existing [lcmt_drake_signal](https://github.com/RobotLocomotion/drake/blob/master/drake/lcmtypes/lcmt_drake_signal.lcm) message. Since this one specialization will likely satisfy the vast majority of signals in Drake, would this alleviate to concern about future technical debt?

Also, I was thinking subclasses of `LcmVectorInterface` and their associated LCM message definitions and unit tests could be automatically generated based on higher level message specifications. Would such a generator be worthwhile? Isn't this what the [Car's generator](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/Cars/lcm_vector_gen.py) is doing?

@sherm1: Perhaps subclassing `VectorInterface` and implementing `Encode()` and `Decode()` methods enables the creation of a generic [LCMInputSystem](https://github.com/RobotLocomotion/drake/pull/2737/files#diff-dbedc6dd0128e30a8e39e6664e486f14R41) that simply calls [Encode()](https://github.com/RobotLocomotion/drake/pull/2737/files#diff-dbedc6dd0128e30a8e39e6664e486f14R105) to covert received LCM messages into an output? I haven't implemented it yet but I anticipate a generic `LCMOutputSystem` to call `Decode()` to convert a `VectorInterface` into an LCM message that can then be published.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLx2ywXtmrWolRKH3AF:1290747795)*

**Comment by jwnimmer-tri** [comment]
> @jwnimmer-tri: My immediate plan is to replace SpringMassLCMVector with a newly defined LcmSignalVector that specializes LcmVectorInterface to the existing lcmt_drake_signal message. Since this one specialization will likely satisfy the vast majority of signals in Drake, would this alleviate to concern about future technical debt?

No.  First, I disagree that we should be mapping all LCM signals to that one message.  For toy examples and throwaways, it's convenient and fine, but that level of message tooling is unacceptable for durable, professional use.  Second, it sounds like `LcmSignalVector` would still reimplement `BasicVector`, rather than reusing it.  Third, that doesn't solve the separation of concerns defect (1) -- the design requirement should be to take any existing _Vector_ from a system, and map it onto an LCM message, without having re-implement it (which it sounds like `LcmSignalVector` design would still require).

> Also, I was thinking subclasses of LcmVectorInterface and their associated LCM message definitions and unit tests could be automatically generated based on higher level message specifications. Would such a generator be worthwhile? Isn't this what the Car's generator is doing?

Yes, I think generator code would be great.   But assuming we have that, most of the abstractions in this PR (or the hypothetical `LcmSignalVector` PR) would be of little or no value -- if we are already generating per-message code, then the templates and virtual dispatch don't help.  (Aside: generating unit tests is not really useful; we should unit test the generator, not its products.)

> @sherm1: Perhaps subclassing VectorInterface and implementing Encode() and Decode() methods enables the creation of a generic LCMInputSystem that simply calls Encode() to covert received LCM messages into an output? I haven't implemented it yet but I anticipate a generic LCMOutputSystem to call Decode() to convert a VectorInterface into an LCM message that can then be published.

By putting the message's typename into a template parameter, we are introducing additional compiler typechecking ceremony, that both makes it harder for us to use LCM, and harder to get code out of header files.

**Comment by sherm1** [comment]
> I'm unclear on what you're trying to ask, but #2737 provides the larger design picture for this PR

Thanks @jwnimmer-tri. That helps. In that case I'm asking: why does the `LcmInputSystem` have to output a vector whose type has "Lcm" in it? I would have thought it could absorb all the Lcm-ness of the input signal and sanitize it into an Lcm-free numerical vector.

Then beyond that, I'm asking whether we need abstract VectorInterfaces for Input and Output at all. In progress we have: every System block has multiple InputPort and OutputPort objects. The value for each port can be either a VectorInterface or an AbstractValue. I understand why the AbstractValue is abstract! But what do we gain with VectorInterface as opposed to just `VectorX<scalar>`?

**Comment by jwnimmer-tri** [comment]
> ... why does the LcmInputSystem have to output a vector whose type has "Lcm" in it? I would have thought it could absorb all the Lcm-ness of the input signal and sanitize it into an Lcm-free numerical vector.

Because, due to poor separation of concerns per my (1) above, the serialization details of the LCM message are implemented on the specific _Vector_ subclass directly, instead of through a serialization adapter.  I agree this is undesirable.

> Then beyond that, I'm asking whether we need abstract VectorInterfaces for Input and Output at all...

I'm not sure why that is a discussion for this PR.  Isn't that a fundamental concept in System 2.0?  Why reopen that design debate here -- is there some relationship to the LCM design that is motivating that thought?

**Comment by sherm1** [comment]
> I'm not sure why that is a discussion for this PR. Isn't that a fundamental concept in System 2.0?

Yes. The reason it came up here is that the VectorInterface is being extended. If this were a good thing to do, that would answer my question and justify the abstraction. I have yet to see a reason for this abstraction to exist and I thought this might be an example. I agree the general design debate belongs elsewhere.

**Comment by jwnimmer-tri** [comment]
>> I'm not sure why that is a discussion for this PR. Isn't that a fundamental concept in System 2.0?

> Yes. The reason it came up here is that the VectorInterface is being extended. If this were a good thing to do, that would answer my question and justify the abstraction...

Ah, makes sense, thanks.  Unfortunately, I don't think this is a meritorious example case.

**Comment by liangfok** [comment]
To ensure I understand, does the following design address all of the above-mentioned concerns?

* Do not extend `drake::systems::VectorInterface` or `drake::systems::BasicVector`.
* Create an `drake::systems::LCMInputSystem<T>` that extends `drake::systems:: SystemInterface<T>` and maintain enough internal state to be able to (1) extract information from the `SystemOutput<T>` parameter in its [EvalOutput(...)](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/system_interface.h#L61) method and (2) package this information in an LCM message, which it then publishes.

My initial reaction is achieving a general `drake::systems::LCMInputSystem<T>` for all System 2.0 Vector and LCM messages types may not be possible, meaning we may need to specialize it to a particular System 2.0 Vector and LCM message type. I'm OK with this, just wanted to make sure I understand.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2729#-:-KLxeekcMcjqGg0FpF0u:-1168926761)*

**Comment by jwnimmer-tri** [comment]
> Do not extend drake::systems::VectorInterface or drake::systems::BasicVector.

I am not sure where this is coming from.  It's likely that extending `BasicVector` will be an important part of reducing the amount of code we need.

> Create an drake::systems::LCMInputSystem.T that extends drake::systems:: SystemInterface.T and maintain enough internal state to be able to (1) extract information from the SystemOutput.T parameter in its EvalOutput(...) method and (2) package this information in an LCM message, which it then publishes.
>
> My initial reaction is achieving a general drake::systems::LCMInputSystem.T for all System 2.0 Vector and LCM messages types may not be possible, meaning we may need to specialize it to a particular System 2.0 Vector and LCM message type.

First -- to be clear on terms, I am assuming:
- LcmOutputSystem
 - publishes LCM messages
 - has 1 drake InputPorts in its Context
 - has 0 drake OutputPorts its SystemOutput 
 - in EvalOutput, uses the data found in its Context's input port to encode and publish an LCM message as a side-effect
- LcmInputSystem
 - subscribes to LCM messages
 - has 0 drake InputPorts in its Context
 - has 1 drake OutputPorts its SystemOutput 
 - in EvalOutput, uses the mostly recently decoded LCM message to set a value on its OutputPort

The quoted paragraph did not seem consistent with that terminology.

Second, it should be entirely possible to have a fully non-templated and non-virtual implementation of LcmInputSystem and LcmOutputSystem that support any message type the user desires.  As promised in email, I can whiteboard the design this week.

**Comment by sherm1** [comment]
> in EvalOutput, uses the data found in its Context's input port to encode and publish an LCM message as a side-effect

I don't think that should be a side effect. If the System has no OutputPorts then there should be no need to call its `EvalOutput()` method. Instead it should have an LcmOutputSystem-specific method that is invoked to obtain the LCM message, something like `EvalLcmMessage()`.

**Comment by liangfok** [comment]
I was just looking at the [API of drake::systems::Context](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_context.html) and don't see any notion of an "output" port. Is an output port the same as an input port?

**Comment by RussTedrake** [comment]
They are definitely not the same!  Input ports are part of the context (required for computation), output ports are not.  The only part of the system that has to think about the output ports is the EvalOutputs method.

**Comment by liangfok** [comment]
Thanks, I now see that the notion of an "OutputPort" is defined in [drake::systems::framework/system_output.h](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/system_output.h) and that it is an output parameter of [drake::systems::SystemInterface](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/system_interface.h#L61).

**Comment by liangfok** [comment]
Here's my latest design idea that does not reply on templates or virtual implementation of `LcmInputSystem` and `LcmOutputSystem`. Basically, the idea is to enumerate various hard-coded relationships between `drake::systems::VectorInterface` types and LCM messages types. Allow the user to select which of these relationships to use as an input argument to the constructor of the `LcmInputSystem` and `LcmOutputSystem`.

**Comment by liangfok** [comment]
> > in EvalOutput, uses the data found in its Context's input port to encode and publish an LCM message as a side-effect

> I don't think that should be a side effect. If the System has no OutputPorts then there should be no need to call its EvalOutput() method. Instead it should have an LcmOutputSystem-specific method that is invoked to obtain the LCM message, something like EvalLcmMessage().

Does this mean the solver needs to know whether a particular system is one that interacts with an LCM network? Or, should all systems have an `EvalLcmMessage()` method, which is only implemented by systems that interact with an LCM network? If it's the latter, which I prefer, we should probably call it something more generic like `EvalMiddlewareCommunication()` so it can also cover, for example, ROS  connectivity.

**Comment by RussTedrake** [comment]
here is a proposal (potentially to be shot down):
- the solver only needs to know about time.   it calls dynamics and output methods according to the simulation clock.  sometimes simulation time needs to be slaved to real time, sometimes not. 
- an LCM application has the additional responsibility (beyond the solver, or a wrapper on the solver) to start up a receive thread for incoming lcm messages, and to register the lcm components of the system as listeners.  
- the message handler routines, which should be implemented by each individual lcm system, can be called at any time, and must be thread safe because they could be called during an evaluation of dynamics and/or output.  it is the system's responsibility to, e.g., lock/unlock a mutex.
- we provide a generic lcmInput system which implements the above in a way that's sufficient for most use cases, and simply spools the content of the most recently received message on it's output port.

**Comment by sherm1** [comment]
I agree with Russ that LCM and other middleware should be invisible to the time-advancing Solver which has enough to worry about dealing only with the System abstraction (time, parameters, input/output, continuous/discrete/modal state, event isolation and response). Any concrete System is likely to provide its own set of additional useful methods; Solver doesn't need to know about those.

> Input ports are part of the context (required for computation), output ports are not.  The only part of the system that has to think about the output ports is the EvalOutputs method.

That does describe the current code but that isn't quite done yet. In order to properly cache output calculations the Context's cache needs to hold memory in which to hold the results with EvalOutput returning a reference to that memory. That also prevents copying from Output-to-Input in system diagrams and provides a place to track dependents for invalidation.

**Comment by liangfok** [comment]
I just met F2F with @jwnimmer-tri and have a new design that does not rely on templates. I will thus close this PR and open a new one with the updated design.

**Pull request closed without merging**
