### PR TITLE
[workspace] Upgrade petsc to latest release v3.19.0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #19137.

Our patches no longer apply and need to be updated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Oops, I also just belatedly realized -- if you expect to remove this dependency soon, another option would be to exclude it from the "monthly upgrades" list by adding it to here:

https://github.com/RobotLocomotion/drake/blob/3ad75c0efdd6b92356a43bb83240114a2675037f/tools/workspace/new_release.py#L54

In that case, our monthly upgrade process would skip over it.

I'm OK either way.

**Review by xuchenhan-tri — COMMENTED** [review]
I'm hoping to remove it in Q2 but it may be delayed as it depends on my progress on the sparse algebra research. Let's upgrade this one more time since I've already done it?
-(status: do not merge) +(release notes: fix) +@mwoehlke-kitware for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NSw9wZ04e-CVZ0omotv:b-jnktyj)* status: LGTM missing from assignees mwoehlke-kitware,xuchenhan-tri(platform), labeled "do not merge" (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
It appears CI is unhappy?
```
tools/workspace/petsc/stubs/petscconf.h:165:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
```

**Review by xuchenhan-tri — COMMENTED** [review]
CI fixed. PTAL, thanks! @mwoehlke-kitware 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NTF8Bh4BJPiaZqrP2T0:b-ojcrd4)* status: LGTM missing from assignees mwoehlke-kitware,xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)* status: 2 unresolved discussions, LGTM missing from assignees mwoehlke-kitware,xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`tools/workspace/petsc/patches/petsc_creationidx_keyval.patch` line 18 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFBkx7E__CefzLogkW:-NTFBkx7E__CefzLogkX:bcf5kgl) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petsc_creationidx_keyval.patch#L18)):*
> ```Diff
> @@ -34,10 +34,6 @@ PetscObjectId PetscObjectNewId_Internal(void)
>  */
>  PetscErrorCode PetscHeaderCreate_Private(PetscObject h, PetscClassId classid, const char class_name[], const char descr[], const char mansec[], MPI_Comm comm, PetscObjectDestroyFunction destroy, PetscObjectV    iewFunction view)
> ```

Er... what's going on here? This doesn't look like valid code.
___
*[`tools/workspace/petsc/patches/petscimpl.patch` line 24 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFCaouEJHt35r9sbby:-NTFCaouEJHt35r9sbbz:b-n43iji) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petscimpl.patch#L24)):*
> ```Diff
> +  atomic_int            atomic_namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
> +  PetscMPIInt           *iflags;          /* length of comm size, shared by all calls to PetscCommBuildTwoSided_Allreduce/RedScatter on this comm */
> +  struct PetscCommStash *comms;           /* communicators available for PETSc to pass off to other packages */
> ```

I would encourage not having more churn in the patch than is necessary. In fact, it's not clear why this alteration to the patch is even necessary?

Suggestion:



_Suggestion:_
```Diff
+  atomic_int            atomic_tag;       /* next free tag value */
+  atomic_int            atomic_refcount;  /* number of references, communicator can be freed when this reaches 0 */
+  atomic_int            atomic_namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
   PetscMPIInt           *iflags;    /* length of comm size, shared by all calls to PetscCommBuildTwoSided_Allreduce/RedScatter on this comm */
   struct PetscCommStash *comms;     /* communicators available for PETSc to pass off to other packages */
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)* status: 1 unresolved discussion, LGTM missing from assignees mwoehlke-kitware,xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`tools/workspace/petsc/patches/petscimpl.patch` line 24 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFCaouEJHt35r9sbby:-NTFU4861nHBfvwZoAM0:b5cpupw) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petscimpl.patch#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The old patch doesn't apply anymore. The intention of the change here is to preserve the original behavior of the patch with minimal changes.
</blockquote></details>

...but AFAICT the changes to the first hunk of the patch aren't necessary. It used to just add some lines. Now it adds some lines and changes some whitespace in some existing lines. The latter isn't necessary and makes both the patch itself, as well as the changes to the patch, more complicated. That seems to miss the "minimal changes" goal? :slightly_smiling_face: 

This seems to work just fine:
```diff
--- include/petsc/private/petscimpl.h
+++ include/petsc/private/petscimpl.h
@@ -5,6 +5,7 @@
 #ifndef PETSCIMPL_H
 #define PETSCIMPL_H
 #include <petscsys.h>
+#include <stdatomic.h>

 /* SUBMANSEC = Sys */

@@ -1317,9 +1318,9 @@ struct PetscCommStash {
   PetscCommDuplicate(), PetscCommDestroy(), PetscCommGetNewTag(), PetscObjectGetName()
 */
 typedef struct {
-  PetscMPIInt            tag;       /* next free tag value */
-  PetscInt               refcount;  /* number of references, communicator can be freed when this reaches 0 */
-  PetscInt               namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
+  atomic_int            atomic_tag;       /* next free tag value */
+  atomic_int            atomic_refcount;  /* number of references, communicator can be freed when this reaches 0 */
+  atomic_int            atomic_namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
   PetscMPIInt           *iflags;    /* length of comm size, shared by all calls to PetscCommBuildTwoSided_Allreduce/RedScatter on this comm */
   struct PetscCommStash *comms;     /* communicators available for PETSc to pass off to other packages */
 } PetscCommCounter;
@@ -1456,9 +1457,9 @@ static inline PetscErrorCode PetscSpinlockDestroy(PetscSpinlock *omp_lock)
 }
   #else
     #if defined(__cplusplus)
-      #error "Thread safety requires either --download-concurrencykit, std::atomic, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #else
-      #error "Thread safety requires either --download-concurrencykit, stdatomic.h, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #endif
   #endif
```

I'm also somewhat on the fence whether the last hunk shouldn't just delete the `#if defined(__cplusplus)`...`#endif` and replace it with a single `#include <petsc_drake_pthread.h>`. One could argue that either way. :shrug:

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: assuming CI is still happy.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NTF_7ayEjXT3iLSC9GT:b-xd8sxi)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @xuchenhan-tri)

___
*[`tools/workspace/petsc/patches/petscimpl.patch` line 24 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFCaouEJHt35r9sbby:-NTF_1WR4rYUZJ3tl1jX:b-tx2gbm) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petscimpl.patch#L24)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...but AFAICT the changes to the first hunk of the patch aren't necessary. It used to just add some lines. Now it adds some lines and changes some whitespace in some existing lines. The latter isn't necessary and makes both the patch itself, as well as the changes to the patch, more complicated. That seems to miss the "minimal changes" goal? :slightly_smiling_face: 

This seems to work just fine:
```diff
--- include/petsc/private/petscimpl.h
+++ include/petsc/private/petscimpl.h
@@ -5,6 +5,7 @@
 #ifndef PETSCIMPL_H
 #define PETSCIMPL_H
 #include <petscsys.h>
+#include <stdatomic.h>

 /* SUBMANSEC = Sys */

@@ -1317,9 +1318,9 @@ struct PetscCommStash {
   PetscCommDuplicate(), PetscCommDestroy(), PetscCommGetNewTag(), PetscObjectGetName()
 */
 typedef struct {
-  PetscMPIInt            tag;       /* next free tag value */
-  PetscInt               refcount;  /* number of references, communicator can be freed when this reaches 0 */
-  PetscInt               namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
+  atomic_int            atomic_tag;       /* next free tag value */
+  atomic_int            atomic_refcount;  /* number of references, communicator can be freed when this reaches 0 */
+  atomic_int            atomic_namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
   PetscMPIInt           *iflags;    /* length of comm size, shared by all calls to PetscCommBuildTwoSided_Allreduce/RedScatter on this comm */
   struct PetscCommStash *comms;     /* communicators available for PETSc to pass off to other packages */
 } PetscCommCounter;
@@ -1456,9 +1457,9 @@ static inline PetscErrorCode PetscSpinlockDestroy(PetscSpinlock *omp_lock)
 }
   #else
     #if defined(__cplusplus)
-      #error "Thread safety requires either --download-concurrencykit, std::atomic, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #else
-      #error "Thread safety requires either --download-concurrencykit, stdatomic.h, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #endif
   #endif
```

I'm also somewhat on the fence whether the last hunk shouldn't just delete the `#if defined(__cplusplus)`...`#endif` and replace it with a single `#include <petsc_drake_pthread.h>`. One could argue that either way. :shrug: 
</blockquote></details>

Better; thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/petsc/patches/petscimpl.patch` line 24 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFCaouEJHt35r9sbby:-NTFZ6wk1UO9FWQbGH9P:b-dz44w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petscimpl.patch#L24)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

...but AFAICT the changes to the first hunk of the patch aren't necessary. It used to just add some lines. Now it adds some lines and changes some whitespace in some existing lines. The latter isn't necessary and makes both the patch itself, as well as the changes to the patch, more complicated. That seems to miss the "minimal changes" goal? :slightly_smiling_face: 

This seems to work just fine:
```diff
--- include/petsc/private/petscimpl.h
+++ include/petsc/private/petscimpl.h
@@ -5,6 +5,7 @@
 #ifndef PETSCIMPL_H
 #define PETSCIMPL_H
 #include <petscsys.h>
+#include <stdatomic.h>

 /* SUBMANSEC = Sys */

@@ -1317,9 +1318,9 @@ struct PetscCommStash {
   PetscCommDuplicate(), PetscCommDestroy(), PetscCommGetNewTag(), PetscObjectGetName()
 */
 typedef struct {
-  PetscMPIInt            tag;       /* next free tag value */
-  PetscInt               refcount;  /* number of references, communicator can be freed when this reaches 0 */
-  PetscInt               namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
+  atomic_int            atomic_tag;       /* next free tag value */
+  atomic_int            atomic_refcount;  /* number of references, communicator can be freed when this reaches 0 */
+  atomic_int            atomic_namecount; /* used to generate the next name, as in Vec_0, Mat_1, ... */
   PetscMPIInt           *iflags;    /* length of comm size, shared by all calls to PetscCommBuildTwoSided_Allreduce/RedScatter on this comm */
   struct PetscCommStash *comms;     /* communicators available for PETSc to pass off to other packages */
 } PetscCommCounter;
@@ -1456,9 +1457,9 @@ static inline PetscErrorCode PetscSpinlockDestroy(PetscSpinlock *omp_lock)
 }
   #else
     #if defined(__cplusplus)
-      #error "Thread safety requires either --download-concurrencykit, std::atomic, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #else
-      #error "Thread safety requires either --download-concurrencykit, stdatomic.h, or --with-openmp"
+      #include <petsc_drake_pthread.h>
     #endif
   #endif
```

I'm also somewhat on the fence whether the last hunk shouldn't just delete the `#if defined(__cplusplus)`...`#endif` and replace it with a single `#include <petsc_drake_pthread.h>`. One could argue that either way. :shrug: 
</blockquote></details>

Done. I missed your point. I had manually made the equivalent changes in my local petsc repo and acquired new patches. You are right that the changes I made isn't minimal. I adopted the proposed patch, thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NTF_IUcD_1Uk64qj4qc:bf6cf0i)* status: LGTM missing from assignees xuchenhan-tri(platform),SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)* status: LGTM missing from assignees SeanCurtis-TRI(platform),xuchenhan-tri(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, 3 of 6 files at r2, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NTFc47G4BhunvIn7A65:bmxilld)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186)* status: LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

___
*[`tools/workspace/petsc/patches/petscimpl.patch` line 24 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-NTFCaouEJHt35r9sbby:-NTFnVqk3237NpYY_paO:bba3k24) ([raw file](https://github.com/RobotLocomotion/drake/blob/0468754f13bce8543fd71823afe825702d923df5/tools/workspace/petsc/patches/petscimpl.patch#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done. I missed your point. I had manually made the equivalent changes in my local petsc repo and acquired new patches. You are right that the changes I made isn't minimal. I adopted the proposed patch, thanks!
</blockquote></details>

...and I managed to acknowledge the fix before your last comment :slightly_smiling_face:. Thanks again! Now, let's hope this reply makes Reviewable happy...

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19186#-:-NTFrhri9g-99nKrTYUO:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),mwoehlke-kitware,xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
