### PR TITLE
Cleanup pkg-config path for ibex

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14109)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14109#-:-MHrDXFs3q5OnlatxbOP:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
+@rpoyner-tri for platform-review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14109#-:-MHrDsZR4kDc5spjSyck:b3bzloe)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14109#-:-MHrJV2PCjz1jIJwRfZa:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jamiesnape (waiting on @rpoyner-tri)

**Pull request merged**
