### PR TITLE
Sparse add linear constraint

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. I am requesting help with how to add the python binding.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-Ng_CE1y1fgD4-lVf_P9:bopxb48)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1468 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0GLk1JwelgYz2PqL:-Nga0GLk1JwelgYz2PqM:bhmplb8) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1468)):*
> ```objc
>    * of the decision variables (defined in the vars parameter).
>    *
>    * @pydrake_mkdoc_identifier{4args_A_lb_ub_dense}
> ```

The `A` matrix is sparse but the identifier says it is dense?
___
*[`solvers/mathematical_program.h` line 1482 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0PWj0wQevGdtD58O:-Nga0PWj0wQevGdtD58P:b-lr360o) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1482)):*
> ```objc
>    * of the decision variables (defined in the vars parameter).
>    *
>    * @exclude_from_pydrake_mkdoc{Not bound in pydrake.}
> ```

Why not to bind this function in pydrake?
___
*[`solvers/mathematical_program.h` line 1532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0YiF6iAeCS2NVUTo:-Nga0YiF6iAeCS2NVUTp:bnzn9hh) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1532)):*
> ```objc
>       const Eigen::Ref<const VectorXDecisionVariable>& vars) {
>     return AddLinearConstraint(
>         Eigen::Map<const Eigen::MatrixXd>(a.data(), 1, a.size()), Vector1d(lb),
> ```

Why making this change?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1468 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0GLk1JwelgYz2PqL:-Nga7Py21hMJCULNDp16:b-ou0lts) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1468)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The `A` matrix is sparse but the identifier says it is dense?
</blockquote></details>

This was put in the wrong spot. Done.
___
*[`solvers/mathematical_program.h` line 1482 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0PWj0wQevGdtD58O:-Nga7UBoEEtfYQbtrG4B:b-bwbv0t) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1482)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why not to bind this function in pydrake?
</blockquote></details>

I switched the tags by accident. Good catch.
___
*[`solvers/mathematical_program.h` line 1532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0YiF6iAeCS2NVUTo:-Nga7Wqr73S5PkniHcp1:b-7j5nyx) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1532)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why making this change?
</blockquote></details>

Eigen needs to be told how to disambiguate between the dense and sparse matrix overload for some reason. My guess is that this has to do with `Eigen::Ref`. This makes the choice explicit and allows the code to compile

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0YiF6iAeCS2NVUTo:-NgdOUh29IiGYHL02Yfn:b-gs05lw) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1532)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Eigen needs to be told how to disambiguate between the dense and sparse matrix overload for some reason. My guess is that this has to do with `Eigen::Ref`. This makes the choice explicit and allows the code to compile
</blockquote></details>

If the newly-added ambiguity breaks this call site, it will probably break downstream users' call sites as well.  More work is probably needed here.  (You could lean on the platform reviewer to help debug it, you don't need to do it on your own.)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm:  +@jwnimmer-tri for platform review please since you already looked at this PR.

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-Ngggm9yEIXT-TL7c46z:bubh0pt)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
@hongkai-dai could you sign off again as there is the new feature of checking whether the linear constraint already has the dense view.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-Ngv78mg7ugKCvp4Ccau:b1bh24c)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 9 of 13 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/constraint.h` line 670 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgvgTd18c2X2kDvQBjC:-NgvgTd18c2X2kDvQBjD:b2c6njh) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/solvers/constraint.h#L670)):*
> ```objc
>   /** Returns true iff this constraint already has a dense representation, i.e,
>    * if GetDenseA() will be cheap. */
>   bool HasDenseA() const;
> ```

Sorry I don't get why we need this function. Is it only used in the unit test, but not in any other `cc` file?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/constraint.h` line 670 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgvgTd18c2X2kDvQBjC:-Ngw3NA3DM4IRmdGWtzm:bvv2o79) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/solvers/constraint.h#L670)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't get why we need this function. Is it only used in the unit test, but not in any other `cc` file?
</blockquote></details>

Just saw the slack discussion. Retract my comment.

**Review by jwnimmer-tri — COMMENTED** [review]
I've posted a few typos below.  I'll return in the morning to finish reading the remainder.

> Reviewed 11 of 13 files at r5, all commit messages.
> Dismissed @hongkai-dai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-Ngw61ua5tK2tNG5r0wz:b6vimjo)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.h` line 1532 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Nga0YiF6iAeCS2NVUTo:-Ngw4Tt0Dkm1YpzS3w5Q:b-z4tmv5) ([raw file](https://github.com/RobotLocomotion/drake/blob/78c4e45efff85a39c02245bc580a34413335f393/solvers/mathematical_program.h#L1532)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the newly-added ambiguity breaks this call site, it will probably break downstream users' call sites as well.  More work is probably needed here.  (You could lean on the platform reviewer to help debug it, you don't need to do it on your own.)
</blockquote></details>

Done (dismissing Hongkai).
___
*[`solvers/mathematical_program.h` line 1773 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Ngw4een1JZ_lGGUVEET:-Ngw4eeoAq7KkZsSK9Hg:b-1r4546) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/solvers/mathematical_program.h#L1773)):*
> ```objc
>    * @endcode
>    *
>    * @pydrake_mkdoc_identifier{3args_A_b_dense}
> ```

BTW This isn't necessarily wrong, but would it be better to name this `...Aeq_beq...` to match the arg names instead of `...A_b...`?

Ditto just below.
___
*[`solvers/sparse_and_dense_matrix.h` line 46 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Ngw37nc0qCwE52LyhiN:-Ngw37nc0qCwE52LyhiO:b-kmrgby) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/solvers/sparse_and_dense_matrix.h#L46)):*
> ```objc
> 
>   // Returns true if the dense matrix has been constructed.
>   [[nodiscard]] bool dense_is_constructed() const;
> ```

nit For clarity and consistency, we always put the "is" first when that word a verb and the function returns a `bool`.



_Suggestion:_
```objc
is_dense_constructed
```
___
*[`bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc` line 945 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Ngw5GcX4LuRmIGMK04Y:-Ngw5GcYDFnz706eFCTl:bvh2hci) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc#L945)):*
> ```cpp
>               &MathematicalProgram::AddLinearEqualityConstraint),
>           py::arg("a"), py::arg("beq"), py::arg("vars"),
>           doc.MathematicalProgram.AddLinearConstraint.doc_4args_a_lb_ub_vars)
> ```

These arg names and the docstring don't seem to line up correctly.



_Code quote:_
```cpp
          py::arg("a"), py::arg("beq"), py::arg("vars"),
          doc.MathematicalProgram.AddLinearConstraint.doc_4args_a_lb_ub_vars)
```
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 10 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Ngw3TBTEks_erTyYg_K:-Ngw3TBTEks_erTyYg_L:b-ni7jws) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/bindings/pydrake/solvers/test/evaluators_test.py#L10)):*
> ```Python
> from pydrake.autodiffutils import InitializeAutoDiff
> from pydrake.common.test_utilities.deprecation import catch_drake_warnings
> import scipy.sparse
> ```

nit The scipy import is third-party, so should move up alongside the other third-party import (numpy) around line 5.

(The `import typing` is in the wrong place too; it should be with the standard library imports (`import unittest`) near the top.  It doesn't matter whether or not you fix that here at the same time.  The important thing is that we don't make anything _worse_ in this PR.)
___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 107 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-Ngw3iah5ZmWw1wtZito:-Ngw3iaiDudOzrWOE7Tc:b-avpfdp) ([raw file](https://github.com/RobotLocomotion/drake/blob/91a4a73c4c831bebff7f410773309a6b2384815b/bindings/pydrake/solvers/test/evaluators_test.py#L107)):*
> ```Python
>     def test_linear_constraint(self):
>         A_sparse = scipy.sparse.csc_matrix(
>             (np.array([2, 1., 3]), np.array([0, 1, 0]),
> ```

typo

(https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals)

Ditto on line 783 in mathematicalprogram_test.py.



_Suggestion:_
```Python
1
```

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 18 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-NgyEGFw8sICMZhgogTu:bnfp4nl)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/test/mathematical_program_test.cc` line 807 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgyD6EaErseQamfSyyk:-NgyD6EaErseQamfSyyl:bywdpd0) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d18bb0cbca305a5930c33f51336f40435d2989/solvers/test/mathematical_program_test.cc#L807)):*
> ```cpp
> }
> 
> // Return True if all the elements of the matrix m1 and m2 are EqualTo as
> ```

nit GSG https://drake.mit.edu/styleguide/cppguide.html#Function_Comments



_Suggestion:_
```cpp
Returns
```
___
*[`solvers/test/mathematical_program_test.cc` line 1284 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgyDGIL8LOvm9LPYDxF:-NgyDGIL8LOvm9LPYDxG:b-w0k5a2) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d18bb0cbca305a5930c33f51336f40435d2989/solvers/test/mathematical_program_test.cc#L1284)):*
> ```cpp
>   std::vector<Eigen::Triplet<double>> A_triplet_list;
>   A_triplet_list.reserve(3 * (n - 2) + 4);
>   double ctr = 1;
> ```

nit _Do not abbreviate by deleting letters within a word._

-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

Ditto throughout the new code below.



_Suggestion:_
```cpp
count
```
___
*[`solvers/test/mathematical_program_test.cc` line 1309 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgyDhTA6oxKqRWEdUaO:-NgyDhTA6oxKqRWEdUaP:bh0vpkh) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d18bb0cbca305a5930c33f51336f40435d2989/solvers/test/mathematical_program_test.cc#L1309)):*
> ```cpp
>   const MatrixX<Expression> Ax{(constraint_ptr->GetDenseA() * var_vec)};
>   const VectorX<Expression> lb_in_ctr{constraint_ptr->lower_bound()};
>   const VectorX<Expression> ub_in_ctr{constraint_ptr->upper_bound()};
> ```

nit I don't know what `in_ctr` is trying to say here?  It is supposed to be "in constraint"?

Ditto in the similar code down below.

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-:-NgyiENnD2EVMia5sn5V:bm9o57a)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/test/mathematical_program_test.cc` line 1309 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/20361#-NgyDhTA6oxKqRWEdUaO:-Ngyhlt2BLDOHGMzFclL:b7rbyka) ([raw file](https://github.com/RobotLocomotion/drake/blob/d2d18bb0cbca305a5930c33f51336f40435d2989/solvers/test/mathematical_program_test.cc#L1309)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I don't know what `in_ctr` is trying to say here?  It is supposed to be "in constraint"?

Ditto in the similar code down below.
</blockquote></details>

Changed them all in the file.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20361)* status: missing label for release notes (waiting on @AlexandreAmice)

**Pull request merged**
