### PR TITLE
'Fix' sphinx to get __init__ documentation.

### LINKED ISSUE #11954: pydrake doc sphinx: Constructors missing in Python 3 CI job?
Was looking at `AxisAngle`, and saw that `__init__` docs weren't being shown:
https://drake.mit.edu/pydrake/pydrake.common.eigen_geometry.html#pydrake.common.eigen_geometry.AngleAxis_.AngleAxis_[float]

Same thing for stuff from `pydrake.math`:
https://drake.mit.edu/pydrake/pydrake.math.html#pydrake.math.RigidTransform_.RigidTransform_[float]

Going to try building locally.
Was this due to some upgrade? They used to show up...

EDIT: Would like to see if we can resolve this by 2019/09/13.

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Resolves #11954

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12452)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
+@EricCousineau-TRI for feature review, please.

**Comment by EricCousineau-TRI** [comment]
TBH, I would say that this effectively resolves the issue relevant to our needs, so we can close the issue once this is resolved.

I'll see if I can make a brief, pure `pybind11` reproduction that illustrates this issue, and then we can just post that as a `pybind11` issue.

**Comment by m-chaturvedi** [comment]
I could make the issue, if you're fine with it.

**Comment by EricCousineau-TRI** [comment]
Sounds good. Let me see if I can make the repro in another 5min, then you can use that in posting the issue.

**Comment by EricCousineau-TRI** [comment]
Longer than 5min, but posted it to the issue. Thanks!

**Comment by EricCousineau-TRI** [comment]
I've updated this PR to "Resolves" rather than "Relates".

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/doc/pydrake_sphinx_extension.py, line 249 at r2](https://reviewable.io/reviews/robotlocomotion/drake/12452#-LvfgJkF7VSnFupT5jdb:-LvfpWYZ04spUQO3e61Q:b-2mfbak) ([raw file](https://github.com/robotlocomotion/drake/blob/257cc621b11e5001a1c669b17ecca3fdfac7e08d/bindings/pydrake/doc/pydrake_sphinx_extension.py#L249)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It's better to have `#11954` as one word, but meh.
</blockquote></details>

Done.  I guess you mean searchability doesn't always align with readability, :).

**Pull request merged**
