### PR TITLE
Add symbolic Jacobian

### PR DESCRIPTION
**Pull request by soonho-tri**
Related issue : #4421

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5264)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-:-KdatIRmP6CkuqSYXss_:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/common/symbolic_expression.cc, line 809 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb15Lhi1ZP98_qMbSI:-Kdb15Lhi1ZP98_qMbSJ:b7l8dtm) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.cc#L809)):*
> ```cpp
>   for (int i = 0; i < n; ++i) {
>     for (size_t j = 0; j < m; ++j) {
>       J(i, j) = f[i].Differentiate(vars[j]);
> ```

This is so clean, love it!

---

*[drake/common/symbolic_expression.h, line 814 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb-Kl4QyfaIYcUJiJq:-Kdb-Kl4QyfaIYcUJiJr:b-hhoxo4) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L814)):*
> ```objc
> 
> /// Computes the Jacobian matrix J of the vector function @p f with respect to
> /// @p vars. J(i,j) contains ∂f(i)/∂var(j).
> ```

∂vars(j)

---

*[drake/common/symbolic_expression.h, line 816 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb-VkHWunFR82lnv4P:-Kdb-VkHWunFR82lnv4Q:b-16s2el) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L816)):*
> ```objc
> /// @p vars. J(i,j) contains ∂f(i)/∂var(j).
> //
> //  For example, Jacobian([x * y * z, y^2, x + z], {x, y, z}) returns the
> ```

In the example, can we add the non-polynomial form, like `sin(x + 2 * y)`.

---

*[drake/common/symbolic_expression.h, line 823 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0gKft-pf6RcLSa_Z:-Kdb0gKft-pf6RcLSa__:bcpq5q7) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L823)):*
> ```objc
> //    |      1         0         1|
> //  </pre>
> MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>> f,
> ```

`const Eigen::Ref<const VectorX<Expression>>&`, missing an `&`, as explained in https://eigen.tuxfamily.org/dox-devel/classEigen_1_1Ref.html

---

*[drake/common/symbolic_expression.h, line 824 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0A5MRXyFWmLKf0qQ:-Kdb0A5MRXyFWmLKf0qR:brxy2em) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L824)):*
> ```objc
> //  </pre>
> MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>> f,
>                              const std::vector<Variable>& vars);
> ```

What if `vars` have repeated entries, like `{x, x, y}`? Maybe throw an error if that happens?

---

*[drake/common/symbolic_expression.h, line 825 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0XjDjYsHP-barfDS:-Kdb0XjDjYsHP-barfDT:b-trn89p) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L825)):*
> ```objc
> MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>> f,
>                              const std::vector<Variable>& vars);
> }  // namespace symbolic
> ```

Can we also provide a function 
```C++
MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>>& f, const Eigen::Ref<const VectorX<Variable>>& vars);
```
That the second argument is an Eigen vector?

---

*[drake/common/test/symbolic_expression_jacobian_test.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb1S7w7DF1JNoQEabo:-Kdb1S7xu-59hEB40kLl:b-yiblgl) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/test/symbolic_expression_jacobian_test.cc#L87)):*
> ```cpp
>   // clang-format on
> 
>   EXPECT_EQ(Jacobian(f, {x_, y_}), expected);
> ```

As a sanity check, can we add a test, that the expression does not contain the variable being differentiated with? For example
```
Jacobian([x * y + sin(x)], {x, z})
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264)*

**Comment by soonho-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 814 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb-Kl4QyfaIYcUJiJq:-Kdb3wGzCncWbBBuwipu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L814)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

∂vars(j)
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.h, line 816 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb-VkHWunFR82lnv4P:-Kdb4DT8n3FIWuJ13etg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L816)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

In the example, can we add the non-polynomial form, like `sin(x + 2 * y)`.
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.h, line 823 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0gKft-pf6RcLSa_Z:-Kdb8Oc5b4SYiVM4CuMj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L823)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const Eigen::Ref<const VectorX<Expression>>&`, missing an `&`, as explained in https://eigen.tuxfamily.org/dox-devel/classEigen_1_1Ref.html
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.h, line 825 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0XjDjYsHP-barfDS:-Kdb8T2OMrZ-U4nMcPm8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L825)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we also provide a function 
```C++
MatrixX<Expression> Jacobian(const Eigen::Ref<const VectorX<Expression>>& f, const Eigen::Ref<const VectorX<Variable>>& vars);
```
That the second argument is an Eigen vector?
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_expression_jacobian_test.cc, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb1S7w7DF1JNoQEabo:-Kdb9VNURu8M5bTl5DLO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/test/symbolic_expression_jacobian_test.cc#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

As a sanity check, can we add a test, that the expression does not contain the variable being differentiated with? For example
```
Jacobian([x * y + sin(x)], {x, z})
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264)*

**Comment by soonho-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_expression.h, line 824 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0A5MRXyFWmLKf0qQ:-KdbG5x5YBxP5pbBqAZP:b-kb2ury) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L824)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

What if `vars` have repeated entries, like `{x, x, y}`? Maybe throw an error if that happens?
</blockquote></details>

Not sure that we need to take care of it here. Probably better to take care of it at a call-site?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_expression.h, line 824 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-Kdb0A5MRXyFWmLKf0qQ:-KdbJCsNXCI-1IgDK4dP:b-jwwhxc) ([raw file](https://github.com/robotlocomotion/drake/blob/3a6eefd12dd4802ac6655c2fd9a8d8473b1356d8/drake/common/symbolic_expression.h#L824)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Not sure that we need to take care of it here. Probably better to take care of it at a call-site?
</blockquote></details>

Never mind, even with the repeated entries this code still work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-:-KdbKth280gpQ-tx9yFv:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sammy-tri , platform-review please.

---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-:-KdbLDWEnp3SQyaZDGjF:bgsorw1)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5264#-:-Kdbb17Z4mbyk9AYjzEU:bnfp4nl)*

**Pull request merged**
