### PR TITLE
Make resource search folders absolute

### PR DESCRIPTION
**Pull request by fbudin69500**
Addresses #8225

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)

### CODE REVIEW

**Comment by fbudin69500** [comment]
@stonier Could you test this locally please, to see if it solves the error you had?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-:-L7f1_Kz3g5oUcNlTC1q:b9sd37)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[common/BUILD.bazel, line 582 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j61bi7PChQF8m-Is1:-L7j61bi7PChQF8m-Is2:b-aqgxd8) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/BUILD.bazel#L582)):*
> ```Python
> # `find_resource_relative_path`.
> drake_cc_binary(
>     name = "libfind_resource.so",
> ```

This name is misleading, because it matches the name of a real component, but it is not where `drake::FindResource` is implemented (`:find_resource`).

One solution would be to rename it `libfind_resource_test_example.so`, for example.

---

*[common/find_loaded_library.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j5n3NfjWnWMJInsJz:-L7j5n3NfjWnWMJInsK-:bgrzhq2) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L77)):*
> ```cpp
>       const char * pos_slash = strrchr(info[i].imageFilePath, '/');
>       if (!strcmp(pos_slash + 1, library_name.c_str())) {
>         // Path is always absolute on MacOS
> ```

BTW punc

---

*[common/find_loaded_library.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j5aIJ0osOsUXimOX3:-L7j5aIJ0osOsUXimOX4:bock92i) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L91)):*
> ```cpp
> // with relative directory to find resource files in drake install tree.
> // This function is specific to Linux.
> optional<string> LoadedLibraryPath(const std::string& library_name) {
> ```

The header file docs should be updated to promise an absolute path (because the calling code now relies on that assumption).

---

*[common/find_loaded_library.cc, line 107 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j5CoNSxGOi9VDbT4m:-L7j5CoPCHAqY7MidceP:b4bsg7i) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L107)):*
The handling of `buf` on success is wrong.  From the man page:

> readlink()  places  the contents of the symbolic link pathname in the buffer buf, which has size bufsiz.  readlink() does not append a null byte to buf.  It will truncate the contents (to a length of bufsiz characters), in case the buffer is too small to hold all of the contents... On  success, these calls return the number of bytes placed in buf.  On error, -1 is returned and errno is set to indicate the error.

Here, we handle neither adding of the nil byte, nor checking that the path actually fit.

---

*[common/find_resource.cc, line 290 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j5ht16u_sbEHbDPBW:-L7j5ht16u_sbEHbDPBX:b-k290bo) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_resource.cc#L290)):*
> ```cpp
>   // resource-root sentinel file.
>   candidate_dirs.emplace_back(FindSentinelDir());
> ```

Please add a fail-fast check here (looping), that all of the `candidate_dirs` are absolute.

---

*[common/test/find_resource_relative_path.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j6yt7xj8m37j1Ifho:-L7j6yt7xj8m37j1Ifhp:b-9gjk6i) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_relative_path.sh#L1)):*
> ```Shell
> # This test should only be invoked via Bazel.
> ```

I don't think the complexity of this script is warranted; there is way to much hard-coded stuff that is brittle with respect to our toolchains, plus hard-coding the list of third_party dependencies (which luckily so far are header-only).

I see that our installed demos and pydrake always seem to be absolute already, so maybe they can't be used to test.  I'd say try to get a repro recipe from Daniel and add it to shambhala as a regression test.

Additional / alternatively, a `ResolveExeRelativePath` helper could be easily unit tested without worrying about library linker paths, if that function were a helper rather than inlined into the library lookup code.

---

*[common/test/find_resource_test.cc, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j8Rus0cgt6BUZmcIv:-L7j8Rus0cgt6BUZmcIw:b-g4xnbr) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_test.cc#L103)):*
> ```cpp
>   // fail.
>   const std::string test_directory = "find_resource_test_scratch";
>   EXPECT_THROW(AddResourceSearchPath(test_directory), std::runtime_error);
> ```

If the `@throws` contract is unit tested, then it must be promised as part of the Doxygen API.

---

*[common/test/find_resource_test.cc, line 137 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j8DeoMo6DuOIaGQg-:-L7j8DeoMo6DuOIaGQg0:b-jq0nk9) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_test.cc#L137)):*
> ```cpp
>   char temp[PATH_MAX];
>   std::string cwd = getcwd(temp, PATH_MAX) ?
>                     std::string(temp) : std::string("");
> ```

The C++ mechanism to get the cwd is:
```c++
  spruce::path cwd;
  cwd.setAsCurrent();
```
If there is a reason that doesn't work here, it should be documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8369)*

**Comment by jamiesnape** [comment]
Review status: 4 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[common/test/find_resource_relative_path.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j6yt7xj8m37j1Ifho:-L7jEy8Aq5SC9cubxt9w:b-4nqlp5) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_relative_path.sh#L1)):*
> I see that our installed demos and pydrake always seem to be absolute already, so maybe they can't be used to test.  I'd say try to get a repro recipe from Daniel and add it to shambhala as a regression test.

Unless the repro also happens to be an exemplary usage of drake, it should not be in shambhala.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8369)*

**Comment by jwnimmer-tri** [comment]
*[common/test/find_resource_relative_path.sh, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8369#-L7j6yt7xj8m37j1Ifho:-L7jFwDZqaCM_1bnQK5w:b-5pwh3b) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_relative_path.sh#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

> I see that our installed demos and pydrake always seem to be absolute already, so maybe they can't be used to test.  I'd say try to get a repro recipe from Daniel and add it to shambhala as a regression test.

Unless the repro also happens to be an exemplary usage of drake, it should not be in shambhala.

</blockquote></details>

Fine by me.  The unit test is a better suggestion anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8369)*

**Comment by stonier** [comment]
> I see that our installed demos and pydrake always seem to be absolute already, so maybe they can't be used to test. I'd say try to get a repro recipe from Daniel and add it to shambhala as a regression test.

Reproduction is a little time consuming. Essentially:

1. Need a version of drake prior to the recent SONAME updates
2. A workspace configuration such as we were using for delphyne CI
3. Installation of the drake sources
4. A program that calls `find_resource` on the installed drake

I believe the key to getting a relative path popping out of all that was that the workspace configuration was in a home directory. Going to take me a while to set that up again - it was on the work pc, but I won't be back for a week.

**Comment by stonier** [comment]
Confirmed the problem and the fix from this branch on my home pc.

**Comment by fbudin69500** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[common/BUILD.bazel, line 582 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j61bi7PChQF8m-Is1:-LAZokPJBmCOieidjNW3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/BUILD.bazel#L582)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This name is misleading, because it matches the name of a real component, but it is not where `drake::FindResource` is implemented (`:find_resource`).

One solution would be to rename it `libfind_resource_test_example.so`, for example.
</blockquote></details>

Done.

---

*[common/find_loaded_library.cc, line 77 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j5n3NfjWnWMJInsJz:-LAZot1P9CC4nXeofGuI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW punc
</blockquote></details>

Done.

---

*[common/find_loaded_library.cc, line 91 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j5aIJ0osOsUXimOX3:-LAZpV2B2qU7cVBllC2j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The header file docs should be updated to promise an absolute path (because the calling code now relies on that assumption).
</blockquote></details>

Done.

---

*[common/find_loaded_library.cc, line 107 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j5CoNSxGOi9VDbT4m:-LAZqnzy2ErV4enDzEtv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L107)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The handling of `buf` on success is wrong.  From the man page:

> readlink()  places  the contents of the symbolic link pathname in the buffer buf, which has size bufsiz.  readlink() does not append a null byte to buf.  It will truncate the contents (to a length of bufsiz characters), in case the buffer is too small to hold all of the contents... On  success, these calls return the number of bytes placed in buf.  On error, -1 is returned and errno is set to indicate the error.

Here, we handle neither adding of the nil byte, nor checking that the path actually fit.
</blockquote></details>

Done.

---

*[common/find_resource.cc, line 290 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j5ht16u_sbEHbDPBW:-LAZtFam-oTw-ryFqVv0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_resource.cc#L290)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please add a fail-fast check here (looping), that all of the `candidate_dirs` are absolute.
</blockquote></details>

Done.

---

*[common/test/find_resource_test.cc, line 103 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j8Rus0cgt6BUZmcIv:-LAZu8fwDuOvPV5SCAu0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_test.cc#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the `@throws` contract is unit tested, then it must be promised as part of the Doxygen API.
</blockquote></details>

Done.

---

*[common/test/find_resource_test.cc, line 137 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j8DeoMo6DuOIaGQg-:-LAZv7rwBk8p_XUTfQ_p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_test.cc#L137)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The C++ mechanism to get the cwd is:
```c++
  spruce::path cwd;
  cwd.setAsCurrent();
```
If there is a reason that doesn't work here, it should be documented.
</blockquote></details>

Done.

---

*[common/test/find_resource_relative_path.sh, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369#-L7j6yt7xj8m37j1Ifho:-LAZtHmZ8cCkpi0yi8fF:b-25hrkz) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/test/find_resource_relative_path.sh#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fine by me.  The unit test is a better suggestion anyway.
</blockquote></details>

If you have a good suggestion for a unit test, let me know. I am out of idea apart from this test that I am removing.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8369)*

**Comment by fbudin69500** [comment]
Review status: 3 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[common/find_loaded_library.cc, line 91 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8369#-L7j5aIJ0osOsUXimOX3:-LAtjqXq4rqYmToZI7rP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca9113d2681aa22a2f9daf6f8f52ad550a60e48/common/find_loaded_library.cc#L91)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The header file isn't fixed yet.
</blockquote></details>

Done.

---

*[common/find_loaded_library.cc, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAmJZ0H7ojNX4lP0NnN:-LAtk36m1biITI2SoTUV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f2d5d0d8d531e748669d5af881cb5d0797174dd2/common/find_loaded_library.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The second clause of this check seems weird / wrong?  I would have expected `&& readlink_res < PATH_MAX`.
</blockquote></details>

Done.

---

*[common/test/find_loaded_library_test.cc, line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAniIaiAIf__iSXZDlG:-LAtkOhX51neuqOcbMHv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/test/find_loaded_library_test.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We should test that the result is an absolute path, because that's part of our API contract for this method, and the purpose of this PR.
</blockquote></details>

Done.

---

*[common/BUILD.bazel, line 615 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAngjGu3G7tuhibgtU7:-LArvNTECozFVZk_t64Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/BUILD.bazel#L615)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Comment is stale?  I think `find_resource_relative_path` no longer exists.
</blockquote></details>

Done.

---

*[common/BUILD.bazel, line 622 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAnhCCL8wuHqRZp-sik:-LArvTRn0WOcs6EMMkI7:bhcsjqw) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/BUILD.bazel#L622)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW For clarity, please move this to be adjacent to the (one) unit test that uses it.
</blockquote></details>

Reverted to previous version. Linking this shared library was creating ODR violation.

---

*[common/BUILD.bazel, line 731 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAnhcWH9OD7WyH8oNfU:-LAtgPHT8sHoc1yw_GAe:b-3mnkhb) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/BUILD.bazel#L731)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This linking violates ODR for `//common:essential`.  Both `//common:libfind_resource_text_example.so` and `//common/test_utilities:drake_cc_googletest_main` each link to essential, separately.  Assuming that you need to have `:find_resource` linked into the example so, then the only recourse I see is to not use `drake_cc_googletest` and its `:drake_cc_googletest_main`, but rather to use `@gtest//:with_main` directly (or similar).
</blockquote></details>

Even if I simplify this, this will still need `@stx` to be linked both by `//common:essential` and ` //common:libfind_resource_text_example.s`. I  will revert to the previous implementation for this test, calling a dummy library.

---

*[common/BUILD.bazel, line 731 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAnhIaTDw4dy-vxozwM:-LAtjPY5DM_Ve2jQDEFf:bp3aow6) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/BUILD.bazel#L731)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I was initially confused how this linking worked.  I see now that the code under test is coming it from the shared library, which is why we have to list the header file here.

I suggest a small comment here explaining how this ends up being linked.
</blockquote></details>

Reverted.

---

*[common/test/find_resource_relative_path_test.cc, line 30 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAngJkXD_3UwCSggInI:-LAtj0psAWqLcB0YHddj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/common/test/find_resource_relative_path_test.cc#L30)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this file is dead code now?
</blockquote></details>

Done.

---

*[tools/workspace/stx/package.BUILD.bazel, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAngP_oEx0CNhnzkvXM:-LAtj1yk0FqRW3MylWJL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/595da0a6c391bb208b56509e044a2ff38c6e6b5d/tools/workspace/stx/package.BUILD.bazel#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this change is no longer needed now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)*

**Comment by jwnimmer-tri** [comment]
Reviewed 6 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/test/find_loaded_library_test.cc, line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAtsWGQ9tCKm4WFLeC-:-LAtsWGQ9tCKm4WFLeC0:b-jr6kb3) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/test/find_loaded_library_test.cc#L22)):*
> ```cpp
>   // loaded by the process.
>   optional<string> library_path = LoadedLibraryPath("lib_is_real.so");
>   EXPECT_EQ((*library_path)[0], '/');
> ```

BTW This would fail in a bad way in library_path was nullopt.  I suggest moving this after the EXPECT_TRUE immediately below, and changing that EXPECT_TRUE to ASSERT_TRUE so that the test would halt on nullopt.

---

*[common/test/find_resource_test.cc, line 17 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAtsp6E0buH57jDegLw:-LAtsp6E0buH57jDegLx:bfs9rbo) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/test/find_resource_test.cc#L17)):*
> ```cpp
> #else  // Not __APPLE__
> #include <linux/limits.h>
> #endif
> ```

BTW I think this ifdef-endif block is unused now?  As well as unistd.h above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@SeanCurtis-tri for platform review, please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369#-:-LAttte05UninFho26EZ:b-k6xj3z)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: And I second @jwnimmer-tri's BTWs (with an FYI of my own).

---

Reviewed 2 of 7 files at r2, 1 of 2 files at r3, 3 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/find_resource.cc, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAx6FsU4mWCqHSySGm9:-LAx6FsU4mWCqHSySGmA:b-mg8s6z) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/find_resource.cc#L294)):*
> ```cpp
>   // bugs, but in theory it should never happen as the code above should
>   // guard against it.
>   for (const auto& candidate_dir : candidate_dirs) {
> ```

FYI I find a disconnect between `const auto& candidate_dir` and `*candidate_dir`. Without looking at the greater context, I initially assumed that `candidate_dir` was a `unique_ptr`. Upon further inspection, I realized it was an `optional<string>`. In this case, I think the use of `auto` is *not* helping clarity. I'd recommend (without requiring), one of two options:

1. (my preference) replace `auto` with `optional<string>`
2. replace `*candidate_dir` with `candidate_dir.value()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369#-:-LAx7IrL6_MH8u48Xats:b-1g9wnr)*

**Comment by fbudin69500** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/find_resource.cc, line 294 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAx6FsU4mWCqHSySGm9:-LAxxBvc3D5gH1koB8rT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/find_resource.cc#L294)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I find a disconnect between `const auto& candidate_dir` and `*candidate_dir`. Without looking at the greater context, I initially assumed that `candidate_dir` was a `unique_ptr`. Upon further inspection, I realized it was an `optional<string>`. In this case, I think the use of `auto` is *not* helping clarity. I'd recommend (without requiring), one of two options:

1. (my preference) replace `auto` with `optional<string>`
2. replace `*candidate_dir` with `candidate_dir.value()`.
</blockquote></details>

Done.

---

*[common/test/find_loaded_library_test.cc, line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAtsWGQ9tCKm4WFLeC-:-LAxqiX51oF-_6k8fpfs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/test/find_loaded_library_test.cc#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This would fail in a bad way in library_path was nullopt.  I suggest moving this after the EXPECT_TRUE immediately below, and changing that EXPECT_TRUE to ASSERT_TRUE so that the test would halt on nullopt.
</blockquote></details>

Done.

---

*[common/test/find_resource_test.cc, line 17 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8369#-LAtsp6E0buH57jDegLw:-LAxqj-m0FYIwE4tWvYo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/25e8086ac004d3134a568a0149dd36153f6e922b/common/test/find_resource_test.cc#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I think this ifdef-endif block is unused now?  As well as unistd.h above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r2, 2 of 7 files at r4, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369#-:-LAxzc6XDJwOrdXd2zXn:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8369)*

**Pull request merged**
