### PR TITLE
Fix AutoDiff bug in unit vector code

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Hypothesis: Returning the squared norm is a _lot_ more trouble than its worth.

As I understand it, the return value is trying to be a micro-optimization for performance (so that the caller doesn't need to re-compute the squared norm in case they are going to re-normalize the argument), but in practice I don't expect such an optimization to matter very much at all.  Anyone who is re-normalizing their vector based on this return value is already going to be paying a lot of cycles to do that sqrt and division, and the overhead associated with returning the squared norm does not obviously trade off positively against the cost of recomputing it, given how pipelining works.

When you're contributing difficult-to-read code into Drake in order to make it run faster, then you need to _prove_ that the level of complexity is worthwhile with a benchmark.  I haven't seen any benchmarks in this journey yet.

A function like `NormalizeOrThrow` makes sense to me (maybe with an adjustable tolerance so the caller can decide how tight they want their margins to be, possibly a separate tolerance for throwing vs re-normalizing).  Returning the squared norm seems like premature optimization, and (apparently) a very difficult one to get right anyway.

Suggestion: Given up on this function.  It's wasting all of your reviewers time to keep trying to grok your misguided wanderings around the solution space.  The only two capabilities that calling code needs access to are (1) reject non-unit vectors and (2) re-normalize unit vectors subject to tolerance checks.  That's probably even just one utility function, with arguments.  In no case does the calling code care what the norm was, and certainly not the _gradient_ of the norm.

**Comment by sherm1** [comment]
My 2 cents: performance is not the issue here. What we are trying to achieve is an API where a user must provide a "reasonable" unit vector so we know we aren't looking at garbage, yet not so strict that we'll throw when given degraded unit vectors such as columns of a rotation matrix after several compositions. But ... further computations need to clean up those unit vectors so that the length is actually 1 and we don't continue to degrade the results. Normalizing unconditionally after the test doesn't throw would be possible though would likely cause expression bloat for symbolics and I would expect callers to forget to do it without some indication that it is necessary. The messy return here should signal to callers that they need to at least consider whether to normalize after ThrowIfNotUnitVector() returns without throwing, and retuning the normsqr gives them a basis for making that decision. No doubt other designs are possible.

In the meanwhile I think we should add the bug fix and missing unit test to the existing code.

**Comment by jwnimmer-tri** [comment]
> In the meanwhile I think we should add the bug fix and missing unit test to the existing code.

Nobody uses this return value, nor should they.  This API is ill-conceived and doesn't encapsulate anything properly.

So sure, it's embarrassing to have broken code.  We can change the function to return void, and now nothing is buggy.  Why should we invest time in gold-plating the wrong design?  We're going to delete this unit test later, when we delete this ill-conceived function.

> What we are trying to achieve is an API where a user must provide a "reasonable" unit vector so we know we aren't looking at garbage, yet not so strict that we'll throw when given degraded unit vectors such as columns of a rotation matrix after several compositions. But ... further computations need to clean up those unit vectors so that the length is actually 1 and we don't continue to degrade the results.

That is a fine goal.   This PR does _absolutely nothing useful_ towards that goal.  All is does is waste our time.

**Review by mitiguy — COMMENTED** [review]
I agree with what you are saying about the return value.  It is better to get rid of it.  It simplifies the PR (which is mostly the new test that is no longer needed).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-NiCNG5c3BZkfUfC47LV:b-6rpl7g)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-NiHHlha0jEvgeXn8bZI:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few typos

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-NiHaDfJ3Wy47jbXEjxu:b-u5vu31)* status: 4 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`math/test/unit_vector_test.cc` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_lJy7Na7fhx6G1vD:-NiH_lJy7Na7fhx6G1vE:b86pe24) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L52)):*
> ```cpp
>       expected_message);
> 
>   // Verify WarnIfNotUnitVector() returns true for a near valid unit vector.
> ```

nit: true -> false
___
*[`math/test/unit_vector_test.cc` line 56 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_r8O-g1fCLMPi2ag:-NiH_r8O-g1fCLMPi2ah:b37zyrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L56)):*
> ```cpp
>   EXPECT_FALSE(is_bad_unit_vector);
> 
>   // Verify WarnIfNotUnitVector() returns false for an invalid unit vector.
> ```

nit: false -> true
___
*[`math/test/unit_vector_test.cc` line 61 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_v9m98ljIicdhpAw:-NiH_v9m98ljIicdhpAx:b86pe24) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L61)):*
> ```cpp
>   EXPECT_TRUE(is_bad_unit_vector);
> 
>   // Verify WarnIfNotUnitVector() returns true for a symbolic unit vector.
> ```

nit: true -> false
___
*[`multibody/tree/unit_inertia.cc` line 87 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiHa2jsD0e9PPLzcaT6:-NiHa2jsD0e9PPLzcaT7:bvximma) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/multibody/tree/unit_inertia.cc#L87)):*
> ```cpp
>   //  argument to this function is either already normalized by the calling
>   //  function (so a const reference to a UnitVector is passed) or if the
>   //  calling function passes a Vector3, the Vector3 is automatrically converted
> ```

typo: automatrically

**Review by mitiguy — COMMENTED** [review]
Platform review +@jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-NiaRyH_2KArm3qJ26CG:b-sh0554)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`math/test/unit_vector_test.cc` line 52 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_lJy7Na7fhx6G1vD:-Ni_y-ObArYEDCnfUJrM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: true -> false
</blockquote></details>

Done.
___
*[`math/test/unit_vector_test.cc` line 56 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_r8O-g1fCLMPi2ag:-Ni_y6706V8ar_Ozse5k:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: false -> true
</blockquote></details>

Done.
___
*[`math/test/unit_vector_test.cc` line 61 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiH_v9m98ljIicdhpAw:-Ni_yBRm9AUzATDU3EDb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/math/test/unit_vector_test.cc#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: true -> false
</blockquote></details>

Done.
___
*[`multibody/tree/unit_inertia.cc` line 87 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NiHa2jsD0e9PPLzcaT6:-Ni_yQVoAm90EZr8tXIr:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/cb24a10d577f1e9cfedd01ae179ca4b36932ef09/multibody/tree/unit_inertia.cc#L87)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: automatrically
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
I'll pass this off to +@rpoyner-tri for tomorrow on-call.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-NifNbMTBMDQV2TGCNJz:bnfp4nl)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/unit_inertia.cc` line 89 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-NifLGDlAWH4ADe2k1d9:-NifLGDlAWH4ADe2k1dA:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/852fcc4adc3d3e2ae817e6014fd62716f73a6a91/multibody/tree/unit_inertia.cc#L89)):*
> ```cpp
>   //  calling function passes a Vector3, the Vector3 is automatically converted
>   //  to a UnitVector (throwing an exception if the Vector3 contains NaN or
>   //  infinite elements or its magnitude is increduluously small).
> ```

typo



_Suggestion:_
```cpp
incredulously
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20467#-:-Nig1f032qDn3CecMOEW:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
