### PR TITLE
Add FCL external

### PR DESCRIPTION
**Pull request by jamiesnape**
- Adds the [Flexible Collision Library](https://github.com/flexible-collision-library/fcl) (FCL) as an external.
- Adds a stubbed collision model that will use FCL and a basic integration test.

Obviously, much work to do implementing the model and adding more tests, but this is something to build upon.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3381)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
Upstreaming danfis/libccd#24 and flexible-collision-library/fcl#181.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
Upstreams have accepted necessary patches.

**Comment by sherm1** [comment]
> Upstreams have accepted necessary patches.

Awesome! Thanks, Jamie.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
Upstreaming flexible-collision-library/fcl#182 and OctoMap/octomap#137.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
FCL patch is in, waiting on the octomap patch.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-64-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for feature review and +@sherm1 for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot windows-msvc-32-experimental please
@drake-jenkins-bot windows-msvc-64-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by sherm1** [comment]
Thanks, @jamiesnape! A few comments -- PTAL. 

+@amcastro-tri can you take a quick look at this please?

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/collision/fcl_model.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBvI3pPAKHnu6-XUZp:-KTBvI3pPAKHnu6-XUZq:bbef2vs) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/fcl_model.h#L21)):*
> ```objc
> 
>   bool closestPointsAllToAll(const std::vector<ElementId>& ids_to_check,
>                              const bool use_margins,
> ```

`const` is meaningless here (in declaration), should be just `bool use_margins`. (and below) You can still use the const in the `.cc` implementation if you want; C++ considers that the same signature.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBuz1e4NyZ1NALoKYq:-KTBuz1e4NyZ1NALoKYr:bei2fvw) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L12)):*
> ```cpp
> 
> GTEST_TEST(FCLModelTest, Test) {
>   using namespace fcl;
> ```

Not allowed per styleguide -- just individual `using fcl::blah`s.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBv6E9e5CUZKGWMNWa:-KTBv6E9e5CUZKGWMNWb:b4cl3zg) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L19)):*
> ```cpp
> 
>   EXPECT_TRUE(v1.cross(v2).isApprox(v3));
>   EXPECT_DOUBLE_EQ(26.0, v1.dot(v2));
> ```

This looks like it's testing Eigen rather than FCL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KTBvfBf4kkrToyHcm1X:b-v5rbnu)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/collision/fcl_model.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBvI3pPAKHnu6-XUZp:-KTEkUri8bSbzoZPIdQ_:b2n1e3l) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/fcl_model.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> `const` is meaningless here (in declaration), should be just `bool use_margins`. (and below) You can still use the const in the `.cc` implementation if you want; C++ considers that the same signature.
</details>
True. I was idly copying the superclass... I will fix both.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBv6E9e5CUZKGWMNWa:-KTEkfkjByZxNURXDr7-:b5sxcdf) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This looks like it's testing Eigen rather than FCL?
</details>
Testing the wrapped versions really. I do not expect this test to persist once the model is implemented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381)*

**Comment by jamiesnape** [comment]
Review status: 8 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBv6E9e5CUZKGWMNWa:-KTErPfiGxs55HYEqonI:b-yzqpye) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Testing the wrapped versions really. I do not expect this test to persist once the model is implemented.
</details>
I will add something more meaningful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381)*

**Comment by amcastro-tri** [comment]
It looks great to get started. Just a few comments.

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/fcl_model.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTF8c03rjJw310EelrD:-KTF8c04q5MRh8hVZhdo:bj66pp0) ([raw file](https://github.com/robotlocomotion/drake/blob/e2af7828ccfd3e4e6d7f6a0597cc2bce1c3d130d/drake/systems/plants/collision/fcl_model.h#L19)):*
> ```objc
>   FCLModel() {}
>   virtual ~FCLModel() {}
> ```

BTW, Here missing override for `addElement()`. And I wonder if you could provide super basic functionality to add say a sphere so that we check it links correctly with FCL (and we can have a more FLC-like unit test in fcl_model_test.cc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KTF9BijSrkvCFv-0I41:byvb09e)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by SeanCurtis-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/collision/fcl_model.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTF8c03rjJw310EelrD:-KTKLp2hDG1y77u3Fxle:b-z930gh) ([raw file](https://github.com/robotlocomotion/drake/blob/e2af7828ccfd3e4e6d7f6a0597cc2bce1c3d130d/drake/systems/plants/collision/fcl_model.h#L19)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, Here missing override for `addElement()`. And I wonder if you could provide super basic functionality to add say a sphere so that we check it links correctly with FCL (and we can have a more FLC-like unit test in fcl_model_test.cc)
</details>
BTW, I'm comfortable with leaving that as an exercise for tying FCL into drake.  I believe the scope of this was getting FCL into the build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KTKM7A2QkOeG-UHMNRd:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
Review status: 8 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/collision/fcl_model.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBvI3pPAKHnu6-XUZp:-KTKhVisRlV1T_KeynHS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/fcl_model.h#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> True. I was idly copying the superclass... I will fix both.
</details>
Done.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 12 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBuz1e4NyZ1NALoKYq:-KTKhZItdLCf0zkfTOWc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Not allowed per styleguide -- just individual `using fcl::blah`s.
</details>
Done.

---

*[drake/systems/plants/collision/test/fcl_model_test.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTBv6E9e5CUZKGWMNWa:-KTKh_JaOM8HNhFRwfGY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c14dfb1c1fdeff4bb746d75b12bef24806b8e35e/drake/systems/plants/collision/test/fcl_model_test.cc#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I will add something more meaningful.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by sherm1** [comment]
-@amcastro-tri due to vacation (already reviewed)

---

Review status: 8 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KTKrw8j0sqrAmTicGb0:b-bevno2)*

**Comment by sherm1** [comment]
:lgtm: -- one comment, PTAL.

---

Reviewed 3 of 8 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/collision/bullet_model.h, line 153 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTKsBVsciy_PYBpelnZ:-KTKsBVsciy_PYBpeln_:bvzkzuf) ([raw file](https://github.com/robotlocomotion/drake/blob/10a985dc21955a50518841076219041d2c8410d5/drake/systems/plants/collision/bullet_model.h#L153)):*
> ```objc
>    */
>   virtual PointPair findClosestPointsBetweenElements(
>       const ElementId idA, const ElementId idB, bool use_margins);
> ```

BTW oops, the ElementIds also have a spurious `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KTKsgHVw0tsuezLDfU4:bo901ef)*

**Comment by jamiesnape** [comment]
Review status: 10 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/bullet_model.h, line 153 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTKsBVsciy_PYBpelnZ:-KTKuztquEMspBr6JNB7:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake/blob/10a985dc21955a50518841076219041d2c8410d5/drake/systems/plants/collision/bullet_model.h#L153)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW oops, the ElementIds also have a spurious `const`.
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
SEGFAULT.

**Comment by sherm1** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by amcastro-tri** [comment]
back from vacation. What's the status of this?. It'd be nice to get it merged!

**Comment by jamiesnape** [comment]
I need to sort out some Eigen alignment issues that are causing the test to SEGFAULT.

**Comment by jamiesnape** [comment]
Resolved merge conflicts.

**Comment by jamiesnape** [comment]
And more merge conflicts.

**Comment by amcastro-tri** [comment]
There still is a CI problem. Once solved this :lgtm: . Thanks!

---

Reviewed 2 of 12 files at r5.
Review status: 7 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/collision/fcl_model.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-KTF8c03rjJw310EelrD:-KUr9ELcUQr9YmyfdlBy:b-tnm8hw) ([raw file](https://github.com/robotlocomotion/drake/blob/e2af7828ccfd3e4e6d7f6a0597cc2bce1c3d130d/drake/systems/plants/collision/fcl_model.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary>
> BTW, I'm comfortable with leaving that as an exercise for tying FCL into drake.  I believe the scope of this was getting FCL into the build.
</details>
I agree, I will mark myself satisfied. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3381#-:-KUrAIF1mQgmRiMZZuxo:b-y4fa7v)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-gcc-experimental-ros please
@drake-jenkins-bot linux-gcc-ninja-experimental please

**Comment by jamiesnape** [comment]
Problem seems to be upstream. Investigating further.

**Comment by jwnimmer-tri** [comment]
@jamiesnape This this PR still on deck (though maybe down on the stack)?  I don't want to close it because it has review in-progress, but it's also quite stale.

**Comment by jamiesnape** [comment]
It is still on-deck.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental please
@drake-jenkins-bot linux-clang-experimental-minimal please
@drake-jenkins-bot linux-clang-experimental-open-source please
@drake-jenkins-bot linux-clang-ninja-experimental please
@drake-jenkins-bot linux-clang-ninja-experimental-minimal please
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-experimental please
@drake-jenkins-bot linux-gcc-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-ninja-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-minimal please
@drake-jenkins-bot mac-clang-experimental-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-minimal please
@drake-jenkins-bot mac-clang-ninja-experimental-open-source please

**Comment by jamiesnape** [comment]
Finally.

**Comment by sherm1** [comment]
Yay! Thanks, @jamiesnape.

@SeanCurtis-TRI, Jamie got FCL linked in.

**Pull request merged**
