### PR TITLE
[workspace] Add libcmaes as a testonly dependency

### LINKED ISSUE #16433: Bring in libcmaes as a dependency
Now that [libcmaes](https://github.com/CMA-ES/libcmaes) has the Apache 2.0 license, I think it is ready to bring it as a Drake dependency

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In the future, we might use this in production, but for getting started we only need it in the sample test.

Closes #16433.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16441)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Tested on macOS locally; no build errors.

+@hongkai-dai to begin feature review, please.  Check over the parts you care about (is the demo working correctly; are there any important upstream optimization flags missing).  You can leave the detailed BUILD review for someone else to cover.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16441)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[tools/workspace/libcmaes/dev/sample_code.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16441#-MuNYU_p-Tjwwv0Q6kA3:-MuNYU_p-Tjwwv0Q6kA4:b2cq6ts) ([raw file](https://github.com/robotlocomotion/drake/blob/93f187f1d90a4f3b6f40c102e05de7b3e7a331e0/tools/workspace/libcmaes/dev/sample_code.cc#L48)):*
> ```cpp
>   CMAParameters<> cmaparams(x0,sigma);
>   //cmaparams._algo = BIPOP_CMAES;
>   CMASolutions cmasols = cmaes<>(fsphere,cmaparams);
> ```

Thanks Jeremy. I am not sure how to check whether this code runs on multi-thread (the black-box optimizer would benefit from multithreading). libcmaes suggest to put this line to activate multi-threading
```
cmaparams.set_mt_feval(true); // activates the parallel evaluation
```
according to https://github.com/CMA-ES/libcmaes/wiki/Multithreading

They also suggest to wrap the objective function `fsphere` with a mutex.

I am OK to not check the multi-threading in this PR (sorry I never use multi-threading before).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16441)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[tools/workspace/libcmaes/dev/sample_code.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16441#-MuNYU_p-Tjwwv0Q6kA3:-MuNgf9B-o7boLRUP1TI:b-bo1yp7) ([raw file](https://github.com/robotlocomotion/drake/blob/93f187f1d90a4f3b6f40c102e05de7b3e7a331e0/tools/workspace/libcmaes/dev/sample_code.cc#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks Jeremy. I am not sure how to check whether this code runs on multi-thread (the black-box optimizer would benefit from multithreading). libcmaes suggest to put this line to activate multi-threading
```
cmaparams.set_mt_feval(true); // activates the parallel evaluation
```
according to https://github.com/CMA-ES/libcmaes/wiki/Multithreading

They also suggest to wrap the objective function `fsphere` with a mutex.

I am OK to not check the multi-threading in this PR (sorry I never use multi-threading before).
</blockquote></details>

Looking at the libcmaes code, `set_mt_feval` only has any effect when OpenMP is enabled at compile-time.  Therefore, it is a no-op in our Drake builds (because we do not enable OpenMP yet), so I think it's OK to merge this as-is.  We can work on adjusting the settings in future commits, if we need to.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ericcousineau-tri for Thursday's platform review, thanks!

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16441#-:-MuNnP18EOQMz5hre1Yx:b-pibrkx)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform - and super informative comments- thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16441#-:-MuRUk9v7WhdTVmHGqC9:btu7dla)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @jwnimmer-tri)

**Pull request merged**
