### PR TITLE
Add Bazel support for spdlog

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4039)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4039#-:-KVp6mclmL-D_EvoldgR:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Retrying an apparent flake:
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4039#-:-KVpB8kE5XF4XNBYwfMJ:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
Only Bazel files changed.  Counting Rick as platform review.

**Pull request merged**
