### PR TITLE
Add "Unicode Tips & Tricks" sphinx doc

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6926)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@russtedrake for both reviews. Thank you.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-:-KsXT0j1JAtDai46lhG5:b-c18igl)*

**Comment by soonho-tri** [comment]
FYI, this is how it renders:

screen shot 2017-08-27 at 2 55 02 am

**Comment by RussTedrake** [comment]
:lgtm:  awesome.  thank you!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/unicode_tips_tricks.rst, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-KsYMSKWXL7WxLncHfEM:-KsYMSKWXL7WxLncHfEN:b-pmokbx) ([raw file](https://github.com/robotlocomotion/drake/blob/8990f3da258dabde71b2acc9fd8f521c9bc5e61b/drake/doc/unicode_tips_tricks.rst#L15)):*
> ```reStructuredText
>    // df/dv_i = (∂f/∂x * dx/dv_i) + (∂f/∂y * dy/dv_i)
>    // ∂f/∂x is y*x^(y-1)
>    y * pow(x, y - 1) * xgrad +
> ```

zap this line?  it's confusing as it is part of a line of real code?

---

*[drake/doc/unicode_tips_tricks.rst, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-KsYMXPw7HSSCh1CeK88:-KsYMXPw7HSSCh1CeK89:b-c6anpj) ([raw file](https://github.com/robotlocomotion/drake/blob/8990f3da258dabde71b2acc9fd8f521c9bc5e61b/drake/doc/unicode_tips_tricks.rst#L17)):*
> ```reStructuredText
>    y * pow(x, y - 1) * xgrad +
>    // ∂f/∂y is (x^y)*ln(x)
>    x_to_the_y * log(x) * ygrad);
> ```

zap this line, too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-:-KsYMno1PECnumTrznel:b-i43ilo)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[drake/doc/unicode_tips_tricks.rst, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-KsYMSKWXL7WxLncHfEM:-KsYUNSZpubbcI8awNyc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8990f3da258dabde71b2acc9fd8f521c9bc5e61b/drake/doc/unicode_tips_tricks.rst#L15)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

zap this line?  it's confusing as it is part of a line of real code?
</blockquote></details>

Done.

---

*[drake/doc/unicode_tips_tricks.rst, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6926#-KsYMXPw7HSSCh1CeK88:-KsYUO1mPOAYGWJp-GGX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8990f3da258dabde71b2acc9fd8f521c9bc5e61b/drake/doc/unicode_tips_tricks.rst#L17)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

zap this line, too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6926)*

**Pull request merged**
