### PR TITLE
Set local = True on boost_repository

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8630)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
Could you explain the thought process?

I am a little bit hesitant, because there are _lots_ of headers and IIRC off the top of my head it takes a long time to process them all, which would now happen anytime we change a BUILD file.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8630#-:-LAPURMc0L9qFWCZSQjA:b-5bs5l0)*

**Comment by jamiesnape** [comment]
It is a system library, so it should be `local`, otherwise something like a `brew upgrade` that upgraded `boost` would cause issues (`boost` was updated yesterday, for instance).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8630#-:-LAPV2Un3AWOVdWQ_Vky:bwumbqt)*

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews.  (I tested the boost-as-local change on Ubuntu and I am not able to detect any slow-downs, so no worries there, as it turns out.)

I think `dreal.bzl` and `vtk.bzl` also need to be local because on macOS they use pkg-config.  (That could be a separate PR.)  Everything else seemed to be properly marked.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8630#-:-LAQ7sv7-iGjXqSwqRRS:b-uat9rb)*

**Pull request merged**
