### PR TITLE
Removes use of ModelInstanceIdTable from gyroscope test.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5222)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for both levels of review please. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5222#-:-KdGNSNvM30BglCzv-dq:b8b4dd)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by liangfok** [comment]
-@sherm1 since it's past Monday. +@david-german-tri and +@soonho-tri for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5222#-:-KdWKZ0jOW7Utq31Bogt:b6yqg7t)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5222#-:-KdWQIu2__v4bHHbMoXu:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5222#-:-KdWRftyal8GukaYaW2K:bnfp4nl)*

**Pull request merged**
