### PR TITLE
Initial conditions

### PR DESCRIPTION
**Pull request by RussTedrake**
fix for issue with simulink failing to find initial conditions as described in #1372 .
also adds methods to stop the functionhandletrajectory creation when playing back TSRBMs with the visualizer.

### CODE REVIEW

**Comment by RussTedrake** [comment]
this one is fun:  
https://www.youtube.com/watch?v=gsebSpj4KK8

**Comment by RussTedrake** [comment]
@mposa -- the last bug (revealed on drake003) is on you, I think.  if gurobi is not present (e.g. on windows) then it calls the matlab version of solveLCP instead of the mex version.  And it's incorrect for joint limits (did you want JL to be in terms of qdot or v?).  

to reproduce on your machine, simply disable gurobi (or otherwise force the use of non-mex solveLCP)

**Comment by tkoolen** [comment]
Awesome!

**Comment by tkoolen** [comment]
Need to investigate more, but I'm thinking right now that #1377  could actually be a rather big problem with this pull request. I would advise against merging right now.

**Comment by RussTedrake** [comment]
thanks for looking. 

i don’t think this pull request could have caused #1377 — only exposed it.  right?

**Comment by tkoolen** [comment]
First off, momentumTest contains a bunch of mistakes (non-unit quaternion initial state, calling doKinematics with qd instead of v, fact that v = [omega_body; v_body] instead of [v_world; omega_world]). But after fixing those, I'm getting a Matlab crash that I'm investigating further now.

**Comment by tkoolen** [comment]
See https://github.com/RussTedrake/drake/pull/21.

**Comment by RussTedrake** [comment]
Thanks @mposa -- that fixed it.  I agree with @tkoolen that we need more tests active for this; will open a new issue.

**Pull request merged**
