### PR TITLE
Added documentation on how to run a Drake / ROS CI test.

### PR DESCRIPTION
**Pull request by liangfok**
Partially addresses https://github.com/RobotLocomotion/drake/issues/2966.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3014)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jhoare for feature review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO5t3N50P96AR7xkKFR:-543330024)*

**Comment by liangfok** [comment]
And +@sherm1 for platform review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO5t7gyUTyM5pFhWC8b:-112220301)*

**Comment by jhoare** [comment]
There are also matlab versions that could be triggered, but I don't think its necessary. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO6gTonkj12ayUIKNGM:-525208601)*

**Comment by liangfok** [comment]
Thanks! I added a brief note mentioning the Drake+ROS+MATLAB CI test and polished the test some more.

Now waiting on @sherm1 for platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO6hF3OgwbqjjAsfkeh:-111378473)*

**Comment by sherm1** [comment]
Platform review: :lgtm:. Waiting for feature review from @jhoare.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO79nkbeNY-ZMadawl-:-31062223)*

**Comment by jhoare** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3014#-:-KO7Hhhhl6hkQ5L-8-vN:1417088721)*

**Pull request merged**
