### PR TITLE
Compile rigid_body_tree.cc in separate halves

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
On master, on my T460p laptop, this file takes ~60s to compile.

With this change, this files takes ~20s + ~40s to compile -- the same amount of time, but split across two CPUs.

Do not merge until:
- [x] tested on macOS

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543)

### CODE REVIEW

**Comment by jamiesnape** [comment]
The remote cache is currently choking on what appears to be the size of `rigid_body_tree.pic.o` in debug mode, so this might helpful.

**Comment by sherm1** [comment]
My 2 cents: That is some impressive bazel-fu, and I do suffer from rbtree compiles, but on balance I don't think it is worth doing that much violence to the source code to split the compiles.

**Comment by jamiesnape** [comment]
Personally, I would physically split the source file and commit the multiple files, particularly if there can be some semantic grouping between the definitions in each file. It would probably upset GSG to have two or more source files to one header, but I would see some merit to having multiple files for both a human reader and a compiler.

**Comment by jwnimmer-tri** [comment]
For the record, there are _already_ multiple source files that implement `rigid_body_tree.h` -- on master in the `multibody/BUILD.bazel` file there is a comment that explains the details.

**Comment by jamiesnape** [comment]
Missed that, I guess I mean even more files then.

**Comment by jwnimmer-tri** [comment]
> ... on balance I don't think it is worth doing that much violence to the source code to split the compiles.

I also neglected to mention that this also probably reduces the RAM footprint required to compile drake, which has sometimes tripped up laptop users who compile from source.  TRI has >=  32 GiB in our laptops, but <= 16 GiB is much more common for students.

As Jamie noted, the size of the object code files is also improved.

> The remote cache is currently choking on what appears to be the size of rigid_body_tree.pic.o in debug mode, so this might helpful.

@jamiesnape Is it easy for you to check whether or not this PR makes that situation better?  This is one of the more concrete reasons we might consider merging this PR.

> Personally, I would physically split the source file and commit the multiple files, particularly if there can be some semantic grouping between the definitions in each file.

I was avoiding that mechanism for two reasons:
1. A split probably makes it more difficult to `git blame` to trace down the origin of the code.
2. In order to preserve inlining, we should (and I've tried to) group related things into the same shard.  In case we later discover that I made a mistake and a few methods should be in a different shard, we can swap them around without relocating the source code.  I also had an earlier draft with more than two shards -- if we want to later split the larger of the two current shards into more pieces, we could again do that without relocating code.

**Comment by jamiesnape** [comment]
> @jamiesnape Is it easy for you to check whether or not this PR makes that situation better? This is one of the more concrete reasons we might consider merging this PR.

Not too difficult. I can kick off a cached debug build easy enough, I just need to tweak the verbosity of the output. I will prime the cache with a build of master first.

**Comment by jamiesnape** [comment]
> 16 GiB is much more common for students.

I think it is more common in general, given the power requirements of current RAM chips (hence why Apple laptops are capped at 16 GiB).

**Comment by jamiesnape** [comment]
Regarding remote caching, there were no upload or download timeouts to/from the remote across the three debug builds of this branch that I did, which is a first as far as I can remember, so yes it is an improvement.

**Comment by jwnimmer-tri** [comment]
So I think that's a good argument that _somehow_ we need to split up this compile, so then the question turns to debating the pro / con of this particular proposal, versus other possible choices.

@sherm1 Do you have an opinion on the mechanism that we should use?  (Or anyone to delegate to on your team to help debate?)  @jamiesnape if you have more thoughts I'm happy to hear them also.

There are a few comments above that speak to different ideas, but I could try to do a longer write-up if you think that would help.  (For example, this PR splits by function groups; you could imagine doing that but with more than two groups; or instead splitting by scalartype (double-only, vs some kind of autodiffs), or even split by both T and ScalarT choices, etc.)

**Comment by sherm1** [comment]
> @sherm1 Do you have an opinion on the mechanism that we should use?

No. Doesn't sound like any way of doing it will be pretty so if it needs to be done I'd say maximize the benefit/programming_effort cost function.

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by amcastro-tri** [comment]
:lgtm:. Just couple comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/BUILD.bazel, line 225 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnSMh11SsOqka_oX-2:-LAnSMh2C77sQKvz5lI7:bl4ycmz) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/BUILD.bazel#L225)):*
> ```Python
>         ],
>     )
>     for i in range(_RBT_SHARD_COUNT)
> ```

BTW very cool we can do this. I wonder if it'll be worth doing something similar for the compilation of MBP for each scalar type. Or even if possible to do a separate compilation for each scalar type at a Drake level automatically for everything that uses `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS`?

---

*[multibody/rigid_body_tree.h, line 1740 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnVg--3V9Xdod0nOWj:-LAnVg--3V9Xdod0nOWk:b-n1ywg7) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.h#L1740)):*
> ```objc
> std::unique_ptr<RigidBodyTree<double>> RigidBodyTree<double>::Clone() const;
> 
> extern template class RigidBodyTree<double>;
> ```

could you provide a comment on why this is needed here?
I believe you might have placed it here to avoid recompiling multiple times when included from different source files since in principle we are compiling in `rigid_body_tree.cc`. However, does this actually have any effect on compilation performance given that pretty much all big methods are template methods? That is, this technique would definitely help in MBP where "everything" is templated on the class's template parameter `T`. But in RBT `T` apply to the class, and in most cases we have a separate `Scalar` template argument.
Just trying to gather your thoughts here.

---

*[multibody/rigid_body_tree.cc, line 101 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnTDHkC0Is7UZ4wlkO:-LAnTDHkC0Is7UZ4wlkP:b5prsdk) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L101)):*
> ```cpp
> // The shard assignments are chosen so that methods that might benefit from
> // inlining their calls are within the same shared.  (In other words, the
> // shards draw a partition through the call graph that crosses are few
> ```

BTW could you provide some guidance on what tools you've been using to analyze the call graph? any hints or pro tips you might have that are worth adding to these notes? (I'm thinking some of these ideas might become more general as our code base grows and we use more scalar types)

---

*[multibody/rigid_body_tree.cc, line 105 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnTAZU-FQCTuq1lcdA:-LAnTAZU-FQCTuq1lcdB:bgrxgg3) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L105)):*
> ```cpp
> // methods to a shard, try to assign the new method to the same shard as the
> // methods it calls.  If it does not need to call anything else, assign it to
> // the shard that compiles mostly quickly currently.
> ```

BTW most

---

*[multibody/rigid_body_tree.cc, line 111 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUs0v51ILDtgnQsI8:-LAnUs0v51ILDtgnQsI9:b-3tbku9) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L111)):*
> ```cpp
> #endif
> 
> #if DRAKE_RBT_SHARD == 0
> ```

I haven't actually double-checked how you assigned this shards. It'd seem you didn't simply split the file in half. You mention above you attempted to allow the compiler to inline things whenever possible. Do you have any tools you used to measure performance after the split? any guidance/tools/pro-tips you could provide in this regard?

---

*[multibody/rigid_body_tree.cc, line 3423 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUIEf2Dxj8HlOJo6N:-LAnUIEf2Dxj8HlOJo6O:bqt8cwp) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3423)):*
> ```cpp
> template Eigen::Transform<double    , 3, 1, 0> RigidBodyTree<double    >::relativeTransform<double    >(const KinematicsCache<double    >&, int, int) const;  // NOLINT
> template Eigen::Transform<AutoDiffXd, 3, 1, 0> RigidBodyTree<double    >::relativeTransform<AutoDiffXd>(const KinematicsCache<AutoDiffXd>&, int, int) const;  // NOLINT
> template Eigen::Transform<AutoDiffXd, 3, 1, 0> RigidBodyTree<AutoDiffXd>::relativeTransform<AutoDiffXd>(const KinematicsCache<AutoDiffXd>&, int, int) const;  // NOLINT
> ```

Why would you need this new instantiation of `RigidBodyTree<AutoDiffXd>`? it used to be that the template `T` in RBT was a dummy template argument (leaft over of our RBT cleanup) and therefore there is no need to instantiate on all scalar types (since each individual method is templated). Here and below.

---

*[multibody/rigid_body_tree.cc, line 3443 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUgL10GUCDCghk1CT:-LAnUgL10GUCDCghk1CU:b2c1r09) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3443)):*
> ```cpp
> template TwistVector<double    > RigidBodyTree<double    >::geometricJacobianDotTimesV<double    >(const KinematicsCache<double    >&, int, int, int) const;  // NOLINT
> template TwistVector<AutoDiffXd> RigidBodyTree<double    >::geometricJacobianDotTimesV<AutoDiffXd>(const KinematicsCache<AutoDiffXd>&, int, int, int) const;  // NOLINT
> template TwistVector<AutoDiffXd> RigidBodyTree<AutoDiffXd>::geometricJacobianDotTimesV<AutoDiffXd>(const KinematicsCache<AutoDiffXd>&, int, int, int) const;  // NOLINT
> ```

ditto on the new instantiation on AutoDiffXd

---

*[multibody/rigid_body_tree.cc, line 3599 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUpby8goMIiRROAV-:-LAnUpby8goMIiRROAV0:b2c1r09) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3599)):*
> ```cpp
> // Explicitly instantiates on the most common scalar types.
> template class RigidBodyTree<double>;
> template class RigidBodyTree<AutoDiffXd>;
> ```

ditto on the new instantiation on AutoDiffXd

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-:-LAnXm2a8Ql4o-kGQOVp:b-vxn3p1)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[multibody/BUILD.bazel, line 225 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnSMh11SsOqka_oX-2:-LAneuvN7Un232oJa7ZO:b-hzhcj7) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/BUILD.bazel#L225)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW very cool we can do this. I wonder if it'll be worth doing something similar for the compilation of MBP for each scalar type. Or even if possible to do a separate compilation for each scalar type at a Drake level automatically for everything that uses `DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS`?
</blockquote></details>

OK Yes, I have considered such before.  I think bazel's "aspect"s are likely to be what we want if we start slicing compilation by scalar type.  That's for another day, though.

---

*[multibody/rigid_body_tree.h, line 1740 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnVg--3V9Xdod0nOWj:-LAo4SbAB8aOHnP46cUA:b-ecgpqm) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.h#L1740)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you provide a comment on why this is needed here?
I believe you might have placed it here to avoid recompiling multiple times when included from different source files since in principle we are compiling in `rigid_body_tree.cc`. However, does this actually have any effect on compilation performance given that pretty much all big methods are template methods? That is, this technique would definitely help in MBP where "everything" is templated on the class's template parameter `T`. But in RBT `T` apply to the class, and in most cases we have a separate `Scalar` template argument.
Just trying to gather your thoughts here.
</blockquote></details>

Done.

I don't know exactly how much it helps, but it seems like a good idea given that we're doing the odd thing of compiling a file more than once.

---

*[multibody/rigid_body_tree.cc, line 101 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnTDHkC0Is7UZ4wlkO:-LAny_XS0bVAfw7MjTqL:bkuyoul) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L101)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW could you provide some guidance on what tools you've been using to analyze the call graph? any hints or pro tips you might have that are worth adding to these notes? (I'm thinking some of these ideas might become more general as our code base grows and we use more scalar types)
</blockquote></details>

OK Nope, I just manually figured out (by code reading) what calls what, and then used by own judgment to partition the graph.

---

*[multibody/rigid_body_tree.cc, line 105 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnTAZU-FQCTuq1lcdA:-LAnyRc88JZiJFvEZdAs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L105)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW most
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 111 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUs0v51ILDtgnQsI8:-LAnyTO_3V5aMWXMJvWm:b-9lpkay) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L111)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I haven't actually double-checked how you assigned this shards. It'd seem you didn't simply split the file in half. You mention above you attempted to allow the compiler to inline things whenever possible. Do you have any tools you used to measure performance after the split? any guidance/tools/pro-tips you could provide in this regard?
</blockquote></details>

No, I did not try to measure anything.  I just did my best manual attempt to avoid disrupting things.

---

*[multibody/rigid_body_tree.cc, line 3423 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUIEf2Dxj8HlOJo6N:-LAo-otd2VaS7UMItPJI:b-ijk0kp) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3423)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Why would you need this new instantiation of `RigidBodyTree<AutoDiffXd>`? it used to be that the template `T` in RBT was a dummy template argument (leaft over of our RBT cleanup) and therefore there is no need to instantiate on all scalar types (since each individual method is templated). Here and below.
</blockquote></details>

There are plenty of other places where we instantiate a `RigidBodyTree<AutoDiffXd>::someMethod<AutoDiffXd>(...)` in this file.  So this formulation (with both `T` and `Scalar` set to `AutoDiffXd`) is not unusual in general.

As to why this specific change, to the best of my recollection, there was code in Drake that relied on it, that used to be accidentally using a symbol created by side-effect from compiling some other function in this file that called this one.

If you like, I could remove this to see what CI was griping about in particular?  I believe it shows up as `pydrake` link failures in certain build configurations.

---

*[multibody/rigid_body_tree.cc, line 3599 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUpby8goMIiRROAV-:-LAnzgiEArdEvg75YE4w:b-q8xsug) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3599)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto on the new instantiation on AutoDiffXd
</blockquote></details>

In general, there is code that uses `RigidBodyTree<T>` with `T = AutoDiffXd`.  We should be sure all such methods exist as object code, even in cases where they are not method templates (i.e., when they to not use Scalar for KinematicsCache, and thus don't have method template instantiations above).

Or more specifically, lots of `pydrake` unit tests fail to link when I remove this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/rigid_body_tree.h, line 821 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543#-LAo7xUq-q6UDAbSu3Tj:-LAoiQHN4SqLPZWqibA4:b-w8rng0) ([raw file](https://github.com/robotlocomotion/drake/blob/d0e7d18baa67f077f0ef295262fee14775a02a6f/multibody/rigid_body_tree.h#L821)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I think this might be wrong. I believe we'd like to have:
 ```c++
return DoTransformPointsJacobian<T, PointScalar>(
  cache, points.template cast<Scalar>().eval(),
  from_body_or_frame_ind, to_body_or_frame_ind, in_terms_of_qdot);
```
since it'd seem that what this is trying to accomplish is to allow points to be templated on `double` while the cache could be on `AutoDiffXd`. Do you think worth fixing in this PR? that'd avoid having to compile `RBT<AutoDiffXd>`

</blockquote></details>

The purpose here is to allow DerivedPoints to be any autodiff type (such as`AutoDiffNd` for some N)  but not have to add an explicit template method instantiation for N in the cc file.  There are _three_ scalars in play here.  We have `T = double` always, `Scalar = double` or `Scalar = AutoDiffXd` depending on the kincache being used, and `PointScalar` set depending on the `DerivedPoints` that the user passed in (which means: do the points have non-zero partials or not).  So I think this code is correct as-written, but perhaps some of the cc file warts you noted still need fixing (per other discussions).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8543)*

**Comment by jwnimmer-tri** [comment]
I've rebased this atop #8663 for now; that one will merge first.

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/rigid_body_tree.h, line 821 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAo7xUq-q6UDAbSu3Tj:-LApGRDT56jyhnnquYnh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d0e7d18baa67f077f0ef295262fee14775a02a6f/multibody/rigid_body_tree.h#L821)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The purpose here is to allow DerivedPoints to be any autodiff type (such as`AutoDiffNd` for some N)  but not have to add an explicit template method instantiation for N in the cc file.  There are _three_ scalars in play here.  We have `T = double` always, `Scalar = double` or `Scalar = AutoDiffXd` depending on the kincache being used, and `PointScalar` set depending on the `DerivedPoints` that the user passed in (which means: do the points have non-zero partials or not).  So I think this code is correct as-written, but perhaps some of the cc file warts you noted still need fixing (per other discussions).
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 3423 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUIEf2Dxj8HlOJo6N:-LApFpim8St2eY3cLF1t:b-rh93sn) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3423)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I actually only find one: `RigidBodyTree<AutoDiffXd>::DoTransformPointsJacobian()` , which is the implementation for `transformPointsJacobian()`. There is some template trickery in there for which it'd seem the `RigidBodyTree<AutoDiffXd>` is needed. I believe there might be an error in there though. Let me point out the specific line...
</blockquote></details>

Done.

You were right, the stray template method instantiation that I've now removed in #8663 was causing all kind of havoc, this included (and all of your other notes).  I've reverted the "add new instantiations" changes.

---

*[multibody/rigid_body_tree.cc, line 3443 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUgL10GUCDCghk1CT:-LApG96g50Izdfo0f0D8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3443)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto on the new instantiation on AutoDiffXd
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 3599 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAnUpby8goMIiRROAV-:-LApGBuB1ywZJ0zRSp4G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2529206f6c2db443be199761c05c922824e2d1f1/multibody/rigid_body_tree.cc#L3599)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

humm... but that wasn't here before this PR and tests passed right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543#-:-LApGDM-Ew4qHmx0wwn7:bjqgphn)*

**Comment by amcastro-tri** [comment]
Feature done. :lgtm:
+@sammy-tri for platform review please.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543#-:-LArhGnQ3Irc5A0EL0W1:b-u6nh91)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by sammy-tri** [comment]
First pass complete.

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[multibody/rigid_body_tree.cc, line 100 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsIdjdDd-ybuTtde6a:-LAsIdjdDd-ybuTtde6b:bbo62uu) ([raw file](https://github.com/robotlocomotion/drake/blob/85e0c46c2fc6e7345528bfc5ae4f6d05ef6c6858/multibody/rigid_body_tree.cc#L100)):*
> ```cpp
> //
> // The shard assignments are chosen so that methods that might benefit from
> // inlining their calls are within the same shared.  (In other words, the
> ```

typo "shared" instead of "shard"?

---

*[multibody/rigid_body_tree.cc, line 101 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsIhG4EM_F8tRmPjvU:-LAsIhG4EM_F8tRmPjvV:bb3atnf) ([raw file](https://github.com/robotlocomotion/drake/blob/85e0c46c2fc6e7345528bfc5ae4f6d05ef6c6858/multibody/rigid_body_tree.cc#L101)):*
> ```cpp
> // The shard assignments are chosen so that methods that might benefit from
> // inlining their calls are within the same shared.  (In other words, the
> // shards draw a partition through the call graph that crosses are few
> ```

"crosses are few" sounds strange

---

*[multibody/rigid_body_tree.cc, line 3483 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsJlwW3Y_BT5z2l-81:-LAsJlwW3Y_BT5z2l-82:b-aystl1) ([raw file](https://github.com/robotlocomotion/drake/blob/81219516a7347d58fd3ce2754282eacd198d3a75/multibody/rigid_body_tree.cc#L3483)):*
> ```cpp
> 
> // Explicit template instantiations for parseBodyOrFrameID.
> template int RigidBodyTree<double>::parseBodyOrFrameID(const int body_or_frame_id, Eigen::Transform<double, 3, Eigen::Isometry>* Tframe) const;  // NOLINT
> ```

Should the declaration of this overload of function in the header still be in the `public` section if there won't be anything to link against? (which I think is what will happen)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543#-:-LAsK0JCBCn6F8OXNFcR:bvb1a6z)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/rigid_body_tree.cc, line 100 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsIdjdDd-ybuTtde6a:-LAskVaR9pv3f3Ut4aQg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85e0c46c2fc6e7345528bfc5ae4f6d05ef6c6858/multibody/rigid_body_tree.cc#L100)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "shared" instead of "shard"?
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 101 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsIhG4EM_F8tRmPjvU:-LAskVos89vtJcO1XjCZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85e0c46c2fc6e7345528bfc5ae4f6d05ef6c6858/multibody/rigid_body_tree.cc#L101)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

"crosses are few" sounds strange
</blockquote></details>

Done.

---

*[multibody/rigid_body_tree.cc, line 3483 at r4](https://reviewable.io/reviews/robotlocomotion/drake/8543#-LAsJlwW3Y_BT5z2l-81:-LAskog51ICUKyv4mu-u:bfrwlbk) ([raw file](https://github.com/robotlocomotion/drake/blob/81219516a7347d58fd3ce2754282eacd198d3a75/multibody/rigid_body_tree.cc#L3483)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should the declaration of this overload of function in the header still be in the `public` section if there won't be anything to link against? (which I think is what will happen)?
</blockquote></details>

The instantiation that was removed here was redundant with the `template class RigidBodyTree<double>;` that already exists.  It has T = double and no Scalar, so its a non-templated method on a templated class, so the class-template explicit instantiation already covers it.

I don't have a good explanation why we don't have explicit template method instantiations for various values of Scalar.  I guess T = double and Scalar = double is all that was needed?  Or else the other ones are implicitly coming from somewhere else?  In any case, I'll claim this PR makes it neither better or worse.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8543#-:-LAsyawY8AEdn1dA5TTr:bnfp4nl)*

**Pull request merged**
