### PR TITLE
GurobiSolver always returns the best effort solution.

### LINKED ISSUE #18366: GurobiSolver should return values when terminating with iteration limit, time limit, etc.
Originally reported on [StackOverflow](https://stackoverflow.com/questions/74320174/how-do-i-obtain-an-intermediate-solution-using-the-pydrake-interface-to-gurobi/74329161).

Gurobi has [many possible return status codes](https://www.gurobi.com/documentation/9.1/refman/optimization_status_codes.html).  Currently in our code, if the solution result is not one of GRB_OPTIMAL, GRB_SUBOPTIMAL, GRB_INF_OR_UNBD, GRB_UNBOUNDED, GRB_INFEASIBLE, we fall off the case statement and return nothing: https://github.com/RobotLocomotion/drake/blob/a2390791c201a87925e3214299dcbf0c349ca808/solvers/gurobi_solver.cc#L1273-L1289

It seems obviously good to return the best effort results from the solver when hitting an iteration/time/etc limit?

### PR DESCRIPTION
**Pull request by hongkai-dai**
This best effort solution is reported by Gurobi, including both the primal and dual solution. The solution is reported for every *non-error* status of the solver, whether it is infeasible/unbounded/hitting iteration limit, etc.

Resolves #18366

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367#-:-NHufCTf-q07jp4yKBDl:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  awesome.  thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367#-:-NHvNpIL1YkqZDedP0es:b-5blr5w)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18367#-NHvNZPm5oZ6xzlUFthJ):*
nit: technically not always.  it could return invalid input.

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367#-:-NHwm3FH-kB23R6j7FAI:b-qsst0j)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18367#-NHvNZPm5oZ6xzlUFthJ):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: technically not always.  it could return invalid input.
</blockquote></details>

Done. I changed the commit message.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With one small clarification in both commit message and code. "No matter the status of the solver" is not true. It should be "for every non-error status".

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367#-:-NI-Bvvz6GH5xEcXjEni:b-9c9e26)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18367#-NI-Aah8A10KE_r6aOtn):*
nit: s/solutionr esult/solution result

(Also, put one line of white space between the single-sentence summary and the further description.)
___
*[`solvers/gurobi_solver.cc` line 1369 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18367#-NI-B1dz574n9n1-nqQ9:-NI-B1dz574n9n1-nqQA:b-7c3k8c) ([raw file](https://github.com/robotlocomotion/drake/blob/9c1ad6c5c10715949a95c9411e220e579f61ebe6/solvers/gurobi_solver.cc#L1369)):*
> ```cpp
>     solver_details.error_code = error;
>   } else {
>     // Always set the primal and dual solution for any gurobi status.
> ```

The PR description says that we get a value "no matter the status
  of the solver". That's not what this code does. If there is an error, it doesn't call `SetSolution()`. Should we tweak the commit message to clarify this? And this comment?  "any gurobi status"? Obviously, the "error" condition gets to be different.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367)* status: 1 unresolved discussion, missing label for release notes (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[`solvers/gurobi_solver.cc` line 1369 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18367#-NI-B1dz574n9n1-nqQ9:-NI-JT1-DWFrPUfwPb7U:bse5tjk) ([raw file](https://github.com/robotlocomotion/drake/blob/9c1ad6c5c10715949a95c9411e220e579f61ebe6/solvers/gurobi_solver.cc#L1369)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The PR description says that we get a value "no matter the status
  of the solver". That's not what this code does. If there is an error, it doesn't call `SetSolution()`. Should we tweak the commit message to clarify this? And this comment?  "any gurobi status"? Obviously, the "error" condition gets to be different.

</blockquote></details>

Done. I changed the documentation here and also the commit message.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367)* status: missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18367#-:-NI-RYubETMmCiUezda1:b-chsgxs)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),RussTedrake(platform) (waiting on @hongkai-dai)

**Pull request merged**
