### PR TITLE
[Draft] Consistently return `Binding<T>` from `Add...Cost` and `Add...Constraint` methods

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is a draft implementation to address #5646, such that the `Add...Cost` and `Add...Constraint` methods in `MathematicalProgram` consistently return `Binding<T>` (where `T` is as specific as possible to the added item).

I am doing this as a draft because I would like to make sure that y'all are okay with how the interface change affects downstream usages.
A good example is how [`mathematical_program_test` changes](https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:issue/5646_return_binding?expand=1#diff-861ece1bb7e5186e9e44628e43a654ca).

Additional, as discussed in the issue, it appears that we may be inducing extra copies of the decision variable vectors (`VectorXDecisionVariable`) when copying the `Binding`'s. There does not seem to be a clean way to sidestep this, but if you have an idea, please do let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5711)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.
+@russtedrake  for feature review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5711#-:-Kgpy7LJH3zaumuLqRW6:b-7lmifm)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for feature review.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5711#-:-KgpyWUu_ZnLYTQM4pkm:bboswjz)*

**Comment by EricCousineau-TRI** [comment]
Please note that the Jenkins build failed due to this being a draft PR. (Will see if there are options in the future to mark this as a draft to prevent testing resources from needlessly being used.)

**Comment by hongkai-dai** [comment]
I do not worry too much about copying the `VectorXDecisionVariable` yet, as we have not run any profiling on our code yet, so we do not know what is the speed bottleneck.  I think we should return-by-value, if we decide to return a binding for AddXXXConstraint.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5711#-:-Kgq-5TWZz5P1DWfe698:b-ibpjar)*

**Comment by EricCousineau-TRI** [comment]
Closing this for a legitimate PR.

**Pull request closed without merging**
