### PR TITLE
Use upstream vtkCapsuleSource

### LINKED ISSUE #12325: Use vtkCapsuleSource directly from VTK
Use vtkCapsuleSource once it's been pulled upstream into VTK itself, see https://gitlab.kitware.com/vtk/vtk/issues/17720
Then we can undo the third party changes in #12305 

Relates to #10153

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove our locally-vendored version of `vtkCapsuleSource` and instead use the upstream version, which is newly available with the switch to VTK 9.

Fixes #12325.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
@mwoehlke-kitware Is this ready for review ?  I can find a feature reviewer for you if you like.  Or if you like I can +  (status: single reviewer ok) and solo review it since it looks low-complexity.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419#-:-MuBEsqG49QLQkzeaK3l:b-aqppwe)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Comment by mwoehlke-kitware** [comment]
@ggould-tri, yes, I'm not sure who would be most appropriate though. Probably should get a look from @svenevs and maybe @tehbelinda?

**Review by ggould-tri — COMMENTED** [review]
+@svenevs for feature review; FYI @tehbelinda  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419#-:-MuBkYIE9WZJGOpsSwp7:b82neaw)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @svenevs)

**Review by ggould-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419#-:-MuBkvPQDDwHqpZGVQ8Q:b-c7f1bi)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
:lgtm: feature review.  +@ggould-tri for platform review please, in the fight for truth, justice, and correctly spelled comments (that made my day) :slightly_smiling_face:

Reference example if helpful, in one terminal run `bazel run //tools:drake_visualizer` and another (only example I'm familiar with, it has capsules in it) `bazel run //geometry/render/dev:render_engine_vtk_minimal_example`.  Worth mentioning that the capsule on the right is not textured, that is expected -- VTK does not implement textures for capsules but that is beyond the scope of this PR.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419#-:-MuC89k78F0ydihzILYO:bm16i5d)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16419#-:-MuCDYxrBIIrjDo8Q6HU:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),svenevs (waiting on @mwoehlke-kitware)

**Pull request merged**
