### PR TITLE
don't modify the param_set_name in a frozen plan

### PR DESCRIPTION
**Pull request by rdeits**
this can cause problems when transitioning from walking to standing,
since the qp_input for the end of a walking plan may not work properly
when its params are suddenly switched to the standing set.

### CODE REVIEW

**Comment by rdeits** [comment]
This doesn't fix the underlying issue, which is that holding the last qp_input of a walking plan while using the standing params causes the robot to try to jump back to the origin. I believe that's happening because we have a whole-body weight on the `q_desired`, which includes the base positions (which are not actually used for walking plans, and thus not accurate). I'm working on a more general fix for that now. 

However, I still think this is a good change to make, since we probably shouldn't get in the habit of modifying a qp_input after it's been created.

**Comment by rdeits** [comment]
Ok, I've added a commit which also sets the floating base weights to zero for the QP by default. This should fix the symptom (popping up or back at the end of a walking plan) and also the root cause (trying to track a floating base state which fights the pelvis body_motion_data).

**Comment by RussTedrake** [comment]
are some of the controller params still setting the floating_base weight to non-zero?  (are we sure this should be zero'd for all param modes?)

**Comment by rdeits** [comment]
All the param sets should now be setting those weights to 0 (previously, most of the weights had them set to zero, but not the standing sim weights). 

@kuindersma what do you think about this? If we require a body_motion_data for the pelvis, is there any reason to have weights on q_dd for the floating base?

**Comment by kuindersma** [comment]
No, those weights should be 0 in that case

**Comment by rdeits** [comment]
Ok, then I think this change is good. `QPLocomotionPlan.getQPControllerInput()` always checks that there's a body_motion data for the pelvis at every call, so there's no danger that we'll suddenly stop tracking base motion for some type of plan

**Pull request merged**
