### PR TITLE
Bind and test python bindings for symbolic::Formula

### LINKED ISSUE #8319: Bind and test python binding for symbolic::Formula
For now, we only support one method, `Formula::to_string`.

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #8319

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8337)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@ericcousineau-tri for all-reviews.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-:-L7KUpwgW9CKSjmCTf7L:b-x6dnqp)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending resolution of `__repr__` functions.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QH5TvKYograylFURp:-L7QH5TvKYograylFURq:b-ip862e) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
Could we change `__repr__` to return something akin to `Variable('{name}')`?

Per the docs:
https://docs.python.org/2/library/functions.html#func-repr

>  [...] For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval(), otherwise the representation is a string enclosed in angle brackets [...]

(Sorry, this is something that I discovered indirectly through Bazel a few weeks ago...)

---

*[bindings/pydrake/symbolic_py.cc, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QHGA8oV8y2o14ZNn6:-L7QHGA8oV8y2o14ZNn7:bjlfa2) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L99)):*
> ```cpp
>       .def("size", &Variables::size)
>       .def("empty", &Variables::empty)
>       .def("__repr__", &Variables::to_string)
> ```

Same thing as above; if it's difficult to make this `eval()`-able, could you make it return something like `<Formula "{variables_str}">`?

---

*[bindings/pydrake/symbolic_py.cc, line 256 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QGefvYAX5pdHWv4t5:-L7QGefvYAX5pdHWv4t6:b-ns7988) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L256)):*
> ```cpp
>            })
>       .def("to_string", &Formula::to_string)
>       .def("__repr__", &Formula::to_string)
> ```

Same thing as above, resorting to angle brackets if need be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-:-L7QH2Ctt74DUb2VJqfj:b5k65s5)*

**Comment by soonho-tri** [comment]
Updated `__repr__`s in the file and expected outputs in the tests. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QH5TvKYograylFURp:-L7_19BscDrGM-i_g__W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could we change `__repr__` to return something akin to `Variable('{name}')`?

Per the docs:
https://docs.python.org/2/library/functions.html#func-repr

>  [...] For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval(), otherwise the representation is a string enclosed in angle brackets [...]

(Sorry, this is something that I discovered indirectly through Bazel a few weeks ago...)
</blockquote></details>

Done.

---

*[bindings/pydrake/symbolic_py.cc, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QHGA8oV8y2o14ZNn6:-L7_1g4GStxPeQdn6g4o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L99)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same thing as above; if it's difficult to make this `eval()`-able, could you make it return something like `<Formula "{variables_str}">`?
</blockquote></details>

Done.

---

*[bindings/pydrake/symbolic_py.cc, line 256 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7QGefvYAX5pdHWv4t5:-L7_22pBHE-Sauu2sl2T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L256)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Same thing as above, resorting to angle brackets if need be.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-:-L7_ASSAdkE-D7g2fOxD:bxfetr9)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7_Fvd-kqn6xzNfweu0:-L7_Fvd0o3xeT5EDcqi9:buyskw3) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
> ```cpp
>       .def(py::init<const std::string&>())
>       .def("get_id", &Variable::get_id)
>       .def("__repr__", &Variable::to_string)
> ```

I'm sorry, one more request (that may change the tests back :( ):
Could you implement `__str__` as well?
(if not, let me know and I can mod this PR - sorry for the back and forth!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337)*

**Comment by soonho-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7_Fvd-kqn6xzNfweu0:-L7_GIhd-jJCE4s7y7Og:b-k1foi3) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I'm sorry, one more request (that may change the tests back :( ):
Could you implement `__str__` as well?
(if not, let me know and I can mod this PR - sorry for the back and forth!)
</blockquote></details>

Not a problem. Just to make sure, is `__str__` supposed to behave as `to_string()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7_Fvd-kqn6xzNfweu0:-L7_OFylERFq0Q84bNw6:b-a2kz0y) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Not a problem. Just to make sure, is `__str__` supposed to behave as `to_string()`?
</blockquote></details>

Yup!
https://docs.python.org/2/library/functions.html#str

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/symbolic_py.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8337#-L7_Fvd-kqn6xzNfweu0:-L7_vilbDeRhL3m5dxMb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85b89009d24303426e094bd1e9fc7f609bc06a40/bindings/pydrake/symbolic_py.cc#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Yup!
https://docs.python.org/2/library/functions.html#str
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8337)*

**Pull request merged**
