### PR TITLE
Screwjoint PR.

### PR DESCRIPTION
**Pull request by liruiw**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks for the PR! I'll do feature review +@ericcousineau-tri

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049#-:-NDjPPlvBaeMy7ku6lxq:b-qo2vnq)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI and @liruiw)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NDjW46g4NYaiWZMSbdq:-NDjW46h3573KmZ7cGeG:bepizod) (no related file):*
Can you add testing to `plant_test.py`, similar to the testing done for other joints?

___
___
*[`.gitignore` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NDjPV7K6qb50zjcw134:-NDjPV7K6qb50zjcw135:b6ny562) ([raw file](https://github.com/robotlocomotion/drake/blob/a023c6d4ddb6e3c091819fba72a85aaba4ff177c/.gitignore#L30)):*
> ```ignore
> 
> # User-specified configuration
> /user.bazelrc
> ```

nit Can you revert changes to this file?
___
*[`bindings/pydrake/multibody/tree_py.cc` line 638 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NDjPl3L8hKDcMjXPE-p:-NDjPl3L8hKDcMjXPE-q:bngt1os) ([raw file](https://github.com/robotlocomotion/drake/blob/a023c6d4ddb6e3c091819fba72a85aaba4ff177c/bindings/pydrake/multibody/tree_py.cc#L638)):*
> ```cpp
>   }
>   
>   // ScrewJoint
> ```

nit Can you update this PR the test failure's advice?
https://drake-cdash.csail.mit.edu/test/852581981
```
drakelint.py: Linting bindings/pydrake/multibody/tree_py.cc
ERROR: bindings/pydrake/multibody/tree_py.cc:34: the #include ordering is incorrect
note: fix via bazel-bin/tools/lint/clang-format-includes bindings/pydrake/multibody/tree_py.cc
note: if that program does not exist, you might need to compile it first: bazel build //tools/lint/...
```

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @liruiw)

___
*[`.gitignore` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NDjPV7K6qb50zjcw134:-NE70kDX-LHqEmoYDQ6T:b-t6vbbj) ([raw file](https://github.com/robotlocomotion/drake/blob/a023c6d4ddb6e3c091819fba72a85aaba4ff177c/.gitignore#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you revert changes to this file?
</blockquote></details>

Ah, this removed too much. You should instead just fix the newline.

Assuming you have `upstream` as a remote, you can do
```
cd drake
git checkout upstream/master -- .gitignore
```
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1651 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NE70ct68S15wcx8W15w:-NE70ct68S15wcx8W15x:bng9i71) ([raw file](https://github.com/robotlocomotion/drake/blob/ed8505341fda634bdde8cc8985f4d313079292e6/bindings/pydrake/multibody/test/plant_test.py#L1651)):*
> ```Python
>             make_universal_joint,
>             make_weld_joint,
>         ]
> ```

You'll need to add `make_screw_joint` here.

**Comment by liruiw** [comment]
Updated!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @liruiw)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NE7iaz6A2DYiBAPmoAE:-NE7iaz6A2DYiBAPmoAF:b-cb2owc) (no related file):*
Thanks! However, CI is still failing on lint (see note below), as well as the unittest itself:
https://drake-cdash.csail.mit.edu/test/857542586

Do you know how to fix, or would you like me to suggest changes?

___

**Comment by liruiw** [comment]
Updated!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, thanks! One last nit about extra added binding that currently seems out of scope / untested.
+@sammy-tri for platform review, please!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049#-:-NEDowjPCzjOqrGRZ0Xy:b-u7hsxj)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @liruiw and @sammy-tri)

___
*[`bindings/pydrake/multibody/tree_py.cc` line 555 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18049#-NEDopAy4uZsbgIxNHHM:-NEDopAy4uZsbgIxNHHN:b-y42fj6) ([raw file](https://github.com/robotlocomotion/drake/blob/a9545ed9fdc8ab903e9a9dbe703928ba36946d94/bindings/pydrake/multibody/tree_py.cc#L555)):*
> ```cpp
>         .def("set_default_translation", &Class::set_default_translation,
>             py::arg("translation"), cls_doc.set_default_translation.doc)
>         .def("AddInForce", &Class::AddInForce, py::arg("context"),
> ```

nit This isn't tested, unfortunately.

Can you either add in a test, or remove it from this PR? (it changes scope of PR a bit)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049#-:-NEHYJnI8SN3G90BzXDm:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @liruiw)

**Review by sammy-tri — COMMENTED** [review]
+(status: squashing now) +(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18049#-:-NEHYo_qD1qWTCRd8NAZ:b4uizua)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @liruiw)

**Pull request merged**
