### PR TITLE
December external upgrades

### PR DESCRIPTION
**Pull request by nicolecheetham**
Towards #22240

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22249)

### CODE REVIEW

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Review by nicolecheetham — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22249#-:-ODN860T9WFeA8f-gTSp:bcwgdgn)* status: LGTM missing from assignee SeanCurtis-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22249#-:-ODNmpT_CjVOJyZm5zCs:bmxilld)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Master has moved, so this needs to be rebased and merged quickly. It might be advisable to defer this til Friday. I'll be available for platform review and there will be very little other activity on TRI's side so it'll be easier to rebase, review, and merge without interruption.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22249#-:-ODNnY6A2Imt0FALVVBR:b-6hofg2)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @nicolecheetham)

**Comment by nicolecheetham** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
Locally I confirmed `bazel test //...` passes after the rebase.  I also tested that install_prereqs passes.  Forcing in now.

**Pull request merged**
