### PR TITLE
Downcase "Drake" namespace to "drake"

### PR DESCRIPTION
**Pull request by ggould-tri**
Mechanically downcase "Drake" namespace to "drake".  Manually resolve the exactly one ambiguity that resulted (in drake/systems/plants/contactConstraintsmex.cpp).

This PR is very large but entirely the result of `perl -pi -e` commands with the exception of one disambiguation noted above.  As such the fact that this compiles demonstrates its correctness and the greater question is whether it is worth doing in the first place.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2983)

### CODE REVIEW

**Comment by david-german-tri** [comment]
> As such the fact that this compiles demonstrates its correctness and the greater question is whether it is worth doing in the first place.

I strongly agree, and am glad you did it.  Thank you!

**Comment by ggould-tri** [comment]
+@jwnimmer-tri who suggested this to me and therefore must bear the consequences :-)

---

Reviewed 137 of 137 files at r1.
Review status: 136 of 137 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2983#-:-KNrsTyCvt6_tyOJXPC1:-1622121370)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2983)*

**Comment by jwnimmer-tri** [comment]
By hand I reviewed the one called-out file, and second commit.  Then I spot-checked a few others, and everything else seemed fine.  For big things like this, I'm happy to go with the author's assurance, and Jenkins, as the testing -- we can clean up any tiny nitpicks down the road as we find them.

:lgtm: 

---

Reviewed 136 of 137 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2983#-:-KNsC3Y19JLsxqJU0p_6:726945741)*

**Comment by ggould-tri** [comment]
(not doing a feature review here because (1) there is no feature and (2) I have wasted enough people's time on this already)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2983#-:-KNsCo_ns6R7tmg2qAhd:-1491587554)*

**Pull request merged**
