### PR TITLE
Move quaternion to rotation matrix method to RotationMatrix class -- …

### PR DESCRIPTION
**Pull request by mitiguy**
Move quaternion to rotation matrix method to RotationMatrix class, and call Eigen's quaternion implementation (rather than good-old home brew).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8412)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by mitiguy** [comment]
@drake-jenkins-bot  linux-xenial-clang-bazel-experimental-everything  please

**Comment by mitiguy** [comment]
@drake-jenkins-bot  linux-xenial-clang-bazel-experimental-memcheck-lsan   please

**Comment by mitiguy** [comment]
@drake-jenkins-bot   linux-xenial-clang-bazel-experimental-debug   please

**Comment by mitiguy** [comment]
Feature review +@hongkai-dai 
Platform review +@ggould-tri 

Note to reviewer:
1.  One change is just cut/paste to move a function earlier in quaternion.h
2.  New algorithm for creating a rotation matrix from a quaternion -- while effectively normalizing the quaternions, but without a square-root.
3.  New unit tests added.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[math/quaternion.h, line 18 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-L84qsHfEZrymaqyRDdL:-L84qsHfEZrymaqyRDdM:b-k4f5u8) ([raw file](https://github.com/robotlocomotion/drake/blob/14dd4eee1efea003f617431cbb4e0fb8ecef8fd7/math/quaternion.h#L18)):*
> ```objc
> namespace drake {
> namespace math {
> ```

Note: The next set of changes (below) are just a cut/paste.
The function was defined later in the quaterion.h file and
needed to be moved up as it is now being called earlier.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-:-L84qMeG-qMl5PSpXroR:bt4jr2s)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 593 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8412#-L8ZW74y4PZ_h4rslbP9:-L8ZW74y4PZ_h4rslbPA:b-g5ts8r) ([raw file](https://github.com/robotlocomotion/drake/blob/b5903a508e5dbff338fe84bfd4c42bd40327e142/math/rotation_matrix.h#L593)):*
> ```objc
>   // Constructs a 3x3 rotation matrix from a Quaternion.
>   // @param[in] quaternion a quaternion which may or may not have unit length.
>   // @param[in] twoOverNormSquared is supplied by the calling method and is
> ```

`twoOverNormSquared` -> `two_over_norm_squared`, same changes below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8412#-:-L8ZVy3CDaP20ZVGCeOr:bnfp4nl)*

**Comment by mitiguy** [comment]
Platform review -@ggould-tri.
Platform review +@jwnimmer-tri 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[math/rotation_matrix.h, line 593 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-L8ZW74y4PZ_h4rslbP9:-L8Ze8c2CWifPERRHk2F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b5903a508e5dbff338fe84bfd4c42bd40327e142/math/rotation_matrix.h#L593)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`twoOverNormSquared` -> `two_over_norm_squared`, same changes below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-:-L8Zfjyb7NKhyWrWcJr4:bd7gq36)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 1 of 3 files at r1, 4 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 57 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-L8Zi3-5DBKLbD6iEhpE:-L8Zi3-5DBKLbD6iEhpF:b-czdjnd) ([raw file](https://github.com/robotlocomotion/drake/blob/76a3ec13d762bbf3f56edf5d47eb7ea4c59ab62d/math/rotation_matrix.h#L57)):*
> ```objc
> 
>   /// Constructs a %RotationMatrix from a Quaternion.
>   /// @param[in] quaternion a unit-length quaternion [`quaternion.norm() ≈ 1`].
> ```

FYI If I am reading this correctly, we document that norm == 1 is a precondition, but then correctly rescale when norm != 1?  It seems to me like either we should fail-fast if not-normalized, or else remove the precondition that it is normalized.  Since we aren't enforcing it, it means users will depend on it working for non-normalized quaternions (because they didn't notice) and then it will be harder later to start enforcing it if we care.

---

*[math/rotation_matrix.h, line 528 at r4](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-L8ZhmDL3ml-HNoTsRnL:-L8ZhmDL3ml-HNoTsRnM:b-r1wjov) ([raw file](https://github.com/robotlocomotion/drake/blob/76a3ec13d762bbf3f56edf5d47eb7ea4c59ab62d/math/rotation_matrix.h#L528)):*
> ```objc
>     if (!R.allFinite())
>       throw std::logic_error(
>         "Error: Rotation matrix contains an element that is infinity or NAN.");
> ```

Missing required curly braces on multi-line `if` body.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412#-:-L8ZgdXJCyMz8UIDwotZ:bsm4ivv)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8412)*

**Pull request merged**
