### PR TITLE
Update gallery.md

### PR DESCRIPTION
**Pull request by Mahdi-Javadi**
A minimalist brachiation robot that uses Pydrke for trajectory optimization and stabilization

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Gallery changes go to +@RussTedrake for both reviews, please.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by RussTedrake — COMMENTED** [review]
Sorry for the tremendous delay.  It's a fun project and I'm happy to include it in the gallery.  One request below.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZLsIU89cnS5kzybqE5:bb2xdch)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Mahdi-Javadi)

___
*[`doc/_pages/gallery.md` line 172 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-NZLry0H6PPJTJqJv2V-:-NZLry0H6PPJTJqJv2V0:bhsm5sz) ([raw file](https://github.com/RobotLocomotion/drake/blob/fdfae5c2ba75ca428d416cfe114c8143b4f97cdf/doc/_pages/gallery.md#L172)):*
> ```Markdown
> 
> {% include video.html
>   url = "https://www.youtube.com/watch?v=FIcDNtJo9Jc"
> ```

Since the video doesn't have direct explanation/concepts/renders from Drake, I would request that we just put the gif:
https://github.com/dfki-ric-underactuated-lab/acromonk/blob/main/hardware/images/5x-tvlqr.gif
instead of the full youtube.  they can of course get to the youtube by following the link to your paper or github.

fwiw -- the youtube link didn't actually render properly for me in the gallery, either.

**Review by Mahdi-Javadi — COMMENTED** [review]
Dear Prof. Tedrake, 
Many thanks for your reply and attention. Thank you so much for your comment and I appreciate your suggestion. 
You are completely right and this is a good point. 

Additionally, if you would prefer to have renders from Drake, I can also offer the gifs available in the following links:

https://github.com/dfki-ric-underactuated-lab/acromonk/raw/main/hardware/images/zb.gif
https://github.com/dfki-ric-underactuated-lab/acromonk/raw/main/hardware/images/zf.gif
https://github.com/dfki-ric-underactuated-lab/acromonk/raw/main/hardware/images/bf.gif
https://github.com/dfki-ric-underactuated-lab/acromonk/blob/main/hardware/images/fb.gif

If you think it would fit, please feel free to include it/them as well. 

Thanks again for your attention and I cannot thank you enough for this amazing framework and awesome lectures that you and your team provided. 

Best regards, 
Mahdi Javadi

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZLwLmi5Ig2HqgBtBlz:b758r9l)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by RussTedrake — COMMENTED** [review]
Yes, I think that the 5x-tvlqr.gif from the github page + any one of those sim gifs would be great.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZM6WXBCtd3bd7-CCpQ:bflai5j)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Mahdi-Javadi)

**Review by Mahdi-Javadi — COMMENTED** [review]
Dear Prof. Tedrake, 
Thanks for the prompt reply. Sounds great!
Then I would suggest using this gif :
https://github.com/dfki-ric-underactuated-lab/acromonk/raw/main/hardware/images/bf.gif
which is one cycle of the brachiation maneuver. 

Please let me know if I should take any further actions on the opened issue. 
Thank you so much for your time and consideration. 

Best regards,
Mahdi Javadi

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZM6zqiCF5E3D5TmiN2:b-v2v819)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by RussTedrake — COMMENTED** [review]
Yes, please update the PR with those changes... and make sure the result renders correctly by building the documentation:
https://drake.mit.edu/documentation_instructions.html
then I'll confirm the same and we'll get this landed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZMgVts2q3YwGiXKNzE:bazmies)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Mahdi-Javadi)

**Review by Mahdi-Javadi — COMMENTED** [review]
Dear Prof. Tedrake, 
Thank you for your time. 

I have built the documentation in my local machine and confirm that the resulting drake website rendered properly. 
The PR has been updated with exact those changes as well. 

Thanks a lot for including this project into the Drake's gallery. 

Best regards, 
Mahdi Javadi

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZPY8J_02fW6mWWvD8s:b-5wogj2)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by RussTedrake — COMMENTED** [review]
Looks great.
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19433#-:-NZRsAkW91Uk14ncrhnD:b-2ig7b0)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @Mahdi-Javadi)

**Pull request merged**
