### PR TITLE
[pydrake] Add symbolic.Formula.Unapply

### LINKED ISSUE #14880: Implement symbolic expression/formula visitors in Python

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Follow-up from #16014.  Closes #14880.

Also adds bindings for a few Formula constructors / factory functions that were missing and relevant here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130#-:-MotgvUw-YIRXhQLcpwF:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/symbolic_formula.h, line 480 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16130#-MotgYTI9DiMROHptv8D:-MotgYTI9DiMROHptv8E:bm4dx9l) ([raw file](https://github.com/robotlocomotion/drake/blob/fdc0d6b215e436a2e5d548c46e004aec12125405/common/symbolic_formula.h#L480)):*
> ```
> is
> ```
should be `of` here, I think? "is an isnan" is fabulous correct nonsense, BTW.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[common/symbolic_formula.h, line 480 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16130#-MotgYTI9DiMROHptv8D:-MothUXUA-_DrIM7mxFc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fdc0d6b215e436a2e5d548c46e004aec12125405/common/symbolic_formula.h#L480)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> is
> ```
should be `of` here, I think? "is an isnan" is fabulous correct nonsense, BTW.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for platform review

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130#-:-Mou6eV3AYJywcvcstmm:buasbda)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri)

___
*[common/symbolic_formula.h, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou6N175At5SFLhkRU7:-Mou6N175At5SFLhkRU8:b-h63zuj) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L483)):*
> ```objc
>  *  \pre{@p f is an isnan formula.}
>  */
> const Expression& get_expression(const Formula& f);
> ```

minor: I don't understand what makes this isnan-specific. Shouldn't it be named something like `get_isnan_expression()` if it is actually requiring f to be an isnan() formula?

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a naming question

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130#-:-Mou9hfk4mZbzzGcCK9v:b-z5z5au)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[common/symbolic_formula.h, line 481 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou708lEfs4tEORWM6l:-Mou708lEfs4tEORWM6m:bxmrqr6) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L481)):*
> ```objc
> 
> /** Returns the expression of an isnan formula @p f.
>  *  \pre{@p f is an isnan formula.}
> ```

FYI there is already an `@pre` in use three methods above.
___
*[bindings/pydrake/symbolic_py_unapply.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou8bAR3j3A97J0OPKQ:-Mou8bAR3j3A97J0OPKR:b-bo2oid) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/bindings/pydrake/symbolic_py_unapply.h#L26)):*
> ```objc
> 
> constexpr char kUnapplyFormulaDoc[] = R"""(
> Given an formula, returns a tuple (ctor, args) that would re-create an
> ```

nit: an -> a

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

___
*[common/symbolic_formula.h, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou6N175At5SFLhkRU7:-Mou9Eu84FV-K3159u-Y:b-m9rquu) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L483)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I don't understand what makes this isnan-specific. Shouldn't it be named something like `get_isnan_expression()` if it is actually requiring f to be an isnan() formula?
</blockquote></details>

If you look at the surrounding functions, the pattern in this file is that the getters are phrased in terms of the nested data that we're trying to access, and they have pre-conditions specifying for which kinds of nodes that nested data is available.

In this case it happens to be that the `FormulaKind::Isnan` is the only kind of node that _currently_ takes a 1-ary expression, but in the future if we have another type of node that is a predicate over a single expression, then this precondition would grow to encompass that new kind, but the function name would remain the same.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[bindings/pydrake/symbolic_py_unapply.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou8bAR3j3A97J0OPKQ:-MouAQZt7Fc2-PlFlk2f:bbeezff) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/bindings/pydrake/symbolic_py_unapply.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: an -> a
</blockquote></details>

`an equivalent` (status quo) looks right to me.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[bindings/pydrake/symbolic_py_unapply.h, line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou8bAR3j3A97J0OPKQ:-MouAnahC2KFnKG7lJeV:bn8ural) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/bindings/pydrake/symbolic_py_unapply.h#L26)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

`an equivalent` (status quo) looks right to me.
</blockquote></details>

(The problem (already fixed) was on the first "a" -- "Given an formula".)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[common/symbolic_formula.h, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou6N175At5SFLhkRU7:-MouG2PI5v6EJ-m1OVdR:bk8wkzi) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L483)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you look at the surrounding functions, the pattern in this file is that the getters are phrased in terms of the nested data that we're trying to access, and they have pre-conditions specifying for which kinds of nodes that nested data is available.

In this case it happens to be that the `FormulaKind::Isnan` is the only kind of node that _currently_ takes a 1-ary expression, but in the future if we have another type of node that is a predicate over a single expression, then this precondition would grow to encompass that new kind, but the function name would remain the same.
</blockquote></details>

Oh. So this is like `get_unary_expression()` with "unary" implied? (If so that would be a better name IMO but I can see why you chose this one.)

I would not have been confused if the comment matched the intent of the method. Consider "Returns the expression in a unary formula." The precondition should be that the Formula is unary. Then it could mention that currently the only unary Formula is isnan(). I think that would be clearer.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @rpoyner-tri and @sherm1)

___
*[common/symbolic_formula.h, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou6N175At5SFLhkRU7:-MouJMZU44GFQlfdMaDS:b-c20tod) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L483)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oh. So this is like `get_unary_expression()` with "unary" implied? (If so that would be a better name IMO but I can see why you chose this one.)

I would not have been confused if the comment matched the intent of the method. Consider "Returns the expression in a unary formula." The precondition should be that the Formula is unary. Then it could mention that currently the only unary Formula is isnan(). I think that would be clearer.
</blockquote></details>

This is a good point.  Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16130)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

___
*[common/symbolic_formula.h, line 483 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16130#-Mou6N175At5SFLhkRU7:-MouNv7Q6ubHHYA7lFK9:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/8cabdf893345522560207079e8eba2219c328b19/common/symbolic_formula.h#L483)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is a good point.  Done.
</blockquote></details>

Thanks!

**Pull request merged**
