### PR TITLE
Blacklist bits/stl_tree.h for UBSan

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards #8572

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8627)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8627#-:-LAPCurV4A7kcI7PuliM:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@EricCousineau-TRI for platform review, please.

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8627#-:-LAP_S4CBjZrJMyFD3ft:bnfp4nl)*

**Pull request merged**
