### PR TITLE
Tidy up comment, whitespace in systems/framework

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3255)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-:-KQ11qy9haUiQekA4_wx:bnfp4nl)*

**Comment by liangfok** [comment]
+@liangfok I volunteer to feature review this.

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-:-KQ17N6mH1Quvn-qbqPL:b-ax0nnb)*

**Comment by liangfok** [comment]
Done with first round of feature review.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[drake/systems/framework/primitives/adder.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ17nn0OhhXvm2ZYYJS:-KQ17nn0OhhXvm2ZYYJT:bo6y1es) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/adder.h#L19)):*
> ```objc
> ///
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> ```

There needs to be a blank line after this line. Otherwise, it'll render like this:



---

*[drake/systems/framework/primitives/adder.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18D5jbCrtnd57Ezrp:-KQ18D5jbCrtnd57Ezrq:b-i2302v) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/adder.h#L20)):*
> ```objc
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> /// They are already available to link against in libdrakeSystemFramework.
> ```

BTW: nit: pedantic: "They are" implies there are more than one. But there's only one (a double)!

---

*[drake/systems/framework/primitives/constant_value_source.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ188nSG9Jc5mVmjgsl:-KQ188nSG9Jc5mVmjgsm:b-7gm7i7) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/constant_value_source.h#L21)):*
> ```objc
> ///
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> ```

There needs to be a blank line after this line.

---

*[drake/systems/framework/primitives/constant_vector_source.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ189gEzl-wuumWJAhp:-KQ189gEzl-wuumWJAhq:b-7gm7i7) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/constant_vector_source.h#L18)):*
> ```objc
> ///
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> ```

There needs to be a blank line after this line.

---

*[drake/systems/framework/primitives/integrator.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18QdSBoaf12-GE_aH:-KQ18QdSBoaf12-GE_aI:b-7gm7i7) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/integrator.h#L18)):*
> ```objc
> ///
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> ```

There needs to be a blank line after this line.

---

*[drake/systems/framework/primitives/pass_through.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18REeRo-QE0rqPnQ5:-KQ18REeRo-QE0rqPnQ6:b-7gm7i7) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/pass_through.h#L22)):*
> ```objc
> ///
> /// Instantiated templates for the following kinds of T's are provided:
> /// - double
> ```

There needs to be a blank line after this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-:-KQ18SYqCBvak4jX6nFN:b51njra)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/primitives/adder.h, line 19 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ17nn0OhhXvm2ZYYJS:-KQ1A7N2izFIA8jxyxOB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/adder.h#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a blank line after this line. Otherwise, it'll render like this:
> 
> 
> 
</details>
Done.

---

*[drake/systems/framework/primitives/adder.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18D5jbCrtnd57Ezrp:-KQ1AD10eZ7bqmq0e8sV:b-74ssib) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/adder.h#L20)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: pedantic: "They are" implies there are more than one. But there's only one (a double)!
</details>
True, but I guess I prefer to leave the boilerplate as boilerplate.  (Same for "instantiated templates" above the bullet list.)

---

*[drake/systems/framework/primitives/constant_value_source.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ188nSG9Jc5mVmjgsl:-KQ1A7ucymobkUEQFjNP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/constant_value_source.h#L21)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a blank line after this line.
</details>
Done.

---

*[drake/systems/framework/primitives/constant_vector_source.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ189gEzl-wuumWJAhp:-KQ1A8ZtH4inpXhbM8aK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/constant_vector_source.h#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a blank line after this line.
</details>
Done.

---

*[drake/systems/framework/primitives/integrator.h, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18QdSBoaf12-GE_aH:-KQ1A91PmBla01S0RdTB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/integrator.h#L18)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a blank line after this line.
</details>
Done.

---

*[drake/systems/framework/primitives/pass_through.h, line 22 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ18REeRo-QE0rqPnQ5:-KQ1A9aj6bEkKcYyDPhI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/151dfae47430bf28f11effef4c48b567b67a299b/drake/systems/framework/primitives/pass_through.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> There needs to be a blank line after this line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-:-KQ1AwJtAgqOZJ62UYgd:bnfp4nl)*

**Comment by sherm1** [comment]
One BTW. Otherwise :lgtm:.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/framework/primitives/constant_value_source.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ1GlKKNG-0k0ojMa3y:-KQ1GlKKNG-0k0ojMa3z:b-gh59oe) ([raw file](https://github.com/robotlocomotion/drake/blob/b89cdb3ee74f93a005b0ecbe2fa7f72142b61d2b/drake/systems/framework/primitives/constant_value_source.h#L18)):*
> ```objc
> ///
> /// This class uses Drake's `-inl.h` pattern.  When seeing linker errors from
> /// this class, please refer to http://drake.mit.edu/cxx_inl.html.
> ```

BTW, this is a nice comment but appears only here and in PassThrough.  Did you want it to be part of the boilerplate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-:-KQ1HEDW3bv4L2ni8LkL:bu3fy5a)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/primitives/constant_value_source.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3255#-KQ1GlKKNG-0k0ojMa3y:-KQ1HrS5jqEa5TL2UWLA:b1hxhym) ([raw file](https://github.com/robotlocomotion/drake/blob/b89cdb3ee74f93a005b0ecbe2fa7f72142b61d2b/drake/systems/framework/primitives/constant_value_source.h#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, this is a nice comment but appears only here and in PassThrough.  Did you want it to be part of the boilerplate?
</details>
Indeed, that was intentional.  Those are the only two blocks that provide inl.  The rest use the two-file pattern, and have a closed set of valid types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3255)*

**Pull request merged**
