### PR TITLE
Disable runAtlasDynamics

### PR DESCRIPTION
**Pull request by jamiesnape**
While I investigate #4513. Relates also to #4512.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4514)

### CODE REVIEW

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-experimental-matlab/1804/

**Comment by jwnimmer-tri** [comment]
:lgtm: for merge.

FYI @russtedrake on an Atlas test being disabled for investigation.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4514#-:-KZ28cak2CtSURFdjNiy:b-9z2lvk)*

**Comment by RussTedrake** [comment]
@jamiesnape  -- the link to cdash above doesn't find any results.   can you point me to a working test failure?

**Comment by jwnimmer-tri** [comment]
IIRC all the failures were just "timeout" with no output.  See the Dec 14th yellow results here, for example: [linux-gcc-continuous-matlab-release](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-gcc-continuous-matlab-release/).

**Comment by jamiesnape** [comment]
Yes, I think the test is hanging somewhere.

**Pull request merged**
