### PR TITLE
Solvers common solver options

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12983)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
(1) Instead of trying to in-process capture the output (possible, but finicky and possibly solver-specific depending on which APIs they are using to print), write the test case in python using a simple C++ device under test.  So have `drake_cc_binary(name = "common_print_test_fixture", testonly = True, ...)` that defines some program to solve, along with gflags to choose a solver and toggle the common options.  Then write a `drake_py_unittest()` that uses `subprocess.run` (or `check_output`, etc.) to invoke the device with different options.  With printing off, the output should be empty. With printing on, it should be at lease N kilobytes.

(2) I don't think we should throw.  For SolverOptions::SetOption we decided to silently ignore unsupported cases, so I think we should be consistent here.  We just have to choose which one wins.  Since a solver-specific option seems more specific than a generic option, I think the solver-specific option should win -- in general, the specific options should fine-tune the general options, not the other way around.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai This might be nice to pick up again, helps with some tutorials & etc?

**Comment by hongkai-dai** [comment]
> @hongkai-dai This might be nice to pick up again, helps with some tutorials & etc?

Good call, I will work on it.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
This PR is six months stale. If it's no longer being worked, please close it.

**Pull request closed without merging**
