### PR TITLE
Redefine all maliput ID types using TypeSpecificIdentifier<T>.

### PR DESCRIPTION
**Pull request by maddog-tri**
This also removes the (apparently unused) `operator<<(std::ostream&, ...)` for the ID types that had one (in favor of continuing the existing practice of using an ID's `string()` method to `<<` it).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6946)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@seancurtis-tri for feature review, please.

Heads up to @liangfok: this PR removes the `operator<<()` which you had added.  I didn't see any actual use of those operators, and it seemed more straightforward (and already widely practiced) to just access an id's `string()` for printing.

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-KstNPira4aKrRlulmpt:b44vd4d)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: 

Sorry for the delay. 

FTR You could have foregone the forward declaration by simply:

```C++
using FooId = TypeSpecificIdentifer<class FooTag>;
```

I believe you're already aware of this, I thought I'd go ahead and stamp this on the PR just to be official.

---

Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-KsuMuJvXNA-KrHZhFbj:bwmqq8i)*

**Comment by maddog-tri** [comment]
+@sherm1 for platform review.  Unfortunately, it is a rather dull review.

---

Review status: 44 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-KsvxaHC-jb0ZuI45g1c:b-nvkdtr)*

**Comment by sherm1** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by sherm1** [comment]
Platform :lgtm:. A few BTWs re tidying up a few things, ptal.

---

Reviewed 44 of 45 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/automotive/maliput/api/branch_point.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-Ksy1r20bwlFen33WjGI:-Ksy1r21eVmHbbNEO6Y8:b4gxu1d) ([raw file](https://github.com/robotlocomotion/drake/blob/c953f5fcb20fdc6534d440ceb620f0b1fccbd8ba/drake/automotive/maliput/api/branch_point.h#L18)):*
> ```objc
> 
> // Persistent identifier for a BranchPoint element.
> using BranchPointId = TypeSpecificIdentifier<BranchPoint>;
> ```

BTW prefer `TypeSpecificIdentifier<class BranchPoint>` over the forward declaration if you don't have other uses for BranchPoint in this file because that makes it clear at a glance the limited scope for this declaration (META).

---

*[drake/automotive/maliput/api/road_geometry.cc, line 152 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-Ksy3pTIm4YaiUDzucxP:-Ksy3pTIm4YaiUDzucxQ:bsvcbjr) ([raw file](https://github.com/robotlocomotion/drake/blob/c953f5fcb20fdc6534d440ceb620f0b1fccbd8ba/drake/automotive/maliput/api/road_geometry.cc#L152)):*
> ```cpp
>            << jnx->id().string()
>            << " (" << jnx << ") but claims to be owned by "
>            << seg->junction()->id().string() << " (" << seg->junction() << ").";
> ```

BTW the `.string()`s here are repetitive clutter. Consider instead implicit conversion of TypeSpecificIdentifier to string (analogous to TypeSafeIndex's implicit conversion to int).

---

*[drake/automotive/maliput/dragway/dragway_to_urdf.cc, line 46 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-Ksy4kwD3yAkFNtkBMlP:-Ksy4kwD3yAkFNtkBMlQ:bm07j16) ([raw file](https://github.com/robotlocomotion/drake/blob/c953f5fcb20fdc6534d440ceb620f0b1fccbd8ba/drake/automotive/maliput/dragway/dragway_to_urdf.cc#L46)):*
> ```cpp
>   RoadGeometry road_geometry(
>       api::RoadGeometryId{
>         "Dragway with " + std::to_string(FLAGS_num_lanes) + " lanes."},
> ```

FYI elsewhere you separated words in Ids with "_". Here there are blanks. Just mentioning it in case you don't want blanks in ids.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-Ksy6VGK0VA47H6oQtUi:b2sq8zu)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/automotive/maliput/api/branch_point.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-Ksy1r20bwlFen33WjGI:-KsyhcyE0t2yH7ENFxz0:b8qb518) ([raw file](https://github.com/robotlocomotion/drake/blob/c953f5fcb20fdc6534d440ceb620f0b1fccbd8ba/drake/automotive/maliput/api/branch_point.h#L18)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW prefer `TypeSpecificIdentifier<class BranchPoint>` over the forward declaration if you don't have other uses for BranchPoint in this file because that makes it clear at a glance the limited scope for this declaration (META).
</blockquote></details>

BTW I like that -- I almost recommended something *almost* as good. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946)*

**Comment by maddog-tri** [comment]
Done (one of them), and some more API-change propagation to deal with a merge conflict.

---

Review status: 39 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/maliput/api/branch_point.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-Ksy1r20bwlFen33WjGI:-Ksykyo4tflLpThaYsF2:b5xpc1n) ([raw file](https://github.com/robotlocomotion/drake/blob/c953f5fcb20fdc6534d440ceb620f0b1fccbd8ba/drake/automotive/maliput/api/branch_point.h#L18)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I like that -- I almost recommended something *almost* as good. 
</blockquote></details>

Done.  (Fine, fine, I did it.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-KszAAAwpkaVYxb817AJ:b-55nnym)*

**Comment by sherm1** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946)*

**Comment by maddog-tri** [comment]
:car:'ing myself, on account of tweaking `monolane` (and, yes, keeping `multilane` in sync).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6946#-:-KszHbT6dMsyIzwn-O8M:b1u694b)*

**Pull request merged**
