### PR TITLE
Add and use drake_install_pkg_config_file function

### PR DESCRIPTION
**Pull request by jamiesnape**
Part one of various install related refactor, for the benefit of packaging, fixing the intermingling of drake headers and those of other externals, and removing PODs.

A lot of the previous pkg-config files were completely wrong. I am hoping medium to long term that we do not need them, but they are fixed for now.

Really this should be a no-op for the purposes of building and testing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4123)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcm/CMakeLists.txt, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWYxGCboDh7x6NLqY__:-KWYxGCeqSQ2KEl-MVa6:b-mniw8c) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c56fb7095d5e5f56ae8860980cdcf871bc94c4/drake/lcm/CMakeLists.txt#L39)):*
> ```CMake
>       drakeLCMTypes
>       lcm)
>   set(lcm_dependent_requires drake-lcm-types lcm)
> ```

This doesn't match. The actual dependency (i.e. `drakeLCMTypes`, just above) is on the C++ bindings, but here you are adding a pkg-config dependency on the C bindings. (The same happens in several other places.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123)*

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcmtypes/CMakeLists.txt, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWctb5pkeaL_hea8qMz:-KWctb5q_ChsN3azCWFz:bh1yi9y) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb69ed5691774fbe3b5484e5e5e15c34a3b430/drake/lcmtypes/CMakeLists.txt#L55)):*
> ```CMake
>   $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>)
> 
> drake_install_pkg_config_file(drake-lcm-types-c
> ```

I am maybe not the right person to give an authoritative opinion, but generally the CMake target names for LCM bindings are `foo-lcmtypes`and `foo-lcmtypes-cpp`, so it might make sense to stick with this convention for the `.pc` files. (I wouldn't mind a second opinion, though...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123)*

**Comment by jamiesnape** [comment]
Review status: 0 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/lcm/CMakeLists.txt, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWYxGCboDh7x6NLqY__:-KWe31zWFtVpm4yzGooM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c3c56fb7095d5e5f56ae8860980cdcf871bc94c4/drake/lcm/CMakeLists.txt#L39)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This doesn't match. The actual dependency (i.e. `drakeLCMTypes`, just above) is on the C++ bindings, but here you are adding a pkg-config dependency on the C bindings. (The same happens in several other places.)
</details>
Done.

---

*[drake/lcmtypes/CMakeLists.txt, line 55 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWctb5pkeaL_hea8qMz:-KWe34D5sErgUrxJEIyM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/37bb69ed5691774fbe3b5484e5e5e15c34a3b430/drake/lcmtypes/CMakeLists.txt#L55)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I am maybe not the right person to give an authoritative opinion, but generally the CMake target names for LCM bindings are `foo-lcmtypes`and `foo-lcmtypes-cpp`, so it might make sense to stick with this convention for the `.pc` files. (I wouldn't mind a second opinion, though...)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123)*

**Comment by mwoehlke-kitware** [comment]
Reviewed 1 of 6 files at r3.
Review status: 1 of 38 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/pods.cmake, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnHNhxxyf949iR9CMn:-KWnHNhytpi0X_MGDw0H:b-lptlcm) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/cmake/pods.cmake#L39)):*
> ```CMake
> function(pods_install_libraries)
>     install(TARGETS ${ARGV}
>       RUNTIME DESTINATION bin
> ```

pedantic: not `DRAKE_INSTALL_BINARY_DIR` via `CMAKE_INSTALL_BINDIR`?

---

*[cmake/pods.cmake, line 226 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnH34Vjy_gHfzmc-66:-KWnH34WtYWLHmeSVlln:b2a3o6r) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/cmake/pods.cmake#L226)):*
> ```CMake
>       # set where files should be installed to
>       set(LIBRARY_INSTALL_PATH "${DRAKE_LIBRARY_DIR}")
>       set(EXECUTABLE_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/bin)
> ```

pedantic: see above

---

*[drake/multibody/collision/CMakeLists.txt, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnP5lP9gSPl5oL8a9E:-KWnP5lP9gSPl5oL8a9F:b-pevamy) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/drake/multibody/collision/CMakeLists.txt#L11)):*
> ```CMake
> add_library_with_exports(LIB_NAME drakeCollision SOURCE_FILES ${drakeCollision_SRC_FILES})
> 
> set(drakeCollision_REQUIRES)
> ```

pedantic: `bullet_dependent_requires` for consistency with similar patterns elsewhere?

---

*[drake/util/CMakeLists.txt, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnPcwl0OviZlHR91A6:-KWnPcwl0OviZlHR91A7:b-10fv5t) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/drake/util/CMakeLists.txt#L21)):*
> ```CMake
>     LIBS
>       -ldrakeLCMUtil
>       -llcmtypes_bot2-core-cpp
> ```

This seems like it should rather be a `REQUIRES`, especially as isn't this not-a-library?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123)*

**Comment by jamiesnape** [comment]
Review status: 1 of 38 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmake/pods.cmake, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnHNhxxyf949iR9CMn:-KWnZlgWCYb63Znnqu0t:bw2z5b0) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/cmake/pods.cmake#L39)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: not `DRAKE_INSTALL_BINARY_DIR` via `CMAKE_INSTALL_BINDIR`?
</details>
Done. `DRAKE_INSTALL_RUNTIME_DIR` / `DRAKE_RUNTIME_DIR`. Using `BINARY` confuses me too much.

---

*[cmake/pods.cmake, line 226 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnH34Vjy_gHfzmc-66:-KWnZl50QfzoGF0buH0x:bzd6zrr) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/cmake/pods.cmake#L226)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: see above
</details>
Done. See above.

---

*[drake/multibody/collision/CMakeLists.txt, line 11 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnP5lP9gSPl5oL8a9E:-KWnZkCme8UGCVz5GD60:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/drake/multibody/collision/CMakeLists.txt#L11)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: `bullet_dependent_requires` for consistency with similar patterns elsewhere?
</details>
Done.

---

*[drake/util/CMakeLists.txt, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnPcwl0OviZlHR91A6:-KWnTc8KINcG4filFrqs:b-qxjy1v) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/drake/util/CMakeLists.txt#L21)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This seems like it should rather be a `REQUIRES`, especially as isn't this not-a-library?
</details>
Looks like that .pc file does not exist. Removed the linker flag and added a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123)*

**Comment by mwoehlke-kitware** [comment]
:lgtm: with the caveat that I didn't try to validate the dependencies

---

Review status: 1 of 38 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/pods.cmake, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnHNhxxyf949iR9CMn:-KWnawikuxdFWPld53ye:b-zlx8w) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/cmake/pods.cmake#L39)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Done. `DRAKE_INSTALL_RUNTIME_DIR` / `DRAKE_RUNTIME_DIR`. Using `BINARY` confuses me too much.
</details>
WFM; I very nearly suggested that myself.

---

*[drake/util/CMakeLists.txt, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-KWnPcwl0OviZlHR91A6:-KWnbGWAAuqxnNg8HlP-:b-d55kov) ([raw file](https://github.com/robotlocomotion/drake/blob/4927dca7effe9b65682835425fe3c28983922e72/drake/util/CMakeLists.txt#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Looks like that .pc file does not exist. Removed the linker flag and added a TODO.
</details>
I suspected as much. The TODO is fine for now; the spurious library probably would have been a problem :wink:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-:-KWnba-hd-esllCiHUwA:beuou7w)*

**Comment by jamiesnape** [comment]
+@david-german-tri for feature review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by david-german-tri** [comment]
@wxmerkt, would you like to check that this doesn't blow up anything for you before we merge it?

---

Reviewed 1 of 38 files at r1.
Review status: 2 of 38 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-:-KWoKzFkuGGJRhnblO5r:b-govzgi)*

**Comment by jamiesnape** [comment]
From #3827, @wxmerkt was using drake-ik.pc, drake-rbm.pc, drake-rigid-body-plant.pc, drake-qp-common.pc. I will double check those on the command line, though I am not convinced they were up-to-date with the current state of master anyway.

**Comment by wxmerkt** [comment]
@david-german-tri and @jamiesnape Thanks for checking - LGTM, I don't see this affecting us (no change in targets/generated pkg-configs)

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 38 files at r1, 27 of 35 files at r2, 5 of 6 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4123#-:-KWoYQ-EAoXCQWtaznSL:bnfp4nl)*

**Pull request merged**
