### PR TITLE
Fix documentation destination

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Install documentation to `share/doc/drake`, not just `share/doc`. This properly respects FHS and leverages the same install destination logic used for other components.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4473)

### CODE REVIEW

**Comment by liangfok** [comment]
BTW, what does "FHS" stand for? http://www.acronymfinder.com/FHS.html

**Comment by jwnimmer-tri** [comment]
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by mwoehlke-kitware** [comment]
...and on that note, I'm not sure FHS itself actually specifies that doc should go in a subdirectory of `share/doc`... but it's certainly convention, for reasons that should be obvious.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4473#-:-KYodUdXOucVDOFbUAHQ:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4473#-:-KYp3a3pEyUeCz00KZmb:bnfp4nl)*

**Pull request merged**
