### PR TITLE
[tutorials] Add tutorial for using Mosek on Deepnote

### PR DESCRIPTION
**Pull request by RussTedrake**
I have hosted the tutorial draft [here](https://deepnote.com/workspace/russtedrake-b58d8141-6691-43e8-ad76-0575b319c8b8/project/Enabling-licensed-solvers-on-Deepnote-7581ca0c-04be-4632-9108-f0426b6c3fbb/%2Flicensed_solvers_deepnote.ipynb) for code review.

+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IddzD5I8SJ7wjwwHQ:-N2IddzD5I8SJ7wjwwHR:b-qqgt9x) (no related file):*
I'm not wild about the "be careful" security model. Have you talked with the Deepnote folks about a more secure way of dealing with secrets that have to live on the file system? 

I checked, and it looks like both terminals and the jupyter notebook itself run as root. Given that, there's probably not a reasonable way to secure a license file without either feature support from Deepnote or, say, changes to the way mosek consumes the license data.

___
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IZS2yC3_4a1pTiQLv:-N2IZS2yC3_4a1pTiQLw:b-otz08j) ([raw file](https://github.com/robotlocomotion/drake/blob/7371dc08329303a3323ccb0528b19656cb71d916/tutorials/licensed_solvers_deepnote.ipynb#L41)):*
> ```
>     "## Mosek\n",
>     "\n",
>     "* If you don't have one, obtain a Mosek license. If have academic status, then you can obtain a [free personal academic license](https://www.mosek.com/products/academic-licenses/).\n",
> ```

typo/grammar/missing word?



_Suggestion:_
```
If you have
```
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IcGmj3d3I_lYQB3hB:-N2IcGmj3d3I_lYQB3hC:b10hgtc) ([raw file](https://github.com/robotlocomotion/drake/blob/7371dc08329303a3323ccb0528b19656cb71d916/tutorials/licensed_solvers_deepnote.ipynb#L127)):*
> ```
>     "from pydrake.solvers.mosek import MosekSolver\n",
>     "\n",
>     "print(MosekSolver().available())"
> ```

In my experiments, `.available()` returns `True` even if I don't provide a license. Should this be saying `.enabled()` instead?

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IddzD5I8SJ7wjwwHQ:-N2IglWsE697S3meFB4I:bgoduzw) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'm not wild about the "be careful" security model. Have you talked with the Deepnote folks about a more secure way of dealing with secrets that have to live on the file system? 

I checked, and it looks like both terminals and the jupyter notebook itself run as root. Given that, there's probably not a reasonable way to secure a license file without either feature support from Deepnote or, say, changes to the way mosek consumes the license data.
</blockquote></details>

The main challenge is that MOSEK _itself_ requires the license secrets to be in a file, with the environment variable giving the full pathname to that file.  Even if the the at-rest storage is other than a file, we'd still need to blat it into a filename immediately prior to calling into MOSEK.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 5 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IddzD5I8SJ7wjwwHQ:-N2J5TUW0HF3LPFOv7s6:b-2s49dx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The main challenge is that MOSEK _itself_ requires the license secrets to be in a file, with the environment variable giving the full pathname to that file.  Even if the the at-rest storage is other than a file, we'd still need to blat it into a filename immediately prior to calling into MOSEK.
</blockquote></details>

Oh, understood that mosek is the root of the problem (or rather, flexlm). Maybe this is the best we can do.

___

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IddzD5I8SJ7wjwwHQ:-N2J6Vvi3B1xIiez_HzW:b4ztwtf) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Oh, understood that mosek is the root of the problem (or rather, flexlm). Maybe this is the best we can do.
</blockquote></details>

I just realized -- one thing we probably _should_ do is to use `os.environ.get("MOSEKLM_LICENSE_FILE")` as the guard for "should I ask for a license file", not the current file-exists test for something in tmp.  That is more robust and correct in general.  If the user already set the environment, we'd obey it.

Then, when we prompt the user for the upload, we could choose stash it into a `tempfile` with a salted obscure name, instead of a hard-coded path.  In practice it is not any more secure since we're running as root, but at least the obvious snafu `$ cat /tmp/mosek.lic` wouldn't work.  Shrug.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IddzD5I8SJ7wjwwHQ:-N2JcjkU1fHWOSTjcT4s:b-8eeirh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I just realized -- one thing we probably _should_ do is to use `os.environ.get("MOSEKLM_LICENSE_FILE")` as the guard for "should I ask for a license file", not the current file-exists test for something in tmp.  That is more robust and correct in general.  If the user already set the environment, we'd obey it.

Then, when we prompt the user for the upload, we could choose stash it into a `tempfile` with a salted obscure name, instead of a hard-coded path.  In practice it is not any more secure since we're running as root, but at least the obvious snafu `$ cat /tmp/mosek.lic` wouldn't work.  Shrug.
</blockquote></details>

Based on my testing with tmpfile, it seems that that mosek will not accept any filename except `mosek.lic`. I've made the other changes.

___
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 127 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2IcGmj3d3I_lYQB3hB:-N2JceLJEsRxV6M2FzDy:b-gczyub) ([raw file](https://github.com/robotlocomotion/drake/blob/7371dc08329303a3323ccb0528b19656cb71d916/tutorials/licensed_solvers_deepnote.ipynb#L127)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

In my experiments, `.available()` returns `True` even if I don't provide a license. Should this be saying `.enabled()` instead?
</blockquote></details>

Done.  Yikes.  Good catch!
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2HfaUt5IOxOHz6bqeB:-N2Jchg_7nLE47QIUFwe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7371dc08329303a3323ccb0528b19656cb71d916/tutorials/licensed_solvers_deepnote.ipynb#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit., consider to spell out `Trace` instead of `tr`. The reader might not be familiar with the abbreviation.
</blockquote></details>

Done.
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2HfrRL4nGyJTRlPtUi:-N2Jcihh27PsGXvHSDOB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7371dc08329303a3323ccb0528b19656cb71d916/tutorials/licensed_solvers_deepnote.ipynb#L174)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @hongkai-dai, @rpoyner-tri, and @RussTedrake)

___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2KG16x2xTpx9M00QvI:-N2KG16x2xTpx9M00QvJ:b-xdfzpq) ([raw file](https://github.com/robotlocomotion/drake/blob/c11473662d5abb4d347970f3f913cfc4bc8c70b4/tutorials/licensed_solvers_deepnote.ipynb#L34)):*
> ```
>    "metadata": {
>     "cell_id": "fc8df00050fd40649e7512adb3c0b6cd",
>     "deepnote_cell_height": 310.1875,
> ```

nit Huh, I thought our linter complained about this meta-data (fields starting with `deepnote_`).  Do we want this in source control?  Probably worth culling it.  Similarly for "execution_millis" and etc. below.

(Zach had this too and removed it by hand -- I thought that was him obeying the linter, but I guess he was just being extra careful with his self-review!)
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2KEgLf0M_aByLs7e9J:-N2KEgLf0M_aByLs7e9K:baucn4v) ([raw file](https://github.com/robotlocomotion/drake/blob/c11473662d5abb4d347970f3f913cfc4bc8c70b4/tutorials/licensed_solvers_deepnote.ipynb#L70)):*
> ```
>     "import os.path\n",
>     "\n",
>     "import ipywidgets as widgets  # Our use requires ipywidgets >= 7.5.0\n",
> ```

Where will this version come from, in the deployed tutorial in the tutorials folder?  I think we might be missing something in this PR, I don't think this version is part of our tutorials' deepnote Environment yet.

The [release playbook](https://drake.mit.edu/release_playbook.html) gives the contents of the `Dockerfile` and `init.ipynb` which are deployed.  I suspect what you'll want to do is specify that we also use a `requirements.txt` file for the tutorials now, with that line as its only content for now.  (Do that by editing the playbook.)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 2 unresolved discussions, missing label for release notes (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
I've addressed all reviewer feedback.  But something seems to have changed, and now mosek core dumps on deepnote on my trivial problem instance.  I've been struggling to debug it.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai, @jwnimmer-tri, and @rpoyner-tri)

___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2KG16x2xTpx9M00QvI:-N2RaQcp9bUBeeZnvQqH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c11473662d5abb4d347970f3f913cfc4bc8c70b4/tutorials/licensed_solvers_deepnote.ipynb#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Huh, I thought our linter complained about this meta-data (fields starting with `deepnote_`).  Do we want this in source control?  Probably worth culling it.  Similarly for "execution_millis" and etc. below.

(Zach had this too and removed it by hand -- I thought that was him obeying the linter, but I guess he was just being extra careful with his self-review!)
</blockquote></details>

Done.
___
*[`tutorials/licensed_solvers_deepnote.ipynb` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17213#-N2KEgLf0M_aByLs7e9J:-N2RaPP-1RPp0t8NcSqO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c11473662d5abb4d347970f3f913cfc4bc8c70b4/tutorials/licensed_solvers_deepnote.ipynb#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Where will this version come from, in the deployed tutorial in the tutorials folder?  I think we might be missing something in this PR, I don't think this version is part of our tutorials' deepnote Environment yet.

The [release playbook](https://drake.mit.edu/release_playbook.html) gives the contents of the `Dockerfile` and `init.ipynb` which are deployed.  I suspect what you'll want to do is specify that we also use a `requirements.txt` file for the tutorials now, with that line as its only content for now.  (Do that by editing the playbook.)
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM on the playbook edits.

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213#-:-N2RlCUqAjuIUKqcHPt1:b9jg0kf)* status: missing label for release notes (waiting on @hongkai-dai and @rpoyner-tri)

**Comment by RussTedrake** [comment]
I've documented the mosek crash and proposed fix here: https://github.com/RobotLocomotion/drake/issues/17237 .  I will resolve that first, then merge this.

**Review by RussTedrake — COMMENTED** [review]
#17237 is now merged.  I will merge this now as well, and upload the tutorial manually to deepnote tomorrow (using the nightly binaries), per the recommendation in `tutorials/_developers.md` and `release_playbook.md`.  

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17213#-:-N2XpsrcCwYk6k2Smnqh:b-yvv26x)* status: missing label for release notes (waiting on @RussTedrake)

**Comment by RussTedrake** [comment]
N.B. -- I've updated the Deepnote tutorials (and confirmed that the mosek notebook succeeds on AMD hardware).

**Comment by jwnimmer-tri** [comment]
@RussTedrake Probably the documentation here could be improved, but see https://drake.mit.edu/release_playbook.html#post-release-tutorials-updates for instructions -- specifically steps 4 and 5.  Poking around now, it seems like all of the tutorials _except_ for the new one do not have any output cells.  I think you still need to do step 5 -- opening each notebook one by one and running it, both to ensure that it works correctly with the new version of Drake, and to populate all of the output cells.

**Comment by RussTedrake** [comment]
Done.

**Pull request merged**
