### PR TITLE
[math] Reduce implementation boilerplate for autodiff

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Requires #17497.  Towards #17492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516#-:-N6Pe0e5BNYcQRr_Qw9t:bnfp4nl)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong:. Simply awesome! 
There are some subtle changes to handling of row-ordered matrices here (as we discussed when you introduced MatrixLikewise). I don't think they are worth mentioning though.

A few minor comments/questions below.

> Reviewed 1 of 2 files at r2, 3 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516#-:-N6nNK5AE-Ido9jQSSim:b-ydzhnv)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`math/autodiff.h` line 184 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6nKgqY-icyyXjSK9Bv:-N6nKgqY-icyyXjSK9Bw:bcz6jh0) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L184)):*
> ```objc
> first argument. Subsequent derivative vector elements correspond first to
> subsequent elements of the first input argument (traversed first by row, then by
> column), and so on for subsequent arguments.
> ```

nit: this parenthetical seems wrong now (maybe it always was). The elements will be traversed in their storage order which depends on the row vs col ordering of the input matrices.
___
*[`math/autodiff.h` line 222 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6nL--D6uALyGdZ2ITz:-N6nL--D6uALyGdZ2IU-:b-9t3wl0) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L222)):*
> ```objc
>   }(std::make_index_sequence<N>{});
> 
>   return result;
> ```

BTW Wow! This is SO MUCH BETTER. Beautiful metaprogramming.
___
*[`tools/skylark/drake_cc.bzl` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6nMlGf8iQ31A4IsASP:-N6nMlGf8iQ31A4IsASQ:b-22mybh) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/tools/skylark/drake_cc.bzl#L36)):*
> ```Starlark
>     "-Wno-c++20-designator",
>     # It's fine for Drake to use any C++20 extensions that pass our CI.
>     "-Wno-c++20-extensions",
> ```

minor: not clear to me why this is in this PR. Is it necessary? If so should add to PR description since (I presume) it affects all of Drake.

Also I'm confused by the comment -- it says "ok to use extensions" but then the flag says "no extensions"

**Comment by jwnimmer-tri** [comment]
*[`math/autodiff.h` line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6ntp5QBJ8RZXX7SXt-:-N6ntp5QBJ8RZXX7SXt0:b-ws3q36) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L165)):*
> ```objc
>     std::optional<int> num_derivatives = {},
>     std::optional<int> deriv_num_start = {}) {
>   AutoDiffMatrixType<Derived, nq> auto_diff_matrix(value.rows(), value.cols());
> ```

@sherm1 You're comment below got me thinking.

I think now maybe this PR is a notable bugfix?

In the overload that we delegate to from here, it assigns from value(i) which could be row-major into auto_diff_matrix(i) which was previously always column-major.  I think that would end up transposing the result vs the input?

If you agree, I'll update the PR overview and label to remark upon this.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

___
*[`math/autodiff.h` line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6ntp5QBJ8RZXX7SXt-:-N6o7kNp5EVoF9puloK-:bilc6nf) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L165)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 You're comment below got me thinking.

I think now maybe this PR is a notable bugfix?

In the overload that we delegate to from here, it assigns from value(i) which could be row-major into auto_diff_matrix(i) which was previously always column-major.  I think that would end up transposing the result vs the input?

If you agree, I'll update the PR overview and label to remark upon this.
</blockquote></details>

Upgraded myself to blocking here.

I'm pretty convinced that _this_ function is now correct (and was incorrect before), but even more importantly the output-argument overloads for `InitializeAutodiff()` above are wrong -- they assign from value into result using the 1-arg `operator(i)`, but there's no checking that the storage orders are compatible.

I think we never noticed because typically the value matrices are most often just 1xN or Nx1, and in any case that RowMajor would be rare.  It would be a problem for numpy matrices fed in here from pydrake, except that we force a copy to MatrixXd (col major) at the interface layer currently.

I'll work on adding a static_assert (probably) to deal with this.
___
*[`math/autodiff.h` line 184 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6nKgqY-icyyXjSK9Bv:-N6o7jRt5Io17JWdRzVK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L184)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this parenthetical seems wrong now (maybe it always was). The elements will be traversed in their storage order which depends on the row vs col ordering of the input matrices.
</blockquote></details>

Done.
___
*[`tools/skylark/drake_cc.bzl` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6nMlGf8iQ31A4IsASP:-N6nrEWu1vDnK1Haw5_j:bwrz57p) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/tools/skylark/drake_cc.bzl#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not clear to me why this is in this PR. Is it necessary? If so should add to PR description since (I presume) it affects all of Drake.

Also I'm confused by the comment -- it says "ok to use extensions" but then the flag says "no extensions"
</blockquote></details>

Done.

The _templated_ lambda syntax `[&]<size_t... I>(` is a C++20 feature.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6oTvUx9sDo4vMdUbuF:-N6oTvUy9MZ6lu9JqkxV:b-r7ftxv) (no related file):*
@sherm1 this has changed in notable ways now.  Please take another look and then dismiss this thread after you've looked at the latest update.

___
___
*[`math/autodiff.h` line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6ntp5QBJ8RZXX7SXt-:-N6oTu87BwQgJfDEK5lI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L165)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Upgraded myself to blocking here.

I'm pretty convinced that _this_ function is now correct (and was incorrect before), but even more importantly the output-argument overloads for `InitializeAutodiff()` above are wrong -- they assign from value into result using the 1-arg `operator(i)`, but there's no checking that the storage orders are compatible.

I think we never noticed because typically the value matrices are most often just 1xN or Nx1, and in any case that RowMajor would be rare.  It would be a problem for numpy matrices fed in here from pydrake, except that we force a copy to MatrixXd (col major) at the interface layer currently.

I'll work on adding a static_assert (probably) to deal with this.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 1 unresolved discussion (waiting on @rpoyner-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6oTvUx9sDo4vMdUbuF:-N6sHqy70GkmaiGKzi_l:b-f9tjfa) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 this has changed in notable ways now.  Please take another look and then dismiss this thread after you've looked at the latest update.
</blockquote></details>

Re-reviewed with a few comments, ptal.

___
___
*[`math/autodiff.h` line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6ntp5QBJ8RZXX7SXt-:-N6sG8Kg9biTS0L_4__6:bttyiyh) ([raw file](https://github.com/robotlocomotion/drake/blob/97c3949564547d1879d8bb142f3e9a0f9d20749d/math/autodiff.h#L165)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yup, I agree. Much better now.
___
*[`math/autodiff.h` line 160 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6sH5t25BoHrOaI3_u-:-N6sH5t25BoHrOaI3_u0:b9v2y5w) ([raw file](https://github.com/robotlocomotion/drake/blob/f57af4247db40c08bdfa193e0f8938a25c2b045c/math/autodiff.h#L160)):*
> ```objc
> When `value` is a matrix (rather than just a vector) note in particular that
> the return value will use the same storage order (ColMajor vs RowMajor) and
> that the derivative numbers count up using the _storage order_ of `value(i)`.
> ```

minor: should note the bad behavior of the gradient in case the input is row ordered, or forbid row order with > 1 row.
___
*[`math/test/autodiff_test.cc` line 218 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6sHC4gDJUOQwm-eenG:-N6sHC4gDJUOQwm-eenH:bbap7kw) ([raw file](https://github.com/robotlocomotion/drake/blob/f57af4247db40c08bdfa193e0f8938a25c2b045c/math/test/autodiff_test.cc#L218)):*
> ```cpp
>   // This might not be the most intuitive answer (and so, it'd be okay to
>   // change our mind later about what this should be) but in any case we
>   // should have a test case here to demonstrate the current reality.
> ```

minor: Yikes! This comment should appear in the documentation for InitializeAutoDiff().

I wonder if we should just forbid row-ordered matrices unless there is only one row?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 2 unresolved discussions (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`math/autodiff.h` line 160 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6sH5t25BoHrOaI3_u-:-N6xpwQS1NwV9E182c_p:b-ux0jgx) ([raw file](https://github.com/robotlocomotion/drake/blob/f57af4247db40c08bdfa193e0f8938a25c2b045c/math/autodiff.h#L160)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think the idea you're getting at here was a problem with ExtractGradient, not with InitializeAutoDiff?  I've adjusted ExtractGradient in any case.  Let me know if I've overlooked a problem at this location.
</blockquote></details>

Right, I incorrectly blamed InitializeAutoDiff.
___
*[`math/autodiff_gradient.h` line 36 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6xqWCGCCWugOzy4ddJ:-N6xqWCGCCWugOzy4ddK:bdjy7zf) ([raw file](https://github.com/robotlocomotion/drake/blob/5aa04df9f6c4cceac5c2e4a91cd778293c1b6019/math/autodiff_gradient.h#L36)):*
> ```objc
>     the typical case of a RowMajor `auto_diff_matrix`, we have
>     `auto_diff_matrix(r, c).derivatives() ==
>     gradient_matrix.row(r + c * auto_diff_matrix.rows())`.
> ```

Did you mean to say "ColMajor" above? 
___
*[`math/test/autodiff_test.cc` line 218 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6sHC4gDJUOQwm-eenG:-N6xrIXK-CsOBrAoSp40:bon4vnk) ([raw file](https://github.com/robotlocomotion/drake/blob/f57af4247db40c08bdfa193e0f8938a25c2b045c/math/test/autodiff_test.cc#L218)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I took another look over the code.  I think that since we're using MatrixLikewise everywhere now, we should simultaneously just +(release notes: breaking change) on `ExtractGradient` to change its contract to follow storage order.
</blockquote></details>

Agreed, nice.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: labeled "do not merge" (waiting on @rpoyner-tri and @sherm1)

___
*[`math/autodiff_gradient.h` line 36 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17516#-N6xqWCGCCWugOzy4ddJ:-N6xssZwDbicAB2FgR5R:b6zrrk4) ([raw file](https://github.com/robotlocomotion/drake/blob/5aa04df9f6c4cceac5c2e4a91cd778293c1b6019/math/autodiff_gradient.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Did you mean to say "ColMajor" above? 
</blockquote></details>

Good catch!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17516)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
