### PR TITLE
Add ComputeQ to rational forward kinematics

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai This is still a WIP. Noticeably, i still need to test the Autodiff version of the templated `ComputeSValue` and `ComputeQValue` and I expect you will want me to test `IsRevolute` and related functions. I am not quite sure how to test these, and also would like your thoughts on the current WIP. 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476#-:-NJbhjRp-mXOzuGnuRVF:b-tv8mbi)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 5 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`multibody/rational/rational_forward_kinematics.h` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcEy3t573j_2D1VJdW:-NJcEy3t573j_2D1VJdX:b-s23me0) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L11)):*
> ```objc
> #include "drake/common/symbolic/trigonometric_polynomial.h"
> #include "drake/multibody/plant/multibody_plant.h"
> #include "drake/multibody/rational/rational_forward_kinematics_internal.h"
> ```

It is better NOT to include `rational_forward_kinematics_internal.h` in this header file. In the documentation of `rational_forward_kinematics_internal.h`, we said that the user should not include `rational_forward_kinematics_internal.h`. Now after we put this `_internal.h` in this header file, any user that includes `rational_forward_kinematics.h` will automatically include `rational_forward_kinematics_internal.h`.

I see that you want `rational_forward_kinematics_internal.h` to use `IsWeld`, `IsPrismatic` and `IsRevolute` functions. But I would argue that `rational_forward_kinematics_internal.h` is not the right place for these three functions. These three functions only depend on the mobilizer, so I think they should live somewhere else, close to where `mobilizer.h` lives.

@sherm1 @jwnimmer-tri where would you suggest to put `IsWeld`, `IsPrismatic` and `IsRevolute` function?
___
*[`multibody/rational/rational_forward_kinematics.h` line 110 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcDlejBcXfSs9-ghKB:-NJcDlejBcXfSs9-ghKC:b-lbgn6e) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L110)):*
> ```objc
>    q(i)).
>    */
>   template <typename Derived>
> ```

See the `is_eigen_vector` comment below.
___
*[`multibody/rational/rational_forward_kinematics.h` line 141 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcCTVsAvHhS-FxLRD3:-NJcCTVsAvHhS-FxLRD4:b-fi1jv) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L141)):*
> ```objc
>    */
>   template <typename Derived>
>   [[nodiscard]] VectorX<typename Derived::Scalar> ComputeQValue(
> ```

Could you add SFINAE here? I think we want to enforce `s_val` to be a vector? You could do it either through
```cc
#include "drake/common/eigen_types.h"

template <typename Derived>
[[nodiscard]] std::enable_if_t<is_eigen_vector<Derived>::value, VectorX<typename Derived::Scalar> ComputeQValue(...)
```

Or use a `static_assert` in the function 
```cc
#include "drake/common/eigen_types.h"

template <typename Derived>
[[nodiscard]] VectorX<typename Derived::Scalar> ComputeQValue(...) {
  if constexpr (!is_eigen_vector<Derived>::value) {
    static_assert("q_val should be an Eigen vector.");
  }
}
```
___
*[`multibody/rational/rational_forward_kinematics.h` line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcE43I20f8LAyJDiy_:-NJcE43I20f8LAyJDiya:b-uw2ntb) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L154)):*
> ```objc
>       if (internal::IsRevolute(mobilizer)) {
>         q_val(q_index) =
>             atan2(2 * s_val(i) / (1 + pow(s_val(i), 2)),
> ```

I think you can ignore the denominator `(1 + pow(s_val(i), 2)` here?
```cc
q_val(q_index) = atan2(2 * s_val(i), 1 - pow(s_val(i), 2)) + q_star_val(q_index);
```
___
*[`multibody/tree/articulated_body_inertia.h` line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcPGQ-B8K0cAIp3wL-:-NJcPGQ-B8K0cAIp3wL0:bnftns4) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/tree/articulated_body_inertia.h#L18)):*
> ```objc
> /// _Articulated %Body Inertia_ is the inertia that a body appears to have when
> /// it is the base (or root) of a rigid-body system, also referred to as
> /// _Articulated %Body_ in the context ofg articulated body algorithms.
> ```

This change is unintentional?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 5 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice, @hongkai-dai, and @jwnimmer-tri)

___
*[`multibody/rational/rational_forward_kinematics.h` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcEy3t573j_2D1VJdW:-NJfbbRG3RBSotQ7q6XC:b-ppep1v) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L11)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is better NOT to include `rational_forward_kinematics_internal.h` in this header file. In the documentation of `rational_forward_kinematics_internal.h`, we said that the user should not include `rational_forward_kinematics_internal.h`. Now after we put this `_internal.h` in this header file, any user that includes `rational_forward_kinematics.h` will automatically include `rational_forward_kinematics_internal.h`.

I see that you want `rational_forward_kinematics_internal.h` to use `IsWeld`, `IsPrismatic` and `IsRevolute` functions. But I would argue that `rational_forward_kinematics_internal.h` is not the right place for these three functions. These three functions only depend on the mobilizer, so I think they should live somewhere else, close to where `mobilizer.h` lives.

@sherm1 @jwnimmer-tri where would you suggest to put `IsWeld`, `IsPrismatic` and `IsRevolute` function?
</blockquote></details>

My inclination would be to add these to rational_forward_kinematics.h and use the existing mobilizer methods to implement them. Mobilizers have num_positions(), can_rotate(), can_translate() already and you could assume that a 1-dof mobilizer that can_rotate is a revolute, etc.

I'm reluctant to add more virtuals to Mobilizer if we can avoid them.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 6 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgLMCO5H7Ui4UoTBin:-NJgLMCO5H7Ui4UoTBio:baelcpf) (no related file):*
I think this PR includes some changes that shouldn't be here? For example the changes in `geometry_state` and `scene_graph`. Could you rebase or merge the code on the master?

___

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 5 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgLMCO5H7Ui4UoTBin:-NJgLhWo8iCqQstuz3Nt:bqzg8xy) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this PR includes some changes that shouldn't be here? For example the changes in `geometry_state` and `scene_graph`. Could you rebase or merge the code on the master?
</blockquote></details>

OK, now the git diff looks good.

___

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 5 files at r19, 1 of 40 files at r20.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @jwnimmer-tri)

___
*[`multibody/rational/rational_forward_kinematics_internal.h` line 9 at r20](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgM9vV79-roPxhQZ36:-NJgM9vV79-roPxhQZ37:bk3fd6v) ([raw file](https://github.com/robotlocomotion/drake/blob/f19e9a0970590331865b6012c8a8fc657841621f/multibody/rational/rational_forward_kinematics_internal.h#L9)):*
> ```objc
> 
> #include "drake/multibody/plant/multibody_plant.h"
> #include "drake/multibody/tree/prismatic_mobilizer.h"
> ```

These include files are not needed any more?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 4 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgLMCO5H7Ui4UoTBin:-NJgOSON13FeWjJu_p02:b71uq5) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

OK, now the git diff looks good.
</blockquote></details>

Sorry for the spam! I messed up the rebase initially

___
___
*[`multibody/rational/rational_forward_kinematics.h` line 11 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcEy3t573j_2D1VJdW:-NJgNQBsCapbG_A9VdHZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L11)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

My inclination would be to add these to rational_forward_kinematics.h and use the existing mobilizer methods to implement them. Mobilizers have num_positions(), can_rotate(), can_translate() already and you could assume that a 1-dof mobilizer that can_rotate is a revolute, etc.

I'm reluctant to add more virtuals to Mobilizer if we can avoid them.
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics.h` line 110 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcDlejBcXfSs9-ghKB:-NJe_70b64cyqgx5qeR7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L110)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

See the `is_eigen_vector` comment below.
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics.h` line 141 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcCTVsAvHhS-FxLRD3:-NJe_7ZP-eqftsj9dQw5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add SFINAE here? I think we want to enforce `s_val` to be a vector? You could do it either through
```cc
#include "drake/common/eigen_types.h"

template <typename Derived>
[[nodiscard]] std::enable_if_t<is_eigen_vector<Derived>::value, VectorX<typename Derived::Scalar> ComputeQValue(...)
```

Or use a `static_assert` in the function 
```cc
#include "drake/common/eigen_types.h"

template <typename Derived>
[[nodiscard]] VectorX<typename Derived::Scalar> ComputeQValue(...) {
  if constexpr (!is_eigen_vector<Derived>::value) {
    static_assert("q_val should be an Eigen vector.");
  }
}
```
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics.h` line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcE43I20f8LAyJDiy_:-NJe_kPI4ZhM-cuo0Xyp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/rational/rational_forward_kinematics.h#L154)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think you can ignore the denominator `(1 + pow(s_val(i), 2)` here?
```cc
q_val(q_index) = atan2(2 * s_val(i), 1 - pow(s_val(i), 2)) + q_star_val(q_index);
```
</blockquote></details>

Done.
___
*[`multibody/rational/rational_forward_kinematics_internal.h` line 9 at r20](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgM9vV79-roPxhQZ36:-NJgOX0gBoRCZJZKcpIR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f19e9a0970590331865b6012c8a8fc657841621f/multibody/rational/rational_forward_kinematics_internal.h#L9)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

These include files are not needed any more?
</blockquote></details>

Done.
___
*[`multibody/tree/articulated_body_inertia.h` line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJcPGQ-B8K0cAIp3wL-:-NJechvN5Oz_p4BARXer:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6556be367321e0d21c1d940ba07ee306974b5f12/multibody/tree/articulated_body_inertia.h#L18)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This change is unintentional?
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@rpoyner-tri for Tuesday's platform review please, thanks!

> Reviewed 2 of 40 files at r20.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476#-:-NJgS5oK6sgHZAjmY18L:b189ngu)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @rpoyner-tri)

___
*[`multibody/rational/rational_forward_kinematics.h` line 258 at r21](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgQmLn8K5odknvuz13:-NJgQmLn8K5odknvuz14:bkpxrf1) ([raw file](https://github.com/robotlocomotion/drake/blob/476e9935c709b5a8e37ff53ac29d451353420773/multibody/rational/rational_forward_kinematics.h#L258)):*
> ```objc
>    * Determines whether the current joint is revolute.
>    */
>   static bool IsRevolute(const internal::Mobilizer<double>& mobilizer);
> ```

Why putting `static` here? For every cc file that includes `rational_forward_kinematics.h`, it will create a copy of `IsRevolute` in its own compilation unit. Seems a waste of memory. See https://stackoverflow.com/questions/42056160/static-functions-declared-in-c-header-files#:~:text=examine%20the%20questions%3A-,What%20is%20the%20problem%20of%20declaring%20static%20functions%20in%20header%20files,actually%20uses%20it%2C%20the%20declaration%20does%20not%20belong%20in%20a%20header.,-One%20possible%20scenario

**Review by hongkai-dai — COMMENTED** [review]
> and I expect you will want me to test IsRevolute and related functions.

I think you can use `KinematicTreeTest` in `rational_forward_kinematics_test.cc`. This kinematic tree contains some revolute/weld/prismatic joint, you can then call `IsWeld`, `IsRevolute` and `IsPrismatic` function on these joints and compare with the expected answer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476#-:-NJgSPGtBmZX61_eOrPJ:b-f2ooz3)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @rpoyner-tri)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 37 of 40 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @rpoyner-tri)

**Review by hongkai-dai — COMMENTED** [review]
As we talked offline, `IsWeld`, `IsRevolute` and `IsPrismatic` are all private functions. We don't have to test them.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476#-:-NJgzVfp1iQholR_prZD:b-hdxvxg)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: the code itself looks fine; the comments and whitespace might benefit from a separate clean-up patch. Seems like this file has gotten a bit shaggy over time.

I'll have to squash the commits and rewrite the commit log message, unless you want to do it.
+(release notes: feature) 

> Reviewed 1 of 2 files at r4, 1 of 5 files at r19, 37 of 40 files at r20, 2 of 2 files at r21, 1 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476#-:-NJkT5xh8KDyL5WSmvPU:b-380s9v)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`multibody/rational/rational_forward_kinematics.h` line 222 at r22](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJkSonaEHpvHOHemSy4:-NJkSonaEHpvHOHemSy5:b6txf8a) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f663d08f41b89ea0b6129baefe9bcc978b8f00/multibody/rational/rational_forward_kinematics.h#L222)):*
> ```objc
>                                      const Pose<T>& X_AP) const;
> 
>   // Computes the pose of the link, connected to its parent link through a
> ```

nit Not the fault of this patch, but this file is fairly inconsistent on choice of comment style: `/**/` vs. `//`. See https://drake.mit.edu/styleguide/cppguide.html#Comment_Style
___
*[`multibody/rational/rational_forward_kinematics.h` line 230 at r22](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJkM4n8DEJRVGgRKwaV:-NJkM4n8DEJRVGgRKwaW:b-hrhq95) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f663d08f41b89ea0b6129baefe9bcc978b8f00/multibody/rational/rational_forward_kinematics.h#L230)):*
> ```objc
>       const math::RigidTransformd& X_PF, const math::RigidTransformd& X_MC,
>       const Pose<T>& X_AP, double d_star, const symbolic::Variable& d) const;
>   /* Given the pose of the parent frame X_AP measured in a frame A, calculates
> ```

nit Not the fault of this patch, but there is a blank line missing here. Feel free to punt.
___
*[`multibody/rational/rational_forward_kinematics.h` line 257 at r22](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJkMu_l2RmpbbtgjWyO:-NJkMu_l2RmpbbtgjWyP:bl5vpav) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f663d08f41b89ea0b6129baefe9bcc978b8f00/multibody/rational/rational_forward_kinematics.h#L257)):*
> ```objc
>   /*
>    * Determines whether the current joint is revolute.
>    */
> ```

nit Not strictly a defect, but I don't think these comments deserve to occupy 3 lines. Consider `/* blah */` formatting. Feel free to punt.
___
*[`multibody/rational/test/rational_forward_kinematics_test.cc` line 382 at r22](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJkS2zs8KFuIG5BGIn1:-NJkS2zs8KFuIG5BGIn2:b6ywcw5) ([raw file](https://github.com/robotlocomotion/drake/blob/e1f663d08f41b89ea0b6129baefe9bcc978b8f00/multibody/rational/test/rational_forward_kinematics_test.cc#L382)):*
> ```cpp
>             };
> 
>         // clang-format on
> ```

nit Is this one necessary? Looks like `clang-format` is already on.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @rpoyner-tri)

___
*[`multibody/rational/rational_forward_kinematics.h` line 258 at r21](https://reviewable.io/reviews/robotlocomotion/drake/18476#-NJgQmLn8K5odknvuz13:-NJguYjC8zhMRg_p13au:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/476e9935c709b5a8e37ff53ac29d451353420773/multibody/rational/rational_forward_kinematics.h#L258)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why putting `static` here? For every cc file that includes `rational_forward_kinematics.h`, it will create a copy of `IsRevolute` in its own compilation unit. Seems a waste of memory. See https://stackoverflow.com/questions/42056160/static-functions-declared-in-c-header-files#:~:text=examine%20the%20questions%3A-,What%20is%20the%20problem%20of%20declaring%20static%20functions%20in%20header%20files,actually%20uses%20it%2C%20the%20declaration%20does%20not%20belong%20in%20a%20header.,-One%20possible%20scenario
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18476)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai (waiting on @AlexandreAmice)

**Pull request merged**
