### PR TITLE
Ask before downgrading Bazel

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7615.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7617)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri I haven't tried it, but it all makes sense. :LGTM:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0PcUqSjN-M6QvaOo1C:-L0PcUqT1nNnNmbCsd5b:b-ud021h) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L128)):*
> ```Shell
> 
>   # Skip the install if we're already at the exact version.
>   installed=$(dpkg-query --showformat='${Version}\n' --show "${package}" 2>/dev/null || true)
> ```

FYI `|| true`? I'm assuming this covers the case where `${package}` isn't installed at all and `dpkg-query` wants to have a non-passing exit code. I'm shell scripting ignorant, is this a common idiom or would it be worth noting for novices like me?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-:-L0Pda9n1WBz-9BzMIZE:b-ffuy3k)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0PcUqSjN-M6QvaOo1C:-L0Pfak-jXgHhK2RxluS:bghyexq) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L128)):*
> I'm assuming this covers the case where ${package} isn't installed at all and dpkg-query wants to have a non-passing exit code.

Yup, you've got it.

> I'm shell scripting ignorant, is this a common idiom or would it be worth noting for novices like me?

I believe it is relatively widely known.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature and platform review on Monday, please.

At least one of @EricCousineau-TRI or @SeanCurtis-TRI should test this out locally, too.  (There is a trick `git fetch upstream pull/7617/head && git checkout FETCH_HEAD`, if folks are unaware?)

**Comment by SeanCurtis-TRI** [comment]
I've run the changes and it definitely detected a bazel change, reported it correctly and responded "correctly" based on my response.

However, because bazel is last, hitting "n" in the "downgrade bazel" prompt makes it look like the script summarily ends. I'd recommend that the script provide a couple of extra messages:

1. In the event the user chooses *not* to downgrade, an acknowledgement of that choice and a "proceeding with other prerequisites" style of message appears,
2. at the conclusion of the script a "all prerequisites successfully installed" kind of message. So, you don't have to wonder about how to interpret the end of the script.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 128 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0PcUqSjN-M6QvaOo1C:-L0PuGhlMzpSONU-QbnM:b-zcjvte) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L128)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I'm assuming this covers the case where ${package} isn't installed at all and dpkg-query wants to have a non-passing exit code.

Yup, you've got it.

> I'm shell scripting ignorant, is this a common idiom or would it be worth noting for novices like me?

I believe it is relatively widely known.
</blockquote></details>

Thanks

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0Pslk-vk7mbP08LGIs:-L0Pslk-vk7mbP08LGIt:b-wejyms) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L158)):*
> ```Shell
>     echo  # Blank line between checkout output and dpkg output.
>   else
>     die "The Bazel deb does not have the expected SHA256.  Not installing Bazel."
> ```

BTW The function has been generalized, but this line still says "Bazel".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-:-L0Pt71M8z8tWs9ooxLn:b-el5k4v)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0QJCTxL041D6TTwPgB:-L0QJCTxL041D6TTwPgC:bicbpoy) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L139)):*
> ```Shell
>       echo "This system has ${package} version ${installed} installed."
>       echo "Drake suggests downgrading to version ${version}, our supported version."
>       read -p "Do you want to downgrade? [Y/n] " yn
> ```

BTW The capital Y would usually imply that Y were the default if you just hit enter, but here it is not.

I prefer the version in the Mac script: https://github.com/RobotLocomotion/drake/blob/ceec5693323847ca643b22b418242e5c735f61d2/setup/mac/install_prereqs.sh#L79-L82, but then I am biased...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by jwnimmer-tri** [comment]
*[setup/ubuntu/16.04/install_prereqs.sh, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0QJCTxL041D6TTwPgB:-L0QKSvqHsrAHqr19Of-:bqorpim) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L139)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW The capital Y would usually imply that Y were the default if you just hit enter, but here it is not.

I prefer the version in the Mac script: https://github.com/RobotLocomotion/drake/blob/ceec5693323847ca643b22b418242e5c735f61d2/setup/mac/install_prereqs.sh#L79-L82, but then I am biased...
</blockquote></details>

OK Actually `Y` is the default, but I will look at abbreviating the case to be like macOS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by jwnimmer-tri** [comment]
I've added more status output per the above.  PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0Pslk-vk7mbP08LGIs:-L0QRwtArn1dlXaFciOV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3bbb28363599b282a054c3b5ae7e5b6fdc388e06/setup/ubuntu/16.04/install_prereqs.sh#L158)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The function has been generalized, but this line still says "Bazel".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-:-L0QSTKEJ1O5QhuNmoNV:bgmbotq)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0QVcHPetcV7X1uTYhD:-L0QVcHPetcV7X1uTYhE:bwz8aka) ([raw file](https://github.com/robotlocomotion/drake/blob/fc12dedcbf7c006422aca786c685260fb23c98ca/setup/ubuntu/16.04/install_prereqs.sh#L139)):*
> ```Shell
>     echo "Drake suggests downgrading to version ${version}, our supported version."
>     read -r -p "Do you want to downgrade? [Y/n] " reply
>     if [[ ! "${reply}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
> ```

BTW As I read this, the reg ex doesn't seem to match the empty string. So, is "yes" really the default? (Although, I do love the fact that an emphatic "yesyesyesyes" would be accepted. :D) Sorry for prolonging the issue -- I was too lazy to update and try it again locally.

It's worth noting that the example this reg-ex is drawn from has the `N` as default, so it must only enumerate acceptable answers to avoid the default. You've got the reverse problem solved by, I think, changing the `+` to a `*`. (Or, reversing it to:

`if [[ "${reply}" =~ ^([nN][oO]+)+$ ]]; then`

(which, of course, would accept things like: Noooooooooooooo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 139 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0QVcHPetcV7X1uTYhD:-L0QYBF64K5Xd-2NEIEA:b92p3gv) ([raw file](https://github.com/robotlocomotion/drake/blob/fc12dedcbf7c006422aca786c685260fb23c98ca/setup/ubuntu/16.04/install_prereqs.sh#L139)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As I read this, the reg ex doesn't seem to match the empty string. So, is "yes" really the default? (Although, I do love the fact that an emphatic "yesyesyesyes" would be accepted. :D) Sorry for prolonging the issue -- I was too lazy to update and try it again locally.

It's worth noting that the example this reg-ex is drawn from has the `N` as default, so it must only enumerate acceptable answers to avoid the default. You've got the reverse problem solved by, I think, changing the `+` to a `*`. (Or, reversing it to:

`if [[ "${reply}" =~ ^([nN][oO]+)+$ ]]; then`

(which, of course, would accept things like: Noooooooooooooo
</blockquote></details>

Absolutely correct, good eyes.  (And as much as I like Noooooo, I'll stick with YesYesYes though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, tested on my system (bumped the script to 0.7.0, had it install over 0.6.1, then reverted that change).

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/16.04/install_prereqs.sh, line 140 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-L0R9fZ6QuyCeGZDYX9k:-L0R9fZ6QuyCeGZDYX9l:b-dv7e78) ([raw file](https://github.com/robotlocomotion/drake/blob/ede11cd54412b15c327f1f96d975aa24218cf4fd/setup/ubuntu/16.04/install_prereqs.sh#L140)):*
> ```Shell
>     read -r -p "Do you want to downgrade? [Y/n] " reply
>     if [[ ! "${reply}" =~ ^([yY][eE][sS]|[yY])*$ ]]; then
>       echo "OK, skipping ${package} ${version} installation."
> ```

BTW grammar nit Is it common for scripts to put an `OK`? The positive response made me briefly think that it had made a change (versus just saying "Skipping ...").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7617#-:-L0QvgunE3rKjsQk7HKs:b1q90hx)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please

**Comment by ahundt** [comment]
How would you guys feel about using the google provided apt repository for bazel by default?

They don't make a full API stability guarantee until 1.0 is out, but they do say they will "try very hard" to keep it stable between now (0.8.1) and 1.0. If that limitation means you can't do it now, perhaps once 1.0 is released?
https://bazel.build/support.html

Here's a script to install:
```
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y bazel
sudo apt-get upgrade bazel
```
This is my version of the bazel install script for linux and MacOS:
https://github.com/ahundt/robotics_setup/blob/master/bazel.sh


This is a repost of https://github.com/RobotLocomotion/drake/issues/7615#issuecomment-352124973 but it seems more relevant here.

**Comment by jwnimmer-tri** [comment]
Oops, I saw that post first and replied there.  I'll repost here:
> We can see about once 1.x is released. For now, we value (mostly) repeatable builds. For a given drake commit, we know that it passed CI with a locked-down Bazel version as reflected on the source tree. Using a PPA means that the version would be floating, so we could not easily build older Drake commits successfully anymore. In any case, we will be updating to 0.8.1 soon, but need to test our developers' IDE integration before upgrading, which is a manual process.

**Comment by jwnimmer-tri** [comment]
`unprovisioned` passed; merging now.

**Comment by jwnimmer-tri** [comment]
Another note -- in general we have a goal of making `install_prereqs.sh` more maintainable and useful for wider purposes.  For example, possibly the list of `apt` packages we install should be in a separate text file, so that other out-of-tree scripts could more easily refer to that list as data, rather than having to run the (semi-interactive) monolithic shell script as it stands now.

**Pull request merged**
