### PR TITLE
Port primitives to default_scalars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7102)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.
+@sammy-tri for platform review per rotation (tomorrow), please.

**Comment by jwnimmer-tri** [comment]
*[drake/common/default_scalars.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuui2UL_2SXfI9gHBzF:-Kuui2UMP--QpHMXdlLt:b-nec4si) ([raw file](https://github.com/robotlocomotion/drake/blob/da62007fafcc3dea2263ec34191f3a64c440f908/drake/common/default_scalars.h#L38)):*
> ```objc
> /// See also @ref system_scalar_conversion.
> #define DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_SCALARS(SomeType) \
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS( \
> ```

(Meta) Typo INSTIATIONS; will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 7 of 23 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/saturation.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuygl4F-YMXHN7mNM1Z:-Kuygl4GUQWsowWnk0dx:bbr0a96) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/saturation.h#L23)):*
> ```objc
> /// - double
> /// - AutoDiffXd
> /// - symbolic::Expression
> ```

BTW if we ever add another default scalar type, is someone going to have to go through and update every one of these?  (we probably won't)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-:-Kuyh1ILy4bC015C2awO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/primitives/saturation.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuygl4F-YMXHN7mNM1Z:-KuyhEDqwgYhleL_gW-K:b-drtv84) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/saturation.h#L23)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW if we ever add another default scalar type, is someone going to have to go through and update every one of these?  (we probably won't)
</blockquote></details>

Well, the overall epic of this PR train _is_ to add another scalartype, like AutoDiff8d.  And yes, in that case text will need de-boilerplating.  That's tracked in #6890 and will need a solution soon.  For now, I'm still manually maintaining the bullet lists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/primitives/saturation.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuygl4F-YMXHN7mNM1Z:-Kuyi-p4Ru4S42Bd6_-Y:b-g5olj4) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/saturation.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Well, the overall epic of this PR train _is_ to add another scalartype, like AutoDiff8d.  And yes, in that case text will need de-boilerplating.  That's tracked in #6890 and will need a solution soon.  For now, I'm still manually maintaining the bullet lists.
</blockquote></details>

I've been following the fixed size autodiff thread and still somehow forgot that...   Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102)*

**Comment by amcastro-tri** [comment]
Reviewed 7 of 23 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/constant_value_source.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuyk-3VZCKIKIXO2mrQ:-Kuyk-3VZCKIKIXO2mrR:b-rv5qc9) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/constant_value_source.cc#L7)):*
> ```cpp
> namespace systems {
> 
> template class ConstantValueSource<double>;
> ```

wouldn't we like to support transmogrification for this system? or for some reason doesn't work now.
I can imagine a Diagram that we do want to convert to AutoDiffXd but one of its leaf systems is one of these `ConstantValueSource`.

---

*[drake/systems/primitives/multiplexer.h, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuykYPECIdK63vmSpEL:-KuykYPECIdK63vmSpEM:brll3ro) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/multiplexer.h#L20)):*
> ```objc
> /// - double
> /// - AutoDiffXd
> /// - symbolic::Expression
> ```

BTW, good job on keeping the doc in sync!

---

*[drake/systems/primitives/signal_log.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuyksINbLBaFr0h_ZMD:-KuyksINbLBaFr0h_ZME:b5twxzr) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/signal_log.cc#L44)):*
> ```cpp
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
>     class ::drake::systems::SignalLog)
> ```

would we need to update the doc in the header for supported scalar types?

---

*[drake/systems/primitives/trajectory_source.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuylZVMVuQ4f4ORBCF8:-KuylZVMVuQ4f4ORBCF9:bymyz7e) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/trajectory_source.cc#L50)):*
> ```cpp
> }
> 
> template class TrajectorySource<double>;
> ```

why not support to `T`? I think it should work even if `Trajectory` only works on doubles (constants)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/primitives/constant_value_source.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuyk-3VZCKIKIXO2mrQ:-Kuz-7HvKIv7fYXtLLzL:b-n7ohou) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/constant_value_source.cc#L7)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

wouldn't we like to support transmogrification for this system? or for some reason doesn't work now.
I can imagine a Diagram that we do want to convert to AutoDiffXd but one of its leaf systems is one of these `ConstantValueSource`.
</blockquote></details>

This PR is a mechanical respelling, and should mostly not try to add new features.  (Here, I was fixing an obvious copy-paste-o.)  See #5872 for semi-related discussions.

---

*[drake/systems/primitives/signal_log.cc, line 44 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuyksINbLBaFr0h_ZMD:-Kuz-iS7jKjC2mrYuthm:b-ioh3dq) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/signal_log.cc#L44)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

would we need to update the doc in the header for supported scalar types?
</blockquote></details>

Nope; the header does not document a list of supported types.

---

*[drake/systems/primitives/trajectory_source.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuylZVMVuQ4f4ORBCF8:-Kuz-XlP9_xzx0dbi5Mg:bs2d942) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/trajectory_source.cc#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why not support to `T`? I think it should work even if `Trajectory` only works on doubles (constants)
</blockquote></details>

This PR is a mechanical respelling, and should mostly not try to add new features.  (Here, I was fixing an obvious copy-paste-o.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102)*

**Comment by amcastro-tri** [comment]
I forgot to publish, sorry. :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/primitives/constant_value_source.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-Kuyk-3VZCKIKIXO2mrQ:-Kuz40rPUhQorlBroA-c:b-9h73b2) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/constant_value_source.cc#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR is a mechanical respelling, and should mostly not try to add new features.  (Here, I was fixing an obvious copy-paste-o.)  See #5872 for semi-related discussions.
</blockquote></details>

I agree, I just wanted to double-check with you. Maybe add TODO referencing that issue?

---

*[drake/systems/primitives/trajectory_source.cc, line 50 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-KuylZVMVuQ4f4ORBCF8:-Kuz4ZxOSsaBnDNGMpqV:b8owbke) ([raw file](https://github.com/robotlocomotion/drake/blob/01789b040c49fb0517adb3c02cab6664527b4437/drake/systems/primitives/trajectory_source.cc#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR is a mechanical respelling, and should mostly not try to add new features.  (Here, I was fixing an obvious copy-paste-o.)
</blockquote></details>

sound good. Add TODO with issue number above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7102#-:-Kuz_qupEYlqA3Pak3hu:b-cumw04)*

**Pull request merged**
