### PR TITLE
Added style guide clarification regarding placement of `*` and `&` symbols.

### PR DESCRIPTION
**Pull request by liangfok**
I also removed some unnecessary trailing spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3849)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@sammy-tri for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3849#-:-KUXPrh3fKC2iSn37coR:b-i1f1kk)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3849#-KUXRcKYu1wPH7Yt9dDm:-KUXRcKZlVrYXOH1rmK2:b-p1osyq) ([raw file](https://github.com/robotlocomotion/drake/blob/e48275388ce118f9f33d440ceeedee6c10f625bf/drake/doc/code_style_guide.rst#L150)):*
> ```reStructuredText
>   what is enforced by :ref:`clang-format <code-style-tools-clang-format>`. For
>   additional context, see
>   `this comment thread <https://reviewable.io/reviews/robotlocomotion/drake/3830#-KUSH9E-rBwyUCb560uX>`_.
> ```

I'm not sure that this link is required, or that it's guaranteed to be permanently available/useful (not that sure about Reviewable).  I think adding the explanatory note from there that we know this is contrary to the style guide might be sufficient (alternately is it possible to link directly to github in a way that makes the discussion look reasonable?  I'm assuming no)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3849)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 150 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3849#-KUXRcKYu1wPH7Yt9dDm:-KUXTnfRzVBpMd0i8ZsB:beiy450) ([raw file](https://github.com/robotlocomotion/drake/blob/e48275388ce118f9f33d440ceeedee6c10f625bf/drake/doc/code_style_guide.rst#L150)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I'm not sure that this link is required, or that it's guaranteed to be permanently available/useful (not that sure about Reviewable).  I think adding the explanatory note from there that we know this is contrary to the style guide might be sufficient (alternately is it possible to link directly to github in a way that makes the discussion look reasonable?  I'm assuming no)
</details>
I updated this paragraph to link to both the actual style guide rule that's being clarified and the original github thread. PTAL. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3849)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3849#-:-KUXaGrkofHA5WkwjjKb:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3849#-:-KUXhQW4ldDek8BlBdTY:bnfp4nl)*

**Pull request merged**
