### PR TITLE
fixes for https://github.com/RobotLocomotion/drake/issues/5742

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
fix for https://github.com/RobotLocomotion/drake/issues/5742

limits the pub rates in sim, also disable set publish every step in sim.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5747)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for platform review. +@naveenoid for feature. thanks.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-:-Kh2sQ1Bs9d8Mg9xYCej:b-jyoh8n)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-Kh2wS8okIp9jl29E5Ou:-Kh2wS8okIp9jl29E5Ov:bepkii) ([raw file](https://github.com/robotlocomotion/drake/blob/75416e0717d0c402805325e47dfd2efd7fa60934/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L210)):*
> ```cpp
>   builder.Connect(model->get_output_port_iiwa_robot_state_msg(),
>                   iiwa_state_pub->get_input_port(0));
>   iiwa_state_pub->set_publish_period(kIiwaLcmStatusPeriod);
> ```

We should probably also fix this in kuka_simulation.cc and schunk_wsg_simulation.cc (why did I originally create 3 of these and why haven't I deleted any?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-Kh2wS8okIp9jl29E5Ou:-Kh32x6u3E2_Ei22bePx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75416e0717d0c402805325e47dfd2efd7fa60934/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L210)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

We should probably also fix this in kuka_simulation.cc and schunk_wsg_simulation.cc (why did I originally create 3 of these and why haven't I deleted any?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-:-Kh3FT9jp_KDQpfd5U-T:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-:-Kh3aS4WbztMcgk0GI5x:bnfp4nl)*

**Comment by naveenoid** [comment]
BTW, the source issue which this PR fixes is exactly why I think we need more "demo" unit tests where terminal state of simulated systems should be used to verify component behaviors. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5747#-:-Kh3aYtLlt5eZVS2hKY4:b57rrin)*

**Pull request merged**
