### PR TITLE
Move foo/test/BUILD content into foo/BUILD

### LINKED ISSUE #4457: Update BUILD files for test-declaration consistency
Before using Bazel with a wider audience, we should be internally consistent.  One big divergence is declaring tests, e.g., in foo/BUILD vs foo/test/BUILD.  We've agreed to use foo/BUILD, so fix the tree to be consistent.

This is part of #3129.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is intended to be shuffle-only changes, without any novel code:
* Paste the foo/test/BUILD content at the end of foo/BUILD.
* Replace DEPS shared variable with copy-pasting into uses.
* Add test/ prefix to paths as needed.
* Use local ":libname" paths instead of "//full/paths" where possible.
* Buildifier reformatting.

Closes #4457.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4459)

### CODE REVIEW

**Comment by liangfok** [comment]
What is the motivation behind moving the contents of `foo/test/BUILD` into `foo/BUILD`? Isn't it better to keep a BUILD files closer to the files it is building? Also, per #4455, is it odd for a single `BUILD` file to cover code that spans a wide difference in terms its place in the overall dependency chain (tests are always last whereas `foo` may be far from last)?

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYlAu_B5De7MIjAH4Jc:b-jocrpi)*

**Comment by jwnimmer-tri** [comment]
The motivation is that Bazel is slightly more convenient to work with when the library rules and test rules are in the same BUILD file.

The #4455 topology is about what `deps = []` says, not about where `BUILD` files are located.

**Comment by liangfok** [comment]
Cool. Thanks!

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please

**Comment by rpoyner-tri** [comment]
+@rpoyner-tri 

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYny8j2WtOPJnmduLNE:bbpa3zd)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYo0c4a3y2CNrKvIlB_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri do you want to weigh in on this (at a high level, at least)?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYo2EFGeOEOq1Yo4JPG:b-eoo2l6)*

**Comment by david-german-tri** [comment]
Only to gripe that #2182 was a suboptimal decision, and this illustrates why: we now have a mismatch between our test target paths in Bazel and the paths to the source code on the filesystem.  It's not worth revisiting, though.

I've confirmed locally that the list of tests is unchanged.  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYoHzEdOYyMYAQSJh_s:b-83jt2x)*

**Comment by david-german-tri** [comment]
I'm going to go ahead and merge this so that I can proceed with #4462.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4459#-:-KYoK8M628mXNZDADViY:bgmhcgo)*

**Pull request merged**
