### PR TITLE
Add Makefile explanatory comment

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3864)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@edrumwri for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3864#-:-KUbRLMk3REsRKFKRjEy:buzjszf)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/Makefile, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3864#-KUbRVcNwpAyzKvs30nI:-KUbRVcNwpAyzKvs30nJ:bsbnlyw) ([raw file](https://github.com/robotlocomotion/drake/blob/6012ea27b2f759c95572ba06caa831b4f099cfbf/drake/Makefile#L3)):*
> ```Makefile
> # This file is drake-distro/drake/Makefile.  It is here for projects still
> # using PODS to be able to build Drake.  Users and developers who use Drake by
> # itself own should ignore (and never run) this file.  For build instructions,
> ```

BTW, do you "run" a Makefile or "use" a Makefile with `make`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3864#-:-KUbRa8jvLjm-8AtytYw:bnfp4nl)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3864#-:-KUbSXc_b0ZhhbUNW_Wd:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3864#-:-KUb_CaoN0JLNIc6_P1q:bnfp4nl)*

**Pull request merged**
