### PR TITLE
[pydrake/trajectories] Make BsplineTrajectory picklable

### PR DESCRIPTION
**Pull request by mpetersen94**
Also makes BsplineBasis picklable.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@ericcousineau-tri for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-Mx6RGR0Asn-xMrZJMK-:by4pfea)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI for durability of the pickled data, and easier maintenance of the bindings, I wonder if we should take a different tack for pickling.

Could we have the setstate implementation always expect a dictionary, which it then passes to the class's constructor (to allow kwargs bindings to be in effect), and so getstate would always just return a dictionary of valid kwargs for the class's constructor.  It also seems easy to have this generate a `repr()` at the same time.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, nice!
+@sammy-tri for platform review, please!

Fair points! I think something along those lines would help; however,
(a) not all bindings may expose those their state in this symmetric save/load form,
(b) not all bindings may expose all of their state,
(c) not all bindings may expose all of their state in a way that is exposed via `self.__dict__` (e.g. they may be function accessors or property accessors),
(d) along these points, it may be better to leverage something like generic archive serialization / deserialization (beyond what's afforded for YAML) for a more generic approach.

I assume this could be discussed / done outside the scope of this immediate PR? Our pickles are rather unstable, so after-the-fact improvements would be only an improvement!

(barring the invalidation of prior pickles)

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxA5cZxDnz0dVv6e1Rh:b-w4n82u)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> (barring the invalidation of prior pickles)

To this effect, I've been wanting to know if pickles had nice "external" affordances for pickle migration; e.g. for visuomotor stuff at TRI, we can manually transform pickles for `RigidTransform` if schema transforms.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxA7-BF37RYh2v6MbIu:b-u3xnjl)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
> I assume this could be discussed / done outside the scope of this immediate PR? Our pickles are rather unstable, so after-the-fact improvements would be only an improvement!

Yes, nothing blocking here.  I wasn't sure how stable we wanted to aim for in pickling, so in case those thoughts advocated for a different pickle format here (done manually), that would have been the only immediate change.  If we're happy to break the current pickle formats if we ever add helper functions that automate it, that's completely fine to defer.

**Comment by EricCousineau-TRI** [comment]
Sounds good! I believe Marks' PR is consistent w/ existing approaches, so I think that's more ideal than a partial setup.

And I guess we don't have to strictly break if we decide to introduce versioning of sorts to the pickle schema (but ew on overhead).

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxApHSW9Q1nV3BQCaF_:bnfp4nl)* status: missing label for release notes (waiting on @mpetersen94)

**Review by sammy-tri — COMMENTED** [review]
oh, oops, #16684 caused a merge conflict here.  :lgtm_cancel:   Will give another check once that's fixed, but no other issues from me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxApjLN1R5hnfr3NgMu:b-c17b0m)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
Merge conflict fixed!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxAq_Az6VbS3k2QfZ98:buz1z66)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxAzheP45uw2yq9b39n:bnfp4nl)* status: missing label for release notes (waiting on @mpetersen94)

**Review by sammy-tri — COMMENTED** [review]
+(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16698#-:-MxAzkqvBe8yHMeACfLx:b-c7f1bi)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),EricCousineau-TRI(platform) (waiting on @mpetersen94)

**Pull request merged**
