### PR TITLE
Refactor wsg sim

### PR DESCRIPTION
**Pull request by naveenoid**
PR moves the diagram building component of the Kuka IIWA - WSG sim example into a factory builder. This solves a part of Spiral 2 of #5371

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5410)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@siyuanfeng-tri for feature review.

**Comment by siyuanfeng-tri** [comment]
:lgtm: 
fyi, i am working on some longer term solution. https://github.com/siyuanfeng-tri/drake/blob/dev/iiwa_sim_factory/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h
i am trying to make it some kind of extended diagram builder that knows about plant and a bunch of controller, and how to wire them. 

---

Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KePeP0u9NoVMyJ1B2Rr:-KePeP0u9NoVMyJ1B2Rs:b-fkn5d) ([raw file](https://github.com/robotlocomotion/drake/blob/9964031b1053b0c24984645bff33966cd2d74eda/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L106)):*
> ```cpp
> 
>     // Export iiwa's desired state input, and state output.
>     builder.ExportInput(iiwa_controller->get_input_port_desired_state());
> ```

BTW, FYI the export input stuff now has int return type now. this is fine though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KePefogyDLW_tj2MwoC:bnomxn7)*

**Comment by naveenoid** [comment]
nice. Let me know if we can discuss this new builder. For now I will push this version and follow it up with minimal automation of port IDs before hookup in the upcoming mega-diagram.

---

Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KeUbiK6m1lj2mXDyTtG:b2g1i3l)*

**Comment by naveenoid** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KePeP0u9NoVMyJ1B2Rr:-KeUbzWFcgIFNFE6buU_:bi5gpzj) ([raw file](https://github.com/robotlocomotion/drake/blob/9964031b1053b0c24984645bff33966cd2d74eda/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L106)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, FYI the export input stuff now has int return type now. this is fine though. 
</blockquote></details>

Will leave this for now..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410)*

**Comment by naveenoid** [comment]
I am currently trying to fix the build errors. In any case, 

+@sherm1 for platform review

---

Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KeVYBAXEjFd4cCIJonv:b9o5vg5)*

**Comment by sherm1** [comment]
+@soonho-tri for co-platform review

---

Review status: 1 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KeZWChNVvtZCRNf2IVy:by5rznl)*

**Comment by soonho-tri** [comment]
First pass done. @sherm1 , please take a look at this PR and meta-review mine. Thank you.

---

Reviewed 1 of 7 files at r1, 2 of 2 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 80 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaNK64Y_fkY9CwiKDn:-KeaNK64Y_fkY9CwiKDo:bf07l5e) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/BUILD#L80)):*
> ```Python
>         ":iiwa_common",
>         ":iiwa_lcm",
>         ":oracular_state_estimator",
> ```

Please consider using the following line after this line (see another `BUILD` file):
```python
        "//drake/examples/kuka_iiwa_arm/iiwa_world:iiwa_wsg_diagram_factory",
```

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaA6t42KwKy-f-9Y_W:-KeaA6t6YxBerf5NGWLB:b4cjk1j) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L114)):*
> ```objc
> };
> 
> // template class OracularStateEstimation<double>;
> ```

BTW, this change seems unnecessary can be removed from this PR?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaMm-TiYIc_ziQ8MQB:-KeaMm-UJLhLImMh7bBh:b8ma0ou) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L23)):*
> ```Python
>     ],
> )
> ```

Please consider using the following here. This version has two `drake_cc_library` which help Bazel parallelize a build.

```python
drake_cc_library(
    name = "world_sim_diagram_factory",
    srcs = [
        "world_sim_diagram_factory.cc",
    ],
    hdrs = [
        "world_sim_diagram_factory.h",
    ],
    visibility = ["//drake/examples/kuka_iiwa_arm:__subpackages__"],
    deps = [
        "//drake/common:drake_path",
        "//drake/common/trajectories:piecewise_polynomial_trajectory",
        "//drake/examples/kuka_iiwa_arm:iiwa_common",
        "//drake/lcm",
        "//drake/multibody:rigid_body_tree",
        "//drake/multibody/parsers",
        "//drake/multibody/rigid_body_plant",
        "//drake/multibody/rigid_body_plant:drake_visualizer",
        "//drake/systems/analysis:simulator",
        "//drake/systems/controllers:inverse_dynamics_controller",
        "//drake/systems/framework",
        "//drake/systems/primitives:constant_vector_source",
        "//drake/systems/primitives:demultiplexer",
        "//drake/systems/primitives:multiplexer",
        "//drake/systems/primitives:trajectory_source",
    ],
)

drake_cc_library(
    name = "iiwa_wsg_diagram_factory",
    srcs = [
        "iiwa_wsg_diagram_factory.cc",
    ],
    hdrs = [
        "iiwa_wsg_diagram_factory.h",
    ],
    visibility = ["//drake/examples/kuka_iiwa_arm:__subpackages__"],
    deps = [
        ":world_sim_tree_builder",
        "//drake/examples/kuka_iiwa_arm:iiwa_common",
        "//drake/examples/kuka_iiwa_arm:oracular_state_estimator",
        "//drake/multibody/rigid_body_plant",
        "//drake/systems/controllers:inverse_dynamics_controller",
        "//drake/systems/controllers:pid_controller",
        "//drake/systems/framework:diagram",
        "//drake/systems/framework:diagram_builder",
        "//drake/systems/primitives:constant_vector_source",
        "//drake/systems/primitives:matrix_gain",
    ],
)
```

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaARL8ujjDH_g95C7R:-KeaARL8ujjDH_g95C7S:bdv6l0a) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L36)):*
> ```Python
>     visibility = ["//drake/examples/kuka_iiwa_arm:__subpackages__"],
>     deps = [
>         "world_sim_tree_builder",
> ```

FYI, it should be`":world_sim_tree_builder" (with leading `:`).

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaO5sgb_Ce7YTKzzYN:-KeaO5sgb_Ce7YTKzzYO:b82b0h7) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L57)):*
> ```cpp
>   iiwa_ki << 1, 1, 1, 1, 1, 1, 1;
> 
>   // Exposing feedforward acceleration. Should help with more dynamic
> ```

nit: these two lines can fit in a line.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 73 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaOiVnOop4HxadjUi1:-KeaOiVnOop4HxadjUi2:b-dsaetj) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L73)):*
> ```cpp
> 
>   const RigidBody<T>* end_effector = world_tree.FindBody("iiwa_link_7");
>   Isometry3<T> X_WEE =
> ```

FYI, consider marking the following definitions as `const`:
```c++
Isometry3<T> X_WEE
std::set<int> gripper_instance_set
Matrix6<T> lumped_gripper_inertia_W
```

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 179 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaQjdroNmaAXuqK1ad:-KeaQjdroNmaAXuqK1ae:bvo9v19) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L179)):*
> ```cpp
> }
> template class IiwaAndWsgPlantWithStateEstimator<double>;
> template class OracularStateEstimation<double>;
> ```

Please consider creating `drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc` and have `template class OracularStateEstimation<double>;` there instead of having it here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaBUaYWdclgIQjgzBD:-KeaBUaYWdclgIQjgzBE:bq8ulmc) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L16)):*
> ```objc
> namespace kuka_iiwa_arm {
> 
> /// A custom `systems::Diagram` composed of a `systems::RigidBodyPlant`, and a
> ```

Please reflow this paragraph.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaBRnUD34tWtfZyM4e:-KeaBRnUD34tWtfZyM4f:b-o47gg8) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L21)):*
> ```objc
> /// generated
> /// from a `RigidBodyTree` containing a Kuka IIWA and a Schunk WSG model and
> /// atleast one
> ```

FYI, typo of `at least`.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaRFHtTc82_1IKyCA6:-KeaRFHtTc82_1IKyCA7:b-mcalsh) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L31)):*
> ```objc
> /// and output ports for IIWA state, WSG state, the complete
> /// `systems::RigidBodyPlant`
> /// state messages for the IIWA robot and an object for manipulation.
> ```

Please consider having the following comment here:
```
/// This class is explicitly instantiated for the following scalar type(s). No
/// other scalar types are supported.
/// - double
```

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaC-izzHHjiulxZLeC:-KeaC-izzHHjiulxZLeD:b-1f1xig) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L35)):*
> ```objc
> class IiwaAndWsgPlantWithStateEstimator : public systems::Diagram<T> {
>  public:
>   ///
> ```

FYI, here is an unfinished Doxygen comment.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaCaEkcl_xTbHd5Ln6:-KeaCaEkcl_xTbHd5Ln7:b-rlbm4k) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L52)):*
> ```objc
>   }
> 
>   const systems::OutputPortDescriptor<T>& get_iiwa_state_port() const {
> ```

BTW, it looks more organized if we swap `get_iiwa_state_port` and `get_wsg_input_port`.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaArTCf0bvMwW6jC9I:-KeaArTCf0bvMwW6jC9J:bza7a02) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L90)):*
> ```objc
> };
> ```

BTW, these whitespace changes can be removed from this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KeaRXPCGcTB4nbEKlJ1:b-dyyoiv)*

**Comment by naveenoid** [comment]
Fixing remaining CI issues shortly but rest of the defects addressed. PTAL.

---

Review status: 2 of 8 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/BUILD, line 80 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaNK64Y_fkY9CwiKDn:-KecMbfF3hzQGRHEngAH:b-ck45pe) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/BUILD#L80)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please consider using the following line after this line (see another `BUILD` file):
```python
        "//drake/examples/kuka_iiwa_arm/iiwa_world:iiwa_wsg_diagram_factory",
```
</blockquote></details>

Done..In light of the new library you requested for iiwa_wsg_diagram_factory

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 114 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaA6t42KwKy-f-9Y_W:-KecMhcd_vfL9hp5abOj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L114)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, this change seems unnecessary can be removed from this PR?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 36 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaARL8ujjDH_g95C7R:-KecPG7riiUol59fVoY-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L36)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, it should be`":world_sim_tree_builder" (with leading `:`).
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaO5sgb_Ce7YTKzzYN:-KecPO8VkYXGhYI5CQ5t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L57)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit: these two lines can fit in a line.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 179 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaQjdroNmaAXuqK1ad:-KecPPpStYONObAt6LYy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L179)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please consider creating `drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc` and have `template class OracularStateEstimation<double>;` there instead of having it here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaBUaYWdclgIQjgzBD:-KecPpFXcxA97YTqeQYQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L16)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please reflow this paragraph.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaBRnUD34tWtfZyM4e:-KecQ1vKLLfAjCpsJxZC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L21)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, typo of `at least`.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 31 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaRFHtTc82_1IKyCA6:-KecRC6_Fzt81pPdZXO5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L31)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please consider having the following comment here:
```
/// This class is explicitly instantiated for the following scalar type(s). No
/// other scalar types are supported.
/// - double
```
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaC-izzHHjiulxZLeC:-KecRCRYY4lftVOOvM2r:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, here is an unfinished Doxygen comment.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaCaEkcl_xTbHd5Ln6:-KecRbnH9DEG_wveq9QG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, it looks more organized if we swap `get_iiwa_state_port` and `get_wsg_input_port`.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h, line 90 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaArTCf0bvMwW6jC9I:-KecRvGI3mG4neBlu9FN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/world_sim_diagram_factory.h#L90)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, these whitespace changes can be removed from this PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KeczwbEYyP5kO70-1-g:bj25a0u)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-Ked-T0TQ9pSVVHAly6a:-Ked-T0UZxq9zHAutV82:bumbk4m) ([raw file](https://github.com/robotlocomotion/drake/blob/7c73659ad87e6c92872d875d89a81c36ce8645b0/drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc#L11)):*
> ```cpp
> }  // namespace kuka_iiwa_arm
> }  // namespace examples
> }  // namespace drake
> ```

BTW, new line is missing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-Ked2b-8R1BKB783ziVR:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-Ked-T0TQ9pSVVHAly6a:-Ked4sQCd5EQHMH8hrHi:b-wwo491) ([raw file](https://github.com/robotlocomotion/drake/blob/7c73659ad87e6c92872d875d89a81c36ce8645b0/drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc#L11)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, new line is missing here.
</blockquote></details>

FYI, this causes cpplint problem (+CI issue).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410)*

**Comment by naveenoid** [comment]
Im close to submitting a fix for the CMakeLists. I will ping you when its pushed, and will feel better about merging if its reviewed.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 23 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaMm-TiYIc_ziQ8MQB:-Ked02BLnt4v-JK0s7fz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L23)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please consider using the following here. This version has two `drake_cc_library` which help Bazel parallelize a build.

```python
drake_cc_library(
    name = "world_sim_diagram_factory",
    srcs = [
        "world_sim_diagram_factory.cc",
    ],
    hdrs = [
        "world_sim_diagram_factory.h",
    ],
    visibility = ["//drake/examples/kuka_iiwa_arm:__subpackages__"],
    deps = [
        "//drake/common:drake_path",
        "//drake/common/trajectories:piecewise_polynomial_trajectory",
        "//drake/examples/kuka_iiwa_arm:iiwa_common",
        "//drake/lcm",
        "//drake/multibody:rigid_body_tree",
        "//drake/multibody/parsers",
        "//drake/multibody/rigid_body_plant",
        "//drake/multibody/rigid_body_plant:drake_visualizer",
        "//drake/systems/analysis:simulator",
        "//drake/systems/controllers:inverse_dynamics_controller",
        "//drake/systems/framework",
        "//drake/systems/primitives:constant_vector_source",
        "//drake/systems/primitives:demultiplexer",
        "//drake/systems/primitives:multiplexer",
        "//drake/systems/primitives:trajectory_source",
    ],
)

drake_cc_library(
    name = "iiwa_wsg_diagram_factory",
    srcs = [
        "iiwa_wsg_diagram_factory.cc",
    ],
    hdrs = [
        "iiwa_wsg_diagram_factory.h",
    ],
    visibility = ["//drake/examples/kuka_iiwa_arm:__subpackages__"],
    deps = [
        ":world_sim_tree_builder",
        "//drake/examples/kuka_iiwa_arm:iiwa_common",
        "//drake/examples/kuka_iiwa_arm:oracular_state_estimator",
        "//drake/multibody/rigid_body_plant",
        "//drake/systems/controllers:inverse_dynamics_controller",
        "//drake/systems/controllers:pid_controller",
        "//drake/systems/framework:diagram",
        "//drake/systems/framework:diagram_builder",
        "//drake/systems/primitives:constant_vector_source",
        "//drake/systems/primitives:matrix_gain",
    ],
)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-Ked7dNPVH40fQPBXW9P:b78dgqk)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 4 files at r5.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410)*

**Comment by naveenoid** [comment]
Done. @soonho-tri  Could you please give it one last pass?

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc, line 11 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-Ked-T0TQ9pSVVHAly6a:-KedCcvMJuZ5sIDGM-bP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7c73659ad87e6c92872d875d89a81c36ce8645b0/drake/examples/kuka_iiwa_arm/oracular_state_estimator.cc#L11)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this causes cpplint problem (+CI issue).
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 73 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-KeaOiVnOop4HxadjUi1:-KedCenNeWqohhG1EgPr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f61c8f74a6a29c9cf7bee7739ba2339f5914f6d/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L73)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, consider marking the following definitions as `const`:
```c++
Isometry3<T> X_WEE
std::set<int> gripper_instance_set
Matrix6<T> lumped_gripper_inertia_W
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KedCguJiiXI1wNVX4jp:b-3e00st)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-KedD1mf7yEZNtRLMaOR:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r3, 4 of 7 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 44 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-Kee1i8q0qzA1tDe4KGz:-Kee1i8q0qzA1tDe4KH-:b-w1b9ry) ([raw file](https://github.com/robotlocomotion/drake/blob/d103e7874edfc44b8bfecb93351b30935ec2281b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L44)):*
> ```objc
>       std::unique_ptr<systems::RigidBodyPlant<T>> combined_plant,
>       ModelInstanceInfo<T> iiwa_info, ModelInstanceInfo<T> wsg_info,
>       ModelInstanceInfo<T> box_info);
> ```

BTW, did you mean to copy the ModelInstanceInfo arguments? Otherwise could use `const ModelInstanceInfo<T>&` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-:-Kee2Qu0QBd1Yhx7U_8J:bnfp4nl)*

**Comment by naveenoid** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 44 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/5410#-Kee1i8q0qzA1tDe4KGz:-KeedeeOJbP4qeY6AYtJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d103e7874edfc44b8bfecb93351b30935ec2281b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L44)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, did you mean to copy the ModelInstanceInfo arguments? Otherwise could use `const ModelInstanceInfo<T>&` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5410)*

**Pull request merged**
