### PR TITLE
Replace "Welding body..." cout with log()->trace()

### PR DESCRIPTION
**Pull request by avalenzu**
Maybe I'm the only one who gets annoyed by these, but I doubt it :)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7544)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@seancurtis-tri  for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-DuEGkqL19qK7ex15-:b-rch5j4)*

**Comment by SeanCurtis-TRI** [comment]
my lgtm pending CI passage. Won't it suck if something in CI relies on that `cout`?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_tree.cc, line 366 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-L-E5PKI2Cs_XPcfQ1I-:-L-E5PKJqwUbc3evG0C7:b-saajsl) ([raw file](https://github.com/robotlocomotion/drake/blob/e5543045eac5d8ddbf526e92b74071e67c451dfe/drake/multibody/rigid_body_tree.cc#L366)):*
> ```cpp
>       }
>       if (!hasChild) {
>         drake::log()->trace("Welding joint {}", bodies[i]->getJoint().get_name());
> ```

BTW Crazy formatting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-E5RHE69pvgIyICC9r:b-b4z9f6)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544)*

**Comment by avalenzu** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_tree.cc, line 366 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-L-E5PKI2Cs_XPcfQ1I-:-L-Eg2CE1G7iToZGY4Ux:b-5m8bqj) ([raw file](https://github.com/robotlocomotion/drake/blob/e5543045eac5d8ddbf526e92b74071e67c451dfe/drake/multibody/rigid_body_tree.cc#L366)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Crazy formatting?
</blockquote></details>

That's what I get for submitting the PR from the train before running clang-format again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544)*

**Comment by liangfok** [comment]
BTW, I attempted to make a similar change in #5678. Maybe the concerns raised in that PR by @ggould-tri are no longer applicable.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-FvvhqKYYgbQwfCVCV:b-ttbwvk)*

**Comment by avalenzu** [comment]
What if I make it an `info` level log output? That should address @ggould-tri's concerns about users not seeing it, while still letting me turn it off by bracketing my RBT building code with `drake::log()->set_level()` calls.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-HflsXsP3iTj8VuLWN:boobngn)*

**Comment by liangfok** [comment]
That seems like a reasonable compromise since it'll require users to opt into not seeing the print statements.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-HkiNXFVQi4e92RYq3:bu0uokg)*

**Comment by SeanCurtis-TRI** [comment]
Agreed

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-HttcCiGMpA8kfaA6j:bqog80t)*

**Comment by avalenzu** [comment]
OK, I've made that change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-I-WiWLNudGCb0S11w:b9d3lsi)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-I079bzf2hQV0mKCmL:bmxilld)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7544#-:-L-I0JmuFmOhrjBqP5GO:bnfp4nl)*

**Pull request merged**
