### PR TITLE
Ensure that WITH_SPOTLESS is off if matlab is not found.

### LINKED ISSUE #2138: Superbuild failure in spotless, when matlab is not installed
From @jwnimmer-tri:  a clean superbuild with `env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make options (ceceg) && env PATH=/usr/lib/ccache:$PATH CXX=g++-4.9 CC=gcc-4.9 make -j8` randomly dies in superbuild externals for no discernable reason.  I eventually just gave up, did it under -j1, and now just use -j8 in drake.

### PR DESCRIPTION
**Pull request by david-german-tri**
Closes #2138.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2146) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@jwnimmer-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jwnimmer-tri">jwnimmer-tri</a>

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2146#-:-KFtwHMxR_u_sU3dEOe_:1417088721)*

**Comment by david-german-tri** [comment]
+@jwnimmer-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2146#-:-KFtxReAxUPvpxRta03f:1889825171)*

**Comment by jwnimmer-tri** [comment]
Sure, I will take a look.  I am unable to review the code, so I will test it instead.  It will still be a few minutes before my experiments there are done; stay tuned.

**Comment by david-german-tri** [comment]
Yep, a test would be much appreciated, since I was not able to reproduce your #2138 failure on Linux.

**Comment by jwnimmer-tri** [comment]
The fix appears to be correct.  (1) My build does not break under -j8.   (2) The build does not mention spotless now, whereas previously the build did mention it, even when it succeeded under -j1.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2146#-:-KFu0SXcLbeOaMjPOkLM:-884966914)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2146#-:-KFu0qR_Btm103svchIV:1417088721)*

**Pull request merged**
