### PR TITLE
Solver explains that one quadratic cost is non-convex.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059#-:-Ma1O6eu0lvQ2nxQgEgf:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint so far.  I want to wait until I have a clear head tomorrow morning to think about what kind of test habits we should put in place across the board for the new "explanation" outputs of SolverInterface.  The implementation changes look good so far.

> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059#-:-Ma1RVF75JYHpGIUGXIR:b-ftkf6c)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QaggCAngg6yQgGZ1:-Ma1QaggCAngg6yQgGZ2:btvrg7j) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L88)):*
> ```objc
>  */
> bool AreAllQuadraticCostsConvex(
>     const std::vector<Binding<QuadraticCost>>& quadratic_costs);
> ```

Does `AreAllQuadraticCostsConvex` serve any purpose anymore?  Should we remove it?  It's tantamount to `!FindNonconvexQuadraticCost(...)`.
___
*[solvers/aggregate_costs_constraints.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1PhnA8f0Ykcb3BGEW:-Ma1PhnA8f0Ykcb3BGEX:b74zx66) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L100)):*
> ```objc
> // If the program is compatible with this solver, returns true and clears the
> // explanation.  Otherwise, returns false and sets the explanation.  In either
> // case, the explanation can be nullptr in which case it is ignored.
> ```

This comment should say something about why "Convex" in in the function name, and what that means in terms of the function's contract with the caller.
___
*[solvers/aggregate_costs_constraints.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1PpuUEL6mBLU8tt2H:-Ma1PpuV4PZcf1QpsDVk:bxoyoqb) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L103)):*
> ```objc
> bool CheckConvexSolverAttributes(const MathematicalProgram& prog,
>                                  const ProgramAttributes& solver_capabilities,
>                                  const std::string& solver_name,
> ```

nit Use `std::string_view solver_name` (no const, not a reference) when passing string literals to helpers -- it saves the cost of a heap allocation.
___
*[solvers/aggregate_costs_constraints.cc, line 242 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QpZZ84DY4aCc937y:-Ma1QpZZ84DY4aCc937z:b-n380wa) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.cc#L242)):*
> ```cpp
>           "{} is unable to solve because the quadratic cost {} is non-convex. "
>           "Either change this cost to a convex one, or switch "
>           "to a different solver like SNOPT/IPOPT/NLOPT",
> ```

nit End sentence with a period for consistency, since we already have a sentence period in the middle of the message.
___
*[solvers/mosek_solver_common.cc, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1PObc3TxJnskiIZ1s:-Ma1PObc3TxJnskiIZ1t:b-cooem6) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/mosek_solver_common.cc#L33)):*
> ```cpp
> 
> namespace {
> bool CheckAttributes(const MathematicalProgram& prog,
> ```

nit Did you want to paste the API comment here on this one, like you have on the other solvers?
___
*[solvers/osqp_solver_common.cc, line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1RFwC2SMiz8D0G6cW:-Ma1RFwC2SMiz8D0G6cX:b-n380wa) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/osqp_solver_common.cc#L70)):*
> ```cpp
>           nonconvex_quadratic_cost->to_string() +
>           " is non-convex. Either change this cost to a convex one, or switch "
>           "to a different solver like SNOPT/IPOPT/NLOPT";
> ```

nit End sentence with a period for consistency, since we already have a sentence period in the middle of the message.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QaggCAngg6yQgGZ1:-Ma6jzAI6SbPwS6xK2F_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does `AreAllQuadraticCostsConvex` serve any purpose anymore?  Should we remove it?  It's tantamount to `!FindNonconvexQuadraticCost(...)`.
</blockquote></details>

Done.
___
*[solvers/aggregate_costs_constraints.h, line 100 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1PhnA8f0Ykcb3BGEW:-Ma6kARHD2aT6pvcWzFO:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L100)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This comment should say something about why "Convex" in in the function name, and what that means in terms of the function's contract with the caller.
</blockquote></details>

Done. Good call.
___
*[solvers/aggregate_costs_constraints.h, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1PpuUEL6mBLU8tt2H:-Ma6kL4lBftei3WRvftX:bjhfx3w) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Use `std::string_view solver_name` (no const, not a reference) when passing string literals to helpers -- it saves the cost of a heap allocation.
</blockquote></details>

Done. TIL `std::string_view`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma9VLUh8-Gydk9ObaxB:-MaAxhCE88lyeiD7mB87:brkn8gm) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Do you think its worth adding a very broad-based acceptance test for known-valid program attributes, for all of the solvers?  Something like this:

```
--- a/solvers/test/optimization_examples.cc
+++ b/solvers/test/optimization_examples.cc
@@ -68,6 +68,8 @@ OptimizationProgram::OptimizationProgram(CostForm cost_form,
 
 void OptimizationProgram::RunProblem(SolverInterface* solver) {
   if (solver->available()) {
+    EXPECT_TRUE(solver->AreProgramAttributesSatisfied(*prog_));
+    EXPECT_EQ(solver->ExplainUnsatisfiedProgramAttributes(*prog_), "");
     const MathematicalProgramResult result =
         RunSolver(*prog_, *solver, initial_guess());
     const std::optional<SolverType> solver_type =
```
</blockquote></details>

Good call, I just added it.

---
___
*[solvers/test/quadratic_program_examples.cc, line 661 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma9QYe44UrD_E-NaACb:-MaAzpP9AVBsfnhgA_V8:bt4ox1i) ([raw file](https://github.com/robotlocomotion/drake/blob/ad6731068626dba15988e1d8ed9f87f4179cfc2d/solvers/test/quadratic_program_examples.cc#L661)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Instead of repeating part of the implementation here (as to how the binding gets stringified, i.e., enforcing the details of whitespace and quoting), what do you think about a more property-based approach to testing this test:

(1) `HasSubstr("is non-convex")`
(2) `HasSubstr(description)`

... where for (2) we do `nonconvex_cost->evaluator()->set_description(description)` above.  The `description` would be something that would never be mistaken as any other part of the message, e.g., `"lorem ipsum"`.

That would allow for reasonable changes to the implementation, without needing to also adjust the test strings.
</blockquote></details>

Done. Thanks for the suggestion.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059#-:-MaB013_4t5lqrGpT5jw:b-5oszqt)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
Needs a lint brush.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done, PTAL!

> Reviewed 5 of 13 files at r1, 2 of 5 files at r2, 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059#-:-MaUo3MC7n4p1dezwOh4:b-v6scke)* status: 4 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUntPQC8iTp3W2IzGO:-MaUntPR0U3YeU1qdS6f:bu1gonz) (no related file):*
nit Any chance you can add Python bindings for new `Solver`+children class methods (and simple test)?

---
___
*[solvers/aggregate_costs_constraints.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QaggCAngg6yQgGZ1:-MaUku1D0bSNrDVlM8yF:b-d0qvu2) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Follow-up: This is public API. Are we OK removal without deprecation?
___
*[solvers/aggregate_costs_constraints.h, line 88 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUmbUp9I9tJdlQamIU:-MaUmbUp9I9tJdlQamIV:b-p0o35b) ([raw file](https://github.com/robotlocomotion/drake/blob/3edcd90ed14edd8b16e150b1aae98da4cdfd6de2/solvers/aggregate_costs_constraints.h#L88)):*
> ```objc
>  * quadratic costs are convex, then return a nullptr.
>  */
> const Binding<QuadraticCost>* FindNonconvexQuadraticCost(
> ```

Design Q: If this is for error reporting, why not report all non-convex costs?

(any chance you have link to motivating case in Drake Slack or StackOverflow?)
___
*[solvers/aggregate_costs_constraints.cc, line 232 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUmLPQ607XIEmDfrJa:-MaUmLPQ607XIEmDfrJb:be9majh) ([raw file](https://github.com/robotlocomotion/drake/blob/3edcd90ed14edd8b16e150b1aae98da4cdfd6de2/solvers/aggregate_costs_constraints.cc#L232)):*
> ```cpp
>     if (explanation) {
>       *explanation = fmt::format(
>           "{} is unable to solve because the quadratic cost {} is non-convex. "
> ```

nit Should this error message qualify that this is possibly *only* the first non-convex cost? (there may be others)
e.g.
`[...] unable to solve because (at least) the quadratic cost [..]`

**Comment by jwnimmer-tri** [comment]
___
*[solvers/aggregate_costs_constraints.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QaggCAngg6yQgGZ1:-MaUopYc7IOceN8pJo_j:bwkmrwm) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Follow-up: This is public API. Are we OK removal without deprecation?
</blockquote></details>

Yes, it was only added 6 days ago.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

___
*[solvers/aggregate_costs_constraints.h, line 88 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15059#-Ma1QaggCAngg6yQgGZ1:-MaUpJKmAqKf1kCJJbOA:b-hnt2yw) ([raw file](https://github.com/robotlocomotion/drake/blob/2709739f7a4111076a6c6834ccd9ae1af4574352/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, it was only added 6 days ago.
</blockquote></details>

OK Sweet, thanks for clarifying!

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUntPQC8iTp3W2IzGO:-MaUpIVDDGCGJXrcXduB:bjaporp) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Any chance you can add Python bindings for new `Solver`+children class methods (and simple test)?
</blockquote></details>

So far, we have never bound the solvers' static methods in pydrake.  Instead, we rely on the similarly-named instance methods, e.g., https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.SolverInterface.ExplainUnsatisfiedProgramAttributes in this case.  That does mean the user will need to construct a solver object before calling the method, but that has not been reported as an undue burden yet.

---

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[solvers/aggregate_costs_constraints.h, line 88 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUmbUp9I9tJdlQamIU:-MaUpkYdE6-rTeNFXzHU:byacak2) ([raw file](https://github.com/robotlocomotion/drake/blob/3edcd90ed14edd8b16e150b1aae98da4cdfd6de2/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Design Q: If this is for error reporting, why not report all non-convex costs?

(any chance you have link to motivating case in Drake Slack or StackOverflow?)
</blockquote></details>

Our current solver fails if any of the quadratic cost is non-convex. So I think if we inform the user that one cost is non-convex, the user could modify that cost, and try again.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 13 files at r1, 1 of 5 files at r2, 1 of 4 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059#-:-MaUsWvS6Yav8G4wBe-t:bcpz082)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUntPQC8iTp3W2IzGO:-MaUsV-bCipTZ3dzBh3a:bnoghtj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

So far, we have never bound the solvers' static methods in pydrake.  Instead, we rely on the similarly-named instance methods, e.g., https://drake.mit.edu/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.SolverInterface.ExplainUnsatisfiedProgramAttributes in this case.  That does mean the user will need to construct a solver object before calling the method, but that has not been reported as an undue burden yet.
</blockquote></details>

OK Sounds good, thanks for the explanation!

---
___
*[solvers/aggregate_costs_constraints.h, line 88 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15059#-MaUmbUp9I9tJdlQamIU:-MaUsNZjANbQOz9JI23V:b56uezr) ([raw file](https://github.com/robotlocomotion/drake/blob/3edcd90ed14edd8b16e150b1aae98da4cdfd6de2/solvers/aggregate_costs_constraints.h#L88)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Our current solver fails if any of the quadratic cost is non-convex. So I think if we inform the user that one cost is non-convex, the user could modify that cost, and try again. 
</blockquote></details>

OK Sounds good!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15059)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
