### PR TITLE
Update coefficients in AffineSystem

### PR DESCRIPTION
**Pull request by pangtao22**
This PR adds a function to `AffineSystem` that allows updating A , B, C, D, f0 and y0.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)

### CODE REVIEW

**Review by pangtao22 — COMMENTED** [review]
@RussTedrake for feature review. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZBZrCt6RzDlgqZski-:bsse04t)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @pangtao22)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: just a few changes requested below.

You'll also need to rebase against master to avoid conflicts with #19708.  (I think it should match the reflows you already did here... which motivated Jeremy's change).

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZBt9Gg5jWRkHzA59E6:bp8o98)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 498 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZBsoZV7YuaOxqvSXqb:-NZBsoZV7YuaOxqvSXqc:b-t58bt4) ([raw file](https://github.com/RobotLocomotion/drake/blob/05610f830a8705cf5303eadc9cd8d8af3c6f1f77/systems/primitives/affine_system.cc#L498)):*
> ```cpp
>     const Eigen::Ref<const Eigen::VectorXd>& new_y0) {
>   if (new_A.rows() != A_.rows() || new_A.cols() != A_.cols()) {
>     throw std::runtime_error("New A matrix has invalid dimensions.");
> ```

instead of "invalid dimensions" here, can we say that the new A matrix must be the same size as the existing A matrix?  And document that requirement in the header file method doc string?

Same for all of the other elements below.
___
*[`systems/primitives/test/affine_system_test.cc` line 113 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZBtVSy4HRbtJqYVIUg:-NZBtVSy4HRbtJqYVIUh:b1jguik) ([raw file](https://github.com/RobotLocomotion/drake/blob/05610f830a8705cf5303eadc9cd8d8af3c6f1f77/systems/primitives/test/affine_system_test.cc#L113)):*
> ```cpp
>   const auto new_C = Eigen::Matrix2d::Zero();
>   const auto new_D = Eigen::Matrix2d::Zero();
>   const auto new_y0 = Eigen::Vector2d::Zero();
> ```

please make them have some arbitrary non-zero values.  it's too easy to get the right answer for the wrong reason with zeros.

**Review by RussTedrake — COMMENTED** [review]
One more typo. 
The mac CI failure is not your fault.  But you still need to rebase master to resolve the merge conflict.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZGfrE69mU6itpZh0wh:b-au5uld)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 518 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZGesjp0w5-WWDJtQUA:-NZGesjq-2fOK_0mp6G2:bie9olf) ([raw file](https://github.com/RobotLocomotion/drake/blob/a688d0493a2cdb2eeeb88a7d6aedc91275e3e9b9/systems/primitives/affine_system.cc#L518)):*
> ```cpp
> 
>   if (new_y0.rows() != y0_.rows()) {
>     throw std::runtime_error("New and current f0 have different sizes.");
> ```

"f0" => "y0"

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`systems/primitives/affine_system.cc` line 498 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZBsoZV7YuaOxqvSXqb:-NZH9PeC7PENC7Wd6gDB:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/05610f830a8705cf5303eadc9cd8d8af3c6f1f77/systems/primitives/affine_system.cc#L498)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

instead of "invalid dimensions" here, can we say that the new A matrix must be the same size as the existing A matrix?  And document that requirement in the header file method doc string?

Same for all of the other elements below.
</blockquote></details>

Done.
___
*[`systems/primitives/affine_system.cc` line 518 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZGesjp0w5-WWDJtQUA:-NZH9vmT41CEyaaNwx8t:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/a688d0493a2cdb2eeeb88a7d6aedc91275e3e9b9/systems/primitives/affine_system.cc#L518)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"f0" => "y0"
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
+@sherm1 for platform review, per rotation.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZHu4_o5sED2F3nCvVP:b-i0igid)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZHtgGH1GHx1c1z_9Iz):*
marco?

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZHtgGH1GHx1c1z_9Iz):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

marco?
</blockquote></details>

These lines were duplicated when I tried to resolve merge conflicts.
https://github.com/pangtao22/drake-fork/blob/ee5dbd9d09f4c3de7f732d6c10f52c2d6f184a51/systems/primitives/affine_system.cc#L533-L535

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZHtgGH1GHx1c1z_9Iz):*
<details><summary><i>Previously, pangtao22 (Pang) wrote…</i></summary><blockquote>

These lines were duplicated when I tried to resolve merge conflicts.
https://github.com/pangtao22/drake-fork/blob/ee5dbd9d09f4c3de7f732d6c10f52c2d6f184a51/systems/primitives/affine_system.cc#L533-L535
</blockquote></details>

i only meant that you have a typo in your commit message (marco instead of macro).

All of your commits are going to be squashed on merge; i normally manually squash everything into a single commit with a clean commit message even during review.

**Review by pangtao22 — COMMENTED** [review]
One issue I see with `UpdateCoefficients` is that one can call this on a `LinearSystem` with nonzero `f0`, and `y0`, making the system affine instead of linear.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZJQ_VTBpphtzH_5f4d:b-6mzhzf)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by RussTedrake** [comment]
Is that true?  For the linear system, f0 and y0 are not just zero, they are empty.  Since you demand that the sizes don't change, they must stay empty during the UpdateCoefficients, no?

**Comment by pangtao22** [comment]
You're right! I didn't know that f0 and y0 are empty for linear systems.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 375 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZLykbH70XSaA3j6XK5:-NZLykbIAJ-qO2iX7ctP:b-2mw53s) ([raw file](https://github.com/RobotLocomotion/drake/blob/21441f6b1f3b07e50f538985ba0c4ec18e21c4eb/systems/primitives/affine_system.cc#L375)):*
> ```cpp
>     std::set<DependencyTicket>& prereqs = cache_entry.mutable_prerequisites();
>     prereqs.clear();
>     if (has_meaningful_C_) {
> ```

The dependency tickets are based on the constructor arguments for C and D.  If the C or D are zero upon constructor, but set to non-zero later on, the dependency tracking will be incorrect.

**Comment by pangtao22** [comment]
*[`systems/primitives/affine_system.cc` line 375 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZLykbH70XSaA3j6XK5:-NZMuEZPAEZexhige75j:bfo78q1) ([raw file](https://github.com/RobotLocomotion/drake/blob/21441f6b1f3b07e50f538985ba0c4ec18e21c4eb/systems/primitives/affine_system.cc#L375)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The dependency tickets are based on the constructor arguments for C and D.  If the C or D are zero upon constructor, but set to non-zero later on, the dependency tracking will be incorrect.
</blockquote></details>

Is it possible to change the dependency tickets in this function?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 375 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZLykbH70XSaA3j6XK5:-NZN5SYl10Qup7J473fq:b-edfesr) ([raw file](https://github.com/RobotLocomotion/drake/blob/21441f6b1f3b07e50f538985ba0c4ec18e21c4eb/systems/primitives/affine_system.cc#L375)):*
<details><summary><i>Previously, pangtao22 (Pang) wrote…</i></summary><blockquote>

Is it possible to change the dependency tickets in this function? 
</blockquote></details>

I think the solution would be to only accept arguments in the UpdateCoefficients method that would not change the value of has_meaningful_C_ and D_...

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`systems/primitives/affine_system.cc` line 375 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZLykbH70XSaA3j6XK5:-NZNJeJT3AWNC8zOq9oJ:b-6a92qo) ([raw file](https://github.com/RobotLocomotion/drake/blob/21441f6b1f3b07e50f538985ba0c4ec18e21c4eb/systems/primitives/affine_system.cc#L375)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think the solution would be to only accept arguments in the UpdateCoefficients method that would not change the value of has_meaningful_C_ and D_...
</blockquote></details>

Done. It throws if has_meaningful_C_ is changed from false to true, but does not throw if from true to false.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 520 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRtljk-jYZYUDDCbdx:-NZRtljk-jYZYUDDCbdy:b-l7zl3v) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L520)):*
> ```cpp
>   const bool is_new_D_meaningful = IsMeaningful(new_D);
> 
>   if (!has_meaningful_C_ && is_new_C_meaningful) {
> ```

we should really add a small test that covers this logic.  
___
*[`systems/primitives/affine_system.cc` line 521 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRt6cHDqRGBMM-CMeX:-NZRt6cI0uxeq1yCcELV:b-uafi02) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L521)):*
> ```cpp
> 
>   if (!has_meaningful_C_ && is_new_C_meaningful) {
>     throw std::runtime_error("new_C makes the output dependent on state.");
> ```

let's make this just a little more descriptive.  if i stumbled upon that error message, I wouldn't know what it was talking about.

can we say explicitly that "dependent on the state, when it was previously independent. This would change the dependencies of the output port, and it is currently unsupported."  and similar below?

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`systems/primitives/affine_system.cc` line 520 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRtljk-jYZYUDDCbdx:-NZXWDJN4fEUXgku6Gch:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L520)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

we should really add a small test that covers this logic.  
</blockquote></details>

Done.
___
*[`systems/primitives/affine_system.cc` line 521 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRt6cHDqRGBMM-CMeX:-NZXWE4f0sA1ZNvCOZ38:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L521)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

let's make this just a little more descriptive.  if i stumbled upon that error message, I wouldn't know what it was talking about.

can we say explicitly that "dependent on the state, when it was previously independent. This would change the dependencies of the output port, and it is currently unsupported."  and similar below?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 521 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRt6cHDqRGBMM-CMeX:-NZXxkef9KVmV58Mz2IW:b-h9xlew) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L521)):*
<details><summary><i>Previously, pangtao22 (Pang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

but the new_D makes it dependent on the input, not state... (sorry!)
___
*[`systems/primitives/test/affine_system_test.cc` line 134 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZXxtBxCNzaGxYBSw-H:-NZXxtBxCNzaGxYBSw-I:bh5r1je) ([raw file](https://github.com/RobotLocomotion/drake/blob/3109c0bd01ffadb8bd22964c2a5d9d0f3d0b336f/systems/primitives/test/affine_system_test.cc#L134)):*
> ```cpp
> 
>   auto dut_zero_D = AffineSystem<double>(A_, B_, f0_, C_, D_zero, y0_);
>   EXPECT_THROW(
> ```

nit: prefer DRAKE_EXPECT_THROWS_MESSAGE, like in BadSizeTest in this file.

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 521 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZRt6cHDqRGBMM-CMeX:-NZYAsiR7LhTLSgEhOdI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1be3e9ac1ba59b737707b83260e09d7e492261eb/systems/primitives/affine_system.cc#L521)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

but the new_D makes it dependent on the input, not state... (sorry!)
</blockquote></details>

Done.
___
*[`systems/primitives/test/affine_system_test.cc` line 134 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZXxtBxCNzaGxYBSw-H:-NZYAqn69uKE_3Qjcg4U:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3109c0bd01ffadb8bd22964c2a5d9d0f3d0b336f/systems/primitives/test/affine_system_test.cc#L134)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: prefer DRAKE_EXPECT_THROWS_MESSAGE, like in BadSizeTest in this file.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

**Review by sherm1 — COMMENTED** [review]
Platform pass done. A few minor testing requests.

> Reviewed 1 of 3 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZbEaT47nFa3cRO5uvM:b-5zdvcj)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[`systems/primitives/affine_system.cc` line 343 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZb4D21Ct4wS94cTXhQ:-NZb4D21Ct4wS94cTXhR:bw7ud3f) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/affine_system.cc#L343)):*
> ```cpp
>     msg << matrix_name;
>     msg << " have different sizes.";
>     throw std::runtime_error(msg.str());
> ```

minor: prefer fmt::format instead (here and elsewhere). 
BTW also consider including the sizes in the message (it's much easier with fmt::format!)



_Suggestion:_
```cpp
    throw std::runtime_error(fmt::format(
      "New and current {} have different sizes.", matrix_name));
```
___
*[`systems/primitives/affine_system.cc` line 347 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZb584y1vfowtLRuvhz:-NZb584y1vfowtLRuvi-:b-viyoi4) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/affine_system.cc#L347)):*
> ```cpp
> }
> 
> void CheckOutputConsistency(const bool is_meanginful,
> ```

typo: meanginful -> meaningful
___
*[`systems/primitives/test/affine_system_test.cc` line 138 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbDUCFAZPNuaLQbQGB:-NZbDUCFAZPNuaLQbQGC:brg9kgj) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/test/affine_system_test.cc#L138)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       dut_zero_D.UpdateCoefficients(new_A, new_B, new_f0, new_C, new_D, new_y0),
>       error_msg_regex);
> ```

minor: please add a unit test to verify that size change errors are caught and properly reported. Would be good also to have one to verify that a change from an empty f0/y0 to non-empty is rejected.
___
*[`bindings/pydrake/systems/primitives_py.cc` line 103 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbDvMp-C4tAY9jocVK:-NZbDvMp-C4tAY9jocVL:bg6k74q) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/bindings/pydrake/systems/primitives_py.cc#L103)):*
> ```cpp
>             doc.AffineSystem.y0.doc)
>         .def("UpdateCoefficients", &AffineSystem<T>::UpdateCoefficients,
>             doc.AffineSystem.UpdateCoefficients.doc)
> ```

minor: should specify the argument names (`py::arg("A")`, etc.) so that kwargs will work (see constructor above)
___
*[`bindings/pydrake/systems/test/primitives_test.py` line 192 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbEIavC_Ra3yKd0w4_:-NZbEIavC_Ra3yKd0w4a:bjehm8r) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/bindings/pydrake/systems/test/primitives_test.py#L192)):*
> ```Python
>         new_D = np.array([[11]])
>         new_y0 = np.array([12])
>         system.UpdateCoefficients(new_A, new_B, new_f0, new_C, new_D, new_y0)
> ```

minor: test call should use kwargs to make sure they are right



_Suggestion:_
```Python
system.UpdateCoefficients(A=new_A, B=new_B, f0=new_f0,
                          C=new_C, D=new_D, y0=new_y0)
```

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`systems/primitives/affine_system.cc` line 343 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZb4D21Ct4wS94cTXhQ:-NZnGZ2I8LlOLKB4XbLF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/affine_system.cc#L343)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: prefer fmt::format instead (here and elsewhere). 
BTW also consider including the sizes in the message (it's much easier with fmt::format!)
</blockquote></details>

Done.
___
*[`systems/primitives/affine_system.cc` line 347 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZb584y1vfowtLRuvhz:-NZnGg3L7YyAxSQbBIs9:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/affine_system.cc#L347)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: meanginful -> meaningful
</blockquote></details>

Done
___
*[`systems/primitives/test/affine_system_test.cc` line 138 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbDUCFAZPNuaLQbQGB:-NZnBoV6Dyu3YwW6Ayub:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/systems/primitives/test/affine_system_test.cc#L138)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: please add a unit test to verify that size change errors are caught and properly reported. Would be good also to have one to verify that a change from an empty f0/y0 to non-empty is rejected.
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/primitives_py.cc` line 103 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbDvMp-C4tAY9jocVK:-NZnNHO6-CuSVTRDYhg8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/bindings/pydrake/systems/primitives_py.cc#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: should specify the argument names (`py::arg("A")`, etc.) so that kwargs will work (see constructor above)
</blockquote></details>

Done.
___
*[`bindings/pydrake/systems/test/primitives_test.py` line 192 at r8](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-NZbEIavC_Ra3yKd0w4_:-NZnNIl66O5xTqvb1Wzb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4bd50eda132270f4626de1d7171ca8a20dad1560/bindings/pydrake/systems/test/primitives_test.py#L192)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: test call should use kwargs to make sure they are right
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Thanks Pang! Platform :lgtm:

> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19707#-:-NZqKqkK9TWODN9VaZzp:balno5a)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

**Pull request merged**
