### PR TITLE
[workspace] Upgrade sdformat_internal, gz_utils_internal to latest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
- Upgrade sdformat_internal to latest release sdformat14_14.0.0
- Upgrade gz_utils_internal to latest release gz-utils2_2.1.0

Towards #20290.

Doesn't build (deprecation errors); may need Drake changes?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20303#-NfqPeyHDFBDz-q9T_Y6:-NfqPeyHDFBDz-q9T_Y7:bn82hjd) (no related file):*
re deprecation error: looking

___

**Comment by rpoyner-tri** [comment]
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

re deprecation error: looking
</blockquote></details>

So far, looks like kSdfScopeDelimiter (type `std::string`) was deprecated in favor of kScopeDelimiter (type `std::string_view`). I hope to have a patch shortly.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20303#-NfqPeyHDFBDz-q9T_Y6:-NfqSJthDNPuhAj9Ve-P:bnx93u6) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So far, looks like kSdfScopeDelimiter (type `std::string`) was deprecated in favor of kScopeDelimiter (type `std::string_view`). I hope to have a patch shortly.
</blockquote></details>

Let's see how `r2` fares.

___

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending CI

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303#-:-NfqSgou1CpkFvZEHxQI:b3cfjge)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for license-related changes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303#-:-Nfqn-0B41r0uGYzUGP1:bulf1yu)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform / license.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20303#-:-Nfqu8E30tMpEfRkGU1_:bb7815o)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Pull request merged**
