### PR TITLE
Fixes Corner Case Where URDF Transmission Is for Non-Existent Joint.

### LINKED ISSUE #1864: RigidBody::getJoint() Fails To Throw Exception If Joint Not Set
This problem can be reproduced by trying to load a URDF model containing a transmission for a joint that does not exist. Instead of throwing an exception, it segfaults while trying to access member variable `joint`.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #1864

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2584)

### CODE REVIEW

**Comment by liangfok** [comment]
Since it's a Friday +@ggould-tri for platform review. 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKVEHFtT4Ahc8Rm6N3e:1633006773)*

**Comment by amcastro-tri** [comment]
+@amcastro-tri for feature review

**Comment by liangfok** [comment]
I apparently broke unit test `systems/plants/test/compareParsers`.

The error is:
```
Error using RigidBodyManipulator/findJointId (line 1172)
couldn't find unique joint non-existent-joint

Error in RigidBodyManipulator/addRobotFromURDF>parseTransmission (line 568)
      actuator.joint = findJointId(model,jn,robotnum);
```
Relevant files:
* drake-distro/drake/systems/plants/@RigidBodyManipulator/addRobotFromURDF.m - contains implementation of `RigidBodyManipulator/addRobotFromURDF(...)`.
* drake-distro/drake/systems/plants/@RigidBodyManipulator/RigidBodyManipulator.m - contains implementation of `findJointId(...)`

I will fix this problem soon.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKVolCzIThUBNdYgDJj:-893007491)*

**Comment by liangfok** [comment]
The problem is `systems/plants/test/compareParsers` was comparing the newly added `bad_transmission_no_joint.urdf`. To resolve the problem, I added this file to to the black list.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKWBwIGSA9lgIlZ-3tx:-1780145468)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2131/ and is thus ready for review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKYYWZmPldYAYAFYdbc:1105308925)*

**Comment by ggould-tri** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 148 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiBgrA2e3QT8fVddO3:-KKiBgrB_B9CAaEFZpua:-965095296) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L148)):*
> ```cpp
> // Tests whether the URDF parser is robust against an improperly specified
> // transmission element. In this case, the transmission element specifies a
> // non-existent joint.
> ```

Please reference #1864 here.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 159 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiAlZlkhfJ5hvGX-u7:-KKiAlZlkhfJ5hvGX-u8:-1447069054) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L159)):*
> ```cpp
>                                        "/systems/plants/test/rigid_body_system/"
>                                        "bad_transmission_no_joint.urdf"),
>       std::runtime_error);
> ```

`addRobotFromFile` will also throw a `std::runtime_error` for bad file extension, xml parse failure,  and possibly other cases I have not found.  You need something more expressive than a simple `EXPECT_THROW(..., std::runtime_error)` here to ensure that you are testing what you expect to be testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKi9cdtZh8IcoG2Y5ch:-KKi9cdtZh8IcoG2Y5ci:1821882863) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/RigidBodyTreeURDF.cpp#L53)):*
> ```cpp
> //                  See: https://github.com/RobotLocomotion/drake/issues/2583
> int findLinkIndexByJointName(RigidBodyTree* model, string joint_name) {
>   // Stores the index of the link whose joint is the one we're searching for.
> ```

Should this be instead something like "initializes to an invalid link index. Valid link indexes are between zero and RigidBodyTree::bodies.size()"?

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 156 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiBKcCtJu6T-kbMx6n:-KKiBKcCtJu6T-kbMx6o:1568786909) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L156)):*
> ```cpp
>   // transmission that specifies a non-existent joint.
>   EXPECT_THROW(
>       rigid_body_sys->addRobotFromFile(Drake::getDrakePath() +
> ```

Should we check here that this tests is actually throwing because `findLinkIndexByJointName` is failing? (with that simple file I wonder if it'd throw somewhere else).
Like you could do something like:
```c++
try {
  rigid_body_sys->addRobotFromFile(Drake::getDrakePath() + 
                                       "/systems/plants/test/rigid_body_system/"
                                       "bad_transmission_no_joint.urdf"))
} catch (std::runtime_error& e)
  // Asserts that the exception is throws when findLinkIndexByJointName fails to find a non-existing joint.
  EXPECT_TRUE(e.what().find("findLinkIndexByJointName") != std::string::npos);
}

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 53 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKi9cdtZh8IcoG2Y5ch:-KKiSosg60BvJR64ogdf:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/RigidBodyTreeURDF.cpp#L53)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Should this be instead something like "initializes to an invalid link index. Valid link indexes are between zero and RigidBodyTree::bodies.size()"?
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 148 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiBgrA2e3QT8fVddO3:-KKiT5VzfDAxVEC6ZzAS:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L148)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Please reference #1864 here.
</details>
Done.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 156 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiBKcCtJu6T-kbMx6n:-KKiTfNr8mMbFtlaVR9H:130379087) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L156)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Should we check here that this tests is actually throwing because `findLinkIndexByJointName` is failing? (with that simple file I wonder if it'd throw somewhere else).
> Like you could do something like:
> ```c++
> try {
>   rigid_body_sys->addRobotFromFile(Drake::getDrakePath() + 
>                                        "/systems/plants/test/rigid_body_system/"
>                                        "bad_transmission_no_joint.urdf"))
> } catch (std::runtime_error& e)
>   // Asserts that the exception is throws when findLinkIndexByJointName fails to find a non-existing joint.
>   EXPECT_TRUE(e.what().find("findLinkIndexByJointName") != std::string::npos);
> }
> 
> ```
</details>
Great advice. Thanks. Done.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 159 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKiAlZlkhfJ5hvGX-u7:-KKiTjrINCePoEn-h7j3:-1409756864) ([raw file](https://github.com/robotlocomotion/drake/blob/579a10403c23137448bc3476bc709c729a381c1d/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L159)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> `addRobotFromFile` will also throw a `std::runtime_error` for bad file extension, xml parse failure,  and possibly other cases I have not found.  You need something more expressive than a simple `EXPECT_THROW(..., std::runtime_error)` here to ensure that you are testing what you expect to be testing.
</details>
["Great Minds Think Alike"](http://idioms.thefreedictionary.com/Great+minds+think+alike)

Thanks. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKic7s8m7oxXBopCYqD:-84625242)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKidmFv5wiuahktRnH3:1417088721)*

**Comment by liangfok** [comment]
I'm pretty sure the `clang-mac` CI build is a known flake:

```
12:46:40 Slave went offline during the build
12:46:40 ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
12:46:40 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
12:46:40 Caused by: java.io.EOFException
12:46:40 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2351)
12:46:40 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2820)
12:46:40 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
12:46:40 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
12:46:40 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
12:46:40 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
12:46:40 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```

Thus, I believe this PR is ready final review / merge.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKius6p1dWDBWnlgojG:-892295623)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 200 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKjSUtzZiZs1a1Ec9VY:-KKjSUtzZiZs1a1Ec9VZ:-1882211092) ([raw file](https://github.com/robotlocomotion/drake/blob/b26748e4db54dbce771446134d1603b18e6786a7/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L200)):*
> ```cpp
>     EXPECT_TRUE(std::string(error.what()).find("FindBodyIndexByJointName") !=
>       std::string::npos);
>   }
> ```

I just realize that this does not detect the case in which no exception is thrown at all (it is already assuming that an exception is thrown and then checks that it comes from the right place). Would there be a (google) way to report failure at this point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc, line 200 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-KKjSUtzZiZs1a1Ec9VY:-KKjcCqCAjHSlA5UltCL:-897245157) ([raw file](https://github.com/robotlocomotion/drake/blob/b26748e4db54dbce771446134d1603b18e6786a7/drake/systems/plants/test/rigid_body_system/rigid_body_system_test.cc#L200)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I just realize that this does not detect the case in which no exception is thrown at all (it is already assuming that an exception is thrown and then checks that it comes from the right place). Would there be a (google) way to report failure at this point?
</details>
Good observation. I addressed this by performing two tests: one to ensure an exception is thrown, and a second one to ensure the exception was thrown by the right method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKjchksKV_qtCnfWkIe:-84625242)*

**Comment by amcastro-tri** [comment]
:lgtm: 

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584#-:-KKmpxX4w_iOgNgXeeqm:980077423)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2584)*

**Pull request merged**
