### PR TITLE
[math] Prefer LinearSolver over plain eigen solvers when using autodiff

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
#17037 reveals that Eigen 3.4's current implementation of direct solver provides the wrong derivatives. Using math::LinearSolver as in #17038 circumvents that.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thanks.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0hPyWl8gIbcFy-Td1X:bhg9nc0)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Great improvement!
now, should we unit test this new path on AutoDiffXd? if not, what is the purpose of this PR?

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0khpVN8HqglOwgAD1O:bughfba)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Not quite clear to me which diff you are referring to. Is it the change in sap_model?
The purpose of the PR is to avoid the issue that happened in #17037.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0l-J1K8fC_RS-oIsGc:b-ktgltp)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Comment by jwnimmer-tri** [comment]
Perhaps I can help frame the question -- 

To me, the question here is whether this bug fix deserves a _regression_ test.  Is it worth the effort of finding an (e.g., SAP) test input that triggers the Eigen upstream bug, so that Drake CI would fail in case anyone ever reverted the implementation changes from this PR.  Is it likely that anyone would do so?  And how much effort is it to craft such a test case?

I have no opinion on the answer to the question, but I think that's the best one to ask.

**Review by xuchenhan-tri — COMMENTED** [review]
I don't have a good answer either, but here's my thought process:

To determine if the test is "worth it", I'd think in terms of cost and benefit. It's probably not too hard to come up with a test since any derivatives that go through those eigen solvers will most likely be incorrect under the current eigen 3.4 and we just need to come up with anlytical answers to verify against. But it does require some thinking and is not trivial. OTOH, I don't see a whole lot of benefit. The upstream issue already got some attention, and when the issue is resolved, the benefit of the regression test is gone.

With or without that regression test, I think the changes in the PR is still of value. It seems to me like we should always prefer LinearSolver over the plain Eigen solver just because it's more performant in the autodiff case, regardless of eigen's autodiff/solver bug.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0l7mLx6jE2W0TnrpDg:b-1odtzi)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Those are good thoughts. The reason I asked is because `Code<double>` is literally a completely different code than `Code<AutoDiffXd>` and therefore in principle, the must be tested separately. Now, in practice we have not always been such good Samaritans and mostly we focused on `<double>` tests (proof of that is the recent bug with TAMSI that went undetected until someone paid close attention).

So my question is, if I write a PR (this one) that now says that some `AutoDiffXd` works properly, should I test it? I am not even asking to trigger the error we got with TAMSI, but rather should we test we get the right answers at least in a simple scenario? wouldn't that be the good practice to follow?

With SAP in particular, the docs actually state that `AutoDiffXd` is not supported (and in fact throws). Should we at least update the code so that now when using dense algebra we do get gradients through?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0lgBsTC9hPvLVQak2T:b-cz9cdj)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Comment by jwnimmer-tri** [comment]
By induction, we can rely on the unit testing of LinearSolver that the double and autodiff solve calls are equally correct, even though inside of that class there are different code paths.  That's what abstraction is for.  Only if the SAP code in specific if-else branches based on the scalar type would there be an _acute_ reason to test the two scalar types differently in the SAP unit tests.

Separate from this patch, you might decide that you want extra-special unit tests that the gradients of various SAP calls are numerically correct.  That's a fine goal, but is not especially related to his change, nor does this change have any influence on whether such tests are appropriate.

> If I write a PR (this one) that now says that some AutoDiffXd works properly, should I test it ...

This PR makes no such claim.  The claim here is that Eigen::LDLT is known to be broken (and also slow), so we should never ever call it.  Instead, we should always call LinearSolve (at least, until Eigen is improved).  That is the only thesis here.  Talking about _total_ numerical correctness is moving the goalposts for this change.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/contact_surface_utility.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0ljoF40txM6G73TDXe:-N0ljoF40txM6G73TDXf:b-7qjlaq) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/contact_surface_utility.cc#L98)):*
> ```cpp
>   for (int i = 0; i < v_count; ++i) {
>     const Vector3<T>& v = vertices_F[polygon[i]];
>     A.block(i, 0, 1, 4) << ExtractDoubleOrThrow(v(0)),
> ```

fyi, I think here you could do `<< math::ExtractValue(v), 1;`
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0liXpn3gcUgY6Tl9Qt:-N0liXpn3gcUgY6Tl9Qu:b-aqubxy) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L372)):*
> ```cpp
> 
>   // Factorize Hessian.
>   // TODO(amcastro-tri): Make use of mat::SolveLinearSystem() for a quick and
> ```

update TODO to something like:
"TODO(amcastro-tri): when T = AutoDiffXd propagate gradients analytically using the chain rule so that here we can use T = double for performance."

**Review by amcastro-tri — COMMENTED** [review]
> By induction, we can rely on the unit testing of LinearSolver that the double and autodiff solve calls are equally correct, even though inside of that class there are different code paths

That's more like what I needed, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0lkTkS0VfClCHn-2UK:b-8eb9ux)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0lkwlO89FubZU4kkT0:-N0lkwlO89FubZU4kkT1:b-k4tuwl) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L86)):*
> ```cpp
>                                              SapSolverResults<T>*) {
>   throw std::logic_error(
>       "SapSolver::SolveWithGuess(): Only T = double is supported.");
> ```

I believe now that you fixed the solver we could remove this?
If too much trouble we can leave it as is.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM but will wait for any final pushes before the emoji.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0lnW8wEk4UIdTtJBv5:b-h0skqw)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

___
*[`geometry/proximity/volume_mesh.h` line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0llH145cCZp2OeOXIl:-N0llH145cCZp2OeOXIm:b-gx07v8) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/volume_mesh.h#L249)):*
> ```objc
>     b << ReturnType(1.0), p_MQ;
>     const math::LinearSolver<Eigen::PartialPivLU, Matrix4<ReturnType>> A_lu(A);
>     const Vector4<ReturnType> b_Q = A_lu.Solve(b);
> ```

FYI matrix factorization seems way too expensive to be an inline function?

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Definitely too big of a change to make in this changeset, but \CC @DamrongGuoy to get this on your radar.  Next time y'all are visiting nearby code here, it might be worth fixing (or at least, not repeating the pattern in new code).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri)

___
*[`geometry/proximity/contact_surface_utility.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0ljoF40txM6G73TDXe:-N0n6QfI7bGeCD-LBAq7:ba4di8c) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/contact_surface_utility.cc#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi, I think here you could do `<< math::ExtractValue(v), 1;`
</blockquote></details>

Done thanks.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0lkwlO89FubZU4kkT0:-N0n69bK8ILB6TOMM3sR:b4fazgc) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L86)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe now that you fixed the solver we could remove this?
If too much trouble we can leave it as is.
</blockquote></details>

I'd defer that to a separate PR where we focus on enabling AutoDiffXd for SAP.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0liXpn3gcUgY6Tl9Qt:-N0n7HG64gsEG4ncBtZU:b-jphovg) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L372)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

update TODO to something like:
"TODO(amcastro-tri): when T = AutoDiffXd propagate gradients analytically using the chain rule so that here we can use T = double for performance."
</blockquote></details>

This sentence doesn't make sense to me.. Did you mean to say
"When T = AutoDiffXd propagate gradients analytically, use the chain rule so that here we can use T = double for performance?" (In fact, that doesn't make sense to me either...) Could you paraphrase?

AFAIK, using math::LinearSolver is already the preferred way of propagating gradients through a linear solve?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057#-:-N0nQZkXAL5fjcrz2Ymx:bnfp4nl)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 86 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0lkwlO89FubZU4kkT0:-N0ul7zm3gSbEQ_xqse_:b-7qqgkb) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L86)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'd defer that to a separate PR where we focus on enabling AutoDiffXd for SAP.
</blockquote></details>

fair.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0liXpn3gcUgY6Tl9Qt:-N0ulPGH1f8mas6b77IA:bvhhrao) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L372)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This sentence doesn't make sense to me.. Did you mean to say
"When T = AutoDiffXd propagate gradients analytically, use the chain rule so that here we can use T = double for performance?" (In fact, that doesn't make sense to me either...) Could you paraphrase?

AFAIK, using math::LinearSolver is already the preferred way of propagating gradients through a linear solve?

</blockquote></details>

What you wrote is ok. It's true, it doesn't make sense completely but I'm skimming over the details. The point is, the previous TODO doesnt not apply anymore and having a TODO about how we'd like gradients to propagate makes more sense. I think what you wrote is is enough to communicate the intention.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @amcastro-tri and @jwnimmer-tri)

___
*[`geometry/proximity/contact_surface_utility.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0ljoF40txM6G73TDXe:-N14hXHj2541fWppeMlE:by86eip) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/contact_surface_utility.cc#L98)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Done thanks.
</blockquote></details>

ExtractValue doesn't seem to work well with double vector/matrix.
___
*[`multibody/contact_solvers/sap/sap_solver.cc` line 372 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0liXpn3gcUgY6Tl9Qt:-N14h8UKCthcm61XZ3kL:bbd6fmk) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/multibody/contact_solvers/sap/sap_solver.cc#L372)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

What you wrote is ok. It's true, it doesn't make sense completely but I'm skimming over the details. The point is, the previous TODO doesnt not apply anymore and having a TODO about how we'd like gradients to propagate makes more sense. I think what you wrote is is enough to communicate the intention.
</blockquote></details>

I think the reason that prevents my understanding of the TODO is that the sentence is grammatically wrong. I think fixing that would help?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @jwnimmer-tri)

___
*[`geometry/proximity/contact_surface_utility.cc` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0ljoF40txM6G73TDXe:-N154WeI6riJOgDKSofp:bwuqwci) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/contact_surface_utility.cc#L98)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

ExtractValue doesn't seem to work well with double vector/matrix.
</blockquote></details>

Well I guess you just can't use << on a mix of vector and scalar? Reverted back to just scalars.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17057)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Comment by DamrongGuoy** [comment]
*[`geometry/proximity/volume_mesh.h` line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17057#-N0llH145cCZp2OeOXIl:-N15XxdpDO8BQCGdXteW:bepno17) ([raw file](https://github.com/robotlocomotion/drake/blob/999ed60195590da363828224c2ee8e162617faa7/geometry/proximity/volume_mesh.h#L249)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI matrix factorization seems way too expensive to be an inline function?

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

Definitely too big of a change to make in this changeset, but \CC @DamrongGuoy to get this on your radar.  Next time y'all are visiting nearby code here, it might be worth fixing (or at least, not repeating the pattern in new code).
</blockquote></details>

Thank you for letting me know. I agree that we should move `CalcBarycentric()` into `volume_mesh.cc` file.

**Pull request merged**
