### PR TITLE
SCS and Clarabel parses scalar PSD constraint as linear constraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-:-OBmR2mXCcn6DlNINDH7:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@rpoyner-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-:-OC0VkQZCteutE7SteP_:b8asji7)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`solvers/aggregate_costs_constraints.h` line 381 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-OC0ACC2C_8N9WkEvqiF:-OC0Vqtr5XyyTlEt0hdK:bbyr1d8) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3df5b076e2df3e331c7037390f7f8a7fa91eab9/solvers/aggregate_costs_constraints.h#L381)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Question. Does the order in which `ParsePositiveSemidefiniteConstraints` vs `ParseScalarPositiveSemidefiniteConstraints` are called matter? I believe no, but maybe it is worth documenting?
</blockquote></details>

SCS requires that PSD cone to be imposed after positive orthant cone, but Clarabel doesn't have this restriction. I added a comment in SCS.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`solvers/scs_solver.cc` line 465 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-OC0yP0U1nUl7n-iiSdr:-OC0yP0U1nUl7n-iiSds:b-1whwj8) ([raw file](https://github.com/RobotLocomotion/drake/blob/e009283d3ad5063676ceeb8a32faf54b1d84601f/solvers/scs_solver.cc#L465)):*
> ```cpp
>   // ParseScalarPositiveSemidefiniteConstraints() next to
>   // ParseLinearConstraints(), before calling
>   // ParsePositiveSemidefiniteConstraints().
> ```

nit: grammar + suggestion



_Suggestion:_
```cpp
  // SCS requires ordering the cone with the positive orthant cone coming before
  // the positive semidefinite cones. So we must call in order ParseLinearConstraints(),
  // ParseScalarPositiveSemidefiniteConstraints(), and finally
  // ParsePositiveSemidefiniteConstraints().
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200)* status: 3 unresolved discussions

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-OC5OTg10Cc8Wioj656P:-OC5Rglx38GBFTG6dFtm:b-hu7fwu) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor, testing: Do we need tests that pass some trivial program with the new constraints to each of clarabel and scs, to demonstrate that the integration works?
</blockquote></details>

It is actually tested in this PR already.

We have optimization programs in semidefinite_program_examples.h/cc, that were called by SCS and Clarabel, for example in https://github.com/RobotLocomotion/drake/blob/edeeb0bb1273635502e3b597e34230d5767ec3e9/solvers/test/scs_solver_test.cc#L428-L433

Before this PR, this test incurs a code path that treats the scalar PSD constraint as a PositiveSemidefinite cone in SCS/Clarabel. After this PR, this test incurs the new code path introduced in this PR, which treats the scalar PSD constraint as a linear equality constraint on that scalar.

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200)* status: 2 unresolved discussions

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22200#-OC5OTg10Cc8Wioj656P:-OC5So2b36HV_p_uVJcN:b-5kk0t9) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is actually tested in this PR already.

We have optimization programs in semidefinite_program_examples.h/cc, that were called by SCS and Clarabel, for example in https://github.com/RobotLocomotion/drake/blob/edeeb0bb1273635502e3b597e34230d5767ec3e9/solvers/test/scs_solver_test.cc#L428-L433

Before this PR, this test incurs a code path that treats the scalar PSD constraint as a PositiveSemidefinite cone in SCS/Clarabel. After this PR, this test incurs the new code path introduced in this PR, which treats the scalar PSD constraint as a linear equality constraint on that scalar.
</blockquote></details>

cool, thanks for the explanation!

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22200)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

**Pull request merged**
