### PR TITLE
[setup] Upgrade Bazel to latest release 7.1.1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI Prior upgrade #21103.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21123)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-documentation please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-mirror-to-s3 please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-packaging please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-wheel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-sonoma-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-ventura-clang-cmake-experimental-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-sonoma-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-sonoma-clang-cmake-experimental-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-debug please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-ventura-clang-cmake-experimental-everything-release please
@drake-jenkins-bot mac-arm-ventura-clang-cmake-experimental-release please

**Comment by jwnimmer-tri** [comment]
The macOS builds were happy.  Now for Ubuntu...

@drake-jenkins-bot linux-jammy-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-coverage please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-coverage please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-coverage please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-debug please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-everything-debug please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x2

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21123#-:-NvmCTW_AjukY6iiYOPN:bks4n6x)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Pull request merged**
