### PR TITLE
add [[nodiscard]] to solvers folder.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4F9IJF6E0r4EC6QyxO:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm: 

+@xuchenhan-tri for platform review please, thanks!

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4Z6YT42mn5PFWATSKK:bby44gc)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform review done. I have two questions:

1. What's the motivation behind this change? The only effect on application I see in this PR is a bunch of unit tests now needs to tag on `unused()`. I'd like to understand this better.
2. Among the functions getting the no discard attributes, a few of them are non-const, so it's conceivable that someone may call them for their side effects. I want to make sure that the newly added attributes are well-justified for those functions.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4ZCOsmAEvnIXseHxIW:b-mh74m6)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/sos_basis_generator.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17380#-N4ZD6rq4oOa9yx-COiZ:-N4ZD6rq4oOa9yx-COi_:brrdjzx) ([raw file](https://github.com/robotlocomotion/drake/blob/f3d11cc0b6c5f246a9d79b7672b2624f03a54bf3/solvers/sos_basis_generator.h#L23)):*
> ```objc
> */
> [[nodiscard]] drake::VectorX<symbolic::Monomial> ConstructMonomialBasis(
>     const drake::symbolic::Polynomial& p);
> ```

FYI, this is one example of a non-const nodiscard function. Perhaps it could be const instead? Ditto for other non-const nodiscard functions.

**Review by hongkai-dai — COMMENTED** [review]
> What's the motivation behind this change? The only effect on application I see in this PR is a bunch of unit tests now needs to tag on unused(). I'd like to understand this better.

This starts from the PR #17330 , where I called some function and thought it modifies the input in-place, but actually it returns the modified object. So I start to add `[[nodiscard]]` flag to const functions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4ZMR6iElvhgRmGpUND:b1z36pf)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/sos_basis_generator.h` line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17380#-N4ZD6rq4oOa9yx-COiZ:-N4ZMmZdAMxSWHPwCt-_:b-fg0o02) ([raw file](https://github.com/robotlocomotion/drake/blob/f3d11cc0b6c5f246a9d79b7672b2624f03a54bf3/solvers/sos_basis_generator.h#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, this is one example of a non-const nodiscard function. Perhaps it could be const instead? Ditto for other non-const nodiscard functions.
</blockquote></details>

Sorry this is a standalone function, not a class method. The input argument `p` is a const reference, so I don't think we should discard the return argument.

**Review by hongkai-dai — COMMENTED** [review]
I think Jeremy's answer here https://github.com/RobotLocomotion/drake/pull/17330#issuecomment-1150106659 explains the motivation for adding `[[nodiscard]]`

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4ZO4t67g3ioaEzoDTT:b-a2c6zi)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the reference! (Sorry that I mistook those free functions as class member functions!)
:lgtm: platform
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17380#-:-N4ZONBjAEphUKx8voBu:bp50n5e)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,xuchenhan-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
