### PR TITLE
[multibody] Re-enable asan for supernodal_solver_test

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR addresses the problem with asan builds reported in #16136:
1. Bumps to latest Conex commit, which removes hard coded build options.
2. Fixes uninitialized data in unit test, which triggered an error with asan.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16161)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-address-sanitizer please

**Comment by amcastro-tri** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-continuous-everything-address-sanitizer please

**Review by amcastro-tri — COMMENTED** [review]
Unit tests pass locally.
linux-bionic-clang-bazel-experimental-address-sanitizer is also successful. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16161#-:-MprolzK9_WGAwYKQGsC:brppthg)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Review by amcastro-tri — COMMENTED** [review]
+@sherm1 for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16161#-:-MprpSlU5T-JFHzkP6lW:bsu6fmf)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2, thanks Alejandro!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16161#-:-Mps86L9Ci69TJM-AoKW:b-odikwr)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16161#-:-Mps8FQT8nokm6XbrZQM:b3dcro0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

**Comment by jwnimmer-tri** [comment]
+(release notes: none)

**Pull request merged**
