### PR TITLE
Added RigidBodyElementId.

### PR DESCRIPTION
**Pull request by liangfok**
As discussed, this software abstraction will replace `model_id`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2919)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review please. +@sherm1 for platform review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNXj8pGAeqY1yBYL-1B:-2124642640)*

**Comment by sherm1** [comment]
Platform review: I don't understand what this is for. I don't see how a collection of strings is going to replace the model ID, or why this is needed. I'll wait for feature review from @amcastro-tri.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNY5674ra5_y14IreTn:1553519902)*

**Comment by liangfok** [comment]
SGTM. Basically an instance name + model name == `model_id`. We added an element ID just to be able to uniquely identify an individual element within a particular model instance.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNY938SuC7G-JsSRmQr:-1869879681)*

**Comment by amcastro-tri** [comment]
@sherm1: we had a pretty long discussion with @jwnimmer-tri, @liangfok and @maddog-tri about this and this is the only solution people agreed to accept. Essentially @liangfok needs to be able to identify what model (actually what instance of a model) each body, joint, etc belongs to. Everybody decided to encapsulate this into an "ElementId", where element could be a body, joint or any other physics engine object in the RBT. What is confusing is that SDF calls a model not to a particular instance but to a "template" of that instance. For instance if your model is called "Atlas" your instances names could be "robot1" and "robot2". 
It'd seem like instance name is enough. However it is not since a single SDF can have several models and each of them be instantiated multiple times. Again, this is unfortunately inherited from the SDF specification and the fact that our RBT is pretty limited. 
@liangfok and @jwnimmer-tri think this is a good incremental step towards having the "multiple models" capability in place without much coding or changes to RBT. Encapsulating this information in a class ElementId would help hiding implementation details and right now will mostly be holding some meta-data. 

IMO, we should have MultibodyWorld (currently RBT), and then you'd be able to add to this world simple objects like RigidBody's, Joint's, ForceElement's and Driver's (Drivers do no exist yet). You could also add more complex objects like a whole ArticulatedBody (to avoid confusion with RBT). Whit that in place @liangfok could work directly with ArticulatedBody instance to pass ROS the information needed to render multiple models. 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_element_id.h, line 64 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbpxKLocQeRPKF80tO:-KNbpxKLocQeRPKF80tP:-1959863289) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/rigid_body_element_id.h#L64)):*
> ```objc
>   const std::string instance_name_;
>   const std::string model_name_;
>   const std::string element_name_;
> ```

I think you will need `model_id` here so that each body could do `RigidBody::get_model_id() { return element_id.get_id();}`.
This will be needed in all methods like [`RigidBodyTree::centerOfMass`](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBodyTree.cpp#L924) taking a set of robotnum's on which to operate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNbqcxfMtrObj2u8GRu:-937931104)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNbt9waODpcnF58iBCe:-363363890) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/rigid_body_element_id.h#L22)):*
> ```objc
>  * using the union of all member variables in this class.
>  */
> class DRAKERBM_EXPORT RigidBodyElementId {
> ```

Consider renaming so that `RigidBody` is not in the name since your plan is that joints will also have this right?
what would a good name be? RBTElementProxy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by liangfok** [comment]
@amcastro-tri: Thanks for the summary!

> It'd seem like instance name is enough. However it is not since a single SDF can have several models and each of them be instantiated multiple times. Again, this is unfortunately inherited from the SDF specification and the fact that our RBT is pretty limited. 

I would be happy to modify the SDF parser to only parse one model within the SDF at a time to ensure a particular instance name only corresponds to a single model. The API will be something like the following:

```
/**
 * Adds a model defined by SDF file @p sdf_filename into @p system.
 *
 * @param[in] sdf_filename The name of the SDF file that contains the description
 * of the model to be added. A `std::runtime_error` is thrown if no such file exists.
 *
 * @param[in] model_name The name of the model within the SDF file to add. A
 * `std::runtime_error` is thrown if no such model exists in the SDF.
 *
 * @param[in] instance_name The name of the model instance. This is used to
 * distinguish between models that are added multiple times to the same
 * `RigidBodySystem`. A `std::runtime_error` is thrown if an existing model in
 * the `RigidBodySystem` has the same instance name.
 *
 * @param[in] floating_base_type The type of joint used to connect the model to
 * the existing `RigidBodyTree` in @p system.
 *
 * @param[out] system The `RigidBodySystem` to which to add the new model.
 */
void AddModelFromSDF(const std::string& sdf_filename,
    const std::string& model_name, const std::string& instance_name,
    const DrakeJoint::FloatingBaseType floating_base_type, RigidBodySystem* system);
```

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNbvsYakdmupHV2DOVO:-518863750)*

**Comment by sherm1** [comment]
@amcastro-tri: thanks, very helpful explanation! I will defer to your judgment regarding the element id since I wasn't part of that conversation.

> IMO, we should have MultibodyWorld (currently RBT).

I agree but I think we should save that name for a fully-updated multibody class whose API is directly compatible with System 2 (understands Context, templatized class rather than methods). I think it will reduce the pain substantially if both the System 1-style RBTree and System 2-style MBWorld can coexist for a while.

> You could also add more complex objects like a whole ArticulatedBody.

I like the World + ModelInstances terminology for thinking (non-physically) about what's in a simulation. I don't think "articulated body" is as good because (a) it is not a good description of collections of individual objects (e.g. rocks on the ground, balls in flight), and (b) the name is too close to "articulated body inertia".

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNc-Y0tqwxLZsrPeyQC:1929991355)*

**Comment by liangfok** [comment]
@amcastro-tri: I addressed your comments. PTAL.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/rigid_body_element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNce3ayR3RfrAmBsT_z:1556624968) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/rigid_body_element_id.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider renaming so that `RigidBody` is not in the name since your plan is that joints will also have this right?
> what would a good name be? RBTElementProxy?
</details>
Done. I renamed it to be `ElementID`.

---

*[drake/systems/plants/rigid_body_element_id.h, line 64 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbpxKLocQeRPKF80tO:-KNcfAyCTrFWQJKdIiFc:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/rigid_body_element_id.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I think you will need `model_id` here so that each body could do `RigidBody::get_model_id() { return element_id.get_id();}`.
> This will be needed in all methods like [`RigidBodyTree::centerOfMass`](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/RigidBodyTree.cpp#L924) taking a set of robotnum's on which to operate.
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNcfFr8s6EgVGwCADef:-1804091721)*

**Comment by liangfok** [comment]
Still waiting on @amcastro-tri's feature review.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNhplq1cJri7rA8bHnx:789502157)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNlhfdXGM31hXUUsPEG:-1463320713) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/element_id.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I renamed it to be `ElementID`.
</details>
I thought you'd notice there is `DrakeCollision::ElementId` already, sorry. That is why I proposed the wacky name above. Open to alternatives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by liangfok** [comment]
*[drake/systems/plants/element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNliMIcyf32N8vK7o8t:460816333) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/element_id.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I thought you'd notice there is `DrakeCollision::ElementId` already, sorry. That is why I proposed the wacky name above. Open to alternatives.
</details>
What do you think about "ModelElementID"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNlng4Dpes-3WTymICF:-682275779) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/element_id.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> What do you think about "ModelElementID"?
</details>
Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by liangfok** [comment]
@amcastro-tri: I addressed your review comment. PTAL. Thanks.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNm5LtILDahzp-A12h9:-693633255) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/element_id.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Sounds good to me.
</details>
Done. I renamed it to be `ModelElementId`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNm5OuuHOgC0nrn9OEy:525091193)*

**Comment by liangfok** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/model_element_id.h, line 22 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNbt9waODpcnF58iBCd:-KNmvykJeFJwZs5cyHx_:1837269821) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd94f6d7e819878ad852bda8721b34fa1e78ec8/drake/systems/plants/model_element_id.h#L22)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I renamed it to be `ModelElementId`.
</details>
Pinging @amcastro-tri for resolution of this thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNnGxnPreJ18VPSTo9A:1417088721)*

**Comment by liangfok** [comment]
Thanks. +@jwnimmer-tri for platform review please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNnIOVWwptFGJOtW5Qw:-1486335014)*

**Comment by liangfok** [comment]
Oh wait, I forgot I already assigned @sherm1 for platform review. -@jwnimmer-tri for platform review.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNnITeWb7xfKTTHSbl1:1867557772)*

**Comment by sherm1** [comment]
Platform review pass done.

---

Reviewed 2 of 11 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 41 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQGvKk8y-HXcpZfeN:-KNnQGvKk8y-HXcpZfeO:-743696966) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L41)):*
> ```objc
>    * actuator, sensor, etc.
>    *
>    * @param[in] model_id A unique number for each model instance.
> ```

Uh oh. If this is actually an instance ID it should not be called `model_id` -- that's really confusing! Wouldn't the right name be ... `instance_id`?

---

*[drake/systems/plants/model_element_id.h, line 45 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQ_4gKKHJ_nWCyAmB:-KNnQ_4gKKHJ_nWCyAmC:-406407202) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L45)):*
> ```objc
>   ModelElementId(const std::string& instance_name,
>                  const std::string& model_name, const std::string& element_name,
>                  int model_id);
> ```

Why does the parameter list include both `instance_name` and `instance_id` -- don't those both identify the same thing? (assuming model_id is really instance_id). That seems inconsistent with the class comment that says the union of all parameters is required to uniquely identify an element.

---

*[drake/systems/plants/model_element_id.h, line 64 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnRZa6coWcXyrY6Q-c:-KNnRZa6coWcXyrY6Q-d:-295888391) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L64)):*
> ```objc
> 
>   /**
>    * Returns the model ID. This is a unique number for each model instance.
> ```

This comment seems to confirm that this is an `instance_id`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNnS2FY6ELfgmVuLBXU:-1931483043)*

**Comment by liangfok** [comment]
@sherm1: I addressed your comments. PTAL. Thanks!

---

Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 41 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQGvKk8y-HXcpZfeN:-KNnncVPx9ufhld-ufWv:-1508883625) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Uh oh. If this is actually an instance ID it should not be called `model_id` -- that's really confusing! Wouldn't the right name be ... `instance_id`?
</details>
I renamed this variable to be `model_instance_id` to prevent people from thinking that this is a modeling element ID.

---

*[drake/systems/plants/model_element_id.h, line 45 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQ_4gKKHJ_nWCyAmB:-KNnn1utufXxMvas9yaz:-83949368) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Why does the parameter list include both `instance_name` and `instance_id` -- don't those both identify the same thing? (assuming model_id is really instance_id). That seems inconsistent with the class comment that says the union of all parameters is required to uniquely identify an element.
</details>
Yes, they identify the same thing. I originally did not include an `instance_id` but @amcastro-tri requested it because a big chunk of the existing API relies on it being a number. Here is his comment: https://reviewable.io/reviews/robotlocomotion/drake/2919#-KNbpxKLocQeRPKF80tO.

---

*[drake/systems/plants/model_element_id.h, line 64 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnRZa6coWcXyrY6Q-c:-KNo0P_YlQCOFw8XdDyy:776359764) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This comment seems to confirm that this is an `instance_id`.
</details>
Yes. I've update the documentation and created https://github.com/RobotLocomotion/drake/issues/2973.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNo1S_PILrG91Scat3U:1909952911)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/3171/ and is thus ready for platform review.

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNoMt837wzI5X1SN-oK:-41372227)*

**Comment by sherm1** [comment]
Reviewed 2 of 11 files at r3, 3 of 8 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 45 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQ_4gKKHJ_nWCyAmB:-KNop-lkEKxkFhluN3rl:78891266) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes, they identify the same thing. I originally did not include an `instance_id` but @amcastro-tri requested it because a big chunk of the existing API relies on it being a number. Here is his comment: https://reviewable.io/reviews/robotlocomotion/drake/2919#-KNbpxKLocQeRPKF80tO.
</details>
But now it seems `model_id` elsewhere doesn't make sense if these are really `instance_id`s. I think we at least need an issue filed to require that the rest of the code get fixed to use instance_ids instead of now-misleading model ids.

---

*[drake/systems/plants/model_element_id.h, line 33 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNopVeXXjw0eCc1pAs4:-KNopVeXXjw0eCc1pAs5:1120572943) ([raw file](https://github.com/robotlocomotion/drake/blob/08fbc96df13b18441cfb104e3ab9ea00e816f407/drake/systems/plants/model_element_id.h#L33)):*
> ```objc
>    * If multiple models exist within a single specification (as is the case for
>    * SDF, each model must have a unique instance name. Multiple modeling
>    * elements may \e not share the same instance name.
> ```

This comment doesn't seem right. Did you mean "multiple instances of the same model may not share the same instance name"?

---

*[drake/systems/plants/model_element_id.h, line 41 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNopl07FIddIQQbGS28:-KNopl07FIddIQQbGS29:-1918370827) ([raw file](https://github.com/robotlocomotion/drake/blob/08fbc96df13b18441cfb104e3ab9ea00e816f407/drake/systems/plants/model_element_id.h#L41)):*
> ```objc
>    *
>    * @param[in] element_name The name of the element within a model instance.
>    * These could be, for example, the name of a joint, body, frame, loop joint,
> ```

I'm not sure this is right now. Doesn't every instance of a model have the exact same element names? In that case isn't this the name of an element within a model, rather than within an instance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by liangfok** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/model_element_id.h, line 45 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNnQ_4gKKHJ_nWCyAmB:-KNovTvxWPPGt0fD8wO0:1874617697) ([raw file](https://github.com/robotlocomotion/drake/blob/9b6b8d15dfcbc8ba6a706834439c9602c3c6e788/drake/systems/plants/model_element_id.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> But now it seems `model_id` elsewhere doesn't make sense if these are really `instance_id`s. I think we at least need an issue filed to require that the rest of the code get fixed to use instance_ids instead of now-misleading model ids.
</details>
I believe the original semantics of `robotnum` and `model_id` were effectively model instance IDs. If true, this will hopefully just entail a find / replace. Here is the issue to track this task: #2975.

---

*[drake/systems/plants/model_element_id.h, line 33 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNopVeXXjw0eCc1pAs4:-KNotyfWHtgvZCp4vZtK:970109704) ([raw file](https://github.com/robotlocomotion/drake/blob/08fbc96df13b18441cfb104e3ab9ea00e816f407/drake/systems/plants/model_element_id.h#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This comment doesn't seem right. Did you mean "multiple instances of the same model may not share the same instance name"?
</details>
You're right. Fixed.

---

*[drake/systems/plants/model_element_id.h, line 41 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-KNopl07FIddIQQbGS28:-KNouBs6oFFwdWIpel8M:-1788373054) ([raw file](https://github.com/robotlocomotion/drake/blob/08fbc96df13b18441cfb104e3ab9ea00e816f407/drake/systems/plants/model_element_id.h#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm not sure this is right now. Doesn't every instance of a model have the exact same element names? In that case isn't this the name of an element within a model, rather than within an instance?
</details>
That's true. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919)*

**Comment by liangfok** [comment]
@sherm1: I addressed your comments. PTAL. Thanks!

---

Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNow1j-Al4msml1YGT6:1909952911)*

**Comment by sherm1** [comment]
Thanks, Liang -- :lgtm:.

---

Reviewed 1 of 11 files at r3, 1 of 8 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2919#-:-KNp0MQVKWByPkjAgYu6:619525287)*

**Pull request merged**
