### PR TITLE
Added LorentzConeConstraint bindings

### PR DESCRIPTION
**Pull request by rahulyesantharao**
Added a binding for LorentzConeConstraint to the pydrake mathematicalprogram package. Added tests in the mathematicalprogram_test unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@hongkai-dai or @EricCousineau-TRI would you like to review / work on this?

**Comment by rahulyesantharao** [comment]
Hi! This test worked on my local fork of Drake using Gurobi 7.5.2 - does the server use a different version?

**Comment by EricCousineau-TRI** [comment]
Hmm... Not quite sure what's going wrong, but when I ran it, it stated that I'm using `Mosek`, and not Gurobi.

Can I ask if you have MOSEK installed on your system?

**Comment by EricCousineau-TRI** [comment]
+@ericcousineau-tri for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723#-:-LBSuwKo6ZzHrXHmxxu8:b-7eskas)*

**Comment by rahulyesantharao** [comment]
Oh no - I only used config=gurobi; let me try config=everything

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8723#-LBYwj2rCUmH-HSbcd9i:-LBYwj2rCUmH-HSbcd9j:b-bejiw7) ([raw file](https://github.com/robotlocomotion/drake/blob/80aa1c5740095f9250605f7d48e361283d66f712/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L341)):*
> ```Python
>         prog = mp.MathematicalProgram()
>         x = prog.NewContinuousVariables(2, "x")
>         prog.AddQuadraticCost(np.eye(2), np.zeros(2), x)
> ```

It is better not to use quadratic cost, together with Lorentz cone constraints. You can re-formulate a quadratic cost as a Lorentz cone constraint, and then you have a second-order cone problem. The solver is usually faster on a conic optimization problem.

To your cost `min xᵀx`, you will need to introduce a slack variable `z`, with the Lorentz cone constraint `z ≥ √xᵀx`, and change the cost to `min z`. For more details, you could refer to https://docs.mosek.com/whitepapers/qmodel.pdf

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 341 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8723#-LBYwj2rCUmH-HSbcd9i:-LBYxXnm6KcOwbqAZkXs:bcm9xu1) ([raw file](https://github.com/robotlocomotion/drake/blob/80aa1c5740095f9250605f7d48e361283d66f712/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L341)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is better not to use quadratic cost, together with Lorentz cone constraints. You can re-formulate a quadratic cost as a Lorentz cone constraint, and then you have a second-order cone problem. The solver is usually faster on a conic optimization problem.

To your cost `min xᵀx`, you will need to introduce a slack variable `z`, with the Lorentz cone constraint `z ≥ √xᵀx`, and change the cost to `min z`. For more details, you could refer to https://docs.mosek.com/whitepapers/qmodel.pdf
</blockquote></details>

So the change to the code is to replace `prog.AddQuadraticCost(np.eye(2), np.zeros(2), x)` with

```py
z = prog.NewContinuousVariables(1, "z")
prog.AddLorentzConeConstraint(np.array([z[0], x[0], x[1]]))
prog.AddCost(z[0])
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 346 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8723#-LBZFIHyEMIW_rxQ8xCe:-LBZFIHyEMIW_rxQ8xCf:bwcz0lu) ([raw file](https://github.com/robotlocomotion/drake/blob/880020bc52650128513e1ba0223e5b85a04a537f/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L346)):*
> ```Python
>         # Add LorentzConeConstraints
>         prog.AddLorentzConeConstraint(np.array([0*x[0]+1, x[0]-1, x[1]-1]))
>         z = prog.AddLorentzConeConstraint(np.array([z[0], x[0], x[1]]))
> ```

I think we do should not return `z` here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723)*

**Comment by rahulyesantharao** [comment]
The tests seem to have failed at `call_python_test`

**Comment by EricCousineau-TRI** [comment]
Sorry about that! Submitted a patch for it; for now, it may work to retest it.

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by EricCousineau-TRI** [comment]
Yup! Since you effectively did feature review, I can do platform review. Would that work?

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723#-:-LC0hTqb1LdpyMWsvUlL:b-p4l5wf)*

**Comment by hongkai-dai** [comment]
Sure thing! +@hongkai-dai for feature review :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723#-:-LC0ioUO1FwDSJZDLqM8:b-hgdz3d)*

**Comment by EricCousineau-TRI** [comment]
Serving as platform reviewer: :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8723#-:-LC0kpof92YCI9pOcnMU:b200icb)*

**Pull request merged**
