### PR TITLE
[render_vtk] New option to choose EGL instead of GLX

### LINKED ISSUE #21700: [render_vtk] Remove X server requirement
(This was split out of #21050.)

**Is your feature request related to a problem? Please describe.**

There's no real reason for an X server to be a strict requirement for this renderer. It makes it harder to deploy to headless environments for containerized environments.

**Describe the solution you'd like**

Build VTK and RenderEngineVtk with EGL support, and provide a `RenderEngineVtkParams` config option to select EGL instead of GLX.

**Describe alternatives you've considered**

Users can do `xvfb` but that does non-HW-accelerated rendering and would be a bottleneck.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21700.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O8wtnY3EoxWeBQPhqg5):*
Working

Do not merge until after the upgrade has landed and we can rebase.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review, please.

> Reviewed 8 of 23 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-:-O9AgChYDGLm57n5FHJu:b-pq7hn8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With some cosmetics things.

I'm looking into the MultiMaterialObject.

> Reviewed 6 of 23 files at r1, 14 of 15 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-:-O9BP96u1OjdQhVZXV_0:b-qneyd8)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/render_vtk/internal_make_render_window.cc` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9BL9GUAE5T0hzSY3WA:-O9BL9GUAE5T0hzSY3WB:b-f9mxa9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d4b159c60ac05395a30d81c7c6519e8a16751a0/geometry/render_vtk/internal_make_render_window.cc#L36)):*
> ```cpp
> #else
>   if (use_egl) {
>     const bool load_egl_success = gladLoaderLoadEGL(EGL_NO_DISPLAY);
> ```

BTW The fact that `gladLoaderLoadEGL()` can apparently be run multiple times whereas `gladLoaderLoadGLX()`should be run no more than once per process feels like it is deserving of a comment rather than looking like an oversight.
___
*[`geometry/render_vtk/internal_render_engine_vtk.h` line 133 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9BLngnBHEbTZ4kexVs:-O9BLngnBHEbTZ4kexVt:bug7cz9) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d4b159c60ac05395a30d81c7c6519e8a16751a0/geometry/render_vtk/internal_render_engine_vtk.h#L133)):*
> ```objc
>     ~RenderingPipeline();
> 
>     const bool used_egl;
> ```

BTW Perhaps `using_egl` would be more apt?

1. The difference between use and used is small and easy to miss (making things look like typos).
2. The gerund seems to more accurately reflect the state of affairs -- the render window _is_ an egl window?
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 46 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9BNP0VCp4wyO-kjBZ6:-O9BNP0VCp4wyO-kjBZ7:b-5zxayt) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d4b159c60ac05395a30d81c7c6519e8a16751a0/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L46)):*
> ```cpp
> DEFINE_bool(show_window, false, "Display render windows locally for debugging");
> DEFINE_double(sleep, 0, "Seconds to sleep between renders");
> DEFINE_string(backend, "", "RenderEngineVtkParams.backend");
> ```

BTW Perhaps a note indicating that the default value for `backend` needs to remain the empty string?

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri for platform review per schedule, please.

> Reviewed 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-:-O9BbVKn7TDhW7k--D5q:b4mx0my)* status: LGTM missing from assignee ggould-tri(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
The actual logic here looks fine; a representation quibble below.

> Reviewed 5 of 23 files at r1, 12 of 15 files at r2, 2 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-:-O9FQ83a3GG_NB_4eTtr:b-7xz5yg)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FOwta69OR1-G7YnE1:-O9FOwta69OR1-G7YnE2:b-6o8yzn) (no related file):*
The meta of my comments below is that for a selection between three things, platform + bool + conditional silent defaulting is a weird representation.  It seems to me like it would be cleaner and make for more readable callsites for the three string values to map to three values of an enum rather than a bool.

___
___
*[`geometry/render_vtk/internal_make_render_window.h` line 13 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FNI95AwevFpxcsBfa:-O9FNI95AwevFpxcsBfb:b-gz00i6) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a04345f4ed9ef35305a981061a5147b97ac3a74/geometry/render_vtk/internal_make_render_window.h#L13)):*
> ```objc
> /* Returns a newly-constructed vtkRenderWindow, or else throws when unable.
> On Linux, use_egl chooses between EGL (when true) and GLX (when false).
> On macOS, use_egl is ignored. */
> ```

minor:  Is ignoring it the right behaviour?  It seems like a programmer error has occurred if you end up in this path, and the caller would like to know that their requested EGL is not available.



_Code quote:_
```objc
is ignored
```
___
*[`geometry/render_vtk/render_engine_vtk_params.cc` line 35 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FOFWU6Qa_20tyK09i:-O9FOFWU6Qa_20tyK09j:b4wq7xb) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a04345f4ed9ef35305a981061a5147b97ac3a74/geometry/render_vtk/render_engine_vtk_params.cc#L35)):*
> ```cpp
>       static const logging::Warn log_once(
>           "RenderEngineVtkParams.backend = 'EGL' is not available");
>       return default_result;
> ```

minor:  "EGL is not available" + setting `use_egl` to default seems odd; why not `return false` since you know that `true` is not valid?



_Code quote:_
```cpp
      static const logging::Warn log_once(
          "RenderEngineVtkParams.backend = 'EGL' is not available");
      return default_result;
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: LGTM missing from assignee ggould-tri(platform)

___
*[`geometry/render_vtk/internal_make_render_window.h` line 13 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FNI95AwevFpxcsBfa:-O9FZOhwCIkZnc3eDVQn:b-msqr8i) ([raw file](https://github.com/RobotLocomotion/drake/blob/3a04345f4ed9ef35305a981061a5147b97ac3a74/geometry/render_vtk/internal_make_render_window.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Not a programmer error.  The semantics of the bool was "use_egl_if_available".

In any case, with the enum this function doesn't "ignore" anymore.
</blockquote></details>

(Actually maybe it was a programmer error?  In any case, it's moot now.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-:-O9F_PK367e-ZNPKvwJo:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FOwta69OR1-G7YnE1:-O9F_4tW1LDWBBVRpTa6:b-a0md83) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I changed the parsing to use to enum for improved clarity.

Config files should not be platform-dependent, so the "warn instead of error when not compiled in this build" is absolutely what we want.
</blockquote></details>

Thank you; this is much clearer to me.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/internal_make_render_window.cc` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FblcH5DEq5y3J6jx-:-O9FblcIDoPew3nxpFOr:b-93ah77) ([raw file](https://github.com/RobotLocomotion/drake/blob/11aa5d5cf98aa495da3664fe242619395883e66f/geometry/render_vtk/internal_make_render_window.cc#L30)):*
> ```cpp
> // with the logic in render_engine_vtk_params.cc.
> vtkSmartPointer<vtkRenderWindow> MakeRenderWindow(
>     RenderEngineVtkBackend backend) {
> ```

This code is subtle and there are some implications that I don't think are obvious:

1. If I'm on linux and I request the Cocoa back end:
    - It automatically falls through to attempt EGL.
    - If initializing EGL doesn't work, we throw.
2. If I'm on mac and request either GLX or EGL, I get the logic error exception (without any indication of what I've requested or why it's a problem.

Have I read that correctly? Is that intentional? If so, I feel the intention should be made explicit. Alternatively, there's an undocumented prerequisite that the `backend` value be compatible with the platform.

If the correctness of this function is dependent on the mapping from string to enum in `ParseRenderEngineVtkBackend()` then that dependency should be clear.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: 1 unresolved discussion

___
*[`geometry/render_vtk/internal_make_render_window.cc` line 30 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/22025#-O9FblcH5DEq5y3J6jx-:-O9Fehh5E2N4OFFriQkI:bbrba11) ([raw file](https://github.com/RobotLocomotion/drake/blob/11aa5d5cf98aa495da3664fe242619395883e66f/geometry/render_vtk/internal_make_render_window.cc#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This code is subtle and there are some implications that I don't think are obvious:

1. If I'm on linux and I request the Cocoa back end:
    - It automatically falls through to attempt EGL.
    - If initializing EGL doesn't work, we throw.
2. If I'm on mac and request either GLX or EGL, I get the logic error exception (without any indication of what I've requested or why it's a problem.

Have I read that correctly? Is that intentional? If so, I feel the intention should be made explicit. Alternatively, there's an undocumented prerequisite that the `backend` value be compatible with the platform.

If the correctness of this function is dependent on the mapping from string to enum in `ParseRenderEngineVtkBackend()` then that dependency should be clear.
</blockquote></details>

Oops.  I forgot all of the `break;` statements.  Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22025)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
