### PR TITLE
trajectories: implement Append for PiecewiseQuaternionSlerp

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031#-:-MGaWFq3AVISnahtpxTk:blyxpiv)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[common/trajectories/piecewise_quaternion.cc, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14031#-MGaYCZv-znabznY4Rlp:-MGaYCZw8E78G2VQIMOr:b-mo6bvs) ([raw file](https://github.com/robotlocomotion/drake/blob/56313dedac0a03dcfefef9087be83df90f2f1880/common/trajectories/piecewise_quaternion.cc#L169)):*
> ```cpp
>         quaternions_.back(), quaternion));
>     angular_velocities_.push_back(internal::ComputeAngularVelocity(
>         time - this->breaks().back(), quaternions_.back(), quaternion));
> ```

After pushing back `quaternion` to `quaternions_`in the previous line, here `quaterion_.back()` and `quaternion` are the same quaternion? I think we should switch the order of calling these two `push_back`.

And BTW the unit test should have caught this problem.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/trajectories/piecewise_quaternion.cc, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14031#-MGaYCZv-znabznY4Rlp:-MGafCRR7D8oqcR78yLh:b-vb3wyp) ([raw file](https://github.com/robotlocomotion/drake/blob/56313dedac0a03dcfefef9087be83df90f2f1880/common/trajectories/piecewise_quaternion.cc#L169)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

After pushing back `quaternion` to `quaternions_`in the previous line, here `quaterion_.back()` and `quaternion` are the same quaternion? I think we should switch the order of calling these two `push_back`.

And BTW the unit test should have caught this problem.
</blockquote></details>

Yikes.  is_approx wasn't checking velocities.  fixed it now (and strengthened the test).

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031#-:-MGaflrg9SWh6zZr6oSn:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for platform

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031#-:-MGdLjk04ef7Hp4ga-fp:b-x1soh9)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14031#-:-MGiMgX14cjjzQ4YAQ-i:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),hongkai-dai

**Pull request merged**
