### PR TITLE
Expose joint_limit_{min,max} in python RBT.

### PR DESCRIPTION
**Pull request by avalenzu**
Also updates `rigid_body_tree_test.py` to use `FindResourceOrThrow`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8351)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@ericcousineau-tri  for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8351#-:-L7Ucrfjp2Re0DdzDYpl:b-raqeaa)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8351#-L7UqxM2aZACiBbgf05C:-L7UqxM3Eqz4AdkpWn0E:bxs8cuf) ([raw file](https://github.com/robotlocomotion/drake/blob/c989ca2f304169c27c11cf94cab2b834a75b6114/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L23)):*
> ```Python
>         # TODO(eric.cousineau): Reduce these tests to only test API, and do
>         # simple sanity checks on the numbers.
>         tree = RigidBodyTree(FindResourceOrThrow(os.path.join(
> ```

BTW I'd be fine with using `/` for paths we already know, since `os` seems to handle these well on Windows (although we're not really doing anything on Windows atm).

---

*[bindings/pydrake/multibody/test/rigid_body_tree_test.py, line 228 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8351#-L7UrCYX9LrZCcN2YTbX:-L7UrCYX9LrZCcN2YTbY:bcnxax8) ([raw file](https://github.com/robotlocomotion/drake/blob/c989ca2f304169c27c11cf94cab2b834a75b6114/bindings/pydrake/multibody/test/rigid_body_tree_test.py#L228)):*
> ```Python
>             floating_base_type=FloatingBaseType.kFixed)
>         # Check sizes.
>         self.assertEqual(tree.joint_limit_min.size, tree.number_of_positions())
> ```

BTW Would you be OK with merging this test into `test_atlas_parsing`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8351#-:-L7UrYAuf616NuxkZMri:bpqxd5f)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8351)*

**Comment by sammy-tri** [comment]
Holding off on review until CI passes.  The errors seem to be in the newly added test.

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8351#-:-L7VMFmo-_ol6eQJgw6q:b-ej0ul4)*

**Comment by avalenzu** [comment]
@sammy-tri , CI is happy now.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8351#-:-L7VfPJQ7BTphHB0TJYz:brk73i2)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8351#-:-L7VgOw72U6XDYYlMb8B:bnfp4nl)*

**Pull request merged**
