### PR TITLE
Document that Drake processes don't apply in examples/valkyrie.

### PR DESCRIPTION
**Pull request by david-german-tri**
@tkoolen for feature review, @RussTedrake for platform review.

This captures Russ's comments in Slack `#general` on 2016-09-28.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4158)

### CODE REVIEW

**Comment by RussTedrake** [comment]
short and to the point.  :LGTM: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-:-KWotIGUhU520vVPBTyo:bfzkkxg)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-KWp2ErzVqldB0ywj4uq:-KWp2ErzVqldB0ywj4ur:bdubrbz) ([raw file](https://github.com/robotlocomotion/drake/blob/4f858ce9c3ba926be162c7826b800bb10f8c7358/drake/examples/Valkyrie/README.md#L10)):*
> ```Markdown
> buildcop cannot trivially resolve them, a GitHub issue will be assigned to
> the Valkyrie team. If the issue is not resolved within 24 hours, the author
> or buildcop may disable the offending target.
> ```

BTW, to be consistent with the first sentence, "target" should be "targets".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4158)*

**Comment by siyuanfeng-tri** [comment]
@tkoolen is away at a conference, and might have more delay. I think it's better to skip him actually. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-:-KWp9Mz1Z8f8OU7lzhK6:b-uji3ii)*

**Comment by david-german-tri** [comment]
-@tkoolen 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Valkyrie/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-KWp2ErzVqldB0ywj4uq:-KWrwiWknLHBitfIzV6V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f858ce9c3ba926be162c7826b800bb10f8c7358/drake/examples/Valkyrie/README.md#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, to be consistent with the first sentence, "target" should be "targets".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-:-KWrwg4QfOY1H5E4lUGL:b-qvl4ue)*

**Comment by david-german-tri** [comment]
Merging without waiting for CI on the extra "s".

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4158#-:-KWrwpNqQkRoP98Numim:b-ohfs6j)*

**Pull request merged**
