### PR TITLE
KukaArmBenchmark

### PR DESCRIPTION
**Pull request by mitiguy**
Benchmark problem for Kuka IIwa robot.
Tests drake results versus exact (MotionGenesis)
results for forward kinematics (orientation, position,
angular velocity, velocity).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6242)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review: +@amcastro-tri 
Platform review +@sherm1 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-Kle1HgySSBIoRvmNr9n:b4hvdeg)*

**Comment by sherm1** [comment]
Platform pass done -- looks great (pending CI), a minor BTW here and there. @mitiguy says mods are coming so I'll finish review when those are ready.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlfAK9_RdIsObwm2Wnr:-KlfAK9_RdIsObwm2Wns:b-2vdch8) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/CMakeLists.txt#L2)):*
> ```CMake
> drake_install_headers(
>   kuka_iiwa_robot.h)
> ```

This isn't enough to get CMake to build the benchmark. Consider deleting this file -- we'll be all-Bazel by the time this is needed.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlfB4rsTvelg5MKM1di:-KlfB4rsTvelg5MKM1dj:b-orbiy2) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L38)):*
> ```objc
>   /// @param[in] v time-derivatives of q (generalized speeds).
>   ///
>   /// @returns Machine-precision values are returned as defined below.
> ```

BTW delete "are returned as" -- it doesn't read correctly this way and `@returns` already says that.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlfBJumW0p6XIiixD4v:-KlfBJumW0p6XIiixD4w:b-ui43ii) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L45)):*
> ```objc
>   /// p_NoGo_N   | Go's position from No, expressed in N.
>   /// w_NG_N     | G's angular velocity in N, expressed in N.
>   /// v_NGo_N    | Go's velocity in N, expressed in N.
> ```

BTW nice table!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-KlfEe5wJoZ9jTxjqUFo:bek1unl)*

**Comment by mitiguy** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlfAK9_RdIsObwm2Wnr:-KlfTbaWAWr7oi9jPPbZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/CMakeLists.txt#L2)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This isn't enough to get CMake to build the benchmark. Consider deleting this file -- we'll be all-Bazel by the time this is needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by amcastro-tri** [comment]
Thank you for this excellent benchmark @mitiguy!! Just some small comments. :lgtm: 

---

Reviewed 2 of 8 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Kle8wQl4PMxhgyv3oKq:-Kle8wQl4PMxhgyv3oKr:bbhuogu) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L2)):*
> ```cpp
> #include "drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h"
> #include "drake/multibody/benchmarks/kuka_iiwa_robot/MGKukaIIwaRobot.h"
> ```

This header must go right after "drake/common/extract_double.h" per style guide.
Headers go in the order:
1. component header under test at the top.
2. System headers
3. gtest header.
4. drake headers.

Look at [some other unit test](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/spatial_inertia_tests.cc) for a specific example.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klspi0Kt-GkjLmVYSxC:-Klspi0Kt-GkjLmVYSxD:bobas4g) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L14)):*
> Abbrevate

typo

And, BTW, I wouldn't say is a function and no conversion is happening, it is a typedef. So maybe: "Convenient type for Eigen matrices with a row-major order".

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqCEksOM23-1f_oUO:-KlsqCEksOM23-1f_oUP:b-t72zaa) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L15)):*
> ```cpp
> 
> // Abbrevate function for converting matrices from row-major to column-major.
> typedef Matrix<double, 3, 3, Eigen::RowMajor> ColumnMajorVector3d;
> ```

Sorry, I know I typed this myself but it should be more like `RowMajorVector3d`

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlfBJumW0p6XIiixD4v:-KlsrP7SP1hJMP301uD7:bwabqgp) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW nice table!
</blockquote></details>

BTW, I second that!

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqpWYV8FUCzMeGgSe:-KlsqpWYV8FUCzMeGgSf:b-ivazlh) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L1)):*
> ```objc
> // Drake interface to the MotionGenesis solution for a 7-DOF KUKA LBR iiwa robot
> ```

BTW, maybe you'd like to make this an `@file` public doc?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsrD2cr2AYBtmGYob3:-KlsrD2cr2AYBtmGYob4:b-1wgpd) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L25)):*
> ```objc
> class KukaIIwaRobot {
>  public:
>   KukaIIwaRobot() {}
> ```

Missing at least some minimum doc.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klsr-OIkDVxw7xE6gB2:-Klsr-OIkDVxw7xE6gB3:btmgs5n) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L26)):*
> ```objc
>  public:
>   KukaIIwaRobot() {}
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(KukaIIwaRobot);
> ```

`DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` must be the first thing that appears after `public:`.
You can cave the default constructor right after, with a blank line in between, and a minimum of documentation for that default constructor.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klsrf79_rnwaB8EZP9q:-Klsrf79_rnwaB8EZP9r:bw9y20v) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L17)):*
> ```cpp
> void CompareEndEffectorPositionVelocityVsExpectedSolution(
>   const Eigen::Matrix<double, 7, 1>& joint_angles,
>   const Eigen::Matrix<double, 7, 1>& joint_anglesDt,
> ```

BTW, in Drake we usually call those `q` and `v`. Maybe worth using the same convention?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsrxFZG2Sytxz2UY7A:-KlsrxFZG2Sytxz2UY7B:bjz7zzl) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L35)):*
> ```cpp
>   // Compare actual results with expected results.
>   constexpr double epsilon = std::numeric_limits<double>::epsilon();
>   const double tolerance = 10*epsilon;
> ```

BTW, space around `*`

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlssXHto2aiu4I4kgrN:-KlssXHto2aiu4I4kgrO:bj3iqof) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L94)):*
> ```cpp
>   joint_anglesDt << qADt, qBDt, qCDt, qDDt, qEDt, qFDt, qGDt;
> 
>   // MotionGenesis solution for these joint angles/time-derivatives.
> ```

BTW, weren't these numbers obtained with Simwise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-KlssiiiaRIctbX_cQkO:b-ri4ct)*

**Comment by mitiguy** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Kle8wQl4PMxhgyv3oKq:-KltMhS66KWo_QUc1kq5:b-u124mc) ([raw file](https://github.com/robotlocomotion/drake/blob/0bfcfdf240e95f5719f0e8c7f6c85a24ff69b462/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This header must go right after "drake/common/extract_double.h" per style guide.
Headers go in the order:
1. component header under test at the top.
2. System headers
3. gtest header.
4. drake headers.

Look at [some other unit test](https://github.com/RobotLocomotion/drake/blob/master/drake/multibody/multibody_tree/test/spatial_inertia_tests.cc) for a specific example.
</blockquote></details>

Done.  Thanks for the helpful tips.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klspi0Kt-GkjLmVYSxC:-KltPHTTKYxu038JUswa:bmfxq1z) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L14)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Abbrevate

typo

And, BTW, I wouldn't say is a function and no conversion is happening, it is a typedef. So maybe: "Convenient type for Eigen matrices with a row-major order".
</blockquote></details>

Done.  

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqCEksOM23-1f_oUO:-Kltt3vT8RGIxC3A64l4:b34bnji) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Sorry, I know I typed this myself but it should be more like `RowMajorVector3d`
</blockquote></details>

Done. Name changed to RowMajorToColumnMajorVector3d.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsrD2cr2AYBtmGYob3:-KltuXsWeXwfKMTf9flH:b-x47rh3) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Missing at least some minimum doc.
</blockquote></details>

Done.  Added @file as you mentioned.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klsr-OIkDVxw7xE6gB2:-KltxUhK9ytWNM3gR8vk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L26)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` must be the first thing that appears after `public:`.
You can cave the default constructor right after, with a blank line in between, and a minimum of documentation for that default constructor.

</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 94 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlssXHto2aiu4I4kgrN:-Klu6vNtfEpDIFr_fmNQ:b-qi62kt) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L94)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, weren't these numbers obtained with Simwise?
</blockquote></details>

Done.  Not exactly.  By continually cranking up accuracy in Simwise, I was able to see 
that SimWise was converging to the MotionGenesis values.  However, I am not sure I could
obtain the last few of the 16 digits in Simwise (even if I let it converge for a long time).
MotionGenesis was built for accuracy and speed.
Simwise was built for ease-of use.
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by sherm1** [comment]
:lgtm: pending a few BTWs, ptal.

---

Reviewed 2 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlusmxZ1sj8xXEUbUjB:-Klusmx__ct3FFhRt0xX:bnd4bwt) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L1)):*
> ```objc
> /// @file kuka_iiwa_robot.h Drake interface to the MotionGenesis solution for a
> ```

BTW a few things wrong here:
- I believe `@file` has to be on its own doxygen line. Please format the doxygen and have a look.
- In general the `@file` documentation is useless since people normally won't see it anywhere in doxygen. Consider moving this documentation to the class where it will actually get seen. (Of course this will get seen by a programmer reading the header file.)
- Should not include the file name in the comment here. That isn't helpful since we know the file name already, but the real problem is that it is brittle because it will stay this way even if the file name is changed in the future by some unknowing diligent programmer.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klus4Oot1ZTZlcDaCXf:-Klus4Oot1ZTZlcDaCXg:b2zrtsr) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L15)):*
> ```cpp
> // Function to compare Kuka iiwa robot arm end-effector (frame G)'s orientation
> // position, angular velocity, velocity in World (frame N) to expected solution.
> // The inputs to this method are the state (q, qDt) and expected values.
> ```

BTW in Drake this is conventionally called q and qdot. I know you like qDt better -- I think that's OK but you should explain that qDt is your name for qdot so people aren't confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-KlutZMC4qgabh6ZFEf5:b-kt6the)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqCEksOM23-1f_oUO:-Klxk89jJi4qxMfQgso_:bfogxff) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L15)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Done. Name changed to RowMajorToColumnMajorVector3d.
</blockquote></details>

BTW, why the "conversion" flavor encoded in the type?. It is just a type for vectors in row-major order. So why not just "RowMajorVector3d"? the conversion you allude to actually happens during assignment. 

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlxkkseTlDASzUoDjgJ:-KlxkkseTlDASzUoDjgK:begkqf) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L27)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(KukaIIwaRobot);
> 
>   /// This empty constructor is like the default constructor (there are no
> ```

"is like the default constructor"?

What about something along the lines of what the constructor actually does?: "Constructs an instance for a Motion Genesis model of a Kuka LBR iiwa arm. All parameters in the model correspond to the 14 Kgr payload model."

Yes, programmatically you do not set the parameters in this class, but they are hardcoded in your MG generated files, so from a user's perspective it is the same thing.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klxm5AN2aq8Ml8vIaaF:-Klxm5AN2aq8Ml8vIaaG:b-p11fki) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L50)):*
> ```objc
>   /// v_NGo_N    | Go's velocity in N, expressed in N.
>   std::tuple<Matrix3d, Vector3d, Vector3d, Vector3d>
>   CalcForwardKinematicsEndEffectorViaMotionGenesis(
> ```

Why the refactor? Isn't the "ViaMotionGenesis" part a contract of this class? as you add more and more methods, do you foresee ending the name of each method with "ViaMotionGenesis"?

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc, line 15 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klus4Oot1ZTZlcDaCXf:-KlxmUyqb4npaH3L-pQK:b-50m28a) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_test.cc#L15)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in Drake this is conventionally called q and qdot. I know you like qDt better -- I think that's OK but you should explain that qDt is your name for qdot so people aren't confused.
</blockquote></details>

BTW, ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by mitiguy** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqCEksOM23-1f_oUO:-Klyha77kVyt5fZa44a_:bj37f5j) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, why the "conversion" flavor encoded in the type?. It is just a type for vectors in row-major order. So why not just "RowMajorVector3d"? the conversion you allude to actually happens during assignment. 
</blockquote></details>

Got rid of this typedef.  It is only used once.  Comments 

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlxkkseTlDASzUoDjgJ:-KlyksRBgJgmssOrNPFq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

"is like the default constructor"?

What about something along the lines of what the constructor actually does?: "Constructs an instance for a Motion Genesis model of a Kuka LBR iiwa arm. All parameters in the model correspond to the 14 Kgr payload model."

Yes, programmatically you do not set the parameters in this class, but they are hardcoded in your MG generated files, so from a user's perspective it is the same thing.
</blockquote></details>

Done.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klxm5AN2aq8Ml8vIaaF:-Klyl17yxIzkADvy9Mmg:b-5icz6e) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Why the refactor? Isn't the "ViaMotionGenesis" part a contract of this class? as you add more and more methods, do you foresee ending the name of each method with "ViaMotionGenesis"?
</blockquote></details>

In this class, I envision having dual methods, e.g.,
  CalcForwardKinematicsEndEffectorViaMotionGenesis
  CalcForwardKinematicsEndEffectorViaDrake.

If that changes, I will remove ViaMotionGenesis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by amcastro-tri** [comment]
Just one small discussion open that I will let up to you to resolve @mitiguy. (notice I  have green checkmakrs on all your files!).

---

Reviewed 1 of 8 files at r1, 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-KlsqCEksOM23-1f_oUO:-Km1zsCLWcYfc6eti9K0:b-3z9lgv) ([raw file](https://github.com/robotlocomotion/drake/blob/448faac768275b4b573cc7d1c6d8d274cbd27a12/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.cc#L15)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

Got rid of this typedef.  It is only used once.  Comments 
</blockquote></details>

Sure, that works. You'll need it back in future PR's when you add more methods, unless of course you want to retype that every time you use it.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klxm5AN2aq8Ml8vIaaF:-Km2-A1tjQjeszf3Pfip:b-qj4s4y) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L50)):*
<details><summary><i>Previously, mitiguy wrote…</i></summary><blockquote>

In this class, I envision having dual methods, e.g.,
  CalcForwardKinematicsEndEffectorViaMotionGenesis
  CalcForwardKinematicsEndEffectorViaDrake.

If that changes, I will remove ViaMotionGenesis.

</blockquote></details>

`CalcForwardKinematicsEndEffectorViaDrake()`? what do you mean? using MBT? that's a bad idea. The MBT model will be self-contained, in its own unit test file, with its own build dependencies. We should not couple our self-contained benchmarking code with the MBT or any other Drake code whenever possible. I thought we talked about this? I'm sorry it wasn't clear. Again, just think only about your BUILD file and you'll see how ugly that gets in terms of unnecessary coupling.
The idea was that a unit test say `multibody_tree_model_of_kuka_iiwa_test.cc` will use your benchmark, but not the opposite. I have a PR in the works that will get pushed today using the Acrobot benchmark, maybe that'll help this discussion.

Regarding the review process, @mitiguy, which will help you streamline your work. When I place a green checkmark (as I had done with this file) on a file that means I am satisfied with everything in it, no need to add refactor or any other code unless of course strictly necessary. What that means is, adding the smallest change (in this case a refactor I had no idea you had in mind) has the potential to slow down your own PR. Remember, I had LGTM'ed this, why to keep pushing unrequested changes on each commit?!

We can always VC if that helps or just call me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-Km21dPx3Gk045oBIDIb:bepgs5b)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klxm5AN2aq8Ml8vIaaF:-Km44JAS-rHuiDId8aCY:b-etjke6) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`CalcForwardKinematicsEndEffectorViaDrake()`? what do you mean? using MBT? that's a bad idea. The MBT model will be self-contained, in its own unit test file, with its own build dependencies. We should not couple our self-contained benchmarking code with the MBT or any other Drake code whenever possible. I thought we talked about this? I'm sorry it wasn't clear. Again, just think only about your BUILD file and you'll see how ugly that gets in terms of unnecessary coupling.
The idea was that a unit test say `multibody_tree_model_of_kuka_iiwa_test.cc` will use your benchmark, but not the opposite. I have a PR in the works that will get pushed today using the Acrobot benchmark, maybe that'll help this discussion.

Regarding the review process, @mitiguy, which will help you streamline your work. When I place a green checkmark (as I had done with this file) on a file that means I am satisfied with everything in it, no need to add refactor or any other code unless of course strictly necessary. What that means is, adding the smallest change (in this case a refactor I had no idea you had in mind) has the potential to slow down your own PR. Remember, I had LGTM'ed this, why to keep pushing unrequested changes on each commit?!

We can always VC if that helps or just call me!

</blockquote></details>

@amcastro-tri, clicking the file green means you reviewed it at the current revision level, not that it is perfect as-is. You might have made comments in those files, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-Klxm5AN2aq8Ml8vIaaF:-Km4VOn3FT5WNl3FxBWa:b-e29tpm) ([raw file](https://github.com/robotlocomotion/drake/blob/01bd3fb3793a00b48e0a01c570a054a420b0f425/drake/multibody/benchmarks/kuka_iiwa_robot/kuka_iiwa_robot.h#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@amcastro-tri, clicking the file green means you reviewed it at the current revision level, not that it is perfect as-is. You might have made comments in those files, right?
</blockquote></details>

True, there is that situation also. I just meant as a general guideline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6242#-:-Km8Mnp-SyIz4eThxptK:bnfp4nl)*

**Pull request merged**
