### PR TITLE
common: Move geometry::Identifier here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #12560.  Used by #12622.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12621)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for feature review, please.

**Comment by sherm1** [comment]
FYI -- issue #12563 reports a problem with a "global" geometry Id, which is that it has the effect of assigning different Ids for otherwise-identical systems.

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule (tomorrow), please.

**Comment by jwnimmer-tri** [comment]
Dur, don't know which day it is.  +@ggould-tri is on call, not -@sherm1.  Sorry!

**Pull request merged**
