### PR TITLE
Install drake-lcm-spy and create a launcher

### PR DESCRIPTION
**Pull request by fbudin69500**
drake-lcm-spy is the same tool as bot-spy but loads all the lcmtypes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7119)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4GW8iaG4P1NllSz_m:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
So again I'll review this assuming its a good idea, but really please change Spartan to build libbot2 on its own in the future, so we can stop exporting this from Drake.  (Would it help to have that in a Drake issue (stop installing libbot2) for tracking?)

:lgtm: 

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-Kv4JNcsqRo_Hiy4fd9k:-Kv4JNcsqRo_Hiy4fd9l:brn7k65) ([raw file](https://github.com/robotlocomotion/drake/blob/0cf145a3a830ed5771b5aefc9dc79be953abadef/tools/libbot.BUILD#L583)):*
> ```
>     rename = {
>         "share/java/liblcmspy_plugins_bot2.jar": "lcmspy_plugins_bot2.jar",
>         "bin/bot-spy-launcher.sh": "bot-spy",
> ```

FYI If this doesn't actually work, should we still be installing it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4IhgM-4iCioxIiKfY:b-w95tc1)*

**Comment by jamiesnape** [comment]
This is really not related to libbot at all. When libbot disappears from Drake it still needs to be installed, it will just have a few less LCM types.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4Ja5hqFBBeeggo5-N:b-20e5aq)*

**Comment by jwnimmer-tri** [comment]
If Drake is going to install `lcm-spy` (or any derivative thereof), it should install a copy that is indistinguishable from upstream... that is, one which roots around in the `$prefix` tree and loads every jar in sight.  Installing an lcm-spy that has only linked in known-to-Drake types is a surprise to users.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4KGnRtPJUNFXnbvmS:b-ctntk6)*

**Comment by jamiesnape** [comment]
Which is why it is called `drake-lcm-spy`. Hardly surprising.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/libbot.BUILD, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-Kv4JNcsqRo_Hiy4fd9k:-Kv4KSUTzsxPy1zMMMNw:bnjzxzp) ([raw file](https://github.com/robotlocomotion/drake/blob/0cf145a3a830ed5771b5aefc9dc79be953abadef/tools/libbot.BUILD#L583)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI If this doesn't actually work, should we still be installing it?
</blockquote></details>

FYI It works fine for LCM t, it is just not comprehensive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4KfEcUds3jHg9IBgC:b16joup)*

**Comment by manuelli** [comment]
LGTM

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/libbot.BUILD, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-Kv4JNcsqRo_Hiy4fd9k:-Kv4LLCuQbGzVR4LavYs:b-brjctr) ([raw file](https://github.com/robotlocomotion/drake/blob/0cf145a3a830ed5771b5aefc9dc79be953abadef/tools/libbot.BUILD#L583)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI It works fine for LCM t, it is just not comprehensive.
</blockquote></details>

LCM types in libbot, so it is not broken per se. It will disappear with the rest of libbot in time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119)*

**Comment by fbudin69500** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/libbot.BUILD, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-Kv4JNcsqRo_Hiy4fd9k:-Kv4Lj6bFrjHHFIGxII-:b-7bn03) ([raw file](https://github.com/robotlocomotion/drake/blob/0cf145a3a830ed5771b5aefc9dc79be953abadef/tools/libbot.BUILD#L583)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

LCM types in libbot, so it is not broken per se. It will disappear with the rest of libbot in time. 
</blockquote></details>

Indeed, it will disappear when libbot is removed from drake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119)*

**Comment by fbudin69500** [comment]
@SeanCurtis-TRI Platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4Lsp_0N_WSG5s7q4p:b-n8me7l)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7119#-:-Kv4PuZc460VF8Mmz-2w:bmxilld)*

**Pull request merged**
