### PR TITLE
Move Variable/Variables/Environment back to symbolic namespace

### PR DESCRIPTION
**Pull request by soonho-tri**
Close https://github.com/RobotLocomotion/drake/issues/5033

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5039)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.
+@sherm1 , platform-review please.

---

Review status: 0 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5039#-:-Kc1owZ9Xn2Xso_9Zcvh:b-was2qw)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_environment.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5039#-Kc46-0wxMAHHUC5SEv5:-Kc46-0xG3KFAGRHfNnR:byt95iw) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a9dc4cf6730cf7f5238ad9a566dc3c938941fc/drake/common/symbolic_environment.h#L55)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Environment)
> 
>   typedef typename drake::symbolic::Variable key_type;
> ```

BTW, this is already inside the `drake::symbolic` namespace, so we probably can use `Variable` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5039#-:-Kc4AkSdMiShphpdLY0n:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 36 of 39 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_environment.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5039#-Kc46-0wxMAHHUC5SEv5:-Kc4Dcb2h-cCRL5POfnw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a6a9dc4cf6730cf7f5238ad9a566dc3c938941fc/drake/common/symbolic_environment.h#L55)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, this is already inside the `drake::symbolic` namespace, so we probably can use `Variable` directly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5039)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 49 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5039)*

**Comment by sherm1** [comment]
:lgtm: -- thanks, Soonho!

---

Reviewed 46 of 49 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5039#-:-Kc4nXe59ehjAJvvtHnB:b-5fqawf)*

**Pull request merged**
