### PR TITLE
[setup] Add ubuntu testonly dependency on python3-opencv

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17597.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18166)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: unless someone objects.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18166#-:-NFAIs-kAfH7kXLP9_qk:bcsqvs7)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: No objections, per Slack thread
https://drakedevelopers.slack.com/archives/C2NN588UA/p1666637022312469

> Ubuntu Focal and newer seems to offer a more modern version of OpenCV which is what we're using in Anzu for both C++ and Python.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18166#-:-NFAKJi830tu21ys31Gg:bl8b9m)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18166#-:-NFALG6P0T0KszgyVvZf:bnfp4nl)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18166)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
