### PR TITLE
Refactor wheel build script(s)

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Refactor wheel build script(s)
    
Refactor build-wheels script, moving the logic into a "package". This will ultimately simplify things if and when we want to support different (i.e. non-Docker) paradigms for building wheels, by moving key functionality into an abstracted layer that can be replaced by different logic.
    
One major change is that the build-wheels front end has been replaced by `bazel run //tools/wheel:builder`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review, please.  I'd like Kitware to do most of the work of reviewing code, so that I can conserve my own time investment.  I'll still take a quick high-level feature-review look to make sure it's pointed in the right direction.

**Comment by mwoehlke-kitware** [comment]
FYI, there's a passing wheel CI build [here](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/4/console). I'm not going to re-run it every time for changes in comments.

Also FYI, neither GitHub nor Reviewable is picking up `linux.py` as a copy/rename of the old `build-wheels` 😢. Some mechanism of comparing those would probably simplify reviewing, since most of the logic is unchanged.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM from the high level (and thus, -@jwnimmer-tri as assignee).

> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996#-:-N0C0Ox41eyN38bVuqBD:bgweaf7)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware and @svenevs)

___
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0C-Gc-AQo7dwoQB9V5:bdhauw) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
> ```
>     environment['DRAKE_WHEEL_RESOURCE_ROOT'] = script_dir
> 
>     command = ['bazel', 'run', '//tools/wheel:builder', '--']
> ```

nit For various reasons that are probably not worth typing into a long discussion here, calling `bazel run` from inside of a script is generally not ideal.

Usually, we'd want to `bazel build //...` or `bazel build //foo:stuff //bar:stuff` first, (or more conventionally, rely on data and deps in a build rule to do so), and then just directly call the program we want, without bazel in the middle of it.

Given how CI is currently configured for wheels, however, there is nowhere to put a `build //tools/wheel/...` command, so this is fine for the moment.

However, please add a reminder for me to come back and improve it later:
```py
# TODO(jwnimmer-tri) Generally we should not invoke `bazel` from within
# Drake scripts.  Rework the CI setup so that CI invokes some `bazel run`
# command directly.
```

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware and @svenevs)

___
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0C1VOP3T2LTH9vXrri:btxby6v) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For various reasons that are probably not worth typing into a long discussion here, calling `bazel run` from inside of a script is generally not ideal.

Usually, we'd want to `bazel build //...` or `bazel build //foo:stuff //bar:stuff` first, (or more conventionally, rely on data and deps in a build rule to do so), and then just directly call the program we want, without bazel in the middle of it.

Given how CI is currently configured for wheels, however, there is nowhere to put a `build //tools/wheel/...` command, so this is fine for the moment.

However, please add a reminder for me to come back and improve it later:
```py
# TODO(jwnimmer-tri) Generally we should not invoke `bazel` from within
# Drake scripts.  Rework the CI setup so that CI invokes some `bazel run`
# command directly.
```
</blockquote></details>

I'm okay with the CI scripts duplicating this. However, `bazel run` is a much more awkward invocation for someone invoking the builds manually. (There's also the matter that the builder needs to know where its resource files are located. I'm not sure how *actually* important a fully resolved path is for that, but at least the user would need to either specify that by hand or rely on `bazel run` rather than invoking the script directly.) Is it still okay to keep this script around in its current form?

My original approach did not involve Bazel at all, but apparently there is no way to have a user-run Python script that consumes other (non-system) Python modules that doesn't either a) litter the user's source tree with `__pycache__` or b) require Bazel to get involved.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware and @svenevs)

___
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0C3-SVAk1vj02oJDY7:b-dzxwff) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I'm okay with the CI scripts duplicating this. However, `bazel run` is a much more awkward invocation for someone invoking the builds manually. (There's also the matter that the builder needs to know where its resource files are located. I'm not sure how *actually* important a fully resolved path is for that, but at least the user would need to either specify that by hand or rely on `bazel run` rather than invoking the script directly.) Is it still okay to keep this script around in its current form?

My original approach did not involve Bazel at all, but apparently there is no way to have a user-run Python script that consumes other (non-system) Python modules that doesn't either a) litter the user's source tree with `__pycache__` or b) require Bazel to get involved.
</blockquote></details>

There are dozens (if not hundreds) of python helper scripts inside Drake that use `bazel run` as the entry point.  I don't see any reason yet for this one to to be any different; most developers on the project have acclimated to `bazel run`.

Can you elaborate on "much more awkward"?  I don't see it.

If your complaint is waiting for the bazel server every time, the way to avoid that is by invoking `bazel-bin/tools/wheel/build_wheel` directly instead of `bazel run //tools/wheel:build_wheel`, as long as no new library dependencies have been added since the last bazel command.  That invocation does not touch the server, but does still allow module importing to work correctly.  (It would actually be faster than the current PR, which does always force a round-trip to the bazel server.)

**Review by svenevs — COMMENTED** [review]
A few minor changes requested in addition to making it `bazel run`able.  If changes are being kept in separate commits then I think you have to rewrite both now :/

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996#-:-N0CLCSg6coo4FhiMrhx:b-w3flve)* status: 4 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware and @svenevs)

___
*[tools/wheel/wheel_builder/linux.py, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKHqhEImSPA44E8X5:-N0CKHqhEImSPA44E8X6:ba40c6i) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/linux.py#L20)):*
> ```Python
> 
> files_to_remove = []
> images_to_remove = []
> ```

Since this is a module being imported now we should prefix these mutable global variables with an `_` and possibly add a comment explaining that they should not be modified or used outside of this file.
___
*[tools/wheel/wheel_builder/linux.py, line 314 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKa6M03RVOSAkWOF9:-N0CKa6M03RVOSAkWOFA:bhvdyvy) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/linux.py#L314)):*
> ```Python
> # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> 
> atexit.register(_cleanup)
> ```

This can change to be the decorator version:

```py
@atexit.register
def _cleanup():
    # ...
```
___
*[tools/wheel/wheel_builder/main.py, line 14 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKw_J7fYoDOi5fHYD:-N0CKw_J7fYoDOi5fHYE:bof4zw0) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/main.py#L14)):*
> ```Python
> 
>     if sys.platform == 'darwin':
>         from drake.tools.wheel.wheel_builder import macos as platform
> ```

This doesn't exist yet, it should be refactored to error with an unsupported operating system and update it in a future PR to add macos back in.

**Comment by mwoehlke-kitware** [comment]
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0CULe60ErukrrFUqcJ:b13hvhf) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There are dozens (if not hundreds) of python helper scripts inside Drake that use `bazel run` as the entry point.  I don't see any reason yet for this one to to be any different; most developers on the project have acclimated to `bazel run`.

Can you elaborate on "much more awkward"?  I don't see it.

If your complaint is waiting for the bazel server every time, the way to avoid that is by invoking `bazel-bin/tools/wheel/build_wheel` directly instead of `bazel run //tools/wheel:build_wheel`, as long as no new library dependencies have been added since the last bazel command.  That invocation does not touch the server, but does still allow module importing to work correctly.  (It would actually be faster than the current PR, which does always force a round-trip to the bazel server.)
</blockquote></details>

Trying to remember that mess vs. tab completion. But, fine; *my* repo is going to keep a `build-wheels`, I just won't commit it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: 4 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware and @svenevs)

___
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0CWaCX7cLLBNzRx_WA:b-i9cxx2) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Trying to remember that mess vs. tab completion. But, fine; *my* repo is going to keep a `build-wheels`, I just won't commit it.
</blockquote></details>

Tab completion for `bazel run` should work correctly for anyone using `bash` or `zsh` (https://bazel.build/install/completion).  It works for me on Ubuntu, with bash on macOS, and with homebrew zsh.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @svenevs)

___
*[tools/wheel/build-wheels, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0C-Gbz2e99DIeSOeyd:-N0CYPGh0iBg4Xj39LH0:b-hbm20) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/build-wheels#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Tab completion for `bazel run` should work correctly for anyone using `bash` or `zsh` (https://bazel.build/install/completion).  It works for me on Ubuntu, with bash on macOS, and with homebrew zsh.
</blockquote></details>

`./b<tab>`. But see previous comment. (Now, if only bash completion for git was working on macOS :sob:.)
___
*[tools/wheel/wheel_builder/linux.py, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKHqhEImSPA44E8X5:-N0CYhfaCxXHeeQIcQQm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/linux.py#L20)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Since this is a module being imported now we should prefix these mutable global variables with an `_` and possibly add a comment explaining that they should not be modified or used outside of this file.
</blockquote></details>

Done.
___
*[tools/wheel/wheel_builder/linux.py, line 314 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKa6M03RVOSAkWOF9:-N0CY6KB3yiTpfRJsVVV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/linux.py#L314)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This can change to be the decorator version:

```py
@atexit.register
def _cleanup():
    # ...
```
</blockquote></details>

Done.
___
*[tools/wheel/wheel_builder/main.py, line 14 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0CKw_J7fYoDOi5fHYD:-N0CY9mQ6p7MwDKtRR35:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81b6340d96e8299ab920fffd3dd1f9ff69489cfd/tools/wheel/wheel_builder/main.py#L14)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

This doesn't exist yet, it should be refactored to error with an unsupported operating system and update it in a future PR to add macos back in.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @svenevs)

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by mwoehlke-kitware** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/9/ succeeded.

**Review by svenevs — COMMENTED** [review]
Changes :lgtm: +@ggould-tri for platform review please (per schedule, Monday).

+(status: do not merge) this needs to co-merge with https://github.com/RobotLocomotion/drake-ci/pull/149 (changes are interdependent since this changes the actual item run in CI).  After review is complete Matthew will remove `status: do not merge` and merge both simultaneously (it is not possible to get a status check on this PR using that build, linked job #9 for `linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release` has modified parameters to build this PR and the `drake-ci` PR).

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996#-:-N0D4vha81f0lg85Fxiu:b-ud9t6y)* status: LGTM missing from assignee ggould-tri(platform), labeled "do not merge" (waiting on @ggould-tri)

**Comment by ggould-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Comment by mwoehlke-kitware** [comment]
@ggould-tri, as noted, the CI build is expected to fail. See https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/11/ for a build using the correct drake-ci branch.

**Review by ggould-tri — COMMENTED** [review]
Oh, whoops.  Saw that just after I posted it.
Anyway :lgtm: with only a couple of notes.

> Reviewed 1 of 6 files at r1, 1 of 4 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996#-:-N0WGhTU0ycFqahdhZ45:bh3z255)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @mwoehlke-kitware)

___
*[`tools/wheel/wheel_builder/common.py` line 37 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0WDvgMEFhUkAegvbYL:-N0WDvgN8Ge9NnI4GvRy:bi6pxxl) ([raw file](https://github.com/robotlocomotion/drake/blob/d74304a9df4cc1311a21cb24f2ceb1bb9122620a/tools/wheel/wheel_builder/common.py#L37)):*
> ```Python
> 
> 
> def entry(args, platform):
> ```

`entry` is not very informative of what this function does (as hinted in the fact that it's only ever imported under a different name); since this is a function that takes actions, its name should probably be a verb phrase -- `parse_args_and_build` or similar.  Alternatively, `do_main` is used elsewhere as a name for a delegate function of a `if __name__ = '__main__'` block.
___
*[`tools/wheel/wheel_builder/linux.py` line 2 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0WGFKq1w7X_MEb14vF:-N0WGFKq1w7X_MEb14vG:blav8h0) ([raw file](https://github.com/robotlocomotion/drake/blob/d74304a9df4cc1311a21cb24f2ceb1bb9122620a/tools/wheel/wheel_builder/linux.py#L2)):*
> ```Python
> # This file contains Linux-specific logic used to build the PyPI wheels. See
> # //tools/wheel:builder for the user interface.
> ```

BTW:  I like the various small comment/docstring cleanups you've done in factoring this file; thanks :-)
___
*[`tools/wheel/wheel_builder/linux.py` line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0WFjFa-qCLM-KZAXDh:-N0WFjFa-qCLM-KZAXDi:bn2tr66) ([raw file](https://github.com/robotlocomotion/drake/blob/d74304a9df4cc1311a21cb24f2ceb1bb9122620a/tools/wheel/wheel_builder/linux.py#L43)):*
> ```Python
> }
> 
> # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
> ```

minor:  It's not clear what this separator is separating from a reader's point of view; it's not public from private, and if it's just data from functions then that's clear even without the separator.  We don't have this separator syntax elsewhere in the code; maybe just remove it?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: labeled "do not merge" (waiting on @ggould-tri and @svenevs)

___
*[tools/wheel/wheel_builder/common.py, line 37 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0WDvgMEFhUkAegvbYL:-N0XFpLrCTcQh3MANMpq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d74304a9df4cc1311a21cb24f2ceb1bb9122620a/tools/wheel/wheel_builder/common.py#L37)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

`entry` is not very informative of what this function does (as hinted in the fact that it's only ever imported under a different name); since this is a function that takes actions, its name should probably be a verb phrase -- `parse_args_and_build` or similar.  Alternatively, `do_main` is used elsewhere as a name for a delegate function of a `if __name__ = '__main__'` block.
</blockquote></details>

Done.
___
*[tools/wheel/wheel_builder/linux.py, line 43 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16996#-N0WFjFa-qCLM-KZAXDh:-N0XFrtz1E_MXSj1wq9j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d74304a9df4cc1311a21cb24f2ceb1bb9122620a/tools/wheel/wheel_builder/linux.py#L43)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It's not clear what this separator is separating from a reader's point of view; it's not public from private, and if it's just data from functions then that's clear even without the separator.  We don't have this separator syntax elsewhere in the code; maybe just remove it?
</blockquote></details>

Done.

**Comment by mwoehlke-kitware** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/12/console is probably not going to report here, but it's running. (Because of the unusual way that job is being launched, I still need to check that it's building the most recent SHA.)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: labeled "do not merge" (waiting on @mwoehlke-kitware)

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16996)* status: labeled "do not merge" (waiting on @mwoehlke-kitware)

**Pull request merged**
