### PR TITLE
Remove deprecated code (2020-10)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14128)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews, please.  Note that this won't merge until Thursday.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14128#-:-MIATVh77p5JUintEuGL:b-uwkowd)* status: labeled "do not merge"

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14128)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/math_py.cc, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14128#-MIBMyEV8PmGltjMpf6c:-MIBMyEW8C1r_FnuGO7c:b-bfjubs) ([raw file](https://github.com/robotlocomotion/drake/blob/b3e8a258082b98277424c49dc254bbd94634bb56/bindings/pydrake/math_py.cc#L276)):*
> ```cpp
>   }
> 
>   auto eigen_geometry_py = py::module::import("pydrake.common.eigen_geometry");
> ```

Per Anzu PR, I did a bad job of putting this module import in the right location.

Could you add `py::module::import("pydrake.common.eigen_geometry")` in this stanza?
https://github.com/RobotLocomotion/drake/blob/b3e8a258082b98277424c49dc254bbd94634bb56/bindings/pydrake/math_py.cc#L461-L462

Sorry about that!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14128)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/math_py.cc, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14128#-MIBMyEV8PmGltjMpf6c:-MIBR6CNA5TFT9BpXhY4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3e8a258082b98277424c49dc254bbd94634bb56/bindings/pydrake/math_py.cc#L276)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per Anzu PR, I did a bad job of putting this module import in the right location.

Could you add `py::module::import("pydrake.common.eigen_geometry")` in this stanza?
https://github.com/RobotLocomotion/drake/blob/b3e8a258082b98277424c49dc254bbd94634bb56/bindings/pydrake/math_py.cc#L461-L462

Sorry about that!
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14128)* status: labeled "do not merge"

___
*[bindings/pydrake/math_py.cc, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14128#-MIBMyEV8PmGltjMpf6c:-MIF4IY24EftsndIb_8M:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/b3e8a258082b98277424c49dc254bbd94634bb56/bindings/pydrake/math_py.cc#L276)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Pull request merged**
