### PR TITLE
Add an extremely simple LQR trajectory controller.

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3160)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@lucy-tri for feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPJZloA-m5vFpB4mU67:bsnuk82)*

**Comment by Lucy-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/controllers/LQR.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJirB6D_wii3YlE8br:-KPJirB6D_wii3YlE8bs:b-6aku14) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L20)):*
> ```objc
>           typename DerivedQ, typename DerivedR, typename DerivedK,
>           typename DerivedS>
> void CalculateLqrMatrices(
> ```

Can you document the args? (I hesitate recommend to rename them if the names will then be too long). x0 = state, u0 = input, etc. 

---

*[drake/systems/controllers/LQR.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJfRPUhNhvkO4qLRcO:-KPJfRPUhNhvkO4qLRcP:b-zcgtyc) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L49)):*
> ```objc
> std::shared_ptr<AffineSystem<NullVector, System::template StateVector,
>                              System::template InputVector>>
> MakeTimeInvariantLqrSystem(
> ```

Is "MakeXSystem" a pattern of names that we use? I don't see that.  Maybe it should just be called TimeInvariantLqrSystem.  Maybe platform reviewer will have an opinion. 

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJiX8cA87VjNm2sbMB:-KPJiX8cA87VjNm2sbMC:b-lk2cgw) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/simple_lqr_trajectory_controller.h#L13)):*
> ```objc
> 
> /**
>  * An time varying LQR controller to play back an input+state
> ```

s/An/A

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJnKrgcu34euMdZTPs:-KPJnKrhJrNTTVM-_Mex:b1ovhlu) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/simple_lqr_trajectory_controller.h#L54)):*
> ```objc
>     CalculateLqrMatrices(*sys_, x_t, u_t, Q_, R_, &K, &S);
> 
>     OutputVector<ScalarType> y = -K * toEigen(u) + u_t + K * x_t;
> ```

Where does this formula come from? Can you provide a reference in a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/LQR.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJirB6D_wii3YlE8br:-KPJtEx-3wDgh2SprMK1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L20)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Can you document the args? (I hesitate recommend to rename them if the names will then be too long). x0 = state, u0 = input, etc. 
</details>
Done.

---

*[drake/systems/controllers/LQR.h, line 49 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJfRPUhNhvkO4qLRcO:-KPJtaLYBObvrLpFQzbY:bo7kshw) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L49)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Is "MakeXSystem" a pattern of names that we use? I don't see that.  Maybe it should just be called TimeInvariantLqrSystem.  Maybe platform reviewer will have an opinion. 
</details>
I was going for the convention that function names should generally be verbs (or verb-like).  I don't think this is required by Drake's coding conventions though.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJiX8cA87VjNm2sbMB:-KPJtmQY56_Sn1U2gSeP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/simple_lqr_trajectory_controller.h#L13)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> s/An/A
</details>
Done.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 54 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJnKrgcu34euMdZTPs:-KPJtyWPMU9p-tWUDdS6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/simple_lqr_trajectory_controller.h#L54)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Where does this formula come from? Can you provide a reference in a comment?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
+@david-german-tri for platform review

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPJuQS0YIQUuZRtKI6K:b-rhk18b)*

**Comment by Lucy-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/LQR.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJirB6D_wii3YlE8br:-KPJxvpPX3eJ_y4dRWlK:b-y5i7k3) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L20)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Done.
</details>
Q,R,K,S ? Can you doc those also? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/LQR.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJirB6D_wii3YlE8br:-KPJyUWiShqPXdtVD1gt:b9zv1g2) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L20)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Q,R,K,S ? Can you doc those also? 
</details>
The underlying lqr() function is not documented, so I actually can't do this easily (it's a cut-n-paste job from my perspective, deep understanding did not occur).  I could copy the text for some of them from the MATLAB documentation at http://www.mathworks.com/help/control/ref/lqr.html -- I think the parameters are all the same (they have the same names, anyway)...  would that be helpful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by liangfok** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/LQR.h, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPK-UNhZcQEJ2lefIsE:-KPK-UNhZcQEJ2lefIsF:b-kxldku) ([raw file](https://github.com/robotlocomotion/drake/blob/b7287aa77e7063cad255a12cd8e839ed44da1ba8/drake/systems/controllers/LQR.h#L15)):*
> ```objc
> using drake::math::autoDiffToGradientMatrix;
> 
> namespace drake {
> ```

BTW should this and the other files in this directory be in namespace `drake::systems::controllers`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/controllers/LQR.h, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPK-UNhZcQEJ2lefIsE:-KPK-sb8wj61vo1RFzcs:br35qj4) ([raw file](https://github.com/robotlocomotion/drake/blob/b7287aa77e7063cad255a12cd8e839ed44da1ba8/drake/systems/controllers/LQR.h#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW should this and the other files in this directory be in namespace `drake::systems::controllers`?
</details>
Probably?  There doesn't seem to be a clear convention for namespaces in drake/systems yet, so I've been trying to follow anything which looks like convention in whatever subdirectory I'm working in.  It's annoying, but I've generally been against having a "last one in cleans up the mess" approach to stuff like this...  particularly without a written convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/LQR.h, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPK-UNhZcQEJ2lefIsE:-KPK1O2yAdgz6DDXSjCU:bl00cea) ([raw file](https://github.com/robotlocomotion/drake/blob/b7287aa77e7063cad255a12cd8e839ed44da1ba8/drake/systems/controllers/LQR.h#L15)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Probably?  There doesn't seem to be a clear convention for namespaces in drake/systems yet, so I've been trying to follow anything which looks like convention in whatever subdirectory I'm working in.  It's annoying, but I've generally been against having a "last one in cleans up the mess" approach to stuff like this...  particularly without a written convention.
</details>
OK SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/LQR.h, line 20 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPJirB6D_wii3YlE8br:-KPK0BXK0kH2jFLPwH-L:bqei2c1) ([raw file](https://github.com/robotlocomotion/drake/blob/b08bcb02bf11bc83eb6e7bd8f8da90a607680fbe/drake/systems/controllers/LQR.h#L20)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> The underlying lqr() function is not documented, so I actually can't do this easily (it's a cut-n-paste job from my perspective, deep understanding did not occur).  I could copy the text for some of them from the MATLAB documentation at http://www.mathworks.com/help/control/ref/lqr.html -- I think the parameters are all the same (they have the same names, anyway)...  would that be helpful?
</details>
If you don't know how to doc them, then ok to leave without doc now.  I'm reading that and I still don't know exactly how to describe K, for example. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPKBrZa5wA6YPzy-Cc6:bnfp4nl)*

**Comment by Lucy-tri** [comment]
I'd be interested to see what @russtedrake thinks of this. @sammy-tri  built it as a quick idea to see if it could be done, and it seems to work. Is there something wrong with this approach as a solution? Is it not efficient?  Sam did that after I wrote my email to you, Russ.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPKI02Zst2xQFEgejpZ:bx1twn4)*

**Comment by david-german-tri** [comment]
Reviewed 4 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPO3O_7m4MWt4cP-1U9:b-zcnk8r) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
> ```objc
>  */
> template <typename System>
> class SimpleLqrTrajectoryController {
> ```

This seems like substantive new code.  Does it have test coverage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPO3yRerQjdR3_7WNcx:b-4e6o0x) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This seems like substantive new code.  Does it have test coverage?
</details>
No.  The code it was built out of did not have test coverage either.

I'd also argue it's not really new code.  It's System1 boiler plate where only the output() function does anything, and it only makes the one function call into old code in CalculateLqrMatrices() (the formula for calculating the output vector is also taken from existing code, it's a distilled version of AffineSystem's output function using the parameters from MakeTimeInvariantLqrSystem()).

I looked into adding a unit test for a bit.  I'd want to move RobotStateTap out of the kuka_iiwa_arm directory into some more general place and tie into the Pendulum example to verify that the trajectory is roughly followed and that the final balance is achieved.  I can go ahead and do so if you want.  Suggestion on where to move RobotStateTap to would be strongly appreciated, otherwise I'm dumping it in systems/plants because it's already a dumping ground.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPO7RkUWRC3LzPXxX0r:bl82323) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> No.  The code it was built out of did not have test coverage either.
> 
> I'd also argue it's not really new code.  It's System1 boiler plate where only the output() function does anything, and it only makes the one function call into old code in CalculateLqrMatrices() (the formula for calculating the output vector is also taken from existing code, it's a distilled version of AffineSystem's output function using the parameters from MakeTimeInvariantLqrSystem()).
> 
> I looked into adding a unit test for a bit.  I'd want to move RobotStateTap out of the kuka_iiwa_arm directory into some more general place and tie into the Pendulum example to verify that the trajectory is roughly followed and that the final balance is achieved.  I can go ahead and do so if you want.  Suggestion on where to move RobotStateTap to would be strongly appreciated, otherwise I'm dumping it in systems/plants because it's already a dumping ground.
</details>
Sorry to be a pain, but yes, I think that's worthwhile.  `systems/plants` is fine.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPOPwAZsu6mM917lXbp:b-hrr5uy) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Sorry to be a pain, but yes, I think that's worthwhile.  `systems/plants` is fine.  
</details>
Ahh, the old "you touched it now you own it" model.  I'll put something together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by sammy-tri** [comment]
Review status: 5 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPOirRbihq048fxJCst:b2mbjk0) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Ahh, the old "you touched it now you own it" model.  I'll put something together.
</details>
Done.  It has increased the size of the PR a bit...  The relevant change is that pendulum_run_swing_up is now run as a test which will fail if SimpleLqrTrajectoryController does not achieve and hold the target position.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by david-german-tri** [comment]
Review status: 5 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPOlc0fwuD90CW0pd_O:b-vaqy2q) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Done.  It has increased the size of the PR a bit...  The relevant change is that pendulum_run_swing_up is now run as a test which will fail if SimpleLqrTrajectoryController does not achieve and hold the target position.
</details>
Did you `git add` the test file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPOnViK4Kt-ItRtn59u:bxfj8ge) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
> pendulum_run_swing_up is now run as a test
And the test is run because of a change to CMakeLists. Looks good to me. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPOnlCIpS-OAg3LVO1M:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/controllers/simple_lqr_trajectory_controller.h, line 19 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-KPO3O_7m4MWt4cP-1U8:-KPOo9n79rgENPzJj1ar:btee7cl) ([raw file](https://github.com/robotlocomotion/drake/blob/f40e6c52fdd18ab2fba9813cd25492cdbb6d0460/drake/systems/controllers/simple_lqr_trajectory_controller.h#L19)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > pendulum_run_swing_up is now run as a test
> And the test is run because of a change to CMakeLists. Looks good to me. 
</details>
I added an add_test() line in examples/Pendulum/CMakeLists.txt (like the other example programs there already had) and a check to the end of pendulum_run_swing_up.cc to fail if the target is not reached.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160)*

**Comment by david-german-tri** [comment]
:lgtm: thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3160#-:-KPP67uRaVGoNxCMQ84k:brfqlux)*

**Pull request merged**
