### PR TITLE
Fix bug in meshcat contact force visualization.

### PR DESCRIPTION
**Pull request by pangtao22**
The current implementation only rotates the force cylinder by up to pi/2, which leads to wrong contact force directions when the rotation needed is more than pi/2. The fix allows rotation up to pi.

@EricCousineau-TRI could you assign a reviewer for this PR? Thanks! 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 616 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15677#-Mi8IeQ052h1kKGhlyWp:-MiRCW_D1a4Gt6HkNGv8:bdxaz84) ([raw file](https://github.com/robotlocomotion/drake/blob/4e60e82069368cbdfa85059756ce88e0d1fe74b9/bindings/pydrake/systems/meshcat_visualizer.py#L616)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I agree it's worth the effort. It's a high utility method, rigorously tested to handle all of the ugly corner cases. It would greatly simplify all of this code.
</blockquote></details>

@pangtao22 would you like a hand switching it to the alternate API?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 616 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15677#-Mi8IeQ052h1kKGhlyWp:-MiajKh_9wbem4WXBFbh:b-dgvh7j) ([raw file](https://github.com/robotlocomotion/drake/blob/4e60e82069368cbdfa85059756ce88e0d1fe74b9/bindings/pydrake/systems/meshcat_visualizer.py#L616)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@pangtao22 would you like a hand switching it to the alternate API?
</blockquote></details>

I've gone ahead and made the change. @ericcousineau-tri PTAL.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

___
*[bindings/pydrake/systems/meshcat_visualizer.py, line 616 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15677#-Mi8IeQ052h1kKGhlyWp:-MibPIT63xlWciHXpWSB:b9bkkp1) ([raw file](https://github.com/robotlocomotion/drake/blob/4e60e82069368cbdfa85059756ce88e0d1fe74b9/bindings/pydrake/systems/meshcat_visualizer.py#L616)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've gone ahead and made the change. @ericcousineau-tri PTAL.
</blockquote></details>

Looks great!

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677#-:-Mibdyxu2OfAnGRjfbTl:bmxilld)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @pangtao22)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677#-:-Mibe3_jDH-TlhQyfOkM:bm9o57a)* status: needs at least two assigned reviewers (waiting on @pangtao22)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@ericcousineau-tri (officially assigning so reviewable is happy).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15677#-:-MibeAOFBFpyl6ISC3z2:b-hb0lup)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @pangtao22)

**Pull request merged**
