### PR TITLE
Return the new cost and slack variables from AddMaximizeLogDeterminantSymmetricMatrixCost

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296#-:-Ms_omNr5-pK3EX1WRMZ:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1206 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaG-tACYooKivl2CzJ:-MsaG-tACYooKivl2CzK:b229cxa) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/mathematical_program.h#L1206)):*
> ```objc
>    * log(Z(i, i)) >= t(i)
>    * and we will minimize -∑ᵢt(i).
>    * @param X A symmetric positive semidefinite matrix X, whose log(det(X)) will
> ```

nit The "be maximized" text that ends the sentence got severed here.
___
*[solvers/mathematical_program.cc, line 562 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaGucA1_cCZj1nUc3M:-MsaGucA1_cCZj1nUc3N:b-lzwfok) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/mathematical_program.cc#L562)):*
> ```cpp
> 
>   const auto cost = AddLinearCost(-Eigen::VectorXd::Ones(t.rows()), t);
>   return std::make_tuple(cost, t, Z_var);
> ```

nit If I'm reading correctly, I think that `t` and `Z_var` should be moved-from here, instead of copied?
___
*[solvers/test/exponential_cone_program_examples.cc, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaI3gC0GNxrPHUqT6j:-MsaI3gC0GNxrPHUqT6k:b-8gkcug) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L98)):*
> ```cpp
>       b.cast<symbolic::Expression>().transpose() / 2, c;
>   prog.AddPositiveSemidefiniteConstraint(ellipsoid_psd);
>   const auto log_det_ret = prog.AddMaximizeLogDeterminantSymmetricMatrixCost(
> ```

Missing unit test coverage for the contents of `Z`.
___
*[solvers/test/exponential_cone_program_examples.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaHoTA82YjAwKRSmro:-MsaHoTA82YjAwKRSmrp:bfgp73b) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L126)):*
> ```cpp
>   EXPECT_NEAR(result.get_optimal_cost(), expected_cost, tol);
>   EXPECT_NEAR(result.EvalBinding(std::get<0>(log_det_ret))(0), expected_cost,
>               tol);
> ```

The `<0>` template mumble here is non-obvious.  Back up on L98 at the call site, you should use structured bindings to store the resulting tuple into three different named locals, without any use of tuples in the unit test.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.cc, line 562 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaGucA1_cCZj1nUc3M:-MsaUQ7VC5sWMSkX7Pl3:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/mathematical_program.cc#L562)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If I'm reading correctly, I think that `t` and `Z_var` should be moved-from here, instead of copied?
</blockquote></details>

Done. Good call.
___
*[solvers/test/exponential_cone_program_examples.cc, line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaI3gC0GNxrPHUqT6j:-Msab_7_3UV_9H-AN2nz:b-h1fv6a) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L98)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing unit test coverage for the contents of `Z`.
</blockquote></details>

Done. Good call. The added test helps to find a bug.
___
*[solvers/test/exponential_cone_program_examples.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaHoTA82YjAwKRSmro:-MsabdRW9_CvRXz8PMNF:b7k5ksy) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `<0>` template mumble here is non-obvious.  Back up on L98 at the call site, you should use structured bindings to store the resulting tuple into three different named locals, without any use of tuples in the unit test.
</blockquote></details>

I tried to do something like this
```cc
Binding<LinearCost> cost;
VectorX<symbolic::Variable> t;
MatrixX<symbolic::Variable> Z;
std::tie(cost, t, Z) = prog.AddMaximizeLogDeterminantSymmetricMatrixCost();
```
but the compilation fails because `Binding<LinearCost>` doesn't have a default constructor. 

So I still use the struct as the return, but add named variable for each entry in the tuple.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsagywKB1awTpVATUiI:bjhodpv) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
> ```objc
>    * be maximized.
>    * @return (cost, t, Z) cost is -∑ᵢt(i), we also return the newly created
>    * slack variables t and Z.
> ```

The cost uses a triangular Z with the upper part as _zero_.

However, as of r2 the `Z` variables are returned as a _symmetric_ matrix (no zeros), whereas in r1 the upper part was undefined (rather than symmetric).  I liked r1 better, but in any case you should choose one and then document in the API here which one it is.
___
*[solvers/mathematical_program.cc, line 548 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaezSA0zngMIDWdMEU:-MsaezSB3FNTLXbS8drX:brmti5g) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.cc#L548)):*
> ```cpp
>     }
>     diag_Z(j, j) = Z(j, j);
>   }
> ```

nit I almost remarked the first time, but with the new code it's more acute.  This loop is quite difficult to follow.  Pulling out the Z_lower iteration step into its own dedicated line would be a big improvement:

```c++
  int Z_lower_index = 0;
  for (int j = 0; j < X_rows; ++j) {
    for (int i = j; i < X_rows; ++i) {
      const Variable z = Z_lower(Z_lower_index++);
      Z(i, j) = z;
      Z_var(i, j) = z;
      if (i != j) {
        Z_var(j, i) = z;
      }
    }
    diag_Z(j, j) = Z(j, j);
  }
```
___
*[solvers/test/exponential_cone_program_examples.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaHoTA82YjAwKRSmro:-MsadED04ygirVMjjvW2:b-a1x58t) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L126)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I tried to do something like this
```cc
Binding<LinearCost> cost;
VectorX<symbolic::Variable> t;
MatrixX<symbolic::Variable> Z;
std::tie(cost, t, Z) = prog.AddMaximizeLogDeterminantSymmetricMatrixCost();
```
but the compilation fails because `Binding<LinearCost>` doesn't have a default constructor. 

So I still use the struct as the return, but add named variable for each entry in the tuple.
</blockquote></details>

See https://drake.mit.edu/styleguide/cppguide.html#Type_deduction at "structured bindings".

Something like:
```c++
const auto [linear_cost, det_log_t, det_log_z] = prog.Add...(...);
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsbB9GrDtwZLhIIOXN1:b-lovwas) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The cost uses a triangular Z with the upper part as _zero_.

However, as of r2 the `Z` variables are returned as a _symmetric_ matrix (no zeros), whereas in r1 the upper part was undefined (rather than symmetric).  I liked r1 better, but in any case you should choose one and then document in the API here which one it is.
</blockquote></details>

Good call, I switched it back to lower diagonal matrix.
___
*[solvers/mathematical_program.cc, line 548 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaezSA0zngMIDWdMEU:-MsbCAmX6ttBbew7gQH9:b-qku2c3) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.cc#L548)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I almost remarked the first time, but with the new code it's more acute.  This loop is quite difficult to follow.  Pulling out the Z_lower iteration step into its own dedicated line would be a big improvement:

```c++
  int Z_lower_index = 0;
  for (int j = 0; j < X_rows; ++j) {
    for (int i = j; i < X_rows; ++i) {
      const Variable z = Z_lower(Z_lower_index++);
      Z(i, j) = z;
      Z_var(i, j) = z;
      if (i != j) {
        Z_var(j, i) = z;
      }
    }
    diag_Z(j, j) = Z(j, j);
  }
```

</blockquote></details>

I removed Z_var and switched back to r0. Do you think it is good now?
___
*[solvers/test/exponential_cone_program_examples.cc, line 126 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaHoTA82YjAwKRSmro:-MsbCMoV5COHH3spVD52:b-beqqn9) ([raw file](https://github.com/robotlocomotion/drake/blob/b27eca15971fb569a48d4224e14d3ac5f336a824/solvers/test/exponential_cone_program_examples.cc#L126)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

See https://drake.mit.edu/styleguide/cppguide.html#Type_deduction at "structured bindings".

Something like:
```c++
const auto [linear_cost, det_log_t, det_log_z] = prog.Add...(...);
```
</blockquote></details>

I see, thanks a lot!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature, modulo the pydrake CI fix.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296#-:-MsbH_UZE4zfZKxW2IAg:bkpiom1)* status: needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsbH2GA40ohqczS0BNV:bd2iles) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call, I switched it back to lower diagonal matrix.
</blockquote></details>

OK I was initially unhappy with switching the return type of Z to use `Expression` to denote "a Variable, or zero" in the returned Z, but after reading the unit test I think it's fine, actually.

It would be nice to overload `MathematicalProgramResult::GetSolution()` to take `Matrix<Expression>` at some future point to reduce boilerplate, but this is fine as-is.
___
*[solvers/mathematical_program.cc, line 548 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsaezSA0zngMIDWdMEU:-MsbFkUe2v8aCfOU_Tvo:b-s8bddm) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.cc#L548)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I removed Z_var and switched back to r0. Do you think it is good now?
</blockquote></details>

Ya, I think the loop is clear enough now.

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296#-:-MsbJ-BA9CWnQuCYUoYW:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsbIeA82xUgD8wPEYKa:b-d0vwyu) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK I was initially unhappy with switching the return type of Z to use `Expression` to denote "a Variable, or zero" in the returned Z, but after reading the unit test I think it's fine, actually.

It would be nice to overload `MathematicalProgramResult::GetSolution()` to take `Matrix<Expression>` at some future point to reduce boilerplate, but this is fine as-is.
</blockquote></details>

We actually have `MathematicalProgramResult::GetSolution(Matrix<Expression>)`, it also returns a Matrix<Expression>, so I will need to convert each entry of symbolic::Expression to double value anyway.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsbJFyf3g6UPJIfWF1d:b867b3s) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We actually have `MathematicalProgramResult::GetSolution(Matrix<Expression>)`, it also returns a Matrix<Expression>, so I will need to convert each entry of symbolic::Expression to double value anyway.
</blockquote></details>

Oh indeed, I didn't scroll long enough.  

Given that, an`ExtractDoubleOrThrow(result.GetSolution(Z))` would avoid the loop.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: LGTM missing from assignee sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[solvers/mathematical_program.h, line 1209 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16296#-MsagywKB1awTpVATUiH:-MsbULinAZHv15rJuYlp:bhqndq8) ([raw file](https://github.com/robotlocomotion/drake/blob/25a4aa677cbd30d639c1c99acd60f185ce8ce65c/solvers/mathematical_program.h#L1209)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oh indeed, I didn't scroll long enough.  

Given that, an`ExtractDoubleOrThrow(result.GetSolution(Z))` would avoid the loop.
</blockquote></details>

Cool, I didn't realize that ExtractDoubleOrThrow works for symbolic expression. Thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one BTW request.

> Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296#-:-MsbnE5eDduLAaEMpvSA:bu09k02)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[solvers/mathematical_program.h, line 1209 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16296#-Msblp4fA7nooWm3yAGx:-Msblp4gAbFWjZctiPKa:b-3vj8l8) ([raw file](https://github.com/robotlocomotion/drake/blob/475dcfa0d9c97e289d6d1f86168dbeb4f1883814/solvers/mathematical_program.h#L1209)):*
> ```objc
>    * be maximized.
>    * @return (cost, t, Z) cost is -∑ᵢt(i), we also return the newly created
>    * slack variables t and Z.
> ```

BTW seeing this description I expected t and Z to be the same type, specifically "variables". Below I see that one is a Variable and the other an Expression. From the previous discussion it appears that there is a good reason for that. But please consider explaining that reason in the comment here or as a note.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16296)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @hongkai-dai)

**Pull request merged**
