### PR TITLE
Build nlopt with cmake

### LINKED ISSUE #3503: Use nlopt CMake build instead of autotools

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #3503.

The commit SHA needed to be updated to get all the necessary CMake configuration files.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3564)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3564)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3564#-:-KSN1n_qVJ41fUhASRJt:bnfp4nl)*

**Pull request merged**
