### PR TITLE
Fix pybind11+NumPy

### LINKED ISSUE #5177: If NumPy is missing, the Drake build should fail hard when generating py bindings
Right now, both pre and post #5158, the bindings are silently disabled in the CMake build.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update pybind11 to version that understands NumPy as a component. Modify our search for pybind11 to require NumPy.

This will produce a hard error if we're expecting pybind11 to be used, but NumPy cannot be found. (Previously, this would cause the Python bindings to be silently disabled.)

Fixes #5177.

@jamiesnape for feature review, but FYI @rdeits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5178)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5178#-:-Kd1rKt5oxfUlBiWEiEV:bnfp4nl)*

**Comment by rdeits** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5178#-:-Kd1s2_-R_vOdmaUd8mU:bnfp4nl)*

**Comment by rdeits** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5178#-:-Kd1uEMddHYZyUTWJYZh:bnfp4nl)*

**Pull request merged**
