### PR TITLE
Add SystemScalarConverter::Remove()

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Support prohibiting scalar conversion to and from a particular scalar type at run time.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159#-:-Mbm-tPG1jQHXSgFvCAD:blt7ijb)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm7ANH3T-ebO_uQ7ws:-MbmCxf79emKhRfJE0M9:b40n0vv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The most important change here is actually making the mutable converter protected; the Remove is just sugar.  As such, the commit message should at least mention the new protected method (so it makes it into the release notes).
</blockquote></details>

I reworded the commit message. PTAL, thanks.

---
___
*[systems/framework/system.h, line 1677 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm4KD_3cdDvCpKFfaj:-Mbm9vRuAEcT2G0TR5XN:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/48cf345582122358d0e682d20457dfd2b2c9997d/systems/framework/system.h#L1677)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Now that this is available to users (being protected), it needs a (short) Doxygen API comment.
</blockquote></details>

Done, thanks.
___
*[systems/framework/system_scalar_converter.h, line 139 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm3QOX-csBoEe7EcXg:-MbmA2VPC75W3A2KbS6-:b-6igfg0) ([raw file](https://github.com/robotlocomotion/drake/blob/48cf345582122358d0e682d20457dfd2b2c9997d/systems/framework/system_scalar_converter.h#L139)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not 100% sure on the grammar here, but it seems to me like we want "or" here, not "and"?
</blockquote></details>

I'm not sure either. Done, thanks.
___
*[systems/framework/system_scalar_converter.h, line 206 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm2hv03NKmPQ3Q2Zo1:-MbmCdnEB3Xg-zf-rq8X:b-x4udh5) ([raw file](https://github.com/robotlocomotion/drake/blob/48cf345582122358d0e682d20457dfd2b2c9997d/systems/framework/system_scalar_converter.h#L206)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions

The only code we need in the header is `typeid(T)`; the loop can live in the cc file (under a private helper method that takes `const std::type_info&`).

If you like, since `Remove()` body will be a 1-liner in that case, you'd be welcome to define it inline within the class, instead of separately here.  Either way is fine.
</blockquote></details>

Done, PTAL, thanks.
___
*[systems/framework/test/system_scalar_converter_test.cc, line 333 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm5w_XAdWt60HdQ8th:-MbmCv_q70DnIQ1A3Txl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/48cf345582122358d0e682d20457dfd2b2c9997d/systems/framework/test/system_scalar_converter_test.cc#L333)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Please keep the blank line here before close-namespace, to match open-namespace above.
</blockquote></details>

Done.
___
*[multibody/plant/multibody_plant.h, line 1588 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15159#-Mbm4dW47oz8Tkd83q1-:-Mbm9ClO15NNuGcbBlhi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/48cf345582122358d0e682d20457dfd2b2c9997d/multibody/plant/multibody_plant.h#L1588)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think that any plant diffs should be in this PR?  We just want to add a new framework feature with unit tests.  A mention of the other PR would be sufficient to demonstrate the utility.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@soonho-tri for platform review per schedule, please.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159#-:-MbmEjGl81xMWwTCsjDl:by9x1z2)* status: 1 unresolved discussion, LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri and @xuchenhan-tri)

___
*[systems/framework/system_scalar_converter.cc, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15159#-MbmEXxt9LZj_UAWsYGi:-MbmEXxu0YMckuiFmWcZ:b-cz0xxg) ([raw file](https://github.com/robotlocomotion/drake/blob/eea33552472bdb78e5c9bed3d07e5538d5e45a5b/systems/framework/system_scalar_converter.cc#L36)):*
> ```cpp
> void SystemScalarConverter::Remove(const std::type_info& t_info) {
>   // Remove the items from `funcs_` whose key contains the type `T` that
>   // mataches `t_info`. (This would use erase_if, if we had it.)
> ```

nit Typo `mataches`

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159#-:-MbmMPpj0vA42w7uYtrl:bnfp4nl)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[systems/framework/system_scalar_converter.cc, line 36 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15159#-MbmLshF57Pdq6itU-JV:-MbmLshF57Pdq6itU-JW:b-wozbca) ([raw file](https://github.com/robotlocomotion/drake/blob/eea33552472bdb78e5c9bed3d07e5538d5e45a5b/systems/framework/system_scalar_converter.cc#L36)):*
> This would use erase_if, if we had it.

C++20!

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15159)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
