### PR TITLE
Introducing a translator API for Lcm <=> arbitrary data types, and System blocks. 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This pr contains 2 main parts:
1. translator API for Data <=> Msg.
2. system wrappers for both directions of translation.

1 is straight forward. 
The system wrappers always have 1 input port and output port, the port that corresponds to Msg is always abstract valued, the port that corresponds to Data can be either abstract or vector based depending on Data is derived from VectorBase or not. 

There is also an example of "abusing" this for more general purpose translation between BasicVector and some arbitrary data type (StateVectorAndHumanoidStatusTranslator).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6192)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for feature review. thanks! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-Kl5OsGUV1g0gaBijxNr:b-p3ab8)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQjyKA0qBBcitSf1_B:-KlQjyKBplyvwuGfk1-v:bwuq37x) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc#L39)):*
> ```cpp
> 
>   // TODO(siyuan): move this to translator.
>   const Vector6<double>& l_foot = data.foot_wrench_raw(Side::LEFT);
> ```

nit This is not part of this PR, but would it be possible to change `LEFT` to `kLeft` (same for `RIGHT`?

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQMTzMBX15E_Bx1LJv:-KlQMTzNTG5EUiLHuagn:bnf6g2a) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L18)):*
> ```objc
>  * A Translator between raw state vector (systems::BasicVector<double>) and
>  * HumanoidStatus. Note that since the raw state does not contain any time
>  * information, I picked the DataType to be systems::BasicVector<double>, and
> ```

nit Could you either change this to be second person, or add your name in?

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQN0HtKvbDGxHLY5ad:-KlQN0Hv26FgmKHuL8lP:b-tvw3o9) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L116)):*
> ```objc
> 
>  private:
>   const manipulation::RobotStateLcmMessageTranslator translator_;
> ```

nit Could this be renamed to `robot_state_translator_`, to make it slightly clearer that this is composition?

---

*[drake/lcm/translator_base.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQhe7IuU_CcCzFguUX:-KlQhe7JMBmSTo5NQDoV:bgc9wql) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L15)):*
> ```objc
>  * representations (DataType). Meanwhile, a well defined Lcm message (MsgType)
>  * almost always contains an time stamp. Thus, during message encoding
>  * (DataType -> MsgType), we provide an additional time information (often
> ```

Grammar, "~an~ additional time"

---

*[drake/lcm/translator_base.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQhWf094vc5XmdqQ4d:-KlQhWf1Qn_4cgUHDaOc:boo7mgd) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L17)):*
> ```objc
>  * (DataType -> MsgType), we provide an additional time information (often
>  * extracted from some Context). During decoding (MsgType -> DataType), the
>  * message's time stamp can be extracted and stored separated. This introduces
> ```

Grammar `s/separated/separately/`

---

*[drake/lcm/translator_base.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQkNZ3QYzkNHn6samA:-KlQkNZ4mhLszvJyp0C5:bryg04z) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L21)):*
> ```objc
>  * <pre>
>  *   (DataType, time) -> MsgType,
>  *   MsgType -> (DataType, time)
> ```

Would it be possible to try and delegate assigning / extracting time to another optional method that can be overridden, like `EncodeTimestamp` / `DecodeTimestamp, that takes the time (and possibly something else like a sequence counter)?

I am thinking specifically of a case when you would want to have composition of different translators, like what you have above for `HumanoidStatusTraslator`, but explicitly calling `Encode`/ `Decode` on each item. It seems like you would encounter a lot of `throw_away_time` situations like you have below.

---

*[drake/systems/lcm/translator_system.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQNvVRq_NmrKJDkk-F:-KlQNvVTMpitxxm0jKUv:b-3yqf3l) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/translator_system.h#L95)):*
> ```objc
>   template <typename DataType1 = DataType,
>             typename = typename std::enable_if<std::is_base_of<
>                 systems::VectorBase<double>, DataType1>::value>::type>
> ```

Could this be placed as something like `static constexpr bool kIsVectorBase  = std::is_base_of<...>`, and then change the `enable_if` to `enable_if<kIsVectorBase, ...>`?

Additionally, it looks like you could consolidate some of `get_default_data`in your traits, and possibly avoid the `enable_if` in general.

Here's a toy example version of these suggestions:
https://github.com/EricCousineau-TRI/repro/blob/5c26e1f/cpp_quick/tpl_spec_switch.h
(You can run this via in the repo via `bazel run //cpp_quick:tpl_spec_switch_main`.)

I believe you could use these to get rid of the `std::enable_if`, and rather do something like `DataTypeTraits::Init(this, translator_)` or whatever inside the constructors.

---

*[drake/systems/lcm/translator_system.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQi-sErlr4WVnR5v_f:-KlQi-sFQp7aolUaQ55V:b-ihlxd8) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/translator_system.h#L160)):*
> ```objc
>    * corresponding default values.
>    *
>    * @param translator Translator, whose ownership is transferred to this.
> ```

nit Grammar `s/transferred to this/transferred to this instance/`.

---

*[drake/systems/lcm/test/translator_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQh6agjHv2S2KaQAKe:-KlQh6agjHv2S2KaQAKf:b-s2ucb6) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L20)):*
> ```cpp
>   }
> 
>   std::vector<std::string> names;
> ```

nit Could you use `using std::vector`, `using std::string`, etc.?

---

*[drake/systems/lcm/test/translator_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQgwbUhUL3xy5KXkFG:-KlQgwbVwI2BJuU06I6H:btbxa78) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L21)):*
> ```cpp
> 
>   std::vector<std::string> names;
>   std::vector<double> vector;
> ```

nit Is there an alternative name, such as `vector_data`, to avoid ambiguity if you include `using` statements?

---

*[drake/systems/lcm/test/translator_test.cc, line 275 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQid8Dgp6MSOxqawba:-KlQid8EDJslN1VSA6BB:b-x37m4o) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L275)):*
> ```cpp
>   }
> }
> ```

Would it be possible to add a test for composite types?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192)*

**Comment by EricCousineau-TRI** [comment]
Sorry for the late follow-up, but I've added in some initial design comments, PTAL whenever you have a chance.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-KlQmsyV9r1rPyw58EWt:b-qj01z1)*

**Comment by EricCousineau-TRI** [comment]
*[drake/systems/lcm/translator_system.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQNvVRq_NmrKJDkk-F:-KlQqh7zGh9TTM5qel2b:b-uvlvs6) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/translator_system.h#L95)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could this be placed as something like `static constexpr bool kIsVectorBase  = std::is_base_of<...>`, and then change the `enable_if` to `enable_if<kIsVectorBase, ...>`?

Additionally, it looks like you could consolidate some of `get_default_data`in your traits, and possibly avoid the `enable_if` in general.

Here's a toy example version of these suggestions:
https://github.com/EricCousineau-TRI/repro/blob/5c26e1f/cpp_quick/tpl_spec_switch.h
(You can run this via in the repo via `bazel run //cpp_quick:tpl_spec_switch_main`.)

I believe you could use these to get rid of the `std::enable_if`, and rather do something like `DataTypeTraits::Init(this, translator_)` or whatever inside the constructors.
</blockquote></details>

I've made a slightly cleaner version (no need to use `friend`, and keeps it all within the same base class):
https://github.com/EricCousineau-TRI/repro/blob/476b36c/cpp_quick/tpl_spec_switch.h

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192)*

**Comment by siyuanfeng-tri** [comment]
@ericcousineau-tri I intend to keep the enable_if stuff as is.. 

---

Review status: 6 of 16 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQjyKA0qBBcitSf1_B:-Kmi-TDppFUlDGcFUolo:bus2v9y) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.cc#L39)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit This is not part of this PR, but would it be possible to change `LEFT` to `kLeft` (same for `RIGHT`?
</blockquote></details>

i am going to ignore this for now. 

---

*[drake/lcm/translator_base.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQhe7IuU_CcCzFguUX:-Kmi1GSg7yZvklyy8olg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L15)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Grammar, "~an~ additional time"
</blockquote></details>

Done.

---

*[drake/lcm/translator_base.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQhWf094vc5XmdqQ4d:-Kmi1Giku3ApHRbZnWll:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L17)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Grammar `s/separated/separately/`
</blockquote></details>

Done.

---

*[drake/lcm/translator_base.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQkNZ3QYzkNHn6samA:-Kmi1J3YGE0J9t2AUBIm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/lcm/translator_base.h#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be possible to try and delegate assigning / extracting time to another optional method that can be overridden, like `EncodeTimestamp` / `DecodeTimestamp, that takes the time (and possibly something else like a sequence counter)?

I am thinking specifically of a case when you would want to have composition of different translators, like what you have above for `HumanoidStatusTraslator`, but explicitly calling `Encode`/ `Decode` on each item. It seems like you would encounter a lot of `throw_away_time` situations like you have below.
</blockquote></details>

Done.

---

*[drake/systems/lcm/translator_system.h, line 160 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQi-sErlr4WVnR5v_f:-Kmi1YfDlLklbHF3mSY_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/translator_system.h#L160)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Grammar `s/transferred to this/transferred to this instance/`.
</blockquote></details>

Done.

---

*[drake/systems/lcm/test/translator_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQh6agjHv2S2KaQAKe:-Kmi1gQxa5FYR61QAHqR:b-8gi61u) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Could you use `using std::vector`, `using std::string`, etc.?
</blockquote></details>

i actually like having std there. 

---

*[drake/systems/lcm/test/translator_test.cc, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQgwbUhUL3xy5KXkFG:-Kmi1ly3qz4DTfKI66gC:bjla91) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L21)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Is there an alternative name, such as `vector_data`, to avoid ambiguity if you include `using` statements?
</blockquote></details>

i am going to leave it as is. 

---

*[drake/systems/lcm/test/translator_test.cc, line 275 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQid8Dgp6MSOxqawba:-Kmi5yhHIp41vH38cXS9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/test/translator_test.cc#L275)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Would it be possible to add a test for composite types?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-Kmi6APp8xWOEIbMi5nz:buf8qoz)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, pending minor comments.

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQMTzMBX15E_Bx1LJv:-Kmj4lUcEwOWqEBdmeZc:b-knfcwy) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L18)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Could you either change this to be second person, or add your name in?
</blockquote></details>

BTW Ignoring given authorship of the file. Would still be nice to include authorship, but not worth blocking the PR.

---

*[drake/systems/lcm/translator_system.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQNvVRq_NmrKJDkk-F:-Kmj58wpwKslT-5N_9ti:b-pxb82s) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/systems/lcm/translator_system.h#L95)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I've made a slightly cleaner version (no need to use `friend`, and keeps it all within the same base class):
https://github.com/EricCousineau-TRI/repro/blob/476b36c/cpp_quick/tpl_spec_switch.h
</blockquote></details>

BTW Nuking this comment per f2f discussion.

---

*[drake/systems/lcm/test/translator_test.cc, line 350 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-Kmj5gd8wLkUxqEgsnnT:-Kmj5gd9d7ySaiXZbWvH:b-40znkq) ([raw file](https://github.com/robotlocomotion/drake/blob/cf3d3c8dd325441d664524eb1b48744d66c1ea24/drake/systems/lcm/test/translator_test.cc#L350)):*
> ```cpp
>               Quaternion<T>* data) const override {
>     *data = Quaternion<T>(msg.w, msg.x, msg.y, msg.z);
>     data->normalize();
> ```

BTW I'm a little sketched out by doing extra operations / extending the scope of the class (serialization), even if just in a unittest.
Would it be possible to move this normalization to the `EXPECT_NEAR` statement?

---

*[drake/systems/lcm/test/translator_test.cc, line 388 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-Kmj75z7fHSCwKP09gXc:-Kmj75z9sFQrq690XQWt:byj08fh) ([raw file](https://github.com/robotlocomotion/drake/blob/cf3d3c8dd325441d664524eb1b48744d66c1ea24/drake/systems/lcm/test/translator_test.cc#L388)):*
> ```cpp
>   void Decode(const robotlocomotion::pose_t& msg,
>               Isometry3<T>* data) const override {
>     Quaternion<T> tmp_rot;
> ```

It may be better to test the `*Translator` classes separately (messages only, no `systems` stuff), especially for being able to use these outside of a System context (e.g., loading from a log file and not wanting to pass them along System ports), and then make a separate unittest testing one or two translators within the systems wrapping, and trust that the translator classes work by component-based testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-Kmj83VDWNKjwPW66Wu3:b-x044kf)*

**Comment by siyuanfeng-tri** [comment]
@ericcousineau-tri I split the translators for robotlocomotion::stuff to drake/lcm/robotlocomotion_translators/ 

+@sherm1 for platform review.

---

Reviewed 5 of 14 files at r1, 3 of 10 files at r2, 21 of 21 files at r3, 1 of 5 files at r4.
Review status: 25 of 29 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQMTzMBX15E_Bx1LJv:-Kml9ebpH_10gYWtUnFC:b9k5jwh) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L18)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Ignoring given authorship of the file. Would still be nice to include authorship, but not worth blocking the PR.
</blockquote></details>

changed. 

---

*[drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-KlQN0HtKvbDGxHLY5ad:-Kml9rv14-QDZCDH6PXm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf1f704e88d333a48a6af16bac15139d7eb4e542/drake/examples/QPInverseDynamicsForHumanoids/humanoid_status_translator.h#L116)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

nit Could this be renamed to `robot_state_translator_`, to make it slightly clearer that this is composition?
</blockquote></details>

Done.

---

*[drake/systems/lcm/test/translator_test.cc, line 350 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-Kmj5gd8wLkUxqEgsnnT:-Kml9yACtWCxOqTXdnX9:bedz649) ([raw file](https://github.com/robotlocomotion/drake/blob/cf3d3c8dd325441d664524eb1b48744d66c1ea24/drake/systems/lcm/test/translator_test.cc#L350)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I'm a little sketched out by doing extra operations / extending the scope of the class (serialization), even if just in a unittest.
Would it be possible to move this normalization to the `EXPECT_NEAR` statement?
</blockquote></details>

I think I ought to normalize it here? As a user, I don't want to normalize it myself. I am expecting an orientation quaternion out of this. I can add a public comment. 

---

*[drake/systems/lcm/test/translator_test.cc, line 388 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-Kmj75z7fHSCwKP09gXc:-Kmm2CUcikqhQTx6IeXS:bjmurmr) ([raw file](https://github.com/robotlocomotion/drake/blob/cf3d3c8dd325441d664524eb1b48744d66c1ea24/drake/systems/lcm/test/translator_test.cc#L388)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

It may be better to test the `*Translator` classes separately (messages only, no `systems` stuff), especially for being able to use these outside of a System context (e.g., loading from a log file and not wanting to pass them along System ports), and then make a separate unittest testing one or two translators within the systems wrapping, and trust that the translator classes work by component-based testing.
</blockquote></details>

I spitted these to /drake/lcm/robotlocomotion_translators/test, and only test for the translators. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-Kmm9eQg13l3qCOky_y6:bewwtx0)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192)*

**Comment by siyuanfeng-tri** [comment]
@sherm1 @ericcousineau-tri 
I think I should break this up for sherm. It's too big even though most of it is not interesting. I can easily breakable into smaller chunks. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6192#-:-KmmCM7xwc0vraKheVZR:br3zyvu)*

**Comment by siyuanfeng-tri** [comment]
Breaking this up to smaller chunks.

**Comment by sherm1** [comment]
Thanks, @siyuanfeng-tri -- there is a lot to review here!

**Pull request closed without merging**
