### PR TITLE
Adds a hierarchy to our dynamical systems library in doxygen

### PR DESCRIPTION
**Pull request by RussTedrake**
and adds some missing @ingroup tags.

we're starting to fill out the library.  exciting!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3698)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/controlled_spring_mass_system/controlled_spring_mass_system.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3698#-KTPHfanzoGgNbf1aiXg:-KTPHfaoFCt2Yk4kAn8K:b6h7at) ([raw file](https://github.com/robotlocomotion/drake/blob/f8851e984b11f75216dd7a829f9341aff0d092a4/drake/systems/plants/controlled_spring_mass_system/controlled_spring_mass_system.h#L29)):*
> ```objc
> /// They are already available to link against in libdrakeSystemFramework.
> /// No other values for T are currently supported.
> /// @ingroup rigid_body_systems
> ```

This system caused a lot of confusion (for me, at least) on #3682.  The slack consensus yesterday was that `plants` precedes `controllers` in the physical ordering, which suggests that this doesn't belong in `plants` at all (once #3699 is resolved).  So, @naveenoid was planning to move it to `analysis/tests`, since that's the only use site.  

However, if we consider this just a piece of test infrastructure, this @ingroup declaration will be confusing.  I'm not sure how to cut that knot; do you have a preference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3698)*

**Comment by RussTedrake** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/controlled_spring_mass_system/controlled_spring_mass_system.h, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3698#-KTPHfanzoGgNbf1aiXg:-KTPkXyeH9SHSAshkq8G:b-826dps) ([raw file](https://github.com/robotlocomotion/drake/blob/f8851e984b11f75216dd7a829f9341aff0d092a4/drake/systems/plants/controlled_spring_mass_system/controlled_spring_mass_system.h#L29)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This system caused a lot of confusion (for me, at least) on #3682.  The slack consensus yesterday was that `plants` precedes `controllers` in the physical ordering, which suggests that this doesn't belong in `plants` at all (once #3699 is resolved).  So, @naveenoid was planning to move it to `analysis/tests`, since that's the only use site.  
> 
> However, if we consider this just a piece of test infrastructure, this @ingroup declaration will be confusing.  I'm not sure how to cut that knot; do you have a preference?
</details>
i agree that it feels more like a test/example than a core library feature.  i'd be happy to see it moved out (and have its group association similarly removed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3698)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3698#-:-KTPkoQoS65R8U4e5pSJ:bnfp4nl)*

**Comment by RussTedrake** [comment]
CI is a flake.  received f2f permission to push.

**Pull request merged**
