### PR TITLE
Remove sparseness_threshold in gurobi_solver

### PR DESCRIPTION
**Pull request by hongkai-dai**
The user should change the MathematicalProgram to remove small
coefficients, rather than using this threshold hidden inside
gurobi_solver.cc

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
This `sparseness_threshold` is hidden inside gurobi_solver.cc and hard-coded to 1E-14. The user might not be aware of it, neither can they modify this. A better approach is just to remove the small coefficients in MathematicalProgram object, where the users have access to all the constraints/costs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N84pjfS05O9bsEsj8dM:b3k95hv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N84q1n1-fcpPlwPx4hU:b-w629gj)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Comment by jwnimmer-tri** [comment]
If I'm understanding correctly, the user might notice different Solve() results as of this change (in case they had forgotten to tidy their MP).  That's fine if so, but in that case we should use "release notes: fix" so that we document the change in behavior for users.

**Review by hongkai-dai — COMMENTED** [review]
Done. I changed the release notes to fix.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N84sFrH2GrmtYvSj-eO:b40hj2z)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
:lgtm:

+@seancurtis-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N8xt1rK3n6sgUdc_8PX:b-79q6mv)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

I'm curious if the typical user of `MathematicalProgram` is aware of a) the need to curate their coefficients and b) how to "remove the small coefficients in MathematicalProgram object".

Are both of those topics familiar topics to MP users? Or should the topic of very small coefficients be broached anywhere? Given that this only effects gurobi users, I might assume that non gurobi users are already trained into this, yes?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N8zA0HI1X3iSqK4dOQU:bicx1u1)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
The typical users are probably not familiar with the need to curate their coefficients, and it is non-trivial to remove small coefficients in MathematicalProgram objects (it is doable, but cannot be done with just one function call).

I will add functions to MathematicalProgram and curates the small coefficients.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17648#-:-N97ZN7B924Rsuak0Mq_:b-gec54j)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,SeanCurtis-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
