### PR TITLE
Remove precompiled snopt

### PR DESCRIPTION
**Pull request by jamiesnape**
See comments in #3763.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3767)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by RussTedrake** [comment]
LGTM  ..  fwiw, i also checked the checkDependency.m logic and confirmed no action was needed there.  

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3767#-:-KTpHp5f6IM5hvbLjnkq:b-r744p1)*

**Comment by jamiesnape** [comment]
@RussTedrake These timeout or fail when they fall back to using `fmincon`:
```
examples/Airplane2D/runDircolWithObs
examples/Atlas/test/runHandContactSensorTest
examples/Atlas/test/testRunningPlanner
examples/Glider/runLQR
examples/Glider/runPSM
examples/HolonomicDrive/HolonomicDrivePlant.runTrajectory
examples/Quadrotor/crazyflie/runDircol
systems/plants/test/contactSensorTest
systems/plants/test/testCollisionDetectFromPoints
systems/plants/test/testIK
```
Do you want me to investigate further or should we make them explicitly depend (at least temporarily) on having SNOPT built from source?

**Comment by RussTedrake** [comment]
Guarding them on having snopt sounds good.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab-open-source please

**Comment by jamiesnape** [comment]
I will take @RussTedrake's LGTM as a feature review and ask +@david-german-tri for a platform review to complete formalities.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3767#-:-KTtFmBiOm5YCzWIbR3t:bnfp4nl)*

**Comment by jamiesnape** [comment]
@david-german-tri, as discussed in the meeting earlier.

**Comment by david-german-tri** [comment]
Awesome.  Thanks for the pointer!

**Pull request merged**
