### PR TITLE
[fem] Add ElementCacheEntry

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #16492.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495#-:-Muw28Z784zqXBdFgiQd:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 5 unresolved discussions, LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fem/element_cache_entry.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-7EkpD1MUl-hfwWad:-Mv-7Ekq5scIJ7pKvMWG:b-e4fizf) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L2)):*
> ```objc
> #pragma once
> ```

nit, per Slack discussion probably worth having a commit with all the `git mv` (in this case this file) and a separate commit with changes/additions? 
For those files for which `git mv` does make sense only. 
___
*[multibody/fem/element_cache_entry.h, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-7WfKDC6a9eiP0U1m:-Mv-7WfKDC6a9eiP0U1n:bp6juvy) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L15)):*
> ```objc
>  per-element, state-dependent quantities used in an FEM simulation that are
>  not states themselves. These quantities are stored in `ElementData`.
>  @tparam ElementData    The state-dependent quantities of the element that are
> ```

nit, is the additional spacing intentional
___
*[multibody/fem/element_cache_entry.h, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-7zuB9NPLA0WFMYwB:-Mv-7zuB9NPLA0WFMYwC:b-g40gzb) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L18)):*
> ... is the same type as the template parameter `DerivedElement` in FemElement.

I wonder if we can have a strong enforcement of this requirement.
For instance, what we simply template this class on the element type instead, FooElement. That way the relationship "Cache entry for FooType::Traits::Data" is implicit.

Below you the would replace `ElementData element_data_` with `typename FooType::Traits::Data element_data_`.
___
*[multibody/fem/element_cache_entry.h, line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-8XLfEA_-pqsRDOxK:-Mv-8XLfEA_-pqsRDOxL:b-6iywbl) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L20)):*
> ```objc
>  is the same type as the template parameter `DerivedElement` in FemElement. */
> template <class ElementData>
> class ElementCacheEntry {
> ```

another question. Are there any other requirements on `FooType::Traits::Data`? for instance, either copyable or being clonable.
___
*[multibody/fem/element_cache_entry.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-9C0XC1vbm3V2w_eU:-Mv-9C0XC1vbm3V2w_eV:bkojkdz) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L34)):*
> ```objc
>    staleness flag. The callers should modify the staleness flag through
>    set_stale() when needed.  */
>   ElementData& mutable_element_data() { return element_data_; }
> ```

this reminds me a bit of the discussion we had when we designed the SapSolver caching. I remember we didn't quite like this and Sherm proposed some nice improvements.
Looking at that code, I see we got away with actually marking data as stale when using the mutable access. Could we do the same here? are there other reasons why not to?

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
+@jwnimmer-tri for platform review please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495#-:-Mv02qqr8Dq9FHguQSds:b-9acgqz)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[multibody/fem/element_cache_entry.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-7EkpD1MUl-hfwWad:-Mv01vNc939NDci8O05O:b-d50jog) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L2)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Do you want me to do that for this PR as well?
</blockquote></details>

I already reviewed it, so I am ok with this PR as is now. It just took this as an example for something you could do in future PRs. Marking as resolved.
___
*[multibody/fem/element_cache_entry.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-9C0XC1vbm3V2w_eU:-Mv02d-Z8Gy6_s3KgkHy:bu7xg3i) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We could, but I don't see a significant amount of benefit. The only place where we access a mutable data is in the `element_data()` method here.
</blockquote></details>

oh I see, I imagine that's because whoever access a mutable cache entry reference will mark it as stale?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv03MwzDCAcyoT_2sBn:b-unyphp) (no related file):*
I have a vague memory that we've already discussed this, but I didn't immediately find any links to the past discussion, and I can't remember what we said.

Why does FEM need to invent its own caching infra from scratch, instead of using (or improving) the excellent systems framework caching infra?  The framework has great logging, diagnostics, thorough testing, settings knobs, type erasure, serialization of intermediate results, etc.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @amcastro-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv07H6pCHc9yua6uZJ1:brqchdv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I have a vague memory that we've already discussed this, but I didn't immediately find any links to the past discussion, and I can't remember what we said.

Why does FEM need to invent its own caching infra from scratch, instead of using (or improving) the excellent systems framework caching infra?  The framework has great logging, diagnostics, thorough testing, settings knobs, type erasure, serialization of intermediate results, etc.
</blockquote></details>

I think we had that discussion in SapSolver. The reason that I have been avoiding the existing caching infra is that I haven't found a way to avoid dragging all the framework dependency along with it. It's easier to reason about FEM stuff independent of the system-context framework. 

---
___
*[multibody/fem/element_cache_entry.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-7EkpD1MUl-hfwWad:-Mv08-jm9VsoRKIxC2nq:b-t4x9wf) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I already reviewed it, so I am ok with this PR as is now. It just took this as an example for something you could do in future PRs. Marking as resolved.
</blockquote></details>

Got it. Future PRs that can be moved will be moved.
___
*[multibody/fem/element_cache_entry.h, line 34 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv-9C0XC1vbm3V2w_eU:-Mv084vH8W7ep1ohBakK:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake/blob/2ee863b79e1e3c51c13589de968bd72887cae989/multibody/fem/element_cache_entry.h#L34)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

oh I see, I imagine that's because whoever access a mutable cache entry reference will mark it as stale?
</blockquote></details>

Yes.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv0FRKw3t5OrrcDfvG9:b-z00ygm) (no related file):*
> ... dragging all the framework dependency along with it ...

Are you alluding to compile times, or do you mean some other kind or ergonomics concern?

> It's easier to reason about FEM stuff independent of the system-context framework.

I'm not convinced that's true.  Code that uses bespoke caching is extremely difficult to review for correctness.  All of the extra features of framework caching make it easier to understand, debug, and diagnose.

Possibly I should join the next FEM project meeting to get a higher-bandwidth channel for this design discussion.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv0LDFYCW8N_rpiLt4T:bpfek1s) (no related file):*
> Are you alluding to compile times, or do you mean some other kind or ergonomics concern?

No. The data being calculated and cached here is low-level, and to utilize the existing caching infra, the cache would probably have to be defined in the closest system (MbP in this case). At that level, these quantities are already abstracted away -- MbP (and the discrete update managers) don't even know that these data exists. It'd be awkward that the system has to reach all the way down here to cache these quantities.

> Code that uses bespoke caching is extremely difficult to review for correctness. 

I agree. In this case though, the dependency is so simple that I don't see the harm of the bespoke cache. There are some FEM state and a single type of cache entry. The cache is invalidated if anything in the state changes. There's no inter-dependency among multiple cache entries. 

> Possibly I should join the next FEM project meeting to get a higher-bandwidth channel for this design discussion.

That'll be great! We don't have a an "FEM project meeting", but discussions on this would happen in softsim meeting. I sent you a calendar invite.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv1K0FY1suEvwJmYDtt:bipb3zm) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> Are you alluding to compile times, or do you mean some other kind or ergonomics concern?

No. The data being calculated and cached here is low-level, and to utilize the existing caching infra, the cache would probably have to be defined in the closest system (MbP in this case). At that level, these quantities are already abstracted away -- MbP (and the discrete update managers) don't even know that these data exists. It'd be awkward that the system has to reach all the way down here to cache these quantities.

> Code that uses bespoke caching is extremely difficult to review for correctness. 

I agree. In this case though, the dependency is so simple that I don't see the harm of the bespoke cache. There are some FEM state and a single type of cache entry. The cache is invalidated if anything in the state changes. There's no inter-dependency among multiple cache entries. 

> Possibly I should join the next FEM project meeting to get a higher-bandwidth channel for this design discussion.

That'll be great! We don't have a an "FEM project meeting", but discussions on this would happen in softsim meeting. I sent you a calendar invite.
</blockquote></details>

Just had a F2F with @sherm1, and I'm starting to think there may be a clean way to use caching infra without the tremendous amount of pain that I imagined. I'll ponder on that.

---

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-Mv052pf8aah7nMJODSQ:bj0r7a7) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Just had a F2F with @sherm1, and I'm starting to think there may be a clean way to use caching infra without the tremendous amount of pain that I imagined. I'll ponder on that.
</blockquote></details>

AFAIK in order to use the `systems::Cache` you need to be a `systems::System`. We'd like to keep the `systems::` namespace out of `fem::` to avoid something similar to what we have in `multibody::internal::MultibodyTree`. Thus far IMO the FEM code is simpler in that regard.

Probably we could have a `drake::CacheClient` class from which anyone wanting to use caching could inherit from? i.e. a `systems::System` would also inherit from this class. That'd seem a project on its own. I believe something like that would delay us here.

---

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16495#-Mv03MwzDCAcyoT_2sBm:-MvKK8V9Ey7u6ra-a9PZ:b-yatr66) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

AFAIK in order to use the `systems::Cache` you need to be a `systems::System`. We'd like to keep the `systems::` namespace out of `fem::` to avoid something similar to what we have in `multibody::internal::MultibodyTree`. Thus far IMO the FEM code is simpler in that regard.

Probably we could have a `drake::CacheClient` class from which anyone wanting to use caching could inherit from? i.e. a `systems::System` would also inherit from this class. That'd seem a project on its own. I believe something like that would delay us here.
</blockquote></details>

Let's discuss f2f.

---

**Comment by jwnimmer-tri** [comment]
+(status: do not review) -@jwnimmer-tri while we explore an alternative design.

**Review by xuchenhan-tri — COMMENTED** [review]
Closing with alternative design in #16653.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16495#-:-MxGfE2g3qn-qV3BC9V9:bahv964)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @sherm1)

**Pull request closed without merging**
