### PR TITLE
find_loaded_library_test: Update test to use dummy shared library.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up to [this comment](https://github.com/RobotLocomotion/drake/pull/7632#issuecomment-352465011) in #7632.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7634)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@fbudin69500 for feature review, please.
+@soonho-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-:-L0eNeRiIDhpzF95UsDb:bxtstpe)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by fbudin69500** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/BUILD.bazel, line 617 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-L0eTTClKlZuCAu8gDTV:-L0eTTCsq5PlTBFoVAZ0:b-t670ya) ([raw file](https://github.com/robotlocomotion/drake/blob/089ec14d86c2867593728266e8a72e9ab7699748/common/BUILD.bazel#L617)):*
> ```Python
>     deps = [
>         # This can be any arbitrary library.
>         ":find_resource",
> ```

I am worried that `:find_resource` is linked twice and that would lead to a duplication of symbols. But if that works, it's all good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by soonho-tri** [comment]
:lgtm:

locally tested :apple: builds as well.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-:-L0eY0DSNQfTLM1Wv0oB:b34tdkh)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/BUILD.bazel, line 617 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-L0eTTClKlZuCAu8gDTV:-L0eY7EzOpF8zdCak_sy:b-s9qqng) ([raw file](https://github.com/robotlocomotion/drake/blob/089ec14d86c2867593728266e8a72e9ab7699748/common/BUILD.bazel#L617)):*
> I am worried that :find_resource is linked twice and that would lead to a duplication of symbols.

If this is the case, we're supposed to see an error (either at linking time, or run-time), right? FYI, when I do local testing, I haven't seen any error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by jwnimmer-tri** [comment]
*[common/BUILD.bazel, line 617 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-L0eTTClKlZuCAu8gDTV:-L0eYIEyRHN68bu30b6k:b-xgs7su) ([raw file](https://github.com/robotlocomotion/drake/blob/089ec14d86c2867593728266e8a72e9ab7699748/common/BUILD.bazel#L617)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> I am worried that :find_resource is linked twice and that would lead to a duplication of symbols.

If this is the case, we're supposed to see an error (either at linking time, or run-time), right? FYI, when I do local testing, I haven't seen any error.
</blockquote></details>

I think its guaranteed to work now (because the unit test doesn't happen to use find_resource), but really its a bit too cute and confusing; KISS would say just to make a small dummy source file for clarity, instead of re-purposing something unrelated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/BUILD.bazel, line 617 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-L0eTTClKlZuCAu8gDTV:-L0eZFB4Vzqy7FbrUrbo:br7kl5) ([raw file](https://github.com/robotlocomotion/drake/blob/089ec14d86c2867593728266e8a72e9ab7699748/common/BUILD.bazel#L617)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think its guaranteed to work now (because the unit test doesn't happen to use find_resource), but really its a bit too cute and confusing; KISS would say just to make a small dummy source file for clarity, instead of re-purposing something unrelated.
</blockquote></details>

Done. Sorry about that! Cuteness minimized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/BUILD.bazel, line 617 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-L0eTTClKlZuCAu8gDTV:-L0eZPDSA6q6PA-wmNIF:b-8fx2u7) ([raw file](https://github.com/robotlocomotion/drake/blob/089ec14d86c2867593728266e8a72e9ab7699748/common/BUILD.bazel#L617)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. Sorry about that! Cuteness minimized.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7634#-:-L0fgxkvKv9ZntfNN_uI:bnfp4nl)*

**Pull request merged**
