### PR TITLE
Feature/fix signed unsigned warnings

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2489)

### CODE REVIEW

**Comment by liangfok** [comment]
Given how small this PR is, perhaps +@david-german-tri can do both the feature and platform review?

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Feature/fix signed unsigned warnings
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-:-KJ7lPoy80uW488G7RLj:-1718275886)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Given how small this PR is, perhaps +@david-german-tri can do both the feature and platform review?
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-:-KJ7mLo-7inP6jwbSlyU:1417088721)*

**Comment by jwnimmer-tri** [comment]
@liangfok Please be aware of my WIP feature branch for this type of thing:
  https://github.com/jwnimmer-tri/drake/tree/werror-sign-compare
If the fix for a particular warning you dislike is already in there, it may save some time.
This is per #2372 where I am chipping away at these warnings.

Also be aware, the issues with signs are subtle, and need a bit of delicacy.  You have to be sure not just that the warning goes away, but that the semantics of the newly-chosen integral types are correct, given the surrounding code.  I've checked, and this PR's changes are fine in that respect.  (With one minor nit, posted below.)

If incremental PRs are desirable, I can help restructure #2374 to have a checklist that people can claim indepdently.  A good strategy would be to start from `common` and `core` and work our way down the list of directories in dependency order.  Then we can turn on `-Werror=sign-compare` on `common` for example, so that it never gets any worse once we've fixed them.  We have to proceed top-down because warnings in common headers would trip up down-tree code as well.

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[drake/systems/controllers/zmpUtil.cpp, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-KJ8F4vJghDYiGrOpiMs:-KJ8F4vJghDYiGrOpiMt:-1272169407) ([raw file](https://github.com/robotlocomotion/drake/blob/34b41401ce2243c3d5d32ef29e5cada53856da28/drake/systems/controllers/zmpUtil.cpp#L61)):*
> ```cpp
>     }
> 
>     if (j == n - 1) {
> ```

BTW This is one of the really dangerous remaining signed / unsigned computations.

---

*[drake/systems/controllers/zmpUtil.cpp, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-KJ8DJ3aST8G_4zWAFei:-KJ8DJ3aST8G_4zWAFej:-819395822) ([raw file](https://github.com/robotlocomotion/drake/blob/34b41401ce2243c3d5d32ef29e5cada53856da28/drake/systems/controllers/zmpUtil.cpp#L69)):*
> ```cpp
>     VectorXd dtpow(k);
>     for (int p = 0; p < k; p++) {
>       dtpow(p) = pow(dt(j), static_cast<int>(p));
> ```

Defect: this cast is no longer necessary.

---

*[drake/systems/plants/RigidBodyTree.h, line 187 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-KJ8EDKPcZOBB_7KpilQ:-KJ8EDKPcZOBB_7KpilR:-788609492) ([raw file](https://github.com/robotlocomotion/drake/blob/34b41401ce2243c3d5d32ef29e5cada53856da28/drake/systems/plants/RigidBodyTree.h#L187)):*
> ```objc
>                                           // this
> 
>     for (size_t i = 0; i < bodies.size(); i++) {
> ```

BTW The fix on my feature branch for this used a range-based for loop, which is a cleaner solution when the integral index is unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-:-KJ8D2JEPKkhL0IhqdPh:-1409555600)*

**Comment by liangfok** [comment]
Oops. I didn't know you had a WIP branch fixing the signed/unsigned compare errors. Thanks for the advice about being careful fixing these errors. Having a checklist that establishes an order in which to fix these errors would be helpful.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @liangfok Please be aware of my WIP feature branch for this type of thing:
>   https://github.com/jwnimmer-tri/drake/tree/werror-sign-compare
> If the fix for a particular warning you dislike is already in there, it may save some time.
> This is per #2372 where I am chipping away at these warnings.
> 
> Also be aware, the issues with signs are subtle, and need a bit of delicacy.  You have to be sure not just that the warning goes away, but that the semantics of the newly-chosen integral types are correct, given the surrounding code.  I've checked, and this PR's changes are fine in that respect.  (With one minor nit, posted below.)
> 
> If incremental PRs are desirable, I can help restructure #2374 to have a checklist that people can claim indepdently.  A good strategy would be to start from `common` and `core` and work our way down the list of directories in dependency order.  Then we can turn on `-Werror=sign-compare` on `common` for example, so that it never gets any worse once we've fixed them.  We have to proceed top-down because warnings in common headers would trip up down-tree code as well.
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-:-KJ8qmT_AmxWpdzr08lS:-1226035976)*

**Comment by liangfok** [comment]
*[drake/systems/plants/RigidBodyTree.h, line 187 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-KJ8EDKPcZOBB_7KpilQ:-KJ8uluACoUYJSGa-7aY:1884968395) ([raw file](https://github.com/robotlocomotion/drake/blob/34b41401ce2243c3d5d32ef29e5cada53856da28/drake/systems/plants/RigidBodyTree.h#L187)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW The fix on my feature branch for this used a range-based for loop, which is a cleaner solution when the integral index is unnecessary.
</details>
OK sorry for inducing a conflict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489)*

**Comment by liangfok** [comment]
*[drake/systems/controllers/zmpUtil.cpp, line 69 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2489#-KJ8DJ3aST8G_4zWAFei:-KJ8uYWJtbbLCD9rlNdl:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/34b41401ce2243c3d5d32ef29e5cada53856da28/drake/systems/controllers/zmpUtil.cpp#L69)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Defect: this cast is no longer necessary.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2489)*

**Pull request merged**
