### PR TITLE
Explain how to turn on assertions for developers

### LINKED ISSUE #1935: Drake's internal assertions should be enabled by default
_**Edited to add: The italics text is from a revised, round two proposal for this debate.** (Struck-through text is from the first round, now removed.)_

(I may have misunderstood something, but here's my best summary.  Please correct me if I'm wrong somewhere here.)

The default build type for Drake is a release build.  This puts `-DNDEBUG` in the compiler flags.  Drake code (drake/drake/**.{h,cc}) uses `assert` statements (from `<cassert>`).  Those turn into no-ops when `-DNDEBUG` is in use.  The developer quick setup ends up with us using release builds, and all the CIs that I can find use release builds as well.  That means that almost nobody is testing whether the assertions pass!

_**Drake's**_ assertions should be ~~enabled by default, and~~ decoupled from whether -O2 and other speed-ups are in use.  If we want to provide users a shotgun to point at their foot (turning off assertions for "speed"), that should be an orthogonal configuration option from everything else.

In other words, I propose
- (1) forbidding "assert" in drake code,
- (2) providing our own drake-specific assertion function(s) that muse be used instead.
- ~~If there is a cry from the community to turn off our assertions, we can add a cmake option for that (and spin up a bunch more CI servers to test that build variant).~~
- _(3) By default, drake_assert being on or off will obey NDEBUG._
- _(4) Drake users can set an option to override the default, and turn drake_assert on or off independently._
- _(5) To the extent that pre-submit PR builds still do not have any debug variants, we turn on drake_assert for at least some PR builders._

How does the community feel about this kind of proposal?

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #1935.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2946)

### CODE REVIEW

**Comment by liangfok** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 129 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNe7ymBlfBR5hsR-jaW:-KNe7ymCSRICYnvLbQDe:-674127697) ([raw file](https://github.com/robotlocomotion/drake/blob/9280e04284422f4bbe1fa340a008e34a43e345b4/drake/doc/unit_testing_instructions.rst#L129)):*
> ```reStructuredText
>   ctest -VV -C RelWithDebInfo -R cascade_system_test
> 
> Enabling Assertions
> ```

Consider adding the following custom anchor immediately above this section title so it can be referenced from other parts of this Sphinx-based website:

```
.. _enabling_assertions:
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by jwnimmer-tri** [comment]
@liangfok for feature review, please.
@sammy-tri for platform review, please.

**Comment by liangfok** [comment]
:lgtm: Just one question below.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNgmZb_9f5IFybIZJvN:-1883701561) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
> ```reStructuredText
>     ninja
> 
> We recommend turning on assertions in all of your builds during development.
> ```

BTW, do you think we should make `DRAKE_ENABLE_ASSERTS` an opt-out option rather than an opt-in option? Is there a performance argument against making it opt-out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-:-KNgmocxoDQgtyka6DWU:-1902224584)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNgotbALpb-Np0ist4q:761849485) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, do you think we should make `DRAKE_ENABLE_ASSERTS` an opt-out option rather than an opt-in option? Is there a performance argument against making it opt-out?
</details>
This was debated extensively in #1935.  Turning on Drake assertions in release builds was thought to be an unspeakably awful sin, so was disagreeable as a default.  To my understanding, this is the best compromise I could achieve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by sammy-tri** [comment]
:lgtm:, though the existence of both DRAKE_ENABLE_ASSERT and DRAKE_DISABLE_ASSERT makes me die a little inside.  (at least the logic is checked in drake_assert.h)...

One comment which I don't think needs to be resolved before merging, but given than Jenkins is also unhappy, I'm going to leave it to @jwnimmer-tri to push the merge button.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/test/CMakeLists.txt, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgonajeEXze_wduulS:-KNgonakLaBL8HJH2WSw:460870805) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/common/test/CMakeLists.txt#L21)):*
> ```CMake
> add_executable(drake_assert_test_enabled drake_assert_test.cc)
> target_compile_definitions(drake_assert_test_enabled PRIVATE DRAKE_ENABLE_ASSERTS)
> if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
> ```

BTW, it was not obvious why "GNU" got STREQUAL and "Clang" got MATCHES on this line...  I'm guessing it's to evaluate to true on both "Clang" and "AppleClang"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-:-KNgpuA6bUhlMgBA9KlR:-135748332)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/common/test/CMakeLists.txt, line 21 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgonajeEXze_wduulS:-KNgtry-Z1FGiRVHq21b:-1337498371) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/common/test/CMakeLists.txt#L21)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW, it was not obvious why "GNU" got STREQUAL and "Clang" got MATCHES on this line...  I'm guessing it's to evaluate to true on both "Clang" and "AppleClang"?
</details>
I do not know either.  I am just cargo-culting Kitware to remain consistent:
https://github.com/RobotLocomotion/drake/blob/2286ebe3ffa276a417799be7400d940d6cc6302d/drake/CMakeLists.txt#L80

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNgufwNwwiAjMxBIafz:138860100) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This was debated extensively in #1935.  Turning on Drake assertions in release builds was thought to be an unspeakably awful sin, so was disagreeable as a default.  To my understanding, this is the best compromise I could achieve.
</details>
I wonder if it's possible to enable-by-default `DRAKE_ENABLE_ASSERT` for mode `RelWithDebInfo` but _not_ `Release`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNgv5v-vRN5kkzAg_WW:-606265562) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I wonder if it's possible to enable-by-default `DRAKE_ENABLE_ASSERT` for mode `RelWithDebInfo` but _not_ `Release`?
</details>
I considered that, but thought it violated the spirit of the consensus.  Also, the fact that those are two separate options is stupid and we should not rely on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by sherm1** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNh59E1sVC2JMK4I1EG:1502310016) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I considered that, but thought it violated the spirit of the consensus.  Also, the fact that those are two separate options is stupid and we should not rely on it.
</details>
RelWithDebInfo is supposed to run at full Release speed and should be suitable for use in shipped binaries since it tends to make field-reported disasters easier to debug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-:-KNhDBQUzIQzO7tPH8DV:1417088721)*

**Comment by jwnimmer-tri** [comment]
*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNhDkZCOLPD9F6nGJVA:-1299719981) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> RelWithDebInfo is supposed to run at full Release speed and should be suitable for use in shipped binaries since it tends to make field-reported disasters easier to debug.
</details>
FYI `RelWithDebInfo` is `-O2` and `Release` is `-O3`.  :jackiechan:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Comment by liangfok** [comment]
*[drake/doc/unit_testing_instructions.rst, line 142 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2946#-KNgmZbZwrYyyPBIwdxt:-KNhEr79hpAhc_aDNvg7:545733519) ([raw file](https://github.com/robotlocomotion/drake/blob/1d7ce03ac6240f3bf4c102ca04cc64a319152d88/drake/doc/unit_testing_instructions.rst#L142)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI `RelWithDebInfo` is `-O2` and `Release` is `-O3`.  :jackiechan:
</details>
TODO: Add benchmarks to Drake that demonstrate this makes a practical difference :smile: .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2946)*

**Pull request merged**
