### PR TITLE
Remove unused libyaml and libdl2 dependencies

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #17161.

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18734)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-cmake-experimental-everything-release please

+@svenevs for feature review, please. (Does this seem like sufficient coverage for pre-merge?)

**Comment by jwnimmer-tri** [comment]
There is no direct CI coverage of the `binary_distribution` text files, since the `source_distribution` usually trumps them anyway and we never install "binary" on their own (since by its nature, Drake CI is always building from source).  The closest we have to CI coverage are the `drake-external-examples` jobs, but that code currently _forks_ the package lists into its git tree, instead of using the list embedded in the packages it downloads, so you'd need to do weird hijinks there to get it testing what you want it to test.

That's all a bit of a hassle.

To me, testing locally manually starting from an empty Docker image would be easiest:
- Boot an empty Docker (once on Focal, and once on Jammy).
- In that container, run the version of `binary_distribution/install_prereqs.sh` from _this_ PR.  Notably the _binary_ script, not the _source_ one.
- Unpack last night's nightly tgz release (https://drake.mit.edu/from_binary.html) into the container.
- Try `import pydrake.all`.  If there are missing shared libraries, it will complain.

**Comment by mwoehlke-kitware** [comment]
> ... testing locally manually ...

Done. No import errors.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging please.
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging please.

These jobs are additionally needed to evaluate the changes here, the contents of `setup/ubuntu/packages-*` in this PR change the final packaged dependencies.

**Review by svenevs — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review, per schedule, please.

> To me, testing locally manually starting from an empty Docker image would be easiest:
>
> - Boot an empty Docker (once on Focal, and once on Jammy).
> - In that container, run the version of binary_distribution/install_prereqs.sh from this PR. Notably the binary script, not the source one.
> - Unpack last night's nightly tgz release (https://drake.mit.edu/from_binary.html) into the container.
> - Try import 1pydrake.all`. If there are missing shared libraries, it will complain.

Feature review repeated these steps and they were successful. I also confirmed from a fresh macOS `brew` state that `libyaml` can be removed (this was never tracked anywhere, it is OK for this PR to remove it).

@mwoehlke-kitware I added more information on how to do this package analysis as you finish off the ticket in https://github.com/RobotLocomotion/drake/issues/17161#issuecomment-1421468999

@jwnimmer-tri there are some new potential issues from this analysis, but **none** relate to this PR.  `shlibs:Depends` vs our packages here, removing `libdl2` and `libyaml-cpp-dev` is A-OK.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18734#-:-NNgqLei4VhRXsux3tnj:b-3riw17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18734#-NNgqDOQ0moMl3GE95i3):*
nit: on squash perhaps state them explicitly (`libyaml` and `libdl`)?  `Remove unused libyaml and libdl dependencies`?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18734#-:-NNhwZPOD3pEXsJnwuZo:b-vtj4vo)* status: 1 unresolved discussion, missing label for release notes (waiting on @mwoehlke-kitware)

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18734)* status: missing label for release notes (waiting on @mwoehlke-kitware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18734#-NNgqDOQ0moMl3GE95i3):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

nit: on squash perhaps state them explicitly (`libyaml` and `libdl`)?  `Remove unused libyaml and libdl dependencies`?
</blockquote></details>

Done.

**Pull request merged**
