### PR TITLE
Fix ParseConstraint for cases with infs in rhs or lhs.

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, cases like
```
b = [0.12, inf]
ParseConstraint(x <= b)
```
would fail with
```
abort: Failure at solvers/create_constraint.cc:88 in ParseConstraint(): condition '!std::isnan(new_lb(i))' failed.
```
due to an `inf - inf` situation. Now we handle those cases properly.

+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19903)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-release please

(#19335 known flake)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@rpoyner-tri for platform review please, thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19903#-:-NalsyzgDJ8lOnxIzOGR:b-sjvomj)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

___
*[`solvers/create_constraint.cc` line 367 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19903#-NalsYmO0emsjDMU9OMW:-NalsYmO0emsjDMU9OMX:b-kipim9) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b559aa1ba70d401dcafb21dce8048dc801c9491/solvers/create_constraint.cc#L367)):*
> ```cpp
>           // -∞ <= lhs - rhs <= 0
>           v(k) = lhs - rhs;
>           lb(k) = -std::numeric_limits<double>::infinity();
> ```

BTW, use `-kInf` here?
___
*[`solvers/create_constraint.cc` line 398 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19903#-Nalsob76y4227mhad0x:-Nalsob76y4227mhad0y:bs4q9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b559aa1ba70d401dcafb21dce8048dc801c9491/solvers/create_constraint.cc#L398)):*
> ```cpp
>           v(k) = lhs - rhs;
>           lb(k) = 0.0;
>           ub(k) = std::numeric_limits<double>::infinity();
> ```

Ditto.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19903)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`solvers/create_constraint.cc` line 398 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19903#-Nalsob76y4227mhad0x:-NaltyaIAWLnvkYMHUIs:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/6b559aa1ba70d401dcafb21dce8048dc801c9491/solvers/create_constraint.cc#L398)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19903)* status: LGTM missing from assignee rpoyner-tri(platform)

**Pull request merged**
