### PR TITLE
Revert "[geometry] Make soft half space/rigid mesh hydroelastic differentiable"

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Dear @SeanCurtis-TRI ,

 The on-call build cop, @BetsyMcPhail , believes that your PR #14943  may have
 broken one or more of Drake's continuous integration builds [1]. It is
 possible to break a build even if your PR passed continuous integration
 pre-merge because additional platforms are tested post-merge.

 The specific build failures under investigation are:

- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-address-sanitizer/3327/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/3329/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-clang-bazel-continuous-release/1011/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-unprovisioned-clang-bazel-continuous-everything-release/1007/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-unprovisioned-clang-bazel-continuous-release/1053/

 Therefore, the build cop has created this revert PR and started a complete
 post-merge build to determine whether your PR was in fact the cause of the
 problem. If that build passes, this revert PR will be merged 60 minutes from
 now. You can then fix the problem at your leisure, and send a new PR to
 reinstate your change.

 If you believe your original PR did not actually break the build, please
 explain on this thread.

 If you believe you can fix the break promptly in lieu of a revert, please
 explain on this thread, and send a PR to the build cop for review ASAP.

 If you believe your original PR definitely did break the build and should be
 reverted, please review and LGTM this PR. This allows the build cop to merge
 without waiting for CI results.

 For advice on how to handle a build cop revert, see [2].

 Thanks!
 Your Friendly On-call Build Cop

 [1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
 [2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14995)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-release please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

Given the asan error (and the newly reported mac error), I'm going for the revert.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14995#-:-MZncS4b59JnZRFEMwc9:b-oqsb61)* status: needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14995#-:-MZncYzi5JUbxvx9LMHO:b3dcro0)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail)

**Comment by jamiesnape** [comment]
Debug is hung up again. I can force this in if this is the agreed upon interim solution.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I agree.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14995#-:-MZnngAFClJUh4ioDisE:btd51a6)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @BetsyMcPhail)

**Pull request merged**
