### PR TITLE
py multibody/plant and multibody/tree: Expose scalar types

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards #11240

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11633)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/11633#-LhIZ7ny2z5gSoKSgs8L:-LhIu86h2DuMiLH3Z9MY:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(er, the lint errors were those that I had introduced :P)
</blockquote></details>

Done.

---

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/common/test_utilities/numpy_compare.py, line 75 at r2](https://reviewable.io/reviews/robotlocomotion/drake/11633#-LhLdkFu4GtBbI039Jmc:-LhM4eu070HwbpDcZSci:bbo1dzb) ([raw file](https://github.com/robotlocomotion/drake/blob/f45733d57d491980375d6b359e14d4edd6e66ed1/bindings/pydrake/common/test_utilities/numpy_compare.py#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry - I hadn't missed this even though you mentioned it.
Can you remove this change?

I would like to see where it's failing, and address each failure specifically (e.g. using `assert_float_allclose`).

Saying a function is `equal` but then checking `allclose` is a lie :(
</blockquote></details>

https://gist.github.com/m-chaturvedi/b3bf63083b86d59bcc72d736b4ade145
CI will start failing, I think.

**Comment by jwnimmer-tri** [comment]
FYI For all the shenanigans  around `std::vector<ExternallyApplied...>`, the correct solution is not to resolve the half-dozen obscure bindings TODOs, but to _never never have std::vector on an input port_.  That input port should be `struct ExternallyAppliedForces`, with a _nested_ std::vector if need be.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/multibody/test/plant_test.py, line 333 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lh__IL_2OS4PkdZY5DZ:-Lhav-pC0R1aMCLPf-Ki:b-rztg6c) ([raw file](https://github.com/robotlocomotion/drake/blob/4eb1fa9875c23cdd46d1166a8bc1ed1692963f75/bindings/pydrake/multibody/test/plant_test.py#L333)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

But how does SceneGraph become intertwined with gravity?  The check_multibody_gravity_default code doesn't even create a SceneGraph?
</blockquote></details>

I only took said it from the logs:
https://gist.github.com/m-chaturvedi/e0dbfb8a5959c46fec99c591f1f3b126#file-for_jeremy-sh-L35

Looks like `finalize` is calling it somewhere with a `null` argument?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/multibody/test/plant_test.py, line 333 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lh__IL_2OS4PkdZY5DZ:-LhazofH4Y326LO_dhIy:b4709lw) ([raw file](https://github.com/robotlocomotion/drake/blob/4eb1fa9875c23cdd46d1166a8bc1ed1692963f75/bindings/pydrake/multibody/test/plant_test.py#L333)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah... I see, `SceneGraph_[Expression]` is not a registered type, so when it tried to resolve `py::arg("scene_graph") = nullptr`, it complains about not being able to bind the value.

In this case, the fix is to do a trivial registration of `SceneGraph<Expression>`; like so in `geometry_py.cc`:
```
{
  using Class = SceneGraph<Expression>;
  DefineTemplateClassWithDefault<
      SceneGraph<Expression>, LeafSystem<Expression>>(
          m, "SceneGraph", GetPyParam<Expression>(),
          "Warning:\n    Bindings of ``SceneGraph_[Expression]`` are not "
          "fully implemented. This is only to permit passing None to APIs "
          "that take references to existing SceneGraph instances.");
}
```

Mmanu, can you add that in to the non-T bindings in `geometry_py.cc`?
</blockquote></details>

(er, the line `using Class = ...` is completely redundant...)

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/multibody/plant_py.cc, line 72 at r4](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lh_Vy0C8YuNLcBcXZg2:-Lhb2kTa-Fy_3b70dVAx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4eb1fa9875c23cdd46d1166a8bc1ed1692963f75/bindings/pydrake/multibody/plant_py.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`CopyIfNotPodType<double>` copies the `VectorBlock`, but it doesn't copy the underlying data, as it's effectively a `Map`.

Perhaps it could be clarified as this?
```
CopyIfNotPodType(<double overload>) {
   // N.B. This references the existing vector's data, and does not perform a copy.
  ...
}

CopyIfNotPodType(<T overload>) {
   // N.B. This copies the vector's data.
  // TODO(eric.cousineau): Remove this once #8116 is resolved.
  ...
}
```

</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhbAxJnB1J9FcaHx14p:bdviity) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er... This was my suggestion. Had you envisioned something else?

Sure, we can always do a shim of `Finalize()` that doesn't require `SceneGraph<Expression>*`, but that just means that we have to do this in every other location.

I personally prefer this approach; it only permits sane referencing to existing objects (or `nullptr`s), but does not expose the constructor.
</blockquote></details>

I guess my follow up question is: How does the signature of `Finalize(SceneGraph<T>*)` work in the first place, given that we have no instantiations of `SceneGraph<Expression>`?

To me, it seems like `SceneGraph<Expression>*` is effectively used in C++, so it is analagous if we use it in Python?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhbHoLb0ahMB4527Irt:b-prg9m4) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> ... we have to do this in every other location.

There are no other locations, are there?

And in any case, all of the default-nullptr arguments need to be deprecated and removed, none of them should exist; they are there for backwards compat only.
</blockquote></details>

Gotcha. Doing a quick perusal, `SceneGraph<T>* = nullptr` is only used for should-be deprecated methods.

In this case, Mmanu, can you remove this addition, and update `plant_py.cc` to explicitly bind the no-arg `Finalize()`?
```
.def("Finalize", [](Class* self) { self->Finalize(); }, doc....)
.def("Finalize", [](Class* self, SceneGraph<T>* scene_graph)  { self->Finalize(scene_graph); }, py::arg("scene_graph"), ...)
```

I'll file a follow-up issue to deprecate the old cruft overloads.

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhbIpkR2f24nWV8_Asa:by56syh) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. Doing a quick perusal, `SceneGraph<T>* = nullptr` is only used for should-be deprecated methods.

In this case, Mmanu, can you remove this addition, and update `plant_py.cc` to explicitly bind the no-arg `Finalize()`?
```
.def("Finalize", [](Class* self) { self->Finalize(); }, doc....)
.def("Finalize", [](Class* self, SceneGraph<T>* scene_graph)  { self->Finalize(scene_graph); }, py::arg("scene_graph"), ...)
```

I'll file a follow-up issue to deprecate the old cruft overloads.
</blockquote></details>

Filed: #11663

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhfJ-LV6YZK9XxyF1aM:bgofuvz) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I also have a PR ready to fix this + deprecation.

If it's easier for this PR, I am OK with a TODO in the unit test and skip the test for Expression support for now.
</blockquote></details>

Sorry for the delay.  I am trying to fix the Python3 issue.  I didn't have a Bionic setup.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-Lhfa-H_6_GyNDXgOiJj:bgim4su) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

Sorry for the delay.  I am trying to fix the Python3 issue.  I didn't have a Bionic setup.
</blockquote></details>

I think this is an interesting thing (include-what-you-use, cpp and clang-format): 
https://gist.github.com/m-chaturvedi/06247a097bdc6998631760c8f8308292

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-Lhfcc7tEAjaONkFgDCK:bmix6xo) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think the solution is just to expand the `#ifdef` to capture `autodiffutils_pybind.h`?
</blockquote></details>

Yes, but we can make it less sweeping than that buy wrapping only the relevant lines causing it?

**Comment by EricCousineau-TRI** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhfdgnY4uVPx2vk_yMT:bpohh6s) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

Yes, but we can make it less sweeping than that buy wrapping only the relevant lines causing it?
</blockquote></details>

Sorry - yeah, that would do it - just move the `#ifndef` to `autodiffutils_pybind.h`, right?

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/geometry_py.cc, line 225 at r6](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhb6M72AguwDy-OAMzc:-LhffDkE0P1ClHjO_hw3:b-dk7gxc) ([raw file](https://github.com/robotlocomotion/drake/blob/d909b05242398767d16b017612c4740b7d2e5404/bindings/pydrake/geometry_py.cc#L225)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry - yeah, that would do it - just move the `#ifndef` to `autodiffutils_pybind.h`, right?
</blockquote></details>

Yeah! ( Sorry for not being clear, but the branch I'd used in the gist was `master`).

**Comment by m-chaturvedi** [comment]
___
*[common/autodiffxd.h, line 95 at r8](https://reviewable.io/reviews/robotlocomotion/drake/11633#-LhfjUXf5II6hCWDf279:-Lhfjoo9Ack2DYMZ2Ju6:beydu7r) ([raw file](https://github.com/robotlocomotion/drake/blob/d56f4cf8eebec3a526e2ade54fe656fc89ff8234/common/autodiffxd.h#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

No, this is a problem with the code used in the pydrake bindings, not a general defect of this class.  The warning nerf should not be here.
</blockquote></details>

Then if we go with [Eric's comment](https://github.com/RobotLocomotion/drake/pull/11633#pullrequestreview-251247347), 
we have a conflict between your [comment](https://github.com/RobotLocomotion/drake/pull/11633#pullrequestreview-250598209) and include-what-you-use.

**Comment by m-chaturvedi** [comment]
___
*[common/autodiffxd.h, line 95 at r8](https://reviewable.io/reviews/robotlocomotion/drake/11633#-LhfjUXf5II6hCWDf279:-LhfmZ-E9gO-U8ypalP5:b-mwxsrz) ([raw file](https://github.com/robotlocomotion/drake/blob/d56f4cf8eebec3a526e2ade54fe656fc89ff8234/common/autodiffxd.h#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm sure there is a fix.  Do you want me to push it to this PR for you, or find it yourself?
</blockquote></details>

Let me try.

**Comment by m-chaturvedi** [comment]
___
*[common/autodiffxd.h, line 95 at r8](https://reviewable.io/reviews/robotlocomotion/drake/11633#-LhfjUXf5II6hCWDf279:-Lhg0HjT5adjZYKPOV-t:b-t05qsp) ([raw file](https://github.com/robotlocomotion/drake/blob/d56f4cf8eebec3a526e2ade54fe656fc89ff8234/common/autodiffxd.h#L95)):*
<details><summary><i>Previously, m-chaturvedi (Mmanu Chaturvedi) wrote…</i></summary><blockquote>

Let me try.
</blockquote></details>

I attempted a fix using the following rationale:
https://gist.github.com/m-chaturvedi/112bc820a5e066615209b62272059c99

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/autodiffutils_py.cc, line 9 at r9](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhg6Rl8840TW_Z_oIoa:-Lhg6lTpDtEFqERli_iC:b-ea6xdr) ([raw file](https://github.com/robotlocomotion/drake/blob/914f93ef669d685a48b7512419e6ba443cd14296/bindings/pydrake/autodiffutils_py.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If I revert the changes to this file, my local bionic gcc7 + python3 build passes.  Can you explain why this change is necessary?
</blockquote></details>

Yeah, mine too.  Like I said the rationale I'd used was in the gist:
https://gist.github.com/m-chaturvedi/112bc820a5e066615209b62272059c99

I can remove it, if you'd like.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/autodiffutils_py.cc, line 9 at r9](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhg6Rl8840TW_Z_oIoa:-Lhg8WOr95VwoG1oudeb:b-8ogfxm) ([raw file](https://github.com/robotlocomotion/drake/blob/914f93ef669d685a48b7512419e6ba443cd14296/bindings/pydrake/autodiffutils_py.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1) The gist was completely impenetrable to me.  You will have to explain it more clearly for me to be able to follow along.

(2) In any case is the rationale for this code being in this file needs to be _comments in this file_ not a gist / discussions in the PR review.
</blockquote></details>

I apologize.

The logic being that I could find that there are two usages of  `autodiff.h` in the `bindings`, one from `math` and one from `common`, the `math` one uses the `common` one.

And the problem file, `autodiffxd.h`, was included in `common/autodiff.h`.

Since we know that `autodiff.h` inside `bindings` can / may cause errors, I included the nerf at both the places.

**Comment by m-chaturvedi** [comment]
___
*[bindings/pydrake/autodiffutils_py.cc, line 9 at r9](https://reviewable.io/reviews/robotlocomotion/drake/11633#-Lhg6Rl8840TW_Z_oIoa:-LhgC6i42YiC3t-7qNJ5:bh02yeu) ([raw file](https://github.com/robotlocomotion/drake/blob/914f93ef669d685a48b7512419e6ba443cd14296/bindings/pydrake/autodiffutils_py.cc#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

But math/autodiff.h and common/autodiff.h are two completely different headers / concepts / code / etc, even though their share their basename?  I don't understand how math/autodiff.h enters the picture at all in the first place?
</blockquote></details>

I see.  The only reason I have is that it that the `math/autodiff.h` includes `common/autodiff.h` which includes `common/autodiffxd.h`:
https://github.com/RobotLocomotion/drake/blob/master/math/autodiff.h#L13

I'll remove the code.

**Pull request merged**
