### PR TITLE
valkyrie control

### PR DESCRIPTION
**Pull request by mauricefallon**
I've been able to make Val walk & balance in drake, basically by modifying all the Atlas example code where needed and making a few small changes to drake/systems where things were not generalized fully.

the only robot-specific changes I made were to move the LIP z-height ... which means that the walking controller was really well written. Kudos ;)
(Though the Valkyrie model is <very> similar in stucture to Atlas.)

Here's one video:
https://www.dropbox.com/s/bk070em5v6cqx5f/walkingA.m4v?dl=0
And a number of others for balancing and other tests are here:
https://www.dropbox.com/sh/ccquv2map95vvms/AAC-fJHa3Ij0S2DTJUL7brl1a?dl=0

I'm creating a pull request, but mostly to get feedback. It should be easy to run:
- runValkyrieWalking, runValkyrieBalance and runValkyrieBalancePerturb

So, where should this live? 
@RussTedrake : you mentioned putting this in a separate examples repo before like littledog?

### CODE REVIEW

**Comment by patmarion** [comment]
awesome!

**Comment by rdeits** [comment]
wow, that's great!!

**Comment by RussTedrake** [comment]
So awesome!  (if only the real robot will work as easily :)

How big are the cad files?  With both of our groups planning to work hard on it, it might make sense to make it a full fleged example in drake, right next to Atlas.



On November 24, 2015 at 2:58:28 PM, Maurice Fallon (notifications@github.com) wrote:

I've been able to make Val walk & balance in drake, basically by modifying all the Atlas example code where needed and making a few small changes to drake/systems where things were not generalized fully.

the only robot-specific changes I made were to move the LIP z-height ... which means that the walking controller was really well written. Kudos ;)
(Though the Valkyrie model is similar in stucture to Atlas.)

Here's one video:
https://www.dropbox.com/s/bk070em5v6cqx5f/walkingA.m4v?dl=0
And a number of others for balancing and other tests are here:
https://www.dropbox.com/sh/ccquv2map95vvms/AAC-fJHa3Ij0S2DTJUL7brl1a?dl=0

I'm creating a pull request, but mostly to get feedback. It should be easy to run:

runValkyrieWalking, runValkyrieBalance and runValkyrieBalancePerturb
So, where should this live?
@RussTedrake : you mentioned putting this in a separate examples repo before like littledog?

You can view, comment on, or merge this pull request online at:

  https://github.com/RobotLocomotion/drake/pull/1468

Commit Summary

adding val directory, a start
changes to val to make it walk as atlas
changes to drake to switch robots
walking working with Atlas on this commit
adding valkyire model without modification
minor
rename torso
legs
arms
another fix
changes allow atlas as valkyrie balancing to work
rename joints except neck
balancing test works
valkyrie walks just fine in drake
got a few more examples working
adding Valkyrie into search path
Val desc uses obj and wrl
rm old data
use fp locally
revert name changes
changes to walk and balance with Valkyrie with correct joint names
resetting torque limits, walking still works fine
make modifications to valkyrie more obvious
adding 'original' valkyrie urdf
rm cruft
File Changes

M drake/examples/CMakeLists.txt (3)
A drake/examples/Valkyrie/+valkyrieControllers/@InstantaneousQPController/InstantaneousQPController.m (155)
A drake/examples/Valkyrie/+valkyrieControllers/BodyMotionControlBlock.m (141)
A drake/examples/Valkyrie/+valkyrieControllers/FootContactBlock.m (246)
A drake/examples/Valkyrie/+valkyrieControllers/IKPDBlock.m (159)
A drake/examples/Valkyrie/+valkyrieControllers/QPInputConstantHeight.m (90)
A drake/examples/Valkyrie/+valkyrieControllers/QTrajEvalBlock.m (106)
A drake/examples/Valkyrie/+valkyrieControllers/RobotiqControlBlock.m (46)
A drake/examples/Valkyrie/+valkyrieControllers/ValkyriePlanEval.m (24)
A drake/examples/Valkyrie/+valkyrieControllers/ValkyriePlanEvalAndControlSystem.m (123)
A drake/examples/Valkyrie/+valkyrieFrames/BodySpatialAcceleration.m (15)
A drake/examples/Valkyrie/+valkyrieFrames/COMAcceleration.m (10)
A drake/examples/Valkyrie/+valkyrieFrames/COMState.m (10)
A drake/examples/Valkyrie/+valkyrieFrames/FootContactState.m (8)
A drake/examples/Valkyrie/+valkyrieFrames/HandInput.m (16)
A drake/examples/Valkyrie/+valkyrieFrames/HandState.m (14)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieBody.m (10)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieCoordinates.m (11)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieForceTorque.m (16)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieInput.m (17)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieJointConfig.m (25)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyriePositionRef.m (13)
A drake/examples/Valkyrie/+valkyrieFrames/ValkyrieState.m (19)
A drake/examples/Valkyrie/+valkyrieParams/Base.m (114)
A drake/examples/Valkyrie/+valkyrieParams/Manip.m (11)
A drake/examples/Valkyrie/+valkyrieParams/PositionControl.m (13)
A drake/examples/Valkyrie/+valkyrieParams/Recovery.m (10)
A drake/examples/Valkyrie/+valkyrieParams/Standing.m (10)
A drake/examples/Valkyrie/+valkyrieParams/Walking.m (50)
A drake/examples/Valkyrie/+valkyrieParams/getDefaults.m (9)
A drake/examples/Valkyrie/+valkyrieUtil/getHardwareJointNames.m (105)
A drake/examples/Valkyrie/+valkyrieUtil/plotWalkingTraj.m (170)
A drake/examples/Valkyrie/+valkyrieUtil/propertyCache.m (68)
A drake/examples/Valkyrie/+valkyrieUtil/simulateWalking.m (35)
A drake/examples/Valkyrie/CMakeLists.txt (7)
A drake/examples/Valkyrie/Valkyrie.m (314)
A drake/examples/Valkyrie/ValkyrieAnkleXYJointLimitConstraint.m (25)
A drake/examples/Valkyrie/data/valkyrie_fp_june2015_30joints_one_neck.mat (0)
A drake/examples/Valkyrie/generateRandomBoxWorld.m (130)
A drake/examples/Valkyrie/package.xml (0)
A drake/examples/Valkyrie/robotiqHandInspector.m (7)
A drake/examples/Valkyrie/runCOMFixedPointSearch.m (223)
A drake/examples/Valkyrie/runDRCDoorTask.m (74)
A drake/examples/Valkyrie/runDRCPracticeTerrain.m (71)
A drake/examples/Valkyrie/runRobotiqPDControl.m (30)
A drake/examples/Valkyrie/runRobotiqTendons.m (22)
A drake/examples/Valkyrie/runValkyrieBalancing.m (97)
A drake/examples/Valkyrie/runValkyrieBalancingMultiContact.m (85)
A drake/examples/Valkyrie/runValkyrieBalancingPerturb.m (108)
A drake/examples/Valkyrie/runValkyrieBalancingWithContactSensor.m (107)
A drake/examples/Valkyrie/runValkyrieDynamics.m (30)
A drake/examples/Valkyrie/runValkyrieFootstepPlanning.m (37)
A drake/examples/Valkyrie/runValkyrieFrontalDynamics.m (21)
A drake/examples/Valkyrie/runValkyrieHandControl.m (177)
A drake/examples/Valkyrie/runValkyrieJumping.m (352)
A drake/examples/Valkyrie/runValkyrieManip.m (126)
A drake/examples/Valkyrie/runValkyrieRunning.m (323)
A drake/examples/Valkyrie/runValkyrieSagittalDynamics.m (21)
A drake/examples/Valkyrie/runValkyrieStepRecovery.m (150)
A drake/examples/Valkyrie/runValkyrieWalking.m (82)
A drake/examples/Valkyrie/runValkyrieWalkingPlanning.m (87)
A drake/examples/Valkyrie/sdf/README.txt (6)
A drake/examples/Valkyrie/sdf/block_angle_steps_1/CMakeLists.txt (8)
A drake/examples/Valkyrie/sdf/block_angle_steps_1/model.config (17)
A drake/examples/Valkyrie/sdf/block_angle_steps_1/model.rsdf (69)
A drake/examples/Valkyrie/sdf/block_angle_steps_1/model.sdf (1434)
A drake/examples/Valkyrie/sdf/block_angle_steps_2/CMakeLists.txt (8)
A drake/examples/Valkyrie/sdf/block_angle_steps_2/model.config (17)
A drake/examples/Valkyrie/sdf/block_angle_steps_2/model.rsdf (69)
A drake/examples/Valkyrie/sdf/block_angle_steps_2/model.sdf (995)
A drake/examples/Valkyrie/sdf/block_level_steps_1/CMakeLists.txt (8)
A drake/examples/Valkyrie/sdf/block_level_steps_1/model.config (17)
A drake/examples/Valkyrie/sdf/block_level_steps_1/model.rsdf (45)
A drake/examples/Valkyrie/sdf/block_level_steps_1/model.sdf (659)
A drake/examples/Valkyrie/sdf/block_level_steps_2/CMakeLists.txt (8)
A drake/examples/Valkyrie/sdf/block_level_steps_2/model.config (17)
A drake/examples/Valkyrie/sdf/block_level_steps_2/model.rsdf (45)
A drake/examples/Valkyrie/sdf/block_level_steps_2/model.sdf (419)
A drake/examples/Valkyrie/sdf/cinder_block_2/materials/textures/cinder_block.png (0)
A drake/examples/Valkyrie/sdf/cinder_block_2/meshes/cinder_block.dae (184)
A drake/examples/Valkyrie/sdf/cinder_block_2/meshes/cinder_block.obj (173)
A drake/examples/Valkyrie/sdf/cinder_block_2/meshes/cinder_block.obj.mtl (14)
A drake/examples/Valkyrie/sdf/cinder_block_2/model-1_4.sdf (140)
A drake/examples/Valkyrie/sdf/cinder_block_2/model.config (18)
A drake/examples/Valkyrie/sdf/cinder_block_2/model.sdf (167)
A drake/examples/Valkyrie/sdf/cinder_block_wide/meshes/cinder_block_wide.dae (253)
A drake/examples/Valkyrie/sdf/cinder_block_wide/meshes/cinder_block_wide.obj (173)
A drake/examples/Valkyrie/sdf/cinder_block_wide/meshes/cinder_block_wide.obj.mtl (13)
A drake/examples/Valkyrie/sdf/cinder_block_wide/model.config (17)
A drake/examples/Valkyrie/sdf/cinder_block_wide/model.sdf (58)
A drake/examples/Valkyrie/sdf/drc_practice_task_2.world (0)
A drake/examples/Valkyrie/sdf/ground_plane/model-1_2.sdf (0)
A drake/examples/Valkyrie/sdf/ground_plane/model-1_3.sdf (0)
A drake/examples/Valkyrie/sdf/ground_plane/model-1_4.sdf (0)
A drake/examples/Valkyrie/sdf/ground_plane/model.config (0)
A drake/examples/Valkyrie/sdf/ground_plane/model.sdf (0)
A drake/examples/Valkyrie/sdf/sun/model-1_2.sdf (0)
A drake/examples/Valkyrie/sdf/sun/model-1_3.sdf (0)
A drake/examples/Valkyrie/sdf/sun/model-1_4.sdf (0)
A drake/examples/Valkyrie/sdf/sun/model.config (0)
A drake/examples/Valkyrie/sdf/sun/model.sdf (0)
A drake/examples/Valkyrie/test/multiRobotTest.m (0)
A drake/examples/Valkyrie/test/runAtlasFastBackwardWalking.m (0)
A drake/examples/Valkyrie/test/runAtlasTurning.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingDownStairs.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingHeelSupport.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingNarrowStairs.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingStairs.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingTestWraparound.m (0)
A drake/examples/Valkyrie/test/runAtlasWalkingTiltedBlocks.m (0)
A drake/examples/Valkyrie/test/runDRCDrillTask.m (0)
A drake/examples/Valkyrie/test/runDRCValveTask.m (0)
A drake/examples/Valkyrie/test/runDoubleAtlas.m (0)
A drake/examples/Valkyrie/test/runHandContactSensorTest.m (0)
A drake/examples/Valkyrie/test/runValkyrieFastWalking.m (0)
A drake/examples/Valkyrie/test/runValkyrieTurning270.m (0)
A drake/examples/Valkyrie/test/singleJointParameterEstimation.m (0)
A drake/examples/Valkyrie/test/testCollisionVolumes.m (0)
A drake/examples/Valkyrie/test/testHybridMode.m (0)
A drake/examples/Valkyrie/test/testKin.m (0)
A drake/examples/Valkyrie/test/testKin2.m (0)
A drake/examples/Valkyrie/test/testKneeSingularity.m (0)
A drake/examples/Valkyrie/test/testMex.m (0)
A drake/examples/Valkyrie/test/testRunningPlanner.m (0)
A drake/examples/Valkyrie/urdf/model/materials/materials.xacro (0)
A drake/examples/Valkyrie/urdf/model/materials/textures/CMakeLists.txt (0)
A drake/examples/Valkyrie/urdf/model/materials/textures/drc_extremities_diffuse.jpg (0)
A drake/examples/Valkyrie/urdf/model/materials/textures/drc_labels_1.jpg (0)
A drake/examples/Valkyrie/urdf/model/materials/textures/drc_torso_head_diffuse.jpg (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/Material Diffuse Color.001.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/Material.001 Diffuse Color.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/PalmTexture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj1_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2Texture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj2_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3Texture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj3_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4Texture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj4_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5Texture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj5_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/aj6_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/palm_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/arms/whiteTexture.png (0)
A drake/examples/Valkyrie/urdf/model/meshes/chull-simple.mlx (0)
A drake/examples/Valkyrie/urdf/model/meshes/chull.mlx (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj1_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj2_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/indexj3_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej1_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej2_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/middlej3_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj1_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj2_right.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_left.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_left.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_left.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_left.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_left.wrl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_right.dae (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_right.obj (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_right.stl (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_right.vtp (0)
A drake/examples/Valkyrie/urdf/model/meshes/fingers/pinkyj3_right.wrl (0)
I drake/examples/Valkyrie/urdf/model/meshes/fingers/thumbj1_left.dae (0)
Patch Links:

https://github.com/RobotLocomotion/drake/pull/1468.patch
https://github.com/RobotLocomotion/drake/pull/1468.diff

**Comment by mauricefallon** [comment]
Drake & the director read a variety of file formats:
- dae (original)
- vtp (needed by the director)
- wrl (needed by drake itself)
- obj (needed by the director but not used. @patmarion : do you know why? )
In total its about 7mb plus 4mb of textures.
Atlas is 15mb of meshes plus 28mb of textures.

That seems reasonable. Shall I start by adding the model with a simple BotVisualiser of the urdf and go from there?

**Comment by patmarion** [comment]
I'll provide some background on the meshes:

dae: original files, collada file format.  XML format, but you need to use a collada parser c++ or python library to read these.  Stores mesh data as ascii.  A single dae file may store more than one mesh, including transforms, and filename references one or more texture image file.

vtp: I wrote a python script to parse collada files and generate equivalent VTK data structures which are saved as vtp file format.  Binary compressed.  The largest .dae file for Atlas is 1.1 MB, the .vtp file is 144 KB.  The vtp preserves all mesh data and texture information.

wrl: We use a meshlab script to open the dae file and output wrl.  Ascii data. Some information like texture coordinates are lost during conversion.

obj: We use a meshlab script to open the dae file and output obj.  While .obj files can reference .mtl material files that store texture filename references, we don't have this.  Our obj files are missing texture coords, lost during conversion.

chull.{obj,wrl}: A meshlab script computes a convex hull and saves a chull file in wrl and obj format.

urdf:  Our urdf files visual elements reference .obj files and collision elements reference _chull.obj files.  The director searches for equivalent files with .vtp extension and loads the .vtp if they exist.  Director does not load collision elements (but I'd like to add this in the future!)  ?? Matlab reads the .obj files, or searches for equivalent files with .wrl extension and reads those ??

**Comment by patmarion** [comment]
Note: the Atlas meshes and urdf are forked to two places:  one copy in openhumanoids, one copy in drake/examples.  I'm not sure about drake, but for openhumanoids we have a script that takes the osrf original and applies all our patches and conversions to output the files we use in our system.

**Comment by psiorx** [comment]
>  I'm not sure about drake, ...

We're also using the output of the patching scripts for Drake Atlas.

**Comment by mauricefallon** [comment]
Yes, the drake version is slightly different from the openhumanoids version, but from the scripts.
It doesn't have the very latest changes e.g. butt contact points.

That's what we would do with Valkyrie also, where NASA provide the original.

**Comment by RussTedrake** [comment]
Drake used wrl to support the vrnl vidualizer that ships with Matlab.  Now that director works on all platforms, maybe we can axe the vrml viewer dependency - it doesn't support everything anyways.  Are there any other pieces that actually need the wrl files?

**Comment by mauricefallon** [comment]
One of the Atlas tests uses the native matlab plotting for a 2D test (runAtlasSaggitalDynamics). Probably a very old test that could be adapted to the director.

I'll add Val without wrl files and we can see which of the adapted Atlas tests need them.

**Comment by avalenzu** [comment]
Re. Drake Atlas urdf: if I recall correctly, the drake Atlas urdf is a
snapshot of one of the DRC urdfs. There's nothing ensuring that they stay
in sync

**Comment by RussTedrake** [comment]
awesome that this is coming.  my understanding is that it will be coming in the new pull requests, and that this one should be closed?

**Pull request closed without merging**
