### PR TITLE
Add issue number citations to broken-out cpplint suppressions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For reference, only the cpplint jenkins needs to pass before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2368) &emsp; Multiple assignees:&emsp;@sammy-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sammy-tri">sammy-tri</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri feature review.
+@sherm1 platform review.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> #### Add issue number citations to broken\-out cpplint suppressions
> 
> For reference, only the cpplint jenkins needs to pass before merging.
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2368#-:-KHuZKPEAbG8x-i3nQWv:-1053939969)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@sammy-tri feature review.
> +@sherm1 platform review.</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2368#-:-KHudYPjn1QKN3x-8s8i:1058782226)*

**Comment by sammy-tri** [comment]
:lgtm:

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Platform review: :lgtm:</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2368#-:-KHueFyjD0QgKWptKyq8:1417088721)*

**Comment by jwnimmer-tri** [comment]
Branch is "out of date with master".  The jenkins cpplint passed, the other jenkins are still in progress.  Using override-merge to get around those two interlocks.

**Pull request merged**
