### PR TITLE
Create @package//:package targets when using pkg_config_package, etc.

### PR DESCRIPTION
**Pull request by jamiesnape**
Discussed briefly in #6152.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6217)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6217#-:-KlWOUKeP7xP1lDAHbf0:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@soonho-tri for platform review.

**Comment by soonho-tri** [comment]
:lgtm:

FYI, @kunimatsu-tri , now you can just use `@zlib`.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6217#-:-KlYv6-rFF3KkhjfQQVj:buwadyj)*

**Pull request merged**
