### PR TITLE
Fixed bug in urdf_parser that resulted in RPY floating joint always being used.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4248)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXIERr-c6_pdt-CvleM:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. My plan is to add a unit test to this PR before merging.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXIWvkIcRRY5sgmWY1F:b5011rv)*

**Comment by liangfok** [comment]
I added the unit test.

+@sherm1 for feature review please.
+@david-german-tri for platform review please.

Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXm0cGEKJI_CBja0SOP:b5e2wxa)*

**Comment by david-german-tri** [comment]
:lgtm: aside from the cpplint

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXmKTbtBV29CGlEByAb:b3nin14)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/test/parser_urdf_test/parser_urdf_test.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-KXmN3GejwJbYUuJttU1:-KXmN3GejwJbYUuJttU2:b-aic0qr) ([raw file](https://github.com/robotlocomotion/drake/blob/8e792ce66be281d9d8c0fa369f305c208f25639b/drake/multibody/test/parser_urdf_test/parser_urdf_test.cc#L7)):*
> ```cpp
> #include <memory>
> #include <string>
> #include <memory>
> ```

BTW, "memory" included twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXmNVmgzIz6_1nUaMja:bnfp4nl)*

**Comment by liangfok** [comment]
Thanks. I've addressed all reviewer comments and am now waiting for CI to complete.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/test/parser_urdf_test/parser_urdf_test.cc, line 7 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-KXmN3GejwJbYUuJttU1:-KXmovhUsTV-2S9lDt8G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8e792ce66be281d9d8c0fa369f305c208f25639b/drake/multibody/test/parser_urdf_test/parser_urdf_test.cc#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, "memory" included twice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4248#-:-KXmoy-UYGeodJlChVi5:b-1oy98l)*

**Pull request merged**
