### PR TITLE
SpatialInertia support for massless bodies.

### PR DESCRIPTION
**Pull request by amcastro-tri**
Massless bodies are commonly defined in URDF/SDF models as a proxy for "frames". Algorithms such at the Composite Body Inertia for computing the mass matrix fail if the user provides a kinematic chain of massless bodies. This use case is so common that we decided to support it. 
This PR allows combining the spatial inertia for massless bodies, solving the issue with kinematic chains of massless bodies.

cc'ing @mitiguy 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12809)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1bcmpZ6hY_iqhFFxF0:b-b70jbp) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd need help with that. @jwnimmer-tri? 
also, would there be any impact on performance for `double` when using those?
</blockquote></details>

The search term is `drake::if_then_else`, similar to the ternary operator.

For example:
```c++
const T total_mass = get_mass() + M_BP_E.get_mass();
p_PScm_E_ = if_then_else(
    (total_mass != 0),
    (CalcComMoment() + M_BP_E.CalcComMoment()) / total_mass,
    0.5 * (get_com() + M_BP_E.get_com()));
```

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1bdLkgAd3pfBqyptRJ:blg3de7) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The search term is `drake::if_then_else`, similar to the ternary operator.

For example:
```c++
const T total_mass = get_mass() + M_BP_E.get_mass();
p_PScm_E_ = if_then_else(
    (total_mass != 0),
    (CalcComMoment() + M_BP_E.CalcComMoment()) / total_mass,
    0.5 * (get_com() + M_BP_E.get_com()));
```
</blockquote></details>

On the other hand, you can choose to disallow mass being a symbolic variable (instead always being a literal) in which case this code is fine as-is.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1c7Txw7zOC3TzXmsrZ:bssc4h4) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
> Oh, doesn't that evaluate both arguments though ...

Depends on how much you trust your compiler.  All of the functions being called seem like they are inline, so it could plausibly do the right thing.  It also seems like Alejandro has a benchmark, so it should be easy to check whether or not it matters.

I still lean towards "don't borrow trouble" though.  Given that no tests fail, for my part I don't see the current implemenation as a defect.

> I thought you had developed a way to create an if_then_else that works like ?: when instantiated with double?

You might be thinking of #11243, which was abandoned for lack of need vs bikeshedding.

**Comment by sherm1** [comment]
Oh, yeah that's what I was thinking of. Your last comment there:
> I think my next step here when I pick it up again will be to find more use cases throughout the code so that we have more data points to evaluate syntax options.

Here's one! :)

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1f_1Mt7B11y-AtXM_4:b-bqftwm) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

No, how about just a TODO noting that this doesn't support symbolic? It could be addressed with enable_if's if we need to.
</blockquote></details>

It _does_ support symbolic.  The template instantiation proves that it compiles.  It does not support a mass being set to a free Variable at runtime.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1flqppBy0pwlzMq6oc:b-ukfj6a) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

So if the mass is a constant in the symbolic expression the code will work. But if the masses are set to "m1" and "m2", say (which wouldn't be surprising in a symbolic expansion!), what will happen? 
</blockquote></details>

It will throw an exception while converting the Formula to bool:

https://github.com/RobotLocomotion/drake/blob/69b000040cfc115385d254a2c25cf7d4915561a5/common/symbolic_expression_cell.cc#L327-L332

**Comment by jwnimmer-tri** [comment]
___
*[multibody/tree/spatial_inertia.h, line 287 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12809#-M1bQs4KBtcHGWz1ePtG:-M1fmUMb1tkmZl8JVFDn:b-omppx2) ([raw file](https://github.com/robotlocomotion/drake/blob/f18a290d407c33bece6c7bfad538fd2803daa6ad/multibody/tree/spatial_inertia.h#L287)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It will throw an exception while converting the Formula to bool:

https://github.com/RobotLocomotion/drake/blob/69b000040cfc115385d254a2c25cf7d4915561a5/common/symbolic_expression_cell.cc#L327-L332
</blockquote></details>

(In symbolic plant usage so far, often the _q_ are variables, but lengths and masses and the like are still constants from the SDF file or what have you.)

**Pull request merged**
