### PR TITLE
pydrake: Override NiceTypeName::Get(ptr) when possible

### LINKED ISSUE #13237: py systems: Should make make debug messages with NiceTypeName prettier for Python?
Issue-ifying #13194. [See discussion](https://github.com/RobotLocomotion/drake/pull/13194#pullrequestreview-403981032)

Motivated by the error encountered here:
https://stackoverflow.com/q/61506822/7829525

> The goal is to turn this message:
> ```
> Traceback (most recent call last):
>   File "debugging.py", line 24, in <module>
>     DirectTranscription(sys, sys.CreateDefaultContext(), 10)
> RuntimeError: The object named [] of type drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem does not support ToAutoDiffXd.
> ```
> into this message:
> ```
> Traceback (most recent call last):
>   File "debugging.py", line 24, in <module>
>     DirectTranscription(sys, sys.CreateDefaultContext(), 10)
> RuntimeError: The object named [] of type my_module.CustomVectorSystem does not support ToAutoDiffXd.
> ```
> 
> The actual type name `drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem` is rather uninformative (aside from being ugly) if you have a  diagram with multiple Python-authored systems that you're trying to convert. (They'll all look the same.)

\cc @sherm1 @jwnimmer-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #13237

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13194)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
The goal is to turn this message:
```
Traceback (most recent call last):
  File "debugging.py", line 24, in <module>
    DirectTranscription(sys, sys.CreateDefaultContext(), 10)
RuntimeError: The object named [] of type drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem does not support ToAutoDiffXd.
```
into this message:
```
Traceback (most recent call last):
  File "debugging.py", line 24, in <module>
    DirectTranscription(sys, sys.CreateDefaultContext(), 10)
RuntimeError: The object named [] of type my_module.CustomVectorSystem does not support ToAutoDiffXd.
```

The actual type name `drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem` is rather uninformative if you have a  diagram with multiple Python-authored systems that you're trying to convert. (They'll all look the same.)

The meta-programming stuff can be discarded, as long as all attempts to get type names for Systems use `.GetSystemType()`.

**Comment by sherm1** [comment]
Ah, that does look better. Does "__custom__" get replaced with the nice name somehow?

There is another glaring fault in the message:
```
The object named [] of type my_module.CustomVectorSystem 
does not support ToAutoDiffXd.
```
"The objected named []" is not very helpful. I feel that's a fault with our API that does not encourage systems to be created with names.

> The meta-programming stuff can be discarded, as long as all attempts to get type names for Systems use .GetSystemType().

If that's enough it seems like a very reasonable way to go.

**Comment by jwnimmer-tri** [comment]
Let's pause and consider the broader situation as well.  When we have runtime type errors in C++ where the user did something wrong, we report the NiceTypeName of the most derived runtime type in the error message to help them out.

However, when the instances were created via Python subclassing, the `typeid(expression)` is not the correct way to report the most derived runtime type.

While we could solve this _only_ for subclasses of SystemBase, I wonder if its worth pausing for a moment to figure out if we could solve for all drake <=> pydrake interactions, not just systems.

If the `Get(thing)` overload of NiceTypeName will be lies so often, we should ideally either make it stop lying or else remove it entirely.

**Comment by EricCousineau-TRI** [comment]
> If the Get(thing) overload of NiceTypeName will be lies so often, we should ideally either make it stop lying or else remove it entirely.

Aye, I think one way to make it stop lying is to make it "overridable" per the meta-programming mess I added, and enforce it in other things (e.g. `AbstractValue`, by implementing it for `Value<py::object>`).
Not sure if there's a more general way to do things.

If we remove it, I feel like that's a step backwards?

**Comment by sherm1** [comment]
I do like `Get(thing)` and would be in favor of having it always work nicely! I don't understand enough about what's going on with the Python type names to be of much help, and maybe I'm being an impediment instead by complaining about the metaprogramming.

**Comment by EricCousineau-TRI** [comment]
Eh, I wouldn't see it as an impediment. I think we should do proper cost / benefit for excessively "cute" things like this.

For the Python stuff, can I ask which part is unclear? I'd be happy to explain it more.

**Comment by jwnimmer-tri** [comment]
I don't think static SFINAE overriding (the current customization point) will work for what is essentially runtime type information.  I think we need a runtime inversion of control to dispatch pydrake types into pydrake's control flow.

**Comment by EricCousineau-TRI** [comment]
I guess I'm not sure how what that runtime inversion of control could look like.

Something like a global that says:
```
NiceTypeName::RegisterRedirect(std::type_info, std::function<std::string (void*)>)
```
and then some shindig like this?
```
string NiceTypeName::Get(const T& thing) {
  if (auto redirect = CanHazRedirect(typeinfo(T))) {
    return redirect(&thing);
  }
}
```

**Comment by jwnimmer-tri** [comment]
I'd start with https://github.com/RobotLocomotion/drake/blob/e176344dcdcb52abfc2002d4c2c3437bf474ed2c/common/drake_assert_and_throw.cc#L82-L87 as the model for how pydrake installs itself into `//common` library control flow.  It's an internal function branded as "for use only by pydrake, to be called exactly once during pydrake init".  Here we'd install a callback on the singleton, instead of just setting a boolean.

Then, the heuristic in NiceTypeName's cc file is something like "Compute the string typename as normal.  If it starts with `"pydrake::"`, then delegate to the installed callback.  Pass the `const type_info&` and `const void* thing` into the callback.  Look up the actual python type name on the receiving end.

**Comment by EricCousineau-TRI** [comment]
A global boolean sounds good to me.

As far as implementations is concerned, I'd prefer something more explicit (e.g. registration), rather than first getting the nice type name, then parsing. Will try that out!

**Comment by EricCousineau-TRI** [comment]
Ah, nvm. You're type-erased approach seems most general, though `type_info` + `void*` is private API in `pybind11` (though we've already dug into other internals from `pydrake` :P)

**Comment by EricCousineau-TRI** [comment]
Bumping priority to medium; saw it some more places, would be nice to have the error messages more readable.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
CI needs some attention.

Also, it's not important but FYI -- I have a slight personal preference that "commits are property curated" PRs are always rebased to tip before merging, so that we have linear history even with >1 commit per PR.  If you could rebase to tip of master when fixing CI, I'd appreciate it!  (Or maybe you're going to squash anyway.)

**Comment by jwnimmer-tri** [comment]
> ...if we want linear history, why not enable rebasing so that we're guaranteed linearity, and disable merging?

Some arcane PRs (such as "fork h file into h and cc") require merge commits to preserve history; rebasing would defeat them.  We could try to deal with them separately with admin permissions, but since basically only you and I curate our commits anyway, having us rebase locally out of habit seemed easier.  (It's also not a big deal in the first place; it just makes gitk ugly and bisecting somewhat more difficult to following along.)

**Pull request merged**
