### PR TITLE
Python style -- assorted cleanups.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This PR cleans up the remaining PEP8 (and in a few cases, PEP257) issues in checked-in drake python files, neglecting **/dev/ and thirdParty/.  These changes clear the way to (limited) automated checking of python style.

I have done my best to limit the changes to mechanical white-space and comment changes only.

These are mostly files with which I am unfamiliar -- if any are obsolete and/or better deleted than maintained, let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4962)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-:-KbkaWiKnD0hgLJU-z4A:b-3f2dwx)*

**Comment by rpoyner-tri** [comment]
+@sammy-tri for feature review please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-:-KblKrWTHNwqrR9FGiXI:bjquaum)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-:-KblTzoSmcLdq4p6c-kW:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
+@jwnimmer-tri for platform review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-:-Kboq415WdtFqJL-m4oj:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/test_urdf_parser.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-Kbp3maruvYJuTXGWMJV:-Kbp3mastXE7iziMj-vu:b-4w4twu) ([raw file](https://github.com/robotlocomotion/drake/blob/338b907ec4a737896d1810e332cb986cf0d1a5a1/drake/bindings/python/pydrake/test/test_urdf_parser.py#L7)):*
> ```Python
> 
> class TestUrdfParser(unittest.TestCase):
>     """Test that an instance of a URDF model can be loaded into a
> ```

BTW I am suspicious of what the "Tests" vs "Test" might imply for a coding standard rule.  Is that change coming from a coding standard?  Otherwise I think it was better the way it was?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-:-Kbp40B0YAh9GmRh9p4n:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/test_urdf_parser.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-Kbp3maruvYJuTXGWMJV:-Kbp55kRwYKWJXKGSw70:bx71jf8) ([raw file](https://github.com/robotlocomotion/drake/blob/338b907ec4a737896d1810e332cb986cf0d1a5a1/drake/bindings/python/pydrake/test/test_urdf_parser.py#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I am suspicious of what the "Tests" vs "Test" might imply for a coding standard rule.  Is that change coming from a coding standard?  Otherwise I think it was better the way it was?
</blockquote></details>

That change was on advice of PEP 257. If you think it is detrimental in this case, I can withdraw the change and/or clarify the advice from PEP 257.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962)*

**Comment by jwnimmer-tri** [comment]
*[drake/bindings/python/pydrake/test/test_urdf_parser.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-Kbp3maruvYJuTXGWMJV:-KbpPWJCbKYxCGnNi0U7:b-2htv39) ([raw file](https://github.com/robotlocomotion/drake/blob/338b907ec4a737896d1810e332cb986cf0d1a5a1/drake/bindings/python/pydrake/test/test_urdf_parser.py#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

That change was on advice of PEP 257. If you think it is detrimental in this case, I can withdraw the change and/or clarify the advice from PEP 257.
</blockquote></details>

Have we had the discussion of whether we want C++ and Python to have different grammar rules?  If so and we've decided "yes" then this change is correct.  If not, let's have that discussion first and then fixups second.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962)*

**Comment by rpoyner-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/test_urdf_parser.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-Kbp3maruvYJuTXGWMJV:-Kbq8H6oH7PiE0nCGfLV:b-lh89fl) ([raw file](https://github.com/robotlocomotion/drake/blob/338b907ec4a737896d1810e332cb986cf0d1a5a1/drake/bindings/python/pydrake/test/test_urdf_parser.py#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Have we had the discussion of whether we want C++ and Python to have different grammar rules?  If so and we've decided "yes" then this change is correct.  If not, let's have that discussion first and then fixups second.
</blockquote></details>

I explicitly called out PEP 257 when presenting https://github.com/RobotLocomotion/drake/pull/4663 . Was that not enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/bindings/python/pydrake/test/test_urdf_parser.py, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4962#-Kbp3maruvYJuTXGWMJV:-KbqJi8CQFAA6uSG6LhY:b-hj3hn5) ([raw file](https://github.com/robotlocomotion/drake/blob/338b907ec4a737896d1810e332cb986cf0d1a5a1/drake/bindings/python/pydrake/test/test_urdf_parser.py#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I explicitly called out PEP 257 when presenting https://github.com/RobotLocomotion/drake/pull/4663 . Was that not enough?
</blockquote></details>

Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4962)*

**Pull request merged**
