### PR TITLE
Upgrade Externals July 2023

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #19715

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19773)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@EricCousineau-TRI for review please. The two "pending" jobs passed, I'm not sure why their status didn't update.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19773#-:-N_FvXou0aSLOscTcbNq:b1hmcso)* status: LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both reviews +@jwnimmer-tri -@EricCousineau-TRI .

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19773#-:-N_G72_T20rR-jbDIa5M:bcgln7d)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), base commit is latest master

___
*[`tools/workspace/qdldl_internal/repository.bzl` line 13 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/19773#-N_G6r-4AJvNsBJ_T7Jb:-N_G6r-4AJvNsBJ_T7Jc:bx59ulm) ([raw file](https://github.com/RobotLocomotion/drake/blob/36048bb8972bc01dff6b913e6995570c8eea3e3c/tools/workspace/qdldl_internal/repository.bzl#L13)):*
> ```Starlark
>         """,
>         commit = "v0.1.7",
>         sha256 = "631ae65f367859fa1efade1656e4ba22b7da789c06e010cceb8b29656bf65757",  # noqa
> ```

FYI The I had to check to see if this was OK (per the README.md noted above).  I think it's fine, because 0.1.6 and 0.1.7 differ only in a few CMake typo fixes that we don't care about.  So we might as well take the upgrade to stop `new_release` from continually suggesting it.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19773)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform), base commit is latest master

___
*[`tools/workspace/qdldl_internal/repository.bzl` line 13 at r11](https://reviewable.io/reviews/RobotLocomotion/drake/19773#-N_G6r-4AJvNsBJ_T7Jb:-N_G8KLmESwKE6pT6fVV:be14xbn) ([raw file](https://github.com/RobotLocomotion/drake/blob/36048bb8972bc01dff6b913e6995570c8eea3e3c/tools/workspace/qdldl_internal/repository.bzl#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The I had to check to see if this was OK (per the README.md noted above).  I think it's fine, because 0.1.6 and 0.1.7 differ only in a few CMake typo fixes that we don't care about.  So we might as well take the upgrade to stop `new_release` from continually suggesting it.
</blockquote></details>

Thanks, I completely missed that note when updating

**Pull request merged**
