### PR TITLE
Add ParseL2NormCosts.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This will be used for Clarabel and SCS.

As a step towards resolving #20552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-:-Nu2kCsl4aLpseM13qKG:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-:-NuPjt9d0SViigJRkKZR:bg7igkv)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOzLLnDIm5kUX2Hbwf:-NuOzLLnDIm5kUX2Hbwg:b-n6l2z0) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L208)):*
> ```objc
> // @param[in/out] A_triplets We append the second order cone constraints to
> // A_triplets.
> // @param[in/out] b We append the second order cone constraints to b.
> ```

These could use some clarifying. I believe you mean you append the linear constraints of the reformulation to these?



_Code quote:_
```objc
// @param[in/out] A_triplets We append the second order cone constraints to
// A_triplets.
// @param[in/out] b We append the second order cone constraints to b.
```
___
*[`solvers/aggregate_costs_constraints.h` line 212 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOzXrY6VWcZ9PZWTSD:-NuOzXrY6VWcZ9PZWTSE:bq44nm9) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L212)):*
> ```objc
> // order cone constraints.
> // @param[in/out] second_order_cone_length The lengths of each second order cone
> // s in K in the Cartesian product K.
> ```

suggestion:



_Suggestion:_
```objc
// @param[in/out] second_order_cone_length The dimension of each second order cone in the overall program.
```
___
*[`solvers/aggregate_costs_constraints.h` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOznYJ5jbdyPoXEGiH:-NuOznYJ5jbdyPoXEGiI:b-yy19bj) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L216)):*
> ```objc
> // constraint to lorentz_cone_y_start_indices.
> // @param[out] cost_coeffs The coefficient of each variable in the cost.
> // @param[out] t_slack_indices The index of the new variable t in the solver
> ```

This is a bit unclear from the docstring. I think I can anticipate what you mean, but the "in the solver" bit is confusing.



_Code quote:_
```objc
// @param[out] t_slack_indices The index of the new variable t in the solver
```
___
*[`solvers/aggregate_costs_constraints.cc` line 496 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuPiZ0G3X9E3AmRL3D9:-NuPiZ0G3X9E3AmRL3DA:b-wg8q04) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.cc#L496)):*
> ```cpp
>     const VectorXDecisionVariable& x = cost.variables();
>     t_slack_indices->push_back(t_slack_count + *num_solver_variables);
>     const Eigen::SparseMatrix<double> C = cost.evaluator()->A().sparseView();
> ```

btw: meta-question about using this `sparseView()`. Would it be better to write `sparseView(1e-12)` or some other small constant? Otherwise `A_triplets` could end up with some ridiculously small values which could be very bad for the solver. This can happen for example if someone were obtain `C` via some sort of matrix factorization or other numerical subroutine.



_Code quote:_
```cpp
cost.evaluator()->A().sparseView();
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

___
*[`solvers/aggregate_costs_constraints.h` line 208 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOzLLnDIm5kUX2Hbwf:-NuV8W2r4JmhwqInOMEt:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L208)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

These could use some clarifying. I believe you mean you append the linear constraints of the reformulation to these?
</blockquote></details>

Done.
___
*[`solvers/aggregate_costs_constraints.h` line 212 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOzXrY6VWcZ9PZWTSD:-NuV8qfc4paFUD0DcIZh:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L212)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

suggestion:
</blockquote></details>

Done.
___
*[`solvers/aggregate_costs_constraints.h` line 216 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuOznYJ5jbdyPoXEGiH:-NuV8zM-1i_gCjAnnV1u:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.h#L216)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This is a bit unclear from the docstring. I think I can anticipate what you mean, but the "in the solver" bit is confusing.
</blockquote></details>

Done.
___
*[`solvers/aggregate_costs_constraints.cc` line 496 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuPiZ0G3X9E3AmRL3D9:-NuV9-XJ4OhtcGWDaKS2:b-k88k91) ([raw file](https://github.com/RobotLocomotion/drake/blob/fa35f5dd0c27d70705350ec05c8bca1903aa8845/solvers/aggregate_costs_constraints.cc#L496)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

btw: meta-question about using this `sparseView()`. Would it be better to write `sparseView(1e-12)` or some other small constant? Otherwise `A_triplets` could end up with some ridiculously small values which could be very bad for the solver. This can happen for example if someone were obtain `C` via some sort of matrix factorization or other numerical subroutine.
</blockquote></details>

I would rather not to filter out small entries in our wrapper. There are better place to filter out small entries, either when the user formulating the optimization program, or setting some options inside the solver (for example, Mosek can set a threshold to ignore the small values).

My general philosophy is that MathematicalProgram should converts an optimization program as faithfully as possible to the solver, then the user can tune the performance through the solver.

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-:-NuV9ZHr0nITUa8fY2RF:b-2hj6f6)* status: 4 unresolved discussions, LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-:-NuVBuZO01oRASgQ-Nn_:bnfp4nl)* status: 8 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 198 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuVC8lQEBbk89Zfe2q7:-NuVC8lQEBbk89Zfe2q8:bqjnyqe) ([raw file](https://github.com/RobotLocomotion/drake/blob/0b4e214978039ee09db9886e2688f720277192f9/solvers/aggregate_costs_constraints.h#L198)):*
> ```objc
> // 2. Impose the constraint t >= |Cx+d|₂ as a Lorentz cone constraint.
> // 3. Add the cost t.
> // For the second step, we consider to formulate it as
> ```

typo: confusing grammar.



_Suggestion:_
```objc
// For the second step, we formulate it as
```
___
*[`solvers/aggregate_costs_constraints.h` line 202 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuVCadR9ygWAkit1BtC:-NuVCadR9ygWAkit1BtD:busu8rd) ([raw file](https://github.com/RobotLocomotion/drake/blob/0b4e214978039ee09db9886e2688f720277192f9/solvers/aggregate_costs_constraints.h#L202)):*
> ```objc
> // [-C   0]   [t]       [d]
> // s is in Lorentz cone.          (2)
> // @param[in] cost The L2NormCost to parse.
> ```

There is no parameter called `cost`.
___
*[`solvers/aggregate_costs_constraints.h` line 210 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuVCl_d0dv4jtK1QhqI:-NuVCl_d0dv4jtK1QhqJ:by39203) ([raw file](https://github.com/RobotLocomotion/drake/blob/0b4e214978039ee09db9886e2688f720277192f9/solvers/aggregate_costs_constraints.h#L210)):*
> ```objc
> // @param[in/out] b We append the right hand side of linear constraints (1) to
> // b.
> // @param[in/out] The number of rows in A before/after appending the second
> ```

typo: Missing parameter name.



_Suggestion:_
```objc
// @param[in/out] A_row_count The number of rows in A before/after appending the second
```
___
*[`solvers/aggregate_costs_constraints.h` line 215 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuVCwtIBDzslInMlmlS:-NuVCwtIBDzslInMlmlT:b-xsmwr5) ([raw file](https://github.com/RobotLocomotion/drake/blob/0b4e214978039ee09db9886e2688f720277192f9/solvers/aggregate_costs_constraints.h#L215)):*
> ```objc
> // cone in the overall program.
> // @param[in/out] Append the indices of the dual variables for the Lorentz cone
> // constraint to lorentz_cone_y_start_indices.
> ```

typo:  parameter name wasn't specified.  Also this documentation makes it unclear what the `in` semantics of this parameter are.



_Suggestion:_
```objc
// @param[in/out] lorentz_cone_y_start_indices Append the indices of the dual variables for the Lorentz cone
// constraint to this parameter.
```

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204)* status: 4 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21204)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 207 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuZAfHR7xRksFWQGEaV:-NuZAfHR7xRksFWQGEaW:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/09bcb646369715a918976378b087edcd2e35a6d2/solvers/aggregate_costs_constraints.h#L207)):*
> ```objc
> // appended after the existing variables in the solver.
> // @param[in/out] A_triplets We append the left hand side of linear constraints
> // (1) to A_triplets.
> ```

nit: grammar



_Suggestion:_
```objc
// @param[in/out] A_triplets We append the left hand side of the linear constraints
// (1) to A_triplets.
```
___
*[`solvers/aggregate_costs_constraints.h` line 208 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21204#-NuZAhpD5vTAddiJoN9G:-NuZAhpD5vTAddiJoN9H:b8a9ykt) ([raw file](https://github.com/RobotLocomotion/drake/blob/09bcb646369715a918976378b087edcd2e35a6d2/solvers/aggregate_costs_constraints.h#L208)):*
> ```objc
> // @param[in/out] A_triplets We append the left hand side of linear constraints
> // (1) to A_triplets.
> // @param[in/out] b We append the right hand side of linear constraints (1) to
> ```

nit: grammar



_Suggestion:_
```objc
right hand side of the linear constraints (1) to
```

**Pull request merged**
