### PR TITLE
Minor wheel fixes

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Don't include `user.bazelrc` in the source tarball used to build wheels; it shouldn't be needed, and its inclusion results in user environment leaking into what is supposed to be a hermetic build environment. Tweak the script used to provision the wheel test containers to use `-y` when running `apt-get update`, for consistency with similar calls in other scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16290)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16290)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16290#-MsaCkMjC8gWerlxWUx-:-MsaCkMkAKSimy0YRv29:bu6rrpz) ([raw file](https://github.com/robotlocomotion/drake/blob/556116d0f31216a0a50ecee51b22b4eef0546647/tools/wheel/build-wheels#L38)):*
> ```
>     Target('37', 'ubuntu', '18.04', 'bionic'),
>     Target('38', 'ubuntu', '18.04', 'bionic'),
>     Target('38', 'ubuntu', '20.04', 'focal'),
> ```

This change isn't mentioned in the commit message, and seems undesirable in any case?

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/build-wheels, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16290#-MsaCkMjC8gWerlxWUx-:-Msamosi9vGULXxmkUnt:b-pwxla5) ([raw file](https://github.com/robotlocomotion/drake/blob/556116d0f31216a0a50ecee51b22b4eef0546647/tools/wheel/build-wheels#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This change isn't mentioned in the commit message, and seems undesirable in any case?
</blockquote></details>

Ack... sorry, I'd already noticed and fixed that locally, but apparently forgot to push. (_Eventually_ it will be desired, but not on this PR :slightly_smiling_face:.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature +(release notes: none) 

+@sherm1 for platform review per schedule, please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16290#-:-MsapH6J9utI27Gtse4L:b-adati2)* status: LGTM missing from assignee sherm1(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16290#-:-MsbjoRn241c4PhLfzBO:b8qx53o)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Pull request merged**
