### PR TITLE
NloptSolver supports setting algorithm

### PR DESCRIPTION
**Pull request by hongkai-dai**
Call SolverOptions::SetOption(NloptSolver::id(), algorithm, ALGORITHM_NAME_STRING) to set the algorithm.

Requested by the stackoverflow question https://stackoverflow.com/questions/74972952/pydrake-nlopt-method-selection

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535#-:-NKyGVDvAagNkz3b4jgR:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535#-:-NKyTUsSBD-5IVNLnTO5:bnfp4nl)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`solvers/nlopt_solver.cc` line 338 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKyQbSf2EkehRD9-Q7c:-NKyQbSf2EkehRD9-Q7d:bmn4g4f) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L338)):*
> ```cpp
> nlopt::algorithm GetNloptAlgorithm(const SolverOptions& merged_options) {
>   const auto& options_str = merged_options.GetOptionsStr(NloptSolver::id());
>   auto it = options_str.find("algorithm");
> ```

For other options, we offer static member functions like `NloptSolver::ConstraintToleranceName()` to provide for the option key.  It's not clear why the `"algorithm"` option handling doesn't follow that same pattern.
___
*[`solvers/nlopt_solver.cc` line 344 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKySEcvD7peVhpg_wVu:-NKySEcvD7peVhpg_wVv:b-riebeu) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L344)):*
> ```cpp
>   } else {
>     for (int i = 0; i < nlopt::algorithm::NUM_ALGORITHMS; ++i) {
>       if (it->second.compare(nlopt_algorithm_to_string(
> ```

nit Here and below, `it->second` is too obscure of a variable name -- it doesn't explain what the thing is, so the code is too difficult to follow.

We should give it a meaningful name, something like `const std::string& algorithm = it->second`.  Or we could imagine naming it `requested_algorithm` or `request` or `algorithm_option`, or etc. 



_Code quote:_
```cpp
it->second
```
___
*[`solvers/nlopt_solver.cc` line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKySlK63JaVMOiX249X:-NKySlK7ANt7a0VXXiUc:b-s7v2c1) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L345)):*
> ```cpp
>     for (int i = 0; i < nlopt::algorithm::NUM_ALGORITHMS; ++i) {
>       if (it->second.compare(nlopt_algorithm_to_string(
>               static_cast<nlopt_algorithm>(i))) == 0) {
> ```

nit Spelling out a string equality check as `foo.compare(bar) == 0` obscures what's happening.  Really we just want `algorithm == nlopt_algorithm_to_string(i)`, I think -- the simple `operator==`?
___
*[`solvers/solver_options.h` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKyRAGG-N6QmEcwFMhb:-NKyRAGG-N6QmEcwFMhc:boc9606) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/solver_options.h#L40)):*
> ```objc
>  * github.com/stevengj/nlopt/blob/master/src/api/general.c. If you would like to
>  * use certain algorithm, for example NLOPT_LD_SLSQP, call
>  * `SetOption(NloptSolver::id(), "algorithm", "LD_SLSQP");`
> ```

This doc fails to specify the other NLOPT options we support (constraint_tol, xtol_rel, etc.), thus misleading the user that we only support 1 option.

Trying to spell out every option here would overwhelm this page.  For all of the other solvers, we only provide a _link_ to the options manifest.  I think we should do the same here, by citing to our NloptSolver doxygen class overview and itemizing the options on that (NLOPT-specific) page.

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535#-:-NL2VYB_DcJOTKcoa1Bi:b-c9pjop)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform) (waiting on @jwnimmer-tri and @sammy-tri)

___
*[`solvers/nlopt_solver.cc` line 338 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKyQbSf2EkehRD9-Q7c:-NL2SxM65NQiTP-JQBej:b-yh16lj) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L338)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For other options, we offer static member functions like `NloptSolver::ConstraintToleranceName()` to provide for the option key.  It's not clear why the `"algorithm"` option handling doesn't follow that same pattern.
</blockquote></details>

Done. Good call!
___
*[`solvers/nlopt_solver.cc` line 344 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKySEcvD7peVhpg_wVu:-NL2T9weCDg1ORAvsiwP:b-hqiis6) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L344)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Here and below, `it->second` is too obscure of a variable name -- it doesn't explain what the thing is, so the code is too difficult to follow.

We should give it a meaningful name, something like `const std::string& algorithm = it->second`.  Or we could imagine naming it `requested_algorithm` or `request` or `algorithm_option`, or etc. 
</blockquote></details>

Done. I named it `requested_algorithm`.
___
*[`solvers/nlopt_solver.cc` line 345 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKySlK63JaVMOiX249X:-NL2TL2u-jd3GaUks-Jj:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/nlopt_solver.cc#L345)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Spelling out a string equality check as `foo.compare(bar) == 0` obscures what's happening.  Really we just want `algorithm == nlopt_algorithm_to_string(i)`, I think -- the simple `operator==`?
</blockquote></details>

Done. Good call.
___
*[`solvers/solver_options.h` line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NKyRAGG-N6QmEcwFMhb:-NL2U_0j5cGlaazaKkKn:b-61e474) ([raw file](https://github.com/robotlocomotion/drake/blob/52a1dc6861b83fd9a019bb9eea22c820a7dc5efa/solvers/solver_options.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This doc fails to specify the other NLOPT options we support (constraint_tol, xtol_rel, etc.), thus misleading the user that we only support 1 option.

Trying to spell out every option here would overwhelm this page.  For all of the other solvers, we only provide a _link_ to the options manifest.  I think we should do the same here, by citing to our NloptSolver doxygen class overview and itemizing the options on that (NLOPT-specific) page.
</blockquote></details>

Done. I added the page.

NLopt doesn't really provide a list of all parameters. Currently we only specify parameters for stopping criteria and algorithm, hence I point to the "stopping criteria" page and the algorithm file.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/nlopt_solver.cc` line 353 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NL2moQk6DMEJ3ojAMP_:-NL2moQk6DMEJ3ojAMPa:b-ajgemx) ([raw file](https://github.com/robotlocomotion/drake/blob/52d41ce84baab44c0f168922956936ef92f7121d/solvers/nlopt_solver.cc#L353)):*
> ```cpp
>         fmt::format("Unknown NLopt algorithm {}, please check "
>                     "nlopt_algorithm_to_string() function "
>                     "github.com/stevengj/nlopt/blob/src/api/general.c for "
> ```

This link didn't work for me (404 error from github).  Would https://github.com/stevengj/nlopt/blob/master/src/api/general.c#L100 be better?  

Oh, the link from `solver_options.h` did work for me, so we could just use that here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[`solvers/nlopt_solver.cc` line 353 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18535#-NL2moQk6DMEJ3ojAMP_:-NL4xrAYB0HfXNdEQOsh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52d41ce84baab44c0f168922956936ef92f7121d/solvers/nlopt_solver.cc#L353)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This link didn't work for me (404 error from github).  Would https://github.com/stevengj/nlopt/blob/master/src/api/general.c#L100 be better?  

Oh, the link from `solver_options.h` did work for me, so we could just use that here.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18535#-:-NL6aBiu1yiGGl9GXl14:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
