### PR TITLE
Move meshes and models from drake to drake_models

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/19078 and https://github.com/RobotLocomotion/drake/issues/11913.

See https://github.com/RobotLocomotion/models/pull/23 for the sibling pull request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

I'm also curious to get your thoughts on whether and which piece of this might merit a second (platform) reviewer.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: questions

So far, I've made no attempt to confirm that moved files have the same contents. I've only looked at which files moved where, and the resulting path name changes. To understand things better, I pulled both patches locally and studied the file manifests, with help from text filtering and diffing tools.

In the context of the other patch review, I'll try to confirm that files arrived undamaged.

I'm a bit curious about the design choices of which files moved, which stayed, and which got dropped. The destination path names seem fine to me.

As for a second reviewer, I'm not feeling strongly about it. If you think I've missed some aspects, by all means recruit a second reviewer.

> Reviewed 357 of 357 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-:-NSlts6T00zHsdrbElkX:b-em1q1k)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`examples/atlas/urdf/door.urdf` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlkUvj8aeuULU-3maa:-NSlkUvj8aeuULU-3mab:b-66v4mw) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f9800b1ebcd451e6042b3c5b302ebe3ba182061/examples/atlas/urdf/door.urdf#L1)):*
> ```XML
> <?xml version="1.0"?>
> ```

nit This is an example of a file that was not transferred, but just dropped. Were these just unused, and inherited from some prior source?
___
*[`manipulation/models/allegro_hand_description/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlphYLAGGAhwEtOhqz:-NSlphYLAGGAhwEtOhr-:b5s3s1a) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5447084191054e19f3dba27b93c4ebfb38b05d5/manipulation/models/allegro_hand_description/BUILD.bazel#L14)):*
> ```Starlark
>     name = "glob_models",
>     extra_srcs = [
>         "LICENSE.TXT",
> ```

Should the license file be coming from drake_models now, similar to `atlas`?
___
*[`manipulation/models/iiwa_description/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSltGAg4XQaPsVFIV4P:-NSltGAg4XQaPsVFIV4Q:b-p5oen) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5447084191054e19f3dba27b93c4ebfb38b05d5/manipulation/models/iiwa_description/BUILD.bazel#L14)):*
> ```Starlark
>     name = "glob_models",
>     extra_srcs = [
>         "LICENSE.TXT",
> ```

Also here, should this license file come from drake_models?

**Review by jwnimmer-tri — COMMENTED** [review]
> I'm a bit curious about the design choices of which files moved, which stayed, and which got dropped.

I moved Atlas all at once here because trying to split it up meshes vs models was going to be a lot of work, and I figured not that many people are using it.

For the others like the iiwa arm and allegro hand, probably a bunch of people have hard-coded the current URDF filenames so I want to be a bit more careful moving them (probably with deprecation, even though models are not Stable API).  Moving the meshes only solves the acute problem (narrowing the install footprint) without disturbing users yet.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-:-NSlwrnl5bQX414r_Co8:b3ynfsl)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`manipulation/models/allegro_hand_description/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlphYLAGGAhwEtOhqz:-NSly4MxEdz60wUVN-zt:b-yxbpns) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5447084191054e19f3dba27b93c4ebfb38b05d5/manipulation/models/allegro_hand_description/BUILD.bazel#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should the license file be coming from drake_models now, similar to `atlas`?
</blockquote></details>

The URDF files are still in drake git and installed as part of drake, so we still need to keep the license text for those files in drake.git alongside the URDFs, and install the license file alongside the installed URDF files.
___
*[`manipulation/models/iiwa_description/BUILD.bazel` line 14 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSltGAg4XQaPsVFIV4P:-NSlyN5d2E4JsxuUndz1:bs4q9op) ([raw file](https://github.com/RobotLocomotion/drake/blob/a5447084191054e19f3dba27b93c4ebfb38b05d5/manipulation/models/iiwa_description/BUILD.bazel#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Also here, should this license file come from drake_models?
</blockquote></details>

Ditto.
___
*[`examples/atlas/urdf/door.urdf` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlkUvj8aeuULU-3maa:-NSlxpDR9liGJdMKFW92:b-79ve4l) ([raw file](https://github.com/RobotLocomotion/drake/blob/3f9800b1ebcd451e6042b3c5b302ebe3ba182061/examples/atlas/urdf/door.urdf#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit This is an example of a file that was not transferred, but just dropped. Were these just unused, and inherited from some prior source?
</blockquote></details>

This was already deleted in #19159.  There must be some kind of rebase confusing either in reviewable or on my part, sorry.

**Review by jwnimmer-tri — COMMENTED** [review]
> As for a second reviewer, I'm not feeling strongly about it. If you think I've missed some aspects, by all means recruit a second reviewer.

+(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-:-NSlyciABEkFIL4pNs6w:b-autzb6)* status: 4 unresolved discussions (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlyaOa8uQT-Br6TZpo:-NSlyaOa8uQT-Br6TZpp:b-mr2yzq) (no related file):*
Working

Do not merge until models git sha is finalized (after the other PR).

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19160#-NSlyaOa8uQT-Br6TZpo:-NSmFIso7nhrrGFbwWms:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Do not merge until models git sha is finalized (after the other PR).
</blockquote></details>

Done.

___

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19160)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I cannot imagine how macOS would have any particular sadness here, but let's be sure:

@drake-jenkins-bot mac-arm-monterey-clang-bazel-continuous-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
FYI the change in compressed release archive size from this PR:

```
-rw-rw-r-- 1 jwnimmer jwnimmer 92M Apr 11 15:49 install-oldmaster.tgz
-rw-rw-r-- 1 jwnimmer jwnimmer 56M Apr 11 15:49 install-newmaster.tgz
```

That's a 36 MiB reduction (-39%).

**Pull request merged**
