### PR TITLE
fix path to mosek test log file

### LINKED ISSUE #9569: mosek tests failing on my mac
Just refreshed my license file, but one test is still failing with:

```
solvers/test/mosek_solver_test.cc:129: Failure
Value of: spruce::path(log_file).exists()
  Actual: true
Expected: false
solvers/test/mosek_solver_test.cc:133: Failure
Value of: spruce::path(log_file).exists()
  Actual: true
Expected: false
Problem
  Name                   :
  Objective sense        : min
  Type                   : LO (linear optimization problem)
  Constraints            : 1
  Cones                  : 0
  Scalar variables       : 2
  Matrix variables       : 0
  Integer variables      : 0

Optimizer started.
Presolve started.
Linear dependency checker started.
Linear dependency checker terminated.
Eliminator started.
Freed constraints in eliminator : 1
Eliminator terminated.
Eliminator - tries                  : 1                 time                   : 0.00
Lin. dep.  - tries                  : 1                 time                   : 0.00
Lin. dep.  - number                 : 0
Presolve terminated. Time: 0.00
Optimizer terminated. Time: 0.00

solvers/test/mosek_solver_test.cc:137: Failure
Value of: spruce::path(log_file).exists()
  Actual: true
Expected: false
[  FAILED  ] MosekTest.TestLogFile (5 ms)
```

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #9569

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10297)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
If `temp_directory()` was e.g. `/tmp/somethingbazelmade/` directory (sans trailing slash), then `/tmp/somethingbazelmademosek.log` could possibly also be a valid, writeable file (depending on sandboxing settings, perhaps?).  Possibly there is some difference between CI and your machine, in terms of user permissions, sandbox settings, output_root, etc.

**Comment by RussTedrake** [comment]
agreed.  but pretty strange that it would happen on my mac and (almost) independently on ubuntu?

**Comment by RussTedrake** [comment]
I was definitely getting `/tmp/robotlocomotion-drake-XXX` on this ubuntu machine.  (can't actually use the debugger easily on mac)

**Comment by RussTedrake** [comment]
Perhaps the build servers are setting TEST_TMPDIR?

**Comment by jwnimmer-tri** [comment]
:lgtm: both reviews.

**Pull request merged**
