### PR TITLE
[planning] Add velocity bounds to subgraphs

### PR DESCRIPTION
**Pull request by wrangelvid**
This adds velocity bounds to the subgraphs, which enables useful minimum time planning.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334)

### CODE REVIEW

**Review by wrangelvid — COMMENTED** [review]
+@RussTedrake for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-:-NUTW4chAYNwELTCYOWq:b1ikduc)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake and @wrangelvid)

**Review by RussTedrake — COMMENTED** [review]
awesome!  i like the test/example.  :lgtm: with a few small questions/corrections.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-:-NUU7wFKA0ztltMKj4uu:b5q5mbo)* status: 8 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 119 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU4YL15le3fqR7Yug-:-NUU4YL15le3fqR7Yug0:bwm7azx) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L119)):*
> ```objc
>     @param ub is the upper bound of the velocity.
> 
>     The subgraph order must be greater than zero, since the velocity is defined
> ```

You should write e.g.
```
throws std::exception if the subgraph order is zero...
```
you also throw if the sizes of lb/ub are wrong.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 336 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU6EeYB5FNDsUIBbKn:-NUU6EeYB5FNDsUIBbKo:bctwoq1) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/gcs_trajectory_optimization.h#L336)):*
> ```objc
>   forming the derivative of the Bézier curve, this constraint will only added to
>   all subgraphs with order greater than zero. Note that this constraint will be
>   applied even to subgraphs added in the future.
> ```

report that you throw if lb and ub are the wrong size.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU4kO-4_K0HYVw1lcJ:-NUU4kO-4_K0HYVw1lcK:beq9hy5) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L51)):*
> ```cpp
> using EdgeId = GraphOfConvexSets::EdgeId;
> 
> const double inf = std::numeric_limits<double>::infinity();
> ```

inf => kInf.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU5CktBelk6sPfFVf8:-NUU5CktBelk6sPfFVf9:btzf793) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L217)):*
> ```cpp
> 
>   // We have q̇(t) = drds * dsdt = ṙ(s) / h, and h >= 0, so we
>   // use duration * lb <= ṙ(s) <= duration * ub. But will be reformulated as:
> ```

duration => h  (twice)

nit: "But will be reformulated as" .  maybe ", formulated as:"
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU6mpABQdGABto5pcr:-NUU6mpABQdGABto5pcs:b1omqgr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L118)):*
> ```cpp
> 
>   // Add shortest path objective.
>   gcs.AddPathLengthCost();
> ```

nit: seems inconsistent with the problem setup?  add a line saying that you 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU78MZ-Cu6BqBMMMNk:-NUU78MZ-Cu6BqBMMMNl:b-vkod4c) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L158)):*
> ```cpp
>   // Now we want to find the fastest path from S to G.
>   // Add minimum time objective with a very high weight to overpower the
>   // shortest path objective.
> ```

nit: would be slightly cleaner to not have both in the same problem, but i realize that removing the costs would be nontrivial, and making a new gcs would be a bunch of lines...
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU7VCB8m7m21X39hyJ:-NUU7VCB8m7m21X39hyK:b1wo3v2) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L171)):*
> ```cpp
> 
>   // We expect the fastest path to take a detour and avoid the slow gravel,
>   // going through the gravel. Thus we expect the number of segments in the
> ```

nit: redundant. "slow gravel, going through the gravel"
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 340 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU7qcPBOI8t_OL-1z2:-NUU7qcPBOI8t_OL-1z3:b1iji2) ([raw file](https://github.com/RobotLocomotion/drake/blob/ad86e4f600da59418b24b047f9670617c4eb144e/bindings/pydrake/planning/test/trajectory_optimization_test.py#L340)):*
> ```Python
> 
>         # Add velocity bounds to the entire graph.
>         gcs.AddVelocityBounds(-max_vel, max_vel)
> ```

lb=, ub=

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 119 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU4YL15le3fqR7Yug-:-NUUWy6bAHFdw0b5BOr6:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/gcs_trajectory_optimization.h#L119)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

You should write e.g.
```
throws std::exception if the subgraph order is zero...
```
you also throw if the sizes of lb/ub are wrong.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 336 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU6EeYB5FNDsUIBbKn:-NUUYFja1qF_w56bgx7b:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/gcs_trajectory_optimization.h#L336)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

report that you throw if lb and ub are the wrong size.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 51 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU4kO-4_K0HYVw1lcJ:-NUUYNz2C-ilExlyUcWH:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L51)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

inf => kInf.
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU5CktBelk6sPfFVf8:-NUUYZFZ7gbq5D1qrOzM:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L217)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

duration => h  (twice)

nit: "But will be reformulated as" .  maybe ", formulated as:"
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 118 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU6mpABQdGABto5pcr:-NUUYl28Ae2ES3D4C1c_:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L118)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: seems inconsistent with the problem setup?  add a line saying that you 
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 158 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU78MZ-Cu6BqBMMMNk:-NUUYmJK9-T_mf4811hT:bege9bx) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L158)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: would be slightly cleaner to not have both in the same problem, but i realize that removing the costs would be nontrivial, and making a new gcs would be a bunch of lines...
</blockquote></details>

`.Clone()` would be a nice addition that could get around that issue. I'll add a TODO statement. 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 171 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU7VCB8m7m21X39hyJ:-NUUZr0lACgx7dRsCmHb:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L171)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: redundant. "slow gravel, going through the gravel"
</blockquote></details>

Done.
___
*[`bindings/pydrake/planning/test/trajectory_optimization_test.py` line 340 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUU7qcPBOI8t_OL-1z2:-NUUZxFyEsZqEFxhkp4A:bs7wuot) ([raw file](https://github.com/RobotLocomotion/drake/blob/0c249215bda60dc0e84d0702121f2ee0afef8164/bindings/pydrake/planning/test/trajectory_optimization_test.py#L340)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

lb=, ub=
</blockquote></details>

Done.d

**Review by wrangelvid — COMMENTED** [review]
fixed. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-:-NUXbhUF5yTaYqXtc0mQ:blkwbr5)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @wrangelvid)

**Review by RussTedrake — COMMENTED** [review]
:lgtm: again.
+@xuchenhan-tri for platform review, please.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-:-NUXdIbd5nD7L39diZUz:b729b5o)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @wrangelvid and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: feature) :lgtm: 

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-:-NUXhSc95vd5kPBpbPxY:brfh9n7)* status: 4 unresolved discussions

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 114 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUXhfhB1bttMnmX-txe:-NUXhfhB1bttMnmX-txf:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.h#L114)):*
> ```objc
>     void AddPathLengthCost(double weight = 1.0);
> 
>     /** Adds a linear velocity constraints to the subgraph `lb` ≤ q̇(t) ≤
> ```

nit



_Suggestion:_
```objc
 Adds a linear velocity constraint to the subgraph 
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 329 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUXhsOI-V3SLVWIikZI:-NUXhsOI-V3SLVWIikZJ:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.h#L329)):*
> ```objc
>   void AddPathLengthCost(double weight = 1.0);
> 
>   /** Adds a linear velocity constraints to the entire graph `lb` ≤ q̇(t) ≤
> ```

nit



_Suggestion:_
```objc
Adds a linear velocity constraint to the entire graph
```
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 226 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUYct3z8eamtMU8uSk1:-NUYct3z8eamtMU8uSk2:b-twl2d9) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L226)):*
> ```cpp
>   // constraints for all t.
> 
>   const MatrixX<Expression> u_rdot_control =
> ```

nit looks like a copy isn't necessary here.



_Suggestion:_
```cpp
const MatrixX<Expression>& u_rdot_control =
```
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUYdwgW8LVoVYFjW7pH:-NUYdwgW8LVoVYFjW7pI:b-7xhfi5) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L70)):*
> ```cpp
> 
>   ░ - wall
>   ▒ - grave
> ```

typo
BTW, cool example.



_Suggestion:_
```cpp
gravel
```

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 114 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUXhfhB1bttMnmX-txe:-NUZHZ0v3ZYAAXB9M2u2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.h#L114)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 329 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUXhsOI-V3SLVWIikZI:-NUZH_en9sgJDsoXcoQI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.h#L329)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.cc` line 226 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUYct3z8eamtMU8uSk1:-NUZHoo465P7h9qoRN98:bxxmfap) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L226)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit looks like a copy isn't necessary here.
</blockquote></details>

The test cases are failing with `&`. 
___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 70 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19334#-NUYdwgW8LVoVYFjW7pH:-NUZHv6560tEd5_2Ugvo:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/e5b1efc21e08343d3db198409c46251974f63fcd/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L70)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
BTW, cool example.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19334)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform)

**Pull request merged**
