### PR TITLE
[render] RenderEngineVtk supports multiple meshes from OBJ

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
`RenderEngineVtk` uses the new `LoadRenderMeshesFromObj()` functionality. The distinct meshes get mapped to the same prop/part infrastructure as the glTF.
    
The description of obj support in the file format module is updated to reflect the current capability.

Incidentally, cleans up the temporary stub function to support the single-mesh OBJ semantics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) +(status: commits are properly curated) 

+@zachfang for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-NfrV5cU46f3fFxnU8BV:baqx52m)* status: 1 unresolved discussion, LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-NfrV8hp6bbhihB4h4wb:-NfrV8hp6bbhihB4h4wc:b-qeo9s2) (no related file):*
Note to reviewers:

R1: contains the updates to `RenderEngineVtk` so it can make use of .obj files with multiple materials/objects.
R2: removes the legacy stub function.

___

**Review by zachfang — COMMENTED** [review]
:lgtm: feature.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-NfwSAHe29U2CmzoGShD:b-n37teh)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/internal_render_engine_vtk.cc` line 729 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-NfwL5zH7LLl5omvzB2Q:-NfwL5zI8EtrAUtsRsJE:b-3gr8n4) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14ebf69a55cb04ce7a4bd3729b54df533ac816a/geometry/render_vtk/internal_render_engine_vtk.cc#L729)):*
> ```cpp
>   // Take ownership of the actors.
>   for (int i = 0; i < kNumPipelines; ++i) {
>     DRAKE_DEMAND(props[i].parts.size() == 1);
> ```

BTW. It's a bit counterintuitive to see that `props[i].parts` can only contain one part. It took me some time to remind myself how each RenderMesh contains. Maybe we can add a comment for that (or somewhere else).



_Code quote:_
```cpp
DRAKE_DEMAND(props[i].parts.size() == 1);
```
___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1074 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-NfwOdco-4msIBqE0Vlx:-NfwOdco-4msIBqE0Vly:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake/blob/e14ebf69a55cb04ce7a4bd3729b54df533ac816a/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1074)):*
> ```cpp
>   };
> 
>   std::vector<std::string> filenames{
> ```

nit.



_Suggestion:_
```cpp
const std::vector
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@EricCousineau-TRI for platform review.

Let me know if you disagree vis a vis declaring this curated. I like the separation of the new function and the removal of the old as separate commits, but I'm willing to squash.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-Ng0H7GC30fJJWqLPuM2:b-jtitim)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-NfrV8hp6bbhihB4h4wb:-Ng0IXXC9b0aKTS_Qtut:bk82m2m) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Note to reviewers:

R1: contains the updates to `RenderEngineVtk` so it can make use of .obj files with multiple materials/objects.
R2: removes the legacy stub function.
</blockquote></details>

R3 has a couple of cosmetic changes based on feature review.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:, nice! Just small BTW

Re: curated vs. squashing, I have a soft preference for squashing - squashed commit is checked by CI, and bisecting across these two commits may not be terribly useful.

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-Ng0L7dDCEPBvfvP7bqT:byu04tk)* status: 1 unresolved discussion, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-Ng0K7LM0aGqYMPcSYBp:-Ng0K7LM0aGqYMPcSYBq:bcnyql9) ([raw file](https://github.com/RobotLocomotion/drake/blob/e88ee0c1cbec0d882b28ca5812d7d9cb8e8beb57/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
> ```cpp
> }
> 
> // Primitives result in a geometry with a single Part. However, we can load
> ```

BTW Quick text search doesn't turn up "Part" as proper noun.

Should this be just `part` (lower case)?

**Review by SeanCurtis-TRI — COMMENTED** [review]
Fair enough. I'll squash when CI is done.

-(status: commits are properly curated)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-Ng0NeJZD5EvGucsDSAs:br3d6ad)* status: 1 unresolved discussion, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-Ng0K7LM0aGqYMPcSYBp:-Ng0Nj_GEzthffvxogZA:bb38hle) ([raw file](https://github.com/RobotLocomotion/drake/blob/e88ee0c1cbec0d882b28ca5812d7d9cb8e8beb57/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Quick text search doesn't turn up "Part" as proper noun.

Should this be just `part` (lower case)?
</blockquote></details>

There is a `struct RenderEngineVtk::Part`. That would be the proper noun being alluded to here.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-Ng0K7LM0aGqYMPcSYBp:-Ng0O3ky8XSUzwEXDOwE:b-fz1xcw) ([raw file](https://github.com/RobotLocomotion/drake/blob/e88ee0c1cbec0d882b28ca5812d7d9cb8e8beb57/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

There is a `struct RenderEngineVtk::Part`. That would be the proper noun being alluded to here.
</blockquote></details>

OK Ah, missed that (only searched available diffs, not the full files - sorry!)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1040 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-Ng0K7LM0aGqYMPcSYBp:-Ng0OaaF3-JmLQ1GUR6m:b-lj9kug) ([raw file](https://github.com/RobotLocomotion/drake/blob/e88ee0c1cbec0d882b28ca5812d7d9cb8e8beb57/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1040)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, missed that (only searched available diffs, not the full files - sorry!)
</blockquote></details>

No worries.  :)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20235#-:-Ng0_AZP7dUnPt3ayICK:b-9yowsm)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),zachfang

**Pull request merged**
