### PR TITLE
[visualization] Add ApplyVisualizerConfig

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #17112 and then (with forthcoming tweaks in #17641) towards #13673.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17645)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

This is a relatively straight copy from Anzu (r1 is the files as-is from Anzu).

I think we can do even more to adapt this for Drake (prototyped in #17641) but I think it makes most sense to land what we have so far, and then iterate in follow-up PRs.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17645#-:-N84Kj7q0L0WCwwCeAni:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, thanks!

> Reviewed 5 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17645#-:-N84vh7L85CR_Ib2w27U:bhm0jc2)* status: 1 unresolved discussion, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`visualization/visualizer_config_functions.cc` line 37 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17645#-N84u-aF1t-m7V5T6Ks1:-N84u-aF1t-m7V5T6Ks2:b-21jkzi) ([raw file](https://github.com/robotlocomotion/drake/blob/b6249d40f745335ca365b0fee19a2d8ce2f20acc/visualization/visualizer_config_functions.cc#L37)):*
> ```cpp
>     // TODO(jwnimmer-tri) At the moment, meldis cannot yet display hydroelastic
>     // geometry. So long as that's true, we should not enable it.
>     DrakeVisualizerParams oopsie = params;
> ```

BTW Was confused about this very odd behavior (discarding it outright, even though Director can handle it).
However, I see it'll be addressed in #17641 per overview - thanks for mentioning that!
___
*[`visualization/test/visualizer_config_functions_test.cc` line 131 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17645#-N84vTkE7idJglcx5PWu:-N84vTkE7idJglcx5PWv:b-wpx7xn) ([raw file](https://github.com/robotlocomotion/drake/blob/b6249d40f745335ca365b0fee19a2d8ce2f20acc/visualization/test/visualizer_config_functions_test.cc#L131)):*
> ```cpp
>   // We'll fail in case any message is transmitted.
>   DrakeLcm drake_lcm;
>   drake_lcm.SubscribeAllChannels([](auto...) { GTEST_FAIL(); });
> ```

TIL! Hadn't seen use of `[](auto...)` before.

**Pull request merged**
