### PR TITLE
Add affine cone constraint in Mosek.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@aykut-tri for feature review please, thanks! This is the continuation of the previous PR #181085

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114#-:-NEXHdcLBkACSGP9y1nu:bgbqtuk)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by hongkai-dai — COMMENTED** [review]
Sorry I mean the previous PR #18085 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114#-:-NEXI11m5aQ9kmKY9ef-:b-4a1uv7)* status: LGTM missing from assignee aykut-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
+@xuchenhan-tri flor platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114#-:-NElKJ_d9y5TrCnInEB9:b50iqj4)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @hongkai-dai and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: pending naming concern and some documentation requests.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114#-:-NEm2qkY7gV47-ZBm8tN:b-st0fdo)* status: 5 unresolved discussions (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEm1iFm93_lt1x45Ldy:-NEm1iFm93_lt1x45Ldz:bwgkc8l) (no related file):*
The naming convention in this PR is slightly confusing. It seems to be a mix of Mosek style `foobarbaz` (which tbh is a little inhuman :)) and GSG compliant `foo_bar_baz`. I suspect the intention is to use Mosek style naming for Mosek types? If that's the case, please make it consistent throughout the PR. Otherwise, following GSG naming convention and using snake case should also be fine.

___
___
*[`solvers/mosek_solver_internal.h` line 572 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NElyNM_6v8KJkZto0_R:-NElyNM_6v8KJkZto0_S:b6xmc12) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L572)):*
> ```objc
> 
> template <typename C>
> void SetNonlinearConstraintDualSolution(
> ```

nit, the document is lacking. With the introduction of acronym "acc", it may be worthwhile to add doc to at least explain what the parameters are.
___
*[`solvers/mosek_solver_internal.h` line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEkgl-lBMKnsfTo1EGx:-NEm30wLEe6PmG70UkfM:b-rirpw5) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L581)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Just curious, why don't you return `rescode` here if not OK, as in the other cases?
</blockquote></details>

I'm guessing this can only be triggered by a bug in the code instead of a user defined invalid configuration? Either way, I'd use DRAKE_DEMAND here because this doesn't seem to be performance critical.
___
*[`solvers/test/mosek_solver_internal_test.cc` line 233 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEm0pKo722eC2rgwaaq:-NEm0pKo722eC2rgwaar:bcyxmqx) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/test/mosek_solver_internal_test.cc#L233)):*
> ```cpp
> }
> 
> VectorX<symbolic::Expression> GetAffineExpression(
> ```

nit, could you add some brief comment on what this function is accomplishing?
___
*[`solvers/test/mosek_solver_internal_test.cc` line 321 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEm1EM40fAODa2L45mn:-NEm1EM40fAODa2L45mo:b5489hm) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/test/mosek_solver_internal_test.cc#L321)):*
> ```cpp
> }
> 
> GTEST_TEST(AddConeConstraings, Test1) {
> ```

nit As a non-expert on optimization/Mosek, I find the tests hard to read.

Some overarching description of the testing strategy and more descriptive test names could be helpful here.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)* status: 2 unresolved discussions (waiting on @aykut-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEm1iFm93_lt1x45Ldy:-NEmQlp30eao6yuY-7h7:b-fh9vfe) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The naming convention in this PR is slightly confusing. It seems to be a mix of Mosek style `foobarbaz` (which tbh is a little inhuman :)) and GSG compliant `foo_bar_baz`. I suspect the intention is to use Mosek style naming for Mosek types? If that's the case, please make it consistent throughout the PR. Otherwise, following GSG naming convention and using snake case should also be fine.
</blockquote></details>

Done. I changed to use `foo_bar_baz`.

___
___
*[`solvers/mosek_solver_internal.h` line 485 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEkeX2X1UHkGo0dwBO9:-NEmMDAc63Cm2xVxFlKi:b4ardwp) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L485)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

BTW, do you think it makes sense to combine these into one operation after the if/else such that you use `weights` as the last argument, and `weights' is defined before the if/else and modified for rotated cones?
</blockquote></details>

I was trying to avoid a heap memory allocation of `weights` when possible. When the cone is not the rotated lorentz cone, I can use `sub_weights.second.data()` directly without allocating new memories.

If I create this `weights` variable for every type of cone, then I always need to allocate heap memory. In the case when we have many cone constraint, this heap memory allocation is undesired.
___
*[`solvers/mosek_solver_internal.h` line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEkgl-lBMKnsfTo1EGx:-NEmOAWaD5CV6GiQFyOl:bhctvem) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L581)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm guessing this can only be triggered by a bug in the code instead of a user defined invalid configuration? Either way, I'd use DRAKE_DEMAND here because this doesn't seem to be performance critical.
</blockquote></details>

As @xuchenhan-tri mentioned, this should not be triggered by a user input error.  Hence I just check the value rather than return the rescode.

Anyway I think I can return the rescode here, which makes debugging easier.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)* status: 2 unresolved discussions (waiting on @aykut-tri and @hongkai-dai)

___
*[`solvers/mosek_solver_internal.h` line 572 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEmSMqR0W30wgqyp7PA:-NEmSMqR0W30wgqyp7PB:b-35lbgx) ([raw file](https://github.com/robotlocomotion/drake/blob/938fa0a24570410f94f2bca9b38078e52f111e89/solvers/mosek_solver_internal.h#L572)):*
> ```objc
> 
> /*
>  * Set the dual solution for the affine cone constraints.
> ```

nit GSG



_Suggestion:_
```objc
Sets the dual solution for the affine cone constraints.
```

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)* status: 1 unresolved discussion (waiting on @aykut-tri)

**Comment by xuchenhan-tri** [comment]
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEmc0xzBZc_DUYs-d6e):*
BTW, it seems like this PR together with #18085 enables the new feature. If that's the case, mentioning it in the commit message may help the release manager.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)* status: 1 unresolved discussion (waiting on @aykut-tri)

**Review by aykut-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18114)* status: :shipit: complete! all discussions resolved, LGTM from assignees aykut-tri,xuchenhan-tri(platform) (waiting on @hongkai-dai)

___
*[`solvers/mosek_solver_internal.h` line 485 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEkeX2X1UHkGo0dwBO9:-NErIKue0Rk3okn74YkK:b-rv7lpn) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L485)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I was trying to avoid a heap memory allocation of `weights` when possible. When the cone is not the rotated lorentz cone, I can use `sub_weights.second.data()` directly without allocating new memories.

If I create this `weights` variable for every type of cone, then I always need to allocate heap memory. In the case when we have many cone constraint, this heap memory allocation is undesired.
</blockquote></details>

I see, that makes a lot of sense, thanks for the explanation!
___
*[`solvers/mosek_solver_internal.h` line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18114#-NEkgl-lBMKnsfTo1EGx:-NErIWm-1rcBssKxmlaW:b-oe1elb) ([raw file](https://github.com/robotlocomotion/drake/blob/976a153dd7e2623c9559f20e40442e7a35ac732e/solvers/mosek_solver_internal.h#L581)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

As @xuchenhan-tri mentioned, this should not be triggered by a user input error.  Hence I just check the value rather than return the rescode.

Anyway I think I can return the rescode here, which makes debugging easier.
</blockquote></details>

Gotcha, that's a good point, thanks.

**Pull request merged**
