### PR TITLE
Add drake_add_cc_test function

### LINKED ISSUE #3407: Reduce unit tests' CMake boilerplate
Writing this over and over again is getting a bit boring:
```
add_executable(foo_bar_test foo_bar_test.cc)
target_link_libraries(foo_bar_test drakeSomething drakeSomething2)
add_test(NAME foo_bar_test COMMAND foo_bar_test)

add_executable(foo_baz_test foo_baz_test.cc)
target_link_libraries(foo_baz_test drakeSomething drakeSomething2)
add_test(NAME foo_baz_test COMMAND foo_baz_test)

add_executable(foo_quux_test foo_quux_test.cc)
target_link_libraries(foo_quux_test drakeSomething drakeSomething2)
add_test(NAME foo_quux_test COMMAND foo_quux_test)
```

I assume there's a way to wrap a macro around this, so as to write approximately this:
```
libraries_required_by_this_subdirectory="drakeSomething drakeSomething2"
drake_add_cc_unit_test(foo_bar_test)
drake_add_cc_unit_test(foo_baz_test)
drake_add_cc_unit_test(foo_quux_test)
```

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #3407.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3547)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review and +@david-german-tri for platform review (or vice versa).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot windows-msvc-ninja-64-experimental please

**Comment by jwnimmer-tri** [comment]
:lgtm: as far as I can tell.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/test.cmake, line 99 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3547#-KSDZoT-KOJ6BVwjv5ks:-KSDZoT0QS57qcWyEdXn:b-7cl90u) ([raw file](https://github.com/robotlocomotion/drake/blob/43c4f755c04b8972d41d31b0a7b989ec23dbe79d/cmake/test.cmake#L99)):*
> ```CMake
> #   NAME
> #     Set the name of the executable and the test. The name may not contain
> #     spaces or quotes. The C++ source code for the executable must be completely
> ```

BTW This shows up at >80 chars in reviewable.  Not sure if you were trying to keep it less than that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3547#-:-KSD_0akZCKT-FmrR7rU:b8buads)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3547)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3547#-:-KSDhNaS4nSOjaj0wwwE:bnfp4nl)*

**Pull request merged**
