### PR TITLE
[tutorials] Reduce overwhelming solver verbosity

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hotfix for #16019.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16030)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@hongkai-dai could you review the tutorial changes, from the perspective of whether we're losing any instructional value?

(I'll deal with the ongoing CI-related concerns separately.)

**Comment by jwnimmer-tri** [comment]
Mac is happy.

+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16030#-:-MnX06AYCXe0j-eb6l93:bmxilld)* status: LGTM missing from assignee hongkai-dai (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
Because this is of emergency priority, I'm going to self-certify feature review and merge now.

-@hongkai-dai please feel free to let me know later if you'd like see any additional changes or fixes related to this tutorial.

**Pull request merged**
