### PR TITLE
[fem] Move documentation of stiffness matrix out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16755)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16755#-:-Mxl4twN0O7-ql2_aYrj:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16755#-:-MxlA2mg67Js8ANtmfyI:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review on Thursday per rotation please.
These files are moving out of dev and require a full review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16755#-:-MxlEzjc-wZt_oKGYk0l:b4u0dhb)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, just skimmed through PDF and didn't see any easy-to-catch omissions or errors (spelling or otherwise)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16755#-:-Mxo1EWL5yVrIGx4hx3v:b-vrrotb)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

___
*[multibody/fem/doc/stiffness_matrix.pdf, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16755#-Mxo1nsx2zm31lO1yO7P:-Mxo1nsx2zm31lO1yO7Q:b-6x47jz) ([raw file](https://github.com/robotlocomotion/drake/blob/395bab8fd83b203ee88fc55882d5e6f2721508e2/multibody/fem/doc/stiffness_matrix.pdf#L0)):*
BTW Minor concern about file size, moreso for setting precedent than this current PR.

Directives here are for models, but I assume it would apply more generally.
https://drake.mit.edu/model_version_control.html
\cc @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI Your intuition was right.  We don't put latex PDF into git.  We put the tex into Doxygen and let it render it onto our website.

**Pull request merged**
