### PR TITLE
[proximity] Implement Mesh for proximity via its convex hull.

### LINKED ISSUE #14197: Use convex hull approximation as default collision geometry for mesh files
I am following up on the discussion from [stackoverflow](https://stackoverflow.com/questions/64196799/mesh-based-collision-geometry-in-drake).  I believe that the fact that, by default, specifying a mesh file as a collision geometry results in NO collision geometry represents a *major* usability issue.  For newcomers, they immediately get a bad impression of our dynamics engine.  For experts, it’s a serious limitation to have to curate the collision geometry ourselves.

@sherm1 suggested that bullet is likely using the convex hull.  Browsing the bullet source code quickly, this seems likely, (and I’ve heard the same sentiment from a number of people) but I haven’t officially confirmed that.

Is there any reason why we shouldn’t compute the convex hull and use it as the default collision geometry (printing a warning to the log)?

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This provides an initial implementation of the Mesh shape for proximity queries. It does so by using a very simple and very slow representation of the mesh's convex hull.

1. Refactor the OBJ --> fcl::Convex code to support Mesh. This basically *moved* the functions so they'd be available more generally.
2. Remove the all artifacts of special mesh treatment:
   - MeshIdentifier reifier.
   - special dynamic_mesh_tree_, anchored_mesh_tree_, and X_MeshBs_ (no longer necessary because the meshes don't have to be segregated).
3. Reimplement ImplementGeometry(Mesh) to make use of fcl::Convex.
4. Update unit tests accordingly.
5. Update documentation.

resolves #14197

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)

### CODE REVIEW

**Comment by sherm1** [comment]
Does this just take advantage of GJK to create an implicit convex shape on the fly?

**Review by SeanCurtis-TRI — COMMENTED** [review]
That's the intent. I have to get it over the CI hump.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMMXHMJ-yBeYerngWmv:b6ulz99)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
An attempt to resolve CI woes....

+(status: do not review) This should wait until #14324 has merged because they *will* have merge conflicts. I'll resolve that after the other is done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMMozh23oiK63vWvLdA:b-7tccaa)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
-(status: do not review) 

+@joemasterjohn for feature review -- although it will change slightly when #14324 merges, still worth getting review through. Joe, this is most relevant to you for your FCL OKR because this behavior needs to be maintained.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMQ_6P91flU_9ZI-pQt:b4xiq42)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by SeanCurtis-TRI — COMMENTED** [review]
BTW I've bumped the priority to see if we can't get this reviewed prior to my disappearance.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMQnOPCBSNd9-gWa5vl:bcg2r29)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Rebased on master (resolving conflicts).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMXTK369rIy38lMfBKj:bzh6vm1)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: 1 unresolved discussion, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 576 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMXa_Ra4i5WXBo2ZLuJ:-MMXa_Ra4i5WXBo2ZLuK:b8utp0l) ([raw file](https://github.com/robotlocomotion/drake/blob/ed5a0b16fac1e47c4e523488a619bed507c83c75/geometry/proximity_engine.cc#L576)):*
> ```cpp
>     }
>     DRAKE_DEMAND(disjoint_faces.size() == 8);
>     auto fcl_convex = make_shared<fcl::Convexd>(
> ```

Is this constructor mistakenly using `faces` instead of `disjoint_faces`?

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMXe8lnAyXJLwcj2iWG:-MMXe8lnAyXJLwcj2iWH:bwj61qw) ([raw file](https://github.com/robotlocomotion/drake/blob/ed5a0b16fac1e47c4e523488a619bed507c83c75/geometry/proximity_engine.cc#L548)):*
> ```cpp
> 
>     // Create an "invalid" convex mesh from two, disjoint triangles.
>     std::vector<int> disjoint_faces;
> ```

Use a single triangle as the intentional non-watertight mesh here instead of these two disjoint triangles.

**Comment by sherm1** [comment]
Please LMK if you need a pre-vacation platform review for this PR.

**Review by joemasterjohn — COMMENTED** [review]
Thanks @sherm1, it will probably need one. I'm ready to give the lgtm after a small bug gets fixed. Everything else looks kosher to me.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMXjQqr0a7Bdbm1sIKn:b71doan)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn and @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMXe8lnAyXJLwcj2iWG:-MMXljk70cCQbzKmCIFX:bigksyn) ([raw file](https://github.com/robotlocomotion/drake/blob/ed5a0b16fac1e47c4e523488a619bed507c83c75/geometry/proximity_engine.cc#L548)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Use a single triangle as the intentional non-watertight mesh here instead of these two disjoint triangles.
</blockquote></details>

I think another reason this has to change is that it wouldn't be able to find two "disjoint" faces for a mesh that is just a single tetrahedron.

Per f2f: it looks like part of the condition for FCL saying "invalid mesh" is if there are any vertices not belonging to a face. Therefore constructing an `fcl::Convexd` with 0 faces and non 0 vertices should also work.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMXrdS4AJtOrkG6ExDC:bel95ya)* status: 2 unresolved discussions, LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

___
*[geometry/proximity_engine.cc, line 548 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMXe8lnAyXJLwcj2iWG:-MMXrKK_3iZdCxE7AwDd:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/ed5a0b16fac1e47c4e523488a619bed507c83c75/geometry/proximity_engine.cc#L548)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

I think another reason this has to change is that it wouldn't be able to find two "disjoint" faces for a mesh that is just a single tetrahedron.

Per f2f: it looks like part of the condition for FCL saying "invalid mesh" is if there are any vertices not belonging to a face. Therefore constructing an `fcl::Convexd` with 0 faces and non 0 vertices should also work.
</blockquote></details>

Done
___
*[geometry/proximity_engine.cc, line 576 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMXa_Ra4i5WXBo2ZLuJ:-MMXrMCO512udyIPHbt4:bh2ewk3) ([raw file](https://github.com/robotlocomotion/drake/blob/ed5a0b16fac1e47c4e523488a619bed507c83c75/geometry/proximity_engine.cc#L576)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Is this constructor mistakenly using `faces` instead of `disjoint_faces`?
</blockquote></details>

Done (by going away).

**Review by joemasterjohn — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMXwQXW9DKQmLyGB-Rp:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by joemasterjohn — COMMENTED** [review]
+@sherm1 for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMaSivB8M1AetIFJx8R:bppyoqq)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

___
*[geometry/query_object.h, line 186 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb0_q-9vB598bVKdYM:-MMb0_q-9vB598bVKdYN:b9vkbzu) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/query_object.h#L186)):*
> ```objc
>             the same.
>     @warning For Mesh shapes, their convex hulls are used in this query. It is
>             *not* computationally efficient or particularly accurate
> ```

nit: lost the final period here.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few minor comments.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMb5P44-Ec0gSW5A-pD:bty5hbu)* status: 7 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[geometry/proximity_engine.cc, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMarlkg3SgKe8ohqOnb:-MMarlkg3SgKe8ohqOnc:b-ua2o3k) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/proximity_engine.cc#L106)):*
> ```cpp
>   //         face2 has vertices v2_0, v2_1,...,v2_n2-1.
>   //         ...
>   // For fcl::Convex, the `faces` is as an array of integers in this format.
> ```

nit: "the faces is as an array" -> "faces is an array"
___
*[geometry/proximity_engine.cc, line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMasJWU3gGhUF9DuqLs:-MMasJWVEfam2xli4F2x:bbyp1nq) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/proximity_engine.cc#L114)):*
> ```cpp
>   //
>   int TinyObjToFclFaces(const tinyobj::mesh_t& mesh,
>                         std::vector<int>* faces) {
> ```

minor: as written this method _appends_ new faces to an existing `faces` vector, but the documentation does not say so.  It isn't clear whether that's the intent -- please clarify in the documentation. Also the return value is just the number of faces in the input `mesh` which could be different than the total number of faces.

It wasn't obvious to me why this function has a different structure than the Vertices function above. Just needs some clarification. If the intent is that `faces` must start out empty, should enforce that. In that case you could also do `faces->reserve(num_vertices + num_faces)` and avoid some allocations and copying.
___
*[geometry/query_object.h, line 186 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMaxQ3e5944soE9lJwg:-MMaxQ3e5944soE9lJwh:b7f4bbp) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/query_object.h#L186)):*
> ```objc
>             the same.
>     @warning For Mesh shapes, their convex hulls are used in this query. It is
>             *not* computationally efficient or particularly accurate
> ```

nit: missing period
___
*[geometry/query_object.h, line 212 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMaxu-82N1koWGrgXgB:-MMaxu-82N1koWGrgXgC:bzfja8l) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/query_object.h#L212)):*
> ```objc
>        | HalfSpace |  no   |  no   |
>        | Mesh      |  no   |  yes  |
>        | Convex    |  no   |  yes  |
> ```

BTW just to be sure -- currently capsule and half space can't be used as rigid objects in hydroelastic contact?
___
*[geometry/test/proximity_engine_test.cc, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb-4Ql8-24CidhryMh:-MMb-4Ql8-24CidhryMi:b-91529g) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L329)):*
> ```cpp
>     - The nearest point to the sphere on the *concave* geometry is shown as
>       point P. Its distance is 0.5 - R.
>     - The signed distance to the *concave region* will be -(0.5 + R).
> ```

minor: isn't the signed distance to the *concave* region 0.5 - R? I think the formula here is for the maximum penetration into the *convex* hull?
___
*[geometry/test/proximity_engine_test.cc, line 356 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb3NxN94cEtdZsknpi:-MMb3NxO3TNYGhvV63d-:bafx2i3) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L356)):*
> ```cpp
>     engine.UpdateWorldPoses(X_WGs);
> 
>     // Existence of a contact surface depends on the radius of the sphere.
> ```

BTW consider mentioning that we're using the actual (concave) mesh here only. That's strange enough behavior that I think it is worth emphasizing -- I had to stare at this for a while to get it.
___
*[geometry/test/proximity_engine_test.cc, line 363 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb2NRUEYUvKd6VPZYp:-MMb2NRUEYUvKd6VPZYq:b-1kze39) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L363)):*
> ```cpp
>       // Perform the queries with the sphere at the origin; it lies inside the
>       // convex hull giving negative signed distance and non-zero penetration
>       // depth..
> ```

nit: extra period

**Review by SeanCurtis-TRI — COMMENTED** [review]
Comments addressed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMbXU_BAp8kD4CmeRjF:bel95ya)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @joemasterjohn and @sherm1)

___
*[geometry/proximity_engine.cc, line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMarlkg3SgKe8ohqOnb:-MMbVgM_5hjLhaLXnL9l:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/proximity_engine.cc#L106)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "the faces is as an array" -> "faces is an array"
</blockquote></details>

Done
___
*[geometry/proximity_engine.cc, line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMasJWU3gGhUF9DuqLs:-MMbSb8J4LuIH81sxYXq:b-wgrpwf) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/proximity_engine.cc#L114)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: as written this method _appends_ new faces to an existing `faces` vector, but the documentation does not say so.  It isn't clear whether that's the intent -- please clarify in the documentation. Also the return value is just the number of faces in the input `mesh` which could be different than the total number of faces.

It wasn't obvious to me why this function has a different structure than the Vertices function above. Just needs some clarification. If the intent is that `faces` must start out empty, should enforce that. In that case you could also do `faces->reserve(num_vertices + num_faces)` and avoid some allocations and copying.
</blockquote></details>

Done

(I had the same concern about the code when I moved it, but I didn't want to spend the time analyzing it because this was a distraction from what I was trying to get done this week. You've done the analysis, so I'm happy to implement the result.  :)
___
*[geometry/query_object.h, line 212 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMaxu-82N1koWGrgXgB:-MMbVptv5YRYujdBkNBI:bs28jrc) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/query_object.h#L212)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just to be sure -- currently capsule and half space can't be used as rigid objects in hydroelastic contact?
</blockquote></details>

Done 

Good call; half space, yes; capsule no.
___
*[geometry/test/proximity_engine_test.cc, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb-4Ql8-24CidhryMh:-MMbX-Mu9cNzsB-eLFiH:b-8oeggd) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L329)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: isn't the signed distance to the *concave* region 0.5 - R? I think the formula here is for the maximum penetration into the *convex* hull?
</blockquote></details>

Nope. This value is correct. Signed distance is minimum translational distance. If the center of the sphere has a minimum translational distance of 0.5, then the sphere with radius R will be 0.5 + R (it has to move that much farther to bring the sphere out). And since translational distance on the inside is negative, it is -(0.5 + R).
___
*[geometry/test/proximity_engine_test.cc, line 356 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb3NxN94cEtdZsknpi:-MMbWudOBWL9f6Ew-963:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L356)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider mentioning that we're using the actual (concave) mesh here only. That's strange enough behavior that I think it is worth emphasizing -- I had to stare at this for a while to get it.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn (waiting on @joemasterjohn and @sherm1)

___
*[geometry/test/proximity_engine_test.cc, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb-4Ql8-24CidhryMh:-MMbbQ2aBCw3mKk2g5wy:buupi5d) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L329)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Nope. This value is correct. Signed distance is minimum translational distance. If the center of the sphere has a minimum translational distance of 0.5, then the sphere with radius R will be 0.5 + R (it has to move that much farther to bring the sphere out). And since translational distance on the inside is negative, it is -(0.5 + R).
</blockquote></details>

That still seems wrong for the CONCAVE object which is what the comment says. If I'm understanding this correctly the sphere at the origin is located at the center of the "cutout" region of the concave shape. Imagine if its radius were R=0. Then it is outside the concave object altogether by a distance of 0.5, right? So the result should be positive 0.5. The formula would give -(0.5 + 0), that is, -0.5 which is wrong. If I'm misunderstanding this can you please explain?

**Review by sherm1 — COMMENTED** [review]
I still think the comment is wrong. If I'm wrong, then I've misunderstood the test case. Either way I'd like to sort that out before this merges. See my attempt to explain my confusion below.

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMbcRhm2MXw1EMKtNoj:ba6x06h)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Resolved, I believe.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351#-:-MMbpn-48AL_xmrPLS_M:b-fwxony)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[geometry/test/proximity_engine_test.cc, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb-4Ql8-24CidhryMh:-MMbpGHSE6paVlqRT9N4:bpwfbks) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L329)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That still seems wrong for the CONCAVE object which is what the comment says. If I'm understanding this correctly the sphere at the origin is located at the center of the "cutout" region of the concave shape. Imagine if its radius were R=0. Then it is outside the concave object altogether by a distance of 0.5, right? So the result should be positive 0.5. The formula would give -(0.5 + 0), that is, -0.5 which is wrong. If I'm misunderstanding this can you please explain?
</blockquote></details>

Touche; it should be *convex* region. My eyes saw the text "concave" and persisted on thinking "convex". My bad. Your confusion is justified. It was emphasized to offer a contrast to the *previous* line, and I still failed.

The math was right for my *intent* (which is what I focused on), but wrong for my word.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),joemasterjohn

___
*[geometry/test/proximity_engine_test.cc, line 329 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14351#-MMb-4Ql8-24CidhryMh:-MMbqfob-yBmI_EqBwxj:bf2rjc1) ([raw file](https://github.com/robotlocomotion/drake/blob/9a0aeee90d1baa2ccd5d2f74117759f1753c02b8/geometry/test/proximity_engine_test.cc#L329)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Touche; it should be *convex* region. My eyes saw the text "concave" and persisted on thinking "convex". My bad. Your confusion is justified. It was emphasized to offer a contrast to the *previous* line, and I still failed.

The math was right for my *intent* (which is what I focused on), but wrong for my word.
</blockquote></details>

Great, that's what I thought -- thanks!

**Pull request merged**
