### PR TITLE
Remove MBP's awareness of SG<AutoDiff> support

### LINKED ISSUE #11454: [geometry] Remove MBP's awareness of SG<AutoDiff> support.
In issue #11120, the historical behavior of MBP<AutoDiff> and SG<AutoDiff> was that attempting to compute derivatives threw an exception. This is because while SG was *compilable* with `AutoDIff`, it couldn't produce viable derivatives. MBP opted to throw in this scenario rather than to leak bad answers out.

This gave rise to PR #11143 which would test to see if collisions existed and only throw if there were contacts. After all, no contact derivatives in the absence of contacts *is* the correct answer.

### Task

MBP should *not* have the burden of implementing these semantics. It should be a property of SG and buried *in* SG. Currently MBP has a [*bunch* of lines](https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.cc#L912-L956) implementing default unsupported behavior and scalar-dependent behavior:

All of that should disappear into one, simple implementation template on `T`.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #11454

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
CI failure is just that `plant_test.py` runs `scene_graph` queries against non-symbolic T with a colliding configuration. So, on the line that calls `ComputePointPairPenetration()`, you'll need to put a guard based on the type of `T`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MLwnHpbEuu47nssCPJQ:bolez8m)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by avalenzu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[geometry/proximity_engine.cc, line 742 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MLwo_pf7MnRmqeKryB3:-MLwo_pf7MnRmqeKryB4:b-kl5i7u) ([raw file](https://github.com/robotlocomotion/drake/blob/ac175672c47b246b1b2cb8659147e7060043ae83/geometry/proximity_engine.cc#L742)):*
> ```cpp
>     } else {
>       // TODO(hongkai.dai): for T != double, compute the contacts for allowable
>       // primitives (sphere-to-sphere, sphere-to-box, etc).
> ```

Yes, this is probably a better approach to getting preliminary support for derivatives through contact than the one I started with in my [dev branch](https://github.com/avalenzu/drake/commit/96664b5cad3d8cdc23f133a6ff090813a2ca6f62). My prototype made MbP do *more* more work.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Sean.

I am a little bit nervous when this PR changes the code implementation, but doesn't add tests. Are you OK with it?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MLxCps_9ihwZIJDH2Ta:bngq1kh)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
I can appreciate your concern and it's well justified. Here's what I'd suggest.

You don't need to appreciably modify the MBP tests (except for the test in `plant_test.py` mentioned above -- which isn't *really* an MBP test...it is, inexplicably, an SG test -- see below.)  From MBP's public API perspective there's been no change.

However, there *has* been a change to SG. So, I'd argue that there *should* be a new test for SG. Specifically, there should be a test in `penetration_as_point_pair_callback_test.cc` exercising the behavior you've just added.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MLxQf5JCD9FUbNhw7vr:bfv5mgw)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMI7Avj7-PpHW8KDi0Y:b-j3v9j6)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've sent you a patch with some add'l tests and the fix in the proximity code to make the tests pass.

(First pass done.)

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMMlo-09QFDhojTD_Q5:b-b7h9zm)* status: 10 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1855 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMO2a21VmRzp0Q3529:-MMMO2a21VmRzp0Q352A:b-5kh0nu) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1855)):*
> ```Python
>     @numpy_compare.check_nonsymbolic_types
>     def test_scene_graph_queries(self, T):
>         # SceneGraph does not support `Expression` type.
> ```

BTW Could you put a *huge* TODO here (with my name) suggesting that unit tests of `QueryObject`/`SceneGraph` don't belong in `plant_test.py`, they belong in `geometry_test.py` and that this should be moved. Failing that, the purpose of this test (and possibly its name) should be clarified.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 1882 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMM5zD1rGayRnInrZ6:-MMMM5zE9aAVq8tBMMYR:b-16uns8) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1882)):*
> ```Python
>         # TODO(hongkai.dai): currently if there are bodies in contact, then we
>         # only support ComputePointPairPenetration() for T=float. After we
>         # resolve issue #11455 we should support AutoDiffXd for primitive
> ```

nit: "...we should support AutoDiffXd for __*some*__ primitive geometries as well." Not all.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 1884 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMMdoR3SiR3TDqYEl8:-MMMMdoR3SiR3TDqYEl9:b-lfk5d4) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1884)):*
> ```Python
>         # resolve issue #11455 we should support AutoDiffXd for primitive
>         # geometries as well.
>         if isinstance(T, float):
> ```

This test *used* to be executed for T = float and T = AutoDiffXd, presumably. Now it is only executed for T = float. That seems like a regression in the test. I should imagine that you wouldn't need to eliminate executions -- only guard against T-dependent results.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 1926 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMN4evCpKLuSomBcDI:-MMMN4evCpKLuSomBcDJ:bdfnufd) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1926)):*
> ```Python
>         # resolve issue #11455 we should support AutoDiffXd for primitive
>         # geometries as well.
>         if isinstance(T, float):
> ```

This test is *really* difficult to understand. Nothing in the body obviously appears dependent on T. It's only after thinking about this carefully, one can recognize that `point_pair` only exists *conditionally* based on the previous incantation of `if isinstance(T, float)`. You should definitely make that clear. Ideally, spatial locality would be a big friend here, but, failing that, we'd need a comment making it clear why this is optional.

Of course, that may all go away based on the response to my previous comment about guarding the executation *at all*.
___
*[geometry/proximity_engine.cc, line 749 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMOn39AcXze0YXVmt_:-MMMOn39AcXze0YXVmta:b-9n9jw4) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/proximity_engine.cc#L749)):*
> ```cpp
>             "ComputePointPairPenetration(): Some of the bodies in the model "
>             "are in contact. Currently we only support computing penetration "
>             "for SceneGraph<double>. Refer to Github issues #11455 for "
> ```

nit s/issues/issue
___
*[geometry/proximity_engine.cc, line 872 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMPA8a6Xil0AYlIQcH:-MMMPA8b7b_RVsyAw0uI:b-nr8epk) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/proximity_engine.cc#L872)):*
> ```cpp
>               OrderPointPair<double>);
>     if constexpr (std::is_same<T, double>::value) {
>       *point_pairs = point_pairs_double;
> ```

nit: Please do a `std::move(point_pairs_double)` here?
___
*[geometry/proximity_engine.cc, line 878 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMPmMX3iJBdyfK5km5:-MMMPmMY3QtqaZRt5TYU:b-amyyom) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/proximity_engine.cc#L878)):*
nit: This error message isn't quite right. How about:

> ComputeContactSurfacesWithFallback() model has bodies in contact that could not be resolved with hydroelastic contact. The fallback contact model
(penetration as point pair) only supports T = double.
___
*[geometry/query_object.h, line 183 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMLNy44vC9wNj5-rD4:-MMMLNy44vC9wNj5-rD5:bjelyzs) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/query_object.h#L183)):*
> ```objc
>             consistent -- for fixed geometry poses, the results will remain
>             the same.
>    @warning This silently ignores Mesh geometries (but Convex mesh geometries
> ```

nit This should clearly document that this throws if:
  - T = autodiff and
  - objects actually collide.
___
*[geometry/query_object.h, line 259 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMLi441OXmp2Hj6AG3:-MMMLi441OXmp2Hj6AG4:b8aykfd) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/query_object.h#L259)):*
> ```objc
>    @param[out] point_pairs  The vector that fall back point pair data will be
>                             added to. The vector will _not_ be cleared.
>    @pre Neither `surfaces` nor `point_pairs` is nullptr.  */
> ```

nit: This should get similar documentation about the conditions under which it throws (see note on `ComputePointPairPenetration()`).
___
*[geometry/test/proximity_engine_test.cc, line 1869 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMSkrL5Kl3rmVANtdp:-MMMRhCy2QDj8t9rJ0p5:b9l8zz6) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/test/proximity_engine_test.cc#L1869)):*
> ```cpp
> }
> 
> GTEST_TEST(ProximityEngineTests, PenetrationSingleAnchoredAutoDiff) {
> ```

I think you can completely eliminate this test. I don't see that it does anything that the addition to `PenetrationDynamicAndAnchored` doesn't already do below. The other test:

  - transomogrifies the engine (which is the typical use case)
  - Evaluates the query and confirms exception thrown.
___
*[multibody/plant/multibody_plant.h, line 4678 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMGNju5TZ31moXP-sV:-MMMGNju5TZ31moXP-sW:b-b4oxg7) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/multibody/plant/multibody_plant.h#L4678)):*
> ```objc
> template <>
> void MultibodyPlant<double>::CalcHydroelasticWithFallback(
>     const systems::Context<double>&,
> ```

nit: This should be addressed in the same way. Should generally work for T, but throw for T = Expression.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Apparently I booby trapped you. :-/

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMNjxe880ZNfuxzZcUB:blbjz30)* status: 10 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1884 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMMdoR3SiR3TDqYEl8:-MMNtldR8qUwdllFtY69:b11q6rt) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1884)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This test *used* to be executed for T = float and T = AutoDiffXd, presumably. Now it is only executed for T = float. That seems like a regression in the test. I should imagine that you wouldn't need to eliminate executions -- only guard against T-dependent results.
</blockquote></details>

Done. I caught the error when T!=float. 
___
*[bindings/pydrake/multibody/test/plant_test.py, line 1926 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMN4evCpKLuSomBcDI:-MMNu8rIECOmP0TaFOGm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/bindings/pydrake/multibody/test/plant_test.py#L1926)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This test is *really* difficult to understand. Nothing in the body obviously appears dependent on T. It's only after thinking about this carefully, one can recognize that `point_pair` only exists *conditionally* based on the previous incantation of `if isinstance(T, float)`. You should definitely make that clear. Ideally, spatial locality would be a big friend here, but, failing that, we'd need a comment making it clear why this is optional.

Of course, that may all go away based on the response to my previous comment about guarding the executation *at all*.
</blockquote></details>

Done.
___
*[geometry/test/proximity_engine_test.cc, line 1869 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMMSkrL5Kl3rmVANtdp:-MMNz8jjBhJUh8oWkhr-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/212a99987f6c00fdd63f5a468ec493585bd55f8d/geometry/test/proximity_engine_test.cc#L1869)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I think you can completely eliminate this test. I don't see that it does anything that the addition to `PenetrationDynamicAndAnchored` doesn't already do below. The other test:

  - transomogrifies the engine (which is the typical use case)
  - Evaluates the query and confirms exception thrown.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two small items. Ready for platform review, +@sammy-tri.

> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMR0HbJEoKxX5BeCQMh:b-lms4fv)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @sammy-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1891 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMQzbYMB56Pvw1QDoqY:-MMQzbYMB56Pvw1QDoqZ:buu25rs) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/bindings/pydrake/multibody/test/plant_test.py#L1891)):*
> ```Python
>             self.assertIsInstance(point_pair, PenetrationAsPointPair_[float])
>         else:
>             try:
> ```

nit: you should use something from the [`self.assertRaises` family](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) here.
___
*[geometry/query_object.h, line 185 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMR-Khx8AwQ1OlrnGuP:-MMR-Khy07ezhYdNI1sI:b1l6l3f) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/geometry/query_object.h#L185)):*
> ```objc
>    @warning This silently ignores Mesh geometries (but Convex mesh geometries
>             are included).
>    @throws if T = AutoDiffXd and object actually collides. TODO(hongkai.dai):
> ```

BTW  It's better to keep the `todo` out of the rendered doxygen. One way to do that is to surround it with html comments: `<!-- TODO(hongkai.dai)... -->`

However, since you're already planning a follow-on PR to address this PR it's not the *end* of the world. I'll defer to you. Same applies below.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri and @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1891 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMQzbYMB56Pvw1QDoqY:-MMRSzgI9tT9LbzLgpI1:b30ya46) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/bindings/pydrake/multibody/test/plant_test.py#L1891)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: you should use something from the [`self.assertRaises` family](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) here.
</blockquote></details>

Done. TIL assertRaisesRegex.
___
*[geometry/query_object.h, line 185 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMR-Khx8AwQ1OlrnGuP:-MMRTGn467CFTuSVrb94:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/geometry/query_object.h#L185)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW  It's better to keep the `todo` out of the rendered doxygen. One way to do that is to surround it with html comments: `<!-- TODO(hongkai.dai)... -->`

However, since you're already planning a follow-on PR to address this PR it's not the *end* of the world. I'll defer to you. Same applies below.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1891 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMQzbYMB56Pvw1QDoqY:-MMS-SUJ2EgKn6Ix4545:bhxqge) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/bindings/pydrake/multibody/test/plant_test.py#L1891)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. TIL assertRaisesRegex.
</blockquote></details>

I'm somewhat surprised you didn't use it, since your original formulation of the test *was* testing for the error message.  :) Nonetheless, I'm marking myself satisified.
___
*[geometry/query_object.h, line 185 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMR-Khx8AwQ1OlrnGuP:-MMS-_zdE63_ffsapdBO:b-xv7u19) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/geometry/query_object.h#L185)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit Sorry. This is something you *can't* do. Putting a comment between the doxygen and the declaration interferes with the pydrake documentation generation. You can put it inside with html comments, or pull it outside and put it *before* the doxygen. But now it's a defect.  :(

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 8 of 10 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMS4di649tNPWcoTTmd:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/multibody/test/plant_test.py, line 1891 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMQzbYMB56Pvw1QDoqY:-MMSYzu-55wUi-2gf7Tl:b-zgs2wc) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/bindings/pydrake/multibody/test/plant_test.py#L1891)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm somewhat surprised you didn't use it, since your original formulation of the test *was* testing for the error message.  :) Nonetheless, I'm marking myself satisified.
</blockquote></details>

Done, I changed to use assertRaisesRegex.
___
*[geometry/query_object.h, line 185 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14324#-MMR-Khx8AwQ1OlrnGuP:-MMSYyDSCW1KdZ7tWvvD:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/21b842b212d4ba54ee038a5ccb34bdf3c5808dd8/geometry/query_object.h#L185)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit Sorry. This is something you *can't* do. Putting a comment between the doxygen and the declaration interferes with the pydrake documentation generation. You can put it inside with html comments, or pull it outside and put it *before* the doxygen. But now it's a defect.  :(
</blockquote></details>

Done, thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
Huzzah!

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14324#-:-MMSl-bIAwFWdspqm6d9:bd5okq0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
