### PR TITLE
Specify the RGBA values directly in the iiwa sdf

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@jwnimmer-tri for all review, thanks!

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094#-:-LGWexKN0uq1jrRszt3v:b-lx95wd)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWmyrEE4VyCwY5ZJt-:-LGWmyrEE4VyCwY5ZJt0:bchb46o) (no related file):*
This added some literal tabs.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWnDKACNaLfhB_LK3w:-LGWnDKBDFRS7It5DZOD:b4tnr4r) (no related file):*
I suspect 4 sig figs for RGB values would be good enough?

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWnTipDg4WJENcouFS:-LGWnTipDg4WJENcouFT:b-hcglkq) (no related file):*
The new literal values don't match my /usr/share/gazebo-7/media/materials/scripts/gazebo.material values.  Where did they come from?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)*

**Comment by sammy-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWmyrEE4VyCwY5ZJt-:-LGWpnji9nfMr3uHpZd8:b-tb136w) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This added some literal tabs.
</blockquote></details>

Fixed.  I thought I fixed that in my emacs config but clearly I was wrong (and can't even figure out how, actually.  I even just crashed emacs trying to fix it though I'm not 100% sure of the cause...).

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWnTipDg4WJENcouFS:-LGWq7u88INC1VqpBkJU:b-qy267w) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The new literal values don't match my /usr/share/gazebo-7/media/materials/scripts/gazebo.material values.  Where did they come from?
</blockquote></details>

They came from the iiwa urdf...   or, more specifically iiwa_description/urdf/materials.xacro.  I don't know why gazebo changed them when converting the file.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWnDKACNaLfhB_LK3w:-LGWqWUN8oMm0Tv-SrMb:b396gwn) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I suspect 4 sig figs for RGB values would be good enough?
</blockquote></details>

I'm sure your're correct about that, I was going to preserve the literal values from the other declarations  (the .xacro file where they originate specifies orange as ` <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>` so I could switch to the integer values presumably).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)*

**Comment by sammy-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWmyrEE4VyCwY5ZJt-:-LGWssfVAGmuUlcJU8ZJ:b-15zhaf) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Fixed.  I thought I fixed that in my emacs config but clearly I was wrong (and can't even figure out how, actually.  I even just crashed emacs trying to fix it though I'm not 100% sure of the cause...).
</blockquote></details>

(fwiw I think I finally figured it out)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWnDKACNaLfhB_LK3w:-LGWzOCB6D5m2yBI9fmz:b-wyjoha) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm sure your're correct about that, I was going to preserve the literal values from the other declarations  (the .xacro file where they originate specifies orange as ` <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>` so I could switch to the integer values presumably).
</blockquote></details>

OK Yeah, I see now the high-precision sig figs actually match our URDFs already in-tree, so I guess whatever.

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzbYQ2LFWrj0RK6V6:-LGWzbYR9PzKteCMPNOi:b5w9bt9) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L70)):*
> ```
>         </geometry>
>         <material>
>           <diffuse>0.4 0.4 0.4 1.0</diffuse>
> ```

This one used to be orange?

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 170 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzhqY0FOXu62w1N31:-LGWzhqY0FOXu62w1N32:b5w9bt9) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L170)):*
> ```
>         </geometry>
>         <material>
>           <diffuse>0.4 0.4 0.4 1.0</diffuse>
> ```

This one used to be orange?

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzjfG0GIfN6FMO6xj:-LGWzjfG0GIfN6FMO6xk:b5w9bt9) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L270)):*
> ```
>         </geometry>
>         <material>
>           <diffuse>0.4 0.4 0.4 1.0</diffuse>
> ```

This one used to be orange?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)*

**Comment by sammy-tri** [comment]
Review status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzbYQ2LFWrj0RK6V6:-LGX-2usEtMa9BwaUTkU:bb8jk1x) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This one used to be orange?
</blockquote></details>

Not according to https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/iiwa_description/urdf/iiwa14.xacro#L98  For some reason the gazebo conversion *also* turned orange links to gray.

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 170 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzhqY0FOXu62w1N31:-LGX-DuM39K_s8JsaScI:b-tcesif) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L170)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This one used to be orange?
</blockquote></details>

https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/iiwa_description/urdf/iiwa14.xacro#L200 has it gray (see above)

---

*[manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, line 270 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9094#-LGWzjfG0GIfN6FMO6xj:-LGX-Jdw0EInbn_SjC19:b4aby3w) ([raw file](https://github.com/robotlocomotion/drake/blob/cef5d694144ad3c75b69d806e6e613ab666c71d7/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf#L270)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This one used to be orange?
</blockquote></details>

https://github.com/RobotLocomotion/drake/blob/master/manipulation/models/iiwa_description/urdf/iiwa14.xacro#L302 is grey (gazebo's urdf->sdf conversion is not good)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094)*

**Comment by jwnimmer-tri** [comment]
:lgtm: all.

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9094#-:-LGX0kPaAethIMKJi_Yw:bb6y9i4)*

**Pull request merged**
