### PR TITLE
Make Diagrams own their subsystems.

### PR DESCRIPTION
**Pull request by david-german-tri**
+@amcastro-tri for feature review.  This is a prerequisite for #3455.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3469)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
Excellent, it looks great! I just added a bunch of BTW comments. Otherwise it :lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 335 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjrdO97E6rGQlxiTVN:-KRjrdO97E6rGQlxiTVO:b-j5cwh2) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram.h#L335)):*
> ```objc
>   }
> 
>   void Own(std::vector<std::unique_ptr<System<T>>> registered_systems) {
> ```

At least for developers only. Could you add one or two lines of comment here for this method so that it explains it is called only from within `DiagramBuilder` to transfer the ownership from the `DiagramBuilder` into the `Diagram`. Is that correct?

---

*[drake/systems/framework/diagram.h, line 347 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjrEGAcGUKBQlychFj:-KRjrEGAcGUKBQlychFk:bveko8v) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram.h#L347)):*
> ```objc
>       DRAKE_DEMAND(it != sorted_systems_map_.end());
>     }
>     // All of those checks having passed, take ownership of the subsystems.
> ```

BTW, would it be worth here to assign a unique id to each system since now we own them? (and maybe you are planning to do so in subsequent PR's) That way if the subcontexts are numbered in the same exact way they subsystems can easily reference their chunk by using this unique (global) index. Super fast random access to my context.

---

*[drake/systems/framework/diagram_builder.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnOR0-c2SwoW9TIPv:-KRjnOR1x_Qb72J0z-Vn:b8zie2l) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L35)):*
> ```objc
>   /// pointer to the System, which will remain valid for the lifetime of the
>   /// Diagram built by this builder.
>   ///
> ```

BTW, [here in Drake](https://github.com/RobotLocomotion/drake/blob/master/drake/common/nice_type_name.h#L16) there is a nice example on how to list code spinets for usage that will render nicely in Doxygen.

---

*[drake/systems/framework/diagram_builder.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjppZFbAqRwsqS3LWd:-KRjppZFbAqRwsqS3LWe:b2ladv3) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L41)):*
> ```objc
>   /// @tparam S The type of system to add.
>   template<class S>
>   S* AddSystem(std::unique_ptr<S> system) {
> ```

BTW, I like this. I just wonder if we should also have a `Diagram::AddSystem` now.

---

*[drake/systems/framework/diagram_builder.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnh0MJqcplfQM4Ncc:-KRjnh0MJqcplfQM4Ncd:bwhazqh) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L63)):*
> ```objc
>   ///
>   /// @tparam S The type of System to construct. Must subclass System<T>.
>   template<class S, typename... Args>
> ```

BTW, ha! this is cool

---

*[drake/systems/framework/primitives/pid_controller.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjsLTT7hj0dCy3m8X5:-KRjsLTT7hj0dCy3m8X6:bj2ajxz) ([raw file](https://github.com/robotlocomotion/drake/blob/bec8abe91e4cd23a2e3793fe59c1c00a75201d40/drake/systems/framework/primitives/pid_controller.cc#L6)):*
> ```cpp
> #include "drake/systems/framework/diagram_builder.h"
> 
> using std::make_unique;
> ```

BTW, why did you remove the `using std::make_unique`? that way you could make the lines below five characters shorter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRjtoWTi-Acz5cvG25_:bkrcu89)*

**Comment by sherm1** [comment]
:lgtm_strong: -- woohoo! I like this a lot. A few BTWs.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 347 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjrEGAcGUKBQlychFj:-KRkAKbptXpEfJ7JLB5R:b-k8xbkw) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram.h#L347)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, would it be worth here to assign a unique id to each system since now we own them? (and maybe you are planning to do so in subsequent PR's) That way if the subcontexts are numbered in the same exact way they subsystems can easily reference their chunk by using this unique (global) index. Super fast random access to my context.
</details>
BTW, now that you have ownership you can write into the subsystems so it would be possible for a subsystem to know its own index if that were useful.

---

*[drake/systems/framework/diagram_builder.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRk8uW6tGN4COig4M6L:-KRk8uW6tGN4COig4M6M:b-2ks4fx) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L54)):*
> ```objc
>   ///
>   ///   DiagramBuilder<double> builder;
>   ///   builder.AddSystem<Foo<double>>("name", 3.14);
> ```

BTW, show the returned pointer being used here now? Might even be a legitimate use of `auto` for extra swagger. (Also `@code`/`@endcode` for good doxygen formatting and colorizing.)

---

*[drake/systems/framework/diagram_builder.h, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnh0MJqcplfQM4Ncc:-KRk9f-ysY7ggbk1-mHU:bb6mt9b) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L63)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, ha! this is cool
</details>
:+1:

---

*[drake/systems/framework/primitives/pid_controller.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRkApnnP6V4Zgd-6VIp:-KRkApnnP6V4Zgd-6VIq:bbveeaa) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/primitives/pid_controller.h#L78)):*
> ```objc
>   Gain<T>* proportional_gain_ = nullptr;
>   Gain<T>* integral_gain_ = nullptr;
>   Gain<T>* derivative_gain_ = nullptr;
> ```

BTW, I like how that came out!

---

*[drake/systems/framework/test/diagram_builder_test.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRkB0RvL9PO3tcMoG7U:-KRkB0RvL9PO3tcMoG7V:b-65o8qj) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/test/diagram_builder_test.cc#L38)):*
> ```cpp
>   //        |------------------------------|
>   auto adder = builder.AddSystem<Adder>(2 /* inputs */, 1 /* length */);
>   auto integrator = builder.AddSystem<Integrator>(1 /* length */);
> ```

BTW, sweet!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRkBqAckOxrhnNCYhqS:b-bu57r2)*

**Comment by jwnimmer-tri** [comment]
I thought that ownership of subsystems by the Builder was going to be optional, and possibly the default, but that we would allow for patterns where it's just working with aliases.  I guess we could add that back later if or when we need it?

Is the motivation for this change only to support ownership as a convenience, or is there some deeper reason why only using aliases makes something difficult?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRkIOJPNawv7ikX_8Wo:b-wj15ak)*

**Comment by sherm1** [comment]
Per virtual f2f with @david-german-tri yesterday, the most proximal motivation was the need to store back pointers in subsystems to facilitate inter-subsystem triggering of computations. There are also a lot of other good reasons to have diagrams own their subsystems. 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRkLKTYOsJckPq1Lz6I:b-unpnnh)*

**Comment by david-german-tri** [comment]
@RussTedrake decided that input evaluation should be lazy.  As a result, Systems need to ask their containing Diagram to evaluate their inputs on demand, which means they need to have a pointer to their containing Diagram, which means it needs to be unique, which means (IMO, though there might conceivably be some wiggle room here) that we should require ownership as well.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRnedOsTlEm5G6mTuyP:bn95huu)*

**Comment by jwnimmer-tri** [comment]
The new requirement to add before connecting will break e.g. https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/demo_multi_car.cc and a few other main programs there.  I am about 25% through backfilling acceptance tests that will evidence this, but if it is easy for you to fix those files as well (anything that uses Diagram), that would be nice.  Else I'll submit a follow-up PR with the fixes and/or tests, depending on which I get done first.

**Comment by david-german-tri** [comment]
Done.  (I verified that the programs compile as edited.)

---

Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 335 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjrdO97E6rGQlxiTVN:-KRopS8njFnTCwl_8_2F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram.h#L335)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> At least for developers only. Could you add one or two lines of comment here for this method so that it explains it is called only from within `DiagramBuilder` to transfer the ownership from the `DiagramBuilder` into the `Diagram`. Is that correct?
</details>
Done.

---

*[drake/systems/framework/diagram.h, line 347 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjrEGAcGUKBQlychFj:-KRopZGKgHrDnXDbIO4Q:b-go9m0d) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram.h#L347)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, now that you have ownership you can write into the subsystems so it would be possible for a subsystem to know its own index if that were useful.
</details>
Possibly.  I won't bolt it on to this PR, but it's easy enough to add in the future if there's a need.

---

*[drake/systems/framework/diagram_builder.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnOR0-c2SwoW9TIPv:-KRoplAEKz_JDveroLNn:b-3l59rw) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, [here in Drake](https://github.com/RobotLocomotion/drake/blob/master/drake/common/nice_type_name.h#L16) there is a nice example on how to list code spinets for usage that will render nicely in Doxygen.
</details>
That is nice.  Done.

Also, according to Google, a spinet is a kind of eighteenth-century piano. ;-)

---

*[drake/systems/framework/diagram_builder.h, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjppZFbAqRwsqS3LWd:-KRopxTGJgRi51L_SstA:b-tmroh7) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, I like this. I just wonder if we should also have a `Diagram::AddSystem` now.
</details>
My feeling is no - Diagrams are const once built.

---

*[drake/systems/framework/diagram_builder.h, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRk8uW6tGN4COig4M6L:-KRoqrTAfc4sXj0MkPlS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L54)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, show the returned pointer being used here now? Might even be a legitimate use of `auto` for extra swagger. (Also `@code`/`@endcode` for good doxygen formatting and colorizing.)
</details>
Done.

---

*[drake/systems/framework/primitives/pid_controller.cc, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjsLTT7hj0dCy3m8X5:-KRor78hIRinB2OuAbkA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bec8abe91e4cd23a2e3793fe59c1c00a75201d40/drake/systems/framework/primitives/pid_controller.cc#L6)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, why did you remove the `using std::make_unique`? that way you could make the lines below five characters shorter
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-:-KRouKL39O2vWo9pbWt9:bpph998)*

**Comment by amcastro-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/framework/diagram_builder.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnOR0-c2SwoW9TIPv:-KRp2KnisnPydJ0uEQA-:bgvbupw) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L35)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> That is nice.  Done.
> 
> Also, according to Google, a spinet is a kind of eighteenth-century piano. ;-)
</details>
haha! Good to know that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469)*

**Comment by amcastro-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469)*

**Comment by sherm1** [comment]
*[drake/systems/framework/diagram_builder.h, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3469#-KRjnOR0-c2SwoW9TIPv:-KRp9qOMBj37Otm-UZUy:bz70avb) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c03785f8129fc21dc78e92c615c3b5907842bc/drake/systems/framework/diagram_builder.h#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> haha! Good to know that
</details>
We native English speakers might call a small chunk of code a "snippet"!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469)*

**Comment by sherm1** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3469)*

**Pull request merged**
