### PR TITLE
pydrake: Re-format using DontAlignAfterOpenBracket

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This style is more horizontally compact, which tends to make the bindings slightly easier to read.  Also, as we start to format non-wrapper code such as `//bindings/pydrake/common` this indentation style will better match the prevailing Drake habits.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10074)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
___
*[.clang-format, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/10074#-LSFaLAr3FqOLmw00lQx:-LSFaLAr3FqOLmw00lQy:b7q58cv) ([raw file](https://github.com/robotlocomotion/drake/blob/20e644011f59ed11e889c7a89e53b7957a6fee34/.clang-format#L1)):*
> ```YAML
> # -*- yaml -*-
> ```

nit Locking in r2 with a post.

**Pull request merged**
