### PR TITLE
Upgrade externals to latest releases 

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16167)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
meshcat_python also needs to be updated but is currently failing local testing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16167#-:-Mprzm0T7mk1XQCsAJ4k:b-k8njao)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for feature review, including the meshcat_python manual test

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16167#-:-Mps10ze2qixIyZLFDyT:bl61jig)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both on code reviews, and locally tested meshcat_manual_test.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16167#-:-MpsGYqaAELNO6SINP5k:b-txu9va)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

Once that passes, this will need a rebase and force-push, and then we can merge.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16167)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Pull request merged**
