### PR TITLE
Provide macros for trace/debug logging that don't evaluate arguments

### PR DESCRIPTION
**Pull request by sherm1**
Our awesome logging tool spdlog provides macros SPDLOG_TRACE and SPDLOG_DEBUG so we can include tracing and debugging output at zero cost when NDEBUG is defined (typically in Release builds). In case NDEBUG is _undefined_ (meaning assertions etc. are enabled), these macros are expanded and evaluate their arguments _regardless_ of whether trace or debug logging is actually enabled. If the arguments are expensive to evaluate, and the macros are present in performance-sensitive inner loops, this can be painfully slow.

This PR adds alternative macros DRAKE_SPDLOG_TRACE and DRAKE_SPDLOG_DEBUG that:
- evaporate if NDEBUG is defined, otherwise
- check the log level before evaluating their arguments.

(See [discussion](https://reviewable.io/reviews/robotlocomotion/drake/8050#-L5MNznTPOK9IWnKrGmw) in review of #8050.)

Probably this should be how the original macros behave. I filed [an issue](https://github.com/gabime/spdlog/issues/638) at spdlog.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8087)

### CODE REVIEW

**Comment by sherm1** [comment]
+@jwnimmer-tri for feature & platform unless you think someone else should take a look.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8087#-:-L5RTCrS-ugjMafYSkJL:bdqrah)*

**Comment by jwnimmer-tri** [comment]
:lgtm: but let's get one more platform reviewer to agree with the proposal before we merge.  I've asked on slack.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/text_logging_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8087#-L5TtvUvYhnryFCfeIEP:-L5TtvUvYhnryFCfeIEQ:b-1icfvy) ([raw file](https://github.com/robotlocomotion/drake/blob/cefc2cb79dd60d998fde4b7a23d327c710aed959/common/test/text_logging_test.cc#L20)):*
> ```cpp
> // Call each API function and macro to ensure that all of them compile; the
> // cmake script will cause this to be compiled in both spdlog and non-spdlog
> // modes.
> ```

FYI The second half of this comment is stale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8087#-:-L5Tuqi0T4fYoUIwJcau:b8sgdy3)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: This makes perfect sense to me.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8087#-:-L5U9JB08-3aV3wFSO53:b-5eact8)*

**Comment by sherm1** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[common/test/text_logging_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8087#-L5TtvUvYhnryFCfeIEP:-L5UPHuyyHtZKiqwJ0j6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cefc2cb79dd60d998fde4b7a23d327c710aed959/common/test/text_logging_test.cc#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI The second half of this comment is stale.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8087)*

**Comment by chrahunt** [comment]
Saw this on the spdlog issue. In its current form this will break unbraced if statements, e.g.

```cpp
if ( condition )
    DRAKE_SPDLOG_TRACE(logger, ...);
else
    do_something_else()
```

The `else` will be associated with the `if` from the expanded `DRAKE_SPDLOG_TRACE` macro. See [here](https://github.com/wxWidgets/wxWidgets/blob/20a98406f06f0392f0b303c0deb6c630e17704fd/include/wx/log.h#L1271) for a correct construction.

**Comment by jwnimmer-tri** [comment]
Yikes, how did I miss that during review!  We need the standard `do {} while (0)` macro trick on these.  I'll open an issue.  Thanks @chrahunt.

**Pull request merged**
