### PR TITLE
Better deal with -pthread in pkg_config_repository

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Through some chain of pkg-config machinations that I cannot understand, the `gtk+-2.0.pc` (on Ubuntu 16.04) asks for -pthread in --cflags but not in --libs, even though all of its dependencies appear to list it in either both places or none.  In any case, rather than insisting on pkg-config being consistent, we choose to just use linkopts for pthreads, always.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771#-:-LBzmH_Y4pzdhNvTyWaA:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Comment by sammy-tri** [comment]
The implementation looks like an improvement, one BTW question below.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/workspace/pkg_config.bzl, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8771#-LC-ocVD79ApB4mRo831:-LC-ocVD79ApB4mRo832:b-n44ipc) ([raw file](https://github.com/robotlocomotion/drake/blob/efd7ef3717e9af7c624719d312db7e905aa676c5/tools/workspace/pkg_config.bzl#L140)):*
> ```Python
>             # We can't meaningfully pass this as a copts, and the -D_REENTRANT
>             # stuff implied by -pthread while compiling isn't really our job to
>             # fix anyway, so instead we'll only pass it into the linkopts.
> ```

BTW I feel like this comment is a little light in terms of explaining what's broken which we wouldn't fix (even with some searching I didn't understand it).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771#-:-LC-opjD3cbpUEZgLIi3:bau4m94)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 140 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8771#-LC-ocVD79ApB4mRo831:-LC0DPDwAt-NWylkse2B:b-1cpayq) ([raw file](https://github.com/robotlocomotion/drake/blob/efd7ef3717e9af7c624719d312db7e905aa676c5/tools/workspace/pkg_config.bzl#L140)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I feel like this comment is a little light in terms of explaining what's broken which we wouldn't fix (even with some searching I didn't understand it).
</blockquote></details>

Is this better?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.bzl, line 141 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8771#-LC0DoitAOM0qmm4NrVS:-LC0DoitAOM0qmm4NrVT:bod99wb) ([raw file](https://github.com/robotlocomotion/drake/blob/05f743588186dd3fd3e8f5396923387b91e9ade3/tools/workspace/pkg_config.bzl#L141)):*
> ```Python
>             # When compiling the typical effect of -pthread is to -D_REENTRANT;
>             # when linking the typical effect of -pthread is to -lpthread.  In
>             # Bazel, we can't pass -pthread in a cc_library's defines (its not
> ```

BTW `it's` or `it is`

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8771#-:-LC0IZwR0wzeZqtl3N1e:bnfp4nl)*

**Pull request merged**
