### PR TITLE
Bump CRU and VGT externals to latest

### PR DESCRIPTION
**Pull request by calderpg-tri**
Updates `common_robotics_utilities` and `voxelized_geometry_tools` to latest. Changes in the externals:
- Change in CRU to properly handle varying Eigen alignment requirements in Eigen alignment enforcement
- Adds backend enumeration in VGT to enumerate possible voxelizers, and uses that enumeration to run voxelizer test case on all possible voxelizers (note - only the basic CPU implementation is available here).

+@ggould-tri for feature review, thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14728)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14728#-:-MUoOOr19RHAGCa6134K:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by calderpg-tri** [comment]
+@sherm1 for platform review, thanks!

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:. Ready to merge pending all-green CI.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14728#-:-MUolrYoEVsOqY5b2bNh:bdrrap8)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
