### PR TITLE
Add symbolic Eval and CheckSatisfied to Constraint/Cost

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai for feature-review, please.

The first PR is the result of running clang-format. Suggested review order is:

 - `solvers/evaluator_base.h` and tests
 - `solvers/constraint.{h,cc}` and tests
 - `solvers/cost.{h,cc}` and tests
 - `solvers/dreal_solver.cc` and tests

The other changes are mostly adding symbolic `DoEval` to the existing subclasses of `Cost`/`Constraint`.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056#-:-LFxaqVp0-4-lm1oVLHj:bjxuh8l)*

**Comment by hongkai-dai** [comment]
In each cost/constraint, we have the DoEval function for three scalar types: double, AutoDiffXd, symbolic::Variable, and the computation is basically the same. Does it make sense to write a template version for each of the derived cost/constraint? For example, in `cost.cc`, for `LinearCost`, we can do
```C++
template <typename T, typename U>
void LinearCost::DoEvalGeneric(const Eigen::Ref<const VectorX<T>>& x, VectorX<U>& y) {
  y.resize(1);
  y(0) = a_.dot(x) + b_;
}

void LinearCost::DoEval(const Eigen::Ref<const Eigen::VectorXd>& x, Eigen::VectorXd& y) {
  DoEvalGeneric(x, y);
}

void LinearCost::DoEval(const Eigen::Ref<const AutoDiffVecXd>& x, AutoDiffVecXd& y) {
  DoEvalGeneric(x, y);
}

void LinearCost::DoEval(const Eigen::Ref<const VectorX<symbolic::Variable>>& x, VectorX<symbolic::Expression>& y) {
  DoEvalGeneric(x, y);
}
```
We do not have to do it in this PR. I think we can leave a TODO, and file a github issue here. I can send a PR later to implement this templated DoEval.

@mposa @kuindersma This PR might affect your code, as the nonlinear constraint you used in trajectory optimization do not have `DoEval` with symbolic variable type. You can overload `DoEval` and throw a logic error, as Soonho did in `direct_collocation.cc` in this PR.

:lgtm: +@ggould-tri for platform review please.

---

Reviewed 23 of 23 files at r1.
Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056#-:-LG0r-_M97wdWuXXeV2_:b-iy5fwl)*

**Comment by soonho-tri** [comment]
> @mposa @kuindersma This PR might affect your code, as the nonlinear constraint you used in trajectory optimization do not have DoEval with symbolic variable type. You can overload DoEval and throw a logic error, as Soonho did in direct_collocation.cc in this PR.

I wanted to make it less intrusive

**Comment by mposa** [comment]
I've found that there's a lot of copy-paste in writing constraints for Autodiff and double. 

Does this PR require all constraints to implement the symbolic version? If so, Is it possible to add a default method which throws that logic error if the symbolic version has not been implemented? 

I agree with @hongkai-dai that, when possible, the eval function should be templated. I did something like this with my own code here: https://github.com/DAIRLab/dairlib-public/blob/master/systems/trajectory_optimization/dircon_opt_constraints.cc

**Comment by soonho-tri** [comment]
> Does this PR require all constraints to implement the symbolic version? If so, Is it possible to add a default method which throws that logic error if the symbolic version has not been implemented?

As the first attempt, I implemented the symbolic version of `EvaluatorBase::DoEval` which throws an exception so that any subclasses of `Constraint`/`Cost` work as they are. However, I've found that it triggers `warning: 'EvaluatorBase::DoEval' hides overloaded virtual function [-Woverloaded-virtual]` which is considered as an error in Drake. One alternative solution is to rename `DoEval` to `DoSymbolicEval`, but I just patch up every subclass of `EvaluatorBase` in the codebase.

**Comment by soonho-tri** [comment]
@hongkai-dai , FYI, I created https://github.com/RobotLocomotion/drake/issues/9068

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: 4 unresolved discussions, platform LGTM from [ggould-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1J6nm-dHZ6QZHK_Ik:-LG1J6nm-dHZ6QZHK_Il:b-s24iso) (no related file):*
The reference-argument violations (http://drake.mit.edu/styleguide/cppguide.html#Reference_Arguments) here are getting a bit intense.  A better version of the `TODO(#2274)` text might be to clarify that the `MathematicalProgram` API (as opposed to the linter config) needs to be corrected.

---

*[solvers/constraint.h, line 761 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1GFv9-NsepZqZCwDD:-LG1GFv9-NsepZqZCwDE:b-yrig9s) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/constraint.h#L761)):*
> ```objc
>   /**
>    * @param x The stacked columns of the symmetric matrix. This function is not
>    * supported yet, since Eigen's eigen value solver does not accept
> ```

"yet" implies it will be in the future; that should cite an issue number.

---

*[solvers/constraint.h, line 820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1GMz25H9JFtWjXae-:-LG1GMz25H9JFtWjXae0:b-dlbdmj) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/constraint.h#L820)):*
> ```objc
> 
>   /**
>    * This function is not supported, since Eigen's eigen value solver does not
> ```

The previous one was "not supported yet".  Is this one not ever going to be supported?

---

*[solvers/evaluator_base.h, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1Hma12cYa5Qi2_gXs:-LG1Hma12cYa5Qi2_gXt:badsmux) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/evaluator_base.h#L141)):*
> ```objc
>    * Implements expression evaluation for scalar type symbolic::Expression.
>    * @param[in] x Input vector.
>    * @param[out] y Output vector.
> ```

The names "x" and "y" do not appear in the function declaration.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056#-:-LG1FJAzA5DYT-C3qHq5:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 3 unresolved discussions, platform LGTM from [ggould-tri]

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1J6nm-dHZ6QZHK_Ik:-LG1K6ui5YstIMVLRSgo:bxcg8rh) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The reference-argument violations (http://drake.mit.edu/styleguide/cppguide.html#Reference_Arguments) here are getting a bit intense.  A better version of the `TODO(#2274)` text might be to clarify that the `MathematicalProgram` API (as opposed to the linter config) needs to be corrected.
</blockquote></details>

New issue: https://github.com/RobotLocomotion/drake/issues/9069

---

*[solvers/constraint.h, line 761 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1GFv9-NsepZqZCwDD:-LG1Knth2eAOVfe5VL5q:b-t6gffy) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/constraint.h#L761)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

"yet" implies it will be in the future; that should cite an issue number.
</blockquote></details>

I took out "yet" from the sentence as I do not have a plan to support this.

---

*[solvers/constraint.h, line 820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1GMz25H9JFtWjXae-:-LG1NptsDjI5UxChdexA:b-2kpx4m) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/constraint.h#L820)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The previous one was "not supported yet".  Is this one not ever going to be supported?
</blockquote></details>

Not now. But I can revisit this if there is a feature-request.

---

*[solvers/evaluator_base.h, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9056#-LG1Hma12cYa5Qi2_gXs:-LG1KmOy3Ar4MQ5aePWY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d67955efe7b3e0afaa99c2f8ddb0a5518324e1d0/solvers/evaluator_base.h#L141)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

The names "x" and "y" do not appear in the function declaration.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9056)*

**Pull request merged**
