### PR TITLE
Fix sign-compare in systems (but not its children)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This another step for #2372.
- Fix sign-compare warnings in NAryFoo.
- Push the sign-compare warning suppressions down one level, from `systems` into its children.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2667)

### CODE REVIEW

**Comment by sherm1** [comment]
Both Windows builds seem to have succeeded but are "pending" (after 3 hours). I'm suspicious.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2667#-:-KLKHoG0_n2PgEYI-vDP:1417088721)*

**Comment by jwnimmer-tri** [comment]
> Both Windows builds seem to have succeeded but are "pending" (after 3 hours). I'm suspicious.

Actually, the dimmed blue bubble with hovertext "Success - pending" means that they have not yet even started to run on this PR.  (The UX is confusing and awful.)

**Comment by jwnimmer-tri** [comment]
It's passed now.  I assert that a single platform review from sherm1 is good enough for this PR, no need for a second reviewer for such a trivial change.

**Pull request merged**
