### PR TITLE
fix missing SONAME fields for libdrake.so and libdrake_marker.so

### PR DESCRIPTION
**Pull request by svenevs**
Partially addresses #15946
Relates: #15963

The original patch suggested by @jwnimmer-tri

https://github.com/RobotLocomotion/drake/blob/610ec7f88ab8f09507d2cd382c48cb15393d9467/tools/workspace/spdlog/package.BUILD.bazel#L66-L70

Relies on

https://github.com/RobotLocomotion/drake/blob/610ec7f88ab8f09507d2cd382c48cb15393d9467/tools/workspace/spdlog/package.BUILD.bazel#L14-L18

(`config_setting(name = "linux", ...)`) being declared.  Currently this patch utilizes a selection based off of `//tools/cc_toolchain:linux`, I'm not sure if a new `config` entry should be declared or if the current selection here is valid.  I have a small SONAME verification script, prior to this change:

```
Drake specific libraries missing SONAME:
  - /tmp/drake-master/lib/libdrake_ibex.so
  - /tmp/drake-master/lib/libdrake_marker.so
  - /tmp/drake-master/lib/libdrake.so
```

Afterward:

```
Drake specific libraries missing SONAME:
  - /tmp/drake-soname-fixed/lib/libdrake_ibex.so
```

Where `libdrake_ibex.so` is currently on hold until #15963 is complete.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16002)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16002)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[common/BUILD.bazel, line 320 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16002#-Mn8ShHeEAzmv1hEALR4:-MnCsrXt3_UNaqMOO_5c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d8aabd10209f135d0cc0467d9ada2442d862a0/common/BUILD.bazel#L320)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We don't need to add `-pthread` here (this library isn't threaded), we just want the soname part.
</blockquote></details>

Done.
___
*[common/BUILD.bazel, line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16002#-Mn8Ss6F3_JL2khJEBpp:-MnCsu2L33Gw4Bo_FNwW:b4gjrqx) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d8aabd10209f135d0cc0467d9ada2442d862a0/common/BUILD.bazel#L323)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is some bazel arcana, but the leading `@` stuff is only relevant for _externals (like spdlog), not for within Drake itself.  So, the string here should just be `"//conditions:default"` (see around line 378 in this file for an example) and we don't need any special comment line like this talking about the `@`.
</blockquote></details>

Done. Thanks for clarifying.
___
*[tools/install/libdrake/BUILD.bazel, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16002#-Mn8TH_QBPAO4oPbEHeF:-MnCt86x8H8FCbo8MUqU:b3mckxr) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d8aabd10209f135d0cc0467d9ada2442d862a0/tools/install/libdrake/BUILD.bazel#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We don't need to add `-pthread` here (it's probably inherited, from any object code that does need it).  We just want the soname part.
</blockquote></details>

Done. Confirmed `pthread` is inherited transitively from somewhere:

```console
$ ldd /tmp/drake-redux-postcheck/lib/libdrake.so | grep -i pthread
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb982673000)
```
___
*[tools/install/libdrake/BUILD.bazel, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16002#-Mn8TNIwCdslvYSl3fo1:-MnCtG0K01CEgj_5LzoW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0d8aabd10209f135d0cc0467d9ada2442d862a0/tools/install/libdrake/BUILD.bazel#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto on nixing the comment and extra `@` character.
</blockquote></details>

Done.

**Review by svenevs — COMMENTED** [review]
This PR will need to be squash merged and make sure to remove that verbiage from the first commit as well!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16002#-:-MnCtjAe41XKuy5zplha:b-jhpxdg)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: as feature reviewer.

+@SeanCurtis-TRI for platform review per schedule, please.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16002#-:-MnD1bRg8msC78Hg1OTv:bqxz4k4)* status: LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

@jwnimmer-tri could I prevail upon you to squash-merge this? I'm reluctant as I'm not confident on what exactly should go in the commit message.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16002#-:-MnRTgXo3HduT9QqImaD:btngygl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Pull request merged**
