### PR TITLE
Small updates to sympy routines.

### PR DESCRIPTION
**Pull request by drewhamiltonasdf**
A few small updates. Support for converting ndarrays of any size back and forth from Drake to Sympy. A few tweaks to get integers to display properly including an option to round floats that are integers to 16 decimal places into proper integer types for readability and simplification.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Good day, `@drewhamiltonasdf`. Thanks for your PR!
I’m assigning +@jwnimmer-tri as the most relevant team member to assist with this pull request. If you already had a different team member in mind, please let us know. To `@jwnimmer-tri`, feel free to delegate in case there is someone else more suitable.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-NhRyp_PDjcYDSZ64QW2:boao7jj)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @drewhamiltonasdf)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

@drewhamiltonasdf All pull requests need tests to prove that the new functionality works, and to prevent regressions as we continue changing the code.  The existing `sympy_test.py` should be amended to have more test cases.  The objective is to have test cases that fail when run against master, but pass with the fixed-up code in this pull request.  I should be able to temporarily undo any of the fixes here and observe that a test will fail to prove the fix is tested.

**Review by jwnimmer-tri — COMMENTED** [review]
There also seem to be some linter failures.  Be sure to run either `bazel test //bindings/pydrake/common/...` before the next push (and fix the failures).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-NhTS46KDOxXFGHMupvi:byalp2k)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @drewhamiltonasdf)

___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 36 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-NhTRqoTCBLeMXK8IbDB:-NhTRqoTCBLeMXK8IbDC:b-vntd61) ([raw file](https://github.com/RobotLocomotion/drake/blob/8a260cee6dcaa4f5c7fbe956f94d1057fd44002b/bindings/pydrake/symbolic/_symbolic_extra.py#L36)):*
> ```Python
>     *,
>     memo: typing.Dict = None,
>     round_ints: bool = False
> ```

What does `round_ints` do?  We're missing documentation in `Args:` about the new argument.

(Ditto for `from_sympy` as well.)

**Comment by drewhamiltonasdf** [comment]
@jwnimmer-tri got it. will get on this.

**Review by jwnimmer-tri — COMMENTED** [review]
Just waiting on the new test(s) now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-Ni-nKpGCFuJFqG6IROx:b-swtfza)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

___
*[`bindings/pydrake/symbolic/_symbolic_extra.py` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-Ni-n3Fl7VHnjtk0HcPo:-Ni-n3Fl7VHnjtk0HcPp:b-vmz9i3) ([raw file](https://github.com/RobotLocomotion/drake/blob/816be5a400117bcbf8a6ed56a5cbe24a9b0af816/bindings/pydrake/symbolic/_symbolic_extra.py#L33)):*
> ```Python
> 
> def to_sympy(
>     x: typing.Union[float, bool, Variable, Expression, Formula],
> ```

BTW Any fixes to the functions' type signatures in `_symbolic_sympy.py` also need to be copied here, due to the weird split from the conditional import on-demand.

**Comment by drewhamiltonasdf** [comment]
> Just waiting on the new test(s) now.
> 
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-Ni-nKpGCFuJFqG6IROx:b-swtfza)_ status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)
> 
> _[`bindings/pydrake/symbolic/_symbolic_extra.py` line 33 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-Ni-n3Fl7VHnjtk0HcPo:-Ni-n3Fl7VHnjtk0HcPp:b-vmz9i3) ([raw file](https://github.com/RobotLocomotion/drake/blob/816be5a400117bcbf8a6ed56a5cbe24a9b0af816/bindings/pydrake/symbolic/_symbolic_extra.py#L33)):_
> 
> > ```python
> > def to_sympy(
> >     x: typing.Union[float, bool, Variable, Expression, Formula],
> > ```
> 
> BTW Any fixes to the functions' type signatures in `_symbolic_sympy.py` also need to be copied here, due to the weird split from the conditional import on-demand.

Let's see if I can get this very un-ambitious pull request across the finish line. _symbolic_extra.py now updated to reflect changes. ;) 

(More later on in terms of documentation and sympy stuff.)

**Review by jwnimmer-tri — COMMENTED** [review]
The code seems to in far shape.  Now all we need in one (or more) new unit test cases that would fail when run against Drake master (or v1.22 etc) but would pass when run against the improvements here.  In other words, test(s) that prove the new code works.

It might be as simple as this?

```patch
--- a/bindings/pydrake/symbolic/test/sympy_test.py
+++ b/bindings/pydrake/symbolic/test/sympy_test.py
@@ -22,6 +22,7 @@ class TestSympy(unittest.TestCase):
         q, r = [Variable(name, BOOLEAN) for name in "q r".split()]
         inputs = [
             # Constants.
+            1,
             1.0,
             np.nan,
             Expression(1.0),
```

... but you would know better than I.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-NiCV_NEDWb8qL7pVnUa:b-86ls0x)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

**Review by jwnimmer-tri — COMMENTED** [review]
(fair* shape)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-NiCVy1D1wJehedVtu7e:b1gcuyt)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

**Comment by drewhamiltonasdf** [comment]
> (fair* shape)
> 
> > _[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20415#-:-NiCVy1D1wJehedVtu7e:b1gcuyt)_ status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @drewhamiltonasdf)

I appreciate your patience with this @jwnimmer-tri and I am well aware all of this would have taken you 2 minutes without my "help". Thanks for the coaching. Tested locally on the nightly build worked on my end.

**Comment by jwnimmer-tri** [comment]
:lgtm: thanks!

I think it's been great to start with a small pull request to get up to speed.

**Pull request merged**
