### PR TITLE
Use system nlopt

### LINKED ISSUE #7335: Use system nlopt
For now, we're building [nlopt](https://nlopt.readthedocs.io/en/latest) in bazel build. I'm wondering if we can switch to use the one in a system. FYI, both of macOS (via homebrew) and Xenial provide the latest version of nlopt, `2.4.2`.

 - macOS (homebrew): https://github.com/Homebrew/homebrew-core/commits/master/Formula/nlopt.rb
 - Ubuntu Xenial https://packages.ubuntu.com/source/xenial/nlopt

/cc @jwnimmer-tri , @stonier.

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #7335

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7386)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@BetsyMcPhail is fixing the images for this now.

**Comment by soonho-tri** [comment]
@jamiesnape , I guess I need to update the following line:

https://github.com/RobotLocomotion/drake/blob/f85ddb96185493aecd71547fd157f77f0630f3ba/cmake/packages.cmake#L18

Do you think `find_package(NLopt MODULE REQUIRED)` is going to work?

**Comment by jamiesnape** [comment]
> Do you think find_package(NLopt MODULE REQUIRED) is going to work?

No, you would need to provide `FindNLopt.cmake`, but #7293 should merge shortly, so you should be able skip the CMake build.

**Comment by soonho-tri** [comment]
@jamiesnape , great!

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by soonho-tri** [comment]
Dropped the changes in `CMakeLists.txt` file.

**Comment by soonho-tri** [comment]
+@jamiesnape for feature-review, please.
+@jwnimmer-tri for platform-review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-:-KxxZsWpcBNH_MMtqjMj:btqyp8w)*

**Comment by jwnimmer-tri** [comment]
@soonho-tri Did you test Shambhala (or some other proxy for the installed Drake) yet?  I would have expected `drake.cps` edits to be required.

**Comment by jamiesnape** [comment]
`Link-Flags: ["-lnlopt", "-ltinyxml2"]` here: https://github.com/RobotLocomotion/drake/blob/master/tools/install/libdrake/drake.cps#L106

**Comment by soonho-tri** [comment]
@jamiesnape , added. Thank you.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-:-Kxxev4iQHiuOdMq5Kc4:bjxt92f)*

**Comment by jwnimmer-tri** [comment]
*[tools/install/libdrake/drake.cps, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-KxxfCD-2b7bt9iulk7Q:-KxxfCD-2b7bt9iulk7R:b-vpfhxi) ([raw file](https://github.com/robotlocomotion/drake/blob/8604a66221a7ac150c6cb7df63063f7c498b21af/tools/install/libdrake/drake.cps#L53)):*
> ```delphi
>       "Hints": ["@prefix@/lib/cmake/nlopt"],
>       "X-CMake-Find-Args": ["CONFIG"]
>     },
> ```

FYI I would have this stanza to cause a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386)*

**Comment by jamiesnape** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/drake.cps, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-KxxfyM3ohJEMXi-KCal:-KxxfyM4X5uWv9cA_YmF:b-xw6zb6) ([raw file](https://github.com/robotlocomotion/drake/blob/8604a66221a7ac150c6cb7df63063f7c498b21af/tools/install/libdrake/drake.cps#L109)):*
> ```delphi
>       "Link-Requires": [
>         "fmt:fmt",
>         "NLopt:nlopt",
> ```

FYI And this one too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386)*

**Comment by soonho-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/drake.cps, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-KxxfCD-2b7bt9iulk7Q:-KxxgQtRrwOLgXpIovdj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8604a66221a7ac150c6cb7df63063f7c498b21af/tools/install/libdrake/drake.cps#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I would have this stanza to cause a problem.
</blockquote></details>

Done.

---

*[tools/install/libdrake/drake.cps, line 109 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-KxxfyM3ohJEMXi-KCal:-KxxgRFSpskywR9EIN6f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8604a66221a7ac150c6cb7df63063f7c498b21af/tools/install/libdrake/drake.cps#L109)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI And this one too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-:-KxxggZ8GQj69Bo3kGRs:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7386#-:-KxxhHbPtJVbhYGnF6-w:bnfp4nl)*

**Pull request merged**
