### PR TITLE
Configure label image publishing in CameraConfig

### LINKED ISSUE #20483: CameraConfig can opt-in to label images
**Is your feature request related to a problem? Please describe.**

Currently, a camera in `CameraConfig` can be configured to create color and/or depth images. But never label images. This makes it awkward and difficult to prototype and test simulations that want to provide label images.

**Describe the solution you'd like**

We should add a field label that has the same semantics as depth: default value is false, and setting it true creates label images.

**Additional context**

Split out of #19901.

### PR DESCRIPTION
**Pull request by zachfang**
Close #20483

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
Add the `label` flag, and modify the associated files and tests to ensure it's propagated properly. I also tested locally with `lcm_image_array_viewer` with `RgbdSensor` and `RgbdSensorAsync`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-:-NjQ0ysf6WqVOivhkOaM:b-v7foah)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

___
*[`systems/sensors/camera_config.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjQ-WWx5gLvyeDbIKu2:-NjQ-WWx5gLvyeDbIKu3:byb9xsx) ([raw file](https://github.com/RobotLocomotion/drake/blob/46e7aa407ed1a3a2d1ca9fd3d49d35b1df4445e6/systems/sensors/camera_config.h#L64)):*
> ```objc
>     a->Visit(DRAKE_NVP(depth));
>     a->Visit(DRAKE_NVP(label));
>     a->Visit(DRAKE_NVP(show_rgb));
> ```

Working. Given the fact that `rgb` and `label` images both come from `ColorRenderCamera`, there will be two windows showing both if `rgb=label=true`. Technically, the name `show_rgb` (which is `show_window` underlying) is probably not appropriate now. My thought is to change the name of this flag to `show_color_camera` or `show_window`. As this is a public interface, we might need the deprecation procedure.



_Code quote:_
```objc
show_rgb
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`systems/sensors/camera_config.h` line 64 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjQ-WWx5gLvyeDbIKu2:-Njsryq04naTYkyKMStl:b-42i0f0) ([raw file](https://github.com/RobotLocomotion/drake/blob/46e7aa407ed1a3a2d1ca9fd3d49d35b1df4445e6/systems/sensors/camera_config.h#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My opinion is that the "show" feature is intended for transient local debugging, so having it pop up _two_ windows is not a big deal.  (It might even be what the user wanted, in some cases.)

I agree the field name is less-than-ideal now, but oh well.  I don't think it's worth changing the name.  Instead, we should update the docs for `show_rgb` to explain its new behavior.

Existing users will not be affected, because `label` defaults to false.  Only users who newly opt-in to label images as well as optin-in to `show_rgb` will be impacted.

Going through a rename would impact _all_ users for very little gain.
</blockquote></details>

Done. Updated the document instead.
___
*[`systems/sensors/sim_rgbd_sensor.h` line 148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjreMRmCBfB4wMkOdaX:-Njss6ax7caFzVrShq9r:b-x6jyri) ([raw file](https://github.com/RobotLocomotion/drake/blob/46e7aa407ed1a3a2d1ca9fd3d49d35b1df4445e6/systems/sensors/sim_rgbd_sensor.h#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For this change, you need to prepare an Anzu PR with the tentative Drake bump (i.e., pointing to this PR) alongside an adjustment (an extra `nullptr`), and have that pre-approved before landing this Drake PR.
</blockquote></details>

Working.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: Pending Anzu coordination.

> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-:-NkHqvwVAT7Xw4gFG2NO:b-ri34bx)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @zachfang)

___
*[`systems/sensors/camera_config.h` line 412 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NkHpcDr2E1O-fXZ3rsX:-NkHpcDr2E1O-fXZ3rsY:b-iau5gm) ([raw file](https://github.com/RobotLocomotion/drake/blob/729dbfbdfc6af6ed3023468b207d288a06e9c0a7/systems/sensors/camera_config.h#L412)):*
> ```objc
>   /** Controls whether the rendered RGB and/or label images are displayed (in
>    separate windows controlled by the thread in which the camera images are
>    rendered). As both image types are rendered from `ColorRenderCamera`, it
> ```

BTW Given how we `show_rgb` works, leaving this on for label images is probably  a bad idea. It's a relic from a bygone error that should be deprecated.

We have two options:

1. Add some functionality so that label images look interesting when we display them, or
2. Don't allow them to be displayed by this flag; it should only apply to color.

I broach this here because the documentation brought it into my attention but this is not a task for *this* PR. If you guys agree, I'll open an issue.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @zachfang)

___
*[`systems/sensors/camera_config.h` line 412 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NkHpcDr2E1O-fXZ3rsX:-NkHs93KAkuWT8xA53B5:b-z2tzg3) ([raw file](https://github.com/RobotLocomotion/drake/blob/729dbfbdfc6af6ed3023468b207d288a06e9c0a7/systems/sensors/camera_config.h#L412)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given how we `show_rgb` works, leaving this on for label images is probably  a bad idea. It's a relic from a bygone error that should be deprecated.

We have two options:

1. Add some functionality so that label images look interesting when we display them, or
2. Don't allow them to be displayed by this flag; it should only apply to color.

I broach this here because the documentation brought it into my attention but this is not a task for *this* PR. If you guys agree, I'll open an issue.
</blockquote></details>

Previously discussed here: https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjQ-WWx5gLvyeDbIKu2

My opinion is that very few people use this feature, so we should not invest time in making it nicer.  It is primarily useful for RenderEngine developers (i.e., only you). I would rather invest our time in "show any/all camera outputs in your web browser" which would yield benefits for a lot more people than option (1) and (2) above.  Once we have that feature working well, we could plausibly deprecate this option for removal, or at least mark it as advanced and steer people away from it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @zachfang)

___
*[`systems/sensors/sim_rgbd_sensor.h` line 148 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjreMRmCBfB4wMkOdaX:-NkHy__s9EevYm5DhIWF:bmnk9nr) ([raw file](https://github.com/RobotLocomotion/drake/blob/46e7aa407ed1a3a2d1ca9fd3d49d35b1df4445e6/systems/sensors/sim_rgbd_sensor.h#L148)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

Working.
</blockquote></details>

The Anzu PR is ready.

**Review by jwnimmer-tri — COMMENTED** [review]
Oops, forgot my :lgtm: badge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-:-NkIJJFdECLc8oRnJxsN:b5gf3os)* status: 1 unresolved discussion, missing label for release notes (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554)* status: missing label for release notes

___
*[`systems/sensors/camera_config.h` line 412 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NkHpcDr2E1O-fXZ3rsX:-NkIIyuKAWfLN4xF9z74:be8clzf) ([raw file](https://github.com/RobotLocomotion/drake/blob/729dbfbdfc6af6ed3023468b207d288a06e9c0a7/systems/sensors/camera_config.h#L412)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Previously discussed here: https://reviewable.io/reviews/RobotLocomotion/drake/20554#-NjQ-WWx5gLvyeDbIKu2

My opinion is that very few people use this feature, so we should not invest time in making it nicer.  It is primarily useful for RenderEngine developers (i.e., only you). I would rather invest our time in "show any/all camera outputs in your web browser" which would yield benefits for a lot more people than option (1) and (2) above.  Once we have that feature working well, we could plausibly deprecate this option for removal, or at least mark it as advanced and steer people away from it.
</blockquote></details>

Marked as resolved for now since this PR is finalized with whichever option we decide (do nothing or do something in another PR).

**Review by zachfang — COMMENTED** [review]
I added `release notes: feature` to satisfy the merge preconditions. Let me know if it should be something else.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20554#-:-NkIK1NzEz61Sx-bbCc1:b9e1997)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
> I added release notes: feature to satisfy the merge preconditions.

SGTM

**Pull request merged**
