### PR TITLE
Constraint solver discretization tests fix.

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses issue #9086

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9088)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@m-chaturvedi for feature review please

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9088#-:-LGRA-jZ-HlWUZpna_8u:b-osju4)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform.

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9088#-:-LGRBh5t6x_xTrDPnLVJ:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all discussions resolved, platform LGTM from [jwnimmer-tri], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9088)*

**Pull request merged**
