### PR TITLE
Add more tests on symbolic::Polynomial on ndeterminates/decision_variables

### PR DESCRIPTION
**Pull request by hongkai-dai**
In a dev branch, accidentally someone makes a change to `symbolic::Polynomial` in https://github.com/AlexandreAmice/drake/commit/f436034dbffbd4404baeec9d63bf8cc2da34df8d. The change is incorrect, but our symbolic_polynomial_test.cc doesn't catch the error. In this PR I add these additional tests to make sure such change on `symbolic::Polynomial` should be caught.

A dev branch accidentally changes symbolic::Polynomial incorrectly, but our unit test fails to capture that.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332#-:-MsmQqEx-GgLu8pAa3gx:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[common/test/symbolic_polynomial_test.cc, line 224 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt3a_6y4ZUEn-as_ISi:-Mt3a_6y4ZUEn-as_ISj:b-uy24v0) ([raw file](https://github.com/robotlocomotion/drake/blob/bf9dd9c112dfe9917c489d00fa3677db66ea8904/common/test/symbolic_polynomial_test.cc#L224)):*
> ```cpp
> }
> 
> // Check that union_expected equals to the union of vars1 and vars2.
> ```

The type `Variables` supports `operator+`.  Do we need a helper function here?

To me, writing out `EXPECT_EQ(vars1 + vars2, union_expected)` at the call sites would be much clearer?  No order-of-arguments ambiguity, and the error message line number will be localized, instead of always pointing to this helper (only).
___
*[common/test/symbolic_polynomial_test.cc, line 246 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt3bZKk-lwJ8jdUfFZ6:-Mt3bZKk-lwJ8jdUfFZ7:bn39ygu) ([raw file](https://github.com/robotlocomotion/drake/blob/bf9dd9c112dfe9917c489d00fa3677db66ea8904/common/test/symbolic_polynomial_test.cc#L246)):*
> ```cpp
>       EXPECT_PRED2(ExprEqual, sum2.ToExpression(),
>                    (m.ToExpression() + e).Expand());
>       CheckEqualToUnion(p.indeterminates(), m.GetVariables(),
> ```

I think all but one of these new test predicates are in the opposite sense of the surrounding code.

In the prior line we have `sum2.ToExpression` as the first operand, and the `Expand` as the second operand.  The `sum2` part is the output of the device under test, and the `Expand` part is the expected value.  So the pattern is `EXPECT(output_value, expected_value)`.

In this line, however, I believe that `sum1.indeterminates` is the output value, and `p.indeterminates + m.variables` is the expected value.  They are in the wrong order.

Ditto throughout almost all of these changes.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/test/symbolic_polynomial_test.cc, line 224 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt3a_6y4ZUEn-as_ISi:-Mt48Y_Z4HxzWuhj19ZR:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/bf9dd9c112dfe9917c489d00fa3677db66ea8904/common/test/symbolic_polynomial_test.cc#L224)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The type `Variables` supports `operator+`.  Do we need a helper function here?

To me, writing out `EXPECT_EQ(vars1 + vars2, union_expected)` at the call sites would be much clearer?  No order-of-arguments ambiguity, and the error message line number will be localized, instead of always pointing to this helper (only).
</blockquote></details>

Done. Good call.
___
*[common/test/symbolic_polynomial_test.cc, line 246 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt3bZKk-lwJ8jdUfFZ6:-Mt49YrdAFuJuWcGdDjb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/bf9dd9c112dfe9917c489d00fa3677db66ea8904/common/test/symbolic_polynomial_test.cc#L246)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think all but one of these new test predicates are in the opposite sense of the surrounding code.

In the prior line we have `sum2.ToExpression` as the first operand, and the `Expand` as the second operand.  The `sum2` part is the output of the device under test, and the `Expand` part is the expected value.  So the pattern is `EXPECT(output_value, expected_value)`.

In this line, however, I believe that `sum1.indeterminates` is the output value, and `p.indeterminates + m.variables` is the expected value.  They are in the wrong order.

Ditto throughout almost all of these changes.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[common/test/symbolic_polynomial_test.cc, line 240 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt4JPep-SQbbrdWzd4X:-Mt4JPeq6fBReNYbNfGS:b4ip7fn) ([raw file](https://github.com/robotlocomotion/drake/blob/279885b4f3c13659260b5af603a30513e72bfafe/common/test/symbolic_polynomial_test.cc#L240)):*
> ```cpp
>       EXPECT_EQ(sum2.indeterminates(), p.indeterminates() + m.GetVariables());
>       EXPECT_EQ(p.decision_variables(), sum1.decision_variables());
>       EXPECT_EQ(p.decision_variables(), sum2.decision_variables());
> ```

To keep output/expected sorted consistently, don't want to swap the EXPECT_EQ arguments here?  Thus, to have `sum` as the first arg and `p` as the second arg?
___
*[common/test/symbolic_polynomial_test.cc, line 451 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt4K6X-9Z46MaCU07WB:-Mt4K6X-9Z46MaCU07WC:bmyk19h) ([raw file](https://github.com/robotlocomotion/drake/blob/279885b4f3c13659260b5af603a30513e72bfafe/common/test/symbolic_polynomial_test.cc#L451)):*
> ```cpp
>                 p.indeterminates() + m.GetVariables());
>       EXPECT_EQ(p.decision_variables(), product1.decision_variables());
>       EXPECT_EQ(p.decision_variables(), product2.decision_variables());
> ```

Ditto on these final two lines -- I think they are both still backwards?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[common/test/symbolic_polynomial_test.cc, line 240 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt4JPep-SQbbrdWzd4X:-Mt5KLU89dJ3ttBEObNx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/279885b4f3c13659260b5af603a30513e72bfafe/common/test/symbolic_polynomial_test.cc#L240)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To keep output/expected sorted consistently, don't want to swap the EXPECT_EQ arguments here?  Thus, to have `sum` as the first arg and `p` as the second arg?
</blockquote></details>

Done.
___
*[common/test/symbolic_polynomial_test.cc, line 451 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16332#-Mt4K6X-9Z46MaCU07WB:-Mt5KSav58BIIaILh8NG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/279885b4f3c13659260b5af603a30513e72bfafe/common/test/symbolic_polynomial_test.cc#L451)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto on these final two lines -- I think they are both still backwards?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule, please.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332#-:-Mt5NEuZ1WYveiB6_vOo:b-gb4g9z)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16332#-:-Mt92Gxy3PwYjtESSu1A:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
