### PR TITLE
[geometry] Establishes Meshcat in C++ (step 1)

### PR DESCRIPTION
**Pull request by RussTedrake**
This is the first of a series of PRs that will provide Meshcat as a visualizer in C++.  The design and PR strategy is documented on in #13038.

This is the first PR:
Meshcat proof of life. Starts the server, demonstrates that clients can connect, and just sends one type of message to show that data can flow. Reviewers can focus on the build system and websocket server details.

The dependencies added here are all quite lightweight, and properly licensed.  And at the end of the PR train, we will likely want to deprecate meshcat-python, and eventually remove the pip dependencies that come along with it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhJ3Quu9_2neZKWHNNT:-MhJ3Quu9_2neZKWHNNU:bqftcv) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/setup/mac/binary_distribution/Brewfile#L24)):*
> ```Ruby
> brew 'nlopt'
> brew 'numpy'
> brew 'msgpack'
> ```

@betsymcphail I will need to bump the build servers (ubuntu, too) to get msgpack.  We can wait until the reviewers ok my usage of this external; but wanted to give you a heads up that it is coming.

**Review by RussTedrake — COMMENTED** [review]
+@iantheengineer for feature review, please.

BTW -- CI won't pass until the msgpack dependency is updated on the build servers.  I *have* tested on mac locally (in addition to ubuntu bionic).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhJOMh83gc0Ybe44m9A:bpwxgb3)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

per https://drake.mit.edu/jenkins.html#updating-installation-prerequisites

**Review by IanTheEngineer — COMMENTED** [review]
For reference, the direct links inside the #13038 thread -
Design Decisions: https://github.com/RobotLocomotion/drake/issues/13038#issuecomment-898774201
PR Strategy: https://github.com/RobotLocomotion/drake/issues/13038#issuecomment-898876077

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhKExEY0JSBE7GIu8J6:b-hvf9k4)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @IanTheEngineer)

**Review by IanTheEngineer — COMMENTED** [review]
First review pass done, and successfully tested locally. This looks great, Russ. I like the design you've put forth here. The new dependencies themselves do seem rather light, well licensed, and well maintained. I just have a few minor discussion points below.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhLcdAe13xyHGOntvha:b-siyohk)* status: 5 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/dev/meshcat.cc, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhL-yhL8o249R22agWk:-MhL-yhM1SQB1vWbehkV:b-uvcq5j) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L4)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> #include <future>
> #include <string>
> #include <thread>
> #include <unordered_map>
> #include <utility>
> #include <App.h>
> ```
</details>

Nit: You already included the above dependencies in the `meshcat.h` file. I don't mind if you prefer leaving them here, but I believe they can be removed.
___
*[geometry/dev/meshcat.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLauli0RK6wYI3G56r:-MhLaulj7vW052DEP1Bl:b2q1a2r) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L45)):*
> ```
> void Meshcat::join_websocket_thread() { websocket_thread_.join(); }
> ```
FYI, It took me a minute to realize that this function is "snake_case" because the function is basically an [accessor function](https://drake.mit.edu/styleguide/cppguide.html#Function_Names) providing access to the underlying thread `join()` functionality. Am I following this logic correctly?
___
*[geometry/dev/meshcat.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLNbQT2M39kEYagCWy:-MhLNbQT2M39kEYagCWz:bci2ft8) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L113)):*
> ```
> LIBUS_LISTEN_EXCLUSIVE_PORT
> ```
How do we determine this port is exclusively owned by the WebSocket app? I am wondering if anything needs to be done to explicitly claim ownership over the port, as [LIBUS_LISTEN_DEFAULT is the non-exclusive default listening option](https://github.com/uNetworking/uSockets/blob/5440dbac79bd76444175b76ee95dfcade12a6aac/src/libusockets.h#L48-L51).
___
*[geometry/dev/meshcat.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLcA5k0UZMDHZVHvGE:-MhLcA5k0UZMDHZVHvGF:bkd8sj6) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L122)):*
> ```
> port++ <= kMaxPort
> ```
FYI, if I am reading it correctly, this means we can only have 50 instances of Meshcat XD.
___
*[geometry/dev/meshcat_demo.cc, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLWCj854fYXnTNCgmp:-MhLWCj9B4keVzzOg2F_:b-n069y9) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L7)):*
> ```
> bazel run //geometry:meshcat_demo
> ```
This should be ` bazel run //geometry/dev:meshcat_demo`.
___
*[geometry/dev/meshcat_demo.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLY4C689D0XYlKV0VX:-MhLY4C689D0XYlKV0VY:b37ezki) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L25)):*
> ```
>   // Note: the grid doesn't actually disappear (bug in meshcat), but the
>   // checkbox is unchecked.
> ```
FYI: I could reproduce this bug. It gave me pause until I found your note here :) Perhaps give a nod to this bug above in your test description as well.
___
*[geometry/dev/meshcat_demo.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhL_HVj0_-22UeElL2A:-MhL_HVj0_-22UeElL2B:bdc7z5p) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L30)):*
> ```
> meshcat.join_websocket_thread();
> ```
Nit: Even though it's not strictly necessary as the OS will clean it up, this example would be "more correct" if you also invoked `meshcat2.join_websocket_thread();` to wait for the second meshcat instance thread to rejoin you the main thread.
___
*[setup/ubuntu/source_distribution/packages-bionic.txt, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLXS_D10ldfYolmbWM:-MhLXS_E44NP7n6G3KAD:byewftl) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/setup/ubuntu/source_distribution/packages-bionic.txt#L24)):*
> ```help
> liblz4-dev
> liblzma-dev
> libmsgpack-dev
> ```

FYI, (though perhaps this is quite obvious) `apt install`'ing `libmsgpack-dev` or running the setup script with this branch checked out is required to test this PR.

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review per schedule.

:lgtm: on the non-dev bits; skipping the `dev` bits since they don't need platform review.

> Reviewed 17 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhLjpWf0dr5NutVhbcD:b-bb4v8n)* status: 11 unresolved discussions, LGTM missing from assignee IanTheEngineer (waiting on @RussTedrake)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLnQLxEwCQhNUyXfSH:-MhLnQLxEwCQhNUyXfSI:b70it0q) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/-- commits#L4)):*
nit Typo `on in`
___
*[doc/BUILD.bazel, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLn99j3VvIY_vadeqR:-MhLn99j3VvIY_vadeqS:bkcb77w) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/doc/BUILD.bazel#L57)):*
> ```Starlark
>         "site.webmanifest",
>     ],
>     visibility = ["//visibility:public"],
> ```

FYI I oscillated back and forth about whether this should be "public" or `@drake//:__subpackages__`, but ended up with this being okay as-is.  I guess it doesn't much hurt to allow downstream software to re-use our icons in their build system?
___
*[geometry/dev/BUILD.bazel, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLniq325FxjwBqcWsN:-MhLniq325FxjwBqcWsO:b1smv0a) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/BUILD.bazel#L10)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> package(default_visibility = ["//visibility:public"])
> ```

nit Code in `dev` folders should have scoped visibility, not public.  That would be `"//visibility:private"` nominally, but making it visible to a list of _other_ dev folders within Drake would be fine as well.
___
*[geometry/dev/BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLmQyxEKpL_WZxS6tc:-MhLmQyxEKpL_WZxS6td:b9ahwmi) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/BUILD.bazel#L21)):*
> ```Starlark
>         "@meshcat//:dist/main.min.js",
>     ],
>     linkopts = ["-pthread"],
> ```

nit Since our `meshcat.h` and `meshcat.cc` files don't use pthread, this seems like a lost dependency of our of our externals, so should be added there, not here.

Indeed, looking at the `Makefile` for `uWebSockets`, it looks like it needs `-pthread`, so this line should move into the `@uwebsockets//:uwebsockets` target instead of here.
___
*[geometry/dev/meshcat.h, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLo9Ea4woPe9LNj8Po:-MhLo9Ea4woPe9LNj8Pp:b-xhruwt) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.h#L9)):*
> ```objc
> #include <utility>
> 
> #include <App.h>
> ```

FYI For the future --

Per https://github.com/RobotLocomotion/drake/issues/7451, we do not want to add new library dependencies to our installed headers.  Therefore, if `#include <App.h>` stays here, then `meshcat.h` cannot be installed, and Drake headers that include `meshcat.h` also cannot be installed.  Only `*.cc` files could use this code.

If we need to provide public header access to `class Meshcat`, then the uWS stuff will need to move into a pimpl.
___
*[tools/workspace/default.bzl, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLjTum5eu2BjB1HnBq:-MhLjTunEUzKerIhlYjP:btmtjka) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/default.bzl#L53)):*
> ```Starlark
> load("@drake//tools/workspace/meshcat:repository.bzl", "meshcat_repository")
> load("@drake//tools/workspace/meshcat_python:repository.bzl", "meshcat_python_repository")  # noqa
> load("@drake//tools/workspace/msgpack:repository.bzl", "msgpack_repository")
> ```

nit Keep the list of externals alpha-sorted (move this after "mosek").
___
*[tools/workspace/default.bzl, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLjOK626eVlylrF0An:-MhLjOK626eVlylrF0Ao:btmtjka) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/default.bzl#L201)):*
> ```Starlark
>         meshcat_python_repository(name = "meshcat_python", mirrors = mirrors)
>     if "msgpack" not in excludes:
>         msgpack_repository(name = "msgpack")
> ```

nit Keep the list of externals alpha-sorted (move this after "mosek").
___
*[tools/workspace/usockets/package.BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLlACv1lUSQikVBauH:-MhLlACv1lUSQikVBauI:bn4w3a1) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/usockets/package.BUILD.bazel#L21)):*
> ```
>         "src/*.h",
>         "src/internal/*.h",
>         "src/internal/**/*.h",
> ```

nit It's not necessarily a problem either way, but instead of the prior three lines of headers, I think we could say ...

```
"src/**/*.h"
```

... on its own, instead, since there does not appear to be anything that we need to exclude or avoid.

Note that the `*.c` stuff is correct as-written, because it matches the upstream `Makefile`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)* status: 11 unresolved discussions, LGTM missing from assignee IanTheEngineer (waiting on @RussTedrake)

___
*[geometry/dev/meshcat.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLauli0RK6wYI3G56r:-MhOOAIC1NQf73WSqlkM:b-o58jck) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L45)):*
btw: Per styleguide: https://drake.mit.edu/styleguide/cppguide.html#Function_Names

>  Such methods should have a time complexity of O(1) and be less than 5 lines long.

Surely a thread join method is *not* O(1)?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)* status: 3 unresolved discussions, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLnQLxEwCQhNUyXfSH:-MhQK3naBTnv40DJmB9J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/-- commits#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Typo `on in`
</blockquote></details>

Done.
___
*[doc/BUILD.bazel, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLn99j3VvIY_vadeqR:-MhQK7hxEnBmBSQqy5Zp:bs03g4m) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/doc/BUILD.bazel#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I oscillated back and forth about whether this should be "public" or `@drake//:__subpackages__`, but ended up with this being okay as-is.  I guess it doesn't much hurt to allow downstream software to re-use our icons in their build system?
</blockquote></details>

I went through the same thought process.  I'm happy with either.
___
*[tools/workspace/default.bzl, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLjTum5eu2BjB1HnBq:-MhQluti7cX0IbQffYpT:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/default.bzl#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Keep the list of externals alpha-sorted (move this after "mosek").
</blockquote></details>

Done. 
___
*[tools/workspace/default.bzl, line 201 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLjOK626eVlylrF0An:-MhQly-dBFUdppbDfQSK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/default.bzl#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Keep the list of externals alpha-sorted (move this after "mosek").
</blockquote></details>

Done.
___
*[tools/workspace/usockets/package.BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLlACv1lUSQikVBauH:-MhQmHFx2gFB4xrXPGFi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/tools/workspace/usockets/package.BUILD.bazel#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It's not necessarily a problem either way, but instead of the prior three lines of headers, I think we could say ...

```
"src/**/*.h"
```

... on its own, instead, since there does not appear to be anything that we need to exclude or avoid.

Note that the `*.c` stuff is correct as-written, because it matches the upstream `Makefile`.
</blockquote></details>

Done.
___
*[geometry/dev/BUILD.bazel, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLniq325FxjwBqcWsN:-MhQKLq03wy-yo3SvWu8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/BUILD.bazel#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Code in `dev` folders should have scoped visibility, not public.  That would be `"//visibility:private"` nominally, but making it visible to a list of _other_ dev folders within Drake would be fine as well.
</blockquote></details>

Done.
___
*[geometry/dev/BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLmQyxEKpL_WZxS6tc:-MhQKiJ7DwZ652GK5QAH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/BUILD.bazel#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Since our `meshcat.h` and `meshcat.cc` files don't use pthread, this seems like a lost dependency of our of our externals, so should be added there, not here.

Indeed, looking at the `Makefile` for `uWebSockets`, it looks like it needs `-pthread`, so this line should move into the `@uwebsockets//:uwebsockets` target instead of here.
</blockquote></details>

Done.
___
*[geometry/dev/meshcat.h, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLo9Ea4woPe9LNj8Po:-MhQdIZP3EiLVQHRH1ym:b-9vj7lt) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.h#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI For the future --

Per https://github.com/RobotLocomotion/drake/issues/7451, we do not want to add new library dependencies to our installed headers.  Therefore, if `#include <App.h>` stays here, then `meshcat.h` cannot be installed, and Drake headers that include `meshcat.h` also cannot be installed.  Only `*.cc` files could use this code.

If we need to provide public header access to `class Meshcat`, then the uWS stuff will need to move into a pimpl.
</blockquote></details>

Done.  Implemented the PIMPL.  Good call.
___
*[geometry/dev/meshcat.cc, line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhL-yhL8o249R22agWk:-MhQdYQE68-5wEtl3XFU:bx8njr3) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L4)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> #include <future>
> #include <string>
> #include <thread>
> #include <unordered_map>
> #include <utility>
> #include <App.h>
> ```
Nit: You already included the above dependencies in the `meshcat.h` file. I don't mind if you prefer leaving them here, but I believe they can be removed.
</blockquote></details>

Done.  The PIMPL allowed me to remove them from the header.
___
*[geometry/dev/meshcat.cc, line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLauli0RK6wYI3G56r:-MhQdmJl3_9-Jqnwjya1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L45)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

btw: Per styleguide: https://drake.mit.edu/styleguide/cppguide.html#Function_Names

>  Such methods should have a time complexity of O(1) and be less than 5 lines long.

Surely a thread join method is *not* O(1)?
</blockquote></details>

Done.
___
*[geometry/dev/meshcat.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLNbQT2M39kEYagCWy:-MhQdvN79wI6ctpwFzWN:b-l11jgd) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L113)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> LIBUS_LISTEN_EXCLUSIVE_PORT
> ```
How do we determine this port is exclusively owned by the WebSocket app? I am wondering if anything needs to be done to explicitly claim ownership over the port, as [LIBUS_LISTEN_DEFAULT is the non-exclusive default listening option](https://github.com/uNetworking/uSockets/blob/5440dbac79bd76444175b76ee95dfcade12a6aac/src/libusockets.h#L48-L51).
</blockquote></details>

Passing this allows me to ensure that multiple instances of Meshcat will not listen on the same port.  I don't know how to protect from some other application silently listening on that port, and would think that protection is out of scope?
___
*[geometry/dev/meshcat.cc, line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLcA5k0UZMDHZVHvGE:-MhQeQ-s3Bcd4MbvVrZZ:berfqoq) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L122)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> port++ <= kMaxPort
> ```
FYI, if I am reading it correctly, this means we can only have 50 instances of Meshcat XD.
</blockquote></details>

Yes.   I've made it 7099, since that's the number of ports that the docker instances open up for meshcat (but it's all pretty arbitrary, i guess...  I've rarely needed more than 2!).   I've added a comment in the constructor, which I think is the right place since we may offer passing a port number as a constructor option in the future.
___
*[geometry/dev/meshcat_demo.cc, line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLWCj854fYXnTNCgmp:-MhQfBYV4rdZkXkJFGnm:bln5tju) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L7)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> bazel run //geometry:meshcat_demo
> ```
This should be ` bazel run //geometry/dev:meshcat_demo`.
</blockquote></details>

Done.  Good catch.  But hopefully we'll move it back soon!
___
*[geometry/dev/meshcat_demo.cc, line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLY4C689D0XYlKV0VX:-MhQkHN3E5Y3X7sOuChy:b-dzt0ba) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L25)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
>   // Note: the grid doesn't actually disappear (bug in meshcat), but the
>   // checkbox is unchecked.
> ```
FYI: I could reproduce this bug. It gave me pause until I found your note here :) Perhaps give a nod to this bug above in your test description as well.
</blockquote></details>

Done.  Turns out the bug was mine.  I've fixed it.  
___
*[geometry/dev/meshcat_demo.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhL_HVj0_-22UeElL2A:-MhQkMHp2-Cn8jHKMFZI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat_demo.cc#L30)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

> ```
> meshcat.join_websocket_thread();
> ```
Nit: Even though it's not strictly necessary as the OS will clean it up, this example would be "more correct" if you also invoked `meshcat2.join_websocket_thread();` to wait for the second meshcat instance thread to rejoin you the main thread.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)* status: 3 unresolved discussions, LGTM missing from assignee IanTheEngineer (waiting on @IanTheEngineer)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please

+@BetsyMcPhail for review, and to update the CI instances.

**Review by BetsyMcPhail — COMMENTED** [review]
Linux images have been updated (as always, keep in mind it may take awhile for Jenkins to use new images)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhTcX980XY1p08_vycV:bbtpsha)* status: 3 unresolved discussions, LGTM missing from assignees BetsyMcPhail,IanTheEngineer (waiting on @BetsyMcPhail and @IanTheEngineer)

**Review by BetsyMcPhail — COMMENTED** [review]
Mac images are also updated.

:lgtm: for CI update portions

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhTgDGB6kZOMY8LAjqL:b-yt9vg)* status: 3 unresolved discussions, LGTM missing from assignee IanTheEngineer (waiting on @BetsyMcPhail and @IanTheEngineer)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

It looks like CI is passing so far, which means that @IanTheEngineer the only thing blocking this PR now is your `:lgtm:`.

**Review by IanTheEngineer — COMMENTED** [review]
:LGTM: Here are my thoughts from last night's review pass. I didn't get a chance to do a second pass this morning as I intended. From my notes last night:

I quite like the PIMPL implementation to hide the external dependencies. I think overall things look good now to proceed. Thanks for the changes Russ!

> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618#-:-MhUmOq61b5NG4_t4Jk2:bqa5rmc)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),BetsyMcPhail,IanTheEngineer (waiting on @BetsyMcPhail and @IanTheEngineer)

___
*[geometry/dev/meshcat.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhLNbQT2M39kEYagCWy:-MhQwUm59elNWE6nl-b6:bq2xtgp) ([raw file](https://github.com/robotlocomotion/drake/blob/07e80e97602947088cab4adfea31a4adb4e5ecd8/geometry/dev/meshcat.cc#L113)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Passing this allows me to ensure that multiple instances of Meshcat will not listen on the same port.  I don't know how to protect from some other application silently listening on that port, and would think that protection is out of scope?
</blockquote></details>

Ah, I read this the other way : that you were meant to guarantee this socket was available. It makes more sense that you're signalling to the app to only grab this port if it's currently free.
___
*[geometry/dev/meshcat.cc, line 75 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15618#-MhR0QEQ9kGkntyTOIuG:-MhR0QER-gzNzYtWlp8h:bkewm8u) ([raw file](https://github.com/robotlocomotion/drake/blob/37fd41753bbf0ae771f10751a2bc9ba5a8da34cf/geometry/dev/meshcat.cc#L75)):*
> ```
>     // Note: Must pass path and property by value because they will go out of
>     // scope.
> ```
BTW: Good find here. I would hazard a guess this was the bug preventing meshcat's grid from being disabled in the test.

**Review by IanTheEngineer — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15618)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),BetsyMcPhail,IanTheEngineer (waiting on @BetsyMcPhail)

**Pull request merged**
