### PR TITLE
Serializes IrisOptions

### PR DESCRIPTION
**Pull request by rcory**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Thanks!  I think we want some minimal test coverage for this (so that the code at least gets run).  Here's a minimal (related) example?

```
GTEST_TEST(HPolyhedronTest, Serialize) {
  const HPolyhedron H = HPolyhedron::MakeL1Ball(3);
  const std::string yaml = yaml::SaveYamlString(H);
  const auto H2 = yaml::LoadYamlString<HPolyhedron>(yaml);
  EXPECT_EQ(H.ambient_dimension(), H2.ambient_dimension());
  EXPECT_TRUE(CompareMatrices(H.A(), H2.A()));
  EXPECT_TRUE(CompareMatrices(H.b(), H2.b()));
}
```

**Review by rcory — COMMENTED** [review]
Yup, I forgot! PTAL.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-:-NXCo7NQ5P4ip0T3HRd6:b-sb4ejh)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rcory and @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rcory)

___
*[`geometry/optimization/test/iris_test.cc` line 259 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-NXDGgS52C2aMV_iCwp8:-NXDGgS52C2aMV_iCwp9:bqu10g1) ([raw file](https://github.com/RobotLocomotion/drake/blob/6560af2858bcc52816b397ce014a5b9392262ea7/geometry/optimization/test/iris_test.cc#L259)):*
> ```cpp
> 
> GTEST_TEST(IrisOptionsTest, Serialize) {
>   const IrisOptions options = IrisOptions();
> ```

Sorry to nit, but it would be much more compelling, and only a few more lines if they were non-default values.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rcory and @RussTedrake)

___
*[`geometry/optimization/test/iris_test.cc` line 259 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-NXDGgS52C2aMV_iCwp8:-NXG_PlbAp2v5NxnqZzl:bis0m37) ([raw file](https://github.com/RobotLocomotion/drake/blob/6560af2858bcc52816b397ce014a5b9392262ea7/geometry/optimization/test/iris_test.cc#L259)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Sorry to nit, but it would be much more compelling, and only a few more lines if they were non-default values.
</blockquote></details>

Agree. Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:
+@rpoyner-tri for platform review, please.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-:-NXGyOIo-DWtIlp05VNe:b-5mhjlt)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rcory and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-:-NXHSpEV4v5E30IXHuFD:bnfp4nl)* status: missing label for release notes (waiting on @rcory)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19512#-:-NXHSy8-5hrI1x7xJjwU:b-l8xbmn)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform)

**Pull request merged**
