### PR TITLE
Updated parsing of hydroelastic properties

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
PR #12464 merged with asan errors. This PR contains the original approved PR (as the first commit) and the fixes for the problem in the second commit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12491)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Comment by SeanCurtis-TRI** [comment]
> @drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Comment by jwnimmer-tri** [comment]
The TODO mentions #12455, but that PR is already merged.

**Comment by SeanCurtis-TRI** [comment]
> @drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Comment by SeanCurtis-TRI** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-address-sanitizer please

**Pull request merged**
