### PR TITLE
Mesh vs. Halfspace intersection

### PR DESCRIPTION
**Pull request by edrumwri**
Utility class for constructing the intersection between a triangle from a mesh and a halfspace.

This is one of two PRs for constructing a ContactSurface from the intersection between a rigid triangle mesh and a compliant halfspace.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11986)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
for my own education, if `CalcZeroLevelSetInMeshDomain()` allows to intersect any tet meshes with a half-space, what is the new functionality in this PR for?

**Comment by SeanCurtis-TRI** [comment]
@amcastro-tri Your half space is rigid and the mesh is compliant. This reverses this -- the mesh is rigid and the half space is compliant (well, this PR is *one* piece of that.)

**Comment by amcastro-tri** [comment]
ah! thanks @SeanCurtis-TRI. So this is for rigid tri-meshes vs. half space? no tets?

**Comment by SeanCurtis-TRI** [comment]
Exactly.

**Pull request merged**
