### PR TITLE
[common] Speed up SoS using negation instead of subtraction

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
In the SoS benchmark, for me this is approx 20% faster on case 1 and 2% faster on case 2.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@hongkai-dai for feature review

:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013#-:-N0Cm-LNDdRjKcQQ-Hj_:b7srbw3)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013#-:-N0Cm4C-BtF1t4Ag1u8V:bi4se7j)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[common/symbolic_generic_polynomial.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17013#-N0CnCu94Y8M0aN8OmSg:-N0CnCu94Y8M0aN8OmSh:b-xph422) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a2b7d6316dbc4f2d50779053d07bab424f40c4/common/symbolic_generic_polynomial.cc#L48)):*
> ```cpp
>     // basis_element ∈ dom(map)
>     Expression& existing_coeff = it->second;
>     if (AreOppositesAfterExpanding(coeff, existing_coeff)) {
> ```

I could change it to be the below, instead.  Would that be better @hongkai-dai?



_Suggestion:_
```cpp
AreEqualAfterExpanding(-coeff, existing_coeff)
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[common/symbolic_generic_polynomial.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17013#-N0CnCu94Y8M0aN8OmSg:-N0CnX1LAOqllxuIcqP7:b-qa8pdv) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a2b7d6316dbc4f2d50779053d07bab424f40c4/common/symbolic_generic_polynomial.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I could change it to be the below, instead.  Would that be better @hongkai-dai?
</blockquote></details>

Yeah probably AreEqualAfterExpanding is better, in the future we might want to re-use this function to compare two expressions being equal.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013#-:-N0Cq8NY9q6pbkph4Ci-:bcpz082)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

___
*[common/symbolic_generic_polynomial.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17013#-N0CnCu94Y8M0aN8OmSg:-N0CqAH514lv6HlLAzk_:b-4o322q) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a2b7d6316dbc4f2d50779053d07bab424f40c4/common/symbolic_generic_polynomial.cc#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yeah probably AreEqualAfterExpanding is better, in the future we might want to re-use this function to compare two expressions being equal.
</blockquote></details>

+1 as reviewer

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

___
*[common/symbolic_generic_polynomial.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17013#-N0CnCu94Y8M0aN8OmSg:-N0CvgGR7RmpvMTjNggc:b-nru59m) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a2b7d6316dbc4f2d50779053d07bab424f40c4/common/symbolic_generic_polynomial.cc#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

+1 as reviewer
</blockquote></details>

Working on it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)* status: missing label for release notes (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[common/symbolic_generic_polynomial.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17013#-N0CnCu94Y8M0aN8OmSg:-N0D3JlJAyqXtjiqvi8x:be022kf) ([raw file](https://github.com/robotlocomotion/drake/blob/f7a2b7d6316dbc4f2d50779053d07bab424f40c4/common/symbolic_generic_polynomial.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working on it.
</blockquote></details>

Done.

For the record, I confirmed that the negation does not cause us to call `Expand`; it remains `is_expanded() == true` in the SOS case.

I should also note that I've chosen to negate the `coeff` here (not the `existing_coeff`) because I expect that `coeff` will typically be the more simpler expression tree of the two, so we should expect it to be the fastest one to negate.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Do we typically include performance improvements in release notes?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17013#-:-N0DMfBwALjiAN9iXB-j:b-ss9zz8)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Generally, yes.  Sometimes they end up grouped under a single umbrella, but in any case most speed-ups are notable, especially if they are measurable.

**Pull request merged**
