### PR TITLE
cleanup example directory names

### PR DESCRIPTION
**Pull request by RussTedrake**
renames examples to c++ naming convention, now that matlab has been removed.
fyi @TristanThrush (hope this doesn't break your pr2 / val work).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6642)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for platform review

---

Review status: 0 of 814 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-:-Kpp_nuqdxpZuVJW_4tl:b-ykw85)*

**Comment by jwnimmer-tri** [comment]
You must have read my mind.  This morning I was thinking we need to do this rename prior to declaring a first release ready to go, and was going to file an issue for it.

:lgtm: platform.

---

Reviewed 1567 of 1567 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KppbH3xCr9M52pIruJR:b-c5xnez) (no related file):*
Do we need a feature review for zapping examples/ZMP?

---

*[drake/examples/acrobot/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbsG6QyFPEj35nZOg:-KppbsG6QyFPEj35nZOh:b67qgog) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/acrobot/BUILD#L74)):*
> ```Python
>         "//drake/systems/analysis:simulator",
>     ],
> )
> ```

Its a big strange to have a test program that isn't run automatically, and isn't `testonly = 1`.  Should this turn into a real test, or at least get a TODO to do so?

---

*[drake/examples/atlas/atlasUtil.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppdzhLA8fcpPs-Rzf0:-KppdzhLA8fcpPs-Rzf1:bgz1wqj) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/atlas/atlasUtil.h#L3)):*
> ```objc
> #pragma once
> 
> namespace Atlas {
> ```

FYI Can you file a follow-up issue or otherwise make a note that C++ namespace(s) have to be repaired now, also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-:-KppmrZbxJ9RW_Pj9FxO:b-4moy7r)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-Kpq0dnYk4Tp1wc-p6oT:bwpkwli) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do we need a feature review for zapping examples/ZMP?
</blockquote></details>

ah, you're right.  it looks like @siyuanfeng-tri might be using it.  siyuan -- can you let me know?  (simple enough for me to instead rename "ZMP => zmp")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbsG6QyFPEj35nZOg:-Kpq0ycyNvpTLSO8hdLf:b9vv58j) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/acrobot/BUILD#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its a big strange to have a test program that isn't run automatically, and isn't `testonly = 1`.  Should this turn into a real test, or at least get a TODO to do so?
</blockquote></details>

it's really more of a development tool than a test.  i thought about stuffing it in a dev directory.  it doesn't put any meaningful coverage on the acrobot unless multiple executables are run (with lcm traffic flowing between them).  

not sure what's best.

---

*[drake/examples/atlas/atlasUtil.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppdzhLA8fcpPs-Rzf0:-Kpq6S7saGj3BnHa-AT9:b-iecq47) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/atlas/atlasUtil.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Can you file a follow-up issue or otherwise make a note that C++ namespace(s) have to be repaired now, also.
</blockquote></details>

Done.  turns out atlas was the only offender.  i've fixed it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 1567 files at r1, 2 of 3 files at r2.
Review status: 813 of 814 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbsG6QyFPEj35nZOg:-Kpq7YTYc2YNm_HhH10h:b-n3ku4l) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/acrobot/BUILD#L74)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's really more of a development tool than a test.  i thought about stuffing it in a dev directory.  it doesn't put any meaningful coverage on the acrobot unless multiple executables are run (with lcm traffic flowing between them).  

not sure what's best.
</blockquote></details>

I'd recommend a short comment to that effect as the resolution here.  (Probably also mark it `testonly = 1` if that builds okay.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by RussTedrake** [comment]
Review status: 813 of 814 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/acrobot/BUILD, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbsG6QyFPEj35nZOg:-Kpq9b-hOUn6Q24MgKNG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e74082bfd765e6ec129ac8c57ca0012b710272ae/drake/examples/acrobot/BUILD#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'd recommend a short comment to that effect as the resolution here.  (Probably also mark it `testonly = 1` if that builds okay.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by RussTedrake** [comment]
Review status: 813 of 814 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqA7G7ZSSi6uaYOy6a:b-kmosya) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

ah, you're right.  it looks like @siyuanfeng-tri might be using it.  siyuan -- can you let me know?  (simple enough for me to instead rename "ZMP => zmp")
</blockquote></details>

+@siyuanfeng-tri for feature

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by siyuanfeng-tri** [comment]
Review status: 813 of 814 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqB45TrXhESH02vYgj:bn1umbb) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

+@siyuanfeng-tri for feature
</blockquote></details>

Ah, I do have test cases in examples/ZMP. Dont zap it! please, rename to zmp is better. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1567 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by RussTedrake** [comment]
Review status: 814 of 823 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqGK_Jhv4jU4YptlZa:b-xb1lrs) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

Ah, I do have test cases in examples/ZMP. Dont zap it! please, rename to zmp is better. 
</blockquote></details>

Done.  can you complete the feature review for me?  thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by siyuanfeng-tri** [comment]
i am working on it.. haven't figured out a way to click through them faster..

**Comment by siyuanfeng-tri** [comment]
Reviewed 1342 of 1567 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: 814 of 823 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqSde6LVtJne0LVXwG:b33zmf9) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  can you complete the feature review for me?  thanks!
</blockquote></details>

check point. 

---

*[drake/examples/ZMP/BUILD, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KpqCoQIbj5M8lqG1dms:-KpqCoQIbj5M8lqG1dmt:b21toa1) ([raw file](https://github.com/robotlocomotion/drake/blob/7163c1a5cad472889dc02b3e5e2a067dccccdeac/drake/examples/ZMP/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

BTW don't zap this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 222 of 1567 files at r1, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqUjT8X7fnYJebuXew:bg7igkv) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

check point. 
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/ZMP/BUILD, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KpqCoQIbj5M8lqG1dms:-KpqXb91NM3mNR6EWxUA:bsbklj2) ([raw file](https://github.com/robotlocomotion/drake/blob/7163c1a5cad472889dc02b3e5e2a067dccccdeac/drake/examples/ZMP/BUILD#L1)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW don't zap this.
</blockquote></details>

i think reviewable is just confused?  the file is fine... checkout the individual commit here:
https://github.com/RobotLocomotion/drake/pull/6642/commits/7c0955e2e784d7109af49179aa3021af0e355da0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6642#-KppbH3wJpMTFv9AS0_K:-KpqZNdlsLvJrBIcoZCq:b-izxtnw) (no related file):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

@russtedrake, my QP stuff was merged earlier, which probably breaks your merge. Apologies. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Build errors are real:
```
drake/examples/QPInverseDynamicsForHumanoids/plan_eval/BUILD:90:1:
  no such package 'drake/examples/Valkyrie':
  BUILD file not found on package path and referenced by
  '//drake/examples/QPInverseDynamicsForHumanoids/plan_eval:humanoid_manipulation_demo'.
```

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 5 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6642)*

**Pull request merged**
