### PR TITLE
bug fix in robot state translator and remove duplicate translator code in examples. 

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
purged robot_state_t encode decode code in humanoids and kuka_iiwa_arm. 
fixed a bug for X_WB and V_WB computation when the rigid body tree's "base" link has a non zero rigid frame.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6073)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-KjpA9cd8PJx3cix1q-h:b-6l9dh6)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjqSqbwjJRuyKlnsBwc:-KjqSqbwjJRuyKlnsBwd:bi0abng) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L17)):*
> ```objc
> 
> /**
>  * A class that takes state vector and output a bot_core::robot_state_t message.
> ```

BTW: How about calling this a "drake::System" instead of just class? 

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjqTCoZgzwBPnxtaSRQ:-KjqTCo_5P4LFsuS8k8h:b-4knscy) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L59)):*
> ```objc
>             ->template GetMutableValue<bot_core::robot_state_t>();
> 
>     msg.utime = static_cast<int64_t>(context.get_time() * 1e6);
> ```

Does context.get_time() return any meaningful information at construction time? If not, why not just set to 0 or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-Kjs5clcRnqnknA4xphv:bnfp4nl)*

**Comment by naveenoid** [comment]
I only have minor comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-Kjs5iTASBUjTW88bBUs:bp1lssv)*

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri for platform review. thanks ! 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjqTCoZgzwBPnxtaSRQ:-KjsATm45Wl_u-OqwFSb:brsudw3) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L59)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Does context.get_time() return any meaningful information at construction time? If not, why not just set to 0 or something?
</blockquote></details>

this is in DoCalcOutput, what do you mean construction time? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-KjsAlCLBNKezMWuqMBO:b-7n8w9w)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 59 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjqTCoZgzwBPnxtaSRQ:-Kjsz53RNbq5AttaCZRS:bfrppxb) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L59)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

this is in DoCalcOutput, what do you mean construction time? 
</blockquote></details>

yikes! Your right sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073)*

**Comment by soonho-tri** [comment]
:lgtm: I only have minor suggestions.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-Kjwvj2DX-ghBtHxrWGV:-Kjwvj2DX-ghBtHxrWGW:bqkjunj) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L18)):*
> ```objc
> /**
>  * A class that takes state vector and output a bot_core::robot_state_t message.
>  * For the encoded `message`, `message.pose will` always be X_WB (pose of `B`
> ```

nit: `message.pose will` -> `message.pose` will

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_status_translator_system.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjwwrVUpwDFvijgSpCW:-KjwwrVV3oQ-IXpaRGTV:b-nijwzg) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_status_translator_system.cc#L76)):*
> ```cpp
>   translator_.DecodeMessageKinematics(*msg, pos, vel);
>   translator_.DecodeMessageTorque(*msg, joint_torque);
>   time = static_cast<double>(msg->utime) / 1e6;
> ```

BTW, nit:

```c++
const double time = static_cast<double>(msg->utime) / 1e6;
```

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 340 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-Kjwy9WVfpWwrEuxrD7r:-Kjwy9WVfpWwrEuxrD7s:b-t2iax7) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/manipulation/util/robot_state_msg_translator.cc#L340)):*
> ```cpp
>         root_body.get_velocity_start_index() != 0) {
>       throw std::logic_error(
>           "This class assumes that floating joint positions and are at the "
> ```

positions ~and~ are at

---

*[drake/manipulation/util/test/robot_state_msg_translator_test.cc, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-Kjx36hlF31B2wmE2W40:-Kjx36hlF31B2wmE2W41:ba9vvr1) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/manipulation/util/test/robot_state_msg_translator_test.cc#L94)):*
> ```cpp
>       const RigidBody<double>& base = robot.get_body(1);
>       KinematicsCache<double> cache = robot.doKinematics(q, v);
>       Isometry3<double> X_WB, X_WB_expected;
> ```

let's have
```c++
      const Isometry3<double> X_WB = DecodePose(message_.pose);
      const Isometry3<double> X_WB_expected =
          robot.CalcBodyPoseInWorldFrame(cache, base);
      const Vector6<double> V_WB = DecodeTwist(message_.twist);
      const Vector6<double> V_WB_expected =
          robot.CalcBodySpatialVelocityInWorldFrame(cache, base);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-Kjx2n_o8bUiXqNrp7ew:b-xm2h64)*

**Comment by siyuanfeng-tri** [comment]
thanks guys. 

---

Review status: 8 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjqSqbwjJRuyKlnsBwc:-Kjx8p5SRZV0tyQra318:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L17)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: How about calling this a "drake::System" instead of just class? 
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/oracular_state_estimator.h, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-Kjwvj2DX-ghBtHxrWGV:-Kjx8dFV-SDq7r3MAb-V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/kuka_iiwa_arm/oracular_state_estimator.h#L18)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit: `message.pose will` -> `message.pose` will
</blockquote></details>

Done.

---

*[drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_status_translator_system.cc, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-KjwwrVUpwDFvijgSpCW:-Kjx9-cY_CUyo63F02oR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/examples/QPInverseDynamicsForHumanoids/system/humanoid_status_translator_system.cc#L76)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, nit:

```c++
const double time = static_cast<double>(msg->utime) / 1e6;
```
</blockquote></details>

Done.

---

*[drake/manipulation/util/robot_state_msg_translator.cc, line 340 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-Kjwy9WVfpWwrEuxrD7r:-Kjx9EVc2MxOkc62X8Fr:b-mfo3fp) ([raw file](https://github.com/robotlocomotion/drake/blob/395c34694e1c2d679a311b8a22a1214509ca751a/drake/manipulation/util/robot_state_msg_translator.cc#L340)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

positions ~and~ are at
</blockquote></details>

opps. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073#-:-Kjx9vcNmd9IfvhqTmT_:bapdw24)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6073)*

**Pull request merged**
