### PR TITLE
Tidy up how leaf systems with state are written

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3205)

### CODE REVIEW

**Comment by david-german-tri** [comment]
I see.  Yeah, that's reasonable.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/leaf_system.h, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmqpxH3-Fj7QiijU-N:-KPmqpxIu6w-o41Iidtd:bpx2boh) ([raw file](https://github.com/robotlocomotion/drake/blob/7cf33227abf7c37fb30affe00e66212f355d65b1/drake/systems/framework/leaf_system.h#L61)):*
> ```objc
>     std::unique_ptr<ContinuousState<T>> continuous_state =
>         this->AllocateTimeDerivatives();
>     if (continuous_state) {
> ```

I don't think this check adds anything.  If it doesn't, the whole implementation can be collapsed to one line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmrEaZyAunqgugGt3Q:b-xzzvlr)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/leaf_system.h, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmspGKrYzImVHEsZv0:-KPmspGLRYu6-N84mCnc:bwi57hz) ([raw file](https://github.com/robotlocomotion/drake/blob/a79a2a8825bd66558dacf469b76b9d54784a0564/drake/systems/framework/leaf_system.h#L58)):*
> ```objc
>   /// By default, delegates to AllocateTimeDerivatives. Child classes that need
>   /// any other variety of state should override.
>   virtual void ReserveState(Context<T>* context) const {
> ```

@david-german-tri Would this be better to rename to ReserveContinuousState and make it non-virtual (and leave a stub virtual ReserveNonContinuousState)?  This code will be correct for many cases, and might be too easy to disable if folks have to override and then call-super?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/leaf_system.h, line 61 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmqpxH3-Fj7QiijU-N:-KPmsngE2GYazaYTHmBW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7cf33227abf7c37fb30affe00e66212f355d65b1/drake/systems/framework/leaf_system.h#L61)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I don't think this check adds anything.  If it doesn't, the whole implementation can be collapsed to one line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by david-german-tri** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmspGKrYzImVHEsZv0:-KPmtJs9pEfGbOTmO0up:bb73djm) ([raw file](https://github.com/robotlocomotion/drake/blob/a79a2a8825bd66558dacf469b76b9d54784a0564/drake/systems/framework/leaf_system.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @david-german-tri Would this be better to rename to ReserveContinuousState and make it non-virtual (and leave a stub virtual ReserveNonContinuousState)?  This code will be correct for many cases, and might be too easy to disable if folks have to override and then call-super?
</details>
SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by amcastro-tri** [comment]
I would prefer having a `LeafSystem<T>::ReserveContinuousState(nq, nv, nz)` (maybe you could implement in this PR?) and then, since state seems to me to be a more fundamental concept to be exposed, I would delegate the allocation of state derivatives to `ReserveContinousState` (not the opposite). 

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/primitives/test/integrator_test.cc, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmrvuEBgWr3grHljEH:-KPmrvuEBgWr3grHljEI:b-uukcon) ([raw file](https://github.com/robotlocomotion/drake/blob/7cf33227abf7c37fb30affe00e66212f355d65b1/drake/systems/framework/primitives/test/integrator_test.cc#L47)):*
> ```cpp
>   }
> 
>   std::unique_ptr<System<double>> integrator_;
> ```

Nice to see we can do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmsmbOEFCwYY9r4LXW:bf3wfu0)*

**Comment by david-german-tri** [comment]
Oh, actually, I agree with @amcastro-tri.  Good point!

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmtaX0W4LfcY9pMKN6:bkcc59a)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/primitives/test/integrator_test.cc, line 47 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmrvuEBgWr3grHljEH:-KPmtX0jdvvLZWBnF-ka:b-3o6t9m) ([raw file](https://github.com/robotlocomotion/drake/blob/7cf33227abf7c37fb30affe00e66212f355d65b1/drake/systems/framework/primitives/test/integrator_test.cc#L47)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Nice to see we can do this.
</details>
Yup, and its actually _required_ to do this now that the methods are all private on Integrator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by jwnimmer-tri** [comment]
> I would prefer having a LeafSystem<T>::ReserveContinuousState(nq, nv, nz) and then, since state seems to me to be a more fundamental concept to be exposed, I would delegate the allocation of state derivatives to ReserveContinousState (not the opposite). 

I do not understand.  `Reserve...` modifies a context; `Allocate...` returns fresh storage.  How to you implement an Allocate in terms of a Reserve?  @amcastro-tri @david-german-tri coul you want to provide pseudocode for what you mean?

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmv85mQwmapT63sML6:b5hda5n)*

**Comment by david-german-tri** [comment]
```
// Possibly also provide an (nq, nv, nz) variant of this, with nq, nv, nz configured analogous to I/O ports.
virtual std::unique_ptr<ContinuousState<T>> LeafSystem::AllocateContinuousState() {  // virtual
  return make_unique<...>();
}

std::unique_ptr<AllocateTimeDerivatives<T>> LeafSystem::AllocateTimeDerivatives() override {  // not virtual
 return AllocateContinuousState();  // or possibly (nq, nv, nz)
}

void ReserveState(Context<T>* context) {  // not virtual
  ReserveDiscreteState();  // virtual
  context.xc = AllocateContinuousState();  // or possibly (nq, nv, nz)
}

```

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmvdrgp00akmhMp5eo:b-bis9y4)*

**Comment by amcastro-tri** [comment]
Right, one returns the other one modifies the context. @david-german-tri got it right. I would however make the "possibly"'s a fact and pass `nq, nv, nz`. Then `ReserveState` would also need get passed the size of continuous state.

@david-german-tri, I just realize that we cannot ask the system the question `System<T>::get_q()`? (with q defined for instance in the constructor.

Then the above default method in System<T> could be written as:
```c++
void ReserveState(Context<T>* context) {  // not virtual
  ReserveDiscreteState();  // virtual
  context.xc = AllocateContinuousState(get_vq(), get_nv(), get_nz());  // or possibly (nq, nv, nz)
}
```

The constructor for the integrator then would look like:
```c++
Integrator<T>::Integrator(int length)
    : System<T>(0, 0, length), length_(length) {
  this->DeclareInputPort(kVectorValued, length, kContinuousSampling);
  this->DeclareOutputPort(kVectorValued, length, kContinuousSampling);
}
```

would something like this make sense? If we do so the user wont need to write any of the Reserve or Allocate methods!

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPmyMPDkB99dUTDflwv:bjobcc2)*

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/leaf_system.h, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPmspGKrYzImVHEsZv0:-KPnE1MOUXMev0AD-VEw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a79a2a8825bd66558dacf469b76b9d54784a0564/drake/systems/framework/leaf_system.h#L58)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> SGTM
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnEGBhAJGxbdE92-Ha:b5xll3r)*

**Comment by amcastro-tri** [comment]
Excellent! I like it. Just a few comments.

---

Reviewed 3 of 6 files at r1, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/leaf_system.h, line 62 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPndICQJsDZQUF7jVAY:-KPndICRgP-soaAI-3vC:bajgnyp) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/leaf_system.h#L62)):*
> ```objc
>     // Reserve continuous state via delegation to subclass.
>     context->get_mutable_state()->continuous_state =
>         std::move(this->AllocateTimeDerivatives());
> ```

wouldn't it read nicer here if we had the call to `AllocateContinuousState`? since then it'll read like `continuous_state = AllocateContinuousState()`

---

*[drake/systems/framework/state.h, line 33 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnaxYc5IkAtnB_gIEw:-KPnaxYc5IkAtnB_gIEx:b-rjr05n) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/state.h#L33)):*
> ```objc
>     generalized_velocity_.reset(new StateSubvector<T>(state_.get()));
>     misc_continuous_state_.reset(
>         new StateSubvector<T>(state_.get(), 0, state_->size()));
> ```

nice fix!. I guess this template never got compiled.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnbjyEIQjyBHhjfReW:b2kuiwj) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
> ```cpp
>   int length = System<T>::get_output_port(0).get_size();
>   DRAKE_ASSERT(System<T>::get_input_port(0).get_size() == length);
>   return std::make_unique<ContinuousState<T>>(
> ```

I see how this is appealing. However I liked the previous version because it shows how the state is only used for its miscellaneous component and there is no second order structure.
If you opt for this version I would like a comment here stating this for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnenc-R26el-prjGx6:b26ukji)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPngkSJswCbmQwp6ihS:bkkbubr) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I see how this is appealing. However I liked the previous version because it shows how the state is only used for its miscellaneous component and there is no second order structure.
> If you opt for this version I would like a comment here stating this for clarity.
</details>
Under that line of thinking, the 1-argument constructor is intrinsically defective.  @david-german-tri perhaps I should replace that constructor with a named factory method that clarifies @amcastro-tri's concern here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by amcastro-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnnnEvXyxE_Mzoqqw-:bcq59au) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Under that line of thinking, the 1-argument constructor is intrinsically defective.  @david-german-tri perhaps I should replace that constructor with a named factory method that clarifies @amcastro-tri's concern here?
</details>
For the purpose of this PR I am ok with either the previous option or a verbose enough comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/framework/leaf_system.h, line 62 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPndICQJsDZQUF7jVAY:-KPnnBbueNpWdBfK3yBc:boj7ro4) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/leaf_system.h#L62)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> wouldn't it read nicer here if we had the call to `AllocateContinuousState`? since then it'll read like `continuous_state = AllocateContinuousState()`
</details>
Good catch!  I meant to do that, but somehow missed it.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by jwnimmer-tri** [comment]
@david-german-tri need your eyes on a few threads below.  Also would you like to self-assign platform review, or I can kick it to the rotation if you prefer.

---

Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnojHJNAE11xogTx_M:b-v7ovre)*

**Comment by david-german-tri** [comment]
+@david-german-tri for platform review

---

Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnq3227P9Yha4Gs_r1:b-rhk18b)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnquEVfHbJaThv6aDd:bk7f8al) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> For the purpose of this PR I am ok with either the previous option or a verbose enough comment.
</details>
I think this is clear as-is, but if you want to document it to satisfy @amcastro-tri, I would prefer a named factory method to a comment (since this situation will be somewhat common).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnrQ3d7aThDhUApH7r:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnuxPpLi0zM9Ib_4Df:b-wijsgj) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I think this is clear as-is, but if you want to document it to satisfy @amcastro-tri, I would prefer a named factory method to a comment (since this situation will be somewhat common).
</details>
@amcastro-tri What do you think?  Is expecting folks to read the `ContinuousState` API sufficient, or do I need to change the API?  Would a general reader expect there to be second-order state, and thus it's very important to be clear that it's only first-order?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnvWwtME7VcucOcQzq:b-w9fxxl) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> @amcastro-tri What do you think?  Is expecting folks to read the `ContinuousState` API sufficient, or do I need to change the API?  Would a general reader expect there to be second-order state, and thus it's very important to be clear that it's only first-order?
</details>
I think most users will be familiar with the concept of `xdot = flow(t, x, u)` for systems that are either first or second order. Most likely the concept of miscellaneous states will be new to users since it is specific to Drake. That is way I suggested to make it explicit. 
A just realized also that this already came up! see #3143 and the proposed API in [this comment](https://reviewable.io/reviews/robotlocomotion/drake/3102#-KOvJLeGJGUuRJANReRx). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnwKoTK-eKM9W1jZ_f:b-9cb1ur) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I think most users will be familiar with the concept of `xdot = flow(t, x, u)` for systems that are either first or second order. Most likely the concept of miscellaneous states will be new to users since it is specific to Drake. That is way I suggested to make it explicit. 
> A just realized also that this already came up! see #3143 and the proposed API in [this comment](https://reviewable.io/reviews/robotlocomotion/drake/3102#-KOvJLeGJGUuRJANReRx). 
</details>
I'd be real happy if you close one of my issues :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205)*

**Comment by amcastro-tri** [comment]
This looks :lgtm: to me as is. Though I'd be thrilled if @jwnimmer-tri decides to close #3143 with a solution in this PR for me :-)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPnwUoSvuEw-AZoTdKS:bj3mc5c)*

**Comment by jwnimmer-tri** [comment]
I just added the `IsValidOutput` cleanup here as well.  PTAL.

---

Review status: 11 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/primitives/integrator.cc, line 38 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-KPnbjyDnJsm77jGG216:-KPnwpSJ-Alq7pmU0fYg:bddm1n3) ([raw file](https://github.com/robotlocomotion/drake/blob/3946c23d018cd5ac45ae6372370a17459118e970/drake/systems/framework/primitives/integrator.cc#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> I'd be real happy if you close one of my issues :-)
</details>
Done.

I looked at the API, and I really think the `ContinuousState` constructor is great as it stands now, so I don't want to change it to a factory method.  Instead, I clarified the comment here to hopefully help.

I'm not going to take #3143, because I personally _never_ want numerical-only state -- I am always going to want vector subclasses with _names_ for getters and setters instead of "the first index means spring something something" documentation that is never at hand when you want it -- so that default implementation will never be useful for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPo-4qK5EUvsYBBiQpQ:b-ifzzd9)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3205#-:-KPo4U1hMFuv27uQG74k:bnfp4nl)*

**Pull request merged**
