### PR TITLE
[sensors] Deprecate the old `foo_sensor.h` to become `foo.h`

### LINKED ISSUE #14123: [sensors] Accelerometer and gyroscope need header deprecation
PRs #13501 and #13604 introduced an acclerometer and gyroscope, respectively. These sensor types had existed in the previous `RigidBodyPlant` regime. As such, to avoid file name collisions in includes, their header files had to be named `accelerometer_sensor.h` and `gyroscope_sensor.h` (even though the classes are simply called `Accelerometer` and `Gyroscope`.

With the conclusion of #13889, the collision no longer exists and the headers can be changed to reflect the contained class and conform to the styleguide. So, we'll create the new header file and deprecate the old (referencing the new).

Squeezing this in before Oct 1 will keep the deprecation time frame as short as possible.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
While attic was alive, we had `attic/systems/sensors/foo.h`. To create versions that were compatible with MBP, we created `attic/systems/sensors/foo_sensor.h` to distinguish them via build systems (although they included classes of the same name).

Now that attic is gone, we can remove the `_sensor` suffix.

This has two curated commits. The first renames the header files and changes all Drake references to be consistent; this preserves the blame/history on the files. The second commit adds back the `foo_sensor.h` files. The restored files emit a deprecation warning and include the renamed header.

resolves #14123

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14185)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(status: commits are properly curated) 
+(status: single reviewer ok) 
+@jwnimmer-tri for review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14185#-:-MJ8P3B-9iMyp4tuIpHr:b7dytri)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I'll emoji after the next push.

> Reviewed 7 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14185#-:-MJ8RVMR7Xw1okPyMWf5:bbmlc7l)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[systems/sensors/accelerometer.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14185#-MJ8Qz1QArLLl7oKb3gO:-MJ8Qz1R3K4VK0gU7GAi:bj233vn) ([raw file](https://github.com/robotlocomotion/drake/blob/05c55c188fd171e838ccf2b4f1329aba54026c3d/systems/sensors/accelerometer.h#L2)):*
> ```objc
> #pragma once
> // TODO(Posa): Rename header to accelerometer.h to match the class name.
> ```

nit This TODO should go away.

Ditto in gyroscope.h.

**Review by SeanCurtis-TRI — COMMENTED** [review]
And CI fixed.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14185#-:-MJ8ks2hDN6j1GZ1Bocy:b-6ebtga)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[systems/sensors/accelerometer.h, line 2 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14185#-MJ8Qz1QArLLl7oKb3gO:-MJ8kqyU6rSgRSsU015d:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/05c55c188fd171e838ccf2b4f1329aba54026c3d/systems/sensors/accelerometer.h#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This TODO should go away.

Ditto in gyroscope.h.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14185#-:-MJ8pQJWAI-BYL83NTaN:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform)

**Pull request merged**
