### PR TITLE
Remove test-only accessors from DrakeVisualizer.

### PR DESCRIPTION
**Pull request by david-german-tri**
@liangfok for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4412)

### CODE REVIEW

**Comment by liangfok** [comment]
@david-german-tri, thanks for making these changes! :lgtm: after addressing one comment.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/toyota_hsrb/test/hsrb_system_factories_test.cc, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4412#-KYPh4CuBYGwUbMzAt0Z:-KYPh4Cu6dPlUiICD6hF:bojz5hz) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ae5cd0a6fc33979cd93743022da982b2f22d19/drake/examples/toyota_hsrb/test/hsrb_system_factories_test.cc#L132)):*
> ```cpp
> 
> 
> // Verifies that @p message is correct. Only a few key fields are checked. The
> ```

BTW, please update "@p message" to be "@p message_bytes".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412#-:-KYPhM5FCId21IDv4iKh:baubxed)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/toyota_hsrb/test/hsrb_system_factories_test.cc, line 132 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4412#-KYPh4CuBYGwUbMzAt0Z:-KYPkJpdAG9n_9kBLe0z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d8ae5cd0a6fc33979cd93743022da982b2f22d19/drake/examples/toyota_hsrb/test/hsrb_system_factories_test.cc#L132)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, please update "@p message" to be "@p message_bytes".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412)*

**Comment by david-german-tri** [comment]
+@sammy-tri for platform review

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412#-:-KYPkN9r-QswhA7PDiZ4:bq11ftp)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412#-:-KYPwgYcDso73UaDZKzY:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4412)*

**Pull request merged**
