### PR TITLE
A simple unit test to load files with <include> tags

### PR DESCRIPTION
**Pull request by nkoenig**
This pull request supports loading an SDF <world> that contains multiple <model> elements.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9159)

### CODE REVIEW

**Comment by sherm1** [comment]
> I can change this code to load only the first world, and throw and exception if multiple worlds are specified. Does that work?

Sounds reasonable to me, what do you think @amcastro-tri ?

**Comment by amcastro-tri** [comment]
sry, I've been out of the loop on this one and I trust your judgement. My two cents though, how was sdformat designed to deal with the "multiple worlds" case? shouldn't that get handled at the sdformat level? shouldn't that be part of the specification? 
What are the use cases? usually we'd have a single file with a world from which we `<include>` several models? (i.e. files with `<models>`s in them but not `<world>`?).

If the latter are true, then I guess trowing an exception with a reasonable message is a good option (again, shouldn't sdformat do this as part of the specification?).

**Comment by amcastro-tri** [comment]
Thanks @nkoenig. It'd be nice if that piece of information made it to the SDF docs online.

Based on that, I believe throwing an exception when multiple worlds are found is a good solution.

**Comment by scpeters** [comment]
I think I've resolved the merge conflicts

**Pull request merged**
