### PR TITLE
Add VTK as an optional external

### LINKED ISSUE #4807: Unable to Run CMake on Drake on Ubuntu 16.04 with VTK 6.2 and ROS Kinetic
# Problem Definition

The following error occurs when running `cmake ..` on an machine with Ubuntu 16.04, ROS Kinetic, and VTK6:

```
-- Preparing to build director with dependencies bot_core_lcmtypes;ctk_python_console;drake;lcm;libbot;pythonqt;qt_property_browser
CMake Warning at cmake/externals.cmake:208 (find_package):
  Could not find a configuration file for package "VTK" that is compatible
  with requested version "5.10".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/vtk-6.2/VTKConfig.cmake, version: 6.2.0

Call Stack (most recent call first):
  cmake/externals.cmake:522 (drake_add_cmake_external)
  CMakeLists.txt:312 (drake_add_external)


CMake Error at cmake/externals.cmake:210 (find_package):
  Could not find a configuration file for package "VTK" that is compatible
  with requested version "5.8".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/vtk-6.2/VTKConfig.cmake, version: 6.2.0

Call Stack (most recent call first):
  cmake/externals.cmake:522 (drake_add_cmake_external)
  CMakeLists.txt:312 (drake_add_external)


-- Configuring incomplete, errors occurred!
```

I suspect this started to happen after #4527 and the removal of the `-DUSE_SYSTEM_VTK=OFF` option.

Relevant comment here: https://github.com/RobotLocomotion/drake/pull/4527#issuecomment-269520481

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Teach the superbuild that VTK is an optional system dependency, which defaults to using the system version, and how to build it if enabled but not using the system version.

This enables us to provide our own VTK if the system version is not available (fixes #4807). This is also much easier to use than the old method of relying on the director superbuild (which we no longer use) to build VTK, and unlike that approach will also allow drake itself (#4834) to use VTK.

Also, false coupling between director and signalscope is now fully broken.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4844)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

If I did this right, CI will be a "poor" test because it will continue to use system-provided VTK as always. Someone else (i.e. in addition to my own testing) might want to locally test that they can build with VTK provided by the drake superbuild.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4844#-:-KaxhPp-KHscKaJhE-tc:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm: aside from one documentation request below

---

Reviewed 3 of 5 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 109 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4844#-KaxvW0xw5RcklKLyZJ-:-KaxvW0xw5RcklKLyZJ0:bxz9ngh) ([raw file](https://github.com/robotlocomotion/drake/blob/513252b85a6a3b56c02ebd68b580eee78b6f4439/cmake/options.cmake#L109)):*
> ```CMake
>     set(_sd_DEPENDS DEPENDS "${_sd_DEPENDS}")
>   endif()
>   if(_sd_PREFER_SYSTEM_VERSION)
> ```

Please document the new parameters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4844#-:-Kaxw0mu0CvF8VjbSrzn:bbzj2sh)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4844)*

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4844#-:-KbBXjMtDCUgex9BLBqd:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4844)*

**Pull request merged**
