### PR TITLE
Refactor Curve2 to accept velocities as additional waypoint data

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8527)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@jwnimmer-tri for feature review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-:-L9NlPWsC5B7_i0G3bHW:b-qf68jg)*

**Comment by jwnimmer-tri** [comment]
@jadecastro I am platform review on-call for Monday, so how about I wear the platform reviewer hat on this one (and I'll also double-check the rough design as I do my review)?  Then today you could assign a feature review from the team that's going to use this.

In particular, feature review should look at:
- that the semantics of speed-at-point are well defined, in particular about how speeds are to be understood or interpolated when between points;
- that the semantics are clear when speed is of no interest (the preexisting use cases).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-cache please

**Comment by jwnimmer-tri** [comment]
I didn't read all of the Curve2 code (yet), but left some high-level thoughts.

The segment-based representation, inferred from points, seems increasingly burdensome and inopportune.  I can't really speak to the feature-review level of design review for whatever application this is feeding, but it seems to my eye like its going to be a real pain.  But I'll let you guys sort that out.  My real concerns I've placed into the inline discussions below.

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---

*[automotive/curve2.h, line 19 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b88Si7J09FHrih3MP:-L9b88Sk-XRp5iSvq0H8:baymxfz) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L19)):*
> ```objc
> template <typename T>
> using Point2 = Eigen::Matrix<T, 2, 1, Eigen::DontAlign>;
> using Point2d = Point2<double>;
> ```

These are probably too general of a name to live at namespace scope within such a specific (curve) header?  Also, they lack documentation.  Also, I see no reason why `drake::Vector2` and `Eigen::Vector2d` can't be the types used within the Waypoint constructor and member field, and these aliases just die.

---

*[automotive/curve2.h, line 22 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b7o4FBLpUAja8Gvd2:-L9b7o4FBLpUAja8Gvd3:b-wmrxn8) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L22)):*
> ```objc
> 
> /// Contains a waypoint consisting of a 2-D x,y position and, optionally, speed
> /// (default zero).
> ```

How does a recipient of this datatype know whether the speed was absent, versus a "stopped" (zero-speed) waypoint?

Or maybe zero-speed is disallowed?  Zero-speed waypoints tend to be a giant pain in my past experience.

---

*[automotive/curve2.h, line 33 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b8nJ-DNeH_sCYB-SC:-L9b8nJ-DNeH_sCYB-SD:b2ubb7q) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L33)):*
> ```objc
> 
>   Point2<T> position{Point2<T>::Zero()};
>   T speed{0.};
> ```

The name `speed` implies a value that is non-negative (possibly except for floating point precision errors).  Is that true?  Document if so.

---

*[automotive/curve2.h, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bArAcEderk4F4aPcL:-L9bArAcEderk4F4aPcM:b-bwbdic) ([raw file](https://github.com/robotlocomotion/drake/blob/352ac8c54976b177b0517d269a06d9f829332d94/automotive/curve2.h#L40)):*
> ```objc
> 
>   /// Constructor that traces through the given @p waypoints in order.
>   /// Throws an error if @p waypoints.size() == 1.
> ```

Why lose the second sentence of this comment?  I assume the unit test is still testing it.

---

*[automotive/curve2.h, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bAaZH7MxTxkOJSUuk:-L9bAaZH7MxTxkOJSUul:b-k3a1ix) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L41)):*
> ```objc
> /// A result type for the Curve2::CalcPositionResult method.
> /// N.B. The Curve2 implementation is only C1-continuous, so we do not provide
> /// AutoDiff for speed_dot.
> ```

It also looks like `pos_deriv` doesn't offer AutoDiff (its hard-coded to double).  Is this comment incomplete?

---

*[automotive/curve2.h, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b9BnyEf0ZtjDwVJZx:-L9b9BnyEf0ZtjDwVJZy:bo3806e) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L42)):*
> ```objc
> /// N.B. The Curve2 implementation is only C1-continuous, so we do not provide
> /// AutoDiff for speed_dot.
> /// TODO(jadecastro) Enable AutoDiff support.
> ```

I don't know what this means (what is still lacking?).  This struct seems finished with respect to AutoDiff-related work.

---

*[automotive/curve2.h, line 44 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b929o1WZfzCOERIy5:-L9b929o1WZfzCOERIy6:bmugfqb) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L44)):*
> ```objc
> /// TODO(jadecastro) Enable AutoDiff support.
> template <typename T>
> struct PositionResult : WaypointT<T> {
> ```

Unclear why using has-a is appropriate here.
http://drake.mit.edu/styleguide/cppguide.html#Inheritance

---

*[automotive/curve2.h, line 48 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b8kxy5m2Xg3PClIvF:-L9b8ky-7X9_Uxc1usyg:b-l6xvnd) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L48)):*
> ```objc
>   PositionResult() = default;
>   /// Fully-parameterized constructor.
>   PositionResult(const Point2<T>& pos, const T& s, const Point2d& pos_deriv,
> ```

BTW Unclear that `s` means `speed`.

---

*[automotive/curve2.h, line 76 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bBoYLEXIkgYBXjwMN:-L9bBoYLEXIkgYBXjwMO:b66otdb) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L76)):*
> ```objc
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Curve2)
> 
>   explicit Curve2(const std::vector<Waypoint>& waypoints)
> ```

Is it well-formed, for a path that does have speeds assigned, for two adjacent waypoints to have zero speed?  If so, what does it mean?  How would a speed-obeying car traverse such a segment?

---

*[automotive/curve2.h, line 107 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bBMX7BKInbNv5kI8g:-L9bBMX9BNtL4qP7DPKv:b-z6lf5c) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L107)):*
> ```objc
>   /// linear interpolation scheme used herein.  With the exception of the final
>   /// waypoint, where speed_dot is zero, speed_dot at waypoint i is the same as
>   /// that for segment {i, i+1}.
> ```

We are promising that speed_dot exactly at a waypoint `i` is forward-looking (to the next segment) instead of the prior one.  The position_deriv however, is allowed to be either the incoming or outgoing segment. 

Why are the two choice-of-segment semantics different?  That seems potentially confusing.

---

*[automotive/trajectory_car.h, line 68 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bAAu-AHharvOgYIGb:-L9bAAu-AHharvOgYIGc:bg2xatm) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/trajectory_car.h#L68)):*
> ```objc
>   /// Constructs a TrajectoryCar system that traces a given two-dimensional @p
>   /// curve.  Throws an error if the curve is empty (has a zero @p path_length).
>   explicit TrajectoryCar(const Curve2<double>& curve)
> ```

So the TrajectoryCar takes in a curve, the curve might have speeds assigned, but it just ignores them?  That seems bad.

Should it fail-fast if given speeds?  Or  should there be different data structures for path-only vs path-and-speed curves?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-:-L9bC2Uk8yelnTDe71RJ:b-ntm7p5)*

**Comment by jadecastro** [comment]
Thanks @jwnimmer-tri. After discussing with @stonier, and looking into the design implications based on your comments, it makes sense to pause the refactor to Curve2, revisiting it again once we've worked out the TrajectoryAgent design (#8529). I agree that it will be a bit of a pain to work with the segment-based representation at the outset.

(I perhaps see value in keeping this around to support other use cases like sample-based motion planning (e.g. RRT) but this is a separate issue.)

---

Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[automotive/curve2.h, line 40 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9bArAcEderk4F4aPcL:-L9ecY_uCFEFOifaYblS:b-xlf6io) ([raw file](https://github.com/robotlocomotion/drake/blob/352ac8c54976b177b0517d269a06d9f829332d94/automotive/curve2.h#L40)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Why lose the second sentence of this comment?  I assume the unit test is still testing it.
</blockquote></details>

Done. (zapped that comment by accident)

---

*[automotive/curve2.h, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-L9b9BnyEf0ZtjDwVJZx:-L9exjnmD7OMtZh_3LVJ:bdcv6ku) ([raw file](https://github.com/robotlocomotion/drake/blob/87b5e4fea001e052f4d621b630dba543e2b52dd9/automotive/curve2.h#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't know what this means (what is still lacking?).  This struct seems finished with respect to AutoDiff-related work.
</blockquote></details>

Good point 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8527#-:-L9fWAMuEGBnMC1pdSNE:bgiejx0)*

**Comment by jadecastro** [comment]
(Replaced by #8720)

**Pull request closed without merging**
