### PR TITLE
Apply the same joint limits when planning which the driver uses

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7603)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@avalenzu for feature review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0KhjvMX63j3B0wXQpN:bvpmr17)*

**Comment by avalenzu** [comment]
:lgtm: Looks like we'll need to tweak `pick_and_place_state_machine_test` to make it happy though.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0NODBrYJK25KlTHUAC:b4cu6hx)*

**Comment by sammy-tri** [comment]
Ah yes, the `--config snopt` does not imply `--test_tag_filters snopt` bites me again.  Should be fixed now.

+@sherm1 for platform review

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0Q7BxrS35spN_QGJN9:b-4wg4c)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a couple of minor BTWs, ptal.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 317 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-L0QkEmPF-6Tx2mAxkAu:-L0QkEmPF-6Tx2mAxkAv:b5tov1k) ([raw file](https://github.com/robotlocomotion/drake/blob/8358bbc4912bfb6fb9306a2c07c5de5d249ab60b/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L317)):*
> ```cpp
>   // The iiwa driver limits joint angle commands to prevent hitting
>   // the stops and triggering an exception.  Update the tree we're
>   // using for planning to reflect this limit.
> ```

BTW I don't get the leap from this comment to adding 1 degree. Are you saying that the driver stretches things by a degree somewhere? Please clarify.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 318 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-L0QjpYiaRRl8H6cAMYF:-L0QjpYiaRRl8H6cAMYG:b-e08vuq) ([raw file](https://github.com/robotlocomotion/drake/blob/8358bbc4912bfb6fb9306a2c07c5de5d249ab60b/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L318)):*
> ```cpp
>   // the stops and triggering an exception.  Update the tree we're
>   // using for planning to reflect this limit.
>   const double kOneDegree = M_PI / 180.;
> ```

BTW this confused me on first read. Please consider calling this `kOneDegreeInRadians` for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0QkiAkeMMcvV2Cgcmv:baxzulx)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 317 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-L0QkEmPF-6Tx2mAxkAu:-L0QqfxMaWr9rzEKr27D:bin87ml) ([raw file](https://github.com/robotlocomotion/drake/blob/8358bbc4912bfb6fb9306a2c07c5de5d249ab60b/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L317)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I don't get the leap from this comment to adding 1 degree. Are you saying that the driver stretches things by a degree somewhere? Please clarify.
</blockquote></details>

Done.  (at least, I hope the new text is clearer)

---

*[examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 318 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-L0QjpYiaRRl8H6cAMYF:-L0QqjqF_aYFmFxrbKg2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8358bbc4912bfb6fb9306a2c07c5de5d249ab60b/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L318)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this confused me on first read. Please consider calling this `kOneDegreeInRadians` for clarity.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0QsN0HSA3TRN5n15Sw:bfqm13d)*

**Comment by avalenzu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603)*

**Comment by sammy-tri** [comment]
Not waiting for the mac test.  It's doomed for unrelated reasons and the pick and place state machine test passed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7603#-:-L0R9h5ox-P1duSfZjJ9:b87kpj0)*

**Pull request merged**
