### PR TITLE
Fix cpplint whitespace/end_of_line and whitespace/ending_newline.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Trying on drake00# now.

**Comment by liangfok** [comment]
+1 Looks like all CI checks also passed.

**Comment by jwnimmer-tri** [comment]
> +1 Looks like all CI checks also passed.

Nope.  For non-documentation-only changes, we need drake00{3,5,6} to also all pass.

**Comment by liangfok** [comment]
I don't see drake00{3,5,6} on the CI list anymore:

screen shot 2016-04-02 at 12 41 40 pm

Were they removed?

**Comment by jwnimmer-tri** [comment]
It's complicated (duct tape and bailing wire).  Let David / Russ / I handle it.

**Pull request merged**
