### PR TITLE
Add cc file to generated vector indicies

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This gets us ODR storage for our constants.  I threw in a tiny build system fixup here, also.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3222)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3222#-:-KPrtHqniEHhIcnWPCVB:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
The Jenkins failure was a flake; I'll wait to retest to see if @rpoyner-tri has any fixes that would anyway necessitate a rebuild.

**Comment by rpoyner-tri** [comment]
Refresh my memory -- why are these values static int members of a struct, instead of, say, members of an enum type?

The patch does what it says on the tin, but I just find myself questioning the whole (sub-)enterprise.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3222#-:-KPsEwBDnHxJgeBLC4Cz:b-726v1u)*

**Comment by rpoyner-tri** [comment]
From nimmer f2f, something something Eigen template horror requires indices to be actual ints. whee. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3222#-:-KPsFjcnq6K9BK1Bb6My:bby7lp1)*

**Comment by jwnimmer-tri** [comment]
The windows build failure is CDash being broken; using override-merge.

**Pull request merged**
