### PR TITLE
system: Add compatibility checks for output using methods

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Relevant to: #12560

Add system-id labeling to the SystemOutput class, and use that to
implement checks using ValidateCreatedForThisSystem(). Retire the
expensive, and less-precise CheckValidOutput() method.

This should complete compatibility checking for public methods of
System<T>. Several other classes need work to be fully checked.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[systems/framework/system_output.h, line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtOBJL3ZgLn06xsda8:-MZtOBJL3ZgLn06xsda9:bc0xpnp) ([raw file](https://github.com/robotlocomotion/drake/blob/6a3255c95dc4936d24bda80ffa6ae1a2dc2ed38c/systems/framework/system_output.h#L93)):*
> ```objc
>   }
> 
>   // Gets the id of the subsystem that created this state.
> ```

s/state/output/ here and below.

**Review by rpoyner-tri — COMMENTED** [review]
+@sherm1 for feature review, since I'm deleting a chunk of your code, and this patch is very much enabled by the preceding method rename patch.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007#-:-MZtPuiq6Q9mbxHCpRXB:b-zhancq)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtYb1D9RK7x_6Cx3Xm:-MZtYb1D9RK7x_6Cx3Xn:b-ghv510) (no related file):*
Ooh, exciting test failure. I wonder if the patch found a pre-existing bug, or introduced one.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtYb1D9RK7x_6Cx3Xm:-MZtfOU80e842N3UhDAC:bkdzvvp) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Ooh, exciting test failure. I wonder if the patch found a pre-existing bug, or introduced one.
</blockquote></details>

Hm, adding some print debugging (gdb was lying to me, for some reason), it looks like a real error:
```
...
C++ exception with description "drake::systems::SystemOutput<double>:38 was not created for drake::systems::controllers::(anonymous)::TestPlantWithMinOutputs system ::_::drake/systems/controllers/(anonymous)/TestPlantWithMinOutputs@0000555fd92ad650:31" thrown in the test body.
[  FAILED  ] ConnectControllerTest.NonSaturatingController (5 ms)
[ RUN      ] ConnectControllerTest.SaturatingController
unknown file: Failure
C++ exception with description "drake::systems::SystemOutput<double>:47 was not created for drake::systems::controllers::(anonymous)::TestPlantWithMinOutputs system ::_::drake/systems/controllers/(anonymous)/TestPlantWithMinOutputs@0000555fd92ad650:39" thrown in the test body.
...
```
Note that 38 != 31 (first error) and 47 != 39 (second error). Will investigate.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtYb1D9RK7x_6Cx3Xm:-MZtkYmDBscku8CV5iDI:b-ju8xf7) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Hm, adding some print debugging (gdb was lying to me, for some reason), it looks like a real error:
```
...
C++ exception with description "drake::systems::SystemOutput<double>:38 was not created for drake::systems::controllers::(anonymous)::TestPlantWithMinOutputs system ::_::drake/systems/controllers/(anonymous)/TestPlantWithMinOutputs@0000555fd92ad650:31" thrown in the test body.
[  FAILED  ] ConnectControllerTest.NonSaturatingController (5 ms)
[ RUN      ] ConnectControllerTest.SaturatingController
unknown file: Failure
C++ exception with description "drake::systems::SystemOutput<double>:47 was not created for drake::systems::controllers::(anonymous)::TestPlantWithMinOutputs system ::_::drake/systems/controllers/(anonymous)/TestPlantWithMinOutputs@0000555fd92ad650:39" thrown in the test body.
...
```
Note that 38 != 31 (first error) and 47 != 39 (second error). Will investigate.
</blockquote></details>

Sure enough, outputs allocated from the top-level diagram were being used with a subsystem. Fix in local testing now.

---

**Review by sherm1 — COMMENTED** [review]
`//systems/controllers:pid_controlled_system_test` failed -- looks like it uses a bad SystemOutput! Cool.

Feature :lgtm_strong: pending a fix for that test.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007#-:-MZtk4bO7E8dcO5XuntL:b-kyqas0)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtYb1D9RK7x_6Cx3Xm:-MZtn9ctB_AmmnvwN_Rb:btt8znr) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Sure enough, outputs allocated from the top-level diagram were being used with a subsystem. Fix in local testing now.
</blockquote></details>

I have a fairly tight fix for the breakage, but see also broader concerns below.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtmS39A4ODNfjOc0KW:-MZtmS39A4ODNfjOc0KX:b-apan8l) (no related file):*
Looking at the docs for SystemOutput, I'm starting to wonder if this might in fact be a breaking change: https://github.com/RobotLocomotion/drake/blob/master/systems/framework/system_output.h#L20-L24

It appears that the docs kind of encouraged sloppy usage. Also maybe relevant is the lack of a handy subsystem helper on Diagram, something like AllocateSubsystemOutput() to be work in parallel with similar GetSubsystem[THING]() methods.

---

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtmS39A4ODNfjOc0KW:-MZto7JKBEP9DTml3px4:b-5v5qtb) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Looking at the docs for SystemOutput, I'm starting to wonder if this might in fact be a breaking change: https://github.com/RobotLocomotion/drake/blob/master/systems/framework/system_output.h#L20-L24

It appears that the docs kind of encouraged sloppy usage. Also maybe relevant is the lack of a handy subsystem helper on Diagram, something like AllocateSubsystemOutput() to be work in parallel with similar GetSubsystem[THING]() methods.
</blockquote></details>

OTOH, a quick grep of AllocateOutput in anzu returned 0 hits. :shrug: 
There are a few uses in drake-external-examples, but they look to a very quick glance to be ok.

Soliciting thoughts on docs and possible breakage from @jwnimmer-tri .

---

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtmS39A4ODNfjOc0KW:-MZtsePv3f56_Ry42McF:b4l4k16) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

OTOH, a quick grep of AllocateOutput in anzu returned 0 hits. :shrug: 
There are a few uses in drake-external-examples, but they look to a very quick glance to be ok.

Soliciting thoughts on docs and possible breakage from @jwnimmer-tri .
</blockquote></details>

SystemOutput is an anachronism from Drake's early days. I think it is only used in some old test cases. It is not the way people normally get output from a Drake System!

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15007#-MZtmS39A4ODNfjOc0KW:-MZudTYc-mejwNJaQsyt:bah0km8) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

SystemOutput is an anachronism from Drake's early days. I think it is only used in some old test cases. It is not the way people normally get output from a Drake System!
</blockquote></details>

I agree with Sherm and other related observations in the PR discussion.  The impact here is relatively narrow, so we should move ahead.

I'll also observe that the entire gist of #12560 is to break people who are playing games with their storage allocations.  Even with other PRs in this train, people might have started seeing errors where they were passing around pointers to storage that happened to be congruent with what was desired, but was allocated from the wrong place.   (IIRC, we had one or two of those in the earlier parts of this train.)  We are now snugging up the bolts on the machine, so people might get new diagnostics for mis-use.  I think that's a fair policy, with whatever appropriate release notes we deem sufficient.  It's also notable that the _correct_ APIs people should have been using have existed since forever, so it should be easy for users who don't want a flag day change to first port to the correct API using their existing Drake, and then the new Drake will work right away.

---

**Review by rpoyner-tri — COMMENTED** [review]
+@sammy-tri for platform review, by schedule

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007#-:-MZx3FS35MDgL9QIOvYy:b5crnyn)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  (and it even caught one!)

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15007#-:-MZy-atK4c4yaAkVBVcy:bbbmdzv)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform) (waiting on @rpoyner-tri)

**Pull request merged**
