### PR TITLE
utility code for building diagrams for simulating multiple instances of iiwa + gripper.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
0. added a wrapper around DiagramBuilder to facilitate building diagrams that has multiple instances of StateFeedbackControllers and sinlge RigidBodyPlant. 
1. moved the lump gripper mass code from iiwa_wsg_simulation.cc to iiwa_common. 
2. added a demo for multiple iiwa arm and multiple wsg gripper.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5427)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. thanks 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KeeE8NO8tIUdqloOcQv:b-gjuu33)*

**Comment by siyuanfeng-tri** [comment]
cc @sammy-tri 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KeeEDZVxpAtZ3mR675K:bs3yvw)*

**Comment by naveenoid** [comment]
Thanks for this @siyuanfeng-tri I basically have one concern, whats the right location for this component? We are now starting to see a proliferation of components that are interrelated across the subfolders..

---

Reviewed 7 of 23 files at r1, 9 of 14 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehJHZA175fVpOSCVwb:-KehJHZA175fVpOSCVwc:bpq5yhj) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L141)):*
> ```cpp
>     SimDiagramBuilder<T> builder;
>     DiagramBuilder<T>* base_builder = builder.get_mutable_builder();
> ```

BTW: You probably noticed, this stuff needs to move to the IiwaAndWsgCombinedPlant builder that is now moved to IiwaWorld.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehMmJc6AreoH1eJ83O:-KehMmJd50RTFFFtY4s2:b-a7ke8e) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L79)):*
> ```cpp
> 
>   // Create the command subscriber and status publisher.
>   systems::DiagramBuilder<double>* base_builder = builder.get_mutable_builder();
> ```

BTW: Why is this called base_builder? I am also not clear why it is not explicitly then built unlike the builder object few lines below.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-Keii1n4UpoPEXepSDds:b9eh7wj) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
> ```objc
> namespace examples {
> namespace kuka_iiwa_arm {
> ```

BTW: Im wondering if a TODO would be useful here noting if it needs to move to a common location across manipulation

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeieDTGQrlJn2EdXH03:-KeieDTGQrlJn2EdXH04:b-a5n1cy) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L23)):*
> ```objc
>  * controlled simulation. This class provides three utilities: adding /
>  * accessing RigidBodyPlant, StateFeedbackController and DrakeVisualizer.
>  */
> ```

Shouldnt this comment block be a doxy block?

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keid_G99FnW3gHAPYJN:-Keid_GA0NXOXWLYOwzG:bh0tmbg) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L25)):*
> ```objc
>  */
> template <typename T>
> class SimDiagramBuilder {
> ```

BTW: Im wondering if this component needs to be named something else? The name seems slightly misleading. How about "ControlledVisualisedDiagramBuilder"? 

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeifPF86J4hqLiB2PS8:-KeifPF9xKpE-eHR8a43:bpstngx) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L5)):*
> ```CMake
>       controlled_kuka_demo.cc)
>   target_link_libraries(controlled_kuka_demo
>       drakeSimDiagramBuilder
> ```

This list will need alphabetizing.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeifXfn6VEXJriloKvl:-KeifXfn6VEXJriloKvm:brhumzt) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L18)):*
> ```CMake
>       kuka_cartesian_way_point_demo.cc)
>   target_link_libraries(kuka_cartesian_way_point_demo
>       drakeSimDiagramBuilder
> ```

Same here.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeigAAVbICcF4makWK8:-KeigAAVbICcF4makWK9:bifmkkm) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L80)):*
> ```Python
>     ],
>     deps = [
>         ":world_sim_tree_builder",
> ```

Im not sure about the bazel deps policy but this might require alphabetizing too..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KeihN3MRvPLCLdheiQw:b2su4ny)*

**Comment by siyuanfeng-tri** [comment]
i don't think it really belongs to iiwa world, and that's the only reason i didn't put it there. 

---

Reviewed 23 of 23 files at r1.
Review status: 12 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 141 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehJHZA175fVpOSCVwb:-Kej6JmsXlEzTSG7YhnR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L141)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: You probably noticed, this stuff needs to move to the IiwaAndWsgCombinedPlant builder that is now moved to IiwaWorld.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehMmJc6AreoH1eJ83O:-KeiiuwC4N_PEXgX9juc:bn9ile3) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L79)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Why is this called base_builder? I am also not clear why it is not explicitly then built unlike the builder object few lines below.
</blockquote></details>

the long story is like this
the SimDiagramBuilder is a wrapper around DiagramBuilder instead of directly inherent from it. The biggest reason being I haven't thought of a scenario that I would want to cast a SimDiagramBuilder to a base pointer. The down side is that it's more cumbersome to call DiagramBuilder's API. e.g.
If SimDiagramBuilder : public DiagramBuilder, you can call sim_diagram_builder.Connect(src, dest), now you have to explicitly do sim_diagram_builder.get_mutable_diagram_builder()->Connect(src, dest), as the getter returns the internal DiagramBuilder.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-KeimYzsdcWqbbncHIIm:buuaop4) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Im wondering if a TODO would be useful here noting if it needs to move to a common location across manipulation
</blockquote></details>

maybe systems? 

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeieDTGQrlJn2EdXH03:-KeimULkMrTAE55KaaRR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L23)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Shouldnt this comment block be a doxy block?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keid_G99FnW3gHAPYJN:-KeikAcOWwHzKffjzzLk:b895amn) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L25)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Im wondering if this component needs to be named something else? The name seems slightly misleading. How about "ControlledVisualisedDiagramBuilder"? 
</blockquote></details>

the funny part is you don't actually have to add controllers or visualizers, the only thing that's required is the plant. so your suggestion isn't really accurate either... 

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeifPF86J4hqLiB2PS8:-KeilFLOK7QTY_dpqxmQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L5)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

This list will need alphabetizing.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeifXfn6VEXJriloKvl:-KeilGJq1TaG4LLo8_k7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/controlled_kuka/CMakeLists.txt#L18)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 80 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KeigAAVbICcF4makWK8:-KeilVUrNQqJG0MdBlJu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L80)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Im not sure about the bazel deps policy but this might require alphabetizing too..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KeiltmYq_zjG33JmRa6:b-1enmz1)*

**Comment by siyuanfeng-tri** [comment]
+@sammy-tri for platform review. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-Kej6MN0tBd5QAyjha4H:bavs5hr)*

**Comment by sammy-tri** [comment]
Review mostly complete.  I need to try to find a previous discussion on what our policy is on death tests.

---

Reviewed 6 of 23 files at r1, 5 of 14 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejJgvK0-AbdQBqVkD4:-KejJgvK0-AbdQBqVkD5:b-skg10t) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L16)):*
> ```cpp
> 
> #include "drake/common/drake_path.h"
> #include "drake/examples/kuka_iiwa_arm/sim_diagram_builder.h"
> ```

This doesn't appear to be used in this file.  (anymore?)

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-KejHIyCIMgdfNQuv6yE:bug6u56) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

maybe systems? 
</blockquote></details>

BTW once I finally get around to making a drake/manipulation directory, this will certainly go there at least.  We can promote to systems/ if/when we decide.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejKu7xafzPUKkIVjK6:-KejKu7xafzPUKkIVjK7:blwlch5) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L104)):*
> ```Python
> )
> 
> drake_cc_binary(
> ```

We're not bothering to build this in the CMake world?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc, line 32 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejLACSpyhlAauwNsGL:-KejLACSpyhlAauwNsGM:bkfq8n3) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc#L32)):*
> ```cpp
>   wsg->clear();
> 
>   int id;
> ```

Is there a reason not to declare this inside the loop where it's used?

---

*[drake/examples/kuka_iiwa_arm/test/sim_diagram_builder_test.cc, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejMsuk9DczFH2lfVw9:-KejMsulSbmShnOmmHG1:b-1ie5cm) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/test/sim_diagram_builder_test.cc#L40)):*
> ```cpp
>   DRAKE_DEMAND(num_wsg >= 0);
> 
>   int id;
> ```

Declare inside the loops where it's used?  I don't think its supposed to carry meaning between the two loops and it kinda looks like it might in the current code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KejNJ5A7TzqnBczLuYB:b-3xeqfg)*

**Comment by siyuanfeng-tri** [comment]
Review status: 15 of 20 files reviewed at latest revision, 11 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejJgvK0-AbdQBqVkD4:-KejRB1Vz0NqyqLSNOqc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc#L16)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This doesn't appear to be used in this file.  (anymore?)
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-KejREIBgsRuj8mdj95a:bfq9ba) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW once I finally get around to making a drake/manipulation directory, this will certainly go there at least.  We can promote to systems/ if/when we decide.
</blockquote></details>

sounds good. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/BUILD, line 104 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejKu7xafzPUKkIVjK6:-KejWDmbgdEI_ycvsZ9L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_world/BUILD#L104)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

We're not bothering to build this in the CMake world?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc, line 32 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejLACSpyhlAauwNsGL:-KejRS80fEFT-6aZCogB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc#L32)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is there a reason not to declare this inside the loop where it's used?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/test/sim_diagram_builder_test.cc, line 40 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KejMsuk9DczFH2lfVw9:-KejRWRgqruQpEDat38U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3eca50d91afec6d377c69a0a1b97f1ad4c08b0c0/drake/examples/kuka_iiwa_arm/test/sim_diagram_builder_test.cc#L40)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Declare inside the loops where it's used?  I don't think its supposed to carry meaning between the two loops and it kinda looks like it might in the current code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by naveenoid** [comment]
Review status: 15 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehMmJc6AreoH1eJ83O:-KejfmHDSUyONw-DvZDE:b64w2co) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L79)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

the long story is like this
the SimDiagramBuilder is a wrapper around DiagramBuilder instead of directly inherent from it. The biggest reason being I haven't thought of a scenario that I would want to cast a SimDiagramBuilder to a base pointer. The down side is that it's more cumbersome to call DiagramBuilder's API. e.g.
If SimDiagramBuilder : public DiagramBuilder, you can call sim_diagram_builder.Connect(src, dest), now you have to explicitly do sim_diagram_builder.get_mutable_diagram_builder()->Connect(src, dest), as the getter returns the internal DiagramBuilder.

</blockquote></details>

I see..Ok i misunderstood the purpose of the class a bit. Could I request you to expand on the class doxy introduction to explain its use-case? I see the uses and see that it simplifies a few things in building these kinds of controlled systems but I think it needs a bit more of explanation if its a utility wrapper on DiagramBuilder.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-KejetmKvA6GbCi_Y5wm:b-p67agq) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

sounds good. 
</blockquote></details>

If @david-german-tri and/or @jwnimmer-tri are opposed to moving it to systems, I suggest something like utils in the upcoming drake/manipulation.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keid_G99FnW3gHAPYJN:-KejfCaYfi8livFQlhAn:btk0ja1) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L25)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

the funny part is you don't actually have to add controllers or visualizers, the only thing that's required is the plant. so your suggestion isn't really accurate either... 
</blockquote></details>

Got it. This was a colour of the bike shed quibble anyhow..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by david-german-tri** [comment]
Review status: 15 of 20 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-KejjYpETJlRXDGcsDXN:b-puhl8o) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

If @david-german-tri and/or @jwnimmer-tri are opposed to moving it to systems, I suggest something like utils in the upcoming drake/manipulation.
</blockquote></details>

If this is only used for manipulation, it should live in a manipulation-specific directory.  If it gets use on other kinds of projects, we can think about promoting it to an infrastructure directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by sammy-tri** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Kejqpnxj5IeF0Z6oOi2:-Kejqpnxj5IeF0Z6oOi3:b-4otjxy) ([raw file](https://github.com/robotlocomotion/drake/blob/4f7af3c81e50bf4e9fa2e7e13c4f3bd549c8f62f/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L60)):*
> ```cpp
>   // Exposing feedforward acceleration. Should help with more dynamic
>   // motions.
>   auto iiwa_controller =
> ```

The builds are blowing up because this appears to shadow a member variable...   Why do the member variables not end in _, and is this one still even needed if it's a local here with this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by siyuanfeng-tri** [comment]
Review status: 18 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/kuka_simulation.cc, line 79 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-KehMmJc6AreoH1eJ83O:-KejtVcGltW1DrfOrEok:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/kuka_simulation.cc#L79)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I see..Ok i misunderstood the purpose of the class a bit. Could I request you to expand on the class doxy introduction to explain its use-case? I see the uses and see that it simplifies a few things in building these kinds of controlled systems but I think it needs a bit more of explanation if its a utility wrapper on DiagramBuilder.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-Kejt33TrQFg7BeNfq_p:b-bgtbxp) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

If this is only used for manipulation, it should live in a manipulation-specific directory.  If it gets use on other kinds of projects, we can think about promoting it to an infrastructure directory.
</blockquote></details>

i added a little todo here about where to move it to eventually. i think we will follow david's comment. 

---

*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keid_G99FnW3gHAPYJN:-KejtG90hS40B8LcmuMs:bdpqmj0) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L25)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Got it. This was a colour of the bike shed quibble anyhow..
</blockquote></details>

since we can't find a good name now, and we are the only users, i vote we keep with it for now. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 60 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Kejqpnxj5IeF0Z6oOi2:-KejsB0SzzEbxiRPpFwX:bjixll7) ([raw file](https://github.com/robotlocomotion/drake/blob/4f7af3c81e50bf4e9fa2e7e13c4f3bd549c8f62f/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L60)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The builds are blowing up because this appears to shadow a member variable...   Why do the member variables not end in _, and is this one still even needed if it's a local here with this PR?
</blockquote></details>

i am fixing those went with _, might eventually need them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-Kejv_drdacIUVa-uYdi:bnfp4nl)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/sim_diagram_builder.h, line 18 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-Keii1n4UpoPEXepSDdr:-Kek5Wt6nVKH5hLMwyLI:b841dtb) ([raw file](https://github.com/robotlocomotion/drake/blob/d863bff6a9ebce321b8f54c9feca57b3d7d88621/drake/examples/kuka_iiwa_arm/sim_diagram_builder.h#L18)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

i added a little todo here about where to move it to eventually. i think we will follow david's comment. 
</blockquote></details>

@david-german-tri can you mark this resolved, thanks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5427#-:-KemJ3CHAvpatENpvlwu:bnfp4nl)*

**Pull request merged**
