### PR TITLE
Use dReal-4.20.04.1

### PR DESCRIPTION
**Pull request by soonho-tri**
nlopt-2.6.2 introduces new enum value `NUM_RESULTS` and this version handles it.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13133)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by soonho-tri** [comment]
+@jamiesnape for both reviews, please.

**Comment by jwnimmer-tri** [comment]
@soonho-tri Could we have a github https://github.com/dreal/dreal4/releases for this (or 4.20.04.02)?  The tools/workspace/new_release checker is asking me to downgrade without one.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , Done.

https://github.com/dreal/dreal4/releases/tag/4.20.04.1

**Comment by jwnimmer-tri** [comment]
Confirmed fixed, thanks!

**Pull request merged**
