### PR TITLE
Pass through LDFLAGS to autotools externals

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3890)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-coverage please
@drake-jenkins-bot linux-clang-experimental-coverage please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
:lgtm: Is this just for completeness, or was something broken?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3890#-:-KUsm8Ek3KTm2WgzV8XX:b5oseg4)*

**Comment by jamiesnape** [comment]
The sanitizer builds were broken even more than before, which is what alerted me.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3890#-:-KUt7F4XwYNhryriD5nu:bb4qxiv)*

**Pull request merged**
