### PR TITLE
Revert "systems: Use Eigen's formatting in VectorBase::operator<<() output (#13365)"

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This reverts commit ac9316f3c8addd0bd692f669b6d4ff07347ef8c0.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13384)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
I commented here: https://github.com/RobotLocomotion/drake/issues/12257#issuecomment-632709748

I feel like this is a change motivated by the wrong workflow. In addition, it broke an Anzu test -- the test is easily fixable, which I would do, except for I don't agree with this change.

I would love to take about ~10-15min to discuss.

**Comment by jwnimmer-tri** [comment]
I'm ambivalent on what the C++ ostr format should be, but for pydrake we definitely want the repr-like string format (with brackets and commas) to appear.

**Comment by EricCousineau-TRI** [comment]
I feel kinda strongly about Python and C++ matching when possible; I hate issues being Python-specific ;)
I also feel that the motivation for this change is wrong, so strongly there too.

**Comment by jwnimmer-tri** [comment]
C++ and Python already differ, though -- C++ uses Eigen and Python uses numpy.  Each library its own irregularities, including how things are printed.  There's a valid argument for our C++ code to align with Eigen conventions, while Python code aligns with numpy conventions.

**Comment by jwnimmer-tri** [comment]
(I think still its valid to revert this commit in order to unbreak Python quickly.)

**Comment by EricCousineau-TRI** [comment]
> C++ and Python already differ, though [...]

Yes in terms of API, but when it comes to printing strings, I would prefer C++ handle it well, and Python just use that; rather than doing a slew of one-offs.
@sherm1 Can I ask for you to weigh in on this comment?
https://github.com/RobotLocomotion/drake/issues/8586#issuecomment-622990503

**Comment by jwnimmer-tri** [comment]
You have an opinion about what "well" means in C++.  I might even agree with it.  But it's just your opinion.  Any other printing in C++ where we _do_ have an Eigen::Vector in hand is going to use the Eigen default.  Why should `drake::log()->info("{}", myvec)` change its output depending on whether myvec is a BasicVector or a VectorXd?  You can't just talk over the consistency argument; you need to speak to it directly.

**Comment by EricCousineau-TRI** [comment]
Sounds good! Ultimately, if hashing out our opinions on the printing issue is what we want (#8586), then I'd be down for that!

For the revert, I'm of course happy to make this land soon. I would like to wait until Sherm and/or Andres have time to weigh in.

Sound feasible?

**Comment by jwnimmer-tri** [comment]
I am a-ok waiting to merge this until others can comment.

(However -- if you did want to revert now, I'd happily single LGTM it. We should never be afraid of reverts when things break, even if we put it back a few hours later.)

However, we do need Anzu to pass vs Drake tip, let's say within an hour or two.  So if this doesn't merge soon, you'll have to adapt Anzu to accept either printout style for now.

**Comment by EricCousineau-TRI** [comment]
Thanks! Will wait until 11:30a ET, and then request your review of Sherm and Andrés are busy.

**Comment by EricCousineau-TRI** [comment]
Sweet, thanks!

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

**Comment by sherm1** [comment]
Wait, why did you revert this? Did it break something in Drake?

**Comment by EricCousineau-TRI** [comment]
It broke stuff in Anzu; also, I agree 100% with the workflow, and I disagree 200% with this solution.
See comments in issue.

**Comment by EricCousineau-TRI** [comment]
Link: https://github.com/RobotLocomotion/drake/issues/12257#issuecomment-632709748

**Comment by jwnimmer-tri** [comment]
There's a whole thread above, and more in #12257.

This change was reverted because it broke pydrake's string representation for `BasicVector`.  The unit test that this PR changed was a true regression, not just chaff along for the ride.

**Comment by jwnimmer-tri** [comment]
To clarify Eric's post above: breaking Anzu is not itself a reason for a revert, in general.  Only to the extent than an Anzu break is indicative of a problem that went undetected in Drake CI (or review) is it a canary to make us aware of a regression in Drake.

**Comment by sherm1** [comment]
I want to fix Drake so that `VectorBase::operator<<` behaves like the Eigen equivalent and I appreciate @avalenzu's good deed in submitting a fix to that long-standing (if minor) issue.

I also agree that pydrake should manage its vector formatting to match numpy. But Eigen's formatting and numpy's are different, so it doesn't make sense to me to have pydrake depending on C++ formatting. And I assume it already has bespoke code for dealing with Eigen vector formatting?

Can we modify pydrake to decouple it from C++ formatting for vectors?

**Comment by EricCousineau-TRI** [comment]
Yes, in light of `VectorBase` vs. `Eigen::Matrix<>` solely in C++, that would make sense for now. Sorry for missing that part in your issue; but, in the future, is it possible to hoist the crux of the issue to the overview?

Also, I would really love to start this discussion:
https://github.com/RobotLocomotion/drake/issues/8586#issuecomment-622990503

**Pull request merged**
