### PR TITLE
Simplify ReplaceBilinearTerms

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6598)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpMfgB3qxLmF-50rWiX:b-utjvo1)*

**Comment by hongkai-dai** [comment]
I think there is a pothole in this code. If `x` or `y` contains an entry in `W`, then when we do 
```
poly.AddProduct(w_xy * p.second, symbolic::Monomial{});
```
We will run into a problem. This sounds absurd, but it is possible to say that diag(x) = x * xᵀ, and let `W = diag(x)`, so as to constrain that `x`only contains binary values (either 0 or 1), and only one entry in `x` is 1, others are 0.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpMpBqxVFwwAQVh8ZAs:bz20ene)*

**Comment by soonho-tri** [comment]
Hi Hongkai,

Could you elaborate more? I don't think I understand the problem yet. I think I need a test case which fails with the current implementation.

> let W = diag(x),

W is a matrix of decision variables, what is the value of `W(i, j)` if `i != j`?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpMytKiey5qKShF3wIL:bez3kjy)*

**Comment by hongkai-dai** [comment]
I think I mean if `x` or `y` and `W` has a duplicated entry, and `e` contains that duplicated entry, we can run into problem. For example
```C++
MathematicalProgram prog;
auto x = prog.NewContinuousVariable<2>();
auto y = prog.NewContinuousVariable<2>();
MatrixDecisionVariable<2, 2> W;
W << x(0), x(1), y(0), y(1);  // W contains entries in x or y
symbolic::Expression  e = x(0) * y(0) + w(0, 0);
ReplaceBilinearTerms(e, x, y, W); //
```
If for the moment, we ignore why the user wants to treat `W` as the bilinear product of `x` and `y`, this code would run into problem when calling
```C++
poly.AddProduct(w_xy * p.second, symbolic::Monomial{});
```
since `w_xy` in this line is not treated as a indeterminate in this line. But when we construct `p_bilinear`, `w_xy` (i.e, x(0)) is treated as an indeterminate.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpNbIl0Mknf_LWRNXh7:b-n5w68i)*

**Comment by soonho-tri** [comment]
Now I understand the problem. Just updated the PR with a patch. PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpNtr1IVR6ybNLYLqV9:b-1e88hq)*

**Comment by hongkai-dai** [comment]
:lgtm: +@ggould-tri for platform review please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpO0vZwa_CCYOwz0ojp:b-9ir12m)*

**Comment by soonho-tri** [comment]
+@ericcousineau-tri for platform review please. (Grant will re-review it afterward)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpO1PRTFHJlZTBGbmfq:b-ratc7l)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: - thanks for the clarifying discussion!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpQHpz7LMBnWgneEvck:b-a7f2p8)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6598#-:-KpQbm6e7Uzdp-fZPlnF:bnfp4nl)*

**Pull request merged**
