### PR TITLE
[tutorials] Update advice for inertia debugging

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21479)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21479#-:-Nyv7gHk7NMvP2mtolrh:b-safpmt)* status: LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21479#-:-Nz4sQ2j5sJk9NqqgvDm:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for platform review, Monday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21479#-:-NzFJDU_1iAcNnxuYjAT:b-k8zoq2)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21479#-:-NzTR7QqEnW4KMVWnQKg:bcpz082)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),DamrongGuoy

**Pull request merged**
