### PR TITLE
Do not require OpenGL and Qt to use Eigen

### PR DESCRIPTION
**Pull request by jamiesnape**
See #general on Slack for more context. FYI @agalbachicar.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6015)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by soonho-tri** [comment]
This looks good to me (while there is a CI failure). I'm wondering if it's still the case that we need to update the required packages section or not.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6015#-:-KjEUrDl4hQPeCX-UpWh:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@soonho-tri 
platform :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6015#-:-KjEV91YfxTK5KFVkCMz:bexm2qz)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6015)*

**Comment by soonho-tri** [comment]
BTW, do we need to pass the same flags in bazel build, right?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6015#-:-KjEVG60VAshjRVTNzAZ:ba5ax9p)*

**Comment by jamiesnape** [comment]
BTW We do not glob any of the test files as far as I can tell, so probably not.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6015#-:-KjEVZ6jin9vIKBwRfn8:bv39tr6)*

**Pull request merged**
