### PR TITLE
Add generic conditional expression (cond)

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4122)

### CODE REVIEW

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJYJr6A-1dynlOF1C_:bupvv94) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
> ```cpp
> TEST_F(SymbolicExpressionTest, Cond2) {
>   // clang-format off
>   const Expression e{cond(x_ >= 10.0, Expression{10.0},
> ```

@jwnimmer-tri & @david-german-tri , do you know a way to avoid the use of `Expression{c}` here? Without it, it doesn't compile for now (even if there is non-explicit `Expression(double)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJYpCupDrBw3NZ_Hfy:b-365pqc) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> @jwnimmer-tri & @david-german-tri , do you know a way to avoid the use of `Expression{c}` here? Without it, it doesn't compile for now (even if there is non-explicit `Expression(double)`.
</details>
Yeah, we want to get ADL working.  I think `symbolic_expression.h` we want to get `cond` into the symbolic namespace.  How about `using drake::cond` within that header (in the symbolic namespace)?  Or else, writing out the forwarding function manually instead of `using` it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJZLJ_Wj9RbuofKNoo:b-b2z5up) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
> How about using drake::cond within that header (in the symbolic namespace)?

I will try this one first. Thanks for the quick reply!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJZtasjuRn6Lhi_juB:b-mad0yz) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> > How about using drake::cond within that header (in the symbolic namespace)?
> 
> I will try this one first. Thanks for the quick reply!!
</details>
No luck with adding `using drake::cond` in `symbolic_expression.h`. It generated the following error message:

```
/Users/soonhok/work/drake-distro/drake/../drake/common/cond.h:27:10: error: no viable conversion from returned value of type 'drake::symbolic::Expression' to function return type 'double'
  return if_then_else(f_cond, e_then, cond(rest...));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/soonhok/work/drake-distro/drake/common/test/symbolic_expression_test.cc:1158:22: note: in instantiation of function template specialization 'drake::cond<double, drake::symbolic::Formula, double>' requested here
  const Expression e{cond(x_ >= 10.0, 10.0, 0.0)};
```

So it first match the test code without `Expression{double}` with `double cond(Formula, double, double)`. The arguments parts are matched to `Expression` since we have `double -> Expression` conversion via implicit constructor. But the current return type of `cond` is `double` and this compiler complains that there is no way to convert `Expression -> double`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJcbJBddUkVaOnkJVd:brxtrsk) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
> writing out the forwarding function manually instead of using it?

Here, you meant to add `Expression cond(double)` and `Expression cond(Formula, double, ...)`, right? A possible issue with this direction is that there could be a collision between `double`'s `cond` -- `double cond(double)` and the provided one `Expression cond(double)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJdpnWnmo2RE2DlVoS:b-fv0mqe) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> > writing out the forwarding function manually instead of using it?
> 
> Here, you meant to add `Expression cond(double)` and `Expression cond(Formula, double, ...)`, right? A possible issue with this direction is that there could be a collision between `double`'s `cond` -- `double cond(double)` and the provided one `Expression cond(double)`.
</details>
```c++
template <typename ScalarType, typename BooleanType, typename... Rest>
ScalarType cond(const BooleanType& f_cond, const ScalarType& e_then,
                Rest... rest) {
  return if_then_else(f_cond, e_then, cond(rest...));
}
```

Possibly related-topic: I was thinking about omitting a template parameter `BooleanType` and using something like `std::result_of<std::less(ScalarType)>` (or something like that). I guess it might help solve this problem. But `FunctionalForm` doesn't provide `operator<` (nor `std::less`). So I didn't implement this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWJgvTLPoayCFzlvWWj:bzhou50) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> ```c++
> template <typename ScalarType, typename BooleanType, typename... Rest>
> ScalarType cond(const BooleanType& f_cond, const ScalarType& e_then,
>                 Rest... rest) {
>   return if_then_else(f_cond, e_then, cond(rest...));
> }
> ```
> 
> Possibly related-topic: I was thinking about omitting a template parameter `BooleanType` and using something like `std::result_of<std::less(ScalarType)>` (or something like that). I guess it might help solve this problem. But `FunctionalForm` doesn't provide `operator<` (nor `std::less`). So I didn't implement this way.
</details>
Hmm.. please ignore the previous comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
*[drake/common/test/symbolic_expression_test.cc, line 1169 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWJYJr6A-1dynlOF1CZ:-KWKEMMByQS30-lvJdV9:b-uv4ysb) ([raw file](https://github.com/robotlocomotion/drake/blob/4d872e6e489e6fe4502b4082cbe59ace6fb36ed7/drake/common/test/symbolic_expression_test.cc#L1169)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> Hmm.. please ignore the previous comment.
</details>
Done. (by adding `symbolic::Expression cond(const symbolic::Formula& f_cond, double v_then, Rest... rest)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , both reviews please.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-:-KWKEX-gyeYmjPkM0GtZ:b-mbs47t)*

**Comment by soonho-tri** [comment]
*[drake/common/cond.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWKEb-WjhdYG8SfNi8P:-KWKEb-WjhdYG8SfNi8Q:byxqqee) ([raw file](https://github.com/robotlocomotion/drake/blob/31f392de974fe5c8bde670b3d760d3d5c61c7fd5/drake/common/cond.h#L35)):*
> ```objc
> }
> template <typename ScalarType, typename... Rest>
> ScalarType cond(const decltype(ScalarType() < ScalarType()) & f_cond,
> ```

@jwnimmer-tri : FYI `cond` requires a `ScalarType` to have `operator<` and this rules out `FunctionalForm`. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWPvUxnbkz5idxQVLgF:-KWPvUxo754GjUG7yQvq:bpoqkk6) (no related file):*
BTW I think this is a fine increment as far as Symbolic goes, but I would still like to see `cond` and `if_then_else` added with unit tests for other scalar types (`double` and `AutoDiffXd`), before we move too far ahead.

---

*[drake/common/cond.h, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWKEb-WjhdYG8SfNi8P:-KWPu1uqQOqgyTAEouUO:bnskqlf) ([raw file](https://github.com/robotlocomotion/drake/blob/31f392de974fe5c8bde670b3d760d3d5c61c7fd5/drake/common/cond.h#L35)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> @jwnimmer-tri : FYI `cond` requires a `ScalarType` to have `operator<` and this rules out `FunctionalForm`. What do you think?
</details>
We can update it later if need be.  For now, I would find an appropriate place to put a TODO explaining that FunctionalForm doesn't yet support cond and ITE.

If we decide that we'd like it to support them, it should be fairly easy to do so, but I don't think its worth investing in now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-:-KWPvk1pT-O976qHGW7N:bnfp4nl)*

**Comment by soonho-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/4122#-KWPvUxnbkz5idxQVLgF:-KWPwlH1S7xW-bOoGgR0:b-4mid6y) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW I think this is a fine increment as far as Symbolic goes, but I would still like to see `cond` and `if_then_else` added with unit tests for other scalar types (`double` and `AutoDiffXd`), before we move too far ahead.
</details>
That's the next stop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4122)*

**Comment by jwnimmer-tri** [comment]
:bullettrain_front:

**Pull request merged**
