### PR TITLE
[meshcat] Add Meshcat::SetLine and Meshcat::SetLineSegments

### PR DESCRIPTION
**Pull request by RussTedrake**
Provides the API necessary to push line geometry to meshcat.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063#-:-MnxYus_7yns12lZm6w-:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

**Comment by RussTedrake** [comment]
among other things, this gives me beautiful, fast, and deepnote/colab compatible renders for the RRT examples in the course notes:
meshcat (2)
:

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: request a few comment updates

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063#-:-Mo-VLyMBJvDKZEIPuX1:b-76ej6m)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[geometry/meshcat.h, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-PPNUB8cvcjVdsiwj:-Mo-PPNVDHEJ2mo8_5hc:bi5vqxw) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L160)):*
> ```
> @param start
> ```
I think you meant `end` on this line?
___
*[geometry/meshcat.h, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-QHMv6cBEUq1sAvGZ:-Mo-QHMv6cBEUq1sAvG_:bhwbnq3) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L166)):*
> ```objc
>                     of the set value.
>   @param rgba is the line color. */
>   void SetLineSegments(std::string_view path,
> ```

nit Probably should document the precondition that start.cols() must equal end.cols().
___
*[geometry/meshcat.h, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-QWMq6gAagg9VT0qI:-Mo-QWMq6gAagg9VT0qJ:b68fxr7) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L168)):*
> ```objc
>   void SetLineSegments(std::string_view path,
>                const Eigen::Ref<const Eigen::Matrix3Xd>& start,
>                const Eigen::Ref<const Eigen::Matrix3Xd>& end,
> ```

BTW this commits even clients who have data in contiguous start-end pairs already to two pivots -- one to (starts, ends), and then back to construct the message. Maybe not necessary for this PR, but consider an alternative API that avoids the double-shuffle?
___
*[geometry/meshcat.cc, line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-Rl348DqB3Jh39yy2:-Mo-Rl348DqB3Jh39yy3:bgf2gqf) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.cc#L437)):*
> ```cpp
> };
> 
> int ToMeshcatColor(const Rgba& rgba) {
> ```

nit Maybe add a comment here noting that the meshcat color encoding discards alpha?

**Review by RussTedrake — COMMENTED** [review]
+@ggould-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063#-:-Mo-rMUn4zR3Be8Cml1a:bcav8r0)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

___
*[geometry/meshcat.h, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-PPNUB8cvcjVdsiwj:-Mo-aKZI3tJj9J70t_7p:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L160)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
> @param start
> ```
I think you meant `end` on this line?
</blockquote></details>

Done.
___
*[geometry/meshcat.h, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-QHMv6cBEUq1sAvGZ:-Mo-aRZZ7y9M5RVJAFVQ:b-47gp4a) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L166)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Probably should document the precondition that start.cols() must equal end.cols().
</blockquote></details>

Done.  Added the test, too.
___
*[geometry/meshcat.cc, line 437 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-Rl348DqB3Jh39yy2:-Mo-oz4BDVAL8VxZ42uM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.cc#L437)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Maybe add a comment here noting that the meshcat color encoding discards alpha?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Comment by RussTedrake** [comment]
___
*[geometry/meshcat.h, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo-QWMq6gAagg9VT0qI:-Mo0NjJV4GRjmcji148C:bssg67j) ([raw file](https://github.com/robotlocomotion/drake/blob/17ca2ad56974501bed82c36c3af8501c78a815fa/geometry/meshcat.h#L168)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW this commits even clients who have data in contiguous start-end pairs already to two pivots -- one to (starts, ends), and then back to construct the message. Maybe not necessary for this PR, but consider an alternative API that avoids the double-shuffle?
</blockquote></details>

Agreed.  (I thought about it, too.. but wanted to favor the more clear syntax).

**Review by ggould-tri — COMMENTED** [review]
:lgtm:
My regrets for the flurry of editorial nits below; none of them are of any great significance.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063#-:-Mo0OwfEBvaE2TxHWrpt:b-4dqy0d)* status: 8 unresolved discussions (waiting on @RussTedrake)

___
*[geometry/meshcat.h, line 151 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0On3l3vNYAQtVIpY_:-Mo0On3l3vNYAQtVIpYa:bsimnto) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.h#L151)):*
> ```objc
>                const Eigen::Ref<const Eigen::Matrix3Xd>& vertices,
>                double line_width = 1.0,
>                const Rgba& rgba = Rgba(.1, .1, .1, 1.));
> ```

nit:  The decimals here are hard on my old astigmatic eyes.  Consider making that last `1.` into `1.0` so it isn't just a sea of dots and lines?
(similarly four lines below)
___
*[geometry/meshcat.h, line 166 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0OroB3wfD8QzpAzVC:-Mo0OroB3wfD8QzpAzVD:b-klhfqk) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.h#L166)):*
> ```objc
>                     of the set value.
>   @param rgba is the line color.
>   
> ```

nit:  Trailing whitespace on this line.
___
*[geometry/meshcat.h, line 172 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0JUNjBGUnDbaQCPdP:-Mo0JUNjBGUnDbaQCPdQ:b-two7ad) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.h#L172)):*
> ```objc
>                const Eigen::Ref<const Eigen::Matrix3Xd>& end,
>                double line_width = 1.0,
>                const Rgba& rgba = Rgba(.1, .1, .1, 1.));
> ```

nit:  Whitespace doesn't look canonical ("each subsequent line aligned with the first argument" https://drake.mit.edu/styleguide/cppguide.html#Function_Calls )
___
*[geometry/meshcat.h, line 172 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0OoG46LEHJa5QKsnj:-Mo0OoG46LEHJa5QKsnk:b2ssxtm) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.h#L172)):*
> ```objc
>                const Eigen::Ref<const Eigen::Matrix3Xd>& end,
>                double line_width = 1.0,
>                const Rgba& rgba = Rgba(.1, .1, .1, 1.));
> ```

nit: Same plea for readability here as above.
___
*[geometry/meshcat.cc, line 439 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0Lh1c2i4teGFNp4AU:-Mo0Lh1c2i4teGFNp4AV:b-ocga8v) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.cc#L439)):*
> ```cpp
> int ToMeshcatColor(const Rgba& rgba) {
>   // Note: The returned color discards the alpha value, which is handled
>   // separately (e.g. by the opacity field in the material properties).
> ```

BTW:  I was going to ask for a link to the meshcat (or three) color specification format here, but... I can't find any.  Oh well.
___
*[geometry/meshcat.cc, line 654 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0MXGL0XMlFLn4QtFW:-Mo0MXGL0XMlFLn4QtFX:b-jtxw0a) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.cc#L654)):*
> ```cpp
>             "backpressure {}).  You will either need to reduce the size of "
>             "your object/mesh/textures, or modify the code to increase the "
>             "allowance.",
> ```

BTW:  This is an extremely good warning message; thank you.
___
*[geometry/meshcat.cc, line 755 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0MhXt4DJmK5AwFNe1:-Mo0MhXt4DJmK5AwFNe2:b-vru8q2) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.cc#L755)):*
> ```cpp
>       //  1) we want to avoid copying the big data nested structure,
>       //  2) this message type would require a nasty hairball of structs, and
>       //  3) the nested structures have path's inside that must be modified with
> ```

nit: typo "path's" -> "paths"
___
*[geometry/meshcat.cc, line 1324 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0LxWzB29QNYVJ-ySg:-Mo0LxWzB29QNYVJ-ySh:b-fy4jko) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/geometry/meshcat.cc#L1324)):*
> ```cpp
>                       const Eigen::Ref<const Eigen::Matrix3Xd>& start,
>                       const Eigen::Ref<const Eigen::Matrix3Xd>& end,
>                       double line_width, const Rgba& rgba) {
> ```

nit:  As above, the whitespace here is slightly noncanonical.
___
*[bindings/pydrake/geometry_py_visualizers.cc, line 213 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0NzG_DW16Qs4MXLSw:-Mo0NzG_DW16Qs4MXLSx:b-ihr4a4) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/bindings/pydrake/geometry_py_visualizers.cc#L213)):*
> ```cpp
>             py::arg("rgba") = Rgba(.9, .9, .9, 1.), cls_doc.SetObject.doc_cloud)
>         .def("SetLine", &Class::SetLine, py::arg("path"), py::arg("vertices"),
>             py::arg("line_width") = 1.0, py::arg("rgba") = Rgba(.1, .1, .1, 1.),
> ```

nit: same plea for readability here as above
___
*[bindings/pydrake/geometry_py_visualizers.cc, line 217 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16063#-Mo0Oixi9IADSDp_j16-:-Mo0Oixi9IADSDp_j160:byre294) ([raw file](https://github.com/robotlocomotion/drake/blob/0916384c0de9460d1ccda2b68ecbac19542f7e4c/bindings/pydrake/geometry_py_visualizers.cc#L217)):*
> ```cpp
>         .def("SetLineSegments", &Class::SetLineSegments, py::arg("path"),
>             py::arg("start"), py::arg("end"), py::arg("line_width") = 1.0,
>             py::arg("rgba") = Rgba(.1, .1, .1, 1.), cls_doc.SetLineSegments.doc)
> ```

nit:  same plea for readability here as above

**Comment by jwnimmer-tri** [comment]
FYI the floating-point literals actually _require_ using the zeros, for all of them (not just the alpha):
https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16063)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
