### PR TITLE
Refactoring QuadraticCost

### PR DESCRIPTION
**Pull request by naveenoid**
QuadraticCost refactored to QuadraticErrorCost and QuadraticProgramCost refactored to QuadraticCost. This resolves https://github.com/RobotLocomotion/drake/issues/2639

+@sherm1 : Platform
+@Lucy-tri  : Feature

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2651)

### CODE REVIEW

**Comment by naveenoid** [comment]
Ready for review..although mac build seems down.

**Comment by Lucy-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/NloptSolver.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHHIVJGzCHj9OMXz9B:-KLHHIVKjuocLQx5gHJJ:-1616180493) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/NloptSolver.cpp#L46)):*
> ```cpp
> // This function meets the signature requirements for nlopt::vfunc as
> // described in
> // http://ab-initio.mit.edu/wiki/index.php/NLopt_C-plus-plus_Reference#ObjectCostive_function
> ```

typo: should the web reference stay the same?  Would be nice to have a comment on terminology, that is, that "in NLopt the term objective function is used, where Drake uses the term cost" (is that correct?).

---

*[drake/solvers/SnoptSolver.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHIAuneVqzc1UWgnEy:-KLHIAuneVqzc1UWgnEz:-596440659) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/SnoptSolver.cpp#L18)):*
> ```cpp
> 
> 
> // todo:  implement sparsity inside each objective/constraint
> ```

Should this say cost instead of objective?

---

*[drake/solvers/SnoptSolver.cpp, line 192 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHIFVFpD4ZaYlbMMmf:-KLHIFVFpD4ZaYlbMMmg:-1434685789) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/SnoptSolver.cpp#L192)):*
> ```cpp
>   memset(G, 0, (*n) * sizeof(snopt::doublereal));
> 
>   // evaluate objective
> ```

Should this say cost instead of objective?  If so, probably should search for "objective" in entire file (e.g. comments).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651)*

**Comment by sherm1** [comment]
Platform: :lgtm:. Mac build failed but looks like a flake.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-:-KLKIfJXXbUh-DRzBesS:-1357733198)*

**Comment by naveenoid** [comment]
Yikes! I made a mess with a rebase attempt..will attempt to cleanup.

**Comment by naveenoid** [comment]
ok fixed..that was rather straightforward.

**Comment by naveenoid** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/SnoptSolver.cpp, line 18 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHIAuneVqzc1UWgnEy:-KLLE7LIFQINY2FyGRn1:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/SnoptSolver.cpp#L18)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Should this say cost instead of objective?
</details>
Done.

---

*[drake/solvers/SnoptSolver.cpp, line 192 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHIFVFpD4ZaYlbMMmf:-KLLE8TqDDFzSrt-O-Tv:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/SnoptSolver.cpp#L192)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> Should this say cost instead of objective?  If so, probably should search for "objective" in entire file (e.g. comments).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651)*

**Comment by naveenoid** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/NloptSolver.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-KLHHIVJGzCHj9OMXz9B:-KLLQVOKqQKVPpreOXzJ:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/f23497c3c344e8cd2d65f1f3373140b87eae1671/drake/solvers/NloptSolver.cpp#L46)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> typo: should the web reference stay the same?  Would be nice to have a comment on terminology, that is, that "in NLopt the term objective function is used, where Drake uses the term cost" (is that correct?).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 37 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-:-KLMJVbnylj-WIk8rukY:1417088721)*

**Comment by naveenoid** [comment]
Solves https://github.com/RobotLocomotion/drake/issues/2652

**Comment by Lucy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2651#-:-KLMzIaeJBhcrHQ3IoPd:1417088721)*

**Comment by sherm1** [comment]
The Win32 build problem here is unrelated to this PR and was fixed by #2679 so I'm force-merging this.

**Pull request merged**
