### PR TITLE
add bindings to mathematical program for SOS calls, …

### PR DESCRIPTION
**Pull request by RussTedrake**
and add new entry points for Frank's monomial basis work

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8242)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@frankpermenter for feature review, please.
cc @soonho-tri 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6mLvCoeacEADb2QPRv:bj6wtwd)*

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, too

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6mOj0lPepURNlKZODL:b10spof)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[solvers/mathematical_program.h, line 608 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mTl1UnkvdZYbZ2kwt:-L6mTl1UnkvdZYbZ2kwu:b-yv5ll) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L608)):*
> ```objc
> 
> 
>   /** Returns a pair of a SOS polynomial p = mᵀQm of degree @p degree and a PSD
> ```

`degree` is not used in this function, consider to remove it? We should also mention that `m` in `mᵀQm` is `@p monomial_basis`.

---

*[solvers/mathematical_program.h, line 613 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mTTmQ5IjJQdHLcvI8:-L6mTTmQ5IjJQdHLcvI9:b-sa5q5m) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L613)):*
> ```objc
>    * polynomial
>    *   p = Q₍₀,₀₎x² + 2Q₍₁,₀₎xy + Q₍₂,₂₎y²
>    * and a PSD constraint over Q.
> ```

BTW, also mention that `Q` is symmetric? And mention that `Q` is of size `monomial_basis.rows() x monomial_basis.rows()`.

---

*[solvers/mathematical_program.h, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mUNHKjSPpKkh3Fnlk:-L6mUNHKjSPpKkh3Fnll:baw6xx7) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L621)):*
> ```objc
>   /** Returns a pair of a SOS polynomial p = m(x)ᵀQm(x) of degree @p degree
>    * and a PSD constraint for the coefficients matrix Q, where m(x) is a
>    * monomial basis over @p indeterminates, x, of degree `@p degree / 2`. For
> ```

of degree <b> no larger than </b>`@p degree / 2`? Otherwise I might think that the monomial basis contains monomials of degree exactly as `@p degree / 2`.

BTW, also mention that the number of rows in `Q` is nchoosek(degree / 2 + indeterminates.size() - 1, indeterminates.size())?

---

*[solvers/mathematical_program.h, line 1931 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mW5Ptso8QLpI2OCah:-L6mW5Ptso8QLpI2OCai:b-okxeqo) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1931)):*
> ```objc
>   /**
>    * Adds constraints that a given polynomial @p p is a sums-of-squares (SOS),
>    * that is, @p p can be decomposed into `mᵀQxm`. It returns a pair of
> ```

BTW, mention that `m` is @p monomial_basis?

---

*[solvers/mathematical_program.h, line 1945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mWkhoBPBahq6hjrl4:-L6mWkhoBPBahq6hjrl5:b9tzpyk) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1945)):*
> ```objc
>    * Adds constraints that a given polynomial @p p is a sums-of-squares (SOS),
>    * that is, @p p can be decomposed into `mᵀQm`, where m is the monomial
>    * basis of all indeterminates in the program with degree equal to the
> ```

I think the `m` is the monomial basis of all intederminates in the program with degree less than or equal to half of the TotalDegree of @p p?

---

*[solvers/mathematical_program.h, line 1956 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mWzhrCWSVqm8MWjv9:-L6mWzhrCWSVqm8MWjvA:bnro1nb) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1956)):*
> ```objc
>   /**
>    * Adds constraints that a given symbolic expression @p e is a
>    * sums-of-squares (SOS), that is, @p p can be decomposed into `mᵀQxm`.
> ```

`mᵀQxm` -> `mᵀQm`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242)*

**Comment by RussTedrake** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[solvers/mathematical_program.h, line 608 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mTl1UnkvdZYbZ2kwt:-L6moDhGhCxDkUvo7Y8F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L608)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`degree` is not used in this function, consider to remove it? We should also mention that `m` in `mᵀQm` is `@p monomial_basis`.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 613 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mTTmQ5IjJQdHLcvI8:-L6mvQoSl6SvIiWORtK9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L613)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, also mention that `Q` is symmetric? And mention that `Q` is of size `monomial_basis.rows() x monomial_basis.rows()`.
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mUNHKjSPpKkh3Fnlk:-L6mvzNX4kFdcqFHfx6r:b9o0j8x) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L621)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

of degree <b> no larger than </b>`@p degree / 2`? Otherwise I might think that the monomial basis contains monomials of degree exactly as `@p degree / 2`.

BTW, also mention that the number of rows in `Q` is nchoosek(degree / 2 + indeterminates.size() - 1, indeterminates.size())?
</blockquote></details>

I think that it does contain exactly those?  (that was the existing code).    
Instead of listing the nchoosek, I've referenced MonomialBasis.

---

*[solvers/mathematical_program.h, line 1931 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mW5Ptso8QLpI2OCah:-L6mwwn5rRyL8N8MEqAb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1931)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, mention that `m` is @p monomial_basis?
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 1945 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mWkhoBPBahq6hjrl4:-L6mx7UgPtuGA19eCBu0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1945)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the `m` is the monomial basis of all intederminates in the program with degree less than or equal to half of the TotalDegree of @p p?
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 1956 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mWzhrCWSVqm8MWjv9:-L6mxK5mXpdZMdxFYXhG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1956)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`mᵀQxm` -> `mᵀQm`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[solvers/mathematical_program.h, line 621 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mUNHKjSPpKkh3Fnlk:-L6mzQz_Suh5rcSOwNen:bv2epa4) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L621)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think that it does contain exactly those?  (that was the existing code).    
Instead of listing the nchoosek, I've referenced MonomialBasis.
</blockquote></details>

I think `MonomialBasis(indeterminates, degree/2)` returns all the monomials , with degree <b> no larger than </b> `degree / 2`. The previous document says the monomial basis is of degree `degree / 2`. The current documentation looks good.

---

*[solvers/mathematical_program.h, line 1931 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mW5Ptso8QLpI2OCah:-L6mypsiCrSGsF5EGbG5:biyfh2y) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1931)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTWm `mᵀQxm` -> `mᵀQm`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6n1Qf1UNLusqY2uOOo:bnfp4nl)*

**Comment by RussTedrake** [comment]
+@soonho-tri for platform review.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[solvers/mathematical_program.h, line 1931 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6mW5Ptso8QLpI2OCah:-L6nGjgg_hgwapBbAmEw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5edc34803a2b9bf7f31b703599182a552a0cb068/solvers/mathematical_program.h#L1931)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTWm `mᵀQxm` -> `mᵀQm`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6nFXMW8Y3RrfUPUV6b:bxw8cpy)*

**Comment by RussTedrake** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 222 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6nHTW_EGlIZg2rd0H6:-L6nHTW_EGlIZg2rd0H7:bjhit6m) ([raw file](https://github.com/robotlocomotion/drake/blob/499f022dbfb41634c5c60b0635e9bb01c8fc44c6/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L222)):*
> ```Python
>         prog.AddSosConstraint(d[0]*x.dot(x))
>         prog.AddSosConstraint(d[1]*x.dot(x), [sym.Monomial(x[0])])
>         result = prog.Solve()
> ```

@soonho-tri -- I'm particularly interested in whether I need all of the explicit Monomial/Variables casts in the lines above.  Perhaps there is some sugar that I missed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 222 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-L6nHTW_EGlIZg2rd0H6:-L6qeHe834uQCp-r6LyR:b-owqy9d) ([raw file](https://github.com/robotlocomotion/drake/blob/499f022dbfb41634c5c60b0635e9bb01c8fc44c6/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L222)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@soonho-tri -- I'm particularly interested in whether I need all of the explicit Monomial/Variables casts in the lines above.  Perhaps there is some sugar that I missed?
</blockquote></details>

Something like `py::implicitly_convertible<drake::symbolic::Variable, drake::symbolic::Monomial>();` might do the magic. I'll check and open a PR if that works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6qeS3hVkYI5GOwTv6l:bnfp4nl)*

**Comment by RussTedrake** [comment]
-@frankpermenter for feature

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8242#-:-L6rVpWgNp_ipkpbqTqt:bcb4c5p)*

**Pull request merged**
