### PR TITLE
Enable -Werror when using gcc

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is one portion of #1936.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2353) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The licensed-software bug #1964 bites again in my jenkins failure on 537ca7f.  Even though the file with an error doesn't need snopt to compile (only to pass its test), it isn't compiled by default, so is easy to overlook when making cross-cutting changes to Drake.

**Comment by jwnimmer-tri** [comment]
+@jamiesnape please for feature review (or delegate within kitware is OK too).
+@sherm1 please for platform review.

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The licensed-software bug #1964 bites again in my jenkins failure on 537ca7f.  Even though the file with an error doesn't need snopt to compile (only to pass its test), it isn't compiled by default, so is easy to overlook when making cross-cutting changes to Drake.</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2353#-:-KHh323ogJPwxtKTUla6:1524746416)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> +@jamiesnape please for feature review (or delegate within kitware is OK too).
> +@sherm1 please for platform review.
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2353#-:-KHq-Xy8BwlMhm_BDiIY:1058782226)*

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Platform review: :lgtm:</details>


---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2353#-:-KHtkCBXPmFMXI6t7u_C:1417088721)*

**Pull request merged**
