### PR TITLE
[multibody] Add `MultibodyPlant::GetEffortLowerLimits` (and friends)

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
feature :lgtm: after some requested tests are added. +@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835#-:-MynGKae-q6Phb7OlXPO:bq90vnc)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri and @RussTedrake)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)* status: 8 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

___
*[multibody/tree/multibody_tree.cc, line 3169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynLFiL2NvnQsbxr8mO:-MynLFiL2NvnQsbxr8mP:b8yiu8o) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3169)):*
> ```cpp
>   DRAKE_MBT_THROW_IF_NOT_FINALIZED();
>   Eigen::VectorXd lower = Eigen::VectorXd::Constant(
>       num_actuators(), -std::numeric_limits<double>::infinity());
> ```

Perhaps I am missing something here. Does not this sizing of the vector assume that num_inputs()==1 for all actuators?



_Code quote:_
```cpp
num_actuators(),
```
___
*[multibody/tree/multibody_tree.cc, line 3174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynPlYy-ks7YLQl0JUY:-MynPlYy-ks7YLQl0JUZ:bhtnrn9) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3174)):*
> ```cpp
>     for (int j = actuator.input_start();
>          j < actuator.input_start() + actuator.num_inputs(); ++j) {
>       lower[j] = -actuator.effort_limit();
> ```

Perhaps we should at least have DRAKE_ASSERT(j < num_actuators()) ?
___
*[multibody/tree/multibody_tree.cc, line 3184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynQDpx1C-b-_F9nOk_:-MynQDpx1C-b-_F9nOka:bs31ai0) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3184)):*
> ```cpp
>   DRAKE_MBT_THROW_IF_NOT_FINALIZED();
>   Eigen::VectorXd upper = Eigen::VectorXd::Constant(
>       num_actuators(), std::numeric_limits<double>::infinity());
> ```

ditto above -- this vector size is at best confusing, and at worst an invitation to UB.
___
*[multibody/tree/test/joint_actuator_test.cc, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynQllg8M-oOnmAAUTh:-MynQllhAjHyAobtSnsQ:b-6hl5co) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/test/joint_actuator_test.cc#L74)):*
> ```cpp
> 
>   EXPECT_EQ(actuator1.input_start(), 0);
>   EXPECT_EQ(actuator1.num_inputs(), 1);
> ```

nit consider a test with non-trivial values of input_start() and num_inputs().

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)* status: 6 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16835#-Myn6h8G2fdk5JWzTAH4:-Myqk3Bp6MOTHN_YpxRi:b1x14o3) (no related file):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

The tests are missing coverage for `GetEffortLowerLimits()` and `GetEffortUpperLimits()` for both MbP and MbT. Even just a small smoke test for now should be fine.
</blockquote></details>

smoke tests added.

---
___
*[multibody/tree/joint_actuator.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-Myn8ACD45LCO-ctBWsE:-MyqfTHDDN-ChAIk76AT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/joint_actuator.cc#L63)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Ditto for specificity.
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 3169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynLFiL2NvnQsbxr8mO:-Myqg3xC52n0PaB6cmvn:b-49rsq) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3169)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Perhaps I am missing something here. Does not this sizing of the vector assume that num_inputs()==1 for all actuators?
</blockquote></details>

Done.  Good catch.  (though I do think that assumption is currently implicit in various parts of the MBP code).
___
*[multibody/tree/multibody_tree.cc, line 3174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynPlYy-ks7YLQl0JUY:-MyqgMdVEhqmSGJizfkM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3174)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Perhaps we should at least have DRAKE_ASSERT(j < num_actuators()) ?
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 3184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynQDpx1C-b-_F9nOk_:-MyqgNP6EMk2ouJPIUs2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3184)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

ditto above -- this vector size is at best confusing, and at worst an invitation to UB.
</blockquote></details>

Done.
___
*[multibody/tree/test/joint_actuator_test.cc, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynQllg8M-oOnmAAUTh:-MyqgQwRA21KFwrIwYPS:b-s9necj) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/test/joint_actuator_test.cc#L74)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit consider a test with non-trivial values of input_start() and num_inputs().
</blockquote></details>

Done.  (I didn't actually know we could do multi-joint actuators here).

Note: It's a little strange that the actuators which throw an exception in the existing tests are still added to the topology. But my code only documents the existing situation (it certainly doesn't make it worse).

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn and @RussTedrake)

___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 966 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MyoOIEQ3gq0db0n5T7K:-MyqniQ5B5e12QrJh9Rb:b549rv2) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/parsing/test/detail_sdf_parser_test.cc#L966)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@joemasterjohn -- this is where I had added the smoke test (since there was an absolute lack of tests / test infra in `multibody_tree_test.cc`).  Is it sufficient?
</blockquote></details>

I wasn't wild about these, but I know the difficulties of writing good tests against multibody/tree/plant are many. I guess we do what we need for now, and try to organize a longer campaign to improve the multibody test situation. Happy with what you and Joe decide for these lines.
___
*[multibody/tree/multibody_tree.cc, line 3174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynPlYy-ks7YLQl0JUY:-MyqmUnl3Mr04S3xQWI5:b-jqzsab) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3174)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for the update. Should I worry enough to file an issue about finding and purging the num_inputs()==1 assumption?

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16835)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform) (waiting on @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16835#-Myn6h8G2fdk5JWzTAH4:-MyroEf66BzLANGbSTm6:b-ucfknh) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

smoke tests added.
</blockquote></details>

Thanks!

---
___
*[multibody/parsing/test/detail_sdf_parser_test.cc, line 966 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MyoOIEQ3gq0db0n5T7K:-MyroVT-9YuR-4Z_VUEl:b-xqukr4) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/parsing/test/detail_sdf_parser_test.cc#L966)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I wasn't wild about these, but I know the difficulties of writing good tests against multibody/tree/plant are many. I guess we do what we need for now, and try to organize a longer campaign to improve the multibody test situation. Happy with what you and Joe decide for these lines.
</blockquote></details>

Thanks for adding the smoke tests to the plant test. That covers everything I was concerned about, thanks!

**Comment by RussTedrake** [comment]
___
*[multibody/tree/multibody_tree.cc, line 3174 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16835#-MynPlYy-ks7YLQl0JUY:-MytOCBl5-MpXFI-2_jw:b-8qzoki) ([raw file](https://github.com/robotlocomotion/drake/blob/c4a4e4243f31a3c5a60af6e5d7c399ea2bc4e011/multibody/tree/multibody_tree.cc#L3174)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Thanks for the update. Should I worry enough to file an issue about finding and purging the num_inputs()==1 assumption?
</blockquote></details>

I had a casual conversation about it f2f today w/ @amcastro-tri and @joemasterjohn .  I think the consensus is that it would be good to do, but that nobody is waiting on it right now.  A low priority/backlog issue sounds reasonable to me -- i'll leave it up to you.  Thanks.

**Comment by RussTedrake** [comment]
My understanding is that @rpoyner-tri intended to LGTM.  So I am going to go ahead and merge.

**Pull request merged**
