### PR TITLE
Revert "Spatial velocity and acceleration ports"

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Reverts RobotLocomotion/drake#13364.

Dear @amcastro-tri,

The stand-in build cop (me) believes that your PR #13364 may have broken one or more of Drake's continuous integration builds [1]. It is possible to break a build even if your PR passed continuous integration pre-merge because additional platforms are tested post-merge.

The specific build failures under investigation are:
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-everything-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-weekly-gurobi-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-weekly-mosek-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-weekly-snopt-undefined-behavior-sanitizer/

Therefore, the build cop has created this revert PR and started a complete post-merge build to determine whether your PR was in fact the cause of the problem. If that build passes, this revert PR will be merged 60 minutes from now. You can then fix the problem at your leisure, and send a new PR to reinstate your change.

If you believe your original PR did not actually break the build, please explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be reverted, please review and LGTM this PR. This allows the build cop to merge without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly On-call Build Cop

[1] CI Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Production/
[2] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13399)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I'm not 100% certain this PR was at fault.  We'll let Jenkins decide:

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-undefined-behavior-sanitizer please

**Comment by jwnimmer-tri** [comment]
Yup, it seems like that was the culprit.

**Comment by jwnimmer-tri** [comment]
:lgtm: rubber stamp on pure revert.

**Comment by sherm1** [comment]
@amcastro-tri I see:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/stl_vector.h:798:9: runtime error: reference binding to null pointer of type 'Eigen::Matrix<double, 6, 1, 0, 6, 1>'
//multibody/plant:multibody_plant_tamsi_test                             FAILED in 1.7s
```

**Pull request merged**
