### PR TITLE
Initializing coulomb_window to epsilon

### PR DESCRIPTION
**Pull request by m-chaturvedi**
[Failure](https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=141746)

Same reason as https://github.com/RobotLocomotion/drake/pull/6539

[Before the change](https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=713744)

[After the change](https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=714192)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6669)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6669#-:-KpziLMeDNsji4aHsTXs:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Note that `linux-xenial-clang-experimental-memcheck-ubsan` is not a required build and it has been run to make sure that we're indeed reducing the number of defects by this PR.

+@liangfok for additional feature review, please

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6669#-:-KpzuXWZ3CFubLG6sEl-:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6669#-:-KpzvuqA47tIsxkBkCmO:bnfp4nl)*

**Pull request merged**
