### PR TITLE
Warn about the memory issue when solving a QP with CLP

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14934)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14934#-:-MYpUG-Y4b1UyvQeyCrK:ba7uda8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14934#-:-MYp_Pvq38H6kVwkj314:b-b5dc06)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
Needs a lint brush.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14934)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Pull request merged**
