### PR TITLE
Remove Bionic wheel(s)

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove Bionic from the set of wheel targets, and move the Python 3.8 wheel to Focal. Switch to distro-provided CMake. Remove Bionic package list. Change default Docker images to Focal.

+@jwnimmer-tri for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

Once the issue below is resolved and the Wheel CI has passed, ping me and I'll pull this locally for extra manual testing, to be sure it's solid.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929#-:-N-OzTJ10OnoQq_C5BLO:b-srr4zx)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/image/packages-focal, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-Oz69jDdGtw-hOPWgC:-N-Oz69jDdGtw-hOPWgD:b-eodrpm) ([raw file](https://github.com/robotlocomotion/drake/blob/70da94aaedf0f4179fcb7a6f4b20a3352022ee62/tools/wheel/image/packages-focal#L18)):*
> ```
> clang-format-9
> # Other code tools.
> cmake
> ```

The `provision-base.sh` has an `# Install CMake ...` stanza that seems like it should be removed now?

**Comment by mwoehlke-kitware** [comment]
*[tools/wheel/image/packages-focal, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-Oz69jDdGtw-hOPWgC:-N-P93KBDvmEZd4PvJ8r:b-hvlajk) ([raw file](https://github.com/robotlocomotion/drake/blob/70da94aaedf0f4179fcb7a6f4b20a3352022ee62/tools/wheel/image/packages-focal#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `provision-base.sh` has an `# Install CMake ...` stanza that seems like it should be removed now?
</blockquote></details>

Ack, I thought that *was* in the commit :flushed:. Should be fixed now.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware)

___
*[tools/wheel/test/test-wheel.sh, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-PEOmJ3wQZxcbNDVrh:-N-PEOmJ3wQZxcbNDVri:b4cbwu2) ([raw file](https://github.com/robotlocomotion/drake/blob/1f31b616f826b72ac8d0759ae654303ebcf420b3/tools/wheel/test/test-wheel.sh#L19)):*
> ```Shell
> . /opt/python/bin/activate
> 
> pip install --upgrade pip
> ```

nit Did you still want to remove this line?  It came back in the last push.

**Comment by mwoehlke-kitware** [comment]
*[tools/wheel/test/test-wheel.sh, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-PEOmJ3wQZxcbNDVrh:-N-PSD6G0rdOZ7mXgJiD:bi1cu5b) ([raw file](https://github.com/robotlocomotion/drake/blob/1f31b616f826b72ac8d0759ae654303ebcf420b3/tools/wheel/test/test-wheel.sh#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Did you still want to remove this line?  It came back in the last push.
</blockquote></details>

Yes; it turns out Focal still needs it :cry:. (Note the change also in the commit message and PR description.)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-PhwniCadpG1UZiFJF:-N-PhwniCadpG1UZiFJG:bkhjbr2) (no related file):*
Working

CI wheel build has passed.  I'll test this locally tomorrow.

---

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@rpoyner-tri for platform review (and release manager eyeball), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929#-:-N-Pt8ox39SEOR2Y-VAP:b-edv415)* status: LGTM missing from assignee rpoyner-tri(platform), missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16929#-N-PhwniCadpG1UZiFJF:-N-Pt6yj1-6ULZQHXk1V:b-ncc1si) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

CI wheel build has passed.  I'll test this locally tomorrow.
</blockquote></details>

OK Seems fine.

---

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929#-:-N-TJq948UKu3rM50p9Z:bnfp4nl)* status: missing label for release notes (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929)* status: missing label for release notes (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: removal of deprecated)  ?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16929#-:-N-TK6kKEtoVmL2vtcaO:b-t3n0lq)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
