### PR TITLE
Add code review checklist document

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This was collaboratively written by several TRI developers offline.  It's stabilized a bit now, so we're going to curate it in the git tree from now on.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3055)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@ggould-tri for feature review
@sammy-tri for platform review

/CC other platform reviewers @david-german-tri  @psiorx @sherm1 @RussTedrake; you can self-assign yourself for review if you'd like to wait until you've read it for this to merge.

**Comment by liangfok** [comment]
Done with quick skim.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOITxATuJWWxlJAp84_:-KOITxATuJWWxlJAp84a:42063116) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L15)):*
> ```reStructuredText
> ===================================
> 
> - If your code doesn’t pass Jenkins, why are you asking for a detailed code review?
> ```

BTW: nit: that apostrophe in "doesn't" doesn't look normal.

---

*[drake/doc/code_review_checklist.rst, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIU4qG62oLjmDZ4kXv:-KOITwSAwVs8ZBFagLre:1322518477) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L16)):*
> ```reStructuredText
> 
> - If your code doesn’t pass Jenkins, why are you asking for a detailed code review?
> - Did you remember to add all new headers to the list of installed files?
> ```

BTW consider clarifying that this is referring to the `CMakeLists.txt` in the same directory has the header file.

---

*[drake/doc/code_review_checklist.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIULfpildqjP7dIFTx:-KOIULfpildqjP7dIFTy:-1199502855) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L31)):*
> ```reStructuredText
> 
>   - As you update your PR based on review feedback, review your commit
>     diffs before pushing them -- don’t leave it to the the reviewers
> ```

extra "the"
missing "to" after "reviewers"
strange apostrophe in "don't"

---

*[drake/doc/code_review_checklist.rst, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIUVRllp8oCgzikslV:-KOIUVRllp8oCgzikslW:325559856) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L35)):*
> ```reStructuredText
> 
> - Remove commented-out code.
> - Remove code that isn’t part of the build, or doesn’t have unit tests.
> ```

BTW strange apostrophe in "isn't" and "doesn't".

---

*[drake/doc/code_review_checklist.rst, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIU_NBNLHdnL5N4EVt:-KOIU_NBNLHdnL5N4EVu:874212823) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L37)):*
> ```reStructuredText
> - Remove code that isn’t part of the build, or doesn’t have unit tests.
> - Don’t include files with only whitespace diffs in your PR.
> ```

BTW strange apostrophe in "Don't"

Should we clarify that the exception to this rule is if the entire PR is just white space diffs for style guide conformance?

---

*[drake/doc/code_review_checklist.rst, line 58 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIV7aiumwryTyIxM0N:-KOIV7aiumwryTyIxM0O:2082216709) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L58)):*
> ```reStructuredText
>   use cases.
> - Bare pointers are a common source of mistakes; if you see one,
>   consider if it is what you want (eg, this is a mutable
> ```

"eg" →  "e.g."

---

*[drake/doc/code_review_checklist.rst, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIVEMiYcoEsfK_5nYQ:-KOIVEMiYcoEsfK_5nYR:-1304257116) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L60)):*
> ```reStructuredText
>   consider if it is what you want (eg, this is a mutable
>   pass-by-reference) and if so ensure that any nontrivial lifetime
>   guarantee is documented and you checked for ``nullptr``.
> ```

Instead of checking for `nullptr`, how about recommending that people use  `DRAKE_ABORT_UNLESS()` with a Doxygen comment saying "this pointer shall not be nullptr"?

---

*[drake/doc/code_review_checklist.rst, line 96 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIVlxQ5AQAb9Cx28GW:-KOIVlxRmU9TzV-yqg0r:996044841) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L96)):*
> ```reStructuredText
>     citing "in-class member initialization".
> 
> Did you use a C-style cast by accident?
> ```

BTW we should probably add a section entitled "Did you use a C-style #include by accident?".

---

*[drake/doc/code_review_checklist.rst, line 110 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIVx0ONITJKFWceW1h:-KOIVx0ONITJKFWceW1i:-783535359) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L110)):*
> ```reStructuredText
> 
> - Run ``drake-distro/drake/common/test/cpplint_wrapper.py`` to catch
>   several common errors.
> ```

BTW consider adding a sentence saying `cpplint_wrapper.py` can be run from _any_ directory and will work as expected.

---

*[drake/doc/developers.rst, line 123 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIWDU3UxO9New-MEPP:-KOIWDU3UxO9New-MEPQ:-821078472) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/developers.rst#L123)):*
> ```reStructuredText
> Before your submit a pull request, please consult the
> :ref:`Code Review Checklist <code-review-checklist>`,
> where a list of the most frequent problems are collected.
> ```

BTW, consider replacing "collected" with "listed".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOIWJUcws-wAZ7S7C7Z:8016574)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOITxATuJWWxlJAp84_:-KOKMDGBQ8qIz_Uxsm79:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L15)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: that apostrophe in "doesn't" doesn't look normal.
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIU4qG62oLjmDZ4kXv:-KOKNJQqwGE625XWPkiG:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW consider clarifying that this is referring to the `CMakeLists.txt` in the same directory has the header file.
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIULfpildqjP7dIFTx:-KOKMI6_OW-wQ1Ukhgf7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L31)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> extra "the"
> missing "to" after "reviewers"
> strange apostrophe in "don't"
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 35 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIUVRllp8oCgzikslV:-KOKMJ8rphBp4AWDJtOI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L35)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW strange apostrophe in "isn't" and "doesn't".
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 37 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIU_NBNLHdnL5N4EVt:-KOKMYuKjw1Ovvqd_dt-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L37)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW strange apostrophe in "Don't"
> 
> Should we clarify that the exception to this rule is if the entire PR is just white space diffs for style guide conformance?
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 58 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIV7aiumwryTyIxM0N:-KOKMayXIgPaHR4wW9BL:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L58)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "eg" →  "e.g."
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 60 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOIVEMiYcoEsfK_5nYQ:-KOKMrd6TEeTPxvafwHA:-1492342490) ([raw file](https://github.com/robotlocomotion/drake/blob/c7b2476edc5241f9536afe2c4ff9613d6f3d81c9/drake/doc/code_review_checklist.rst#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Instead of checking for `nullptr`, how about recommending that people use  `DRAKE_ABORT_UNLESS()` with a Doxygen comment saying "this pointer shall not be nullptr"?
</details>
If we fine that confusion here is a common problem, we can then amend this document to be more verbose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOKPQTOu26PFSOyLfAx:1417088721)*

**Comment by ggould-tri** [comment]
Unsurprisingly :lgtm: as I wrote much of the text :)
One nit noted below.
I assume you have generated and viewed html from the rst?  Some of the whitespace seems suspicious to me but I will trust it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/code_review_checklist.rst, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOKZCE4V5ji8zOSLLpq:-KOKZCE4V5ji8zOSLLpr:1675130490) ([raw file](https://github.com/robotlocomotion/drake/blob/c444a8072e9083d17af5bc58667f15cab0ebac2e/drake/doc/code_review_checklist.rst#L15)):*
> ```reStructuredText
> ===================================
> 
> - If your code doesn't pass Jenkins, why are you asking for a detailed code review?
> ```

FYI -- Long line; please wrap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOK_pc3CUWWrg7tF4Ne:-835276615)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/doc/code_review_checklist.rst, line 15 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOKZCE4V5ji8zOSLLpq:-KOKc7MQUl0MeJbzm7f7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/c444a8072e9083d17af5bc58667f15cab0ebac2e/drake/doc/code_review_checklist.rst#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- Long line; please wrap.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by jwnimmer-tri** [comment]
> I assume you have generated and viewed html from the rst?  Some of the whitespace seems suspicious to me but I will trust it.

Yup, I did originally, and just reconfirmed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOKcPuH2tZvYmRfrisD:-1458080605)*

**Comment by jhoare** [comment]
Perhaps alongside this, you'd like to create a ``CONTRIBUTING.md`` file into the root of the repository.

See: https://github.com/blog/1184-contributing-guidelines

**Comment by sherm1** [comment]
A few mods/additions (in non-blocking comments). Otherwise :lgtm:.

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[drake/doc/code_review_checklist.rst, line 34 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLAldM4tM90BIFcfmm:-KOLAldM4tM90BIFcfmn:-1281814472) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L34)):*
> ```reStructuredText
>   - As you update your PR based on review feedback, review your commit
>     diffs before pushing them -- don't leave it to the reviewers to
>     discover your careless typos.
> ```

BTW, delete "careless" (seems unfriendly and typos do happen at times even with care).

---

*[drake/doc/code_review_checklist.rst, line 50 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLBBUg0OgMsIvl01v_:-KOLBBUhdL_eIeOLyuqC:-1376022590) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L50)):*
> ```reStructuredText
> - Arguments are ``lowercase_style`` and nouns, and are single-letter only
>   when they have a clear and documented meaning.  Yes, this includes
>   single greek letters!
> ```

I'm not sure what you mean here. Greek letters aren't valid variable names are they? Or do you mean you don't want to see spelled-out Greek variable names like `lambda` and `theta`?

---

*[drake/doc/code_review_checklist.rst, line 52 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLDSWX0XPRGi9sXUGN:-KOLDSWYaS--84Dm-PRa:-1994757032) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L52)):*
> ```reStructuredText
>   single greek letters!
> - Member fields are ``lowercase_style_with_trailing_underscore_``.
> ```

Add (somewhere):
```
Have you considered copy and move constructors and assignment?
- If your class shouldn't be copied, moved, or assigned did you delete the compiler-generated methods to do so (using ``=delete``).
- Hand written copy, move, and assignment are error prone. If you had to write your own consider how you could redesign to allow the compiler to do it.
```

---

*[drake/doc/code_review_checklist.rst, line 121 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLCK7FRmi7hLQpW_VQ:-KOLCK7FRmi7hLQpW_VR:-938106849) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L121)):*
> ```reStructuredText
>   You can use ``libstdc++``'s new random generators, as long as you
>   call them using a local instance (no global state), and seed it with
>   a hard-coded value.
> ```

BTW, "... with a hard-coded value *for repeatability*." Also mention that this applies to test cases. Consider heading "Is your *test* code deterministic?" since that is where the urge to use random numbers is strong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOLEb3jx7iyxwb2DVQP:-1631433012)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/code_review_checklist.rst, line 50 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLBBUg0OgMsIvl01v_:-KOLQ260UwPpDoAdIT10:-2121921807) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm not sure what you mean here. Greek letters aren't valid variable names are they? Or do you mean you don't want to see spelled-out Greek variable names like `lambda` and `theta`?
</details>
The intent when I wrote it was that "theta" is just as much a one-letter variable name as "x"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-:-KOLSg72d2duH8eiUu4O:1417088721)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 34 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLAldM4tM90BIFcfmm:-KOe7HTeoc_qsveGQofD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, delete "careless" (seems unfriendly and typos do happen at times even with care).
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 50 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLBBUg0OgMsIvl01v_:-KOe82bT_cJ71K-0aLSP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L50)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> The intent when I wrote it was that "theta" is just as much a one-letter variable name as "x"
</details>
Done.

---

*[drake/doc/code_review_checklist.rst, line 52 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLDSWX0XPRGi9sXUGN:-KOe7Mrm3exzg6UpKVky:b-8uybh9) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L52)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Add (somewhere):
> ```
> Have you considered copy and move constructors and assignment?
> - If your class shouldn't be copied, moved, or assigned did you delete the compiler-generated methods to do so (using ``=delete``).
> - Hand written copy, move, and assignment are error prone. If you had to write your own consider how you could redesign to allow the compiler to do it.
> ```
</details>
If you have improvements like this, we definitely welcome them in future PRs.

---

*[drake/doc/code_review_checklist.rst, line 121 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3055#-KOLCK7FRmi7hLQpW_VQ:-KOe7hRGbWrl-yMgw-xn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/75fa459d5554b2a8ee4e8febe930824b9f6034cc/drake/doc/code_review_checklist.rst#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, "... with a hard-coded value *for repeatability*." Also mention that this applies to test cases. Consider heading "Is your *test* code deterministic?" since that is where the urge to use random numbers is strong.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by jwnimmer-tri** [comment]
@jhoare 
> Perhaps alongside this, you'd like to create a CONTRIBUTING.md file into the root of the repository.

That already exists.

**Comment by ggould-tri** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3055)*

**Comment by jhoare** [comment]
> That already exists.

My mistake. I took a quick look before and must have missed it. Sorry about that!

**Comment by jwnimmer-tri** [comment]
Someone appears to have resolved all of the discussions.  Hopefully that was intended.  Merging now.

**Comment by liangfok** [comment]
Oops. I resolved them for myself. I didn't realize my changes affected others.

**Pull request merged**
