### PR TITLE
Port perception/dev to SystemScalarConverter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI The Doxygen in #6982 (merged to master, but not yet on the website) and #6743 (hopefully merged to master soon) helps explain what's going on here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@nikos-tri for review of the `perception/dev/**` files, please.  You may ignore the `system/framework/**` file, they are pulled in from #6743 which is already under review.

**Comment by nikos-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/dev/feedforward_neural_network.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7012#-Ku0HKJtv9pwVaF4VTIY:-Ku0HKJuVagpv2wgS8_U:b1y3v2h) ([raw file](https://github.com/robotlocomotion/drake/blob/cf12b410f25cbd06648c9f3ad26659f5fdec2770/drake/perception/dev/feedforward_neural_network.cc#L19)):*
> ```cpp
> namespace perception {
> 
> // TODO(jwnimmer-tri) The W and b should be typed as doubles, not T.
> ```

I do store them in the context; and I want to autodiff with respect to them. For this reason I need them to be type T. If you look at DoCalcOutput you'll notice that for computing the output I first pull the weigths and biases from the context.

The reason I keep the weights and biases around as members is because I need a local cache of them for passing to the constructor in DoToAutoDiffXd. I can't remember why I didn't pull them from the context for that purpose, and maybe that's the way to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7012)*

**Comment by nikos-tri** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/dev/feedforward_neural_network.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7012#-Ku0HKJtv9pwVaF4VTIY:-Ku0VnimXOl46WjY26Hl:bfp82dz) ([raw file](https://github.com/robotlocomotion/drake/blob/cf12b410f25cbd06648c9f3ad26659f5fdec2770/drake/perception/dev/feedforward_neural_network.cc#L19)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

I do store them in the context; and I want to autodiff with respect to them. For this reason I need them to be type T. If you look at DoCalcOutput you'll notice that for computing the output I first pull the weigths and biases from the context.

The reason I keep the weights and biases around as members is because I need a local cache of them for passing to the constructor in DoToAutoDiffXd. I can't remember why I didn't pull them from the context for that purpose, and maybe that's the way to do it.
</blockquote></details>

Disregard the previous message, looking more carefully at the rest of the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7012)*

**Comment by nikos-tri** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/perception/dev/feedforward_neural_network.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7012#-Ku0HKJtv9pwVaF4VTIY:-Ku0f5A3ZXXaCynZ4gPY:bg7igkv) ([raw file](https://github.com/robotlocomotion/drake/blob/cf12b410f25cbd06648c9f3ad26659f5fdec2770/drake/perception/dev/feedforward_neural_network.cc#L19)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Disregard the previous message, looking more carefully at the rest of the changes.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7012#-:-Ku0f1oTMPMn-zM2Itb4:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Thanks!  FYI I plan to wait to merge until 6743 merges first -- assuming that happens in the next few days.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7012#-:-Ku0fgyeiyIbJpxNL2Ik:b-cr3t0q)*

**Pull request merged**
