### PR TITLE
[doc] Link from SpatialInertia to CalcSpatialInertia of meshes

### PR DESCRIPTION
**Pull request by DamrongGuoy**
I was working on SDFormat files and browsed documentation of [SpatialInertia](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html) and saw useful functions to help me set `<inertial>` blocks for HollowSphere, SolidBox, SolidCapsule, etc.  However, I didn't find the function for meshes.

I propose to make a doxygen link from SpatialInertia to CalcSpatialInertia(mesh).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
It looks like this:


> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTLZZTs444VVbqX5FZy:bkvy0ja)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
+@mitiguy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTLZp4dBK03Ksr6BUQZ:b-55mseh)* status: LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @mitiguy)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy and @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-NTOMlQP91YKf2FelSc4:-NTOMlQP91YKf2FelSc5:be7ul23) ([raw file](https://github.com/RobotLocomotion/drake/blob/11965caae877b3ce00c57641eb0101cc66ac0f17/multibody/tree/spatial_inertia.h#L89)):*
> ```objc
> /// checks are not performed when T is symbolic::Expression.
> ///
> /// @see To create a spatial inertia of a mesh, see
> ```

nit: As long as we're doing this, let's cast a wider net:

1. Mention the other overload for creating a `SpatialInertia` from a `geometry::Shape`.
2. Mention the `MbP::CalcSpatialInertia` for creating spatial inertia for a set of *bodies*.

(And if you care the last nth degree, the link generated in this @ref doesn't go to the *mesh* variant, but, instead, to the `Shape` variant. The distinction is slight because they're next to each other on their own doxygen page, but I thought it would be worth noting that this probably doesn't do what you intended.)

**Review by DamrongGuoy — COMMENTED** [review]
Added more links. Now it looks like this:


> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NToSQVG4lA7TRd4GzuG:b5j439k)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-NToP2Yb-z0y_hRpf5bN:-NToP2Yb-z0y_hRpf5bO:b-qpsfi7) (no related file):*
BTW, From [Documentation Generation Instruction](https://drake.mit.edu/documentation_instructions.html) the reviewer might want to:
```
bazel run //doc/doxygen_cxx:build -- --serve --quick drake.multibody
```

___
___
*[`multibody/tree/spatial_inertia.h` line 89 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-NTOMlQP91YKf2FelSc4:-NToT9Dj58-dqRT_Y5xg:bt4ox1i) ([raw file](https://github.com/RobotLocomotion/drake/blob/11965caae877b3ce00c57641eb0101cc66ac0f17/multibody/tree/spatial_inertia.h#L89)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: As long as we're doing this, let's cast a wider net:

1. Mention the other overload for creating a `SpatialInertia` from a `geometry::Shape`.
2. Mention the `MbP::CalcSpatialInertia` for creating spatial inertia for a set of *bodies*.

(And if you care the last nth degree, the link generated in this @ref doesn't go to the *mesh* variant, but, instead, to the `Shape` variant. The distinction is slight because they're next to each other on their own doxygen page, but I thought it would be worth noting that this probably doesn't do what you intended.)
</blockquote></details>

Done. Thanks for the suggestion.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226)* status: 1 unresolved discussion, LGTM missing from assignee mitiguy, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
Looks good -- thank you Damrong.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTpD5Gz74WhAIkZR2MA:bfy6qvh)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-NToP2Yb-z0y_hRpf5bN:-NTpCxKuClumn-J5SNwM:bg7igkv) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, From [Documentation Generation Instruction](https://drake.mit.edu/documentation_instructions.html) the reviewer might want to:
```
bazel run //doc/doxygen_cxx:build -- --serve --quick drake.multibody
```
</blockquote></details>

:lgtm: 

___

**Review by DamrongGuoy — COMMENTED** [review]
+@ggould-tri for platform review, please.  It's only 9 lines of documentation.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTpDM-95-Iy4JFooPOs:bfokmam)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: as to this change.
But for the future, it might be clearer to just add a convenience wrapper here that just does that call, rather than this "but our princess is in another castle" documentation indirection.  Consider TODO'ing that in this PR if it seems sensible to you (I assume you have a better view of the intended design of this class than I do).

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTsYT_u0CS58u7acvCL:b-s6zjg6)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19226#-:-NTspSXF9SyCaP56RX0J:bm9o57a)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

**Pull request merged**
