### PR TITLE
Improve syntactic sugar for continuous state.

### LINKED ISSUE #3751: Improve syntactic sugar for continuous state allocation
Requests from @RussTedrake on #3735:

- [ ] Provide a more concise way to access the continuous state variables as a vector

- [ ] Provide a default implementation of `LeafSystem<T>::AllocateContinuousState` that reserves a vector of `z` of a declared size.

- [ ] Rename `ContinuouousState<T>::get_state` to `get_vector`

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #3751.  The structure of commits in this PR is intentional, and may be a useful guide to reviewing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3847)

### CODE REVIEW

**Comment by liangfok** [comment]
There are some minor `cpplint` issues here. I'm going to try to refine them. Hope you don't mind.

**Comment by liangfok** [comment]
I finished refining this PR. Hope it passes `cpplint` now.

**Comment by david-german-tri** [comment]
@liangfok Did you push to my branch or something?  I didn't notice your comments until after I fixed the cpplint and did a `push -f`.  (Whatever you did, it did not re-trigger CI, since the first thing I saw this morning was the CI failure.)

**Comment by david-german-tri** [comment]
+@liangfok for feature review, +@ggould-tri for platform review, cc @RussTedrake

**Comment by liangfok** [comment]
@david-german-tri, yes, I "refined" your PR by addressing the `cpplint` issues. My changes did in fact retrigger CI. Looking at the history, I made two direct-edits of your PR and they triggered the following two builds: 

1. https://drake-jenkins.csail.mit.edu/job/experimental/5935/  -- This was aborted due to me making a second direct-edit.
2. https://drake-jenkins.csail.mit.edu/job/experimental/5936/ -- This one successfully finished.

I'm actually surprised you saw a CI failure given the success of the second build above.

**Comment by liangfok** [comment]
This is sweet! Just a few minor comments and questions.

---

Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EZBtN0GAIO-bRjGV:-KU_EZBtN0GAIO-bRjGW:bc28665) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L73)):*
> ```objc
>       throw std::out_of_range("Index " + std::to_string(index) +
>                               " out of bounds for state vector of size " +
>                               std::to_string(size()));
> ```

BTW, have you thought about combining the bodies of this method and the one below into a private helper method that is called by these methods?

---

*[drake/systems/framework/basic_vector.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EPfLlwx4qGumrMd8:-KU_EPfLlwx4qGumrMd9:b-6mvbwi) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L78)):*
> ```objc
>   }
> 
>   T& GetAtIndex(int index) override {
> ```

BTW, should this be called `GetMutableAtIndex()`?

---

*[drake/systems/framework/leaf_system.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_Eop5Q8x26sy-gbDa:-KU_Eop5Q8x26sy-gbDb:b2dyq5o) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/leaf_system.h#L167)):*
> ```objc
>   }
> 
>   /// Declares that this System should reserve continuous state with @p num_z
> ```

"num_z" should be "num_state_variables".

---

*[drake/systems/framework/leaf_system.h, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_F5YOcE4R5TbByKSh:-KU_F5YOcE4R5TbByKSi:b-hae99t) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/leaf_system.h#L188)):*
> ```objc
>   /// generalized positions, @p num_v generalized velocities, and @p num_z
>   /// miscellaneous state variables, stored in the a vector Cloned from
>   /// @p model_vector. Throws if @p model_vector has the wrong size. Has no
> ```

BTW, can you document the type of exception that could be thrown?

---

*[drake/systems/framework/subvector.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_CVXGkyJIMP2_umTf:-KU_CVXGkyJIMP2_umTg:br5kqda) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L45)):*
> ```objc
>   const T& GetAtIndex(int index) const override {
>     if (index >= size()) {
>       throw std::out_of_range("Index " + std::to_string(index) +
> ```

BTW, to reduce code nduplication, have you considered combining the bodies of this method and the method below in a private method helper method, which is called by both of these methods?

---

*[drake/systems/framework/subvector.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_C1tTHZiWoMUPgFG_:-KU_C1tTHZiWoMUPgFGa:b-i3f579) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L52)):*
> ```objc
>   }
> 
>   T& GetAtIndex(int index) override {
> ```

BTW, should this method be called `GetMutableAtIndex()`?

---

*[drake/systems/framework/supervector.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_Crey5-Zoq7yV5Iwr:-KU_Crey5-Zoq7yV5Iws:b-hjkz9q) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/supervector.h#L43)):*
> ```objc
>   }
> 
>   T& GetAtIndex(int index) override {
> ```

BWT, should this method be called `GetMutableAtIndex()`?
Same comment about merging these bodies of these two methods into a private helper method.

---

*[drake/systems/framework/vector_base.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_DGlGwJrAc6rifUBS:-KU_DGlGwJrAc6rifUBT:b-6mvbwi) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/vector_base.h#L46)):*
> ```objc
>   /// Implementations should ensure this operation is O(1) and allocates no
>   /// memory.
>   virtual T& GetAtIndex(int index) = 0;
> ```

BTW, should this be called `GetMutableAtIndex()`?

---

*[drake/systems/framework/vector_base.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_DRaMB_eolVC3n52n:-KU_DRaMB_eolVC3n52o:b-n7l8to) ([raw file](https://github.com/robotlocomotion/drake/blob/e15ac7a0392bfba8f9013dec83ba29c8f34b32d8/drake/systems/framework/vector_base.h#L49)):*
> ```objc
> 
>   /// Replaces the entire state with the contents of value. Throws
>   /// std::out_of_range if value is not a column vector with size() rows.
> ```

BTW, why remove the exception type from the documentation?

---

*[drake/systems/plants/constraint/direct_collocation_constraint.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EBRnaV3MAj5LmLD5:-KU_EBRnaV3MAj5LmLD6:b-t4gov4) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/plants/constraint/direct_collocation_constraint.cc#L101)):*
> ```cpp
>   input_port_->GetMutableVectorData<AutoDiffXd>()->SetFromVector(input);
>   context_->get_mutable_continuous_state()
>       ->SetFromVector(state);
> ```

BTW, can this be moved onto the the previous line without violating the 80 character limit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-:-KUZR9fmnXuvnrUEDH5e:bhpn9ra)*

**Comment by david-german-tri** [comment]
> This is sweet!

Thank you!  However, I propose we give this pun a decent burial.  ;-)

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EZBtN0GAIO-bRjGV:-KUbbqZp5f_FuGZ5lYyi:b-ngzcde) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L73)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, have you thought about combining the bodies of this method and the one below into a private helper method that is called by these methods?
</details>
I'd then have a const_cast, which IMO is worse than the duplication.  I did remove the pointless throw message, though.

---

*[drake/systems/framework/basic_vector.h, line 78 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EPfLlwx4qGumrMd8:-KUbbw9sK9QsBdWQARt0:brw1w8i) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L78)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should this be called `GetMutableAtIndex()`?
</details>
My preference is no, for symmetry with `operator[]`.

---

*[drake/systems/framework/leaf_system.h, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_Eop5Q8x26sy-gbDa:-KUbZBbmFewqFGhU7JQe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/leaf_system.h#L167)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "num_z" should be "num_state_variables".
</details>
Done.

---

*[drake/systems/framework/leaf_system.h, line 188 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_F5YOcE4R5TbByKSh:-KUbZcvyoQag5MaB3j4M:b-m0byvf) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/leaf_system.h#L188)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, can you document the type of exception that could be thrown?
</details>
Oh, good catch, it doesn't anymore.  Updated.

---

*[drake/systems/framework/subvector.h, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_CVXGkyJIMP2_umTf:-KUbc3qmlfxGDoGqsbWw:bribihm) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, to reduce code nduplication, have you considered combining the bodies of this method and the method below in a private method helper method, which is called by both of these methods?
</details>
As above.

---

*[drake/systems/framework/subvector.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_C1tTHZiWoMUPgFG_:-KUbc58RZ2GG3Uz1Z1C-:bribihm) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L52)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should this method be called `GetMutableAtIndex()`?
</details>
As above.

---

*[drake/systems/framework/supervector.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_Crey5-Zoq7yV5Iwr:-KUbc9eLfB_QwJESQgIQ:bribihm) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/supervector.h#L43)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BWT, should this method be called `GetMutableAtIndex()`?
> Same comment about merging these bodies of these two methods into a private helper method.
</details>
As above.

---

*[drake/systems/framework/vector_base.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_DGlGwJrAc6rifUBS:-KUbcP4BIYupvg1q0DGi:bribihm) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/vector_base.h#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, should this be called `GetMutableAtIndex()`?
</details>
As above.

---

*[drake/systems/framework/vector_base.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_DRaMB_eolVC3n52n:-KUbgIfQ5NGNXa8mjdyC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e15ac7a0392bfba8f9013dec83ba29c8f34b32d8/drake/systems/framework/vector_base.h#L49)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, why remove the exception type from the documentation?
</details>
Done.

---

*[drake/systems/plants/constraint/direct_collocation_constraint.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KU_EBRnaV3MAj5LmLD5:-KUbgU6aNKDwD4FXe72a:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/plants/constraint/direct_collocation_constraint.cc#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, can this be moved onto the the previous line without violating the 80 character limit?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-:-KUbYkcEVG5S7hS2_bLA:b-dwbqhb)*

**Comment by ggould-tri** [comment]
This is a wonderful improvement to readability.

---

Reviewed 42 of 42 files at r1.
Review status: 33 of 42 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KUbiN1uytjEX5xEpzj3:-KUbiN1uytjEX5xEpzj4:bvhpzqu) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L74)):*
> ```objc
>                               " out of bounds for state vector of size " +
>                               std::to_string(size()));
>     }
> ```

Rule of three on this size check and exception.  Please factor it.

---

*[drake/systems/framework/subvector.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KUbiumxQWRrWwlTlBjQ:-KUbiumxQWRrWwlTlBjR:b-gw9wit) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L48)):*
> ```objc
>                               " out of bounds for subvector of size " +
>                               std::to_string(size()));
>     }
> ```

Rule of three on this size check and exception.  Please factor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-:-KUbjF3rEYFj3Mwc7sna:b-l409ep)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-:-KUbl9a2w5Rbw96nwQM4:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KUbiN1uytjEX5xEpzj3:-KUblIjMuqkEFL5npWxD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/basic_vector.h#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Rule of three on this size check and exception.  Please factor it.
</details>
Done.

---

*[drake/systems/framework/subvector.h, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-KUbiumxQWRrWwlTlBjQ:-KUblJwnBRiPbaBwqKSN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/56a6422ca037e28364c1ea9bcf120f309ea65a93/drake/systems/framework/subvector.h#L48)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Rule of three on this size check and exception.  Please factor.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3847#-:-KUbqLr7wBEMt_UFwr6h:bnfp4nl)*

**Comment by david-german-tri** [comment]
MATLAB failure is unrelated license server flake.  Merging.

**Pull request merged**
