### PR TITLE
non-world reference frames for DiffIK

### PR DESCRIPTION
**Pull request by sgmurray**
Add support for non-world reference frames to differential inverse kinematics.
    
Adds two new overloads to DoDifferentialInverseKinematics().

Towards #19580

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail @svenevs it seems like Jenkins bot commands are no longer working, possibly due to the upgrades or backup/restore.  Could you check into it please?

**Comment by jwnimmer-tri** [comment]
> Could you check into it please?

Hmm, maybe it just wasn't responsive right away?  Jenkins looks fine now.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI could I ask you to feature-review this code if you have time, or else find/suggest someone who could?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with some small nits and a question, thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-:-NnQdNjQ6r90H7JHMjeo:b-b2f5ci)* status: 2 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 393 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQasSWDhP6eOdMON1k:-NnQasSX6aWt7UeO1HF4:b90ch2c) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/differential_inverse_kinematics.h#L393)):*
> ```objc
>  * @param context Must be the Context of the MultibodyPlant. Contains the
>  * current generalized position and velocity.
>  * @param V_AE_desired Desired @p frame_A spatial velocity of @p frame_E.
> ```

nit This phrase may be ambiguous.

Consider rewording as:
```
Desired spatial velocity of @p frame_E in @p frame_A.
```
___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 394 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQb7SzDX93dpBiPc8L:-NnQb7SzDX93dpBiPc8M:b-qsbiki) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/differential_inverse_kinematics.h#L394)):*
> ```objc
>  * current generalized position and velocity.
>  * @param V_AE_desired Desired @p frame_A spatial velocity of @p frame_E.
>  * @param frame_A Reference frame.
> ```

BTW I believe this does not need to be an inertial frame. What do you think?
___
*[`multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQchgx9gq4NG_3pXUJ:-NnQchgx9gq4NG_3pXUK:biutye7) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc#L149)):*
> ```cpp
>   }
> 
>   void CheckPositiveResult(const multibody::SpatialVelocity<double>& V_AB,
> ```

nit Rather than duplicate both of these functions, is it possible to to make the `V_WE` flavor of this function call into this function using `frame_W, frame_E_` ?
___
*[`bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQdC3K8sqcjCWxUJwH:-NnQdC3K8sqcjCWxUJwI:b-b7l6j6) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py#L102)):*
> ```Python
>         frame = plant.GetFrameByName("Link2")
> 
>         world_frame = plant.world_frame()
> ```

BTW (pre-existing) I believe these should be using named kwargs, i.e. `(plant=plant, context=context, ...)`, etc.

However, since this is pre-existing, I will not defect it in this PR. (this comment is non-blocking)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@SeanCurtis-TRI for platform review on Monday, please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-:-NnQhBAg7Iih9dU3J7bY:b-jxm7hq)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @sgmurray)

**Comment by RussTedrake** [comment]
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NnZVeWf28CkPWscfN50:blci40e) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
> ```objc
> 
> /**
>  * A wrapper over DoDifferentialInverseKinematics(q_current, v_current, V, J,
> ```

Sorry I'm late to the party here.  

I know that the proposal to add a new overload was mine (in https://github.com/RobotLocomotion/drake/issues/19580 ).  Now that we see the implementation details, can we just agree quickly that we prefer this to the other natural choice: Adding frame_A as an optional argument which defaults to world in the existing entry points?

Now that we can see your implementation, and it _looks_ at my quick glance like there would be no additional computational cost, perhaps the single entry point optional argument is better?

**Review by sgmurray — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 393 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQasSWDhP6eOdMON1k:-Nnb2Vfs4ouDaQPGabwT:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/differential_inverse_kinematics.h#L393)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This phrase may be ambiguous.

Consider rewording as:
```
Desired spatial velocity of @p frame_E in @p frame_A.
```
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 394 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQb7SzDX93dpBiPc8L:-Nnb2byXDxIXmYKr8iai:b-lpnsuo) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/differential_inverse_kinematics.h#L394)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I believe this does not need to be an inertial frame. What do you think?
</blockquote></details>

I also believe that frame A does not need to be an inertial frame. I have updated to the documentation to further clarify that.
___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-Nnb5RGx60emOHWUUrSK:b6ox5ve) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Sorry I'm late to the party here.  

I know that the proposal to add a new overload was mine (in https://github.com/RobotLocomotion/drake/issues/19580 ).  Now that we see the implementation details, can we just agree quickly that we prefer this to the other natural choice: Adding frame_A as an optional argument which defaults to world in the existing entry points?

Now that we can see your implementation, and it _looks_ at my quick glance like there would be no additional computational cost, perhaps the single entry point optional argument is better?
</blockquote></details>

I do not have a strong opinion with regards to overloads vs optional argument. I will commit to implementing whichever option the group decides on.
___
*[`multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQchgx9gq4NG_3pXUJ:-Nnb36Gq-YuwGDsMmgM5:bb7f2mf) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc#L149)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than duplicate both of these functions, is it possible to to make the `V_WE` flavor of this function call into this function using `frame_W, frame_E_` ?
</blockquote></details>

done
___
*[`bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQdC3K8sqcjCWxUJwH:-Nnb3O0S2_0GhYLH0o28:biabwaz) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW (pre-existing) I believe these should be using named kwargs, i.e. `(plant=plant, context=context, ...)`, etc.

However, since this is pre-existing, I will not defect it in this PR. (this comment is non-blocking)
</blockquote></details>

I fixed it anyways.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NncrVreBoDGExtq3SCU:b-athbm8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, sgmurray wrote…</i></summary><blockquote>

I do not have a strong opinion with regards to overloads vs optional argument. I will commit to implementing whichever option the group decides on.
</blockquote></details>

@EricCousineau-TRI , @SeanCurtis-TRI , wdyt?

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 394 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQb7SzDX93dpBiPc8L:-NndJlCEABJGebWyUuni:b-w196av) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/multibody/inverse_kinematics/differential_inverse_kinematics.h#L394)):*
<details><summary><i>Previously, sgmurray wrote…</i></summary><blockquote>

I also believe that frame A does not need to be an inertial frame. I have updated to the documentation to further clarify that.
</blockquote></details>

OK Thanks!
___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NndJ6hWC1-dyVWq25Fy:b-3pvw6m) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

@EricCousineau-TRI , @SeanCurtis-TRI , wdyt?
</blockquote></details>

My concern for adding `frame_A` as an optional argument is that either we add it at the end (logical grouping of arguments may not make a ton of sense, as it appears after `parameters`), or we break backwards compatibility.

Are you OK with either of those?
___
*[`bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnQdC3K8sqcjCWxUJwH:-NndJrIN-Jjx1cbMJQux:b-zfh9kw) ([raw file](https://github.com/RobotLocomotion/drake/blob/49c97f5609f7f931cd7cd80a6e4419e290866b83/bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py#L102)):*
<details><summary><i>Previously, sgmurray wrote…</i></summary><blockquote>

I fixed it anyways.
</blockquote></details>

OK Awesome, thanks!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NneUFtr2l0BtUBZqhNu:bdvsccl) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My concern for adding `frame_A` as an optional argument is that either we add it at the end (logical grouping of arguments may not make a ton of sense, as it appears after `parameters`), or we break backwards compatibility.

Are you OK with either of those?
</blockquote></details>

What if we added `frame_A` to the parameters where it defaults to world (with some yet-to-be-determined encoding)?

All of these APIs already take the parameters. How contorted would it be to interpret the the relative-to frame as a "parameter" in that sense?

The primary argument I can imagine is parameter names and python bindings. Parameters currently named `?_WE_desired` would have to change to `?_AE_desired` and indicate that frame A is defined in `parameters`. 

-----

If we don't like that, I'm content with any of the other options (overloads or trailing optional parameter). I'll defer my full review until we have a clear consensus on this.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NoF-L5_4chETMRyEUsO:b-pbg46w) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

What if we added `frame_A` to the parameters where it defaults to world (with some yet-to-be-determined encoding)?

All of these APIs already take the parameters. How contorted would it be to interpret the the relative-to frame as a "parameter" in that sense?

The primary argument I can imagine is parameter names and python bindings. Parameters currently named `?_WE_desired` would have to change to `?_AE_desired` and indicate that frame A is defined in `parameters`. 

-----

If we don't like that, I'm content with any of the other options (overloads or trailing optional parameter). I'll defer my full review until we have a clear consensus on this.
</blockquote></details>

Sorry to be slow deciding.  Let's stick with the overloads as implemented. This version is nicely consistent with e.g. the CalcJacobian... methods.

If anything, maybe we can eventually deprecate the original entry point and make this one the default.

**Review by sgmurray — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NoG7jIZC-56KFrOGnmW:b-1rsveg) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Sorry to be slow deciding.  Let's stick with the overloads as implemented. This version is nicely consistent with e.g. the CalcJacobian... methods.

If anything, maybe we can eventually deprecate the original entry point and make this one the default.
</blockquote></details>

Fair enough.

For what it is worth, I also have a branch that adds frame_A to the DifferentialInverseKinematicsParameters class as suggested by @SeanCurtis-TRI . This has the advantage that no additional changes need to be made to the DifferentialInverseKinematicsIntegrator. 

https://github.com/sgmurray/drake/tree/iss19580_params

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NoH2g9E0OZ4KwSTl-9F:b-9fsuwi) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, sgmurray wrote…</i></summary><blockquote>

Fair enough.

For what it is worth, I also have a branch that adds frame_A to the DifferentialInverseKinematicsParameters class as suggested by @SeanCurtis-TRI . This has the advantage that no additional changes need to be made to the DifferentialInverseKinematicsIntegrator. 

https://github.com/sgmurray/drake/tree/iss19580_params
</blockquote></details>

I appreciate that.  But having thought it through, I think the API in this current draft is the right long term API, so we should prefer that.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NoHzrFK2_UhtW5HJKMc:b-gd8ud8) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I appreciate that.  But having thought it through, I think the API in this current draft is the right long term API, so we should prefer that.
</blockquote></details>

Keeping it as-is sounds great to me.
FWIW, I think this conversation is still blocked - Russ, would you be able to mark it as resolved?

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With two cosmetic clean ups.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-:-NoI703IBTDY7BZhPIDV:b7418hr)* status: 3 unresolved discussions, missing label for release notes (waiting on @sgmurray)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 439 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NoI4tR3CPJ7gtYozx_9:-NoI4tR3CPJ7gtYozx_A:byp2bj6) ([raw file](https://github.com/RobotLocomotion/drake/blob/096a50f933129475f462849b192c0e20e614bd22/multibody/inverse_kinematics/differential_inverse_kinematics.h#L439)):*
> ```objc
>  * A wrapper over DoDifferentialInverseKinematics(robot, context, V_AE_desired,
>  * frame_A, frame_E, params) that tracks frame E's pose in frame A. q_current
>  * and v_current are taken from @p context. V_AE is computed by
> ```

nit: For consistency, I believe this should be `V_AE_desired`.



_Code quote:_
```objc
V_AE
```
___
*[`multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc` line 350 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NoI6aOQB16_aZpXHOex:-NoI6aOQB16_aZpXHOey:bofhcib) ([raw file](https://github.com/RobotLocomotion/drake/blob/096a50f933129475f462849b192c0e20e614bd22/multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc#L350)):*
> ```cpp
>     plant_->GetFrameByName("iiwa_link_0");
>   math::RigidTransform<double> X_AE = frame_E_->CalcPose(*context_, frame_A);
>   math::RigidTransform<double> X_AE_desired =
> ```

nit: make `X_AE_desired` const.

Particularly important since `X_AE` is *not* `const` (the contrast has value).

**Review by sgmurray — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: 1 unresolved discussion, missing label for release notes

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 439 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NoI4tR3CPJ7gtYozx_9:-NoKFSOrBVjqR7JG0xIf:b7sr8fw) ([raw file](https://github.com/RobotLocomotion/drake/blob/096a50f933129475f462849b192c0e20e614bd22/multibody/inverse_kinematics/differential_inverse_kinematics.h#L439)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: For consistency, I believe this should be `V_AE_desired`.
</blockquote></details>

done.

The existing documentation of the other overload also had the same issue (V_WE vs V_WE_desired), so I fixed that too.
___
*[`multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc` line 350 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NoI6aOQB16_aZpXHOex:-NoKFKAR6jmzVYV6nzfT:b-7rl0jd) ([raw file](https://github.com/RobotLocomotion/drake/blob/096a50f933129475f462849b192c0e20e614bd22/multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc#L350)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: make `X_AE_desired` const.

Particularly important since `X_AE` is *not* `const` (the contrast has value).
</blockquote></details>

done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: feature) 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-:-NoN1DQJCG86p73X5bsd:b-l8xbmn)* status: 1 unresolved discussion

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Dismissed @RussTedrake from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20735)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

___
*[`multibody/inverse_kinematics/differential_inverse_kinematics.h` line 385 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20735#-NnZVeWf28CkPWscfN5-:-NoN1JN_7ETtIAU-RzaS:bkscn2x) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9671311a40085e90faebe2588237a35993bf57a/multibody/inverse_kinematics/differential_inverse_kinematics.h#L385)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Keeping it as-is sounds great to me.
FWIW, I think this conversation is still blocked - Russ, would you be able to mark it as resolved?
</blockquote></details>

Given the nature of the conversation, I'll go ahead and bump him out so we can merge.

**Pull request merged**
