### PR TITLE
Moved kuka iiwa 14 model into drake/manipulation and made it xacro-generated.

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards #5267.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5636)

### CODE REVIEW

**Comment by liangfok** [comment]
+@naveenoid and +@ericcousineau-tri for feature review please. Thanks!

---

Review status: 0 of 66 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgKXwByBudsk6_f6Fl4:b-sch2cz)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 88 of 88 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/iiwa_description/LICENSE.TXT, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-KgLz4KZhrtHKq2Hzifv:-KgLz4K_7IUTA0zUeUQo:b-k3d9q0) ([raw file](https://github.com/robotlocomotion/drake/blob/639cea583edfc71216f4a7ba59482b75826c6ab7/drake/manipulation/models/iiwa_description/LICENSE.TXT#L3)):*
> ```
> This folder contains a model of the Kuka LBR IIWA R820 14. The URDF and OBJ
> files that constitute the arm model are taken from
> https://github.com/SalvoVirga/iiwa_stack.
> ```

BTW, would it be possible to include the abbreviated Git ref / SHA here as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgM-0eASTqmT9yfQlJy:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 65 of 66 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/iiwa_description/LICENSE.TXT, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-KgLz4KZhrtHKq2Hzifv:-KgMiYbV230kDtPIrp3n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/639cea583edfc71216f4a7ba59482b75826c6ab7/drake/manipulation/models/iiwa_description/LICENSE.TXT#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW, would it be possible to include the abbreviated Git ref / SHA here as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636)*

**Comment by liangfok** [comment]
+@ggould-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgOhgV71I-9SAniiz_K:b-yqnxb4)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/manipulation/models/iiwa_description/LICENSE.TXT, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-KgLz4KZhrtHKq2Hzifv:-KgPNbCN79AIvYL6FEgh:b2g4ulo) ([raw file](https://github.com/robotlocomotion/drake/blob/639cea583edfc71216f4a7ba59482b75826c6ab7/drake/manipulation/models/iiwa_description/LICENSE.TXT#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
Would it be possible to abbreviate the SHA's to just the 7-character version for brevity?
Also, is there a motivation for having a different SHA between the file origin (iiwa_stack:2fa5bd5) and the original license (iiwa_stack:1f45c77)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636)*

**Comment by ggould-tri** [comment]
This all looks good as it stands, but I am wary of having generated files checked in like this.  If you have investigated and it is in fact impractical to teach bazel to run xacro, you should include the exact command line that generates each urdf file.

---

Reviewed 87 of 88 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgPO1M9luKP3wp4ntfj:b-vo4oo9)*

**Comment by liangfok** [comment]
Teaching bazel to run `xacro` will likely require ROS to either be installed on the system or in Bazel's sandbox (see #bazel in drakedevelopers slack -- look like it's covered in a giant swarm of bees).

The exact command line for generating the URDFs is available in the README.md that's part of this PR:

https://github.com/liangfok/drake/blob/fdd67bebad1b7fd5cc1946dc092594e9d158cdef/drake/manipulation/models/iiwa_description/README.md

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgPQFBAd4FoyT5F1IWt:b-wg8yrs)*

**Comment by ggould-tri** [comment]
On the readme, excellent, I missed that. :lgtm:
On the generation, I am sorry to hear about the ros bees; your approach here is sensible.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-:-KgPST324MZxakLeqyGz:be6x5f1)*

**Comment by liangfok** [comment]
Review status: 65 of 66 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/manipulation/models/iiwa_description/LICENSE.TXT, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5636#-KgLz4KZhrtHKq2Hzifv:-KgPWtHOJ-MKdPCh3q6L:b-fiiqvx) ([raw file](https://github.com/robotlocomotion/drake/blob/639cea583edfc71216f4a7ba59482b75826c6ab7/drake/manipulation/models/iiwa_description/LICENSE.TXT#L3)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Thanks!
Would it be possible to abbreviate the SHA's to just the 7-character version for brevity?
Also, is there a motivation for having a different SHA between the file origin (iiwa_stack:2fa5bd5) and the original license (iiwa_stack:1f45c77)?
</blockquote></details>

Done.

Regarding the differing SHA for the license, that occurred because it was the SHA in which the LICENSE.TXT file was last updated. To avoid confusion, I modified this file to use the same SHA as the fork point (2fa5bd5).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 88 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5636)*

**Pull request merged**
