### PR TITLE
Add more SpatialInertia::ObjectWithMass() functions

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@rpoyner-tri 
Note: Feel free to remove yourself and instead assign to Xuechen or Sherm or ... 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-:-NZhz1I505JpugtM8JTb:b-tbxsxf)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
-@rpoyner-tri +@sherm1 you mind taking a look at these?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-:-N_0DhHy8QUycTzkiJjR:b-zd7i24)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
Will do!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-:-N_0QsptAcX3aJGEU71r:bhy9ost)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: with a few minor comments, PTAL
Please be sure to generate Doxygen to see if you like the result: 
`bazel run //doc/doxygen_cxx:build drake/multibody -- --serve --quick`

+@jwnimmer-tri for platform review per schedule, please

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-:-N_0Y80hBnkcjmVSLi93:b-8drah4)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.h` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0TRal0SnMc3t2J3lZ:-N_0TRal0SnMc3t2J3l_:bvv1iec) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L217)):*
> ```objc
>   /// its geometric center Bo (which is coincident with B's center of mass Bcm).
>   /// @param[in] mass mass of the solid capsule (kg).
>   /// @param[in] radius radius of the cylinder/half-sphere part of the capsule.
> ```

nit: part -> parts
___
*[`multibody/tree/spatial_inertia.h` line 265 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0VJTP6ExG2dm9Iy8c:-N_0VJTP6ExG2dm9Iy8d:b-6w4o7s) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L265)):*
> ```objc
>   /// @throws std::exception if mass, radius, or length is not positive and
>   /// finite.
>   /// @pre ‖unit_vector‖ = 1.
> ```

minor: missing the nice `see UnitInertia::SolidCapsule` phrase
___
*[`multibody/tree/spatial_inertia.h` line 266 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0VSt51OxWp0nrN7bb:-N_0VSt51OxWp0nrN7bc:bbpzrdr) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L266)):*
> ```objc
>   /// finite.
>   /// @pre ‖unit_vector‖ = 1.
>   /// @see SolidCylinderWithMassAboutEnd() to calculate M_BBp_B, B's spatial
> ```

minor: this reference didn't generate a link in Doxygen. Maybe missing a qualifier or did the function get renamed?
___
*[`multibody/tree/spatial_inertia.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0WooKAFG1_qxqnPak:-N_0WooKAFG1_qxqnPal:b-swoewu) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.cc#L145)):*
> ```cpp
>   const T volume = pi_r_squared * length + (4.0 / 3.0) * pi_r_squared * radius;
>   const T mass = density * volume;
>   return SolidCapsuleWithMass(mass, radius, length, unit_vector);
> ```

BTW with this implementation you do the runtime checks twice. I assume there is no performance issue here so this is fine but just wanted to note that in case it was unintentional.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-:-N_0jKkuCfOFNKiR8zAU:b-vtj4vo)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0gz4e9bzPaGcUxcgz:-N_0gz4fCtnZASb2P8FK:b6j2uun) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc#L63)):*
> ```cpp
>                            MultibodyPlant<double>* plant) {
>   const SpatialInertia<double> M_Bcm =
>       SpatialInertia<double>::SolidCylinderWithMass(
> ```

BTW Writing the classname twice is not strictly required, if you prefer.

Ditto throughout this PR.



_Suggestion:_
```cpp
  const auto M_Bcm = SpatialInertia<double>::SolidCylinderWithMass(
```
___
*[`multibody/tree/spatial_inertia.h` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0hJ0u3Kfo8u_wGH69:-N_0hJ0v8IaPyJSM_IYa:bikj9p2) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L217)):*
> ```objc
>   /// its geometric center Bo (which is coincident with B's center of mass Bcm).
>   /// @param[in] mass mass of the solid capsule (kg).
>   /// @param[in] radius radius of the cylinder/half-sphere part of the capsule.
> ```

nit It's somewhat odd to document that `length` is in meters, but not the same for `radius`.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0gz4e9bzPaGcUxcgz:-N_619bz00ZbeZH6nGnt:bilg8vp) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Writing the classname twice is not strictly required, if you prefer.

Ditto throughout this PR.
</blockquote></details>

I appreciate the advice and input.  As Sean, Alejandro and others know, my preference tends towards explicit notation and declarations (although the auto keyword is a rockstar sometimes).    I have read various opinions on the good/bad/ugly to auto.  Hopefully, my use is not causing stress.  
___
*[`multibody/tree/spatial_inertia.h` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0TRal0SnMc3t2J3lZ:-N_66HobEnvQlkUFYNT7:brdmx0x) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L217)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: part -> parts
</blockquote></details>

Done.  Changed part to parts here and two other repeated spots.
___
*[`multibody/tree/spatial_inertia.h` line 217 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0hJ0u3Kfo8u_wGH69:-N_66XRxA6u_mkpqEro3:bj11o7b) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L217)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It's somewhat odd to document that `length` is in meters, but not the same for `radius`.
</blockquote></details>

Done.  Removed (meters) here and one other repeated spot.
___
*[`multibody/tree/spatial_inertia.h` line 265 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0VJTP6ExG2dm9Iy8c:-N_69I_QDBu6qRGE-aTO:b-sob2ps) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L265)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: missing the nice `see UnitInertia::SolidCapsule` phrase
</blockquote></details>

Not done.  Unfortunately, UnitInertia::SolidCylinder() does not enforce a unit vector (whereas UnitIneria::SolidCapsule() does)..  It only checks that it is non-zero.  We discussed this before and we both think this is a defect.  Fixing it may be a breaking change.
___
*[`multibody/tree/spatial_inertia.h` line 266 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0VSt51OxWp0nrN7bb:-N_68FWG95VVSH8F7GOm:b-nsdmr) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.h#L266)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this reference didn't generate a link in Doxygen. Maybe missing a qualifier or did the function get renamed?
</blockquote></details>

Done.  Yes -- this comment is getting ahead of myself.  Since this documentation pre-exists the function's creation.   I replaced the @see comment  with a TODO().
___
*[`multibody/tree/spatial_inertia.cc` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0WooKAFG1_qxqnPak:-N_6AA2v4fFikVNuZmS4:b-5t0geq) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/multibody/tree/spatial_inertia.cc#L145)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW with this implementation you do the runtime checks twice. I assume there is no performance issue here so this is fine but just wanted to note that in case it was unintentional.
</blockquote></details>

Done.  (Yes this is intentional).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0gz4e9bzPaGcUxcgz:-N_6L7FvCR-kYqDiMrRW:b-4345v6) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc#L63)):*
> I have read various opinions on the good/bad/ugly to auto.

If you could provide a citation for anyone advising _against_ using `auto` in this case, please send me a link, so that I might learn something.

The modal use of `auto` is when constructing something using a factory function instead of the class's constructor (e.g., `make_unique`).  I have never seen anyone advocate against it in this situation.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19737)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc` line 63 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19737#-N_0gz4e9bzPaGcUxcgz:-N_6OzqABNTRJQkqmOHO:bmtezkx) ([raw file](https://github.com/RobotLocomotion/drake/blob/82519386fd108e77719837bb8985058be7489614/examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc#L63)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I have read various opinions on the good/bad/ugly to auto.

If you could provide a citation for anyone advising _against_ using `auto` in this case, please send me a link, so that I might learn something.

The modal use of `auto` is when constructing something using a factory function instead of the class's constructor (e.g., `make_unique`).  I have never seen anyone advocate against it in this situation.
</blockquote></details>

I acknowledge your expertise in these matters. 

From my less expert viewpoint, it is not clear that this function is named in such a way to clearly communicate it is a factory function -- similarly for related functions such as SpatialInertia::PointMass().  As such, I prefer to be explicit.

I am happy to change it in a subsequent PR (probably consistently as the auto is not used in many places).  Let me know if you feel strongly about it.

**Comment by mitiguy** [comment]
PR #19737 makes progress on issue #18416.

**Pull request merged**
