### PR TITLE
Visualize meshcat pointclouds

### PR DESCRIPTION
**Pull request by kmuhlrad**
A system to visualize point clouds in meshcat. It can be called with a MeshcatVisualizer system or with an independent meshcat Visualizer instance.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10911)

### CODE REVIEW

**Comment by kmuhlrad** [comment]
Resolves https://github.com/RobotLocomotion/drake/issues/9891

**Comment by EricCousineau-TRI** [comment]
I'm tinkering with the changes. Will push them soom.

**Comment by EricCousineau-TRI** [comment]
Preview:
> image

**Comment by EricCousineau-TRI** [comment]
Would require @RussTedrake's request in #9599 for better docstring rendering of ports at some point.

**Comment by EricCousineau-TRI** [comment]
Going to squash+merge.

**Pull request merged**
