### PR TITLE
Remove `tags = ["snopt"]` from several tests which pass with IPOPT

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7032)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental please
@drake-jenkins-bot mac-clang-experimental please

**Comment by sammy-tri** [comment]
-(status: do not review) +@sherm1 for all review based on platform rotation (I can get a feature reviewer if you think it's necessary).

As far as I can tell, these were probably cargo-cult copied from other examples which didn't pass under IPOPT.  Tested on both mac and linux in CI with no issues.

cc: @jwnimmer-tri who is looking into changing IPOPT versions IIRC

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7032#-:-Ku5GdjDZ93NWAmQ7Zk0:bn59k8t)*

**Comment by jwnimmer-tri** [comment]
Thanks.  It's probably still days / few weeks away _if_ we decide to change IPOPT version.  We'll just test against whatever's on master at that time, and deal accordingly.

**Comment by sherm1** [comment]
I'm happy as long as these pass CI, which they do: :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7032#-:-Ku5KzqOxdkf3PRzXoSx:b-iri9w8)*

**Pull request merged**
