### PR TITLE
Remove deprecated code 2023-02

### LINKED ISSUE #18688: Deprecation removals 2023-02
The following code is scheduled for deprecation removals on 2023-02-01.

I'm looking for a volunteer to prepare the pull request.  It's probably easiest to do them all at once since they are each pretty small on their own.

From #18179 via @hongkai-dai:
- `drake/common/symbolic/trigonometric_polynomial.h`
- `drake/bindings/pydrake/symbolic_py.cc`
- `drake/bindings/pydrake/test/symbolic_test.py`

From #18094 via @sherm1:
- `drake/systems/framework/system.h`

From #18122 via @amcastro:
- `drake/bindings/pydrake/multibody/tree_py.cc`

(Other code due 2023-02 has already been filed at #18686 and #18689.)

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes #18688.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +(release notes: removal of deprecated) 
+@sherm1 for both reviews, Wednesday schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716#-:-NN93wYZ-pcW_mp0gtfY:b-i0dfwj)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by rpoyner-tri — COMMENTED** [review]
Closes #18688.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716#-:-NN94DaEEa24N4JcpRdS:bhti9aa)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
BTW I searched for 2023-02-01 and found a few more:
- package_map.cc
- meldis.py
- plotting.py
- camera_foinfg_functions.h
- and a bunch of dreal and .bzl files

Should those be included here?

:lgtm: x 2 for the changes already here (pending CI)

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716#-:-NN98umDB-FImBVYvfV3:bca5lc4)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @rpoyner-tri)

**Review by sherm1 — COMMENTED** [review]
*camera_config_functions.h

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716#-:-NN9A9n3Ab6F_rewys7M:b-glhjsj)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Does your search space include #18686 and #18689 ?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18716#-:-NN9F8wk22FkQHxNgD3v:b-pr45p0)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @rpoyner-tri)

**Comment by sherm1** [comment]
Nope, I was out of date -- sorry!

**Pull request merged**
