### PR TITLE
A collection of additions/modifications to System 2

### PR DESCRIPTION
**Pull request by sherm1**
(This is a squashed version of PR #2513 which died due to trashed branch during the submodule cutover.)

Changes here are:
- Adds integrator test cases to the spring-mass system.
- Adds energy and power methods to the API.
- Adds power method and work integral to spring-mass system.
- Adds scaling to StateVector arithmetic.
- Renames potentially-cacheable methods to start with "Eval".
- Renames Output->EvalOutput, Dynamics->EvalTimeDerivatives.
- Renamed Time class TimeStep and adds get_time/set_time to Context.

Unfortunately reviewer comments did not survive the PR switch. I have addressed most of them. Please take a fresh look.

Feature review should be @david-german-tri but he is on vacation and I need this to go in fast so I can add the non-vector (AbstractValue) Outputs this week. So @RussTedrake you are feature reviewer. David, when you get back please feel free to undo anything you don't like here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2725)

### CODE REVIEW

**Comment by sherm1** [comment]
+@russtedrake for feature review
Not sure about platform -- anyone available? if not, I'll invoke holiday exception and do it myself.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLcUPPGsZ6dSJfnHN1y:-1082276590)*

**Comment by RussTedrake** [comment]
looking really good.  had a few more questions/comments.  excited to get this in.

---

Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLkXUyaL1QxTo4Q_QIf:-1724213363) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
> ```cpp
> }
> 
> // TODO(sherm1) Make this more interesting.
> ```

i think the most obvious thing is to have an input which is a horizontal force on the mass (all of our other spring mass examples have this).  that would be a good role for this.  

---

*[drake/examples/spring_mass/test/spring_mass_system_test.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkYXtFle7DyGzX8nSv:-KLkYXtFle7DyGzX8nSw:1680254489) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/test/spring_mass_system_test.cc#L63)):*
> ```cpp
>     system_output_ = system_->AllocateOutput();
>     system_derivatives_ = system_->AllocateTimeDerivatives();
>     const int nq = system_derivatives_->get_generalized_position().size();
> ```

is this the recommended way to obtain that in general?  will this call to size() ever return -1 (e.g. for dynamically sized objects)?

---

*[drake/systems/framework/context.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZYm5AnIEVwfne_l9:-KLkZYm5AnIEVwfne_lA:-2138309331) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L16)):*
> ```objc
> 
> template <typename T>
> struct TimeStep {
> ```

I'm confused.  Is this really time, or timestep?  if it holds the time in seconds, then it is not timestep (which is the step size?)

---

*[drake/systems/framework/context.h, line 156 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZnkw1rAhE5vASm1m:-KLkZnkw1rAhE5vASm1n:-950703187) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L156)):*
> ```objc
>   Context& operator=(Context&& other) = delete;
> 
>   // Current time and step information.
> ```

are you hoping to add additional information to that structure, then?

---

*[drake/systems/framework/continuous_system_interface.h, line 23 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_-OD6Nx9cKX-QrWx:-KLk_-OEe8GwJyNbe8r3:883014738) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/continuous_system_interface.h#L23)):*
> ```objc
>   /// output argument to EvalTimeDerivatives.
>   virtual std::unique_ptr<ContinuousState<T>> AllocateTimeDerivatives()
>       const = 0;
> ```

yes -- that's definitely a good change.

---

*[drake/systems/framework/state.h, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_B_80SsCOvwOhA-3:-KLk_B_80SsCOvwOhA-4:-1945646540) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/state.h#L113)):*
> ```objc
> 
>  private:
>   // The entire state vector.  May or may not own the underlying data.
> ```

just to be sure I understand.  did you do this so that the comments do not show up in doxygen?  wouldn't it be better to leave them with /// and use doxygen's options to include or not include private methods?

---

*[drake/systems/framework/system_interface.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_cGkSKvwDSZQJZvb:-KLk_cGkSKvwDSZQJZvc:-1414583919) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/system_interface.h#L72)):*
> ```objc
>   // methods. For now I'm breaking the no-code-in-interface rule to provide
>   // zero defaults so that these don't have to be implemented in non-physical
>   // systems.
> ```

should you add the non-conservative power to this list, too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLk_wqay2VIdHE66h_n:589340873)*

**Comment by sherm1** [comment]
Thanks, Russ. Responses to your questions & comments below.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZYm5AnIEVwfne_l9:-KLnGxhf-jbLtYNqZIE5:466614191) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L16)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> I'm confused.  Is this really time, or timestep?  if it holds the time in seconds, then it is not timestep (which is the step size?)
</details>
This is poorly named -- it is intended to hold the current value of the independent variable (time) and a counter or step number that can be used to distinguish multi-valued signals such as occur before and after events (since events occur in zero time both before and after are at the same time). Right now the struct is just a place holder so that we won't be blindsided when we need to carry along some extra information besides just the numerical value of time. I called it TimeStep because it has time and step info but forgot that that phrase has another meaning (dt)! 

I believe the step number will also be useful for non-forward-dynamics solvers applied to Systems, such as equilibrium analysis and design studies, where there are distinct steps but time doesn't advance.

I will try to think up a better name for this struct -- any suggestions?

---

*[drake/systems/framework/context.h, line 156 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZnkw1rAhE5vASm1m:-KLnJ8I5Mz_xnWxd2khz:1784553336) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L156)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> are you hoping to add additional information to that structure, then?
</details>
Yes, exactly.

---

*[drake/systems/framework/state.h, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_B_80SsCOvwOhA-3:-KLnJOh5PRmNkU5iXGjB:-686014595) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/state.h#L113)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> just to be sure I understand.  did you do this so that the comments do not show up in doxygen?  wouldn't it be better to leave them with /// and use doxygen's options to include or not include private methods?
</details>
We already have `EXTRACT_PRIVATE=NO` in Drake's Doxyfile so private comments don't show up either way. My reasons for not wanting these doxygenated are:
- I have only used doxygen to produce documentation for API users, so I interpret the presence or absence of doxygen comments as information about what is part of the API and what is not. 
- I worry that developers won't think clearly about the API if they write doxygen for everything -- API documentation is aimed at a different audience. 
- I know doxygen does have a developer mode, but I don't know how useful it is -- I assume developers can look in the header file and read the comments! 
- I'd like to be able to write private comments without having to satisfy doxygen's formatting rules.
- I assume private doxygen would be buggy since it likely wouldn't get tested. I don't know how much that matters though.

We haven't yet developed a doxygen styleguide for TRI (issue #2051). My inclination would be to focus all doxygen use on API user documentation so that developers and reviewers will always know who the reader is supposed to be. But I could be convinced otherwise.

---

*[drake/systems/framework/system_interface.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_cGkSKvwDSZQJZvb:-KLnOBXiJWFLMWhTGiEr:789049434) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/system_interface.h#L72)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> should you add the non-conservative power to this list, too?
</details>
I think power methods only make sense for continuous systems (since power is inherently a derivative), while energy methods are more general. I will discuss this with Paul when he arrives, but I think that at least some discrete systems can still usefully track energy for conservation tests. For example, a rigid impact is a discrete zero-time event that dissipates energy, but it is fairly easy to properly book-keep its losses so we can track energy conservation across impacts.

So for now I put the  virtuals for conservative and non-conservative power in the ContinuousSystemInterface class. As with the energy routines here, this is awkward because these methods should only exist for *physical* systems, but inheritance is a messy way to try to capture all the various combinations of continuous/discrete/hybrid and physical/nonphysical. For now I think it is easier to include the extra methods and give them default values, but ideally these would be pure virtual for physical systems so that anyone claiming to model something physical would have to think about energy conservation. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLnRplA9ZD1eWe2kefW:126951215)*

**Comment by sherm1** [comment]
I missed a couple of your questions.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLnSg3vTe2CZ94Mi-3T:159636205) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> i think the most obvious thing is to have an input which is a horizontal force on the mass (all of our other spring mass examples have this).  that would be a good role for this.  
</details>
Yes, I like that -- basically have wind blowing on the mass. I don't want to do that in this PR because I think it will mess up my integrator tests cases which are currently depending on this being a conservative system (so that energy gains and losses are attributable to the numerical methods). I will add that idea to the TODO.

---

*[drake/examples/spring_mass/test/spring_mass_system_test.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkYXtFle7DyGzX8nSv:-KLnU7aL0uxQTdAV-BgK:-348678148) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/test/spring_mass_system_test.cc#L63)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> is this the recommended way to obtain that in general?  will this call to size() ever return -1 (e.g. for dynamically sized objects)?
</details>
That's a good question. Currently this will always return a good value because the states are fixed-size and have fixed q,v,z partitioning. I think this will have to change somewhat when we add variable-sized states, but that should only occur as a result of an event where the handler changes a mode variable, after which the state will be fixed size again but at a different size. I think that implies that these methods should take the Context as an argument (since that is where the mode variables will live). This is one of the many things yet to be nailed down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLnVxysHjO58YaOoyoU:-1995494051)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLnaCVY4wi4MgFIPt0q:-1891084020) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Yes, I like that -- basically have wind blowing on the mass. I don't want to do that in this PR because I think it will mess up my integrator tests cases which are currently depending on this being a conservative system (so that energy gains and losses are attributable to the numerical methods). I will add that idea to the TODO.
</details>
Suppose an LCM message is used to convey the horizontal force that is applied to the mass. What would this message look like? I will add such a message to #2729.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725)*

**Comment by liangfok** [comment]
BTW, the clang-mac CI failure is being tracked here: https://github.com/RobotLocomotion/drake/issues/2736

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLndHuBSzrgepqFSCll:-1077245900)*

**Comment by sherm1** [comment]
Thanks, Liang -- I wondered about that.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLnhHDDKphK1zS5eOQW:-1394492154) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Suppose an LCM message is used to convey the horizontal force that is applied to the mass. What would this message look like? I will add such a message to #2729.
</details>
I would like to try it first with just another System that outputs wind. Doing it with LCM messages seems like a good idea. I presume you'll need to create another system that outputs LCM wind though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLnh6XSTLCpElIKfVyr:-987848736)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLnm94_gxl6vkl5Vtcw:-1377787767) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I would like to try it first with just another System that outputs wind. Doing it with LCM messages seems like a good idea. I presume you'll need to create another system that outputs LCM wind though.
</details>
OK I will wait for you to finish a "Wind System" that is cascaded with the "Mass Spring System". I will then create LCM Input and Output systems that enable the two to be decoupled across an LCM network. This feature is obviously not strictly necessary. It'll mostly be for demonstration and educational purposes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725)*

**Comment by sherm1** [comment]
Review status: 14 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLo6g0X9nyWr0pPOh8w:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> OK I will wait for you to finish a "Wind System" that is cascaded with the "Mass Spring System". I will then create LCM Input and Output systems that enable the two to be decoupled across an LCM network. This feature is obviously not strictly necessary. It'll mostly be for demonstration and educational purposes.
</details>
Done.

---

*[drake/systems/framework/system_interface.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_cGkSKvwDSZQJZvb:-KLo6OAlEgHzIt7Dz3oc:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/system_interface.h#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I think power methods only make sense for continuous systems (since power is inherently a derivative), while energy methods are more general. I will discuss this with Paul when he arrives, but I think that at least some discrete systems can still usefully track energy for conservation tests. For example, a rigid impact is a discrete zero-time event that dissipates energy, but it is fairly easy to properly book-keep its losses so we can track energy conservation across impacts.
> 
> So for now I put the  virtuals for conservative and non-conservative power in the ContinuousSystemInterface class. As with the energy routines here, this is awkward because these methods should only exist for *physical* systems, but inheritance is a messy way to try to capture all the various combinations of continuous/discrete/hybrid and physical/nonphysical. For now I think it is easier to include the extra methods and give them default values, but ideally these would be pure virtual for physical systems so that anyone claiming to model something physical would have to think about energy conservation. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725)*

**Comment by sherm1** [comment]
I believe I addressed all reviewer comments here and from now-deceased PR #2513. I apologize for any I missed in the latter -- I didn't have the benefit of Reviewable's careful accounting. Although this likely has some controversial changes I am going to merge this soon so I can move forward, with the understanding that there will be many more PRs to come that can revert bad ideas I may have injected here.

---

Review status: 7 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/framework/context.h, line 16 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZYm5AnIEVwfne_l9:-KLsjysdFw5oU74pw7St:-732294499) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L16)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> This is poorly named -- it is intended to hold the current value of the independent variable (time) and a counter or step number that can be used to distinguish multi-valued signals such as occur before and after events (since events occur in zero time both before and after are at the same time). Right now the struct is just a place holder so that we won't be blindsided when we need to carry along some extra information besides just the numerical value of time. I called it TimeStep because it has time and step info but forgot that that phrase has another meaning (dt)! 
> 
> I believe the step number will also be useful for non-forward-dynamics solvers applied to Systems, such as equilibrium analysis and design studies, where there are distinct steps but time doesn't advance.
> 
> I will try to think up a better name for this struct -- any suggestions?
</details>
Done. Renamed `StepInfo` and made access to it private for now.

---

*[drake/systems/framework/context.h, line 156 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkZnkw1rAhE5vASm1m:-KLsk5ybIPlRBZ-xUWEd:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/context.h#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Yes, exactly.
</details>
Done.

---

*[drake/systems/framework/continuous_system_interface.h, line 35 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLslr9cYRJua_ohMKnV:-KLslr9cYRJua_ohMKnW:-489299461) ([raw file](https://github.com/robotlocomotion/drake/blob/914fe5d35411a10065ef2b5336951dc9251661c4/drake/systems/framework/continuous_system_interface.h#L35)):*
> ```objc
>   ///                    state vector Context.state.continuous_state.
>   virtual void EvalTimeDerivatives(const Context<T>& context,
>                                    ContinuousState<T>* derivatives) const = 0;
> ```

BTW, this should return a reference into the cache rather than working in a separate output argument.

---

*[drake/systems/framework/state.h, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_B_80SsCOvwOhA-3:-KLskB7-vlN4VdWR_8yC:-1628515299) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/state.h#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> We already have `EXTRACT_PRIVATE=NO` in Drake's Doxyfile so private comments don't show up either way. My reasons for not wanting these doxygenated are:
> - I have only used doxygen to produce documentation for API users, so I interpret the presence or absence of doxygen comments as information about what is part of the API and what is not. 
> - I worry that developers won't think clearly about the API if they write doxygen for everything -- API documentation is aimed at a different audience. 
> - I know doxygen does have a developer mode, but I don't know how useful it is -- I assume developers can look in the header file and read the comments! 
> - I'd like to be able to write private comments without having to satisfy doxygen's formatting rules.
> - I assume private doxygen would be buggy since it likely wouldn't get tested. I don't know how much that matters though.
> 
> We haven't yet developed a doxygen styleguide for TRI (issue #2051). My inclination would be to focus all doxygen use on API user documentation so that developers and reviewers will always know who the reader is supposed to be. But I could be convinced otherwise.
</details>
Done. Made this consistent at least. Final disposition should depend on doxygen standards we haven't agreed on yet.

---

*[drake/systems/framework/state_vector.h, line 64 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLslJdD3oM137T6-VVX:-KLslJdELsAAiqoN0PFZ:-538146942) ([raw file](https://github.com/robotlocomotion/drake/blob/914fe5d35411a10065ef2b5336951dc9251661c4/drake/systems/framework/state_vector.h#L64)):*
> ```objc
>   /// Implementations should ensure this operation remains O(N) in the size of
>   /// the value and allocates no memory.
>   virtual void ScaleAndAddToVector(const T& scale,
> ```

BTW, these virtuals are not general enough to permit efficient scale-and-add operations on subvectors.

---

*[drake/systems/framework/system_interface.h, line 72 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_cGkSKvwDSZQJZvb:-KLskWah_b-dHaTqoAHe:-648925072) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/system_interface.h#L72)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Done.
</details>
OK (not sure why this wasn't already marked resolved).

---

*[drake/systems/framework/system_interface.h, line 62 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLslaV4O6zwoVDixhy1:-KLslaV4O6zwoVDixhy2:-489299461) ([raw file](https://github.com/robotlocomotion/drake/blob/914fe5d35411a10065ef2b5336951dc9251661c4/drake/systems/framework/system_interface.h#L62)):*
> ```objc
>   /// in the cache.
>   virtual void EvalOutput(const Context<T>& context,
>                           SystemOutput<T>* output) const = 0;
> ```

BTW, this should return a reference into the cache rather than working in a separate output argument.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLskq89P5A7p-YT2yQE:-908032540)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Reviewed 1 of 15 files at r4, 1 of 4 files at r5.
Review status: 9 of 22 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLuS3bJA44pWOIa-6M3:680695959) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Done.
</details>
acknowledged.  fwiw - i wouldn't call it "wind" (that sounds passive).  the spring-mass-damper system often has a control force applied horizontally.

---

*[drake/examples/spring_mass/spring_mass_system.h, line 52 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLuSW9UNL1CrMc9oTMG:-KLuSW9Vf7Y938-lnzNo:1581409100) ([raw file](https://github.com/robotlocomotion/drake/blob/2e4ff55ed274a616c0c041142af1f2e189dfd31f/drake/examples/spring_mass/spring_mass_system.h#L52)):*
> ```objc
> /// The output of a one-dimensional spring-mass system, consisting of the
> /// position and velocity of the mass, in meters. Note that although this
> /// system tracks work done as a state variable, we are not reporting that
> ```

"work done as a state variable" .  i got the other meaning the first time I read this.  how about "has a state variable to track mechanical energy" (or work)

fwiw - i was going to try editing your source in place (to spare you the burden of modifying it), but didn't have write access to your fork.

---

*[drake/examples/spring_mass/test/spring_mass_system_test.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkYXtFle7DyGzX8nSv:-KLuTfXByFA-rTnggduz:1244973840) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/test/spring_mass_system_test.cc#L63)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> That's a good question. Currently this will always return a good value because the states are fixed-size and have fixed q,v,z partitioning. I think this will have to change somewhat when we add variable-sized states, but that should only occur as a result of an event where the handler changes a mode variable, after which the state will be fixed size again but at a different size. I think that implies that these methods should take the Context as an argument (since that is where the mode variables will live). This is one of the many things yet to be nailed down.
</details>
agreed we can nail it down later.  but i'm thinking more about the case of the RigidBodySystem for which the fixed size is not known until runtime.  Will size() return -1 or the size of the currently instantiated system?

---

*[drake/systems/framework/state.h, line 113 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLk_B_80SsCOvwOhA-3:-KLuUaDH47VwQJoDXhuD:-94956010) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/systems/framework/state.h#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Done. Made this consistent at least. Final disposition should depend on doxygen standards we haven't agreed on yet.
</details>
thanks.  i personally find doxygen an extremely useful way to navigate the code as an internal developer, too.  but i absolutely agree on the importance/value of the API being prestine.  a good discussion for the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLuV-lL0icwbBvnntsH:1417088721)*

**Comment by RussTedrake** [comment]
Reviewed 10 of 15 files at r4, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/system_output.h, line 82 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLuViRZW6U8vA2enXzS:-KLuViRZW6U8vA2enXzT:-1953032448) ([raw file](https://github.com/robotlocomotion/drake/blob/46efa232d11f064565ccab804fe518a5536de439/drake/systems/framework/system_output.h#L82)):*
> ```objc
>   OutputPort& operator=(OutputPort&& other) = delete;
> 
>   /// The port data, if the port is vector-valued.
> ```

more (unnecessary) zapping of doxygen.  i'm fine with whichever you pick for now.

---

*[drake/systems/framework/value.h, line 60 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLuVun1kk8bgkf6Oabi:-KLuVun1kk8bgkf6Oabj:-472614533) ([raw file](https://github.com/robotlocomotion/drake/blob/46efa232d11f064565ccab804fe518a5536de439/drake/systems/framework/value.h#L60)):*
> ```objc
> 
>  private:
>   /// Casts this class to a Value<T>*. In Debug builds, throws
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Build is failing on Mac per issue #2736 but that isn't specific to this PR. Will override merge.

---

Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/spring_mass/spring_mass_system.cc, line 105 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkXUyaL1QxTo4Q_QIe:-KLvyqLNJxAos1WQVwLB:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/spring_mass_system.cc#L105)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> acknowledged.  fwiw - i wouldn't call it "wind" (that sounds passive).  the spring-mass-damper system often has a control force applied horizontally.
</details>
Done.

---

*[drake/examples/spring_mass/test/spring_mass_system_test.cc, line 63 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-KLkYXtFle7DyGzX8nSv:-KLvyJJiCFg59ESQfz5J:-166689661) ([raw file](https://github.com/robotlocomotion/drake/blob/5528d7f5d67effffdcf79d607902044ae381d12d/drake/examples/spring_mass/test/spring_mass_system_test.cc#L63)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> agreed we can nail it down later.  but i'm thinking more about the case of the RigidBodySystem for which the fixed size is not known until runtime.  Will size() return -1 or the size of the currently instantiated system?
</details>
BTW, this is just forwarding Eigen's size so will return the currently instantiated size, 0 or larger -- it isn't returning the template argument that would be -1 for dynamic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2725#-:-KLvz1Vs5yWVE-UlAw4d:-420307288)*

**Pull request merged**
