### PR TITLE
pydrake: Add overview to individual modules

### LINKED ISSUE #12655: sphinx documentation for pydrake is missing overview docs
in discussing with some users about why the python documentation is not working well for them, many complain that our sphinx output is just a list of methods, with no apparent organization.  I think that publishing the doxygen pages (e.g. https://drake.mit.edu/doxygen_cxx/index.html#://) to the front of the sphinx pages would go a long way, even if it temporarily has some smatterings of c++ documentation in it like the rest of the pydrake docs.

In the very short term, I think folks would get a lot out of even having a trivial front page for sphinx that points users to the doxygen c++ (and explains that doxygen c++ is the first class citizen, they may want to browse there first).

cc @EricCousineau-TRI

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #12655

Requires:
- [x] #12671

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12670)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
> My only concern is maintainability in terms of avoiding broken links ...

We can (manually or automatically) run a hyperlink checker on the website, to catch any typos here or elsewhere in the tree.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI The feedback on this seems positive -- want to keep pushing it along?  It's been open & idle for several months.

**Comment by EricCousineau-TRI** [comment]
In another week, yeah!

**Comment by jwnimmer-tri** [comment]
Thanks for your interest in contributing to Drake! Since this PR has not received any updates over the past 6+ months, we are closing it automatically. To resume the PR again, you may reopen it with updates (be sure to reopen before you push any changes), or open a new one.

**Pull request closed without merging**
