### PR TITLE
Optitrack LCM translator

### PR DESCRIPTION
**Pull request by naveenoid**
Used to translate optitrack LCM message to an object pose.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6081)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBEFqrfX_uZkfxdov6:-KkBEFqrfX_uZkfxdov7:b-wj29kh) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc#L43)):*
> ```cpp
>     const optitrack::optitrack_frame_t *optitrack_msg) {
> 
>   std::vector<optitrack::optitrack_rigid_body_t> rigid_bodies =
> ```

is this array maximal? if one obj is missing, does optitrack still have that in the array? or will it be omitted? does object_index_ always correspond to the same object? 

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBDepy2tKSLqZ3T5qi:-KkBDepz6mbxN2rR41Ge:bzcizfq) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc#L48)):*
> ```cpp
>   DRAKE_DEMAND(object_index_ < rigid_bodies.size());
>   // The optitrack quaternion ordering is Z-W-X-Y.
>   Eigen::Quaterniond quaternion(
> ```

might want to normalize this. 

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBDqsU67Fuh--Qc_3z:-KkBDqsU67Fuh--Qc_4-:b-mttkqq) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.h#L21)):*
> ```objc
>  *
>  */
> Isometry3<double> DefaultWorldOptitrackTransform();
> ```

could make this a static member of OptitrackPoseTranslator

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6081)*

**Comment by naveenoid** [comment]
Im still racking my head on how to push in suitable demo style gtest of this. The dummy few second demo lcm dataset that @sammy-tri generated for me can easily go into drake however, we dont want gtests with LCM. Is there a way to load an LCM log into mock-lcm? 

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBEFqrfX_uZkfxdov6:-KkFQBNx0EOYC5QfFgXj:b-6hsjr8) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc#L43)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

is this array maximal? if one obj is missing, does optitrack still have that in the array? or will it be omitted? does object_index_ always correspond to the same object? 
</blockquote></details>

From what I can tell from preliminary tests : 
1. Yes its maximal (every model loaded in the software)
2. obj missing - No idea, needs testing : Help! @sammy-tri 
3. object_index_ - AFAICT yes since this depends on the world setup in the optitrack software. So it could change if the world setup file changes..we may later need to move that to version control too somehow. 

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBDepy2tKSLqZ3T5qi:-KkFQZwPgh37tQQLKCmp:b-lvq4mx) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.cc#L48)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

might want to normalize this. 
</blockquote></details>

Good point. will do. 

---

*[drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-KkBDqsU67Fuh--Qc_3z:-KkFQbRti2k2GXuf2DYt:b7asat9) ([raw file](https://github.com/robotlocomotion/drake/blob/03f5ab684f523a8f474552ab8ba433de7d120f84/drake/examples/kuka_iiwa_arm/dev/tools/optitrack_pose_translator.h#L21)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

could make this a static member of OptitrackPoseTranslator
</blockquote></details>

Good point will do. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-:-KkFQdqJMefm_9jM8voL:b4f8fl)*

**Comment by siyuanfeng-tri** [comment]
does this have to live in drake? or spartan? 
this seems border line for serious testing. more dic on the message format is better, otherwise it's pretty trivial. @sammy-tri what do you think.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6081#-:-KkGW8R--2ohXrvVwDPi:basgmsz)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by naveenoid** [comment]
Already resolved in a seperate PR.

**Pull request closed without merging**
