### PR TITLE
pydrake sensors: Add example plotting images from RgbdCamera in matplotlib

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
\cc @naveenoid @kunimatsu-tri 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8585)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@thduynguyen for feature review, please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-:-L9uZqUN7U284AAmSIno:b-iqxeax)*

**Comment by thduynguyen** [comment]
:lgtm: with some minor BTWs.  Please proceed at will.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/systems/test/rgbd_camera_example.py, line 1 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9uiPV99g3jupDPsGeP:-L9uiPV99g3jupDPsGeQ:b24k6oc) ([raw file](https://github.com/robotlocomotion/drake/blob/c683734418e94d7c1824de57d3c5561c7123f921/bindings/pydrake/systems/test/rgbd_camera_example.py#L1)):*
> ```Python
> import matplotlib as mpl
> ```

BTW not really a test. Should it be in some `example` folder?

---

*[bindings/pydrake/systems/test/rgbd_camera_example.py, line 57 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9uiV4K4IHF9XUon6aF:-L9uiV4K4IHF9XUon6aG:bsc2z6b) ([raw file](https://github.com/robotlocomotion/drake/blob/c683734418e94d7c1824de57d3c5561c7123f921/bindings/pydrake/systems/test/rgbd_camera_example.py#L57)):*
> ```Python
> depth_image = output.get_data(depth_index).get_value()
> depth_array = depth_image.data
> ```

BTW lots of (cryptic) steps to just get an image out.  IMO, a helper class/function will be very useful here. That could be because I'm alien to drake.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-:-L9ujQ6N-T6zGV4irXnw:b62jf6r)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/test/rgbd_camera_example.py, line 1 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9uiPV99g3jupDPsGeP:-L9ulswo3XqCslHwbSkP:bc5i8qu) ([raw file](https://github.com/robotlocomotion/drake/blob/c683734418e94d7c1824de57d3c5561c7123f921/bindings/pydrake/systems/test/rgbd_camera_example.py#L1)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW not really a test. Should it be in some `example` folder?
</blockquote></details>

Done. Good point! Moved other example.

---

*[bindings/pydrake/systems/test/rgbd_camera_example.py, line 57 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9uiV4K4IHF9XUon6aF:-L9uk1-eERDV1fT-HBrZ:b-d1kkgv) ([raw file](https://github.com/robotlocomotion/drake/blob/c683734418e94d7c1824de57d3c5561c7123f921/bindings/pydrake/systems/test/rgbd_camera_example.py#L57)):*
<details><summary><i>Previously, thduynguyen (Duy-Nguyen Ta) wrote…</i></summary><blockquote>

BTW lots of (cryptic) steps to just get an image out.  IMO, a helper class/function will be very useful here. That could be because I'm alien to drake.
</blockquote></details>

OK Agreed, but that's kind of along the lines of having more Pythonic access. Filed a separate issue to capture the larger point #8587

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585)*

**Comment by kunimatsu-tri** [comment]
Woo, nice! Thanks Eric!

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-:-L9v6U2Z7-uWNni77yVX:buhuzqd)*

**Comment by peteflorence** [comment]
@EricCousineau-TRI sounds very cool, can you post an example pic? :)

**Comment by EricCousineau-TRI** [comment]
Yup! The scene is simple, but at least shows the working example:
image

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review, please.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-:-L9vRrHZ9zFaElIxawlR:bxwr5c8)*

**Comment by soonho-tri** [comment]
Nice! and :lgtm: (aside two ignorable BTWs and one question about the naming)

---

Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 180 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9w1QPI7mf0Nhd6Qctt:-L9w1QPI7mf0Nhd6Qctu:b75mmp9) ([raw file](https://github.com/robotlocomotion/drake/blob/e71bef5f98ef2cc94a572327a20a5d1a256a8497/bindings/pydrake/multibody/rigid_body_tree_py.cc#L180)):*
> ```cpp
>     })
>     .def("addFrame", &RigidBodyTree<double>::addFrame,
>          py::arg("frame"))
> ```

BTW, nit, it can be fit into a single line:
```c++
      .def("addFrame", &RigidBodyTree<double>::addFrame, py::arg("frame"))
```

---

*[bindings/pydrake/multibody/rigid_body_tree_py.cc, line 251 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-L9w1ZcaAOEtkso8KE88:-L9w1ZcaAOEtkso8KE89:b-ugkc7a) ([raw file](https://github.com/robotlocomotion/drake/blob/e71bef5f98ef2cc94a572327a20a5d1a256a8497/bindings/pydrake/multibody/rigid_body_tree_py.cc#L251)):*
> ```cpp
>     .def("get_name", &RigidBodyFrame<double>::get_name)
>     .def("get_frame_index", &RigidBodyFrame<double>::get_frame_index)
>     .def("get_body", &RigidBodyFrame<double>::get_rigid_body,
> ```

BTW, nit, it can be fit into a single line:
```c++
      .def("get_body", &RigidBodyFrame<double>::get_rigid_body, py_reference,
```

BTW, the name on the python-side `get_body` is different from the one on the C++ side, `get_rigid_body`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585#-:-L9w44_h4dUWsdkxl8fP:b92gb59)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8585)*

**Pull request merged**
