### PR TITLE
Integrates Maliput Railcar Model With Automotive  Demo.

### PR DESCRIPTION
**Pull request by liangfok**
To run a demo, start `drake-visualizer`, then execute:

```
$ bazel run //drake/automotive:automotive_demo -- --num_dragway_lanes=1 --num_trajectory_car=0 --num_maliput_railcar=1 --dragway_base_speed=20
```

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5377)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@jwnimmer-tri for platform and car reviews please.

Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-:-Kgirt-CN6zSjt8ZC5UC:bwywf8w)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 328 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-Kgk61U8BF8rqctDJU15:-Kgk61U8BF8rqctDJU16:b-8oqhbz) ([raw file](https://github.com/robotlocomotion/drake/blob/1aa259eec35ca8402152193dc092962e088e8145/drake/automotive/automotive_simulator.cc#L328)):*
> ```cpp
> // TODO(liang.fok) The following three methods meet the rule-of-three since all
> // of them take a LeafSystem as input and connect their outputs to an
> // LcmPublisherSystem. Factor out the common code into a shared method.
> ```

FYI Even better would be to delete the code we don't want anymore, which includes all of the `*Endless*` and `*Euler*` stuff.

---

*[drake/automotive/README.md, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-Kgk5E6jNhHJ7t52ZgJY:-Kgk5E6jNhHJ7t52ZgJZ:bxk09uo) ([raw file](https://github.com/robotlocomotion/drake/blob/1aa259eec35ca8402152193dc092962e088e8145/drake/automotive/README.md#L84)):*
> ```Markdown
>        --num_trajectory_car=0 \
>        --num_maliput_railcar=1
>    ```
> ```

This is not a very interesting demo..  People can read the `-help` to find what's available -- we don't need to spoon-feed it here unless its acutely interesting.

One solution would be to add a railcar to the prior bullet (which is also a dragway) and remove this block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-:-Kgk6lVLzHiy1ENzMGTk:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/automotive_simulator.cc, line 328 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-Kgk61U8BF8rqctDJU15:-KgkBk4ALSF4QmG69KoU:b-t1h88t) ([raw file](https://github.com/robotlocomotion/drake/blob/1aa259eec35ca8402152193dc092962e088e8145/drake/automotive/automotive_simulator.cc#L328)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Even better would be to delete the code we don't want anymore, which includes all of the `*Endless*` and `*Euler*` stuff.
</blockquote></details>

OK. I simply deleted this TODO comment since your impending refactor will address it.

---

*[drake/automotive/README.md, line 84 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-Kgk5E6jNhHJ7t52ZgJY:-KgkBMeWnnfE70v9UsbY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1aa259eec35ca8402152193dc092962e088e8145/drake/automotive/README.md#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is not a very interesting demo..  People can read the `-help` to find what's available -- we don't need to spoon-feed it here unless its acutely interesting.

One solution would be to add a railcar to the prior bullet (which is also a dragway) and remove this block?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5377)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5377)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5377#-:-KglDBVL1ldgmlzWklye:bnfp4nl)*

**Pull request merged**
