### PR TITLE
Remove Macports and Cygwin installation instructions.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2102)

### CODE REVIEW

**Comment by liangfok** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2102)*

**Comment by jwnimmer-tri** [comment]
Needs a CHANGELOG.md.

**Comment by david-german-tri** [comment]
Done

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2102#-:-KFLP_5_4pynaywQ4WW1:676635175)*

**Comment by david-german-tri** [comment]
MATLAB build timed out, obviously unrelated.  @RussTedrake, OK to zap macports as well as cygwin?

**Comment by RussTedrake** [comment]
yes.  let's zap macports.

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2102#-:-KFduV8AxXHHUVcUoYd2:-1694407121)*

**Pull request merged**
