### PR TITLE
Clique cover solver/stable set mip

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
Towards the solving clique cover step of #20372. 

+@wernerpe  for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-:-Nh2v9BBEySbVKyMG72X:bryovfa)* status: LGTM missing from assignee wernerpe, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Comment by wernerpe** [comment]
I am confused as to why you are setting MOSEK as the default sover for the ILP. Otherwise :lgtm:

**Review by AlexandreAmice — COMMENTED** [review]
Updated to choose best solver

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-:-Nh3jtIA-JifXwtTZLGr:b-avtfa7)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+@EricCousineau-tri for platform review per schedule

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-:-Nh3k1JiEbuLO8ZWE2n9:bc4x8jp)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Review by RussTedrake — COMMENTED** [review]
I think we should get another Drake-calibrated feature review before moving to platform.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-:-Nh4T6379ptKFFi2kKDG:bw5xm1a)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`planning/graph_algorithms/max_stable_set.h` line 20 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4TudC0eE8mGt58D8V:-Nh4TudC0eE8mGt58D8W:b-imdd35) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L20)):*
> ```objc
> 
> /**
>  * The problem of finding the maximum clique in a graph is known to a
> ```

you talk about max stable set and max clique.  i prefer the max clique spelling; i find it more clear.  but the current docs are confusing as to the relationship.
___
*[`planning/graph_algorithms/max_stable_set.h` line 79 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4TjwB3y532ctHJw01:-Nh4TjwB3y532ctHJw02:b-4rjrat) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L79)):*
> ```objc
>  * Given the adjacency matrix of an undirected graph, find the maximum stable
>  * set within the graph. A stable set is a collection of vertices in a graph
>  * such that each no pair of vertices is connected by an edge. This problem is
> ```

"each no pair"
___
*[`planning/graph_algorithms/max_stable_set.h` line 82 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4ToaOCAZQ8Zij_bG7:-Nh4ToaOCAZQ8Zij_bG8:b-ul4acw) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L82)):*
> ```objc
>  * known to be NP-complete, and so the choice of solvers in options determines
>  * whether the return of this function is the true maximum stable set in the
>  * subgraph (which may take very long to compute), or just some large subgraph.
> ```

"just some large subgraph" is not precise.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

___
*[`planning/graph_algorithms/max_stable_set.h` line 20 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4TudC0eE8mGt58D8V:-Nh4egwQ1PjY8zQ4pJ6b:bd8ml9g) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L20)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

you talk about max stable set and max clique.  i prefer the max clique spelling; i find it more clear.  but the current docs are confusing as to the relationship.
</blockquote></details>

That's some copy-pasta. Sorry about that.
___
*[`planning/graph_algorithms/max_stable_set.h` line 79 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4TjwB3y532ctHJw01:-Nh4ejBYDvX9E7rrvEb2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L79)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"each no pair"
</blockquote></details>

Done.
___
*[`planning/graph_algorithms/max_stable_set.h` line 82 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-Nh4ToaOCAZQ8Zij_bG7:-Nh4ejas7R21r1SufHpM:b7nxhxh) ([raw file](https://github.com/RobotLocomotion/drake/blob/3b191070acaa5e023fc280f0a8bdeee33ac0595b/planning/graph_algorithms/max_stable_set.h#L82)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"just some large subgraph" is not precise.
</blockquote></details>

I don't want to promise that every `MaxStableSetSolver` return the true maximum. Is the new documentation better?

**Review by AlexandreAmice — COMMENTED** [review]
+@sadraddini for feature review 2. Thanks

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20395#-:-Nh72td53Pxpv9FomMrp:b-fdqwwj)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sadraddini, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Pull request closed without merging**
