### PR TITLE
Minimum/maximum safety check now performed in IntegratorBase<T>::Init…

### PR DESCRIPTION
**Pull request by edrumwri**
…ialize().

Addresses issue #4339.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4341)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Platform :lgtm: (21 minutes left!).

I assume it will get a proper unit test when the settings logic gets tidied, per the issue discussion.  For now, failing fast even without a backing unit test seems like a fair trade.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 254 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KXxp3tHQSnZ9zRi1j4x:-KXxp3tHQSnZ9zRi1j4y:bufqn3v) ([raw file](https://github.com/robotlocomotion/drake/blob/15c00ca71f556783844e1bfe0c16f134204b0231/drake/systems/analysis/integrator_base.h#L254)):*
> ```objc
>     if (max_step_size < min_step_size)
>       throw std::logic_error("Integrator maximum step size is less than the "
>                              "minimum step size");
> ```

BTW Multi-line if bodies require curly braces, per cppguide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KXxonn4Z3uhPU8muKE5:b-7p3c4f)*

**Comment by edrumwri** [comment]
Now _that_ is a serious dedication to platform reviewing. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KXxr2Vunen1jEOHayOf:b-srzfx)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/analysis/integrator_base.h, line 254 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KXxp3tHQSnZ9zRi1j4x:-KXxr7qnGpKVjRZU2Y0Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/15c00ca71f556783844e1bfe0c16f134204b0231/drake/systems/analysis/integrator_base.h#L254)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Multi-line if bodies require curly braces, per cppguide.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot retest all please

**Comment by RussTedrake** [comment]
thanks!  could we add a similar fast failure when the user requests an initial step size outside the bounds?  that also failed silently.

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/analysis/integrator_base.h, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KXzJ5cAZysKj8pYMOAI:-KXzJ5cAZysKj8pYMOAJ:b-hzcnfz) ([raw file](https://github.com/robotlocomotion/drake/blob/1c20994ae0993544d15c50ab669625a290ac9c90/drake/systems/analysis/integrator_base.h#L255)):*
> ```objc
>       throw std::logic_error("Integrator maximum step size is less than the "
>                              "minimum step size");
>     }
> ```

BTW, what is the guideline regarding when to throw an exception vs. calling `DRAKE_DEMAND()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/analysis/integrator_base.h, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KXzJ5cAZysKj8pYMOAI:-KY-1ED_8IuJC3SNIhrW:b-pos6jn) ([raw file](https://github.com/robotlocomotion/drake/blob/1c20994ae0993544d15c50ab669625a290ac9c90/drake/systems/analysis/integrator_base.h#L255)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, what is the guideline regarding when to throw an exception vs. calling `DRAKE_DEMAND()`?
</blockquote></details>

If you're unit testing the condition, you _must_ use throw (and document that in the API) -- don't unit test assertion failures.  Otherwise, IMO it's generally author's discretion.

(There's some argument against using a manually-written throw if its really verbose for no good reason (e.g., it will never trip), but in this example it's complaining about user-provided settings, so the vertical space used by the throw seems justified.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/analysis/integrator_base.h, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KY-28pxjxdcaMPz7JIu:-KY-28pxjxdcaMPz7JIv:byxn8ft) ([raw file](https://github.com/robotlocomotion/drake/blob/1c20994ae0993544d15c50ab669625a290ac9c90/drake/systems/analysis/integrator_base.h#L245)):*
> ```objc
>    *         weighting matrix coefficients is set to a negative value (this
>    *         check is only performed for integrators that support error
>    *         estimation).
> ```

Please update this documentation to indicate that this exception is also thrown when `max_step_size < min_step_size`.

---

*[drake/systems/analysis/integrator_base.h, line 255 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KXzJ5cAZysKj8pYMOAI:-KY-2VYYepWQEWXFMIdH:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/1c20994ae0993544d15c50ab669625a290ac9c90/drake/systems/analysis/integrator_base.h#L255)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you're unit testing the condition, you _must_ use throw (and document that in the API) -- don't unit test assertion failures.  Otherwise, IMO it's generally author's discretion.

(There's some argument against using a manually-written throw if its really verbose for no good reason (e.g., it will never trip), but in this example it's complaining about user-provided settings, so the vertical space used by the throw seems justified.)
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by edrumwri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 245 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-KY-28pxjxdcaMPz7JIu:-KY-FBmbcY31KXIANblH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1c20994ae0993544d15c50ab669625a290ac9c90/drake/systems/analysis/integrator_base.h#L245)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please update this documentation to indicate that this exception is also thrown when `max_step_size < min_step_size`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by edrumwri** [comment]
Failure test has been added.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KY-FDLE9aFTEmq3maem:bvoeo7d)*

**Comment by sherm1** [comment]
:lgtm: (pending CI)

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KY-HYDbR2jXdNmnphgq:b-lj32db)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KY-IAIfpru2QoH_xm_c:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Comment by sherm1** [comment]
CI failing.

**Comment by edrumwri** [comment]
@drake-jenkins-bot retest all please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341#-:-KY0-dijHio2dpXRMPRz:b-79vxhj)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4341)*

**Pull request merged**
