### PR TITLE
Replace TWIST_SIZE with drake::kTwistSize

### PR DESCRIPTION
**Pull request by david-german-tri**
Makes it possible to remove `#include "drake/util/drakeGeometryUtil.h"` from a number of widely-used header files.  It does still make its way into `RigidBodyTree.h` via `KinematicsCache.h`, but this is progress!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2666)

### CODE REVIEW

**Comment by sherm1** [comment]
Cpplint had some complaints about line length.

**Comment by david-german-tri** [comment]
Done.  Remarkably clean on CI otherwise, so it's now ready for review.  +@jwnimmer-tri for feature and platform (since I'm today's platform reviewer).

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-:-KLMHPoqrQcFM0pd7zs0:-387043370)*

**Comment by jwnimmer-tri** [comment]
Reviewed 21 of 37 files at r1, 15 of 15 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/eigen_types.h, line 41 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMJZbCNUfiw5Dqcku5:-KLMJZbDMNbXKy82eaX5:-415083314) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/common/eigen_types.h#L41)):*
> ```objc
> using AutoDiffXd = Eigen::AutoDiffScalar<Eigen::VectorXd>;
> 
> constexpr int kTwistSize = 6;
> ```

BTW A link to https://en.wikipedia.org/wiki/Screw_theory#Twist would have saved me about 15 seconds here, *shrug*.

---

*[drake/systems/plants/RigidBodyTree.h, line 200 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMQI0qhaOaQxujZQTP:-KLMQI0rsciWLDCsowba:-65578412) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBodyTree.h#L200)):*
> ```objc
> 
>   template <typename Scalar>
>   Eigen::Matrix<Scalar, drake::kTwistSize, Eigen::Dynamic> worldMomentumMatrix(
> ```

BTW Several of these look like drake::TwistMatrix or drake::TwistVector could be used instead?  Fine either way, but wanted to mention it.

Actually, a few methods below *did* change to the new spelling.  In which case, probably all of them should?

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 1064 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMOKuTpvBWMI85lr4x:-KLMOKuUDl1YBkOiRlNO:1436590018) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBodyTreeURDF.cpp#L1064)):*
> ```cpp
>   if (body == nullptr) {
>     throw runtime_error("ERROR: Couldn't find body \"" + body_name +
>                         "\""
> ```

This newline is silly, now.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 6 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMPARHk93DWmPHICVq:-KLMPARHk93DWmPHICVr:705032168) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/QuaternionFloatingJoint.h#L6)):*
> ```objc
> 
> #include "drake/util/drakeGeometryUtil.h"
> #include "drake/util/drakeGradientUtil.h"
> ```

BTW is this new line intentional?

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 33 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMPCGnrr56uN7mjgyk:-KLMPCGo6xpH0moV6Npr:-1496890613) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/QuaternionFloatingJoint.h#L33)):*
> ```objc
>       typename drake::math::Gradient<DerivedMS, Eigen::Dynamic>::type*
>           dmotion_subspace = nullptr) const {
>     motion_subspace.setIdentity(drake::kTwistSize, getNumVelocities());
> ```

Missing `#include` for `eigen_types.h`.

---

*[drake/systems/plants/joints/test/testDrakeJointsmex.cpp, line 8 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRcP7fuIs2gobIDNx:-KLMRcP7fuIs2gobIDNy:1310501556) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/test/testDrakeJointsmex.cpp#L8)):*
> ```cpp
> #include <iostream>
> 
> #include <mex.h>
> ```

See bc15b85 which carefully places these atop the file, in which case this change is a regression.

---

*[drake/systems/plants/joints/test/testDrakeJointsmex.cpp, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRc7Rl73GitN5ASlr:-KLMRc7Rl73GitN5ASls:1310501556) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/test/testDrakeJointsmex.cpp#L9)):*
> ```cpp
> 
> #include <mex.h>
> #include <matrix.h>
> ```

See bc15b85 which carefully places these atop the file, in which case this change is a regression.

---

*[drake/systems/plants/test/compareParsersmex.cpp, line 4 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRUGQ7b3d19Udt9cR:-KLMRUGR6XAVu8-S9nQ9:1310501556) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/test/compareParsersmex.cpp#L4)):*
> ```cpp
> #include <iostream>
> 
> #include <mex.h>
> ```

See bc15b85 which carefully places these atop the file, in which case this change is a regression.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666)*

**Comment by david-german-tri** [comment]
Review status: 31 of 37 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/eigen_types.h, line 41 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMJZbCNUfiw5Dqcku5:-KLMZpZ6STCrSWZhWN8Z:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/common/eigen_types.h#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW A link to https://en.wikipedia.org/wiki/Screw_theory#Twist would have saved me about 15 seconds here, *shrug*.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 200 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMQI0qhaOaQxujZQTP:-KLM_8UKljHdr5HS-p3O:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBodyTree.h#L200)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Several of these look like drake::TwistMatrix or drake::TwistVector could be used instead?  Fine either way, but wanted to mention it.
> 
> Actually, a few methods below *did* change to the new spelling.  In which case, probably all of them should?
</details>
Done.

---

*[drake/systems/plants/RigidBodyTreeURDF.cpp, line 1064 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMOKuTpvBWMI85lr4x:-KLM_IEDMY0OJjRoFRZ-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBodyTreeURDF.cpp#L1064)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This newline is silly, now.
</details>
Done.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 6 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMPARHk93DWmPHICVq:-KLM_W1DtwGimtUOaOSn:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/QuaternionFloatingJoint.h#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW is this new line intentional?
</details>
Done.

---

*[drake/systems/plants/joints/QuaternionFloatingJoint.h, line 33 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMPCGnrr56uN7mjgyk:-KLM_YeZTRj6bLa5Fu6v:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/QuaternionFloatingJoint.h#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing `#include` for `eigen_types.h`.
</details>
Done.

---

*[drake/systems/plants/joints/test/testDrakeJointsmex.cpp, line 8 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRcP7fuIs2gobIDNx:-KLM_oGFOOan0c5-3i6W:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/test/testDrakeJointsmex.cpp#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> See bc15b85 which carefully places these atop the file, in which case this change is a regression.
</details>
Done.

---

*[drake/systems/plants/joints/test/testDrakeJointsmex.cpp, line 9 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRc7Rl73GitN5ASlr:-KLM_ocOQP5XEctgDuyw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/joints/test/testDrakeJointsmex.cpp#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> See bc15b85 which carefully places these atop the file, in which case this change is a regression.
</details>
Done.

---

*[drake/systems/plants/test/compareParsersmex.cpp, line 4 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMRUGQ7b3d19Udt9cR:-KLM_vZ2YWHb9LD0EqKI:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/test/compareParsersmex.cpp#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> See bc15b85 which carefully places these atop the file, in which case this change is a regression.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-:-KLMctg3x9d1HGMBlf_q:1417088721)*

**Comment by liangfok** [comment]
Just did a quick pass of this PR. Left one non-blocking comment.

---

Reviewed 19 of 37 files at r1, 12 of 15 files at r2, 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/plants/RigidBody.cpp, line 5 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMdzSWWSwMoCRRE_lh:-KLMdzSXlQN82gSZY-RX:1632305052) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBody.cpp#L5)):*
> ```cpp
> #include <stdexcept>
> 
> #include "drake/util/drakeGeometryUtil.h"
> ```

BTW, is the above include needed? `drake::SquareTwistMatrix<double>` appears defined in `drake/common/eigen_types.h`, which is already included in `RigidBody.h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-:-KLMflDYbTZMK5Ee_QDl:717991169)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/RigidBody.cpp, line 5 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-KLMdzSWWSwMoCRRE_lh:-KLMgixZgcDtTwDuK-8c:449186083) ([raw file](https://github.com/robotlocomotion/drake/blob/6e736749a22b77b3aadfbf3f71693c7339efb5a3/drake/systems/plants/RigidBody.cpp#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, is the above include needed? `drake::SquareTwistMatrix<double>` appears defined in `drake/common/eigen_types.h`, which is already included in `RigidBody.h`.
</details>
Unfortunately, yes.  It's for `transformSpatialInertia` (and possibly one or two other functions).  I look forward to deleting it again ASAP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-:-KLMh_PbW-0u8Yt3BYb7:-1868698381)*

**Comment by david-german-tri** [comment]
I'm going to merge this without waiting for the Mac build to schedule, because it looks like #2633 has recurred.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2666#-:-KLMj5fsc2M-Dg3cy7Pf:-276074914)*

**Pull request merged**
