### PR TITLE
Remove remaining Windows-specific CMake and preprocessor code

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4201)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4201#-KX7qfJ-3VOuDoaqWAiH:-KX7qfJ-3VOuDoaqWAiI:b-t27exz) ([raw file](https://github.com/robotlocomotion/drake/blob/c5b81a812a23d0daa351a6bfc89e53ea62738b1f/cmake/options.cmake#L233)):*
> ```CMake
> 
> 
>   drake_optional_external(DIRECTOR ON
> ```

Consider re-alphabetizing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4201#-:-KX7r8Sng1drBGRw8Qqd:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/options.cmake, line 233 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4201#-KX7qfJ-3VOuDoaqWAiH:-KX7tohPXtT0E7UtJPpV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c5b81a812a23d0daa351a6bfc89e53ea62738b1f/cmake/options.cmake#L233)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Consider re-alphabetizing?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4201)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
:lgtm: thanks!

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4201#-:-KX7uPAH66nHGhDDvlzE:brfqlux)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Pull request merged**
