### PR TITLE
[geometry] Select output format from mesh_plane_intersection in hydroelastics.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Support Part II of the [development plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123). This PR for mesh_plane_intersection is similar to PR #15131 for mesh_intersection.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for feature review please.

Most of the changes are in the unit tests. Please let me know if there's anything I can do to make the review easier.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310#-:-MdyGobE3Uq0rcrk4lSU:btk839x)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310#-:-Me0imja1FSPCWNdlR-a:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @DamrongGuoy)

___
*[geometry/proximity/mesh_plane_intersection.h, line 57 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me0GkHWDVbcMT9ihgXP:-Me0GkHXAlHAz-J-rtCD:bc5341b) ([raw file](https://github.com/robotlocomotion/drake/blob/789ae895d3d174b9c6838a4e8896daaafd04a41b/geometry/proximity/mesh_plane_intersection.h#L57)):*
> ```objc
>  choice produces 3 or 4 times fewer triangles than the other choice by
>  representing the intersected polygon as one triangle. However, it does not
>  guarantee unique vertices and ignores `cut_edges` parameter.
> ```

nit: s/ignores cut_edges/ignores the cut_edges/
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 206 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me0hvPk0uG5wWtw90Gc:-Me0hvPk0uG5wWtw90Gd:b-ij37zt) ([raw file](https://github.com/robotlocomotion/drake/blob/789ae895d3d174b9c6838a4e8896daaafd04a41b/geometry/proximity/test/mesh_plane_intersection_test.cc#L206)):*
> ```cpp
>     switch (representation_) {
>       case ContactPolygonRepresentation::kCentroidSubdivision:
>         num_verts = num_faces == 0 ? 0 : num_faces + 1; break;
> ```

BTW I don't know that the style guide strictly prohibits this, but I certainly prefer the `break` on its own line -- makes it clearer what the actual code of the branch is.

**Review by DamrongGuoy — COMMENTED** [review]
+@soonho-tri for platform review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310#-:-Me1-arV3mcKEJQMLdLR:b-vt9vbo)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[geometry/proximity/mesh_plane_intersection.h, line 57 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me0GkHWDVbcMT9ihgXP:-Me0zT_M89rIbJnxFn-E:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/789ae895d3d174b9c6838a4e8896daaafd04a41b/geometry/proximity/mesh_plane_intersection.h#L57)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit: s/ignores cut_edges/ignores the cut_edges/
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/mesh_plane_intersection_test.cc, line 206 at r4](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me0hvPk0uG5wWtw90Gc:-Me0zfKvCYWB13zcAuf-:b7lvsf9) ([raw file](https://github.com/robotlocomotion/drake/blob/789ae895d3d174b9c6838a4e8896daaafd04a41b/geometry/proximity/test/mesh_plane_intersection_test.cc#L206)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW I don't know that the style guide strictly prohibits this, but I certainly prefer the `break` on its own line -- makes it clearer what the actual code of the branch is.
</blockquote></details>

Done. The `break` is on its own line now. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310#-:-Me1VWyh0RJODkCh8pto:bnfp4nl)* status: 1 unresolved discussion (waiting on @DamrongGuoy)

___
*[geometry/proximity/mesh_plane_intersection.h, line 108 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me1LtPNBt7JkuRy7Nuy:-Me1LtPNBt7JkuRy7Nuz:b-uzi8ck) ([raw file](https://github.com/robotlocomotion/drake/blob/be554eefe7fbd2e31453bccb6ffa75487af48c9e/geometry/proximity/mesh_plane_intersection.h#L108)):*
> ```objc
>  @param[in] plane_M         The plane to intersect against the tetrahedra;
>                             measured and expressed in the same frame M.
>  @param[in] tet_indces      Indices for the tetrahedra in mesh_M to test against
> ```

nit, `tet_indces` => `tet_indices`

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform) (waiting on @rpoyner-tri and @soonho-tri)

___
*[geometry/proximity/mesh_plane_intersection.h, line 108 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15310#-Me1LtPNBt7JkuRy7Nuy:-Me1h-9d-LzXnxEz6mVQ:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/be554eefe7fbd2e31453bccb6ffa75487af48c9e/geometry/proximity/mesh_plane_intersection.h#L108)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `tet_indces` => `tet_indices`
</blockquote></details>

Done. Thanks.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15310)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),soonho-tri(platform) (waiting on @DamrongGuoy)

**Pull request merged**
