### PR TITLE
dynamic_programming_test: Increase test timeout

### LINKED ISSUE #8858: `dynamic_programming_test` frequently times out on CI
Capturing prior discussions about CI failures for this test:

> betsymcphail [12:50 PM]
> Summary of recent mystery timeouts Nightly or Continuous
> 
> *systems/controllers:dynamic_programming_test*
> 22 - linux-xenial-clang-bazel-nightly-snopt-debug,     linux-xenial-clang-bazel-nightly-cache-debug
> 21 - linux-xenial-clang-bazel-experimental-memcheck-lsan-debug
> 18 - linux-xenial-clang-bazel-nightly-cache-debug
> 17 - linux-xenial-gcc-bazel-nightly-mosek-debug 
> 16 - linux-xenial-clang-bazel-continuous-mosek-debug

\cc @avalenzu @BetsyMcPhail

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #8858

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8859)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
If the test still times out, then there is a small chance it might be possibly due to odd circumstances of `CallMatlab` blocking. (The test takes 30s on my machine, so it's a tad surprising that it times out on CI.)

+@avalenzu for feature review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8859#-:-LDCHS9r1dTcneKPwnZa:bhd4wov)*

**Comment by avalenzu** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8859#-:-LDCvA2sDs1o_5EkqCFn:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@SeanCurtis-TRI for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8859#-:-LDDB68k-8VNlSDcA0vT:b-q8kqhl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8859#-:-LDDWXGB7JnakK8FzMDi:bmxilld)*

**Pull request merged**
