### PR TITLE
Remove MultibodyTreeContext step 1: split up multibody_tree.h

### PR DESCRIPTION
**Pull request by sherm1**
This is the first step towards getting rid of MultibodyTreeContext, which at this point adds only knowledge of whether the kinematic state variables are continuous or discrete. MultibodyTree alone can provide that information to its subcomponents, but only if some untangling occurs first.

This PR moves multibody_tree.h definitions that depend on element declarations to multibody_tree-inl.h.
That avoids circular header inclusion while still providing the necessary inlining for speed. Existing places that need definitions are updated. Removed the separate forward declaration header which isn't needed now.

MultibodyTreeContext's is_state_discrete() method is removed so there are no direct dependencies on that now. However, there are still indirect dependencies through other MBTreeContext methods. Those will be removed in the next PR. Some opportunistic fixes to recently-out-of-date comments are here too.

Relates #10572

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10569)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Is there a tracking issue for this ?(perhaps higher-level, where this is a checkbox)? If not, can we create one?

**Comment by avalenzu** [comment]
___
*[multibody/tree/multibody_tree.h, line 41 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10569#-LXtrZuJ4GZDsvolzZmr:-LXtrZuJ4GZDsvolzZms:b-bgfsiu) ([raw file](https://github.com/robotlocomotion/drake/blob/6b88128711138ae9c323fd0439d71a937ca8a96a/multibody/tree/multibody_tree.h#L41)):*
> ```objc
> template <typename T> class JointActuator;
> template <typename T> class ForceElement;
> template <typename T> class UniformGravityFieldElement;
> ```

Forgive me if I've missed this in a previous conversation, but what's the justification for violating the [Forward Declarations](https://drake.mit.edu/styleguide/cppguide.html#Forward_Declarations) portion of the style guide here?

**Comment by avalenzu** [comment]
___
*[multibody/tree/multibody_tree.h, line 41 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10569#-LXtrZuJ4GZDsvolzZmr:-LXtx_Zh6CuKlRLBNYWX:b-b47e) ([raw file](https://github.com/robotlocomotion/drake/blob/6b88128711138ae9c323fd0439d71a937ca8a96a/multibody/tree/multibody_tree.h#L41)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Forgive me if I've missed this in a previous conversation, but what's the justification for violating the [Forward Declarations](https://drake.mit.edu/styleguide/cppguide.html#Forward_Declarations) portion of the style guide here?
</blockquote></details>

Sorry, to clarify my previous statement, I'm not looking for a justification in the code, a reply to this thread is enough for me.

**Comment by jwnimmer-tri** [comment]
> > Forgive me if I've missed this in a previous conversation, but what's the justification for violating the [Forward Declarations](https://drake.mit.edu/styleguide/cppguide.html#Forward_Declarations) portion of the style guide here?
>
> The MultibodyTree and the MBElements it contains are all part of the same project. Prior to this PR the element header files were included in the MBTree header, preventing the elements from accessing MBTree services (since they weren't allowed to include anything from multibody_tree.h). Forward declarations are necessary here in order to short circuit circular dependencies while still allowing methods to be inlined (we're trying to improve MBTree performance so converting to virtuals is not an option).

That's fine, but now we've abused using-code to be exposed to brittle forward declarations.  If we have have circular dependencies that require forward declaration games, we should isolate that to private headers.  The thing which out-of-package code includes (`tree/multibody_tree_system.h`) should have _all_ of the body / frame / joint etc. forward declarations already fully defined.

**Comment by sherm1** [comment]
> That's fine, but now we've abused using-code to be exposed to brittle forward declarations. If we must have circular dependencies that require forward declaration games, we should isolate that to private headers.

All the multibody_tree stuff is internal now, so end users will include `multibody_plant.h` which does have all the definitions. Do you think that's insufficient?

**Comment by jwnimmer-tri** [comment]
It means that when someone like myself goes to adjust pydrake or multibody_plant or some unit tests, the bees some out and sting me.  I ended up including `multibody_tree-inl.h` just to stop them.  I just think there's no value in keeping the loose ends loose -- why not add a pile of include statements to multibody_tree_system.h (or whatever is the most sensible, within-package nexus) and call it good?

**Comment by sherm1** [comment]
Certainly no objection from me to this idea -- but I don't have a good sense of the use case where the current setup is problematic. Please feel free to fix or make an issue with a specific request.

**Pull request merged**
