### PR TITLE
[planning] Switch CollisionChecker and VisibilityGraph to use CRU parfor API

### PR DESCRIPTION
**Pull request by calderpg-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528)

### CODE REVIEW

**Comment by calderpg-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please

**Comment by calderpg-tri** [comment]
Changes `CollisionChecker` and `VisibilityGraph` to use the CRU unified parallel-for-loop API, so that parallelized loops can be performed with both OpenMP (preferred) or `std::async` (fallback).

+@jwnimmer-tri for review, thanks!

**Comment by jwnimmer-tri** [comment]
For something as fundamental as the par-for abstraction that will be used pervasively across all of Drake, I am skeptical of asking Drake's developers to try to learn and use a bespoke API that's not part of Drake's codebase, nor subject to Drake's development process, coding conventions, community ownership, etc.

Should I be viewing this PR as a stop-gap to unblock some downstream feature work (e.g., getting the `bool parallelize` out of the way, by fixing some signatures to use `Parallelism` instead)?  If so, I can set aside that concern for now.

On the other hand, if this PR is proposing that Drake adopt the CRU headers for our par-for substrate long term, then I'll need to take a more reflective approach to decide how to review it.

**Review by calderpg-tri — COMMENTED** [review]
I view this mostly as an immediate change to decouple parallel operations in `planning` from OpenMP plus `bool parallelize` cleanup, with Drake presumably having its own par-for abstraction/sugar in the future.

(That said, I do think Drake and CRU will want abstractions that behave similarly, so significant concerns about the interface should be raised)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-:-NjLo7hj7xhYaU-5yWNK:b-h1ynkk)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`tools/workspace/common_robotics_utilities/repository.bzl` line 8 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjLpwwG1oMpe28og602:-NjLpwwG1oMpe28og603:b-m7nujn) ([raw file](https://github.com/RobotLocomotion/drake/blob/d46dce821ef39b053703e26140665615ab9ed15c/tools/workspace/common_robotics_utilities/repository.bzl#L8)):*
> ```Starlark
>     github_archive(
>         name = name,
>         repository = "calderpg/common_robotics_utilities",
> ```

Working return to TRI mirror once CRU#73 lands
___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 8 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjLq4ZK4aGuR1VZovGE:-NjLq4ZK4aGuR1VZovGF:b-mmijuo) ([raw file](https://github.com/RobotLocomotion/drake/blob/d46dce821ef39b053703e26140665615ab9ed15c/tools/workspace/voxelized_geometry_tools/repository.bzl#L8)):*
> ```Starlark
>     github_archive(
>         name = name,
>         repository = "calderpg/voxelized_geometry_tools",
> ```

Working return to TRI mirror once VGT#51 lands

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.  The gist of the API seems plausible.  I'll spend more time looking at the Drake API later once we have it in this tree.

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-:-NjOYFpLAQ4GbVWLF7lo:b2l8dk2)* status: 8 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOWpRZ4JdnssiMhqGq):*
nit In the ultimate commit message, we will need these two lines in the commit body (for the release notes):

Upgrade common_robotics_utilities to latest commit.
Upgrade voxelized_geometry_tools to latest commit.
___
*[`planning/collision_checker.cc` line 571 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOXWBS69Dypgm6Fq6z:-NjOXWBS69Dypgm6Fq7-:b-ear3yw) ([raw file](https://github.com/RobotLocomotion/drake/blob/92bc99ebd35012107a5254fbe2415930e1a11f08/planning/collision_checker.cc#L571)):*
> ```cpp
> 
>   const auto config_work = [&](const int thread_num, const int64_t index) {
>     collision_checks.at(static_cast<size_t>(index)) =
> ```

BTW For my money, this cast as well as the one on the next line both harm (rather than help) readability.  The implicit conversions already do the obvious (and equivalent) thing.  We can express the algorithm without all of this extra punctuation:

```c++
    collision_checks.at(index) =
        CheckConfigCollisionFree(configs.at(index), thread_num);
```
___
*[`planning/collision_checker.cc` line 573 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOXNNS6g3vgLRBQhj5:-NjOXNNTAqJysHkyHRHT:b5dsq17) ([raw file](https://github.com/RobotLocomotion/drake/blob/92bc99ebd35012107a5254fbe2415930e1a11f08/planning/collision_checker.cc#L573)):*
> ```cpp
>     collision_checks.at(static_cast<size_t>(index)) =
>         static_cast<uint8_t>(CheckConfigCollisionFree(
>             configs.at(static_cast<int64_t>(index)), thread_num));
> ```

nit This cast specifically is a no-op.



_Code quote:_
```cpp
static_cast<int64_t>(index)
```
___
*[`planning/collision_checker.cc` line 760 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOZHMY4Xvph0NXSc11:-NjOZHMZ--wEEoFpyH0i:b3xnit2) ([raw file](https://github.com/RobotLocomotion/drake/blob/92bc99ebd35012107a5254fbe2415930e1a11f08/planning/collision_checker.cc#L760)):*
> ```cpp
>   const auto edge_work = [&](const int thread_num, const int64_t index) {
>     const std::pair<Eigen::VectorXd, Eigen::VectorXd>& edge =
>         edges.at(static_cast<size_t>(index));
> ```

BTW Ditto on all of these casts.
___
*[`planning/collision_checker.cc` line 864 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOZNy513_tAlVf3AHU:-NjOZNy513_tAlVf3AHV:b-lykz3w) ([raw file](https://github.com/RobotLocomotion/drake/blob/92bc99ebd35012107a5254fbe2415930e1a11f08/planning/collision_checker.cc#L864)):*
> ```cpp
>   const auto edge_work = [&](const int thread_num, const int64_t index) {
>     const std::pair<Eigen::VectorXd, Eigen::VectorXd>& edge =
>         edges.at(static_cast<size_t>(index));
> ```

BTW Ditto.
___
*[`planning/visibility_graph.cc` line 143 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjOWLx99-IHDhFZf4z2:-NjOWLxAAC3bneTatiZY:b-y25rhu) ([raw file](https://github.com/RobotLocomotion/drake/blob/92bc99ebd35012107a5254fbe2415930e1a11f08/planning/visibility_graph.cc#L143)):*
> ```cpp
> 
>   const auto edge_check_work = [&](const int thread_num, const int64_t i) {
>     if (points_free[i] > 0) {
> ```

nit This would read more clearly (require fewer casts) if we immediately dropped the 64-bit down to 32, for example:



_Suggestion:_
```cpp
  const auto edge_check_work = [&](const int thread_num, const int64_t index) {
    const int i = static_cast<int>(index);
    if (points_free[i] > 0) {
```

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

___
*[`tools/workspace/common_robotics_utilities/repository.bzl` line 8 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjLpwwG1oMpe28og602:-NjP0IiU71lklg8Zn4RY:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d46dce821ef39b053703e26140665615ab9ed15c/tools/workspace/common_robotics_utilities/repository.bzl#L8)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Working return to TRI mirror once CRU#73 lands
</blockquote></details>

Done.
___
*[`tools/workspace/voxelized_geometry_tools/repository.bzl` line 8 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-NjLq4ZK4aGuR1VZovGE:-NjP0KC36EQV5fxCpBJ-:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d46dce821ef39b053703e26140665615ab9ed15c/tools/workspace/voxelized_geometry_tools/repository.bzl#L8)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Working return to TRI mirror once VGT#51 lands
</blockquote></details>

Done.

**Review by calderpg-tri — COMMENTED** [review]
+@EricCousineau-tri for platform review, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-:-NjP0c8S-e6OXvXVv9KL:b9w87cf)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528)* status: LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20528#-:-NjPcNVA7NWrVvgAtY5k:bcpz082)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @calderpg-tri)

**Pull request merged**
