### PR TITLE
[sensors] Add output_delay and capture_offset to CameraConfig

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
\CC @SeanCurtis-TRI FYI

Towards #19437.  Requires #19899 (will rebase).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
From #19863:

> I presume we'll never actually instantiate a RgbdSensorDiscrete, because that's just an async camera with a zero delay, yes?

The `RgbdSensorAsync` requires a strictly positive `output_delay`.

Currently, I don't see a good way to declare a `RgbdSensorDiscrete` in `CameraConfig`, anyway.  At the moment (when `output_delay` is zero), we rely solely on the `LcmPublisherSystem` to determine the image period.  The sensor is always a continuous time `RgbdSensor`; if anyone else connects to its image ports, they will get continuous-time images.

Once we fix the framework / simulator to handle concurrent publish/update events correctly, then we could image _always_ using a discrete sensor.  But until that's fixed, I don't know of any good middle ground.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've only reviewed the `camera_config*` family of things in this PR. After `LcmPublisherSystem` updates in the other PR and this rebases, I'll see if I glossed over any shrapnel outside of that ecosystem.

:LGTM:

> Reviewed 1 of 3 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-:-NajJ9Xa3YC8NTiRebDe:b-mu4dmi)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`systems/sensors/camera_config.h` line 298 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-NajLKFk2ZXtteAE0tWa:-NajLKFk2ZXtteAE0tWb:b-tongbx) ([raw file](https://github.com/RobotLocomotion/drake/blob/5590ed4ed70ce823eb302057871a7a3a2749f975/systems/sensors/camera_config.h#L298)):*
> ```objc
>    @pre capture_offset is finite and non-negative.
>    @warning This is currently only supported when output_delay is non-zero.
>    We intend to remove this restriction in the future. */
> ```

nit: I'm not sure this phrase successfully suggests that a non-zero value (paired with a zero output_delay) will actually throw. The behavior for "unsupported" fields is ambiguous. I think it should be a bit more obvious, that it'll throw.



_Suggestion:_
```objc
   @throws if `capture_offset` is non-zero when `output_delay` is zero, when
           applying this config. We intend to remove this restriction in the
           future. */
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 7 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`systems/sensors/camera_config.h` line 298 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-NajLKFk2ZXtteAE0tWa:-NanVm4DDI4rlLlt78-Q:b53tqq4) ([raw file](https://github.com/RobotLocomotion/drake/blob/5590ed4ed70ce823eb302057871a7a3a2749f975/systems/sensors/camera_config.h#L298)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'm not sure this phrase successfully suggests that a non-zero value (paired with a zero output_delay) will actually throw. The behavior for "unsupported" fields is ambiguous. I think it should be a bit more obvious, that it'll throw.
</blockquote></details>

That works too.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 9 files at r4, 6 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-:-Nar8JY4E8rJAdxR9y3S:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-Nar8GJoAHHyGkKMMgyf:-Nar8GJoAHHyGkKMMgyg:bcuq62r) (no related file):*
Temporary block to let @SeanCurtis-TRI have a final pass of review.

___

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one suggestion

> Reviewed 2 of 9 files at r4, 6 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-:-Nas5zoN7qSyjFh3DU4l:b-g6fn90)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`systems/sensors/camera_config_functions.cc` line 161 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-Nas42ww801_LnPGvlGR:-Nas42ww801_LnPGvlGS:bsaf8ip) ([raw file](https://github.com/RobotLocomotion/drake/blob/3aeb1427beefb9ee0ddfc8630c4f8202dd97a3e3/systems/sensors/camera_config_functions.cc#L161)):*
> ```cpp
>         config.depth ? std::optional<DepthRenderCamera>{depth_camera}
>                      : std::nullopt,
>         render_label_image);
> ```

BTW this would read easier as `dont_render_label_image`

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898)* status: 1 unresolved discussion, needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`systems/sensors/camera_config.h` line 300 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-NasXr7X6iZ8_4AZjHz3:-NasXr7X6iZ8_4AZjHz4:by13ve7) ([raw file](https://github.com/RobotLocomotion/drake/blob/201aa636570197801d2ab66030871066afb8693c/systems/sensors/camera_config.h#L300)):*
> ```objc
> 
>   /** Delay (in seconds) between when the scene graph geometry is "captured"
>    and when the output image is published. Refer to the the RgbdSensorAsync
> ```

Ha! I can't believe I missed all of the "the the"s.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI (Hmmmm...I never got assigned.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19898#-:-NasY7YZEB9KGWGPIt8J:b-bapk45)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
