### PR TITLE
[pydrake] Bind all C++ message type serializers

### LINKED ISSUE #16022: Bind all message serializers for all Drake LCM types
At the moment, only very few of Drake's LCM messages can be used from Python via the LcmPublisherSystem; in particular, only those that are bound here:

https://github.com/RobotLocomotion/drake/blob/6ea3f08c43846d848f3be1c6c66e3dd87bb60355/bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc#L17-L27

We should bind _all_ of Drake's LCM message types there, so that pydrake is not missing access to important C++ features, e.g. publishing point clouds.

Ideally, we also have a unit test cross-check that all of our defined messages appear in that list, so that we'll remember to add new bindings anytime we add new messages.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #16022.

See [slack thread for consensus of binding all types](https://app.slack.com/client/T0JNB2DS4/C3YB3EV5W/thread/C3YB3EV5W-1635778071.011600).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)* status: 1 unresolved discussion, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16026#-MnVy6YEAw1jf31OOlmj:-MnW4ozm2tZvgtjb3nC0:b-lvhl2c) ([raw file](https://github.com/robotlocomotion/drake/blob/3b4fb8aa9f3faefb1d8073acdb40feeb23f9140f/bindings/pydrake/systems/test/lcm_test.py#L95)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Could you elaborate on this test? As I meander through the code, there's something very opaque taking place.

My initial impression is that the *only* mechanism via which the lcm type gets registered, simultaneously binds a serializer. However, it's equally unclear to me that it *actually* binds the lcm message. And further digging did not reveal to me what mechanism causes the type to be bound.

Ultimately, this test implies that an lcm type can be bound (i.e., it appears in the `drake` module), but its serializer doesn't.

Is this obvious to someone more deeply versed with how the bindings work? Do I represent a category of developer that should be able to make sense of this test? And, if so, what information am I missing that would help me actually appreciate what this test achieves?

</blockquote></details>

Done.

(It would help if the overview comment wasn't a complete lie!)

The unit test was checking the most direct binding, but I've added a cross-check of the acceptance condition, in addition to implementation of the binding, for extra clarity.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16026#-MnVy6YEAw1jf31OOlmj:-MnW78YT4ZW9XlUXfTyT:bvbpt5u) ([raw file](https://github.com/robotlocomotion/drake/blob/3b4fb8aa9f3faefb1d8073acdb40feeb23f9140f/bindings/pydrake/systems/test/lcm_test.py#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

(It would help if the overview comment wasn't a complete lie!)

The unit test was checking the most direct binding, but I've added a cross-check of the acceptance condition, in addition to implementation of the binding, for extra clarity.
</blockquote></details>

I like this more, but it doesn't clarify my core confusion.

We're asking `pypdrake` for a list of message types. Under what circumstances would `pydrake` know about an lcm type that doesn't pass the acceptance criteria given here?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)* status: 1 unresolved discussion, missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16026#-MnVy6YEAw1jf31OOlmj:-MnW7m-DEFpG5lWQXcu-:behf021) ([raw file](https://github.com/robotlocomotion/drake/blob/3b4fb8aa9f3faefb1d8073acdb40feeb23f9140f/bindings/pydrake/systems/test/lcm_test.py#L95)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I like this more, but it doesn't clarify my core confusion.

We're asking `pypdrake` for a list of message types. Under what circumstances would `pydrake` know about an lcm type that doesn't pass the acceptance criteria given here?
</blockquote></details>

Let me try to explain in this thread, and then once we sort it out I'll turn that into a code comment.

The file that we are iterating over via `dir()` on the next line is `drake/__init__.py`.

It's contents looks like this:

```python
"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from .experimental_lcmt_deformable_tri import experimental_lcmt_deformable_tri
from .experimental_lcmt_deformable_tri_mesh_init import experimental_lcmt_deformable_tri_mesh_init
from .experimental_lcmt_deformable_tri_mesh_update import experimental_lcmt_deformable_tri_mesh_update
from .experimental_lcmt_deformable_tri_meshes_init import experimental_lcmt_deformable_tri_meshes_init
from .experimental_lcmt_deformable_tri_meshes_update import experimental_lcmt_deformable_tri_meshes_update
from .lcmt_acrobot_u import lcmt_acrobot_u
from .lcmt_acrobot_x import lcmt_acrobot_x
from .lcmt_acrobot_y import lcmt_acrobot_y
... etc ...
```

This is the full list of Drake LCM messages that are known to Python.  The goal of the test is to check that they are also known to `LcmPublisherSystem`.

The list of messages  that appear in that `__init__` file comes from the BUILD rule here:

https://github.com/RobotLocomotion/drake/blob/e36042817b0ecbbe9527db71207c004d3e77e350/lcmtypes/BUILD.bazel#L281-L288

... where `ALL_LCM_SRCS` matches a glob of every file in the lcmtypes folder:

https://github.com/RobotLocomotion/drake/blob/e36042817b0ecbbe9527db71207c004d3e77e350/lcmtypes/BUILD.bazel#L33

Thus, we achieve the invariant that all of Drake's LCM messages are known to `LcmPublisherSystem`.

(1) Does this help clear things up? 

(2) If so, can you help point me to which part(s) of that to highlight in a comment, and/or provide some sample comment text?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)* status: 1 unresolved discussion, missing label for release notes (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/test/lcm_test.py, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16026#-MnVy6YEAw1jf31OOlmj:-MnWDbkW-wmTJmtrUtlz:b-w0woyv) ([raw file](https://github.com/robotlocomotion/drake/blob/3b4fb8aa9f3faefb1d8073acdb40feeb23f9140f/bindings/pydrake/systems/test/lcm_test.py#L95)):*
This was *immensely* helpful. I couldn't find that in the source (for obvious reasons). I think that a small piece of documentation on the test would help direct future readers in the right direction. What do you think of the following?

> Confirms that all lcm types automatically bound by `drake_lcm_py_library` in `drake/lcmtypes/BUILD.bazel` are partnered with the definition of a C++ serializer in `lcm_py_bind_cpp_serializers.cc`.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026)* status: missing label for release notes (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+(release notes: yes)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16026#-:-MnWetUND9rdZeU0uktH:b-9k4hpu)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
