### PR TITLE
Setting accuracy in the context copies accuracy to all subcontexts.

### PR DESCRIPTION
**Pull request by edrumwri**
(Prototype, toward addressing issue #8489)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8577)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-:-L9qqtPMDMrO_FCSldRn:b1tu4a9)*

**Comment by sherm1** [comment]
Feature :lgtm: except for CI failures. Per f2f I suggest modifying how rimless_wheel uses accuracy so that nothing changes from the earlier values, rather than trying to debug that in this PR.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[examples/rimless_wheel/simulate.cc, line 91 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-L9riVJ8049ucqqKwAk-:-L9riVJ8049ucqqKwAk0:b-j2dvmf) ([raw file](https://github.com/robotlocomotion/drake/blob/e62d97e8bd0c06b0711e073b88c6999987db2e9b/examples/rimless_wheel/simulate.cc#L91)):*
> ```cpp
> 
>   simulator.set_target_realtime_rate(FLAGS_target_realtime_rate);
>   simulator.get_mutable_context().set_accuracy(FLAGS_accuracy);
> ```

BTW would be better to have `simulator.set_accuracy()` I think, with the simulator secretly using that for its various purposes including integration and setting accuracy in the context.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-:-L9rjalt2Nfanr_xPcEM:bq2suua)*

**Comment by edrumwri** [comment]
+@soonho-tri for platform review (per regular rotation please, and also because you rock)

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/rimless_wheel/simulate.cc, line 91 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-L9riVJ8049ucqqKwAk-:-L9v-5oY3Hk90e5UnPp3:baz2w12) ([raw file](https://github.com/robotlocomotion/drake/blob/e62d97e8bd0c06b0711e073b88c6999987db2e9b/examples/rimless_wheel/simulate.cc#L91)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would be better to have `simulator.set_accuracy()` I think, with the simulator secretly using that for its various purposes including integration and setting accuracy in the context.
</blockquote></details>

BTW Agreed- I'm going to work on adding the necessary plumbing between the integrator accuracy and the context accuracy this quarter. I'll add that then.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-:-L9v-JnA0wW9PXdEN0L2:b-ifkgce)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-L9v-vZ66B9E7_0Qque8:-L9v-vZ66B9E7_0Qque9:b-uq2eyt) (no related file):*
Checked :apple: tests: `bazel test //systems/... //examples/... -c dbg --config=asan`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8577#-:-L9vCPVFEG3E8Pn98F5o:bnfp4nl)*

**Pull request merged**
