### PR TITLE
Update to point to the new reviewable disposition proposal

### PR DESCRIPTION
**Pull request by soonho-tri**
This is how the new version looks:

screen shot 2018-06-13 at 2 39 02 pm

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8982)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for all reviews, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8982#-:-LEuRqN-BwBpLUIEsIyY:b-g6fe9u)*

**Comment by jwnimmer-tri** [comment]
:lgtm: all.  Thanks!

FYI I think in the future once we settle in to the new semantics, we could probably also add a couple best practices here.  If I had to write them down now, I think they would be:
- Authors or reviewers should use "FYI" prefix when initiating a discussion for something of interest (but that is probably not a defect).  This will show up for any other people who open the review, but will not hold up the PR.
- Reviewers should use "nit" prefix when initiating a discussion where there is a small defect that should be fixed, but it is not strictly necessary to discuss further.  (For example -- typos, whitespace, etc.)
- Use https://reviewable.io/reviews#q=+mine as your dashboard and aggressively work to whack-a-mole your red bubbles in the "Being reviewed by me" section -- the works in progress.
- Reviewers should focus on pointing out problems (aka defects), not suggesting changes.  Even if you have a suggestion for a change, begin the discussion posting by articulating the problem and then present your suggested after stating the problem

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---

*[doc/reviewable.rst, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8982#-LEvUF8vCsJF3hVr0ptm:-LEvUF8vCsJF3hVr0ptn:b3gvgzs) ([raw file](https://github.com/robotlocomotion/drake/blob/7aacdc1780869a5f225d61fe83e4cad86da2709a/doc/reviewable.rst#L37)):*
> ```reStructuredText
> All threads in Reviewable must be resolved before you can merge your PR.
> 
> The semantics of discussion resolution is a little tricky. We recommend to read
> ```

FYI Perhaps "a little tricky" is no longer (quite) so true?  It was arguably worse before.  What do you think about "more nuanced than GitHub's default code review tool"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8982#-:-LEvYAuGAaWTtaGUhuWh:blmkrmi)*

**Comment by sherm1** [comment]
I'm not as sure yet that FYI/BTW is usable now. In a recent PR, several reviewer comments disappeared before I had addressed them. The sequence of events was:
- reviewer made a helpful FYI comment
- some discussion ensued, with me saying what action I would take
- later, I went through open reviewer comments to address them but this one was gone (resolved)

I believe the reason is that the first response has the effect of resolving the comment, regardless of its content. (Previously required a "Done" or "OK".) Might be better always to use Nit or Minor so the comments stick around. Could use "Nit (FYI):" for ignorable comments.

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8982#-:-LEvjykH-MjtHgd-PBlO:bpa8u1u)*

**Comment by jwnimmer-tri** [comment]
Indeed, if the reviewer starts a discussion with a post "FYI" then the default will be "Discussing".  If you say "I agree, stay tuned" and they hit Ack, then its folded up and resolved with no UX anymore.

I think the design intent is that you need to either start your reply with "Will do" as in "Will do a fix, I agree" (to toggle it to Working), or else manually toggle yourself to either Working or Blocking.

I think the broader principles for this case though, are:
- Be careful to only use "FYI" for discussions, not defects.
- Never post status updates like "Thanks, I like that idea".  Either ask a follow-up question (such that they will ping it back to you), or post a final resolution that its done.  Status updates are pointless noise.
- Pay attention to marking yourself Working on FYI discussions that turn into defects.

Perhaps that's still a too-difficult workflow; I don't yet have enough personal experience to say.

**Comment by sherm1** [comment]
Thanks, I didn't know about the "will do" trick. I'll have to play with that.

**Comment by soonho-tri** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---

*[doc/reviewable.rst, line 37 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8982#-LEvUF8vCsJF3hVr0ptm:-LEyt36m14ovz_WFTqaR:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/7aacdc1780869a5f225d61fe83e4cad86da2709a/doc/reviewable.rst#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Perhaps "a little tricky" is no longer (quite) so true?  It was arguably worse before.  What do you think about "more nuanced than GitHub's default code review tool"?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8982)*

**Pull request merged**
