### PR TITLE
jekyll: Fix sample_vimrc dowload link

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also fix some markup glitches.

Part of #14577.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14682)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews, please.

**Comment by jwnimmer-tri** [comment]
+@IanTheEngineer -@ggould-tri for review, please.

+@jwnimmer-tri :lgtm: rubber stamp for platform.

**Review by IanTheEngineer — COMMENTED** [review]
:lgtm: Your changes all rendered well locally. I was able to download the `sample_vimrc`. I did find a link that didn't render, but it's not directly part of this PR, so we can handle that separately if you prefer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14682#-:-MUAd9GREls7eRTfihbo:b-8gy44k)* status: 1 unresolved discussion (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[doc/_pages/vim.md, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14682#-MUAbiR01Qi1ZEwxk0Gk:-MUAbiR01Qi1ZEwxk0Gl:b-qgojbq) ([raw file](https://github.com/robotlocomotion/drake/blob/6d06a69eb8d45d010b17e077f092b18899a9a56b/doc/_pages/vim.md#L65)):*
> ```
> bazel-compilation-database](https://github.com/grailbio/bazel-compilation-database)
> ```
Nit: As it's not part of this review. The opening bracket of this link is missing.

**Review by IanTheEngineer — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14682)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Forcing in now.

**Pull request merged**
