### PR TITLE
Deprecate FixedOffsetFrame::SetPoseInBodyFrame() for SetPoseInParentFrame()

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 
 
PR #18198 resolves issue #15638 for the FixedOffsetFrame class by deprecating SetPoseInBodyFrame() for SetPoseInParentFrame() 
and by adding GetPoseInParentFrame().

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFQXN3wBPtTOIfU7rcy:bqtf4el)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Lunch checkpoint.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFjWVvjCm9CwojQUndx:b27rxgr)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3795 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjU8bW7UReyLXTeujI:-NFjU8bW7UReyLXTeujJ:bsqucpy) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/plant/test/multibody_plant_test.cc#L3795)):*
> ```cpp
> #pragma GCC diagnostic pop  // pop -Wdeprecated-declarations
> 
>   frame_F.SetPoseInParentFrame(context.get(), X_WF_new);
> ```

minor: since the deprecated method above already set the pose to X_WF_new the test here can't distinguish between this working or doing nothing. Please make it change to something else.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjTvfI0iF63GMDBeQL:-NFjTvfI0iF63GMDBeQM:bhnavj5) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/plant/test/multibody_plant_test.cc#L3798)):*
> ```cpp
> 
>   const RigidTransformd& X_WF_context_new =
>       frame_F.CalcPoseInBodyFrame(*context);
> ```

Does this function have the same problem? Or is that really the Body frame? If it's correct then I don't understand calling the result X_WF. Can you clarify?
___
*[`multibody/tree/fixed_offset_frame.h` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjV8Im0zkDHt4UXqdq:-NFjV8Im0zkDHt4UXqdr:b-7pay4j) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L103)):*
> ```objc
>   /// @param[in] context contains the state of the multibody plant.
>   /// @param[in] X_PF Rigid transform that contains the pose (orientation and
>   ///   position vector) from the parent frame P to `this` frame F.
> ```

minor: the wording above is imprecise. Both the "relates" and "from/to" wording are ambiguous. More conventional for us would be:
"The rigid transform X_PF that gives the pose of this frame F in its parent frame P." (or "relative to its parent frame" or "with respect to its parent frame P").
___
*[`multibody/tree/fixed_offset_frame.h` line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjW8YiAvoz7L7WC2Sx:-NFjW8YiAvoz7L7WC2Sy:bbznqcz) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L113)):*
> ```objc
> 
>   /// Returns the rigid transform X_PF that relates the parent frame P to
>   /// `this` frame F.
> ```

minor: reword
___
*[`multibody/tree/fixed_offset_frame.h` line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjWJyHDXg6wUx4IS4m:-NFjWJyHDXg6wUx4IS4n:bp04kz5) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L124)):*
> ```objc
> 
>   DRAKE_DEPRECATED("2023-02-01", "SetPoseInBodyFrame() has been superseded by "
>                                  "SetPoseInParentFrame().")
> ```

minor: clarify that it has just been renamed and had the wrong name before -- otherwise users might think the functionality changed

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm: pending some minor things

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFjk8_PBgFPClHSgfds:bcntfqm)* status: 5 unresolved discussions, needs at least two assigned reviewers, missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3795 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjU8bW7UReyLXTeujI:-NFpiOBQ7S-UEc_7KTOQ:bmave3g) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/plant/test/multibody_plant_test.cc#L3795)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: since the deprecated method above already set the pose to X_WF_new the test here can't distinguish between this working or doing nothing. Please make it change to something else.
</blockquote></details>

Done.  Complete test overhaul.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjTvfI0iF63GMDBeQL:-NFpiRcJ2b4thT8Uehp_:bmave2g) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/plant/test/multibody_plant_test.cc#L3798)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Does this function have the same problem? Or is that really the Body frame? If it's correct then I don't understand calling the result X_WF. Can you clarify?
</blockquote></details>

Done.  Complete test overhaul
___
*[`multibody/tree/fixed_offset_frame.h` line 103 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjV8Im0zkDHt4UXqdq:-NFjqosKDd02HbstoC0H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L103)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the wording above is imprecise. Both the "relates" and "from/to" wording are ambiguous. More conventional for us would be:
"The rigid transform X_PF that gives the pose of this frame F in its parent frame P." (or "relative to its parent frame" or "with respect to its parent frame P").
</blockquote></details>

Done.



_Code quote:_
```objc
  /// Sets the rigid transform that relates the parent frame to `this` frame.
```
___
*[`multibody/tree/fixed_offset_frame.h` line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjW8YiAvoz7L7WC2Sx:-NFjpfSVB7WNyR-5bXTm:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: reword
</blockquote></details>

Done.
___
*[`multibody/tree/fixed_offset_frame.h` line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjWJyHDXg6wUx4IS4m:-NFjnOqs75UTJaqK8RiY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/tree/fixed_offset_frame.h#L124)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: clarify that it has just been renamed and had the wrong name before -- otherwise users might think the functionality changed
</blockquote></details>

Done.

**Review by mitiguy — COMMENTED** [review]
@sherm1 -- Is this ready for platform review.  There is one blocking comment that may not longer be relevant.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFuAuD02mJStGwYmBMZ:be83hak)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
I love the new test!

+@xuchenhan-tri for platform review per rotation, please

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFubtOt91IYPZq5uDoz:b3zjff0)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @xuchenhan-tri)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3795 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFjU8bW7UReyLXTeujI:-NFubcDo9RGPspK6othn:b-h1hkn2) ([raw file](https://github.com/robotlocomotion/drake/blob/d5aca8e42155bef243130c6aad6d0122ca90de87/multibody/plant/test/multibody_plant_test.cc#L3795)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.  Complete test overhaul.
</blockquote></details>

Very nice, thanks!
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3761 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuYsQj1YBuRIxZEZN5:-NFuYsQj1YBuRIxZEZN6:b94znbh) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3761)):*
> ```cpp
>                               Vector3d(0.1, 0.2, 0));
>         RigidTransformd X_BP(RotationMatrixd::MakeXRotation(M_PI/4),
>                              Vector3d(0, 0.3, 0.4));
> ```

nit: non-compliant indenting, should start at beginning of line
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3785 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFua589AXO7ElGl1jIq:-NFua589AXO7ElGl1jIr:bvmwe4c) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3785)):*
> ```cpp
>   RigidTransformd X_BP_check1 = frame_P.GetPoseInParentFrame(*context);
>   RigidTransformd X_BP_check2 = frame_P.CalcPoseInBodyFrame(*context);
>   EXPECT_TRUE(CompareMatrices(X_BP.GetAsMatrix34(),
> ```

nit: we have RigidTransform::IsNearlyEqualTo() for exactly this purpose. Why not
```c++
EXPECT_TRUE(X_BP_check1.IsNearlyEqualTo(X_BP, kTolerance);
```
here and below instead? That is much more compact and elegant IMO.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3786 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFu_EcZ9qKLh6xfPuzB:-NFu_EcZ9qKLh6xfPuzC:bcwwpu0) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3786)):*
> ```cpp
>   RigidTransformd X_BP_check2 = frame_P.CalcPoseInBodyFrame(*context);
>   EXPECT_TRUE(CompareMatrices(X_BP.GetAsMatrix34(),
>                     X_BP_check1.GetAsMatrix34(), kTolerance));
> ```

nit: odd indenting (here and below). You can indent 4 spaces for continuation or line up the arguments -- clang_format will give you something reasonable too.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NFuhQRf5u2IoNK4wB-S:b-cxwtpw)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3879 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFudx2e3ijhI4J7XYES:-NFudx2f-_dsoFCeu5T5:b2ni8l0) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3879)):*
> ```cpp
>                          X_BF_check.GetAsMatrix34()));
> 
>   // Misnaming means SetPoseInBodyFrame() matches GePoseInParentFrame().
> ```

nit



_Suggestion:_
```cpp
GetPoseInParentFrame().
```
___
*[`multibody/tree/fixed_offset_frame.h` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuf5ZXCgtAPYnYyoCH:-NFuf5ZXCgtAPYnYyoCI:bxsg2da) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L118)):*
> ```objc
>       const systems::Context<T>& context) const {
>     const systems::BasicVector<T>& X_PF_parameter =
>         context.get_numeric_parameter(X_PF_parameter_index_);
> ```

BTW should there be a precondition that `this` frame has been registered in the given `context`?
___
*[`multibody/tree/fixed_offset_frame.h` line 123 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFugtgTC-SIUJmsvg53:-NFugtgTC-SIUJmsvg54:b1xtbk9) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L123)):*
> ```objc
>   }
> 
>   DRAKE_DEPRECATED("2023-02-01", "SetPoseInBodyFrame() was incorrectly named "
> ```

BTW we usually round up when counting for deprecation so this should be 2023-03-01.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/plant/test/multibody_plant_test.cc` line 3761 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuYsQj1YBuRIxZEZN5:-NFvD28S5OWKGiNc9ah4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3761)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: non-compliant indenting, should start at beginning of line
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3785 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFua589AXO7ElGl1jIq:-NFvEZIR4ZCT8ol4SnGi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3785)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: we have RigidTransform::IsNearlyEqualTo() for exactly this purpose. Why not
```c++
EXPECT_TRUE(X_BP_check1.IsNearlyEqualTo(X_BP, kTolerance);
```
here and below instead? That is much more compact and elegant IMO.
</blockquote></details>

Done.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3786 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFu_EcZ9qKLh6xfPuzB:-NFvEdW0A1BddcCGMKmP:bxymthc) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3786)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: odd indenting (here and below). You can indent 4 spaces for continuation or line up the arguments -- clang_format will give you something reasonable too.
</blockquote></details>

Not relevant anymore as one-liner removed need to indent.
___
*[`multibody/plant/test/multibody_plant_test.cc` line 3879 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFudx2e3ijhI4J7XYES:-NFvEq0c1yi73uOBEdVg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3879)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`multibody/tree/fixed_offset_frame.h` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuf5ZXCgtAPYnYyoCH:-NFvFms9CrjvRfnr2EYU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L118)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW should there be a precondition that `this` frame has been registered in the given `context`?
</blockquote></details>

Done.
___
*[`multibody/tree/fixed_offset_frame.h` line 123 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFugtgTC-SIUJmsvg53:-NFvFMoA-BaSRFrIUd0P:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L123)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW we usually round up when counting for deprecation so this should be 2023-03-01.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
*[`multibody/plant/test/multibody_plant_test.cc` line 3785 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFua589AXO7ElGl1jIq:-NFvGQZBECoqqzxjLzqn:b-cyaond) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/plant/test/multibody_plant_test.cc#L3785)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

CompareMatrices displays the contents of the matrices when they differ.  IsNearlyEqualTo doesn't.  The former is better for tests; the latter makes developers pull their hair out when a test fails but they have no idea what.  IsNearlyEqualTo is for production code, not tests.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

___
*[`multibody/tree/fixed_offset_frame.h` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuf5ZXCgtAPYnYyoCH:-NFyKslH9zMfiQmVtbrM:bcputha) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L118)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For consistency, we should put the same precondition in the `Set...` function above.
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1941 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFyL2ZcDjlE4aiyBLbQ:-NFyL2ZcDjlE4aiyBLbR:b-upcd8g) ([raw file](https://github.com/robotlocomotion/drake/blob/0a7e9deb72ba148ef1d84ed89185e30daeadd973/bindings/pydrake/multibody/test/plant_test.py#L1941)):*
> ```Python
>                 frame.CalcPoseInBodyFrame(context).GetAsMatrix34(),
>                 numpy_compare.to_float(X_PF.GetAsMatrix34()))
>         self.assertIn("2023-02-01", str(w[0].message))
> ```

nit, CI wants this to be "2023-03-01".

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1 and @xuchenhan-tri)

___
*[`multibody/tree/fixed_offset_frame.h` line 118 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFuf5ZXCgtAPYnYyoCH:-NG-1kC21yZqfcT9-sWZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fae73cb2d62fb0720afbf00622c0698ff313e78a/multibody/tree/fixed_offset_frame.h#L118)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

For consistency, we should put the same precondition in the `Set...` function above.
</blockquote></details>

Done.



_Code quote:_
```objc
  /// @pre `this` frame has been registered in the given `context`.
```
___
*[`bindings/pydrake/multibody/test/plant_test.py` line 1941 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18198#-NFyL2ZcDjlE4aiyBLbQ:-NG-2eMr7evAA1E8oUeq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0a7e9deb72ba148ef1d84ed89185e30daeadd973/bindings/pydrake/multibody/test/plant_test.py#L1941)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, CI wants this to be "2023-03-01".
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18198#-:-NGJknl2A3KZ301owY8o:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @mitiguy)

**Pull request merged**
