### PR TITLE
Add PurePursuit function and PurePursuitController system block

### PR DESCRIPTION
**Pull request by jadecastro**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5729)

### CODE REVIEW

**Comment by jadecastro** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
I'll just mumble about some things here, that I probably won't bother to block this particular PR with.

* simple_car_gen.sh has probably outgrown its filename at this point ; maybe automotive_vector_gen.sh ??
* it may be desirable for pure pursuit to be applicable to an arbitrary path, not just a maliput lane (maybe other Drake-computed trajectories?) sounds like a future-work, even to me.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/pure_pursuit.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KgzkGC1wL99loLLVCRw:-KgzkGC23HLyK5NvOgnN:bi4288x) ([raw file](https://github.com/robotlocomotion/drake/blob/d372e7c1e70689accd86489ff33b923431bec147/drake/automotive/pure_pursuit.cc#L5)):*
> ```cpp
> #include <cmath>
> 
> #include "drake/automotive/maliput/api/road_geometry.h"
> ```

huh. I'm not sure how this module's .h file gets away without needing this include nor having a forward declaration for RoadGeometry. I guess some transitive include trickery? consider if it might be clearer to kick this include statement up to the header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-KgzfrD1tRmPkTq7N4do:b-l7729a)*

**Comment by jwnimmer-tri** [comment]
> simple_car_gen.sh has probably outgrown its filename at this point ; maybe automotive_vector_gen.sh ??

Agreed, I keep meaning to rename it in its own PR but haven't done it yet.  Separate issue / PR though.

**Comment by jadecastro** [comment]
> it may be desirable for pure pursuit to be applicable to an arbitrary path, not just a maliput lane (maybe other Drake-computed trajectories?) sounds like a future-work, even to me.

I've added some logic to compute a valid geo position from a lane if the lookahead distance is beyond the range of the current lane. 

I still need to update the unit test for this function; I'll let you know when that's in.

---

Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/pure_pursuit.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KgzkGC1wL99loLLVCRw:-Kh4IKiq_nxVvyyDfzrL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d372e7c1e70689accd86489ff33b923431bec147/drake/automotive/pure_pursuit.cc#L5)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

huh. I'm not sure how this module's .h file gets away without needing this include nor having a forward declaration for RoadGeometry. I guess some transitive include trickery? consider if it might be clearer to kick this include statement up to the header file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-Kh3mBewd9J2MnLXqVkJ:bpblmuf)*

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-Kh7hAejNYCRpX3gGP1B:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
:lgtm_cancel: waiting for unit tests.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-Kh7hF80vtEgST2EzF8-:b-8gp8yn)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/pure_pursuit_controller.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-Kh7lOrs1AYMTdW38J_P:-Kh7lOrthLp-cgTsjKcG:bkppqp0) ([raw file](https://github.com/robotlocomotion/drake/blob/879346dc719525bb3651622e7f3d99136d522cc3/drake/automotive/pure_pursuit_controller.h#L29)):*
> ```objc
> ///
> /// Input Port 0: a DrivingCommand input.  Existing acceleration is passed
> ///   through; steering command is overwritten.
> ```

BTW, the design of taking a `DrivingCommand` and modifying its steering field while passing through the acceleration field is OK for an initial first cut, but longer term I think it will be better for this controller to just output a steering angle command without taking a `DrivingCommand` as input. This will especially be the case when `IdmController` only outputs an acceleration command.

A downstream mux can stitch together a `DrivingCommand` from individual acceleration & steering angle commands as necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729)*

**Comment by jadecastro** [comment]
Ahh. The added logic was failed because `RoadGeometry::DoToRoadPosition()` isn't implemented yet. I've removed that, added a `TODO`, and opened an issue (#5772).

I've also added missing unit test coverage for `ComputeGoalPoint()`, PTAL.

---

Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-KhAU14MtyvP5YX1nwRM:b-2xrxx5)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-KhNdQW4-svcP4etPmbv:bnfp4nl)*

**Comment by jadecastro** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/automotive/pure_pursuit_controller.h, line 29 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-Kh7lOrs1AYMTdW38J_P:-KhNe0_1viJ6KUC-t4GR:b-5g4ed0) ([raw file](https://github.com/robotlocomotion/drake/blob/879346dc719525bb3651622e7f3d99136d522cc3/drake/automotive/pure_pursuit_controller.h#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, the design of taking a `DrivingCommand` and modifying its steering field while passing through the acceleration field is OK for an initial first cut, but longer term I think it will be better for this controller to just output a steering angle command without taking a `DrivingCommand` as input. This will especially be the case when `IdmController` only outputs an acceleration command.

A downstream mux can stitch together a `DrivingCommand` from individual acceleration & steering angle commands as necessary.
</blockquote></details>

I agree with that assessment. I will work on removing the `DrivingCommand` output in a follow-up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729)*

**Comment by jadecastro** [comment]
+@jwnimmer-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 11 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/automotive/BUILD, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhNxBwWOD-8JhVjIeI2:-KhNxBwXaJzeeX27yskp:b-71c7ss) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/BUILD#L1)):*
> ```Python
> # -*- python -*-
> ```

_Meta_ Please add the new sources into `CMakeLists.txt` as well.

---

*[drake/automotive/pure_pursuit.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO6aU7FE5ryLTcl895:-KhO6aU7FE5ryLTcl896:b-7j0qbd) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L29)):*
> ```objc
> /// They are already available to link against in the containing library.
> ///
> /// @ingroup automotive_systems
> ```

This is not a System, so should not be in the group of systems.

---

*[drake/automotive/pure_pursuit.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO8swhUFdDWh8cr9HN:-KhO8swhUFdDWh8cr9HO:b-qn22a9) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L49)):*
> ```objc
>   /// @param pose is the PoseVector for the ego vehicle.
>   // TODO(jadecastro): Infer the direction of travel rather than require it.
>   static const T Evaluate(const PurePursuitParams<T>& pp_params,
> ```

return-by-value should just be `T` not `const T`.

---

*[drake/automotive/pure_pursuit.h, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO9NG8QxH7gjm2AQ0i:-KhO9NG9LHEfqE3sGJQ1:b-h9bry8) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L55)):*
> ```objc
> 
>   /// Computes the goal point at a distance `s_lookahead` from the closest
>   /// position on the curve in the intended direction of travel.
> ```

BTW Maybe point out that `pose` is as per the above?  It took me an extra moment to grok that.

---

*[drake/automotive/simple_car_gen.sh, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhNvIt-Ja9jGVzgVsis:-KhNvIt0aAaDhQY5vcDu:b-ecj06r) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/simple_car_gen.sh#L21)):*
> ```Shell
> gen_lcm_and_vector_from_proto "maliput railcar state" $drake/automotive/maliput_railcar_state.named_vector
> gen_lcm_and_vector_from_proto "maliput railcar params" $drake/automotive/maliput_railcar_params.named_vector
> gen_lcm_and_vector_from_proto "pure pursuit params" $drake/automotive/pure_pursuit_params.named_vector
> ```

Do we need to have LCM support for these params?  If not, perhaps `gen_vector_proto` instead of `gen_lcm_and_...`?

Oh... the LCM files aren't even added as part of this PR?  In which case, yes, definitely remove the `lcm_and_` part here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729)*

**Comment by jadecastro** [comment]
Review status: 7 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/BUILD, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhNxBwWOD-8JhVjIeI2:-KhOIg14ybs9X4qxFCCg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/BUILD#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ Please add the new sources into `CMakeLists.txt` as well.
</blockquote></details>

Done.

---

*[drake/automotive/pure_pursuit.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO6aU7FE5ryLTcl895:-KhOFR4Gsz7qcfYpr9iz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is not a System, so should not be in the group of systems.
</blockquote></details>

Done.

---

*[drake/automotive/pure_pursuit.h, line 49 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO8swhUFdDWh8cr9HN:-KhOFTXSISftIDDwwB6m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

return-by-value should just be `T` not `const T`.
</blockquote></details>

Done.

---

*[drake/automotive/pure_pursuit.h, line 55 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhO9NG8QxH7gjm2AQ0i:-KhOGsz2sDX5_PlU9Tya:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/pure_pursuit.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Maybe point out that `pose` is as per the above?  It took me an extra moment to grok that.
</blockquote></details>

Done.

---

*[drake/automotive/simple_car_gen.sh, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-KhNvIt-Ja9jGVzgVsis:-KhOIuwTRWfBKBCV7d3l:bkdzxpw) ([raw file](https://github.com/robotlocomotion/drake/blob/9b2ebd998ba1f3221978dfbfc451fd5563e052c5/drake/automotive/simple_car_gen.sh#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do we need to have LCM support for these params?  If not, perhaps `gen_vector_proto` instead of `gen_lcm_and_...`?

Oh... the LCM files aren't even added as part of this PR?  In which case, yes, definitely remove the `lcm_and_` part here.
</blockquote></details>

Ah, that's right.  LCM files not needed.  Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.

---

Reviewed 1 of 11 files at r1, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-KhOT2Wwy0_xPRE2-MK1:by96gdd)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5729#-:-KhOoPNHVZm7w8Fd6ed4:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Oops.  Somehow we missed that this PR reverted the portion of #5726 that fixed up the `BUILD` file.

**Pull request merged**
