### PR TITLE
 Move all matlab-related solvers files into matlab/solvers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is just #3181 with a new number, and `drake-distro/drake/matlab/solvers/` as the new home for the solvers matlab code.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3191)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The proposal here is to segregate C++ code from Matlab code in the source tree, so that folks who only want to use the C++ bits can have a cleaner area to work in.

In this proposal, there are directories at the `drake-distro/drake` top level (`common`, `math`, `solvers`, `systems`, etc.) that contain only C++.  The Matlab is a layer atop those building blocks, and all lives under `drake-distro/drake/matlab` (so `matlab/util`, `matlab/solvers`, `matlab/systems`, etc.).

Big picture, there will be six major blocks of code within the RobotLocomotion/drake repository, which in dependency order are:
 1. The superbuild and its externals.
 2. The Drake C++ libraries.
 3. The SWIG bindings for the Drake C++ libraries (python, matlab).
 4. The Drake Matlab libraries.
 5. The Drake Examples.
 5. The ROS wrappers for the Drake C++ libraries (and other ROS bits).

**Comment by liangfok** [comment]
Reviewed 56 of 394 files at r1.
Review status: 35 of 205 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 306 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPVWA9wgfQ8f4O9uUHy:-KPVWA9wgfQ8f4O9uUHz:bqwh2x3) ([raw file](https://github.com/robotlocomotion/drake/blob/e407a7272f72ccacd797eb6b967c987ba398c013/CMakeLists.txt#L306)):*
> ```CMake
>     BUILD_COMMAND cmake -E copy_directory
>       ${CMAKE_BINARY_DIR}/snopt-precompiled/
>       ${PROJECT_SOURCE_DIR}/drake/solvers_matlab/
> ```

Shouldn't this be `drake/matlab/solvers`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by jwnimmer-tri** [comment]
Review status: 34 of 205 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 306 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPVWA9wgfQ8f4O9uUHy:-KPVgZMxdfSJx6290sEc:bt7hj) ([raw file](https://github.com/robotlocomotion/drake/blob/e407a7272f72ccacd797eb6b967c987ba398c013/CMakeLists.txt#L306)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Shouldn't this be `drake/matlab/solvers`?
</details>
Done.  (Jenkins doesn't test this configuration pre-merge; we definitely need to fire off more test builds before we merge this.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by liangfok** [comment]
Reviewed 39 of 394 files at r1, 1 of 1 files at r2.
Review status: 55 of 205 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPVl1SjEP6nHxQ5TeV8:-KPVl1SjEP6nHxQ5TeV9:b-frykdq) ([raw file](https://github.com/robotlocomotion/drake/blob/5e37f47fbd473e3f7322ddd5a064adb694de52b8/drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt#L1)):*
> ```CMake
> add_matlab_test(NAME solvers/trajectoryOptimization/test/contactImplicitBrick
> ```

BTW, the name of the unit test should ideally include the full path:

`drake/mathlab/solvers/trajectoryOptimization/test/contactImplicitBrick`

That way there will be 0% probability of (1) confusion about where the test's source code is located and (2) name clashes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by Lucy-tri** [comment]
Reviewed 1 of 394 files at r1.
Review status: 55 of 205 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by jwnimmer-tri** [comment]
Review status: 51 of 205 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPVl1SjEP6nHxQ5TeV8:-KPY0cDrw7J2obOEfrFZ:b-b5ha6i) ([raw file](https://github.com/robotlocomotion/drake/blob/5e37f47fbd473e3f7322ddd5a064adb694de52b8/drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt#L1)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, the name of the unit test should ideally include the full path:
> 
> `drake/mathlab/solvers/trajectoryOptimization/test/contactImplicitBrick`
> 
> That way there will be 0% probability of (1) confusion about where the test's source code is located and (2) name clashes.
</details>
Huh, TIL you can add `/` to test names.  I've updated these to track the rename (adding `solvers/`), though I'm not going to add the `drake/` prefix -- the scope of the `CTest` invocation is entirely within `drake` so the extra word is redundant.

Done throughout, including `doc/` change I found during the same grep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by amcastro-tri** [comment]
Excellent! thank you for taking care of this!

**Comment by Lucy-tri** [comment]
Reviewed 1 of 394 files at r1, 2 of 11 files at r3.
Review status: 53 of 205 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: 53 of 205 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPVl1SjEP6nHxQ5TeV8:-KPYJEU2gwPSOxnaDjIF:b-8sfqwd) ([raw file](https://github.com/robotlocomotion/drake/blob/5e37f47fbd473e3f7322ddd5a064adb694de52b8/drake/matlab/solvers/trajectoryOptimization/test/CMakeLists.txt#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Huh, TIL you can add `/` to test names.  I've updated these to track the rename (adding `solvers/`), though I'm not going to add the `drake/` prefix -- the scope of the `CTest` invocation is entirely within `drake` so the extra word is redundant.
> 
> Done throughout, including `doc/` change I found during the same grep.
</details>
OK. Upon further reflection, since all unit tests listed when I execute the commands below fall under the "drake" directory, I now agree that including "drake/" in the names of the unit tests is redundant.

```
cd drake-distro/build/drake
ctest -N
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-:-KPYJW3jnoakJdk7or-v:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@RussTedrake curious to get your comments on this one, as the first step towards doing the same for the rest of the matlab code.

**Comment by RussTedrake** [comment]
thanks.  i agree with it; i think it will clean things up and emphasize the direction where everything is going.  but I would like to give @robotlocomotion/group-member-write a chance to comment.  in particular, it might be yet another major hiccup in some long forks (ahem... @mposa ).  let's give another 24 hours to let people comment?

---

Review status: 52 of 205 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-:-KPmdOdU6_Ft68w7Xzbe:b-70br4i)*

**Comment by jwnimmer-tri** [comment]
> let's give another 24 hours to let people comment?

No problem.

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

Once defects are posted, I will fix them, rebase onto master, and fire off extra pre-merge builds.  Tagging DMN until that is all done.

**Comment by david-german-tri** [comment]
Thanks to the large number of files touched, and @jwnimmer-tri's careful structuring of commits, this is the rare PR that is easier to review in GitHub than Reviewable.

---

Reviewed 381 of 394 files at r1, 1 of 1 files at r2, 10 of 11 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/matlab/solvers/CMakeLists.txt, line 3 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPrhSakKRCfYKO_xcNx:-KPrhSakKRCfYKO_xcNy:b-i946q6) ([raw file](https://github.com/robotlocomotion/drake/blob/ca6f300b15649f7a9ee22bba8d55a4aaf461c0c1/drake/matlab/solvers/CMakeLists.txt#L3)):*
> ```CMake
> pods_find_pkg_config(gurobi)
> 
> if(gurobi_FOUND)
> ```

Previously, these were only conditioned on MATLAB_FOUND.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-:-KPriM8AQBwTbAg5D053:bnt75cu)*

**Comment by jwnimmer-tri** [comment]
*[drake/matlab/solvers/CMakeLists.txt, line 3 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-KPrhSakKRCfYKO_xcNx:-KPsBy7yJWa6q8br1kip:b-jcwho3) ([raw file](https://github.com/robotlocomotion/drake/blob/ca6f300b15649f7a9ee22bba8d55a4aaf461c0c1/drake/matlab/solvers/CMakeLists.txt#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Previously, these were only conditioned on MATLAB_FOUND.
</details>
I don't think so?
https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/CMakeLists.txt#L3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 196 of 205 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-:-KPsEIdlna0XWTIGKY2g:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-minimal please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-minimal please
@drake-jenkins-bot windows-msvc-ninja-32-experimental-matlab-open-source please
@drake-jenkins-bot windows-msvc-64-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
+@liangfok Can I get an official review from you also?

**Comment by liangfok** [comment]
:lgtm: (feature)

---

Reviewed 5 of 394 files at r1, 1 of 2 files at r4, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191#-:-KPsG1sY817JqGzSt_wR:b8j5bpo)*

**Comment by liangfok** [comment]
Reviewed 288 of 394 files at r1, 3 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3191)*

**Comment by jwnimmer-tri** [comment]
All of the opt-in builds passed.  The only pre-merge matrix failure was on msvc due to #3230, so I'm using override-merge to get around the jenkins flake.

**Pull request merged**
