### PR TITLE
Add doxygen.py tool to generate Doxygen output

### LINKED ISSUE #5814: Add build_doxygen convenience for Bazel-only developers
It would be nice to be able to generate Doxygen locally for testing, without having to spin up a CMake build.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Resolves #5814.  Relates #5881.

Ideas for future improvements:
- Flags to process only certain subdirectories.
- Check for errors in the output log.
- Port `drake/doc/CMakeLists.txt` to call this instead.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6306)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Git flake
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental please

**Comment by liangfok** [comment]
+@liangfok for feature review. I'll probably get to this over the weekend or early next week. If someone else is able to feature review this before me, please feel free to remove me.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmBuYhHqN5bgm4fPh_k:b-rrs43s)*

**Comment by SeanCurtis-TRI** [comment]
+@seancurtis-tri 
It turns out I may not be the ideal feature reviwer -- some time in the last few weeks my doxygen now segfaults. It does this via the old method and it *may* lead to an error I'm getting in running this script (I'm assuming they're related):

```
Traceback (most recent call last):
  File "drake/doc/doxygen.py", line 76, in <module>
    main()
  File "drake/doc/doxygen.py", line 72, in main
    _run_doxygen(args)
  File "drake/doc/doxygen.py", line 60, in _run_doxygen
    subprocess.check_call([doxygen, doxyfile], cwd=binary_dir)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/doxygen', '/home/seanc/code/drake-distro/build/drake/doc/Doxyfile_CXX']' returned non-zero exit status -11
```

So, assuming that I've got some local corruption that is affecting this (and modulo a single BTW). :LGTM:  

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/Doxyfile_CXX.in, line 323 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC532gttMRbpY2uqTx:-KmC532gttMRbpY2uqTy:b-wuv81) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/Doxyfile_CXX.in#L323)):*
> ```
> EXTERNAL_GROUPS        = YES
> EXTERNAL_PAGES         = YES
> PERL_PATH              =
> ```

BTW I'm assuming this is some anachronistic value that was noted during the creation of this PR; if the script depends on this correction, the relationship certainly isn't clear.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmC4LG-nU6utRqySeRq:b-slkpq5) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
> ```Python
> 
> # Looks like "@VAR@" or "${VAR}".
> _varsubst = re.compile(r'^(.*?)(@[^ ]+?@|\$\{[^ ]+?\})(.*)([\r\n]*)')
> ```

BTW As with the other edit to cmake-related things, I'm assuming this PR doesn't actually depend on this, but it was clean up that was noted and rolled in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmC4Qon74Q0F8pIzEce:baqsep7)*

**Comment by jwnimmer-tri** [comment]
Yup, that error means that Doxygen segfaulted.

Aside: When I'm at HQ, remind me to tell the "Segfault means its works" story.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/Doxyfile_CXX.in, line 323 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC532gttMRbpY2uqTx:-KmC5veG_uhHGa6rInT0:b-54cynk) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/Doxyfile_CXX.in#L323)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm assuming this is some anachronistic value that was noted during the creation of this PR; if the script depends on this correction, the relationship certainly isn't clear.
</blockquote></details>

Good question.

The value was being curated during CMake's configuration step, but is not required by Doxygen.  Rather than port the `which perl` hunt to the new Python script, I removed the useless parameterization here.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmC6BtaGwtQRacl8jJZ:b-n1dce8) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As with the other edit to cmake-related things, I'm assuming this PR doesn't actually depend on this, but it was clean up that was noted and rolled in.
</blockquote></details>

Actually without this fixup, `doxygen.py` would throw an exception, due to non-substituting uses of `@` in the configuration file like https://github.com/RobotLocomotion/drake/blob/master/drake/doc/Doxyfile_CXX.in#L40-L41.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmC5m-PDoQhbsJP39_T:b-g2fii4)*

**Comment by SeanCurtis-TRI** [comment]
I understand you won't be here very long. And we have so many other conversations, the "Segfault means it works" story may have to be delayed.  :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmC7OCypubputy9QQmV:b-y0edxy) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Actually without this fixup, `doxygen.py` would throw an exception, due to non-substituting uses of `@` in the configuration file like https://github.com/RobotLocomotion/drake/blob/master/drake/doc/Doxyfile_CXX.in#L40-L41.
</blockquote></details>

OK Good to know.  The joys of non-unique sentinel characters.  That's why I always simply use 0x32 as *my* sentinel character.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmC7AxPyt0L3Vk6sHJT:b-3d7um7)*

**Comment by SeanCurtis-TRI** [comment]
Also, incidentally, if "segfault means it works" is to be taken at face value, can this case be handled better in the script so users don't think, "Aw, crap!  It didn't work."  I only know through my own experience that I still have built doxygen, even in the presence of the segfault.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmC8QFNQogr0Q4yTAyI:bgrntuf)*

**Comment by jwnimmer-tri** [comment]
In light of the actual folk tale I'm referring to, the fact that your Doxygen actually works _while segfaulting_ is hilarious! The story is only two minutes, we'll definitely do it at lunch (with @rpoyner-tri if possible).

**Comment by SeanCurtis-TRI** [comment]
Sounds a worthy lunch-time entertainment.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmCC-5F0m_kn2gYHJHj:bpt6f1z)*

**Comment by amcastro-tri** [comment]
Thanks @jwnimmer-tri, this is great! just a few questions.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmCWt_U9W4fhfmwPUOs:-KmCWt_U9W4fhfmwPUOt:b-s8in6a) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L38)):*
> ```reStructuredText
> 
>     $ cd drake-distro
>     $ drake/doc/doxygen.py [--quick]
> ```

could you briefly comment on what the `--quick` flag is for?

---

*[drake/doc/documentation_instructions.rst, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmCWyGoxg6apdffsvWJ:-KmCWyGoxg6apdffsvWK:b-ku5onn) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L41)):*
> ```reStructuredText
> 
> To view the generated documentation, open using a web browser to
> ``drake-distro/build/drake/doc/doxygen_cxx/html/index.html``
> ```

With `Cmake/ninja`, I usually build in `drake-distro/build/release/drake/doc` (or `drake-distro/build/debug/drake/doc`). I assume the generated doc with this method always lives in `drake-distro/build/drake/doc` regardless of what I would usually choose for ninja?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmCXTCvI9tKT8VCiyUu:b-kjf5nr)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmCWt_U9W4fhfmwPUOs:-KmCXn0-n1CV-PLEaIUl:bsoyf2n) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L38)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you briefly comment on what the `--quick` flag is for?
</blockquote></details>

The tool has a `--help` output -- does the help message there have enough detail?

---

*[drake/doc/documentation_instructions.rst, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmCWyGoxg6apdffsvWJ:-KmCXv4fMqV5kHlC7fCv:btqqu5l) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

With `Cmake/ninja`, I usually build in `drake-distro/build/release/drake/doc` (or `drake-distro/build/debug/drake/doc`). I assume the generated doc with this method always lives in `drake-distro/build/drake/doc` regardless of what I would usually choose for ninja?
</blockquote></details>

Correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review please per rotation, or else punt to ggould-tri if needed.

**Comment by sherm1** [comment]
Platform :lgtm:, a few ignorable BTWs.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmDOrhJsiZfIB6FKXTi:-KmDOrhKbXDQYIaAlbHW:b-2agimp) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L41)):*
> ```reStructuredText
> 
> To view the generated documentation, open using a web browser to
> ``drake-distro/build/drake/doc/doxygen_cxx/html/index.html``
> ```

BTW Bazel-only builders won't necessarily have a drake-distro/build directory. I see that this command creates build/drake/... as needed, so no problem. It does seem like a bit of a CMake-legacy anachronism though. Fine as is, but something shorter would work too, like drake-distro/build/doxygen_cxx/html.  

---

*[drake/doc/doxygen.py, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmDQqim9aXKMYxZoddK:-KmDQqim9aXKMYxZoddL:bkmend4) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/doxygen.py#L5)):*
> ```Python
> """Command-line tool to generate Drake's Doxygen content.
> 
> """
> ```

BTW odd comment formatting?

---

*[drake/doc/doxygen.py, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmDRMKJaTTCT8ewVeFM:-KmDRMKJaTTCT8ewVeFN:brkk18) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/doxygen.py#L20)):*
> ```Python
>     result = dirname(dirname(dirname(os.path.abspath(sys.argv[0]))))
>     if not os.path.exists(os.path.join(result, "WORKSPACE")):
>         raise RuntimeError("Could not place drake-distro at " + result)
> ```

BTW "place" -> "find"?

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmDTH9vd5SRySUOyEib:b-qiwzna) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

OK Good to know.  The joys of non-unique sentinel characters.  That's why I always simply use 0x32 as *my* sentinel character.
</blockquote></details>

@seancurtis-tri 0x32 == '2' ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-:-KmDTkWBGdIo31CULM1x:b-jaguv6)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmDXNFWKAcHnlW7RzPH:b5rxdqn) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

@seancurtis-tri 0x32 == '2' ?
</blockquote></details>

Touche. I meant just `(char)32`.  Something about that seemed odd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/documentation_instructions.rst, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmDOrhJsiZfIB6FKXTi:-KmDbqp1ffNHTQD1fmRJ:blidlw3) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/documentation_instructions.rst#L41)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Bazel-only builders won't necessarily have a drake-distro/build directory. I see that this command creates build/drake/... as needed, so no problem. It does seem like a bit of a CMake-legacy anachronism though. Fine as is, but something shorter would work too, like drake-distro/build/doxygen_cxx/html.  
</blockquote></details>

I think in the future we can change it.  For now I'd like to keep it the same as CMake, because I'd like to switch CMake and Drake CI to use this script.

---

*[drake/doc/doxygen.py, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmDQqim9aXKMYxZoddK:-KmDc5HhjJbtIC9nNqpS:bf46kl4) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/drake/doc/doxygen.py#L5)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW odd comment formatting?
</blockquote></details>

Yup.  PEP-008 is a weird, weird thing.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmDcDiR1RXsTivXJa0p:b4qxeaj) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Touche. I meant just `(char)32`.  Something about that seemed odd.
</blockquote></details>

Hah.  I thought that was supposed to be the joke.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306)*

**Comment by SeanCurtis-TRI** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[tools/cmake_configure_file.py, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6306#-KmC4LFzFMbK19oMfc1E:-KmDce69vfEHdSU_aRA-:b-1hyzp5) ([raw file](https://github.com/robotlocomotion/drake/blob/f71c8a52dcdb48664a7828632789c8633bbdb262/tools/cmake_configure_file.py#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hah.  I thought that was supposed to be the joke.
</blockquote></details>

Siiiigh.  It seems my best jokes are accidents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6306)*

**Pull request merged**
