### PR TITLE
libdrake: Fix build_componets_refresh

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
I think this may have broken at some point; this just does a quick fix.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8073)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature and platform, please.

Ran across this when looking at #8069 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-:-L5L5e0qBEciB8qRrai-:bdr80cu)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tools/install/libdrake/build_components.bzl, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5LckBqeRsdHVRoXB4I:-L5LckBqeRsdHVRoXB4J:bnscq3j) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L50)):*
> ```Python
>     "//common/proto:matlab_rpc",
>     "//common/proto:protobuf",
>     "//common/proto:protobuf_ubsan_fixup",
> ```

Does this cause the header to be duplicately installed (the new one being in the wrong place)?

---

*[tools/install/libdrake/build_components.bzl, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5LccZ8VCWu0sDsq2bC:-L5LccZ8VCWu0sDsq2bD:brtsbem) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L85)):*
> ```Python
>     "//common:symbolic",
>     "//common:symbolic_decompose",
>     "//common:text_logging_gflags",
> ```

This should not be here.

---

*[tools/install/libdrake/build_components.bzl, line 360 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5Lc6iLQyLuNPrbmqeU:-L5Lc6iLQyLuNPrbmqeV:b-3hfq80) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L360)):*
> ```Python
>     "//tools/install/libdrake:gurobi_deps",
>     "//tools/install/libdrake:mosek_deps",
>     "//tools/install/libdrake:vtk_deps",
> ```

These four above should not be here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8073)*

**Comment by jwnimmer-tri** [comment]
I've merged a PR with just the renames.  Once rebased, this PR can focus on fixing the script, and any new changes to the bzl file should show up more clearly.

**Comment by EricCousineau-TRI** [comment]
Thanks! Just updated the branch, PTAL.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/install/libdrake/build_components.bzl, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5LckBqeRsdHVRoXB4I:-L6Y4zsTEKvd3H-_01IP:b-74bepi) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Does this cause the header to be duplicately installed (the new one being in the wrong place)?
</blockquote></details>

Done. Removed it.

---

*[tools/install/libdrake/build_components.bzl, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5LccZ8VCWu0sDsq2bC:-L6Y50okIzTQMk_Cnt2J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L85)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This should not be here.
</blockquote></details>

Done.

---

*[tools/install/libdrake/build_components.bzl, line 360 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-L5Lc6iLQyLuNPrbmqeU:-L6Y4saprDefbIJoAiLW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/22fd55df4e17aaf463d98fe4dec8c3e984d1d477/tools/install/libdrake/build_components.bzl#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

These four above should not be here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-:-L6Y54cmsRrSjQeG_QMz:bodbyi6)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8073#-:-L6Y7yYmMx28bN8btico:bnfp4nl)*

**Pull request merged**
