### PR TITLE
Rod2d tan dir spurious lambda function parameter removal

### PR DESCRIPTION
**Pull request by edrumwri**
This PR follows from a notification by @jwnimmer-tri that a lambda function was not using all parameters. Investigation indicated that the parameter was in fact unnecessary.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5961)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I just reviewed the one file, assuming the other changes were some git error.  Let me know if otherwise.

---

Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5961#-:-KiljMCGiqffE0wfUJMS:bfa03b5)*

**Comment by edrumwri** [comment]
Ah, you're too fast! Yes, that's correct.

---

Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5961#-:-KillcMWd6xSguSf8Yqw:bgd1f5u)*

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5961#-:-Kiln-cpCSDL7oDAIJ6T:b-kmrewj)*

**Comment by edrumwri** [comment]
Thanks Jeremy!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5961#-:-Kilp7FERHBpiRowbhIo:bo0c705)*

**Pull request merged**
