### PR TITLE
[doc] Add tips for profiling

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16817)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please?

I plan to have a few more advanced tips in the future, but having even the basic things on the website seems like a nice first step.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

I checked the content but did not check for broken links.  Please let me know if you'd like me to check them as well. I can run the Doxygen locally to check.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16817#-:-MyPTBiz4veFinD7cZqL:bkfsum8)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I double-checked the links, all are good.

+@ggould-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16817#-:-MyX_1cG97Zxwnl8YdJU:b-huk7ai)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: a few unimportant nits.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16817#-:-MyhBnsF6bH0mUG04ckL:bf0jvqf)* status: 4 unresolved discussions (waiting on @jwnimmer-tri)

___
*[doc/_pages/profiling.md, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16817#-MyhCYCbDl5K19F238jr:-MyhCYCbDl5K19F238js:b9ra9es) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c799ba0ac3636eb310114be2dae425e70452be/doc/_pages/profiling.md#L6)):*
> ```Markdown
> 
> This page contains tips and tricks for capturing and understanding profiling
> reports, as related to Drake.
> ```

nit:  Presumably a reader already knows this is the drake documentation.



_Suggestion:_
```Markdown
reports.
```
___
*[doc/_pages/profiling.md, line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16817#-MyhC8DyCSdJsk1u0eoc:-MyhC8DyCSdJsk1u0eod:b1t8ohw) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c799ba0ac3636eb310114be2dae425e70452be/doc/_pages/profiling.md#L38)):*
> ```Markdown
> 
> In CMake, configure like this:
> ```

nit: extra blank line.
___
*[doc/_pages/profiling.md, line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16817#-MyhChDq1A9BwfPj4WXQ:-MyhChDq1A9BwfPj4WXR:b1t8ohw) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c799ba0ac3636eb310114be2dae425e70452be/doc/_pages/profiling.md#L59)):*
> ```Markdown
> default instrumentation settings, so we recommend running with extra flags.
> These flags will slow down data collection, but are usually worth it:
> ```

nit: extra blank line.
___
*[geometry/profiling/README.md, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16817#-MyhCoNV6X6FvJ_ieB6m:-MyhCoNV6X6FvJ_ieB6n:b-klhfqk) ([raw file](https://github.com/robotlocomotion/drake/blob/e5c799ba0ac3636eb310114be2dae425e70452be/geometry/profiling/README.md#L6)):*
> ```Markdown
> # Profiling instructions.
> 
> For installation instructions and an overview of profiling tools, refer to 
> ```

nit:  Trailing whitespace on this line.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16817)* status: 4 unresolved discussions (waiting on @jwnimmer-tri)

**Pull request merged**
