### PR TITLE
Polishes accelerometer.h.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5411)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for both levels of reviews please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5411#-:-KeTmc2YHE3fPUUo1t_L:b58faaf)*

**Comment by liangfok** [comment]
+@soonho-tri for platform review please. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5411#-:-KeZV25Qw_m7-ynd8Lkb:b-lnsuqk)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-cpplint-experimental please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5411#-:-KeZuOm3kK0WBLU92qkL:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5411#-:-Ke_v0fvy4mkNCL5UJlX:bnfp4nl)*

**Pull request merged**
