### PR TITLE
Add bindings for ConvexSet::CalcVolumeViaSampling

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@cohnt for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-:-NpMu1lc7AYRBcLzCQvP:b-uh5oqr)* status: LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by cohnt — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843)* status: 2 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 382 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhGbE-B-z1xzn1p2b:-NpVhGbE-B-z1xzn1p2c:bxz7clr) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L382)):*
> ```Python
>         self.assertGreaterEqual(sampled_volume.rel_accuracy,
>                                 desired_rel_accuracy)
>         self.assertEqual(rect.SampledVolume(), max_num_samples)
> ```

Is this a typo? Seems like the left hand side should be `sampled_volume.max_num_samples`.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-NpVhjuRDeCo_bG6nDqP:bnj8pyg) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
> ```Python
>                                 desired_rel_accuracy)
>         self.assertEqual(rect.SampledVolume(), max_num_samples)
> ```

Looks like the test was duplicated?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843)* status: 2 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 382 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhGbE-B-z1xzn1p2b:-Np_MWao89l_yXSv_mpk:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L382)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Is this a typo? Seems like the left hand side should be `sampled_volume.max_num_samples`.
</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-Np_MYO_3d2EiyCxCoS6:bvknhr1) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Looks like the test was duplicated?
</blockquote></details>

This was done intentionally. The block in `test_hyperrectangle` ensures that Hyperrectangle has access to the method. The block in `test_sampled_volume` chooses an arbitrary convex set to check that `ConvexSet` has the binding. I think that all the subclasses of convex set should be testing the bindings inheritted from `ConvexSet`, but they do not, so I don't want someone to accidentally erase the `Hyperrectangle` tests and no longer be testing this binding.

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-:-Np_Qqm55RWaNfhCRn3a:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-Np_Qnk12uh0sO0Gw6WP:bqrfamp) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This was done intentionally. The block in `test_hyperrectangle` ensures that Hyperrectangle has access to the method. The block in `test_sampled_volume` chooses an arbitrary convex set to check that `ConvexSet` has the binding. I think that all the subclasses of convex set should be testing the bindings inheritted from `ConvexSet`, but they do not, so I don't want someone to accidentally erase the `Hyperrectangle` tests and no longer be testing this binding.
</blockquote></details>

Understood!

**Review by jwnimmer-tri — COMMENTED** [review]
+@jwnimmer-tri for platform.

+(release notes: fix)

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-:-Np_P9ps23i6zuO395cB:banmm50)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-Np_OqCQ3rODkOMSULuB:-Np_OqCQ3rODkOMSULuC:br38nr2) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f60d3d372194020b09e50bda799ea8afbdb9c83/bindings/pydrake/geometry/geometry_py_optimization.cc#L131)):*
> ```cpp
>             cls_doc.ToShapeWithPose.doc)
>         .def("CalcVolume", &ConvexSet::CalcVolume, cls_doc.CalcVolume.doc)
>         .def("CalcVolumeViaSampling", &ConvexSet::CalcVolumeViaSampling,
> ```

Bindings need to be declared in topological dependency order.  In other words, SampledVolume needs to be bound before ConvexSet is bound.  Otherwise, the type signatures come out wrong (note the C++ spelling of the return type name with no hyperlink; it should be the Python spelling with a hyperlink):


___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-Np_QE-V0AYLA8r_k6ws:b-p8776n) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
Duplication is harmful to upkeep over time.

> I don't want someone to accidentally erase the `Hyperrectangle` tests and no longer be testing this binding.

In that case, keep `test_sampled_volume` and undo the changes in `test_hyperrectangle`?  (Maybe rename it to `test_calc_volume_via_sampling` for clarity?)

There's no real risk that someone moves the `CalcVolume...` binding(s) from the ConvexSet base class to Hyperrectangle subclass and it goes unnoticed during code review.  We don't need a unit test to catch that kind of mistake.

**Comment by jwnimmer-tri** [comment]
If you like, just let me know and I can push the fixes for my comments.

**Review by AlexandreAmice — COMMENTED** [review]
Sorry for the delay. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-:-Nq875aQAhIdOPsdd4KU:b1fzbqf)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/geometry_py_optimization.cc` line 131 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-Np_OqCQ3rODkOMSULuB:-Nq879mC7qO5p1htjvRO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/5f60d3d372194020b09e50bda799ea8afbdb9c83/bindings/pydrake/geometry/geometry_py_optimization.cc#L131)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Bindings need to be declared in topological dependency order.  In other words, SampledVolume needs to be bound before ConvexSet is bound.  Otherwise, the type signatures come out wrong (note the C++ spelling of the return type name with no hyperlink; it should be the Python spelling with a hyperlink):


</blockquote></details>

Done.
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-Nq86Ym77SVwBMaduCT6:b-pxew6j) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Duplication is harmful to upkeep over time.

> I don't want someone to accidentally erase the `Hyperrectangle` tests and no longer be testing this binding.

In that case, keep `test_sampled_volume` and undo the changes in `test_hyperrectangle`?  (Maybe rename it to `test_calc_volume_via_sampling` for clarity?)

There's no real risk that someone moves the `CalcVolume...` binding(s) from the ConvexSet base class to Hyperrectangle subclass and it goes unnoticed during code review.  We don't need a unit test to catch that kind of mistake.
</blockquote></details>

Sounds good. Perhaps in a later PR, we have a method which tests **all** the `ConvexSet` bindings using one of the concrete classes. Then every other subclass of `ConvexSet` would only need to check one of the methods in `ConvexSet` to know that it has all the other ones?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20843)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 414 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20843#-NpVhjuRDeCo_bG6nDqO:-Nq8Ih5K5Y1aVBqcWHcN:blkq5g5) ([raw file](https://github.com/RobotLocomotion/drake/blob/93a6f078b0163a4aeff869b7c0a42a2ddddb1089/bindings/pydrake/geometry/test/optimization_test.py#L414)):*
Having refreshed my memory on the existing test code, I'd offer a few suggestions to improve overall:

(1) Make a new dedicated file `convex_set_test.py` that tests `ConvexSex` and all of its subclasses in one place, but not the other `geometry.optimization` bindings code e.g. IRIS.  This will help focus the purpose of the file and make it easier to keep it clean.

(2) As you say, de-duplicate the testing code for "Methods inherited from ConvexSet" that's somewhat copy-pasted all over the place currently.

That could happen via one dedicated test on a representative class as you say, or it could be a helper function like ...

```py
def _check_convex_set_base(self, dut):
        self.assertIsInstance(dut.ambient_dimension(), int)
        self.assertIsInstance(dut.IntersectsWith(dut), bool)
        self.assertIsInstance(dut.IsBounded(), bool)
        self.assertIsInstance(dut.IsEmpty(), bool)
```

... that each subclass calls ...

```py
def test_hyperrectangle(self):
    rect = mut.Hyperrectangle()
    self._check_convex_set_base(rect)
    rect = mut.Hyperrectangle(lb=-self.b, ub=self.b)
    np.testing.assert_array_equal(rect.lb(), -self.b)
    ... more Hyperrectangle-unique bindings tests ...
```

> Then every other subclass of `ConvexSet` would only need to check one of the methods in `ConvexSet` to know that it has all the other ones?

(3) Even that is more work than necessary.  To test the `py::class_<Hyperrectangle, ConvexSet>(m, "Hyperrectangle", cls_doc.doc)` line of bindings code, all we need is `self.assertIsInstance(rect, ConvexSet)` somewhere, we don't actually need to call any bound functions.

**Comment by jwnimmer-tri** [comment]
Oops, I forgot the :lgtm: stamp.

**Pull request merged**
