### PR TITLE
Add common/unused.h and use it in framework

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This doesn't have tool support to keep it from bitrotting, but I think it's still worth improving a bit now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5788)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for feature review, please.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhPblnhxacyK2nwK2Eh:b-vawmhb)*

**Comment by soonho-tri** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/unused.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhPdK0gkBdVqhvgbhOl:-KhPdK0gkBdVqhvgbhOm:b-4gd10f) ([raw file](https://github.com/robotlocomotion/drake/blob/4c48e0fbf0d9e1ab29e241753fb9e87959d257cb/drake/common/unused.h#L7)):*
> ```objc
> /// Documents the argument as unused.  This can be added within function bodies
> /// to mark that certain parameters are unused.  (However, note that removing
> /// the unused parameter is a superior solution, when possible.)
> ```

Is it the case that the decision also depends on whether a file is `.h` or `.cc`? From the PR, I can tell:

 - If it's `.cc`, it's better to remove the unused param.
 - If it's `.h` (and template definition), use `unused(param)` in the function body.

If this is the case, it seems that it's better to document it somewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by soonho-tri** [comment]
:lgtm: (aside one BTW)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhPfYOqgdWN2oBfX9Hw:bm9b64f)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/unused.h, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhPdK0gkBdVqhvgbhOl:-KhS5M2s9hEEAlpaCwpF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c48e0fbf0d9e1ab29e241753fb9e87959d257cb/drake/common/unused.h#L7)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Is it the case that the decision also depends on whether a file is `.h` or `.cc`? From the PR, I can tell:

 - If it's `.cc`, it's better to remove the unused param.
 - If it's `.h` (and template definition), use `unused(param)` in the function body.

If this is the case, it seems that it's better to document it somewhere.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhS5ObigDnFl3woTBJZ:bppyoqq)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/unused.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSFl-pbtsHPzKeD8bM:-KhSFl-qML0AwNj0AmcA:b-s7ch9t) ([raw file](https://github.com/robotlocomotion/drake/blob/ce6d1fec8107afd7199f5bd863dec50b16971964/drake/common/unused.h#L19)):*
> ```objc
> void unused(const T&) {}
> 
> }
> ```

FYI, 
```
Namespace should be terminated with "// namespace drake"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/unused.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSFl-pbtsHPzKeD8bM:-KhSG0XxRziXSaIjbW7i:bvxcm25) ([raw file](https://github.com/robotlocomotion/drake/blob/ce6d1fec8107afd7199f5bd863dec50b16971964/drake/common/unused.h#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, 
```
Namespace should be terminated with "// namespace drake"
```
</blockquote></details>

FWIW, I have a `'before-save-hook` calling `clang-format` which fixes this kind of warnings automatically ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by jwnimmer-tri** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/unused.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSFl-pbtsHPzKeD8bM:-KhSJtShszn9Ww6ccBUl:b-3s430v) ([raw file](https://github.com/robotlocomotion/drake/blob/ce6d1fec8107afd7199f5bd863dec50b16971964/drake/common/unused.h#L19)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FWIW, I have a `'before-save-hook` calling `clang-format` which fixes this kind of warnings automatically ;-)
</blockquote></details>

Done.

Sorry, I was careless and was only running `bazel build` and not `bazel test`, so I didn't get my cpplint checks locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by sherm1** [comment]
I like it - a few BTWs. :lgtm: A possible beautification would be if unused() could take a variable number of variable-type arguments to allow `unused(context, input, state);`.

---

Reviewed 7 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/BUILD, line 270 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSq80Ia7TPsBcsPgbG:-KhSq80Ia7TPsBcsPgbH:b-u5v6yg) ([raw file](https://github.com/robotlocomotion/drake/blob/7be26a807e1f565cd49ab313b56499eac011e4de/drake/common/BUILD#L270)):*
> ```Python
>     hdrs = ["unused.h"],
>     deps = [
>         ":common",
> ```

BTW I see that this includes drake_compat.h but I don't understand why. Without that it wouldn't have any dependencies -- wouldn't that be better?

---

*[drake/common/unused.h, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSpxSU76c0D3jecchV:-KhSpxSU76c0D3jecchW:bqxgnq5) ([raw file](https://github.com/robotlocomotion/drake/blob/7be26a807e1f565cd49ab313b56499eac011e4de/drake/common/unused.h#L3)):*
> ```objc
> #pragma once
> 
> #include "drake/common/drake_compat.h"
> ```

BTW why include this here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhSrS5t4XlMpt6SFh3P:b4hc663)*

**Comment by jwnimmer-tri** [comment]
Oh, nice idea.  I will see if I can get that working.  +(status: do not merge) 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/unused.h, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-KhSpxSU76c0D3jecchV:-KhStiJQxThgnXZu3CNc:batmpnt) ([raw file](https://github.com/robotlocomotion/drake/blob/7be26a807e1f565cd49ab313b56499eac011e4de/drake/common/unused.h#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why include this here?
</blockquote></details>

The idea is that `drake_compat.h` is included (at least transitively) by every single file within Drake.  Since this file doesn't include any others, it should to include the compat header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhStd7shGcl45IJccc_:b-hhlgfy)*

**Comment by jwnimmer-tri** [comment]
PTAL -(status: do not merge) 

---

Review status: 7 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhTE0aC-j_BUwXehQTh:b20vaa4)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788)*

**Comment by sherm1** [comment]
Sweet! :lgtm_strong: (pending CI)

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5788#-:-KhTIE7C6KHRpEN5Xxro:b-fko8ja)*

**Pull request merged**
