### PR TITLE
libdrake: Remove ODR violation for linking in `@osqp`

### LINKED ISSUE #10025: drake_shared_library: Trivial `drake_cc_test` fails ASan
From #10027, reproduction of what @jwnimmer-tri found in CI for `pydrake/util:alias_cc_test`:

```
$ export CC=clang-6.0 CXX=clang++-6.0 FC=gfortran-5.4
$ bazel test --config=asan //tools/install/libdrake:drake_shared_library_test
==================== Test output for //tools/install/libdrake:drake_shared_library_test:
=================================================================
==19==ERROR: AddressSanitizer: odr-violation (0x7f39d2056540):
  [1] size=48 'SuiteSparse_config' external/osqp/lin_sys/direct/qdldl/amd/src/SuiteSparse_config.c:57:34
  [2] size=48 'SuiteSparse_config' external/osqp/lin_sys/direct/qdldl/amd/src/SuiteSparse_config.c:57:34
These globals were registered at these points:
  [1]:
    #0 0x55ab252f6c10  (/ssd/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/execroot/drake/bazel-out/k8-opt/bin/tools/install/libdrake/drake_shared_library_test+0x31c10)
    #1 0x7f39cfc3c5fb  (/ssd/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/execroot/drake/bazel-out/k8-opt/bin/tools/install/libdrake/../../../_solib_k8/_U_S_Stools_Sinstall_Slibdrake_Cdrake_Ushared_Ulibrary___Utools_Sinstall_Slibdrake/libdrake.so+0x719a5fb)

  [2]:
    #0 0x55ab252f6c10  (/ssd/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/execroot/drake/bazel-out/k8-opt/bin/tools/install/libdrake/drake_shared_library_test+0x31c10)
    #1 0x7f39c146655b  (/ssd/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/execroot/drake/bazel-out/k8-opt/bin/tools/install/libdrake/../../../_solib_k8/libexternal_Sosqp_Slibosqp.so+0xf55b)

==19==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'SuiteSparse_config' at external/osqp/lin_sys/direct/qdldl/amd/src/SuiteSparse_config.c:57:34
==19==ABORTING
```

\cc @jwnimmer-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #10025

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10027)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please.

**Comment by jwnimmer-tri** [comment]
(After the next push, remember to opt-in to the asan build also, to make sure it's really fixed.)

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-asan please.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
Oops, forgot my :lgtm: emoji.

**Pull request merged**
