### PR TITLE
Add overloading for relational opreators between symbolic eigen arrays

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5505)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , could you feature-review this PR?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-:-KfINqSQKKdFgIpmzC36:bhtid5c)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 330 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfISmo-pV58D85DLlA7:-KfISmo-pV58D85DLlA8:b-elfdwj) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/symbolic_formula.h#L330)):*
> ```objc
>                      Formula>::value,
>     Eigen::Array<Formula, DerivedA::RowsAtCompileTime,
>                  DerivedB::ColsAtCompileTime>>::type
> ```

Why use `DerivedB::ColsAtCompileTime`? Is it OK to use
```C++
Eigen::Array<Formula, DerivedA::RowsAtCompileTime == Eigen::Dynamic ? DerivedB::RowsAtCompileTime : DerivedA::RowsAtCompileTime, DerivedA::ColsAtCompileTime == Eigen::Dynamic ? DerivedB::ColsAtCompileTime : DerivedA::ColsAtCompileTime>
```

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfITnPvpywjlJk23iDw:-KfITnPwCr1-ptXpy0ma:bfcpwui) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/test/symbolic_expression_matrix_test.cc#L40)):*
> ```cpp
>   Eigen::Matrix<Expression, 3, 2, Eigen::DontAlign> C_;
> 
>   Eigen::Matrix<Expression, 2, 2, Eigen::DontAlign> matrix_expr_1_;
> ```

Out of curiosity, why we use `Eigen::DontAlign` here? Is it because of the alignment issue of the fixed size eigen matrix, as explained here https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html and https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html?

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfIUi7S49iGU1i1Klx9:-KfIUi7S49iGU1i1KlxA:b-ed3isu) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/test/symbolic_expression_matrix_test.cc#L204)):*
> ```cpp
>         std::is_base_of<Eigen::MatrixBase<DerivedB>, DerivedB>::value,
>     bool>::type
> CheckArrayOperatorEq(const DerivedA& m1, const DerivedB& m2) {
> ```

Maybe rename this function to `CheckMatrixOperatorEq`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 330 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfISmo-pV58D85DLlA7:-KfIWk9FG2WWpwR7QvMO:b-suwp36) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/symbolic_formula.h#L330)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why use `DerivedB::ColsAtCompileTime`? Is it OK to use
```C++
Eigen::Array<Formula, DerivedA::RowsAtCompileTime == Eigen::Dynamic ? DerivedB::RowsAtCompileTime : DerivedA::RowsAtCompileTime, DerivedA::ColsAtCompileTime == Eigen::Dynamic ? DerivedB::ColsAtCompileTime : DerivedA::ColsAtCompileTime>
```
</blockquote></details>

Good point. I'll also check if Eigen provides a shorthand macro for that.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 40 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfITnPvpywjlJk23iDw:-KfIVxkqURTEdoZ95xxR:bgd2ts3) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/test/symbolic_expression_matrix_test.cc#L40)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Out of curiosity, why we use `Eigen::DontAlign` here? Is it because of the alignment issue of the fixed size eigen matrix, as explained here https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html and https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html?
</blockquote></details>

That's right. Actually, I think we only need `DontAlign` for `double` cases. Am I correct? If so, I'll remove `DontAlgin` for non-double cases.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 204 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfIUi7S49iGU1i1Klx9:-KfIW8QeGQlRvL-P_2eb:b-imwfmu) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/test/symbolic_expression_matrix_test.cc#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Maybe rename this function to `CheckMatrixOperatorEq`?
</blockquote></details>

We have another function `CheckMatrixOperatorEq` below. That function checks `Formula operator==(const Eigen::Matrix<Expression>&, const Eigen::Matrix<Expression>&)`. This one is checking `operator==` returning `Eigen::Array`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 330 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfISmo-pV58D85DLlA7:-KfIYd6L0m0fUs0d24xL:b-behwc6) ([raw file](https://github.com/robotlocomotion/drake/blob/6db8888950127204f7daf26cf13ad4a2f92a2ea0/drake/common/symbolic_formula.h#L330)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Good point. I'll also check if Eigen provides a shorthand macro for that.
</blockquote></details>

I think we can use `EIGEN_SIZE_MIN_PREFER_FIXED`:

https://github.com/RobotLocomotion/eigen-mirror/blob/224ee8d9e3606749c00fe71266af15f4066ecf07/Eigen/src/Core/util/Macros.h#L886-L894

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula.h, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfMNK-9-naTQgX2DFF2:-KfMNK-AuSaFHeqZlxiP:bl6m7ks) ([raw file](https://github.com/robotlocomotion/drake/blob/9fc311d67d3cc1286c4875f8f1674c9f230bc149/drake/common/symbolic_formula.h#L327)):*
> ```objc
> /// element-wise comparison of two arrays @p a1 and @p a2 using
> /// less-than-or-equal operator (<=).
> template <typename DerivedA, typename DerivedB>
> ```

BTW Wow, this signature is a lot of boilerplate.  (I'm not requesting that anything be done about it since I don't have any good ideas and I don't know if the bad ones (e.g. preprocessor macro) would even work).  C++ still has the power to amaze me sometimes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-:-KfMOaC4O6AW0xw3Bidu:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/common/symbolic_formula.h, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5505#-KfMNK-9-naTQgX2DFF2:-KfMPCwVz8s02ZtYkVUl:b-lz21d7) ([raw file](https://github.com/robotlocomotion/drake/blob/9fc311d67d3cc1286c4875f8f1674c9f230bc149/drake/common/symbolic_formula.h#L327)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW Wow, this signature is a lot of boilerplate.  (I'm not requesting that anything be done about it since I don't have any good ideas and I don't know if the bad ones (e.g. preprocessor macro) would even work).  C++ still has the power to amaze me sometimes.
</blockquote></details>

I'll try to make a better version and open a PR (when I find one).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5505)*

**Pull request merged**
