### PR TITLE
Add symbolic Evaluate for symbolic matrices

### LINKED ISSUE #9049: Feature request: Sugar function to evaluate a matrix of symbolic expressions with an Environment
In the symbolic::Expression class, It would be helpful to have a "sugar function (static method) -- possibly called Evaluate -- whose first argument is a matrix of symbolic expressions and whose second argument is a symbolic::Environment (maps symbolic variables to values).

Ideally, this "sugar" function would evaluate each of its elements and return an appropriately sized matrix of type double.  

If the symbolic expression fails to evaluate to a number, it should throw an exception (at least for this sugar function).

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #9049

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@mitiguy for feature-review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073#-:-LG69TaZ1UDR6v4WcwC4:br54kju)*

**Comment by mitiguy** [comment]
:lgtm:
See BTW below.

---

Review status: all discussions resolved, platform LGTM missing

---

*[common/test/symbolic_expression_matrix_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG6kyKf8AmzyZ9e5ywc:-LG6kyKf8AmzyZ9e5ywd:b-xssgso) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/test/symbolic_expression_matrix_test.cc#L465)):*
> ```cpp
>        y_, z_;
>   // clang-format on
>   EXPECT_THROW(Evaluate(C, env).eval(), std::runtime_error);
> ```

BTW:  I am unsure where the exception is thrown.  
Is it during Evaluate() or .eval() ?
Consider breaking this into something like the following:

  MatrixX<Expression> C(2, 2);
  // clang-format off
  C << x_, Expression::NaN(),
           y_, z_;
  // clang-format on

const Eigen::Matrixxd C_evaluated{Evaluate(C, env)};
EXPECT_THROW(C_evaluated.eval(), std::runtime_error);

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073#-:-LG6xSZF7870tnuqDU5s:banmz26)*

**Comment by soonho-tri** [comment]
Review status: all discussions resolved, platform LGTM missing

---

*[common/test/symbolic_expression_matrix_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG6kyKf8AmzyZ9e5ywc:-LG6yOibCRCFWeObofi_:b6mo74b) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/test/symbolic_expression_matrix_test.cc#L465)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

BTW:  I am unsure where the exception is thrown.  
Is it during Evaluate() or .eval() ?
Consider breaking this into something like the following:

  MatrixX<Expression> C(2, 2);
  // clang-format off
  C << x_, Expression::NaN(),
           y_, z_;
  // clang-format on

const Eigen::Matrixxd C_evaluated{Evaluate(C, env)};
EXPECT_THROW(C_evaluated.eval(), std::runtime_error);
</blockquote></details>

FYI, we have `.eval()` in the body of the new `Evaluate` function
```c++
  return m.unaryExpr([&env](const Expression& e) { return e.Evaluate(env); })
      .eval();
```
as a result, the exception occurs when `Evaluate(C, env)` is called. I can remove `.eval()` from the body. I was thinking about it shortly and chose eager-evaluation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)*

**Comment by soonho-tri** [comment]
+@sherm1 for platform-review, please. (per schedule, tomorrow)

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073#-:-LG6zSik4HPaZZbvS-dK:b-1kv02v)*

**Comment by sherm1** [comment]
Platform :lgtm: pending a couple of small comments.

---

Reviewed 3 of 3 files at r1.
Review status: 2 unresolved discussions, platform LGTM from [sherm1]

---

*[common/symbolic_expression.h, line 762 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8lHD-A02KfCgAuKg0:-LG8lHD0-YsyoSHZ-jjT:bhj9dr9) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/symbolic_expression.h#L762)):*
> ```objc
>                 "Evaluate only accepts a symbolic matrix.");
>   return m.unaryExpr([&env](const Expression& e) { return e.Evaluate(env); })
>       .eval();
> ```

Minor: can you explain why the `.eval()` is needed here? I would have thought that e.Evaluate(env) does, well, evaluate! If it is needed, please consider adding a comment saying why.

---

*[common/test/symbolic_expression_matrix_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8kMnNAmQA9BWshZ6R:-LG8kMnNAmQA9BWshZ6S:bp2bono) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/test/symbolic_expression_matrix_test.cc#L465)):*
> ```cpp
>        y_, z_;
>   // clang-format on
>   EXPECT_THROW(Evaluate(C, env).eval(), std::runtime_error);
> ```

Minor: consider using DRAKE_EXPECT_THROWS_MESSAGE() to ensure that the returned error message is the correct one (i.e. a complaint about NaN).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073#-:-LG8lbci0wnEdv85CayL:bg4yk84)*

**Comment by soonho-tri** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---

*[common/symbolic_expression.h, line 762 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8lHD-A02KfCgAuKg0:-LGAqglkBGfjjpA7HCFy:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/symbolic_expression.h#L762)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: can you explain why the `.eval()` is needed here? I would have thought that e.Evaluate(env) does, well, evaluate! If it is needed, please consider adding a comment saying why.
</blockquote></details>

Done

---

*[common/test/symbolic_expression_matrix_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG6kyKf8AmzyZ9e5ywc:-LGAqZVg5KCdD-jNftZs:b-nl1pi9) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/test/symbolic_expression_matrix_test.cc#L465)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, we have `.eval()` in the body of the new `Evaluate` function
```c++
  return m.unaryExpr([&env](const Expression& e) { return e.Evaluate(env); })
      .eval();
```
as a result, the exception occurs when `Evaluate(C, env)` is called. I can remove `.eval()` from the body. I was thinking about it shortly and chose eager-evaluation.
</blockquote></details>

The trailing `.eval()` was redundant. I removed it.

---

*[common/test/symbolic_expression_matrix_test.cc, line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8kMnNAmQA9BWshZ6R:-LGAqWB08AcfcglBTgvp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/test/symbolic_expression_matrix_test.cc#L465)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Minor: consider using DRAKE_EXPECT_THROWS_MESSAGE() to ensure that the returned error message is the correct one (i.e. a complaint about NaN).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)*

**Comment by jwnimmer-tri** [comment]
*[common/symbolic_expression.h, line 762 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8lHD-A02KfCgAuKg0:-LGB-vcI31pFfpsPOXkq:b-hpnrtr) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/symbolic_expression.h#L762)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done
</blockquote></details>

FYI A link to https://eigen.tuxfamily.org/dox/TopicPitfalls.html would be more terse.  In general, I think it should be common knowledge that `Eigen` + `auto` means you need to say `eval`, though placing a reminder hyperlink is OK too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)*

**Comment by sherm1** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)*

**Comment by soonho-tri** [comment]
Review status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1]

---

*[common/symbolic_expression.h, line 762 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9073#-LG8lHD-A02KfCgAuKg0:-LGB6klL1Jd_V2YQbj_Y:bnmf9vl) ([raw file](https://github.com/robotlocomotion/drake/blob/6105d97b537736689776d3206ab0ca4446bde2b3/common/symbolic_expression.h#L762)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI A link to https://eigen.tuxfamily.org/dox/TopicPitfalls.html would be more terse.  In general, I think it should be common knowledge that `Eigen` + `auto` means you need to say `eval`, though placing a reminder hyperlink is OK too.
</blockquote></details>

Done (Added the hyperlink)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9073)*

**Pull request merged**
