### PR TITLE
Adds python bindings for van der pol oscillator example.

### PR DESCRIPTION
**Pull request by RussTedrake**
also fix transmogrification, and add the recommended unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8594)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
Platform :lgtm: pending a few BTWs.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bindings/pydrake/examples/van_der_pol_py.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zXYgk0suAjPlrFeos:-L9zXYgk0suAjPlrFeot:b-u7z9w7) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/van_der_pol_py.cc#L1)):*
> ```cpp
> #include "pybind11/eigen.h"
> ```

BTW unused?

---

*[bindings/pydrake/examples/test/van_der_pol_test.py, line 7 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zX6mM03LzeOJzagnr:-L9zX6mM03LzeOJzagns:b-57lcd6) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/test/van_der_pol_test.py#L7)):*
> ```Python
> import numpy as np
> 
> import pydrake.systems.framework as framework
> ```

BTW some of the above appear to be unused. Are these all needed?

---

*[bindings/pydrake/examples/test/van_der_pol_test.py, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zXBeYBcM_pREI4jid:-L9zXBeYBcM_pREI4jie:b-5ouspo) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/test/van_der_pol_test.py#L14)):*
> ```Python
> class TestVanDerPol(unittest.TestCase):
>     def test_simulation(self):
>         # Basic constant-torque rimless_wheel simulation.
> ```

BTW copy pasta

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-:-L9zXdWf6g2qbKwuE-wV:b-i06ut8)*

**Comment by RussTedrake** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/examples/van_der_pol_py.cc, line 1 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zXYgk0suAjPlrFeos:-LA5j6s5BW_rmNVesuHM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/van_der_pol_py.cc#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unused?
</blockquote></details>

Done.

---

*[bindings/pydrake/examples/test/van_der_pol_test.py, line 7 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zX6mM03LzeOJzagnr:-LA5jHhV0Dp3ATvO-Jev:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/test/van_der_pol_test.py#L7)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW some of the above appear to be unused. Are these all needed?
</blockquote></details>

Done.

---

*[bindings/pydrake/examples/test/van_der_pol_test.py, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594#-L9zXBeYBcM_pREI4jid:-LA5jI-30BjNcqOLAhrz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0978b487e3b8a10e47cd71c879b3badb19eb5511/bindings/pydrake/examples/test/van_der_pol_test.py#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW copy pasta
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8594)*

**Pull request merged**
