### PR TITLE
[FEM] Add analytic solution test for elasticity

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
- Create a setup under which the solution obtained from the FEM solver
can be tested against the analytic solution calculated by pen and paper.

- Document the pen and paper analytic solution.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MUkLOu8-7hVcrKp_0eU:bwshpyi)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Per Slack discussion, the review of #14723 is higher priority. I'll put this on hold until I look at 14723 first.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MUnDStu6S8Rk8e9kDr2:bw85ouw)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MUughJF9z6bc-lbstUB:-MUughJF9z6bc-lbstUC:blnth5g) (no related file):*
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

---

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MUughJF9z6bc-lbstUB:-MUuhD-s7sQWs1gyFz8k:bet4yzy) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
</blockquote></details>

@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

---

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri this PR is ready for review. It has a lower priority.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MUv0SSm3EMw3EZgNu27:b-gb80mu)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Review pass done. This is great!

> Reviewed 2 of 15 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MVWvzDl8XKsSHSS8bjs:b-61cnjs)* status: 15 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWm1obDcDSabasPDgA:-MVWm1obDcDSabasPDgB:b-by74af) (no related file):*
> Minor bug fixes in FemModelBase API:

not true anymore. Update the PRs description

---
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWtZsPC2kpeHYOEC2n:-MVWtZsPC2kpeHYOEC2o:b-4v73nu) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L25)):*
> ```TeX
> \begin{figure}[!h]
> 	\centering
> 	\includegraphics[width=0.5\columnwidth]{stretch_bar.png}
> ```

nit, the figure shows a rectangular block, though in reality is a block of equal sized sides. Not big deal, but you might consider updating either the figure to match the text  or the setup to match the figure (this last option would be nice to break the "numerical symmetry" of the problem, to make the unit test yet more interesting).
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWs8VrAtpLSyq21kf3:-MVWs8VrAtpLSyq21kf4:bgdfvqz) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L27)):*
> ```TeX
> 	\includegraphics[width=0.5\columnwidth]{stretch_bar.png}
> 	\caption{\label{fig:problem}
> 		Problem description.}
> ```

Reviewable shows me lil red marks here. I believe those are tabs? see if you can get rid of them.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWtRdj776ha9wrV69H:-MVWtRdj776ha9wrV69I:bfezy6t) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L30)):*
> ```TeX
> \end{figure}
> 
> We consider an elastic block stretched on the side by Dirichlet boundary
> ```

mention that the block actually is a box of size L x L x L.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWvLzNEkMZOsa3ujsl:-MVWvLzNEkMZOsa3ujsm:b-j78dcj) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L35)):*
> ```TeX
> elasticity with Young's modulus $E$ and Poisson ratio $\nu$. We apply Dirichlet
> boundary condition at $y = \frac{L}{2}$ and $y = -\frac{L}{2}$ so that the bar
> is stretched by a factor of $s$ in the $y$-direction. In other words, the
> ```

nit, consider saying instead "the bar is stretched by a factor of 1+ε in the y-direction."

This replaces s with ε, which has the nice meaning of linear straing in your equation. Then nicely, the equation for c (or \sigma as I propose below) reads σ = E ε.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWsQIA24K1v5vgf76W:-MVWsQIA24K1v5vgf76X:bbngjvm) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L39)):*
> ```TeX
> 	u_3(x,y,z))^T$ takes the form
> \begin{align*}
> 	u_2(x,-L,z) = -(s-1)L \\
> ```

This should be `u_2(x,-L/2,z) = -(s-1)L/2`? (and `u_2(x,L/2,z) = (s-1)L/2`)
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWsd2Z19fvPxVEJ-Mq:-MVWsd2Z19fvPxVEJ-Mr:b-sthuvh) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L47)):*
> because otherwise the solution would not be unique

That is true when solving things numerically. Mathematically (what this doc is about) what people usually do is to allude to the "symmetry" of the problem and then, in this case, solve an equivalent problem with just a fourth of the bar's section in the domain Ω = [0; L/2]×[−L/2; L/2]×[0; L/2]. 

N.B. Similarly, with additional symmetry along y, you'd only need to solver for an eight of the domain.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWugDZ7FnnDh806_wE:-MVWugD_AL5-GT_Onomz:b6j7q14) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L92)):*
> ```TeX
> 	\epsilon_{33}) = 0 \label{eq:P11},                                     \\
> 	P_{22} & = 2\mu\epsilon_{22} + \lambda(\epsilon_{11} + \epsilon_{22} +
> 	\epsilon_{33}) = c \label{eq:P22},                                     \\
> ```

nit, you might, right here, use another symbol for `c`, like `\sigma`?, to allude to the fact that this is the value of the uniaxial stress along the y direction. Still a constant of course.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWv3iF4GYtEoO8PylC:-MVWv3iF4GYtEoO8PylD:b-158bg) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L118)):*
> ```TeX
> \end{align}
> where $h_1, h_2, h_3$ are arbitrary functions resulting from integration.
> Using boundary conditions $u_2(x,L,z) = (s-1)L$ and $u_2(x,-L,z) = -(s-1)L$, we
> ```

L --> L/2 (it turns out it cancels out and you get the same constant c)
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWmzLJ-t0SPxDnyhdB:-MVWmzLJ-t0SPxDnyhdC:bngv85o) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L32)):*
> ```cpp
> using ModelType = StaticElasticityModel<ElementType>;
> using geometry::VolumeMesh;
> const double kYoungsModulus = 7.89;
> ```

nit, Given this is a full example, it would not hurt to use parameter values for real materials. Unless these are not Pa? state units just in case.
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWnM8D7mvrKY9ADEw-:-MVWnM8D7mvrKY9ADEw0:b-j0vvrl) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L47)):*
> ```cpp
>     /* It's important to set kL/dx to be a power of 2, so that the appropriate
>      boundary conditions at x = 0 and z = 0 can be applied. The test, however,
>      does pass without those boundary conditions as well even though the
> ```

could you say more about this? is that because you are using an iterative solver?
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWnkr25jUCYgUSHn7U:-MVWnkr38b4d4WAOoHCE:b3moi0m) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L101)):*
> ```cpp
>       const DofIndex y_dof_index(kSolutionDimension * node + 1);
>       const DofIndex z_dof_index(kSolutionDimension * node + 2);
>       /* No shift in the xz-plane. */
> ```

nit, shift --> translation?
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 110 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWo5-tC9Oggdr4zf4e:-MVWo5-tC9Oggdr4zf4f:bcldh11) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L110)):*
> ```cpp
>                                  Vector1<T>(kStretchFactor * q(y_dof_index)));
>       }
>       /* No shift in the xz-plane. */
> ```

nit xz --> xy
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWo0EJ6zd3Gi0xxfpu:-MVWo0EKBY8refLl_uCH:b7l0gsr) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L113)):*
> ```cpp
>       if (std::abs(q(z_dof_index)) <= kEpsilon) {
>         bc->AddBoundaryCondition(z_dof_index, Vector1<T>(q(z_dof_index)));
>       }
> ```

the boundary conditions on the xz and xy planes are kinda odd in that, traditionally, you'd set a "symmetry" boundary condition (effectively the same thing here, nothing new) and you'd only model a fourth of the domain.
As setup here, you are effectively solving the same problem times four (your tangent matrix will have four diagonal blocks that do not couple with each other).
My preference would be to use the symmetry of the problem, that'd definitely make your writeup look nicer.
Otherwise, at least document this choice.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for the review. I addressed the comment, PTAL, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MVYAkEy4mlA5WFL2--q:b-4xrrqy)* status: 11 unresolved discussions, LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWm1obDcDSabasPDgA:-MVXcuvI9umAL-2A2jr_:b-ytedve) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> Minor bug fixes in FemModelBase API:

not true anymore. Update the PRs description
</blockquote></details>

Good catch! Done, thanks!

---
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 25 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWtZsPC2kpeHYOEC2n:-MVXdfcH-QRe79Kj6A3W:b159tml) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, the figure shows a rectangular block, though in reality is a block of equal sized sides. Not big deal, but you might consider updating either the figure to match the text  or the setup to match the figure (this last option would be nice to break the "numerical symmetry" of the problem, to make the unit test yet more interesting).
</blockquote></details>

I changed to setup to match the text and figure.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWs8VrAtpLSyq21kf3:-MVXd6rLCNEI0Zar4KwA:b-t46x18) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Reviewable shows me lil red marks here. I believe those are tabs? see if you can get rid of them.
</blockquote></details>

Could be. It's the result of formatting tools from VSCode. I'm reluctant to fix it unless there's some formatting guidelines for .tex files.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWtRdj776ha9wrV69H:-MVXdlRY1tVbRxVd0Frg:b-i0xc5c) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L30)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

mention that the block actually is a box of size L x L x L.
</blockquote></details>

Not anymore :)
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 35 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWvLzNEkMZOsa3ujsl:-MVXgbdG3epP2qJoyde9:b2gero4) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L35)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, consider saying instead "the bar is stretched by a factor of 1+ε in the y-direction."

This replaces s with ε, which has the nice meaning of linear straing in your equation. Then nicely, the equation for c (or \sigma as I propose below) reads σ = E ε.

</blockquote></details>

Good call! Done, thanks.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWsQIA24K1v5vgf76W:-MVXgpnWDvAb4yixVR5R:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This should be `u_2(x,-L/2,z) = -(s-1)L/2`? (and `u_2(x,L/2,z) = (s-1)L/2`)
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWsd2Z19fvPxVEJ-Mq:-MVXwsLgCmWmoWSDc4rT:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L47)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> because otherwise the solution would not be unique

That is true when solving things numerically. Mathematically (what this doc is about) what people usually do is to allude to the "symmetry" of the problem and then, in this case, solve an equivalent problem with just a fourth of the bar's section in the domain Ω = [0; L/2]×[−L/2; L/2]×[0; L/2]. 

N.B. Similarly, with additional symmetry along y, you'd only need to solver for an eight of the domain.

</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWugDZ7FnnDh806_wE:-MVXhk6j-lKWA7HO1sJH:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L92)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, you might, right here, use another symbol for `c`, like `\sigma`?, to allude to the fact that this is the value of the uniaxial stress along the y direction. Still a constant of course.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWv3iF4GYtEoO8PylC:-MVXhjDAAllR-DR-wKBq:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L118)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

L --> L/2 (it turns out it cancels out and you get the same constant c)
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWmzLJ-t0SPxDnyhdB:-MVXis8_1OgUZDfKR92K:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, Given this is a full example, it would not hurt to use parameter values for real materials. Unless these are not Pa? state units just in case.
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWnM8D7mvrKY9ADEw-:-MVXiuQW2sARI1bIpMCb:b-3xytif) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L47)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

could you say more about this? is that because you are using an iterative solver?
</blockquote></details>

It's because of the symmetry. Without the boundary condition, the gradient of the residual happens to be pointing at the solution that we would have arrived at with the boundary condition, among the infinite number of solutions.
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 101 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWnkr25jUCYgUSHn7U:-MVXhtjJEPOLNwMVTiO6:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L101)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, shift --> translation?
</blockquote></details>

Done, thanks!
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 110 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWo5-tC9Oggdr4zf4e:-MVXi1dfAv-4Jd005nCB:blpiph5) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L110)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit xz --> xy
</blockquote></details>

It should be xz, right?
___
*[multibody/fixed_fem/dev/test/stretch_test.cc, line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWo0EJ6zd3Gi0xxfpu:-MVXwuSK0af1tuita9lw:b-mvlssv) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/test/stretch_test.cc#L113)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

the boundary conditions on the xz and xy planes are kinda odd in that, traditionally, you'd set a "symmetry" boundary condition (effectively the same thing here, nothing new) and you'd only model a fourth of the domain.
As setup here, you are effectively solving the same problem times four (your tangent matrix will have four diagonal blocks that do not couple with each other).
My preference would be to use the symmetry of the problem, that'd definitely make your writeup look nicer.
Otherwise, at least document this choice. 
</blockquote></details>

I changed to only solve for a quarter of the original domain, PTAL, thanks.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWs8VrAtpLSyq21kf3:-MVYlpwa8NS6NMbwNnzd:btcghk0) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could be. It's the result of formatting tools from VSCode. I'm reluctant to fix it unless there's some formatting guidelines for .tex files.
</blockquote></details>

humm.... not sure. I believe we always at least try to get rid of these. 
Maybe @mitiguy or @sherm1 have more experience with this? 
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVYmEs_DqCy3I72vWgy:-MVYmEs_DqCy3I72vWgz:b-qo4hq0) ([raw file](https://github.com/robotlocomotion/drake/blob/ee228b691fdeb16579d61b6a5f8325060a7988b3/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L40)):*
> ```TeX
> \begin{align*}
> 	u_2(x,-\frac{L}{2},z) = -\frac{\epsilon L}{2} \\
> 	u_2(x,\frac{L}{2},z) = -\frac{\epsilon L}{2}.
> ```

+ sign?

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)* status: 1 unresolved discussion, LGTM missing from assignee amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVYmEs_DqCy3I72vWgy:-MVYnYyI1N-__W8EPx9I:b-ovu79p) ([raw file](https://github.com/robotlocomotion/drake/blob/ee228b691fdeb16579d61b6a5f8325060a7988b3/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

+ sign?
</blockquote></details>

`+sign`

**Review by amcastro-tri — COMMENTED** [review]
Good suff, :lgtm_strong:.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721#-:-MVYnboeCchZOr5BAEyZ:bszpb68)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWs8VrAtpLSyq21kf3:-MVo2Vd98k9mtzop6Djx:b-h7luh7) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

humm.... not sure. I believe we always at least try to get rid of these. 
Maybe @mitiguy or @sherm1 have more experience with this? 
</blockquote></details>

I fixed it. Just need to be careful not to blindly run reformat on VSCode.
___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVYmEs_DqCy3I72vWgy:-MVo2b6d2fZAas-zDl10:b-ytedve) ([raw file](https://github.com/robotlocomotion/drake/blob/ee228b691fdeb16579d61b6a5f8325060a7988b3/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L40)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`+sign`
</blockquote></details>

Good catch! Done, thanks!

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 40 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVYmEs_DqCy3I72vWgy:-MVoIjlO3Xc9pzUZ8PN0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ee228b691fdeb16579d61b6a5f8325060a7988b3/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L40)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good catch! Done, thanks!
</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14721)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/doc/stretch_bar_test.tex, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14721#-MVWs8VrAtpLSyq21kf3:-MVq0g6076Qcg-6Ia4S_:b-hcdpgl) ([raw file](https://github.com/robotlocomotion/drake/blob/f46524b35168e19d9b458f5fe83bc0e29639e2b2/multibody/fixed_fem/dev/doc/stretch_bar_test.tex#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I fixed it. Just need to be careful not to blindly run reformat on VSCode.
</blockquote></details>

vccode's reformat is super nice. Maybe it can be configured to it right? (we have a DrakeDevelopers vscode channel, maybe someone knows)

**Pull request merged**
