### PR TITLE
Allows parsing of URDFs with dual offsets

### PR DESCRIPTION
**Pull request by naveenoid**
Fixes https://github.com/RobotLocomotion/drake/issues/4069 

Unit tests included.

+@liangfok for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4087)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
#4058 will conflict with this.  Consider whether this can wait for a day or two?

**Comment by naveenoid** [comment]
I have a couple of PRs waiting on this fix. But considering that they too must be rebased post #4058, I guess I will have to wait.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KW5DDt-1-5nfFXu7c_a:b-l8ifc8)*

**Comment by liangfok** [comment]
I completed my first round of review. Looking good!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1011 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5tQytSWU7pLltq_wi:-KW5tQytSWU7pLltq_wj:b-uaoflb) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1011)):*
> ```cpp
> 
>       if (string(name_attr) == string(RigidBodyTree<double>::kWorldName)) {
>         // Since a world link was specified within the URDF, there must be
> ```

Missing "a" after "be".

---

*[drake/systems/plants/parser_urdf.cc, line 1016 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5ta-_LHTS2DwDMneM:-KW5ta-_LHTS2DwDMneN:b-bc7rbs) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1016)):*
> ```cpp
>         // joint. The weld_to_frame transform, if not a nullptr, is updated
>         // with the transform specified by this joint. If it is a nullptr,
>         // a shared_ptr is created initialized to this transform.
> ```

Missing "and" after "created".

---

*[drake/systems/plants/parser_urdf.cc, line 1016 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW6-kgZUQRkBoqPQC-E:-KW6-kgZUQRkBoqPQC-F:bd6r187) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1016)):*
> ```cpp
>         // joint. The weld_to_frame transform, if not a nullptr, is updated
>         // with the transform specified by this joint. If it is a nullptr,
>         // a shared_ptr is created initialized to this transform.
> ```

Please change `shared_ptr` to be `shared_ptr<RigidBodyFrame>`.

---

*[drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1.urdf, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5wgtp68eBBjps1Jhx:-KW5wgtp68eBBjps1Jhy:b6wuto9) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1.urdf#L66)):*
> ```XML
>   </joint>
> 
> </robot>
> ```

Missing newline.

---

*[drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1_r90.urdf, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5wnxr5mh9cJ2GCcks:-KW5wnxr5mh9cJ2GCckt:b91bo5m) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1_r90.urdf#L53)):*
> ```XML
>   </link>
> 
>     
> ```

Indentation is inconsistent with rest of file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KW5x1X_-0m5nF8Zznbn:b-sxxpon)*

**Comment by naveenoid** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/plants/parser_urdf.cc, line 1011 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5tQytSWU7pLltq_wi:-KW8TOfBZA4IRSeT21dY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1011)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing "a" after "be".
</details>
Done.

---

*[drake/systems/plants/parser_urdf.cc, line 1016 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5ta-_LHTS2DwDMneM:-KW8TW3kBuEWcZVobYu8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1016)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing "and" after "created".
</details>
Done.

---

*[drake/systems/plants/parser_urdf.cc, line 1016 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW6-kgZUQRkBoqPQC-E:-KW8TXCsgFUZEdqXH8nm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/parser_urdf.cc#L1016)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Please change `shared_ptr` to be `shared_ptr<RigidBodyFrame>`.
</details>
Done.

---

*[drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1.urdf, line 66 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5wgtp68eBBjps1Jhx:-KW8TrpO4nZUxiAK7VEm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1.urdf#L66)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Missing newline.
</details>
Done.

---

*[drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1_r90.urdf, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KW5wnxr5mh9cJ2GCcks:-KW8UILM74D4GY0hEqsm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9afcb1abb0900ad8a3c42b3c6ff8071664cdd479/drake/systems/plants/test/models/cylindrical_1dof_robot_offset_z1_r90.urdf#L53)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Indentation is inconsistent with rest of file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KW8a3IBeh9_-4VYr0Ou:bnfp4nl)*

**Comment by naveenoid** [comment]
+@sammy-tri for platform review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KW8wEmjx3Hkt76fX-G4:b-1zm1j3)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KW9wMbWqqfNVEZf9Tvq:bnfp4nl)*

**Comment by liangfok** [comment]
This PR has conflicts with master. Need to resolve them before this can be merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWArMWAc2Egk6IFoxGq:by93a77)*

**Comment by naveenoid** [comment]
rebased..PTAL.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWCxe-0RY7GN-XLnmma:bv7njlw)*

**Comment by liangfok** [comment]
Just one comment.

---

Reviewed 6 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/multibody/rigid_body_system1/test/load_model_test.cc, line 354 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KWD6uO_1G5-jrHreBDV:-KWD6uO_1G5-jrHreBDW:b9ctfx0) ([raw file](https://github.com/robotlocomotion/drake/blob/a170ecd5dde5d93ade8051c0583d00cb21683a47/drake/multibody/rigid_body_system1/test/load_model_test.cc#L354)):*
> ```cpp
>   rbs.AddModelInstanceFromFile(drake::GetDrakePath() +
>                                    "/multibody/rigid_body_system1/test/models/" +
>                                        "cylindrical_1dof_robot_offset_z1_r90.urdf",
> ```

This line appears to exceed 80 characters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWD75rzcJowzAkowrG_:b-cc91uw)*

**Comment by liangfok** [comment]
Looks like there's now a problem with the file name / path:

```
[ RUN      ] LoadSDFTest.TestDualOffsetUrdf2
unknown file: Failure
C++ exception with description "failed to parse xml in file /home/ubuntu/workspace/linux-gcc-ninja-experimental-open-source-debug/drake/multibody/rigid_body_system1/test/models/cylindrical1dof_robot_offset_z1_r90.urdf
XML_ERROR_FILE_NOT_FOUND" thrown in the test body.
[  FAILED  ] LoadSDFTest.TestDualOffsetUrdf2 (4 ms)
```

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWE9V3tGlQYdzkuo3m8:b-8o64uh)*

**Comment by naveenoid** [comment]
Fixed..PTAL.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/multibody/rigid_body_system1/test/load_model_test.cc, line 354 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-KWD6uO_1G5-jrHreBDV:-KWDNxbNDZEMISPs2Mfu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a170ecd5dde5d93ade8051c0583d00cb21683a47/drake/multibody/rigid_body_system1/test/load_model_test.cc#L354)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This line appears to exceed 80 characters.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWDNyfy9I3JCUSuKqjK:b-h7whc)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWETxcmOwtSa4ZiwjXr:bnfp4nl)*

**Comment by liangfok** [comment]
Looks like this PR is ready to be merged. I'll let @naveenoid get the satisfaction :smile: .

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4087#-:-KWF2IIxsRIq6c21gVNK:b-5gokcy)*

**Pull request merged**
