### PR TITLE
[geometry] Deprecate RenderEngineVtk's default_label option

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See #19906 for discussion.

To avoid some merge conflict awkwardness, I plan to wait for that PR to merge first before we start reviewing this one.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review, please.

> Reviewed 9 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911#-:-NasBJ1-AAFWNyZ322nu:b-pq7hn8)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.  I anticipate that @SeanCurtis-TRI will want to merge this overnight, after he finishes his review.

**Review by sherm1 — COMMENTED** [review]
There is one CI failure - flake?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911#-:-NasH7pw8o81JqlKlXTa:bbwwcou)* status: LGTM missing from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Out of order platform :lgtm: pending feature review.

> Reviewed 8 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911#-:-NasI6rx-R_hhIAilNEf:b5eagmw)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`geometry/render_vtk/test/internal_render_engine_vtk_test.cc` line 1273 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19911#-NasHkT5EDbSgwxRRRfE:-NasHkT5EDbSgwxRRRfF:b-73o4ne) ([raw file](https://github.com/RobotLocomotion/drake/blob/d9da383dc8328a2f7d48911f1eb049cf1be7b155/geometry/render_vtk/test/internal_render_engine_vtk_test.cc#L1273)):*
> ```cpp
>     ResetExpectations();
>     RenderEngineVtk renderer;
>     InitializeRenderer(X_WC_, true /* no terrain */, &renderer);
> ```

nit: comment should read "add terrain"

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 7 of 9 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19911#-:-NasX-7d9_sVjciPMNL4:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),sherm1(platform)

**Pull request merged**
