### PR TITLE
doc: Add in mention of Drake apt repository.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8015)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@sherm1 for platform review, please.

\cc @jwnimmer-tri @sammy-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015#-:-L4sHD28taPkDOZi4B3E:b4qqhcf)*

**Comment by jwnimmer-tri** [comment]
-@sherm1 +@jwnimmer-tri :lgtm: for platform since I'd already read over this.

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/ubuntu_xenial.rst, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8015#-L4sKXT23xgJZHwHYJ3q:-L4sKXT23xgJZHwHYJ3r:bl66tof) ([raw file](https://github.com/robotlocomotion/drake/blob/2ecd098e85ef295e74dd4b6beae3b495424d37a6/doc/ubuntu_xenial.rst#L13)):*
> ```reStructuredText
> You may need to respond to interactive prompts to confirm that you agree to add
> the Drake `apt` repository (``https://drake-apt.csail.mit.edu/``) to your
> system, for packages such as ``dreal``, ``lcm``, and others.
> ```

BTW We don't actually install `lcm` in the script. We do install `kcov-34`, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015#-:-L4sKf-Z9nh4hePjgRmR:bnfp4nl)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/ubuntu_xenial.rst, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8015#-L4sKXT23xgJZHwHYJ3q:-L4sLfdnA7TfA1rn9DNc:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2ecd098e85ef295e74dd4b6beae3b495424d37a6/doc/ubuntu_xenial.rst#L13)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW We don't actually install `lcm` in the script. We do install `kcov-34`, though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8015)*

**Pull request merged**
