### PR TITLE
Additional QP Test problem

### PR DESCRIPTION
**Pull request by naveenoid**
Cleaned up PR to fix the problem that triggered https://github.com/RobotLocomotion/drake/commit/f226039ce9d684317773ddc6d35dc26391248dea

The PR introduces an additional test problem and some cosmetic (whitespace) changes on the source.

Feature review : @sammy-tri 
Platform review : @david-german-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2561)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Could you point out which part of this is the fix?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561#-:-KKG5xAHxDMhRWP-nWVi:1670006355)*

**Comment by naveenoid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/testOptimizationProblem.cpp, line 251 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2561#-KKG8k-Q_eLMRbtnRamc:-KKG8k-Rw46g-FvUd6nF:-1465275574) ([raw file](https://github.com/robotlocomotion/drake/blob/7efc05d60775589922286c7a481b8b31d46cb2d8/drake/solvers/test/testOptimizationProblem.cpp#L251)):*
> ```cpp
>   VectorXd expected(6);
>   expected << 0, 1, 0, 1, 1, 20;
>   prog.SetInitialGuess({x}, expected + .2 * VectorXd::Random(6));
> ```

@david-german-tri The fix is in the argument for VectorXd::Random 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561#-:-KKGEHGU3lQBbCHFe1CT:1417088721)*

**Comment by david-german-tri** [comment]
@jamiesnape added linux-debug on Jenkins and this is passing, so that's good :-)  Can merge as soon as the matlab build finishes.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561#-:-KKGEK1hXJyVrBYBhqFV:1553792795)*

**Comment by naveenoid** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561)*

**Comment by naveenoid** [comment]
@sammy-tri would you like to take one last look before I merge? I guess its mostly ok.

**Comment by sammy-tri** [comment]
The whitespace changes bother me, and I think it's going to be an ongoing problem unless we can figure out how to keep different editors from stomping on each other.  Were these added manually?  Or did your editor do this automatically to the file? 

Anyway, I'm not going to hold up this PR over it.

:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561#-:-KKJvHMLU5awZPkdIAyU:-2057145782)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2561)*

**Pull request merged**
