### PR TITLE
(frozen) prototype [geometry] Compliant-compliant hydroelastic contact model.

### LINKED ISSUE #16040: Implement compliant-compliant hydroelastic contact
<h1>Target February 2022 Release</h1>
This is the implementation plan to change prototype #15545 into quality code in master.  It will be updated as we go. Each item should become a small PR. This is a team work with contributions from several members including @joemasterjohn and @rpoyner-tri.

#### ComputeContactSurfaceFromCompliantVolumes()
  - [X] Equilibrium plane between two linear functions from two tetrahedra. (@DamrongGuoy @rpoyner-tri )
    - #16052 
  - [x] Refactor mesh-plane intersection code for plane-tetrahedron intersection. (@joemasterjohn )
    - [x] #16458
  - [x] #16365 (@DamrongGuoy @joemasterjohn )
    - [x] #16374  
    - [X] Intersection of two linear-field tetrahdra with their equilibrium plane into a polygon.
    - [x] Heuristic to filter out special cases
         - Only allow contact polygons whose normal vectors are along pressure gradients. 
    - [x] All contact polygons between two tetrahedral meshes with pressure fields
    - [x] Contact surface between two compliant hydroelastic tetrahedral meshes

#### Use the new capability in SceneGraph
  - [x] Update hydroelastic_callback and proximity_engine_test (@DamrongGuoy @rpoyner-tri )
    - [x] #16366
        - Ready to merge, pending on `#16365`. 
        - [x] Check whether it breaks Anzu (Anzu-master-Drake-PR 147)
    - [x] Update doxygen of QueryObject::ComputeContactSurfaces() 
      - [x] #16471

#### Use the new capability in MultibodyPlant
  - [x] Update MultibodyPlant::CalcDiscreteContactPairs() (@DamrongGuoy @amcastro-tri @xuchenhan-tri )
    - [x]  #16367
      - [x] Confirm that it plays well with Anzu (Anzu-master-Drake-PR 149) :heavy_check_mark: 
  - [x] Confirm with @amcastro-tri that it works well with HydroelasticTractionCalculator and other parts.
    - @amcastro-tri gave the new formula for the effective hydroelastic pressure gradient between two objects. 

<h1> Half space </h1>
Move the request for compliant-halfspace contacting another compliant object to #16487.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Close this prototype now. The production code is in master via #16040.

<h1>Original Description</h1>
Support #16040.

Prototype for computing contact surfaces for compliant-compliant hydroelastic contact.

This is a working prototype with no intention to merge into master.

image (1)

image

<h1> On Hold (January 12, 2022)</h1>
This prototype is now replaced by a number of smaller PRs (see the plan in #16040). There is no more development in this branch.  I'll close this PR when we resolve #16040.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MgJFf692iW4XDnP-T_d:bdcggqo)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
This is compliant box-box.


> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-Mgs51hED3njdLwIHXX5:b-ce8knv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
I cc: @rpoyner-tri here.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-Mgxb8oR1g2xAKXd88WW:bqcy8j5)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
For r5, we made the main API `ComputeContactSurfaceFromCompliantVolumes()` available and added more visual testing of that function like this (a compliant box makes contacts with a compliant ball, another box, and a cylinder):



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MhGyLGWAcf-XKaE0fIm:b-dwabfb)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by amcastro-tri — COMMENTED** [review]
I love these figures @damrongguoy. Figure X very nicely summarizes the algorithm. Great job!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MhOZdLe-7aPPukdgse-:bka2it7)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
The r7 can cull back faces now. See the tilted thin box in the picture below.


> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MhRPgTT0Lkw2uAsAwxT:b-b8wn3b)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
@amcastro-tri @sherm1  could you please help me check the new formula I used in `multibody_plant.cc` like this? (Please see the r9-r8 diff).
```C++
            const Vector3<T>& gradE_M_W =
                M_is_soft ? s.EvaluateGradE_M_W(face) : Vector3<T>::Zero();
            const Vector3<T>& gradE_N_W =
                N_is_soft ? s.EvaluateGradE_N_W(face) : Vector3<T>::Zero();
           ...
              const T k = wq[qp] * Ae * (gradE_M_W - gradE_N_W).dot(nhat_W);

```
That's my guess how to make it support both Rigid-Compliant and Compliant-Compliant a the same time.

However, I got a problem in one of my test (food_scoop) like this:
```
C++ exception with description "MultibodyPlant's discrete update solver failed to converge at simulation time =    3.53 with discrete update period =   0.007. This usually means that the plant's discrete update period is too large to resolve the system's dynamics for the given simulation conditions. This is often the case during abrupt collisions or during complex and fast changing contact configurations. Another common cause is the use of high gains in the simulation of closed loop systems. These might cause numerical instabilities given our discrete solver uses an explicit treatment of actuation inputs. Possible solutions include:
  1. reduce the discrete update period set at construction,
  2. decrease the high gains in your controller whenever possible,
  3. switch to a continuous model (discrete update period is zero),      though this might affect the simulation run time.
```

It made me thinking that we should make Compliant-Compliant an opt-in option, just like the low-res discrete "polygonal" contact patch option.  By default, compliant-compliant is still handled by point contact. Only when a special flag is set, then we enable hydroelastic compliant-compliant for experimenting.

 @rpoyner-tri .  This is the issue I reported in our 1-1 today.

Unfortunately the example that I used is in Anzu. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-Mhudjtx5B2k95Mr9LEw:bw24w2d)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
I'm not sure why Reviewable is not showing the following comment that I made previously.  I repeat it here (I apologize if this is redundant to you):

--------------------------------------------------------------
It made me thinking that we should make Compliant-Compliant an opt-in option, just like the low-res discrete "polygonal" contact patch option. By default, compliant-compliant is still handled by point contact. Only when a special flag is set, then we enable hydroelastic compliant-compliant for experimenting.

@rpoyner-tri . This is the issue I reported in our 1-1 today.

Unfortunately the example that I used is in Anzu.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MhvKHj23_bBs2EYmgmI:b-m4y4si)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
Good news. @amcastro-tri gave me the correct formula for the effective pressure gradient and the stiffness for the discrete compliant-compliant hydroelastic contact.  The Anzu example ran fine now (no explosion, no punch-through problem).

The correct formula is in r10.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-Mi9G2FbC9rwqeUmFja0:b-dijznh)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
The unit test `TEST_F(FieldIntersectionVizTest, BoxCloneBox)` (field_intersection_test.cc) showed this problem.  We got the contact patch that is not symmetrical when we stack two identical boxes perfectly on top of the other.  The code is suffering from numerical issues, I think.



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MiObvvlAKGUiyGDeBHl:b93o1c5)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
These pictures show a moving compliant ball kissing a stationary compliant box at its corner.









> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MjfpV0C98Q3CTLGkFCt:b-j3q77r)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by DamrongGuoy — COMMENTED** [review]
I shrink this PR by 300 lines by moving human-verification test into #16358.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15545#-:-MtASAoQALUUfTRCY3je:bmy5kgi)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Pull request closed without merging**
