### PR TITLE
[build] Modernize bazel sanitizer configs

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #17268.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)

### CODE REVIEW

**Comment by svenevs** [comment]
Scoped this while checking on CI statuses.  This one should also be checking the mac sanitizers we have (these will take some time to complete given current queue):

@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-everything-address-sanitizer please.

**Review by xuchenhan-tri — COMMENTED** [review]
Thanks for spotting the miss!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405#-:-N4dDpW58mRflfmkTe31:bi2pq0f)* status: 1 unresolved discussion, LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405#-:-N4giti241mritpJe0Wv:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @BetsyMcPhail)

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for platform review per rotation please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405#-:-N4hUIu6-QtQtdzpxgoW:b-i35568)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @BetsyMcPhail and @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @BetsyMcPhail and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4hx1qV1e13LVEY5vJ6:bntnpz0) (no related file):*
BTW Were you able to check the flags with `build -s -j 1` per Jeremy's suggestion, to see what was already included?

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4i-jH82Mqp7Wy-aFMZ:bmn4rs6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Were you able to check the flags with `build -s -j 1` per Jeremy's suggestion, to see what was already included?
</blockquote></details>

Now blocking: Doing a quick check, I don't see any difference in compliation flags:
https://github.com/EricCousineau-TRI/repro/blob/8e24d3a/bazel/bazel_asan_features/repro.diff

This is for Bazel 5.1.0.
Is that expected?

___

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4i1_9t8UZ_0-7yJ7y8:bge47jk) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Now blocking: Doing a quick check, I don't see any difference in compliation flags:
https://github.com/EricCousineau-TRI/repro/blob/8e24d3a/bazel/bazel_asan_features/repro.diff

This is for Bazel 5.1.0.
Is that expected?
</blockquote></details>

To fully close the issue, yes we will need to dig more closely into the verbose command traces.  However, this PR does not claim "Closes", it only claims "Towards" -- it opts-in to the preferred bazel spelling and removes a few of redundant flags.  As long as it doesn't break CI, it is therefore a monotonic improvement and there do not appear to be any defects here?

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4i59AB7CWi30i3wCNx:b-3icm8) (no related file):*
> I thought the intent of this PR was to remove flags that are redundant ...

Nope, that is the intent of the _issue_.  This PR is something different.

Saying `--features=asan` turns on some important bazel magic related to default preprocessor flags and linking options (as part of the bazel cc toolchain).  Switching it on make things that currently fail start succeeding.  The purpose of this PR is to turn on that Bazel setting, so that CI will pass in some future PRs that are currently blocked on this (#17394).

It's probable that a few of our remaining rcfile flags (e.g., `-fno-omit-frame-pointer`) are redundant with `--features=asan`.  The issue remains open in order to tidy up our rcfiles.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: to proceed forward, per comment below

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405#-:-N4i7yAMABH9CQ0EmKxJ:b4aboqk)* status: 1 unresolved discussion (waiting on @BetsyMcPhail and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4i740A0jYIWHyh6Lrh:b-etjy5n) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I thought the intent of this PR was to remove flags that are redundant ...

Nope, that is the intent of the _issue_.  This PR is something different.

Saying `--features=asan` turns on some important bazel magic related to default preprocessor flags and linking options (as part of the bazel cc toolchain).  Switching it on make things that currently fail start succeeding.  The purpose of this PR is to turn on that Bazel setting, so that CI will pass in some future PRs that are currently blocked on this (#17394).

It's probable that a few of our remaining rcfile flags (e.g., `-fno-omit-frame-pointer`) are redundant with `--features=asan`.  The issue remains open in order to tidy up our rcfiles.
</blockquote></details>

I'm afraid I still don't understand how dropping flags is a monotonic improvement, as `--features=asan` seems to do nothing observable to cc toolchain flags.

It might've been clearer if this PR simply dropped flags, then added `--features=asan` later, with testing to ensure that dropping flags doesn't admit new errors.

But for the purpose of forward motion, will simply approve and leave it up to y'all.
Please also feel free to assign another platform reviewer if you're concerned.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)* status: 1 unresolved discussion (waiting on @BetsyMcPhail and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4iA6Ch4-sBAtSsqXew:b-kcibwo) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm afraid I still don't understand how dropping flags is a monotonic improvement, as `--features=asan` seems to do nothing observable to cc toolchain flags.

It might've been clearer if this PR simply dropped flags, then added `--features=asan` later, with testing to ensure that dropping flags doesn't admit new errors.

But for the purpose of forward motion, will simply approve and leave it up to y'all.
Please also feel free to assign another platform reviewer if you're concerned.
</blockquote></details>

It _does_ change the flags, but not every command line is affected.  You probably just didn't notice in your repro.  Note that the compiler command line often refers to _filenames_ that themselves contain flags.  You need to scrape the named params files in order to see changes.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),BetsyMcPhail (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4iCeAU0a7wpn5jtVTK:b-p3m2zw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It _does_ change the flags, but not every command line is affected.  You probably just didn't notice in your repro.  Note that the compiler command line often refers to _filenames_ that themselves contain flags.  You need to scrape the named params files in order to see changes.
</blockquote></details>

Gotcha. An incorrect repro would make sense in that case.

That being said, I still don't see any changes when using clang (oops!) and cat'ing the param file:
https://github.com/EricCousineau-TRI/repro/commit/c9e30e9
However, perhaps there are still other things I'm missing.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17405)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),BetsyMcPhail (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4iGdMS9_yjV1Sp4vtk:b-701ei6) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. An incorrect repro would make sense in that case.

That being said, I still don't see any changes when using clang (oops!) and cat'ing the param file:
https://github.com/EricCousineau-TRI/repro/commit/c9e30e9
However, perhaps there are still other things I'm missing.
</blockquote></details>

I think your repro is probably too narrow.  You'd need to scrape the entire Drake build to see the effect.  The preprocessor definitions that change are (as best I recall) only on macOS.  The linker flags that change are on x86_64 but only for certain kinds of source code / compiler pragmas.  (The difficulty of comprehensively examining the flags is why we're deferring the rcfile cleanup to a follow-up.)

___

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17405#-N4hx1qUA_5ZTyC94c-T:-N4i59500yWKuD6leyUY:b-vg6wfx) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think your repro is probably too narrow.  You'd need to scrape the entire Drake build to see the effect.  The preprocessor definitions that change are (as best I recall) only on macOS.  The linker flags that change are on x86_64 but only for certain kinds of source code / compiler pragmas.  (The difficulty of comprehensively examining the flags is why we're deferring the rcfile cleanup to a follow-up.)
</blockquote></details>

Sorry for the late reply. I was in a meeting. 

Thanks @jwnimmer-tri for filling in the gap. I have nothing to add to the technical discussion.
@ericcousineau-tri To provide a little more context for the motivation of this PR, see https://drakedevelopers.slack.com/archives/C270MN28G/p1655214894045749. I tested in #17394 that this fixed the post-merge tsan CI.

**Pull request merged**
