### PR TITLE
Pass SWIG_EXECUTABLE path to IRIS

### PR DESCRIPTION
**Pull request by jamiesnape**
A temporary fix for OS X builds.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4921)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-experimental-matlab please

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

This would at least mean I could switch IRIS on for C++ only builds.

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4921)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4921#-:-KbRvV7DziggkAKHZI_t:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-clang-experimental-debug  please
@drake-jenkins-bot linux-gcc-experimental-open-source please
@drake-jenkins-bot linux-xenial-clang-experimental please

**Pull request merged**
