### PR TITLE
[tools] Refactor rcfiles for reuse

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19023.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19025)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.

\CC @BetsyMcPhail @ggould-tri @mwoehlke-kitware @sammy-tri @svenevs FYI

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19025#-:-NQzqWy83f-8gR3byEeX:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/ubuntu-focal.bazelrc` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19025#-NQzqJbU6xJt8dJRbLvv:-NQzqJbU6xJt8dJRbLvw:bqt45gy) ([raw file](https://github.com/RobotLocomotion/drake/blob/82d8460973cd39defac2b6cee5d696a860237973/tools/ubuntu-focal.bazelrc#L7)):*
> ```
> build:_helgrind --extra_toolchains=//tools/py_toolchain:linux_dbg_toolchain
> 
> # TODO(jamiesnape): Builds with configuration "memcheck" should also use
> ```

nit I assume whatever this was about has been dealt with?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19025)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

___
*[`tools/ubuntu-focal.bazelrc` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19025#-NQzqJbU6xJt8dJRbLvv:-NQzqi1HBF8O93y2aBbu:b-x0u05c) ([raw file](https://github.com/RobotLocomotion/drake/blob/82d8460973cd39defac2b6cee5d696a860237973/tools/ubuntu-focal.bazelrc#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit I assume whatever this was about has been dealt with?
</blockquote></details>

Yes, by giving up:

https://github.com/RobotLocomotion/drake/blob/022a1efdd8b5c052b791412066b9bbd80d42bf55/tools/dynamic_analysis/bazel.rc#L229

**Pull request merged**
