### PR TITLE
[tools] Promote repack_deb packaging script out of development

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #17177 and https://github.com/RobotLocomotion/drake-ci/pull/157.

I confirmed that the moved script runs locally but will add a test CI job once this is open for good measure.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17366)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature +(release notes: none) +(priority: medium).

+@EricCousineau-TRI for platform review per schedule, please.  Note that this PR is moving files out of dev so please **review all files as-if they are new from scratch**, including the "Only renamed" group in the File Matrix.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17366#-:-N487LZK-x-CRv2N-w-g:b-d9hyk2)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Comment by svenevs** [comment]
Job running with both PRs: https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging/14/

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform, reviewing full files with small nits, thanks!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17366#-:-N49J4_5EalGYRqFEw_d:b-bhtqe3)* status: 1 unresolved discussion (waiting on @svenevs)

___
*[`tools/release_engineering/repack_deb.py` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17366#-N49I29jEV_uNVBilyKG:-N49I29jEV_uNVBilyKH:bkuk4vx) ([raw file](https://github.com/robotlocomotion/drake/blob/88625e5dbfc7eae7684146568562631abf2857c7/tools/release_engineering/repack_deb.py#L5)):*
> ```Python
> This script assumes that the Ubuntu distribution the .tar.gz archive was built
> for is the same as what is running the script.  For example, a
> drake-latest-focal.tar.gz must be re-packaged on a focal machine.
> ```

nit This assumption may be violated, and it is unclear at what point in pipeline failure may occur.
Rather than state expectation here, can this be given "teeth" to ensure there isn't an issue?

e.g. assert `codename` extracted below is part of archive basename?
___
*[`tools/release_engineering/repack_deb.py` line 157 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17366#-N49HqKp1fMWOif0Yoyf:-N49HqKp1fMWOif0Yoyg:bcuqfqm) ([raw file](https://github.com/robotlocomotion/drake/blob/88625e5dbfc7eae7684146568562631abf2857c7/tools/release_engineering/repack_deb.py#L157)):*
> ```Python
>         '--version', type=str, required=False, default=None,
>         help=(
>             'version number to package (e.g., "1.3.0"), if not specified the '
> ```

BTW Odd grammar to have "if not specified" separated by comma.

Consider using semi-colon or separate sentence.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17366)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform) (waiting on @svenevs)

___
*[`tools/release_engineering/repack_deb.py` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17366#-N49I29jEV_uNVBilyKG:-N49QPwG5G-GIKdXeMiS:b9emktr) ([raw file](https://github.com/robotlocomotion/drake/blob/88625e5dbfc7eae7684146568562631abf2857c7/tools/release_engineering/repack_deb.py#L5)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, added some "baby teeth".  It's not exactly a robust check, but this is a drake developer only tool and our package creation always has the codename in it.  E.g., somebody could theoretically just rename their archive, but presumably they would know that bypassing the assertion via renaming is not going to result in success :wink:
</blockquote></details>

OK Thanks! :baby:

**Pull request merged**
