### PR TITLE
Clion 3 puts its build directory in the source tree where it should be ignored by git

### PR DESCRIPTION
**Pull request by sherm1**
The default names are "cmake-build-debug" and "cmake-build-release" depending on configuration, in `drake-distro/drake/`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4350)

### CODE REVIEW

**Comment by sherm1** [comment]
@hongkai-dai for feature review which should be plenty!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KY1IuY7vWbCNOh9qsSw:b-mzg95m)*

**Comment by sherm1** [comment]
That is, +@hongkai-dai.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KY1JCVVx_U58Epa_vU6:brsv26b)*

**Comment by RussTedrake** [comment]
i had noticed that, too, but forced clion3 to use the normal build directory by modifying my project settings.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KY1Ls1AcWvtCR5mX7MX:bpf0c38)*

**Comment by hongkai-dai** [comment]
:lgtm: 
FWIW, when I run cpplint_wrapper.py, it still detects all the the code in cmake-build-debug directory

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KY1VSdSjqvMAj-vo7ZA:b-zi76yw)*

**Comment by hongkai-dai** [comment]
I end up moving the build directory outside of drake folder.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KY1W-gx3DBGJL_HdO45:b-eorycf)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-KYER7QXHC_4EsZRc7ya:-KYER7QXHC_4EsZRc7yb:bw9k6ch) ([raw file](https://github.com/robotlocomotion/drake/blob/15ee561ca55bb53e3e80fb1cf36c3a417f75fe3c/.gitignore#L49)):*
> ```
> pod-build
> build
> cmake-build*
> ```

Per the PR description, not `cmake-build-*` in `drake/.gitignore`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350)*

**Comment by sherm1** [comment]
Thanks, @hongkai-dai. I don't see an exclusion list in cpplint_wrapper.py so that would be a separate project. This fix at least makes git status tolerable with default clion3 behavior.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-KYER7QXHC_4EsZRc7ya:-KYEucengLWRnlRde74z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/15ee561ca55bb53e3e80fb1cf36c3a417f75fe3c/.gitignore#L49)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Per the PR description, not `cmake-build-*` in `drake/.gitignore`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4350#-:-KYEujI3cfvZ3PRgQpBR:b6ocxq)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
