### PR TITLE
Fix wheel build of libtiff

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Use correct names of CMake variables to tell the wheel build of libtiff where to find libjpeg and liblzma. It seems the build works anyway, probably due to `CMAKE_PREFIX_PATH`. (Besides being more correct, the old names also produced warnings about unused CMake variables being passed into the build.)

Toward #18233.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18630)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@svenevs for feature review, please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Review by svenevs — COMMENTED** [review]
:lgtm: +@xuchenhan-tri for platform review, per schedule please!

Easiest to demonstrate success to platform via some log scraping, in the prior build there were warnings about `JPEG_INCLUDE` and `LIBLZMA_INCLUDE` not being used.  The experimental build on this PR, the warnings are gone (what we're solving).  Do note in the output below, we will not be fixing the unused / manually specified `CMAKE_CXX_FLAGS` (at least in this ticket), it's because our wheel dependencies have a mixture of C or C++ so we just provide the `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` to each project.

The latest nightly that still has the warning:

```console
$ curl https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-snopt-mosek-release/298/consoleFull | grep -A 10 'Manually-specified variables were not used by the project:'
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891   Manually-specified variables were not used by the project:
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891 
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891     CMAKE_CXX_FLAGS
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891 
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891 
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/zlib-build
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.891 [33/133] Performing build step for 'zlib'
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.954 [1/41] Building C object CMakeFiles/zlibstatic.dir/compress.o
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 1.977 [2/41] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 2.005 [3/41] Building C object CMakeFiles/zlibstatic.dir/zutil.o
<span class="timestamp">[1:10:12 AM] </span><span style="display: none">[2023-01-25T06:10:12.372Z]</span> #12 2.029 [4/41] Building C object CMakeFiles/minigzip.dir/test/minigzip.o
--
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947   Manually-specified variables were not used by the project:
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947 
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947     CMAKE_CXX_FLAGS
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947 
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947 
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/libjpeg-turbo-build
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 2.947 [40/133] Performing build step for 'libjpeg-turbo'
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.402Z]</span> #12 3.079 [1/328] Building C object CMakeFiles/tjunittest-static.dir/tjutil.c.o
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.670Z]</span> #12 3.090 [2/328] Building C object CMakeFiles/jpegtran-static.dir/cdjpeg.c.o
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.670Z]</span> #12 3.092 [3/328] Building C object CMakeFiles/turbojpeg-static.dir/jcapistd.c.o
<span class="timestamp">[1:10:13 AM] </span><span style="display: none">[2023-01-25T06:10:13.670Z]</span> #12 3.104 [4/328] Building C object CMakeFiles/turbojpeg-static.dir/jcapimin.c.o
--
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93   Manually-specified variables were not used by the project:
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93     CMAKE_CXX_FLAGS
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/png-build
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 [53/133] Performing build step for 'bzip2'
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 If compilation produces errors, or a large number of warnings,
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 please read README.COMPILATION.PROBLEMS -- you might be able to
<span class="timestamp">[1:10:25 AM] </span><span style="display: none">[2023-01-25T06:10:25.520Z]</span> #12 14.93 adjust the flags in this Makefile to improve matters.
--
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66   Manually-specified variables were not used by the project:
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66 
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66     JPEG_INCLUDE
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66     LIBLZMA_INCLUDE
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66 
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66 
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/libtiff-build
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.66 [94/133] Performing build step for 'libtiff'
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.70 [1/125] Building C object port/CMakeFiles/port.dir/dummy.c.o
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.74 [2/125] Building C object libtiff/CMakeFiles/tiff.dir/tif_codec.c.o
<span class="timestamp">[1:10:39 AM] </span><span style="display: none">[2023-01-25T06:10:39.502Z]</span> #12 28.74 [3/125] Building C object libtiff/CMakeFiles/tiff.dir/tif_close.c.o
```

This pr's experimental build:

```console
$ curl https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release/116/consoleFull
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689   Manually-specified variables were not used by the project:
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689 
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689     CMAKE_CXX_FLAGS
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689 
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689 
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/zlib-build
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.689 [33/133] Performing build step for 'zlib'
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.769 [1/41] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.790 [2/41] Building C object CMakeFiles/zlibstatic.dir/compress.o
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.820 [3/41] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
<span class="timestamp">[2:01:19 PM] </span><span style="display: none">[2023-01-20T19:01:19.679Z]</span> #12 1.853 [4/41] Building C object CMakeFiles/zlibstatic.dir/adler32.o
--
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729   Manually-specified variables were not used by the project:
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729 
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729     CMAKE_CXX_FLAGS
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729 
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729 
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/libjpeg-turbo-build
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.729 [38/133] Performing build step for 'libjpeg-turbo'
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.836 [1/328] Building C object CMakeFiles/turbojpeg-static.dir/jcapistd.c.o
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.862 [2/328] Building C object CMakeFiles/jpegtran-static.dir/cdjpeg.c.o
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.878 [3/328] Building C object CMakeFiles/tjunittest-static.dir/tjutil.c.o
<span class="timestamp">[2:01:20 PM] </span><span style="display: none">[2023-01-20T19:01:20.793Z]</span> #12 2.884 [4/328] Building C object CMakeFiles/turbojpeg-static.dir/jcapimin.c.o
--
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91   Manually-specified variables were not used by the project:
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91     CMAKE_CXX_FLAGS
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 -- Build files have been written to: /opt/drake-wheel-build/dependencies/build/src/png-build
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 [53/133] Performing build step for 'bzip2'
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 If compilation produces errors, or a large number of warnings,
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 please read README.COMPILATION.PROBLEMS -- you might be able to
<span class="timestamp">[2:01:31 PM] </span><span style="display: none">[2023-01-20T19:01:31.769Z]</span> #12 13.91 adjust the flags in this Makefile to improve matters.
```

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18630#-:-NMeF9NE4ONr2iIJTRYJ:b-np9188)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @mwoehlke-kitware and @xuchenhan-tri)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18630#-NMeCjot5VL3kdZxYNvS):*
nit: second sentence I'd prefer to reword (on merge to avoid needing a repush if desired) to say "Removes libtiff configuration warnings about unused variables."  AFAICT it's because the LIBRARY vars were set correctly, and we _know_ the build currently works / finds the correct dependency.  And it _does_ get rid of the warnings (not _should_).

**Comment by mwoehlke-kitware** [comment]
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18630#-NMeCjot5VL3kdZxYNvS):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

nit: second sentence I'd prefer to reword (on merge to avoid needing a repush if desired) to say "Removes libtiff configuration warnings about unused variables."  AFAICT it's because the LIBRARY vars were set correctly, and we _know_ the build currently works / finds the correct dependency.  And it _does_ get rid of the warnings (not _should_).
</blockquote></details>

PR description has been updated.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18630#-:-NMeJlUZ2dv9mvG29jgw:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees svenevs,xuchenhan-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
