### PR TITLE
workspace: Upgrade spdlog to latest release 1.8.1

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14153)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  Wow, only released yesterday and already we support it! :-)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14153#-:-MI_uQDp16-TjzL2mDsi:boku1mx)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/workspace/spdlog/repository.bzl, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14153#-MI_uTAN7ihprRL6nQ13:-MI_uTAN7ihprRL6nQ14:b8chpub) ([raw file](https://github.com/robotlocomotion/drake/blob/622d2a1cc5383ddd9b73646ab0af5f37dbbc6a0a/tools/workspace/spdlog/repository.bzl#L10)):*
> ```
> abime/spdlog"
> ```

**Comment by jwnimmer-tri** [comment]
A stopped clock is right twice a day... ;)

**Pull request merged**
