### PR TITLE
Deprecate Mesh and Convex::filename() method (in favor of source())

### LINKED ISSUE #15263: [geometry] Mesh and Convex shape specification uses in-memory mesh
# Problem

Currently, when specifying a shape for `SceneGraph` via [`Mesh`](https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L258) or [`Convex`](https://github.com/RobotLocomotion/drake/blob/master/geometry/shape_specification.h#L280), the mesh data is solely specified by a path to a resource on disk.

For applications such as cutting or doing on-line decomposition of an object or space, that generate meshes, it is unreasonable to demand that the mesh representation in memory be forced to go to disk in order to end up in `SceneGraph`. It would be better to go directly into `SceneGraph`.

# Proposal

Modify `Mesh` and `Convex` such that they can take mesh data and take ownership of that directly.

(Edit: 10/15/21 We create a "universal" mesh type in Drake. It would carry all of the mesh information we typically care about: vertex positions, normals, texture coordinates, materials (including textures), etc. It would also support queries about the fundamental nature of the mesh: is it convex? Is it closed? Etc. Finally, we create instances of the universal mesh from the various forms of files we parse as well as allow programmatic instantiation.)

# Challenges

1. We need to broadcast meshes to visualizers when there are no files on disk. Instead, we have to broadcast the mesh data directly.
    - (Edit: 10/15/21 This is not so problematic. It has been done to a limited degree in #15773 and #15772 and will soon be added to the C++`MeshcatVisualizer`. These only include vertices and normals, but texture coordinates could definitely be added. Textures would be the only unknown quantity.)
2. We need an in-memory representation that contains *at least* as much information as we'd get out of our currently supported file formats (e.g., obj). This includes vertex positions, normals, texture coordinates, groups, material information, etc.
3. Whatever the representation that is owned by `Mesh` and `Convex`, we'll need to translate from *it* to the various engines we currently support (`RenderEngineVtk`, `RenderEngineGl`, `ProximityEngine` -- aka FCL).

# PR strategy

PR #21881 contains the full set of commits for resolving this issue (encoded in its revisions); it's transformed into the final PR in the strategy. The PR sequence has the following strategy:

- [X] #21875
  - [x] #21890
     - [x] #21914
     - [x] #21923.
         - [x] #21944
     - [x] #21922
       - [x] #21945
       - [x] #21949
         - [x] #21959
         - [x] #21952
         - [x] #21953
         - [x] #21954
       - [x] #21950
- [ ] #21881

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This represents the scope and coarse sequence of PRs to fully implement in-memory meshes in Drake.

Closes #15263

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Revisions 1-13 represent the 13 PRs in this train. See the issue (#15263) for the overall strategy.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O63ZDyeDuudFng9RyOy:bvy15hc)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.h` line 78 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O6bN-CpAuNqNjUrUNvz:-O6bN-CpAuNqNjUrUNw-:b-vqjnqc) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab72e475a1e75bac94cd9c131e7ce5f2c549554/geometry/shape_specification.h#L78)):*
> ```objc
> 
>   // TODO(SeanCurtis-TRI): Deprecate this in favor of a camel-case spelling; the
>   // cost of Mesh::to_string() and Convex::to_string() belie the snake_case.
> ```

BTW The canonical spelling is `to_string()`.  It is not-unexpected that formatting the string during some `to_string()` call will need a lot of fmt substitions and effort behind it.  We should still stick to to `to_string` for simplicity and consistency.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

___
*[`geometry/shape_specification.h` line 78 at r15](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O6bN-CpAuNqNjUrUNvz:-O6bZ5m62BKiCFYEJQtZ:b-hkxorv) ([raw file](https://github.com/RobotLocomotion/drake/blob/eab72e475a1e75bac94cd9c131e7ce5f2c549554/geometry/shape_specification.h#L78)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW The canonical spelling is `to_string()`.  It is not-unexpected that formatting the string during some `to_string()` call will need a lot of fmt substitions and effort behind it.  We should still stick to to `to_string` for simplicity and consistency.
</blockquote></details>

That resolution makes me perfectly happy. Removing the TODO is the perfect resolution.

**Comment by jwnimmer-tri** [comment]
My suggestion for the deprecation PR would be to withdraw the `DRAKE_DEPRECATED` automatic-warning flagging (and ditto in pydrake), and instead change the API documentation of `filename()` to say something along the lines of "Deprecated, will turn into a warning on 2025-01-01".  We would still announce the "newly deprecated" in this current release's notes.  We would still port all of the drake-local call sites (except 1 unit test) to the new spelling.  Then after the new year we will add back the DRAKE_DEPRECATION markers, with setting the code removal timeout for 2025-04-01.

Because the `filename()` is a relative critical function, rolling out the change more gradually (and with a longer runway) will provide a smoother transition-path for our users.  Also, since the deprecated function is sugar for calling another function plus an error-check, it's not really that costly for us to keep it around.  The feature isn't being removed, just respelled slightly.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'm not wholly against it, but I'm skeptical.

I'm dubious about how much non-Drake code uses the API in question. For example, nothing under CI in Anzu uses it (Anzu-master-Drake-PR/276). There are four obvious usages, two in Anzu's forked `RenderEngineVtk` and two in `RvizGeometryVisualizer`. While a gradual deprecation strategy would indeed provide a "longer runway", I don't think we are making affordances for 747s. I think there's a handful of Cessnas out there. Is that worth such an atypical deprecation strategy?

It seems that announcing it as deprecated in release notes will carry little weight in comparison with actual deprecation and no code that might need to adapt would adapt until we actually triggered those warnings. The time in between wouldn't afford gradual adoption, it would simply be a denial of reality and all of the required work would be deferred. We can certainly increase the deprecation window if we want to give them more time. But I fail to see how pseudo-deprecation serves anyone.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8qsakf20yGJ8zNS6ih:b-qs1s69)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
Whatever, fine.  I'll write up a deprecation playbook later to provide more specific guidance, with sufficient background to explain.  We can keep this as-is.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I've extended the deprecation deadline by a couple of months.

-(status: do not review) 
+(type: feature request) +(release notes: newly deprecated) 

+@jwnimmer-tri for feature review, please.

(BTW If you feel strongly about the soft deprecation period, I'll go ahead and remove the warning triggers.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8rj9nlCL7XYGedQcaO:bt0wai5)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 12 files at r13, 5 of 53 files at r15, 83 of 97 files at r16, 13 of 13 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8s2ThG3VzC4pQm2n7g:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`geometry/shape_specification.h` line 308 at r18](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O8s1wa85fKbNJ8adc7K:-O8s1wa85fKbNJ8adc7L:bwlox7l) ([raw file](https://github.com/RobotLocomotion/drake/blob/9c20e5976a6953af401aae33db3e64aa2dddb720/geometry/shape_specification.h#L308)):*
> ```objc
>   std::string filename() const;
> 
>   /** Returns the extension of the convex type -- all lower case and including
> ```

nit The word "type" here doesn't quite sit right with me.  Are we talking about "convex type" as in "this convex shape" or as in "the file type".  Maybe there is a less ambiguous phrasing we could use.
___
*[`geometry/test/geometry_state_test.cc` line 409 at r18](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O8s1Ph48YXbdztheFg5:-O8s1Ph48YXbdztheFg6:b-r9uy63) ([raw file](https://github.com/RobotLocomotion/drake/blob/9c20e5976a6953af401aae33db3e64aa2dddb720/geometry/test/geometry_state_test.cc#L409)):*
> ```cpp
>   if (test.source().description() != expected_.source().description()) {
>     error() << "\nExpected mesh filename " << expected_.source().description()
>             << ", received mesh filename " << test.source().description();
> ```

nit "filename" here is a little bit stale.  Seems like "source" (or maybe "description") would be more clear?

Ditto below.
___
*[`geometry/test/proximity_engine_test.cc` line 332 at r18](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O8s14EeEBZ_8xwRMIjh:-O8s14EeEBZ_8xwRMIji:b-neue6z) ([raw file](https://github.com/RobotLocomotion/drake/blob/9c20e5976a6953af401aae33db3e64aa2dddb720/geometry/test/proximity_engine_test.cc#L332)):*
> ```cpp
> 
>   const Mesh mesh{FindResourceOrThrow("drake/geometry/test/octahedron.obj")};
>   const Convex convex(mesh.source().description());
> ```

nit The `.description()` here smells weird.  We want to copy the source, so just `context(mesh.source())` I would think?

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sammy-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8sD5vW3B2_kUZeh-Wn:bz1t39v)* status: LGTM missing from assignee sammy-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`geometry/shape_specification.h` line 541 at r19](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-O8sDuLV-5dJ4LK-QQim:-O8sDuLV-5dJ4LK-QQin:b-uoaeeb) ([raw file](https://github.com/RobotLocomotion/drake/blob/442fc2048578d2f326c45ec794ba88bc60f86e37/geometry/shape_specification.h#L541)):*
> ```objc
>   std::string filename() const;
> 
>   /** Returns the extension of the mesh type -- all lower case and including
> ```

nit "of the underlying input mesh" likewise

**Review by SeanCurtis-TRI — COMMENTED** [review]
-@sammy-tri +@rpoyner-tri for out-of-sequence platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8viBnU6tnLqynAUDxY:b-3cdyjn)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 12 files at r13, 5 of 53 files at r15, 83 of 97 files at r16, 13 of 13 files at r17, 1 of 2 files at r18, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21881#-:-O8xKr2NBP1fKyUvhPby:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
