### PR TITLE
add pybind for MinimumValueConstraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-Na7xS5KDn78wUEAy97C:-Na7xS5KDn78wUEAy97D:buba5ds) ([raw file](https://github.com/RobotLocomotion/drake/blob/87960a59b8ffd9b76fa46390af6ff72497c2f726/bindings/pydrake/solvers/test/evaluators_test.py#L205)):*
> ```Python
>         self.assertFalse(dut.CheckSatisfied(np.array([-5.])))
>         # Evaluate with autodiff.
>         y = dut.Eval(InitializeAutoDiff(np.array([1.])))
> ```

@EricCousineau-TRI may I ask for your help here? When I try to evaluate this constraint using autodiff scalar, I got the error
```
y = dut.Eval(InitializeAutoDiff(np.array([1.])))
RuntimeError: dtype=object arrays must be copied, and cannot be referenced
```
but I don't quite understand where this error comes from.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-Na7xS5KDn78wUEAy97C:-Na8B2DDE8R_sMRi0lUY:b-z5zc4w) ([raw file](https://github.com/RobotLocomotion/drake/blob/87960a59b8ffd9b76fa46390af6ff72497c2f726/bindings/pydrake/solvers/test/evaluators_test.py#L205)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@EricCousineau-TRI may I ask for your help here? When I try to evaluate this constraint using autodiff scalar, I got the error
```
y = dut.Eval(InitializeAutoDiff(np.array([1.])))
RuntimeError: dtype=object arrays must be copied, and cannot be referenced
```
but I don't quite understand where this error comes from. 
</blockquote></details>

Long-story short, you cannot alias NumPy arrays <-> Eigen matrices when using `dtype=object` (`AutoDiff`, `Expression`, etc)
You need to use `return_value_policy_for_scalar_type`, `CopyIfNotPodType`, etc. if you want to bind specific signatures for all scalar types.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-Na7xS5KDn78wUEAy97C:-Na8mEpLEQce8EHiSYe6:b-dnhrtu) ([raw file](https://github.com/RobotLocomotion/drake/blob/87960a59b8ffd9b76fa46390af6ff72497c2f726/bindings/pydrake/solvers/test/evaluators_test.py#L205)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Long-story short, you cannot alias NumPy arrays <-> Eigen matrices when using `dtype=object` (`AutoDiff`, `Expression`, etc)
You need to use `return_value_policy_for_scalar_type`, `CopyIfNotPodType`, etc. if you want to bind specific signatures for all scalar types.
</blockquote></details>

Thanks Eric for the reply.

Sorry I am still not sure what should be done here. I think the problem occurs when I call the constraint `Eval` function, which works fine for np.array of float, but fails for np.array of autodiff scalar. Notice that I haven't add the binding for the `Eval` function in `MinimumValueConstraint`, it just uses the `Eval` binding of the parent `EvaluatorBase` class https://github.com/RobotLocomotion/drake/blob/c1474e6aa00cd649eba5a54ad7d3ee97f18e483c/bindings/pydrake/solvers/solvers_py_evaluators.cc#L151-L165.

I am not sure where should I add the return value poilcy in the python binding. In the entire `solvers_py_evaluators.cc` file where we bind the costs/constraints, we never specify the return value policy for the Eval class.

**Review by hongkai-dai — COMMENTED** [review]
+@EricCousineau-TRI for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-:-Na8s_VfB4WPBMigwT7d:b-g5jkj8)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/test/evaluators_test.py` line 205 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-Na7xS5KDn78wUEAy97C:-Na8sLU22ApIKFI90IPA:byn98ar) ([raw file](https://github.com/RobotLocomotion/drake/blob/87960a59b8ffd9b76fa46390af6ff72497c2f726/bindings/pydrake/solvers/test/evaluators_test.py#L205)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks Eric for the reply.

Sorry I am still not sure what should be done here. I think the problem occurs when I call the constraint `Eval` function, which works fine for np.array of float, but fails for np.array of autodiff scalar. Notice that I haven't add the binding for the `Eval` function in `MinimumValueConstraint`, it just uses the `Eval` binding of the parent `EvaluatorBase` class https://github.com/RobotLocomotion/drake/blob/c1474e6aa00cd649eba5a54ad7d3ee97f18e483c/bindings/pydrake/solvers/solvers_py_evaluators.cc#L151-L165.

I am not sure where should I add the return value poilcy in the python binding. In the entire `solvers_py_evaluators.cc` file where we bind the costs/constraints, we never specify the return value policy for the Eval class.
</blockquote></details>

I found that if I change the input argument in the `std::function` from `const Eigen::Ref<const AutoDiffVecXd>&` to `const AutoDiffVecXd&` then the runtime error is gone. Mark this as resolved.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, nice!
+@xuchenhan-tri for platform review, please!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-:-NaIutlq2-YLdCDKyemp:b4tqhxf)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/solvers_py_evaluators.cc` line 475 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-NaItiTh52SgMUQK2sxs:-NaItiTh52SgMUQK2sxt:b-oqstgo) ([raw file](https://github.com/RobotLocomotion/drake/blob/c66944ee08404ea5c3bfa6febb35da9d42e7a670/bindings/pydrake/solvers/solvers_py_evaluators.cc#L475)):*
> ```cpp
>       m, "MinimumValueConstraint", doc.MinimumValueConstraint.doc)
>       .def(py::init(
>                [](int num_vars, double minimum_value,
> ```

BTW Ah, I see. At some point, may be worth teaching a variant of `WrapCallbacks` to handle this case, e.g. `WrapCallbacksForNonPodScalars()`.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm: 
+(release notes: fix) 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19839#-:-NaJ6nuUC-E6djjavDfm:bk35uop)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),xuchenhan-tri(platform)

**Comment by rpoyner-tri** [comment]
-(release notes: fix) +(release notes: feature)

**Pull request merged**
