### PR TITLE
Polished implementation of TranslatorBetweenLcmtDrakeSignal.

### PR DESCRIPTION
**Pull request by liangfok**
Mostly comment changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3450)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review please.
+@david-german-tri for platform review please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-:-KSfXqmfOnFaA2gZZrah:b-1gbpvm)*

**Comment by liangfok** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/lcm/lcmt_drake_signal_translator.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-KSfYKIupP-B8oO7j0ok:-KSfYKIupP-B8oO7j0ol:bslohsy) ([raw file](https://github.com/robotlocomotion/drake/blob/1f28c0b69b8e92e8903c90749ad886e5f45c5c30/drake/systems/lcm/lcmt_drake_signal_translator.h#L26)):*
> ```objc
>   /**
>    * A constructor that sets the expected sizes of the LCM message and the
>    * BasicVector. Both the LCM message and BasicVector must be the same size.
> ```

"BasicVector" should be "VectorBase". (Both instances.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450)*

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-KSgdM-zVC1qedjD_kIl:-KSgdM-zVC1qedjD_kIm:bevxl7s) ([raw file](https://github.com/robotlocomotion/drake/blob/1f28c0b69b8e92e8903c90749ad886e5f45c5c30/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L11)):*
> ```cpp
> 
> #include "drake/systems/lcm/lcm_receive_thread.h"
> #include "drake/systems/lcm/lcm_subscriber_system.h"
> ```

Redundant with first line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/lcm/test/lcm_subscriber_system_test.cc, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-KSgdM-zVC1qedjD_kIl:-KSgepFdZHaiF0aOc-CG:b-o7vuhc) ([raw file](https://github.com/robotlocomotion/drake/blob/1f28c0b69b8e92e8903c90749ad886e5f45c5c30/drake/systems/lcm/test/lcm_subscriber_system_test.cc#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Redundant with first line.
</details>
Good catch! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450)*

**Comment by jwnimmer-tri** [comment]
:lgtm: Just _your own_ blocking comment remaining.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-:-KSgh8p4L4qcmExKbUr8:b5phycw)*

**Comment by liangfok** [comment]
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/lcm/lcmt_drake_signal_translator.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-KSfYKIupP-B8oO7j0ok:-KSgsbCrbSWw-04_YF2X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1f28c0b69b8e92e8903c90749ad886e5f45c5c30/drake/systems/lcm/lcmt_drake_signal_translator.h#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> "BasicVector" should be "VectorBase". (Both instances.)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3450#-:-KShp-PVPxS1QWUVrqIz:bnfp4nl)*

**Pull request merged**
