### PR TITLE
Updates Drake's ROS Kinetic build instructions to disable Director

### LINKED ISSUE #6575: Issue Building Drake with ROS
Ciao,

I am trying to build drake with ROS Kinetic on my laptop (with Ubuntu 16.04) following your guide, [Building Drake as a Catkin Package in ROS](http://drake.mit.edu/from_source_ros_kinetic.html) but i get this error:

drake_error

This error happens after the first tentative of building since there is no VTK5 installed on my laptop and i need to build it directly from source. Following your guide i to set -DUSE_SYSTEM_VTK=OFF -DWITH_VTK=ON, but actually both flags do not exist and are not settable.

Recompiling i get again the above error.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #6575.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6580)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jamiesnape for feature review please. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6580#-:-Kp2o90-doFE-Fzk_rh1:b-hgoxu6)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6580#-:-KpFfSYy1YGDKFzL5JLu:bnfp4nl)*

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review please. Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6580#-:-KpGj5QZ5oeBDKp4CKML:b-1bcdxl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: rubber-stamp.

Ideally ROS Kinetic on Xenial would be a supported configuration and thus these instructions would be tested in CI.  However, given the likelihood of significant rework to this doc before we support ROS Kinetic, I think ad-hoc fixes should be blessed without meaningful platform review, until such a time as we offer official support.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6580#-:-KpGkcFo03r0b01knVtV:b-gjydy8)*

**Pull request merged**
