### PR TITLE
Store indeterminates and decision variables in symbolic::Polynomial as members

### LINKED ISSUE #10229: Calling symbolic::Polynomial::decision_variables() is very slow
I just found when I call `Polynomial::AddProduct` https://github.com/RobotLocomotion/drake/blob/07cd8f081b52b06547c852edf001a133c951a899/common/symbolic_polynomial.cc#L642-L646, 99.46% of time is spent on `CheckInvariant`. And inside `CheckInvariant`, 90% of time is spent on calling `decision_variables()` in https://github.com/RobotLocomotion/drake/blob/07cd8f081b52b06547c852edf001a133c951a899/common/symbolic_polynomial.cc#L666-L667

Here is the callgrind output of my test.
[callgrind.out.28429.zip](https://github.com/RobotLocomotion/drake/files/2680953/callgrind.out.28429.zip)
together with a screenshot visualized in kCachegrind
screenshot from 2018-12-14 08-26-37

I would like to propose two improvements
1. We call `CheckInvariant` only in the debug mode.
2. `Polynomial` stores `decision_variables_` and `indeterminates_`. It also updates `decision_variables_` and `indeterminates_` inside any of its non-cost methods that changes to `indeterminates_` and `decision_variables_`.

@soonho-tri what do you think?

### PR DESCRIPTION
**Pull request by soonho-tri**
Fix #10229.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11790)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@hongkai-dai , could you check if this PR makes your examples faster?

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@hongkai-dai ping?

@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
*[`common/symbolic_polynomial.cc` line 383 at r2](https://reviewable.io/reviews/robotlocomotion/drake/11790#-Ne_a4OZD2njrXw6zxCr:-Ne_a4O_8OXjQXAoevgA:b-9lbrx3) ([raw file](https://github.com/robotlocomotion/drake/blob/6948aed77a3e831ae8282a52a19f9cbb1adf813f/common/symbolic_polynomial.cc#L383)):*
> ```cpp
>     : monomial_to_coefficient_map_{DecomposePolynomialVisitor{}.Decompose(
>           e, indeterminates)},
>       indeterminates_{std::move(indeterminates)},
> ```

This was a bug.  We need to intersect `indeterminates_` with the monomial map, in case the user passed in any `indeterminates` that did not appear in `e`.  I will open a PR with the fix.

**Pull request merged**
