### PR TITLE
Add names to systems in the quadrotor example.

### PR DESCRIPTION
**Pull request by david-german-tri**
@naveenoid for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5840)

### CODE REVIEW

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-ninja-experimental-minimal please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5840#-:-KhlU4ASuGWRmGEtxaTG:b-yug89b)*

**Comment by soonho-tri** [comment]
+@soonho-tri 
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5840#-:-KhlUA0O8AdQ8I6A6bY2:b-denpm8)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5840)*

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5840#-:-KhlgI_YrwAHjYDXEs5S:bnfp4nl)*

**Pull request merged**
