### PR TITLE
Add features to PackageMap

### PR DESCRIPTION
**Pull request by calderpg-tri**
Adds/modifies several features to `PackageMap`:

- Makes `PackageMap` copy/move/assignable
- Changes `PackageMap::Add` to allow duplicate (package, path) to be added without throwing
- Adds `PackageMap::AddMap` to combine package maps
- Adds `PackageMap::GetPackageNames` to enumerate the packages mapped by the map

+@jwnimmer-tri for feature review, thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @calderpg-tri)

___
*[multibody/parsing/package_map.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaA8v4h4Fv5VPK9oVnK:-MaA8v4i4C3KV1gqHa6O:b-dx6o9t) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/package_map.h#L41)):*
> ```objc
>   int size() const;
> 
>   /// Returns the package names in this PackageMap.
> ```

nit The documentation should specify what order (if any) is to be expected for the names (unspecified, order of addition, alphbetical, etc.).
___
*[multibody/parsing/package_map.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaA9yUVB5uhqvdZISQC:-MaA9yUVB5uhqvdZISQD:b-ezbx4n) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/package_map.cc#L253)):*
> ```cpp
>   const string package_name = GetPackageName(filename);
>   const string package_path = GetParentDirectory(filename);
>   AddPackageIfNew(package_name, package_path);
> ```

We lost something here.

Previously we called Add, which would throw if the path did not exist, or if the name was already present _at all_.

Now we call AddPackageIfNew, which will still throw if the path does not exist, but now allows for inconsistent duplicates to be skipped without any exception being throws.

I think we need to call `Add` here instead, and also ensure there is a unit test case that specifically covers this situation.
___
*[multibody/parsing/test/package_map_test.cc, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABQ9P9UsoBzH_rZC0:-MaABQ9Q7UEpgYCiaZuX:bq627cb) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L35)):*
> ```cpp
>     EXPECT_EQ(package_map.GetPath(package_name), package_path);
>   }
>   for (const auto& package_name : package_map.GetPackageNames()) {
> ```

If `GetPackageNames` always returns an empty vector, this test would still pass.  We also need to check that `GetPackageNames().size() == expected_packages.size()`.
___
*[multibody/parsing/test/package_map_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABgC9C_t8V4RsckH0:-MaABgC9C_t8V4RsckH1:b9fsfsh) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L82)):*
> ```cpp
>   package_map.Add("package_foo", "package_foo");
>   // Adding a duplicate package with a different path throws.
>   EXPECT_THROW(package_map.Add("package_foo", "garbage"), std::runtime_error);
> ```

Here we're claiming that "same name with different path" is being tested, but the test as written does not distinguish between "package_foo already maps to something else" vs "no such directory named garbage".
___
*[multibody/parsing/test/package_map_test.cc, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaACFnID6flhDSzooAP:-MaACFnID6flhDSzooAQ:bxkoj97) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L145)):*
> ```cpp
> 
>   // Combine package maps with a matching duplicate package + path.
>   package_map_1.AddMap(package_map_2);
> ```

This PR makes the PackageMap copyable, and we don't really have to test the _correctness_ of that since we let C++ do its thing, but we should check that the copy constructor at least _exists_.

Making a copy of map_1 before we mutate it might be a convenient way to do that.  It would also help the reader reason about the EXPECT_THROW at the end of this test, where we're trying to merge into map_1, but map_1's contents are no longer expected_1 but rather combined.
___
*[multibody/parsing/test/package_map_test.cc, line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaACsuR3Gbfh1m58z7h:-MaACsuR3Gbfh1m58z7i:b2nuied) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L151)):*
> ```cpp
>   // Combining package maps with a conflicting package + path throws.
>   EXPECT_THROW(
>       package_map_1.AddMap(package_map_conflicting), std::runtime_error);
> ```

There is a lot of code in PackageMap that throws (and we'll inevitably add more over time), and the AddMap methods delegates to at least two more helpers as it does it's job.  Therefore, this test is not specific enough to convince the reader that the path conflict in particular was the cause of the runtime_error.

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[multibody/parsing/package_map.h, line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaA8v4h4Fv5VPK9oVnK:-MaAjm6IA3ygyS4VTTk3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/package_map.h#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The documentation should specify what order (if any) is to be expected for the names (unspecified, order of addition, alphbetical, etc.).
</blockquote></details>

Done.
___
*[multibody/parsing/package_map.cc, line 253 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaA9yUVB5uhqvdZISQC:-MaAjp8zBL8hyf3jzNR5:bblr1bq) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/package_map.cc#L253)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We lost something here.

Previously we called Add, which would throw if the path did not exist, or if the name was already present _at all_.

Now we call AddPackageIfNew, which will still throw if the path does not exist, but now allows for inconsistent duplicates to be skipped without any exception being throws.

I think we need to call `Add` here instead, and also ensure there is a unit test case that specifically covers this situation.
</blockquote></details>

Switched back to use `Add`, and added a test using a conflicting `package.xml` (same package name, different path).
___
*[multibody/parsing/test/package_map_test.cc, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABQ9P9UsoBzH_rZC0:-MaAk2ep26SbfaYpPtJG:bxe23ff) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If `GetPackageNames` always returns an empty vector, this test would still pass.  We also need to check that `GetPackageNames().size() == expected_packages.size()`.
</blockquote></details>

Changed the test to ensure that all expected package names are present exactly once.
___
*[multibody/parsing/test/package_map_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABgC9C_t8V4RsckH0:-MaAkGjgECH8-sIuuDFG:bifqmoa) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here we're claiming that "same name with different path" is being tested, but the test as written does not distinguish between "package_foo already maps to something else" vs "no such directory named garbage".
</blockquote></details>

Added separate cases for conflicting path and for garbage paths.
___
*[multibody/parsing/test/package_map_test.cc, line 145 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaACFnID6flhDSzooAP:-MaAkNDC7TwS-MAbGx-s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L145)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This PR makes the PackageMap copyable, and we don't really have to test the _correctness_ of that since we let C++ do its thing, but we should check that the copy constructor at least _exists_.

Making a copy of map_1 before we mutate it might be a convenient way to do that.  It would also help the reader reason about the EXPECT_THROW at the end of this test, where we're trying to merge into map_1, but map_1's contents are no longer expected_1 but rather combined.
</blockquote></details>

Done.
___
*[multibody/parsing/test/package_map_test.cc, line 151 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaACsuR3Gbfh1m58z7h:-MaAkXpM7IZDc7umxyGg:b9idym3) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L151)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is a lot of code in PackageMap that throws (and we'll inevitably add more over time), and the AddMap methods delegates to at least two more helpers as it does it's job.  Therefore, this test is not specific enough to convince the reader that the path conflict in particular was the cause of the runtime_error.
</blockquote></details>

Added test for contents of exception message.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064#-:-MaAr8Zm575WsFsDVFZh:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[multibody/parsing/test/package_map_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABgC9C_t8V4RsckH0:-MaApW1k9F7piLKiQdQm:bcn320b) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L82)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Added separate cases for conflicting path and for garbage paths.
</blockquote></details>


Still nothing here shows easy proof to the reader that the predicates are checking what the comments claim they are checking.  One easy way to convince the reader would be to check that the error message string is consistent with the claim.  Checking the exact message string would be overkill and brittle, but confirming whether it said ".*conflicts with.*" vs ".*does not exist.*" is important.  The `DRAKE_EXPECT_THROWS_MESSAGE` macro provides a concise spelling for matching exception messages.
___
*[multibody/parsing/test/package_map_test.cc, line 162 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaAqzTK80BVSlhvt1L6:-MaAqzTLDql9jOiH_7Xx:bxc6hid) ([raw file](https://github.com/robotlocomotion/drake/blob/f4142df97ec84ccc7988e8da57ffbb383e97b997/multibody/parsing/test/package_map_test.cc#L162)):*
> ```cpp
> 
>   // Combining package maps with a conflicting package + path throws.
>   EXPECT_THROW({
> ```

nit Use `DRAKE_EXPECT_THROWS_MESSAGE` for better readability / conciseness.
___
*[multibody/parsing/test/package_map_test.cc, line 201 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaAqcyB3v-1Be3oLQQS:-MaAqcyB3v-1Be3oLQQT:b-9o4x4w) ([raw file](https://github.com/robotlocomotion/drake/blob/f4142df97ec84ccc7988e8da57ffbb383e97b997/multibody/parsing/test/package_map_test.cc#L201)):*
> ```cpp
>       "package.xml");
>   EXPECT_THROW(
>       package_map.AddPackageXml(conflicting_xml_filename), std::runtime_error);
> ```

Ditto here, we need to disambiguate "no such xml file" vs "conflicts with".

**Review by calderpg-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[multibody/parsing/test/package_map_test.cc, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaABgC9C_t8V4RsckH0:-MaAzqE60_SdBW1Qak9G:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08c08749ac1e49c1e1370dc489d62bee68440cc0/multibody/parsing/test/package_map_test.cc#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Still nothing here shows easy proof to the reader that the predicates are checking what the comments claim they are checking.  One easy way to convince the reader would be to check that the error message string is consistent with the claim.  Checking the exact message string would be overkill and brittle, but confirming whether it said ".*conflicts with.*" vs ".*does not exist.*" is important.  The `DRAKE_EXPECT_THROWS_MESSAGE` macro provides a concise spelling for matching exception messages.
</blockquote></details>

Done.
___
*[multibody/parsing/test/package_map_test.cc, line 162 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaAqzTK80BVSlhvt1L6:-MaAzqvi2IWE5X1xCbKb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4142df97ec84ccc7988e8da57ffbb383e97b997/multibody/parsing/test/package_map_test.cc#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Use `DRAKE_EXPECT_THROWS_MESSAGE` for better readability / conciseness.
</blockquote></details>

Done.
___
*[multibody/parsing/test/package_map_test.cc, line 201 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaAqcyB3v-1Be3oLQQS:-MaAzs4YDh9w6Umrmhs3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f4142df97ec84ccc7988e8da57ffbb383e97b997/multibody/parsing/test/package_map_test.cc#L201)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ditto here, we need to disambiguate "no such xml file" vs "conflicts with".
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Comment by calderpg-tri** [comment]
+@EricCousineau-TRI for platform review, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with BTW / nit on exposed asymmetry regarding error vs. warning for conflict package definitions.

> Reviewed 2 of 5 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064#-:-MaB6bcc9Ev2PiHJgU9e:bs0qmlt)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[multibody/parsing/package_map.h, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB5Gfs3m76VCE5Q8Z2:-MaB5Gft55MFOf0a63FK:bvdqvag) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/package_map.h#L59)):*
> ```objc
>   /// key is the package name as specified within `package.xml` and the
>   /// directory's path is the value.
>   void PopulateFromFolder(const std::string& path);
> ```

nit The following `Populate*` methods do not indicate that a warning is shown if attempt is made to add package with different path.

May be confusing now that it's documented above as an error; worth documenting?
(feel free to dismiss)
___
*[multibody/parsing/package_map.cc, line 147 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB4taWB4rRYyJpbxzo:-MaB4taWB4rRYyJpbxzp:b-4m2ctp) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/package_map.cc#L147)):*
> ```cpp
> }  // namespace
> 
> bool PackageMap::AddPackageIfNew(const string& package_name,
> ```

BTW This is slightly inconsistent behavior now; understandable for backwards compatibility, but may cause confusion down the road.

- Via `Add()`, this will throw an error.
- Via `Populate*`, it will just warn.
___
*[multibody/parsing/test/package_map_test.cc, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB6DgdAvej8b_xBFWx:-MaB6DgdAvej8b_xBFWy:bkmg4vf) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/test/package_map_test.cc#L193)):*
> ```cpp
>   // Adding a conflicting package.xml with the same package name but different
>   // path throws.
>   const string conflicting_xml_filename = FindResourceOrThrow(
> ```

nit I don't believe there's a *positive*  test that `Populate*` methods will admit conflicting overlap (vs. explicit `Add*()` which will throw).

At minimum, consider adding TODO?

**Review by calderpg-tri — COMMENTED** [review]
Presumably `PopulateFromEnvironment` is really the only one of these methods where this handling of duplicate paths is an explicit *feature* (i.e. handling workspace overlays in `ROS_PACKAGE_PATH`). As far as I can tell, the handling of conflicting package+path within `PopulateFromFolder`/`PopulateUpstreamToDrake` depends on the (unspecified) filesystem iteration order, and thus not something to rely on. Do we want to clarify/change/deprecate any of this behavior as well?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064#-:-MaBEYlHAB1sssHmss5K:b6srt1q)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Ah, good point!
Perhaps that's too much for this PR at this stage, but something to note with a small TODO or issue?
(And at least for `PopulateUpstreamFromDrake`, we *shouldn't* have conflicting packages :crossed_fingers:)

I also haven't kept up with how `ROS_PACKAGE_PATH` operates in the newer catkin / colcon devel / install environments; e.g. does it admit "stack" iteration / directory recursion? (if so, then you may also filesystem-dependent conflicts as is done with `PopulateFromFolder`?)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064#-:-MaE6sQf0ylFKx_Kb4XI:b-bp24r7)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Comment by jwnimmer-tri** [comment]
I wouldn't worry about changing the documentation or behavior of `PopulateUpstreamFromDrake`; we'll be deprecating and removing that as #14363 and #10531 make progress.

I think it's fair to argue that because the `Add` docs now talk about throwing on mismatch, it begs the question of what `PopulateFromEnvironment` and `PopulateFromFolder` do in that case, and therefore their documentation should be improved.  I don't see any reason to do more than just document that they ignore mismatches.  We definitely should not change their semantics in this PR, since that would be a breaking change, and is unrelated to the new features being proposed here.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

**Review by calderpg-tri — COMMENTED** [review]
`ROS_PACKAGE_PATH` behaves essentially the same in catkin, and IIRC, roughly the same in ROS2. "Higher" overlays appear first, ex `ROS_PACKAGE_PATH=/home/<user>/catkin_workspace/src:/opt/ros/melodic/share` in the devel case.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064#-:-MaESz5FEKt0Lt_DB_jU:bf7czfa)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

___
*[multibody/parsing/package_map.h, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB5Gfs3m76VCE5Q8Z2:-MaESl1B5eW6g6VQdSxE:bedxwcm) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/package_map.h#L59)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The following `Populate*` methods do not indicate that a warning is shown if attempt is made to add package with different path.

May be confusing now that it's documented above as an error; worth documenting?
(feel free to dismiss)
</blockquote></details>

Added documentation on behavior.
___
*[multibody/parsing/test/package_map_test.cc, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB6DgdAvej8b_xBFWx:-MaESu_rCq4jhAlbsuTe:b-kdffb7) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/test/package_map_test.cc#L193)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't believe there's a *positive*  test that `Populate*` methods will admit conflicting overlap (vs. explicit `Add*()` which will throw).

At minimum, consider adding TODO?
</blockquote></details>

Added docs above

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15064)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @calderpg-tri)

___
*[multibody/parsing/package_map.h, line 59 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB5Gfs3m76VCE5Q8Z2:-MaUB3Oe-RPvlatlWoXQ:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/package_map.h#L59)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Added documentation on behavior.
</blockquote></details>

OK Thanks!
___
*[multibody/parsing/test/package_map_test.cc, line 193 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15064#-MaB6DgdAvej8b_xBFWx:-MaUBAeR14LbVROEVJDW:b-d8j4vi) ([raw file](https://github.com/robotlocomotion/drake/blob/62430f5079863e19c8a9ccf7c493efaea2f1cbc5/multibody/parsing/test/package_map_test.cc#L193)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Added docs above
</blockquote></details>

OK Better!

**Pull request merged**
