### PR TITLE
Fix CI failures caused by #7814

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Attempts to resolve the following failures:

https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/267/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/263/

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7859)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything please

**Comment by soonho-tri** [comment]
+@soonho-tri 
:lgtm: 
+(status: do not merge)  until valgrind builds pass

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7859#-:-L3ie4rrlFvRLSVY4eqk:bx8m3ut)*

**Comment by kunimatsu-tri** [comment]
So quick! Thanks @soonho-tri!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7859#-:-L3ieJjhRjOhRDCHCmMZ:b-e7qed1)*

**Comment by amcastro-tri** [comment]
Thank you Kuni!! but wouldn't it be a waste of resources having this simple smoke test based on an example running for so long?
I can PR a little fix so that we can pass the simulation time as a flag for the test, like using something like `test_rule_args = ["--duration=0.1"]`. Now duration is set to 10, so that alone would decrease the runtime for testing to a factor of 1000.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7859#-:-L3j79wCk2muoPOnbGER:by049qu)*

**Comment by kunimatsu-tri** [comment]
Thanks @amcastro-tri and I like your idea!

OK, I will close this PR without merging it after CI finishes just so that we can see the result of *this* change.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7859#-:-L3j8VEo_cEpFMvrtU7X:bfxaret)*

**Comment by soonho-tri** [comment]
FYI,
- https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind/30/
- https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-bazel-experimental-memcheck-valgrind-everything/39/

**Pull request closed without merging**
