### PR TITLE
Cleanup/fix various installed targets and file locations

### PR DESCRIPTION
**Pull request by jamiesnape**
This cleans up some inconsistencies and minor breakages in the naming of CMake targets and installed locations of headers and CMake files. It should be mostly a no-op to end users of the installed packages, assuming that they are using `find_package` correctly and everywhere that they should be. The one exception is the optitrack lcmtypes, that were inconsistent with the drake and robotlocomotion lcmtypes. Users of those packages would need to change the targets that they use from `optitrack::lcmtypes_optitrack-{cpp|java}` to `optitrack::optitrack-lcmtypes-{cpp|java}`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7919)

### CODE REVIEW

**Comment by fbudin69500** [comment]
Disclaimer: I haven't tested it to see if the new include directories are correct, but LGTM.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7919#-:-L4anpB_-UTDdfMmMtnn:b-umd94q)*

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7919#-:-L4anzisyLq97u3bX1he:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for platform review.

**Comment by EricCousineau-TRI** [comment]
:LGTM: -  but before merging, could we wait until we have acknowledgement from downstream users about the optitrack target change? (I think the only one is us, and I'll ping Sammy.)

> Users of those packages would need to change the targets that they use from optitrack::lcmtypes_optitrack-{cpp|java} to optitrack::optitrack-lcmtypes-{cpp|java}.

@sammy-tri Would we need a follow-up PR / update for your Spartan branch to accommodate this target change?

I'm assuming that the other RobotLocomotion spartan users do not use the optitrack package in their workflows.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7919#-:-L4az1gKduqoB6lS9S7G:b-iyyhof)*

**Comment by jamiesnape** [comment]
No changes are needed to Spartan, and we had the discussion on Slack.

**Comment by EricCousineau-TRI** [comment]
Alright, sounds good to me!

**Pull request merged**
