### PR TITLE
remove dead code (matlab accessors) from rigid body tree

### PR DESCRIPTION
**Pull request by RussTedrake**
was not getting called from anywhere.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8171)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@sherm1 for both reviews, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8171#-:-L6BlwICrifAy6wxre-y:b-3q8wn7)*

**Comment by RussTedrake** [comment]
actually, +@hongkai-dai for feature review, too.  want to make sure you're not using these anywhere in your dev branches.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8171#-:-L6Ew-PN6uZ68TWZQ2hy:b-5fto79)*

**Comment by hongkai-dai** [comment]
:lgtm: I am not using them, but @diitsgp and @pangtao22 might use the surface tangent Jacobian

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8171#-:-L6EwY0ufcU3kA4IpjjV:bhzrwqv)*

**Comment by sherm1** [comment]
Awesome -- I love to see dead code disappear. :lgtm: but merge should wait until @DiitsGp and @pangtao22 weigh in.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8171#-:-L6FJUJudm-HWJyzWKxI:b4cpjlw)*

**Comment by pangtao22** [comment]
Please don't delete them just yet. I am using `computeContactJacobians` and `surfaceTangents`

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8171#-:-L6Hy7KHF35q_7mS_STj:bj1n886)*

**Comment by DiitsGp** [comment]
Wait can we not merge this for a week or so? I need some of this deprecated code for IROS deadline

**Comment by RussTedrake** [comment]
I will leave it for now.

**Pull request closed without merging**
