### PR TITLE
fixes SteeringCommandDriver.py throttle not being able to decrease

### LINKED ISSUE #4434: SteeringCommandDriver.py Throttle Can Only Increase
# Problem Definition

When running `drake-distro/drake/automotive/steering_command_driver.py`, the throttle value can only be increased, not decreased.

### PR DESCRIPTION
**Pull request by shensquared**
This fixes #4434, and adds the option of keeping the current throttle/brake. It also adds keyboard control instruction for better usability. 

+@liangfok for feature review, thanks.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4458)

### CODE REVIEW

**Comment by liangfok** [comment]
@shensquared: Thanks for doing this! I made a quick pass just now and will do a more thorough review tomorrow. 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/automotive/steering_command_driver.py, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlDcjPXPDaJlSNsDPu:-KYlDcjPXPDaJlSNsDPv:b-xep3ph) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L48)):*
> ```Python
>         return math.copysign(MAX_STEERING_ANGLE, requested_value)
> 
> # Since there are both throttle and brake values, they should be non-negative.
> ```

BTW, is it possible that this sentence may be confusing to someone who's not privy to how this program evolved? Consider simply stating the fact, like "Both the throttle and brake values should be non-negative." Or, even better, describe what this method is doing. For example: "Applies the lower and upper limits to @p requested value".

---

*[drake/automotive/steering_command_driver.py, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEXwNkMaWFm3sEClC:-KYlEXwNkMaWFm3sEClD:b-vnfryz) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L52)):*
> ```Python
>     if 0 <= requested_value <= MAX_VELOCITY:
>         return requested_value
>     elif 0 > requested_value:
> ```

This is in "Yoda" format (https://en.wikipedia.org/wiki/Yoda_conditions). Consider flipping it for clarity:

```
    elif requested_value < 0
```

(same comment below)

---

*[drake/automotive/steering_command_driver.py, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEu2cJXjlwzVebbw9:-KYlEu2cJXjlwzVebbwA:blg9t5s) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L116)):*
> ```Python
>         new_msg.brake = _limit_brake(
>                 last_msg.brake + self.brake_gradient * BRAKE_SCALE)
>         
> ```

BTW: nit: extraneous spaces.

---

*[drake/automotive/steering_command_driver.py, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEyrQ8IzshdbhwAOr:-KYlEyrQ8IzshdbhwAOs:blg9t5s) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L253)):*
> ```Python
>         print >>sys.stderr, 'error: missing pygame; see README.md for help.'
>         return 1
>         
> ```

BTW: nit: extraneous spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KYlF-Eo-mdnLpTUSHXR:bn51r0k)*

**Comment by liangfok** [comment]
+@liangfok since apparently assignment through GitHub did not get transferred into Reviewable.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KYlHR0G9sCqAsRyVlIY:b6gajao)*

**Comment by liangfok** [comment]
I created #4471 to document other ways `steering_command_driver.py` can be improved.

I finished my first round of feature review. PTAL.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxLLEzkPqJygJ5u79:-KYnxLLEzkPqJygJ5u7A:b-tnnobr) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
> ```Python
>                 elif (event.key == pygame.K_DOWN):
>                     self.brake_gradient = -1 
>             # Post a fake KEYUP event so that the throttle/brake can keep 
> ```

BTW: nit: delete "that".

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxa10EwORQ0O_bSjh:-KYnxa10EwORQ0O_bSji:b65wbwr) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
> ```Python
>                 elif (event.key == pygame.K_DOWN):
>                     self.brake_gradient = -1 
>             # Post a fake KEYUP event so that the throttle/brake can keep 
> ```

BTW: nit: extraneous spaces at the end of the line. (Same for the subsequent three lines.)

Some text editors can be configured to highlight trailing spaces. Consider enabling it on your text editor if such a feature is supported.

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYo3_jYljLArAR5nqDm:-KYo3_jYljLArAR5nqDn:b-37g2jc) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
> ```Python
>                 elif (event.key == pygame.K_DOWN):
>                     self.brake_gradient = -1 
>             # Post a fake KEYUP event so that the throttle/brake can keep 
> ```

BTW, I personally feel that faking a `KEYUP` event is a bit hacky. Can you think of a better way to achieve the same results that does not require faking key presses? Maybe splitting this code into a Finite State Machine and a trajectory generator?

(I marked this as BTW because I recognize this may require a major re-write and didn't want to overburden you.)

---

*[drake/automotive/steering_command_driver.py, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxQZqM_caroKKU3QP:-KYnxQZqM_caroKKU3QQ:b-3eome3) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L88)):*
> ```Python
>             # Post a fake KEYUP event so that the throttle/brake can keep 
>             # decreasing in the absence of real (and impossible) successive 
>             # key releasing. Yield to any KEYDOWN event waiting in the queue. 
> ```

BTW: nit: replace "releasing" with "releases".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KYo0NLCeSxUoeTJZYTP:bai9bda)*

**Comment by shensquared** [comment]
I addressed the comments, sorry for the delay. 

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/steering_command_driver.py, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlDcjPXPDaJlSNsDPu:-KYyxi-mrIrg3W5Mr4SS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L48)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, is it possible that this sentence may be confusing to someone who's not privy to how this program evolved? Consider simply stating the fact, like "Both the throttle and brake values should be non-negative." Or, even better, describe what this method is doing. For example: "Applies the lower and upper limits to @p requested value".
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEXwNkMaWFm3sEClC:-KYyxiur0XA4vYt_mbj2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L52)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This is in "Yoda" format (https://en.wikipedia.org/wiki/Yoda_conditions). Consider flipping it for clarity:

```
    elif requested_value < 0
```

(same comment below)
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxa10EwORQ0O_bSjh:-KYuDDKmFywyj_XzuhOu:b63a06g) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: extraneous spaces at the end of the line. (Same for the subsequent three lines.)

Some text editors can be configured to highlight trailing spaces. Consider enabling it on your text editor if such a feature is supported.
</blockquote></details>

thanks for the tip! it's so much easier to spot them now. 

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYo3_jYljLArAR5nqDm:-KYuDNNyFBecsFFQtzUL:b-8mv61x) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I personally feel that faking a `KEYUP` event is a bit hacky. Can you think of a better way to achieve the same results that does not require faking key presses? Maybe splitting this code into a Finite State Machine and a trajectory generator?

(I marked this as BTW because I recognize this may require a major re-write and didn't want to overburden you.)
</blockquote></details>

I actually tried a few other ways under the current setup. I tried to query if any of the arrow keys are currently being pressed, (maybe what you mean by finite state machine?) but as pygame API doc noted, it's not very reliable (http://www.pygame.org/docs/ref/key.html#pygame.key.get_pressed). I also tried using KEYUP as a flag to enter a different loop, one that doesn't rely on event.wait()  API, but this would be also be hacky, and even messier than the fake KEYUP event because it needs additional hack to synchronize with the actual pygame delay (it processes with 10ms intervals)

A different setup would be to also add modifier keys. So for example pressing UP alone = increase, ctrl and up = decrease, and releasing up = keep current value. This is actually easier to implement, I passed it only because it felt less intuitive. 

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxLLEzkPqJygJ5u79:-KYyxjFC50wIaAnkGboC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: delete "that".
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 88 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYnxQZqM_caroKKU3QP:-KYyxkLwe4-WedXSHgKn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L88)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: replace "releasing" with "releases".
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 116 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEu2cJXjlwzVebbw9:-KYyxkn-pCUIyGW0V9jB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L116)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: extraneous spaces.
</blockquote></details>

Done.

---

*[drake/automotive/steering_command_driver.py, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEyrQ8IzshdbhwAOr:-KYyxlAIZdKn5hycHJO7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L253)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: extraneous spaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KYyxM3Y5Kj3d9lb8uCA:bf7cedo)*

**Comment by liangfok** [comment]
Very nice. :lgtm: 

I was just thinking having unit test coverage for this program would be nice, but I'm not sure it's worth it or how to do it without having an LCM mocking framework in Python. Thoughts?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/steering_command_driver.py, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYo3_jYljLArAR5nqDm:-KYzdB72ELS_hr001xip:b-53r083) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L86)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

I actually tried a few other ways under the current setup. I tried to query if any of the arrow keys are currently being pressed, (maybe what you mean by finite state machine?) but as pygame API doc noted, it's not very reliable (http://www.pygame.org/docs/ref/key.html#pygame.key.get_pressed). I also tried using KEYUP as a flag to enter a different loop, one that doesn't rely on event.wait()  API, but this would be also be hacky, and even messier than the fake KEYUP event because it needs additional hack to synchronize with the actual pygame delay (it processes with 10ms intervals)

A different setup would be to also add modifier keys. So for example pressing UP alone = increase, ctrl and up = decrease, and releasing up = keep current value. This is actually easier to implement, I passed it only because it felt less intuitive. 
</blockquote></details>

OK thanks for all of the thought put into this.

By "finite state machine" I meant some way of remembering the context to avoid needing to fake a particular key being pressed.

I'll mark this thread is resolved to prevent it from blocking this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KYzdgu7ZS_tNfdjlbrQ:b7tgk5r)*

**Comment by shensquared** [comment]
+@RussTedrake for platform review, thanks.

**Comment by shensquared** [comment]
Thanks, @liangfok. Since you mentioned LCM mocking framework, I sense you were referring to testing the entire program, from keyboard activity to the LCM msg sent? If so, I don't have any idea/opinion. In fact I found a relevant thread #3546 and I'm lost for the most part of the discussion. But FWIW, at least for `KeyboardEventProcessor` unit test alone, I understand it and I'm happy to add it.

Btw, reviewable just let me know I failed to add Russ as reviewer because I don't have push permissions for drake. Could you help assign him, or any other team member you see fit? Thanks.

**Comment by liangfok** [comment]
Actually, a "mock" is a fake and typically simpler stand-in for something real but complex. https://en.wikipedia.org/wiki/Mock_object

In this case, the "something" is LCM itself. In C++ Drake, we added a [mocking framework](https://github.com/RobotLocomotion/drake/tree/6d7e1b5b05a39a77a240fc39b5d9bd8c0aa06a1c/drake/lcm) to allow a unit test to "send" a message without the message actually being transmitted across the network. To properly test  `SteeringCommandDriver.py`, I believe we're going to need to mock both LCM and the `KeyboardEventProcessor`.

**Comment by liangfok** [comment]
+@jwnimmer-tri for platform review per rotation schedule.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KZ-AFQC4k1UXKajRu4n:btkcyl9)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/steering_command_driver.py, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEyrQ8IzshdbhwAOr:-KZ-AU-TaEkKXHAnqQr1:bfkk5r8) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L253)):*
<details><summary><i>Previously, shensquared (Shen Shen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like the trailing spaces are still here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458)*

**Comment by shensquared** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/steering_command_driver.py, line 253 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KYlEyrQ8IzshdbhwAOr:-KZ-BeaG00vOClkeoE9C:b-b6cf2j) ([raw file](https://github.com/robotlocomotion/drake/blob/414f6390bfd70bd8e683f198e8b332a0f0a29f27/drake/automotive/steering_command_driver.py#L253)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Looks like the trailing spaces are still here.
</blockquote></details>

oops... missed this one. Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458)*

**Comment by liangfok** [comment]
After a F2F meeting with @jwnimmer-tri this morning, I discovered a major bug with the changes we've been making to `steering_command_driver.py`: https://github.com/RobotLocomotion/drake/issues/4471. @jwnimmer-tri is currently studying the code to determine the best course of action.

**Comment by jwnimmer-tri** [comment]
:lgtm: Let's just merge this.  The entire thing needs rewrite anyway, and this isn't really any worse than what's on master now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/steering_command_driver.py, line 63 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-KZ1sOSxaJDtR6gb-Ifw:-KZ1sOSyZUzl8dmIbpCa:by2n3sz) ([raw file](https://github.com/robotlocomotion/drake/blob/64756e116a2785366be745160ee862273363bec8/drake/automotive/steering_command_driver.py#L63)):*
> ```Python
>         return 0
>     else:
>         return MAX_BRAKE
> ```

FYI Implementing this method (and the above) as `return max(0, min(requested_value, MAX_BRAKE))` would be more conventional, but this is correct and fine to leave as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4458#-:-KZ2QsM5hysHSnhg9-KD:b-6xymkh)*

**Pull request merged**
