### PR TITLE
Added semi-explicit Euler integrator.

### PR DESCRIPTION
**Pull request by edrumwri**
Adds semi-explicit Euler integration (thereby adding symplectic integration for Hamiltonian systems) and also stresses the conversions between generalized coordinates and generalized velocities (when the two are distinct).

*This PR has uncovered a bug in rigid body angular velocity / time derivative of Euler parameter conversions and should not be merged. A proper unit test for rigid body angular velocity / time derivative of Euler parameter is forthcoming (to help address the aforementioned bug), and another PR will address that bug before this merge is attempted.*

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4340)

### CODE REVIEW

**Comment by sherm1** [comment]
Checkpointing. Very nice. Some comments so far.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxr0kbdA3bqtx7EVDL:-KXxr0kbdA3bqtx7EVDM:b-h33m8e) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L16)):*
> ```objc
>  * q(t0+h) = q(t0) + qdot * h
>  * </pre>
>  * where `v = dx/dt` are the generalized velocity variables, `q` are generalized
> ```

BTW, should use ꝗ (qbar) rather than x for consistency with IntegratorBase. Actually is there any reason to mention quasi-coordinates at all here? v is a state variable here -- only its derivative appears and we integrate to q rather than qbar.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxsjUvDuelv7ABt4XY:-KXxsjUvDuelv7ABt4XZ:bb0qq6j) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L21)):*
> ```objc
>  * to time derivatives of position coordinates. For rigid body systems in 2D,
>  * for example, `N` will generally be an identity matrix. For rigid body systems
>  * in 3D, `N` and its transpose are frequently used to transform between
> ```

transpose->inverse

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxtBES6ELJgwuYCSd9:-KXxtBES6ELJgwuYCSdA:b-uven4y) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L34)):*
> ```objc
>  * Euler integrator is a symplectic (momentum conserving) integrator. 
>  * Symplectic integrators promise energetically consistent behavior with large 
>  * step sizes compared to non-symplectic integrators.
> ```

BTW, add "Note that a multibody system will not be Hamiltonian even in the absence of applied velocity-dependent forces, because of Coriolis and gyroscopic forces. These terms can be large in relative coordinate representations like Drake's."

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxuFcdrOVDIELh7oPx:-KXxuFcdrOVDIELh7oPy:bywt2ra) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L56)):*
> ```objc
>  * integration can conceivably be applied to these problems (using, e.g.,
>  * collocation methods), but we are unaware of a working such method in
>  * existence. 
> ```

The above paragraph seems out of place here. It doesn't apply to an integrator, just a time stepper. The time stepper calculates delta-v using the velocity constraints; here delta-v follows only the acceleration constraints that are built into dv/dt. I don't see how those could be used to make an impulsive delta-v that would handle Painleve. Why do you want to include this text here?

A possibly more relevant discussion would be the difference between this semi-explicit scheme and the truly symplectic semi-implicit (aka Symplectic Euler) scheme. That explains why we don't actually get sympecticity here.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxv_704Xo_N2IsY0_5:-KXxv_704Xo_N2IsY0_6:b-37s3wr) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L74)):*
> ```objc
>  * converges to the solution of the continuous time rigid body dynamics problem
>  * as the integration step goes to zero. The practical effect is of losing
>  * first order accuracy when unilateral constraints are present.
> ```

Not sure why the last two sentences are here?

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxvsSvl_Xh2N5XNulF:-KXxvsSvl_Xh2N5XNulG:b-u5bl3b) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L95)):*
> ```objc
>    * Constructs a fixed-step integrator for a given system using the given
>    * context for initial conditions.
>    * @param system A reference to the system to be simulated
> ```

BTW, period.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxvoKilcgcj2LbbKUJ:-KXxvoKilcgcj2LbbKUK:bevo7l1) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L97)):*
> ```objc
>    * @param system A reference to the system to be simulated
>    * @param max_step_size The maximum (fixed) step size; the integrator will
>    *                      not take larger step sizes than this.
> ```

This seems slightly untrue due to stretching.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-:-KXxw_r3Ci8BociDiy4x:b1a0mqx)*

**Comment by edrumwri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 56 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxuFcdrOVDIELh7oPx:-KXxx9cVC25BGq27IXZr:b-ggurn8) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The above paragraph seems out of place here. It doesn't apply to an integrator, just a time stepper. The time stepper calculates delta-v using the velocity constraints; here delta-v follows only the acceleration constraints that are built into dv/dt. I don't see how those could be used to make an impulsive delta-v that would handle Painleve. Why do you want to include this text here?

A possibly more relevant discussion would be the difference between this semi-explicit scheme and the truly symplectic semi-implicit (aka Symplectic Euler) scheme. That explains why we don't actually get sympecticity here.
</blockquote></details>

I was still working on this part of the documentation. Didn't expect you to review it tonight!

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxvoKilcgcj2LbbKUJ:-KXxxL-8REQnlnVYvgwb:b-h6j3ng) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L97)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This seems slightly untrue due to stretching.
</blockquote></details>

Going to comment on David's PR now :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4340)*

**Comment by edrumwri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxsjUvDuelv7ABt4XY:-KY0z5H2KBGo5RO4hap-:bvp637z) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

transpose->inverse
</blockquote></details>

PTAL now- it will be the transpose in the example I described.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxtBES6ELJgwuYCSd9:-KY1--hRIpEPyciacZc8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, add "Note that a multibody system will not be Hamiltonian even in the absence of applied velocity-dependent forces, because of Coriolis and gyroscopic forces. These terms can be large in relative coordinate representations like Drake's."
</blockquote></details>

Done.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxv_704Xo_N2IsY0_5:-KY1-5Zk-xInuowjuoGj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L74)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Not sure why the last two sentences are here?
</blockquote></details>

Done.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxvsSvl_Xh2N5XNulF:-KXxyawNCzWrr155GE5R:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L95)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, period.
</blockquote></details>

Done.

---

*[drake/systems/analysis/semi_explicit_euler_integrator.h, line 97 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4340#-KXxvoKilcgcj2LbbKUJ:-KY1-eh96mWS0v2elyXg:barjtim) ([raw file](https://github.com/robotlocomotion/drake/blob/edbec39d5e01e82d389a42a29ba0b3462f7dc902/drake/systems/analysis/semi_explicit_euler_integrator.h#L97)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Going to comment on David's PR now :+1: 
</blockquote></details>

Done- put in a TODO to deal with this properly. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4340)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental please

**Comment by edrumwri** [comment]
This PR has become "stale" and is being superseded by PR #5017.

**Pull request closed without merging**
