### PR TITLE
[lcm] De-flake a unit test again

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sBI423gd7Jdg28FVF:b2z8vck) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've been trying to finagle the test and am running into obstacles.

The normal test condition is that we publish a message on an appropriately suffixed channel and confirm it gets executed.

The discard test condition is trickier. It's not enough to say "my callback didn't get invoked". Because it might have been not invoked because the message simply got lost (the joys of udp).

So, we need a mechanism that confirms `DrakeLcm` has received the message and subsequently opted to discard it because of suffix reasons.

The best I can do right now is *assume* that the message reaches `DrakeLcm` then interpret non-exercise of the callback as evidence of discarding.
</blockquote></details>

The `EXPECT_EQ(channel_name, "SuffixInMultiChannel");` within the callback is what confirms that the callback was only ever called with appropriately-named messages.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6s8hJX2qfPZBolWapg:b-r57n3x) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `EXPECT_EQ(channel_name, "SuffixInMultiChannel");` within the callback is what confirms that the callback was only ever called with appropriately-named messages.
</blockquote></details>

I'm still not completely understanding this:

1. If I change the for loop to publish only the "wrong' message, the test fails because `LoopUntilDone` considers not receiving a message that matches `message_` to represent failure. (So, this can't distinguish between "got the wrong message" and "no message received").
2. If I change both publish channels to have the target suffix, the test still passes. This despite the fact half the time we're ostensibly decoding the wrong message. However, by the time `LoopUntilDone` gets involved, it sees the right message at least once.
    - Could this be due to the fact that we publish the "good" message second?
    - Nope. Reversing the publishing order still passes. But given both subscribers write to the same `lcmt_drake_signal`, it must be that regardless of publish order, the right message gets handled last at least once.

So, testing for the discard is....tricky.

**Comment by SeanCurtis-TRI** [comment]
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sBg2H80heRBuhIMYx:b-yq32hq) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
> EXPECT_EQ(channel_name, "SuffixInMultiChannel"); 

But we have the promise that if the callback is invoked, the suffix is stripped off. So, if a bad suffix is detected, but doesn't get detected, it will still invoke the callback with the "unadorned" channel name. That condition seems insufficient.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sBqHw9wZ1vUVwlqX4:bcikcqo) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

(oops  "...bad suffix is detected, but doesn't get __*discarded*__, ...)
</blockquote></details>

Here's a helpful command line: `bazel test --compilation_mode=dbg //lcm:drake_lcm_test --nocache_test_results --test_output=streamed --test_arg=--gtest_filter='*SuffixInMultiChannel' --test_arg=--spdlog_level=debug`.

Running that, I see:
```
[ RUN      ] DrakeLcmTest.SuffixInMultiChannel
[2022-07-13 15:36:17.623] [console] [debug] DrakeLcm with suffix _SUFFIX received message on channel LCM_SELF_TEST, which lacks the suffix.
[2022-07-13 15:36:17.623] [console] [debug] DrakeLcm with suffix _SUFFIX received message on channel SuffixInMultiChannel_ShouldBeDiscarded, which lacks the suffix.
```

I'll also try to play with the test inputs to see if I can offer better explanations or test fixups.

**Comment by jwnimmer-tri** [comment]
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sDB1FBWbLd8yHGvf9:b4bqs6w) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here's a helpful command line: `bazel test --compilation_mode=dbg //lcm:drake_lcm_test --nocache_test_results --test_output=streamed --test_arg=--gtest_filter='*SuffixInMultiChannel' --test_arg=--spdlog_level=debug`.

Running that, I see:
```
[ RUN      ] DrakeLcmTest.SuffixInMultiChannel
[2022-07-13 15:36:17.623] [console] [debug] DrakeLcm with suffix _SUFFIX received message on channel LCM_SELF_TEST, which lacks the suffix.
[2022-07-13 15:36:17.623] [console] [debug] DrakeLcm with suffix _SUFFIX received message on channel SuffixInMultiChannel_ShouldBeDiscarded, which lacks the suffix.
```

I'll also try to play with the test inputs to see if I can offer better explanations or test fixups.
</blockquote></details>

I don't understand yet why you think the test is insufficient.  If I introduce this bug into the implementation, the test fails:
```patch
--- a/lcm/drake_lcm.cc
+++ b/lcm/drake_lcm.cc
@@ -297,12 +297,12 @@ std::shared_ptr<DrakeSubscriptionInterface> DrakeLcm::SubscribeAllChannels(
           if (channel.length() >= suffix.length() &&
               channel.substr(channel.length() - suffix.length()) == suffix) {
             channel.remove_suffix(suffix.length());
-            handler(channel, data, length);
           } else {
             drake::log()->debug("DrakeLcm with suffix {} received message on"
                                 " channel {}, which lacks the suffix.",
                                 suffix, channel);
           }
+          handler(channel, data, length);
         };
   }
 
```

**Comment by jwnimmer-tri** [comment]
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sEHDQEYw44dz8Tsnm:b-vrmss3) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't understand yet why you think the test is insufficient.  If I introduce this bug into the implementation, the test fails:
```patch
--- a/lcm/drake_lcm.cc
+++ b/lcm/drake_lcm.cc
@@ -297,12 +297,12 @@ std::shared_ptr<DrakeSubscriptionInterface> DrakeLcm::SubscribeAllChannels(
           if (channel.length() >= suffix.length() &&
               channel.substr(channel.length() - suffix.length()) == suffix) {
             channel.remove_suffix(suffix.length());
-            handler(channel, data, length);
           } else {
             drake::log()->debug("DrakeLcm with suffix {} received message on"
                                 " channel {}, which lacks the suffix.",
                                 suffix, channel);
           }
+          handler(channel, data, length);
         };
   }
 
```
</blockquote></details>

Ah.  The reason for the flakiness is that the `SubscribeAllChannels` uses a queue capacity of 1, so we're dropping messages like crazy.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sEe9c3ubWli-Qf_AG:b-kc6j45) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  The reason for the flakiness is that the `SubscribeAllChannels` uses a queue capacity of 1, so we're dropping messages like crazy.
</blockquote></details>

I was wondering if we were dropping messages.

As for "insufficient". ThIt's true that the test is sufficiently robust for *that* bug (the one caught in review), but there are other implementation errors that it wouldn't detect. That said, I'm content with a glass-box argument that we *know* only the expected suffix is removed. If we fail to discard, we also fail to strip the bad suffix so a channel name with a bad suffix presented to the callback would be proof of discard failure.

**Review by jwnimmer-tri — COMMENTED** [review]
+@ggould-tri and +@SeanCurtis-TRI for review, please.

+(priority: high) is this is still a release blocker.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561#-:-N6sH1di5TzvRgm_WX74:beypsy2)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),ggould-tri(platform), missing label for release notes (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`lcm/test/drake_lcm_test.cc` line 405 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17561#-N6rzazT329vrjzlt8-H:-N6sGrHKCkzpWtXSEJ_T:b-bkuvy1) ([raw file](https://github.com/robotlocomotion/drake/blob/4d9784b2d0f575c85427e87d3683a297a5ed0645/lcm/test/drake_lcm_test.cc#L405)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was wondering if we were dropping messages.

As for "insufficient". ThIt's true that the test is sufficiently robust for *that* bug (the one caught in review), but there are other implementation errors that it wouldn't detect. That said, I'm content with a glass-box argument that we *know* only the expected suffix is removed. If we fail to discard, we also fail to strip the bad suffix so a channel name with a bad suffix presented to the callback would be proof of discard failure.
</blockquote></details>

I actually think it's robust to all errors.  If you can think of an implementation bug it won't catch, let me know.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  We can relocate the enlarged queue size from the test to the implementation in a later PR.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17561#-:-N6sL4K9CZgAhE1U4GuF:b2e80l8)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
I've filed #17564 as a reminder to upgrade the default.

**Pull request merged**
