### PR TITLE
[fem] Report status of Petsc solver

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Fix a size mismatch in unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.

**Comment by xuchenhan-tri** [comment]
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-eWkU-Ahdl5AAUGsNc:-N-eWkU-Ahdl5AAUGsNd:b-v4cmf8) ([raw file](https://github.com/robotlocomotion/drake/blob/a6d67a52c91bae4e6f28e847bea04a10dd5a8c26/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L235)):*
> ```cpp
>   unique_ptr<PetscSymmetricBlockSparseMatrix> A = MakeBlockSparseMatrix();
>   A->set_relative_tolerance(kEps);
>   const VectorXd b = MakeVector9d();
> ```

This is the fix. In the previous PR we made b a vector3 instead of a vector9.

**Review by xuchenhan-tri — COMMENTED** [review]
+@svenevs for feature review please. I highlighted the one line fix.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-eX0Zb5QBPUtdQeRDc:b-guxanb)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
FYI when merging this, we'd like subject line to avoid double negatives, and be more direct:

```
[fem] Report status of Petsc solver (#16975)
```

If you like, the commit message body can mention the prior commit id's that this is replaying (or unreverting).

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-eYJMXDZ9kT5YhdlQF:-N-eYJMY2e_le7inYrnc:bda18kb) (no related file):*
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.

---

**Review by xuchenhan-tri — COMMENTED** [review]
I cleaned up the subject line and the commit message.
+@jwnimmer-tri for platform review (if it's not too late).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-eYUbhDdu3YVVi9DHw:b-3oac0e)* status: LGTM missing from assignees jwnimmer-tri(platform),svenevs (waiting on @jwnimmer-tri and @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
The test case is actually failing now even in regular builds.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-e_S7xDweQHz1qz0Ra:bbzisjp)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),svenevs (waiting on @svenevs and @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 109 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-e_ohoCXY3IvZHF1QG:-N-e_ohoCXY3IvZHF1QH:b3h86eu) ([raw file](https://github.com/robotlocomotion/drake/blob/0c8b03535db2cf321beb3c28effcbb5fdc4e3a78/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L109)):*
> ```cpp
>                           EigenPtr<VectorX<double>> x) const {
>     ThrowIfNotAssembled(__func__);
>     DRAKE_DEMAND(x != nullptr);
> ```

nit I advise adding `DRAKE_ASSERT()` on the size of b and x here (and also `b_in_x_out`, below).  That would bring any future size mismatches in scope during our typical Debug builds, instead of relying on post-merge ASan to catch us.

**Comment by xuchenhan-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-eYJMXDZ9kT5YhdlQF:-N-fLFkW-uUdJ-J9qJVX:b-ub9ek6) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.

</blockquote></details>

@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please.

---

**Review by xuchenhan-tri — COMMENTED** [review]
:man_facepalming: Sorry about the mess. Here's another try.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-fLj-Y1dLb2upt8HI2:bnd1zba)* status: LGTM missing from assignees jwnimmer-tri(platform),svenevs (waiting on @jwnimmer-tri and @svenevs)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 109 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-e_ohoCXY3IvZHF1QG:-N-fLMut-J4w1JpdzCRQ:b-qu6n94) ([raw file](https://github.com/robotlocomotion/drake/blob/0c8b03535db2cf321beb3c28effcbb5fdc4e3a78/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I advise adding `DRAKE_ASSERT()` on the size of b and x here (and also `b_in_x_out`, below).  That would bring any future size mismatches in scope during our typical Debug builds, instead of relying on post-merge ASan to catch us.
</blockquote></details>

Good point. Done.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 240 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16975#-N-fLR6JESpVdWCmgoV0:-N-fLR6JESpVdWCmgoV1:b31va38) ([raw file](https://github.com/robotlocomotion/drake/blob/0c8b03535db2cf321beb3c28effcbb5fdc4e3a78/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L240)):*
> ```cpp
>   PetscSolverStatus status = A->Solve(
>       PetscSymmetricBlockSparseMatrix::SolverType::kConjugateGradient,
>       PetscSymmetricBlockSparseMatrix::PreconditionerType::kIncompleteCholesky,
> ```

FYI, It looks like the preconditioner is smart enough to handle the problem so I turned it off to produce the failure of convergence.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-hU4jqAkcRPFjSriSO:b-b5dc06)* status: LGTM missing from assignee svenevs (waiting on @svenevs)

**Review by xuchenhan-tri — COMMENTED** [review]
-@svenevs 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16975#-:-N-xP0ga98LSQ2HYBS3k:btyxbuq)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
