### PR TITLE
Templates RigidBodyFrame on <T>

### PR DESCRIPTION
**Pull request by amcastro-tri**
This is a step towards the completion of #3987. Just a refactor templating `RigidBodyFrame` on `<T>` and replacing all use cases in the codebase by `RigidBodyFrame<double>`.
As it is right now, we cannot explicitly instantiate `RBT` on a scalar type different from `double`. This PR is a step forward towards that goal.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4406)

### CODE REVIEW

**Comment by sherm1** [comment]
When this is ready for review, I suggest @mitiguy who has been thinking a lot about frames!

**Comment by amcastro-tri** [comment]
+@liangfok for feature review please.
+@sammy-tri for platform review please.

This PR already passed CI but I rebased (and push -f) adding a few comments. Therefore it is ready to go into master.

---

Review status: 0 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-:-KYPRWt2B7aQex9OtNDp:b-hqfpq2)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-:-KYPVF09366nmEJRt2gY:bnfp4nl)*

**Comment by liangfok** [comment]
I completed my first round of feature review. A bunch of minor comments. PTAL.

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/bindings/python/pydrake/__init__.py, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPUqnOCsQJVvLOSM91:-KYPUqnOEW1hK1oVAf6P:bk0ybl4) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/bindings/python/pydrake/__init__.py#L9)):*
> ```Python
>     from autogenerated_path import getDrakePath
> except ImportError:
>     from insource_path import getDrakePath
> ```

BTW, I know this is a preexisting defect, but could you add the missing newline here?

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVqI91_sTXDZytwbx:-KYPVqI94VQJ2n_PwuiG:bp4z9gl) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/valkyrie_simulation.cc#L101)):*
> ```cpp
>   std::vector<RigidBodyFrame<double>> force_torque_sensor_info = {
>       RigidBodyFrame<double>("leftFootFTSensor", tree.FindBody("leftFoot"),
>                      Isometry3<double>::Identity()),
> ```

Please indent this line to match beginning of the parameter list on preceding line.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVvUT1BPqh1M8Mvp9:-KYPVvUT0pMCu7nPvgMI:bp4z9gl) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/valkyrie_simulation.cc#L103)):*
> ```cpp
>                      Isometry3<double>::Identity()),
>       RigidBodyFrame<double>("rightFootFTSensor", tree.FindBody("rightFoot"),
>                      Isometry3<double>::Identity())};
> ```

Please indent this line to match beginning of the parameter list on preceding line.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW1_-7ltOEukDXX6w:-KYPW1_-6fx7VnqterFg:bp4z9gl) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L92)):*
> ```cpp
>     foot_ft_sensor_info[side] =
>         RigidBodyFrame<double>(foot_names[side] + "FTSensor",
>                        tree.FindBody(foot_names[side]), foot_ft_sensor_offset);
> ```

Please indent this line to match beginning of the parameter list on preceding line.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW2MG6efNE4tR1gZh:-KYPW2MHDZP5XI4q3dRZ:bp4z9gl) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L95)):*
> ```cpp
>     hand_ft_sensor_info[side] =
>         RigidBodyFrame<double>(hand_names[side] + "FTSensor",
>                        tree.FindBody(hand_names[side]), hand_ft_sensor_offset);
> ```

Please indent this line to match beginning of the parameter list on preceding line.

---

*[drake/multibody/parser_sdf.cc, line 434 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW5Uc5YEkvKYWgMYS:-KYPW5UcE2i_5-YC7gfN:bndad90) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L434)):*
> ```cpp
>   std::shared_ptr<RigidBodyFrame<double>> frame =
>       allocate_shared<RigidBodyFrame<double>>(
>       Eigen::aligned_allocator<RigidBodyFrame<double>>(), name, link, xyz, rpy);
> ```

Please indent this line by four more spaces.

---

*[drake/multibody/parser_sdf.cc, line 577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWHKV510x7vUohoxg:-KYPWHKV3sSKzRguA0Or:b-sgw3pm) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L577)):*
> ```cpp
>         transform_parent_to_model.inverse() * loop_point_model;
> 
>     std::shared_ptr<RigidBodyFrame<double>> frameA =
> ```

BTW, Consider using `auto frameA` here if possible.

---

*[drake/multibody/parser_sdf.cc, line 579 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWAcF5Dlaif0UTn-c:-KYPWAcF9AE8NAgHhKYI:b-4z4azw) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L579)):*
> ```cpp
>     std::shared_ptr<RigidBodyFrame<double>> frameA =
>         allocate_shared<RigidBodyFrame<double>>(
>         Eigen::aligned_allocator<RigidBodyFrame<double>>(),
> ```

Please indent this line and the subsequent two lines by four additional spaces.

---

*[drake/multibody/parser_sdf.cc, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWLoC8Vbipp_8VZil:-KYPWLoCEZSPJ4mtHPMv:b-z8ami3) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L583)):*
> ```cpp
>         loop_point_parent, Vector3d::Zero());
> 
>     std::shared_ptr<RigidBodyFrame<double>> frameB =
> ```

BTW, Consider using `auto frameB` here if possible.

---

*[drake/multibody/parser_sdf.cc, line 585 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWGka4btMqkeo_hoH:-KYPWGka8bUXrAV7l0fM:b-4z4azw) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L585)):*
> ```cpp
>     std::shared_ptr<RigidBodyFrame<double>> frameB =
>         allocate_shared<RigidBodyFrame<double>>(
>         Eigen::aligned_allocator<RigidBodyFrame<double>>(),
> ```

Please indent this line and the subsequent two lines by four additional spaces.

---

*[drake/multibody/parser_urdf.cc, line 864 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVaofB6uHQqOekFYl:-KYPVaof6f1PYmSm8_J0:b-bjgp28) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L864)):*
> ```cpp
>   std::shared_ptr<RigidBodyFrame<double>>
>       frameA = MakeRigidBodyFrameFromUrdfNode(
>       *tree, *link_node, link_node, name + "FrameA", model_instance_id);
> ```

Please indent this line by another four spaces.

---

*[drake/multibody/parser_urdf.cc, line 869 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVaBpB07tLOem5Mcw:-KYPVaBp5_yzqDkTsJMW:b-bjgp28) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L869)):*
> ```cpp
>   std::shared_ptr<RigidBodyFrame<double>> frameB =
>       MakeRigidBodyFrameFromUrdfNode(
>       *tree, *link_node, link_node, name + "FrameB", model_instance_id);
> ```

Please indent this line by another four spaces.

---

*[drake/multibody/parser_urdf.cc, line 888 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVWEW2a9gCd8QWBKO:-KYPVWEW8HS1cfud16JX:b-bjgp28) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L888)):*
> ```cpp
>   std::shared_ptr<RigidBodyFrame<double>> frame =
>       MakeRigidBodyFrameFromUrdfNode(
>       *tree, *node, node, frame_name, model_instance_id);
> ```

Please indent this line by another four spaces.

---

*[drake/multibody/parser_urdf.cc, line 979 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWbRn6RX_yTSck48C:-KYPWbRn9rAM5yBLySte:b-bjgp28) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L979)):*
> ```cpp
>                                 const FloatingBaseType floating_base_type,
>                                 std::shared_ptr<RigidBodyFrame<double>>
>                                 weld_to_frame) {
> ```

Please indent this line by another four spaces.

---

*[drake/multibody/rigid_body_frame.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWxTZ7PWkFM7Wk-zn:-KYPWxTZ-IZcVe5BB2t1:b-xv8yh4) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/rigid_body_frame.h#L14)):*
> ```objc
> 
> template <typename T>
> class RigidBodyFrame {
> ```

Please document the types that are explicitly instantiated and thus available for use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-:-KYPXi3e9FDSA7yHGlYo:b4tnbx8)*

**Comment by amcastro-tri** [comment]
Review status: 23 of 29 files reviewed at latest revision, 15 unresolved discussions.

---

*[drake/bindings/python/pydrake/__init__.py, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPUqnOCsQJVvLOSM91:-KYPnlotB-OW3gOoKSM2:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/bindings/python/pydrake/__init__.py#L9)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I know this is a preexisting defect, but could you add the missing newline here?
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVqI91_sTXDZytwbx:-KYPnvfr6dW6ClcOIw5V:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/valkyrie_simulation.cc#L101)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line to match beginning of the parameter list on preceding line.
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/valkyrie_simulation.cc, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVvUT1BPqh1M8Mvp9:-KYPnw2P490_TyxKEU_O:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/valkyrie_simulation.cc#L103)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line to match beginning of the parameter list on preceding line.
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 92 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW1_-7ltOEukDXX6w:-KYPo74c37L9rhOk2zr3:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L92)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line to match beginning of the parameter list on preceding line.
</blockquote></details>

Done.

---

*[drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc, line 95 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW2MG6efNE4tR1gZh:-KYPo6DIDZVFIlLvvrXK:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/examples/Valkyrie/test/robot_state_encoder_decoder_test.cc#L95)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line to match beginning of the parameter list on preceding line.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 434 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPW5Uc5YEkvKYWgMYS:-KYPoGYX32GDmTlY08Fo:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L434)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line by four more spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 577 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWHKV510x7vUohoxg:-KYPoWIM2_EUwmsD4YOw:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L577)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, Consider using `auto frameA` here if possible.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 579 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWAcF5Dlaif0UTn-c:-KYPoWxM2Jhae4WwRorK:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L579)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line and the subsequent two lines by four additional spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 583 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWLoC8Vbipp_8VZil:-KYPoXtCBKnQw5MKsLwK:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L583)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, Consider using `auto frameB` here if possible.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 585 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWGka4btMqkeo_hoH:-KYPoYL4CB-huV60elrN:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_sdf.cc#L585)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line and the subsequent two lines by four additional spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_urdf.cc, line 864 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVaofB6uHQqOekFYl:-KYPojoY77n0NNpp77WS:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L864)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line by another four spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_urdf.cc, line 869 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVaBpB07tLOem5Mcw:-KYPokNP896XDjsv6G55:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L869)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line by another four spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_urdf.cc, line 888 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPVWEW2a9gCd8QWBKO:-KYPoo9CBa21l_7HXJNF:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L888)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line by another four spaces.
</blockquote></details>

Done.

---

*[drake/multibody/parser_urdf.cc, line 979 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWbRn6RX_yTSck48C:-KYPpCpF7g3NRBnci7-6:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/parser_urdf.cc#L979)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please indent this line by another four spaces.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_frame.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPWxTZ7PWkFM7Wk-zn:-KYPqxivByARN_hFsUoH:undefined) ([raw file](https://github.com/robotlocomotion/drake/blob/c23c975208d313cba0217fab5bc587cdde6681f9/drake/multibody/rigid_body_frame.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Please document the types that are explicitly instantiated and thus available for use.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406)*

**Comment by liangfok** [comment]
Done with second round of feature review. PTAL.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/parser_sdf.cc, line 579 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPrY2CCoFOF2zLvGj8:-KYPrY2CCsdZwAm-KAqk:bo1f4gp) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/parser_sdf.cc#L579)):*
> ```cpp
> 
>     auto frameA =
>         allocate_shared<RigidBodyFrame<double>>(
> ```

BTW, consider combining this line with the previous line.

---

*[drake/multibody/parser_sdf.cc, line 585 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPr_jlB-vUTp-UwFcA:-KYPr_jl-ATkS0tPPNz6:bo1f4gp) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/parser_sdf.cc#L585)):*
> ```cpp
> 
>     auto frameB =
>         allocate_shared<RigidBodyFrame<double>>(
> ```

BTW, consider combining this line with the previous line.

---

*[drake/multibody/rigid_body_frame.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPrxGzDnk9BCccBoeH:-KYPrxGz-I3zbZwL3L2J:bj1go0q) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/rigid_body_frame.h#L14)):*
> ```objc
> }
> 
> /// Multibody systems typically have distinguished frames of interest that
> ```

BTW, consider removing "distinguished".

---

*[drake/multibody/rigid_body_frame.h, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPs04RARHGJO1BITWZ:-KYPs04R8VQ5yRN7Lzkm:bqkuwk4) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/rigid_body_frame.h#L16)):*
> ```objc
> /// Multibody systems typically have distinguished frames of interest that
> /// need to be monitored. A frame is fully described by the body it is rigidly
> /// attaches to and the pose of this frame with respect to that body.
> ```

"attaches" should be "attached".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-:-KYPsSLi2mitP9ABs-nh:buu4kdb)*

**Comment by amcastro-tri** [comment]
Review status: 27 of 29 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/parser_sdf.cc, line 579 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPrY2CCoFOF2zLvGj8:-KYPt6OEDEe1yvf-aV2F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/parser_sdf.cc#L579)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider combining this line with the previous line.
</blockquote></details>

Done.

---

*[drake/multibody/parser_sdf.cc, line 585 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPr_jlB-vUTp-UwFcA:-KYPt6ni9W22Zjyf4UfX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/parser_sdf.cc#L585)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider combining this line with the previous line.
</blockquote></details>

Done.

---

*[drake/multibody/rigid_body_frame.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPrxGzDnk9BCccBoeH:-KYPtM8e5Ltm_vM8oekW:bktg3yb) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/rigid_body_frame.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider removing "distinguished".
</blockquote></details>

BTW, I actually like it if you dont mind

---

*[drake/multibody/rigid_body_frame.h, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-KYPs04RARHGJO1BITWZ:-KYPtLiRDvr26x0JKXgt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a026204deac2d743722e51535af99a5fdc19f1e3/drake/multibody/rigid_body_frame.h#L16)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

"attaches" should be "attached".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4406#-:-KYPtoHBAYUYk54fWquq:bnfp4nl)*

**Pull request merged**
