### PR TITLE
Convert an expression to a monomial

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5171)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kcyb_3zHslgLIVIh5OY:bboswjz)*

**Comment by soonho-tri** [comment]
check-point (will finish them in two hours).

high-level idea: How about having `Monomial(const Expression& e)` constructor instead of `ToMonomial` method?

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/monomial.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcydX5OfTGg2oSUCnZ4:-KcydX5OfTGg2oSUCnZ5:b-drgda8) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.cc#L119)):*
> ```cpp
>   if (is_one(e)) {
>   } else if (is_constant(e)) {
>     throw std::runtime_error(
> ```

META :`std::` in `std::runtime_error` is redundant since we have `using std::runtime_error` above.

---

*[drake/common/monomial.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcyeC4XAnezpXiw-LAv:-KcyeC4XAnezpXiw-LAw:b4i2cg) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.cc#L130)):*
> ```cpp
>     auto exponent_val = get_constant_value(exponent);
>     powers = ToMonomialPower(get_first_argument(e));
>     for (auto& p : powers) {
> ```

Please consider adding a comment explaining this step.

```
// pow(∏ᵢ x_i^{k_i}, exponent) => ∏ᵢ x_i^{k_i * exponent}
```

---

*[drake/common/monomial.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycQvgj3rt_ylpShT8:-KcycQvhSXmTfRieFgZH:bgc076w) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L208)):*
> ```objc
> 
> /**
>  * Convert an expression to a monomial, if the expression is written as
> ```

nit: convert -> converts

---

*[drake/common/monomial.h, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycSULFdLVQeG5w65z:-KcycSULFdLVQeG5w66-:b-hcj2mi) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L209)):*
> ```objc
> /**
>  * Convert an expression to a monomial, if the expression is written as
>  * ∏ᵢxᵢᵏᵢ, otherwise throws a runtime error.
> ```

Nice unicode :-)

Does this mean, `\prod_i x_i^{k_i}`? If so, the last `k_i` part doesn't render correct here..

---

*[drake/common/monomial.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycoYoLVJWfVm_ffgn:-KcycoYpniDt1Yzkrbw-:b-l8hr65) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L212)):*
> ```objc
>  * Note that we cannot handle the case that the expression contains
>  * addition/subtraction yet, namely x*(y+z)-x*z will not be converted to a
>  * monomial.
> ```

Could you add a TODO?

```
TODO(soonho): revisit this when we have Expression::Expand() method.
```

---

*[drake/common/monomial.h, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kcyd5fnRYwYXj7VcX5N:-Kcyd5fnRYwYXj7VcX5O:bp5fzut) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L213)):*
> ```objc
>  * addition/subtraction yet, namely x*(y+z)-x*z will not be converted to a
>  * monomial.
>  */
> ```

I think it's clearer if we specify the precondition, something like:
```
@pre is_polynomial(e) is true.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-KcyfEtp2GAu6temz5Wm:becy0il)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/common/monomial.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcydX5OfTGg2oSUCnZ4:-Kcyn8GMA_f9xRHrb8ve:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.cc#L119)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

META :`std::` in `std::runtime_error` is redundant since we have `using std::runtime_error` above.
</blockquote></details>

Done.

---

*[drake/common/monomial.cc, line 130 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcyeC4XAnezpXiw-LAv:-Kcyn-ldAhl4vCMqhxg_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.cc#L130)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Please consider adding a comment explaining this step.

```
// pow(∏ᵢ x_i^{k_i}, exponent) => ∏ᵢ x_i^{k_i * exponent}
```
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 208 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycQvgj3rt_ylpShT8:-Kcymhi8cJSRiidoUk-Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L208)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit: convert -> converts
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycSULFdLVQeG5w65z:-KcymcRQzet8ZMbpkc5Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L209)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Nice unicode :-)

Does this mean, `\prod_i x_i^{k_i}`? If so, the last `k_i` part doesn't render correct here..
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 212 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KcycoYoLVJWfVm_ffgn:-Kcym_szMZ6-6h_vdUnd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L212)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you add a TODO?

```
TODO(soonho): revisit this when we have Expression::Expand() method.
```
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 213 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kcyd5fnRYwYXj7VcX5N:-Kcym_CMGWjjq8lnP7Uv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c98cc6a21fb82fdad9ef7ac9c8388af86ea3779/drake/common/monomial.h#L213)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it's clearer if we specify the precondition, something like:
```
@pre is_polynomial(e) is true.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171)*

**Comment by soonho-tri** [comment]
> high-level idea: How about having Monomial(const Expression& e) constructor instead of ToMonomial method?

Please ignore this (as we found the problem in #cpp channel).

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/monomial_test.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KczaeH0V0YnztgtXAxL:-KczaeH0V0YnztgtXAxM:b-a8c75i) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L326)):*
> ```cpp
>   EXPECT_EQ(internal::ToMonomial(1), expected);
>   EXPECT_EQ(internal::ToMonomial(pow(x_, 0)), expected);
>   EXPECT_THROW(internal::ToMonomial(2), std::exception);
> ```

I think it's better to have `std::runtime_error` instead of `std::exception`).

---

*[drake/common/test/monomial_test.cc, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kczu5HdiSDcaKIjOXQy:-Kczu5HdiSDcaKIjOXQz:b-f0ktuf) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L327)):*
> ```cpp
>   EXPECT_EQ(internal::ToMonomial(pow(x_, 0)), expected);
>   EXPECT_THROW(internal::ToMonomial(2), std::exception);
> }
> ```

Let's have two more exception cases to increase test coverage:

```
  EXPECT_THROW(internal::ToMonomial(x_ + 2), std::runtime_error);
  EXPECT_THROW(internal::ToMonomial(2 * x_), std::runtime_error);
```

---

*[drake/common/test/monomial_test.cc, line 359 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KczuFiCFErPfVW1WvqH:-KczuFiCFErPfVW1WvqI:byxtjeg) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L359)):*
> ```cpp
>   EXPECT_EQ(internal::ToMonomial(pow(x_, 3) * y_), expected);
>   EXPECT_EQ(internal::ToMonomial(pow(x_, 2) * y_ * x_), expected);
> }
> ```

Let's have one more test here to increase coverage:

```c++
TEST_F(MonomialTest, ToMonomial5) {
  internal::Monomial expected{{{var_x_.get_id(), 4}, {var_y_.get_id(), 4}}};
  EXPECT_EQ(internal::ToMonomial(pow(x_ * y_, 2) * pow(x_, 2) * pow(y_, 2)),
            expected);
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kcz_fkxLTsDIefq7-ty:bkzmxf9)*

**Comment by soonho-tri** [comment]
:lgtm: (aside comments)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-KczueUGtmeJ47GP5nWj:bog1ams)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/monomial_test.cc, line 326 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KczaeH0V0YnztgtXAxL:-Kd--cQlyUtl3I6ber8W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L326)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think it's better to have `std::runtime_error` instead of `std::exception`).
</blockquote></details>

Done.

---

*[drake/common/test/monomial_test.cc, line 327 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kczu5HdiSDcaKIjOXQy:-Kd--cvPdLvEweQPUeQB:b-yh16lj) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L327)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Let's have two more exception cases to increase test coverage:

```
  EXPECT_THROW(internal::ToMonomial(x_ + 2), std::runtime_error);
  EXPECT_THROW(internal::ToMonomial(2 * x_), std::runtime_error);
```
</blockquote></details>

Done. Good call!

---

*[drake/common/test/monomial_test.cc, line 359 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-KczuFiCFErPfVW1WvqH:-Kd-0th-yMrA5N-gT4Mz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18f1581930e4d09c2dbc3a3979eb10cdb546685c/drake/common/test/monomial_test.cc#L359)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Let's have one more test here to increase coverage:

```c++
TEST_F(MonomialTest, ToMonomial5) {
  internal::Monomial expected{{{var_x_.get_id(), 4}, {var_y_.get_id(), 4}}};
  EXPECT_EQ(internal::ToMonomial(pow(x_ * y_, 2) * pow(x_, 2) * pow(y_, 2)),
            expected);
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kd-1D0-BuomgKI8yjyO:bpk00vl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging)

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 117 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kd1MzZEEJI_04N8OHsv:-Kd1MzZF2Z9VtTPZ39uK:bssk1h6) ([raw file](https://github.com/robotlocomotion/drake/blob/a7065f6963d712e4e0145d6877bf2fde562c5338/drake/common/monomial.cc#L117)):*
> ```cpp
>   DRAKE_DEMAND(e.is_polynomial());
>   map<Variable::Id, int> powers;
>   if (is_one(e)) {
> ```

BTW maybe comment that this block was deliberately left empty

---

*[drake/common/monomial.cc, line 119 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kd1N34dFQQOt5NQtpde:-Kd1N34dFQQOt5NQtpdf:b-6gmjdm) ([raw file](https://github.com/robotlocomotion/drake/blob/a7065f6963d712e4e0145d6877bf2fde562c5338/drake/common/monomial.cc#L119)):*
> ```cpp
>   if (is_one(e)) {
>   } else if (is_constant(e)) {
>     throw runtime_error("A constant not equalto to 1, this is not a monomial.");
> ```

typo "equal to"?  (or is this deliberate to refer to a comparison function or something?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kd1MfgWwcCG-TYCll8F:b-up35mr)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/monomial.cc, line 117 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kd1MzZEEJI_04N8OHsv:-Kd2Ucte5LrNxXTRVtB1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a7065f6963d712e4e0145d6877bf2fde562c5338/drake/common/monomial.cc#L117)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW maybe comment that this block was deliberately left empty
</blockquote></details>

Done.

---

*[drake/common/monomial.cc, line 119 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-Kd1N34dFQQOt5NQtpde:-Kd2UXeQJXcjL9fzuAc1:b-9vnikj) ([raw file](https://github.com/robotlocomotion/drake/blob/a7065f6963d712e4e0145d6877bf2fde562c5338/drake/common/monomial.cc#L119)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

typo "equal to"?  (or is this deliberate to refer to a comparison function or something?)
</blockquote></details>

Done. it is a typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kd2ZDYIXLU9k0-g5ngd:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5171#-:-Kd2i2brMa3-fnyi6blD:b-l70wzf)*

**Pull request merged**
