### PR TITLE
[panda_arm] Upstream acc. limits and collision filtering from Anzu

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates Anzu PR 10635

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@AdityaBhat-TRI and +@sammy-tri for review, please

\cc @calderpg-tri

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-:-NYyAVxs90IMrKlEnC_L:b-dzyvrb)* status: LGTM missing from assignees AdityaBhat-TRI,sammy-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/franka_description/urdf/panda_arm_hand.urdf` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyBj-n9THuP4ER-OGH:-NYyBj-n9THuP4ER-OGI:b-anzri0) ([raw file](https://github.com/RobotLocomotion/drake/blob/895256148d156b51f3d46ce0c4284e5845409770/manipulation/models/franka_description/urdf/panda_arm_hand.urdf#L161)):*
> ```XML
>     <child link="panda_link1"/>
>     <axis xyz="0 0 1"/>
>     <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750" drake:acceleration="15.0"/>
> ```

Can you add the source for this number in a readme? I was looking at the emika documentation and found these values : https://frankaemika.github.io/docs/control_parameters.html

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)* status: 1 unresolved discussion, LGTM missing from assignees AdityaBhat-TRI,sammy-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyBL3ZDrbv5icTigpl:-NYyMx2g8RwgFUoHOFkn:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW

The README.md in this directory promises a changelog (i.e., inventory) of all of the edits we've made versus upstream.  It should be updated to mention these edits its our log of Drake-specific changes.

That goes for both the new limits as well as the new collision filters.
</blockquote></details>

Done.

___
___
*[`manipulation/models/franka_description/urdf/panda_arm_hand.urdf` line 161 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyBj-n9THuP4ER-OGH:-NYyMwBA2vNbn0Tp81Nf:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/895256148d156b51f3d46ce0c4284e5845409770/manipulation/models/franka_description/urdf/panda_arm_hand.urdf#L161)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

Can you add the source for this number in a readme? I was looking at the emika documentation and found these values : https://frankaemika.github.io/docs/control_parameters.html
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)* status: 1 unresolved discussion, LGTM missing from assignees AdityaBhat-TRI,sammy-tri(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/franka_description/README.md` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyOr-w9DfdWK1yyFkF:-NYyOr-w9DfdWK1yyFkG:bd2x32f) ([raw file](https://github.com/RobotLocomotion/drake/blob/b15a3decaf33dd3f2c9a7deb676b006e67b1c31a/manipulation/models/franka_description/README.md#L31)):*
> ```Markdown
> https://frankaemika.github.io/docs/control_parameters.html#limits-for-panda
> 
> |Axis data   | acceleration limit (m/s^2)|
> ```

rad/s^2 ?

**Comment by AdityaBhat-TRI** [comment]
*[`manipulation/models/franka_description/README.md` line 39 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyPBKS5ir0oxOkGcSX:-NYyPBKS5ir0oxOkGcSY:bwqso3n) ([raw file](https://github.com/RobotLocomotion/drake/blob/b15a3decaf33dd3f2c9a7deb676b006e67b1c31a/manipulation/models/franka_description/README.md#L39)):*
> ```Markdown
> |Axis 5 (A5) |15                         |
> |Axis 6 (A6) |20                         |
> |Axis 7 (A7) |20                         |
> ```

It may be worth adding a test case to verify that the values for accelerations are the same across the urdfs.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)* status: 2 unresolved discussions, LGTM missing from assignees AdityaBhat-TRI,sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

___
*[`manipulation/models/franka_description/README.md` line 31 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyOr-w9DfdWK1yyFkF:-NYyUueT8q2ArHpTOgCS:b-19eps3) ([raw file](https://github.com/RobotLocomotion/drake/blob/b15a3decaf33dd3f2c9a7deb676b006e67b1c31a/manipulation/models/franka_description/README.md#L31)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

rad/s^2 ?
</blockquote></details>

Done. :facepalm: x 1000
___
*[`manipulation/models/franka_description/README.md` line 39 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-NYyPBKS5ir0oxOkGcSX:-NYyUwDD2eeC6W4ysMst:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/b15a3decaf33dd3f2c9a7deb676b006e67b1c31a/manipulation/models/franka_description/README.md#L39)):*
<details><summary><i>Previously, AdityaBhat-TRI (Aditya Bhat) wrote…</i></summary><blockquote>

It may be worth adding a test case to verify that the values for accelerations are the same across the urdfs.
</blockquote></details>

Done.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689#-:-NYyr9Rh6I5TPx-LwN8b:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee AdityaBhat-TRI, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)* status: 2 unresolved discussions, LGTM missing from assignee AdityaBhat-TRI, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Comment by AdityaBhat-TRI** [comment]
:lgtm:

**Review by AdityaBhat-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19689)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @EricCousineau-TRI)

**Pull request merged**
