### PR TITLE
[setup] Fail fast if invoked with sudo when already root

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17284)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: do not review) 
FYI @edrumwri @jwnimmer-tri If you like this, I can herd it through at low priority.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17284#-:-N35g_TICXdJRB7GA6Hg:b4xla9h)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17284#-:-N35iQv77U2BRj7YjcHL:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`setup/ubuntu/install_prereqs.sh` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17284#-N35hSjeDZA-x8vCC-pI:-N35hSjfBoTTWuMrPt4r:b-h0kpax) ([raw file](https://github.com/robotlocomotion/drake/blob/b5df2c99eb96c4b86f1a4ac0a5edeba9a79633b0/setup/ubuntu/install_prereqs.sh#L20)):*
> ```Shell
> # environments.
> if [[ -n "${SUDO_USER:+D}" && $(id -u ${SUDO_USER}) -eq 0 ]]; then
>   echo 'This script must NOT be run through sudo as root' >&2
> ```

nit I don't find this message particularly good.  Here's my take on a new one:

"It appears that this script is running under sudo, but it was the root user who ran sudo. That use is not supported; when already running as root, do not use sudo when calling this script."
___
*[`setup/ubuntu/install_prereqs.sh` line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17284#-N35hJd-1BNJt47NVZN4:-N35hJd-1BNJt47NVZN5:b-h7ru2p) ([raw file](https://github.com/robotlocomotion/drake/blob/b5df2c99eb96c4b86f1a4ac0a5edeba9a79633b0/setup/ubuntu/install_prereqs.sh#L21)):*
> ```Shell
> if [[ -n "${SUDO_USER:+D}" && $(id -u ${SUDO_USER}) -eq 0 ]]; then
>   echo 'This script must NOT be run through sudo as root' >&2
>   exit 1
> ```

nit We should probably do the new code _before_ adding the `at_exit` trap -- the extra line number business is not useful when we're already printing a more specific diagnostics.

**Review by rpoyner-tri — COMMENTED** [review]
+@jwnimmer-tri for both reviews, if you like. +(status: single reviewer ok) -(status: do not review) +(release notes: yes) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17284#-:-N35tUn60fut9K22hFHQ:b-vefw43)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17284)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Pull request merged**
