### PR TITLE
Multiple arms, grippers, and boxes in IiwaPlantWithStateEstimator.

### PR DESCRIPTION
**Pull request by avalenzu**
This PR updates the `IiwaPlantWithStateEstimator` class to handle multiple arms and objects.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7346)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@naveenoid for feature review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxP-hSW1DEM2uoZDw3N:b-ijjxgm)*

**Comment by naveenoid** [comment]
Do you see any use for maintaining a string name for each of th models instead of just integer? For instance, it might be useful to refer to "IIWA_Right" instead of "IIWA_2".. I will leave it to you though. I suppose it comes down to demo diagram hooking up complexity.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP33YmjgblnCBLcmUd:-KxP33YnOy8AY0aeZRcw:bg8i1f1) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L23)):*
> ```cpp
> IiwaAndWsgPlantWithStateEstimator<T>::IiwaAndWsgPlantWithStateEstimator(
>     std::unique_ptr<systems::RigidBodyPlant<T>> combined_plant,
>     const std::vector<manipulation::util::ModelInstanceInfo<T>>& iiwa_info,
> ```

BTW: consider pluralizing these variable names to reflect their multi-dimensionality, for instance "robots_info" or "wsg_grippers_info". Also box_info has bothered me for a while, maybe we can uniformly use "target" instead of "box" when we talk about manipulation targets?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP3fP7cEMlG2XEJew1:-KxP3fP7cEMlG2XEJew2:b2ln43h) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L35)):*
> suffix
BTW : consider moving this declaration to right before where you use it below.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP4L8MpM22kZNl_yQr:-KxP4L8MpM22kZNl_yQs:b10muad) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L39)):*
> ```objc
>  public:
>   /// Constructs the IiwaAndWsgPlantWithStateEstimator.  `combined_plant` :  a
>   /// `RigidBodyPlant` that is assumed to be generated containing a Kuka IIWA
> ```

BTW: this would be "a Kuka IIWA" -> "atleast one Kuka IIWA" with this PR's change wouldnt it?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP4rDMb-aiOqlXBBCj:-KxP4rDMb-aiOqlXBBCk:bjdvfml) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L43)):*
> ```objc
>   /// `iiwa_info`, `wsg_info`, and `box_info` are the
>   /// `manipulation::util::ModelInstanceInfo` objects corresponding to the Kuka
>   /// IIWA, Schunk WSG and the box object respectively.
> ```

Pluralization needed on some of the things talked about in this comment block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxP5EsPKkL3RDFktoT3:b-kgzwcq)*

**Comment by avalenzu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxT33bzPEnNnuJqlrKZ:-KxT33bzPEnNnuJqlrK_:b-xs2plv) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L124)):*
> ```objc
>   std::vector<int> output_port_box_robot_state_t_;
>   int output_port_plant_state_{-1};
>   int output_port_contact_results_t_{-1};
> ```

s/contact_results_t/contact_results. This is not an LCM message output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346)*

**Comment by avalenzu** [comment]
The string names become cumbersome when you get past "right" and "left." I'd rather stick with numbering.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP33YmjgblnCBLcmUd:-KxTLC1il0Ng8RFCxaaQ:byfm44q) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L23)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: consider pluralizing these variable names to reflect their multi-dimensionality, for instance "robots_info" or "wsg_grippers_info". Also box_info has bothered me for a while, maybe we can uniformly use "target" instead of "box" when we talk about manipulation targets?
</blockquote></details>

I've changed these to *_instances to match the usage in `BuildCombinedPlant()` in `monolithic_pick_and_place_demo`. I've also replaced "box" with "object" throughout. I don't want to use target because there can be arbitrarily many of these objects and only one of them is the target in the pick-and-place demo.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP3fP7cEMlG2XEJew1:-KxTMIqolepGxejuAbZg:b-j0wyfh) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L35)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

> suffix
BTW : consider moving this declaration to right before where you use it below.
</blockquote></details>

I'd like to leave this where it is because it's used both in the controller setup and the state estimator setup. I think it's cleaner to have it defined before either of those sections rather than defining it in the first one.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP4L8MpM22kZNl_yQr:-KxTLizaP7wqhzdgODdq:bnvdtrv) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L39)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: this would be "a Kuka IIWA" -> "atleast one Kuka IIWA" with this PR's change wouldnt it?
</blockquote></details>

I've re-written this comment. PTAL.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxP4rDMb-aiOqlXBBCj:-KxTLuRcfuSiZcpnle78:bnvdtrv) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L43)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Pluralization needed on some of the things talked about in this comment block.
</blockquote></details>

I've re-written this comment. PTAL.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 124 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxT33bzPEnNnuJqlrKZ:-KxTM2PhOC6l-j1Nhi2A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/86d60d5496a2dbc48aeae9ca600572b8aac23771/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L124)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/contact_results_t/contact_results. This is not an LCM message output.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxT4Io7ZFe8OQ8jNnDg:b-wy79k4)*

**Comment by avalenzu** [comment]
@naveenoid, I've addressed the comments from your first pass. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxTNqXdZ1Kh-axMePvk:bjif128)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxTQ0_7_jCNs7h3Sblr:bnfp4nl)*

**Comment by avalenzu** [comment]
+@sherm1 for platform review.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxTU8P8RSo6sAwV8Uqf:bfvx2sg)*

**Comment by sherm1** [comment]
Platform pass: looks good with a few minor BTWs. I didn't see a unit test that checks that the multiple-arm bookkeeping works. Is there one?

---

Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 293 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUj9BgSqh-IB6AHKqU:-KxUj9BgSqh-IB6AHKqV:b6vbmgb) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L293)):*
> ```cpp
>           iiwa_base, place_locations);
> 
>   builder.Connect(plant->get_output_port_object_robot_state_msg(),
> ```

BTW above you changed "box" to "target" everywhere. Here "box" became "object". Should the method also use "target" rather than "object" for consistency? Or should "object" be used above rather than "target"? Or is there a good reason for these to be distinct?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 121 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUl6jsgGnnXw7crtb_:-KxUl6jsgGnnXw7crtba:b-g7pyjp) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L121)):*
> ```cpp
>         base_builder->template AddSystem<OracularStateEstimation<T>>(
>             *objects_.back());
>     object_state_est->set_name("OracularStateEstimationBoxState" + suffix);
> ```

BTW is this misnamed now (still says "box")?

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUjuSaioC5pmaZ_DWA:-KxUjuSaioC5pmaZ_DWB:bvflhgc) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L26)):*
> ```objc
> /// resulting diagram exposes an input port for the desired state and
> /// acceleration of each IIWA arm as well as the actuator command for each WSG
> /// gripper. It expose an output port for the state of each IIWA arm and WSG
> ```

BTW expose -> exposes

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUk81I8WWD3sguASkX:-KxUk81I8WWD3sguASkY:b-hk0f3g) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L39)):*
> ```objc
>  public:
>   /// Constructs the IiwaAndWsgPlantWithStateEstimator.
>   /// @param combined_plant` a systems::RigidBodyPlant containing some number of
> ```

BTW spurious back tick

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUkQVsd-WfauD1dQ5R:-KxUkQVsd-WfauD1dQ5S:b-hk0f3g) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L60)):*
> ```objc
>   /// Constructs an IiwaAndWsgPlantWithStateEstimator for a RigidBodyPlant @p
>   /// combined_plant that contains a single Kuka IIWA, Schunk WSG, and object.
>   /// @param combined_plant` a `RigidBodyPlant` that is assumed to be generated
> ```

BTW spurious back tick

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxUlsk7ZQJJxvltAugg:b-1kmvdd)*

**Comment by avalenzu** [comment]
@sherm1, there is now! PTAL.

---

Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc, line 293 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUj9BgSqh-IB6AHKqU:-KxhkiubgAX49M-4pduB:b-f7dd1w) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc#L293)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW above you changed "box" to "target" everywhere. Here "box" became "object". Should the method also use "target" rather than "object" for consistency? Or should "object" be used above rather than "target"? Or is there a good reason for these to be distinct?
</blockquote></details>

There are many "objects" in the scenario. One of them is the "target." The plant doesn't know that there's a target. It just knows that there are objects. The no-arguments syntax for `get_output_port_object_robot_state_msg()` returns the port for the first object.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc, line 121 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUl6jsgGnnXw7crtb_:-KxhlFoYaPUMNQfsAvV9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc#L121)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is this misnamed now (still says "box")?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 26 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUjuSaioC5pmaZ_DWA:-KxhlKDEj14k7Ip0LTj2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW expose -> exposes
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 39 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUk81I8WWD3sguASkX:-KxhlR5D0aYFGFuYpjGO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L39)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW spurious back tick
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h, line 60 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-KxUkQVsd-WfauD1dQ5R:-KxhlROCB0ElgG7EJfQD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3d8168c5961fcefb7ecf28333b1b3045ec23348b/drake/examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h#L60)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW spurious back tick
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-KxnNuAi_RxW14VCQz-z:brpfcof)*

**Comment by sherm1** [comment]
Thanks, @avalenzu! Platform :lgtm:.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7346#-:-Kxo_pKcIcjG5pFPMLP8:b-c9b3je)*

**Pull request merged**
