### PR TITLE
[tools] Add C++ codegen to lcm_gen for variable-sized structs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This commit introduces lcm_gen support for strings and arrays, as well as a (currently private) command-line main program.

This does not yet switch Drake to use the new tool by default.

Towards #20761.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for feature review, please.

**Comment by jwnimmer-tri** [comment]
(There was one missed line of kcov.  I pushed the missing test just now.)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: 10 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpysTgl-UTRuQ2DHFdS:-NpysTgl-UTRuQ2DHFdT:bb0umj1) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
> ```Python
>   // passed with `_input` as vector-like container and `_dims...` as the list
>   // of (multi-dimensional) vector sizes, e.g., `int8_t image[6][4]` would
>   // be called like `_encode_field(image.at(0), &cursor, end, 6, 4)`.
> ```

nit:  This does not indicate the dimension packing order.  Consider documenting that the last dimension is the most tightly packed, C-style.
___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpywElt8cuELyIbmxVU:-NpywElt8cuELyIbmxVV:b-kpwb5s) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
> ```Python
>   // passed with `_input` as vector-like container and `_dims...` as the list
>   // of (multi-dimensional) vector sizes, e.g., `int8_t image[6][4]` would
>   // be called like `_encode_field(image.at(0), &cursor, end, 6, 4)`.
> ```

This seems correct but... why?
What is the advantage that we get from doing this with varargs rather than just a `optional<vector<int>>=nullopt` of the dimensions, e.g. `_encode_field(..., {6, 4})`?  I don't think we're getting better runtime efficiency from the templating since the inner loop recursion is the same either way (maybe you're picking up some funroll inlining leverage?  I don't think any -O is going to get you the cheap memcpy...?).  And the readability of this code seems worse, as probably (I haven't checked) are the error messages if the codegen ever burps from python/C++ numerics shear.
___
*[`tools/lcm_gen/__init__.py` line 504 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpyuwkYBH4bjdjTte5m:-NpyuwkYBH4bjdjTte5n:b-sktp7c) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L504)):*
> ```Python
>         const bool ok = [&](int /* _dim */, auto&&... _child_dims) {
>           return _encode_field(_child, _cursor, _end, _child_dims...);
>         }(_dims...);
> ```

BTW:  TIL.  I hadn't seen this varargs-destructuring lambda trick before.
___
*[`tools/lcm_gen/__init__.py` line 697 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npyyd1zENB6Jz-aRMUQ:-Npyyd2-AM3X2fcDb1nV:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L697)):*
> ```Python
>             return f"_result += {known_encoded_size};  // {field.name}\n"
> 
>         # For varible-size elements, we need to loop in case of arrays.
> ```

typo



_Suggestion:_
```Python
 variable
```
___
*[`tools/lcm_gen/__init__.py` line 865 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpyzYHn5LZgabNj30t5:-NpyzYHn5LZgabNj30t6:bob7t00) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L865)):*
> ```Python
> 
> def main():
>     parser = argparse.ArgumentParser()
> ```

minor:  Consider help text?



_Suggestion:_
```Python
    parser = argparse.ArgumentParser(description==__doc__)
```
___
*[`tools/lcm_gen/__init__.py` line 874 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz21jX3jOJ791oiZcj:-Npz21jX3jOJ791oiZck:bve01f6) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L874)):*
> ```Python
>     args = parser.parse_args()
> 
>     real_cwd = os.environ.get("BUILD_WORKING_DIRECTORY")
> ```

minor:  Comment this so that readers don't need to look up that this envvar is a bazel thing?



_Suggestion:_
```Python
    # If this is inside a `bazel build`, use bazel's working directory.
    real_cwd = os.environ.get("BUILD_WORKING_DIRECTORY")
```
___
*[`tools/lcm_gen/__init__.py` line 884 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz2_tA1297QSllUheV:-Npz2_tA1297QSllUheW:b-9ggyrt) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L884)):*
> ```Python
>             generator = CppGen(struct=struct)
>             content = generator.generate()
>             path = args.outdir / f"{struct.typ.name}.h"
> ```

It seems important to document that the output files will be named by their types, not by the input file names.

This also seems like it would prevent some automation of bazel rules, since you can't know the outputs of a rule from its inputs without file parsing, so I wonder if it's a good idea at all.

(This also means the generated files will not follow our snake_case conventions for filenames, but instead our CamelCase conventions for type names.  But we don't generally follow our conventions for LCM so whatever)
___
*[`tools/lcm_gen/__init__.py` line 885 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz3TG61zKJk0WvCKjw:-Npz3TG74eBunrdhnhdH:bt8nycp) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L885)):*
> ```Python
>             content = generator.generate()
>             path = args.outdir / f"{struct.typ.name}.h"
>             path.write_text(content, encoding="utf-8")
> ```

minor:  At _very low confidence_ I believe that this may be incorrect for MacOS.
I believe that MacOS HFS+ requires that filenames be not merely utf-8 but fully decomposed utf-8.  As such, I believe you may need to `unicodedata.normalize('NFD', path)` here.

Of course anybody naming their LCM types with 8859-1 diacritics is making their own bed, so feel free to disregard.



_Code quote:_
```Python
encoding="utf-8"
```
___
*[`tools/lcm_gen/__init__.py` line 888 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz46OI1c0XoZsT7qi4:-Npz46OI1c0XoZsT7qi5:b-idrjrj) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L888)):*
> ```Python
>         except Exception as e:
>             print(e)
>             returncode = 1
> ```

minor:  AIUI you're redirecting the error text to stdout instead of stderr and accomplishing nothing else (since python uncaught exception is already returncode 1).  I would suggest simply deleting this block -- it seems worse than just letting the exception flow through.
___
*[`tools/lcm_gen/test/functional_test.cc` line 134 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpyvbrmAqf4yxygSXGr:-NpyvbrmAqf4yxygSXGs:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/test/functional_test.cc#L134)):*
> ```cpp
> }
> 
> // With our new lcm-gen, partiall-fixed-size arrays are typed as std::array so
> ```

typo?



_Suggestion:_
```cpp
partially fixed-size
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: 3 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpywElt8cuELyIbmxVU:-NpzC9bx18lOwIi73OyV:b301098) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This seems correct but... why?
What is the advantage that we get from doing this with varargs rather than just a `optional<vector<int>>=nullopt` of the dimensions, e.g. `_encode_field(..., {6, 4})`?  I don't think we're getting better runtime efficiency from the templating since the inner loop recursion is the same either way (maybe you're picking up some funroll inlining leverage?  I don't think any -O is going to get you the cheap memcpy...?).  And the readability of this code seems worse, as probably (I haven't checked) are the error messages if the codegen ever burps from python/C++ numerics shear.
</blockquote></details>

Working

I will look into this.  My recollection is that yes, the compiler fuses the whole thing at compile time and emits a large-block memcpy, and that doing so was important.  (It might only be relevant after my next PR, which hoists the bounds checking out of the inner loops.)
___
*[`tools/lcm_gen/__init__.py` line 865 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpyzYHn5LZgabNj30t5:-Npz8fd9CVQnglLCNol9:b-ao9son) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L865)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider help text?
</blockquote></details>

Good idea.  The whole thing was a bit too long, so I'm only printing part of it in `--help`.
___
*[`tools/lcm_gen/__init__.py` line 884 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz2_tA1297QSllUheV:-NpzBKqhDVy_5So98u7A:btxtq7k) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L884)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

It seems important to document that the output files will be named by their types, not by the input file names.

This also seems like it would prevent some automation of bazel rules, since you can't know the outputs of a rule from its inputs without file parsing, so I wonder if it's a good idea at all.

(This also means the generated files will not follow our snake_case conventions for filenames, but instead our CamelCase conventions for type names.  But we don't generally follow our conventions for LCM so whatever)
</blockquote></details>

The `foo.lcm` file containing `struct foo` are **required** by upstream to be identical.  See https://lcm-proj.github.io/lcm/content/lcm-type-ref.html at _"This declaration must appear in a file named `temperature_t.lcm`."_  That's why the Bazel rules don't have any trouble.

LCM types are always snake, never Camel.  This is a nice reminder that their POD values are uninitialized and so always need `lcmt_foo bar{};` in our local variable declarations to zero them out explicitly (not `lcmt_foo bar;`).

In terms of the output filename, throughout the whole LCM ecosystem it _must_ match the struct name exactly, so that different projects' generated LCM messages can `#include` each other.  I've added some comments to help communicate this.
___
*[`tools/lcm_gen/__init__.py` line 885 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz3TG61zKJk0WvCKjw:-Npz9SMM0iRF4EC3Okkz:b92mpeq) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L885)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  At _very low confidence_ I believe that this may be incorrect for MacOS.
I believe that MacOS HFS+ requires that filenames be not merely utf-8 but fully decomposed utf-8.  As such, I believe you may need to `unicodedata.normalize('NFD', path)` here.

Of course anybody naming their LCM types with 8859-1 diacritics is making their own bed, so feel free to disregard.
</blockquote></details>

Yeah, I'm going to wait to deal with non-ASCII message names until we hear about a need.

**Review by ggould-tri — COMMENTED** [review]
Checkpoint.  Giving this one more readthrough after lunch to make sure it's clear in my mind.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-:-NpzJvDL5CbBdcrlu2Rs:b-duvfqe)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpywElt8cuELyIbmxVU:-NpzJMfvDYeRiW_3p-9k:b-fq9cfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I will look into this.  My recollection is that yes, the compiler fuses the whole thing at compile time and emits a large-block memcpy, and that doing so was important.  (It might only be relevant after my next PR, which hoists the bounds checking out of the inner loops.)
</blockquote></details>

Ah, I can see that.
In any case a comment explaining why we're doing this would help.  It all reads as a little bit too clever.
___
*[`tools/lcm_gen/__init__.py` line 884 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz2_tA1297QSllUheV:-NpzJb917Q-MxGpDxrRh:b-5hynew) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L884)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `foo.lcm` file containing `struct foo` are **required** by upstream to be identical.  See https://lcm-proj.github.io/lcm/content/lcm-type-ref.html at _"This declaration must appear in a file named `temperature_t.lcm`."_  That's why the Bazel rules don't have any trouble.

LCM types are always snake, never Camel.  This is a nice reminder that their POD values are uninitialized and so always need `lcmt_foo bar{};` in our local variable declarations to zero them out explicitly (not `lcmt_foo bar;`).

In terms of the output filename, throughout the whole LCM ecosystem it _must_ match the struct name exactly, so that different projects' generated LCM messages can `#include` each other.  I've added some comments to help communicate this.
</blockquote></details>

Ah, thanks!
___
*[`tools/lcm_gen/__init__.py` line 885 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz3TG61zKJk0WvCKjw:-NpzJe6F6OCB6_mBQZWt:b-buo79m) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L885)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yeah, I'm going to wait to deal with non-ASCII message names until we hear about a need.
</blockquote></details>

Possibly indirecting it through os.path would make it python's problem?  Regardless, no defect for now.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-:-NpzQ9e_EI46HPP0oZQc:bnfp4nl)* status: 5 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 486 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpzO67ECYOY81PadP_T:-NpzO67ECYOY81PadP_U:b-2z204m) ([raw file](https://github.com/RobotLocomotion/drake/blob/58b4476cd8092ced8e10ed9b1c46fd21f391a759/tools/lcm_gen/__init__.py#L486)):*
> ```Python
>         const int32_t _size = _input.size() + 1;
>         const bool ok = (_input.size() < INT32_MAX) &&
>                         (*_cursor + 4 + _size <= _end) &&
> ```

nit: consider de-magic'ing this number.



_Suggestion:_
```Python
sizeof(_size)
```
___
*[`tools/lcm_gen/__init__.py` line 539 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpzOn_j7Fc1GuMqmXk3:-NpzOn_j7Fc1GuMqmXk4:b-e2p0sp) ([raw file](https://github.com/RobotLocomotion/drake/blob/58b4476cd8092ced8e10ed9b1c46fd21f391a759/tools/lcm_gen/__init__.py#L539)):*
> ```Python
>         // String output.
>         int32_t _size{};
>         const bool ok = (*_cursor + 4 <= _end) &&
> ```

nit: as above, consider de-magic-numbering



_Suggestion:_
```Python
sizeof(_size)
```
___
*[`tools/lcm_gen/__init__.py` line 711 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpzRWbK4JDUyfO2YtBX:-NpzRWbK4JDUyfO2YtBY:b-8mpcgh) ([raw file](https://github.com/RobotLocomotion/drake/blob/58b4476cd8092ced8e10ed9b1c46fd21f391a759/tools/lcm_gen/__init__.py#L711)):*
> ```Python
>             pad += " " * 2
>         if field.typ == PrimitiveType.string:
>             content += f"{pad}_result += 4 + {var}.size() + 1;\n"
> ```

BTW:  A more questionable candidate for de-magic-numbering



_Suggestion:_
```Python
(sizeof {var}.size())
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 885 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Npz3TG61zKJk0WvCKjw:-NpzU6Hv8pWcApqiCRvg:bq8767l) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L885)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Possibly indirecting it through os.path would make it python's problem?  Regardless, no defect for now.
</blockquote></details>

`path` is a `pathlib.Path` which is Python's preferred spelling of `os.path` now.  The `encoding` argument here is the encoding for the content, not the filename.
___
*[`tools/lcm_gen/__init__.py` line 539 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpzOn_j7Fc1GuMqmXk3:-NpzTbeBDsRlzEMymbOe:b-nl0v9y) ([raw file](https://github.com/RobotLocomotion/drake/blob/58b4476cd8092ced8e10ed9b1c46fd21f391a759/tools/lcm_gen/__init__.py#L539)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit: as above, consider de-magic-numbering
</blockquote></details>

Done.

In this case, the check was redundant because `_decode_field` does exactly the same thing.  (In a future refactor I hope to hoist the size-check, but for this version it is clearer to omit this.)
___
*[`tools/lcm_gen/__init__.py` line 711 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpzRWbK4JDUyfO2YtBX:-NpzUWlDCDOuigs9kJdS:b-pxv1po) ([raw file](https://github.com/RobotLocomotion/drake/blob/58b4476cd8092ced8e10ed9b1c46fd21f391a759/tools/lcm_gen/__init__.py#L711)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:  A more questionable candidate for de-magic-numbering
</blockquote></details>

The `string::size()` is 8 bytes, not 4, so that particular would be wrong.  I split the difference and used a slightly less magical name now.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpywElt8cuELyIbmxVU:-Nq-6t1cA3Ge5FT4dDE8:b-s1st9e) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Ah, I can see that.
In any case a comment explaining why we're doing this would help.  It all reads as a little bit too clever.
</blockquote></details>

I pushed a version that I think is more readable.  PTAL.  (It might be easiest to review the `goal/*.h` changes before reading the Python code.)

As best I can tell it will perform equally well, but it any case performance optimization with benchmarking is a future PR.  As long as this code isn't gratuitously slow (it's not) I think this is good enough for now.

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule (tomorrow), please.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: LGTM missing from assignee xuchenhan-tri(platform)

___
*[`tools/lcm_gen/__init__.py` line 461 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-NpywElt8cuELyIbmxVU:-Nq-IT177XGiBncfi19w:b-8fx2u7) ([raw file](https://github.com/RobotLocomotion/drake/blob/5d8af79158cafe2cac48e13ed03c1acb67fe2ce7/tools/lcm_gen/__init__.py#L461)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I pushed a version that I think is more readable.  PTAL.  (It might be easiest to review the `goal/*.h` changes before reading the Python code.)

As best I can tell it will perform equally well, but it any case performance optimization with benchmarking is a future PR.  As long as this code isn't gratuitously slow (it's not) I think this is good enough for now.
</blockquote></details>

:+1:

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r1, 1 of 2 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-:-Nq3kbUQ2AqwMwJMR19_:bg7igkv)* status: 2 unresolved discussions

___
*[`tools/lcm_gen/__init__.py` line 482 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq-RhYrE8ZaI1DyZLS-:-Nq-RhYsAhQ-V-C_v6O6:b-ndalpg) ([raw file](https://github.com/RobotLocomotion/drake/blob/068882c46394ef544a9c04ca61070d008ec6f413/tools/lcm_gen/__init__.py#L482)):*
> ```Python
>   // passed with `_input` as vector-like container and `_dims...` as the list
>   // of (multi-dimensional) vector sizes, e.g., `int8_t image[6][4]` would
>   // be called like `_encode_field(image.at(0), &cursor, end, 6, 4)`. In LCM
> ```

BTW, I don't understand why is this called this way. Shouldn't the last argument be an std::array? Where does this varargs looking thing come from?



_Code quote:_
```Python
`_encode_field(image.at(0), &cursor, end, 6, 4)`
```
___
*[`tools/lcm_gen/test/functional_test.cc` line 126 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq3gNWPBsFWdpBEh151:-Nq3gNWPBsFWdpBEh152:bmk2f0k) ([raw file](https://github.com/RobotLocomotion/drake/blob/068882c46394ef544a9c04ca61070d008ec6f413/tools/lcm_gen/test/functional_test.cc#L126)):*
> ```cpp
> }
> 
> // With the old lcm-gen, partially-fixed-size arrays are typed as std::vector so
> ```

BTW, question: why are the encoding/hash the same for old and new when the old uses std::vector and the new uses std::array? Is it because the encoding doesn't care what the container is and just encode the content?

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq3l58r9uCi4JAnZFm5:-Nq3l58r9uCi4JAnZFm6:bsgt24p) (no related file):*
BTW, I'm also wondering why we need to replace the upstream lcm_gen.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20887)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),xuchenhan-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq3l58r9uCi4JAnZFm5:-Nq3p0xZ21wDMyL9zjzi:bcm6ntp) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm also wondering why we need to replace the upstream lcm_gen.
</blockquote></details>

My intention was for #20761 to explain that.  I've added a bit more more elaboration to its overview text now.

___
___
*[`tools/lcm_gen/__init__.py` line 482 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq-RhYrE8ZaI1DyZLS-:-Nq3oJ9R7SLd5LffZiGi:b-mw7e27) ([raw file](https://github.com/RobotLocomotion/drake/blob/068882c46394ef544a9c04ca61070d008ec6f413/tools/lcm_gen/__init__.py#L482)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I don't understand why is this called this way. Shouldn't the last argument be an std::array? Where does this varargs looking thing come from?
</blockquote></details>

Good catch!  The docs bitrotted as the PR evolved.
___
*[`tools/lcm_gen/test/functional_test.cc` line 126 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20887#-Nq3gNWPBsFWdpBEh151:-Nq3oNnSEdnD6Zfc8KGY:bkt8ri8) ([raw file](https://github.com/RobotLocomotion/drake/blob/068882c46394ef544a9c04ca61070d008ec6f413/tools/lcm_gen/test/functional_test.cc#L126)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, question: why are the encoding/hash the same for old and new when the old uses std::vector and the new uses std::array? Is it because the encoding doesn't care what the container is and just encode the content?
</blockquote></details>

Yes, the fingerprint (see [here](https://lcm-proj.github.io/lcm/content/lcm-type-ref.html#fingerprint-computation)) is a function of the `*.lcm` message definition, not of the language-specific embodiment of that message in some class definition.  LCM allows communication across programming languages, so the specific programming language embodiment is not part of the fingerprint, only the parts that effect the on-network representation are fingerprinted.

**Pull request merged**
