### PR TITLE
workspace: Use newer Doxygen on Ubuntu

### LINKED ISSUE #10631: Upgrade to latest Doxygen
The latest Doxygen (1.8.15) has a few bugfixes that end up being very nice (in particular, using-declarations for class methods).

Homebrew [already has 1.8.15](https://formulae.brew.sh/formula/doxygen), and in general seems like it will track the latest releases like it usually does.

Ubuntu is [stuck on 1.8.13](https://packages.ubuntu.com/bionic/doxygen) (even in > 18.04).  We should provide a binary image for latest on Ubuntu, so that we can have nice things.

See also in-progress [Debian upgrade to 1.8.15](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919413).

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #10631.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10659)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.  The moved-file diff isn't showing up well here; you can peek at 
[the github diff](https://github.com/RobotLocomotion/drake/pull/10659/commits/079f2afd9fc71a428398c45364e4a1f0077db6c1#diff-917460d00c1959edb35cf592728c68b2) for clarity.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.  (Please also try it out locally.)

**Comment by jwnimmer-tri** [comment]
___
*[doc/doxygen_main.py, line 137 at r1](https://reviewable.io/reviews/robotlocomotion/drake/10659#-LYWzYoO3YOMyfMROJcI:-LYWzYoO3YOMyfMROJcJ:bs7xwf6) ([raw file](https://github.com/robotlocomotion/drake/blob/079f2afd9fc71a428398c45364e4a1f0077db6c1/doc/doxygen_main.py#L137)):*
> ```Python
> 
> 
> def main():
> ```

FYI @jamiesnape I imagine us eventually adding `--out_dir` here, to match the sphinx side.  Then drake-ci could just `bazel run` this tool, the same way it does sphinx.  If you want, I am OK to roll that into this PR.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jamiesnape** [comment]
Is `bazel run //doc:doxygen -- --out_dir=<path>` the new way to run this script on CI?

**Comment by jwnimmer-tri** [comment]
> Is `bazel run //doc:doxygen -- --out_dir=<path>` the new way to run this script on CI?

Yes, that's what I'd recommend changing it to, at some point after this merges.  (Even after this PR merges, the existing command `cd doc && ./doxygen.py` should still work in the meantime.)

Note that `<path>` must be an absolute path if using `bazel run` though, because `bazel run` changes the cwd.

**Comment by jamiesnape** [comment]
I'll make the change now (conditional on doc/doxygen_main.py existing so we can test).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-documentation please

**Comment by jwnimmer-tri** [comment]
___
*[tools/workspace/doxygen/repository.bzl, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10659#-LYYF9M7-fsFwcdMBP2Z:-LYYJAVe8QBb--V9d6Sv:b-wtyyfy) ([raw file](https://github.com/robotlocomotion/drake/blob/463affb6fb9364f8885ccbc7fb49ae9b6a1a2632/tools/workspace/doxygen/repository.bzl#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is there a recipe somewhere for how to regenerate this artifact?  (might not be needed if it's really obvious, I haven't tried building doxygen from source)
</blockquote></details>

Yup, it's easy to build by hand, but indeed ideally we'd write it down / automate it.  Are you OK if I open an issue for Jamie to PR some docs, after this merges?

**Comment by jwnimmer-tri** [comment]
I'm overriding the lsan and debug builds -- they've already passed before, this was a comment-only change, and for a //doc PR they shouldn't be any different.

**Pull request merged**
