### PR TITLE
Use formulae dependent on Python 3.8 on macOS and rebuild VTK for all platforms

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #14243 and #14326. <s>Depends on #14392 and #14393</s>. Note that I have not deprecated anything here, because we did not go through deprecation with the OSPRay renderer (most of the VTK changes are the less obvious cleanup from that removal).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please (expected to have failing tests)
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please (expected to have failing tests)
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Slight mystery why provisioned bionic is not failing. I am probably going to need to update or disable drake-visualizer on Mac.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please (expected to have failing tests)
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jamiesnape)

___
*[setup/mac/binary_distribution/Brewfile, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNxEv3QCJ_eFSq09K8b:-MNxEv3R2EWNfo2bGBSS:bmguvye) ([raw file](https://github.com/robotlocomotion/drake/blob/a8ac891d55ef6354281f0db310b07f86ff2f931b/setup/mac/binary_distribution/Brewfile#L22)):*
> ```Ruby
> brew 'lz4'
> brew 'nlopt'
> brew 'robotlocomotion/director/numpy@1.19.4'
> ```

There needs to be a README somewhere that captures why we make our own snowflake versions of these packages, and these need to cross reference that README.

These two are unsettling (albeit merited, I guess, b/c of upstream Homebrew maintainership).

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNxEv3QCJ_eFSq09K8b:-MNyD7oj73-yuTRXAuUO:b-y2b5m3) ([raw file](https://github.com/robotlocomotion/drake/blob/a8ac891d55ef6354281f0db310b07f86ff2f931b/setup/mac/binary_distribution/Brewfile#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

There needs to be a README somewhere that captures why we make our own snowflake versions of these packages, and these need to cross reference that README.

These two are unsettling (albeit merited, I guess, b/c of upstream Homebrew maintainership).
</blockquote></details>

I don't think a snowflake README is the way forward. Happy to a one-line comment to each entry, though.

**Comment by jamiesnape** [comment]
Actually need the do not merge for Mac. Linux has already been updated, but Mac was deferred since that was the only way we have functioning Mac builds at present.

**Review by jwnimmer-tri — COMMENTED** [review]
I can't review the Brewfile change until the rationale for such a sweeping change to numpy and scipy is explained.  It needs a thorough explanation (more than one sentence), though that can certainly appear in the PR or issue, leaving only a short citation in the actual Brewfile itself.  I assume we should also link to the homebrew issue filed with whatever is wrong with their packages.

(The PR overview post also appears to lack a citation to the issue it's related to.)

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MNyEYrkErmfLrZRUNRs:bq3oljc)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyEIOcExnD9l1epsAl:-MNyEIOcExnD9l1epsAm:b-96zpq2) (no related file):*
Needs someone other than Jamie to locally test that the macOS setup scripts succeed.

Needs someone other than Jamie to locally test that drake-visualizer operates correctly.

---
___
*[setup/mac/binary_distribution/install_prereqs.sh, line 23 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyE4y1DoavDrWK3KjZ:-MNyE4y1DoavDrWK3Kj_:b-35lit2) ([raw file](https://github.com/robotlocomotion/drake/blob/a8ac891d55ef6354281f0db310b07f86ff2f931b/setup/mac/binary_distribution/install_prereqs.sh#L23)):*
> ```Shell
> /usr/local/bin/brew update
> 
> # TODO(jamiesnape): Remove lines uninstalling vtk@8.2, ospray@1.8, and embree@3.5 on or
> ```

nit >80

**Comment by jamiesnape** [comment]
The regular formulae support Python 3.9 only and Drake tests randomly crash at teardown with Python 3.9 from Homebrew. The workaround is to `brew extract` the last working version that uses Python 3.8, and so hopefully the change here is a little less sweeping than it may at first seem.

**Review by jwnimmer-tri — COMMENTED** [review]
So essentially, we are pinning numpy and scipy to the last working revision.  That makes sense.  I assume there is a viable path to unpinning them without reinstalling the whole machine?  At this point, then, my only concerns are the discussions posted inline below.

> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MNyJ2OU9bng8LASNOiA:b-op6brs)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
Yes and `brew uninstall numpy@version && brew install numpy` is all you need, but actually you can have both installed (I do at the moment) and they will purposefully not conflict. Same for `scipy`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MNyK6MS7HB3_4bcwpxC:brbdwbo)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @EricCousineau-TRI and @jamiesnape)

**Comment by jamiesnape** [comment]
Also +@soonho-tri for review and macOS testing.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 2 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jamiesnape, and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI and @jamiesnape)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNyeUaG3AFmgrRD0Lp_:b-avr7s0) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
> ```Ruby
> brew 'nlopt'
> # brew extract last working version that depends on python@3.8.
> brew 'robotlocomotion/director/numpy@1.19.4'
> ```

Both `numpy` and `numpy@1.19.4` want to create a symlink `/usr/local/bin/f2py` and cause the following message:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/f2py3.8
Target /usr/local/bin/f2py3.8
already exists. You may want to remove it:
  rm '/usr/local/bin/f2py3.8'

To force the link and overwrite all conflicting files:
  brew link --overwrite numpy@1.19.4

To list all files that would be deleted:
  brew link --overwrite --dry-run numpy@1.19.4

Possible conflicting files are:
/usr/local/bin/f2py3.8
```

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyEIOcExnD9l1epsAl:-MNyid9a-DMS7ar_hj8b:byy89z5) (no related file):*
> Needs someone other than Jamie to locally test that the macOS setup scripts succeed.
 
There was one error caused by `numpy@1.19.4`. I left a comment in `Brewfile`. I fixed the issue locally by running `brew link --overwrite` to test drake-visualizer.

> Needs someone other than Jamie to locally test that drake-visualizer operates correctly.

I was able to run it on my local mac.

---

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNyjg1J4X_mbR0ed_oi:b-z5bub6) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Both `numpy` and `numpy@1.19.4` want to create a symlink `/usr/local/bin/f2py` and cause the following message:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/f2py3.8
Target /usr/local/bin/f2py3.8
already exists. You may want to remove it:
  rm '/usr/local/bin/f2py3.8'

To force the link and overwrite all conflicting files:
  brew link --overwrite numpy@1.19.4

To list all files that would be deleted:
  brew link --overwrite --dry-run numpy@1.19.4

Possible conflicting files are:
/usr/local/bin/f2py3.8
```


</blockquote></details>

Is your regular `numpy` up to date? It should have `/usr/local/bin/f2py3.9` rather than `/usr/local/bin/f2py3.8`

**Comment by jwnimmer-tri** [comment]
___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNykC1A2PEp57PQNPMR:b8jymog) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Is your regular `numpy` up to date? It should have `/usr/local/bin/f2py3.9` rather than `/usr/local/bin/f2py3.8`
</blockquote></details>

If Drake users had been waiting to brew upgrade because doing so would break Drake, then I think they would get the same error as Soonho?  I assume most users would be in the same boat.  Can install_prereqs do anything to smooth the upgrade path, or at least fail faster with a diagnostic?

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNykVmF4dO4shxr8kGG:b9kmh42) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If Drake users had been waiting to brew upgrade because doing so would break Drake, then I think they would get the same error as Soonho?  I assume most users would be in the same boat.  Can install_prereqs do anything to smooth the upgrade path, or at least fail faster with a diagnostic?
</blockquote></details>

Yes, I just need to be sure that is the case.

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNykrvV0SJafoII5eR4:b-k2yzvr) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Yes, I just need to be sure that is the case.
</blockquote></details>

@jamiesnape , this is what I got when I remove `numpy` and reinstall it:

```
brew install numpy                                                                                                                                                                                                                                                              14:52:31
==> Downloading https://homebrew.bintray.com/bottles/numpy-1.19.4.catalina.bottle.tar.gz
Already downloaded: /Users/soonhokong/Library/Caches/Homebrew/downloads/8afb20c493abbe31406e182e6a9a428e4049e44a8c9e7c6da425d12085c822fb--numpy-1.19.4.catalina.bottle.tar.gz
==> Pouring numpy-1.19.4.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/f2py
Target /usr/local/bin/f2py
already exists. You may want to remove it:
  rm '/usr/local/bin/f2py'

To force the link and overwrite all conflicting files:
  brew link --overwrite numpy

To list all files that would be deleted:
  brew link --overwrite --dry-run numpy

Possible conflicting files are:
/usr/local/bin/f2py
/usr/local/bin/f2py3
==> Summary
🍺  /usr/local/Cellar/numpy/1.19.4: 491 files, 16.3MB
```


<!-- Sent from Reviewable.io -->

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNyla1n93y1wRNEq-Id:bn05nsw) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@jamiesnape , this is what I got when I remove `numpy` and reinstall it:

```
brew install numpy                                                                                                                                                                                                                                                              14:52:31
==> Downloading https://homebrew.bintray.com/bottles/numpy-1.19.4.catalina.bottle.tar.gz
Already downloaded: /Users/soonhokong/Library/Caches/Homebrew/downloads/8afb20c493abbe31406e182e6a9a428e4049e44a8c9e7c6da425d12085c822fb--numpy-1.19.4.catalina.bottle.tar.gz
==> Pouring numpy-1.19.4.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/f2py
Target /usr/local/bin/f2py
already exists. You may want to remove it:
  rm '/usr/local/bin/f2py'

To force the link and overwrite all conflicting files:
  brew link --overwrite numpy

To list all files that would be deleted:
  brew link --overwrite --dry-run numpy

Possible conflicting files are:
/usr/local/bin/f2py
/usr/local/bin/f2py3
==> Summary
🍺  /usr/local/Cellar/numpy/1.19.4: 491 files, 16.3MB
```
</blockquote></details>

This should be where that issue is being mitigated:

https://github.com/RobotLocomotion/homebrew-director/blob/7a3181953f7039064c241a80e3042b511e72db18/Formula/numpy%401.19.4.rb#L104-L105

What does `/usr/local/opt/numpy@1.19.4/bin` contain for you?


<!-- Sent from Reviewable.io -->

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNymu7iBzFoLktyqqdv:bj49v9p) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
> What does /usr/local/opt/numpy@1.19.4/bin contain for you?

There is just a single file `f2py3.8`.

FWIW, I removed `usr/local/bin/f2py*` as well as `numpy` and `numpy@1.19.4` formulas. Then I was able to install both. I guess those `/usr/local/bin/f2py*` were residuals of old numpy formula(s).

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNyvB2y6SGaKPhW3KuV:buhrzo7) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> What does /usr/local/opt/numpy@1.19.4/bin contain for you?

There is just a single file `f2py3.8`.

FWIW, I removed `usr/local/bin/f2py*` as well as `numpy` and `numpy@1.19.4` formulas. Then I was able to install both. I guess those `/usr/local/bin/f2py*` were residuals of old numpy formula(s).
</blockquote></details>

Potentially installed by `pip` if they were not symlinks, I would imagine.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),soonho-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @soonho-tri)

___
*[setup/mac/binary_distribution/Brewfile, line 24 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNyeUaG3AFmgrRD0LpZ:-MNyvtitDtc3gukk-z0c:b-q12vh6) ([raw file](https://github.com/robotlocomotion/drake/blob/7f52696b24daa66fc758971755697e535be908b4/setup/mac/binary_distribution/Brewfile#L24)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Potentially installed by `pip` if they were not symlinks, I would imagine.
</blockquote></details>

I think the original issue is mitigated now. Homebrew does not make upgrading a formula that may or may not be installed and may or may not be outdated without either erroring or outputting to the console very easy,

The PyPI-Homebrew conflict issue has been around since the time of dinosaurs, and not sure I can fix it without breaking something for someone.

**Comment by jamiesnape** [comment]
Assuming Mac CI passes, we should be in good shape. Unfortunately looks like there is maybe a queue for unprovisioned builds at the moment.

**Review by soonho-tri — COMMENTED** [review]
:lgtm: for :apple: part

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MNz66mi9UMW1lvXTunp:b3ed5gf)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+@EricCousineau-TRI needs to resolve a blocking discussion.  Might as well do a light platform review pass at the same time.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MNz6lIu4BfL941Rigl-:b-66nhh1)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge" (waiting on @EricCousineau-TRI)

**Comment by jamiesnape** [comment]
Looks like I need to squash stderr for the `brew list` command for when `numpy` is not installed. Will let the Mac build finish first.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), labeled "do not merge" (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: - sorry for the delay!

> Reviewed 11 of 13 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14395#-:-MO2PGmv3KpXiQqn7QF9:b6yqai1)* status: labeled "do not merge"

___
*[setup/mac/binary_distribution/Brewfile, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14395#-MNxEv3QCJ_eFSq09K8b:-MO2Oy-_AuruwXXDFwm0:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/a8ac891d55ef6354281f0db310b07f86ff2f931b/setup/mac/binary_distribution/Brewfile#L22)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I don't think a snowflake README is the way forward. Happy to a one-line comment to each entry, though.
</blockquote></details>

OK Thanks!

**Pull request merged**
