### PR TITLE
Add script for building drake-visualizer on macOS

### LINKED ISSUE #10729: Add scripts for building Drake Visualizer binary releases

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #10729, finally. Same caveats as #14573, really. There is a small amount of theoretically shared code with the Ubuntu build, but probably not enough to worry about refactoring,

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@soonho-tri for review. This script should not break anyone's Mac, but it does require that Qt 6 is not installed. Tracking down the offending dependency that causes the breakage of Qt 5 might take me some time, so avoiding Qt 6 is my best workaround for now,

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

If @soonho-tri has time to review and locally test this, then I think that's good and we can wait for it.  If review or testing too much work within the next few days, I am a-ok if we land this without necessarily testing it locally first.  We can cross that bridge later.

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771#-:-MVcRiFv6OKiF6UVtpgj:b3y3cex)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @jamiesnape and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14771#-MVb3cI7E-uFWMvnAOFy:-MVb3cI7E-uFWMvnAOFz:bfq8qsn) (no related file):*
nit The do the patch file renames (/ convention of all vs mac vs ubuntu)  need to be reflected back into the Ubuntu script or its globs also?

---
___
*[tools/workspace/drake_visualizer/build_mac_binaries, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14771#-MVb43ax8r8Gi1qABH4R:-MVb43ax8r8Gi1qABH4S:b-8fl4p5) ([raw file](https://github.com/robotlocomotion/drake/blob/d4a6df15ff17dcf397a9bd3d48973cf6d282c0a5/tools/workspace/drake_visualizer/build_mac_binaries#L71)):*
> ```
> 
> bazel clean --expunge
> bazel shutdown
> ```

nit `--expunge` always shuts down, too:
https://docs.bazel.build/versions/master/user-manual.html#clean
so this isn't strictly required.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771)* status: 2 unresolved discussions, LGTM missing from assignee soonho-tri(platform) (waiting on @jamiesnape, @jwnimmer-tri, and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14771#-MVb3cI7E-uFWMvnAOFy:-MVcTLEj643ps3fD0zr0:b-m27gq3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The do the patch file renames (/ convention of all vs mac vs ubuntu)  need to be reflected back into the Ubuntu script or its globs also?
</blockquote></details>

The `.dockerignore` change covers that. Only the non-ignored files are available to the Docker container.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm: 

> This script should not break anyone's Mac, but it does require that Qt 6 is not installed.

FYI, I had to uninstall `qt6` on my mac to run the `./tools/workspace/drake_visualizer/build_mac_binaries` script. I think it's not so difficult to add a check for `qt6` and early-terminate with a message?

> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771#-:-MVdIvuf-ldo7kp81bVX:b-ij70e4)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape)

**Comment by jamiesnape** [comment]
>  I think it's not so difficult to add a check for qt6 and early-terminate with a message?

I guess that means my check already there did not work?

**Comment by soonho-tri** [comment]
> I guess that means my check already there did not work?

It doesn't work.

**Comment by soonho-tri** [comment]
Maybe `brew list <formula> &> /dev/null` is an alternative? It returns 0 if it's installed and `1` otherwise.

**Comment by jamiesnape** [comment]
Try the current version:
https://github.com/RobotLocomotion/drake/blob/0bb73d5e20d190c2e6cc59b2a21c4cbfc163db2c/tools/workspace/drake_visualizer/build_mac_binaries#L43-L49

**Review by soonho-tri — COMMENTED** [review]
It works.

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14771#-:-MVlLLx2B869MOnLjhA1:b-u4jdac)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),soonho-tri(platform) (waiting on @jamiesnape)

**Pull request merged**
