### PR TITLE
doc: Add snapshot of current release playbook

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
There are a lot of imperfections still here, but here the goal is just to transcribe the google docs draft into our project docs, so we can PR it like everything else.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14170)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both(?) reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks for doing this. I wouldn't object to @ggould-tri also looking at it. But wouldn't demand it.

:LGTM: With some small cosmetic things.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14170#-:-MIuk7yC-oNoYlqjHbu7:bd7vnaj)* status: 7 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/release_playbook.rst, line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIuZNp42yVUndy9vMDE:-MIuZNp42yVUndy9vMDF:b-7m3o5j) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L12)):*
> ```reStructuredText
> calendar month, with version number is ``v0.N.0`` where ``N`` is monotonically
> increasing.
>    
> ```

nit trailing whitespace.
___
*[doc/release_playbook.rst, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIuhLIIEUDF1Yypwewz:-MIuhLIIEUDF1Yypwex-:bhpwog1) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L51)):*
> ```reStructuredText
>       the code for ``YYYY-MM-01`` deprecation notations, for the ``MM`` values
>       that would have been associated with our +3 months typical period. (Or
>       alternatively, diff prior_tag..master and grep for DRAKE_DEPRECATED?)
> ```

nit: Question mark here feels like you have an implicit TODO to make sure this works. Can you make it explicit or change the puncutation?
___
*[doc/release_playbook.rst, line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIuhUfF3mW2_4s2YNEU:-MIuhUfF3mW2_4s2YNEV:b8h4uk0) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L61)):*
> ```reStructuredText
> * Many commit messages can be cut down to their summary strings and used as-is.
> * Expand all acronyms (eg, MBP -> MultibodyPlant, SG -> SceneGraph).
> * Commits can be omitted if they only affect tests or non-installed examples.
> ```

BTW Worth expanding on how to recognize "non-installed" examples?
___
*[doc/release_playbook.rst, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIuhfiJ-XpxzlE2cl5T:-MIuhfiJ-XpxzlE2cl5U:bty9thb) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L62)):*
> ```reStructuredText
> * Expand all acronyms (eg, MBP -> MultibodyPlant, SG -> SceneGraph).
> * Commits can be omitted if they only affect tests or non-installed examples.
> * In general you should literally mention added or removed classes and methods
> ```

nit: This makes sense in the context you give below (bindings/deprecations), but this doesn't seem to be generally true (either historically or by fiat). 
___
*[doc/release_playbook.rst, line 108 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIuiCAVE0qoDHSW_fmH:-MIuiCAVE0qoDHSW_fmI:ba3djdf) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L108)):*
> ```reStructuredText
>       from the moment they were launched).  Note it.
> 
>       i. If the git sha for the two does not match, wait and try again tomorrow night.
> ```

nit s/two/three
___
*[doc/release_playbook.rst, line 153 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIujC86-PpLKCCEwIOp:-MIujC86-PpLKCCEwIOq:b4lhle6) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L153)):*
> ```reStructuredText
> 
> 10. Open https://github.com/RobotLocomotion/drake/releases and choose "Draft a
>     new release".  Note that this page does not have history nor undo.  Be slow
> ```

BTW "...does not have history nor undo" burns my eyes. "Not" appearing *before* the verb (to have) seems to render "nor" isolated and unable to do its job. In other words, "I don't have A or B" (negation of verb). Or, "I have neither A nor B" (negation of items). But mixed together?  No thank you.

And is this an example of being overly nit-picky?  I really wrestled with myself on whether I'd write this.
___
*[doc/release_playbook.rst, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14170#-MIujypXDPsghfNEpGO_:-MIujypXDPsghfNEpGOa:bt2yhw6) ([raw file](https://github.com/robotlocomotion/drake/blob/d24cfe488536b07f14a2182a97c2af8505ccbba3/doc/release_playbook.rst#L175)):*
> ```reStructuredText
>        page actually works.
>     b. Click "Publish release"
>     c. Party on, wayne.
> ```

nit Capital "W"?

**Review by jwnimmer-tri — COMMENTED** [review]
I think we'll be rewriting much of this in the near future, so I'll defer any extra review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14170#-:-MIuwByj8V3napsAKydw:b-zijqa0)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
SGTM

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14170#-:-MIuygKeEapwJYP1yhHp:bb73djm)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request merged**
