### PR TITLE
Add CMake target for build documentation

### LINKED ISSUE #1870: add a CMake target for building doxygen docs
It would be nice to be able to test doxygen along with code during development. Having CMake produce a "doxygen" target that could be built with `make doxygen` or from within an IDE would be useful and would hopefully encourage testing of doxygen output, which can be full of surprises.

### PR DESCRIPTION
**Pull request by jamiesnape**
Closes #1870.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2128)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/conf.py.in, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpezUFZVHxZlRacTtb:-KFpezUGEhsyc_EPM8xg:1539946030) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L46)):*
Why this change?  If there's a need for it, it should be a separate PR and flagged for Russ's attention.

---

*[drake/doc/conf.py.in, line 73 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpfLOr9QHZiOaSeoXS:-KFpfLOr9QHZiOaSeoXT:-209729479) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L73)):*
This new sentence doesn't parse.

---

*[drake/doc/conf.py.in, line 120 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpfBzBxd7KXIW9b1rp:-KFpfBzBxd7KXIW9b1rq:-1516699903) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L120)):*
Thanks for fixing this.  It annoys me every time I notice it.

---

*[drake/doc/conf.py.in, line 225 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpfbcsUzTfdsele3Xi:-KFpfbcsUzTfdsele3Xj:-1015454922) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L225)):*
Ditto - can't change this without Russ's approval, and shouldn't be buried.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2128)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/conf.py.in, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpezUFZVHxZlRacTtb:-KFpi3XBZt583Vd2LSH7:297652632) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L46)):*
I entered the wrong name when I ran the sphinx-quickstart tool. Will fix.

---

*[drake/doc/conf.py.in, line 73 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpfLOr9QHZiOaSeoXS:-KFpgxwXSN7R34LTjupZ:1994929823) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L73)):*
This file is auto-generated by Sphinx. Feel free to file a bug with them.

---

*[drake/doc/conf.py.in, line 225 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpfbcsUzTfdsele3Xi:-KFpiULp-y91fE27Zz3J:1095333393) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L225)):*
Also ditto the above. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2128)*

**Comment by jamiesnape** [comment]
Test failures are unrelated.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-:-KFtNfeaebQcHl9nlxCc:1417088721)*

**Comment by david-german-tri** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/doc/conf.py.in, line 46 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2128#-KFpezUFZVHxZlRacTtb:-KFtNjTWnImoj9goHDUg:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/b748f65b5a172f7923a58d7887880179a4986df3/drake/doc/conf.py.in#L46)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2128)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 17 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2128)*

**Comment by david-german-tri** [comment]
@jamiesnape Agreed that the test failures are unrelated, so I'll proceed with the merge, but they're also pretty weird.  In https://drake-jenkins.csail.mit.edu/job/experimental/960/compiler=msvc-32,label=windows/consoleFull, `testConstraintConstructor` appears to build but then can't be found.

**Comment by david-german-tri** [comment]
No, actually, I don't think I should have merged this.  It breaks the left-hand-side table of contents, and it likely breaks the way drake.mit.edu loads the documentation. Reverting.

**Comment by jamiesnape** [comment]
What is wrong the the table of contents?

**Comment by david-german-tri** [comment]
Compare drake.mit.edu to the generated output.  The links in the top left are missing.

**Comment by jamiesnape** [comment]
There no code to create that table of contents as far as I can see. I have not changed anything that could create it.

**Comment by jamiesnape** [comment]
Maybe not. I see an issue now: https://github.com/RobotLocomotion/drake/commit/a41f5a44e1dfb5ee47e8c4c948d815469598ade0#diff-d897d4d6b7858ba295f3acf0b8d5ae00R166

**Comment by david-german-tri** [comment]
Yeah, I suspect that's it.  Sorry for the premature merge - I thought I had sanity-checked the HTML yesterday, but if I did I missed that.  Once it's fixed, we'll need to coordinate with Russ on updating where drake002 looks for the docs.

**Comment by jamiesnape** [comment]
We set up a new repo for that: https://github.com/RobotLocomotion/RobotLocomotion.github.io

**Comment by david-german-tri** [comment]
Oh, OK.  How will it pull the built artifacts?

**Comment by jamiesnape** [comment]
They will  be pushed by Jenkins nightly builds. I have to coordinate with MIT to get drake.mit.edu redirected once they are in place.

**Comment by david-german-tri** [comment]
Sounds good.

**Pull request merged**
