### PR TITLE
Upgrade to Bazel 6.1.1

### LINKED ISSUE #18946: Upgrade to Bazel 6.1.1
We should upgrade our supported Bazel version to https://github.com/bazelbuild/bazel/releases/tag/6.1.0 (really, 6.1.1 once it's out).

FYI the prior upgrade was here: https://github.com/RobotLocomotion/drake/issues/18508.

It might be worth planning to upgrade Ubuntu and macOS separately.

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #18946  

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19012)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Let's start with a few jobs, if these look good then I'll launch the entire suite:

@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-gcc-bazel-experimental-coverage please

**Comment by jwnimmer-tri** [comment]
"Signs point to yes", as they say.

+@ggould-tri for both reviews, please +(status: single reviewer ok).

+(status: do not merge) to allow coordinating with the AMI refresh.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19012#-:-NQg-LwB6l0SwmkCjwoG:bnfp4nl)* status: labeled "do not merge" (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
The linux provisioned images are ready to go. When this last Mac job finishes, we're ready to merge and update Jenkins.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19012#-:-NQgB9Lt9uuvHnhsenDc:b-dtcvsp)* status: labeled "do not merge" (waiting on @BetsyMcPhail)

**Pull request merged**
