### PR TITLE
[multibody] Remove the deprecated Parser::AddModelFromString

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NVX4ML16cCEceRH3RV3:bra0dy3) (no related file):*
I'm testing it with Anzu-master-Drake-PR/206/.

___

**Review by DamrongGuoy — COMMENTED** [review]
CC: @rpoyner-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-:-NVX4UAO2xp_4G-pKthR:b17tksk)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
I think this is fine to remove. Don't forget the python bindings!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-:-NVXA2nF56V9lYLd7f3m:b-q1wrsi)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Comment by jwnimmer-tri** [comment]
I guess I should have bumped the date out another three months when I purposefully skipped this deprecation removal.  My thought was that `AddModelFromFile` and `AddModelFromString` should live and die together, to retain symmetry, but I guess I don't care enough to fight it.

**Review by rpoyner-tri — COMMENTED** [review]
I think the argument against `AddModelFromString` was that the modelrenaming could be simulated with string substitutions more easily. I'm not against letting it ride a few more months, but don't really feel the need.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-:-NVXBJ-KEr7QasTrPG2u:bfy7r2b)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
Indeed CI failed in Python bindings. Thanks, @rpoyner-tri. I have removed its Python binding.

I'll continue on Wednesday after my 1-day vacation tomorrow(Tuesday).  Please feel free to take over if you'd like it merged tomorrow.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-:-NVXMBco6Ctd9n42GYbS:b-7hg8sa)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NVXQr_R8F_XbQxuqh9j:b-lksyw6) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I'm testing it with Anzu-master-Drake-PR/206/.
</blockquote></details>

Test Anzu-master-Drake-PR/207/.

___

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per https://drake.mit.edu/platform_reviewer_checklist.html, please.

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-:-NV_5sP22kMo7E2AN12j:b3dcro0)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NV_9kiu2rQYry6DS4kS:b-8m3kug) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

From what I can tell, those anzu builds are failing badly, but I can't tell that it has anything at all to do with this patch.
</blockquote></details>

Here's what I think needs to happen. This PR branch is based off some days-old notion of Drake master, and I suspect that is what is causing anzu mayhem. Try rebasing (and squashing while you're at it) onto current master, and give the anzu-master-drake-pr thing another try.

FWIW, Anzu-master-Drake-master is currently passing.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NVfqjMp0FQZNIufaOMd:b-dhbukn) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Here's what I think needs to happen. This PR branch is based off some days-old notion of Drake master, and I suspect that is what is causing anzu mayhem. Try rebasing (and squashing while you're at it) onto current master, and give the anzu-master-drake-pr thing another try.

FWIW, Anzu-master-Drake-master is currently passing.
</blockquote></details>

Thank you.  I'll squash rebase on the new master now.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NVfxDex552Bo3dtsonE:b-xr1rp) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you.  I'll squash rebase on the new master now.
</blockquote></details>

Rebased and try another Anzu-master-Drake-PR/208.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19413)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19413#-NVX4ML0AjQLnFjCMl-l:-NVg4K-aD6w6trbgHZO_:bbxuc34) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Rebased and try another Anzu-master-Drake-PR/208.
</blockquote></details>

Anzu-master-Drake-PR/208 passed now.  Rebased Drake master did fix the problem.  Thanks.

___

**Pull request merged**
