### PR TITLE
Update Bazel documentation for Trusty and OS X.

### PR DESCRIPTION
**Pull request by david-german-tri**
cc @siyuanfeng-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4408)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This is fine for now.  I would like to automate it within our Bazel configs, but at least this is a start.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4408#-:-KYPKf782bW8v0avbA7c:bpg5143)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4408#-:-KYPKp2T9qhQXi8twkF3:undefined)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/doc/bazel.rst, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4408#-KYPLWGv7GSQ95IuSMVa:-KYPLWGv9XUz_ISdoTwf:b-tkqzt5) ([raw file](https://github.com/robotlocomotion/drake/blob/101e5340ecf11b3d0299e891583625687c739f05/drake/doc/bazel.rst#L31)):*
> ```reStructuredText
> 
>    - Note that **only** the software installation steps are required.
>    - If applicable, you must ``export`` your compiler environment variables.
> ```

BTW, maybe just make it a bit more explicit for noobs like me..
i compiled everything with 
cd drake-distro
env CC=gcc-4.9 CXX=g++-4.9 FC=gfortran-4.9 bazel build //...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4408)*

**Comment by david-german-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/bazel.rst, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4408#-KYPLWGv7GSQ95IuSMVa:-KYVvrlJIIwFaUVt3k9j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/101e5340ecf11b3d0299e891583625687c739f05/drake/doc/bazel.rst#L31)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, maybe just make it a bit more explicit for noobs like me..
i compiled everything with 
cd drake-distro
env CC=gcc-4.9 CXX=g++-4.9 FC=gfortran-4.9 bazel build //...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4408)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4408)*

**Pull request merged**
