### PR TITLE
Use yaml_cpp from Ubuntu Xenial.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
This splits the yaml-cpp changes from https://github.com/RobotLocomotion/drake/pull/7347 into a separate pull request.

yaml-cpp is already part of the setup scripts for Xenial and Mac.

CC collaborators @j-rivero and @clalancette

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7352)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Note for reviewers, please verify that redistributable packages still work. Shambhala is the test case at this present moment in time.

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/drake.cps, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-KxUETFRxnpozFn5MYpq:-KxUETFRxnpozFn5MYpr:b-2mr29v) ([raw file](https://github.com/robotlocomotion/drake/blob/efc17fc438f0e1973bfa7a3cd23a3c03ae827552/tools/install/libdrake/drake.cps#L87)):*
> ```delphi
>       "X-CMake-Find-Args": ["CONFIG"]
>     },
>     "yaml-cpp": {
> ```

Note that the install packages would be broken with this change. See below for a temporary workaround.

---

*[tools/install/libdrake/drake.cps, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-KxUEwvR5ed8anFKyGfr:-KxUEwvR5ed8anFKyGfs:bbe8oam) ([raw file](https://github.com/robotlocomotion/drake/blob/efc17fc438f0e1973bfa7a3cd23a3c03ae827552/tools/install/libdrake/drake.cps#L106)):*
> ```delphi
>       ],
>       "Compile-Features": ["c++14"],
>       "Link-Flags": ["-ltinyxml2"],
> ```

Changing this to
```
"Link-Flags": [
  "-ltinyxml2",
  "-lyaml-cpp"
],
```
would probably be good enough for now, but it is not entirely correct as it implicitly relies on the headers being the search path. Ideally, the `yaml-cpp` header would not be used in a public header, but that is not currently the case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxUG1Ak_T3ar_c5igLj:b-yj97dj)*

**Comment by jamiesnape** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/install/libdrake/drake.cps, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-KxUEwvR5ed8anFKyGfr:-KxUHGzIGZuD3uwo4KTc:b-h6uyff) ([raw file](https://github.com/robotlocomotion/drake/blob/efc17fc438f0e1973bfa7a3cd23a3c03ae827552/tools/install/libdrake/drake.cps#L106)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Changing this to
```
"Link-Flags": [
  "-ltinyxml2",
  "-lyaml-cpp"
],
```
would probably be good enough for now, but it is not entirely correct as it implicitly relies on the headers being the search path. Ideally, the `yaml-cpp` header would not be used in a public header, but that is not currently the case.
</blockquote></details>

(also ideally Bazel would not suffer from #492 so this could be omitted altogether)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please

+@jwnimmer-tri as platform review volunteer.
+@soonho-tri as :apple: local build tester, please.

We will still need to find an Ubuntu volunteer to feature review and test vs Shambhala.

**Comment by jwnimmer-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/maliput/monolane/BUILD.bazel, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-Kx_g-3i9NCvE_L_BNcI:-Kx_g-3i9NCvE_L_BNcJ:blszkoq) ([raw file](https://github.com/robotlocomotion/drake/blob/efc17fc438f0e1973bfa7a3cd23a3c03ae827552/drake/automotive/maliput/monolane/BUILD.bazel#L80)):*
> ```
>     deps = [
>         ":builder",
>         "@yaml_cpp",
> ```

Why is this removed?  This is exactly the place it should have been.

---

*[drake/automotive/maliput/monolane/BUILD.bazel, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-Kx_gKbANQIIbbS_sDN_:-Kx_gKbANQIIbbS_sDNa:b-x9vu7d) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b5fe083092649c75e0b383eb3f33695cd35b24/drake/automotive/maliput/monolane/BUILD.bazel#L127)):*
> ```
>         ":loader",
>         "//drake/common:text_logging_gflags",
>         "@yaml_cpp",
> ```

This cc file doesn't include anything from yaml, so this line should not be here.

---

*[drake/automotive/maliput/utility/BUILD.bazel, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-Kx_eYViC1IGleAujZpN:-Kx_eYViC1IGleAujZpO:b-h4honl) ([raw file](https://github.com/robotlocomotion/drake/blob/b4b5fe083092649c75e0b383eb3f33695cd35b24/drake/automotive/maliput/utility/BUILD.bazel#L41)):*
> ```
>         "//drake/automotive/maliput/monolane",
>         "//drake/common:text_logging_gflags",
>         "@yaml_cpp",
> ```

This cc file doesn't include anything from yaml, so this line should not be here.

I pulled the PR locally to explore.  The actual problem is that monolane's `loader.cc` fails to declare is deps on `@yaml_cpp`.  Once it's added there, it's no longer needed here.

Ditto for the same edit below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352)*

**Comment by stonier** [comment]
+@stonier as :penguin: (xenial) feature review and local build tester

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxdGA4f5W4x0ksVXSbd:b-h2j9ab)*

**Comment by stonier** [comment]
Testing currently fine for this branch and shambhala (using [this branch](https://github.com/stonier/drake-shambhala/tree/stonier/yaml)).

Awaiting changes requested by @jamiesnape and @jwnimmer-tri.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxeqNq0HytXpvS3nh4M:b6d3e31)*

**Comment by nuclearsandwich** [comment]
> Changing this to
> 
> ```
> "Link-Flags": [
>   "-ltinyxml2",
>   "-lyaml-cpp"
> ],
> ```
> 
> would probably be good enough for now, but it is not entirely correct as it implicitly relies on the headers being the search path. Ideally, the yaml-cpp header would not be used in a public header, but that is not currently the case.

Shall I make this change on the PR branch?

**Comment by jamiesnape** [comment]
Either that or a proper fix. This PR cannot break the packages.

**Comment by jwnimmer-tri** [comment]
If both Jamie is correct about the metadata changes being required, and Daniel is correct that Shambhala tests are passing, does that mean Shambhala is not yet a good enough test of the packages?  Should we be testing PRs like this against, say, Spartan also?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxhUKHYvGaEXOd5C3yj:b-rokim3)*

**Comment by nuclearsandwich** [comment]
> Either that or a proper fix. This PR cannot break the packages.

I will start with this change as I'm not clear on what the proper fix would be, nor how to test an attempt at one locally. What are you exercising to exhibit the breakage locally?

Should I be concerned that on both my local workspace and in an isolated docker container the PR as submitted builds (`bazel build //...`) without reported errors? It sounds like the two of you both had issues immediately.

---

> Why is this removed? This is exactly the place it should have been.
...
> This cc file doesn't include anything from yaml, so this line should not be here.
> 
> I pulled the PR locally to explore. The actual problem is that monolane's loader.cc fails to declare is deps on @yaml_cpp. Once it's added there, it's no longer needed here.

I will make these changes and test again. At the time I was under the impression that I was addressing build failures but I've rebased against master enough since then that it's entirely possible I bungled something but not enough to break my local build.

**Comment by jamiesnape** [comment]
> I will start with this change as I'm not clear on what the proper fix would be, nor how to test an attempt at one locally. What are you exercising to exhibit the breakage locally?

Drake uses yaml-cpp in its public headers, you can use `grep` to verify that, so if someone uses that header in their code it will be broken. I have no idea if there is actually coverage of that.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxhUnRQSuxdRZDGXiud:b-2oijrv)*

**Comment by jwnimmer-tri** [comment]
> Should I be concerned that on both my local workspace and in an isolated docker container the PR as submitted builds (bazel build //...) without reported errors? It sounds like the two of you both had issues immediately.

FYI I did not experience any errors.  My comments are all about code review and bad smells.

Jamie's comments about link flags are about whether Drake's installed or packaged binary release will work for users consuming it.  Because of #7260, we don't have CI coverage of that yet.  So the author (and reviewer, here Daniel) has to test manually against some exemplar downstream users --  Shambhala at least.  (My recent question asks whether Shambhala on its own is good enough.)

**Comment by jwnimmer-tri** [comment]
+(status: curate commits before merging) 
http://drake.mit.edu/reviewable.html#curated-commits

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-Kxhc0nUAFH8k9sVMFxC:bohreui)*

**Comment by soonho-tri** [comment]
:apple: tested. `bazel test //drake/automotive/maliput/monolane/... -c dbg` passed.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-Kxhe4FlscbNCrz6jG8V:b-ldk16w)*

**Comment by stonier** [comment]
> Jamie's comments about (Edit to add: include and) link flags are about whether Drake's installed or packaged binary release will work for users consuming it. Because of #7260, we don't have CI coverage of that yet. So the author (and reviewer, here Daniel) has to test manually against some exemplar downstream users -- Shambhala at least. (My recent question asks whether Shambhala on its own is good enough.)

Just to be clear, we do have CI coverage, but it's posthumous. Next steps are to get it into buildcop review and ultimately some form of it as a PR hook. Obviously, I am looking forward to that so I don't have a manual step involved.

Having said that, this wouldn't have been caught by CI since in normal cases it gets saved by discovering it via the default system path setting. We should actually provide the system include path *and* libs here, just like for any other installed cmake/pkgconfig module. 

@jamiesnape what's the recommended way to handle this? Push the discovered yaml-cpp include directory into the "Includes" list? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxhhZTjSYR38gnso43d:bkgh6cc)*

**Comment by soonho-tri** [comment]
> Note for reviewers, please verify that redistributable packages still work. Shambhala is the test case at this present moment in time.

I think I found an existing problem. Filed an issue at https://github.com/RobotLocomotion/drake-shambhala/issues/56 .

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-Kxhk6C8PmvfF-Sz35cX:b-e0y3v5)*

**Comment by soonho-tri** [comment]
Please ignore my previous comment.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-Kxhl1I7xi8yj5Ejh_w_:bs20ewx)*

**Comment by jamiesnape** [comment]
> @jamiesnape what's the recommended way to handle this? Push the discovered yaml-cpp include directory into the "Includes" list?

That would work on Linux, but is brittle on Mac since the pkg-config file there unfortunately points to `/usr/local/Cellar/yaml-cpp/0.5.3` instead of `/usr/local` or `/usr/local/opt/yaml-cpp`. Probably the correct answer would be to write a find-module, install it, and reference it in `drake-config.cmake`.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxhxuA63-04-R5n2byZ:b-xezb3u)*

**Comment by stonier** [comment]
That should be fine though since the setup script for Mac will make sure that gets installed?

Most other pkg-config scripts rely on the fact that their dependencies are explicitly installed by the system and don't go hunting for potentially a different one than the binaries were compiled with. 

Additionally, there is only likely to be support for Mac binaries on local installs for the foreseeable future.

**Comment by jamiesnape** [comment]
> That should be fine though since the setup script for Mac will make sure that gets installed?

The problem is when someone does `brew upgrade` and there happens to be an update to `yaml-cpp`, you end up with a disconnect.

**Comment by stonier** [comment]
We do not have it yet, but only planning on support for Mac binaries on local installs for the foreseeable future which should avoid any brittleness with the system (patch) version changing. If for any reason that does happen - the policy would be just to make sure you have the latest of both.

I'd prefer that than going hunting for and potentially finding the wrong yaml-cpp on linux.

**Comment by jamiesnape** [comment]
> I'd prefer that than going hunting for and potentially finding the wrong yaml-cpp on linux.

Not sure how that would happen. The find-module would just call `pkg-config`.

**Comment by stonier** [comment]
> Not sure how that would happen. The find-module would just call pkg-config.

Someone installs a (possibly non system patched) version in `/usr/local`. 

I would rather it points explicitly to the dependencies it was created from rather than have the potential to be misdirected. If for homebrew that means upgrading the installed drake following a brew upgrade, then that's fine for the foreseeable future until we get to the point of producing mac binaries.

**Comment by jamiesnape** [comment]
> I would rather it points explicitly to the dependencies it was created from rather than have the potential to be misdirected. If for homebrew that means upgrading the installed drake following a brew upgrade, then that's fine for the foreseeable future until we get to the point of producing mac binaries.

Ok, your decision, but from past experience, and the number of bug reports that it generates, that is not a good idea.

**Comment by jamiesnape** [comment]
So, in the absence of find-modules (for better or worse), we have a prototype [`pc2cps`](https://github.com/mwoehlke/pycps/blob/pkgconf/pc2cps) utility and I would suggest that this PR does the minimum to keep the packages working while we iterate on that, since this a general problem for all the new pkg-config dependencies.

**Comment by nuclearsandwich** [comment]
For what it is worth, we suffer a steady amount of issue traffic in ROS 2 as a result of hard coded paths to installed binaries (https://github.com/ros2/ros2/issues/311 is a representative example). These paths change at upstream's discretion. There are platform limitations preventing us from working around our issue there easily, but hard coding these paths is going to be a definite developer experience hit, especially on a rolling release platform like MacOS + Homebrew.

**Comment by stonier** [comment]
Ffrom f2f with @jamiesnape , just append the yaml cpp include directories found via pkgconfig to the "drake" "Includes" list in `drake.cps`. @jamiesnape is that actually extractable from the bazel generated `@yaml_cpp`?

We might automate that better with the `pc2cps` linked above or find the appropriate way to go scrummaging for it with homebrew in the future, but we don't have anything ready to go, so that will do for now.

**Comment by jamiesnape** [comment]
> @jamiesnape is that actually extractable from the bazel generated `@yaml_cpp`?

Good question. Certainly available from a `.bzl` file, not sure about a `BUILD` file.

**Comment by stonier** [comment]
> > @jamiesnape is that actually extractable from the bazel generated @yaml_cpp?
>
> Good question. Certainly available from a .bzl file, not sure about a BUILD file.

@nuclearsandwich can you see if you can work this out?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich can you see if you can work this out?

Yes, I'll take a look at it before tomorrow's sync.

**Comment by jwnimmer-tri** [comment]
FYI #7363 has merged, so `yaml_util.h` is in `/drake/systems/controllers` now, with private visibility.  We could change the install to exclude its header file, at which point I believe Drake's installed headers would not reference `#include "yaml-cpp/yaml.h"` anymore.

**Comment by nuclearsandwich** [comment]
> >  just append the yaml cpp include directories found via pkgconfig to the "drake" "Includes" list in drake.cps. `@jamiesnape` is that actually extractable from the bazel generated @yaml_cpp?

> Good question. Certainly available from a .bzl file, not sure about a BUILD file.

Looked into it this morning and that information is only available from the `repo_ctx` object and friends in .bzl files. Chris did some work in to generate the cps content for libccd (#7371) which we talked about factoring into a PR that this could use as well.

If I understand correctly, with the merge of #7363 , we could also stopgap by just adding the link flag described in https://github.com/RobotLocomotion/drake/pull/7352#issuecomment-340061837 until a pc2cps solution is available.

**Comment by jamiesnape** [comment]
> If I understand correctly, with the merge of #7363 , we could also stopgap by just adding the link flag described in #7352 (comment) until a pc2cps solution is available.

Yes, once the install excludes `yaml_util.h`.

**Comment by nuclearsandwich** [comment]
> Yes, once the install excludes yaml_util.h.

Okay, so one option for this PR in the immediate term

- exclude yaml_util.h from the install.
- Add the `-lyaml-cpp` link flag to drake.cps

**Comment by jamiesnape** [comment]
> Okay, so one option for this PR in the immediate term
>
> * exclude yaml_util.h from the install.
> * Add the -lyaml-cpp link flag to drake.cps

Sounds good.

**Comment by nuclearsandwich** [comment]
In a sync with @stonier earlier today we've opted to pursue the immediate option of adding the link flag and excluding yaml_util.h. I was under the seemingly mistaken impression that [this change](https://github.com/RobotLocomotion/drake/pull/7363/files#diff-b0703373c5efa9991f5ca8a429322b23L331) from #7363 would exclude that header but that doesn't appear to be the case. Are there any other examples of excluded files for the installation tools or should I be looking to implement new functionality?

**Comment by jwnimmer-tri** [comment]
For removing that header from the install, I had thought we already had a sample you could copy from, but I'm not immediately finding it.  Sorry for that confusion.

The place to edit the list of installed headers would be:
https://github.com/RobotLocomotion/drake/blob/22f17bd7cdc1990347147b00e385b76dcbfeb52d/tools/install/libdrake/BUILD.bazel#L38-L46
I think `guess_hdrs_exclude = ..something..` on that rule is the mechanism you want.

**Comment by jwnimmer-tri** [comment]
This patch works for me.
```diff
--- a/tools/install/libdrake/BUILD.bazel
+++ b/tools/install/libdrake/BUILD.bazel
@@ -39,6 +39,12 @@
     name = "install",
     targets = ["libdrake.so"],
     guess_hdrs = "WORKSPACE",
+    guess_hdrs_exclude = [
+        # This is private visibility; we don't want to have a yaml dependency
+        # in our published headers.  TODO(jwnimmer-tri) Update the guess_hdrs
+        # logic to exclude non-public headers by default.
+        "drake/systems/controllers/yaml_util.h",
+    ],
     allowed_externals = ["//:LICENSE.TXT"],  # Root for our #include paths.
     deps = [
         ":install_cmake_config",
```

**Comment by nuclearsandwich** [comment]
Thanks @jwnimmer-tri I'll I'm afk at the moment in Eastern time but I'll confirm it works locally and make the change before calling it a night.

**Comment by nuclearsandwich** [comment]
Rebased on master to pick up #7363 and applied @jwnimmer-tri's patch to exclude yaml_util.h from the instal and added yaml-cpp to the link flags.

I tested the subsequent install using @stonier's [branch of drake-shambhala](https://github.com/stonier/drake-shambhala/tree/stonier/yaml). Though it looks like the copied out yaml_to_obj.cc used to test wasn't committed to the actual branch. Copying it in, the build succeeds.

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-KxwRmQn8kAcbXC3B1iU:bcpz082)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by nuclearsandwich** [comment]
Should I be addressing the two failures [[1]](https://drake-jenkins.csail.mit.edu/job/linux-xenial-clang-cmake-experimental/23/) [[2]](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-cmake-experimental-matlab/18/) with the CMake builds?

**Comment by jwnimmer-tri** [comment]
Possibly they are due to Jenkins having not exactly the right sources established to build.  Since there are merge conflicts anyway, perhaps just update the PR to base off latest master.  The push from that will cause a re-test, and we'll see what it looks like then.

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352)*

**Comment by jwnimmer-tri** [comment]
The cmake builds have passed now.  We'll do a final check of Mac builds:

@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
I've confirmed on Ubuntu that the library is listed:
```console
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro/tmp$ ldd lib/libdrake.so  | grep yaml
	libyaml-cpp.so.0.5 => /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.5 (0x00007fd4bb00a000)
```

I've confirmed on Ubuntu that Shambhala drake_cmake_installed still works :penguin:.  I think we can de-assign @stonier if everything else is ready and he doesn't object.

@soonho-tri Do you want to test locally on Mac?  If so, can you LGTM?  If not, just de-assign yourself?

**Comment by soonho-tri** [comment]
:lgtm:

+ tested `bazel test //drake/automotive/maliput/monolane/... -c dbg` (passed).

---

Reviewed 3 of 8 files at r1, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7352#-:-Kxyq75YIBcCP2hpfRXi:bn7nl7g)*

**Comment by jwnimmer-tri** [comment]
The elcapitan error is:
```
//drake/systems/controllers/qp_inverse_dynamics:valkyrie_balancing_test  FAILED in 47.0s
```
But I don't think that test uses yaml:
```console
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel query 'somepath("//drake/systems/controllers/qp_inverse_dynamics:valkyrie_balancing_test", "@yaml_cpp//:yaml_cpp")'
INFO: Empty results
```
so probably not the fault of this PR, but rather just a flake.  We'll try a retest.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental-everything please

**Pull request merged**
