### PR TITLE
Mouse + keyboard teleop for manipulation station

### PR DESCRIPTION
**Pull request by peteflorence**
Per request by @RussTedrake ! (see #10570)

Demo video: https://www.youtube.com/watch?v=5wSl09jm1vY&feature=youtu.be

Commands are at the top of the file:

## End Effector Control
```
    mouse movement     - move in the manipulation station's y/z plane
    mouse buttons      - roll left/right
    w / s              - move forward/back this y/z plane
    q / e              - yaw left/right (also can use mouse side buttons)
    a / d              - pitch up/down
```

## Gripper Control
```
    mouse wheel        - open/close gripper
```
## Misc
```
   space              - switch out of teleop mode
   alt+tab then enter - return to teleop mode
   escape             - quit")
```

Note that I moved DifferentialIK to a different file so it could be used from new file without running that script.

There is still considerable code copy from `end_effector_teleop.py`, but this didn't seem like the best PR to abstract some of that, seems better fit for a different PR.

In future could make it more configurable to map keys-->DOFs, but... the Python is so easy to write, I'm not sure a .yaml would be any easier :)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10632)

### CODE REVIEW

**Comment by RussTedrake** [comment]
awesome.  a few initial thoughts:
- i think this should simply replace the current end_effector_teleop.  It's strictly better, right?
- pulling out the diffIK is still good; it's been on my list.
- the comment you put in your PR message is great -- can you put it in the top of the file, too?
- perhaps the `teleop_mouse_keyboard_manager.py` could be in the same file as the mouse_keyboard_teleop -- it's an implementation detail and I would like it to be more hidden?

**Comment by peteflorence** [comment]
Thanks Russ

1. I would still keep the slider-based end_effector_teleop.py... ^1 ^2
2. 👍 can put instructions in the file
3. 👍 can move the TeleopMouseKeyboardManager class into the same file

^1 One annoying thing about my teleop is that it grabs the mouse's focus and so you can't easily switch to changing the 3D visualizer view. Could add hotkeys to switch in and out of focus.  But that is one thing that's nicer about the slider GUI, it's easy to switch in + out of teleopping.

^2 Also, I think it's useful to have lots of "example" code?

@jwnimmer-tri 🥇  if possible could you help me parse why the CI is failing?  (This is just Python code?)

**Comment by RussTedrake** [comment]
i agree with having lots of examples.  i just want to avoid duplicating too much (and having to maintain them).  in my book, they are both "end_effector_teleop".  perhaps we could have a command-line argument for which to use (e.g. --mouse uses yours instead of the sliders?).  

and perhaps we could even print the key bindings to the console when the app runs?

I think both the sliders and the mouse version are pretty general tools for teleoping a pose that could move next to (or inside of) bindings/pydrake/manipulation/simple_ui.py.  but we can save that for a future PR.

**Comment by RussTedrake** [comment]
re: why it fails, just following the links into cdash on the console, and you'll see
https://drake-cdash.csail.mit.edu/testDetails.php?test=26104632&build=1116637

**Comment by peteflorence** [comment]
Would also be interested to see if somebody else wants to try this out and test it?

One thing is that all the sensitivities of the keyboard presses are dependent on how fast the process runs (as opposed to the ROS-based version which runs in a separate process at a fixed 100 Hz)... there could be solutions to this but I'm not sure if it's a problem worth solving.  If somebody could try it out on a different machine that would be helpful to know.

**Comment by peteflorence** [comment]
- [ ] Added prints for instructions
- [ ] Moved the teleop manager class into the same one file

**Comment by peteflorence** [comment]
Okay @RussTedrake I think responded to all comments other than a larger overhaul of the manipulation station examples?

Let me know who else should review / what else to do to get merged?

Would like to have somebody else test first if possible... (wouldn't even need to build anything... somebody could try it out very quickly!)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-debug please

**Comment by RussTedrake** [comment]
will try it out myself tonight.

**Comment by peteflorence** [comment]
Yeah open to suggestions on the mouse focus... probably easiest to discuss in person?

**Comment by gizatt** [comment]
Just tried it in Drake (and building for Spartan now) -- works great!

Thoughts:
- I didn't see this as a Bazel target -- might be nice to list as one (can copy from the `*_teleop` targets)
- q/e could be good yaw buttons rather than side-of-mouse buttons

**Comment by peteflorence** [comment]
- [ ] add switch in/out of focus
- [ ] add q/e yaw bindings
- [ ] merge with `end_effector_teleop.py`
- [ ] make sure this covers it as a Bazel target
- [ ] code review myself again

**Comment by RussTedrake** [comment]
you convinced me (f2f) that the number of switches required to put it into end_effector_teleop.py might be too much; i'm ok with it living as a parallel example. but i do think it should be named appropriately, e.g. end_effector_teleop_mouse.py ?

**Comment by peteflorence** [comment]
OK I think ready to go?

Added the ability to switch in/out of focus.  Long story short I think this is the best way:
- press `space` at any time: release focus
- `alt+tab`, then `enter`: re-grab focus

Options that would have allowed just one key press (i.e., `enter`) to re-grab focus would have been quite complicated... not possible with pygame... would need something like `xdotool` or `keyboard` with sudo access.

Added the focusing instructions to the printout

**Comment by peteflorence** [comment]
Re: scaling the key press sensitivities, I actually think it is currently the best thing.  Because if it drops lower than realtime, the sensitivities will proportionally drop with it... which is we want I think?

**Comment by peteflorence** [comment]
Build error is revealing:

`ModuleNotFoundError: No module named 'pygame'`

Is it OK to introduce `pygame` as a dependency?

**Comment by RussTedrake** [comment]
pygame is already a dependency:
https://github.com/RobotLocomotion/drake/search?q=pygame&unscoped_q=pygame

**Comment by peteflorence** [comment]
Hey Russ, I'm not sure though why the CDash errors are "No module named pygame"
https://drake-cdash.csail.mit.edu/testDetails.php?test=26249411&build=1117318

I looked for some type of special whitelisting over in the automotive example but didn't see anything that seemed necessary.  Obviously I am missing something.

**Comment by RussTedrake** [comment]
Looks to be python3 related.   @jamiesnape — any advice?

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/source_distribution/packages-bionic.txt has python-pygame but not python3-pygame.  If its only failing on python3 builds, that could be why.

**Comment by peteflorence** [comment]
👍 thanks @jwnimmer-tri I just added `python3-pygame`, let's see if works now!

**Comment by jwnimmer-tri** [comment]
Those files are not typically processed by everyday CI.  You have to opt-in to a https://drake-jenkins.csail.mit.edu/view/Unprovisioned/ build to try it (https://drake.mit.edu/jenkins.html#running-an-on-demand-build), but there's no python3 builds defined there yet it seems, so that won't help.  I'd say just work on the PR for now ignoring any python3-only failures; we'll just PR that txt file change separately (and then re-image CI with the new dependency).

**Comment by jwnimmer-tri** [comment]
Tagging +@RussTedrake specifically as feature reviewer.  (We can swap that for someone else later if we need, but we should have someone assigned for now at least.)

**Comment by jwnimmer-tri** [comment]
(Also note that this needs a merge up to latest master -- there is a conflict at the moment.)

**Comment by peteflorence** [comment]
Rebased on master!

**Comment by peteflorence** [comment]
OK I think this is only blocked on:

- Python3 test environment not having `pygame`
- Code review

**Comment by jwnimmer-tri** [comment]
> Does that mean the plan is to split the change to `setup/ubuntu/source_distribution/packages-bionic.txt` into its own PR to merge before this one and then merge this PR after we re-spin CI?

Yes.  But now that #10651 is fixed, please iterate first on _this_ PR to get bionic + python3 working, so that we know what the correct change is.  Once someone has tested and debugged on Bionic, comment here on github (not reviewable) `@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release please` and it'll fire off a build that _does_ obey the new packages txt file.  Once that unprovisioned build has passed, then we can split off the packages txt file into its own PR.

**Comment by jamiesnape** [comment]
There is no `apt` package for a Python 3 version of `pygame` and we do not use `pip` on Ubuntu, so this PR needs to find an alternative way of obtaining `pygame` or work without `pygame`.

**Comment by jamiesnape** [comment]
> @drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-python3-release
> please

Backticks don't actually defeat Jenkins...

**Comment by jwnimmer-tri** [comment]
Yup, TIL :(.  Luckily(?) it died after a minute anyway because TANSTA python3-pygame.

**Comment by peteflorence** [comment]
Hi everybody, so do we think it’s okay to do the same thing as the automotive/steering_command_driver.py? If you look lower down in the file, it just exits if it can’t find pygame
@jamiesnape @jwnimmer-tri

And thanks @sammy-tri, many good comments, and they basically all apply to the slider teleop demo as well so I can fix those too

**Comment by jwnimmer-tri** [comment]
For my part, I would be okay if the `end_effector_teleop_mouse` landed on master with a disclaimer that it only works on python2 on Ubuntu + an error message if the user tries to run it on Ubuntu with python3 anyway.  In a year(?) from now when we drop support for python2 we'll have to remove the program if nobody steps up to upgrade it to python3, but we can cross that bridge when we come to it.  There's every chance someone gets python3-pygame working in Drake in the meantime.

**Comment by peteflorence** [comment]
For what it's worth, I did try out a couple other Python options for mouse + keyboard interfacing, but in my experience, they were not as fully featured as `pygame`.  For example, `PyUserInput`[ cannot decipher whether or not the mouse wheel is going up or down](https://github.com/SavinaRoja/PyUserInput/issues/10), which is limiting. :)

**Comment by peteflorence** [comment]
@RussTedrake yes can do today!

**Comment by peteflorence** [comment]
Yes just pushed!
There is conflict though too so will need to rebase

**Comment by peteflorence** [comment]
- @jamiesnape, I'm not sure how this differs from automotive example (https://github.com/RobotLocomotion/drake/blob/9efae87938866402ab9fb8e3c3a1a1eba8dd651a/automotive/steering_command_driver.py#L268) but I don't know what exactly the test is
- removed python3-pygame from packages-bionic

**Comment by peteflorence** [comment]
Thanks @RussTedrake 

And yes @sammy-tri sorry I had been looking at a different file when trimming python imports!

Should we squash this PR into one commit when merging?
Alternatively, I could go squash on my fork, so this PR looks like only one commit?

**Comment by peteflorence** [comment]
Woohoo!! The finish line seems upon us?
Sorry all that took a while, I got lost in RLG Group Meeting prep last week.

**Pull request merged**
