### PR TITLE
[parsing] Provide name suggestions when dmd frames have typos

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
+@rpoyner-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19154)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19154#-:-NSNVIDx2Z3RggE-s5At:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
looks like one other test needs fixing...

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19154#-:-NSNVjDVCHKGkTBHrXM4:b-f246a6)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19154)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: Nice to catch up with the plant aesthetics now that the plant aesthetics are nice :-)

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19154#-:-NSfYreoCq5MPBkoxQ9w:brya47f)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
