### PR TITLE
Fixes #5745 ("Request to remove lane length restriction in DrawLaneArrow").

### LINKED ISSUE #5745: Request to remove lane length restriction in DrawLaneArrow
There is a restriction in [DrawLaneArrow](https://github.com/RobotLocomotion/drake/blob/master/drake/automotive/maliput/utility/generate_obj.cc#L413) on generate_obj.cc, which requires the lane to have a minimum length (from what I've seen this is to make sure you can fit the two triangles used to depict the lane direction). This restriction becomes quite difficult to meet when dealing with arbitrary road network geometries, so I was wondering if it could be removed. Below there are two examples that I bumped into and I think should be valid, but fail to pass that assertion (note: I generated the obj files for these by commenting out that `DRAKE_DEMAND` line):

1-sharparc

2-sroad

### PR DESCRIPTION
**Pull request by maddog-tri**
Fixes #5745 ("Request to remove lane length restriction in DrawLaneArrow").

The "lane length restriction" is actually an assertion ensuring that
`DrawLaneArrow()` is not being asked to draw an arrow which pokes out beyond
the end of the lane.   The caller (`MarkLaneEnds()`) does in fact try to
calculate parameters which avoid that --- but apparently numeric precision
issues in `double` arithmetic can cause the assertion to be violated.

Solution:  nudge arrows inwards by `linear_tolerance()` of the `RoadGeometry`,
which provides plenty of buffer to avoid precision issues.

Also:  create a unit-test (based on @basicNew's test case) which exercises the failure.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5768)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature-review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-:-Kh9IAAPxMc-IglxOT9J:b-2n5opl)*

**Comment by jwnimmer-tri** [comment]
I will volunteer for platform review, once feature is complete.

**Comment by liangfok** [comment]
Feature review complete. Just one question.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 524 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-Kh9Z7sa7gQTAdhlJ24j:-Kh9Z7sa7gQTAdhlJ24k:bqwo164) ([raw file](https://github.com/robotlocomotion/drake/blob/db97085fc7dae0fdc80846c608b8a7042b8a34f9/drake/automotive/maliput/utility/generate_obj.cc#L524)):*
> ```cpp
>   // the ends of the lanes by the RoadGeometry's linear_tolerance().
>   const double nudge =
>       lane->segment()->junction()->road_geometry()->linear_tolerance();
> ```

Should we lower bound `nudge` to protect against the user selecting a linear tolerance of zero?

---

*[drake/automotive/maliput/utility/test/generate_urdf_test.cc, line 105 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-Kh9ZaAtevGACn2OPwet:-Kh9ZaAtevGACn2OPweu:b-cuaaag) ([raw file](https://github.com/robotlocomotion/drake/blob/db97085fc7dae0fdc80846c608b8a7042b8a34f9/drake/automotive/maliput/utility/test/generate_urdf_test.cc#L105)):*
> ```cpp
> )R", actual_urdf_contents);
> 
>   // spruce is retarded: it has no functionality for reading/walking a
> ```

BTW, I believe `tinydir.h` has this functionality: https://github.com/RobotLocomotion/drake/tree/master/drake/thirdParty/bsd/tinydir 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-:-Kh9_NhZONrJ-QHY2UpV:b-vm6sci)*

**Comment by jwnimmer-tri** [comment]
:lgtm: platform

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-:-Kh9iDb4L3r-Hz9SuRh1:bcpz082)*

**Comment by maddog-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/maliput/utility/generate_obj.cc, line 524 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-Kh9Z7sa7gQTAdhlJ24j:-Kh9jUfNWyho6IOd4nsx:b-pil6pt) ([raw file](https://github.com/robotlocomotion/drake/blob/db97085fc7dae0fdc80846c608b8a7042b8a34f9/drake/automotive/maliput/utility/generate_obj.cc#L524)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Should we lower bound `nudge` to protect against the user selecting a linear tolerance of zero?
</blockquote></details>

I would say "Neah", since setting the linear tolerance to zero ("Everything about this RoadGeometry is _exact_ and it should be operated on exactly.") is a generally foolhardy thing to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5768)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5768#-:-Kh9kjXKqMA_IZPBEupK:bnfp4nl)*

**Pull request merged**
