### PR TITLE
update director external and enable USE_DRAKE in director build

### PR DESCRIPTION
**Pull request by patmarion**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3900)

### CODE REVIEW

**Comment by patmarion** [comment]
@jamiesnape this PR is waiting on CI updates to run director tests.  Just wanted to check in to see how it's going, thanks!

**Comment by jamiesnape** [comment]
@mwoehlke-kitware and @billhoffman are working on it now.

**Comment by mwoehlke-kitware** [comment]
See also https://github.com/RobotLocomotion/drake-ci/pull/32.

**Comment by patmarion** [comment]
@drake-jenkins-bot retest this please

**Comment by patmarion** [comment]
@sammy-tri for feature review
@jwnimmer-tri for platform review

thanks!  I don't think there's much to review here.  CI builds are passing.  This is bumping the director external and enabling the USE_DRAKE switch on director (so that director libs link with drake).  There isn't any visible change to end users of drake-visualizer.

**Comment by jwnimmer-tri** [comment]
@patmarion To assign, please either say "+@jwnimmer-tri" in the mention, or use the "Assignees" widget on the right.  Just naming me only sends an email; it doesn't put it into the review queue.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3900#-:-KV5eJ0jwRpkWOgpgJI1:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:  Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3900#-:-KV5l1_ASzQmhVKvk8Ni:b-e7bejd)*

**Pull request merged**
