### PR TITLE
Fix Wunused-parameter in bead_on_a_wire and rod2d

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6033)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@edrumwri for feature review, please.  This repairs unused parameters using the guidelines in [drake::unused's documentation](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0).

**Comment by edrumwri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6033#-:-KjKxB1iwal2klKQQFIL:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6033#-:-KjOBM7tcQinF42wVfkU:bnfp4nl)*

**Pull request merged**
