### PR TITLE
[GcsTrajOpt] Add Edges accessor to EdgesBetweenSubgraphs

### PR DESCRIPTION
**Pull request by RussTedrake**
+@wrangelvid for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504)

### CODE REVIEW

**Review by wrangelvid — COMMENTED** [review]
Awesome! I just added a minor comment :lgtm: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-:-NzT4WQp2ydkjw58490N:b8nzd3d)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 406 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-NzT3VvB2n9xDOmLeVvE:-NzT3VvCCEkZ_qRUEt5b:bknowke) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ddaeaf3ba3c1bb805717052dfd866a1594395c0/planning/trajectory_optimization/gcs_trajectory_optimization.h#L406)):*
> ```objc
>     }
> 
>     /** Returns pointers to the edges stored in the subgraph.
> ```

These are not the edges stored in the subgraph, but rather directed edges between two subgraphs. Ditto above.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 406 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-NzT3VvB2n9xDOmLeVvE:-NzoVtDx0ZLhC3OUBD2n:b-yotv5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ddaeaf3ba3c1bb805717052dfd866a1594395c0/planning/trajectory_optimization/gcs_trajectory_optimization.h#L406)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

These are not the edges stored in the subgraph, but rather directed edges between two subgraphs. Ditto above.
</blockquote></details>

Done.  For completeness, I've actually also added the Edges accessor for the subgraphs.

**Review by RussTedrake — COMMENTED** [review]
+@jwnimmer-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-:-O-WX3IXCd7IVi9eX_sE:b-ruv0ff)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504)* status: LGTM missing from assignee jwnimmer-tri(platform)

___
*[`planning/trajectory_optimization/gcs_trajectory_optimization.h` line 406 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-NzT3VvB2n9xDOmLeVvE:-O-X1qdL3SQWQbvdkaqY:bccpe8g) ([raw file](https://github.com/RobotLocomotion/drake/blob/3ddaeaf3ba3c1bb805717052dfd866a1594395c0/planning/trajectory_optimization/gcs_trajectory_optimization.h#L406)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  For completeness, I've actually also added the Edges accessor for the subgraphs.
</blockquote></details>

Awesome.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-:-O-bx1d_2vyPfSz7rhol:b-vtj4vo)* status: 1 unresolved discussion

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 273 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-O-bwM10Eyxn5ljFB2Bv:-O-bwM10Eyxn5ljFB2Bw:b98rwlm) ([raw file](https://github.com/RobotLocomotion/drake/blob/1d5866fd39f0bf96ddd4eec7015beb96840ffb58/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L273)):*
> ```cpp
>   }
> 
>   {  // Confirm that the const accessor returns the same vertices.
> ```

Manual container looping in a test is generally a bad smell.  In this case, there is a much more concise (readable) way to write this:

```c++
  {  // Confirm that the const accessor returns the same vertices.
    const auto& const_scooter_regions = scooter_regions;
    EXPECT_THAT(const_scooter_regions.Vertices(),
                testing::ElementsAreArray(scooter_regions.Vertices()));
  }
```

It also needs `#include <gmock/gmock.h>` atop the file.

Ditto for all of the const-overload test cases in this file that are new in this PR.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),wrangelvid

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 273 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21504#-O-bwM10Eyxn5ljFB2Bv:-O-jLyrQ4Q2K92B7aXFi:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1d5866fd39f0bf96ddd4eec7015beb96840ffb58/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L273)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Manual container looping in a test is generally a bad smell.  In this case, there is a much more concise (readable) way to write this:

```c++
  {  // Confirm that the const accessor returns the same vertices.
    const auto& const_scooter_regions = scooter_regions;
    EXPECT_THAT(const_scooter_regions.Vertices(),
                testing::ElementsAreArray(scooter_regions.Vertices()));
  }
```

It also needs `#include <gmock/gmock.h>` atop the file.

Ditto for all of the const-overload test cases in this file that are new in this PR.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21504)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),wrangelvid

**Pull request merged**
