### PR TITLE
[geometry] Unbundle glTFs before sending to Meshcat

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This substantially improves loading times for large files.

Towards #19598.

- [x] Requires #20876.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_internal.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpurAO5DShEE8yvtr0z:-NpurAO6DxQo6wdcCK0R:b-mk61r) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae87ca45ea079d9e03c5d27ab3f7f67eb301afaf/geometry/meshcat_internal.cc#L162)):*
> ```cpp
>   }
>   if (edited) {
>     *gltf_contents = gltf.dump();
> ```

Working

Is nlohmann output deterministic?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[`geometry/meshcat_internal.cc` line 162 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpurAO5DShEE8yvtr0z:-Npv4XML48p5NRJGkcx6:bxv5kul) ([raw file](https://github.com/RobotLocomotion/drake/blob/ae87ca45ea079d9e03c5d27ab3f7f67eb301afaf/geometry/meshcat_internal.cc#L162)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Is nlohmann output deterministic?
</blockquote></details>

Done.

Yes, per https://json.nlohmann.me/features/object_order/ by default it's a std::map so the output should be reasonably consistent.  The formatting for floating-point types might change when we upgrade nlohmann (https://github.com/nlohmann/json/discussions/2526) but for any given version pin it should be deterministic.

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

+@SeanCurtis-TRI please give this a quick "sniff test" to make sure the design seems unobjectionble.

Then we can tag Grant for platform tomorrow.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Seems reasonable to me.

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-:-NpvNnwM6u7BGID4Rng-:b-h69u49)* status: 4 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 266 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKJA34sdlh2kh2TCc:-NpvKJA34sdlh2kh2TCd:b-9b7dml) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L266)):*
> ```cpp
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(MeshcatShapeReifier);
> 
>   explicit MeshcatShapeReifier(
> ```

nit No longer necessary.



_Code quote:_
```cpp
explicit 
```
___
*[`geometry/meshcat_internal.h` line 57 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvL7Rq5RIYRy4qqy0k:-NpvL7Rq5RIYRy4qqy0l:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat_internal.h#L57)):*
> ```objc
> them. Meshcat is MUCH slower at loading bundled assets compared to unbundled.
> 
> When glTF file has relative path URIs (i.e., unbundled files on disk), this
> ```

nit: typo



_Suggestion:_
```objc
When a glTF
```
___
*[`geometry/meshcat_internal.h` line 58 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvLD2HEmc8uz8GuD3_:-NpvLD2HEmc8uz8GuD3a:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat_internal.h#L58)):*
> ```objc
> 
> When glTF file has relative path URIs (i.e., unbundled files on disk), this
> loads the files FileStorage so that we can serve them later, even if the
> ```

nit: typo



_Suggestion:_
```objc
files into FileStorage
```
___
*[`geometry/meshcat_internal.h` line 62 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvLfgdE9rOZ7yj9O3h:-NpvLfgdE9rOZ7yj9O3i:bn2msma) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat_internal.h#L62)):*
> ```objc
> 
> @param[in] gltf_filename The glTF filename, used to calculate relative paths.
> @param[in,out] gltf_contents The glTF data already loaded from `gltf_filename`.
> ```

nit; I think you mean "glTF file contents" as something to contrast with "glTF data" which would be the form that is stored in memory (e.g., decoded mesh data), right?



_Code quote:_
```objc
glTF data
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat_internal.h` line 62 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvLfgdE9rOZ7yj9O3h:-NpvQyfv3EX9nNijPf5O:b-supikp) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat_internal.h#L62)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit; I think you mean "glTF file contents" as something to contrast with "glTF data" which would be the form that is stored in memory (e.g., decoded mesh data), right?
</blockquote></details>

I tried to rephrase it a bit for clarity.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKRyi535IDMJYqSB2:-NpvKRyi535IDMJYqSB3:bdlxq1q) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L382)):*
> ```cpp
>       }
>     } else if (format == "gltf") {
>       assets_ =
> ```

BTW It seems that we'd want to explain why we're locally overriding this parameter from the constructor. That seems a bit odd.
___
*[`geometry/meshcat_internal.h` line 62 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvLfgdE9rOZ7yj9O3h:-NpygOD13mH78d9Oa71z:b-wks87u) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat_internal.h#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I tried to rephrase it a bit for clarity.
</blockquote></details>

Very clear.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKRyi535IDMJYqSB2:-NpyoZ0U6g7kTSUrVkXD:b7lsrfw) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L382)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It seems that we'd want to explain why we're locally overriding this parameter from the constructor. That seems a bit odd.
</blockquote></details>

I'm not sure what you mean.  Are you saying we could envision the `assets_` as `[in,out]` instead of just `[out]`, so we should append to it here instead of overwriting it?  (Maybe I could add Doxygen to the constructor to clarify what's going on?)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKRyi535IDMJYqSB2:-Npz1KCx1Qz38BjysmAW:b-bfj6hi) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L382)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure what you mean.  Are you saying we could envision the `assets_` as `[in,out]` instead of just `[out]`, so we should append to it here instead of overwriting it?  (Maybe I could add Doxygen to the constructor to clarify what's going on?)
</blockquote></details>

Clarification is key. You contrast `[in,out]` and `[out]`, but there is, of course, no documentation to either extent. It stands in *particular* contrasts to its adjacent parameter, `file_storage` which is definitely `[in,out]`.

Documenting the semantics is minimally sufficient.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKRyi535IDMJYqSB2:-Npz3Jza3x_Ly2MfBY_S:b-my0iv4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L382)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Clarification is key. You contrast `[in,out]` and `[out]`, but there is, of course, no documentation to either extent. It stands in *particular* contrasts to its adjacent parameter, `file_storage` which is definitely `[in,out]`.

Documenting the semantics is minimally sufficient.
</blockquote></details>

Working

Right, the problem is it's really a new addition to the return value, and instead of refactoring the reifier stuff to admit as much, I hacked it into the constructor.  I'll work on refactoring the reifier to "return" more than one value.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

___
*[`geometry/meshcat.cc` line 382 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-NpvKRyi535IDMJYqSB2:-Npz7F5-D5iUTHyYwW1R:bdszso4) ([raw file](https://github.com/RobotLocomotion/drake/blob/c3f3d43ff772838f1ff45091aa22186d5e439b07/geometry/meshcat.cc#L382)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Right, the problem is it's really a new addition to the return value, and instead of refactoring the reifier stuff to admit as much, I hacked it into the constructor.  I'll work on refactoring the reifier to "return" more than one value.
</blockquote></details>

Yup, much clearer now.  Now we have consistency:

- the long-lived helper tools are constructor arguments,
- the shape details are the ImplementGeometry argument,
- the reification result is the reify output argument.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 12 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-:-Nq-GKIV11AndDe03VJk:bnfp4nl)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 12 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-:-Nq-xFn-CdxBhfRnd7i9:bnfp4nl)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`geometry/meshcat_file_storage_internal.cc` line 138 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-Nq-cBRsDboZhladvMzf:-Nq-cBRsDboZhladvMzg:blh9x83) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dcd806f8b28d90206e4ab2e48468d57de84ceed/geometry/meshcat_file_storage_internal.cc#L138)):*
> ```cpp
>   // not contain a subdirectory (i.e., no "/" characters) because that confuses
>   // any assets that refer to sub-assets.
>   return fmt::format("cas-v1-{}", asset.sha256.to_string());
> ```

BTW, what does "v1? mean here?



_Code quote:_
```cpp
cas-v1
```
___
*[`geometry/meshcat_internal.cc` line 98 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-Nq-otT94ttTWKk06xhB:-Nq-otT94ttTWKk06xhC:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dcd806f8b28d90206e4ab2e48468d57de84ceed/geometry/meshcat_internal.cc#L98)):*
> ```cpp
>       return nullptr;
>     }
>     // TODO(jwnimer-tri) Save the media type to http-serve later on.
> ```

typo



_Suggestion:_
```cpp
// TODO(jwnimmer-tri) Save the media type to http-serve later on.
```
___
*[`geometry/meshcat_internal.cc` line 100 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-Nq-p93t5vfBWQhC40C0:-Nq-p93t5vfBWQhC40C1:b-cklff6) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dcd806f8b28d90206e4ab2e48468d57de84ceed/geometry/meshcat_internal.cc#L100)):*
> ```cpp
>     // TODO(jwnimer-tri) Save the media type to http-serve later on.
>     // For now, we'll just skip ahead to the actual content.
>     std::string_view base64_content = uri.substr(pos + 8);
> ```

BTW, what is the magic number 8?



_Code quote:_
```cpp
std::string_view base64_content = uri.substr(pos + 8);
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20877)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`geometry/meshcat_internal.cc` line 100 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20877#-Nq-p93t5vfBWQhC40C0:-Nq0Wh_zEyqfXGeLl4Vw:b98f7p9) ([raw file](https://github.com/RobotLocomotion/drake/blob/7dcd806f8b28d90206e4ab2e48468d57de84ceed/geometry/meshcat_internal.cc#L100)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, what is the magic number 8?
</blockquote></details>

Replaced with a more meaningful constant expression.

**Pull request merged**
