### PR TITLE
Group cross product

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is the first PR to clean `drakeGeometryUtil`. This PR contains three changes

1. Put the constants such as `SPACE_DIMENSION` into `drake/common/constants`.
2. Pull the functions to generate random orientation into a separate file `drake/math/random_orientation.h`
3. Pull the functions on cross product into `drake/math/cross_product.h`.

I would expect subsequent PRs to continue clean up `drakeGeometryUtil`. Like this PR, it would make following changes.

1. If a function is dead (like `dcrossProduct`), then delete it.
2. If a function should continue to live, then pull it out to a separate file; deprecate the function in `drakeGeometryUtil`.
3. Write a test function (`cross_product_test` in this PR).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3441)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
The test failure was a Windows issue. +@jwnimmer-tri for feature review, and +@david-german-tri for platform review

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KR_mnByOvTsO5yC84TW:b-hn4mmy)*

**Comment by jwnimmer-tri** [comment]
Looks good on a very quick skim.  I will make some time later this evening to give it a good study.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KR_stZVvphg7fVAIPn1:b1o0e73)*

**Comment by jwnimmer-tri** [comment]
Very close to being ready.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[drake/common/constants.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KR_vr1nmytJLvABQTgb:-KR_vr1o4EIPqBVmlRaS:b-t7req9) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/common/constants.h#L14)):*
> ```objc
> constexpr int kTwistSize = 6;
> 
> constexpr int kHomogeneousTransform = 16;
> ```

Perhaps to be consistent this should be `kH...TransformSize` (adding the `Size`)?

---

*[drake/math/cross_product.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa8PajqzVEMLiuOOEx:-KRa8PajqzVEMLiuOOEy:b9orl83) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/cross_product.h#L6)):*
> ```objc
> 
> #include "drake/common/constants.h"
> #include "drake/math/gradient.h"
> ```

Unused, I think?

---

*[drake/math/cross_product.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa8qxmfLx01Yd1tTTc:-KRa8qxmfLx01Yd1tTTd:bkgl4vi) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/cross_product.h#L11)):*
> ```objc
> namespace math {
> template <typename Derived>
> Eigen::Matrix<typename Derived::Scalar, 3, 3> VectorToSkewSymmetric(
> ```

BTW `Matrix3<typename Derived::Scalar>` from `drake/common/eigen_types.h` would be slightly shorter than `Eigen::Matrix<typename Derived::Scalar, 3, 3>` -- here and in the `ret` type below.

---

*[drake/math/random_rotation.h, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa7ajhwWozQMme9D-D:-KRa7ajiVwBnXccXHzcl:bxshe7z) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L4)):*
> ```objc
> 
> #include <Eigen/Dense>
> #include <cmath>
> ```

Unused (by this header)?

---

*[drake/math/random_rotation.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5X1sUjAEEHRRcd_2:-KRa5X1sUjAEEHRRcd_3:br8tae1) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L5)):*
> #include <cmath>
> #include <random>

These two system includes should precede the Eigen include, with a blank line inbetween the two groups.
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/math/random_rotation.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5m1HW8I3gc_00PV6:-KRa5m1Id_grLQ_A1qL4:b9orl83) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L10)):*
> ```objc
> #include "drake/common/eigen_types.h"
> #include "drake/drakeMath_export.h"
> #include "drake/math/quaternion.h"
> ```

Unused, I think?

---

*[drake/math/random_rotation.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5I3gTAPoVb9rHKtV:-KRa5I3hUrvoE5buKQwx:b-429dui) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L15)):*
> ```objc
> namespace math {
> DRAKEMATH_EXPORT Eigen::Vector4d UniformlyRandomAxisAngle(
>     std::default_random_engine& generator);
> ```

FYI (no action required) In new code I would prefer `std::mt19937` or some other generator whose output is toolchain-independent, but for a cleanup PR it's fine to stick with the `default_random_engine` (and non-const reference arguments!) and live with some platform-to-platform variance; it will still be consistent within a platform.

---

*[drake/math/test/cross_product_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa9o-2baFjpnzwpZPH:-KRa9o-2baFjpnzwpZPI:bonlsrz) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/test/cross_product_test.cc#L18)):*
> ```cpp
>   auto x_skew_mat = VectorToSkewSymmetric(x);
>   EXPECT_TRUE(CompareMatrices(x_skew_mat_expected, x_skew_mat, 1E-10,
>                               MatrixCompareType::absolute));
> ```

This test doesn't seem super-useful to me, as it just repeats the implementation.

Suggestion -- what about instead testing:
- a few specific literal values, e.g., that (1, 2, 3) turns into ((0 -3 2) (2 3 0) (-1 -2 0)) or whatever it is, by writing a sample or two out fully;
- the `$-A = A_T$` property of the result -- or alternative, or additional properties that relate to the purpose of the transformation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRaBHPbhB_qNxiiXi3C:b-10kon0)*

**Comment by hongkai-dai** [comment]
Thank @jwnimmer-tri for the review!

---

Review status: 11 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/constants.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KR_vr1nmytJLvABQTgb:-KRaHWS9aYm-zQkYUZod:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/common/constants.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Perhaps to be consistent this should be `kH...TransformSize` (adding the `Size`)?
</details>
Done.

---

*[drake/math/cross_product.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa8PajqzVEMLiuOOEx:-KRaHYbANL9TknmAyXeT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/cross_product.h#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think?
</details>
Done.

---

*[drake/math/cross_product.h, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa8qxmfLx01Yd1tTTc:-KRaH_4ZD4w3U0AsLsAB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/cross_product.h#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW `Matrix3<typename Derived::Scalar>` from `drake/common/eigen_types.h` would be slightly shorter than `Eigen::Matrix<typename Derived::Scalar, 3, 3>` -- here and in the `ret` type below.
</details>
Done.

---

*[drake/math/random_rotation.h, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa7ajhwWozQMme9D-D:-KRaHbz5dr80pviLZS4o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused (by this header)?
</details>
Done.

---

*[drake/math/random_rotation.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5X1sUjAEEHRRcd_2:-KRaHcN4JEyDwGRuTFnQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> > #include <cmath>
> > #include <random>
> 
> These two system includes should precede the Eigen include, with a blank line inbetween the two groups.
> https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</details>
Done.

---

*[drake/math/random_rotation.h, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5m1HW8I3gc_00PV6:-KRaHeBerY8qb3m3Iw7Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused, I think?
</details>
Done.

---

*[drake/math/random_rotation.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa5I3gTAPoVb9rHKtV:-KRaHh7FzrjSEV3VPh6y:bw4wi54) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/random_rotation.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI (no action required) In new code I would prefer `std::mt19937` or some other generator whose output is toolchain-independent, but for a cleanup PR it's fine to stick with the `default_random_engine` (and non-const reference arguments!) and live with some platform-to-platform variance; it will still be consistent within a platform.
</details>
Done. Will address this in the future PR.

---

*[drake/math/test/cross_product_test.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KRa9o-2baFjpnzwpZPH:-KRaHli3uOn9czwdyQJU:b95z43a) ([raw file](https://github.com/robotlocomotion/drake/blob/81db93539102cca9f2690bf7bf6f159c4ec775dc/drake/math/test/cross_product_test.cc#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This test doesn't seem super-useful to me, as it just repeats the implementation.
> 
> Suggestion -- what about instead testing:
> - a few specific literal values, e.g., that (1, 2, 3) turns into ((0 -3 2) (2 3 0) (-1 -2 0)) or whatever it is, by writing a sample or two out fully;
> - the `$-A = A_T$` property of the result -- or alternative, or additional properties that relate to the purpose of the transformation.
</details>
Thanks for the comment. The reason to put this test is to make sure that the `VectorToSkewSymmetric` gives the right answer, even if it might use a different representation (for example, it can return a sparse skew symmetric matrix, in stead of a dense one.)

I think with the three tests (1,0,0), (0,1,0) and (0,0,1), it already guarantees that the skew symmetric matrix is correct, for whatever input. Since the transform from the vector to the skew-symmetric matrix is a linear transform, with 3 degrees of freedom. These three tests should be sufficient.

I like the idea on checking the skew symmetric property. I added that already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRaHOsWQZQ6D-lcTSnL:bt64qcb)*

**Comment by jwnimmer-tri** [comment]
Feature :lgtm:.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRaJOvbfekorSuyXDw6:b-37uu31)*

**Comment by hongkai-dai** [comment]
Some of the functions are not used in either drake or openhumanoids, may I delete them, instead of deprecating them?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRaKd2JdJNuq3poDrU3:b13s3v3)*

**Comment by jwnimmer-tri** [comment]
#3404 was one example where deleting code was undesirable.  I personally don't have a great sense of what code should be kept even without an immediate use.

It it helps consider the problem, we can keep the `drake/matlab/util/drakeFooUtil.h` files around with the possibly-dead or deprecated code within it (relocating them out of `drake/util`); the purpose of PRs like this one as they relate to #3414 is that we don't want _Drake C++_ libraries to use `drake/util` anymore, so we need to change the _call sites_ more than we need to change the _util directory itself_.

That all being said, I think absent any specific requests to keep (and test) things, deleting code that lacks unit tests should be a generally accepted practice.  Git remembers, in case we want it back later.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRaLP5RBUBbtBJWg6Q-:bsein0l)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
> deleting code that lacks unit tests should be a generally accepted practice
 :+1:

Starting review now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KReH0PdQ4YZt1o1LdL9:bxu82mo)*

**Comment by david-german-tri** [comment]
:lgtm:

The Windows test failure looks like infrastructure noise, but it killed the build early so you'll need to retest.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/common/constants.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReHGDqr2JWO6IBmCyS:-KReHGDqr2JWO6IBmCyT:bprg60n) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d762f077465ac16a102b01257c2c5d79ffc08f/drake/common/constants.h#L14)):*
> ```objc
> constexpr int kTwistSize = 6;
> 
> constexpr int kHomogeneousTransformSize = 16;
> ```

BTW, consider adding a citation as for `kTwistSize` above.

---

*[drake/math/test/cross_product_test.cc, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReHuOd2g5r6KZKO4Nj:-KReHuOd2g5r6KZKO4Nk:bb6musu) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d762f077465ac16a102b01257c2c5d79ffc08f/drake/math/test/cross_product_test.cc#L13)):*
> ```cpp
> namespace math {
> namespace {
> void SkewSymMatTestFun(const Vector3d& x) {
> ```

This could use some kind of comment explaining what is being asserted.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KReIE9UO9da0yGHWuyL:b-uduwc8)*

**Comment by hongkai-dai** [comment]
Thank @david-german-tri for the review!

---

Review status: 13 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/constants.h, line 14 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReHGDqr2JWO6IBmCyS:-KReSKr9OPnCOpyNPDG0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d762f077465ac16a102b01257c2c5d79ffc08f/drake/common/constants.h#L14)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, consider adding a citation as for `kTwistSize` above.
</details>
Done.

---

*[drake/math/test/cross_product_test.cc, line 13 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReHuOd2g5r6KZKO4Nj:-KReSNrZQTSiZ6TqgeGj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d762f077465ac16a102b01257c2c5d79ffc08f/drake/math/test/cross_product_test.cc#L13)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This could use some kind of comment explaining what is being asserted.  
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KReSOoR9ODwZBSCwBiL:b-c496pn)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/test/cross_product_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReSYQiC5ocEPsH6XlN:-KReSYQiC5ocEPsH6XlO:b-jb203v) ([raw file](https://github.com/robotlocomotion/drake/blob/c95bf0cc09447571ff912a3a2bfa212f5b9ef4c3/drake/math/test/cross_product_test.cc#L14)):*
> ```cpp
> namespace {
> void SkewSymMatTestFun(const Vector3d& x) {
>   // manually computes the skew symmetric matrix.
> ```

BTW Sentences must the capitalized correctly.

---

*[drake/math/test/cross_product_test.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReSa5VSdAENsnUjaTm:-KReSa5VSdAENsnUjaTn:bar7y03) ([raw file](https://github.com/robotlocomotion/drake/blob/c95bf0cc09447571ff912a3a2bfa212f5b9ef4c3/drake/math/test/cross_product_test.cc#L20)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(x_skew_mat_expected, x_skew_mat, 1E-10,
>                               MatrixCompareType::absolute));
>   // checks the skew-symmetric property A' = -A
> ```

BTW Sentences must the capitalized and punctuated correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441)*

**Comment by hongkai-dai** [comment]
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/test/cross_product_test.cc, line 14 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReSYQiC5ocEPsH6XlN:-KReTRqnRiGphbFxuVv2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c95bf0cc09447571ff912a3a2bfa212f5b9ef4c3/drake/math/test/cross_product_test.cc#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Sentences must the capitalized correctly.
</details>
Done.

---

*[drake/math/test/cross_product_test.cc, line 20 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-KReSa5VSdAENsnUjaTm:-KReTRaJojx41F5A_oFs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c95bf0cc09447571ff912a3a2bfa212f5b9ef4c3/drake/math/test/cross_product_test.cc#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW Sentences must the capitalized and punctuated correctly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot windows-msvc-ninja-32-experimental please

---

Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRe_6vavm3rD8NGdCeI:b-p3vbpg)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please

---

Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441#-:-KRe_WNZ57Ydp6R8WevI:bzdwe9o)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3441)*

**Pull request merged**
