### PR TITLE
py mbp: Make SpatialVector's default constructor initialize to NaN

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards #14086

Intermediate version of #14087

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for feature review, please.
+@jwnimmer-tri for platform review, please.

This targets Python-only, where I'd say consistency in user API is wayyy more important than minor performance gains.
The drawback to this is inconsistency with C++. However, that is made obvious by the docstring.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096#-:-MHasssFDQ65P79_DABT:b8yj1lp)* status: LGTM missing from assignees sherm1(platform),jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
I agree that performance is not an issue for the Python API use of this class. But why do you want to initialize this to zero rather than NaN? Zero has the appearance of a legitimate velocity/acceleration/force/momentum and would hide a failure to set the vector to anything meaningful. Note that Drake C++ already initializes to NaN, but only in Debug -- the comment could then just say that Python does it unconditionally. Here you are changing the semantics to define a particular value of these quantities.

RigidTransform and RotationMatrix are mathematical objects with enforced invariants, for example that the rotation matrix consists of three orthogonal columns of unit length with determinant +1. It is not possible to leave those uninitialized while claiming that they implement the appropriate abstractions. That is not so with SpatialVelocity and the like -- they are physical quantities and there is an unenforced expectation that if they contain anything it is a quantity of the appropriate type. NaN indicates correctly that no such quantity has been assigned; zero hides that.

I would support initialization of SpatialVector to NaN in Python and would prefer that in C++ also if we didn't have to be so concerned with performance there. I do not support setting it to zero anywhere since I think that can hide failure to appropriately assign values, leading to bad answers. Bad-but-plausible-looking answers are the worst possible outcome from a numerical code. That is the *least* user-friendly feature possible in a numerical API -- initializing to zero is therefore a step in the wrong direction; initializing to NaN would be an improvement.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096#-:-MHcoLOBECCgVKujAZKg:bu4uyof)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/multibody/math_py.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHcrtbuC-aceTHYNLBo:-MHcrtbuC-aceTHYNLBp:bw058c9) ([raw file](https://github.com/robotlocomotion/drake/blob/4e395836a4ef9a95712e134cca21bb48f93e81fa/bindings/pydrake/multibody/math_py.cc#L26)):*
> ```cpp
>   cls  // BR
>       .def(py::init([]() { return Class::Zero(); }), R"""(
>       Constructs to all zeros.
> ```

Please consider initializing to NaN instead.

**Comment by jwnimmer-tri** [comment]
I wasn't sure about the pydrake-only zeros change as originally proposed here (I was still thinking it through), but I could get behind initializing to NaN in pydrake.  Having pydrake in both Debug and Release match what C++ does in Debug mode seems unobjectionable and at least improves on the non-determinism front.

**Comment by EricCousineau-TRI** [comment]
Aye, I'm convinced that purely initializing to `NaN` in Python is strictly better than the current state, and `Zero` is sketchy in terms of deviating from C++.

I'm still mulling over the "physical quantities without invariants should be NaN", but will address that in the upstream issue.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[bindings/pydrake/multibody/math_py.cc, line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHcrtbuC-aceTHYNLBo:-MHlmdDC1dpWPD4Wr5jO:b-896fja) ([raw file](https://github.com/robotlocomotion/drake/blob/4e395836a4ef9a95712e134cca21bb48f93e81fa/bindings/pydrake/multibody/math_py.cc#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Please consider initializing to NaN instead.
</blockquote></details>

Done!

**Review by sherm1 — COMMENTED** [review]
Great, thanks! :lgtm_strong: with a question about NaN==NaN.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096#-:-MHlrOqr2HZ6PjaTr4bG:b-22pc8o)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/math_test.py, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlpBNM5TRNTg6coOdP:-MHlpBNM5TRNTg6coOdQ:bhygk6i) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/test/math_test.py#L33)):*
> ```Python
>                 vec.rotational(), np.full(3, np.nan))
>             numpy_compare.assert_float_equal(
>                 vec.translational(), np.full(3, np.nan))
> ```

BTW in IEEE floating point world `operator==(NaN,NaN)` returns `false`. Does `assert_float_equal()` special case that or are the rules different in numpy? If NaN==NaN is true here, please consider noting that in a comment since it is unusual.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/math_test.py, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlpBNM5TRNTg6coOdP:-MHlsRg99crpxJhaQX2x:bobr5bl) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/test/math_test.py#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW in IEEE floating point world `operator==(NaN,NaN)` returns `false`. Does `assert_float_equal()` special case that or are the rules different in numpy? If NaN==NaN is true here, please consider noting that in a comment since it is unusual. 
</blockquote></details>

OK Yup! It's documented in this function itself:
https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_equal.html

I don't really want to document it here, as it's directly mentioned in the function.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/test/math_test.py, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlpBNM5TRNTg6coOdP:-MHlycKa-8KzkWI0Kixr:b-lbvf88) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/test/math_test.py#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup! It's documented in this function itself:
https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_equal.html

I don't really want to document it here, as it's directly mentioned in the function.
</blockquote></details>

BTW That's numpy's assert_array_equal() but the code here calls assert_float_equal() which is one of ours. Poking around I couldn't convince myself that our function ever calls assert_array_equal(), and ours doesn't say anything about NaNs. Maybe it should?

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096#-:-MHlzohi4Wcl5ovyEie2:b-vtj4vo)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[bindings/pydrake/multibody/math_py.cc, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlyApa7PpORZFIrSdc:-MHlyApa7PpORZFIrSdd:bfw3awv) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/math_py.cc#L51)):*
> ```cpp
>       Note:
>           This is different from C++, which in Release builds may leave memory
>           uninitialized. For more details, see issue #14086.
> ```

FYI My personal preference -- adding issue numbers to implementation comments is helpful for developers who next touch that code, but adding issue numbers in API docs is absurd.  (And this is the second PR today where I've seen it happen, so I'll just toss this out now.)  Asking users to dig through a pile of discussion comments to learn about something is not helpful.  However, this isn't a de jure rule in any guide yet, so not a defect.

If there's something API-relevant, then it should either be summarized here inline, or else have a hyperlink to some website overview (Doxygen, or pydrake, sphinx, etc.), or possibly even link to a source code implementation comment summary.

If the only take-away from the issue is "In pydrake, the function call overhead already trumps any overhead from NAN-initialization, so we'll err on the side of safety." then we can just say that outright.  If you want readers to glean something beyond that from the issue in terms of the API or rationale, best spell it out because I have no idea what you're getting at by citing the issue.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14096)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform)

___
*[bindings/pydrake/multibody/math_py.cc, line 51 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlyApa7PpORZFIrSdc:-MHmYFSh9lVoQL2vL1N-:b-x43y3o) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/math_py.cc#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI My personal preference -- adding issue numbers to implementation comments is helpful for developers who next touch that code, but adding issue numbers in API docs is absurd.  (And this is the second PR today where I've seen it happen, so I'll just toss this out now.)  Asking users to dig through a pile of discussion comments to learn about something is not helpful.  However, this isn't a de jure rule in any guide yet, so not a defect.

If there's something API-relevant, then it should either be summarized here inline, or else have a hyperlink to some website overview (Doxygen, or pydrake, sphinx, etc.), or possibly even link to a source code implementation comment summary.

If the only take-away from the issue is "In pydrake, the function call overhead already trumps any overhead from NAN-initialization, so we'll err on the side of safety." then we can just say that outright.  If you want readers to glean something beyond that from the issue in terms of the API or rationale, best spell it out because I have no idea what you're getting at by citing the issue.
</blockquote></details>

Done. Hoisted issue number to implementation, inlined your suggestion. Thanks!
___
*[bindings/pydrake/multibody/test/math_test.py, line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14096#-MHlpBNM5TRNTg6coOdP:-MHmYJof3CBhLbNMBhfH:b-urihqt) ([raw file](https://github.com/robotlocomotion/drake/blob/d667deae8a6d6504576e37742d0afdf019f80b01/bindings/pydrake/multibody/test/math_test.py#L33)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW That's numpy's assert_array_equal() but the code here calls assert_float_equal() which is one of ours. Poking around I couldn't convince myself that our function ever calls assert_array_equal(), and ours doesn't say anything about NaNs. Maybe it should?
</blockquote></details>

Done. Sorry about that!

**Comment by EricCousineau-TRI** [comment]
Skipping the slow builds

**Pull request merged**
