### PR TITLE
Upgrade externals to latest releases

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Working towards #16301

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16324)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16324#-:-MspDLLb5kBytTWT8ypN:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16324#-:-MsuNtQZ9trTCGceBCBu:b-b5dc06)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
This is ready to merge after a rebase.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16324)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
Lost the race.  Needs another rebase.

**Pull request merged**
