### PR TITLE
Refactor linear programming in convex optimization test

### PR DESCRIPTION
**Pull request by hongkai-dai**
The goal is to have separate test scripts `gurobi_solver_test.cc` and `mosek_solver_test.cc`, as mentioned in https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/BUILD#L233. This is the first step, just refactored the linear programs in `convex_optimization_test`. I will continue to refactor the QP, SOCP and SDP in the test.

This PR exceeds 500 lines. But many of them are existing code, no math is changed.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5122)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@david-german-tri for feature review.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-Kc_dZU_6y-H9PEuEbo8:b-scjx9w)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 9 of 13 files at r1.
Review status: 9 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/BUILD, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-KccaZBdvOKiNq_DaQ3i:-KccaZBehl4VnuHHrYpy:b-h7f73o) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/BUILD#L342)):*
> ```Python
>     srcs = [
>         "test/add_solver_util.cc",
>         "test/add_solver_util.h",
> ```

Rather that repeat these utils in a bunch of `srcs` (which causes them to be recompiled for each), please put them in a separate `drake_cc_library`, set `testonly = 1`, and include that library in the `deps` of the various tests.

---

*[drake/solvers/test/add_solver_util.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccb_OFlt76XXRXLVuU:-Kccb3vYuE8GTOOCTyXQ:b-dk7xdc) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/add_solver_util.cc#L16)):*
> ```cpp
>     std::list<std::unique_ptr<MathematicalProgramSolverInterface>>*
>     solver_list) {
>   std::list<std::unique_ptr<MathematicalProgramSolverInterface>> all_solvers;
> ```

BTW why not just use a `switch` statement  on `solver_type` to set a single `unique_ptr<MPSI>`, then check that ptr for `available()`?  Seems more readable, and also O(N) instead of O(N^2), not that the efficiency really matters.

(Since you're just moving pre-existing code, feel free not to change it in this PR)

---

*[drake/solvers/test/CMakeLists.txt, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccdcwh3C0rlZaieK6I:-Kccdcwh3C0rlZaieK6J:bnw4fbe) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/CMakeLists.txt#L32)):*
> ```CMake
> macro(add_solver_test)
>   add_executable(${ARGV}
>           add_solver_util.cc
> ```

BTW, I don't really care too much about CMake code health at this point, but it seems like you could make a library here too, and then use `drake_add_cc_test`.

---

*[drake/solvers/test/mosek_solver_test.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-KccfJh0rtiYgmVI6yaz:-KccfJh0rtiYgmVI6yb-:bre39ur) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/mosek_solver_test.cc#L16)):*
> ```cpp
>   RunLinearPrograms(solver);
> }
> ```

BTW extra whitespace here

---

*[drake/solvers/test/nonlinear_program_test.cc, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccez6Atuwny-YwpB_V:-Kccez6Atuwny-YwpB_W:b-kg9vk0) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/nonlinear_program_test.cc#L156)):*
> ```cpp
> 
> GTEST_TEST(testNonlinearProgram, testNonConvexQPproblem1) {
>   for (auto cost_form : NonConvexQPproblem1::cost_forms()) {
> ```

BTW META for file: consider `const auto&`.   It doesn't really matter, since this is an enum, but it will be a little less surprising for readers.

---

*[drake/solvers/test/optimization_examples.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccfg7R5vcf3b0YG8jc:-Kccfg7R5vcf3b0YG8jd:b6o5s7r) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L26)):*
> ```cpp
> namespace test {
> 
> static std::set<CostForm> linear_cost_form{CostForm::kNonSymbolic,
> ```

"Variables of class type with static storage duration are forbidden"

Consider either allocating this object with `new`, or making a free function that returns it.

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

---

*[drake/solvers/test/optimization_examples.cc, line 824 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccnt3lCLfTr4U8ApRw:-Kccnt3mhZpUT0mfzfhW:b-2nzd0r) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L824)):*
> ```cpp
>   Eigen::Vector3d b_ub(numeric_limits<double>::infinity(), 5,
>                        numeric_limits<double>::infinity());
>   switch (cnstr_form) {
> ```

BTW Am I correctly understanding that this change adds a lot of coverage for symbolic costs and constraints?  Nice!

---

*[drake/solvers/test/optimization_examples.cc, line 880 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcco2akjLvT32sBR79j:-Kcco2akjLvT32sBR79k:bsmuakx) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L880)):*
> ```cpp
> }
> 
> void RunLinearPrograms(const MathematicalProgramSolverInterface& solver) {
> ```

This approach rolls up a ton of test coverage into one GTest case, which means that failures will not be very diagnostic: future developers will have a hard time determining which program, cost, and constraint form they broke.

To fix this, I'd suggest replacing this function with a value-parameterized base class test fixture.

https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#how-to-write-value-parameterized-tests

For each solver, you'd then have `class MosekLinearProgramTest : public LinearProgramTest`, a single `TEST_P(MosekLinearProgramTest, LinearPrograms, and 

```INSTANTIATE_TEST_CASE_P(AllConfigurations, MosekLinearProgramTest, ::testing::Combine(costs, constraints, problems)```

I know that sounds a little hairy, but I think it's actually a pretty small change from what you already have.  Essentially your `for` loops just become `switch` statements on the params.
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-KccaQQCFTYEfDT85gTX:b-s794vx)*
<!-- Sent from Reviewable.io -->

**Comment by hongkai-dai** [comment]
Review status: 6 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/BUILD, line 342 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-KccaZBdvOKiNq_DaQ3i:-Kcd7beyrA7V7ybmjHe1:bkr124k) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/BUILD#L342)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Rather that repeat these utils in a bunch of `srcs` (which causes them to be recompiled for each), please put them in a separate `drake_cc_library`, set `testonly = 1`, and include that library in the `deps` of the various tests.
</blockquote></details>

Done. Thanks! I did not know we can add a testonly library.

---

*[drake/solvers/test/add_solver_util.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccb_OFlt76XXRXLVuU:-Kcd7yIb5zpIr3qg1TuW:b-xfu7) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/add_solver_util.cc#L16)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW why not just use a `switch` statement  on `solver_type` to set a single `unique_ptr<MPSI>`, then check that ptr for `available()`?  Seems more readable, and also O(N) instead of O(N^2), not that the efficiency really matters.

(Since you're just moving pre-existing code, feel free not to change it in this PR)
</blockquote></details>

I agree, but I am going to remove this file after another one or two PRs (https://github.com/RobotLocomotion/drake/pull/5122/files#diff-d0303f4358e2c08dc7c37920a852a20d), so I did not change this code 

---

*[drake/solvers/test/CMakeLists.txt, line 32 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccdcwh3C0rlZaieK6I:-Kcd8TRbjTHK8hUX37c3:bs7wumx) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/CMakeLists.txt#L32)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I don't really care too much about CMake code health at this point, but it seems like you could make a library here too, and then use `drake_add_cc_test`.
</blockquote></details>

Done. 

---

*[drake/solvers/test/mosek_solver_test.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-KccfJh0rtiYgmVI6yaz:-KcdtqmT1Lyx4CV--C8H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/mosek_solver_test.cc#L16)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW extra whitespace here
</blockquote></details>

Done.

---

*[drake/solvers/test/nonlinear_program_test.cc, line 156 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccez6Atuwny-YwpB_V:-KcduB9qYp_KR1rFbutq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/nonlinear_program_test.cc#L156)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW META for file: consider `const auto&`.   It doesn't really matter, since this is an enum, but it will be a little less surprising for readers.
</blockquote></details>

Done.

---

*[drake/solvers/test/optimization_examples.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccfg7R5vcf3b0YG8jc:-KcdvP-oALDQ2M4GhEvw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L26)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

"Variables of class type with static storage duration are forbidden"

Consider either allocating this object with `new`, or making a free function that returns it.

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
</blockquote></details>

Done.

---

*[drake/solvers/test/optimization_examples.cc, line 824 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kccnt3lCLfTr4U8ApRw:-KcdvQQqYcFrXkEmP6M8:bci6ls4) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L824)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW Am I correctly understanding that this change adds a lot of coverage for symbolic costs and constraints?  Nice!
</blockquote></details>

Done. Yes, that is the purpose, and I actually find bugs in our code with this coverage. Will fix these bugs in my next PR.

---

*[drake/solvers/test/optimization_examples.cc, line 880 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcco2akjLvT32sBR79j:-KceUC6spSsjkw033GAw:bt4ox15) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L880)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This approach rolls up a ton of test coverage into one GTest case, which means that failures will not be very diagnostic: future developers will have a hard time determining which program, cost, and constraint form they broke.

To fix this, I'd suggest replacing this function with a value-parameterized base class test fixture.

https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#how-to-write-value-parameterized-tests

For each solver, you'd then have `class MosekLinearProgramTest : public LinearProgramTest`, a single `TEST_P(MosekLinearProgramTest, LinearPrograms, and 

```INSTANTIATE_TEST_CASE_P(AllConfigurations, MosekLinearProgramTest, ::testing::Combine(costs, constraints, problems)```

I know that sounds a little hairy, but I think it's actually a pretty small change from what you already have.  Essentially your `for` loops just become `switch` statements on the params.
</blockquote></details>

Done. Thanks for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

---

Review status: 6 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-Kcen0KS8EmL8SiVVjxh:bq323eq)*

**Comment by hongkai-dai** [comment]
Review status: 6 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/solvers/test/optimization_examples.cc, line 880 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcco2akjLvT32sBR79j:-Kcgr9Bff2EuYDoZvmtR:b-kf1fxc) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L880)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. Thanks for the suggestion!
</blockquote></details>

@david-german-tri , I used `std::shared_ptr` here because `::testing::VariableIn` does not work well with `std::vector<std::unique_ptr<T>>`, that it tries to call the copy constructor of the storage type in `std::vector`, and the copy constructor for `std::unique_ptr` is deleted. Do you know a better way other than using `std::shared_ptr`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by david-german-tri** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/BUILD, line 126 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kctm8ACRy4MYYqhQ7yA:-Kctm8ACRy4MYYqhQ7yB:b-9ap1ny) ([raw file](https://github.com/robotlocomotion/drake/blob/2f374cdc7525739fa8439a1afb24e1db646fe5f5/drake/solvers/BUILD#L126)):*
> ```Python
>     srcs = ["test/add_solver_util.cc"],
>     hdrs = ["test/add_solver_util.h"],
>     linkstatic = 1,
> ```

META: this is no longer needed post #5155 

---

*[drake/solvers/test/optimization_examples.cc, line 880 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcco2akjLvT32sBR79j:-KctnD7fJecpe2KyEJGB:b-iihfve) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L880)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

@david-german-tri , I used `std::shared_ptr` here because `::testing::VariableIn` does not work well with `std::vector<std::unique_ptr<T>>`, that it tries to call the copy constructor of the storage type in `std::vector`, and the copy constructor for `std::unique_ptr` is deleted. Do you know a better way other than using `std::shared_ptr`?
</blockquote></details>

This is an improvement, but wasn't quite what I meant.  I was proposing that the parameter is a tuple of `CostForm`, `ConstraintForm`, and problem, where problem is either

* a new enum, on which you `switch`, or 
* an `std::function` of `CostForm` and `ConstraintForm` that returns a `std::unique_ptr<LinearProgram>`

Either of these avoids the `shared_ptr` problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by hongkai-dai** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/BUILD, line 126 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kctm8ACRy4MYYqhQ7yA:-Kcu8wGE5qdB5BUKt1K2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f374cdc7525739fa8439a1afb24e1db646fe5f5/drake/solvers/BUILD#L126)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

META: this is no longer needed post #5155 
</blockquote></details>

Done.

---

*[drake/solvers/test/optimization_examples.cc, line 880 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcco2akjLvT32sBR79j:-Kcu8rpetkIhUOynBzss:b-nf1irt) ([raw file](https://github.com/robotlocomotion/drake/blob/c1b7fbf1ff88ab6441686d88a3ddc8bb87803c79/drake/solvers/test/optimization_examples.cc#L880)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

This is an improvement, but wasn't quite what I meant.  I was proposing that the parameter is a tuple of `CostForm`, `ConstraintForm`, and problem, where problem is either

* a new enum, on which you `switch`, or 
* an `std::function` of `CostForm` and `ConstraintForm` that returns a `std::unique_ptr<LinearProgram>`

Either of these avoids the `shared_ptr` problem.
</blockquote></details>

Done. Thanks for the suggestion, I used enum approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by david-german-tri** [comment]
Awesome! :lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/test/mosek_solver_test.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcx7fu0saZB6fkt_epB:-Kcx7fu0saZB6fkt_epC:bnk6348) ([raw file](https://github.com/robotlocomotion/drake/blob/3a36b1f34f5ee2f68054400199308631169861a6/drake/solvers/test/mosek_solver_test.cc#L28)):*
> ```cpp
>                             ::testing::ValuesIn(linear_cost_form()),
>                             ::testing::ValuesIn(linear_constraint_form()),
>                         ::testing::ValuesIn(linear_problems())));
> ```

BTW weird indent here (not worth re-running CI just for this, though)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-Kcx7sJ3oy0C6IldJDf1:bfgc9op)*

**Comment by hongkai-dai** [comment]
+@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-KcxeqJmJPFSEZNE-Y93:b-trzqz1)*

**Comment by jwnimmer-tri** [comment]
I can look, but would probably be on Friday (my on-call day).

**Comment by hongkai-dai** [comment]
@david-german-tri , would you like to serve as a platform reviewer for this PR?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-KcxgOA3qQKpZJNMArl8:bc5847s)*

**Comment by david-german-tri** [comment]
I think a second review is appropriate, but feel free to pick someone who isn't a platform reviewer.

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review. -@jwnimmer-tri for platform review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-KcxkCPlPNHtaMCe15Rm:bhc4gff)*

**Comment by sammy-tri** [comment]
Partial pass completed.  Will resume later this afternoon.

---

Reviewed 5 of 13 files at r1, 1 of 7 files at r2, 3 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcy0AS2Z7y5wWSdJbYE:-Kcy0AS2Z7y5wWSdJbYF:b-gahfx) ([raw file](https://github.com/robotlocomotion/drake/blob/3a36b1f34f5ee2f68054400199308631169861a6/drake/solvers/test/CMakeLists.txt#L27)):*
> ```CMake
>         optimization_examples.h
>         mathematical_program_test_util.h)
> set(drakeOptimizationPrivateHeaders
> ```

Why are we creating an empty variable here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-Kcy0hY_bZ5BmA8rfPwx:b-kfcxbn)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r1, 1 of 7 files at r2, 2 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-KcyTqF7T_5O_ywNGs52:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 27 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcy0AS2Z7y5wWSdJbYE:-KcycSjIpbGg4gghKtw4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a36b1f34f5ee2f68054400199308631169861a6/drake/solvers/test/CMakeLists.txt#L27)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Why are we creating an empty variable here?
</blockquote></details>

Done.

---

*[drake/solvers/test/mosek_solver_test.cc, line 28 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-Kcx7fu0saZB6fkt_epB:-Kcyc5frsPMeS_9QLX9k:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3a36b1f34f5ee2f68054400199308631169861a6/drake/solvers/test/mosek_solver_test.cc#L28)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW weird indent here (not worth re-running CI just for this, though)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122)*

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5122#-:-Kcyj5-lOt3GxCygFWuJ:b-l70wzf)*

**Pull request merged**
