### PR TITLE
Fix relational operators overloading to support block/segment of symbolic matrix/array

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5633)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@hongkai-dai , feature-review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-:-KgGLdjvvF00M7H4gW8M:b-utjvo1)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 563 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGS0N6XA3N81_3jyra:-KgGS0N7KJIKcP1mL_lX:b-yzrsij) ([raw file](https://github.com/robotlocomotion/drake/blob/10952a48c21c3d2647573a88be21900ad8ba5b75/drake/common/test/symbolic_expression_matrix_test.cc#L563)):*
> ```cpp
>   Eigen::Matrix<Expression, 5, 1> v;
>   v << x_, 1, y_, x_, 1;
>   const auto s1 = v.segment(0, 2);  // [x, 1]
> ```

This test is for dynamic sized block, can we also test the static sized ones, like 
`v.segment<2>(0)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 563 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGS0N6XA3N81_3jyra:-KgGSFreufpgjFzmX9Jn:bp9x8k) ([raw file](https://github.com/robotlocomotion/drake/blob/10952a48c21c3d2647573a88be21900ad8ba5b75/drake/common/test/symbolic_expression_matrix_test.cc#L563)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This test is for dynamic sized block, can we also test the static sized ones, like 
`v.segment<2>(0)`?
</blockquote></details>

Sure. I'll add more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 563 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGS0N6XA3N81_3jyra:-KgGTuPvXtPrntrn8vf1:b-tcv3a9) ([raw file](https://github.com/robotlocomotion/drake/blob/10952a48c21c3d2647573a88be21900ad8ba5b75/drake/common/test/symbolic_expression_matrix_test.cc#L563)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Sure. I'll add more.
</blockquote></details>

I've changed some of `.segment` and `.block()` operations in the tests to the static-sized ones. Do you think this is good enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by hongkai-dai** [comment]
:lgtm: +@jwnimmer-tri for platform review.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 563 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGS0N6XA3N81_3jyra:-KgGYJvWDQMYc9lV04w7:b-bwwxm5) ([raw file](https://github.com/robotlocomotion/drake/blob/10952a48c21c3d2647573a88be21900ad8ba5b75/drake/common/test/symbolic_expression_matrix_test.cc#L563)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I've changed some of `.segment` and `.block()` operations in the tests to the static-sized ones. Do you think this is good enough?
</blockquote></details>

Looks awesome, thanks for adding the tests.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 588 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGYdRjjhmGbA1ejxNE:-KgGYdRjjhmGbA1ejxNF:b-omwoac) ([raw file](https://github.com/robotlocomotion/drake/blob/de662988a12ede96a72a6d23dfd58a7b976a1d4d/drake/common/test/symbolic_expression_matrix_test.cc#L588)):*
> ```cpp
>   //      [3, 4]
>   const auto b2 = m.block<2, 2>(1, 1);
>   // (x = 1) /\ (y = 2) /\ (y = 3) /\ (1 = 4) -> False
> ```

BTW, you might want to use the symbol `∧`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-:-KgGYjwRlvzJuZYT7JFS:b-xrxq0n)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 588 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGYdRjjhmGbA1ejxNE:-KgGZ62pb-jQ5MqoEkKF:b-oljgdx) ([raw file](https://github.com/robotlocomotion/drake/blob/de662988a12ede96a72a6d23dfd58a7b976a1d4d/drake/common/test/symbolic_expression_matrix_test.cc#L588)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you might want to use the symbol `∧`
</blockquote></details>

Right. I'll fix it when I have comments from @jwnimmer-tri .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 476 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGfQzF3J1wxhefdChm:-KgGfQzF3J1wxhefdChn:bvalu7h) ([raw file](https://github.com/robotlocomotion/drake/blob/de662988a12ede96a72a6d23dfd58a7b976a1d4d/drake/common/symbolic_formula.h#L476)):*
> ```objc
>   DRAKE_DEMAND(m1.rows() == m2.rows() && m1.cols() == m2.cols());
>   return m1.binaryExpr(m2, std::equal_to<void>())
>       .redux(std::logical_and<void>());
> ```

FYI GCC 4.8's `libstdc++` doesn't have `std::logical_and`, so while this isn't strictly defective, I would just revert it when I next do my GCC 4.8 backporting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-:-KgGfbquVim6ctyMgeMV:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula.h, line 476 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGfQzF3J1wxhefdChm:-KgGmIkIc3U7sDFHeQ0T:b-g42qez) ([raw file](https://github.com/robotlocomotion/drake/blob/de662988a12ede96a72a6d23dfd58a7b976a1d4d/drake/common/symbolic_formula.h#L476)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI GCC 4.8's `libstdc++` doesn't have `std::logical_and`, so while this isn't strictly defective, I would just revert it when I next do my GCC 4.8 backporting.
</blockquote></details>

I just reverted. Thanks for the explanation.

---

*[drake/common/test/symbolic_expression_matrix_test.cc, line 588 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5633#-KgGYdRjjhmGbA1ejxNE:-KgGmeaNQCfP-k4C7S_D:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de662988a12ede96a72a6d23dfd58a7b976a1d4d/drake/common/test/symbolic_expression_matrix_test.cc#L588)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Right. I'll fix it when I have comments from @jwnimmer-tri .
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5633)*

**Pull request merged**
