### PR TITLE
Port estimators and some examples to default_scalars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7111)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for all review please, per rotation.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: This is nice. Is there a plan for connecting this in with the doxygen boilerplate?

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7111#-:-Kv2nxJiwf1kSmV24FuC:bz2d88p)*

**Comment by jwnimmer-tri** [comment]
I have a hope, but not a plan.  (My hope is that this macro _just by itself_ would induce the boilerplate; that would depend on whether Doxygen offers a `\appendto Classname` tag of some kind.)

**Comment by SeanCurtis-TRI** [comment]
That's the trickeration, isn't it? It works beautifully for the copy/move semantics because the macro is used in the header. Pushing it *from* the .cc file into (effectively) the header is definitely going to require some help from doxygen. Good luck.

**Pull request merged**
