### PR TITLE
Mention C++14

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7038)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake I believe we discussed this last week; is this the kind of thing you were thinking we should do?

**Comment by RussTedrake** [comment]
:lgtm:   

fyi - It's very reasonable to mention it there.  But I wondered if somewhere in the design notes we should say something to the effect of "C++14 allowed".  Looking quickly at the pages, perhaps the frontpage of Doxygen c++ might be another reasonable place to say it (http://drake.mit.edu/doxygen_cxx/index.html#://)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7038#-:-KuJl1RBe7tKyGfhRKUR:b3x4jwg)*

**Comment by jwnimmer-tri** [comment]
I've added the same new sentence to the Doxygen main page.  It gave me pause because the dependencies should be enumerated in only one place, but I think expressing the language revision we target as part of the the API documentation is a reasonable compromise, distinct from the OS + toolchain support matrix.

FYI In http://drake.mit.edu/code_style_guide.html we already have "Embrace templates/C++14 when it makes the code more correct..." which like the right place for prescriptive advice.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7038#-:-KuJlXqwxlY9sNLkb5RA:b-9ysaxc)*

**Comment by jwnimmer-tri** [comment]
+@jamiesnape as second reviewer, please.

**Comment by RussTedrake** [comment]
i was asking for the prescriptive advice.  if that's already in the code style guide, then i agree it's not needed on the doxygen front page.  and i agree that perhaps it's cleaner to not have the same line repeated.  my vote is to take that line back out of doxygen.h (sorry), but i'm ok with either solution.  

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7038#-:-KuJopRBJpBc7bKq8ZTo:b-y1vt8w)*

**Comment by jamiesnape** [comment]
:lgtm: (though I guess really it is a combination of compiler and standard library support, but we do not currently mention standard libraries at all at present.)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7038#-:-KuK42UbPutCQX-TEW6T:b-dejn4w)*

**Pull request merged**
