### PR TITLE
Use mkdtemp when creating temp directories except for call_{matlab|python}

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8493)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/proto/call_temp_directory.h, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96a0Bd7oZxu-1ERP6z:-L96a0Bd7oZxu-1ERP7-:b-yc19o2) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/proto/call_temp_directory.h#L14)):*
> ```objc
> /// @throws std::runtime_error If the path referred to by TEST_TMPDIR or /tmp
> /// does not exist or is not a directory.
> std::string call_temp_directory();
> ```

That "call" is meant as a noun here, but is easily misread as a verb, is probably a bit too misleading.  Maybe add "get_" to clarify?

Or what do you think about GetRpcPipeTempDirectory as a name, just to make it plainly obnoxious since we should in general shun it?

---

*[common/test/temp_directory_test.cc, line 21 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96br66B2YewBlWXArO:-L96br66B2YewBlWXArP:b-ls3odh) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/test/temp_directory_test.cc#L21)):*
> ```cpp
> 
> // We do not test the case when TEST_TMPDIR is unset since it would create a
> // file /tmp/robotlocomotion_drake_XXXXXX outside the sandbox.
> ```

I think its important to have this code tested, since things like the automotive demo etc. are run outside of tests, and its important that they keep working.

Possibly an easy way to do this is to offer a private testing API that allows the `mkdtmp` pattern to be customized?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/temp_directory_test.cc, line 21 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96br66B2YewBlWXArO:-L96fqN1Cd0Fo2VJ8gqK:b31vxaf) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/test/temp_directory_test.cc#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think its important to have this code tested, since things like the automotive demo etc. are run outside of tests, and its important that they keep working.

Possibly an easy way to do this is to offer a private testing API that allows the `mkdtmp` pattern to be customized?
</blockquote></details>

Another option, I guess, would be to respect `TMPDIR`, if set, rather than hardcoding `/tmp` (which would probably be preferable on Mac anyway).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/temp_directory_test.cc, line 21 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96br66B2YewBlWXArO:-L96gwUz2vY6A3x0EMpk:br09cq3) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/test/temp_directory_test.cc#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Another option, I guess, would be to respect `TMPDIR`, if set, rather than hardcoding `/tmp` (which would probably be preferable on Mac anyway).
</blockquote></details>

That sounds reasonable to me.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jamiesnape** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/test/temp_directory_test.cc, line 21 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96br66B2YewBlWXArO:-L970K7aENv1PcxFuved:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/test/temp_directory_test.cc#L21)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That sounds reasonable to me.
</blockquote></details>

Done.

---

*[common/proto/call_temp_directory.h, line 14 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L96a0Bd7oZxu-1ERP6z:-L970J1X-JXOT2r4E-53:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/238cf9ce8248310f1f0006b602a21770869c5f3d/common/proto/call_temp_directory.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That "call" is meant as a noun here, but is easily misread as a verb, is probably a bit too misleading.  Maybe add "get_" to clarify?

Or what do you think about GetRpcPipeTempDirectory as a name, just to make it plainly obnoxious since we should in general shun it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

+@sammy-tri for platform review, please.

---

Reviewed 13 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/temp_directory.cc, line 24 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L975UFQApgtR4oThIiX:-L975UFQApgtR4oThIiY:b-84h74d) ([raw file](https://github.com/robotlocomotion/drake/blob/67450af10fb6d712e5f4da1af1de6b67a1b71852/common/temp_directory.cc#L24)):*
> ```cpp
>     path_template.append("robotlocomotion_drake_XXXXXX");
> 
>     char* path_template_str = ::strdup(path_template.getStr().c_str());
> ```

I think `&mycppstring[0]` is the idiomatic way to get a non-const`char*` pointer from a `std::string`?  strdup without RAII is a bit weird.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-:-L9764enBgU4P3nwUUug:b-3v5mxt)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[common/temp_directory.cc, line 24 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-L975UFQApgtR4oThIiX:-L9ApA8tCNp6MPyfU38e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/67450af10fb6d712e5f4da1af1de6b67a1b71852/common/temp_directory.cc#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think `&mycppstring[0]` is the idiomatic way to get a non-const`char*` pointer from a `std::string`?  strdup without RAII is a bit weird.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493)*

**Comment by jamiesnape** [comment]
`mkdtemp` is returning junk on Ubuntu.

**Comment by jwnimmer-tri** [comment]
I wasn't 100% sure that the reference-capture address-of-`operator[]` change was correct C++, but I _thought_ it was okay.  If you put the `getStr()` into a named local variable instead of a temporary, does it work better?

**Comment by sammy-tri** [comment]
Given that `mkdtemp` mutates the data which the `template` argument points to, perhaps copying the result of `c_str()` on the `std::string` from spruce into a local character array would be the safest option?   (just guessing here, didn't try it).

---

Reviewed 12 of 19 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-:-L9BF0J5B33WszvbLTA7:b-4a9lcs)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8493#-:-L9Bd9Pw6s46I2UDiG1D:bnfp4nl)*

**Pull request merged**
