### PR TITLE
[planning] Add CollisionCheckerParams

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@seancurtis-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473#-:-NJRmUTH7DR5W_tQWhkH:bax1t9m)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of nits.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473#-:-NJfkEiK2pzoES3_jvg-:b-xlmni7)* status: 3 unresolved discussions, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @rpoyner-tri)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJfjKL7-mpbvBoBd4cW):*
nit: I don't think my name actually belongs on this PR.
___
*[`planning/collision_checker_params.h` line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJfjq_I1n-b6fzCIJm9:-NJfjq_I1n-b6fzCIJmA:b2p339p) ([raw file](https://github.com/robotlocomotion/drake/blob/024d4354c1c65e948f22b54e5c11df1f1acf6447/planning/collision_checker_params.h#L60)):*
> ```objc
> 
>   /** Step size for edge checking; in units compatible with the configuration
>    distance function..
> ```

nit: one oddball whitespace.

nit: Extra trailing period.
___
*[`planning/collision_checker_params.h` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJfk-AI2ymLTjv5rU0Y:-NJfk-AI2ymLTjv5rU0Z:bxh32qk) ([raw file](https://github.com/robotlocomotion/drake/blob/024d4354c1c65e948f22b54e5c11df1f1acf6447/planning/collision_checker_params.h#L64)):*
> ```objc
>   at edge_step_size steps and checking the interpolated configuration for
>   collision. The value must be positive. */
>   double edge_step_size{};
> ```

nit: Can you put a TODO on this with my name such that I provide a hyper link to the documentation on edge checking `CollisionChecker`?

In fact, it should apply to this parameter as well as the following two padding parameters.

**Review by rpoyner-tri — COMMENTED** [review]
+@ggould-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473#-:-NJg7HT215QtsQmDC1bO:b-8qo47q)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
I'm as-new'ing this since it's new to drake.

:lgtm: with lawyerly nits.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473#-:-NJgL7DwCiX-a_DMmhd3:bo8nwjq)* status: 6 unresolved discussions (waiting on @rpoyner-tri)

___
*[`planning/collision_checker_params.h` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJ6LX5EtzEthz8Lyo:-NJgJ6LX5EtzEthz8Lyp:b-ivbl0s) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L17)):*
> ```objc
> /** Configuration distance takes two configurations of the robot, q1 and q2,
> both as Eigen::VectorXd, and returns (potentially weighted) C-space distance
> as a double.
> ```

minor:  May this return value be negative?  The term "distance" is usually nonnegative, so it might be good to be explicit.
___
*[`planning/collision_checker_params.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJhcm8jfBMuct42XY:-NJgJhcm8jfBMuct42XZ:be9tjq5) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L27)):*
> ```objc
> 
> /** Configuration interpolation function takes two configurations of the robot,
> q1, and q2, both as Eigen::VectorXd, plus a ratio in [0, 1] and returns the
> ```

nit:  Is the function or the caller responsible for ensuring that `r` is in that range?
___
*[`planning/collision_checker_params.h` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgIsePDMmm0b17vgjM:-NJgIsePDMmm0b17vgjN:b-gxmudp) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L32)):*
> ```objc
> To be valid, the function must satisfy the following conditions:
> 
>  - F(q1, q2, 0) ≡ q1
> ```

nit:  Since you just used `F` for a different function, might it be better to choose a different letter here?
___
*[`planning/collision_checker_params.h` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJMsb9KIgqhSz3Tm_:-NJgJMsb9KIgqhSz3Tma:bs0212o) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L34)):*
> ```objc
>  - F(q1, q2, 0) ≡ q1
>  - F(q1, q2, 1) ≡ q2
>  - F(q, q, for all r in [0, 1]) ≡ q
> ```

nit:  consider rephrasing this to not have a hanging "r" ?



_Suggestion:_
```objc
 - F(q, q, r) for all r in [0, 1] ≡ q
```
___
*[`planning/collision_checker_params.h` line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKqP77mP-OjNCE3Uu:-NJgKqP77mP-OjNCE3Uv:b-cjov5f) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L38)):*
> ```objc
> using ConfigurationInterpolationFunction =
>     std::function<Eigen::VectorXd(
>         const Eigen::VectorXd&, const Eigen::VectorXd&, double)>;
> ```

nit:  Unused????  I'd have expected this to appear in the params.

Cheating a bit and looking downstream, I see that in the anzu planning version this is defaulted at checker creation and then set via a setter.  That seems like a weird asymmetry that should be justified -- even with a setter there's no reason not to let the initial value be set a construction time.

I was thinking it was a constness question (i.e. that the checker was retaining a const copy of the params struct, whcih would make a single member setter awkward) but that doesn't seem to be the case.
___
*[`planning/collision_checker_params.h` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKAZ-2kJT59__Y8sn:-NJgKAZ-2kJT59__Y8so:b4cmlab) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L39)):*
> ```objc
>     std::function<Eigen::VectorXd(
>         const Eigen::VectorXd&, const Eigen::VectorXd&, double)>;
> ```

minor meta:  What is the relationship if any between an interpolation function and a distance function?  Is there an implied relationship between distance and interpolation functions in the same params, e.g. a convexity condition that distance is monotonic along an interpolated trajectory.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: 6 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @ggould-tri)

___
*[`planning/collision_checker_params.h` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJ6LX5EtzEthz8Lyo:-NJjfrLX6FFihfr7u1lU:b-tygvn) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L17)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  May this return value be negative?  The term "distance" is usually nonnegative, so it might be good to be explicit.
</blockquote></details>

Good point; in this case, it should be clear that  it is strictly non-negative.
___
*[`planning/collision_checker_params.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJhcm8jfBMuct42XY:-NJjhT15D_1HA-t11GNw:by24e9m) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L27)):*
This is an interesting question. If we absolved the function of the responsibility to check, it would devolve to `CollisionChecker`; that is hard to test. Perhaps:

> CollisionChecker will do its best to only evaluate for values of r in the range [0, 1]. But the function may throw for values of r outside of that range if it chooses.

Or, more succinctly,

> Behavior for values of r outside of the range [0, 1] is undefined behavior.
___
*[`planning/collision_checker_params.h` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgIsePDMmm0b17vgjM:-NJjfzeyDbvAJexm_Wjw:bf0rbg1) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L32)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Since you just used `F` for a different function, might it be better to choose a different letter here?
</blockquote></details>

alternatively, we can replace both `F` with `dist` and `interpolate`, respectively.
___
*[`planning/collision_checker_params.h` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJMsb9KIgqhSz3Tm_:-NJjg57S2LdKQ-T0ZDqx:b-94cyv1) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L34)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  consider rephrasing this to not have a hanging "r" ?
</blockquote></details>

I'd propose:

```
 - F(q, q, r) ≡ q, for all r in [0, 1] 
```z
```

___
*[`planning/collision_checker_params.h` line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKqP77mP-OjNCE3Uu:-NJjgFkABAJaZ3UwuFi1:b6kqw9v) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L38)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Unused????  I'd have expected this to appear in the params.

Cheating a bit and looking downstream, I see that in the anzu planning version this is defaulted at checker creation and then set via a setter.  That seems like a weird asymmetry that should be justified -- even with a setter there's no reason not to let the initial value be set a construction time.

I was thinking it was a constness question (i.e. that the checker was retaining a const copy of the params struct, whcih would make a single member setter awkward) but that doesn't seem to be the case.
</blockquote></details>

To be perfectly frank, this is one of the small bits of weirdness that leaked through. Getting this corner of the code ready has been an Herculean effort and there are still aspects of it that we're not happy with that we're largely resigned that will need clean up in the post move.

I'd propose that a TODO here:

```
TODO(SeanCurtis-TRI): Move the default interpolator into the params.
```
___
*[`planning/collision_checker_params.h` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKAZ-2kJT59__Y8sn:-NJjgfb50S7o0gz5mfJi:b-pbs0i9) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor meta:  What is the relationship if any between an interpolation function and a distance function?  Is there an implied relationship between distance and interpolation functions in the same params, e.g. a convexity condition that distance is monotonic along an interpolated trajectory.
</blockquote></details>

There is no explicit connection. The best thing to do in regards to these functions is to link to the documentation in `CollisionChecker` on edge checking. 

Adding similar TODOs (as below) on these two function types is probably a good thing.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: 6 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

___
*[`planning/collision_checker_params.h` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJ6LX5EtzEthz8Lyo:-NJjyg0k18V-f9HeHLYa:b4c9lyr) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L17)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Good point; in this case, it should be clear that  it is strictly non-negative.
</blockquote></details>

:thumbsup: 
___
*[`planning/collision_checker_params.h` line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJhcm8jfBMuct42XY:-NJjyOnRE17npwKL0Umk:b-maqwpu) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L27)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is an interesting question. If we absolved the function of the responsibility to check, it would devolve to `CollisionChecker`; that is hard to test. Perhaps:

> CollisionChecker will do its best to only evaluate for values of r in the range [0, 1]. But the function may throw for values of r outside of that range if it chooses.

Or, more succinctly,

> Behavior for values of r outside of the range [0, 1] is undefined behavior.
</blockquote></details>

Both of those seem like fine clarifications.
___
*[`planning/collision_checker_params.h` line 32 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgIsePDMmm0b17vgjM:-NJjyWfl57wa0bdt3nTU:b4c9lyr) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L32)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

alternatively, we can replace both `F` with `dist` and `interpolate`, respectively.
</blockquote></details>

:thumbsup: 
___
*[`planning/collision_checker_params.h` line 34 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgJMsb9KIgqhSz3Tm_:-NJjyZnPD38kwyc22NXu:b4c9lyr) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L34)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd propose:

```
 - F(q, q, r) ≡ q, for all r in [0, 1] 
```z
```

</blockquote></details>

:thumbsup: 
___
*[`planning/collision_checker_params.h` line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKqP77mP-OjNCE3Uu:-NJjy4Xf2cRWtMeTbqQ9:b-yry5i1) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L38)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

To be perfectly frank, this is one of the small bits of weirdness that leaked through. Getting this corner of the code ready has been an Herculean effort and there are still aspects of it that we're not happy with that we're largely resigned that will need clean up in the post move.

I'd propose that a TODO here:

```
TODO(SeanCurtis-TRI): Move the default interpolator into the params.
```
</blockquote></details>

A TODO would a fine answer here, yes.
___
*[`planning/collision_checker_params.h` line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18473#-NJgKAZ-2kJT59__Y8sn:-NJjy9z-4ke0OiAdmaSB:b-yry5i1) ([raw file](https://github.com/robotlocomotion/drake/blob/12011e6d28aedbd67bfcd8b1868ec8929128035d/planning/collision_checker_params.h#L39)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

There is no explicit connection. The best thing to do in regards to these functions is to link to the documentation in `CollisionChecker` on edge checking. 

Adding similar TODOs (as below) on these two function types is probably a good thing.
</blockquote></details>

A TODO would a fine answer here, yes.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform), base commit is latest master (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform), base commit is latest master (waiting on @rpoyner-tri)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform), base commit is latest master (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform), base commit is latest master (waiting on @rpoyner-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Race won?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18473#-:-NJkM4rX8pi7t_PAfAK3:b-f67bql)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),SeanCurtis-TRI(platform), base commit is latest master (waiting on @rpoyner-tri)

**Pull request merged**
