### PR TITLE
Remove non-functional output port listener and cache code

### PR DESCRIPTION
**Pull request by sherm1**
The framework contained several flavors of non-functional cache-y code. This PR removes them in preparation for putting in the real cache code.

Removed here are:
- output port listener (completely)
- cache (stubbed out)

I left cache.h cache.cc and cache_test.cc as stubs because those files are still used in the new code, but with different guts. Leaving them will make it easier for me to merge the new code it after this lands. You can see what goes there in PR #7668.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7999)

### CODE REVIEW

**Comment by sherm1** [comment]
Feature review +@jwnimmer-tri please since doing this as a separate PR was your idea. (And thanks for fixing my missing reviewable assignment syntax for my previous PR!)
Platform review +@soonho-tri per rotation please.

This is almost entirely deletions -- should make for pleasant reviewing!

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-:-L4o1jL-48GHkdK9eFV3:b-fdwhha)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[systems/framework/cache.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pRJRqSsNnmv-76hTE:-L4pRJRr_HKrNqVTzRSo:b-wb7buw) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/cache.h#L13)):*
> ```objc
> #include "drake/common/drake_assert.h"
> #include "drake/common/drake_copyable.h"
> #include "drake/systems/framework/value.h"
> ```

FYI I guess the next PR will clean up the includes to suit the new code?  (Ditto for cc file, and the unit test.)

---

*[systems/framework/input_port_value.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pS0_4P6hKKNDKSqSn:-L4pS0_4P6hKKNDKSqSo:b-c27kto) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/input_port_value.h#L31)):*
> ```objc
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(InputPortValue)
> 
>   virtual ~InputPortValue() = default;
> ```

FYI Even with empty or small bodies, I think placing the definition in the cc file has real value -- it prevents the vtable from being a weak symbol that appears (repeatedly) in every downstream compilation unit.  This is both sometimes more efficient, but is mostly important to enhance debug-ability when using shared libraries with RTTI.

Ditto for the other `= default`(s) in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-:-L4pSZIYsjOJQYDp8FDY:bnfp4nl)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-:-L4qGjicYd4TDvpw71kX:bnfp4nl)*

**Comment by soonho-tri** [comment]
@sherm1 , apparently CI is not happy. PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-:-L4qGm_dlBp27ayWfYvk:bhnrzod)*

**Comment by sherm1** [comment]
Review status: 11 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/framework/cache.h, line 13 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pRJRqSsNnmv-76hTE:-L4qQbBOkTZXF3EXtHVA:b-urt6eg) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/cache.h#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I guess the next PR will clean up the includes to suit the new code?  (Ditto for cc file, and the unit test.)
</blockquote></details>

Right -- these are still needed in the upcoming code so I left them here. Others will be added.

---

*[systems/framework/input_port_value.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pS0_4P6hKKNDKSqSn:-L4qTWCarA7rllwiUsIA:b-3bo2tq) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/input_port_value.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Even with empty or small bodies, I think placing the definition in the cc file has real value -- it prevents the vtable from being a weak symbol that appears (repeatedly) in every downstream compilation unit.  This is both sometimes more efficient, but is mostly important to enhance debug-ability when using shared libraries with RTTI.

Ditto for the other `= default`(s) in this PR.
</blockquote></details>

Done. Would like to make sure I understand this, though. 
- I'm assuming this only applies to the original `virtual` declaration -- subsequent overrides shouldn't affect the character of the vtable so override definitions in the header shouldn't cause trouble, right? 
- Does this require that _every_ virtual function definition go in a .cc, or is having at least one sufficient to strengthen the vtable symbol?
- Do you have a handy link to discussion or stackoverflow topic from which I could get a more solid grasp on this issue?

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Comment by jwnimmer-tri** [comment]
*[systems/framework/input_port_value.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pS0_4P6hKKNDKSqSn:-L4qYquxhlVUSNnyyUGH:bnq4d94) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/input_port_value.h#L31)):*
> I'm assuming this only applies to the original virtual declaration -- subsequent overrides shouldn't affect the character of the vtable so override definitions in the header shouldn't cause trouble, right?

Well, each (virtual) class has its own vtable, so while this vtable would be into this object code, the vtable for subclasses would still be emitted repeatedly unless they were also defined only in a single cc file.  Basically, for me, by habit, destructors are never defined in headers (unless they are templates).

> Does this require that every virtual function definition go in a .cc, or is having at least one sufficient to strengthen the vtable symbol?

To my recollection: no -- the vtable symbol is emitted along with the destructor symbol, full stop; not related to other virtual methods.

> Do you have a handy link to discussion or stackoverflow topic from which I could get a more solid grasp on this issue?

Not off the top of my head; this is from historical experience.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Comment by soonho-tri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Comment by sherm1** [comment]
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---

*[systems/framework/input_port_value.h, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7999#-L4pS0_4P6hKKNDKSqSn:-L4qwlpF5VRuAqRp31Ga:b-hnzx1s) ([raw file](https://github.com/robotlocomotion/drake/blob/7d7e23dcd31fdbd896126e64c8bbb613c994308d/systems/framework/input_port_value.h#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I'm assuming this only applies to the original virtual declaration -- subsequent overrides shouldn't affect the character of the vtable so override definitions in the header shouldn't cause trouble, right?

Well, each (virtual) class has its own vtable, so while this vtable would be into this object code, the vtable for subclasses would still be emitted repeatedly unless they were also defined only in a single cc file.  Basically, for me, by habit, destructors are never defined in headers (unless they are templates).

> Does this require that every virtual function definition go in a .cc, or is having at least one sufficient to strengthen the vtable symbol?

To my recollection: no -- the vtable symbol is emitted along with the destructor symbol, full stop; not related to other virtual methods.

> Do you have a handy link to discussion or stackoverflow topic from which I could get a more solid grasp on this issue?

Not off the top of my head; this is from historical experience.
</blockquote></details>

Done, thanks. I can't say the issue is clear for me yet, but the rule-of-thumb seems fine. I removed the remaining header-defined destructor overrides.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7999)*

**Pull request merged**
