### PR TITLE
Solves drake compilation abort when bullet is disabled. 

### LINKED ISSUE #2958: When bullet is disabled, drake no longer compiles
These are the error messages:
- /home/jwnimmer/jwnimmer-tri/drake-distro/drake/systems/plants/collision/DrakeCollision.cpp:45:69: error: ‘DRAKE_ABORT_UNLESS’ was not declared in this scope
- /home/jwnimmer/jwnimmer-tri/drake-distro/drake/systems/plants/collision/DrakeCollision.cpp:47:1: error: no return statement in function returning non-void [-Werror=return-type]

### PR DESCRIPTION
**Pull request by amcastro-tri**
Closes #2958

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2965)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@jwnimmer-tri for platform review.
+@liangfok for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-:-KNljiiRS_iDEIuz4MY4:-21525114)*

**Comment by liangfok** [comment]
I left one question.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNlkoy2IwP-bjhUhfyn:-KNlkoy2IwP-bjhUhfyo:1398105963) ([raw file](https://github.com/robotlocomotion/drake/blob/e037022d0b8209b56ebd276678230309fc7c46cf/drake/systems/plants/collision/DrakeCollision.cpp#L46)):*
> ```cpp
> #else
>   DRAKE_ABORT_UNLESS(!"DrakeCollision must be compiled with Bullet.");
>   // This return statement is actually never reached.
> ```

Is it never reached because `BULLET_COLLISION` is always defined? If not, consider clarifying the above sentence by ending it with:

```
... never reached when BULLET_COLLISION is defined.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-:-KNll3qfCMPnXLIx936O:-1212595919)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNllmDpXGkdYWXzxW1F:-KNllmDpXGkdYWXzxW1G:1865868578) ([raw file](https://github.com/robotlocomotion/drake/blob/e037022d0b8209b56ebd276678230309fc7c46cf/drake/systems/plants/collision/DrakeCollision.cpp#L31)):*
> ```cpp
> #else
>       cerr << "Recompile with Bullet enabled (-DBULLET_COLLISION) to use "
>               "Bullet collision models." << endl;
> ```

This line is confusing, dead code.  It will never be run.  In fact, now that I read it, this whole method suffers from that same defect -- other than the one single `return ... new BulletModel ...` line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 25 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNlt1hhCS7hg7Wjeyv1:-KNlt1hhCS7hg7Wjeyv2:150277014) ([raw file](https://github.com/robotlocomotion/drake/blob/8630f49b4b58d35782f2e34134481e9ca209392f/drake/systems/plants/collision/DrakeCollision.cpp#L25)):*
> ```cpp
>   DRAKE_ABORT_UNLESS(!"DrakeCollision must be compiled with Bullet.");
>   // This return statement is actually never reached when
>   // BULLET_COLLISION is defined.
> ```

Actually, it's never reached no matter what is defined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNllmDpXGkdYWXzxW1F:-KNm9Y4PXWFpXiKLueaM:922358851) ([raw file](https://github.com/robotlocomotion/drake/blob/e037022d0b8209b56ebd276678230309fc7c46cf/drake/systems/plants/collision/DrakeCollision.cpp#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This line is confusing, dead code.  It will never be run.  In fact, now that I read it, this whole method suffers from that same defect -- other than the one single `return ... new BulletModel ...` line.
</details>
Good observation. Actually the helper method `newModel(ModelType model_type)` is not part of the API and ModelType is never used outside this file. 
I decided to simplify by just removing this unused chunk of code and delegated the model creation to `newModel()`. PTAL.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNlkoy2IwP-bjhUhfyn:-KNm9W-ZgK3Po1WWFJF2:676635175) ([raw file](https://github.com/robotlocomotion/drake/blob/e037022d0b8209b56ebd276678230309fc7c46cf/drake/systems/plants/collision/DrakeCollision.cpp#L46)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Is it never reached because `BULLET_COLLISION` is always defined? If not, consider clarifying the above sentence by ending it with:
> 
> ```
> ... never reached when BULLET_COLLISION is defined.
> ```
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 46 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNlkoy2IwP-bjhUhfyn:-KNmAcba2SzJE2jHQr5P:563648428) ([raw file](https://github.com/robotlocomotion/drake/blob/e037022d0b8209b56ebd276678230309fc7c46cf/drake/systems/plants/collision/DrakeCollision.cpp#L46)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Done
</details>
Sorry, I just undid this in response to @jwnimmer-tri observation. That piece of code is "never" reached.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 25 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNlt1hhCS7hg7Wjeyv1:-KNmAXVGBXo3hxE1PETx:813785232) ([raw file](https://github.com/robotlocomotion/drake/blob/8630f49b4b58d35782f2e34134481e9ca209392f/drake/systems/plants/collision/DrakeCollision.cpp#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Actually, it's never reached no matter what is defined.
</details>
Very true. I just undid my "fix" to @liangfok's comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-:-KNmBAzY71ldTBSk2jZV:1417088721)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNmGLLgg0ZCwjvZX7wS:-KNmGLLgg0ZCwjvZX7wT:-840017703) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3a6b0abd14bf815e27bf96b3495dabdeb9d340/drake/systems/plants/collision/DrakeCollision.cpp#L24)):*
> ```cpp
> #else
>   DRAKE_ABORT_UNLESS(!"DrakeCollision must be compiled with Bullet.");
>   // This return statement is actually never reached.
> ```

Isn't the above statement a lie if `BULLET_COLLISION` is not defined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNmGLLgg0ZCwjvZX7wS:-KNmK8zMgBiAkbF9RB_P:1106711308) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3a6b0abd14bf815e27bf96b3495dabdeb9d340/drake/systems/plants/collision/DrakeCollision.cpp#L24)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Isn't the above statement a lie if `BULLET_COLLISION` is not defined?
</details>
Nope. If BULLET_COLLISION is not defined we go into the `#else`. However we `DRAKE_ABORT` before returning and therefor the return is never reached.
If BULLET_COLLISION IS defined, then well, again we don't reach that return. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 24 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-KNmGLLgg0ZCwjvZX7wS:-KNmKiYrvX5IkRamrbl5:293024136) ([raw file](https://github.com/robotlocomotion/drake/blob/4e3a6b0abd14bf815e27bf96b3495dabdeb9d340/drake/systems/plants/collision/DrakeCollision.cpp#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Nope. If BULLET_COLLISION is not defined we go into the `#else`. However we `DRAKE_ABORT` before returning and therefor the return is never reached.
> If BULLET_COLLISION IS defined, then well, again we don't reach that return. 
</details>
OK got it. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2965#-:-KNmKmJWBe5_6NYA7HtI:1417088721)*

**Comment by jamiesnape** [comment]
Compilation is fixed, but tests are still failing: https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=63218

**Comment by jwnimmer-tri** [comment]
Yup.  I knew that would happen too, but was okay with it for now.  Fixing that is a slightly dicier problem.  I guess it deserves a new issue.

**Comment by jamiesnape** [comment]
> I guess it deserves a new issue.

#2972

**Pull request merged**
