### PR TITLE
Revert "[Multilane] Adds start and end Endpoint computation to Connections (#7343)"

### PR DESCRIPTION
**Pull request by liangfok**
Dear @agalbachicar,

The on-call build cop, @liangfok, believes that your PR #7343 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind/194/console
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-everything/192/console
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-clang-bazel-nightly-memcheck-valgrind-snopt/114/console
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-gcc-bazel-nightly-memcheck-valgrind/189/console
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-gcc-bazel-nightly-memcheck-valgrind-everything/190/console
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-xenial-gcc-bazel-nightly-memcheck-valgrind-snopt/112/console

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7480)

### CODE REVIEW

**Comment by liangfok** [comment]
+@agalbachicar in case a quick fix forward isn't possible.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7480#-:-Kz-08MQ0y5OflKUhmYk:b-o3hh)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-valgrind please.

**Comment by agalbachicar** [comment]
I suspect that something similar to #7180 happened here. Adding an overload of `operator<<` to stream  `EndpointZTestParameters` structure make the tests pass. 

If fixing it if you agree, I will send a PR fixing it.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7480#-:-Kz-9RlcDRaJHt6vgBJq:btgrznu)*

**Comment by liangfok** [comment]
I agree and will delay merging this PR.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7480#-:-Kz-FzUgHGxBJmbbNl_0:b6okp53)*

**Comment by agalbachicar** [comment]
PR #7481 has been created to solve this issue.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7480#-:-Kz-H_GmlhfI8ONLbc3Y:bhffjpz)*

**Comment by liangfok** [comment]
#7481 was merged.

**Pull request closed without merging**
