### PR TITLE
[workspace] Upgrade CRU and VGT to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Upgrade common_robotics_utilities to latest commit.
Upgrade voxelized_geometry_tools to latest commit.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15716)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri for feature review, please.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15716#-:-MigrkvR6584RejDgt6M:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15716#-:-Mj-pjgv063l4lr8jYGe:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),calderpg-tri (waiting on @jwnimmer-tri)

**Pull request merged**
