### PR TITLE
Add python binding for LinearTransformDensity

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166#-:-MbmwZ2ZCkgXiQkSbaqR:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok).

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166#-:-MbmzmF71koLnJsw4xpW:b-fl40af)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/common/module_py.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn0171A0P1LP9w3Ldy:-Mbn0171A0P1LP9w3Ldz:b-8drzdj) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/module_py.cc#L5)):*
> ```cpp
> #include "pybind11/stl.h"
> 
> #include "drake/bindings/pydrake/common/default_scalars_pybind.h"
> ```

nit I can't figure out why we need this include?

(If you end up removing it, also remove from BUILD deps.)
___
*[bindings/pydrake/common/test/module_test.py, line 115 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn-HdS9RWLzoudxxB7:-Mbn-HdS9RWLzoudxxB8:bd0yn5c) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/test/module_test.py#L115)):*
> ```Python
>             unregistered_derived_type_cc_name)
> 
>     def test_calc_probability_density(self):
> ```

nit Consider relocating this test case to be closer to its brothers from the same header, e.g., adjacent to `test_random_generator`.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/common/module_py.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn0171A0P1LP9w3Ldy:-MbqsUQy76sJ9s0SKdpc:b-u9ooa) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/module_py.cc#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I can't figure out why we need this include?

(If you end up removing it, also remove from BUILD deps.)
</blockquote></details>

I added this header so that I can use `AutoDiffXd` in `CalcProbabilityDensity<AutoDiffXd>`, should I use a different header?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/common/module_py.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn0171A0P1LP9w3Ldy:-MbqtEXG2AO_rYZvAXiC:b-igdpc7) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/module_py.cc#L5)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added this header so that I can use `AutoDiffXd` in `CalcProbabilityDensity<AutoDiffXd>`, should I use a different header?
</blockquote></details>

That would be just `drake/common/autodiffxd.h`, but `drake/common/random.h` already has that.  (Maybe it shouldn't, though?  Possibly that should move to the cc file.)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: 2 unresolved discussions (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/common/module_py.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn0171A0P1LP9w3Ldy:-MbqxBmBCxixTtkizAsE:b889dip) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/module_py.cc#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That would be just `drake/common/autodiffxd.h`, but `drake/common/random.h` already has that.  (Maybe it shouldn't, though?  Possibly that should move to the cc file.)
</blockquote></details>

If I remove this header file, I got the following compilation error
```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/pybind11/include/pybind11/eigen.h:12:0,
                 from bindings/pydrake/common/module_py.cc:1:
external/pybind11/include/pybind11/numpy.h: In instantiation of 'struct pybind11::detail::npy_format_descriptor<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, void>':
external/pybind11/include/pybind11/eigen.h:201:29:   required from 'constexpr const auto pybind11::detail::EigenProps<Eigen::Ref<const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, -1, 1, 0, -1, 1>, 0, Eigen::InnerStride<1> > >::descriptor'
external/pybind11/include/pybind11/eigen.h:200:27:   required from 'struct pybind11::detail::EigenProps<Eigen::Ref<const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, -1, 1, 0, -1, 1>, 0, Eigen::InnerStride<1> > >'
```
I can't quite decode what the error message means. I thought that is used for add python binding for AutoDiffXd?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: 2 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/common/module_py.cc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15166#-Mbn0171A0P1LP9w3Ldy:-MbqyHR17l7T7DmzPbNA:bwvivnk) ([raw file](https://github.com/robotlocomotion/drake/blob/eec02adf36b09bef04d5abe2221824927f23469a/bindings/pydrake/common/module_py.cc#L5)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If I remove this header file, I got the following compilation error
```
Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/pybind11/include/pybind11/eigen.h:12:0,
                 from bindings/pydrake/common/module_py.cc:1:
external/pybind11/include/pybind11/numpy.h: In instantiation of 'struct pybind11::detail::npy_format_descriptor<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, void>':
external/pybind11/include/pybind11/eigen.h:201:29:   required from 'constexpr const auto pybind11::detail::EigenProps<Eigen::Ref<const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, -1, 1, 0, -1, 1>, 0, Eigen::InnerStride<1> > >::descriptor'
external/pybind11/include/pybind11/eigen.h:200:27:   required from 'struct pybind11::detail::EigenProps<Eigen::Ref<const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1> >, -1, 1, 0, -1, 1>, 0, Eigen::InnerStride<1> > >'
```
I can't quite decode what the error message means. I thought that is used for add python binding for AutoDiffXd?
</blockquote></details>

Ah, okay.

You want this ...

```
#include "drake/bindings/pydrake/autodiff_types_pybind.h"
```

... which is the first line from default_scalars_pybind.  That tells pybind11 how to deal with AutoDiff, which is the part you care about.  The `default_scalars_pybind` is only if you need `CommonScalarPack` to loop over while binding a templated class.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15166)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Pull request merged**
