### PR TITLE
Allow lazy linking on sanitize builds

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
When sanitizers are in use, don't add the flags to require strict linking (no unresolved externals). This is needed as the compiler does not include necessary sanitizer libraries when linking libraries, and is is difficult to impossible to specify them manually. We'll still use strict linking for the general case, so shouldn't lose much error detection, but this should allow the sanitize builds to work without too many headaches.

@jamiesnape for feature review, @sammy-tri for platform review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4028)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-clang-experimental-memcheck-asan please
@drake-jenkins-bot linux-clang-experimental-memcheck-msan please
@drake-jenkins-bot linux-clang-experimental-memcheck-tsan please

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4028#-:-KVk8TJcsEVRildifxn2:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
```
00:00:19.568   gfortran-4.9: error: -fsanitize=thread linking must be done with -pie or
00:00:19.568   -shared
```

Geez... well, I guess this isn't likely to magically fix much... or at least, the experimental *san builds have other problems...

**Comment by jamiesnape** [comment]
Is the `-fsanitize` linker flag getting passed down?

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-gcc-experimental-memcheck-asan please
@drake-jenkins-bot linux-gcc-experimental-memcheck-tsan please

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4028#-:-KVkfvGD7tQZ-VNsvg08:bnfp4nl)*

**Pull request merged**
