### PR TITLE
Added RigidBodyTree::FindChildrenOfbody(), RigidBodyTree::FindBaseBod…

### PR DESCRIPTION
**Pull request by liangfok**
…ies(), and RigidBodyTree::GetBody().

Resolves https://github.com/RobotLocomotion/drake/issues/3142.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3184)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed pre-merge CI. Since this touches `RigidBody*`:

+@amcastro-tri for feature review please.
+@sherm1 for platform review please.

CC: @hongkai-dai since this will assist in identifying the pose of a model instance.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-:-KPUi8Fyfkv4hTXMbm34:bk6rfl4)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1874 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPUjoY2h0ov9eg6sPT_:-KPUjoY2h0ov9eg6sPTa:b-pb4zhi) ([raw file](https://github.com/robotlocomotion/drake/blob/83126ccae7b88b7765019c7f1081432e8783c232/drake/systems/plants/RigidBodyTree.cpp#L1874)):*
> ```cpp
> 
>   // Obtains a reference to the parent body.
>   const RigidBody& parent_body = *(bodies.at(body_index).get());
> ```

Use the method `GetBody` for better readability?

---

*[drake/systems/plants/RigidBodyTree.h, line 636 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPUkLPrgcsto1Cg7nCZ:-KPUkLPrgcsto1Cg7nC_:bu8hvh3) ([raw file](https://github.com/robotlocomotion/drake/blob/83126ccae7b88b7765019c7f1081432e8783c232/drake/systems/plants/RigidBodyTree.h#L636)):*
> ```objc
>   /**
>    * Obtains a list of body indexes of the bodies that are the children of the
>    * world body.
> ```

Use `vector` instead of `list` in the documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-:-KPUkwQZhwpweeoCpNqv:bnfp4nl)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 1874 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPUjoY2h0ov9eg6sPT_:-KPUotFH-cwJ8PUlulIp:b-xxiavj) ([raw file](https://github.com/robotlocomotion/drake/blob/83126ccae7b88b7765019c7f1081432e8783c232/drake/systems/plants/RigidBodyTree.cpp#L1874)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Use the method `GetBody` for better readability?
</details>
Done. I also changed the name of the method to be `get_body()` since the time complexity of accessing the rigid body is `O(1)`:

http://en.cppreference.com/w/cpp/container/vector/operator_at

---

*[drake/systems/plants/RigidBodyTree.h, line 636 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPUkLPrgcsto1Cg7nCZ:-KPUmHMKb6GAIG56vQl5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/83126ccae7b88b7765019c7f1081432e8783c232/drake/systems/plants/RigidBodyTree.h#L636)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Use `vector` instead of `list` in the documentation?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-:-KPV2hTXu39qj7k-CTz9:bblnx7i)*

**Comment by sherm1** [comment]
A few comment changes needed but :lgtm: otherwise. Feel free to merge after those are fixed.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.h, line 667 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV7CYS_-Zs6TMhWBJS:-KPV7CYS_-Zs6TMhWBJT:b-q0c3an) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L667)):*
> ```objc
>    * be bodies that belong to model instance ID @p model_instance_id.
>    */
>   std::vector<int> FindChildrenOfBody(int parent_body_index,
> ```

Should say that the computational complexity is O(N) here. I think that's fine for now but it wouldn't have to be that expensive -- for example every body could contain a list of its children in which case this would be O(1).

---

*[drake/systems/plants/RigidBodyTree.h, line 751 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV6zmw_ybYTkxaQhgh:-KPV6zmw_ybYTkxaQhgi:byp300y) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L751)):*
> ```objc
>    * Returns the body at index @p body_index. Parameter @p body_index must be
>    * between zero and the number of bodies in this tree, which can be determined
>    * by calling RigidBodyTree::get_number_of_bodies().
> ```

BTW, mention that body 0 is defined to be the world?

---

*[drake/systems/plants/RigidBodyTree.h, line 756 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV6uDa9wl2YFjgArb3:-KPV6uDa9wl2YFjgArb4:b-btrgwc) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L756)):*
> ```objc
> 
>   /**
>    * Returns the number of bodies in this tree.
> ```

Say whether this number includes the "world" body.

---

*[drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc, line 336 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPVIrhJ4z1m58lWzkze:-KPVIrhJ4z1m58lWzkzf:b3qpn0w) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_test.cc#L336)):*
> ```cpp
> // and RigidBodyTree::FindBaseBodies(). This also tests
> // RigidBodyTree::get_body() and RigidBodyTree::get_number_of_bodies().
> TEST_F(RigidBodyTreeTest, TestFindChildrenOfBodyAndFindBaseBodies) {
> ```

BTW I like this series of tests!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-:-KPVJBH3TX4YXgBdIPmZ:bzeyyou)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. Now waiting on CI to pass.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 667 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV7CYS_-Zs6TMhWBJS:-KPVSe0EnqyeqIIHUnSj:b-coyz5f) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L667)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Should say that the computational complexity is O(N) here. I think that's fine for now but it wouldn't have to be that expensive -- for example every body could contain a list of its children in which case this would be O(1).
</details>
Done. +1 for eventually having each body store a list of its children.

---

*[drake/systems/plants/RigidBodyTree.h, line 751 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV6zmw_ybYTkxaQhgh:-KPVSN_j0jIjcRfsA93I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L751)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, mention that body 0 is defined to be the world?
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.h, line 756 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-KPV6uDa9wl2YFjgArb3:-KPVS8udWvZOXlF1MZM3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c0afd75fecd7fff580ac26bb7352e91c9a9cf733/drake/systems/plants/RigidBodyTree.h#L756)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Say whether this number includes the "world" body.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3184#-:-KPVSoynvixPDTKtr_FP:bfjsc5j)*

**Pull request merged**
