### PR TITLE
Remove Acrobot and Pendulum MATLAB examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These examples have been (to a satisfactory degree) ported to the newer C++ APIs.

(This does not attempt to remove now-unused model (e.g., URDF) files.  They might still be useful in the future, and can easily be culled later if need be.)

_Edit: For the record, the original draft of this PR also removed the Quadrotor example._

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6235)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for simple confirmation on the concept, please.  I'll wait to assign feature / platform review until after that.

**Comment by RussTedrake** [comment]
:lgtm:  but note that there is a lot of good stuff here that has NOT been ported yet.  some of these should stay on our list.  could we open an issue specifically about porting the iris+quadrotor mi-convex planning examples?  (you can assign it to me)

---

Review status: 0 of 122 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6235#-:-KleMF0uszOZSoVIrB9O:b1abp09)*

**Comment by jwnimmer-tri** [comment]
Filed as #6243.
-(status: do not merge) 
+@soonho-tri for all review, please.

---

Review status: 0 of 122 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6235#-:-KleZnpRujh44u-5wJlL:b6clvc)*

**Comment by rdeits** [comment]
I'm actually not happy about this. I've cited Drake as the source for this algorithm in the original paper, and now it's being deleted with no replacement. Is this code actually hurting anything? Removing it will make the paper harder to follow without a clear benefit.

**Comment by rdeits** [comment]
(to clarify, I'm referring to the MI-convex quadrotor planning code)

**Comment by jwnimmer-tri** [comment]
@rdeits I apologize for the surprise!  I will revert the Quadrotor changes from this PR, and move this discussion elsewhere; probably #6243 will be a fine place to discuss.

**Comment by rdeits** [comment]
Ok, thank you!

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 93 of 93 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6235#-:-Km6vQh0pBxt_bKb-v1l:bnfp4nl)*

**Pull request merged**
