### PR TITLE
Fix sign-compare warnings in systems/robotInterfaces

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
- Fix sign-compare warnings in systems/robotInterfaces.
- Stop suppressing sign-compare warnings in systems/robotInterfaces.

(This is a little bit of a trickier one, because we were doing subtraction on unsigned integers.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2717)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@ggould-tri for all review, please.

Note that the mac failure is a flake; everything else passed.

**Comment by ggould-tri** [comment]
Looks... something to me.  "Good" is possibly an overstatement.  Better than what was, anyway.  :lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/robotInterfaces/CMakeLists.txt, line 5 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2717#-KLahZB8IZUG7cjtxigl:-KLahZB9l8qcwxdX-ImP:677247605) ([raw file](https://github.com/robotlocomotion/drake/blob/f21013ff3109acbef84b0ef3205d48a4a14b1f2e/drake/systems/robotInterfaces/CMakeLists.txt#L5)):*
> ```CMake
>   # TODO(#2372) These are warnings that we can't handle yet.
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-sign-compare")
> endif()
> ```

Yay!

---

*[drake/systems/robotInterfaces/footstepCollocationConstraintsMex.cpp, line 40 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2717#-KLai82nSKdk1bDs6ei4:-KLai82nSKdk1bDs6ei5:-1352006835) ([raw file](https://github.com/robotlocomotion/drake/blob/52dcd475cc3b5701bade424178883f1b7d57bb90/drake/systems/robotInterfaces/footstepCollocationConstraintsMex.cpp#L40)):*
> ```cpp
>   double dx, dy, si, co;
> 
>   for (j = 2; j <= static_cast<int>(nsteps); j++) {
> ```

FYI -- I went down the rathole of trying to prove what this does for large `nsteps` and whether an upcast of `j` rather than a downcast of `nsteps` is more correct.  The results only made me sad, because numerics suck.

I believe the most correct solution would be to make `j` unsigned but your solution here is at least as readable and certainly not interestingly wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2717#-:-KLajiBPR9P64-tzCOB9:200378805)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/robotInterfaces/footstepCollocationConstraintsMex.cpp, line 40 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2717#-KLai82nSKdk1bDs6ei4:-KLakplJx0GPF1oByxRK:-661129790) ([raw file](https://github.com/robotlocomotion/drake/blob/52dcd475cc3b5701bade424178883f1b7d57bb90/drake/systems/robotInterfaces/footstepCollocationConstraintsMex.cpp#L40)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I went down the rathole of trying to prove what this does for large `nsteps` and whether an upcast of `j` rather than a downcast of `nsteps` is more correct.  The results only made me sad, because numerics suck.
> 
> I believe the most correct solution would be to make `j` unsigned but your solution here is at least as readable and certainly not interestingly wrong.
</details>
If there are ever more than 2**31 `nsteps` then (1) holy cow!, and (2) the correct answer is `int64_t` or `long long` depending on #2514.  Unsigned is a plague on arithmetic.  We wouldn't want it here in particular, because of the `j - 1` and `j - 2` expressions below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2717)*

**Comment by jwnimmer-tri** [comment]
Using override-merge due to mac flake.

**Comment by jwnimmer-tri** [comment]
FTR, this was a portion of #2372.

**Pull request merged**
