### PR TITLE
[workspace] Upgrade openusd_internal to latest release 24.11

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
https://github.com/PixarAnimationStudios/OpenUSD/blob/release/CHANGELOG.md

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22082)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please

FYI @hong-nvidia

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22082)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22082#-:-OAOeMo21Hk-yYGQbfXy:bnfp4nl)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review later this week, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22082)* status: LGTM missing from assignee xuchenhan-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22082)* status: 3 unresolved discussions

___
*[`tools/workspace/openusd_internal/package.BUILD.bazel` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22082#-OATLMov68HTWf-kbYmK:-OATM8zP0_3IHZUZVYco:bdni8em) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9fbb131b5fd30d304d3270d06e31bfd4e04d930/tools/workspace/openusd_internal/package.BUILD.bazel#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I haven't figured out where this file is generated.
</blockquote></details>

It actually lives in the upstream source tree, e.g.,

https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usd/usd/generatedSchema.classes.txt
___
*[`tools/workspace/openusd_internal/patches/nanocolor_namespace.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22082#-OATG2Ul2MNYNvTe-JsZ:-OATME0dB-BirLOA1H3r:bv31154) ([raw file](https://github.com/RobotLocomotion/drake/blob/b9fbb131b5fd30d304d3270d06e31bfd4e04d930/tools/workspace/openusd_internal/patches/nanocolor_namespace.patch#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm assuming this replaces symbol leak patch that's removed from this PR, right?
</blockquote></details>

Right!  Upstream accepted most of our patch; this little tweak (not for upstreaming) is all that remains.
___
*[`tools/workspace/openusd_internal/patches/usd_sdf_flex_hidden.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22082#-OATGXDpE-R8HBBD38oP:-OATMKew2wnzCW-mDRcR:bxay0sf) ([raw file](https://github.com/RobotLocomotion/drake/blob/68a11682c9f4768c16311c1165e339310d412a48/tools/workspace/openusd_internal/patches/usd_sdf_flex_hidden.patch#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What about the symbol leaks here? Why is this patch removed?
</blockquote></details>

Upstream deleted this code which needed patching.  Whatever its replacement was apparently doesn't need patching (probably uses the pxr_namespace correctly already.)

**Pull request merged**
