### PR TITLE
Add installation script for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by jamiesnape**
Obviously, Trusty support is winding down, but for now, we are building binary packages for supported platforms and that occurs on ephemeral, un-provisioned instances. Hence, we need a script to provision an instance for a Bazel-only build on Trusty.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6687)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-unprovisioned-gcc-bazel-experimental-snopt-packaging please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Done with read-through.  I will want to test it locally before the LGTM, but I suspect it will be fine.  +@sherm1 for platform review on-call, please.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5iGfELCzI4S3jelQd:-Kq5iGfFg_lIybIZfQp_:bu2dx41) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L7)):*
> ```Shell
> set -euo pipefail
> 
> apt-get update
> ```

FYI `apt update` to be modern, and consistent with the below.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5jLaIiI2ES7d6dtbh:-Kq5jLaIiI2ES7d6dtbi:b6s1b8c) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L17)):*
> ```Shell
> # Add APT repository for (clang|clang-format|lldb)-3.9.
> readonly lsb_release_codename="$(lsb_release -sc)"
> add-apt-repository "deb http://apt.llvm.org/${lsb_release_codename}/ llvm-toolchain-${lsb_release_codename}-3.9 main"
> ```

Unfortunately I think this command is not idempotent, which is one reason there is a prompt for it in the Xenial script.  (Every time the user runs this -- which may be frequently to "make sure I'm up to date", it will add another duplicate line to `sources.list`.)

I could live with a TODO here, or copy the prompt logic from xenial prereqs, or actually sensing whether its needed.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5ieNYbjUnWKslyDq8:-Kq5ieNYbjUnWKslyDq9:brvegp9) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L25)):*
> ```Shell
> # Add APT repository for oracle-java8-installer.
> add-apt-repository ppa:webupd8team/java
> echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
> ```

I can understand why CI needs this, but I'm not sure we should be agreeing to licenses on users' behalf.  Would it make more sense to move this into the CI code, instead of here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-:-Kq5jv-SAOVAMc6jvgM-:byqpr68)*

**Comment by jamiesnape** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5iGfELCzI4S3jelQd:-Kq8Yrf5swtjbwC2RpE7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI `apt update` to be modern, and consistent with the below.
</blockquote></details>

Done.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5jLaIiI2ES7d6dtbh:-Kq8YsyG-tREoQdPOcEj:b-ayocn6) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unfortunately I think this command is not idempotent, which is one reason there is a prompt for it in the Xenial script.  (Every time the user runs this -- which may be frequently to "make sure I'm up to date", it will add another duplicate line to `sources.list`.)

I could live with a TODO here, or copy the prompt logic from xenial prereqs, or actually sensing whether its needed.
</blockquote></details>

I would call it semi-idempotent to be nice, contradictory to the documentation to be indifferent, and broken otherwise. The documentation vaguely implies that they would be duplicated, but in practice, enabled repos are not duplicated, disabled ones, i.e., comments, are duplicated. Since this is a small repo and Ubuntu enable deb-src on all their repos anyway, I am punting on the issue with an `--enable-source` and comment.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 25 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq5ieNYbjUnWKslyDq8:-Kq8YsXbNgQPePmAzTM-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/abb5580b8b2feb8328103fdf7e13e8e769160636/setup/ubuntu/14.04/install_prereqs.sh#L25)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I can understand why CI needs this, but I'm not sure we should be agreeing to licenses on users' behalf.  Would it make more sense to move this into the CI code, instead of here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by sherm1** [comment]
Platform :lgtm:, assuming feature review includes a Trusty test.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-:-Kq8fQEbav1HzEC7l8Aw:b2ccoy)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

Tested locally in a clean schroot.

+@sherm1 for platform review on-call, please.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu_trusty.rst, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bZBCR_bIeJUdTQeW:-Kq8bZBCR_bIeJUdTQeX:b-kjoymf) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/drake/doc/ubuntu_trusty.rst#L15)):*
> ```reStructuredText
> Prerequisite setup is automated. Simply run::
> 
>     ./setup/ubuntu/14.04/install_prereqs.sh
> ```

I think this needs a `sudo` in front of it.

---

*[drake/doc/ubuntu_trusty.rst, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8dI900WGTbUWTJAtm:-Kq8dI900WGTbUWTJAtn:bjxmsts) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/drake/doc/ubuntu_trusty.rst#L17)):*
> ```reStructuredText
>     ./setup/ubuntu/14.04/install_prereqs.sh
> 
> After running the script, return to :doc:`from_source` to complete and test your
> ```

FYI Do we want to say "You will have to answer several prompts as the script proceeds." or something here?  No defect.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bk6kho2bLzH70Ukw:-Kq8bk6lzUf2PHeef8Nv:bjvnbf7) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/setup/ubuntu/14.04/install_prereqs.sh#L39)):*
> ```Shell
> g++-4.9
> g++-4.9-multilib
> g++-5
> ```

I'm not sure why we're adding GCC 5 items into this list?  I get that CROSSTOOL provides a way to choose it (intended for use on Xenial), but since its not in the CI or support matrix for Trusty, it seems like a waste for users to have it in the defaults.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-:-Kq8ewANN3I-4DivBo7q:b-garj8)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bk6kho2bLzH70Ukw:-Kq8mVp9Uu02Bmf0aSsl:b-8yjl3p) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/setup/ubuntu/14.04/install_prereqs.sh#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm not sure why we're adding GCC 5 items into this list?  I get that CROSSTOOL provides a way to choose it (intended for use on Xenial), but since its not in the CI or support matrix for Trusty, it seems like a waste for users to have it in the defaults.
</blockquote></details>

I could remove it, but it is useful for building packages with Xenial-like options for non-Docker Travis CI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bk6kho2bLzH70Ukw:-Kq8o8O1nhJcwVnKAQBX:b-z7k14t) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/setup/ubuntu/14.04/install_prereqs.sh#L39)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I could remove it, but it is useful for building packages with Xenial-like options for non-Docker Travis CI.
</blockquote></details>

Well, I'm not sure why we care about that kind of build, but even assuming we do, its not clear to me why the general user install script is a better place for that than the Travis-CI scripts.  In any case, if you really want to keep it in here that's OK, but it needs a comment explaining the rationale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bk6kho2bLzH70Ukw:-Kq8pRdALekRUwFDSb_g:bafmnfc) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/setup/ubuntu/14.04/install_prereqs.sh#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Well, I'm not sure why we care about that kind of build, but even assuming we do, its not clear to me why the general user install script is a better place for that than the Travis-CI scripts.  In any case, if you really want to keep it in here that's OK, but it needs a comment explaining the rationale.
</blockquote></details>

To be honest we should care about it more than 4.9 now, but it is not worth the complications given that Trusty is going away soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/ubuntu_trusty.rst, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bZBCR_bIeJUdTQeW:-Kq8poTEVmKM03Iukzyo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/drake/doc/ubuntu_trusty.rst#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this needs a `sudo` in front of it.
</blockquote></details>

Done.

---

*[drake/doc/ubuntu_trusty.rst, line 17 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8dI900WGTbUWTJAtm:-Kq8poHoNOGi5SgXign8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/drake/doc/ubuntu_trusty.rst#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Do we want to say "You will have to answer several prompts as the script proceeds." or something here?  No defect.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687)*

**Comment by jamiesnape** [comment]
The activities on Slack reminded me that I had not added the prereqs for actually running the precompiled Drake visualizer.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-:-Kq8xwmBbtZATuLiUHeM:bv5hcu)*

**Comment by jwnimmer-tri** [comment]
I forgot to test that, too.  I've confirmed that prior to this update I have a loader error, and with this update I get far enough for the X server to complain about my schroot.  We'll call that good enough.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/ubuntu/14.04/install_prereqs.sh, line 39 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-Kq8bk6kho2bLzH70Ukw:-Kq956liBDdo_E76wbCO:b-rido4v) ([raw file](https://github.com/robotlocomotion/drake/blob/ec974363505467100eb9fc176ec4212c726ade97/setup/ubuntu/14.04/install_prereqs.sh#L39)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

To be honest we should care about it more than 4.9 now, but it is not worth the complications given that Trusty is going away soon.
</blockquote></details>

FYI I would support _replacing_ 4.9 with 5 (or 6) if Trusty lives on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6687#-:-Kq95m6YMSvWmHyiGaNO:b-joem2s)*

**Pull request merged**
