### PR TITLE
Downgrades log level of joint welding and looping.

### PR DESCRIPTION
**Pull request by liangfok**
# Before

```
$ bazel run //drake/automotive:automotive_simulator_test
INFO: Found 1 target...
Target //drake/automotive:automotive_simulator_test up-to-date:
  bazel-bin/drake/automotive/automotive_simulator_test
INFO: Elapsed time: 17.783s, Critical Path: 14.85s

INFO: Running command line: bazel-bin/drake/automotive/automotive_simulator_test
Running main() from gtest_main.cc
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from AutomotiveSimulatorTest
[ RUN      ] AutomotiveSimulatorTest.BasicTest
[       OK ] AutomotiveSimulatorTest.BasicTest (3 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusSimpleCar
[2017-03-31 09:51:00.331] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.334] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.334] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.334] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.334] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.334] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.335] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.335] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.335] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.339] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.339] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.339] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.339] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[       OK ] AutomotiveSimulatorTest.TestPriusSimpleCar (21 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusSimpleCarInitialState
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.347] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.347] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.347] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.347] [console] [info] Adding joint rear_left_lidar_joint to the plant.
[       OK ] AutomotiveSimulatorTest.TestPriusSimpleCarInitialState (3 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusTrajectoryCar
[2017-03-31 09:51:00.350] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.350] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.350] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint front_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.350] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.350] [console] [info] Adding joint rear_left_lidar_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.352] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.352] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.352] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.365] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.365] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.365] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.365] [console] [info] Adding joint rear_left_lidar_joint to the plant.
[       OK ] AutomotiveSimulatorTest.TestPriusTrajectoryCar (18 ms)
[ RUN      ] AutomotiveSimulatorTest.TestMaliputRailcar
Welding joint base
[       OK ] AutomotiveSimulatorTest.TestMaliputRailcar (13 ms)
[ RUN      ] AutomotiveSimulatorTest.TestLcmOutput
[2017-03-31 09:51:00.381] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.381] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.381] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.381] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.383] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.383] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.383] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.383] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.384] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.388] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.388] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.388] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.388] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.392] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.392] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.393] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.393] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.393] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[2017-03-31 09:51:00.398] [console] [info] Adding joint chassis_floor_axle to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint steering to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint left_hub to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint left_pin to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint left_wheel_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint axle_tie_rod_arm to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint right_hub to the plant.
[2017-03-31 09:51:00.398] [console] [info] Made joint right_pin a loop joint.
[2017-03-31 09:51:00.398] [console] [info] Adding joint right_wheel_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint chassis_rear_axle to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint rear_left_wheel_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint rear_right_wheel_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint body to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint front_lidar_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint top_lidar_joint to the plant.
[2017-03-31 09:51:00.398] [console] [info] Adding joint rear_right_lidar_joint to the plant.
[2017-03-31 09:51:00.399] [console] [info] Adding joint rear_left_lidar_joint to the plant.
Welding joint front_lidar_joint
Welding joint top_lidar_joint
Welding joint rear_right_lidar_joint
Welding joint rear_left_lidar_joint
[       OK ] AutomotiveSimulatorTest.TestLcmOutput (21 ms)
[----------] 6 tests from AutomotiveSimulatorTest (79 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (79 ms total)
[  PASSED  ] 6 tests.
```
# After

```
$ bazel run //drake/automotive:automotive_simulator_test
INFO: Found 1 target...
Target //drake/automotive:automotive_simulator_test up-to-date:
  bazel-bin/drake/automotive/automotive_simulator_test
INFO: Elapsed time: 8.019s, Critical Path: 7.74s

INFO: Running command line: bazel-bin/drake/automotive/automotive_simulator_test
Running main() from gtest_main.cc
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from AutomotiveSimulatorTest
[ RUN      ] AutomotiveSimulatorTest.BasicTest
[       OK ] AutomotiveSimulatorTest.BasicTest (3 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusSimpleCar
[       OK ] AutomotiveSimulatorTest.TestPriusSimpleCar (16 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusSimpleCarInitialState
[       OK ] AutomotiveSimulatorTest.TestPriusSimpleCarInitialState (2 ms)
[ RUN      ] AutomotiveSimulatorTest.TestPriusTrajectoryCar
[       OK ] AutomotiveSimulatorTest.TestPriusTrajectoryCar (14 ms)
[ RUN      ] AutomotiveSimulatorTest.TestMaliputRailcar
[       OK ] AutomotiveSimulatorTest.TestMaliputRailcar (7 ms)
[ RUN      ] AutomotiveSimulatorTest.TestLcmOutput
[       OK ] AutomotiveSimulatorTest.TestLcmOutput (18 ms)
[----------] 6 tests from AutomotiveSimulatorTest (60 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (60 ms total)
[  PASSED  ] 6 tests.
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5678)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ggould-tri for feature review please since this relates to #3673.
+@sherm1 for platform review please.

Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-KgZhoC9tCn7dUmU4Y5j:b-32rihj)*

**Comment by ggould-tri** [comment]
What is the current state of #3673 issues?  I haven't been in Drake code for a while but IIRC a new robot implementer needs to see these messages to map coordinates to joints.  Has that been fixed?

If not, downgrading these messages to a level where users won't see them will make the #3673 situation worse.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-KgZj8kFnatrG4M7EBf_:bu1o5la)*

**Comment by liangfok** [comment]
#3673 is currently blocked on a complete revamp of both the RBT (to be replaced with MBT) and the SDF parser (to be replaced with `libsdformat`). @amcastro-tri, can you shed some light on whether #3673 will be relevant once we switch to MBT?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-KgZkwy2Z2nz8w7wdtO4:b-z6m2vh)*

**Comment by ggould-tri** [comment]
If 3673 is blocked, I don't think this should change without another workaround in place.  Obviously this change is good once mbt is in, but I worry that it is premature before that point.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-KgZmtB46cwugduR7RYw:bgjh6f6)*

**Comment by jwnimmer-tri** [comment]
Yeah.  Bazel mutes _all_ unit test output by default.  So having the logs in there isn't a problem, is it?

**Comment by sherm1** [comment]
Platform :lgtm:, but consider whether using SPDLOG_TRACE macro would be more appropriate (see below).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 367 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-Kg_C3UtOllB5FfXV6IG:-Kg_C3Uu0sKxMBLgSiOF:bsoklp1) ([raw file](https://github.com/robotlocomotion/drake/blob/7340b5050b9cedd074cb7d043849507d04107b3f/drake/multibody/rigid_body_tree.cc#L367)):*
> ```cpp
>       if (!hasChild) {
>         drake::log()->trace("Welding joint {}.",
>             bodies[i]->getJoint().get_name());
> ```

BTW, spdlog provides macros for the two lowest logging levels -- SPDLOG_TRACE and SPDLOG_DEBUG. SPDLOG_TRACE would generate identical code as here, but only in Debug builds -- in Release it removes the code altogether along with the overhead involved in figuring out that it is not enabled. If this is only for debugging, consider whether using the macro would be better here.

---

*[drake/multibody/parsers/sdf_parser.cc, line 576 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-Kg_DH2tnL_OBcgnHqvu:-Kg_DH2tnL_OBcgnHqvv:bsrjdv0) ([raw file](https://github.com/robotlocomotion/drake/blob/7340b5050b9cedd074cb7d043849507d04107b3f/drake/multibody/parsers/sdf_parser.cc#L576)):*
> ```cpp
>     // This log statement is required for users to work around #3673, and can
>     // be removed when that issue is resolved.
>     drake::log()->trace("Made joint {} a loop joint.", name);
> ```

BTW, same comment here and below -- consider using the SPDLOG_TRACE macro.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-Kg_DQIx0Us3DWQGpLxw:b9yriu3)*

**Comment by liangfok** [comment]
Thanks for the reviews. I will close this PR based on the above-mentioned concerns.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_tree.cc, line 367 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-Kg_C3UtOllB5FfXV6IG:-Kg_OXYPOZRbMSwopms-:b-3t2nth) ([raw file](https://github.com/robotlocomotion/drake/blob/7340b5050b9cedd074cb7d043849507d04107b3f/drake/multibody/rigid_body_tree.cc#L367)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, spdlog provides macros for the two lowest logging levels -- SPDLOG_TRACE and SPDLOG_DEBUG. SPDLOG_TRACE would generate identical code as here, but only in Debug builds -- in Release it removes the code altogether along with the overhead involved in figuring out that it is not enabled. If this is only for debugging, consider whether using the macro would be better here.
</blockquote></details>

Thanks for the info. I'll keep it in mind next time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5678#-:-Kg_OI8V7sA7Zq8VNekY:b-i8kj3d)*

**Pull request closed without merging**
