### PR TITLE
Move non-general utilities into robotInterfaces QP controllers

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #6464, in that it's difficult to make `//drake/util` well-phrased with so much going on in there.

All of the method declarations and definitions are just cut-paste of code (+ nolint tags).  The using-statments, includes, and BUILD rules are fixed up by hand.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7363)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.

**Comment by siyuanfeng-tri** [comment]
:lgtm: thanks @jwnimmer-tri 

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7363#-:-KxrgItT1rcvafD2-YbF:b8jlb3p)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7363#-:-KxrivYdxBYuvI2nVFyE:bnfp4nl)*

**Pull request merged**
