### PR TITLE
Initial jammy support

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Relates: #16217, #17185

Start adding support for Jammy. This should get things past the initial setup and past the build setup to the point where a build can start actually compiling code. However, it is expected to error at that point (at least, my local build didn't complete).

This should, however, be enough that we can start showing that CI is working.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17312)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please.

**Comment by mwoehlke-kitware** [comment]
+@svenevs for feature review, please.

**Review by svenevs — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, 3 of 3 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17312)* status: 1 unresolved discussion, LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mwoehlke-kitware and @svenevs)

___
*[`tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17312#-N3Zt7odCZ5xfNJMSG6h:-N3Zt7odCZ5xfNJMSG6i:by76hvg) ([raw file](https://github.com/robotlocomotion/drake/blob/d40db02d38e8d3ff9bc43fe61473ca5367d434aa/tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel#L1)):*
> ```
> package-ubuntu-20.04.BUILD.bazel
> ```

I'm not sure what's going on here.  It seems to need a newline at the end of the file, and it also seems that this makes it point to the sibling file.  Should we just load `package-ubuntu.BUILD.bazel` instead if they are both the same?

**Comment by jwnimmer-tri** [comment]
*[`tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17312#-N3Zt7odCZ5xfNJMSG6h:-N3ZuJ_0EHyb0zLDIGlD:b-bipwxz) ([raw file](https://github.com/robotlocomotion/drake/blob/d40db02d38e8d3ff9bc43fe61473ca5367d434aa/tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel#L1)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

I'm not sure what's going on here.  It seems to need a newline at the end of the file, and it also seems that this makes it point to the sibling file.  Should we just load `package-ubuntu.BUILD.bazel` instead if they are both the same?
</blockquote></details>

OK This is just how symlinks show up in reviewable (see "symlink" in the UI header of this file); the red unicode thing is not a problem.

Renaming the file as you suggest might be better than symlinking, but in any case in #17288 I'm going to repave this whole directory so it doesn't much matter.

**Review by svenevs — COMMENTED** [review]
:lgtm: +@sammy-tri for platform review please.  Context: these commits enable the jammy CI configuration to actually begin building drake itself.  The failed [jammy-gcc-everything](https://drake-jenkins.csail.mit.edu/job/linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release/4/consoleFull) and [jammy-clang-everything](https://drake-jenkins.csail.mit.edu/job/linux-jammy-unprovisioned-clang-bazel-experimental-everything-release/2/consoleFull) builds are actually indicators of success here -- the unprovisioned CI is able to obtain all of its dependencies via `setup/` scripts as well as a newly available `vtk` archive to download.

We are not trying to fix the build failures within drake for the two jammy jobs that failed in this PR.

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17312#-:-N3Zv2S57mVgsU5XLlJP:b-c1y2ko)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

___
*[`tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel` line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17312#-N3Zt7odCZ5xfNJMSG6h:-N3ZuqaK7eYsoxUMIEeb:b-pa6wl4) ([raw file](https://github.com/robotlocomotion/drake/blob/d40db02d38e8d3ff9bc43fe61473ca5367d434aa/tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK This is just how symlinks show up in reviewable (see "symlink" in the UI header of this file); the red unicode thing is not a problem.

Renaming the file as you suggest might be better than symlinking, but in any case in #17288 I'm going to repave this whole directory so it doesn't much matter.
</blockquote></details>

Ok great, works for me! :+1:

**Comment by mwoehlke-kitware** [comment]
FYI, on the assumption that we want to hang a notice of Jammy support off of something *other* than this, I am applying +(release notes: none). Please change if you disagree!

**Comment by jwnimmer-tri** [comment]
Re "properly curated" -- it will probably be a pain for Sam (or Stephen?) to do a full `bazel test //..` locally to prove that each commit passes (on focal) on its own, especially for the setup script changes (to be tested in a Docker).  I suggest changing to "squash" as the plan for this PR.  I don't think the independent commit history here is important to survive beyond the PR process. Curated commits for unprovisioned changes are fairly awkward.

That also reminds me: this needs _Focal_ unprovisioned Jenkins testing as well, since it changes the setup scripts.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-everything-release please.

> Re "properly curated" -- it will probably be a pain for Sam (or Stephen?) to do a full bazel test //.. locally to prove that each individual commit passes (on focal) on its own

I removed it, we can just squash at merge rather than Matthew squash and re-push right?

> hang a notice of Jammy support off of something other than this

Sounds right to me, we should save that for when we finish fixing the build errors in drake.

**Comment by jwnimmer-tri** [comment]
> I removed it, we can just squash at merge rather than Matthew squash and re-push right?

That's fine, yes.

>> hang a notice of Jammy support off of something other than this
>
> Sounds right to me, we should save that for when we finish fixing the build errors in drake.

Either way is fine with me.  We definitely want a release note once it's fully ready.  In the meantime, it would be OK if you prefer to have a release note "Jammy support is in progress" but _shrug_ it's probably not that meaningful.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17312#-:-N3_zPFV1SW2_L7wJcoD:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Pull request merged**
