### PR TITLE
MathematicalProgram should not be copyable, assignable or movable

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4493)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@soonho-tri for feature review. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-:-KYw1xqZYLzuTSkzDltx:b77brch)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-:-KYxtVzn9z_1HRk_OQva:bnfp4nl)*

**Comment by hongkai-dai** [comment]
+@sammy-tri for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-:-KYyA88_CNlzrvPJ6Ome:bpk00vl)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-KYygFL2j2hfGkNt1t0G:-KYygFL2j2hfGkNt1t0H:bxu4rmf) ([raw file](https://github.com/robotlocomotion/drake/blob/8c428b5216f14b12ecf2266548fd26d639bae718/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc#L110)):*
> ```cpp
>   // The order of insertion is important, the rest of the program assumes this
>   // layout.
>   prog_ = solvers::MathematicalProgram();
> ```

Removing this seems to violate the documentation for ResizeQP which says that it reinitializes the program to be the correct size.  Perhaps making prog_ a unique_ptr to a MathematicalProgram would allow it to be deleted and recreated in this function, and thus still fulfill the documentation?  Alternate approaches would include changing the documentation (and probably the function name) and to only add variables to prog_ once ever for the life of the qp controller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc, line 110 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-KYygFL2j2hfGkNt1t0G:-KZ-t5YS9sPQp0aPNyIx:b-amh0gu) ([raw file](https://github.com/robotlocomotion/drake/blob/8c428b5216f14b12ecf2266548fd26d639bae718/drake/examples/QPInverseDynamicsForHumanoids/qp_controller.cc#L110)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Removing this seems to violate the documentation for ResizeQP which says that it reinitializes the program to be the correct size.  Perhaps making prog_ a unique_ptr to a MathematicalProgram would allow it to be deleted and recreated in this function, and thus still fulfill the documentation?  Alternate approaches would include changing the documentation (and probably the function name) and to only add variables to prog_ once ever for the life of the qp controller.
</blockquote></details>

Done. Thanks! That is a very good point. I changed it to a unique pointer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4493#-:-KZ27q_ERAP3Trlux3qZ:bnfp4nl)*

**Pull request merged**
