### PR TITLE
Update BUILD to track recent PRs

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4284)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/BUILD, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4284#-KXkWJUlr3zUfNJsWeIK:-KXkWJUlr3zUfNJsWeIL:bggb51a) ([raw file](https://github.com/robotlocomotion/drake/blob/2cde05832e58c2491303a67a0449fe501809afc1/drake/solvers/BUILD#L18)):*
> ```Python
>     name = "mathematical_program",
>     srcs = [
>         "decision_variable.cc",
> ```

BTW there are some .h files in this list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4284#-:-KXkWLFJtDIzD_PEUjtK:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
*[drake/solvers/BUILD, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4284#-KXkWJUlr3zUfNJsWeIK:-KXkWbHugKYdrKADcolQ:b-1egigo) ([raw file](https://github.com/robotlocomotion/drake/blob/2cde05832e58c2491303a67a0449fe501809afc1/drake/solvers/BUILD#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW there are some .h files in this list.
</blockquote></details>

Is there a better way to list private headers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4284)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/solvers/BUILD, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4284#-KXkWJUlr3zUfNJsWeIK:-KXkXJ7Xe9l8FkSP8Iml:b-83og3x) ([raw file](https://github.com/robotlocomotion/drake/blob/2cde05832e58c2491303a67a0449fe501809afc1/drake/solvers/BUILD#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is there a better way to list private headers?
</blockquote></details>

Nope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4284)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4284)*

**Pull request merged**
