### PR TITLE
[framework] Tidy up ValueProducer loose ends

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These fix some code review questions that were noted during the PR train.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews, please.  No hurry here -- I've sat on this for a few weeks developing myself, so it's fine if it takes a few more weeks to land.

**Review by sherm1 — COMMENTED** [review]
:lgtm: x 2 with one suggested change

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557#-:-MgIYk4P3HNDdVrDQKtZ:b-yynm84)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgIYNXl4ljsi5AVDh0M:b-oa477h) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
> ```objc
>       void (SomeClass::*calc)(const SomeContext&, SomeOutput*) const) {
>     static_assert(std::is_base_of_v<ContextBase, SomeContext>,
>                   "The inferred type of SomeContext was invalid.");
> ```

BTW this could be more specific. Consider something like "The inferred type of SomeContext must derive from ContextBase."

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgIZAJr1430T4IcahGk:b-bp1318) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this could be more specific. Consider something like "The inferred type of SomeContext must derive from ContextBase."
</blockquote></details>

I considered that (since the LeafSystem code does similarly), but "ContextBase" seemed a bit too inside-baseball, and anywhere is right there on the prior line for the user to read.

Coming back to it here now with fresh eyes, maybe I could say "The inferred type of SomeContext was not a Context<T> or similar" and that would probably be the most helpful?

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgIa9rU5L6qpkVeGCDT:b-1imxh0) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I considered that (since the LeafSystem code does similarly), but "ContextBase" seemed a bit too inside-baseball, and anywhere is right there on the prior line for the user to read.

Coming back to it here now with fresh eyes, maybe I could say "The inferred type of SomeContext was not a Context<T> or similar" and that would probably be the most helpful?
</blockquote></details>

That would be OK, but I think you could just say "The inferred type of SomeContext must derive from Context." The test is _slightly_ more permissive than that but only some obscure test cases are going to have classes that derive from ContextBase but not Context.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: 1 unresolved discussion (waiting on @sherm1)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgIb_dtCcTcqIrqfPvh:b-l2up1f) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That would be OK, but I think you could just say "The inferred type of SomeContext must derive from Context." The test is _slightly_ more permissive than that but only some obscure test cases are going to have classes that derive from ContextBase but not Context.
</blockquote></details>

Maybe `"The inferred type of SomeContext was invalid; typically it should be Context<T>"`?  It would be extremely unusual for a user to having anything other than `Context<T>` in their calc callback.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgLwZyU6tRP_w-2N8ct:b4ruo3t) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe `"The inferred type of SomeContext was invalid; typically it should be Context<T>"`?  It would be extremely unusual for a user to having anything other than `Context<T>` in their calc callback.
</blockquote></details>

That sounds good.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @sherm1)

___
*[systems/framework/value_producer.h, line 440 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15557#-MgIYNXl4ljsi5AVDh0L:-MgM4cBz10VvYmsifLlq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/354e92ad922169651a4e8cbce4e6b4d183ed5015/systems/framework/value_producer.h#L440)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

That sounds good.
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15557)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
