### PR TITLE
workspace: Bump fcl to latest commit on master

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
As part of platform reviewer duties, per request on Slack: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1609951566108100

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14497)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
+@seancurtis-tri for both reviews, please.

\cc @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14497#-:-MQNss7k10O0C0jsJku8:b-depynx)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14497#-MQNsqZkBeGtspCpi96s:-MQNsqZl1L5DnKbLrRz3:b-or4oud) (no related file):*
Working: Block for Mac CI.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: Deferring to @ericcousineau-tri on what he wants to do vis-a-vis the blocking mac.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14497#-:-MQTjx0cARyH8PVKP5Ax:b-llfgz0)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14497#-MQNsqZkBeGtspCpi96s:-MQTjpFR2c4POyrYoXWH:b9kl0uc) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Block for Mac CI.
</blockquote></details>

Is this related to the recent breakage we had in mac CI (now fixed)?

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14497)* status: needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14497#-MQNsqZkBeGtspCpi96s:-MQTsv5--HTRiuIAY4-g:b38frad) (no related file):*
OK Passed!
---
> Is this related to the recent breakage we had in mac CI (now fixed)?

Er, not sure if I understand - it passed here, so why would it relate to any failures?
(Or are you asking if this is a fix for it?)

I did this based on Jeremy's request in Slack.

---

**Comment by EricCousineau-TRI** [comment]
Ah, but to clarify: This is a third-party bump, which I thought we normally run Mac CI on.

Lemme see if I can substantiate it, or if I was just going off of superstition...

**Comment by EricCousineau-TRI** [comment]
Aha! Substantiated:
https://drake.mit.edu/code_review_checklist.html#did-you-change-third-party-software

**Pull request merged**
