### PR TITLE
[geometry] Take care of centroids of zero-area polygons in PolygonSurfaceMesh

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Relevant to issue #16244.

I have created another PR #16258 for ease of testing the rolling sphere example.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 
+@rpoyner-tri for feature review, please.

CC: @joemasterjohn 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257#-:-MsbWFJl7mArqirXzdeU:br4u9m3)* status: LGTM missing from assignees DamrongGuoy,rpoyner-tri(platform), missing label for release notes (waiting on @DamrongGuoy and @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy, missing label for release notes (waiting on @DamrongGuoy)

___
*[geometry/proximity/polygon_surface_mesh.cc, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16257#-Msf6x35A-WOegPoX9Wh:-Msf6x35A-WOegPoX9Wi:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/eec5a403d2dae34f260436acad8c1632cb0cc391/geometry/proximity/polygon_surface_mesh.cc#L175)):*
> ```cpp
>   } else {
>     // The accumulated total area is still zero, so we simply use the last
>     // entry of element_ceontroid_M_ as a temporary solution for now. If the
> ```

typo



_Code quote:_
```cpp
ceontroid
```
___
*[geometry/proximity/test/polygon_surface_mesh_test.cc, line 443 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16257#-MsfGSa56z0wFXmbnw-l:-MsfGSa56z0wFXmbnw-m:bnbg4tp) ([raw file](https://github.com/robotlocomotion/drake/blob/eec5a403d2dae34f260436acad8c1632cb0cc391/geometry/proximity/test/polygon_surface_mesh_test.cc#L443)):*
> ```cpp
>   EXPECT_EQ(zero_area_mesh_M.face_normal(0), Vector3d::Zero());
>   EXPECT_EQ(zero_area_mesh_M.area(0), 0.0);
> }
> ```

BTW, does it make sense to test the situation where the averaged point is not in the "middle"? Perhaps {3,0,0,1},{p1, p2}? If it's obvious enough from a geometry POV, feel free to ignore this.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)* status: LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy, missing label for release notes (waiting on @rpoyner-tri)

___
*[geometry/proximity/polygon_surface_mesh.cc, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16257#-Msf6x35A-WOegPoX9Wh:-MsfJIdx5Rk6DLmVwb92:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/eec5a403d2dae34f260436acad8c1632cb0cc391/geometry/proximity/polygon_surface_mesh.cc#L175)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done. Thanks.
___
*[geometry/proximity/test/polygon_surface_mesh_test.cc, line 443 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16257#-MsfGSa56z0wFXmbnw-l:-MsfPu3-3nBQwiJ4eusD:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/eec5a403d2dae34f260436acad8c1632cb0cc391/geometry/proximity/test/polygon_surface_mesh_test.cc#L443)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, does it make sense to test the situation where the averaged point is not in the "middle"? Perhaps {3,0,0,1},{p1, p2}? If it's obvious enough from a geometry POV, feel free to ignore this.
</blockquote></details>

Done. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy, missing label for release notes (waiting on @DamrongGuoy)

___
*[geometry/proximity/test/polygon_surface_mesh_test.cc, line 436 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16257#-MsfWpKc5-FDOn3U3vsP:-MsfWpKc5-FDOn3U3vsQ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/1c55e5c9b3448add26a90153637ea7ca43b0d562/geometry/proximity/test/polygon_surface_mesh_test.cc#L436)):*
> ```cpp
> 
>   // This expected centroid p_MC assumes that our code falls back from
>   // area-weigthed averaging to arithmetic averaging for zero-area polygons.
> ```

typo



_Code quote:_
```cpp
weigthed
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)* status: LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy, missing label for release notes (waiting on @rpoyner-tri)

___
*[geometry/proximity/test/polygon_surface_mesh_test.cc, line 436 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16257#-MsfWpKc5-FDOn3U3vsP:-MsfnKmyDdZJ1sdYkLYM:boyexbg) ([raw file](https://github.com/robotlocomotion/drake/blob/1c55e5c9b3448add26a90153637ea7ca43b0d562/geometry/proximity/test/polygon_surface_mesh_test.cc#L436)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done. Thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257)* status: LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy, missing label for release notes (waiting on @DamrongGuoy)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: yes) 
+@sammy-tri for lpatform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257#-:-MsfvHmv4hCG_g06hleV:beoqqp0)* status: LGTM missing from assignees rpoyner-tri(platform),DamrongGuoy,sammy-tri(platform) (waiting on @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257#-:-MsfvU7C5Dt9iUhSVe-B:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),DamrongGuoy (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257#-:-MsgZQty74eWQzeC847m:bnfp4nl)* status: LGTM missing from assignee DamrongGuoy (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
I'm not sure why Reviewable wants me to `lgtm` myself. Well...:lgtm:



> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16257#-:-Msg_YXUBh9Qxp30I1lo:bhsu05g)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform),DamrongGuoy (waiting on @DamrongGuoy)

**Comment by jwnimmer-tri** [comment]
It's because of this:
image

**Comment by DamrongGuoy** [comment]
I see. Thanks!   I accidentally put myself into `Assignees` (though not `Reviewers`).

**Pull request merged**
