### PR TITLE
Replaced "mobilizer" with "joint".

### PR DESCRIPTION
**Pull request by liangfok**
We decided to use "joint" publicly and "mobilizer" internally within technical contexts.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3515)

### CODE REVIEW

**Comment by liangfok** [comment]
+@sherm1 for both levels of review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS3-QDHqBAl1EkLIQHz:b-9j5084)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS3S-VU0YxQnBxfivdS:-KS3S-VU0YxQnBxfivdT:bjjb725) ([raw file](https://github.com/robotlocomotion/drake/blob/7227d814232e15d3cc7c0b4358062cbeb68c7262/drake/systems/plants/RigidBodyTree.h#L50)):*
> ```objc
>  * </pre>
>  *
>  * Each RigidBody object maintains indices to its joint's generalized
> ```

Since there will be multiple joints connected to a given rigid body I think an adjective would be good here to clarify. How about "tree joint" or "inboard joint"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by liangfok** [comment]
@sherm1, I addressed you comments. PTAL. Thanks.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS3S-VU0YxQnBxfivdS:-KS3X9EZoaBwofZWpJH2:bdiqw1z) ([raw file](https://github.com/robotlocomotion/drake/blob/7227d814232e15d3cc7c0b4358062cbeb68c7262/drake/systems/plants/RigidBodyTree.h#L50)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Since there will be multiple joints connected to a given rigid body I think an adjective would be good here to clarify. How about "tree joint" or "inboard joint"?
</details>
Done.

BTW, Drake's `RigidBody` currently only supports one joint. Should I create an issue saying more than one joint should be addable to a RigidBody?

http://drake.mit.edu/doxygen_cxx/class_rigid_body.html#aa47302f0a8f447b298165cbf8a97d063

https://github.com/RobotLocomotion/drake/blob/2bce50fd01ced9497a2511f917cc6b7ceb18aa09/drake/systems/plants/RigidBody.h#L346

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS3Y1mXJ7CMr3BBtgtu:b-29qph8)*

**Comment by jwnimmer-tri** [comment]
@liangfok Adding a few `inboard`s here and there is just as wrong as adding a few `mobilizer` here or there.  If we are going to adopt a new term, we should do it thoughtfully and pervasively, with appropriate citations to the semantics of the term.  You should push back when people approach your shed with new paint, not take every review comment at face value.  You are the author (or this PR)!  You have the last say!

@sherm1 The goal of this PR is to remove an obscure term from the docs, that seeped through an earlier abortive attempt to adopt new terminology.  Can we please just merge it as such, and not pile on future improvements in a sub-standard way?

**Comment by sherm1** [comment]
> Drake's RigidBody currently only supports one joint. 

What I meant was that a rigid body will be involved in many joints. It will serve as a child once, but can be the parent an arbitrary number of times (think of a torso). So if I say "the torso's joint" it is ambiguous.

@jwnimmer-tri: I see new text that went from unambiguous to ambiguous; I think it makes sense not to make it intentionally ambiguous. I'm fine with any phrase that distinguishes the joint we're talking about from the many other possible joints; "tree joint" doesn't introduce any controversial words. "the joint connecting it to its parent" would also be fine. It just shouldn't be left with no adjective.

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/RigidBodyTree.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS3S-VU0YxQnBxfivdS:-KS3bV5YoNEm2uli-vuK:bkzosxu) ([raw file](https://github.com/robotlocomotion/drake/blob/7227d814232e15d3cc7c0b4358062cbeb68c7262/drake/systems/plants/RigidBodyTree.h#L50)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done.
> 
> BTW, Drake's `RigidBody` currently only supports one joint. Should I create an issue saying more than one joint should be addable to a RigidBody?
> 
> http://drake.mit.edu/doxygen_cxx/class_rigid_body.html#aa47302f0a8f447b298165cbf8a97d063
> 
> https://github.com/RobotLocomotion/drake/blob/2bce50fd01ced9497a2511f917cc6b7ceb18aa09/drake/systems/plants/RigidBody.h#L346
</details>
I am unable to find where in RigidBodyTree or its related classes where it has "multiple joints connected to a given rigid body".  What I am missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by jwnimmer-tri** [comment]
Our messages crossed in flight.

I think it was clear as written without `inboard` (RigidBody.joint is a single thing, the other joints are not in scope for a body), but I guess extra verbiage is fine, as long as we don't go overboard.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS3cS3v7N9wcUF_mlQj:bk3z354)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS3g4JfhukHXamDb9aZ:bnfp4nl)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by liangfok** [comment]
@jwnimmer-tri and @sherm1, I addressed your comments. PTAL.

I obviously need to fine-tune my bike-shed-paint detection and rejection algorithm. :smiley: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS3S-VU0YxQnBxfivdS:-KS4B5arDAdY9qQPrBk8:b-7nzc7j) ([raw file](https://github.com/robotlocomotion/drake/blob/7227d814232e15d3cc7c0b4358062cbeb68c7262/drake/systems/plants/RigidBodyTree.h#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am unable to find where in RigidBodyTree or its related classes where it has "multiple joints connected to a given rigid body".  What I am missing?
</details>
I believe @sherm1's comments answers this question. The "other" joints are those that connect a `RigidBody` "down" the `RigidBodyTree`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS4AvX_XDItn6ZFrd2m:bx2e3cc)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/RigidBodyTree.h, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS4CeyYuRASHrRzimcg:-KS4CeyYuRASHrRzimch:b-ughku6) ([raw file](https://github.com/robotlocomotion/drake/blob/9f09f87bd883e30ace927dc527fa4c82a06f9a4f/drake/systems/plants/RigidBodyTree.h#L52)):*
> ```objc
>  * Each RigidBody maintains for its joint that connects to its parent the
>  * joint's generalized coordinate vector and generalized velocity vector in the
>  * RigidBodyTree's generalized state vector.
> ```

I don't think this is true now.  It used to say "maintains indices into the RBT vector".  Now it says "maintains ... the joint's vector in the RBT ... vector".  The word "indices" was important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by liangfok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.h, line 52 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS4CeyYuRASHrRzimcg:-KS4HyXbiQV7rWjnkeXS:b-mm2i46) ([raw file](https://github.com/robotlocomotion/drake/blob/9f09f87bd883e30ace927dc527fa4c82a06f9a4f/drake/systems/plants/RigidBodyTree.h#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I don't think this is true now.  It used to say "maintains indices into the RBT vector".  Now it says "maintains ... the joint's vector in the RBT ... vector".  The word "indices" was important.
</details>
Oops! Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri
It is a mouthful now, but clear enough and correct.  :lgtm:.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS4J6YYYGExnor9otkl:b-12qaek)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by liangfok** [comment]
Thanks. Yes, we really need to figure out how to express these complex ideas more concisely.

Just waiting on CI now.

**Comment by jwnimmer-tri** [comment]
Not having to document vector sub-index math would be a good start.  Then (most of) that whole comment goes poof.

**Comment by liangfok** [comment]
Yes, updating the `RigidBodyTree` software abstractions to allow users to avoid needing to do complex index management is on @amcastro-tri's TODO list.

**Comment by jwnimmer-tri** [comment]
CI flake is windows executor something something.  We should override-merge once reviewable's portion is ready.

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/RigidBodyTree.h, line 50 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-KS3S-VU0YxQnBxfivdS:-KS617phhgQLTh3_9UMC:b-bsk9qy) ([raw file](https://github.com/robotlocomotion/drake/blob/7227d814232e15d3cc7c0b4358062cbeb68c7262/drake/systems/plants/RigidBodyTree.h#L50)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I believe @sherm1's comments answers this question. The "other" joints are those that connect a `RigidBody` "down" the `RigidBodyTree`.
</details>
@sherm1, this thread is blocked on you. PTAL. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515)*

**Comment by sherm1** [comment]
All clear now, @liangfok.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS7Hh4pirch9F_4-AB_:b-upvj8k)*

**Comment by liangfok** [comment]
@sherm1: Thanks! 

@jwnimmer-tri: Can you override merge this please? Thanks.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3515#-:-KS7It27EVU2wADW0GBO:bu1hvh5)*

**Comment by jwnimmer-tri** [comment]
Using override-merge because jenkins lost its brain, and this is a comment-only change.

**Pull request merged**
