### PR TITLE
[C-IRIS] Add unit length vector constraint when searching for separating plane

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJJZizqEgOo30hH9Fhg:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
I need some of the math in the Matrix-Sos condition explained to me I believe.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJL0bdY2JIkHgm226af:b-1wbys)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKuGpl0kUCNfsAXsOU:-NJKuGpl0kUCNfsAXsOV:b-kheaug) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L156)):*
> ```objc
>     VectorX<symbolic::Polynomial> s_upper;
>     // λ₄(y, s) in the documentation.
>     symbolic::Polynomial y_square;
> ```

why do we need a restriction on the norm of y?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKu8WE5FHr85hFlX9j:-NJKu8WE5FHr85hFlX9k:bnn1ftl) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L259)):*
> ```objc
>   // Then we impose the condition
>   // p(y, s) - λ₁(y, s)ᵀ(d−Cs) − λ₂(y, s)ᵀ(s−s_lower) − λ₃(y, s)ᵀ(s_upper−s) -
>   // λ₄(y, s)(1−yᵀy) is sos.
> ```

Sorry I am slow, but why do we need `1-y^Ty`?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKrKIVDsvDYHNbmDGM:-NJKrKIVDsvDYHNbmDGN:bosn7lk) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L283)):*
> ```objc
> 
>   // Sometimes we need to impose that a certain matrix of polynomials are always
>   // psd (for example with sphere or capsule collision geometries), we will use
> ```

this comma should be a period



_Code quote:_
```objc
geometries), we will
```
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKuPG9DgCqLyP0g383:-NJKuPG9DgCqLyP0g384:b-twqble) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L3)):*
> ```cpp
> #include "drake/geometry/optimization/dev/cspace_free_polytope.h"
> 
> #include <iostream>
> ```

Was this intentional?
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKwxC-867PgWCDNcjU:-NJKwxC-867PgWCDNcjV:buphq8r) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
> ```cpp
>   // p(y, s) - λ₁(y, s)ᵀ(d−Cs) − λ₂(y, s)ᵀ(s−s_lower) − λ₃(y, s)ᵀ(s_upper−s) -
>   // λ₄(y, s)(1−yᵀy) being sos, we only need λ₁(y, s) λ₂(y, s) and λ₃(y, s) to
>   // be quadratic polynomials of y and λ₄(y, s) to be an affine polynomial of s.
> ```

While I agree that this is the minimum degree required for our multipliers, I don't believe it is accurate to say that it is sufficient in general. However, for the purposes of implementation I believe this is a fine thing to hope to hold.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 626 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKyMH5E0veeDJyM9Ac:-NJKyMH5E0veeDJyM9Ad:b-2qo08a) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L626)):*
> ```cpp
>   }
>   // This Lagrangian is just an affine polynomial of s.
>   ret.y_square = prog->NewFreePolynomial(s_set_, 1);
> ```

I don't believe I agree with this. The multiplier need to be non-negative polynomials in the semi-algebraic case
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 642 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKyuIU1gZktK_enPuH:-NJKyuIU1gZktK_enPuI:b-2gi9n8) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L642)):*
> ```cpp
>       &gram);
>   prog->AddPositiveSemidefiniteConstraint(gram);
>   const symbolic::Polynomial poly_sos =
> ```

Unless I missed something, I think this poly_sos is only a function of `y`? Doesn't it need to be a function of both `s` and `y`? Is this because you have assumed that the LHS is an affine function of `s` that we need all the `s` to cancel?

**Review by hongkai-dai — COMMENTED** [review]
Sorry I missed some steps when I document the matrix-sos condition. I added more explanations, do you think it is clear now?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJLpZLr4PdDM8eynZeE:b695u99)* status: 7 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKuGpl0kUCNfsAXsOU:-NJLtbJJBJ4yhsgaZ5BT:bysokq7) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L156)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

why do we need a restriction on the norm of y?
</blockquote></details>

Done. I added more documentation.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKu8WE5FHr85hFlX9j:-NJLtrnZEFaNyCpg8-yG:bkkzrup) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L259)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Sorry I am slow, but why do we need `1-y^Ty`?
</blockquote></details>

Done. I added more documentation. Sorry I missed this step in the previous version.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 283 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKrKIVDsvDYHNbmDGM:-NJLu2FhE5JVlEgINYiN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.h#L283)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

this comma should be a period
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKuPG9DgCqLyP0g383:-NJLu3J_BT3ppTOQaLh6:b-2xn54s) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L3)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

Done. Good catch, it was used when I debug the code.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKwxC-867PgWCDNcjU:-NJLuWscE2AiCQHrLcUz:bh2s5rh) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

While I agree that this is the minimum degree required for our multipliers, I don't believe it is accurate to say that it is sufficient in general. However, for the purposes of implementation I believe this is a fine thing to hope to hold.
</blockquote></details>

Done. I added some more documentation.

I believe when p(y, s) is quadratic in y and linear in s, with the highest-degree monomial in the form yᵢ²sⱼ, then it is sufficient to set λ₁(y, s) λ₂(y, s) and λ₃(y, s) to be quadratic polynomials of y and λ₄(y, s) to be an affine polynomial of s, so that we can match the degree of p(y, s)?

With λ₁(y, s) λ₂(y, s) and λ₃(y, s) to be quadratic polynomials of y, we have λ₁(y, s)ᵀ(d−Cs),  − λ₂(y, s)ᵀ(s−s_lower)  and − λ₃(y, s)ᵀ(s_upper−s) all containing the monomials yᵢ²sⱼ, yᵢ², sⱼ. Similarly with λ₄(y, s) to be an affine polynomial of s, then λ₄(y, s)(1−yᵀy) will contain term sⱼ and yᵢ²sⱼ. So each monomial in p(y, s) can be cancelled out.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 626 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKyMH5E0veeDJyM9Ac:-NJLw2Kj-DHm5-wSZPDR:b6x4gsu) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L626)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I don't believe I agree with this. The multiplier need to be non-negative polynomials in the semi-algebraic case
</blockquote></details>

Done. I added more documentation.

I don't mean to use the semi-algebraic set {y | yᵀy <= 1}, but the algebraic set { y | yᵀy=1}, hence I only need a free polynomial Lagrangian here.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 642 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKyuIU1gZktK_enPuH:-NJLwUeEDv2Bmliez6AZ:bp1zi8o) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L642)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Unless I missed something, I think this poly_sos is only a function of `y`? Doesn't it need to be a function of both `s` and `y`? Is this because you have assumed that the LHS is an affine function of `s` that we need all the `s` to cancel?
</blockquote></details>

That is exactly right. I added more documentation. Is it more clear now?

**Review by AlexandreAmice — COMMENTED** [review]
I agree that the current implementation provides sufficient conditions for degree matching in our polynomials, however I am not yet convinced about the additional constraint `yᵀy=1`. Following up offline.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJMBkT61uwET0Z6iZB_:b2dv88p)* status: 3 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKwxC-867PgWCDNcjU:-NJMBFeHDw5D9gD2B6Vj:bymsd9o) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I added some more documentation.

I believe when p(y, s) is quadratic in y and linear in s, with the highest-degree monomial in the form yᵢ²sⱼ, then it is sufficient to set λ₁(y, s) λ₂(y, s) and λ₃(y, s) to be quadratic polynomials of y and λ₄(y, s) to be an affine polynomial of s, so that we can match the degree of p(y, s)?

With λ₁(y, s) λ₂(y, s) and λ₃(y, s) to be quadratic polynomials of y, we have λ₁(y, s)ᵀ(d−Cs),  − λ₂(y, s)ᵀ(s−s_lower)  and − λ₃(y, s)ᵀ(s_upper−s) all containing the monomials yᵢ²sⱼ, yᵢ², sⱼ. Similarly with λ₄(y, s) to be an affine polynomial of s, then λ₄(y, s)(1−yᵀy) will contain term sⱼ and yᵢ²sⱼ. So each monomial in p(y, s) can be cancelled out.
</blockquote></details>

Yes it is sufficient in this sense but is the bare minimum that is required. If we let λi(y, s) be higher degree then there can be cancellations internally in for example the terms of λ₁(y, s)ᵀ(d−Cs) which may make this easier for the optimizer to prove. Since the program is already huge, perhaps it is best to keep these multipliers small degree to prevent program bloat.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 575 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMArG63CTW3XjR1_bz:-NJMArG63CTW3XjR1_c-:b-fubkxz) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.cc#L575)):*
> ```cpp
>   // TODO(hongkai.dai): handle higher degree unit length vector.
>   for (int i = 0; i < unit_length_vec.rows(); ++i) {
>     // We set the Lagrangian multiplier degrees based on the assumping that
> ```

nit: spelling assumping -> assumption

**Review by AlexandreAmice — COMMENTED** [review]
Followed up offline and am satisfied by the constraint `yᵀy=1`. Just a couple of things to address in the comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJMGt8C-eSo1DuuBqbV:bifnncz)* status: 4 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMFzUv8rSi_cL0-733:-NJMFzUv8rSi_cL0-734:bvjz3av) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.h#L150)):*
> ```objc
> 
>    This struct records the Lagrangian multipliers λ₁(y,
>    s), λ₂(y, s), λ₃(y, s) and λ₄(y, s).
> ```

Can we use a different symbol for λ₄, perhaps ν₄ so that it is clear that it is not a SOS polynomial?
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 266 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMGUdWCVmraXZyXsd3:-NJMGUdWCVmraXZyXsd4:b-p5hm62) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.h#L266)):*
> ```objc
>   //
>   // Note that this polytope is NOT a compact set on y (it is a compact set on
>   // s). To incur the strong Positivstellasatz theorem on a compact set, we
> ```

I would change this to "We wish to make this set compact so we can use a stronger Positivstellensatz. To do so, we notice..."



_Code quote:_
```objc
To incur the strong Positivstellasatz theorem on a compact set,
```
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 266 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMGlf28oo1M7hzbwzV:-NJMGlf28oo1M7hzbwzW:b-bfr6w9) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.h#L266)):*
> ```objc
>   //
>   // Note that this polytope is NOT a compact set on y (it is a compact set on
>   // s). To incur the strong Positivstellasatz theorem on a compact set, we
> ```

nit: spelling "Positivstellensatz"



_Code quote:_
```objc
Positivstellasatz
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMFzUv8rSi_cL0-733:-NJNOjZw58o-5qYRBXHk:b-ydonir) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.h#L150)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can we use a different symbol for λ₄, perhaps ν₄ so that it is clear that it is not a SOS polynomial?
</blockquote></details>

Done. Good idea.
___
*[`geometry/optimization/dev/cspace_free_polytope.h` line 266 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJMGUdWCVmraXZyXsd3:-NJNP1LDBOyb93Sd4uTN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/47332b8d406a0d4e0e0ef456ebec41456cb0a0f1/geometry/optimization/dev/cspace_free_polytope.h#L266)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would change this to "We wish to make this set compact so we can use a stronger Positivstellensatz. To do so, we notice..."
</blockquote></details>

Done.
___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJKwxC-867PgWCDNcjU:-NJNPScgBi_fs6v09aan:bvknhkm) ([raw file](https://github.com/robotlocomotion/drake/blob/de2b5b80ba46bf339e3f22d892e395c62da3dae5/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Yes it is sufficient in this sense but is the bare minimum that is required. If we let λi(y, s) be higher degree then there can be cancellations internally in for example the terms of λ₁(y, s)ᵀ(d−Cs) which may make this easier for the optimizer to prove. Since the program is already huge, perhaps it is best to keep these multipliers small degree to prevent program bloat.
</blockquote></details>

I see what you mean. I modified the documentation to say that they meet the minimum requirement.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm: minus one fix in the comments

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJNq29b2-B0M9Usje_P:b-2xoyw6)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJNppwpAGJ1gxI5qGrJ:-NJNppwpAGJ1gxI5qGrK:b4kg74g) ([raw file](https://github.com/robotlocomotion/drake/blob/98adb5c540420d781f6dfcda591f630c2ff6df22/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
> ```cpp
>   // Since p(y, s) is quadratic in y and linear in s, with the highest-degree
>   // monomial in the form yᵢ²sⱼ, we know that to make p(y, s) - λ₁(y, s)ᵀ(d−Cs)
>   // − λ₂(y, s)ᵀ(s−s_lower) − λ₃(y, s)ᵀ(s_upper−s) - λ₄(y, s)(1−yᵀy) being sos,
> ```

This λ₄ should be a ν₄

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/cspace_free_polytope.cc` line 596 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18461#-NJNppwpAGJ1gxI5qGrJ:-NJNrXmo-Z_uwVQpKmTs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/98adb5c540420d781f6dfcda591f630c2ff6df22/geometry/optimization/dev/cspace_free_polytope.cc#L596)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This λ₄ should be a ν₄
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18461#-:-NJT0Sh83RQ71j4QQs16:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
