### PR TITLE
Implementation for Diagram::MapQDotToVelocity()

### PR DESCRIPTION
**Pull request by edrumwri**
This PR addresses issue #4505. The test does not attempt to change the iiwa world demo to reproduce the original problem, but I have verified that this PR does indeed correct that issue.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4537)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@david-german-tri for feature request please and +@sherm1 for platform request (from regular rotation, starting tomorrow) please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-:-KZIWYbmjcGG98lkvL21:b-a2r8zy)*

**Comment by sherm1** [comment]
Platform: :lgtm: except for one minor change, PTAL.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 682 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-KZKFGi2bNNGa1zfbYl6:-KZKFGi2bNNGa1zfbYl7:bgu1z2f) ([raw file](https://github.com/robotlocomotion/drake/blob/e6c9567e872ff2d14fdb09cdf1840f62c16b6c9d/drake/systems/framework/test/diagram_test.cc#L682)):*
> ```cpp
>   BasicVector<double> qdot(2);
>   VectorBase<double>* v = context->get_mutable_continuous_state()->
>                             get_mutable_generalized_velocity();
> ```

This should be left as a const reference, with a different mutable variable used below. With the same variable this test could pass if the second test doesn't do anything. Better not to share these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-:-KZKFkCMxVoAPq5r6Xio:bxs5vgu)*

**Comment by edrumwri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 682 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-KZKFGi2bNNGa1zfbYl6:-KZNMFwfKIaFItFDlCmG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e6c9567e872ff2d14fdb09cdf1840f62c16b6c9d/drake/systems/framework/test/diagram_test.cc#L682)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This should be left as a const reference, with a different mutable variable used below. With the same variable this test could pass if the second test doesn't do anything. Better not to share these.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/test/diagram_test.cc, line 682 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-KZKFGi2bNNGa1zfbYl6:-KZNlUvpvLhGfiesxn8I:b1ept18) ([raw file](https://github.com/robotlocomotion/drake/blob/e6c9567e872ff2d14fdb09cdf1840f62c16b6c9d/drake/systems/framework/test/diagram_test.cc#L682)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW odd indent (and no particular need to change the whitespace at all)

---

*[drake/systems/framework/test/diagram_test.cc, line 695 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-KZNldVihAvllv_UV0B6:-KZNldVihAvllv_UV0B7:b-ni7o87) ([raw file](https://github.com/robotlocomotion/drake/blob/66d28a608857fd4a9cdb54cb7ca2e65e89cdf4e4/drake/systems/framework/test/diagram_test.cc#L695)):*
> ```cpp
>   // TODO(david-german-tri): Address the issue broached immediately above
>   // here too.
>   BasicVector<double> vmut(v.size());
> ```

BTW not sure what this variable name means

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-:-KZNllOYg1yo63bcoEDY:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537)*

**Comment by david-german-tri** [comment]
CI disapproves, but still :lgtm: aside from the mismatched variable name

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537#-:-KZOI_lF2SrrNzvPyvnT:b-4royr5)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4537)*

**Comment by jwnimmer-tri** [comment]
Please squash-and-merge next time.

**Comment by sherm1** [comment]
> Please squash-and-merge next time.

Will do -- sorry. I hit the green button out of habit.

**Pull request merged**
