### PR TITLE
Update SDFormat SHA to use less Boost

### PR DESCRIPTION
**Pull request by jamiesnape**
Needed by RobotLocomotion/drake-shambhala#8.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6570)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review and +@soonho-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

I wasn't able to confirm whether or not `bac3d..` comes from a protected branch, I'll trust that it was.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6570#-KoxA3Qt3pu-mI74GfJZ:-KoxA3Qt3pu-mI74GfJ_:b-n51qet) (no related file):*
It seems like this means that Drake doesn't use boost anymore?

The `drake-distro/setup/...` code and related docs ask the user to install boost, and `git blame` says that sdformat was the reason why we listed it there.  Should this PR also de-scope the setup scripts to remove boost?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6570#-:-Kox8zf-GT4mrIL1O6nE:b-lvbaoi)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/6570#-KoxA3Qt3pu-mI74GfJZ:-KoxAmosf82EWwiq9XtN:b-rnjfjg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It seems like this means that Drake doesn't use boost anymore?

The `drake-distro/setup/...` code and related docs ask the user to install boost, and `git blame` says that sdformat was the reason why we listed it there.  Should this PR also de-scope the setup scripts to remove boost?
</blockquote></details>

I think we can remove `libboost-system-dev`, but it still uses a small amount of Boost.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6570)*

**Comment by soonho-tri** [comment]
:lgtm:

> I wasn't able to confirm whether or not bac3d.. comes from a protected branch, I'll trust that it was.

Ditto here. Anyway I'll test it on shambhala side.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6570#-:-KoxBJbTtzgfboKpriXQ:b-8u7kdt)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6570)*

**Comment by soonho-tri** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6570)*

**Pull request merged**
