### PR TITLE
Add the Kuka IIWA arm to examples

### PR DESCRIPTION
**Pull request by kuindersma**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2161)

### CODE REVIEW

**Comment by RussTedrake** [comment]
awesome.  i think the .5mb of obj files are well worth it (it's a pretty robot :).  thanks Scott!

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/KukaArm/runPassive.m, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2161#-KG1MJsvVq05rCkloVQe:-KG1MJsvVq05rCkloVQf:-61545570) ([raw file](https://github.com/robotlocomotion/drake/blob/f83de369246cf668f846f49ccafab669518d2ae8/drake/examples/KukaArm/runPassive.m#L10)):*
also quiet this one:
```
Warning: RigidBodyManipulator: velocity limits are not
supported yet 
> In WarningManager/warnOnce (line 21)
  In RigidBodyManipulator/addRobotFromURDF>parseJoint (line 357)
  In RigidBodyManipulator/addRobotFromURDF>parseRobot (line 105)
  In RigidBodyManipulator/addRobotFromURDF (line 55)
  In RigidBodyManipulator (line 75)
  In TimeSteppingRigidBodyManipulator (line 42)
  In runPassive (line 5) 
```

---

*[drake/examples/KukaArm/runPassive.m, line 15 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2161#-KG1MF8sIGoKIaK_pdUy:-KG1MF8sIGoKIaK_pdUz:-1993488808) ([raw file](https://github.com/robotlocomotion/drake/blob/f83de369246cf668f846f49ccafab669518d2ae8/drake/examples/KukaArm/runPassive.m#L15)):*
xtraj is undefined.  (forgot to get it from simulate)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2161#-:-KG1MPMrdaVfJ9DWURJI:1451179906)*

**Comment by RussTedrake** [comment]
also, can we clarify which model this is?  http://www.kuka-robotics.com/en/products/industrial_robots/sensitiv/

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2161#-:-KG1MjwPr9MZtnXB_Jf1:-1511473633)*

**Comment by kuindersma** [comment]
Hang tight. When looking back for the model number, I found another ROS package that has updates to this model. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2161#-:-KG1pwwS2a-cM9Ib_3_Y:1023894038)*

**Comment by kuindersma** [comment]
Added the IIWA 14 (I think that's going to be the relevant one for MoMap)

**Comment by RussTedrake** [comment]
can you do it on a clean branch, so we don't have the old unused meshes in the history?

**Pull request closed without merging**
