### PR TITLE
Mitigate python user site-packages

### LINKED ISSUE #8475: Bazel is using user site packages by default
Something like
- https://docs.python.org/2/library/site.html#site.USER_SITE
or
- https://docs.python.org/2/library/site.html#site.USER_BASE

is enabled by default when Bazel is running python stuff, which means that `$HOME/.local` can non-hermetically enter the build.

This is bad in general, but specifically bad for genrules such as https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/godotengine/main_make_binders.py where we do `import core` and some other thing in `.local` was named `core`, and then _poof_ our genrule fails.

Note that this is _different_ than `PYTHONPATH` leaks -- I think we are correctly guarding against PYTHONPATH breaking the hermetic seal.  The user site mechanism appears to operate distinctly and outside of the PYTHONPATH mechanisms.

More details / fixes to follow as I explore more.  This is just a placeholder for now.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #8475 as best we can right now.  Hopefully upstream will provide a more comprehensive solution.

Do not merge until:
- [ ] macOS builds pass.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8476)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review, please.

Could you also test locally on macOS if possible?

**Comment by soonho-tri** [comment]
:lgtm_cancel: 

For the simple example in the upstream issue, using `--action_env=PYTHONNOUSERSITE=1` does the trick.

But somehow, it's not the case for the Drake. This is what I did to test it:

1. `pip uninstall pyyaml`
2. `bazel clean`
3. `bazel test //tools/vector_gen/... -c dbg` gives:
```
    import yaml
ImportError: No module named yaml
```
which is expected.
4. `pip install pyyaml --user`. It install `pyyaml` under `${HOME}/Library/Python/2.7/lib/python/site-packages`.
5. `bazel test //tools/vector_gen/... -c dbg` works, while it should fail.
6. I've added `print sys.path` in `tools/vector_gen/lcm_vector_gen.py` to debug. FYI, it still includes `${HOME}/Library/Python/2.7/lib/python/site-packages`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8ncnUV3S0HiN_K4YDq:buvr6g2)*

**Comment by jwnimmer-tri** [comment]
Are there any cases where this _breaks_ the macOS build?  If not, then my proposal would be to rework it slightly to include macOS TODOs but then merge so at least Ubuntu is fixed (and leave the issue open).  What do you think?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8nfGoc7opyScsQMRoX:b-iij4z7)*

**Comment by jamiesnape** [comment]
FWIW I install everything with `pip --user` locally and our builds are already broken with `Sphinx`. `lxml` is currently only for Director so is unaffected by this, leaving just `matplotlib`, `pygame`,`PyYAML`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8noYWQ5kNlVqJq4WLb:btg1khf)*

**Comment by jwnimmer-tri** [comment]
@soonho-tri I am having trouble reconciling these two statements:

> [if a PIP package exists locally] Then Drake will not pick it up (if this PR get merged) and it will cause a problem.

> I've added print sys.path in tools/vector_gen/lcm_vector_gen.py to debug. FYI, it still includes ${HOME}/Library/Python/2.7/lib/python/site-packages.

Maybe I will try some things on `macsim` and see what I can find out.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8o14mMEhMtKc9_BUM9:bf4dujj)*

**Comment by soonho-tri** [comment]
> I've added print sys.path in tools/vector_gen/lcm_vector_gen.py to debug. FYI, it still includes ${HOME}/Library/Python/2.7/lib/python/site-packages.

It's about the current macOS issue that I have. I think it's a Drake-specific issue but I have no clues at the same time.

> [if a PIP package exists locally] Then Drake will not pick it up (if this PR get merged) and it will cause a problem.

Even if we resolve my issue (macOS + Drake-specific?), I think we will have a problem because of this local python packages. I guess it's not macOS-specific.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8o2I8y7vVnkQNXBn8u:bnzruky)*

**Comment by jwnimmer-tri** [comment]
Well, on Ubuntu we should not use`$HOME` nor grab things directly from `pip`, so I don't think this makes Ubuntu any worse.

I guess I buy that for macOS, if users have previously done `pip install --user PyYAML` and then later run our setup script, they would expect our build to still work.  So indeed if this PR breaks that workflow, then I will need to find another solution.

Possibly mac's `install_prereqs_user_environment.sh` could patch this up, but I'm not in love with adding more items there, since I don't really want Drake to own (very much of) that file.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8o3dUb1M8V09v071VO:bs61rfx)*

**Comment by soonho-tri** [comment]
> I've added print sys.path in tools/vector_gen/lcm_vector_gen.py to debug. FYI, it still includes ${HOME}/Library/Python/2.7/lib/python/site-packages.

FYI, it seems that we have the same problem on Ubuntu. Could you check?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8oCMkrCVAPiZE7x5Mg:b-nzrj0s)*

**Comment by jwnimmer-tri** [comment]
Aha.  So I guess `--action_env` only affects genrule, but not `rule()`?  The rule has a default, small environment?  At least, once I add the following, then it seems to remove the `.local` from the `sys.path`:

```patch
jwnimmer@call-cc:~/jwnimmer-tri/drake$ git diff tools/vector_gen/vector_gen.bzl
diff --git a/tools/vector_gen/vector_gen.bzl b/tools/vector_gen/vector_gen.bzl
index c1ba33c..a7559c9 100644
--- a/tools/vector_gen/vector_gen.bzl
+++ b/tools/vector_gen/vector_gen.bzl
@@ -78,6 +78,7 @@ def _vector_gen_impl(ctx):
         ] + [
             "--out=%s" % out.path for out in ctx.outputs.outs
         ],
+        env = {"PYTHONNOUSERSITE": "1"},
         executable = ctx.executable.lcm_vector_gen,
     )
     return struct()
```

I was testing with `tools/workspace/godotengine/main_make_binders.py` which is a `genrule()`, and is affected by this patch.

**Comment by jwnimmer-tri** [comment]
This really makes me think that the `virtualenv` proposal is going to be a better long-term answer (#8392).  Then we can make a python that does what we want, and even use `pip` to make the virtualenv (as part of a repository rule).  In the meantime, I'll consider whether I can rework this patch to be a stop-gap.

**Comment by jwnimmer-tri** [comment]
I've pushed a revision that sets PYTHONNOUSERSITE when calling `vector_gen`, and `vector_gen` is the only user of PyYAML.  I assume this means if PyYAML is `pip --user` only, then this would make it the build fail.

**Comment by soonho-tri** [comment]
:lgtm: Now the negative testing (pyyaml installed locally) works as expected (FAIL) on mac and Ubuntu.

> Well, on Ubuntu we should not use$HOME nor grab things directly from pip, so I don't think this makes Ubuntu any worse.

Correct. I just forget that we do not use PIP at all in those install scripts.

@jamiesnape , can we have something like the following to warn mac users if they have installed the packages used by Drake using `--user`?

```python
import pip
from os.path import expanduser
home = expanduser("~")
for item in pip.get_installed_distributions():
    # Need to check if item is in the requirement list.
    if item.location.startswith(home):
        print(("Error: {} is installed locally (--user) "
              "and Drake will ignore this package")
              .format(item.project_name))
```

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8oN7AxEJhutKp5AFQt:b-c11iqi)*

**Comment by jwnimmer-tri** [comment]
I decided to focus on the codegen rules, and not worry about tests and stuff yet.

I fixed godotengine by changing the imports; it was the only real genrule at risk.  The other codegen genrules are the cps stuff that doesn't really import enough to be worrisome yet.

I fixed the vector_gen rule to allow for user site-packages for PyYAML on macOS; the cmake_configure_file rule doesn't need anything from pip so I locked it down fully.

This is no longer a trivial PR, so needs at least a second reviewer.
+@jamiesnape for feature review, please.

**Comment by soonho-tri** [comment]
Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/vector_gen/vector_gen.bzl, line 106 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-L8rRZ9b4osD9m_-leiK:-L8rRZ9b4osD9m_-leiL:b-2tnq0n) ([raw file](https://github.com/robotlocomotion/drake/blob/8455c420767d568bf74d81620ed70cd6089b1fa5/tools/vector_gen/vector_gen.bzl#L106)):*
> ```Python
> 
> def _vector_gen_env():
>     # In general, we do not want to use $HOME/.local because it's not hermetic.
> ```

Since the directory is different on Mac, something like`the Python user install directory (e.g., $HOME/.local)` maybe better.

---

*[tools/workspace/cmake_configure_file.bzl, line 17 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-L8rS8g5Eapsy9jBu3u6:-L8rS8g5Eapsy9jBu3u7:bfctt07) ([raw file](https://github.com/robotlocomotion/drake/blob/8455c420767d568bf74d81620ed70cd6089b1fa5/tools/workspace/cmake_configure_file.bzl#L17)):*
> ```Python
>         outputs = [ctx.outputs.out],
>         arguments = arguments,
>         # Never use $HOME/.local; it's not hermetic.
> ```

BTW This is a different behavior to `vector_gen.bzl`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-:-L8rSEduAmNA8DljO-mi:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/vector_gen/vector_gen.bzl, line 106 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-L8rRZ9b4osD9m_-leiK:-L8rYC_o9fgqMLktY7k7:b-ot7l77) ([raw file](https://github.com/robotlocomotion/drake/blob/8455c420767d568bf74d81620ed70cd6089b1fa5/tools/vector_gen/vector_gen.bzl#L106)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Since the directory is different on Mac, something like`the Python user install directory (e.g., $HOME/.local)` maybe better.
</blockquote></details>

Done (in new file).

---

*[tools/workspace/cmake_configure_file.bzl, line 17 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476#-L8rS8g5Eapsy9jBu3u6:-L8rYElV1h7S6W3sjk9p:bi960f) ([raw file](https://github.com/robotlocomotion/drake/blob/8455c420767d568bf74d81620ed70cd6089b1fa5/tools/workspace/cmake_configure_file.bzl#L17)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW This is a different behavior to `vector_gen.bzl`.
</blockquote></details>

Done.

My initial thought was that since this program doesn't use anything from pip, we didn't need the complexity.   But on second thought, why try to parse that distinction -- better to just reuse the same settings for everything, so I've factored into a helper.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476)*

**Comment by soonho-tri** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8476)*

**Pull request merged**
