### PR TITLE
First PR2 example pull request.

### PR DESCRIPTION
**Pull request by TristanThrush**
This pull request is the first step in a sequence of pull requests that will eventually put a controlled PR2 example that can pick and place objects in drake master.

The pull request contains a passive simulation of the PR2 and a URDF for the PR2 that is compatible with Drake. After a discussion, it was decided that the original PR2 URDF should be removed because it is incompatible with Drake. An issue will then be opened to eventually make the original URDF compatible.

The Drake-compatible URDF has some notable features:
- There is an x joint, y joint, and theta joint for base movement because Drake has difficulty simulating the wheels. A floating PR2 would also sink into the ground substantially with the simulation's contact parameters, which are set to be soft to support gripping. 
- The gripper joints are fully actuated instead of set up to mimic each other from the motions of a prismatic joint (drake is incompatible with the former because it requires support for a custom transmission). While discussing this pull request, it came up that it would be good to just lock the fingers and move them apart with a prismatic joint. After trying this, though, I found that the fingers had to separate from the palm by an awkward amount in order to have a decent grip width. I can always revert back to this if it is still desired. But even though fully actuated grippers are more complex, they allow for the same motions as the original gripper description, instead of limiting gripper movement.
- The collision geometry is the same as the visualization geometry. It was decided that the unnecessary collisions should be removed in C++ after loading the RigidBodyTree instead of creating a second URDF. After https://github.com/RobotLocomotion/drake/issues/6803 is resolved, I can submit the feature of removing collisions in C++ in another PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6806)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@naveenoid for feature review

**Comment by naveenoid** [comment]
Thanks a lot for your contribution @tristanthrush 

Some broader comments : Perhaps pr2_simulation should be renamed to pr2_passive_simulation since its not going to actively listen to control signals etc..

Also please fix the CI issues. 

First pass done. PTAL

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/pr2/pr2_drake.urdf, line 0 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBeaSIL4J6MkZ74Nm8:-KrBeaSJTSZNOZqeyrt9:b8twlq2) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_drake.urdf#L0)):*
Is there any reason this file is not inside examples/pr2/models? Your BUILD file mentions data to be present in :models. Also why have you named it pr2_drake? Perhaps pr2_simplified might be better? 

---

*[drake/examples/pr2/pr2_drake.urdf, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBf8rbix3LsQY0W6z-:-KrBf8rbix3LsQY0W6z0:bq9kwkp) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_drake.urdf#L9)):*
> ```XML
> 
> 
> 
> ```

Perhaps more of a note is needed to explain what kind of simplifications / mods were made for Drake compatibility? Also what about the notes on the collision mesh edits?

---

*[drake/examples/pr2/pr2_simulation.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBdiSNdPTY0-qgc-hP:-KrBdiSNdPTY0-qgc-hQ:bl47shg) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_simulation.cc#L1)):*
> ```cpp
> #include "drake/common/find_resource.h"
> ```

An @brief comment block at the top of this file explaining what one is expected to see with this demo would be useful. 

---

*[drake/examples/pr2/pr2_simulation.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBcVGzVzQ7FnPFNqW1:-KrBcVGzVzQ7FnPFNqW2:beerjrf) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_simulation.cc#L16)):*
> ```cpp
> namespace pr2 {
> 
> void main() {
> ```

This method is typically an int returning local namespace method named DoMain for most of the examples inside drake.

---

*[drake/examples/pr2/pr2_simulation.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBd_E4W3dzNrVYrADq:-KrBd_E4W3dzNrVYrADr:b-ja47tw) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_simulation.cc#L96)):*
> ```cpp
>   simulator.Initialize();
>   simulator.set_target_realtime_rate(1.0);
>   simulator.StepTo(10);
> ```

Why only 10 seconds? Either this needs documentation or I suggest a GFLAGS argument to enable setting this.

---

*[drake/examples/pr2/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBe3hcUwjeO6JAcPEF:-KrBe3hcUwjeO6JAcPEG:b-5b68k8) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/README.md#L10)):*
> ```Markdown
> 
> To run the simulation from the root directory of Drake:
> $ ./bazel-bin/drake/examples/pr2/pr2_simulation
> ```

There neeeds to be a note here mentioning that drake-visualizer needs to be built and launched as well in order to "see" the demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrBds__T9Y6ESyfmkWr:b-wjubwa)*

**Comment by TristanThrush** [comment]
Review status: 0 of 89 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/pr2/pr2_passive_simulation.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBdiSNdPTY0-qgc-hP:-KrCA1qsqC5cdjBvVBT8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_passive_simulation.cc#L1)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

An @brief comment block at the top of this file explaining what one is expected to see with this demo would be useful. 
</blockquote></details>

Done.

---

*[drake/examples/pr2/pr2_passive_simulation.cc, line 16 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBcVGzVzQ7FnPFNqW1:-KrCA4HjqvOFACSMHHFj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_passive_simulation.cc#L16)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

This method is typically an int returning local namespace method named DoMain for most of the examples inside drake.
</blockquote></details>

Done.

---

*[drake/examples/pr2/pr2_passive_simulation.cc, line 96 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBd_E4W3dzNrVYrADq:-KrCA603DYNmVzMwD-9l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/pr2_passive_simulation.cc#L96)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Why only 10 seconds? Either this needs documentation or I suggest a GFLAGS argument to enable setting this.
</blockquote></details>

Done.

---

*[drake/examples/pr2/README.md, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBe3hcUwjeO6JAcPEF:-KrCA7Q4pPODfGURqvah:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/README.md#L10)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

There neeeds to be a note here mentioning that drake-visualizer needs to be built and launched as well in order to "see" the demo.
</blockquote></details>

Done.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 9 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBf8rbix3LsQY0W6z-:-KrCAAyG0e8KPsfJuZ2K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L9)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Perhaps more of a note is needed to explain what kind of simplifications / mods were made for Drake compatibility? Also what about the notes on the collision mesh edits?
</blockquote></details>

Done.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line  at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrBeaSIL4J6MkZ74Nm8:-KrCA8ZINy_NYAG2iRMw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7228353994a32d73015b0d9742622ed56c3e6150/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Is there any reason this file is not inside examples/pr2/models? Your BUILD file mentions data to be present in :models. Also why have you named it pr2_drake? Perhaps pr2_simplified might be better? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806)*

**Comment by naveenoid** [comment]
CI issues need fixing. There also definitely needs to be atleast a simple unit test that loads up the model and does not fail.

---

Reviewed 1 of 7 files at r1, 6 of 176 files at r2.
Review status: 4 of 89 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCFG2irYlsIwJqxA6O:-KrCFG2irYlsIwJqxA6P:b-vere2j) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L3)):*
> ```XML
> <?xml version="1.0" ?>
> 
> 
> ```

@russtedrake What about licensing issues? Shall we proceed with this model for now?

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCBVMdOxDqT1A02FmX:-KrCBVMeHEDH5smR9USQ:b-rjz128) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L10)):*
> ```XML
> 
> 
> 
> ```

How about "..have been fixed in the following manner:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrCFR7dTF-urzqEzhl0:b6a5nqa)*

**Comment by naveenoid** [comment]
I think you may have cpplint errors. Check this : http://drake.mit.edu/code_style_tools.html to fix. Once done, I will pass this PR onto platform review.

---

Reviewed 1 of 3 files at r3.
Review status: 3 of 93 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrHcoTrf0-gtoiMvcxE:b-ctwpmj)*

**Comment by TristanThrush** [comment]
Formatting has been fixed. Sorry it took so long, but I'll be able to quickly do this in the future, now.

---

Review status: 2 of 93 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCBVMdOxDqT1A02FmX:-KrHyepzd3l_wMbGALga:brnjat9) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L10)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

How about "..have been fixed in the following manner:"
</blockquote></details>

By 'fixed' I meant 'fixed joint type' not 'solved.'  I updated it to clarify - is that okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrHyspuakvqsmyOtu46:b-qdresi)*

**Comment by naveenoid** [comment]
:lgtm:

@sherm1 for platform review.

---

Reviewed 2 of 4 files at r4.
Review status: 4 of 93 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrHzYCqvR9DS02I2X4v:b-azzudd)*

**Comment by sherm1** [comment]
Platform review pass done, PTAL. There are still comments from @naveenoid that don't appear to have been resolved.

Regarding licensing: it appears to me that all the potentially licensed files here have just been renamed from their previous spots within Drake. Is that correct? If so this PR doesn't introduce any new licensing issues so that wouldn't need to be addressed here.

---

Reviewed 1 of 7 files at r1, 4 of 176 files at r2, 2 of 3 files at r3, 4 of 4 files at r4.
Review status: 8 of 93 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/pr2/pr2_passive_simulation.cc, line 6 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrICRrbrFOrmYnSoqKB:-KrICRrcMzcc5Fs7AYqB:b-494o88) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/pr2_passive_simulation.cc#L6)):*
> ```cpp
> /// PR2 robot. There is no controller, but the contact parameters and integrator
> /// parameters are set to support reliable gripping of objects if a controller
> /// is added.
> ```

BTW this is a ".cc" file so shouldn't have doxygen comments. Also, `@brief` doesn't make sense like this even in a doxygen comment. I suggest you remove that, and just make this a regular "//" comment.

---

*[drake/examples/pr2/README.md, line 3 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIC3yoMQZk5o5jVf6E:-KrIC3yoMQZk5o5jVf6F:b-um6x2n) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/README.md#L3)):*
> ```Markdown
> This directory contains a drake-compatible description of the PR2 and an example uncontrolled simulation that simply loads the description, with contact parameters and integrator parameters that are reasonably stable for gripping objects.
> 
> The description differs from a standard PR2 description because it uses two prismatic joints and one revolute joint to move along the ground plane (named x, y, and theta, respectively), instead of wheels. The description also contains fully actuated finger joints, instead of a single prismatic joint that closes and opens finger joints that mimic each other.
> ```

BTW please consider keeping line lengths to 80 characters here as in code. (Not required, but it is good hygiene and makes the text easier to review.)

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 12 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIECZ7N5hL0857CUuo:-KrIECZ7N5hL0857CUup:b-u9p66f) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L12)):*
> ```XML
> 
> 
> 
> ```

BTW there appear to be tabs in this file. Please replace them with spaces.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 2232 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIEX5G5HLWAVlPaphH:-KrIEX5HQ1exCELQgNUQ:b-vcln9g) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2232)):*
> ```XML
>   </link>
>

**Comment by TristanThrush** [comment]
Review status: 4 of 93 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/examples/pr2/pr2_passive_simulation.cc, line 6 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrICRrbrFOrmYnSoqKB:-KrWYemHcP4VAjiLN2IW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/pr2_passive_simulation.cc#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this is a ".cc" file so shouldn't have doxygen comments. Also, `@brief` doesn't make sense like this even in a doxygen comment. I suggest you remove that, and just make this a regular "//" comment.
</blockquote></details>

Done.

---

*[drake/examples/pr2/README.md, line 3 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIC3yoMQZk5o5jVf6E:-KrWYhSZsOLMlFJ-wnxw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/README.md#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW please consider keeping line lengths to 80 characters here as in code. (Not required, but it is good hygiene and makes the text easier to review.)
</blockquote></details>

Done.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCFG2irYlsIwJqxA6O:-KrWZWzS6Se10Ikapkaw:b-5po6mx) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L3)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

@russtedrake What about licensing issues? Shall we proceed with this model for now?
</blockquote></details>

Per the comment from @sherm1 it should be fine.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 12 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIECZ7N5hL0857CUuo:-KrWYlwmfrMjJAhaeNDy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L12)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW there appear to be tabs in this file. Please replace them with spaces.
</blockquote></details>

Done.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 2232 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIEX5G5HLWAVlPaphH:-KrWYocnTB92h5vLgUK7:b-p135tf) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2232)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there a reason to keep all this commented out junk in this file? Why not delete it all and leave a smaller file?
</blockquote></details>

I took out the commented links that I made for testing. @RussTedrake I think that you mentioned that you wanted to leave the features from the original pr2.urdf in there, but commented out?

---

*[drake/examples/pr2/test/load_pr2_simplified_test.cc, line 19 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIBPBU9KcuSas0BbjL:-KrWZBM6XtSCChCLkBNq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/test/load_pr2_simplified_test.cc#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW is there some "EXPECT..." condition you can add here that would fail if the tree didn't get built properly? Number of links, or a name, or ??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806)*

**Comment by sherm1** [comment]
Platform :lgtm:. I think there is still one discussion blocked by @naveenoid.

---

Reviewed 1 of 7 files at r1, 172 of 176 files at r2, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrXLyhl2ol7ro4pt89E:b-fftffz)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCFG2irYlsIwJqxA6O:-KrYRDBv-Sd29bKSnGSe:b-39dm) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L3)):*
<details><summary><i>Previously, TristanThrush wrote…</i></summary><blockquote>

Per the comment from @sherm1 it should be fine.
</blockquote></details>

i'm not the expert on licensing.  @sherm1 knows more than me... i'd trust his judgement.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 2232 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIEX5G5HLWAVlPaphH:-KrYRNOZ4g8GV_iH0eky:b9hwk59) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2232)):*
<details><summary><i>Previously, TristanThrush wrote…</i></summary><blockquote>

I took out the commented links that I made for testing. @RussTedrake I think that you mentioned that you wanted to leave the features from the original pr2.urdf in there, but commented out?
</blockquote></details>

i did request that (so that we remember that this is an approximation of the original ROS-provided urdf)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806)*

**Comment by TristanThrush** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 3 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrCFG2irYlsIwJqxA6O:-KraYMMwGFn2ZtnTnbBo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/71e1742e8811671a356bbfdf2fcfe5b1fc039181/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L3)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i'm not the expert on licensing.  @sherm1 knows more than me... i'd trust his judgement.
</blockquote></details>

Done.

---

*[drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf, line 2232 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-KrIEX5G5HLWAVlPaphH:-KraYNaxSLxudgGbDL6X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b13c25f409393e9ed234f3b384fe8c5791749c4c/drake/examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf#L2232)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i did request that (so that we remember that this is an approximation of the original ROS-provided urdf)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806)*

**Comment by naveenoid** [comment]
Ive unblocked. There seems to be one comment blocked by @sherm1 and then we are good to merge.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrbEK6p6oc8Mt6X1SDb:bjim9p9)*

**Comment by sherm1** [comment]
All discussions are resolved now. Just needs a squash-merge (please edit the commit message to make it useful).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrbQfr-6-XgiOlO0Noy:byyqcb7)*

**Comment by naveenoid** [comment]
-(status: curate commits before merging) 
Moving to squash and merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6806#-:-KrbwZil-GU-AVSpRI3u:ba38enc)*

**Pull request merged**
