### PR TITLE
pydrake.all: Do not promote using `from x import *` in documentation.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per [discussion here](https://github.com/RussTedrake/underactuated/pull/58#issuecomment-363252363).

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7963)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@rdeits and +@peteflorence for feature review please. If this conflicts with the class code, we can defer it.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4cLfdxtdmpAN4ISgpH:b-w1osrp)*

**Comment by peteflorence** [comment]
Hey @EricCousineau-TRI !

This looks good!  We need to change the textbook Chapter 1 reference to this syntax.  I'll make an issue at github.com/RussTedrake/underactuated to reflect that

**Comment by peteflorence** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4cPYB9zWhDVlCqn2RH:bnfp4nl)*

**Comment by rdeits** [comment]
:lgtm: thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4cVs5XXRWY4_0QaRET:brfqlux)*

**Comment by RussTedrake** [comment]
:lgtm:  it doesn't actually make any functional changes, though?   only a style recommendation?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4cXhyGKhVjRC3HaDIK:b-xyxc3)*

**Comment by EricCousineau-TRI** [comment]
Yup! Purely stylistic.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4c_YKNcYKbSSN7r2TS:b-chex3p)*

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for platform review, please.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4ca7cn4WlypWYGxjkf:bz1t39v)*

**Comment by sammy-tri** [comment]
:lgtm:  Thanks, I definitely prefer this style.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7963#-:-L4fe78W7B4Nfugph4bh:b-q1hvar)*

**Pull request merged**
