### PR TITLE
Add mujoco_menagerie as a test-only dependency

### PR DESCRIPTION
**Pull request by RussTedrake**
And use it for testing the mujoco parser.
Towards #20444 and #21648.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@jwnimmer-tri for feature review of build-system, please.

**Comment by jwnimmer-tri** [comment]
See https://github.com/RussTedrake/drake/pull/56 for changes.

**Comment by jwnimmer-tri** [comment]
(I also changed the release notes tag -- adding new dependencies to the workspace is notable.)

**Comment by RussTedrake** [comment]
thanks @jwnimmer-tri -- are you satisfied enough to give one or both LGTMs?

**Comment by jwnimmer-tri** [comment]
Build system stuff looks good now.

Both for reasons of time, and somewhat because I co-authored, we should probably find someone else to review -@jwnimmer-tri.

Probably @joemasterjohn or @rpoyner-tri would be good for feature review, or maybe @sherm1 feels confident enough to do both reviews.

**Comment by RussTedrake** [comment]
+@rpoyner-tri for feature review, please (unless @sherm1 feels good to take both)
+@sherm1 for platform review, please.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm:
My grasp of build system details is tenuous, so I think it is worth getting a feature review from Rico (he's back tomorrow).

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-:-O0iuJk67K6luyHNmiyD:b-uurz0s)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
If your only doubt is about the build system (rather than parser semantics), then I've already LGTMd the build system.

**Review by jwnimmer-tri — COMMENTED** [review]
Ugh, I'm trying to keep my hands out of this one and focus work that more directly requires my skillset, but I can't help myself but comment again

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-:-O0ixKvqEWOfBPVKhGVv:bhopvlt)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

___
*[`multibody/tree/geometry_spatial_inertia.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-O0ixG4Q29yzOFJPIOX5:-O0ixG4Q29yzOFJPIOX6:b3d9ums) ([raw file](https://github.com/RobotLocomotion/drake/blob/b95a2febcba570989581129de7afee37634d859d/multibody/tree/geometry_spatial_inertia.h#L34)):*
> ```objc
>  @throws std::exception if `shape` is an instance of geometry::HalfSpace or
>                         geometry::MeshcatCone.
>  @throws std::exception if the resulting spatial inertia computation does not
> ```

BTW Probably better to revert this header file change until a future PR that deals in semantics instead of build system.

(1) This is a "release notes: breaking change" (by changing the contract of a public API in a backwards-incompatible way).

(2) The rationale for editing this comment now is not clear.  There are no tests that relate to this documentation change.  Why aren't we testing the new promise?

(3) Why is only this overload changed?  It's the overload below the actual source of the throwing?  Why isn't that one also changed?

(4) Why change this public API in the first place, instead of fixing the bug so that we don't actually throw?  This seems like it's pointing us in the wrong direction.

**Review by sherm1 — COMMENTED** [review]
With the new comment reverted, +(status: single reviewer ok) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-:-O0j8KIj1ZVlnoOlIl4k:b-pk8c6x)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`multibody/tree/geometry_spatial_inertia.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-O0ixG4Q29yzOFJPIOX5:-O0j7hPB1OP0MH3_ZcMN:b3fi6wh) ([raw file](https://github.com/RobotLocomotion/drake/blob/b95a2febcba570989581129de7afee37634d859d/multibody/tree/geometry_spatial_inertia.h#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Probably better to revert this header file change until a future PR that deals in semantics instead of build system.

(1) This is a "release notes: breaking change" (by changing the contract of a public API in a backwards-incompatible way).

(2) The rationale for editing this comment now is not clear.  There are no tests that relate to this documentation change.  Why aren't we testing the new promise?

(3) Why is only this overload changed?  It's the overload below the actual source of the throwing?  Why isn't that one also changed?

(4) Why change this public API in the first place, instead of fixing the bug so that we don't actually throw?  This seems like it's pointing us in the wrong direction.
</blockquote></details>

Done.  (i included it because the method threw an exception that it was not documented as throwing , and it happened while testing this PR; but I agree it should be done more carefully in the future).

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`multibody/tree/geometry_spatial_inertia.h` line 34 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/21649#-O0ixG4Q29yzOFJPIOX5:-O0j9C0R-lU4PW8XutbR:bx17oc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/b95a2febcba570989581129de7afee37634d859d/multibody/tree/geometry_spatial_inertia.h#L34)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (i included it because the method threw an exception that it was not documented as throwing , and it happened while testing this PR; but I agree it should be done more carefully in the future).
</blockquote></details>

For sure, the code had (has) a bug.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21649)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Pull request merged**
