### PR TITLE
Port automotive to default_scalars

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #7039.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7101)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jadecastro for feature review, please.

**Comment by jadecastro** [comment]
:lgtm: aside from a couple BTWs..

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/automotive/simple_car.cc, line 242 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-KuucPdvaqs5RjbljTBL:-KuucPdvaqs5RjbljTBM:b-rdq4ik) ([raw file](https://github.com/robotlocomotion/drake/blob/d3ee015f247b3adbbb318f4561403616439fee23/drake/automotive/simple_car.cc#L242)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_SCALARS(
> ```

BTW, It might make sense to add the comment: `// These instantiations must match the API documentation in simple_car.h.` here or get rid of the one in idm_planner.cc.

---

*[drake/automotive/simple_powertrain.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-KuuchXyZvJtzBz28s_c:-KuuchXyZvJtzBz28s_d:be9hynd) ([raw file](https://github.com/robotlocomotion/drake/blob/d3ee015f247b3adbbb318f4561403616439fee23/drake/automotive/simple_powertrain.cc#L5)):*
> ```cpp
> #include "drake/common/default_scalars.h"
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_SCALARS(
> ```

BTW, It might make sense to add the comment`// These instantiations must match the API documentation in simple_powertrain.h.` here or get rid of the one in idm_planner.cc.

---

*[drake/common/default_scalars.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-KuubOOY_ppS1QBXpAOB:-KuubOOY_ppS1QBXpAOC:b-orfidn) ([raw file](https://github.com/robotlocomotion/drake/blob/d3ee015f247b3adbbb318f4561403616439fee23/drake/common/default_scalars.h#L38)):*
> ```objc
> /// See also @ref system_scalar_conversion.
> #define DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_SCALARS(SomeType) \
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS( \
> ```

FYI (meta), typo: `INSTIATIONS` (-> `INSTANTIATIONS`?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-:-KuucujkbBfTf9G19Dnq:b-6s3ieo)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/simple_car.cc, line 242 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-KuucPdvaqs5RjbljTBL:-KuurmIfbBNN71CqusaY:bkw2bik) ([raw file](https://github.com/robotlocomotion/drake/blob/d3ee015f247b3adbbb318f4561403616439fee23/drake/automotive/simple_car.cc#L242)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

BTW, It might make sense to add the comment: `// These instantiations must match the API documentation in simple_car.h.` here or get rid of the one in idm_planner.cc.
</blockquote></details>

Done, thanks!

I had waffled about keeping those, but did decide to keep them and just screwed up the editing on these two files.

---

*[drake/common/default_scalars.h, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-KuubOOY_ppS1QBXpAOB:-KuuqpGvu3cNV9uOPZHW:b-w6ltgl) ([raw file](https://github.com/robotlocomotion/drake/blob/d3ee015f247b3adbbb318f4561403616439fee23/drake/common/default_scalars.h#L38)):*
<details><summary><i>Previously, jadecastro (Jonathan DeCastro) wrote…</i></summary><blockquote>

FYI (meta), typo: `INSTIATIONS` (-> `INSTANTIATIONS`?)
</blockquote></details>

Wow.  Good eyes!!  I only wish I'd had you review the first PR, instead of the 9th.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7101)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review per rotation, please.

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7101#-:-KuvCACXp_M4AOJ-9KfJ:bnfp4nl)*

**Pull request merged**
