### PR TITLE
[doc] Add release notes v1.29.0

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxnQsQw7kIDGVxzH0RF):*
I have merged from `master` up to PR 21414. I'm polishing the release notes. Hopefully, we can start the review tomorrow Tuesday to release on Wednesday.

**Review by DamrongGuoy — COMMENTED** [review]
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-:-Nxo6EwYDuvRoZrchUBj:ba0k9zt)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`-- commits` line 36 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrkZADEbpnN8CkPQqY):*
Merge master up to PR 21417. I'll start the review now.

**Review by DamrongGuoy — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-:-NxrlYKc3eJNlKA-x0yA:b-qf68jg)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrmAxkENeRaU5gzRjo:-NxrmAxkENeRaU5gzRjp:b-aqcksn) (no related file):*
@mitiguy @sherm1 There are items in `Newly-deprecated APIs` from #21169. Please help me double check the release notes.

___

**Review by jwnimmer-tri — COMMENTED** [review]
I pushed my edits to this branch.

:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-:-Nxrtcwp9H7mmRsEHq4M:brmd37f)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrmAxkENeRaU5gzRjo:-NxtBQtz9JfClC4s2QK1:b-t9oxin) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

@mitiguy @sherm1 There are items in `Newly-deprecated APIs` from #21169. Please help me double check the release notes.
</blockquote></details>

@DamrongGuoy   I double-checked the release notes for these newly-deprecated APIs and it looks as if you have them all.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrmAxkENeRaU5gzRjo:-NxtxRl072LXrMYFhilz:bxs88ha) (no related file):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

@DamrongGuoy   I double-checked the release notes for these newly-deprecated APIs and it looks as if you have them all.
</blockquote></details>

Thank you, Paul.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_pages/from_binary.md` line 37 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-Nxwzq6tBwMtwe56qX3u:-Nxwzq6tBwMtwe56qX3v:bg1e7ti) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e19be25f6c3728fc6f51d711c1ac15ff5ead327/doc/_pages/from_binary.md#L37)):*
> ```Markdown
> 
> * [https://github.com/RobotLocomotion/drake/releases/download/v1.29.0/drake-1.29.0-jammy.tar.gz](https://github.com/RobotLocomotion/drake/releases/download/v1.29.0/drake-1.29.0-jammy.tar.gz)
> * https://github.com/RobotLocomotion/drake/releases/download/v1.29.0/drake-1.29.0-mac.tar.gz (for x86_64)
> ```

nit Remove this line.  (The link will be broken; there are no more x86_64 mac release tgzs.)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

___
*[`doc/_pages/from_binary.md` line 37 at r7](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-Nxwzq6tBwMtwe56qX3u:-Nxx-ZaX2GxAK684jOMu:boyexbg) ([raw file](https://github.com/RobotLocomotion/drake/blob/6e19be25f6c3728fc6f51d711c1ac15ff5ead327/doc/_pages/from_binary.md#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Remove this line.  (The link will be broken; there are no more x86_64 mac release tgzs.)
</blockquote></details>

Done. Thanks.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrmAxkENeRaU5gzRjo:-NxxsHDc2fmkLp5fPdQt:bg7igkv) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Thank you, Paul.
</blockquote></details>

:lgtm: 

___

**Review by DamrongGuoy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-:-NxxsafSBooxX2uLI6g0:bm9o57a)* status: needs at least two assigned reviewers

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21406)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),mitiguy

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21406#-NxrmAxkENeRaU5gzRjo:-NxxsoCx2MnLSNitPpKq:b-55mseh) (no related file):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

:lgtm:
</blockquote></details>

+@mitiguy for feature review, please.

___

**Pull request merged**
