### PR TITLE
Add drake_visualizer local repository to workspace

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Enables launching the GUI via Bazel if the program is available in a well-known-location at build time.  If not, it only fails at runtime.

```
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel run @drake_visualizer//:drake-visualizer
...
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/external/drake_visualizer/drake-visualizer
... (gui appears) ...

jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ mv build/debug/install/bin/drake-visualizer{,.bak}
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel run @drake_visualizer//:drake-visualizer
WARNING: .../external/drake_visualizer/BUILD:1:46: The target @drake_visualizer//:drake-visualizer will not run correctly because /home/jwnimmer/jwnimmer-tri/drake-distro/build/install/bin/drake-visualizer is missing
...
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/external/drake_visualizer/drake-visualizer
tools/soft_failure.bzl: as of last build, no such file /home/jwnimmer/jwnimmer-tri/drake-distro/build/install/bin/drake-visualizer
ERROR: Non-zero return code '1' from command: Process exited with status 1

jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ mv build/debug/install/bin/drake-visualizer{.bak,}
jwnimmer@call-cc:~/jwnimmer-tri/drake-distro$ bazel run @drake_visualizer//:drake-visualizer
...
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/external/drake_visualizer/drake-visualizer
... (gui appears) ...
```

This will be used in a future PR where the `automotive` demo can optionally launch the visualizer, eventually including in CI.

This is also (hopefully) just a stop-gap until we get `drake-visualizer` actually compiling under Bazel, but it's unclear how long that will take, and we need this now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4705)

### CODE REVIEW

**Comment by liangfok** [comment]
I left a few comments. PTAL.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/soft_failure.bzl, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qy2YkJV10KWq0Pbp_:-K_qy2YkJV10KWq0Pbpa:b-xmxf5x) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L30)):*
> ```Python
> #
> # When building the repository, we add a symlink for where the binary should
> # be.  By using a glob against that symlink in our BUILD, Bazel will notice at
> ```

BTW, the previous reference to "glob" used "glob()". Consider being consistent. (Same comment below.)

---

*[tools/soft_failure.bzl, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyKcLVVgjDe_yiY4J:-K_qyKcLVVgjDe_yiY4K:bdz2joh) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L31)):*
> ```Python
> # When building the repository, we add a symlink for where the binary should
> # be.  By using a glob against that symlink in our BUILD, Bazel will notice at
> # build time whether or not the actual binary exists, and bring it into the
> ```

BTW, consider deleting "actual" or replacing "actual binary" with "binary target file actually".

---

*[tools/soft_failure.bzl, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyo4UxiabT4XU1OR8:-K_qyo4Vo9sj5E7wZ3FR:bn0fchl) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L33)):*
> ```Python
> # build time whether or not the actual binary exists, and bring it into the
> # sandbox only if so.  Bazel notices when glob outcomes change, so will rebuild
> # anything the actual binary (dis)appears.  Later at runtime, our wrapper
> ```

BTW, missing some words between "anything" and "the".

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyxnPM04_pMe_WeRf:-K_qyxnPM04_pMe_WeRg:b-tuipjz) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
> ```Python
> # sandbox only if so.  Bazel notices when glob outcomes change, so will rebuild
> # anything the actual binary (dis)appears.  Later at runtime, our wrapper
> # sh_binary will see if globbed file exists, and emit a good message if not.
> ```

BTW, should "file" be plural?

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qz9QCp-IuraKL1W4D:-K_qz9QCp-IuraKL1W4E:bde98v) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
> ```Python
> # sandbox only if so.  Bazel notices when glob outcomes change, so will rebuild
> # anything the actual binary (dis)appears.  Later at runtime, our wrapper
> # sh_binary will see if globbed file exists, and emit a good message if not.
> ```

BTW, where is "sh_binary"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-K_qzKGX_WSesC-pS7fl:b-ljoz1n)*

**Comment by jwnimmer-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/soft_failure.bzl, line 31 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyKcLVVgjDe_yiY4J:-K_r-bc7CBNfNoVGJHsI:bmkkf1q) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L31)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider deleting "actual" or replacing "actual binary" with "binary target file actually".
</blockquote></details>

Done (new wording).

---

*[tools/soft_failure.bzl, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyo4UxiabT4XU1OR8:-K_r-8bIeCKFd7eNg0_5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L33)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, missing some words between "anything" and "the".
</blockquote></details>

Done.

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyxnPM04_pMe_WeRf:-K_qzcd6tZdEzLPOmutq:bkf8om6) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should "file" be plural?
</blockquote></details>

Nope, the call is `glob(["soft-failure-binary"])` which is only looking for 1 file.

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qz9QCp-IuraKL1W4D:-K_qzsQVCtgVmflLTQ13:bprzgoo) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, where is "sh_binary"?
</blockquote></details>

It's about 20 lines down:
```
    data = glob(["soft-failure-binary"]) or print("%s");
    sh_binary(
        name = ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyxnPM04_pMe_WeRf:-K_r0n7WzTgZpAaG5BKW:by0gim3) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Nope, the call is `glob(["soft-failure-binary"])` which is only looking for 1 file.
</blockquote></details>

BTW, consider adding "the" before "globbed".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-K_r1FYaa_jAcjpJqgPO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/soft_failure.bzl, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-K_qyxnPM04_pMe_WeRf:-K_r1SLhlWO3kYlp2hDm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a9d374eb0c384f126edaae6b18494bc73bebae8f/tools/soft_failure.bzl#L34)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider adding "the" before "globbed".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri and +@david-german-tri for review please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-Ka2QMY6Z0bH5cx56TB9:b5bm2jz)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-Ka2qCSNC--fp9SC1Gvl:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/collision/BUILD, line 96 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3LFPz27fTJm3LbB8n:-Ka3LFQ--eu2ogPljHlG:bn1ixqn) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/drake/multibody/collision/BUILD#L96)):*
> ```Python
>         ":collision",
>         "//drake/common:drake_path",
>         "//drake/common:eigen_matrix_compare",
> ```

BTW, this change is profoundly unrelated to the topic at hand. punt to another PR?

---

*[tools/soft_failure.bzl, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3TSGsV-EmkcmcEJRG:-Ka3TSGtVQiF9ecW1L01:bilb9x2) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/tools/soft_failure.bzl#L12)):*
> ```Python
> #  soft_failure_binary_repository(name = "foo", path = "/usr/local/bin/bar")
> #
> # ... will create a binary target @foo://bar that can be used via "bazel run",
> ```

should be `@foo//:bar`

---

*[tools/soft_failure.bzl, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3XixlKcB00wcJF7rM:-Ka3XixlKcB00wcJF7rN:b-csj1ul) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/tools/soft_failure.bzl#L59)):*
> ```Python
>         visibility = ["//visibility:public"],
>     )
>     """.replace("\n", " ") % (warning, basename)
> ```

BTW, consider pulling out the "file template" strings to named multiline strings at file scope, so then indentation can be right. Sadly, it does separate the format substitutions sites from the lists that fill them. OTOH, it took me quite a while to figure out what magic the `replace()` call was doing in this incantation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/collision/BUILD, line 96 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3LFPz27fTJm3LbB8n:-Ka3ZYWhbvVrZyuBqGeb:basyaf8) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/drake/multibody/collision/BUILD#L96)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, this change is profoundly unrelated to the topic at hand. punt to another PR?
</blockquote></details>

Yeah, it's a separate commit at least.  It seemed silly as its own PR, but *shrug*.  I can do that next time.

---

*[tools/soft_failure.bzl, line 12 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3TSGsV-EmkcmcEJRG:-Ka3Zk6b3GtQ5DYs9sSV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/tools/soft_failure.bzl#L12)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

should be `@foo//:bar`
</blockquote></details>

Done.

---

*[tools/soft_failure.bzl, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3XixlKcB00wcJF7rM:-Ka3a-zcOpNNrm2Nxz0I:b8kaxja) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/tools/soft_failure.bzl#L59)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW, consider pulling out the "file template" strings to named multiline strings at file scope, so then indentation can be right. Sadly, it does separate the format substitutions sites from the lists that fill them. OTOH, it took me quite a while to figure out what magic the `replace()` call was doing in this incantation.
</blockquote></details>

I didn't do this earlier because I couldn't figure out named-string substitution for some reason.  But I have the names working now.  Must have been a PEBKAC before.

I've also rephrased the indentation-stripping replacement a bit.  PTAL.

If you think its still confusing, I can extract the strings to globals, but think I prefer the locality of this mechanism if I can make it readable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/soft_failure.bzl, line 59 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-Ka3XixlKcB00wcJF7rM:-Ka3XYc08hA2M0yDCPux:b-fe00fy) ([raw file](https://github.com/robotlocomotion/drake/blob/711d4b7b0d1039d594e8020395d9663016568254/tools/soft_failure.bzl#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I didn't do this earlier because I couldn't figure out named-string substitution for some reason.  But I have the names working now.  Must have been a PEBKAC before.

I've also rephrased the indentation-stripping replacement a bit.  PTAL.

If you think its still confusing, I can extract the strings to globals, but think I prefer the locality of this mechanism if I can make it readable?
</blockquote></details>

I think this revision is clear enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-Ka3lin7l4hPh_z8Ktq2:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
-(status: do not merge)

PTAL.  There are two further improvements that showed up during additional testing.  Apologies for not noticing these in the first round and churning the review:
 1. When the `glob()` fails at build-time, the wrapper script should always fail; it should not magically start working when the binary later appears outside of the workspace.
 2. Running directly `bazel-bin/externals/drake_visualizer/drake-visualizer` by hand outside of the sandbox wasn't working.  Now it does (assuming the target program was found at build-time).

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-Ka94Cu8_inUqvYzN3tJ:bt9sulb)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4705#-:-Ka9GPlt-ctDVlR1jUyg:bnfp4nl)*

**Pull request merged**
