### PR TITLE
Rotation constraint big m

### PR DESCRIPTION
**Pull request by hongkai-dai**
Changed the big M number in two constraints. Potentially this should help the lower bound to increase faster, and mixed-integer problem would converge quicker.

In the `rotation_constraint_limit_test`, I compare the speed before and after this PR

| test number | 1 | 2 | 3 | 4 |
|---|--|--|--|--|
| before this PR (s)| 13.34 | 102.36 | 19.82 | 233.06 |
| after this PR (s) | 12 | 88 | 14.5 | 198.24 |

I do not have other tests that look for an optimal solution using `rotation_constraint.cc`. @gizatt it might help your pose estimation problem.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6872)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@gizatt for feature review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-:-Krr1FwxDBYVxdglA8kP:biagjkq)*

**Comment by gizatt** [comment]
:lgtm: one very minor comment! Looks great!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/rotation_constraint.cc, line 803 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-KrrI9O7G9siskOMd-ze:-KrrI9O8d9PyC1PEpJRv:b-1bes9k) ([raw file](https://github.com/robotlocomotion/drake/blob/332566a59763e89fc15b038c8e63b4fb0c77f458/drake/solvers/rotation_constraint.cc#L803)):*
> ```cpp
>               //   |v2 - normal.cross(v1)| <= 2*sin(θ/2).
>               const double sin_theta2 = sin(theta/2);
>               const Vector3<symbolic::Expression> v2_minus_n_cross_n1{
> ```

Variable should be named "v2_minus_n_cross_v1" instead of "...n1"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-:-KrrINGCMwKt0D-utc30:b-u64qsu)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/rotation_constraint.cc, line 803 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-KrrI9O7G9siskOMd-ze:-KrrqDc9eaQTT5llQaMD:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/332566a59763e89fc15b038c8e63b4fb0c77f458/drake/solvers/rotation_constraint.cc#L803)):*
<details><summary><i>Previously, gizatt (Gregory Izatt) wrote…</i></summary><blockquote>

Variable should be named "v2_minus_n_cross_v1" instead of "...n1"?
</blockquote></details>

Done. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872)*

**Comment by hongkai-dai** [comment]
+@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-:-KrrqGUMxeoA0_X1AusV:b6vi582)*

**Comment by sherm1** [comment]
Platform :lgtm:, pending CI.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-:-KrrrdqtZtQwzBlGs5JM:b2bb7qv)*

**Comment by sherm1** [comment]
@hongkai-dai, this PR is ready for a squash-merge.

**Comment by sherm1** [comment]
P.S. Please update the commit comment on the squashed commit before you merge.

**Comment by hongkai-dai** [comment]
-(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6872#-:-KsQytnfRaFgpPlO_DIG:b-l70wzf)*

**Pull request merged**
