### PR TITLE
Bug fixes for holonomic and weld constraints

### PR DESCRIPTION
**Pull request by amcastro-tri**
A separate comits for each fix:
 - Fixes math in the computation of the weld constraint Jacobian
 - Fixes DEMAND of already moved variables in holonomic constraints

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-:-O9QzZ8O4HJy6FbUdAMx:bqwin3e)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by joemasterjohn — COMMENTED** [review]
Good catch! :lgtm: feature. +@sherm1 for platform review, please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-:-O9R1kkr12yeeo-Vsqab:b-9in0i1)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
Excellent! Great to see the better unit test that would have caught this problem.
Platform :lgtm: pending one minor fix and an ignorable suggestion.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-:-O9R9Eky-HWHoWA4mZDm:b-4elavi)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-O9R7vjVCH-LjX4NiBrV:-O9R7vjVCH-LjX4NiBrW:btrxa33) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3f9280e2365b23232fcf49d808233f4b9f038c1/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L30)):*
> ```cpp
>   DRAKE_DEMAND(impulse_lower_limits_.size() == relaxation_times_.size());
>   DRAKE_DEMAND((impulse_lower_limits_.array() <= kInf).all());
>   DRAKE_DEMAND((impulse_upper_limits.array() >= -kInf).all());
> ```

minor: the underscore is missing here.
___
*[`multibody/plant/sap_driver.cc` line 644 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-O9R8Wh52dyZRA39UX0n:-O9R8Wh52dyZRA39UX0o:b-2m09o5) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3f9280e2365b23232fcf49d808233f4b9f038c1/multibody/plant/sap_driver.cc#L644)):*
> ```cpp
>     const math::RigidTransform<T> X_WQ = X_WB * spec.X_BQ.template cast<T>();
>     const math::RotationMatrix<T> R_AW = X_WA.rotation().transpose();
>     const math::RotationMatrix<T> R_BW = X_WB.rotation().transpose();
> ```

BTW consider `.inverse()` here rather than transpose. (They are the same, but the fact that the inverse happens to be the transpose is irrelevant here.)

**Review by sherm1 — COMMENTED** [review]
Also, the Mac failure looks like a test whose tolerance is too tight and should be fixed:
```
[12:53:22 PM]  [ RUN      ] SapWeldConstraintTests/TwoBodiesTest.ConfirmConstraintProperties/SingleClique
[12:53:22 PM]  multibody/plant/test/sap_driver_weld_constraints_test.cc:254: Failure
[12:53:22 PM]  Value of: CompareMatrices(J, J_expected, kEps, MatrixCompareType::relative)
[12:53:22 PM]    Actual: false (Values at (3, 1) exceed tolerance: 3.597427876414631 vs. 3.5974278764146326, diff = 1.7763568394002505e-15, tolerance = 4.440892098500626e-16, relative tolerance = 1.5975789031295629e-15
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-:-O9RA15x9V9LVczweioK:b-pxw0a5)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

___
*[`multibody/contact_solvers/sap/sap_holonomic_constraint.cc` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-O9R7vjVCH-LjX4NiBrV:-O9RC-IhBjzTsbw5edDC:bd5l6mr) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3f9280e2365b23232fcf49d808233f4b9f038c1/multibody/contact_solvers/sap/sap_holonomic_constraint.cc#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: the underscore is missing here.
</blockquote></details>

thanks!
___
*[`multibody/plant/sap_driver.cc` line 644 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22057#-O9R8Wh52dyZRA39UX0n:-O9RC0nO9fy3SWfIpO9t:b-6pxi66) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3f9280e2365b23232fcf49d808233f4b9f038c1/multibody/plant/sap_driver.cc#L644)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider `.inverse()` here rather than transpose. (They are the same, but the fact that the inverse happens to be the transpose is irrelevant here.)
</blockquote></details>

My personal preference is to use `transpose()` for rotations. That's how I'd write it in math.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22057)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @amcastro-tri)

**Comment by jwnimmer-tri** [comment]
BTW Remember to use "status: squashing now" not "status: properly curated".  (Using "properly curated" is contingent on marking it at the start of reviews (so both reviewers actually check that it _is_ actually curated), and someone locally running `bazel test //...` on the entire tree between the two commits and pinky-swearing that it actually passed.)

**Pull request merged**
