### PR TITLE
[multibody] Use ValueProducer sugar in DiscreteUpdateManager

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for feature review, please.  (The small plant unit test change will require platform.)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature done. There's a duplicated method. PTAL, thanks.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376#-:-MeRoh3AEVLqA2a7ecAA:bvtgw6y)* status: 4 unresolved discussions, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRlWlhCJf_203ZWTbs:-MeRlWlhCJf_203ZWTbt:boplhq0) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L124)):*
> ```objc
>   /* Extracts the q, qdot, and qddot from the given context and copies them to
>    the cached fem state. */
>   void CopyToFemState(SoftBodyIndex deformable_body_id,
> ```

nit: There's a corresponding Eval method (tagged below). Please consider placing them close to each other and/or make their names more uniform.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRlg-k2ALBxfaqNkfd:-MeRlg-k2ALBxfaqNkfe:boplhq0) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L129)):*
> ```objc
> 
>   /* Calculates the free-motion velocity for the deformable body. */
>   void CalcFemStateStar(SoftBodyIndex deformable_body_id,
> ```

nit: There's a corresponding Eval method (tagged below). Please consider placing them close to each other and/or make their names more uniform.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRl6nl6sMHB5Y5EzpW:-MeRl6nl6sMHB5Y5EzpX:b-gv9b8) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L134)):*
> ```objc
> 
>   /* Calculates the contact data for all deformable bodies. */
>   void CalcContactData(
> ```

A similar method already exists below. Please consider removing the old one (tagged below) in favor of the new one.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRls0nE7rl2immAmV3:-MeRls0nE7rl2immAmV4:b82ypwd) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L175)):*
> ```objc
> 
>   /* Evaluates the FEM state of the deformable body with index `id`. */
>   const FemStateBase<T>& EvalFemStateBase(const systems::Context<T>& context,
> ```

FYI, this is the Eval version of `CopyToFemState()`.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 184 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRlhlG7EiuEi7PLExm:-MeRlhlG7EiuEi7PLExn:b-ntc7fw) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L184)):*
> ```objc
>   /* Evaluates the free motion FEM state of the deformable body with index `id`.
>    */
>   const FemStateBase<T>& EvalFreeMotionFemStateBase(
> ```

FYI, this is the Eval version of `CalcFemStateStar()`.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 225 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRm4hM7SOfrXbL93wN:-MeRm4hM7SOfrXbL93wO:b99rot3) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L225)):*
> ```objc
>    (data[i]) in the return value will have `data[i].num_contact_points() == 0`.
>   */
>   std::vector<internal::DeformableContactData<T>> CalcDeformableRigidContact(
> ```

FYI, this essentially the same as the `CalcContactData()`. I prefer this name as it's more specific: the method doesn't calculation all contact data, but just the contact data between deformable and rigid bodies.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRn_KX4SKKFG7Mt9RG:-MeRn_KX4SKKFG7Mt9RH:btkz1hz) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L170)):*
> ```cpp
>     std::vector<internal::DeformableContactData<T>>* result) const {
>   result->clear();
>   this->UpdateCollisionObjectPoses(context);
> ```

nit: `this->` not needed.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 124 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRlWlhCJf_203ZWTbs:-MeRpu86B-hhkllG7uCX:b4s28pa) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L124)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: There's a corresponding Eval method (tagged below). Please consider placing them close to each other and/or make their names more uniform.
</blockquote></details>

Done.

For all of these, I took the current Eval as gospel and switched the Calc to mimic it.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 129 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRlg-k2ALBxfaqNkfd:-MeRqIaa2x6OFldX2ifB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L129)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: There's a corresponding Eval method (tagged below). Please consider placing them close to each other and/or make their names more uniform.
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.h, line 134 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRl6nl6sMHB5Y5EzpW:-MeRrLCo07sUaYVRPMTW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.h#L134)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

A similar method already exists below. Please consider removing the old one (tagged below) in favor of the new one.
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRn_KX4SKKFG7Mt9RG:-MeRsIIr32K4fYyJ35Zv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5b1f9b5f55755599b8c27a566f5a4c893e5a1005/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L170)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit: `this->` not needed.
</blockquote></details>

Done.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm_strong: Thanks for doing this. The lambdas were growing out of control!
+@rpoyner-tri for platform review on Tuesday per rotation please, thank you.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376#-:-MeRv9t42OMAjVcYSDYn:b-omdq38)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 105 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRx_vaAr_P6NSuZdEf:-MeRx_vaAr_P6NSuZdEg:bl1t26t) ([raw file](https://github.com/robotlocomotion/drake/blob/46b21d98fa0ebde6237e5f311627122924b63a43/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L105)):*
> ```cpp
>                 std::bind(&DeformableRigidManager<T>::CalcFemStateBase, this,
>                           std::placeholders::_1, deformable_body_id,
>                           std::placeholders::_2))),
> ```

BTW Yuck! Why use `std::bind` rather than a lambda with capture? I have been treating std::bind as obsolete -- is it actually required here for some reason?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 105 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRx_vaAr_P6NSuZdEf:-MeS-QabA7GjrhKnrrw6:b-9mflp4) ([raw file](https://github.com/robotlocomotion/drake/blob/46b21d98fa0ebde6237e5f311627122924b63a43/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L105)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Yuck! Why use `std::bind` rather than a lambda with capture? I have been treating std::bind as obsolete -- is it actually required here for some reason?
</blockquote></details>

Phrasing it as `bind` just happened to be the first thing I tried.  In my mind, I just want to call the member function _but_ with a single argument pre-bound here.  In other words, the same mnemonic as https://docs.python.org/3/library/functools.html#functools.partial.  Maybe what I really want is sugar atop `bind` to say "forward everything but curry the n'th argument to be set to foo".  That would reduce the syntax here, while preserving the mnemonic.

This is what the lambda patch would look like.

```patch
@@ -99,10 +99,11 @@ void DeformableRigidManager<T>::DeclareCacheEntries() {
         fmt::format("FEM state {}", deformable_body_id),
         systems::ValueProducer(
             *model_fem_state,
-            std::function<void(const systems::Context<T>&, FemStateBase<T>*)>(
-                std::bind(&DeformableRigidManager<T>::CalcFemStateBase, this,
-                          std::placeholders::_1, deformable_body_id,
-                          std::placeholders::_2))),
+            std::function{
+                [this, deformable_body_id](const systems::Context<T>& context,
+                                           FemStateBase<T>* result) {
+                  this->CalcFemStateBase(context, deformable_body_id, result);
+                }}),
         {systems::System<T>::xd_ticket()});
     fem_state_cache_indexes_.emplace_back(fem_state_cache_entry.cache_index());
 
```

I don't know that I'd argue either one is best; neither are great.

I'd meant to post in the PR overview a disclaimer that this is a step in a better direction, but further improvements might still be worthwhile.  We could imagine improving the ValueProducer sugar even more so that binding is easier in cases where we have indexed callbacks like these, or extra data in general, or something.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri Take note -- only one file (the test) needs platform review.  The other two are exempt.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 105 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeRx_vaAr_P6NSuZdEf:-MeS4mWU0HG8lZhwJ96g:b-hjst4e) ([raw file](https://github.com/robotlocomotion/drake/blob/46b21d98fa0ebde6237e5f311627122924b63a43/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L105)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Phrasing it as `bind` just happened to be the first thing I tried.  In my mind, I just want to call the member function _but_ with a single argument pre-bound here.  In other words, the same mnemonic as https://docs.python.org/3/library/functools.html#functools.partial.  Maybe what I really want is sugar atop `bind` to say "forward everything but curry the n'th argument to be set to foo".  That would reduce the syntax here, while preserving the mnemonic.

This is what the lambda patch would look like.

```patch
@@ -99,10 +99,11 @@ void DeformableRigidManager<T>::DeclareCacheEntries() {
         fmt::format("FEM state {}", deformable_body_id),
         systems::ValueProducer(
             *model_fem_state,
-            std::function<void(const systems::Context<T>&, FemStateBase<T>*)>(
-                std::bind(&DeformableRigidManager<T>::CalcFemStateBase, this,
-                          std::placeholders::_1, deformable_body_id,
-                          std::placeholders::_2))),
+            std::function{
+                [this, deformable_body_id](const systems::Context<T>& context,
+                                           FemStateBase<T>* result) {
+                  this->CalcFemStateBase(context, deformable_body_id, result);
+                }}),
         {systems::System<T>::xd_ticket()});
     fem_state_cache_indexes_.emplace_back(fem_state_cache_entry.cache_index());
 
```

I don't know that I'd argue either one is best; neither are great.

I'd meant to post in the PR overview a disclaimer that this is a step in a better direction, but further improvements might still be worthwhile.  We could imagine improving the ValueProducer sugar even more so that binding is easier in cases where we have indexed callbacks like these, or extra data in general, or something.
</blockquote></details>

My 2¢ -- the lambda is _much_ easier to read.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376#-:-MeVKGb-0TCJhPXL0dM7:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 126 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeVJzdk88KKDfQRA2vK:-MeVJzdl2yCLAN1BqubJ:bvvrw0q) ([raw file](https://github.com/robotlocomotion/drake/blob/169394f89c9ded72793f8c221d4ffaa44ecab45b/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L126)):*
> ```cpp
>     const auto& fem_state_cache_entry = this->DeclareCacheEntry(
>         "FEM state",
>         // TODO(jwnimmer-tri) The use of lambdas for calculation functions is
> ```

BTW is this documented or explained anywhere? For my education...

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15376)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri (waiting on @jwnimmer-tri)

___
*[multibody/fixed_fem/dev/deformable_rigid_manager.cc, line 126 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15376#-MeVJzdk88KKDfQRA2vK:-MeVNa1z4-TAGMBP7JU3:b-xbdzw7) ([raw file](https://github.com/robotlocomotion/drake/blob/169394f89c9ded72793f8c221d4ffaa44ecab45b/multibody/fixed_fem/dev/deformable_rigid_manager.cc#L126)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

BTW is this documented or explained anywhere? For my education...
</blockquote></details>

OK I'll see what I can dig up, and/or add new documentation to clarify.  I've made a note in #15161.

The short answer would go something like this:

(1) By promoting the computational logic to a first-class citizen (a named member function, vs splatters of code within a constructor), the purpose and semantics of each callback is made more clear for the reader.  For example, in this PR we've obtained a nice Calc/Eval symmetry for the various functions of the context state.

(2) In most cases (but not here, due to the curried body id), the `&MyClass::MyCalc` syntax for binding the callback is the most ergonomic.

**Pull request merged**
