### PR TITLE
Add python binding on GurobiSolver callbacks

### PR DESCRIPTION
**Pull request by hongkai-dai**
As requested from stackoverflow https://stackoverflow.com/q/72823452/1973861

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17704)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@ericcousineau-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17704#-:-N8w5ovDCp6J6wEzAoIe:bhru7xi)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: x2 with blocker (minor) on missing class docs

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17704#-:-N8xwbrmB6ociV2T_ruI:bb2j9t9)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`bindings/pydrake/solvers/solvers_py_gurobi.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17704#-N8xwS4q4NL2nGgB_rFX:-N8xwS4rBcaQDzfKeFkV:b53i387) ([raw file](https://github.com/robotlocomotion/drake/blob/55cf169208c3169bced3fd5236a81323f59605e5/bindings/pydrake/solvers/solvers_py_gurobi.cc#L41)):*
> ```cpp
>   AddValueInstantiation<GurobiSolverDetails>(m);
> 
>   py::class_<GurobiSolver::SolveStatusInfo>(cls, "SolveStatusInfo")
> ```

Missing class doc, `doc.SolveStatusInfo.doc`?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17704)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bindings/pydrake/solvers/solvers_py_gurobi.cc` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17704#-N8xwS4q4NL2nGgB_rFX:-N8yAXFz86RDvQ4sJzDB:b-376vyb) ([raw file](https://github.com/robotlocomotion/drake/blob/55cf169208c3169bced3fd5236a81323f59605e5/bindings/pydrake/solvers/solvers_py_gurobi.cc#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Missing class doc, `doc.SolveStatusInfo.doc`?
</blockquote></details>

Done. Good catch.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17704)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @hongkai-dai)

**Pull request merged**
