### PR TITLE
Add some convenience accessors for State dimensions.

### LINKED ISSUE #4262: Need IsContinuousTimeOnly and IsDiscreteTimeOnly for Context<T>
IsContinuousTimeOnly should return true iff there is continuous state but no discrete nor modal state.  

IsDiscreteTimeOnly should return true iff there is discrete state but no continuous nor modal state.

These will be used, eg, in Linearize/LQR/Kalman/... to justify only examining the Derivatives and making an approximation of xdot, or only discrete analysis.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #4262

@RussTedrake for both levels of review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4297)

### CODE REVIEW

**Comment by sherm1** [comment]
One comment.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/context.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-KXmIeOpMyoqha2ycivv:-KXmIeOpMyoqha2ycivw:bojq12m) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4183ac80803f126e9e6f36d289531296c3964/drake/systems/framework/context.h#L101)):*
> ```objc
> 
>   /// Returns the number of elements in the difference state.
>   int get_difference_state_size() const {
> ```

BTW, I suspect this will be misleading since each "element" of the difference state is a vector. I suggest calling this something like `get_num_difference_state_groups()`; the current name could be reserved for something that would return the total number of scalars.

Could the difference variables be returned as a Supervector so that they could be treated all together in cases where that makes sense? The reasons for subgrouping have to do with update rate and limiting the scope of cache invalidation -- those are important but obscure so it would be nice if the easy case treated xd as a single vector as we do xc (even though it has q,v,z subgroups).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-:-KXmKE-3qvfOAcc2HDLK:b-xclmb6)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/context.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-KXnDf2SGVQsaqWg0BXH:-KXnDf2SGVQsaqWg0BXI:brcan1n) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4183ac80803f126e9e6f36d289531296c3964/drake/systems/framework/context.h#L55)):*
> ```objc
>   /// Returns true if the Context has continuous state, but no difference or
>   /// modal state.
>   bool has_only_continuous_state() const {
> ```

BTW, this definitely looks like a good method to have, but I'm not sure if it's a sufficient check for my testing purposes.  In the specific case which motivated this, what I need to know is whether it's ok to approximate the system as a continuous-time linear system.  Are there other system/context properties that I need to check?  e.g. to make sure that there aren't events or discrete updates getting called which I will miss?  or discrete sample times on the output port, ...?

---

*[drake/systems/framework/context.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-KXmIeOpMyoqha2ycivv:-KXnD_doftKMDbtRHBUP:bq8q1pb) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4183ac80803f126e9e6f36d289531296c3964/drake/systems/framework/context.h#L101)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I suspect this will be misleading since each "element" of the difference state is a vector. I suggest calling this something like `get_num_difference_state_groups()`; the current name could be reserved for something that would return the total number of scalars.

Could the difference variables be returned as a Supervector so that they could be treated all together in cases where that makes sense? The reasons for subgrouping have to do with update rate and limiting the scope of cache invalidation -- those are important but obscure so it would be nice if the easy case treated xd as a single vector as we do xc (even though it has q,v,z subgroups).
</blockquote></details>

i agree the original name is confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4297)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/context.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-KXnDf2SGVQsaqWg0BXH:-KXrhgZHKUz0QGSAMiGE:b-5uty7n) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4183ac80803f126e9e6f36d289531296c3964/drake/systems/framework/context.h#L55)):*
>  Are there other system/context properties that I need to check?

I don't think so.  Discrete updates can only modify difference state, so if there's no xd there are no discrete updates.  Similarly, output is a function `y(t, x, u, p)`.  Of those components, only `xd`, `xm` and `u` can change discretely, and the properties of `u` are outside the System's control or knowledge.

Once we have witness functions, I suppose a system with only continuous state could experience discontinuous events (e.g. bouncing-ball) but that API doesn't exist yet.

Also, since it sounds like a stateless system would count as continuous for your purposes, I've added `is_stateless`.

---

*[drake/systems/framework/context.h, line 101 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-KXmIeOpMyoqha2ycivv:-KXrlhxyLBkbFjIWXJ4S:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ace4183ac80803f126e9e6f36d289531296c3964/drake/systems/framework/context.h#L101)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i agree the original name is confusing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4297)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-:-KXrthBdfHNA4I0Blfvd:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@sherm1 -@RussTedrake 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4297#-:-KXuo30lN9fQdiqUqEmq:bbsz6fu)*

**Pull request merged**
