### PR TITLE
Residual, feasibility, and linear solver classes for dense QPs

### PR DESCRIPTION
**Pull request by dliaomcp**
Part 2

+@frankpermenter for feature review, please
+@soonho-tri for platform review, please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/11797)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
(Using `+@...` in the PR overview does not work -- that syntax only works in comments.  I've updated assignees manually.)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
@soonho-tri @dliaomcp Please double-check that `add_lint_tests()` appears as the last line of each `BUILD.bazel` file.  From a quick glance it seemed to be missing.

**Comment by soonho-tri** [comment]
@jwnimmer-tri , thanks for the check!
@dliaomcp , can you add `add_lint_tests()` to the files?

**Pull request merged**
