### PR TITLE
Add semi-automated Python binding generation tool

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #7889, #14265, and [autopybind11/autopybind11#140](https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/140) (gitlab.kitware.com).

Needs CI update.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14878)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
Unprovisioned are happy so using system dependencies where possible is looking good.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-leak-sanitizer please

**Comment by jamiesnape** [comment]
`Error in fail: Header external/eigen/include/_usr_include_eigen3/Eigen/Cholesky lacks a plausible include path`. Looks like #15069 has changed some behavior. FYI @jwnimmer-tri (though I am sure the issue is here, not in #15069).

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14878)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14878#-McBXF-MEMd-944zncIG:-McBUnYI7uJdsuV3jG9F:bf8rj2z) (no related file):*
Should it worry me that just adding a header that includes generated lcm headers fails because it can't find those headers? Do I need to augment some build rule somewhere?

```
diff --git a/tools/autopybind/bindings_to_generate.yaml b/tools/autopybind/bindings_to_generate.yaml
index bbee6e93e1..ba174c0328 100644
--- a/tools/autopybind/bindings_to_generate.yaml
+++ b/tools/autopybind/bindings_to_generate.yaml
@@ -151,3 +151,23 @@ files:
                   DepthRange: {}
                   DepthRenderCamera: {}
                   RenderEngine: {}
+  # This stanza fails to build because generated headers for
+  # lcm structs are not found.
+  # "drake/manipulation/kuka_iiwa/iiwa_command_receiver.h":
+  #   namespaces:
+  #     drake:
+  #       namespaces:
+  #         manipulation:
+  #           namespaces:
+  #             kuka_iiwa:
+  #               classes:
+  #                 IiwaCommandReceiver: {}
```

For now, I'm doing experiments in a branch that contains this PR and a revert of #15069.

---

**Comment by jamiesnape** [comment]
Try adding `//lcmtypes:lcmtypes_drake_cc` here and see if it unblocks you: https://github.com/RobotLocomotion/drake/blob/bd479344132234146c7fdb9737507118d6555453/tools/autopybind/BUILD.bazel#L20

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14878)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14878#-McBXF-MEMd-944zncIG:-McGTm659EFiyV5fKwwU:bemjuve) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Should it worry me that just adding a header that includes generated lcm headers fails because it can't find those headers? Do I need to augment some build rule somewhere?

```
diff --git a/tools/autopybind/bindings_to_generate.yaml b/tools/autopybind/bindings_to_generate.yaml
index bbee6e93e1..ba174c0328 100644
--- a/tools/autopybind/bindings_to_generate.yaml
+++ b/tools/autopybind/bindings_to_generate.yaml
@@ -151,3 +151,23 @@ files:
                   DepthRange: {}
                   DepthRenderCamera: {}
                   RenderEngine: {}
+  # This stanza fails to build because generated headers for
+  # lcm structs are not found.
+  # "drake/manipulation/kuka_iiwa/iiwa_command_receiver.h":
+  #   namespaces:
+  #     drake:
+  #       namespaces:
+  #         manipulation:
+  #           namespaces:
+  #             kuka_iiwa:
+  #               classes:
+  #                 IiwaCommandReceiver: {}
```

For now, I'm doing experiments in a branch that contains this PR and a revert of #15069.
</blockquote></details>

The remedy recommended above (add a dependency) worked.

---

**Comment by jamiesnape** [comment]
Moved to #15205.

**Pull request closed without merging**
