### PR TITLE
add minimal bindings for linear/affine systems

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8097)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for both reviews, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8097#-:-L5auY6-HRRcpH4l8mPU:b-dpgjx8)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/primitives_py.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8097#-L5l22KUP33dvAxe82N0:-L5l22KVaoMh_jmnUXhr:bxsh0v) ([raw file](https://github.com/robotlocomotion/drake/blob/cfd89316db866d8dbe4ea399b4abce426afaf14c/bindings/pydrake/systems/primitives_py.cc#L38)):*
> ```cpp
>            py::arg("D"), py::arg("y0"), py::arg("time_period") = 0.0)
>       .def("A",
>            overload_cast_explicit<const Eigen::MatrixXd&>(&AffineSystem<T>::A))
> ```

BTW I believe this will not return an actual reference to `A`, but rather a copy. Can you add a TODO for me to resolve this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8097#-:-L5l2Gas3m2iyKm9KyRO:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/systems/primitives_py.cc, line 38 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8097#-L5l22KUP33dvAxe82N0:-L5l8nfYvBW28IG7s0fK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cfd89316db866d8dbe4ea399b4abce426afaf14c/bindings/pydrake/systems/primitives_py.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I believe this will not return an actual reference to `A`, but rather a copy. Can you add a TODO for me to resolve this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8097)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8097)*

**Pull request merged**
