### PR TITLE
Move matplotlib and tk to binary distribution prerequisities scripts and add pydot

### LINKED ISSUE #8918: Binary install_prereqs missing python-tk
Encountered by a user on Wednesday at the Cornell tutorial, and also encountered by myself when setting up a test image. Needs to be pulled from apt, I think?

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #8918.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9034)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-unprovisioned-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
+@gizatt for feature review and +@sammy-tri for platform review.

**Comment by gizatt** [comment]
:lgtm:, thanks!

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9034#-:-LFU0XU17qa22QfHNKuL:bpqxd5f)*

**Pull request merged**
