### PR TITLE
 [workspace] Upgrade gz_math_internal to latest release gz-math7_7.3.0

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/20108

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri this one should be a pretty simple fix to get building correctly.  Are you up for pushing the fixup to the PR?

**Review by rpoyner-tri — COMMENTED** [review]
:eyes: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-:-NdlP2WH3As0y0VAAZ7I:bd5ty59)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-:-NdlZZqS1kJ4F2eoVJmx:b-chsgxs)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-:-NdlgiJeErmbACG-OD_V:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-:-Ndp1F0HD7q_8roVldUJ:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-:-Ndp4T6A37VNipirE9dn:b-vtj4vo)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[`tools/workspace/gz_math_internal/package.BUILD.bazel` line 218 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20146#-Ndp4QZe75J1a4hVntoS:-Ndp4QZe75J1a4hVntoT:b-tivgvx) ([raw file](https://github.com/RobotLocomotion/drake/blob/56e1e4b8947830b3c0608186d9f1994ef223d958/tools/workspace/gz_math_internal/package.BUILD.bazel#L218)):*
> ```
> 
> # The explicitly listed srcs= matches upstream's explicitly listed sources plus
> # private headers.
> ```

nit From a peek at [the upstream PR](https://github.com/gazebosim/gz-math/pull/549/files) it looks like there is a `cc` file also that we should be adding here.

**Comment by rpoyner-tri** [comment]
+(status: squashing now)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146)* status: 1 unresolved discussion

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20146)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
