### PR TITLE
Add ability to alter the mirrors used in workspace

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The `tools/workspace/default.bzl` gains a `mirrors` argument that allows changing which mirrors are used.  The argument is passed down to only the repositories that use mirrors; to ensure that's reliably achieved, all of the individual rules and repositories declare `mirrors = None` as an argument and fail if no value was supplied.  Only the `default.bzl` provides a default value.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8196)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.
\CC @jamiesnape

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-:-L6Ou4Kzz3-P5JNe4Fz1:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule (tomorrow), please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM: with a few cosmetic documentation thoughts.

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/workspace/mirrors.bzl, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SBEzXWOs3bQXQnqgj:-L6SBEzXWOs3bQXQnqgk:b-eibee9) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/mirrors.bzl#L6)):*
> ```Python
> # This constant contains Drake's default lists of mirrors.  It is keyed by the
> # repository type using magic strings ("github", "bitbucket", etc.), and has
> # values of type list-of-string; each string is a pattern for a mirror URL.
> ```

BTW Worth explicitly noting that the pattern string must have the same place-holder names inside the list for a single magic string, but the set of place-holder names can change from magic string to magic string?

---

*[tools/workspace/mirrors.bzl, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SFenF0ceQusOVRy26:-L6SFenF0ceQusOVRy27:b3jcdgl) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/mirrors.bzl#L21)):*
> ```Python
> DEFAULT_MIRRORS = {
>     "bitbucket": [
>         "https://bitbucket.org/{repository}/get/{commit}.tar.gz",
> ```

FYI When the set of substitution names match up between two sets of mirrors, it becomes possible for someone downstream to add a repo against bitbucket instead of github (as an example). The error won't be in string substitution, but in pulling data from the mirrors. Any thoughts on failing faster by making sure that the *set* of parameters across any of these default mirrors don't match?

I realize it's largely a palliative because other mirrors could be added that would likewise mirror the substitution labels.  But the thought popped into my mind while I was looking at this.

---

*[tools/workspace/pypi.bzl, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SDEZ7SnyGTJoGTaTV:-L6SDEZ7SnyGTJoGTaTW:b-ew6dpf) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/pypi.bzl#L71)):*
> ```Python
> 
>         mirrors: A dict from string to list-of-string with key "pypi", where
>             the list-of-strings are URLs to use, formatted using {repository}
> ```

BTW copypasta -- pypi takes `p`, `package`, and `version`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-:-L6SG5rQpb1GOW-7Uhxz:b-xbrgr5)*

**Comment by jwnimmer-tri** [comment]
Review status: 38 of 40 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/workspace/mirrors.bzl, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SBEzXWOs3bQXQnqgj:-L6SKEtT__pJ2KrFvkoe:b89a9ou) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/mirrors.bzl#L6)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Worth explicitly noting that the pattern string must have the same place-holder names inside the list for a single magic string, but the set of place-holder names can change from magic string to magic string?
</blockquote></details>

Done.

I added some text below.  (Note that the pattern string is allowed _not_ to use certain substitutions, but can only use _at most_ the substitutions provided by the kind of repository -- an example is that `{p}` is only used by one of the pypi pattern strings.)

---

*[tools/workspace/mirrors.bzl, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SFenF0ceQusOVRy26:-L6SKlZIPA8qjz1JA-fX:b-y9qvs6) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/mirrors.bzl#L21)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI When the set of substitution names match up between two sets of mirrors, it becomes possible for someone downstream to add a repo against bitbucket instead of github (as an example). The error won't be in string substitution, but in pulling data from the mirrors. Any thoughts on failing faster by making sure that the *set* of parameters across any of these default mirrors don't match?

I realize it's largely a palliative because other mirrors could be added that would likewise mirror the substitution labels.  But the thought popped into my mind while I was looking at this.
</blockquote></details>

OK That seems rare enough that I think I'll stick with the shorter substitution keywords.

---

*[tools/workspace/pypi.bzl, line 71 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8196#-L6SDEZ7SnyGTJoGTaTV:-L6SJyj52XezURyBWYT1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2f5b4135fa66ee4086eceee3ff74c0d7f891c847/tools/workspace/pypi.bzl#L71)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW copypasta -- pypi takes `p`, `package`, and `version`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8196)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8196)*

**Pull request merged**
