### PR TITLE
[workspace] Add new_release tooling for automatic upgrades

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

I have tested locally with `fcl`, `rules_python`, and `rules_skylib`.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/new_release.py, line 226 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MkxsEkgDNq6tijToMsC:-MkxsEkgDNq6tijToMsD:b-4l10hz) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L226)):*
> ```Python
>     print("Done.  Be sure to review and commit the changes:")
>     message = f"[workspace] Upgrade {workspace_name}"
>     if len(new_commit) == 40:
> ```

Magic constant 40 could use some explanation. Also, what prevents some dependency release tag from being exactly 40 characters?
___
*[tools/workspace/new_release.py, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-Mkxq2EW9yXa5lGZEg64:-Mkxq2EW9yXa5lGZEg65:bobxfn9) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L235)):*
> ```Python
> 
> def main():
>     parser = argparse.ArgumentParser(prog="new_release", description=__doc__)
> ```

consider using argparse.RawDescriptionHelpFormatter; right now the nice layout of the man docstring gets mangled.
___
*[tools/workspace/new_release.py, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MkxqirZ6GwyUBWBzLH3:-MkxqirZ6GwyUBWBzLH4:btne2wm) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L275)):*
> ```
>  repositores
> ```
typo, that prevents no-args invocation from running.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864#-:-MkxtYEJ1Dh3h4NSOd-4:bnfp4nl)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[tools/workspace/new_release.py, line 226 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MkxsEkgDNq6tijToMsC:-Ml0mbwj-oEfJ1yO3CNi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L226)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Magic constant 40 could use some explanation. Also, what prevents some dependency release tag from being exactly 40 characters?
</blockquote></details>

Done.
___
*[tools/workspace/new_release.py, line 235 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-Mkxq2EW9yXa5lGZEg64:-Ml0mck3Eq9uixOTQDpv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L235)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

consider using argparse.RawDescriptionHelpFormatter; right now the nice layout of the man docstring gets mangled.
</blockquote></details>

Done.
___
*[tools/workspace/new_release.py, line 275 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MkxqirZ6GwyUBWBzLH3:-Ml0lTf5BYno1fD_lDL2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7b2cbc14ecd236d4bf994e2838a18b3eae8693e2/tools/workspace/new_release.py#L275)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

> ```
>  repositores
> ```
typo, that prevents no-args invocation from running.
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with BTW comments

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864#-:-MlCFwvh5hDyFPe2WMTG:brbikej)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[tools/workspace/new_release.py, line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MlCF2Pj5TCDRMWltLmA:-MlCF2Pj5TCDRMWltLmB:b-fh468p) ([raw file](https://github.com/robotlocomotion/drake/blob/e5ea5f16cdd97a014d7b6aac47c348df7b6237e2/tools/workspace/new_release.py#L165)):*
> ```Python
> def _do_upgrade(temp_dir, gh, workspace_name, metadata):
>     if workspace_name not in metadata:
>         raise RuntimeError(f"Unknown repository {workspace_name}")
> ```

BTW Rather than `RuntimeError`, consider defining custom `UserError`, possibly with `try... except` around `main()` call. (iff stack trace is just noise)
___
*[tools/workspace/new_release.py, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MlCFcSh7X62hkEzzkpg:-MlCFcSh7X62hkEzzkph:b-mvyy56) ([raw file](https://github.com/robotlocomotion/drake/blob/e5ea5f16cdd97a014d7b6aac47c348df7b6237e2/tools/workspace/new_release.py#L230)):*
> ```Python
>     # Copy the downloaded tarball into the repository cache.
>     print("Populating repository cache ...")
>     subprocess.check_call(["bazel", "fetch", "//...", f"--distdir={temp_dir}"])
> ```

BTW Is it worth nothing at the top of the file that this executes `bazel` command, and thus requires all repository / cache arguments to be specified by bazelrc files?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @rpoyner-tri)

___
*[tools/workspace/new_release.py, line 165 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MlCF2Pj5TCDRMWltLmA:-MlCL77jDIrnbXgCVK_j:b-vc4o6c) ([raw file](https://github.com/robotlocomotion/drake/blob/e5ea5f16cdd97a014d7b6aac47c348df7b6237e2/tools/workspace/new_release.py#L165)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Rather than `RuntimeError`, consider defining custom `UserError`, possibly with `try... except` around `main()` call. (iff stack trace is just noise)
</blockquote></details>

Given the small user base of this tool, I think they can handle the occasional stack trace.
___
*[tools/workspace/new_release.py, line 230 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15864#-MlCFcSh7X62hkEzzkpg:-MlCLDQ0-nxP9eUuB3Wd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e5ea5f16cdd97a014d7b6aac47c348df7b6237e2/tools/workspace/new_release.py#L230)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Is it worth nothing at the top of the file that this executes `bazel` command, and thus requires all repository / cache arguments to be specified by bazelrc files?
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15864)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
