### PR TITLE
[framework] Avoid energy-related cache updates for stateless systems

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This shaves around 14% off the compute cost for the PassThrough3 benchmark, once the `dynamic_casts` in the Calc path are already gone.

Relates to #10882 somewhat.

Towards #15421.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432#-:-Mf1Oids6JBy0xj_EF-x:b7dve2f)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

___
*[systems/framework/system.cc, line 909 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15432#-Mf1OkqO5slRi998PVtx:-Mf1OkqO5slRi998PVty:b-aeglel) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5bddeff56380e1fb49178923f243a377a1736a/systems/framework/system.cc#L909)):*
> ```cpp
>   // more specific configuration, kinematics, and mass tickets.
>   const std::set<DependencyTicket> energy_prereqs_for_9171{
>       accuracy_ticket(), all_state_ticket(), all_parameters_ticket()};
> ```

I don't recall (and couldn't find) if there was any reason we went with the all_sources_ticket here before, instead of listing out these three?  Is there a lurking hazard that I might have overlooked?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15432#-Mf1PGVu25sLFW3LjtSI:-Mf1PGVu25sLFW3LjtSJ:b-pt062e) (no related file):*
Seeking input on unit testing.  Should I do an acceptance test that `PassThrough` doesn't invalidate is pe cache on input changes?  Or add a specific check to `system_test` in framework?  Or both?

---

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432)* status: 2 unresolved discussions, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15432#-Mf1PGVu25sLFW3LjtSI:-Mf4zMqD6LiP2-FWSlpe:b-4r3wec) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Seeking input on unit testing.  Should I do an acceptance test that `PassThrough` doesn't invalidate is pe cache on input changes?  Or add a specific check to `system_test` in framework?  Or both?
</blockquote></details>

I think the unit tests should go in system_test only. This change is not specific to PassThrough in any way. I like the "not time dependent" tests you added in system_test. There just needs to be a "not input port dependent" test added there also. The available test_sys_ has input ports so you could set a value on one of them, re-evaluate the relevant methods, and make sure the count has not changed (probably should EvalDerivatives() also and make sure its count _has_ changed). There might be an input port dependency test somewhere there already; I didn't see one though.

Feature :lgtm: pending that.

---
___
*[systems/framework/system.cc, line 909 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15432#-Mf1OkqO5slRi998PVtx:-Mf4xRwD8lSC5ycGnty2:b-x822zn) ([raw file](https://github.com/robotlocomotion/drake/blob/9f5bddeff56380e1fb49178923f243a377a1736a/systems/framework/system.cc#L909)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't recall (and couldn't find) if there was any reason we went with the all_sources_ticket here before, instead of listing out these three?  Is there a lurking hazard that I might have overlooked?
</blockquote></details>

Laziness on my part is the most likely explanation -- I can't see any reason for PE, KE, or conservative power to depend on time or input ports.

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not merge) +@soonho-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432#-:-Mf5HhbCAxWSauTUkgVa:b-7zex2y)* status: LGTM missing from assignee soonho-tri(platform), labeled "do not merge" (waiting on @sherm1 and @soonho-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15432#-Mf1PGVu25sLFW3LjtSI:-Mf5HeRj3C3gdg2PkkVJ:b-896fix) (no related file):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think the unit tests should go in system_test only. This change is not specific to PassThrough in any way. I like the "not time dependent" tests you added in system_test. There just needs to be a "not input port dependent" test added there also. The available test_sys_ has input ports so you could set a value on one of them, re-evaluate the relevant methods, and make sure the count has not changed (probably should EvalDerivatives() also and make sure its count _has_ changed). There might be an input port dependency test somewhere there already; I didn't see one though.

Feature :lgtm: pending that.
</blockquote></details>

Done.

---

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15432#-:-Mf8SOBm7pFpdJ-jdmdw:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
