### PR TITLE
Ensure that the N matrix is consistent with MapVelocityToQdot() and MapQdotToVelocity().

### PR DESCRIPTION
**Pull request by ArjunBadyal**
Pull request adding unit tests to ensure mobilizer implementations are consistent with the N matrix. 
https://stackoverflow.com/questions/75211342/why-isnt-the-use-of-the-kinematic-coupling-matrix-in-unit-tests-for-mobilizers

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

+@sherm1 for feature review or delegation per [Q&A here](https://stackoverflow.com/questions/75211342/why-isnt-the-use-of-the-kinematic-coupling-matrix-in-unit-tests-for-mobilizers).

**Review by sherm1 — COMMENTED** [review]
Thanks, Arjun! 

CI is failing due to some minor [styleguide](https://drake.mit.edu/styleguide/cppguide.html) violations. Here's a sample complaint:
```
multibody/tree/test/planar_mobilizer_test.cc:285:  Missing space before {  [whitespace/braces] [5]
multibody/tree/test/planar_mobilizer_test.cc:298:  Missing space before {  [whitespace/braces] [5]
multibody/tree/test/planar_mobilizer_test.cc:307:  Should have a space between // and comment  [whitespace/comments] [4]
Done processing multibody/tree/test/planar_mobilizer_test.cc
Total errors found: 3
```

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-:-NMZrAJ99YtE_myuMPcp:b-47ri1v)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
Locally you can do `bazel test --config lint //...` to run all of the style linters.

**Review by sherm1 — COMMENTED** [review]
Feature review pass complete with a few comments, PTAL.
Also please consider adding a test for QuaternionFloatingMobilizer (that's actually used for every unconnected free body).
WeldMobilizer is also missing (for good reason though since the functions are all no-ops!). Consider adding a comment in weld_mobilizer_test.cc noting that the Map/N consistency tests are not needed, in case some future programmer adding a mobilizer looks there for a unit test model.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-:-NMZyPlk-CHx5AiQ4gFr:bjngglq)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @ArjunBadyal)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NMZrnxl8n5lxbIZ9I14):*
FYI Ideally the first line of the commit message should be a brief summary (50 characters or less). Then a blank line and then all the detail you want.
___
*[`multibody/tree/test/space_xyz_floating_mobilizer_test.cc` line 211 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NMZxBIw3lQ1tzhBIMrb:-NMZxBIw3lQ1tzhBIMrc:b328iqo) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab61a97931758dffcb71deee1ac779b290e521ef/multibody/tree/test/space_xyz_floating_mobilizer_test.cc#L211)):*
> ```cpp
> 
>   //Ensure N⁺(q) is used in `v = N⁺(q)⋅q̇`
>   EXPECT_TRUE(CompareMatrices(v,Nplus * qdot ,kTolerance, MatrixCompareType::relative));
> ```

nit: there are some lines > 80 chars in the cases where a tolerance was needed
___
*[`multibody/tree/test/space_xyz_mobilizer_test.cc` line 122 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NMZxV4j-p-5nnkCw1NU:-NMZxV4j-p-5nnkCw1NV:b-kjkexr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab61a97931758dffcb71deee1ac779b290e521ef/multibody/tree/test/space_xyz_mobilizer_test.cc#L122)):*
> ```cpp
> 
> TEST_F(SpaceXYZMobilizerTest, MapUsesNplus){
>   const Vector3<double> qdot = (Vector3<double>() << 1, 2, 3, 4, 5, 6).finished();
> ```

minor: oops -- should be only 3 elements here. You could just use the 3-element constructor here and above as you did elsewhere.

**Comment by ArjunBadyal** [comment]
Thank you for the reviews, I have made these changes. The only mobilizer I SetArbitraryNonZeroState() for was the SpaceXYZFloatingMobilizer. Should a non-zero state be set for any of the other mobilizers?

**Review by sherm1 — COMMENTED** [review]
> Should a non-zero state be set for any of the other mobilizers?

Yes, definitely -- thanks, I missed that. Otherwise the states will be zero and can hide errors (e.g. multiplying N * v=0 when v=0 even if N is garbage!).

Thanks for making these changes. CI caught an error I missed before, see below.

[Review best practices tip: when a reviewer leaves a comment, you should always respond. Most commonly, if you address the issue mentioned in the comment you just say "Done". That's a magic keyword to Reviewable that changes the status on that comment to resolved (for most comments). "OK" is magic for "I'm leaving it as-is" (in which case you should say why).]

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-:-NMel-KmEB6sCam6Fegi:bumr28e)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ArjunBadyal)

___
*[`multibody/tree/test/planar_mobilizer_test.cc` line 301 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NMek-tu5U375U7Rn5y4:-NMek-tu5U375U7Rn5y5:b-y94ylv) ([raw file](https://github.com/RobotLocomotion/drake/blob/ea40039f35080ddedb2b6ce77260bdc29b0e34eb/multibody/tree/test/planar_mobilizer_test.cc#L301)):*
> ```cpp
>   Vector3d v(1.5, 2.5, 3.5);
>   Vector3d qdot;
>   mobilizer_->MapQDotToVelocity(*context_, qdot, &v);
> ```

qdot is uninitialized here -- v is the output!

**Comment by ArjunBadyal** [comment]
> Yes, definitely -- thanks, I missed that. Otherwise the states will be zero and can hide errors (e.g. multiplying N * v=0 when v=0 even if N is garbage!).

OK. Does this mean that the velocities should be non-zero or the positions? SetArbitraryNonZeroState sets the angles and translations to non-zero, but not the velocities. v is already set $\neq 0$ in the test.
 
> [Review best practices tip: when a reviewer leaves a comment, you should always respond. Most commonly, if you address the issue mentioned in the comment you just say "Done". That's a magic keyword to Reviewable that changes the status on that comment to resolved (for most comments). "OK" is magic for "I'm leaving it as-is" (in which case you should say why).]

Thank you for letting me know. 

> qdot is uninitialized here -- v is the output!

Done.

**Review by sherm1 — COMMENTED** [review]
BTW you don't need to quote reviewer comments up here -- you can answer them in place in Reviewable.

This is all good now -- my example N*v was no good since you were already setting v to zero. 

Feature :lgtm: pending one minor thing.

+@ggould-tri for platform review per schedule, please

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-:-NMuP__E9d_JMVyjBljJ:bmbs0i5)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ArjunBadyal and @ggould-tri)

___
*[`multibody/tree/test/screw_mobilizer_test.cc` line 316 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NMuQeEg6vusHGZhKN9T:-NMuQeEg6vusHGZhKN9U:bdx839p) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab31c61b595223e5c5a41b86bfafffbac078df15/multibody/tree/test/screw_mobilizer_test.cc#L316)):*
> ```cpp
>   const double translation_z{angle_z * kScrewPitch / (2. * M_PI)};
>   mobilizer_->set_angle(context_.get(), angle_z);
>   mobilizer_->set_translation(context_.get(), translation_z);
> ```

minor: from the Screw mobilizer documentation, the only generalized coordinate is the angle. The translation is computed from the pitch. So setting just the angle is sufficient -- that changes the translation and setting the translation changes the angle (so un-does the previous setting).

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; minor tedious nitpicking below.

> Reviewed 2 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-:-NN2cha48zPnO4hk2N0s:b-s17s39)* status: 6 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ArjunBadyal)

___
*[`multibody/tree/test/planar_mobilizer_test.cc` line 292 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NN2ZbRaCRmUh_N-2i0u:-NN2ZbRaCRmUh_N-2i0v:b-km92oq) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab31c61b595223e5c5a41b86bfafffbac078df15/multibody/tree/test/planar_mobilizer_test.cc#L292)):*
> ```cpp
> 
>   // Set arbitrary v and MapVelocityToQDot.
>   Vector3d v(1.5, 2.5, 3.5);
> ```

minor:  If you avoid reusing "arbitrary number" constants within a test your test will catch more bugs where inputs get switched.
(here and below)



_Suggestion:_
```cpp
5.5, 6.5
```
___
*[`multibody/tree/test/quaternion_floating_mobilizer_test.cc` line 193 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NN2_a6D1EJbEVFCzdJM:-NN2_a6E9VoyluI2PIgr:b-mqa1ec) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab31c61b595223e5c5a41b86bfafffbac078df15/multibody/tree/test/quaternion_floating_mobilizer_test.cc#L193)):*
> ```cpp
>   // Set arbitrary v and MapVelocityToQDot
>   const Vector6<double> v =
>       (Vector6<double>() << 1, 2, 3, 4, 5, 6).finished();
> ```

nit:  Inconsistent formatting of float literals (`1` vs `1.0` below).
Our style guide permits both ( https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals ) but  https://drake.mit.edu/styleguide/cppguide.html#Goals "Just pick one" :-) 

(And below, e.g., ll 198, 223)
___
*[`multibody/tree/test/screw_mobilizer_test.cc` line 313 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NN2adMEB3sh_t2t2WKA:-NN2adMEB3sh_t2t2WKB:bfuj2yb) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab31c61b595223e5c5a41b86bfafffbac078df15/multibody/tree/test/screw_mobilizer_test.cc#L313)):*
> ```cpp
> TEST_F(ScrewMobilizerTest, MapUsesN) {
>   // Set an arbitrary "non-zero" state.
>   const double angle_z{1. * 180. / M_PI};
> ```

nit:  Here and below, trailing-decimal-point is the one style of writing floating point numbers that our style guide does not permit.  (https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals requests "a radix point, with digits on both sides" or "an integer literal (assuming the variable type can exactly represent that integer)")



_Suggestion:_
```cpp
1.0 * 180.0
```
___
*[`multibody/tree/test/universal_mobilizer_test.cc` line 264 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/18642#-NN2cRHdC4PMTNN2O3HW:-NN2cRHdC4PMTNN2O3HX:bf85zqq) ([raw file](https://github.com/RobotLocomotion/drake/blob/ab31c61b595223e5c5a41b86bfafffbac078df15/multibody/tree/test/universal_mobilizer_test.cc#L264)):*
> ```cpp
> 
>   // Set arbitrary v and MapVelocityToQDot.
>   Vector2d v(1.5, 2.5);
> ```

nit:  You'd get slightly better coverage with different values.
(and below at l. 283)



_Suggestion:_
```cpp
3.5, 4.5
```

**Review by sherm1 — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18642)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ArjunBadyal)

**Comment by sherm1** [comment]
Merged -- thanks, @ArjunBadyal !

**Pull request merged**
