### PR TITLE
Add a LCM based jaco controller

### PR DESCRIPTION
**Pull request by sammy-tri**
Also adds a README.md with very brief descriptions of the various files in this directory.

A driver which is suitable for use with this controller lives in https://github.com/sammy-tri/drake-jaco-driver

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7388)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review
+(priority: low) 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-:-KxsaKfslyMZigjJct-W:bifjyec)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxsbfsdLmkgkaeVLorX:-KxsbfsdLmkgkaeVLorY:bhh7mn7) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L58)):*
> ```cpp
>       builder.AddSystem(systems::lcm::LcmSubscriberSystem::Make<robot_plan_t>(
>           kLcmPlanChannel, &lcm));
>   plan_sub->set_name("plan_sub");
> ```

FYI, i think we are planning to remove all instances of forcing system names. 

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-Kxt52H2qPXvF8SdpXhQ:-Kxt52H2qPXvF8SdpXhR:b-2xam8l) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L85)):*
> ```cpp
>           (num_joints + num_fingers) * 2, num_joints + num_fingers);
>   target_demux->set_name("target_demux");
> ```

can you put a short description of what's being controlled here? 
the pid loop is computing y = kp*(q_d - q) + kd * (v_d - v), and is added on top of v_d?? and shipped as the velocity command in the eventual command message. this seems a bit odd. but alright, you could have wrapped it into the kd number. 

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-Kxt4wLd2sBRHnl8j9wx:-Kxt4wLd2sBRHnl8j9wy:b-h4g63o) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L158)):*
> ```cpp
> 
>   // Specify a zero initial velocity.
>   VectorX<double> v0 = VectorX<double>::Zero(num_joints + num_fingers);
> ```

v0 or q0? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Comment by sammy-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 58 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxsbfsdLmkgkaeVLorX:-KxtdiICfvburxA-Yeog:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L58)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

FYI, i think we are planning to remove all instances of forcing system names. 
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 85 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-Kxt52H2qPXvF8SdpXhQ:-KxthrfKAJh7xcfjLoqg:beibxe2) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L85)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

can you put a short description of what's being controlled here? 
the pid loop is computing y = kp*(q_d - q) + kd * (v_d - v), and is added on top of v_d?? and shipped as the velocity command in the eventual command message. this seems a bit odd. but alright, you could have wrapped it into the kd number. 
</blockquote></details>

Reflowed the order that the components of the diagram are created in and added inline comments explaining what's going on.  Hopefully this is clearer.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 158 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-Kxt4wLd2sBRHnl8j9wx:-KxtdbUNZoslyEKA9KPA:b-3f3z5z) ([raw file](https://github.com/robotlocomotion/drake/blob/4dfa8791c8b9a73bce42d766de8010806344ae39/drake/examples/kinova_jaco_arm/jaco_controller.cc#L158)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

v0 or q0? 
</blockquote></details>

Done.  (facepalm)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxuTVGoE1J9fjykwVg_:-KxuTVGoE1J9fjykwVga:br94nk5) ([raw file](https://github.com/robotlocomotion/drake/blob/c02f07347afb2d8767c7730d1b2581d7bca4193e/drake/examples/kinova_jaco_arm/jaco_controller.cc#L88)):*
> ```cpp
>   // construct.  We create a pid controller which calculates
>   //
>   // y = kp*(q_d - q) + kd * (v_d - v)
> ```

BTW might want to space the first *. Also might be worthwhile saying _d is desired. 

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxuUpuLzgzaf9aM_B0z:-KxuUpuLzgzaf9aM_B1-:beefj3t) ([raw file](https://github.com/robotlocomotion/drake/blob/c02f07347afb2d8767c7730d1b2581d7bca4193e/drake/examples/kinova_jaco_arm/jaco_controller.cc#L164)):*
> ```cpp
>                first_status.num_fingers == num_fingers);
> 
>   // Specify a zero initial velocity.
> ```

BTW I am not quite sure what this comment is about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-:-KxuV8S3YyrqzCLqEUtr:bnfp4nl)*

**Comment by sammy-tri** [comment]
+@soonho-tri for feature review per rotation

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 88 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxuTVGoE1J9fjykwVg_:-KxxDNBBtfstxD2P9I9s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c02f07347afb2d8767c7730d1b2581d7bca4193e/drake/examples/kinova_jaco_arm/jaco_controller.cc#L88)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW might want to space the first *. Also might be worthwhile saying _d is desired. 
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 164 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxuUpuLzgzaf9aM_B0z:-KxxDR2sng_13xWbtnn0:b-76yf7j) ([raw file](https://github.com/robotlocomotion/drake/blob/c02f07347afb2d8767c7730d1b2581d7bca4193e/drake/examples/kinova_jaco_arm/jaco_controller.cc#L164)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW I am not quite sure what this comment is about.
</blockquote></details>

cut and paste error?  search and replace error?  removed at any rate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-:-KxxDkunBZFEbRU-P5IA:b-920y3i)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Comment by sammy-tri** [comment]
(that should have said platform review)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-:-KxxImJy9DblnvY9bw4V:b-sjq8h2)*

**Comment by sammy-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kinova_jaco_arm/jaco_controller.cc, line 68 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxxMgMok3OnRp2sFODC:-KxxSmUtBB-16nMFclo-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/250926f11007d7cd37d52899cc463da06e3cf85f/drake/examples/kinova_jaco_arm/jaco_controller.cc#L68)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, need `#include "drake/common/drake_assert.h"` for this.
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/README.md, line 21 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxxJwreeN16zoMZRMtp:-KxxT25hb3PAVaaSX6KS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/250926f11007d7cd37d52899cc463da06e3cf85f/drake/examples/kinova_jaco_arm/README.md#L21)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

It might be obvious, but it'd be kind to ask users to run `bazel build drake/examples/kinova_jaco_arm/...` (otherwise those examples are not present).
</blockquote></details>

Done.

---

*[drake/examples/kinova_jaco_arm/README.md, line 57 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7388#-KxxKVHot_sudSR2KNQQ:-KxxT45Ae8T5x37F4ZI_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/250926f11007d7cd37d52899cc463da06e3cf85f/drake/examples/kinova_jaco_arm/README.md#L57)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, need a newline at the end?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7388)*

**Pull request merged**
