### PR TITLE
Document that gfortran is required, for both Clang and GCC.

### PR DESCRIPTION
**Pull request by david-german-tri**
gfortran is already present on CI images.

@siyuanfeng-tri for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5003)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5003#-:-KbqbuGYWRcVVamku8KQ:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5003#-:-KbqbwRClz3uGDRWdcTZ:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5003)*

**Comment by david-german-tri** [comment]
override-merging; docs only, and too minor to merit separate platform review

**Pull request merged**
