### PR TITLE
Support (opt-in) derivatives in FunctionHandleTrajectory.

### LINKED ISSUE #22076: Provide Derivatives in FunctionHandleTrajectory
#21093 introduced a way for the user to specify trajectories as the image of an arbitrary function, completing the feature request in #20699. However, it does not yet support computing derivatives of the trajectory, which is needed for trajectory processing algorithms like Toppra. I think this should be pretty straightforward to implement, so I'll self-assign (and ask for help if I get stuck).

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #22076.

+@cohnt for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22262)

### CODE REVIEW

**Review by cohnt — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22262)* status: 5 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/function_handle_trajectory.h` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHa7XTADT09GX-uOEI:-ODHa7XTADT09GX-uOEJ:bxrainu) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.h#L44)):*
> ```objc
>   ~FunctionHandleTrajectory() final;
> 
>   /** Sets a callback function that returns the derivative of the function.
> ```

Should we be throwing if the derivative function throws something of the wrong shape? If a downstream user passes in a poorly-defined function, the shape problems will cause segfaults that could be very hard to diagnose. If speed is a concern, maybe at least a `DRAKE_ASSERT` so a debug build would catch it?

If we don't do this sort of checking, I do think we should document that the output shape should match the shape of value.
___
*[`common/trajectories/function_handle_trajectory.h` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHagzD4DoHh3sTr61y:-ODHagzE11g2I0L-yKDh:b-7p46ee) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.h#L45)):*
> ```objc
> 
>   /** Sets a callback function that returns the derivative of the function.
>   `func(t,order)` will only be called with `order > 0`. */
> ```

btw Can we drop a hint that the user should feel free to only implement some of the derivatives, and throw an error otherwise?
___
*[`common/trajectories/function_handle_trajectory.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHcOAX9mEbe8RqKWb9:-ODHcOAX9mEbe8RqKWbA:bd10n8w) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L69)):*
> ```cpp
> MatrixX<T> FunctionHandleTrajectory<T>::DoEvalDerivative(
>     const T& t, int derivative_order) const {
>   if (derivative_order == 0) {
> ```

btw Do we need to document that `EvalDerivative` will not throw if `derivative_order == 0` and `derivative_fun_ == nullptr`? Or swap the order of this statement and the null check? `This seems like a weird edge case.
___
*[`common/trajectories/function_handle_trajectory.cc` line 79 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHd5YADPkBWNAAbsmV:-ODHd5YADPkBWNAAbsmW:becib6n) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L79)):*
> ```cpp
> std::unique_ptr<Trajectory<T>> FunctionHandleTrajectory<T>::DoMakeDerivative(
>     int derivative_order) const {
>   if (derivative_order == 0) {
> ```

btw Same question as above.
___
*[`common/trajectories/function_handle_trajectory.cc` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHdB8hEsaB8u4hY7fI:-ODHdB8hEsaB8u4hY7fJ:b-t27791) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L82)):*
> ```cpp
>     return Clone();
>   }
>   DRAKE_THROW_UNLESS(derivative_func_ != nullptr);
> ```

btw Do you think it makes sense to query `EvalDerivative` at least once to make sure that order is supported? Or is the error not occurring until we try to use such a trajectory okay?

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22262)* status: 4 unresolved discussions, LGTM missing from assignee cohnt, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`common/trajectories/function_handle_trajectory.h` line 44 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHa7XTADT09GX-uOEI:-ODk8JkxA9u0aCFGYTlM:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.h#L44)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

Should we be throwing if the derivative function throws something of the wrong shape? If a downstream user passes in a poorly-defined function, the shape problems will cause segfaults that could be very hard to diagnose. If speed is a concern, maybe at least a `DRAKE_ASSERT` so a debug build would catch it?

If we don't do this sort of checking, I do think we should document that the output shape should match the shape of value.
</blockquote></details>

Done. Good call.
___
*[`common/trajectories/function_handle_trajectory.h` line 45 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHagzD4DoHh3sTr61y:-ODk8JHD12eg-LB0Dr5O:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.h#L45)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

btw Can we drop a hint that the user should feel free to only implement some of the derivatives, and throw an error otherwise?
</blockquote></details>

Done.
___
*[`common/trajectories/function_handle_trajectory.cc` line 69 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHcOAX9mEbe8RqKWb9:-ODk9PcTBbWAfgMn_Dnx:bobmr8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L69)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

btw Do we need to document that `EvalDerivative` will not throw if `derivative_order == 0` and `derivative_fun_ == nullptr`? Or swap the order of this statement and the null check? `This seems like a weird edge case.
</blockquote></details>

It's a fair question. I agree that it might be conceptually simpler to throw if derivative_func_ is not set, but it's more correct to allow the zero-order derivatives (it strikes me as wrong to use DRAKE_THROW_UNLESS and then not rely on that condition in one of the following code paths).

I've added documentation in the header, but it's a private overload, so won't actually appear in any documentation.
___
*[`common/trajectories/function_handle_trajectory.cc` line 79 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHd5YADPkBWNAAbsmV:-ODk9oFoDd5m3IjoUZsy:b4tal4i) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L79)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

btw Same question as above.
</blockquote></details>

Same answer as above.
___
*[`common/trajectories/function_handle_trajectory.cc` line 82 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODHdB8hEsaB8u4hY7fI:-ODkA0dxCGceziAcC1Cn:b-exoait) ([raw file](https://github.com/RobotLocomotion/drake/blob/d78e83a0b4ed284e692b7b084e3e70e3dce3fcea/common/trajectories/function_handle_trajectory.cc#L82)):*
<details><summary><i>Previously, cohnt (Thomas Cohn) wrote…</i></summary><blockquote>

btw Do you think it makes sense to query `EvalDerivative` at least once to make sure that order is supported? Or is the error not occurring until we try to use such a trajectory okay?
</blockquote></details>

this actually happens already in the DerivativeTrajectory constructor.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22262)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),cohnt

___
*[`common/trajectories/function_handle_trajectory.h` line 23 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODlk8R16LVguy18s9dM:-ODrvYUGD4ga27SWGVEa:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/c79673cd2a4b2ef5263ff3531871442effdeb57d/common/trajectories/function_handle_trajectory.h#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Since `set_derivative` is meant to be called near ctor-time, it would be good to document the situation here.
</blockquote></details>

Done.
___
*[`common/trajectories/function_handle_trajectory.cc` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22262#-ODliusi1J2rMN-0PQOR:-ODrvh5-31JqYe9wFU8k:b-sdyrvn) ([raw file](https://github.com/RobotLocomotion/drake/blob/c79673cd2a4b2ef5263ff3531871442effdeb57d/common/trajectories/function_handle_trajectory.cc#L45)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW:   I believe this conditional does nothing, as set_derivative from empty to empty is valid and vacuous.
</blockquote></details>

Done.  (I know; I thought it was a little clearer/cleaner the other way, but I've gone with your version).

**Review by cohnt — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22262)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),cohnt

**Pull request merged**
