### PR TITLE
Move controlled_spring_mass_system to test_utilities

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
One more cleanup, related to #7402.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7411)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@naveenoid for feature review, please.  `git` seems to assign you as related to placing the file into its current home.   Also /CC @edrumwri for any objections/

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7411#-:-KyN7Gb1L8JzN2YuQTTW:bnfp4nl)*

**Comment by naveenoid** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7411)*

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-tri for platform review per schedule, please.

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7411#-:-KyRVtJB4en7lCyIMeMX:bmxilld)*

**Pull request merged**
