### PR TITLE
Update swigmake SHA to allow mex_setup to be removed

### PR DESCRIPTION
**Pull request by jamiesnape**
See rdeits/swigmake#2.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3632)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@rdeits for feature review.

**Comment by rdeits** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3632#-:-KSro_xa6BC7R5Rj4qX6:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3632#-:-KSrym0gzUblVY8JROj3:bnfp4nl)*

**Pull request merged**
