### PR TITLE
[tools] Disable binary-only solvers in sanitizer builds

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
We cannot reasonably use binary-only GUROBI and MOSEK libraries in sanitizer builds, since they lack the sanitizer instrumentation. Sanitizers rely on building everything from source with their hooks.

Also drop them from Valgrind checks since they use complicated threading allocation tricks without any good debug instrumentation, which leads to frequent false positives that require effort to suppress; and anyway if there are leaks, there is nothing we can do to solve the problems anyway.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22149)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22149#-:-OBQvPgd04bWX6Dj8O8S:bnfp4nl)* status: 1 unresolved discussion, needs at least two assigned reviewers

___
*[`tools/dynamic_analysis/bazel.rc` line 302 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22149#-OBQvAI3BL5o_mfP6Yj-:-OBQvAI3BL5o_mfP6Yj0:b-wu2j54) ([raw file](https://github.com/RobotLocomotion/drake/blob/707469024a50d1a27b64b713356fbb620aab4492/tools/dynamic_analysis/bazel.rc#L302)):*
> ```
> 
> build:drd --config=_drd
> build:drd --test_tag_filters=-lint,-gurobi,-mosek,-snopt,-no_drd,-no_valgrind_tools
> ```

nit Is this change just arbitrary? If so, ok, I guess. I just want to make sure I'm not missing some hidden meaning.

**Review by jwnimmer-tri — COMMENTED** [review]
+@sammy-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22149#-:-OBQygSm4XzKhCzkdyAJ:b-1krawd)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`tools/dynamic_analysis/bazel.rc` line 302 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22149#-OBQvAI3BL5o_mfP6Yj-:-OBQyb0F5iAGfHPCoVjs:b470amw) ([raw file](https://github.com/RobotLocomotion/drake/blob/707469024a50d1a27b64b713356fbb620aab4492/tools/dynamic_analysis/bazel.rc#L302)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Is this change just arbitrary? If so, ok, I guess. I just want to make sure I'm not missing some hidden meaning.
</blockquote></details>

Right.  It's a non-functional change, merely for improved consistency within this file.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22149#-:-OBSFUxM-tTXOly0xisi:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform)

**Pull request merged**
