### PR TITLE
Refactor symbolic classes

### PR DESCRIPTION
**Pull request by soonho-tri**
- Make ctors/assign ops of FormulaCell protected
 - Add virtual destructor to ExpressionCell and FormulaCell

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5352)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri platform :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula_cell.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-Ke6dGioMMyzo7uQnle7:-Ke6dGioMMyzo7uQnle8:b-1yv8rn) ([raw file](https://github.com/robotlocomotion/drake/blob/69868acfd4d915dad8523c68e48fa9340abcc0a2/drake/common/symbolic_formula_cell.h#L51)):*
> ```objc
>   /** Default constructor (deleted). */
>   FormulaCell() = delete;
>   /** Move-construct a set from an rvalue. */
> ```

BTW _Meta_ "a set" seems wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-:-Ke6dU8AUG0Jr9bRyw6x:b-sq8mxm)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/symbolic_formula_cell.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-Ke6e45lpfezq3TiZ_aj:-Ke6e45mKDmLcfgGEHfn:bksmusk) ([raw file](https://github.com/robotlocomotion/drake/blob/69868acfd4d915dad8523c68e48fa9340abcc0a2/drake/common/symbolic_formula_cell.h#L57)):*
> ```objc
>   /** Move-assign (DELETED). */
>   FormulaCell& operator=(FormulaCell&& f) = delete;
>   /** Copy-assign (DELETED). */
> ```

From slack discussion, we will use `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(FormulaCell)` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula_cell.h, line 57 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-Ke6e45lpfezq3TiZ_aj:-Ke6fUb3kBMAldfG39iz:b1qr271) ([raw file](https://github.com/robotlocomotion/drake/blob/69868acfd4d915dad8523c68e48fa9340abcc0a2/drake/common/symbolic_formula_cell.h#L57)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

From slack discussion, we will use `DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(FormulaCell)` instead.
</blockquote></details>

Ah, it is not deleted. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-:-Ke6fZxusoA5uABts38Z:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_formula_cell.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5352#-Ke6dGioMMyzo7uQnle7:-Ke6gT78K9cxKWysrKcl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69868acfd4d915dad8523c68e48fa9340abcc0a2/drake/common/symbolic_formula_cell.h#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW _Meta_ "a set" seems wrong?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5352)*

**Pull request merged**
