### PR TITLE
Declarative matlab tests

### LINKED ISSUE #1846: convert known issue logic from matlab
to e.g. python?
see #1845

### PR DESCRIPTION
**Pull request by RussTedrake**
matlab unit tests used to be found programmatically at test time by crawling the directories and looking for all methods that could be run without any arguments (static class methods and standalone functions).  now all tests must be declared explicitly in a CMakeLists.txt .  This is a more standard workflow, and is easier for integrating with Jenkins.

One important thing to notice in the code review -- I now use glob to recurse into the subdirectories in drake/examples/CMakeLists.txt -- and realize I should have been doing that before to support externals installed directly as examples and developers using that workflow.  Might want to revisit this in #1939.  

my old build servers also allowed some tests to fail under known conditions with some "known issue logic" which connected to the comment field on github via the github api.  This was also non-standard and hard to integrate with the build servers.  i've gone through and moved all of that logic into cmake (by commenting out tests and adding links to github).  many of the known issues only happened with small probability, which was resolved for the build servers by making all matlab tests run with the known random seed -- in those cases I've simply added a textual comment with a link to the issue to the matlab source file.  Also resolved a few of the old bugs.   Resolves #1846  .

For completeness, here is the list of known issue logic clauses that had been evaluated from the github api:
```
#1848: strcmp(test_name,'examples/PR2/runSaggitalPassive') && strcmp(error_id,'MATLAB:load:notBinaryFile')
#1761: strcmp(error_id,'timeout') && strcmp(test_name,'examples/Quadrotor/runDircolWObs')
#1637: (strcmp(test_name,'examples/Pendulum/runTrajectorySwingUpAndBalance') || strcmp(test_name,'examples/UnderwaterAcrobot/runSwingUp') || strcmp(test_name,'examples/CartPole/runLQR'))&& strcmp(error_id,'timeout')
#1515: (strcmp(test_name,'examples/Acrobot/runLQR') || strcmp(test_name,'examples/Acrobot/runTrigLQR')) && strcmp(error_id,'timeout')
#1460: strcmp(test_name,'systems/plants/test/testIK') && strcmp(error_id,'timeout')
#1417: strcmp(error_id,'timeout') && ~isempty(strfind(test_name,'Atlas'))
#1271: is_segfault && ~isempty(strfind(test_output,'drake005'))
#1244: ispc() && (strcmp(test_name,'testConvexHull') || strcmp(test_name,'testIK') || strcmp(test_name,'testIKtraj') || strcmp(test_name,'testIKpointwise'))
#1158: strcmp(test_name,'util/test/testQuat2expmapSequence') && strcmp(error_id,'Drake:ValueCheck')
#1102: strcmp(error_id,'MATLAB:remoteparfor:AllParforWorkersAborted')
#855: strcmp(test_name,'systems/robotInterfaces/test/testFootstepSolvers') && ~isempty(strfind(error_message,'Out of range'))
#854: strcmp(test_name,'examples/Atlas/runDRCDoorTask') && ~isempty(strfind(error_message,'Out of range'))
#827: strcmp(test_name,'solvers/test/testMixedIntegerConvexDemo') && strcmp(error_id,'Drake:ValueCheck')
#723: strcmp(test_name,'examples/Atlas/runDRCPracticeTerrain') && ~isempty(strfind(error_message,'Out of range'))
#633: strcmp(error_message,'Solution file not found. Bertini error?') && ~isempty(strfind(test_output,'drake007'))
#583: strcmp(test_name,'examples/Glider/test/verifyURDF') && ~isempty(strfind(error_message,'Values don''t match'))
#569: (~isempty(strfind(test_output,'lcppath.mexw64')) || ~isempty(strfind(test_output,'lcppath.mexw32'))) && ~isempty(strfind(test_output,'Invalid MEX-file'))
#516: strcmp(test_name,'systems/plants/constraint/test/testKinCnst') && ~isempty(strfind(test_output,'dc_mex')) && ~isempty(strfind(test_output,'AllBodiesClosest'))
#494: strcmp(test_name,'examples/Acrobot/runLQR') && strcmp(error_id,'Simulink:Engine:SolverConsecutiveZCNum')
#485: strcmp(test_name,'util/test/baryTest') && ~isempty(strfind(error_message,'NANs'))
#471: strncmp(test_name,'examples/SimpleFourBar',22) && ~isempty(strfind(error_message,'onstraints'))
#468: strcmp(error_id,'MATLAB:nonLogicalConditional') && strcmp(test_name,'systems/plants/test/timeSteppingRigidBodyManipulatorFramesTest')
#466: strcmp(test_name,'examples/SimpleFourBar/runLQR') && ~isempty(strfind(error_message,'nested gevals'))
#374: ~isempty(strfind(error_message,'bug 1728'))
#366: strcmp(test_name,'systems/test/linear_gaussian_dt') && strcmp(error_id,'Drake:ValueCheck')
#365: ~isempty(strfind(test_output,'infeasible mss program')) && ~isempty(strfind(test_output,'optimizeRho'))
#313: strcmp(error_id,'Simulink:Engine:SolverConsecutiveZCNum') && strcmp(test_name,'examples/PlanarNLink/runLQR')
#311: strcmp(error_id,'Drake:ValueCheck') && strcmp(test_name,'systems/plants/test/testFloatingBaseDynamics')
#310: strcmp(error_id,'Simulink:SFunctions:SFcnErrorStatus') && (strcmp(test_name,'examples/Pendulum/test/testLCMPlant') || strcmp(test_name,'systems/test/runPendulum')) && ~isempty(strfind(test_output,'real time'))
```

sorry for the huge PR.  this one sort of had to go all or nothing.

### CODE REVIEW

**Comment by jamiesnape** [comment]
Rather than define your own macros, you should use this file:

https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake

You can import that file directly into the this repo and set the cmake module path so that you do not have to upgrade everyone to the latest version of CMake immediately.

It looks like this still this code still calls perl, so it will still be an issue for CI.

You can fix the above now or create tickets to do so later.

**Comment by jamiesnape** [comment]
If possible, can you also add a comment in each CMakeLists.txt next to tests with issues? Just say something like `UNSTABLE, see #NNN`.

**Comment by jamiesnape** [comment]
Other than the above comments, LGTM.

**Comment by billhoffman** [comment]
@RussTedrake I was looking at https://github.com/RobotLocomotion/cmake/blob/master/matlab_clean.pl to see if we could avoid the perl call:  http://www.mail-archive.com/cmake@cmake.org/msg02175.html.  I think we could do this with a cmake script instead, using execute_process.  It has the ability to redirect to a file and capture output and clean it.  It would avoid needing perl to run matlab.

**Comment by jwnimmer-tri** [comment]
> ... the perl call ... we could do this with a cmake script instead ...

Broadly speaking, I'd recommend writing test-facilitating tools in python.  It is universally well-known and well-supported on all platforms, and is a better first-class programming language that CMake.

CMake can get by as a build system wrapper -- to inventory what to build, the dependencies, and the list of shell commands to build it.  Actual test logic should not live in CMake.

**Comment by billhoffman** [comment]
Not actually test logic, just logic to clean the output of a matlab test.   My goal is to reduce external dependencies.  Right now python is not a hard depend.  This is not complicated code, it is just a filter of the output of matlab tests.  Basically sed, cmake can do that well enough and cleanly across platforms and not bring in another required depend.

**Comment by jwnimmer-tri** [comment]
I guess I will stop polluting this PR, and wait for #1939 to argue my case against being scared of dependencies.

**Comment by billhoffman** [comment]
Fair enough, I would like to not use perl for this if possible since it is causing trouble on the Windows CI machine.  I would also at least for now not require python either.  This should be a pretty simple bit of CMake code, and I am willing to implement it.

**Comment by RussTedrake** [comment]
Re: defining my own macros.  I have not defined anything that could have used FindMatlab here.  I'm just using the existing MATLAB_FOUND logic.  Happy to address that, but it would be a separate PR.

Re: perl.  the existing make test all uses perl.  I would be thrilled to remove it.   if it's a few lines in cmake that would be great; if it's more then I agree python is better.  the question, again, is whether we need to couple that update with this PR.  can jenkins run the matlab tests with this version?

If jenkins can run the matlab tests like this, then I propose we agree on the changes here as the first pass, then clean up the two issues above immediately after?

**Comment by jamiesnape** [comment]
Is `matlab_add_unit_test` not sufficient?

https://github.com/Kitware/CMake/blob/master/Modules/FindMatlab.cmake#L754

We should fix it, if that is the case.

**Comment by jamiesnape** [comment]
> You can fix the above now or create tickets to do so later.

Post the issue numbers and LGTM.

**Comment by RussTedrake** [comment]
awesome.  did not know about that.

perhaps it will be, but not until we get the missing dependency logic out of matlab and into cmake.  that is going to take some work.  i would propose taking my version right now — it’s most similar to what the build servers have been doing reliably — and then adding an issue to switch to that?

**Comment by jamiesnape** [comment]
Sure. I am happy for you to merge now.

**Comment by RussTedrake** [comment]
posted #1997 and #1998.

**Comment by RussTedrake** [comment]
it seems that the "update branch" button in this github console is not to be trusted.  but the merge can still go through.

**Comment by billhoffman** [comment]
The perl script as it is will fail on our Windows build machine:

if ($osname eq "cygwin" || $osname eq "MSWin32") {
  $tmpfile = "c:\\tmp\\" . time() . "_" . int(rand(100000));
  $cmd .= " -nosplash -nodesktop -logfile \"$tmpfile\"";
} else {
  $tmpfile = "/tmp/" . time() . "_" . int(rand(100000));
  $cmd .= " -nosplash -nodisplay -logfile \"$tmpfile\"";
}
The osname will not be cygwin, so it will use /tmp and matlab will not know what /tmp is and it will not work.

**Comment by jamiesnape** [comment]
retest this please

**Comment by jamiesnape** [comment]
Failed due to license issues.

**Comment by jamiesnape** [comment]
retest this please

**Comment by RussTedrake** [comment]
@jamiesnape , @billhoffman -- should we accept this as is, to enable linux matlab tests at least?  or resolve the perl issue first?

**Comment by billhoffman** [comment]
Let's accept it as it is.  I sent you an email with my version of a cmake replacement for perl.  We should get this in first.  It moves us in the right direction.  I can base my cmake perl script replacement off of this work once it is merged.

**Pull request merged**
