### PR TITLE
[multibody] Add ability to set PD gains to zero

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21786)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri and/or +@joemasterjohn could you please check that I'm on the right track here, in terms of a design?

**Review by amcastro-tri — COMMENTED** [review]
I like how you bundled three checks into `IsPdControllerActive()`, it makes the rest of the code much easier to read. 
:lgtm: on the design, pending unit testing.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21786#-:-O3hPhiwAWjHXmk8G3kn:b-9jtqz0)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned

**Comment by jwnimmer-tri** [comment]
Thanks!  I'm still chasing down exactly how to use this in a simulator.  I might need to take an even bigger swing here (adjusting how the desired state input ports work).  I'll post back more details once I've convinced myself.

**Comment by jwnimmer-tri** [comment]
Yeah.  This was a good sanity check that I'm on the right track, but for the moment I'll pause for a week or three so that I can do some more end-to-end testing with sample use cases.

**Comment by jwnimmer-tri** [comment]
As of recent PRs up through #22715, a better solution has been found and merged.

**Pull request closed without merging**
