### PR TITLE
[planning] Bump up gcs_trajectory_optimization_test shard count

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21490)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-everything-address-sanitizer please

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21490)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21490#-Nz9MUYp8CtP89IbmWqJ:-Nz9MUYq6vS5knj1sxuR:b-jce82t) (no related file):*
In the failed nightly CI (`linux-jammy-gcc-bazel-nightly-coverage`), the 8 shards were given 600s before timing out.

In this PR's additional CI (`linux-jammy-clang-bazel-experimental-everything-address-sanitizer`), we had shard 3 time out in 150s. Do we have varying definitions of test size based on configuration? (I.e., does asan get a larger timeout window than coverage?)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21490#-Nz9N02f4qaqedyzkaPO:-Nz9N02f4qaqedyzkaPP:b-k3iqrv) (no related file):*
In this PR's [failed CI](https://drake-cdash.csail.mit.edu/test/1475774924), one shard timed out. The shard included three tests. Two of them took a combined total of 2 ms, the third test (`SimpleEnv2D.GlobalContinuityConstraints`) took the remainder 150s.

(1) Can we simplify the test so it provides equivalent test coverage in a simpler package? @wrangelvid? I know that test is documented as what was presented in the GCS paper. How important is it that CI provides regression against the paper? Would a simpler scenario not accomplish the same thing, from a code correctness perspective?
(2) The log reported the "Set parameter ServerPassword" *dozens* of times. I have no idea of knowing if that's normal or how much time that burned (the timestamps in the log *appear* to be related to when the test's accumulated messages were *written* en masse, and not when the individual messages were dispatched). That said, could the parameter setting contribute to overall run time?
    - A side note, after the sequence of "Serverpassword" and "TokenServer" parameter setting, the log does report that it "Solved GCS shortest path using Mosek...". So, clearly the mosek parameter games didn't interfere with a solution. Does that message indicate that the test was close to passing? Or was that just a preliminary ste?

___

**Comment by jwnimmer-tri** [comment]
Note that the ASan build is stale (pre-hotfix).  Since coverage passed, we should just merge this.

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @SeanCurtis-TRI from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21490)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21490#-Nz9MUYp8CtP89IbmWqJ:-NzFqsRR7oHizmCP2me4:b-5ky3t2) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the failed nightly CI (`linux-jammy-gcc-bazel-nightly-coverage`), the 8 shards were given 600s before timing out.

In this PR's additional CI (`linux-jammy-clang-bazel-experimental-everything-address-sanitizer`), we had shard 3 time out in 150s. Do we have varying definitions of test size based on configuration? (I.e., does asan get a larger timeout window than coverage?)
</blockquote></details>

The ASan timing is not relevant.  It's from days ago.  The purpose of this PR is Coverage.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21490#-Nz9N02f4qaqedyzkaPO:-NzFqyZ23DHNuYtYDwbH:b-sktg2x) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In this PR's [failed CI](https://drake-cdash.csail.mit.edu/test/1475774924), one shard timed out. The shard included three tests. Two of them took a combined total of 2 ms, the third test (`SimpleEnv2D.GlobalContinuityConstraints`) took the remainder 150s.

(1) Can we simplify the test so it provides equivalent test coverage in a simpler package? @wrangelvid? I know that test is documented as what was presented in the GCS paper. How important is it that CI provides regression against the paper? Would a simpler scenario not accomplish the same thing, from a code correctness perspective?
(2) The log reported the "Set parameter ServerPassword" *dozens* of times. I have no idea of knowing if that's normal or how much time that burned (the timestamps in the log *appear* to be related to when the test's accumulated messages were *written* en masse, and not when the individual messages were dispatched). That said, could the parameter setting contribute to overall run time?
    - A side note, after the sequence of "Serverpassword" and "TokenServer" parameter setting, the log does report that it "Solved GCS shortest path using Mosek...". So, clearly the mosek parameter games didn't interfere with a solution. Does that message indicate that the test was close to passing? Or was that just a preliminary ste?
</blockquote></details>

ASan is not relevant.  It's from days ago.

___

**Comment by jwnimmer-tri** [comment]
:lgtm: bash on regardless.

**Pull request merged**
