### PR TITLE
Add HPolyhedron::FindRedundant

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432#-:-NIyh_pE38NhPo44gD8H:b4xbtza)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/hpolyhedron.h` line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ1Z0G60XAFLK3rcS5T:-NJ1Z0G60XAFLK3rcS5U:b28n6ul) ([raw file](https://github.com/robotlocomotion/drake/blob/d093846616ae1f0c8093aa929b1a07f27a95e5d9/geometry/optimization/hpolyhedron.h#L82)):*
> ```objc
>                                          double tol = 1E-9) const;
> 
>   /** Finds the redundant faces in this polyhedron.
> ```

I would say inequality instead of faces as face has a very specific meaning in convex geometry.
___
*[`geometry/optimization/test/hpolyhedron_test.cc` line 593 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ1Zg0t7QoZcO76inJM:-NJ1Zg0t7QoZcO76inJN:b8s2dye) ([raw file](https://github.com/robotlocomotion/drake/blob/d093846616ae1f0c8093aa929b1a07f27a95e5d9/geometry/optimization/test/hpolyhedron_test.cc#L593)):*
> ```cpp
>   HPolyhedron polyhedron_to_reduce(A_int, b_int);
>   const auto redundant_indices = polyhedron_to_reduce.FindRedundant();
>   // Removed Linfity_ball.
> ```

nit typo: `Linfty_ball`

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:  minus a few notes about the comments.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432#-:-NJ1ZqcM27WvHBaIYAig:b-1ycqvj)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hpolyhedron.h` line 82 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ1Z0G60XAFLK3rcS5T:-NJ1ffNn81au44OGNhIt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d093846616ae1f0c8093aa929b1a07f27a95e5d9/geometry/optimization/hpolyhedron.h#L82)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I would say inequality instead of faces as face has a very specific meaning in convex geometry.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
+@seancurtis-tri for Monday's platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432#-:-NJ1g3xh7phtejFrZu5P:bhcma3h)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @AlexandreAmice and @SeanCurtis-TRI)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai and @SeanCurtis-TRI)

___
*[`geometry/optimization/hpolyhedron.h` line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ5g5Ht5ZuyXrA69L2E:-NJ5g5Ht5ZuyXrA69L2F:bxpr60) ([raw file](https://github.com/robotlocomotion/drake/blob/b129e07c8dc010192a70acbc6c53f5eac3905d11/geometry/optimization/hpolyhedron.h#L82)):*
> ```objc
>                                          double tol = 1E-9) const;
> 
>   /** Finds the redundant inequliaites in this polyhedron.
> ```

Inequalities is misspelled here

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[`geometry/optimization/hpolyhedron.h` line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ5g5Ht5ZuyXrA69L2E:-NJ6Sgc158VIyb_rxc1Q:bw10jn4) ([raw file](https://github.com/robotlocomotion/drake/blob/b129e07c8dc010192a70acbc6c53f5eac3905d11/geometry/optimization/hpolyhedron.h#L82)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Inequalities is misspelled here
</blockquote></details>

Oops, done.
___
*[`geometry/optimization/hpolyhedron.h` line 85 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ5s3Or6vocqElQmI98:-NJ6SoFFEqNidigHvOzk:b-cvgar6) ([raw file](https://github.com/robotlocomotion/drake/blob/b129e07c8dc010192a70acbc6c53f5eac3905d11/geometry/optimization/hpolyhedron.h#L85)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Perhaps I'm missing something, but I believe this respelling is missing a "for all", i.e., `{x | A.row(i)*x <= b(i), ∀i ∉ ℑ}` (with an implicit understanding that `i` *is* a valid row index in A. Or is the "forall" commonly assumed in this context?
</blockquote></details>

Done, I added ∀
___
*[`geometry/optimization/hpolyhedron.h` line 86 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ5tLMe8g4gdk4uyY46:-NJ6SydT1-iMkN3-vXcX:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/b129e07c8dc010192a70acbc6c53f5eac3905d11/geometry/optimization/hpolyhedron.h#L86)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW an alternative to the atypical "j'th" would be: jᵗʰ.
</blockquote></details>

Done.
___
*[`bindings/pydrake/test/geometry_optimization_test.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18432#-NJ5vp8I5E4y9wyPrvdY:-NJ6TDYC-Ln3n5oSu8-S:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/b129e07c8dc010192a70acbc6c53f5eac3905d11/bindings/pydrake/test/geometry_optimization_test.py#L140)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Something to think about. This isn't standard practice, but this is something I've come to of late and leave it up to your aesthetic to decide if you want to include it. (Obviously, I give a strong vote in favor.)

This tests confirms the keyword arguments are correctly named. The binding code *also* is responsible for defining a default value for tolerance. This unit test should confirm that `tol` has a default value by invoking `FindRedundant` without specifying `tol`. That *is* an expected property of the *binding* and, therefore, is worthy of a test.
</blockquote></details>

Done. Good call.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: 2 unresolved discussions (waiting on @AlexandreAmice)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Dismissed @AlexandreAmice from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),AlexandreAmice (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18432)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),AlexandreAmice

**Pull request merged**
