### PR TITLE
Acrobot w offsets

### PR DESCRIPTION
**Pull request by RussTedrake**
The most substantial example I've done yet, which includes linearizing through a diagram (woohoo!) and some pretty complex wiring.  

Note: this PR contains the kalman filter PR.  I will curate the commits as soon as the Kalman PR lands.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4365)

### CODE REVIEW

**Comment by RussTedrake** [comment]
cleaned up my commits.  +@hongkai-dai for feature review.  +@sherm1 for platform review, please.

**Comment by hongkai-dai** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/diagram.h, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYG2ElkthZNZOoJi7Xp:-KYG2ElkthZNZOoJi7Xq:bnk7w89) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L164)):*
> ```objc
>   }
> 
>   /// Returns a pointer to the subsystem, referenced by name.
> ```

Could you add a comment on the lifespan of this pointer?

---

*[drake/systems/framework/diagram.h, line 780 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYG2RH-CpGuDq-qVXA7:-KYG2RH-CpGuDq-qVXA8:b73etim) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L780)):*
> ```objc
>   }
> 
>   // Returns the index of the given @p sys in the sorted order of this diagram,
> ```

Returns the FIRST index?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by sherm1** [comment]
Punting on platform review due to Monday burnout, sorry: -@sherm1 +@david-german-tri.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-:-KYHrNHQ-a20LTloKKuq:bib876y)*

**Comment by david-german-tri** [comment]
I'm glad this one got punted to me.  Here are a couple of design comments.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJekOB6YvRHYHJE0Bs:-KYJekOB746jRXlvXVPb:b-874239) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L43)):*
> ```cpp
>   auto acrobot_w_encoder = builder.AddSystem(AcrobotWEncoder<double>(true));
> 
>   // Get a pointer to the actual plant subsystem (will be used below).
> ```

Perhaps I fail at parsing (the word "acrobot" appears a lot) but I don't see where this is used.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYJfRgwB_8581ADY5WS:b-qup9aa) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
> ```cpp
>   auto observer_context = observer_acrobot->CreateDefaultContext();
>   {  // Set context to upright fixed point.
>     auto x0 = dynamic_cast<AcrobotStateVector<double>*>(
> ```

Rooting around in the context like this would also be better delegated to a public (static?) method on `AcrobotWEncoder : public Diagram<T>`

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYJcm3ED4e6AkmYQ8x_:bu2jtey) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
> ```objc
> 
>   /// Returns a pointer to the subsystem, referenced by name.
>   const systems::System<T>* GetSubsystem(const std::string& name) const {
> ```

From Slack(system2): I don't think we should add this function.  The conventional approach elsewhere is to make `AcrobotWEncoder : public Diagram<T>`, and add named accessors for subsystems you want to expose.  See https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/diagram_test.cc#L27 for an example.

As an alternative, jwnimmer-tri proposes passing a `DiagramBuilder*` into helper methods that build pieces of a Diagram.  That's also OK with me, though I personally think the inheritance approach is a little cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-:-KYJg48kBgq_kqRylOCn:b-xe6hr1)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJj-mj77ykrFu-d7Mk:-KYJj-mjETKvwh4fSeCN:b-ni80kd) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L45)):*
> ```cpp
>   // Get a pointer to the actual plant subsystem (will be used below).
>   auto acrobot = dynamic_cast<const AcrobotPlant<double>*>(
>       acrobot_w_encoder->GetSubsystem("Acrobot"));
> ```

BTW, see @sherm1's comments in #4195 explaining why we cannot reply on the name of a subsystem being a certain value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJj-mj77ykrFu-d7Mk:-KYJj85w2ZRwATjPEECC:b-fe87b5) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, see @sherm1's comments in #4195 explaining why we cannot reply on the name of a subsystem being a certain value.
</blockquote></details>

Oops. I meant "rely" not "reply".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYK0lo0EaPIJZC2lE_J:-KYK0lo08NoTH5WvAaxQ:b-ib0pi7) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L45)):*
> ```cpp
>   // Get a pointer to the actual plant subsystem (will be used below).
>   auto acrobot = dynamic_cast<const AcrobotPlant<double>*>(
>       acrobot_w_encoder->GetSubsystem("Acrobot"));
> ```

Another solution is to provide an accessor like `AcrobotWEncoder::get_plant()`. I remember doing that [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L249)

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYK1U-J1bH3G2gvUcyG:b-lyvohs) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Rooting around in the context like this would also be better delegated to a public (static?) method on `AcrobotWEncoder : public Diagram<T>`
</blockquote></details>

I agree. See [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L257) for an example already in master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYK45Wi06qBt-xW_RH8:b-cdi9c2) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

From Slack(system2): I don't think we should add this function.  The conventional approach elsewhere is to make `AcrobotWEncoder : public Diagram<T>`, and add named accessors for subsystems you want to expose.  See https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/test/diagram_test.cc#L27 for an example.

As an alternative, jwnimmer-tri proposes passing a `DiagramBuilder*` into helper methods that build pieces of a Diagram.  That's also OK with me, though I personally think the inheritance approach is a little cleaner.
</blockquote></details>

@naveenoid and I are wondering: If we subclass `Diagram` to provide the named accessors to subsystems within the `Diagram`, are we expected to also subclass `DiagramBuilder` to ease the process of creating the subclass of `Diagram`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYKMRseDA5SUWxjwcz2:bymk19m) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
> are we expected to also subclass DiagramBuilder to ease the process of creating the subclass of Diagram?

No.  I don't think I understand how that would even be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYKN9fw2OU88KnSxaRr:b-pejzrr) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> are we expected to also subclass DiagramBuilder to ease the process of creating the subclass of Diagram?

No.  I don't think I understand how that would even be useful.
</blockquote></details>

Suppose I define a new class called `IiwaWithGripperDiagram` that is a subclass of `Diagram`. How would I create it? I cannot use the existing `DiagramBuilder` since it would output a `Diagram`, not an `IiwaWithGripperDiagram`.  Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYKNjUp3jy7KuAnLhWF:b-2ijeky) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Suppose I define a new class called `IiwaWithGripperDiagram` that is a subclass of `Diagram`. How would I create it? I cannot use the existing `DiagramBuilder` since it would output a `Diagram`, not an `IiwaWithGripperDiagram`.  Thoughts?
</blockquote></details>

Oops. I think I am using the wrong terminology. I mean "child class" not "subclass".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYKOI193zl_E290hUhM:beybpgv) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
> I cannot use the existing DiagramBuilder since it would output a Diagram, not an IiwaWithGripperDiagram. 

Please take a look at the link to `diagram_test.cc` I posted above, and possibly also https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/diagram_builder.h#L50.  Does that answer the question?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYKPVyY7UrLi0zKLVou:bimowxj) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> I cannot use the existing DiagramBuilder since it would output a Diagram, not an IiwaWithGripperDiagram. 

Please take a look at the link to `diagram_test.cc` I posted above, and possibly also https://github.com/RobotLocomotion/drake/blob/master/drake/systems/framework/diagram_builder.h#L50.  Does that answer the question?
</blockquote></details>

Yes, I did not realize `Diagram` provides a `BuildInto()` method.  H/T to @jwnimmer-tri for pointing it out to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/diagram.h, line 780 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYG2RH-CpGuDq-qVXA7:-KYKPwqc3yMFCE6HSSkb:b-br7b4m) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L780)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Returns the FIRST index?
</blockquote></details>

Per @sherm1's comments in #4195, we should for now avoid accessing systems by name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by RussTedrake** [comment]
I believe I've addressed everyone's concerns (everyone had the same concern -- about the design pattern the the AcrobotWEncoders diagram).  I've switched to subclassing from Diagram, and zapped the method I proposed from diagram.h.  PTAL.

---

Review status: 5 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 43 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJekOB6YvRHYHJE0Bs:-KYOWxH09CbNaARCwCGd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L43)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Perhaps I fail at parsing (the word "acrobot" appears a lot) but I don't see where this is used.
</blockquote></details>

Done.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJj-mj77ykrFu-d7Mk:-KYOWyaCBMsdkTqFT10_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L45)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oops. I meant "rely" not "reply".
</blockquote></details>

Done

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYK0lo0EaPIJZC2lE_J:-KYOWzvs8aw1nT1Hdc4Y:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L45)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Another solution is to provide an accessor like `AcrobotWEncoder::get_plant()`. I remember doing that [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L249)
</blockquote></details>

Done

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYOX0YrEHTHm7XGVASi:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I agree. See [here](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/kuka_iiwa_arm/controlled_kuka/kuka_demo.cc#L257) for an example already in master.
</blockquote></details>

Done

---

*[drake/systems/framework/diagram.h, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYG2ElkthZNZOoJi7Xp:-KYOX27U3L1PCtYOQWfd:b2nhjff) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L164)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you add a comment on the lifespan of this pointer?
</blockquote></details>

N/A

---

*[drake/systems/framework/diagram.h, line 165 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJcm3EDk_omtRDcXa0:-KYOX4sNBEZ-wHFdUMki:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L165)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, I did not realize `Diagram` provides a `BuildInto()` method.  H/T to @jwnimmer-tri for pointing it out to me.
</blockquote></details>

Done.

---

*[drake/systems/framework/diagram.h, line 780 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYG2RH-CpGuDq-qVXA7:-KYOX5ZsE1EwEKl6Ty1E:b2nhjff) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/systems/framework/diagram.h#L780)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Per @sherm1's comments in #4195, we should for now avoid accessing systems by name.
</blockquote></details>

N/A

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-:-KYOWitj1tTm0ZQqXkhv:b7rce9f)*

**Comment by liangfok** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOcy6jDPRGPf9DzLNE:-KYOcy6j2KkUDwHzMIco:b-19ldqf) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L28)):*
> ```cpp
> namespace {
> 
> // Simple example which simulates the Acrobot, started near the upright, with an
> ```

BTW, consider removing the "the" before "upright" or adding "configuration" after "upright".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYOxViqCS-ZqcdLthjd:b-ojwjnv) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I was suggesting

```
AcrobotStateVector<double>* x0 =
    AcrobotWEncoder<double>::get_mutable_acrobot_state(observer_context);
```

---

*[drake/systems/sensors/rotary_encoders.h, line 64 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOyLKYCbA2SWFL2YnN:-KYOyLKZ0vvAdKknGO5C:b-4c8h6x) ([raw file](https://github.com/robotlocomotion/drake/blob/576983a79b2b65eab8444094a50bc6761d3a1afb/drake/systems/sensors/rotary_encoders.h#L64)):*
> ```objc
> 
>   // System<T> override.
>   RotaryEncoders<AutoDiffXd>* DoToAutoDiffXd() const override;
> ```

BTW consider adding test coverage for this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-:-KYOyyMP3eMAeVXhuCIC:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 9 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-:-KYPBxwQA2bWjxUYCe4L:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOcy6jDPRGPf9DzLNE:-KYQCLak2ZggKnoaS1pa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider removing the "the" before "upright" or adding "configuration" after "upright".
</blockquote></details>

Done.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYQ8uPa0sYv4kt_0xmm:bsfj34p) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I was suggesting

```
AcrobotStateVector<double>* x0 =
    AcrobotWEncoder<double>::get_mutable_acrobot_state(observer_context);
```
</blockquote></details>

Ah.  that's better.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOcy6jDPRGPf9DzLNE:-KYQCq5L8xcToFd2pn1Y:b-yo0iza) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L28)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you push your changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOcy6jDPRGPf9DzLNE:-KYQCwxc2iN0lFkDC9wW:bmra23g) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Did you push your changes?
</blockquote></details>

Oh, nevermind. LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYQCsoYCYMdbcy_Fs0U:b3el89x) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Ah.  that's better.  Done.
</blockquote></details>

Like @liangfok, I'm not seeing pushed changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYOcy6jDPRGPf9DzLNE:-KYQDZdZ2Owak2Zx58Ft:bgutix4) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L28)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oh, nevermind. LGTM.
</blockquote></details>

FTR, my previous comment was in recognition that my original comment was a "BTW, consider..." meaning I would be OK if it were ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by RussTedrake** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4365#-KYJfRgw2MEFwpf_CH05:-KYQF63s-9af6QKD2A-g:b-9m94bv) ([raw file](https://github.com/robotlocomotion/drake/blob/b1dca3b043646f186bbf349b8f53d858dd2ce9fd/drake/examples/Acrobot/acrobot_run_lqr_w_estimator.cc#L62)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Like @liangfok, I'm not seeing pushed changes?
</blockquote></details>

ok, ok.  it took a second to clean up the cpplint.  it's in now.  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Comment by david-german-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4365)*

**Pull request merged**
