### PR TITLE
Add macOS wheel build scripts

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create a script to build a wheel on macOS. Update various Bazel logic to support the `macos_wheel` platform. Add scripts to mangle library load paths on macOS. Update inner wheel build script to support macOS as well as `manylinux`. Update various inner build scripts to support a build root other than `/`, since macOS does not permit creation of arbitrary top-level directories.

Note that the wheel build requires that the user running the scripts is able to use `brew`, and has write access to `/opt`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

Suggestion for testing:
```
export DRAKE_WHEELBUILD_PREFIX=/opt/drake-wheel
tools/wheel/macos/build-wheel.sh 0.0.0+experimental
```

Make sure you have permission to write to `/opt`. The wheel will be written to `${DRAKE_WHEELBUILD_PREFIX}/wheel/wheelhouse`. (You'll probably want to save this for testing the next PR.) You *can* run this in your usual Drake checkout, but you may need to do a `bazel clean` and/or `bazel shutdown` before and/or after, as I've known Bazel to get confused by switching back and forth between `macos` and `macos_wheel` in the same tree. (If you do run into problems, `build-wheel.sh --no-deps` will skip building the external dependencies, including VTK. This can save quite some time if those steps succeeded.)

I expect at some point we'll want release notes? Do you think it makes sense to tag *this* PR, or the last one that integrates this into the wheel builder?

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint on the easy stuff.  I'll dig into the more substantial code tomorrow.

> Reviewed 8 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307#-:-N3WWk3d5O3WuZIqbnCU:b-igmuaf)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[`tools/wheel/image/setup.py` line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3WW4P19frQUenBF6YC:-N3WW4P21iOgJi-CpBsB:b-3vtk0j) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/image/setup.py#L80)):*
> ```Python
>       # TODO Check this: do we need to add third-party licenses?
>       license='BSD 3-Clause License',
>       platforms=['linux_x86_64', 'macosx_12_0_x86_64'],
> ```

Do we know what `platforms...` does?  My very quick search found [this](https://stackoverflow.com/questions/34994130/what-does-the-platforms-argument-to-setup-in-setup-py-do) which makes it seem like nothing uses this field?  Is there a better citation.

I ask in part because I don't know what the `12_0` means here, and whether we will need to update it at some moment in the future (and if so, what would trigger that and how will we remember to do so)?

**Review by jwnimmer-tri — COMMENTED** [review]
First pass complete.

> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307#-:-N3_GP_g0dyfPitODv3s:bvb1a6z)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_57rE0ETP_lwCKGUN:-N3_57rE0ETP_lwCKGUO:bsf880p) (no related file):*
I see a bunch of code here being changed to obey `$DRAKE_WHEELBUILD_PREFIX` but I don't see any documentation about what the semantics of that variable are, nor anywhere it is being set.

Looking ahead to 37cd865 from the overall feature branch, I see that `macos.py` will eventually set this automatically, so that covers "anywhere it is being set" part.

That leaves the "documentation about semantics" still up in the air.  Even for something automatically set, I think we need some kind of overall documentation reference (with the wheel subsystem) that explains what this variable means, so that people reading over the various files here can refer back that definition.  It's a ... user-writeable scratch folder that these tools can nuke with abandon?  There is already a `README.rst` in this folder with an "Implementation Details" section; that's probably a good place for the definition to appear.

Part of the documentation of this variable should also specify whether/which scripts need to obey it.  Is it OK for a linux-only bash script helper to ignore it, or must we support it comprehensively?

I also find it suspicious that we allow the variable to be _conditionally_ set in all of our bash scripts.  If we really do want it to be empty on Ubuntu, I would think we could set it to empty explicitly in `linux.py` and then drop the `:-` from the uses in bash, so that we will fail-fast in case it ever accidentally becomes unset.  Nuking stuff in `/` when we didn't mean to would be a big problem.

---

It's also unclear to me (in the feature branch at 37cd865) why we need to offer this as a command-line option`--build-root`.  Could we hard-code `DRAKE_WHEELBUILD_PREFIX=/opt/drake-wheel/build` or something in the main, platform-agnostic script and call it a day?  What is the use case for letting macos developers vary this path, and what is the reason we can't use the same default on macos and Ubuntu?  Removing config options and platform-specific differences should make the code easier to maintain in the long term.

This half of the discussion is not a blocker for this PR (since that command-line option isn't here yet) but might influence how the first half gets resolved here.

___
___
*[`tools/wheel/image/build-wheel.sh` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_C_O3858KfLzEquj-:-N3_C_O3858KfLzEquj0:bp8pwhc) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/image/build-wheel.sh#L106)):*
> ```Shell
> if [ "$(uname)" == "Darwin" ]; then
>     change_lpath '@loader_path/../../../' '@rpath/' pydrake/*.so
>     change_lpath '@loader_path/../../../../' '@rpath/' pydrake/*/*.so
> ```

Using argument position to convey semantics makes this code more difficult to follow than need be.



_Suggestion:_
```Shell
    change_lpath --old='@loader_path/../../../' --new='@rpath/' pydrake/*.so
    change_lpath --old='@loader_path/../../../../' --new='@rpath/' pydrake/*/*.so
```
___
*[`tools/wheel/image/setup.py` line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3WW4P19frQUenBF6YC:-N3_4a698xUUe87YGy4t:b-ytk414) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/image/setup.py#L80)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

I know no more than you do. It was present in the original `setup.py` that I inherited (possibly from Jamie?). It sounds like it's probably fairly safe to just remove it? Or, at least, on the theory that humans might look at this, drop the `_12_0`. I suspect one of those options is probably desired; which do you prefer?
</blockquote></details>

I'll leave it up to you to decide and/or research more to figure out a better resolution?  I guess if I had to flip a coin, I'd drop the `_12_0` but keep the line.
___
*[`tools/wheel/macos/build-wheel.sh` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_DjPCES_DNdCv7gLC:-N3_DjPD4fhtOEqNE498:bdbcbeu) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L10)):*
> ```Shell
> set -eu -o pipefail
> 
> readonly pip_root="$(cd "$(dirname "${BASH_SOURCE}")" && realpath ..)"
> ```

nit I think `pip_root` here means the same things as `resource_root` in the `wheel_builder/*.py` scripts?  If they refer to the same concept, they should use the same name throughout.



_Code quote:_
```Shell
pip_root
```
___
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3_Ewel1nfU6Ed9z8he:b-o7hvgu) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
> ```Shell
> # -----------------------------------------------------------------------------
> 
> rm -rf "${DRAKE_WHEELBUILD_PREFIX}/wheel"
> ```

At this point, should _anything_ exist in the `${DRAKE_WHEELBUILD_PREFIX}`?  It seems to me like we should either fail-fast here if it has pollution, or else just nuke the whole thing, recursively.  Since we haven't built any dependencies yet, it seems like it should be empty, there's nothing there of value?  (We could skip the cleanout or fail-fast when `build_deps` is false.)
___
*[`tools/wheel/macos/build-wheel.sh` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_EVLB2RwVmdVnadEu:-N3_EVLB2RwVmdVnadEv:b-sn12y3) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L43)):*
> ```Shell
> chmod 700 ~/.ssh
> 
> while read host proto fingerprint; do
> ```

nit This could probably use a comment explaining what's happening.  I think it might be "copy github.com known_hosts from git into the user's home folder, unless it's already there"?
___
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3_Fdxx5AstzwDIM3mD:bwipfdq) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
> ```Shell
> 
> bazel build "${bazel_args[@]}" //tools/wheel:strip_rpath
> bazel build "${bazel_args[@]}" //tools/wheel:change_lpath
> ```

I don't think these two lines have any effect.  We do not appear to call these tools using the `bazel-bin/tools/wheel/change_lpath` command, rather just invoking them directly from the source tree?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_57rE0ETP_lwCKGUN:-N3_e7Ho4L3poblae2XL:b-2w5kvk) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I see a bunch of code here being changed to obey `$DRAKE_WHEELBUILD_PREFIX` but I don't see any documentation about what the semantics of that variable are, nor anywhere it is being set.

Looking ahead to 37cd865 from the overall feature branch, I see that `macos.py` will eventually set this automatically, so that covers "anywhere it is being set" part.

That leaves the "documentation about semantics" still up in the air.  Even for something automatically set, I think we need some kind of overall documentation reference (with the wheel subsystem) that explains what this variable means, so that people reading over the various files here can refer back that definition.  It's a ... user-writeable scratch folder that these tools can nuke with abandon?  There is already a `README.rst` in this folder with an "Implementation Details" section; that's probably a good place for the definition to appear.

Part of the documentation of this variable should also specify whether/which scripts need to obey it.  Is it OK for a linux-only bash script helper to ignore it, or must we support it comprehensively?

I also find it suspicious that we allow the variable to be _conditionally_ set in all of our bash scripts.  If we really do want it to be empty on Ubuntu, I would think we could set it to empty explicitly in `linux.py` and then drop the `:-` from the uses in bash, so that we will fail-fast in case it ever accidentally becomes unset.  Nuking stuff in `/` when we didn't mean to would be a big problem.

---

It's also unclear to me (in the feature branch at 37cd865) why we need to offer this as a command-line option`--build-root`.  Could we hard-code `DRAKE_WHEELBUILD_PREFIX=/opt/drake-wheel/build` or something in the main, platform-agnostic script and call it a day?  What is the use case for letting macos developers vary this path, and what is the reason we can't use the same default on macos and Ubuntu?  Removing config options and platform-specific differences should make the code easier to maintain in the long term.

This half of the discussion is not a blocker for this PR (since that command-line option isn't here yet) but might influence how the first half gets resolved here.
</blockquote></details>

Okay, everyone is now hard-coded to use `/opt/drake-wheel-build`, except for tests on Ubuntu, which still use `/test`. The next PR will change those to `/opt/drake-wheel-test`. Since it would require additional reworking for non-obvious value, there is no `rm -rf /opt/drake-wheel-build`. (It would require **even more** reworking for macOS to not need a writable `/opt`, so hard-coding the build location as 'somewhere in `/opt`' is presumed to be acceptable, at least for now.)

___
___
*[`tools/wheel/image/build-wheel.sh` line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_C_O3858KfLzEquj-:-N3_uvp-5z_TAZX6lDzW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/image/build-wheel.sh#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Using argument position to convey semantics makes this code more difficult to follow than need be.
</blockquote></details>

Done.
___
*[`tools/wheel/image/setup.py` line 80 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3WW4P19frQUenBF6YC:-N3_fADMBX8_yuQ-DC9h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/image/setup.py#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'll leave it up to you to decide and/or research more to figure out a better resolution?  I guess if I had to flip a coin, I'd drop the `_12_0` but keep the line.
</blockquote></details>

Done.
___
*[`tools/wheel/macos/build-wheel.sh` line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_DjPCES_DNdCv7gLC:-N3_YmgN17wWE-GBxrvV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think `pip_root` here means the same things as `resource_root` in the `wheel_builder/*.py` scripts?  If they refer to the same concept, they should use the same name throughout.
</blockquote></details>

Done.
___
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3_Ytue5UyB9O7wb4M4:bvz8z06) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

At this point, should _anything_ exist in the `${DRAKE_WHEELBUILD_PREFIX}`?  It seems to me like we should either fail-fast here if it has pollution, or else just nuke the whole thing, recursively.  Since we haven't built any dependencies yet, it seems like it should be empty, there's nothing there of value?  (We could skip the cleanout or fail-fast when `build_deps` is false.)
</blockquote></details>

Well... in my earlier testing, I had Drake's own checkout at `${DRAKE_WHEELBUILD_PREFIX}/drake`. Plus, I'd as soon not risk someone setting `${DRAKE_WHEELBUILD_PREFIX}` to `$HOME` (which I think is actually relatively safe as the scripts are currently). Requiring an empty directory might be okay, but it would make repeated testing less convenient. Since we nuke all of the subdirectories that are actually written, I don't think requiring an empty directory actually gains us much.
___
*[`tools/wheel/macos/build-wheel.sh` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_EVLB2RwVmdVnadEu:-N3_XbQB-8mIe0gwc6zr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This could probably use a comment explaining what's happening.  I think it might be "copy github.com known_hosts from git into the user's home folder, unless it's already there"?
</blockquote></details>

Done.
___
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3_Waya9RrxG93qRSQX:b-t6z9vp) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think these two lines have any effect.  We do not appear to call these tools using the `bazel-bin/tools/wheel/change_lpath` command, rather just invoking them directly from the source tree?
</blockquote></details>

Uh... not even remotely? We invoke them via `change_lpath`, which has to be in `PATH`. Which happens at lines 116-122 (plus when we activate that virtualenv). Also, I'm pretty sure they can't be run directly from the source tree due to `import`s; they need to be "packaged", which is what these lines do. (IIRC, at the point at which we need to invoke them, we no longer know where Drake's sources live, which precludes invoking them via `bazel run` or by full or partial path.)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3_wJnN5VwoiO1MDV5X:b-8ubh5q) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Uh... not even remotely? We invoke them via `change_lpath`, which has to be in `PATH`. Which happens at lines 116-122 (plus when we activate that virtualenv). Also, I'm pretty sure they can't be run directly from the source tree due to `import`s; they need to be "packaged", which is what these lines do. (IIRC, at the point at which we need to invoke them, we no longer know where Drake's sources live, which precludes invoking them via `bazel run` or by full or partial path.)
</blockquote></details>

Clarification: we certainly *don't* invoke them from the source tree, and I don't know where you thought you saw that happening?

**Comment by jwnimmer-tri** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3_xk9r1xyWlFIRC3-Y:bsan07f) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Clarification: we certainly *don't* invoke them from the source tree, and I don't know where you thought you saw that happening?
</blockquote></details>

OK Aha, I misread the symlinking code originally.  I saw `ln -s $git_root` and assumed we were symlinking the source files.  But now I see the `$git_root/bazel-bin` part of that path which I'd overlooked the first time, so we are in fact calling the compiled programs.  Comment withdrawn.

**Review by mwoehlke-kitware — COMMENTED** [review]
If the CI wheel build fails again, I'll stop trying to fix it on my mac (which forces me to push changes _anyway_ before I'd be able to test them locally) and interrupt what I was doing on our Ubuntu machine to fix it locally.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307#-:-N3_zkDRBJOj6y9aDLD9:bszack8)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3_z-CP9hzXHEkFS-vU:bbcluo0) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Aha, I misread the symlinking code originally.  I saw `ln -s $git_root` and assumed we were symlinking the source files.  But now I see the `$git_root/bazel-bin` part of that path which I'd overlooked the first time, so we are in fact calling the compiled programs.  Comment withdrawn.
</blockquote></details>

:+1: :slightly_smiling_face:.

(Also, as I was trying to say, I apologize if my original comment came across as harsher than intended. By "remote", what I was trying to say is that the way these tools get invoked is *two* steps removed — i.e. 'more remote' — compared to "directly from the source tree", where you (rightly) observed they aren't run *one* step removed, i.e. as `bazel-bin/tools/wheel/change_lpath`.)

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3a1P8I6komVtMsri2D:b-x9328j) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

:+1: :slightly_smiling_face:.

(Also, as I was trying to say, I apologize if my original comment came across as harsher than intended. By "remote", what I was trying to say is that the way these tools get invoked is *two* steps removed — i.e. 'more remote' — compared to "directly from the source tree", where you (rightly) observed they aren't run *one* step removed, i.e. as `bazel-bin/tools/wheel/change_lpath`.)
</blockquote></details>

On that note... I'm going to let the wheel build finish first, but maybe `drake_root` would be clearer than `git_root`? (Originally, `pip_root` and `git_root` lined up nicely, but with `pip_root` already renamed, I don't have that argument :slightly_smiling_face:.)

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Fdxx5AstzwDIM3mC:-N3a36hy6NRA1AkXdUwv:b-ohha9h) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure, it was no problem.  Much to everyone else's chagrin, my tact filter is on the inbound direction, not the outbound one.

I actually liked `git_root` (or `drake_git_root`) because it could only mean one thing here.  Just `drake_root` on its own could mean any number of things -- including an installed drake prefix, for example.
</blockquote></details>

Okay. I'll probably leave it, then, as `drake_git_root` doesn't seem all that likely to address the "not noticing the `bazel-bin` after it" problem (to wit, still having "git" there is likely to still have you thinking "**source** tree"). If you have further ideas, though, let me know!

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @mwoehlke-kitware)

___
*[`tools/wheel/Dockerfile` line 29 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3a3859EieW7dKhNMHq:-N3a385A5V6JhD56OMqL:brbes7k) ([raw file](https://github.com/robotlocomotion/drake/blob/e80d001876a8c14dbd46e8a5f8c0d1eaf0e7de1a/tools/wheel/Dockerfile#L29)):*
> ```Dockerfile
> 
> ADD image/build-vtk.sh /image/
> ADD image/vtk-args /vtk/
> ```

nit The changes to the `ADD` lines for vtk here don't quite make sense to me?  We are adading the shell script into two different places?
___
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3a3Oc477RocQgU3CRp:b-phsngp) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
Given that we're not in a container, I do think that we need to be as paranoid as practical about ensuring no lingering state.  Part of merging this to master is pivoting from "most convenient for local incremental hacking" to "most likely to be correct for the long term".  The main way we stay safe will be running on an Unprovisioned VM image, but I think it's worth adding a little code here and there for double-checking as well.

> Since we nuke all of the subdirectories that are actually written, I don't think requiring an empty directory actually gains us much.

Maybe as of this commit you're sure that the `rm` commands later in this file are sufficient, but there is no cross-checking of that happening so it might easily bitrot, and (as best I understand) doing the extra checking is close by within our reach.

I think we could move all of the `rm` commands sprinkled below up to here, at which point we should be able to make a statement about what's expected/allowed to be in `/opt/drake-wheel-build` by default?

It would be fine to skip the check if a manual user doing local hacking requested as much, either via `--no-deps` or a new flag like `--no-pedantic`.  My only request is that we default to paranoia and cross-checking.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Well, it's all consistent and spelled correctly. The question of what the state of the wheel prefix directory should be still seems open. And you've still got CI issues (seems like the most relevant CI build). But, otherwise, :LGTM:

> Reviewed 8 of 15 files at r1, 7 of 7 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307#-:-N3ae0Jr2t4gK8oW33Eb:bw2uq8g)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3dtISk15feudeLypch:b-rwdcnk) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To keep the PR train going, this could also turn into a TODO comment for now, to revisit later.
</blockquote></details>

Actually, I was going to propose that we leave *this* script as-is. It can't clean up after itself *anyway*, as that would be counterproductive (build the wheel, delete the wheel, test... er... extract... er... d'oh!) The builder can be tidy and paranoid. (It's also much easier to add arguments to the builder :stuck_out_tongue:.)

Besides, it's a fallacy that once it's working, ease of development is no longer an issue. That would only be true if the code never changed again. I still use the debugging features of the Docker build process all the time, and even those are much less efficient than they could be.

Speaking of trains, it occurred to me that this might be sufficient to revisit the MUMPS changes. I hope to be able to look into that today.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI (waiting on @mwoehlke-kitware)

___
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3dwOho2ETm8adY2ZZU:bxmxzk0) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Actually, I was going to propose that we leave *this* script as-is. It can't clean up after itself *anyway*, as that would be counterproductive (build the wheel, delete the wheel, test... er... extract... er... d'oh!) The builder can be tidy and paranoid. (It's also much easier to add arguments to the builder :stuck_out_tongue:.)

Besides, it's a fallacy that once it's working, ease of development is no longer an issue. That would only be true if the code never changed again. I still use the debugging features of the Docker build process all the time, and even those are much less efficient than they could be.

Speaking of trains, it occurred to me that this might be sufficient to revisit the MUMPS changes. I hope to be able to look into that today.
</blockquote></details>

Sure, if the plan is for the _caller_ of this script to do the nuking and/or double-checking, that's fine by me too.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: 1 unresolved discussion (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3dwcXq5W4OzT4lAVpN:-N3dwcXq5W4OzT4lAVpO:b-bcdi09) (no related file):*
Jenkins still seems unhappy with the Ubuntu build.

___

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please

**Comment by mwoehlke-kitware** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3dwcXq5W4OzT4lAVpN:-N3dwuqz8_arJoe4C5Em:b42vzx2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Jenkins still seems unhappy with the Ubuntu build.
</blockquote></details>

Yeah... I have no idea why. It looks like extracting the wheel must have gone sideways somehow, but I have no idea why *that* would suddenly stop working. Especially as it's passing for me locally. I'm re-running in case it was a fluke, but if anyone has any ideas, please share.

(The most obvious possible problem would be that the wheel *name* is wrong, but AFAICT that isn't the case; `auditwheel` reported the same name that we're trying to test.)

**Comment by mwoehlke-kitware** [comment]
*[`tools/wheel/macos/build-wheel.sh` line 28 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3_Ewel1nfU6Ed9z8hd:-N3dxqLq0CnEFViAm6A9:bqlkqrn) ([raw file](https://github.com/robotlocomotion/drake/blob/008b9741bb213572ddd183d58d9575d41b4ed008/tools/wheel/macos/build-wheel.sh#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure, if the plan is for the _caller_ of this script to do the nuking and/or double-checking, that's fine by me too.
</blockquote></details>

Yes, after thinking about it last night (after signing off), that's my thought. It should be easier to implement, at least while preserving the ability to debug when things go sideways, and doing it that way also means *this* PR (and the next one, which adds testing but doesn't yet do the builder integration) doesn't need to wait.

**Comment by mwoehlke-kitware** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17307#-N3dwcXq5W4OzT4lAVpN:-N3e-peDCEJW0FhAujM0:bc87621) (no related file):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Yeah... I have no idea why. It looks like extracting the wheel must have gone sideways somehow, but I have no idea why *that* would suddenly stop working. Especially as it's passing for me locally. I'm re-running in case it was a fluke, but if anyone has any ideas, please share.

(The most obvious possible problem would be that the wheel *name* is wrong, but AFAICT that isn't the case; `auditwheel` reported the same name that we're trying to test.)
</blockquote></details>

Ah, okay, I'm pretty sure I see the problem. Trivial fix, if I'm right... and not helping that `--output-dir .` (i.e. the default) appears to be broken. Apparently the fix for that is later in the "macOS wheel" chain of commits :sob:.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI (waiting on @mwoehlke-kitware)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17307)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI (waiting on @mwoehlke-kitware)

**Pull request merged**
