### PR TITLE
systems: Use const-ref arguments, not unique_ptr

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This commit adjusts FixInputPort and DeclareAbstractState to use pass-by-const-ref.

Part of #8904.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14453)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review (or delegation), please.

**Review by sherm1 — COMMENTED** [review]
The call sites look much nicer!
Feature :lgtm: with a few minor comments.

> Reviewed 23 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14453#-:-MOd4ozV3Zp_osJ2MOnW:b-kwdmuq)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/framework/context_base.h, line 222 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14453#-MOd2p-93sVBsCEMAHc6:-MOd2p-93sVBsCEMAHc7:b-2hye8q) ([raw file](https://github.com/robotlocomotion/drake/blob/ef5b72a4369b3ac315ded1bdab58be33d1459b0e/systems/framework/context_base.h#L222)):*
> ```objc
>   /** (Advanced) Same as above method but the value is passed by unique_ptr
>   instead of by const reference. The port will contain a copy of the `value`
>   (not retain a pointer to the `value`). */
> ```

This is a change to the semantics of the original method, which took ownership of the AbstractValue argument. I suppose that could be considered a breaking change, though it seems unlikely any code dependent on that was correct (code that set the value just once through a retained pointer _could_ be right, however inadvisable).

I'm not concerned about the compatibility but this change should get mentioned in the next release notes.
___
*[systems/framework/leaf_system.h, line 1127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14453#-MOd3tgw6BuZy2JvlcLh:-MOd3tgw6BuZy2JvlcLi:b6mqc9m) ([raw file](https://github.com/robotlocomotion/drake/blob/ef5b72a4369b3ac315ded1bdab58be33d1459b0e/systems/framework/leaf_system.h#L1127)):*
> ```objc
> 
>   /** Declares an abstract state.
>   @param abstract_state The abstract state, its ownership is transferred.
> ```

minor: this comment is wrong now
___
*[systems/framework/leaf_system.h, line 1133 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14453#-MOd40KH1Z39qopaR4N2:-MOd40KIAjLX2DTKbv60:bbrremr) ([raw file](https://github.com/robotlocomotion/drake/blob/ef5b72a4369b3ac315ded1bdab58be33d1459b0e/systems/framework/leaf_system.h#L1133)):*
> ```objc
> 
>   /** Declares an abstract state.
>   @param abstract_state The abstract state, its ownership is transferred.
> ```

minor: semantics have changed here -- despite appearances this signature no longer takes ownership.

The behavioral change should get mentioned in the release notes.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14453)* status: needs at least two assigned reviewers (waiting on @sherm1)

___
*[systems/framework/context_base.h, line 222 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14453#-MOd2p-93sVBsCEMAHc6:-MOdCHm8EIudApxOC5Hj:b-rwawkx) ([raw file](https://github.com/robotlocomotion/drake/blob/ef5b72a4369b3ac315ded1bdab58be33d1459b0e/systems/framework/context_base.h#L222)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is a change to the semantics of the original method, which took ownership of the AbstractValue argument. I suppose that could be considered a breaking change, though it seems unlikely any code dependent on that was correct (code that set the value just once through a retained pointer _could_ be right, however inadvisable).

I'm not concerned about the compatibility but this change should get mentioned in the next release notes.


</blockquote></details>

Done (in commit message).

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule (tomorrow), please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 22 of 24 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14453#-:-MOhW84TEtS5TNFzl9kO:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),sherm1(platform)

**Pull request merged**
