### PR TITLE
Fix kinematic trajectory optimization

### PR DESCRIPTION
**Pull request by manuelli**
Fixes an issue in the constructor of KinematicTrajectoryOptimization where it attempts to call getXinds() but that abstract function isn't yet defined in the calling subclass or the other superclass. Adds an initialize() method. If you have SubClass < KinematicTrajectoryOptimization & SuperClass then you can call the constructor of KinematicTrajectoryOptimization in SubClass without defining getXinds() and then after you have defined it you can call obj.initialize() to perform the rest of the steps that were in the original constructor.

@avalenzu could you review this please.

### CODE REVIEW

**Comment by RussTedrake** [comment]
code looks good to me.  are there any test cases in the codebase which use this (and would catch a bug if one were introduced)?

**Comment by manuelli** [comment]
No there aren't currently any unit tests for this but I will try to write one tonight that includes a test class with KinematicTrajectoryOptimization as a superclass and that uses the initialize_flag option in the constructor.

**Comment by avalenzu** [comment]
Content of the changes looks fine. Thanks for this, @manuelli!

One style note: could you change your editor preferences in MATLAB to indent by 2 spaces (the default is 4) and then re-indent `KinematicTrajectoryOptimization`? That's the convention we use in the rest of the codebase.

**Comment by manuelli** [comment]
I added a unit test that utilizes the added functionality of the constructor in solvers/trajectoryOptimization/test.

**Pull request merged**
