### PR TITLE
Revert "Enable caching in Drake (but disabled by default)"

### PR DESCRIPTION
**Pull request by fbudin69500**
Dear @sherm1 ,

The on-call build cop, @fbudin69500, believes that your PR #9113 may have
broken one or more of Drake's continuous integration builds [1,2]. It is
possible to break a build even if your PR passed continuous integration
pre-merge because additional platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-bazel-continuous-memcheck-asan/1558/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-xenial-gcc-bazel-continuous-memcheck-asan-everything/1508/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [3].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Continuous Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/
[2] CI Nightly Production Dashboard: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/
[3] https://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9258)

### CODE REVIEW

**Comment by fbudin69500** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-asan please
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-memcheck-asan-everything please

**Comment by sherm1** [comment]
@fbudin69500 do these memcheck/asan builds have Debug code enabled? I wouldn't be surprised if that was expensive since there are lots of costly Debug checks in the cache invalidation code.

Of the two builds in the message above 1557 and 1508 I was able to see four tests that timed out in 1508 but everything looked green in 1557. What was the issue there?

I'd like to investigate before deciding to change any timeouts. Can you provide instructions for running with the same settings locally as were used in 1557/1508?  Thanks!

**Comment by sherm1** [comment]
(Per @fbudin69500 the other timed-out build is https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=1038722 (1558) not 1557 as above.)

**Comment by fbudin69500** [comment]
@sherm1, thanks for the pointer. I have updated 1557 to 1558 in the original to improve readability.

**Comment by sherm1** [comment]
The 4 timed-out tests (in Debug/memcheck/asan builds):
`systems/analysis:{explicit/implicit/semi_explicit}_euler_integrator_test`
`systems/analysis:initial_value_problem_test`

**Comment by sherm1** [comment]
Does anyone know how I can find the complete set of test runtimes for before and after this PR landed? If only the Debug times slowed down I'll adjust the time limits but if Release times were affected significantly I'd like to revert and do some performance tweaking first.

**Comment by sherm1** [comment]
Submitted PR #9260 to fix these timeouts, PTAL @fbudin69500.

**Comment by sherm1** [comment]
Closing this now that #9260 merged.

**Pull request closed without merging**
