### PR TITLE
pydrake: Bind some missing multibody tree-related items

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
I just found myself needing some of these.  I can give a review this afternoon if you like.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJYTEDV8j8i6eRRIFb2:b-9rk3cm)* status: needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jwnimmer-tri — COMMENTED** [review]
I think the code is done, but I hit my timebox before finishing the tests.  I've just pushed my self-comments on what still needs testing so we know what's untested.

If you need parts already tested, let me know which ones and I can split the PR to get those merged.  If you need parts not yet tested, you or others could push commits to the PR with those.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJYU3fb4dA1IlAcy9hy:biarxhw)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/tree_py.cc, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNoeTC9zDsJdNekl2W:-MJNoeTC9zDsJdNekl2X:bxbbzmx) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L163)):*
> ```cpp
>   // Frames.
>   {
>     using Class = Frame<T>;
> ```

Working

All of the new Frame methods need tests.
___
*[bindings/pydrake/multibody/tree_py.cc, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNobDVExFperX1ijRf:-MJNobDVExFperX1ijRg:bal2m6w) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L259)):*
> ```cpp
>   // Bodies.
>   {
>     using Class = Body<T>;
> ```

Working

All of the new Body methods need tests.
___
*[bindings/pydrake/multibody/tree_py.cc, line 317 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNr0O57Dc1ZpKcHHly:-MJNr0O57Dc1ZpKcHHlz:b-iej6g8) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L317)):*
> ```cpp
>                  const SpatialInertia<double>&>(),
>             py::arg("body_name"), py::arg("model_instance"), py::arg("M_BBo_B"),
>             cls_doc.ctor.doc_3args)
> ```

Working

All of the new constructors immediately above need tests.

**Review by RussTedrake — COMMENTED** [review]
The methods i need at the moment are covered by tests: the additional accessors for RevoluteJoint and PrismaticJoint.  

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJYVgVR9A-JFTgIsP_F:b-mgcb8f)* status: 4 unresolved discussions, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/tree_py.cc, line 543 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJYVAnp0VrulbP0mv3-:-MJYVAnp0VrulbP0mv30:bzg7aek) ([raw file](https://github.com/robotlocomotion/drake/blob/f53658585eb084c95471390f307eef1c3b1952a0/bindings/pydrake/multibody/tree_py.cc#L543)):*
> ```cpp
>                  const Vector3<double>&, double>(),
>             py::arg("name"), py::arg("frame_on_parent"),
>             py::arg("frame_on_child"), py::arg("axis"), py::arg("damping") = 0,
> ```

this binding is only for the constructor without joint limits.  And there are no other methods that allow me to set the joint limits.  can we please bind the other one?  (it is also more consistent with the prismatic joint)

**Review by jwnimmer-tri — COMMENTED** [review]
Ready for review.

-(status: do not merge) -(status: do not review)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJYZPjg5gBAagDEIMp8:bv2amv3)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge" (waiting on @jwnimmer-tri and @RussTedrake)

___
*[bindings/pydrake/multibody/tree_py.cc, line 163 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNoeTC9zDsJdNekl2W:-MJYZ8DjDHRkoFDpHLJB:b-2u3ke6) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L163)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

All of the new Frame methods need tests.
</blockquote></details>

I've removed Frame bindings to a future PR.
___
*[bindings/pydrake/multibody/tree_py.cc, line 259 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNobDVExFperX1ijRf:-MJYZAQ-6KPhkmWixbXh:brtx6s1) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L259)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

All of the new Body methods need tests.
</blockquote></details>

I've removed Body bindings to a future PR.
___
*[bindings/pydrake/multibody/tree_py.cc, line 317 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJNr0O57Dc1ZpKcHHly:-MJYZJr56Qsj4mX306Uo:b-xbkoh8) ([raw file](https://github.com/robotlocomotion/drake/blob/b4227a0196a2172cce19369e648d154df1f44bca/bindings/pydrake/multibody/tree_py.cc#L317)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

All of the new constructors immediately above need tests.
</blockquote></details>

Done.  Added tests.
___
*[bindings/pydrake/multibody/tree_py.cc, line 543 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJYVAnp0VrulbP0mv3-:-MJYZMgzE8Y6TRnlvzI5:b-l02crk) ([raw file](https://github.com/robotlocomotion/drake/blob/f53658585eb084c95471390f307eef1c3b1952a0/bindings/pydrake/multibody/tree_py.cc#L543)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this binding is only for the constructor without joint limits.  And there are no other methods that allow me to set the joint limits.  can we please bind the other one?  (it is also more consistent with the prismatic joint)
</blockquote></details>

Working on it now.

**Review by jwnimmer-tri — COMMENTED** [review]
+@RussTedrake for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJY_o8G939i_UgbVO4F:bnqv4zg)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @RussTedrake)

___
*[bindings/pydrake/multibody/tree_py.cc, line 543 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJYVAnp0VrulbP0mv3-:-MJY_trnD6BRgZ0OfIgy:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f53658585eb084c95471390f307eef1c3b1952a0/bindings/pydrake/multibody/tree_py.cc#L543)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working on it now.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  i spent some time checking all of them.  i thought I had you once or twice, but found the coverage somewhere else.  ;-)  thanks for doing this.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14195#-:-MJYcEpNB9kBWmJ5qIy6:b-8pmktu)* status: :shipit: complete! all discussions resolved, LGTM from assignee RussTedrake(platform)

___
*[bindings/pydrake/multibody/tree_py.cc, line 543 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14195#-MJYVAnp0VrulbP0mv3-:-MJYaQo36pPHuEkeStGA:bsv417u) ([raw file](https://github.com/robotlocomotion/drake/blob/f53658585eb084c95471390f307eef1c3b1952a0/bindings/pydrake/multibody/tree_py.cc#L543)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thank you.

**Pull request merged**
