### PR TITLE
Methods and tests for maximum absolute difference between two spatial…

### PR DESCRIPTION
**Pull request by mitiguy**
Methods and tests to compare two spatial vectors.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7334)

### CODE REVIEW

**Comment by mitiguy** [comment]
Feature review +@amcastro-tri 
Platform review +@soonho-tri 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-:-KxKtHTm1DEw0rpqI0OC:b-xwtlpq)*

**Comment by soonho-tri** [comment]
:lgtm: (aside a few typos)

@amcastro-tri , please double-check the math behind the code. 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxO4_p3ZR2iH1H2MlZB:-KxO4_p3ZR2iH1H2MlZC:b3x9ilo) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L135)):*
> ```objc
>   /// -----------------|-------------------------------------------------
>   /// w_max_difference | Maximum absolute difference in rotation components.
>   /// v_max_difference | Maximum absolute difference in translation components.
> ```

FYI, doxygen doesn't render this table as we want.



---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxO4ujgy9Jwc6c-pe7H:-KxO4ujgy9Jwc6c-pe7I:b764uxs) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L147)):*
> ```objc
>   /// Compares the rotational and translational parts of `this` and `other`
>   /// to check if they are the same to within specified absolute differences.
>   /// @returns `true` if the rotational part of`this` and `other` are equal
> ```

FYI,
```
of`this` -> of `this`
```

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxO5Mvx0j3Htu5SXope:-KxO5Mvx0j3Htu5SXopf:buaxqmx) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L148)):*
> ```objc
>   /// to check if they are the same to within specified absolute differences.
>   /// @returns `true` if the rotational part of`this` and `other` are equal
>   /// within @p rotational_tolerance and the translational part of `this` and
> ```

FYI, `*_tolerance` -> `*_epsilon`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-:-KxO5grTxMwninuHYvRD:b-jgsax3)*

**Comment by amcastro-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOPF14qYl-Vgji0v71:-KxOPF14qYl-Vgji0v72:b-213nrh) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L134)):*
> ```objc
>   /// and translational components of `this` and `other`, as follows:
>   /// -----------------|-------------------------------------------------
>   /// w_max_difference | Maximum absolute difference in rotation components.
> ```

BTW why not to say "Infinity norm of the difference in rotational components"?

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 135 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOPNahv8VCMSkoWfB_:-KxOPNahv8VCMSkoWfBa:b-sx2sr6) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L135)):*
> ```objc
>   /// -----------------|-------------------------------------------------
>   /// w_max_difference | Maximum absolute difference in rotation components.
>   /// v_max_difference | Maximum absolute difference in translation components.
> ```

BTW why not to say "Infinity norm of the difference in translational components"?

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOPqUGlrFWTzOUv5yM:-KxOPqUGlrFWTzOUv5yN:bm1vcmp) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L146)):*
> ```objc
> 
>   /// Compares the rotational and translational parts of `this` and `other`
>   /// to check if they are the same to within specified absolute differences.
> ```

I would add here documentation for `rotational_epsilon` and `translational_epsilon` using `@param`. That gives us the chance to say , for instance, that these arguments have units.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOQ_lFnovE5WuVDBT2:-KxOQ_lFnovE5WuVDBT3:bmzfw7x) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L219)):*
> ```cpp
>   const Vector3<T> wA(1, 2, -3), vA(9, 8, -7);
>   const Vector3<T> wB(4, 5, -7), vB(7, 7, -7);
>   const SpatialQuantity A(wA, vA), B(wB, vB);
> ```

shouldn't `A` and `B` be nearly equal to each other? This, with the pretty large tolerance used bellow, makes for a very strange way to test this (though granted it does what it says, just an abuse on its usage).

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOQG_MxOed3lq59Kd4:-KxOQG_MxOed3lq59Kd5:b-60sniw) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L222)):*
> ```cpp
> 
>   const double tolerance = 8 * std::numeric_limits<double>::epsilon();
>   double w_epsilon = 4 + tolerance, v_epsilon = 2 + tolerance;
> ```

This test is pretty strange. Isn't this method supposed to be used for spatial quantities that are nearly equal?
I was expecting to see `w_epsilon` to be a small number. In this case is close to 4. Same for v_epsilon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334)*

**Comment by mitiguy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOPqUGlrFWTzOUv5yM:-KxVER7KNMUGJTiY5p7e:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/spatial_vector.h#L146)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I would add here documentation for `rotational_epsilon` and `translational_epsilon` using `@param`. That gives us the chance to say , for instance, that these arguments have units.
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOQ_lFnovE5WuVDBT2:-KxVJJs45lqEnu2_d8rZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L219)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

shouldn't `A` and `B` be nearly equal to each other? This, with the pretty large tolerance used bellow, makes for a very strange way to test this (though granted it does what it says, just an abuse on its usage).
</blockquote></details>

Done.

---

*[drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc, line 222 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-KxOQG_MxOed3lq59Kd4:-KxVJKP36CbySCFq0_si:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9f0debd586016e36cbd49d0bb189e0c8cc74fe67/drake/multibody/multibody_tree/math/test/spatial_algebra_test.cc#L222)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This test is pretty strange. Isn't this method supposed to be used for spatial quantities that are nearly equal?
I was expecting to see `w_epsilon` to be a small number. In this case is close to 4. Same for v_epsilon.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 138 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-Kxhev4XXSox4DiK1dT2:-Kxhev4YR9iupsP10K9b:b-s9fdf6) ([raw file](https://github.com/robotlocomotion/drake/blob/28d4edf566df7ac84d96814fbb392e2c889a1c3b/drake/multibody/multibody_tree/math/spatial_vector.h#L138)):*
> ```objc
>   /// w_max_difference | Maximum absolute difference in rotation components
>   /// v_max_difference | Maximum absolute difference in translation components
>   std::tuple<const T, const T> GetMaximumAbsoluteDifferences(
> ```

actually, this documentation does not specify how `w_max_difference` and `v_max_difference` are packed into the tuple. That is, which one goes first and which one is the second? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-:-KxhfyAkQLeAGICXfqbg:bnfp4nl)*

**Comment by mitiguy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/multibody_tree/math/spatial_vector.h, line 138 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7334#-Kxhev4XXSox4DiK1dT2:-KxipHPFy0cDvQDWdWIg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/28d4edf566df7ac84d96814fbb392e2c889a1c3b/drake/multibody/multibody_tree/math/spatial_vector.h#L138)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

actually, this documentation does not specify how `w_max_difference` and `v_max_difference` are packed into the tuple. That is, which one goes first and which one is the second? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7334)*

**Pull request merged**
