### PR TITLE
Remove deprecated code 2023-05

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
(Anzu CI has passed.)

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19307)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
There were many things removed here that weren't obviously marked as deprecated. I'm assuming there was some uber-deprecation that included all of them but just want you to confirm that.

Pending that, :lgtm: x 2

> Reviewed 60 of 60 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19307#-:-NUDC2hJ-gvzgRXPmkvO:b-fdcyrt)* status: needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'm not quite sure what you're referring to.  If you mean the `tools/workspace`, the directory removals there are consistent with `tools/workspace/default.bzl` notating deprecation removals.  In any case, everything here came from grepping for `2023-05-01` and removing the necessary items based on that.

**Review by sherm1 — COMMENTED** [review]
OK. Ready to merge 5/1

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19307#-:-NUDg6X09X3B1Q3lI9T1:b-49axt2)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform)

**Comment by jwnimmer-tri** [comment]
> Ready to merge 5/1

Merging now...

```
$ TZ=Japan date -R
Mon, 01 May 2023 05:49:32 +0900
```

**Pull request merged**
