### PR TITLE
Removes sparse matrix Lemke algorithm implementation routines from Moby solver.

### PR DESCRIPTION
**Pull request by edrumwri**
These routines are not being used in Drake and do not convey much, if any, value: I expect the revised simplex implementation of the Lemke algorithm to suffer from accumulated roundoff error far before a solution could be found on a typical sparse problem size.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8309)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@hongkai-dai for feature review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8309#-:-L76u8dyLa5D3_Rdtqzi:b-8gls7r)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8309#-:-L76vZ1wXmZOHdgM52co:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8309)*

**Comment by edrumwri** [comment]
+@sherm1 for platform review

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8309#-:-L7CMjJOQIfCbV5_-aXT:buasbda)*

**Comment by sherm1** [comment]
:lgtm: -- sweet! I love deleted code.

---

Reviewed 2 of 3 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8309#-:-L7CbtggkXGEedDgmmIX:bk9m541)*

**Pull request merged**
