### PR TITLE
[multibody] Exempt a long test from kcov

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21716)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +(status: single reviewer ok) +@jwnimmer-tri for reviews please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21716#-:-O1r1ctfDC22mWTaaLUb:b1mlegm)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21716)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21716#-O1r8_7z1aRoInAu5nR3:-O1r8_7z1aRoInAu5nR4:bo8w4zm) (no related file):*
Are you _sure_ this test is at fault?  The test finished in 6 seconds, and then kcov apparently sat on its hands for 564 seconds?  Maybe there was a different test eating all of the cpu or disk resources?  It is not immediately obvious to me why a test that takes 6 seconds is long enough to merit exempting.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21716)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21716#-O1r8_7z1aRoInAu5nR3:-O1rSY0F9I7owU1-lnI8:b-bvlmm4) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Are you _sure_ this test is at fault?  The test finished in 6 seconds, and then kcov apparently sat on its hands for 564 seconds?  Maybe there was a different test eating all of the cpu or disk resources?  It is not immediately obvious to me why a test that takes 6 seconds is long enough to merit exempting.
</blockquote></details>

I'll take a closer look.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21716)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21716#-O1r8_7z1aRoInAu5nR3:-O1xuQqn82U5X5EI7oW6:b-mka0ii) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I'll take a closer look.
</blockquote></details>

Indeed, kcov source-annotating is slow. There is maybe a way to split report-writing (slow) from data collection (fast), but it appears to require kcov bug fixes only available in non `apt`ified versions.  I'll close this pr and investigate coverage alternatives.

___

**Pull request closed without merging**
