### PR TITLE
python bindings for MathematicalProgram::AddLinearComplementarityConstraint

### PR DESCRIPTION
**Pull request by pangtao22**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8248)

### CODE REVIEW

**Comment by pangtao22** [comment]
+@ericcousineau-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6rIo8PaaxaV5JxktXT:b-7eskas)*

**Comment by pangtao22** [comment]
+@russtedrake for feature/platform review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6rZi46eoaZiorLVmcI:b-i8ck1y)*

**Comment by pangtao22** [comment]
-@RussTedrake 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6rj2ieyuoIrxQpn2Vu:b-t7mwbl)*

**Comment by RussTedrake** [comment]
the binding looks right, but we need a least one function call to it in the unit tests, just to make sure everything "is spelled right", and stays that way.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8248#-:-L6rvx6Q8UtZpRv88JKi:bqbgp24)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 232 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-L6wIpwCyl0b9x0dlppG:-L6wIpwCyl0b9x0dlppH:b193m4v) ([raw file](https://github.com/robotlocomotion/drake/blob/59c6edaa6ae9e3041e5d85b3f6576dfa732a776d/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L232)):*
> ```Python
>         M.resize(2, 2)
>         q = np.array([-16, -15])
>         prog.AddLinearComplementarityConstraint(M, q, x)
> ```

BTW Can you add a check on the returned binding type, something like:
```
binding = prog.AddLinearComplementarityConstraint(...)
self.assertIsInstance(binding.constraint(), LinearComplementarityConstraint)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6wIlVyUm1j0szodZMj:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 229 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-L6wJ9UbV7B2ER4JCdwV:-L6wJ9UbV7B2ER4JCdwW:b-k1q78) ([raw file](https://github.com/robotlocomotion/drake/blob/59c6edaa6ae9e3041e5d85b3f6576dfa732a776d/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L229)):*
> ```Python
>         prog = mp.MathematicalProgram()
>         x = prog.NewContinuousVariables(2, 'x')
>         M = np.array([1, 4, 3, 1])
> ```

Rather than resizing, can you write this as:
```
M = np.array([[1, 3], [4, 1]])
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248)*

**Comment by pangtao22** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 229 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-L6wJ9UbV7B2ER4JCdwV:-L6wMQ_I26_nZwqVlzXX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59c6edaa6ae9e3041e5d85b3f6576dfa732a776d/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L229)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Rather than resizing, can you write this as:
```
M = np.array([[1, 3], [4, 1]])
```
</blockquote></details>

Done.

---

*[bindings/pydrake/solvers/test/mathematicalprogram_test.py, line 232 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-L6wIpwCyl0b9x0dlppG:-L6wMR1RQrFtBvx2pdqg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59c6edaa6ae9e3041e5d85b3f6576dfa732a776d/bindings/pydrake/solvers/test/mathematicalprogram_test.py#L232)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Can you add a check on the returned binding type, something like:
```
binding = prog.AddLinearComplementarityConstraint(...)
self.assertIsInstance(binding.constraint(), LinearComplementarityConstraint)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248)*

**Comment by pangtao22** [comment]
I accidentally ran clangformat on this python file and messed up the original file. Does Drake have a formatting tool for python files?

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6wZ_q2ZSYaSRSALUyG:b-bjknbj)*

**Comment by EricCousineau-TRI** [comment]
Nope, no automated formatting for `*.py` files. You can use `autopep8` - it will not resolve all formatting issues, but it will take out most of the simple ones.

BTW Depending on which merges first, this PR may have to accommodate https://github.com/RobotLocomotion/drake/pull/8257

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6w__uD8elBvJQXodiH:b-gmc66j)*

**Comment by EricCousineau-TRI** [comment]
* No automated formatting *included with drake*. `autopep8` is available under Ubuntu, or `pip` if you're feeling lucky.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6w_w9gk5x0e3nbs0Tf:b-g96wh8)*

**Comment by pangtao22** [comment]
Thanks Eric! Can I also assign you for platform review? 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8248#-:-L6wevU6ZAWQeju469ki:b-3u759p)*

**Pull request merged**
