### PR TITLE
Convert `maliput::api::RBounds` into a class (from struct)

### PR DESCRIPTION
**Pull request by maddog-tri**
Convert `maliput::api::RBounds` into a class (from struct),
mirroring the API of other entities in `lane_data.h`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6573)

### CODE REVIEW

**Comment by maddog-tri** [comment]
+@liangfok for feature-review, please.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6573#-:-Koxny2ZriRz7KasQFsk:b-gwywvr)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6573#-:-Koy0jJsILAb7mgsYyl9:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6573#-:-Koy2tvcK2UfCwCqL91f:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Pull request merged**
