### PR TITLE
[math] Add tolerance to linear_solve_test Eigen compare

### PR DESCRIPTION
**Pull request by svenevs**
Relates: #18327.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot mac-arm-ventura-clang-bazel-experimental-everything-release please.

**Review by svenevs — COMMENTED** [review]
+@hongkai-dai via #16045 please, see also https://github.com/RobotLocomotion/drake/issues/18327#issuecomment-1535537588

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-:-NUo7aw51pVEKktyA0Jo:b-fq74qr)* status: 1 unresolved discussion, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai and @svenevs)

___
*[`math/test/linear_solve_test.cc` line 110 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-NUo7P5t8_tRp-OEkfFq:-NUo7P5t8_tRp-OEkfFr:bjdgkug) ([raw file](https://github.com/RobotLocomotion/drake/blob/83055dfa009e69dd93f0d8bbbf5d61c7a69ef913/math/test/linear_solve_test.cc#L110)):*
> ```cpp
>     // When T = AutoDiffScalar or double, check if we get the same result as
>     // calling Eigen's linear solver directly.
>     constexpr double kTol = 1.0e-14;
> ```

working, success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //math:linear_solve_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //math:linear_solve_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //math:linear_solve_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/math/linear_solve_test/test.log)
INFO: From Testing //math:linear_solve_test:
==================== Test output for //math:linear_solve_test:
Using drake_cc_googletest_main.cc

[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LinearSolveTest
[ RUN      ] LinearSolveTest.TestDoubleAandb
[       OK ] LinearSolveTest.TestDoubleAandb (0 ms)
[ RUN      ] LinearSolveTest.TestSymbolicAandb
[       OK ] LinearSolveTest.TestSymbolicAandb (0 ms)
[ RUN      ] LinearSolveTest.TestAutoDiffAandDoubleB
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAutoDiffAandDoubleB (0 ms)
[ RUN      ] LinearSolveTest.TestDoubleAandAutoDiffB
math/test/linear_solve_test.cc:136: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestDoubleAandAutoDiffB (0 ms)
[ RUN      ] LinearSolveTest.TestNoGrad
[       OK ] LinearSolveTest.TestNoGrad (0 ms)
[ RUN      ] LinearSolveTest.TestBwithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestBwithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestAwithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAwithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestFixedDerivativeSize
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
math/test/linear_solve_test.cc:136: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestFixedDerivativeSize (1 ms)
[ RUN      ] LinearSolveTest.TestAbWithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAbWithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestAbWithMaybeEmptyGrad
[       OK ] LinearSolveTest.TestAbWithMaybeEmptyGrad (0 ms)
[ RUN      ] LinearSolveTest.TestWrongGradientSize
[       OK ] LinearSolveTest.TestWrongGradientSize (0 ms)
[ RUN      ] LinearSolveTest.GetLinearSolver
[       OK ] LinearSolveTest.GetLinearSolver (0 ms)
[----------] 12 tests from LinearSolveTest (4 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (4 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] LinearSolveTest.TestAutoDiffAandDoubleB
[  FAILED  ] LinearSolveTest.TestDoubleAandAutoDiffB
[  FAILED  ] LinearSolveTest.TestBwithGrad
[  FAILED  ] LinearSolveTest.TestAwithGrad
[  FAILED  ] LinearSolveTest.TestFixedDerivativeSize
[  FAILED  ] LinearSolveTest.TestAbWithGrad

 6 FAILED TESTS
================================================================================
Target //math:linear_solve_test up-to-date:
  bazel-bin/math/linear_solve_test
INFO: Elapsed time: 0.212s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//math:linear_solve_test                                                 FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.
```

**Comment by jwnimmer-tri** [comment]
@hongkai-dai To clarify the procedure: if you're OK with the new tolerance, simple LGTM and we can merge (after platform review).  If you are unhappy with the new tolerance, you can develop an alternative patch and either push it here or open a new PR.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri I think possibly you are also familiar with this test case.  Feel free to steal the review, if it makes sense.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-:-NUrCmI21MyscZuYJmrN:bg7igkv)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform +@jwnimmer-tri.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-:-NUrSSY83T7ZQ5yMqs6c:b-udyqyg)* status: 2 unresolved discussions

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-NUrScKf0Zcg7tgjwmek):*
nit Remove issue number when merging.
___
*[`math/test/linear_solve_test.cc` line 110 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19373#-NUo7P5t8_tRp-OEkfFq:-NUrSkKQBvfbhCi7O_9P:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/83055dfa009e69dd93f0d8bbbf5d61c7a69ef913/math/test/linear_solve_test.cc#L110)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, success criteria is this test passes in CI

```
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //math:linear_solve_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //math:linear_solve_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
FAIL: //math:linear_solve_test (see /private/var/tmp/_bazel_stephen.mcdowell/c82709baf62040b4ad09f16721f3b518/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/math/linear_solve_test/test.log)
INFO: From Testing //math:linear_solve_test:
==================== Test output for //math:linear_solve_test:
Using drake_cc_googletest_main.cc

[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LinearSolveTest
[ RUN      ] LinearSolveTest.TestDoubleAandb
[       OK ] LinearSolveTest.TestDoubleAandb (0 ms)
[ RUN      ] LinearSolveTest.TestSymbolicAandb
[       OK ] LinearSolveTest.TestSymbolicAandb (0 ms)
[ RUN      ] LinearSolveTest.TestAutoDiffAandDoubleB
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAutoDiffAandDoubleB (0 ms)
[ RUN      ] LinearSolveTest.TestDoubleAandAutoDiffB
math/test/linear_solve_test.cc:136: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestDoubleAandAutoDiffB (0 ms)
[ RUN      ] LinearSolveTest.TestNoGrad
[       OK ] LinearSolveTest.TestNoGrad (0 ms)
[ RUN      ] LinearSolveTest.TestBwithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestBwithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestAwithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAwithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestFixedDerivativeSize
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
math/test/linear_solve_test.cc:136: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestFixedDerivativeSize (1 ms)
[ RUN      ] LinearSolveTest.TestAbWithGrad
math/test/linear_solve_test.cc:124: Failure
Value of: CompareMatrices(ExtractValue(x_eigen), ExtractValue(x))
  Actual: false (Values at (1, 2) exceed tolerance: -27.00000000000002 vs. -27.000000000000025, diff = 3.552713678800501e-15, tolerance = 0
m1 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
m2 =
 27.00000000000003  56.00000000000006  89.00000000000009
-8.000000000000009 -17.00000000000001 -27.00000000000002
delta=
                    0                     0                     0
                    0                     0 3.552713678800501e-15)
Expected: true
[  FAILED  ] LinearSolveTest.TestAbWithGrad (0 ms)
[ RUN      ] LinearSolveTest.TestAbWithMaybeEmptyGrad
[       OK ] LinearSolveTest.TestAbWithMaybeEmptyGrad (0 ms)
[ RUN      ] LinearSolveTest.TestWrongGradientSize
[       OK ] LinearSolveTest.TestWrongGradientSize (0 ms)
[ RUN      ] LinearSolveTest.GetLinearSolver
[       OK ] LinearSolveTest.GetLinearSolver (0 ms)
[----------] 12 tests from LinearSolveTest (4 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (4 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] LinearSolveTest.TestAutoDiffAandDoubleB
[  FAILED  ] LinearSolveTest.TestDoubleAandAutoDiffB
[  FAILED  ] LinearSolveTest.TestBwithGrad
[  FAILED  ] LinearSolveTest.TestAwithGrad
[  FAILED  ] LinearSolveTest.TestFixedDerivativeSize
[  FAILED  ] LinearSolveTest.TestAbWithGrad

 6 FAILED TESTS
================================================================================
Target //math:linear_solve_test up-to-date:
  bazel-bin/math/linear_solve_test
INFO: Elapsed time: 0.212s, Critical Path: 0.04s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//math:linear_solve_test                                                 FAILED in 0.0s

Executed 1 out of 1 test: 1 fails locally.
```
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @svenevs from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19373)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Pull request merged**
