### PR TITLE
multibody: Put plotting scripts under test

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Came across this when looking at an Anzu PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13463)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Did minor rebase; merging now.

**Comment by jwnimmer-tri** [comment]
This looks like the kind of thing that will break macOS; `python3` is not on the PATH, in general?

**Comment by EricCousineau-TRI** [comment]
ohhh, good point; will make a potential fix

**Comment by EricCousineau-TRI** [comment]
https://github.com/RobotLocomotion/drake/pull/13468

**Pull request merged**
