### PR TITLE
[doc] Add release notes v1.21.0

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
*[`doc/_release-notes/v1.21.0.md` line 149 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-Ne49dYm1v7PBi8gyIcG:-Ne49dYm1v7PBi8gyIcH:b-uqtjq1) ([raw file](https://github.com/RobotLocomotion/drake/blob/db71835d859131fb7654c6c7f5d7ec09bcf175b0/doc/_release-notes/v1.21.0.md#L149)):*
> ```Markdown
> * Upgrade tinyobjloader_internal to latest commit ([#20148][_#20148])
> * Upgrade to gurobi 10 ([#19766][_#19766])
> * [newly deprecated feature] TBD [workspace,tools,geometry,systems,setup,third_party] [workspace] Use VTK built from source ([#19945][_#19945])  # Drake now uses a custom version of VTK that is compiled from source. Users on macOS (who are not running Drake's unit tests) no longer need the "robotlocomotion/director" tap and may remove it. The following Bazel workspace externals are now deprecated: - double_conversion - glew - liblz4 - liblzma - vtk The repository rules will continue to work during the deprecation window, but Drake no longer installs their Ubuntu packages; if you need the packages, ensure your project setup scripts install them. For CMake users on Ubuntu 20.04 ("Focal"), Drake's source build and pre-compiled binaries no longer provide a copy of VTK 9.1. If you still need Drake's build of VTK 9.1 in your project, you can download it here: - https://drake-packages.csail.mit.edu/vtk/vtk-9.1.0-3-focal-x86_64.tar.gz To avoid ABI/ODR headaches, Drake's VTK build uses a custom namespace and hidden symbols. This is particularly an advantage for wheel builds. During manual testing on macOS, we found that RenderEngineVtk sometimes does not obey show_window=true. It is not clear whether this is a new bug due to the upgrade. Refer to issue 20144 for further discussion.
> ```

@jwnimmer-tri This seems like an important change people might want to pay attention to? Could you provide a snippet to be put in the announcement section?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.21.0.md` line 149 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-Ne49dYm1v7PBi8gyIcG:-Ne5FPo7EVPtzF7vJIGA:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/db71835d859131fb7654c6c7f5d7ec09bcf175b0/doc/_release-notes/v1.21.0.md#L149)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@jwnimmer-tri This seems like an important change people might want to pay attention to? Could you provide a snippet to be put in the announcement section?
</blockquote></details>

Done

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.21.0.md` line 149 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-Ne49dYm1v7PBi8gyIcG:-Ne5MuGpEleReGldjdYm:b-9755fn) ([raw file](https://github.com/RobotLocomotion/drake/blob/db71835d859131fb7654c6c7f5d7ec09bcf175b0/doc/_release-notes/v1.21.0.md#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thank you!

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) 
+@SeanCurtis-TRI +@sammy-tri +@jwnimmer-tri for reviews on the release notes please, thanks.
I'm targeting to release on Thursday 9/14.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-:-NeAHl2f8s0vz1TsovUq:b-34h3t8)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform),sammy-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: 5 unresolved discussions, LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform),SeanCurtis-TRI(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.21.0.md` line 30 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeBDVfE0KcVRCAFpEtz:-NeBDVfF5u1gMbaONFx5:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca9ae1f86ca825097f71d38753e2366adc4013b5/doc/_release-notes/v1.21.0.md#L30)):*
> ```Markdown
> # Breaking changes since v1.20.0
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
* None
```
___
*[`doc/_release-notes/v1.21.0.md` line 45 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeBE0RJEEIQCk8oNn5I:-NeBE0RK4x9asktzKjk-:bipu7l4) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca9ae1f86ca825097f71d38753e2366adc4013b5/doc/_release-notes/v1.21.0.md#L45)):*
> ```Markdown
> 
> * Support default scalars for TrajectorySource ([#19967][_#19967])
> * Add to_string and PixelScalarBoth to be soon used as part of a new consolidated image I/O feature ([#20015][_#20015])
> ```

nit clarity



_Suggestion:_
```Markdown
* Add to_string for Image metadata enums ([#20015][_#20015])
* Add PixelScalar Image metadata enum ([#20015][_#20015])
```
___
*[`doc/_release-notes/v1.21.0.md` line 48 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeBDpRj6Wf1WRRBGTlv:-NeBDpRkDaf8zQ5_tkCH:be9h7b6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca9ae1f86ca825097f71d38753e2366adc4013b5/doc/_release-notes/v1.21.0.md#L48)):*
> ```Markdown
> * Add an initialization event to LcmSubscriberSystem ([#20072][_#20072])
> * Adjust "sole port" getters to work around deprecation ([#20090][_#20090])
> * Simulator.AdvanceTo is interruptible by default ([#20130][_#20130])
> ```

nit 20130 should probably be a pydrake-specific note.  It's only relevant for Python users.
___
*[`doc/_release-notes/v1.21.0.md` line 104 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeBERU5D7brr_ts0Jti:-NeBERU5D7brr_ts0Jtj:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca9ae1f86ca825097f71d38753e2366adc4013b5/doc/_release-notes/v1.21.0.md#L104)):*
> ```Markdown
> Fixes
> 
> * TBD
> ```

nit



_Suggestion:_
```Markdown
* None
```
___
*[`doc/_release-notes/v1.21.0.md` line 120 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeBEZj12ZRiS6kbsIKR:-NeBEZj12ZRiS6kbsIKS:b-dhlrg9) ([raw file](https://github.com/RobotLocomotion/drake/blob/ca9ae1f86ca825097f71d38753e2366adc4013b5/doc/_release-notes/v1.21.0.md#L120)):*
> ```Markdown
> * Fix some awkward grammar in an error message ([#20060][_#20060])
> * Rewrite the DARE solver to use a faster algorithm ([#20104][_#20104])
> * The Meshcat control panel is now resizable ([#20000][_#20000])
> ```

nit 19968 and 20000 are both Meshcat so should both be in the same section.  (I don't mind which section that is.)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-:-NeEgMkiAmkk9OF3D4KW:bnfp4nl)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@jwnimmer-tri could you make another pass at the release notes as we wait for the release builds? Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-:-NeJYZOG8K0fvjw2WUkn:b2kd48e)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-:-NeJ_gsKCYtKEDd2bvSj:bb6ywmx)* status: 1 unresolved discussion, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.21.0.md` line 124 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeJ_Way7GV8k_-gxojB:-NeJ_Way7GV8k_-gxojC:b-ogyxxt) ([raw file](https://github.com/RobotLocomotion/drake/blob/f831e51e73f9a6645c7a340db7ada56a2e4570a2/doc/_release-notes/v1.21.0.md#L124)):*
> ```Markdown
> * The Meshcat control panel is now resizable ([#20000][_#20000])
> * Add RotationMatrix::MakeClosestRotationToIdentityFromUnitZ ([#20107][_#20107])
> * Give the default Variable a name ([#20164][_#20164])
> ```

nit 20164 probably makes more sense in "Mathematical Program"

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`doc/_release-notes/v1.21.0.md` line 124 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-NeJ_Way7GV8k_-gxojB:-NeJaHGiC37z-G7gtr3G:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/f831e51e73f9a6645c7a340db7ada56a2e4570a2/doc/_release-notes/v1.21.0.md#L124)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit 20164 probably makes more sense in "Mathematical Program"
</blockquote></details>

Done, thanks.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134)* status: labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20134#-:-NeJogR_Df8_8Xu_h5qw:bnmvvxy)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Pull request merged**
