### PR TITLE
[multibody] Support .vtk meshes in CalcSpatialInertia()

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20539)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@SeanCurtis-TRI for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-:-NjEVzdl-kPLGH4i760F:b-gpqagm)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth a couple of small nits.

+@EricCousineau-TRI for platform review, please.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-:-NjJWgf74_kbs3a0iU-I:b-faivc2)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`multibody/tree/geometry_spatial_inertia.cc` line 93 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-NjJVyqOEYchm9Fzr6Y_:-NjJVyqOEYchm9Fzr6Ya:b-bl4kjl) ([raw file](https://github.com/RobotLocomotion/drake/blob/5aa03236856f8a3c1233a77dbaf343e352a3415c/multibody/tree/geometry_spatial_inertia.cc#L93)):*
> ```cpp
>     } else {
>       throw std::runtime_error(fmt::format(
>           "CalcSpatialInertia currently only supports .obj or .vtk files for"
> ```

nit: Probably worth emphasizing `tetrahedral .vtk` files (or .vtk files containing tetrahedral meshes).
___
*[`multibody/tree/test/geometry_spatial_inertia_test.cc` line 184 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-NjJWMryEvW5CGG7J0wh:-NjJWMryEvW5CGG7J0wi:b-8y5tjh) ([raw file](https://github.com/RobotLocomotion/drake/blob/5aa03236856f8a3c1233a77dbaf343e352a3415c/multibody/tree/test/geometry_spatial_inertia_test.cc#L184)):*
> ```cpp
>   }
> 
>   {
> ```

nit: I think there should be a note about why all of the remaining tests only use .objs. A piece of rhetoric suggesting why we can take for granted that scale and density also affect the vtk file.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-:-NjJXFvC-ScHxgwLJH9x:bcpz082)* status: 2 unresolved discussions

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20539)* status: 1 unresolved discussion

___
*[`multibody/tree/test/geometry_spatial_inertia_test.cc` line 184 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20539#-NjJWMryEvW5CGG7J0wh:-NjK2Xsn2igp54r-4hTx:b-9yt3sb) ([raw file](https://github.com/RobotLocomotion/drake/blob/5aa03236856f8a3c1233a77dbaf343e352a3415c/multibody/tree/test/geometry_spatial_inertia_test.cc#L184)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I think there should be a note about why all of the remaining tests only use .objs. A piece of rhetoric suggesting why we can take for granted that scale and density also affect the vtk file.
</blockquote></details>

Having re-read the implementation, I think at least scale would benefit from a test.

**Pull request merged**
