### PR TITLE
Change "do not edit" text to try to hint reviewable

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Per Reviewable/Reviewable#73.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3558)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
This seems to work great.  The generated code is shows in the UI as "Generated file: generic marker found", but with a button to read it if you wish.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3558#-:-KSEDxTgkw7uJNJ7pBJ8:bx3gp3n)*

**Comment by jwnimmer-tri** [comment]
This is comment-only changes, so a only platform review is really required.  Seeking any volunteers.

**Comment by liangfok** [comment]
:lgtm:

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3558#-:-KSENlb9cNfB12VQjaZj:bnfp4nl)*

**Comment by david-german-tri** [comment]
+@david-german-tri 

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3558#-:-KSH1AMMxp2daVPSFyDo:bqmdn1l)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3558#-:-KSH1mFtscNnArHuwJMs:bnfp4nl)*

**Pull request merged**
