### PR TITLE
Revert "Defer collision element registration with the collision engine"

### PR DESCRIPTION
**Pull request by jonathan-owens**
Dear @SeanCurtis-TRI ,

The on-call build cop, @jonathan-owens, believes that your PR 4554 may have broken
Drake's continuous integration build [1]. It is possible to break the build
even if your PR passed continuous integration pre-merge, because additional
platforms and tests are built post-merge.

The specific build failures under investigation are:
https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-minimal-release/812/
https://drake-jenkins.csail.mit.edu/job/mac-clang-continuous-minimal-debug/806/

Therefore, the build cop has created this revert PR and started a complete
post-merge build to determine whether your PR was in fact the cause of the
problem. If that build passes, this revert PR will be merged 60 minutes from
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.

If you believe your original PR did not actually break the build, please
explain on this thread.

If you believe you can fix the break promptly in lieu of a revert, please
explain on this thread, and send a PR to the build cop for review ASAP.

If you believe your original PR definitely did break the build and should be
reverted, please review and LGTM this PR. This allows the build cop to merge
without waiting for CI results.

For advice on how to handle a build cop revert, see [2].

Thanks!
Your Friendly Oncall Buildcop

[1] CI Dashboard: https://drake-jenkins.csail.mit.edu/view/Continuous/
[2] http://drake.mit.edu/buildcop.html#workflow-for-handling-a-build-cop-revert

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4689)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Don't merge.  I have a simple fix forward.

**Comment by SeanCurtis-TRI** [comment]
Addressed by #4690

**Comment by SeanCurtis-TRI** [comment]
This can be closed.

**Comment by jamiesnape** [comment]
Yes and no. We fixed the build error, but not the test error.

**Comment by SeanCurtis-TRI** [comment]
Can you provide a link to the test errors?

**Comment by jamiesnape** [comment]
https://drake-cdash.csail.mit.edu/testDetails.php?test=6368872&build=295489 and its friends in the continuous section of https://drake-cdash.csail.mit.edu/index.php?project=Drake.

**Comment by SeanCurtis-TRI** [comment]
Two questions:

1) I also need matlab enabled, right?
2) Is there a quick & dirty way to know before I go down that path that the file is being copied?

**Comment by SeanCurtis-TRI** [comment]
#4695 corrects the `compareParsers` matlab issue and is merged.  *Now* I think we can close this.

**Pull request closed without merging**
