### PR TITLE
Add symbolic::Expression to automotive examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add `symbolic::Expression` to automotive examples.  This replaces `MST` as the fundamental `ScalarType`.

+@soonho-tri for feature review, please.
/CC @david-german-tri @rpoyner-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3912)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please :grimacing:

**Comment by soonho-tri** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV13Rf__hwsWr2wBeh8:-KV13Rf__hwsWr2wBeh9:blchoxg) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/automotive/simple_car.cc#L5)):*
> ```cpp
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/common/symbolic_expression.h"
> #include "drake/common/symbolic_formula.h"
> ```

Is this include `symbolic_formula.h` here because of `bool EvaluateCondition<symbolic::Formula>(const symbolic::Formula&)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/simple_car.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV13Rf__hwsWr2wBeh8:-KV18urbsdscZWXfaE0o:bjursw4) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/automotive/simple_car.cc#L5)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary>
> Is this include `symbolic_formula.h` here because of `bool EvaluateCondition<symbolic::Formula>(const symbolic::Formula&)`?
</details>
Yes, it's so that `const T foo = ...; DRAKE_ASSERT(foo > -M_PI);` works when T is a `symbolic::Expression`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by soonho-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-:-KV19bzMUNgZMtvcJOC4:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-:-KV19ezgs9LGtTK2BAlc:bz1t39v)*

**Comment by sammy-tri** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/simple_car.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1BsjoKCG1p6aUucRr:-KV1BsjpLyNs_u_1gcTg:b-lm3n08) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/automotive/simple_car.cc#L5)):*
> ```cpp
> #include "drake/common/eigen_autodiff_types.h"
> #include "drake/common/symbolic_expression.h"
> #include "drake/common/symbolic_formula.h"
> ```

This include performs non-obvious magic, as it appears unused when reading the file.  Please document/comment.

---

*[drake/common/drake_assert.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1AyrvFG6mLhMi9b1C:-KV1AyrvFG6mLhMi9b1D:b-eiqzbw) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/common/drake_assert.h#L80)):*
> ```objc
> namespace assert {
> template <typename Condition>
> // Allows for specialization of whether Condition can be used as an assertion.
> ```

While I normally don't think it's necessary to comment what code is doing, I think a better explanation of what we're trying to get the compiler to do for us here might be appropriate.

Also document that this is intended as an external API, if that's what the intent is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by jwnimmer-tri** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1O0zo4PSgkauOLF3A:-KV1O0zo4PSgkauOLF3B:b-8e4g39) (no related file):*
So I was naughty and specialized a function template.  I am going to undo that, so DNM for now.

---

*[drake/automotive/simple_car.cc, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1BsjoKCG1p6aUucRr:-KV1Ee9DF9oBGAxxfGcL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/automotive/simple_car.cc#L5)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> This include performs non-obvious magic, as it appears unused when reading the file.  Please document/comment.
</details>
Done.

---

*[drake/common/drake_assert.h, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1AyrvFG6mLhMi9b1C:-KV1FrPMPXBcsXjPSmxU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0615d63543150d349224ec6e878ad04cd46ad62e/drake/common/drake_assert.h#L80)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> While I normally don't think it's necessary to comment what code is doing, I think a better explanation of what we're trying to get the compiler to do for us here might be appropriate.
> 
> Also document that this is intended as an external API, if that's what the intent is.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by sammy-tri** [comment]
:lgtm: pending jenkins

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-:-KV1WWlgSKcSJBymKSMl:b42mpcu)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1O0zo4PSgkauOLF3A:-KV1Wnl4fMZpQLlvX1eP:b-pqhaaj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> So I was naughty and specialized a function template.  I am going to undo that, so DNM for now.
</details>
:lgtm_cancel: I should probably platform review those changes...  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri and @soonho-tri please both PTAL.  Besides the template tricks fixup, I have also added in here compat fixes for TRI downstream users.

---

Review status: 9 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-KV1O0zo4PSgkauOLF3A:-KV2rZ0tCm5Qtc7RyTWY:b-896fix) (no related file):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary>
> :lgtm_cancel: I should probably platform review those changes...  :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-:-KV2rWq8-Uw8qKXJBtHn:b-s7re4d)*

**Comment by rpoyner-tri** [comment]
Reviewed 1 of 13 files at r1, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3912#-:-KV5Z1RiTcKUQcqL-vs_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please :grimacing:

**Pull request merged**
