### PR TITLE
Add in the prerequisites for using the system version of libccd.

### PR DESCRIPTION
**Pull request by clalancette**
Prerequisite of #7371 . @BetsyMcPhail , if you could update the Xenial and Mac images with this, that would be great.  Thanks.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7376)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm: pending CI.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7376#-:-KxnYgGT_ebFGBRN4xu4:bwo9p68)*

**Comment by jamiesnape** [comment]
+@sammy-tri for platform review.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7376#-:-KxndK1Vy5DYnkawbBWs:bnfp4nl)*

**Comment by BetsyMcPhail** [comment]
The Xenial and Mac images have been updated.

Note: It takes awhile for Jenkins to cycle through any existing Xenial images and use the updated one.

**Pull request merged**
