### PR TITLE
Add doxygen suppressions for _EXPORT goop

### LINKED ISSUE #2177: Export preprocessor symbols should be excluded from Doxygen
Drake's build system generates Microsoft export macros like `DRAKEUTIL_EXPORT` to force symbols to be visible in `.dll` shared libraries. Doxygen dutifully includes these ugly and meaningless things in the generated documentation. They should not be included.

Normally special macro handling is done by modifying `Doxyfile` which has provision for doxygen-specific macro expansion or elimination. That would be hard to do nicely with build-time generated export symbols. However, the symbols could exclude themselves from Doxygen in the generated export files using a symbol that is only present when Doxygen is running (doxygen manual suggests `DOXYGEN_SHOULD_SKIP_THIS`; see the `PREDEFINED` keyword for Doxyfile).

FYI, code can be skipped at point of use with
```
/** @cond **/ 
Doxygen won't see this.
/** @endcond **/
```
(The space after `@cond` is required for some reason.) So this works but is awkward:
```/** @cond **/ DRAKEUTIL_EXPORT /** @endcond **/```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #2177.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2994)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@mwoehlke-kitware for feature review, please.
@sherm1 for platform review, please.

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by sherm1** [comment]
Great! Thanks, @jwnimmer-tri -- this was badly needed. Platform: :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-:-KNxF0QBhyF37lICbDBK:426907462)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO67MXtk0tcAXFMe_iK:-1301244607) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
> ```
>   DRAKEXMLUTIL_EXPORT= \
>   DRAKEYAMLUTIL_EXPORT= \
>   DRAKEZMPUTIL_EXPORT=
> ```

Whee! Would it not be easier to add the directory with the export headers to `INCLUDE_PATH`? (Or does that make ugly documentation?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO682HJbUod8RpogZM9:896288159) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Whee! Would it not be easier to add the directory with the export headers to `INCLUDE_PATH`? (Or does that make ugly documentation?)
</details>
I am not quite sure what you're getting at.

The intent of this change was to remove the `FOO_EXPORT` ornaments from the generated HTML documentation, per #2177.  I'm not sure how a path edit would address that?  Would the thought be that the `#include` statements for the `FOO_EXPORT` would resolve the token to be nothing (because we're not on windows?), and thus `MACRO_EXPANSION` would take care of them?  But it seems like `EXPAND_ONLY_PREDEF` is a really good idea when `MACRO_EXPANSION` is on, so we'd have to list them all out anyway?  I'm not sure where that leaves us.

Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO6AWJvChfoWVwsr0vL:525343414) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I am not quite sure what you're getting at.
> 
> The intent of this change was to remove the `FOO_EXPORT` ornaments from the generated HTML documentation, per #2177.  I'm not sure how a path edit would address that?  Would the thought be that the `#include` statements for the `FOO_EXPORT` would resolve the token to be nothing (because we're not on windows?), and thus `MACRO_EXPANSION` would take care of them?  But it seems like `EXPAND_ONLY_PREDEF` is a really good idea when `MACRO_EXPANSION` is on, so we'd have to list them all out anyway?  I'm not sure where that leaves us.
> 
> Please clarify.
</details>
Right now the doc includes e.g. `DRAKECOMMON_EXPORT`, presumably because it is missing a definition of `DRAKECOMMON_EXPORT`. Obviously, this is ugly.

I am wondering, if doxygen saw (and expanded) the definition of `DRAKECOMMON_EXPORT`, would it still be ugly? If not, this would have the advantage of not needing to list every export symbol. (But on second thought, it would require expanding *all* non-function macros, which may or may not be desired.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO6D6DrcV_ieVagJCC-:-1004295633) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
>  (But on second thought, it would require expanding all non-function macros, which may or may not be desired.)

Right.  The expand-all seemed like a bad idea to me, though admittedly I didn't try running it to find out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by mwoehlke-kitware** [comment]
:LGTM: with the caveat that I didn't test it locally.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO6DTvNLHdomT3m4NbG:250380040) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> >  (But on second thought, it would require expanding all non-function macros, which may or may not be desired.)
> 
> Right.  The expand-all seemed like a bad idea to me, though admittedly I didn't try running it to find out.
</details>
Fair enough. My original question was just that: a question, not a request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-:-KO6Dic6gioJAMeGgPKH:-1962441321)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/Doxyfile_CXX.in, line 326 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2994#-KO67MXtk0tcAXFMe_iJ:-KO6Lnwkbgl9V5Gqqqpi:842759727) ([raw file](https://github.com/robotlocomotion/drake/blob/81a2c88b6c096662fe86343c65868c9f7e12304f/drake/doc/Doxyfile_CXX.in#L326)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Fair enough. My original question was just that: a question, not a request.
</details>
Surely.  I wanted to make sure I understood it, and definitely wanted your input as someone who had set up this Doxygen for us.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2994)*

**Comment by jwnimmer-tri** [comment]
I tested this locally to good effect (at least, I spot-tested a few classes to make sure the goop was gone).

**Pull request merged**
