### PR TITLE
[doc] Add release notes v1.9.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@svenevs for review of the installation documentation changes, please.  (In other words, all of the docs changes other than the release notes themselves.)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for review of the Python changes, please (`relnotes.py`).

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 6 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 3 unresolved discussions, LGTM missing from assignees rpoyner-tri(platform),svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`doc/_pages/from_binary.md` line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo6YVQCdguUE7fwUrP:-NDo6YVQCdguUE7fwUrQ:b-se3acn) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_binary.md#L38)):*
> ```Markdown
> * [https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-jammy.tar.gz](https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-jammy.tar.gz)
> * [https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-mac.tar.gz](https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-mac.tar.gz) (for x86_64)
> * [https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-mac-arm64.tar.gz](https://github.com/RobotLocomotion/drake/releases/download/v1.9.0/drake-YYYYMMDD-mac-arm64.tar.gz) (for arm64)
> ```

Blocking until we have a date to double check final urls.
___
*[`doc/_pages/from_binary.md` line 51 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo7187EJtkZWUQvS33:-NDo7187EJtkZWUQvS34:by4j4pt) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_binary.md#L51)):*
> ```Markdown
> In most cases, we suggest using our [pip releases](/pip.html), because that
> will be more convenient than manually downloading.  However, if you are running
> on macOS arm64 or if you need both
> ```

Nit: add comma after `arm64`?
___
*[`doc/_pages/from_source.md` line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo9bqh02tTHu_fTArw:-NDo9bqh02tTHu_fTArx:b-asn23r) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_source.md#L27)):*
> ```Markdown
> native arm64 mode when building from source. However, to use Drake's
> pre-compiled binaries, refer to [Running under Rosetta 2](/rosetta2.html) for
> instructions on running using x86_64 emulation.
> ```

This table needs to update and the footnote `(1)` go away, right?

If so, grepping for `rosetta` I think that page can be deleted from the website?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: relnotes.py

> Reviewed 1 of 1 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053#-:-NDoOJkAEAgh2loaHTsG:b-e0n7q8)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @svenevs)

___
*[`doc/_pages/from_binary.md` line 51 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo7187EJtkZWUQvS33:-NDpiSxzESaqbQX3glZq:bqaitb8) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_binary.md#L51)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Nit: add comma after `arm64`?
</blockquote></details>

My eyeballs say better to omit it.
___
*[`doc/_pages/from_source.md` line 27 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo9bqh02tTHu_fTArw:-NDpiYpP642w4kpT6gLy:b-aldjp3) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_source.md#L27)):*
> This table needs to update and the footnote (1) go away, right?

Wow, facepalm.  I must have gotten interrupted while I was working on this.  Fixed now.

> If so, grepping for rosetta I think that page can be deleted from the website?

My plan was to leave it intact (for anyone who bookmarked it) but positively affirm the _new_ situation that rosetta is no longer needed.  But I _also_ forgot to do that.  Fixed now.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @svenevs)

___
*[`doc/_pages/from_binary.md` line 38 at r4](https://reviewable.io/reviews/robotlocomotion/drake/18053#-NDo6YVQCdguUE7fwUrP:-NDx5nrJEnjWSR1PfeNA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9e0a35b8d182429fe1d67865b009cc8a2ac8a50/doc/_pages/from_binary.md#L38)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Blocking until we have a date to double check final urls.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 6 files at r2, 1 of 3 files at r3, 5 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri and @svenevs)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 6 files at r2, 2 of 3 files at r3, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053#-:-NE1-gFADB8Xu12KOY_p:bmxilld)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @svenevs)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @svenevs)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 6 files at r2, 1 of 3 files at r3, 6 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @svenevs)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r2, 1 of 3 files at r3, 4 of 7 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18053#-:-NE1aba--Fmwt6OM8Se7:bnfp4nl)* status: 2 unresolved discussions, LGTM missing from assignee svenevs, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @svenevs)

**Pull request merged**
