### PR TITLE
rendering_py: Add PoseVector. Enable by-value casting for geometric arguments.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Provides `Pose` as a prereq for #7918.

\cc @jadecastro 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7948)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please (if you have time).
+@sammy-tri for platform review, please (since I am on the schedule for Monday).

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4ORBpwLRarPiE6scOu:b-ihoa9m)*

**Comment by jwnimmer-tri** [comment]
Checkpoint.  I'm saving the template stuff until I have a clear head and some coffee tomorrow.

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/systems/framework_py.cc, line 437 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OlS-PBuZQ5yUF4CR-:-L4OlS-PBuZQ5yUF4CR0:b-x94hhf) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/systems/framework_py.cc#L437)):*
> ```cpp
>     .def(py::init<int>())
>     .def("Clone", &BasicVector<T>::Clone)
>     .def("__copy__", &BasicVector<T>::Clone)
> ```

FYI I guess these two are pretty heavily used anyway so problems are unlikely to go unnoticed, but do you want a small direct unit test for them at all?

---

*[bindings/pydrake/systems/test/rendering_test.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OmA3y-nSse5kY1Mlu:-L4OmA3y-nSse5kY1Mlv:b7ofc6o) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/systems/test/rendering_test.py#L1)):*
> ```Python
> # -*- coding: utf8 -*-
> ```

_META_ These make my emacs yell at me when I save, with a https://www.emacswiki.org/emacs/ChangingEncodings warning from MULE.  It wants me to spell it `utf-8`, which python seems to be OK with and seems more standard.

---

*[bindings/pydrake/util/eigen_pybind.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OkjuA1AXgGCnMpYvS:-L4OkjuBD0STqQIOiSot:b-8e4x8b) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_pybind.h#L6)):*
> ```objc
> #include <pybind11/eigen.h>
> 
> #include "drake/bindings/pydrake/util/eigen_geometry_pybind.h"
> ```

Unclear why this include is needed here.  Add a comment?

(If its a "convenience" include then that's usually a defect.  It if needs to be here for correctness, document why.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4Xx2Fif2SkGFdLT54I:b-uxk1ae)*

**Comment by jwnimmer-tri** [comment]
Sorry for the delay, this took me a while to ramp up into.  First pass complete.

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b708Iep7SP-eBPyOF:-L4b708Iep7SP-eBPyOG:b-w0xikq) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L4)):*
> ```objc
> 
> /// @file
> /// Provides pybind11 type casters for Eigen geometric types.
> ```

BTW `type_caster` not `type caster` -- since we mean a specific API, not the general idea.

FYI A link to http://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html might also help the reader.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bAZjY1uf1X06qOb90:-L4bAZjY1uf1X06qOb91:b-29m3c) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L14)):*
> ```objc
> 
> namespace pybind11 {
> namespace detail {
> ```

I understand that the `type_caster<>` specializations need to appear in this namespace, but also putting our helper glue into it seems defective.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bCPwin7b5h4xCL1T7:-L4bCPwin7b5h4xCL1T8:bjrq83s) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L51)):*
> ```objc
>         (policy == return_value_policy::reference ||
>          policy == return_value_policy::reference_internal)) {
>       // @note `_(...)` is pybind secret sauce for constexpr strings.
> ```

When I first read this PR, I thought that the `_` constexpr string stuff was required for compatibility with pybind APIs.  That doesn't seem like the case, though?  If I'm reading correctly and this is just intra-Drake code, I see no reason to make developers learn an obscure new syntax when C++'s existing mechanisms should be sufficient.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bBIGatDGGoQfzWNzs:-L4bBIGatDGGoQfzWNzt:bx06k3i) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L61)):*
> ```objc
> 
>  private:
>   Type value_;
> ```

FYI Per Drake cppguide it would be discretionary, but consider initializing this member to a valid value, instead of leaving it be Eigen garbage.  While in inner-loop C++ code there's some argument for allowing authors to choose garbage (and then we have the `-san` builds to catch it), I feel like for pydrake its a fairly dangerous precedent (we don't have `-san` tools, for example).

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b4uGi0fI7C0RFEs-m:-L4b4uGi0fI7C0RFEs-n:b-rdru3s) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L64)):*
> ```objc
> };
> 
> // Wrapper for Transform<>.
> ```

FYI This sentence, and `Wrapper` in particular, doesn't really help me understand what's happening.  (There are enough wrappers around, like 7841, that it can be murky.)  I think "This struct is intended to be used as the first argument of `drake_wrap_caster`." or something would have helped me.  (Of course, after reading the whole PR a few times the intention here seems obvious, but on first read I had trouble finding my bearings.)

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b5rNxdVXM_l7A90PT:-L4b5rNxdVXM_l7A90PU:b-qkew0c) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L76)):*
> ```objc
>     return src.matrix();
>   }
>   Type value;
> ```

I'm having trouble seeing where this gets used.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b95JEMdEQ1UXuRxws:-L4b95JEMdEQ1UXuRxwt:b603joi) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L103)):*
> ```objc
> 
> // Wrapper for Quaternion<>.
> // Eigen stores the quaternion in `(xyz, w)`, but Drake wants `(w, xyz)`.
> ```

Providing undesignated wxyz coordinate wrapping seems to me like we're pointing the shotgun at users' feet.  My current believe is that any pydrake glue for Eigen::Quaternion is defective unless it provides meaningful names to the coordinates, either via the method name, kwargs, or similar.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b8fJPce60mvKFiyCD:-L4b8fJQN6qBN7BO1zCo:b-tddge7) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L111)):*
> ```objc
>   static Type unwrap(const WrappedType& wxyz) {
>     Type out;
>     out.coeffs() << wxyz.tail(3), wxyz(0);
> ```

Its not obvious to me why normalization is being accounted for here in a way that's consistent with conventional Eigen use and/or pydrake's users' and/or C++ users' expectations.  (Perhaps just adding some documentation here is enough.)

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bAA-NfQ8wwh2-y8MH:-L4bAA-OwRv2ivFFQWS4:b-qkew0c) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L119)):*
> ```objc
>     return wxyz;
>   }
>   Type value;
> ```

I'm having trouble seeing where this gets used.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b89QzQ3_qepa8bq0d:-L4b89QzQ3_qepa8bq0e:btmex1g) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L127)):*
> ```objc
> 
> }  // namespace detail
> }  // namespace pybind11
> ```

The correctness of the implementations in this file are not obviously straightforward, and so deserve acute unit testing with an eigengeometry-specific unit test, not just relying on the rendering test indirectly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4bDF-iCIRE9qrlCpVu:b-za9xxu)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 17 files reviewed at latest revision, 13 unresolved discussions.

---

*[bindings/pydrake/systems/framework_py.cc, line 437 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OlS-PBuZQ5yUF4CR-:-L4d0anFQjH9knbahi_O:bkujn9e) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/systems/framework_py.cc#L437)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I guess these two are pretty heavily used anyway so problems are unlikely to go unnoticed, but do you want a small direct unit test for them at all?
</blockquote></details>

Done. Added to `value_test`.

---

*[bindings/pydrake/systems/test/rendering_test.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OmA3y-nSse5kY1Mlu:-L4d0fGSbu6T_EI7f1U-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/systems/test/rendering_test.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_META_ These make my emacs yell at me when I save, with a https://www.emacswiki.org/emacs/ChangingEncodings warning from MULE.  It wants me to spell it `utf-8`, which python seems to be OK with and seems more standard.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b708Iep7SP-eBPyOF:-L4d0li3h3ojvGXbTtQ2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L4)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `type_caster` not `type caster` -- since we mean a specific API, not the general idea.

FYI A link to http://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html might also help the reader.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bAZjY1uf1X06qOb90:-L4d0m5VrOL5It3tBNSP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I understand that the `type_caster<>` specializations need to appear in this namespace, but also putting our helper glue into it seems defective.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bBIGatDGGoQfzWNzs:-L4d0nV3i6aiOPVAgDmT:b86vrdb) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Per Drake cppguide it would be discretionary, but consider initializing this member to a valid value, instead of leaving it be Eigen garbage.  While in inner-loop C++ code there's some argument for allowing authors to choose garbage (and then we have the `-san` builds to catch it), I feel like for pydrake its a fairly dangerous precedent (we don't have `-san` tools, for example).
</blockquote></details>

Done. I'd prefer not to specialize initialization, so I've added `loaded_` as a guard.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b4uGi0fI7C0RFEs-m:-L4d0tOuaJhoNnXIZs2n:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This sentence, and `Wrapper` in particular, doesn't really help me understand what's happening.  (There are enough wrappers around, like 7841, that it can be murky.)  I think "This struct is intended to be used as the first argument of `drake_wrap_caster`." or something would have helped me.  (Of course, after reading the whole PR a few times the intention here seems obvious, but on first read I had trouble finding my bearings.)
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b5rNxdVXM_l7A90PT:-L4d0twgYB8pYfszUxTF:b-gijhng) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm having trouble seeing where this gets used.
</blockquote></details>

Done. Removed (first just that line, then more as I wanted to get more out of `Quaternion` and `Isometry3`).

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 103 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b95JEMdEQ1UXuRxws:-L4d0zl0V1oBQqvqzJRM:b-8mk9i6) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Providing undesignated wxyz coordinate wrapping seems to me like we're pointing the shotgun at users' feet.  My current believe is that any pydrake glue for Eigen::Quaternion is defective unless it provides meaningful names to the coordinates, either via the method name, kwargs, or similar.
</blockquote></details>

Done. Binding entire class as we do with `AutoDiffXd`.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bAA-NfQ8wwh2-y8MH:-L4d14hujCA-qxSMyDar:b-wnfmk9) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm having trouble seeing where this gets used.
</blockquote></details>

Done. Removed.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 127 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b89QzQ3_qepa8bq0d:-L4d16-pm9ljVWqshcQp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L127)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The correctness of the implementations in this file are not obviously straightforward, and so deserve acute unit testing with an eigengeometry-specific unit test, not just relying on the rendering test indirectly.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_pybind.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4OkjuA1AXgGCnMpYvS:-L4d18tXQ_tTCiB10pax:b2gp3bx) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_pybind.h#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear why this include is needed here.  Add a comment?

(If its a "convenience" include then that's usually a defect.  It if needs to be here for correctness, document why.)
</blockquote></details>

Done. Was a defect (for convenience).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bindings/pydrake/all.py, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d5d04M1AbIwhWuJ45:-L4d5d04M1AbIwhWuJ46:b-k1hihs) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/all.py#L36)):*
> ```Python
> from .systems.all import *
> # - Do not include `third_party`.
> from .util.all import *
> ```

FYI I guess "Do not include" did not mean "It would be wrong to include" but rather "Intentionally omitted" or "Doesn't offer any public classes" or something?  If so, consider rephrasing the remaining uses (here or elsewhere) to draw that distinction.

---

*[bindings/pydrake/systems/framework_py.cc, line 442 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d5HJ8MSc55MN4b3sZ:-L4d5HJ8MSc55MN4b3s_:b-my16mo) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/systems/framework_py.cc#L442)):*
> ```cpp
>     // N.B. Place `init<VectorX<T>>` `init<int>` so that we do not implicitly
>     // convert scalar-size `np.array` objects to `int` (since this is normally
>     // permitted).
> ```

BTW This comment indentation seems wrong now?  (Maybe move it to follow the `basic_vector` line?)

---

*[bindings/pydrake/test/all_test.py, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dBxVNXF4GGBujJFQr:-L4dBxVNXF4GGBujJFQs:b5pt8a2) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/test/all_test.py#L35)):*
> ```Python
>             "Simulator",
>             # util
>             "Quaternion",
> ```

BTW `Isometry3` should be here?

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d8wTmN4Vc44BjZlsQ:-L4d8wTmN4Vc44BjZlsR:b-nn53qe) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L36)):*
> ```cpp
>       identity_error < kCheckTolerance &&
>       "Rotation matrix is not orthonormal");
>   const T det_error = fabs(R.determinant() - 1);
> ```

Missing include (and `std::` qualifier or `using`) for `fabs`.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d8D_22jWotadZediz:-L4d8D_22jWotadZedj-:b-xwx6q1) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L61)):*
> ```cpp
>       "Quaternion is not normalized");
> }
> ```

BTW Should the above (including the kConst) be in the anonymous namespace?  I would think so, but don't know if pybind is adding special requirements.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dAPZuqY9mDyHz2uaY:-L4dAPZuqY9mDyHz2uaZ:bxy9gw2) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_pybind.h#L37)):*
> ```objc
>   // Python to C++.
>   bool load(py::handle src, bool converter) {
>     Wrapper::init();
> ```

The `init` isn't mentioned in the class (struct) overview, and also doesn't seem to be doing anything.

---

*[bindings/pydrake/util/test/eigen_geometry_test_util_py.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dEcL6CZP7-g-lQ9-s:-L4dEcL6CZP7-g-lQ9-t:b-cg7pk9) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/test/eigen_geometry_test_util_py.cc#L16)):*
> ```cpp
> namespace pydrake {
> 
> const double kTolerance = 1e-8;
> ```

BTW Prefer anonymous or static?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4dFGP4gCaA2Q-h_KMG:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[bindings/pydrake/all.py, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d5d04M1AbIwhWuJ45:-L4dU3taqIQt61NTtP8O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/all.py#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I guess "Do not include" did not mean "It would be wrong to include" but rather "Intentionally omitted" or "Doesn't offer any public classes" or something?  If so, consider rephrasing the remaining uses (here or elsewhere) to draw that distinction.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/framework_py.cc, line 442 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d5HJ8MSc55MN4b3sZ:-L4dU5RF88x5CMRjIJ5M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/systems/framework_py.cc#L442)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This comment indentation seems wrong now?  (Maybe move it to follow the `basic_vector` line?)
</blockquote></details>

Done.

---

*[bindings/pydrake/test/all_test.py, line 35 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dBxVNXF4GGBujJFQr:-L4dU7Hjnl2u9rU1_Q05:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/test/all_test.py#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW `Isometry3` should be here?
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d8wTmN4Vc44BjZlsQ:-L4dU99f6D2GMxjIDdRB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Missing include (and `std::` qualifier or `using`) for `fabs`.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 61 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d8D_22jWotadZediz:-L4dUAv8jWpjwg21EX9H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L61)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should the above (including the kConst) be in the anonymous namespace?  I would think so, but don't know if pybind is adding special requirements.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 51 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4bCPwin7b5h4xCL1T7:-L4dUECUHtJgu0A9CyZY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L51)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I first read this PR, I thought that the `_` constexpr string stuff was required for compatibility with pybind APIs.  That doesn't seem like the case, though?  If I'm reading correctly and this is just intra-Drake code, I see no reason to make developers learn an obscure new syntax when C++'s existing mechanisms should be sufficient.
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 111 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4b8fJPce60mvKFiyCD:-L4dUFmJvbysuzSIAJ2Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0aa4f19588e270647b47d012054ef31b0a10b20e/bindings/pydrake/util/eigen_geometry_pybind.h#L111)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Its not obvious to me why normalization is being accounted for here in a way that's consistent with conventional Eigen use and/or pydrake's users' and/or C++ users' expectations.  (Perhaps just adding some documentation here is enough.)
</blockquote></details>

Done.

---

*[bindings/pydrake/util/eigen_geometry_pybind.h, line 37 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dAPZuqY9mDyHz2uaY:-L4dUBzaaMDBhwdvjCWm:b-m42umv) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_pybind.h#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `init` isn't mentioned in the class (struct) overview, and also doesn't seem to be doing anything.
</blockquote></details>

Done. (Was vestigial)

---

*[bindings/pydrake/util/test/eigen_geometry_test_util_py.cc, line 16 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4dEcL6CZP7-g-lQ9-s:-L4dUHuQzHOLdsbQ8Zgj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/test/eigen_geometry_test_util_py.cc#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Prefer anonymous or static?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948)*

**Comment by jwnimmer-tri** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 36 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-L4d8wTmN4Vc44BjZlsQ:-L4dYyc-bmB9t6pXjW2G:b-yp7i41) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW Still missing `std::` (for this location; the other one got it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948)*

**Comment by EricCousineau-TRI** [comment]
Review status: 13 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/util/eigen_geometry_py.cc, line 36 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/7948#-L4d8wTmN4Vc44BjZlsQ:-L4fw0AcEbUmTDbd-NEI:bu9g4k6) ([raw file](https://github.com/robotlocomotion/drake/blob/fa0468e633ea5705fb2be4971fbc986ce5ea83ff/bindings/pydrake/util/eigen_geometry_py.cc#L36)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Still missing `std::` (for this location; the other one got it).
</blockquote></details>

Done. Thanks for catching that!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/7948)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948)*

**Comment by sammy-tri** [comment]
Still working through my first pass -- so far, so good.  I suspect I may not finish until tomorrow (apologies!)

---

Reviewed 6 of 18 files at r2, 3 of 7 files at r3, 3 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4hDhckFXEs0Q5BG6GM:bnmr3y8)*

**Comment by sammy-tri** [comment]
:lgtm: (though I'm going to admit I did not fully understand the weedier pybind bits)

---

Reviewed 4 of 18 files at r2, 1 of 7 files at r3, 2 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7948#-:-L4lRCUybGSFvbvpsg-b:bxtfs9)*

**Pull request merged**
