### PR TITLE
doc: Fix 29 nits on new Jekyll website

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
To the moon!

Towards #14695.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14737)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews, please.

\CC @avalenzu @SeanCurtis-TRI @hongkai-dai

**Review by ggould-tri — COMMENTED** [review]
:lgtm: ; one possible mis-badging noted below.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14737#-:-MUxQW9F-Q4h9QnJVlHL:bjkgiw2)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14737#-MUxP9a388RyUnvkd9ZO:-MUxLSjy8jnNMPmCgCXK:b-r6mt23) (no related file):*
You rocket-shipped Sean's 

    Under Python - Additional Rules.
    The footnote on "Executable Python files should be limited..." is a live link in sphinx, but not in Jekyll.
 
but this does not actually appear to be fixed in this PR or listed as TODO.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14737)* status: 1 unresolved discussion (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14737#-MUxP9a388RyUnvkd9ZO:-MUxlp0T3qcQ7GykbUIT:bkl72wi) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

You rocket-shipped Sean's 

    Under Python - Additional Rules.
    The footnote on "Executable Python files should be limited..." is a live link in sphinx, but not in Jekyll.
 
but this does not actually appear to be fixed in this PR or listed as TODO.
</blockquote></details>

I converted the footnote into a parenthetical, I think?

---

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14737)* status: :shipit: complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14737#-MUxP9a388RyUnvkd9ZO:-MUxmfpkB70Em5bNxu6A:b-uw5lq6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I converted the footnote into a parenthetical, I think?
</blockquote></details>

Ah, I misinterpreted.

---

**Pull request merged**
