### PR TITLE
Renamed "number_of_foo()" to be "get_num_foo()". 

### LINKED ISSUE #3549: Rename RigidBodyTree::get_number_of_foo() to be RigidBodyTree:get_num_foo()
Our style guide explicitly allows for the "num" abbreviation:

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

This rename should happen to be consistent with the usage of "num" in `RigidBodyPlant`.

### PR DESCRIPTION
**Pull request by liangfok**
I also included some miscellaneous style guide fixes. Old methods were kept but marked deprecated meaning downstream code should still continue to build and work.

Resolves #3549.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3566)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/4934/. I'm now going to add a CHANGELOG.

---

Review status: 0 of 76 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSJmaV242kwyQJmtfAo:b-fs8d6x)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-ros please.

**Comment by liangfok** [comment]
This PR passed:

* https://drake-jenkins.csail.mit.edu/job/experimental/4935/
* https://drake-jenkins.csail.mit.edu/job/linux-gcc-experimental-matlab-ros/36/

Thus:

+@amcastro-tri for feature review, please.
+@ggould-tri for platform review, please.

---

Review status: 0 of 77 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSK1THojQpkzdrGv3Yy:bbarryg)*

**Comment by amcastro-tri** [comment]
I didn't look at each of the 77 files but I trust this is just a refactor and I do agree it makes sense. Therefore :lgtm: 

---

Reviewed 9 of 77 files at r1.
Review status: 9 of 77 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSNDVizkq4MU4pJf_0u:-KSNDVizkq4MU4pJf_0v:bla1c3j) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodyTree.h#L153)):*
> ```objc
>   DRAKE_DEPRECATED("Please use get_num_model_instances().")
> #endif
>   int get_number_of_model_instances();
> ```

BTW, Does it make any sense to deprecate a method that probably didn't even find any new users? I would just remove it completely with this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSNEXwUi8ZtVQL1NBa7:b-xmlrpo)*

**Comment by liangfok** [comment]
Thanks. Now waiting on a platform review from @ggould-tri .

---

Review status: 9 of 77 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.h, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSNDVizkq4MU4pJf_0u:-KSNQYq-q1l2fY86z4aa:b-ft2xip) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodyTree.h#L153)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, Does it make any sense to deprecate a method that probably didn't even find any new users? I would just remove it completely with this PR.
</details>
This is done in an abundance of caution since we don't know what downstream code is using. I don't think it hurts to keep it since it's clearly marked deprecated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSNQU2xNX89xDuWHHLI:b-m0ojym)*

**Comment by ggould-tri** [comment]
Some 'considers' and a bad indent.  :lgtm: pending open discussion.

---

Reviewed 76 of 77 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaqaFPeDnpdg5OVqxv:-KSaqaFQ5vjvppVuCQ0X:b-z0dobi) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodySystem.cpp#L74)):*
> ```cpp
> }
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> ```

BTW - consider `DRAKE_DEPRECTATED(...)` here.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaqf99bTwoRWYZuxOe:-KSaqf99bTwoRWYZuxOf:b-z0dobi) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodySystem.cpp#L83)):*
> ```cpp
> }
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> ```

BTW - consider `DRAKE_DEPRECTATED(...)` here.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSarNt-_IkbVW0jG-Cl:-KSarNt-_IkbVW0jG-Cm:b20xmss) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodyTree.cpp#L2118)):*
> ```cpp
> }
> 
> // TODO(liang.fok) Remove this method prior to Release 1.0.
> ```

BTW - consider `DRAKE_DEPRECATED(...)` here.

---

*[drake/systems/plants/test/compareParsersmex.cpp, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaquu0kQzgrlCL77UG:-KSaquu0kQzgrlCL77UH:b-cpheu) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/test/compareParsersmex.cpp#L60)):*
> ```cpp
>       MatrixXd::Zero(cpp_model->get_num_positions(),
>                      matlab_model->get_num_positions());  // projection from
>                                                             // the coordinates
> ```

Indention here is now wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSasgWOgtHOLHkA0yvg:bk3w5mp)*

**Comment by liangfok** [comment]
@ggould-tri, I addressed your comments. PTAL. Thanks.

---

Review status: 74 of 77 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 74 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaqaFPeDnpdg5OVqxv:-KSayvaD_8lhWY36cLzw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodySystem.cpp#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW - consider `DRAKE_DEPRECTATED(...)` here.
</details>
Done.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 83 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaqf99bTwoRWYZuxOe:-KSaz0zPsKwQHWE2tc48:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodySystem.cpp#L83)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW - consider `DRAKE_DEPRECTATED(...)` here.
</details>
Done.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2118 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSarNt-_IkbVW0jG-Cl:-KSaz6zbfRMAYfmm-o_q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/RigidBodyTree.cpp#L2118)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW - consider `DRAKE_DEPRECATED(...)` here.
</details>
Done.

---

*[drake/systems/plants/test/compareParsersmex.cpp, line 60 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSaquu0kQzgrlCL77UG:-KSazMOtVb2bmVOmRcNI:b-a1aov) ([raw file](https://github.com/robotlocomotion/drake/blob/33e010559637836ced46082bf1d172c4b1400841/drake/systems/plants/test/compareParsersmex.cpp#L60)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Indention here is now wrong.
</details>
Done. I also fixed the grammar per style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSb-T0mtkQh2q1G_ujV:b-2kq3ds)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by ggould-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566)*

**Comment by ggould-tri** [comment]
Still LGTM, just discovered and noted that you can delete a few unnecessary lines if you like; see below.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbyrBBqQxiM_n2S4Rt:-KSbyrBBqQxiM_n2S4Ru:b-b8rlno) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L75)):*
> ```cpp
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> #ifndef SWIG
> ```

FYI -- I just noticed `DRAKE_DEPRECATED` already has an `#ifndef SWIG` that disables it.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbz7Vsf29ASTUMzGAq:-KSbz7Vsf29ASTUMzGAr:b-b8rlno) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L87)):*
> ```cpp
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> #ifndef SWIG
> ```

FYI -- I just noticed `DRAKE_DEPRECATED` already has an `#ifndef SWIG` that disables it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSbzANB8rgermglWwqK:bu2qlql)*

**Comment by jwnimmer-tri** [comment]
*[drake/systems/plants/RigidBodySystem.cpp, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbyrBBqQxiM_n2S4Rt:-KSbzukHjz_16bhkzvjP:b1jr5zn) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L75)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I just noticed `DRAKE_DEPRECATED` already has an `#ifndef SWIG` that disables it.
</details>
But swig is special, and doesn't play by your silly preprocessor rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbyrBBqQxiM_n2S4Rt:-KSc-EnfRHu11-G8Bw5j:bq5svir) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> But swig is special, and doesn't play by your silly preprocessor rules.
</details>
Yeah. We unfortunately need `#ifndef SWIG` outside of the macro too:

https://reviewable.io/reviews/robotlocomotion/drake/2597#-KKyshnUyy05WVVvAuQd

---

*[drake/systems/plants/RigidBodySystem.cpp, line 87 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbz7Vsf29ASTUMzGAq:-KSc0SlyBpvycsoaPMlC:bbx87r0) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L87)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- I just noticed `DRAKE_DEPRECATED` already has an `#ifndef SWIG` that disables it.
</details>
See comment above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566)*

**Comment by liangfok** [comment]
@jwnimmer-tri: The Windows 32 CI error is a known flake. Can you override merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSc0lLqBy2xZq6mF-d6:bd0ezpg)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/plants/RigidBodySystem.cpp, line 75 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-KSbyrBBqQxiM_n2S4Rt:-KSc4IxYu7_1hdkUka7S:bb75bp9) ([raw file](https://github.com/robotlocomotion/drake/blob/4fef93102e9c91fe112092c7c23c4d63c7d71905/drake/systems/plants/RigidBodySystem.cpp#L75)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yeah. We unfortunately need `#ifndef SWIG` outside of the macro too:
> 
> https://reviewable.io/reviews/robotlocomotion/drake/2597#-KKyshnUyy05WVVvAuQd
</details>
Ugh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566)*

**Comment by liangfok** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please.
@drake-jenkins-bot linux-gcc-experimental-ros please.

**Comment by ggould-tri** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566)*

**Comment by liangfok** [comment]
@jwnimmer-tri, can you override merge this PR? The latest CI suffered a known Windows flake (#2798).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3566#-:-KSgEaB2LfFr1SQWh6Io:b-pdphci)*

**Comment by jwnimmer-tri** [comment]
But has the most recent revision passed CI at some point in the past?  I am not seeing it in the history.  If a rebuild passes, we can override.

@drake-jenkins-bot windows-msvc-ninja-32-experimental please

**Comment by liangfok** [comment]
I was thinking https://drake-jenkins.csail.mit.edu/job/experimental/5064/ showed the PR passing all tests.

**Comment by jwnimmer-tri** [comment]
That (5064) build doesn't have any windows results, though, does it?  What it has a compilation error on windows, would we have seen it yet?

**Comment by liangfok** [comment]
I see. You're right. I just scrolled to the bottom of the console log and saw the following typical error:

```

08:52:16 Slave went offline during the build
08:52:16 ERROR: Connection was broken: java.io.IOException: Pipe closed
08:52:16 	at java.io.PipedInputStream.read(PipedInputStream.java:308)
08:52:16 	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
08:52:16 	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:73)
08:52:16 	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
08:52:16 	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
08:52:16 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
08:52:16 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
08:52:16 
```

Since this passed https://drake-jenkins.csail.mit.edu/job/windows-msvc-ninja-32-experimental/9/, are we good to merge now?

**Comment by jwnimmer-tri** [comment]
Yes, just needed to confirm that one.  Using override-merge due to earlier windows flake.

**Pull request merged**
