### PR TITLE
Add GCC 4.8 compatibility shim for make_unique

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3793)

### CODE REVIEW

**Comment by sherm1** [comment]
Consider a one-stop-shopping common.h?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_assert.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3793#-KTw4I1WZ37nwA69kqeI:-KTw4I1WZ37nwA69kqeJ:b-rosghj) ([raw file](https://github.com/robotlocomotion/drake/blob/d3fe61cbf9a65b76216c593572e7291f12afd9dc/drake/common/drake_assert.h#L6)):*
> ```objc
> 
> #include "drake/common/drake_export.h"
> #include "drake/common/drake_gcc48.h"
> ```

Rather than sneaking this into commonly-included headers, consider adding a `drake/common/common.h` that should be included in all drake-using code. Initially it would just include `drake_gcc48.h` but we could use it for other drake boilerplate later, or include some other ubiquitous headers like `constants.h`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3793#-:-KTw6JIUjh9ifGhicy12:b-c24d6j)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_assert.h, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3793#-KTw4I1WZ37nwA69kqeI:-KTyOtQrp7lVIH8-Moxi:b-u5dxx3) ([raw file](https://github.com/robotlocomotion/drake/blob/d3fe61cbf9a65b76216c593572e7291f12afd9dc/drake/common/drake_assert.h#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Rather than sneaking this into commonly-included headers, consider adding a `drake/common/common.h` that should be included in all drake-using code. Initially it would just include `drake_gcc48.h` but we could use it for other drake boilerplate later, or include some other ubiquitous headers like `constants.h`.
</details>
I can't quite perceive a future need that would merit that approach?

I disagree that things like `constants.h` should magically appear in everyone's translation unit automatically, and I am not sure about any other boilerplate that we would need?

I am also unclear whether you mean `common.h` would replace these four cases, or instead that we insist all ~700 files in Drake add an include for `common.h` (which I would call `bottom.h` -- bottom of the dependency graph)?

I _could_ add a layer of indirection here, where these `#include`s turned into `#include "drake/common/bottom.h" and `bottom.h` just included `gcc48.h` for now, but I don't see the point?  That's easy to do later, and I'd rather just do the smallest thing that works here, because I intend to revert this PR in about three months, when I can drop support for GCC 4.8.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3793)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3793)*

**Comment by jwnimmer-tri** [comment]
-@jwnimmer-tri +@ggould-tri for both reviews, please (it's _almost_ Friday, eh?).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3793#-:-KTz50kdSu7QqJxZqba7:b-jr8rca)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3793#-:-KU2NFZzS7CAjZsMgt5A:bnfp4nl)*

**Pull request merged**
