### PR TITLE
Enforce file naming and folder structure in //geometry/render/dev

### PR DESCRIPTION
**Pull request by zachfang**
- Move all the files into `geometry/render/dev/render_gltf_client` folder. Thus each file will simply be moved to `geometry/render/render_gltf_client` correspondingly for the platform review.
- Rename files to `factory.{cc, h}` and `internal_*.{cc, h}`.
- Change the namespace of the internal classes from `geometry::render::internal` to `geometry::render_gltf_client::internal`.
- Change the namespace of the gltf_client factory method and the params struct from `geometry::render` to `geometry`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16936)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for review, thanks!

cc @svenevs

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16936#-:-N-TMnM_4W30O9YG7Ex8:b-axkma4)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TLHmcBGL7kTeyDTH-:-N-TLHmcBGL7kTeyDTH0:b-tju5bc) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h#L67)):*
> ```objc
>   `image_type` and `scene_id`.  The returned path is constructed as
>   `{RenderClient::temp_directory()}/{scene_id}-{image_type}.gltf`. */
>   std::string ExportPathFor(geometry::render::internal::ImageType image_type,
> ```

This is the part I am not sure. Should we duplicate the ImageType definition under `geometry::render_gltf_client::internal` as `RenderEngineGltfClient` and `RenderEngineVtk` are in different namespaces now.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TLueJ6R_oos5O7dJ_:-N-TLueJ6R_oos5O7dJa:bk0m4s0) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L44)):*
> ```cpp
>  */
> DEFINE_string(camera_xyz_rpy, "0.8, 0.0, 0.5, -2.2, 0.0, 1.57",
>               "Sets the camera pose by xyz (meters) and rpy (radians) values.");
> ```

FYI, most of the changes in this file are due to reformatting using clang. Will mark the actual changes in the following comments. 
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TM8zmCdOmKGNtsX01:-N-TM8zmCdOmKGNtsX02:b-q7x4b7) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L64)):*
> ```cpp
> namespace drake {
> namespace geometry {
> namespace render_gltf_client {
> ```

FYI, change the namespace.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 104 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TMDglC6s7pYbRGI_d:-N-TMDglC6s7pYbRGI_e:b9yt29a) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L104)):*
> ```cpp
> 
> using Eigen::Vector3d;
> using geometry::render::ColorRenderCamera;
> ```

FYI, add using-declaration because of the namespace change.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 185 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TMJ_H-juz_mMrH7vE:-N-TMJ_H-juz_mMrH7vF:b-owq577) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L185)):*
> ```cpp
>   const SourceId source_id = scene_graph->RegisterSource("main");
>   const std::string texture_path = FindResourceOrThrow(
>       "drake/geometry/render/dev/render_gltf_client/test/4_color_texture.png");
> ```

FYI, change due to folder structure change.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 276 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TMUZN7_XGwvIdYOhx:-N-TMUZN7_XGwvIdYOhy:bfbd7hl) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L276)):*
> ```cpp
>   if (FLAGS_render_engine == "vtk") {
>     scene_graph->AddRenderer(render_name,
>                              geometry::render::MakeRenderEngineVtk(
> ```

FYI, specifying the namespace because of the namespace change.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 420 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TMir3BQ2vD25bJYhM:-N-TMir3BQ2vD25bJYhN:bfbd7hl) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L420)):*
> ```cpp
> int main(int argc, char* argv[]) {
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
>   return drake::geometry::render_gltf_client::minimal_example::do_main();
> ```

FYI, specifying the namespace because of the namespace change.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16936#-:-N-TTirx6l6-fWA-XbYE:bnfp4nl)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @zachfang)

___
*[geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TLHmcBGL7kTeyDTH-:-N-TTXU62IPi_dpzPELT:b-348i29) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h#L67)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

This is the part I am not sure. Should we duplicate the ImageType definition under `geometry::render_gltf_client::internal` as `RenderEngineGltfClient` and `RenderEngineVtk` are in different namespaces now.
</blockquote></details>

I don't see any problem with the current code.  It's perfectly valid for directories _within Drake itself_ to access code in "internal" namespace from another folder.  The "internal" is relative to Drake as a whole, not just that one folder.  Does that help clarify?
___
*[geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TUSOR7DdPPOSa_qK4:-N-TUSOR7DdPPOSa_qK5:b-9j2kfw) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc#L62)):*
> ```cpp
> namespace {
> 
> namespace fs = drake::filesystem;
> ```

nit This is redundant with line 27.
___
*[geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TTrmQ4NimLeiazs7Z:-N-TTrmR1dmJrha48V-9:b1iwoqe) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc#L48)):*
> ```cpp
> 
>   // RenderEngineGltfClient private method access.
>   std::string ExportPathFor(geometry::render::internal::ImageType image_type,
> ```

nit This `...ImageType` typename is kind of awkwardly long here.  WDYT about adding a `using` statement for it atop the file?

...

Oh, we already have one, it's just down on line 83 where it's useless here.  Those `using` lines down there can all move up higher in the file, and then keep the short typename here
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TSk2OBCf5V2s7GkVC:-N-TSk2P90Ojf6L6DZpm:b-ajm7pl) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L65)):*
> ```cpp
> namespace geometry {
> namespace render_gltf_client {
> namespace minimal_example {
> ```

We can't make up namespaces out of thin air.  A namespace needs to be either a directory name, or "internal".  Probably just removing this namespace entirely is the easiest fix.

https://drake.mit.edu/styleguide/cppguide.html#Namespaces



_Code quote:_
```cpp
minimal_example
```
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TRobHB9k7rJlzWb7_:-N-TRobHB9k7rJlzWb7a:b95en5t) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L190)):*
> ```cpp
>   int label_value = 0;
> 
>   const Box box(0.1, 0.075, 0.05);
> ```

The whitespace formatting changes to the `MakeInstance` calls from here through around line 260 are a significant detriment to readability.  The prior code had a consistent indentation that was easy to skim.

Broadly speaking, when the auto-formatter makes a bad decision, we can either ignore it (by rejecting its suggestion) or else we can rewrite the code so that it auto-formats in a readable way (e.g., by factoring sub-expressions into named local variables, or adding comments to force line breaks, or adding helper sugar functions, or etc.).

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16936)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h, line 67 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TLHmcBGL7kTeyDTH-:-N-TqkRCASTVCvmlkSn8:b-78smiw) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h#L67)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

`ImageType` should not be duplicated, it needs to be identical for `RenderEngineVtk` and `RenderEngineGltfClient` (to access `actors_`).  This will need to update in the future when the [other render engines](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1646937427862689) eventually get moved to their own folders / namespaces.  For now it seems fine to me, the alternative I see is moving the `ImageType` enum inside of the `RenderEngineVtk` class itself (at `protected` scope, like how we have `RenderingPipeline`).  I don't think that needs to block this PR though and could be done separately, that'll incur a couple of updates across files.
</blockquote></details>

OK. Thanks for the clarification.
Will revisit when we shuffle other renderer implementations around. 
___
*[geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TTrmQ4NimLeiazs7Z:-N-TrCyf2sgjlRySGllV:b-12fes5) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This `...ImageType` typename is kind of awkwardly long here.  WDYT about adding a `using` statement for it atop the file?

...

Oh, we already have one, it's just down on line 83 where it's useless here.  Those `using` lines down there can all move up higher in the file, and then keep the short typename here
</blockquote></details>

Done. Moved the using-declaration up so that they can be leveraged from both the Tester class and unit tests.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TSk2OBCf5V2s7GkVC:-N-TrQG4BM7GHjiFUfGt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We can't make up namespaces out of thin air.  A namespace needs to be either a directory name, or "internal".  Probably just removing this namespace entirely is the easiest fix.

https://drake.mit.edu/styleguide/cppguide.html#Namespaces
</blockquote></details>

Done.
___
*[geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc, line 190 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16936#-N-TRobHB9k7rJlzWb7_:-N-TrR1UA6CMNYbYNhpq:b-7g4en2) ([raw file](https://github.com/robotlocomotion/drake/blob/37aab3cb28e44c77b6aeb59d8e904237dfdc42fb/geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc#L190)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The whitespace formatting changes to the `MakeInstance` calls from here through around line 260 are a significant detriment to readability.  The prior code had a consistent indentation that was easy to skim.

Broadly speaking, when the auto-formatter makes a bad decision, we can either ignore it (by rejecting its suggestion) or else we can rewrite the code so that it auto-formats in a readable way (e.g., by factoring sub-expressions into named local variables, or adding comments to force line breaks, or adding helper sugar functions, or etc.).
</blockquote></details>

Done. Reverted some of the reformattings, especially the `MakeInstance` function.

**Comment by jwnimmer-tri** [comment]
FYI you don't need to force-push and burn an extra CI spin.  You or your reviewer (me) can squash-and-merge once CI (on the multiple commits) finished.  It was only a minute or so away.

**Comment by zachfang** [comment]
Oh sorry, noted!

**Pull request merged**
