### PR TITLE
[workspace] Upgrade googlebenchmark to latest release v1.8.0

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #19511.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri could you please investigate here and see if you can push a fix for the new warnings?  It looks to me like we're misusing the benchmark API a little bit, somehow.

**Review by rpoyner-tri — COMMENTED** [review]
:eyes: started looking last night. Will return when other platform review is cleared up.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-:-NXGSJ0_2-AJdO0mJkT-:bwrx56n)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
I composed some fixes that would apply to this branch rebased to newer master; I'm failing to see what is preventing the fixes to be cherry-picked to the pr branch. If you would like me to cherry-pick my patch onto this branch, could you please rebase? if not, I can drop a diff text somewhere.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-:-NXH2aNo67Zd1KqQh2Zk:b-4t33nt)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-NXH3CjiCJ-vS5zViB8h:-NXH3CjiCJ-vS5zViB8i:b-nlezd) (no related file):*
My fixes, as applied to this branch rebased to newer master.

In one case (Stop()) it looks like a (deprecated?) virtual overload got removed. In another (DoNotOptimize()), a free-function overload (const-ref template arg) got deprecated, and we have to assign function results to local values to avoid the poisoned overload signature.

```
From 07a40411208546f25fa3b7b09e88abd76fa55109 Mon Sep 17 00:00:00 2001
From: Rick Poyner <rick.poyner@tri.global>
Date: Tue, 6 Jun 2023 11:32:42 -0400
Subject: [PATCH] wip: fix compile errors

---
 multibody/benchmarking/position_constraint.cc | 12 ++++++++----
 tools/performance/fixture_memory_yes.cc       |  2 +-
 2 files changed, 9 insertions(+), 5 deletions(-)

diff --git a/multibody/benchmarking/position_constraint.cc b/multibody/benchmarking/position_constraint.cc
index 9d9061a95a..d4ba1320e8 100644
--- a/multibody/benchmarking/position_constraint.cc
+++ b/multibody/benchmarking/position_constraint.cc
@@ -95,8 +95,10 @@ BENCHMARK_F(IiwaPositionConstraintFixture, EvalAutoDiffMbpDouble)
     VectorX<AutoDiffXd> q_autodiff = math::InitializeAutoDiff(q_);
     AutoDiffVecXd y_autodiff;
     constraint_->Eval(q_autodiff, &y_autodiff);
-    benchmark::DoNotOptimize(math::ExtractValue(y_autodiff));
-    benchmark::DoNotOptimize(math::ExtractGradient(y_autodiff));
+    VectorXd value;
+    benchmark::DoNotOptimize(value = math::ExtractValue(y_autodiff));
+    MatrixXd gradient;
+    benchmark::DoNotOptimize(gradient = math::ExtractGradient(y_autodiff));
   }
 }
 
@@ -110,8 +112,10 @@ BENCHMARK_F(IiwaPositionConstraintFixture, EvalAutoDiffMbpAutoDiff)
     VectorX<AutoDiffXd> q_autodiff = math::InitializeAutoDiff(q_);
     AutoDiffVecXd y_autodiff;
     ad_constraint_->Eval(q_autodiff, &y_autodiff);
-    benchmark::DoNotOptimize(math::ExtractValue(y_autodiff));
-    benchmark::DoNotOptimize(math::ExtractGradient(y_autodiff));
+    VectorXd value;
+    benchmark::DoNotOptimize(value = math::ExtractValue(y_autodiff));
+    MatrixXd gradient;
+    benchmark::DoNotOptimize(gradient = math::ExtractGradient(y_autodiff));
   }
 }
 
diff --git a/tools/performance/fixture_memory_yes.cc b/tools/performance/fixture_memory_yes.cc
index 90335041c6..2866d42799 100644
--- a/tools/performance/fixture_memory_yes.cc
+++ b/tools/performance/fixture_memory_yes.cc
@@ -28,7 +28,7 @@ class GlibcMemoryManager final : public MemoryManager {
   GlibcMemoryManager() = default;
 
   void Start() final { Tare(); }
-  void Stop(Result* result) final;
+  void Stop(Result* result);
   void Stop(Result& result) final { this->Stop(&result); }  // NOLINT
 
   // Resets all counters back to zero.
-- 
2.34.1

```

___

**Review by rpoyner-tri — COMMENTED** [review]
Forced rebase and added fixes. 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-:-NXHBJQ5-f5LZRNXk356:b-tzk1a)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) +@jwnimmer-tri for both reviews.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-:-NXHNxcg4wZSGHW-unBp:b-cunuh9)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19537#-:-NXHQZqTCxVPFJ995DWY:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

**Pull request merged**
