### PR TITLE
[C-IRIS] Consolidate to the formulation using Chebyshev center for polytope

### PR DESCRIPTION
**Pull request by hongkai-dai**
If I were to use the formulation that doesn't introduce Chebyshev, namely a'*x + b >= 1, then this causes problem in the bilinear iteration. Since when we search for the separating margin, we use the formulation a'*x + b - margin - lambda(s) * (d - C*s) is sos. Then in the next iteration when we search for C and d, we don't need the margin and use the formulation a'*x + b - 1 - lambda(s) * (d-C*s) is sos. This causes the problem that the solution a, b, lambda in the first iteration with margin is NOT a feasible solution for the next iteration when we search for C and d but fix lambda(s) (as very likely the margin is < 1).

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496#-:-NKHIeud5T2dnKB3zM4V:b-kengf8)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Two things to consider.
1) Is there any reason to make the separating margin optional now? It may simplify to just remove the option all together
2) Is there a way to make the multiple `0.5` in `0.5r` a named constant? It might be less brittle this way.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496#-:-NKJWP4WDsdfccMLaYIc:b7hnx7c)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Currently I still like to keep the separating margin optional. For the polytope case, when we have the separating margin, the constraint is
```
a.dot(p_AV) + b >= margin
a.dot(p_AC) + b >= 0.5 * radius
|a| <= 1
```
When we don't have the margin, the constraint is
```
a.dot(p_AV) +  b >= 0
a.dot(p_AC + b >= 0.5 * radius
```
The major difference is that when we have the margin, we introduce the constraint `|a|<=1`, which leads to a matrix-sos constraint.

> Is there a way to make the multiple 0.5 in 0.5r a named constant? It might be less brittle this way.

Done, I added a named constant.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496#-:-NKJonazAArY_0W2SZ6-:b4q8dlh)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496#-:-NKJqLsj3uq8VwxA3oDI:bnfp4nl)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18496#-NKJqARx45D41Ofx_A3W:-NKJqARx45D41Ofx_A3X:bgc44ms) ([raw file](https://github.com/robotlocomotion/drake/blob/6daadf6fdcedf8a42e54cd0991534f9ff1ba7cde/geometry/optimization/dev/collision_geometry.cc#L113)):*
> ```cpp
>   //   aᵀ*p_AC+b ≤ -k*r
>   // where C is the Chebyshev center of the polytope, and r is the distance
>   // from C to the polytope boundary. k is a positive scalar between (0.5 in
> ```

nit: `k is a positive scalar in (0,1), defined in PolytopeChebyshevRadiusMultiplier`

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18496#-:-NKK9A9qAz7gXnSBi6eJ:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
