### PR TITLE
solvers: Add python bindings for DrealSolver

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15215)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please
+@soonho-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15215#-:-MceNYM_6OBrKLqbn4md:bkz28bw)* status: LGTM missing from assignees hongkai-dai,soonho-tri(platform) (waiting on @hongkai-dai and @soonho-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15215#-:-MceS9vB5qWHZ-TwHsii:bg7igkv)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot retest this please.

retest the PR since #15214 just got merged.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15215)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @RussTedrake)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15215#-:-McfTss1C27QeuErpd-8:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
