### PR TITLE
Fix a failure on Mac on penetration test.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fix the mac CI failure https://drake-cdash.csail.mit.edu/test/80036322

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  mac-catalina-clang-bazel-continuous-experimental please

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot  mac-catalina-clang-bazel-experimental-release please.

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406#-:-MN_XW532KZFYcnqNjO6:b3qx5dq)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: +(status: single reviewer ok) 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406#-:-MN__Baf44pVxAuV-_61:b-b5dc06)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MN__FQLAiCm2T5pUfm6:b-rjlj2b) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
> ```cpp
>       EXPECT_TRUE(
>           CompareMatrices(math::autoDiffToValueMatrix(first_result.p_WCb),
>                           point_pairs_double[0].p_WCb, kEps));
> ```

BTW I probably would have put this on all of the `CompareMatrices` calls, but CI is already running and we'd like to unbreak the mac builds, so I won't insist on it.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @hongkai-dai)

___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MN_iLBpBySqPPPXf4P2:b-aul61z) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
At the top of this section is the note (emphasis mine):

>  Make sure that callback with T=AutoDiffXd and T=double produces the __*same*__ result.

I don't know why this is failing on mac, but we should do more than just paper over it. Could you post an issue and put a TODO on this test with that issue? I certainly wouldn't expect *any* deviation between the actual *value*...the fact that an epsilon is required is *very* disturbing.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MN_slCM0N9rYIcShDPP:b-8t2ext) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

At the top of this section is the note (emphasis mine):

>  Make sure that callback with T=AutoDiffXd and T=double produces the __*same*__ result.

I don't know why this is failing on mac, but we should do more than just paper over it. Could you post an issue and put a TODO on this test with that issue? I certainly wouldn't expect *any* deviation between the actual *value*...the fact that an epsilon is required is *very* disturbing.
</blockquote></details>

Agreed it is very disturbing. I just added a TODO here. I will investigate it after the PR is merged.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @sammy-tri)

___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MN_xLmO9PIIeOl7ysI2:b-c7xrpp) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Agreed it is very disturbing. I just added a TODO here. I will investigate it after the PR is merged.
</blockquote></details>

I'm not bothered by the need for a machine epsilon here (if I've interpreted kEps correctly). That's because the additional operations _surrounding_ the value computation in the AD case affect what optimizations the compiler will perform and that affects order of operations which affects roundoff accumulation. Consider e.g. the limitation on the number of registers that can be used at once. Usability of fused-multiply-and-add instructions can also have this effect even without reordering because there is just one roundoff error introduced for the two operations.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14406)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MNaDNRM2E8qpZbDm39V:bzcnemt) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm not bothered by the need for a machine epsilon here (if I've interpreted kEps correctly). That's because the additional operations _surrounding_ the value computation in the AD case affect what optimizations the compiler will perform and that affects order of operations which affects roundoff accumulation. Consider e.g. the limitation on the number of registers that can be used at once. Usability of fused-multiply-and-add instructions can also have this effect even without reordering because there is just one roundoff error introduced for the two operations.
</blockquote></details>

Thanks Sherm for the explanation. I didn't know this before. I removed the TODO.

**Comment by SeanCurtis-TRI** [comment]
___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MNasvr06SwsAyKtjUGw:b2dy7sl) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Thanks Sherm for the explanation. I didn't know this before. I removed the TODO.
</blockquote></details>

I don't believe we can reason about machine epsilon quite so cavalierly. 

1. Surely it depends on the scale of the values being compared. What if the values are orders of magnitude smaller than 1, then the error can't simply be attributed to round-off error due to order of operations (or at least trivial re-ordering).
2. By placing the epsilon here, we have no sense of whether the epsilon was necessary for all shapes, or just to address one shape in particular.
3. Given we test *multiple* quantities for bit-identical equality, this is the *only* value that requires epsilon. Your argument would be more meaningful if we had to spread it around a bit more.
4. Given that we get the expected, bit-identical performance across two different compilers on Linux, understanding why Mac (which ostensibly uses one of our compilers) is different is worthwhile.

**Comment by sherm1** [comment]
___
*[geometry/proximity/test/penetration_as_point_pair_callback_test.cc, line 254 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14406#-MN__FQLAiCm2T5pUfm5:-MNdPXFe7DuIUA0gtfj7:b-lq3u4r) ([raw file](https://github.com/robotlocomotion/drake/blob/b6454abe5cbb384f1a60256cbaeba1d2c5820f66/geometry/proximity/test/penetration_as_point_pair_callback_test.cc#L254)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't believe we can reason about machine epsilon quite so cavalierly. 

1. Surely it depends on the scale of the values being compared. What if the values are orders of magnitude smaller than 1, then the error can't simply be attributed to round-off error due to order of operations (or at least trivial re-ordering).
2. By placing the epsilon here, we have no sense of whether the epsilon was necessary for all shapes, or just to address one shape in particular.
3. Given we test *multiple* quantities for bit-identical equality, this is the *only* value that requires epsilon. Your argument would be more meaningful if we had to spread it around a bit more.
4. Given that we get the expected, bit-identical performance across two different compilers on Linux, understanding why Mac (which ostensibly uses one of our compilers) is different is worthwhile.
</blockquote></details>

To your point 1: whether the test uses relative or absolute tolerance is important if the problem is badly scaled, I agree. Here the test is just doing absolute tolerance, appropriate for values near 1. The fact that it passes with just 2e-16 suggests it is well scaled.

2,3,4: There is no guarantee of bit-identical results from mathematically-equivalent but reordered floating point instructions. Nice that the other tests happened to match exactly but IMO that's just luck and is somewhat misleading -- compilers are free to make small changes that could result in different roundoff results. Past performance is no guarantee of future results.

It would be fun to track down exactly why the computation differed here but I don't think the behavior _requires_ an investigation. It would if you could argue that the instruction sequence _must_ be the same, e.g. two calls to the same non-inlined function with bit-identical arguments.

**Pull request merged**
