### PR TITLE
Replace sin/cos in a symbolic polynomial with half-angle rational functions

### PR DESCRIPTION
**Pull request by hongkai-dai**
This is the first step to introduce C_Iris into Drake.

cc @AlexandreAmice

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N65zmGNEhKEg3BZZhAh:b-835t8)* status: LGTM missing from assignee RussTedrake(platform), missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[`multibody/dev/c_iris/rational_forward_kinematics.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N68VbgAAUqCZQpiYMiV:-N68VbgAAUqCZQpiYMiW:b-my2kx7) ([raw file](https://github.com/robotlocomotion/drake/blob/e6cedea531e724ec3a284e89c315735a9750ae5e/multibody/dev/c_iris/rational_forward_kinematics.h#L1)):*
> ```objc
> #pragma once
> ```

I don't think this method needs to live in a `dev` folder (i would put it in or near `symbolic_trignometric_polynomial.h`)?  It seems generally useful, already covered with tests, and we would only be adding work down the road to move it?
___
*[`multibody/dev/c_iris/rational_forward_kinematics.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N68Uq2n-oWu9oOkWOeO:-N68Uq2n-oWu9oOkWOeP:bxksv84) ([raw file](https://github.com/robotlocomotion/drake/blob/e6cedea531e724ec3a284e89c315735a9750ae5e/multibody/dev/c_iris/rational_forward_kinematics.h#L19)):*
> ```objc
>  * @param[out] e_rational The rational polynomial of e after replacement.
>  */
> void ReplaceCosAndSinWithRationalFunction(
> ```

this is great!  but can we make the API closer to https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1symbolic.html#a6639ded5e13e34eee457b3ceb92a1d62 ?  For instance, using SinCos.  We should be building up a common library of these conversions, and I feel we are in danger of having lots of fragments.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @hongkai-dai and @RussTedrake)

___
*[`multibody/dev/c_iris/rational_forward_kinematics.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N68Uq2n-oWu9oOkWOeO:-N6FGhJ55m5fHoTpczB-:bq68pbb) ([raw file](https://github.com/robotlocomotion/drake/blob/e6cedea531e724ec3a284e89c315735a9750ae5e/multibody/dev/c_iris/rational_forward_kinematics.h#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this is great!  but can we make the API closer to https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1symbolic.html#a6639ded5e13e34eee457b3ceb92a1d62 ?  For instance, using SinCos.  We should be building up a common library of these conversions, and I feel we are in danger of having lots of fragments.
</blockquote></details>

Thanks! I think there are some difference from this function with the rest of `Substitute`

The input / output of this function are symbolic::Polynomial / symbolic::RationalFunction, while the input/output of Substitute function are symbolic::Expression. In a sense this function works for a much narrower type of expressions, namely only the multilinear polynomials (where each monomial can contain either cos(θᵢ) or sin(θᵢ), but not both, or any higher degrees of cos or sin). I could change the API to
   ```cc
   Expression Substitute(const Expression& e, const SinCosSubstitution& subs);
   ```
   but the problem is that it is harder to re-construct the symbolic rational function out from the returned symbolic::Expression. I somehow prefer to working with symbolic::Polynomial/RationalFunction rather than symbolic::Expression, because there are a lot more structure in Polynomial class.

What do you think if I use this API
```cc
symbolic::RationalFunction SubstituteMultilinear(const symbolic::Polynomial& e, const std::unordered_map<Variable, Variable>& subs);
```
where `subs` has the map `θ => t`. This function substitute cosθ with (1-t^2)/(1+t^2), and sinθ with 2t/(1+t^2). It has a different name compared to the other `Substitute` function to emphasize the special requirement on the input `e`.

**Review by hongkai-dai — COMMENTED** [review]
I didn't add python binding in this PR because `symbolic::RationalFunction` doesn't have a python binding yet. I will add the python binding in separate PRs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6JxHjrCU9KphEN5zyO:b-v3qhyq)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`multibody/dev/c_iris/rational_forward_kinematics.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N68VbgAAUqCZQpiYMiV:-N6JxFqXEc5WWCiBPrCz:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/e6cedea531e724ec3a284e89c315735a9750ae5e/multibody/dev/c_iris/rational_forward_kinematics.h#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't think this method needs to live in a `dev` folder (i would put it in or near `symbolic_trignometric_polynomial.h`)?  It seems generally useful, already covered with tests, and we would only be adding work down the road to move it?
</blockquote></details>

Done. Good call.
___
*[`multibody/dev/c_iris/rational_forward_kinematics.h` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N68Uq2n-oWu9oOkWOeO:-N6JxB8u6cmD6o2ii2I8:b-sws6gn) ([raw file](https://github.com/robotlocomotion/drake/blob/e6cedea531e724ec3a284e89c315735a9750ae5e/multibody/dev/c_iris/rational_forward_kinematics.h#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

FTR -- we do already have `Substitute` for `symbolic::Polynomial`, too, not just `Expression`.  And many of the substitute methods throw if the substitution cannot be accomplished.

I don't think Multilinear is a good name here, especially if the argument is theta (it's not multilinear in the thetas).

Perhaps 
```
symbolic::RationalFunction SubstituteCosAndSinWithRationalFunction(const symbolic::Polynomial& e, const std::unordered_map<Variable, Variable>& subs);
```
is more clear?  If `Substitute` is the prefix, then at least it will appear when I type Substitute in the doxygen search bar...

But maybe I'd be most happy with `SubstituteStereographicProjection`?  To do see the appeal of just calling it `StereographicProjection`, but really do think the Substitute prefix will help discoverability.  WDYT?
</blockquote></details>

Done. I renamed the function to `SubstituteStereographicProjection`.

**Review by RussTedrake — COMMENTED** [review]
one small question.. (and you have some test failures)

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6KAnGl5ScN4U_EkbE9:bhpp0ja)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[`common/symbolic_trigonometric_polynomial.h` line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9CVz0m5BtTZiXBGr:-N6K9CVz0m5BtTZiXBGs:b-si6bjd) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L102)):*
> ```objc
> [[nodiscard]] symbolic::RationalFunction SubstituteStereographicProjection(
>     const symbolic::Polynomial& e, const VectorX<symbolic::Variable>& cos_vars,
>     const VectorX<symbolic::Variable>& sin_vars,
> ```

maybe use the SinCos structure for consistency?
___
*[`common/symbolic_trigonometric_polynomial.h` line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9kpw6b6oOinQXsT1:-N6K9kpx4f7191zjoV2k:bts3x49) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L112)):*
> ```objc
>  * @param e The symbolic expression to be substituted. Note that e has to be a
>  * multilinear polynomial of cosθ and sinθ, and no cosθᵢ and sinθᵢ appear in the
>  * same monomial. Namely e can be t₁cosθ₁sinθ₂ + sinθ₂, but cannot be sinθ₁cosθ₁
> ```

nit: do you really want t to be mentioned there?  that would be strange?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`common/symbolic_trigonometric_polynomial.h` line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9CVz0m5BtTZiXBGr:-N6KBjtM80db0Kgh_oZj:b1hm0my) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

maybe use the SinCos structure for consistency?
</blockquote></details>

I think I want the the pair of (sin(theta), cos(theta)) to map to a `t`. On the other hand, I think we created SinCos structure as being mapped from other structures, not being mapped to? If I use `SinCos` structure, then I will need to make this structure to be hashable, and also the SinCosSubstitutionType in SinCos structure is not used. So I don't feel I should use `SinCos` directly?

Do you mean that you would like to see sin and cos to be in the same structure, not two independent input arguments? I think I can probably change the API to
```cc
RationalFunction SubstituteStereographicProjection(const Polynomial& e, std::vector<std::array<symbolic::Variable, 3>>& sin_cos_t);
```
where `sin_cos_t` stores the pair (sinθᵢ, cosθᵢ, tᵢ). Would this API be cleaner?

I almost want to pub this `SubstituteStereographicProjection` in the `internal` namespace. It is used by C_IRIS internal code, but I don't think it is very easy to use for external users.
___
*[`common/symbolic_trigonometric_polynomial.h` line 112 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9kpw6b6oOinQXsT1:-N6KDYYR4Oq2F66vKkJE:bve1hkn) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L112)):*
> nit: do you really want t to be mentioned there? that would be strange?

Do you mean the example I give  t₁cosθ₁sinθ₂ + sinθ₂ which also contains `t`? That example actually appear in C_Iris. When we look for the separating plane (a, b), such that
```
aᵀp_WV + b >= 1
```
here p_WV (the position of a point V in the world frame W) is a multilinear function of cosθ and sinθ. The separating plane (a, b) are polynomials of `t`. Hence the product `aᵀp_WV`  does look like t₁cosθ₁sinθ₂

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6Ka-gRDCSg0FwfBrrI:buer3go)* status: LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[`common/symbolic_trigonometric_polynomial.h` line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9CVz0m5BtTZiXBGr:-N6K_Zj6-qrrZiUAkECO:beb0hlb) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L102)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I don't think it's too hard to use.  I like keeping it public. 
My proposal was ```
RationalFunction SubstituteStereographicProjection(const Polynomial& e, std::vector<SinCos> sincos, std::vector<Variable> t)
```
But I admit that the benefit is probably small at this point, so I will leave it up to you to choose.  It would be nice to have `std::unordered_map<SinCos, Variable>`, but agree that isn't quite natural.
```

</blockquote></details>

I changed it to use `std::vector<std::pair<symbolic::Variable, symbolic::Variable>> sin_cos`. I didn't use SinCos structure in this API because SinCos::SinCosSubstitutionType is not used in this function, and the user might be wonder why we use a structure with this redundant information.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[`common/symbolic_trigonometric_polynomial.h` line 102 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6K9CVz0m5BtTZiXBGr:-N6Kurpu6HRy4XD6TfcC:b9m9e2l) ([raw file](https://github.com/robotlocomotion/drake/blob/e56cc5930edd36797a4bbbd4c5acabbdeb7db695/common/symbolic_trigonometric_polynomial.h#L102)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I changed it to use `std::vector<std::pair<symbolic::Variable, symbolic::Variable>> sin_cos`. I didn't use SinCos structure in this API because SinCos::SinCosSubstitutionType is not used in this function, and the user might be wonder why we use a structure with this redundant information.
</blockquote></details>

The SinCosSubstitutionType was only introduced when you requested it in the last PR. I agree I don't love it in the SinCos structure.  We could revisit that.

**Review by sherm1 — COMMENTED** [review]
@hongkai-dai Reviewable is telling me that the files I just reviewed got reverted. I'm not sure what to review now.

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6KwOUe7jyRPhBfN8rW:b-pzx4oo)* status: 10 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai, @RussTedrake, and @sherm1)

___
*[`common/symbolic_trigonometric_polynomial.h` line 94 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KmQqh5_evBUCm8zlt:-N6KmQqi7x2eSKBJYk3t:bs2uosi) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L94)):*
> ```objc
>  * polynomial of t.
>  * @param e The symbolic polynomial in which cosθ and sinθ will be replaced.
>  * @param sin_cos sin_cos(i) is the pair (sinθᵢ, cosθᵢ) as documented above.
> ```

minor: I'm confused by this description. sin_cos is actually a pair of Variables. Does that mean these are variables like si & ci representing sin and cosine or are they variables theta where we expect to find expressions sin(theta) in the polynomial?
I don't understand the relationship between parameters e & sin_cos or between sin_cos and t. 

Also are there naming conventions that are expected to be followed, like "s_" and "c_" prefixes for sin and cos variables? If that's documented elsewhere it should be referenced here, otherwise documented here.

An example here would help a lot (like the one for the other signature).
___
*[`common/symbolic_trigonometric_polynomial.h` line 96 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Kj1r46MGqBVszz58r:-N6Kj1r46MGqBVszz58s:b-7lrf5d) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L96)):*
> ```objc
>  * @param sin_cos sin_cos(i) is the pair (sinθᵢ, cosθᵢ) as documented above.
>  * @param t New variables to express cos and sin as rationals of t. tᵢ =
>  * tan(θᵢ/2). @pre t.rows() == sin_cos.size()
> ```

BTW consider putting `@pre` on its own line (more conventional but not required)
___
*[`common/symbolic_trigonometric_polynomial.h` line 107 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KjP8pBRI-SNnm9teQ:-N6KjP8pBRI-SNnm9teR:bg19zz0) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L107)):*
> ```objc
> 
> /**
>  * If e is a multilinear polynomial of cosθ and sinθ, and no
> ```

nit: inconsistent formatting with previous comment (that one starts immediately after the `/**`). Likely the format here (with `/**` on its own line) is more common.
___
*[`common/symbolic_trigonometric_polynomial.h` line 110 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Km3hR2_BhYXDsdWJL:-N6Km3hR2_BhYXDsdWJM:b-crx37g) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L110)):*
> ```objc
>  * cosθᵢ and sinθᵢ appear in the same monomial, then we replace
>  * cosθᵢ with (1-tᵢ²)/(1+tᵢ²), and sinθᵢ with 2tᵢ/(1+tᵢ²), and get a rational
>  * polynomial of t.
> ```

minor: the first sentence (the doxygen "brief") should make it clear how the two functions differ. Both briefs here are identical.
___
*[`common/symbolic_trigonometric_polynomial.h` line 113 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KkBYC3noXwfbdYf9z:-N6KkBYC3noXwfbdYfA-:b-wn9npy) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L113)):*
> ```objc
>  * @param e The symbolic expression to be substituted. Note that e has to be a
>  * multilinear polynomial of cosθ and sinθ, and no cosθᵢ and sinθᵢ appear in the
>  * same monomial. Namely e can be t₁cosθ₁sinθ₂ + sinθ₂, but cannot be sinθ₁cosθ₁
> ```

BTW I'm confused by the appearance of t₁ in the _input_ polynomial here. Aren't the t's the variables we use instead of the sin/cos?
___
*[`common/symbolic_trigonometric_polynomial.h` line 115 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KlYwgEUUokumcZ_i8:-N6KlYwgEUUokumcZ_i9:b-v0z1tz) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L115)):*
> ```objc
>  * same monomial. Namely e can be t₁cosθ₁sinθ₂ + sinθ₂, but cannot be sinθ₁cosθ₁
>  * (where sinθ₁ and cosθ₁ appear in the same monomial) or sin²θ₁ (where the
>  * degree or sinθ₁ is larger than 1).
> ```

minor: this clarifying example is very helpful but seems equally relevant to the other function yet is not present in that function's documentation. Consider putting it in both places
___
*[`common/symbolic_trigonometric_polynomial.h` line 116 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Ko1NkAa6-UR8tKDrf:-N6Ko1NkAa6-UR8tKDrg:b-iziqxy) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L116)):*
> ```objc
>  * (where sinθ₁ and cosθ₁ appear in the same monomial) or sin²θ₁ (where the
>  * degree or sinθ₁ is larger than 1).
>  * @param subs Map each θᵢ to tᵢ.
> ```

BTW I find this confusing. Are you saying we just replace θᵢ with tᵢ? I thought the substitution was more complicated than that.
___
*[`common/symbolic_trigonometric_polynomial.h` line 124 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KkfUxDkZrsHaKKkt7:-N6KkfUxDkZrsHaKKkt8:b-vtibzk) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L124)):*
> ```objc
>  * @verbatim
>  * const auto e_rational = SubstituteStereographicProjection(t *
>  *     sin(theta)*cos(theta) + 1, {{theta, t}});
> ```

minor: it would be helpful to see what you expect e_rational to look like in this example

From the comments above I would expect it to be `t * sin(t) * cos(t)`, because you described `subs` as "Map each θᵢ to tᵢ". But I don't think that's what you meant.
___
*[`common/symbolic_trigonometric_polynomial.cc` line 407 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KoTR36Ab7U7sfPTuR:-N6KoTR36Ab7U7sfPTuS:boiii2i) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.cc#L407)):*
> ```cpp
>     const symbolic::Polynomial& e_poly,
>     const std::vector<std::pair<symbolic::Variable, symbolic::Variable>>&
>         sin_cos) {
> ```

BTW this seems to be enforcing a relationship between e and sin_cos that is not mentioned in the documentation.
___
*[`common/symbolic_trigonometric_polynomial.cc` line 466 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Kq5pM0X-DYRRzVdty:-N6Kq5pNCiJZxxEQsowU:b-2fjyc0) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.cc#L466)):*
> ```cpp
>     // The coefficient could contain "t_set", (the indeterminates for e are
>     // cos_vars and sin_vars). Hence we first need to write the coefficient
>     // as a polynomial of indeterminates interset(t_set, coeff.variables()).
> ```

nit: interset -> intersect
___
*[`common/test/symbolic_trigonometric_polynomial_test.cc` line 222 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Kte166auBXL85p-OG:-N6Kte166auBXL85p-OH:b-bermtl) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/test/symbolic_trigonometric_polynomial_test.cc#L222)):*
> ```cpp
>     theta(i) = symbolic::Variable("theta" + std::to_string(i));
>     cos_vars(i) = symbolic::Variable("cos(theta(" + std::to_string(i) + "))");
>     sin_vars(i) = symbolic::Variable("sin(theta(" + std::to_string(i) + "))");
> ```

BTW just to check my understanding: "cos(theta(1))" is just a variable name, not an expression as it appears to my naïve eyes? 
___
*[`common/test/symbolic_trigonometric_polynomial_test.cc` line 261 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KugghA_mccloXGuMM:-N6Kuggi7K4djcT1O2mo:bltuzhy) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/test/symbolic_trigonometric_polynomial_test.cc#L261)):*
> ```cpp
>       a + b, subs, symbolic::Polynomial({{symbolic::Monomial(), a + b}}),
>       sin_cos, t_angle,
>       symbolic::RationalFunction(symbolic::Polynomial(a + b, t)));
> ```

BTW I can't follow this one. "a" and "b" aren't sin or cos of anything. Yet the expected result appears to have "t" in it, meaning some substitution was performed?? Could you explain in the comment?

**Review by sherm1 — COMMENTED** [review]
Looks like they got renamed from `common/symbolic_something` to `common/symbolic/something`. I see the sizes match so I hope you can use my review comments as-is. I'm not planning to redo them!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6Kwix--RoWG8eoe08T:bbtk9ee)* status: 10 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai, @RussTedrake, and @sherm1)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: 11 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @hongkai-dai, @RussTedrake, and @sherm1)

___
*[`common/symbolic/trigonometric_polynomial.h` line 93 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KxHAC8qtoQ4bdEI47:-N6KxHAC8qtoQ4bdEI48:bbaaycu) ([raw file](https://github.com/robotlocomotion/drake/blob/489e234422f61a6238f077e38ea392d82ed9a9f3/common/symbolic/trigonometric_polynomial.h#L93)):*
> ```objc
>  * cosθᵢ and sinθᵢ appear in the same monomial, then we replace
>  * cosθᵢ with (1-tᵢ²)/(1+tᵢ²), and sinθᵢ with 2tᵢ/(1+tᵢ²), and get a rational
>  * polynomial of t.
> ```

minor: from the code it appears that _something_ also happens when there are no sines and cosines. But the documentation doesn't say that.

**Review by hongkai-dai — COMMENTED** [review]
@russtedrake I replaced the input argument with `std::vector<SinCos>`. I agree this is cleaner. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491#-:-N6LC-EO6NTU7tT2bkWZ:bdm896r)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

___
*[`common/symbolic/trigonometric_polynomial.h` line 93 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KxHAC8qtoQ4bdEI47:-N6L5q8X3LpxZrlqPHfn:b-iudpjk) ([raw file](https://github.com/robotlocomotion/drake/blob/489e234422f61a6238f077e38ea392d82ed9a9f3/common/symbolic/trigonometric_polynomial.h#L93)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: from the code it appears that _something_ also happens when there are no sines and cosines. But the documentation doesn't say that.
</blockquote></details>

Done. I added some documentation.
___
*[`common/symbolic_trigonometric_polynomial.h` line 94 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KmQqh5_evBUCm8zlt:-N6L6-F06qtSloMbImDB:bwqkui2) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L94)):*
> sin_cos is actually a pair of Variables. Does that mean these are variables like si & ci representing sin and cosine or are they variables theta where we expect to find expressions sin(theta) in the polynomial?

That is right. I modified the documentation to make it more clear.

> I don't understand the relationship between parameters e & sin_cos or between sin_cos and t.

sin_cos are variables showing up in `e`. We will replace these variables with 2t/(1+t^2) and (1-t^2)/(1+t^2). The rationale for this substitution is sinθ = 2 * tan(θ/2) / (1 + tan²(θ/2)) and cosθ = (1−tan²(θ/2)) / (1 + tan²(θ/2))

> Also are there naming conventions that are expected to be followed, like "s_" and "c_" prefixes for sin and cos variables? If that's documented elsewhere it should be referenced here, otherwise documented here.

I don't think we have that naming convention yet. Here I just use `sin_cos` to represent the pair (sin, cos).
___
*[`common/symbolic_trigonometric_polynomial.h` line 113 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KkBYC3noXwfbdYf9z:-N6L8lf9CJxF4e4P_4_7:b-p2faxf) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L113)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm confused by the appearance of t₁ in the _input_ polynomial here. Aren't the t's the variables we use instead of the sin/cos?
</blockquote></details>

Done. We will replace cos and sin with t. But I want to emphasize that the original expression can also contain `t` (and that use case is important in our work). I modified the documentation a bit.
___
*[`common/symbolic_trigonometric_polynomial.h` line 116 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Ko1NkAa6-UR8tKDrf:-N6LA90s7sNUpoRdewS1:bgkppaf) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L116)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I find this confusing. Are you saying we just replace θᵢ with tᵢ? I thought the substitution was more complicated than that.
</blockquote></details>

We are going to replace cos(theta) with (1-t^2) / (1 + t^2), and sin(theta) with 2t / (1+t^2). Hence the user only need to provide the mapping from theta to t, we will handle the math for the replacement.

I changed the word "Map" to "Correspond", is it more clear now?
___
*[`common/symbolic_trigonometric_polynomial.h` line 124 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KkfUxDkZrsHaKKkt7:-N6LB-69-P6j0NFsSjNa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.h#L124)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: it would be helpful to see what you expect e_rational to look like in this example

From the comments above I would expect it to be `t * sin(t) * cos(t)`, because you described `subs` as "Map each θᵢ to tᵢ". But I don't think that's what you meant.
</blockquote></details>

Done.
___
*[`common/symbolic_trigonometric_polynomial.cc` line 407 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KoTR36Ab7U7sfPTuR:-N6LB_Ip9AL6GO8gHvrp:bwpzq5g) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/symbolic_trigonometric_polynomial.cc#L407)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW this seems to be enforcing a relationship between e and sin_cos that is not mentioned in the documentation.
</blockquote></details>

Done. Good call. I added it to the documentation.
___
*[`common/test/symbolic_trigonometric_polynomial_test.cc` line 222 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6Kte166auBXL85p-OG:-N6LBjS5EVaqDQuumyhP:b-kembdm) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/test/symbolic_trigonometric_polynomial_test.cc#L222)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW just to check my understanding: "cos(theta(1))" is just a variable name, not an expression as it appears to my naïve eyes? 
</blockquote></details>

Right, it is just a variable name.
___
*[`common/test/symbolic_trigonometric_polynomial_test.cc` line 261 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6KugghA_mccloXGuMM:-N6L4uZj2sE7u1lISSME:btdqonv) ([raw file](https://github.com/robotlocomotion/drake/blob/12e515a3ec57babd17b273a8179a9c3c90d8ff00/common/test/symbolic_trigonometric_polynomial_test.cc#L261)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I can't follow this one. "a" and "b" aren't sin or cos of anything. Yet the expected result appears to have "t" in it, meaning some substitution was performed?? Could you explain in the comment?
</blockquote></details>

Ah I see, I guess you read `symbolic::Polynomial(a + b, t)` as a polynomial having `t` in it. This actually says "construct a+b as a polynomial, with t being the indeterminates". Since a + b doesn't have t in it, so it constructs a polynomial with only a constant term, with the constant being `a+b`

I added some documentation to make it more clear.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17491)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),RussTedrake(platform) (waiting on @hongkai-dai)

___
*[`common/symbolic/trigonometric_polynomial.h` line 158 at r7](https://reviewable.io/reviews/robotlocomotion/drake/17491#-N6OnEzuEqU3HAreXJge:-N6PFcF83mOWiuhBQvSg:b-6n1t8b) ([raw file](https://github.com/robotlocomotion/drake/blob/f2fa518d066493aa0a3beffb5d94bcf47434f10f/common/symbolic/trigonometric_polynomial.h#L158)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It has t₁²  because we multiply t1 with sin(theta1)
</blockquote></details>

Oh, I missed the other t1 because it was alone on the previous line!

**Pull request merged**
