### PR TITLE
Create new method Frame::CalcSpatialAcceleration().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760#-:-MyAOOgW2XmQwRNWX6NR:bwuh3l8)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: with a few minor comments & nits

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760#-:-MyErK1h01sVpxRRHeMp:b-qzv0tr)* status: 9 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 302 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEo1T1AAgldSNvHt6n:-MyEo1T1AAgldSNvHt6o:b-h7opqo) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/plant/test/frame_kinematics_test.cc#L302)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(
>       A_WL3_E.get_coeffs(), A_WL3_E_expected.get_coeffs(),
>       kTolerance, MatrixCompareType::relative));
> ```

minor: I think we need one more unit test where
- all three frames are distinct
- all three frames are moving, and
- the result is non-zero.

Otherwise some of the code is unexercised or gets multiplied by zero which could hide bugs (current or future).
___
*[multibody/tree/frame.h, line 250 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEluJm0f9WmwxcHBWz:-MyEluJm0f9WmwxcHBX-:bqxn5yk) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L250)):*
> ```objc
> 
>     // If the expressed-in frame E is the world, no need to re-express results.
>     if (frame_E.index() == FrameIndex(0)) return V_MF_W;
> ```

nit: use `frame_E.is_world_frame()`
___
*[multibody/tree/frame.h, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEj2Oj4HPHfFsktvzb:-MyEj2Oj4HPHfFsktvzc:b7ked7k) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L327)):*
> ```objc
> 
>   /// Computes and returns the spatial acceleration A_WF_W of `this` frame F in
>   /// world frame W expressed in W as a function of the state stored in context.
> ```

BTW consider modernizing the documentation here for CalcSpatialAccelerationInWorld() to make it more like the new documentation. (You could also just reference the more-general method.)
___
*[multibody/tree/frame.h, line 381 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEoegxAhjlS5LDWBha:-MyEoegxAhjlS5LDWBhb:b-p1ji3) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L381)):*
> ```objc
>     // spatial acceleration in the world frame W, expressed in world frame W).
>     // Modify return value below if frame M or E differ from world frame W.
>     SpatialAcceleration<T> A_MF_W =
> ```

minor: this name worries me because here it is actually A_WF_W, with the intent to upgrade it later. That means for most of the code below the notation is misleading. I'd rather see something like A_XF_W with comments tracking the current value of X whenever it is used, or (simpler) just name it correctly as 
`const A_WF_W` and introduce a new variable A_MF_W when you have the pieces. I doubt there is any speed advantage to re-using the same local memory.
___
*[multibody/tree/frame.h, line 392 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEljuADQLVtz4FOESx:-MyEljuADQLVtz4FOESy:b-drghe4) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L392)):*
> ```objc
>     // a_WCoincidentPoint = a_WMo + α_WM x p_MoFo + ω_WM x (ω_WM x p_MoFo).
>     // Avoid inefficient unnecessary calculations if frame M is the world frame.
>     if (frame_M.index() != FrameIndex(0)) {
> ```

nit: use `frame_M.is_world_frame()`
___
*[multibody/tree/frame.h, line 403 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEpwKEA4_-cXL_Zpsl:-MyEpwKEA4_-cXL_Zpsm:b-8nz93e) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L403)):*
> ```objc
>           CalcSpatialVelocity(context, frame_M, frame_W);
>       const Vector3<T>& w_MF_W = V_MF_W.rotational();
>       A_MF_W.rotational() -= (alpha_WM_W + w_WM_W.cross(w_MF_W));
> ```

minor: instead could be
```
A_MF_W.rotational() = A_WF_W.rotational()
                      - (alpha_WM_W + w_WM_W.cross(w_MF_W));
```
which would be much easier to understand.
___
*[multibody/tree/frame.h, line 413 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEmg-JEYP3zFkyINtN:-MyEmg-JEYP3zFkyINtO:b-eg38jh) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L413)):*
> ```objc
>           A_WM_W.Shift(p_MoFo_W, w_WM_W).translational();
>       const Vector3<T>& v_MFo_W = V_MF_W.translational();
>       const Vector3<T> Coriolis = 2 * w_MF_W.cross(v_MFo_W);
> ```

nit: per GSG variable name should be `coriolis` (or `coriolis_W` might be better).
___
*[multibody/tree/frame.h, line 414 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEqhD32pkuQY6d0WRp:-MyEqhD32pkuQY6d0WRq:b-cowidy) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L414)):*
> ```objc
>       const Vector3<T>& v_MFo_W = V_MF_W.translational();
>       const Vector3<T> Coriolis = 2 * w_MF_W.cross(v_MFo_W);
>       A_MF_W.translational() -= (a_WcoincidentPoint_W + Coriolis);
> ```

minor: instead could be
```
A_MF_W.translational() = A_WF_W.translational()
                         - (a_WcoincidentPoint_W + coriolis_W);
```
___
*[multibody/tree/frame.h, line 418 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEmt1c2RzFrCJheb3P:-MyEmt1c2RzFrCJheb3Q:bqxn5yk) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L418)):*
> ```objc
> 
>     // If expressed-in frame E is the world, no need to re-express results.
>     if (frame_E.index() == FrameIndex(0)) return A_MF_W;
> ```

nit: use `frame_E.is_world_frame()`

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)* status: 3 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 302 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEo1T1AAgldSNvHt6n:-MyJcjSH2-rE2sDQ95Vq:b2nhoc1) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/plant/test/frame_kinematics_test.cc#L302)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think we need one more unit test where
- all three frames are distinct
- all three frames are moving, and
- the result is non-zero.

Otherwise some of the code is unexercised or gets multiplied by zero which could hide bugs (current or future).
</blockquote></details>

TBD
___
*[multibody/tree/frame.h, line 250 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEluJm0f9WmwxcHBWz:-MyJSx5q4S_9r_2m7U6t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L250)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: use `frame_E.is_world_frame()`
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 327 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEj2Oj4HPHfFsktvzb:-MyJV3Vp4E2MiGpxFl6f:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L327)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider modernizing the documentation here for CalcSpatialAccelerationInWorld() to make it more like the new documentation. (You could also just reference the more-general method.)
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 381 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEoegxAhjlS5LDWBha:-MyJa3Ch7_fvn8jkGNx6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L381)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: this name worries me because here it is actually A_WF_W, with the intent to upgrade it later. That means for most of the code below the notation is misleading. I'd rather see something like A_XF_W with comments tracking the current value of X whenever it is used, or (simpler) just name it correctly as 
`const A_WF_W` and introduce a new variable A_MF_W when you have the pieces. I doubt there is any speed advantage to re-using the same local memory.
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 392 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEljuADQLVtz4FOESx:-MyJa4qLCPiblWOTHAqb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L392)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: use `frame_M.is_world_frame()`
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 403 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEpwKEA4_-cXL_Zpsl:-MyJbzWlDUxu4EBOxRua:bhvc9fo) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L403)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: instead could be
```
A_MF_W.rotational() = A_WF_W.rotational()
                      - (alpha_WM_W + w_WM_W.cross(w_MF_W));
```
which would be much easier to understand.
</blockquote></details>

I updated with the better name you suggested above.
I avoid an "if-else" block with relatively easy-to-understand logic that differs from both my original logic and the logic you suggested.  Let's see what you think.
___
*[multibody/tree/frame.h, line 413 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEmg-JEYP3zFkyINtN:-MyJcW8-9dHb58AAYxvG:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L413)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: per GSG variable name should be `coriolis` (or `coriolis_W` might be better).
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 414 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEqhD32pkuQY6d0WRp:-MyJcYdY7awl9NjNGE0a:bhvc9fo) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L414)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: instead could be
```
A_MF_W.translational() = A_WF_W.translational()
                         - (a_WcoincidentPoint_W + coriolis_W);
```
</blockquote></details>

I updated with the better name you suggested above.
I avoid an "if-else" block with relatively easy-to-understand logic that differs from both my original logic and the logic you suggested.  Let's see what you think.
___
*[multibody/tree/frame.h, line 418 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEmt1c2RzFrCJheb3P:-MyJcgOTBk1r2blOQjI2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L418)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: use `frame_E.is_world_frame()`
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
Ok, not quite feature :lgtm_cancel: now.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760#-:-MyioQIREavpCj7E4x9I:b4v9rof)* status: 6 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 318 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyinQdu9cwssYagbzli:-MyinQdu9cwssYagbzlj:bns4yq) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L318)):*
> ```cpp
> 
>   // Verify translational part with by-hand calculations.
>   const Vector3<double> v_WHo_W = V_WH_W.translational();
> ```

nit: should be a reference
___
*[multibody/plant/test/frame_kinematics_test.cc, line 333 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myinpyf07e1WsNELt85:-Myinpyf07e1WsNELt86:bb0gey9) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L333)):*
> ```cpp
>   // To verify rotational part, use known relationship alpha_WH = -alpha_HW.
>   const Vector3<double>& alpha_WH_W = A_WH_W.rotational();
>   EXPECT_TRUE(CompareMatrices(A_HW_E.rotational(), -alpha_WH_W,
> ```

This line has mismatched expressed-in frames. It's scary that the test passed! Is R_WE an identity rotation? Probably need to rotate something so that this wouldn't pass.
___
*[multibody/plant/test/frame_kinematics_test.cc, line 342 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyioJ75EkAZVRNitUMT:-MyioJ75EkAZVRNitUMU:b-5sve5a) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L342)):*
> ```cpp
>   const Vector3<double> twowv = 2 * w_WH_W.cross(v_WHo_W);
>   const Vector3<double> a_HWo_W_expected = -a_WHo_W + alf_r - wwr + twowv;
>   EXPECT_TRUE(CompareMatrices(A_HW_E.translational(), a_HWo_W_expected,
> ```

Same issue here.
___
*[multibody/tree/frame.h, line 403 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEpwKEA4_-cXL_Zpsl:-MyikcTe-Ail0V0o-V68:b-3e3t2u) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L403)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I updated with the better name you suggested above.
I avoid an "if-else" block with relatively easy-to-understand logic that differs from both my original logic and the logic you suggested.  Let's see what you think.
</blockquote></details>

I still think it is a misuse of the notation that must at least get some comments to explain what's happening. The line here looks like you are subtracting something from A_MF_W but in fact you are (partially) _creating_ A_MF_W here. Nicer would be to write
```c++
const SpatialAcceleration A_MF_W = 
    frame_M.is_world_frame() ? A_WF_W : something();
```
where `something()` is a local lambda or separate helper function that performs the necessary calculation. You don't even have to name the lambda in which case it would look almost exactly like the code you have:
```c++
const SpatialAcceleration A_MF_W = 
    frame_M.is_world_frame() ? A_WF_W : [this]() { /*code*/ }();
```
(The final `()` is necessary to actually invoke the lambda.)

I think the extra punctuation is worth it if it means you don't have to misuse the notation.
___
*[multibody/tree/frame.h, line 414 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEqhD32pkuQY6d0WRp:-MyilTrD3m8kXvPGpIas:b304l7u) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L414)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I updated with the better name you suggested above.
I avoid an "if-else" block with relatively easy-to-understand logic that differs from both my original logic and the logic you suggested.  Let's see what you think.
</blockquote></details>

At least needs some documentation explaining that this line does not do what it appears to do. But I think it would be better not to misuse the notation at all.
___
*[multibody/tree/frame.h, line 331 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myijmxa3qmcbTiYIXc4:-Myijmxa3qmcbTiYIXc5:b72xslm) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/tree/frame.h#L331)):*
> ```objc
>   /// @return A_WF_W, `this` frame F's spatial acceleration measured and
>   /// expressed in the world frame W. The rotational part of the returned
>   /// quantity is α_MF_E (frame F's angular acceleration α measured and
> ```

typo: M -> W

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @sherm1)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 318 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyinQdu9cwssYagbzli:-Myj-Z4b0dEwIvVQCHeM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L318)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: should be a reference
</blockquote></details>

Done.
___
*[multibody/plant/test/frame_kinematics_test.cc, line 333 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myinpyf07e1WsNELt85:-Myj-d2744pLyQnUoIVh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L333)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This line has mismatched expressed-in frames. It's scary that the test passed! Is R_WE an identity rotation? Probably need to rotate something so that this wouldn't pass.
</blockquote></details>

Done.
___
*[multibody/plant/test/frame_kinematics_test.cc, line 342 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyioJ75EkAZVRNitUMT:-Myj-fnR9PY3v8sRP2lx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/plant/test/frame_kinematics_test.cc#L342)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Same issue here.
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 403 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEpwKEA4_-cXL_Zpsl:-MyjK7-2BeZGTWIj0m1x:b-l3vhde) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L403)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I still think it is a misuse of the notation that must at least get some comments to explain what's happening. The line here looks like you are subtracting something from A_MF_W but in fact you are (partially) _creating_ A_MF_W here. Nicer would be to write
```c++
const SpatialAcceleration A_MF_W = 
    frame_M.is_world_frame() ? A_WF_W : something();
```
where `something()` is a local lambda or separate helper function that performs the necessary calculation. You don't even have to name the lambda in which case it would look almost exactly like the code you have:
```c++
const SpatialAcceleration A_MF_W = 
    frame_M.is_world_frame() ? A_WF_W : [this]() { /*code*/ }();
```
(The final `()` is necessary to actually invoke the lambda.)

I think the extra punctuation is worth it if it means you don't have to misuse the notation.
</blockquote></details>

Done.  
Thanks for showing me the Lambda function.
___
*[multibody/tree/frame.h, line 414 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MyEqhD32pkuQY6d0WRp:-MyjIvYU28mp1D8SGAHP:bvhuud1) ([raw file](https://github.com/robotlocomotion/drake/blob/af2c564a9200171a09fa311124ddd16367ee10aa/multibody/tree/frame.h#L414)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

At least needs some documentation explaining that this line does not do what it appears to do. But I think it would be better not to misuse the notation at all.
</blockquote></details>

Done (and agreed).
___
*[multibody/tree/frame.h, line 331 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myijmxa3qmcbTiYIXc4:-Myj-yNs3YukyYYRbrOx:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a374aa02e706171849527ca22f3a9910e136f499/multibody/tree/frame.h#L331)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: M -> W
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760#-:-MynDiss-XyKyRA2FEkW:bnfp4nl)* status: 7 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 322 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn5vcyCsidARP1lSiI:-Myn5vcyCsidARP1lSiJ:btc7mwy) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/plant/test/frame_kinematics_test.cc#L322)):*
> ```cpp
>   // Verify the translational part of V_HW_E via the following calculations.
>   //   v_WHo =  DtW(p_WoHo)                    Definition of Ho's velocity in W.
>   //         =  DtH(p_WoHo) + ω_WH x p_WoHo   Golden rule vector differentation.
> ```

typo, suggest `differentiation`



_Code quote:_
```cpp
differentation
```
___
*[multibody/tree/frame.h, line 252 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn64An9K2xURl3XibB:-Myn64An9K2xURl3XibC:bus1xpv) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L252)):*
> ```objc
>     if (frame_E.is_world_frame()) return V_MF_W;
> 
>     // Othwerwise re-express results from world frame W to frame E.
> ```

typo, suggest `Otherwise`



_Code quote:_
```objc
Othwerwise
```
___
*[multibody/tree/frame.h, line 437 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn6Ggt8hpB83SdBwNG:-Myn6Ggt8hpB83SdBwNH:bus1xpv) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L437)):*
> ```objc
>     if (frame_E.is_world_frame()) return A_MF_W;
> 
>     // Othwerwise re-express results from world frame W to frame E.
> ```

typo, suggest `Otherwise`



_Code quote:_
```objc
Othwerwise 
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)* status: 7 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mitiguy)

___
*[multibody/plant/test/frame_kinematics_test.cc, line 322 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn5vcyCsidARP1lSiI:-MynO2uF7EeeCKcjDfYS:b4bqqrp) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/plant/test/frame_kinematics_test.cc#L322)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo, suggest `differentiation`
</blockquote></details>

Done.  Great eyes!
___
*[multibody/plant/test/frame_kinematics_test.cc, line 325 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MymPl1s3pCjM4uInjwN:-MynOGdHD_KBCGzO6_2F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/plant/test/frame_kinematics_test.cc#L325)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: sign is wrong on v_WHo here (it's correct in the code)
</blockquote></details>

Done.
___
*[multibody/plant/test/frame_kinematics_test.cc, line 353 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MymQNB09q0c6fUyZunZ:-MynOV4l5PjNMVO9lJv9:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/plant/test/frame_kinematics_test.cc#L353)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: wo -> Wo
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 252 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn64An9K2xURl3XibB:-MynPzaa3s3JSMeBLS0W:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L252)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo, suggest `Otherwise`
</blockquote></details>

Done
___
*[multibody/tree/frame.h, line 399 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MymRlnhCeQYpmXc0aWL:-MynQWfW8jOntneob0EE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L399)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: it's clear from the syntax that this is a lambda. The comment should say briefly what it computes. Something like:
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 400 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-MymRI220_MSM6nbWNuy:-MynQgaNEtIx03NZLOtu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L400)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this is a variable name (even though it holds a function). So should be `calc_helper`. Or consider calling it `calc_A_MF_W` for better readability.
</blockquote></details>

Done.
___
*[multibody/tree/frame.h, line 437 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16760#-Myn6Ggt8hpB83SdBwNG:-MynQrWx54B0i09szzIl:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b3fed6bd3275aa27979b7c85961f1e840cecadf7/multibody/tree/frame.h#L437)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo, suggest `Otherwise`
</blockquote></details>

Done

**Review by mitiguy — COMMENTED** [review]
+(release notes: yes) 
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16760#-:-MynjUbHA4HvhUBz_e8V:b-puocn1)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Pull request merged**
