### PR TITLE
[controllers] InverseDynamics doxygen and scalar support

### PR DESCRIPTION
**Pull request by RussTedrake**
Cleans up the doxygen for InverseDynamics and
InverseDynamicsController.

Adds support for default scalars to both classes, and implements the scalar conversion. (This required moving the owned plant from InverseDynamicsController to InverseDynamics, which is where it really belonged).

Also fixes up a bunch of errant uses of @tparam_default_scalar throughout the codebase that I found while trying to remember how to spell it!

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@sammy-tri for feature review, please?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271#-:-NG9MvfY-nLSiNgRvzVB:b-1h8so9)* status: LGTM missing from assignee sammy-tri(platform), needs at least two assigned reviewers (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  +@ggould-tri for platform review

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271#-:-NGIW6x9C4y_MczPf3tT:bj1l0nk)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @RussTedrake)

___
*[`systems/controllers/inverse_dynamics_controller.h` line 44 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGIW1dV6O7yIdlMs96n:-NGIW1dV6O7yIdlMs96o:b-7u6uv7) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics_controller.h#L44)):*
> ```objc
>  * @endsystem
>  *
>  * The desired acceleration port show in <span style="color:gray">gray</span>
> ```

nit: typo (existing) "show" instead of "shown"

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 9 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @RussTedrake)

**Review by ggould-tri — COMMENTED** [review]
I love the delegation to a single common ctor -- a pleasant lack of brittleness!
:lgtm: 
I've quibbled with naming and reassignment a bit below, but nothing of real consequence.

> Reviewed 8 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271#-:-NGIby0g4Jktg-nnjdCy:b-d9lyji)* status: 4 unresolved discussions (waiting on @RussTedrake)

___
*[`systems/controllers/inverse_dynamics.cc` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGId_xMBjw29bZvWgr_:-NGId_xMBjw29bZvWgra:b4x0s51) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L16)):*
> ```cpp
> InverseDynamics<T>::InverseDynamics(
>     std::unique_ptr<multibody::MultibodyPlant<T>> owned_plant,
>     const MultibodyPlant<T>* plant, const InverseDynamicsMode mode)
> ```

nit:  `owned_plant` and `plant` are confusingly similar names.  `owned_plant` and `aliased_plant` or `unowned_plant` would lampshade the distinction a bit better (especially as there is no interface documentation comment to clarify matters).

(feel free to disagree and dismiss -- very much a matter of individual taste which is more readable.)

(Although -- renaming the `plant` argument would free up that name to rename the `multibody_plant_` member to `plant_`, if you think that would improve things?)
___
*[`systems/controllers/inverse_dynamics.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGIdNuc7elO4sdqod04:-NGIdNuc7elO4sdqod05:bqsgo11) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L22)):*
> ```cpp
>       mode_(mode),
>       q_dim_(multibody_plant_->num_positions()),
>       v_dim_(multibody_plant_->num_velocities()) {
> ```

minor:  You definitely should check that `owned_plant` and `plant` were not both set before you go much further.
___
*[`systems/controllers/inverse_dynamics.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGIcY8C6M8NPoupc2hJ:-NGIcY8C6M8NPoupc2hK:by6d2pn) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L24)):*
> ```cpp
>       v_dim_(multibody_plant_->num_velocities()) {
>   if (owned_plant_) {
>     plant = owned_plant_.get();
> ```

nit:  Although this is perfectly legal and correct, reassigning an input parameter that appears to be `const` is a bit of a brainfreeze for the casual reader.  Just using `*multibody_plant_` would be clearer and, net of removing this reassignment, no more characters.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @RussTedrake)

___
*[`systems/controllers/inverse_dynamics.cc` line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGId_xMBjw29bZvWgr_:-NGKB3DT0CwJqdTjTStL:b-58peas) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L16)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  `owned_plant` and `plant` are confusingly similar names.  `owned_plant` and `aliased_plant` or `unowned_plant` would lampshade the distinction a bit better (especially as there is no interface documentation comment to clarify matters).

(feel free to disagree and dismiss -- very much a matter of individual taste which is more readable.)

(Although -- renaming the `plant` argument would free up that name to rename the `multibody_plant_` member to `plant_`, if you think that would improve things?)
</blockquote></details>

Done. I think that `thing` and `owned_thing` is already a pattern, and I'm ok sticking with it.  But I did shorten the excessive multibody_plant to plant throughout.
___
*[`systems/controllers/inverse_dynamics.cc` line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGIdNuc7elO4sdqod04:-NGKA-CpBpY_mAnOPJiT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L22)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  You definitely should check that `owned_plant` and `plant` were not both set before you go much further.
</blockquote></details>

Done.
___
*[`systems/controllers/inverse_dynamics.cc` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18271#-NGIcY8C6M8NPoupc2hJ:-NGK9eyo8g4IhTzxcfne:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/87b6b6006ce2ffc2fafba08c7e7f73b5335e172f/systems/controllers/inverse_dynamics.cc#L24)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  Although this is perfectly legal and correct, reassigning an input parameter that appears to be `const` is a bit of a brainfreeze for the casual reader.  Just using `*multibody_plant_` would be clearer and, net of removing this reassignment, no more characters.
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18271)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sammy-tri(platform) (waiting on @RussTedrake)

**Pull request merged**
