### PR TITLE
Perl pie the new system1 include paths for ROS

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This corrects #3902.  The ROS files were missed in 528991b15b5486c5b0f4e1d1697a3ed29997bb50.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3905)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by liangfok** [comment]
+@liangfok :lgtm_strong: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3905#-:-KUyYWl8cJf1TuCB7MvW:bfb5efj)*

**Comment by jwnimmer-tri** [comment]
I wonder what a self-:lgtm: does.  Let's try it.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3905#-:-KUypZpgQPf053s1bMov:b-87u1e3)*

**Comment by jwnimmer-tri** [comment]
Ah.  Well, it's green-button-merge now.  If anyone needs this tonight you can merge it in.

**Pull request merged**
