### PR TITLE
[workspace] Remove opt-in to FMT_DEPRECATED_OSTREAM

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Drake is natively compatible with fmt v9 now. This reverts commit 33a33485 and 7c44c7e2.

Remove all mentions of `#include <fmt/ostream.h>` except where it is actually used in earnest.

Add a few formatters missed in prior commits.

---

Towards #17742.

This retires the risk that a fmt 10 upgrade will break us on Homebrew.

Remaining work involves polishing up all of the loose ends to make the developer UX even better.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@EricCousineau-TRI for platform review, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform high-level

> Reviewed 43 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-:-NOwY3ob0RW00LMO4ls2:bgowyaf)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOwXd9LAGGARzOQxYjO):*
BTW Some other changes not mentioned, e.g.

```
Fixed placement of ifdef comments
Add quotes around certain formatted values in messages
Use std::string in lieu of auto
```
___
*[`common/text_logging.h` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOwX-IECov6EYLN4C0Z:-NOwX-IECov6EYLN4C0_:b-6p2cds) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc83d568131368428fa92e285bb927bff803f48f/common/text_logging.h#L38)):*
> ```objc
> very rare (only a couple uses in Drake so far).
> 
> When implementing a string output for a Drake type, eventually we'll want to
> ```

nit the "eventually we'll want to teach you" sounds a bit unanchored / ambiguous.

Consider linking to issue, or restating like
"once X lands, you should use fmt::formater. Pending that, continue usage of ostream<<, but prepare for [...]"

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", missing label for release notes (waiting on @EricCousineau-TRI and @rpoyner-tri)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOwXd9LAGGARzOQxYjO):*
OK

> Add quotes around certain formatted values in messages

This is not a separate change. The filesystem operator<< displays quotes, but its to_string does not use quotes.  Updating the format strings keeps the output identical.

> Use std::string in lieu of auto

This is not a separate change.  This is a build fix required by "stop using operator<<", because std::sub_match is not formattable, but it is implicitly convertible to std::string.

> Fixed placement of ifdef comments

This was "make Doxygen slightly more pretty", which I didn't think was particularly notable.
___
*[`common/text_logging.h` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOwX-IECov6EYLN4C0Z:-NOyvMng6lfzaIU4YQHX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/fc83d568131368428fa92e285bb927bff803f48f/common/text_logging.h#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit the "eventually we'll want to teach you" sounds a bit unanchored / ambiguous.

Consider linking to issue, or restating like
"once X lands, you should use fmt::formater. Pending that, continue usage of ostream<<, but prepare for [...]"
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", missing label for release notes (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 39 of 44 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850)* status: LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: looks like a few more fmt/ostream removals are possible.

> Reviewed 2 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-:-NP-1Qv-6spCMWxwe3RM:baizc75)* status: 5 unresolved discussions, labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/expression/formula_cell.cc` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzvuy1Bw-I_0E3i_Uv:-NOzvuy28_xnSDiH-l6x:bcvowgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/common/symbolic/expression/formula_cell.cc#L14)):*
> ```cpp
> 
> #include <fmt/format.h>
> #include <fmt/ostream.h>
> ```

minor can this fmt/ostream include be removed?
___
*[`common/yaml/yaml_read_archive.cc` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzqjP87Aysqirysk-I:-NOzqjP87Aysqirysk-J:bcvowgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/common/yaml/yaml_read_archive.cc#L8)):*
> ```cpp
> #include <drake_vendor/yaml-cpp/yaml.h>
> #include <fmt/format.h>
> #include <fmt/ostream.h>
> ```

minor can this fmt/ostream include be removed?
___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 15 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzIDD_7HRQhJu8OmRB:-NOzIDD_7HRQhJu8OmRC:bcvowgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/geometry/render_gltf_client/test/internal_render_client_test.cc#L15)):*
> ```cpp
> 
> #include <fmt/format.h>
> #include <fmt/ostream.h>
> ```

minor can this fmt/ostream include be removed?
___
*[`geometry/test/proximity_engine_test.cc` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzIKPf1eVviRDYYN-d:-NOzIKPf1eVviRDYYN-e:bcvowgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/geometry/test/proximity_engine_test.cc#L11)):*
> ```cpp
> 
> #include <drake_vendor/fcl/fcl.h>
> #include <fmt/ostream.h>
> ```

minor can this fmt/ostream include be removed?
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzJnmV2uVNTgSQvnGZ:-NOzJnmV2uVNTgSQvnG_:bcvowgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/multibody/parsing/test/detail_urdf_geometry_test.cc#L7)):*
> ```cpp
> 
> #include <fmt/format.h>
> #include <fmt/ostream.h>
> ```

minor can this fmt/ostream include be removed?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18850)* status: labeled "do not merge", missing label for release notes (waiting on @jwnimmer-tri)

___
*[`common/symbolic/expression/formula_cell.cc` line 14 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzvuy1Bw-I_0E3i_Uv:-NP-Q2jdDOfOG0kZTJ8u:bqy0v8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/common/symbolic/expression/formula_cell.cc#L14)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor can this fmt/ostream include be removed?
</blockquote></details>

No; we use `fmt::print(os, ...)`.
___
*[`common/yaml/yaml_read_archive.cc` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzqjP87Aysqirysk-I:-NP-Q8x_7oFf501Xltvc:bqy0v8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/common/yaml/yaml_read_archive.cc#L8)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor can this fmt/ostream include be removed?
</blockquote></details>

No; we use `fmt::print(os, ...)`.
___
*[`geometry/render_gltf_client/test/internal_render_client_test.cc` line 15 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzIDD_7HRQhJu8OmRB:-NP-PgsbCzzMzNgN-iAP:bqy0v8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/geometry/render_gltf_client/test/internal_render_client_test.cc#L15)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor can this fmt/ostream include be removed?
</blockquote></details>

No; we use `fmt::print(os, ...)`.
___
*[`geometry/test/proximity_engine_test.cc` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzIKPf1eVviRDYYN-d:-NP-PjTW9TPFny82oU0z:bqy0v8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/geometry/test/proximity_engine_test.cc#L11)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor can this fmt/ostream include be removed?
</blockquote></details>

No; we use `fmt::print(os, ...)`.
___
*[`multibody/parsing/test/detail_urdf_geometry_test.cc` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18850#-NOzJnmV2uVNTgSQvnGZ:-NP-PwuI1mXvoh3Lsmde:bqy0v8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/09e8060f4f8f3e0f36c225fb61389208a42e54e8/multibody/parsing/test/detail_urdf_geometry_test.cc#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

minor can this fmt/ostream include be removed?
</blockquote></details>

No; we use `fmt::print(os, ...)`.

**Pull request merged**
