### PR TITLE
[solvers] Fix parsing bugs in OsqpSolver and MosekSolver

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
I haven't had time to figure out tests which break in the old version of the code, but this bug was discovered while working with @cohnt on QPs from trajectory optimization. I cannot find time to write tests for these myself in the next two days, so if there are any volunteers that would be appreciated.

+(release notes: fix) +(priority: high) 

cc @hongkai-dai 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-bfvt60oCs6bEiHTPq:b-f70q53)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
I will PR a test for this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-btFZO28V8Mqfuo3IP:bhwi6c6)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
+(status: do not merge) After further testing today. The Osqp bug is not fixed

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-hEC911T8xff4GXahJ:bnhktbj)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
-(status: do not merge) good to go.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-hP6A1Er-E_SUJZzMI:b-p3ynsl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by rpoyner-tri — COMMENTED** [review]
+@hongkai-dai  -- apparently already reviewing, but not assigned according to Reviewable.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-hcr_QEcI5bKtPdGSE:b-bo6wsp)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Comment by jwnimmer-tri** [comment]
Hongkai is not available for review.

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.
:lgtm:

+@jwnimmer-tri ... will you take platform, since you're clearly reading the code?

> Reviewed 1 of 2 files at r1, 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-hjKxZDRZaj1e1aZ6m:b-8x4enx)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/osqp_solver.cc` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-hmgpS0sNZU5MF3NYF:-O-hmgpS0sNZU5MF3NYG:buzc583) ([raw file](https://github.com/RobotLocomotion/drake/blob/82ccc68e52169083974ed70858fa049f73fce6aa/solvers/osqp_solver.cc#L3)):*
> ```cpp
> #include "drake/solvers/osqp_solver.h"
> 
> #include <algorithm>
> ```

unused.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/osqp_solver.cc` line 3 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-hmgpS0sNZU5MF3NYF:-O-ht5Mz-iLrEcm6T12n:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/82ccc68e52169083974ed70858fa049f73fce6aa/solvers/osqp_solver.cc#L3)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-i-OAvEwtNnwB5qRwV):*
per slack, please update the commit message into the note you want to have appear in the release notes.

**Review by RussTedrake — COMMENTED** [review]
fwiw -- i went ahead and pushed so that we add that same test for snopt and ipopt.  (csdp is the only remaining solver, and it does not support quadratic costs).

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-jTgrz2NsUyZNFxT3a:b5cpf5x)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Draft commit message.

```
Fixed parsing bugs in OsqpSolver and MosekSolver. The changes to OsqpSolver may change the output behavior of Osqp Solver.

This commit fixes three bugs.
1.) A parsing bug in OsqpSolver which sometimes led to the wrong optimization program being solved by OsqpSolver. 
2.) A parsing bug in OsqpSolver which sometimes led to the sometime led to the error  "ERROR in validate_data: P is not upper triangular" 
3.) A parsing bug in MosekSolver which sometimes led to the error "MOSEK error 1415 (MSK_RES_ERR_QOBJ_UPPER_TRIANGLE): Only elements in the lower triangle of the quadratic term in the objective should be specified"
```

Please let me know your thoughts on this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-kfGL44P02jZz3f6kT:b-x3bmna)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-i-OAvEwtNnwB5qRwV):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

per slack, please update the commit message into the note you want to have appear in the release notes.
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
Looks good.  The first is the only one that could silently change the behavior, I guess.  If it was only the factor of 2 on the Q matrix, you might state that.  (Did all other occurrences necessarily result in one of those error messages?)

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-l6j7X1B3G2e7KrE0-:b-1wfxh9)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-i-OAvEwtNnwB5qRwV):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(well, almost done.  you didn't actually update the commit message)

**Review by AlexandreAmice — COMMENTED** [review]
Yes only 1.) could cause an error. It is not a global factor of 2. If the quadratic cost had repeated variables at indices `i` and `j`, then the the off diagonal entries of `Q` corresponding to those entries were not being scaled by two. This is a convoluted corner case that arises due to the way the parser is implemented and I think might be too detailed.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-l8XaZ7j5gks8xbrzG:bml8oku)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`-- commits` line 23 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-i-OAvEwtNnwB5qRwV):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

(well, almost done.  you didn't actually update the commit message)
</blockquote></details>

I will update the commit message when I squash before merging.

**Review by jwnimmer-tri — COMMENTED** [review]
I've confirmed that reverting the implementation fixes cause the new unit tests to fail.

:lgtm: platform

> Reviewed 1 of 2 files at r1, 7 of 8 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-lFbrV8jlhiww6xqWx:bok8kjb)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/osqp_solver.cc` line 21 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-lH3PZ67rcY6U86hdM:-O-lH3PZ67rcY6U86hdN:b2rrh1d) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e02d018b8d52464a0d19f9260c608a09d433fde/solvers/osqp_solver.cc#L21)):*
> ```cpp
>                          std::vector<c_float>* q, double* constant_cost_term) {
>   DRAKE_ASSERT(static_cast<int>(q->size()) == prog.num_vars());
>   std::vector<Eigen::Triplet<c_float>> P_triplets;
> ```

The `internal::ParseQuadraticCosts` function names this argument as `P_upper_triplets`.  I think when a list of triplets is required to be either upper or lower, it's important to use a variable name which matches that, so we should rename this here now, to match the helper function.

It might also be worthwhile to rename `P` to be `P_upper` for utmost clarity (and likewise at the call site of this function).
___
*[`solvers/test/quadratic_program_examples.cc` line 798 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-O-lFqNaEHg8jKdNNOwH:-O-lFqNaEHg8jKdNNOwI:b-uuws8u) ([raw file](https://github.com/RobotLocomotion/drake/blob/3e02d018b8d52464a0d19f9260c608a09d433fde/solvers/test/quadratic_program_examples.cc#L798)):*
> ```cpp
>   // clang-format on
>   const Eigen::Vector4d b(1, 0, 2, 3);
>   // This cost as variable both out of order and repeated.
> ```

grammar



_Suggestion:_
```cpp
has variables
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21579#-:-O-lfDwv8LYZ4hTOxMED:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),RussTedrake(platform)

**Pull request merged**
