### PR TITLE
Add drake_copyable.h and use it in drake/common/

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4780)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Sample doxygen output when using this macro:
screenshot_from_2017-01-13_12-11-15

**Comment by jwnimmer-tri** [comment]
The one build error so far is a flake.

Further examples of applying this macro are in my dev branch https://github.com/jwnimmer-tri/drake/tree/noncopyable2/drake for the curious.

+@ggould-tri for platform review, please.

/CC @sherm1 Would you like to self-assign and offer a feature review?

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaNoOSaRzqzTTElIEne:bx2qyex)*

**Comment by sherm1** [comment]
+@sherm1 for feature review

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaNwvgNr1STI55SYrQv:b-f384lj)*

**Comment by ggould-tri** [comment]
I like this.  Correct deboilerplating makes everything better.
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/common/drake_copyable.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0IHVaXRy3kiWf0vW:-KaO0IHVaXRy3kiWf0vX:bc5i3vo) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L20)):*
> ```objc
>   void operator=(Classname&&) = delete;
> 
> #define DRAKE_COPYABLE_INTERNAL_YA_COPY(Classname)              \
> ```

Please document or expand "YA" -- it is quite unclear what you mean by it.

---

*[drake/common/drake_copyable.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0E2riyiKkR_ehXlY:-KaO0E2riyiKkR_ehXlZ:b-e9i2d3) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L23)):*
> ```objc
>   Classname(const Classname&) = default;                        \
>   Classname& operator=(const Classname&) = default;             \
>   /* Fail at compile-time if default-copy doesn't work */       \
> ```

FYI punc

---

*[drake/common/drake_copyable.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0h9TTqJqikPFfBqX:-KaO0h9TTqJqikPFfBqY:badgswe) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L39)):*
> ```objc
> 
> // Default copy-construction and copy-assignment, but disable move-construction
> // and move-assignment.
> ```

Please comment why this does not use `DRAKE_COPYABLE_INTERNAL_NO_MOVE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaO2VAjhtX6GpDQq8o-:b-l40ica)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0IHVaXRy3kiWf0vW:-KaO6pKbHY07UQGmL9HL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Please document or expand "YA" -- it is quite unclear what you mean by it.
</blockquote></details>

Done.

---

*[drake/common/drake_copyable.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0E2riyiKkR_ehXlY:-KaO76fQPyV2tg5GDpBU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L23)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI punc
</blockquote></details>

Done.

---

*[drake/common/drake_copyable.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0h9TTqJqikPFfBqX:-KaO8qZgsGM9_nNem9ng:b-83330m) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Please comment why this does not use `DRAKE_COPYABLE_INTERNAL_NO_MOVE`.
</blockquote></details>

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/drake_copyable.h, line 39 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaO0h9TTqJqikPFfBqX:-KaOMMwQEkrTtNNm-UUX:bpunm30) ([raw file](https://github.com/robotlocomotion/drake/blob/de0151be73f421a46f4c4f542209bb2eea69b0e1/drake/common/drake_copyable.h#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

PTAL.
</blockquote></details>

Nice!  Very clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by jwnimmer-tri** [comment]
Added `_DEFAULT_` to the macro names as appropriate, per slack.  PTAL.

---

Review status: 4 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaOQl-hIUqOT16nKOc9:bl9g61d)*

**Comment by sherm1** [comment]
A few post-slack comments here, PTAL.

---

Reviewed 3 of 13 files at r1, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOS5EvQ6ADPzKWSX29:-KaOS5EvQ6ADPzKWSX2A:b-qyp9kd) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L29)):*
> ```objc
>   }
> 
> #define DRAKE_COPYABLE_INTERNAL_DEFAULT_MOVE(Classname) \
> ```

BTW, consider moving the "internal" macros to the end of this file (like "private:"). They don't need to be defined prior to their uses.

---

*[drake/common/drake_copyable.h, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOSKRJ_NvE7B3K3oFm:-KaOSKRJ_NvE7B3K3oFn:b-w8v8ch) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L34)):*
> ```objc
> 
> // Disable copy, assign, and move.
> #define DRAKE_NONCOPYABLE(Classname)                    \
> ```

I would like this to be something like`DRAKE_NOT_COPYMOVEABLE`. I know it's implied but that is too much for my feeble brain. Also better matches `DRAKE_DEFAULT_COPYMOVEABLE`.

---

*[drake/common/drake_copyable.h, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOU9CGSYCCCptat2M7:-KaOU9CGSYCCCptat2M8:b-t929br) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L45)):*
> ```objc
> // leaving the move functions undeclared, overload selection chooses the
> // copy functions instead, which matches the mnemonic of this macro.
> #define DRAKE_DEFAULT_COPYABLE(Classname)               \
> ```

As I read this, I can use `DRAKE_DEFAULT_COPYABLE` then add custom move methods if I want to. With proper documentation, that seems acceptable. But then I think `DRAKE_NOT_COPYABLE` (if it exists) should suppress copy but still allow me to add properly-documented move methods. That is an additional argument for `DRAKE_NOT_COPYMOVEABLE` when both are suppressed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaOVBTw3xpJfRqA2tfL:b-q5b4m8)*

**Comment by sherm1** [comment]
/cc @maddog-tri 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaOVHDdfZfPj_PJjU0i:b-b4m5pw)*

**Comment by sherm1** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by maddog-tri** [comment]
I still don't understand how `DRAKE_DEFAULT_COPYABLE` --- i.e. "provide default copy operations, but do not provide default move operations" --- is ever the right thing to do.  When is it the case that the default-copy operations work correctly but the default-move operations don't?

I do understand that you encountered such declarations in the existing code --- I don't see any instances in this PR, but it looks like there are 4 instances caught in your PR2 branch:
 * `ContactResults`: this class consists of a `std::vector<ContactInfo>`.  `std::vector` is fine with default-move as all the elements recursively are just `std::vector`, integers, eigen `Vector3`, and `unique_ptr`.  (Well... they would be  except that the `ContactInfo` class has explicitly deleted move-operations, even though the default move-ops would work fine.)
 * `Curve2`: this class is inherently default-moveable, too.  The original version explicitly specified `= default` for copy-operations, but said nothing explicitly about the move-operations.  (...so the author's intent is not clear, though, yeah, I know, I recall you are the original author...)
 * `PrintableValue`: I imagine this class is just cribbing from its parent class, `Value`...
 * `Value`: ok, this is an interesting one.  It is explicitly default-copyable, and explicitly move-deleted.  But, it also has a declared virtual destructor and it is used as a base class for at least one subclass.  Is the idea that "copyable" is necessary feature (to make `System` things work),  but "moveable" is not, so we give it a contract that requires the one and... prohibits the other? I don't understand how the default-copying works.  Doesn't the default-copy-assignment operator make it susceptible to object-slicing?

(You _could_ just take `DRAKE_DEFAULT_COPYABLE` out of this PR, since it is not actually used yet in this PR.)

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 33 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaRBDprQj9AVEQe6iji:-KaRBDprQj9AVEQe6ijj:b-cdr2vw) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L33)):*
> ```objc
>   Classname& operator=(Classname&&) = default;
> 
> // Disable copy, assign, and move.
> ```

The public macros do not have proper doxygen docstrings.

---

*[drake/doc/Doxyfile_CXX.in, line 301 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaQNDvJSasljXMHWXTC:-KaQNDvJSasljXMHWXTD:bmwgf49) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/doc/Doxyfile_CXX.in#L301)):*
> ```
> /** \} */"
> PREDEFINED += DRAKE_DEFAULT_COPYABLE(X):=" \
> /** \name Implements CopyConstructible and CopyAssignable, but no move operations */ \
> ```

The "but no move operations" is potentially a lie: `DRAKE_DEFAULT_COPYABLE` disables the compiler-default move operations, but does not preclude hand-coded move operations.

(One possible resolution:  get rid of `DRAKE_DEFAULT_COPYABLE` altogether.  See my comments in the master thread above.  If the premise is "these macros shall not be used in the presence of any hand-coded copy/move operations", that should be explicitly stated in the documentation for the macros.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaQWXrUBgvOLBpBhGkn:bqwd1jm)*

**Comment by sherm1** [comment]
If something is copyable it is should also be movable. According to this [stackoverflow discussion](http://stackoverflow.com/questions/14323093/are-there-any-use-cases-for-a-class-which-is-copyable-but-not-movable) about copyable-but-not-movable, the CopyConstructible concept is a sub-concept of MoveConstructible. But ... the fact that something is *default* copy constructible doesn't mean it ought to be *default* move constructible. It is often nice to write move constructors in terms of `std::swap()` but that doesn't happen by default. So I think it makes sense to have `DRAKE_DEFAULT_COPYABLE` not say anything about move -- that way move will work but it can still be overridden.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaTyGLcGT-fzOdVz7Db:b4iw4ln)*

**Comment by sherm1** [comment]
BTW, "movable" is an acceptable spelling (with "moveable" as an alternate). I'm not sure which is better; I usually like the shortest spelling I can get away with.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaU0CM6jPWEWxE2rgRb:bqts0wg)*

**Comment by maddog-tri** [comment]
> If something is copyable it is should also be movable. According to this stackoverflow discussion about copyable-but-not-movable, the CopyConstructible concept is a sub-concept of MoveConstructible. 

My take-away from that stackoverflow discussion is "Yes, it is technically possible to create a copyable-but-not-movable class, but no, no one has yet discovered a good reason to ever do that."  I can anyhow imagine situations involving hand-crafted copy operations, which would require similarly hand-crafted move operations, and (in deference to the Google Guidelines) where the expected gain from supporting move would be outweighed by the cost of maintaining more code.

> But ... the fact that something is default copy constructible doesn't mean it ought to be default move constructible. 

However, mine is an even more specific question:  when is it ever the case that the _default_ copy operations are valid but the _default_ move operations are not?

> It is often nice to write move constructors in terms of std::swap() but that doesn't happen by default. 

(Sure... and if you choose to take matters in your own hands and craft your own move operators, then (as I understand Jeremy's intent) you won't/shouldn't use these macros.)

>So I think it makes sense to have DRAKE_DEFAULT_COPYABLE not say anything about move -- that way move will work but it can still be overridden.

But, that's not what happens with DRAKE_DEFAULT_COPYABLE:  by saying something ("= default") about copy and not saying anything about move, the default move operations are _disabled_.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaVWo2orgJBeFtVWaHH:bn3wn51)*

**Comment by sherm1** [comment]
Ah, thanks @maddog-tri. TIL that specifying default copy construct/assign prevents generation of default move/assign but still leaves the class movable, though that is done by using the default copy methods. That is weird enough that I agree we shouldn't have the COPYABLE macro, just COPYMOVEABLE, with all 4 defaults.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KaZ2YWeScevMpyyfHKv:bjrsqus)*

**Comment by jwnimmer-tri** [comment]
---

> ... this stackoverflow discussion about copyable-but-not-movable, the CopyConstructible concept is a sub-concept of MoveConstructible.

That SO link is off-topic; its about deleting the move operations, rather than omitting them.  Its title is not super-clear.

It is important to be clear about a whether a type is moveable, versus whether the type provides a move constructor.  They are not the same thing!  "_A movable type is one that can be initialized and assigned from temporaries (all copyable types are therefore movable)."_

I think even the Herb Sutter answer that's linked from the SO link is the same -- moveable means "MoveConstructible" not _"Has `T(T&& other)` overloaded constructor_".

> My take-away from that stackoverflow discussion is "Yes, it is technically possible to create a copyable-but-not-movable class, but no, no one has yet discovered a good reason to ever do that." 

Same reply.  That is an incorrect reading of the discussion.  That discussion is about deleting the move constructor, which means that you get compile failures when the type is used in the context of a moving from a temporary.  If we define copy functions and are silent about move, then everything works.

---

> TIL that specifying default copy construct/assign prevents generation of default move/assign but still leaves the class movable, though that is done by using the default copy methods. That is weird enough that I agree we shouldn't have the COPYABLE macro, just COPYMOVEABLE, with all 4 defaults.

Copying from temporaries is how C++ worked for >20 years.  Why is it suddenly a problem now?

---

> I still don't understand how DRAKE_DEFAULT_COPYABLE --- i.e. "provide default copy operations, but do not provide default move operations" --- is ever the right thing to do. When is it the case that the default-copy operations work correctly but the default-move operations don't?

When copying the temporary is just as good as moving it (e.g., the class is just a pile of `int`s or int-equivalents), the move functions are just extra object-code baggage for no reason.

---

> `ContactResults`: this class consists ...

It would be fine to revisit this code if there's some point where moving made sense.  As it stands, we believe that the framework will only ever use copying.

> `Curve2`: this class is inherently default-moveable ...

Is it?  Did you try defining them and confirm they show up in the object code, versus fallbacks to the copy constructor?  I am not sure that immutable types should be thought of as being moveable, especially from xvalues.  The code is unlikely to be long-lived, so I selected more obvious correctness over runtime performance.

> `PrintableValue`: I imagine this class is just cribbing from its parent class, `Value`...
> `Value`: ok, this is an interesting one ...

`Value` was wrong, and is now fixed on master.

> (You could just take DRAKE_DEFAULT_COPYABLE out of this PR, since it is not actually used yet in this PR.)

Right-o.  I've done this, in an attempt to make forward progress.

---

Review status: 2 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 29 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOS5EvQ6ADPzKWSX29:-KaObkgeBNiOWsiOhwpJ:bog24tu) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L29)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider moving the "internal" macros to the end of this file (like "private:"). They don't need to be defined prior to their uses.
</blockquote></details>

Done (removed entirely).

---

*[drake/common/drake_copyable.h, line 33 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaRBDprQj9AVEQe6iji:-KamuN_Mk-TFvmOaL_-2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L33)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

The public macros do not have proper doxygen docstrings.
</blockquote></details>

Done.

---

*[drake/common/drake_copyable.h, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOSKRJ_NvE7B3K3oFm:-KamuOZjfeF9njpLEHYZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L34)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I would like this to be something like`DRAKE_NOT_COPYMOVEABLE`. I know it's implied but that is too much for my feeble brain. Also better matches `DRAKE_DEFAULT_COPYMOVEABLE`.
</blockquote></details>

Done.

---

*[drake/common/drake_copyable.h, line 45 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaOU9CGSYCCCptat2M7:-KamuPsJ2WP03KMF5qSO:b9h8af3) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/common/drake_copyable.h#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

As I read this, I can use `DRAKE_DEFAULT_COPYABLE` then add custom move methods if I want to. With proper documentation, that seems acceptable. But then I think `DRAKE_NOT_COPYABLE` (if it exists) should suppress copy but still allow me to add properly-documented move methods. That is an additional argument for `DRAKE_NOT_COPYMOVEABLE` when both are suppressed.
</blockquote></details>

Done (removed, for now).

---

*[drake/doc/Doxyfile_CXX.in, line 301 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KaQNDvJSasljXMHWXTC:-KamuU4v_dtaB1nY-oH9:b9h8af3) ([raw file](https://github.com/robotlocomotion/drake/blob/43944606310d82654976b44eda330e2ac0e255da/drake/doc/Doxyfile_CXX.in#L301)):*
<details><summary><i>Previously, maddog-tri (Matt Marjanović) wrote…</i></summary><blockquote>

The "but no move operations" is potentially a lie: `DRAKE_DEFAULT_COPYABLE` disables the compiler-default move operations, but does not preclude hand-coded move operations.

(One possible resolution:  get rid of `DRAKE_DEFAULT_COPYABLE` altogether.  See my comments in the master thread above.  If the premise is "these macros shall not be used in the presence of any hand-coded copy/move operations", that should be explicitly stated in the documentation for the macros.)
</blockquote></details>

Done (removed, for now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KacVmO4Xi-3DXf0QUjR:bbnj426)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_copyable.h, line 12 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-Kan--BBY8fYPJD8pfPU:-Kan--BBY8fYPJD8pfPV:bwzz1u1) ([raw file](https://github.com/robotlocomotion/drake/blob/acd8456ec22799920b5f4b06949ff21d2a29de06/drake/common/drake_copyable.h#L12)):*
> ```objc
> /** @file
> Provides careful macros to selectively enable or disable the special member
> functions for copy-construction, copy-assignment, move-construction. and
> ```

Oops, period should be comma here.  Will fix in next push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by sherm1** [comment]
> Copying from temporaries is how C++ worked for >20 years.  Why is it suddenly a problem now?

Because expectations are higher now. I expect move to be used if possible; that wasn't true before C++11.

:lgtm: now, thanks Jeremy. One BTW question. I like the new long-winded macro names!

---

Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 64 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-Kan4mtrXSWc_8qRvQwS:-Kan4mtrXSWc_8qRvQwT:b-2wl14q) ([raw file](https://github.com/robotlocomotion/drake/blob/acd8456ec22799920b5f4b06949ff21d2a29de06/drake/common/drake_copyable.h#L64)):*
> ```objc
>   Classname(Classname&&) = default;                             \
>   Classname& operator=(Classname&&) = default;                  \
>   /* Fails at compile-time if default-copy doesn't work. */     \
> ```

BTW, this appears to be validating generation of default copy assignment only -- does that also ensure default copy construction somehow? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-Kan2kgMxozRR4Y0WiyA:b-j3stc3)*

**Comment by jwnimmer-tri** [comment]
*[drake/common/drake_copyable.h, line 64 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-Kan4mtrXSWc_8qRvQwS:-KanF2MF8P4X5sNZb_Xx:b-dwlgjl) ([raw file](https://github.com/robotlocomotion/drake/blob/acd8456ec22799920b5f4b06949ff21d2a29de06/drake/common/drake_copyable.h#L64)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this appears to be validating generation of default copy assignment only -- does that also ensure default copy construction somehow? 
</blockquote></details>

I wouldn't say it guarantees it, but I was unable to think of a case where they would disagree on being well-formed vs ill-formed when defaulted, nor a simiarly-trivial way to confirm that the copy-constructor was defined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by jwnimmer-tri** [comment]
+@maddog-tri for review, please.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-KanFYc3SnqA4WHNeZCG:b-hmb7zv)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KanGIx047LI3yfoU5WG:-KanGIx1GqpX2Cn-8Jk1:b-i72bqf) ([raw file](https://github.com/robotlocomotion/drake/blob/acd8456ec22799920b5f4b06949ff21d2a29de06/drake/common/drake_copyable.h#L13)):*
> ```objc
> Provides careful macros to selectively enable or disable the special member
> functions for copy-construction, copy-assignment, move-construction. and
> move-assignment
> ```

FYI, should be some punc here.  Period or colon, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by jwnimmer-tri** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/common/drake_copyable.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-KanGIx047LI3yfoU5WG:-KanLMoWlNjpOgQLjVCD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/acd8456ec22799920b5f4b06949ff21d2a29de06/drake/common/drake_copyable.h#L13)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI, should be some punc here.  Period or colon, I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780)*

**Comment by maddog-tri** [comment]
:lgtm:  (If/when `DRAKE_FRANKEN_COPYABLE(Foo)` rematerializes in a succeeding PR, we can carry on the discussion there.)

---

Reviewed 2 of 13 files at r1, 10 of 11 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4780#-:-Kap_r59xVUD_q-savXu:brwxqgy)*

**Pull request merged**
