### PR TITLE
[solvers] prefer SCS to CSDP.

### PR DESCRIPTION
**Pull request by hongkai-dai**
In ChooseBestSolver, prefers SCS to CSDP. SCS might give a low accuracy solution, but CSDP fail to solve some trivial problems.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@RussTedrake for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NYrzzF18XfdPqVH_zZJ:b-7vq6ss)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
:lgtm: Thanks!  I'll wait til you look at the CI failures before passing to platform.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NYxeeUi8Hg3tZ4HOy_x:bvyen7c)* status: needs at least two assigned reviewers

**Comment by RussTedrake** [comment]
We should probably discuss whether those CI failures are real enough to suggest that SCS is brittle, too.
For GCS, at least, it might be reasonable to prefer CSDP (e.g. setting our own preferred solvers instead of using ChooseBestSolver) since we expect all of the decision variables to be bounded.

**Review by hongkai-dai — COMMENTED** [review]
> We should probably discuss whether those CI failures are real enough to suggest that SCS is brittle, too.  
For GCS, at least, it might be reasonable to prefer CSDP (e.g. setting our own preferred solvers instead of using ChooseBestSolver) since we expect all of the decision variables to be bounded.

I think these variables don't have the lower or upper bound https://github.com/RobotLocomotion/drake/blob/31eae0b156a77763822a5aeb4fc1633471984755/geometry/optimization/graph_of_convex_sets.cc#L701-L703?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NYyMX4B27dDqqtc6uc8:b-w4sfvl)* status: needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
@jwnimmer-tri How can I enable a specific `GTEST_TEST` when gurobi/mosek are enabled? After we switch to SCS, many problems cannot be solved accurately, so I only want to have the CI to test these problems with gurobi/mosek.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NZ3v-I6BurJ0Hladkb8:bah6h6r)* status: needs at least two assigned reviewers

**Review by RussTedrake — COMMENTED** [review]
We have 
```
if (!GurobiOrMosekSolverAvailable()) {
return;
}
```
in many of the unit tests in `gcs_trajectory_optimization_test.cc`

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NZ5gkwx3U1E6eQejBpU:b1g8g2g)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
> After we switch to SCS, many problems cannot be solved accurately, ...

Isn't this a canary in the coal mine?  If a bunch of tests are unhappy now, won't all of our users' programs that are similar to those tests also start failing?

**Review by hongkai-dai — COMMENTED** [review]
It would affect many of our users who rely on solvers::Solve() to use CSDP solver.

I can spend a day to understand why CSDP solver fails for the simple problem and try to fix CSDP.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19676#-:-NZ6OeKE04Hbwg0CrCih:b-b612wo)* status: needs at least two assigned reviewers

**Pull request closed without merging**
