### PR TITLE
[parsing] Support parsing continuous joint in SDFormat

### LINKED ISSUE #14747: Should support continuous joints from SDFormat
SDFormat defines "continuous" as a supported joint type since 1.6; however, our SDF parser does not support this joint type and throws a "Joint type not supported" exception when parsing a SDF file containing such a joint.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Closes #14747.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
+(status: do not review) while I work on unit tests.

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +@amcastro-tri for feature review please, thanks.
+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956#-:-NCWm49CEOfk9ec_FaaD:bzcdwwq)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
Excellent!
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956#-:-NCa1mGJ2UK-Y3jOgpG8:b-16y5d2)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[`multibody/parsing/test/detail_sdf_parser_test.cc` line 838 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1g1UA2YgZcU0TKAj:-NCa1g1V0mCyn6FF5m-7:b-opeeuv) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/detail_sdf_parser_test.cc#L838)):*
> ```cpp
>       prismatic_joint.acceleration_upper_limits(), Vector1d(10)));
> 
>   // Continuous joint
> ```

ditto, wouldn't we also like to have a test for "Limitless revolute joint"?



_Code quote:_
```cpp
Limitless revolute joint
```
___
*[`multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1TD18dznQoKO525T:-NCa1TD18dznQoKO525U:byvpref) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf#L98)):*
> ```
>         </inertial>
>       </link>
>       <joint name="continuous_joint" type="continuous">
> ```

wouldn't we like to have both tests? one for a revolute joint with no limits and one for a continuous joint? even if they are both an equivalent representation of the same mechanism.

**Review by amcastro-tri — COMMENTED** [review]
+@ericcousineau-tri for platform please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956#-:-NCa1pNb13uKRJHK6m2D:b-g9b9o9)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @xuchenhan-tri)

**Comment by xuchenhan-tri** [comment]
*[`multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1TD18dznQoKO525T:-NCa5WOQBi0Mb8vNBqki:bkcgmbd) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

wouldn't we like to have both tests? one for a revolute joint with no limits and one for a continuous joint? even if they are both an equivalent representation of the same mechanism.
</blockquote></details>

I had the same question when modifying this test -- Do people actually specify revolute joints without limit or is it a stop gap for the lack of support for continuous joint? If the answer is the former, I'll add back revolute joint without limits.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong:, excellent indeed, thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956#-:-NCaDFbX6AgDQGaHHFTu:b-h6fsbw)* status: 2 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCaCqxj86K1rBewv5rI:-NCaCqxj86K1rBewv5rJ:bqkib1s) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/detail_sdf_parser.cc#L558)):*
> ```cpp
>   // Drake marks joints with no limits with ±numeric_limits<double>::infinity()
>   // and therefore we make the change here.
>   // Default position limits to infinities which is the case for continuous
> ```

FWIW (pre-existing defect) Seems like line continuations in this files are a bit inconsistent, oops!
___
*[`multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1TD18dznQoKO525T:-NCaD1B64dmbU8ZwAhBf:birmtoi) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf#L98)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I had the same question when modifying this test -- Do people actually specify revolute joints without limit or is it a stop gap for the lack of support for continuous joint? If the answer is the former, I'll add back revolute joint without limits.
</blockquote></details>

Given that this current revision might be reducing test coverage, yeah, I think it's good to have `revolute_joint_no_limits` as well (making this PR a pure addition).

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)* status: 2 unresolved discussions (waiting on @amcastro-tri and @EricCousineau-TRI)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCaCqxj86K1rBewv5rI:-NCaEMtNBMRETDR0Zw95:brs5q5m) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/detail_sdf_parser.cc#L558)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FWIW (pre-existing defect) Seems like line continuations in this files are a bit inconsistent, oops!
</blockquote></details>

I don't see the inconsistency. I intend the new comment to be a new paragraph. Is this better?
___
*[`multibody/parsing/test/detail_sdf_parser_test.cc` line 838 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1g1UA2YgZcU0TKAj:-NCaEVsS1HEGDr2TbB0i:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/detail_sdf_parser_test.cc#L838)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, wouldn't we also like to have a test for "Limitless revolute joint"?
</blockquote></details>

Done, thanks.
___
*[`multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf` line 98 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCa1TD18dznQoKO525T:-NCaEWim3CMaETNY9Tpl:b-nplwsn) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Given that this current revision might be reducing test coverage, yeah, I think it's good to have `revolute_joint_no_limits` as well (making this PR a pure addition).
</blockquote></details>

Gotcha, done, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)* status: 2 unresolved discussions (waiting on @amcastro-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCaCqxj86K1rBewv5rI:-NCaXXZNE_Jl3UGq80p1:b-ntqblg) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/detail_sdf_parser.cc#L558)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't see the inconsistency. I intend the new comment to be a new paragraph. Is this better?
</blockquote></details>

Ah, no need to take action - I'm just saying that line continuations + whitespace (hanging indent vs. visual indent) are inconsistent, in addition to some hanging indents not even being correct.
However, that was all preexisting, so not worth defecting.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/parsing/detail_sdf_parser.cc` line 558 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17956#-NCaCqxj86K1rBewv5rI:-NCavo-RARCWWAwLkA0X:b4ian5x) ([raw file](https://github.com/robotlocomotion/drake/blob/f709d16b4ed21c6aaadf2724d89060534c294f13/multibody/parsing/detail_sdf_parser.cc#L558)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, no need to take action - I'm just saying that line continuations + whitespace (hanging indent vs. visual indent) are inconsistent, in addition to some hanging indents not even being correct.
However, that was all preexisting, so not worth defecting.
</blockquote></details>

I see. So not this particular line, gotcha.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17956)* status: :shipit: complete! all discussions resolved, LGTM from assignees amcastro-tri,EricCousineau-TRI(platform) (waiting on @xuchenhan-tri)

**Pull request merged**
