### PR TITLE
[solvers] Disable CsdpSolver console printing by default

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Users can use kPrintToConsole to opt-in.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@hongkai-dai says that we need to retain the ability to print to the console.  I'll rework this to obey `kPrintToConsole` later on.

**Comment by jwnimmer-tri** [comment]
Passed local testing on macsim.

+@hongkai-dai for feature review, please.  This plumbing code is somewhat awkward, but does seem to work:

```console
[----------] 2 tests from TrivialSDP1
[ RUN      ] TrivialSDP1.Solve
[       OK ] TrivialSDP1.Solve (0 ms)
[ RUN      ] TrivialSDP1.SolveVerbose
CSDP 6.2.0
Iter:  0 Ap: 0.00e+00 Pobj:  0.0000000e+00 Ad: 0.00e+00 Dobj:  0.0000000e+00 
Iter:  1 Ap: 9.00e-01 Pobj: -4.5530809e+00 Ad: 1.00e+00 Dobj:  1.5748155e+01 
Iter:  2 Ap: 1.00e+00 Pobj: -2.1263319e-01 Ad: 1.00e+00 Dobj:  1.4224457e+01 
Iter:  3 Ap: 1.00e+00 Pobj: -1.6417109e-01 Ad: 9.00e-01 Dobj:  1.2746910e+00 
Iter:  4 Ap: 1.00e+00 Pobj:  5.1762579e-01 Ad: 7.29e-01 Dobj:  7.2279005e-01 
Iter:  5 Ap: 1.00e+00 Pobj:  6.0152833e-01 Ad: 1.00e+00 Dobj:  7.0411022e-01 
Iter:  6 Ap: 9.00e-01 Pobj:  6.6006418e-01 Ad: 9.00e-01 Dobj:  6.7032192e-01 
Iter:  7 Ap: 1.00e+00 Pobj:  6.6285875e-01 Ad: 1.00e+00 Dobj:  6.6798737e-01 
Iter:  8 Ap: 1.00e+00 Pobj:  6.6475327e-01 Ad: 1.00e+00 Dobj:  6.6731733e-01 
Iter:  9 Ap: 1.00e+00 Pobj:  6.6570754e-01 Ad: 1.00e+00 Dobj:  6.6698932e-01 
Iter: 10 Ap: 9.00e-01 Pobj:  6.6657075e-01 Ad: 9.00e-01 Dobj:  6.6669848e-01 
Iter: 11 Ap: 1.00e+00 Pobj:  6.6665705e-01 Ad: 1.00e+00 Dobj:  6.6666937e-01 
Iter: 12 Ap: 1.00e+00 Pobj:  6.6666570e-01 Ad: 1.00e+00 Dobj:  6.6666678e-01 
Iter: 13 Ap: 1.00e+00 Pobj:  6.6666657e-01 Ad: 1.00e+00 Dobj:  6.6666669e-01 
Iter: 14 Ap: 9.00e-01 Pobj:  6.6666666e-01 Ad: 9.00e-01 Dobj:  6.6666667e-01 
Success: SDP solved
Primal objective value: 6.6666666e-01 
Dual objective value: 6.6666667e-01 
Relative primal infeasibility: 3.18e-17 
Relative dual infeasibility: 8.27e-10 
Real Relative Gap: 5.14e-09 
XZ Relative Gap: 5.50e-09 
DIMACS error measures: 3.18e-17 0.00e+00 1.51e-09 0.00e+00 5.14e-09 5.50e-09
[       OK ] TrivialSDP1.SolveVerbose (1 ms)
[----------] 2 tests from TrivialSDP1 (1 ms total)
```

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: thanks for the fix!
+@ericcousineau-tri for platform review on Thursday.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281#-:-MdUSWHiDdxuQswj5D7-:b-tkq7h3)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[solvers/csdp_solver.cc, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdUS61x6QzwV7-MFVJA:-MdUS1oR670QQ6WRox5H:b-4lednz) ([raw file](https://github.com/robotlocomotion/drake/blob/2298a358adcc1a515c1aec144a8793302791efa7/solvers/csdp_solver.cc#L1)):*
> ```cpp
> #include "drake/solvers/csdp_solver.h"
> ```

nit, Could you put a documentation here that we patch `easy_sdp` function in `csdp/params_pathnames.patch`? In case in the future I forgot where the first filepath argument comes from.
___
*[tools/workspace/csdp/params_pathname.patch, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdURucv4ayM3zy9TMyH:-MdURucv4ayM3zy9TMyI:b-z5u4bs) ([raw file](https://github.com/robotlocomotion/drake/blob/2298a358adcc1a515c1aec144a8793302791efa7/tools/workspace/csdp/params_pathname.patch#L1)):*
> ```Diff
> Add option to specify a filename to parse for CSDP parameters.
> ```

I didn't know we can modify upstream code in this way, that is awesome!

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @hongkai-dai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[solvers/csdp_solver.cc, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdUS61x6QzwV7-MFVJA:-MdUViPJBWoddAFXrRA8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2298a358adcc1a515c1aec144a8793302791efa7/solvers/csdp_solver.cc#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, Could you put a documentation here that we patch `easy_sdp` function in `csdp/params_pathnames.patch`? In case in the future I forgot where the first filepath argument comes from.
</blockquote></details>

Done.
___
*[tools/workspace/csdp/params_pathname.patch, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdURucv4ayM3zy9TMyH:-MdUVjTiDXaZpkPACCtb:b-e6f36i) ([raw file](https://github.com/robotlocomotion/drake/blob/2298a358adcc1a515c1aec144a8793302791efa7/tools/workspace/csdp/params_pathname.patch#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I didn't know we can modify upstream code in this way, that is awesome!
</blockquote></details>

Only for libraries are are rebuilding from source already, but yeah!

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with two blocking comments

> Reviewed 5 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281#-:-MdY9bb8-VCz1c1Tzibn:b9nukg)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[solvers/test/csdp_solver_internal_test.cc, line 246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY99KJ7vmL7EilphCS:-MdY99KJ7vmL7EilphCT:b-r5tvkm) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/solvers/test/csdp_solver_internal_test.cc#L246)):*
> ```cpp
>   double pobj, dobj;
>   const int ret =
>       csdp::easy_sdp(0, dut.num_X_rows(), dut.g().rows(), C, rhs, constraints,
> ```

This test is written in C++; why isn't `nullptr` used here in lieu of `0`?
___
*[solvers/test/sdpa_free_format_test.cc, line 849 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY94KC9CuLrqVjHGMA:-MdY94KC9CuLrqVjHGMB:b-r5tvkm) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/solvers/test/sdpa_free_format_test.cc#L849)):*
> ```cpp
>   double dobj{0};
>   const int ret = csdp::easy_sdp(
>       0, dut.num_X_rows(), rhs_hat.rows(), C_csdp, rhs_csdp, constraints_csdp,
> ```

This test is written in C++; why isn't `nullptr` used here in lieu of `0`?
___
*[tools/workspace/csdp/params_pathname.patch, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY8FiZ9O4cekWC3c6_:-MdY8Fi_9wZAwaOrgaeq:bhwtzy5) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/tools/workspace/csdp/params_pathname.patch#L19)):*
> ```Diff
>  
> -int easy_sdp(int n, int k, struct blockmatrix C, double *a, 
> +int easy_sdp(char* params_pathname, int n, int k, struct blockmatrix C, double *a, 
> ```

It's not immediately clear to me why `params_pathname` is `char*` instead of `const char*`.
(Since we're patching, I'd argue we should make this const, even if it deviates from other CSDP API that may use `char*` - FTR, I dunno if it does)

FTR:
```
$ man fopen | grep 'const char*'
       FILE *fopen(const char *pathname, const char *mode);
       FILE *fdopen(int fd, const char *mode);
       FILE *freopen(const char *pathname, const char *mode, FILE *stream);
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI and @hongkai-dai)

___
*[solvers/test/csdp_solver_internal_test.cc, line 246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY99KJ7vmL7EilphCS:-MdYGpfh9C-6SP0kIYEf:byln25a) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/solvers/test/csdp_solver_internal_test.cc#L246)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This test is written in C++; why isn't `nullptr` used here in lieu of `0`?
</blockquote></details>

Done.

(I was just being lazy and trying to avoid whitespace shuffle of the obscenely long function calls.)
___
*[solvers/test/sdpa_free_format_test.cc, line 849 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY94KC9CuLrqVjHGMA:-MdYGp4fB8b5T2DSupkZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/solvers/test/sdpa_free_format_test.cc#L849)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This test is written in C++; why isn't `nullptr` used here in lieu of `0`?
</blockquote></details>

Done.
___
*[tools/workspace/csdp/params_pathname.patch, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY8FiZ9O4cekWC3c6_:-MdYGJOM2b4vwd2x29xL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/tools/workspace/csdp/params_pathname.patch#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's not immediately clear to me why `params_pathname` is `char*` instead of `const char*`.
(Since we're patching, I'd argue we should make this const, even if it deviates from other CSDP API that may use `char*` - FTR, I dunno if it does)

FTR:
```
$ man fopen | grep 'const char*'
       FILE *fopen(const char *pathname, const char *mode);
       FILE *fdopen(int fd, const char *mode);
       FILE *freopen(const char *pathname, const char *mode, FILE *stream);
```
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15281)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai (waiting on @jwnimmer-tri)

___
*[solvers/test/csdp_solver_internal_test.cc, line 246 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15281#-MdY99KJ7vmL7EilphCS:-Md_TAzz0f2GM7wVdRxy:bi5ugq2) ([raw file](https://github.com/robotlocomotion/drake/blob/678ce260f93b8154b2776ba8374a52e9c7627395/solvers/test/csdp_solver_internal_test.cc#L246)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

(I was just being lazy and trying to avoid whitespace shuffle of the obscenely long function calls.)
</blockquote></details>

OK Ah, gotcha! Doesn't look too bad (barring my negative opinions of visual indents :grimacing:)

**Pull request merged**
