### PR TITLE
[doc] Unify the tutorials links to a single destination

### LINKED ISSUE #17964: [doc] Website header links to wrong tutorials page
All three of our website's header templates link from "Tutorials" to the github tree index, instead of the actual tutorials instructions.  This confuses our users.

```
./doc/doxygen_cxx/header.html.patch:33:+      <a class="site-menu-item" href="https://github.com/RobotLocomotion/drake/tree/master/tutorials">Tutorials</a>
./doc/pydrake/layout.html:27:            <a class="site-menu-item" href="/getting_help.html">Getting Help</a> <a class="site-menu-item" href="https://github.com/RobotLocomotion/drake/tree/master/tutorials">Tutorials</a> <a class="site-menu-item" href="/python_bindings.html">Python Bindings</a> <a class="site-menu-item" href="/developers.html">For Developers</a> <a class="site-menu-item" href="/credits.html">Credits</a>
./doc/_config.yml:44:          url: 'https://github.com/RobotLocomotion/drake/tree/master/tutorials'
```

We should adjust those links to show something more helpful, similar to how the in-page content of the https://drake.mit.edu landing page does.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #17964.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17971)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@RussTedrake for both(?) reviews, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17971#-:-NCazJn03caRDbtq9zox:br513oc)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17971#-NCaz6j67TsbetXO_XEV:-NCaz6j67TsbetXO_XEW:b-iawy7j) (no related file):*
Working (to block merging).

Once final reviews are done, I'll merge this myself and re-deploy the website and then refresh the tutorials.  (If I don't do all of those at once, some of the instructions would evaporate until the next stable release.)

___

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17971)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri)

___
*[`tutorials/index.ipynb` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17971#-NCe0sDu2MqlIVUjvQnM:-NCe0sDu2MqlIVUjvQnN:b-ontq6j) ([raw file](https://github.com/robotlocomotion/drake/blob/5671db1cebf81ec6585c1e4162183501a3771bb2/tutorials/index.ipynb#L20)):*
> ```
>     "If you would like to run a tutorial _interactively_ or to experiment with editing the code, click the 'Duplicate' button in the upper right while viewing. You'll be prompted to create an account using Google, GitHub, or SSO. The button will duplicate the entire suite of tutorials into your own personal Deepnote project.\n",
>     " \n",
>     "Alternatively, to run the tutorials locally via `pip`, refer to [drake/tutorials/README.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/README.md).\n",
> ```

I think moving the text is much better.  Thanks!

Should we consider: "to run the tutorials locally via `pip`" could be "to run the tutorials locally, you can install drake (via `pip` or one of our other installation methods)". 
___
*[`tutorials/README.md` line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17971#-NCe1hqw5Ao1JLeA_2Dx:-NCe1hqw5Ao1JLeA_2Dy:b5w3ncp) ([raw file](https://github.com/robotlocomotion/drake/blob/5671db1cebf81ec6585c1e4162183501a3771bb2/tutorials/README.md#L8)):*
> ```Markdown
> you [view the tutorials online](https://deepnote.com/workspace/Drake-0b3b2c53-a7ad-441b-80f8-bf8350752305/project/Tutorials-2b4fc509-aef2-417d-a40d-6071dfed9199/%2Findex.ipynb).
> 
> Alternatively, you may run the tutorials locally using `pip`.
> ```

not just pip.  given the text immediately below, you could just zap this line?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17971)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`tutorials/index.ipynb` line 20 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17971#-NCe0sDu2MqlIVUjvQnM:-ND4gu071PARzg35HB_Z:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5671db1cebf81ec6585c1e4162183501a3771bb2/tutorials/index.ipynb#L20)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think moving the text is much better.  Thanks!

Should we consider: "to run the tutorials locally via `pip`" could be "to run the tutorials locally, you can install drake (via `pip` or one of our other installation methods)". 
</blockquote></details>

Done.
___
*[`tutorials/README.md` line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17971#-NCe1hqw5Ao1JLeA_2Dx:-ND4fzCM2M0JkZU2zVzT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5671db1cebf81ec6585c1e4162183501a3771bb2/tutorials/README.md#L8)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

not just pip.  given the text immediately below, you could just zap this line?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17971#-:-ND4y4Q52O2vwydy2IVt:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Comment by RussTedrake** [comment]
Do I have to write :lgtm: x 2 ?

**Comment by jwnimmer-tri** [comment]
Huh, I'm not sure how you merged it.  I had a blocking discussion in place:

> Working (to block merging).
>
> Once final reviews are done, I'll merge this myself and re-deploy the website and then refresh the tutorials. (If I don't do all of those at once, some of the instructions would evaporate until the next stable release.)

**Comment by RussTedrake** [comment]
sorry.  i missed that and powered through.  :-(

**Pull request merged**
