### PR TITLE
Tweak Bazel memcheck/sanitizer options and add MSan

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5802)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXQ4XIiH2BvY1nCpJu:b-incf9n) (no related file):*
With this patch, I randomly tried `bazel test --config=msan  //drake/lcm:drake_lcm_test` because it was in my shell history, and to my surprise -

(a) msan finds a use-of-uninitialized-value problem (awesome!)
(b) The stack trace is not informed by any debug symbols (huh?)

```
INFO: From Testing //drake/lcm:drake_lcm_test:
==================== Test output for //drake/lcm:drake_lcm_test:
==43740==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55fb81  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55fb81)
    #1 0x526e49  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x526e49)
    #2 0x55e21f  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55e21f)
    #3 0x52ce5c  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x52ce5c)
    #4 0x51420a  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x51420a)
    #5 0x424b36  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x424b36)
    #6 0x424e0d  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x424e0d)
    #7 0x56581c  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x56581c)
    #8 0x7f23a0f56ed4  (/lib/x86_64-linux-gnu/libc.so.6+0x21ed4)
    #9 0x429caa  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x429caa)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55fb81) 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXR2A3b3Y8F9ZE01D2:b-tlfeq7) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

With this patch, I randomly tried `bazel test --config=msan  //drake/lcm:drake_lcm_test` because it was in my shell history, and to my surprise -

(a) msan finds a use-of-uninitialized-value problem (awesome!)
(b) The stack trace is not informed by any debug symbols (huh?)

```
INFO: From Testing //drake/lcm:drake_lcm_test:
==================== Test output for //drake/lcm:drake_lcm_test:
==43740==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55fb81  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55fb81)
    #1 0x526e49  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x526e49)
    #2 0x55e21f  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55e21f)
    #3 0x52ce5c  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x52ce5c)
    #4 0x51420a  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x51420a)
    #5 0x424b36  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x424b36)
    #6 0x424e0d  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x424e0d)
    #7 0x56581c  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x56581c)
    #8 0x7f23a0f56ed4  (/lib/x86_64-linux-gnu/libc.so.6+0x21ed4)
    #9 0x429caa  (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x429caa)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/dgerman/.cache/bazel/_bazel_dgerman/8697ea2ecc5a8b6851ba2dffa5be491f/execroot/drake-distro/bazel-out/clang-3.9-linux-dbg/bin/drake/lcm/drake_lcm_test+0x55fb81) 
```
</blockquote></details>

Strange. I would have thought `-g -O1` would have been sufficient. I will look into it. If you run other sanitizers, do you get debug symbols?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXReppO70VoJbQRQAs:b-3xtc5x) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Strange. I would have thought `-g -O1` would have been sufficient. I will look into it. If you run other sanitizers, do you get debug symbols?
</blockquote></details>

https://clang.llvm.org/docs/MemorySanitizer.html#report-symbolization fixes it - msan is expecting a binary named exactly `llvm-symbolizer` on the path, and that doesn't happen on Trusty by default.  Not sure yet how to streamline this for users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXTzJ20zL9NYDNsPeS:b-kug0jq) (no related file):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

https://clang.llvm.org/docs/MemorySanitizer.html#report-symbolization fixes it - msan is expecting a binary named exactly `llvm-symbolizer` on the path, and that doesn't happen on Trusty by default.  Not sure yet how to streamline this for users.
</blockquote></details>

So first iteration `--action-env=MSAN_SYMBOLIZER_PATH`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Comment by jamiesnape** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXUBLHr_iNqu-739bh:b-z6d8c) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So first iteration `--action-env=MSAN_SYMBOLIZER_PATH`?
</blockquote></details>

Or `--test_env= MSAN_SYMBOLIZER_PATH`, probably.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-KhXQ4XIiH2BvY1nCpJt:-KhXpejsBe23EmQWtLWT:btbxa9p) (no related file):*
> Or --test_env= MSAN_SYMBOLIZER_PATH, probably.

SGTM for a first iteration - that can't hurt, and sort of helps.  For the archives, the logic appears to be:

- If MSAN_SYMBOLIZER_PATH is present, use it.  Complain if it's not named `llvm-symbolizer` exactly.

- Otherwise, if `which llvm-symbolizer` exists, use it.  Complain if it's not named `llvm-symbolizer` exactly.

- Otherwise, complain.

So, the test_env helps developers who, outside of bazel, are relying on MSAN_SYMBOLIZER_PATH.  I would guess that is few people - most people are probably either relying on PATH, which will work without changes, or just broken - but :man_shrugging: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802#-:-KhXqftwCcOqx3pyD_gA:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5802)*

**Pull request merged**
