### PR TITLE
Create IKTrajectoryHelper

### PR DESCRIPTION
**Pull request by sammy-tri**
Split out some of the code used for IK trajectory calculation and which can be reused by the upcoming generic implementation into a helper class.  There should be no functional changes resulting from this PR.

There are some accessors on the helper class which are not yet used.  Their users are coming in a future PR.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2929)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot   mac-clang-experimental-matlab please

**Comment by sammy-tri** [comment]
There's still some fallout from the turning on of shadowing warnings on the mac build which is keeping this from being ready to merge, but I think we can start review.

+@hongkai-dai for feature review (as in https://github.com/RobotLocomotion/drake/blob/master/drake/doc/developers.rst#code-review ).   +@ggould-tri as second feature reviewer while Hongkai sping up, unless that seems like overkill?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNbTTZmWNFKoH0JTJ9_:2014702120)*

**Comment by ggould-tri** [comment]
:lgtm: pending header comment resolution.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/ik_trajectory_helper.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNc1oE19yipjHPc12zH:-KNc1oE19yipjHPc12zI:1191649140) ([raw file](https://github.com/robotlocomotion/drake/blob/acd0e83d6561a8d28b3cbaa8921e3f9e54d0a471/drake/systems/plants/ik_trajectory_helper.cc#L1)):*
> ```cpp
> #include "ik_trajectory_helper.h"
> ```

FYI:  This file is unreviewably awful.  Because the code here is moved unchanged from elsewhere I am going to not review it.  However bear in mind that if we ever do make changes to this code, not one single line of it will ever pass review.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNbxc78kgL-Qi6B8dox:-KNbxc78kgL-Qi6B8doy:938658550) ([raw file](https://github.com/robotlocomotion/drake/blob/acd0e83d6561a8d28b3cbaa8921e3f9e54d0a471/drake/systems/plants/ik_trajectory_helper.h#L21)):*
> ```objc
>  public:
>   /// @param nq -- number of positions of the body
>   /// @param nT -- number of time steps being planned
> ```

Code conventions prefer documenting all parameters of none.  I strongly recommend all in this case, as these parameters are a bit opaque

---

*[drake/systems/plants/ik_trajectory_helper.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNbxSStTbjUgLxcTmmJ:-KNbxSStTbjUgLxcTmmK:854551142) ([raw file](https://github.com/robotlocomotion/drake/blob/acd0e83d6561a8d28b3cbaa8921e3f9e54d0a471/drake/systems/plants/ik_trajectory_helper.h#L31)):*
> ```objc
>   /// @return cost
>   /// @param[out] dJ_vec Matrix to be filled in with the current
>   ///                    gradients.
> ```

Code conventions prefer documenting all parameters of none.  I strongly recommend all in this case, as these parameter names scare and confuse me.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 39 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNbxLaDSLFSYdEXWGud:-KNbxLaECyPjbERIxVRK:1261761852) ([raw file](https://github.com/robotlocomotion/drake/blob/acd0e83d6561a8d28b3cbaa8921e3f9e54d0a471/drake/systems/plants/ik_trajectory_helper.h#L39)):*
> ```objc
>   int nq() const { return nq_;}
>   int nT() const { return nT_;}
>   const double* t() const { return t_; }
> ```

FYI -- inconsistent whitespace between `;` and `}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNc35CTmvDCw-3dXAsL:-385941882)*

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri do you think we should split inverseKinBackend.cpp in the future? When I created inverseKinBackend, it is supposed to support inverseKin, inverseKinPointwise, and inverseKinTraj. Now I feel the code for inverseKin/inverseKInPointwise do not share many parts with inverseKinTraj, and the backend is really OptimizationProblem. It can make the code more understandable if we write a separate inverseKin/inverseKinPointwise file and a inverseKinTraj file.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNc72eAVYvnhjIhZCYo:-2037032915)*

**Comment by sammy-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNbxc78kgL-Qi6B8dox:-KNcCg3qjuz0rE4-xr7Y:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7047706f37ee9739ca86cfde6dd45ad1b12d047f/drake/systems/plants/ik_trajectory_helper.h#L21)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Code conventions prefer documenting all parameters of none.  I strongly recommend all in this case, as these parameters are a bit opaque
</details>
Done.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 31 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNbxSStTbjUgLxcTmmJ:-KNcCgY7qzq0-ZaY71p9:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/7047706f37ee9739ca86cfde6dd45ad1b12d047f/drake/systems/plants/ik_trajectory_helper.h#L31)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Code conventions prefer documenting all parameters of none.  I strongly recommend all in this case, as these parameter names scare and confuse me.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
There's another PR coming soon which does split the pointwise (and single point) vs. trajectory into separate files.  I need to do a little more cleanup there, but I think it'll be ready this afternoon.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNcDpgzsX5iNr9rpKVV:1496299724)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
+@david-german-tri for today's platform review

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNcExXeHvozrKGFvvLm:-1599063598)*

**Comment by david-german-tri** [comment]
I will get to this today, but it might be a couple of hours.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNcWkDsajQFf-lTs08i:2121988417)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNcie36GoeSLvQfedfb:-756535509) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
> ```objc
> /// interesting parts of the optimization.  It is intended to only
> /// hold/calculate data which is independent of the solver being used.
> class IKTrajectoryHelper  {
> ```

Why no test coverage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNcn1UawYjmIvbyrG1L:-54158093) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why no test coverage?
</details>
Interesting question...  It's tested through testIKtraj.cpp and testIKtraj.m rather thoroughly though indirectly.  If we think closer-level test coverage is useful, I can probably write a new C++ test which uses some of that code (and instruments the intermediate results from those tests to find my expected values).

Sigh...  Though those tests use the atlas .urdf from examples/, so we wander into that tar pit again.  Thoughts on how much effort this goal is worth?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNcoGEVvBP_K5RcRPYV:1855194609) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
> Thoughts on how much effort this goal is worth?
 
Your guess is better than mine.  If you think the indirect coverage is unlikely to bit-rot, and is sufficiently local to make the cause-and-effect clear when it fails, then maybe it's good enough.

I'm kind of skeptical that tests which "use the atlas .urdf" are sufficiently local, though.  By way of contrast, you've used textbook examples for other optimization stuff, and I thought that was awesome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNcrG_CT2dJ6Zu2k_YW:828995661) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> > Thoughts on how much effort this goal is worth?
>  
> Your guess is better than mine.  If you think the indirect coverage is unlikely to bit-rot, and is sufficiently local to make the cause-and-effect clear when it fails, then maybe it's good enough.
> 
> I'm kind of skeptical that tests which "use the atlas .urdf" are sufficiently local, though.  By way of contrast, you've used textbook examples for other optimization stuff, and I thought that was awesome.
</details>
I think the existing tests (particularly the MATLAB ones, for better or for worse) are sufficiently comprehensive.  They're not very local at all, I agree.

I could probably come up with plausible local values to test the constructor purely against bit-rot (like hardcode the output from my test run), but I can't say I'd really understand it.

Coming up with plausible values to feed into CalculateCost would take me quite a bit longer to think about.  It would be pretty black box both input and output (dump an existing test or write a bigger test and dump the more local outputs) since, honestly, I don't really understand what the cost function for IK trajectories is exactly doing.

I'll take back the thing about needing the atlas .urdf though.  It's not necessary.  I could (presumably) generate the test data with a smaller model to reduce the complexity of the vectors, and the actual model is never used by the helper class.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNctCPaojOGRY6t2K04:-45492257) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I think the existing tests (particularly the MATLAB ones, for better or for worse) are sufficiently comprehensive.  They're not very local at all, I agree.
> 
> I could probably come up with plausible local values to test the constructor purely against bit-rot (like hardcode the output from my test run), but I can't say I'd really understand it.
> 
> Coming up with plausible values to feed into CalculateCost would take me quite a bit longer to think about.  It would be pretty black box both input and output (dump an existing test or write a bigger test and dump the more local outputs) since, honestly, I don't really understand what the cost function for IK trajectories is exactly doing.
> 
> I'll take back the thing about needing the atlas .urdf though.  It's not necessary.  I could (presumably) generate the test data with a smaller model to reduce the complexity of the vectors, and the actual model is never used by the helper class.  
</details>
This seems like a big quantity of change to propose on a PR that is just moving existing code around.  I don't think we should hold up reorganization of legacy code on the fact that the legacy code is badly tested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
I made a cursory effort to match up the old code to new code in diff, and it looks plausibly like a no-op to me.  

In a part of the code base where I felt more ownership, I would demand tests, but I don't feel comfortable meddling to that degree here.  So, I leave it to your conscience.  It is possible we should consider replacing platform review with an ownership model.

:lgtm:, modulo minor comments below.  

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/plants/ik_trajectory_helper.cc, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNd0CzjeDBLBz2tVMB9:-KNd0CzjeDBLBz2tVMBA:-26139377) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.cc#L1)):*
> ```cpp
> #include "ik_trajectory_helper.h"
> ```

full path, please

---

*[drake/systems/plants/ik_trajectory_helper.h, line 18 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNcie36GoeSLvQfedfa:-KNcwBTEDMZ_JvzFWWNb:-672009428) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.h#L18)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> This seems like a big quantity of change to propose on a PR that is just moving existing code around.  I don't think we should hold up reorganization of legacy code on the fact that the legacy code is badly tested.
</details>
Isn't this PR creating a new API upon which new things are going to be built?  If so, I disagree with @ggould-tri; the fact that the implementation is borrowed from old code doesn't excuse it from testing.

Anyway, @sammy-tri, I leave it to you to decide whether it is adequately tested.  I'm happy to review tests, if you decide to add them.

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 24 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNctZQqdgWchuNx7rgL:-KNchexp9z78EvCiPRNv:-2079200879) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/inverseKinSnoptBackend.cpp#L24)):*
> ```cpp
> #include "constraint/RigidBodyConstraint.h"
> #include "drake/systems/plants/IKoptions.h"
> #include "ik_trajectory_helper.h"
> ```

full path, please

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 85 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNct_fdeB1TthRUL7So:-KNct_fdeB1TthRUL7Sp:-1340115502) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/inverseKinSnoptBackend.cpp#L85)):*
> ```cpp
> static snopt::integer num_qdotfree;
> 
> static IKTrajectoryHelper* ik_traj_h;
> ```

BTW, I think `ik_traj_helper` would be a good bit clearer for a small cost in characters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-:-KNcgMP5nLi-sdL88voN:549421076)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/ik_trajectory_helper.cc, line 1 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNd0CzjeDBLBz2tVMB9:-KNdB6wZggnOqFn_JsZL:63049815) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/ik_trajectory_helper.cc#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> full path, please
</details>
Done, but I don't think I've been doing this in other cases where the .cc file is including it's own .h...

---

*[drake/systems/plants/inverseKinSnoptBackend.cpp, line 24 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2929#-KNctZQqdgWchuNx7rgL:-KNdB-a8QBSFyqmpmoy7:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ad90917080e31111ed2d6aa806d34c9abe66261a/drake/systems/plants/inverseKinSnoptBackend.cpp#L24)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> full path, please
> 
> https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2929)*

**Pull request merged**
