### PR TITLE
[fem] Implement DeformableRigidManager::DoCalcContactSolverResults()

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please, thank you.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611#-:-MgxC1OT-jc8ky95nO4Z:bwshpyi)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri could you consider bumping up the priority of reviewing this PR? There are two more PRs queued up after this one and having those merged in master would 
1. potentially make @jshep-tri's workflow a bit easier so that he doesn't have to coordinate between my personal branch and other changes he makes on top of drake master.
2. make it easier for me to experiment with integrating SAP solver.
Thanks!!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611#-:-MhOre5Z7pFe_C0yXfaL:bbuwvh3)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
This was a breeze to review @xuchenhan-tri, thanks! :lgtm: 

+@jwnimmer-tri for platform review of non-dev changes please.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611#-:-MhPd-_q4VSxG63Ia7MZ:b-h4db8e)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15611#-MhPcoRx3T5x2G-5Bj81:-MhPcoRx3T5x2G-5Bj82:b-t6t1nt) ([raw file](https://github.com/robotlocomotion/drake/blob/57b26a8b51225931a0f6b0d66fdd7575d63d3315/-- commits#L16)):*
do we have a test for this? like a deformable object in contact with the ground. A TODO would be ok if we don't have it.
___
*[multibody/fixed_fem/dev/test/rigid_update_test.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15611#-MhPcHRP3s-SE4T-pxLQ:-MhPcHRP3s-SE4T-pxLR:b-f1mr4z) ([raw file](https://github.com/robotlocomotion/drake/blob/57b26a8b51225931a0f6b0d66fdd7575d63d3315/multibody/fixed_fem/dev/test/rigid_update_test.cc#L79)):*
> ```cpp
>   /* Wire up the plant and the scene graph. */
>   DRAKE_DEMAND(plant.get_source_id().has_value());
>   builder.Connect(scene_graph.get_query_output_port(),
> ```

nit, you might want to use AddMultibodyPlantScenGraph() to avoid all this boilerplate.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: easy platform review!  Just removing some protected functions within an internal class.

> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611#-:-MhPdwY7-GD6-uub3Sn2:b-r3megi)* status: 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611)* status: 2 unresolved discussions (waiting on @amcastro-tri)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15611#-MhPcoRx3T5x2G-5Bj81:-MhQGBKL1BS2GY6nnhjZ:b-8h7214) ([raw file](https://github.com/robotlocomotion/drake/blob/57b26a8b51225931a0f6b0d66fdd7575d63d3315/-- commits#L16)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we have a test for this? like a deformable object in contact with the ground. A TODO would be ok if we don't have it.
</blockquote></details>

Technically we have one [here](https://github.com/RobotLocomotion/drake/blob/bfe1964ca1aa25a0680e194f62484b39f3af9265/multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc#L134). But that test will be modified and after my next PR and won't cover this scenario anymore, so I added a TODO.
___
*[multibody/fixed_fem/dev/test/rigid_update_test.cc, line 79 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15611#-MhPcHRP3s-SE4T-pxLQ:-MhQHfR86nxyeZCOdcoI:b-gnqnst) ([raw file](https://github.com/robotlocomotion/drake/blob/57b26a8b51225931a0f6b0d66fdd7575d63d3315/multibody/fixed_fem/dev/test/rigid_update_test.cc#L79)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, you might want to use AddMultibodyPlantScenGraph() to avoid all this boilerplate. 
</blockquote></details>

Please refer to the [previous PR review](https://github.com/RobotLocomotion/drake/pull/15123#pullrequestreview-678467973) for the reason why `AddMultibodyPlantScenGraph()` won't work here.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611)* status: 1 unresolved discussion (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15611)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Pull request merged**
