### PR TITLE
spatial_vector: Make default constructor initialize to zeros

### LINKED ISSUE #14086: py mbp: SpatialVelocity() default ctor should initialize with zeros
Ran into an issue on Anzu where I messed up our `--config=assertions` CI job (see Anzu Issue 5362).

Issue was that I was using `SpatialVelocity()` instead of `SpatialVelocity.Zero()`.

FTR I was expecting that the default ctor would be all zeros, b/c the surround code looked like this:
```
self._X_TPdes_command = fix_port(X_TPdes_input, RigidTransform())
self._V_TPdes_command = fix_port(V_TPdes_input, SpatialVelocity.Zero())
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #14086

This is the least conservative approach: Change C++ to always initialize to zero.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14087)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@amcastro-tri for feature review, please.
+@sherm1 for platform review, please.

Let me know if there is a benchmark you'd like me to check against.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14087#-:-MHT1yFg4i8xA_5zoctQ:b-tnviyg)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Please seem my comment in the issue [here](https://github.com/RobotLocomotion/drake/issues/14086#issuecomment-694529592).

Please don't make this change.
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14087#-:-MHT8pKR4RkUW8Cbii0u:b8y2uss)* status: LGTM missing from assignees amcastro-tri,sherm1(platform) (waiting on @amcastro-tri and @sherm1)

**Comment by EricCousineau-TRI** [comment]
@sherm1 Can you give me a benchmark to run so we both can concretely reject this, rather than speculate?

**Comment by sherm1** [comment]
No I can't and in fact I'm not sure that's even possible. What benchmark could prove that this doesn't slow MBPlant down in some important application? We know this change _can_ have a negative performance impact. We know MBPlant performance is one of the top user complaints we have and we are working very hard to improve that. This is literally the most basic data structure used in every inner loop of MBPlant. It's a painfully slow process and it upsets me to have to deal with this setback.

**Comment by jwnimmer-tri** [comment]
> Can you give me a benchmark to run so we both can concretely reject this ...

@EricCousineau-TRI In most cases, I'm in the "give me a benchmark to run or else get out of the way" camp on performance defecting (e.g., for System's method bodies), but for core data types like SpatialVelocity in particular I am personally convinced that it's inner loop enough to always be careful with.  At minimum, I think any PR to change the default constructor would need to concurrently opt-in the existing inner-loop uses to a `SpatialVelocity::uninitialized()` spelling so that they are unchanged.  Certainly not even _offering_ that option seems like a defect to me.

As you can see in the issue, I'm very sympathetic to leaving shotguns lying around on the floor of the nursery, but I don't think this PR is how we get from here to there.

**Comment by EricCousineau-TRI** [comment]
> No I can't and in fact I'm not sure that's even possible. What benchmark could prove that this doesn't slow MBPlant down in some important application? [...]

I was more-or-less asking the question hoping you'd point me to the most-up-to-date instructions on running the Cassie benchmark in Drake, assuming that if you're benchmarking against it to inform micro-improvement PR's like #14088, then that'd enable this to show a 1% slowdown, and say it's not a huge issue?

A meta-complaint here is process: you've identified a (tractable) problem - useful measurements - and provided zero direction on how to constructively address the problem?
I mean, you can ask for help, right? (e.g. "Can you identify / help us identify a better benchmark", etc.?)

---

@jwnimmer-tri: Yup, I can do that. I'll have to think about how to teach things like `std::vector<>` to use this, hopefully without needing to define an allocator.

---

For my own purposes, I've filed a simplified PR (#14096) for Python, but I do think we should aim for Jeremy's comment of leaving fewer shotguns laying around the nursery even in C++.

**Comment by sherm1** [comment]
> you've ... provided zero direction on how to constructively address the problem?

There is not a consistency problem between the mathematical rotation operators and the physical quantities (we can discuss f2f if my other comments about that aren't clear). So I think we disagree about what is the actual problem. The problem I do see is that SpatialVector-based physical quantities are not initialized automatically, and it would be nicer for users if they were. They should be initialized to NaN, as we do in Drake C++ in Debug. We intentionally left them uninitialized in C++ Release due to performance concerns, and will not be changing that now while we are trying to fix MBP's urgent performance problems.

To constructively address the problem, initialize the quantities to NaN in Python. Once we have addressed MBP's high priority performance issues, we can revisit this in C++ also.

**Comment by EricCousineau-TRI** [comment]
Closing for now. Can revisit per issue.

**Pull request closed without merging**
