### PR TITLE
Python binding evaluate

### PR DESCRIPTION
**Pull request by soonho-tri**
Part of #8484

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8494)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@gizatt for feature-review, please.
/cc @tobiamarcucci 

Could you check it's good enough to call `Evaluate` function with a Python dictionary and you do not need a Python class `Environment`?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-:-L96LqkDC-xxgYcj-0h6:b-qidw3m)*

**Comment by gizatt** [comment]
Looks like all we're missing not having a full `Environment` class is domain() and to_string()? I don't see any functionality that I'll miss too much.

This looks like it'll be a little awkward for vector-valued decision variables (user will have to populate a dictionary entry for every individual element, rather than a single key with a np array value?), but I think that's inherited from the original `Environment` functionality and not a fault of the bindings?

Looks great for the core functionality! :LGTM:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-:-L96lQpaEQajskeDTIBJ:b-mtt7jg)*

**Comment by soonho-tri** [comment]
> This looks like it'll be a little awkward for vector-valued decision variables (user will have to populate a dictionary entry for every individual element, rather than a single key with a np array value?), but I think that's inherited from the original Environment functionality and not a fault of the bindings?

That's correct. We don't provide that combination on C++-side either. If you think that is something most of Python users will want/need, please open an issue for me.


+@jwnimmer-tri for platform-review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-:-L96rgQsAkZCy_t0rlXw:b-c7ku3w)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[common/symbolic_environment.cc, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-L96tFlKBmy1o_NsHxKe:-L96tFlKBmy1o_NsHxKf:b-erwrom) ([raw file](https://github.com/robotlocomotion/drake/blob/13dc1d9317c611f5a6e61d6ee78151b0c2deb736/common/symbolic_environment.cc#L42)):*
> ```cpp
> }  // anonymous namespace
> 
> Environment::Environment(const initializer_list<value_type> init) : map_(init) {
> ```

BTW Prefer delegating ctor when possible?  I think this one can easily delegate?

---

*[common/symbolic_environment.cc, line 49 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-L96tKqpBEQkAJ87vkJ_:-L96tKqpBEQkAJ87vkJa:b-j4f473) ([raw file](https://github.com/robotlocomotion/drake/blob/13dc1d9317c611f5a6e61d6ee78151b0c2deb736/common/symbolic_environment.cc#L49)):*
> ```cpp
> }
> 
> Environment::Environment(const initializer_list<key_type> vars) {
> ```

FYI Prefer delegating ctor when possible?  I think (with a tiny zip-with-zero utility function) this one could delegate.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-:-L96uUk_9x9MZ0aRXSdp:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/symbolic_environment.cc, line 42 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-L96tFlKBmy1o_NsHxKe:-L973IFsBWaKDXCB_4u7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/13dc1d9317c611f5a6e61d6ee78151b0c2deb736/common/symbolic_environment.cc#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Prefer delegating ctor when possible?  I think this one can easily delegate?
</blockquote></details>

Done.

---

*[common/symbolic_environment.cc, line 49 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494#-L96tKqpBEQkAJ87vkJ_:-L973JD9Bxbt_eUT41kQ:b-896fig) ([raw file](https://github.com/robotlocomotion/drake/blob/13dc1d9317c611f5a6e61d6ee78151b0c2deb736/common/symbolic_environment.cc#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Prefer delegating ctor when possible?  I think (with a tiny zip-with-zero utility function) this one could delegate.
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8494)*

**Pull request merged**
