### PR TITLE
Remove googletest from CMake build

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7202)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7202)*

**Comment by jamiesnape** [comment]
+@ggould-tri for platform review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7202#-:-Kvlu3UHWRmv-L7H7MGh:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7202#-:-Kvlz-NdNskuEQch12zQ:bnfp4nl)*

**Pull request merged**
