### PR TITLE
VPolytope implements convex geometry.

### PR DESCRIPTION
**Pull request by hongkai-dai**
@AlexandreAmice this PR would enable us to use convex meshes in our SOS iris project.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
To reviewers: I moved the function `ReadObjForConvex` from `scene_graph.cc` to `utilities.h`. I didn't change anything inside its implementation.

+@russtedrake for feature review please since you put this feature as a TODO before.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-Mt6abY5DocjwXujOGow:b-grouio)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
This is great!  A few small comments below.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-Mt8fVoM3_AbUa9HjZx7:bgdtdcs)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[geometry/proximity_engine.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8diBJ0JsZjyd5nxYE:-Mt8diBJ0JsZjyd5nxYF:b-hckcaz) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/proximity_engine.cc#L14)):*
> ```cpp
> #include <fcl/fcl.h>
> #include <fmt/format.h>
> #include <tiny_obj_loader.h>
> ```

will be unused in this file...
___
*[geometry/proximity_engine.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8e1mt8ctEIQR2p4-s:-Mt8e1mt8ctEIQR2p4-t:bf35j28) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/proximity_engine.cc#L30)):*
> ```cpp
> 
> static_assert(std::is_same_v<tinyobj::real_t, double>,
>               "tinyobjloader must be compiled in double-precision mode");
> ```

this should move, too?
___
*[geometry/optimization/vpolytope.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8ec8C76xPDKqEwZv-:-Mt8ec8C76xPDKqEwZv0:b1tk8rt) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/optimization/vpolytope.cc#L239)):*
> ```cpp
>   const auto [tinyobj_vertices, faces, num_faces] = internal::ReadObjForConvex(
>       convex.filename(), convex.scale(), false /* triangulate */);
>   Matrix3Xd* vertices = static_cast<Matrix3Xd*>(data);
> ```

what if the mesh is not convex?  should we use qhull here to take the convex hull?  (or perhaps even in ReadObjForConvex?).  i think we don't have to -- this class says it's ok if there are points in the interior -- but it would be more efficient to do so?
___
*[geometry/optimization/test/vpolytope_test.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8f6vADBSkbO3pwIz8:-Mt8f6vADBSkbO3pwIz9:b-9w1dg) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/optimization/test/vpolytope_test.cc#L168)):*
> ```cpp
>   EXPECT_TRUE(V.PointInSet(in1_W, kTol));
>   EXPECT_TRUE(V.PointInSet(in2_W, kTol));
>   EXPECT_FALSE(V.PointInSet(out_W, kTol));
> ```

These tests are so bad in vpolytope right now.  I've been talking to Jack and @tobiamarcucci about fixing it.  I'm guessing your CI errors are due to these.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/utilities.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8fzEX6sG5ekYmm79h:-Mt8fzEX6sG5ekYmm79i:b4ov31j) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/utilities.h#L146)):*
> ```objc
> std::tuple<std::shared_ptr<std::vector<Eigen::Vector3d>>,
>            std::shared_ptr<std::vector<int>>, int>
> ReadObjForConvex(const std::string& filename, double scale, bool triangulate);
> ```

minor As a general principle, don't make "utilities" a dumping ground for random unrelated functions.  Please just move this into a new dedicated file -- `read_obj.h` or similar.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake and @TobiaMarcucci)

___
*[geometry/proximity_engine.cc, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8diBJ0JsZjyd5nxYE:-MtBLgpeEcJ1Oe1JMOPO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/proximity_engine.cc#L14)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

will be unused in this file...
</blockquote></details>

Done.
___
*[geometry/proximity_engine.cc, line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8e1mt8ctEIQR2p4-s:-MtBLhiy6jWii--T0fCb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/proximity_engine.cc#L30)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this should move, too?
</blockquote></details>

Done.
___
*[geometry/utilities.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8fzEX6sG5ekYmm79h:-Mt9HEEy4o6pO3csVrjX:b9tmhct) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/utilities.h#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

minor As a general principle, don't make "utilities" a dumping ground for random unrelated functions.  Please just move this into a new dedicated file -- `read_obj.h` or similar.
</blockquote></details>

Done, thanks! I added a new read_obj.h file.

BTW, I am curious about our policy of the "internal" namespace. If I put this function in `internal` namespace, does that mean this function should only be called inside `geometry` namespace? And do I need to add python binding for functions in the internal namespace?
___
*[geometry/optimization/vpolytope.cc, line 239 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8ec8C76xPDKqEwZv-:-Mt9HwGq4A_Jhq5Jc1WG:biqacf9) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/optimization/vpolytope.cc#L239)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

what if the mesh is not convex?  should we use qhull here to take the convex hull?  (or perhaps even in ReadObjForConvex?).  i think we don't have to -- this class says it's ok if there are points in the interior -- but it would be more efficient to do so?
</blockquote></details>

Good point. I think this function name is misleading. It should then be named as `ReadObjFile` instead of `ReadObjForConvex`. As far as I can see, this function doesn't care if the mesh is convex or not. I can then call `qhull` on the output of this function to get the convex hull.
___
*[geometry/optimization/test/vpolytope_test.cc, line 168 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8f6vADBSkbO3pwIz8:-MtBLb3XEOTP7MQFuIsp:b-ed6ebl) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/optimization/test/vpolytope_test.cc#L168)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

These tests are so bad in vpolytope right now.  I've been talking to Jack and @tobiamarcucci about fixing it.  I'm guessing your CI errors are due to these.
</blockquote></details>

I changed the test to check the vertices. I think that test is more meaningful.

**Comment by jwnimmer-tri** [comment]
___
*[geometry/utilities.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8fzEX6sG5ekYmm79h:-MtBMQZ52QyJz3DnEJM4:b-rw4r5o) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/utilities.h#L146)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done, thanks! I added a new read_obj.h file.

BTW, I am curious about our policy of the "internal" namespace. If I put this function in `internal` namespace, does that mean this function should only be called inside `geometry` namespace? And do I need to add python binding for functions in the internal namespace?
</blockquote></details>

The "internal" means "internal to Drake" not "internal to Geometry"; there is no rule against calling it from other directories.  That being said, we should in general be smart with what code depends on what other code.  We don't want spaghetti.

Since "internal" is not to be used outside of Drake, should should not be available via pydrake at all.  (The only exception would be, for example, where we bound it as a private (underscore'd) symbol in pydrake, for use by _other_ public code within pydrake directly.  But at that point, it should probably elevate out of "internal" anyway and grow a real API.)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake and @TobiaMarcucci)

___
*[geometry/utilities.h, line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16351#-Mt8fzEX6sG5ekYmm79h:-MtBV1l97nbSw-qP1MNS:bo0c705) ([raw file](https://github.com/robotlocomotion/drake/blob/acad552d87e4350f9abfdd58cbda9b59ce24e331/geometry/utilities.h#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The "internal" means "internal to Drake" not "internal to Geometry"; there is no rule against calling it from other directories.  That being said, we should in general be smart with what code depends on what other code.  We don't want spaghetti.

Since "internal" is not to be used outside of Drake, should should not be available via pydrake at all.  (The only exception would be, for example, where we bound it as a private (underscore'd) symbol in pydrake, for use by _other_ public code within pydrake directly.  But at that point, it should probably elevate out of "internal" anyway and grow a real API.)
</blockquote></details>

Thanks Jeremy!

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[geometry/utilities.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDfh7D9qcKdgknVB_C:-MtDfh7EDQTNkgQiLlbq:b-mr2gvd) ([raw file](https://github.com/robotlocomotion/drake/blob/3c3191a71e61d3f1f0a696430cdc297eb1dc4304/geometry/utilities.h#L118)):*
> ```objc
> 
> //@}
> ```

accidentally zapped this whitespace?  probably you should just revert the file?
___
*[geometry/utilities.cc, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDfmxy3FIBuK1sxVlg:-MtDfmxy3FIBuK1sxVlh:b-7bixg6) ([raw file](https://github.com/robotlocomotion/drake/blob/59b02d6810c2aa9419039131bc178c334a153d8c/geometry/utilities.cc#L6)):*
> ```cpp
> 
> #include "drake/common/drake_assert.h"
> #include "drake/common/text_logging.h"
> ```

not needed.  (just revert the file)?
___
*[geometry/test/utilities_test.cc, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDg4zsD2lBXMF11f6R:-MtDg4zsD2lBXMF11f6S:b-d89a8u) ([raw file](https://github.com/robotlocomotion/drake/blob/59b02d6810c2aa9419039131bc178c334a153d8c/geometry/test/utilities_test.cc#L10)):*
> ```cpp
> #include <gtest/gtest.h>
> 
> #include "drake/common/find_resource.h"
> ```

again, extra include and whitespace at the bottom.  just revert the file?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: 3 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @RussTedrake)

___
*[geometry/utilities.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDfh7D9qcKdgknVB_C:-MtEGxhE8IanTN5thQJY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3c3191a71e61d3f1f0a696430cdc297eb1dc4304/geometry/utilities.h#L118)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

accidentally zapped this whitespace?  probably you should just revert the file?
</blockquote></details>

Done.
___
*[geometry/utilities.cc, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDfmxy3FIBuK1sxVlg:-MtEGylVEjb6R8VBO2Rf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59b02d6810c2aa9419039131bc178c334a153d8c/geometry/utilities.cc#L6)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

not needed.  (just revert the file)?
</blockquote></details>

Done.
___
*[geometry/test/utilities_test.cc, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtDg4zsD2lBXMF11f6R:-MtEGzWcCwvftWUWeGIs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59b02d6810c2aa9419039131bc178c334a153d8c/geometry/test/utilities_test.cc#L10)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

again, extra include and whitespace at the bottom.  just revert the file?
</blockquote></details>

Done.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  +@sammy-tri for platform review

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-MtF64bL1cnixVL8yb2P:by1kl01)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
+@xuchenhan-tri for shadow platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-MtFO-p663cqOWucsonQ:bvy48z2)* status: LGTM missing from assignees sammy-tri(platform),xuchenhan-tri, missing label for release notes (waiting on @sammy-tri and @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: (didn't verify changes to ReadObjFile aside from the name and the header comments)

> Reviewed 3 of 11 files at r1, 8 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-MtFR0cW4kL-a6x1v8ih:b-jvpz0f)* status: LGTM missing from assignee xuchenhan-tri, missing label for release notes (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a few minor points.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351#-:-MtF_SBw7YUq78SyP_U-:byvkxji)* status: 3 unresolved discussions (waiting on @hongkai-dai)

___
*[geometry/optimization/vpolytope.cc, line 257 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFYL3vADOA-u37W5i9:-MtFYL3vADOA-u37W5iA:bdjr7q4) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/vpolytope.cc#L257)):*
> ```cpp
>                     qhull.qhullStatus(), qhull.qhullMessage()));
>   }
>   Matrix3Xd* vertices = static_cast<Matrix3Xd*>(data);
> ```

nit, should verify that user-data is non-null.
___
*[geometry/optimization/test/vpolytope_test.cc, line 149 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFVTeo9c83BNL1Bkjf:-MtFVTeo9c83BNL1Bkjg:b-618riq) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/test/vpolytope_test.cc#L149)):*
> ```cpp
> }
> 
> void CheckVertices(const Eigen::Ref<const Eigen::Matrix3Xd>& vertices,
> ```

nit, this function could use a comment about what it does. The name seems to imply that vertices == vertices_expected (up to some permutation), but it actually checks for something less strict.
___
*[geometry/test/read_obj_test.cc, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFYrtrCeQrdfKt7N39:-MtFYrtrCeQrdfKt7N3A:b-8o91vv) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/test/read_obj_test.cc#L14)):*
> ```cpp
> namespace {
> 
> // Check if the vertices match (not caring about the order).
> ```

nit, the comment is a bit misleading. The function only checks if the unique set of vertices match (which may not be what you wanted here?)
___
*[geometry/test/read_obj_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtF_fEM3s-yy_qHFW7L:-MtF_fEM3s-yy_qHFW7M:btyqic0) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/test/read_obj_test.cc#L76)):*
> ```cpp
> }
> 
> GTEST_TEST(ReadObjFile, Octahedron) {
> ```

BTW, I'm not quite seeing what this test provides in addition to the test above (which covers quads) and the one below (which covers tris).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @hongkai-dai)

___
*[geometry/test/read_obj_test.cc, line 14 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFYrtrCeQrdfKt7N39:-MtFnfKO1xoxve580qpO:b48821s) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/test/read_obj_test.cc#L14)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the comment is a bit misleading. The function only checks if the unique set of vertices match (which may not be what you wanted here?)
</blockquote></details>

Done. Since vertices_expected is provided by human, and the human would make sure that vertices_expected has unique element, I think this check is fine.
___
*[geometry/test/read_obj_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtF_fEM3s-yy_qHFW7L:-MtFnwzJ9aGDLSHsCYGf:b-ypvgj8) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/test/read_obj_test.cc#L76)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm not quite seeing what this test provides in addition to the test above (which covers quads) and the one below (which covers tris).
</blockquote></details>

I added a todo. I suppose for quad, the triangulated version is different from the un-triangulated version, but the octahedron they should be the same.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 5 of 11 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 149 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFVTeo9c83BNL1Bkjf:-MtFq5k5BezPWgDapsd0:b-i2u4ht) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/test/vpolytope_test.cc#L149)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this function could use a comment about what it does. The name seems to imply that vertices == vertices_expected (up to some permutation), but it actually checks for something less strict.
</blockquote></details>

Similar to the other `CheckVertices` method, this only checks the set of vertices are the same.
___
*[geometry/test/read_obj_test.cc, line 76 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtF_fEM3s-yy_qHFW7L:-MtFpySe5vLmfVxnTPWw:b-lg05o9) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/test/read_obj_test.cc#L76)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I added a todo. I suppose for quad, the triangulated version is different from the un-triangulated version, but the octahedron they should be the same.
</blockquote></details>

I see, thanks for the explanation.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 149 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFVTeo9c83BNL1Bkjf:-MtFsaMhDwPiwdHxHGIP:b-34uy8o) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/test/vpolytope_test.cc#L149)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Similar to the other `CheckVertices` method, this only checks the set of vertices are the same.
</blockquote></details>

Because `vertices_expected` is set by the user, and it has unique elements, I think checking if the set are the same is already enough.

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @hongkai-dai)

___
*[geometry/optimization/test/vpolytope_test.cc, line 149 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFVTeo9c83BNL1Bkjf:-MtFt2Nm97_Umob-6Mvi:bf3u1tf) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/test/vpolytope_test.cc#L149)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Because `vertices_expected` is set by the user, and it has unique elements, I think checking if the set are the same is already enough.
</blockquote></details>

I think that's fine. I was referring to the inaccuracy in the documentation of the function.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @xuchenhan-tri)

___
*[geometry/optimization/test/vpolytope_test.cc, line 149 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16351#-MtFVTeo9c83BNL1Bkjf:-MtGr8Hq9dwdAvAg9bCS:bk18bvr) ([raw file](https://github.com/robotlocomotion/drake/blob/d7d37bec51600ecae1a0967b66572815f8d670f8/geometry/optimization/test/vpolytope_test.cc#L149)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think that's fine. I was referring to the inaccuracy in the documentation of the function.
</blockquote></details>

I modified the documentation to make it more accurate.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16351)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform),xuchenhan-tri (waiting on @hongkai-dai)

**Pull request merged**
