### PR TITLE
Add scripts to test wheels

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create a script to run a basic sanity test on a wheel. Create a second script to drive the first, given a wheel version. For now, the tests this runs are fairly rudimentary, but this should provide a reasonable framework for growing the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: modulo some discussions.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994#-:-MnWmhmTDdEsCcc9PUPh:bqosi7o)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnBvsqMCvnB3yi9jCUs:-MnWmiDJ-IVAkmn6x9Om:b-6ygfyu) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I will test this locally.
</blockquote></details>

Seems to work great.

I'm still leaving this as "Working" status, since I'll need to re-test after any PR updates.

---
___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnWk88Q1nvjMLJk01Tn:b-b68dmk) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
> It is intended to be run inside either a "pristine" Ubuntu container, or one which has been provisioned by the accompanying test-wheels.sh script.

Why is it important to support both mechanisms?  It seems to me like supporting only of those options would be sufficient, with less code complexity and brittleness to maintain over time.  Since these testing scripts will themselves have no tests, they should be the most boring, obviously-correct, straight-line code that we can manage.
___
*[tools/wheel/dev/test/test-wheel.sh, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWn77s8Ta7bYPZDL2L:-MnWn77s8Ta7bYPZDL2M:b-36vifj) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L8)):*
> If no path is specified, "drake" from PyPI will be tested.

This seems extremely dangerous, and not at all useful -- the purpose of these scripts is a check a specific wheel build.  Defaulting to testing the latest already-published released is of no value, and risks that the test accidentally checks the public wheel, instead of the candidate wheel that we've just compiled.

If the user really wants to test the latest public whl, they can download those files manually and then run these test(s).
___
*[tools/wheel/dev/test/test-wheels.sh, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWlyjOB3ikc0KItjM_:-MnWlyjOB3ikc0KItjMa:b-9v7xso) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheels.sh#L1)):*
> ```Shell
> #!/bin/bash -e
> ```

Don't put `-e` in the shebang -- if a user does `bash test-wheels.sh`, it will get lost.  Put it as a `set -e` within the script itself.

Ditto throughout the PR.
___
*[tools/wheel/dev/test/test-wheels.sh, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWj2DyAvS85Ly9YXIz:-MnWj2DyAvS85Ly9YXJ-:bp9nq7u) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheels.sh#L7)):*
> ```Shell
> # argument is not given, the wheels are assumed to be in the current directory.
> 
> wv="$1"
> ```

nit In general within Drake, we avoid abbreviation.  It's more important that the code be easy to read / follow, than it is to be quick to key in or be ultra-compact on the screen.

Things like abbreviating "python" to just "py" are usually fine, but not initialisms like "wv" or "wd" or "tr".  Those are too obscure.

https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules has some general advice.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnWyNbk61DXkrHnJJZr:b-iywjxf) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> It is intended to be run inside either a "pristine" Ubuntu container, or one which has been provisioned by the accompanying test-wheels.sh script.

Why is it important to support both mechanisms?  It seems to me like supporting only of those options would be sufficient, with less code complexity and brittleness to maintain over time.  Since these testing scripts will themselves have no tests, they should be the most boring, obviously-correct, straight-line code that we can manage.
</blockquote></details>

The "code complexity and brittleness" consists of a whole 4 lines of code... one of which is obtaining the path to the current file (hardly "brittle"), and one of which is `fi`. For that small cost, it is possible to test a single wheel, or one which for some reason has a strange name, or test a wheel in an environment not covered by the driver script. That seems like useful added capability at a minimal cost.

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/wheel/dev/test/test-wheel.sh, line 8 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWn77s8Ta7bYPZDL2L:-MnX1bC_DH6rR_s6fZRZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> If no path is specified, "drake" from PyPI will be tested.

This seems extremely dangerous, and not at all useful -- the purpose of these scripts is a check a specific wheel build.  Defaulting to testing the latest already-published released is of no value, and risks that the test accidentally checks the public wheel, instead of the candidate wheel that we've just compiled.

If the user really wants to test the latest public whl, they can download those files manually and then run these test(s).
</blockquote></details>

Done.
___
*[tools/wheel/dev/test/test-wheels.sh, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWlyjOB3ikc0KItjM_:-MnX1cJx4aoiX-sbe1SF:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheels.sh#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Don't put `-e` in the shebang -- if a user does `bash test-wheels.sh`, it will get lost.  Put it as a `set -e` within the script itself.

Ditto throughout the PR.
</blockquote></details>

Done.
___
*[tools/wheel/dev/test/test-wheels.sh, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWj2DyAvS85Ly9YXIz:-MnX1dGa3tvF2bqQEzsi:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheels.sh#L7)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit In general within Drake, we avoid abbreviation.  It's more important that the code be easy to read / follow, than it is to be quick to key in or be ultra-compact on the screen.

Things like abbreviating "python" to just "py" are usually fine, but not initialisms like "wv" or "wd" or "tr".  Those are too obscure.

https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules has some general advice.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnXHvig9v7NeFdRlm3I:bsaub7h) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

The "code complexity and brittleness" consists of a whole 4 lines of code... one of which is obtaining the path to the current file (hardly "brittle"), and one of which is `fi`. For that small cost, it is possible to test a single wheel, or one which for some reason has a strange name, or test a wheel in an environment not covered by the driver script. That seems like useful added capability at a minimal cost.
</blockquote></details>

Just to be clear, I'm okay with passing the wheel name as `$1`.  This discussion is about the presence of `$2` vs the check-for-existence of `/opt/python`.

The complexity isn't about the number of lines of code, it's about having branches in the control flow of this script that don't end with "exit 1", i.e., where there are two different sequences of command that end in "exit 0".  For example, if I don't have `/opt/python` and also don't pass `$2`, won't I end up with some indeterminate venv version, that is different than my wheel?

In order to confirm both paths work, and reason about whether the script is doing what we want it to, I'll need to test both control flow paths manually every time we change this code.  That cost might be worth it, but I don't yet understand the benefits you're alluding to.

Can you give an example sequence of commands where I _want_ this script to call the "provision.sh"?  I would have started from some blank docker environment for some reason?  I can already test one wheel at a time or a wheel with a funny name (via `$1`).  The "environment not covered by the driver script" sounds like the most interesting.  What's an example of that, and why should I not start from a docker tag in that case as well, just like in the current tests?

**Comment by mwoehlke-kitware** [comment]
___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnXP7MB9cVD-ahFGHJf:b-luj3w4) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
> Can you give an example sequence of commands where I want this script to call the "provision.sh"? I would have started from some blank docker environment for some reason?

Yes. This is how the script was run prior to be89444ef. For example:

    docker run -v path/to/test:/test ubuntu:bionic \
      /test/test-wheel.sh /test/drake-0.32.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

...or:

    docker run -v path/to/wheel:/wheel -v path/to/test:/test ubuntu:bionic \
      /test/test-wheel.sh /wheel/drake-0.32.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

Alternatively, if I need to test the test scripts, but don't actually care about the wheel, I could run:

    docker run -v path/to/test:/test ubuntu:bionic /test/test-wheel.sh drake 36

>  I can already test one wheel at a time or a wheel with a funny name (via `$1`).

By editing `test-wheels.sh`? I don't know how you'd do so otherwise.

A funny version identifier is not a funny name. A funny name is e.g. `almost-drake-0.32.0-cp36-cp36m-linux_x86_64.whl`. (Well, again, I suppose you could edit `test-wheels.sh`...)

> The "environment not covered by the driver script" sounds like the most interesting. What's an example of that?

A non-LTS Ubuntu (if you can find one with a version of Python we support that still has online package archives or a docker image that already has Python; this probably won't be relevant until we're supporting Python 3.8 and 3.9) would be the most obvious. I'd say "Fedora", also (or any other non-Ubuntu), but you'd have to start those from an already-provisioned image, since the provisioning script obviously won't work.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnXn7qV2SY0n6RK_Ccs:b-s6gam2) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> Can you give an example sequence of commands where I want this script to call the "provision.sh"? I would have started from some blank docker environment for some reason?

Yes. This is how the script was run prior to be89444ef. For example:

    docker run -v path/to/test:/test ubuntu:bionic \
      /test/test-wheel.sh /test/drake-0.32.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

...or:

    docker run -v path/to/wheel:/wheel -v path/to/test:/test ubuntu:bionic \
      /test/test-wheel.sh /wheel/drake-0.32.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

Alternatively, if I need to test the test scripts, but don't actually care about the wheel, I could run:

    docker run -v path/to/test:/test ubuntu:bionic /test/test-wheel.sh drake 36

>  I can already test one wheel at a time or a wheel with a funny name (via `$1`).

By editing `test-wheels.sh`? I don't know how you'd do so otherwise.

A funny version identifier is not a funny name. A funny name is e.g. `almost-drake-0.32.0-cp36-cp36m-linux_x86_64.whl`. (Well, again, I suppose you could edit `test-wheels.sh`...)

> The "environment not covered by the driver script" sounds like the most interesting. What's an example of that?

A non-LTS Ubuntu (if you can find one with a version of Python we support that still has online package archives or a docker image that already has Python; this probably won't be relevant until we're supporting Python 3.8 and 3.9) would be the most obvious. I'd say "Fedora", also (or any other non-Ubuntu), but you'd have to start those from an already-provisioned image, since the provisioning script obviously won't work.
</blockquote></details>

This still isn't making sense to me.  Let me try to lay it out as I understand it, to see where I'm going wrong:

If I'm testing our default build process (e.g., during a release) with no variation, then I just run `test_wheels.sh` and the maybe-provision stanza on lines 16..19 in this file is a no-op, because I'm starting from a docker tag that already has the `/opt/python` set up ahead of time.

If I'm doing exploratory testing against a Fedora container, then there is no way that I want to run `provision.sh` inside of the container; it is hard-coded to call `apt`.  I need to start from some docker tag that already has an appropriate virtual environment set up in `/opt/python`.  Again, the maybe-provision stanza on lines 16..19 is a no-op.

If I want to test just one of wheels I have on hand vs one of our supported versions of Ubuntu, I can run it like so:

```patch
index 8cca722776..e694d6adad 100755
--- a/tools/wheel/dev/test/test-wheel.sh
+++ b/tools/wheel/dev/test/test-wheel.sh
@@ -13,11 +13,6 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
-if [ ! -d /opt/python ]; then
-    test_root="$(readlink -f "$(dirname "${BASH_SOURCE}")")"
-    "$test_root/provision.sh" $2
-fi
-
 . /opt/python/bin/activate
 
 pip install --upgrade pip

```

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ docker run \
  --rm -t \
  -v /home/jwnimmer/jwnimmer-tri/drake/tools/wheel/dev/test:/test \
  -v /home/jwnimmer/Downloads/whl:/wheel pip-drake:test-py36 \
  /test/test-wheel.sh \
  /wheel/drake-0.35.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36
...
/opt/python/lib/python3.6/site-packages/pydrake/share/drake
```

If I really need to test Ubuntu 19.10, then I can either go make a provisioned Docker tag for that manually, or just edit `test-wheels.sh` to add it as another case to cover.

For none of those use cases do I need to provision the virtual environment on demand as a fallback while I'm trying to run the test case.  I will always have the venv created in a docker tag ahead of time.  That seems like a good invariant to lock in place, rather than being blurry about?

**Review by mwoehlke-kitware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnaG_0y0fwzM1e7btuv:b-pzme71) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This still isn't making sense to me.  Let me try to lay it out as I understand it, to see where I'm going wrong:

If I'm testing our default build process (e.g., during a release) with no variation, then I just run `test_wheels.sh` and the maybe-provision stanza on lines 16..19 in this file is a no-op, because I'm starting from a docker tag that already has the `/opt/python` set up ahead of time.

If I'm doing exploratory testing against a Fedora container, then there is no way that I want to run `provision.sh` inside of the container; it is hard-coded to call `apt`.  I need to start from some docker tag that already has an appropriate virtual environment set up in `/opt/python`.  Again, the maybe-provision stanza on lines 16..19 is a no-op.

If I want to test just one of wheels I have on hand vs one of our supported versions of Ubuntu, I can run it like so:

```patch
index 8cca722776..e694d6adad 100755
--- a/tools/wheel/dev/test/test-wheel.sh
+++ b/tools/wheel/dev/test/test-wheel.sh
@@ -13,11 +13,6 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
-if [ ! -d /opt/python ]; then
-    test_root="$(readlink -f "$(dirname "${BASH_SOURCE}")")"
-    "$test_root/provision.sh" $2
-fi
-
 . /opt/python/bin/activate
 
 pip install --upgrade pip

```

```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ docker run \
  --rm -t \
  -v /home/jwnimmer/jwnimmer-tri/drake/tools/wheel/dev/test:/test \
  -v /home/jwnimmer/Downloads/whl:/wheel pip-drake:test-py36 \
  /test/test-wheel.sh \
  /wheel/drake-0.35.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36
...
/opt/python/lib/python3.6/site-packages/pydrake/share/drake
```

If I really need to test Ubuntu 19.10, then I can either go make a provisioned Docker tag for that manually, or just edit `test-wheels.sh` to add it as another case to cover.

For none of those use cases do I need to provision the virtual environment on demand as a fallback while I'm trying to run the test case.  I will always have the venv created in a docker tag ahead of time.  That seems like a good invariant to lock in place, rather than being blurry about?
</blockquote></details>

Huh?

Your diff makes no sense; I don't see any way making that change would be useful.

If you want to test one wheel, you can use one of the commands I described in the prior comment; no file edits needed. If you *have* the test-provisioned image, you can use it (and don't need to change `test-wheel.sh`; at that point you're running exactly what `test-wheels.sh` runs!), but you can also use `ubuntu:bionic`.

*In theory*, if you wanted to test e.g. Disco, you could run:

    docker run --rm -t \
      -v /home/jwnimmer/jwnimmer-tri/drake/tools/wheel/dev/test:/test \
      -v /home/jwnimmer/Downloads/whl:/wheel \
      ubuntu:disco \
      /test/test-wheel.sh \
      /wheel/drake-0.35.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

In practice, the package repositories seem to no longer exist (`apt update` produces a bunch of 404s, and `apt search python` returns only two packages, both crypto libraries with no obvious direct connection to Python).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mwoehlke-kitware)

___
*[tools/wheel/dev/test/test-wheel.sh, line 5 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnWk88Q1nvjMLJk01Tm:-MnalEsPCAPbyGJksQkG:b-nfh38e) ([raw file](https://github.com/robotlocomotion/drake/blob/e1d3cefcdbdf8f2b9e3787351c84ce9935f93b4a/tools/wheel/dev/test/test-wheel.sh#L5)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Huh?

Your diff makes no sense; I don't see any way making that change would be useful.

If you want to test one wheel, you can use one of the commands I described in the prior comment; no file edits needed. If you *have* the test-provisioned image, you can use it (and don't need to change `test-wheel.sh`; at that point you're running exactly what `test-wheels.sh` runs!), but you can also use `ubuntu:bionic`.

*In theory*, if you wanted to test e.g. Disco, you could run:

    docker run --rm -t \
      -v /home/jwnimmer/jwnimmer-tri/drake/tools/wheel/dev/test:/test \
      -v /home/jwnimmer/Downloads/whl:/wheel \
      ubuntu:disco \
      /test/test-wheel.sh \
      /wheel/drake-0.35.0-cp36-cp36m-manylinux_2_27_x86_64.whl 36

In practice, the package repositories seem to no longer exist (`apt update` produces a bunch of 404s, and `apt search python` returns only two packages, both crypto libraries with no obvious direct connection to Python).
</blockquote></details>

The diff I provided is my imagined resolution to this discussion (along with fixing the comment -- "It is intended to be run inside ~either a pristine Ubuntu container, or one which has been~ _an image_ provisioned by the accompanying test-wheels.sh script.").

My hypothesis for this whole discussion is that the `-d /opt/python` clause (that the patch removes) has zero benefit and yet actively makes this script more difficult to maintain (read, understand, test, and modify for future needs).  In all of the use cases that we care about, it is dead code, isn't it?

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15994)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15994#-MnBvsqMCvnB3yi9jCUs:-MnbltQk9SCpCvr6oAn6:bhuk7kd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Seems to work great.

I'm still leaving this as "Working" status, since I'll need to re-test after any PR updates.
</blockquote></details>

OK I'm busy doing tons of _other_ test builds today, so FYI I'm not going to re-test this after recent changes.  It seems on paper like it's in good shape, and we can always submit more fixes if I missed something.

---

**Pull request merged**
