### PR TITLE
Add fourbar and strandbeest to the gallery

### PR DESCRIPTION
**Pull request by joemasterjohn**
Adds videos as well as links to the source code for the fourbar and strandbeest examples.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181)

### CODE REVIEW

**Review by joemasterjohn — COMMENTED** [review]
+@sherm1 for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181#-:-MJ402wZ02CzhDPVBNlt:b7dve2f)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by joemasterjohn — COMMENTED** [review]
Here's the rendered changes so you don't have to build the site.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181#-:-MJ40zru3p-m83J_ie77:b-vhklp4)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Nice, thanks. Feature :lgtm:.
+@ggould-tri for platform review per rotation, please

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181#-:-MJ4LRgY0DnhVc_iYvNS:b-m9s3nn)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @joemasterjohn)

___
*[doc/gallery.rst, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14181#-MJ4L3gb800iGQJ1qD-m:-MJ4L3gb800iGQJ1qD-n:b-ds6ad1) ([raw file](https://github.com/robotlocomotion/drake/blob/1e09e5a9401abc68830dcfc30dd34c1e87164a7f/doc/gallery.rst#L110)):*
> ```reStructuredText
> ================================
> 
> Drake has examples of combining its rigid body kinematic tree dynamics with penalty forces to model a closed loop topology, such as a four bar linkage.
> ```

nit: line length should be <= 80 where possible

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sherm1)

___
*[doc/gallery.rst, line 110 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14181#-MJ4L3gb800iGQJ1qD-m:-MJ4NoeQ3qr8A8I7VRGI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1e09e5a9401abc68830dcfc30dd34c1e87164a7f/doc/gallery.rst#L110)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: line length should be <= 80 where possible
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14181#-:-MJ79mMV4l4Ku7BcfgT2:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform)

**Pull request merged**
