### PR TITLE
Lower bound in GcsTrajectoryOptimization subspace constraint should be -inf.

### LINKED ISSUE #21383: [GCSTrajOpt] Infeasible Subspace constraint
### What happened?

This [line](https://github.com/RobotLocomotion/drake/blob/a5638694d4a24642cbe2e60f46ce459442531fa1/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L460) is setting the lower bound of the subspace constraint to positive infinity, making it infeasible. The lower bound should be **- inf**.
We should also modify the test cases using [subspace regions](https://github.com/RobotLocomotion/drake/blob/a5638694d4a24642cbe2e60f46ce459442531fa1/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L1334) to ensure the solution actually goes through the expected subspace.

### Version

_No response_

### What operating system are you using?

_No response_

### What installation option are you using?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cohnt**
Fixes #21383.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Would +@wrangelvid be a good feature reviewer for this one?

**Review by wrangelvid — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 882 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-NxSaRwPD3HfMXIPHeoE:-NxSaRwPD3HfMXIPHeoF:bplml4f) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ba68436b7c353112f31ee4ce59a7afde5fd9058/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L882)):*
> ```cpp
> }
> 
> GTEST_TEST(GcsTrajectoryOptimizationTest, SimpleSubspaceTest) {
> ```

I am in favor of fixing the [test case](https://github.com/RobotLocomotion/drake/blob/a5638694d4a24642cbe2e60f46ce459442531fa1/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L1334) that was supposed to catch this rather than writing a new test case. The reason why this silently failed was that we didn't check the solution of SolveShortestPath, which due to the rounding would simply choose the other path. 
It shouldn't take too much effort to either check the solution path or to use SolveConvexRestrction to force a certain vertex sequence through a subspace.

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release please

**Comment by cohnt** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-mosek-release please

**Review by cohnt — COMMENTED** [review]
I was having a bunch of trouble trying to isolate this typo from the underlying bug in #21386. So I've gone ahead and fixed the underlying bug in `graph_of_convex_sets.cc` -- the new behavior is that if you somehow create one of these trivially-infeasible constraints, it throws an error when you try to construct its perspective.

The first commit fixes the underling bug in gcs, and causes the existing subspace test case to fail. (It also adds tests verifying this behavior.) The second commit fixes the bug in gcstrajopt, so that all test cases pass again.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-:-NzcMHr07yeBBToQqQb0:b7c1v7e)* status: 1 unresolved discussion, LGTM missing from assignee wrangelvid, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

___
*[`planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc` line 882 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-NxSaRwPD3HfMXIPHeoE:-NzcMq-g8OSjf6izT3mB:b-dy6fn2) ([raw file](https://github.com/RobotLocomotion/drake/blob/4ba68436b7c353112f31ee4ce59a7afde5fd9058/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L882)):*
<details><summary><i>Previously, wrangelvid (David von Wrangel) wrote…</i></summary><blockquote>

I am in favor of fixing the [test case](https://github.com/RobotLocomotion/drake/blob/a5638694d4a24642cbe2e60f46ce459442531fa1/planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc#L1334) that was supposed to catch this rather than writing a new test case. The reason why this silently failed was that we didn't check the solution of SolveShortestPath, which due to the rounding would simply choose the other path. 
It shouldn't take too much effort to either check the solution path or to use SolveConvexRestrction to force a certain vertex sequence through a subspace.
</blockquote></details>

Fixing the underlying bug in gcs caused the original subspace test case to fail without any modification. Fixing the bug in gcstrajopt then allows this test to pass again. I've removed the additional test case I had proposed.

**Review by wrangelvid — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-:-NzizE9c2_jvpNtFpm5b:bg7igkv)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Comment by cohnt** [comment]
+@rpoyner-tri for platform review per the schedule, please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-:-O-77v7dD3WAcXWOKX4z:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cohnt)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21384#-:-O-78BPSAApT3ENzTdLY:bm9o57a)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),wrangelvid

**Pull request merged**
