### PR TITLE
py mp: Reorder overall bindings for better Python type signatures

### LINKED ISSUE #15407: py mp: Should register `Binding[]` before `MathematicalProgram`; otherwise, type sig. shows up as C++ typeid
Presently, showing `Binding` and other related types show their C++ type in Python type signatures. For example:
https://github.com/RobotLocomotion/drake/pull/15353#pullrequestreview-704674292
```
TypeError: CheckSatisfied(): incompatible function arguments. The following argument types are supported:
    1. (..., binding: drake::solvers::Binding<drake::solvers::Constraint>, ...) -> bool
    2. (..., bindings: ...) -> bool
```

\cc @hongkai-dai @RussTedrake

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Otherwise, type signatures may have C++ types

Resolves #15407
Will be better in conjunction with #15409 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Doc generation:
```
$ bazel run //doc:build -- --serve pydrake.solvers.mathematicalprogram
$ xdg-open http://127.0.0.1:8000/pydrake/pydrake.solvers.mathematicalprogram.html#pydrake.solvers.mathematicalprogram.MathematicalProgram.Add2NormSquaredCost
```

Before:
> image
After:
> image

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai for feature review, please!
+@seancurtis-tri for platform review, please!

\cc @russtedrake 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410#-:-Meh9dDBB9SK9xIFJZJt:b5g6z1i)* status: LGTM missing from assignees hongkai-dai,SeanCurtis-TRI(platform) (waiting on @hongkai-dai and @SeanCurtis-TRI)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410#-:-MehNITr08rY-L0XC9Nt:bg7igkv)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Just a quick question (see below).

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410#-:-MejnXeI2Nt9cQPhmo3z:b-gdvdd2)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-MejnG192Dew6HLlP7wk:b3g031d) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
> ```cpp
>   py::module::import("pydrake.symbolic");
> 
>   BindEvaluatorsAndBindings(m);
> ```

By decomposing it in this manner, does this provide sufficient guidance to future changes to mathematical program to preserve the effect you've achieved here?

Or, the true question is, what informs other developers in the future on how to avoid re-introducing the thing you're correct here? Is this new structure enough, or should there be some commented guidance?

I haven't played with these bindings at all (and have minimal experience with MathematicalProgram). I can imagine that someone who plays in this domain would see these function names and always bind things in the right place such that the order induced here is sufficient. I'd just like you to make that claim.  :)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-MezsKRB4hQrj_hSypM-:bls3wa5) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

By decomposing it in this manner, does this provide sufficient guidance to future changes to mathematical program to preserve the effect you've achieved here?

Or, the true question is, what informs other developers in the future on how to avoid re-introducing the thing you're correct here? Is this new structure enough, or should there be some commented guidance?

I haven't played with these bindings at all (and have minimal experience with MathematicalProgram). I can imagine that someone who plays in this domain would see these function names and always bind things in the right place such that the order induced here is sufficient. I'd just like you to make that claim.  :)
</blockquote></details>

Nothing here strictly prevents the defect of consuming `typeid`s that haven't been preventing. I think that could be addressed, but in a separate fashion (either checking resolved docstrings for `typeid` signatures, or telling `pybind11` to fail fast if it sees it).

This is a minor fix to alleviate a minor issue, so I don't think it's necessary to try to fix all usages yet?
I can file a longer-term issue if you like!

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-MezvFGO-qSSFAO7335T:b74f8h0) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Nothing here strictly prevents the defect of consuming `typeid`s that haven't been preventing. I think that could be addressed, but in a separate fashion (either checking resolved docstrings for `typeid` signatures, or telling `pybind11` to fail fast if it sees it).

This is a minor fix to alleviate a minor issue, so I don't think it's necessary to try to fix all usages yet?
I can file a longer-term issue if you like!
</blockquote></details>

The goal was not to fix all usages (or even to make this fix bullet proof). The goal was to have *something* in this PR that would reduce the odds of the corrected issue coming right back. I was asking if the inherent structure does that. I infer from your response that it does not.

Failing that, a comment clarifying best practice to avoid re-introducing the issue would be a fine alternative.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-MezyHNN3TboZaQKZpDp:bsk44z7) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The goal was not to fix all usages (or even to make this fix bullet proof). The goal was to have *something* in this PR that would reduce the odds of the corrected issue coming right back. I was asking if the inherent structure does that. I infer from your response that it does not.

Failing that, a comment clarifying best practice to avoid re-introducing the issue would be a fine alternative.
</blockquote></details>

Working: It's a general pattern though, so it's less useful here, and more useful in something like `pydrake_doxygen.h`. Will do so in separate PR.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410#-:-Mf-82g27JOYxt5MrPBG:bmxilld)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-Mf-80_A9UgTmyvrI7_E:bq0ncok) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: It's a general pattern though, so it's less useful here, and more useful in something like `pydrake_doxygen.h`. Will do so in separate PR.
</blockquote></details>

sounds good

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15410)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),hongkai-dai (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/solvers/mathematicalprogram_py.cc, line 1820 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15410#-MejnG192Dew6HLlP7wj:-Mf-N5a94_4_HE0dDPku:b-yp3rkb) ([raw file](https://github.com/robotlocomotion/drake/blob/e0f0b2ce2e2bf041f6a1890e85dfb71fb66aebb6/bindings/pydrake/solvers/mathematicalprogram_py.cc#L1820)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

sounds good
</blockquote></details>

OK Done in #15429 - thanks!

**Pull request merged**
