### PR TITLE
New SpatialInertia factory method SolidBoxWithMass().

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@sherm1 

Note:  If OK with you, I'll fix the CI failure with my next commit -- here is the summary.
multibody/plant/test/multibody_plant_jacobians_test.cc:367:50: 
error: use of undeclared identifier 'mass_link'; did you mean 'mass_link_'?
        SpatialInertia<double>::SolidBoxWithMass(mass_link, link_length_, 1, 1);
                                                 ^~~~~~~~~
                                                 mass_link_
multibody/plant/test/multibody_plant_jacobians_test.cc:414:16: note: 'mass_link_' declared here
  const double mass_link_ = 5.0;    // kg

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSMFdqP2y2SN4hk2TNi:bez8s7)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Tidies up those call sites very nicely!
Feature :lgtm: pending CI fix and a nit

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSMgMX83-IhV1G9fk3Y:bjzdw37)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-NSMfla82ONh96xYtupZ:-NSMfla82ONh96xYtup_:bdjhytj) ([raw file](https://github.com/RobotLocomotion/drake/blob/1cf3ab4b987a0f50951c05f13bda09ac70139b3e/multibody/tree/spatial_inertia.cc#L61)):*
> ```cpp
>   if (lx <= 0 || ly <= 0 || lz <= 0) {
>     std::string error_message = fmt::format("{}(): One or more dimensions of a "
>     "solid box is negative or zero: ({}, {}, {}).",
> ```

nit: needs reformatting
Also, BTW can be `const std::string`

**Review by mitiguy — COMMENTED** [review]
Ready for another look.  
For consistency with the rest of spatial inertia.cc, I also update related error messages with "const" keyword.
While doing so, I updated parameter names to better match some of the recently updated parameter names in the header file.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSNYWVr3RzgphRRWDq4:b-khr5ei)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

___
*[`multibody/tree/spatial_inertia.cc` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-NSMfla82ONh96xYtupZ:-NSNYGm9-h6MkmvgSSvC:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/1cf3ab4b987a0f50951c05f13bda09ac70139b3e/multibody/tree/spatial_inertia.cc#L61)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: needs reformatting
Also, BTW can be `const std::string`
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
+@rpoyner-tri for platform review if it's not too late, else punt to Grant

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSNa0GH8ObEPQ9ORses:bpejg49)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSNh56nEQAmqdL4QQMS:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSNhpZn7R8eKsYAv1Fa:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @mitiguy)

**Review by rpoyner-tri — COMMENTED** [review]
Last question: why "release notes none"? Isn't this a new public API, therefore a new feature?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19141#-:-NSNhrMF0uB7_AUdrOkp:bdrawhj)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Comment by rpoyner-tri** [comment]
We can change the release notes label after the fact and it will still be of use to the release notes authors.

**Comment by rpoyner-tri** [comment]
-(release notes: none) +(release notes: feature) (too much data into release notes is better than not enough.)

**Comment by mitiguy** [comment]
Similar to what I did earlier this week with SolidBoxWithDensity(), SolidCylinderWithDensity(), etc., -- and that worked very well for unifying the keyword arguments in Python later,  I plan on doing a sequence of C++  only functions.  Then in a single subsequent PR, I am planning to Python-bind all the new functions and add +(release notes: feature) on that.  Otherwise, we may have duplicate (release notes: feature) -- one for the early C++ functions that dribble in, and one for the whole Python bindings that follow.  However, let's proceed as you deem best.

**Comment by mitiguy** [comment]
PR https://github.com/RobotLocomotion/drake/pull/19141 helps resolve part of issue https://github.com/RobotLocomotion/drake/issues/18416.

**Pull request merged**
