### PR TITLE
Convert State from a struct to a class. 

### PR DESCRIPTION
**Pull request by david-german-tri**
Impose const correctness on access to the members of State.  Move ContinuousState to its own file.

Incidentally, makes almost all references briefer.

+@amcastro-tri for feature review, +@ggould-tri for platform review, which can probably proceed in parallel.  There are many lines in this PR, but none of them are substantive.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3565)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
:lgtm:, just a few BTW's

---

Reviewed 15 of 33 files at r1.
Review status: 15 of 32 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/automotive/simple_car-inl.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNIl0dN6h2nAoAGuFP:-KSNIl0dN6h2nAoAGuFQ:b-9k1r7u) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/automotive/simple_car-inl.h#L61)):*
> ```objc
>   // Obtain the state.
>   const systems::VectorBase<T>& context_state =
>       context.get_continuous_state()->get_state();
> ```

BTW, same here about a `get_state` after another `get_state`, you get the idea.

---

*[drake/automotive/test/simple_car_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNIQ67PO0mmX6mEuwR:-KSNIQ67PO0mmX6mEuwS:b-jfsjzd) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/automotive/test/simple_car_test.cc#L33)):*
> ```cpp
>   SimpleCarState<double>* continuous_state() {
>     auto result = dynamic_cast<SimpleCarState<double>*>(
>         context_->get_mutable_continuous_state()->get_mutable_state());
> ```

BTW, it's kind of odd that we have sort of like a concatenation of `get_state()` methods here. Probably we should refactor the second one to be more explicit? like `get_mutable_state_vector()`? and so it returns a vector instead of a state unlike the first `get`.

---

*[drake/systems/framework/context.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNHSQb8-SclvrdheU6:-KSNHSQcAsV4NAK_gJuc:b-o3csrk) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/context.h#L76)):*
> ```objc
>   virtual State<T>* get_mutable_state() = 0;
> 
>   /// Sets the continuous state to @p xc, overwriting whatever was there before.
> ```

BTW, maybe "overwriting" --> "destroying" is more accurate?

---

*[drake/systems/framework/context.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNHg_ZYdRXUmkvWA5g:-KSNHg_ZYdRXUmkvWA5h:b-j3s1k4) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/context.h#L87)):*
> ```objc
>   }
> 
>   /// Returns a const reference to the continuous component of the state,
> ```

BTW, `const reference` to `const pointer` to be consistent with the doxy comment for the method above?

---

*[drake/systems/framework/primitives/integrator.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNJ420jeedHGIRgcwb:-KSNJ420jeedHGIRgcwc:bm9yj3v) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/primitives/integrator.cc#L29)):*
> ```cpp
>   // constructions.
>   VectorBase<T>* state_vector =
>       context->get_mutable_continuous_state()->get_mutable_state();
> ```

BTW, ah! I see you added the explicit type here (nice!). That's what I was trying to convey with the "concatenation of get-state comments above"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-:-KSNJRHoEaUwkSBe4-zN:b-o7x8jp)*

**Comment by jwnimmer-tri** [comment]
-@ggould-tri +@jwnimmer-tri for platform

---

Review status: 15 of 32 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-:-KSNuEXx4hrD77JyJUzJ:b-vohxt6)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/test/simple_car_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNIQ67PO0mmX6mEuwR:-KSNuhOXiwJBLZsMGBi9:b3iafyb) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/automotive/test/simple_car_test.cc#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, it's kind of odd that we have sort of like a concatenation of `get_state()` methods here. Probably we should refactor the second one to be more explicit? like `get_mutable_state_vector()`? and so it returns a vector instead of a state unlike the first `get`.
</details>
FYI The automotive code is known to be overly verbose, because we haven't added good sugar yet for custom vector subclasses.  I wouldn't worry about it right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565)*

**Comment by jwnimmer-tri** [comment]
Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/framework/continuous_state.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwol3rIXBYqekGAB5:-KSNwol3rIXBYqekGAB6:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L3)):*
> ```objc
> #pragma once
> 
> #include <cstdint>
> ```

Unused?

---

*[drake/systems/framework/continuous_state.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwqDe-Ml3p6OzYLFF:-KSNwqDe-Ml3p6OzYLFG:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L5)):*
> ```objc
> #include <cstdint>
> #include <memory>
> #include <set>
> ```

Unused?

---

*[drake/systems/framework/continuous_state.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwuwtXCEvZ86vlFRg:-KSNwuwuJceiRXbLTiDH:b-ciom1o) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L8)):*
> ```objc
> #include <stdexcept>
> #include <string>
> #include <vector>
> ```

Unused?

---

*[drake/systems/framework/continuous_state.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwiNcR2q_yW9cJ64h:-KSNwiNdpZ76o4s8Cefy:b18opoo) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L23)):*
> ```objc
> /// @tparam T A mathematical type compatible with Eigen's Scalar.
> template <typename T>
> class ContinuousState {
> ```

Disable copy and assign.

---

*[drake/systems/framework/state.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNx1iw7xrU5MeX6ucX:-KSNx1iw7xrU5MeX6ucY:b18opoo) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/state.h#L15)):*
> ```objc
> /// @tparam T A mathematical type compatible with Eigen's Scalar.
> template <typename T>
> class State {
> ```

Disable copy and assign.

---

*[drake/systems/framework/examples/spring_mass_system.cc, line 89 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNvl2eLKAww_sWt8uV:-KSNvl2fXj4RMa2oa1EP:b-gt26mh) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/examples/spring_mass_system.cc#L89)):*
> ```cpp
>   const int num_q = 1, num_v = 1, num_z = 1;
>   context->set_continuous_state(std::make_unique<ContinuousState<double>>(
>       std::move(state), num_q, num_v, num_z));
> ```

FYI God bless.  The `/* name */` thing drives me batty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565)*

**Comment by david-german-tri** [comment]
Review status: 29 of 32 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/automotive/test/simple_car_test.cc, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNIQ67PO0mmX6mEuwR:-KSNzhoFxP74nLfITZfC:b-mz2lju) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/automotive/test/simple_car_test.cc#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> FYI The automotive code is known to be overly verbose, because we haven't added good sugar yet for custom vector subclasses.  I wouldn't worry about it right now.
</details>
I do agree that `ContinuousState::get_state` and `::get_mutable_state` are awkward names.  Adding `_vector` or `_data` might help.  Unrelated to this PR, though.

---

*[drake/systems/framework/context.h, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNHSQb8-SclvrdheU6:-KSO-59e6DQxykJSJkAL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/context.h#L76)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, maybe "overwriting" --> "destroying" is more accurate?
</details>
Done.

---

*[drake/systems/framework/context.h, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNHg_ZYdRXUmkvWA5g:-KSO-AKlYbNkD-E6lmve:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/context.h#L87)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> BTW, `const reference` to `const pointer` to be consistent with the doxy comment for the method above?
</details>
Done.

---

*[drake/systems/framework/continuous_state.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwol3rIXBYqekGAB5:-KSO-HL4SgEdmg2YFWXM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---

*[drake/systems/framework/continuous_state.h, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwqDe-Ml3p6OzYLFF:-KSO-Hotw5VfMpKT1rfo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---

*[drake/systems/framework/continuous_state.h, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwuwtXCEvZ86vlFRg:-KSO-ICXBJuY40Ja01zj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Unused?
</details>
Done.

---

*[drake/systems/framework/continuous_state.h, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNwiNcR2q_yW9cJ64h:-KSO-owAmo0_02IPsFq2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/continuous_state.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Disable copy and assign.
</details>
Done.

---

*[drake/systems/framework/state.h, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-KSNx1iw7xrU5MeX6ucX:-KSO00ey_hBTtMQcdO-K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9d0e3ad8d086aa09fa0f4cdee5b8faf998dafe09/drake/systems/framework/state.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Disable copy and assign.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3565#-:-KSO1gwVKl-6Vte9evPQ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
I'll push the button for David, lest he lost some merge-conflict battle.

**Comment by david-german-tri** [comment]
Thanks!

**Pull request merged**
