### PR TITLE
[fem] Remove pdf file from documentation

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16758)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@ericcousineau-tri for both reviews please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16758#-:-MxpRuGG0FqFCfhZpGgM:b-19qv8w)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! See initial comment.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16758#-:-Mxp_S_v61ULp4v7Lwld:byhibhh)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @xuchenhan-tri)

___
*[multibody/fem/doc/stiffness_matrix.pdf, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16758#-Mxp_Pxv8sb7rR_iNbfL:-Mxp_Pxv8sb7rR_iNbfM:bdrk3tc) ([raw file](https://github.com/robotlocomotion/drake/blob/853d4d45431accb37883e107b1792a116764b227/multibody/fem/doc/stiffness_matrix.pdf#L0)):*
Unclear why this file remains - should this be removed?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2, thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16758#-:-MxpefBT4qY-9DnumxkF:bmpd3jd)* status: missing label for release notes (waiting on @xuchenhan-tri)

**Comment by EricCousineau-TRI** [comment]
Skipping slow build

**Pull request merged**
