### PR TITLE
Remove the use of `testUtil` from within `drake/systems`

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3276)

### CODE REVIEW

**Comment by liangfok** [comment]
Overall, this PR does a wonderful and significant cleanup.

However, it also switches from measuring execution time in milliseconds to seconds. Has this change impacted measurement precision? It might if the user is saving the measured values in text log files since typically only a limited number of decimal places are saved. Thoughts?

Why not use `std::high_resolution_clock()`?

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KQ8hIhXv2e27bXTWHaM:bm5qf6)*

**Comment by jwnimmer-tri** [comment]
> [This] switches from measuring execution time in milliseconds to seconds.

The units of reporting are changed, but the measurements are still done with sub-second precision.  I ran the RBT benchmark before and after this edit, and the results were similar:

Before:
```
no gradients: 3.336 ms
autodiff fixed max size: 28.663 ms
...
```

After:
```
no gradients: 0.00330296 s
autodiff fixed max size: 0.0286834 s
...
```

> Has this change impacted measurement precision? It might if the user is saving the measured values in text log files since typically only a limited number of decimal places are saved. Thoughts?

Given the above sample output, I don't think this is a concern.

> Why not use std::high_resolution_clock()?

When I quickly glanced at it, that block did not appear to be guaranteed to be monotonic.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KQ8kAX-Ii8sz11rLbtY:b-kpwtrr)*

**Comment by liangfok** [comment]
In the spirit and recognition that we are in a sprint, I bestow upon this PR a :lgtm: under one condition:

1. Add a CHANGELOG.md entry indicating the API change for measuring method execution times and the fact that the measurement unit was changed from milliseconds to seconds.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KQ8pYHS62pHkJ9FKa5k:bxrcu0r)*

**Comment by jwnimmer-tri** [comment]
Done.

---

Review status: 20 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KQDU1jX7xVlHzZ_P1dR:b-896fix)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 26 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KQDYg0Whpnp1tRJs1-g:-KQDYg0Whpnp1tRJs1-h:b2cxwkv) ([raw file](https://github.com/robotlocomotion/drake/blob/ffdefa7382fe2545daf5c2f05f725155133760e2/CHANGELOG.md#L26)):*
> ```Markdown
> ### Changed
> 
>  - [#3276][] The measure::execution function has been replaced by MeasureExecutionTime.
> ```

BTW: nit: Surround C++ class / method names with back ticks so they appear in a different font, which indicate they are actual software artifacts.

Also add a sentence saying the units changed from milliseconds to seconds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 26 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KQDYg0Whpnp1tRJs1-g:-KQD_APvGwicpBF1tZj-:b-p685up) ([raw file](https://github.com/robotlocomotion/drake/blob/ffdefa7382fe2545daf5c2f05f725155133760e2/CHANGELOG.md#L26)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: Surround C++ class / method names with back ticks so they appear in a different font, which indicate they are actual software artifacts.
> 
> Also add a sentence saying the units changed from milliseconds to seconds.
</details>
The prior units were undocumented; the new units are documented; the changelog should be as brief as reasonably possible; I don't think the units detail is worth writing about here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 26 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KQDYg0Whpnp1tRJs1-g:-KQD_obUg1WnkTZk9rDY:b-jufc4y) ([raw file](https://github.com/robotlocomotion/drake/blob/ffdefa7382fe2545daf5c2f05f725155133760e2/CHANGELOG.md#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The prior units were undocumented; the new units are documented; the changelog should be as brief as reasonably possible; I don't think the units detail is worth writing about here. 
</details>
OK. SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 26 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KQJAilV7JEqslgqy08v:-KQJAilV7JEqslgqy08w:b-sihhoh) ([raw file](https://github.com/robotlocomotion/drake/blob/94a0f30d6cdaf313d326bcac44ec809e39b2a03b/CHANGELOG.md#L26)):*
> ```Markdown
> ### Changed
> 
>  - [#3276][] The `measure::execution` function has been replaced by `MeasureExecutionTime`.
> ```

BTW: nit: Added `()` behind method names to indicate that they are method names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KQfDFRTRX6BkI7jx1H-:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 39 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KR-G5EQX6PIbT-POMgO:-KR-G5EQX6PIbT-POMgP:b-o7ywv1) ([raw file](https://github.com/robotlocomotion/drake/blob/1b0a3f2f3e8768002f431ba728449455f2e321aa/CHANGELOG.md#L39)):*
> ```Markdown
>  - [#2984][] Renamed and moved `Polynomial.h` and `TrigPoly.h` from `drake/util` to `drake/common` and into the `drakeCommon` library.
>  - [#2963][] Rename RigidBody::CollisionElement to RigidBodyCollisionElement.
>  - [#3010][] All header file names under `solvers` are now spelled with lower case and underscore names.
> ```

why deleted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-:-KR-Gl4D4wrUHF6Ox9OV:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 39 \[r4\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3276#-KR-G5EQX6PIbT-POMgO:-KR-N6-f0anzXOgi7fnS:bupmmn8) ([raw file](https://github.com/robotlocomotion/drake/blob/1b0a3f2f3e8768002f431ba728449455f2e321aa/CHANGELOG.md#L39)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> why deleted?
</details>
It was a duplicate of ~three lines above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3276)*

**Pull request merged**
