### PR TITLE
update names in prius.urdf

### PR DESCRIPTION
**Pull request by RussTedrake**
the names of the suspension links were confusing (I believe because they started as the contact points at the bottom of the wheels, before we were doing the full cylinder collision geometry).  this PR cleans that up, and also clarifies the start-up instructions.

@Sproulx -- please review.

### CODE REVIEW

**Comment by RussTedrake** [comment]
@jamiesnape -- PTAL at the msvc jenkins build failures?

**Comment by Sproulx** [comment]
Only thing that seems off to me is that the contact points were/are at the bottom of the wheels. You've renamed them "*_wheel_center", I don't think they're actually the centers since I don't see any transforms changed. But, functionally, it's the same as before.

**Comment by RussTedrake** [comment]
That's what I thought, too.  But they seem to be at the center now.  And the suspension goes up from the center 3.2whatever. Can you confirm?

**Comment by Sproulx** [comment]
Using the Drake Visualizer with Matlab, they still show up at the base of the wheel, for me. I can confirm that the urdf exhibits the same behavior as before.
prius_suspension

**Comment by jamiesnape** [comment]
retest this please

**Comment by liangfok** [comment]
I tried to load the prius.urdf into the [ROS RViz](http://wiki.ros.org/rviz) application to visualize the robot's kinematics but encountered the following errors:

```
[ERROR] [1456848270.302994987]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303024898]: Could not parse inertial element for Link [left_wheel]
[ERROR] [1456848270.303048791]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303064009]: Could not parse inertial element for Link [right_wheel]
[ERROR] [1456848270.303087632]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303103729]: Could not parse inertial element for Link [left_wheel_rear]
[ERROR] [1456848270.303124134]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303142480]: Could not parse inertial element for Link [right_wheel_rear]
[ERROR] [1456848270.303166447]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303182001]: Could not parse inertial element for Link [chassis_floor]
[ERROR] [1456848270.303210534]: Visual material must contain a name attribute
[ERROR] [1456848270.303227826]: Could not parse visual element for Link [front_left_wheel_center]
[ERROR] [1456848270.303246739]: Visual material must contain a name attribute
[ERROR] [1456848270.303262295]: Could not parse visual element for Link [front_right_wheel_center]
[ERROR] [1456848270.303280035]: Visual material must contain a name attribute
[ERROR] [1456848270.303294403]: Could not parse visual element for Link [rear_left_wheel_center]
[ERROR] [1456848270.303312139]: Visual material must contain a name attribute
[ERROR] [1456848270.303326942]: Could not parse visual element for Link [rear_right_wheel_center]
[ERROR] [1456848270.303350496]: inertia element must have ixx,ixy,ixz,iyy,iyz,izz attributes
[ERROR] [1456848270.303366506]: Could not parse inertial element for Link [body]
[ERROR] [1456848270.303394210]: joint limit: no effort
[ERROR] [1456848270.303409447]: Could not parse limit element for joint [steering]
[ERROR] [1456848270.303424943]: joint xml is not initialized correctly
```
I will fix these problems soon.

**Comment by liangfok** [comment]
I loaded Drake master's Prius.urdf model in [ROS RViz](http://wiki.ros.org/rviz) and ran [ROS joint_state_publisher](http://wiki.ros.org/joint_state_publisher) to control the kinematic state of the model. Using [RViz's axes plugin](http://wiki.ros.org/rviz/DisplayTypes/Axes), I visualized the frames of the left/right wheel and left/right wheel_center links. Below is the result:

drake_prius_front_wheel_frames

Clearly, the links that are currently called "wheel_center" should be called "contact point" as they were originally called.

I still need to look into this more to understand how the contact point links connect to the rest of the body.

**Comment by liangfok** [comment]
Here is a better RViz visualization of Drake Master's URDF that shows how the steering links (front_axle, left_tie_rod_arm, right_tie_rod_arm, and tie_rod) actually reside on the ground and thus do not match the visualization:

prus_urdf_model_visualizer

This explains how the contact point links can reside on the ground even though they reside between the wheel joints and the hub joints.

**Comment by RussTedrake** [comment]
ah.  no wonder!  thanks.  
we should definitely clean this up.

**Pull request closed without merging**
