### PR TITLE
Port multibody to model-based port declarations

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #5431.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5512)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@amcastro-tri for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5512#-:-KfJkWOmkkZAUKISZofj:b5xll3r)*

**Comment by amcastro-tri** [comment]
I really like this. I like how now the declaration of these abstract valued ports is self-contained in the system's constructor. In my mind, as it should be. :lgtm_strong: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5512#-:-KfMMJCgZyCDeGKgD5KR:b-4x1ast)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5512#-:-KfMNP_fywp5fQ9L9ivm:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5512#-:-KfMbmg0-k99uSYbB3CP:bnfp4nl)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri ,  I don't have the platform-reviewer bit. Should I ask for it to David?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5512#-:-KfMbr4WTSgVQgYlq12Q:bnknykl)*

**Pull request merged**
