### PR TITLE
Clarabel and SCS support L2NormCost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Towards #20552

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-:-NujEKl_CqsgWEAVd7Ib:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-:-NujGRIk5cKHxmFsXJU-:bnfp4nl)* status: 3 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/test/l2norm_cost_examples.h` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujGA3W87mq15dGozMd:-NujGA3W87mq15dGozMe:b45h) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L55)):*
> ```objc
> };
> 
> // Compute the shortest distance from a plane to two points
> ```





_Suggestion:_
```objc
on
```
___
*[`solvers/test/l2norm_cost_examples.h` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujFzzWA3wpymLR1Y1V:-NujFzzWA3wpymLR1Y1W:undefined) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L59)):*
> ```objc
> // s.t cᵀ*(A*x) = d
> // This test L2NormCost with linear constraints.
> // Notice we take an invertible transformation A.
> ```





_Suggestion:_
```objc
// This tests L2NormCost with linear constraints.
// A must be an invertible linear transformation.
```
___
*[`solvers/test/l2norm_cost_examples.cc` line 80 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujGFF70805vFesIFkG:-NujGFF70805vFesIFkH:b8bqqdz) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.cc#L80)):*
> ```cpp
>   A_ << 1, 3, -2,
>         2, 1, 4,
>         0, 1, 0;
> ```

nit: whitespace



_Suggestion:_
```cpp
  A_ << 1, 3, -2,
        2, 1,  4,
        0, 1,  0;
```

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-:-NujsuKe3muMkTq4zL5-:bqljb9l)* status: 3 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-:-NujufoB8KgsGAwvkrEI:bnfp4nl)* status: 5 unresolved discussions

___
*[`solvers/test/l2norm_cost_examples.h` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujuNQo8S77P9iuWtNr:-NujuNQo8S77P9iuWtNs:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L37)):*
> ```objc
> // -1 <= x[2] <= 1
> // x[0]² + x[1]² <= 4
> // This test L2NormCost with Lorentz cone and bounding box constraints.
> ```

typo



_Suggestion:_
```objc
tests
```
___
*[`solvers/test/l2norm_cost_examples.h` line 58 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujtziSBIGpY_U_kTyS:-NujtziSBIGpY_U_kTyT:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L58)):*
> ```objc
> // min |A * x - pt0|₂ + |A * x - pt1|₂
> // s.t cᵀ*(A*x) = d
> // This test L2NormCost with linear constraints.
> ```

typo



_Suggestion:_
```objc
tests
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271)* status: 2 unresolved discussions

___
*[`solvers/test/l2norm_cost_examples.h` line 55 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujGA3W87mq15dGozMd:-Nulb48b715jdtiFiaj0:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L55)):*
> ```objc
> };
> 
> // Compute the shortest distance from a plane to two points
> ```

Done.
___
*[`solvers/test/l2norm_cost_examples.h` line 59 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21271#-NujFzzWA3wpymLR1Y1V:-NulbB2MAalvTm7ev6BC:b2j28wm) ([raw file](https://github.com/RobotLocomotion/drake/blob/4d5470fbb895cef24c030ccc67acdeef6213547c/solvers/test/l2norm_cost_examples.h#L59)):*
> ```objc
> // s.t cᵀ*(A*x) = d
> // This test L2NormCost with linear constraints.
> // Notice we take an invertible transformation A.
> ```

Done.

I realize A doesn't need to be invertible as I do not take the inverse of A.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271)* status: 2 unresolved discussions

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21271)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),AlexandreAmice

**Pull request merged**
