### PR TITLE
 lcm_subscriber_system: Allow `WaitForMessage` to output the latest message

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Indirectly connected to #8312: I wanted to use `DrakeLcm` to get the message, rather than writing my own for-loops, or incantations of `DrakeLcmMessageHandlerInterface`.

BTW, does anyone know why `DrakeLcmMessageHandlerInterface` is, rather than just using a `std::function<>`?

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8313)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@siyuanfeng-tri for feature review, please.
+@sherm1 for platform review, please.

Tested `lcm_subscriber_system_test` under TSan, and did not get any errors. I'm scratching my head just a bit about race conditions -- I'm not sure if I can make a guarantee that the loop for `WaitForMessage` is running before the mock publish happens.
That being said, TSan did catch some of my other shenanigans, so I have a decent amount of confidence in it passing this off (on Linux, at least).

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-:-L787In0MWUAU4Gff8dY:buciejr)*

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
Hm... Thinking about it a bit more, I believe I can avoid the race condition (publishing before `WaitForMessage(-1, ...)` is called if I remove the `-1` option, and instead use something like `GetInternalMessageCount()`.

May try that out.

**Comment by jwnimmer-tri** [comment]
> BTW, does anyone know why DrakeLcmMessageHandlerInterface is, rather than just using a std::function<>?

Interesting to have this PR touching `//lcm` when its been silent for so long.  I'm tackling #8256 to improve the decoding interface but first got stalled on the pile of defects in #7178 that haven't been fixed yet; I'm working on those as well as #8256.  WIP at https://github.com/jwnimmer-tri/drake/tree/lcm-logger-followup though its very rough.  Depending on how that comes out, its possible I replace the callback interface with a `std::function`.

**Comment by EricCousineau-TRI** [comment]
Mac CI failures seem to be related to linting shenanigans with `cpplint`. Will assume that this PR sits well with Mac.

**Comment by siyuanfeng-tri** [comment]
talked with eric f2f, suggesting using dumb busy waiting loop in the test with atomic bools to reduce the cognitive load on readers.. i do like the #include <future> part.. 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lcm/drake_lcm_log.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ACJDGuRMP9t3zviYZ:-L7ACJDGuRMP9t3zviY_:b-pcrvyq) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/lcm/drake_lcm_log.h#L139)):*
> ```objc
>   std::unique_ptr<::lcm::LogFile> log_;
>   const ::lcm::LogEvent* next_event_{nullptr};
>   bool receive_thread_started_{false};
> ```

does this need to be atomic? 

---

*[systems/lcm/lcm_subscriber_system.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ADoVNJmhL37WwHh2J:-L7ADoVOR6-BSdjv3z15:b-7ddz1i) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/systems/lcm/lcm_subscriber_system.cc#L317)):*
> ```cpp
>   // This while loop is necessary to guard for spurious wakeup:
>   // https://en.wikipedia.org/wiki/Spurious_wakeup
>   while (old_message_count == received_message_count_)
> ```

BTW i want throw an pair of {} here for readability. 

---

*[systems/lcm/lcm_subscriber_system.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7AEDNzUtJTRNw6rTBY:-L7AEDNzUtJTRNw6rTBZ:bgcigsr) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/systems/lcm/lcm_subscriber_system.h#L147)):*
> ```objc
> 
>   /**
>    * Blocks the caller it has received a different number of messages
> ```

BTW different from old_msg_count or the current internally msg count when old_msg_ctr = -1. 

---

*[systems/lcm/test/lcm_subscriber_system_test.cc, line 4 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7AGYD-mC8bEwas_Rjq:-L7AGYD-mC8bEwas_Rjr:b-3ccllj) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/systems/lcm/test/lcm_subscriber_system_test.cc#L4)):*
> ```cpp
> 
> #include <array>
> #include <future>
> ```

BTW wow for the header name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-:-L7AJ3EfjsKfciPbMDwj:b-ma2h2f)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[lcm/drake_lcm_log.h, line 139 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ACJDGuRMP9t3zviYZ:-L7AL72WlcwJoRsdLjgc:b-eqjn1d) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/lcm/drake_lcm_log.h#L139)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

does this need to be atomic? 
</blockquote></details>

Done. I don't think so, but made it so anywho.

---

*[systems/lcm/lcm_subscriber_system.cc, line 317 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ADoVNJmhL37WwHh2J:-L7AOkcSu32Y271WsOzQ:b-4l67a1) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/systems/lcm/lcm_subscriber_system.cc#L317)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW i want throw an pair of {} here for readability. 
</blockquote></details>

Done. Also, made this an inequality.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/lcm/lcm_subscriber_system.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7AEDNzUtJTRNw6rTBY:-L7AQ48R9YEPc2TBz0J2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b069aeef8a376103bb72531534ca2c9d2e98a33a/systems/lcm/lcm_subscriber_system.h#L147)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW different from old_msg_count or the current internally msg count when old_msg_ctr = -1. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/lcm/test/lcm_subscriber_system_test.cc, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ASNTrsFIL8UMvoPx3:-L7ASNTrsFIL8UMvoPx4:b-ce50q9) ([raw file](https://github.com/robotlocomotion/drake/blob/846422e4f1290f26d07948505f15f0ed7248ef1a/systems/lcm/test/lcm_subscriber_system_test.cc#L193)):*
> ```cpp
>   auto future_count = std::async(std::launch::async, [&]() {
>     started = true;
>     EXPECT_EQ(dut->GetInternalMessageCount(), 0);
> ```

should this be before started = true? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-:-L7AU-uI6qBYCESewdmn:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[systems/lcm/test/lcm_subscriber_system_test.cc, line 193 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7ASNTrsFIL8UMvoPx3:-L7AY5ZA_lXYNU5_i7Vv:b-r08yfo) ([raw file](https://github.com/robotlocomotion/drake/blob/846422e4f1290f26d07948505f15f0ed7248ef1a/systems/lcm/test/lcm_subscriber_system_test.cc#L193)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

should this be before started = true? 
</blockquote></details>

Done. D'oh!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313)*

**Comment by sherm1** [comment]
Platform :lgtm:, one tiny BTW.

---

Reviewed 2 of 11 files at r1, 8 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/lcm/lcm_subscriber_system.h, line 158 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-L7BwlcZoczqMDT4H33Y:-L7BwlcZoczqMDT4H33Z:b-1a2cbo) ([raw file](https://github.com/robotlocomotion/drake/blob/4123650bcd6aab5a788557cea825656b91da3130/systems/lcm/lcm_subscriber_system.h#L158)):*
> ```objc
>   /**
>    * Returns the internal message counter. Meant to be used with
>    `WaitForMessage`.
> ```

BTW missing `*`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8313#-:-L7BzeX9zHZVE6Ew9Cz8:b-75c26x)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/lcm/lcm_subscriber_system.h, line 158 at r3](https://beta.reviewable.io/reviews/robotlocomotion/drake/8313#-L7BwlcZoczqMDT4H33Y:-L7QXGFq1V1KiM7tmFv1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4123650bcd6aab5a788557cea825656b91da3130/systems/lcm/lcm_subscriber_system.h#L158)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW missing `*`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8313)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8313)*

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I don't quite understand why the first commit is here -- the `DrakeLcmInterface::IsReceiveThreadRunning` query.  It doesn't seem to have been used by any revision of this PR, and isn't used anywhere but its own unit tests in master of Drake or Anzu.  I am going to be improving our LCM abstractions soon, including process / thread models, and preserving this method in its more general form isn't necessarily easy or desirable.  Would it be a problem if this method were no longer part of DrakeLcmInterface the base class?  My current impressions is that only the _real_ LCM stack `drake::lcm::DrakeLcm` should offer thread-control methods.

**Comment by EricCousineau-TRI** [comment]
I wanted this method to exist since the base interface needs the implementation of `StartReceiveThread()` and `StopReceiveThread()`, but there was no way to query if you're *actually* running the receive thread.

I wrote a utility, and I had wanted to assert that the LCM thread be running, and not leave it entirely up to user choice / user error with no means of programmatically checking, as that is the current state.
I believe @siyuanfeng-tri had also mentioned that he's run into situations where he's debugging why he wasn't receiving anything, and it was because he had forgot to call `StartReceiveThread`.

If there were another query or guarantee that LCM is actually doing some useful (e.g. starting the thread upon construction), then I'd be fine with ditching this method.

**Comment by jwnimmer-tri** [comment]
Ok great.  I plan to keep the method as long as we have Start / Stop, but I plan to move all of them to DrakeLcm concrete class, and not be part of the pure interface.  They really only apply to the concrete class; using LCM from mocking or logs doesn't use the concept of a "receive thread".

**Pull request merged**
