### PR TITLE
styleguide: Bump to latest commit

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Towards https://github.com/RobotLocomotion/styleguide/pull/28

From  logs:
> [2020-03-02T21:17:17.152Z] //tools/workspace/styleguide:cpplint_unittest                            PASSED in 1.2s

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12776)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Note that the sha is already upgraded on master.

**Comment by m-chaturvedi** [comment]
Yeah, I had seen #12800 while resolving conflicts.  This is for getting the cpplint tests to build with python3 and running them while testing drake.

> Towards https://github.com/RobotLocomotion/styleguide/pull/28

**Comment by jwnimmer-tri** [comment]
That's fine.  But the git sha in this PR is wrong, even after the rebase.

**Comment by jwnimmer-tri** [comment]
Oh -- I guess not "wrong", but pointing to a PR branch.  So needs "do not merge" label here at a minimum.  Probably "do not review" still as well.

**Comment by m-chaturvedi** [comment]
Yeah, that's because I'd forced pushed a change on the styleguide PR after CI started running the tests.  Sorry about that.

**Comment by m-chaturvedi** [comment]
@jwnimmer-tri for feature review, please.

**Comment by m-chaturvedi** [comment]
+@soonho-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for platform review per schedule, please.

I tested this locally on macsim already.

**Comment by jamiesnape** [comment]
This broke coverage builds, it appears.

**Comment by jwnimmer-tri** [comment]
Ah, because coverage turns off the sandbox.  Probably fine to tag this test to be skipped in coverage builds (`no_kcov`).

**Pull request merged**
