### PR TITLE
Fix bug in zmpUtil

### PR DESCRIPTION
**Pull request by tkoolen**
Part of addressing https://github.com/RobotLocomotion/drake/issues/2165.

In Debug mode, running `runAtlasWalking.m` resulted in a Matlab crash with
```
[...]
[ 11] 0x00000001b988c557 /Users/twan/Library/Caches/CLion2016.2/cmake/generated/drake-8d5e0e9a/8d5e0e9a/Debug/systems/controllers/libdrakeZMPUtil.dylib+00267607 _ZN5Eigen9DenseBaseINS_5BlockINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi1ELin1ELb0EEEE6resizeEll+00000167
[...]
```

in the matlab dump and
```
Assertion failed: (rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow to resize."), function resize, file /Users/twan/code/drake-distro/build/install/include/eigen3/Eigen/src/Core/DenseBase.h, line 257.
```
on the command line.

This was due to a bug in `zmpUtil.cpp` (that may have crept in after the Release configuration bug that #2165 started with). We check that the degree of all of the segments of the `PiecewisePolynomial` `zmp_trajectory` is `d` (so all its segments have `k = d + 1` coefficients), which is good. Then we compute
```C++
PiecewisePolynomial<double> zbar_pp = zmp_trajectory - zmp_tf;
```
where `zmp_tf` is a constant matrix. One would think that the degrees of the segments of `zbar_pp` would be the same as those of `zmp_trajectory`, but the `operator-=` for `Polynomial` calls `MakeMonomialsUnique`, which erases monomials with coefficients equal to zero, so it actually *can* change the degree of the polynomial as returned by the `GetDegree` method, as well as the size of the vector of coefficients. Later on we were doing the following:
```C++
MatrixXd poly_coeffs = MatrixXd::Zero(nq, k);
...
auto poly_mat = zbar_pp.getPolynomialMatrix(j);
...
poly_coeffs.row(x) = poly_mat(x).GetCoefficients().transpose();
```

But the left hand side was a bigger row vector than the right hand side in that assignment due to the erased monomials.

cc: @manuelli, @siyuanfeng-tri.

After this pull request `runAtlasWalking` works again **in Debug mode, but not in Release mode**. I'll PR the fix for Release mode separately.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3457)

### CODE REVIEW

**Comment by tkoolen** [comment]
Reviewer suggestion: perhaps @rdeits?

**Comment by rdeits** [comment]
:lgtm:

good catch!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3457#-:-KRj2CNgzRkTAxeYSJHr:b1w4heg)*

**Comment by rdeits** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3457)*

**Comment by tkoolen** [comment]
@psiorx, would you be available for platform review?

**Comment by RussTedrake** [comment]
:lgtm: (for the platform review)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3457#-:-KRjANOrE58Hlqu8o6AO:bx04o77)*

**Comment by tkoolen** [comment]
Thanks!

**Pull request merged**
