### PR TITLE
MBT pendulum test cleanup.

### PR DESCRIPTION
**Pull request by amcastro-tri**
The previous double pendulum test in double_pendulum_test.cc is using some MBT internals and testers to verify inner workings of MBT (mobilizers, joints impls, etc). That tests grew kind of big now and it obscures the actual API we want to offer.
This PR renames the previous tests (which still serves a purpose) and creates a new clean pendulum test (double_pendulum.cc) that will be best suited as a reference on what MBT code should look like (it uses joints for instance instead of mobilizers).
Tests on how to apply external forcing on joints will be pushed in a next PR based off this cleaner test using joint's API.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7719)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for feature review please

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2Rhoudbk7J6r5r_0__:b-kr3pa2)*

**Comment by amcastro-tri** [comment]
+@seancurtis-tri, notice the new test file is named `double_pendulum.cc` instead of `double_pendulum_test.cc`. The reason for this is to aid the review. Reviewable gets confused with the old version of this file and shows huge diffs while in reality this is a completely new file (yes, based off the old one, but new in that it simplifies the pendulum model quite a bit using Joint objects). 
Therefore I will keep that name until the review is done and I will rename at the end. 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2RsBiqC1KP67Z-e9NH:-L2RsBiqC1KP67Z-e9NI:b6ub0xb) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L2)):*
> ```cpp
> // clang-format: off
> #include "drake/multibody/multibody_tree/multibody_tree.h"
> ```

Rename this file to `double_pendulum_test.cc` before merging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2Rrgll3ytNhRGQFMXQ:b-1rax2m)*

**Comment by SeanCurtis-TRI** [comment]
Starting review -- but I figured I'd broach a topic of discussion that you can consider while I look at details.

As you indicate the renamed test serves "a purpose"?  What would you say that purpose is? And would the name of the test be better if that purpose were reflected in the name? It seems to be exercising low-level MBT elements and it *happens* to be using a double pendulum to do so. But there's nothing about its purpose that requires a double pendulum, right? I'd rather keep the fact that it's a double pendulum as an internal implementation detail and have the file name reflect what is under test.

Similarly, the new `double_pendulum.cc` is a test of the MBT high-level abstraction. I"d apply the same logic there. Your thoughts?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2VlPCmDLLLzmaLolTn:bkunux9)*

**Comment by amcastro-tri** [comment]
The original `double_pendulum` tests a number of different things. It tests the ability to add internal low level elements through MBT's API as well as it tests a number of computational methods on MBT. Some cleanup might be in order I'm just not sure if that'd entail a rename and/or a splitting of the file. I decided now, that I don't have the time to thing about this, to just go with a simple rename. Better names are welcome if you can think of any.

The new double pendulum file attempts to only expose the high level API so that it could potentially serve as an example of what that API looks like. Probably a better name would be more appropriate, I just couldn't think of any. That cleaner test was motivated by the soon to arrive API to apply forces to an MBT model, the actual important bit of code.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2W1zC10iO_suTfi3NW:b-64w0td)*

**Comment by SeanCurtis-TRI** [comment]
Given that the file names don't introduce *new* sins, I'm willing to let it go. But I *do* consider a test file whose name doesn't hint at *what* is being tested is a bit of a sin. :)

Otherwise, mostly :LGTM: with a few cosmetic issues.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2Vx8gKkkGtTJB0Bofq:-L2Vx8gKkkGtTJB0Bofr:bb3gfkh) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L18)):*
> ```cpp
> #include "drake/multibody/multibody_tree/fixed_offset_frame.h"
> #include "drake/multibody/multibody_tree/joints/revolute_joint.h"
> #include "drake/multibody/multibody_tree/revolute_mobilizer.h"
> ```

BTW I'm pretty sure this isn't used. (I further suspect that there are a couple of other headers that aren't used as well.)

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W6gqSOew7dtiTA2q-:-L2W6gqSOew7dtiTA2q0:b-ipish2) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L29)):*
> ```cpp
> const double kEpsilon = std::numeric_limits<double>::epsilon();
> 
> using benchmarks::Acrobot;
> ```

A number of the following aliases are unused in this file.:
- `AngleAxisd`
- `Matrix3d`
- `Matrix4d`
- `Vector2d`
- `VectorXd`
- `std::vector`

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W-Q8puKgRc3ecERuP:-L2W-Q8puKgRc3ecERuQ:b-8stvty) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L63)):*
> ```cpp
> //  - The body frame for link 1 is placed at its geometric center.
> //  - The body frame for link 2 is placed at the joint's outboard frame.
> //  - The origin of the shoulder frames (Si and So) are coincident at all times.
> ```

BTW This doesn't quite scan right.

1. Subject is singular ("the origin"), verb is plural ("are"). Follow up phrase has singular verb ("is"). (Same for elbow description.)

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W0JPj8SEgO_KQVZS_:-L2W0JPj8SEgO_KQVZSa:b-tuhyof) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L94)):*
> ```cpp
> //      +--+-----+
> //      |  ^     |
> //      |  |Eo/L2| Elbow outboard frame Eo.
> ```

Before you used the notation `Si ≡ W` to emphasize that the `Si` and `W` are *coincident*. Following that vein, instead of `Eo/L2`, perhaps `Eo ≡ L2` or `Eo ≜ L2` here as well?  The `/` notation isn't overly suggestive to me.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 153 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W1F3J-WvsDloGcIfM:-L2W1F3J-WvsDloGcIfN:b-zangs8) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L153)):*
> ```cpp
>     shoulder_ = &tree_->template AddJoint<RevoluteJoint>(
>         "ShoulderJoint",
>         *world_body_, {},  /* No input, frame Si IS the world frame W. */
> ```

BTW Two thoughts:

1. A comment applying to a line with *two* expressions seems to invite ambiguity. Perhaps put {} on its own line?
2. "No input" is overly vague. How about: `/* Default to Identity; frame Si IS the world frame W. */  

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 157 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W1b_Fce-Vz7tYumf6:-L2W1b_Fce-Vz7tYumf7:b8ecgh6) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L157)):*
> ```cpp
>         Vector3d::UnitZ()  /* revolute axis */);
> 
>     // The elbow is the mobilizer that connects links 1 and 2.
> ```

BTW "mobilizer" probably shouldn't be the language here.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 164 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W4l_Dvo97orpYCkPY:-L2W4l_Dvo97orpYCkPZ:b-kny4wr) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L164)):*
> ```cpp
>     // The elbow's outboard frame Eo is taken to be coincident with link 2's
>     // frame L2 (i.e. L2o != L2cm).
>     // X_L1Ei defines the pose of the elbow inboard frame Ei link 1's frame L1:
> ```

BTW Final period instead of colon.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 246 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W5Fm9NpDDfgCjgr1G:-L2W5Fm9NpDDfgCjgr1H:b-d5tete) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L246)):*
> ```cpp
> 
>     // Benchmark mass matrix:
>     Matrix2d H_expected = acrobot_benchmark_.CalcMassMatrix(theta2);
> ```

BTW It's somewhat surprising that *this* tree depends on theta1 and theta2 but the reference tree only depends on theta2. Perhaps some documentation? (I note that you document it below in `CalcMassMatrixViaInverseDynamics`. Maybe steal from there and put it in the description of the `DoublePendulumModel` documentation and then the two instances can simply reference it?

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W65UHY4xAlm874rQf:-L2W65UHY4xAlm874rQg:b-ggkeul) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L277)):*
> ```cpp
>   VerifyCalcMassMatrixViaInverseDynamics(0.0, M_PI / 4.0);
> 
>   // For the double pendulum system it turns out that the mass matrix is only a
> ```

There seems to be a weirdness in this test. Essentially, the documentation says that `f(a, b) = f(a', b)` for any `a != a'`. However, the *appearance* of the code doesn't seem to test the assertion. Ultimately, it *does* test it, but only indirectly if you dig into the details of `VerifyCalcMassMatrix....()`. Can this be made more clear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2W7QrjG_dAsGpZLVWc:bm2f6s7)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 29 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W6gqSOew7dtiTA2q-:-L2WoMXjH1nrhzBRCqc0:b-iry7x8) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L29)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

A number of the following aliases are unused in this file.:
- `AngleAxisd`
- `Matrix3d`
- `Matrix4d`
- `Vector2d`
- `VectorXd`
- `std::vector`
</blockquote></details>

Done, thanks

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 94 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W0JPj8SEgO_KQVZS_:-L2WpQesZht195OejKKD:b-rlogx2) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L94)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Before you used the notation `Si ≡ W` to emphasize that the `Si` and `W` are *coincident*. Following that vein, instead of `Eo/L2`, perhaps `Eo ≡ L2` or `Eo ≜ L2` here as well?  The `/` notation isn't overly suggestive to me.
</blockquote></details>

I like that.

---

*[multibody/multibody_tree/test/double_pendulum.cc, line 277 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2W65UHY4xAlm874rQf:-L2WsPqBW-8Fj-_SnazN:b-bizqh8) ([raw file](https://github.com/robotlocomotion/drake/blob/fcea5ff5c5e3a4821a09bf5ffc717e0b3fdc93b2/multibody/multibody_tree/test/double_pendulum.cc#L277)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

There seems to be a weirdness in this test. Essentially, the documentation says that `f(a, b) = f(a', b)` for any `a != a'`. However, the *appearance* of the code doesn't seem to test the assertion. Ultimately, it *does* test it, but only indirectly if you dig into the details of `VerifyCalcMassMatrix....()`. Can this be made more clear?
</blockquote></details>

Added comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by amcastro-tri** [comment]
Thank you @seancurtis-tri. Note for the platform reviewer. Per Slack discussion with @seancurtis-tri, renamed the files in this PR as:
 - `double_pendulum_test.cc` --> `tree_from_mobilizers_test.h` and,
 -  `double_pendulum.cc` --> `tree_from_joints_test.h`.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2WseNFs8J8EIqDTjNX:b-3onvt)*

**Comment by amcastro-tri** [comment]
+@soonho-tri for platform review please.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2WxGe5pT7rcZ4IPRGE:b-vt9vbo)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2X1e7_BiLPEBYlXw_T:-L2X1e7_BiLPEBYlXw_U:bkypn0q) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L53)):*
> ```cpp
> //  - The body frame for link 2 is placed at the joint's outboard frame.
> //  - The origins of the shoulder frames (Si and So) are coincident at all
> //    times. So is aligned with Si for θ₁ = 0.
> ```

FYI I realized that I misread the last sentence over and over. It's supposed to be:

`So` is aligned with `Si` for...

But I read `So` as the conjunction "So", leading to a difficult-to-parse sentence. When you end up with symbols that look just like English words, it might be worth developing the habit of ticking them or some such thing. (Particularly since the capitalization of the sentence overlaps with the symbol.)

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 232 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2X2XWZWl9e8s0Tspan:-L2X2XWZWl9e8s0Tspao:bno0kta) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L232)):*
> ```cpp
>   // function of the elbow angle, theta2, independent of the shoulder angle,
>   // theta1. This fact can be verified by calling this method with
>   // different values of theta1, given that our benchmark does have this
> ```

FYI I suggest s/different/arbitrary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by soonho-tri** [comment]
:lgtm: I've added some minor comments. PTAL.

---

Reviewed 1 of 6 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2_jYKknKawSPvviK8j:-L2_jYKknKawSPvviK8k:bbq0giz) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L34)):*
> ```cpp
> 
> // Set of MultibodyTree tests for a double pendulum model. This simple set of
> // tests serve as an example on how to build a model using RigidBody and Joint
> ```

BTW, nit, `serve` -> `serves`.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 197 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2_jH6KLwq4ZZADo0Jq:-L2_jH6KLwq4ZZADo0Jr:b-om5ngi) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L197)):*
> ```cpp
>  private:
>   std::unique_ptr<MultibodyTree<T>> tree_;
>   const Body<T>* world_body_;
> ```

FYI, those non-const pointers to const objects need to be initialized here (with `{nullptr}`) per our style-guide.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 276 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2_iVm60EqT6hUktxqg:-L2_iVm60EqT6hUktxqh:bsjjnrt) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L276)):*
> ```cpp
>   VerifyCalcMassMatrixViaInverseDynamics(0.0, M_PI / 4.0);
> 
>   // We run run the same previous tests with different shoulder angles to verify
> ```

BTW, nit, `run run` -> `run`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-:-L2_jqxhUyJtJi4sy5-t:ba9lzie)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2X1e7_BiLPEBYlXw_T:-L2a5a-K4hXA3wWkWMf5:boaotcz) ([raw file](https://github.com/robotlocomotion/drake/blob/a341ba5a1d65444b552746ccc6c2dd9e0f15fd9c/multibody/multibody_tree/test/tree_from_joints_test.cc#L53)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI I realized that I misread the last sentence over and over. It's supposed to be:

`So` is aligned with `Si` for...

But I read `So` as the conjunction "So", leading to a difficult-to-parse sentence. When you end up with symbols that look just like English words, it might be worth developing the habit of ticking them or some such thing. (Particularly since the capitalization of the sentence overlaps with the symbol.)
</blockquote></details>

I see the confusion. I didn't use back ticks originally because this is not Doxygen.  I added them now since hopefully they'll help avoid this kind of confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/test/tree_from_joints_test.cc, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7719#-L2aItccSmKcJGxz1Lgd:-L2aItcdIBG4kOMozzJR:b-6up45u) ([raw file](https://github.com/robotlocomotion/drake/blob/1a689f46ac20b588b1a13cce9524e38046f2d985/multibody/multibody_tree/test/tree_from_joints_test.cc#L53)):*
> ```cpp
> //  - The body frame for link 2 is placed at the joint's outboard frame.
> //  - The origins of the shoulder frames (`Si` and `So`) are coincident at all
> //    times. `So` is aligned with `Si` `for θ₁ = 0`.
> ```

BTW the back tick extended to include "for". I'm assuming that was not intended.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 5 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7719)*

**Pull request merged**
