### PR TITLE
Upgrade Externals April 2023

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #19137.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19185)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please

**Comment by sherm1** [comment]
Is this ready for feature review?

**Comment by mwoehlke-kitware** [comment]
@sherm1, as mentioned on slack, yes, this is waiting for a reviewer. Are you volunteering? 🙂

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19185#-:-NSvmfM9EATo424DB26f:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Pull request merged**
