### PR TITLE
[pydrake] Bind LcmImageArrayToImages

### PR DESCRIPTION
**Pull request by svenevs**
Bindings seem close, something special needs to happen with `lcmt_image_array`.  CC @jwnimmer-tri 

In trying to validate the `.whl` installation's jpeg backend we attempted to run a port of the following test:

https://github.com/RobotLocomotion/drake/blob/4a181559d67dd8f777c7a3a01496876d0aa47e17/systems/sensors/test/lcm_image_array_to_images_test.cc#L57

To build the wheel, the user needs:

1. To own `/opt` (or be able to `mkdir` beneath it without permissions).  Some directories are created there during the build.
2. Git access to the drake snopt repo with an ssh key loaded.

```console
# After the first time, you can add --incremental to not rebuild drake
$ SNOPT_PATH=git bazel run //tools/wheel:builder -- -o $PWD 3.4.5 -k

# produces: drake-3.4.5-cp310-cp310-macosx_12_0_arm64.whl

$ python -m venv venv
$ source venv/bin/activate
$ pip install drake-3.4.5-cp310-cp310-macosx_12_0_arm64.whl
$ python drake_image.py  # code below
```

Python code:

```py
#!/usr/bin/env python3

from drake import lcmt_image, lcmt_image_array
from pydrake.systems.sensors import ImageRgba8U, ImageDepth32F, LcmImageArrayToImages


if __name__ == "__main__":
    # Start with an empty color image and expect that it will be populated.
    color_image = ImageRgba8U(0, 0)

    # Start with a populated depth image, expect it will be cleared.
    depth_image = ImageDepth32F(32, 32)

    jpeg_image = lcmt_image()
    jpeg_image.width = 32
    jpeg_image.height = 32
    jpeg_image.row_stride = jpeg_image.width * 3
    jpeg_image.bigendian = 0
    jpeg_image.pixel_format = lcmt_image.PIXEL_FORMAT_RGB
    jpeg_image.channel_type = lcmt_image.CHANNEL_TYPE_UINT8
    jpeg_image.compression_method = lcmt_image.COMPRESSION_METHOD_JPEG

    # Load image data to jpeg_image manually
    from pathlib import Path
    this_file_dir = Path(__file__).parent.absolute()
    # update this var according to local filesystem
    drake_repo_root = this_file_dir / "Desktop" / "drake"
    jpeg_path = drake_repo_root / "systems" / "sensors" / "test" / "jpeg_test.jpg"
    assert jpeg_path.is_file()

    with open(jpeg_path, "rb") as f:
        jpeg_image.data = f.read()
    jpeg_image.size = len(jpeg_image.data)


    lcm_images = lcmt_image_array()
    lcm_images.num_images = 1
    lcm_images.images.append(jpeg_image)

    dut = LcmImageArrayToImages()
    # Decode image array
    context = dut.CreateDefaultContext()
    dut.image_array_t_input_port().FixValue(context, lcm_images)

    color_image = dut.color_image_output_port().Eval(context)
    depth_image = dut.depth_image_output_port().Eval(context)

    assert color_image.size() == 32 * 32 * 4
    assert depth_image.size() == 0
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
PTAL.

In short, for both `LcmImageArrayToImages` and `ImageToLcmImageArray`, you need to connect a C++-based LCM publisher or subscriber, fed into a `lcm = DrakeLcm("memq://")`.   Then in Python, you can fetch the message bytes from `lcm` and decode it using the Python flavor of the message.

Now that I write that out, I realize we could probably also do:

```py
serializer = pydrake.systems.lcm._Serializer_[drake.lcmt_image_array]()
raw = serializer.Serialize(output_port_value)
return drake.lcmt_image_array.decode(raw)
```

... without the publisher / subscriber systems.

**Comment by jwnimmer-tri** [comment]
My plan is to land #18245 first (to improve the existing test) and then circle back here.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

**Comment by jwnimmer-tri** [comment]
+@svenevs for feature review, please.

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-focal-unprovisioned-gcc-wheel-experimental-snopt-mosek-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237)* status: LGTM missing from assignees jwnimmer-tri(platform),svenevs, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
:lgtm: +@xuchenhan-tri for platform review per schedule please.

I confirmed the mac build locally, CI confirmed linux builds, focal 38 wheel worked as expected:

```console
$ python -m venv venv
$ source venv/bin/activate
$ pip install -U pip  # required on focal
$ pip install https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2022.11.2.18.24.45%2Bgita044ce1e-cp38-cp38-manylinux_2_31_x86_64.whl
$ python 
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydrake.all
>>> from pydrake.systems.sensors import LcmImageArrayToImages
>>>
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237#-:-NFtnUsEELtsrYjByFNZ:b6zrred)* status: LGTM missing from assignees jwnimmer-tri(platform),xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri, @svenevs, and @xuchenhan-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: co-feature / co-author.

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237#-:-NFtperfDYHmHzeh0Zt-:b-dmm9o1)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs and @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 
Please curate the commit message before merging, thanks.

> Reviewed 3 of 5 files at r2, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18237#-:-NFu57rq4Vf2kwjRi5zK:bq5pnpc)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Pull request merged**
