### PR TITLE
Relocate system identification tools-in-progress to solvers directory…

### PR DESCRIPTION
**Pull request by ggould-tri**
… and rename the files to conventional under_scores style rather than FunkyCaps.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2198)

### CODE REVIEW

**Comment by ggould-tri** [comment]
The windows build failure is real, and means that I have to actually solve the nested class inside template export problem.  I will be doing a series of blind commits for this, and so am adding the 'do not merge' flag while I use CI as a windows build oracle.

**Comment by liangfok** [comment]
@ggould-tri, I can help you setup a working Drake development environment on Windows if that would be useful.

**Comment by ggould-tri** [comment]
This time my shot in the dark hit the target.  Yay?

**Comment by liangfok** [comment]
It's what years of experience enables you to do I guess...

**Comment by Lucy-tri** [comment]
I had one question applying to 2 places, commented below, the rest looks fine. 

---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/Polynomial.h, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGOThNjvhlyKh-Ajgc2:-KGOThNjvhlyKh-Ajgc3:-1872716326) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/util/Polynomial.h#L58)):*
Is POLYNOMIAL supposed to be OPTIMIZATION?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-:-KGOYJsVXZtoXRUEzDDZ:2111387976)*

**Comment by ggould-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/util/Polynomial.h, line 58 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGOThNjvhlyKh-Ajgc2:-KGRsxq9IIRWn5PGtyz9:-617065030) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/util/Polynomial.h#L58)):*
No.  Polynomial is still a util, and expected to be used in other util-level code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2198)*

**Comment by jwnimmer-tri** [comment]
:lgtm: With two optional suggestions.

---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 11 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGSC57kOYvBeGXJG_IB:-KGSC57lhIXwSsJ-ViX6:1604323842) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/solvers/test/CMakeLists.txt#L11)):*
Per styleguide, this needs to be system_identification_test and system_identification_test.cc.  If this is an incremental PR and that's in the pipeline later, fine.  But renaming and moving seems like a good time to do it correctly?

---

*[drake/solvers/test/test_system_identification.cpp, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGSE-jJTQxssKEeJnwE:-KGSE-jKYO5GigXdE2is:2051785287) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/solvers/test/test_system_identification.cpp#L3)):*
Probably this order of includes does not meet the styleguide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-:-KGSEJ3lfzkRPazFWmf9:-890605184)*

**Comment by ggould-tri** [comment]
Fixed

---

Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/CMakeLists.txt, line 11 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGSC57kOYvBeGXJG_IB:-KGSILai5D3eNV6zGXYN:-1620474753) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/solvers/test/CMakeLists.txt#L11)):*
fixed.

---

*[drake/solvers/test/system_identification_test.cpp, line 3 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-KGSE-jJTQxssKEeJnwE:-KGSIMxFFBk3uClcYyrs:-467915377) ([raw file](https://github.com/robotlocomotion/drake/blob/2fe347e82fd5c0cd4e14624dbf08aee321b44daa/drake/solvers/test/system_identification_test.cpp#L3)):*
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-:-KGSIHq0mHBfPZwv02IN:-497468049)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2198#-:-KGSJ83nfAMMtfsiqmsg:1417088721)*

**Comment by ggould-tri** [comment]
The mac failure there appears spurious; I am retaining the ready-to-accept tag.

**Comment by jwnimmer-tri** [comment]
Yes.  The mac failure was a flake.  The 2fe347e a few versions back passed on mac, and the changes since then should not be platform-dependent.  Doing override-merge now.

**Pull request merged**
