### PR TITLE
[cmake] Fix several errors and imprecisions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #19023.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19110)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@mwoehlke-kitware do you have bandwidth for feature review here?

**Review by mwoehlke-kitware — COMMENTED** [review]
:lgtm: 

(As an aside, this seems like a good argument for not prematurely converting lists to strings...)

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19110#-:-NS7CWAL7RZFSGyd9cUn:b-28rryd)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19110#-:-NS7H7XiAB3ltGiwRZbW:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees mwoehlke-kitware,xuchenhan-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
