### PR TITLE
Add drake/tools/formatter.py

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is the core technology of the pending `clang-format-includes` tool at https://github.com/jwnimmer-tri/drake/tree/clang-format-includes.

Relates #2269.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5598)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-:-KfutW_sIYwjTKIppNDs:blnrywe)*

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/tools/formatter.py, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvQL62afDOPeS9WKb4:-KfvQL63S5tWYHInBM2x:buzc583) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L5)):*
> ```Python
> 
> import os
> import sys
> ```

unused.

---

*[drake/tools/formatter.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvQR33FayBUB8d_QPK:-KfvQR33FayBUB8d_QPL:b-5rg6ew) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L6)):*
> ```Python
> import os
> import sys
> from subprocess import Popen, PIPE, STDOUT, CalledProcessError
> ```

STDOUT unused.

---

*[drake/tools/formatter.py, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXiQ0ly0_TOu6SNFR:-KfvXiQ1nLRkKIOb8TRh:b-agtnr5) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L10)):*
> ```Python
> 
> class FormatterBase(object):
>     """A base class for formatting-related tools, with the ability to load a file,
> ```

line too long.

---

*[drake/tools/formatter.py, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvW3dtGxltU8KPlsHb:-KfvW3dvY3bWfeb-FXBK:b-rc6iae) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L28)):*
> ```Python
> 
>     def __init__(self, filename, readlines=None):
>         """Create a new FormatterBase.  The required filename parameter refers to the
> ```

SUPER META: I feel like the pep8 tool used whine about (even doc-string) encroachments over column 79, but it is not happening for me today. Neither does my emacs word-wrap them properly. Oh well, fix or not as you please.

---

*[drake/tools/formatter.py, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXpEk9JOdfFJWqGQ0:-KfvXpEk9JOdfFJWqGQ1:b-7zgtrl) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L120)):*
> ```Python
> 
>     def get_format_indices(self):
>         """Return the sorted list of all indices that pass the self.should_format
> ```

too long. (hm, maybe it's only the first line of a multi-line doc string that the tools are failing on?)

---

*[drake/tools/test/formatter_test.py, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXLjcRDmXrFc57GAC:-KfvXLjcRDmXrFc57GAD:b-agtnr5) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/test/formatter_test.py#L55)):*
> ```Python
> 
>         self.assertEqual(dut.get_format_ranges(), [[0], [4, 5], [10]])
>         self.assertEqual(dut.get_non_format_ranges(), [[1, 2, 3], [6, 7, 8, 9]])
> ```

line too long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/tools/formatter.py, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvQL62afDOPeS9WKb4:-Kfwqe6IPxTyzvk8OTri:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L5)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

unused.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvQR33FayBUB8d_QPK:-KfwqeRE1DE9KUMvw40Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L6)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

STDOUT unused.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXiQ0ly0_TOu6SNFR:-Kfwql4eDWGvKFCBVlnT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L10)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

line too long.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvW3dtGxltU8KPlsHb:-Kfwqp8MfbXXGyBrUl5K:buxigtx) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L28)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

SUPER META: I feel like the pep8 tool used whine about (even doc-string) encroachments over column 79, but it is not happening for me today. Neither does my emacs word-wrap them properly. Oh well, fix or not as you please.
</blockquote></details>

Done.

Yeah, pep8 isn't catching this.  And yeah, my emacs is wrapping these wrong and I' keep fixing them by hand and keep accidentally breaking them again.

---

*[drake/tools/formatter.py, line 120 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXpEk9JOdfFJWqGQ0:-Kfwr6v472o1u1so9_CA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/formatter.py#L120)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

too long. (hm, maybe it's only the first line of a multi-line doc string that the tools are failing on?)
</blockquote></details>

Done.

---

*[drake/tools/test/formatter_test.py, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-KfvXLjcRDmXrFc57GAC:-Kfwr7jKOvq09kj1t2uX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1b2707b227a3f5d4269f0585e88eb5a97e797742/drake/tools/test/formatter_test.py#L55)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

line too long.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-:-Kfwv-zldjQvNyKcThGr:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

**Comment by rpoyner-tri** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[.clang-format, line 32 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0W1Hl_NbGGCV9cQOC:-Kg0W1Hl_NbGGCV9cQOD:brnma6z) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/.clang-format#L32)):*
> ```YAML
>     Priority: 45
>   # C system headers.
>   - Regex:    '^[<"](aio\.h|arpa/inet\.h|assert\.h|complex\.h|cpio\.h|ctype\.h|curses\.h|dirent\.h|dlfcn\.h|errno\.h|fcntl\.h|fenv\.h|float\.h|fmtmsg\.h|fnmatch\.h|ftw\.h|glob\.h|grp\.h|iconv\.h|inttypes\.h|iso646\.h|langinfo\.h|libgen\.h|limits\.h|locale\.h|math\.h|monetary\.h|mqueue\.h|ndbm\.h|netdb\.h|net/if\.h|netinet/in\.h|netinet/tcp\.h|nl_types\.h|poll\.h|pthread\.h|pwd\.h|regex\.h|sched\.h|search\.h|semaphore\.h|setjmp\.h|signal\.h|spawn\.h|stdalign\.h|stdarg\.h|stdatomic\.h|stdbool\.h|stddef\.h|stdint\.h|stdio\.h|stdlib\.h|stdnoreturn\.h|string\.h|strings\.h|stropts\.h|sys/ipc\.h|syslog\.h|sys/mman\.h|sys/msg\.h|sys/resource\.h|sys/select\.h|sys/sem\.h|sys/shm\.h|sys/socket\.h|sys/stat\.h|sys/statvfs\.h|sys/time\.h|sys/times\.h|sys/types\.h|sys/uio\.h|sys/un\.h|sys/utsname\.h|sys/wait\.h|tar\.h|term\.h|termios\.h|tgmath\.h|threads\.h|time\.h|trace\.h|uchar\.h|ulimit\.h|uncntrl\.h|unistd\.h|utime\.h|utmpx\.h|wchar\.h|wctype\.h|wordexp\.h)[">]$'
> ```

BTW -- It might have been slightly clearer to factor the `.h` here.

---

*[.clang-format, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0WN2eIB2by8Q2VN9M:-Kg0WN2eIB2by8Q2VN9N:b-k89txu) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/.clang-format#L34)):*
> ```YAML
>   - Regex:    '^[<"](aio\.h|arpa/inet\.h|assert\.h|complex\.h|cpio\.h|ctype\.h|curses\.h|dirent\.h|dlfcn\.h|errno\.h|fcntl\.h|fenv\.h|float\.h|fmtmsg\.h|fnmatch\.h|ftw\.h|glob\.h|grp\.h|iconv\.h|inttypes\.h|iso646\.h|langinfo\.h|libgen\.h|limits\.h|locale\.h|math\.h|monetary\.h|mqueue\.h|ndbm\.h|netdb\.h|net/if\.h|netinet/in\.h|netinet/tcp\.h|nl_types\.h|poll\.h|pthread\.h|pwd\.h|regex\.h|sched\.h|search\.h|semaphore\.h|setjmp\.h|signal\.h|spawn\.h|stdalign\.h|stdarg\.h|stdatomic\.h|stdbool\.h|stddef\.h|stdint\.h|stdio\.h|stdlib\.h|stdnoreturn\.h|string\.h|strings\.h|stropts\.h|sys/ipc\.h|syslog\.h|sys/mman\.h|sys/msg\.h|sys/resource\.h|sys/select\.h|sys/sem\.h|sys/shm\.h|sys/socket\.h|sys/stat\.h|sys/statvfs\.h|sys/time\.h|sys/times\.h|sys/types\.h|sys/uio\.h|sys/un\.h|sys/utsname\.h|sys/wait\.h|tar\.h|term\.h|termios\.h|tgmath\.h|threads\.h|time\.h|trace\.h|uchar\.h|ulimit\.h|uncntrl\.h|unistd\.h|utime\.h|utmpx\.h|wchar\.h|wctype\.h|wordexp\.h)[">]$'
>     Priority: 20
>   # C++ system headers.
> ```

BTW -- This is sensitive to the C++ version, so I would say `C++14` rather than just `C++`.

---

*[drake/tools/formatter.py, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0XUTT4s3O1nosno0k:-Kg0XUTT4s3O1nosno0l:bvrc3iv) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L35)):*
> ```Python
>         reads the contents of the filename from disk into the work list (i.e.,
>         the default value of readlines is open(filename).readlines()).
> ```

Unnecessary whitespace here and in all docstrings below.  PEP-257 requests such a blank line only for class docstrings; you have done the opposite.

---

*[drake/tools/formatter.py, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0Xx2KBKbH65L1GcAu:-Kg0Xx2KBKbH65L1GcAv:b1ojv05) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L62)):*
> ```Python
>     def is_permutation_of_original(self):
>         """Return whether the working list is a permultation of the original
>         file contents read in by (or passed to) the constructor, modulo blank
> ```

FYI "lines" would be clearer than "contents" here.

---

*[drake/tools/formatter.py, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0_i_Z_IqqA9fVG4T3:-Kg0_i__lq3ZPaTOmZCq:b5fxotv) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L227)):*
> ```Python
>     def __init__(self, filename, *args, **kwargs):
>         super(IncludeFormatter, self).__init__(filename, *args, **kwargs)
>         self._related_headers = []
> ```

FYI -- It is extremely unclear to me how this gets populated in the general (non-`inl`) case.

---

*[drake/tools/formatter.py, line 270 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0aesoDm3fjXLfX-42:-Kg0aespQ4cIuMNJg3Gn:b-wtmjnt) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L270)):*
> ```Python
>         # will put back blank lines later, but in the meantime we need all of
>         # the includes bunched together so that clang-format will sort them.
>         # We want to preserve the comment line lalyours near include
> ```

FYI -- "lalyours"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by jwnimmer-tri** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[.clang-format, line 32 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0W1Hl_NbGGCV9cQOC:-Kg0eMu6P33DvsJVAxwS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/.clang-format#L32)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- It might have been slightly clearer to factor the `.h` here.
</blockquote></details>

Done.

---

*[.clang-format, line 34 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0WN2eIB2by8Q2VN9M:-Kg0eU1PY56xpcW4jDn5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/.clang-format#L34)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

BTW -- This is sensitive to the C++ version, so I would say `C++14` rather than just `C++`.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 35 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0XUTT4s3O1nosno0k:-Kg0g6QbnstBYrYAQ56c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L35)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Unnecessary whitespace here and in all docstrings below.  PEP-257 requests such a blank line only for class docstrings; you have done the opposite.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 62 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0Xx2KBKbH65L1GcAu:-Kg0f5YqsUQozRV7jZQW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L62)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI "lines" would be clearer than "contents" here.
</blockquote></details>

Done.

---

*[drake/tools/formatter.py, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0_i_Z_IqqA9fVG4T3:-Kg0f02jofkUr0PTbj1n:bmm2cgc) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L227)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- It is extremely unclear to me how this gets populated in the general (non-`inl`) case.
</blockquote></details>

Done.  See if the new comment helps?

---

*[drake/tools/formatter.py, line 270 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0aesoDm3fjXLfX-42:-Kg0ecXka0tHWOYz5k0M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L270)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- "lalyours"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/tools/formatter.py, line 227 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-Kg0_i_Z_IqqA9fVG4T3:-Kg0hEiLdZHWOH25h_jJ:b-qn5lbb) ([raw file](https://github.com/robotlocomotion/drake/blob/a748d19f5ed58d393fe5aab486c93702e95869ae/drake/tools/formatter.py#L227)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.  See if the new comment helps?
</blockquote></details>

Perfect!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5598#-:-Kg0hSCqB01jg1GzQcxO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Only the matlab build remains.  Using override-merge.

**Pull request merged**
