### PR TITLE
MBP weld joint

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements `WeldJoint` and its internal implementation in `WeldMobilizer`.
Parsing is implemented and unit testing covers kinematics, dynamics and parsing.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@avalenzu for feature review please since you know the drill.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817#-:-LCaGZZe3staxaqyX9bw:bz6rbpb)*

**Comment by amcastro-tri** [comment]
CI didn't finish, but it'd seem like the `linux-xenial-clang-bazel-experimental-cache` and `linux-xenial-gcc-cmake-experimental-matlab` are unrelated.

**Comment by avalenzu** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[multibody/multibody_tree/multibody_tree_topology.h, line 819 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCe9Hyu6dNmdHgMB-PW:-LCe9Hyu6dNmdHgMB-PX:b-l9k64v) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/multibody_tree_topology.h#L819)):*
> ```objc
>       // Start index in a vector containing only generalized velocities.
>       node.mobilizer_velocities_start_in_v = mobilizer.velocities_start_in_v;
>       // Demand indexes to be positive only for mobilizers with a non-zer number
> ```

s/non-zer/non-zero

---

*[multibody/multibody_tree/weld_mobilizer.h, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCe9VXx6Ky1LYg7giX0:-LCe9VXx6Ky1LYg7giX1:bap7lt1) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/weld_mobilizer.h#L19)):*
> ```objc
> 
> /// This mobilizer fixes the relative pose `X_FM` of an outboard frame M in an
> /// inboard frames F as if "welding" them together at this fixed relative pose.
> ```

s/frames/frame

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 218 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeY0khB6UBbeiydE5m:-LCeY0khB6UBbeiydE5n:b-jq5m35) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L218)):*
> ```cpp
>   if (X_PJ.value().isApprox(Isometry3d::Identity())) X_PJ = nullopt;
> 
>   // Only supporting revolute joints for now.
> ```

BTW, this comment is no longer true. Yay!

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 225 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeY7db4RJ4zX6VvZCV:-LCeY7db4RJ4zX6VvZCW:b-mbkqsi) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L225)):*
> ```cpp
>           parent_body, X_PJ,
>           child_body, X_CJ,
>           // The pose X_JpJc of Jc in Jp.
> ```

BTW, the "of Jc in Jp" is redundant and should be removed. Also, I'd strongly prefer having this inline:
```
Isometry3d::Identity() /*X_JpJc*/);
```
but that's up to you.

---

*[multibody/multibody_tree/test/weld_mobilizer_test.cc, line 27 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeZ4CTBw3MW7UP5Pmf:-LCeZ4CTBw3MW7UP5Pmg:bx4yxdq) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/test/weld_mobilizer_test.cc#L27)):*
> ```cpp
> constexpr double kTolerance = 10 * std::numeric_limits<double>::epsilon();
> 
> // Fixture to setup a simple MBT model containing a prismatic mobilizer.
> ```

BTW, s/prismatic/weld throughout this file.

---

*[multibody/multibody_tree/test/weld_mobilizer_test.cc, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeZTwE0nrVTBat3WOo:-LCeZTwE0nrVTBat3WOp:b-kxcgyk) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/test/weld_mobilizer_test.cc#L70)):*
> ```cpp
> };
> 
> // Verifies method to mutate and access the context.
> ```

This description doesn't fit for a weld.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817#-:-LCeZiAI4u3Bbz_NRX7G:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCiLCqw5JFxyw612hBC:-LCiLCqw5JFxyw612hBD:b-fht96e) (no related file):*
FYI,
```
==================== Test output for //multibody/multibody_tree/multibody_plant:multibody_plant_test:
Using drake_cc_googletest_main.cc
...
[==========] Running 8 tests from 4 test cases.
[ RUN      ] SplitPendulum.MassMatrix
Assertion failed: (startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols), function Block, file external/eigen/Eigen/src/Core/Block.h, line 147.
Abort trap: 6
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817)*

**Comment by amcastro-tri** [comment]
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[multibody/multibody_tree/multibody_tree_topology.h, line 819 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCe9Hyu6dNmdHgMB-PW:-LCjPX144g1QpzX06DnR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/multibody_tree_topology.h#L819)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/non-zer/non-zero
</blockquote></details>

Done.

---

*[multibody/multibody_tree/weld_mobilizer.h, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCe9VXx6Ky1LYg7giX0:-LCjPYDcAwgUZSz513jU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/weld_mobilizer.h#L19)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

s/frames/frame
</blockquote></details>

Done.

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 218 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeY0khB6UBbeiydE5m:-LCjOeIlDhaiFdPYhMGS:buz1ezx) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L218)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

BTW, this comment is no longer true. Yay!
</blockquote></details>

True that!

---

*[multibody/multibody_tree/test/weld_mobilizer_test.cc, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCeZTwE0nrVTBat3WOo:-LCjPZRW2lhI6FxPVDXP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/test/weld_mobilizer_test.cc#L70)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

This description doesn't fit for a weld.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[multibody/multibody_tree/weld_mobilizer.cc, line 92 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCjBGeBBCy9UzTaG6nd:-LCjBGeBBCy9UzTaG6ne:b-arrvv3) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/weld_mobilizer.cc#L92)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
> ```

FYI, this is inconsistent with the `.h` file.

---

*[multibody/multibody_tree/joints/weld_joint.h, line 94 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCj9iNs9jcrPVJAjlal:-LCj9iNs9jcrPVJAjlam:b-8c45k9) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/joints/weld_joint.h#L94)):*
> ```objc
> 
>   // The pose of frame C in P.
>   Isometry3<double> X_PC_;
> ```

BTW, it can be marked as `const`.

---

*[multibody/multibody_tree/joints/weld_joint.cc, line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8817#-LCjA0kl7nEe7-VHdBx_:-LCjA0kl7nEe7-VHdBxa:b-arrvv3) ([raw file](https://github.com/robotlocomotion/drake/blob/a17026c3d95c51bb4d1a2a09320242332f334ca4/multibody/multibody_tree/joints/weld_joint.cc#L44)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
> ```

FYI, this is inconsistent with the `.h` file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817#-:-LCjXkU2CcRaYyHVw1bt:bnfp4nl)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8817)*

**Pull request merged**
