### PR TITLE
Add ClpSolver

### PR DESCRIPTION
**Pull request by hongkai-dai**
---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@jwnimmer-tri the CI test only fails on Linux focal, but succeeds on linux bionic. Do you know if the CLP installation on focal is different from Linux bionic? Is there a Focal machine that I can use for debugging?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MVeBq1o3K-4y8ms1VWI:b-gxfgo1)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
You can check Ubuntu versions on packages.ubuntu.com:
  https://packages.ubuntu.com/source/focal/clp

I CC'd you into the slack discussion explaining how to use a Focal schroot locally.  You can also test it in docker locally.  You don't need a different machine.

**Review by hongkai-dai — COMMENTED** [review]
Thanks Jeremy, I think I understand the problem. I currently include two headers in `clp_solver.cc`, namely `ClpModel.hpp` and `CoinBuild.hpp`, as used in CLP upstream example https://github.com/coin-or/Clp/blob/master/examples/addRows.cpp. But `ClpModel.hpp` comes from CLP, while `CoinBuild.hpp` comes from IPOPT. On Focal they are probably incompatible.

I will try to rewrite our wrapper class `ClpSolver` without using `CoinBuild.hpp` header.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MVh5v624IMIKuXJN2RM:b-7tmzhz)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@avalenzu for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MVjiTOI2_Ym7Smp_RJc:b-uss1yj)* status: LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

**Comment by jamiesnape** [comment]
Probably should request a Mac build since the versions are probably going to be different there too.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by avalenzu — COMMENTED** [review]
Review pass done. A few nits and one unrelated change to pull out.

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MWPd6av2KFQP4CbXbAl:b-nljii2)* status: 6 unresolved discussions, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[solvers/choose_best_solver.cc, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPcKe98TEvK9VtveCz:-MWPcKe98TEvK9VtveD-:b-7bd6dw) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/choose_best_solver.cc#L84)):*
> ```cpp
> 
> std::unique_ptr<SolverInterface> MakeSolver(const SolverId& id) {
>   if (id == ClpSolver::id()) {
> ```

minor: I know it doesn't matter functionally, but, to decrease cognitive dissonance for future readers, could you maintain the matching order between the if statements here and the list of solver ids in `GetKnownSolvers()`?
___
*[solvers/clp_solver.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPZ5Q7ECn_kyIhkIqb:-MWPZ5Q7ECn_kyIhkIqc:b-gia5dq) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L31)):*
> ```cpp
>                      constraint_mat.innerIndexPtr(), constraint_mat.valuePtr(),
>                      xlow.data(), xupp.data(), objective_coeff.data(),
>                      constraint_lower.data(), constraint_upper.data(), nullptr);
> ```

nit: Could this `nullptr` get an inline comment saying `/* what it is */`?
___
*[solvers/clp_solver.cc, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPZVfF9fLnQN1_43GE:-MWPZVfF9fLnQN1_43GF:br396nx) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L46)):*
> ```cpp
>   for (int j = 0; j < linear_constraint.variables().rows(); ++j) {
>     const int var_index =
>         prog.FindDecisionVariableIndex(linear_constraint.variables()(j));
> ```

nit: Isn't this just `variable_indices(j)`?
___
*[solvers/clp_solver.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWP_7Uh6GGnERGvonwR:-MWP_7Uh6GGnERGvonwS:b-c6rinx) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L47)):*
> ```cpp
>     const int var_index =
>         prog.FindDecisionVariableIndex(linear_constraint.variables()(j));
>     for (int i = 0; i < linear_constraint.evaluator()->num_constraints(); ++i) {
> ```

minor: If you make the "i" loop the outer one and the "j" loop the inner one, you could set the bounds here as well, instead of having an additional for loop below.
___
*[solvers/mathematical_program_doxygen.h, line 141 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPanGH3YcqrIwlQJep:-MWPanGH3YcqrIwlQJeq:b3srrhx) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/mathematical_program_doxygen.h#L141)):*
> ```objc
>  * <tr><td> &loz;
>  * @ref drake::solvers::MixedIntegerBranchAndBound "naive branch-and-bound"
>  * </td> <td align="center">&diams;</td> <td align="center">&diams;</td> <td
> ```

nit: Looks like some unrelated whitespace changes here.
___
*[solvers/snopt_solver.cc, line 961 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPbAN53nrnquVrFGwh:-MWPbAN53nrnquVrFGwi:b-nqtoke) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/snopt_solver.cc#L961)):*
> ```cpp
>     const std::unordered_map<Binding<Constraint>, int>&
>         constraint_dual_start_index,
>     double ObjAdd, MathematicalProgramResult* result) {
> ```

I know this is a tiny change, but I really think it should get it's own PR. I'm happy to review.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)* status: 1 unresolved discussion, LGTM missing from assignee avalenzu, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @avalenzu)

___
*[solvers/clp_solver.cc, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPZ5Q7ECn_kyIhkIqb:-MWPkYri9PbcTAG6jKHo:b-nv9n2l) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L31)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Could this `nullptr` get an inline comment saying `/* what it is */`?
</blockquote></details>

Done. Good call (I don't know that that `rowObjective` means. Even in CLP's own documentation it puts a question mark. 

___
*[solvers/clp_solver.cc, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPZVfF9fLnQN1_43GE:-MWPlJYf0ekdbmVxf3GC:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L46)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

nit: Isn't this just `variable_indices(j)`?
</blockquote></details>

Done. Good call.
___
*[solvers/clp_solver.cc, line 47 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWP_7Uh6GGnERGvonwR:-MWPlSdh9yiG_k0KQ9Ml:b-yh16l6) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/clp_solver.cc#L47)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

minor: If you make the "i" loop the outer one and the "j" loop the inner one, you could set the bounds here as well, instead of having an additional for loop below.
</blockquote></details>

Done. Good call.
___
*[solvers/snopt_solver.cc, line 961 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWPbAN53nrnquVrFGwh:-MWPmQ2Y7HymlKEX1jVd:b-huwipr) ([raw file](https://github.com/robotlocomotion/drake/blob/3eee4f003563a222775dde5853d57906f639adbb/solvers/snopt_solver.cc#L961)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

I know this is a tiny change, but I really think it should get it's own PR. I'm happy to review.
</blockquote></details>

Done. I filed a separate PR #14809 . I will rebase this branch on top of master once PR #14809 is merged.

**Review by avalenzu — COMMENTED** [review]
:lgtm: +@seancurtis-tri for platform review.

> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MWQT3J44Mm7FFoLXPJ8:b362zgh)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: A couple of small nits and some passing thoughts.

> Reviewed 16 of 22 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776#-:-MWQysQYAHfVSSF6HeSe:b-lfsjt4)* status: 7 unresolved discussions (waiting on @hongkai-dai)

___
*[solvers/BUILD.bazel, line 844 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQvxRQAI4VJmlq3ktC:-MWQvxRQAI4VJmlq3ktD:bop1e68) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/BUILD.bazel#L844)):*
> ```Starlark
> drake_cc_library(
>     name = "clp_solver",
>     srcs = select({
> ```

BTW This could be:

```py
    srcs = ["clp_solver_common.cc"] +
           select({
               "//tools:no_clp": ["no_clp.cc"],
               "//conditions:default": ["clp_solver.cc"],
           }),
```

You could apply a very similar pattern to the dependencies (where the common are simply included in a preliminary list, concatenated to a conditional list.
___
*[solvers/clp_solver.h, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQa1vi69TU5Dyf4WYp:-MWQa1vi69TU5Dyf4WYq:b4bocvp) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L10)):*
> ```objc
> namespace drake {
> namespace solvers {
> struct ClpSolverDetails {
> ```

The other solvers get full doxygenation on these details; why not here?
___
*[solvers/clp_solver.h, line 39 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQaJzb-n3OwvZiXpau:-MWQaJzc1Qx7OhB5j7FM:bp45qf4) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L39)):*
> ```objc
>   static bool ProgramAttributesSatisfied(const MathematicalProgram&);
>   //@}
>   //
> ```

BTW In comparison with other `*_solver.h` files, this empty line of comments is unique. It implies a connection with the previous line which doesn't really exist. For the sake of consistency, probably good to clean it out.
___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWQblILB88nVzOndrdy:bf5srl1) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
> ```objc
>   //
>   // A using-declaration adds these methods into our class's Doxygen.
>   using SolverBase::Solve;
> ```

BTW I'm mildly surprised to see this `using` here. It's a pattern that appears in multiple solver headers, but it doesn't seem to serve any purpose. The *typical* reason to do it is because the base class has a number of overloads and the local class implements an overload as well. We have the first case (overloads on `Solve`) but we don't have the second condition.  Is there a concrete reason for including this `using` in all of these solvers, or are they left over from when the code had a slightly different architecture?
___
*[solvers/clp_solver.cc, line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQd0It6yANfpNYe9j5:-MWQd0It6yANfpNYe9j6:b29fpf4) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.cc#L4)):*
> ```cpp
> 
> #include <limits>
> #include <unordered_map>
> ```

nit: unused
___
*[solvers/clp_solver.cc, line 13 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQcT8X0Wcnzuj-JsY6:-MWQcT8X0Wcnzuj-JsY7:b2uij0u) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.cc#L13)):*
> ```cpp
> namespace drake {
> namespace solvers {
> const double kInf = std::numeric_limits<double>::infinity();
> ```

nit s/`const`/`constexpr`
___
*[solvers/clp_solver.cc, line 127 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQui5a1tTk5ASRbjoF:-MWQui5a1tTk5ASRbjoG:b353dsa) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.cc#L127)):*
> ```cpp
>     }
>     default: {
>       solution_result = SolutionResult::kUnknownError;
> ```

nit: Can we get a note here indicating that we know we're merging multiple Clp return codes into one Drake code?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[solvers/BUILD.bazel, line 844 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQvxRQAI4VJmlq3ktC:-MWREdyK3QsxRL7D0sg3:b6f70xv) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/BUILD.bazel#L844)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This could be:

```py
    srcs = ["clp_solver_common.cc"] +
           select({
               "//tools:no_clp": ["no_clp.cc"],
               "//conditions:default": ["clp_solver.cc"],
           }),
```

You could apply a very similar pattern to the dependencies (where the common are simply included in a preliminary list, concatenated to a conditional list.
</blockquote></details>

Done. Thanks TIL using python syntax in BUILD.bazel
___
*[solvers/clp_solver.h, line 10 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQa1vi69TU5Dyf4WYp:-MWRFBI4EuLQ7eBlakHN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L10)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The other solvers get full doxygenation on these details; why not here?
</blockquote></details>

Done.
___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWRG2Id93B6F-7yGcL8:b-1drtxo) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'm mildly surprised to see this `using` here. It's a pattern that appears in multiple solver headers, but it doesn't seem to serve any purpose. The *typical* reason to do it is because the base class has a number of overloads and the local class implements an overload as well. We have the first case (overloads on `Solve`) but we don't have the second condition.  Is there a concrete reason for including this `using` in all of these solvers, or are they left over from when the code had a slightly different architecture?
</blockquote></details>

I am not sure why I have the 'using' here. The documentation says "A using-declaration adds these methods into our class's Doxygen". But I removed this "using" declaration and the doxygen still generates the expected documentation.

@jwnimmer-tri do you remember why we have this "using" declaration?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),avalenzu (waiting on @hongkai-dai)

___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWRIC24AbUfErfz1H2o:b-h2ae4l) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure why I have the 'using' here. The documentation says "A using-declaration adds these methods into our class's Doxygen". But I removed this "using" declaration and the doxygen still generates the expected documentation.

@jwnimmer-tri do you remember why we have this "using" declaration?
</blockquote></details>

Might just be an anachronism. Certainly not a blocking question.

**Comment by jwnimmer-tri** [comment]
___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWRILCACLJptcvuZtmF:bt18q5u) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Might just be an anachronism. Certainly not a blocking question.
</blockquote></details>

When I preview this locally:

[With using statement](https://files.reviewableusercontent.io/images/reviewable/17596505/37UPMm-OvNesTNzSBwq_ZA8X/image.png)

[Without using agement](https://files.reviewableusercontent.io/images/reviewable/17596505/mOVFq5KKkLHED27ekaWeBaI0/image.png)

It seems like the using-statement is doing exactly what the comment describes.  Are you getting a different result in your preview, Hongkai?  Did you be sure to reload (or shift-reload) when you removed the using?

I think we definitely should keep the using-statements.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),avalenzu (waiting on @SeanCurtis-TRI)

___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWRKgtAC3txJ7CplK4g:b6x7iu7) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I preview this locally:

[With using statement](https://files.reviewableusercontent.io/images/reviewable/17596505/37UPMm-OvNesTNzSBwq_ZA8X/image.png)

[Without using agement](https://files.reviewableusercontent.io/images/reviewable/17596505/mOVFq5KKkLHED27ekaWeBaI0/image.png)

It seems like the using-statement is doing exactly what the comment describes.  Are you getting a different result in your preview, Hongkai?  Did you be sure to reload (or shift-reload) when you removed the using?

I think we definitely should keep the using-statements.
</blockquote></details>

Sorry I must have made a mistake when generating the doxygen. Yes the using declaration gives me the documentation for Solve method. Removing the using declaration, the documentation is gone.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14776)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),avalenzu (waiting on @hongkai-dai)

___
*[solvers/clp_solver.h, line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14776#-MWQblILB88nVzOndrdx:-MWROr4r2_fxC4IyIOiB:bqog80t) ([raw file](https://github.com/robotlocomotion/drake/blob/e7d7c72393e8d659359ddc286ba8c57abf428e46/solvers/clp_solver.h#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I must have made a mistake when generating the doxygen. Yes the using declaration gives me the documentation for Solve method. Removing the using declaration, the documentation is gone.
</blockquote></details>

Agreed

**Pull request merged**
