### PR TITLE
[planning] Add RobotClearance

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Towards #14431.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review please.

+(release notes: feature) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NIiaZw4EA5POQpE7ipL:byptsy)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NIik4SnD8jBZIQtXSEv:bnfp4nl)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418)* status: needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sammy-tri for platform review.

This is a port from Anzu. Please treat *all* lines of code as new.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NIm5mdD7NQ3-Ddw_Kmx:b8v1t5p)* status: LGTM missing from assignee sammy-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+(status: commits are properly curated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NInBdjt5UusxU-zCGc8:b-qv2c28)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
Whee, now you get to run the curated-commits rebase race.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NInBj8Q9GEB2Gf1Yy7m:bccybe2)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Can you explain why we do two commits? 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NInCg-d803ihuZWZ_wm:bjbjp2n)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
It clarifies the origin with the exact text in one, and the adaptations in the second. If @jwnimmer-tri wants to weigh in as well, have at it.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NInDnsS2wTwEpFhQz5h:bkx852g)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Fair enough...let the race, commence!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18418#-:-NInEK5m89-boIBm_-7I:b-68z0u8)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @SeanCurtis-TRI)

**Comment by rpoyner-tri** [comment]
Victory! Now I have to rebase :)

**Pull request merged**
