### PR TITLE
Use python3-semantic-version package on Ubuntu

### LINKED ISSUE #14749: Use python3-semantic-version package on Ubuntu
Instead of `@semantic_version`. Not sure why we do not at present.

FYI @jwnimmer-tri.

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #14749

Will need a CI update prior to merge.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
For clarification, is the plan also to switch semantic version on macOS to use `requirements.txt`, and so we can drop it from our workspace entirely?  Using it from the workspace 50% of the time seems worse to me than either 0% or 100%, since we still have the burden of maintaining the workspace rules they'd not be tested pre-merge.  I don't mind if the macOS change is in this same PR or a separate PR, but I think we should go either all the way or none of it?

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot mac-catalina-unprovisioned-clang-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please.
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-snopt-packaging please.

**Comment by BetsyMcPhail** [comment]
> For clarification, is the plan also to switch semantic version on macOS to use `requirements.txt`, and so we can drop it from our workspace entirely? Using it from the workspace 50% of the time seems worse to me than either 0% or 100%, since we still have the burden of maintaining the workspace rules, but they'd not be tested pre-merge. I don't mind if the macOS change is in this same PR or a separate PR, but I think we should go either all the way or none of it? (I didn't quite realize the implications of the #14749 ticket when it was first proposed.)

Let's update both Mac and Ubuntu at once and remove semantic_version from the workspace completely.

**Review by BetsyMcPhail — COMMENTED** [review]
+@jamiesnape for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MW53wiS2Fswtb9kZFcW:bdx3wf2)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @BetsyMcPhail)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWAAz2c1lhksRvNoOW7:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @BetsyMcPhail)

**Comment by jamiesnape** [comment]
+@SeanCurtis-TRI for feature review.

**Review by jwnimmer-tri — COMMENTED** [review]
I have some comments below, so I'll take over platform review as well.

-@SeanCurtis-TRI +@jwnimmer-tri for platform.

> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWADHOM7GGKVLTO8f3Q:b-wog77t)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @BetsyMcPhail)

___
*[tools/workspace/default.bzl, line 245 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14784#-MWADAeP5rlxekHsRXTn:-MWADAeP5rlxekHsRXTo:b-nk6wtj) ([raw file](https://github.com/robotlocomotion/drake/blob/693c8497ff4d8bb7869ccbf0a9d8fbe90aa8c92d/tools/workspace/default.bzl#L245)):*
> ```Starlark
>         sdformat_repository(name = "sdformat", mirrors = mirrors)
>     if "semantic_version" not in excludes:
>         semantic_version_repository(name = "semantic_version", mirrors = mirrors)  # noqa
> ```

nit This is a breaking change (see other thread) -- so this patch should not happen in this PR, but rather in the removal PR a few months down the road.
___
*[tools/workspace/semantic_version/package.BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14784#-MWACTiO2gNl4BhxbDuq:-MWACTiO2gNl4BhxbDur:b-l28g60) ([raw file](https://github.com/robotlocomotion/drake/blob/693c8497ff4d8bb7869ccbf0a9d8fbe90aa8c92d/tools/workspace/semantic_version/package.BUILD.bazel#L11)):*
> ```
>     srcs = glob(["*.py"]),
>     visibility = ["//visibility:public"],
> )
> ```

Instead of removing this directly (which is a breaking change for users), we should use `deprecation = ...` here instead.

```python
deprecation = "DRAKE DEPRECATED: The @semantic_version repository is being removed from Drake on or after 2021-07-01. Downstream projects should add it to their own WORKSPACE if needed.",  # noqa
```

Therefore, none of the files in this folder should be removed in this PR, also.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM, modulo new CI images rolling out first.

> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWUs89t88OyPXZ8F6XN:b-4ubqay)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge" (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
Ah, the images must already be updated, since CI is passing.  Thus, :lgtm: both reviews.

**Review by BetsyMcPhail — COMMENTED** [review]
Images have not been updated. Do we expect CI to fail? This should no longer be a breaking change?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWVbMJ2BHQDZ07Je99s:b-w4e6ni)* status: labeled "do not merge" (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
Aha, I overlooked one change in r2.  See below.

> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWVblbeEGqx7hTwvBVn:bxkwjgl)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @BetsyMcPhail)

___
*[tools/workspace/pycps/package.BUILD.bazel, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14784#-MWVbwt09vhhGSkODU4p:-MWVbwt09vhhGSkODU4q:brbyhjp) ([raw file](https://github.com/robotlocomotion/drake/blob/d3c2c70944176940a154a5bd95f1f77ff364d971/tools/workspace/pycps/package.BUILD.bazel#L19)):*
> ```
>     srcs = ["cps.py"],
>     visibility = ["//visibility:public"],
>     deps = ["@semantic_version"],
> ```

Our builds now spam the user: `[2021-03-23T16:19:00.111Z] WARNING: /media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-experimental-release/_bazel_ubuntu/c1977afaa3c50edead0abe83ebdc6e9e/external/pycps/BUILD.bazel:15:11: in py_library rule @pycps//:cps: target '@pycps//:cps' depends on deprecated target '@semantic_version//:semantic_version': DRAKE DEPRECATED: The @semantic_version repository is being removed from Drake on or after 2021-07-01. Downstream projects should add it to their own WORKSPACE if needed.`

This line should in fact be removed, as it was in r1, so that we're actually using the Ubuntu (or macOS) semantic-version.  Therefore for CI to pass, we'll need new images first.

**Review by jwnimmer-tri — COMMENTED** [review]
Still LGTM once CI is happy (via new images).

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWWQWWpBr70kLZHhdm3:b-v119xx)* status: labeled "do not merge" (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
Mac & Ubuntu images have been updated, I'll re-run the tests tomorrow to be sure Jenkins has switched over.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14784#-:-MWWYr1g7pLU_s0SRyde:b-9sr15o)* status: labeled "do not merge" (waiting on @BetsyMcPhail)

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
