### PR TITLE
Move the examples/Cars models into a models subdir

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2232) &emsp; Multiple assignees:&emsp;@ggould-tri&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/ggould-tri">ggould-tri</a>,&emsp;@liangfok&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/liangfok">liangfok</a>

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok PTAL.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGm7i7eoMEQy-c2ViiQ:-1650654946)*

**Comment by liangfok** [comment]
@jwnimmer-tri left one comment.

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/README.md, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-KGmBLT3VxEzVEOLcEOa:-KGmBLT3VxEzVEOLcEOb:927480590) ([raw file](https://github.com/robotlocomotion/drake/blob/8bdc4a41b8c77b25c9ae6fff7f7b3262568f4678/drake/examples/Cars/README.md#L26)):*
Do be consistent, let's move `stata_garage_p1.sdf` to `models/stata_garage/stata_garage_p1.sdf`. This directory will likely eventually hold a bunch more SDFs of the garage, like one for each floor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmBhSzNTIaXVcPAqfY:1498360656)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/README.md, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-KGmBLT3VxEzVEOLcEOa:-KGmCiXKq7dv8XLrK2Qb:2106797517) ([raw file](https://github.com/robotlocomotion/drake/blob/8bdc4a41b8c77b25c9ae6fff7f7b3262568f4678/drake/examples/Cars/README.md#L26)):*
Can I let someone else deal with that once it becomes relevant?  I'll posit that this PR is strictly better than existing conditions, and does not violate any code conventions or clarity rules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232)*

**Comment by liangfok** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/README.md, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-KGmBLT3VxEzVEOLcEOa:-KGmDNThXvVQI_7GjZ3f:-1530771663) ([raw file](https://github.com/robotlocomotion/drake/blob/8bdc4a41b8c77b25c9ae6fff7f7b3262568f4678/drake/examples/Cars/README.md#L26)):*
Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmDRIR_NCogvGCymjg:-1868698381)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri Could you do a once-over and merge?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmSzPWKidwggOGOWBh:1688453627)*

**Comment by jwnimmer-tri** [comment]
Oops, looks like jenkins has some complaints.  I will look into those now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmTEE3rY76QD_5lymd:356049174)*

**Comment by jwnimmer-tri** [comment]
-@david-german-tri +@ggould-tri Will take this over.

---

Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmg8Bd3c0WPWLWhiFC:-1812910009)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232#-:-KGmgScEyaskyxrfADut:1417088721)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2232)*

**Comment by jwnimmer-tri** [comment]
Using override-merge to get around out-of-date-with-master.  The only unmerged changes from master are a code style doc fix.

**Pull request merged**
