### PR TITLE
Fixing A Few UBSan Issues

### PR DESCRIPTION
**Pull request by m-chaturvedi**
https://drake-cdash.csail.mit.edu/viewDynamicAnalysis.php?buildid=687286

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6509)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

**Comment by jwnimmer-tri** [comment]
@m-chaturvedi This PR hasn't changed in a while; is it still worth keeping open?

**Comment by m-chaturvedi** [comment]
No, closing it.

**Pull request closed without merging**
