### PR TITLE
Remove everything in the attic

### LINKED ISSUE #12158: Deprecation timeline for RigidBodyTree and attic
FYI For the new APIs, see [`MultibodyPlant<T>` documentation](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html).

If you have questions or need help converting to `MultibodyPlant` please use https://drake.mit.edu/getting_help.html. If there are missing features that could block your workflow, please let us know NOW by commenting on this issue.

---

We are wondering if it's time to finally remove the `RigidBodyTree`, `RigidBodyPlant`, and related attic code and examples from Drake master.

We would like to understand the useful timeline for keeping them -- what issues with MultibodyPlant do we need to solve first, how long do users need to finish their transition to MultibodyPlant, and therefore what is a good target date for removing the code.

We are hoping for a removal date in early 2020.

I'd like to ask any users who would like to influence this timeline to speak up here, or on `#dynamics` slack.

Known possible blockers:
- #10322
- #11831

Feature request buckets:
- #5013 
- #7025

See also #9783 for past work on the attic.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #12158.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13889)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Soooo excited!!!

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI would you like to review this over the next week?

The changes other than pure deletions relate to build system and pydrake doc / shared library integration.

**Comment by EricCousineau-TRI** [comment]
> Will we have a "last SHA with attic" tag to make it easier to go back and look for any lost technology that might still be up there?

As a workaround, you could do `git log -- attic/`?

**Comment by jwnimmer-tri** [comment]
The linked issue talks about making a tag.  It might still be a good idea.  However, also note that all of v0.10 through v0.22 release tags also have the attic code.  Posting that in the issue might be good enough.  We can also always go back and make a tag later, it doesn't have to be concurrent with the merge.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Woo hoo!

**Pull request merged**
