### PR TITLE
 pydrake: Add all_install_test. 

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This also fixes a small bug in `install_test_helpers` (where it assumed the `installation_folder` was `tmp` in one piece of logic) and allows running install tests via `bazel run`.

I manually tested this before the merge of #7936 and confirmed that it failed (and thus should have caught that error).

This is another specific installation test incantation, probably to be superseded by the completion of testing in #7774?

\cc @fbudin69500

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7938)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please.
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please.

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for feature review, please.
+@sherm1 for platform review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-:-L4MPzxjKtdBpF5UXbDm:bdkf0gx)*

**Comment by sherm1** [comment]
CI failures?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-:-L4Mus8TC-b2C0iwu8YW:bksknep)*

**Comment by EricCousineau-TRI** [comment]
Hup, fixed!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-:-L4NDkLECuzDKfzBaMvA:bk35mqn)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/install_test_helper.py, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-L4NILYFtKjuxdAFQW9Y:-L4NILYGhsmYtAZfAt3y:b-2ln2jm) ([raw file](https://github.com/robotlocomotion/drake/blob/4d394c79ef2f852463a10710d468153b6ae33dd3/tools/install/install_test_helper.py#L42)):*
> ```Python
>     # If under `bazel test`, remove Bazel build artifacts, and ensure that we
>     # only have install artifacts. If we removed these files under `bazel run`,
>     # then Bazel may not refresh `.runfiles`, breaking future invocations.
> ```

I'm hesitant to hazard losing this leg of the test coverage.

How important is this part of the change?  Could we instead just bomb out if `bazel run` is detected?    Yes, `bazel test` should behave identically with only changes in this PR, but if something else shifts maybe we'd lose out on the rmtree.  Since this code will be rewritten soon in the other PR, my preference would be to leave it alone for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-:-L4NIuzovVQRJkg24BBT:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install/install_test_helper.py, line 42 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-L4NILYFtKjuxdAFQW9Y:-L4NOOeMu0IwWjhO5aV0:b5iaa2c) ([raw file](https://github.com/robotlocomotion/drake/blob/4d394c79ef2f852463a10710d468153b6ae33dd3/tools/install/install_test_helper.py#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'm hesitant to hazard losing this leg of the test coverage.

How important is this part of the change?  Could we instead just bomb out if `bazel run` is detected?    Yes, `bazel test` should behave identically with only changes in this PR, but if something else shifts maybe we'd lose out on the rmtree.  Since this code will be rewritten soon in the other PR, my preference would be to leave it alone for now.
</blockquote></details>

Done. Constraining test to only be run in `bazel test`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938)*

**Comment by sherm1** [comment]
Platform :lgtm: with one minor BTW.

---

Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 168 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-L4Nif8mckrgv3j95rl7:-L4Nif8mckrgv3j95rl8:b6mn4sy) ([raw file](https://github.com/robotlocomotion/drake/blob/b6ce3a46e879b33b43b4612bcc5a3af50a5398ae/bindings/pydrake/BUILD.bazel#L168)):*
> ```Python
> )
> 
> # See `common_install_test` for explanation of values.
> ```

BTW Not sure I understand what values you mean here but I don't see an explanation in common_install_test? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-:-L4NjabLGOXnC5lJj5t2:b-o8mr8k)*

**Comment by EricCousineau-TRI** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[bindings/pydrake/BUILD.bazel, line 168 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7938#-L4Nif8mckrgv3j95rl7:-L4Npmk9JpBg8lwmoCo7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b6ce3a46e879b33b43b4612bcc5a3af50a5398ae/bindings/pydrake/BUILD.bazel#L168)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Not sure I understand what values you mean here but I don't see an explanation in common_install_test? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7938)*

**Pull request merged**
