### PR TITLE
[solvers] Add FindNonconvexQuadraticConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Returns the first non-convex quadratic constraint among a list of quadratic constraints.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYg-h6wBrqfWsqqfoRR:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYsvhbJDyP7fteVbidI:-NYutfTLEIOZFXNphVhl:b-w42t5i) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebab07e682034e167808397840816ecc784dc794/solvers/aggregate_costs_constraints.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This function is blindingly simple (it's basically just https://en.cppreference.com/w/cpp/algorithm/find overload 3).

Do we _need_ to make it public API, with all the documentation and stability and python bindings guarantees that implies?

Maybe it should be `internal` instead?
</blockquote></details>

Good call.

Then maybe we should also make its cousin `FindNonconvexQuadraticCost` in the internal namespace? If I do that in this PR, would it count as a breaking change?
___
*[`solvers/aggregate_costs_constraints.cc` line 299 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYsvxx9EkVhvJo1Z7gk:-NYuvuRVEwF7DOb288OK:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebab07e682034e167808397840816ecc784dc794/solvers/aggregate_costs_constraints.cc#L299)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems like the most important part of this PR.  But there is no regression test that covers it?
</blockquote></details>

Done. Good call.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYx6TG_27fdwK7OVVr8:b-n37teh)* status: 1 unresolved discussion, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYsvhbJDyP7fteVbidI:-NYx66f-E_LIjlR_4MH-:bwehpcq) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebab07e682034e167808397840816ecc784dc794/solvers/aggregate_costs_constraints.h#L109)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Good call.

Then maybe we should also make its cousin `FindNonconvexQuadraticCost` in the internal namespace? If I do that in this PR, would it count as a breaking change?
</blockquote></details>

The `FindNonconvexQuadraticCost` has been around for a while, so yes it would be breaking.  We should use deprecation to remove it.  I can open a separate PR for that, if you like?  In this PR, we could still mark this new one as internal.

**Review by hongkai-dai — COMMENTED** [review]
+@sammy-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYy7LVU46YVm8iSxZ3L:b-c9pjop)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/aggregate_costs_constraints.h` line 109 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYsvhbJDyP7fteVbidI:-NYy6uTzC-Jw7IPFL9oB:b8x86pr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ebab07e682034e167808397840816ecc784dc794/solvers/aggregate_costs_constraints.h#L109)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The `FindNonconvexQuadraticCost` has been around for a while, so yes it would be breaking.  We should use deprecation to remove it.  I can open a separate PR for that, if you like?  In this PR, we could still mark this new one as internal.
</blockquote></details>

Done. I moved this function to the internal namespace and deprecate the old function.

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: newly deprecated) 
+(release notes: fix) 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYy7vA97uv6pOKqNXWu:beaq9zw)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform)

___
*[`solvers/aggregate_costs_constraints.h` line 102 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYy84WECZbGGxXP0MkE:-NYy84WECZbGGxXP0MkF:bl6dlik) ([raw file](https://github.com/RobotLocomotion/drake/blob/756a591a997a4c2d647e522562194a0d435377c5/solvers/aggregate_costs_constraints.h#L102)):*
> ```objc
> DRAKE_DEPRECATED("2023-11-01",
>                  "This function has been moved to the internal namespace. Use "
>                  "solvers::internal::FindNOnconvexQuadraticCost")
> ```

nit Users are not supposed to call the internal namespace.



_Suggestion:_
```objc
                 "This function is no longer public.")
```

**Review by jwnimmer-tri — COMMENTED** [review]
FYI If you `bazel test //solvers/...` you'll see that there's one more change necessary for a passing build.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYyCuIfBz5O2Nov1Lxj:b-4821zh)* status: LGTM missing from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
I'm out of time today.  -@sammy-tri +@EricCousineau-TRI for tomorrow

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NYz2iHZ51tGV7IXR4Kb:bociqk9)* status: LGTM missing from assignee EricCousineau-TRI(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform)

___
*[`-- commits` line 6 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-NYz4HLT1wkt_kB9Wj1S):*
nit As far as a commit message goes, the new function is not notable anymore.

The things we should focus on here are like this:

> [solvers] Convex solvers reject non-convex quadratic constraints
>
> In particular, CLP, Gurobi, Mosek, and SCS will reject such constraints with a helpful error message.
>
> Move FindNonconvexQuadraticCost to the internal namespace, deprecate the old function outside of the internal namespace.

**Review by EricCousineau-TRI — COMMENTED** [review]
Ah, nvm - CI needs some fixing

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668#-:-NZ1Rk-i-bRNzZSTxqq8:b3k92mi)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19668)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

**Pull request merged**
