### PR TITLE
Adds wsg_50_description.

### PR DESCRIPTION
**Pull request by liangfok**
This is an incremental step towards #5267. Note that it does not yet integrate the gripper with the iiwa arm or provide fancy features like the ability to generate models with alternative collision models. Those features will be added in follow-up PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5809)

### CODE REVIEW

**Comment by liangfok** [comment]
+@ericcousineau-tri for feature review since you reviewed the similar #5636 and #5660 PRs. Thanks.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KhYndFzFCLTlXPebLsv:b1bmzoe)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:


Sorry for the late follow-up! Just made some minor comments, otherwise, looks good!

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/model.config, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhwT7yc-xM-qK-9qB4a:-KhwT7yc-xM-qK-9qB4b:b-kmlgjt) ([raw file](https://github.com/robotlocomotion/drake/blob/60e83c59ddc0e574617506c78fa0facb5ff95774/drake/manipulation/models/wsg_50_description/model.config#L7)):*
> ```
>     <sdf>urdf/wsg_50_mesh_collision.urdf</sdf>
>     <author>
>         <name></name>
> ```

BTW, for consistency, should we have authorship / contact here?

---

*[drake/manipulation/models/wsg_50_description/README.md, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhwTFtb9Omi-S0nBeCb:-KhwTFtcceYuLut6Eqlu:bjhtkgt) ([raw file](https://github.com/robotlocomotion/drake/blob/60e83c59ddc0e574617506c78fa0facb5ff95774/drake/manipulation/models/wsg_50_description/README.md#L6)):*
> ```Markdown
> 
> ```
> source /opt/ros/kinetic/setup.bash
> ```

BTW, Given that this has been included before for the IIWA, would it be useful to make a convention? (e.g., having a script that generates version-controlled artifacts?)
This convention could be merged with the named basis vector codegen approach as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KhwTny20eecYXF91M5p:brsc40q)*

**Comment by liangfok** [comment]
No worries. Thanks for the review.
+@sherm1 for platform review please.

---

Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/model.config, line 7 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhwT7yc-xM-qK-9qB4a:-KhxWy5sK4iw_Q13YA7t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60e83c59ddc0e574617506c78fa0facb5ff95774/drake/manipulation/models/wsg_50_description/model.config#L7)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW, for consistency, should we have authorship / contact here?
</blockquote></details>

Done.

---

*[drake/manipulation/models/wsg_50_description/README.md, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhwTFtb9Omi-S0nBeCb:-KhxX-HxAzJj-nrswRvO:b-c8t2z1) ([raw file](https://github.com/robotlocomotion/drake/blob/60e83c59ddc0e574617506c78fa0facb5ff95774/drake/manipulation/models/wsg_50_description/README.md#L6)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW, Given that this has been included before for the IIWA, would it be useful to make a convention? (e.g., having a script that generates version-controlled artifacts?)
This convention could be merged with the named basis vector codegen approach as well.
</blockquote></details>

Yes, replacing this with a script is preferable. Let's make the switch in followup PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KhxXMC8rrusuPLYVSUd:btrkhd3)*

**Comment by sherm1** [comment]
Platform :lgtm: after resolving some BTWs, ptal. A general comment: there is an assortment of mysterious boilerplate here, I think, like nearly identical xml files model.config and package.xml. I'm guessing that has something to do with ROS but I really don't know. It would have been helpful for me if each human-written file started with some English comments explaining what it is. I'm not blocking on that but if there is something useful you could put to provide some context, please do.

---

Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxbJ_OccCAAzqcO9vC:-KhxbJ_OccCAAzqcO9vD:bkqoyxt) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/BUILD#L19)):*
> ```Python
>         "**/*.obj",
>         "**/*.urdf",
>         "**/*.xml",
> ```

BTW generally speaking we prefer explicit file names to glob in the build system. Is there a reason to use glob here rather than list the small number of actual files?

---

*[drake/manipulation/models/wsg_50_description/model.config, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxaesBL1rBrAas14Vn:-KhxaesBL1rBrAas14Vo:b-btyhe6) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/model.config#L5)):*
> ```
>     <name>wsg_50</name>
>     <version>1.0</version>
>     <sdf>urdf/wsg_50_mesh_collision.urdf</sdf>
> ```

BTW seems odd to have tag `<sdf>` but then use a `.urdf` file rather than an `.sdf`. No complaint -- I just want to check that this is your intent.

---

*[drake/manipulation/models/wsg_50_description/README.md, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxc-e__B8g_xEEycXd:-Khxc-e__B8g_xEEycXe:b-78qbdw) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/README.md#L10)):*
> ```Markdown
> export ROS_PACKAGE_PATH=`pwd`:$ROS_PACKAGE_PATH
> cd wsg_50_description
> rosrun xacro xacro -o urdf/wsg_50_mesh_collision.urdf urdf/wsg_50_mesh_collision.urdf.xacro
> ```

BTW "xacro xacro" -- is that right?

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxc_jJjxNU8RFUONj7:-Khxc_jJjxNU8RFUONj8:bwx0tlg) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L1)):*
> ```XML
> <?xml version="1.0"?>
> ```

BTW I believe this is the real source for the model, right? If so it needs at least a short block of comments at the top saying what it is.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50_mesh_collision.urdf.xacro, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxd6z8swvi4K3pCe1P:-Khxd6z8swvi4K3pCe1Q:baffomb) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/urdf/wsg_50_mesh_collision.urdf.xacro#L4)):*
> ```XML
> 
> 
> ```

BTW I'm glad there is a comment here but it seems to lack context. I don't see any meshes below and I don't see any primitives competing with them. Can you be more specific about what this particular file is about? As written I'm guessing it is actually describing something in the wsg_50 file instead? If so the comment should go there rather than here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KhxdmjjzWRBCmFuTilK:byxmsnk)*

**Comment by sherm1** [comment]
Is this ready to merge, @liangfok ?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KjPHNP1qe0ZbU3i-8Z8:b-ke154h)*

**Comment by jwnimmer-tri** [comment]
*[drake/manipulation/models/wsg_50_description/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxbJ_OccCAAzqcO9vC:-KjPIUnZAN4kseWEi__-:b65e7b6) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/BUILD#L19)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW generally speaking we prefer explicit file names to glob in the build system. Is there a reason to use glob here rather than list the small number of actual files?
</blockquote></details>

FYI This the `filegroup(name = "models", ... glob ...)` is widely used throughout the project.  (I think we should make it a macro, actually.)  To my estimation, hand-curating the list of data files adds little value -- everything should come along; as people add different resources, its nice to not have to update the list of files all the time.

The hazard to think about is if the glob gives us too much or too little.  Have we seen any examples of where it misbehaved, even once?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809)*

**Comment by liangfok** [comment]
Not yet, sorry for the delay. I'll address your BTW comments soon.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/model.config, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxaesBL1rBrAas14Vn:-Kj3RQs34FyU-C7zf9rc:b-sn2z4f) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/model.config#L5)):*
Yes, this is correct based on the following `model.config` documentation:

http://gazebosim.org/tutorials?tut=model_structure&cat=#ModelConfig

> * \<sdf\> required
>
> The name of a SDF or URDF file that describes this model. The version attribute indicates what SDF version the file uses, and is not required for URDFs.

---

*[drake/manipulation/models/wsg_50_description/README.md, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxc-e__B8g_xEEycXd:-Kj3SEsexxDsiPI-Xn5U:b-rvmcym) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/README.md#L10)):*
Yes, this is correct. The first `xacro` identifies the ROS package and the second `xacro` identifies the exectuable to run.

http://wiki.ros.org/rosbash#rosrun

> Usage:
> 
> rosrun \<package\> \<executable\>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KjQBpNTaaeqEu1F2vQI:bqffdxf)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 6 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxbJ_OccCAAzqcO9vC:-KjZoXUj3l4HuPx5caFl:b1bwp70) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/BUILD#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This the `filegroup(name = "models", ... glob ...)` is widely used throughout the project.  (I think we should make it a macro, actually.)  To my estimation, hand-curating the list of data files adds little value -- everything should come along; as people add different resources, its nice to not have to update the list of files all the time.

The hazard to think about is if the glob gives us too much or too little.  Have we seen any examples of where it misbehaved, even once?
</blockquote></details>

Done. I cannot think of an instance where glob grabbed too much data. However, I went ahead and listed all of the data files anyway.

---

*[drake/manipulation/models/wsg_50_description/model.config, line 5 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxaesBL1rBrAas14Vn:-KjZpyTLd_zdluKQrHdC:bwwujux) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/model.config#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, this is correct based on the following `model.config` documentation:

http://gazebosim.org/tutorials?tut=model_structure&cat=#ModelConfig

> * \<sdf\> required
>
> The name of a SDF or URDF file that describes this model. The version attribute indicates what SDF version the file uses, and is not required for URDFs.
</blockquote></details>

I've updated the documentation to include the above information.

---

*[drake/manipulation/models/wsg_50_description/README.md, line 10 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxc-e__B8g_xEEycXd:-KjZtk5EJtyxMiz6Y61-:bwkgsrn) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/README.md#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Yes, this is correct. The first `xacro` identifies the ROS package and the second `xacro` identifies the exectuable to run.

http://wiki.ros.org/rosbash#rosrun

> Usage:
> 
> rosrun \<package\> \<executable\>

</blockquote></details>

Since I plan to replace these manual instructions with an automated script in a follow-up PR, I've elected not to include the above details in this PR.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxc_jJjxNU8RFUONj7:-KjZsYIwwMxyEJbPWlN-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I believe this is the real source for the model, right? If so it needs at least a short block of comments at the top saying what it is.
</blockquote></details>

Done.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50_mesh_collision.urdf.xacro, line 4 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Khxd6z8swvi4K3pCe1P:-KjZtMhhaH5OHj6sSwUt:bchtfx3) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/urdf/wsg_50_mesh_collision.urdf.xacro#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I'm glad there is a comment here but it seems to lack context. I don't see any meshes below and I don't see any primitives competing with them. Can you be more specific about what this particular file is about? As written I'm guessing it is actually describing something in the wsg_50 file instead? If so the comment should go there rather than here.
</blockquote></details>

Done. I worded it to be robust against future refinements to the xacro files that will parameterize the mesh type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-KjZzmz2qoR_0DA90tlK:bblnx7i)*

**Comment by jwnimmer-tri** [comment]
*[drake/manipulation/models/wsg_50_description/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxbJ_OccCAAzqcO9vC:-Kj_0BY_Mj9aLOw0QaJ0:b-b4ap7b) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/BUILD#L19)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Done. I cannot think of an instance where glob grabbed too much data. However, I went ahead and listed all of the data files anyway.
</blockquote></details>

With this change, someone who stumbled upon this will wonder why this one folder's approach is different that the dozens of other examples in the project.  If this BUILD files is going to list everything out, at least rename it the target to be something like `:wsg_50_mesh_collision` that differs from the pre-existing `:models` idiom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809)*

**Comment by liangfok** [comment]
Review status: 6 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/BUILD, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-KhxbJ_OccCAAzqcO9vC:-Kj_3fTP65VzMcdx7YB8:bs7wumb) ([raw file](https://github.com/robotlocomotion/drake/blob/c927da9ec3885d4956c930aa5d602b75f4c94f28/drake/manipulation/models/wsg_50_description/BUILD#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

With this change, someone who stumbled upon this will wonder why this one folder's approach is different that the dozens of other examples in the project.  If this BUILD files is going to list everything out, at least rename it the target to be something like `:wsg_50_mesh_collision` that differs from the pre-existing `:models` idiom.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809)*

**Comment by liangfok** [comment]
@drake-jenkins-bot retest this please.

**Comment by sherm1** [comment]
:lgtm: - a couple of BTW typos

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Kj_8GiwcY-7PsKsdo7N:-Kj_8GiwcY-7PsKsdo7O:bwgca4t) ([raw file](https://github.com/robotlocomotion/drake/blob/66a112a2badb43c0680a53d80b93d5147425ffd8/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L10)):*
> ```XML
>      attached.
>   3. origin - X_PG where P is the parent body's frame and G is
>      the gipper's base frame.
> ```

BTW gipper -> gripper

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Kj_8TIzal6q2tt5jVaT:-Kj_8TIzal6q2tt5jVaU:b-6dyn8k) ([raw file](https://github.com/robotlocomotion/drake/blob/66a112a2badb43c0680a53d80b93d5147425ffd8/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L14)):*
> ```XML
>   Since this file only defines a macro, it is not meant to be used directly with
>   the xacro exectuable. Instead, another xacro file must call this macro while
>   supplying the nessary parameters. See, for example, the other *.urdf.xacro
> ```

BTW typos: exectuable, nessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-:-Kj_8gxf4d3fGR19hm2s:b-p66r4m)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 10 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Kj_8GiwcY-7PsKsdo7N:-Kj_aFRA6dF_qcSNfR-c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66a112a2badb43c0680a53d80b93d5147425ffd8/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L10)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW gipper -> gripper
</blockquote></details>

Done.

---

*[drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro, line 14 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/5809#-Kj_8TIzal6q2tt5jVaT:-Kj_aGDuZI086iMiAUqD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/66a112a2badb43c0680a53d80b93d5147425ffd8/drake/manipulation/models/wsg_50_description/urdf/wsg_50.urdf.xacro#L14)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW typos: exectuable, nessary
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5809)*

**Pull request merged**
