### PR TITLE
[models] Move ycb models into drake_models package

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/13942.

Twin PR: https://github.com/RobotLocomotion/models/pull/42.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for both reviews, please (load balancing Rico).

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-:-NtrSwT82Ulq7GFzbBHy:b4g1oqt)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`manipulation/models/ycb/test/parse_test.cc` line 0 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrSbiI2TuqflPoTIDI:-NtrSbiI2TuqflPoTIDJ:bec51q6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff7f196e3f6a71bf47f76bd08ea752e25f064aa3/manipulation/models/ycb/test/parse_test.cc#L0)):*
FYI The `drake/tools/workspace/drake_models/test/parse_test.py` runs _all_ of its model files through the parser, so we don't need bespoke unit tests like this anymore.
___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrSlKk4e3r14ciCMXm:-NtrSlKk4e3r14ciCMXn:bpom6vr) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff7f196e3f6a71bf47f76bd08ea752e25f064aa3/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "209d8aece4e3b5d36f0831f95156c2c89b01ea3a",
> ```

Working

Needs the final commit sha from models master.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrUa-B-ESb5kHvqcwg:-NtrUa-C49NlRklmvkVP:b-k9sqgh) (no related file):*
Working

Blocking merge so I can coordinate the Anzu upgrade at the same time.  There are couple hard-coded YCB paths there that will need fixing.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2 

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-:-NtrX_V9DVRfpDPNAqiU:b-jhwb49)* status: 3 unresolved discussions

___
*[`bindings/pydrake/test/parse_models_test.py` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrXHBa2ZM-5iT-blc_:-NtrXHBa2ZM-5iT-blca:b-itd37j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff7f196e3f6a71bf47f76bd08ea752e25f064aa3/bindings/pydrake/test/parse_models_test.py#L47)):*
> ```Python
>                 model_files.remove(model_file)
>             if model_relpath.startswith("external/drake_models/"):
>                 # These are checked elsewhere by drake_models-specific tests.
> ```

BTW It might be worth calling out `parse_test.py`. It would be hard to know the correctness of this statement without some kind of cross reference. Hard to maintain.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190)* status: 3 unresolved discussions

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190)* status: 2 unresolved discussions

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrSlKk4e3r14ciCMXm:-NtrYV_9ERSjEJ-fs2z1:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff7f196e3f6a71bf47f76bd08ea752e25f064aa3/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs the final commit sha from models master.
</blockquote></details>

Done
___
*[`bindings/pydrake/test/parse_models_test.py` line 47 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrXHBa2ZM-5iT-blc_:-NtrY4GH0j34Y2ryFPrm:bczlcmy) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff7f196e3f6a71bf47f76bd08ea752e25f064aa3/bindings/pydrake/test/parse_models_test.py#L47)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW It might be worth calling out `parse_test.py`. It would be hard to know the correctness of this statement without some kind of cross reference. Hard to maintain.
</blockquote></details>

I understand the point, but OTOH soon I aim to kill that test and replace it with more thorough CI on `drake_models` itself (so that the parse test runs pre-merge there), in which case this comment would immediately bitrot.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21190)* status: 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21190#-NtrUa-B-ESb5kHvqcwg:-NtrfIxoCmAoofJH9h3I:belcasq) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Blocking merge so I can coordinate the Anzu upgrade at the same time.  There are couple hard-coded YCB paths there that will need fixing.
</blockquote></details>

OK Anzu PR 12211 passed.

___

**Pull request merged**
