### PR TITLE
Require that each subsystem of a Diagram has a unique name.

### LINKED ISSUE #3556: Require that all children of a Diagram have unique names.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes #3556.

@sherm1 for feature review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5866)

### CODE REVIEW

**Comment by david-german-tri** [comment]
Hey, this unearthed some tests that were in CMake only.  Cool!  Also, not cool.  Fixing now.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-KhxfB_rwmI1nK7QlTkY:b-62om8s)*

**Comment by david-german-tri** [comment]
> Hey, this unearthed some tests that were in CMake only.  Cool!  Also, not cool.  Fixing now.

Done.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-KhxgCR8_S22tjyUmvmm:b-1q5omy)*

**Comment by sherm1** [comment]
Nice, but would like to see the naming policy clearly stated in class comments, maybe for Diagram? I find I am somewhat unclear on the policy. Do all systems in a diagram have to have names now? I inferred that policy from the NamesAreUnique() method which treats "" as a name I think (so one unnamed system would be allowed but two would be illegal?). Better to lay out the policy explicitly so we can discuss. I don't think "" should be an allowable name -- we should either allow unnamed Systems and say that "" means "doesn't have a name", or disallow unnamed systems altogether, or provide unique default names?

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-KhxwJRVHcdTHnCylbKC:-KhxwJRVHcdTHnCylbKD:b-3ey54d) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L20)):*
> ```Python
>         "//drake/manipulation/models/iiwa_description:models",
>     ],
>     tags = ["snopt"],
> ```

BTW would you mind translating for my edification? What does `add_test_rule=1` mean and why did this need a "tags=snopt"?

---

*[drake/systems/framework/diagram.h, line 1262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-KhxxFbsnRnz2Ex6T8CY:-KhxxFbsnRnz2Ex6T8CZ:b-4mz3j8) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/systems/framework/diagram.h#L1262)):*
> ```objc
>   }
> 
>   // Returns true if every subsystem has a unique name.
> ```

BTW may want to point out the O(n log n) execution time.

---

*[drake/systems/framework/test/diagram_test.cc, line 1293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Khxywq-sHEMBOndedfi:-Khxywq-sHEMBOndedfj:br65x63) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/systems/framework/test/diagram_test.cc#L1293)):*
> ```cpp
>   adder1->set_name("unoriginal");
>   EXPECT_THROW(builder.Build(), std::runtime_error);
> }
> ```

BTW if the policy is that every system in a diagram must have a name, should have a test that unnamed systems are rejected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-KhxzJ2T5RABQq1mQ2ie:bgguixw)*

**Comment by david-german-tri** [comment]
Done - disallowed unnamed systems altogether, added comments, and fixed up a few more violators.

---

Review status: 4 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-KhxwJRVHcdTHnCylbKC:-Ki0PE1ZJKwMJIZIIrL7:bt0mzga) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW would you mind translating for my edification? What does `add_test_rule=1` mean and why did this need a "tags=snopt"?
</blockquote></details>

`drake_cc_binary` means "create an executable program".  `add_test_rule` means "also create a test that runs this program, and passes iff the program exits 0".  I disapprove of this form of "testing", but it's better than no test at all, and the CMake build was already doing it for this demo.

This demo will link without SNOPT, because MathematicalProgram will fall back to the no-op API, but it won't run successfully.  So, now that Bazel is trying to run it as a test, we also need to tell Bazel only to do that when SNOPT is enabled.  (This also was already happening on the CMake side.)

---

*[drake/systems/framework/diagram.h, line 1262 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-KhxxFbsnRnz2Ex6T8CY:-Ki0Q8BW08BFRuuhv3tf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/systems/framework/diagram.h#L1262)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW may want to point out the O(n log n) execution time.
</blockquote></details>

Done.

---

*[drake/systems/framework/test/diagram_test.cc, line 1293 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Khxywq-sHEMBOndedfi:-Ki0VvFxurqumRy8jAox:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/systems/framework/test/diagram_test.cc#L1293)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW if the policy is that every system in a diagram must have a name, should have a test that unnamed systems are rejected?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-Ki0QUk_G2iWE_q6-Wap:bx1dqj0)*

**Comment by sherm1** [comment]
Thanks, David! Just to double check -- this is just enforcing that *peer* subsystems have unique names so that subsystem *pathnames* are unique, right? Assuming that's correct, :lgtm:.

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-KhxwJRVHcdTHnCylbKC:-Ki0he_1XnnJZ3CZyc1I:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/6dd1d547a26529afdf4e5581ef5b4c0d7d6e911c/drake/examples/kuka_iiwa_arm/controlled_kuka/BUILD#L20)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

`drake_cc_binary` means "create an executable program".  `add_test_rule` means "also create a test that runs this program, and passes iff the program exits 0".  I disapprove of this form of "testing", but it's better than no test at all, and the CMake build was already doing it for this demo.

This demo will link without SNOPT, because MathematicalProgram will fall back to the no-op API, but it won't run successfully.  So, now that Bazel is trying to run it as a test, we also need to tell Bazel only to do that when SNOPT is enabled.  (This also was already happening on the CMake side.)
</blockquote></details>

Thanks!

---

*[drake/systems/framework/diagram.h, line 160 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Ki0khj1STSxmqpw2vtD:-Ki0khj1STSxmqpw2vtE:bhet1e5) ([raw file](https://github.com/robotlocomotion/drake/blob/7c53f7aa35c78e002f2181e9f5ba91149703cc51/drake/systems/framework/diagram.h#L160)):*
> ```objc
> /// Each System in the Diagram must have a unique, non-empty name.
> ///
> /// \tparam T The mathematical scalar type. Must be a valid Eigen scalar.
> ```

BTW `\` -> `@`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-Ki0iRIsL54it5hERZNk:b6lbgj9)*

**Comment by david-german-tri** [comment]
Yes, that's correct.  Thanks!  +@sammy-tri for platform review.

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/diagram.h, line 160 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Ki0khj1STSxmqpw2vtD:-Ki0v77hpvvnwxCQwOGJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7c53f7aa35c78e002f2181e9f5ba91149703cc51/drake/systems/framework/diagram.h#L160)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `\` -> `@`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-Ki0umUhVG597wW_FN2e:b-7ixf7b)*

**Comment by sammy-tri** [comment]
:lgtm: (pending open issues and CI)

---

Reviewed 4 of 7 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 1298 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Ki0wB8ZBbQ1hOyXWDiM:-Ki0wB8_4AKmEiqoIr0B:byq3izm) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc43f887caa7f7d6c8912326457db593979d0c1/drake/systems/framework/test/diagram_test.cc#L1298)):*
> ```cpp
> // name.
> GTEST_TEST(NonUniqueNamesTest, EmptyName) {
> DiagramBuilder<double> builder;
> ```

Should this be indented?  (possible reviewable is rendering it strangely for me)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-:-Ki0wfMcBwueGy00pRDi:bhlc148)*

**Comment by david-german-tri** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/diagram_test.cc, line 1298 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5866#-Ki0wB8ZBbQ1hOyXWDiM:-Ki1224A_r1o6WlC-OMW:b-l290g8) ([raw file](https://github.com/robotlocomotion/drake/blob/1dc43f887caa7f7d6c8912326457db593979d0c1/drake/systems/framework/test/diagram_test.cc#L1298)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this be indented?  (possible reviewable is rendering it strangely for me)
</blockquote></details>

Done.  (Argh, CLion 2016.3 is such a performance regression...it will _eventually_ grok big files like this, but until it does all of the autoformatting is disengaged.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5866)*

**Pull request merged**
