### PR TITLE
Modified compareParsers.m to use a hard-coded list of URDFs.

### PR DESCRIPTION
**Pull request by liangfok**
This is to avoid URDFs that it should not compare like those with world links.

Closes https://github.com/RobotLocomotion/drake/issues/2194
Closes https://github.com/RobotLocomotion/drake/issues/2175

Contributes to https://github.com/RobotLocomotion/drake/pull/2163 and https://github.com/RobotLocomotion/drake/pull/2171.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2221)

### CODE REVIEW

**Comment by liangfok** [comment]
Not really sure what happened to the mac and windows builds of [CI build 1135](https://drake-jenkins.csail.mit.edu/job/experimental/1135/). I assume the cpplint error is fixed in https://github.com/RobotLocomotion/drake/pull/2219. 

Going to fetch latest from master and re-run CI on this PR to see if the problems go away by themselves.

**Comment by jwnimmer-tri** [comment]
Yup, the mac and windows errors were CI randomly tipping over; nothing you can do but try again.

**Comment by liangfok** [comment]
[CI build 1141](https://drake-jenkins.csail.mit.edu/job/experimental/1141/) passed. Since this is a MATLAB

**Comment by liangfok** [comment]
This PR passed [CI Build 1141](https://drake-jenkins.csail.mit.edu/job/experimental/1141/) and is thus ready for final review / merge.

**Comment by RussTedrake** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/compareParsers.m, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2221#-KHC77yO-Bg9ApQjcMMf:-KHC77yPJy3Os0YPPw_Z:-341181676) ([raw file](https://github.com/robotlocomotion/drake/blob/1f8db45a2814443a5b0d022ccd690ca7b5323ecc/drake/systems/plants/test/compareParsers.m#L6)):*
i have commented on this issue.  i don't think that test is actually broken.  and I prefer having the inclusive test (otherwise, for instance, we wouldn't have even realized that this impacted the matlab parser as well)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2221)*

**Comment by RussTedrake** [comment]
i think we need to resolve #2194 and avoid this change.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2221#-:-KHC7baRBTSprU4vRAL6:-840370070)*

**Comment by jwnimmer-tri** [comment]
@liangfok in [a 2175 comment](https://github.com/RobotLocomotion/drake/issues/2175#issuecomment-214793800) I suggested a blacklist instead of whitelist, which I think would be a good mechanism to satisfy Russ while unblocking the other PRs.  You could blacklist just one or two models (possibly with TODOs of issues where they will be added back in to the testing), as a way to get the models into master and unblock #2163, but still promise to fix the parsing discrepancies in the near future.

**Comment by RussTedrake** [comment]
+1 to blacklisting.

**Comment by liangfok** [comment]
OK I will switch to black listing as soon as I figure out why my machine is failing on https://github.com/RobotLocomotion/drake/issues/2194.

**Comment by liangfok** [comment]
This PR will be superseded by https://github.com/RobotLocomotion/drake/pull/2356, which contains the initial blacklist. I will thus close this PR.

**Pull request closed without merging**
