### PR TITLE
Move detail::is_eigen_* into eigen_types.h and symbolic_expression.h

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This moves the trait operations, and adds unittests for basic Eigen matrix types.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6678)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.

(Let me know if you'd like these current trait helpers to only work with `MatrixBase<>`, rather than `MatrixBase<>` and `ArrayBase<>`).

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq3D_w5IGOAs_FOYyzn:b-bqysv1)*

**Comment by hongkai-dai** [comment]
:lgtm: I don't think we need to the trait helpers to work only with `MatrixBase<>` now. 
+@seancurtis-tri for platform review please.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq46gSOhhfG__IrjVR_:b-5ph3qj) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
> ```objc
>  */
> template <typename Derived, typename Scalar>
> struct is_eigen_matrix_of
> ```

BTW, how about calling this `is_eigen_flat_matrix_of`? Technically matrix is a superset of vectors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq47r3_XXISrh3wyjPg:b-wglayl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq4GFE5Fn00OdQnjdyU:b2g8k1h) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, how about calling this `is_eigen_flat_matrix_of`? Technically matrix is a superset of vectors.
</blockquote></details>

Hmm... I agree that the name should indicate that this wouldn't match to a vector.  However, can I ask what `flat` would mean in this context, or how that would better delineate the two (`vector` vs. `matrix` (`nonvector`))?

Perhaps `is_eigen_nonvector_of`? (though, this seems like it'd be fragile against a `Matrix1d` case)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq4JvSUj1e9lWR8n5Sb:b-lay0la) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Hmm... I agree that the name should indicate that this wouldn't match to a vector.  However, can I ask what `flat` would mean in this context, or how that would better delineate the two (`vector` vs. `matrix` (`nonvector`))?

Perhaps `is_eigen_nonvector_of`? (though, this seems like it'd be fragile against a `Matrix1d` case)
</blockquote></details>

That, or should this simply accept both matrices and vectors? (That would simplify things a tad)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq4KjfgkBU6f9xejGEz:bcm6qgj) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

That, or should this simply accept both matrices and vectors? (That would simplify things a tad)
</blockquote></details>

Ah, sorry, I should say `fat_matrix` instead of `flat_matrix`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by EricCousineau-TRI** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq4QoYap7j7r7ZR_jX7:b-m2qgbd) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ah, sorry, I should say `fat_matrix` instead of `flat_matrix`.
</blockquote></details>

Ah, that makes more sense!
I think that it would be simplest to have this accept both matrices and vectors. If you or Sean think it should exclude vectors, please let me know.
Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by hongkai-dai** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq4S-ijAep-D2ot6qxX:b-cz1ejb) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Ah, that makes more sense!
I think that it would be simplest to have this accept both matrices and vectors. If you or Sean think it should exclude vectors, please let me know.
Thanks!
</blockquote></details>

Yes, I agree, accepting both matrices and vectors makes more sense. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by SeanCurtis-TRI** [comment]
Somebody made the gods of CI angry. :LGTM: with some, I suspect, CLion induced indentation quirks.
+@soonho-tri for final review.

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/common/BUILD, line 510 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4miE3rLQ69cTwDnM_:-Kq4miE3rLQ69cTwDnMa:bmps8i2) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/BUILD#L510)):*
> ```Python
> 
> drake_cc_googletest(
>     name = "eigen_types_test",
> ```

BTW I would've expected to see this alphabetized. However, as I look at the whole file, I recognize that while there is a *trend* towards alphabetization, there is no definitive pattern. No defect.

---

*[drake/common/eigen_types.h, line 207 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nKcdCIxXYXlhXbpu:-Kq4nKcdCIxXYXlhXbpv:bly2fn4) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/eigen_types.h#L207)):*
> ```objc
>     : std::integral_constant<
>           bool, detail::is_eigen_scalar_same<Derived, Scalar>::value &&
>                     detail::is_eigen_vector<Derived>::value> {};
> ```

BTW Funny indentation?  Back four spaces? Should "detail" align with "detail"?

---

*[drake/common/symbolic_expression.h, line 911 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nvVutO2k_riqbVyX:-Kq4nvVutO2k_riqbVyY:b-6gto6w) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/symbolic_expression.h#L911)):*
> ```objc
>           bool,
>           detail::is_eigen_matrix_of<DerivedV, symbolic::Expression>::value &&
>               detail::is_eigen_matrix_of<DerivedB, double>::value> {};
> ```

BTW Bad indentation?  Clion likes doing that.

---

*[drake/common/symbolic_expression.h, line 922 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nyMbT5FZOAqej5Fv:-Kq4nyMbT5FZOAqej5Fw:b6khpr9) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/symbolic_expression.h#L922)):*
> ```objc
>           bool,
>           detail::is_eigen_vector_of<DerivedV, symbolic::Expression>::value &&
>               detail::is_eigen_vector_of<DerivedB, double>::value> {};
> ```

BTW Indentation.

---

*[drake/common/test/eigen_types_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4oOT29iPfo6jV_5lu:-Kq4oOT29iPfo6jV_5lv:bjqyvfb) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/test/eigen_types_test.cc#L24)):*
> ```cpp
> void CheckTraits(bool is_vector) {
>   std::string info = "Type: " + NiceTypeName::Get<Derived>() + "\n";
>   EXPECT_TRUE(detail::is_eigen_type<Derived>::value) << info;
> ```

BTW I'd forgotten this trick (with <<) thanks for the reminder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq4p5f_8LAR0Jjlurqo:bcocbrz)*

**Comment by soonho-tri** [comment]
Please allow me 2-3 hours to finish it. I hope the CI failures will be addressed before then.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq4pUrsKrx4isJJJmp_:b-96izvd)*

**Comment by soonho-tri** [comment]
Previously, it was not possible to satisfy both of `is_eigen_vector_of` and `is_eigen_matrix_of`. This PR changes the semantics of `is_eigen_matrix_of` to subsume `is_eigen_vector_of`. As a result, a compiler think that some function declarations are ambiguous. An example is `AddLinearEqualityConstraint` in `MathematicalProgram`.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq67-0yh2dH2QCz76ML:b-kdiiww)*

**Comment by soonho-tri** [comment]
Checkpoint (mainly replying to @seancurtis-tri 's comments). I'll do another round of review when the aforementioned problem is fixed.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/common/BUILD, line 510 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4miE3rLQ69cTwDnM_:-Kq68-33RdiPtT8rtEv7:bmbh1kj) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/BUILD#L510)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I would've expected to see this alphabetized. However, as I look at the whole file, I recognize that while there is a *trend* towards alphabetization, there is no definitive pattern. No defect.
</blockquote></details>

FYI, running `buildifer.sh` does not change this part of the file. I think it indicates that this is good to go.

---

*[drake/common/eigen_types.h, line 207 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nKcdCIxXYXlhXbpu:-Kq68I_d06ULkecJTsqn:bd0pfrb) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/eigen_types.h#L207)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Funny indentation?  Back four spaces? Should "detail" align with "detail"?
</blockquote></details>

FYI, this matches with the result from the `clang-format` in my machine.

However, I agree that it is not consistent with the formatting style in `is_eigen_vector` and `is_eigen_scalar_same` where `clang-format` suggests changes.

---

*[drake/common/symbolic_expression.h, line 911 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nvVutO2k_riqbVyX:-Kq69-RkD-OPCbBPM3ny:bim1oej) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/symbolic_expression.h#L911)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Bad indentation?  Clion likes doing that.
</blockquote></details>

FYI, META (this and the below), this is a fixed point of clang-format. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq69IHL_XR-Q3iuu-XC:b-gotkaz)*

**Comment by EricCousineau-TRI** [comment]
I believe I've fixed the CI issues due to the ambiguity. PTAL when  you have a chance. Thanks!

---

Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/eigen_types.h, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq46gSOhhfG__IrjVRZ:-Kq8nPmObxwf-WogtEMM:b-2qtj31) ([raw file](https://github.com/robotlocomotion/drake/blob/8b69320db38a0f895a26d15a20b142b5cdb62865/drake/common/eigen_types.h#L210)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes, I agree, accepting both matrices and vectors makes more sense. 
</blockquote></details>

Changed to `is_eigen_nonvector_of` to appease ambiguities. I prefer `nonvector` to `fat_matrix` as `vector` is already known and implies mutual exclusion. (Can change it if you like.)

---

*[drake/common/eigen_types.h, line 207 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nKcdCIxXYXlhXbpu:-Kq8oV42oN2gdT_VEDyF:buthwf2) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/eigen_types.h#L207)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this matches with the result from the `clang-format` in my machine.

However, I agree that it is not consistent with the formatting style in `is_eigen_vector` and `is_eigen_scalar_same` where `clang-format` suggests changes.
</blockquote></details>

Done. Accepted `clang-format` changes.

---

*[drake/common/symbolic_expression.h, line 911 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nvVutO2k_riqbVyX:-Kq8nvu621ain84dCWHv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/symbolic_expression.h#L911)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, META (this and the below), this is a fixed point of clang-format. 
</blockquote></details>

Done.

---

*[drake/common/symbolic_expression.h, line 922 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4nyMbT5FZOAqej5Fv:-Kq8o8CHFF7C_m7NszxK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/symbolic_expression.h#L922)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Indentation.
</blockquote></details>

Done.

---

*[drake/common/test/eigen_types_test.cc, line 24 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq4oOT29iPfo6jV_5lu:-Kq8oLeUr6DD4jWsIdfE:b-kbnish) ([raw file](https://github.com/robotlocomotion/drake/blob/ac9fdc3e454013441c215c879fb523ae842d389c/drake/common/test/eigen_types_test.cc#L24)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd forgotten this trick (with <<) thanks for the reminder.
</blockquote></details>

BTW Welcome!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq8oeeTI29OxirsGd2_:b-ki7boi)*

**Comment by hongkai-dai** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by soonho-tri** [comment]
Thanks for the patience. PTAL.

---

Reviewed 2 of 7 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/BUILD, line 510 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bX1yksYVcm0V2_-B:-Kq9bX1yksYVcm0V2_-C:b-ecda4) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/BUILD#L510)):*
> ```Python
> 
> drake_cc_googletest(
>     name = "eigen_types_test",
> ```

FYI, please consider adding this test on CMake side. 

---

*[drake/common/eigen_types.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9dQZ48MA2JdIwKCHj:-Kq9dQZ48MA2JdIwKCHk:byg3oeh) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L172)):*
> ```objc
> 
> 
> namespace detail {
> ```

BTW, I think we don't need to put them inside of `detail` namespace. What do you think? 

---

*[drake/common/eigen_types.h, line 175 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bkYpAtenJvSZHnHG:-Kq9bkYpAtenJvSZHnHH:b-pzojgl) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L175)):*
> ```objc
> 
> /*
>  * Determine if a type derived from EigenBase<> (e.g. ArrayBase<>,
> ```

BTW, META/nit, `Determine` -> `Determines` (other files as well).

---

*[drake/common/eigen_types.h, line 196 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bvTrsSBIduyhXpB9:-Kq9bvTrsSBIduyhXpBA:b-7vgw58) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L196)):*
> ```objc
> struct is_eigen_vector
>     : std::integral_constant<bool, detail::is_eigen_type<Derived>::value &&
>                                        Derived::ColsAtCompileTime == 1> {};
> ```

FYI, this excludes the dynamic case like the following:
```c++
Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic,> M(3, 1);
```
For now, `M` satisfies the condition for `is_eigen_nonvector_of`. I think we need to refine the documentation at least, or need to modify the design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-Kq9da6b6IeH_x17i9qH:bwc5aec)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/common/BUILD, line 510 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bX1yksYVcm0V2_-B:-KqEGNSpkztOKppcmt_X:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/BUILD#L510)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, please consider adding this test on CMake side. 
</blockquote></details>

Done.

---

*[drake/common/eigen_types.h, line 172 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9dQZ48MA2JdIwKCHj:-KqEGPd9rU3tb4DkV3C8:bb2003v) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L172)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think we don't need to put them inside of `detail` namespace. What do you think? 
</blockquote></details>

Done. I like that a lot more.

---

*[drake/common/eigen_types.h, line 175 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bkYpAtenJvSZHnHG:-KqEGR1HL91KWHJI7g1v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L175)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, META/nit, `Determine` -> `Determines` (other files as well).
</blockquote></details>

Done.

---

*[drake/common/eigen_types.h, line 196 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-Kq9bvTrsSBIduyhXpB9:-KqEGU57b7ueISrHefcc:bew28ii) ([raw file](https://github.com/robotlocomotion/drake/blob/229de2a82fad9c65724fe51d01f1d9b0ce9ee7d1/drake/common/eigen_types.h#L196)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

FYI, this excludes the dynamic case like the following:
```c++
Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic,> M(3, 1);
```
For now, `M` satisfies the condition for `is_eigen_nonvector_of`. I think we need to refine the documentation at least, or need to modify the design.
</blockquote></details>

Done. Added indication in dox that this is a compile-time check only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Comment by soonho-tri** [comment]
:lgtm: But we have CI failures.
```
...
undefined reference to `drake::NiceTypeName::Demangle[abi:cxx11](char const*)'
...
```
Could you check?

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-KqEIZU5jGfnquPDyL9O:b2vqice)*

**Comment by EricCousineau-TRI** [comment]
Forgot to link `drakeCommon`. Fixed. Thanks!

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678#-:-KqEJvdiXr6AwRaToxJF:b-qzffql)*

**Comment by soonho-tri** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6678)*

**Pull request merged**
