### PR TITLE
CI fix: Remove test from asan until its timeout issue is addressed.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14854)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(status: single reviewer ok) 
+@jwnimmer-tri for both reviews.

I will revisit this tomorrow for a better fix.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14854#-:-MXE5a9h-Qgd9qgR_9Mc:bbbyg48)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(priority: high)  :lgtm: both.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14854#-:-MXE61zh4fPuwsPYMu1s:bjye2fo)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
Needs a lint brush.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14854)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Comment by jwnimmer-tri** [comment]
For the record, this was a hotfix for #14840.

**Pull request merged**
