### PR TITLE
Change lcm package to "lcmdrake"

### PR DESCRIPTION
**Pull request by rdeits**
Currently, drake's lcm types live in the "drake" package. That's very sensible, but it creates some weird side effects for LCM's language bindings. Primarily, it means that the auto-generated Python bindings are created as a package named "drake". That means that we can't have, for example, an *actual* set of Python bindings for Drake itself using that name. 

This pull request renames the lcmtypes package to `lcmdrake`, which I chose because it's what the director is already using internally and because it's as good as anything else. 

We definitely don't *have* to merge this; it's not a critical fix. But I think we'll appreciate the clearer naming down the line. @patmarion I think you've wanted something like this for a while. Does this look good to you?

@RussTedrake before this gets merged, we'll have to merge in my 1-line change to the Director and stop pointing to my fork.

### CODE REVIEW

**Comment by patmarion** [comment]
Yep, seems reasonable to me, if folks are on board with the name change.

**Comment by RussTedrake** [comment]
the compiled library is drake_lcmtypes.a.   
the jar file is lcmtypes_drake.jar .
what were those pods guys thinking?  :)

rather than start yet another permutation of the name, i’d prefer to pick one of those (and possibly even change the other to conform).

and i would even consider making this change at the pods.cmake level?

**Comment by mauricefallon** [comment]
The standard library name is like this liblcmtypes_multisense.a and lcmtypes_multisense.jar
headers look like this:
include/lcmtypes/multisense_imu_t.h
include/lcmtypes/multisense/imu_t.hpp
... with multisense being the pod package name

@rdeits 's suggestion would break this typical lcm convention in favour the python bindings.
Is there no other way?

**Comment by patmarion** [comment]
Another option could be to just adjust the install rule for Python.  Install the python lcmtypes directory to lcmtypes/drake instead of just drake.  Then you could do imports like:


import lcmtypes.drake as lcmdrake

from lcmtypes.drake import lcmt_qp_controller_input

**Comment by rdeits** [comment]
@patmarion I like that suggestion. Working on it now.

**Pull request closed without merging**
