### PR TITLE
Get pick_and_place_scenario_1 to pass on mac

### LINKED ISSUE #6648: pick_and_place_scenario_1 times out on mac
See build: https://drake-jenkins.csail.mit.edu/job/mac-clang-bazel-nightly-everything-release/104/

I think there's actually a test failure which is only showing up on mac, and so we need to investigate further (as just increasing the timeout probably won't work).

### PR DESCRIPTION
**Pull request by sammy-tri**
Fixes #6648 

I'm not thrilled with how this "fix" turned out, because slight differences in the pose of the arm when the planner is called result in substantially different results (still) on mac vs ubuntu...  but it passes on both of them.

I think having the test enabled for future changes (which may hopefully mitigate the effect of slight changes in initial conditions) is worth it (though this change serves to highlight how iffy the current test is).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6700)

### CODE REVIEW

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-nightly-everything-release please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-Kq9gqxHtsDFeB7siSpG:b-ds0qnv)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-Kq9h7vKsnniwlBntQeX:b-7mwjtq)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-Kq9nC68ixMfDCt6zT3L:b-7mwjtq)*

**Comment by sammy-tri** [comment]
+@naveenoid for feature review

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KqA9cwb1vFRvT96VtY2:b-psw9ws)*

**Comment by naveenoid** [comment]
:lgtm: but I think the underlying problems need 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KqTLJgZeIAZkk7F2WXN:bza9wuk) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
> ```Python
>         # radically different results.  This value produces usable
>         # (but different!) results on Mac vs. Linux builds.
>         "--dt 6e-4",
> ```

BTW: This implies that the numerical integration for a given time period gives slightly diverging results on mac and linux - hence the differences in the queried IK initial conditions. If this is the case, isnt this more serious? We expect identical performances in each platform no? @siyuanfeng-tri : Any comments?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 91 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLix8Rv7R6Rhyei6X:-KqTLix9xN25hjdxugmT:b5q7pek) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L91)):*
> ```cpp
>   }
>   drake::log()->debug("result: {}", planner_result);
>   return planner_result;
> ```

BTW: I think we might need to do some matlab plots contrasting linux v mac performance. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KqTM1jjY-pkJtJ60JiZ:bqogtb)*

**Comment by naveenoid** [comment]
a issue to track. <sorry for a premature publish>

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KqTMPse7ikOeUpkVtDk:bi41192)*

**Comment by naveenoid** [comment]
*an <facepalm>

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KqTMYR387ekYFxtpVfB:b-3r0uwv)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KqTPR4kATPugL_9kuzw:b21fo5v) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: This implies that the numerical integration for a given time period gives slightly diverging results on mac and linux - hence the differences in the queried IK initial conditions. If this is the case, isnt this more serious? We expect identical performances in each platform no? @siyuanfeng-tri : Any comments?
</blockquote></details>

After f2f with @siyuanfeng-tri and @avalenzu it was agreed that the nominal pose for the IK query might need a fresh look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by siyuanfeng-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KqTQFQxaVnAfQc5KBNH:btlp5qk) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

After f2f with @siyuanfeng-tri and @avalenzu it was agreed that the nominal pose for the IK query might need a fresh look.
</blockquote></details>

let me hack it a bit. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by siyuanfeng-tri** [comment]
*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KqTV2jirjwO49nIM-xD:b5dx7l5) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

let me hack it a bit. 
</blockquote></details>

@sammy-tri can you try this? https://github.com/siyuanfeng-tri/drake/tree/fix/ik 
without the dt time hack for mac

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KrB_9TJ7QUMmg7KZfsV:b8d6ddy) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

@sammy-tri can you try this? https://github.com/siyuanfeng-tri/drake/tree/fix/ik 
without the dt time hack for mac

</blockquote></details>

I'm pretty sure a fixed nominal pose is not the answer we're looking for.  Particularly on the smaller moves (like pregrasp->grasp, lifting from pick, etc) using a fixed nominal pose (instead of the current post) makes the arm go through some unfortunate gyrations at the exact time we want smooth movements.  I've had good luck using a fixed nominal pose for large movements (moving to pregrasp, between the "lift from pick" and "approach place" positions, etc). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBa_qmZ_QwMW0YxTWq:b-7mwjtq)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBb0PzLUJg49lQW0c4:b-nmowns)*

**Comment by sammy-tri** [comment]
Opened #6811 to track simulation divergence across platforms

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBcehMkDgssdfVs0Fg:bz9o1wf)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBcl2Hzg3ikoGdzeon:b-nmowns)*

**Comment by sammy-tri** [comment]
+@EricCousineau-TRI for platform review of the non-dev portion

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBcsPSxuPdRGn1HV27:bnqiqdr)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, thanks!
+@soonho-tri for follow-up platform review of non-dev portion.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KrBmL68PSDJd-COa-jU:-KrBmL68PSDJd-COa-jV:bvc7cis) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c4779541a7b3704e1fcba4075af55982557f54/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L45)):*
> ```cpp
>                             ConstraintRelaxingIk* planner, IKResults* ik_res,
>                             std::vector<double>* times) {
>   DRAKE_DEMAND(duration > 0 && num_via_points >= 0);
> ```

BTW Should this demand that `planner`, `ik_res`, and `times` be non-null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBmPzWHreayaTEoaVO:b-793jw4)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by soonho-tri** [comment]
non-dev portion :lgtm: . Checked that `bazel test //drake/examples/kuka_iiwa_arm/...` works on a mac.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-:-KrBpYnGy60_yfwWu6Zl:b-3b62b7)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KrBmL68PSDJd-COa-jU:-KrBr1ZocbUHFlzHHYf1:b33ai0j) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c4779541a7b3704e1fcba4075af55982557f54/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Should this demand that `planner`, `ik_res`, and `times` be non-null?
</blockquote></details>

Probably, but it's a file-scope helper function which will fail in a pretty obvious way if those get messed up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KrBmL68PSDJd-COa-jU:-KrBrgptEE54DwC5mVH_:b-m92hue) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c4779541a7b3704e1fcba4075af55982557f54/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L45)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Probably, but it's a file-scope helper function which will fail in a pretty obvious way if those get messed up.
</blockquote></details>

I've been also more lenient with helper functions in anonymous namespaces. Probably, it's not so harmful to have `DRAKE_ASSERT`s here? I'd like to know if we have a general policy for this (i.e. too obvious vs. better-to-be-cautious-for-the-future).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD, line 76 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KqTLJgZeIAZkk7F2WXM:-KrCaIG3TzvWr9aDvged:b-k4f5wb) ([raw file](https://github.com/robotlocomotion/drake/blob/31a04b14a291327fb2a411949a83aacdb48bb081/drake/examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD#L76)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm pretty sure a fixed nominal pose is not the answer we're looking for.  Particularly on the smaller moves (like pregrasp->grasp, lifting from pick, etc) using a fixed nominal pose (instead of the current post) makes the arm go through some unfortunate gyrations at the exact time we want smooth movements.  I've had good luck using a fixed nominal pose for large movements (moving to pregrasp, between the "lift from pick" and "approach place" positions, etc). 
</blockquote></details>

@siyuanfeng-tri do you still want me to do anything here?  Or can we resolve this discussion?

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KrBmL68PSDJd-COa-jU:-KrCaP6BVKn9EoMDPb1a:bn1x7zt) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c4779541a7b3704e1fcba4075af55982557f54/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L45)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I've been also more lenient with helper functions in anonymous namespaces. Probably, it's not so harmful to have `DRAKE_ASSERT`s here? I'd like to know if we have a general policy for this (i.e. too obvious vs. better-to-be-cautious-for-the-future).
</blockquote></details>

@soonho-tri do you want me to put that change in for this PR?  Or should this discussion be resolved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc, line 45 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6700#-KrBmL68PSDJd-COa-jU:-KrCnRjYbgDlYfsOdLbw:b-ebdijr) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c4779541a7b3704e1fcba4075af55982557f54/drake/examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc#L45)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

@soonho-tri do you want me to put that change in for this PR?  Or should this discussion be resolved?
</blockquote></details>

Switched to satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6700)*

**Pull request merged**
