### PR TITLE
Kinematic constraints use MultibodyPlant<double>

### PR DESCRIPTION
**Pull request by avalenzu**
We initially hid the kinematic constraint classes because they were such heavy users of `MultibodyPlant<AutoDiffXd>`. This PR moves them over to use `MultibodyPlant<double>` and makes them visible.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10161)

### CODE REVIEW

**Comment by avalenzu** [comment]
___
*[multibody/inverse_kinematics/angle_between_vectors_constraint.cc, line 25 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10161#-LTceZlX9UMgDT3IZDe3:-LTcvEoq5vyVJoF5_u4-:bt940zv) ([raw file](https://github.com/robotlocomotion/drake/blob/0615332bb182519d90b86fe7c3763187bcc991e7/multibody/inverse_kinematics/angle_between_vectors_constraint.cc#L25)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, this is too late, right? We'll already be in trouble with `plant_(*plant)`. What's the right way to handle that, @seancurtis-tri ?

**Comment by avalenzu** [comment]
___
*[multibody/inverse_kinematics/angle_between_vectors_constraint.cc, line 25 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10161#-LTceZlX9UMgDT3IZDe3:-LTcvbiP7OHQl2gMmsaR:b-qgdato) ([raw file](https://github.com/robotlocomotion/drake/blob/0615332bb182519d90b86fe7c3763187bcc991e7/multibody/inverse_kinematics/angle_between_vectors_constraint.cc#L25)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The list of 1 & 2 weren't meant to be options; they were meant to be steps.
</blockquote></details>

Man, I can't read today.  I saw "change the type of `plant_`" and read "change the type of `plant`."

**Comment by avalenzu** [comment]
___
*[multibody/inverse_kinematics/angle_between_vectors_constraint.cc, line 25 at r4](https://reviewable.io/reviews/robotlocomotion/drake/10161#-LTceZlX9UMgDT3IZDe3:-LTcwq_n39tswbUm4YDL:bbibe0h) ([raw file](https://github.com/robotlocomotion/drake/blob/0615332bb182519d90b86fe7c3763187bcc991e7/multibody/inverse_kinematics/angle_between_vectors_constraint.cc#L25)):*
<details><summary><i>Previously, avalenzu (Andres Valenzuela) wrote…</i></summary><blockquote>

Man, I can't read today.  I saw "change the type of `plant_`" and read "change the type of `plant`."
</blockquote></details>

Actually even those steps aren't enough because of the call to `num_positions()` in the `Constraint` constructor.

**Comment by jwnimmer-tri** [comment]
___
*[multibody/inverse_kinematics/angle_between_vectors_constraint.h, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/10161#-LTZUT0l3mCGpWf2WnY_:-LTd1xjz9tc-tKx95JCc:b-6ant9r) ([raw file](https://github.com/robotlocomotion/drake/blob/364f262c313035e35a2ec315d1378e24fc0d3172/multibody/inverse_kinematics/angle_between_vectors_constraint.h#L53)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The problem we have is that `Constraint` tries to model the math equations `lower <= f(x) <= upper`, and `Constraint::Eval` takes in a vector of doubles as `x`, and outputs a vector of doubles as `f(x)`, as the API in https://github.com/RobotLocomotion/drake/blob/16a386ed4c591e0e2cb6d687cc74f996b28c7348/solvers/evaluator_base.h#L43-L44. Hence it doesn't allow us to pass in a `Context` to the Constraint::Eval` function.

One solution to this problem is to change the API of `Constraint` (or `EvaluatorBase`), so that it looks like
```C++
Eval(const Context& x, VectorXd* y) const;
```
This would cause a lot of change across Drake. @avalenzu, @jwnimmer-tri what do you think?
</blockquote></details>

I think that the Eval signature should not change, and that when we have Constraints such as this one that need more than just the `x`, that they should keep the extra info as member fields, similar to what is happening here.

The only question would be whether the Constraint should have its own private copy of the context (twinned from the one the user passes in), or if it is OK to write into the one the user passed in.  I'd have to study more of the PR to know whether the aliasing here is appropriate, but maybe my answer so far is good enough without that deep dive.  Does this help?

**Pull request merged**
