### PR TITLE
[pydrake] Bind RenderEngineGlParams

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This is replacing #14828 with an active branch intended to be merged.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16201)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16201)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", missing label for release notes

___
*[bindings/pydrake/geometry_py_render.cc, line 311 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16201#-MqWHAUDCAc4xA9h9NKZ:-MqWKvsR3y3QGizFB9h_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b16dac2b512acb320a642c0212fa6b6d3ba9e32b/bindings/pydrake/geometry_py_render.cc#L311)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

(A comment taken from the prior PR...)

These fields should appear in header-declaration order.
</blockquote></details>

Done.
___
*[bindings/pydrake/geometry_py_render.cc, line 320 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16201#-MqWHKamBobW2hhteUlW:-MqWKwUq0MtcuxFMFJRa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b16dac2b512acb320a642c0212fa6b6d3ba9e32b/bindings/pydrake/geometry_py_render.cc#L320)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

(A comment taken from the prior PR...)

The casting here is superfluous.
</blockquote></details>

Done.
___
*[bindings/pydrake/test/geometry_render_test.py, line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16201#-MqWH_FPAFSA2nlQc0KM:-MqWM2Tc9wP8-6qW0j5U:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b16dac2b512acb320a642c0212fa6b6d3ba9e32b/bindings/pydrake/test/geometry_render_test.py#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

(A comment taken from the prior PR...)

Testing for specific magic numbers here didn't sit will with Sherm.  Investigate more what's happening.
</blockquote></details>

Done.
___
*[bindings/pydrake/test/geometry_render_test.py, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16201#-MqWHjDG1qNIZIJOcX_2:-MqWM2-zDdCikXsuUfce:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b16dac2b512acb320a642c0212fa6b6d3ba9e32b/bindings/pydrake/test/geometry_render_test.py#L75)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

(A comment taken from the prior PR...)

Needs testing (and probably fixing) on macOS.  This will be null in that case.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule (next week), please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: X 2

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16201#-:-Mq_7X9H1SLwuOrKohSB:b4xyt23)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
