### PR TITLE
geometry:optimization: Add VPolytope isa ConvexSet

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, pretty please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-MdciqiF36cfocAd72lO:b-wl5p35)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by RussTedrake — COMMENTED** [review]
cc @tobiamarcucci 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-MdckdF5BFexrIH2RaWx:b-4fk4qb)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[geometry/optimization/vpolytope.cc, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdcuAR99pOs-zLcffO8:-MdcuAR99pOs-zLcffO9:b-jeudxc) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c6f3384face8fff5a642224d2b1cb97d4101e0/geometry/optimization/vpolytope.cc#L47)):*
> ```cpp
> VPolytope VPolytope::MakeBox(const Eigen::Ref<const VectorXd>& lb,
>                              const Eigen::Ref<const VectorXd>& ub) {
>   DRAKE_DEMAND(lb.size() == ub.size());
> ```

Do we require lb <= ub?
___
*[geometry/optimization/test/vpolytope_test.cc, line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdczVwp-2LBD8Fn-S-Y:-MdczVwp-2LBD8Fn-S-Z:b-qhn3vu) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c6f3384face8fff5a642224d2b1cb97d4101e0/geometry/optimization/test/vpolytope_test.cc#L42)):*
> ```cpp
> 
>   const Eigen::Vector2d center = triangle.rowwise().mean();
>   const double kTol = 1e-12;  // 1e-12 worked for Mosek.
> ```

This tolerance depends on the solver. For CLP we probably don't have such high precision.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308)* status: 2 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[geometry/optimization/vpolytope.cc, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdcuAR99pOs-zLcffO8:-MddQlP60gNs2-AArmka:b-vn2hs1) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c6f3384face8fff5a642224d2b1cb97d4101e0/geometry/optimization/vpolytope.cc#L47)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do we require lb <= ub?
</blockquote></details>

Done.  Though ironically I don't think that check exists in the Constraint class?  (I looked there to remember the spelling for the .array() call)  :-)
___
*[geometry/optimization/test/vpolytope_test.cc, line 42 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdczVwp-2LBD8Fn-S-Y:-Mdd_LdDC-f4rIa7cJtZ:b-1ax64m) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c6f3384face8fff5a642224d2b1cb97d4101e0/geometry/optimization/test/vpolytope_test.cc#L42)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This tolerance depends on the solver. For CLP we probably don't have such high precision.
</blockquote></details>

Done.  Yes, I forgot to test CLP before pushing, but I've done it now.  Gurobi was actually quite sloppy at first, but rounding the solution fixed that.

**Review by hongkai-dai — COMMENTED** [review]
+@soonho-tri for platform review please, thanks!

> Reviewed 1 of 5 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-MddrGlqDg9a8lQmSCVJ:balbw5e)* status: LGTM missing from assignees hongkai-dai,soonho-tri(platform) (waiting on @soonho-tri)

___
*[geometry/optimization/vpolytope.cc, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdcuAR99pOs-zLcffO8:-MddqhHh9ad1ZqayO7Pm:b-2i6y9e) ([raw file](https://github.com/robotlocomotion/drake/blob/e4c6f3384face8fff5a642224d2b1cb97d4101e0/geometry/optimization/vpolytope.cc#L47)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  Though ironically I don't think that check exists in the Constraint class?  (I looked there to remember the spelling for the .array() call)  :-)
</blockquote></details>

Yeah you are right, constraint class doesn't have it. The solver will terminates immediately and report input error when the upper bound is less than the lower bound. 

I can add that check to Constraint class.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-MdeG0dWBLpdWNAOsedH:bg7igkv)* status: LGTM missing from assignee soonho-tri(platform) (waiting on @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-Mdj3UQgDV9cd1WBz8pf:bnfp4nl)* status: 4 unresolved discussions (waiting on @RussTedrake)

___
*[geometry/optimization/vpolytope.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivlpFE5EXsABgGRca:-MdivlpFE5EXsABgGRcb:b-dbjecw) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L49)):*
> ```cpp
>   DRAKE_DEMAND(lb.size() == ub.size());
>   DRAKE_DEMAND((lb.array() <= ub.array()).all());
>   const int n = lb.size();
> ```

nit, `int` => `Eigen::Index` or `auto`
___
*[geometry/optimization/vpolytope.cc, line 51 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivzumAI1jxWgGyegA:-MdivzumAI1jxWgGyegB:b-hyr61r) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L51)):*
> ```cpp
>   const int n = lb.size();
>   // Create all 2^n vertices.
>   MatrixXd vertices = lb.replicate(1, std::pow(2, n));
> ```

`std::pow(2, n)` returns a double value, which will be converted to `Eigen::Index`. To avoid loss of precision, it's better to write `static_cast<Eigen::Index>(1) << n`.
We also need to make sure than `n` is small enough to avoid overflow.

```c++
DRAKE_DEMAND(n <= static_cast<Eigen::Index>(sizeof(Eigen::Index)) * 8 - 2);
```
(or `DRAKE_THROW_UNLESS`)
___
*[geometry/optimization/vpolytope.cc, line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-Mdj1x-E6_MJ6Gqoi43n:-Mdj1x-E6_MJ6Gqoi43o:b7aqpx9) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L52)):*
> ```cpp
>   // Create all 2^n vertices.
>   MatrixXd vertices = lb.replicate(1, std::pow(2, n));
>   for (unsigned int i = 1; i < vertices.cols(); ++i) {
> ```

nit, `unsigned int` => `Eigen::Index`
___
*[geometry/optimization/vpolytope.cc, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-Mdj1zQk2vvxSqi_LeXE:-Mdj1zQk2vvxSqi_LeXF:b-jzsxr2) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L53)):*
> ```cpp
>   MatrixXd vertices = lb.replicate(1, std::pow(2, n));
>   for (unsigned int i = 1; i < vertices.cols(); ++i) {
>     for (int j = 0; j < n; j++) {
> ```

nit, `int` => `Eigen::Index`

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308)* status: 2 unresolved discussions (waiting on @hongkai-dai and @soonho-tri)

___
*[geometry/optimization/vpolytope.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivlpFE5EXsABgGRca:-Mdl06rqEWSQu7ohoedq:bxz9anp) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L49)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `int` => `Eigen::Index` or `auto`
</blockquote></details>

I think int is strongly preferred here?  (certainly it is by me). 
https://drake.mit.edu/styleguide/cppguide.html#Integer_Types
___
*[geometry/optimization/vpolytope.cc, line 51 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivzumAI1jxWgGyegA:-Mdl10W4C2FROZOK4NmK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L51)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`std::pow(2, n)` returns a double value, which will be converted to `Eigen::Index`. To avoid loss of precision, it's better to write `static_cast<Eigen::Index>(1) << n`.
We also need to make sure than `n` is small enough to avoid overflow.

```c++
DRAKE_DEMAND(n <= static_cast<Eigen::Index>(sizeof(Eigen::Index)) * 8 - 2);
```
(or `DRAKE_THROW_UNLESS`)
</blockquote></details>

Done.
___
*[geometry/optimization/vpolytope.cc, line 52 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-Mdj1x-E6_MJ6Gqoi43n:-Mdl18AWCba4pjY1MDNU:b-svp3zk) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L52)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

nit, `unsigned int` => `Eigen::Index`
</blockquote></details>

Done. (to int)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15308#-:-MdlMxItByUMDZ-XdzaS:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees soonho-tri(platform),hongkai-dai (waiting on @RussTedrake)

___
*[geometry/optimization/vpolytope.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivlpFE5EXsABgGRca:-MdlLlESDokaw8hTK7AW:bst3xtm) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L49)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think int is strongly preferred here?  (certainly it is by me). 
https://drake.mit.edu/styleguide/cppguide.html#Integer_Types
</blockquote></details>

OK.

I think this is something I need to discuss with platform-reviewers in the next meeting.
 - There are many `Eigen` functions returning a `Eigen::Index` value.
 - Note that `Eigen::Index` is `long` in a modern Mac / Intel PC (e.g. `puget`).
 - `long` => `int` is narrow-conversion which can cause loss of precision.
 - In practice, we don't handle a large matrix whose size is > INT_MAX (e.g. `2147483647`). So I think this is just OK?

**Comment by RussTedrake** [comment]
___
*[geometry/optimization/vpolytope.cc, line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15308#-MdivlpFE5EXsABgGRca:-MdlS8u40y4Mg8igeBQd:bdips12) ([raw file](https://github.com/robotlocomotion/drake/blob/c9181e17e7cc858b36cc8be6fffb88abfbd12198/geometry/optimization/vpolytope.cc#L49)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK.

I think this is something I need to discuss with platform-reviewers in the next meeting.
 - There are many `Eigen` functions returning a `Eigen::Index` value.
 - Note that `Eigen::Index` is `long` in a modern Mac / Intel PC (e.g. `puget`).
 - `long` => `int` is narrow-conversion which can cause loss of precision.
 - In practice, we don't handle a large matrix whose size is > INT_MAX (e.g. `2147483647`). So I think this is just OK?

</blockquote></details>

Happy to discuss (and revise this if we agree on the right solution).

**Pull request merged**
