### PR TITLE
Four Bar Linkage example

### PR DESCRIPTION
**Pull request by joemasterjohn**
Adds a four bar linkage example program to `examples/multibody/four_bar`. Comes with two different four bar SDFs and some command line options to turn off and on several features. Demonstrates how to use the `LinearBushingRollPitchYaw` `ForceElement` to weld two links together and approximate a closed loop kinematic chain.
//cc @amcastro-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13036)

### CODE REVIEW

**Comment by sherm1** [comment]
@mitiguy, @joemasterjohn is the plan to have the pdf be part of the Drake example? If so I'd like to see it more Drake-ified. At least it should be using World frame W rather than "N", but also the frame symbols seem confusingly divorced from the link names, e.g. "C" is the Rocker frame, not Crank or Coupler.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/13036#-M57THkCAQi9CVFGIaVX:-M59CIt7CQs6-RxrZE12:b-jsoakq) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

@sherm1, I forget, what are the guidelines (any?) to upload pdfs into Drake? is it ok to push these binaries? is size something to consider? any other tips?
</blockquote></details>

Any binary data in git needs a clear recipe for someone to edit and regenerate the data.  Otherwise is it unmaintainable.  So even if we commit a nicely-rendered PDF, we still need to commit the source format used to design it.

The PDF looks like TeX maybe?  I think we can have that natively in Doxygen, without committing a PDF in the first place.

---

**Comment by amcastro-tri** [comment]
How to change gflags default values: https://gflags.github.io/gflags/#default

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/four_bar/BUILD.bazel, line 30 at r12](https://reviewable.io/reviews/robotlocomotion/drake/13036#-M5Sj6_kDMEUVXR9_L8d:-M5T3YQa01xrfKI23t8v:b6lvc3v) ([raw file](https://github.com/robotlocomotion/drake/blob/2facb269956f694259f8e3a1aea09911ac820428/examples/multibody/four_bar/BUILD.bazel#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: tree is internal and shouldn't be listed here
</blockquote></details>

That's not correct.  There are include statements `#include "drake/multibody/tree/linear_bushing_roll_pitch_yaw.h"`.  The tree class is internal, but the whole package is not internal.

**Comment by jwnimmer-tri** [comment]
___
*[examples/multibody/four_bar/BUILD.bazel, line 30 at r12](https://reviewable.io/reviews/robotlocomotion/drake/13036#-M5Sj6_kDMEUVXR9_L8d:-M5TfXeF9EXxqjO8RJ53:b-dp0vkm) ([raw file](https://github.com/robotlocomotion/drake/blob/2facb269956f694259f8e3a1aea09911ac820428/examples/multibody/four_bar/BUILD.bazel#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Oh rats. That code is definitely in the wrong place. The code builds fine without the explicit `//multibody/tree` here (since `//multibody/plant` picks it up). Do you (@jwnimmer-tri) think it is better to list it here?
</blockquote></details>

"The code builds fine even without this line in deps" is not a valid formula for a defect.  The only related valid defect is "we list foo in the deps but never actually use any code from foo".

We should allow people to list items in `deps` that they are also `#include`ing  from in their source files.

**Comment by sherm1** [comment]
:clap: Congratulations, @joemasterjohn !
And thanks to @DamrongGuoy @mitiguy @amcastro-tri.

We now have a beautiful example of using a bushing to create a closed-topology mechanism.
(`examples/multibody/four_bar` in case you are interested in playing with it)

**Pull request merged**
