### PR TITLE
Remove PODS Makefile

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Remove the top-level Makefile that was included for PODS compatibility. Users of drake should build drake as a 'typical' CMake project.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2809)

### CODE REVIEW

**Comment by jhoare** [comment]
Should remove drake/Makefile as well. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809#-:-KMeyGxIZEpZ5GtHKbIU:325060814)*

**Comment by liangfok** [comment]
I believe this comment prevents us from removing `drake-distro/drake/Makefile`: https://github.com/RobotLocomotion/drake/issues/2484#issuecomment-232419100

Basically, to support downstream users who are currently using Drake as a POD within their project.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809#-:-KMeyZm-Y4amhMMhlazK:-275510741)*

**Comment by david-german-tri** [comment]
Hold on.  We definitely need to preserve the ability for downstream projects to use Drake as a POD.  Based on #2484, my understanding was that `Makefile` is not necessary for that purpose, but `drake/Makefile` is.  Why do you say the top-level Makefile is "for PODS compatibility"?

**Comment by jhoare** [comment]
My mistake, ignore my previous comment, don't remove drake/Makefile. Sorry everyone!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809#-:-KMez91nK-LU1mG3LWdC:-1825101316)*

**Comment by david-german-tri** [comment]
@jhoare thanks for clarifying!  My question to @mwoehlke-kitware still applies, though.

**Comment by jhoare** [comment]
@david-german-tri the root level Makefile was the pod-build entry point into building the superbuild with pods. I believe thats what @mwoehlke-kitware is referring to. 

Along the line of de-podsing the superbuild, does ``addpath_pods.m`` still have a purpose in life or should it be removed along with this Makefile?  The comment here: https://github.com/RobotLocomotion/drake/issues/2768#issuecomment-231619250 says it should not be used, so if true, should be removed with the same motivation as removing the superbuild pods Makefile.

**Comment by mwoehlke-kitware** [comment]
The top-level Makefile allows the Drake *superbuild* to be built "as a POD". The `drake/Makefile` allows *Drake itself* to be built "as a POD". The comments in #2484 suggest that folks care about the latter, but not as much the former.

**Comment by david-german-tri** [comment]
OK, thanks.  @RussTedrake, @wxmerkt says that OpenHumanoids has no need of superbuild-as-POD.  Are there any other consumers we should worry about?

**Comment by jwnimmer-tri** [comment]
If we decide to go ahead with this, it definitely needs a `CHANGELOG.md` entry.

**Comment by mwoehlke-kitware** [comment]
Is anyone maintaining (i.e. in an independent repository) a generic `Makefile` for wrapping a CMake project "as a POD"? It might be nice to mention that in a changelog entry.

**Comment by david-german-tri** [comment]
> Are there any other consumers we should worry about?

I got a verbal "no" from @RussTedrake, so I think there's nothing blocking this, but I'll leave it to Russ to LGTM and merge.

**Comment by david-german-tri** [comment]
> Is anyone maintaining (i.e. in an independent repository) a generic Makefile for wrapping a CMake project "as a POD"? It might be nice to mention that in a changelog entry.

There's [the PODs repository on sourceforge](https://sourceforge.net/p/pods/svn/HEAD/tree/).

**Comment by RussTedrake** [comment]
Our makefiles started from those but have matured considerably at this point

**Comment by RussTedrake** [comment]
apart from needing the changelog entry, it looks good to me.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809#-:-KMvY2QeVaeJ_tluj4a0:-356287675)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809)*

**Comment by mwoehlke-kitware** [comment]
>> There's [the PODs repository on sourceforge](https://sourceforge.net/p/pods/svn/HEAD/tree/).
>
> Our `Makefile`s started from those but have matured considerably at this point.

Maybe we should update upstream, then?

**Comment by RussTedrake** [comment]
nobody has touched the PODS website in years and years.

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2809#-:-KMyknGJhpWyQ6iyPfN1:1417088721)*

**Comment by ashuang** [comment]
Hi all,

Yes, I wouldn't worry about pods upstream. For context, that was something that Abe Bacharch and I did a while ago to make it easier for folks (students, research groups, etc.) to more easily exchange software modules, and I think it succeeded in that respect. If you're building a large complex repo there are probably a hundred better ways to do your build systems. It's also not something that we maintain or really even support anymore, as both of us work on different types of software now.

**Pull request merged**
