### PR TITLE
[workspace] Add reusable macro and documentation for vendor_cxx

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Update `@yaml_cpp_internal` to follow the new style.

For use in #17229 and #17230 and more afterwards.  (Those serve as more examples of this macro.)

Towards #17231.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17278)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.  Low priority.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17278)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17278#-:-N3Qcm6ECBgesoY8s0_W:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17278#-:-N3R0FQT2iFdqZmCgvwP:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
