### PR TITLE
Fix compilation errors when HAVE_SPDLOG is unset

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3012)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@ggould-tri for feature review, please.

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3012#-:-KO5ee8dw02_jlMrBvSh:1417088721)*

**Comment by jwnimmer-tri** [comment]
@sherm1 for platform review and merge, please.

**Comment by jwnimmer-tri** [comment]
(Using DMN tag solely to await second review.)

**Comment by sherm1** [comment]
Platform: :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3012#-:-KO6OK1e8AuXdoy-XCRo:-1446635318)*

**Pull request merged**
