### PR TITLE
Update dd and sdd dual cone constraints  to use sparse matrices

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-:-NgywSdMC6P8ME_5mIK-:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@xuchenhan-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-:-Nh0ThEiAih8AzbkwJoJ:bq10k5o)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.cc` line 1207 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh0U5iD24y6LV29MCMd:-Nh0U5iD24y6LV29MCMe:b-qnonic) ([raw file](https://github.com/RobotLocomotion/drake/blob/9de81b43d674b99c602194814426612e8ad41f80/solvers/mathematical_program.cc#L1207)):*
> ```cpp
>   // the A matrix using this triplet list.
>   std::vector<Eigen::Triplet<double>> A_triplet_list;
>   A_triplet_list.reserve(n * n);
> ```

BTW, I counted 4 * n * n - 3*n nonzero entries in A_triplet_list.

In
```
for (int i = 0; i < n; ++i) {
    // Variable Xᵢᵢ is in position i*(n+1)
    A_triplet_list.emplace_back(i, compute_flat_index(i, i), 1);
  }
```
we have `n` non-zero entries.

In 
```cc
for (int j = 0; j < n; ++j) {
    for (int k = j + 1; k < n; ++k) {
      // X(k, k) + X(k, j) + X(j, k) + X(j, j)
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, j), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, j), 1);
      ++row_ctr;

      // X(k, k) - X(k, j) - X(j, k) + X(j, j)
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, j), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, k), -1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, j), -1);
      ++row_ctr;
    }
  }
```
Each of the inner loop inserts 8 entries, and we run the inner loop for nchoosek(n, 2) = n * (n-1) / 2 times. 

So in total we have 8 * n * (n-1)/2 + n = 4 * n * n-3 * n nonzero entries.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.cc` line 1207 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh0U5iD24y6LV29MCMd:-Nh2DKkuEBwDPb0U8ebM:b-vxk7n) ([raw file](https://github.com/RobotLocomotion/drake/blob/9de81b43d674b99c602194814426612e8ad41f80/solvers/mathematical_program.cc#L1207)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I counted 4*n*n - 3*n nonzero entries in A_triplet_list.

In
```
for (int i = 0; i < n; ++i) {
    // Variable Xᵢᵢ is in position i*(n+1)
    A_triplet_list.emplace_back(i, compute_flat_index(i, i), 1);
  }
```
we have `n` non-zero entries.

In 
```cc
for (int j = 0; j < n; ++j) {
    for (int k = j + 1; k < n; ++k) {
      // X(k, k) + X(k, j) + X(j, k) + X(j, j)
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, j), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, j), 1);
      ++row_ctr;

      // X(k, k) - X(k, j) - X(j, k) + X(j, j)
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, k), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, j), 1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(j, k), -1);
      A_triplet_list.emplace_back(row_ctr, compute_flat_index(k, j), -1);
      ++row_ctr;
    }
  }
```
Each of the inner loop inserts 8 entries, and we run the inner loop for nchoosek(n, 2) = n * (n-1) / 2 times. 

So in total we have 8 * n * (n-1)/2 + n = 4*n*n-3*n nonzero entries.
</blockquote></details>

Good catch. I also added a test to be sure that the size of the linear constraint output is correct and that the constructed matrix is sparse.

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: 
+(release notes: none) 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-:-Nh2mNkn9HF_u3O7-neF:b-4u7a8u)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

___
*[`solvers/mathematical_program.cc` line 1244 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2hdZ_2LnO2yeiV036:-Nh2hdZ_2LnO2yeiV037:b-cyj3h5) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1244)):*
> ```cpp
>   }
>   DRAKE_ASSERT(row_ctr == n * n);
>   DRAKE_ASSERT(static_cast<int>(A_triplet_list.size()) == 4 * n * n - 3 * n);
> ```

FYI, we now have the c++20 ssize so you don't need to cast all the time.



_Suggestion:_
```cpp
ssize(A_triplet_list)
```
___
*[`solvers/mathematical_program.cc` line 1247 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2jH_M0_o7eYBwvMTk:-Nh2jH_N-SCevX8NlEaA:b-u6fey7) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1247)):*
> ```cpp
>   Eigen::SparseMatrix<double> A(row_ctr, n * n);
>   A.setFromTriplets(A_triplet_list.begin(), A_triplet_list.end());
>   return std::make_tuple(A, lb, ub);
> ```

BTW, if A is large enough so that using sparse algebra is worth-while, you might consider moving it instead of copying it.



_Suggestion:_
```cpp
return std::make_tuple(std::move(A), lb, ub);
```
___
*[`solvers/mathematical_program.cc` line 1267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2kW9wBpfPpHRmUC-3:-Nh2kW9wBpfPpHRmUC-4:b-o5syb9) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1267)):*
> ```cpp
>           ConstructPositiveDiagonallyDominantDualConeConstraintMatricesForN(n)};
>   return AddLinearConstraint(
>       (std::get<0>(constraint_mats) * A_expr).sparseView(),  // A * A_expr
> ```

BTW, I don't know about the underlying math, but want to make sure the result of this sparse dense multiplication is still indeed sparse.



_Code quote:_
```cpp
(std::get<0>(constraint_mats) * A_expr).sparseView()
```

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`solvers/mathematical_program.cc` line 1267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2kW9wBpfPpHRmUC-3:-Nh2ngk-41fj8r9a0rvY:b-acv864) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1267)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I don't know about the underlying math, but want to make sure the result of this sparse dense multiplication is still indeed sparse.
</blockquote></details>

This one is tricky here. `DecomposeAffineExpresion` returns a dense matrix. For simple expressions this makes sense, but for large matrices of expressions, this may or may not be a good design pattern. Since `A_expr` is already dense, it is faster to make this `sparse * dense` product return a `dense` and view it as sparse rather than trying to decide whether it makes sense to convert `A_expr` to sparse.

FYI: the tests ensure that the return of `AddDiagonallyDominantDualConeConstraint` is a `LinearConstraint` which only has a sparse matrix constructed (i.e. the dense matrix is not constructed until it is accessed).

**Review by AlexandreAmice — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-:-Nh2xXuX-F_WD3Uf1s3I:bm9o57a)* status: 1 unresolved discussion

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)* status: 1 unresolved discussion

___
*[`solvers/mathematical_program.cc` line 1267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2kW9wBpfPpHRmUC-3:-Nh2y9sB9cGBCqzlnkyJ:b-5dqpdq) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1267)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This one is tricky here. `DecomposeAffineExpresion` returns a dense matrix. For simple expressions this makes sense, but for large matrices of expressions, this may or may not be a good design pattern. Since `A_expr` is already dense, it is faster to make this `sparse * dense` product return a `dense` and view it as sparse rather than trying to decide whether it makes sense to convert `A_expr` to sparse.

FYI: the tests ensure that the return of `AddDiagonallyDominantDualConeConstraint` is a `LinearConstraint` which only has a sparse matrix constructed (i.e. the dense matrix is not constructed until it is accessed).
</blockquote></details>

I'm not following. If the result of the product is dense, why don't we just call the dense version of AddLinearConstraint like before?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20379)* status: 1 unresolved discussion

___
*[`solvers/mathematical_program.cc` line 1267 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20379#-Nh2kW9wBpfPpHRmUC-3:-Nh31xwu3i3xWlqYjMQM:blwbxl8) ([raw file](https://github.com/RobotLocomotion/drake/blob/2fb3530aa64f1d7ec7450d0348a6998912f68212/solvers/mathematical_program.cc#L1267)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not following. If the result of the product is dense, why don't we just call the dense version of AddLinearConstraint like before?
</blockquote></details>

The result of the product is a dense which I cast to sparse as I expect it to typically be sparse.

**Comment by xuchenhan-tri** [comment]
**@drake-jenkins-bot** linux-focal-gcc-cmake-experimental-release please.

**Pull request merged**
