### PR TITLE
[cmake] Remove buggy color and verbosity support

### LINKED ISSUE #19092: [cmake] Use of CMAKE_{COLOR,VERBOSE}_MAKEFILE invalid
Surfaced in #19023.

Drake is using unofficial generator-specific entry points to determine the underlying `bazel` command behavior.  As a result, the default behavior between drake's CMake when run using the `Unix Makefiles` generator and any other generator (e.g., `Ninja`) is inconsistent.

- When makefile is used, the defaults are: `color=yes`, `subcommands=no`.
- Any other generator: `color=no`, `subcommands=no`.

One option is to just make them official entry points, `option(CMAKE_VERBOSE_MAKEFILE ...)`.  A slightly better option:

```cmake
set(drake_color_default ON)
if(DEFINED CMAKE_COLOR_MAKEFILE)
  set(drake_color_default "${CMAKE_COLOR_MAKEFILE}")
endif()
option(DRAKE_BUILD_COLOR
  "Enable/Disable color output during build." "${drake_color_default}"
)

set(drake_verbose_default OFF)
if(DEFINED CMAKE_VERBOSE_MAKEFILE)
  set(drake_verbose_default "${CMAKE_VERBOSE_MAKEFILE}")
endif()
option(DRAKE_BUILD_VERBOSE
  "Enable/Disable verbose (bazel subcommands) build output." "${drake_verbose_default}"
)
```

This isn't a bug with CMake, this is a bug with how drake is leaning on certain CMake variables.  And how `if(SOME_VARIABLE_NOT_DEFINED_YET)` behaves to always be falsey, plus the fact that these variables are not defined by default for anything other than the makefile generator.

CC @jwnimmer-tri @mwoehlke-kitware

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19092.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22110)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review or delegation, please.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22110#-:-OBRzG4q3P6fHtYAWGKM:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule (tomorrow), please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22110#-:-OBSAn1m0uEDebNZWfXF:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),BetsyMcPhail

**Pull request merged**
