### PR TITLE
Prerequisites for Drake Gym:  Import OpenAI Gym; fake-vendor stable_b…

### PR DESCRIPTION
**Pull request by ggould-tri**
…aselines3

 * This is a preparatory PR for adding "Drake Gym" (Tools for using Drake to build OpenAI Gym environment classes).
 * OpenAI Gym is imported in order to gain access to its superclasses and test suite.
 * stable_baselines3 is pseudo-vendored to get its tests without the dependencies not exercised by thoses tests.
   * The resulting SB3 installation is fairly useless, but sb3's dependency tree is much larger than Drake itself and so not really appropriate to depend on; users who want SB3 should maintain their own SB3 installation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
FWIW, I'm on-call today, so platform will need to be someone else.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440#-:-NJBZIIL4RAIWmkw-yCf:b-142etq)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

___
*[`tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18440#-NJBYnHDDtQdFx59FlJ5:-NJBYnHE1AYdeFnPviqK:b-yznw37) ([raw file](https://github.com/robotlocomotion/drake/blob/e5de384a4116acfb2c0d8a7eca78104d9ba103f3/tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py#L7)):*
> ```Python
>     """Test that the methods that we use in drake are able to be loaded
>     in spite of Drake not having all of SB3's dependencies."""
>     def import_test():
> ```

This test is malformed, and therefore doesn't run. The test method needs a signature that starts with `test` and has `self` as a parameter.

Having fixed this for myself locally, I get:

```
rico@puget-161804-10:~/checkout/drake$ bazel test //tools/workspace/stable_baselines3_internal/...
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 test targets...
FAIL: //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test (see /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test/test.log)
INFO: From Testing //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test:
==================== Test output for //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test:

Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.006s]: test_import (stable_baselines3_internal_test.StableBaselines3InternalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/drake/tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py", line 8, in test_import
    from stable_baselines3.common.env_checker import check_env
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/a2c/a2c.py", line 3, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)

Generating XML reports...
================================================================================
INFO: Elapsed time: 0.408s, Critical Path: 0.28s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test FAILED in 0.2s
  /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

h/t to `kcov` python coverage for pointing all of this out.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @rpoyner-tri)

___
*[`tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py` line 7 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18440#-NJBYnHDDtQdFx59FlJ5:-NJlVXm28EFx7dZ5DQhE:bxhx8fm) ([raw file](https://github.com/robotlocomotion/drake/blob/e5de384a4116acfb2c0d8a7eca78104d9ba103f3/tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py#L7)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

This test is malformed, and therefore doesn't run. The test method needs a signature that starts with `test` and has `self` as a parameter.

Having fixed this for myself locally, I get:

```
rico@puget-161804-10:~/checkout/drake$ bazel test //tools/workspace/stable_baselines3_internal/...
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 test targets...
FAIL: //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test (see /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test/test.log)
INFO: From Testing //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test:
==================== Test output for //tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test:

Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.006s]: test_import (stable_baselines3_internal_test.StableBaselines3InternalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/drake/tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py", line 8, in test_import
    from stable_baselines3.common.env_checker import check_env
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/sandbox/linux-sandbox/31/execroot/drake/bazel-out/k8-opt/bin/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test.runfiles/stable_baselines3_internal/stable_baselines3/a2c/a2c.py", line 3, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)

Generating XML reports...
================================================================================
INFO: Elapsed time: 0.408s, Critical Path: 0.28s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//tools/workspace/stable_baselines3_internal:py/stable_baselines3_internal_test FAILED in 0.2s
  /home/rico/.cache/bazel/_bazel_rico/7f8997f28c9253517a55d673c67a6c74/execroot/drake/bazel-out/k8-opt/testlogs/tools/workspace/stable_baselines3_internal/py/stable_baselines3_internal_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

h/t to `kcov` python coverage for pointing all of this out.
</blockquote></details>

Huh, I'd been wondering how he got this passing without my other diffs.  Guess I know now.
Anyway, restored my other diffs, making this review a little harder and more annoying.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440#-:-NJlmLbl8yiP1W69KOxT:bnfp4nl)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
+@sherm1 for platform review if you have the time; feel free to leave it for next year's reviewer if you like.
+(priority: medium)
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440#-:-NJq8mJ1B3bFSFWJ-Wf_:bjv9fku)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Everything looks fine as far as I can tell, which isn't very far! Platform :lgtm:

> Reviewed 7 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18440#-:-NJqZh9WD913mKdFjDOb:b8d0xc6)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @ggould-tri)

**Comment by jwnimmer-tri** [comment]
Adding new dependencies is release-notable +(release notes: fix).

**Pull request merged**
