### PR TITLE
Deprecate robotlocomotion_lcmtypes and bot2_core_lcmtypes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Port existing Drake code to use the new types.

Add helper header `drake/systems/sensors/robotlocomotion_compat.h` to alias the old names onto the new names, along with a deprecation warning.

Requires #14885 first.  Towards #14362.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @RussTedrake on inbound change coming next week -- `robotlocomotion.image_t` and `robotlocomotion.image_array_t` will be renamed to `drake.lcmt_image` and `drake.lcmt_image_array`, alongside all of our usual Drake LCM message types.  The manipulation_station uses these messages for its cameras.

The deprecation affordances here were enough to pass all Anzu CI tests, and I didn't immediately see anything in the underactuated or manipulation repositories that used these messages.  But possibly you'd like to check this over.

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-snopt-packaging please in case you need binaries to test on.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: with one small and impractical misgiving below.

> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884#-:-MY5E4sP0szvPFE0tX0J:b-cb5kk2)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[lcmtypes/BUILD.bazel, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY5Df3-5yL5Wy8_s4tM:-MY5Df3-5yL5Wy8_s4tN:b-naobnp) ([raw file](https://github.com/robotlocomotion/drake/blob/0dba39ab915f992528f6632b981efbe6a87e5313/lcmtypes/BUILD.bazel#L74)):*
> ```Starlark
> drake_lcm_cc_library(
>     name = "header",
>     lcm_package = "drake",
> ```

minor:  This seems to me to violate the spirit of the namespace/directory rule ("The code in that namespace should usually be in a directory whose basename matches the namespace name") but not the letter of it ("... or in a subdirectory thereof" which would seem to argue that the bare drake namespace is always appropriate).

This is probably too much of a pain to deal with anyway.  Author's discretion.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[lcmtypes/BUILD.bazel, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY5Df3-5yL5Wy8_s4tM:-MY5O8XB1rbNE6qrrAMZ:b-6e4r2w) ([raw file](https://github.com/robotlocomotion/drake/blob/0dba39ab915f992528f6632b981efbe6a87e5313/lcmtypes/BUILD.bazel#L74)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This seems to me to violate the spirit of the namespace/directory rule ("The code in that namespace should usually be in a directory whose basename matches the namespace name") but not the letter of it ("... or in a subdirectory thereof" which would seem to argue that the bare drake namespace is always appropriate).

This is probably too much of a pain to deal with anyway.  Author's discretion.
</blockquote></details>

OK Fixing the packaging and include paths is part of the #14362 scope already, but will happen later.

**Comment by jwnimmer-tri** [comment]
Tagging +@ggould-tri officially for feature review.

+@EricCousineau-TRI for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[lcmtypes/BUILD.bazel, line 74 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY5Df3-5yL5Wy8_s4tM:-MY5PFHI9SfB13gGeGzV:bb6mt9b) ([raw file](https://github.com/robotlocomotion/drake/blob/0dba39ab915f992528f6632b981efbe6a87e5313/lcmtypes/BUILD.bazel#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Fixing the packaging and include paths is part of the #14362 scope already, but will happen later.
</blockquote></details>

:+1:

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with two minor nits.

> Reviewed 26 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884#-:-MY6oqBfB6T1Yf3_Naip:b-5gjdkm)* status: 2 unresolved discussions (waiting on @jwnimmer-tri)

___
*[systems/sensors/BUILD.bazel, line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6o91Q1xXUffMc3GTc:-MY6o91REN6QE1WRVKyQ:b-6vdr5) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/BUILD.bazel#L120)):*
> ```Starlark
> # TODO(jwnimmer-tri) This header assists with the deprecation of the
> # @lcmtypes_robotlocomotion repository; remove it on or after 2021-08-01.
> drake_cc_library(
> ```

nit This is presently public (per default visibility).

Can you make this private?
___
*[systems/sensors/robotlocomotion_compat.h, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6obbu7O1hb7y6XppN:-MY6obbu7O1hb7y6XppO:bcfk2oc) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/robotlocomotion_compat.h#L20)):*
> ```objc
> namespace robotlocomotion {
> 
> using header_t DRAKE_DEPRECATED("2021-08-01",
> ```

nit From brief inspection, not sure if I see these aliases tested.

Consider adding minor unittest, e.g. `static_assert(std::is_same_v<robotlocomotion::header_t, drake::lcmt_header>, "")`, etc.?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @ggould-tri)

___
*[systems/sensors/BUILD.bazel, line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6o91Q1xXUffMc3GTc:-MY6s_veDyku2eP_BXGj:b9mwk3e) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/BUILD.bazel#L120)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is presently public (per default visibility).

Can you make this private?
</blockquote></details>

I think it should be public.  Anyone who wants to ease their transition to the new spellings would want to `#include` this?
___
*[systems/sensors/robotlocomotion_compat.h, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6obbu7O1hb7y6XppN:-MY6syOC29EKoIhhD6Au:bv32hf5) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/robotlocomotion_compat.h#L20)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit From brief inspection, not sure if I see these aliases tested.

Consider adding minor unittest, e.g. `static_assert(std::is_same_v<robotlocomotion::header_t, drake::lcmt_header>, "")`, etc.?
</blockquote></details>

Done.

That particular test is useless -- the compiler already catches those kind of errors.  Instead, I forked one of the unit tests from prior to this PR, checking that it still passes (with the only change being that the `#include "robotlocomotion/..."` line has to be removed.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 32 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[systems/sensors/BUILD.bazel, line 120 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6o91Q1xXUffMc3GTc:-MY74s-g0UMI4ROt6o1z:b-qyscl9) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/BUILD.bazel#L120)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it should be public.  Anyone who wants to ease their transition to the new spellings would want to `#include` this?
</blockquote></details>

OK SGTM!

FWIW Would have been clearer w/ explicit `visibility` tag and comment but meh for now.
___
*[systems/sensors/robotlocomotion_compat.h, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6obbu7O1hb7y6XppN:-MY752Cf2v0E3up5PC-d:b-3xrdj9) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/robotlocomotion_compat.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

That particular test is useless -- the compiler already catches those kind of errors.  Instead, I forked one of the unit tests from prior to this PR, checking that it still passes (with the only change being that the `#include "robotlocomotion/..."` line has to be removed.
</blockquote></details>

OK Works for me! (not 100% on board with "useless", but I'm like 70% on board w/ it)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14884)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

___
*[systems/sensors/robotlocomotion_compat.h, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6obbu7O1hb7y6XppN:-MY784xg7MiveabMZaHp:b61vdar) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/robotlocomotion_compat.h#L20)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Works for me! (not 100% on board with "useless", but I'm like 70% on board w/ it)
</blockquote></details>

I could not imagine an implementation error that such a test would find, but would otherwise go undetected.

**Comment by EricCousineau-TRI** [comment]
___
*[systems/sensors/robotlocomotion_compat.h, line 20 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14884#-MY6obbu7O1hb7y6XppN:-MY78UPVEpAmtTCWBnUv:b-hgv5x4) ([raw file](https://github.com/robotlocomotion/drake/blob/126c14924487fd788704a5d32e54a1031d0cdb1a/systems/sensors/robotlocomotion_compat.h#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I could not imagine an implementation error that such a test would find, but would otherwise go undetected.
</blockquote></details>

Could ensure that it's an alias to the right type (non-error typo).
True, should be caught via code review, but add'l active check.

**Pull request merged**
