### PR TITLE
Add FAQ for fixing OpenGL / VTK errors when using `bazel test`. Use `local = 1` for select tests.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per [this discussion](https://github.com/RobotLocomotion/drake/pull/6903#issuecomment-328120368) in #6903, some machines may encounter driver related issues when running OpenGL / VTK applications under `bazel test`.

This PR will add documentation to the FAQ, and updates the tests accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7004)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@sammy-tri for platform review, please.

\cc @jwnimmer-tri 

(I am presently running `bazel test //...` on my system to see if there are any other related failures.)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-:-KtqBh9sSwUtz57UDJq6:bhz1m4z)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/faq.rst, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqD-7pmf06aDdDuq20:-KtqD-7pmf06aDdDuq21:b-wehkjw) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L206)):*
> ```reStructuredText
> ================================================================================
> 
> Symptom: While the binary works with ``bazel run``, when you I running a test using ``bazel teset``, such as::
> ```

 when you I running -> when you run

tesest -> test

---

*[drake/doc/faq.rst, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqDEvaTSBDfQraz5Af:-KtqDEvaTSBDfQraz5Ag:b42t6ng) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L210)):*
> ```reStructuredText
>     $ bazel test //drake/systems/sensors:rgbd_camera_test
> 
> I encounter a slew of errors from VTK / OpenGL::
> ```

I -> you

---

*[drake/doc/faq.rst, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqDKxyX-rV8Z1Nzb8f:-KtqDKxyX-rV8Z1Nzb8g:b-8aipkz) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L236)):*
> ```reStructuredText
>     )
> 
> If this does not work, then please try running the test in bazel without sandboxing::
> ```

Bazel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-:-KtqDbiX8vDdMVSz0p1W:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/doc/faq.rst, line 206 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqD-7pmf06aDdDuq20:-KtqQ97bKyJvBUShAPw_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L206)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

 when you I running -> when you run

tesest -> test
</blockquote></details>

Done.

---

*[drake/doc/faq.rst, line 210 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqDEvaTSBDfQraz5Af:-KtqQCUES6TY84j5GCU5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L210)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I -> you
</blockquote></details>

Done.

---

*[drake/doc/faq.rst, line 236 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqDKxyX-rV8Z1Nzb8f:-KtqQC0cQNIXyyqe9mqJ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fd30a3aa0bb3f3413d9606d1a135f1084e38cbd2/drake/doc/faq.rst#L236)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Bazel
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004)*

**Comment by sammy-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/doc/faq.rst, line 232 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqSj2WEhyXvawQY2C-:-KtqSj2XJQb4SKM9xL1k:b-w7fuy9) ([raw file](https://github.com/robotlocomotion/drake/blob/a49824c6bad31663fd7a6177c207f0522996db82/drake/doc/faq.rst#L232)):*
> ```reStructuredText
>             ":test_models",
>         ],
>         local = 1,  # This line should make it work.
> ```

It would be nice if there was a brief explanation of what this flag does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004)*

**Comment by EricCousineau-TRI** [comment]
Tests completed, no other failures related to this. (Just some small timeouts on some of the optimization-based unittests.)

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/faq.rst, line 232 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-KtqSj2WEhyXvawQY2C-:-KtqnOb5isJan8W-S1FW:b-ul712j) ([raw file](https://github.com/robotlocomotion/drake/blob/a49824c6bad31663fd7a6177c207f0522996db82/drake/doc/faq.rst#L232)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It would be nice if there was a brief explanation of what this flag does.
</blockquote></details>

Niceness added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-:-KtqngjNH98Q-JmQ6MMx:b4t6006)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7004#-:-Ktr6chPjUPAVPEBt0OL:bnfp4nl)*

**Pull request merged**
