### PR TITLE
[Bazel] Add systems/analysis/test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
If these were in Bazel, we would have found #4323 earlier.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4324)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Another #4034 flake.
@drake-jenkins-bot linux-clang-ninja-experimental-open-source please

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4324#-:-KXsWAzXPQbOQ3dETm_G:bnfp4nl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by david-german-tri** [comment]
https://drake-jenkins.csail.mit.edu/view/Bazel/job/linux-xenial-gcc-bazel-experimental/8 passes

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4324#-:-KXup6rbbYKcr4zPBDJR:bnfp4nl)*

**Pull request merged**
