### PR TITLE
Implements Eval() methods in MBP to avoid boilerplate

### PR DESCRIPTION
**Pull request by amcastro-tri**
To avoid boilerplate code like this:
```
TODO(my name!): Eval() this from context.
PositionKinematics<T> pc(model_->topology());
model_->CalcPositionKinematics(context, &pc);
```
all over the place, I introduce `Eval()` methods that place the boilerplate in a singe central location.
Per suggestion [here](https://reviewable.io/reviews/robotlocomotion/drake/7947#-L4OY0liwjNpp-j4SYnD).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7973)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@sherm1 for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4hDV2ICziGMS-8GyDS:b-ec6d43)*

**Comment by sherm1** [comment]
Beautiful -- one BTW suggestion. :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-L4lF1Q0UJg1THlLOIlr:-L4lF1Q0UJg1THlLOIls:b-jykmdt) ([raw file](https://github.com/robotlocomotion/drake/blob/07d7eacfb94dd5306515f0d964cbe94bd35a4b4c/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L141)):*
> ```cpp
>   static never_destroyed<VelocityKinematicsCache<T>> vc(model_->get_topology());
>   model_->CalcPositionKinematicsCache(context, &pc.access());
>   model_->CalcVelocityKinematicsCache(context, pc.access(), &vc.access());
> ```

BTW couldn't you just write:
```c++
model_->CalcVelocityKinematicsCache(context, EvalPositionKinematics(context), &vc.access());
```
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4lFHzuUiJKUYu93e1k:btwnbvn)*

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel: function-local statics that hold memory for instance method return values are an astoundingly bad and brittle idea.  Don't do this!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4lFahyJdF8EQCQFGVu:bokvplm)*

**Comment by sherm1** [comment]
@jwnimmer-tri this is just a temporary hack so that Alejandro can localize his cache workaround in one place. It is not that different in concept from having the real cache in the context -- that also has the "brief lifetime" problem for the return value. References to the return value must not be held in either case.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4lJ9lRqDVHDKd2pDAU:b-pruk2k)*

**Comment by jwnimmer-tri** [comment]
I get that its a hack.  What would be so bad about having these as member fields instead of statics though?  That lifetime seems long enough, and substantially less brittle.

**Comment by amcastro-tri** [comment]
> What would be so bad about having these as member fields instead of statics though?

Not a real bad thing but, having them as `never_destroyed` helps to neatly localize this temporary solution to a single spot.

Also, I don't understand your concern. The reason I took this approach is because I've seen it in use in Drake in non-temporary solutions (yes, most cases are returns to static methods, but not all).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4lTKBV5sFAhELjReCp:b-c03qri)*

**Comment by sherm1** [comment]
I agree that mutable member fields would be fine and accomplish the same end. Ah, I was only thinking about the normal caching brittleness (don't hold references into the cache). Are you thinking about there being multiple MultibodyPlants extant simultaneously with overlapping computations? Members would at least provide separate data for each. There would still be the usual caching cautions but at least different plants couldn't stomp on each other's statics.

**Comment by jwnimmer-tri** [comment]
@sherm1 precisely correct.

@amcastro-tri The problem comes if you have >1 instance of an MBP, as Sherm notes.  If you see other places in Drake then either (1) they are broken and we should fix them (please point them out to me), or (2) they differ from this PR in a meaningful way (e.g., they are read-only constants, never-modified).

**Comment by amcastro-tri** [comment]
I see the concern, thanks. I will then change to a mutable member.

Regarding your question. I only see methods returning constants as you mention.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4lX780cSCVyHde3mQ5:b-n4fjun)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7973#-:-L4ljK8L1nYDQWqyimH5:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Better now, thanks!

**Pull request merged**
