### PR TITLE
Mosek uses imposes linear or rotated quadratic constraint for small-size LMI constraints.

### PR DESCRIPTION
**Pull request by hongkai-dai**
For LMI on a 1x1 matrix, we impose linear inequality constraint. For LMI on a 2x2 matrix, we impose a rotated quadratic constraint (rotated Lorentz cone constraint)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-:-OCW3KPf4Z2q1IzGsep2:bgvexs6)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: 3 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/mosek_solver_internal.h` line 651 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYoQsuA-soR8VvqJ8R:-OCYoQsv6tYkmXJpglul:bpb54yv) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.h#L651)):*
> ```objc
>         const double tmp = dual_sol(1);
>         dual_sol(1) = dual_sol(2) / 2;
>         dual_sol(2) = tmp;
> ```

I find this inconsistent reshuffling a bit confusing. I would introduce the mapping 
```
[y0, y1] -> [y0, y2, y1*sqrt(2)]
[y1, y2]
```
this being in mosek's rotated lorentz cone is the condition
```
2*y0*y2 >=  2 * y1**2 
```
which is the determinant condition and this is just a reshuffling of the standard PSD matrix vectorization.

Then denote the dual solution of Mosek's rotated second order cone as
```
[z0, z2, z1]
```
which makes it clear that under the inverse mapping, to preserve the inner product we must have
```
[z0, z2, z1] -> [z0, z1/sqrt(2)]
                       [z1/sqrt(2), z2]
```
This makes everything symmetric and much more similar to the normal case.



_Suggestion:_
```objc
        // We impose the LMI constraint as a rotated Quadratic cone constraint
        // in Mosek. For a constraint that
        // [y0 y1]
        // [y1 y2]
        // is in psd, this is equivalent to
        // [y0/2, y2, y1] in Mosek's rotated quadratic cone.
        // If we denote the dual solution of the Mosek's rotated quadratic cone
        // as [z0, z1, z2], then by the duality theory, that the complementary
        // slackness (namely the inner product between the primal and the dual)
        // should be the same for both the PSD cone and the rotated quadratic
        // cone, hence the dual solution for the PSD constraint is
        // [z0/2 z2/2]
        // [z2/2   z1]
        // We store the lower triangular part of the dual PSD matrix as the dual
        // solution, namely [z0/2, z2/2, z1]
        dual_sol(0) *= 0.5;
        const double tmp = dual_sol(1);
        dual_sol(1) = dual_sol(2) / 2;
        dual_sol(2) = tmp;  
```
___
*[`solvers/mosek_solver_internal.cc` line 969 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYrQDC5ZDQteQfwOkX:-OCYrQDC5ZDQteQfwOkY:b-fi5rbz) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.cc#L969)):*
> ```cpp
>       A.setFromTriplets(A_triplets.begin(), A_triplets.end());
>       MSKdomaintypee domain_type =
>           matrix_rows == 1 ? MSK_DOMAIN_RPLUS : MSK_DOMAIN_SVEC_PSD_CONE;
> ```

It might be nice to hard-code the 1x1 case similar to the 2x2 case. It would help the reader separate the three cases more easily.



_Code quote:_
```cpp
      MSKdomaintypee domain_type =
          matrix_rows == 1 ? MSK_DOMAIN_RPLUS : MSK_DOMAIN_SVEC_PSD_CONE;
```
___
*[`solvers/mosek_solver_internal.cc` line 981 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYrNKc-6dW6v34tvOK:-OCYrNKc-6dW6v34tvOL:b-kz7sf9) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.cc#L981)):*
> ```cpp
>       // [y1, y2]
>       // We impose it as a rotated Lorentz cone constraint, namely
>       // [y0/2, y2, y1] is in Mosek's rotated Quadratic cone.
> ```

see discussion on the dual solution.



_Code quote:_
```cpp
      // For PSD constraint on a 2x2 matrix
      // [y0, y1] = F0 + F1*x0 + ... + Fk*xk
      // [y1, y2]
      // We impose it as a rotated Lorentz cone constraint, namely
      // [y0/2, y2, y1] is in Mosek's rotated Quadratic cone.
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: 3 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/mosek_solver_internal.h` line 651 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYoQsuA-soR8VvqJ8R:-OCZvMhb74uzYC13jDHB:b-dv8qgc) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.h#L651)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I find this inconsistent reshuffling a bit confusing. I would introduce the mapping 
```
[y0, y1] -> [y0, y2, y1*sqrt(2)]
[y1, y2]
```
this being in mosek's rotated lorentz cone is the condition
```
2*y0*y2 >=  2 * y1**2 
```
which is the determinant condition and this is just a reshuffling of the standard PSD matrix vectorization.

Then denote the dual solution of Mosek's rotated second order cone as
```
[z0, z2, z1]
```
which makes it clear that under the inverse mapping, to preserve the inner product we must have
```
[z0, z2, z1] -> [z0, z1/sqrt(2)]
                       [z1/sqrt(2), z2]
```
This makes everything symmetric and much more similar to the normal case.
</blockquote></details>

I agree scaling y2 by sqrt(2) is aesthetically better (it is symmetric).

On the other hand, all the rotated Lorentz cone constraint in MosekSolver is parsed by scaling y0 with a factor of 0.5. To stay consistent with all the other code in side this same file, I think we should do scaling of 0.5 on y0 here as well.

We could have a separate PR to change the scaling for all rotated Lorentz cone constraint. 
___
*[`solvers/mosek_solver_internal.cc` line 981 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYrNKc-6dW6v34tvOK:-OCZw94J8eBDLm_lmW_1:b-qz2p8v) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.cc#L981)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

see discussion on the dual solution.
</blockquote></details>

Done. Ditto

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-:-OCaH6w77bk5L1WajUOu:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`solvers/mosek_solver_internal.h` line 651 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCYoQsuA-soR8VvqJ8R:-OCaHHrB3fnV29uK2gfn:b-vusvm5) ([raw file](https://github.com/RobotLocomotion/drake/blob/d32a5d96734e13ec3812e119b4577639ffd0aa08/solvers/mosek_solver_internal.h#L651)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I agree scaling y2 by sqrt(2) is aesthetically better (it is symmetric).

On the other hand, all the rotated Lorentz cone constraint in MosekSolver is parsed by scaling y0 with a factor of 0.5. To stay consistent with all the other code in side this same file, I think we should do scaling of 0.5 on y0 here as well.

We could have a separate PR to change the scaling for all rotated Lorentz cone constraint.
</blockquote></details>

Very well. I would still adjust the labeling in the comment so that it appears as [z0 z2 z1]

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by hongkai-dai — COMMENTED** [review]
+@ggould-tri for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-:-OCdO_v5EEvPMGcK3ztz:b-2hj6f6)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCdXbk8D0yuN6lgrykQ:-OCdXbk8D0yuN6lgrykR:b-qk8486) (no related file):*
I was not able to find test coverage of these matrix sizes, although I may have been looking in the wrong place.  Can you clarify where the test coverage is?
___
*[`solvers/mosek_solver_internal.h` line 645 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCdWCtm1mhBg7UxgTwf:-OCdWCtm1mhBg7UxgTwg:b-v7uj1k) ([raw file](https://github.com/RobotLocomotion/drake/blob/dce1ea596e3377b76b7e7dc2686e98854ff92b05/solvers/mosek_solver_internal.h#L645)):*
> ```objc
>         // cone, hence the dual solution for the PSD constraint is
>         // [z0/2 z1/2]
>         // [z1/2   z2]
> ```

typo I think there's a grammatical error, in that the "that" I have removed here has no antecedent.



_Suggestion:_
```objc
        // If we denote the dual solution of the Mosek's rotated quadratic cone
        // as [z0, z2, z1], then by the duality theory, the complementary
        // slackness (namely the inner product between the primal and the dual)
        // should be the same for both the PSD cone and the rotated quadratic
        // cone, hence the dual solution for the PSD constraint is
        // [z0/2 z1/2]
        // [z1/2   z2]
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCdXbk8D0yuN6lgrykQ:-OCd_XOcCEzm1mAn4N7j:bea0dzj) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I was not able to find test coverage of these matrix sizes, although I may have been looking in the wrong place.  Can you clarify where the test coverage is?
</blockquote></details>

They are tested in https://github.com/RobotLocomotion/drake/blob/f01b6939f78db845b68d0f8114bb9f67193ccfa0/solvers/test/mosek_solver_test.cc#L557-L569

Previously these program were parsed with Mosek's PSD cone, now we parse them with positive or rotated quadratic cone, which are more efficient.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-OCdXbk8D0yuN6lgrykQ:-OCdaXlm3IKlZL_y81Uu:bqnqad7) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

They are tested in https://github.com/RobotLocomotion/drake/blob/f01b6939f78db845b68d0f8114bb9f67193ccfa0/solvers/test/mosek_solver_test.cc#L557-L569

Previously these program were parsed with Mosek's PSD cone, now we parse them with positive or rotated quadratic cone, which are more efficient.
</blockquote></details>

Perfect; thank you!
(I was looking in the solver _internal_test.cc ; oops.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/22238#-:-OCe2tEuA5A5nZ80P-aN:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice

**Pull request merged**
