### PR TITLE
Work around Xcode gfortran issues

### PR DESCRIPTION
**Pull request by jamiesnape**
With the Xcode generator, I have only ever been able to compile Fortran code using the Intel compiler.

To test:
```
mkdir build && cd build && cmake -GXcode ..
```
(on a mac, of course)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4273)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware and +@RussTedrake for feature review and +@david-german-tri for platform review.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 176 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4273#-KXgXOvPw2iqUC6AqxA6:-KXgXOvPw2iqUC6AqxA7:b-og2xb4) ([raw file](https://github.com/robotlocomotion/drake/blob/5743e532b0c0556ee9f974ea7d5a84783047686e/cmake/config.cmake#L176)):*
> ```CMake
>       enable_language(Fortran)
> 
>       if(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU" AND CMAKE_Fortran_COMPILER_VERSION VERSION_LESS "4.9")
> ```

BTW, not really this PR's fault, but shouldn't finding the Fortran compiler manually also check the version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4273#-:-KXgXaMmAF6riypR19St:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/config.cmake, line 176 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4273#-KXgXOvPw2iqUC6AqxA6:-KXgXlgEGOHLKVjY-W02:bkplju1) ([raw file](https://github.com/robotlocomotion/drake/blob/5743e532b0c0556ee9f974ea7d5a84783047686e/cmake/config.cmake#L176)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

BTW, not really this PR's fault, but shouldn't finding the Fortran compiler manually also check the version?
</blockquote></details>

BTW, ideally, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4273)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by RussTedrake** [comment]
:LGTM:  tested locally, and it gets through configure and build (at least I'm into drake now).  Thanks!

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4273#-:-KXh27oiOvWBlY7vB_gk:bnfp4nl)*

**Pull request merged**
