### PR TITLE
Run buildifier

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The weekly tidy, preempting Monday since its a holiday.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5220)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@soonho-tri 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5220#-:-KdDf-ipJAz06BjbtvMt:b-v3eqt6)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5220#-:-KdDf1ZXFDrShwdpzDih:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm: as not requiring platform review, per convention.

**Comment by liangfok** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5220)*

**Pull request merged**
