### PR TITLE
[workspace] Upgrade drake_models to latest commit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/RobotLocomotion/models/pull/64

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21310)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for both reviews per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21310#-:-NvbRS7p9g-eGoBZcnud:bnfp4nl)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21310)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21310#-NvbBI16CWVrBPSkSITR:-NvbSMbV1jWbCkrZ6bRA:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/8cc3f78e1895116ac11883041ffa9b85f27e80aa/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs real sha from master.
</blockquote></details>

Done

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21310)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee ggould-tri(platform)

**Pull request merged**
