### PR TITLE
Improve the documentation for mathematicalprogram doxygen.

### PR DESCRIPTION
**Pull request by hongkai-dai**
From Slack conversation https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1626898485086100?thread_ts=1626896625.081800&cid=C3L92BM2Q
Screenshot from 2021-07-26 12-37-43

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for both reviews please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467#-:-MfJhIc847aCmlAlTRbM:ba7uda8)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
https://github.com/hongkai-dai/drake/pull/24 shows more along the lines of what I was thinking.

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM so far.

Once you and I are satisfied with the PR, I think we should edit some screenshots into PR overview (for easier preview) and then ask Russ to have a look.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467#-:-MfK-Q2-1u7DIpfLaMhH:b-9dtud1)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15467#-MfJzItdBwHeJmPV0Z_P:-MfJzItdBwHeJmPV0Z_Q:by0vxbo) ([raw file](https://github.com/robotlocomotion/drake/blob/90f06db2c75fb2dadbb3bfc8dfc1bbcee0b62fde/solvers/mathematical_program_doxygen.h#L129)):*
> ```objc
>  *     <td></td>
>  *     <td></td>
>  * </tr>
> ```

I am interested why NLopt is not listed here after Ipopt in the Convex Optimization table?

We seem to have an NLopt unit test for convex QP, and its supported program attributes seem to admit both QP and LP, so ChooseBestSolver might choose it.

Maybe you intent to change it soon so that it's not chosen anymore?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program_doxygen.h, line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15467#-MfJzItdBwHeJmPV0Z_P:-MfYoFYPEo17vOSjOfIB:b-p8i2ap) ([raw file](https://github.com/robotlocomotion/drake/blob/90f06db2c75fb2dadbb3bfc8dfc1bbcee0b62fde/solvers/mathematical_program_doxygen.h#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I am interested why NLopt is not listed here after Ipopt in the Convex Optimization table?

We seem to have an NLopt unit test for convex QP, and its supported program attributes seem to admit both QP and LP, so ChooseBestSolver might choose it.

Maybe you intent to change it soon so that it's not chosen anymore?
</blockquote></details>

I am not very confident to recommend NLopt. My limited experience has been that it doesn't compete with IPOPT/SNOPT (in terms of computation time, success rate, optimality of solution). Are you OK if we add NLopt here, but also note that we recommend SNOPT/IPOPT over NLopt? (I am a bit reluctant to put that note here, as I feel I haven't done exhaustive benchmark tests here, and it's probably unfair to NLopt developers)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15467#-MfJzItdBwHeJmPV0Z_P:-MfYp_h19aPwkKgvM7tq:bnn082t) ([raw file](https://github.com/robotlocomotion/drake/blob/90f06db2c75fb2dadbb3bfc8dfc1bbcee0b62fde/solvers/mathematical_program_doxygen.h#L129)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not very confident to recommend NLopt. My limited experience has been that it doesn't compete with IPOPT/SNOPT (in terms of computation time, success rate, optimality of solution). Are you OK if we add NLopt here, but also note that we recommend SNOPT/IPOPT over NLopt? (I am a bit reluctant to put that note here, as I feel I haven't done exhaustive benchmark tests here, and it's probably unfair to NLopt developers)
</blockquote></details>

My primary objective is that the tables here and the implementations of ProgramAttributesSatisfied are exactly congruent, in the sense that the marked vs empty cell in this table matches the true vs false in the code.

If we don't yet know how to resolve that discrepancy in the case of NLopt trying to solve LPs and QPs, then we could defer it via a TODO or issue for follow-up later.

**Review by hongkai-dai — COMMENTED** [review]
Done, I added the screen shot for preview

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467#-:-MfZHwFQ-gIILtHc2DtE:bc59a72)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program_doxygen.h, line 129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15467#-MfJzItdBwHeJmPV0Z_P:-MfZHsmD5W5t8aPEyWiz:b-ms9aav) ([raw file](https://github.com/robotlocomotion/drake/blob/90f06db2c75fb2dadbb3bfc8dfc1bbcee0b62fde/solvers/mathematical_program_doxygen.h#L129)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

My primary objective is that the tables here and the implementations of ProgramAttributesSatisfied are exactly congruent, in the sense that the marked vs empty cell in this table matches the true vs false in the code.

If we don't yet know how to resolve that discrepancy in the case of NLopt trying to solve LPs and QPs, then we could defer it via a TODO or issue for follow-up later.
</blockquote></details>

Done. That makes sense. I added NLopt

**Comment by jwnimmer-tri** [comment]
+@RussTedrake could you check over this for your taste?  The PR description contains screen captures for easy preview.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467#-:-MfZKHfy7YA8LNccgZWJ:bnfp4nl)* status: LGTM missing from assignee RussTedrake(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  very nice!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467#-:-Mf_3LSL4_hiX_uulp5A:bt3mtl7)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2FYPEbAmy8piy-nT:-Mf_2FYQEjXBRTsG3C_7:b-z8pllb) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L19)):*
> ```objc
>  *
>  * Drake wraps a number of open source and commercial solvers
>  * (+ a few custom solvers) to
> ```

btw: odd line-break.
___
*[solvers/mathematical_program_doxygen.h, line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2QaG5Evo0ATM1byl:-Mf_2QaG5Evo0ATM1bym:b-q73f9m) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L154)):*
> ```objc
>  * ▢ These solvers can solve the convex problems, but are not good at it. They
>  * treat the convex problems as general nonlinear optimization problems, which
>  * can lose the nice guarantee from convex optimization (global convergence,
> ```

btw: guarantee => guarantees 
___
*[solvers/mathematical_program_doxygen.h, line 155 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2_MD3-ULD_o8BWQ7:-Mf_2_MD3-ULD_o8BWQ8:bymoktd) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L155)):*
> ```objc
>  * treat the convex problems as general nonlinear optimization problems, which
>  * can lose the nice guarantee from convex optimization (global convergence,
>  * global optimality, etc).
> ```

btw, this sentence sounds quite surprising.  a nonlinear optimization approach to a convex problem would still get the global optima, one would think.  I guess you are referring to the possibility of details like we have in the SOCP formulations, where a problem can be convex but still have a vanishing gradient that can cause problems.

i don't think you want to include more details here, but perhaps "for subtle technical reasons" or something might be worth including.
___
*[solvers/mathematical_program_doxygen.h, line 241 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_3CvQ8PHfiMa2lDXS:-Mf_3CvRBQUZzNSjgUzM:bjqzewn) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L241)):*
> ```objc
>  *
>  * ‡ <a href="https://drake.mit.edu/from_binary.html">Drake's
>  * pre-compiled binary releases</a> provide SNOPT for anyone to use.
> ```

btw, add "with drake"?  (that was explicit in our deal with Philip)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 19 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2FYPEbAmy8piy-nT:-Mf_81Qw0bm-193XGePa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L19)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw: odd line-break.
</blockquote></details>

Done.
___
*[solvers/mathematical_program_doxygen.h, line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2QaG5Evo0ATM1byl:-Mf_86Nh7r3ZQnNR82mN:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L154)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw: guarantee => guarantees 
</blockquote></details>

Done.
___
*[solvers/mathematical_program_doxygen.h, line 155 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_2_MD3-ULD_o8BWQ7:-Mf_87XM-aHFDVBmnPdo:b9hhfee) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L155)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw, this sentence sounds quite surprising.  a nonlinear optimization approach to a convex problem would still get the global optima, one would think.  I guess you are referring to the possibility of details like we have in the SOCP formulations, where a problem can be convex but still have a vanishing gradient that can cause problems.

i don't think you want to include more details here, but perhaps "for subtle technical reasons" or something might be worth including.
</blockquote></details>

Right, I was thinking about some constraints that represent convex sets, but might be formulated as in a non-convex way, for example the Lorentz cone constraint. If we formulate it as
z >= 0
z² >= x₁² + ... + xₙ²
then the second constraint is non-convex. If we formulate it as z >= sqrt(x₁² + ... + xₙ²) then it is non-differentiable at 0.

I removed this sentence completely, since here we only recommend these solvers (snopt/ipopt/nlopt) for LP and QP, which I think they should still converge to global optimality with a gradient based approach.
___
*[solvers/mathematical_program_doxygen.h, line 241 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_3CvQ8PHfiMa2lDXS:-Mf_90IiCFQDvN1f8Yy6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L241)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw, add "with drake"?  (that was explicit in our deal with Philip)
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 241 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_3CvQ8PHfiMa2lDXS:-Mf_7j9wAE_slnAm8KxI:bbbye83) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L241)):*
Ah yes.  We've provided technical measures that prevent direct use, but the language in our docs could be more precise.  What do you think about this proposal:

> Drake's pre-compiled binary releases incorporate a private build of SNOPT that does not require a license when invoke via Drake's SnoptSolver wrapper class.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 241 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_3CvQ8PHfiMa2lDXS:-Mf_9svN1uHcMfJkbrZk:b-swowdv) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L241)):*
Oops, my suggestion had a typo s/invoke/invoked/

Fixed version: 

> Drake's pre-compiled binary releases incorporate a private build of SNOPT that does not require a license when invoked via Drake's SnoptSolver wrapper class.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[solvers/mathematical_program_doxygen.h, line 241 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_3CvQ8PHfiMa2lDXS:-Mf_Am8QAW2XJQsoj9fT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a95671d9d176d6cb6a0a9590abcc16c0bc94534c/solvers/mathematical_program_doxygen.h#L241)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, my suggestion had a typo s/invoke/invoked/

Fixed version: 

> Drake's pre-compiled binary releases incorporate a private build of SNOPT that does not require a license when invoked via Drake's SnoptSolver wrapper class.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

___
*[solvers/mathematical_program_doxygen.h, line 144 at r5](https://reviewable.io/reviews/robotlocomotion/drake/15467#-Mf_Bd329Qs-Z4j9Roz1:-Mf_Bd329Qs-Z4j9Roz2:b56enb7) ([raw file](https://github.com/robotlocomotion/drake/blob/f8d13b9b5c72c780c82b128f831dd267e40423d3/solvers/mathematical_program_doxygen.h#L144)):*
> ```objc
>  *
>  * ‡ <a href="https://drake.mit.edu/from_binary.html">Drake's pre-compiled
>  * binary releases incorporate a private build of SNOPT that does not require a
> ```

nit We're missing the `</a>` closing tag here now.

Ditto below.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15467)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
Squashed in, skipping debug builds for docs-only.

**Pull request merged**
