### PR TITLE
Move Variable/Variables/Environment classes under 'drake' namespace

### PR DESCRIPTION
**Pull request by soonho-tri**
- Move `Variable`/`Variables`/`Environment` classes from `drake::symbolic` namespace to 'drake' namespace.
 - Rename `symbolic_variable.{h,cc}` => `variable.{h,cc}`, `symbolic_variables.{h,cc}` => `variables.{h,cc}`, `symbolic_environment.{h,cc}` => `environment.{h,cc}`
 - Fix Bazel `BUILD` file
 - Fix `CMakeLists.txt` files

Close https://github.com/RobotLocomotion/drake/issues/4884

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4953)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri , could you review this?

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbbacYd8wKPR2k3mDP8:b-ty79mo)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
I am happy to look, but it might not happen today.  I have a lot of copy-paste and powerpoint that might eat the whole daytime.

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbjzX_aX6Wa797Hz0Ct:b-q4nhw9)*

**Comment by soonho-tri** [comment]
-@jwnimmer-tri , I see. I'll ask Hongkai if he can review it.

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-Kbjzm7M-I3JXTbpXvxv:b-dlp6ro)*

**Comment by soonho-tri** [comment]
+@hongkai-dai , could you feature-review this? It's mainly move/rename files/classes. No functionalities added.

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-Kbjzt0q-RtJyi5RpRn1:bendmy5)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 46 of 48 files at r1.
Review status: 36 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbkX_Ct782aWZwkmz1Q:bnfp4nl)*

**Comment by soonho-tri** [comment]
+@sherm1 , platform-review please.

---

Review status: 36 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbkXgJPdk_qe_rCrt4U:bb44qzm)*

**Comment by sherm1** [comment]
Platform: it appears that everything visible got moved out of namespace symbolic except for `symbolic::Expression` and `symbolic::Formula`. Why?

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbpYmiJ4j24NhKsrBsq:bq7haya)*

**Comment by soonho-tri** [comment]
Last week, we (Russ, Hongkai, Grant, Sam, and I) decided to promote `symbolic::Variable` to `Variable` and use it as a common "variable" in drake codebase. `Variables` and `Environment` are moved outside of `symbolic` namespace since they are strongly related to `Variable` class.

`Expression` and `Formula` are still in `symbolic` namespace because I think the annotation `symbolic` is still necessary to describe them.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbpZGvfmh_WD-jjSzxt:bhxsauq)*

**Comment by sherm1** [comment]
OK, thanks. I'm not sure why `Expression` and `Formula` need qualification -- we don't have any non-symbolic ones but we do have plenty of non-symbolic variables! But I trust you've thought it through. :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4953#-:-KbpioVc_RP5HFGl6kME:b-irt217)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-debug  please

**Pull request merged**
