### PR TITLE
[GCS] Use SparseMatrix for linear perspective constraints

### PR DESCRIPTION
**Pull request by RussTedrake**
+@hongkai-dai for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@ggould-tri for platform review please, thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874#-:-NaeKwlQ5jYn-oaIWahQ:b-svovrs)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19874#-NagJNsVDhqwa9itZEpG:-NagJNsVDhqwa9itZEpH:bonj7fo) (no related file):*
I am surprised to see a lot of additional if/else cases but no additional tests.  Do we know that the existing tests visit each of these blocks?

___

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874)* status: LGTM missing from assignee ggould-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19874#-NagJNsVDhqwa9itZEpG:-Nakf7qc4VnoCAM1QQvW:bliqxhv) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

I am surprised to see a lot of additional if/else cases but no additional tests.  Do we know that the existing tests visit each of these blocks?
</blockquote></details>

Done.  I've added comments to the existing test coverage and added one new test for the mixed case.

___

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874)* status: LGTM missing from assignee ggould-tri(platform)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19874)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),hongkai-dai

**Pull request merged**
