### PR TITLE
Allow model_instances for MBP::CalcJacobianCenterOfMassTranslationalVelocity()

### PR DESCRIPTION
**Pull request by mitiguy**
New overload for MultibodyPlant::CalcJacobianCenterOfMassTranslationalVelocity() to allow for model_instances 
to resolve issue #14916.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387)

### CODE REVIEW

**Review by mitiguy — COMMENTED** [review]
Feature review +@hongkai-dai (you suggested issue #14916, feel free to redirect if needed).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387#-:-Mf-uxic-XK1eRuKE0df:b46q013)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: could you also add the python binding for this new function?

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387#-:-Mf12vqN32XeXM0MOOkq:b-u7fzbx)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by hongkai-dai — COMMENTED** [review]
+@sherm1 for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387#-:-Mf4Goy7-oZSDsLa6wqc:buer3go)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending a few nits. I will fix those since Paul is on a long vacation.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387#-:-Mf5_kv48v2JSX3rfEkZ:bq8wx6k)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[multibody/plant/test/multibody_plant_jacobians_test.cc, line 313 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15387#-Mf5_h1D9IEUmh-3eL68:-Mf5_h1D9IEUmh-3eL69:bbjp7gu) ([raw file](https://github.com/robotlocomotion/drake/blob/7e95999833ef486655b0d9e53ccdcd4475f38884/multibody/plant/test/multibody_plant_jacobians_test.cc#L313)):*
> ```cpp
>     bodyB_ = &plant_->AddRigidBody("bodyB", bodyB_instance_, M_Bcm);
>     // bodyA_ = &plant_->AddRigidBody("BodyA", M_Bcm);
>     // bodyB_ = &plant_->AddRigidBody("BodyB", M_Bcm);
> ```

nit: delete dead code
___
*[multibody/tree/multibody_tree.cc, line 2615 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15387#-Mf5_Tun70ZBOwIRhtc9:-Mf5_Tun70ZBOwIRhtcA:b-i41ux4) ([raw file](https://github.com/robotlocomotion/drake/blob/7e95999833ef486655b0d9e53ccdcd4475f38884/multibody/tree/multibody_tree.cc#L2615)):*
> ```cpp
>     JacobianWrtVariable with_respect_to,
>     const Frame<T> &frame_A,
>     const Frame<T> &frame_E,
> ```

nit: "&" misplaced

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @sherm1)

___
*[multibody/plant/test/multibody_plant_jacobians_test.cc, line 313 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15387#-Mf5_h1D9IEUmh-3eL68:-Mf8PoEk8guvSXK7QL09:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e95999833ef486655b0d9e53ccdcd4475f38884/multibody/plant/test/multibody_plant_jacobians_test.cc#L313)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: delete dead code
</blockquote></details>

Done.
___
*[multibody/tree/multibody_tree.cc, line 2615 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15387#-Mf5_Tun70ZBOwIRhtc9:-Mf8RBOi8dYZqlY5ZPHg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7e95999833ef486655b0d9e53ccdcd4475f38884/multibody/tree/multibody_tree.cc#L2615)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: "&" misplaced
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15387)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),hongkai-dai (waiting on @mitiguy)

**Pull request merged**
