### PR TITLE
September 2022 updates

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Towards #17807.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17872)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Howdy Matt! This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, could you label it “status: do not review”?

(per checklist - https://drake.mit.edu/platform_reviewer_checklist.html)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please

**Comment by mwoehlke-kitware** [comment]
+@BetsyMcPhail for feature review, please.

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17872#-:-NBm9mDu67OQidbBJzEo:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
:lgtm: :  all appear to be releases or main branch; all that have any CI at all were passing at that revision. +(status: commits are properly curated) appears to be true; +(release notes: fix) applies.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17872#-:-NBnT7FT8CZdzeSOCWBS:bmteub0)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Pull request merged**
