### PR TITLE
Reorganize rotation_matrix.h 

### PR DESCRIPTION
**Pull request by mitiguy**
Reorganize files in preparation for moving file  drake/multibody/multibody_tree/math/rotation_matrix.h  to  drake/math/rotation_matrix.h

// The goal of PR #8217 is a first step to replace the "old" rotation_matrix.h
// file with the "new" rotation_matrix.h file which contains the new
// RotationMatrix class.  The process being employed will be able to make this
// replacement without changing #include drake/math/rotation_matrix.h statements
// in the multiplicity of its uses in currently existing Drake code.
// For PR #8217, the process is as follows:
// * Rename drake/math/rotation_matrix.h to
//   drake/math/rotation_matrix_utilities.h.
// * Rename drake/math/rotation_matrix.cc to
//   drake/math/rotation_matrix_utilities.cc.
// * Create new (mostly-empty) files:
//   drake/math/rotation_matrix.h
//   drake/math/rotation_matrix.cc.
// * Update build files and #include statements accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8217)

### CODE REVIEW

**Comment by sherm1** [comment]
Per f2f: needs an explanation of what happened here and what the next step is going to be. May need some TODOs.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-L6YtEzsHR0ura7ALus-:-L6YtEzsHR0ura7ALus0:bha5pju) ([raw file](https://github.com/robotlocomotion/drake/blob/76b807bc306e6c44a7ed285eb3e1dc33ce3db91c/math/rotation_matrix.h#L3)):*
> ```objc
> #pragma once
> 
> #include "drake/math/rotation_matrix_utilities.h"
> ```

BTW I think this needs a TODO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6YtJCcsyGDEAcNAfP6:b-3dteou)*

**Comment by mitiguy** [comment]
Feature review +@seancurtis-tri 
Platform review +@sherm1 

Note: To Sean and Sherm.
Ideally, this is an easy review - with just renaming of files.  
Unfortunately reviewable is not able to see that the file:
rotation_matrix.h  and  rotation_matrix.cc 
were renamed (via git mv) to
rotation_matrix_utilities.h   and  rotation_matrix_utilities.cc

Then I created/added two nearly-empty new files
called rotation_matrix.h and rotation_matrix.cc

TODO(mitiguy) Merge Rotation class from 
/drake/multibody/multibody_tree/math/rotation.h  into
/drake/math/rotation.h. 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6YsrbIrVcXYd-3sRoL:b-56grl2)*

**Comment by sherm1** [comment]
Review pass done,  a few comments. TODOs must go in code so that they end up in master until the work is done. Your comment above refers to `rotation.h` -- is that intentional? I would still appreciate a brief explanation of why you're doing this and what is the end goal (here in the comments).

---

Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8217#-L6YtEzsHR0ura7ALus-:-L6Z65Oe2o_3mBJH34ej:b7g8cq5) ([raw file](https://github.com/robotlocomotion/drake/blob/76b807bc306e6c44a7ed285eb3e1dc33ce3db91c/math/rotation_matrix.h#L3)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW I think this needs a TODO?
</blockquote></details>

BTW still needs a TODO (they go in code, not in reviewable comments).

---

*[math/rotation_matrix_utilities.cc, line 2 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8217#-L6Z6SlEBZeYVGDOyX_N:-L6Z6SlEBZeYVGDOyX_O:b-jrywym) ([raw file](https://github.com/robotlocomotion/drake/blob/76b807bc306e6c44a7ed285eb3e1dc33ce3db91c/math/rotation_matrix_utilities.cc#L2)):*
> ```cpp
> // For now, this is an empty .cc file that only serves to confirm
> // rotation_matrix.h is a stand-alone header.
> ```

BTW this comment needs updating.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8217#-:-L6Z6hi24d_h7qcd6RcS:b-avnmpl)*

**Comment by jwnimmer-tri** [comment]
If github and reviewable aren't seeing that its a simple rename, then `git praise` won't either.  Please squash and force-push to see if that fixes things.  Else, close and reopen.

**Comment by sherm1** [comment]
@jwnimmer-tri, @mitiguy and I looked at this. He made a new PR #8220 where the first commit does _just_ the rename of the files (not sufficient to pass CI). That renames rotation_matrix.h,cc -> rotation_matrix_utilities.h,cc. Then in the next commit reintroduces new files named rotation_matrix.h,cc. That all works fine and git understands the rename-then-recreated sequence. However, Reviewable is confused by that and decides that lots of changes got made if the "combined commits" view is used. Reviewing one commit at a time does show the correct operations.

So I think everything is fine, but I like the idea of a new PR that separates the rename commit from subsequent changes just so it is clear to reviewers what happened.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6ZIZ8-Bp1C2yDDPP17:b-9lljl4)*

**Comment by jwnimmer-tri** [comment]
I just pulled #8220 locally, squashed into a single commit, and it looks beautiful.  Try it!

**Comment by jwnimmer-tri** [comment]
(Maybe squashing this PR into a single commit is an easy way to try that, without disturbing #8220's attempt.)

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

I agree with Sherm on the need for TODOs.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6baBI7Y_a0nYu9P7Gm:bi5b3ph)*

**Comment by sherm1** [comment]
:lgtm: pending one comment fix.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[math/rotation_matrix.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-L6cShD2RUIVaAOURfSq:-L6cShD2RUIVaAOURfSr:b-65n2im) ([raw file](https://github.com/robotlocomotion/drake/blob/39f70994794c21d2df1620a20d523eba0f682cf6/math/rotation_matrix.h#L19)):*
> ```objc
> //   drake/math/rotation_matrix.h
> //   drake/math/rotation_matrix.cc.
> // * Update build files and #include statements accordingly.
> ```

BTW this is great but needs to be split into the code-relevant piece, and the PR discussion which should move to the PR comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6cTEgWCE4A3GrleoP7:b2p8qi4)*

**Comment by jwnimmer-tri** [comment]
I would still be more comfortable if this PR was locally squashed and force-pushed, so that we confirm that github understands the file-move, before we merge to master.  Relying on the green button to squash means that if something doesn't work, there is no way to undo it.

**Comment by sherm1** [comment]
We're planning to do that after CI succeeds.

**Comment by sherm1** [comment]
Rebased and squashed to one commit. Last change was just a comment so I'll force-merge this.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8217#-:-L6crtRcYPkplkeoL6ke:b-3vbsr)*

**Pull request merged**
