### PR TITLE
Remove orphaned urdf_*_test files

### LINKED ISSUE #6529: Remove files orphaned by removal of MATLAB tests
In `multibody\parsers/test`, the files
 - `urdf_collision_test`
 - `urdf_kinematics_test`
 - `urdf_manipulator_dynamics_test`
are now unused. Their original purpose was to ensure that the MATLAB and C++ URDF parsers stayed in sync. Now that the MATLAB parser is now more, they can be removed.

### PR DESCRIPTION
**Pull request by avalenzu**
These used to be used in conjunction with MATLAB tests to compare the
MATLAB and C++ parsers. Now that the MATLAB parser is gone, they're no
longer needed. Fixes #6529.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6531)

### CODE REVIEW

**Comment by avalenzu** [comment]
+@hongkai-dai for feature review

**Comment by hongkai-dai** [comment]
:lgtm: +@sammy-tri for platform review please

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6531#-:-KoTUUiIkh3VK6su6Vvc:b-5ivax5)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6531#-:-KoTk25rzAn14WPosZM1:bsf2vkf)*

**Comment by avalenzu** [comment]
-(status: curate commits before merging)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6531#-:-KogdoRx-9mI7V63DsXW:bhnab23)*

**Pull request merged**
