### PR TITLE
[parsing] Add PackageMap::PopulateFromRosPackagePath

### PR DESCRIPTION
**Pull request by cottsay**
This change aligns the PackageMap recursive crawl behavior with the `catkin_pkg` Python package in two specific behaviors:
1. Do not crawl in subdirectories of already identified packages.
2. Do not crawl into directories which have been explicitly marked to be ignored.

Packages currently found under such circumstances will receive a deprecation warning on use until this new behavior is promoted to the default behavior on or around 2022-07-01.

Fixes: #17171

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)

### CODE REVIEW

**Comment by cottsay** [comment]
I'm specifically looking for early feedback on:
1. The deprecation mechanism being used here
2. The new boolean flag that can be used to revert to the previous behavior
   I initially implemented this with a new enum flag for controlling the behaviors specifically, but I'm not sure that level of control is really desirable. That said, using flags we could also expose control over the omission of 'dot' directories, which are currently skipped unconditionally.

**Comment by jwnimmer-tri** [comment]
\CC @rpoyner-tri on the feedback.  I'll look as well (tomorrow).

**Review by IanTheEngineer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @cottsay and @jwnimmer-tri)

___
*[`multibody/parsing/package_map.h` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2q63g948FjGtvuUn1E:-N2q63gA-vq8KIdwV2JB:b-ho8vgq) ([raw file](https://github.com/robotlocomotion/drake/blob/76083846492667204f37b118d4cd7546a0a6c044/multibody/parsing/package_map.h#L26)):*
> ```objc
>   /// content in that directory and any subdirectories.
>   static constexpr std::array<std::string_view, 3> IgnoreMarkers = {
>     "AMENT_IGNORE",
> ```

Last I checked (admittedly a while ago): ROS1 tools respect `CATKIN_IGNORE` and ignore the others when present, while ROS2 tools respect `AMENT_IGNORE` and `COLCON_IGNORE` and ignore `CATKIN_IGNORE`. Is this still the case, and should we be respecting the union of these ignore files, or do something more granular? I figure this is worth pointing out, but I am not sure which is preferable.



_Code quote:_
```objc
    "AMENT_IGNORE",
    "CATKIN_IGNORE",
    "COLCON_IGNORE",
```

**Review by rpoyner-tri — COMMENTED** [review]
Looks ok so far. A few thoughts on the deprecation machinery:
 (1) can we make it clearer to future maintainers exactly what to delete?
 (2) do the deprecation messages give enough clues to a user about what to do instead? I'm no ROS/package-map expert, and it wasn't entirely clear to me.

As for fancier search control, I don't have a strong opinion. I think the single bool is good enough for cases I can foresee.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N2qhf1w3f5zz8gG-4jW:bv8x9l)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @cottsay and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: newly deprecated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N2qfiQW5kMGQrW_7EEo:b-dngdyv)* status: 6 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @cottsay, @IanTheEngineer, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qgPL6836HuBjCgxUM:-N2qgPL6836HuBjCgxUN:bbq62fd) (no related file):*
A slightly different mechanism for the "exhaustive" option would be to have it be a class property, instead of an argument on each function call.  Something like `set_is_exhaustive(bool)` or `bool& get_mutable_is_exhaustive()`.

That would allow the user to put the entire parser into non-exhaustive mode permanently at the beginning, instead of needing to annotate every call site with the policy.

It would also give a _much_ easier path to deprecation in the future -- we could deprecate that function as a whole.  Deprecating only a single argument is not easy with how C++ works.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qhpHi0-dWVoaGo0q_:-N2qhpHi0-dWVoaGo0qa:b-jsye7i) (no related file):*
I am having a bit of a struggle reading the logic of the crawl function.

Here is the desired behavior:

When called as exhaustive=true, any package.xml files that would have been ignored under the exhaustive=false search logic should receive a deprecation message.

When called as exhaustive=false, obey the new skipping logic and don't add any deprecation notices.

Is that how it works now?

It might be easier to follow the code if the function had a `bool within_ignored_subtree` instead of a `deprecation_message` as the recursion argument?

___
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qigbK-BcMtPJVn9Vh):*
nit Minimum 3 months, rounded up to the next 1st of the month.

Ditto throughout the code.



_Suggestion:_
```
2022-09-01
```
___
*[`multibody/parsing/package_map.h` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qg7br5-ONb74VccIT:-N2qg7br5-ONb74VccIU:bglggh3) ([raw file](https://github.com/robotlocomotion/drake/blob/76083846492667204f37b118d4cd7546a0a6c044/multibody/parsing/package_map.h#L25)):*
> ```objc
>   /// PopulateFromFolder and PopulateFromEnvironment to ignore all other
>   /// content in that directory and any subdirectories.
>   static constexpr std::array<std::string_view, 3> IgnoreMarkers = {
> ```

nit There's probably no reason to expose this symbol as part of our public contract?  Do we expect users to use this programmatically?  Seems like an implementation detail to me.
___
*[`multibody/parsing/package_map.h` line 26 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2q63g948FjGtvuUn1E:-N2qil1N4UmQ-AKnwrni:bm92cz8) ([raw file](https://github.com/robotlocomotion/drake/blob/76083846492667204f37b118d4cd7546a0a6c044/multibody/parsing/package_map.h#L26)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Last I checked (admittedly a while ago): ROS1 tools respect `CATKIN_IGNORE` and ignore the others when present, while ROS2 tools respect `AMENT_IGNORE` and `COLCON_IGNORE` and ignore `CATKIN_IGNORE`. Is this still the case, and should we be respecting the union of these ignore files, or do something more granular? I figure this is worth pointing out, but I am not sure which is preferable.
</blockquote></details>

For my part, I'm OK if Drake's PackageMap obeys all of the ignore spellings all at once.  That seems the most useful by default.  If the user wants something else, then they can write their own code to crawl-and-add using their own rules.  Our crawler function is just sugar heuristics around AddPackageXml in a loop.
___
*[`multibody/parsing/package_map.h` line 99 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qffJ89EgjfRFjV13d:-N2qffJ9Bye5k341Gb5j:bpfefr) ([raw file](https://github.com/robotlocomotion/drake/blob/76083846492667204f37b118d4cd7546a0a6c044/multibody/parsing/package_map.h#L99)):*
> ```objc
>   /// conflicting path, a warning is logged and the original path is kept.
>   /// If the path does not exist or is unreadable, a warning is logged.
>   void PopulateFromFolder(const std::string& path, bool exhaustive = false);
> ```

nit We need to default to the _current_ behavior for now, otherwise this would be a breaking change when a user upgrades their Drake version.

Users can opt-in to the new behavior immediately if they prefer.

After the deprecation window expires, we will change the default to false (and remove the flag if we'd like).



_Suggestion:_
```objc
exhaustive = true
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay, @IanTheEngineer, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qhpHi0-dWVoaGo0q_:-N2rgmvlCplMOMCQ4abM:b-6xqso4) (no related file):*
> I was under the impression that the current/exhaustive crawl behavior will always be desirable ..

Ah, okay, I failed to grasp that.

All of these functions are just sugar around `Add(name, path)`.  We should choose exactly the sugar that makes the most sense for the most users.

If we want to keep around "search for everything" indefinitely then I think it should remain exactly as it is, under exactly the same function names, no changes.  That will avoid disrupting anyone currently.  Then, in this PR we would add _totally new functions_ that do whatever sugar and semantics that ROS users want.  Maybe `void PackageMap::AddRosPackagePaths();` which only ever looks at `$ROS_PACAKGE_PATH` and obeys the ROS-specific ignore semantics.

___

**Review by rpoyner-tri — COMMENTED** [review]
Release notes should mention the topic, but shouldn't be a source for detailed advice. PackageMap is a public class with doxygen documentation. One could imagine adding a doxygen `@note` in the header and having error messages refer to that somehow. @jwnimmer-tri may have a better idea.

> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N2vuWKDBa5Yvo-gRkL1:b-31mufx)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay, @IanTheEngineer, and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
My current understanding is that once this PR is reworked, there will be no more deprecation, so it's probably moot.

**Review by cottsay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay, @IanTheEngineer, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2qhpHi0-dWVoaGo0q_:-N2xcLTV7oJAP3xLj3f_:b-tvv8ns) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I was under the impression that the current/exhaustive crawl behavior will always be desirable ..

Ah, okay, I failed to grasp that.

All of these functions are just sugar around `Add(name, path)`.  We should choose exactly the sugar that makes the most sense for the most users.

If we want to keep around "search for everything" indefinitely then I think it should remain exactly as it is, under exactly the same function names, no changes.  That will avoid disrupting anyone currently.  Then, in this PR we would add _totally new functions_ that do whatever sugar and semantics that ROS users want.  Maybe `void PackageMap::AddRosPackagePaths();` which only ever looks at `$ROS_PACAKGE_PATH` and obeys the ROS-specific ignore semantics.
</blockquote></details>

Alright, I added `PopulateFromRosPackagePath`, which hides the new behaviors from the public API.

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot ok to test

**Review by jwnimmer-tri — COMMENTED** [review]
This seems on the right track to me.  I posted a few small style notes.

+@IanTheEngineer for feature review, please.  \CC @calderpg-tri FYI

> Reviewed 1 of 8 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N2yeF4m3L9HnLJz0cxY:b314x7o)* status: 3 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),IanTheEngineer, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay, @IanTheEngineer, and @jwnimmer-tri)

___
*[`multibody/parsing/package_map.cc` line 33 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2yd5HhE6GiBl3Iq023:-N2yd5HhE6GiBl3Iq024:b-6njc7l) ([raw file](https://github.com/robotlocomotion/drake/blob/89d7bb3afa737aa5ff1e390e5c3712021ce38170/multibody/parsing/package_map.cc#L33)):*
> ```cpp
> // PopulateFromRosPackagePath to ignore all other content in that directory
> // and any subdirectories.
> static const std::vector<std::string_view> IgnoreMarkers = {
> ```

nit This is a non-trivial constructor, so cannot be a global.

https://drake.mit.edu/styleguide/cppguide.html#Static_and_Global_Variables

Creating it as a stack local within `PopulateFromRosPackagePath` is cheap compared to everything else going on in that function, so is probably the best fix.
___
*[`multibody/parsing/package_map.cc` line 155 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N2ydh1MDw88ISZWydWN:-N2ydh1MDw88ISZWydWO:b-2fn60f) ([raw file](https://github.com/robotlocomotion/drake/blob/89d7bb3afa737aa5ff1e390e5c3712021ce38170/multibody/parsing/package_map.cc#L155)):*
> ```cpp
>     return;
>   }
>   std::istringstream iss{string(value)};
> ```

nit `iss` is not a valid form of abbreviation:

https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules



_Suggestion:_
```cpp
input
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer)

**Review by cottsay — COMMENTED** [review]
@jwnimmer-tri, do you think it might be helpful to add a warning if someone calls `PopulateFromEnvironment` with `ROS_PACKAGE_PATH`, instructing the user to use `PopulateFromRosPackagePath` instead?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N3QmtRE0OIMKbPASxzR:bqdwozs)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer)

**Comment by jwnimmer-tri** [comment]
It does seems like using that function in that way would be a mistake, since we'd be ignoring ROS semantics in a case where we almost certainly should be obeying them.

Therefore, I would buy documenting in the Doxygen for `PopulateFromEnvironment` that `PopulateFromEnvironment("ROS_PACKAGE_PATH")` is not allowed.  To avoid a breaking change, we'd just log a warning for now is the user tries it, but then after the deprecation period (in >3 months) we'd promote it to throw an exception.

(In general, Drake does not log warnings because in there's not always a console for them to go to.  That's why I proposed an exception here as the eventual goal.)

**Review by IanTheEngineer — COMMENTED** [review]
Thanks for iterating on this PR already, Scott. I appreciate that you've already incorporated feedback from the team. I have a few small thoughts and suggestions below.

> Reviewed 3 of 8 files at r1, 1 of 4 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N5NYWIqEKqGkWmhhl31:b-p0helk)* status: 2 unresolved discussions, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay)

___
*[`multibody/parsing/BUILD.bazel` line 27 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N5NXKWn8G4JHgIXSwC0:-N5NXKWn8G4JHgIXSwC1:b-lin10s) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b4f3995337ac0d13781c67a3002f6da9a353c7/multibody/parsing/BUILD.bazel#L27)):*
> ```Starlark
>         "test/**/*.xml",
>         "test/**/*.png",
>         "test/**/CATKIN_IGNORE",
> ```

BTW: I follow your logic; adding a single CATKIN_IGNORE for the testing environment is likely sufficient. AMENT_IGNORE is pretty uncommon these days. I do wonder, should we add a folder with a COLCON_IGNORE for testing? I'd be interested in your thoughts here.
___
*[`multibody/parsing/package_map.h` line 108 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N3ukBJ52v1a9EMah2kb:-N3ukBJ52v1a9EMah2kc:b59p13a) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1bcd3cb8255289c989e1ac25a75a0dade5fc78/multibody/parsing/package_map.h#L108)):*
> ```objc
> 
>   /// Obtains one or more paths from the ROS_PACKAGE_PATH environment variable.
>   /// Semantics are similar to PopulateFromEnvironment, except that ROS-style
> ```

nit This is a function, so specify with parentheses: `PopulateFromEnvironment()`. That will be more consistent with the other doxygen text referring to functions in this file.



_Code quote:_
```objc
PopulateFromEnvironment
```
___
*[`multibody/parsing/package_map.h` line 134 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N3uu21063eyFbN5Cc7X:-N3uu21063eyFbN5Cc7Y:b-gwtkzu) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1bcd3cb8255289c989e1ac25a75a0dade5fc78/multibody/parsing/package_map.h#L134)):*
> ```objc
> 
>   // Recursively crawls through @p path looking for package.xml files. Adds
>   // the packages defined by these package.xml files to this PackageMap.
> ```

The new function parameters should be addressed in this description (even though their defaulted values prevent impacting downstream users).



_Code quote (from multibody/parsing/package_map.cc):_
```cpp
CrawlForPackages
```
___
*[`multibody/parsing/package_map.cc` line 284 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N5ManvO9zw30obGOblk:-N5ManvO9zw30obGObll:bgzhlew) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b4f3995337ac0d13781c67a3002f6da9a353c7/multibody/parsing/package_map.cc#L284)):*
> ```cpp
>         ParsePackageManifest(manifest.string());
>     const string package_path = dir.string();
>     if (AddPackageIfNew(package_name, package_path + "/"))
> ```

BTW, consider adding curly braces to these single line conditionals to increase readability, but it is not required:
https://drake.mit.edu/styleguide/cppguide.html#Conditionals



_Code quote:_
```cpp
    if (AddPackageIfNew(package_name, package_path + "/"))
      SetDeprecated(package_name, deprecated_message);
    if (stop_at_package)
      return;
```

**Review by cottsay — COMMENTED** [review]
Sorry for the delayed responses. I applied all of the remaining recommendations.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N6F393N8mTcAgV4MVXL:b8gyeo5)* status: 1 unresolved discussion, LGTM missing from assignee IanTheEngineer, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @jwnimmer-tri)

___
*[`multibody/parsing/BUILD.bazel` line 27 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N5NXKWn8G4JHgIXSwC0:-N6F0xLoEfCvX6EzQhBf:b-tkzz7u) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b4f3995337ac0d13781c67a3002f6da9a353c7/multibody/parsing/BUILD.bazel#L27)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: I follow your logic; adding a single CATKIN_IGNORE for the testing environment is likely sufficient. AMENT_IGNORE is pretty uncommon these days. I do wonder, should we add a folder with a COLCON_IGNORE for testing? I'd be interested in your thoughts here.
</blockquote></details>

I really don't care which one we pick for testing. I'll change it to `COLCON_IGNORE` if that's the one you'd like to see.
___
*[`multibody/parsing/package_map.h` line 134 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N3uu21063eyFbN5Cc7X:-N6F1X8n-k2byzT054p_:b-n3u2fo) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1bcd3cb8255289c989e1ac25a75a0dade5fc78/multibody/parsing/package_map.h#L134)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

The new function parameters should be addressed in this description (even though their defaulted values prevent impacting downstream users).
</blockquote></details>

I'll go ahead and add some docs, but please note that this is a private function, so there are no downstream users.

**Review by IanTheEngineer — COMMENTED** [review]
:LGTM: Thanks for the updates, Scott.

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N6QlWFb6Dr53XZszQt_:b48ysqn)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay)

___
*[`multibody/parsing/package_map.h` line 134 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N3uu21063eyFbN5Cc7X:-N6Qk5bE4gU8ZGm02pe_:bnqxaah) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1bcd3cb8255289c989e1ac25a75a0dade5fc78/multibody/parsing/package_map.h#L134)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

I'll go ahead and add some docs, but please note that this is a private function, so there are no downstream users.
</blockquote></details>

Indeed this is private, but the clarifying doc strings are appreciated.
___
*[`multibody/parsing/package_map.cc` line 131 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N6QmN9K2qXEfcCZgeV-:-N6QmN9K2qXEfcCZgeV0:byohiw8) ([raw file](https://github.com/robotlocomotion/drake/blob/d9b4f3995337ac0d13781c67a3002f6da9a353c7/multibody/parsing/package_map.cc#L131)):*
> ```cpp
>     drake::log()->warn(
>       "PackageMap: PopulateFromEnvironment(\"ROS_PACKAGE_PATH\") is "
>       "deprecated, and will be disabled on or around 2022-10-01. To populate "
> ```

Nit: This date now rounds up to 2022-11-01.



_Code quote:_
```cpp
2022-10-01
```

**Review by IanTheEngineer — COMMENTED** [review]
+@rpoyner-tri for Platform Review (as you're already familiar with this PR) when you're up on Tuesday, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N6Qmmd88r-MQ_jecayr:b-n7nugi)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo, deprecation date adjustment

> Reviewed 2 of 8 files at r1, 1 of 4 files at r3, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251#-:-N6TmvvlEjCnSaiglWiY:bx195po)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay)

___
*[`multibody/parsing/package_map.h` line 108 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N6Ti4bc1g76-pg1W08P:-N6Ti4bc1g76-pg1W08Q:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/0a1e5f387e833e55190b9a37397d9b7e063d2808/multibody/parsing/package_map.h#L108)):*
> ```objc
>   /// ROS_PACKAGE_PATH environment variable. To do so, the
>   /// PopulateFromRosPackagePath function should be used instead, which follows
>   /// standard ROS package discovery semantices described in the documentation
> ```

typo



_Code quote:_
```objc
semantices
```

**Review by cottsay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer and @rpoyner-tri)

___
*[`multibody/parsing/package_map.h` line 134 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17251#-N3uu21063eyFbN5Cc7X:-N6Tz9OU7vxMWkvmGDzU:b-2gt84r) ([raw file](https://github.com/robotlocomotion/drake/blob/0e1bcd3cb8255289c989e1ac25a75a0dade5fc78/multibody/parsing/package_map.h#L134)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Indeed this is private, but the clarifying doc strings are appreciated.
</blockquote></details>

Sure, I added `@param` descriptions for each.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @IanTheEngineer)

**Review by jwnimmer-tri — COMMENTED** [review]
> Dismissed @IanTheEngineer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17251)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @cottsay)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
