### PR TITLE
Extracted reusable functionality from DoCalcOutput, renamed methods related to pitch and yaw

### PR DESCRIPTION
**Pull request by nikos-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6176)

### CODE REVIEW

**Comment by nikos-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
This PR contains a commit from another PR. Try re-basing with master:

```
$ git checkout master
$ git pull upstream master
$ git checkout depth-sensor-mods
$ git rebase master

// Be careful before executing this since it destroys the previous branch
// on your fork. Ensure your branch is in a desirable state.
$ git push -f origin depth-sensor-mods
```

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kkx7l0cwqgQucToUebH:b-xhvn0)*

**Comment by liangfok** [comment]
Completed first pass. I ignored the file that I think was accidentally included in this PR.

---

Reviewed 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/depth_sensor.cc, line 168 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxDYbB7J5_BUOz1vbD:-KkxDYbB7J5_BUOz1vbE:b-ca0e23) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.cc#L168)):*
> ```cpp
> }
> 
> void DepthSensor::ApplyLimits(VectorX<double>* distances) const {
> ```

BTW, you can create a reference to avoid all the dereferencing below:

```
VectorX<double>& d = *distances;
```

---

*[drake/systems/sensors/depth_sensor.h, line 129 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxEW-ttdjBz3MSS656:-KkxEW-ttdjBz3MSS657:bb49nka) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L129)):*
> ```objc
> 
>   /// Returns the number of pixel rows in the resulting depth sensor output.
>   /// This is equal to parameter `DepthSensorSpecification::num_pitch_values`
> ```

BTW, you can omit the back-ticks here because Doxygen will automatically make it a URL. Try generating the Doxygen website to verify that this is true: 

http://drake.mit.edu/documentation_instructions.html#when-using-cmake

Note that you will need to build Drake using CMake before you can generate the Doxygen website.

---

*[drake/systems/sensors/depth_sensor.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxEog1kpdn29TQOvUM:-KkxEog1kpdn29TQOvUN:b-akti9g) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L134)):*
> ```objc
> 
>   // Returns the number of pixel columns in the resulting depth sensor output.
>   // This is equal to parameter `DepthSensorSpecification::num_yaw_values`
> ```

BTW, same comment here regarding omitting the back-ticks.

---

*[drake/systems/sensors/depth_sensor.h, line 197 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxF1bVBssx7NBoylmb:-KkxF1bVBssx7NBoylmc:bxphqzc) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L197)):*
The style guide indicates that methods be ordered first within the private section of a class:

> Within each section, generally prefer grouping similar kinds of declarations together, and generally prefer the following order: types (including typedef, using, and nested structs and classes), constants, factory functions, constructors, assignment operators, destructor, all other methods, data members.

https://google.github.io/styleguide/cppguide.html#Declaration_Order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-KkxFUzfqtlf-GWhv_1t:b-84jewo)*

**Comment by nikos-tri** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/sensors/depth_sensor.cc, line 168 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxDYbB7J5_BUOz1vbD:-Kl-Zgfvg252pTq4oJ0k:b-90ux3f) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.cc#L168)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, you can create a reference to avoid all the dereferencing below:

```
VectorX<double>& d = *distances;
```
</blockquote></details>

Done, thanks for the tip.

---

*[drake/systems/sensors/depth_sensor.h, line 129 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxEW-ttdjBz3MSS656:-Kl-Zn7Tv-H-wHNmCfqL:b4fdb67) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L129)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, you can omit the back-ticks here because Doxygen will automatically make it a URL. Try generating the Doxygen website to verify that this is true: 

http://drake.mit.edu/documentation_instructions.html#when-using-cmake

Note that you will need to build Drake using CMake before you can generate the Doxygen website.
</blockquote></details>

Done, thanks for the pointer to building the documentation.

---

*[drake/systems/sensors/depth_sensor.h, line 134 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxEog1kpdn29TQOvUM:-Kl-ZrDNLpBcusgAPyC0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L134)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, same comment here regarding omitting the back-ticks.
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 197 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-KkxF1bVBssx7NBoylmb:-Kl-LOd1rE9bJnjas3Fa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5f2344f406826d77bed433f7004a625ac50638df/drake/systems/sensors/depth_sensor.h#L197)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The style guide indicates that methods be ordered first within the private section of a class:

> Within each section, generally prefer grouping similar kinds of declarations together, and generally prefer the following order: types (including typedef, using, and nested structs and classes), constants, factory functions, constructors, assignment operators, destructor, all other methods, data members.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl-_PB7SMiWi20McHJI:b-896fix)*

**Comment by liangfok** [comment]
Completed another pass.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/depth_sensor.cc, line 174 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0CBdMhDxJuAP-ps00:-Kl0CBdMhDxJuAP-ps01:bbh0p26) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.cc#L174)):*
> ```cpp
>     if (d[i] < 0) {
>       // Infinity distance measurements show up as -1.
> ```

BTW, odd blank line introduced here.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0ClkF3jZTE2M5dWrj:b-2ksew7) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
> ```objc
>   // Returns the number of pixel columns in the resulting depth sensor output.
>   // This is equal to parameter DepthSensorSpecification::num_yaw_values
>   // that's passed into the constructor.
> ```

This should be a Doxygen comment block (`///` instead of `//`) since the method it describes is public.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl0D3ezjJccEOYwR2tP:b-pna0oq)*

**Comment by nikos-tri** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/sensors/depth_sensor.cc, line 174 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0CBdMhDxJuAP-ps00:-Kl0OUYHAVLUyvs2xejo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.cc#L174)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, odd blank line introduced here.
</blockquote></details>

Done.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0NIui2Ng0fAqy90Lq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

This should be a Doxygen comment block (`///` instead of `//`) since the method it describes is public.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl0OW257PFi23dFjRAU:b-896fix)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0PsLmrQ2LAJ6kPQdD:b-y0binr) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you changed the wrong comment block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Comment by nikos-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0RzIwacxfRJucgAde:b-2hpv4l) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Looks like you changed the wrong comment block.
</blockquote></details>

Sorry, should not have changed the private ones. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0gw4w2qQRGD_81Pjh:bmudf4k) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
<details><summary><i>Previously, nikos-tri wrote…</i></summary><blockquote>

Sorry, should not have changed the private ones. Done.
</blockquote></details>

The documentation for this method (`get_num_yaw()` should be a Doxygen block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Comment by nikos-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/depth_sensor.h, line 135 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl0ClkF3jZTE2M5dWri:-Kl0i5wT6J6JeIzIebY3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d159ff2c80f1c86897ae720e1de7c804f48eea89/drake/systems/sensors/depth_sensor.h#L135)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

The documentation for this method (`get_num_yaw()` should be a Doxygen block.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl0tCwNn_FOLIMOfuyb:bnfp4nl)*

**Comment by nikos-tri** [comment]
+@sammy-tri

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl5ksuOoRSzWhqvWmTy:b38cofj)*

**Comment by nikos-tri** [comment]
+@sherm1 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl5ly-P-jSTg1ebBqiI:bal7hz4)*

**Comment by sherm1** [comment]
Nice! :lgtm: with one ignorable BTW, ptal.

-@sammy-tri

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/depth_sensor.cc, line 178 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl5mfYu-sxcDwaQ8UiO:-Kl5mfYu-sxcDwaQ8UiP:bj49ypg) ([raw file](https://github.com/robotlocomotion/drake/blob/56ad2dee5ce04e42eb729186b43fa6a100d2826d/drake/systems/sensors/depth_sensor.cc#L178)):*
> ```cpp
>       } else {
>         drake::log()->warn("Measured distance was < 0 and != -1: " +
>                            std::to_string(d[i]));
> ```

BTW consider throwing an exception (`std::logic_error`?) here if this represents a user error of some kind, or replace with a `DRAKE_DEMAND` assertion if this can only be due to a bug within the Drake codebase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-:-Kl5m4zRx8Z3mZo6-EqJ:b9fe8sc)*

**Comment by nikos-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/sensors/depth_sensor.cc, line 178 at r6](https://reviewable.io:443/reviews/robotlocomotion/drake/6176#-Kl5mfYu-sxcDwaQ8UiO:-Kl5tgmizf_tSLWmbLcy:b-8wwae0) ([raw file](https://github.com/robotlocomotion/drake/blob/56ad2dee5ce04e42eb729186b43fa6a100d2826d/drake/systems/sensors/depth_sensor.cc#L178)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider throwing an exception (`std::logic_error`?) here if this represents a user error of some kind, or replace with a `DRAKE_DEMAND` assertion if this can only be due to a bug within the Drake codebase.
</blockquote></details>

Discussed with Liang and replaced with a DRAKE_DEMAND.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6176)*

**Pull request merged**
