### PR TITLE
[fem] Add unit test for CorotatedModelData

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16597)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for sole review please.

+(status: single reviewer ok) +(release notes: none) +(component: softsim fem) 

This is towards #16492. The CorotatedModelData class was missing unit tests. This PR fixes that, and the next PR will move `CorotatedModelData` along with the unit tests here out of `dev`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16597#-:-MvzLkkz7mvdhNK08O4z:bav9wvg)* status: LGTM missing from assignee amcastro-tri (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16597)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16597)* status: 1 unresolved discussion (waiting on @amcastro-tri)

___
*[multibody/fixed_fem/dev/test/corotated_model_data_test.cc, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16597#-Mw2-09N5CtfPRexPGl7:-Mw2eF5n8TZdMa2MyBqV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4db763e6f23da9714f8073c97ca888b6b06409ca/multibody/fixed_fem/dev/test/corotated_model_data_test.cc#L51)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi, I often like to write this as:
```c++
// clang-format off
const Matrix3<double> S = (Matrix3<T>() << 
       6, 1, 2,
       1, 4, 1,
       2, 1, 5
).finished();
// clang-format on
```
</blockquote></details>

Done.
___
*[multibody/fixed_fem/dev/test/corotated_model_data_test.cc, line 63 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16597#-Mw20fPk8d9Zv7kIKSbA:-Mw2eEvAArsGhyU-seLH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4db763e6f23da9714f8073c97ca888b6b06409ca/multibody/fixed_fem/dev/test/corotated_model_data_test.cc#L63)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

TIL, EXPECT_DOUBLE_EQ. However, I cannot find docs specifying the accuracy of this loose comparison. 
Wound't we prefer EXPECT_NEAR we  a tolerance we control explicitly?

</blockquote></details>

Done.

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16597)* status: :shipit: complete! all discussions resolved, LGTM from assignee amcastro-tri, exempt from platform review (waiting on @xuchenhan-tri)

**Pull request merged**
