### PR TITLE
Port make_arm_controller_model() to Drake

### PR DESCRIPTION
**Pull request by zachfang**
Toward #17112 

Another PR for porting the Iiwa simulated driver will follow after this one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
+@jwnimmer-tri for feature review, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865#-:-NBQVpLwDGM495lTSnsV:buc9dmg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

+(status: commits are properly curated)
+(release notes: none)

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865#-:-NBSXvu36kbz9TUrnmqo:be9xs8s)* status: 5 unresolved discussions, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @zachfang)

___
*[`manipulation/util/make_arm_controller_model.h` line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSVjd4-RjHCqghvhBA:-NBSVjd4-RjHCqghvhBB:b-yrm6nn) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.h#L5)):*
> ```objc
> #include <memory>
> #include <optional>
> #include <string>
> ```

nit Unused `<string>`
___
*[`manipulation/util/make_arm_controller_model.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSVumEEfbmDUEIoKkx:-NBSVumEEfbmDUEIoKky:b9m1zpx) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.h#L15)):*
> ```objc
> namespace internal {
> 
> /// Constructs a separate plant (different from the simulated plant!) that the
> ```

nit For `namespace internal` code, we cannot use Doxygen comment markers (see [GSG](https://drake.mit.edu/styleguide/cppguide.html#Doxygen)), so here we need either `//` or `/* ... */` per GSG.  Our evolving custom is to prefer `/* ... */` in this case.
___
*[`manipulation/util/make_arm_controller_model.cc` line 49 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWTjt8vOzITt9RoQg:-NBSWTju3G49wiQ9KG3N:b-ygultx) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.cc#L49)):*
> ```cpp
>   drake::log()->debug("  arm:");
>   drake::log()->debug("    model: {}", arm_info.model_path);
>   drake::log()->debug("    child_frame: {}", arm_info.child_frame_name);
> ```

nit We can lose the `drake::` prefixes here and throughout.
___
*[`manipulation/util/make_arm_controller_model.cc` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWmlS-PtGUXsW_CcQ:-NBSWmlTCxNixFs4d9hM:b-88pfw5) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.cc#L57)):*
> ```cpp
>   // MbP. The same time step (=1.0) is used for plants in planning. Provided
>   // this plant is never used for simulation, this should be OK.
>   // See Drake issue #14688.
> ```

For the record, zero-timestep plants don't warning-spam anymore (the issue is fixed), so this comment is out of date.  I'm OK with leaving this comment alone for now, if you prefer, though; it's not the only commit inside Drake that's gone stale about this.
___
*[`manipulation/util/test/make_arm_controller_model_test.cc` line 88 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWK4Z2aJF_rVZ69Q-:-NBSWK4Z2aJF_rVZ69Q0:b-qrf9xs) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/test/make_arm_controller_model_test.cc#L88)):*
> ```cpp
>     const std::vector<ModelInstanceIndex>& models) {
>   std::vector<BodyIndex> body_indices;
>   for (const auto model : models) {
> ```

nit typo



_Suggestion:_
```cpp
for (const auto& model : models) {
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for platform review per schedule, please.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865#-:-NBSlM8S9fd7fDiQGO8d:b2xa7ij)* status: 2 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @zachfang)

___
*[`manipulation/util/make_arm_controller_model.h` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSlFnA2AtB79GxtHZZ:-NBSlFnA2AtB79GxtHZ_:b-qrf9xs) ([raw file](https://github.com/robotlocomotion/drake/blob/5537311eda4defa47df296f1bcc954980d00453c/manipulation/util/make_arm_controller_model.h#L23)):*
> ```objc
> 
>  If @p gripper_info is provided, this function will use @p simulation_plant
>  togit dif measure the gripper's inertia and attach a single non-articulated
> ```

nit typo

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @zachfang)

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`manipulation/util/make_arm_controller_model.h` line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSVumEEfbmDUEIoKkx:-NBSld2iEkhUeWz2O-bz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.h#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit For `namespace internal` code, we cannot use Doxygen comment markers (see [GSG](https://drake.mit.edu/styleguide/cppguide.html#Doxygen)), so here we need either `//` or `/* ... */` per GSG.  Our evolving custom is to prefer `/* ... */` in this case.
</blockquote></details>

Done.
___
*[`manipulation/util/make_arm_controller_model.h` line 23 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSlFnA2AtB79GxtHZZ:-NBSlc-m1lxIiGXN70cu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5537311eda4defa47df296f1bcc954980d00453c/manipulation/util/make_arm_controller_model.h#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit typo
</blockquote></details>

Done.
___
*[`manipulation/util/make_arm_controller_model.cc` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWmlS-PtGUXsW_CcQ:-NBSlh_VDuC1rwt8LBKW:b-hnhtv8) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.cc#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For the record, zero-timestep plants don't warning-spam anymore (the issue is fixed), so this comment is out of date.  I'm OK with leaving this comment alone for now, if you prefer, though; it's not the only commit inside Drake that's gone stale about this.
</blockquote></details>

I can make the change here (together with the platform comments). My understanding is we can now do
```
auto plant = std::make_unique<MultibodyPlant<double>>(0.0);
```

And kill the above comment entirely.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @zachfang)

___
*[`manipulation/util/make_arm_controller_model.cc` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWmlS-PtGUXsW_CcQ:-NBSmMJa8CAmJMO7P3i0:b-q1kpqh) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.cc#L57)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

I can make the change here (together with the platform comments). My understanding is we can now do
```
auto plant = std::make_unique<MultibodyPlant<double>>(0.0);
```

And kill the above comment entirely.
</blockquote></details>

Yes, I think so.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with some minor nits, sweet!

> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865#-:-NBSxV10Asz5PmhAEPT6:bvduyka)* status: 4 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @zachfang)

___
*[`manipulation/util/BUILD.bazel` line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSxI4U-9-Tfl2JxtS2:-NBSxI4U-9-Tfl2JxtS3:bl0x5n9) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/BUILD.bazel#L133)):*
> ```Starlark
>     hdrs = ["make_arm_controller_model.h"],
>     internal = True,
>     # TODO(zachfang): Change the visibility setting when migrating iiwa driver.
> ```

nit TODO may also apply to `internal = True` above.

Consider moving one line up, or to line above `drake_cc_library`? (I guess it may have been shifted to do `buildifier`)
___
*[`manipulation/util/make_arm_controller_model.h` line 15 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSwq_V2LNalUrP7Bz0:-NBSwq_V2LNalUrP7Bz1:b9pbcb6) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/make_arm_controller_model.h#L15)):*
> ```objc
> 
> /* Constructs a separate plant (different from the simulated plant!) that the
>  controller will do inverse dynamics on.  The difference between this plantvand
> ```

nit The phrase "the controller will do inverse dynamics on" may be imprecise from a Drake user's perspective.

Consider something like:
```
the can be used to instantiate a controller system such as `InverseDynamicsController`
```
___
*[`manipulation/util/make_arm_controller_model.h` line 36 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSprON4EaYz26NpGUK:-NBSprON4EaYz26NpGUL:be4rwju) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/make_arm_controller_model.h#L36)):*
> ```objc
>  @pre If @p gripper_info is given and `grasp_frame` exists, then `grasp_frame`
>       is welded to @p gripper_info.child_frame_name. */
> // TODO(eric.cousineau): Replace this with more generic (and robust) multibody
> ```

FYI @azeey Here is another use case that could possibly be improved by subgraph - it could eliminate need for bespoke `ModelInstanceInfo`, and only rely on added model instances.
___
*[`manipulation/util/make_arm_controller_model.cc` line 100 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSq5IF-Gd5WRungi_T:-NBSq5IF-Gd5WRungi_U:bwlggxn) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/make_arm_controller_model.cc#L100)):*
> ```cpp
>         gripper_body_name, gripper_info->model_instance);
> 
>     // TODO(sam-creasey) We actually want all kinematic children from the
> ```

BTW This may be stale (but not strictly invalid) with landing of #17800 to include fingers by means of
`welded_bodies_to_G + bodies_affected_by_finger_joints`.

That also being said, this could also be simplified with subgraph approach or something like it at some point.
\cc @sammy-tri
___
*[`manipulation/util/make_arm_controller_model.cc` line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSw27O8NSOY6Ou7CYK:-NBSw27O8NSOY6Ou7CYL:b7fsd97) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/make_arm_controller_model.cc#L110)):*
> ```cpp
>       if ((welded_body->model_instance() != gripper_info->model_instance) &&
>           (welded_body->model_instance() != arm_info.model_instance)) {
>         log()->info("Adding BodyIndex of Body {}", welded_body->name());
> ```

nit Logging to `info` seems noisy. Consider demoting to `debug`.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 4 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @zachfang)

___
*[`manipulation/util/BUILD.bazel` line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSxI4U-9-Tfl2JxtS2:-NBSxunM0ogl30CueJ76:b-h8sp08) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/BUILD.bazel#L133)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit TODO may also apply to `internal = True` above.

Consider moving one line up, or to line above `drake_cc_library`? (I guess it may have been shifted to do `buildifier`)
</blockquote></details>

Er, I'm actually confused on what intended visibility is for this.
Is it Drake-private for use only with the driver config applicator, or is it intended for Drake-public?

Could not grok it from overview in linked issue.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 4 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @EricCousineau-TRI and @zachfang)

___
*[`manipulation/util/BUILD.bazel` line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSxI4U-9-Tfl2JxtS2:-NBSydNe0w26Z9bjtTwC:b-b707qi) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/BUILD.bazel#L133)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Er, I'm actually confused on what intended visibility is for this.
Is it Drake-private for use only with the driver config applicator, or is it intended for Drake-public?

Could not grok it from overview in linked issue.
</blockquote></details>

It will be `namespace internal`, i.e., not Stable API.

As to whether the bazel target will be `//visibility:public` vs `//:__subpackages__`?   I don't think it will much matter either way.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: 3 unresolved discussions, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @zachfang)

___
*[`manipulation/util/BUILD.bazel` line 133 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSxI4U-9-Tfl2JxtS2:-NBT51e3EWIxOQkUQ9nn:berxofw) ([raw file](https://github.com/robotlocomotion/drake/blob/82a664c1ce1ea6567b294e9705e71cac6fb2141b/manipulation/util/BUILD.bazel#L133)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It will be `namespace internal`, i.e., not Stable API.

As to whether the bazel target will be `//visibility:public` vs `//:__subpackages__`?   I don't think it will much matter either way.
</blockquote></details>

OK Cool, thanks!

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17865)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @zachfang)

___
*[`manipulation/util/make_arm_controller_model.h` line 15 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSwq_V2LNalUrP7Bz0:-NBUesfb4LGLIjNX-r84:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2ddd4a9c18e9c179fae7e7d36020050312d5f7a4/manipulation/util/make_arm_controller_model.h#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit The phrase "the controller will do inverse dynamics on" may be imprecise from a Drake user's perspective.

Consider something like:
```
the can be used to instantiate a controller system such as `InverseDynamicsController`
```
</blockquote></details>

Done.
___
*[`manipulation/util/make_arm_controller_model.cc` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSWmlS-PtGUXsW_CcQ:-NBUdb5HBQLmQm1F_MWL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ab9d5da15b3547398722ecf0c2b1ea4fecdd14d6/manipulation/util/make_arm_controller_model.cc#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes, I think so.
</blockquote></details>

Done.
___
*[`manipulation/util/make_arm_controller_model.cc` line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17865#-NBSw27O8NSOY6Ou7CYK:-NBUdDXuBR0LobqaFl2o:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2ddd4a9c18e9c179fae7e7d36020050312d5f7a4/manipulation/util/make_arm_controller_model.cc#L110)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Logging to `info` seems noisy. Consider demoting to `debug`.
</blockquote></details>

Done.

**Comment by zachfang** [comment]
Rebased to the latest main branch.

**Pull request merged**
