### PR TITLE
Treat polynomial constraints on affine polynomials as linear constrai…

### PR DESCRIPTION
**Pull request by ggould-tri**
Note that I had to fix a missing include in Constraint.h here (every other use site had already included the relevant file).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2806)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@sammy-tri for feature review.
+@jwnimmer-tri is on-call platform reviewer.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdZdJfoH1mVszh_9aq:167804948)*

**Comment by ggould-tri** [comment]
Okay actually you can ignore my remark about Constraint.h above because somebody already fixed it on head before my PR arrived.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdhaVMWdEE_idVB-Cs:-873059954)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/Optimization.h, line 651 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-KMdk6a-_lmmUtaBnN4e:-KMdk6a0wQDdsuAPd5Xa:907573637) ([raw file](https://github.com/robotlocomotion/drake/blob/62a47746d74f3549828ea2066146337e43db590d/drake/solvers/Optimization.h#L651)):*
> ```objc
>                                linear_constraint_lb,
>                                linear_constraint_ub));
>       AddLinearConstraint(constraint, vars);
> ```

BTW, I guess you could add this as a LinearEqualityConstraint if lb and ub are equal, but I'm not sure it's worth the bother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdkGmApUKDXPnO9gk-:1417088721)*

**Comment by ggould-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/solvers/Optimization.h, line 651 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-KMdk6a-_lmmUtaBnN4e:-KMdlJdmVXVoBTwZdlCC:-1924424760) ([raw file](https://github.com/robotlocomotion/drake/blob/62a47746d74f3549828ea2066146337e43db590d/drake/solvers/Optimization.h#L651)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> BTW, I guess you could add this as a LinearEqualityConstraint if lb and ub are equal, but I'm not sure it's worth the bother.
</details>
Hm, that could get a bunch of problems into `kLinearSystemSolverCapabilities` so it is almost certainly worth it.  Update to follow shortly!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806)*

**Comment by sammy-tri** [comment]
:lgtm_cancel: un-lgtm'ing since update is expected...

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdm-5yc_R6l7sJQf_o:-1299520162)*

**Comment by jwnimmer-tri** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/Optimization.h, line 640 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-KMdlwduL_n10N4c2WAq:-KMdlwdvSXQIJR4U8Jf0:-1553605116) ([raw file](https://github.com/robotlocomotion/drake/blob/62a47746d74f3549828ea2066146337e43db590d/drake/solvers/Optimization.h#L640)):*
> ```objc
>                                      term_var) -
>                            poly_vars.begin());
>             DRAKE_ASSERT(var_num < (int)poly_vars.size());
> ```

C-style casting is verboten by cppguide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806)*

**Comment by ggould-tri** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/Optimization.h, line 640 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-KMdlwduL_n10N4c2WAq:-KMdpEt6TU-y80r2dyQo:-1794838984) ([raw file](https://github.com/robotlocomotion/drake/blob/62a47746d74f3549828ea2066146337e43db590d/drake/solvers/Optimization.h#L640)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> C-style casting is verboten by cppguide.
</details>
Ouch.  Yup.

---

*[drake/solvers/Optimization.h, line 651 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-KMdk6a-_lmmUtaBnN4e:-KMdqCCFDeumeMkaoSJ6:-1541529102) ([raw file](https://github.com/robotlocomotion/drake/blob/62a47746d74f3549828ea2066146337e43db590d/drake/solvers/Optimization.h#L651)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Hm, that could get a bunch of problems into `kLinearSystemSolverCapabilities` so it is almost certainly worth it.  Update to follow shortly!
</details>
Huh.  TIL:  The least-squares solver is actually slower than IpOpt, so this change is a performance regression (75% worse for SpringMassIdentification!).  It's still a conceptual improvement, though -- if we ever optimize solver choice we can fix it then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdr9U_s7tUbFCqQSKR:1417088721)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2806#-:-KMdrlLRqvGQ5bQaq3VK:1417088721)*

**Pull request merged**
