### PR TITLE
[C-IRIS] Fix a problem when generating rationals for polytope on one side of plane

### PR DESCRIPTION
**Pull request by hongkai-dai**
1. When the geometry on the other side of the plane is not a polytope, then we can't use a'*x+b>=1 formulation for the polytope geometry, instead we should use the one with the Chebyshev center.

2. Add a'*p_AC+b >= 0.5r where C is the chebyshev center to the formulation to prevent trivial solution a = 0, b=0.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please. No rush, hope you have a great holiday.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494#-:-NK6DyJl0V5tDaQmqZ98:b-qs6k1g)* status: LGTM missing from assignee AlexandreAmice, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
It seems to me that carrying around the `a'x+b>=1` formulation is rather unnecessary and complicates the code a good bit. The other formulation is more flexible and almost no increased cost. Should we just remove it completely?

Otherwise :lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494#-:-NKEHjIH21eTqp3c7veu:bv2ywto)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKEIdpMCkmMcauR04lN:b-wuufcm) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
> ```cpp
>   // where C is the Chebyshev center of the polytope, and r is the distance
>   // from C to the polytope boundary. Note that in the condition
>   // aᵀ*p_AC+b ≥ 0.5r (or ≤ -0.5r), in the right hand side we can use any
> ```

I think this part of the comment might be more confusing than helpful. 



_Code quote:_
```cpp
  // from C to the polytope boundary. Note that in the condition
  // aᵀ*p_AC+b ≥ 0.5r (or ≤ -0.5r), in the right hand side we can use any
  // strictly positive scalar <= r. We choose 0.5r here.
```
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 920 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKELhrtDyaoA6sYRccx:-NKELhrtDyaoA6sYRccy:b-4kzktt) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L920)):*
> ```cpp
>                   ignored_collision_pairs.size());
>     EXPECT_TRUE(is_success);
>     // Check the separating plane does separates the geometries.
> ```

nit typo: Check that the separating plane does **separate** the geometries.

**Review by hongkai-dai — COMMENTED** [review]
I kept `a'x+b >= ` for two reasons

1. I want to keep the WAFR formulation as a sanity check, that this new implementation can reproduce the WAFR result.
2. The formulation a' * p_AV + b >= margin, a' * p_AC + b >= radius needs to verify num_vertices + 1 rationals, where the extra 1 is on the Chebyshev center p_AC. The formulation a' * p_AV + b >= 1 only need num_vertices rationals. So it has a slightly smaller size. 

I think in the paper we can use the formulation with the Chebyshev center which is very general. In the code, I would like to test them on more complicated problems (like IIWA with shelf) to understand better on the pros and cons of each formulation.

I can remove the a'x+b>=1 formulation later, if we decide the other formulation performs better on a variety of examples.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494#-:-NKEUJsCBevGFOwWYUtw:botvbmt)* status: 1 unresolved discussion, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKETxgzCKq3aisDwYYz:bicfx5y) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this part of the comment might be more confusing than helpful. 
</blockquote></details>

Done. I re-worded this part.
___
*[`geometry/optimization/dev/test/cspace_free_polytope_test.cc` line 920 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKELhrtDyaoA6sYRccx:-NKEU6qnCwM8kR7pGnyR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/test/cspace_free_polytope_test.cc#L920)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit typo: Check that the separating plane does **separate** the geometries.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
Sounds good to me. I don't believe you have actually pushed anything new yet.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494#-:-NKEYvO4D0W_cMI4F_nn:b-ku4w8v)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKEYmOs1fH59GuOOvuL:by8pr4n) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I re-worded this part.
</blockquote></details>

I don't see a change?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494)* status: 2 unresolved discussions, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKEd80UCG9WrzezqWYL:bhl5yb4) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

Could you check if you are reviewing the newest revision? Here is the screenshot that shows the difference between r1 and r2

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKEe3PU82suolBuhUNO:bfjafph) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you check if you are reviewing the newest revision? Here is the screenshot that shows the difference between r1 and r2


</blockquote></details>

nit: you say or twice in `(or or ≤ -0.5r)`

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494)* status: missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/dev/collision_geometry.cc` line 122 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18494#-NKEIdpMCkmMcauR04lM:-NKEf0ib68AVEm60rdth:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4489e0f085d426f468ac6d34baf9ca2f1e219b63/geometry/optimization/dev/collision_geometry.cc#L122)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: you say or twice in `(or or ≤ -0.5r)`
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18494#-:-NKEhPI2Cz9WE4pOSbh5:bnfp4nl)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
