### PR TITLE
rgbd_camera: Teach RgbdCamera to take different image sizes 

### LINKED ISSUE #8123: RgbdCamera, RgbdCameraDiscerte: Use (named) parameter structures
`RgbdCamera` and `RgbdCameraDiscrete` have some numeric / boolean parameters, some of which have default values.

To ensure that these values explicitly have context that is clear to users, named parameter structs could be used (per [Style Guide](http://drake.mit.edu/styleguide/cppguide.html#Implementation_Comments)).

This should resolve the concerns expressed in [this comment](https://github.com/robotlocomotion/drake/pull/8119#issuecomment-367161777).

\cc @kunimatsu-tri @jwnimmer-tri @ggould-tri

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Checks box 1 of #8850.

This just appends the `width` and `height `arguments, prioritizing backwards compatibility and getting it done. My next step is to resolve #8123, and ultimately deprecate these overly coupled constructors.

\cc @naveenoid

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@kunimatsu-tri for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852#-:-LD8apAVBohaXwh2svC2:b-1actl4)*

**Comment by EricCousineau-TRI** [comment]
Build failures on Jenkins were a tad cryptic (for commit 52cab0e); not even the full console output yields useful info? Some indicate `git clone` issues, some CDash things indicate no failures (maybe just due to staleness) - but the Console Output indicates failures without much description, and the matlab builds indicate a segfault but on a `mkdir` command? (`.../drake_cxx_python-mkdir] Segmentation fault (core dumped)`)
I'm still not sure if this is due to an issue I introduced, or if the build nodes went rogue on a bad mount / out of disk space issue.
\cc @BetsyMcPhail @jamiesnape Any ideas on these?
(Note: If the issue was due to some server flake and goes away with a retest, I wouldn't say it's a huge priority just yet.)

I was able to run this without a segfault on my machine for `clang: { -c fastbuild, -c dbg }` (testing `gcc-5 -c dbg` now).

@drake-jenkins-bot retest this please

**Comment by kunimatsu-tri** [comment]
Thanks for making this change!

:lgtm: besides CI and a few super minor BTW comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8rgWa785m5YTMcxqJ:-LD8rgWa785m5YTMcxqK:b-tp7awf) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L56)):*
> ```cpp
> constexpr Size kSizeVga = {
>     RenderingConfig::kDefaultWidth, RenderingConfig::kDefaultHeight};
> constexpr Size kSizeHdtv = {1280, 720};
> ```

BTW, nit `Hd720` might be better than `Hdtv` since there exists `Hd1080` as well.
fyi: http://www.reinmedical.com/en/knowledge-technology/monitor-resolutions-overview.html

---

*[systems/sensors/test/rgbd_camera_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8t6Ue7I6Ez9Ncn53s:-LD8t6Ue7I6Ez9Ncn53t:buatsfr) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L114)):*
> ```cpp
> 
>   // Verify that we can construct specifying a different width and hegiht.
>   RgbdCamera fixed_camera_hdtv(
> ```

BTW, `hd720` or just `hd` is ok to me.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8tGXvCDMCAqgNnSjI:-LD8tGXvCDMCAqgNnSjJ:b-dgrt54) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L121)):*
> ```cpp
>   Verify(fixed_camera_hdtv, kSizeHdtv);
> 
>   RgbdCamera movable_camera_hdtv(
> ```

BTW, ditto.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852#-:-LD8ulTrBq4B2M36lPvQ:b-1w85i3)*

**Comment by BetsyMcPhail** [comment]
I'm not sure to the root cause of the CI issues but looked into why CDash wasn't reporting errors.

For a few jobs ([example](https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-bazel-experimental/12916/console)), there was an error `'Server terminated abruptly (error code: 14, error message: '', log file: '/home/ubuntu/workspace/linux-xenial-gcc-bazel-experimental/_bazel_ubuntu/7d79f863c59b67ba7a1ab1641300f288/server/jvm.out')'`.  This error is outside the scope of what Bazel reports in its output files, so CDash didn't have any information about the error. CDash does [report](https://drake-cdash.csail.mit.edu/index.php?project=Drake&showfilters=1&filtercount=2&showfilters=1&filtercombine=and&field1=label&compare1=61&value1=jenkins-linux-xenial-gcc-bazel-experimental-release-12916&field2=buildstarttime&compare2=84&value2=now) 0's for number of tests failed and passed but this isn't immediately obvious when the row is still green.

**Comment by EricCousineau-TRI** [comment]
Gotcha, thank you for looking into that! Would it be possible to flag the table cell as red if 0 tests also passed?

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8rgWa785m5YTMcxqJ:-LDCRFw08MHhHiHZTvQ1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L56)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, nit `Hd720` might be better than `Hdtv` since there exists `Hd1080` as well.
fyi: http://www.reinmedical.com/en/knowledge-technology/monitor-resolutions-overview.html
</blockquote></details>

Done.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8t6Ue7I6Ez9Ncn53s:-LDCRGPy6spviEPVR6GV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L114)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, `hd720` or just `hd` is ok to me.
</blockquote></details>

Done.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 121 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LD8tGXvCDMCAqgNnSjI:-LDCRGdtE7MmJvJ_vEQD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/52cab0e098310c5ac653cab9904b10e7c668d0df/systems/sensors/test/rgbd_camera_test.cc#L121)):*
<details><summary><i>Previously, kunimatsu-tri (Kunimatsu Hashimoto) wrote…</i></summary><blockquote>

BTW, ditto.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852#-:-LDCRKrN4Cj-llBdjHRu:b-axn75)*

**Comment by kunimatsu-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852)*

**Comment by EricCousineau-TRI** [comment]
+@seancurtis-tri for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852#-:-LDD8BmV7uzlIrtg7NbW:btfqah9)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: With one typo.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LDDUoou6YlxuY4UnEyg:-LDDUoou6YlxuY4UnEyh:b-xf024x) ([raw file](https://github.com/robotlocomotion/drake/blob/9ef822851d995a4e41f70683eb2dcded43185d31/systems/sensors/test/rgbd_camera_test.cc#L113)):*
> ```cpp
>   EXPECT_NO_THROW(movable_camera.frame());
> 
>   // Verify that we can construct specifying a different width and hegiht.
> ```

BTW s/hegiht/height

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852#-:-LDDVKbED_qCUPy2Om4P:byjfdlx)*

**Comment by EricCousineau-TRI** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/test/rgbd_camera_test.cc, line 113 at r2](https://reviewable.io/reviews/robotlocomotion/drake/8852#-LDDUoou6YlxuY4UnEyg:-LDDX8FrDdvTldmPL-jB:b-qsx7uj) ([raw file](https://github.com/robotlocomotion/drake/blob/9ef822851d995a4e41f70683eb2dcded43185d31/systems/sensors/test/rgbd_camera_test.cc#L113)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW s/hegiht/height
</blockquote></details>

Done. Oops!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8852)*

**Pull request merged**
