### PR TITLE
Also explicitly remove python-lldb-4.0

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9880)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-cmake-experimental please

**Comment by jamiesnape** [comment]
This is no-op for the build. I just need the provisioning script to run and the CMake build is the quickest to finish.

**Comment by sherm1** [comment]
@jamiesnape this didn't fix the problem for me. But @sammy-tri's recipe worked:
```
apt remove python-lldb-4.0 lldb-4.0 liblldb-4.0-dev lldb-6.0 liblldb-4.0
```

**Comment by jamiesnape** [comment]
Well, we cannot uninstall lldb-6.0.

**Comment by jwnimmer-tri** [comment]
@sherm1 Once you've experienced the problem, then yes the `apt` command to recover is a larger removal than what the install_prereqs change does in this PR.  However, if you start from a _working_ system with last month's package list, then the tweak in this PR should be enough to get to the other side successfully.

**Comment by sherm1** [comment]
OK. I can confirm that I had no trouble with this on my Puget workstation, just my laptop with an older Ubuntu installation.

**Pull request merged**
