### PR TITLE
Add missing dependency pygame for xenial

### PR DESCRIPTION
**Pull request by stonier**
Also some trivial gitignores for eclipse project files.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5528)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot ok to test please

**Comment by david-german-tri** [comment]
Our ordinary CI builds don't test the Xenial install script, so let's ask Jenkins to run a special build that does.

@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by david-german-tri** [comment]
:lgtm: once unprovisioned build passes

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5528#-:-KfNzLYlyLHfF2zUH29O:b65b2jo)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5528#-KfO-FJtGNvCfmuiCsB4:-KfO-FJuoM0VLpjFwnzd:bhgqtw7) ([raw file](https://github.com/robotlocomotion/drake/blob/92ea3e9b76af9fc5102ff4691ed9d35eb641ac62/.gitignore#L64)):*
> ```
> .cproject
> .project
> .settings
> ```

BTW Should these have a leading `/` so that they _only_ apply in the root directory?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5528#-:-KfO-I_QfvS1xBBBbF8L:bnfp4nl)*

**Comment by stonier** [comment]
*[.gitignore, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5528#-KfO-FJtGNvCfmuiCsB4:-KfOsefcNgxKBz-HCsgU:bnx9tvn) ([raw file](https://github.com/robotlocomotion/drake/blob/92ea3e9b76af9fc5102ff4691ed9d35eb641ac62/.gitignore#L64)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should these have a leading `/` so that they _only_ apply in the root directory?
</blockquote></details>

It would be quite unusual to have a mixed policy for such a thing inside a repository and despite the generic nature of the names, I've yet to run into a use case which also uses the same. We can easily handle it retroactively if that should ever happen, or we can drop them, @david-german-tri is now pointing me at CLion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5528)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5528#-KfO-FJtGNvCfmuiCsB4:-KfR0qkBSX7pbB1iTNz3:buvntwy) ([raw file](https://github.com/robotlocomotion/drake/blob/92ea3e9b76af9fc5102ff4691ed9d35eb641ac62/.gitignore#L64)):*
<details><summary><i>Previously, stonier (Daniel Stonier) wrote…</i></summary><blockquote>

It would be quite unusual to have a mixed policy for such a thing inside a repository and despite the generic nature of the names, I've yet to run into a use case which also uses the same. We can easily handle it retroactively if that should ever happen, or we can drop them, @david-german-tri is now pointing me at CLion.
</blockquote></details>

Well, this entire file is awfully bitrotted so I guess this is no worse.  I'll mark myself resolved, and I'll plan to clean up the whole file in a later PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5528)*

**Pull request merged**
