### PR TITLE
Create methods for relative spatial acceleration to parallel spatial velocity.

### PR DESCRIPTION
**Pull request by mitiguy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Feature checkpoint.

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N0hYyV48EucNX1FelWN:bvpqlh3)* status: 8 unresolved discussions, LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy and @sherm1)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hTa3EEiH0mcaFPPB1:-N0hTa3EEiH0mcaFPPB2:b31ewsb) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L314)):*
> ```cpp
> 
>   // Verify that the calculation of separation speed (1ˢᵗ time-derivative
>   // of distance) between Ho (frame H's origin) and L3o (frame L3's origin) can
> ```

nit: consider "separation distance" to make the connection clearer. Then we have separation distance/speed/acceleration.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hYdoF0H8UPrCyxlrU:-N0hYdoF0H8UPrCyxlrV:bswrije) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L488)):*
> ```cpp
>   const Frame<double>& frame_L3 = link3.body_frame();
>   const Frame<double>& frame_W = plant_->world_frame();
>   const SpatialAcceleration<double> A_L3_HH_W =
> ```

minor: can you add a check that frame L3's velocity & acceleration are non-zero? That seems important for these tests to be dispositive.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 494 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hU3HECPG1cfkTnNzt:-N0hU3HECPG1cfkTnNzu:b-6tcvx2) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L494)):*
> ```cpp
>       A_L3_HH_W.get_coeffs(), Vector6<double>::Zero(),
>       kTolerance, MatrixCompareType::relative));
> ```

nit: extra blank line
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 496 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hUACY2kHdBfUCOQQF:-N0hUACY2kHdBfUCOQQG:b-2rq71a) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L496)):*
> ```cpp
> 
> 
>   // Verify that relative spatial velocity is the same as absolute spatial if
> ```

typos: velocity -> acceleration, and absolute spatial -> absolute spatial acceleration
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 511 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hUla-0EfeAUyf4Er-:-N0hUla-0EfeAUyf4Er0:bpb3myv) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L511)):*
> ```cpp
>       frame_H.CalcRelativeSpatialAcceleration(*context_, frame_L3, frame_L3,
>           frame_W);
>   const SpatialAcceleration<double> A_L3_L3H_W_expected =
> ```

nit: this name is inconsistent with the previous test where you used A_WH_W. Why not call this one A_L3H_W ?
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 584 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hWSRn3rFEm9hrvf1r:-N0hWSRn3rFEm9hrvf1s:b-5y15vm) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L584)):*
> ```cpp
>   const Vector3<double> cross_product_term = w_WL3_W.cross(w_L3H_W);
>   EXPECT_TRUE(CompareMatrices(DtW_w_L3H_W, alpha_L3H_W + cross_product_term,
>       kTolerance, MatrixCompareType::relative));
> ```

BTW Cool! I like those two tests.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 589 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hWhsBELbjuFV4YVbD:-N0hWhsBELbjuFV4YVbE:b-gglsjm) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L589)):*
> ```cpp
>   // that the rotational part of frame H's spatial acceleration relative to
>   // frame E measured in the world frame W is zero and verify the translational
>   // part is equal to α_WE x p_EoH + ω_WE x (ω_WE x p_EoHo). This is proved by:
> ```

nit p_EoH -> p_EoHo (or both could be p_EH)
(also below)
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 608 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hX7H5CYr2uYRBSIFZ:-N0hX7H5CYr2uYRBSIF_:b-2e5pxo) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L608)):*
> ```cpp
> 
>   // Verify that the calculation of separation acceleration (2ⁿᵈ time-derivative
>   // of distance) between Ho (frame H's origin) and L3o (frame L3's origin) can
> ```

BTW distance -> separation distance?
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 614 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hXnHKE24ePKNAdVA1:-N0hXnHKE24ePKNAdVA2:b37of9p) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L614)):*
> ```cpp
>   //                           For professional engineers and scientists,"
>   //                           Prodigy Press, Sunnyvale CA, 2017.
>   //                           Available at www.MotionGenesis.com
> ```

BTW consider adding a chapter or section name, ideally one that will likely keep the same name in later editions.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 639 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hY4c02uL8yeMBRG1c:-N0hY4c02uL8yeMBRG1d:b-sjtqib) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L639)):*
> ```cpp
>   const Vector3<double> v_L3_L3H_W = frame_H
>           .CalcRelativeSpatialVelocity(*context_, frame_L3, frame_L3, frame_W)
>           .translational();
> ```

BTW should indent 4 spaces for continuation lines
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hYtNR8_7lZ2Y5FH0d:-N0hYtNR8_7lZ2Y5FH0e:b-qyzn5f) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L643)):*
> ```cpp
>   const double separation_acceleration2 = a_L3_L3H_W.dot(u_L3oHo_W) +
>       1.0/distance * (v_L3_L3H_W_magSquared - separation_speed_squared);
>   EXPECT_NEAR(separation_acceleration1, separation_acceleration2, kTolerance);
> ```

BTW Whew! Awesome.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong:
The new methods and doc came out very nicely! Great tests too.
+@jwnimmer-tri for platform review per rotation please (Thursday)

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N0ha6bPAV1IH9VnEh8T:b-hd3c2y)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mitiguy)

___
*[`multibody/tree/frame.h` line 505 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hZEeh8jC4TSFHpYVT:-N0hZEeh8jC4TSFHpYVU:b-uet0tw) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L505)):*
> ```objc
>   /// @return A_W_BC_W = A_WC_W - A_WB_W, frame C's spatial acceleration
>   /// relative to frame B, measured and expressed in the world frame W. In
>   /// general, A_W_BC = DtW(V_W_BC), the time-derivative in the world frame W of
> ```

minor: add a blank line before "In general, ..." That way the long explanation won't come out as part of Doxygen's `@return` description, which should be short.
___
*[`multibody/tree/frame.h` line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0h_NAl5NxGUUujPDza:-N0h_NAl5NxGUUujPDzb:bsdp375) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L538)):*
> ```objc
>   /// @return A_M_BC_E = A_MC_E - A_MB_E, frame C's spatial acceleration
>   /// relative to frame B, measured in frame M, expressed in frame E.
>   /// In general, A_M_BC = DtW(V_M_BC), the time-derivative in frame M of
> ```

minor: insert a blank line to separate this from the `@return` doc.
___
*[`multibody/tree/frame.h` line 552 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0h_kUh6ZRfRgps1R5R:-N0h_kUh6ZRfRgps1R5S:b-6dllkf) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L552)):*
> ```objc
>   /// Bo and Co can be done with relative translational acceleration, but this
>   /// calculation does not depend on the measured-in-frame, hence in this case,
>   /// consider CalcRelativeSpatialAccelerationInWorld().
> ```

minor: add "since it is faster."

**Review by jwnimmer-tri — COMMENTED** [review]
FYI I plan to wait until the open discussions are resolved before starting.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N0i4ivp9oRTfpcXEKlC:bjzx9c6)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @mitiguy)

**Review by mitiguy — COMMENTED** [review]
@sherm1 ready for another look.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N16d3aL9ao27In37N5i:bnzb9pb)* status: LGTM missing from assignee jwnimmer-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 314 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hTa3EEiH0mcaFPPB1:-N0muOkL2CkOhmDx5bHr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L314)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: consider "separation distance" to make the connection clearer. Then we have separation distance/speed/acceleration.
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 488 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hYdoF0H8UPrCyxlrU:-N0n1FwVBQop4Uz6yAM-:bu3udpn) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L488)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: can you add a check that frame L3's velocity & acceleration are non-zero? That seems important for these tests to be dispositive.
</blockquote></details>

Done.   See a few lines below.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 494 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hU3HECPG1cfkTnNzt:-N0n1k115Jm-HhkajckW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L494)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: extra blank line
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 496 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hUACY2kHdBfUCOQQF:-N0n22A_CdrPEVSc3SgK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L496)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typos: velocity -> acceleration, and absolute spatial -> absolute spatial acceleration
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 511 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hUla-0EfeAUyf4Er-:-N0n2mU41O-0UNNR_1GG:b1355it) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L511)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this name is inconsistent with the previous test where you used A_WH_W. Why not call this one A_L3H_W ?
</blockquote></details>

Done.  Bonus: I can use the A_L3H_W that was defined previously.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 584 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hWSRn3rFEm9hrvf1r:-N0n2ofJ3kNvaMQgIBZO:b-dqvnz4) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L584)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Cool! I like those two tests.
</blockquote></details>

Thank you Sherm :)
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 589 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hWhsBELbjuFV4YVbD:-N0n329M-iyMXQpDF9as:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L589)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit p_EoH -> p_EoHo (or both could be p_EH)
(also below)
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 608 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hX7H5CYr2uYRBSIFZ:-N0n3Wo86WxppfE68da5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L608)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW distance -> separation distance?
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 614 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hXnHKE24ePKNAdVA1:-N0n4dMi-eK5iCgmPYhh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L614)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider adding a chapter or section name, ideally one that will likely keep the same name in later editions.
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 639 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hY4c02uL8yeMBRG1c:-N0n5789-P7-3dLka2n1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L639)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW should indent 4 spaces for continuation lines
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 643 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hYtNR8_7lZ2Y5FH0d:-N0n58EE75vfNt6w9ZtZ:b-b45h3q) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/plant/test/frame_kinematics_test.cc#L643)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Whew! Awesome.
</blockquote></details>

Marathon test!
___
*[`multibody/tree/frame.h` line 505 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0hZEeh8jC4TSFHpYVT:-N0n6GYm9noFKADTB5qh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L505)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: add a blank line before "In general, ..." That way the long explanation won't come out as part of Doxygen's `@return` description, which should be short.
</blockquote></details>

Done.
___
*[`multibody/tree/frame.h` line 538 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0h_NAl5NxGUUujPDza:-N0n6MPZ88nXqg3ibtH7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L538)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: insert a blank line to separate this from the `@return` doc.
</blockquote></details>

Done.
___
*[`multibody/tree/frame.h` line 552 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N0h_kUh6ZRfRgps1R5R:-N0n6T6Q9ecJjrVEC-TY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb347b84af3ee1d9af0d6f63769346debad8bc80/multibody/tree/frame.h#L552)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: add "since it is faster."
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N16tczR4l1SKtJwcNLq:b-vtj4vo)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 656 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16tVLRD2UdkZijWMmE:-N16tVLS8jUcNRqGKkM4:bpmluqz) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L656)):*
> ```cpp
>   const double v_L3_L3H_W_magSquared = v_L3_L3H_W.dot(v_L3_L3H_W);
>   const double separation_acceleration2 = a_L3_L3H_W.dot(u_L3oHo_W) +
>       1.0/distance * (v_L3_L3H_W_magSquared - separation_speed_squared);
> ```

nit It might be slightly easier to read this test stanza vs the prior one if the `+ 1.0 / ...` whitespace formatting were uniform between this line and the one 8 lines prior.
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 71 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16rLiG2VO2ceMq08sP:-N16rLiH4BdMAoNXiJcT:be5oox2) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/kuka_iiwa_model_tests.h#L71)):*
> ```objc
>   // even if the state stores a non-unit quaternion.
>   void SetArbitraryConfigurationAndMotion(bool unit_quaternion = true) {
>     // Get a set of joint angles and angular rates that avoids in-plane motion.
> ```

nit Since several tests rely on the "non in-plane" behavior of `GetArbitraryJointAnglesAndRates`, the "not in-plane" promise should be an API comment (specification) atop the `GetArbitraryJointAnglesAndRates()` function declaration.

In that case, one could also imagine not copy-pasting the same specification at every call site, though there is a valid case for adding such a reminder if it aids the reader in following along.



_Code quote:_
```objc
 avoids in-plane motion
```

**Comment by jwnimmer-tri** [comment]
Actually also +(release notes: yes) not -(release notes: none) ... this is a new feature (a new, public API).

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 513 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N19qUzc2IqRCy5fGdLs:-N19qUzc2IqRCy5fGdLt:b-t1cjuk) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L513)):*
> ```cpp
>   EXPECT_FALSE(CompareMatrices(
>       A_L3H_W.translational(), Vector3<double>::Zero(),
>       kTolerance, MatrixCompareType::relative));
> ```

BTW when comparing against Zero, better to use an absolute tolerance.

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 513 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N19qUzc2IqRCy5fGdLs:-N1AKOGHCFBrI_8P-Wwe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L513)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW when comparing against Zero, better to use an absolute tolerance.
</blockquote></details>

Done.
___
*[`multibody/plant/test/frame_kinematics_test.cc` line 656 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16tVLRD2UdkZijWMmE:-N1AKYKp4hZKMkOPGW9M:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L656)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It might be slightly easier to read this test stanza vs the prior one if the `+ 1.0 / ...` whitespace formatting were uniform between this line and the one 8 lines prior.
</blockquote></details>

Done.
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 71 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16rLiG2VO2ceMq08sP:-N1ANKSXDaFXDvt335h9:b-896fjx) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/kuka_iiwa_model_tests.h#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Since several tests rely on the "non in-plane" behavior of `GetArbitraryJointAnglesAndRates`, the "not in-plane" promise should be an API comment (specification) atop the `GetArbitraryJointAnglesAndRates()` function declaration.

In that case, one could also imagine not copy-pasting the same specification at every call site, though there is a valid case for adding such a reminder if it aids the reader in following along.
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 656 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16tVLRD2UdkZijWMmE:-N1AgOOD4pWYaPyY4mFG:b-10eo1d) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L656)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(The `+` is still on different lines, but _shrug_.)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 68 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N1B4ogK3s58DuV0024M:-N1B4ogK3s58DuV0024N:b-d4yn4f) ([raw file](https://github.com/robotlocomotion/drake/blob/f9d61b417c30200d9045229f8d78e0b8657a97b4/multibody/plant/test/kuka_iiwa_model_tests.h#L68)):*
> ```objc
>   // Sets the configuration and motion for this kuka iiwa's context with
>   // non-zero joint angles and angular rates that avoid in-plane motion.
>   // param[in] unit_quaternion true means the quaternion for the kuka iiwa's
> ```

nit: use `@param` here as though it was a Doxygen command
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 70 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N1B53oKBMCDYTTl2NPW:-N1B53oKBMCDYTTl2NPX:bci5swv) ([raw file](https://github.com/robotlocomotion/drake/blob/f9d61b417c30200d9045229f8d78e0b8657a97b4/multibody/plant/test/kuka_iiwa_model_tests.h#L70)):*
> ```objc
>   // param[in] unit_quaternion true means the quaternion for the kuka iiwa's
>   // free floating base is normalized whereas false means the quaternion is not
>   // normalized. A value of false helps verify the computation of Jacobians with
> ```

nit: we don't normally document both true and false since that's normally redundant (and it is redundant here since the quaternion is either normalized or not)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17014#-:-N1BWMtI1N-XsS3uGZxd:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri and @sherm1)

___
*[`multibody/plant/test/frame_kinematics_test.cc` line 656 at r4](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N16tVLRD2UdkZijWMmE:-N1AuWGXETbR_ELExaS1:b-ye43nb) ([raw file](https://github.com/robotlocomotion/drake/blob/93d7381317374433756b29b1c81ce47fda6aa5d1/multibody/plant/test/frame_kinematics_test.cc#L656)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(The `+` is still on different lines, but _shrug_.)
</blockquote></details>

Done.  Sorry I missed the different lines.
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 68 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N1B4ogK3s58DuV0024M:-N1BOhlI1C73bKHZAD46:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9d61b417c30200d9045229f8d78e0b8657a97b4/multibody/plant/test/kuka_iiwa_model_tests.h#L68)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: use `@param` here as though it was a Doxygen command
</blockquote></details>

Done.
___
*[`multibody/plant/test/kuka_iiwa_model_tests.h` line 70 at r6](https://reviewable.io/reviews/robotlocomotion/drake/17014#-N1B53oKBMCDYTTl2NPW:-N1BOivK7vYKwkLRB6bT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f9d61b417c30200d9045229f8d78e0b8657a97b4/multibody/plant/test/kuka_iiwa_model_tests.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: we don't normally document both true and false since that's normally redundant (and it is redundant here since the quaternion is either normalized or not)
</blockquote></details>

Done.

**Pull request merged**
