### PR TITLE
Update supported versions of Bazel and CMake on macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8079)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature and platform review.

**Comment by jwnimmer-tri** [comment]
:lgtm:

\CC @soonho-tri

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8079#-L5P4SHFYGARf89XqunC:-L5P4SHFYGARf89XqunD:buwdlcl) ([raw file](https://github.com/robotlocomotion/drake/blob/3f2893b57df2c5d821794e803d66dbc66b5e0e98/CMakeLists.txt#L18)):*
> ```CMake
> 
> # TODO(jamiesnape): Update to 0.10.1 after #8016 merges.
> find_package(Bazel 0.9.0 MODULE REQUIRED)
> ```

Still keep 0.6.1 here for Ubuntu for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8079#-:-L5P4cUcahNwu58Sgor8:bgk1jgr)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 18 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8079#-L5P4SHFYGARf89XqunC:-L5P4yjzhrqwwnmXwZTA:b-983m7e) ([raw file](https://github.com/robotlocomotion/drake/blob/3f2893b57df2c5d821794e803d66dbc66b5e0e98/CMakeLists.txt#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Still keep 0.6.1 here for Ubuntu for now?
</blockquote></details>

Oh, I can't read.  Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8079)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8079#-:-L5P6QO2Xsoql5ec7UYM:bnfp4nl)*

**Pull request merged**
