### PR TITLE
SpatialInertia::MakeFromCentralInertia() immediately checks physical validity

### LINKED ISSUE #19544: Unable to parse thin rod via SDFormat
### What happened?

The SDFormat parser fails to parse a valid link inertia.

This demo program:
```python
from pydrake.all import *

def main():
    model = """
<?xml version="1.0"?>
<sdf version="1.7">
  <model name="semiacrobot">
    <link name="link1">
      <inertial>
        <pose>0 20 0 0 0 0</pose>
        <mass>1</mass>
        <inertia>
          <ixx>0.083</ixx>
          <iyy>0.083</iyy>
          <izz>0</izz>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyz>0</iyz>
        </inertia>
      </inertial>
    </link>
  </model>
</sdf>
    """
    plant = MultibodyPlant(0)
    Parser(plant).AddModelsFromString(model, ".sdf")

main()
```

... produces this output ...

```
WARNING:drake:<literal-string>.sdf:5: warning: Spatial inertia fails SpatialInertia::IsPhysicallyValid().
 mass = 1.0
 Center of mass = [0.0  20.0  0.0]
 Inertia about point P, I_BP =
[400.083        0        0]
[      0    0.083        0]
[      0        0      400]
 Inertia about center of mass, I_BBcm =
[0.083      0      0]
[    0  0.083      0]
[    0      0      0]
 Principal moments of inertia about Bcm (center of mass) =
[0.0  0.083  0.08300000000002683]
```

... and substitutes a stand-in spherical inertia for the actual thin rod inertia.

The desired outcome is no warnings, and the actual inertia remains intact as given by the user (within a few epsilon, I suppose).

I am not sure whether the parser code is misusing the Multibody API (i.e., a parser bug), or whether the Multibody API has precision-matching problems, or something else.

### Version

v1.17.0

### What operating system are you using?

Ubuntu 22.04

### What installation option are you using?

pip install drake

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mitiguy**
Closes #19544

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)

### CODE REVIEW

**Comment by mitiguy** [comment]
PR [#19581](https://github.com/RobotLocomotion/drake/pull/19581) helps resolves issue [#19544](https://github.com/RobotLocomotion/drake/issues/19544).

**Review by rpoyner-tri — COMMENTED** [review]
Good day, @mitiguy . This PR does not yet have a reviewer assigned. Is it ready for review yet? If yes, then please assign a feature reviewer. If not, then please label it “status: do not review”.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXpfsWz9NjIAhr1klam:byeh1dx)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by mitiguy — COMMENTED** [review]
Feature review +@jwnimmer-tri 
Note: This PR provides the fix you suggested, which is to simply deal with problems with MakeCentralInertia().

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXq08wE1RbVWV8hMPIz:b-wvi4ip)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXqwyoU9-ZdTA5Mmdtu:bnfp4nl)* status: 4 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqrioA5Y-_2b2n4YTN:-NXqrioA5Y-_2b2n4YTO:b-g3zntb) (no related file):*
When I run the test case from the issue #19544 against this code, the test case passes now.  That's a good thing of course, but it makes me wonder why the metadata of this pull request implies that the issue is not completely fixed by this change:

(1) The "PR [#19581](https://github.com/RobotLocomotion/drake/pull/19581) helps resolves issue [#19544](https://github.com/RobotLocomotion/drake/issues/19544)" comment only **mentions** this pull request number in the issue timeline, it does not actually close the issue when the pull request gets merged.  Please read https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to learn about how the "Closes: NNNNN" syntax is intended to be used on GitHub.  In short -- when a PR closes an issue, you need to edit the PR description (the top post of `https://github.com/RobotLocomotion/drake/pull/19581`) to say "closes" -- putting it in a separate comment does not engage the auto-close feature.  (You can also type in "Closes" when creating the pull request, instead of editing later.)

(2) The release notes are marked "none".  Fixing our parsing to provide correct inertia values seems worthy of announcing as bug fix, but maybe not if there are still more related bugs lurking.

Could you clarify for me what work still remains before closing #19544?

If no more work remains, let me know and I can adjust the "Closes" messaging and release notes label.

___
___
*[`multibody/tree/rotational_inertia.h` line 601 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqtxLyDido6wDHAM6l:-NXqtxLyDido6wDHAM6m:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/rotational_inertia.h#L601)):*
> ```objc
>     const T max_possible_inertia_moment = CalcMaximumPossibleMomentOfInertia();
> 
>     // To avoid false negatives for inertias close to zero we use, we also use
> ```

typo



_Suggestion:_
```objc
we also use
```
___
*[`multibody/tree/spatial_inertia.cc` line 462 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXquTp708pmQ3adRCG7:-NXquTp86DmBQi0SoviZ:b-fap7p0) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/spatial_inertia.cc#L462)):*
> ```cpp
>           "Spatial inertia fails SpatialInertia::IsPhysicallyValid().");
>   const T& mass = get_mass();
>   if (!is_nonnegative_finite(mass)) {
> ```

On first reading, this seems like an important bug fix (removing an erroneous mention of zero mass from an error message).  However, if I undo this change, then no unit tests fail.

Either this bug fix needs to have a regression test added, or else it should be withheld from this PR and filed separately (with a test)
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1044 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqutl77sZc9FLaWbIx:-NXqutl77sZc9FLaWbIy:b2gs11g) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/test/spatial_inertia_test.cc#L1044)):*
> ```cpp
>   // test) caused I_BBcm_B's calculated principal moments of inertia to be:
>   // [0.0  20.833333333333712  20.83333333333485] which violated the triangle
>   // inequality by ≈ 1.14E-12.
> ```

This final sentence filled with lots of numbers seems redundant with the overview text already atop the test case. I do not understand why explaining the magnitude of errors in previously-buggy code (or pasting dozens of sig figs of old data) is useful to anyone moving forward.

Ditto below for the similar comments on the rest of the test inputs.



_Suggestion:_
```cpp
  // digits can be lost in the process.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: 4 unresolved discussions, needs at least two assigned reviewers

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqrioA5Y-_2b2n4YTN:-NXrF60N-rYrT59prp3T:b-an27vd) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When I run the test case from the issue #19544 against this code, the test case passes now.  That's a good thing of course, but it makes me wonder why the metadata of this pull request implies that the issue is not completely fixed by this change:

(1) The "PR [#19581](https://github.com/RobotLocomotion/drake/pull/19581) helps resolves issue [#19544](https://github.com/RobotLocomotion/drake/issues/19544)" comment only **mentions** this pull request number in the issue timeline, it does not actually close the issue when the pull request gets merged.  Please read https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to learn about how the "Closes: NNNNN" syntax is intended to be used on GitHub.  In short -- when a PR closes an issue, you need to edit the PR description (the top post of `https://github.com/RobotLocomotion/drake/pull/19581`) to say "closes" -- putting it in a separate comment does not engage the auto-close feature.  (You can also type in "Closes" when creating the pull request, instead of editing later.)

(2) The release notes are marked "none".  Fixing our parsing to provide correct inertia values seems worthy of announcing as bug fix, but maybe not if there are still more related bugs lurking.

Could you clarify for me what work still remains before closing #19544?

If no more work remains, let me know and I can adjust the "Closes" messaging and release notes label.
</blockquote></details>

Ah.  There is still the nerf in a different unit test:

```c++
  // TODO(jwnimmer-tri) Our SDFormat parser erroneously rejects rods that are
  // posed too far away.  We need to skip those test cases for now.
  if (pose.maxCoeff() > 5) {
    drake::log()->info("Skipping test case due to SDFormat parser bug");
    return;
  }
```

How about we delete that code as part of this PR (to help prove that the problem is actually fixed), and have the PR close the issue?

___

**Review by mitiguy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqrioA5Y-_2b2n4YTN:-NXrOWYT2QdgV_3O5lfM:bm3zd6x) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  There is still the nerf in a different unit test:

```c++
  // TODO(jwnimmer-tri) Our SDFormat parser erroneously rejects rods that are
  // posed too far away.  We need to skip those test cases for now.
  if (pose.maxCoeff() > 5) {
    drake::log()->info("Skipping test case due to SDFormat parser bug");
    return;
  }
```

How about we delete that code as part of this PR (to help prove that the problem is actually fixed), and have the PR close the issue?
</blockquote></details>

I am onboard with whatever you think makes sense (closing or not closing #19544) as you deem best.

Tangent: There is still a loss of significant digits for one of the spatial inertia constructors (this is one of the new tests in spatial_inertia_test.cc).   Since MakeFromCentralInertia() has been fixed (which is what is used in parsing SDFormat), the spatial inertia constructor problem should not affect #19544. 

___
___
*[`multibody/tree/rotational_inertia.h` line 601 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqtxLyDido6wDHAM6l:-NXrAj1z4rBARPVtTwrQ:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/rotational_inertia.h#L601)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`multibody/tree/spatial_inertia.cc` line 462 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXquTp708pmQ3adRCG7:-NXrN_csDtngK9lwue9u:bxkr0hn) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/spatial_inertia.cc#L462)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On first reading, this seems like an important bug fix (removing an erroneous mention of zero mass from an error message).  However, if I undo this change, then no unit tests fail.

Either this bug fix needs to have a regression test added, or else it should be withheld from this PR and filed separately (with a test)
</blockquote></details>

I agree, albeit not done yet.  Hmmmm, I need a test case to check the message that is thrown depends on !is_positive_finite() vs. !is_nonnegative_finite().  Will revert to !is_positive_finite() if I cannot dream up a regression test soon.
___
*[`multibody/tree/unit_inertia.h` line 140 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXrQc--A0UuiKIUS_qk:-NXrQc--A0UuiKIUS_ql:bbpbnqi) ([raw file](https://github.com/RobotLocomotion/drake/blob/18cc3623ab9fde40045b5fe00c162071abe5e4c2/multibody/tree/unit_inertia.h#L140)):*
> ```objc
>     return *this;
>   }
> ```

FYI  Opportunistically, the R2 commit fixes typos in unit_inertia.h (I happened to notice them in passing). The old/existing Python bindings and documentation both use an argument named p_BcmQ_E, but the C++ function arguments used an argument named p_BcQ_E.  Hence, the C++ argument p_BcQ_E was updated to p_BcmQ_E.  
___
*[`multibody/tree/test/spatial_inertia_test.cc` line 1044 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqutl77sZc9FLaWbIx:-NXrHw7j7wBtGcwejTc3:b-1jpqku) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/test/spatial_inertia_test.cc#L1044)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This final sentence filled with lots of numbers seems redundant with the overview text already atop the test case. I do not understand why explaining the magnitude of errors in previously-buggy code (or pasting dozens of sig figs of old data) is useful to anyone moving forward.

Ditto below for the similar comments on the rest of the test inputs.
</blockquote></details>

Done (perhaps).  Sig figs for old data removed.  Perhaps it may be helpful to retain information showing how distance² affects violation of triangle inequality?  Alternatively, I can remove this too.  Let me know.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXqrioA5Y-_2b2n4YTN:-NXu7bWA-O2b0NYF7pWF:bjvk6tv) (no related file):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I am onboard with whatever you think makes sense (closing or not closing #19544) as you deem best.

Tangent: There is still a loss of significant digits for one of the spatial inertia constructors (this is one of the new tests in spatial_inertia_test.cc).   Since MakeFromCentralInertia() has been fixed (which is what is used in parsing SDFormat), the spatial inertia constructor problem should not affect #19544. 

</blockquote></details>

My vote is to amend this PR to delete the "if ... return" block quoted above, and to have this PR close the issue.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: 2 unresolved discussions, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 462 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXquTp708pmQ3adRCG7:-NXuXwseCowRdOTp7wd7:brx1mkd) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/spatial_inertia.cc#L462)):*
<details><summary><i>Previously, mitiguy (Mitiguy) wrote…</i></summary><blockquote>

I agree, albeit not done yet.  Hmmmm, I need a test case to check the message that is thrown depends on !is_positive_finite() vs. !is_nonnegative_finite().  Will revert to !is_positive_finite() if I cannot dream up a regression test soon.
</blockquote></details>

Sounds fine.

**Comment by mitiguy** [comment]
Closes [#19544](https://github.com/RobotLocomotion/drake/issues/19544).

**Review by mitiguy — COMMENTED** [review]
Platform review +@EricCousineau-TRI 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXvvHtP15d0u327g613:bvhp85w)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 462 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXquTp708pmQ3adRCG7:-NXvjQFxAmPHdgRn7V95:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/46a70225c75ff415eb31a185e749afe969471cf6/multibody/tree/spatial_inertia.cc#L462)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sounds fine.
</blockquote></details>

Done.

**Comment by EricCousineau-TRI** [comment]
FYI You need to have "Closes" be in the PR overview, not as a comment. I've edited your overview to that effect.

**Comment by EricCousineau-TRI** [comment]
Changes to `release notes: fix` as this is a (great!) user-facing change

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform pending remaining discussion items and minor BTW

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXvz3evBjA-URNEByvs:b-28uieu)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

___
*[`multibody/tree/spatial_inertia.cc` line 443 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXvyJ1d4fj7Rkum-pub:-NXvyJ1d4fj7Rkum-puc:b-8ds2h5) ([raw file](https://github.com/RobotLocomotion/drake/blob/ddd86bbe3ddf823c3d1a2177ff078b6cdcc174e3/multibody/tree/spatial_inertia.cc#L443)):*
> ```cpp
> template <typename T>
> boolean<T> SpatialInertia<T>::IsPhysicallyValid() const {
>   // This spatial inertia is not physically valid if the mass is NaN or if the
> ```

BTW This comment may miss the fact that infinite inertias also aren't covered.
Consider replacing `NaN` with `non-finite`

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Comment by jwnimmer-tri** [comment]
FYI When you choose the final commit message subject for this PR during merge, I'd recommend something more along the lines of  "Fix MakeFromCentralInertia() not to reject valid inputs".  The "immediately check" is an implementation detail mechanism.  The outcome we care about is removing the false negative, not the mechanism.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mitiguy)

**Review by mitiguy — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-:-NXw7gLT8XFiRzBknffe:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[`multibody/tree/spatial_inertia.cc` line 443 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19581#-NXvyJ1d4fj7Rkum-pub:-NXw1xu60G880a5ZlvFG:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ddd86bbe3ddf823c3d1a2177ff078b6cdcc174e3/multibody/tree/spatial_inertia.cc#L443)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW This comment may miss the fact that infinite inertias also aren't covered.
Consider replacing `NaN` with `non-finite`
</blockquote></details>

Done.

**Pull request merged**
