### PR TITLE
Update iris to latest master

### LINKED ISSUE #2771: CI Failure - gcc-linux-matlab - cddlib download error
# Example Logs

https://drake-jenkins.csail.mit.edu/job/experimental/2572/compiler=gcc,label=linux_matlab/consoleFull

# The Error

```
21:13:33 [ 11%] Performing download step (download, verify and extract) for 'cdd_project'
21:13:33 -- downloading...
21:13:33      src='ftp://ftp.ifor.math.ethz.ch/pub/fukuda/cdd/cddlib-094h.tar.gz'
21:13:33      dst='/home/ubuntu/workspace/experimental/06107e1d/externals/iris/pod-build/cdd_project-prefix/src/cddlib-094h.tar.gz'
21:13:33      timeout='none'
21:13:33 CMake Error at cdd_project-stamp/download-cdd_project.cmake:21 (message):
21:13:33   error: downloading
21:13:33   'ftp://ftp.ifor.math.ethz.ch/pub/fukuda/cdd/cddlib-094h.tar.gz' failed
21:13:33 
21:13:33     status_code: 7
21:13:33     status_string: "Couldn't connect to server"
21:13:33     log:   Trying 129.132.145.45...
21:13:33 
21:13:33   connect to 129.132.145.45 port 21 failed: Connection timed out
21:13:33 
21:13:33   Failed to connect to ftp.ifor.math.ethz.ch port 21: Connection timed out
21:13:33 
21:13:33   Closing connection 0
21:13:33 
```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fixes #2771.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3172)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@sammy-tri for all review, please.

**Comment by jwnimmer-tri** [comment]
Here's a link to [the relevant build](https://drake-jenkins.csail.mit.edu/job/experimental/3762/compiler=gcc,label=linux_matlab,type=release/).

**Comment by jwnimmer-tri** [comment]
Sadness...
```
-- Downloading... done
-- extracting...
     src='/home/ubuntu/workspace/experimental/c5b85b52/externals/iris/pod-build/cdd_project-prefix/src/cddlib-094h.tar.gz'
     dst='/home/ubuntu/workspace/experimental/c5b85b52/externals/iris/pod-build/cdd_project-prefix/src/cdd_project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 17%] Performing patch step for 'cdd_project'
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up make[6]: *** [cdd_project-prefix/src/cdd_project-stamp/cdd_project-patch] Error 1
to this was:
--------------------------
|diff -p --exclude=.DS_Store -r cddlib-094h 2/src-gmp/Makefile.in cddlib-094h/src-gmp/Makefile.in
|*** cddlib-094h 2/src-gmp/Makefile.in	2012-03-23 04:51:54.000000000 -0400
|--- cddlib-094h/src-gmp/Makefile.in	2016-02-18 13:37:52.000000000 -0500
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
make[6]: Leaving directory `/home/ubuntu/workspace/experimental/c5b85b52/externals/iris/pod-build'
make[5]: Leaving directory `/home/ubuntu/workspace/experimental/c5b85b52/externals/iris/pod-build'
make[5]: *** [CMakeFiles/cdd_project.dir/all] Error 2
```

I haven't tried to understand or debug this yet.

**Comment by jwnimmer-tri** [comment]
Grasping at straws...
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Comment by jwnimmer-tri** [comment]
Heads up -- now that RobotLocomotion/drake-ci#20 is merged, we shouldn't rely on the pre-merge Jenkins matrix to test this PR.

Also -@sammy-tri because this is broken.

**Comment by jamiesnape** [comment]
I guess I could just patch the tarball to unblock us.

**Comment by jwnimmer-tri** [comment]
I have no opinion.  For my part, I am content to wait and let MIT solve this problem.  TRI can continue merging PRs in the meantime, and if matlab regresses because of it, then MIT can fix that too.

**Comment by jwnimmer-tri** [comment]
@jamiesnape is there a good way to test this with `IRIS` enabled?  Should I edit `drake-ci` to change the `ENV{ghprbPullId}` logic to special-case on 3172?  Or can I (temporarily) edit the superbuild `CMakeLists.txt` in this PR to force IRIS on (and how)?

**Comment by jwnimmer-tri** [comment]
> Or can I (temporarily) edit the superbuild CMakeLists.txt in this PR to force IRIS on (and how)?

This seemed to work locally, so I've pushed it to see what Jenkins thinks.

**Comment by jamiesnape** [comment]
@jwnimmer-tri  You can manually run an experimental build on Jenkins (using the UI not the @drake-jenkins-bot commands).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
> You can manually run an experimental build on Jenkins...

Ah, and that doesn't still set `ghprbPullId`?

**Comment by jamiesnape** [comment]
Only builds triggered by the GitHub pull request builder have `ghprbPullId` set, i.e., builds automatically triggered by updates or comments to a PR. Hence, you do not see the PR number and link in the description of the build on Jenkins once it has completed, nor an :octocat: link on CDash.

**Comment by jwnimmer-tri** [comment]
Test build of this of vanilla master, with IRIS enabled:
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental-matlab/14/

Test build of this PR merged with master, with IRIS enabled:
https://drake-jenkins.csail.mit.edu/view/Experimental/job/linux-gcc-ninja-experimental-matlab/13/

We expect the first one to fail, and the second one to pass.  If (and only if)so, we should merge this PR.

@david-german-tri could you take on all review and merge?

**Comment by jwnimmer-tri** [comment]
Build 14 failed (yay) and build 13 got through the superbuild (yay) so likely this is good-to-go.

**Comment by jwnimmer-tri** [comment]
All green (well, blue).  Ready to merge.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3172#-:-KPTokGc9649OvhdbwXf:bnfp4nl)*

**Pull request merged**
