### PR TITLE
[fem] Integrate PETSc matrix with FemSolver

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This PR contains two commits:

Commit 1: Apply Dirichlet boundary conditions to tangent matrices in PETSc format.
Commit 2: Build and solve tangent matrices in PETSc format in FemSolver when the scalar type is `double`. Fall back to the slow `Eigen::SparseMatrix` tangent matrix for other scalar types.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@joemasterjohn for sole review please, thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306#-:-MsbLFBhCqwe_pBxkPm3:b-58tih5)* status: LGTM missing from assignee joemasterjohn, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @joemasterjohn)

**Review by xuchenhan-tri — COMMENTED** [review]
I incorporated the suggestion about the name change in this PR and added a couple of missing unit tests in `dirichlet_boundary_coundition_test.cc`. PTAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306#-:-MsfmC1j1JyH8MhlKlhl:b-cgocbe)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @joemasterjohn)

___
*[multibody/fixed_fem/dev/dirichlet_boundary_condition.h, line 94 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16306#-MsfDAXDCcO5rCidONHO:-Msfkh6H00mOZkgvFcSg:bxhmwof) ([raw file](https://github.com/robotlocomotion/drake/blob/06a92869eaf541e09849f43606e3e66380b3a40f/multibody/fixed_fem/dev/dirichlet_boundary_condition.h#L94)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

nit: To me, `Bc` looks a little too much like monogram notation and might be a bit confusing. Maybe consider renaming these APIs when this comes out of dev. Having the full "BoundaryConditions" in the API will make searching the doc a bit easier for the uninitiated as well.
</blockquote></details>

Done.

I rolled the change into this PR.
___
*[multibody/fixed_fem/dev/dirichlet_boundary_condition.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16306#-MsfHIooDUTZP0WOlvvu:-MsfksDSE4dF0mKPvMdK:bi64uvo) ([raw file](https://github.com/robotlocomotion/drake/blob/06a92869eaf541e09849f43606e3e66380b3a40f/multibody/fixed_fem/dev/dirichlet_boundary_condition.h#L106)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

BTW: having to do this always annoys me. In C++20 though with the `<ranges>` library you can extract the keys like:

```
auto keys_view = std::views::keys(m);
std::vector<int> keys{ keys_view.begin(), keys_view.end() };
```

No action item or anything, just sharing.
</blockquote></details>

Good to know! Thanks.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @joemasterjohn)

___
*[multibody/fixed_fem/dev/dirichlet_boundary_condition.h, line 106 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16306#-MsfHIooDUTZP0WOlvvu:-MsfoR1o9B2rSp-emdXo:b-xl0yhp) ([raw file](https://github.com/robotlocomotion/drake/blob/06a92869eaf541e09849f43606e3e66380b3a40f/multibody/fixed_fem/dev/dirichlet_boundary_condition.h#L106)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Good to know! Thanks.
</blockquote></details>

TIL -- sweet!

**Review by joemasterjohn — COMMENTED** [review]
Looks good. Thanks for adding the additional tests, I missed that in my first look. 

> Reviewed 3 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306#-:-Msg-Xth7DTq1gl4jKmK:bnwo6rl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Me too. Realized that when changing API names.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16306#-:-Msg0T5i6jDTB5wRzCf7:bj9bm5f)* status: :shipit: complete! all discussions resolved, LGTM from assignee joemasterjohn, exempt from platform review, base commit is latest master (waiting on @xuchenhan-tri)

**Pull request merged**
