### PR TITLE
Fix range-loop-analysis warnings

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates #14085. Gets us clean for now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094)

### CODE REVIEW

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

+@soonho-tri 

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094#-:-MHaGxeOC6NNBup1xuUJ:b-nqdohc)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jamiesnape)

___
*[geometry/proximity/test/obb_test.cc, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHaDoBn9_ljZtT8GNYG:-MHaDoBn9_ljZtT8GNYH:b703mbn) ([raw file](https://github.com/robotlocomotion/drake/blob/34400ac0f9a70ccf6c5245f125428a5c5cce5204/geometry/proximity/test/obb_test.cc#L166)):*
> ```cpp
>     Matrix3d covariance_M = Matrix3d::Zero();
>     Vector3d p_MC(1. / 3., 1. / 3., 1. / 3.);
>     for (const Vector3d& p_MV : std::vector<Vector3d>{
> ```

nit, can we just have `const auto& p_MV : {...}`?

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094)* status: needs at least two assigned reviewers

**Review by soonho-tri — COMMENTED** [review]
+@seancurtis-tri for platform-review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094#-:-MHmbVF50XhsiZgaHI5f:b-9amejk)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
One quick subtlety arises with the `TypeSafeIndex` and `Identifier` changes required by the compiler. See below.

> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094#-:-MHmg_ih7RQh1cOiGpQs:b-omgj0q)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmdMw64EVVPvX1gw3h:-MHmdMw74MYUCKzECuPi:b-g6kyse) (no related file):*
I presume that the warning in question distinguishes between POD and class/struct. For example, in `multiplexer.cc` we [copy a value that is returned by reference](https://github.com/RobotLocomotion/drake/blob/master/systems/primitives/multiplexer.cc#L42-L44), but the type is `int`, so that doesn't need to be corrected. However, for a class (e.g., `TypeSafeIndex` or `Identifier`) which is supposed to be `int`-like, the compiler isn't smart enough to recognize that simply copying it is no worse than taking a reference.

In that case, the documentation of classes [`TypeSafeIndex`](https://github.com/RobotLocomotion/drake/blob/master/common/type_safe_index.h#L64-L66) and ['Identifier'](https://github.com/RobotLocomotion/drake/blob/master/common/identifier.h#L70-L72) is no longer correct. The documentation explicitly requests users to "treat these like ints and const references is a misuse" -- the compiler has made that a lie. I'd recommend a change in both of those files to something like this:

```c++
/// It is the designed intent of this class, that indices derived from this
/// class can be passed and returned by value. Generally, passing indices by
/// const reference should be considered a misuse. The conspicuous exception to
/// this would be in range-loops where the compiler may consider copies an
/// error. So, prefer `for (const IndexType& i : my_indices) { ... }` to
/// `for (const IndexType i : my_indices) { ... }`.
```

(With changes in formatting and `IndexType` --> `IdType` as appropriate to `TypeSafeIndex` vs `Identifier`.) 

Alternatively, is there any way to decorate those types so that the compiler ignores those?

---
___
*[geometry/proximity/test/obb_test.cc, line 166 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmfnfx58JmeRIv_D6v:-MHmfnfx58JmeRIv_D6w:b37kyx6) ([raw file](https://github.com/robotlocomotion/drake/blob/2bab9ffd8b89aee0f411a7ec982de10231b334d3/geometry/proximity/test/obb_test.cc#L166)):*
> ```cpp
>     Matrix3d covariance_M = Matrix3d::Zero();
>     Vector3d p_MC(1. / 3., 1. / 3., 1. / 3.);
>     for (const auto& p_MV :
> ```

BTW Given this is a test, this might be clearer using `Vector3d` (no ampersand) instead of `auto&`. Sure, it comes with a construction cost, but in the test, who cares?

On the other hand, I can equally accept the idea the code kind of *implies* `auto` is `Vector3d` and even though it's not true, it's a harmless lie.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmdMw64EVVPvX1gw3h:-MHmiq1U5vni87UGqw24:b-p58a3i) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I presume that the warning in question distinguishes between POD and class/struct. For example, in `multiplexer.cc` we [copy a value that is returned by reference](https://github.com/RobotLocomotion/drake/blob/master/systems/primitives/multiplexer.cc#L42-L44), but the type is `int`, so that doesn't need to be corrected. However, for a class (e.g., `TypeSafeIndex` or `Identifier`) which is supposed to be `int`-like, the compiler isn't smart enough to recognize that simply copying it is no worse than taking a reference.

In that case, the documentation of classes [`TypeSafeIndex`](https://github.com/RobotLocomotion/drake/blob/master/common/type_safe_index.h#L64-L66) and ['Identifier'](https://github.com/RobotLocomotion/drake/blob/master/common/identifier.h#L70-L72) is no longer correct. The documentation explicitly requests users to "treat these like ints and const references is a misuse" -- the compiler has made that a lie. I'd recommend a change in both of those files to something like this:

```c++
/// It is the designed intent of this class, that indices derived from this
/// class can be passed and returned by value. Generally, passing indices by
/// const reference should be considered a misuse. The conspicuous exception to
/// this would be in range-loops where the compiler may consider copies an
/// error. So, prefer `for (const IndexType& i : my_indices) { ... }` to
/// `for (const IndexType i : my_indices) { ... }`.
```

(With changes in formatting and `IndexType` --> `IdType` as appropriate to `TypeSafeIndex` vs `Identifier`.) 

Alternatively, is there any way to decorate those types so that the compiler ignores those?
</blockquote></details>

We might be able to placate the clang warning, but most of the humans who encounter the by-value will remain buggy in their interpretations.  We normally pass classes by const reference, and `drake::IndexType` looks like a class.  Asking people to memorize exceptions is undesirable.  Was the original justification to avoid pass by reference based only on aesthetics, or also on benchmarking?  If only for aesthetics, maybe having exceptions to a wide-ranging rule for only that reason is not worth the maintenance cost.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jamiesnape and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmdMw64EVVPvX1gw3h:-MHmjv2MCtbqPZoP9dHR:b-rxsz1l) (no related file):*
> "treat these like ints and const references is a misuse"

Can you provide a link to substantiate that quotation?  I'm not finding it anywhere.  It seems like an exaggeration of what's actually in the docs, which I see as:

> It is the designed intent of this class, that indices derived from this
> class can be passed and returned by value. Passing indices by const
> reference should be considered a misuse.

... and here, we are not "passing" anything.  So I don't think there is any defect in this PR?

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jamiesnape and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmdMw64EVVPvX1gw3h:-MHmlI7GAeCuLFa16Zzv:b-4bj07e) (no related file):*
I did provide two links to substantiate the quotation and then the meat of it was copied and pasted into the recommendation.

You've made two points:

> Asking people to memorize exceptions is undesirable.

and 

> here, we are not "passing" anything.

I'd argue there is still cognitive dissonance between what is currently in master's documentation and the particular usage demanded by the compiler. There *is* a legalistic argument for why they may be consistent. But making legalistic arguments one way or the other is probably also not a good use of our user's time.

So, I'd suggest the superior alternative to my original comment is that the paragraphs in question (linked to in my original comment), should simply be excised. Since the dissonance arises in this PR, I'd suggest the cut should likewise happen here.

(And the answer to the question I haven't given is, "Yes. I believe it's largely an aesthetic choice consistent with the documented 'this is just a funny int' language.")

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jamiesnape and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14094#-MHmdMw64EVVPvX1gw3h:-MHms6_c6QGMMeQMShp8:btpgvpb) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I did provide two links to substantiate the quotation and then the meat of it was copied and pasted into the recommendation.

You've made two points:

> Asking people to memorize exceptions is undesirable.

and 

> here, we are not "passing" anything.

I'd argue there is still cognitive dissonance between what is currently in master's documentation and the particular usage demanded by the compiler. There *is* a legalistic argument for why they may be consistent. But making legalistic arguments one way or the other is probably also not a good use of our user's time.

So, I'd suggest the superior alternative to my original comment is that the paragraphs in question (linked to in my original comment), should simply be excised. Since the dissonance arises in this PR, I'd suggest the cut should likewise happen here.

(And the answer to the question I haven't given is, "Yes. I believe it's largely an aesthetic choice consistent with the documented 'this is just a funny int' language.")
</blockquote></details>

I've moved from this reviewable thread into pull request to retire this: #14105.

---

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14094#-:-MHmtYCp6WvNY_ohV56a:bmxilld)* status: 1 unresolved discussion (waiting on @jamiesnape)

**Pull request merged**
