### PR TITLE
diff ik: Expand docs for ComputePoseDiffInCommonFrame; add bindings

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This math seems simple but has some nuance; we have a few occurrences of this.
Just trying to capture nuance and consolidate usages.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15990)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@siyuanfeng-tri would you like to offer any review comments here?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI could you help move this forward, or else close it?  Maybe Aykut or Paul would like to take over from Siyuan?

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI any progress here?

**Comment by EricCousineau-TRI** [comment]
Not yet, sorry; would you like me to close it for the time being?

(I def. want to address, may not be soon though.)

**Comment by EricCousineau-TRI** [comment]
Sounds good! Closed for now, but may become relevant again in a few months (maybe)

**Pull request closed without merging**
