### PR TITLE
Fixing rotation_constraint_test

### PR DESCRIPTION
**Pull request by m-chaturvedi**
bug: https://drake-cdash.csail.mit.edu/viewDynamicAnalysisFile.php?id=131769

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6172)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-nightly-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by soonho-tri** [comment]
Hi @m-chaturvedi, do you have a clue what's wrong here? This morning, we merged https://github.com/RobotLocomotion/drake/pull/6210 suspecting that https://github.com/RobotLocomotion/drake/pull/6153 broke the CI, esp `rotation_constraint_test`. However, I couldn't really figure out what caused the problem and just found this PR.

**Comment by m-chaturvedi** [comment]
From Slack conversation with Soonho: 
- A possibly related error happened in https://github.com/RobotLocomotion/drake/commit/ec00b6fc6, the CI failed deterministically on this test at least 10 times in a row, due to which the commit was reverted.
- Soonho couldn't reproduce the error on his local machine with `--compiler=gcc-5` and `-c opt`
- I was not able to reproduce the Valgrind error on CI. I can't run the test on my local machine because I lack access to MOSEK.

**Comment by jwnimmer-tri** [comment]
Hmm, what is the return type of the `lambda_mag` expression ending in `...real();` (i.e., what type is the `auto`)?  The usual Eigen mnemonic is either to write out the desired local variable type explicitly, or else `const auto& foo = ( ... some arithmetic ... ).eval();` so you get a value instead of a promise.

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-continuous-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by soonho-tri** [comment]
I think @jwnimmer-tri hits the right spot again.

> In short: do not use the auto keywords with Eigen's expressions, unless you are 100% sure about what you are doing. In particular, do not use the auto keyword as a replacement for a Matrix<> type. 

https://eigen.tuxfamily.org/dox/TopicPitfalls.html

**Comment by soonho-tri** [comment]
@m-chaturvedi , I think the issue is resolved by #6299.

**Pull request closed without merging**
