### PR TITLE
framework: Add ExternalSystemConstraint to a System 

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates #10339.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/10394)

### CODE REVIEW

**Comment by RussTedrake** [comment]
I guess by my own comment, it would be even better to declare the v=0 as an entirely separate constraint, because we’d want the solver to parse it as a bounding box constraint (even if the dynamics are a generic constraint).

**Comment by jwnimmer-tri** [comment]
FYI All of the prerequisite commits have been merged now.  Having dwelled on this a bit now, there are a couple possible improvements I still want to make here before it's done (as well as likely some missing test cases).

**Comment by jwnimmer-tri** [comment]
I think this is in fairly good shape now.

+@hongkai-dai can I ask you for a full feature review?

+@RussTedrake I think we should have you sign off on the terminology / comments / API design here?

**Comment by jwnimmer-tri** [comment]
Not going to wait on -@RussTedrake any longer.  Will merge after CI refresh passes.

**Pull request merged**
