### PR TITLE
Remove the deprecated contiguity assumption from VectorBase.

### PR DESCRIPTION
**Pull request by david-german-tri**
Update Subvector and Supervector to inherit from VectorBase.  Contributes to #3208.

+@jwnimmer-tri for both levels of review.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3390)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Checkpoint of review. 

The edits look good, but I haven't been able to understand yet why things like e.g. `System::get_input_vector` are allowed to assume that the port is `BasicVector.  I will have to come back to that.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pSMIGRw10Xg6cEgn:-KR9pSMIGRw10Xg6cEgo:bcf2n7f) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L44)):*
> ```objc
>   }
> 
>   void set_value(const Eigen::Ref<const VectorX<T>>& value) {
> ```

Missing API doc.

---

*[drake/systems/framework/basic_vector.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pTZQxV7B-5QQRYnG:-KR9pTZQxV7B-5QQRYnH:bcf2n7f) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L55)):*
> ```objc
>   int size() const override { return static_cast<int>(values_.rows()); }
> 
>   Eigen::VectorBlock<const VectorX<T>> get_value() const {
> ```

Missing API doc.

---

*[drake/systems/framework/basic_vector.h, line 59 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pUDjtP2thgE9uAAY:-KR9pUDjtP2thgE9uAAZ:bcf2n7f) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L59)):*
> ```objc
>   }
> 
>   Eigen::VectorBlock<VectorX<T>> get_mutable_value() {
> ```

Missing API doc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-:-KR9pwCbkv7m72Lfn2XK:bekmb1y)*

**Comment by david-german-tri** [comment]
> I haven't been able to understand yet why things like e.g. System::get_input_vector are allowed to assume that the port is `BasicVector`.

Input and output ports are required to be contiguous. 

Before  #3208, they implemented `VectorBase`, formerly `VectorInterface`, which was the most abstract type that enforced contiguousness. 

Post #3208, `VectorBase` no longer enforces contiguousness, so input and output ports implement BasicVector.  (Which has many other goodies in addition to contiguousness.)

---

Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/basic_vector.h, line 44 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pSMIGRw10Xg6cEgn:-KR9tAjH8kHfnZedfiUm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API doc.
</details>
Done.

---

*[drake/systems/framework/basic_vector.h, line 55 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pTZQxV7B-5QQRYnG:-KR9tBB9mmDKlYdkDOhe:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L55)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API doc.
</details>
Done.

---

*[drake/systems/framework/basic_vector.h, line 59 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-KR9pUDjtP2thgE9uAAY:-KR9tA3jq0zGNX2XfIFu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dbf9b55733b2c9dcef9cdb6cdd91cf9da74f3331/drake/systems/framework/basic_vector.h#L59)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API doc.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-:-KR9sCLnYsBZk8Zi1qFZ:bm9wl)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

---

Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-:-KR9tLIAhaVS4HhmDz6C:bmripy1)*

**Comment by jwnimmer-tri** [comment]
Ah.  I didn't realize that inputs and outputs can't be scattered.  I guess that's fine; if I want to fork or join output ports I'll need to copy, but probably worth it for the common-case benefit to assuming they are contiguous.

:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3390#-:-KRA9Py1inOS0JUu2UW1:bof4o7m)*

**Comment by sherm1** [comment]
> Input and output ports are required to be contiguous.

Wait, is that just temporary? Doesn't that limitation mean we can't export a diagram state to an output port?

**Comment by david-german-tri** [comment]
> Wait, is that just temporary?

Well, it's been true from the beginning.  I have no particular plans to change it, but we could (with a little bit of yak shaving) if there were a need.

> Doesn't that limitation mean we can't export a diagram state to an output port?

To export the state of a whole diagram as an output, write a stateless system that concatenates the state outputs of other constituent Systems.  Actually, this is the correct approach even if we did allow non-contiguous input or output ports; the only difference is whether a copy is required.

**Pull request merged**
