### PR TITLE
Add bazel build files for pybind11

### PR DESCRIPTION
**Pull request by jamiesnape**
This may need some tweaking when we actually use `pybind11`. At the very least, I assume bindings will need to link to the Python libraries.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4937)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Seriously?

**Comment by david-german-tri** [comment]
@drake-jenkins-bot ok to test

:rofl:

**Comment by david-german-tri** [comment]
+@david-german-tri

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-:-KbWAmXQqJivUcFi7Lnr:b-m1yjmx)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/pybind11.BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-KbWAvvFv__ru27GSucZ:-KbWAvvFv__ru27GSuc_:b-k9ttht) ([raw file](https://github.com/robotlocomotion/drake/blob/2705fe95d6a0960e9cbe884cbd2ee3c4505e2f3a/tools/pybind11.BUILD#L5)):*
> ```
> cc_library(
>     name = "pybind11",
>     hdrs = glob([
> ```

BTW, this isn't actually globbing anything (no wildcards).  You could just use a list, or you could `glob(["include/pybind11/*.h"])`, as you like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-:-KbWB5hQYGYAjrcuAoZM:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/pybind11.BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-KbWAvvFv__ru27GSucZ:-KbWBFNHc2kCHPbWXgWZ:b-b3gc88) ([raw file](https://github.com/robotlocomotion/drake/blob/2705fe95d6a0960e9cbe884cbd2ee3c4505e2f3a/tools/pybind11.BUILD#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, this isn't actually globbing anything (no wildcards).  You could just use a list, or you could `glob(["include/pybind11/*.h"])`, as you like.
</blockquote></details>

That is very true. I was globbing originally and then switched. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937)*

**Comment by jamiesnape** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/pybind11.BUILD, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-KbWAvvFv__ru27GSucZ:-KbWCPRE-gRuA9V8q4Qp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2705fe95d6a0960e9cbe884cbd2ee3c4505e2f3a/tools/pybind11.BUILD#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

That is very true. I was globbing originally and then switched. Will fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4937#-:-KbWDcAHWqrdT8kH78qp:bnfp4nl)*

**Pull request merged**
