### PR TITLE
[framework] Add sugar for declaring state output ports

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Even with pydrake bindings and new tests, this is still net-LOC negative.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256#-:-MdNLG9p3KtFU7bPtrKd:b-83sjoh)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@sherm1 for feature review of the changes **within** `systems/framework`, please.  You are invited spot-check some sample uses as well.

+@ggould-tri for feature review of the changes **outside** `systems/framework` and platform review of the whole thing per schedule (on Thursday), please.

**Comment by ggould-tri** [comment]
FYI I am not the scheduled Thursday on-call.  But happy to review it anyway as this is a pain point I have had.

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm_strong: for systems/ stuff and bindings and a few random uses. A really nice improvement, thanks!

> Reviewed 10 of 26 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256#-:-MdT6grW-pNTaL2_XbEl:bi9v62y)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sherm1)

**Review by ggould-tri — COMMENTED** [review]
LGTM feature; platform second-look tomorrow morning.

> Reviewed 13 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256#-:-MdTEq9l8lTWqEexRBHN:b-e0b4e4)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

___
*[systems/framework/leaf_system.h, line 1510 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15256#-MdSA_CB3JaC8gGYvvCC:-MdSA_CB3JaC8gGYvvCD:bncgq94) ([raw file](https://github.com/robotlocomotion/drake/blob/8c5e9634aa2592bf3051cb52badc920be5ff2639/systems/framework/leaf_system.h#L1510)):*
> ```objc
>   /** Declares a vector-valued output port whose value is the continuous state
>   of this system.
>   @param state_index must be ContinuousStateIndex{0}
> ```

minor:  This would be a bit less confusing if you said "for now" or similar to this documentation, to explain why there is a parameter with only one valid value.

At author's discretion, `ContinuousStateIndex{0}` is rule-of-three as an idiom; consider a named constant (`kAllContinuousState` or something) rather than making everyone lookup the definition to figure out what's going on.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @sherm1)

___
*[systems/framework/leaf_system.h, line 1510 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15256#-MdSA_CB3JaC8gGYvvCC:-Mdd6O-I6-bCxlQKgdZO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8c5e9634aa2592bf3051cb52badc920be5ff2639/systems/framework/leaf_system.h#L1510)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@sherm1 I wonder if I should change `LeafSystem::DeclareContinuousState` to return a `ContinuousStateIndex{0}`, which we could then feed in here?  That would allow our call sites to forward along the index when adding the port, like they do already for discrete or abstract states.  WDYT?
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 7 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

___
*[systems/framework/leaf_system.h, line 1510 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15256#-MdSA_CB3JaC8gGYvvCC:-MdhKu7K0m1i-ahIrKex:b-3r9lwq) ([raw file](https://github.com/robotlocomotion/drake/blob/8c5e9634aa2592bf3051cb52badc920be5ff2639/systems/framework/leaf_system.h#L1510)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

On balance I think that's a good idea though I suspect if we ever actually do the #9171 revamping of state variables q, v, and z may end up in different continuous state "groups", with different indices.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 26 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15256#-:-Me0NOCSD6DGMlRX2HoZ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),sherm1(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Pull request merged**
