### PR TITLE
[C-IRIS] split cspace_free_polytope_test.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Create cspace_free_polytope_with_mosek_test that requires Mosek.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by hongkai-dai — COMMENTED** [review]
+@xuchenhan-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-:-NMHcpL03ljoNMhWsqm1:b29gpxh)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: pending CI and a question.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-:-NMUmXn68nJGBKtvny7F:b-51td42)* status: 1 unresolved discussion, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc` line 514 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-NMUlvJJ5HlGZlV04Ytz:-NMUlvJJ5HlGZlV04Yu-:bocebs8) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e233568cd88b3a882201bcb5a3325334c72d667/geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc#L514)):*
> ```cpp
>   options.solver_id = solver.id();
>   for (int num_threads : {1, kTestConcurrency}) {
>     options.num_threads = num_threads;
> ```

BTW, a potentially dumb question: what happens under the hood when `num_threads > 1` when it comes to MOSEK licenses? Does each thread need to acquired a separate license? Is this compatible with the idea of acquiring the license before all test cases?

I'm curious because of the spam of 

"Set parameter ServerPassword
Set parameter TokenServer to value "172.31.29.246""

that we saw from the console in the failed test.

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for platform review please due to the slack conversation https://drakedevelopers.slack.com/archives/C270MN28G/p1674142473151599

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-:-NMVXeB62Ov0z_diTJoL:bpobc3z)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc` line 514 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-NMUlvJJ5HlGZlV04Ytz:-NMVXTbW4jXOWYOs0CAA:bj1oa2q) ([raw file](https://github.com/RobotLocomotion/drake/blob/2e233568cd88b3a882201bcb5a3325334c72d667/geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc#L514)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, a potentially dumb question: what happens under the hood when `num_threads > 1` when it comes to MOSEK licenses? Does each thread need to acquired a separate license? Is this compatible with the idea of acquiring the license before all test cases?

I'm curious because of the spam of 

"Set parameter ServerPassword
Set parameter TokenServer to value "172.31.29.246""

that we saw from the console in the failed test.
</blockquote></details>

No, the whole binary will acquire a single license, no matter how many threads it invoke.

**Review by xuchenhan-tri — COMMENTED** [review]
+(status: single reviewer ok) since this PR is contained in `dev`.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-:-NMVYBa18EaJw5ntHrNI:b11hkul)* status: LGTM missing from assignee jwnimmer-tri(platform), missing label for release notes (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: none) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18632#-:-NMVYLaS-ORG-1JREG1V:b-safpmt)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I did a quick look that nothing is calling `solver.available()` anymore, which to me is the crux of the matter.  I think this is a-ok for dev so -@jwnimmer-tri no need for platform yet.

**Pull request merged**
