### PR TITLE
Resolve cpplint build/header_guard issues.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by RussTedrake** [comment]
@jwnimmer-tri -- sorry.  need a merge (it's an easy one).

**Comment by RussTedrake** [comment]
+1

**Comment by liangfok** [comment]
+1

**Comment by RussTedrake** [comment]
fyi - i think jenkins is down.

**Comment by billhoffman** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
Jenkins is still going "virtual memory exhausted: Cannot allocate memory".

**Comment by jwnimmer-tri** [comment]
retest this please

**Comment by jwnimmer-tri** [comment]
Jenkins and Travis are happy, but drake006 is still unhappy.  Declaring "mission accomplished" and ready to merge.

**Pull request merged**
