### PR TITLE
Bump bazelbuild/{buildtools,rules_go}, Add org_golang_x_tools

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5794)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Removes the warning:
```
WARNING: /home/sfeng/.cache/bazel/_bazel_sfeng/182479d4bdf8a72cbe661ee7cc82bb5d/external/com_github_bazelbuild_buildtools/WORKSPACE:1: Workspace name in /home/sfeng/.cache/bazel/_bazel_sfeng/182479d4bdf8a72cbe661ee7cc82bb5d/external/com_github_bazelbuild_buildtools/WORKSPACE (@com_github_bazelbuild_buildifier) does not match the name given in the repository's definition (@com_github_bazelbuild_buildtools); this will cause a build error in future versions.
```

I've tested it in OSX+bazel-0.4.5 and Ubuntu-14.04+bazel-0.4.5 combinations.

+@jwnimmer-tri , +@david-german-tri reviews please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhSreOnUgseTMhKSFkl:bk7pipx)*

**Comment by jwnimmer-tri** [comment]
Did you see bazelbuild/buildtools#81?  I haven't studied yet if this relates.

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhSsy6MOqpFjZzq9Ic9:b-58ldh0)*

**Comment by soonho-tri** [comment]
Probably it's better for this one to go hand-in-hand with https://github.com/RobotLocomotion/drake/issues/5781 ?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhStt68mjegOeKeQ-oJ:be5sxdb)*

**Comment by jwnimmer-tri** [comment]
I don't know.  I trust you to decide.

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please
@drake-jenkins-bot linux-gcc-bazel-experimental please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhSw6289DLKBizkr7qt:b-pg3ap9)*

**Comment by soonho-tri** [comment]
@jwnimmer-tri , btw, do we call `buildifier.sh` in CI? I remember it was not the case previously.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhSwcoSgCnvPA_T3zjw:bixqwe6)*

**Comment by jwnimmer-tri** [comment]
In `tools/BUILD` we have:
```python
alias(
    name = "buildifier",
    actual = "@com_github_bazelbuild_buildtools//buildifier",
)
```

... which (I think) builds it, but we do not run it automatically.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhSx7SW5UqN6GK75Owb:bymzy7)*

**Comment by david-german-tri** [comment]
CI failure seems legit, yes?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhT6TPr9pt_nmVGxG3e:b-sb2jkd)*

**Comment by soonho-tri** [comment]
@david-german-tri , yes it is. I can reproduce the problem with `bazel-0.4.3` but not with `-0.4.4` and `-0.4.5`. Anyway, I'll check how to avoid the problem in `-0.4.3`. In the worst case, this can be waited until we switch to `-0.4.5`.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5794#-:-KhTFXOjPl6SGHkwLfOk:bhx4jt1)*

**Comment by soonho-tri** [comment]
I'll open it again when we switch to `bazel-0.4.5`.

**Pull request closed without merging**
