### PR TITLE
VariableSaturation primitive block

### PR DESCRIPTION
**Pull request by naveenoid**
Follows up on the Saturation block with a variable version (settable min and max values).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4798)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@sammy-tri for feature review.

**Comment by sammy-tri** [comment]
Apologies if I don't get to this in more detail today...  do we think we'll have users for both Saturation and VariableSaturation?  And if so, does it make more sense to have two classes which duplicate code (and comments) than using a ConstantVectorSource with an implementation like this one in the case where the saturation doesn't change?

---

Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-Kai5fA1CPo64xtV98yE:b5h0na9)*

**Comment by naveenoid** [comment]
I thought about it and figured that Saturation could be replaced with a static method in this class that does something similar to ConnectController. What do you think is the ideal way to proceed with this PR? Im using this in a custom gripper controller that Im currently testing.

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KaiD20SvoXjMFJ1zn8k:b-9p42qo)*

**Comment by sammy-tri** [comment]
If the constant version of saturation doesn't actually have any candidate users?  Maybe rename this class to Saturation and submit it as a diff instead of a new implementation?  (Maybe this doesn't make sense if a saturation block is something which has a common meaning in control programming and a variable saturation is something different).  One approach might be to make Saturation a Diagram which has the constant vector sources and the VariableSaturation block?  (which would make a complicated diagram out of what's currenty a simple class, so I don't love that either).

The other option is to tolerate the duplicate code while I feature review (honestly it's more duplicated in comments/theory than in actual syntax) and see how the platform reviewer feels.  Perhaps the duplication is worth it for the resulting code simplicity (particularly in Saturation).  Maybe I'll start down that path once I start reviewing (sorry again for the delay!).

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KaiIhPP-epveLs1XbWp:b-kbxlwm)*

**Comment by naveenoid** [comment]
I will wait for your review (do-nothing is easiest for me). I can easily accommodate any of the changes that you suggest.

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-Kakee-OiJvJ5VFp07ZK:b-554xec)*

**Comment by sammy-tri** [comment]
checkpoint, still reviewing

---

Reviewed 2 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/variable_saturation.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamJq8xZPmba2shswKu:-KamJq8znpSlGRfNsr8c:b-9bres6) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L46)):*
> ```objc
>   /// represented by scalars.
>   ///
>   /// @param[in] enable_max_value_port Enables the max value port
> ```

BTW I think I'd prefer either detecting if the port is connected during DoCalcOutput (EvalVectorInput will return nullptr if the port isn't connected) or forcing the user to always connect the port (e.g. to a ConstantVectorSource returning +/-infinity).

---

*[drake/systems/primitives/variable_saturation.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamJTba4HIMuRive6ix:-KamJTbbL2A4gcN3KzMx:b-4jr4e2) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L52)):*
> ```objc
>   /// Atleast one of enable_max_value_port or enable_min_value_port
>   /// must be set and input_size must be a positive integer.
>   explicit VariableSaturation(bool enable_max_value_port,
> ```

The explicit keyword doesn't seem to make sense with a multi-argconstructor?

---

*[drake/systems/primitives/variable_saturation.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamKJqYYUZovLK62aAI:-KamKJqYYUZovLK62aAJ:br7d2jo) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L73)):*
> ```objc
> 
>   /// Returns the input port index.
>   int get_input_port_index() const { return input_port_index_; }
> ```

BTW I feel like the named accessors for the actual ports make the index accessors a bit redundant?  (and you can call get_index() on the port descriptor itself if the index is needed)

---

*[drake/systems/primitives/variable_saturation.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamKWpIkSlelHQAX2Rc:-KamKWpIkSlelHQAX2Rd:bsgoyuh) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L86)):*
> ```objc
>   }
> 
>   /// Returns true if min_value_port is enabled.
> ```

I feel like the caller should know this when they built the Diagram?  or am I missing a use case?

---

*[drake/systems/primitives/variable_saturation.h, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamL-HXx2eKpXaG5U2j:-KamL-HXx2eKpXaG5U2k:bmq25qy) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L108)):*
> ```objc
>   const bool kMinValuePortEnabled_{false};
>   const bool kMaxValuePortEnabled_{false};
>   int input_size_;
> ```

missing {} initializer like the other members have

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KamL76QmCWC4enVA1Qa:bwlb241)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/primitives/variable_saturation.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-Kamk96ZRcgjNlRkHOFi:-Kamk96_UrpCljsZQ7Y_:b-cjjs9z) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.cc#L1)):*
> ```cpp
> 
> ```

Extra leading whitespace (it looks like two lines?)

---

*[drake/systems/primitives/variable_saturation.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamJq8xZPmba2shswKu:-KammUxmIQmu0hWIe77z:bixfxid) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L46)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I think I'd prefer either detecting if the port is connected during DoCalcOutput (EvalVectorInput will return nullptr if the port isn't connected) or forcing the user to always connect the port (e.g. to a ConstantVectorSource returning +/-infinity).
</blockquote></details>

BTW specifying +/-infinity instead of enable/disable could also save a lot of test framework boilerplate below

---

*[drake/systems/primitives/variable_saturation.h, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamkUbBTyFgQGu26N5D:-KamkUbC3Yy56zvHcaa-:biumytr) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L106)):*
> ```objc
>   int max_value_port_index_{};
>   int output_port_index_{};
>   const bool kMinValuePortEnabled_{false};
> ```

I'm not sure a member variable initialized in the constructor from a parameter meets the const-ness standard for kConstant naming in https://google.github.io/styleguide/cppguide.html#Constant_Names

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamlIjTAJ-V2n93krr1:-KamlIjTAJ-V2n93krr2:b-adn3mp) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L20)):*
> ```cpp
>                         const VectorX<T>& input_vector,
>                         const VectorX<T>& expected_output) {
>   const int kPortSize = variable_saturation_system.get_size();
> ```

I don't think this deserves kConstant status since it's based on a parameter.

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamlV3WNuQvkbtpxAIJ:-KamlV3WNuQvkbtpxAIK:bjhbtic) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L26)):*
> ```cpp
> 
>   // Verifies that Saturation allocates no state variables in the context.
>   EXPECT_EQ(context->get_continuous_state()->size(), 0);
> ```

duplicated above?

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KammAu7rpZGF4LBGHhv:-KammAu7rpZGF4LBGHhw:b-vct1fj) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L54)):*
> ```cpp
>   auto context = variable_saturation_system.CreateDefaultContext();
> 
>   const int kPortSize = variable_saturation_system.get_size();
> ```

see above re: kConstant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798)*

**Comment by naveenoid** [comment]
ok based on your feedback so far, Ive decided to make some large changes - > replace Saturation with this block and setup a constructor for a "Constant" Saturation version. The unit test verifies both the variable and constant versions of this System. 

---

Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/systems/primitives/variable_saturation.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-Kamk96ZRcgjNlRkHOFi:-KavCq0IN4x21xUZqsQh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.cc#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Extra leading whitespace (it looks like two lines?)
</blockquote></details>

Done.

---

*[drake/systems/primitives/variable_saturation.h, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamJq8xZPmba2shswKu:-KavD-tLGaZ2wANriMog:bd5gr0s) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L46)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW specifying +/-infinity instead of enable/disable could also save a lot of test framework boilerplate below
</blockquote></details>

I just realised that with a const constructor available, and by removing the enable/disable style constructor, I can eliminate Saturation and call this class as VariableSaturation. This is the solution I prefer and I will let you decide if a rollback is necessary.

---

*[drake/systems/primitives/variable_saturation.h, line 52 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamJTba4HIMuRive6ix:-Kax6-G4fxrIKD6OG--E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L52)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The explicit keyword doesn't seem to make sense with a multi-argconstructor?
</blockquote></details>

Done.

---

*[drake/systems/primitives/variable_saturation.h, line 73 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamKJqYYUZovLK62aAI:-Kax6-woXn0h771xeovq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L73)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I feel like the named accessors for the actual ports make the index accessors a bit redundant?  (and you can call get_index() on the port descriptor itself if the index is needed)
</blockquote></details>

Done.

---

*[drake/systems/primitives/variable_saturation.h, line 86 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamKWpIkSlelHQAX2Rc:-Kax61OocNGGE1zA12V1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L86)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I feel like the caller should know this when they built the Diagram?  or am I missing a use case?
</blockquote></details>

Done.

---

*[drake/systems/primitives/variable_saturation.h, line 106 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamkUbBTyFgQGu26N5D:-Kax6CRBsgzzfHBf4IQ5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L106)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure a member variable initialized in the constructor from a parameter meets the const-ness standard for kConstant naming in https://google.github.io/styleguide/cppguide.html#Constant_Names
</blockquote></details>

Done.

---

*[drake/systems/primitives/variable_saturation.h, line 108 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamL-HXx2eKpXaG5U2j:-Kax6DTubgMvhVdVfN4c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/variable_saturation.h#L108)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

missing {} initializer like the other members have
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamlIjTAJ-V2n93krr1:-Kax6EyUP0xnkgrfYSra:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L20)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I don't think this deserves kConstant status since it's based on a parameter.
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KamlV3WNuQvkbtpxAIJ:-Kax6aBFbTHlo_twLL7l:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L26)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

duplicated above?
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/variable_saturation_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KammAu7rpZGF4LBGHhv:-Kax6ZeGydCHTZbD_Oci:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/85babb0fe319176bef256a38822b67c026c6dc27/drake/systems/primitives/test/variable_saturation_test.cc#L54)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

see above re: kConstant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-Kawfe-riNGbxF3dVtxZ:b-feorhu)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) 

---

Reviewed 3 of 8 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/primitives/saturation.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxGCfjPcOahJscOdLB:-KaxGCfkOwnybV3ydvis:b-w17i6h) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.cc#L16)):*
> ```cpp
> template <typename T>
> Saturation<T>::Saturation(int input_size)
>     : min_max_ports_enabled_{true},
> ```

Inconsistent {} vs () initializer syntax

---

*[drake/systems/primitives/saturation.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxFU9CaBdqbkJBtm1e:-KaxFU9DZBwqFwHboO5Q:b-d11vss) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.h#L47)):*
> ```objc
>   /// @param[in] input_size sets size of the input and output ports.
>   ///
>   /// The min and max values can be connected in the appropriate ports
> ```

Was there supposed to be more text here?  This reads like a fragment of a sentence.

---

*[drake/systems/primitives/saturation.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxG3uICfLHySmJcZtg:-KaxG3uICfLHySmJcZth:b5y9vg1) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.h#L50)):*
> ```objc
>   explicit Saturation(int input_size);
> 
>   Saturation(const VectorX<T>& min_value, const VectorX<T>& max_value);
> ```

There should probably be some documentation on this constructor?  (the text from the old version of Saturation is probably pretty close)

---

*[drake/systems/primitives/test/saturation_test.cc, line 182 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxHTTJTNb_hIJYmwCw:-KaxHTTJTNb_hIJYmwCx:b-wldyoh) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/test/saturation_test.cc#L182)):*
> ```cpp
> }
> 
> // Tests the ability to use double vectors for inputs, and limits and constant
> ```

Should this say AutoDiffXd (and below?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KaxGbpi7hb0KF-sSQmO:b-s794vx)*

**Comment by sammy-tri** [comment]
Reviewed 3 of 8 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798)*

**Comment by naveenoid** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/primitives/saturation.cc, line 16 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxGCfjPcOahJscOdLB:-Kb1estl59M_4GJ7S41j:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.cc#L16)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Inconsistent {} vs () initializer syntax
</blockquote></details>

Done.

---

*[drake/systems/primitives/saturation.h, line 47 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxFU9CaBdqbkJBtm1e:-Kb1fnDU7yFxejHOhUfV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.h#L47)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Was there supposed to be more text here?  This reads like a fragment of a sentence.
</blockquote></details>

Done.

---

*[drake/systems/primitives/saturation.h, line 50 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxG3uICfLHySmJcZtg:-Kb1jCEA8PnTqGX9BH8_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/saturation.h#L50)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

There should probably be some documentation on this constructor?  (the text from the old version of Saturation is probably pretty close)
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/saturation_test.cc, line 182 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KaxHTTJTNb_hIJYmwCw:-Kb1jPP41OG88rG-noyM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/69d24256b7a5fee4fbddb334dfdf71c8c444b66f/drake/systems/primitives/test/saturation_test.cc#L182)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Should this say AutoDiffXd (and below?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KbAxzqZjIbtWjsa3Xt1:bnfp4nl)*

**Comment by naveenoid** [comment]
+@sherm1 for platform review. 
Note : This PR changed from introducing a new primitive block to modifying an existing one. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KbAzpUCkj331_8VTePI:b-soldkk)*

**Comment by sherm1** [comment]
A few BTWs needing response, otherwise :lgtm:.

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/saturation.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCkjtqtkdy0yOU_AZf:-KbCkjtrwlHFR0qn2-fC:b-t1fdsh) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L13)):*
> ```objc
> /// An element-wise hard saturation block with inputs signal `u`,
> /// saturation values @f$ u_{min} @f$ and/or @f$ u_{max} @f$, and output
> /// `y ` respectively as in:
> ```

BTW, extra space next to 'y'.

---

*[drake/systems/primitives/saturation.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCoFHbZW4flSOZ6JxH:-KbCoFHbZW4flSOZ6JxI:b-bzk2zi) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L35)):*
> ```objc
> /// appropriate constructor by passing their default value. If these quantities
> /// are not defined as constants but they are not connected to appropriate
> /// sources, their values are taken by default to be
> ```

BTW, please consider whether it might be better to fail if the input ports are enabled but not connected. I suspect this is more likely to be an error than something the user meant to do, in which case failing with a helpful error message would be a kindness.

---

*[drake/systems/primitives/saturation.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbClGK7lkR5Dg21DL5s:-KbClGK7lkR5Dg21DL5t:bvb2jc4) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L36)):*
> ```objc
> /// are not defined as constants but they are not connected to appropriate
> /// sources, their values are taken by default to be
> /// @f$ u_{min} = \infty @f$, and  @f$ u_{max} = \infty @f$ respectively.
> ```

BTW shouldn't min be *minus* infinity?

---

*[drake/systems/primitives/saturation.h, line 48 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCmLuOtmy6Zd7l3pBu:-KbCmLuOtmy6Zd7l3pBv:b-dlhc43) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L48)):*
> ```objc
>   /// @param[in] input_size sets size of the input and output ports.
>   ///
>   /// Please consult this class' description for the requirements of
> ```

BTW, the possessive for "class" is "class's" since "class" is a singular noun (see [here](http://english.stackexchange.com/questions/1073/what-is-the-correct-possessive-for-nouns-ending-in-s)).

---

*[drake/systems/primitives/test/saturation_test.cc, line 156 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCqyzY4GNT8Yuus3Oz:-KbCqyzY4GNT8Yuus3P-:bilbd2r) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/test/saturation_test.cc#L156)):*
> ```cpp
>     } else {
>       // Tests Saturation with variable max and min values.
>       EXPECT_NO_THROW(
> ```

BTW, I don't understand these nested `EXPECT`s. Wouldn't it be sufficient just to call `TestVariableSaturation()` since it contains ASSERTs and EXPECTs already? Does this cause it to suppress or nest the internal failures and report them here instead? Please let me know that you are sure this works or give it a try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KbCrbCP06UYOvgsVlEV:b-7ssiwp)*

**Comment by naveenoid** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/primitives/saturation.h, line 13 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCkjtqtkdy0yOU_AZf:-KbEoRbMYnWMHx2DWy0u:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L13)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, extra space next to 'y'.
</blockquote></details>

Done.

---

*[drake/systems/primitives/saturation.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCoFHbZW4flSOZ6JxH:-KbEojTuswnRn-uFvfS5:bfnza3x) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L35)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, please consider whether it might be better to fail if the input ports are enabled but not connected. I suspect this is more likely to be an error than something the user meant to do, in which case failing with a helpful error message would be a kindness.
</blockquote></details>

Done. Added another DRAKE_THROW. There is a minor annoyance with using DRAKE_ABORT_MSG in that unit tests must then look for EXPECT_DEATH. This was discouraged by @jwnimmer-tri . Is there any accepted fall back? Or perhaps I can add a custom DRAKE_THROW which includes an abort message on std::cerr or something - something like DRAKE_THROW_MSG

---

*[drake/systems/primitives/saturation.h, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbClGK7lkR5Dg21DL5s:-KbEoo2Xh4A1GEVyHZ9K:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L36)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW shouldn't min be *minus* infinity?
</blockquote></details>

Done.

---

*[drake/systems/primitives/saturation.h, line 48 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCmLuOtmy6Zd7l3pBu:-KbEortpjAS318rFguI-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L48)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, the possessive for "class" is "class's" since "class" is a singular noun (see [here](http://english.stackexchange.com/questions/1073/what-is-the-correct-possessive-for-nouns-ending-in-s)).
</blockquote></details>

Done.

---

*[drake/systems/primitives/test/saturation_test.cc, line 156 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCqyzY4GNT8Yuus3Oz:-KbEp5SDu-5X7TgewHxd:btl519t) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/test/saturation_test.cc#L156)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I don't understand these nested `EXPECT`s. Wouldn't it be sufficient just to call `TestVariableSaturation()` since it contains ASSERTs and EXPECTs already? Does this cause it to suppress or nest the internal failures and report them here instead? Please let me know that you are sure this works or give it a try.
</blockquote></details>

Done. I removed the EXPECT_NO_THROWs at this location. The called method will generate errors, if any exist. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/primitives/saturation.h, line 35 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-KbCoFHbZW4flSOZ6JxH:-KbHL5Xf1i5uD5pOIx3z:b-54anuo) ([raw file](https://github.com/robotlocomotion/drake/blob/4f34587228c60958ac0c18a96c4c8bb9dcfca4f7/drake/systems/primitives/saturation.h#L35)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

Done. Added another DRAKE_THROW. There is a minor annoyance with using DRAKE_ABORT_MSG in that unit tests must then look for EXPECT_DEATH. This was discouraged by @jwnimmer-tri . Is there any accepted fall back? Or perhaps I can add a custom DRAKE_THROW which includes an abort message on std::cerr or something - something like DRAKE_THROW_MSG
</blockquote></details>

throw seems fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KbHLgizjuc9HvEAca_n:bnfp4nl)*

**Comment by naveenoid** [comment]
Moving to squash and merge -(status: curate commits before merging) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4798#-:-KbKGdEJ4YQX0S434tma:b7qov74)*

**Pull request merged**
