### PR TITLE
Updating Bullet3 to 2.86.1

### PR DESCRIPTION
**Pull request by m-chaturvedi**
re https://github.com/RobotLocomotion/drake/issues/6426

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6428)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-nightly-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-memcheck-asan please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-bazel-experimental-everything-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-continuous-debug please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-experimental-debug

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-continuous please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-experimental please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-experimental please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-Kne29IyfYfyRcjRCIpa:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
@sammy-tri for platform review, please.

**Comment by sammy-tri** [comment]
+@seancurtis-tri for additional feature review.  I don't feel I have enough understanding of what the change in test tolerance means to sign off on this alone.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-Knexp8Rsa-JAyZBtPOY:-Knexp8SFypUqSKh4NOG:bk18g9f) ([raw file](https://github.com/robotlocomotion/drake/blob/eb7a5042c1fe6a08f1c8e1900ed64f72e330b96a/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
> ```cpp
>   ASSERT_TRUE(CompareMatrices(resultant.get_spatial_force(),
>                               expected_spatial_force,
>                               (7.0/6)*kTolerance,
> ```

The rest of this file has whitespace around mathematical operators.  This style might be permissible under https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace but I'd prefer we be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-KnexXbRXaAXOqrQKqos:b-srfu8w)*

**Comment by m-chaturvedi** [comment]
*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-Knexp8Rsa-JAyZBtPOY:-Knezz3KOvAYymSOFfug:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/eb7a5042c1fe6a08f1c8e1900ed64f72e330b96a/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

The rest of this file has whitespace around mathematical operators.  This style might be permissible under https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace but I'd prefer we be consistent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm: pending feature review

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-Knf-UEA1-N5u70ygf64:bm0ewrg)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by SeanCurtis-TRI** [comment]
Can I ironically put a checkpoint in for a single line?

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-KnfGXnglE5FAmmlIaK7:-KnfGXnhS1J_0kc9LfbX:bflk7kf) ([raw file](https://github.com/robotlocomotion/drake/blob/63d95315ddbf1b333d239568d83687fe82461cc8/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
> ```cpp
>   ASSERT_TRUE(CompareMatrices(resultant.get_spatial_force(),
>                               expected_spatial_force,
>                               (7.0 / 6) * kTolerance,
> ```

Looking into this....I'll get right back to you...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-KnfGag2JOsnJmT9ultD:bqp0aba)*

**Comment by SeanCurtis-TRI** [comment]
So, I've looked at the functionality before and after. Bullet is doing something *slightly* different in its iterative loop to compute the distance between the two objects. The difference leads to a *slight* deviation in the reported distance on approximately the same order as the threshold. In *old* bullet, its distance estimate was on the *small* side, so both the static contact force and the dissipative contact force (bigger by a factor of 1.5) fit under the threshold. THe *new* bullet errs on the large side such that in the dissipative case, the factor of 1.5 magnifies the distance error to no longer fall under the threshold. I've made my recommendation down below.  Otherwise, :LGTM:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-KnfGXnglE5FAmmlIaK7:-KnfXQi4hNZD0aXShrfO:b-j6hc0o) ([raw file](https://github.com/robotlocomotion/drake/blob/63d95315ddbf1b333d239568d83687fe82461cc8/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Looking into this....I'll get right back to you...
</blockquote></details>

This might be best addressed in the following way:

1. Document `kTolerance` to be the appropriate tolerance for a 1000 N force.
2. Indicate that in *this* case, the expected force is 1500 N, so the tolerance should be grown by the same factor (1.5).

This could potentially be expressed larger than just inside the scope of this function, but I would be content.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-KnfWlQEXCtvgS1WIfw1:b-82m3nn)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-KnfGXnglE5FAmmlIaK7:-KnfY8fctfvOcg8forw0:b-pcn0ys) ([raw file](https://github.com/robotlocomotion/drake/blob/63d95315ddbf1b333d239568d83687fe82461cc8/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This might be best addressed in the following way:

1. Document `kTolerance` to be the appropriate tolerance for a 1000 N force.
2. Indicate that in *this* case, the expected force is 1500 N, so the tolerance should be grown by the same factor (1.5).

This could potentially be expressed larger than just inside the scope of this function, but I would be content.
</blockquote></details>

Alternatively, we can just increase the threshold where it is defined and have it globally large. The same factor of 1.5 would be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by m-chaturvedi** [comment]
*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 202 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-KnfGXnglE5FAmmlIaK7:-KngRz-yYnb09kcJ96-G:boyodla) ([raw file](https://github.com/robotlocomotion/drake/blob/63d95315ddbf1b333d239568d83687fe82461cc8/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L202)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Alternatively, we can just increase the threshold where it is defined and have it globally large. The same factor of 1.5 would be enough.
</blockquote></details>

I chose the latter option.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot mac-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-clang-experimental please

**Comment by SeanCurtis-TRI** [comment]
One last quibble.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 149 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-Kniy4or8E6E0skDSlWD:-Kniy4or8E6E0skDSlWE:bfr3u7g) ([raw file](https://github.com/robotlocomotion/drake/blob/a7f08675b70c7ad75e2ebd035fd3adc6acfbbbcf/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L149)):*
BTW I'd recommend an alternative documentation. The comment of the bullet upgrade doesn't tell future programmers anything about this value. Alternatively:

> dummy_precision is a *very* tight threshold for these tests. It is well suited to the static contact force (1000 N) but because the moving contact force is 1.5 greater than the static contact force (1500 N), the threshold may *not* be enough to account for small errors/approximations in the underlying geometric code. This scale factor satisfies both scenarios. If the constants or configuration of these tests change, this value may have to increase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-KniyuDJrDsbg4gdhrc1:b-kq3151)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by m-chaturvedi** [comment]
*[drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc, line 149 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-Kniy4or8E6E0skDSlWD:-Knj77jaKVTP6UbxMy7t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a7f08675b70c7ad75e2ebd035fd3adc6acfbbbcf/drake/multibody/rigid_body_plant/test/contact_force_formula_test.cc#L149)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I'd recommend an alternative documentation. The comment of the bullet upgrade doesn't tell future programmers anything about this value. Alternatively:

> dummy_precision is a *very* tight threshold for these tests. It is well suited to the static contact force (1000 N) but because the moving contact force is 1.5 greater than the static contact force (1500 N), the threshold may *not* be enough to account for small errors/approximations in the underlying geometric code. This scale factor satisfies both scenarios. If the constants or configuration of these tests change, this value may have to increase.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428)*

**Comment by SeanCurtis-TRI** [comment]
Thanks for humoring me.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-Knj7CAIr9Ri11oGODKO:b81qpby)*

**Comment by m-chaturvedi** [comment]
You're welcome.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6428#-:-KnjsefvfU5rIR31kQeE:b-bavq6s)*

**Pull request merged**
