### PR TITLE
Remove drakeAppUtil (deprecated and unused)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I guess at some point we already removed the code that depended on this.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6467)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for all review per on-call rotation, please.

**Comment by jamiesnape** [comment]
Remove `drakeAppUtil.h` too?

**Comment by jwnimmer-tri** [comment]
Oops.  Thanks!

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6467#-:-Kno4_Dk_gsJvl90fQ3A:bnfp4nl)*

**Pull request merged**
