### PR TITLE
py mbp: Fix missing runtime module import

### LINKED ISSUE #14071: pydrake: multibody.math should import `pydrake.math`
See StackOverflow:
https://stackoverflow.com/questions/63904666/import-error-on-importing-pydrake-multibody-math

I can repro on latest, `drake-20200915-bionic.tar.gz`, using `virtualenv` instructions:
```
$ ./bin/python -c 'import pydrake.multibody.math'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: C++ type is not registered in pybind: N5Eigen14AutoDiffScalarINS_6MatrixIdLin1ELi1ELi0ELin1ELi1EEEEE
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #14071

FYI @mpetersen94

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@sherm1 for both reviews, please! +(status: single reviewer ok) 

Acute fix is simple, and (I think) the general check is pretty straightforward too. Lemme know if you need any explanations!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072#-:-MHIXNav84nVieKrUlXB:bh6v3q5)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for feature review.

**Comment by EricCousineau-TRI** [comment]
Ah, sweet, thanks!

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072#-:-MHI_A2d8oFkwpY7tmG0:b-n37teh)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHIZWEc2tqJfekqhfJ9:b4z0ur7) (no related file):*
Needs macOS testing.

---
___
*[bindings/pydrake/BUILD.bazel, line 348 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIYIPt65Tue-0wCM7b:-MHIYIPt65Tue-0wCM7c:b8f5tsu) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/BUILD.bazel#L348)):*
> ```Starlark
>     timeout = "moderate",
>     deps = [":all_py"],
> )
> ```

nit Missing `tags = ["cpu:4"],` because the test uses more than 1 CPU.
___
*[bindings/pydrake/test/all_each_import_test.py, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZ0_B54xks_yjs1oX:-MHIZ0_B54xks_yjs1oY:by4h4h6) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L10)):*
> ```Python
>     # Run a new interpreter and ensure we can import the module in isolation.
>     print(name)
>     subprocess.run([sys.executable, "-c", f"import {name}"], check=True)
> ```

nit Does this end up placing `pyc` files or `__pycache__` directories into places that it should not (e.g., the read-only runfiles directory, or the test's cwd)?  Please confirm locally.
___
*[bindings/pydrake/test/all_each_import_test.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZcCW3JnRxsjWTfMh:-MHIZcCW3JnRxsjWTfMi:b-vwi3mr) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L15)):*
> ```Python
> class Test(unittest.TestCase):
>     def test_each_import(self):
>         import pydrake.all
> ```

nit Unclear why we need to use a function-local import in this situation.
___
*[bindings/pydrake/test/all_each_import_test.py, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZm_246eaZTPI0bNZ:-MHIZm_246eaZTPI0bN_:byzodt3) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L24)):*
> ```Python
>                 continue
>             names.append(name)
> ```

nit Consider failing-fast if `names` is empty.  We should be sure that the test is actually doing something.

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-everything-release please

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHIvA_f6bUzndwgOLoD:b2g2qs2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs macOS testing.
</blockquote></details>

Current job: https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-experimental-everything-release/42/

---
___
*[bindings/pydrake/BUILD.bazel, line 348 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIYIPt65Tue-0wCM7b:-MHIvB_K5KcxxN4SBisR:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/BUILD.bazel#L348)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Missing `tags = ["cpu:4"],` because the test uses more than 1 CPU.
</blockquote></details>

Done
___
*[bindings/pydrake/test/all_each_import_test.py, line 10 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZ0_B54xks_yjs1oX:-MHIuq-k3lQztnVV-LMz:bx7j4hg) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Does this end up placing `pyc` files or `__pycache__` directories into places that it should not (e.g., the read-only runfiles directory, or the test's cwd)?  Please confirm locally.
</blockquote></details>

OK Just checked, does not seem to:

```
$ bazel run //bindings/pydrake:py/all_each_import_test
...
$ bazel-bin/bindings/pydrake/py/all_each_import_test
...
$ bazel test //bindings/pydrake:py/all_each_import_test
...
$ find . -name '__pycache__' -o -name '*.pyc'
# Nada
```

If there are files dumped in Bazel directories, I would claim that is a problem outside the scope of this PR.

TBH, running `python3 -c 'import blah'` from CWD in a Python script should be the same as `import blah` in the script itself, unless we/Bazel inject some anti-bytecode flags.
___
*[bindings/pydrake/test/all_each_import_test.py, line 15 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZcCW3JnRxsjWTfMh:-MHIv4xF4PoigGuHplW1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why we need to use a function-local import in this situation.
</blockquote></details>

Done.
___
*[bindings/pydrake/test/all_each_import_test.py, line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZm_246eaZTPI0bNZ:-MHIv5aW0DRO2Z2i4XLC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f8fadeff79df52e0a8a7fb4ac3f339242360d44d/bindings/pydrake/test/all_each_import_test.py#L24)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Consider failing-fast if `names` is empty.  We should be sure that the test is actually doing something.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
The build error looks like a flake, so
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJ-zEo3XZ-ixvijAvM:bx3j0sh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Current job: https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-experimental-everything-release/42/
</blockquote></details>

Fiery death on macsim:
```
...
ModuleNotFoundError: No module named 'all_each_import_test'
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'all_each_import_test'
...
//bindings/pydrake:py/all_each_import_test                              TIMEOUT in 300.0s
```

---

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending Mac fix.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072#-:-MHJ0Myn6L6lv8MOcNl4:b-2jmzgh)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJ0lMAAIkCYdo4Js05:bi5l8g) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fiery death on macsim:
```
...
ModuleNotFoundError: No module named 'all_each_import_test'
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'all_each_import_test'
...
//bindings/pydrake:py/all_each_import_test                              TIMEOUT in 300.0s
```
</blockquote></details>

Blarg. My guess is it's due to our wrapper logic that hurts the pickler (due to `sys.modules` meddling).

May tell this one to be a plain-vanilla unittest.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJ1Kc4D-dt20STM3fv:b-a281th) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Blarg. My guess is it's due to our wrapper logic that hurts the pickler (due to `sys.modules` meddling).

May tell this one to be a plain-vanilla unittest.
</blockquote></details>

Do we need the complexity of multiprocessing and BUILD cpu labels & etc?  For me locally, the test takes 20 seconds locally as a single for-loop thread.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJ9nag5rtH241uLYE4:bmms5kl) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Do we need the complexity of multiprocessing and BUILD cpu labels & etc?  For me locally, the test takes 20 seconds locally as a single for-loop thread.
</blockquote></details>

OK The fix for `multiprocessing` is simple, so I want it to stay. And in general, `multiprocessing` *should* be simple.

Also a data point for me on possible drawbacks to our `drake_py_unittest` wrapper, at least on Mac (or Python 3.8? dunno).

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJA0T967Hk_-7lDiT5:b-kgtjcj) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK The fix for `multiprocessing` is simple, so I want it to stay. And in general, `multiprocessing` *should* be simple.

Also a data point for me on possible drawbacks to our `drake_py_unittest` wrapper, at least on Mac (or Python 3.8? dunno).
</blockquote></details>

Ah, and yeah, tested the latest rev on macsim.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJA1ud5WvhlpbLz90x:bsknqwh) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, and yeah, tested the latest rev on macsim.
</blockquote></details>

On its own, changing 20 seconds to 5 seconds is no reason to add so much complexity to the execution infrastructure.  I should have been clearer it was a straight defect.  Unless your timings show up differently that my quick check?  Are debug builds much slower that 20 seconds, for example?  At minimum, we need a comment somewhere explaining why a test that takes 20 seconds on the surface is so complex.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJAs42Dp7qCRnN_TaW:b-qiwp1f) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On its own, changing 20 seconds to 5 seconds is no reason to add so much complexity to the execution infrastructure.  I should have been clearer it was a straight defect.  Unless your timings show up differently that my quick check?  Are debug builds much slower that 20 seconds, for example?  At minimum, we need a comment somewhere explaining why a test that takes 20 seconds on the surface is so complex.
</blockquote></details>

I'm not entirely convinced that this is "complex", and it still adds to the fact that I'm still not fan of how we do our entry-point wrapping; however, what does convince me is this from the `multiprocessing` docs:


At present, importing `pydrake.all` at the top-level is a complete waste of time with the "spawn" method.

So yeah, just gonna ditch multiprocessing then.
Will push changes.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJCMDrDxqEqTfkx0J0:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not entirely convinced that this is "complex", and it still adds to the fact that I'm still not fan of how we do our entry-point wrapping; however, what does convince me is this from the `multiprocessing` docs:


At present, importing `pydrake.all` at the top-level is a complete waste of time with the "spawn" method.

So yeah, just gonna ditch multiprocessing then.
Will push changes.
</blockquote></details>

Done.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @sherm1)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14072#-MHIZWEc2tqJfekqhfJ8:-MHJCPMP1omFefXjDcqx:b-b9txfi) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK And to follow-up: Yeah, it got complex due to the different platforms' default start methods :(
So yeah, nevermind, I am convinced it's complex, but maybe just sad :(

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14072)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by EricCousineau-TRI** [comment]
Will rebase on latest `master` and then do a merge commit.

**Pull request merged**
