### PR TITLE
Website: Add `apt-get install drake-dev` instructions to Binary Installation page

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Related to #12783

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@jamiesnape for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016#-:-M_0w05m8Rv065nI6M-0:bdx3wf2)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016#-:-M_12bL3CKAjFpkzN1T7:bnfp4nl)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @BetsyMcPhail)

___
*[doc/_pages/from_binary.md, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_11zmQ8Sv5OYSuPz8Y:-M_11zmQ8Sv5OYSuPz8Z:b-1c57vd) ([raw file](https://github.com/robotlocomotion/drake/blob/9aceea62373395c6404ac46be8aecd8eb2a3f59f/doc/_pages/from_binary.md#L62)):*
> ```Markdown
> described on [release notes page](/release_notes/older_releases.html).
> 
> # Debian (Ubuntu) Packaging Configuration for Drake
> ```

`APT Packages for Monthly Tagged Releases`
___
*[doc/_pages/from_binary.md, line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_11iPE7VZIpt7lKCap:-M_11iPE7VZIpt7lKCaq:b6wphrm) ([raw file](https://github.com/robotlocomotion/drake/blob/9aceea62373395c6404ac46be8aecd8eb2a3f59f/doc/_pages/from_binary.md#L64)):*
> ```Markdown
> # Debian (Ubuntu) Packaging Configuration for Drake
> 
> Debian packaging is currently available for Ubuntu 18.04 (Bionic) and
> ```

`APT packages are currently available for the ...`
___
*[doc/_pages/from_binary.md, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_11Sm6DmIxKLkg0fOj:-M_11Sm6DmIxKLkg0fOk:bp1kzlt) ([raw file](https://github.com/robotlocomotion/drake/blob/9aceea62373395c6404ac46be8aecd8eb2a3f59f/doc/_pages/from_binary.md#L75)):*
> ```Markdown
>    container image, you may need to install the following packages:
>    ```bash
>    #!/bin/bash
> ```

BTW We can probably lose the shebangs. Not sure why I added then on the `debian-drake` README.

**Review by BetsyMcPhail — COMMENTED** [review]
+@ggould-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016#-:-M_17bzb7VVgj5nYo4Q1:bffmgsm)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm: , one note below.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016#-:-M_1AR6JDpDWeehGew1u:b3uqkem)* status: 1 unresolved discussion (waiting on @BetsyMcPhail)

___
*[doc/_pages/from_binary.md, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_19oaE87630d7C1cSf:-M_19oaE87630d7C1cSg:bue0el4) ([raw file](https://github.com/robotlocomotion/drake/blob/37f27fd93f23fd4d2ea672e4f2112d8f01dc2a97/doc/_pages/from_binary.md#L83)):*
> ```Markdown
>    ```bash
>    wget -qO- https://drake-apt.csail.mit.edu/drake.asc | gpg --dearmor - \
>      | sudo tee /etc/apt/trusted.gpg.d/drake.gpg
> ```

This command dumps a lot of binary garbage to my console, because the tee is after the dearmor in this pipeline.  I'm not sure what teeing is accomplishing here anyway.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016)* status: 1 unresolved discussion (waiting on @ggould-tri)

___
*[doc/_pages/from_binary.md, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_19oaE87630d7C1cSf:-M_1Aj5qC-wNd7YkWjvs:b-9k3cs6) ([raw file](https://github.com/robotlocomotion/drake/blob/37f27fd93f23fd4d2ea672e4f2112d8f01dc2a97/doc/_pages/from_binary.md#L83)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This command dumps a lot of binary garbage to my console, because the tee is after the dearmor in this pipeline.  I'm not sure what teeing is accomplishing here anyway.
</blockquote></details>

You need it for `sudo`. We can add `>/dev/null` to the end of the `tee` command(s).

**Review by jamiesnape — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jamiesnape (waiting on @BetsyMcPhail)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15016)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jamiesnape (waiting on @BetsyMcPhail)

___
*[doc/_pages/from_binary.md, line 83 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15016#-M_19oaE87630d7C1cSf:-M_1IVHrEBeOFnjihBfx:bszm2f7) ([raw file](https://github.com/robotlocomotion/drake/blob/37f27fd93f23fd4d2ea672e4f2112d8f01dc2a97/doc/_pages/from_binary.md#L83)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You need it for `sudo`. We can add `>/dev/null` to the end of the `tee` command(s).
</blockquote></details>

Much better!

**Pull request merged**
