### PR TITLE
Temporarily remove //examples/acrobot:run_swing_up_traj_optimization_test

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/13263)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
We don't want the program manual (or else even the example itself is never compiled in CI), we only want its test removed.  So remove `add_test_rule = 1` from the `drake_cc_binary` with no change to tags.

**Comment by ggould-tri** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
The macOS CI has passed.  I think we should merge this now + open an issue for Russ to follow-up?

**Comment by RussTedrake** [comment]
SGTM

**Pull request merged**
