### PR TITLE
Split out IrisInConfigurationSpaceTest

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Move `IrisInConfigurationSpaceTest` tests from `iris_test.cc` into a new, separate test which is excluded from several instrumented configurations. While a number of the IRIS tests are slow, the majority of these in particular are [exceptionally slow](https://github.com/RobotLocomotion/drake/issues/16459#issuecomment-1024512656) and have been repeatedly causing instrumented builds to fail due to test timeouts. Splitting off the whole group is therefore a relatively simple way to hopefully address the timeout issue once and for all.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16567)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jwnimmer-tri for feature review, please.

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-gurobi-valgrind-memcheck please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-mosek-valgrind-memcheck please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-valgrind-memcheck please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-valgrind-memcheck please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-gurobi-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-address-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-leak-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-snopt-undefined-behavior-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-thread-sanitizer please.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16567)* status: LGTM missing from assignee sammy-tri(platform), missing label for release notes (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with much thanks to feature review for verifying the moved code.

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16567#-:-Mv_alZiCZiY8_Bk-fzh:b-cth829)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),jwnimmer-tri(platform) (waiting on @mwoehlke-kitware)

**Pull request merged**
