### PR TITLE
frame_visualizer, show_frames: Enable subscribing to multiple channels similar to director.drakevisualizer

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8126)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@naveenoid for feature review, please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8126#-:-L5tDHdhXZ9WX6uhaLDS:b-dj2eo4)*

**Comment by naveenoid** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/frame_visualizer.h, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8126#-L5yU5b2Lh9GF-8WJLju:-L5yU5b3D4PVR19q670L:b-g5u546) ([raw file](https://github.com/robotlocomotion/drake/blob/857352900f74924898090a49dfcda79069a870e0/multibody/rigid_body_plant/frame_visualizer.h#L49)):*
> ```objc
> 
>   /**
>    * Sets the channel to publish frames to.
> ```

BTW: sentence feels odd. How about "Sets the channel to which frames are published"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8126#-:-L5yTtoO4lcmJHtNlNYE:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
+@soonho-tri for platform review, please.

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[multibody/rigid_body_plant/frame_visualizer.h, line 49 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8126#-L5yU5b2Lh9GF-8WJLju:-L5ynMxM-eIXxxIj3IFh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/857352900f74924898090a49dfcda79069a870e0/multibody/rigid_body_plant/frame_visualizer.h#L49)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: sentence feels odd. How about "Sets the channel to which frames are published"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8126#-:-L5ynNxc6nSwELJbhwJJ:bxwr5c8)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8126#-:-L5ys-fG6LhwwwKchA3o:bnfp4nl)*

**Pull request merged**
