### PR TITLE
Add Value<T> default and forwarding constructors

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
These will come in handy when declaring model-based abstract ports, parameters, and state in future PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5485)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@david-german-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5485#-:-KfCKuyQ52Mwohqj4IIn:br4y6no)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5485#-:-KfCR6QPsRmetnASggkH:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/test/value_test.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5485#-KfCTyMMVUI7jM6HFnub:-KfCTyMNMh899teXkgjG:becy4q5) ([raw file](https://github.com/robotlocomotion/drake/blob/1057f0052f7cf790a0552bc8486a2817de3d98d4/drake/systems/framework/test/value_test.cc#L54)):*
> ```cpp
>   const Value<BareStruct> lvalue_bare(bare_struct);
> 
>   // Value<BareStruct>(BareStruct&) should use the `(const T&)` constructor,
> ```

is this comment missing a `const` before `BareStruct&` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5485)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5485#-:-KfCW5DGU2qr1DS-h6ER:bnfp4nl)*

**Pull request merged**
