### PR TITLE
add picosha2 dependency for computing sha256 sums

### PR DESCRIPTION
**Pull request by svenevs**
For render client / server validation of transmitted scene, we propose a sha256 hash.

Relates: #16234

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232)

### CODE REVIEW

**Comment by svenevs** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Review by svenevs — COMMENTED** [review]
+reviewer:@jwnimmer-tri for feature review please.  Modeled after the json feedback (#16231), this creates an expected merge conflict, can rebase after that merges.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrN-0XL5rX-x5DuFqZp:b-5otua8)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[tools/workspace/picosha2/package.BUILD.bazel, line 8 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrN-guX18twuPMqFZCi:-MrN-guX18twuPMqFZCj:b-hkqcdo) ([raw file](https://github.com/robotlocomotion/drake/blob/b954170db1f674ae19b5a1b7ffa9ebad8ed3b1e3/tools/workspace/picosha2/package.BUILD.bazel#L8)):*
> ```
> )
> 
> licenses(["notice"])  # MIT
> ```

FYI convenience link https://github.com/okdshin/PicoSHA2
___
*[tools/workspace/picosha2/package.BUILD.bazel, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrN-m2-3yI5-QHAsqmj:-MrN-m2-3yI5-QHAsqmk:b-m6rtvk) ([raw file](https://github.com/robotlocomotion/drake/blob/b954170db1f674ae19b5a1b7ffa9ebad8ed3b1e3/tools/workspace/picosha2/package.BUILD.bazel#L17)):*
> ```
>     name = "picosha2",
>     hdrs = ["picosha2.h"],
>     includes = ["."],
> ```

FYI I believe this is the correct way to include the top-level directory, but perhaps there is an alternative that is better that I am not aware of.
___
*[tools/workspace/picosha2/repository.bzl, line 11 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrN-wf89FH1lfJSgv-n:-MrN-wf89FH1lfJSgv-o:b-ruzpxx) ([raw file](https://github.com/robotlocomotion/drake/blob/b954170db1f674ae19b5a1b7ffa9ebad8ed3b1e3/tools/workspace/picosha2/repository.bzl#L11)):*
> ```Starlark
>         name = name,
>         repository = "okdshin/PicoSHA2",
>         commit = "1677374f23352716fc52183255a40c1b8e1d53eb",
> ```

FYI it is a relatively low activity repository, they do not have any tagged versions so I just pinned to the latest commit they have.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrNQmx58nGvciqb0bsH:b-n37teh)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

___
*[tools/workspace/picosha2/package.BUILD.bazel, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrN-m2-3yI5-QHAsqmj:-MrNQQjO8B9ATOXiy7J9:b-9145sz) ([raw file](https://github.com/robotlocomotion/drake/blob/b954170db1f674ae19b5a1b7ffa9ebad8ed3b1e3/tools/workspace/picosha2/package.BUILD.bazel#L17)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI I believe this is the correct way to include the top-level directory, but perhaps there is an alternative that is better that I am not aware of.
</blockquote></details>

OK This is fine, yes.

If we wanted, we could say `include_prefix = "picosha2"` and then in the C++ code do `#include <picosha2/picosha2.h>` if we didn't want to clutter the top-level include paths.  But since it's single-header, it's really the same either way.

**Comment by svenevs** [comment]
Rerunning unprovisioned installs for good measure.

@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Review by svenevs — COMMENTED** [review]
:lgtm: pending CI completion

+@ggould-tri for platform review please :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrOeMSK1u9-T6WevrVl:b-vpucuz)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[tools/workspace/picosha2/package.BUILD.bazel, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrN-m2-3yI5-QHAsqmj:-MrOebZr6JztsG1bglGp:btz0dtz) ([raw file](https://github.com/robotlocomotion/drake/blob/b954170db1f674ae19b5a1b7ffa9ebad8ed3b1e3/tools/workspace/picosha2/package.BUILD.bazel#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK This is fine, yes.

If we wanted, we could say `include_prefix = "picosha2"` and then in the C++ code do `#include <picosha2/picosha2.h>` if we didn't want to clutter the top-level include paths.  But since it's single-header, it's really the same either way.
</blockquote></details>

OK interesting.  I left it as is since it's one file but `include_prefix` is good to know about, thanks!

**Comment by jwnimmer-tri** [comment]
If a PR doesn't touch `setup`, then it doesn't need any `unprovisioned` jobs to validate it.  (Testing on macOS non-unprovisioned is still good though.)

**Review by svenevs — COMMENTED** [review]
Right, sorry.  Cancelled those, adding provisioned mac

@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrOgRCIAb5FsReTO9xY:bc4vv1t)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

**Comment by svenevs** [comment]
From GitHub not Reviewable... sorry for the spam!

@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-everything-release please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; two minor notes.

> Reviewed 1 of 6 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrOlSEv1otciGgBcM0e:bnz1g8y)* status: 2 unresolved discussions (waiting on @svenevs)

___
*[geometry/render/dev/test/picosha2_compile_test.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrOkc2TE43TzQmJ0ZQ7:-MrOkc2TE43TzQmJ0ZQ8:b-94r0vo) ([raw file](https://github.com/robotlocomotion/drake/blob/3785322c03514659f5bf1f596141dbb098666e4b/geometry/render/dev/test/picosha2_compile_test.cc#L12)):*
> ```cpp
>   std::string sha = picosha2::bytes_to_hex_string(hash.begin(), hash.end());
> 
>   // If the sha is correct, we desire a return code of 0.
> ```

minor: It would be good to give the user some idea of where this number came from and close the loop with a reference implementation; I'd suggest a comment like this:



_Suggestion:_
```cpp
  // If the sha is correct, we desire a return code of 0.
  // The literal hash value here can be checked via the command:  echo -n "This is a test." | sha256sum
```
___
*[geometry/render/dev/test/picosha2_compile_test.cc, line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrOkCA410PKZtSaTW36:-MrOkCA410PKZtSaTW37:b2nqffb) ([raw file](https://github.com/robotlocomotion/drake/blob/3785322c03514659f5bf1f596141dbb098666e4b/geometry/render/dev/test/picosha2_compile_test.cc#L13)):*
> ```cpp
> 
>   // If the sha is correct, we desire a return code of 0.
>   return \
> ```

minor:  I don't think this backslash is required?

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[geometry/render/dev/test/picosha2_compile_test.cc, line 12 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrOkc2TE43TzQmJ0ZQ7:-MrOpm2PAPxC2P3bBP2F:b-ohdol) ([raw file](https://github.com/robotlocomotion/drake/blob/3785322c03514659f5bf1f596141dbb098666e4b/geometry/render/dev/test/picosha2_compile_test.cc#L12)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor: It would be good to give the user some idea of where this number came from and close the loop with a reference implementation; I'd suggest a comment like this:
</blockquote></details>

Done, good call!
___
*[geometry/render/dev/test/picosha2_compile_test.cc, line 13 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16232#-MrOkCA410PKZtSaTW36:-MrOpocB8LAHvlLanak4:b-vofao0) ([raw file](https://github.com/robotlocomotion/drake/blob/3785322c03514659f5bf1f596141dbb098666e4b/geometry/render/dev/test/picosha2_compile_test.cc#L13)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  I don't think this backslash is required?
</blockquote></details>

OK, I like it better as one line as well ... only split it to stay under 80 chars.  I think this is clean.

**Review by svenevs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232#-:-MrOq5Uz9_kykSfawO5h:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16232)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @svenevs)

**Comment by jwnimmer-tri** [comment]
Oops.  We forgot to install the license notice file.  I'll fix that in #19879.

**Pull request merged**
