### PR TITLE
add reference to hello world examples of writing systems

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7445)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@ggould-tri for both reviews, please.  this is in (partial) response to your observation about not giving pointers to the simple examples. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7445#-:-KyYcJOXW0L-ar9es90f:bpwyejp)*

**Comment by RussTedrake** [comment]
-@ggould-tri +@sherm1 instead please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7445#-:-Kyc-tzuZdlOJ8gQSL3s:bhfay5d)*

**Comment by sherm1** [comment]
:lgtm: for both reviews, one BTW nit.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/systems.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7445#-KycDJy7hQmrJWi5gEKk:-KycDJy7hQmrJWi5gEKl:b9cwiw7) ([raw file](https://github.com/robotlocomotion/drake/blob/58129e51bff2afaf1b2cd9184cdd3fb5794925c4/drake/systems/systems.h#L20)):*
> ```objc
> /// For an example of a system that uses some of the more advanced
> /// features, such as typed input, output, state, and parameter vectors,
> /// see simple_car.h . 
> ```

BTW Reviewable is showing spurious characters at eol above and 3 lines prior. Probably just trailing blanks that didn't get caught by lint for some reason?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7445#-:-KycECmHlA6DSnddblZD:b7if3b4)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/systems.h, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7445#-KycDJy7hQmrJWi5gEKk:-Kyk19AIZUCh3-zy11rV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/58129e51bff2afaf1b2cd9184cdd3fb5794925c4/drake/systems/systems.h#L20)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW Reviewable is showing spurious characters at eol above and 3 lines prior. Probably just trailing blanks that didn't get caught by lint for some reason?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7445)*

**Pull request merged**
