### PR TITLE
[fem] Move Petsc matrix out of dev

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Towards #16492

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@amcastro-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-MvQt3cK1BGWK5iL6QLc:b-57wv7n)* status: LGTM missing from assignee amcastro-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: 
+@sammy-tri for platform review (tomorrow, next one in the rotation)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-MvV9vvaDApNzHAXxMG8:bn4scww)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-Mv_wXhH99qb9VN0uUmh:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.h, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mv_VdaI6aMReXBtw34-:-Mv_p7lx2WK-E2T6Lqmq:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/879694392bbf026140ad1dda2afc97ae9c1e9fbb/multibody/fem/petsc_symmetric_block_sparse_matrix.h#L46)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: missing "of" in "number (of) rows"
</blockquote></details>

Done, thanks.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 52 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mv_Z946-khnBDWkEoOA:-Mv_pE1ZE0wqBWvDKDO-:b-dtkdrq) ([raw file](https://github.com/robotlocomotion/drake/blob/879694392bbf026140ad1dda2afc97ae9c1e9fbb/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L52)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: typo "A20" instead of...  I think it should say "A21"?  or the next line should say "A20" instead of "A21".   Either way, the comment seems to disagree with itself.  (the comment for `MakeBlockSparseMatrix` probably also needs updated)
</blockquote></details>

Done, thanks.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 166 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mv__glQAsrGIAuIpEp_:-Mv_un9r23szJ1ij8g4S:bbgekyu) ([raw file](https://github.com/robotlocomotion/drake/blob/879694392bbf026140ad1dda2afc97ae9c1e9fbb/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L166)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

There aren't any tests of calling `Solve` with `kConjugateGradient`  (I guess kDirect is kinda handled through `CalcSchurComplement`, though that doesn't test the `Solve` path).  Should there be explicit tests for these options?  Or is there a reason why we don't need the test coverage now (it's an `internal` class so maybe this is OK?)
</blockquote></details>

Done. I added the missing tests.

**Review by xuchenhan-tri — COMMENTED** [review]
@amcastro-tri I added a few unit tests to round the edges. I'll merge this PR tomorrow to give you some time to vet them if you want to do that.
+(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-Mv_whQhBPyHchxd9Lkd:b-u4i27o)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)* status: labeled "do not merge" (waiting on @xuchenhan-tri)

**Review by amcastro-tri — COMMENTED** [review]
Thanks, added a question/suggestion on the new tests

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-MvcwwOkBnhW1YcXPmV6:bkqseyt)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 141 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-MvctHpEAp5mBEmy_GA2:-MvctHpEAp5mBEmy_GA3:b-p5uz6q) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L141)):*
> ```cpp
>         break;
>       case PreconditionerType::kNone:
>         PCSetType(preconditioner_, PCNONE);
> ```

why is it we wouldn't like to have both, kJacobi (useful when testing divergence of iterative solvers) and kNone?.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 171 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mvcw2mT5nDQ7yECHsGf:-Mvcw2mT5nDQ7yECHsGg:b-x20lk4) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L171)):*
> ```cpp
> }
> 
> GTEST_TEST(PetscSymmetricBlockSparseMatrixTest, CgSolve) {
> ```

I love the new tests, but I wonder if they test what you want? that is, do these tests confirm we actually used the specified iterative KSP and preconditioner?
Consider having methods like `SolverType PetscSymmetricBlockSparseMatrix::get_solver_type() ` and `PreconditionerType PetscSymmetricBlockSparseMatrix::get_preconditioner_type()` that directly query `owned_solver_` and `preconditioner_` to provide an answer. That way you could augment these tests by checking the return from these methods.

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not merge) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550#-:-Mve7JO34W3nEOhtc5MK:b-b9fcpn)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @amcastro-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 141 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-MvctHpEAp5mBEmy_GA2:-MvdvkgK-5o2vC6HuDcy:b-6423ta) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L141)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why is it we wouldn't like to have both, kJacobi (useful when testing divergence of iterative solvers) and kNone?.
</blockquote></details>

The reason I want kNone is to provide a most generic option. We can add more options when the need arises.
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 171 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mvcw2mT5nDQ7yECHsGf:-Mve5snT9Vf1heD8YWP0:b-f5nats) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L171)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I love the new tests, but I wonder if they test what you want? that is, do these tests confirm we actually used the specified iterative KSP and preconditioner?
Consider having methods like `SolverType PetscSymmetricBlockSparseMatrix::get_solver_type() ` and `PreconditionerType PetscSymmetricBlockSparseMatrix::get_preconditioner_type()` that directly query `owned_solver_` and `preconditioner_` to provide an answer. That way you could augment these tests by checking the return from these methods.
</blockquote></details>

For now, SolverType and PreconditionerType isn't intended to be a state of PetscSymmetricBlockSparseMatrix. It only exists in the scope of Solve() and SolveInPlace(). 

The test for now only tests that passing in various valid solver/preconditioner flag combinations all give the correct answer.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fem/petsc_symmetric_block_sparse_matrix.cc, line 141 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-MvctHpEAp5mBEmy_GA2:-MveId7J28QK67dL4D0D:bq0ncok) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/petsc_symmetric_block_sparse_matrix.cc#L141)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The reason I want kNone is to provide a most generic option. We can add more options when the need arises.
</blockquote></details>

sounds good
___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 171 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mvcw2mT5nDQ7yECHsGf:-MveIx6Z8-sTtvldv6IV:bicamxs) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L171)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

For now, SolverType and PreconditionerType isn't intended to be a state of PetscSymmetricBlockSparseMatrix. It only exists in the scope of Solve() and SolveInPlace(). 

The test for now only tests that passing in various valid solver/preconditioner flag combinations all give the correct answer.
</blockquote></details>

right, I was suggesting that the semantics of those methods was more like "return the last type used in a Solve() call", since you do store the solver and its preconditioner. 
Non-blocking though

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16550)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),amcastro-tri (waiting on @xuchenhan-tri)

___
*[multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc, line 171 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16550#-Mvcw2mT5nDQ7yECHsGf:-MveK7Dm678Aqqr6Doha:b-xe9l74) ([raw file](https://github.com/robotlocomotion/drake/blob/d5ecf273e0eb2e12aec92a1247a673134ac85bf7/multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc#L171)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

right, I was suggesting that the semantics of those methods was more like "return the last type used in a Solve() call", since you do store the solver and its preconditioner. 
Non-blocking though
</blockquote></details>

Right now I don't quite see the use of that semantic (other than for testing purpose like you mentioned). We can add it in the future if it turns out to be useful.

**Pull request merged**
