### PR TITLE
Fix ongoing lanes in MonolaneOnrampExample

### LINKED ISSUE #5702: No Default Branches Specified in On-Ramp RoadGeometry
I first noticed this when trying to run a `MaliputRailcar` on an on-ramp `RoadGeometry` created by `MonolaneOnrampMerge` in #5699. It wouldn't proceed across lane boundaries because no default branch was specified. I had to modify the `MaliputRailcar` to instead select the first "ongoing" branch.

I'm not sure if the above is actually a defect. Maybe it can simply be documented? (Or is it already documented and I simply missed it?)

### PR DESCRIPTION
**Pull request by jadecastro**
resolves #5702.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5710)

### CODE REVIEW

**Comment by liangfok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/monolane_onramp_merge_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-KgpkVDqr1R1pjj83Dac:-KgpkVDqr1R1pjj83Dad:b-8ka7ej) ([raw file](https://github.com/robotlocomotion/drake/blob/e51a84d82913a952c17b743040ed557ef27b6098/drake/automotive/test/monolane_onramp_merge_test.cc#L17)):*
> ```cpp
>                               const std::string& lane_id) {
>   for (int i = 0; i < rg.num_junctions(); ++i) {
>     if (rg.junction(i)->id().id == lane_id) {
> ```

BTW, I find it odd how a "lane_id" parameter is being compared against a `Junction`'s ID. Should the parameter be named "junction_id"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jadecastro** [comment]
+@liangfok for feature review.
+@jwnimmer-tri for platform, automotive review.

**Comment by jadecastro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/monolane_onramp_merge_test.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-KgpkVDqr1R1pjj83Dac:-KgpmZDD542YY9eL0d3Y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e51a84d82913a952c17b743040ed557ef27b6098/drake/automotive/test/monolane_onramp_merge_test.cc#L17)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, I find it odd how a "lane_id" parameter is being compared against a `Junction`'s ID. Should the parameter be named "junction_id"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/automotive/monolane_onramp_merge.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-KgpvW5vOM98HpvegwQd:-KgpvW5w9d2M963lymHP:b-mano80) ([raw file](https://github.com/robotlocomotion/drake/blob/2ca551ea799bcfb65c65c75bc63a4531113e78fe/drake/automotive/monolane_onramp_merge.cc#L48)):*
> ```cpp
>   // Construct the pre-merge road.
>   const double& kPostLinearLength = 100.;
>   //const auto& pre0 =
> ```

BTW Commented-out code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-:-KgpvhA7NeQPurniobNb:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/automotive/test/monolane_onramp_merge_test.cc, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-Kgpw5uwJnN0nXsng5BM:-Kgpw5uwJnN0nXsng5BN:bv4n2nt) ([raw file](https://github.com/robotlocomotion/drake/blob/2ca551ea799bcfb65c65c75bc63a4531113e78fe/drake/automotive/test/monolane_onramp_merge_test.cc#L60)):*
> ```cpp
>       pre0->GetOngoingBranches(api::LaneEnd::kStart);
>   EXPECT_EQ(1, lanes_beyond_pre0->size());
>   EXPECT_EQ("l:post0", lanes_beyond_pre0->get(0).lane->id().id);
> ```

Can you also verify that the return values of `Lane::GetDefaultBranch()` returns valid values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jadecastro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/test/monolane_onramp_merge_test.cc, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-Kgpw5uwJnN0nXsng5BM:-KgqT_OkJkCk6x7OEvOQ:b-gd4ffy) ([raw file](https://github.com/robotlocomotion/drake/blob/2ca551ea799bcfb65c65c75bc63a4531113e78fe/drake/automotive/test/monolane_onramp_merge_test.cc#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Can you also verify that the return values of `Lane::GetDefaultBranch()` returns valid values?
</blockquote></details>

Done.  I've manually set the default branches at the merge point.Can you check if this suffices? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jadecastro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/automotive/monolane_onramp_merge.cc, line 48 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-KgpvW5vOM98HpvegwQd:-KgqU-uZgjHDpfdowotA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2ca551ea799bcfb65c65c75bc63a4531113e78fe/drake/automotive/monolane_onramp_merge.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Commented-out code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by jadecastro** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/automotive/test/monolane_onramp_merge_test.cc, line 60 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-Kgpw5uwJnN0nXsng5BM:-KgtqknP5OyLL_VvlFA5:b-19xu5k) ([raw file](https://github.com/robotlocomotion/drake/blob/2ca551ea799bcfb65c65c75bc63a4531113e78fe/drake/automotive/test/monolane_onramp_merge_test.cc#L60)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oops: 

/s/single/more than one/
</blockquote></details>

Done.  PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Comment by liangfok** [comment]
:lgtm: Note that the changes in lane names mean the following patch will need to be applied to `automotive_demo`:

https://github.com/liangfok/drake/commit/35752e5a353cb5ca20468b32e92e260238cad44e

If it is not applied in this PR, I will file a subsequent PR with it. Thanks again!

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-:-Kgu5zuz1wIjGfluyVPT:byi3myi)*

**Comment by jadecastro** [comment]
Patch applied. Thanks!

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710#-:-KguOPX9i7ukplpaaR6G:bdkjie)*

**Comment by liangfok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5710)*

**Pull request merged**
