### PR TITLE
pydrake systems: Add missing bindings to ContinuousState, DiscreteValues, VectorBase, and BasicVector

### PR DESCRIPTION
**Pull request by mpetersen94**
Addresses two check boxes for #14223

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@RussTedrake for feature review
I was bumping up against these too so decided to cross them off the list.

**Review by RussTedrake — COMMENTED** [review]
awesome.  thanks! and looks perfect to my eyes.  :lgtm:
+@sammy-tri for platform review.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MK9oWb-1CVRJCkbnmQ9:b6te1xp)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Comment by mpetersen94** [comment]
I just realized that the way I wrote the `operator[]` binding allows you to use it for accessing values but not for setting values.  How much does that impede your use case Russ?

**Review by sammy-tri — COMMENTED** [review]
:lgtm:  Would you prefer that I wait for Russ's feedback on the `operator[]` question before merging?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MKAvcKo2tmASRl2m8lp:b-u32hka)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Comment by mpetersen94** [comment]
Yes, let's wait on merge because I just found a fix to the problem.  Adding tests and will post shortly.

**Review by sammy-tri — COMMENTED** [review]
+(status: do not merge) adding Do Not Merge just to make sure I don't do it accidentally while you're updating.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MKB5l5O4QOf1S7bQLQh:bngh8co)* status: labeled "do not merge"

**Review by mpetersen94 — COMMENTED** [review]
Ok. Ready for review and merge if everyone is happy.  I also added bidings for DiscreteValues while it was compiling.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MKB6bVZ09eNylRF8GzE:b96ap29)* status: labeled "do not merge" (waiting on @RussTedrake and @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
-(status: do not merge) Just one question about a doc comment.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MKBJtTi3m07YtaDj0SD:b-vabvpi)* status: 1 unresolved discussion, labeled "do not merge" (waiting on @mpetersen94)

___
*[systems/framework/discrete_values.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14231#-MKBJhwO-UDDfwRrwxKX:-MKBJhwO-UDDfwRrwxKY:b9dzc2y) ([raw file](https://github.com/robotlocomotion/drake/blob/8fdf09c3cb5021c6283911e47cca5c8f73f64034/systems/framework/discrete_values.h#L60)):*
> ```objc
>   /// Constructs a %DiscreteValues that owns the underlying @p data. Every entry
>   /// must be non-null.
>   /// @exclude_from_pydrake_mkdoc{This overload is not bound in pydrake.}
> ```

Is this also true for the overload directly above?  (1arg `data`)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231#-:-MKBY0OABg28BizcTc1w:bnfp4nl)* status: 1 unresolved discussion (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231)* status: 1 unresolved discussion (waiting on @RussTedrake and @sammy-tri)

___
*[systems/framework/discrete_values.h, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14231#-MKBJhwO-UDDfwRrwxKX:-MKC-YFd592blxyRksOi:b2rohoj) ([raw file](https://github.com/robotlocomotion/drake/blob/8fdf09c3cb5021c6283911e47cca5c8f73f64034/systems/framework/discrete_values.h#L60)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this also true for the overload directly above?  (1arg `data`)
</blockquote></details>

Done.  Initially I tried binding the other which caused some seg faults. Binding this one and excluding the other works better.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14231)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),RussTedrake(platform)

**Pull request merged**
