### PR TITLE
[parsing] PackageMap better encapsulates PackageData

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/15774 and https://github.com/RobotLocomotion/drake/issues/9498.

See for the https://github.com/RobotLocomotion/drake/pull/18955 next PR that takes advantage of the encapsulation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-:-NQzobdQDmd-HhHzgTbH:bnfp4nl)* status: 3 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/package_map.cc` line 74 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzkiwICZRrpbN5gKC9:-NQzkiwICZRrpbN5gKCA:bvbclxm) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L74)):*
> ```cpp
>   const std::string& display_path() const { return path_; }
> 
>   /* Returns true iff `other` specifies a suitably identical pacakge to `this`
> ```

typo (my old nemesis =P )



_Suggestion:_
```cpp
package
```
___
*[`multibody/parsing/package_map.cc` line 224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQznUgHCq4Sbe-Tla_b:-NQznUgHCq4Sbe-Tla_c:b-nsjgah) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L224)):*
> ```cpp
>   // deprecation status. For that data, we'll take it from either party.
>   if (!this->is_deprecated() && other.is_deprecated()) {
>     set_deprecation(other.get_deprecation());
> ```

nit this branch is not covered by unit tests. Should I worry?
___
*[`multibody/parsing/test/package_map_test.cc` line 169 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQznFMa1paccBWDLe1c:-NQznFMa1paccBWDLe1d:b-7ilvfu) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/test/package_map_test.cc#L169)):*
> ```cpp
> 
> // Default-constructed maps must always be merge-able.
> GTEST_TEST(PackageMapTest, AddDefauledMaps) {
> ```

typo?



_Suggestion:_
```cpp
AddDefaultConstructedMaps
```

**Review by rpoyner-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review, by schedule.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-:-NQzp1jWEyQZFtadRhxN:bv840px)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`multibody/parsing/package_map.cc` line 74 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzkiwICZRrpbN5gKC9:-NQzr94s9enILprIyrt9:b-bgpkhz) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L74)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

typo (my old nemesis =P )
</blockquote></details>

Hah!  One finally escaped.
___
*[`multibody/parsing/package_map.cc` line 224 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQznUgHCq4Sbe-Tla_b:-NQzxrGd7kpmZ8RYNMlV:b-dtkdrq) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L224)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit this branch is not covered by unit tests. Should I worry?
</blockquote></details>

Done, thanks.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Some ticky nacky details/questions.

> Reviewed 4 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-:-NR-GR5D7gW5bFvSGzlc:b-7daw4l)* status: 9 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/package_map.h` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-Fik_8eT2HCPi3Pyx:-NR-Fik_8eT2HCPi3Pyy:b-9s2kkw) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd972a79e39dd18913663283906796b6f6678606/multibody/parsing/package_map.h#L73)):*
> ```objc
>   /** Adds package->path mappings from another PackageMap `other_map`. Throws
>   if the other PackageMap contains the same package with a different path. */
>   void AddMap(const PackageMap& other_map);
> ```

BTW This makes no promises about deprecation status. Should it?
___
*[`multibody/parsing/package_map.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzt3pZ18CKJHjwXs5l:-NQzt3pZ18CKJHjwXs5m:b-rwmeou) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L50)):*
> ```cpp
> 
>   // Does not support assignment.
>   void operator=(const PackageData&) = delete;
> ```

nit:

- Missing move assignment deletion.

Tangential btw:
- I'm kind of surprised at this spelling with the return value of void. It's compact, but I'm not sure it's what the average C++ developer would expect to see. Admittedly, they may simply see the comment and the "delete" and not even give the return value a second thought.
___
*[`multibody/parsing/package_map.cc` line 61 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzuYn80F-UrJ3l0cxk:-NQzuYn80F-UrJ3l0cxl:b-hzivgk) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L61)):*
> ```cpp
>   }
> 
>   /* Sets the deprecation status and message for this package; if deprecated
> ```

BTW Is it sufficiently clear that `nullopt` *clears* the deprecation status? It's internal and defined right here, so someone reading the doc can make immediate reference to the implementation, so even if that aspect lacks explicit clarity, the cost is arguably low.
___
*[`multibody/parsing/package_map.cc` line 76 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzvaXQ6ihCGPJ3CdDp:-NQzvaXR-Ey6SU4efrmy:btcf6x) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L76)):*
> ```cpp
>   /* Returns true iff `other` specifies a suitably identical pacakge to `this`
>   such that we can fold the two together: the path specification
>   must match, but the deprecation or fetch status can differ. In
> ```

BTW Is this reference to "fetch" status an allusion to subsequent PRs? (I know you mentioned one, but this seemed a small enough issue, I thought I'd just ask.)
___
*[`multibody/parsing/package_map.cc` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzwBxX3zVL77wcef6J:-NQzwBxX3zVL77wcef6K:b-9kvmt6) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L102)):*
> ```cpp
> }  // namespace
> 
> struct PackageMap::Impl {
> ```

nit: Strictly speaking, `Emplace` means this doesn't get to be a `struct` anymore.
___
*[`multibody/parsing/package_map.cc` line 115 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzweq_405kiZ8P9aWn:-NQzweqa1-hOqe8SZTOt:b2jpxcm) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L115)):*
> ```cpp
>             "PackageMap::Add() cannot add '{}' {}", package_name, error));
>       }
>       // The package already exists; since the new package cannot have a
> ```

This comment and test don't make sense to me.

Why is the deprecation status of `data` important when we are otherwise ignoring it? The data in the map may or may not be deprecated already and this subsequent invocation doesn't seem to change it. So, what is the significance of this test?
___
*[`multibody/parsing/package_map.cc` line 121 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzx7DR7kuwxZeGAROK:-NQzx7DS9-ef2SrRpVdh:b1asmjt) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L121)):*
> ```cpp
>     }
> 
>     // Everything checks out, so we can add it now.
> ```

nit: "Everything checks out" is not quite the condition for which we reach this line. The only reason we get here is because `package_name` is *new*.
___
*[`multibody/parsing/package_map.cc` line 222 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-Bo5K2l49MOt8BiZC:-NR-Bo5K2l49MOt8BiZD:b-qlk0ht) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L222)):*
> ```cpp
> 
>   // The paths are equivalent. The only thing remaining to merge is the
>   // deprecation status. For that data, we'll take it from either party.
> ```

btw: The word "data" in a class called `PackageData` is a bit confusing. The semantics as I understand them are that the result is deprecated if either instance was deprecated. The message is arbitrarily one of the two and we don't care. The code happens to bias toward the pre-existing deprecation message. That could be clearer.

```c++
  // The equivalent paths now need to merge deprecation status. The result is
  // deprecated if this or other are deprecated. This implementation favors
  // this's deprecation message (if it exists), but otherwise doesn't care.
```
___
*[`multibody/parsing/test/package_map_test.cc` line 255 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-FCl52YsXe2xsXLSE:-NR-FCl52YsXe2xsXLSF:b-lf9bj6) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/test/package_map_test.cc#L255)):*
> ```cpp
>   EXPECT_EQ(dut.GetDeprecated("hats").value_or(""), "I like hats.");
> 
>   // Ditto even if a different message is merged in.
> ```

BTW This test almost makes it look like the preference for the old deprecation message should be a preserved feature. Is that the intent? Alternatively, it could be phrased as "it's one of two tests in a set" to support the documented behavior.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @rpoyner-tri and @SeanCurtis-TRI)

___
*[`multibody/parsing/package_map.h` line 73 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-Fik_8eT2HCPi3Pyx:-NR-JPx28jKCa-YtOdnz:b-1sx2pu) ([raw file](https://github.com/RobotLocomotion/drake/blob/dd972a79e39dd18913663283906796b6f6678606/multibody/parsing/package_map.h#L73)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This makes no promises about deprecation status. Should it?
</blockquote></details>

I don't think any user would expect deprecation annotations to disappear across a merge, and I don't think the specifics of how we merge two deprecation messages are an important part of the contract.  (If we come up with better heuristics later, we should be free to change it up without fussing over the API docs here.)
___
*[`multibody/parsing/package_map.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzt3pZ18CKJHjwXs5l:-NR-H4s-2-0rChe8D6s2:b-513f4d) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L50)):*
Deleting copy-assign deletes move-assign as well.  I suppose the defect is in clarity for the reader of that fact?

Fixed with comment.

> I'm kind of surprised at this spelling with the return value of void.

https://github.com/RobotLocomotion/drake/blob/9755974392773b6c9d0bcff7c420ffc4511d1245/common/drake_copyable.h#L35
___
*[`multibody/parsing/package_map.cc` line 102 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzwBxX3zVL77wcef6J:-NR-Nb086YMqXyn1O6wc:b-vl3cd7) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L102)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Strictly speaking, `Emplace` means this doesn't get to be a `struct` anymore.
</blockquote></details>

Done.  Now any non-const functions are forwarded to the Impl to be handled.
___
*[`multibody/parsing/package_map.cc` line 115 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzweq_405kiZ8P9aWn:-NR-KPkZ00t8gvvDMEba:bx3kqgv) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This comment and test don't make sense to me.

Why is the deprecation status of `data` important when we are otherwise ignoring it? The data in the map may or may not be deprecated already and this subsequent invocation doesn't seem to change it. So, what is the significance of this test?
</blockquote></details>

This was meant to be a pre-condition; hopefully it's clearer now that its atop the function.
___
*[`multibody/parsing/test/package_map_test.cc` line 255 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-FCl52YsXe2xsXLSE:-NR-JC7v6d_yiS_jXzxO:bk4qwoc) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/test/package_map_test.cc#L255)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This test almost makes it look like the preference for the old deprecation message should be a preserved feature. Is that the intent? Alternatively, it could be phrased as "it's one of two tests in a set" to support the documented behavior.
</blockquote></details>

Yes, that's the intent.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`multibody/parsing/package_map.cc` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzt3pZ18CKJHjwXs5l:-NR-hguU6nKFubvtzRMW:b-lxrfbu) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L50)):*
I was thinking in terms of the text of our styleguide (emphasis mine):

> Failing that, it should take the form of __*explicitly*__ declaring and/or deleting the appropriate operations in the public section of the declaration.

What's the definition of "explicit" in this case? Explicit communication to the compiler or explicit communication to the reader? This certainly satisfies but arguably only satisfies the latter for a subset of readers.

But, I'm marking myself satisfied.
___
*[`multibody/parsing/package_map.cc` line 115 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NQzweq_405kiZ8P9aWn:-NR-jjvt4mvW5dG46fnD:b-eji098) ([raw file](https://github.com/RobotLocomotion/drake/blob/fde391dd80a20cd77aa8db6d8bf0d51514ee9f48/multibody/parsing/package_map.cc#L115)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This was meant to be a pre-condition; hopefully it's clearer now that its atop the function.
</blockquote></details>

Yep. That works.
___
*[`multibody/parsing/package_map.cc` line 110 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-irxp0EzFmnqzM_Xu:-NR-irxq56ZfwswEfV-C:b-5zoq50) ([raw file](https://github.com/RobotLocomotion/drake/blob/8203f9fb30436af9afdc0b89581ae73ccf64c32a/multibody/parsing/package_map.cc#L110)):*
> ```cpp
>   Impl(Impl&&) = default;
> 
>   // Does not support copy-assignment nor move-assignment.
> ```

nit: Mixed commenting style (and on the constructors above.
___
*[`multibody/parsing/package_map.cc` line 114 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-iyo-21okbYuiEvzi:-NR-iyo-21okbYuiEvzj:bxs3jvi) ([raw file](https://github.com/RobotLocomotion/drake/blob/8203f9fb30436af9afdc0b89581ae73ccf64c32a/multibody/parsing/package_map.cc#L114)):*
> ```cpp
> 
>   /* Read-only access to the underlying map. This allows the PackageMap's const
>   member functions to do their job without fowarding them all to the Impl. */
> ```

nit: typo



_Suggestion:_
```cpp
forwarding
```

**Comment by SeanCurtis-TRI** [comment]
*[`multibody/parsing/package_map.cc` line 110 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-NR-irxp0EzFmnqzM_Xu:-NR-kCBN6VqfuAt3kWWk:byb2yoc) ([raw file](https://github.com/RobotLocomotion/drake/blob/8203f9fb30436af9afdc0b89581ae73ccf64c32a/multibody/parsing/package_map.cc#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Mixed commenting style (and on the constructors above.
</blockquote></details>

But this is rife throughout the file.  So, I'm changing it to a BTW.

**Comment by jwnimmer-tri** [comment]
FYI This still needs your emoji @SeanCurtis-TRI.

**Review by jwnimmer-tri — COMMENTED** [review]
(That's why I'd advocate for a best practice / habit of "LGTM immediately and use discussion threads to hold it open".  Next time I'm in the control panel I'll see if I can make the lack of LGTM more prominent, too.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19020#-:-NR-pAml1LXYfJysd8iB:bijqj4)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
