### PR TITLE
Fix for #2672

### LINKED ISSUE #2672: Warning for potentialCollisionPoints in Windows builds
@sherm1 brought this to my attention. In windows builds we get the warning:

```
DrakeCollision.cpp

..\..\drake/systems/plants/collision/bullet_model.h(120): warning C4373: 'DrakeCollision::BulletModel::potentialCollisionPoints': virtual function overrides 'DrakeCollision::Model::potentialCollisionPoints', previous versions of the compiler did not override when parameters only differed by const/volatile qualifiers

c:\projects\workspace\experimental\a99ae8ad\drake\systems\plants\collision\Model.h(145): note: see declaration of 'DrakeCollision::Model::potentialCollisionPoints'
```

See for instance [here](https://drake-cdash.csail.mit.edu/viewBuildError.php?type=1&buildid=42360).

### PR DESCRIPTION
**Pull request by amcastro-tri**
Fixes #2672 

However, is there a way to trigger this warning also for gcc/clang compilers?

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2673)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@david-german-tri since you are the platform reviewer of the day.
+@sherm1 for feature review since you brought it to my attention. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLMTY9SlTGPjvKugPWf:1363351633)*

**Comment by jwnimmer-tri** [comment]
> However, is there a way to trigger this warning also for gcc/clang compilers?

I would start by using `override` instead of `virtual`, as required by cppguide[1], and see what GCC / Clang say then.

[1] https://google.github.io/styleguide/cppguide.html#Inheritance

**Comment by amcastro-tri** [comment]
It is marked as override [here](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/collision/bullet_model.h#L121).
Notice that none of the (virtual) methods in [Model](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/collision/Model.h#L16) are pure virtual but have a real bad default implementation. I just pushed a fix to that. PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLMWBxtbq1B-m4r9ypi:-1682168821)*

**Comment by jwnimmer-tri** [comment]
I don't immediately see a clang warning for this: https://gist.github.com/d0k/3608547

But possibly with the new pureness something would be better.  In any case, I don't have an answer right now.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLMcC6apO-X6-youCbT:328615015)*

**Comment by jwnimmer-tri** [comment]
Actually, upon further reflection -- as long as all of the overriding methods are tagged with `override`, I can't see why we need any other kind of warning.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLMeO13OwOYxz0zZGWO:-1718317457)*

**Comment by sherm1** [comment]
Feature: one backwards assert condition. Otherwise :lgtm:.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-KLMguUbNO3ffiDx_SVE:-KLMguUbNO3ffiDx_SVF:-380853329) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0514d07cc432d7d16b643ccb9ea40b2942ebcc/drake/systems/plants/collision/DrakeCollision.cpp#L45)):*
> ```cpp
>   return newModel(BULLET);
> #else
>   DRAKE_ABORT_UNLESS("DrakeCollision must be compiled with Bullet.");
> ```

"abort unless" has the same signature as "assert" -- `true` means everything is fine. Since a string literal is a non-zero pointer this condition is always true and will never abort. I think you meant `!"DrakeCollision must ..."` to force abort here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLMiG13HV_8mmAhYbSP:-2077904350)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 45 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-KLMguUbNO3ffiDx_SVE:-KLMnIJG3OHT9Y-tNXAi:350885795) ([raw file](https://github.com/robotlocomotion/drake/blob/8d0514d07cc432d7d16b643ccb9ea40b2942ebcc/drake/systems/plants/collision/DrakeCollision.cpp#L45)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> "abort unless" has the same signature as "assert" -- `true` means everything is fine. Since a string literal is a non-zero pointer this condition is always true and will never abort. I think you meant `!"DrakeCollision must ..."` to force abort here. 
</details>
You are right! fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673)*

**Comment by sherm1** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 6 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-KLNHGWRcgA6TX_cJpEc:-KLNHGWRcgA6TX_cJpEd:1549212949) ([raw file](https://github.com/robotlocomotion/drake/blob/fe68e158126d031839c482dfb5cb4c37527e44bd/drake/systems/plants/collision/DrakeCollision.cpp#L6)):*
> ```cpp
> #include "drake/systems/plants/collision/DrakeCollision.h"
> 
> #ifdef BULLET_COLLISION
> ```

BTW, does this `#ifdef` serve a purpose?  You might be able to just delete it (and avoid the awkward string-to-bool thing below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-:-KLNHPxMbuHWx6OO-tpL:1417088721)*

**Comment by amcastro-tri** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[drake/systems/plants/collision/DrakeCollision.cpp, line 6 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2673#-KLNHGWRcgA6TX_cJpEc:-KLNRWcuU0q3TDUddYkQ:185239949) ([raw file](https://github.com/robotlocomotion/drake/blob/fe68e158126d031839c482dfb5cb4c37527e44bd/drake/systems/plants/collision/DrakeCollision.cpp#L6)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> BTW, does this `#ifdef` serve a purpose?  You might be able to just delete it (and avoid the awkward string-to-bool thing below).
</details>
It is. `DrakeCollision.h` includes a number of Bullet headers that won't be available if the user does not compile with Bullet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2673)*

**Pull request merged**
