### PR TITLE
Add scs external

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #3773. I strongly anticipate that we will choose one of `:scsdir` and `:scsindir` after initial testing (I do not think they will really coexist well in any case), so I have deliberately not factored out the commonality between them. Note that the direct linear system solver (used by `:scsdir`) contains LGPL v2.1+ code. FYI @hongkai-dai.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7419)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRcKNbEail-rDtioO-:b-g89j1u) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
> ```Python
>     modname = "lapack-netlib",
> )
> ```

On one computer, at the moment, I have:
```console
jwnimmer@call-cps:~$ ls -l {/usr/lib/pkgconfig/,/etc/alternatives/}*{blas,lapack}*.pc
lrwxrwxrwx 1 root root  32 Apr  7  2017 /etc/alternatives/blas.pc -> /usr/lib/pkgconfig/blas-atlas.pc
lrwxrwxrwx 1 root root  34 Apr  7  2017 /etc/alternatives/lapack.pc -> /usr/lib/pkgconfig/lapack-atlas.pc
-rw-r--r-- 1 root root 302 Nov 23  2015 /usr/lib/pkgconfig/blas-atlas.pc
-rw-r--r-- 1 root root 207 Jan 16  2016 /usr/lib/pkgconfig/blas-netlib.pc
lrwxrwxrwx 1 root root  25 Apr  7  2017 /usr/lib/pkgconfig/blas.pc -> /etc/alternatives/blas.pc
-rw-r--r-- 1 root root 214 Sep 14  2016 /usr/lib/pkgconfig/cublas-8.0.pc
-rw-r--r-- 1 root root 308 Nov 23  2015 /usr/lib/pkgconfig/lapack-atlas.pc
-rw-r--r-- 1 root root 213 Jan 16  2016 /usr/lib/pkgconfig/lapack-netlib.pc
lrwxrwxrwx 1 root root  27 Apr  7  2017 /usr/lib/pkgconfig/lapack.pc -> /etc/alternatives/lapack.pc
```

I don't know whether we care about netlib or atlas, but there is at least one problem with the PR as-is:

```
jwnimmer@call-cps:~$ grep Requires /usr/lib/pkgconfig/lapack-netlib.pc 
Requires: blas
```

That means that even if we specify blas-netlib and lapack-netlib, pkg-config will give us the alternatives flavor of blas as well, due to that Requires.  And in my case that would also bring in the atlas flavor and its `-L` flag, which seems poor.

---

*[drake/solvers/scs_solver.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRb2ZFApYKALECV_4B:-KyRb2ZGdnWJXIlKUCu-:b-2ovz7b) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/drake/solvers/scs_solver.h#L3)):*
> ```objc
> #pragma once
> 
> #include <string>
> ```

BTW Unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRg0KKwIk0JbM2bdth:b3grlit) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On one computer, at the moment, I have:
```console
jwnimmer@call-cps:~$ ls -l {/usr/lib/pkgconfig/,/etc/alternatives/}*{blas,lapack}*.pc
lrwxrwxrwx 1 root root  32 Apr  7  2017 /etc/alternatives/blas.pc -> /usr/lib/pkgconfig/blas-atlas.pc
lrwxrwxrwx 1 root root  34 Apr  7  2017 /etc/alternatives/lapack.pc -> /usr/lib/pkgconfig/lapack-atlas.pc
-rw-r--r-- 1 root root 302 Nov 23  2015 /usr/lib/pkgconfig/blas-atlas.pc
-rw-r--r-- 1 root root 207 Jan 16  2016 /usr/lib/pkgconfig/blas-netlib.pc
lrwxrwxrwx 1 root root  25 Apr  7  2017 /usr/lib/pkgconfig/blas.pc -> /etc/alternatives/blas.pc
-rw-r--r-- 1 root root 214 Sep 14  2016 /usr/lib/pkgconfig/cublas-8.0.pc
-rw-r--r-- 1 root root 308 Nov 23  2015 /usr/lib/pkgconfig/lapack-atlas.pc
-rw-r--r-- 1 root root 213 Jan 16  2016 /usr/lib/pkgconfig/lapack-netlib.pc
lrwxrwxrwx 1 root root  27 Apr  7  2017 /usr/lib/pkgconfig/lapack.pc -> /etc/alternatives/lapack.pc
```

I don't know whether we care about netlib or atlas, but there is at least one problem with the PR as-is:

```
jwnimmer@call-cps:~$ grep Requires /usr/lib/pkgconfig/lapack-netlib.pc 
Requires: blas
```

That means that even if we specify blas-netlib and lapack-netlib, pkg-config will give us the alternatives flavor of blas as well, due to that Requires.  And in my case that would also bring in the atlas flavor and its `-L` flag, which seems poor.
</blockquote></details>

So you are staying that you would prefer to just query `blas.pc` and `lapack.pc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRgrWmYG6m2BaxliQE:b-2586yj) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So you are staying that you would prefer to just query `blas.pc` and `lapack.pc`?
</blockquote></details>

I haven't looked at it enough to come to an opinion, just looking for your inputs here at the moment.  The inconsistency seems wrong, so if we do really want netlib flavor then we'll have to tweak this to make sure atlas doesn't come in accidentally, I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRiYBVhXAnXld--7EC:bq9plc6) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I haven't looked at it enough to come to an opinion, just looking for your inputs here at the moment.  The inconsistency seems wrong, so if we do really want netlib flavor then we'll have to tweak this to make sure atlas doesn't come in accidentally, I think?
</blockquote></details>

I was going by the packages in the setup scripts, but they are not executed in a vacuum, so there may be other versions of BLAS etc. and not sure fighting against the alternatives mechanism is going to be a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRpgU9V2iqbMrNqdxP:b-osp9nr) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I was going by the packages in the setup scripts, but they are not executed in a vacuum, so there may be other versions of BLAS etc. and not sure fighting against the alternatives mechanism is going to be a good idea.
</blockquote></details>

That sounds to me like an argument for just using `blas` and `lapack` here, then?  The prereqs script will provide them (via alternatives), and the default use of pkg-config will work as intended.

I believe the the pc file and so file are also slaved in the alternatives mechanism, so it means that dynamic linking would also remain in sync.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[WORKSPACE, line 265 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRcKNa0iMEuT1mkdG0:-KyRrR39dE-NRRg7qa3H:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/WORKSPACE#L265)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That sounds to me like an argument for just using `blas` and `lapack` here, then?  The prereqs script will provide them (via alternatives), and the default use of pkg-config will work as intended.

I believe the the pc file and so file are also slaved in the alternatives mechanism, so it means that dynamic linking would also remain in sync.
</blockquote></details>

Done.

---

*[drake/solvers/scs_solver.h, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRb2ZFApYKALECV_4B:-KyRrRdwksEDM4ZGgway:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cd574b950359ed08e7ef792aa62c585759829864/drake/solvers/scs_solver.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Unused?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KyRuUGJMjb0CdBrxU9Y:bviiive) (no related file):*
On Ubuntu at least, the AMD and LDL code is already available in `libsuitesparse-dev`, `libcamd2`, `libldl2` with ~3 years newer versions:
- SDS vendored AMD 2.3.1
- Xenial AMD 2.4.6
- SDS vendored LDL 2.1.0
- Xenial LDL 2.2.6

I think at minimum we should have a TODO somewhere here (scs.BUILD.bazel?) to use the system versions, for both modernity and symbol compatibility.  (TRI uses those shared libraries at runtime already in other projects.)

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRvy-E1IcVQrNVbUfh:-KyRvy-E1IcVQrNVbUfi:b-go5u8c) (no related file):*
If I am correctly interpreting my ELF tool outputs with respect to `libdrake.so`, I believe we are statically linking AMD and LDL sources into `libdrake.so`, even though they are LGPL-2.1+.  There are many distribution scenarios where that is fine (e.g., if all source code is available anyway), but I think because for example we are publishing releases with SNOPT included, it's not fine?  At least not under old LGPL 2.1.  Admittedly I haven't recently studied what opting into the LGPL 3.0 upgrade does for this situation, so maybe my understanding it dated.  Do you happen to know?

I think we already have this same situation with LCM, though, so perhaps not worth holding up this PR for?  But if you agree its a problem, perhaps we should at least open an issue; it seems like the solution would be changing our LGPL externals to be linked dynamically.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRt2RsIDZLu3KexdAD:-KyRt2RsIDZLu3KexdAE:b-oj6n77) ([raw file](https://github.com/robotlocomotion/drake/blob/375027bb4189a45793aae6462fe5052cc937cecc/tools/workspace/scs/scs.BUILD.bazel#L96)):*
> ```
>     hdr_dest = "include/scs",
>     hdr_strip_prefix = ["include"],
>     guess_hdrs = "PACKAGE",
> ```

As it stands, the install rule is installing headers under `include/scs/linsys/...` that are coming from the `srcs = glob(...)` attributes of the rules.  Is this intended?  It seems like not, because with the way we are linking, the user could not anyway provide their own linSys.h back-end implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KyS0ufhTJz6CaaKhQOc:b-vtxm92) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

On Ubuntu at least, the AMD and LDL code is already available in `libsuitesparse-dev`, `libcamd2`, `libldl2` with ~3 years newer versions:
- SDS vendored AMD 2.3.1
- Xenial AMD 2.4.6
- SDS vendored LDL 2.1.0
- Xenial LDL 2.2.6

I think at minimum we should have a TODO somewhere here (scs.BUILD.bazel?) to use the system versions, for both modernity and symbol compatibility.  (TRI uses those shared libraries at runtime already in other projects.)
</blockquote></details>

I guess we would have to pull in `suite-sparse` from on Mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KyS4A7k0o3PCvuORUGQ:b-t45qni) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I guess we would have to pull in `suite-sparse` from on Mac.
</blockquote></details>

Fine by me.  I see that is the much-newer 4.5.5, hopefully it works OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KyS86SJkMm03cpMMfQM:b-im990j) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Fine by me.  I see that is the much-newer 4.5.5, hopefully it works OK.
</blockquote></details>

Looks like we would need to send a patch upstream to use a non-vendored AMD and LDL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KySFCgN4-IG6Qe2DG6j:blgvkre) (no related file):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Looks like we would need to send a patch upstream to use a non-vendored AMD and LDL.
</blockquote></details>

Maybe a TODO is most efficient then, since we might not use direct anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jamiesnape** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRvy-E1IcVQrNVbUfh:-KyW6GOJgmPg6bXvOEAp:b-juvd4q) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If I am correctly interpreting my ELF tool outputs with respect to `libdrake.so`, I believe we are statically linking AMD and LDL sources into `libdrake.so`, even though they are LGPL-2.1+.  There are many distribution scenarios where that is fine (e.g., if all source code is available anyway), but I think because for example we are publishing releases with SNOPT included, it's not fine?  At least not under old LGPL 2.1.  Admittedly I haven't recently studied what opting into the LGPL 3.0 upgrade does for this situation, so maybe my understanding it dated.  Do you happen to know?

I think we already have this same situation with LCM, though, so perhaps not worth holding up this PR for?  But if you agree its a problem, perhaps we should at least open an issue; it seems like the solution would be changing our LGPL externals to be linked dynamically.
</blockquote></details>

The direct solver version is built exclusively as a shared library now.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRuUGI1b_9eX1r7TOR:-KyW6PiwepaLSlj0X9Lc:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe a TODO is most efficient then, since we might not use direct anyway.
</blockquote></details>

Done.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 96 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyRt2RsIDZLu3KexdAD:-KyW6RTuIUeBVyjHozrh:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake/blob/375027bb4189a45793aae6462fe5052cc937cecc/tools/workspace/scs/scs.BUILD.bazel#L96)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

As it stands, the install rule is installing headers under `include/scs/linsys/...` that are coming from the `srcs = glob(...)` attributes of the rules.  Is this intended?  It seems like not, because with the way we are linking, the user could not anyway provide their own linSys.h back-end implementation.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by jwnimmer-tri** [comment]
:lgtm: should be ready for platform review +@soonho-tri.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-KyW8W31NOVYXNEZ0PAb:b-6754fp)*

**Comment by jwnimmer-tri** [comment]
FYI We should probably re-run the Mac builders, prior to the final merge.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-bazel-experimental please
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please
@drake-jenkins-bot mac-sierra-clang-cmake-experimental please

**Comment by jamiesnape** [comment]
True, for the record, local testing was on High Sierra.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-elcapitan-clang-cmake-experimental please

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r1, 2 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 56 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyWqK6ysiyugXW2MioG:-KyWqK6ysiyugXW2MioH:bwri2u) ([raw file](https://github.com/robotlocomotion/drake/blob/e4e9bcf46d23a44277c36a90309eba6f02c94144/tools/workspace/scs/scs.BUILD.bazel#L56)):*
> ```
>             "@blas",
>             "@lapack",
>         ],
> ```

Could you explain why we don't need `@blas` and `@lapack` in macOS?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-KyWqVQ4jv6jLkeFOc2Z:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 56 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyWqK6ysiyugXW2MioG:-KyWrofi4IB0QY1sgg6P:bce5fvw) ([raw file](https://github.com/robotlocomotion/drake/blob/e4e9bcf46d23a44277c36a90309eba6f02c94144/tools/workspace/scs/scs.BUILD.bazel#L56)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Could you explain why we don't need `@blas` and `@lapack` in macOS?
</blockquote></details>

https://developer.apple.com/documentation/accelerate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/scs/scs.BUILD.bazel, line 56 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-KyWqK6ysiyugXW2MioG:-KyWs3DRvu-PoCZU-Bn3:b-jhyyta) ([raw file](https://github.com/robotlocomotion/drake/blob/e4e9bcf46d23a44277c36a90309eba6f02c94144/tools/workspace/scs/scs.BUILD.bazel#L56)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

https://developer.apple.com/documentation/accelerate
</blockquote></details>

Got it. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419)*

**Comment by soonho-tri** [comment]
FYI, @hongkai-dai, it's in now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-KyX4UdiK20hoO23XtYM:b-r6pwff)*

**Comment by hongkai-dai** [comment]
Thanks @soonho-tri , I am working on the `scs_solver.cc` to add the solver wrapper

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-KyXBQmyy-vGj3RTH5J2:boc0v2o)*

**Comment by RussTedrake** [comment]
@hongkai-dai -- please also add SCS to the support matrix in http://drake.mit.edu/doxygen_cxx/group__solvers.html .

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-Kyufp4fJ6He3YUkzKlm:bkpxbpk)*

**Comment by hongkai-dai** [comment]
@russtedrake , I will add it with the PR https://reviewable.io/reviews/RobotLocomotion/drake/7447#-

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7419#-:-KyvHwCadUGp0M-vhKad:b-2ky7lm)*

**Pull request merged**
