### PR TITLE
Port more files to use drake_add_cc_test

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Fix rule-of-19 violation by removing duplicated code.  This is a follow-up to #3633, which was the boilerplate fixes.  This PR is a bit more individualized changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3634)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for all review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-:-KSstuqUXHy-mDpoiN3N:b-7ewwmf)*

**Comment by jwnimmer-tri** [comment]
Actually, also +@jamiesnape for feature review of the test.cmake changes, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-:-KSsu4ZmYWhPbhP7B1Dv:b-wcvn06)*

**Comment by jamiesnape** [comment]
One minor comment on style, otherwise :lgtm: 

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/test.cmake, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-KSvGMGoEq5w-nQDzF-W:-KSvGMGpWmWCD0VhUpy5:bkv4j24) ([raw file](https://github.com/robotlocomotion/drake/blob/7781e73d9a9a1a664ce2496dc7e90172ebe359d0/cmake/test.cmake#L134)):*
> ```CMake
> 
>   if(NOT _EXTENSION)
>     set (_EXTENSION "cc")
> ```

Style: `set(_EXTENSION cc)` (no space between set and ( and no quotes needed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-:-KSvGYY4pbklMHE8e--n:b-i3nraf)*

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/test.cmake, line 134 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-KSvGMGoEq5w-nQDzF-W:-KSvNri7Z64f7hgL8j_c:b-sr0vuv) ([raw file](https://github.com/robotlocomotion/drake/blob/7781e73d9a9a1a664ce2496dc7e90172ebe359d0/cmake/test.cmake#L134)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Style: `set(_EXTENSION cc)` (no space between set and ( and no quotes needed)
</details>
Thanks!  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-:-KSvO7Wb5p4vtTOK65kr:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3634#-:-KTA7uVxXD05G6igY0A1:bnfp4nl)*

**Pull request merged**
