### PR TITLE
Fixed location of citation.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2406)

### CODE REVIEW

**Comment by liangfok** [comment]
This is such a small change that I'm thinking +@jwnimmer-tri can handle both feature / platform review.

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> #### Fixed location of citation\.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2406#-:-KI9wmZNnavSl2WKPLLc:2062837589)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This is such a small change that I'm thinking +@jwnimmer-tri can handle both feature / platform review.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2406#-:-KIA60QrFviSrTXowNwk:1417088721)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2406)*

**Comment by david-german-tri** [comment]
Merging without waiting for Jenkins.  Thanks for catching this.

**Pull request merged**
