### PR TITLE
Per issue #13646, throw an exception if composite_mass <= 0.

### PR DESCRIPTION
**Pull request by mitiguy**
Per issue #13646, throw an exception if composite_mass <= 0.
This PR #14316 resolves issue #13646.
Note: Since I am currently working on center of mass methods, this is an opportune time to address issue #13646.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Tagging "do not review" until a feature reviewer gets assigned.

**Review by mitiguy — COMMENTED** [review]
Feature review: +@sherm1 
This PR addresses issue #13646 and relates to work in PR#14268.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316#-:-MMJh8LY1vybOlq_Db5N:bwocgom)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Feature :lgtm:. I like the little cleanups here too -- thanks!
+@rpoyner-tri for platform review, please.

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316#-:-MMMEY6J6fJXPpH5FX5H:b-tt3bbd)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316)* status: LGTM missing from assignee rpoyner-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316#-:-MMMZMmP8zochmQuoH-C:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14316#-MMMyPWt9yjeccPCmk3f:-MMMyPWt9yjeccPCmk3g:bcx8hfs) (no related file):*
All good except for having multiple commits. See https://drake.mit.edu/reviewable.html?highlight=curated#curated-commits for advice.

---

**Review by mitiguy — COMMENTED** [review]
label: +(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14316#-:-MMMwK6H9J_T9zSannr8:bow8fdy)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform)

**Pull request merged**
