### PR TITLE
Allow for new macOS versioning scheme and sync minimum compiler and CMake versions for macOS

### PR DESCRIPTION
**Pull request by jamiesnape**
Toward #13648.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14608)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
+@soonho-tri for feature review.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

BTW, could you check if we can remove these lines with this update https://github.com/RobotLocomotion/drake/blob/master/tools/macos.bazelrc#L5-L8 ?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14608#-:-MSbdJdu859fXB0NsSJ6:b-n3vm1v)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by jamiesnape — COMMENTED** [review]
Will do. I imagine we can as I don't think I have remembered to install that `bazelrc` file locally for a while.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14608#-:-MSc8vlG21DRFaeKjzTc:bmp0zya)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14608)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jamiesnape** [comment]
Looks like we are good with removing the flag. I guess you are platform reviewer today. Do you think we need one?

**Comment by soonho-tri** [comment]
I just added the `single reviewer ok` label.

**Pull request merged**
