### PR TITLE
Adds hsrb_description as an optional submodule of Drake.

### LINKED ISSUE #3984: Need drake_add_ros_package() CMake Function
# Current Description

In `drake-distro/cmake/examples.cmake`, there is a function called `drake_add_example()`. I'd like a similar method called `drake_add_ros_package()` that differs in terms of adding a submodule to `drake-distro/ros/` instead of `drake-distro/drake/examples/`.

# Deprecated Descriptions

## Version 1
In `drake-distro/cmake/examples.cmake`, I would like to generalize function `drake_add_example()` to allow the user to specify the directory in which the example's submodule is placed. It currently places all submodules in `drake-distro/drake/examples/`. For some examples that are actually ROS packages, I would like to place them in `drake-distro/ros/`. Should a new `drake_add_ros_example()` method be created? Or, should the existing method be modified to accept another parameter?

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3986)

### CODE REVIEW

**Comment by liangfok** [comment]
+@mwoehlke-kitware for feature review please since I modified the build system.
+@david-german-tri for platform review please per rotation schedule.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-:-KVW2neItkcaUKZxhHHv:b-6f1mhp)*

**Comment by david-german-tri** [comment]
Closing this (at least temporarily) pending some TRI-internal clarification.

**Comment by liangfok** [comment]
-@liangfok 
+@mwoehlke-kitware because I added `ros_package.cmake` -- Is this reasonable? Should I not add this?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-:-KWoEX7iXanCqcTYuDgz:bl7u4zv)*

**Comment by david-german-tri** [comment]
+(status: curate commits before merging) 

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.gitmodules, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoZvjpyf0-2Yuf4rgp:-KWoZsTsXahdBpctotB2:b91kp1x) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/.gitmodules#L99)):*
> ```
> 	path = externals/robotlocomotion_lcmtypes
> 	url = https://github.com/RobotLocomotion/lcmtypes.git
> [submodule "ros/hsrb_description"]
> ```

I thought you were going to put this in `externals`?

---

*[.gitmodules, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWo_YXYEGE-JL9B9yG4:-KWo_YXYEGE-JL9B9yG5:bfarqga) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/.gitmodules#L99)):*
> ```
> 	path = externals/robotlocomotion_lcmtypes
> 	url = https://github.com/RobotLocomotion/lcmtypes.git
> [submodule "ros/hsrb_description"]
> ```

CI seems sad about this, but possibly just needs to be re-triggered now that the repo is public

---

*[cmake/ros_packages.cmake, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoaCpAYPTAUbI4s_DJ:-KWoaCpB0CUw9HaUVZm6:b-vpjshr) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/cmake/ros_packages.cmake#L1)):*
> ```CMake
> # TODO(liang.fok) This file contains code that overlaps with examples.cmake.
> ```

Why not just use drake_add_external?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-:-KWoZmeJ74TyA7D9Ppe5:b-s794vx)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitmodules, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoZvjpyf0-2Yuf4rgp:-KWopSJPRKU6jDBjD5y-:b-hylavm) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/.gitmodules#L99)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I thought you were going to put this in `externals`?
</details>
Yes, I mistakenly said that this afternoon. I subsequently recalled that `hsrsb_description` _is_ a ROS package meaning placing it in `ros/` instead of `externals/` makes more sense.

---

*[.gitmodules, line 99 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWo_YXYEGE-JL9B9yG4:-KWopqA7beR1462ipujw:b4hxmh1) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/.gitmodules#L99)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> CI seems sad about this, but possibly just needs to be re-triggered now that the repo is public
</details>
I forgot that the CI servers don't have an SSH key uploaded to github and thus changed the submodule to use `https`. Hopefully it'll work now.

---

*[cmake/ros_packages.cmake, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoaCpAYPTAUbI4s_DJ:-KWosBdCa4zxxTpyc8DO:b-u86gcz) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/cmake/ros_packages.cmake#L1)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Why not just use drake_add_external?
</details>
This was a hold-over from when `hsrb_description` was private. I wanted to allow the user to disable the submodule, which I didn't think `drake_add_external` supports. Now that it's a public repo, I will try to switch to `drake_add_external`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
I'm going to apply a "Do Not Review" label to this PR while I attempt to switch to use `drake_add_external`.

**Comment by mwoehlke-kitware** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/ros_packages.cmake, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoaCpAYPTAUbI4s_DJ:-KWrwowJx7_klutzj6_r:b-fmin9e) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/cmake/ros_packages.cmake#L1)):*
> I wanted to allow the user to disable the submodule, which I didn't think `drake_add_external` supports.

That's what the `WITH_<NAME>` options do. (You do need to add such an option in `options.cmake`, but `drake_add_external` will honor it. Actually, it won't even build your external without such an option, or `ALWAYS`.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/ros_packages.cmake, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWoaCpAYPTAUbI4s_DJ:-KWs3SisbBxrp5fKRawu:bvlymdq) ([raw file](https://github.com/robotlocomotion/drake/blob/84a3591639356c545c88c1721a5edc684ea85344/cmake/ros_packages.cmake#L1)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> > I wanted to allow the user to disable the submodule, which I didn't think `drake_add_external` supports.
> 
> That's what the `WITH_<NAME>` options do. (You do need to add such an option in `options.cmake`, but `drake_add_external` will honor it. Actually, it won't even build your external without such an option, or `ALWAYS`.)
> 
</details>
Thanks. I forgot about `options.cmake`. In my latest revision, I use the `ALWAYS` flag since (1) `hsrb_description` is a public repository and should always be available and (2) there will soon be example applications in `drake-distro/drake/examples/toyota_hsr` that will always be built and use `hsrb_description`.

I hope the above is OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWs70y3ZZuEUIf5dB83:bklym1e) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
> ```CMake
> # a ROS Catkin package. For details on how to do this, see:
> # http://drake.mit.edu/from_source_ros.html.
> drake_add_external(hsrb_description PUBLIC ALWAYS
> ```

(hijacking the other thread) ...I'm not sure if this really should be `ALWAYS` vs. just defaulting to `ON`. The only `ALWAYS` we have currently is drake itself.

Will the build fail catastrophically if this isn't present? If yes, `ALWAYS` makes sense. If no, I'd consider a default-`ON` option instead. (That said, I'll also encourage additional opinions here...)

---

*[CMakeLists.txt, line 343 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs7TneiJ1dGp3HIfx2:-KWs7TneiJ1dGp3HIfx3:b-s1sgrs) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L343)):*
> ```CMake
> # http://drake.mit.edu/from_source_ros.html.
> drake_add_external(hsrb_description PUBLIC ALWAYS
>   SOURCE_DIR ${PROJECT_SOURCE_DIR}/ros
> ```

Shouldn't this be `ros/hsrb_description`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWs8esdwTGWcpkbv-K2:bmdxvkh) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> (hijacking the other thread) ...I'm not sure if this really should be `ALWAYS` vs. just defaulting to `ON`. The only `ALWAYS` we have currently is drake itself.
> 
> Will the build fail catastrophically if this isn't present? If yes, `ALWAYS` makes sense. If no, I'd consider a default-`ON` option instead. (That said, I'll also encourage additional opinions here...)
</details>
I suppose I can always guard the building of all HSR examples in Drake based on `WITH_HSRB_DESCRIPTION` to prevent catastrophic failure if `hsrb_description` is not present.

---

*[CMakeLists.txt, line 343 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs7TneiJ1dGp3HIfx2:-KWsA2cLaKdoaWGUUn-2:bd838xe) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L343)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> Shouldn't this be `ros/hsrb_description`?
</details>
When I switch this to use `ros/hsrb_description`, I encounter the following error:

```
-- Preparing to build hsrb_description
CMake Error at cmake/externals.cmake:441 (file):
  file RELATIVE_PATH must be passed a full path to the file:
  ros/hsrb_description
Call Stack (most recent call first):
  CMakeLists.txt:342 (drake_add_external)


CMake Error at cmake/externals.cmake:445 (drake_add_submodule):
  drake_add_submodule Function invoked with incorrect arguments for function
  named: drake_add_submodule
Call Stack (most recent call first):
  CMakeLists.txt:342 (drake_add_external)


-- Configuring incomplete, errors occurred!
```

I modified it to include `hsrb_description/`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by mwoehlke-kitware** [comment]
tentative :lgtm:, but see nit and comment re: `ALWAYS` (and, as per the status label, this should probably be a single commit)

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWsFyyOk2dWk_CYCq3n:b-xbzqbk) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> I suppose I can always guard the building of all HSR examples in Drake based on `WITH_HSRB_DESCRIPTION` to prevent catastrophic failure if `hsrb_description` is not present.
</details>
This is exactly why I ask. Is this a reasonable thing to do? Maybe not... if not, if drake absolutely *must have* `hsrb_description` (and if we don't want to allow the option of a "system" version), then `ALWAYS` makes sense.

---

*[CMakeLists.txt, line 343 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs7TneiJ1dGp3HIfx2:-KWsGXd0oc_dwrygRYC-:b-f59t64) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L343)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> When I switch this to use `ros/hsrb_description`, I encounter the following error:
> 
> ```
> -- Preparing to build hsrb_description
> CMake Error at cmake/externals.cmake:441 (file):
>   file RELATIVE_PATH must be passed a full path to the file:
>   ros/hsrb_description
> Call Stack (most recent call first):
>   CMakeLists.txt:342 (drake_add_external)
> 
> 
> CMake Error at cmake/externals.cmake:445 (drake_add_submodule):
>   drake_add_submodule Function invoked with incorrect arguments for function
>   named: drake_add_submodule
> Call Stack (most recent call first):
>   CMakeLists.txt:342 (drake_add_external)
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> I modified it to include `hsrb_description/`.
</details>
Right... I wasn't clear; sorry :smile:. I meant 'as opposed to just `ros`'; the absolute path is correct.

---

*[cmake/options.cmake, line 254 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWsGNp8GwCfC7S_pmax:-KWsGNp9aKv2QJjjg4_h:b-ex2cn) ([raw file](https://github.com/robotlocomotion/drake/blob/16104b5aaa35fe973ae67f1da4830178b2ae6432/cmake/options.cmake#L254)):*
> ```CMake
>   endif()
> 
>   drake_optional_external(HSRB_DESCRIPTION ON
> ```

pedantic: I *believe* these are in lexicographical order :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-:-KWsHSNo0x8ARHBn0iGv:b-5gi85j)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWsHotUy44cIp93Se6Z:bnifycm) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> This is exactly why I ask. Is this a reasonable thing to do? Maybe not... if not, if drake absolutely *must have* `hsrb_description` (and if we don't want to allow the option of a "system" version), then `ALWAYS` makes sense.
</details>
...looked at differently, do we, as a matter of policy, want to make support for specific robots that not all users will care about non-optional (in cases where the required dependencies are not onerous), or should this sort of thing always be optional? (Note: I am not expressing an opinion either way. Both have benefits and drawbacks.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-:-KWsQWQYIjrd0upI8uuw:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWsR1JYEIpZRUkT3jNY:b-5ubqy4) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> ...looked at differently, do we, as a matter of policy, want to make support for specific robots that not all users will care about non-optional (in cases where the required dependencies are not onerous), or should this sort of thing always be optional? (Note: I am not expressing an opinion either way. Both have benefits and drawbacks.)
</details>
FWIW, I agree it makes little sense for this to be an ALWAYS, when nothing else is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 342 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWs70y3ZZuEUIf5dB82:-KWsYGAgEXWLFHFiMHEK:b-2k0npa) ([raw file](https://github.com/robotlocomotion/drake/blob/ff6d2ec38658e65d1c729a8e196d332171e3224e/CMakeLists.txt#L342)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> FWIW, I agree it makes little sense for this to be an ALWAYS, when nothing else is.
</details>
@mwoehlke-kitware: It's a good question. Based on @david-german-tri's comment, I'll keep `hsrb_description` an optional external. There is an open issue (#3772) where we can continue the discussion of which externals should be made required via the application of `ALWAYS`.

---

*[cmake/options.cmake, line 254 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWsGNp8GwCfC7S_pmax:-KWsXtTD27h-qq7O4Gvu:blig91r) ([raw file](https://github.com/robotlocomotion/drake/blob/16104b5aaa35fe973ae67f1da4830178b2ae6432/cmake/options.cmake#L254)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> pedantic: I *believe* these are in lexicographical order :smile:
</details>
Done. I ended up sorting a few other optional externals as well.

I notice there is a block of optional externals that are guarded on `if (NOT WIN32)`. Now that we're not supporting Windows, should this be guard be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by mwoehlke-kitware** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/options.cmake, line 254 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWsGNp8GwCfC7S_pmax:-KWsaM2Kn_QIGYU2i2Av:b83wbbk) ([raw file](https://github.com/robotlocomotion/drake/blob/16104b5aaa35fe973ae67f1da4830178b2ae6432/cmake/options.cmake#L254)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Done. I ended up sorting a few other optional externals as well.
> 
> I notice there is a block of optional externals that are guarded on `if (NOT WIN32)`. Now that we're not supporting Windows, should this be guard be removed?
</details>
I guess so, but maybe as a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by liangfok** [comment]
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[cmake/options.cmake, line 254 at r5](https://reviewable.io:443/reviews/robotlocomotion/drake/3986#-KWsGNp8GwCfC7S_pmax:-KWsfLO97DyS3-SYiC4d:b-2948zd) ([raw file](https://github.com/robotlocomotion/drake/blob/16104b5aaa35fe973ae67f1da4830178b2ae6432/cmake/options.cmake#L254)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> I guess so, but maybe as a separate PR.
</details>
Yes, I agree. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3986)*

**Pull request merged**
