### PR TITLE
Download and use precompiled buildifier

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7200)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri and +@soonho-tri for feature and platform reviews.

**Comment by soonho-tri** [comment]
:lgtm: Nice!

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7200#-:-Kvi7l89BiEgZm8F596r:b-8gk8uj)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

FYI Would it make sense to have the `output = repository_ctx.path("buildifier")` and then just `exports_files(["buildifier"])`, without the sh_binary wrapper?  If there is something tricky going on, maybe document that.  OK to defer / ignore.

**Comment by jamiesnape** [comment]
Done.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7200#-:-KviK1zUTLhw1ZXrEYLk:b-896fix)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7200)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7200#-:-KviZDGs5nw3zpuk69cW:bnfp4nl)*

**Pull request merged**
