### PR TITLE
[meldis] Display point contact results

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16216.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

\CC @joemasterjohn FYI re: strandbeest

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/meshcat_py.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16436#-MuRjXi15ep2aPD3cXFR:-MuRjXi15ep2aPD3cXFS:b9fscqo) ([raw file](https://github.com/robotlocomotion/drake/blob/34022f57a9763ac4f8fea8371650bc4c86cdc6b1/bindings/pydrake/multibody/meshcat_py.cc#L89)):*
> ```cpp
>                  ContactVisualizerParams>(),
>             py::arg("meshcat"), py::arg("params"), doc_internal)
>         .def("Update", &Class::Update, py::arg("items"));
> ```

btw side discussion: is it settled policy that internal-use bindings can roll without unit tests?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: side discussion

Strandbeest with point contacts worked great port-forwarded from CAM5 to my house!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436#-:-MuRjeD28IB_8e1G4RVm:brqn7c1)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436)* status: needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[bindings/pydrake/multibody/meshcat_py.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16436#-MuRjXi15ep2aPD3cXFR:-MuRpuzQ41VqOUQMbruy:b-k0yyne) ([raw file](https://github.com/robotlocomotion/drake/blob/34022f57a9763ac4f8fea8371650bc4c86cdc6b1/bindings/pydrake/multibody/meshcat_py.cc#L89)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

btw side discussion: is it settled policy that internal-use bindings can roll without unit tests?
</blockquote></details>

Done.

Note that the unit test BUILD declaration overlaps with #16450.  Whichever PR ends up second will just eat the rebase to evaporate the duplicated infrastructure.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: : platform

> Reviewed 2 of 9 files at r1, 2 of 6 files at r4, 2 of 2 files at r5, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16436#-:-MuSJ8sF8xoRFmkvfltz:b-njcd9w)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
