### PR TITLE
Remove .clang-tidy

### PR DESCRIPTION
**Pull request by sloretz**
This file appears to be unused.

I tried using it in some downstream code that is following the Drake style guide, but I soon discovered the changes required when using this config definitely aren't in Drake itself.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15654)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
It's true that the file is not used by CI.  In the past, it has been used manually by developers.  We could add a comment to that effect, if we keep it.

\CC +@soonho-tri what do you think here?

**Comment by soonho-tri** [comment]
I'm using it in my development environment. But I can live with removing this file by keeping the file in my local copies and list it in `~/.gitignore_global`.

**Comment by jwnimmer-tri** [comment]
I think that's sufficient to keep it on master (so others can reproduce your setup); we should just comment it that it's not used by CI.

**Comment by sloretz** [comment]
> I think that's sufficient to keep it on master (so others can reproduce your setup); we should just comment it that it's not used by CI.

I restored the file and added a comment saying contributors can ignore it.

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15654#-:-MhrzMMdAfy6glxLfQcg:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sloretz)

**Pull request merged**
