### PR TITLE
 pybind11: Ensure all modules are compiled with hidden symbols 

### LINKED ISSUE #8433: 'drake::pydrake::MirrorDef' declared with greater visibility than the type of its field
```
INFO: From Compiling bindings/pydrake/symbolic_py.cc:
In file included from bindings/pydrake/symbolic_py.cc:13:0:
bazel-out/k8-opt/bin/bindings/pydrake/util/_virtual_includes/wrap_pybind/drake/bindings/pydrake/util/wrap_pybind.h
:17:7: warning: 'drake::pydrake::MirrorDef' declared with greater visibility than the type of its field
'drake::pydrake::MirrorDef::m_' [-Wattributes]
 class MirrorDef {
       ^
bazel-out/k8-opt/bin/bindings/pydrake/util/_virtual_includes/wrap_pybind/drake/bindings/pydrake/util/wrap_pybind.h
:17:7: warning: 'drake::pydrake::MirrorDef' declared with greater visibility than the type of its field
'drake::pydrake::MirrorDef::mirror_' [-Wattributes]
```

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Closes #8433

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8435)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please.
+@jwnimmer-tri for platform review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8435#-:-L8DyJZIbRl9SbtpQ6rb:b-o8u9xy)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

This is great to see.

Be sure to test in CI for macOS, to cover the new Werror.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8435#-:-L8E-6rnc9gLhr5nIe1f:b-93bilq)*

**Comment by jamiesnape** [comment]
An existing defect, but I saw the following with GCC
```
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
cc1plus: warning: unrecognized command line option '-Wno-#warnings'
```

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
:lgtm: (pending Mac CI)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8435#-:-L8E8CyjkTJlxyOBm9eh:bh1fz68)*

**Comment by EricCousineau-TRI** [comment]
> An existing defect, but I saw the following with GCC

Tinkered with it, but will defer fixing that for now:
https://github.com/RobotLocomotion/drake/issues/8437

**Comment by EricCousineau-TRI** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[tools/skylark/pybind.bzl, line 44 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8435#-L8ES3G-4A8sUpxq0p0R:-L8ES3G-4A8sUpxq0p0S:b-ct2fri) ([raw file](https://github.com/robotlocomotion/drake/blob/662c046e07f4be35b3310122a44f36c591f0cb05/tools/skylark/pybind.bzl#L44)):*
> ```Python
>         copts = [
>             "-fvisibility=hidden",
>             # The following copts are per pybind11 deficiencies.
> ```

FYI I wonder if this would be slightly clearer if it returned to be above copts, but rephrased as "The warning disables below are per py..." or something.   It's not 100% obvious that it covers both groups now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8435)*

**Comment by jamiesnape** [comment]
```
AbstractValue: a request to extract a value of type 'drake::systems::BasicVector<double>' failed because the actual type was 'drake::systems::BasicVector<double>'.
```

**Comment by jwnimmer-tri** [comment]
That's consistent with having more than one `typeinfo` in play.  The `typeinfo` requirement for process-wide uniqueness vs mach linker on macOS has been challenging in the past for us.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8435#-:-L8IaJEg4RrwUURyn3G6:bbqwgxw)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/skylark/drake_cc.bzl, line 16 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8435#-L8XY4huCsjxz7raWgKk:-L8XY4huCsjxz7raWgKl:b-d0ghji) ([raw file](https://github.com/robotlocomotion/drake/blob/662c046e07f4be35b3310122a44f36c591f0cb05/tools/skylark/drake_cc.bzl#L16)):*
> ```Python
> CXX_FLAGS = [
>     "-Werror=all",
>     "-Werror=attributes",
> ```

Also add to CMake build (see the comment just above this code block)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8435)*

**Comment by EricCousineau-TRI** [comment]
Hm... From my understanding, this PR itself is a great improvement for link size, but not yet necessary at this point (since the platforms we care about use `RTLD_LAZY`).

If we are going to encounter run-time linking errors such as duplicate (and mismatched) typeids for the same types, I'd like to defer making this change until we refactor our Python modules to better handle this (i.e. better curation of cross-module dependencies for templated types). A potential solution would be to have the Python modules be linked statically, which is possible, but I'd prefer to have more time to develop something that is more cohesive to development (e.g. not waiting forever when focusing on a specific unittest, and not having to hack a manifest file everytime I wish to prune unneeded dependencies).

**Comment by jwnimmer-tri** [comment]
If this PR is stalled, maybe you could pull the last two commits into their own PR, since I think they are a strict improvement?

**Comment by EricCousineau-TRI** [comment]
> If this PR is stalled, maybe you could pull the last two commits into their own PR, since I think they are a strict improvement?

Done. Submitted #8537 (which resolves #8437 - gotta love those offsets)

**Comment by EricCousineau-TRI** [comment]
Seems that I just got bit by the above symbol visibility mismatch with Mac in the following PR:
https://github.com/robotlocomotion/drake-shambhala/pull/98
Specifically failing in this Mac build:
https://travis-ci.org/RobotLocomotion/drake-shambhala/builds/363828263#L2747-L2756

```
Traceback (most recent call last):
  File ".../example_module_test.py", line 68, in <module>
    main()
  File ".../example_module_test.py", line 60, in main
    simulator.StepTo(1)
RuntimeError: LeafOutputPort::Calc(): Expected a vector output type for output port 0 of shambhala::(anonymous)::SimpleAdder<double> System ::_::shambhala/(anonymous)/SimpleAdder@00007fc640e0bf90 but got a drake::systems::Value<drake::systems::BasicVector<double>> instead.
```

Seems that this is a problem that would not be fixed by resolve this PR, nor the above solutions (compacting `pydrake` into a single statically-linked library).

Will post a separate issue.

**Comment by EricCousineau-TRI** [comment]
Closing this for now. Can re-open later if need be.

**Pull request closed without merging**
