### PR TITLE
Disable cspace_free_polytope_test to appease CI

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18621)

### CODE REVIEW

**Comment by xuchenhan-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please.

**Review by xuchenhan-tri — COMMENTED** [review]
+@sammy-tri for platform review please.

This is to address the nightly CI failure https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-nightly-everything-valgrind-memcheck/346/

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18621#-:-NMAEgfo7d4drafKcznl:byggdq2)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: with one doc request

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18621#-:-NMBFAud6_0GRRvYb7z9:buvsqde)* status: 2 unresolved discussions (waiting on @sammy-tri and @xuchenhan-tri)

___
*[`geometry/optimization/dev/BUILD.bazel` line 80 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18621#-NMBEtr34dJ6vbKJm_h3:-NMBEtr34dJ6vbKJm_h4:b-b0la48) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe7937e983ef1ab4ba33621e0ec9fb4495567c60/geometry/optimization/dev/BUILD.bazel#L80)):*
> ```Starlark
>     name = "cspace_free_polytope_test",
>     timeout = "long",
>     tags = ["no_memcheck"],
> ```

nit: This should probably have a comment like "Takes too long to run with Valgrind" so that people know why `no_memcheck` is being added.  (I'm guessing #18583 is the reason this test got so much longer, though I'm not sure if we need to explicitly say that here)

**Comment by jwnimmer-tri** [comment]
FYI I don't think this is worth changing anything up at this point, but since this is `dev` code the nominal review process is to assign a feature reviewer (Hongkai) only, without any platform review.

**Review by xuchenhan-tri — COMMENTED** [review]
It's been a while since I worked in `dev` and I forgot about that. Sorry!
Hongkai is well aware of the test failure and is working on fixing it. I'd propose we merge as is before the nightly today.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18621#-:-NMBH-Bj548U-GrSp5np:b-epcrde)* status: 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`geometry/optimization/dev/BUILD.bazel` line 80 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/18621#-NMBEtr34dJ6vbKJm_h3:-NMBGnl6BnCipvAX3yXI:becxw4j) ([raw file](https://github.com/RobotLocomotion/drake/blob/fe7937e983ef1ab4ba33621e0ec9fb4495567c60/geometry/optimization/dev/BUILD.bazel#L80)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: This should probably have a comment like "Takes too long to run with Valgrind" so that people know why `no_memcheck` is being added.  (I'm guessing #18583 is the reason this test got so much longer, though I'm not sure if we need to explicitly say that here)
</blockquote></details>

We don't intend for this code to move out of dev like this. @hongkai-dai is actively investigating this test. 

This is just to clear CI for the moment.

**Comment by jwnimmer-tri** [comment]
> We don't intend for this code to move out of dev like this. @hongkai-dai is actively investigating this test.

Oops.  #18909 moved it out of `dev` without finishing the investigation, leaving the test still disabled.

**Pull request merged**
