### PR TITLE
[geometry] Enable valgrind on Meshcat testing

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16659.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16757)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for both reviews per schedule, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: x 2 with small nit for qualifying flag

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16757#-:-Mxp_0hq7cX4v71Cvo2J:b-8znb4l)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/dynamic_analysis/drd.sh, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16757#-MxpZrucAsrFHuxR3Brj:-MxpZrucAsrFHuxR3Brk:b-f79w3m) ([raw file](https://github.com/robotlocomotion/drake/blob/dc5940c5413a5f6d4cfc55b2c9040917c9903fef/tools/dynamic_analysis/drd.sh#L31)):*
> ```Shell
>     --trace-children=yes \
>     --trace-children-skip=/bin/cat,/bin/cp,/bin/ln,/bin/ls,/bin/mkdir,/bin/mv,/bin/sed,/lib/ld-linux.so.\*,/lib64/ld-linux-x86-64.so.\*,/usr/bin/clang,/usr/bin/clang-9,/usr/bin/clang-format-9,/usr/bin/curl,/usr/bin/diff,/usr/bin/dot,/usr/bin/fc-list,/usr/bin/file,/usr/bin/find,/usr/bin/gcc,/usr/bin/ldd,/usr/bin/patchelf,/usr/bin/strip,/usr/bin/uname,\*/external/buildifier/buildifier \
>     --trace-children-skip-by-arg=--no-valgrind \
> ```

nit May be unclear that this is a flag invented here (which I assume it is).

Consider qualifying this as a Drake-specific argument, e.g. `--no-valgrind-via-drake`?

**Comment by jwnimmer-tri** [comment]
___
*[tools/dynamic_analysis/drd.sh, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16757#-MxpZrucAsrFHuxR3Brj:-Mxp_J0-5gSlyvKIJevR:b-xpp3ht) ([raw file](https://github.com/robotlocomotion/drake/blob/dc5940c5413a5f6d4cfc55b2c9040917c9903fef/tools/dynamic_analysis/drd.sh#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit May be unclear that this is a flag invented here (which I assume it is).

Consider qualifying this as a Drake-specific argument, e.g. `--no-valgrind-via-drake`?
</blockquote></details>

Maybe `--disable-drake-valgrind-tracing`?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16757)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[tools/dynamic_analysis/drd.sh, line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16757#-MxpZrucAsrFHuxR3Brj:-MxpeVIN8Tzkz7FlEstk:b-ba7jdc) ([raw file](https://github.com/robotlocomotion/drake/blob/dc5940c5413a5f6d4cfc55b2c9040917c9903fef/tools/dynamic_analysis/drd.sh#L31)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Maybe `--disable-drake-valgrind-tracing`?
</blockquote></details>

Sounds good to me!

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16757)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
