### PR TITLE
Fix Wunused-parameter in robotInterfaces

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6032)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@siyuanfeng-tri for feature review, please.  This repairs unused parameters using the guidelines in [drake::unused's documentation](http://drake.mit.edu/doxygen_cxx/namespacedrake.html#ade20b7bf635eecb13adbaac4df980af0).

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental please

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6032#-:-KjLeW4elpj_1Aab7PcZ:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

**Comment by sherm1** [comment]
I am uncomfortable with suppressing the warnings on these suspiciously-unused arguments. If they really should have been used this removes any compiler-generated reminders that something is wrong. Can the author of this code be persuaded to add a comment and TODO as to why these parameters should be present but currently unused? Maybe there is an intention to make use of them later? Then I think it would be reasonable to suppress the warning. Better would be to get rid of them altogether until they are needed.
@siyuanfeng-tri, do you know about this code?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6032#-:-KjOHF7BpyonEzM4UdHV:b-tdc6c7)*

**Comment by jwnimmer-tri** [comment]
Per f2f with @siyuanfeng-tri, he thinks this code will be deleted soon, so we were hoping to just do simple suppressions for now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6032#-:-KjOgsM8ErpAmC52ayTH:b-r0kvum)*

**Comment by sherm1** [comment]
OK, thanks. :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6032#-:-KjOrUvSm9Q8wIWG8h7R:b-cu9kkk)*

**Pull request merged**
