### PR TITLE
IRIS-ZO

### PR DESCRIPTION
**Pull request by wernerpe**
First draft of the FastIris PR. Some of the details are still under development. I am opening this pr to give a pointer for interested people to try FastIris out.

+(status: do not review)

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21418)

### CODE REVIEW

**Review by wernerpe — COMMENTED** [review]
+@cohnt for eventual feature review. 
+@sadraddini pinging due to your expressed interest so you have a pointer to the code.

More to follow on this pr.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21418#-:-NxTzgcc8ckwsAekee5P:bgjq3a0)* status: LGTM missing from assignees cohnt,sadraddini, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @wernerpe)

**Comment by sadraddini** [comment]
Any update on this? I'm very excited to land this

**Review by wernerpe — COMMENTED** [review]
I will be back in the middle of next week and be pushing on this.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21418#-:-O4IUw308GXEaibn1ybK:b-bvmm0u)* status: LGTM missing from assignees cohnt,sadraddini, needs platform reviewer assigned, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @wernerpe)

**Comment by RussTedrake** [comment]
This PR covers what we're calling IRIS-ZO (Zero Order Optimization), correct?  (not the IRIS-NP2 improvements?).  Ok if I update the title to reflect that?

**Comment by jwnimmer-tri** [comment]
I updated the title.  Feel free to update again in case I got it wrong.

**Comment by wernerpe** [comment]
See dev branch: https://github.com/wernerpe/drake/tree/devel/cliquecovers

**Pull request closed without merging**
