### PR TITLE
Cache/CacheEntry rename.

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Enforce naming convention such that FooCacheEntry refers to a single cache entry and FooCache refers to a collection of cache entries. Specific changes include:

Rename ElementCache to ElementCacheEntry.
Rename DeformationGradientCache to DeformationGradientCacheEntry.
All derived classes of ElementCache and DeformationGradientCache have also been renamed according to the convention.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14364)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@sherm1 for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14364#-:-MMT-GRnBMzA7wlPWgkW:b-ec6d43)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Wow -- that's a lot of name changes! Thanks for fixing this -- very clear now.
Since this is just a name change: +(status: single reviewer ok) 
Feature and platform :lgtm: (with one nit to fix)

> Reviewed 20 of 22 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14364#-:-MMTAqkd2SFI9ioCo-5F:b-plm9dg)* status: 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[multibody/fem/dev/constitutive_model.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14364#-MMT90lC0dKfbdJnacWg:-MMT90lC0dKfbdJnacWh:bul26l9) ([raw file](https://github.com/robotlocomotion/drake/blob/b4f9c9e4d9c3d0c730648894ef664f5041147054/multibody/fem/dev/constitutive_model.h#L70)):*
> ```objc
>   }
> 
>   /** Calculates the First Piola stress, in unit Pa, given the model cache. */
> ```

nit: cache -> cache entry

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14364)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform), exempt from platform review (waiting on @sherm1)

___
*[multibody/fem/dev/constitutive_model.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14364#-MMT90lC0dKfbdJnacWg:-MMTCqOnAi4K9lc6Myh2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b4f9c9e4d9c3d0c730648894ef664f5041147054/multibody/fem/dev/constitutive_model.h#L70)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: cache -> cache entry
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14364)* status: :shipit: complete! all discussions resolved, LGTM from assignee sherm1(platform), exempt from platform review (waiting on @xuchenhan-tri)

**Pull request merged**
