### PR TITLE
add instruction to setup code style for clion

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3454)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@amcastro-tri for feature review, +@jwnimmer-tri for platform review

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-:-KRghMvuivhAtxmMU8xV:b-9wfsrh)*

**Comment by RussTedrake** [comment]
LGTM.  I just tested it in my CLion.  But I noticed that the Code Style menu is actually under Editor.  So I added a commit to your branch which fixed that!   (please confirm that you agree).

Github seems to have improved their interface enough that I could do that directly in the web review interface.  @liangfok , @sherm1 -- this is exactly what we've been pining for!

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-KRi0G8-ct0UKEdr0LgF:-KRi0G8-ct0UKEdr0LgG:bghth1i) ([raw file](https://github.com/robotlocomotion/drake/blob/e248c61a9edff84b32792b0c7639083673b4b3a2/drake/doc/clion.rst#L95)):*
> ```reStructuredText
> 2. On the right panel, Go to Default Options > Right margin (columns): Set it to 80
> 3. Go to File > Settings > Editor > Code Style > C/C++
> 4. On the right panel, choose Set from > Predefined Style > Google   
> ```

BTW This line has trailing whitespace (three blank spaces at the end); it shows up in reviewable as three red centerdots.  We disallow that in code, but no rule for rst files.  Fix or not as you like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-:-KRi0fM3pMUiDh1TU8eV:bnfp4nl)*

**Comment by tkoolen** [comment]
Probably for another pull request, but I also recently changed the following two things.

In preferences, under Editor > File and Code Templates, tab "Files", click "C++ Class Header". Replace the template with:

```
#parse("C File Header.h")
#pragma once

${NAMESPACES_OPEN}

#set($class_name = ${StringUtils.removeAndHump(${NAME}, "_")})

class ${class_name} {

};

${NAMESPACES_CLOSE}
```

This makes it so that if you use Right click > New > C++ Class, and you type `my_class`, then it'll create `my_class.cc` and `my_class.h`, but the class name will be `MyClass`, and the class will use `#pragma` instead of generated include guards.

**Comment by tkoolen** [comment]
Perhaps in the long term it would be better to just export a settings file (File > Export Settings...) and host it somewhere.

**Comment by hongkai-dai** [comment]
Thank @RussTedrake and @jwnimmer-tri for the review and the fix! @tkoolen, thanks a lot for making the class template better! I think a separate PR may be good. I will create that PR unless you want to do it.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 95 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-KRi0G8-ct0UKEdr0LgF:-KRiU3B6cM6zyoWlde_m:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e248c61a9edff84b32792b0c7639083673b4b3a2/drake/doc/clion.rst#L95)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW This line has trailing whitespace (three blank spaces at the end); it shows up in reviewable as three red centerdots.  We disallow that in code, but no rule for rst files.  Fix or not as you like.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-:-KRiTYbUKFTK-iBA6J1S:bfebd0r)*

**Comment by amcastro-tri** [comment]
Excellent! I actually have this setup but never documented it. Thank you @hongkai-dai! :lgtm: 
Please @hongkai-dai or @tkoolen document this class files templates please! I'd love giving that a try!
and @russtedrake, good discovery on how to directly send PR's or commits on someones branch with github! I will definitely give that a try next time I review a PR

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454#-:-KRiY1qwerE32NSa4Rc2:b-u8xxlc)*

**Comment by amcastro-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3454)*

**Pull request merged**
