### PR TITLE
add credits page to the docs

### PR DESCRIPTION
**Pull request by RussTedrake**
drake developers -- please fill in some details for yourself!

### CODE REVIEW

**Comment by RussTedrake** [comment]
@jhoare -- drake003 suddenly woke up and caught another problem with the bot_core_lcmtypes.  PTAL?

**Comment by billhoffman** [comment]
@jhoare : "drake003 suddenly woke up and caught another problem with the bot_core_lcmtypes."  Seems to be a java issue:
 C:\cygwin64\tmp\drake-1858-310\externals\bot_core_lcmtypes\java\src\bot2_spy\ImagePlugin.java:13: error: package lcm.spy does not exist
    import lcm.spy.ChannelData;
                  ^

**Comment by jhoare** [comment]
@billhoffman and I just spoke a bit about this. We think the issue is that drake003 is using cygwin to run the build, and is doing something funny with the classpath that is being passed into Java. 

If you look here:
https://github.com/openhumanoids/bot_core_lcmtypes/blob/master/java/CMakeLists.txt#L30

It sets the path differently on windows (with semicolons), but I'm guessing that when running with cygwin it actually wants a UNIX path. Is cygwin a supported system?

**Comment by RussTedrake** [comment]
I’m sure you’re right.
cygwin has been supported so far, primarily because i have been using cygwin as
a way to administer the local build servers (via common ssh scripts). i’d be ok
removing that support down the road. that would mean removing it from the drake
installation pages.
it seems likely that this is a one line fix? if yes, I’d vote for fixing it.

**Comment by jhoare** [comment]
I did a little more research, I think we could just change the ``if(WIN32)`` check to ``if(WIN32 AND NOT UNIX)`` since UNIX should be defined on cygwin and other unix-like environments on windows.

**Comment by billhoffman** [comment]
I no longer thing it is a cygwin thing.  This is a VS build error, so it should not be using cygwin paths.

Can you  send us this file: 
C:\cygwin64\tmp\drake-1858-310\externals\bot_core_lcmtypes\pod-build\java\jar.vcxproj

On my machine where it works I have:
"C:\Program Files (x86)\Java\jdk1.8.0_65\bin\javac.exe" -source 6 -target 6 -cp C:/Users/hoffman/Work/drake/draketest/externals/bot_core_lcmtypes/java/src;C:/Users/hoffman/Work/drake/draketest/build/share/java/lcm.jar;C:/Users/hoffman/Work/drake/draketest/externals/bot_core_lcmtypes/pod-build/java/../lcmtypes_bot2_core.jar -d C:/Users/hoffman/Work/drake/draketest/externals/bot_core_lcmtypes/pod-build/java/java-build C:/Users/hoffman/Work/drake/draketest/externals/bot_core_lcmtypes/java/src/bot2_spy/ImagePlugin.java C:/Users/hoffman/Work/drake/draketest/externals/bot_core_lcmtypes/java/src/bot2_spy/PlanarLidarPlugin.java

This might be a cmake version issue.

**Comment by RussTedrake** [comment]
[jar.vcxproj.zip](https://github.com/RobotLocomotion/drake/files/172971/jar.vcxproj.zip)

**Comment by billhoffman** [comment]
I see the problem...  Not sure why, but I see the issue.

Here is the call to javac:

"C:\Program Files\Java\jdk1.8.0\bin\javac.exe" -source 6 -target 6 -cp C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src;/tmp/drake-1858-310/build/share/java/lcm.jar;C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/pod-build/java/../lcmtypes_bot2_core.jar -d C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/pod-build/java/java-build C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src/bot2_spy/ImagePlugin.java C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src/bot2_spy/PlanarLidarPlugin.java


The problem is this one:
/tmp/drake-1858-310/build/share/java/lcm.jar

/tmp should be C:/cygwin64/tmp.

**Comment by RussTedrake** [comment]
That might be coming through the lcm package config?

On Mon, Mar 14, 2016 at 6:50 PM, Bill Hoffman <notifications@github.com> wrote:
I see the problem... Not sure why, but I see the issue.

Here is the call to javac:

"C:\Program Files\Java\jdk1.8.0\bin\javac.exe" -source 6 -target 6 -cp
C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src;/tmp/drake-1858-310/build/share/java/lcm.jar;C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/pod-build/java/../lcmtypes_bot2_core.jar
-d
C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/pod-build/java/java-build
C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src/bot2_spy/ImagePlugin.java
C:/cygwin64/tmp/drake-1858-310/externals/bot_core_lcmtypes/java/src/bot2_spy/PlanarLidarPlugin.java

The problem is this one:
/tmp/drake-1858-310/build/share/java/lcm.jar

/tmp should be C:/cygwin64/tmp.

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/pull/1858#issuecomment-196554299] .[https://github.com/notifications/beacon/AGJNNKe6C3WlMXzV6S1Al0hI210gEfkYks5pteZMgaJpZM4HwKBg.gif]

**Comment by billhoffman** [comment]
Might be.  It is using the cygwin pkgconfig:
Found PkgConfig: C:/cygwin64/bin/pkg-config.exe
That is going to give back cygwin paths like /tmp.

It comes from here:
# where is lcm.jar?
execute_process(COMMAND pkg-config --variable=classpath lcm-java OUTPUT_VARIABLE LCM_JAR)
if (NOT LCM_JAR)
	message(STATUS "\n\n----- ERROR: lcm-java not found. Not building bot-spy plugins")
	return()
endif()
string(STRIP ${LCM_JAR} LCM_JAR)

I guess we  could cygpath -W it if we find cygpath.   Or we could update the build server not to use a cygwin pkg-config and to use the one that we are using on other Windows builds.

**Comment by RussTedrake** [comment]
All of the other cygwin code is expecting the cygwin pkg-config.  And the install instructions for cygwin have people installing the cygwin version.

**Comment by billhoffman** [comment]
OK, will have to add cygwin-pkg config path clean up code here.  Once cygwin is remove we will want to update this build machine.

**Comment by billhoffman** [comment]
@jhoare can you try calling shell_path  on LCM_JAR, it is a function in pods.cmake.

**Comment by jhoare** [comment]
@billhoffman Pull Request #1865

**Pull request merged**
