### PR TITLE
Remove System 1.0 code for Quadrotor

### LINKED ISSUE #3975: Purge System 1.0 from Acrobot, Pendulum, Quadrotor
Subtask of #3960.  Purge System 1.0 code from examples/Acrobot, examples/Pendulum, examples/Quadrotor.

If the resolution is to port to System 2.0 instead of deleting them, note that this includes creating a System 2.0-based LQR controller.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #3975.  Decision to remove is per discussion in #3994.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4425)

### CODE REVIEW

**Comment by naveenoid** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4425#-:-KYTsy0RdPNGxpcBuuP8:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4425#-:-KYUbJC2QBpyaKn7ACfm:bcav8r0)*

**Comment by jwnimmer-tri** [comment]
More triggered-but-not-started:
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-cpplint-experimental please
@drake-jenkins-bot linux-gcc-experimental-matlab please
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by ggould-tri** [comment]
:lgtm:  If CI likes it, I like it :)

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4425#-:-KYV5tOweCSmH2YVeqlz:bj0bwf1)*

**Pull request merged**
