### PR TITLE
Lcm on windows

### LINKED ISSUE #1220: lcm-gen.exe fails on windows because it needs build/lib in the path
it's a little subtle, since that directory doesn't necessarily exist before the build, but needs to be in the path during the (later part of) the build.  i think the right thing to do is to add it, e.g. in pods.cmake, or even just for lcm-gen in lcmtypes.cmake, but my first attempts at that somehow didn't work.  

once this is resolved, we can re-enable lcm by default on windows.

### PR DESCRIPTION
**Pull request by RussTedrake**
fixed lcm so that it builds with VS 2015 ( except for the lcm-logger which crashes the linker, so is disabled on VS 2015 only: https://github.com/RobotLocomotion/lcm-pod/issues/9 )

fixed the lcmtypes.cmake build scripts to call lcm-gen with the PATH set so that it would find the lcm libraries when called.  

a few minor code mods throughout to make VC++ happy with the code that got enabled now that LCM_FOUND=TRUE.

Resolves #1220.

### CODE REVIEW

**Comment by RussTedrake** [comment]
@rdeits -- any idea why travis has gone flakey on us?  this build fine on the previous commit (and nothing changed that would impact download-all)

**Comment by RussTedrake** [comment]
i think this one is (finally) good to go.  i ended up changing a lot more than I originally intended.
- i rewrote the bullet_pod build system using cmake.  it's now a cmake pod, too.  (that allowed me to zap almost all of the GnuWin32 prereqs required for the non-cmake windows install).  
- i rewrote the eigen_pod build system... got tired of 
- i dramatically cleaned up the gnu makefiles in drake-distro, drake, gtk, eigen, bullet, snopt, and spotless.  the new rule is "no platform dependent logic in gnu make".  moved it all into cmake.  this made my life better this weekend, but it also resolves #1319 and generally give us a much more robust build.

bullet isn't quite ready to go on windows, but it's super close.

**Comment by RussTedrake** [comment]
ps - still not sure why travis g++ is dying spontaneously in compiling RBM, but that's the only failure above.

**Comment by rdeits** [comment]
@RussTedrake it looks like the download issues were probably due to some issues they were having with AWS: https://www.traviscistatus.com/

As for the consistent failures with g++, I can only speculate that it's running out of RAM while building. The Travis VM has no swap space to fall back to when it runs out of RAM. See: http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error https://github.com/travis-ci/travis-ci/issues/2407 

Other people are also having similar issues: https://github.com/travis-ci/travis-ci/issues/1972 https://github.com/kashefy/elm/issues/60

**Comment by psiorx** [comment]
> no platform dependent logic in gnu make

Good call. :+1:

**Pull request merged**
