### PR TITLE
Adds a description of car_sim_lcm.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5075)

### CODE REVIEW

**Comment by liangfok** [comment]
Documentation-only change. +@sherm1 for both levels of review please.

\CC: @seancurtis-tri 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5075#-:-KcKvP2-bc9KeXSFoOmJ:b-silcum)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5075#-:-KcL-FtSOUJllC4DeDZd:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Realizing I'm coming to this late; I would've liked a reference in the `car_sim_lcm.cc` documentation to the readme.  Given we have some info in sphinx, some in doxygen, and some in readmes, it would be nice to close the net a bit so that if the first place you go looking is the code, it can direct you in the right..er..direction.

**Comment by jwnimmer-tri** [comment]
That's a fair point, but keep in mind that `car_sim_lcm` as a separate executable will die soonish (to be folded into the overall demo).

**Comment by SeanCurtis-TRI** [comment]
I'm satisfied in this regard.  Generally, I'd advocate this kind of "cross linking".  For those of us who think, "look at the code first" as a way to answer questions, those kinds of links would serve us well.

**Pull request merged**
