### PR TITLE
Rename InputPort to InputPortValue

### PR DESCRIPTION
**Pull request by sherm1**
Follow on to #5496. I'm making sure the names clearly reflect the distinction between ports and their values. Renamed files to match, including output port-value related ones. Clarified some comments. Modified one of the FixInputPort() signatures to make sure invalidation can be propagated properly.

There are many files touched because of name changes but the only significant changes are in context.h, and input_port_value.h (née system_input.h). 

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5533)

### CODE REVIEW

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
+@david-german-tri for all review please.

---

Review status: 0 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-:-KfTqVWeQ0zrNvqI8Lhx:b-lotqf9)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 69 of 70 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/systems/framework/context.h, line 219 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-KfhR3XiR7RrWbn2UL8r:-KfhR3XiR7RrWbn2UL8s:b-7w1krn) ([raw file](https://github.com/robotlocomotion/drake/blob/6a653f9268a98f03332cee6b74b46f47e0e150e3/drake/systems/framework/context.h#L219)):*
> ```objc
>   /// through the returned pointer if there is any possibility the input port's
>   /// value has been accessed since the value was last changed.
>   // TODO(sherm1) I believe this method is too dangerous to live.
> ```

BTW, I agree with the additional warning, but I'm not convinced this method should be zapped.  It's most popular for tests, but more importantly, we originally added it because Russ wanted to do stuff like this:

https://github.com/RobotLocomotion/drake/blob/2066adeead9516388a761822e5de566585d6d29a/drake/systems/estimators/luenberger_observer.cc#L88

I wonder if there might be a way forward where this method still exists, but it returns a pointer to a wrapper object that will ensure writes trigger invalidations, instead of to a raw `BasicVector`.

---

*[drake/systems/framework/context.h, line 273 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-KfhSHP2eg_RLZGhKVVv:-KfhSHP32Ilx616pINos:b-og6elm) ([raw file](https://github.com/robotlocomotion/drake/blob/6a653f9268a98f03332cee6b74b46f47e0e150e3/drake/systems/framework/context.h#L273)):*
> ```objc
> 
>   /// Evaluates and returns the abstract value of the input port with the given
>   /// @p descriptor. This is a recursive operation that may invoke long chains
> ```

BTW good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-:-KfhTgxmmmzjmdH6Ln6J:bnfp4nl)*

**Comment by sherm1** [comment]
I made the modification you suggested David, PTAL.

---

Review status: 63 of 67 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/systems/framework/context.h, line 219 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-KfhR3XiR7RrWbn2UL8r:-Kfi8FNd8acvaPfjglHC:b-1l5ov1) ([raw file](https://github.com/robotlocomotion/drake/blob/6a653f9268a98f03332cee6b74b46f47e0e150e3/drake/systems/framework/context.h#L219)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, I agree with the additional warning, but I'm not convinced this method should be zapped.  It's most popular for tests, but more importantly, we originally added it because Russ wanted to do stuff like this:

https://github.com/RobotLocomotion/drake/blob/2066adeead9516388a761822e5de566585d6d29a/drake/systems/estimators/luenberger_observer.cc#L88

I wonder if there might be a way forward where this method still exists, but it returns a pointer to a wrapper object that will ensure writes trigger invalidations, instead of to a raw `BasicVector`.
</blockquote></details>

Done, ptal. Good idea -- fortunately you already provided such a wrapper class! I changed this method to return a reference to the FreestandingInputPortValue object, which already has (potentially) invalidating methods for changing the data. I found only two places where the dangerous signature was being used (the above link was a different sig). See `examples/{Acrobot,Pendulum}/test/{acrobot,pendulum}_urdf_dynamics_test.cc` for the usage changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-:-Kfi9t_do-H_fXMt7w9-:b-tst7j9)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5533#-:-KfkyXZ28XFiK1zfsNUp:bnfp4nl)*

**Pull request merged**
