### PR TITLE
workspace: Add ignition_utils 1.0.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This will be required by sdformat 11.0.0 (#14852).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14853)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14853)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/ignition_utils/package.BUILD.bazel, line 69 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14853#-MXD_cOU68L_ty0HozZF:-MXD_cOV9ongSprN9n8N:b-d5pf10) ([raw file](https://github.com/robotlocomotion/drake/blob/a2139f3329f800ea843594d95b723fb1206c3ade/tools/workspace/ignition_utils/package.BUILD.bazel#L69)):*
> ```
> #define IGN_DEPRECATED(version) __attribute__ ((__deprecated__))
>     """,
>     visibility = ["//visibility:private"],
> ```

nit Remove this line (private is the default).

**Comment by jwnimmer-tri** [comment]
+@jamiesnape for feature review, please.

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14853#-:-MXDdUJx94zqlMO-RPq-:bnfp4nl)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[tools/workspace/sdformat/package.BUILD.bazel, line 249 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14853#-MXDcuiI5mGsIpt8H5kr:-MXDcuiJ-7QXtikuGGU-:bsrxirh) ([raw file](https://github.com/robotlocomotion/drake/blob/a2139f3329f800ea843594d95b723fb1206c3ade/tools/workspace/sdformat/package.BUILD.bazel#L249)):*
> ```
>         "@ignition_math",
>         "@tinyxml2",
>         # N.B. The ignition_utils library is not used as of Drkae's current
> ```

BTW Drkae's -> Drake's

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review on Monday, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14853#-:-MXXoCKgA8DCVYHlYLT8:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),jamiesnape (waiting on @jwnimmer-tri)

**Pull request merged**
