### PR TITLE
Revert just the data file changes from #4516.

### PR DESCRIPTION
**Pull request by david-german-tri**
Fixes https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=267569

Supersedes #4567.

@RussTedrake @liangfok FYI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4568)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4568#-:-KZTVGVNs4JpmdwpEo3U:bnfp4nl)*

**Comment by liangfok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4568#-:-KZTWLcZQD6nLDSlwwg9:bnfp4nl)*

**Comment by david-german-tri** [comment]
Remaining builds are irrelevant, override-merging.

**Comment by RussTedrake** [comment]
thanks all.  do we understand why that test didn't fail on continuous?  i think the change is good, and should get back in.

**Comment by jwnimmer-tri** [comment]
CI was lying to us for a while; several PRs were affected.  Any resubmit that passes CI should be fine, but some test edits would need to accompany this model edits.    There was a little more discussion in #4516.

**Pull request merged**
