### PR TITLE
[planning] Add RobotDiagram and RobotDiagramBuilder

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #14431.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@calderpg-tri for feature review, please.

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594)* status: 2 unresolved discussions, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`planning/robot_diagram.h` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LwZV7-a2dKf8ob9zp:-N7LwZV7-a2dKf8ob9zq:boda71c) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/robot_diagram.h#L33)):*
> ```objc
>   explicit RobotDiagram(const RobotDiagram<U>&);
> 
>   ~RobotDiagram() final;
> ```

Question here and with `robot_diagram_builder`- is there a reason to declare default constructors for these types rather than letting the compiler generate the default constructor automatically? If there's an important reason, that seems like something important to document here.
___
*[`planning/robot_diagram_builder.cc` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LvJO84FRIe3RMGdxu:-N7LvJO84FRIe3RMGdxv:b-iiurg9) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/robot_diagram_builder.cc#L12)):*
> ```cpp
> 
> template <typename T>
> RobotDiagramBuilder<T>::RobotDiagramBuilder(double time_step)
> ```

nit `time_step` could be `const` here
___
*[`planning/test/robot_diagram_test.cc` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LxBx_8xUFS0VQRqf2:-N7LxBx_8xUFS0VQRqf3:bvr1t5b) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/test/robot_diagram_test.cc#L26)):*
> ```cpp
>   builder->mutable_parser().AddAllModelsFromFile(FindResourceOrThrow(
>       "drake/manipulation/models/iiwa_description/urdf/"
>       "iiwa14_spheres_dense_elbow_collision.urdf"));
> ```

btw Not particularly important here, but I think it would be clearer if we stuck to using the `iiwa_spheres_dense_collision.urdf` model in `planning` tests. The "dense elbow" version is something of an ugly hack.
___
*[`planning/test/robot_diagram_test.cc` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LxrFaEbcoeCnktwVG:-N7LxrFaEbcoeCnktwVH:b-pyug3f) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/test/robot_diagram_test.cc#L70)):*
> ```cpp
> 
>   auto robot_diagram = dut->BuildDiagram();
>   robot_diagram.reset();
> ```

btw I assume the `robot_diagram.reset()` calls are just to suppress warnings about `robot_diagram` being unused?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @calderpg-tri)

___
*[`planning/robot_diagram.h` line 33 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LwZV7-a2dKf8ob9zp:-N7M0ePG6ZDwSFKWemms:bfcrgpi) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/robot_diagram.h#L33)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Question here and with `robot_diagram_builder`- is there a reason to declare default constructors for these types rather than letting the compiler generate the default constructor automatically? If there's an important reason, that seems like something important to document here.
</blockquote></details>

The rule is from https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions.

Generally a destructor should only be inline when the member fields are all trivially destructible (e.g., integers and such).  Here since we have `DiagramBuilder` and `Parser` objects to delete and no runtime performance considerations are in play, inline would not be advised.

I am little hesitant to comment that (even in the cc file) because the comment would need to appear on almost every class in Drake.
___
*[`planning/robot_diagram_builder.cc` line 12 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LvJO84FRIe3RMGdxu:-N7M-y2n08PWRtstOaCY:b18k32d) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/robot_diagram_builder.cc#L12)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

nit `time_step` could be `const` here
</blockquote></details>

OK In this case, it doesn't seem like any particular help for readability.
___
*[`planning/test/robot_diagram_test.cc` line 26 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LxBx_8xUFS0VQRqf2:-N7M0BpgDcZktoEcOZE7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/test/robot_diagram_test.cc#L26)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

btw Not particularly important here, but I think it would be clearer if we stuck to using the `iiwa_spheres_dense_collision.urdf` model in `planning` tests. The "dense elbow" version is something of an ugly hack.
</blockquote></details>

Done.
___
*[`planning/test/robot_diagram_test.cc` line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7LxrFaEbcoeCnktwVG:-N7M0VvfA8JNqrjQ5HPu:bsczo3e) ([raw file](https://github.com/robotlocomotion/drake/blob/6b851faf2f3cc4fd81a2f13d2477fa80efafc5cd/planning/test/robot_diagram_test.cc#L70)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

btw I assume the `robot_diagram.reset()` calls are just to suppress warnings about `robot_diagram` being unused?
</blockquote></details>

OK clarified with a comment.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594#-:-N7N-Ghn7vBk_JHQYQbW:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review per schedule, please.

**Review by ggould-tri — COMMENTED** [review]
I will not finish this before EOB today; you can reassign it or I can pick it back up in the morning; either is fine with me.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594#-:-N7N3crp3I3bK5zcF-xu:bfgjpln)* status: LGTM missing from assignee ggould-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7NE_yiDLsu10dSI7Rg:-N7NE_yiDLsu10dSI7Rh:b3fjt2m) (no related file):*
This PR seems broadly correct for what it does, but I have a design misgiving.

In anzu downstream we seem to have three general patterns of things that help you to build your diagram:
 * (a) Things like this that want to create and own their own DiagramBuilder.
 * (b) Things that take an existing DiagramBuilder and build things of well-known names into it.
 * (c) Things that take an existing DiagramBuilder and return a struct of const pointers to ports.

My inclination is that category a is the least general and useful.  Obviously you can't ever use more than one category a helper in the same diagram -- they're not composable.  Category b helpers are easy to use, and category c helpers give nice C++ interfaces, but I don't see much to recommend the category a design.  Are a plant and sg so special that they should own your builder?

Alternatively, it might be the case that the result of this builder is always meant to be a subdiagram.  But the plant and sg are poor candidates for that, since all sorts of things constantly want to wire into this or that plant port, plus per #16908 the outputs of your plant were probably wrong and so now the outputs of your subdiagram are probably wrong.

This seems like a question for the Drake Adoption team, so I'm happy to bow out as long as this reflects some sort of design intention.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @ggould-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7NE_yiDLsu10dSI7Rg:-N7NHe4W4PT0FrPFlftw:b-b8tm7e) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This PR seems broadly correct for what it does, but I have a design misgiving.

In anzu downstream we seem to have three general patterns of things that help you to build your diagram:
 * (a) Things like this that want to create and own their own DiagramBuilder.
 * (b) Things that take an existing DiagramBuilder and build things of well-known names into it.
 * (c) Things that take an existing DiagramBuilder and return a struct of const pointers to ports.

My inclination is that category a is the least general and useful.  Obviously you can't ever use more than one category a helper in the same diagram -- they're not composable.  Category b helpers are easy to use, and category c helpers give nice C++ interfaces, but I don't see much to recommend the category a design.  Are a plant and sg so special that they should own your builder?

Alternatively, it might be the case that the result of this builder is always meant to be a subdiagram.  But the plant and sg are poor candidates for that, since all sorts of things constantly want to wire into this or that plant port, plus per #16908 the outputs of your plant were probably wrong and so now the outputs of your subdiagram are probably wrong.

This seems like a question for the Drake Adoption team, so I'm happy to bow out as long as this reflects some sort of design intention.
</blockquote></details>

The key observation is that this class a planner-specific sugar (in the planner folder, not the multibody or systems folders).  The (a)..(c) you mention are more commonly used for simulation set-up, which is not the case here. I would not advise using this class for those situations.

Perhaps its class overview should make that distinction more clear?

___

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7NE_yiDLsu10dSI7Rg:-N7Qi-0xCEWEfyI73was:b-puc31c) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The key observation is that this class a planner-specific sugar (in the planner folder, not the multibody or systems folders).  The (a)..(c) you mention are more commonly used for simulation set-up, which is not the case here. I would not advise using this class for those situations.

Perhaps its class overview should make that distinction more clear?
</blockquote></details>

Yes, the folder/namespace is probably not the only place to mention the purpose of the class; with no documentation of purpose, I assumed this was a general purpose utility that simply lacked any better place to land.

Moving this to the class comment.

**Review by ggould-tri — COMMENTED** [review]
Returning to this now.

> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594#-:-N7QhyOL0is_biyjJhnc:b-18ddrs)* status: 4 unresolved discussions, LGTM missing from assignee ggould-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`planning/robot_diagram.h` line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QiUPRBUmW9RX8fgBk:-N7QiUPRBUmW9RX8fgBl:bqir496) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram.h#L20)):*
> ```objc
> references.
> 
> @tparam_default_scalar */
> ```

Per meta discussion above, this should explain the purpose of this class (planning, not simulation), since its design looks general-purpose but isn't quite impedance-matched.
___
*[`planning/robot_diagram.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QktRn-atWLSQWnTYK:-N7QktRn-atWLSQWnTYL:b13l4oo) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram.cc#L15)):*
> ```cpp
> using systems::SystemTypeTag;
> 
> // These are a consequence of AddMultibodyPlantSceneGraph.
> ```

This is a roundabout way to do this, given that
* `AddMultibodyPlantSceneGraph` does not guarantee these indexes (nor should it), and
* instead it provides precisely the pointers you are going to complicatedly downcast to get directly in its return type, which your only allowable caller is already storing in its `pair_` member.

If you're going to depend on your caller using `AddMultibodyPlantSceneGraph`, just make them pass its return value to your ctor and store pointers or indexes from there instead of speculating.
___
*[`planning/robot_diagram_builder.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QoeWP3k5WWHByKKLE:-N7QoeWP3k5WWHByKKLF:bcdb3ce) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram_builder.h#L39)):*
> ```objc
>   @throws exception when IsDiagramBuilt() already. */
>   systems::DiagramBuilder<T>& mutable_builder() {
>     DRAKE_THROW_UNLESS(!IsDiagramBuilt());
> ```

minor, meta:  All of these throw_unless lines seem like workarounds to `DiagramBuilder::ThrowIfAlreadyBuilt` being private.  Why not just make it public and use that, thereby avoiding the problem of this class and its contained builder having separate validity tracking.  Or, better, make a public accessor for `DiagramBuilder::already_built_`, which ought to exist (insert standard Drake defect gripe about throwing on known-but-inaccessible state) and a later comment in this file will argue is required anyway.
___
*[`planning/robot_diagram_builder.h` line 111 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7Qnwrb06-e3luJYsV_:-N7Qnwrb06-e3luJYsVa:be2cw6n) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram_builder.h#L111)):*
> ```objc
> 
>   /** Checks if the diagram has already been built. */
>   bool IsDiagramBuilt() const {
> ```

Since you allow mutable access to the `DiagramBuilder`, this isn't actually the correct check:  Only the `DiagramBuilder` itself knows if it has been built.
(this is obviously the same problem as the meta minor defect above, but less minor).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform), when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @calderpg-tri and @ggould-tri)

___
*[`planning/robot_diagram.h` line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QiUPRBUmW9RX8fgBk:-N7RGWCSD4u6D2Rkmcu1:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram.h#L20)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Per meta discussion above, this should explain the purpose of this class (planning, not simulation), since its design looks general-purpose but isn't quite impedance-matched.
</blockquote></details>

Done
___
*[`planning/robot_diagram.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QktRn-atWLSQWnTYK:-N7RHxKB0XcR-BnPNtzf:bje0zm4) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram.cc#L15)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This is a roundabout way to do this, given that
* `AddMultibodyPlantSceneGraph` does not guarantee these indexes (nor should it), and
* instead it provides precisely the pointers you are going to complicatedly downcast to get directly in its return type, which your only allowable caller is already storing in its `pair_` member.

If you're going to depend on your caller using `AddMultibodyPlantSceneGraph`, just make them pass its return value to your ctor and store pointers or indexes from there instead of speculating.
</blockquote></details>

That doesn't handle what to do with the scalar-converting copy constructor.
___
*[`planning/robot_diagram_builder.h` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QoeWP3k5WWHByKKLE:-N7RFfWt-UgeWaasCgTS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram_builder.h#L39)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor, meta:  All of these throw_unless lines seem like workarounds to `DiagramBuilder::ThrowIfAlreadyBuilt` being private.  Why not just make it public and use that, thereby avoiding the problem of this class and its contained builder having separate validity tracking.  Or, better, make a public accessor for `DiagramBuilder::already_built_`, which ought to exist (insert standard Drake defect gripe about throwing on known-but-inaccessible state) and a later comment in this file will argue is required anyway.
</blockquote></details>

Done.
___
*[`planning/robot_diagram_builder.h` line 111 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7Qnwrb06-e3luJYsV_:-N7RFi805Xw_mdf4dXQY:beppjui) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram_builder.h#L111)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Since you allow mutable access to the `DiagramBuilder`, this isn't actually the correct check:  Only the `DiagramBuilder` itself knows if it has been built.
(this is obviously the same problem as the meta minor defect above, but less minor).
</blockquote></details>

Done.  Using `mutable_builder().Build()` is now specifically disallowed and enforced.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17594#-:-N7RI_HJAHkWCpB61Bpn:bnfp4nl)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @jwnimmer-tri)

___
*[`planning/robot_diagram.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17594#-N7QktRn-atWLSQWnTYK:-N7RIURJ2AExNv9W4p14:b-6zze48) ([raw file](https://github.com/robotlocomotion/drake/blob/b69f3131550013c52881bc19b4335df9092e057e/planning/robot_diagram.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That doesn't handle what to do with the scalar-converting copy constructor.
</blockquote></details>

OK *sigh*

**Pull request merged**
