### PR TITLE
Added details about locations of build and install directories. 

### LINKED ISSUE #2808: Document the Locations of the "Build" and "Install" Directories
Prior to #2706, they were `drake-distro/pod-build` and `drake-distro/build`, respectively.

Post #2706, they are `drake-distro/build` and `drake-distro/build/install`, respectively.

### PR DESCRIPTION
**Pull request by liangfok**
Closes #2808.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2824)

### CODE REVIEW

**Comment by liangfok** [comment]
+@david-german-tri for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-:-KMqjTqLDzcqhuksIe1j:-1714137908)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-:-KMy7A17c1NGIS4iKu1f:1417088721)*

**Comment by liangfok** [comment]
Thanks. Since it's Monday, +@sherm1 for platform review and merge.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-:-KMy7cmQTsVraDxFfHad:-522777393)*

**Comment by sherm1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[drake/doc/from_source.rst, line 207 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-KMyeWo-Y12SqPC2CRH2:-KMyeWo-Y12SqPC2CRH3:-1244393599) ([raw file](https://github.com/robotlocomotion/drake/blob/fbbc210d97e48928e476c31e7f81931f48736fcf/drake/doc/from_source.rst#L207)):*
> ```reStructuredText
> `Ninja <https://ninja-build.org/>`_ place build artifacts in
> ``drake-distro/build/``. Externally visible build artifacts are placed in
> ``drake-distro/build/install``.
> ```

I'm confused about the scope of these instructions. Is the somewhat-in-source-tree build a suggestion, or a restriction for people using ROS? I thought we supported completely out-of-source builds and I have been doing that on both Windows and Ubuntu (admittedly with some strange things happening in the source externals directory). 

Would you please clarify for me the scope of your instructions, and consider whether that should be part of the text?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/from_source.rst, line 207 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-KMyeWo-Y12SqPC2CRH2:-KMyyFvAKGhYIRNd0bt0:-956033145) ([raw file](https://github.com/robotlocomotion/drake/blob/fbbc210d97e48928e476c31e7f81931f48736fcf/drake/doc/from_source.rst#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> I'm confused about the scope of these instructions. Is the somewhat-in-source-tree build a suggestion, or a restriction for people using ROS? I thought we supported completely out-of-source builds and I have been doing that on both Windows and Ubuntu (admittedly with some strange things happening in the source externals directory). 
> 
> Would you please clarify for me the scope of your instructions, and consider whether that should be part of the text?
</details>
The somewhat-in-source-tree build is part of the [official installation guide](http://drake.mit.edu/from_source.html#build-with-make). It is not required. I've updated this PR to contain a statement of scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-:-KMz1LFY-h0fntWbeR5K:701515998)*

**Comment by sherm1** [comment]
Platform review: :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/doc/from_source.rst, line 207 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-KMyeWo-Y12SqPC2CRH2:-KMzYtBZmAMOrWhF_MNi:141133547) ([raw file](https://github.com/robotlocomotion/drake/blob/fbbc210d97e48928e476c31e7f81931f48736fcf/drake/doc/from_source.rst#L207)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> The somewhat-in-source-tree build is part of the [official installation guide](http://drake.mit.edu/from_source.html#build-with-make). It is not required. I've updated this PR to contain a statement of scope.
</details>
LGTM, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2824#-:-KMzYxR7oXFYHkrwqk6G:1058782226)*

**Pull request merged**
