### PR TITLE
Sphinx/doxygen documentation updates

### PR DESCRIPTION
**Pull request by RussTedrake**
A first pass at updating the sphinx documentation.
 - "Modeling dynamical systems" now points to system 2.0.  Note that new systems should just add `@ingroup systems` to add themselves to this list.  When we get more systems, we can put some hierarchy there, too. 
 - added "Formulating and Solving Optimization Problems" with an html table in doxygen showing our current problem/solver coverage. 
 - fixed a few minor documentation blips/bugs/inconsistencies that I found in the process.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3410)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm: -- some minor comments below.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/doc/doxygen.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLXdsoBNVpYvORFCeW:-KRLXdsoBNVpYvORFCeX:b-5dq5gy) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/doc/doxygen.h#L6)):*
> ```objc
> <h3>Overview</h3>
> 
> <p>Drake's C++ library is composed primarily of an interface for solving numerical optimization problems, interfaces for modeling dynamical system, and collection of state-of-the-art algorithms for optimization on dynamical systems:</p>
> ```

Lines should be <= 80 characters (here and below).

---

*[drake/doc/doxygen.h, line 56 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLXl8GtEVWGLieKgGc:-KRLXl8GtEVWGLieKgGd:bto4jxx) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/doc/doxygen.h#L56)):*
> ```objc
> <br /><br /><br /><br /><hr />
> Brought to you by the MIT Robot Locomotion Group:
> http://groups.csail.mit.edu/locomotion/
> ```

BTW, should add a plug for TRI.

---

*[drake/solvers/optimization.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLYsuaCQRYZWJEGyHk:-KRLYsubyF-IvVFvjH8R:buhy9s9) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L26)):*
> ```objc
> /** @defgroup solvers Formulating and Solving Optimization Problems
>  * @{
>  * drake wraps a number of commercial solvers (+ a few custom solvers) to provide a common
> ```

BTW, capitalize "Drake" (?)

---

*[drake/solvers/optimization.h, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZmMa9eqBxt05_iX3:-KRLZmMbU924QMsJuhgj:bz7nt3t) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L30)):*
> ```objc
>  * other non-convex mathematical programs.
>  *
>  * @nbsp
> ```

BTW, what do these `nbsp`'s add?

---

*[drake/solvers/optimization.h, line 139 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZO5iWodVXtu9vv4C:-KRLZO5iWodVXtu9vv4D:biil7qm) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L139)):*
> ```objc
>  * @nbsp
>  * &dagger; indicates that this is a commercial solvers (note that some have free licenses for academics).
>  * drake must be able to locate the solver on your system during the configuration step (when you run cmake),
> ```

BTW, we have been capitalizing "Drake" - is that wrong?

---

*[drake/systems/framework/system.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZYWMtsQeAhFyHHxN:-KRLZYWMtsQeAhFyHHxO:bdaj7kb) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/systems/framework/system.h#L21)):*
> ```objc
> /** @defgroup systems Modeling Dynamical Systems
>  * @{
>  * @brief Drake uses a Simulink-inspired description of dynamical systems
> ```

BTW needs a period.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-:-KRL_Rv4FVcTYw-7dXOa:b2u9uw3)*

**Comment by RussTedrake** [comment]
addressed them all 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/doc/doxygen.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLXdsoBNVpYvORFCeW:-KRLae40fp0R4oKZeBBQ:b-qssebl) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/doc/doxygen.h#L6)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Lines should be <= 80 characters (here and below).
</details>
fixed.

---

*[drake/doc/doxygen.h, line 56 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLXl8GtEVWGLieKgGc:-KRLag2pkRpQCb600T7x:bpxip6) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/doc/doxygen.h#L56)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, should add a plug for TRI.
</details>
removed the ref to RLG here.  it's not the right place for the credit list.

---

*[drake/solvers/optimization.h, line 26 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLYsuaCQRYZWJEGyHk:-KRLat5fxgWIUE0s2Kzg:blvaaa5) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L26)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, capitalize "Drake" (?)
</details>
capitalize is fine.  

---

*[drake/solvers/optimization.h, line 30 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZmMa9eqBxt05_iX3:-KRLawH9OQeHOT5RbjoA:bc2ebke) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, what do these `nbsp`'s add?
</details>
just forces a nicer paragraph break (I believe)

---

*[drake/solvers/optimization.h, line 139 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZO5iWodVXtu9vv4C:-KRLb-_zg-ztxV4kgSEM:b-yntd4y) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/solvers/optimization.h#L139)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW, we have been capitalizing "Drake" - is that wrong?
</details>
it's fine

---

*[drake/systems/framework/system.h, line 21 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLZYWMtsQeAhFyHHxN:-KRLbAS4kG8KRtxtT1qT:b-7ql1td) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/systems/framework/system.h#L21)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> BTW needs a period.
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-:-KRLbCQ66FzGp3tAjfU3:bhwh969)*

**Comment by sherm1** [comment]
Line length still odd?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/doxygen.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-KRLXdsoBNVpYvORFCeW:-KRLpKVwQyrxaXKriZpI:b-k9m0tw) ([raw file](https://github.com/robotlocomotion/drake/blob/8784b689102a5c01e329d210d6943d56d5afa0ed/drake/doc/doxygen.h#L6)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> fixed.
</details>
Shorter now, but I think they are at 120 rather than 80?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-:-KRLpVOMcFK1zVqqp0_X:b-h1kv6t)*

**Comment by RussTedrake** [comment]
you caught me.  editor had wrapping at 120 chars instead of 80.  fixed.

---

Review status: 11 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-:-KRNKoMSjCwJxJnlocLJ:bs3mm1e)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3410#-:-KRPZ85D4tb4zdX_OtOt:bnfp4nl)*

**Comment by sherm1** [comment]
I'm merging this now to make #3411 easier to review.

**Pull request merged**
