### PR TITLE
Add pointwise and trajectory modes to pydrake's ik module.

### PR DESCRIPTION
**Pull request by sammy-tri**
This also drops the word "Simple" from the exported functions and
renames them to use proper capitalization.

This will break any current pydrake users, but I don't think there are
any except for some tests in director which I don't think actually run
anywhere.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3468)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@hongkai-dai for feature review (since I think he's probably most familiar with the IK apis).  Feel free to remove yourself if you know of a more appropriate reviewer.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KRjaHJcSg65JdhxO8Co:b-xdi8h3)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRjiIv3dNE1baD43MP1:-KRjiIv3dNE1baD43MP2:b-gl8o37) ([raw file](https://github.com/robotlocomotion/drake/blob/1bbac17b9c63716ec7f3d96cf8ef87ad8a53cfb2/drake/bindings/python/pydrake/test/testRBTIK.py#L19)):*
> ```Python
>         # Choose a seed configuration (randomly) and a nominal configuration (at 0)
>         q_seed = np.vstack((np.zeros((6,1)),
>                             0.8147))
> ```

This is not related to this PR, but if you know where 0.8147 comes from, could you document it?

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRjihvr8Em5iumF5uE6:-KRjihvr8Em5iumF5uE7:blcis05) ([raw file](https://github.com/robotlocomotion/drake/blob/1bbac17b9c63716ec7f3d96cf8ef87ad8a53cfb2/drake/bindings/python/pydrake/test/testRBTIK.py#L28)):*
> ```Python
>         self.assertAlmostEqual(results.q_sol[0][6], q, 1e-9)
> 
>         # Test again both pointwise and as a trajectory to validate
> ```

Use `Tests` instead of `Test`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KRjjDGGi1CdUKtjjylJ:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRjiIv3dNE1baD43MP1:-KRjqZ5oNFmgfG5OUthY:bqd7hag) ([raw file](https://github.com/robotlocomotion/drake/blob/1bbac17b9c63716ec7f3d96cf8ef87ad8a53cfb2/drake/bindings/python/pydrake/test/testRBTIK.py#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> This is not related to this PR, but if you know where 0.8147 comes from, could you document it?
</details>
Sadly, I have no idea.  I'm hoping the comment above is accurate and that the value is random/arbitrary.

---

*[drake/bindings/python/pydrake/test/testRBTIK.py, line 28 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRjihvr8Em5iumF5uE6:-KRjqfxEjywckwfdRN4m:bgkg6ny) ([raw file](https://github.com/robotlocomotion/drake/blob/1bbac17b9c63716ec7f3d96cf8ef87ad8a53cfb2/drake/bindings/python/pydrake/test/testRBTIK.py#L28)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary>
> Use `Tests` instead of `Test`?
</details>
I was going for an imperative sentence here.  I guess declarative might be better?  Updated wording.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r2.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sammy-tri** [comment]
+@ggould-tri for platform review

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KRnOi2z0FFndpAruEJm:b-gbk9vg)*

**Comment by ggould-tri** [comment]
:lgtm: pending items below.

---

Reviewed 7 of 10 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 64 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo46bDn0Hs6p70q4t5:-KRo46bDn0Hs6p70q4t6:b2q3dfx) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/bindings/python/pydrake/test/testPR2IK.py#L64)):*
> ```Python
> results = ik.InverseKin(robot, q_seed, q_seed, constraints, options)
> 
> # results.info gives the output status of SNOPT. info = 1 is good, anything
> ```

Comment does not match code (rewrite `results.info` and `info` to `info[0]` or similar)

---

*[drake/systems/plants/inverseKinPointwise.cpp, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo4pQuxMyaBgWNnDhB:-KRo4pQuxMyaBgWNnDhC:b-njyuu0) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/systems/plants/inverseKinPointwise.cpp#L53)):*
> ```cpp
>       model, t.size(), t.data(), q_seed, q_nom,
>       constraint_array.size(),
>       const_cast<RigidBodyConstraint** const>(constraint_array.data()),
> ```

BTW -- for the sanity of future readers, consider documenting why this `const_cast` is necessary and appropriate.

---

*[drake/systems/plants/inverseKinTraj.cpp, line 69 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo53gSHYNf6f64CuiQ:-KRo53gSHYNf6f64CuiR:b-njyuu0) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/systems/plants/inverseKinTraj.cpp#L69)):*
> ```cpp
>       model, t.size(), t.data(), q_seed, q_nom,
>       constraint_array.size(),
>       const_cast<RigidBodyConstraint** const>(constraint_array.data()),
> ```

BTW -- for the sanity of future readers, consider documenting why this `const_cast` is necessary and appropriate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KRo5EH6v4NDv23vGKXk:b-mr5pn)*

**Comment by sammy-tri** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/bindings/python/pydrake/test/testPR2IK.py, line 64 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo46bDn0Hs6p70q4t5:-KRoS5QPnkOTmvgQzO8J:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/bindings/python/pydrake/test/testPR2IK.py#L64)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> Comment does not match code (rewrite `results.info` and `info` to `info[0]` or similar)
</details>
Done.

---

*[drake/systems/plants/inverseKinPointwise.cpp, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo4pQuxMyaBgWNnDhB:-KRomXPHVLMb3kCo45Yz:b3ezop4) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/systems/plants/inverseKinPointwise.cpp#L53)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW -- for the sanity of future readers, consider documenting why this `const_cast` is necessary and appropriate.
</details>
Oof, I'm starting to think the existing declarations are wrong, if that's actually casting to a constant pointer to mutable pointers.  Will investigate further.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by sammy-tri** [comment]
@hongkai-dai Could you take a look at the changes I added to ik_trajectory_helper.cc and inverseKinTrajBackend.cpp and see if that seems like a reasonable way to handle an IK trajectory with only two timesteps?  Or is this not something that should be handled at all, and instead we should require at least three timesteps when doing IK trajectories?

(CI failed on Debug builds with my test that only used two timesteps, which is what prompted the change).

---

Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KRon01bBsWsHhTvkZio:bh2psqc)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by sammy-tri** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/inverseKinPointwise.cpp, line 53 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo4pQuxMyaBgWNnDhB:-KS2oiJXgyvEe8xes_cW:bs3r25j) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/systems/plants/inverseKinPointwise.cpp#L53)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Oof, I'm starting to think the existing declarations are wrong, if that's actually casting to a constant pointer to mutable pointers.  Will investigate further.
</details>
Done.  (fixed function signatures to not require cast)

---

*[drake/systems/plants/inverseKinTraj.cpp, line 69 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-KRo53gSHYNf6f64CuiQ:-KS2onQWsXl4I5Pt3Ihy:bg4jvqt) ([raw file](https://github.com/robotlocomotion/drake/blob/fcbff0eadceebec77b4b41186d03ec3e78367853/drake/systems/plants/inverseKinTraj.cpp#L69)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> BTW -- for the sanity of future readers, consider documenting why this `const_cast` is necessary and appropriate.
</details>
Done. (fixed function signatures to not require cast)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468)*

**Comment by ggould-tri** [comment]
:lgtm: `const` all the things!

---

Reviewed 9 of 9 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3468#-:-KS2rICKkXjJk6-_PQO8:b-jsxbs4)*

**Pull request merged**
