### PR TITLE
templatize RandomSource.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Co-authored by jeremy.nimmer@tri.global

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@jwnimmer-tri I will work on the test next, could you check if the changes to `random_source.h` and `random_source.cc` match with your expectation? Specifically to keep the documentation like `get_fixed_seed` in the child class `RandomSourced`, I declare this function as virtual, and just call the parent `get_fixed_seed` function.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092#-:-MabEuwdD8ft4FlRJEgd:b-8oulhl)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
When I imaged this in my head, this is what I would have tried first (instead of virtuals):

```c++
class RandomSource final : public internal::RandomSourceT<double> {
 public:
  using internal::RandomSourceT<double>::get_distribution();
  // .. etc ..
};
```

Oftentimes, 'using' the method name from your base class is sufficient to bring its documentation into your class.  You can see an example in `drake/systems/framework/output_port.h`.  It is a little bit finicky though, so perhaps won't work here.

If you stick with the current approach, then move the documentation back to the public class (leaving the internal one undocumented).  There's no need to document the internal class (until we promote it out of internal).

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[systems/primitives/random_source.h, line 159 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maj90vc3QhnbIfelHuD:-Maj90vc3QhnbIfelHuE:bosconf) ([raw file](https://github.com/robotlocomotion/drake/blob/51fbf6077264ff00617c303be43ac17db28d937e/systems/primitives/random_source.h#L159)):*
> ```objc
> };
> 
> #pragma GCC diagnostic push
> ```

@jwnimmer-tri it seems to me that this macro only works for gcc, is there a counterpart for clang?

**Review by hongkai-dai — COMMENTED** [review]
I tried to use `using internal::RandomSourceT<double>::get_distribution;` but doxygen doesn't generate documentations. I thought it is because that `RandomSourceT` is in the internal namespace, so I moved it out of the internal namespace, it still doesn't generate doxygen. I suspect it is because `RandomSourceT<double>` is a specialized template, while the doxygen is for the templated version `RandomSourceT<T>`. 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092#-:-Makqm1rEdSIgWhARmsX:b-suxg2g)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092#-:-Mat27V7-wlJwzxxEmfP:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 16 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/systems/primitives_py.cc, line 404 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxyBaMD02YSw97axPb:-MaxyBaMD02YSw97axPc:b-csqpog) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/primitives_py.cc#L404)):*
> ```cpp
>           doc.BarycentricMeshSystem.get_output_values.doc);
> 
>   py::class_<RandomSourced, LeafSystem<double>>(
> ```

Changing the RTTI of this class from `RandomSource` to `internal::RandomSourceT<double>` is a breaking change.  This line should remain unchanged (and so, will need deprecation warning suppressions).
___
*[bindings/pydrake/systems/primitives_py.cc, line 405 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxxzV19TpWRP5MdK1W:-MaxxzV19TpWRP5MdK1X:bv90i2b) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/primitives_py.cc#L405)):*
> ```cpp
> 
>   py::class_<RandomSourced, LeafSystem<double>>(
>       m, "RandomSourced", doc.RandomSourced.doc)
> ```

Changing the pydrake classname is a breaking change.  The `"RandomSource"` string name here should remain untouched.

Check the generated pydrake docs as well.  I suspect the `RandomSourced.doc` also removed the class overview from pydrake docs.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 47 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxyfbD-xPp3J-RRN2m:-MaxyfbD-xPp3J-RRN2n:bfrqdi8) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/test/primitives_test.py#L47)):*
> ```Python
>     ObservabilityMatrix,
>     PassThrough, PassThrough_,
>     RandomSourced,
> ```

nit Revert this.
___
*[bindings/pydrake/systems/test/primitives_test.py, line 534 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxyhfh43VPs2ZlzDDM:-Maxyhfh43VPs2ZlzDDN:bfrqdi8) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/test/primitives_test.py#L534)):*
> ```Python
> 
>     def test_random_source(self):
>         source = RandomSourced(distribution=RandomDistribution.kUniform,
> ```

nit Revert this.
___
*[systems/primitives/random_source.h, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxpxwXAl6vecGDZMFT:-MaxpxwXAl6vecGDZMFU:b9zuqdh) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L29)):*
> ```objc
>   std::optional<Seed> get_fixed_seed() const { return fixed_seed_; }
> 
>   double sampling_interval_sec() const { return sampling_interval_sec_; }
> ```

It is somewhat dubious to add a new API intermingled in the middle of a refactoring PR, but I guess it's fine.

However, (1) the commit message must reflect the additional change, and (2) this now-public-and-unit-tested function must be added to `RandomSource` with a public Doxygen comment.

Or, if the only purpose here was in support of the scalar conversion ctor and not end-users, then just use friendship and remove the new getter:

```c++
 private:
  // Allow different specializations to access each other's private data.
  template <typename> friend class RandomSourceT;
```
___
*[systems/primitives/random_source.h, line 40 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxqAw-5Foe9VdXbAS0:-MaxqAw-5Foe9VdXbAS1:bjcwgfp) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L40)):*
> ```objc
> 
>   template <typename U>
>   explicit RandomSourceT(const RandomSourceT<U>&);
> ```

nit Per GSG, the three prior items (two ctors + one dtor) should be placed between types `using Seed` and methods `get_distribution`, and both ctors should precede the dtor.

https://drake.mit.edu/styleguide/cppguide.html#Declaration_Order
___
*[systems/primitives/random_source.h, line 52 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxqReZDWGyxYuVApDv:-MaxqReZDWGyxYuVApDw:by73kjz) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L52)):*
> ```objc
>   const Seed instance_seed_;
>   std::optional<Seed> fixed_seed_;
>   double sampling_interval_sec_;
> ```

nit Missing `const` or `{}` on mutable POD member field.

https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization

For best consistency with existing code, it should be phrased as `const sampling_interval_sec_;` and be placed immediately after `const RandomDistribution distribution_;` so that constructor arguments that we copy into member fields all appear first, as a group.
___
*[systems/primitives/random_source.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxoLWj7IQLEInWrJqm:-MaxoLWj7IQLEInWrJqn:b-74mfzd) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L118)):*
> ```objc
>     "Re-spell uses of this class as RandomSourced, not RandomSource.  In the"
>     " future, this class will gain a template argument <typename T> in order to"
>     " support multiple scalar types.") RandomSource final
> ```

nit The classname `RandomSource` should begin a new line, per the examples at https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html
___
*[systems/primitives/random_source.h, line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxoiaJBqRGuYh_I6eY:-MaxoiaJBqRGuYh_I6eZ:be8di1d) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L136)):*
> ```objc
> 
>   /// An integer type for a random seed.
>   using Seed = RandomGenerator::result_type;
> ```

nit The `using Seed` has (accidentally?) moved from the start of the class to the middle.  Per GSG, typedefs should precede the constructor.

https://drake.mit.edu/styleguide/cppguide.html#Declaration_Order
___
*[systems/primitives/random_source.h, line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxobSX8wRdgPqoTYbr:-MaxobSX8wRdgPqoTYbs:b-4jywdl) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L150)):*
> ```objc
> };
> 
> #pragma GCC diagnostic push
> ```

nit This deprecation guard doesn't seem to be required anymore -- the internal class is not marked as deprecated.
___
*[systems/primitives/random_source.h, line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxw-m24c_zTRMR0oxg:-Maxw-m24c_zTRMR0oxh:b-xsirhg) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L153)):*
> ```objc
> #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> /// A convenient alias for a RandomSource that uses the `double` scalar type.
> using RandomSourced = internal::RandomSourceT<double>;
> ```

Working I need to think through the possible hazards of aliasing the base class instead of the `RandomSource` derived class, in case it could bite users.

(I've confirmed that my original proposal of `using RandomSourced = RandomSource;` is incompatible with Clang's interpretation of deprecation annotations.)
___
*[systems/primitives/random_source.cc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxsBqM46cd54MyhBc9:-MaxsBqM46cd54MyhBcA:b-t78ymg) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L79)):*
> ```cpp
> RandomSourceT<T>::RandomSourceT(RandomDistribution distribution,
>                                 int num_outputs, double sampling_interval_sec)
>     : LeafSystem<T>(SystemTypeTag<RandomSourceT>{}),
> ```

Working The guaranteed subtype preservation flag here seems wrong.  Will have to check myself locally, later.
___
*[systems/primitives/random_source.cc, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxsGKlEhCG07ab_waZ:-MaxsGKlEhCG07ab_wa_:b58p7qm) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L82)):*
> ```cpp
>       distribution_(distribution),
>       instance_seed_(get_next_seed()),
>       sampling_interval_sec_{sampling_interval_sec} {
> ```

nit Use `()` not `{}` for consistency with existing code.
___
*[systems/primitives/random_source.cc, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxt1ZC11c0a7qQOD9l:-Maxt1ZC11c0a7qQOD9m:bz79wx1) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L192)):*
> ```cpp
> 
>       const auto* const source =
>           builder->template AddSystem<internal::RandomSourceT<T>>(
> ```

For compatibility with existing code, when `T == double` we need to install a `RandomSource` not `internal::RandomSourceT<double>`.  Users might currently be downcasting the added system to `RandomSource` (e.g., to adjust its seed, etc), and we need to keep that working in the meantime.

My guess at a solution:

```c++
using Source = std::conditional<std::is_same_v<T, double>, RandomSource, internal::RandomSourceT<T>>;
const auto* const source = builder->AddSystem<Source>(
    port.get_random_type().value(), port.size(), sampling_interval_sec);
```
___
*[systems/primitives/random_source.cc, line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxrt9R6FOZ8XYnwwUv:-Maxrt9S7MTSDj0ycky-:bclr0uu) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L208)):*
> ```cpp
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS(
> ```

This seems like a typo -- we want NONSYMBOLIC here, not DEFAULT?
___
*[systems/sensors/test/beam_model_test.cc, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxnakV9gpkqD5LCEyG:-MaxnakW88AOvvJnmGdT:b-wh3ovl) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/sensors/test/beam_model_test.cc#L60)):*
> ```cpp
> 
>   auto w_event =
>       builder.AddSystem<RandomSourced>(RandomDistribution::kUniform, 1, 0.0025);
> ```

nit The slight variation in the lengths of the variable names here is causing clang-format to wrap each of these changed lines differently, and so has destroyed the visual alignment that previously guided the reader to see that the sources were identical except for the distribution shape.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 7 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/systems/primitives_py.cc, line 404 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxyBaMD02YSw97axPb:-Mayi0Pj0VgK1fC1RJzt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/primitives_py.cc#L404)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Changing the RTTI of this class from `RandomSource` to `internal::RandomSourceT<double>` is a breaking change.  This line should remain unchanged (and so, will need deprecation warning suppressions).
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/primitives_py.cc, line 405 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxxzV19TpWRP5MdK1W:-MayjPXU9F8iehK6ePgB:b-f4g545) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/bindings/pydrake/systems/primitives_py.cc#L405)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Changing the pydrake classname is a breaking change.  The `"RandomSource"` string name here should remain untouched.

Check the generated pydrake docs as well.  I suspect the `RandomSourced.doc` also removed the class overview from pydrake docs.
</blockquote></details>

Done. I reverted the first one, but keeps `doc.RandomSourced.doc`. If I change to `doc.RandomSource.doc`, then the code doesn't compile.

Here is the doxygen for RandomSource class with `doc.RandomSourced.doc`.

___
*[systems/primitives/random_source.h, line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxpxwXAl6vecGDZMFT:-Maylm1f8YVSMpSLvuB4:b5afjxy) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L29)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is somewhat dubious to add a new API intermingled in the middle of a refactoring PR, but I guess it's fine.

However, (1) the commit message must reflect the additional change, and (2) this now-public-and-unit-tested function must be added to `RandomSource` with a public Doxygen comment.

Or, if the only purpose here was in support of the scalar conversion ctor and not end-users, then just use friendship and remove the new getter:

```c++
 private:
  // Allow different specializations to access each other's private data.
  template <typename> friend class RandomSourceT;
```
</blockquote></details>

Done. I did the friendship approach, thanks!
___
*[systems/primitives/random_source.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxoLWj7IQLEInWrJqm:-MaynMq4AHfaNebRZ1d_:bl1eiam) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L118)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The classname `RandomSource` should begin a new line, per the examples at https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html
</blockquote></details>

Done. But clang-format insists to put them in the same line.
___
*[systems/primitives/random_source.cc, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxt1ZC11c0a7qQOD9l:-MayoAC34uCxCS3o5x_R:bs3e0d4) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For compatibility with existing code, when `T == double` we need to install a `RandomSource` not `internal::RandomSourceT<double>`.  Users might currently be downcasting the added system to `RandomSource` (e.g., to adjust its seed, etc), and we need to keep that working in the meantime.

My guess at a solution:

```c++
using Source = std::conditional<std::is_same_v<T, double>, RandomSource, internal::RandomSourceT<T>>;
const auto* const source = builder->AddSystem<Source>(
    port.get_random_type().value(), port.size(), sampling_interval_sec);
```
</blockquote></details>

It would raise a deprecation error when I have `RandomSource` in the `std::conditional`.
___
*[systems/primitives/random_source.cc, line 208 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxrt9R6FOZ8XYnwwUv:-MayoM6U0EhWpWMuqt9I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L208)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems like a typo -- we want NONSYMBOLIC here, not DEFAULT?
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[bindings/pydrake/systems/primitives_py.cc, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maz3HQ-8b7JXB8-qbaH:-Maz3HQ07vuWehY-A8QQ:b-8knh59) ([raw file](https://github.com/robotlocomotion/drake/blob/e1a97ceb13cc3eb9296d562020533b4e039f5d85/bindings/pydrake/systems/primitives_py.cc#L7)):*
> ```cpp
> #include "drake/bindings/pydrake/common/cpp_template_pybind.h"
> #include "drake/bindings/pydrake/common/default_scalars_pybind.h"
> #include "drake/bindings/pydrake/common/deprecation_pybind.h"
> ```

nit It seems like this new include is unused (ditto for BUILD).
___
*[systems/primitives/random_source.h, line 118 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxoLWj7IQLEInWrJqm:-Maz3lS98kedgB0GKomg:buc11d0) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L118)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. But clang-format insists to put them in the same line.
</blockquote></details>

clang-format is not the ultimate arbiter of anything.  When it's wrong, you need to work around it.
___
*[systems/primitives/random_source.cc, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxt1ZC11c0a7qQOD9l:-Maz3QGz4ly2AlUJkmrz:bpyx3vy) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L192)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It would raise a deprecation error when I have `RandomSource` in the `std::conditional`.
</blockquote></details>

Sure; in that case, you need `#pragma GCC diagnostic ignored "-Wdeprecated-declarations"` around that line.
___
*[systems/sensors/test/beam_model_test.cc, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxnakV9gpkqD5LCEyG:-Maz40j577egmIWcZ8-T:b-sge4oy) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/sensors/test/beam_model_test.cc#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The slight variation in the lengths of the variable names here is causing clang-format to wrap each of these changed lines differently, and so has destroyed the visual alignment that previously guided the reader to see that the sources were identical except for the distribution shape.
</blockquote></details>

The layout for all of these clauses is still both mis-indented an inconsistent across them.

The easiest way to resolve this is to go back to the original file, add the "d" suffix to RandomSourced, and don't clang-format it at all.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[systems/primitives/random_source.cc, line 192 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxt1ZC11c0a7qQOD9l:-MazLyW-5wNAKJ1Y3oN5:b-y4wjch) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L192)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sure; in that case, you need `#pragma GCC diagnostic ignored "-Wdeprecated-declarations"` around that line.
</blockquote></details>

Done. TIL `std::conditional`.
___
*[systems/sensors/test/beam_model_test.cc, line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxnakV9gpkqD5LCEyG:-MazMkBb8959y7cqXzGQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/sensors/test/beam_model_test.cc#L60)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The layout for all of these clauses is still both mis-indented an inconsistent across them.

The easiest way to resolve this is to go back to the original file, add the "d" suffix to RandomSourced, and don't clang-format it at all.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai)

___
*[systems/primitives/random_source.h, line 153 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Maxw-m24c_zTRMR0oxg:-Mb24Hzp72CZtUp3twwR:b-7iv9bv) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.h#L153)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working I need to think through the possible hazards of aliasing the base class instead of the `RandomSource` derived class, in case it could bite users.

(I've confirmed that my original proposal of `using RandomSourced = RandomSource;` is incompatible with Clang's interpretation of deprecation annotations.)
</blockquote></details>

OK This is not ideal, but I think it's the best we can do.  As long as the user sticks with the old spelling 100% of the time, or the new spelling 100% of the time, they will be fine.  (Mixing them might create dynamic_cast problems.)
___
*[systems/primitives/random_source.cc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxsBqM46cd54MyhBc9:-Mb24G1h2kceSTd7wg8G:buhu6jr) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working The guaranteed subtype preservation flag here seems wrong.  Will have to check myself locally, later.
</blockquote></details>

https://github.com/hongkai-dai/drake/pull/23

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[systems/primitives/random_source.cc, line 79 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15092#-MaxsBqM46cd54MyhBc9:-Mb3XBOj58DjQhhn1c6L:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/09f011884dea04519d1f9b68f72bce1b6bc9e09c/systems/primitives/random_source.cc#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

https://github.com/hongkai-dai/drake/pull/23
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

**Comment by jwnimmer-tri** [comment]
:lgtm: feature.

+@rpoyner-tri for platform review per schedule (tomorrow), please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: strategy question below.

> Reviewed 1 of 7 files at r1, 1 of 6 files at r2, 1 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092#-:-Mb7HIgkBrJczVt6mgff:b4l3nmh)* status: 1 unresolved discussion, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Mb7Gr1Z78Y9aXHDF2D0:-Mb7Gr1Z78Y9aXHDF2D1:bh2b8vj) (no related file):*
Just for my edification: it looks like we are handling the deprecation and replacement of RandomSource at a different pace in python bindings than in C++. I can see why this might be so, but what is the plan?

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15092)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15092#-Mb7Gr1Z78Y9aXHDF2D0:-Mb7Hl143c40A48o-znn:b-ezy7ck) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Just for my edification: it looks like we are handling the deprecation and replacement of RandomSource at a different pace in python bindings than in C++. I can see why this might be so, but what is the plan?
</blockquote></details>

Drake's class-template machinery for Python has the advantage that `RandomSource` will continue to refer to the T=double concrete class.  The templated class will be named `RandomSource_[T]` (once it appears as non-internal in C++).

---

**Pull request merged**
