### PR TITLE
Prepare lcm_vector_gen for translators

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This should be only non-functional changes, including:
- using an explicit context dict, instead of `locals()`;
- tidying up some variable names.

This extracts some of the clean-ups from #3268 into this PR, and adds to them the explicit context dict refactoring.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3359)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.

**Comment by rpoyner-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/CMakeLists.txt, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-KR-X4aYxyNX8zZ4uPnc:-KR-X4aZkCZ6c5-z6eNV:b-ne86f0) ([raw file](https://github.com/robotlocomotion/drake/blob/18a402d4f07aadf1637a79c229d3ff52e785b966/drake/examples/Cars/CMakeLists.txt#L23)):*
> ```CMake
>     drakeShapes
>     drakeSystemFramework
>     )
> ```

does list need to be topo-sorted by dependency? I can't say if it there is a problem, just by looking, but it looks a little suspicious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/CMakeLists.txt, line 23 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-KR-X4aYxyNX8zZ4uPnc:-KR-_7f5gExIop_O_U3s:b-r4lts5) ([raw file](https://github.com/robotlocomotion/drake/blob/18a402d4f07aadf1637a79c229d3ff52e785b966/drake/examples/Cars/CMakeLists.txt#L23)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary>
> does list need to be topo-sorted by dependency? I can't say if it there is a problem, just by looking, but it looks a little suspicious.
</details>
I believe the correct ordering is alpha (for maintainability).  Each of the individual libraries tells CMake their own dependencies, which it then sorts.

This is the link line from the build output.  You can see (if you stare enough) that the order is correct.
```
/usr/bin/g++-4.9
-fPIC
-Werror=all
-Werror=ignored-qualifiers
-DGTEST_DONT_DEFINE_FAIL=1
-DGTEST_DONT_DEFINE_SUCCEED=1
-DGTEST_DONT_DEFINE_TEST=1
-O3
-DNDEBUG
-Wl,--no-undefined
-shared
-Wl,-soname,libdrakeCars.so
-o ../../lib/libdrakeCars.so
CMakeFiles/drakeCars.dir/car_simulation.cc.o
CMakeFiles/drakeCars.dir/curve2.cc.o
CMakeFiles/drakeCars.dir/gen/driving_command.cc.o
CMakeFiles/drakeCars.dir/gen/driving_command_translator.cc.o
CMakeFiles/drakeCars.dir/gen/euler_floating_joint_state.cc.o
CMakeFiles/drakeCars.dir/gen/euler_floating_joint_state_translator.cc.o
CMakeFiles/drakeCars.dir/gen/idm_with_trajectory_agent_state.cc.o
CMakeFiles/drakeCars.dir/gen/idm_with_trajectory_agent_state_translator.cc.o
CMakeFiles/drakeCars.dir/gen/simple_car_state.cc.o
CMakeFiles/drakeCars.dir/gen/simple_car_state_translator.cc.o
CMakeFiles/drakeCars.dir/idm_with_trajectory_agent.cc.o
CMakeFiles/drakeCars.dir/simple_car.cc.o
CMakeFiles/drakeCars.dir/trajectory_car.cc.o
-L/home/ubuntu/workspace/experimental/d415b2e5/drake/build/lib
-L/home/ubuntu/workspace/experimental/d415b2e5/build/install/lib
../../lib/libdrakeLCMSystem.so
../../lib/libdrakeLCMSystem2.so
../../lib/libdrakeRBSystem.so
../../lib/libdrakeSystemFramework.so
/home/ubuntu/workspace/experimental/d415b2e5/build/install/lib/liblcm.so.1.3.1
../../lib/libdrakeOptimization.so
-L/usr/lib/gcc/x86_64-linux-gnu/4.9
-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu
-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib
-L/lib/../lib
-L/usr/lib/../lib
-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..
-lipopt
-ldl
-lcoinmumps
-lcoinlapack
-lcoinmetis
-lcoinblas
-lgfortran
-L/home/ubuntu/workspace/experimental/d415b2e5/build/install/lib/dreal
-lm
-lquadmath
-lnlopt
-ldreal
-libex
-lClpSolver
-lClp
-lCoinUtils
-lcapd
-ladept
-lglpk
-lprim
-lpicosat
-lpthread
-lm
-lquadmath
-lnlopt
-ldreal
-libex
-lClpSolver
-lClp
-lCoinUtils
-lcapd
-ladept
-lglpk
-lprim
-lpicosat
-lpthread
-lsnopt_c
-lf2c
-lgurobi60
-lmosek64
-liomp5
../../lib/libdrakeRigidBodyConstraint.so
../../lib/libdrakeRBM.so
../../lib/libdrakeCollision.so
../../lib/libdrakeShapes.so
-L/home/ubuntu/workspace/experimental/d415b2e5/build/install/lib
-lBulletSoftBody
-lBulletDynamics
-lBulletCollision
-lLinearMath
../../lib/libdrakeJoints.so
../../lib/libdrakeUtil.so
../../lib/libdrakeXMLUtil.so
../../lib/libspruce.so
../../lib/libtinyxml2.so
../../lib/libdrakeGeometryUtil.so
../../lib/libdrakeCommon.so
-lpthread
-Wl,-rpath,/home/ubuntu/workspace/experimental/d415b2e5/drake/build/lib:/home/ubuntu/workspace/experimental/d415b2e5/build/install/lib:
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359)*

**Comment by rpoyner-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-:-KR-cQkgFjoAUpd0qApO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-KR-dsVB_Pby_qChLY21:-KR-dsVB_Pby_qChLY22:bx4e5lt) ([raw file](https://github.com/robotlocomotion/drake/blob/18a402d4f07aadf1637a79c229d3ff52e785b966/drake/examples/Cars/lcm_vector_gen.py#L50)):*
> ```Python
>     context.update(kname = "kNumCoordinates")
>     put(cc, INDICES_FIELD_STORAGE % context, 1)
>     for kvalue, field in enumerate(fields):
> ```

This could use some kind of comment explaining what the elements of `fields` are, and as a result what `kvalue` is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-:-KR-eY1vBuslKPhFlLrF:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 50 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-KR-dsVB_Pby_qChLY21:-KR-gVIdkvY9pzGF35EY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/18a402d4f07aadf1637a79c229d3ff52e785b966/drake/examples/Cars/lcm_vector_gen.py#L50)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> This could use some kind of comment explaining what the elements of `fields` are, and as a result what `kvalue` is.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359)*

**Comment by jwnimmer-tri** [comment]
FYI the [prior ROS build](https://drake-jenkins.csail.mit.edu/view/ROS/job/linux-gcc-experimental-ros/95/) passed, and I'm not planning to re-running it, given the subsequent comments-only edit

**Comment by rpoyner-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3359#-:-KR02sDoSQjE0qLyTS7u:bnfp4nl)*

**Pull request merged**
