### PR TITLE
Do override compiler flags in ignition_* externals

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=562588.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5967)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-clang-experimental please

**Comment by BetsyMcPhail** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5967#-:-KiplSp7mDCG2EkQ_9Vp:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@sherm1 pour l'examen de la plate-forme.

**Comment by sherm1** [comment]
Looks bon to moi! :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5967#-:-KiqB6Z5Q-0pBLyRWW3w:b-x616xv)*

**Pull request merged**
