### PR TITLE
Move code from symbolic_extraction to symbolic_decompose.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also add the python bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for feature review please, thanks
+@soonho-tri for platform review please, thanks

The new code in `symbolic_decompose.h/cc` are copied from `symbolic_extration.h/cc`, I didn't write any new code in this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMNTfMa8CIEnRI_1pV0:b-q3tr4d)* status: LGTM missing from assignees RussTedrake(platform),soonho-tri(platform) (waiting on @RussTedrake and @soonho-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: 1 unresolved discussion, LGTM missing from assignees soonho-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai, @RussTedrake, and @soonho-tri)

___
*[common/symbolic_decompose.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNVDnZ8NFZ1eQzA7Vn:-MMNVDn_-7ACq7aAeZK5:b72qqv1) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/common/symbolic_decompose.h#L19)):*
> ```objc
>  * Adds context to symbolic expression-related errors.
>  */
> class SymbolicError : public std::runtime_error {
> ```

nit From a platform review perspective, I don't know that we have a GSG write-up forbidding this, but we really shouldn't be subclassing exceptions.

From a platform review perspective, instead, it would be fine to offer a utility function that formats text that the user can then pass into the `std::runtime_error` constructor themselves.

Given that none of the relocated code actually _uses_ this formatting anyway (from what I can tell), I don't see why we need to hoist message-formatting code to common?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: 2 unresolved discussions, LGTM missing from assignees soonho-tri(platform),RussTedrake(platform) (waiting on @hongkai-dai, @RussTedrake, and @soonho-tri)

___
*[solvers/symbolic_extraction.h, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNXcqt6P8O4fEk6UCK:-MMNXcqt6P8O4fEk6UCL:bi7f05k) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/solvers/symbolic_extraction.h#L73)):*
> ```objc
> void ExtractAndAppendVariablesFromExpression(
>     const symbolic::Expression& e, VectorXDecisionVariable* vars,
>     std::unordered_map<symbolic::Variable::Id, int>* map_var_to_index);
> ```

nit If this function body has been coped to `common/...`, why does this cc file still have a copy of it?  Shouldn't this function simply call the function from common now?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: LGTM missing from assignees soonho-tri(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[common/symbolic_decompose.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNVDnZ8NFZ1eQzA7Vn:-MMOcJ8N7AFHlBXoy7RW:b-fd4n4k) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/common/symbolic_decompose.h#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit From a platform review perspective, I don't know that we have a GSG write-up forbidding this, but we really shouldn't be subclassing exceptions.

From a platform review perspective, instead, it would be fine to offer a utility function that formats text that the user can then pass into the `std::runtime_error` constructor themselves.

Given that none of the relocated code actually _uses_ this formatting anyway (from what I can tell), I don't see why we need to hoist message-formatting code to common?
</blockquote></details>

Done. I changed it to utility function that formats text.
___
*[solvers/symbolic_extraction.h, line 73 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNXcqt6P8O4fEk6UCK:-MMOf1et5j9_wzK9F98l:b3rcp3p) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/solvers/symbolic_extraction.h#L73)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If this function body has been coped to `common/...`, why does this cc file still have a copy of it?  Shouldn't this function simply call the function from common now?
</blockquote></details>

Done. I replaced the function bodies.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: LGTM missing from assignees soonho-tri(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[common/symbolic_decompose.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNVDnZ8NFZ1eQzA7Vn:-MMPC5gm66w2MbajESeD:b-j1hmb6) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/common/symbolic_decompose.h#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I changed it to utility function that formats text.
</blockquote></details>

I don't yet see why we need to hoist message-formatting code to common in the first place?  Nothing in common calls it.

Furthermore, the exception text says "constraint" even though nothing in the function name or comment suggests that semantics, and common doesn't (not shouldn't) know about "constraints" in the first place.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: LGTM missing from assignees soonho-tri(platform),RussTedrake(platform) (waiting on @RussTedrake and @soonho-tri)

___
*[common/symbolic_decompose.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNVDnZ8NFZ1eQzA7Vn:-MMPI2DSDtdq_8MHpGzf:btxj92e) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/common/symbolic_decompose.h#L19)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't yet see why we need to hoist message-formatting code to common in the first place?  Nothing in common calls it.

Furthermore, the exception text says "constraint" even though nothing in the function name or comment suggests that semantics, and common doesn't (not shouldn't) know about "constraints" in the first place.
</blockquote></details>

The only place that calls this function is in `create_constraint.cc`. I am OK to remove this function from public API. @soonho-tri is that OK with you?

**Review by hongkai-dai — COMMENTED** [review]
-@soonho-tri for platform review since he is on PTO

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMQz60N4cSq5mtM1IKN:bmsuez1)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[common/symbolic_decompose.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMNVDnZ8NFZ1eQzA7Vn:-MMRJ41_D915hRhtViM4:b-68vbbw) ([raw file](https://github.com/robotlocomotion/drake/blob/8744bfe49414594f6d5a5756ced971e284b60448/common/symbolic_decompose.h#L19)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The only place that calls this function is in `create_constraint.cc`. I am OK to remove this function from public API. @soonho-tri is that OK with you?
</blockquote></details>

Done. I removed this function.

**Review by hongkai-dai — COMMENTED** [review]
-@russtedrake for feature review. +@ericcousineau-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMYpn44--nLlyuWDjaL:b-36gh8v)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgVqXHCjwCkpQxO0YJ:-MMgVqXI9to-Go1aL-07:b2l7vx8) (no related file):*
nit As it stands, I can't judge the merit / benefit of the C++ code movement at a high-level.

Is there a tracking issue, or can you give me a 1-or-2-liner as to why you're doing this?
FTR If I'm in a rush, I usually just say "For my workflow in Anzu", or whatevs. I just want to know where this is going.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgVqXHCjwCkpQxO0YJ:-MMgWjFp6BrM-GICVDNp:b7swqyy) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit As it stands, I can't judge the merit / benefit of the C++ code movement at a high-level.

Is there a tracking issue, or can you give me a 1-or-2-liner as to why you're doing this?
FTR If I'm in a rush, I usually just say "For my workflow in Anzu", or whatevs. I just want to know where this is going.
</blockquote></details>

(Or if you wanna be more concrete in scope, you can also just say "Trust me, and please keep your review local". I just need a bit more guidance / hand-holding at a high level ;)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: locally!

> Reviewed 6 of 12 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMg_62g879O4fsRFr6k:bd5ixy0)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgVqXHCjwCkpQxO0YJ:-MMg_7lHANn-pojZD3dy:bl0ntl1) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Or if you wanna be more concrete in scope, you can also just say "Trust me, and please keep your review local". I just need a bit more guidance / hand-holding at a high level ;)
</blockquote></details>

OK After reviewing, goal is sufficiently clear!

---
___
*[bindings/pydrake/test/symbolic_test.py, line 524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgZOap6ygtipPWEX6V:-MMgZOap6ygtipPWEX6W:b-c6cguh) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/bindings/pydrake/test/symbolic_test.py#L524)):*
> ```Python
> 
>     def test_get_variable_vector(self):
>         vars = sym.GetVariableVector([e_x, e_y])
> ```

nit `vars` is a builtin keyword.

Consider using `vars_` instead.
(There are other examples of this kind of defect in `pydrake`, though, so feel free to dismiss.)
___
*[bindings/pydrake/test/symbolic_test.py, line 1280 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgZeeq4YrJFIb7PYSZ:-MMgZeeq4YrJFIb7PYS_:b-asqsyh) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/bindings/pydrake/test/symbolic_test.py#L1280)):*
> ```Python
>         e = [2 * x + 3 * y, 4 * x + 2 * y, 3 * x]
>         M = sym.DecomposeLinearExpressions(e, [x, y])
>         np.testing.assert_allclose(M, np.array([[2, 3], [4., 2.], [3., 0.]]))
> ```

nit This should use `assert_arrays_equal`, since tolerance shouldn't be an issue?

If it is, please explicitly specify `rtol` and `atol` (and only use one?).
https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html
___
*[common/symbolic_decompose.h, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgXhknCzmAFBHCCseo:-MMgXhknCzmAFBHCCsep:b3qm7je) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.h#L68)):*
> ```objc
>  * index in the vector `x`.
>  * @param Q[out] The Hessian of the quadratic expression. @pre The size of Q
>  * should be `num_variables * num_variables`.
> ```

BTW Should this mention that it handles asymmetric matrices, given that you explicitly test it?
___
*[common/symbolic_decompose.h, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgY9BVE58weGD7Daki:-MMgY9BVE58weGD7Dakj:b-lt0cqv) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.h#L68)):*
> ```objc
>  * index in the vector `x`.
>  * @param Q[out] The Hessian of the quadratic expression. @pre The size of Q
>  * should be `num_variables * num_variables`.
> ```

nit `*` in this context (and below) feels ambiguous / distracting.

Do you mean the shape? Consider using a cross `×` or `x` instead of `*`, to delimiter separate dimensions?
___
*[common/symbolic_decompose.h, line 70 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgYB3s-wvvjPh15EFw:-MMgYB3s-wvvjPh15EFx:bn070zh) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.h#L70)):*
> ```objc
>  * should be `num_variables * num_variables`.
>  * @param b[out] The linear term of the quadratic expression. @pre The size of
>  * `b` should be `num_variables * 1`.
> ```

nit The type of `b` is a vector.

Consider removing the trailing (redundant) `* 1`?
___
*[common/symbolic_decompose.cc, line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgYlYg8tdX6y4jfQPl:-MMgYlYg8tdX6y4jfQPm:b-8ydnqs) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.cc#L144)):*
> ```cpp
>     const double coefficient = get_constant_value(p.second);
>     const symbolic::Monomial& p_monomial = p.first;
>     if (p_monomial.total_degree() > 2) {
> ```

nit Why check this in the inner monomials, when you can fail using a higher-level `poly.TotalDegree()`, like what is done for the affine experssion?
https://drake.mit.edu/doxygen_cxx/classdrake_1_1symbolic_1_1_polynomial.html#aaf2a77325f716479b2f8c5b17729a5c6

(If it's for performance, then I'm OK with that, though now this and the affine case diverge a bit.)
___
*[solvers/symbolic_extraction.h, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMg_E1o608L_1btVJxe:-MMg_E1p1jdlGeikK_wf:b-nuuuzh) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/solvers/symbolic_extraction.h#L82)):*
> ```objc
>  * pair.second[pair.first(i).get_id()] = i
>  */
> DRAKE_DEPRECATED("2021-01-01",
> ```

These dates should be `2021-03-01` (3 months, rounding up), unless you think there's something exceptional about this deprecation:
https://drake.mit.edu/code_review_checklist.html
https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html#a847d827d084f28e4ae1788a0ae75be96

**Review by EricCousineau-TRI — COMMENTED** [review]
I am also fine as serving as platform review too (single review). Let me know what you'd like.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMg_XBr-NuENCUmndro:b-lx1spo)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @hongkai-dai)

**Comment by RussTedrake** [comment]
> Is there a tracking issue, or can you give me a 1-or-2-liner as to why you're doing this?
> FTR If I'm in a rush, I usually just say "For my workflow in Anzu", or whatevs. I just want to know where this is going.
> 
This originated in a discussion with me (and soonho).  I was writing MBP symbolic code, but without mathematical program, and we realized that the ability to extract these things should not be hidden away inside MathematicalProgram.  Specifically, I’ll use it in my parameter estimation code.

**Comment by EricCousineau-TRI** [comment]
Awesome - thank you for the explanation!

**Review by hongkai-dai — COMMENTED** [review]
@ericcousineau-tri , I do have a question about the doc. We have two `DecomposeAffineExpressions` defined in `symbolic_decompose.h`, but when I build `documentation_pybind.h`, I only see one entry as `doc.DecomposeAffineExpressions.doc`. Should I expect two different entries for each overloaded `DecomposeAffineExpressions`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMhWnqF2a4FqDIC5oob:b-8tsv1j)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/test/symbolic_test.py, line 524 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgZOap6ygtipPWEX6V:-MMhUUp8AEkaYfK44AJK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/bindings/pydrake/test/symbolic_test.py#L524)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `vars` is a builtin keyword.

Consider using `vars_` instead.
(There are other examples of this kind of defect in `pydrake`, though, so feel free to dismiss.)
</blockquote></details>

Done.
___
*[bindings/pydrake/test/symbolic_test.py, line 1280 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgZeeq4YrJFIb7PYSZ:-MMhUbvxE9E_rBmxY6gg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/bindings/pydrake/test/symbolic_test.py#L1280)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This should use `assert_arrays_equal`, since tolerance shouldn't be an issue?

If it is, please explicitly specify `rtol` and `atol` (and only use one?).
https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html
</blockquote></details>

Done.
___
*[common/symbolic_decompose.h, line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgXhknCzmAFBHCCseo:-MMhVe0u9LIj1px7GaeI:b-5bk5fd) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.h#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Should this mention that it handles asymmetric matrices, given that you explicitly test it?
</blockquote></details>

Done. `Q` is the output. Here we always output a symmetric matrix.
___
*[common/symbolic_decompose.cc, line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgYlYg8tdX6y4jfQPl:-MMhW3BRC1xSDQ7-AWmC:bq2ui42) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.cc#L144)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why check this in the inner monomials, when you can fail using a higher-level `poly.TotalDegree()`, like what is done for the affine experssion?
https://drake.mit.edu/doxygen_cxx/classdrake_1_1symbolic_1_1_polynomial.html#aaf2a77325f716479b2f8c5b17729a5c6

(If it's for performance, then I'm OK with that, though now this and the affine case diverge a bit.)
</blockquote></details>

Yes this is for performance. calling `poly.TotalDegree()` is more expensive.
___
*[solvers/symbolic_extraction.h, line 82 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMg_E1o608L_1btVJxe:-MMhWKri7PR8VWRV08nZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/solvers/symbolic_extraction.h#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

These dates should be `2021-03-01` (3 months, rounding up), unless you think there's something exceptional about this deprecation:
https://drake.mit.edu/code_review_checklist.html
https://drake.mit.edu/doxygen_cxx/drake__deprecated_8h.html#a847d827d084f28e4ae1788a0ae75be96
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
Yes, you should, bit it looks like `mkdoc` / `clang.cindex` isn't able to pick up the var-as-output flavor.

I don't have a good recommendation here... My only suggestion is you make it easier to see that only the `accept_vars` is exposed, and add something like this in the output-variant:
```
// TODO(#14385): Use `doc.DecomposeAffineExpressions.doc_output_vars` once we figure out why it isn't included in the output.
```

I tested it using the following patch on top of r2 (dd24366550):
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeDoc
```
$ git diff -U1
diff --git a/common/symbolic_decompose.h b/common/symbolic_decompose.h
index f0b471f4b2..a60c984af4 100644
--- a/common/symbolic_decompose.h
+++ b/common/symbolic_decompose.h
@@ -29,2 +29,3 @@ void DecomposeLinearExpressions(
 /// @pre v.rows() == expressions.rows().
+/// @pydrake_mkdoc_identifier{accept_vars}
 void DecomposeAffineExpressions(
@@ -84,2 +85,3 @@ void DecomposeQuadraticPolynomial(
  * @param[out] vars All variables.
+ * @pydrake_mkdoc_identifier{output_vars}
  */
diff --git a/tools/workspace/pybind11/mkdoc.py b/tools/workspace/pybind11/mkdoc.py
index d11a88ef23..fbc46e9a49 100644
--- a/tools/workspace/pybind11/mkdoc.py
+++ b/tools/workspace/pybind11/mkdoc.py
@@ -769,2 +769,3 @@ def main():
     assert len(include_files) > 0
+    include_files = ["drake/common/symbolic_decompose.h"]  # HACK
     unused_ignore_patterns = set(ignore_patterns) - used_ignore_patterns
```

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMkHuRCCtJLEwBUZhlI:b-7xy3xf)* status: needs at least two assigned reviewers

___
*[common/symbolic_decompose.cc, line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MMgYlYg8tdX6y4jfQPl:-MMkG9_b8hD_SrqUrLAc:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/dd24366550b9de29c0674d96c14220fe1022ebcc/common/symbolic_decompose.cc#L144)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Yes this is for performance. calling `poly.TotalDegree()` is more expensive.
</blockquote></details>

OK Thanks!

**Review by hongkai-dai — COMMENTED** [review]
Hmm, I got the following error when I apply the patch
```
ERROR: /home/hongkaidai/drake/bindings/pydrake/common/BUILD.bazel:423:21: C++ compilation of rule '//bindings/pydrake/common:test/deprecation_example/cc_module.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 311 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bindings/pydrake/common/test/deprecation_example/cc_module_py.cc: In function 'void drake::pydrake::{anonymous}::pybind11_init_cc_module(pybind11::module&)':
bindings/pydrake/common/test/deprecation_example/cc_module_py.cc:14:37: error: 'const struct<unnamed>' has no member named 'drake'
   constexpr auto& doc = pydrake_doc.drake.example_class;
```

Are you OK if I just add the TODO, but not applying the patch?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMlWylB3HT4lPSwUXmP:b-nd6di8)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Ew... And yup, sounds good!

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14353#-:-MMvIAWx-0DOM1Hqr7td:b6jb1i6)* status: needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
___
*[solvers/symbolic_extraction.h, line 42 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MXACp1O236A635iZFgY:-MXACp1O236A635iZFgZ:bzdtk9i) ([raw file](https://github.com/robotlocomotion/drake/blob/17cef01221db200bb7becc316845a155b70e9477/solvers/symbolic_extraction.h#L42)):*
> ```objc
>  * Adds context to symbolic expression-related errors.
>  */
> class DRAKE_DEPRECATED("2021-03-01",
> ```

FYI These functions were all in an `internal::` namespace, so we did not need to deprecate them.  We could have just removed this file entirely.

**Comment by hongkai-dai** [comment]
I see, thanks!

**Comment by EricCousineau-TRI** [comment]
___
*[solvers/symbolic_extraction.h, line 42 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14353#-MXACp1O236A635iZFgY:-MXCdWdv2l9ClSo5KIdK:b-9h964s) ([raw file](https://github.com/robotlocomotion/drake/blob/17cef01221db200bb7becc316845a155b70e9477/solvers/symbolic_extraction.h#L42)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI These functions were all in an `internal::` namespace, so we did not need to deprecate them.  We could have just removed this file entirely.
</blockquote></details>

Indeed!
Sorry Hongkai, I should've caught that as well :facepalm: Well, at least advised on using the right date :grimacing:

**Pull request merged**
