### PR TITLE
Add bindings for PiecewisePolynomial and trajectory optimization

### PR DESCRIPTION
**Pull request by RussTedrake**
Add bindings for PiecewisePolynomial
Add bindings for trajectory optimization (MultipleShooting, DirectTranscription, DirectCollocation)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8328)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@ericcousineau-tri for feature review, please.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-:-L7EKZmgBb3iM6FRdxL0:b7kye1q)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-snopt-packaging please
@drake-jenkins-bot mac-highsierra-unprovisioned-clang-bazel-experimental-snopt-packaging please

**Comment by EricCousineau-TRI** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7QHd3pNiJcs_9WLruc:-L7QHd3pNiJcs_9WLrud:b-63aocp) (no related file):*
Overall it looks good, but I'm a bit concerned above having `pydrake.trajectories` rather than `pydrake.common.trajectories`.

Would it be OK with you if I pushed a modified version of this PR that does this?
(I could use this to also move some of the `util` stuff into `common`, or at least file it as a future issue.)

---

*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7QI5Bd3IaEcF0hIyJ3:-L7QI5Bd3IaEcF0hIyJ4:b-2jbowf) ([raw file](https://github.com/robotlocomotion/drake/blob/6118e3ce8bf9321b894e1233b94eec98eb45c4d5/bindings/pydrake/systems/test/trajectory_optimization_test.py#L11)):*
> ```Python
> from pydrake.systems.primitives import LinearSystem
> from pydrake.systems.trajectory_optimization import (
>     DirectCollocation, DirectTranscription
> ```

BTW Could you add a trailing `,`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by RussTedrake** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7QHd3pNiJcs_9WLruc:-L7RLPgbS6LMM8HrJtzi:bps9rd1) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Overall it looks good, but I'm a bit concerned above having `pydrake.trajectories` rather than `pydrake.common.trajectories`.

Would it be OK with you if I pushed a modified version of this PR that does this?
(I could use this to also move some of the `util` stuff into `common`, or at least file it as a future issue.)
</blockquote></details>

it's true, but we also have pydrake.symbolic m pydrake.autodiffutils, ... all yours if you want to clean it up.   

+@jwnimmer-tri for platform review, please. 

---

*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 11 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7QI5Bd3IaEcF0hIyJ3:-L7RMRNrvMPP9ASVVEvz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/6118e3ce8bf9321b894e1233b94eec98eb45c4d5/bindings/pydrake/systems/test/trajectory_optimization_test.py#L11)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Could you add a trailing `,`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7QHd3pNiJcs_9WLruc:-L7RSyvwdtFCRLptG0rB:birkqct) (no related file):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

it's true, but we also have pydrake.symbolic m pydrake.autodiffutils, ... all yours if you want to clean it up.   

+@jwnimmer-tri for platform review, please. 
</blockquote></details>

FYI Eric the C++ namespace is `drake::trajectories`.  Do you want pydrake to use the namespaces or the filepaths?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bindings/pydrake/trajectories_py.cc, line 38 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7RUEmUaUJVw-eYm-jc:-L7RUEmUaUJVw-eYm-jd:b-rojrzl) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/trajectories_py.cc#L38)):*
> ```cpp
>       .def_static("ZeroOrderHold", &PiecewisePolynomial<T>::ZeroOrderHold)
>       .def_static("FirstOrderHold", &PiecewisePolynomial<T>::FirstOrderHold)
>       .def_static("Pchip", &PiecewisePolynomial<T>::Pchip)
> ```

FYI _Meta_ Is omitting argument name like `arg("breaks"), etc.` here conventional?  (Do we have a guide for this?)

---

*[bindings/pydrake/systems/trajectory_optimization_py.cc, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7RWFeeXSn8M7IXd7GD:-L7RWFeeXSn8M7IXd7GE:bxynaxu) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/systems/trajectory_optimization_py.cc#L74)):*
> ```cpp
>   py::class_<DirectCollocation, MultipleShooting>(m, "DirectCollocation")
>       .def(py::init<const systems::System<double>*,
>                     const systems::Context<double>&, int, double, double>())
> ```

FYI This one seems like an especially good candidate for putting some `py::arg` on it.

---

*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7RVQ1XJcf4Ob1MQcIR:-L7RVQ1XJcf4Ob1MQcIS:b-wklku4) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/systems/test/trajectory_optimization_test.py#L20)):*
> ```Python
>         context = plant.CreateDefaultContext()
> 
>         kNumTimeSamples = 21
> ```

FYI _Meta_ This spelling is a bit weird for python -- its C++ style bleeding into here.  I think `num_time_samples` would be conventional python.  On the other hand, I guess there's a fair argument in testing C++ bindings to use C++-inspired spellings, so no defect?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-:-L7RWOs0iU7GqnG8ZX-7:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328#-L7QHd3pNiJcs_9WLruc:-L7Rmwob0V8pZu7yay6x:b-c5r9gx) (no related file):*
> it's true, but we also have pydrake.symbolic m pydrake.autodiffutils, ... all yours if you want to clean it up.

Yup; I had tried out a branch that did the rename, but it does seem more complicated than needed for this module.

> FYI Eric the C++ namespace is drake::trajectories. Do you want pydrake to use the namespaces or the filepaths?

For now, things are reflecting the file directories (for if we ever want to merge the` pydrake` tree into `drake`s tree itself), modulo `pydrake.util` and other items that I want to eventually fix).

Will post this on Slack as well to see what the consensus is.

---

*[bindings/pydrake/trajectories_py.cc, line 38 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328#-L7RUEmUaUJVw-eYm-jc:-L7RqjLn3GstMuNNT0zc:b-4mqe8u) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/trajectories_py.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ Is omitting argument name like `arg("breaks"), etc.` here conventional?  (Do we have a guide for this?)
</blockquote></details>

BTW There is not rule, but it would be good to make one now; my ultimate preference would be to require `py::arg`, but I had not been practicing that consistently. Will post on Slack.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/trajectories_py.cc, line 38 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328#-L7RUEmUaUJVw-eYm-jc:-L7RxkOEEH9orF3ilbPd:bu3r0cw) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/trajectories_py.cc#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW There is not rule, but it would be good to make one now; my ultimate preference would be to require `py::arg`, but I had not been practicing that consistently. Will post on Slack.
</blockquote></details>

BTW 2: I wouldn't defect in this PR, as other modules inconsistently apply `py::arg`. We can wait until to update this code. (However, for the case mentioned by Jeremy below, it would be nice if that one had `py::arg` spelled out.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 20 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328#-L7RVQ1XJcf4Ob1MQcIR:-L7RxwOQBe39WJ5FidrI:b8w4w7j) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/systems/test/trajectory_optimization_test.py#L20)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI _Meta_ This spelling is a bit weird for python -- its C++ style bleeding into here.  I think `num_time_samples` would be conventional python.  On the other hand, I guess there's a fair argument in testing C++ bindings to use C++-inspired spellings, so no defect?
</blockquote></details>

BTW I've defected similar spellings like this, as it's not PEP8, and it's not something imported from C++ code.

My preference would be lower snake case, unless you want to define this at a module level, in which case it should be all-caps.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8328)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bindings/pydrake/systems/trajectory_optimization_py.cc, line 74 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7RWFeeXSn8M7IXd7GD:-L7RzTtF6kafKzlMtZ_B:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/systems/trajectory_optimization_py.cc#L74)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This one seems like an especially good candidate for putting some `py::arg` on it.
</blockquote></details>

Done.

---

*[bindings/pydrake/systems/test/trajectory_optimization_test.py, line 20 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-L7RVQ1XJcf4Ob1MQcIR:-L7S-NWMTImzP6Ly4Taz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/99b474e11fd2df799a907fcf8aa65e18c7a31928/bindings/pydrake/systems/test/trajectory_optimization_test.py#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I've defected similar spellings like this, as it's not PEP8, and it's not something imported from C++ code.

My preference would be lower snake case, unless you want to define this at a module level, in which case it should be all-caps.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 10 files at r1, 1 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328)*

**Comment by jwnimmer-tri** [comment]
Its cute how the two fixes dovetailed.  I had not foreseen that.

FYI @EricCousineau-TRI needs your stamp.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-:-L7S8Wi8GUWF0notFjdY:b-p2llys)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: (thanks for the reminder!)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8328#-:-L7SCHLNykzYOyErgcrP:b9ffafy)*

**Pull request merged**
