### PR TITLE
Fix kcov configuration

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7292)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@jwnimmer-tri for all reviews, please. This fixes the problem introduced by #7165.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7292#-:-KwkP34cL9W1Aq9IHL9z:bgb7ivh)*

**Comment by jwnimmer-tri** [comment]
:lgtm: Thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/dynamic_analysis/kcov.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7292#-KwkPiisa6cKYTFuT-Tz:-KwkPiitEVwXvHnD8NI_:b-cue209) ([raw file](https://github.com/robotlocomotion/drake/blob/5bb1935dc54b994940427ec0d0e4db5276f956d8/tools/dynamic_analysis/kcov.sh#L6)):*
> ```Shell
> me=$(python -c 'import os; print(os.path.realpath("'"$0"'"))')
> WORKSPACE=$(dirname $(dirname $(dirname "$me")))
> ```

FYI Consider adding a fail-fast that `"${WORKSPACE}/WORKSPACE"` exists, for the next time this happens?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7292#-:-KwkPdf5jWqiIFCI80t5:b-g2a5fb)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/dynamic_analysis/kcov.sh, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7292#-KwkPiisa6cKYTFuT-Tz:-KwkSSVIhSNCmz_P6hV4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5bb1935dc54b994940427ec0d0e4db5276f956d8/tools/dynamic_analysis/kcov.sh#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Consider adding a fail-fast that `"${WORKSPACE}/WORKSPACE"` exists, for the next time this happens?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7292)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7292)*

**Pull request merged**
