### PR TITLE
[build] picosat: Fix UBSan complaints

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #17139

Patch picosat locally to avoid null-pointer-arithmetic complaints. Once
upstream PR#2 lands, we can drop this patch.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N5rIk2g2pdcV58veneM:-N5rIk2g2pdcV58veneN:brxpixz) (no related file):*
LSan now has opinions:

```
Using drake_cc_googletest_main.cc

[==========] Running 50 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 50 tests from DrealSolverTest
[ RUN      ] DrealSolverTest.Interval
[       OK ] DrealSolverTest.Interval (0 ms)
[ RUN      ] DrealSolverTest.Available
[       OK ] DrealSolverTest.Available (0 ms)
[ RUN      ] DrealSolverTest.CheckSatisfiabilityTrivialUnsat
[       OK ] DrealSolverTest.CheckSatisfiabilityTrivialUnsat (0 ms)
[ RUN      ] DrealSolverTest.CheckSatisfiabilityTrivialSat
[       OK ] DrealSolverTest.CheckSatisfiabilityTrivialSat (0 ms)
[ RUN      ] DrealSolverTest.CheckSatisfiabilityConjunction
[       OK ] DrealSolverTest.CheckSatisfiabilityConjunction (0 ms)
[ RUN      ] DrealSolverTest.CheckSatisfiabilityDisjunction
dreal_solver_test: external/picosat/picosat.c:3140: void original_clauses_satisfied(PS *): Assertion `clause_satisfied (c)' failed.
/media/ephemeral0/ubuntu/workspace/linux-focal-clang-bazel-experimental-leak-sanitizer/_bazel_ubuntu/121c3126d1aa49ba49792f66511a10a2/sandbox/linux-sandbox/3713/execroot/drake/bazel-out/k8-dbg/bin/solvers/dreal_solver_test.runfiles/drake/tools/dynamic_analysis/lsan: line 7:    20 Aborted                 (core dumped) "$@"

//solvers:dreal_solver_test                                              FAILED in 0.3s

  /media/ephemeral0/ubuntu/workspace/linux-focal-clang-bazel-experimental-leak-sanitizer/_bazel_ubuntu/121c3126d1aa49ba49792f66511a10a2/execroot/drake/bazel-out/k8-dbg/testlogs/solvers/dreal_solver_test/test.log

```

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @jwnimmer-tri, @mwoehlke-kitware, and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N5uSg64CU0CiV9oh4Kk:-N5uSg64CU0CiV9oh4Kl:b9fzjgs) (no related file):*
Placing a hold here while upstream PR discussions proceed.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)* status: LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N5uSg64CU0CiV9oh4Kk:-N5vIFrh9DR7SICLeJoG:bcb53ds) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Placing a hold here while upstream PR discussions proceed.
</blockquote></details>

Upstream discussions complete.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)* status: LGTM missing from assignees jwnimmer-tri(platform),mwoehlke-kitware (waiting on @jwnimmer-tri and @mwoehlke-kitware)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N5qjhWTD321k8XMnymO:-N5vIYG3A9P73cEme8n9:bo5twnq) (no related file):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

Please see review of https://github.com/dreal-deps/picosat/pull/3. It appears the patch could be significantly smaller?
</blockquote></details>

I believe r3 should be better. PTAL.

___

**Review by mwoehlke-kitware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N5qjhWTD321k8XMnymO:-N68eb1KCpounwdubmXB:bw1j0jg) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

I believe r3 should be better. PTAL.
</blockquote></details>

:LGTM: code-wise (also tested locally). Commit could use some additional information (see other comment)?

___
___
*[`-- commits` line 7 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17486#-N68e-5I1OqQ7A67hNUc):*
I guess this should also mention that it updates the picosat SHA? (FYI, the commit and description are out of sync; which one actually gets used?)

**Comment by mwoehlke-kitware** [comment]
Soonho just merged dreal-deps/picosat#3, so this can be updated to just use the latest picosat.

**Review by rpoyner-tri — COMMENTED** [review]
I'll probably just close this one, and do an update-the-hashes PR separately. Thanks for you patience.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17486#-:-N6IsC991Bco9QdowqX8:b-ztkcx)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @rpoyner-tri)

**Pull request closed without merging**
