### PR TITLE
BUILDCOP: Disable flaky test / fix timeouts for MSVC 32 MATLAB

### PR DESCRIPTION
**Pull request by jamiesnape**
See #2320, https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=18333.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2321)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
Ideally I would like to get this in before the nightly builds tonight.

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Ideally I would like to get this in before the nightly builds tonight.</details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2321#-:-KHWp64F6xjJLDhXgWXp:1417088721)*

**Pull request merged**
