### PR TITLE
Move boxes_overlap tests from obb_test to boxes_overlap_test

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This resolves a TODO in `boxes_overlap.cc`. The function is no longer implicitly tested by `obb_test.cc`, but tested directly.

Furthermore, the test is expanded to provide an affordance for visualizing the configurations (this helped in test authoring, clean up, and, I anticipate, future maintenance).

Relates to #21526 

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
Note to reviewers. The commits are (currently) curated.

R1: This is a strict cut-and-paste. Code was lifted directly out of `obb_test.cc` and placed into `boxes_overlap_test.cc` without modification.
R2: These are the modifications that make the test run and update it for its OBB-less spelling.
R3: This provides a mechanism for visualizing the test scenarios. I'm open to this being frivolous. If we want to keep it, we should modify the test rules to include exercising the gflags to make sure they don't bitrot. Let me know what you think.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-1GDyvBMlEDA0LdYWY:blnrywe)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: except the viz affordances, see below.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-7C6k674tkB_lZpaHm:bhkgyw2)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-7C-6m06iOjbQLQLGX:-O-7C-6m06iOjbQLQLGY:bi2yc10) (no related file):*
My first several attempts to use the visualization controls failed. I'm not a fan of fixed-delay-time interfaces, I guess. 

May I suggest you use the scheme we set up for a bunch of Russ's tests? See drake/common/maybe_pause_for_user.h and the various tests that use it.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-7C-6m06iOjbQLQLGX:-O-7CxcqDdRPSil7sg1s:bzapgdk) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

My first several attempts to use the visualization controls failed. I'm not a fan of fixed-delay-time interfaces, I guess. 

May I suggest you use the scheme we set up for a bunch of Russ's tests? See drake/common/maybe_pause_for_user.h and the various tests that use it.
</blockquote></details>

None of that worked for me. Believe me, I tried.

The weird timing affordance is the only thing I could do to get the test to stay alive long enough to get a visualizer browser window populated.

Perhaps the simplest solution is to nuke the visualization.

___

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 1 unresolved discussion, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-7C-6m06iOjbQLQLGX:-O-7I8n93iKw4cXU28e9:bqpe5ni) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

None of that worked for me. Believe me, I tried.

The weird timing affordance is the only thing I could do to get the test to stay alive long enough to get a visualizer browser window populated.

Perhaps the simplest solution is to nuke the visualization.
</blockquote></details>

Nuke is fine with me; now I'm distracted by the fact that all of those other test visualizations appear to broken. But that's not for this PR to worry about.

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@xuchenhan-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-C1vSK-Fg9gbCPQUwt:b223nro)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-7C-6m06iOjbQLQLGX:-O-C1Rql3ccFrFdj8LrH:bymwgjl) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Nuke is fine with me; now I'm distracted by the fact that all of those other test visualizations appear to broken. But that's not for this PR to worry about.
</blockquote></details>

I have an alternative; I actually read the documentation for `MaybePauseForUser()` and updated the instructions. PTAL.

___

**Review by rpoyner-tri — COMMENTED** [review]
linters are whingeing; I could not quite tell why.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-CjgZ0Dhc5QoJp2fBC:boqqn37)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
Platform :lgtm: pending linter failure and squashing commits.
+(release notes: none) 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-CwfFGDp1iyY-I5svi:b8dz1rf)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-Cx8ZJ0yDPv8_0a8UO:-O-Cx8ZJ0yDPv8_0a8UP:b-ub8jj0) (no related file):*
minor, looks like the TODO in `boxes_overlap.cc` can now be retired.

___
___
*[`geometry/proximity/test/boxes_overlap_test.cc` line 145 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-ClbT1CBk6k0H4np1W:-O-ClbT1CBk6k0H4np1X:bgarxfx) ([raw file](https://github.com/RobotLocomotion/drake/blob/7816034f597c21a0595eb6de18f06e95edf34bd0/geometry/proximity/test/boxes_overlap_test.cc#L145)):*
> ```cpp
> }
> 
> class BoxesOverlapTest_ : public ::testing::Test {
> ```

Why the trailing underscore?
___
*[`geometry/proximity/test/boxes_overlap_test.cc` line 198 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CwDIm7BFCb_oy5Hux:-O-CwDIm7BFCb_oy5Huy:b3nyb4t) ([raw file](https://github.com/RobotLocomotion/drake/blob/7816034f597c21a0595eb6de18f06e95edf34bd0/geometry/proximity/test/boxes_overlap_test.cc#L198)):*
> ```cpp
> // 9 cases use the axes defined by the cross product of axes from Frame A and
> // Frame B. We also test that it is robust for the case of parallel boxes.
> TEST_F(BoxesOverlapTest_, AllCases) {
> ```

BTW, the test name ("AllCases") seems to suggest that the set of one test fixture is closed. In that case you could just use `SetUp` instead of `SetUpTestSuites` and get rid of all the `static` keywords.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CxVMY05jJ6I9d5-BV:-O-CxVMZ2L-l-pD5Uu6w:btk7r2l) (no related file):*
The visualization code path should be somehow exercised in CI.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CxVMY05jJ6I9d5-BV:-O-CyA2B6EePcDHDV8-I:b-h8tw3p) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The visualization code path should be somehow exercised in CI.
</blockquote></details>

Suggestion:

I imagine it's easy to only guard the "pause for user" under the visualization gflag.  Making the Meshcat and publishing during the test is still even even if nobody is watching.

Or really, I don't know why we have a gflag at all.  The maybe-pause-for-user is inert during CI testing.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: 4 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CxVMY05jJ6I9d5-BV:-O-CyTiw0YvZWrN4-yco:bgq4jim) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Suggestion:

I imagine it's easy to only guard the "pause for user" under the visualization gflag.  Making the Meshcat and publishing during the test is still even even if nobody is watching.

Or really, I don't know why we have a gflag at all.  The maybe-pause-for-user is inert during CI testing.
</blockquote></details>

... is still _fine_ even if ...

___

**Review by SeanCurtis-TRI — COMMENTED** [review]
Thanks.

One additional change for your eyes.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-:-O-HoRCX-JzWTDHUHCZw:bgk3muf)* status: 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CxVMY05jJ6I9d5-BV:-O-Hk6DuAaR8ZVOY3v6U:bi1ete2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

... is still _fine_ even if ...
</blockquote></details>

I've removed the flag, shifted some documentation, and modified `MaybePauseForUser` to allow for user-defined prompt instructions that only get called if the pause is enabled.

___
___
*[`geometry/proximity/test/boxes_overlap_test.cc` line 145 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-ClbT1CBk6k0H4np1W:-O-HnbwG7c1wmPrkgRwC:b5lie1x) ([raw file](https://github.com/RobotLocomotion/drake/blob/7816034f597c21a0595eb6de18f06e95edf34bd0/geometry/proximity/test/boxes_overlap_test.cc#L145)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Why the trailing underscore?
</blockquote></details>

Done

It's simply one of life's great mysteries.
___
*[`geometry/proximity/test/boxes_overlap_test.cc` line 198 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21546#-O-CwDIm7BFCb_oy5Hux:-O-Hnkod7JGHlxSZZf01:bqwdmiz) ([raw file](https://github.com/RobotLocomotion/drake/blob/7816034f597c21a0595eb6de18f06e95edf34bd0/geometry/proximity/test/boxes_overlap_test.cc#L198)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, the test name ("AllCases") seems to suggest that the set of one test fixture is closed. In that case you could just use `SetUp` instead of `SetUpTestSuites` and get rid of all the `static` keywords.
</blockquote></details>

I was planning on parameterizing them so that one could chose which case(s) they wanted to run. I think that's still a good idea, but I'm kicking it down the road. So, I'm inclined to leave it as is. However, I've added some documentation explaining the reasoning.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21546)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),xuchenhan-tri(platform)

**Pull request merged**
