### PR TITLE
AddQuadraticCost

### PR DESCRIPTION
**Pull request by naveenoid**
QuadraticCosts processed independent of GenericCost

Platform : +@jwnimmer-tri 
Feature : +@sammy-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2692)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/IpoptSolver.cpp, line 407 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLRUMHkU_6kGGQYBPgZ:-KLRUMHlzq9kEusTYN26:976970899) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/IpoptSolver.cpp#L407)):*
> ```cpp
>     cost_cache_->grad.assign(n, 0);
> 
>     for (auto const& binding : problem_->GetAllCosts()) {
> ```

I can't decide if (in all three solvers) the change from generic_costs to GetAllCosts is semantically correct.  Feature reviewer, can you please double-check on this for me?

---

*[drake/solvers/Optimization.h, line 351 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8A_qKxl-8FmTaDoo:-KLR8A_qKxl-8FmTaDop:-1395952410) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L351)):*
> ```objc
>   }
> 
>   void AddQuadraticCost(std::shared_ptr<Constraint> const& obj,
> ```

BTW -- TTBOMK, the `const` here is in the wrong place (should come first).  However, the rest of the file does it this way, so I guess it's fine for now, and fix the whole file in a next PR.

---

*[drake/solvers/Optimization.h, line 351 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8TAHoo2tl3aMlYhV:-KLR8TAHoo2tl3aMlYhW:-1285680775) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L351)):*
> ```objc
>   }
> 
>   void AddQuadraticCost(std::shared_ptr<Constraint> const& obj,
> ```

Missing API documentation.

---

*[drake/solvers/Optimization.h, line 352 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8MG9_VmCy2X2eClN:-KLR8MG9_VmCy2X2eClO:-1657285845) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L352)):*
> ```objc
> 
>   void AddQuadraticCost(std::shared_ptr<Constraint> const& obj,
>   VariableList const& vars) {
> ```

This indentation is incorrect.

---

*[drake/solvers/Optimization.h, line 357 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8Uny4Z5JApetMBf-:-KLR8Uny4Z5JApetMBf0:-1285680775) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L357)):*
> ```objc
>   }
> 
>   void AddQuadraticCost(std::shared_ptr<Constraint> const& obj) {
> ```

Missing API documentation.

---

*[drake/solvers/Optimization.h, line 752 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR93XtRK_hFyk6f6Xv:-KLR93XuZBqzW07b8bam:-1531593841) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L752)):*
> ```objc
>   }
> ```

Extra newline.

---

*[drake/solvers/Optimization.h, line 762 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR9BAWZvhIrwXMvlE0:-KLR9BAXD02AtygDdyOf:-2112117617) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L762)):*
> ```objc
>   }
> 
>   const std::list<Binding<Constraint>> GetAllCosts() const {
> ```

The first `const` here is pointless and thus confusing.

---

*[drake/solvers/Optimization.h, line 762 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLRUYpiMiPBwJhuyhQa:-KLRUYpiMiPBwJhuyhQb:-1285680775) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L762)):*
> ```objc
>   }
> 
>   const std::list<Binding<Constraint>> GetAllCosts() const {
> ```

Missing API documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2692)*

**Comment by sammy-tri** [comment]
:lgtm: (once the remainder of jwnimmer's issues are fixed)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/solvers/IpoptSolver.cpp, line 407 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLRUMHkU_6kGGQYBPgZ:-KLSJ7Vft4PIn-GciFay:2101405661) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/IpoptSolver.cpp#L407)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I can't decide if (in all three solvers) the change from generic_costs to GetAllCosts is semantically correct.  Feature reviewer, can you please double-check on this for me?
</details>
I believe that this change is correct.  I would say that, though, since I originally suggested it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-:-KLSJbdl1YYN7hzUR6kj:1266716929)*

**Comment by naveenoid** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/IpoptSolver.cpp, line 407 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLRUMHkU_6kGGQYBPgZ:-KLSQMtI0aWcyoWX5yHj:-1853665434) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/IpoptSolver.cpp#L407)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> I believe that this change is correct.  I would say that, though, since I originally suggested it.
</details>
From a design perspective : all generic costs include quadratic costs as well. Hence any generic solver should extract all costs.

---

*[drake/solvers/Optimization.h, line 351 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8TAHoo2tl3aMlYhV:-KLShGEGu5fn2faRodLt:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L351)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API documentation.
</details>
Done.

---

*[drake/solvers/Optimization.h, line 357 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8Uny4Z5JApetMBf-:-KLShF5Rfmag1D44Ou8v:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L357)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API documentation.
</details>
Done.

---

*[drake/solvers/Optimization.h, line 752 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR93XtRK_hFyk6f6Xv:-KLSQh8LMfK9rm0814XW:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L752)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Extra newline.
</details>
Done.

---

*[drake/solvers/Optimization.h, line 762 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR9BAWZvhIrwXMvlE0:-KLShDWe8DrC7lxcIC15:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L762)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The first `const` here is pointless and thus confusing.
</details>
Done.

---

*[drake/solvers/Optimization.h, line 762 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLRUYpiMiPBwJhuyhQa:-KLShDtPyyaro73_7y7Y:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L762)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Missing API documentation.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2692)*

**Comment by naveenoid** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/Optimization.h, line 352 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLR8MG9_VmCy2X2eClN:-KLT6F8h6Fx1spMys-Co:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/0a22447fa906806aa6893e08eb8d2518afa8c961/drake/solvers/Optimization.h#L352)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> This indentation is incorrect.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2692)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/solvers/Optimization.h, line 345 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLTXgKyUqXG1wSM1k5i:-KLTXgKzOHXRKMQfI2YD:-723434444) ([raw file](https://github.com/robotlocomotion/drake/blob/d9e66cc5851a5786540f51fe07ddedff091f79ab/drake/solvers/Optimization.h#L345)):*
> ```objc
> 
>   /** AddQuadraticErrorCost
>   * @brief Adds a cost term of the form (x-x_desired)'*Q*(x-x_desired).
> ```

This line and the two after are not indented correctly.

---

*[drake/solvers/Optimization.h, line 765 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLT_D3BEKGvqSUAiwji:-KLT_D3BEKGvqSUAiwjj:-1262723958) ([raw file](https://github.com/robotlocomotion/drake/blob/d9e66cc5851a5786540f51fe07ddedff091f79ab/drake/solvers/Optimization.h#L765)):*
> ```objc
> 
>   /** quadratic_cost
>   *
> ```

Wrong indent.

---

*[drake/solvers/Optimization.h, line 778 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2692#-KLT_DvUVs-MjgsUyZqZ:-KLT_DvUVs-MjgsUyZq_:-1262723958) ([raw file](https://github.com/robotlocomotion/drake/blob/d9e66cc5851a5786540f51fe07ddedff091f79ab/drake/solvers/Optimization.h#L778)):*
> ```objc
> 
>   /** GetAllCosts
>   *
> ```

Wrong indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2692)*

**Comment by naveenoid** [comment]
Grr...messed up the rebase again..Maybe I need a bit of a tutorial. Anyways since Im a few hours ahead of your daylight, I will make a new PR.

**Pull request closed without merging**
