### PR TITLE
Add missing sedumi external

### LINKED ISSUE #3176: SeDuMi external does not download and install when selected
If I turn on the option using the gui (`ccmake ../` then select SeDuMi), it doesn't download and install SeDuMi (but that works for Snopt, for example).  I also tried the command line:
`cmake ../  -DCMAKE_BUILD_TYPE:STRING=Debug -DWITH_SEDUMI:BOOL=ON`
This was in the directory `drake-distro/build`. Then I would run `cmake -j8`. The SeDuMi directory remaines empty.

This was on my Linux Ubuntu 14.04 machine.
Workaround is to manually install SeDuMi.

### PR DESCRIPTION
**Pull request by jamiesnape**
Fixes #3176.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3243)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@mwoehlke-kitware for feature review, @david-german-tri for platform review

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3243#-:-KPy-V4ZivCwuMMPkNpz:bnfp4nl)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3243#-:-KPyDKGCGQJZs6FEy5Cp:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
It would an interesting question to ask how we nuked Sedumi out of existence and CI didn't notice.  Perhaps it didn't have any test coverage?  Or perhaps "polite request" strikes again?

**Comment by jamiesnape** [comment]
The main issue is that the MATLAB `checkDependency` function returns 0 when a dependency is not found.

**Comment by jamiesnape** [comment]
By my calculations there are four tests that need sedumi.

**Comment by jamiesnape** [comment]
For reference, #1997.

**Pull request merged**
