### PR TITLE
Update testSplineGeneration to use googletest

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Update testSplineGeneration to use googletest.  Specifically:
- Replace valuecheck with EXPECT.
- Replace runtime random numbers with source-controlled random numbers.
- Remove performance measurement displayed to cout.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3180)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@lucy-tri for feature review please.
+@sammy-tri for platform review please.

**Comment by Lucy-tri** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/qpSpline/test/testSplineGeneration.cpp, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-KPSuhLx-8NlrJXKRFsV:-KPSuhLyVQi_TPQpT29f:bgt1m42) ([raw file](https://github.com/robotlocomotion/drake/blob/65744fe29690380272628c4b985b89d68164990b/drake/solvers/qpSpline/test/testSplineGeneration.cpp#L13)):*
> double t0 = 0.0;
>   segment_times.push_back(t0);
Why not do:  segment_times.push_back(0.0);

---

*[drake/solvers/qpSpline/test/testSplineGeneration.cpp, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-KPSuxKBrReGNYmvFVk3:-KPSuxKBrReGNYmvFVk4:b-qw3ehz) ([raw file](https://github.com/robotlocomotion/drake/blob/65744fe29690380272628c4b985b89d68164990b/drake/solvers/qpSpline/test/testSplineGeneration.cpp#L16)):*
>  double duration = 1.0;
>     segment_times.push_back(segment_times[i] + duration);

Could eliminate the var here also. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3180)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/qpSpline/test/testSplineGeneration.cpp, line 13 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-KPSuhLx-8NlrJXKRFsV:-KPT-FfI7gFNS1vwkQDr:bxxx505) ([raw file](https://github.com/robotlocomotion/drake/blob/65744fe29690380272628c4b985b89d68164990b/drake/solvers/qpSpline/test/testSplineGeneration.cpp#L13)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> > double t0 = 0.0;
> >   segment_times.push_back(t0);
> Why not do:  segment_times.push_back(0.0);
</details>
I kept the code how used to be.  I suppose it is to clarify the value of "t0", which is a well-known mnemonic variable for math like this?

---

*[drake/solvers/qpSpline/test/testSplineGeneration.cpp, line 16 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-KPSuxKBrReGNYmvFVk3:-KPT-VIcojSolvqcQvJP:b-u7eg7s) ([raw file](https://github.com/robotlocomotion/drake/blob/65744fe29690380272628c4b985b89d68164990b/drake/solvers/qpSpline/test/testSplineGeneration.cpp#L16)):*
<details><summary><i>Previously, Lucy-tri (Lucy) wrote…</i></summary>
> >  double duration = 1.0;
> >     segment_times.push_back(segment_times[i] + duration);
> 
> Could eliminate the var here also. 
</details>
I kept the code how used to be.  There is arguably some value to labeling the magic "1.0" as the "duration" between segments, rather than standing alone within a subexpression.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3180)*

**Comment by Lucy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-:-KPT2VKVNaKKDeRVWkI8:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3180#-:-KPT3tYgU4uat5fg_xgo:bnfp4nl)*

**Pull request merged**
