### PR TITLE
Extracted SDF parser from RigidBodyTree

### PR DESCRIPTION
**Pull request by liangfok**
This contributes to #2676 and builds upon #2707. It is just a refactor; it does not contain any functional change. Once this PR is merged, I'll work on further decoupling the parsers from the `RigidBodyTree` using `Model` container objects.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2720)

### CODE REVIEW

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2441/ but should not be reviewed until after #2707 is merged.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2534/ and is thus ready for review.

Since tomorrow is Thursday and this is just a refactor, +@jwnimmer-tri for both levels of review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM2ADyFUQqHBcFz9ozC:1004607985)*

**Comment by jwnimmer-tri** [comment]
I need to kick this over to @ggould-tri in case he has time for it today.

Furthermore, I don't think we should be so cavalier about only having a single reviewer.  Only the very most trivial reviews (e.g., spelling fixes) should have a single reviewer.  I suggest finding two folks to review.

**Comment by liangfok** [comment]
-@jwnimmer-tri from platform review
+@ggould-tri for platform review
+@amcastro-tri for feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM4jNyLva4RL0Zm8agO:-1965762631)*

**Comment by ggould-tri** [comment]
Minor formatting nits.  Otherwise :lgtm:

---

Reviewed 2 of 17 files at r1, 5 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/parser_sdf.h, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM67-2pg4j5sUie_ZFt:-KM67-2pg4j5sUie_ZFu:-820633329) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/parser_sdf.h#L32)):*
> ```objc
> DRAKERBM_EXPORT
> void addRobotFromSDFInWorldFrame(const std::string& sdf_filename,
>                      const DrakeJoint::FloatingBaseType floating_base_type,
> ```

FYI -- This indentation looks wrong to me.  Does `clang-format` like it?

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2121 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM66QNL1ltDLl51nDFY:-KM66QNL1ltDLl51nDFZ:1171822529) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/RigidBodyTree.cpp#L2121)):*
> ```cpp
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> void RigidBodyTree::addRobotFromSDF(const std::string& sdf_filename,
>                      const DrakeJoint::FloatingBaseType floating_base_type,
> ```

FYI -- Indentation inconsistent with earlier in the file.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2123 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM66E83x_0QyfVBEBcU:-KM66E83x_0QyfVBEBcV:-1056489443) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/RigidBodyTree.cpp#L2123)):*
> ```cpp
>                      const DrakeJoint::FloatingBaseType floating_base_type,
>                      std::shared_ptr<RigidBodyFrame> weld_to_frame) {
>   ::drake::parsers::sdf::addRobotFromSDF(sdf_filename, floating_base_type,
> ```

FYI -- This is the same inconsistent use of the leading `::` as remarked elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM66rMVVR8NTYS2D-za:443996481)*

**Comment by liangfok** [comment]
Thanks for the review! I addressed all reviewer comments. PTAL.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/systems/plants/parser_sdf.h, line 32 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM67-2pg4j5sUie_ZFt:-KM6FJORePpA3TBO5IIT:1965057032) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/parser_sdf.h#L32)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- This indentation looks wrong to me.  Does `clang-format` like it?
</details>
Fixed by running `clang-format`.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2121 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM66QNL1ltDLl51nDFY:-KM6G1320DGq6ZVwFjnQ:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/RigidBodyTree.cpp#L2121)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- Indentation inconsistent with earlier in the file.
</details>
Fixed.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2123 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM66E83x_0QyfVBEBcU:-KM6G2OXMF-AVi4HvRV5:1758359711) ([raw file](https://github.com/robotlocomotion/drake/blob/3f96de38b35b412e45305f01fc6f4731ed646b9e/drake/systems/plants/RigidBodyTree.cpp#L2123)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary>
> FYI -- This is the same inconsistent use of the leading `::` as remarked elsewhere.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM6G3XiAVNRkT6xHUKF:284826000)*

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2548/ and is thus ready for feature review.

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM7BFQ8RRYAbFMfgH4j:-1912804247)*

**Comment by ggould-tri** [comment]
Pinging @amcastro-tri for feature review.

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM9VGmwYDP0BZEScgYP:1854136646)*

**Comment by amcastro-tri** [comment]
This is great. Just two little comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[drake/systems/plants/parser_sdf.h, line 31 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM9n_dGlGYCOKCEzIgo:-KM9n_dH6FXRkyG0YD5S:-194849349) ([raw file](https://github.com/robotlocomotion/drake/blob/dd479e22cee3d40f248dd19458527c396dbdac24/drake/systems/plants/parser_sdf.h#L31)):*
> ```objc
> /// @param[out] tree The rigid body tree to which to add the model.
> DRAKERBM_EXPORT
> void addRobotFromSDFInWorldFrame(
> ```

Consider using style guide naming here since you are creating this file.

---

*[drake/systems/plants/parser_sdf.h, line 51 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM9nlHwwuJ1Uy2oTs5P:-KM9nlHwwuJ1Uy2oTs5Q:-194849349) ([raw file](https://github.com/robotlocomotion/drake/blob/dd479e22cee3d40f248dd19458527c396dbdac24/drake/systems/plants/parser_sdf.h#L51)):*
> ```objc
> /// @param[out] tree The rigid body tree to which to add the model.
> DRAKERBM_EXPORT
> void addRobotFromSDF(const std::string& sdf_filename,
> ```

Consider using style guide naming here since you are creating this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KM9o5a4AdRHf36eKDO5:812690866)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/parser_sdf.h, line 31 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM9n_dGlGYCOKCEzIgo:-KMA1KO7ANCWbdNCVkJ-:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/dd479e22cee3d40f248dd19458527c396dbdac24/drake/systems/plants/parser_sdf.h#L31)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider using style guide naming here since you are creating this file.
</details>
Done.

---

*[drake/systems/plants/parser_sdf.h, line 51 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KM9nlHwwuJ1Uy2oTs5P:-KMA1Jf0DeExQdqZaWQw:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/dd479e22cee3d40f248dd19458527c396dbdac24/drake/systems/plants/parser_sdf.h#L51)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Consider using style guide naming here since you are creating this file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KMA1LecwqogRUvXlgu5:-84625242)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 17 files at r1, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by amcastro-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2115 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5jy3FUXVvEfzKfPa:-KMA5jy3FUXVvEfzKfPb:1726425153) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2115)):*
> ```cpp
>     const DrakeJoint::FloatingBaseType floating_base_type,
>     std::shared_ptr<RigidBodyFrame> weld_to_frame) {
>   drake::parsers::urdf::addRobotFromURDF(urdf_filename, package_map,
> ```

You forgot to refactor the call here. Maybe in other places also.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2120 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5q9SE-ibT5EXFF9j:-KMA5q9SE-ibT5EXFF9k:-469765787) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2120)):*
> ```cpp
> 
> // TODO(liang.fok) Remove this deprecated method prior to release 1.0.
> void RigidBodyTree::addRobotFromSDF(
> ```

ditto

---

*[drake/systems/plants/RigidBodyTree.h, line 127 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5sPw6ybr3NvkIW8o:-KMA5sPw6ybr3NvkIW8p:-469765787) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.h#L127)):*
> ```objc
>   DRAKE_DEPRECATED("Please use drake::parsers::sdf::AddRobotFromSDF.")
>   #endif
>   void addRobotFromSDF(const std::string& sdf_filename,
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by amcastro-tri** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2120 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5q9SE-ibT5EXFF9j:-KMA6Bc6EseNctesKBaB:1570572621) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2120)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> ditto
</details>
Sorry. Disregard this one.

---

*[drake/systems/plants/RigidBodyTree.h, line 127 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5sPw6ybr3NvkIW8o:-KMA6GMpS3FvLTI26-UC:1570572621) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.h#L127)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> ditto
</details>
Sorry. Disregard this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 17 files at r1, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by liangfok** [comment]
I addressed all reviewer comments. PTAL.

---

Review status: 4 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2115 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5jy3FUXVvEfzKfPa:-KMA6YiW_7L8wsJHyl4_:709525768) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2115)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> You forgot to refactor the call here. Maybe in other places also.
</details>
This is for URDF files. Regardless, I went ahead and updated it for consistency as well.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2120 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5q9SE-ibT5EXFF9j:-KMA6Sp6do-ZftBmY2cY:468772122) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2120)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Sorry. Disregard this one.
</details>
I believe I need you to mark this as "satisfied". Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KMAvzUBREJSHsknyohm:-84625242)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 17 files at r1, 10 of 10 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720)*

**Comment by amcastro-tri** [comment]
If CI passes this time :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/plants/RigidBodyTree.cpp, line 2115 \[r6\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-KMA5jy3FUXVvEfzKfPa:-KMAxmRXDtDSvGBIKUOo:-688736339) ([raw file](https://github.com/robotlocomotion/drake/blob/a1e59084783974c45f958d5a5ddd1a5ffe985b94/drake/systems/plants/RigidBodyTree.cpp#L2115)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> This is for URDF files. Regardless, I went ahead and updated it for consistency as well.
</details>
This is the reason the previous CI didn't pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KMAy2NetYXOPcYZoWEO:898724606)*

**Comment by liangfok** [comment]
CI passed. Thus, I'm going to merge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2720#-:-KMB6I1w4_Wp0gHxVJHn:1672305959)*

**Pull request merged**
