### PR TITLE
add ToAutoDiffXd to pose aggregator and associated classes

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5852)

### CODE REVIEW

**Comment by RussTedrake** [comment]
@david-german-tri for feature review.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-KhrQHxFiqvE3WPhXjdU:b-58nllf)*

**Comment by RussTedrake** [comment]
oops +@david-german-tri for feature review

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-KhrQOheI4lZ6GZO72WZ:b-tcndwx)*

**Comment by david-german-tri** [comment]
First pass done, I'll take a more complete look at the tests this afternoon.

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/pose_aggregator.cc, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-KhwYCEq4s_WIWa-I4h4:-KhwYCEq4s_WIWa-I4h5:b-xo845o) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/pose_aggregator.cc#L167)):*
> ```cpp
>       }
>       default: {
>         // Note: kSingelVelocity should be handled in the kSinglePose branch.
> ```

BTW typo `Single`

---

*[drake/systems/rendering/pose_bundle.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-KhwYnuNTLjyqVBKMtiq:-KhwYnuNTLjyqVBKMtir:bw2kpe4) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/pose_bundle.cc#L77)):*
> ```cpp
> 
> template <typename T>
> std::unique_ptr<PoseBundle<AutoDiffXd>> PoseBundle<T>::ToAutoDiffXd() const {
> ```

BTW This is exactly the case I had in mind for #5454.  In the long term, I think it should be an override of `AbstractValue::DoToAutoDiffXd`, the default implementation of which is simply ` Clone`.  @sherm1 @jwnimmer-tri FYI

For the purposes of this PR, I think a `TODO(sherm1)` citing 5454 would be good enough!

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khw_ZNANy0Nz_s8vFtM:b-8g1yox) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
> ```cpp
>   auto pose_vec1 = std::make_unique<PoseVector<double>>();
>   pose_vec1->set_translation(Eigen::Translation<double, 3>(0.5, 1.5, 2.5));
>   // TODO(russt): Consider implementing ToAutoDiffXd for BasicVector<double>?
> ```

We've expressed this as `SetFrom` elsewhere, note similarity between this code and https://github.com/RobotLocomotion/drake/blob/82623cb1929268edb0beb3e7e5b39678b2ca0203/drake/systems/framework/continuous_state.h#L179.

I think sugaring it onto BasicVector is reasonable, though.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_nFYn5CDBtxWLN4v:-Khw_nFYn5CDBtxWLN4w:b-ocp423) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L146)):*
> ```cpp
>       x_pose.matrix()));
> 
>   // The sequel checks the AutoDiffXd conversion.
> ```

BTW, it would be nice if the autodiff stuff were a separate test case, by shifting a bunch of the setup in this case into the fixture.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-Khwa5MCEND3s2-qPA9G:bmw7pso)*

**Comment by RussTedrake** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khwd31oWcev29VPx4Pj:b-vwbwpz) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

We've expressed this as `SetFrom` elsewhere, note similarity between this code and https://github.com/RobotLocomotion/drake/blob/82623cb1929268edb0beb3e7e5b39678b2ca0203/drake/systems/framework/continuous_state.h#L179.

I think sugaring it onto BasicVector is reasonable, though.
</blockquote></details>

The problem is not the setting... it's the goal of getting the right derived classz. Eg consider whoe you would write DoToAutoDiffXd for the constantVectorSource system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by RussTedrake** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khwdrp9uXzNIes6JAGy:b9alyo9) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The problem is not the setting... it's the goal of getting the right derived classz. Eg consider whoe you would write DoToAutoDiffXd for the constantVectorSource system.
</blockquote></details>

... where the ConstabtVector must be of type DrivingCommand, even in the AutoDiffXd version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by david-german-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-KhwmHpw8Kl1-_jqY-lp:bu9g2hp) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
> Eg consider whoe you would write DoToAutoDiffXd for the constantVectorSource system.

`Clone` then `SetFrom` was my thinking - am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by david-german-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khwmq8ACaCzrRticXY0:b-i9fl7e) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> Eg consider whoe you would write DoToAutoDiffXd for the constantVectorSource system.

`Clone` then `SetFrom` was my thinking - am I missing something?
</blockquote></details>

With `BasicVector<T>::SetFrom(const BasicVector<double>&)` being the sugar over `template cast<Foo>` that's currently missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by RussTedrake** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khww83e22Z2An_Fbs0u:bfvazl2) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

With `BasicVector<T>::SetFrom(const BasicVector<double>&)` being the sugar over `template cast<Foo>` that's currently missing.
</blockquote></details>

How exactly do I go from a BasicVector<double>& referencing of a derived class (DrivingCommand), to a DrivingCommand<AutoDiffXd> from inside a class that does not know how BasicVector& was originally created?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by david-german-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khx4ut5hOjfk9jRTBEr:b-q2nhhh) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

How exactly do I go from a BasicVector<double>& referencing of a derived class (DrivingCommand), to a DrivingCommand<AutoDiffXd> from inside a class that does not know how BasicVector& was originally created?  
</blockquote></details>

You can use `dynamic_cast` to downcast, and `Clone` is type-preserving.

```
void CloneThisDrivingCommand(const BasicVector<T>& vec_in) {
  auto typed_original = dynamic_cast<const DrivingCommand<T>*>(&vec_in);
  DRAKE_ASSERT(typed_original != nullptr);

  std::unique_ptr<BasicVector<T>> clone = vec_in.Clone();
  auto typed_clone = dynamic_cast<DrivingCommand<T>*>(clone.get);
  DRAKE_ASSERT(typed_clone != nullptr);
}
```

Example here: https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/test/depth_sensor_test.cc#L93

I'm concerned I might not be correctly understanding your question, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by RussTedrake** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-KhxDuo000vD_S_R1DPU:b-kp288v) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

You can use `dynamic_cast` to downcast, and `Clone` is type-preserving.

```
void CloneThisDrivingCommand(const BasicVector<T>& vec_in) {
  auto typed_original = dynamic_cast<const DrivingCommand<T>*>(&vec_in);
  DRAKE_ASSERT(typed_original != nullptr);

  std::unique_ptr<BasicVector<T>> clone = vec_in.Clone();
  auto typed_clone = dynamic_cast<DrivingCommand<T>*>(clone.get);
  DRAKE_ASSERT(typed_clone != nullptr);
}
```

Example here: https://github.com/RobotLocomotion/drake/blob/master/drake/systems/sensors/test/depth_sensor_test.cc#L93

I'm concerned I might not be correctly understanding your question, though.
</blockquote></details>

The ConstantVectorSystem, where the proposed code would live, does not know it was built with DrivingCommand passed in the constructor.  Use of DrivingCommand explicitly in the code here is not possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by david-german-tri** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-KhxIXS6C2vvm_-so9wK:b-qvamdz) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

The ConstantVectorSystem, where the proposed code would live, does not know it was built with DrivingCommand passed in the constructor.  Use of DrivingCommand explicitly in the code here is not possible.
</blockquote></details>

OH, I see the problem now, apologies for being slow.

I agree `BasicVector<T>::ToAutoDiffXd` would work.  It has the advantage of being easy to read, and the disadvantage of being a little boilerplate-heavy, and of breaking the rule that `System`s are responsible for transmogrification.  (I did _just_ propose to break that rule for AbstractValue, undermining my own moral consistency here, but that one really can't be solved any other way as far as I can tell.)

Another option that occurs to me: systems like `ConstantVectorSource` could be templated on their vector type as well as their scalar type, with BasicVector by default.  It has the inverse pros and cons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-KhxL-qvAhLYZQJJH82p:bzdwe9o)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 80 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_ZN9Bmk_iqLFgeko:-Khxis3oS8_cfL0T9KV-:b-eahmrz) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L80)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

OH, I see the problem now, apologies for being slow.

I agree `BasicVector<T>::ToAutoDiffXd` would work.  It has the advantage of being easy to read, and the disadvantage of being a little boilerplate-heavy, and of breaking the rule that `System`s are responsible for transmogrification.  (I did _just_ propose to break that rule for AbstractValue, undermining my own moral consistency here, but that one really can't be solved any other way as far as I can tell.)

Another option that occurs to me: systems like `ConstantVectorSource` could be templated on their vector type as well as their scalar type, with BasicVector by default.  It has the inverse pros and cons.

</blockquote></details>

(Marking myself satisfied)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-KhxjFSCYQ4K6mZdZk69:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/rendering/pose_aggregator.cc, line 167 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-KhwYCEq4s_WIWa-I4h4:-Ki-a3c3BsNF91xS9mA2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/pose_aggregator.cc#L167)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW typo `Single`
</blockquote></details>

Done.

---

*[drake/systems/rendering/pose_bundle.cc, line 77 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-KhwYnuNTLjyqVBKMtiq:-Ki-adtU986JKlD6IgRQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/pose_bundle.cc#L77)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW This is exactly the case I had in mind for #5454.  In the long term, I think it should be an override of `AbstractValue::DoToAutoDiffXd`, the default implementation of which is simply ` Clone`.  @sherm1 @jwnimmer-tri FYI

For the purposes of this PR, I think a `TODO(sherm1)` citing 5454 would be good enough!
</blockquote></details>

Done.

---

*[drake/systems/rendering/test/pose_aggregator_test.cc, line 146 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-Khw_nFYn5CDBtxWLN4v:-Ki-ahwrGJOP4Vw0xXNK:bfwfyt2) ([raw file](https://github.com/robotlocomotion/drake/blob/4af90a25e767b89b447d46c8e574d0f9025aa931/drake/systems/rendering/test/pose_aggregator_test.cc#L146)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW, it would be nice if the autodiff stuff were a separate test case, by shifting a bunch of the setup in this case into the fixture.
</blockquote></details>

Agreed, and I thought about it.  But the code is a bit intertwined (since I have to clone the autodiff pieces before the ownership is passed into system, etc).  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by RussTedrake** [comment]
+@sammy-tri  for platform

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-Ki-owJYbCsmGdLy7_5H:bshrgpl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5852#-:-Ki0QMhxB5Ypmcly1-T8:bnfp4nl)*

**Pull request merged**
