### PR TITLE
Changes velocity to momentum in velocity-level constraint problem data.

### PR DESCRIPTION
**Pull request by edrumwri**
Velocity-level constraint data had been storing generalized velocity, but it turns out that we need generalized momentum for a computation with bilateral constraints. This PR gets around a kludge that used the inverse of the inverse of the generalized inertia matrix (!) to determine the generalized momentum.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7262)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@amcastro-tri for feature review please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7262#-:-Kwp1bTOKZZxWrccbSXJ:brbsdox)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7262#-:-KxEZYVIn0cwlNNR98Yu:bnfp4nl)*

**Comment by edrumwri** [comment]
+@sammy-tri for platform review please (per regular rotation)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7262#-:-KxEwVHdsJKyzUM1teFF:b-ugdwr5)*

**Comment by sammy-tri** [comment]
+(status: curate commits before merging) :lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7262#-:-KxFP0_i7P_uHJcbN9hb:bsf2vkf)*

**Pull request merged**
