### PR TITLE
doc: Add release notes v0.14.0

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Approximate release candidate is ~2020-01-15~ 2020-01-16. Checklist (pulling from [Playbook](https://docs.google.com/document/d/1Fn24n7caMCSEPclGCELvmzHqbHxvJQ4tvyb3uw1KgZY/edit#)):
- [x] Review
- [x] Find plausible build for release candidate, update in release notes: 5259cc0ae11add6d00d1d4baf1f1c2946ca624b0
 - https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-mojave-unprovisioned-clang-bazel-nightly-snopt-packaging/273/consoleText
 - https://drake-jenkins.csail.mit.edu/view/Packaging/job/linux-bionic-unprovisioned-gcc-bazel-nightly-snopt-packaging/433/consoleText
- [x] Prepare binaries
- [ ] Merge release notes PR
- [ ] Draft GitHub release page
- [ ] Publish

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12571)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
___
*[doc/release_notes/v0.14.0.rst, line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12571#-LyVsQ3tENeY5KHXyxWy:-LyVsQ3tENeY5KHXyxWz:b-voayno) ([raw file](https://github.com/robotlocomotion/drake/blob/d5cd2c99ca76bf5a4cd763c53fa940b8c01aa944/doc/release_notes/v0.14.0.rst#L328)):*
> ```reStructuredText
> ------------------------
> 
> * Add python bindings for PendulumGeometry (`#12569`_)
> ```

Is this list duplicative of the above?  The prior workflow was to remove lines here that have been sorted into the above.  This PR at least seems duplicated.

**Comment by EricCousineau-TRI** [comment]
___
*[doc/release_notes/v0.14.0.rst, line 328 at r1](https://reviewable.io/reviews/robotlocomotion/drake/12571#-LyVsQ3tENeY5KHXyxWy:-LyWDzfy9p9E__8FJ4HZ:bc6i46b) ([raw file](https://github.com/robotlocomotion/drake/blob/d5cd2c99ca76bf5a4cd763c53fa940b8c01aa944/doc/release_notes/v0.14.0.rst#L328)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, yup, I can do that. Will force-push in this case.
</blockquote></details>

Er, but may timebox to 15min...

**Comment by EricCousineau-TRI** [comment]
Crap, accidentally let myself force push. Gonna try to get it back.

**Comment by EricCousineau-TRI** [comment]
Meh, just going to re-merge.

**Comment by EricCousineau-TRI** [comment]
Tested build of docs locally; going to go ahead and merge.

**Comment by EricCousineau-TRI** [comment]
https://github.com/RobotLocomotion/drake/releases/tag/v0.14.0

**Pull request merged**
