### PR TITLE
Fixed DRC Terrain Cinder Block Heights

### PR DESCRIPTION
**Pull request by scottviteri**
This version takes into account the correct individual cinder block heights.

adjustedheights

### CODE REVIEW

**Comment by kuindersma** [comment]
The blocks in the image don't look quite right to me (the zig-zag blocks look too tall and the others look too short).

**Comment by RussTedrake** [comment]
@scottviteri  -- can you communicate w/ @rdeits and @kuindersma to make sure we get this one right?

**Comment by rdeits** [comment]
I'm looking at the terrain now, and @kuindersma I think you're right: it looks like the chevron blocks are 0.2m high and the wide blocks are 0.09m high. I'll try to figure out what the correct value is

**Comment by kuindersma** [comment]
@hongkai-dai measured the cinder block heights for the jumping stuff. Hongkai, do you have that number handy?

**Comment by rdeits** [comment]
It looks to be 0.146m from some of our old affordance models.

**Comment by rdeits** [comment]
@scottviteri can you re-run your script to update the block heights?

**Comment by scottviteri** [comment]
Alright.

Before I fix this I wasn't to make sure I have the right values. The
current heights just come from comments in the original model files that
specify a desired size.

Is the case that all blocks are 0.146m, or are the zigzag blocks and stack
blocks different in height?

Also, I researched for while but did not find a better description of the
tilt pattern of the last file. I believe it is more complicated than what I
have.
Some pictures exist but either do not show both sides or are
indistinguishable.
Does anyone have a better idea of the pattern or a reliable source of the
information?

Thanks,
Scott Viteri

**Comment by scottviteri** [comment]
*want
I apologize for the typo: I sent this from my phone.

**Comment by kuindersma** [comment]
> Is the case that all blocks are 0.146m, or are the zigzag blocks and stack blocks different in height?

All blocks are the same height.

**Comment by rdeits** [comment]
@scottviteri I think the tilted block pattern you've got looks good. I believe it matches exactly what we saw at the DRC trials. And as Scott K. said, all the blocks should be the same height. Physically, the square blocks that make up the flat and tilted steps are just two cinderblocks strapped together (but representing them as a single square block in the model, as you've done, is perfectly fine).

**Comment by rdeits** [comment]
@scottviteri I just checked this out. The block sizes look right to me, and the arrangements are all good. I noticed that the level and tilted stacks are actually floating slightly above the ground now. I've put in a pull request against your drake fork to fix it: https://github.com/scottviteri/drake/pull/1 If you approve that request, then this pull request should automatically include my fix.

**Comment by scottviteri** [comment]
Thanks!

**Pull request merged**
