### PR TITLE
Add drake-config.cmake for bazel

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Create `drake.cps` with the targets and includes as currently produced by bazel, and add` drake-config.cmake` generated by the same. Teach `package_drake.sh` to install this.

This should make bazel-built drake usable by external (CMake) consumers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5763)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8hoPYRkzLK8WKsWiV:b-h4qpjy) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
> ```CMake
> 
> # Generated by cps2cmake
> ```

BTW Should this have (or somewhere nearby have_ some kind of pointer or TODO on how a person can run cps2cmake (or that it's not possible to do that yet).

---

*[tools/drake.cps, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hPjGsc37IWMzze7D:-Kh8hPjGsc37IWMzze7E:b-c0jkbs) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L1)):*
> ```delphi
> {
> ```

I don't think a drake developer will typically know what a `*.cps` file is.  Please add some documentation either here, or in some related folder, explaining what's going on here.

---

*[tools/drake.cps, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8h_7HubPDEiSz9RLr:-Kh8h_7HubPDEiSz9RLs:bicrbfr) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L14)):*
> ```delphi
>         "@prefix@/include/external/spdlog",
>         "@prefix@/include/external/tinyobjloader"
>       ]
> ```

Please help the maintainer of this by commenting something like in slack, as in "this should match the list of folders in package_drake.sh's include/external folder" or whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-Kh8i-HbvOmEB8E79qRG:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8lX3QgrNzNqrVH0y1:btc2r8l) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this have (or somewhere nearby have_ some kind of pointer or TODO on how a person can run cps2cmake (or that it's not possible to do that yet).
</blockquote></details>

Would it make sense to add this step to `package_drake.sh`, instead of checking in the generated code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8kPUZJ7fKT__KNix6:bqavucf) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this have (or somewhere nearby have_ some kind of pointer or TODO on how a person can run cps2cmake (or that it's not possible to do that yet).
</blockquote></details>

Not possible; ATM that tool only exists on my laptop. (I thought I'd pushed it to github, but apparently not yet. I'll try to do that Monday, if not this evening.)

---

*[tools/drake.cps, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hPjGsc37IWMzze7D:-Kh8lF20g6nY93-0E5Ev:b-n7v8tx) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think a drake developer will typically know what a `*.cps` file is.  Please add some documentation either here, or in some related folder, explaining what's going on here.
</blockquote></details>

See http://mwoehlke.github.io/cps. I'm not sure how much we want to advertise CPS yet, however? TBH I'm a little on the fence currently even including the .cps, as it is of limited use currently.

---

*[tools/drake.cps, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8h_7HubPDEiSz9RLr:-Kh8llImkCQQjLtel7PG:b-xb30oi) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Please help the maintainer of this by commenting something like in slack, as in "this should match the list of folders in package_drake.sh's include/external folder" or whatever.
</blockquote></details>

How do you prefer to do that, considering this is a JSON document? (Offhand, maybe adding something like a `cps-howto` would make sense?) In the long term, it would be much preferable if bazel generated this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8rYBEwlgZ5fmnKYg_:blikdqx) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
> Would it make sense to add this step to `package_drake.sh`

I'd say "yes", but how will PyCPS be obtained? (And is it okay for the script to depend on that, and by extension, on Python?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8sJOwTC5GibItTYpM:b5ghj7e) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> Would it make sense to add this step to `package_drake.sh`

I'd say "yes", but how will PyCPS be obtained? (And is it okay for the script to depend on that, and by extension, on Python?)
</blockquote></details>

I should add: I like that as a _long term_ plan. I'm less convinced it needs to be automated from the get-go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by david-german-tri** [comment]
:lgtm:

cc @stonier FYI

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hoPYRkzLK8WKsWiU:-Kh8uFl3LGzQLMIEs-Yf:b-reffc3) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L2)):*
> I'd say "yes", but how will PyCPS be obtained? (And is it okay for the script to depend on that, and by extension, on Python?)

I'm fine with pulling in CPS tools as Bazel workspace externals in Drake.  Then package_drake.sh can just `bazel run //tools:the_cps_thing`.  It's already a done deal that Drake depends on Python.

>   I should add: I like that as a long term plan. I'm less convinced it needs to be automated from the get-go.

Yeah, I now agree.  Marking myself satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-Kh8ug2KSTl4weazY0-Q:buuj38b)*

**Comment by david-german-tri** [comment]
(I was able to build and run a little Adder diagram locally using this package.  Awesome!)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-Kh8vNltJ6cKp0T3WTvT:b57eb5b)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/drake-config.cmake, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8viStkiPzfmFHNeXj:-Kh8viSu0XqWAKxPIoiX:b-2s5t6s) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L5)):*
> ```CMake
> 
> if(CMAKE_MAJOR_VERSION LESS 3)
>   message(FATAL_ERROR "CMake >= 3.0 required")
> ```

BTW if it's possible to make this file insist on C++14, that would be nice.  (I had to specify it in my downstream project, cued by compiler errors, not by CMake.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/drake-config.cmake, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8viStkiPzfmFHNeXj:-Kh8w972Npl8Kl3Ddel6:b-4zqpt) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L5)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW if it's possible to make this file insist on C++14, that would be nice.  (I had to specify it in my downstream project, cued by compiler errors, not by CMake.)
</blockquote></details>

BTW Really that should be in the target properties of `drake::drake` so that the flags are added automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.cps, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hPjGsc37IWMzze7D:-Kh9goKKfODmYg_WX173:b-pl23pr) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L1)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

See http://mwoehlke.github.io/cps. I'm not sure how much we want to advertise CPS yet, however? TBH I'm a little on the fence currently even including the .cps, as it is of limited use currently.
</blockquote></details>

If its in `master` it should at least be clear to Drake Developers what the file is for and what its doing in the tree.  I'd say its author's discretion whether that means removing this from the PR vs adding a short note like "stay tuned; here's a teaser URL" or whatever.

---

*[tools/drake.cps, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8h_7HubPDEiSz9RLr:-Kh9fIz9GfalMb_lcmpA:b-8dy3kb) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L14)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

How do you prefer to do that, considering this is a JSON document? (Offhand, maybe adding something like a `cps-howto` would make sense?) In the long term, it would be much preferable if bazel generated this...
</blockquote></details>

Probably the document structure should be amended to allow for comments?  Otherwise that a pretty bad limiting for using it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/drake.cps, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8h_7HubPDEiSz9RLr:-Kh9qZ_I6YvHXGgsdTQm:b-aosolc) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Probably the document structure should be amended to allow for comments?  Otherwise that a pretty bad limiting for using it.
</blockquote></details>

You mean change from JSON? It is a data format, so it deliberately does not have any notion of comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jwnimmer-tri** [comment]
*[tools/drake.cps, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8h_7HubPDEiSz9RLr:-Kh9rjPkVTgKI56ItRfa:b-pwao94) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L14)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You mean change from JSON? It is a data format, so it deliberately does not have any notion of comments.
</blockquote></details>

Looking at stackoverflow for "json comment", there are plenty bits of advice on how to add them in as part of the data.

Given that these files are de-facto human-readable and human-editable, I think its reasonable to insist that humans can write comments too.

But in any case, even if the comment has to live in a separate location like a README or HOWTO, it could still be documented as part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhNlhdOp7yNyFYf8F5c:byb2dfq) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
> ```CMake
> set_target_properties(drake::drake PROPERTIES
>   IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libdrake.so"
>   INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/external/bullet;${_IMPORT_PREFIX}/include/external/eigen;${_IMPORT_PREFIX}/include/external/fmt;${_IMPORT_PREFIX}/include/external/spdlog;${_IMPORT_PREFIX}/include/external/tinyobjloader"
> ```

BTW Original idea was to have `drake::bullet`, `drake::eigen`, `drake::fmt`, `drake::spdlog`, and `drake::tinyobjloader` targets, but I guess we do not really need them. Also where are the paths to the external libraries referenced. Not all externals referenced here are header only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhNmVfBN9aa9nJx-lbz:b-h743n1) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Original idea was to have `drake::bullet`, `drake::eigen`, `drake::fmt`, `drake::spdlog`, and `drake::tinyobjloader` targets, but I guess we do not really need them. Also where are the paths to the external libraries referenced. Not all externals referenced here are header only.
</blockquote></details>

Actually, that last part should not be a BTW.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhNyBxWgPkaHzIAKsBb:b1dge4n) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
> Original idea was to have `drake::bullet`, `drake::eigen`, `drake::fmt`, `drake::spdlog`, and `drake::tinyobjloader` targets, but I guess we do not really need them. Also where are the paths to the external libraries referenced. Not all externals referenced here are header only.

*What* external libraries? ATM, the only library I see (visible in an install) is `libdrake.so`.

If this changes at some point in the future, we can update things accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhO8ZNboZhAFO1z5u35:b-j68y4h) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

You are referencing Bullet headers. If they are not needed, remove them. Otherwise, you need the library.
</blockquote></details>

Interesting.  Those headers are in the Bazel package because they're in the transitive closure of `_LIBDRAKE_COMPONENTS`.  

```
$ bazel query 'somepath(//drake/multibody/parsers, @bullet//:lib)'
............
//drake/multibody/parsers:parsers
//drake/multibody:rigid_body_tree
//drake/multibody:rigid_body_tree_cc
//drake/multibody/collision:collision
//drake/multibody/collision:bullet_collision
@bullet//:lib
```

However, the linker didn't create a runtime dependency on the bullet library:

```
$ ldd libdrake.so
	linux-vdso.so.1 =>  (0x00007fff1fd44000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5d366b2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5d363ac000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5d36194000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5d35f76000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5d35bae000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558f1c1af000)
```

I think this is because the Bazel dependencies declared for `rigid_body_tree_cc` are too expansive - it only really needs `collision_api` and  `model`.  I'll try PRing that.  @seancurtis-tri FYI.  

In the meantime, I think it would be reasonable to proceed on this PR without the bullet headers, as @jamiesnape suggests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jwnimmer-tri** [comment]
*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOF08Q_x5KA5LBWtKM:bj4hn43) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Interesting.  Those headers are in the Bazel package because they're in the transitive closure of `_LIBDRAKE_COMPONENTS`.  

```
$ bazel query 'somepath(//drake/multibody/parsers, @bullet//:lib)'
............
//drake/multibody/parsers:parsers
//drake/multibody:rigid_body_tree
//drake/multibody:rigid_body_tree_cc
//drake/multibody/collision:collision
//drake/multibody/collision:bullet_collision
@bullet//:lib
```

However, the linker didn't create a runtime dependency on the bullet library:

```
$ ldd libdrake.so
	linux-vdso.so.1 =>  (0x00007fff1fd44000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5d366b2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5d363ac000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5d36194000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5d35f76000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5d35bae000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558f1c1af000)
```

I think this is because the Bazel dependencies declared for `rigid_body_tree_cc` are too expansive - it only really needs `collision_api` and  `model`.  I'll try PRing that.  @seancurtis-tri FYI.  

In the meantime, I think it would be reasonable to proceed on this PR without the bullet headers, as @jamiesnape suggests.

</blockquote></details>

@david-german-tri I don't think that's true; I think `rigid_body_tree.cc`'s constructor implementation calls `DrakeCollision::newModel()` which requires `bullet_collision`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOFQ38-PXORP--KNN5:bp63l2g) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@david-german-tri I don't think that's true; I think `rigid_body_tree.cc`'s constructor implementation calls `DrakeCollision::newModel()` which requires `bullet_collision`.
</blockquote></details>

@jwnimmer-tri is correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jwnimmer-tri** [comment]
*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOFOUcif9i2ojz6Ctw:bqzbxnj) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

@jwnimmer-tri is correct.
</blockquote></details>

Bullet is not showing up in the `ldd` because its linked in statically (with PIC).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOFjfgAB1-stbD_tsx:b-83g9ba) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Bullet is not showing up in the `ldd` because its linked in statically (with PIC).
</blockquote></details>

I forgot about that. I guess everything is good then, though, personally, I would prefer linking to a `libdrakebullet.so`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOHV2UnTTeQrSefHan:b810a2k) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
> personally, I would prefer linking to a `libdrakebullet.so`

Me too, but for the moment, there is no such libary. If/when that changes, the CPS (and generated `drake-config.cmake`) can be updated accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by david-german-tri** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/drake-config.cmake, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-KhNlhdOp7yNyFYf8F5b:-KhOItHA3LQmVCe_j2S4:bb73djm) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L49)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary><blockquote>

> personally, I would prefer linking to a `libdrakebullet.so`

Me too, but for the moment, there is no such libary. If/when that changes, the CPS (and generated `drake-config.cmake`) can be updated accordingly.

</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-KhOJNmzUklO7aYcISA7:bnfp4nl)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/drake-config.cmake, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8viStkiPzfmFHNeXj:-KhOL4hK1HLjjUAe501Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake-config.cmake#L5)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Really that should be in the target properties of `drake::drake` so that the flags are added automatically.
</blockquote></details>

Done.

---

*[tools/drake.cps, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-Kh8hPjGsc37IWMzze7D:-KhOI5rj7M9EwZbgwwjJ:b-9v9821) ([raw file](https://github.com/robotlocomotion/drake/blob/32bbd9cfb8ffe59b409198a88267b525fdefa3d0/tools/drake.cps#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If its in `master` it should at least be clear to Drake Developers what the file is for and what its doing in the tree.  I'd say its author's discretion whether that means removing this from the PR vs adding a short note like "stay tuned; here's a teaser URL" or whatever.
</blockquote></details>

See `X-Purpose`; does that seem sufficient?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by jwnimmer-tri** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763)*

**Comment by mwoehlke-kitware** [comment]
> if it's possible to make this file insist on C++14, that would be nice

@david-german-tri, can you confirm if this is working now for you? (I *think* it is, but I don't entirely trust testing on my machine, because my GCC defaults to newer C++.)

**Comment by david-german-tri** [comment]
I don't think it is.  Unless I specify `CXX_STANDARD` in my CMakeLists, gcc-4.9 still doesn't get a `-std` flag, and spews all sorts of errors.  Happy to help debug in realtime on Slack, if that would be useful.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-KhObqDJuvtu5UJzz89C:booayei)*

**Comment by david-german-tri** [comment]
Resolved - CMake was rooting around in my homedir to find some other `drake-config.cmake`.  Once I steered it toward the actual up-to-date config from this PR, it deduced to use `-std=gnu++14`.  :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5763#-:-KhOfHcDGRrrd5U-qQhs:bgd3xax)*

**Pull request merged**
