### PR TITLE
[analysis] Update MonteCarlo to use Parallelism API

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
+@calderpg-tri for feature review, please.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785)

### CODE REVIEW

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785)* status: 1 unresolved discussion, LGTM missing from assignee calderpg-tri, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`systems/analysis/test/monte_carlo_test.cc` line 292 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-NoKGwgI56a1ug7gwqIm:-NoKGwgJ80AEcf-20t0c:b-xvn3sv) ([raw file](https://github.com/RobotLocomotion/drake/blob/14c29d7460350f417b00507df18db351638296ee/systems/analysis/test/monte_carlo_test.cc#L292)):*
> ```cpp
>                        num_samples, &generator, kNoConcurrency);
>   MonteCarloSimulation(make_simulator, &GetScalarOutput, final_time,
>                        num_samples, &generator, kUseHardwareConcurrency);
> ```

It probably doesn't matter for such a simple test system, but note that this will use more threads than before (and more than are specified in the test rule).

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-:-NoKYrrE0vdLoF8ZouSs:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignees calderpg-tri,sherm1(platform)

___
*[`systems/analysis/test/monte_carlo_test.cc` line 292 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-NoKGwgI56a1ug7gwqIm:-NoKYklzEKG7cWQMfr-Y:bv75dra) ([raw file](https://github.com/RobotLocomotion/drake/blob/14c29d7460350f417b00507df18db351638296ee/systems/analysis/test/monte_carlo_test.cc#L292)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

It probably doesn't matter for such a simple test system, but note that this will use more threads than before (and more than are specified in the test rule).
</blockquote></details>

Good point, that was doing more harm than good.

**Review by calderpg-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-:-NoKdM8b1GXxU8rxH-R2:bnfp4nl)* status: LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with one ignorable suggestion

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-:-NoOTlCS023LOkeCtRmL:bjuia4f)* status: 1 unresolved discussion

___
*[`bindings/pydrake/systems/analysis_py.cc` line 404 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-NoOTRkd507piwt8i0IF:-NoOTRkd507piwt8i0IG:bsbjks) ([raw file](https://github.com/RobotLocomotion/drake/blob/b8c50032d9317b19145c262ad050546c0739ccf9/bindings/pydrake/systems/analysis_py.cc#L404)):*
> ```cpp
>                           -> std::vector<RandomSimulationResult> {
>           return MonteCarloSimulation(make_simulator, output, final_time,
>               num_samples, generator, /* parallelism = */ Parallelism::None());
> ```

BTW the `/* parallelism = */` comment seems superfluous here (would make sense if using the `false` abbreviation)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20785)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees calderpg-tri,sherm1(platform)

___
*[`bindings/pydrake/systems/analysis_py.cc` line 404 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20785#-NoOTRkd507piwt8i0IF:-NoOWqxJ6U-kbEL460qJ:boo1o14) ([raw file](https://github.com/RobotLocomotion/drake/blob/b8c50032d9317b19145c262ad050546c0739ccf9/bindings/pydrake/systems/analysis_py.cc#L404)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the `/* parallelism = */` comment seems superfluous here (would make sense if using the `false` abbreviation)
</blockquote></details>

Fair, but for my taste I like highlighting the pseudo-`py::arg` name here, as a kind of placeholder, grep target, etc.  Omitting a kwarg in a binding is quite unusual, so the more I can do to help call attention to the oddity, the better (I hope).

**Pull request merged**
