### PR TITLE
Provide implicit conversion to bool from Bool<T> when Bool<T>::value is bool

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9127)

### CODE REVIEW

**Comment by sherm1** [comment]
FYI in f2f discussion @mitiguy mentioned being confused by the `.value()` name which doesn't actually return a numeric value in some cases (can be a formula). He suggested changing that name to `.result()` instead which wouldn't have the same implication.

**Comment by mitiguy** [comment]
http://www.wolframalpha.com/input/?i=value
Value is defined as:
A numerical quantity measured or assigned or computed.

I'll ponder suggestions for change.
I prefer result to value -- but I need to think about this in context for the documentation for the class.

**Comment by sherm1** [comment]
Paul, I assume you would stretch to include `true` and `false` as "numeric" by that definition?

**Comment by soonho-tri** [comment]
I think `type` and `value` have the same generality. If a `type` does not necessarily imply a `numerical type`, a `value` doesn't have to be interpreted as a `numerical value`.

We have another instance in Drake which uses `value` as a more general notion. It's `reset_on_copy<T>` written by @sherm1. Of course, I admit that it has superior documentation.

https://github.com/RobotLocomotion/drake/blob/master/common/reset_on_copy.h

**Comment by sherm1** [comment]
Ha ha -- good example! I do agree with you that `value_type` in C++ is a term of art for containers, and doesn't have to be numerical. Generally if I have some `container<T>` then its `value_type` is T. `std::vector<T>` and `reset_on_copy<T>` are both containers for objects of type T.

However, `Bool<T>` is _not_ a container for objects of type T. Instead it contains an object of whatever type is returned by `T() < T()`, which in practice is either a `bool` or `symbolic::Formula`. That is, it contains the _result_ of an operation on T, not a _value_ of type T.

So although I don't buy Paul's "value should be numeric" argument in a C++ context, I also don't think the use of `value_type` in Bool is consistent with its use in other containers. My preference would be to call that something like `result_type` and to have the access method be `.result()`.

**Comment by jwnimmer-tri** [comment]
> ... if I want to write scalar type-independent code, I should always write if (ExtractBoolOrThrow(expr)) rather than if (expr), right?

If you are application-level code, you probably might use ExtractBoolOrThrow.  If you are writing generic code, you generally should not degrade down to `bool`, but rather use `if_then_else` or `cond`.

**Pull request merged**
