### PR TITLE
[geometry/optimization] Remove requirement that CartesianProduct sets must be bounded

### PR DESCRIPTION
**Pull request by mpetersen94**
@AlexandreAmice for feature review (namely to confirm `DoIsBounded` is correct)

cc @RussTedrake @TobiaMarcucci

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
Still need tests for the case of CartesianProduct between unbounded sets (i.e. you never have a case that DoIsBounded returns false). Your `DoIsBounded` is correct  because we have a countable number of sets and we assume the product topology for the CartesianProduct. (Just writing this in case a topologist comes along and wants to ask about infinite products/weird topologies).

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NEi3NOzCfob3Em1KzDU:b-e4wd7b)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NEi7sTy4HRcaAhZM9VM:b-896fix)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140)* status: 2 unresolved discussions, LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`geometry/optimization/test/cartesian_product_test.cc` line 132 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18140#-NEuCMOd2oG4HFo884j4:-NEvJ0AZ7scjD2QWfpou:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08b1eee80660abdb28d4075226e81d237b73f4ce/geometry/optimization/test/cartesian_product_test.cc#L132)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Tests only the case unbounded x bounded. Can you add a simple one that tests unbounded x unbounded and bounded x unbounded to ensure order doesn't matter.
</blockquote></details>

Done.
___
*[`geometry/optimization/test/cartesian_product_test.cc` line 137 at r2](https://reviewable.io/reviews/robotlocomotion/drake/18140#-NEuCFYq5GPT7jlhApYM:-NEvJ0Tx7Ott5oKtx3-d:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/08b1eee80660abdb28d4075226e81d237b73f4ce/geometry/optimization/test/cartesian_product_test.cc#L137)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Should this be testing PointInSet? I think it belongs in a different test.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NEvgl8k84MjFhhOFcR2:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @mpetersen94)

**Review by mpetersen94 — COMMENTED** [review]
+@ggould-tri for platform review on Monday per rotation.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NEwQy5S4orlolt3NH6Z:b-t39jy6)* status: LGTM missing from assignee ggould-tri(platform), missing label for release notes (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; one minor comment/wording note.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NF9VoTr2S0H2phPf82E:bi24jwp)* status: 1 unresolved discussion, missing label for release notes (waiting on @mpetersen94)

___
*[`geometry/optimization/test/cartesian_product_test.cc` line 131 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18140#-NF9TZ31-FzkwIyc2AeK:-NF9TZ31-FzkwIyc2AeL:b-8nhxsn) ([raw file](https://github.com/robotlocomotion/drake/blob/38a07e2f5827f266ba5b8a17eb2f725bb0f60f8e/geometry/optimization/test/cartesian_product_test.cc#L131)):*
> ```cpp
>   const HPolyhedron H(A, Vector2d(0, 2));
> 
>   const CartesianProduct S(P, H);
> ```

minor:  The semantics under test would be clearer if you commented each stanza here (e.g. "Bounded x Unbounded -> Unbounded") or named the variables for their significance to the test (e.g. `P` -> `bounded_space`, `H` -> `unbounded_space`).

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140)* status: missing label for release notes (waiting on @AlexandreAmice and @ggould-tri)

___
*[`geometry/optimization/test/cartesian_product_test.cc` line 131 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18140#-NF9TZ31-FzkwIyc2AeK:-NF9ovu9ATc-H-_7YAa6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/38a07e2f5827f266ba5b8a17eb2f725bb0f60f8e/geometry/optimization/test/cartesian_product_test.cc#L131)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  The semantics under test would be clearer if you commented each stanza here (e.g. "Bounded x Unbounded -> Unbounded") or named the variables for their significance to the test (e.g. `P` -> `bounded_space`, `H` -> `unbounded_space`).
</blockquote></details>

Done.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140)* status: missing label for release notes (waiting on @mpetersen94)

**Review by ggould-tri — COMMENTED** [review]
+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18140#-:-NFACFWY0BHqn3mGv1dt:b-chsgxs)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),AlexandreAmice (waiting on @mpetersen94)

**Pull request merged**
