### PR TITLE
Add a new PR size policy.

### PR DESCRIPTION
**Pull request by david-german-tri**
This is based on a consensus of platform reviewers on Slack, but needs approval from Russ.

+@sammy-tri for feature review (have I accurately captured the consensus?) and +@RussTedrake for platform review (do we have the green light to implement this rule?)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4734)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-Ka9wbrFfSVxW-JgySEY:bnfp4nl)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaA4PSUplwgBiyFuim2:bwczu5s) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
> ```reStructuredText
> A PR generally should not exceed 500 lines of code. Larger PRs are sometimes
> allowed, for instance if the change is generated by an easily-reviewed script.
> Before sending an oversize PR, check that your platform reviewer is willing to
> ```

BTW, consider replacing "platform reviewer is" with "reviewers are".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by SeanCurtis-TRI** [comment]
BTW We want to merge new features with a "minimal" set of tests?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaD8SuQXDjs5s341Ieh:byta0hz)*

**Comment by david-german-tri** [comment]
@seancurtis-tri Multiple parsings FTL!  Fixed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaDKzhETeByvAmCy5HM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, consider replacing "platform reviewer is" with "reviewers are".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaDKgOSjaFcRBOsIyqc:bs96has)*

**Comment by sherm1** [comment]
Per discussion in dynamics cave this morning: we should consider exempting comments from this limit -- otherwise we risk discouraging submitters from writing them! Also, let's consider explicitly exempting deletions -- I would be very happy to review a PR where someone deletes a multi-thousand line file and would like to encourage that.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaDbtjn4VNMsbudylR3:b-mfqg0m)*

**Comment by jwnimmer-tri** [comment]
The "checklist" text already excluded comment lines, so I guess "developers" on its own was unclear.  To me, excluding deleted lines from the count was implied, but writing it down is clearer too! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaDck2scGMjF0TS6Cr8:b-fj5ctm)*

**Comment by sammy-tri** [comment]
I think I vote for explicitly mentioning that deletion doesn't count against the PR's LOC limit.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaDejMTSh56q5Z6U5WY:bhrwvi2)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_review_checklist.rst, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaDfAHVo7Hd6_8S8E2P:-KaDfAHVo7Hd6_8S8E2Q:bjmpx94) ([raw file](https://github.com/robotlocomotion/drake/blob/224e74b831996aea4df298e9ccd73341b445a26f/drake/doc/code_review_checklist.rst#L23)):*
> ```reStructuredText
> =============================================
> 
> - If the PR exceeds 500 lines of code, excluding comments, divide it
> ```

This reads to me like a hard limit, but developers.rst reads like a soft limit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by RussTedrake** [comment]
apart from the one comment, :lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/code_review_checklist.rst, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaEVQWbwtoUWpFNihu0:-KaEVQWbwtoUWpFNihu1:b2rw833) ([raw file](https://github.com/robotlocomotion/drake/blob/224e74b831996aea4df298e9ccd73341b445a26f/drake/doc/code_review_checklist.rst#L27)):*
> ```reStructuredText
> 
>   - If you are modifying an API, consider deprecating the old interface instead
>     of migrating all call sites immediately.
> ```

Agreed we want to get there, but I think our decision was to not force this on people in the short term ("drake is under construction").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaEVnY_sLvnfu1p2YL2:b-tfbw4v)*

**Comment by david-german-tri** [comment]
Re comments and deletions - Done.

---

Review status: 0 of 108 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drake/doc/code_review_checklist.rst, line 23 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaDfAHVo7Hd6_8S8E2P:-KaIC8Z9EcTB3fQA4y38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/224e74b831996aea4df298e9ccd73341b445a26f/drake/doc/code_review_checklist.rst#L23)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This reads to me like a hard limit, but developers.rst reads like a soft limit.
</blockquote></details>

Done.

---

*[drake/doc/code_review_checklist.rst, line 27 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaEVQWbwtoUWpFNihu0:-KaIC8u_TjbIfuVHD5EO:bhj28l8) ([raw file](https://github.com/robotlocomotion/drake/blob/224e74b831996aea4df298e9ccd73341b445a26f/drake/doc/code_review_checklist.rst#L27)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Agreed we want to get there, but I think our decision was to not force this on people in the short term ("drake is under construction").
</blockquote></details>

Yes - This is just a recommended technique to reduce the size of a huge PR, not a requirement on all API changes.  Updated the text above to clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaIBFYogdw6H8Wkck08:b2tv8z5)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaIEL2Getakult0ix88:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaIkNWiIQfFPyItS6Oz:bnfp4nl)*

**Comment by sammy-tri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaIkpdIi26_R0Ld7Pw_:b-wcz65n) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaIljTt35Tqb0qayQfb:b-n7xva9) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

No change?
</blockquote></details>

Shows up for me.  Were you selecting an old diff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by liangfok** [comment]
*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaImKuen2bEDHb1dnXE:b-67fk1h) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Shows up for me.  Were you selecting an old diff?
</blockquote></details>

Oh, I was thinking about deleting the word "platform" since I assume the author should ideally also ask the "feature" reviewers whether they are willing to review a PR with > 500 lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/developers.rst, line 141 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-KaA4PSUplwgBiyFuim1:-KaJ-QSCgD7CdiRKXhOt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9465bf779a777127b8c1957d14a20f7a2b992c2a/drake/doc/developers.rst#L141)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

Oh, I was thinking about deleting the word "platform" since I assume the author should ideally also ask the "feature" reviewers whether they are willing to review a PR with > 500 lines.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4734#-:-KaJ-e_2n5f_YAVNyyUh:bnfp4nl)*

**Pull request merged**
