### PR TITLE
[Bazel] Add bullet

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I had been trying to make this conditional within RBT, but probably worth just getting it in unconditionally for now at least.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4394)

### CODE REVIEW

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/BUILD, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-KYLN0GH-PXT7k_l7KVT:-KYLN0GI8CxKLWz-XBkz:b-wz9qyr) ([raw file](https://github.com/robotlocomotion/drake/blob/ec152d62470276347a786b36537483d66f09c2b4/drake/multibody/BUILD#L175)):*
> ```Python
> )
> 
> # TODO(jwnimmer-tri) This requires gmock.
> ```

BTW I'm pretty astonished to learn `gmock` is available in the CMake build.  (#3133)

---

*[drake/multibody/collision/BUILD, line 63 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-KYLOaQ4AnQcLnEk7ZAc:-KYLOaQ4CCicOHeHE7PK:b-i5ci81) ([raw file](https://github.com/robotlocomotion/drake/blob/ec152d62470276347a786b36537483d66f09c2b4/drake/multibody/collision/BUILD#L63)):*
> ```Python
> # By default, supply a bullet-only model.  As we gain more collision library
> # choices, we may want to be more subtle here.
> alias(
> ```

BTW I didn't know about this feature!  Nice.

---

*[tools/bullet.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-KYLOKra-ej9mPiRvvV1:-KYLOKraDj9wEymMDmSF:bpict1h) ([raw file](https://github.com/robotlocomotion/drake/blob/ec152d62470276347a786b36537483d66f09c2b4/tools/bullet.BUILD#L3)):*
> ```
> # -*- python -*-
> 
> cc_library(
> ```

BTW - this is only a subset of bullet, right?  If so, consider a comment to that effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-:-KYLOdBcDq9661nF_bLk:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 2 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4394)*

**Comment by david-german-tri** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4394)*

**Comment by jwnimmer-tri** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/BUILD, line 175 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-KYLN0GH-PXT7k_l7KVT:-KYLs5OcARk5SAxLnoh0:b7iwc8m) ([raw file](https://github.com/robotlocomotion/drake/blob/ec152d62470276347a786b36537483d66f09c2b4/drake/multibody/BUILD#L175)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW I'm pretty astonished to learn `gmock` is available in the CMake build.  (#3133)
</blockquote></details>

:facepalm:

Done.

---

*[tools/bullet.BUILD, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-KYLOKra-ej9mPiRvvV1:-KYLrLsu5JszGz1r3ELk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/ec152d62470276347a786b36537483d66f09c2b4/tools/bullet.BUILD#L3)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW - this is only a subset of bullet, right?  If so, consider a comment to that effect.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4394)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4394#-:-KYOm3fZC-_f_m3zHeKt:bnfp4nl)*

**Pull request merged**
