### PR TITLE
[py common] Add use_native_cpp_logging feature

### LINKED ISSUE #19680: [pydrake] Disable spdlog redirection when using multithreaded C++ code?
**Is your feature request related to a problem? Please describe.**
I am writing Python bindings in a downstream project (Anzu) that does work in a multithreaded fashion, and calls `drake::log()->info()`, `->debug()`, `->trace()`, etc., in those separate threads.

Even though this code doesn't explicitly call Python code in those other threads (e.g. not via `std::function<>` or C++ <-> Python polymorphism), it still seemed to deadlock.

If I commented out this line, my multithreaded code seemed to work fine:
https://github.com/RobotLocomotion/drake/blob/b9813a712454580cd6bc0724f8d2506d85412e58/bindings/pydrake/common/module_py.cc#L103

**Describe the solution you'd like**
Perhaps an environment variable, like `PYDRAKE_NO_SPDLOG_REDIRECT`, or a function to call from pydrake that undoes the effects of `MaybeRedirectPythonLogging()` and related methods.

**Describe alternatives you've considered**
(1) Writing a C++ pybind11 module as follows, then importing it before `pydrake`, fixes the "seems to deadlock" issue:
https://gist.github.com/EricCousineau-TRI/ff52a8e3be0ca5fd085307c16ff09dbc

(2) Set spdlog's debugging level such that no messages are printed

(3) Add an option to only redirect to Python if it's the main thread. If it isn't the main thread, it should ideally emit directly to `stderr` as the nominal sink would.

**Additional context**
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1687807563590549

\cc @jwnimmer-tri @dmcconachie-tri @sammy-tri

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19695.  Closes #19680. Relates #19685.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/text_logging_threading_test.py` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-N_j3ZKLBhlCX9OiZT7m:-N_j3ZKN74Ncs2XllwqY:b-9d4aak) ([raw file](https://github.com/RobotLocomotion/drake/blob/f43bc5e5d9879d8b239dd1c51575bec3e7faad1d/bindings/pydrake/common/test/text_logging_threading_test.py#L8)):*
> ```Python
> from pydrake.common.test.text_logging_test_helpers import do_log_test
> 
> # With this commented out, the test should fail (block).
> ```

@EricCousineau-TRI I tried to create a repro test case for  your bug report, but I was unable to make it deadlock.

Could you help point me in the right direction to reproduce the deadlock?

My best guess is shown below.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/text_logging_threading_test.py` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-N_j3ZKLBhlCX9OiZT7m:-NaIwTMHBpZqpJOUyntE:b-1dt2js) ([raw file](https://github.com/RobotLocomotion/drake/blob/f43bc5e5d9879d8b239dd1c51575bec3e7faad1d/bindings/pydrake/common/test/text_logging_threading_test.py#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@EricCousineau-TRI I tried to create a repro test case for  your bug report, but I was unable to make it deadlock.

Could you help point me in the right direction to reproduce the deadlock?

My best guess is shown below.
</blockquote></details>

Working: Trying it out now.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/text_logging_threading_test.py` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-N_j3ZKLBhlCX9OiZT7m:-NaIxfvg4KnEvlsi9963:b-hhjmg4) ([raw file](https://github.com/RobotLocomotion/drake/blob/f43bc5e5d9879d8b239dd1c51575bec3e7faad1d/bindings/pydrake/common/test/text_logging_threading_test.py#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Trying it out now.
</blockquote></details>

Ah, sorry, you said it failed to deadlock, missed that.

I've commented in Anzu PR 10614, but restating my best guess of the sequence of events:
- We call something like `MoveRobotAsync(...)` causes GIL to still be actively held (default binding behavior, I believe)
- In a separate thread, the executing method calls `drake::log()->info(...)`
- Due to the redirect, this logging call tries to acquire the GIL that is already held, thus is in a deadlock

So the solutions in this case are:
(1) Not do redirect (as we are doing now)
(2) Tell our Python bindings to release the GIL in those bindings of interest

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers, labeled "do not merge" (waiting on @jwnimmer-tri)

___
*[`bindings/pydrake/common/test/text_logging_threading_test.py` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-N_j3ZKLBhlCX9OiZT7m:-NaN1G2_9F1kJfcOC2C1:b-qo9r8f) ([raw file](https://github.com/RobotLocomotion/drake/blob/f43bc5e5d9879d8b239dd1c51575bec3e7faad1d/bindings/pydrake/common/test/text_logging_threading_test.py#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry, you said it failed to deadlock, missed that.

I've commented in Anzu PR 10614, but restating my best guess of the sequence of events:
- We call something like `MoveRobotAsync(...)` causes GIL to still be actively held (default binding behavior, I believe)
- In a separate thread, the executing method calls `drake::log()->info(...)`
- Due to the redirect, this logging call tries to acquire the GIL that is already held, thus is in a deadlock

So the solutions in this case are:
(1) Not do redirect (as we are doing now)
(2) Tell our Python bindings to release the GIL in those bindings of interest
</blockquote></details>

Ah.  It sounds like the key difference that I didn't capture is that the C++ code itself launches multiple worker threads (while holding the GIL).  I think I should be able to adjust this test to try that.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: with questions about `set_log_level` and `py::call_guard<py::gil_scoped_release>()`.

> Reviewed 5 of 5 files at r1, 3 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-:-NaNczUG2jFLsu-2Zycx:bqpjxly)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/__init__.py` line 10 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNc85K74JiiaX912AP:-NaNc85L9xGAoMt3qcay:b-7utg76) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/__init__.py#L10)):*
> ```Python
> 
> from ._module_py import *
> from ._module_py import _set_log_level, _use_native_cpp_logging
> ```

nit As a user debugging things, when using `use_native_cpp_logging()`, I find that I may still want to adjust logging levels.

In an Anzu dev branch, I ended up calling `pydrake.common._set_log_level` directly, which is admittedly fragile.
Is it possible to expose this function publicly, say `set_native_cpp_log_level`, and have it fail fast if _drake_loggger._tied_to_spdlog` is true?
___
*[`bindings/pydrake/common/test/text_logging_test_helpers_py.cc` line 76 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNcewu9CmAApZZn4G3:-NaNcewu9CmAApZZn4G4:b33n5pl) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/test/text_logging_test_helpers_py.cc#L76)):*
> ```cpp
> 
>   m.def("do_log_test", &do_log_test);
>   m.def("do_log_test_async", &do_log_test_async);
> ```

nit Per above, the alternative solution is to decorate each and every C++ entry point with possible multi-threaded logging with `py::call_guard<py::gil_scoped_release>()` (or something equivalent).

It may be useful to illustrate / test here. I've made an (somewhat messy) attempt here:
https://github.com/jwnimmer-tri/drake/pull/12

FTR, I prefer `use_native_cpp_logging()` as it is less to reason about, but it may be good to be aware of / test the workflow with a GIL release.
___
*[`bindings/pydrake/common/test/text_logging_threading_test.py` line 8 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-N_j3ZKLBhlCX9OiZT7m:-NaNcc8U8wgEoDL6HbDl:b556ppi) ([raw file](https://github.com/RobotLocomotion/drake/blob/f43bc5e5d9879d8b239dd1c51575bec3e7faad1d/bindings/pydrake/common/test/text_logging_threading_test.py#L8)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

The new test case isn't as complicated as that example, but I think it sufficiently covers the use case.
</blockquote></details>

Awesome, thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/__init__.py` line 10 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNc85K74JiiaX912AP:-NaNeW7vBR2wtDgvDFB_:b202887) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/__init__.py#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit As a user debugging things, when using `use_native_cpp_logging()`, I find that I may still want to adjust logging levels.

In an Anzu dev branch, I ended up calling `pydrake.common._set_log_level` directly, which is admittedly fragile.
Is it possible to expose this function publicly, say `set_native_cpp_log_level`, and have it fail fast if _drake_loggger._tied_to_spdlog` is true?
</blockquote></details>

Alternatively, perhaps the suggested route is to configure the logging level before calling `use_native_cpp_logging()`.
Then users can use existing public interfaces? e.g.
```
logging.getLogger("drake").setLevel(logging.TRACE)
use_native_cpp_logging()
# Restore Python logging.
logging.getLogger("drake").setLevel(logging.INFO)
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: needs at least two assigned reviewers

___
*[`bindings/pydrake/common/__init__.py` line 10 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNc85K74JiiaX912AP:-NaNhJAN0ASrahjF0_lX:b-e8n9vo) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/__init__.py#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Alternatively, perhaps the suggested route is to configure the logging level before calling `use_native_cpp_logging()`.
Then users can use existing public interfaces? e.g.
```
logging.getLogger("drake").setLevel(logging.TRACE)
use_native_cpp_logging()
# Restore Python logging.
logging.getLogger("drake").setLevel(logging.INFO)
```
</blockquote></details>

I don't think we should offer public pydrake API to configure spdlog.

(1) It's not terribly valuable.  Users in the `use_native_cpp_logging()` camp are already doing their own custom witchcraft, so it shouldn't be too much of a lift for them to write and bind whatever C++ log configuration code they want.

(2) It's somewhat costly.  Coupling the spdlog API choices through into a public pydrake API will be an extra compatibility burden as spdlog evolves and we need to figure out how to keep the sugar intact and well-tested.
___
*[`bindings/pydrake/common/test/text_logging_test_helpers_py.cc` line 76 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNcewu9CmAApZZn4G3:-NaO2W1H0y95sY66NUk2:b-gnqcmv) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/test/text_logging_test_helpers_py.cc#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Per above, the alternative solution is to decorate each and every C++ entry point with possible multi-threaded logging with `py::call_guard<py::gil_scoped_release>()` (or something equivalent).

It may be useful to illustrate / test here. I've made an (somewhat messy) attempt here:
https://github.com/jwnimmer-tri/drake/pull/12

FTR, I prefer `use_native_cpp_logging()` as it is less to reason about, but it may be good to be aware of / test the workflow with a GIL release.
</blockquote></details>

Done.

I added the demo, but as a separate program for utmost clarity.  (The old test has been renamed to `threading1`, with some comment improvements, but Reviewable didn't notice that.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 2 unresolved discussions, needs at least two assigned reviewers

___
*[`bindings/pydrake/common/__init__.py` line 10 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNc85K74JiiaX912AP:-NaOBbjREuaAR41Xok4V:b-ba7jcz) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/__init__.py#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think we should offer public pydrake API to configure spdlog.

(1) It's not terribly valuable.  Users in the `use_native_cpp_logging()` camp are already doing their own custom witchcraft, so it shouldn't be too much of a lift for them to write and bind whatever C++ log configuration code they want.

(2) It's somewhat costly.  Coupling the spdlog API choices through into a public pydrake API will be an extra compatibility burden as spdlog evolves and we need to figure out how to keep the sugar intact and well-tested.
</blockquote></details>

Sounds good to me.
___
*[`bindings/pydrake/common/test/text_logging_test_helpers_py.cc` line 76 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaNcewu9CmAApZZn4G3:-NaOBxAuCn-XzIyritvn:bru5xav) ([raw file](https://github.com/RobotLocomotion/drake/blob/09982315a1a7b612c028055c532407a31b3bb59e/bindings/pydrake/common/test/text_logging_test_helpers_py.cc#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.

I added the demo, but as a separate program for utmost clarity.  (The old test has been renamed to `threading1`, with some comment improvements, but Reviewable didn't notice that.)
</blockquote></details>

Sweet, thanks. Just some small follow-up nits on the usage of `1, 2` vs. something more descriptive.
___
*[`bindings/pydrake/common/test/text_logging_threading1_test.py` line 1 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaOBmpfCl24MtK9Hmxc:-NaOBmpfCl24MtK9Hmxd:b-k58gfz) ([raw file](https://github.com/RobotLocomotion/drake/blob/74ba41031d950ae7c80165fc128585b983756562/bindings/pydrake/common/test/text_logging_threading1_test.py#L1)):*
> ```Python
> import logging
> ```

nit Can the name of this test reflect its goal? e.g.
```
text_loging_threading_use_native_cpp_threading.py
```
___
*[`bindings/pydrake/common/test/text_logging_threading2_test.py` line 1 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NaOBs4w4Mqz957pWNyK:-NaOBs4w4Mqz957pWNyL:bputypn) ([raw file](https://github.com/RobotLocomotion/drake/blob/74ba41031d950ae7c80165fc128585b983756562/bindings/pydrake/common/test/text_logging_threading2_test.py#L1)):*
> ```Python
> import logging
> ```

nit Can the name of this test reflect its goal? e.g.
```
text_loging_threading_gil_release.py
```

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ggould-tri for platform review, please!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-:-NaOC5reChlg1IHQyMHE:bcav8qn)* status: 2 unresolved discussions, LGTM missing from assignee ggould-tri(platform)

**Comment by EricCousineau-TRI** [comment]
\cc @dmcconachie-tri for better insight + alternatives for the GIL deadlock problem

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: LGTM missing from assignee ggould-tri(platform)

**Review by ggould-tri — COMMENTED** [review]
:lgtm_strong: ; minor notes.

> Reviewed 5 of 5 files at r1, 3 of 5 files at r2, 2 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-:-Nah-jqVBncPcRtFL9eQ:bru7ff4)* status: 2 unresolved discussions

___
*[`bindings/pydrake/common/__init__.py` line 111 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NagzRlF49nUWyVEeNvl:-NagzRlF49nUWyVEeNvm:begolmg) ([raw file](https://github.com/RobotLocomotion/drake/blob/86fce938723fce12a626c988db78b271c163b0b1/bindings/pydrake/common/__init__.py#L111)):*
> ```Python
> 
>     After this function has been called, pydrake's C++ code will log directly
>     to stderr, with no interaction with Python. (The Python settings for log
> ```

nit, super-picky:  "Directly" is misleading, as the logging still goes via spdlog and respects any C++ actions subsequently done to spdlog (e.g., level reconfiguration, or if we ever bring the `text_log_lcm_bridge` over).



_Suggestion:_
```Python
    After this function has been called, pydrake's C++ code will log
    to stderr, with no interaction with Python. (The Python settings for log
```
___
*[`bindings/pydrake/common/text_logging_pybind.h` line 14 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-Nah0_Zg8rfS7ZFirbiS:-Nah0_Zg8rfS7ZFirbiT:b-f3lvc9) ([raw file](https://github.com/RobotLocomotion/drake/blob/86fce938723fce12a626c988db78b271c163b0b1/bindings/pydrake/common/text_logging_pybind.h#L14)):*
> ```objc
> /* Implements pydrake.common.use_native_cpp_logging(). This function is not
> thread-safe; no other threads should be running when it is called. */
> void UseNativeCppLogging();
> ```

minor:  It's odd that one of these functions is named with "maybe" and the other isn't, given that they have nearly exactly identical precondition checks and warn-and-nop failure behaviour.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19703)* status: 1 unresolved discussion

___
*[`bindings/pydrake/common/__init__.py` line 111 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-NagzRlF49nUWyVEeNvl:-NahI6Y4CePfp5oHGC9V:b-dtdau6) ([raw file](https://github.com/RobotLocomotion/drake/blob/86fce938723fce12a626c988db78b271c163b0b1/bindings/pydrake/common/__init__.py#L111)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit, super-picky:  "Directly" is misleading, as the logging still goes via spdlog and respects any C++ actions subsequently done to spdlog (e.g., level reconfiguration, or if we ever bring the `text_log_lcm_bridge` over).
</blockquote></details>

The text is correct insofar as "after" means "immediately after".  If someone comes by later and further changes things, that's their own fault -- for all we know, they could disable all logging entirely or send it to a file instead of stderr, so that "to stderr" on its own is no longer true.  I don't think we need to anticipate those kind of changes in the text here.
___
*[`bindings/pydrake/common/text_logging_pybind.h` line 14 at r6](https://reviewable.io/reviews/RobotLocomotion/drake/19703#-Nah0_Zg8rfS7ZFirbiS:-NahIXhQ4e9LmWlDurdZ:bo00lnu) ([raw file](https://github.com/RobotLocomotion/drake/blob/86fce938723fce12a626c988db78b271c163b0b1/bindings/pydrake/common/text_logging_pybind.h#L14)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  It's odd that one of these functions is named with "maybe" and the other isn't, given that they have nearly exactly identical precondition checks and warn-and-nop failure behaviour.
</blockquote></details>

Their behavior is not the same.  In case of any error, the "Maybe" function will give up (do nothing and return early), but the non-"Maybe" function will throw an exception.  To my ear, that's exactly what "Maybe" always means in a function -- it's allowed to fail without throwing.

**Pull request merged**
