### PR TITLE
[workspace] fix drake-visualizer for system jchart2d

### PR DESCRIPTION
**Pull request by svenevs**
Remnant of #16185.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: provided CI for bionic passes, I have verified locally on focal that the new archive extracts and runs as expected.

+@BetsyMcPhail for feature review please.  We are electing to fix rpath things related to directory / vtk8 for apt stuff in the packaging script (since internally and installed drake does not need it).  As such, I want to fix this now before I forget about it again.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884#-:-MzMFofM6JjNfl75Tcwq:bve95kk)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

___
*[tools/workspace/drake_visualizer/repository.bzl, line 46 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16884#-MzMG1eh6EWKJm6I6L7P:-MzMG1eh6EWKJm6I6L7Q:b41cfox) ([raw file](https://github.com/robotlocomotion/drake/blob/ab903118dc7288bf3de046e76f1bd01712471aba/tools/workspace/drake_visualizer/repository.bzl#L46)):*
> ```Starlark
>     elif os_result.ubuntu_release == "18.04":
>         archive = "dv-0.1.0-406-g4c3e570a-python-3.6.9-qt-5.9.5-vtk-8.2.0-bionic-x86_64-3.tar.gz"  # noqa
>         sha256 = "634e208ca23edf8b8e3a6dfed06ff5dff0265b615db9762a2fef815c45fd2e72"  # noqa
> ```

FYI the archives are already uploaded to S3 so CI passing indicates it downloads and builds as expected.
___
*[tools/workspace/drake_visualizer/image/build-lcm.sh, line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16884#-MzMGBhqBNJdqu7RBlPh:-MzMGBhqBNJdqu7RBlPi:b-2i9hdq) ([raw file](https://github.com/robotlocomotion/drake/blob/cd72eaf29514846a1304aeada6ec1cfb92a7ea2d/tools/workspace/drake_visualizer/image/build-lcm.sh#L35)):*
> ```Shell
>     --linkopt=-Wl,-z,now \
>     --linkopt=-Wl,-z,relro \
>     //tools/workspace/net_sf_jchart2d:install -- /opt/drake
> ```

FYI this is the main need for the change, this target no longer exists.  Low priority because it does not _appear_ to be the case that anything runs differently with or without this fix.

**Review by svenevs — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884)* status: LGTM missing from assignee BetsyMcPhail, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm: assuming CI passes

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884#-:-MzMM19cEjnu2z3Kqjz_:bat8f8x)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@sammy-tri for platform review please.  If you do not have availability today this can easily wait until next week :+1:  This is a minor fixup to use the system jchart2d in the `drake_visualizer` builds (followup to #16185), PR passes CI indicating the new tarballs build with drake and `bazel run //tools:drake_visualizer` runs fine locally but this does not appear to be a necessary fix for drake (rather, cosmetic, making sure the `drake_visualizer` tarballs continue to be buildable).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884#-:-MzQ1zuDAE5aKt3DxgUN:b-t48fru)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
Availability today is indeed limited, but will try to get to this soon.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884#-:-MzRN9zs1vtTh2nSNu8j:bg0jmb5)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16884#-:-MzRewpo1e1kwmhhI-ab:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees sammy-tri(platform),BetsyMcPhail (waiting on @svenevs)

**Pull request merged**
