### PR TITLE
update IRIS version to remove swig, mex, and pods dependencies

### LINKED ISSUE #2797: Mysterious CI Flake - gcc-linux-matlab - fatal error: setoper.h: No such file or directory
# The Error

```
05:09:16 make[9]: Entering directory `/home/ubuntu/workspace/experimental/06107e1d/externals/iris/pod-build/iris_project-prefix/src/iris_project-build'
05:09:16 [  2%] Building C object CMakeFilIn file included from /home/ubuntu/workspace/experimental/06107e1d/externals/iris/iris/src/geometry.cpp:5:0:
05:09:16 /home/ubuntu/workspace/experimental/06107e1d/externals/iris/iris/src/iris_cdd.cpp:2:21: fatal error: setoper.h: No such file or directory
05:09:16  #include "setoper.h"
05:09:16                      ^
05:09:16 compilation terminated.
```
# Example Logs
- https://drake-jenkins.csail.mit.edu/job/experimental/2658/compiler=gcc,label=linux_matlab/consoleFull

### LINKED ISSUE #4914: Mac builds with Matlab failing in compile of Iris
Starting two nights ago, but masked by other build failures yesterday, all mac builds with matlab began failing during the compilation of the `iris` external.

Example failures: https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=331321
Relevant commits listed here: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-clang-nightly-matlab-debug/172/

Typical errors are:
...`iris_wrapperPYTHON_wrap.cxx:4793:12: error: explicit specialization of non-template struct 'traits_reserve'`
`cddlp.c:2954:109: warning: data argument not used by format string [-Wformat-extra-args]
    if (localdebug) printf("No interior-point is found and thus the standard LP technique will be used.\n", ired);`
`cddio.c:1948:16: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]`
`cddlib.c:116:59: warning: for loop has empty body [-Wempty-body]
      for (itemp=1; cone->OrderVector[itemp]!=hh; itemp++);`
`cddlp.c:2954:109: warning: data argument not used by format string [-Wformat-extra-args]
    if (localdebug) printf("No interior-point is found and thus the standard LP technique will be used.\n", ired);`
`cddio.c:1948:16: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]`
`cddlib.c:116:59: warning: for loop has empty body [-Wempty-body]
      for (itemp=1; cone->OrderVector[itemp]!=hh; itemp++);`
`cddlp_f.c:2955:109: warning: data argument not used by format string [-Wformat-extra-args]
    if (localdebug) printf("No interior-point is found and thus the standard LP technique will be used.\n", ired);`
`cddio_f.c:1949:16: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]`
`cddlib_f.c:117:59: warning: for loop has empty body [-Wempty-body]
      for (itemp=1; cone->OrderVector[itemp]!=hh; itemp++);`

### PR DESCRIPTION
**Pull request by rdeits**
This updates to the latest IRIS master, which uses pybind11 instead of SWIG and which does not build any Matlab mex files or use any of the Pods architecture. 

This *should* preserve IRIS compatibility with Drake, since the Matlab functions still work (they just no longer have mex-ed speedups). However, there's one significant change: Previously, IRIS (like all our other Matlab tools) installed an `addpath_iris.m` file which drake's `checkDependency` would call to mutate the global path and add the IRIS folders. Now, instead, IRIS's install step just copies its Matlab package to `install/matlab`. This is how all of our Python tools work, and it makes the IRIS build and its integration with drake vastly easier. This does, however, mean that it's possible that a user who tries to edit IRIS could end up editing the installed copy rather than the source. But I don't think that's worth the cost of having a custom Pods build system to generate the `addpath_iris.m` logic and the awkwardness of activating packages by mutating global state. Especially since no one has edited any IRIS matlab file in two years or more :wink: 

Fixes #4914 
I believe this also fixes #2797

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4944)

### CODE REVIEW

**Comment by rdeits** [comment]
+@jamiesnape for feature review, +@ggould-tri for platform review

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-:-KbWix_6K62T8NxS1UxE:b5zsydl)*

**Comment by david-german-tri** [comment]
> This does, however, mean that it's possible that a user who tries to edit IRIS could end up editing the installed copy rather than the source. But I don't think that's worth the cost of having a custom Pods build system to generate the addpath_iris.m logic and the awkwardness of activating packages by mutating global state.

:+1: Keeping MATLAB build products in-source has never sat well with me anyway.

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-KbWkus-7ylNsVNA9ty6:-KbWkus-7ylNsVNA9ty7:b-yjkog7) ([raw file](https://github.com/robotlocomotion/drake/blob/59e7ac321a925a5dcbaf1f262f42db12883bdc2d/CMakeLists.txt#L209)):*
> ```CMake
>     -DIRIS_WITH_EIGEN=OFF
>     -DIRIS_WITH_MOSEK=OFF
>     -DIRIS_WITH_MATLAB=${Matlab_FOUND}
> ```

Alphabetize. Do you need `-DIRIS_WITH_PYBIND11=OFF`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Comment by rdeits** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-KbWkus-7ylNsVNA9ty6:-KbWlR2CI-yr6kPNIcu2:b8c0uvm) ([raw file](https://github.com/robotlocomotion/drake/blob/59e7ac321a925a5dcbaf1f262f42db12883bdc2d/CMakeLists.txt#L209)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Alphabetize. Do you need `-DIRIS_WITH_PYBIND11=OFF`?
</blockquote></details>

Good point, thanks. I'll verify that it works with that flag turned off. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Comment by rdeits** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 209 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-KbWkus-7ylNsVNA9ty6:-KbWlzkSqPkEF_G6EQV4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/59e7ac321a925a5dcbaf1f262f42db12883bdc2d/CMakeLists.txt#L209)):*
<details><summary><i>Previously, rdeits (Robin Deits) wrote…</i></summary><blockquote>

Good point, thanks. I'll verify that it works with that flag turned off. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-:-KbWmumJkQNi6z9bp_aY:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944#-:-KbWo0xIPfCq_HXDx9tr:bnfp4nl)*

**Comment by rdeits** [comment]
Erk. Somehow the `linux-gcc-experimental-matlab` machine isn't finding the Python headers? I'm not sure what's going on there yet.

**Comment by jamiesnape** [comment]
That is actually the only job that builds IRIS. I am planning to have the others building IRIS, but I do not want to risk breaking anything on a Friday afternoon.

**Comment by jamiesnape** [comment]
```
-- Found PythonInterp: /usr/bin/python3.4 (found version "3.4.3") 
-- Found PythonLibs: python3.4m
```

**Comment by rdeits** [comment]
Ok, makes sense. That's definitely a bug in the IRIS build, then. I'll keep investigating.

**Comment by rdeits** [comment]
Oh, well, that's a problem.

**Comment by jamiesnape** [comment]
IRIS will need to pass the values of `PYTHON_EXECUTABLE`, `PYTHON_INCLUDE_DIR`, and `PYTHON_LIBRARY` down through its superbuild.

**Comment by rdeits** [comment]
I *think* we can just pass the PYBIND11_PYTHON_VERSION down to IRIS, since we let pybind11 do the work of finding that python version. Would it be better to pass those flags down as well?

**Comment by jamiesnape** [comment]
That would guarantee you got at least that version.

**Comment by jamiesnape** [comment]
https://github.com/pybind/pybind11/blob/master/tools/pybind11Tools.cmake#L16

**Comment by rdeits** [comment]
Ok. IRIS will need to be updated to pass those flags properly within its own build.

**Comment by rdeits** [comment]
https://github.com/rdeits/iris-distro/pull/53

**Comment by jamiesnape** [comment]
Looks good.

**Comment by rdeits** [comment]
Somehow cmake is finding the python2.7 library, but thinks it's found version 1.4? 

```
CMake Error at /usr/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "2.7" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
```

**Comment by rdeits** [comment]
I see... CMake return a nonexistent python 1.4 version when it can't find python: https://github.com/Kitware/CMake/blob/master/Modules/FindPythonInterp.cmake#L138

So, somehow passing in the PYTHON_EXECUTABLE and other flags is causing cmake not to find python at all.

**Comment by jamiesnape** [comment]
Strange. I will try this PR out locally.

**Comment by ggould-tri** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Comment by jamiesnape** [comment]
Replace the `WITH_SWIG_MATLAB` here:
https://github.com/rdeits/drake/blob/b8a4c60786bdb781e35a7b4598110febbf438e47/cmake/options.cmake#L350-L352

**Comment by jamiesnape** [comment]
Also try not passing down `PYBIND11_PYTHON_VERSION`. It is redundant if you pass down all the other python variables.

**Comment by jamiesnape** [comment]
The `-DPYTHON_EXECUTABLE=${PYTHON_INCLUDE_DIR|PYTHON_LIBRARY}` in IRIS is the ultimate problem, but also do the above.

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Comment by rdeits** [comment]
Thanks @jamiesnape 

Just waiting on https://github.com/rdeits/iris-distro/pull/54 so I can update the SHA in this PR

**Comment by rdeits** [comment]
Ok, let's see how it goes.

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4944)*

**Pull request merged**
