### PR TITLE
[geometry/optimization] Enable adding costs to vertices in GraphOfConvexSets

### PR DESCRIPTION
**Pull request by mpetersen94**
Resolves a previous TODO and lays the ground work to make the implementation of the GCS planner cleaner.

cc @TobiaMarcucci

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@RussTedrake for feature review please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844#-:-NBJGWRP8caS6r_IJQ0d:b-ez1mbz)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake)

**Review by RussTedrake — COMMENTED** [review]
Awesome!  And beautifully implemented.  :lgtm: (apart from two nits and the CI code style failure)

+@xuchenhan-tri for platform review, please.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844#-:-NBMQUbp7NwEfX6vFIta:b-l3jri4)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @mpetersen94 and @xuchenhan-tri)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBMNg6QDSvEj9AiLguR:-NBMNg6QDSvEj9AiLguS:bgv1uu6) ([raw file](https://github.com/robotlocomotion/drake/blob/b4862aca85f4605126c852b94e5e02c2db6863a5/geometry/optimization/graph_of_convex_sets.h#L118)):*
> ```objc
>     costs are eventually implemented with a slack variable and a constraint:
>     @verbatim
>     min g(x) ⇒ min ℓ, s.t. ℓ ≥ g(x)
> ```

nit: should the methods then also return the constraint?

update: now I see in the implementation that it would be hard to do.  Please instead clarify that the cost which is returned is g(x), not ell.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 531 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBMONGH3vkbY9Jntklm:-NBMONGH3vkbY9Jntkln:b-4ly8m4) ([raw file](https://github.com/robotlocomotion/drake/blob/b4862aca85f4605126c852b94e5e02c2db6863a5/geometry/optimization/graph_of_convex_sets.h#L531)):*
> ```objc
>   // Adds a perspective constraint to the mathematical program to upper bound
>   // the cost below a slack variable. `vars` consists of the slack variable ℓ, ϕ
>   // and ϕ times the variables in the original cost.
> ```

nit: the statement about `vars` is confusing to me (here and below).  i know this is only a private method, but perhaps a one line example below (like you did for the AddCost method, etc, above would clarify it?

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)* status: LGTM missing from assignee xuchenhan-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @RussTedrake and @xuchenhan-tri)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBMNg6QDSvEj9AiLguR:-NBO2P6IAsJ1CNoSXYvO:b-qekkk4) ([raw file](https://github.com/robotlocomotion/drake/blob/b4862aca85f4605126c852b94e5e02c2db6863a5/geometry/optimization/graph_of_convex_sets.h#L118)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: should the methods then also return the constraint?

update: now I see in the implementation that it would be hard to do.  Please instead clarify that the cost which is returned is g(x), not ell.
</blockquote></details>

Done. Updated the edge version of AddCost to address the same issue.
___
*[`geometry/optimization/graph_of_convex_sets.h` line 531 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBMONGH3vkbY9Jntklm:-NBO74M84SDweOVeRT2b:b-ns008o) ([raw file](https://github.com/robotlocomotion/drake/blob/b4862aca85f4605126c852b94e5e02c2db6863a5/geometry/optimization/graph_of_convex_sets.h#L531)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit: the statement about `vars` is confusing to me (here and below).  i know this is only a private method, but perhaps a one line example below (like you did for the AddCost method, etc, above would clarify it?
</blockquote></details>

Done. PTAL

**Review by xuchenhan-tri — COMMENTED** [review]
+(release notes: feature)
platform :lgtm: with two nits.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844#-:-NBOMgpqDvZSF8eyxKCJ:b5vlr08)* status: 2 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 540 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOJcMT7rAk6DsH1v84:-NBOJcMUBEaO0ieM6qB6:b-8rjpn5) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.h#L540)):*
> ```objc
> 
>   // Adds a perspective version of the constraint to the mathematical program.
>   // Specifically given a constraint h(x) ≤ b, this method implement its
> ```

typo s/implement/implements
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOMUid4_DqWrajYjc1:-NBOMUieBH-4dfz88Sai:b-4drxn7) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.cc#L651)):*
> ```cpp
>       relaxed_phi.emplace(edge_id, phi);
>     } else {
>       phi = e->phi_;
> ```

nit kcov shows no test coverage here. Would it be hard to add?

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/graph_of_convex_sets.h` line 540 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOJcMT7rAk6DsH1v84:-NBOZDB28QUULiMcTe_E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.h#L540)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo s/implement/implements
</blockquote></details>

Done.
___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOMUid4_DqWrajYjc1:-NBO_40_0IQiORxitPYh:bfcw4kd) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.cc#L651)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit kcov shows no test coverage here. Would it be hard to add?
</blockquote></details>

Done I think?

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @mpetersen94)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOMUid4_DqWrajYjc1:-NBOs6ur57lz9NEXae-s:bc5ohqk) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.cc#L651)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Done I think?
</blockquote></details>

This code path isn't exercised unless `options.convex_relaxation` is `false`.

https://drake.mit.edu/bazel.html bottom of this page documents to run kcov locally in case it helps.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @xuchenhan-tri)

___
*[`geometry/optimization/graph_of_convex_sets.cc` line 651 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17844#-NBOMUid4_DqWrajYjc1:-NBT6cn36HpqtDrRr9a8:b-cfj0e1) ([raw file](https://github.com/robotlocomotion/drake/blob/a554854deecc73d266e59567562da333111feb1e/geometry/optimization/graph_of_convex_sets.cc#L651)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This code path isn't exercised unless `options.convex_relaxation` is `false`.

https://drake.mit.edu/bazel.html bottom of this page documents to run kcov locally in case it helps.
</blockquote></details>

Thanks! All new code is fully covered by tests.

**Review by mpetersen94 — COMMENTED** [review]
+(status: commits are properly curated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844#-:-NBT6tgG4nZQzzkgmeXp:b-qv2c28)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17844)* status: :shipit: complete! all discussions resolved, LGTM from assignees RussTedrake(platform),xuchenhan-tri(platform), base commit is latest master (waiting on @mpetersen94)

**Pull request merged**
