### PR TITLE
pydrake: Add bindings for AddLinearEqualityConstraint

### PR DESCRIPTION
**Pull request by mpetersen94**
Also adds binding for Eigen quaternion conjugate

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9293)

### CODE REVIEW

**Comment by mpetersen94** [comment]
@EricCousineau-TRI for feature review.  Also, Jenkins tests don't seem to be running.

**Comment by mpetersen94** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot ok to test

**Comment by mpetersen94** [comment]
@jamiesnape Has something happened recently that means I will need you (or someone else) to do this for future PR's? My previous PR's started Jenkins automatically.

**Comment by mpetersen94** [comment]
Would someone be able to merge this for me?

**Pull request merged**
