### PR TITLE
Disable opening windows at unit tests and remove "manual" tags

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7589)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
+@thduynguyen feature review please.
/cc @jamiesnape @jwnimmer-tri

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0BNKpjTOGvsipVMIwZ:bab0fd3)*

**Comment by kunimatsu-tri** [comment]
Relates: #7573

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0BOE8nkcJjOAbf5U4G:b-5e5wv2)*

**Comment by thduynguyen** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0G6ZomHL-wfuO9qBgC:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[systems/sensors/rgbd_camera_publish_lcm_example.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-L0G9rOVvMiM0C-bLifI:-L0G9rOVvMiM0C-bLifJ:buxrp57) ([raw file](https://github.com/robotlocomotion/drake/blob/403cb774107af85829e6f7a3c72b00c7c8bb4118/systems/sensors/rgbd_camera_publish_lcm_example.cc#L54)):*
> ```cpp
> DEFINE_bool(show_window, true,
>             "If true, RgbdCamera opens windows for displaying rendering "
>             "context.");
> ```

BTW  Why default to true? (In other tests, you have it default to false.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589)*

**Comment by kunimatsu-tri** [comment]
+@SeanCurtis-TRI for platform review please although you've been there already, thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0GA_LUHErpelrbshpk:b5ug7is)*

**Comment by kunimatsu-tri** [comment]
*[systems/sensors/rgbd_camera_publish_lcm_example.cc, line 54 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-L0G9rOVvMiM0C-bLifI:-L0GAkyKDv_5gN6d57P-:bpom55k) ([raw file](https://github.com/robotlocomotion/drake/blob/403cb774107af85829e6f7a3c72b00c7c8bb4118/systems/sensors/rgbd_camera_publish_lcm_example.cc#L54)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW  Why default to true? (In other tests, you have it default to false.)
</blockquote></details>

Good point.

Actually this is not meant to be a test but an executable and reused as a test.  See [here](https://github.com/kunimatsu-tri/drake/blob/403cb774107af85829e6f7a3c72b00c7c8bb4118/systems/sensors/BUILD.bazel#L465).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0GY-TEpEHT0csA2LN5:bmxilld)*

**Comment by kunimatsu-tri** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental please

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0GxZ6ZlheThMjWK2qG:bnuwbvt)*

**Comment by kunimatsu-tri** [comment]
I'm going to merge this since the error I've got from mac build is not related to this PR, but call python.

For the detail, see : https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=924634

/cc @EricCousineau-TRI 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7589#-:-L0HFp0JnWN0fY_DGQdL:bu36vxi)*

**Pull request merged**
