### PR TITLE
Optitrack_pose_extractor memcheck fix

### PR DESCRIPTION
**Pull request by naveenoid**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6717)

### CODE REVIEW

**Comment by naveenoid** [comment]
+@seancurtis-tri for feature (and platform) review

Its a simple fix.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6717#-:-KqOM9NZh7ZIXuQM8ffr:b-u370yf)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:. Match set.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6717#-:-KqObdKMOKtjNtxydBFh:b8ex4bu)*

**Comment by jwnimmer-tri** [comment]
:lgtm: this is a strict improvement.

But please note that the file has more LCM messages on the stack that lack a moustache -- e.g., the immediately prior line.  Until LCM codegen offers an option to generate constructors, every single LCM message variable ever declared within Drake must have a moustache, full stop.  @naveenoid Can you take an action item to fix at least this file (and any nearby friends) to add the moustaches?

**Comment by jwnimmer-tri** [comment]
All builds passed, but the github API outage means that status didn't get published, so the merge is still blocked.  I'll use my override powers.

**Pull request merged**
