### PR TITLE
[workspace] Use host OS VTK 9.1 when on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change all builds on Jammy except for wheel builds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18340)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-unprovisioned-gcc-bazel-experimental-debug please

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform with small nits

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18340#-:-NH5UqDH9iwlqnVBkTfd:b4e8jir)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), labeled "do not merge" (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18340#-NH5UsgbCw-hUP8O-gCM:-NH5UsgbCw-hUP8O-gCN:b-1nvdvs) (no related file):*
nit Worth porting `opencv_pydrake_test` to Drake to confirm?

___
___
*[`tools/workspace/vtk/build_binaries_with_docker` line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18340#-NH5UVWsCu6AoLHNefcJ:-NH5UVWsCu6AoLHNefcK:bygir2e) ([raw file](https://github.com/robotlocomotion/drake/blob/00b638de9f3f34243357659e93a7618f5705eb30/tools/workspace/vtk/build_binaries_with_docker#L49)):*
> ```
> 
> build focal --build-arg PLATFORM=ubuntu:20.04
> extract focal
> ```

nit Worth comment stating why Jammy isn't necessary?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18340#-:-NH5Y5UfEMjtTCAaFwhX:bnfp4nl)* status: 2 unresolved discussions, labeled "do not merge" (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18340)* status: labeled "do not merge" (waiting on @EricCousineau-TRI and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18340#-NH5UsgbCw-hUP8O-gCM:-NH5YFeJ-7GrOsX3aAcZ:b6h0hxv) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Worth porting `opencv_pydrake_test` to Drake to confirm?
</blockquote></details>

Even better, I can re-enable the OpenCV movie-streaming unit tests now.

___
___
*[`tools/workspace/vtk/build_binaries_with_docker` line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18340#-NH5UVWsCu6AoLHNefcJ:-NH5YJxg44VinhWlsn18:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/00b638de9f3f34243357659e93a7618f5705eb30/tools/workspace/vtk/build_binaries_with_docker#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Worth comment stating why Jammy isn't necessary?
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-clang-bazel-experimental-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-everything-release please
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-snopt-mosek-packaging please
@drake-jenkins-bot linux-jammy-gcc-cmake-experimental-release please

**Comment by cohnt** [comment]
I ran into some issues with this change when I was rebuilding. I was getting messages down the lines of
`Middleman _middlemen/@vtk_S_S_Cvtkkwiml-BazelCppSemantics_build_arch_k8-opt failed: missing input file 'external/vtk/include/vtk-9.1/vtk_kwiml.h', owner: '@vtk//:include/vtk-9.1/vtk_kwiml.h'`
Installing libvtk9-dev and libvtk9.1 with apt-get fixed it for me.

(I'm not really commenting asking for anything, just putting it out here in case someone else runs into the issue.)

**Comment by EricCousineau-TRI** [comment]
Thanks!
Typically when you get compilation failures, you should be sure to run `install_prereqs` to see if you're missing a dependency. In this case, it should have resolved the error you ran into.

**Pull request merged**
