### PR TITLE
[tutorials] Fix typos for hydroelastic_basics.ipynb

### PR DESCRIPTION
**Pull request by zachfang**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-:-NXS0jjP9V645Gcue0IE:bks4kj3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-NXS9tPi5jARP6iU-WOq:-NXS9tPjBZs17faf5WMV:b-ayxuu2) (no related file):*
BTW, according to [tutorials/_developers.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md), I'm not sure whether you should provide:
```
https://nbviewer.jupyter.org/github/{user}/drake/blob/{branch}/tutorials/
```
However, nbviewer didn't seem to like your branch name with `/` in its name (feature`/`hydroelastic-tutorial).

Instead, I'm looking at your file in GitHub directly 
- https://github.com/zachfang/drake/blob/feature/hydroelastic-tutorial/tutorials/hydroelastic_basics.ipynb

It looks good on GitHub.

___
___
*[`tutorials/hydroelastic_basics.ipynb` line 1044 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-NXS6IpzEh2QeYClhNV3:-NXS6IpzEh2QeYClhNV4:b-8n9tih) ([raw file](https://github.com/RobotLocomotion/drake/blob/e0a5d81944878240a461845403c776e9ddfe63d2/tutorials/hydroelastic_basics.ipynb#L1044)):*
> ```
>     "To visualize contact results, we will add `ContactVisualizer` to `Diagram` of the previous section.\n",
>     "\n",
>     "The following function `add_contact_viz()` adds `ContactVisualizer` to `DiagramBuilder` using `MultibodyPlant` and `MeshCat`.\n",
> ```

BTW, when I wrote it, I thought about the global variable `meshcat`.  Now I can see that, here, referring to the class `Meshcat` (drake::geometry::Meshcat) would be better than the global variable.

Anyway, change `MeshCat` to `Meshcat` please. To me, MeshCat refers to the MeshCat.js that rdeits writes, and Meshcat refers to drake's class.  It might be too subtle, so please feel free to ignore this request.



_Suggestion:_
```
"The following function `add_contact_viz()` adds `ContactVisualizer` to `DiagramBuilder` using `MultibodyPlant` and `Meshcat`.\n",
```

**Review by zachfang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-NXS9tPi5jARP6iU-WOq:-NXhQX870Fvi_LJ_S7B9:bc0k4h8) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, according to [tutorials/_developers.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md), I'm not sure whether you should provide:
```
https://nbviewer.jupyter.org/github/{user}/drake/blob/{branch}/tutorials/
```
However, nbviewer didn't seem to like your branch name with `/` in its name (feature`/`hydroelastic-tutorial).

Instead, I'm looking at your file in GitHub directly 
- https://github.com/zachfang/drake/blob/feature/hydroelastic-tutorial/tutorials/hydroelastic_basics.ipynb

It looks good on GitHub.
</blockquote></details>

Right! I had the same branch name issue with a previous tutorial. Will keep that in mind next time.

___
___
*[`tutorials/hydroelastic_basics.ipynb` line 1044 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-NXS6IpzEh2QeYClhNV3:-NXhQ0KrCwDLYCSfAa12:b-2bmc8p) ([raw file](https://github.com/RobotLocomotion/drake/blob/e0a5d81944878240a461845403c776e9ddfe63d2/tutorials/hydroelastic_basics.ipynb#L1044)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

BTW, when I wrote it, I thought about the global variable `meshcat`.  Now I can see that, here, referring to the class `Meshcat` (drake::geometry::Meshcat) would be better than the global variable.

Anyway, change `MeshCat` to `Meshcat` please. To me, MeshCat refers to the MeshCat.js that rdeits writes, and Meshcat refers to drake's class.  It might be too subtle, so please feel free to ignore this request.

</blockquote></details>

Done. Thanks for the clarification on the `Meshcat` variants.

**Review by DamrongGuoy — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes

**Review by DamrongGuoy — COMMENTED** [review]
+@xuchenhan-tri for platform review per June 12 schedule, please.

Tip: you can look at Zach's file in GitHub.  GitHub renders ipynb reasonably well.

https://github.com/zachfang/drake/blob/feature/hydroelastic-tutorial/tutorials/hydroelastic_basics.ipynb

According to [tutorials/_developers.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md), we should use nbviewer; however, nbviewer has problems with `/` in branch name (feature**/**hydroelastic-tutorial) and didn't work.

Since it's about fixing typos, I suppose we don't need to run the notebook. Otherwise, `bazel run //tutorials:hydroelastic_basics` is the command, according to [tutorials/_developers.md](https://github.com/RobotLocomotion/drake/blob/master/tutorials/_developers.md).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-:-NXkS7Ys20diGnQ6foct:b-tl6ayw)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @zachfang)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19562#-:-NXkWPo_AywnXyiLhtGB:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform)

**Pull request merged**
