### PR TITLE
Pulled out RigidBodyActuator into its own files.

### PR DESCRIPTION
**Pull request by liangfok**
Again, motived by the creation of a `Model` abstraction.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2889)

### CODE REVIEW

**Comment by liangfok** [comment]
+@amcastro-tri for feature review.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNHePgI1S5XxU6a2gUM:-833572683)*

**Comment by sammy-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_actuator.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNI3MHDyx_jubWa3kqk:-KNI3MHEof6KezUyywot:569241128) ([raw file](https://github.com/robotlocomotion/drake/blob/37b746b653584027eebf3aa85a27c3a92788a333/drake/systems/plants/rigid_body_actuator.h#L6)):*
> ```objc
> 
> #include "drake/drakeRBM_export.h"
> #include "drake/systems/plants/RigidBody.h"
> ```

Do we need to include RigidBody.h instead of forward declaring RigidBody?  I was under the impression that it was one of the headers which significantly increases compile times.  (which I might be wrong about this is a vague memory from when @david-german-tri was looking into it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889)*

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_actuator.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNI3MHDyx_jubWa3kqk:-KNI63QSZBmNmteF5Og2:360986986) ([raw file](https://github.com/robotlocomotion/drake/blob/37b746b653584027eebf3aa85a27c3a92788a333/drake/systems/plants/rigid_body_actuator.h#L6)):*
<details><summary><i>Previously, sammy-tri wrote…</i></summary>
> Do we need to include RigidBody.h instead of forward declaring RigidBody?  I was under the impression that it was one of the headers which significantly increases compile times.  (which I might be wrong about this is a vague memory from when @david-german-tri was looking into it)
</details>
Since `drakeGeometryUtil.h` is no longer in its transitive closure, I don't think `#include RigidBody.h` is a big cost anymore.  @liangfok, unless you're feeling your build grind to a halt on this file, it's probably better to leave as-is - the style guide warns us to minimize use of fwd-decl.

https://google.github.io/styleguide/cppguide.html#Forward_Declarations

http://drake.mit.edu/doxygen_cxx/_rigid_body_8h.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889)*

**Comment by liangfok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_actuator.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNI3MHDyx_jubWa3kqk:-KNI5aNv2n7uigtzY7ok:214333457) ([raw file](https://github.com/robotlocomotion/drake/blob/37b746b653584027eebf3aa85a27c3a92788a333/drake/systems/plants/rigid_body_actuator.h#L6)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Since `drakeGeometryUtil.h` is no longer in its transitive closure, I don't think `#include RigidBody.h` is a big cost anymore.  @liangfok, unless you're feeling your build grind to a halt on this file, it's probably better to leave as-is - the style guide warns us to minimize use of fwd-decl.
> 
> https://google.github.io/styleguide/cppguide.html#Forward_Declarations
> 
> http://drake.mit.edu/doxygen_cxx/_rigid_body_8h.html
</details>
Nice. I've updated this PR to forward declare `RigidBody`. My build actually does grind to a halt on this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889)*

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_actuator.h, line 6 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNI3MHDyx_jubWa3kqk:-KNI7AaUDb9CsBD4Ob8x:815118131) ([raw file](https://github.com/robotlocomotion/drake/blob/37b746b653584027eebf3aa85a27c3a92788a333/drake/systems/plants/rigid_body_actuator.h#L6)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Nice. I've updated this PR to forward declare `RigidBody`. My build actually does grind to a halt on this file.
</details>
OK, good to know!  It's amusing (in a sad way) that you don't actually have to include `RigidBody.h` in the `.cc` file either, since this public member field is not actually used by the class to which it belongs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/plants/rigid_body_actuator.h, line 2 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNIAHX0t_QqrfTU3-_3:-KNIAHX0t_QqrfTU3-_4:-1864512978) ([raw file](https://github.com/robotlocomotion/drake/blob/2cc5c2bc520f93addb3897c545bf905c5a727330/drake/systems/plants/rigid_body_actuator.h#L2)):*
> ```objc
> #pragma once
> ```

Missing `#include <limits>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889)*

**Comment by sherm1** [comment]
CI failure looks to be due to missing `#include <limits>` as @amcastro-tri  noted.

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNI_NHaxjI7e6GDghXt:-1076229699)*

**Comment by liangfok** [comment]
Thanks. Fixed. Waiting on CI now.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/rigid_body_actuator.h, line 2 \[r3\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-KNIAHX0t_QqrfTU3-_3:-KNImiVnezYMUkOhaD4A:1508991532) ([raw file](https://github.com/robotlocomotion/drake/blob/2cc5c2bc520f93addb3897c545bf905c5a727330/drake/systems/plants/rigid_body_actuator.h#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary>
> Missing `#include <limits>`
</details>
Done. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNImqBNBA74llh1HOJW:-1691002294)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2929/ and is thus ready for another round of feature review. @amcastro-tri 

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNJPD7Ik94VzOTyIPfO:773932958)*

**Comment by amcastro-tri** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNJQxVrXDf1dqX9TRP6:1417088721)*

**Comment by liangfok** [comment]
Thanks. +@sherm1 for platform review please.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNK0UhgQju0Ye_xZUFL:542600653)*

**Comment by liangfok** [comment]
This PR passed https://drake-jenkins.csail.mit.edu/job/experimental/2938/ and is thus ready for platform review. @sherm1

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNKQpP6TmdgEAN4U6Iq:-218004297)*

**Comment by sherm1** [comment]
Platform: :lgtm:. BTW, it would be nice to add some class documentation for these undocumented classes when you touch them, especially if you have figured out what they do!

---

Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2889#-:-KNL801nkGsVolLOAfMC:760669721)*

**Comment by liangfok** [comment]
OK I will add documentation in a future PR.

**Pull request merged**
