### PR TITLE
[systems/lcm] Add protocol for opting out of LCM messaging

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #20055.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for conceptual design review, please.

As an example, here's the graphviz output of the following command:

```console
bazel run //examples/hardware_sim:demo_cc -- --scenario_text='{simulation_duration: -1, lcm_buses: { default: null }}'   --graphviz=$(pwd)/example.dot; dot -Tpng example.dot > example.png
```

image

Note that the `IiwaDriver` is present and connected to the plant, but with no command inputs nor status outputs connected to anything.

The `WsgDriver` has not yet been ported to the Diagram encapsulation nor the LCM opt-out, so is unchanged.  That will change in a follow-up.

A summary of the no-LCM game:
- To _allow for_ opt-out of LCM, a scenario should flag the DrakeLcmParams as Optional in the dictionary.  (See `hardware_sim.py` for an example.)
- The disable LCM, the `scenario.lcm_buses` dictionary should have `{bus_name: None}` for any/all buses that want to opt-out.  Typically this would just be `scenario.lcm_buses = {"default": None}`.
- A particular `Scenario` dataclass can choose whether LCM is on or off by default.  To be on by default, a default `DrakeLcmParams` should be in the `scenario.lcm_buses` dict (or the dict should be empty).  To be off by default, the default `Scenario` should specifically set `"default"` to `None` (in the dataclass defaults for `Scenario.lcm_buses`).
- If you want to control the LCM on/off without changing or forking the scenario YAML files on disk, then in your simulation runner you can programmatically alter the `scenario.lcm_buses` dict after loading it but before passing it to `ApplyLcmBusConfig`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/hardware_sim.py` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-Nf78LxkCn1FC-EnRkcc:-Nf78LxlE65rA1KeX47T:bq4j5io) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3d069872f41f422aab2746a09e02050df7e538f/examples/hardware_sim/hardware_sim.py#L90)):*
> ```Python
>     # A map of {bus_name: lcm_params} for LCM transceivers to be used by
>     # drivers, sensors, etc. Setting the `lcm_params` to `None` indicates that
>     # LCM should not be used for that `bus_name`.
> ```

Working

I'm not sure that demonstrating the no-LCM scenario format in `hardware_sim` is a good idea.  (At least not until we can add something like a trajectory controller as part of the sim.)  The demo won't even run with LCM turned off.

Possibly is there is somewhere better where we could demo this feature?

**Review by RussTedrake — COMMENTED** [review]
That looks great to me

> Note that the `IiwaDriver` is present and connected to the plant, but with no command inputs nor status outputs connected to anything.

Agreed.  That's what I need.  All of the higher-level planning, etc will be built around it and connect here.

> To allow for opt-out of LCM, a scenario should flag the DrakeLcmParams as Optional.

That seems a bit strange to me? I think I see the "one process; no lcm" as the first class citizen (maybe even the most important workflow), but you don't?

In my workflow, I would likely not ask users to mark anything optional in the yaml file, but would always modify the `DrakeLcmParams` / `scenario.lcm_buses`in my `station.py`.  I see that's your last bullet.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-NfBA-q60325nRHL8kX1:b-rqoo64)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/hardware_sim.py` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-Nf78LxkCn1FC-EnRkcc:-NfBBGHlAKG6mBbH5cgr:b1xzg71) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3d069872f41f422aab2746a09e02050df7e538f/examples/hardware_sim/hardware_sim.py#L90)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I'm not sure that demonstrating the no-LCM scenario format in `hardware_sim` is a good idea.  (At least not until we can add something like a trajectory controller as part of the sim.)  The demo won't even run with LCM turned off.

Possibly is there is somewhere better where we could demo this feature?
</blockquote></details>

We could certainly put together a new example (one of the small ones from my course notes) that exercises the "one process; no lcm" workflow.

**Comment by jwnimmer-tri** [comment]
> > To allow for opt-out of LCM, a scenario should flag the DrakeLcmParams as Optional.
>
> That seems a bit strange to me?

Well, if the scenario _might_ or _might not_ have LCM, then there needs to be some way to denote that.  Using `typing.Optional` and setting the params to `None` (aka `null` in yaml) seemed like the best phrasing.  (If the user just wanted a `bool` for it or something, they could put that bool in their Scenario class even today.)  If there is _never_ any LCM, then the user can omit `DrakeLcmParams` from the scenario entirely and doesn't need to call `ApplyLcmBusConfig` or deal with `Optional` anything.

> I think I see the "one process; no lcm" as the first class citizen (maybe even the most important workflow), but you don't?

The hill we climbed to get here was to develop and open source `hardware_sim`, whose goal in life is to inter-operate at the LCM message layer in a multi-process environment.  So since its inception, that has been the first-class goal.

This issue is asking to put the other two new use cases on par with that goal, and I'm happy with that.  I don't understand what about this PR is treating the no-LCM as a second-class citizen.  If your Scenario default value should be to have LCM disabled, you can set up its default dataclass constructor to do that automatically, without any custom code in your scenario loader / apply code.

**Review by jwnimmer-tri — COMMENTED** [review]
Okay, the library code and tests are in near-final shape now.

I'm still not sure about the example/demo.  That will also depend on https://github.com/RobotLocomotion/drake/issues/20055#issuecomment-1736020444 response.

> Reviewed 17 of 17 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-NfNrome987ioDOZqCLg:b-vim4o8)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
Example yanked.

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-NfuyFXg4OsWFebE_dW1:bxct05r)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers

___
*[`examples/hardware_sim/hardware_sim.py` line 90 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-Nf78LxkCn1FC-EnRkcc:-Nfuy4HR8L_Z95CPMWiI:b-wq31go) ([raw file](https://github.com/RobotLocomotion/drake/blob/a3d069872f41f422aab2746a09e02050df7e538f/examples/hardware_sim/hardware_sim.py#L90)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

We could certainly put together a new example (one of the small ones from my course notes) that exercises the "one process; no lcm" workflow.
</blockquote></details>

For now, I've just withdrawn the example.  Maybe once we have the WSG changes also finished, we'll add one back.

**Comment by SeanCurtis-TRI** [comment]
+@SeanCurtis-TRI

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

+(priority: medium) 

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-Nfvl7Mg5I2tSejNUHPp:b-quante)* status: 2 unresolved discussions, LGTM missing from assignees SeanCurtis-TRI(platform),rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvHNi_3otf8E_Htmlm:-NfvW0ql7NEGil2jdZvV:b-opom2p) (no related file):*
(1)

> The "normal" values of two outputs (joint torques and external torques) depend on the omitted gain systems (they flip the signs). By not adding those diagrams, you'll get different output values for those two signals.  Why is this a good thing?

The sign flips are insane and need to die.  There's a TODO to that effect:

```c++
// TODO(eric.cousineau): Why do we flip this?
```

It is _correct_ to connect to the IiwaDriver output ports without the sign flip.  (The LCM messages currently contain the wrong data.)

Does that resolve your concerns around "cannot connect after the fact"?

(2)

Fixed by introducing a more specific helper function.

___
___
*[`manipulation/kuka_iiwa/test/build_iiwa_control_test.cc` line 262 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvJKRh41i_G1tdODSB:-NfvVEYPAIQuBJ-6Vj6C:baq8v7w) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/manipulation/kuka_iiwa/test/build_iiwa_control_test.cc#L262)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: How about confirming that we skipped adding systems as well?
</blockquote></details>

Moot now.
___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvDrkbCOMkTRpmjWGZ:-NfvX-cC91WkUlGGZvYD:baah0w0) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/systems/lcm/test/lcm_config_functions_test.cc#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Might be worth noting that while this test only invokes the `optional` flavor of `ApplyLcmBusConfig`, it relies on knowledge of delegation to implicitly test the non-optional version as well.
</blockquote></details>

I understand the gist of what you're saying, but I went back to look and I couldn't identify any functional test from a prior test case that we're implicitly relying on here for coverage.

We directly check the size of the result, and both calls to `Find`, and the list of systems that got added.  What else does `LcmConfigFunctionsTest.Basic` check that we are not checking here?  Or did you mean some other prior test?
___
*[`bindings/pydrake/systems/test/lcm_test.py` line 115 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvEanGAYGdNJIdfezB:-NfvbxWD7VO9oBYokEJd:bdu4xpk) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/bindings/pydrake/systems/test/lcm_test.py#L115)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: I'd expect a test where you apply lcm config with a `None` value. The ability to pass `None` is kind of the point, isn't it?
</blockquote></details>

Ah, yes, we need to prove that the `overload_cast` selected the proper function.  Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-NfvusLB0d3GcA5vmYr0:bmxilld)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvHNi_3otf8E_Htmlm:-NfvsF6E0K2aL1UpMmKu:b-juu82b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(1)

> The "normal" values of two outputs (joint torques and external torques) depend on the omitted gain systems (they flip the signs). By not adding those diagrams, you'll get different output values for those two signals.  Why is this a good thing?

The sign flips are insane and need to die.  There's a TODO to that effect:

```c++
// TODO(eric.cousineau): Why do we flip this?
```

It is _correct_ to connect to the IiwaDriver output ports without the sign flip.  (The LCM messages currently contain the wrong data.)

Does that resolve your concerns around "cannot connect after the fact"?

(2)

Fixed by introducing a more specific helper function.
</blockquote></details>

Ah...the "why is this a good thing?" question has a great answer. It is a *GREAT* thing and the negation needs to die by fire.  Simple enough.

___
___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvDrkbCOMkTRpmjWGZ:-NfvtAyvDvaGq0ma8z11:b1ejb5t) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/systems/lcm/test/lcm_config_functions_test.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I understand the gist of what you're saying, but I went back to look and I couldn't identify any functional test from a prior test case that we're implicitly relying on here for coverage.

We directly check the size of the result, and both calls to `Find`, and the list of systems that got added.  What else does `LcmConfigFunctionsTest.Basic` check that we are not checking here?  Or did you mean some other prior test?
</blockquote></details>

So, we can call two versions of `ApplyLcmBusConfig()` one version takes optional params the other just takes params. *Both* can be used for "opting-out of LCM" (as the purpose of this test is documented). This test only explicitly invokes the optional-flavored override. Someone who looks at the public APIs might think, what about the other override? I can use that to opt out. Why isn't that called?

If they look at the *implementation* of the two overrides, they'd see that the optional one invokes the other. Thus, testing the optional one tests both. But to put that together, the reader would have to look at more than the header file and test file. They'd also have to look at the .cc file.

I was merely suggesting a comment on the test making it clear that while one can opt out by using the other override, we're not explicitly testing it because the test, as is, is already implicitly testing it.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvDrkbCOMkTRpmjWGZ:-NfvvSdUDyN7aKl9Y4I6:b2lcr19) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/systems/lcm/test/lcm_config_functions_test.cc#L121)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

So, we can call two versions of `ApplyLcmBusConfig()` one version takes optional params the other just takes params. *Both* can be used for "opting-out of LCM" (as the purpose of this test is documented). This test only explicitly invokes the optional-flavored override. Someone who looks at the public APIs might think, what about the other override? I can use that to opt out. Why isn't that called?

If they look at the *implementation* of the two overrides, they'd see that the optional one invokes the other. Thus, testing the optional one tests both. But to put that together, the reader would have to look at more than the header file and test file. They'd also have to look at the .cc file.

I was merely suggesting a comment on the test making it clear that while one can opt out by using the other override, we're not explicitly testing it because the test, as is, is already implicitly testing it.
</blockquote></details>

Ah.  The important part there was opt-ing out via the magic string, when calling the non-optional overload.  I didn't grok that from the first post.

I'll push some clarification.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 121 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-NfvDrkbCOMkTRpmjWGZ:-Nfvvk849P7Ed3f1OrTF:bx0kr3i) ([raw file](https://github.com/RobotLocomotion/drake/blob/f585b439917c6ad4066b49bd18b47cba0471a05a/systems/lcm/test/lcm_config_functions_test.cc#L121)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  The important part there was opt-ing out via the magic string, when calling the non-optional overload.  I didn't grok that from the first post.

I'll push some clarification.
</blockquote></details>

Yeah. My first pass was overly terse.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 17 files at r1, 3 of 7 files at r2, 6 of 7 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-:-NfwBQRd-cb9Xq-aOV1a:bnfp4nl)* status: 3 unresolved discussions

___
*[`systems/lcm/lcm_buses.h` line 27 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-Nfw8IwcAj7RQsuWvbZt:-Nfw8Iwd2GhNDlhuhLJK:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ba9d7575a8c4cadfb4e2cae23c82e8939ea98f9/systems/lcm/lcm_buses.h#L27)):*
> ```objc
>   /** A magic LCM URL sentinel value for the "null" LCM interface. In some
>   cases, LCM messages are unwanted but we need to pass around a well-formed
>   DrakeLcmParams or DrakeLcmInteraface object. Instead of passing `nullptr`
> ```

typo



_Suggestion:_
```objc
DrakeLcmInterface
```
___
*[`systems/lcm/test/lcm_config_functions_test.cc` line 146 at r4](https://reviewable.io/reviews/RobotLocomotion/drake/20247#-Nfw7K1MA-V0sTJpda4B:-Nfw7K1N0kh_frIeZvVc:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake/blob/9ba9d7575a8c4cadfb4e2cae23c82e8939ea98f9/systems/lcm/test/lcm_config_functions_test.cc#L146)):*
> ```cpp
>   }
>   const std::vector<std::string> expected{
>       // The two `SharedPtrSystem`s are the only things that gets added.
> ```

typo



_Suggestion:_
```cpp
things that get
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20247)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform)

**Pull request merged**
