### PR TITLE
Support named_vector inequality constraints on output ports

### LINKED ISSUE #7037: Generated BasicVector subclasses should automatically generate SystemConstraints
Generated BasicVector subclasses such as [PendulumParams](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/pendulum/gen/pendulum_params.h) should automatically generate [SystemConstraint](http://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_system_constraint.html) instances when they are declared as State, Params, etc. of a System.

This should happen automatically (the DeclareFoo methods should inspect the type to see if constraints are available), but perhaps should offer an opt-out in case someone doesn't want the magic behavior.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #7037 again.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7067)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for feature review, please.

+@ggould-tri for platform review, please.  I'm on-call tomorrow and this is nearly identical to #7057 that you looked at today.

**Comment by RussTedrake** [comment]
:lgtm:  very slick

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7067#-:-KuYbhxiiMNltNW2JzKQ:bt6ftz3)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-open-source please

**Comment by jwnimmer-tri** [comment]
-@ggould-tri +@soonho-tri for platform review per rotation (Monday), please.

**Comment by soonho-tri** [comment]
:lgtm:

TIL, I can do `[x = ...]` in C++ lambda!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7067#-:-KutoRPyq7AFpFBxCrsn:b-gk86z9)*

**Pull request merged**
