### PR TITLE
equality constrained QP solver was not parsing linear costs

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6916)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6916#-:-KsPklhF_RhyKFGkdrEi:b-81zjv5)*

**Comment by RussTedrake** [comment]
@drake-jenkins-bot ok to test

**Comment by hongkai-dai** [comment]
:lgtm: +@sherm1 for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6916#-KsPmCstqLCwygeglH53:-KsPmCsupSVqH3rejHM_:bnnui1s) ([raw file](https://github.com/robotlocomotion/drake/blob/855effc5198863ee33f81bce4985c0516be4dee9/drake/solvers/equality_constrained_qp_solver.cc#L149)):*
> ```cpp
>     int num_v_variables = binding.variables().rows();
> 
>     std::vector<size_t> v_index(num_v_variables);
> ```

BTW, we probably do not need to do this dynamic allocation for `std::vector` here, if we combine the following two for loops as
```C++
for (int i = 0; i < num_v_variables; ++i) {
    auto v_index_i = prog.FindDecisionVariableIndex(binding.variables()(i));
    c(v_index_i) += a(i);
 }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6916#-:-KsPmc-X6KqjqApmI0Q0:bozh2sc)*

**Comment by RussTedrake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/equality_constrained_qp_solver.cc, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6916#-KsPmCstqLCwygeglH53:-KsQ9mpPVMI5ozD2RVgU:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/855effc5198863ee33f81bce4985c0516be4dee9/drake/solvers/equality_constrained_qp_solver.cc#L149)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, we probably do not need to do this dynamic allocation for `std::vector` here, if we combine the following two for loops as
```C++
for (int i = 0; i < num_v_variables; ++i) {
    auto v_index_i = prog.FindDecisionVariableIndex(binding.variables()(i));
    c(v_index_i) += a(i);
 }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6916)*

**Comment by sherm1** [comment]
Platform :lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6916#-:-KsQhbOCOFSAOLqkOW-Y:b8qx53o)*

**Pull request merged**
