### PR TITLE
[systems/framework] FixInputPortsFrom does not support type-dependent abstract ports

### PR DESCRIPTION
**Pull request by RussTedrake**
This PR adds a docstring and some tests confirming the behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@seancurtis-tri for feature review.
+@sherm1 for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437#-:-Mf53wi2-is93TSq7Ozd:b-cmk80r)* status: LGTM missing from assignees SeanCurtis-TRI(platform),sherm1(platform) (waiting on @SeanCurtis-TRI and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending feature review and a few minor comments.

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437#-:-Mf5WCRq0TPGaySSi2yS:b-hx86ju)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @RussTedrake and @SeanCurtis-TRI)

___
*[multibody/plant/test/multibody_plant_test.cc, line 3569 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5VS-g5F6a-ckmNMc-:-Mf5VS-g5F6a-ckmNMc0:bmpu08r) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/multibody/plant/test/multibody_plant_test.cc#L3569)):*
> ```cpp
> 
> // Demonstrate that FixInputPortsFrom does *not* currently work for a
> // MBP+SceneGraph combo.
> ```

minor: not obvious from the description why this fails. I _think_ it is because the presence of SG creates a port of T-dependent AbstractValue type? Please explain a little more in the comment.
___
*[systems/framework/system.h, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5U_4589kMoEsqfFc5:-Mf5U_4589kMoEsqfFc6:bd6jma6) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/systems/framework/system.h#L1136)):*
> ```objc
>   disconnected inputs.
>   @throws std::exception if other_system has any type-dependent AbstractValue
>   input ports and T != double. */
> ```

minor: not clear what "type-dependent AbstractValue" means here. Consider spelling it out a little more, like "AbstractValue where the actual value is templatized on T"
___
*[systems/framework/test/system_test.cc, line 888 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5UyEt1YJ06OxPzwOQ:-Mf5UyEuCRApEWdxwxAJ:be9k818) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/systems/framework/test/system_test.cc#L888)):*
> ```cpp
> }
> 
> // Confirm that FixInputPortsFrom does *not* convert type-depedendent abstract
> ```

nit: depedendent -> dependent

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI and @sherm1)

___
*[multibody/plant/test/multibody_plant_test.cc, line 3569 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5VS-g5F6a-ckmNMc-:-Mf5Zod3EyJ49rB9Xp4Q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/multibody/plant/test/multibody_plant_test.cc#L3569)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not obvious from the description why this fails. I _think_ it is because the presence of SG creates a port of T-dependent AbstractValue type? Please explain a little more in the comment.
</blockquote></details>

Done.
___
*[systems/framework/system.h, line 1136 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5U_4589kMoEsqfFc5:-Mf5_5Kh95xWaGEbkF2V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/systems/framework/system.h#L1136)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: not clear what "type-dependent AbstractValue" means here. Consider spelling it out a little more, like "AbstractValue where the actual value is templatized on T"
</blockquote></details>

Done.
___
*[systems/framework/test/system_test.cc, line 888 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf5UyEt1YJ06OxPzwOQ:-Mf5_Bqi5FjgE1q-yb08:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/f77267f36475f231cabfe93989c9a1c69252b180/systems/framework/test/system_test.cc#L888)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: depedendent -> dependent
</blockquote></details>

Done.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: with some small cosmetic points.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437#-:-Mf8U2JxAuSscIcA9R7w:b-fr8uek)* status: 3 unresolved discussions (waiting on @RussTedrake)

___
*[multibody/plant/test/multibody_plant_test.cc, line 3568 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8S5bd5sMZ-92hG2ef:-Mf8S5bd5sMZ-92hG2eg:b-rrtdo1) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/multibody/plant/test/multibody_plant_test.cc#L3568)):*
nit: Have we tested something that isn't part of the public API documentation? Perhaps this is merely a marker for us to track a particularly undesirable behavior. But, given the number of people who've tripped over this, it seems it should be documented. That said, I'm not exactly sure what the documentation should be, because how you hit this problem is somewhat removed from direct use of the plant (generally, the user isn't making a direct call to the MBP API, but passing the MBP around such that it is exercised by other operations). But if anyone has creative ideas to help protect users in the interim, I'm game.

At the least, we should connect this to an issue.

> TODO(5454) Once transmogrification of scalar-dependent abstract values is implemented, this test can simply be removed (as we no longer have to track this undesirable behavior).
___
*[multibody/plant/test/multibody_plant_test.cc, line 3587 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8RosO4spv6wMz76Lo:-Mf8RosO4spv6wMz76Lp:b-mag81v) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/multibody/plant/test/multibody_plant_test.cc#L3587)):*
> ```cpp
>   auto autodiff_context = autodiff_plant->CreateDefaultContext();
> 
>   DRAKE_EXPECT_THROWS_MESSAGE(autodiff_plant->FixInputPortsFrom(
> ```

BTW With recent styleguide changes (and supporting changes in code), you can completely omit the reference to `std::exception` as:

```c++
DRAKE_EXPECT_THROWS_MESSAGE(test_expression, "message reg ex");
```
___
*[systems/framework/system.h, line 1135 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8LfJk5pjb1STkoktg:-Mf8LfJk5pjb1STkokth:b-5u9vbv) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/systems/framework/system.h#L1135)):*
When I first read this sentence, I originally thought it was simply "wrong". Part of it has to do with the scope of the symbol `T` (it is the scalar type for *this* system, so, by definition, the other system cannot be templatized on T). As I ws trying to figure out what the problem was, I was able to figure out what was being communicated. Here's my best alternative suggestion:

> throws if `this` system's scalar type T != double and `other_system` has any abstract input ports whose contained type depends on scalar type.

(Note, I picked phrases like "abstract input port" and "contained type" to match the language and APIs like "DeclareAbstractInputPort" and AbstractValue is a "fully type-erased container class". I also reversed the order of the predicates because I felt it helped disambiguate clause attachment -- curse you, English!)
___
*[systems/framework/test/system_test.cc, line 909 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8RN8qCbb8lZX3z6AW:-Mf8RN8qCbb8lZX3z6AX:b-mag81v) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/systems/framework/test/system_test.cc#L909)):*
> ```cpp
>   DRAKE_EXPECT_THROWS_MESSAGE(autodiff_system.FixInputPortsFrom(
>                                   test_sys_, *context, autodiff_context.get()),
>                               std::exception,
> ```

BTW With recent styleguide changes (and supporting changes in code), you can completely omit the reference to `std::exception` as:

```c++
DRAKE_EXPECT_THROWS_MESSAGE(test_expression, "message reg ex");
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI and @sherm1)

___
*[multibody/plant/test/multibody_plant_test.cc, line 3568 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8S5bd5sMZ-92hG2ef:-MfTZAw9D1XdNcvI-wPZ:b-nv8fcy) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/multibody/plant/test/multibody_plant_test.cc#L3568)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Have we tested something that isn't part of the public API documentation? Perhaps this is merely a marker for us to track a particularly undesirable behavior. But, given the number of people who've tripped over this, it seems it should be documented. That said, I'm not exactly sure what the documentation should be, because how you hit this problem is somewhat removed from direct use of the plant (generally, the user isn't making a direct call to the MBP API, but passing the MBP around such that it is exercised by other operations). But if anyone has creative ideas to help protect users in the interim, I'm game.

At the least, we should connect this to an issue.

> TODO(5454) Once transmogrification of scalar-dependent abstract values is implemented, this test can simply be removed (as we no longer have to track this undesirable behavior).
</blockquote></details>

Done.  I'm also open to suggestions, but feel better at least having confirmed this and now having a place I can point to.  Connecting to #5454 is a big improvement (I've also done it in `system_test`), thanks!
___
*[multibody/plant/test/multibody_plant_test.cc, line 3587 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8RosO4spv6wMz76Lo:-MfTZXoq2Y44Clehr6Cd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/multibody/plant/test/multibody_plant_test.cc#L3587)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW With recent styleguide changes (and supporting changes in code), you can completely omit the reference to `std::exception` as:

```c++
DRAKE_EXPECT_THROWS_MESSAGE(test_expression, "message reg ex");
```
</blockquote></details>

Done.
___
*[systems/framework/system.h, line 1135 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8LfJk5pjb1STkoktg:-MfT_1vp1gt41cZqEw9i:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/systems/framework/system.h#L1135)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

When I first read this sentence, I originally thought it was simply "wrong". Part of it has to do with the scope of the symbol `T` (it is the scalar type for *this* system, so, by definition, the other system cannot be templatized on T). As I ws trying to figure out what the problem was, I was able to figure out what was being communicated. Here's my best alternative suggestion:

> throws if `this` system's scalar type T != double and `other_system` has any abstract input ports whose contained type depends on scalar type.

(Note, I picked phrases like "abstract input port" and "contained type" to match the language and APIs like "DeclareAbstractInputPort" and AbstractValue is a "fully type-erased container class". I also reversed the order of the predicates because I felt it helped disambiguate clause attachment -- curse you, English!)
</blockquote></details>

Done.
___
*[systems/framework/test/system_test.cc, line 909 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15437#-Mf8RN8qCbb8lZX3z6AW:-MfT_sgB0sxKMpwK-Lv-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/cc31333f601f4141665c8f973ecad4dfd59df90c/systems/framework/test/system_test.cc#L909)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW With recent styleguide changes (and supporting changes in code), you can completely omit the reference to `std::exception` as:

```c++
DRAKE_EXPECT_THROWS_MESSAGE(test_expression, "message reg ex");
```
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15437#-:-MfYCU5j569FrTF0V4lQ:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Comment by RussTedrake** [comment]
I don't mind passing it around, but sherm already did the platform review on this one.
-@rpoyner-tri

**Pull request merged**
