### PR TITLE
Rational forward kinematics python bindings

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKH-xp-1wCJlVPMq6eO:bggbbet)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
CI fails in the lint test.

> Reviewed 1 of 3 files at r1, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKH4Zmf-AdMldOy7apy:b-n5ziaf)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/multibody/rational_py.cc` line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH3o0j-R7d1NVSJRtw:-NKH3o0j-R7d1NVSJRtx:b-yn9mft) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/rational_py.cc#L48)):*
> ```cpp
>             &Class::ConvertMultilinearPolynomialToRationalFunction,
>             py::arg("e"), cls_doc.ctor.doc)
>         .def("plant", &Class::plant, cls_doc.ctor.doc)
> ```

missing `py_rvp::reference_internal` here?
___
*[`bindings/pydrake/multibody/rational_py.cc` line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH3UMFEMX4oqOhWhIC:-NKH3UMFEMX4oqOhWhID:b-nqpsoh) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/rational_py.cc#L49)):*
> ```cpp
>             py::arg("e"), cls_doc.ctor.doc)
>         .def("plant", &Class::plant, cls_doc.ctor.doc)
>         .def("s", &Class::s, py_rvp::copy, cls_doc.ctor.doc)
> ```

Why the return value policy is copy here instead or reference_internal?
___
*[`bindings/pydrake/multibody/test/rational_test.py` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH46JT4DctFa3OtUiZ:-NKH46JT4DctFa3OtUi_:btnbrm5) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/test/rational_test.py#L36)):*
> ```Python
> 
>         # test constructor
>         self.rat_forward = rational.RationalForwardKinematics(self. plant)
> ```

Use named argument in the test as `rational.RationalForwardKinematics(plant=self.plant)`.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

___
*[`bindings/pydrake/multibody/rational_py.cc` line 48 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH3o0j-R7d1NVSJRtw:-NKH4tzv2p--w6x932_w:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/rational_py.cc#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

missing `py_rvp::reference_internal` here?
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/rational_py.cc` line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH3UMFEMX4oqOhWhIC:-NKH4uX48TOhrOFstgVa:b-anbgc3) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/rational_py.cc#L49)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why the return value policy is copy here instead or reference_internal?
</blockquote></details>

This returns an array of numpy objects of type `symbolic::Variable` which must be copied as far as I know.
___
*[`bindings/pydrake/multibody/test/rational_test.py` line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH46JT4DctFa3OtUiZ:-NKH59Z86N8E8a3N8pF-:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/test/rational_test.py#L36)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Use named argument in the test as `rational.RationalForwardKinematics(plant=self.plant)`.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

Please either squash the commits or re-write the commit message when merging the PR.

> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKH6UaY3gME_K-BJd-B:bhuu2kh)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/multibody/rational_py.cc` line 49 at r3](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH3UMFEMX4oqOhWhIC:-NKH6-eX7u2PdOqR8YfA:btdsfzr) ([raw file](https://github.com/robotlocomotion/drake/blob/889269f1719468edc57ec2efb9a2079e44dd82e9/bindings/pydrake/multibody/rational_py.cc#L49)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This returns an array of numpy objects of type `symbolic::Variable` which must be copied as far as I know.
</blockquote></details>

I see.
___
*[`bindings/pydrake/multibody/test/rational_test.py` line 82 at r5](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKH6A6z-BH3bynjreI-:-NKH6A6z-BH3bynjreI0:b-8nedrd) ([raw file](https://github.com/robotlocomotion/drake/blob/c4537361d7775ef339968f2ed876fdf188136a90/bindings/pydrake/multibody/test/rational_test.py#L82)):*
> ```Python
>         q_recomputed = self.rat_forward.ComputeQValue(s_val=s,
>                                                       q_star_val=q_star)
>         print(q)
> ```

nit. Remove the print?

**Review by AlexandreAmice — COMMENTED** [review]
Do I need a platform review here?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKJWle9EF572KfSiLdt:b-lk1osu)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai)

**Review by sherm1 — COMMENTED** [review]
Yes. +@sherm1 for platform review
:lgtm: pending a few minor things

> Reviewed 1 of 3 files at r1, 1 of 5 files at r3, 3 of 5 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKKvF7SDfRKnUUQn31u:boy5b47)* status: 5 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

___
*[`multibody/rational/rational_forward_kinematics.h` line 154 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKshge45iX7SlHXXGc:-NKKshge45iX7SlHXXGd:b-a7tri3) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/multibody/rational/rational_forward_kinematics.h#L154)):*
> ```objc
>       // a variable into s_.
>       const int q_index = mobilizer.position_start_in_q();
>       using std::pow;
> ```

BTW what was the motivation for adding this using, and should that same motivation apply to atan2?
___
*[`bindings/pydrake/multibody/rational_py.cc` line 47 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKupuqAlc00gUFhDTn:-NKKupuqAlc00gUFhDTo:bgk3k0) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/bindings/pydrake/multibody/rational_py.cc#L47)):*
> ```cpp
>         .def("ConvertMultilinearPolynomialToRationalFunction",
>             &Class::ConvertMultilinearPolynomialToRationalFunction,
>             py::arg("e"), cls_doc.ctor.doc)
> ```

minor: This and the previous binding both use the constructor documentation. Is that intentional? If not please fix. If so, please add a comment explaining why that is the right thing to do.
___
*[`bindings/pydrake/multibody/rational_py.cc` line 78 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKv7-TCYcvvFTQxcJX:-NKKv7-TCYcvvFTQxcJY:b6st4t7) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/bindings/pydrake/multibody/rational_py.cc#L78)):*
> ```cpp
>               return self.ComputeQValue(s_val, q_star_val);
>             },
>             py::arg("s_val"), py::arg("q_star_val"), cls_doc.ComputeSValue.doc)
> ```

minor: shouldn't this be using ComputeQValue.doc rather than SValue? (Also below)
___
*[`bindings/pydrake/multibody/rational_py.cc` line 93 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKvRhK8k7dmRFx85Bv:-NKKvRhL3WkhGJF03wPB:b-yc8d34) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/bindings/pydrake/multibody/rational_py.cc#L93)):*
> ```cpp
>             },
>             py::arg("s_val"), py::arg("q_star_val"), cls_doc.ComputeSValue.doc);
>   }
> ```

BTW please take a careful look at all the doc strings specified above to make sure each one is what you want -- easy to make copy/paste errors here.
___
*[`bindings/pydrake/multibody/test/pendulum_on_rail.sdf` line 57 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKuDDX6PcTER4Wxa8U:-NKKuDDX6PcTER4Wxa8V:b-sy7sp) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/bindings/pydrake/multibody/test/pendulum_on_rail.sdf#L57)):*
> ```
>     </joint>
>   </model>
> </sdf>
> ```

nit: Reviewable is complaining because there is no newline at end of file

**Review by AlexandreAmice — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495#-:-NKLGMmJ1K6Eq8qhRbYA:b-9qdoz3)* status: 3 unresolved discussions, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @hongkai-dai and @sherm1)

___
*[`multibody/rational/rational_forward_kinematics.h` line 154 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKshge45iX7SlHXXGc:-NKLFRCR-EN6H_Dsa96o:b-ubn83) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/multibody/rational/rational_forward_kinematics.h#L154)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW what was the motivation for adding this using, and should that same motivation apply to atan2?
</blockquote></details>

We need to use different `pow` functions based on the type. Adding this using allows the compiler to look for the appropriate `pow` function in the name space. I added the the same for `atan2`
___
*[`bindings/pydrake/multibody/rational_py.cc` line 78 at r6](https://reviewable.io/reviews/robotlocomotion/drake/18495#-NKKv7-TCYcvvFTQxcJX:-NKLFzAF2GldvDJn4Lze:b8go2vd) ([raw file](https://github.com/robotlocomotion/drake/blob/ab0b8e93376603f8b78916a970d2aa7ff0f22082/bindings/pydrake/multibody/rational_py.cc#L78)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: shouldn't this be using ComputeQValue.doc rather than SValue? (Also below)
</blockquote></details>

Good catch. Thanks!

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18495)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @AlexandreAmice)

**Pull request merged**
