### PR TITLE
Clean up external dependencies in CMakeLists.txt.

### PR DESCRIPTION
**Pull request by david-german-tri**
Hide dependencies that should always be OFF when MATLAB is absent, remove some commented-out code, and delete a Cygwin-specific hack.

@jamiesnape for feature review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2314) &emsp; Multiple assignees:&emsp;@jamiesnape&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/jamiesnape">jamiesnape</a>,&emsp;@sherm1&nbsp;<a href="/robotlocomotion/drake/pulls/assigned/sherm1">sherm1</a>

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> #### Clean up external dependencies in CMakeLists\.txt\.
> 
> Hide dependencies that should always be OFF when MATLAB is absent, remove some commented-out code, and delete a Cygwin-specific hack.
> 
> 
> 
> @jamiesnape for feature review
> 
> 
> </details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2314#-:-KHV-VTiJiD4YA6uWHsW:1417088721)*

**Comment by david-german-tri** [comment]
+@sherm1 for platform review

**Comment by sherm1** [comment]
One optional comment. Also,  does CI include builds with Matlab present and missing so that the bulk of these changes has been tested? If so, :lgtm:, and this is a big improvement over the earlier mess!

<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> +@sherm1 for platform review</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2314#-KHVuZ7ye8knEn_pWsDV:-KHVuZ7zOayEpe5211U3:729106313) ([raw file](https://github.com/robotlocomotion/drake/blob/4fe837a097086066cb565e9fa377dfbee14a55fd/CMakeLists.txt#L111)):*
> ```CMake
> CMAKE_DEPENDENT_OPTION(WITH_IRIS "fast approximate convex segmentation" OFF "NOT DISABLE_MATLAB;matlab;NOT WIN32" OFF)
> CMAKE_DEPENDENT_OPTION(WITH_MOSEK "convex optimization solver; free for academics" OFF "NOT DISABLE_MATLAB;matlab;NOT WIN32" OFF)
> CMAKE_DEPENDENT_OPTION(WITH_OCTOMAP "provides oct-tree data structures" OFF "NOT DISABLE_MATLAB;matlab;NOT WIN32" OFF)
> ```

Octomap is also an optional dependency of FCL; I don't think it should be contingent on Matlab. However, FCL PR #2010 doesn't have it enabled so if you prefer to leave it we can fix it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2314#-:-KHVxHWyx6yOrTZqGW4A:-722878692)*

**Comment by jamiesnape** [comment]
>  Also, does CI include builds with Matlab present and missing so that the bulk of these changes has been tested?

Yes, on every pull request.

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 111 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2314#-KHVuZ7ye8knEn_pWsDV:-KHb15ek2UYKDFVucoR_:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/6a2c663b918f68c9e80a938c7738288a075856ac/CMakeLists.txt#L111)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary>
> Octomap is also an optional dependency of FCL; I don't think it should be contingent on Matlab. However, FCL PR #2010 doesn't have it enabled so if you prefer to leave it we can fix it later.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2314)*

**Pull request merged**
