### PR TITLE
Increase error margin for OSQP solve time in the unit test

### PR DESCRIPTION
**Pull request by yminchen**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637)

### CODE REVIEW

**Comment by yminchen** [comment]
@avalenzu This might fix the failed test. #14636

**Comment by avalenzu** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-coverage please.

**Comment by avalenzu** [comment]
@drake-jenkins-bot retest this please

**Review by avalenzu — COMMENTED** [review]
+@avalenzu for feature review. :lgtm: +@ggould-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637#-:-MTHuWzL3OKSmLUwSIRb:bo1479k)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @avalenzu and @ggould-tri)

**Review by avalenzu — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by avalenzu — COMMENTED** [review]
+(priority: emergency) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637#-:-MTHxFN18aFhkn85j8jo:bcyjq0s)* status: LGTM missing from assignee ggould-tri(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637#-:-MTHyYiJ0kqKA00PATFE:bnfp4nl)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @ggould-tri)

**Review by avalenzu — COMMENTED** [review]
+(status: squashing now) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14637#-:-MTI0c1H9e9VkGO13K4i:bm9o57a)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),avalenzu (waiting on @ggould-tri)

**Comment by jwnimmer-tri** [comment]
@hongkai-dai @yminchen @avalenzu Even the 40% limit is still too flaky: https://drake-cdash.csail.mit.edu/test/123025721.  I don't think the test can measure wall-time on an order of 2x tolerance.  Need at least 10x or 100x tolerance.  But really, I'm not sure the failing assertion is actually useful, in the first place?  Can't we check the status code for "timed out" instead of inspecting the actual wall clock?

**Comment by yminchen** [comment]
@jwnimmer-tri Yes that sounds like a good solution. I will submit a PR that check the status value.

**Pull request merged**
