### PR TITLE
Making Two Bazel and CMake Test Sizes Consistent

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6559)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-nightly-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-nightly-memcheck-valgrind-minimal please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-valgrind-minimal please

**Comment by m-chaturvedi** [comment]
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-valgrind please
@drake-jenkins-bot linux-xenial-clang-experimental-memcheck-valgrind-minimal please

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6559#-:-KosYT3rsWcfkuzu0Axr:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
+@ggould-tri for platform review, please.

**Comment by jwnimmer-tri** [comment]
:lgtm:

**Pull request merged**
