### PR TITLE
Fixes alignment issue for #2683 

### LINKED ISSUE #2683: Jenkins build unstable after #2596
#2596 introduces a test using a fixture class with a `RigidBodyTree` member. `RigidBodyTree` is Eigen aligned and therefore the fixture should as well.
This could potentially be the cause for alignment issues [here](https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=43109).

See also #2679

### PR DESCRIPTION
**Pull request by amcastro-tri**
Fixes #2683

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2684)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@david-german-tri for platform review
+@mwoehlke-kitware and +@liangfok for feature review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-:-KLNONWzq5BGGz5sq13z:97375344)*

**Comment by liangfok** [comment]
I scheduled the following Win32-continuous-debug CI test:

https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/16/

The link should work once it's actually begun executing.

**Comment by david-german-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-KLNOsjrmKa2z19GndsZ:-KLNOsjrmKa2z19Gnds_:1424223329) ([raw file](https://github.com/robotlocomotion/drake/blob/ef3c5071bddd644b00004be3c46be64ce8f609a5/drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc#L66)):*
> ```cpp
>   const RigidBody *small_sphere_, *large_box_;
>   BodyToSurfacePointMap solution_;
>  public:
> ```

https://google.github.io/styleguide/cppguide.html#Declaration_Order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684)*

**Comment by amcastro-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc, line 66 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-KLNOsjrmKa2z19GndsZ:-KLNPW7fp6sdTJpD2r62:-499146009) ([raw file](https://github.com/robotlocomotion/drake/blob/ef3c5071bddd644b00004be3c46be64ce8f609a5/drake/systems/plants/test/rigid_body_tree/rbt_collisions_test.cc#L66)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> https://google.github.io/styleguide/cppguide.html#Declaration_Order
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684)*

**Comment by liangfok** [comment]
https://drake-jenkins.csail.mit.edu/view/Experimental/job/windows-msvc-ninja-32-experimental/16/ passed. The changes since that test appear to be unrelated. Thus, I believe this PR is ready to be merged.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-:-KLNTE302uvEDqmtaqhA:-2143562940)*

**Comment by mwoehlke-kitware** [comment]
@david-german-tri, reviewable seems to be waiting on you...?

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-:-KLNa8_gGMEuRvoU23xz:1417088721)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2684#-:-KLNah9ngUnoPXIbQaWb:1417088721)*

**Pull request merged**
