### PR TITLE
[IRIS] New termination conditions for IrisInConfigurationSpace

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds options.num_infeasible_samples to support a probabilistic guarantee of correctness (with probability one as the number of samples goes to infinity) for the nonlinear-optimization-based version of IRIS.

Because this requires solving potentially many more (nearly identical) MathematicalPrograms, I've finally done the refactor which reuses the allocated programs and just updated the constraints.

BREAKING CHANGE: We have elected to remove support for Ibex from IRIS; it proved to only be useful for exceptionally toy problems and has become a footgun for users that turn it on (and wait forever). Rather than carry it through this refactor, I have elected to remove it.

+@mpetersen94 for feature review
+@cohnt for additional feature review

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
Thanks for doing all this!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987#-:-ND3lFEe0_r-biY7s-Ii:b-i108fi)* status: 5 unresolved discussions, LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3dTb5A-iFU5LSxJvk:-ND3dTb5A-iFU5LSxJvl:b-iy6ba8) ([raw file](https://github.com/robotlocomotion/drake/blob/90d8b0d4c8eaaace6e44279db18ce2cf8c0396b9/geometry/optimization/iris.h#L55)):*
> ```objc
>   computationally demanding, so we disable it by default for a faster
>   algorithm for obtaining regions without the rigorous guarantee. */
>   bool enable_ibex = false;
> ```

Is there anyway to add a deprecation to this option? Removing the actual ibex code that is run when this is true is the right move but having a warning when users try to set this might be better than their code throwing.
___
*[`geometry/optimization/iris.h` line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3gcoS6ILvuc4-p0pW:-ND3gcoS6ILvuc4-p0pX:b8cx257) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.h#L162)):*
> ```objc
> `options.num_additional_constraints_infeasible_samples`.
> 
> @throws std::exception if the sample configuration in @p context is infeasible.
> ```

nit: Is there any benefit to allowing configurations that are in collision when the user doesn't require that the sample point is contained?
___
*[`geometry/optimization/iris.cc` line 484 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3frMcEuqm9S04TeaR:-ND3frMcEuqm9S04TeaS:beir3t5) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L484)):*
> ```cpp
> // Defines a MathematicalProgram to solve the problem
> // min_q (q-d)*CᵀC(q-d)
> // s.t. setA in frameA and setB in frameB are in collision in q.
> ```

I think this is a copy-paste mistake and should still be the `counter-example-constraint`
___
*[`geometry/optimization/iris.cc` line 663 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3kJOs6FawxN7_xsUx:-ND3kJOs6FawxN7_xsUy:b-jcchd7) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L663)):*
> ```cpp
>             .distance;
>     if (distance < 0.0) {
>       throw std::runtime_error(
> ```

There are no tests for this new error checking behavior. Consider adding a test that confirms behavior when a sample is passed that it outside joint limits, in collision, or violates additional constraints.
___
*[`geometry/optimization/iris.cc` line 753 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3hwEj99vgGaWj2pyZ:-ND3hwEj99vgGaWj2py_:b-abr32s) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L753)):*
> ```cpp
>       {solvers::SnoptSolver::id(), solvers::IpoptSolver::id()});
> 
>   DRAKE_THROW_UNLESS(P.PointInSet(sample, 1e-12));
> ```

Can this be moved up to right after the construction of `P` so that if the user passes a bad sample it fails almost immediately without any of the distance checking work?

**Review by cohnt — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987)* status: 5 unresolved discussions, LGTM missing from assignee mpetersen94, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @RussTedrake)

**Review by mpetersen94 — COMMENTED** [review]
Forgot to :lgtm: pending the above comments.
+@sherm1 for platform review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987#-:-ND4OIjEBy78sTFfEufy:b-8ateit)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

**Review by cohnt — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987#-:-ND4R2kV2p2_73MNZnOt:bnfp4nl)* status: 5 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake and @sherm1)

**Review by sherm1 — COMMENTED** [review]
Platform checkpoint (lunch)

> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987#-:-ND4TDh2BWOaLx1jBlML:bypd00n)* status: 7 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.h` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND4SSV01lDjrp_OD_OG:-ND4SSV01lDjrp_OD_OH:b-q8j7na) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.h#L57)):*
> ```objc
>   counter-example search, defining the number of consecutive failures to find a
>   counter-example requested before moving on to the next constraint. */
>   int num_infeasible_samples{5};
> ```

BTW can this have a more specific name? There is an existing option `num_additional_constraint_infeasible_samples` which would seem to be included in the new option. Maybe `num_collision_infeasible_samples` ?
___
*[`bindings/pydrake/geometry_py_optimization.cc` line 297 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND4T5dK0c_8pZ76k5-N:-ND4T5dL6kHSV0zP0-ng:bas866a) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/bindings/pydrake/geometry_py_optimization.cc#L297)):*
> ```cpp
>       .def_readwrite("num_infeasible_samples",
>           &IrisOptions::num_infeasible_samples,
>           doc.IrisOptions.num_additional_constraint_infeasible_samples.doc)
> ```

minor: wrong doc string

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending open comments

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987#-:-ND4rge3CWrTQcHRy7Tk:b8ux4j9)* status: 8 unresolved discussions (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.cc` line 323 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND4ngiQ5Ly5SQYEEz4k:-ND4ngiRDCChySNh6IMn:bw0kk9s) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L323)):*
> ```cpp
> 
> // Defines a MathematicalProgram to solve the problem
> // min_q (q-d)*CᵀC(q-d)
> ```

nit: missing `*`, or could be `min_q (q−d)ᵀ CᵀC (q−d)`
(Same comment below)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987)* status: 5 unresolved discussions (waiting on @cohnt, @mpetersen94, and @sherm1)

___
*[`geometry/optimization/iris.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3dTb5A-iFU5LSxJvk:-ND4yaY_2OS-TXio9U2a:b-wrauu7) ([raw file](https://github.com/robotlocomotion/drake/blob/90d8b0d4c8eaaace6e44279db18ce2cf8c0396b9/geometry/optimization/iris.h#L55)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Is there anyway to add a deprecation to this option? Removing the actual ibex code that is run when this is true is the right move but having a warning when users try to set this might be better than their code throwing.
</blockquote></details>

I tried, but decided this was cleaner.  Having this method deprecated causes the pybind11 wrapper of the IrisOptions default constructor to squawk, in a way that was hard to disable.  And having the flag here but doing nothing was, I think, not a proper deprecation anyhow.
___
*[`geometry/optimization/iris.h` line 57 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND4SSV01lDjrp_OD_OG:-ND52TZZ1OVZyb9RBUYd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.h#L57)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW can this have a more specific name? There is an existing option `num_additional_constraint_infeasible_samples` which would seem to be included in the new option. Maybe `num_collision_infeasible_samples` ?
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.h` line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3gcoS6ILvuc4-p0pW:-ND530rt7bqD2ixqCs2h:bcfqcdv) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.h#L162)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

nit: Is there any benefit to allowing configurations that are in collision when the user doesn't require that the sample point is contained?
</blockquote></details>

i think we assume it in the code (e.g. that the initial small ellipse is feasible).  just discussed with Tommy, Tobia, and Alex, and we all think it's better to fail fast on this.
___
*[`geometry/optimization/iris.cc` line 484 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3frMcEuqm9S04TeaR:-ND53wUW7kM1z81Ps-lC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L484)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

I think this is a copy-paste mistake and should still be the `counter-example-constraint`
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 663 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3kJOs6FawxN7_xsUx:-ND59SFo8IuGRFbakpXV:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L663)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

There are no tests for this new error checking behavior. Consider adding a test that confirms behavior when a sample is passed that it outside joint limits, in collision, or violates additional constraints.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.cc` line 753 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3hwEj99vgGaWj2pyZ:-ND54_mGDk1LecQLXCBE:b-llwzr1) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.cc#L753)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Can this be moved up to right after the construction of `P` so that if the user passes a bad sample it fails almost immediately without any of the distance checking work?
</blockquote></details>

Done. (slightly differently) I meant for it to also check the (linear) additional constraints; but you made me realize that I missed updating P in that case.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987)* status: 6 unresolved discussions (waiting on @mpetersen94 and @RussTedrake)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND5KF-KCWYACeDR7Dp-):*
nit: commit message should say num_collision_infeasible_samples now

**Review by mpetersen94 — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17987)* status: 1 unresolved discussion (waiting on @RussTedrake)

___
*[`geometry/optimization/iris.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3dTb5A-iFU5LSxJvk:-ND5tMA8D2gotlf0I7hF:ba5k4r9) ([raw file](https://github.com/robotlocomotion/drake/blob/90d8b0d4c8eaaace6e44279db18ce2cf8c0396b9/geometry/optimization/iris.h#L55)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I tried, but decided this was cleaner.  Having this method deprecated causes the pybind11 wrapper of the IrisOptions default constructor to squawk, in a way that was hard to disable.  And having the flag here but doing nothing was, I think, not a proper deprecation anyhow.
</blockquote></details>

Got it. Marking resolved.
___
*[`geometry/optimization/iris.h` line 162 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3gcoS6ILvuc4-p0pW:-ND5t_8t99XaKEK8p3d7:b-bk5ip0) ([raw file](https://github.com/robotlocomotion/drake/blob/fa9ad34bbae6adeeb2331a8f4ca936635917ce1f/geometry/optimization/iris.h#L162)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think we assume it in the code (e.g. that the initial small ellipse is feasible).  just discussed with Tommy, Tobia, and Alex, and we all think it's better to fail fast on this.
</blockquote></details>

Works for me.

**Comment by mpetersen94** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-leak-sanitizer please

**Comment by jwnimmer-tri** [comment]
*[`geometry/optimization/iris.h` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17987#-ND3dTb5A-iFU5LSxJvk:-NDmuSSo4oHZqI4fZnBX:b-pdq0cj) ([raw file](https://github.com/robotlocomotion/drake/blob/90d8b0d4c8eaaace6e44279db18ce2cf8c0396b9/geometry/optimization/iris.h#L55)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

Got it. Marking resolved.
</blockquote></details>

Here's the alternative:

(1) Keep the flag intact here, as well as its bindings.
(2) Document it as deprecated.
(3) Do not try to use Python/C++ official language-level deprecation annotations, since apparently they were a headache.
(4) Within `IrisInConfigurationSpace`, still delete the code that calls ibex.  Instead, throw:

```c++
if (options.enable_ibex) {
  throw std::logic_error("enable_ibex is deprecated");
}
```

The key observation: deprecation is a function of our _release notes_, full stop -- we can deprecate things without using DRAKE_DEPRECATED.

That is minimal work for us.  The question is whether it adds any value for users.

This helps users in two cases:

(a) For C++ or Python users who were only ever _reading_ the value of `enable_ibex` (e.g. for logging), their program does not immediately break.  They have 3+ months to drop their logging.

(b) For C++ users who were _conditionally_ setting this flag, e.g.,

```c++
if (verify) {
  log()->info("Will verify...");
  iris_options.enable_ibex = true;
}
```

... their program will continue to compile, and they will only break in case they set their own `verify = true` somewhere.  This would minimize the impact.  "My code doesn't compile anymore" is a more major disruption than "a few tests stopped passing".

In the end, maybe it's unlikely that anyone would benefit from the alternative approach.

My main point is informational for the reviewer audience here: just because `DRAKE_DEPRECATED` is acting up is _not_ a sufficient reason to avoid doing a deprecation.

**Pull request merged**
