### PR TITLE
Use geval, allowing optimization of gradient-less systems

### PR DESCRIPTION
**Pull request by eric-wieser**
Would previously crash with `matlab:TooManyOutputs`

As mentioned in #1477

### CODE REVIEW

**Comment by eric-wieser** [comment]
Unfortunately, in my particular implementation, this gives the incessant warnings:

```
Warning: converting taylorvar to double even though it has non-zero
gradients.  gradient information will be lost! 
> In TaylorVar/double (line 47)
  In HolonomicDrive/rotorSpeeds (line 52)
  In HolonomicDrive/sodynamics (line 78)
  In SecondOrderSystem/dynamics (line 35)
  In CascadeSystem/dynamics (line 75)
  In geval (line 171)
```
Where the offending function is implemented as:

```
		function speeds = rotorSpeeds(obj, vel, omega)
			% get the wheel speeds needed to give the robot a certain
			% velocity in body space
			i = 1;
			speeds = zeros(length(obj.wheels), 1);
			for wheel = obj.wheels
				% r cross omega
				rotv = omega * [-wheel.pos(2); wheel.pos(1)];
				totalv = vel + rotv;

				% decompose into powered and unpowered direction
				vwheel = [wheel.driveDir wheel.slipDir] \ totalv;

				speeds(i) = vwheel(1) / wheel.r;
				i = i + 1;
			end
		end
```

**Comment by RussTedrake** [comment]
@mposa will have a strong opinion about this.  I believe we had this in there before and decided it was not worth the performance hit.

**Comment by eric-wieser** [comment]
Performance associated with getting the gradients, or with checking to see if they're already user-implemented?

**Comment by eric-wieser** [comment]
Darn, looks like the performance hit made some tests timeout

**Comment by RussTedrake** [comment]
I think we should close this one (without merging) because of the known performance hit.  
Or perhaps better -- add the geval lines commented out with a note about the performance issues.

**Comment by eric-wieser** [comment]
Perhaps a better fix here is a function `ensuregrads(sys, degree)` that takes a plant and emits a new one with `output`/`dynamics` functions that return at least `degree` values. This function would only be run once in the constructor, and would therefore only incur a performance hit if the gradients were missing in the first place (which is better than not running at all)

**Comment by RussTedrake** [comment]
That’s a bigger change.  And the reason it doesn’t happen automatically is because the generateGradients method will crap out for even relatively complicated systems.

The autodiff tools in C++ will fill in some of these gaps soon.  I’d wait on them before implementing something like this.

**Pull request closed without merging**
