### PR TITLE
Add output projection to pid controller

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
pr part of #6403.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6794)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@naveenoid for feature review. thanks!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-Kr2arMKhLaB-srghyfv:b-gjuu32)*

**Comment by siyuanfeng-tri** [comment]
cc @tristanthrush 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-Kr2awcnoBxFMqEKunwS:b-o2qf40)*

**Comment by naveenoid** [comment]
One pass done - a minor test request and some small bikeshedding.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6B2vZKJ0hWzEhxWPZ:-Kr6B2vZKJ0hWzEhxWP_:bfn8eup) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/pid_controller.h#L27)):*
> ```objc
>  * where `integral(q_d - q, dt)` is the integrated position error, and
>  * `P_output`
>  * is the output projection matrix.
> ```

BTW: Bikeshedding here but cant we just call them Pi and Po or P_i and P_o? Alternatively, P_y and P_x? Looks slightly ugly to mix a word in the suffix with otherwise normal symbols.

---

*[drake/systems/controllers/pid_controller.h, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6A5HDxqe0BQRGPy0x:-Kr6A5HDxqe0BQRGPy0y:bgxcq4r) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/pid_controller.h#L211)):*
> ```objc
>   // Projection matrix from full state to controlled state, whose size is
>   // num_controlled_q_ * 2 X num_full_state_.
>   const MatrixX<double> output_projection_;
> ```

BTW: Why not just call these P_output_ and P_input_?

---

*[drake/systems/controllers/test/pid_controller_test.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6AlNwV6559nnWT2id:-Kr6AlNwV6559nnWT2ie:b69egpw) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/test/pid_controller_test.cc#L191)):*
> ```cpp
>   MatrixX<double> P_output =
>       MatrixX<double>::Random(num_control, num_controlled_q);
> ```

I think there needs to be a EXPECT_ANY_THROW / DEATH test with misshapen P_input  or P_output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-Kr6BRGrwEEM48gNTybu:b-1wtzzh)*

**Comment by siyuanfeng-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 27 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6B2vZKJ0hWzEhxWPZ:-KrBCM3CRs_KmthSV04O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/pid_controller.h#L27)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Bikeshedding here but cant we just call them Pi and Po or P_i and P_o? Alternatively, P_y and P_x? Looks slightly ugly to mix a word in the suffix with otherwise normal symbols.
</blockquote></details>

Done.

---

*[drake/systems/controllers/pid_controller.h, line 211 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6A5HDxqe0BQRGPy0x:-KrBB3yLi0Zv7PACJX90:bx59beq) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/pid_controller.h#L211)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

BTW: Why not just call these P_output_ and P_input_?
</blockquote></details>

BTW i think. this is slightly more descriptive. 

---

*[drake/systems/controllers/test/pid_controller_test.cc, line 191 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-Kr6AlNwV6559nnWT2id:-KrBECem2Y1_cRi94DVa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b03fed361f3ccf4cc7a21e5b411e591b57ba900/drake/systems/controllers/test/pid_controller_test.cc#L191)):*
<details><summary><i>Previously, naveenoid (Naveen Kuppuswamy) wrote…</i></summary><blockquote>

I think there needs to be a EXPECT_ANY_THROW / DEATH test with misshapen P_input  or P_output.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794)*

**Comment by siyuanfeng-tri** [comment]
+@ericcousineau-tri for platform review. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrBLZQ64cFg37nwIgyr:bralfhj)*

**Comment by naveenoid** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrBPXR6haDUgdxsLjqb:bg7igkv)*

**Comment by EricCousineau-TRI** [comment]
The code and logic looks good, but I'm still concerned about the overall complexity that this feature is injecting.

Can we just delegate the projection / selection to something other than the PID controller?
It seems like a better mechanism would be to allow the user to select custom `Kp`, `Kd`, `Ki` matrices, which would give both selection and gain scaling, and provide utility mechanisms to generate a corresponding PID controller with those gains, so when debugging, a user doesn't think "crap! User A put their gains in all three matrices, user B put their gains in one of them, ...", etc.

Additionally, we could probably do some simple checks to ensure that the effective masking / permutation that can result from the gain matrices are synchronized (e.g., you don't mix `q_1` with `v_2`, etc.)

If we don't enforce unitary values in the projection matrices, then there's a whole lot of free space to mix the roles of the projection and gain matrices - which makes it even weirder if we can't change them at run-time (for stuff like task space / virtual constraints / feedback linearization projects).

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBd7Fh7LpwI3u5ig-R:-KrBd7FiXr6ksPYSKxE2:bohrbds) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L19)):*
> ```objc
> 
> /**
>  * Implements the PID controller. Given state `x = (q, v)`, desired state
> ```

Can we rename this to `x_input = (q_input, v_input)` (or `x_i = (q_i, v_i)`, but that may get confused with integral terms...)?
And mention that `x_d` corresponds to `x_c`?

---

*[drake/systems/controllers/pid_controller.h, line 26 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBaZiek507stczMreS:-KrBaZifZ1lFH9rd7OXL:b43zed0) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L26)):*
> ```objc
>  * </pre>
>  * where `integral(q_d - q, dt)` is the integrated position error, and
>  * `P_y`
> ```

BTW (1) extra line space, (2) can we mention that `P_y` projects from? Something like the rigid body notation, `P_YoYc`, where `Yc` represents the outputs corresponding to the controlled terms, `Xc`?

---

*[drake/systems/controllers/pid_controller.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdOt_ModMVsilHBZg:-KrBdOt_ModMVsilHBZh:b-bvx69n) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L30)):*
> ```objc
>  *
>  * This system has one continuous state which is the integral of position error,
>  * two input ports: estimated state `x_input` and desired state `x_d`, and one
> ```

I don't think that the PID controller should have any responsibility for estimated state vs. input state. Can we change this to `s/estimated/input/g`?

---

*[drake/systems/controllers/pid_controller.h, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBcEuMut2pxDTbo3Ks:-KrBcEuMut2pxDTbo3Kt:b-4sw8zy) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L31)):*
> ```objc
>  * This system has one continuous state which is the integral of position error,
>  * two input ports: estimated state `x_input` and desired state `x_d`, and one
>  * output port `y`. `x = P_x * x_input`, where `P_x` is the input
> ```

It seems like `P_XcXi` has wiggle room to screw things up if you don't synchronize `P_QcQi` with `P_VcVi` (where `P_XcXi = blkdiag(P_QcQi, P_VcVi)`).

Should the user just supply `P_QcQi` in this case, since this math requires that `v = qdot` anyways? (because the user can then do selection by zeroing out the corresponding gains in `Kp`).

---

*[drake/systems/controllers/pid_controller.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrB_iGd7sxDj192ZZYl:-KrB_iGd7sxDj192ZZYm:bcid28a) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L32)):*
> ```objc
>  * two input ports: estimated state `x_input` and desired state `x_d`, and one
>  * output port `y`. `x = P_x * x_input`, where `P_x` is the input
>  * projection matrix. Note that this class assumes |q| = |v|, |q_d| = |v_d|.
> ```

BTW Do we have a mention of `|x|` in our nomenclature, specifying that this is the cardinality and not the absolute value? And do we use `abs(x)` elsewhere when implying absolute value?

---

*[drake/systems/controllers/pid_controller.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdaKjIRnWfATR5Fc1:-KrBdaKjIRnWfATR5Fc2:b-xlrdrt) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L34)):*
> ```objc
>  * projection matrix. Note that this class assumes |q| = |v|, |q_d| = |v_d|.
>  * However, |q| does not have to equal to |q_d|. One use case for non-identity
>  * `P_x` and `P_yput` is to select a subset of state for feedback.
> ```

What is `P_yput`? Did you mean `P_y`?

---

*[drake/systems/controllers/pid_controller.h, line 98 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdooMReAkbIJelSBa:-KrBdooMReAkbIJelSBb:bvta6s3) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L98)):*
> ```objc
>    * @throws std::logic_error if any assumption is violated.
>    */
>   PidController(const MatrixX<double>& state_projection,
> ```

Just to reiterate, I'm not a huge fan of `P_x` on the whole state space, because that means the user could shoot themselves in the foot by mixing up different position and velocities if they permute stuff too much.

---

*[drake/systems/controllers/pid_controller.h, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBbiDrVxAc6JxmB-2e:-KrBbiDrVxAc6JxmB-2f:bryxgvx) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L217)):*
> ```objc
>   const MatrixX<double> state_projection_;
> 
>   // Projection matrix from full state to controlled state, whose size is
> ```

Copy pasta? `s/state/output/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrBe6ZCEigp1HXfwSdv:bjmbv0z)*

**Comment by EricCousineau-TRI** [comment]
Per f2f discussion, will accept the existing design as-is (still not a fan, but OK'ing it for now...)
Added a couple of more minor suggestions. PTAL.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 31 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBcEuMut2pxDTbo3Ks:-KrBuwogzqE0B-RNImpz:b-l4fvyf) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L31)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

It seems like `P_XcXi` has wiggle room to screw things up if you don't synchronize `P_QcQi` with `P_VcVi` (where `P_XcXi = blkdiag(P_QcQi, P_VcVi)`).

Should the user just supply `P_QcQi` in this case, since this math requires that `v = qdot` anyways? (because the user can then do selection by zeroing out the corresponding gains in `Kp`).
</blockquote></details>

Will create follow-up issue.

---

*[drake/systems/controllers/pid_controller.h, line 32 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrB_iGd7sxDj192ZZYl:-KrBvWIAiex0zDHC9vrn:bupbor9) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Do we have a mention of `|x|` in our nomenclature, specifying that this is the cardinality and not the absolute value? And do we use `abs(x)` elsewhere when implying absolute value?
</blockquote></details>

BTW To add to this, can there be a mention that `qdot` must be consistent `v` (unless somehow changed via the mappings)?
That is what the math in the comments and the source code implies.

---

*[drake/systems/controllers/pid_controller.h, line 98 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdooMReAkbIJelSBa:-KrBuoGcbO9sNhsRkq0x:b-bi48rp) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L98)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Just to reiterate, I'm not a huge fan of `P_x` on the whole state space, because that means the user could shoot themselves in the foot by mixing up different position and velocities if they permute stuff too much.
</blockquote></details>

Marking satisfied per f2f discussion. Will create separate issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrBuYElud2vqNeDJItC:b-gltf5h)*

**Comment by siyuanfeng-tri** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 19 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBd7Fh7LpwI3u5ig-R:-KrCGKDwMn8Chp9843tW:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can we rename this to `x_input = (q_input, v_input)` (or `x_i = (q_i, v_i)`, but that may get confused with integral terms...)?
And mention that `x_d` corresponds to `x_c`?
</blockquote></details>

Done.

---

*[drake/systems/controllers/pid_controller.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdOt_ModMVsilHBZg:-KrCGiFPQ_5R9Dy5Z39j:b7fs04w) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I don't think that the PID controller should have any responsibility for estimated state vs. input state. Can we change this to `s/estimated/input/g`?
</blockquote></details>

I like estimated better. Also this is inherented from state feedback controller. 

---

*[drake/systems/controllers/pid_controller.h, line 34 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdaKjIRnWfATR5Fc1:-KrCHHcI5ZQqaZ7YE3zr:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

What is `P_yput`? Did you mean `P_y`?
</blockquote></details>

Done.

---

*[drake/systems/controllers/pid_controller.h, line 217 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBbiDrVxAc6JxmB-2e:-KrCHr9VcWrr5elgbHwm:b-l4svnf) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L217)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Copy pasta? `s/state/output/`?
</blockquote></details>

rephrased. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:
+@soonho-tri for follow-up platform review, please.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/controllers/pid_controller.h, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrBdOt_ModMVsilHBZg:-KrCcpPUrpVywUmLJUfN:b-82oeh) ([raw file](https://github.com/robotlocomotion/drake/blob/3b5d5649bae8b92cad477755429ec54c5d77dd89/drake/systems/controllers/pid_controller.h#L30)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I like estimated better. Also this is inherented from state feedback controller. 
</blockquote></details>

Still seems that it's outside of the scope of the PID, and the state is input (could be anything, including measured, estimated, or synthetic state), but will mark as satisfied for bike sheddingness.

---

*[drake/systems/controllers/test/pid_controller_test.cc, line 212 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-KrCcYjCmdvHrt-2lEVl:-KrCcYjCmdvHrt-2lEVm:be8veho) ([raw file](https://github.com/robotlocomotion/drake/blob/213726cdbf0014704ba11a2b2e4df3c305d82cc3/drake/systems/controllers/test/pid_controller_test.cc#L212)):*
> ```cpp
>   auto output = dut.AllocateOutput(*context);
> 
>   VectorX<double> q = VectorX<double>::Random(num_full_q);
> ```

BTW These and other locals can be `const`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrCeVscT2cZi6leExaJ:b-2eqidf)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6794#-:-KrDvs3U5gR8Uu1PW9L0:bnfp4nl)*

**Pull request merged**
