### PR TITLE
Extend drake_install_libraries function

### PR DESCRIPTION
**Pull request by jamiesnape**
Now exports library targets to a file` drake-targets.cmake`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4345)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
:lgtm: ...using drake from the build directory is not supported, though? I guess since it's meant to only ever be built via the superbuild, that makes some sense...

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4345#-:-KY0GpmVl29QqT7zNsfR:b-3hwrp3)*

**Comment by jamiesnape** [comment]
+@david-german-tri for feature review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmake/install.cmake, line 35 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4345#-KY0mcamjgCLjLFxSxX_:-KY0mcanXtp3OBH_FyXW:b5dkhz4) ([raw file](https://github.com/robotlocomotion/drake/blob/5d9ff63079a89e179d6c0e565a82634ea46d393a/cmake/install.cmake#L35)):*
> ```CMake
>     COMPATIBILITY SameMajorVersion)
> 
>   install(EXPORT ${PROJECT_NAME}-targets
> ```

BTW, wow, this line does an awful lot of lifting.  The number of options to `install` is boggling in general.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4345#-:-KY0mklH1cz6IEHM-0st:bnfp4nl)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab please

**Pull request merged**
