### PR TITLE
Add handling for ipopt solver's STOP_AT_ACCEPTABLE_POINT result

### PR DESCRIPTION
**Pull request by jefesaurus**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by sammy-tri** [comment]
@drake-jenkins-bot retest this please

+@sammy-tri for feature review  (I think we want this change and it shouldn't have been left sitting for so long).  IPOPT appears to have a default setting for acceptable tolerance according to https://www.coin-or.org/Ipopt/documentation/node42.html so I suspect we might currently be claiming that IPOPT fails to find a solution when it actually is.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6413#-:-Ku-q06cuy47HR5Om2ko:b-n5nwlm)*

**Comment by jwnimmer-tri** [comment]
@sammy-tri ping; are you still working on this?

**Comment by sammy-tri** [comment]
It's on my list of stuff I'd like to look into...  at an extremely low priority.  The code is pretty bitrotted since we neglected to promptly review it when it was first proposed (sorry about that!).  If we're trying to clear out the PR backlog I'll close this and open an issue recording the first implementation for posterity.

With sincere apologies to @jefesaurus for the fact that this still hasn't gotten any real attention.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6413#-:-Kx9ZT3Ljo3tNlHIAcUO:b-7pvjvu)*

**Comment by jwnimmer-tri** [comment]
For clarity, my interest is (1) as platform reviewer of the day, that all non-TRI PRs have appropriate feature reviewer assignments, and (2) with my #6996 coming, PRs forked from master a while ago are going to have merge challenges.

**Comment by jwnimmer-tri** [comment]
I will re-ping, with the same questions and desires now.  @sammy-tri or @hongkai-dai does anyone want to rework this to get it into master?

**Comment by sammy-tri** [comment]
I've cloned the branch into my repo in case we want to pick this back up later.  I don't have the cycles to work it now if we want to close the PR.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413#-:-LEFG-mfBk74ZOlGByv4:bwnhxng)*

**Comment by jwnimmer-tri** [comment]
@hongkai-dai or @avalenzu are you interested in feature review?  With my platform reviewer hat on, I am trying to find an appropriate feature reviewer to start this off.

**Comment by avalenzu** [comment]
+@avalenzu for feature review.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413#-:-LEFatMj1pxlwDy8ONPk:b-bczhl9)*

**Comment by hongkai-dai** [comment]
+@hongkai-dai for feature review.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/solvers/test/ipopt_solver_test.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/6413#-LEFa9Rk2Y2VaZpXipaO:-LEFa9Rl4Tiss-ow9cD5:b-8eojc9) ([raw file](https://github.com/robotlocomotion/drake/blob/0e88715541d8db135090a581a07d39ed696c90c5/drake/solvers/test/ipopt_solver_test.cc#L54)):*
> ```cpp
>     // Parabola with minimum at (-1, 1) with some noise applied to the input so
>     // derivatives will be correctish but not easily followable to the minimum
>     auto noisy_x = (x + Vector1d::Random() * max_noise_ + Vector1d::Ones());
> ```

We do not allow this kind of random number in the test. It is better to use a definitive number.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413#-:-LEFa3lPBKug2sJSFHQJ:bl5ccwd)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/solvers/test/ipopt_solver_test.cc, line 54 at r1](https://reviewable.io/reviews/robotlocomotion/drake/6413#-LEFa9Rk2Y2VaZpXipaO:-LEFev_S-Ah6Sj8y4RFe:b-n6gnpb) ([raw file](https://github.com/robotlocomotion/drake/blob/0e88715541d8db135090a581a07d39ed696c90c5/drake/solvers/test/ipopt_solver_test.cc#L54)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We do not allow this kind of random number in the test. It is better to use a definitive number.
</blockquote></details>

Resolved this after a discussion with Andres.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413)*

**Comment by avalenzu** [comment]
This needs to be rebased onto master. @jefesaurus, are you still interested in pushing this in? If not I can take it the rest of the way. I'll let @hongkai-dai keep reviewer duties. -@avalenzu 

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6413#-:-LEFgOjR7QfwNGOOkqnR:bduv82f)*

**Comment by jwnimmer-tri** [comment]
@avalenzu given the lack of reply, it seems like this should move onto your plate.

**Comment by jwnimmer-tri** [comment]
Ping @avalenzu.

**Comment by avalenzu** [comment]
Thanks for the ping @jwnimmer-tri. I'll port this over to master.

**Comment by avalenzu** [comment]
Superseded by #10345.

**Pull request closed without merging**
