### PR TITLE
Mosek quadratic cost nonlinear constraint

### PR DESCRIPTION
**Pull request by hongkai-dai**
Some users encountered this https://stackoverflow.com/questions/61360928/sos-polynomial-with-drake-and-mosek-yields-error-code-1501.

It is kind of hard for the users to find out the cause for this failure. So we check it explicitly, that mosek doesn't support quadratic cost with nonlinear constraint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14129)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@russtedrake for both reviews please, thanks! (Since you answered that stackoverflow question).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14129#-:-MIAEpRk-IC1qwdO4O6m:bbo8ugk)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
On first read, I question whether the new log message would trigger each and every time we call `ChooseBestSolver`, even if some other solver was successfully solving the program.

My gut feeling is that if we want to explain to whether and why a program is compatible with one (or more) solver backends, we should have an API for that, not just gripe into the console log.  There could be a flavor of ChooseBestSolver that returns explanatory text, and Solve could pass that into MathematicalProgramResult as an error condition report in case there was no backend.

**Review by hongkai-dai — COMMENTED** [review]
> even if some other solver was successfully solving the program.

Currently none of our solver can solve a problem with quadratic cost and nonlinear conic constraint. Mathematically, this problem is better reformulated.

I am thinking about what is the best place to put this warning. Ideally I want to receive the warning in two cases
1. The user doesn't specify the solver, and calls `ChooseBestSolver`.
2. The user specifies the solver (Mosek/Gurobi etc).

My original plan was to add this warning to each solver (Mosek/Gurobi). But as you said, now calling `ChooseBestSolver` would trigger this warning message for multiple times. 

Would it solve the problem if I call `warn_once` instead of `warn`?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14129#-:-MIAKO6eA_t8WZRhipic:b-rpl4bo)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers (waiting on @RussTedrake)

**Comment by jwnimmer-tri** [comment]
What if we added an internal helper function to perform the check (and that returned true/false), and that helper embedded the warn-once, and the relevant solvers all called the helper function to identify this condition?  That way, we would warn at most once per process no matter which functions the user was calling.  I don't love it on principle, but as a band-aid it's probably the best we can do and is a fine step forward.

**Review by hongkai-dai — COMMENTED** [review]
I take it back. Gurobi can solve problem with quadratic cost and nonlinear constraint.

I will close this PR. I think the right solution is to write a function that converts the quadratic cost to a Lorentz cone constraint with slack variable, so that Mosek can solve the optimization problem. I will do that in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14129#-:-MIAWJ3R5ygbqefibJbb:bshv2q)* status: LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @RussTedrake)

**Pull request closed without merging**
