### PR TITLE
Make {Input,Output}PortDescriptor references stable.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4803)

### CODE REVIEW

**Comment by david-german-tri** [comment]
@sherm1 for both levels of review, following up on our conversation last week

Superbuild CI failures are pre-existing and unrelated.

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by sherm1** [comment]
Nice -- :lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4803#-:-Kahtxm2Ly-B7yVrCM7U:b-re6q)*

**Comment by david-german-tri** [comment]
@sammy-tri for platform review

**Comment by sammy-tri** [comment]
:lgtm: (not sure what's up with CI)

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4803#-:-Kai300ANXEuodPtU7xg:bbesf9f)*

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by david-german-tri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4803#-:-KanJGlLpoG3oxFpsNEG:b-qgwxgk)*

**Pull request merged**
