### PR TITLE
Add AffineSystem<T>::MakeAffineSystem

### LINKED ISSUE #6710: symbolic::Expression constructors for AffineSystem and LinearSystem
I was hoping to add an extra constructor to AffineSystem (and LinearSystem) that looks something like this:

```
  AffineSystem(const symbolic::Variables& state_vars, const symbolic::Variables& input_vars, const Eigen::Ref<const VectorX<symbolic::Expression>>& dynamics, const Eigen::Ref<const VectorX<symbolic::Expression>>& output, double time_period = 0.0)
```

I think this should be simple, but to do it, I need to extract the linear and constant parts of the expression.  I feel like I can get `A` , `B`, `C`, and `D` from calling `symbolic::Jacobian(dynamics,state_vars)`, but don't actually see an easy way to extract the constant terms (`get_constant_value` etc assume special cases).  I see `DecomposeLinearExpression` , but it's embedded in symbolic_extraction and special cased for the solvers use case.  I also need to `DRAKE_DEMAND` that the system is affine/linear in (only) the input variables.

What is the recommended API for this?  (any chance there is something simple enough to use in a delegating constructor)?  Thanks!

### PR DESCRIPTION
**Pull request by soonho-tri**
Related Issue #6710.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6739)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@russtedrake , feature-review please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-:-KqUJy--0TdyW9lLJHeC:bgni43s)*

**Comment by RussTedrake** [comment]
it's surprisingly complicated, but the feature is exactly as requested, and the tests look good.  minor typos, but otherwise :lgtm:

perhaps we want MakeLinearSystem also before closing #6710?  
thanks! 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/affine_system.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-KqUKCV5oZfIJZgQJaqv:-KqUKCV5oZfIJZgQJaqw:b-y0wq5y) ([raw file](https://github.com/robotlocomotion/drake/blob/665b9010550e93c120623665e7bff94700a6c2b7/drake/systems/primitives/affine_system.cc#L195)):*
> ```cpp
> void ThrowNonAffineError(const string& msg) {
>   throw runtime_error(
>       "DecomposeAffineSystem detects that an non-affine expression: " + msg +
> ```

"an" -> "a" .  

---

*[drake/systems/primitives/affine_system.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-KqUKV0zunc97CLFrRsv:-KqUKV0zunc97CLFrRsw:b-v700yi) ([raw file](https://github.com/robotlocomotion/drake/blob/665b9010550e93c120623665e7bff94700a6c2b7/drake/systems/primitives/affine_system.cc#L200)):*
> ```cpp
> 
> // A helper function for DecomposeAffineSystem. It finds the coefficient of the
> // monomial `m` in the `map` and fill `M(i)` with the value. If the monomial `m`
> ```

"fill" -> "fills"  (or "populates")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-:-KqULG_co-rk7wLVhYPA:bjwpqo0)*

**Comment by soonho-tri** [comment]
Thanks! +@sammy-tri , platform-review please.

> perhaps we want MakeLinearSystem also before closing #6710?

Yes (just modified the PR message). I'm working on a separate PR.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/primitives/affine_system.cc, line 195 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-KqUKCV5oZfIJZgQJaqv:-KqUMdjKlaT7Hx0sm4SA:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/665b9010550e93c120623665e7bff94700a6c2b7/drake/systems/primitives/affine_system.cc#L195)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"an" -> "a" .  
</blockquote></details>

Done.

---

*[drake/systems/primitives/affine_system.cc, line 200 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-KqUKV0zunc97CLFrRsv:-KqUMe_pVFku--OV1g18:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/665b9010550e93c120623665e7bff94700a6c2b7/drake/systems/primitives/affine_system.cc#L200)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

"fill" -> "fills"  (or "populates")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-:-KqULfRMsOJEtMywS0zU:b-5o9j4v)*

**Comment by sammy-tri** [comment]
Review started, though I may be sidetracked for a bit.  Will get to this today, though it may be a bit late.

---

Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-:-KqUNZrzluP8hek9yhJf:b3mh23k)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6739#-:-KqV-EWAjoplWGoMlGvh:bnfp4nl)*

**Pull request merged**
