### PR TITLE
pydrake: Begin to enforce clang-format

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
My premise is that, while code layout and whitespace _is_ important for `//pydrake/bindings` code readability, nitpicking it during code review is an inefficient way to enforce it.  At least for pydrake, I think its okay to accept whatever layout choices that clang-format suggests.  Here, I've reformatted the root package as an example, and added opt-in linter enforcement of clang-format idempotence.

If this PR is accepted, the plan is that we should opt-in to clang-format for all of the `//pydrake/bindings`.

Relates #4843.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9860)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for early feature review, please.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, please.

Platform reviewers @ggould-tri @SeanCurtis-TRI @sherm1 @soonho-tri @RussTedrake please speak up if you have strong feelings against requiring `clang-format` within `//bindings/pydrake/...`.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by jamiesnape** [comment]
> My only concern is that we're using two different versions of clang-format (clang-format 8.0.0 on mac and clang-format-6.0 on Ubuntu). A natural question is "what happens if the two do not agree on a formatting?".

I would say for now we should be fine. Most the changes to clang-format between versions are under the hood and they should be reasonably consistent. We run the same risk with compilers and with the python bindings for clang, so this is something we have been dealing with in various ways for a long time.

**Comment by jwnimmer-tri** [comment]
The macOS build was happy with this.

**Pull request merged**
