### PR TITLE
kcov_tool: Implement Bazel 5.3.1 compatibility

### PR DESCRIPTION
**Pull request by rpoyner-tri**
While all recent versions of bazel provide a zipfile archive of contents of $TEST_UNDECLARED_OUTPUTS_DIR, new versions are more aggressive about deleting the raw file trees in favor of the zipfile archive only.

Update kcov_tool to be able to find and clean kcov data in either file-tree form or zipfile archive form.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17992)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+(release notes: none) +@jwnimmer-tri for review -- sole review, if you like.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17992#-:-ND5TsFT6aKWU5qTJ-Mo:bnhlllq)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17992)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

___
*[`tools/dynamic_analysis/kcov_tool` line 24 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17992#-ND5fSo47DMfEtoAWAHY:-ND5fSo47DMfEtoAWAHZ:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/c7993cad96a435d1d2e69ba5e0f215e2ba4de191/tools/dynamic_analysis/kcov_tool#L24)):*
> ```
> def has_kcov_data(path):
>     """Returns True iff the supplied path contains kcov data, either in a
>     `kcov` subtree,  or in a bazel-constructed zip file."""
> ```

typo



_Suggestion:_
```
subtree, or
```
___
*[`tools/dynamic_analysis/kcov_tool` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17992#-ND5ge1L4yAp1evEfe9i:-ND5ge1L4yAp1evEfe9j:b-tpkamy) ([raw file](https://github.com/robotlocomotion/drake/blob/c7993cad96a435d1d2e69ba5e0f215e2ba4de191/tools/dynamic_analysis/kcov_tool#L64)):*
> ```
>     # consider re-running `install_prereqs.sh`.
>     cmd = ['zip', '-q', '-d', zip_path, 'kcov/*']
>     subprocess.run(cmd, check=True)
> ```

Perhaps it would be simplest here just to nuke the entire `outputs.zip` file, instead of updating it.  I wonder how much we care about preserving the non-kcov-related contents of `outputs.zip`.  Does anything go awry if we remove if in full?

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17992)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`tools/dynamic_analysis/kcov_tool` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17992#-ND5ge1L4yAp1evEfe9i:-ND8dVaF0FQDZjKYO3uO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c7993cad96a435d1d2e69ba5e0f215e2ba4de191/tools/dynamic_analysis/kcov_tool#L64)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

That was my first draft. I figured I would try the slightly fancier solution, to see how it went. :)

I think the stakes are low, because re-running the test will always regenerate the outputs. Let's try it and see.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
LGTM on the code.  I'll test it locally later this morning.  Let's also check CI:

@drake-jenkins-bot linux-focal-clang-bazel-experimental-coverage please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: both +(status: single reviewer ok) .

Tested locally with current-bazel 5.1.0 and it works fine.  I'll assume your testing of 5.3.1 was sufficient -- we'll double-check as part of the 5.3.1 upgrade anyway.

```
  git fetch upstream pull/17992/head && git checkout FETCH_HEAD
  git merge upstream/master 
  ./tools/dynamic_analysis/kcov_tool clean
  bazel test --config=kcov common:polynomial_test
  # Confirmed that it finds only polynomial test coverage data.

  ./tools/dynamic_analysis/kcov_tool merge bazel-kcov
  ./tools/dynamic_analysis/kcov_tool clean
  bazel test --config=kcov common:timer_test common:scope_exit_test
  ./tools/dynamic_analysis/kcov_tool merge bazel-kcov
  # Confirmed that it finds only scope_exit and timer test coverage data.
```


And hah!  I both _love_ and _hate_ that the example we give for https://drake.mit.edu/bazel.html#kcov (polynomial_test) has poor test coverage.  It's a great example of a coverage report with red/green/yellow lines, but wow those tests are really missing some important special cases!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17992#-:-ND9Iqfl-wmnBNpcGqYg:b-pnys)* status: :shipit: complete! all discussions resolved, LGTM from assignee jwnimmer-tri(platform) (waiting on @rpoyner-tri)

**Comment by rpoyner-tri** [comment]
And yet, that module has fairly good (statement) coverage in the all-tests-merged report in CI. Just another symptom of the long-distance test coverage that is widespread in Drake.

**Pull request merged**
