### PR TITLE
SpatialVector unary minus operator

### PR DESCRIPTION
**Pull request by amcastro-tri**
A little something I needed while doing math with spatial vectors.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8064)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@ericcousineau-tri for feature review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8064#-:-L5GQJJ5TxNKThypXygr:bvhsv4m)*

**Comment by amcastro-tri** [comment]
+@seancurtis-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8064#-:-L5K87SZH7D3waTuFIPu:b-tnzbcp)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8064#-:-L5KJlNWzitNhINUvZa0:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8064#-:-L5LjcP4v7Hd2czoNaIn:bmxilld)*

**Pull request merged**
