### PR TITLE
Use GTest::GTest and Threads::Threads imported targets from upstream CMake

### PR DESCRIPTION
**Pull request by jamiesnape**
CMake already sets up an imported target for Threads, so we do not need to create our own. Using `GTest::GTest` automatically adds `Threads::Threads` to those targets (as well as the appropriate include directory for GTest).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3748)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
Apparently some code was relying on GTest and Gurobi having the same include directory...

**Comment by jamiesnape** [comment]
+@david-german-tri for feature and platform review.

**Comment by david-german-tri** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/CMakeLists.txt, line 42 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/3748#-KTo3cvvoUayZEqEJmn6:-KTo3cvvoUayZEqEJmn7:b-1r3vcx) ([raw file](https://github.com/robotlocomotion/drake/blob/1130b546a3cbfcb5418848ca5c080e1daf7820ee/drake/common/test/CMakeLists.txt#L42)):*
> ```CMake
>   target_compile_options(drake_assert_test_disabled PRIVATE -UDRAKE_ENABLE_ASSERTS)
> endif()
> target_link_libraries(drake_assert_test_disabled drakeCommon ${GTEST_BOTH_LIBRARIES})
> ```

What's the rationale for all these substitutions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3748)*

**Comment by jamiesnape** [comment]
Reviewable does not seem to be working for me.

`${GTEST_BOTH_LIBRARIES}` are simply library names. `GTest:: GTest ` `GTest::Main` are CMake targets so they automatically set include paths and add any other required libraries (like Threads::Threads). Hence, we do not have to pass GTest include directories to every single target.

**Comment by jamiesnape** [comment]
Basically modern CMake versus old school CMake.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3748#-:-KToCJmIzTFm5O633Y4C:bnfp4nl)*

**Pull request merged**
