### PR TITLE
Upgrade Externals June 2023

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Toward #19511.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19536)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-everything-release please

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews per schedule, please.

**Review by rpoyner-tri — COMMENTED** [review]
Looks good, but needs to play the "rebase frogger" game. Good luck!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19536#-:-NXGSAKP87PjRpVU_rL3:b-6y6651)* status: when planning a "properly curated" merge commit the PR must always be rebased onto latest master (waiting on @mwoehlke-kitware)

**Comment by jwnimmer-tri** [comment]
Rebased, and forcing in now.

**Pull request merged**
