### PR TITLE
multibody: Move `rigid_body_tree` and `parsers` here.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is meant to reflect the C++ folder structure, and consolidate unittests (using simpler names).
This also revives tests of `PackageMap`, which were previously dead code.

This introduces `backwards_compatibility_py`, and renames `rbtree_shim_test` to `backwards_compatibility_test`, to accommodate a few more backwards compatibility tests.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7931)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@gizatt for feature review, please. Please let me know if these dates for deprecation are too soon; I can stretch them out if y'all don't wanna mess with renames two months from now.
+@soonho-tri for platform review, please.

\cc @manuelli @peteflorence @rdeits - Please also let me know if you'd like me to delay full deprecation further than 2 months from now.

Sorry, the Git Diff is not too friendly here; it's generally just some renames / deletions. Please let me know if you want a high-level overview.

Letter stats:
```
$ git diff $(git merge-base upstream/master HEAD) --name-status -M0.4
M       bindings/pydrake/BUILD.bazel
M       bindings/pydrake/all.py
M       bindings/pydrake/multibody/BUILD.bazel
M       bindings/pydrake/multibody/all.py
R092    bindings/pydrake/parsers_py.cc  bindings/pydrake/multibody/parsers_py.cc
M       bindings/pydrake/multibody/rigid_body_plant_py.cc
R097    bindings/pydrake/rbtree_py.cc   bindings/pydrake/multibody/rigid_body_tree_py.cc
A       bindings/pydrake/multibody/test/parsers_test.py
M       bindings/pydrake/multibody/test/rigid_body_plant_test.py
R049    bindings/pydrake/test/rbt_com_test.py   bindings/pydrake/multibody/test/rigid_body_tree_test.py
A       bindings/pydrake/parsers.py
M       bindings/pydrake/rbtree.py
M       bindings/pydrake/solvers/BUILD.bazel
M       bindings/pydrake/solvers/test/pr2_ik_test.py
M       bindings/pydrake/solvers/test/rbt_ik_test.py
M       bindings/pydrake/test/all_test.py
D       bindings/pydrake/test/atlas_constructor_test.py
A       bindings/pydrake/test/backwards_compatability_test.py
D       bindings/pydrake/test/package_map_test.py
D       bindings/pydrake/test/parsers_test.py
D       bindings/pydrake/test/rbt_transform_points_test.py
D       bindings/pydrake/test/rbtree_shim_test.py
M       bindings/pydrake/util/module_shim.py
M       doc/python_bindings.rst
```

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4JdZcFUnkSwbFQnmGS:b-hvfjwr)*

**Comment by manuelli** [comment]
I think this would mainly affect `director` code that uses `pydrake` for ik calls. Looking at the diffs it's hard to make sense of what exactly has changed. So I for one would appreciate a higher level overview. This would make it easier to see how major the necessary `director` changes are.

**Comment by gizatt** [comment]
:lgtm:, banking on it being mostly moving files around.

Wouldn't mind the deprecation dates being pushed out to after class ends, just in case it manages to bite someone. That'd be out at a pretty long 4 months, however. I don't think it'll be an issue if it poofs in the middle of class -- the written warnings, plus most of the software being curated by us, will help there.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4JiIU5yePy-Lz9bCVD:bgd8xdx)*

**Comment by EricCousineau-TRI** [comment]
Changed deprecation warning to start after the class ends, removal to follow 1.5 months after that.

At a high-level, there should be zero changes with the backwards-compatibility shims.

When the deprecation happens (now about 6 months away), `RigidBodyTree` (and related functions) will live in `pydrake.multibody.rigid_body_tree` rather than `pydrake.rbtree`, and `PackageMap` will live in `pydrake.multibody.parsers` rather than in both `pydrake.rbtree` and `pydrake.parsers`.

Note that both of these symbols live in the roll-up `pydrake.all` (`pydrake.multibody.all`), so if you wanted a simple short term fix, you could write `import pydrake.multibody.all as rbtree`, or write your own symbol import module for even fewer source changes.
Some of the enums would be scoped only under `FloatingBaseType`, e.g. you'd have to say `FloatingBaseType.kFixed` rather than just `kFixed`, per #4950.

And if it makes sense, the full removal could be pushed out further if it's more effort than it's worth (since the shims are simple and lightweight).

---

Review status: 23 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4JqHuyWXTDbwfpEuxV:b-kzsc6p)*

**Comment by soonho-tri** [comment]
:lgtm: (pending BTWs)

Tested on :apple: as well.

---

Reviewed 25 of 27 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/parsers.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MCR0R7IzOXAZpTX6A:-L4MCR0R7IzOXAZpTX6B:b-xnuyxa) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/parsers.py#L6)):*
> ```Python
> 
> # TODO(eric.cousineau): After the underactuated course is done, post a warning
> # that this module will be deprecated. After 1.5 months, remove the module.
> ```

BTW, I think using a specific date makes it easier to check in the future (i.e. `on March 17` instead of `After 1.5 Months`).

---

*[bindings/pydrake/rbtree.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MCvCJ_bLnKWT8dRmC:-L4MCvCKnQEE7zI43ZkA:boqs6sm) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/rbtree.py#L6)):*
> ```Python
> 
> # TODO(eric.cousineau): After the underactuated course is done, post a warning
> # that this module will be deprecated. After 1.5 months, remove the module.
> ```

BTW, ditto here about `after 1.5 months` 

---

*[bindings/pydrake/multibody/parsers_py.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MDF9XvnbIj4a74qsN:-L4MDF9XvnbIj4a74qsO:b-bvp9ho) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/multibody/parsers_py.cc#L15)):*
> ```cpp
> 
>   py::class_<PackageMap>(m, "PackageMap")
>     .def(py::init<>())
> ```

BTW, was it a bug?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4METtm1edR9BNfVDtB:b-3lwcwt)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[bindings/pydrake/parsers.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MCR0R7IzOXAZpTX6A:-L4NVcy4cv3iU0Z5Jwma:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/parsers.py#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think using a specific date makes it easier to check in the future (i.e. `on March 17` instead of `After 1.5 Months`).
</blockquote></details>

Done.

---

*[bindings/pydrake/rbtree.py, line 6 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MCvCJ_bLnKWT8dRmC:-L4NVe25_ZRs_82Mi6Um:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/rbtree.py#L6)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, ditto here about `after 1.5 months` 
</blockquote></details>

Done.

---

*[bindings/pydrake/multibody/parsers_py.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-L4MDF9XvnbIj4a74qsN:-L4NVfl3JqKpog0tShGt:b-xpn0qt) ([raw file](https://github.com/robotlocomotion/drake/blob/e05d30f0c684be66b2093d8b31e05ab81038f998/bindings/pydrake/multibody/parsers_py.cc#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, was it a bug?
</blockquote></details>

OK Yup. `init` should always take ownership of the returned value, so `py::return_value_policy::reference` is incorrect (though probably ignored by `pybind`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931)*

**Comment by EricCousineau-TRI** [comment]
Attempting to run automated tests from `spartan` Docker to see if this PR has any adverse effects. Ensured that `spartan/drake` points to this commit (`e05d30f`) in Docker image for the build.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4NVw_4oyQk5jbVytkH:b-72o1sm)*

**Comment by soonho-tri** [comment]
Reviewed 2 of 27 files at r1, 27 of 27 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931)*

**Comment by EricCousineau-TRI** [comment]
Ran off of Greg's branch of `spartan` (`f088b21`, PR 240) to run `python ./setup/docker/test_full_simulation_stack.py`, it terminated correctly. Going to merge in.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7931#-:-L4NlbSjH8LI3NAIcFLw:b9uxfmu)*

**Pull request merged**
