### PR TITLE
Move the definition of MathematicalProgram::Clone() to the header.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Fixes #7707.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7709)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-ubsan-everything please

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2MIsHfNT-9Ux8jdcPK:bpe5d2n)*

**Comment by hongkai-dai** [comment]
@m-chaturvedi for feature review, @ericcousineau-tri for both feature and platform review.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2MIxEkLdlRwOrPZ7gX:b8pfx4e)*

**Comment by EricCousineau-TRI** [comment]
Will comment once the `ubsan` checks are complete, so that we can see if these tests pass.
Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2MJffDk5T5AzsO3dV4:b-h1ew5t)*

**Comment by EricCousineau-TRI** [comment]
+@m-chaturvedi 
+@ericcousineau-tri 
(Using Reviewable-style assignment.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2MORes0fiGBRVIbrab:blgvn4n)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with minor (but blocking) nits. Nice!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-L2N_cSz9AoG0uFmjan4:-L2N_cSz9AoG0uFmjan5:brgtptn) ([raw file](https://github.com/robotlocomotion/drake/blob/03178efc383ba20fc5b7486d412846d4b237720b/solvers/mathematical_program.h#L313)):*
> ```objc
>    * solvers will be freshly constructed.
>    * @retval new_prog. The newly constructed mathematical program.
>    * I need to put the definition of this function in the header file, so that
> ```

Could you make this either (a) impersonal or (b) put your name next to it?

---

*[solvers/mathematical_program.h, line 318 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-L2N_lLliL8931EPF_uU:-L2N_lLliL8931EPF_uV:b88ieil) ([raw file](https://github.com/robotlocomotion/drake/blob/03178efc383ba20fc5b7486d412846d4b237720b/solvers/mathematical_program.h#L318)):*
> ```objc
>    */
>   virtual std::unique_ptr<MathematicalProgram> Clone() const {
>   // The constructor of MathematicalProgram will construct each solver. It also
> ```

Is this indentation correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2N_vmtueH1GXEqy--Y:b-pu1v23)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[solvers/mathematical_program.h, line 313 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-L2N_cSz9AoG0uFmjan4:-L2Nx4KNgukKVXaJiXrK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03178efc383ba20fc5b7486d412846d4b237720b/solvers/mathematical_program.h#L313)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Could you make this either (a) impersonal or (b) put your name next to it?
</blockquote></details>

Done.

---

*[solvers/mathematical_program.h, line 318 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-L2N_lLliL8931EPF_uU:-L2Nx8YNXHwXsFez9Z1A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/03178efc383ba20fc5b7486d412846d4b237720b/solvers/mathematical_program.h#L318)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Is this indentation correct?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709)*

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709#-:-L2QLdqE6Uwb1a_blvtf:bnfp4nl)*

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7709)*

**Pull request merged**
