### PR TITLE
Add drake_copyable requirement

### LINKED ISSUE #4861: Use common/drake_copyable pervasively
In #4780 and #4826, I introduced `common/drake_copyable.h` and used it in two subdirs.  We should likely use it even more pervasively.

My plan is to (slowly) convert most code to use it, and then once we have an empirical sense of how and where to use it, possibly turn it into a `code_style_guide` rule.

PRs from subsystem owners to convert their own code to use it are of course entirely welcome.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #4861.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5486)

### CODE REVIEW

**Comment by ggould-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-KfCN6Yi99fP90ZjFPEg:-KfCN6Yi99fP90ZjFPEh:b20wsp8) ([raw file](https://github.com/robotlocomotion/drake/blob/3e64db75ed12e2f8d71e927df3767412ac3a0bdd/drake/doc/code_style_guide.rst#L161)):*
> ```reStructuredText
>   base class).  Prefer to use ``drake/common/drake_copyable.h`` macros (either
>   ``DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN`` or
>   ``DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN`` whenever practical.  When not using
> ```

FYI missing close-paren

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfCO0AE4GzduMQISrba:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfCV37TBx1cBsKoGf_8:bg7igkv)*

**Comment by jwnimmer-tri** [comment]
+@sammy-tri +@david-german-tri for additional review.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfCWqyzdj6ebwWO7WOx:b-7pcwen)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/code_style_guide.rst, line 157 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-KfCXumceZklif1HkmLG:-KfCXumeXqKzzCJ3Slcd:bjq0foj) ([raw file](https://github.com/robotlocomotion/drake/blob/551a5ccc3bd5174e732ffa71ef0eceeb14e66841/drake/doc/code_style_guide.rst#L157)):*
> ```reStructuredText
> 
> * For the `Copyable and Movable Types <https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types>`_,
>   we clarify that the copy and move operations on a class must always be noted
> ```

BTW proposed rewording for clarity:

```
we clarify that a class must declare its own copy and move operations, and must not inherit the disposition of a base class.
````

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfCYEfwped10ioll5zc:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfCzPruCvKkM8iXqSq6:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@soonho-tri for a final look.

/CC @russtedrake if you want to weigh in.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfDbcgQerNGYQcxAnn_:b-zabdmv)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5486#-:-KfDdtqqBUlyv2wlC2kX:bnfp4nl)*

**Pull request merged**
