### PR TITLE
Minor documentation tweaks to extract_double.h.

### PR DESCRIPTION
**Pull request by liangfok**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5396)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for both levels of review please since I believe you were the original author.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5396#-:-KeJb62xN_C3vSCuU0DB:b-pqvjsz)*

**Comment by jwnimmer-tri** [comment]
The "as a" typo fix is good, but I'd prefer not to add the glottal stops everywhere.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5396#-:-KeJbRLndyuM9j0eBqS7:b-2fdndy)*

**Comment by liangfok** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5396#-:-KeJeU7GCeARBTPw_9Rn:b-896fix)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5396#-:-KeJechphCHewTG4KgdX:bnfp4nl)*

**Pull request merged**
