### PR TITLE
[examples] Move hydroelastic models to drake_models

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #13942.

Twin PR: https://github.com/RobotLocomotion/models/pull/57

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21244)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@DamrongGuoy for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-:-NuVlJ7a5NyU3nJqpkAn:b-feiw5h)* status: 1 unresolved discussion, LGTM missing from assignee DamrongGuoy, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuVlKlT9vWZigXFThT9:-NuVlKlT9vWZigXFThTA:b-ebd2w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/tools/workspace/drake_models/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "RobotLocomotion/models",
>         commit = "45c092654b1cd95b90d98f8c0b779250c27184ce",
> ```

Working

Needs real sha

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

I also ran the relevant examples and the tutorial to confirm.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-:-NuW5BAa79E-drPf_frs:b-sv6hdu)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: I didn't manually check the tutorial notebook. Trusting the feature reviewer and the author there.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-:-NuX-BBRAxMPEsSAcBUF:b-4q4zpa)* status: 3 unresolved discussions

___
*[`examples/hydroelastic/ball_plate/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuX-LwUBlha8Adm-o_r:-NuX-LwUBlha8Adm-o_s:b6306dw) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/examples/hydroelastic/ball_plate/BUILD.bazel#L11)):*
> ```Starlark
> 
> filegroup(
>     name = "models",
> ```

BTW, what's our convention for the `models` file group now? Is it just everything that's introduced in the subdirs of the dir containing the BUILD file?
___
*[`examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuWzqQvDneFLTLcKloC:-NuWzqQvDneFLTLcKloD:b8qdefh) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py#L41)):*
> ```Python
>     parser.AddModels(
>         url="package://drake_models/dishes/"
>             "evo_bowl.sdf")
> ```

nit the line break looks odd here. Not sure if intentional.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21244)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees DamrongGuoy,xuchenhan-tri(platform)

___
*[`examples/hydroelastic/ball_plate/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuX-LwUBlha8Adm-o_r:-NuX1Pe18RBNxuTxu2BK:bgc6i96) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/examples/hydroelastic/ball_plate/BUILD.bazel#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, what's our convention for the `models` file group now? Is it just everything that's introduced in the subdirs of the dir containing the BUILD file?
</blockquote></details>

Yeah, it probably deserves some clean-up.  The purpose of "models" group is "things that `bazel run //tools:model_visualizer` should be able to preview", i.e., for use by the `//:all_models` rollup.  Nominally that should be everything here, yes.  Anzu has a macro to help with this, which we should probably port up here to Drake.
___
*[`examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py` line 41 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuWzqQvDneFLTLcKloC:-NuX286E1UiBuQtSml6E:bat7oox) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit the line break looks odd here. Not sure if intentional.
</blockquote></details>

Yeah.  I was trying to keep all three lines similarity formatted, but that was probably the wrong choice. 
___
*[`tools/workspace/drake_models/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21244#-NuVlKlT9vWZigXFThT9:-NuX2Eh05wt9aF67md_u:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/f1c8303a23adde89fb97f3dbae825d37fb76b902/tools/workspace/drake_models/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Needs real sha
</blockquote></details>

Done

**Pull request merged**
