### PR TITLE
no-review [geometry] Hack to dump hydroelastic meshes to obj files when make contact.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
No review. Draft PR.

Use for discrete hydro paper.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15766)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
Rebased on draft PR #15833.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15766#-:-MkeE3w7EGrPDCa1VpUe:bi5kynu)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Comment by jwnimmer-tri** [comment]
@DamrongGuoy as I understand it, work on the paper has concluded.  Can we close this PR now?

**Review by DamrongGuoy — COMMENTED** [review]
Yes, I'll close it now.  It has so many merge conflicts already; I think.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15766#-:-MuwOs_W4461_3gSgaw_:bqf6zgq)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Review by DamrongGuoy — COMMENTED** [review]
On the other hand, the paper, as the situation unfolds, is not concluded yet due to comments from ICRA reviewers.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15766#-:-MuwP4-lAPhutLrgZwT2:b-oa6ky3)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

**Pull request closed without merging**
