### PR TITLE
Deprecate `--with-maintainer-only` install flag on macOS

### PR DESCRIPTION
**Pull request by williamjallen**
Closes https://github.com/RobotLocomotion/drake/issues/14754

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665)

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
+@jwnimmer-tri for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665#-:-NMjuPAS2zREirwKjBHA:b8qd208)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+(release notes: newly deprecated) 

:lgtm: feature review.

+@xuchenhan-tri for platform review per schedule, please.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665#-:-NMjwtocAeaLpa7mtbas:bg7m8nq)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri(platform) (waiting on @williamjallen and @xuchenhan-tri)

___
*[`setup/mac/install_prereqs.sh` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18665#-NMjxBS32FoWki52Cj0T:-NMjxBS32FoWki52Cj0U:b931wmd) ([raw file](https://github.com/RobotLocomotion/drake/blob/1bc540d32d829eb46664d21a3d79e12bd7b7a220/setup/mac/install_prereqs.sh#L15)):*
> ```Shell
>     # Maintainer-only tools are only supported on Ubuntu
>     --with-maintainer-only)
>       echo 'Warning: Maintainer-only tools are only supported on Ubuntu.  The "--with-maintainer-only" flag will do nothing.'
> ```

nit Here we should tell the user a drop-dead date where the flag will be removed entirely (which also serves as a reminder for us to finish the removal).

The new sentence to add to the end of this string would go something like "This flag will be removed from Drake on or after 2023-05-01."

(Every month, we grep for 2023-MM-01 and purge the the deprecated code.)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665#-:-NMjzJGlEJUdI8siWWv2:bnfp4nl)* status: 1 unresolved discussion (waiting on @williamjallen)

**Review by williamjallen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`setup/mac/install_prereqs.sh` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18665#-NMjxBS32FoWki52Cj0T:-NMk8GDQ2yKqLM3BHbYq:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake/blob/1bc540d32d829eb46664d21a3d79e12bd7b7a220/setup/mac/install_prereqs.sh#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Here we should tell the user a drop-dead date where the flag will be removed entirely (which also serves as a reminder for us to finish the removal).

The new sentence to add to the end of this string would go something like "This flag will be removed from Drake on or after 2023-05-01."

(Every month, we grep for 2023-MM-01 and purge the the deprecated code.)
</blockquote></details>

Done

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @williamjallen)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-x86-monterey-unprovisioned-clang-bazel-experimental-release please

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18665)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @williamjallen)

**Comment by jwnimmer-tri** [comment]
The macOS build got past `install_prereqs` just fine.  Squashing now.

**Pull request merged**
