### PR TITLE
[inverse_kinematics] Add OrientationCost

### PR DESCRIPTION
**Pull request by RussTedrake**
Towards #17507.  This is the second half of supporting GlobalIK's
AddPostureCost in the nonlinear IK toolchain.

+@hongkai-dai for feature review, please.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592)* status: 3 unresolved discussions, LGTM missing from assignee hongkai-dai, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @hongkai-dai and @RussTedrake)

___
*[`multibody/inverse_kinematics/orientation_cost.cc` line 75 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7H3D3ZE29jmYjiPnK4:-N7H3D3ZE29jmYjiPnK5:b-4n8sg6) ([raw file](https://github.com/robotlocomotion/drake/blob/4730d25e8bef065db4a09437464e62c7c5da923f/multibody/inverse_kinematics/orientation_cost.cc#L75)):*
> ```cpp
>   const T err = 1.0 + (R_AB.matrix().trace() - 1.0)/2.0;
>   if constexpr (std::is_same_v<T, S>) {
>     (*y)[0] = err;
> ```

I think the cost should multiply by `c` here? Same for the gradient computation below.
___
*[`multibody/inverse_kinematics/test/inverse_kinematics_test.cc` line 197 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7H3O3w4xk0wpahq_mV:-N7H3O3w4xk0wpahq_mW:bx1p0la) ([raw file](https://github.com/robotlocomotion/drake/blob/4730d25e8bef065db4a09437464e62c7c5da923f/multibody/inverse_kinematics/test/inverse_kinematics_test.cc#L197)):*
> ```cpp
>       math::wrap_to(R_AB.ToAngleAxis().angle(), -M_PI / 2.0, M_PI / 2.0);
>   EXPECT_NEAR(ik_.prog().EvalBindingAtInitialGuess(binding)[0],
>               1.0 - cos(theta), 1e-12);
> ```

Multiply the cost by `c`?
___
*[`multibody/inverse_kinematics/test/orientation_cost_test.cc` line 114 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7H3XQv8Qff_s7HxY02:-N7H3XQv8Qff_s7HxY03:bx1p0kt) ([raw file](https://github.com/robotlocomotion/drake/blob/4730d25e8bef065db4a09437464e62c7c5da923f/multibody/inverse_kinematics/test/orientation_cost_test.cc#L114)):*
> ```cpp
>       (X_WAbar.rotation() * R_AbarA).inverse() * X_WBbar.rotation() * R_BbarB;
>   theta = math::wrap_to(R_AB.ToAngleAxis().angle(), -M_PI/2.0, M_PI/2.0);
>   CheckCases(*cost, *cost_ad, q, 1.0 - cos(theta));
> ```

Multiply the cost by `c`.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: +@jwnimmer-tri for platform review please, thanks!

> Reviewed 1 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7ITlie2z66yhsjkUTV:bp0q8hr)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
I think the motivation for introducing PositionCost and OrientationCost is to allow InverseKinematics to specify the same cost as GlobalInverseKinematics, where we impose cost on position error and orientation error.

For the moment I don't plan to introduce more cost type to GlobalInverseKinematics. If I do, then we will need to add the same nonlinear cost to InverseKinematics. We will need to think about the right way to re-use the constraint evaluation in the cost code then.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7IYXaD7y0k2WS6YsXo:bmh79sf)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
That explains why we need costs _at all_.  I agree we need costs!

It doesn't explain why `PositionCost.Eval` can't be implemented by calling `PositionConstraint.Eval` and then dotting that with `C` (for example), instead of copy-pasting most of the intricate MbP implementation.

Maybe the cost math is different than the constraint math?  I didn't immediately see how, but I also didn't look extremely closely.  If the math is different, the comments across the two classes should point out the contrast specifically.

**Review by hongkai-dai — COMMENTED** [review]
The math is slightly different. In both OrientationConstraint and OrientationCost it computes 1 - cos(theta). In OrientationConstraint it multiplies this with a constant `c` as  c * (1 - cos(theta)).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7I_tFB2utZo742230X:buc59gm)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Right.  So `OrientationCost.Eval` is a one-liner: `y = c * OrientationConstraint.Eval(x)`.  Isn't that much simpler that copy-pasting all of the code?  If it were a function of some intermediate internal value it might make sense to re-implement, but if y_cost(x) is affine in y_constraint(x), why can't we just apply that final transformation in the Cost code as an extra step?

**Comment by jwnimmer-tri** [comment]
To be clear, my idea is something like this (in a broad outline):

```c++
class ConstraintPenaltyCost {
  /// Imposes the cost `y(x) = (z - foo.lb).dot(c)` where z is the constraint's value `foo(x)`.
  /// Only allowed for constraints with ub == lb (for now).
  ConstraintAsCost(Constraint foo, VectorXd c);
  /// Imposes the cost `y(x) = (z - foo.lb)ᵀ C (z-foo.lb)` where z is the constraint's value `foo(x)`.
  /// Only allowed for constraints with ub == lb (for now).
  ConstraintAsCost(Constraint foo, MatrixXd C);
};
```

That could be a standalone cost, or even a factory function on `solvers::Constraint` as in `constraint.ToCost(c)`.

**Review by RussTedrake — COMMENTED** [review]
I think that could be nice (I slightly dislike having to define lb and ub only to have them unused, but could get over it).  

But `the Eval function of OrientationCost (or PositionCost)` is only a very small handful of lines, and nothing complicated.  The mass of the PR is the setup of the class and test coverage.  I don't think this proposal helps with any of that?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7IuooG2EmW6N99upmo:b-px98an)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
All of the setup boilerplate and "should use autodiff" checks in the implementation goes away, along with all of the Eval helpers.  The only member variable is the wrapped Constraint object and `c` -- no plants nor contexts -- and all of the Eval bodies are the same two-liner (`wrapped.Eval(x, y); y *= c;`).

I care less about the volume of lines, and more that the mathematics are duplicated.  Running a diff from one cc file to the other shows a lot of differences, which I _think_ are mostly formatting rather than anything important?  But it's difficult to tell, and will be for the next maintainer as well.  I worry about fixing an arithmetic bug it only one class (but then forgetting the other).

If the math is supposed to be the same in both cases, it's still better to write down the math just once, even if the LOC with implementation re-use were net-zero.

**Comment by RussTedrake** [comment]
That's funny. From my perspective, I think we're more likely to have a bug introduced in the volume of lines than the few simple lines of math.  I'll go ahead and make the smaller version of your proposed change; it's simple enough.

**Comment by jwnimmer-tri** [comment]
I outlined my idea here, in case it helps: https://github.com/jwnimmer-tri/drake/commits/ik-cost-constraint-impl

**Review by RussTedrake — COMMENTED** [review]
Sorry.  I did my version before seeing that.  (They are similar).  PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7J241OABRSxJZo8F3A:b-k0ez70)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @hongkai-dai and @jwnimmer-tri)

**Comment by RussTedrake** [comment]
(if we like this, I can cleanup PositionCost tomorrow; there is one other change I want to make to that method anyhow)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 9 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592#-:-N7J6JmIAeZWpnqV9SOi:bnfp4nl)* status: 3 unresolved discussions (waiting on @RussTedrake)

___
*[`multibody/inverse_kinematics/inverse_kinematics.cc` line 44 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J4u8-A29LufWXY0P6:-N7J4u8-A29LufWXY0P7:bmglcsb) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/inverse_kinematics.cc#L44)):*
> ```cpp
>                                     plant.GetPositionUpperLimits(), q_);
>   }
>   AddUnitQuaternionConstraintOnPlant(plant, q_, prog_.get());
> ```

If I revert this change, no unit tests in this directory fail.
___
*[`multibody/inverse_kinematics/orientation_cost.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J43Qr1nXpa9lkTV-4:-N7J43Qr1nXpa9lkTV-5:b5kdwaz) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/orientation_cost.cc#L15)):*
> ```cpp
> 
> template <typename T>
> systems::Context<T>* ContextOrThrow(
> ```

nit As future work (maybe a TODO?), RefFromPtrOrThrow should accept two string arguments -- the name of the calling function, and the name of the variable.  Then we can use that one helper everywhere in this folder, instead of having this extra boilerplate.
___
*[`multibody/inverse_kinematics/test/orientation_cost_test.cc` line 106 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J62YE4ojOBby3OD4Y:-N7J62YE4ojOBby3OD4Z:b-ykqqyw) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/test/orientation_cost_test.cc#L106)):*
> ```cpp
>   // X_WA, X_WB are arbitrary non-identity transforms.
>   RigidTransform<double> X_WAbar(RollPitchYaw<double>(0.32, -0.24, -0.51),
>                               Vector3d(0.1, 0.3, 0.72));
> ```

nit Wrong indentation -- align with the prior function argument.

Ditto immediately below.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`multibody/inverse_kinematics/inverse_kinematics.cc` line 44 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J4u8-A29LufWXY0P6:-N7KmMeq0cdP-y1eyETz:b-9zhgv1) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/inverse_kinematics.cc#L44)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If I revert this change, no unit tests in this directory fail.
</blockquote></details>

Done. I've added a test.
___
*[`multibody/inverse_kinematics/orientation_cost.cc` line 15 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J43Qr1nXpa9lkTV-4:-N7KnCKW7i_xd0OEeA24:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/orientation_cost.cc#L15)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit As future work (maybe a TODO?), RefFromPtrOrThrow should accept two string arguments -- the name of the calling function, and the name of the variable.  Then we can use that one helper everywhere in this folder, instead of having this extra boilerplate.
</blockquote></details>

Done.
___
*[`multibody/inverse_kinematics/test/orientation_cost_test.cc` line 106 at r3](https://reviewable.io/reviews/robotlocomotion/drake/17592#-N7J62YE4ojOBby3OD4Y:-N7KnLOM0EGNJUCAQ2Lb:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2db19cca655ba1c045a06a3edf262ad51a115c13/multibody/inverse_kinematics/test/orientation_cost_test.cc#L106)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Wrong indentation -- align with the prior function argument.

Ditto immediately below.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17592)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),hongkai-dai (waiting on @RussTedrake)

**Pull request merged**
