### PR TITLE
Bring tinygltf in as a dependency

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
It vendors the header and does a minimal smoke test in RenderEngineGl's unit tests.

In addition to vendoring:
  - we redirect tinygltf to use Drake's vendored  json library.
  - We change the callback declaration from a C-style function pointer to a std::function to allow a callback with captures.

Relates #20185.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
+(release notes: feature) 

To see how this inevitably gets used, see #21520.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@jwnimmer-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-:-Nz_CoiS4wlNEKnrtTUg:b-qf68jg)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: feature.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-:-NzdZ8ln4WpIAgOIWsYE:b-n37teh)* status: 3 unresolved discussions, needs at least two assigned reviewers

___
*[`tools/workspace/tinygltf_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdX9JI6sacH2t_ZV7t:-NzdX9JJEKkI_X86ganX:bvfz7qb) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/repository.bzl#L9)):*
> ```Starlark
>         name = name,
>         repository = "syoyo/tinygltf",
>         commit = "e0b393c6958c0a7cbe134a240fad7915aae53db3",
> ```

When possible, we prefer numbered releases instead of git sha.  Are we able to use `v2.8.22` here, and do we ancitipate upstream release tags to appear on a frequent enough basis to suit us?
___
*[`tools/workspace/tinygltf_internal/patches/function_pointer.patch` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdYg-F5VZVsHbZSkMm:-NzdYg-F5VZVsHbZSkMn:b-yx9fxo) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/function_pointer.patch#L6)):*
> ```Diff
> This doesn't bind *all* function pointer typedefs, just the ones that Drake
> cares about. We should consider replacing all function pointers and submitting
> an upstream patch.
> ```

BTW Yes, please add this to the overall issue's checklist.  I'd like us to submit this patch (or an improved version) upstream while it's still fresh in our heads.
___
*[`tools/workspace/tinygltf_internal/patches/vendor.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdZ-aH7ZhRdgerWDZ3:-NzdZ-aH7ZhRdgerWDZ4:bbgfjs8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/vendor.patch#L1)):*
> ```Diff
> Add vendoring namespace.
> ```

BTW Does our `cc_library_vendored(` choke on this file?  If that's the reason we're writing out the patch manually, we should probably say so in a comment here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-:-Nzi1Fjs-vI6A2yaZWYx:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/tinygltf_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdX9JI6sacH2t_ZV7t:-Nzhj3Fp22PX9nb67bC4:b7qbjl9) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When possible, we prefer numbered releases instead of git sha.  Are we able to use `v2.8.22` here, and do we ancitipate upstream release tags to appear on a frequent enough basis to suit us?
</blockquote></details>

Done

On the basis he's put out ten releases in the last year (with the most recent being just two weeks ago), it seems it's under lively development. 
___
*[`tools/workspace/tinygltf_internal/patches/function_pointer.patch` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdYg-F5VZVsHbZSkMm:-Nzi0f-H4rebK4OmFn1m:b77305m) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/function_pointer.patch#L6)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Yes, please add this to the overall issue's checklist.  I'd like us to submit this patch (or an improved version) upstream while it's still fresh in our heads.
</blockquote></details>

I've updated the issue and submitted the PR to tinygltf.
___
*[`tools/workspace/tinygltf_internal/patches/vendor.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdZ-aH7ZhRdgerWDZ3:-NzhliHW-G6zbdylhs8U:b-1xz25y) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/vendor.patch#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Does our `cc_library_vendored(` choke on this file?  If that's the reason we're writing out the patch manually, we should probably say so in a comment here.
</blockquote></details>

I hadn't been aware of it.  :) Cargo culted from the wrong thing.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/tinygltf_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdX9JI6sacH2t_ZV7t:-Nzi1zNSC_dzr6LeAnE7:bgjwgp8) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/repository.bzl#L9)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

On the basis he's put out ten releases in the last year (with the most recent being just two weeks ago), it seems it's under lively development.
</blockquote></details>

Ah good, thanks.  (I hadn't actually looked; those were just the stock questions about whether to use tags vs head.)
___
*[`tools/workspace/tinygltf_internal/patches/vendor.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdZ-aH7ZhRdgerWDZ3:-Nzi1uJj19Sw5AN72UBo:b-6aqm16) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/vendor.patch#L1)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I hadn't been aware of it.  :) Cargo culted from the wrong thing.
</blockquote></details>

Sorry :(

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521)* status: LGTM missing from assignee rpoyner-tri(platform)

___
*[`tools/workspace/tinygltf_internal/repository.bzl` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdX9JI6sacH2t_ZV7t:-Nzi3F6y350ZPRefP_pr:bmcy6r7) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/repository.bzl#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah good, thanks.  (I hadn't actually looked; those were just the stock questions about whether to use tags vs head.)
</blockquote></details>

No worries. I hadn't thought of looking at the releases *at all*. So, this was a helpful exercise all around.
___
*[`tools/workspace/tinygltf_internal/patches/vendor.patch` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-NzdZ-aH7ZhRdgerWDZ3:-Nzi3KIz1YlXD_aq21Ei:b-vxxg9k) ([raw file](https://github.com/RobotLocomotion/drake/blob/f16f8fc946decc6776fd848cf832b7cd0ccf544b/tools/workspace/tinygltf_internal/patches/vendor.patch#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Sorry :(
</blockquote></details>

No apologies necessary. Again, I learned. The tricky bit was injecting tinygltf into the visibility list for the vendor tool. The message was a *bit* confusing because we have a build target `vendor_cxx` *and* `vendor_cxx.bzl` and `vendor_cxx.py` (which is associated with the build target). I wasted a few minutes wondering why `vendor_cxx.bzl` had visibliity settings.  :-/

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21521#-:-NziNSb8CczvoX_YH-BF:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),jwnimmer-tri(platform)

**Pull request merged**
