### PR TITLE
[drake_visualizer] Fix message handling in hydro visualization

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16867)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
Bug reported in TRI Slack
Locally tested that the patch fixes the error.

+@damrongguoy for feature review.
+@ericcousineau-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16867#-:-Myxq7AWD3sl9FBh9kF3:bvx08rm)* status: LGTM missing from assignees DamrongGuoy,EricCousineau-TRI(platform), missing label for release notes (waiting on @DamrongGuoy and @EricCousineau-TRI)

**Review by DamrongGuoy — COMMENTED** [review]
It looks good on my Puget now.  :lgtm: 

Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16867#-:-MyxrZJnCp4keg6LZKqv:b-6m39lh)* status: LGTM missing from assignee EricCousineau-TRI(platform), missing label for release notes (waiting on @DamrongGuoy and @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
@xuchenhan-tri If you can, you may want to scrub the TRI-internal link above. I've tried in GitHub.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: platform!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16867#-:-MyxrrURBCwtMpXHsk6j:b-50cww5)* status: missing label for release notes (waiting on @DamrongGuoy)

**Review by xuchenhan-tri — COMMENTED** [review]
@ericcousineau-tri I don't think reviewable allows comment editing just yet. See https://github.com/Reviewable/Reviewable/issues/836

OTOH, the link should be safe since only reader with credentials can read the internal slack message?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16867#-:-Myy-E-G64BbAhmBuu5I:b-da3oqy)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),DamrongGuoy

**Comment by EricCousineau-TRI** [comment]
Yes, there are access restrictions, but it'd be best to try and "trim the graph" tracing back to internal TRI resources.

**Pull request merged**
