### PR TITLE
Add initialization mechanism as event handling.

### PR DESCRIPTION
**Pull request by siyuanfeng-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7397)

### CODE REVIEW

**Comment by siyuanfeng-tri** [comment]
+@seancurtis-tri for feature, +@sherm1 for platform. thanks guys.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-Kxx0_vLq-2CxCLrOI0y:b2lme08)*

**Comment by SeanCurtis-TRI** [comment]
Very clean.  Two small things (and one vague thing that doesn't require a response).

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxDTQjOoLiJfYsPGGo:-KxxDTQjOoLiJfYsPGGp:b-jkx2d) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
> ```cpp
>   if (enable_playback) log_.reset(new SignalLog<double>(vector_size));
> 
>   PublishEvent<double> init_event(
> ```

FYI For the record, I'm not a big fan of this particular implementation. I don't like the fact that `DoPublish` has to distinguish between an initialization and update on *every* call. This seems to under-utilize the basic functionality (e.g., providing a callback to the `PublishEvent`).

In an ideal world, the periodic publish event should have a callback that simply sends an update message. The initialize publish event would have a callback that simply sends an update message, and `DoPublish()` should be the `LeafSystem::DoPublish()` implementation.

The only reason we *don't*/*can't* do that right now is because we don't have an interface for declaring a periodic publish event that supports specifying a callback. 

I'm not asking you to add this. This is largely just a case of me going on the record. :)

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxD4WlMHaP79HbV87h:-KxxD4WlMHaP79HbV87i:b-thie03) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L119)):*
> ```cpp
>     const Context<double>& context,
>     const std::vector<const PublishEvent<double>*>& event) const {
>   if (event.size() == 1 && event.front()->get_trigger_type() ==
> ```

BTW The logic underlying this test could use some explanation. If *either* of these conditions are false we blindly proceed with an update message. It doesn't seem obvious why both tests are necessary. A note in the code explaining the reasoning would prevent future coders from wasting time trying to convince themselves that this is the right test.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 515 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxEj8i3_ZVVOwv5g_w:-KxxEj8i3_ZVVOwv5g_x:b-hqexr5) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L515)):*
> ```cpp
>   drake::systems::Simulator<double> simulator(dut, std::move(context));
>   simulator.set_publish_every_time_step(false);
>   simulator.Initialize();
> ```

BTW As a result of this invocation, we should expect that an lcm message has been broadcast. I would expect to see something akin to `lcm.DecodeLastPublishedMessageAs()` being called here to confirm that has happened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KxxF-bPzH2VRLCM19Y3:byihxxm)*

**Comment by SeanCurtis-TRI** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxDTQjOoLiJfYsPGGo:-KxxFP7s9s1JieIxlUQH:b-qx6j5r) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI For the record, I'm not a big fan of this particular implementation. I don't like the fact that `DoPublish` has to distinguish between an initialization and update on *every* call. This seems to under-utilize the basic functionality (e.g., providing a callback to the `PublishEvent`).

In an ideal world, the periodic publish event should have a callback that simply sends an update message. The initialize publish event would have a callback that simply sends an update message, and `DoPublish()` should be the `LeafSystem::DoPublish()` implementation.

The only reason we *don't*/*can't* do that right now is because we don't have an interface for declaring a periodic publish event that supports specifying a callback. 

I'm not asking you to add this. This is largely just a case of me going on the record. :)
</blockquote></details>

I just realized the alternative is to modify `DrakeVisualizer::set_publish_period()` to explicitly call `LeafSystem::DeclarePeriodicEvent<PublishEvent<T>>(period, 0, callback);` instead of using the convenience method it currently uses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397)*

**Comment by siyuanfeng-tri** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxDTQjOoLiJfYsPGGo:-KxxJAejmiFT-YgXNHS8:b-nflpn3) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I just realized the alternative is to modify `DrakeVisualizer::set_publish_period()` to explicitly call `LeafSystem::DeclarePeriodicEvent<PublishEvent<T>>(period, 0, callback);` instead of using the convenience method it currently uses.
</blockquote></details>

I agree with everything you just said. The reason I sort of hacked it here is to minimize the impact on the public API change.
The basic problem is that by override DoPublish, we effectively specified a default publish behavior for every trigger type. Instead, what we should have done is to explicitly specify callbacks for each relevant trigger type, e.g. have kForced, kPeriodic, kPerStep all call the same default publish 1 draw message. And to do this, I might need to touch a lot of the application code to specify if they want per step publish or periodic. So I am saving this for the next pr. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397)*

**Comment by SeanCurtis-TRI** [comment]
+(status: curate commits before merging) 
:LGTM:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 30 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxDTQjOoLiJfYsPGGo:-KxxYHG1WWRWldYkdDJ3:bsuc6u1) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L30)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

I agree with everything you just said. The reason I sort of hacked it here is to minimize the impact on the public API change.
The basic problem is that by override DoPublish, we effectively specified a default publish behavior for every trigger type. Instead, what we should have done is to explicitly specify callbacks for each relevant trigger type, e.g. have kForced, kPeriodic, kPerStep all call the same default publish 1 draw message. And to do this, I might need to touch a lot of the application code to specify if they want per step publish or periodic. So I am saving this for the next pr. 

</blockquote></details>

FYI My final comment is that we could have callbacks *without* touching the public API in anyway.  Nevertheless, I accept the TODO as an acceptable solution.

---

*[drake/multibody/rigid_body_plant/drake_visualizer.cc, line 119 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxD4WlMHaP79HbV87h:-KxxY1sozQOfoAlpIWFI:b-t4yill) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/drake_visualizer.cc#L119)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW The logic underlying this test could use some explanation. If *either* of these conditions are false we blindly proceed with an update message. It doesn't seem obvious why both tests are necessary. A note in the code explaining the reasoning would prevent future coders from wasting time trying to convince themselves that this is the right test.
</blockquote></details>

BTW Thanks for the comment. I'm still not blissful about it, but I'm not going to sweat any other niggling details because:

1) It'd be subsumed by the other todo you added about switching to callbacks,
2) This isn't a particularly long-lived; MBT and GeometryWorld will supplant this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KxxYR4j9AshXpdObtcj:byqq853)*

**Comment by jwnimmer-tri** [comment]
This PR touches simulator.h, system.h, leaf_system.h, and diagram.h, but only touches leaf_system_test.cc?  Surely at least some of the other components (probably all) should have unit tests added?

**Comment by siyuanfeng-tri** [comment]
+@soonho-tri for platform review. 

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc, line 515 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KxxEj8i3_ZVVOwv5g_w:-KxxZxndvIb8nUc2-Hvv:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e342fdf83278e2f58a4d2b0427dca216113e1cb7/drake/multibody/rigid_body_plant/test/drake_visualizer_test.cc#L515)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As a result of this invocation, we should expect that an lcm message has been broadcast. I would expect to see something akin to `lcm.DecodeLastPublishedMessageAs()` being called here to confirm that has happened.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-Kxxv40dX9A_HmK2EWYK:b-ephv9i)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-cmake-experimental please
@drake-jenkins-bot linux-xenial-gcc-cmake-experimental-matlab please

**Comment by SeanCurtis-TRI** [comment]
Did you still mean to have @sherm1 as platform reviewer as well?

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-Kxy3B9aHwgijwyraVVI:b8aqkxi)*

**Comment by soonho-tri** [comment]
@seancurtis-tri , could you check if @sherm1 is on it?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-Kxy7rOBq2-NqIvjOzhe:bkfltb6)*

**Comment by siyuanfeng-tri** [comment]
-@soonho-tri my apologies. Sherm should do this one. I must have been half awake. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KxyAUc4i_62tDlTV2Tc:b2yatp6)*

**Comment by soonho-tri** [comment]
Not a problem.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KxyCB2zwswYAot6Hc3d:b-3muwgw)*

**Comment by sherm1** [comment]
I'm on it @siyuanfeng-tri, just slow.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KxyS5QUcoe9_ZMToTVn:b-au1f3c)*

**Comment by sherm1** [comment]
Awesome! Thanks, @siyuanfeng-tri. Platform :lgtm:, one trivial BTW.

---

Reviewed 5 of 9 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/systems/framework/system.h, line 666 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KyE73lBwAc3YlvAjAGK:-KyE73lBwAc3YlvAjAGL:bg1ydh9) ([raw file](https://github.com/robotlocomotion/drake/blob/207a7ce4049691fada6a6ad7ab79050c5eb245ba/drake/systems/framework/system.h#L666)):*
> ```objc
>   /// @p events cannot be null. @p events will be cleared on entry.
>   void GetInitializationEvents(const Context<T>& context,
>                         CompositeEventCollection<T>* events) const {
> ```

BTW odd indent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-:-KyE9VOZm6bdp-Jp_CAh:b-sw6y4m)*

**Comment by siyuanfeng-tri** [comment]
Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/framework/system.h, line 666 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/7397#-KyE73lBwAc3YlvAjAGK:-KyGLTxbw78HNeu4g7VK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/207a7ce4049691fada6a6ad7ab79050c5eb245ba/drake/systems/framework/system.h#L666)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW odd indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7397)*

**Pull request merged**
