### PR TITLE
Fix rotation_constraint_test

### PR DESCRIPTION
**Pull request by soonho-tri**
Reference: https://eigen.tuxfamily.org/dox/TopicPitfalls.html

Related: https://github.com/RobotLocomotion/drake/pull/6172

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6299)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@m-chaturvedi feature-review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6299#-:-Km8g3EzwR1gg4Ee8NvK:b-mddmik)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-gcc-bazel-experimental-everything please

**Comment by m-chaturvedi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6299#-:-Km8oayDMGZVC2Ll5Zo2:bnfp4nl)*

**Comment by soonho-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-experimental-memcheck-valgrind please

**Comment by m-chaturvedi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6299)*

**Comment by soonho-tri** [comment]
https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-memcheck-valgrind/16/

1. `linux-xenial-gcc-experimental-memcheck-valgrind` has failures but they are not related to `rotation_constraint_test` test.
    ```
    21:03:35 	 74 - global_inverse_kinematics_reachable_test (Timeout)
    21:03:35 	178 - lcm_driven_loop_test (Failed)
    ```

2. `rotation_constraint_test` is not triggered in `linux-xenial-gcc-experimental-memcheck-valgrind`.

    ```
    -- Not running rotation_constraint_test because large tests are not enabled
    ```

**Comment by jwnimmer-tri** [comment]
> rotation_constraint_test is not triggered in linux-xenial-gcc-experimental-memcheck-valgrind.

If you launch it from the jenkins UI instead of the chatbot, it will run the `large` tests.

**Comment by soonho-tri** [comment]
I launched it using Build with Parameters (`sha1=pr/6299/head`). But I have an error:

```
(pending—Jenkins doesn’t have label linux_xenial_experimental;
drake-linux-trusty-i-2017-05-29-c4.8xlarge (i-0bcc0e138b05bbe27) 
doesn’t have label linux_xenial_experimental; 
drake-linux-xenial-i-2017-05-29-c4.8xlarge (i-02df2f2306eb192b6) is offline)
```
It seems that I need to turn on https://drake-jenkins.csail.mit.edu/computer/drake-linux-xenial-i-2017-05-29-c4.8xlarge%20(i-02df2f2306eb192b6)/ but how?

**Comment by jwnimmer-tri** [comment]
There shouldn't be any additional action required.  Perhaps just retry?  Sometimes the builders just flake out.  Or else we can discuss on slack.

**Comment by soonho-tri** [comment]
@jwnimmer-tri : You're right. It's on now and build 18 is running!

**Comment by soonho-tri** [comment]
Just checked https://drake-jenkins.csail.mit.edu/job/linux-xenial-gcc-experimental-memcheck-valgrind/18:

```
288/291 MemCheck #142: rotation_constraint_test .............................   Passed  4653.77 sec
```

@m-chaturvedi , do you think we're good to go?

+@jwnimmer-tri , platform-review please. It's one-line change that you suggested.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6299#-:-KmChs1a7SVcTStz3YyH:b-5caa3k)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6299#-:-KmCiNzzsjkuho95BU2J:bnfp4nl)*

**Comment by soonho-tri** [comment]
@m-chaturvedi , just merged it. Let me know if you think there's more things to fix regarding this test.

**Pull request merged**
