### PR TITLE
Estimate velocity for LCM controlled iiwa

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4919)

### CODE REVIEW

**Comment by sammy-tri** [comment]
+@siyuanfeng-tri for feature review (and shout out to @naveenoid who may have some interest)

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-KbQuBHlWIam9NWmbeWn:bgs46ta)*

**Comment by siyuanfeng-tri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVK0F7NK6kVW-aANVg:-KbVK0F7NK6kVW-aANVh:bvtqvqc) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L41)):*
> ```cpp
>   // If we're using a default constructed message (haven't received
>   // a command yet), just return zeros.
>   if (command.num_joints == 0) {
> ```

BTW, I think this block should actually receive the measure robot state, or the initial state at least. You can then just command measured joint position here. doesn't have to be this pr.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVKUGqL5I5HiQwWNN8:-KbVKUGqL5I5HiQwWNN9:b-dfwvhy) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L53)):*
> ```cpp
>   auto state_value = state->get_mutable_value();
>   state_value.tail(kNumJoints) =
>       (new_positions - state_value.head(kNumJoints)) / kReceiverUpdatePeriod;
> ```

BTW, is state_value initialized to some random stuff, Zero() probably? The first tick is probably not quite right here. 

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVLSh2ISm0ogIygh4r:-KbVLSh2ISm0ogIygh4s:bbh2n9l) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L26)):*
> ```objc
>   void DoCalcOutput(const systems::Context<double>& context,
>                     systems::SystemOutput<double>* output) const override;
> ```

maybe add a public init function to set the current measured pose, and init discrete state. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVKUGqL5I5HiQwWNN8:-KbW1zi7QK9lNx6m3h7Q:b-aa6s5a) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, is state_value initialized to some random stuff, Zero() probably? The first tick is probably not quite right here. 
</blockquote></details>

It's initialized to zero in LeafSystem::SetDefaultState(), which is consistent with RigidBodyPlant::SetDefaultState(), at least for the case of the iiwa arm.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVLSh2ISm0ogIygh4r:-KbW2fuKxYgycDXFWGes:b-c8oacm) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L26)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

maybe add a public init function to set the current measured pose, and init discrete state. 
</blockquote></details>

Will investigate starting with a simulated arm not in the zero configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by sammy-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 41 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVK0F7NK6kVW-aANVg:-Kbk5JoPPT9rHwagr4aL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L41)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, I think this block should actually receive the measure robot state, or the initial state at least. You can then just command measured joint position here. doesn't have to be this pr.
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.h, line 26 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVLSh2ISm0ogIygh4r:-Kbk5RSAYywF1-oegwpq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.h#L26)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Will investigate starting with a simulated arm not in the zero configuration.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by siyuanfeng-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVKUGqL5I5HiQwWNN8:-Kbk9D3IAoE7W78NQ4Wv:b67sm4w) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L53)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's initialized to zero in LeafSystem::SetDefaultState(), which is consistent with RigidBodyPlant::SetDefaultState(), at least for the case of the iiwa arm.
</blockquote></details>

BTW, if you run this on the robot, you need to init this to something that matches the robot's right? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by sammy-tri** [comment]
Review status: 3 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 53 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-KbVKUGqL5I5HiQwWNN8:-KbkGYgywuNzxZOwE4rE:b-4l1e2g) ([raw file](https://github.com/robotlocomotion/drake/blob/4fc539c6526949969a043976cf17edd909981d4a/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L53)):*
<details><summary><i>Previously, siyuanfeng-tri wrote…</i></summary><blockquote>

BTW, if you run this on the robot, you need to init this to something that matches the robot's right? 
</blockquote></details>

I think this will only ever be used in simulation.  The command receiver / status sender here are intended to simulate the driver in https://github.com/RobotLocomotion/drake-iiwa-driver

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by sammy-tri** [comment]
+@sherm1 for platform review (I think we're close enough to the final form now)

---

Review status: 3 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-KbkGqNBpVWP-VLUwYc4:bh3xv2i)*

**Comment by sammy-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

---

Review status: 3 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-KbkSBV_m_xTKWRJkVEw:b-3f2dwx)*

**Comment by sammy-tri** [comment]
-@sherm1 +@jwnimmer-tri for platform review

---

Review status: 3 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-Kbp5HmaeHkilwzYT_Xa:bfz3ejc)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-Kbp8GP2_3_0HichgO51:-Kbp8GP2_3_0HichgO52:b-rhkab6) ([raw file](https://github.com/robotlocomotion/drake/blob/b703868b7fd8e9f0314e29eb7c010381699a32c8/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L52)):*
> ```cpp
>   // a command yet), keep using the initial state.
>   if (command.num_joints != 0) {
>     DRAKE_ASSERT(command.num_joints == kNumJoints);
> ```

BTW This seems fast and useful in release mode?

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-Kbp8k2ZTyOPvgiEVOU4:-Kbp8k2ZTyOPvgiEVOU5:bmpcqbx) ([raw file](https://github.com/robotlocomotion/drake/blob/b703868b7fd8e9f0314e29eb7c010381699a32c8/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L68)):*
> ```cpp
> void IiwaCommandReceiver::DoCalcOutput(const Context<double>& context,
>                                        SystemOutput<double>* output) const {
>   auto output_vec = this->GetMutableOutputVector(output, 0);
> ```

Unclear what type `output_vec` ends up as (and thus what `operator=` in the next line is doing).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-Kbp91PGjkbuKIZV-jG8:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 52 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-Kbp8GP2_3_0HichgO51:-KbpH5Ti402YeXPztpZp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b703868b7fd8e9f0314e29eb7c010381699a32c8/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L52)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This seems fast and useful in release mode?
</blockquote></details>

Done.

---

*[drake/examples/kuka_iiwa_arm/iiwa_lcm.cc, line 68 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-Kbp8k2ZTyOPvgiEVOU4:-KbpGqhQ0tRZI_OBbsZu:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/b703868b7fd8e9f0314e29eb7c010381699a32c8/drake/examples/kuka_iiwa_arm/iiwa_lcm.cc#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Unclear what type `output_vec` ends up as (and thus what `operator=` in the next line is doing).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919)*

**Comment by siyuanfeng-tri** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4919#-:-KbpeRe8j7UPvvk_3NKa:bg7igkv)*

**Pull request merged**
