### PR TITLE
[pydrake] More bindings for TriangleSurfaceMesh (hydroelastics APIs)

### PR DESCRIPTION
**Pull request by DamrongGuoy**
Towards #17625.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17713)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+(status: single reviewer ok) +@ericcousineau-tri for both reviews, :lgtm: x2 with nit on checking accessor types

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17713#-:-N9C6Kkr2unAdaID1t4U:b61z1qh)* status: 2 unresolved discussions (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6RwQ4VE5OXdfnqm9:-N9C6RwQ4VE5OXdfnqmA:bv5or24) (no related file):*
nit #17625 is an excellent writeup, but I do not see this PR tracked there in any of those checkboxes. Can you add this PR to it?
\cc @SeanCurtis-TRI

___
___
*[`bindings/pydrake/test/geometry_hydro_test.py` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6BmsD-9u1bTjBHJH:-N9C6BmtDzb7ukY75_d7:b-8fu7us) ([raw file](https://github.com/robotlocomotion/drake/blob/b1b1cae392a27302e280ca1486017586f96ffb20/bindings/pydrake/test/geometry_hydro_test.py#L128)):*
> ```Python
>                                       vertices=(v0, v1, v2, v3))
> 
>         # Sanity check every accessor.
> ```

nit For each accessor, I'd recommend at least checking the return type, i.e.,
`self.assertIsInstance(dut.accessor(), AccessorType)`

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17713)* status: 2 unresolved discussions (waiting on @DamrongGuoy and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6RwQ4VE5OXdfnqm9:-N9CwpAc7sKnFA0_uuOe:b-tqtepm) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit #17625 is an excellent writeup, but I do not see this PR tracked there in any of those checkboxes. Can you add this PR to it?
\cc @SeanCurtis-TRI
</blockquote></details>

Set to working.  I'll add checkboxes to #17625.

___
___
*[`bindings/pydrake/test/geometry_hydro_test.py` line 128 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6BmsD-9u1bTjBHJH:-N9CvwRLAJShsiWEHsGm:b-4f77d2) ([raw file](https://github.com/robotlocomotion/drake/blob/b1b1cae392a27302e280ca1486017586f96ffb20/bindings/pydrake/test/geometry_hydro_test.py#L128)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For each accessor, I'd recommend at least checking the return type, i.e.,
`self.assertIsInstance(dut.accessor(), AccessorType)`
</blockquote></details>

I'm new to Python.  Could you tell me more about what AccessorType is?  Is it something like this?

```
self.assertIsInstance(dut.num_vertices(), int)
```

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17713)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6RwQ4VE5OXdfnqm9:-N9E35NB-UJTajq7sIxi:bkxxrc1) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to working.  I'll add checkboxes to #17625.
</blockquote></details>

Done.  I added to #17625 like this:


___

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17713)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17713#-N9C6RwQ4VE5OXdfnqm9:-N9Hk1Qr9jC40ZeSHZrL:b-w196av) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Done.  I added to #17625 like this:


</blockquote></details>

OK Thanks!

___

**Pull request merged**
