### PR TITLE
Adds a RosClockPublisher.

### LINKED ISSUE #4344: Create a System 2.0 ROS Clock Server
# Problem Definition

When running a simulation that spans both Drake and ROS, it is important that both Drake and ROS processes remain in sync in terms of their notion of time. Currently, Drake's notion of time is stored within a `systems::Context` object whereas ROS' notion of time is dependent on a [ROS Clock Server](http://wiki.ros.org/Clock#Running_a_Clock_Server).

# Action Items

Synchronize ROS nodes to Drake's time by writing a System 2.0 ROS Clock Server that takes the time specified by `systems::Context::get_time()`, stores the time in a [rosgraph_msgs/Clock](http://docs.ros.org/api/rosgraph_msgs/html/msg/Clock.html) message, and publishes it on ROS topic `/clock`.

### PR DESCRIPTION
**Pull request by liangfok**
Resolves #4344.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4507)

### CODE REVIEW

**Comment by liangfok** [comment]
+@naveenoid for feature review please.
+@sammy-tri for platform review please.

Thanks!

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4507#-:-KYzZqN53eofCVDoi-vo:b-qbwdrw)*

**Comment by liangfok** [comment]
This PR passed all pre-merge CI checks and is thus ready to be reviewed.

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4507#-:-KZ2HMX_hwbI-l0HVYso:bnfp4nl)*

**Comment by naveenoid** [comment]
:lgtm: I see no feature defects here. Thanks for the patience!

---

Reviewed 4 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4507#-:-KZ5lNrDBDiTcwLmhg71:b-wovs0n)*

**Pull request merged**
