### PR TITLE
[py visualization] Split flaky camera_test into its own file

### LINKED ISSUE #19415: //bindings/pydrake/visualization:py/model_visualizer_test failure in CI
### What happened?

CI failure on `linux-focal-unprovisioned-clang-bazel-nightly-debug`: https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-unprovisioned-clang-bazel-nightly-debug/757/consoleFull

Initial glance suggests a network transient; this will be auto-closed until it recurs per policy.

### Version

_No response_

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

```shell
[2:48:51 AM]  ==================== Test output for //bindings/pydrake/visualization:py/model_visualizer_test:
[2:48:51 AM]  
[2:48:51 AM]  Running tests...
[2:48:51 AM]  ----------------------------------------------------------------------
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7000
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7001
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7002
[2:48:51 AM]  INFO:drake:Meshcat listening for connections at http://localhost:7003
[2:48:51 AM]  INFO:drake:Meshcat listening for connections at http://localhost:7004
[2:48:51 AM]  INFO:drake:Meshcat listening for connections at http://localhost:7005
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7006
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7007
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7008
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7009
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7010
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7011
[2:48:51 AM]  [2023-05-16 06:48:34,464] [meshcat_websocket_client] [INFO] Connecting...
[2:48:51 AM]  [2023-05-16 06:48:34,472] [meshcat_websocket_client] [INFO] ... connected
[2:48:51 AM]  [2023-05-16 06:48:34,472] [meshcat_websocket_client] [INFO] Sending...
[2:48:51 AM]  [2023-05-16 06:48:34,472] [meshcat_websocket_client] [INFO] ... sent
[2:48:51 AM]  [2023-05-16 06:48:34,472] [meshcat_websocket_client] [INFO] Disconnecting...
[2:48:51 AM]  [2023-05-16 06:48:34,476] [meshcat_websocket_client] [INFO] ... disconnected
[2:48:51 AM]  INFO:drake:Reload was successful
[2:48:51 AM]  .INFO:drake:Meshcat listening for connections at http://localhost:7012
[2:48:51 AM]  ..INFO:drake:Meshcat listening for connections at http://localhost:7012
[2:48:51 AM]  .drake/multibody/benchmarks/acrobot/acrobot.sdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  drake/multibody/benchmarks/acrobot/acrobot.urdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  drake/manipulation/util/test/simple_nested_model.sdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  drake/manipulation/util/test/simple_world_with_two_models.sdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  .INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  .INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  .drake/multibody/benchmarks/acrobot/acrobot.sdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7014
[2:48:51 AM]  drake/multibody/benchmarks/acrobot/acrobot.urdf
[2:48:51 AM]  INFO: Meshcat listening for connections at http://localhost:7013
[2:48:51 AM]  [*** LOG ERROR #0001 ***] [2023-05-16 06:48:50] [console] {Unknown exception in logger}
[2:48:51 AM]  FATAL: exception not rethrown
[2:48:51 AM]  E
[2:48:51 AM]  ======================================================================
[2:48:51 AM]  ERROR [3.819s]: test_set_position (model_visualizer_test.TestModelVisualizerSubprocess)
[2:48:51 AM]  Test that the --position option doesn't crash.
[2:48:51 AM]  ----------------------------------------------------------------------
[2:48:51 AM]  Traceback (most recent call last):
[2:48:51 AM]    File "/media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-clang-bazel-nightly-debug/_bazel_ubuntu/a932ec712c8398859de59d8e3b493f98/sandbox/linux-sandbox/11960/execroot/drake/bazel-out/k8-dbg/bin/bindings/pydrake/visualization/py/model_visualizer_test.runfiles/drake/bindings/pydrake/visualization/test/model_visualizer_test.py", line 70, in test_set_position
[2:48:51 AM]      subprocess.check_call([self.dut, self.model_file(model_runpath),
[2:48:51 AM]    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
[2:48:51 AM]      raise CalledProcessError(retcode, cmd)
[2:48:51 AM]  subprocess.CalledProcessError: Command '['/media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-clang-bazel-nightly-debug/_bazel_ubuntu/a932ec712c8398859de59d8e3b493f98/sandbox/linux-sandbox/11960/execroot/drake/bazel-out/k8-dbg/bin/bindings/pydrake/visualization/py/model_visualizer_test.runfiles/drake/bindings/pydrake/visualization/model_visualizer', '/media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-clang-bazel-nightly-debug/_bazel_ubuntu/a932ec712c8398859de59d8e3b493f98/sandbox/linux-sandbox/11960/execroot/drake/bazel-out/k8-dbg/bin/bindings/pydrake/visualization/py/model_visualizer_test.runfiles/drake/multibody/benchmarks/acrobot/acrobot.urdf', '--loop_once', '--position', '0.1', '0.2']' died with <Signals.SIGABRT: 6>.
[2:48:51 AM]  
[2:48:51 AM]  ----------------------------------------------------------------------
[2:48:51 AM]  Ran 17 tests in 21.028s
[2:48:51 AM]  
[2:48:51 AM]  FAILED (errors=1)
```
```

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #19415.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19687)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule, please.

(I _hope_ this will solve #19415 but there's no real easy way to check other than buildcop telemetry once it lands and bakes for a week or two.)

**Review by sammy-tri — COMMENTED** [review]
:lgtm: I think I've convinced myself that it doesn't matter that there's no visual geometry in the scene for a smoke test to be valid.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19687#-:-NYyMaWq5iHMfAixDmhe:b-ceqpee)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Review by sammy-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19687)* status: 1 unresolved discussion

___
*[`bindings/pydrake/visualization/test/model_visualizer_camera_test.py` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19687#-NYyNZUW8WyN64doTRdj:-NYyNZUW8WyN64doTRdk:bgbhnt3) ([raw file](https://github.com/RobotLocomotion/drake/blob/12ef763c169818ad9a582834a4932e708e1f0333/bindings/pydrake/visualization/test/model_visualizer_camera_test.py#L22)):*
> ```Python
>           <sdf version="1.9">
>             <model name="sample">
>               <link name="base"/>
> ```

nit: I think this test is still doing what we want (not crashing) despite the lack of visual geometry in a visualization test.  Consider commenting that this is a deliberate configuration.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19687)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

___
*[`bindings/pydrake/visualization/test/model_visualizer_camera_test.py` line 22 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19687#-NYyNZUW8WyN64doTRdj:-NYykGut8MJDmL1Ffoyt:b-xo56ou) ([raw file](https://github.com/RobotLocomotion/drake/blob/12ef763c169818ad9a582834a4932e708e1f0333/bindings/pydrake/visualization/test/model_visualizer_camera_test.py#L22)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: I think this test is still doing what we want (not crashing) despite the lack of visual geometry in a visualization test.  Consider commenting that this is a deliberate configuration.
</blockquote></details>

Good idea; more backstory commentary added up above.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19687)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform)

**Pull request merged**
