### PR TITLE
[doc] Add release notes v0.38.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
-(status: do not review) 

+@rpoyner-tri to begin feature review, please.  Target date is early next week.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356#-:-MtEEPau3SlqoGx-SOhO:b811ram)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtEB2Wu1aFtRSdIE_2O:-MtEB2Wv6pmahVDoH4nH:b-rozwg9) (no related file):*
Working

- Confirm (via PR filter) that all "newly deprecated" PR numbers appear in that section.
- Confirm (via PR filter) that all "removal of deprecated" PR numbers appear in that section.
- Confirm (via PR filter) that all "breaking change" PR numbers appear in that section.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtEB2Wu1aFtRSdIE_2O:-MtJKG2ODFwcIHSIkcCD:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

- Confirm (via PR filter) that all "newly deprecated" PR numbers appear in that section.
- Confirm (via PR filter) that all "removal of deprecated" PR numbers appear in that section.
- Confirm (via PR filter) that all "breaking change" PR numbers appear in that section.
</blockquote></details>

Done.

---

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356#-:-MtJVly15gBr-jYX0-Xg:bg7igkv)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[doc/_release-notes/v0.38.0.md, line 79 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJV6cPEOvv8YLsuhqe:-MtJV6cPEOvv8YLsuhqf:b-8ue156) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L79)):*
> ```Markdown
> 
> * Add meshcat option to disable SetTransform during recording ([#16271][_#16271])
> * Add UnitInertia::SolidEllipsoid utility ([#16349][_#16349])
> ```

BTW, what's the cut off the the release? There's a cousin PR to this (#16357) that will land soon.
___
*[doc/_release-notes/v0.38.0.md, line 80 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJUxCs4RXcX8ixAjYg:-MtJUxCs4RXcX8ixAjYh:b-x9iegt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L80)):*
> ```Markdown
> * Add meshcat option to disable SetTransform during recording ([#16271][_#16271])
> * Add UnitInertia::SolidEllipsoid utility ([#16349][_#16349])
> * Some MultibodyPlant functions that lookup element names are now heapless ([#16303][_#16303])
> ```

nit, lookup -> look up.
___
*[doc/_release-notes/v0.38.0.md, line 141 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJVbKBEBQF2mParpJs:-MtJVbKBEBQF2mParpJt:bk9vpg1) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L141)):*
> ```Markdown
> * pydrake.systems.framework.State.get_mutable_discrete_state ([#16207][_#16207])
> * pydrake.systems.framework.System.Accept ([#16352][_#16352])
> * pydrake.systems.framework.SystemVisitor
> ```

Should this item also have a PR number?  It's also part of #16352.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri, @sherm1, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.38.0.md, line 79 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJV6cPEOvv8YLsuhqe:-MtJWWgv8kS080xt222g:b-bdm7yt) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L79)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, what's the cut off the the release? There's a cousin PR to this (#16357) that will land soon.
</blockquote></details>

Most probably, tonight's nightly builds will be the release tag.  It will depend on what CI says, though.  This PR will have some final tweaks (to match the tag's contents) once I know what the tag will be.

The https://drake.mit.edu/release_playbook.html explains the entire process.
___
*[doc/_release-notes/v0.38.0.md, line 80 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJUxCs4RXcX8ixAjYg:-MtJWPyx4DMPvgvWbEga:b-kg5c29) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L80)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, lookup -> look up.
</blockquote></details>

OK Actually, I think it's one word (when referring to indexing, as opposed to gazing at the sky):
https://www.merriam-webster.com/dictionary/lookup
___
*[doc/_release-notes/v0.38.0.md, line 141 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJVbKBEBQF2mParpJs:-MtJWIH75cCaIXq2Sm4S:b-m8tooc) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L141)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Should this item also have a PR number?  It's also part of #16352.
</blockquote></details>

Yes!  Done.  Copy-pasting snafu.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri, @sherm1, and @xuchenhan-tri)

___
*[doc/_release-notes/v0.38.0.md, line 80 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJUxCs4RXcX8ixAjYg:-MtJXUrkEpFHTZDOi7TN:bqyupjo) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Actually, I think it's one word (when referring to indexing, as opposed to gazing at the sky):
https://www.merriam-webster.com/dictionary/lookup
</blockquote></details>

Reading more carefully, maybe "look up" is actually right?  In any case, I've added the space.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356#-:-MtJa-A8A8WAEee6P21g:bnfp4nl)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.38.0.md, line 79 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJV6cPEOvv8YLsuhqe:-MtJe0zkBBSla7sNFEKp:b-f46hkm) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L79)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Most probably, tonight's nightly builds will be the release tag.  It will depend on what CI says, though.  This PR will have some final tweaks (to match the tag's contents) once I know what the tag will be.

The https://drake.mit.edu/release_playbook.html explains the entire process.
</blockquote></details>

Got it. Thanks for the reference.
___
*[doc/_release-notes/v0.38.0.md, line 80 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtJUxCs4RXcX8ixAjYg:-MtJe2lF4rnLV6UpFhFh:blsyu28) ([raw file](https://github.com/robotlocomotion/drake/blob/5b91d4a9a3c98cb4bb43ad4c794b0c023d485c26/doc/_release-notes/v0.38.0.md#L80)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Reading more carefully, maybe "look up" is actually right?  In any case, I've added the space.
</blockquote></details>

Yeah I think with a space (verb) is right.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356#-:-MtKT3Hy4K_lvlXOJbPh:bg7igkv)* status: 1 unresolved discussion, needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.38.0.md, line 160 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtKS6OFAVavevq_4KUM:-MtKS6OFAVavevq_4KUN:b-g4lflt) ([raw file](https://github.com/robotlocomotion/drake/blob/60ca1db7278ba31b23d462551d6e64643473b2a0/doc/_release-notes/v0.38.0.md#L160)):*
> ```Markdown
> * Add nlohmann/json dependency ([#16231][_#16231])
> * Add picosha2 dependency ([#16232][_#16232])
> * Upgrade builifier to latest release 4.2.4 ([#16324][_#16324])
> ```

Just to be sure, is it `builifier` or `buildifier` ?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.38.0.md, line 160 at r5](https://reviewable.io/reviews/robotlocomotion/drake/16356#-MtKS6OFAVavevq_4KUM:-MtKWtzQ2SErvY2jY0g1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/60ca1db7278ba31b23d462551d6e64643473b2a0/doc/_release-notes/v0.38.0.md#L160)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Just to be sure, is it `builifier` or `buildifier` ?
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16356#-:-MtKfG660DfXBYHNcrgZ:bg7igkv)* status: needs at least two assigned reviewers, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail this is ready to manually tag docker images and upload the releases to S3.

Binary date: 20220114
Commit SHA: 8c4b39c
Release tag: v0.38.0

**Comment by BetsyMcPhail** [comment]
Docker images and S3 have been updated.

**Pull request merged**
