### PR TITLE
[cmake] Add pybind11_strip to enable -DCMAKE_BUILD_TYPE=Release

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards https://github.com/RobotLocomotion/drake-external-examples/issues/216
FYI @pangtao22

See downstream PR https://github.com/robotlocomotion/drake-external-examples/pull/247

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18453)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@svenevs for feature review, please!
See linked issue in overview for context

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18453#-:-NJG5Kqu265atEufGDPy:b-ayorwx)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
:lgtm: from what I'm understanding of the issue this resolves downstream problems, but the linked DEE PR won't pass until we merge this.

I did not test / reproduce this locally.  From what I'm gathering on how `pybind11` for drake works is we are doing custom CMake config files, but the [`pybind11Tools.cmake`](https://github.com/pybind/pybind11/blob/v2.7.0/tools/pybind11Tools.cmake) and other helper scripts are coming from somewhere else?  In which case the absence of `pybind11_strip` will cause this problem it seems.

+@xuchenhan-tri for platform review per schedule please.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18453#-:-NJGILePE2d9roV1cND0:bibeh3q)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Review by svenevs — COMMENTED** [review]
> but the linked DEE PR won't pass until we merge this.

Clarify: because it downloads and uses `drake-latest-focal.tar.gz` for example (produced by nightly jobs, so earliest it will pass is the morning after we merge here).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18453#-:-NJGJoEC8kqumTDKhh23:b-2a1l9e)* status: LGTM missing from assignee xuchenhan-tri(platform), missing label for release notes (waiting on @xuchenhan-tri)

**Comment by EricCousineau-TRI** [comment]
> is we are doing custom CMake config files

Correct! We take some files from pybind11 itself, e.g.:
https://github.com/RobotLocomotion/drake/blob/d735ad725492253b9dbd71d8aeef6702178b2dfb/tools/workspace/pybind11/package.BUILD.bazel#L65-L73

I don't remember exact rationale, but I believe we do not vendor in `pybind11Common.cmake` directly because it conflicts with our own definitions per `pybind11-config.cmake`.

**Comment by EricCousineau-TRI** [comment]
Not sure why we didn't have explicit note about that, so I've added it in here.

**Review by xuchenhan-tri — COMMENTED** [review]
platform :lgtm:
+(release notes: fix) 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18453#-:-NJGiuJV0c6sJZxDtc7v:b-yk0ai7)* status: :shipit: complete! all discussions resolved, LGTM from assignees svenevs,xuchenhan-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
