### PR TITLE
Dev/update gurobi doc

### PR DESCRIPTION
**Pull request by jonathan-owens**
Update the documentation for building from source with Gurobi, as discussed in issue #1392

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2286)

### CODE REVIEW

**Comment by jonathan-owens** [comment]
@david-german-tri Can you take a look at this? Simple doc update

**Comment by david-german-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/from_source.rst, line 38 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2286#-KHRNJYuuLpRPV5EERqv:-KHRNJYuuLpRPV5EERqw:2005466021) ([raw file](https://github.com/robotlocomotion/drake/blob/620089d8934b027b5e236b56f1bc7dc7c05ec229/drake/doc/from_source.rst#L38)):*
> ```reStructuredText
> 
> This capability is primarily meant for members of our team and close collaborators with whom we share licenses.
> ```

nit: trailing whitespace (throughout file)

---

*[drake/doc/from_source.rst, line 57 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/2286#-KHRNGwz6H3NEOh2OSiy:-KHRNGwz6H3NEOh2OSiz:1535828474) ([raw file](https://github.com/robotlocomotion/drake/blob/620089d8934b027b5e236b56f1bc7dc7c05ec229/drake/doc/from_source.rst#L57)):*
> ```reStructuredText
>      ./externals/gurobi/gurobi604/linux64/bin/grbgetkey [key-number]
> 
>    where ``[key-number]`` is the number you were given when you obtained a license from Gurobi. You should now have a function Gurobi to use with Drake.
> ```

functioning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2286)*

**Comment by david-german-tri** [comment]
:lgtm:

<details><summary><i>Previously, jonathan-owens (Jonathan Owens) wrote…</i></summary>
> @david-german-tri Can you take a look at this? Simple doc update</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2286#-:-KHRNWpOyKz4bw-ILCn3:1417088721)*

**Comment by jonathan-owens** [comment]
@david-german-tri I've marked them as resolved and pushed the changes but it doesn't seem to be picked up by reviewable...

**Comment by david-german-tri** [comment]
Reviewable just wanted you to click the "Done" button.  I've marked them as resolved from my end.  Still :lgtm:!

<details><summary><i>Previously, jonathan-owens (Jonathan Owens) wrote…</i></summary>
> @david-german-tri I've marked them as resolved and pushed the changes but it doesn't seem to be picked up by reviewable...</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2286#-:-KHVwyIHBMvCwqWRuO0j:1187993934)*

**Pull request merged**
