### PR TITLE
Implement APIs to enable/disable gravity

### PR DESCRIPTION
**Pull request by amcastro-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@joemasterjohn for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfIaood6HQJhpA0ZIVm:bns48ck)* status: LGTM missing from assignee joemasterjohn, needs platform reviewer assigned, needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
nvm, Joe is OOO tomorrow.

-@joemasterjohn 
+@sherm1 for feature review please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfIbjtqACbiuHy86cyb:br0tr10)* status: LGTM missing from assignee sherm1(platform), needs at least two assigned reviewers

**Review by amcastro-tri — COMMENTED** [review]
and... @sherm1 is platform today. So I'll switch again.
+@EricCousineau-TRI for feature review please.

@sherm1 you can serve as platform if Eric gets to LGTM today :-) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfLqYQjDzO-heVSTC3s:bwq0l1h)* status: LGTM missing from assignees sherm1(platform),EricCousineau-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! Any chance there's an issue / discussion regarding motivation?
On my side, I would have just implemented a gravity compensation controller - though it would not have been perfect for SAP.

Is the motivation here to align with the implicit controllers for SAP?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfM2gOx8tKajfp_q1b8:b-jz7ips)* status: LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
First pass done w/ motivation question above - PTAL!

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfM76OuClgrjCUtpYg_:biwy020)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/plant/multibody_plant.h` line 4747 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM67VX4IzF9MsaOVB8:-NfM67VX4IzF9MsaOVB9:bkl4o4d) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4747)):*
nit Per sytle guide, comments should be "Enables gravity"
https://drake.mit.edu/styleguide/cppguide.html#Function_Comments

> Function comments should be written with an implied subject of _This function_ and should start with the verb phrase; for example, "Opens the file", rather than "Open the file".

(here and elsewhere)
___
*[`multibody/plant/multibody_plant.h` line 4749 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM5csG5OWKGRRr7tK1:-NfM5csG5OWKGRRr7tK2:b-91t8lf) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4749)):*
> ```objc
>   /// Enable gravity for `model_instance`. No-op if already enabled.
>   /// @throws std::exception if called post-finalize.
>   void enable_gravity(ModelInstanceIndex model_instance);
> ```

nit Is there a reason as to why this is not a parameter in the context?
___
*[`multibody/tree/uniform_gravity_field_element.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM6lm86pPd0NYlsS6N:-NfM6lm86pPd0NYlsS6O:b-3qrhzn) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/tree/uniform_gravity_field_element.cc#L23)):*
> ```cpp
> 
> template <typename T>
> void UniformGravityFieldElement<T>::enable(ModelInstanceIndex model_instance) {
> ```

I do not see a code path that checks if the model instance (or instances) are valid.

Should that be added? e.g. `AssertAllModelInstancesValid()`

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 5 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM8NZTAsXqz2B8zv5K:-NfM8NZTAsXqz2B8zv5L:b1wehp) (no related file):*
BTW What's your plan for adding python bindings?  (You can delegate it if you don't want to do it, or you can do it in a follow-up PR, but we shouldn't ignore it entirely.)

___
___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfM86ELEQP5-GJO2-1e:b-mwshlh) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
> ```objc
>   /// this model instance. No-op if already disabled.
>   /// @throws std::exception if called post-finalize.
>   void disable_gravity(ModelInstanceIndex model_instance);
> ```

One of my pet peeves is implementing boolean setters using two functions instead of one.

If I have a config file that specifies a bool for this parameter, then at my call site I have to write a bloated if-else branch:

```
if config_gravity:
    plant.enable_gravity(model)
else:
    plant.disable_gravity(model)
```

Would you consider merging the two setters into a single setter that takes a `bool`?  It also cuts down on documentation bloat, implementation bloat, bindings bloat, etc.

**Review by amcastro-tri — COMMENTED** [review]
not a public one. It is a convenience feature that users could use in whichever way they find it useful. It's a very common feature in other simulators.

Re a use case, for us is IDTO. We build models where the robot has no gravity so that IDTO does not have to figure out the "gravity compensation portion" but jus the "task portion". The important thing here is that for this application, turning off gravity per model instance is helpful. 

For simulation, you are right you'd use a gravity compensation controller..... would you? with this, you could simplify your diagram by turning off gravity in your robot. Both workflows are allowed.

I'd imagine others might have their own applications. Again, just a feature.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfME6PB3H1Clo_IOq2l:bw0ig7u)* status: 5 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM8NZTAsXqz2B8zv5K:-NfMDbpABrCFCSC_REDT:bzdumcj) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW What's your plan for adding python bindings?  (You can delegate it if you don't want to do it, or you can do it in a follow-up PR, but we shouldn't ignore it entirely.)
</blockquote></details>

interesting... the pythong bindings are int there already,  @jwnimmer-tri 

___
___
*[`multibody/plant/multibody_plant.h` line 4749 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM5csG5OWKGRRr7tK1:-NfMFL3M4dq8PO6u-SiS:bjrox67) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4749)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is there a reason as to why this is not a parameter in the context?
</blockquote></details>

I wanted the simplest feature that enabled my work. The parameter API is obviously possible, but a bit more cumbersome to write and can be added later if needed.
___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfMDmU-2yEAHUL8X6n-:b-bzx49n) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

One of my pet peeves is implementing boolean setters using two functions instead of one.

If I have a config file that specifies a bool for this parameter, then at my call site I have to write a bloated if-else branch:

```
if config_gravity:
    plant.enable_gravity(model)
else:
    plant.disable_gravity(model)
```

Would you consider merging the two setters into a single setter that takes a `bool`?  It also cuts down on documentation bloat, implementation bloat, bindings bloat, etc.
</blockquote></details>

I like that. What would you call the method that takes a bool?
Would it be `void enable_gravity(bool enable)`?
and then disabling gravity would read `plant.enable_gravity(false)`?

**Review by EricCousineau-TRI — COMMENTED** [review]
Gotcha, that all makes sense - thanks!

> For simulation, you are right you'd use a gravity compensation controller..... would you? with this, you could simplify your diagram by turning off gravity in your robot. Both workflows are allowed.

I've done both, depending on what I want to achieve. I haven't needed per-model gravity, but then again it was only for testing controllers. I can see it being useful if I have manipulands (that should have gravity).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfMIi2TA-0le2wFbddB:b-pt23qn)* status: 5 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/plant/multibody_plant.h` line 4749 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM5csG5OWKGRRr7tK1:-NfMIvoOCl43i9nS4seU:b-qg7i08) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4749)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I wanted the simplest feature that enabled my work. The parameter API is obviously possible, but a bit more cumbersome to write and can be added later if needed.
</blockquote></details>

OK SGTM, thanks!
___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfMJ9sL2Vyd_Sy01g_w:b-qku3kj) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The getter is called `gravity_is_enabled`, so the natural setter would be `set_gravity_is_enabled`.

Or you could rename both getter and setter to something else, if you find a phrasing you prefer.  But get vs set should follow a pattern and use the same underlying phrasing.
</blockquote></details>

+1
FWIW, one slight tweak (reordering) is `is_gravity_enabled` and `set_gravity_enabled()`

**Review by amcastro-tri — COMMENTED** [review]
Excellent! I'm glad this helped

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfMUDblBTBp7ksPTUtf:b-wlqu1h)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfMIGv415h5Ke4X0SBL:-NfMaJiA-fQ-puhN69CU:bwfd52b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Is this worth a mention in the InverseDynamicsController API docs as an alternative?  "Instead of adding a pure gravity comp controller, see also `Mbp::set_...` to turn off gravity for the model, no controller needed".
</blockquote></details>

good idea. Added notes in `InversDynamics` and `InverseDynamicsController`

___
___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfMa_Y5-kcm8YfexKnl:b-jffrqo) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

+1
FWIW, one slight tweak (reordering) is `is_gravity_enabled` and `set_gravity_enabled()`
</blockquote></details>

I like this one @EricCousineau-TRI 
___
*[`multibody/tree/uniform_gravity_field_element.cc` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM6lm86pPd0NYlsS6N:-NfM_FpHCLsWlEhYdOq8:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/tree/uniform_gravity_field_element.cc#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I do not see a code path that checks if the model instance (or instances) are valid.

Should that be added? e.g. `AssertAllModelInstancesValid()`
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 2 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/plant/multibody_plant.h` line 4748 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfMggFPDAj7j3xbYXej:-NfMggFPDAj7j3xbYXek:b-cujmy) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f5afd3333dc3dbad55d631f46cd3aaee6bf4b8c/multibody/plant/multibody_plant.h#L4748)):*
> ```objc
> 
>   /// @returns `true` iff gravity is enabled for `model_instance`.
>   /// @see enable_gravity(), disable_gravity().
> ```

nit The vestigial names are still mentioned here.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfMrflYAg6y4UwpXJG9:-NfMrflYAg6y4UwpXJGA:b2qzsdg) (no related file):*
@jwnimmer-tri, would you like to serve as platform given you already did a good pass? and spare @sherm1 ?

___
___
*[`multibody/plant/multibody_plant.h` line 4748 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfMggFPDAj7j3xbYXej:-NfMr_D4CBkqRRFoHSOf:brbcwaj) ([raw file](https://github.com/RobotLocomotion/drake/blob/9f5afd3333dc3dbad55d631f46cd3aaee6bf4b8c/multibody/plant/multibody_plant.h#L4748)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The vestigial names are still mentioned here.
</blockquote></details>

ah.... :facepalm:

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 3 unresolved discussions, LGTM missing from assignees EricCousineau-TRI(platform),sherm1(platform)

___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfMyvGqBorGIBrjB-jA:binqp3) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I like this one @EricCousineau-TRI
</blockquote></details>

Ah, nuts, sorry - I think this diverges from accessor `my_attribute` and mutator `my_attribute`. What we have here is `is_my_attribute` and `set_my_attribute`.
In this case, Jeremy's could be used, or you can use just `gravity_enabled()` and `set_gravity_enabled()`. I can push that change if you'd like.

(Or do we care?)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: feature, thanks! Just one remaining item about accessor + mutator conventions.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfMzJUd89y-4BMFZq7f:b-hiz1gz)* status: 3 unresolved discussions, LGTM missing from assignee sherm1(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`multibody/plant/multibody_plant.h` line 4754 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfM86ELEQP5-GJO2-1d:-NfN2DAs6YRpzkCM8WbX:b-e4k86n) ([raw file](https://github.com/RobotLocomotion/drake/blob/350fd0e1487d081091d39f09b7d41a5365136ef1/multibody/plant/multibody_plant.h#L4754)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think we generally allow `is` to stand in as the accessor verb instead of `get`. So `is_foo` and `set_foo` is an OK pairing.
</blockquote></details>

OK Cool, resolving this then - thanks!
___
*[`systems/controllers/inverse_dynamics.h` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfN2Hib2tRZbCHSmCNK:-NfN2Hib2tRZbCHSmCNL:b-dnwstw) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/systems/controllers/inverse_dynamics.h#L38)):*
> ```objc
>  * </pre>
>  *
>  * @note As an alternative to adding a controller to your diagram, gravity
> ```

nit I have control diagrams for hardware that use this system - can't use that parameter meaningfully ;)

I'd recommend qualifying this as "your simulation diagram"
___
*[`systems/controllers/inverse_dynamics_controller.h` line 45 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfN2NyP89t1bInwu5Y9:-NfN2NyP89t1bInwu5YA:b-b30nhb) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/systems/controllers/inverse_dynamics_controller.h#L45)):*
> ```objc
>  *
>  * @note As an alternative to adding a separate controller system to your
>  * diagram, you can model gravity compensation with PD controllers using
> ```

nit (Same as above) Should qualify "your simulation diagram"

**Review by amcastro-tri — COMMENTED** [review]
Thanks @EricCousineau-TRI. 
+@sherm1 for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfN7VaG90veXvzlTQvD:bpm4opo)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform)

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 4 unresolved discussions, LGTM missing from assignee sherm1(platform)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfMrflYAg6y4UwpXJG9:-NfNDQVx5RSSHxCbbLbL:b-175s8s) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

@jwnimmer-tri, would you like to serve as platform given you already did a good pass? and spare @sherm1 ?
</blockquote></details>

I'm on it ...

___

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform)

___
*[`systems/controllers/inverse_dynamics.h` line 38 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfN2Hib2tRZbCHSmCNK:-NfNGx81--We9MBWwA6T:b-fwk2le) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/systems/controllers/inverse_dynamics.h#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I have control diagrams for hardware that use this system - can't use that parameter meaningfully ;)

I'd recommend qualifying this as "your simulation diagram"
</blockquote></details>

as with the IDTO example, it's not meant for simulation only. The IDTO diagram does exactly this.
The comment is simply a guidance, it's up to the user to choose what's best for their use case. 
I think ok to not be specific.
___
*[`systems/controllers/inverse_dynamics_controller.h` line 45 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfN2NyP89t1bInwu5Y9:-NfNHHka8AGg8yddvkQz:b-rqxvo7) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/systems/controllers/inverse_dynamics_controller.h#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Same as above) Should qualify "your simulation diagram"
</blockquote></details>

ditto.

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: with a few nits and typos

> Reviewed 1 of 9 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-:-NfNIlEc4OAF5XssGDbZ:by22e9h)* status: 5 unresolved discussions

___
*[`multibody/plant/multibody_plant.h` line 4749 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfNDiSW4vQpMYD9JC5i:-NfNDiSW4vQpMYD9JC5j:b-aowfgj) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/multibody/plant/multibody_plant.h#L4749)):*
> ```objc
>   /// @returns `true` iff gravity is enabled for `model_instance`.
>   /// @see set_gravity_enabled().
>   /// @throws std::exception iff model_instance >= num_model_instances().
> ```

BTW consider '"if the model instance is invalid". The specifics of how we identify model instances should be internal. For example, we might like the option at some point of allowing model editing which could leave some of the model instance slots unpopulated, or we might change to ids, etc.
___
*[`multibody/plant/multibody_plant.h` line 4752 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfNEU2vDowEXvoYhAq-:-NfNEU2vDowEXvoYhAq0:b-cm2gpa) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/multibody/plant/multibody_plant.h#L4752)):*
> ```objc
>   bool is_gravity_enabled(ModelInstanceIndex model_instance) const;
> 
>   /// Sets is_gravity_enabled() for `model_instance` to `is_enabled`.
> ```

nit: documentation should say what the effect is of changing this flag. Likely easy to guess, but it should say something. Should also say what the default value of the flag is. The relationship between this flag and the `gravity_field` would be worth mentioning also IMO.
___
*[`multibody/plant/test/gravity_test.cc` line 29 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfNFwC8CrsUR0ygDI1M:-NfNFwC8CrsUR0ygDI1N:bkmdaml) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/multibody/plant/test/gravity_test.cc#L29)):*
> ```cpp
>         "iiwa14_no_collision.sdf");
>     plant_ = std::make_unique<MultibodyPlant<double>>(0.0);
>     // Parser parser(plant_.get());
> ```

nit: vestigal comment?
___
*[`multibody/tree/uniform_gravity_field_element.h` line 40 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfNGnnA72PiLeQx_Epv:-NfNGnnA72PiLeQx_Epw:bp9sa69) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/multibody/tree/uniform_gravity_field_element.h#L40)):*
> ```objc
>   /// Constructs a uniform gravity field element with a strength given by the
>   /// acceleration of gravity vector `g_W`, expressed in the world frame W.
>   /// Gravity is diabled for the set of model instances
> ```

typo: "diabled" _should_ be a word meaning something like "turned into something devilish"! But ... likely you wanted "disabled" here.
___
*[`systems/controllers/inverse_dynamics.h` line 40 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/20264#-NfNIEio2YcbUqXSKJ4Y:-NfNIEio2YcbUqXSKJ4Z:bmfctby) ([raw file](https://github.com/RobotLocomotion/drake/blob/0350244ada3613cba92e75e2c263c9707b2a3e33/systems/controllers/inverse_dynamics.h#L40)):*
> ```objc
>  * @note As an alternative to adding a controller to your diagram, gravity
>  * compensation can be modeled by disabling gravity for a given model instance,
>  * see MultibodyPlat::set_gravity_enabled().
> ```

typo: Plat -> Plant

**Review by sherm1 — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20264)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),sherm1(platform)

**Pull request merged**
