### PR TITLE
Update NLopt

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Update to newer upstream [NLopt](https://github.com/stevengj/nlopt). This fixes the build if strict linking is enabled and fixes how testing is handled (such that drake could drive NLopt's tests from the superbuild, if desired).

See also:
- stevengj/nlopt#98
- stevengj/nlopt#99
- stevengj/nlopt#100

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4140)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
+@jamiesnape  for feature review

**Comment by jamiesnape** [comment]
Does this incidentally fix this issue? Not to worry if not.

https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/CMakeLists.txt#L88-L89

:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4140#-:-KWhvTSka_0kO92wTaoy:bjzfyst)*

**Comment by mwoehlke-kitware** [comment]
+@david-german-tri for platform review

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4140)*

**Comment by mwoehlke-kitware** [comment]
> Does this incidentally fix [this issue](https://github.com/RobotLocomotion/drake/blob/master/drake/solvers/CMakeLists.txt#L88-L89)?

Probably not. I recommend filing an issue (or better, a PR) upstream; they seem pretty responsive. (At least, @jschueller was great about fixing the issues I reported even without PR's.)

**Comment by mwoehlke-kitware** [comment]
@drake-jenkins-bot linux-gcc-ninja-experimental please
(failed due to some weird issue cloning mosek; probably a fluke and not a problem with this PR)

**Comment by david-german-tri** [comment]
:lgtm: thanks for the helpful PR message!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4140#-:-KWo22IcLLE_vIfUwiK1:b-fn6iu2)*

**Pull request merged**
