### PR TITLE
Deprecate drake_optional.h header

### PR DESCRIPTION
**Pull request by jamiesnape**
Depends on #12271,  #12272, #12273, #12274, #12275, #12276, and #12277.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12278)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Given the potentially very-wide use of `drake::optional` in downstream code, I'd like to see `DRAKE_DEPRECATED` placed on _all_ of the types in the header, so that we're not relying solely on the `#warning` to give notice.  Some downstream builds could conceivably choose to mute pre-processor warnings but deal more carefully with `Wdeprecated-declarations`.

**Comment by jamiesnape** [comment]
What is the syntax for deprecating an alias?

**Comment by jwnimmer-tri** [comment]
https://godbolt.org/z/G8hdgT
```c++
template <typename T>
using optional DRAKE_DEPRECATED(...)
  = std::optional<T>;
}
```

**Comment by jamiesnape** [comment]
Strange, wonder why that didn't work for me earlier. Will fix.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Pull request merged**
