### PR TITLE
[bindings/manipulation] Bind manipulation drivers

### PR DESCRIPTION
**Pull request by mpetersen94**
Adds bindings for the ZeroForce, Iiwa & Schunk drivers.

Towards #17112

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940)

### CODE REVIEW

**Review by mpetersen94 — COMMENTED** [review]
+@zachfang for feature review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NC6ojw58Zdqx4QNc14j:bdcmg4f)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @zachfang)

**Review by mpetersen94 — COMMENTED** [review]
I wasn't able to figure out how to bind a `ApplyDriverConfigs` with a variant the used all the exposed driver types. Any thoughts would be helpful.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NCLascRBGOmK2mmREHg:b1nmm78)* status: LGTM missing from assignee zachfang, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @zachfang)

**Comment by zachfang** [comment]
Hi @mpetersen94, Thanks for the PR. I am out of the office today but I can review it tomorrow.

**Comment by jwnimmer-tri** [comment]
+@jwnimmer-tri for platform review per schedule.

> I wasn't able to figure out how to bind a ApplyDriverConfigs with a variant the used all the exposed driver types. Any thoughts would be helpful.

My plan was not to bind `ApplyDriverConfigs`, but instead to either re-implement it in Python or else do something completely different for Python.  When I have a moment to finish the Python demo of `hardware_sim`, that will help me decide which way to go.

**Review by jwnimmer-tri — COMMENTED** [review]
Thinking ahead -- as part of the "pydrake modules names to too long" work, we're going to collapse all of the `pydrake.manipulation.{kuka_iiwa,schunk_wsg,...}` modules down into just `pydrake.manipulation`, in which case `ApplyDriverConfig` will end up being a pybind11 overloaded function, so maybe will just work?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NCQcqNg5XtF9I4shNnh:bpsox0c)* status: 6 unresolved discussions, LGTM missing from assignees jwnimmer-tri(platform),zachfang (waiting on @mpetersen94 and @zachfang)

___
*[`bindings/pydrake/manipulation/kuka_iiwa_py.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQa-9B8OKOPyBeNkmE:-NCQa-9B8OKOPyBeNkmF:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L146)):*
> ```cpp
>     m.def("ApplyDriverConfig", &ApplyDriverConfig, py::arg("driver_config"),
>         py::arg("model_instance_name"), py::arg("sim_plant"),
>         py::arg("models_from_directives"), py::arg("lcm"), py::arg("builder"),
> ```

typo



_Suggestion:_
```cpp
lcms
```
___
*[`bindings/pydrake/manipulation/schunk_wsg_py.cc` line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQbJ6T5nQD5x40ImQn:-NCQbJ6T5nQD5x40ImQo:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/schunk_wsg_py.cc#L132)):*
> ```cpp
>     m.def("ApplyDriverConfig", &manipulation::schunk_wsg::ApplyDriverConfig,
>         py::arg("driver_config"), py::arg("model_instance_name"),
>         py::arg("sim_plant"), py::arg("models_from_directives"), py::arg("lcm"),
> ```

typo



_Suggestion:_
```cpp
lcms
```
___
*[`bindings/pydrake/manipulation/util_py.cc` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQcRkG-_0nzOJgOl11:-NCQcRkH19CBVcF23aHd:bb7phvt) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/util_py.cc#L35)):*
> ```cpp
>     m.def("ApplyDriverConfig", &ApplyDriverConfig, py::arg("driver_config"),
>         py::arg("model_instance_name"), py::arg("sim_plant"),
>         py::arg("models_from_directives"), py::arg("lcm"), py::arg("builder"),
> ```

typo



_Suggestion:_
```cpp
lcms
```
___
*[`bindings/pydrake/manipulation/util_py.cc` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQcGbm33iEZ3ho1F_T:-NCQcGbn9V_a_Lm5YJjs:bbh1ip8) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/util_py.cc#L38)):*
> ```cpp
>         doc.ApplyDriverConfig.doc);
> 
>     // using DriverVariant =
> ```

nit Remove commented-out code.  (We can do it in another PR if we like.)

Ditto for the matching `#include` stuff above.
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQaQSFDNRJfWuirewA:-NCQaQSFDNRJfWuirewB:b-7ilvfu) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L76)):*
> ```Python
>         self.assertEqual(mut.get_iiwa_max_joint_velocities().shape, (7,))
> 
>     def test_schunk_wsg_build_control(self):
> ```

typo?



_Suggestion:_
```Python
iiwa
```
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQaVmJ-uxHZ5kk7SRi:-NCQaVmJ-uxHZ5kk7SRj:by4mymm) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L84)):*
> ```Python
>         models_from_directives = ProcessModelDirectives(directives, parser)
>         plant.Finalize()
>         ctrl_plant = MultibodyPlant(1.)
> ```

nit  _Do not abbreviate by deleting letters within a word._

-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules



_Suggestion:_
```Python
controller
```

**Review by zachfang — COMMENTED** [review]
:lgtm: for feature with some non-blocking nits regarding the consistency between C++ and Python tests.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NCQouLZEtVQZROy9VgB:b-2x10m6)* status: 10 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @mpetersen94)

___
*[`bindings/pydrake/manipulation/test/schunk_wsg_test.py` line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQnNVJ9uQxvXgkli0T:-NCQnNVJ9uQxvXgkli0U:b-wfxpys) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/schunk_wsg_test.py#L102)):*
> ```Python
>     def test_schunk_wsg_driver(self):
>         dut = mut.SchunkWsgDriver()
>         dut.pid_gains = np.array([1., 2., 3.])
> ```

BTW. Are the `pid_gains` here and a few lines above different types, i.e., list vs. `np.array`?
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQj6Gg7sD0WKuSumBE:-NCQj6Gg7sD0WKuSumBF:b-wl5xe) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L6)):*
> ```Python
> 
> import unittest
> import numpy as np
> ```

nit: unused.
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQl0PDDpCG9mscwoKz:-NCQl0PDDpCG9mscwoL-:bvw6yo7) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L25)):*
> ```Python
> 
>         builder = DiagramBuilder()
>         plant = builder.AddSystem(MultibodyPlant(1.))
> ```

nit: per [the previous IIwa PR comment](https://github.com/RobotLocomotion/drake/pull/17886#pullrequestreview-1107545299), should we apply here, i.e., use AddMultibodyPlant() instead? 
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQnhRG2tuwiLZdp-SY:-NCQnhRG2tuwiLZdp-SZ:bltblgt) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L36)):*
> ```Python
> 
>         self.assertEqual(len(builder.GetSystems()), 1)
>         mut.ApplyDriverConfig(
> ```

nit: in the c++ version we doesn't really exercise ` models_from_directives.at()` to query the `ModelInstanceInfo`. Should we keep the tests consistent?

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-jammy-gcc-bazel-experimental-release please.

**Review by mpetersen94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri and @zachfang)

___
*[`bindings/pydrake/manipulation/kuka_iiwa_py.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQa-9B8OKOPyBeNkmE:-NCYFtjlBpHp8oyu0t3N:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/kuka_iiwa_py.cc#L146)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/schunk_wsg_py.cc` line 132 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQbJ6T5nQD5x40ImQn:-NCYG31PA6PB03S8sqkX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/schunk_wsg_py.cc#L132)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/util_py.cc` line 35 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQcRkG-_0nzOJgOl11:-NCYG4BdA4Z_VepteyIj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/util_py.cc#L35)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/util_py.cc` line 38 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQcGbm33iEZ3ho1F_T:-NCYGVzy24TcC4nHBRI6:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/util_py.cc#L38)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Remove commented-out code.  (We can do it in another PR if we like.)

Ditto for the matching `#include` stuff above.
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 76 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQaQSFDNRJfWuirewA:-NCYGcbDAbUqxV6om4ng:bu9gagv) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done. Thanks for catching this!
___
*[`bindings/pydrake/manipulation/test/kuka_iiwa_test.py` line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQaVmJ-uxHZ5kk7SRi:-NCYHiHd3DZqhTmfD_zS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/kuka_iiwa_test.py#L84)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit  _Do not abbreviate by deleting letters within a word._

-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/test/schunk_wsg_test.py` line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQnNVJ9uQxvXgkli0T:-NCYLUos4LgfuQSltwjf:b-uva5vw) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/schunk_wsg_test.py#L102)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Are the `pid_gains` here and a few lines above different types, i.e., list vs. `np.array`?
</blockquote></details>

Yes. I intentionally made them different to ensure both lists and arrays are handled well. Sometimes the bindings handle these two types differently in ways that a Python user would not expect so I like having a smoke test to find those cases.
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQj6Gg7sD0WKuSumBE:-NCYI4PoCLlsNJd2SppD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L6)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: unused.
</blockquote></details>

Done.
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQl0PDDpCG9mscwoKz:-NCYKJ3z-zIxYRKswbkS:bdgtjwg) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L25)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: per [the previous IIwa PR comment](https://github.com/RobotLocomotion/drake/pull/17886#pullrequestreview-1107545299), should we apply here, i.e., use AddMultibodyPlant() instead? 
</blockquote></details>

If the goal is consistency across the Python tests of `ApplyFooConfig`, the current constructor is closer to what's already in master. If the goal is to be consistent between C++ & Python, I'm not sure this change is necessary since testing should be different between C++ & Python. If there is a different goal, there might be a reason for the change. Leaving unless you feel strongly that this should change.
___
*[`bindings/pydrake/manipulation/test/util_test.py` line 36 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQnhRG2tuwiLZdp-SY:-NCYIRJyBbLiXuDRJ2jg:b-dbulps) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L36)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit: in the c++ version we doesn't really exercise ` models_from_directives.at()` to query the `ModelInstanceInfo`. Should we keep the tests consistent? 
</blockquote></details>

I'm not quite sure what you are suggesting but since Python testing is just meant to exercise the bound API, not check the logic/behavior of the underlying C++, I'm leaning towards leaving it as is.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NC_s75Q8WX97PRX8yO3:b-vtj4vo)* status: 2 unresolved discussions (waiting on @zachfang)

**Review by jwnimmer-tri — COMMENTED** [review]
Zach is AFK this afternoon, so I'll resolve the optn discussions on his behalf.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17940#-:-NCaprxfCI36VQEbUAVf:b-ud9val)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),zachfang (waiting on @mpetersen94)

___
*[`bindings/pydrake/manipulation/test/util_test.py` line 25 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17940#-NCQl0PDDpCG9mscwoKz:-NCaq0yE9iUwhjUM1UO6:b-50b4qq) ([raw file](https://github.com/robotlocomotion/drake/blob/5ca4e90bccd1fe2dd61c291c8977a95f5867b6aa/bindings/pydrake/manipulation/test/util_test.py#L25)):*
<details><summary><i>Previously, mpetersen94 (Mark Petersen) wrote…</i></summary><blockquote>

If the goal is consistency across the Python tests of `ApplyFooConfig`, the current constructor is closer to what's already in master. If the goal is to be consistent between C++ & Python, I'm not sure this change is necessary since testing should be different between C++ & Python. If there is a different goal, there might be a reason for the change. Leaving unless you feel strongly that this should change.
</blockquote></details>

I think this is OK as-is.  The C++ tests are a _functional_ test, where we check that the implementation is correct.  The Python test are a _bindings_ test where we only need to check that the pybind11 glue code is transcribed correctly; broadly there's no requirement to _idiomatically_ use the Python classes in the bindings' unit tests. The goal is to be compact and as little code as possible, which is often non-idomatic. We generally leave idiomatic use to examples and tutorials.

**Pull request merged**
