### PR TITLE
mutlibody_plant: Convert class overview to javadoc

### LINKED ISSUE #14498: plant: Weird mix of documentation messes up mkdoc parsing
In doing #12590, I'm hitting a point where the weird mix of doc-styles messes up `mkdoc`:
https://github.com/RobotLocomotion/drake/blob/935f56aaf4d58dfd2275b046dce9d677419fe3f5/multibody/plant/multibody_plant.h#L338-L341

This stuff:
https://github.com/EricCousineau-TRI/drake/blob/6f95c761df4003ac873a6fd912b6edc823df2ca4/tools/workspace/pybind11/test/sample_header.h#L365-L379

Generates weird stuff where the indentation gets funky:
```
before:
 My simple system.

 @system
 name: Wooh
 input_ports:
 - u
 output_ports:
 - y
 @endsystem

Intermedaite
comment

 Yeah.

after:
 My simple system.

 .. pydrake_system::

    name: Wooh
     input_ports:
     - u
     output_ports:
     - y

Intermedaite
comment

 Yeah.
```

I don't feel like robustifying text parsing, so I'm just going to fix the TODO in the C++ file. Boring work, but whatevs.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves #14498

Using latest commit (033687858b) from https://github.com/RobotLocomotion/drake/pull/13461#pullrequestreview-423280837, using this command:
```
bazel-bin/tools/lint/cpp_docstring_lint multibody/plant/multibody_plant.h
```
I cherry-picked the diff for class overview, then left everything else the same.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14499)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@joemasterjohn for a quick feature review, please?
+@rpoyner-tri for a quick platform review, please?

I dunno why git diff isn't working that well, but TBH meh. I just want to resolve this for #12590

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14499#-:-MQOqB-GBgM7vNdnjwwH:b-5wy3wz)* status: LGTM missing from assignees rpoyner-tri(platform),joemasterjohn (waiting on @joemasterjohn and @rpoyner-tri)

**Review by joemasterjohn — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14499#-:-MQOwMxV0CzMv8Rci-PW:bnfp4nl)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn and @rpoyner-tri)

**Comment by EricCousineau-TRI** [comment]
MutlibodyPlant pydrake docs before: https://drake.mit.edu/pydrake/pydrake.multibody.plant.html#pydrake.multibody.plant.MultibodyPlant_
>
image

After:
> image

Not perfect, but a step in the right direction.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14499)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @joemasterjohn)

**Review by rpoyner-tri — COMMENTED** [review]
ugh, diff fail, but :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14499#-:-MQP4CSY8kzuhIKGdG_9:b-ypnmp9)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),joemasterjohn (waiting on @joemasterjohn)

**Pull request merged**
