### PR TITLE
ParseConstraint should ignore true formula, and throws an error with false formula

### PR DESCRIPTION
**Pull request by hongkai-dai**
Based on the slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1646782917272159

cc @lujieyang

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@jwnimmer-tri for feature review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761#-:-MxrUOI216coNd2M3_Xg:b-o4a2ka)* status: LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16761#-Mxv1YgdBzJC-d6_yO94:-Mxv1YgdBzJC-d6_yO95:b-40htmo) (no related file):*
The fact that we had to add this guard in three places seems like a violation of the single responsibility principle.  I'm going to take a closer look at the existing code to understand why such a simple change is so much code and bloats the inline functions in our header files.

---

**Review by hongkai-dai — COMMENTED** [review]
I rebased this branch on top of your PR. Thanks for your PR!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761#-:-My9DX23EKrFQH_mxQQd:be4dcok)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
___
*[solvers/create_constraint.cc, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My9IimDDWxSUUqdfSEU:-My9IimDDWxSUUqdfSEV:b-cqflb) ([raw file](https://github.com/robotlocomotion/drake/blob/5329ac8c2eaa10f8108f0a29b5aaeb93894841b0/solvers/create_constraint.cc#L305)):*
> ```cpp
>     const Eigen::Ref<const MatrixX<symbolic::Formula>>& formulas) {
>   // Only add the constraint if the formula is not always True or False.
>   int num_valid_formulas = 0;
> ```

nit This pre-computation of the final vector sizes seems a bit too verbose and brittle, with the requirement to carefully keep in sync with the iteration loop below.

What do you think about this implementation tactic instead?

```c++
std::vector<Expression> v;
std::vector<double> lb;
std::vector<double> ub;
v.reserve(formulas.size());
lb.reserve(formulas.size());
ub.reserve(formulas.size());

for (...) {
  if (is_true(f)) {
    continue;
  } else if (is_equal_to(f)) {
    ...;
  } else if (is_less_than_or_equal_to(f)) {
    ...;
  } else if (is_greater_than_or_equal_to(f)) {
    ...;
  } else if (is_greater_than_or_equal_to(f)) {
    ...;
  } else {
    // throw unsupported formula kind
  }
}

const Eigen::Map v_map(v.data(), v.size());
const Eigen::Map lb_map(lb.data(), lb.size());
const Eigen::Map ub_map(ub.data(), ub.size());
return ParseConstraint(v_map, lb_map, ub_map));
```

It's the same number of allocations, but with less code to worry about.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/create_constraint.cc, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My9IimDDWxSUUqdfSEU:-MyAWPa29x_S5QDQ8KOo:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5329ac8c2eaa10f8108f0a29b5aaeb93894841b0/solvers/create_constraint.cc#L305)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This pre-computation of the final vector sizes seems a bit too verbose and brittle, with the requirement to carefully keep in sync with the iteration loop below.

What do you think about this implementation tactic instead?

```c++
std::vector<Expression> v;
std::vector<double> lb;
std::vector<double> ub;
v.reserve(formulas.size());
lb.reserve(formulas.size());
ub.reserve(formulas.size());

for (...) {
  if (is_true(f)) {
    continue;
  } else if (is_equal_to(f)) {
    ...;
  } else if (is_less_than_or_equal_to(f)) {
    ...;
  } else if (is_greater_than_or_equal_to(f)) {
    ...;
  } else if (is_greater_than_or_equal_to(f)) {
    ...;
  } else {
    // throw unsupported formula kind
  }
}

const Eigen::Map v_map(v.data(), v.size());
const Eigen::Map lb_map(lb.data(), lb.size());
const Eigen::Map ub_map(ub.data(), ub.size());
return ParseConstraint(v_map, lb_map, ub_map));
```

It's the same number of allocations, but with less code to worry about.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
___
*[solvers/create_constraint.cc, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My9IimDDWxSUUqdfSEU:-MyAxqC7B1akGXQVnhv3:b-5jq13b) ([raw file](https://github.com/robotlocomotion/drake/blob/5329ac8c2eaa10f8108f0a29b5aaeb93894841b0/solvers/create_constraint.cc#L305)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think `num_valid_formulas` and this whole first loop can disappear as well?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/create_constraint.cc, line 305 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My9IimDDWxSUUqdfSEU:-MyDYUry8lPASiA9689t:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5329ac8c2eaa10f8108f0a29b5aaeb93894841b0/solvers/create_constraint.cc#L305)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think `num_valid_formulas` and this whole first loop can disappear as well?
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
FYI I just force-pushed a rebase onto latest master to help continue my review.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 2 of 5 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16761#-Mxv1YgdBzJC-d6_yO94:-MyG49g72EaQzzWG4OvK:blyhr4j) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The fact that we had to add this guard in three places seems like a violation of the single responsibility principle.  I'm going to take a closer look at the existing code to understand why such a simple change is so much code and bloats the inline functions in our header files.
</blockquote></details>

OK resolving this now in lieu of a new discussion, below.

---
___
*[solvers/test/mathematical_program_test.cc, line 1449 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16761#-MyFykE62ZZVDNz9enUA:-MyFykE62ZZVDNz9enUB:b-y3ksv5) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c7b0f8fe31fb5ae5663c7b69137954bee2d941/solvers/test/mathematical_program_test.cc#L1449)):*
> ```cpp
>       symbolic::Expression(1) == 1, symbolic::Expression(2) == 2);
>   DRAKE_EXPECT_THROWS_MESSAGE(
>       prog.AddConstraint(all_true_formulas),
> ```

In the test case above an all-True constraint is a no-op, but in this case it's an exception.  I'd like to seek 100% uniformity in our MathematicalProgram API.

What do you think about the following?

(1) When given Formula(s) that are always false, the Formula-related parsing functions (ParseConstraint and ParseLinearEqualityConstraint) will throw, as is already implemented here.

(2) Ideally other parsing functions beyond just the Formula ones would reject trivially-false constraints as well (e.g., ub < lb), but that can wait for a different PR.

(3) When given a mix of Formula(s) where some are always true but some are meaningful, the parsing functions prune off the always-true outputs and only bind the meaningful outputs, as is already implemented here.

(4) When ParseConstraint is given Formula(s) where all of them are always true, it returns a zero-sized BoundingBoxConstraint (where both num_vars and num_outputs are zero).

(5) When ParseLinearEqualityConstraint is given Formula(s) where all of them are always true, it returns a zero-sized LinearEqualityConstraint.

(6) In MathematicalProgram when trying to add a zero-sized constraint, it returns a Binding but doesn't add it to into the program, no matter what type of constraint it was.  (We can probably do this best in the shared_ptr family of Add functions, not the functions that call Parse, since the ones that call Parse always delegate to the shared_ptr ones.)  Probably the same goes for meaningless Costs being added.

(7) Fully document the semantics of ParseConstraint with a real API comment.  "Assist AddLinearConstraint" is not a particularly helpful specification.

(8) Fully document the semantics of MP::AddConstraint and related with specific API comments about these special cases.  (Possibly as part of a section group or class overview, to avoid repetition?)

---

If you like the plan, then I think a good PR train would be:

(a) PR that throws on always-false Formula(s).

(b) PR to make all of the AddCost and AddConstraint functions that take a shared_ptr to detect trivial (empty) additions and skip adding them into the program;

(c) PR to compress down always-true constraints when parsing.
___
*[solvers/create_constraint.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My3TFX-5AvfQqYCKj_U:-My3TFX08Nn14_StUPou:b4stx8o) ([raw file](https://github.com/robotlocomotion/drake/blob/567e4189f4bea6fe92a885623b9e2c352b8cdbfd/solvers/create_constraint.h#L58)):*
> ```objc
> 
> /*
>  * Assist MathematicalProgram::AddLinearConstraint(...).
> ```

Some specific thoughts here also... see the above thread on the unit testing for context.

All of these API specifications need to be clear on whether they will parse non-linear constraints (some do, even though they are documented as "assist AddLinearConstraint"), or when they will throw an exception.

They all need to be clear on whether a trivially-true constraint should return a zero-dimensional bounding box constraint or throw an exception.

They all need to be clear on whether is_conjunction is unpacked internally or is an exception.

Probably all of them should have a uniform answer to those questions, so that their implementation can be shared instead of repeating some fairly tricky code in multiple places.

**Comment by jwnimmer-tri** [comment]
___
*[solvers/mathematical_program.cc, line 796 at r6](https://reviewable.io/reviews/robotlocomotion/drake/16761#-MyG4thz5Gf38zU_1dSE:-MyG4thz5Gf38zU_1dSF:br1zaqt) ([raw file](https://github.com/robotlocomotion/drake/blob/f4c7b0f8fe31fb5ae5663c7b69137954bee2d941/solvers/mathematical_program.cc#L796)):*
> ```cpp
> Binding<LinearConstraint> MathematicalProgram::AddLinearConstraint(
>     const Formula& f) {
>   if (symbolic::is_true(f)) {
> ```

nit I'd like to see all of the formula-unpacking logic live in the parser functions, not in MathematicalProgram.  That will make it easier to unit test, re-use helper functions, and document what's happening.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/create_constraint.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My3TFX-5AvfQqYCKj_U:-Myx9KQv0llfcI4gmteu:bwv3mpn) ([raw file](https://github.com/robotlocomotion/drake/blob/567e4189f4bea6fe92a885623b9e2c352b8cdbfd/solvers/create_constraint.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Some specific thoughts here also... see the above thread on the unit testing for context.

All of these API specifications need to be clear on whether they will parse non-linear constraints (some do, even though they are documented as "assist AddLinearConstraint"), or when they will throw an exception.

They all need to be clear on whether a trivially-true constraint should return a zero-dimensional bounding box constraint or throw an exception.

They all need to be clear on whether is_conjunction is unpacked internally or is an exception.

Probably all of them should have a uniform answer to those questions, so that their implementation can be shared instead of repeating some fairly tricky code in multiple places.
</blockquote></details>

Other PRs have resolved most of the other semantics and documentation changes.

However, we might still have a problem that `is_conjunction` is not uniformly handled across all of the helpers.  Maybe that should just be a TODO or issue?  (Not urgent at the moment?)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[solvers/create_constraint.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My3TFX-5AvfQqYCKj_U:-MyxEMYB1gnp0azDPzHv:b-v3zgpj) ([raw file](https://github.com/robotlocomotion/drake/blob/567e4189f4bea6fe92a885623b9e2c352b8cdbfd/solvers/create_constraint.h#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Other PRs have resolved most of the other semantics and documentation changes.

However, we might still have a problem that `is_conjunction` is not uniformly handled across all of the helpers.  Maybe that should just be a TODO or issue?  (Not urgent at the moment?)
</blockquote></details>

Sorry I don't fully understand this yet. As far as I can see, is_conjunction is only called twice inside `create_constraint.cc`, and in both cases it is unpacked. I don't see throwing an exception. Did I miss anything?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16761)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), needs at least two assigned reviewers (waiting on @hongkai-dai and @jwnimmer-tri)

___
*[solvers/create_constraint.h, line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16761#-My3TFX-5AvfQqYCKj_U:-MyxEz-v3gU2CGHkukg6:bcxcsxe) ([raw file](https://github.com/robotlocomotion/drake/blob/567e4189f4bea6fe92a885623b9e2c352b8cdbfd/solvers/create_constraint.h#L58)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry I don't fully understand this yet. As far as I can see, is_conjunction is only called twice inside `create_constraint.cc`, and in both cases it is unpacked. I don't see throwing an exception. Did I miss anything?
</blockquote></details>

These two handle it fine:
* `ParseConstraint(const Formula& f)` 
* `ParseLinearEqualityConstraint(const Formula& f)`  

These two will throw if any of the formulas is a conjunction, because they don't have any if-else branch that notices conjunctions:
* `ParseConstraint(const Eigen::Ref<const MatrixX<symbolic::Formula>>& formulas)`
* `ParseLinearEqualityConstraint(const set<Formula>& formulas)` 

In the bigger picture, having the single-formula and multiple-formula code be near-duplicates of each other is the root cause here.  There should only be one implementation of the if-else chain to match valid formulas.  (Specifically, one chain for generic constraint, different chain for linear equality, since they are different patterns.)

**Comment by hongkai-dai** [comment]
Close this PR as it is superseded by #16854 #16813

**Comment by jwnimmer-tri** [comment]
Should I file an issue about the `is_conjunction` being mis-handled?

**Comment by hongkai-dai** [comment]
> Should I file an issue about the is_conjunction being mis-handled?

Ah yes I forgot that, would be great if you file an issue and assign it to me.

**Comment by jwnimmer-tri** [comment]
=> https://github.com/RobotLocomotion/drake/issues/16898

**Pull request closed without merging**
