### PR TITLE
Add operator* between Transform<Expression> and Transform<double>

### LINKED ISSUE #6505: Support multiplication of Isometry3<T> between symbolic::Expression and double
```cpp
Isometry3<symbolic::Expression> pose_exp;
Isometry3<double> pose_dbl;

pose_exp * pose_dbl;                   // Invalid!
pose_exp.matrix() * pose_dbl.matrix(); // Valid
```

We need to extend the specification to allow straight-up multiplication (and other binary ops).

### PR DESCRIPTION
**Pull request by soonho-tri**
Close #6505

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6604)

### CODE REVIEW

**Comment by soonho-tri** [comment]
+@seancurtis-tri , feature-review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-:-KpR1aFd2cIX5Z6SSU-x:b-sxc74e)*

**Comment by SeanCurtis-TRI** [comment]
Generally :LGTM:, but I have one question for my own edification.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpR81lSxUazQn2GEF2X:-KpR7Oy7ay7uxBmSSiWt:b-5586zz) ([raw file](https://github.com/robotlocomotion/drake/blob/cde8b9b4cfb1e2f853e7c70aadcd07e5f6fd2a7b/drake/common/test/symbolic_expression_transform_test.cc#L64)):*
> ```cpp
> //   lhs.cast<Expresion>() * rhs  ==  (lhs * rhs).cast<Expresion>()
> //
> template <typename LhsTransform, typename RhsTransform>
> ```

BTW These tests could trivially pass if  `lhs.template cast<Expression>()` does something trivially bad. (i.e., if everything was the equivalent of zeros). 

It seems that the `cast` method is integral for what is being tested, but our expected answer arises from the use of that same method. More generally, I would expect to see an expected answer that arises from a unique code path.

For future generations, can you add a note about why this is sufficient?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-:-KpR98ViFtgTJ7MMVMGn:bh1idmg)*

**Comment by soonho-tri** [comment]
+@ericcousineau-tri , platform-review please.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 64 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpR81lSxUazQn2GEF2X:-KpRA0eAtBZ_8kcUqKMt:b-50q104) ([raw file](https://github.com/robotlocomotion/drake/blob/cde8b9b4cfb1e2f853e7c70aadcd07e5f6fd2a7b/drake/common/test/symbolic_expression_transform_test.cc#L64)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW These tests could trivially pass if  `lhs.template cast<Expression>()` does something trivially bad. (i.e., if everything was the equivalent of zeros). 

It seems that the `cast` method is integral for what is being tested, but our expected answer arises from the use of that same method. More generally, I would expect to see an expected answer that arises from a unique code path.

For future generations, can you add a note about why this is sufficient?
</blockquote></details>

Done (added a test with expected answers).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-:-KpR9jWmYYOJQwqucYze:b14x3pl)*

**Comment by soonho-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 149 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRR2mp56Hr-q0jGY7Q:-KpRSWFiQsuXtSZb3Ju_:b9cedjm) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L149)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I suspect you're missing a line here:

`EXPECT_EQ(isometry_expr * isometry_double).matrix(), expected_expr_double);`
</blockquote></details>

Done. Thanks for catching it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604)*

**Comment by soonho-tri** [comment]
+@ggould-tri , meta-platform-review please.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRN2b8CWinSwmg8B2h:-KpRW584TAruyruYaeue:b-gdd25v) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L15)):*
I changed the code to use `X/Y/ZRotation` and I think the code is cleaner now.

> Could we possibly make an intrinsic body-fixed x-y'-z'' variant of rpy2rotmat?
(I can make that issue, if you like.)

Probably? But I'd like to ask @seancurtis-tri to make a decision.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 25 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRMyEseVPTmSr72SGI:-KpRTrdfAHQ7w03XwYEI:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L25)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Would it be possible to compact this into `affine_.translation() << 1, 2, 3;`?
</blockquote></details>

Done.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 142 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRS1u3RhXipcOigE4R:-KpRU14OW7mbk6iIo1Nh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Can you describe `expected_expr_double` and `expected_double_expr` with a quick comment? Something like `Expected result from Transform<Expression> * Transform<double>`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-:-KpRWKEFLEfytxhSo_45:b-dpripg)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRN2b8CWinSwmg8B2h:-KpRbi4tW7Fj-ZPxUqEW:bprcyvg) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L15)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I changed the code to use `X/Y/ZRotation` and I think the code is cleaner now.

> Could we possibly make an intrinsic body-fixed x-y'-z'' variant of rpy2rotmat?
(I can make that issue, if you like.)

Probably? But I'd like to ask @seancurtis-tri to make a decision.
</blockquote></details>

Sounds good. Will mark this as satisfied since this is just an aside. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604)*

**Comment by SeanCurtis-TRI** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/test/symbolic_expression_transform_test.cc, line 15 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-KpRN2b8CWinSwmg8B2h:-KpRmlkdEKgkvSExi_gW:bomb595) ([raw file](https://github.com/robotlocomotion/drake/blob/9e5a044551ebd444bf505c4f1f5bbb5384bfef51/drake/common/test/symbolic_expression_transform_test.cc#L15)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Sounds good. Will mark this as satisfied since this is just an aside. Thanks!
</blockquote></details>

Somehow, I missed myself tagged on that. I'm indifferent. I've used libraries that had `XYZRotation`, `ZYXRotation`, etc. methods. They're nice and compact, but frequently underused. I find this a definite improvement and sufficiently compact. But I can conceive the value of having the last layer of syntatic sugar at some point down the road.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6604#-:-KpV4NcTiN9VG39X5Fyi:bnfp4nl)*

**Pull request merged**
