### PR TITLE
[workspace] Build NLopt from source

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Compared to the Ubuntu and macOS packages, this removes the LGPL'd "luksan" solver from the build, which means we can link the library statically (and eventually, hidden). This might mean that NLopt is no longer able to solve certain kinds of programs, but that is a fair trade-off given all of the problems caused by LGPL linking.

The `package.BUILD.bazel` is modeled on `nlopt.BUILD.bazel` in a10ebb7.

Deprecate the now-unused current (host OS) nlopt external.

Towards #17231 and #16872.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-focal-clang-bazel-experimental-address-sanitizer please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-valgrind-memcheck please
@drake-jenkins-bot linux-focal-clang-bazel-experimental-undefined-behavior-sanitizer please

**Review by jwnimmer-tri — COMMENTED** [review]
+(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288#-:-N3C9yQT9H4Mqurewg9U:b7ovtzr)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9FzCBeG8XT8zeDWc):*
Working

Check homebrew and Ubuntu sources to see if they've added any useful patching which we'd now be losing out on.
___
*[`tools/workspace/dreal/repository.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9RhhC4DPZFi-Fi8F:-N3C9RhhC4DPZFi-Fi8G:b6l9azn) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/dreal/repository.bzl#L18)):*
> ```Starlark
>         ],
>         repo_mapping = {
>             "@nlopt": "@nlopt_internal",
> ```

Working

Since we don't do dReal counterexamples in Drake, it _seems_ like we should be able to stop using nlopt, but I haven't figured out how so far.
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9cYsE5RMm9uLa7Sc:-N3C9cYt2KbLwA6uENG5:b-i4s3s0) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L50)):*
> ```
>     outs = ["src/api/nlopt.hpp"],
>     cmd = " ".join([
>         "cmake",
> ```

Working

Possibly we should vendor the enums into out git, so that we can avoid using CMake at build-time.  (We would still use it a test-time to check that our enums are up-to-date.)
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9nrA9t1vgrN3ioI0:-N3C9nrA9t1vgrN3ioI1:b-w6iijw) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L65)):*
> ```
>         ":nlopt_config.h",
>         # This list exactly matches CMakeLists.txt NLOPT_SOURCES, except that
>         # we have removed all of the "src/algs/luksan/**" sources (LGPL).
> ```

Working

Possibly we should have a cross-check on the list of sources vs CMakeLists.
___
*[`tools/workspace/nlopt_internal/patches/remove-luksan.patch` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9s85AnvJxBe-8s_7:-N3C9s86APVNSBVFDWIM:b-kvb3au) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/patches/remove-luksan.patch#L1)):*
> ```Diff
> TBD
> ```

Working

Describe what's going on here.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9FzCBeG8XT8zeDWc):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Check homebrew and Ubuntu sources to see if they've added any useful patching which we'd now be losing out on.
</blockquote></details>

OK

[Hombrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/nlopt.rb) doesn't add patches, it just disables multi-language bindings.

[Ubuntu](https://packages.ubuntu.com/focal/libnlopt-cxx0) has patches to fix the install locations and soname, but nothing to the code itself.
___
*[`tools/workspace/dreal/repository.bzl` line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9RhhC4DPZFi-Fi8F:-N3KOkMUCwfdLKHFg786:b-9w1et5) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/dreal/repository.bzl#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Since we don't do dReal counterexamples in Drake, it _seems_ like we should be able to stop using nlopt, but I haven't figured out how so far.
</blockquote></details>

OK actually we _do_ seem to have `use_local_optimization` set to true by default, so this will need to stay.

https://github.com/RobotLocomotion/drake/blob/f8d36f4233450f8d0cd51f55c59f2b6c6c62019f/solvers/dreal_solver.cc#L566-L570
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9cYsE5RMm9uLa7Sc:-N3KaSDH9RwIFCqfuRZ3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L50)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Possibly we should vendor the enums into out git, so that we can avoid using CMake at build-time.  (We would still use it a test-time to check that our enums are up-to-date.)
</blockquote></details>

Done.
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3MNN-i8JChP7uBYL4a:-N3MNN-i8JChP7uBYL4b:bsssny6) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L58)):*
> ```
> )
> 
> # TODO(jwnimmer-tri) Compile this using vendor_cxx.
> ```

Working

To avoid loader conflicts, we should do this immediately as part of this PR.
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9nrA9t1vgrN3ioI0:-N3MMct_8t3IsnZ15IIf:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L65)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Possibly we should have a cross-check on the list of sources vs CMakeLists.
</blockquote></details>

Done.
___
*[`tools/workspace/nlopt_internal/patches/remove-luksan.patch` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3C9s85AnvJxBe-8s_7:-N3KPlx81M719mW46TSg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/patches/remove-luksan.patch#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Describe what's going on here.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)* status: needs platform reviewer assigned, needs at least two assigned reviewers, commits need curation (https://drake.mit.edu/reviewable.html#curated-commits)

___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 58 at r1](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3MNN-i8JChP7uBYL4a:-N3Ph86v3jImhKBIUr0W:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/9252809c425b35dccc4604c75070784a2130f924/tools/workspace/nlopt_internal/package.BUILD.bazel#L58)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

To avoid loader conflicts, we should do this immediately as part of this PR.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

(Apologies; there's a few typos I missed originally, noted in review comments.  I'll push a fix for them after the bonus CI runs return their results.)

\CC @hongkai-dai FYI

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288#-:-N3aLbgED8PxMmf7FAW7:b-ta0sul)* status: 4 unresolved discussions, LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri and @rpoyner-tri)

___
*[`tools/workspace/dreal/patches/warnings.patch` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aKJZfEMfkn5_DXhR9:-N3aKJZfEMfkn5_DXhRA:bcfpzzz) ([raw file](https://github.com/robotlocomotion/drake/blob/85151ef06051e982885b9b3537fed4e6e07462fe/tools/workspace/dreal/patches/warnings.patch#L1)):*
> ```Diff
> TBD
> ```

Working

The problem we're dealing with here is this console spam:

`external/dreal/dreal/optimization/nlopt_optimizer.h:44:7: warning: 'dreal::NloptOptimizer' declared with greater visibility than the type of its field 'dreal::NloptOptimizer::opt_' [-Wattributes]`

I need to place a comment here (instead of the TBD) explaining that, and probably a TODO here to try to vendor-build dReal as well.
___
*[`tools/workspace/nlopt_internal/package.BUILD.bazel` line 191 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aLJIOAiMe10yxyLbq:-N3aLJIOAiMe10yxyLbr:bervhm8) ([raw file](https://github.com/robotlocomotion/drake/blob/85151ef06051e982885b9b3537fed4e6e07462fe/tools/workspace/nlopt_internal/package.BUILD.bazel#L191)):*
> ```
> )
> 
> # The _SRCS_AGS and _HDRS_AGS cover the NLOPT_CXX sources from the upstream
> ```

Working

typo



_Suggestion:_
```
NLOPT_CXX11
```
___
*[`tools/workspace/nlopt_internal/test/enum_test.py` line 41 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aKbCN0kK0_mxhr_jc:-N3aKbCN0kK0_mxhr_jd:b-4uoqpf) ([raw file](https://github.com/robotlocomotion/drake/blob/85151ef06051e982885b9b3537fed4e6e07462fe/tools/workspace/nlopt_internal/test/enum_test.py#L41)):*
> ```Python
>         expected = re.sub(r'\s+\\', r' \\', expected)
> 
>         # Compare
> ```

Working

nit punc
___
*[`tools/workspace/nlopt_internal/patches/remove_luksan.patch` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aKtQr4HuRZmr4r50G:-N3aKtQr4HuRZmr4r50H:bervhm8) ([raw file](https://github.com/robotlocomotion/drake/blob/85151ef06051e982885b9b3537fed4e6e07462fe/tools/workspace/nlopt_internal/patches/remove_luksan.patch#L1)):*
> ```Diff
> Remove NLopt's dependency on it's internal luksan algorithm library.
> ```

Working

typo



_Suggestion:_
```Diff
its
```

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aYhAyCHLxmxvPCvHh:-N3aYhAz7FFzMg_jpxeP:b-yo1qut) (no related file):*
Working

macOS build indicates that Ubuntu is probably still leaking system NLopt a bit.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3aYhAyCHLxmxvPCvHh:-N3a_pZu6uISzrZPiMcP:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

macOS build indicates that Ubuntu is probably still leaking system NLopt a bit.
</blockquote></details>

Done.

___

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-big-sur-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for platform review, if you have time please?  You have some familiarity with the solvers externals' build system over the years.  (Sorry, I meant to tag @ggould-tri on call today but the updated Reviewable dashboard makes those reminders more difficult to recall now.)

**Review by ggould-tri — COMMENTED** [review]
@sammy-tri btw, if you don't have the time, I'd be happy to take this platform review for you.

> Reviewed 4 of 11 files at r1, 6 of 15 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288#-:-N3y_5VwDyL8xKOiaede:bixdibr)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @rpoyner-tri and @sammy-tri)

**Comment by jwnimmer-tri** [comment]
FYI the rebase surfaces a build error.  I'll need to make some small edits here before pushing it.

**Review by jwnimmer-tri — COMMENTED** [review]
Let's do +@ggould-tri -@sammy-tri for platform review load balancing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288#-:-N3z1LbC-jwr-jGOF_fw:b7q8fx7)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @rpoyner-tri)

___
*[`tools/workspace/nlopt_internal/patches/gen_enums.patch` line 4 at r5](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3yzQ_08Go9xNDHolQe:-N3z1KBtBhJiNnN1wOb0:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/c71afed349a974892677d07fefedbe08d6d0a624/tools/workspace/nlopt_internal/patches/gen_enums.patch#L4)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

grammar? missing words?
</blockquote></details>

Done.

**Comment by ggould-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3z7M7w5MezgrLxW96U:-N3z7M7w5MezgrLxW96V:b-gn8o5q) (no related file):*
Running this locally, I get bazel errors even with a clean--expunge.  Not sure if this is an actual bazel issue or not.
```
ggould@baymax:~/git/drake$ bazel clean --expunge
INFO: Invocation ID: 275f3581-043e-4f60-ab7c-5522fb5ea81c
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ggould@baymax:~/git/drake$ bazel test @nlopt_internal//...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 742f4597-1e37-463d-9191-3eae020dab63
INFO: Analyzed 10 targets (49 packages loaded, 471 targets configured).
INFO: Found 10 targets and 0 test targets...
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: missing input file 'external/nlopt_internal/src/AUTHORS', owner: '@nlopt_internal//:src/AUTHORS'
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: missing input file 'external/nlopt_internal/src/NEWS', owner: '@nlopt_internal//:src/NEWS'
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: 2 input file(s) do not exist
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8 Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: 2 input file(s) do not exist
INFO: Elapsed time: 8.340s, Critical Path: 0.08s
INFO: 21 processes: 21 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3z7M7w5MezgrLxW96U:-N3z9n1v7EXtiSGkrMOw:b5li1y0) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

Running this locally, I get bazel errors even with a clean--expunge.  Not sure if this is an actual bazel issue or not.
```
ggould@baymax:~/git/drake$ bazel clean --expunge
INFO: Invocation ID: 275f3581-043e-4f60-ab7c-5522fb5ea81c
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ggould@baymax:~/git/drake$ bazel test @nlopt_internal//...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 742f4597-1e37-463d-9191-3eae020dab63
INFO: Analyzed 10 targets (49 packages loaded, 471 targets configured).
INFO: Found 10 targets and 0 test targets...
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: missing input file 'external/nlopt_internal/src/AUTHORS', owner: '@nlopt_internal//:src/AUTHORS'
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: missing input file 'external/nlopt_internal/src/NEWS', owner: '@nlopt_internal//:src/NEWS'
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8: Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: 2 input file(s) do not exist
ERROR: /media/sdb1/ggould/.cache/bazel/_bazel_ggould/330cdd996cb32c1347931fe9e349adad/external/nlopt_internal/BUILD.bazel:331:8 Middleman _middlemen/external_Snlopt_Uinternal_Sinstall-runfiles failed: 2 input file(s) do not exist
INFO: Elapsed time: 8.340s, Critical Path: 0.08s
INFO: 21 processes: 21 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
</blockquote></details>

Aha, this PR fails to install the license notices.  Working.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288)* status: LGTM missing from assignee ggould-tri(platform) (waiting on @ggould-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3z7M7w5MezgrLxW96U:-N3zAq_46ruNEpE1ecDE:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Aha, this PR fails to install the license notices.  Working.
</blockquote></details>

Done.

___

**Review by ggould-tri — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 15 files at r2, 1 of 1 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/17288#-:-N3z72Zc4omuYMztzr-4:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/17288#-N3z7M7w5MezgrLxW96U:-N3zGYD42ARtJcNHhTJP:bw03ysw) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Verified working.

___

**Pull request merged**
