### PR TITLE
Avoid Diagram pollution when opted-out of LCM

### LINKED ISSUE #20668: support disabling LCM in VisualizationConfig
visualization_config.h already has [this TODO](https://github.com/RobotLocomotion/drake/blob/b78faae30159e2615316330c451db5f02243c706/visualization/visualization_config.h#L13):
> TODO(jwnimmer-tri or trowell-tri) Add an option to disable LCM entirely.

We don't use meldis/DrakeVisualizer at all on Deepnote. Having DrakeVisualizer added automatically is potential computational inefficient and leads to more complex/confusing output when drawing the graphviz diagrams. But in the last weeks I also saw many instances of student projects which had LCM warnings in their notebook output. Now I definitely want to disable LCM visualization by default in my implementation of the single-process simulation-only hardware station.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #20668.

---

Using this patch to the example demo:

```
--- a/examples/hardware_sim/example_scenarios.yaml
+++ b/examples/hardware_sim/example_scenarios.yaml
@@ -3,6 +3,7 @@
 
 # This demo simulation shows an IIWA arm with an attached WSG gripper.
 Demo:
+  simulation_duration: 0
   directives:
   - add_model:
       name: amazon_table
@@ -46,9 +47,8 @@ Demo:
       parent: wsg_on_iiwa
       child: wsg::body
   lcm_buses:
-    driver_traffic:
-      # Use a non-default LCM url to communicate with the robot.
-      lcm_url: udpm://239.241.129.92:20185?ttl=0
+    default:
+      lcm_url: memq://null
   cameras:
     oracular_view:
       name: camera_0
@@ -56,8 +56,5 @@ Demo:
         translation: [1.5, 0.8, 1.25]
         rotation: !Rpy { deg: [-120, 5, 125] }
   model_drivers:
-    iiwa: !IiwaDriver
-      hand_model_name: wsg
-      lcm_bus: driver_traffic
-    wsg: !SchunkWsgDriver
-      lcm_bus: driver_traffic
+    iiwa: !ZeroForceDriver {}
+    wsg: !ZeroForceDriver {}
```

I end up with this graphviz:

sim

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20671)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@RussTedrake for high-level review, please.  (Or feature review, if you like.)

This follows the same pattern as the iiwa driver (and others) -- instead of an LCM on/off toggle flag in every individual sub-struct, the user configures the `LcmBuses` to specify that by default no LCM happens anywhere.  This extends the null-awareness to two more subsystems -- the visualizer config, and the rgbd camera config.

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.
Sorry for the delay. Thanks for this.  I've confirmed it also allows me to clean up the use case in my course notes.  
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20671#-:-NmeqxvHAWsTm5tkk1f_:bfiuopg)* status: needs at least two assigned reviewers

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20671#-:-Nmwx2UfCunPkZLCA414:b-z0s7k5)* status: LGTM missing from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20671#-:-NnAODh-ArzkI57_CFkM:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),RussTedrake(platform)

**Comment by jwnimmer-tri** [comment]
I might have made a mistake here...

When opted-out of LCM, we end up ignoring the `fps` configuration setting.  We should probably be adding `RgbdSensorDiscrete` in that case, not `RgbdSensor`?

Also \CC @SeanCurtis-TRI FYI on this PR.

**Comment by SeanCurtis-TRI** [comment]
> we end up ignoring the fps configuration setting. We should probably be adding RgbdSensorDiscrete in that case, not RgbdSensor?

I'm not sure I get the concern here.

Ultimately, the only thing we typically have pulling on the `RgbdSensor` is the lcm publisher, right? So, no LCM means no rendering. If that's the only thing pulling on the sensor, then not actually rendering seems a good thing. If, on the other hand, there is something else pulling on the sensor's output (at its own arbitrary rate), then rendering happens. Swapping to a discrete sensor doesn't seem like a good thing -- it'd be rendering images that aren't getting consumed by anything; all work, no gain. And if anything *else* were pulling on that sensor, we've changed its behavior based on the fact we opted out of LCM. That wouldn't be right.

**Comment by jwnimmer-tri** [comment]
> Ultimately, the only thing we typically have pulling on the RgbdSensor is the lcm publisher, right?

No.  For example, a perception System might be attached to the image output port of the sensor, alongside the LCM publisher.

> If that's the only thing pulling on the sensor, then not actually rendering seems a good thing.

This is a performance optimization.  If we really care, we could enhance the framework to communicate to a system when its output port is not connected, in which case it could skip unnecessary updates.

> If, on the other hand, there is something else pulling on the sensor's output (at its own arbitrary rate), then rendering happens.

We are modeling a _physical sensor that actually has a discrete frame rate_.  Each downstream system that's connected to the output port should see the _same_ image.  Downstream systems are _not supposed to have different rates_.

If the user wants an instantaneous, continuous-time sensor, then `fps = infinity` would be the way to communicate that.

> And if anything else were pulling on that sensor, we've changed its behavior based on the fact we opted out of LCM. That wouldn't be right.

I'm arguing that someone relying on the `fps` to be ignored is wrong, and we should (possibly with deprecation) switch to something more sensible.

Right now the fps is documented as "publish rate".  I'm arguing we should change it to mean "photograph rate" or "output rate", and that the publish rate naturally defaults to that rate.  In other words, a continuous-time sensor is the _arcane_ use case, so we should not cater to it.  Rather, we default to a sensible periodic (stepped) model, and the user has to opt-out of that.

**Comment by SeanCurtis-TRI** [comment]
It seems you didn't read my whole comment before you started responding -- I'll try not to make the same mistake.

Here's my best interpretation of your key point:

> People shouldn't use `RgbdSensor` unless they truly want to do the wrong thing.

Then there are some ancillary points (which should not be interpreted as counter arguments, merely side issues that would also need to be addressed):
  - You've left an out for people to do the "wrong" thing, but then we wouldn't have a way to specify a publication rate of that continuous sensor. That seems a step beyond simply not "catering to it".
  - As for your "optimization" idea about omitting calculations for unconnected ports, that presumably would be just enough API so that a system can ask if its port is connected and choose to skip operations that would become meaningless? It's not like there's a higher-level of abstraction that would cause events to not be evaluated or the like, right? `LeafSystem`s would have to opt in to that kind of optimization on a per-`System` basis.

I don't particularly have an issue with saying Drake defaults to a more physical, discrete camera model. I simply hadn't realized you weren't suggesting we do it *conditionally*, but, rather, *universally*.

**Pull request merged**
