### PR TITLE
[contact_properties] Add testing for scalar conversion to AutoDiffXd

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This embodies workflow issue illustrated in #18396
This now tests the behavior of interaction w/ scalar conversion, and confirms behavior fix in #18397

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@amcastro-tri and +@seancurtis-tri for review, please!
\cc @xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399#-:-NISDpam5MDeRwwzpny7:b-lr1i3t)* status: LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform), missing label for release notes (waiting on @amcastro-tri and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Pass done

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399#-:-NIY4RCzCup3fnJ8uQjz:b1y7mb0)* status: 4 unresolved discussions, LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform), missing label for release notes (waiting on @amcastro-tri and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Rxg5cT7-G9QDacT:-NIXywC04Yaq5JuuvD-i:bdc8gbe) (no related file):*
Ultimately, I felt this was more arcane than it needed to be. I have an alternate bid (see #18403). For some reason, unclear to me right now, I wasn't able to submit a PR against your branch. Am I missing collaborator permissions?  PTAL.

___
___
*[`multibody/plant/test/contact_properties_test.cc` line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIXt5kQ02N1sHjX2QPa:-NIXt5kQ02N1sHjX2QPb:bp0dtho) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L123)):*
> ```cpp
>   }
> 
>   /*
> ```

nit: For better or worse, the comments in this doc (few though they are) are of the `//` variety and not the `/*` variety.
___
*[`multibody/plant/test/contact_properties_test.cc` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIXzUc_-KvyL3E2CD4V:-NIXzUc_-KvyL3E2CD4W:born7ym) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L138)):*
> ```cpp
>           AutoDiffXd{}, scene_graph_ad_->model_inspector());
>     } catch (...) {
>       // N.B. SCOPED_TRACE does not help when an exception occurs.
> ```

Generally this feels like some arcane voodoo. Its abstractions make it difficult to grok:

1. Stop gap to allow type deduction.
2. Workaround on scoped trace.
3. grokking the `Lambda` requires careful parsing of the documentation.

As near as I can tell, this is all about softening the blow if the implicit scalar promotion fails. That feels like a lot friction for something we don't expect to happen. See my linked alternative. Let me know what you think.
___
*[`multibody/plant/test/contact_properties_test.cc` line 240 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Ne53TkmCR-jZrCu:-NIY4Ne53TkmCR-jZrCv:bskrd7l) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L240)):*
> ```cpp
>         using T = decltype(T_dummy);
>         const auto data = GetCoulombFriction(g_A_, inspector);
>         // Sum the values as a *very* naive way to check general convresion.
> ```

nit s/convresion/conversion

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Rxg5cT7-G9QDacT:-NIZDEd01b9tWdlAIS3b:bhyq906) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Ultimately, I felt this was more arcane than it needed to be. I have an alternate bid (see #18403). For some reason, unclear to me right now, I wasn't able to submit a PR against your branch. Am I missing collaborator permissions?  PTAL.
</blockquote></details>

Huh, not sure why you couldn't do that...

But yeah, I'm down for either formulation. Addressed some items.
Will comment on your PR as well.

___
___
*[`multibody/plant/test/contact_properties_test.cc` line 123 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIXt5kQ02N1sHjX2QPa:-NIZDCYp2L8pdbjBkBkL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L123)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: For better or worse, the comments in this doc (few though they are) are of the `//` variety and not the `/*` variety.
</blockquote></details>

Done.
___
*[`multibody/plant/test/contact_properties_test.cc` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIXzUc_-KvyL3E2CD4V:-NIZDQm-DdruHb6NDjCk:bh80m7) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L138)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Generally this feels like some arcane voodoo. Its abstractions make it difficult to grok:

1. Stop gap to allow type deduction.
2. Workaround on scoped trace.
3. grokking the `Lambda` requires careful parsing of the documentation.

As near as I can tell, this is all about softening the blow if the implicit scalar promotion fails. That feels like a lot friction for something we don't expect to happen. See my linked alternative. Let me know what you think.
</blockquote></details>

While yes, it's some friction, it doesn't seem like that much?
But per above, yeah, down for whatever is best. Will review proposed PR!
___
*[`multibody/plant/test/contact_properties_test.cc` line 240 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Ne53TkmCR-jZrCu:-NIZDDQ07rQ7Y3tPwVFS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L240)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit s/convresion/conversion
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Rxg5cT7-G9QDacT:-NIZTWzh65yqU1kfhqXX:bn9ms57) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Huh, not sure why you couldn't do that...

But yeah, I'm down for either formulation. Addressed some items.
Will comment on your PR as well.
</blockquote></details>

Let me know what you think of the newest version of the alternative.

___
___
*[`multibody/plant/test/contact_properties_test.cc` line 138 at r1](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIXzUc_-KvyL3E2CD4V:-NIZTNMj263zglc6xcag:bpc0uzj) ([raw file](https://github.com/robotlocomotion/drake/blob/337b205d01cf2646d7743cded2dbcbe583d663eb/multibody/plant/test/contact_properties_test.cc#L138)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

While yes, it's some friction, it doesn't seem like that much?
But per above, yeah, down for whatever is best. Will review proposed PR!
</blockquote></details>

Based on the newest version of the alt spelling, I'd suggest at this point that this piece of arcanum doesn't provide sufficient value.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/18399)* status: 2 unresolved discussions, LGTM missing from assignees amcastro-tri,SeanCurtis-TRI(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits), missing label for release notes (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/18399#-NIY4Rxg5cT7-G9QDacT:-NIZnKDl0P2bf0JTo59Y:bkb6c2n) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Let me know what you think of the newest version of the alternative.
</blockquote></details>

Love it! Will close this if we move forward with yours!

___

**Pull request closed without merging**
