### PR TITLE
Further respect DISABLE_PYTHON to keep memory checkers happy

### PR DESCRIPTION
**Pull request by jamiesnape**
Python is still needed for build infrastructure, but that does not affect memcheck.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4239)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
+@mwoehlke-kitware for feature review.

**Comment by mwoehlke-kitware** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/CMakeLists.txt, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-KXHU78pTP_i_nM7vWFr:-KXHU78tgjpZ7-xAZhLf:b8hc7tg) ([raw file](https://github.com/robotlocomotion/drake/blob/d7577cfedc43e55eef03a777542f5af711ede0d0/drake/lcmtypes/CMakeLists.txt#L87)):*
> ```CMake
> )
> 
> if(NOT DISABLE_PYTHON)
> ```

If we're going to skip *installing* the bindings, we probably shouldn't *generate* them either... see other types libraries for examples of making Python generation conditional (hint: similar to Java).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by jamiesnape** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/lcmtypes/CMakeLists.txt, line 87 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-KXHU78pTP_i_nM7vWFr:-KXHlxyGhwVOnhy5KeWR:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/d7577cfedc43e55eef03a777542f5af711ede0d0/drake/lcmtypes/CMakeLists.txt#L87)):*
<details><summary><i>Previously, mwoehlke-kitware (Matthew Woehlke) wrote…</i></summary>
> If we're going to skip *installing* the bindings, we probably shouldn't *generate* them either... see other types libraries for examples of making Python generation conditional (hint: similar to Java).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-gcc-experimental-matlab-open-source please
@drake-jenkins-bot linux-gcc-ninja-experimental please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab please
@drake-jenkins-bot linux-gcc-ninja-experimental-matlab-open-source please
@drake-jenkins-bot mac-clang-experimental please
@drake-jenkins-bot mac-clang-experimental-matlab please
@drake-jenkins-bot mac-clang-ninja-experimental please

**Comment by mwoehlke-kitware** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-:-KXILggTtwLuMpQfiT88:bnfp4nl)*

**Comment by jamiesnape** [comment]
+@david-german-tri for platform review.

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/CMakeLists.txt, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-KXf_mch3-VzMCCSU-Pi:-KXf_mciPjeEbrjZOF9F:b-1ptsg2) ([raw file](https://github.com/robotlocomotion/drake/blob/0e17cf03b6645335837b26eb4c44fb0cea0c63cb/drake/bindings/CMakeLists.txt#L8)):*
> ```CMake
> if(SWIG_EXECUTABLE)
>   add_subdirectory(swig)
>   if(NOT DISABLE_PYTHON)
> ```

BTW is this redundant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-:-KXfa3TCSs4g_fL8txMe:bnfp4nl)*

**Comment by david-german-tri** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/CMakeLists.txt, line 8 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4239#-KXf_mch3-VzMCCSU-Pi:-KXfffyD-EG20xpvYPy8:bgxwkr8) ([raw file](https://github.com/robotlocomotion/drake/blob/0e17cf03b6645335837b26eb4c44fb0cea0c63cb/drake/bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

BTW is this redundant?
</blockquote></details>

BTW no, though I doubt may people will have MATLAB enabled and Python disabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4239)*

**Pull request merged**
