### PR TITLE
Update lcm_vector_gen to create "LcmSystem2" translators

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
FYI, it may be worth peeking at the three separate commits.  The first is a non-functional refactor of the existing code.  The second is the new feature.  The third is the script-generated code changes.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3268)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Not sure who to tag for feature review here; @maddog-tri or @liangfok if you feel like you have cycles to look at this, please self-assign and begin feature review.

**Comment by liangfok** [comment]
+@liangfok since I need to fix any problems this causes in #3103.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQ6qnDrSlsWMuPg5PLc:b-n7jm4j)*

**Comment by liangfok** [comment]
While I did look over the Python code that generates the C++ code, I admit I did not pay as much attention to it as I did the generated C++ code. I'm hoping that any defects in the Python-based generator will show up as defects in the generated C++.

I left some comments. PTAL.

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Cars/gen/driving_command_translator.cc, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9C--spMmHtAu1TJYx:-KQ9C--spMmHtAu1TJYy:b-52yaxt) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.cc#L10)):*
> ```cpp
> #include "drake/common/drake_assert.h"
> 
> namespace drake {
> ```

Should this code be further name spaced:
```
namespace examples {
namespace cars {
```
?

Same comment for all other translator files below.

Maybe the desired namespace can be passed as a command line parameter to `lcm_vector_gen.py`?

---

*[drake/examples/Cars/gen/driving_command_translator.cc, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9A6--M_1-gFH3XKpr:-KQ9A6-0-sxgzKMbNl-S:b-zcvqzv) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.cc#L29)):*
> ```cpp
>     systems::VectorBase<double>* vector_base) const {
>   DRAKE_ABORT_UNLESS(vector_base != nullptr);
>   auto* const vector = dynamic_cast<DrivingCommand<double>*>(vector_base);
> ```

BTW: nit: A variable named `vector` may at first be confused with a data type called `vector` as evidenced by the fact that it shows up as being blue in Reviewable.

(same comment to all other generated files)

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQ9AbAws5M3_e-N4na6:b-m6rfom) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
> ```objc
> #pragma once
> 
> // This file is generated by a script.  Do not edit!
> ```

BTW: This and the other generated C++ files in this PR do not appear to have unit test coverage. It would be ideal if unit tests covering the generated code could also be generated. However, given we are in a sprint, I would be OK if the plan is to achieve unit test coverage once the translators in this PR are used in an example application.

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AysYBdZBBucCS75I:-KQ9AysYBdZBBucCS75J:bov4zzw) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L14)):*
> ```objc
> 
> /**
>  * Translates between LCM message objects and vector objects for the
> ```

BTW: Consider adding "System 2.0" before "vector" to prevent someone from thinking it's a different kind of vector like `std::vector` or what not. After all, we qualify "message" with "LCM" in the same sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQ98hFXRhSUfOLLwJbU:b-sjy4i4)*

**Comment by jwnimmer-tri** [comment]
> While I did look over the Python code that generates the C++ code, I admit I did not pay as much attention to it as I did the generated C++ code. I'm hoping that any defects in the Python-based generator will show up as defects in the generated C++.

To a degree, yes.  But the python code should still be readable and maintainable by us for future revisions, so it's still important to read through.

---

Review status: 7 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Cars/gen/driving_command_translator.cc, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9C--spMmHtAu1TJYx:-KQAzgzrxkI_wWPfdbnq:b-hi8i8k) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.cc#L10)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should this code be further name spaced:
> ```
> namespace examples {
> namespace cars {
> ```
> ?
> 
> Same comment for all other translator files below.
> 
> Maybe the desired namespace can be passed as a command line parameter to `lcm_vector_gen.py`?
</details>
TBH I hadn't eally been worrying about that yet.  (If we want to do it, I'll just hard-code it into the script like several other things; parameterization can come later.)  But now that I've thought about it more, the fact that ROS uses `examples/Cars` as a library means that we _should_ use a namespace other than bare `drake`, for this entire directory.

How about a follow-up PR that fixes this throughout `examples/Cars` including all of the other code as well?

---

*[drake/examples/Cars/gen/driving_command_translator.cc, line 29 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9A6--M_1-gFH3XKpr:-KQAxAkRgo911YGYBp5b:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.cc#L29)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: nit: A variable named `vector` may at first be confused with a data type called `vector` as evidenced by the fact that it shows up as being blue in Reviewable.
> 
> (same comment to all other generated files)
</details>
Done.

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQAxICyqynm5QJLIn9j:bifzqvx) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: This and the other generated C++ files in this PR do not appear to have unit test coverage. It would be ideal if unit tests covering the generated code could also be generated. However, given we are in a sprint, I would be OK if the plan is to achieve unit test coverage once the translators in this PR are used in an example application.
</details>
(Aside: let's not worry about the sprint too much; let's do this right.  If a fix is too time-consuming, I will instead just `TODO` it, but I can't imagine any that would be so cumbersome.)  Now on to the comment...

Unit testing of generated code is a bit murky.  Usually one would not generate unit tests (how would you know they are correct any more than the generated vector class?), but rather test the generator itself.  Here, since we are committing the generated code, the pre-merge code inspection already suffices for a fair degree of "coverage", in lieu of a unit test.

For most of this code, if it compiles it's good enough, and furthermore any defect in the vector code generation half would show up in the unit tests for things like `SimpleCar` that regularly use these types.

Could you help me think of defects that wouldn't be caught by pre-merge code inspection nor the `SimpleCar` unit test?  Such a thing would be useful to have focused testing for.

I suppose some kind of encode/decode round trip isn't really covered anywhere yet.  Maybe that's the most relevant?

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 14 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AysYBdZBBucCS75I:-KQAzYkYogviK2IZS3Un:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L14)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: Consider adding "System 2.0" before "vector" to prevent someone from thinking it's a different kind of vector like `std::vector` or what not. After all, we qualify "message" with "LCM" in the same sentence.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQAt_ibiscKP5cDQfDd:b-uj7ve7)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQBSsA8QjZ0ubD37zMr:b-f753or) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> (Aside: let's not worry about the sprint too much; let's do this right.  If a fix is too time-consuming, I will instead just `TODO` it, but I can't imagine any that would be so cumbersome.)  Now on to the comment...
> 
> Unit testing of generated code is a bit murky.  Usually one would not generate unit tests (how would you know they are correct any more than the generated vector class?), but rather test the generator itself.  Here, since we are committing the generated code, the pre-merge code inspection already suffices for a fair degree of "coverage", in lieu of a unit test.
> 
> For most of this code, if it compiles it's good enough, and furthermore any defect in the vector code generation half would show up in the unit tests for things like `SimpleCar` that regularly use these types.
> 
> Could you help me think of defects that wouldn't be caught by pre-merge code inspection nor the `SimpleCar` unit test?  Such a thing would be useful to have focused testing for.
> 
> I suppose some kind of encode/decode round trip isn't really covered anywhere yet.  Maybe that's the most relevant?
</details>
I have started work on a round-trip unit test, but it will required a preparatory refactoring to the translator APIs.  I will submit that separately, and rebase this PR once that one is merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by liangfok** [comment]
Alright I will review the Python code soon.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/Cars/gen/driving_command_translator.cc, line 10 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9C--spMmHtAu1TJYx:-KQC5tg9YUa4peAQMqTH:b3vpo4) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.cc#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> TBH I hadn't eally been worrying about that yet.  (If we want to do it, I'll just hard-code it into the script like several other things; parameterization can come later.)  But now that I've thought about it more, the fact that ROS uses `examples/Cars` as a library means that we _should_ use a namespace other than bare `drake`, for this entire directory.
> 
> How about a follow-up PR that fixes this throughout `examples/Cars` including all of the other code as well?
</details>
OK.  SGTM.

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQC65Dn2u8cL2re1Azn:b-kj80f9) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> I have started work on a round-trip unit test, but it will required a preparatory refactoring to the translator APIs.  I will submit that separately, and rebase this PR once that one is merged.
</details>
Yes, when I wrote the comment I was thinking of the round trip tests in https://github.com/RobotLocomotion/drake/tree/master/drake/systems/lcm/test.

Sorry I was not more clear. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQC6oZPLiHIqR7U_IYK:b-u6rdjk)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQDdLphUtvTGiI9Q8FF:b-mlcrg0) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Yes, when I wrote the comment I was thinking of the round trip tests in https://github.com/RobotLocomotion/drake/tree/master/drake/systems/lcm/test.
> 
> Sorry I was not more clear. 
</details>
A gist of the proposed unit test is here:
https://gist.github.com/jwnimmer-tri/7cefcbc044533f58a308c178b68a3a3a
Blocked on #3285 before I can push it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by liangfok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/examples/Cars/gen/driving_command_translator.h, line 3 \[r1\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQ9AbAws5M3_e-N4na5:-KQDjnii0fnPCf-CfgVx:b7ty71u) ([raw file](https://github.com/robotlocomotion/drake/blob/e1b66b3aae46a8fe1650d98664707c4f54adfc65/drake/examples/Cars/gen/driving_command_translator.h#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> A gist of the proposed unit test is here:
> https://gist.github.com/jwnimmer-tri/7cefcbc044533f58a308c178b68a3a3a
> Blocked on #3285 before I can push it here.
</details>
OK. I see you're avoiding _actual_ LCM transmission.

Looking at #3285 now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by liangfok** [comment]
I completed first round of feature review of python code.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 156 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEIMJCGdIFixj8qreI:-KQEIMJDep3ODr9NOfxM:bgals58) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L156)):*
> ```Python
> #include <Eigen/Core>
> 
> #include "lcmtypes/drake/lcmt_%(snake)s_t.hpp"
> ```

Should either alpha sort this or insert a blank line here.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 205 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEJ4EZ-QvgdgFo37vC:-KQEJ4EZ-QvgdgFo37vD:bgals58) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L205)):*
> ```Python
> // See %(generator)s.
> 
> #include "lcmtypes/drake/lcmt_%(snake)s_t.hpp"
> ```

Should either alpha sort this or insert a blank line here.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 276 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEHATeh8zNqJz5XUcd:-KQEHATeh8zNqJz5XUce:b-v9nfe4) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L276)):*
> ```Python
>     put(cc, LCM_TO_VECTOR_BASE_BEGIN % context, 1)
>     # pylint: disable=unused-variable
>     for k, field in enumerate(fields):
> ```

BTW: I believe the `pylint` suppression can be eliminated by using:

```python
for field in fields:
```

---

*[drake/examples/Cars/lcm_vector_gen.py, line 304 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEJcJFyRjaUw7NtKV9:-KQEJcJFyRjaUw7NtKVA:b-v9nfe4) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L304)):*
> ```Python
>     put(cc, VECTOR_BASE_TO_LCM_BEGIN % context, 1)
>     # pylint: disable=unused-variable
>     for k, field in enumerate(fields):
> ```

BTW: I believe the `pylint` suppression can be eliminated by using:

```python
for field in fields:
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQEJtUmNX_bGdKa0lcf:bu4lv9a)*

**Comment by jwnimmer-tri** [comment]
Do not review the `drake/systems/lcm` edits; they are part of #3285 which I've rebased this PR onto, so should be reviewed there instead.  They will disappear here once #3285 is merged.

---

Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 156 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEIMJCGdIFixj8qreI:-KQFvun_oDozJaUecRXM:b-p0os3k) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L156)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should either alpha sort this or insert a blank line here.
</details>
Ah, good catch.  The generated code is `clang-format`'d, which often fixes things like this.  _However_ it looks like the Trusty clang doesn't fix it (buy my Xenial clang does), which is why @rpoyner's and my generated code were disagreeing.

Done.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 205 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEJ4EZ-QvgdgFo37vC:-KQFwC175mTpAf6fGqor:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L205)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> Should either alpha sort this or insert a blank line here.
</details>
Done.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 276 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEHATeh8zNqJz5XUcd:-KQFyjOnXP1uOWskNv3o:b-uixdql) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L276)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: I believe the `pylint` suppression can be eliminated by using:
> 
> ```python
> for field in fields:
> ```
</details>
Ah, `k`is unused, yes.  (Removed now.)  But the comment is still required, because `fields` is only used indirectly, via `locals()`.  Done.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 304 \[r2\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQEJcJFyRjaUw7NtKV9:-KQFyvBeGX1i1zi8z196:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/4c8e59eac82d0c16538e554227088adb2bfb6bc8/drake/examples/Cars/lcm_vector_gen.py#L304)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW: I believe the `pylint` suppression can be eliminated by using:
> 
> ```python
> for field in fields:
> ```
</details>
Done.

---

*[drake/systems/lcm/lcm_and_vector_base_translator.h, line 1 \[r5\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQFx_mCR70SJcmrOada:-KQFx_mCR70SJcmrOadb:bxqw9tc) ([raw file](https://github.com/robotlocomotion/drake/blob/90d29e6f2cb451ed2e647ba1739b18bf4d96ff73/drake/systems/lcm/lcm_and_vector_base_translator.h#L1)):*
> ```objc
> #pragma once
> ```

Do not review the `drake/systems/lcm` edits; they are part of #3285 which I've rebased this PR onto, so should be reviewed there instead.  They will disappear here once #3285 is merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQFxonRoWODN300u8Ve:bxqw9tc)*

**Comment by liangfok** [comment]
Reviewed 1 of 21 files at r3, 1 of 1 files at r6.
Review status: 2 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by jwnimmer-tri** [comment]
Tagging DNR / DNM.  Besides the #3285 rebase, there's also more incorrect LCM2 code going on, that I'll have to fix in a preemptive PR and rebase this onto.

**Comment by liangfok** [comment]
Reviewed 1 of 21 files at r3, 15 of 16 files at r4, 2 of 2 files at r5, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by jwnimmer-tri** [comment]
(Still "do not review".)

**Comment by jwnimmer-tri** [comment]
@liangfok This is ready for another round of feature review, please.

---

Review status: 7 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQW9vU1FAvvEPVw3o3q:b-51s2s)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 11 of 14 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KQWjwAezeb8GJXos69O:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@david-german-tri for platform review, please.

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 36 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb3JQVxvefjOidMCXZ:-KQb3JQVxvefjOidMCX_:bx41aam) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L36)):*
> ```Python
> def generate_indices(context, fields):
>     # pylint: disable=unused-variable
>     hh = context["hh"]
> ```

Let me see if I've got this. `context` comes from `locals()` in the stack frame above.  We extract the stuff we care about into names in this stack frame, and then call `locals()` again to generate a dictionary for the string substitution.  

Is it really a good idea to repurpose the program stack this way, instead of building a dictionary in a respectable manner?  I don't think it even saves much typing.  I'm no Python expert, though.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 42 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb1H116bO3peslrTgD:-KQb1H12T2MECcYs3EcB:b-ewohk4) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L42)):*
> ```Python
>     kname = "kNumCoordinates"
>     put(hh, INDICES_BEGIN % locals(), 1)
>     for k, field in enumerate(fields):
> ```

So...`k` is only used for substitution into a string from `locals()`?   Can it have a better name, and maybe a comment explaning this `locals` technique?

---

*[drake/examples/Cars/lcm_vector_gen.py, line 264 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb5ps7MKHH124O_xn8:-KQb5ps7MKHH124O_xn9:bkpl81j) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L264)):*
> ```Python
> 
> def generate_allocate_output_vector(context, fields):
>     cc = context["cc"]
> ```

Again, not a Python expert, but this really seems like it crosses a line.  You're giving the callee visibility into the caller's entire frame, you're using it to fish out arbitrary objects (file pointers) and do arbitrary things to them, and there's no way for a reader to understand this without careful study of the caller.  It's a macro in all but name.  Why not just pass the file as a separate argument?

---

*[drake/examples/Cars/lcm_vector_gen.py, line 265 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb6N4RSqsHl9TcoqNA:-KQb6N4RSqsHl9TcoqNB:b2phol) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L265)):*
> ```Python
> def generate_allocate_output_vector(context, fields):
>     cc = context["cc"]
>     put(cc, ALLOCATE_OUTPUT_VECTOR % context, 2)
> ```

BTW, I think `newlines_after=2` would be clearer (here and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by jwnimmer-tri** [comment]
I am going to stage a cleanup PR that will precede this one.  DNR / DNM on this for now.

**Comment by jwnimmer-tri** [comment]
Substantial rework pushed.  PTAL.

I suggest reviewing the `gen/*` files compared against your most recently reviewed revision, but all of the other files compared against bottom (⊥) as if you hadn't reviewed them yet.

---

Review status: 3 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 36 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb3JQVxvefjOidMCXZ:-KR0tH2TPc3rFPvQV4Um:b-42z0ys) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L36)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Let me see if I've got this. `context` comes from `locals()` in the stack frame above.  We extract the stuff we care about into names in this stack frame, and then call `locals()` again to generate a dictionary for the string substitution.  
> 
> Is it really a good idea to repurpose the program stack this way, instead of building a dictionary in a respectable manner?  I don't think it even saves much typing.  I'm no Python expert, though.
</details>
Done (during #3359).

---

*[drake/examples/Cars/lcm_vector_gen.py, line 42 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb1H116bO3peslrTgD:-KR0tHpBxvAYPhxWLByS:b-42z0ys) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L42)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> So...`k` is only used for substitution into a string from `locals()`?   Can it have a better name, and maybe a comment explaning this `locals` technique?
</details>
Done (during #3359).

---

*[drake/examples/Cars/lcm_vector_gen.py, line 264 \[r8\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KQb5ps7MKHH124O_xn8:-KR0tQTwoxAIi_WIbZvt:bx6m5) ([raw file](https://github.com/robotlocomotion/drake/blob/0608ef7a1e7e6e81419fd8baa7756843642ccb6e/drake/examples/Cars/lcm_vector_gen.py#L264)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Again, not a Python expert, but this really seems like it crosses a line.  You're giving the callee visibility into the caller's entire frame, you're using it to fish out arbitrary objects (file pointers) and do arbitrary things to them, and there's no way for a reader to understand this without careful study of the caller.  It's a macro in all but name.  Why not just pass the file as a separate argument?
</details>
Done (#3359).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KR0tkPtNv3idHeVDR55:b5jm49g)*

**Comment by jwnimmer-tri** [comment]
Jenkins had a remote procedure call flake (failure).
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
The retest was flaky too.  Hopefully it's healthy again now this morning.
@drake-jenkins-bot retest this please

**Comment by liangfok** [comment]
:lgtm: Just two BTW comments. CI failure appears to be a flake while uploading results.

---

Reviewed 11 of 17 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[drake/examples/Cars/lcm_vector_gen.py, line 37 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KR4U0jxvFFiZqUzKFVb:-KR4U0jxvFFiZqUzKFVc:bz36076) ([raw file](https://github.com/robotlocomotion/drake/blob/89e5d9f19c3b899b1c09b49fc2fe8d3721cfb7e5/drake/examples/Cars/lcm_vector_gen.py#L37)):*
> ```Python
>     """
>     Args:
>         fields is the list of fieldnames in the LCM message.
> ```

BTW, might as well document _all_ of the parameters (not just fields).

---

*[drake/examples/Cars/lcm_vector_gen.py, line 148 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KR4XLYevQID5VYlV4pq:-KR4XLYevQID5VYlV4pr:btdeyh5) ([raw file](https://github.com/robotlocomotion/drake/blob/89e5d9f19c3b899b1c09b49fc2fe8d3721cfb7e5/drake/examples/Cars/lcm_vector_gen.py#L148)):*
> ```Python
>     put(hh, DECODE_BEGIN % context, 1)
>     for k, field in enumerate(fields):
>         context.update(field = field)
> ```

BTW, on first glance `field = field` seems very odd. Consider renaming one of the variables. Maybe `field = current_field`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KR4XsMWKeUSMkVR80Cu:btpvlmo)*

**Comment by jwnimmer-tri** [comment]
*[drake/examples/Cars/lcm_vector_gen.py, line 148 \[r9\]](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-KR4XLYevQID5VYlV4pq:-KR4Zei5tDcYPLl6r6K6:b5cmquj) ([raw file](https://github.com/robotlocomotion/drake/blob/89e5d9f19c3b899b1c09b49fc2fe8d3721cfb7e5/drake/examples/Cars/lcm_vector_gen.py#L148)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary>
> BTW, on first glance `field = field` seems very odd. Consider renaming one of the variables. Maybe `field = current_field`?
</details>
That's just how python works; kwargs are bareword magical, but you get used to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
Fourth time's a charm?
@drake-jenkins-bot retest this please.

**Comment by jwnimmer-tri** [comment]
The builders finally all succeeded at once.  @david-german-tri just waiting on your comments now.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KR54Ox9YPY72GIoAFRi:bkvotsz)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3268#-:-KR57xHeE_Bm2naRmjt2:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Woot!  Thanks all.

**Pull request merged**
