### PR TITLE
Partially revert 5167

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Partially revert #5167:
- Copy automotive_demo.cc to dev_demo.cc
- Revert the village changes to automotive_demo.cc
- Port old automotive_demo to use new automotive_simulator

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5235)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Note that r1 and r2 in that File Matrix do not require review; only r3+ will be new code.

**Comment by liangfok** [comment]
:lgtm: Note that I did not review `dev_demo.cc`.

---

Reviewed 3 of 3 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake/automotive/automotive_demo.cc, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5235#-KdT9gGa6UAoXHcdOZVl:-KdT9gGb2jS_Qvv_YQHH:bn22kr1) ([raw file](https://github.com/robotlocomotion/drake/blob/3f36a51efdd851076f3c0a24a36004961156343f/drake/automotive/automotive_demo.cc#L30)):*
> ```cpp
> 
> std::string MakeChannelName(const std::string& name) {
>   static const std::string kDrivingCommandChannelName {"DRIVING_COMMAND"};
> ```

BTW, should this variable's name indicate it is the "Default"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5235#-:-KdTAe4ww_pCBBKeOmoC:bx9zw0o)*

**Comment by jwnimmer-tri** [comment]
*[drake/automotive/automotive_demo.cc, line 30 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5235#-KdT9gGa6UAoXHcdOZVl:-KdTBIAGdfmWbGh4VbFK:b-caoogn) ([raw file](https://github.com/robotlocomotion/drake/blob/3f36a51efdd851076f3c0a24a36004961156343f/drake/automotive/automotive_demo.cc#L30)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW, should this variable's name indicate it is the "Default"?
</blockquote></details>

There are about seven defects on that line.  Let's fix them in new PRs ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5235)*

**Comment by jwnimmer-tri** [comment]
Yup, it was already reviewed because its an exact copy of what's on master.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5235#-:-KdTB3ULqY6Ejs20vU9-:bp0w9zn)*

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-gcc-experimental-ros please

**Comment by jwnimmer-tri** [comment]
:lgtm: without platform review due to emergency.  It's only 33 LOC the only novel part of which is BUILD file tweaks, plus 2 SLOC of python demo hack.

**Pull request merged**
