### PR TITLE
Removed TODO that says LCM messages should be co-located with software that uses them.

### PR DESCRIPTION
**Pull request by liangfok**
For context, see: https://github.com/RobotLocomotion/drake/pull/2582#issuecomment-229120696

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/2682)

### CODE REVIEW

**Comment by liangfok** [comment]
+@jwnimmer-tri for feature review since he reviewed the previous version and this is such a small change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/2682#-:-KLNDq0XTCRTyl_0YBPS:-2112574676)*

**Comment by jwnimmer-tri** [comment]
The pre-existing TODO was correct.

**Comment by liangfok** [comment]
Oh, never mind. I now see that #2582 removes the TODO entirely.

**Comment by mwoehlke-kitware** [comment]
> Oh, never mind. I now see that #2582 removes the TODO entirely.

Right; per discussion there we decided the second part is okay as-is, and #2582 fixes the first part :smile:.

**Comment by jwnimmer-tri** [comment]
I strongly believe that things like `drake-distro/examples/Foo` should define their own LCM messages, and not dump them into `drake-distro/drake/lcmtypes`.  However, FTR, I am fine with that not being captured in a TODO.

**Comment by mwoehlke-kitware** [comment]
Eh... well, then, I have to ask, why are there LCM types that are specific to an example program? :wink:

Sure, if someone *really needs* a one-off type for an end-point like that, then it does make more sense to isolate it. On the plus side, having those be in their own packages should be much less onerous, and probably they only needs bindings for one language.

I didn't realize we had such critters...

**Comment by jwnimmer-tri** [comment]
As one example, `drake-distro/drake/examples/Cars/simple_car_gen.sh` generates three lcm message definitions, which it rolls into the Drake package (but shouldn't).  Some of the other examples like `Quadrotor` also have their own demo-specific messages to communicate with the robot(s).

**Pull request closed without merging**
