### PR TITLE
[visualization] Add contact visualization to meshcat defaults

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
To see this in action, run `bazel run //examples/hardware_sim:demo_py` and then click on the Meshcat link in the terminal once it starts running.

On master, there are no green arrows.  With this PR, there's one point-contact arrow pair.

Towards #17712.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both(?) reviews, please.

\CC @trowell-tri FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
Could I get you to extend the unit test a bit?  (See below.)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-:-NPTI6CN0OxlmICPiC-p:b-5gbkg)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`visualization/visualization_config_functions.h` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTFhDR6O3EYS4ldtcC:-NPTFhDR6O3EYS4ldtcD:b-nrkyl1) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.h#L145)):*
> ```objc
> ConvertVisualizationConfigToMeshcatParams(const VisualizationConfig&);
> 
> // (For unit testing only.)
> ```

BTW This phrase caused a moment of cognitive dissonance. This particular phrasing implies the *function* exists for "unit testing only". In fact, it's the *presence* of the function in the header that is for unit testing only. So, I read the comment, but then saw it called in the .cc file and thought...should we be calling something that's for unit testing only?
___
*[`visualization/visualization_config_functions.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTHdvXCswSq1R7AQAY:-NPTHdvXCswSq1R7AQAZ:b-k8gx7p) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.cc#L68)):*
> ```cpp
>     }
>     if (config.publish_contacts) {
>       ContactVisualizer<double>::AddToBuilder(
> ```

nit I'm not overly pleased that there's nothing in the test that detects this act actually took place. Seems simple enough to confirm the existence of the visualizer in the diagram.

**Comment by jwnimmer-tri** [comment]
*[`visualization/visualization_config_functions.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTHdvXCswSq1R7AQAY:-NPTIjz13ZBaTeKSkimE:bxq5b99) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.cc#L68)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit I'm not overly pleased that there's nothing in the test that detects this act actually took place. Seems simple enough to confirm the existence of the visualizer in the diagram.
</blockquote></details>

I did give that a spin.  The obvious check for `meshcat.GetPath("/drake/contact")` doesn't work.  That path doesn't show up until we have non-empty contact results.  Creating non-empty contact results didn't seem worth the effort versus the likelihood of this regressing.  LMK if you have any ideas.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`visualization/visualization_config_functions.h` line 145 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTFhDR6O3EYS4ldtcC:-NPTJq_D3t7GlweBeCZ2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.h#L145)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW This phrase caused a moment of cognitive dissonance. This particular phrasing implies the *function* exists for "unit testing only". In fact, it's the *presence* of the function in the header that is for unit testing only. So, I read the comment, but then saw it called in the .cc file and thought...should we be calling something that's for unit testing only?
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[`visualization/visualization_config_functions.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTHdvXCswSq1R7AQAY:-NPTK9Bk6chZakbcVr75:byz29vq) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.cc#L68)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I did give that a spin.  The obvious check for `meshcat.GetPath("/drake/contact")` doesn't work.  That path doesn't show up until we have non-empty contact results.  Creating non-empty contact results didn't seem worth the effort versus the likelihood of this regressing.  LMK if you have any ideas.
</blockquote></details>

I was literally thinking you'd check for the existence of the *system* that gets added by this new code. It's not proof that everything is working, but it's a pretty big necessary condition.  You certainly do passes through the diagram looking for `MeshcatVisualizer` instances -- it seems reasonable to look for the contact visualizer as well.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`visualization/visualization_config_functions.cc` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-NPTHdvXCswSq1R7AQAY:-NPTVlwv4-0MdCWTWR6I:baqbq15) ([raw file](https://github.com/RobotLocomotion/drake/blob/f5a700eaa5c9fa87e8277ff04aaa8855d090a17a/visualization/visualization_config_functions.cc#L68)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I was literally thinking you'd check for the existence of the *system* that gets added by this new code. It's not proof that everything is working, but it's a pretty big necessary condition.  You certainly do passes through the diagram looking for `MeshcatVisualizer` instances -- it seems reasonable to look for the contact visualizer as well.
</blockquote></details>

Thanks!  Indeed, you said that but I didn't read it carefully enough.  Done now.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18907#-:-NPTcJcFEpb8KFXEv1QG:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
