### PR TITLE
[systems] Add template instantiations for Diagram scalar conversion

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Hotfix for #18813.

Closes #18832.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18833)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-arm-monterey-clang-bazel-experimental-release please.
@drake-jenkins-bot mac-x86-monterey-clang-bazel-experimental-release please.

**Review by EricCousineau-TRI — COMMENTED** [review]
+@EricCousineau-TRI :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18833#-:-NOlXPWN4AlowN7I-Cdn:b-ld7fp5)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform)

**Comment by jwnimmer-tri** [comment]
The mac arm build shows that the loader error is fixed now.  The failure there is something else.

We can merge this once the Ubuntu builds pass.

**Comment by EricCousineau-TRI** [comment]
Was going to merge; however, `max-x86*` failure looks very odd:
https://drake-cdash.csail.mit.edu/test/972294403
```
Traceback (most recent call last):
  File "/Users/monterey/workspace/mac-x86-monterey-clang-bazel-experimental-release/_bazel_monterey/2caed80725be65f6af9d8aabf719e595/sandbox/darwin-sandbox/5956/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/systems/py/scalar_conversion_test.runfiles/drake/bindings/pydrake/systems/test/scalar_conversion_test.py", line 297, in test_diagram_sublcass
    self.assertIs(diagram_T.example.copied_from, diagram_U.example)
AssertionError: None is not <scalar_conversion_test.Example_ AutoDiffXd  object at 0x103a79370>
```

**Comment by EricCousineau-TRI** [comment]
I'm totes skeeved out by that failure, and would probably need quite some time to dig in / fix it.

Let's go with the revert for now?

**Comment by jwnimmer-tri** [comment]
Sure thing.  I'd only looked at the arm failure, assuming x86 would be the same.  It also passed on x86 locally.  Ah well, better safe.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI I'll leave it to you to carry this forward, or whatever other fix makes sense, as part of the unvert.  Closing.

**Pull request closed without merging**
