### PR TITLE
Bugfix for simulator attempting to drive error-controlled integrators…

### PR DESCRIPTION
**Pull request by edrumwri**
… with larger steps than the integrator maximum.

This fix addresses an unusual bug that occurs when an error controlled integrator is asked to step with a larger step than its maximum step *and* that larger step respects error estimates.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6447)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@siyuanfeng-tri for review please (since you happened to observe the bug)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-KniyrGdMdLTBF6fBxjT:bhnjrzb)*

**Comment by jwnimmer-tri** [comment]
Consider adding a unit test concurrently with the bugfix.

**Comment by siyuanfeng-tri** [comment]
Code seems to do what the doc says. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knizdi8uWVlEzj6ekrg:b-vc2bis)*

**Comment by jamiesnape** [comment]
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-everything please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-memcheck-lsan please

**Comment by edrumwri** [comment]
Added a unit test to detect this nasty little bug.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knj0GWFCKv3fjxrXqDo:buv862d)*

**Comment by edrumwri** [comment]
Thanks for the review Siyuan!

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-KnlOYEZrrWm7JLKyHxQ:bhx9l2q)*

**Comment by siyuanfeng-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by siyuanfeng-tri** [comment]
CI is very unhappy. 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knlksm9yJQI5xNdkp4Y:brnt7jk)*

**Comment by edrumwri** [comment]
+@soonho-tri for platform review please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-KnoEI3mA05uWowFs7Ri:b-10xzum)*

**Comment by soonho-tri** [comment]
Is anyone working on the CI issue?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-KnoFo_3S1zBhsvN5faW:b-ir391o)*

**Comment by edrumwri** [comment]
I'm checking it out right now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-KnoJExO_tPiTmCZJPcf:b-lmdkml)*

**Comment by edrumwri** [comment]
@drake-jenkins-bot retest this please

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knoa44_-EZHOgtCjuU6:bzdwe9o)*

**Comment by soonho-tri** [comment]
For the record, `bazel test //drake/systems/analysis/... -c dbg` gives me:

```
[ RUN      ] RK3IntegratorTest.MaxStepSizeRespected
drake/systems/analysis/test/runge_kutta3_integrator_test.cc:347: Failure
Expected: (integrator_->get_largest_step_size_taken()) <= (max_step_size), actual: 0.01 vs 0.01
```

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knoq3ERo_A9utanMMsE:b-7wdqgy)*

**Comment by soonho-tri** [comment]
:lgtm: (Thanks for the patience!)

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6447#-:-Knq1ELCopnXQPN6L8v8:bbtz3gd)*

**Pull request merged**
