### PR TITLE
Add BUILD files for drake/common/trajectories/qp_spline.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4314)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/qp_spline/test/BUILD, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4314#-KXq_kxqpfVVWsfOVw8s:-KXq_kxr6kAlmg6i8LO2:bvhwfsc) ([raw file](https://github.com/robotlocomotion/drake/blob/aca7ca4b5f288922ae025e4fd908f1f486ca3ca8/drake/common/trajectories/qp_spline/test/BUILD#L10)):*
> ```Python
>     "//drake/common:eigen_matrix_compare",
>     "@gtest//:main",
> ]
> ```

Dead variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4314#-:-KXq_ohnqhGR9gc78PgR:bnfp4nl)*

**Comment by david-german-tri** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/trajectories/qp_spline/test/BUILD, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4314#-KXq_kxqpfVVWsfOVw8s:-KXqa8r7zZ1J_zHDOoz5:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/aca7ca4b5f288922ae025e4fd908f1f486ca3ca8/drake/common/trajectories/qp_spline/test/BUILD#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Dead variable?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4314)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4314)*

**Comment by jwnimmer-tri** [comment]
Using override-merge for BUILD-only change.

**Pull request merged**
