### PR TITLE
Remove CMake documentation generation

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/7270)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@fbudin69500 for feature review.

**Comment by fbudin69500** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7270#-:-Kwb2rYSKdSu2ZpQEor_:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7270#-Kwb4aF-MBLII0TaEV4T:-Kwb4aF0vnxnUXSm05Qx:bsq0esp) ([raw file](https://github.com/robotlocomotion/drake/blob/6966da57c734882d496d3510e4d8352c0d251dd9/drake/doc/documentation_instructions.rst#L20)):*
> ```reStructuredText
> .. _documentation-generation-instructions-bazel:
> 
> When using Bazel
> ```

BTW Is "When using Bazel " semi-redundant now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7270#-:-Kwb4iK09xpcBPBheAkx:bnfp4nl)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/documentation_instructions.rst, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/7270#-Kwb4aF-MBLII0TaEV4T:-Kwb4u5z02rQoEwZK6FH:b-2dmkse) ([raw file](https://github.com/robotlocomotion/drake/blob/6966da57c734882d496d3510e4d8352c0d251dd9/drake/doc/documentation_instructions.rst#L20)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Is "When using Bazel " semi-redundant now?
</blockquote></details>

BTW Yes, there is a lot of cleanup. I will follow up once all the CMake is gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/7270)*

**Pull request merged**
