### PR TITLE
[pydrake] Add bindings for SimulatorConfig, MultibodyPlantConfig

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Add bindings for functions that operate on them: `AddMultibodyPlant`, `ApplySimulatorConfig`, `ExtractSimulatorConfig`.

Use `DefAttributesUsingSerialize` in `pydrake.common.schema` for consistency.

- [x] Requires #16718.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16717)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
\CC @dmcconachie-tri @DamrongGuoy FYI

**Comment by jwnimmer-tri** [comment]
+@dmcconachie-tri would you like to feature review this?

**Review by dmcconachie-tri — COMMENTED** [review]
Checkpoint, will finish tomorrow.

> Reviewed 2 of 17 files at r1, 3 of 12 files at r2, 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16717#-:-MxbEVMvBGpryU3McPZQ:b-s161o7)* status: 3 unresolved discussions, LGTM missing from assignee dmcconachie-tri, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @dmcconachie-tri and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16717#-Mxb7DYa-62ot4DuW0jy:-Mxb7DYa-62ot4DuW0jz:bbi09wk) (no related file):*
BTW `DoorHingeConfig` in `bindings/pydrake/multibody_tree/tree_py.cc` looks like a prime candidate for this as well, though the base `struct` doesn't appear to have a `Serialize` function written.

---
___
*[bindings/pydrake/common/schema_py.cc, line 47 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-Mxb8TV887WjvxkqEQXZ:-Mxb8TV887WjvxkqEQX_:b-l68wpu) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/common/schema_py.cc#L47)):*
> ```cpp
>         .def(py::init<>(), cls_doc.ctor.doc)
>         .def(py::init<const Class&>(), py::arg("other"))
>         .def(py::init<double>(), py::arg("value"), cls_doc.ctor.doc);
> ```

BTW, consider `.def(py::init<double>(), py::arg("value"), cls_doc.ctor.doc);` vs `.def(ParamInit<Class>());` throughout for similar consistency? Might be a downgrade in terms of docstrings; I have not looked into the details of `ParamInit`.
___
*[bindings/pydrake/multibody/BUILD.bazel, line 115 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbAZXW2jAQhXJIY0VW:-MxbAZXW2jAQhXJIY0VX:byf9cw9) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/BUILD.bazel#L115)):*
> ```Starlark
>         "//bindings/pydrake/common:type_safe_index_pybind",
>         "//bindings/pydrake/common:value_pybind",
>     ],
> ```

TIL that `drake_pybind_library` automatically adds `//:drake_shared_library` as a `cc_deps`, and thus adding extra drake includes doesn't trigger IWYU extra deps.
___
*[bindings/pydrake/multibody/plant_py.cc, line 1058 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbBzQj9Zr43J8LK_ZC:-MxbBzQj9Zr43J8LK_ZD:b-u95m3a) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/plant_py.cc#L1058)):*
> ```cpp
>             .doc_3args_systemsDiagramBuilder_double_stduniqueptr);
> 
>     if constexpr (std::is_same_v<T, double>) {
> ```

nit: Is it worth adding a N.B. that `AddMultibodyPlant` is only defined in ++ for `double` and thus the same is done here?
___
*[bindings/pydrake/multibody/plant_py.cc, line 1221 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbBXQG6SP9Zsq_1XSO:-MxbBXQG6SP9Zsq_1XSP:bdsccz8) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/plant_py.cc#L1221)):*
> ```cpp
>     using Class = MultibodyPlantConfig;
>     constexpr auto& cls_doc = doc.MultibodyPlantConfig;
>     py::class_<Class> cls(m, "MultibodyPlantConfig", cls_doc.doc);
> ```

minor: per https://drake.mit.edu/doxygen_cxx/group__python__bindings.html I think this should be defined before it is used by `AddMultibodyPlant`.
___
*[bindings/pydrake/multibody/test/plant_test.py, line 238 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbE60n09woKpFD_fyG:-MxbE60n09woKpFD_fyH:b-q0ymzi) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/test/plant_test.py#L238)):*
> ```Python
>         config = MultibodyPlantConfig(time_step=0.01)
>         self.assertEqual(config.time_step, 0.01)
>         copy.copy(config)
> ```

nit: Test the default constructor and `deepcopy` as is done for the `common/schema_py.cc` objects?
___
*[bindings/pydrake/multibody/test/plant_test.py, line 243 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbEGvM29AaO-K7xLqd:-MxbEGvM29AaO-K7xLqe:b-m0djyu) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/test/plant_test.py#L243)):*
> ```Python
>         plant, scene_graph = AddMultibodyPlant(config, builder)
>         self.assertIsNotNone(plant)
>         self.assertIsNotNone(scene_graph)
> ```

BTW: Is there a good way to test the `keep_alive` settings?

**Review by dmcconachie-tri — COMMENTED** [review]
:lgtm: with minor comments.

> Reviewed 1 of 17 files at r1, 2 of 12 files at r2, 9 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16717#-:-MxdXIBn5PsQt53VNpUJ:b-68qyxo)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[bindings/pydrake/multibody/plant_py.cc, line 1221 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbBXQG6SP9Zsq_1XSO:-MxdTTtf7ekKr-S3mTJy:br0esqr) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/plant_py.cc#L1221)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it is?  This line precedes `DoScalarDependentDefinitions` below.
</blockquote></details>

Ah, I overlooked that, you are correct.
___
*[bindings/pydrake/systems/analysis_py.cc, line 239 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxdWXLQEtz4lARcwEuF:-MxdWXLRC1lnI-qO5SnS:bh20rex) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/systems/analysis_py.cc#L239)):*
> ```cpp
>       .def("ApplySimulatorConfig",
>           overload_cast_explicit<void, Simulator<double>*,
>               const SimulatorConfig&>(&ApplySimulatorConfig),
> ```

nit: Locally `&ApplySimulatorConfig<double>` compiles and `py/analysis_test` passes. Any particular reason to use `overload_cast_explicit`? Ditto `ExtractSimulatorConfig` below.



_Code quote:_
```cpp
          overload_cast_explicit<void, Simulator<double>*,
              const SimulatorConfig&>(&ApplySimulatorConfig),
```
___
*[bindings/pydrake/systems/analysis_py.cc, line 242 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxdWw9pAoIk73aDi_Jt:-MxdWw9pAoIk73aDi_Ju:bd00jyn) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/systems/analysis_py.cc#L242)):*
> ```cpp
>           py::arg("simulator"), py::arg("config"),
>           pydrake_doc.drake.systems.ApplySimulatorConfig.doc)
>       .def("ExtractSimulatorConfig",
> ```

minor: The surrounding functions are instantiated for both `double` and `AutoDiffXd` types; any reason not to do the same for `{Apply,Extract}SimulatorConfig`?
___
*[bindings/pydrake/systems/test/analysis_test.py, line 116 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxdTsiG8ss-PW11u1RH:-MxdTsiG8ss-PW11u1RI:b-hwcoqs) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/systems/test/analysis_test.py#L116)):*
> ```Python
>         config = SimulatorConfig(target_realtime_rate=2.0)
>         self.assertEqual(config.target_realtime_rate, 2.0)
>         copy.copy(config)
> ```

nit: Test the default constructor and deepcopy as is done for the common/schema_py.cc objects?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16717)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @dmcconachie-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/16717#-Mxb7DYa-62ot4DuW0jy:-Mxe7nLx0Q9kJ-1hkrg4:b-6uml4g) (no related file):*
<details><summary><i>Previously, dmcconachie-tri (Dale McConachie) wrote…</i></summary><blockquote>

BTW `DoorHingeConfig` in `bindings/pydrake/multibody_tree/tree_py.cc` looks like a prime candidate for this as well, though the base `struct` doesn't appear to have a `Serialize` function written.
</blockquote></details>

Good find, but I'll defer that from this PR just to keep moving forward.

---
___
*[bindings/pydrake/multibody/test/plant_test.py, line 238 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxbE60n09woKpFD_fyG:-Mxe7bRWCHzP_E3Vj73V:b-l84b8z) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/multibody/test/plant_test.py#L238)):*
> Test the default constructor ...

Done.

> ... and deepcopy ...

Because the binding code is only a single line of code (`DefCopyAndDeepCopy`), a single unit test is sufficient.
___
*[bindings/pydrake/systems/analysis_py.cc, line 242 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxdWw9pAoIk73aDi_Jt:-Mxe7EAh92Ixt6D7id38:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/systems/analysis_py.cc#L242)):*
<details><summary><i>Previously, dmcconachie-tri (Dale McConachie) wrote…</i></summary><blockquote>

minor: The surrounding functions are instantiated for both `double` and `AutoDiffXd` types; any reason not to do the same for `{Apply,Extract}SimulatorConfig`?
</blockquote></details>

Done.
___
*[bindings/pydrake/systems/test/analysis_test.py, line 116 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16717#-MxdTsiG8ss-PW11u1RH:-Mxe6mXr1xlqDlXj5BhE:b-l84b8z) ([raw file](https://github.com/robotlocomotion/drake/blob/8ac0bbca46c30cf6f07b032bf2af12cade2fd6c4/bindings/pydrake/systems/test/analysis_test.py#L116)):*
> Test the default constructor ...

Done.

> ... and deepcopy ...

Because the binding code is only a single line of code (`DefCopyAndDeepCopy`), a single unit test is sufficient.

**Review by dmcconachie-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16717)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Pull request merged**
