### PR TITLE
Small refactor to the rod2d code.

### PR DESCRIPTION
**Pull request by edrumwri**
Removes code duplication by moving gravitational force and external force computation to a single function.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5971)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
Just two little BTW's. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/rod2d/rod2d-inl.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj3ca_QNg67tHcJa46X:-Kj3ca_QNg67tHcJa46Y:bz2y2ry) ([raw file](https://github.com/robotlocomotion/drake/blob/3eeb3bb5ba2e6af94050acbcb778e69c508ca3b4/drake/examples/rod2d/rod2d-inl.h#L55)):*
> ```objc
> }
> 
> // Computes the external forces on the rod.
> ```

BTW, for a split second I forgot this was 2D. Maybe add line explaining what each component in the returned 3d vector are and especifically stating the third component is the moment about the center of mass.

---

*[drake/examples/rod2d/rod2d-inl.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj3bYTB825aLofli65y:-Kj3bYTB825aLofli65z:bxsbk8u) ([raw file](https://github.com/robotlocomotion/drake/blob/3eeb3bb5ba2e6af94050acbcb778e69c508ca3b4/drake/examples/rod2d/rod2d-inl.h#L61)):*
> ```objc
>   // Compute the external forces (expressed in the world frame).
>   const int port_index = 0;
>   const auto input = this->EvalEigenVectorInput(context, port_index);
> ```

BTW, what `auto` resolves to is not clear from the context (unless of course you played with this API for a while). I recommend explicitly stating the return type: `const VectorX<T> input = this->EvalEigenVectorInput(context, port_index);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-:-Kj3dGOcHgZGCinYM2_J:b-kiqlgo)*

**Comment by edrumwri** [comment]
Thanks Alejandro (trying to throw an easier one your way after that 2k+ line monster!)

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/examples/rod2d/rod2d-inl.h, line 55 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj3ca_QNg67tHcJa46X:-Kj4H079xOp50Kipgfo6:bm7h3nw) ([raw file](https://github.com/robotlocomotion/drake/blob/3eeb3bb5ba2e6af94050acbcb778e69c508ca3b4/drake/examples/rod2d/rod2d-inl.h#L55)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, for a split second I forgot this was 2D. Maybe add line explaining what each component in the returned 3d vector are and especifically stating the third component is the moment about the center of mass.
</blockquote></details>

BTW Done.

---

*[drake/examples/rod2d/rod2d-inl.h, line 61 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj3bYTB825aLofli65y:-Kj4IcdEZ-yg3TesDTre:bgrrpfm) ([raw file](https://github.com/robotlocomotion/drake/blob/3eeb3bb5ba2e6af94050acbcb778e69c508ca3b4/drake/examples/rod2d/rod2d-inl.h#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

BTW, what `auto` resolves to is not clear from the context (unless of course you played with this API for a while). I recommend explicitly stating the return type: `const VectorX<T> input = this->EvalEigenVectorInput(context, port_index);`
</blockquote></details>

BTW done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-:-Kj4JHSeFCmTz_fnZhm5:bovftr7)*

**Comment by edrumwri** [comment]
+@jwnimmer-tri for platform review please per regular rotation

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-:-Kj4JTHsD787RtLsB8oj:b1isc0m)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj4LMjlIVzaq8kNVulX:-Kj4LMjlIVzaq8kNVulY:bb84xjn) (no related file):*
FYI So this is definitely an improvement, but having skimmed over the whole file now, I think many of the identifiers are unnecessarily smashed together, e.g., `fext` vs `f_ext` or `thetadot` vs `theta_dot`, etc.  Some cases are more or less usable (e.g., `thetadot` scans pretty well), but I think when multiple words are abbreviated into a single word with no separator, a reader might not immediately realize what the unpacking of the full name is.

Even though math papers and matlab code tend to use highly abbreviated variable names, I would encourage us to aim for making the code as readable as possible, which I think for several places in this file would argue for less obscure variable naming for casual readers.  A bad smell, for example, is when a variable needs a comment to explain its name at its point of declaration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-:-Kj4LMNo3iHcZ04DP-SQ:bnfp4nl)*

**Comment by edrumwri** [comment]
Thanks for the reviews, guys!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-Kj4LMjlIVzaq8kNVulX:-Kj4_T9bERwMienq8gRc:b6beovg) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI So this is definitely an improvement, but having skimmed over the whole file now, I think many of the identifiers are unnecessarily smashed together, e.g., `fext` vs `f_ext` or `thetadot` vs `theta_dot`, etc.  Some cases are more or less usable (e.g., `thetadot` scans pretty well), but I think when multiple words are abbreviated into a single word with no separator, a reader might not immediately realize what the unpacking of the full name is.

Even though math papers and matlab code tend to use highly abbreviated variable names, I would encourage us to aim for making the code as readable as possible, which I think for several places in this file would argue for less obscure variable naming for casual readers.  A bad smell, for example, is when a variable needs a comment to explain its name at its point of declaration.
</blockquote></details>

BTW This is the first in the series of a few refactors, but am interested to hear about any particular variables you'd like to see renamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5971#-:-Kj4_kFl94gpiB1xid-T:br6m9ia)*

**Comment by jwnimmer-tri** [comment]
My starting premise is that every multi-word abbreviation should separate its words with either capital-lowercase boundaries or underscores; `sin_theta`, `theta_dot`, `f_ext`, `fN`.  For `nc` and `ngc` I would instead of using `ngc` everywhere define typedefs for the sized matrixes of interested.  (It reads weird to have `lowercase` as a template argument!)

**Comment by amcastro-tri** [comment]
I agree with @jwnimmer-tri here. Specifically for `nc` and `ngc` we could probably rename them to `num_contacts` and `num_generalized_coordinates`?
The number of friction directions `nk` would probably need a similar refactor. A nicely documented typedef for the LCP matrix MM (now hard-coded to be of size 8x8) would be nice!

**Comment by edrumwri** [comment]
Ok, thanks guys. I'll keep this mind as I continue refactoring.


--------------------------------
Evan Drumwright
Senior Research Scientist
http://positronicslab.github.io
Toyota Research Institute
Palo Alto, CA

**Pull request merged**
