### PR TITLE
Change name of generated BUILD files to BUILD.bazel

### PR DESCRIPTION
**Pull request by jamiesnape**
And add comment to files to indicate that they are generated. The inconsistency in the file names was bothering me way too much, I guess....

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8459)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for feature review.

**Comment by jwnimmer-tri** [comment]
:lgtm:  I am OK as single reviewer if you prefer.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.BUILD.tpl, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/8459#-L8ZPNcel7329Hz2tN3-:-L8ZPNcgYLcTGXjNpSD3:b7ubv1y) ([raw file](https://github.com/robotlocomotion/drake/blob/7c635493c92a2c30dbc35381a20db5bbd49e3234/tools/workspace/pkg_config.BUILD.tpl#L3)):*
> ```Smarty
> # -*- python -*-
> 
> # DO NOT EDIT: generated by pkg_config_repository()
> ```

This is slightly misleading, because indeed this file _should_ be modified -- only the emitted BUILD.bazel should not be.

One solution is to amend the comment to be slightly more specific.

Another solution is to use `%{topcomment}` substitution or similar here, and substitute that with a disclaimer when calling the substitution logic elsewhere.

(For the BUILD.bazel files which are inline strings, I don't think this applies, but for this case of a separate template file I think its different.  We can't use that way here though, because the user being able to fork this tpl and replace it with customized rules is part of the API contract.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8459#-:-L8ZQ8HB6d4CfAN3C7z6:b-ix5o31)*

**Comment by jwnimmer-tri** [comment]
I don't know why the install test is failing, but switching the unittest assert to use https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertSetEqual would be a win in any case.

**Comment by jamiesnape** [comment]
> I don't know why the install test is failing, but switching the unittest assert to use https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertSetEqual would be a win in any case.

Done.

---

Review status: 12 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/pkg_config.BUILD.tpl, line 3 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake/8459#-L8ZPNcel7329Hz2tN3-:-L8bo7kv1B27vcQEyjoT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/7c635493c92a2c30dbc35381a20db5bbd49e3234/tools/workspace/pkg_config.BUILD.tpl#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is slightly misleading, because indeed this file _should_ be modified -- only the emitted BUILD.bazel should not be.

One solution is to amend the comment to be slightly more specific.

Another solution is to use `%{topcomment}` substitution or similar here, and substitute that with a disclaimer when calling the substitution logic elsewhere.

(For the BUILD.bazel files which are inline strings, I don't think this applies, but for this case of a separate template file I think its different.  We can't use that way here though, because the user being able to fork this tpl and replace it with customized rules is part of the API contract.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8459#-:-L8boAJr-yoT0zRWZair:bbs785l)*

**Comment by jwnimmer-tri** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[tools/workspace/vtk/repository.bzl, line 590 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/8459#-L8bqLc1tr0_4O4NqZRE:-L8bqLc1tr0_4O4NqZRF:b7yvyuh) ([raw file](https://github.com/robotlocomotion/drake/blob/bcdf6a605935bf3c07fa82419f9554c657ffbd85/tools/workspace/vtk/repository.bzl#L590)):*
> ```Python
> filegroup(
>     name = "vtk",
>     srcs = glob(["**/*"], exclude=["BUILD", "WORKSPACE"]),
> ```

BTW This needs to be BUILD.bazel (its the CI failure).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8459)*

**Comment by jamiesnape** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/workspace/vtk/repository.bzl, line 590 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake/8459#-L8bqLc1tr0_4O4NqZRE:-L8bqyZKDQBpX-dVrkcT:b-nhuv2a) ([raw file](https://github.com/robotlocomotion/drake/blob/bcdf6a605935bf3c07fa82419f9554c657ffbd85/tools/workspace/vtk/repository.bzl#L590)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This needs to be BUILD.bazel (its the CI failure).
</blockquote></details>

Done. Thanks, I missed that totally.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake/8459)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/8459)*

**Pull request merged**
