### PR TITLE
adds optional names for output ports

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9437)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
If it confuses the compiler, it is also likely to confuse users, even if we find a trick to placate the compiler.

I'll again advocate for the "wither" design -- where starting a `Declare()` gives you a handle that you call `with_name` and `with_model_value` on, and then when the handle is destroyed, no further edits can be made.  For pydrake, we'd just make them all kwargs instead of using the wither.  In this way, we don't need combinatorially many overloads, and its easy to add more (optional) port attributes later.

**Comment by sherm1** [comment]
Make sense though I don't get the last step yet. How does the temporary `OutputPortBuilder` object turn into an `OutputPort&` ?

**Comment by jwnimmer-tri** [comment]
We'd provide an implicit conversion operator, which I think would be invoked by default in most cases.  We'd also offer `Finalize()` I imagine, to force it in cases for clarify / funkyness.

**Comment by sherm1** [comment]
@RussTedrake -- yes, I've been working on it and will push something for you to look at asap (probably Friday).

**Comment by RussTedrake** [comment]
Superceded by #9459.

**Pull request closed without merging**
