### PR TITLE
Revert "Disable spurious required MATLAB dependency not found warnings"

### PR DESCRIPTION
**Pull request by jamiesnape**
Reverts RobotLocomotion/drake#3374

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3401)

### CODE REVIEW

**Comment by jamiesnape** [comment]
https://drake-jenkins.csail.mit.edu/view/Continuous/job/linux-gcc-experimental-matlab/99/

**Comment by david-german-tri** [comment]
At first glance, I can't figure out why this is the culprit, though I agree it makes sense to test the revert given the timing.

**Comment by jamiesnape** [comment]
I am a little puzzled too.

**Comment by jamiesnape** [comment]
False alarm, I guess.

**Pull request closed without merging**
