### PR TITLE
automotive: begin to apply python style.

### PR DESCRIPTION
**Pull request by rpoyner-tri**
* PEP8 white space.
 * Delete pointless semicolons.
 * Convert some comments to docstrings.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4876)

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
This is the first step of a campaign to bring our existing code more in line with the recently ratified python style proposal. There will be a few of these fix-up patches forthcoming, and eventually some recommendations for tooling configuration and usage.

+@maddog-tri for feature review.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4876#-:-KbGGLuF-GtC3mXGpY7K:b-vj8nux)*

**Comment by maddog-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4876#-:-KbH-cZW0BRH9VdNFXRi:bnfp4nl)*

**Comment by rpoyner-tri** [comment]
+@sherm1 for platform review.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4876#-:-KbHByAxqvaAQuRVN6zj:bfvx2sg)*

**Comment by sherm1** [comment]
Per platform rotation: -@sherm1 +@david-german-tri 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4876#-:-KbHEIgyvKUcV8wBg0q9:b8jz92o)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4876#-:-KbHI_Q_SCjhx9pmoXYV:bnfp4nl)*

**Pull request merged**
