### PR TITLE
[solvers] MathematicalProgram adds and stores QuadraticConstraint.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Currently except for IPOPT/NLOP/SNOPT (which support generic nonlinear constraints), none of the other solvers will support quadratic constraints.

In the future PRs, I will modify each solver wrapper to support convex quadratic constraint.

Towards #6341

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@AlexandreAmice for feature review please since you asked about quadratic constraints. Thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-:-NQgxFQ472vBrPbQ0EOc:bjprnh8)* status: LGTM missing from assignee AlexandreAmice, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
A few nits but overall :lgtm: 

> Reviewed 12 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-:-NQq0RTt2bsMc-xFDc3k:b-jpqym0)* status: 5 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/get_program_type.cc` line 206 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpwsaV43tzow8j8LAd:-NQpwsaW98929YhZMaH1:bqk3ucl) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/get_program_type.cc#L206)):*
> ```cpp
>   // constraints).
>   // 3. It has at least one of : generic costs, generic constraints, non-convex
>   // quadratic cost, linear complementarity constraints, quadratic constraints.
> ```

nit: I assume that the plan will be to make this `non-convex quadratic constraint1 in a few PRs, but for now you want to leave all quadratic constraints as NLP constraints as that is the current API. If this is the case I will mark myself as satisfied.



_Code quote:_
```cpp
 quadratic constraints
```
___
*[`solvers/mathematical_program.h` line 1883 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpvkV449z553iAotPa:-NQpvkV449z553iAotPb:b-lda7z8) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/mathematical_program.h#L1883)):*
> ```objc
>    @param hessian_type Whether the Hessian is positive semidefinite, negative
>    semidefinite or indefinite. Drake will check the type if
>    hessian_type=std::nullopt. For speed reason, please set hessian_type.
> ```

nit: I would change this to "Specifying the hessian type will speed this method up." Otherwise, it seems like `hessian_type` isn't really optional.



_Code quote:_
```objc
 For speed reason, please set hessian_type.
```
___
*[`solvers/mathematical_program.h` line 1897 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpxL-C09AyZ6AErOZl:-NQpxL-C09AyZ6AErOZm:b-l0jcwy) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/mathematical_program.h#L1897)):*
> ```objc
>    @param hessian_type Whether the Hessian is positive semidefinite, negative
>    semidefinite or indefinite. Drake will check the type if
>    hessian_type=std::nullopt. For speed reason, please set hessian_type.
> ```

nit: Ditto.
___
*[`solvers/test/create_constraint_test.cc` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpyUdWBNSl4ZLMhNjx:-NQpyUdWBNSl4ZLMhNjy:b1pdr5y) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/test/create_constraint_test.cc#L49)):*
> ```cpp
>   if (hessian_type.has_value()) {
>     EXPECT_EQ(binding.evaluator()->hessian_type(), hessian_type.value());
>   }
> ```

I think here, it would be good to be able to pass a `hessian_type` in the constructor and an `expected_hessian_type` to test against. That way you can do:
```  
if (hessian_type.has_value()) {
    EXPECT_EQ(binding.evaluator()->hessian_type(), hessian_type.value());
  }
EXPECT_EQ(binding.evaluator()->hessian_type(), expected_hessian_type);
```
___
*[`solvers/test/optimization_examples.h` line 981 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpzVLV2_784zTPDSCI:-NQpzVLV2_784zTPDSCJ:b-uh41o1) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/test/optimization_examples.h#L981)):*
> ```objc
> // max x + 2*y
> // s.t x² + y² = 1
> class QuadraticConstrainedProgram1 : public ::testing::Test {
> ```

nit: Can we change this to `QuadraticEqualityConstrainedProgram1`? When I see `QuadraticConstrainedProgram` I assume the quadratic constraint will be an inequality.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @AlexandreAmice)

___
*[`solvers/get_program_type.cc` line 206 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpwsaV43tzow8j8LAd:-NQq3JZO0fiT6tuyk4bO:b-4ojjxm) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/get_program_type.cc#L206)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

nit: I assume that the plan will be to make this `non-convex quadratic constraint1 in a few PRs, but for now you want to leave all quadratic constraints as NLP constraints as that is the current API. If this is the case I will mark myself as satisfied.
</blockquote></details>

That is right. For the moment we don't have a  `kQuadraticConstrainedConvexProgram` enum type. I just treat it as a generic nonlinear constraints.
___
*[`solvers/test/create_constraint_test.cc` line 49 at r2](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQpyUdWBNSl4ZLMhNjx:-NQq55fX2NnYhiPgeqDV:b-yh16l6) ([raw file](https://github.com/RobotLocomotion/drake/blob/ce853efd4753a5cf9e965e3e8ae898d5345acb0a/solvers/test/create_constraint_test.cc#L49)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think here, it would be good to be able to pass a `hessian_type` in the constructor and an `expected_hessian_type` to test against. That way you can do:
```  
if (hessian_type.has_value()) {
    EXPECT_EQ(binding.evaluator()->hessian_type(), hessian_type.value());
  }
EXPECT_EQ(binding.evaluator()->hessian_type(), expected_hessian_type);
```

</blockquote></details>

Done. Good call.

**Review by AlexandreAmice — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 16 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-:-NQv5KjW5xBuP3dQ8I0d:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-:-NQwxk0F8uPey_-p9j6S:bycyfct)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: WIth a couple of small things.

> Reviewed 9 of 16 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-:-NQzpYXn0HK9oNG8bRZ-:bhuqqxp)* status: 3 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 1883 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQzkKlsB_XeFMbGTGfL:-NQzkKlsB_XeFMbGTGfM:b-sswzib) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/mathematical_program.h#L1883)):*
> ```objc
>    @param hessian_type Whether the Hessian is positive semidefinite, negative
>    semidefinite or indefinite. Drake will check the type if
>    hessian_type=std::nullopt. Specifying the hessian type will speed this
> ```

nit: The constructor for `QuadraticConstraint` is more clear about the fact that the given classification of the hessian is blindly trusted (with possible downstream problems if it's incorrect). I think that kind of warning is required here. I.e., "You can make things faster, because we're *trusting* you. Don't screw it up." The language, as is, merely makes it seem like the *test* for classification becomes cheaper.

The simplest way to resolve this is add a `@pre` saying that the classification must be correct.
___
*[`solvers/test/mathematical_program_test.cc` line 2771 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQznO5J3oBXPQFAyYZJ:-NQznO5KB87wpoxEAP5R:b8bv15f) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/test/mathematical_program_test.cc#L2771)):*
> ```cpp
>                 ProgramAttribute::kQuadraticConstraint),
>             0);
>   EXPECT_EQ(prog.quadratic_constraints().size(), 1);
> ```

nit: When you have this kind of sequence (assume entry in vector and then access entry), it's kind of better to use `ASSERT_EQ` to make sure that the entry exists. Otherwise, the subsequent failures throw obnoxious errors instead of gtest messages.

And as all subsequent logic is wholly dependent on these indices being as expected, there's no downside to hardening these tests.
___
*[`solvers/test/mathematical_program_test.cc` line 2803 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQzo4Tg2q4D-od7zomL:-NQzo4Tg2q4D-od7zomM:b-pnsk9h) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/test/mathematical_program_test.cc#L2803)):*
> ```cpp
>   EXPECT_EQ(prog.required_capabilities().count(
>                 ProgramAttribute::kQuadraticConstraint),
>             0);
> ```

BTW Vague thought.

You've *kind of* documented these functions to accept lies about the hessian type, relying on problems during solving to reveal that. As I see it, the goal is for these `Add*Constraint` functions not to bark, even if the parameters are a lie. If that's an explicit goal, probably worth confirming that in test.

That said, if the documentation adds a `@pre` regarding things not being a lie, you are not obliged to test.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19016)* status: missing label for release notes (waiting on @hongkai-dai)

___
*[`solvers/mathematical_program.h` line 1883 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQzkKlsB_XeFMbGTGfL:-NQzvzYC9X5Szr65OEuc:b-2v0r33) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/mathematical_program.h#L1883)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: The constructor for `QuadraticConstraint` is more clear about the fact that the given classification of the hessian is blindly trusted (with possible downstream problems if it's incorrect). I think that kind of warning is required here. I.e., "You can make things faster, because we're *trusting* you. Don't screw it up." The language, as is, merely makes it seem like the *test* for classification becomes cheaper.

The simplest way to resolve this is add a `@pre` saying that the classification must be correct.
</blockquote></details>

Done. I added `@pre`.
___
*[`solvers/test/mathematical_program_test.cc` line 2771 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQznO5J3oBXPQFAyYZJ:-NQzwDwpAKOSpRdOPAIX:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/test/mathematical_program_test.cc#L2771)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: When you have this kind of sequence (assume entry in vector and then access entry), it's kind of better to use `ASSERT_EQ` to make sure that the entry exists. Otherwise, the subsequent failures throw obnoxious errors instead of gtest messages.

And as all subsequent logic is wholly dependent on these indices being as expected, there's no downside to hardening these tests.
</blockquote></details>

Done.
___
*[`solvers/test/mathematical_program_test.cc` line 2803 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/19016#-NQzo4Tg2q4D-od7zomL:-NQzwJVlAYJWRwUPhGq4:b-xm1onc) ([raw file](https://github.com/RobotLocomotion/drake/blob/3405286767b989f08b2d8912319ec26b5240f33c/solvers/test/mathematical_program_test.cc#L2803)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Vague thought.

You've *kind of* documented these functions to accept lies about the hessian type, relying on problems during solving to reveal that. As I see it, the goal is for these `Add*Constraint` functions not to bark, even if the parameters are a lie. If that's an explicit goal, probably worth confirming that in test.

That said, if the documentation adds a `@pre` regarding things not being a lie, you are not obliged to test.
</blockquote></details>

I added `@pre` in the documentation. I would prefer not to test it here, as using a wrong hessian_type is undefined behavior.

**Pull request merged**
