### PR TITLE
Adds RigidBodyPlantThatPublishesXdot and its unit test to BUILD.

### PR DESCRIPTION
**Pull request by liangfok**
Builds upon #4721.

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4907)

### CODE REVIEW

**Comment by liangfok** [comment]
Minor changes. +@sammy-tri for both levels of review please.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4907#-:-KbM84zsh5JAUrjvRLfm:b-s7x9g5)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/BUILD, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4907#-KbMCgeK5Zyorq23QKwt:-KbMCgeK5Zyorq23QKwu:bsnyoat) ([raw file](https://github.com/robotlocomotion/drake/blob/0325a6d306d0b4ec058eef5963ed07770159b4ea/drake/multibody/BUILD#L219)):*
> ```Python
>     name = "models",
>     srcs = [
>         "models/box.urdf",
> ```

BTW it seems weird that this one file isn't in a test subdirectory (yet it's only used by tests)...   but it predates this change, so, um...  I guess it can stay...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4907)*

**Comment by liangfok** [comment]
*[drake/multibody/BUILD, line 219 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4907#-KbMCgeK5Zyorq23QKwt:-KbML0BbrcqoSi-e94QJ:bimhre6) ([raw file](https://github.com/robotlocomotion/drake/blob/0325a6d306d0b4ec058eef5963ed07770159b4ea/drake/multibody/BUILD#L219)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW it seems weird that this one file isn't in a test subdirectory (yet it's only used by tests)...   but it predates this change, so, um...  I guess it can stay...
</blockquote></details>

Looks like `box.urdf` was originally added by @russtedrake in #4634. You have a good point though. I'll update this PR by moving `box.urdf`into drake/multibody/test/models/.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4907)*

**Comment by RussTedrake** [comment]
I actually think box.urdf should stay, though i'm happy to discuss.  At the time it was entered, the discussion was that this directory would serve as the landing point for models that are used across multiple tests and examples.  I think we do need a place for that.

**Comment by liangfok** [comment]
Oh, I forgot that this model may also be used by examples (not just tests) in the future. I thus agree to keep it as is.

**Comment by sammy-tri** [comment]
A README.md in multibody/models may help alleviate confusion in the future, though I don't think this PR needs to solve that issue.  :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4907#-:-KbQKtJm71ODyj15v2Uf:b-re37ut)*

**Pull request merged**
