### PR TITLE
Make SapContactProblem and friends clonable.

### PR DESCRIPTION
**Pull request by amcastro-tri**
This essentially gives SapContactProblem Value semantics so that we can place it in the cache along with other contact quantities in the manager.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@xuchenhan-tri for feature review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874#-:-Mz1gQChBjKCrbsymOzz:bzgdhpr)* status: LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — COMMENTED** [review]
Feature review done. PTAL, thanks.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874#-:-Mz2HOk-91GwvYfRg80i:b-l8luuj)* status: 9 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 95 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2H5Jb-XSee6EnJIDN:-Mz2H5Jb-XSee6EnJIDO:bajwc6l) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/contact_problem_graph.h#L95)):*
> ```objc
> 
>   /* Constructs an empty graph. */
>   ContactProblemGraph() = default;
> ```

BTW, it seems natural to me to call the one arg overload with `ContactProblemGraph(0)`. Default is ok too.
___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2AQvPA_GZ2FnYob6T:-Mz2AQvPA_GZ2FnYob6U:b4jbmrn) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/contact_problem_graph.h#L102)):*
> ```objc
> 
>   /* Resets this graph to store `num_cliques` and zero constraints. */
>   void ResetNumCliques(int num_cliques);
> ```

We need the same throw condition on `num_cliques` as in the 1-arg constructor.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Atk-0TDlhJXlzlmx:-Mz2Atk-0TDlhJXlzlmy:bropncc) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L49)):*
> ```objc
>  public:
>   /* Constructs an empty contact problem. */
>   SapContactProblem() = default;
> ```

This constructor seems to leave the object in an invalid state (time_step_ == 0.0)? Also, I don't see in this PR for the need of a default constructor. Could you explain?
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Aj4129vFfxDrTcYo:-Mz2Aj42CkTSBAdm6hGB:bdzw0x8) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
> ```objc
>                     VectorX<T> v_star);
> 
>   void SetDynamics(const T& time_step, std::vector<MatrixX<T>> A,
> ```

This function and the one below is missing documentation. In particular, it should be mentioned calling this function effectively removes all constraints registered in this contact problem.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2BmkJ8A8PDBbPm0Ty:-Mz2BmkK7mLFMhsVR5m9:b7qjsm5) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
> ```objc
>                     VectorX<T> v_star);
> 
>   void SetDynamics(const T& time_step, std::vector<MatrixX<T>> A,
> ```

We need the same throw condition as in the constructor.
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2DF-F6SC3i5xBUCnY:-Mz2DF-F6SC3i5xBUCnZ:bmydocp) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.cc#L22)):*
> ```cpp
>   A_ = std::move(A);
>   v_star_ = std::move(v_star);
>   graph_.ResetNumCliques(num_cliques());
> ```

It baffles me a little bit that the graph effectively clears all constraints, but `constraints_` isn't updated accordingly. Why is that?
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2E7Mp8SlwgW-kpv7g:-Mz2E7Mp8SlwgW-kpv7h:b5dnub9) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L113)):*
> ```cpp
> 
> TEST_F(ContactGraphTest, Construction) {
>   ContactProblemGraph graph = MakeGraph();
> ```

nit, looks like this line and the one below are unnecessary?
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 186 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2FSDx9NpdKKfhC6kq:-Mz2FSDx9NpdKKfhC6kr:b-izqg4v) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L186)):*
> ```cpp
> GTEST_TEST(ContactProblem, AddConstraints) {
>   const double time_step = 0.01;
>   const std::vector<MatrixXd> A{S22, S33, S44, S22};
> ```

BTW, you can move `A` and `v_start` into the problem.
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 210 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2FbvQEHpJjNgs9oms:-Mz2FbvQEHpJjNgs9omt:b-qrf9xs) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L210)):*
> ```cpp
>   EXPECT_EQ(problem.num_constraint_equations(), 0);
> 
>   // Tests we can set dynamics and add constraints on an already instanted
> ```

nit typo



_Suggestion:_
```cpp
instantiated
```
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 212 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2FxF54kCbTZ3UUY5n:-Mz2FxF54kCbTZ3UUY5o:b-izqg4v) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L212)):*
> ```cpp
>   // Tests we can set dynamics and add constraints on an already instanted
>   // problem.
>   const double time_step = 0.01;
> ```

BTW, you can move `A` and `v_start` into the problem.
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 215 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2G59B9haqNTZMo6Ya:-Mz2G59B9haqNTZMo6Yb:b-kca6nw) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L215)):*
> ```cpp
>   const std::vector<MatrixXd> A{S22, S33, S44, S22};
>   const VectorXd v_star = VectorXd::LinSpaced(11, 1.0, 11.0);
>   problem.SetDynamics(time_step, A, v_star);
> ```

I think it'd be helpful to have to a test where `SetDynamics` is called on a non-empty probelm.
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 337 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2GUv50brkUMzgtpVx:-Mz2GUv50brkUMzgtpVy:bdu1an5) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L337)):*
> ```cpp
>   SapFrictionConeConstraint<double> c(clique, J32, phi0, parameters);
>   auto clone =
>       dynamic_pointer_cast<SapFrictionConeConstraint<double>>(c.Clone());
> ```

Is this going to a typical use case of `Clone` for SapConstraints? If so, why not just let derived class return a pointer to derived cloned object?

**Review by xuchenhan-tri — COMMENTED** [review]
BTW it seems like CI is complaining about a few SapConstraints for testing purpose don't have `Clone()` implemented.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874#-:-Mz2JZot5sTONUc8V_kJ:b-nq2fdl)* status: 9 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: 7 unresolved discussions, LGTM missing from assignee xuchenhan-tri(platform), needs at least two assigned reviewers (waiting on @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/contact_problem_graph.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2AQvPA_GZ2FnYob6T:-MzHcV-t5jY9-_v2s0Fg:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/contact_problem_graph.h#L102)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We need the same throw condition on `num_cliques` as in the 1-arg constructor.
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Atk-0TDlhJXlzlmx:-MzHdN9T4oBYtwWvmaDz:b-nrzcfp) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This constructor seems to leave the object in an invalid state (time_step_ == 0.0)? Also, I don't see in this PR for the need of a default constructor. Could you explain?
</blockquote></details>

It is invalid until someone does `SetDynamics()`. I added doc.
For my user case, I will place a `SapContactProblem` in a cache entry as a way to avoid copying Jacobian matrices around (that is, SapContactProblem becomes my storage for the Jacobian blocks). Therefore I need this class to have value semantics. Since I do not know the structure of the problem in advance, the only thing I can tell the allocator is to create a cheap (default) empty object. Then the calc method will make sure we size the problem accordingly.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Aj4129vFfxDrTcYo:-MzHf-Be9XmA-Yq-x3x8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This function and the one below is missing documentation. In particular, it should be mentioned calling this function effectively removes all constraints registered in this contact problem.
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2BmkJ8A8PDBbPm0Ty:-MzHfCZ_3pgluBiapRhH:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We need the same throw condition as in the constructor.
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/sap_contact_problem.cc, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2DF-F6SC3i5xBUCnY:-MzHfOho7wg7AbHMvl4X:b-c4j5eu) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.cc#L22)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It baffles me a little bit that the graph effectively clears all constraints, but `constraints_` isn't updated accordingly. Why is that?
</blockquote></details>

no reason, I simply forgot.
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 215 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2G59B9haqNTZMo6Ya:-MzHhDjIEOQq_8JIxk6V:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L215)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think it'd be helpful to have to a test where `SetDynamics` is called on a non-empty probelm.
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 337 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2GUv50brkUMzgtpVx:-MzHh_kz3-aA38uIrW0D:bce1b2f) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L337)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Is this going to a typical use case of `Clone` for SapConstraints? If so, why not just let derived class return a pointer to derived cloned object?
</blockquote></details>

no, it's not the typical use of Clone(). I need Clone() to allow "copies" using polymorphism, that is, to allow the model to call Clone on the base class and still get a deep copy to the orignal constraints.

While covariant returns are allowed in C++, covariant return of unique_ptr to a derived class is not :-(. In this case however I don't need it so I won't try to come up with a solution to a problem I don't have.

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: after CI fix.
+@sherm1 for platform review per rotation please.

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874#-:-MzHr8Sw0U_146HXjbRw:brqe6he)* status: 2 unresolved discussions, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri and @sherm1)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Atk-0TDlhJXlzlmx:-MzHnRH555KLdRhcWZHY:b-bl51vt) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It is invalid until someone does `SetDynamics()`. I added doc.
For my user case, I will place a `SapContactProblem` in a cache entry as a way to avoid copying Jacobian matrices around (that is, SapContactProblem becomes my storage for the Jacobian blocks). Therefore I need this class to have value semantics. Since I do not know the structure of the problem in advance, the only thing I can tell the allocator is to create a cheap (default) empty object. Then the calc method will make sure we size the problem accordingly.
</blockquote></details>

The doc should probably say that the constructed SapContactProblem is invalid until `SetDynamics()` is called.
Another thought, do you know dt when allocating the contact problem?
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2BmkJ8A8PDBbPm0Ty:-MzHmt8m8ReME6hoTrMo:bdqio9) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The documentation of the throw condition should carry over as well.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Aj4129vFfxDrTcYo:-MzHnuXk6ph_Po0iD7WS:b-purqgd) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, would you consider working the phrase "remove/reset constraints" in to the name of the function?
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2E7Mp8SlwgW-kpv7g:-MzHpXK44BGUyiJirhHB:b2gdj44) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L113)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, looks like this line and the one below are unnecessary?
</blockquote></details>

This is upsetting CI.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Atk-0TDlhJXlzlmx:-MzKndoRBtKRsY77NaBy:bxgcd29) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L49)):*
Done.

> do you know dt when allocating the contact problem?

Actually it is known. I like this. I got rid of the default ctor and added instead one that takes dt.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2Aj4129vFfxDrTcYo:-MzKpgK_DMkBVaD5BxzY:b-r67uuc) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, would you consider working the phrase "remove/reset constraints" in to the name of the function?
</blockquote></details>

I like the idea. Renamed to `Reset()`. 
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 84 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2BmkJ8A8PDBbPm0Ty:-MzKpttZ3cEBzVH13fxd:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/sap_contact_problem.h#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The documentation of the throw condition should carry over as well.
</blockquote></details>

Done.
___
*[multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, line 113 at r1](https://reviewable.io/reviews/robotlocomotion/drake/16874#-Mz2E7Mp8SlwgW-kpv7g:-MzKqN4P1UA2EKeE8Han:b-334idr) ([raw file](https://github.com/robotlocomotion/drake/blob/93667be7164b7fa6105cc3052a72e6514baa54ba/multibody/contact_solvers/sap/test/contact_problem_graph_test.cc#L113)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is upsetting CI.
</blockquote></details>

Thanks for looking into it. Fixed.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: LGTM missing from assignee sherm1(platform) (waiting on @sherm1)

**Review by xuchenhan-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @amcastro-tri, @sherm1, and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/sap_constraint.h, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzLU1gvAJdvgba2saEj:-MzQlX3h4QPvA7HVV7NI:by8thjo) ([raw file](https://github.com/robotlocomotion/drake/blob/586132d6bf84d2dc47fc40c358ce30e4c05518b2/multibody/contact_solvers/sap/sap_constraint.h#L61)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Good catch. I actually do not need these in the base class, not even protected. Removed.
</blockquote></details>

I think in this case you'd want to explicitly prevent public copy semantics by moving the macro to protected. Otherwise the compiler will generate the default one for you.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: 1 unresolved discussion, LGTM missing from assignee sherm1(platform) (waiting on @sherm1 and @xuchenhan-tri)

___
*[multibody/contact_solvers/sap/sap_constraint.h, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzLU1gvAJdvgba2saEj:-MzRaxv-99mHSycMtJx_:b-1nyush) ([raw file](https://github.com/robotlocomotion/drake/blob/586132d6bf84d2dc47fc40c358ce30e4c05518b2/multibody/contact_solvers/sap/sap_constraint.h#L61)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think in this case you'd want to explicitly prevent public copy semantics by moving the macro to protected. Otherwise the compiler will generate the default one for you.
</blockquote></details>

nvm. CLang needs it to generate the copy/move ctors for the derived classes. I am not sure why gcc does not bark though, it should?

**Review by sherm1 — COMMENTED** [review]
Platform :lgtm: pending some minor stuff.

> Reviewed 3 of 12 files at r1, 2 of 8 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874#-:-MzRdJxv3jywsvBmPXW5:b-dt41lw)* status: 4 unresolved discussions (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_constraint.h, line 61 at r3](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzLU1gvAJdvgba2saEj:-MzR9HGu2QHTisSWbjjd:bub6lb9) ([raw file](https://github.com/robotlocomotion/drake/blob/586132d6bf84d2dc47fc40c358ce30e4c05518b2/multibody/contact_solvers/sap/sap_constraint.h#L61)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think in this case you'd want to explicitly prevent public copy semantics by moving the macro to protected. Otherwise the compiler will generate the default one for you.
</blockquote></details>

Definitely! As written now these are still all public.
___
*[multibody/contact_solvers/sap/sap_contact_problem.h, line 97 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzR91Ue3UfC73mWpgsc:-MzR91Ue3UfC73mWpgsd:bbz22lt) ([raw file](https://github.com/robotlocomotion/drake/blob/0db2d1d446e6f1d1bcda5b876786456fb7b8cd79/multibody/contact_solvers/sap/sap_contact_problem.h#L97)):*
> ```objc
>    removes any existing constraints. The problem will have a new number of
>    cliques and generalized velocities according to the sizes of `A` and `v_star`
>    and no constraints.
> ```

BTW consider mentioning that the time step is preserved by Reset().
___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 67 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzR9QVq-3DEt0melkcg:-MzR9QVq-3DEt0melkch:b-8cwxef) ([raw file](https://github.com/robotlocomotion/drake/blob/0db2d1d446e6f1d1bcda5b876786456fb7b8cd79/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L67)):*
> ```objc
> class SapFrictionConeConstraint final : public SapConstraint<T> {
>  public:
>   DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(SapFrictionConeConstraint);
> ```

BTW the methods generated here are working because the base class has default implementations of the same methods. Those base class methods are needed but should be protected.
___
*[multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, line 230 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzRBm4a4Vm2JBixCA2X:-MzRBm4a4Vm2JBixCA2Y:b-qbjcsr) ([raw file](https://github.com/robotlocomotion/drake/blob/0db2d1d446e6f1d1bcda5b876786456fb7b8cd79/multibody/contact_solvers/sap/test/sap_contact_problem_test.cc#L230)):*
> ```cpp
>   EXPECT_EQ(problem.num_velocities(), 5);
>   EXPECT_EQ(problem.num_constraints(), 0);
>   EXPECT_EQ(problem.num_constraint_equations(), 0);
> ```

minor: should verify that the time step remains unchanged after Reset()
___
*[multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, line 337 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzRC4vTDnSiQ8H19wl1:-MzRC4vTDnSiQ8H19wl2:bsv567l) ([raw file](https://github.com/robotlocomotion/drake/blob/0db2d1d446e6f1d1bcda5b876786456fb7b8cd79/multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc#L337)):*
> ```cpp
>   SapFrictionConeConstraint<double> c(clique, J32, phi0, parameters);
>   // N.B. Here we dynamic cast to the derived type so that we can test the clone
>   // a deep-copy of the original constraint.
> ```

nit: the clone a -> that the clone is

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

___
*[multibody/contact_solvers/sap/sap_friction_cone_constraint.h, line 67 at r4](https://reviewable.io/reviews/robotlocomotion/drake/16874#-MzR9QVq-3DEt0melkcg:-MzRhZWU2DQ-wQqhSYeU:b-ejdu92) ([raw file](https://github.com/robotlocomotion/drake/blob/0db2d1d446e6f1d1bcda5b876786456fb7b8cd79/multibody/contact_solvers/sap/sap_friction_cone_constraint.h#L67)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the methods generated here are working because the base class has default implementations of the same methods. Those base class methods are needed but should be protected.
</blockquote></details>

thanks, I see the problem now. Done.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Review by sherm1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16874)* status: :shipit: complete! all discussions resolved, LGTM from assignees sherm1(platform),xuchenhan-tri(platform) (waiting on @amcastro-tri)

**Pull request merged**
