### PR TITLE
Update statistics bugfix

### PR DESCRIPTION
**Pull request by edrumwri**
This PR addresses issue #4336, where UpdateStatistics() could be called with the wrong step size for variable step integrators.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4347)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@sherm1 for feature review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KY0UqB4g55isj59wWM5:b1tu4a9)*

**Comment by edrumwri** [comment]
+@ggould-tri for platform review please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KY0by2vr7oTiaGz23g-:bffmgsm)*

**Comment by sherm1** [comment]
Feature review: :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KY0bz-SuoC2mY4R3OXe:bqdzdqx)*

**Comment by ggould-tri** [comment]
I am surprised to see no unit test changes in this PR; it suggests that there is no test coverage of the return value of `DoStepOnceAtMost` or for the resulting statistics.  Because this is a protected method and a purely informational output, and because the situation is clearly pre-existing, I'm not going to flag that as a defect, but consider expanding test coverage there in the future.

(I assume you have at least manually verified a reproduction scenario for #4336)

:lgtm: pending trivial whitespace issue noted below.

I am flagging +(status: curate commits before merging) because not all of the commits in this history appear to build.  In practice this just means you should squash-merge this when you land it rather than preserve the branch commit history.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 822 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-KYEPTNSUNqvtaLiUHgu:-KYEPTNTHDyvj5u6LIbe:b-vcc1as) ([raw file](https://github.com/robotlocomotion/drake/blob/313c7d841f69875ceba64b36b0278213dd372308/drake/systems/analysis/integrator_base.h#L822)):*
> ```objc
>    *          `false` if the integrator does not take the full step of @p max_dt
>    *           (and `true` otherwise) and the second element corresponding to
>    *           the step size actually taken by the integrator. 
> ```

FYI -- trailing whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KYEPs9bZS9H5Z7vOn0u:b-g9qkc8)*

**Comment by edrumwri** [comment]
You're right, Gerald, and I'll go ahead and add a test for it now. No reason to put it off until later!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KYEYIFTd2l12Mw8RuMq:b2opyz2)*

**Comment by sherm1** [comment]
Gerald?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-:-KYEjlewQ7TkU6DdbLAT:b-989r57)*

**Comment by edrumwri** [comment]
Good thing I haven't started writing code yet!

**Comment by liangfok** [comment]
http://www.urbandictionary.com/define.php?term=Gerald ?

**Comment by edrumwri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/systems/analysis/integrator_base.h, line 822 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4347#-KYEPTNSUNqvtaLiUHgu:-KYFOBzzg4BE5bb5Ci2O:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/313c7d841f69875ceba64b36b0278213dd372308/drake/systems/analysis/integrator_base.h#L822)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

FYI -- trailing whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347)*

**Comment by edrumwri** [comment]
FYI, preparing to squash commits.

**Comment by ggould-tri** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4347)*

**Pull request merged**
