### PR TITLE
convert pendulum example visualization from RBT to SceneGraph

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9363)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Unfortunately, one consequence of this PR is that `bazel test //systems/framework/...` now has to crawl through and compile scene graph (which uses the framework) because a few framework unit tests were depending on the pendulum plant example as a toy system.  Thus, when iterating locally on small framework changes, builds tend to be both slow and also present compiler errors in frustrating orderings.

I am not sure exactly the right way to resolve this.  I could fork the pendulum plant into a framework benchmark (removing is visualization support), or I could re-split the example plant to have visualization as a separate system (that the user would cascade in their diagram), or ...?

Any thoughts @RussTedrake @sherm1 @amcastro-tri?

**Comment by amcastro-tri** [comment]
The `PendulumPlant` only needs SG info (namely source_id_ and frame_id_) in `AllocateGeometryPoseOutputPort()` and `CopyPoseOut()`. So I was thinking that we could probably pass those at construction and just have an external method to do the geometry registration. 
However, just to include `geometry_ids.h` right now we need to depend on the entire `geometry` module. Would it be worth splitting the module into `geometry_ids` and `geometry_core` (with the rest)?
Otherwise, the other option would be having a bare bones `PendulumPlant` and either a Diagram that composes it with SG or even a `PendulumPlantWithGeometry` that inherits form `PendulumPlant`?

**Comment by SeanCurtis-TRI** [comment]
There is a `//geometry:geometry_ids` target. YOu don't have to grab all of `geometry`.

**Comment by jwnimmer-tri** [comment]
I think the idea of the current approach was one-stop-shopping where viz JustWorks(TM).  If we are going to make the user deal with adding viz separately, we might as well just encapsulate it into an entirely new System that you can just cascade.  That would be less boilerplate that trying to ask the user to shuffle IDs around.

**Pull request merged**
