### PR TITLE
Clean up URDF parsing of unused custom tags and uses in Drake-owned URDF files

### LINKED ISSUE #15781: atlas example prints ignoring collision group warnings
Mentioned in:
https://stackoverflow.com/questions/69199764/atlas-example-warning-in-drake-toolkit

Given @SeanCurtis-TRI 's answer "In an URDF you can specify the "group" attribute in the <link> tag. Drake doesn't make use of this attribute and is letting you know it's not being used," I think we need to update the urdf/sdf files in that example.

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Historically, Drake had introduced a number of custom tags and attributes in URDF files. Some/many of these have long since been mothballed in practice. However, they remained in numerous URDF files owned/tracked in the repo and the parsing of those custom elements would lead to (not overly helpful) spew into the console.

This makes two changes:

  - The Drake-owned URDF files simply don't include those legacy tags/attributes anymore.
  - The warnings no longer spew on a per-instance basis. Now they do a log once.

Closes #15781.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
+@sherm1 for feature review

Design note: the previous messages (which generated log bloat) were more specific, while the new ones don't mention any particular element that could be easily searched for in the URDF. You could avoid the bloat without entirely giving up on specifics, by issuing one specific message like
> Link `left_arm` and possibly others specifies `<youngs_modulus>` under the `<drake_compliance>` tag. 
> Drake no longer makes use of  that tag and all instances will be ignored.

However :lgtm: pending a few minor fixes.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-MjjDWIZ-K82kiRPPcYv:bm2wjzs)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjC1QcCE0wQr2CHB-b:-MjjC1QcCE0wQr2CHB-c:b-ipikns) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_geometry.cc#L581)):*
> ```cpp
>     if (node->FirstChildElement("drake_compliance")) {
>       static const logging::Warn log_once(
>           "At least one of your URDF files has specified the the collision "
> ```

nit: the the
___
*[multibody/parsing/detail_urdf_geometry.cc, line 586 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjCC3K36zBpIuqFf3x:-MjjCC3K36zBpIuqFf3y:b-wewki0) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_geometry.cc#L586)):*
> ```cpp
>           "that case and is generally dispreferred. Consider removing all "
>           "instances of <drake_compliance> in favor of "
>           "<drake:proximity_properties>.");
> ```

BTW this message seems very helpful. I'm wondering if the other messages should also suggest some action for the offender?
___
*[multibody/parsing/detail_urdf_parser.cc, line 493 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjCqAr3_5B55uVChN7:-MjjCqAr3_5B55uVChN8:bz5s0jw) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_parser.cc#L493)):*
minor: I think this message is wrong now. The test is looking for transmission types OTHER THAN SimpleTransmission, since only SimpleTransmission is supported. Should say something like
> At least one ... specifies `<transmission>` type other than SimpleTransmission. Only SimpleTransmissions are supported currently.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@sherm1 the comment about loss of *any* specific information is an excellent point. A similar thought occurred to me. The primary reason I didn't do it is that it's has the potential of only being *partly* helpful. I.e., each invocation would have to whittle away at the individual sites. I feel the language would have to be a bit more verbose so there's no implication that the list is complete in any sense. Also, in this context, we lack file name and line number information, which vastly undercuts the value of the message details.

I'd appreciate your further thoughts on this, but I think I'll defer adding details in until I've considered it more.

Also, I've updated the PR to include changes to Drake-owned URDF files. All of the legacy Drake custom XML stuff have been removed from our files (so, at least, our files won't be triggering these warnings. :))

+(status: commits are properly curated) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-Mjjr5sI83-khzJ42PUP:b-j5m1j6)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[multibody/parsing/detail_urdf_geometry.cc, line 581 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjC1QcCE0wQr2CHB-b:-Mjjrpre3ewP695zlr6N:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_geometry.cc#L581)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: the the
</blockquote></details>

Done
___
*[multibody/parsing/detail_urdf_geometry.cc, line 586 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjCC3K36zBpIuqFf3x:-MjjrqfP1SVr7rAspHKq:b-eh7dvp) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_geometry.cc#L586)):*
I know what you mean. This message has more of a "old is deprecated, please use new" flavor. The other messages are more about, "Meh. We're just ignoring that." 

I'm going to follow up in the future with a separate PR that gives a stronger "deprecation" style warning. Something along the lines of:

> You're making use of a legacy Drake-specific [thing] that is no longer supported. Please [take an appropriate action]. On or after [some date] that [thing] will be silently ignored.
___
*[multibody/parsing/detail_urdf_parser.cc, line 493 at r1](https://reviewable.io/reviews/robotlocomotion/drake/15783#-MjjCqAr3_5B55uVChN7:-MjnrCgr4ooeZoG9FvU_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/31b8f5bcca15bd4f99856b71173e55497006adf8/multibody/parsing/detail_urdf_parser.cc#L493)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: I think this message is wrong now. The test is looking for transmission types OTHER THAN SimpleTransmission, since only SimpleTransmission is supported. Should say something like
> At least one ... specifies `<transmission>` type other than SimpleTransmission. Only SimpleTransmissions are supported currently.
</blockquote></details>

Done

**Review by sherm1 — COMMENTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-Mk7iw5G757wD209RlPs:b-syrr9x)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: typo; deadwood.

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-Mk82Acy9pNA64xgSOPm:b-ymgm0r)* status: 3 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15783#-Mk7xrDRCWIEoYLB9Q5S):*
> ```
> relplaced
> ```
typo
___
*[examples/atlas/urdf/block_hand.urdf, line 18 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15783#-Mk8-Y3YBv9kCG_wICgS:-Mk8-Y3Z8coeDprJvy_3:btaobqp) ([raw file](https://github.com/robotlocomotion/drake/blob/1a94955b24e7723827d704d7539b3d29706d4908/examples/atlas/urdf/block_hand.urdf#L18)):*
> ```XML
>       <origin rpy="0 0 0" xyz="0 0 0"/>
>     </visual>
>     <collision group="block_hand">
> ```

I can't find any evidence that this file is used any more. Delete? Add a test? Add a comment justifying its existence?
___
*[examples/pendulum/test/PendulumWithFriction.urdf, line 63 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15783#-Mk81IhGBdo5xmfUpQ9B:-Mk81IhGBdo5xmfUpQ9C:b2k2ttt) ([raw file](https://github.com/robotlocomotion/drake/blob/1a94955b24e7723827d704d7539b3d29706d4908/examples/pendulum/test/PendulumWithFriction.urdf#L63)):*
> ```XML
>     <child link="arm"/>
>     <axis xyz="0 1 0"/>
>     <dynamics damping="0.5" friction="20" coulomb_window="0.1"/>
> ```

ditto above -- I can't find any evidence of use of this file.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783)* status: 3 unresolved discussions (waiting on @rpoyner-tri)

___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake/15783#-Mk7xrDRCWIEoYLB9Q5S):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Addressed in merge.
</blockquote></details>

Well, I *will* resolve it once you've cleared the blocking comments. Or, if you end up merging it, you could tweak the commit message at merge time.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Blast....I'd forgotten this was a pre-curated, 2-commit PR. So, to fix the commit typo, I have to re-run CI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-Mk8EoT1EopABCRWzVUk:bauadsq)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform) (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
Looking at the prior revision, I _think_ that our Reviewable config would have prevented you from merging anyway -- the base commit was not the head of master.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Yep. Now it's properly blocking.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15783#-:-Mk8XUVi0g3-cArZ9lo6:b-u9n80s)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sherm1(platform), base commit is latest master (waiting on @SeanCurtis-TRI)

**Pull request merged**
