### PR TITLE
Joint damping

### PR DESCRIPTION
**Pull request by amcastro-tri**
Introduced viscous damping for the modeling of losses within a joint.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046)

### CODE REVIEW

**Comment by amcastro-tri** [comment]
+@hongkai-dai for feature review please.
+@sherm1 for platform review please.

---

Review status: all discussions resolved, platform LGTM missing, commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFd-guB-g4y5q1FeEMa:bb92koi)*

**Comment by hongkai-dai** [comment]
:lgtm: with a few minor comments.

---

Reviewed 15 of 15 files at r1.
Review status: 5 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/joints/prismatic_joint.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd2VBe47PBQlLEkCV9:-LFd2VBf84wTDMTwSnjR:b-zhabkv) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/prismatic_joint.h#L60)):*
> ```objc
>   ///   joint. The damping force (in N) is modeled as `f = -damping⋅v`, i.e.
>   ///   opposing motion, with v the translational speed for `this` joint (see
>   ///   get_translation_rate()).
> ```

I am not sure if dynamics uses this convention, but if the input parameter has a default value, you can add `@default damping = 0` in the documentation, and doxygen will render it.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd6fzJDoIQWToMu6PJ:-LFd6fzJDoIQWToMu6PK:b-1qrkw4) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L288)):*
> ```cpp
>     Vector2d tau_g_expected =
>         acrobot_benchmark_.CalcGravityVector(theta1, theta2);
>     Vector2d tau_damping(
> ```

If `tau_damping` is not changed later, we should declare it as `const Vector2d`.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 920 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd6zpr2V_EbpzmDgIy:-LFd6zpr2V_EbpzmDgIz:buyrfds) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L920)):*
> ```cpp
>   A << 0.0, 1.0,
>        parameters.g() / parameters.l(),
>       -parameters.damping() / parameters.m() / parameters.l() / parameters.l();
> ```

Is it OK if I ask you to write it as `-parameters.damping() / (parameters.m() * parameters.l() * parameters.l())`? With the parenthesis on the denominator, the equation is more clear.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 935 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd7EWdAv4LHh2YURZe:-LFd7EWdAv4LHh2YURZf:bs4q9op) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L935)):*
> ```cpp
>   A << 0.0, 1.0,
>       -parameters.g() / parameters.l(),
>       -parameters.damping() / parameters.m() / parameters.l() / parameters.l();
> ```

Ditto.

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd7Qzm7o-AweB70ATa:-LFd7Qzm7o-AweB70ATb:b-j3eq87) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L156)):*
> ```cpp
>         "An axis must be specified for joint '" + joint_spec.Name() + "'");
>   }
>   double damping = axis->Damping();
> ```

`double` -> `const double`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFd8Jf45GT02rXrvOUf:bavmcyl)*

**Comment by sherm1** [comment]
Platform pass done. Looks great with a few minor things plus a design question. I'm not getting why the damping element has to be treated separately in the API from the other force elements, and what the implications are for adding more built-in forces in the future, please see my comment below.

There appears to be a CI problem.

---

Reviewed 15 of 15 files at r1.
Review status: 11 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/joints/joint.h, line 160 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdBdrD1RjW_zsbLIK6:-LFdBdrD1RjW_zsbLIK7:b4trwo0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L160)):*
> ```objc
>       const systems::Context<T>& context,
>       int joint_dof,
>       const T &joint_tau,
> ```

Nit: misplaced &

---

*[multibody/multibody_tree/joints/joint.h, line 175 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdBmtOEE_pKO5t-h6w:-LFdBmtOEE_pKO5t-h6x:b-p10kl3) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L175)):*
> ```objc
>   /// @param[out] forces
>   ///   On return, this method will add the force due to damping within `this`
>   ///   joint. This method aborts if `forces` is `nullptr` or if `forces` doest
> ```

Nit: doest -> does

---

*[multibody/multibody_tree/joints/joint.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdCEmWBH3XqRrhRF0Z:-LFdCEmWBH3XqRrhRF0_:b-fstuzw) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L180)):*
> ```objc
>   // NVI to DoAddInOneForce().
>   void AddInDamping(
>       const systems::Context<T> &context, MultibodyForces<T>* forces) const {
> ```

I don't understand why this is needed as a public API. It doesn't have an argument for the actual damping value so I presume that's calculated by some kind of force element that is already built in to the joint. But then why does there have to be an API for this -- wouldn't that have to be added in along with the forces from other force elements?  Couldn't you apply damping automatically at the time you process the other forces?

Also, does this mean there will be an ever-growing number of these APIs as we add additional types of built-in force elements? I don't get why that would be a good thing. Please consider whether any built-in force element can simply be applied as part of general force element processing.

My thought would be to make this and similar methods just private helpers that you make use of internally when collecting up all the forces.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdERlQ0Z3mULYIZBxw:-LFdERlQ0Z3mULYIZBxx:bn1m8fj) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L798)):*
> ```cpp
>     const Joint<T>& joint = model().get_joint(joint_index);
>     joint.AddInDamping(context0, &forces0);
>   }
> ```

The above looks like a big chunk of repeated code from DoCalcTimeDerivatives(). If it really is the same, please factor it out into an "ApplyForces()" method or whatever and use it in both places.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdGHiXDIekFx0qP6U0:-LFdGHiXDIekFx0qP6U1:b-hybsrq) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L294)):*
> ```cpp
>     MultibodyForces<double> forces(plant_->model());
>     shoulder_->AddInDamping(*context_, &forces);
>     elbow_->AddInDamping(*context_, &forces);
> ```

This is testing the public AddInDamping() API but I don't understand why that isn't just a private helper method. Do users need to call this? Will there be many more of these methods as additional force types are added? Why?

---

*[multibody/multibody_tree/parsing/test/negative_damping_joint.sdf, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdBHTaClCDCKvJDeHX:-LFdBHTaClCDCKvJDeHY:btu6bwq) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/parsing/test/negative_damping_joint.sdf#L5)):*
> ```
>     
> ```

Minor: this seems to be a copy pasta artifact.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFdHnN58sqaMv5jkmiM:b-f04qb0)*

**Comment by amcastro-tri** [comment]
Review status: 8 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/joints/joint.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdCEmWBH3XqRrhRF0Z:-LFdJvOK4TMJY_bQ2-Mh:bb3dtel) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L180)):*
> I don't understand why this is needed as a public API.

So that `MultibodyPlant`  can use it. I don't see any harm on this being public. 

> wouldn't that have to be added in along with the forces from other force elements? Couldn't you apply damping automatically at the time you process the other forces?

This is such a simple force that I decided to make it joint specific. A force element would be another solution but it'd require a bigger PR. I don't think it's worth it.

> Also, does this mean there will be an ever-growing number of these APIs as we add additional types of built-in force elements?

not at all. If I add a `DragForceElement`, why would that cause any changes to the joints?

> My thought would be to make this and similar methods just private helpers

I guess I could try some sort of friendship or attorney but I really think it is not worth the effort for really, not gain at all.

---

*[multibody/multibody_tree/joints/prismatic_joint.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd2VBe47PBQlLEkCV9:-LFdHLvk4pGCsuNKJxUv:b-1xcb4i) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/prismatic_joint.h#L60)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure if dynamics uses this convention, but if the input parameter has a default value, you can add `@default damping = 0` in the documentation, and doxygen will render it.
</blockquote></details>

I actually don't like `@default` because you need to essentially keep it in sync with the actual default value. `double damping = 0` appears nicely in the generated Doxygen that I think is good enough? and there is nothing to keep in sync.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdERlQ0Z3mULYIZBxw:-LFdLVmd-GtsqmxdKTR8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L798)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The above looks like a big chunk of repeated code from DoCalcTimeDerivatives(). If it really is the same, please factor it out into an "ApplyForces()" method or whatever and use it in both places.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 288 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd6fzJDoIQWToMu6PJ:-LFdHqGt5q5bbw9arKps:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L288)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

If `tau_damping` is not changed later, we should declare it as `const Vector2d`.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdGHiXDIekFx0qP6U0:-LFdLgvM7Mt6gyMi7HQ6:bgcjtbl) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L294)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

This is testing the public AddInDamping() API but I don't understand why that isn't just a private helper method. Do users need to call this? Will there be many more of these methods as additional force types are added? Why?
</blockquote></details>

so that MBP can call it. See more detailed answer above.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 920 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd6zpr2V_EbpzmDgIy:-LFdIVW9EIT621dChGtw:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L920)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Is it OK if I ask you to write it as `-parameters.damping() / (parameters.m() * parameters.l() * parameters.l())`? With the parenthesis on the denominator, the equation is more clear.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 935 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd7EWdAv4LHh2YURZe:-LFdIWMb6XvGabnZWUee:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L935)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

---

*[multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc, line 156 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd7Qzm7o-AweB70ATa:-LFdIcNN1qLvZHHvj4_I:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc#L156)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`double` -> `const double`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046)*

**Comment by hongkai-dai** [comment]
Reviewed 4 of 6 files at r2.
Review status: 3 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/joints/prismatic_joint.h, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFd2VBe47PBQlLEkCV9:-LFdNMVv3bEYxI9_tWne:b-dxcbts) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/prismatic_joint.h#L60)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I actually don't like `@default` because you need to essentially keep it in sync with the actual default value. `double damping = 0` appears nicely in the generated Doxygen that I think is good enough? and there is nothing to keep in sync.
</blockquote></details>

Makes sense.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046)*

**Comment by sherm1** [comment]
I'm still not understanding the design. Attempted to clarify my question, but maybe best to discuss f2f?

---

Reviewed 6 of 6 files at r2.
Review status: 4 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing, commit history needs curation

---

*[multibody/multibody_tree/joints/joint.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdCEmWBH3XqRrhRF0Z:-LFdNpoaAu7zvin2Agze:b-6yp0tf) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L180)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> I don't understand why this is needed as a public API.

So that `MultibodyPlant`  can use it. I don't see any harm on this being public. 

> wouldn't that have to be added in along with the forces from other force elements? Couldn't you apply damping automatically at the time you process the other forces?

This is such a simple force that I decided to make it joint specific. A force element would be another solution but it'd require a bigger PR. I don't think it's worth it.

> Also, does this mean there will be an ever-growing number of these APIs as we add additional types of built-in force elements?

not at all. If I add a `DragForceElement`, why would that cause any changes to the joints?

> My thought would be to make this and similar methods just private helpers

I guess I could try some sort of friendship or attorney but I really think it is not worth the effort for really, not gain at all.
</blockquote></details>

I'm not sure I have conveyed my point adequately. There are a variety of forces built in to the multibody tree, including general force elements and specialized ones like damping, actuators, gravity(?), and likely more in the future (we've already talked about building in joint feedback controllers e.g.). Will MBPlant be required to track each of those additions separately? Why can't it just ask the tree to apply built-in forces? In MBPlant I already noticed two apparently-duplicate implementations of a bunch of code that works its way through all the built in force stuff -- not clear why that couldn't just be a single call that hides the individual components.

I don't think you would need to expose this API and other similar ones if you had a single "ApplyForces()" method somewhere, right? What is the reason for requiring MBPlant to have to assemble the collection of forces itself -- seems brittle?

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdQ_YF4Ucovn9_KMEt:-LFdQ_YF4Ucovn9_KMEu:b-78f02i) ([raw file](https://github.com/robotlocomotion/drake/blob/061f68feca72808c0f6271180b4386f65b15be91/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1129)):*
> ```objc
>   // Helper method to apply forces due to damping at the joints.
>   void AddJointDampingForces(
>       const systems::Context<T>& context, MultibodyForces<T>* forces) const;
> ```

Not clear to me why this wouldn't be in MBTree -- isn't that where the joint dampers reside? (And not clear why these should be separated out from other forces.)

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdERlQ0Z3mULYIZBxw:-LFdPnWwDAlayFZmc4rN:biagcu0) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L798)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't mean just the damping loop -- it looks to me that the actuators, force elements, and damping (and as-yet-to-be-invented future additions) are all duplicated.

Please consider collecting those up into a single method provided by MBTree that MBPlant can call, and then hide the individual APIs.

---

*[multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc, line 294 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdGHiXDIekFx0qP6U0:-LFdQKp73zZzcymARtdx:b-upj58l) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc#L294)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

so that MBP can call it. See more detailed answer above.
</blockquote></details>

See my comments above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFdR2i-DlPfR4hMbUGE:bimkqmy)*

**Comment by sherm1** [comment]
Met f2f and resolved everything. Just needs:
- a comment explaining why it is useful for MBPlant to understand damping separate from other forces
- combine the duplicated force application stuff in one place so it can be called from derivatives and discrete update.

Then, platform :lgtm:.

---

Review status: 3 unresolved discussions, platform LGTM from [sherm1], commit history needs curation

---

*[multibody/multibody_tree/joints/joint.h, line 180 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdCEmWBH3XqRrhRF0Z:-LFdj3rUAa6nY9AgsCsE:b1w08la) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/joints/joint.h#L180)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm not sure I have conveyed my point adequately. There are a variety of forces built in to the multibody tree, including general force elements and specialized ones like damping, actuators, gravity(?), and likely more in the future (we've already talked about building in joint feedback controllers e.g.). Will MBPlant be required to track each of those additions separately? Why can't it just ask the tree to apply built-in forces? In MBPlant I already noticed two apparently-duplicate implementations of a bunch of code that works its way through all the built in force stuff -- not clear why that couldn't just be a single call that hides the individual components.

I don't think you would need to expose this API and other similar ones if you had a single "ApplyForces()" method somewhere, right? What is the reason for requiring MBPlant to have to assemble the collection of forces itself -- seems brittle?
</blockquote></details>

Per f2f: this is so that the discrete solver in MBPlant can handle damping specially if needed. 

Please add a comment explaining that here. Unblocking.

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.h, line 1129 at r2](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdQ_YF4Ucovn9_KMEt:-LFdjLCR3-FIiwd7BGSy:b-tx0wal) ([raw file](https://github.com/robotlocomotion/drake/blob/061f68feca72808c0f6271180b4386f65b15be91/multibody/multibody_tree/multibody_plant/multibody_plant.h#L1129)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Not clear to me why this wouldn't be in MBTree -- isn't that where the joint dampers reside? (And not clear why these should be separated out from other forces.)
</blockquote></details>

Per f2f: could replace with a method here that applies _all_ the built-in forces?

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdERlQ0Z3mULYIZBxw:-LFdjYAC0fp7rsF9Ki-T:bw7d18b) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L798)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I didn't mean just the damping loop -- it looks to me that the actuators, force elements, and damping (and as-yet-to-be-invented future additions) are all duplicated.

Please consider collecting those up into a single method provided by MBTree that MBPlant can call, and then hide the individual APIs.
</blockquote></details>

Per f2f: please collect up the force element/actuator/damping etc stuff into a single method you can call from both places. That way if more special forces get added later they only have to be added in one place.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFdjvgG9wIqN3nAUkPq:b4vc8jb)*

**Comment by sherm1** [comment]
Also, there is a CI failure.

---

Review status: 3 unresolved discussions, platform LGTM from [sherm1], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046#-:-LFdkJwE-ABG25e2PG9i:b-90wy0r)*

**Comment by amcastro-tri** [comment]
Review status: 1 unresolved discussion, platform LGTM from [sherm1], commit history needs curation

---

*[multibody/multibody_tree/multibody_plant/multibody_plant.cc, line 798 at r1](https://reviewable.io/reviews/robotlocomotion/drake/9046#-LFdERlQ0Z3mULYIZBxw:-LFr9uBsCYJhMHdS38eh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/0e6377d3ac5b87f3ab01b508948afcb39fa271d3/multibody/multibody_tree/multibody_plant/multibody_plant.cc#L798)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Per f2f: please collect up the force element/actuator/damping etc stuff into a single method you can call from both places. That way if more special forces get added later they only have to be added in one place.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046)*

**Comment by sherm1** [comment]
Reviewed 5 of 6 files at r3.
Review status: all discussions resolved, platform LGTM from [sherm1], commit history needs curation

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9046)*

**Pull request merged**
