### PR TITLE
[vtk] Add vtkProbeOpenGLVersion binary rule for debugging

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #21700.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri or @SeanCurtis-TRI whichever if you gets to this first, please sign up for the review.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer (waiting on @jwnimmer-tri)

___
*[`geometry/BUILD.bazel` line 756 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21963#-O7oLICE3Qhjujdp3z3y:-O7oLICE3Qhjujdp3z3z:b6eogq5) ([raw file](https://github.com/RobotLocomotion/drake/blob/b018e5d4ad20f62b5d383681184a0b3434ede056/geometry/BUILD.bazel#L756)):*
> ```Starlark
> 
> drake_cc_library(
>     name = "vtk_opengl_init",
> ```

BTW It would not be totally insane to move this file and its `drake_cc_library` to live under `tools/workspace_vtk_internal`, as in `@drake//tools/workspace/vtk_internal:vtk_opengl_init` (not `@vtk_internal//:vtk_opengl_init`).  If we like that better, I can adjust here.

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for review.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963#-:-O7oLwtJDgQEyP1bBTEM:b2no51w)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri(platform)

___
*[`geometry/BUILD.bazel` line 756 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21963#-O7oLICE3Qhjujdp3z3y:-O7oLo-72oSI9RYlAQoH:b-pq8xnz) ([raw file](https://github.com/RobotLocomotion/drake/blob/b018e5d4ad20f62b5d383681184a0b3434ede056/geometry/BUILD.bazel#L756)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW It would not be totally insane to move this file and its `drake_cc_library` to live under `tools/workspace_vtk_internal`, as in `@drake//tools/workspace/vtk_internal:vtk_opengl_init` (not `@vtk_internal//:vtk_opengl_init`).  If we like that better, I can adjust here.
</blockquote></details>

+1 for moving this bit into the vtk stuff. Please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: pending untwisting of dependencies.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963#-:-O7oM5Bh0i3m2ec7sCRK:b-1qyds)* status: 1 unresolved discussion

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21963)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform)

**Pull request merged**
