### PR TITLE
Windows workaround for bot_lcm_datatypes failures.

### LINKED ISSUE #1830: bot_core_lcm is failing to build on windows/appveyor

### PR DESCRIPTION
**Pull request by jhoare**
Fixes #1830 

Temporary solution to fix constant build failures on windows.

### CODE REVIEW

**Comment by mauricefallon** [comment]
Feel free to make a PR to bot_core_lcmtypes with your change @jhoare .
The java code isn't important and I assume the pkgconfig command is system independent?

Would be best not to use your personal fork.

**Comment by jhoare** [comment]
Sure, this mainly was to see that it actually fixed the build error for appveyor/Jenkins before submitting a pull request to your repo. We also weren't sure if this is something that you would want in the openhumanoids repo. If you're okay with it though once we verify that it passes CI tests we can get it merged into the OpenHumanoids repo and I can update this pull request.

**Comment by RussTedrake** [comment]
looks like appveyor is happy.  and the jenkins failure is still the bullet issue.  would like to proceed with this and get back up and running.

**Comment by jhoare** [comment]
openhumanoids/bot_core_lcmtypes#2

**Comment by RussTedrake** [comment]
Thank you!!

On Tue, Mar 8, 2016 at 8:03 PM, John Hoare <notifications@github.com> wrote:
openhumanoids/bot_core_lcmtypes#2
[https://github.com/openhumanoids/bot_core_lcmtypes/pull/2]

—
Reply to this email directly or view it on GitHub
[https://github.com/RobotLocomotion/drake/pull/1833#issuecomment-194050606] .[https://github.com/notifications/beacon/AGJNNK1S-uL_2FD6s0uzDYwmM4d9uaQFks5prhxogaJpZM4HsOdh.gif]

**Comment by RussTedrake** [comment]
as discussed in the open-humanoids PR, we will merge this now and follow up with a proper fix.

**Pull request merged**
