### PR TITLE
Add missing header install

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3163)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please

**Comment by jwnimmer-tri** [comment]
Well, jenkins is constipated with too many merges-to-master and broken executors, so we'll just have to wait to see if the missed header was the only problem.

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-clang-experimental-ros please srsly

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by jwnimmer-tri** [comment]
The ROS build passed.  Any platform reviewer who like can review and merge this, otherwise I'll assign someone tomorrow.

**Comment by jwnimmer-tri** [comment]
/CC @liangfok if you want to review, I'll call them good enough before merging.

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3163#-:-KPL58mijw5glBTynZL-:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Using override-merge:
- The jenkins error was a flake with "port already in use", perhaps related to #3167.
- Reviewable is missing platform LGTM, but I'll assert this is fine.

**Pull request merged**
