### PR TITLE
Remove PetscSymmetricBlockSparseMatrix

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
-(status: do not review) +(priority: low) 
+@amcastro-tri for feature review on FEM namespace changes.
+@jwnimmer-tri for review on the workspace change. Without the added dependency, a linker error manifested after the PETSc purge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135#-:-NdgauyC30J3mti3jB9n:b939q09)* status: LGTM missing from assignees amcastro-tri,jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
LGTM on build system.

> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135#-:-NdgoEAF4vkum0lcpVvs:bq2cj03)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),amcastro-tri

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake/20135#-NdgcPy2DnzJs62t3Qcg:-NdgcPy4D_jWLdsXlgXK:b-d2rirg) (no related file):*
nit Assuming that we no longer use PETSc at all (and it looks like that's true now), then the install rule at `drake/tools/workspace/BUILD.bazel:103` needs to be unhooked.  Delete that line, as well as the lines in `drake/tools/workspace/petsc/package.BUILD.bazel` that mention the word "install" (the two stanzas for `load(...)` and `install(...)`).  The premise is that we don't need to ship license texts for things that we don't ship in `libdrake.so` anymore, and so then the install rules for it are dead code.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),amcastro-tri

**Comment by jwnimmer-tri** [comment]
I would love for us to land this before the next release.  @amcastro-tri are you planning to review it today?

**Review by amcastro-tri — COMMENTED** [review]
:lgtm: on the fem namespace changes.

> Reviewed 13 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135#-:-Ne8VEZLCgUsrUFkBYKd:b4ui5nn)* status: LGTM missing from assignee jwnimmer-tri(platform)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform, also.

> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20135#-:-Ne8sRf2-0vidmG_ROFU:baw360h)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),amcastro-tri

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot retest this please

**Comment by xuchenhan-tri** [comment]
Pimpling `DeformableDriver` should do.

**Comment by jwnimmer-tri** [comment]
I was wondering if maybe `std::unique_ptr<DeformableDriver<double>> deformable_driver_;` in `compliant_contact_manager.h` was enough already -- by forward declaring the `DeformableDriver<double>` in the CCM header.

**Comment by xuchenhan-tri** [comment]
The `fem` namespace also leaks into `DeformableModel` via `multibody::fem::DeformableBodyConfig` (which really should have been multibody::DeformableBodyConfig`) and `multibody::fem::FemModel`. The latter is trickier to eliminate but I guess we could leave FemModel in the interface dependency?

**Comment by jwnimmer-tri** [comment]
Okay, I haven't looked closely enough to get a sense of the landscape.  The overall objective is that the only header files included by `multibody_plant.h` are those required to speak with its public API.  Anything that's Calc-only dynamics evaluation should be implementation deps, ideally.

**Pull request merged**
