### PR TITLE
workspace: Add suitesparse for osqp and scs

### LINKED ISSUE #11697: OSQP and SCS export extra symbols
As mentioned in #11682, both OSQP and SCS have symbols for (at least) `SuiteSparse_malloc` (and related functions).  Per @jamiesnape "If they are vendoring libraries, they should be mangling names. That is the bug regardless of build system. The odds are probably we would need to make that fix."

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #11697.  Relates #11883.

Requires:
- [x] #12072 _setup: Add suitesparse as a new dependency_

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/12071)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-debug please
@drake-jenkins-bot linux-bionic-unprovisioned-clang-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-xenial-unprovisioned-clang-bazel-experimental-debug please

**Comment by jwnimmer-tri** [comment]
- https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-bionic-unprovisioned-clang-bazel-experimental-release/35/
- https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-bionic-unprovisioned-gcc-bazel-experimental-debug/7/
- https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-xenial-unprovisioned-clang-bazel-experimental-debug/7/
- https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-xenial-unprovisioned-gcc-bazel-experimental-release/20/

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-unprovisioned-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
+@jamiesnape and +@sammy-tri for review, please.

Once this PR has rough approval, we can move ahead with #12072 to update the images.

**Comment by jamiesnape** [comment]
@drake-jenkins-bot retest this please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot In mac-mojave-clang-bazel-experimental-release please

**Comment by jamiesnape** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-mojave-clang-bazel-experimental-everything-release please
 @drake-jenkins-bot mac-high-sierra-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-cxx17-release please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-cxx17-debug please

@drake-jenkins-bot linux-bionic-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-clang-bazel-experimental-snopt-fortran-release please
@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-snopt-fortran-release please

@drake-jenkins-bot linux-xenial-gcc-bazel-experimental-everything-debug please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-address-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-leak-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-thread-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-undefined-behavior-sanitizer please
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-valgrind-memcheck please

**Pull request merged**
