### PR TITLE
build: Wcpp warnings to errors

### LINKED ISSUE #14151: #warning that have not been squelched bypass CI
For example https://github.com/RobotLocomotion/drake/pull/14135 introduced a `#warning` for deprecation purposes, but that warning shows up when building Drake from source, not just downstream when used in external projects:
```
[7:05:21 AM]  INFO: From Compiling systems/analysis/simulator_flags.cc:
[7:05:21 AM]  In file included from systems/analysis/simulator_flags.cc:1:
[7:05:21 AM]  bazel-out/k8-opt/bin/systems/analysis/_virtual_includes/simulator_flags/drake/systems/analysis/simulator_flags.h:3:2: warning: "This file has been merged into simulator_config_functions.h. This file and build target will be removed from Drake on or after 2021-01-01."  // NOLINT(whitespace/line_length) [-W#warnings]
[7:05:21 AM]  #warning "This file has been merged into simulator_config_functions.h. This file and build target will be removed from Drake on or after 2021-01-01."  // NOLINT(whitespace/line_length)
[7:05:21 AM]   ^
[7:05:21 AM]  1 warning generated.
```
https://github.com/RobotLocomotion/drake/pull/14149 fixes the issue for this particular `#warning`, but CI/bazel should (presumably) catch these warnings and prevent them from being merged to master.

### PR DESCRIPTION
**Pull request by dmcconachie-tri**
Closes #14151.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14155)

### CODE REVIEW

**Review by dmcconachie-tri — COMMENTED** [review]
+@jamiesnape for feature review  please (I think)
-(status: do not review) 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14155#-:-MI_rtD8DsAS_XYPIG9D:b3p6mzu)* status: LGTM missing from assignee jamiesnape, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-catalina-clang-bazel-experimental-release please

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform review.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14155#-:-MIbZFUyEPP9JD_Cy3IO:b-a5n9m0)* status: LGTM missing from assignee jamiesnape (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14155#-:-MIedXm-8TMBq2uunGcH:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),jamiesnape

**Pull request merged**
