### PR TITLE
Tidy up ConvexSet implementation conventions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #19311.

+@SeanCurtis-TRI for platform review per schedule, please.  No feature review required; this is just cleaning up prior platform reviewer leaks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19313)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
A couple of missing implementations and some doc clarity requests.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-:-NUMipX2EkF3DuixiGUP:b-l38uf)* status: 3 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`geometry/optimization/hpolyhedron.cc` line 410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMgkLa-pWk4fxXCqWN:-NUMgkLa-pWk4fxXCqWO:bm39z7c) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff288a10e1b6aa262229c5cf61138e72572fdb03/geometry/optimization/hpolyhedron.cc#L410)):*
> ```cpp
> HPolyhedron HPolyhedron::DoIntersectionWithChecks(const HPolyhedron& other,
>                                                   double tol) const {
>   DRAKE_DEMAND(other.A().cols() == A_.cols());
> ```

BTW When I first saw this I was flummoxed by the removal of what seemed a necessary condition. After I dug a bit, I recognized that `Intersection` tested against the two sets `ambient_dimension()` values (which proves to be equivalent).

We might want to simply add that as a documented `@pre` in the header for this function to spare future readers the spelunking endeavor. `DoIntersectionNoCheck` should probably get the same treatment for symmetry's sake.
___
*[`geometry/optimization/point.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMhocs3E7csC580ecg:-NUMhocs3E7csC580ech:baiyk2l) ([raw file](https://github.com/RobotLocomotion/drake/blob/97183f7485e4658cfcf6291fc4dfe72c865f4366/geometry/optimization/point.h#L23)):*
> ```objc
> 
>   /** Constructs a default (zero-dimensional) set. */
>   Point();
> ```

nit: Declaration without definition. Probably need to add it to the unit test as well.
___
*[`geometry/optimization/vpolytope.h` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMiZhU3DruixV3Nhi0:-NUMiZhU3DruixV3Nhi1:baiyk2l) ([raw file](https://github.com/RobotLocomotion/drake/blob/97183f7485e4658cfcf6291fc4dfe72c865f4366/geometry/optimization/vpolytope.h#L30)):*
> ```objc
> 
>   /** Constructs a default (zero-dimensional) set. */
>   VPolytope();
> ```

nit: Declaration without definition. Probably need to add it to the unit test as well.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19313)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[`geometry/optimization/hpolyhedron.cc` line 410 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMgkLa-pWk4fxXCqWN:-NUMjpUe3h2Lss2vudeI:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake/blob/ff288a10e1b6aa262229c5cf61138e72572fdb03/geometry/optimization/hpolyhedron.cc#L410)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW When I first saw this I was flummoxed by the removal of what seemed a necessary condition. After I dug a bit, I recognized that `Intersection` tested against the two sets `ambient_dimension()` values (which proves to be equivalent).

We might want to simply add that as a documented `@pre` in the header for this function to spare future readers the spelunking endeavor. `DoIntersectionNoCheck` should probably get the same treatment for symmetry's sake.
</blockquote></details>

Done.
___
*[`geometry/optimization/point.h` line 23 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMhocs3E7csC580ecg:-NUMjt-MB2PaFb-Vz-L9:b-yquhc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/97183f7485e4658cfcf6291fc4dfe72c865f4366/geometry/optimization/point.h#L23)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Declaration without definition. Probably need to add it to the unit test as well.
</blockquote></details>

Rebase mistake from future PR.  Removed.
___
*[`geometry/optimization/vpolytope.h` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-NUMiZhU3DruixV3Nhi0:-NUMjxCaDDYCdIkoOceL:b-yquhc6) ([raw file](https://github.com/RobotLocomotion/drake/blob/97183f7485e4658cfcf6291fc4dfe72c865f4366/geometry/optimization/vpolytope.h#L30)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Declaration without definition. Probably need to add it to the unit test as well.
</blockquote></details>

Rebase mistake from future PR.  Removed.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19313)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: X2

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/19313#-:-NUMmeOc0GKqudk8EL1v:bxqo58p)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI(platform)

**Pull request merged**
