### PR TITLE
Rename ProjectMatTo{Rot => Orthonormal}Mat for O(3) projection, add ProjectMatToRotMat with SO(3) projection

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This renames the O(3) projection to `ProjectMatToOrthonormalMat`, and adds an SO(3) projection, `ProjectMatToRotMat`.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6752)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@hongkai-dai for feature review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-:-KqZJnR7HgtZP5B_fFHm:b-81zjv5)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/test/rotation_matrix_test.cc, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLPbjS1_xnFCq4PQB:-KqZLPbkeAzjW81rET6z:b-fbbt8d) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/math/test/rotation_matrix_test.cc#L82)):*
> ```cpp
>   EXPECT_NEAR(std::abs(R2.determinant()), 1.0, tol);
>   // Check that we get SO(3) with Moakher's formulation.
>   Matrix3d R2_SO3 = ProjectMatToRotMat(M2);
> ```

Can we add a test case with some `M`, such that when we call `ProjectMatToOrthonormalMat`, we get a matrix with det = -1, but when we call `ProjectMatToRotMat`, we get a matrix with det = 1?

---

*[drake/multibody/global_inverse_kinematics.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZL1tSDDaALTiWXDSW:-KqZL1tSDDaALTiWXDSX:bd6iau9) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/multibody/global_inverse_kinematics.cc#L182)):*
> ```cpp
>       // p_WBi is the position of the body frame in the world frame.
>       Vector3d p_WBi = GetSolution(p_WBo_[body_idx]);
>       Matrix3d normalized_rotmat = math::ProjectMatToOrthonormalMat(R_WC);
> ```

We actually want ProjectMatToRotMat here.

---

*[drake/perception/estimators/dev/scratch.m, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLA_t2Z73pi_6zf7c:-KqZLA_t2Z73pi_6zf7d:b9ir9g4) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/perception/estimators/dev/scratch.m#L1)):*
> ```objc
> M = reshape(1:9, [3, 3])';
> ```

Should we delete this file? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/math/test/rotation_matrix_test.cc, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLPbjS1_xnFCq4PQB:-KqZR_plJ-2LHRNH1lOU:b-jlpxfy) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/math/test/rotation_matrix_test.cc#L82)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Can we add a test case with some `M`, such that when we call `ProjectMatToOrthonormalMat`, we get a matrix with det = -1, but when we call `ProjectMatToRotMat`, we get a matrix with det = 1?
</blockquote></details>

Done. (Luckily that is already the case.)
Did not thoroughly check that `det(M) < 0` is the "degenerate" SO(3) case for `ProjectMatToOrthonormalMat`. Would you like me to dig into that further?

Changing the matrix to have `det(M) > 0` does make the O(3) and SO(3) projections match:
https://github.com/EricCousineau-TRI/repro/commit/dd8a163d2d51a3319ad23f6a66abde5994bc5923#diff-e71174c8d7084db05bfb6a464167656fR9

---

*[drake/multibody/global_inverse_kinematics.cc, line 182 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZL1tSDDaALTiWXDSW:-KqZS-XcJfcjhJgi7PVm:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/multibody/global_inverse_kinematics.cc#L182)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We actually want ProjectMatToRotMat here.
</blockquote></details>

Done.

---

*[drake/perception/estimators/dev/scratch.m, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLA_t2Z73pi_6zf7c:-KqZOdssrQNeXktc-xhl:b-1tsezw) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/perception/estimators/dev/scratch.m#L1)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should we delete this file? 
</blockquote></details>

Done. Whoops!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/test/rotation_matrix_test.cc, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLPbjS1_xnFCq4PQB:-KqZVdlbJ9yrB9JeqiQF:b-wh6t6i) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/math/test/rotation_matrix_test.cc#L82)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done. (Luckily that is already the case.)
Did not thoroughly check that `det(M) < 0` is the "degenerate" SO(3) case for `ProjectMatToOrthonormalMat`. Would you like me to dig into that further?

Changing the matrix to have `det(M) > 0` does make the O(3) and SO(3) projections match:
https://github.com/EricCousineau-TRI/repro/commit/dd8a163d2d51a3319ad23f6a66abde5994bc5923#diff-e71174c8d7084db05bfb6a464167656fR9
</blockquote></details>

I think I am suggesting to check that `R2.determinant()` is -1, instead of checking `abs(R2.determinant())`. I do not think we need to dig into if `det(M) <0` is the degenerate case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/test/rotation_matrix_test.cc, line 82 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqZLPbjS1_xnFCq4PQB:-KqZWEVzYHpDx4c3anxa:b7e3z4y) ([raw file](https://github.com/robotlocomotion/drake/blob/3348d90b792c491a2ceb6a4c785d0647121cd617/drake/math/test/rotation_matrix_test.cc#L82)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think I am suggesting to check that `R2.determinant()` is -1, instead of checking `abs(R2.determinant())`. I do not think we need to dig into if `det(M) <0` is the degenerate case.
</blockquote></details>

Sorry, had pushed that, but Reviewable focused on the wrong set of revisions. Updated revision range.
And sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752)*

**Comment by hongkai-dai** [comment]
:lgtm: +@seancurtis-tri for platform review please.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-:-KqZXvTynYbLHvLn5Mt6:b-o1mdov)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: +@ggould-tri for final review.

---

Reviewed 1 of 4 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-:-Kq_4ZDIxj5jdXrshqAx:b-t6caff)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/math/rotation_matrix.h, line 272 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-KqcR5eKlfeQ2Ks11GNj:-KqcR5eLJgQFmbodN53g:b23y4h8) ([raw file](https://github.com/robotlocomotion/drake/blob/13754b5bb47b864fae786b808cbec8a2e0c6a802/drake/math/rotation_matrix.h#L272)):*
> ```objc
>   using Scalar = typename Derived::Scalar;
>   const Scalar det = M.determinant();
>   DRAKE_THROW_UNLESS(fabs(det) > std::numeric_limits<Scalar>::epsilon());
> ```

BTW Switched this to throw, as that is more appropriate in the case of numeric conditioning (IMO).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752)*

**Comment by SeanCurtis-TRI** [comment]
-@ggould-tri +@soonho-tri for final review.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-:-KqcRULjYpMpMS_ZxEHE:bpsafh2)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6752#-:-KqcW3mMSgkarH0cRDbK:bnfp4nl)*

**Pull request merged**
