### PR TITLE
In pydrake, turn Drake assertion failures into SystemExit

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A new module `pydrake.common` exposes some fundamental C++ items from `//drake/common:common`, for now only assertion-related.

At `pydrake.__init__` time, we always set the toggle to turn assertion failures into exceptions; this seems like always the right thing to do for Python users.

This changes `DRAKE_THROW_UNLESS` to use an exception subtype, though does not promise this in the API.

Note that `DRAKE_ABORT` behavior is unchanged, and will still result in a full process exit (`abort`); only assertions change.

Relates #5268.  Subsumes #6167.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/6175)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-xenial-gcc-ninja-experimental-open-source-debug please

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.
+@ggould-tri for platform review, please.

**Comment by RussTedrake** [comment]
+@rdeits

**Comment by ggould-tri** [comment]
I argued myself back and forth about four times on whether the `testDrakeDemandThrows` catch-block should `raise`.  In the end I think I will leave it to your wisdom.

Anyway, :lgtm:.  This is excellent.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-:-Kkzk9EaNTbR1s-DgRWB:bh3ijhd)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: Looks awesome!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_common.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-Kl-3uMlVMJ0UdqmKSUG:-Kl-3uMmRmWla2oUuGuW:b4ubpgc) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b823ae9389d4bb10fa6804a0c3d6fd306bf0b4/drake/bindings/pybind11/pydrake_common.cc#L17)):*
> ```cpp
>   DRAKE_DEMAND(false);
> }
> }  // namespace
> ```

BTW I've seen `// anonymous namespace` as well, but I see that the GSG mentions just `// namespace`. Should I put in a super-low priority clean up action to make those consistent?

---

*[drake/common/drake_assert_and_throw.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-Kl-3Hta9gDAdf-9B27h:-Kl-3HtbpboClWc8szd4:b-32jz1p) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b823ae9389d4bb10fa6804a0c3d6fd306bf0b4/drake/common/drake_assert_and_throw.cc#L22)):*
> ```cpp
> 
> // Singleton to manage assertion configuration.
> struct AssertionConfig {
> ```

BTW As a singleton, does it matter to expose trivial construction to the public? Or should it be private / protected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-:-Kl-4q67X6zE3cMhzUp3:b-pzgpt3)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/bindings/pybind11/pydrake_common.cc, line 17 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-Kl-3uMlVMJ0UdqmKSUG:-Kl-5t3oQ_NKNkaHKQ4W:b-shfue2) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b823ae9389d4bb10fa6804a0c3d6fd306bf0b4/drake/bindings/pybind11/pydrake_common.cc#L17)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW I've seen `// anonymous namespace` as well, but I see that the GSG mentions just `// namespace`. Should I put in a super-low priority clean up action to make those consistent?
</blockquote></details>

IMO neither way is defective, and I don't really care about the inconsistency.  (If we want it consistent, we should write a tool to do it and/or enforce it, e.g., amend `cpplint.py` to change its special case for this.)

---

*[drake/common/drake_assert_and_throw.cc, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-Kl-3Hta9gDAdf-9B27h:-Kl-65l9rrMmGW4QHnA3:b4c081s) ([raw file](https://github.com/robotlocomotion/drake/blob/f8b823ae9389d4bb10fa6804a0c3d6fd306bf0b4/drake/common/drake_assert_and_throw.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW As a singleton, does it matter to expose trivial construction to the public? Or should it be private / protected?
</blockquote></details>

I'd originally written it that way (also disabling copy, etc.), but it seemed like a lot of noise for no real benefit.  Since its declared in an anonymous namespace within the cc file, we'd only be protecting it from ourselves within these hundred lines, which seemed to me like a low risk and sufficiently covered by the unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6175)*

**Comment by rdeits** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/6175#-:-Kl0_A1vUbpU3MH7NUNr:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Thanks!

**Pull request merged**
