### PR TITLE
[tools] Allow macOS 12 Monterey

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #16001.  Follow-up from #16055.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16068)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot mac-monterey-clang-bazel-experimental-release please

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail my best guess from this output is that XCode might not be installed properly in the provisioned image (or else, bazel upstream somehow doesn't recognize it correctly yet).

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for both reviews, please.  There is a little bit of a game here of what our codebase allows for vs what our CI checks for.  My proposal here is to remove the code interlocks that forbid macOS 12, even without working CI yet.  Our website still says that 12 is not yet supported, so I think this is a fair compromise.  Once CI is working, we can update the website.  WDYT?

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16068#-:-MoAlPg42gpcP2Q1WlWx:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
