### PR TITLE
SnoptSolver uses C snopt_interface instead of f2c interface.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/9177)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental-everything please

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review per schedule, please.

**Comment by sherm1** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/9177#-LIHCtqfEFyFw1rIzjUu:-LIRMnVp8RJM96ZLc223:bokwwvb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

We can't merge this until TRI CI is ready for it.  (I'll close out this discussion thread once we are.)
</blockquote></details>

TRI CI is green -- does that mean you can close this thread, @jwnimmer-tri ?

---

**Comment by jamiesnape** [comment]
> I tested on TRI CI, and disturbs two test cases. Hongkai is looking into it.

What is the defect on Drake CI that means it is not authoritative (any more)? Having parallel (hidden) CI holding up PRs is not a good situation to be in at all.

**Comment by jwnimmer-tri** [comment]
@hongkai-dai re-ping to add the test that shows the problem (we could / should PR it to master separately, prior to this PR).

**Pull request closed without merging**
