### PR TITLE
[draft][geometry] Add subsystem test for mesh_intersection.

### PR DESCRIPTION
**Pull request by DamrongGuoy**
In anticipation to the upcoming improvement by SIMD AVX for RigidTransform compositions and also the new geometric query for discrete hydroelastics, I set up this PR for a simple subsystem test of mesh_intersection.  Instead of checking the detailed triangulation, it will check the numerical integration of quantities in the output without going into the multibody territory. It is not a unit test, but I believe it's good to have.

Before starting the formal review process, I would like to hear from the team because the concept of subsystem test (I will change the term "regression test" in the code to "subsystem test" later) might not mean the same thing for everybody.

If this PR does not get merged, at least, we have a sharable and convenient way to test SIMD and discrete-hydroelastics query during this development cycle.  After finishing the development, we might delete it.

This is related to #14768 and its coming PR trains. @sherm1 I set up this PR per your request.  I'll wait for general comments for a few days.  If it turns out ok, I'll start the review process.  For now, this is a draft PR.  (The prequel to this PR is #14917, which is basically this subsystem test plus #14768 to test CI on multiple platforms.)

Please do not review in details yet.  Instead, please voice your opinion about merging this PR into master (and perhaps keeps it for a certain period.)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15009)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
By the way, I heard of the term [subsystem test](https://wiki.c2.com/?SubsystemTest) from @rpoyner-tri . 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15009#-:-MZubGEG3fiUiAFmiG_V:b-31v72a)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by sherm1 — COMMENTED** [review]
I'm not sure of the meaning of "subsystem test". I did see that in a recent @rpoyner-tri PR. There it seemed to be a generic term for a localized Drake System test where it doesn't matter if the system under test is standalone or part of a diagram.

For the test here I think "regression test" is the correct term -- there aren't any Drake Systems involved and the purpose (as I understand it) is to ensure that certain critical invariants are preserved in contact patches produced by all future versions of Drake.

BTW my first impression is that this is a valuable test even though the basics are already covered by unit tests. Here we have a test that is known to generate different meshes due to trivial numerical differences among platforms so clearly defines the invariants that actually matter for all such contact patches (e.g. total area).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15009#-:-MZxEl7WEJPZVZvgIzh0:bhct84i)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by sherm1** [comment]
@rpoyner-tri can you clarify what you mean by "subsystem test" and when we should use that term?

**Comment by jwnimmer-tri** [comment]
For my part, I usually find the c2 definitions relatively authoritative.

https://wiki.c2.com/?SubsystemTest in this case.

**Comment by SeanCurtis-TRI** [comment]
In that context, "Integration test" has always come to my mind.

https://wiki.c2.com/?IntegrationTest

**Review by rpoyner-tri — COMMENTED** [review]
As always, a perfectly good term dies 1k deaths because of overloading. In ordinary software testing, "subsystem test" just means a test that covers several units working together. Larger in scope than a unit test (and probably less detailed), smaller in scope than a system test. None of this has the least relation to Drake Systems, Subsystems, etc.

As for "regression test", I typically reserve that for crafted tests that detect the re-emergence of some previously found bugs. And this is somewhat different from  (antique and probably useless) "regression testing", which really just re-running all of your tests to see if they fail. In modern times, we call that CI.

Do we care about subtle semantic differences between, say, subsystem test, integration test, functional test? The questions care about are: 
* What property of the software does this test?
* Does it provide coverage different from other tests?
* Does the coverage it provides compensate for the costs of execution and maintenance?

Also, +1 for wiki.c2.com -- excellent, if crufty, resource.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15009#-:-MZxMWzZ2iv1cfmyClTp:bgvnr7j)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Review by sherm1 — COMMENTED** [review]
Great, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15009#-:-MZxW-Gf4NMHIlnigPcO:b-6mhyx0)* status: needs platform reviewer assigned, needs at least two assigned reviewers, labeled "do not merge"

**Comment by jwnimmer-tri** [comment]
This PR is starting to get a bit long in the tooth -- two months idle.  Is it time to either start working to finalize it, or abandon and close for now?

**Comment by DamrongGuoy** [comment]
Close for now.

**Pull request closed without merging**
