### PR TITLE
Signed distance query

### PR DESCRIPTION
**Pull request by hongkai-dai**
Add a signed distance query to SceneGraph.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8896)

### CODE REVIEW

**Comment by hongkai-dai** [comment]
+@seancurtis-tri for feature review please.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8896#-:-LDhojdi106nSX9FtVKs:b-4269ug)*

**Comment by jwnimmer-tri** [comment]
Aside: remember to test on macOS at some point prior to merge.  See https://github.com/RobotLocomotion/drake/pull/9085#issuecomment-401914181 for a good 'bot syntax.

**Comment by hongkai-dai** [comment]
@drake-jenkins-bot mac-sierra-clang-bazel-experimental-everything please
@drake-jenkins-bot mac-highsierra-clang-bazel-experimental please

**Comment by sherm1** [comment]
SGTM

**Pull request merged**
