### PR TITLE
Update CLion+Bazel instructions to use released plugin

### PR DESCRIPTION
**Pull request by david-german-tri**
Google released the Bazel plugin in the JetBrains repo, so we no longer have to build from source or pin to an old version of CLion.  I've confirmed that it works for me on Linux and OS X.  Kudos, @brendandouglas!  https://github.com/bazelbuild/intellij/issues/26#issuecomment-286172920

@sherm1 for feature review, since you said this was "all you've been waiting for".  Let me know how it goes!

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5509)

### CODE REVIEW

**Comment by sherm1** [comment]
Thanks, David!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfJ8YD6-XU5IHg1TKo8:blo2whb)*

**Comment by sherm1** [comment]
So far so good. Clion 2016.3.4 is building the Bazel project. I got a few warnings:
> ____Loading package: drake/doc
WARNING: /home/sherm/Documents/GitHub/sherm1/drake-distro2/drake/util/BUILD:43:1: target '//drake/util:app_util' is deprecated: Please use gflags instead of drakeAppUtil.h..
____Loading complete.  Analyzing...
____Loading package: tools/defaults
____Loading package: @bazel_tools//tools/zip
____Loading package: @protobuf//
____Loading package: @bazel_tools//tools/coverage
____Loading package: @drake_visualizer//
WARNING: /home/sherm/.cache/bazel/_bazel_sherm/d3684f5810c05a72e264480177f4abb1/external/drake_visualizer/BUILD:2:48: soft_failure.bzl: @drake_visualizer//:drake-visualizer does not work because /home/sherm/Documents/GitHub/sherm1/drake-distro2/build/install/bin/drake-visualizer was missing.

Are those normal?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfJJF8X8w-eMoAny_Ps:bqstep)*

**Comment by jwnimmer-tri** [comment]
> Are those normal?

Yes.

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJMjD8_g-gW7t3sBFG:-KfJMjD8_g-gW7t3sBFH:bude02o) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L161)):*
> ```reStructuredText
> 
> To build all of Drake with default Bazel options, select
> ``Bazel > Make Project``.
> ```

There was no menu item "Bazel/Make Project". However there was "Bazel/Compile Project". I selected that and it ran a "bazel build" but completed within a few seconds. Could it have built everything in the previous step?

---

*[drake/doc/clion.rst, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJNKWc_nS4lxcGAnFW:-KfJNKWc_nS4lxcGAnFX:b-4djrgz) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L168)):*
> ```reStructuredText
> 
> To run a specific target in the debugger, create a configuration as above,
> using the ``bazel run`` command. Then launch it from ``Run > Debug``.
> ```

It wasn't clear to me what to do here. In CMake-based CLion there is a pull down with all the targets so I could run specific tests. Do you have to create a separate configuration for each test executable?

Also, the Edit Configurations form wanted something called a "target expression". It wasn't clear to me what goes there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509)*

**Comment by sherm1** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJNKWc_nS4lxcGAnFW:-KfJOtVMF0PY93ImqFE-:b2e0ua) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L168)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

It wasn't clear to me what to do here. In CMake-based CLion there is a pull down with all the targets so I could run specific tests. Do you have to create a separate configuration for each test executable?

Also, the Edit Configurations form wanted something called a "target expression". It wasn't clear to me what goes there.
</blockquote></details>

I figured out how to make a configuration to run a test case. Next question that came up was how to make a debug version of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509)*

**Comment by sherm1** [comment]
This is working for me except for the git interface in CLion. I think the problem is that CLion thinks that `drake-distro/bazel-drake-distro` is a repo (because it contains a `.git`) and then it thinks there are ~4000 modified files in it that need to be committed. (CLion adds that as a "git root".) I could not figure out how to get CLion to ignore that "repo". Any ideas? Can Bazel be taught not to write into my source directory?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfKS6T4s6KNEci2YVe9:b-vqq49k)*

**Comment by david-german-tri** [comment]
> This is working for me except for the git interface in CLion

I can reproduce the problem and am investigating.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/doc/clion.rst, line 161 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJMjD8_g-gW7t3sBFG:-KfMGqM-Ss19pLyfYFLD:b5pepf1) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L161)):*
> There was no menu item "Bazel/Make Project". However there was "Bazel/Compile Project".

Done!

> I selected that and it ran a "bazel build" but completed within a few seconds. Could it have built everything in the previous step?

Yeah, it compiles the entire project when you import for the first time.  Updated to clarify.

---

*[drake/doc/clion.rst, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJNKWc_nS4lxcGAnFW:-KfMIv49VB_Gc9QXUBPR:b-x4cljn) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L168)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I figured out how to make a configuration to run a test case. Next question that came up was how to make a debug version of that.
</blockquote></details>

These questions are really about Bazel, not CLion, but I've added a little more information here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfMGZABGP_Td0VFOszB:b-bewt3g)*

**Comment by david-german-tri** [comment]
> This is working for me except for the git interface in CLion

I've found and documented a workaround, PTAL!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfMRjxmxaL0yHgcbBZm:b-vx0giy)*

**Comment by sherm1** [comment]
:lgtm: -- thanks, David!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 168 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfJNKWc_nS4lxcGAnFW:-KfMdbwFoSNKytVUgtXa:b2kums2) ([raw file](https://github.com/robotlocomotion/drake/blob/77a7109475bdc61022a5b53202c8233e006f47c5/drake/doc/clion.rst#L168)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

These questions are really about Bazel, not CLion, but I've added a little more information here.
</blockquote></details>

Thanks, I discovered `-c dbg`. 

---

*[drake/doc/clion.rst, line 189 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfMd7xiFFhPMdy2avDp:-KfMd7xiFFhPMdy2avDq:b-zcy1ga) ([raw file](https://github.com/robotlocomotion/drake/blob/3817739f163dfcf1a7435d26a8f6b11bafb4976c/drake/doc/clion.rst#L189)):*
> ```reStructuredText
> spuriously appear in the CLion UI. To make CLion ignore ``bazel-drake-distro``,
> enable Git integration, shut down CLion, and remove the ``bazel-drake-distro``
> line from ``.idea/vcs.xml`` in your CLion project directory.
> ```

BTW, this works perfectly -- thanks!

Likely this deserves a bug report submitted ... somewhere. Do you know the right venue? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-:-KfMdtVvd28t4m7rKR9H:bt68ewr)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/doc/clion.rst, line 189 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfMd7xiFFhPMdy2avDp:-KfMqD8Ev726G4YAfrZQ:b-e8r3k6) ([raw file](https://github.com/robotlocomotion/drake/blob/3817739f163dfcf1a7435d26a8f6b11bafb4976c/drake/doc/clion.rst#L189)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, this works perfectly -- thanks!

Likely this deserves a bug report submitted ... somewhere. Do you know the right venue? 
</blockquote></details>

I'd say it's an IntelliJ feature request ("provide some UI to do that thing we just did to the XML file").  I can't find an existing FR, although there is some textually-similar stuff about unregistered VCS roots that I predict will cause confusion.

Conclusion: I'll leave opening this issue to someone who has more IntelliJ big picture than I do.  Maybe you, or @seancurtis-tri?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509)*

**Comment by sherm1** [comment]
*[drake/doc/clion.rst, line 189 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/5509#-KfMd7xiFFhPMdy2avDp:-KfNMsW4BGDeEFpjueXX:b-z34zmo) ([raw file](https://github.com/robotlocomotion/drake/blob/3817739f163dfcf1a7435d26a8f6b11bafb4976c/drake/doc/clion.rst#L189)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

I'd say it's an IntelliJ feature request ("provide some UI to do that thing we just did to the XML file").  I can't find an existing FR, although there is some textually-similar stuff about unregistered VCS roots that I predict will cause confusion.

Conclusion: I'll leave opening this issue to someone who has more IntelliJ big picture than I do.  Maybe you, or @seancurtis-tri?
</blockquote></details>

While attempting to write the feature request for IntelliJ I found the already-existing GUI feature for doing exactly what we want! PR momentarily ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5509)*

**Pull request merged**
