### PR TITLE
[pydrake] Leave C++ logging sink intact (but no-op)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Sometimes, users might still want to add more C++ specific sinks (e.g., logging over the network) even when running via pydrake.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18750)

### CODE REVIEW

**Comment by dmcconachie-tri** [comment]
I can confirm that my immediate symptoms (C++ call failing as the root node type has been modified) have been resolved by this patch. I have not confirmed if both the python and C++ logging calls have successfully made it to all the sinks (console and LCM log on disk).

**Comment by dmcconachie-tri** [comment]
Confirmed that the data is all logged to console in the following format:

```
 [2023-02-13 15:57:26,506] [drake] [INFO] <python message here>
...
[2023-02-13 15:57:26.507] [console] [info] <C++ message here>
...
```
when following the instructions here: https://drake.mit.edu/pydrake/pydrake.common.html#pydrake.common.configure_logging

Presumably if I was so inclined I could change the `[drake]` to `[console]` in python.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for both reviews per schedule, please.

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/18750#-:-NOQvf3d85yzaYeI4m02:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee sammy-tri(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
