### PR TITLE
doc: Add release notes v0.33.0

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
ETA is August 9th or later.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.33.0.md, line 77 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15516#-Mg8bY9IE3IEkbDUGjW3:-Mg8bY9IE3IEkbDUGjW4:bb5uhjm) ([raw file](https://github.com/robotlocomotion/drake/blob/0f68fcfd592ded4ef92c20180cf8da6334cc12c7/doc/_release-notes/v0.33.0.md#L77)):*
> ```Markdown
> * Allow model_instances in MultibodyPlant CalcJacobianCenterOfMassTranslationalVelocity ([#15387][_#15387])
> * TBD QueryObject's new queries for hydroelastics ([#15210][_#15210])
> * TBD Select output format from mesh_half_space_intersection in hydroelastics ([#15358][_#15358])
> ```

@SeanCurtis-TRI or @DamrongGuoy for the prior two TBDs here (15210, 15358) could you help me out with release notes text?

Is it just under the usual umbrella "New hydroelastic contact model in progress"?

Or should we say something in particular here?  (In which case, paste the one-liner here, or push a commit to this branch.)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @SeanCurtis-TRI)

___
*[doc/_release-notes/v0.33.0.md, line 77 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15516#-Mg8bY9IE3IEkbDUGjW3:-Mg8u4cP7b0BNb3iQ1LM:b-xzjtkk) ([raw file](https://github.com/robotlocomotion/drake/blob/0f68fcfd592ded4ef92c20180cf8da6334cc12c7/doc/_release-notes/v0.33.0.md#L77)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@SeanCurtis-TRI or @DamrongGuoy for the prior two TBDs here (15210, 15358) could you help me out with release notes text?

Is it just under the usual umbrella "New hydroelastic contact model in progress"?

Or should we say something in particular here?  (In which case, paste the one-liner here, or push a commit to this branch.)
</blockquote></details>

I think it should be under the usual umbrella `"New hydroelastic contact model in progress"`.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

___
*[doc/_release-notes/v0.33.0.md, line 77 at r3](https://reviewable.io/reviews/robotlocomotion/drake/15516#-Mg8bY9IE3IEkbDUGjW3:-Mg8xZRR1U1BwgQ4jfNm:b-dtkds3) ([raw file](https://github.com/robotlocomotion/drake/blob/0f68fcfd592ded4ef92c20180cf8da6334cc12c7/doc/_release-notes/v0.33.0.md#L77)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I think it should be under the usual umbrella `"New hydroelastic contact model in progress"`.
</blockquote></details>

Done, thanks!

**Comment by RussTedrake** [comment]
As requested, I am commenting here that I would like to see #15549 to be resolved for this release, if it is reasonable.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: 1 unresolved discussion, needs platform reviewer assigned, needs at least one assigned reviewer, labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15516#-MgMGF_gDEX3puPPq5Di:-MgMGF_gDEX3puPPq5Dj:b2b3mx5) (no related file):*
Working

Moving Russ's comment to a thread:

> As requested, I am commenting here that I would like to see #15549 to be resolved for this release, if it is reasonable.

---

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake/15516#-MgMGF_gDEX3puPPq5Di:-MgmuJ962XVUQvQNNMFb:b10zu0q) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Moving Russ's comment to a thread:

> As requested, I am commenting here that I would like to see #15549 to be resolved for this release, if it is reasonable.

</blockquote></details>

Given that #15596 indicates our v0.32.0 stable release no longer works at all on homebrew, I think that tips the scale to releasing ASAP to unbreak macOS.  The #15549 is a real issue, but is not a regression.

---
___
*[doc/_release-notes/v0.33.0.md, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15516#-MgmuiNY2sqlICfoFsJk:-MgmuiNY2sqlICfoFsJl:bhdjlpy) ([raw file](https://github.com/robotlocomotion/drake/blob/5238b5d7448cee83edbf7b3045809348c8a93762/doc/_release-notes/v0.33.0.md#L3)):*
> ```Markdown
> ---
> title: Drake v0.33.0
> released: YYYY-MM-DD
> ```

Working

Still needs YYYYMMDD updates throughout.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: LGTM missing from assignee jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @rpoyner-tri)

___
*[doc/_release-notes/v0.33.0.md, line 3 at r6](https://reviewable.io/reviews/robotlocomotion/drake/15516#-MgmuiNY2sqlICfoFsJk:-MgpWvgBEUhZtPyo2oa3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/5238b5d7448cee83edbf7b3045809348c8a93762/doc/_release-notes/v0.33.0.md#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Still needs YYYYMMDD updates throughout.
</blockquote></details>

Done.

**Comment by jwnimmer-tri** [comment]
+@sammy-tri for all reviews per schedule, please.

**Review by sherm1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516)* status: LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-documentation please

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/15516#-:-MgpvyuL1dAaduX8F-H7:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),jwnimmer-tri(platform), labeled "do not merge", commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @sammy-tri)

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail please manually tag docker images and upload the releases to S3. 

The binary date is `20210811`.
The commit SHA is `92be0bd4a6c50cdd0edb1963323ccbd178c0f608`.
The release tag is `v0.33.0`.

**Comment by BetsyMcPhail** [comment]
Docker images and uploads for the release are all set.

**Pull request merged**
