### PR TITLE
Port systems/lcm to drake_copyable

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
A portion of #4861.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/5141)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@liangfok for feature review, please.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5141#-:-KcjF2-FL8kyNPnyeR38:bltds52)*

**Comment by liangfok** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5141#-:-KcjNv9esttgb7EMwR95:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
+@sherm1 for platform review, please.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5141#-:-KcjOKYn29eNO9RSqokL:bppyoqq)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/5141#-:-KcnuJwUfwBpM17DEoUa:bnfp4nl)*

**Pull request merged**
