### PR TITLE
Add counterexample_solver_options to IrisOptions.

### LINKED ISSUE #21150: Allow User to Set SolverOptions for IrisInConfigurationSpace
Currently, there's no way for the user to specify solver options to be applied to the counterexample searches used by IrisInConfigurationSpace. For example, if I want to set the feasibility or optimality tolerances in SNOPT to be loose, I don't have such an option. This would be useful for generating rough candidate regions, where we don't need such tight tolerances or guarantees.

cc @rhjiang @wernerpe

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolve #21150

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@RussTedrake for feature review.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-:-NtjpAWA1FjIWbiJVD0W:b1ikduc)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/iris.cc` line 860 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-NtjoiZFEtjquC2paVmZ:-NtjoiZFEtjquC2paVm_:b4eskee) ([raw file](https://github.com/RobotLocomotion/drake/blob/ec0b355dd6d4cace23793e578434a7d10a7f1283/geometry/optimization/iris.cc#L860)):*
> ```cpp
>                    options.num_additional_constraint_infeasible_samples) {
>               if (counter_example_prog->Solve(
>                       *solver, guess, options.counterexample_solver_options,
> ```

there are two calls to Solve in this loop.  (This is actually the one that most people don't use).  We need to pass the solve options in both.  

Is there any form of test you can add?  I think you would have seen that for almost all of the examples in the tests, your code didn't actually set the solver options.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182)* status: 1 unresolved discussion, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes

___
*[`geometry/optimization/iris.cc` line 860 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-NtjoiZFEtjquC2paVmZ:-NtxPiGB21Qm1XP5NUNl:b-36m4a) ([raw file](https://github.com/RobotLocomotion/drake/blob/ec0b355dd6d4cace23793e578434a7d10a7f1283/geometry/optimization/iris.cc#L860)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

there are two calls to Solve in this loop.  (This is actually the one that most people don't use).  We need to pass the solve options in both.  

Is there any form of test you can add?  I think you would have seen that for almost all of the examples in the tests, your code didn't actually set the solver options.
</blockquote></details>

Done. I added two solver options for both Solve, together with the tests.

**Comment by RussTedrake** [comment]
*[`geometry/optimization/test/iris_internal_test.cc` line 82 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-Nu8sV5P3aaoTdCTD7Vt:-Nu8sV5P3aaoTdCTD7Vu:b-el7ntg) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7c7a61e429c64ec116d0a6415e6d6dd3cfe4a6c/geometry/optimization/test/iris_internal_test.cc#L82)):*
> ```cpp
>     std::tie(plant_, scene_graph_) =
>         multibody::AddMultibodyPlantSceneGraph(&builder, 0.0);
>     // Add two spheres with arbitrary mass/inertia.
> ```

stale comment?

**Review by RussTedrake — COMMENTED** [review]
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182)* status: 4 unresolved discussions, LGTM missing from assignee RussTedrake(platform), needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/iris.h` line 168 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-Nu8pJYXBjGp5Psofnrd:-Nu8pJYXBjGp5Psofnre:bfhv0w7) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7c7a61e429c64ec116d0a6415e6d6dd3cfe4a6c/geometry/optimization/iris.h#L168)):*
> ```objc
>   /* The SolverOptions used in the optimization program to find the closest
>    * point. */
>   std::optional<solvers::SolverOptions> closest_collision_solver_options;
> ```

i would have thought we'd just use counterexample_solver_options for both of these.  in my view, the closest collision program is just a specific (optimized) instantiation of the counterexample search, and the second one is the generic implementation.

If we do leave both, then we absolutely need to make the documentation more clear.  the names ClosestCollision and CounterExample were for internal use, but would not make sense for users here without that context.
___
*[`geometry/optimization/test/iris_internal_test.cc` line 23 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-Nu8q5Bc6cnPe_M6MQUo:-Nu8q5Bc6cnPe_M6MQUp:b5vp86g) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7c7a61e429c64ec116d0a6415e6d6dd3cfe4a6c/geometry/optimization/test/iris_internal_test.cc#L23)):*
> ```cpp
>     std::tie(plant_, scene_graph_) =
>         multibody::AddMultibodyPlantSceneGraph(&builder, 0.0);
>     // Add two spheres with arbitrary mass/inertia.
> ```

fwiw: i would have done this with a few lines of mjcf + the parser.  it would be much shorter and more readable/maintainable.  

I believe it would be, e.g.
```
<mujoco model="twospheres">
  <worldbody>
    <body><geom type="sphere" size="0.1"/></body>
    <body><geom type="sphere" size="0.2" /></body>
  </worldbody>
</mujoco>
```
___
*[`geometry/optimization/test/iris_internal_test.cc` line 75 at r3](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-Nu8sYAb4DvMzGIG4Gci:-Nu8sYAb4DvMzGIG4Gcj:bg1t8w2) ([raw file](https://github.com/RobotLocomotion/drake/blob/f7c7a61e429c64ec116d0a6415e6d6dd3cfe4a6c/geometry/optimization/test/iris_internal_test.cc#L75)):*
> ```cpp
> 
> // A planar robot with three links (including one base link), connected by two
> // revolute joints.
> ```

fwiw: https://github.com/RobotLocomotion/drake/blob/master/multibody/benchmarks/acrobot/acrobot.xml

**Review by RussTedrake — COMMENTED** [review]
:lgtm:  thanks!

You have a bunch of CI errors; but otherwise I'd say it's ready for platform review.

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-:-NuGrS13CNfiGSpWxlT7:b-z90fno)* status: needs at least two assigned reviewers, missing label for release notes (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
+@SeanCurtis-TRI for platform review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-:-NuPb0U83yOqqrL7bWF6:bycyfct)* status: LGTM missing from assignee SeanCurtis-TRI(platform), missing label for release notes (waiting on @hongkai-dai)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: With a couple of nits.

> Reviewed 2 of 10 files at r2, 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-:-NuPwkQd4spOnnV5zUtA:b-xlmni7)* status: 2 unresolved discussions, missing label for release notes (waiting on @hongkai-dai)

___
*[`geometry/optimization/test/iris_internal_test.cc` line 113 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-NuPwBt_1hmwXNl_7O-l:-NuPwBt_1hmwXNl_7O-m:b4bsfgf) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf5ad1d745f9f6ecec9226bca0cb3eb7aafc3ee9/geometry/optimization/test/iris_internal_test.cc#L113)):*
> ```cpp
>   const double radius_A = 0.1;
>   const double radius_B = 0.1;
>   Hyperellipsoid setA(1. / radius_A * Eigen::Matrix3d::Identity(),
> ```

nit: replace 1. with 1.0 as per [styleguide](https://drake.mit.edu/styleguide/cppguide.html#Floating_Literals) (here and on `setB`).
___
*[`bindings/pydrake/geometry/test/optimization_test.py` line 25 at r5](https://reviewable.io/reviews/RobotLocomotion/drake/21182#-NuPwf8P14IX86g-4QmV:-NuPwf8Q3HTaFsZpJJ9r:b-6dbb8o) ([raw file](https://github.com/RobotLocomotion/drake/blob/cf5ad1d745f9f6ecec9226bca0cb3eb7aafc3ee9/bindings/pydrake/geometry/test/optimization_test.py#L25)):*
> ```Python
>     Binding, ClpSolver, Constraint, Cost, MathematicalProgram,
>     MathematicalProgramResult, SolverOptions, CommonSolverOption,
>     ScsSolver, SolverOptions, MosekSolver
> ```

nit" This addition is redundant; it's already included in the previous line.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21182)* status: missing label for release notes (waiting on @hongkai-dai)

**Pull request merged**
