### PR TITLE
[workspace] Upgrade VTK to latest commit

### LINKED ISSUE #20772: Teach new_release about vtk_internal
This isn't really relevant until #20765 lands, but after that does -- we should be sure to remind ourselves every month to see if we can upgrade VTK to a newer version.

For now that would mean re-pinning to newer commits on the master branch, but eventually I expect we'd switch to use the stable, numbered releases.

The most important thing is that `new_release` reminds us about the need.  It's not clear that trying to _automate_ the upgrade would pay off, but I'm open to the possibility if it seems to make sense.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Also unpin it so that it will be upgraded every month. This requires adding one more trampoline to the repository rule.

Closes #20772.

+@svenevs for feature review, please.

\CC @mwoehlke-kitware FYI

I've locally tested that `new_release` works (by using it to _actually_ bump the git commit seen here).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867)* status: LGTM missing from assignee svenevs, needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/vtk_internal/repository.bzl` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-NpaTMCW-qw7LOfwykE8:-NpaTMCW-qw7LOfwykE9:bzg1eov) ([raw file](https://github.com/RobotLocomotion/drake/blob/f90e70a6024e506d8990952a33d7d669d65fed8d/tools/workspace/vtk_internal/repository.bzl#L149)):*
> ```Starlark
>             default = [
>                 "@drake//tools/workspace/vtk_internal:patches/common_core_version.patch",  # noqa
>                 "@drake//tools/workspace/vtk_internal:patches/filters_sources_cylinder.patch",  # noqa
> ```

FYI This patch got removed (compared to the text below).

**Review by svenevs — COMMENTED** [review]
:lgtm: Matthew is out today and possibly Monday, everything looks in order to me.

> I've locally tested that `new_release` works (by using it to _actually_ bump the git commit seen here).

I don't really know the monthly upgrades parts, Matthew is out today and possibly Monday.  @BetsyMcPhail might be able to help quickly test that it tries to upgrade VTK when run from this PR branch, but since you used it to bump things I'm also happy to say this is ready for platform review.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-:-NpfhhtO7h1F2T1wgAvV:by5s05j)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/vtk_internal/repository.bzl` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-NpaTMCW-qw7LOfwykE8:-NpfftPXA0QahUyTeTda:bkptfh4) ([raw file](https://github.com/RobotLocomotion/drake/blob/f90e70a6024e506d8990952a33d7d669d65fed8d/tools/workspace/vtk_internal/repository.bzl#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This patch got removed (compared to the text below).
</blockquote></details>

OK, nice, the process works!  There's only one left that's ready to be upstreamed (`gltf_parser.patch`).  Should we open a ticket and plan to upstream it near the end of the month or something (as a "known test for monthly updates")?  I didn't look very closely at the patch, just remember there was only one left when I looked during f2f.
___
*[`tools/workspace/vtk_internal/repository.bzl` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-Npfg4tl38UDNz2usBUk:-Npfg4tm2PhE1v-a6U9d:b-t133my) ([raw file](https://github.com/RobotLocomotion/drake/blob/bac6b9c644601ec770520783b771c8ba56a5aa90/tools/workspace/vtk_internal/repository.bzl#L157)):*
> ```Starlark
>         # TODO(jwnimmer-tri) Once there's a tagged release with support for
>         # VTK_ABI_NAMESPACE, we should switch to an official version number
>         # here. That probably means waiting for the VTK 10 release.
> ```

FYI, this is the only thing I don't really understand about the future plan.  Once the next VTK is released, are we going to

1. Keep tracking `master` each month?
2. Start tracking that release branch and only pickup backports?
3. Restore pinning the commit?

If we're going to keep tracking `master`, I'd say this `TODO` can be removed.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[`tools/workspace/vtk_internal/repository.bzl` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-NpaTMCW-qw7LOfwykE8:-NpfkaepA2sJkFGVlhws:b-tbpsko) ([raw file](https://github.com/RobotLocomotion/drake/blob/f90e70a6024e506d8990952a33d7d669d65fed8d/tools/workspace/vtk_internal/repository.bzl#L149)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

OK, nice, the process works!  There's only one left that's ready to be upstreamed (`gltf_parser.patch`).  Should we open a ticket and plan to upstream it near the end of the month or something (as a "known test for monthly updates")?  I didn't look very closely at the patch, just remember there was only one left when I looked during f2f.
</blockquote></details>

Basically yes.

It seems worthwhile to periodically check the list of patches and work to open merge requests to get them upstreamed.

I'll defer to you on what periodicity makes sense for that.  I'd guess the optimal answer would be something aligned with the VTK release cadence, so if that is once every 6 months, maybe we check for patches to upstream once every 3 months or so?
___
*[`tools/workspace/vtk_internal/repository.bzl` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-Npfg4tl38UDNz2usBUk:-NpfjUmS-3qKj2ZMW4Hl:bn0nmvh) ([raw file](https://github.com/RobotLocomotion/drake/blob/bac6b9c644601ec770520783b771c8ba56a5aa90/tools/workspace/vtk_internal/repository.bzl#L157)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

FYI, this is the only thing I don't really understand about the future plan.  Once the next VTK is released, are we going to

1. Keep tracking `master` each month?
2. Start tracking that release branch and only pickup backports?
3. Restore pinning the commit?

If we're going to keep tracking `master`, I'd say this `TODO` can be removed.
</blockquote></details>

For our downstream users who provide their own builds of externals instead of using ours, it's slightly kinder to stick with official version numbers (not git shas) to simplify what they need to do.

Therefore, my goal is to switch to using _only_ numbered VTK releases like "10.0" once there is one that offers the necessary ABI-control support (which I think is consistent with this TODO), and to track minor & patch releases as normal during the monthly updates (which is consistent with no longer having a commit_pin).  In short, like any other external we have.

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule (Monday), please.

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/vtk_internal/repository.bzl` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-NpaTMCW-qw7LOfwykE8:-Npfolr90yy_To0mfWav:btile77) ([raw file](https://github.com/RobotLocomotion/drake/blob/f90e70a6024e506d8990952a33d7d669d65fed8d/tools/workspace/vtk_internal/repository.bzl#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Basically yes.

It seems worthwhile to periodically check the list of patches and work to open merge requests to get them upstreamed.

I'll defer to you on what periodicity makes sense for that.  I'd guess the optimal answer would be something aligned with the VTK release cadence, so if that is once every 6 months, maybe we check for patches to upstream once every 3 months or so?
</blockquote></details>

Ok, makes sense.  I poked internally and probably sometime soon we'll have a new #buildcop reminder schedule setup to check for patches :+1:
___
*[`tools/workspace/vtk_internal/repository.bzl` line 157 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-Npfg4tl38UDNz2usBUk:-Npfp1t41WZWrwvEGkFP:b-fxngxl) ([raw file](https://github.com/RobotLocomotion/drake/blob/bac6b9c644601ec770520783b771c8ba56a5aa90/tools/workspace/vtk_internal/repository.bzl#L157)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

For our downstream users who provide their own builds of externals instead of using ours, it's slightly kinder to stick with official version numbers (not git shas) to simplify what they need to do.

Therefore, my goal is to switch to using _only_ numbered VTK releases like "10.0" once there is one that offers the necessary ABI-control support (which I think is consistent with this TODO), and to track minor & patch releases as normal during the monthly updates (which is consistent with no longer having a commit_pin).  In short, like any other external we have.
</blockquote></details>

Ah, ok that makes sense.  Neat!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

___
*[`tools/workspace/vtk_internal/repository.bzl` line 149 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-NpaTMCW-qw7LOfwykE8:-Npg1IyO9Wr5EOJNS_l-:b-n9zow9) ([raw file](https://github.com/RobotLocomotion/drake/blob/f90e70a6024e506d8990952a33d7d669d65fed8d/tools/workspace/vtk_internal/repository.bzl#L149)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Ok, makes sense.  I poked internally and probably sometime soon we'll have a new #buildcop reminder schedule setup to check for patches :+1:
</blockquote></details>

(Maybe a #tri-kitware reminder, though; not really a buildcop job.)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20867#-:-Npv40jD6_nTBYXthn5y:bmxilld)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),svenevs

**Pull request merged**
