### PR TITLE
AgentTrajectory/TrajectoryAgent -> Trajectory/TrajectoryFollower

### PR DESCRIPTION
**Pull request by stonier**
AgentTrajectory/TrajectoryAgent renamed to Trajectory/TrajectoryFollower
respectively. This aims to minimalise the functionality to the system
level (only what is necessary to compute in the simulation update step).

Agent and agent-related data will be handled elsewhere.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8839)

### CODE REVIEW

**Comment by stonier** [comment]
+@jadecastro for feature review please.

---







*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8839#-:-LD4Xy3A2gyOfgpj7OlL:be98m6n)*

**Comment by jadecastro** [comment]
:lgtm: with a few BTWs.

---

Reviewed 13 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[automotive/trajectory.h, line 90 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8839#-LD6WqauBHCQKZBDiFKr:-LD6Wqav0H9GsMdinm7s:bmf2igu) ([raw file](https://github.com/robotlocomotion/drake/blob/394c7c89770bd9f1adea5c3f684ce0f6e99b9847/automotive/trajectory.h#L90)):*
> ```objc
> 
>   /// An identifier for the type of valid types of interpolation used in
>   /// evaluating the translational component of an Trajectory.  These types
> ```

BTW, typo "an" -> "a" (also in a couple other places below)

---

*[automotive/trajectory_follower.h, line 51 at r1](https://reviewable.io/reviews/robotlocomotion/drake/8839#-LD6XzgA4VrY6_xipdui:-LD6XzgA4VrY6_xipduj:bhau359) ([raw file](https://github.com/robotlocomotion/drake/blob/394c7c89770bd9f1adea5c3f684ce0f6e99b9847/automotive/trajectory_follower.h#L51)):*
> ```objc
>   /// Constructs a TrajectoryFollower system that traces a given Trajectory.
>   ///
>   /// @param trajectory an Trajectory containing the trajectory.
> ```

BTW, could you please change this to read "@param trajectory a Trajectory of poses and velocities." ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8839#-:-LD6Zag10FC0tvzoIl8g:b-uqs2tu)*

**Comment by jadecastro** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8839)*

**Comment by stonier** [comment]
+@sammy-tri for platform review please.

**Comment by sammy-tri** [comment]
:lgtm: +(status: curate commits before merging) 

Someday we should think of consolidating our multiple cartesian trajectory representations and trajectory evaluator systems, but I don't think this PR needs to be that day.

---

Reviewed 9 of 19 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/8839#-:-LD8f2UqEbdAYANvRmsZ:bwsbyzl)*

**Comment by stonier** [comment]
> Someday we should think of consolidating our multiple cartesian trajectory representations and trajectory evaluator systems, but I don't think this PR needs to be that day.

Aye. Suggested this to Jon earlier, but we'll be iterating on this pretty aggressively for a while. I'd to consider this once it's done.

**Pull request merged**
