### PR TITLE
Added infinity norm to VectorBase and BasicVector.

### PR DESCRIPTION
**Pull request by edrumwri**
Addresses issue #3845

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4006)

### CODE REVIEW

**Comment by edrumwri** [comment]
+@david-german-tri for feature reviewer and +@sammy-tri for platform reviewer please

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-:-KVbMYLXjolBlDH09T-q:b-s2f3u3)*

**Comment by david-german-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNZ7K4u20RY6sPnK5:-KVbNZ7LlCRn-fjLBUJD:b1jhouo) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L144)):*
> ```objc
>   /// ensure that this operation remains O(N) in the size of
>   /// the value and allocates no memory.
>   virtual T NormInf() const {
> ```

Please also add a test to `subvector_test.cc` so that this has coverage.

---

*[drake/systems/framework/vector_base.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNJVkEBi0yUeDcvNt:-KVbNJVkEBi0yUeDcvNu:b-detkrl) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L149)):*
> ```objc
>     T nrm(0);
>     const int sz = size();
>     for (int i=0; i< sz; ++i) {
> ```

btw spacing nit `i = 0; i < sz`

---

*[drake/systems/framework/test/basic_vector_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNTmSyJ6iz2hgq4U1:-KVbNTmTMcffyWgh5Yji:b-bkfj4k) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/test/basic_vector_test.cc#L112)):*
> ```cpp
> GTEST_TEST(BasicVectorTest, InfNorm) {
>   BasicVector<int> vec(2);
>   vec.get_mutable_value() << 3, 4;
> ```

I'd suggest using `-4` to exercise the `abs`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbQBI9BlANq4B2W_2K:-KVbQBI9BlANq4B2W_2L:b-8utqmo) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L147)):*
> ```objc
>     using std::abs;
>     using std::max;
>     T nrm(0);
> ```

BTW nit: "do not abbreviate by deleting letters within a word."
-- https://google.github.io/styleguide/cppguide.html

---

*[drake/systems/framework/vector_base.h, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbQE361vdeS37K9IYD:-KVbQE361vdeS37K9IYE:b-8utqmo) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L148)):*
> ```objc
>     using std::max;
>     T nrm(0);
>     const int sz = size();
> ```

BTW nit: "do not abbreviate by deleting letters within a word."
-- https://google.github.io/styleguide/cppguide.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 144 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNZ7K4u20RY6sPnK5:-KVbTzta7WNDVzjQOmFS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L144)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> Please also add a test to `subvector_test.cc` so that this has coverage.
</details>
Done.

---

*[drake/systems/framework/vector_base.h, line 147 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbQBI9BlANq4B2W_2K:-KVbSdRNxNy0av8mct9s:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L147)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW nit: "do not abbreviate by deleting letters within a word."
> -- https://google.github.io/styleguide/cppguide.html
</details>
Done.

---

*[drake/systems/framework/vector_base.h, line 148 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbQE361vdeS37K9IYD:-KVbScz--I6D8mjDxa4F:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> BTW nit: "do not abbreviate by deleting letters within a word."
> -- https://google.github.io/styleguide/cppguide.html
</details>
Done.

---

*[drake/systems/framework/vector_base.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNJVkEBi0yUeDcvNt:-KVbSci-hNxRrVLR7A4h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L149)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> btw spacing nit `i = 0; i < sz`
</details>
Done.

---

*[drake/systems/framework/test/basic_vector_test.cc, line 112 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNTmSyJ6iz2hgq4U1:-KVbSMRt0nnq8kM9ilXY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/test/basic_vector_test.cc#L112)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary>
> I'd suggest using `-4` to exercise the `abs`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 148 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbU_VgyI1js5FxtS1q:-KVbU_VgyI1js5FxtS1r:b-h2tlxl) ([raw file](https://github.com/robotlocomotion/drake/blob/16be17af4099950caa97e872c1e51cf28e84b17c/drake/systems/framework/vector_base.h#L148)):*
> ```objc
>     using std::max;
>     T norm(0);
>     const int kSize = size();
> ```

The `kFoo` syntax may only be used when "the value is fixed for the duration of the program".  Since the value may vary from one call here to the next, it can't be used in this case.
-- https://google.github.io/styleguide/cppguide.html#Constant_Names

(Sorry, the `const int size = size();` idiom is a particularly unfortunate confluence of style rules.  Things like `siz` or `num` or `count` are fair solutions I've seen before.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by edrumwri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 148 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbU_VgyI1js5FxtS1q:-KVbWg2sRobCf7fkm4PV:bo0c70i) ([raw file](https://github.com/robotlocomotion/drake/blob/16be17af4099950caa97e872c1e51cf28e84b17c/drake/systems/framework/vector_base.h#L148)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> The `kFoo` syntax may only be used when "the value is fixed for the duration of the program".  Since the value may vary from one call here to the next, it can't be used in this case.
> -- https://google.github.io/styleguide/cppguide.html#Constant_Names
> 
> (Sorry, the `const int size = size();` idiom is a particularly unfortunate confluence of style rules.  Things like `siz` or `num` or `count` are fair solutions I've seen before.)
</details>
Thanks Jeremy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by jwnimmer-tri** [comment]
I might as well take platform on this one also.
-@sammy-tri +@jwnimmer-tri for platform.

:lgtm: pending open discussions.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNJVkEBi0yUeDcvNt:-KVc5F6qon67nV-KvhET:b-5bop6o) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L149)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary>
> Done.
</details>
Still needs `i = 0` whitespace around the `=`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-:-KVc59qnlnsGx_s2lSzV:b-rlk74j)*

**Comment by edrumwri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake/systems/framework/vector_base.h, line 149 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-KVbNJVkEBi0yUeDcvNt:-KVeSMbQeddXZ0zGclb8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/1719d632f31ef4b0ff1ab2773c49d97870253919/drake/systems/framework/vector_base.h#L149)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary>
> Still needs `i = 0` whitespace around the `=`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006#-:-KVeVJRpc008KpbhPZg_:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4006)*

**Pull request merged**
