### PR TITLE
Update the Drake credits list

### PR DESCRIPTION
**Pull request by sherm1**
Added mention of TRI and some missing contributors to the [Drake credits list](https://drake.mit.edu/credits.html). Please let me know if you _don't_ want to be listed.

This not an attempt to be comprehensive -- these are just people I noticed were missing. If anyone wants to be added to this PR let me know.

cc @EricCousineau-TRI @xuchenhan-tri @joemasterjohn @dmcconachie-tri

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Thanks!!!

**Review by xuchenhan-tri — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162#-:-MIfNG3_7Ua8iyUZCfs4:b-9755fn)* status: needs platform reviewer assigned, needs at least two assigned reviewers

**Review by sherm1 — COMMENTED** [review]
+@ericcousineau-tri for all review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162#-:-MIfgljxAWKmURTjL3gM:b-vqaauz)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

**Review by sherm1 — COMMENTED** [review]
+@sammy-tri for all review per rotation, please
-@ericcousineau-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162#-:-MJ-2Zd-2jY-AsaFrolr:b-k8w1ms)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by joemasterjohn — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162#-:-MJ-CI1uCnK_xtnDWQVz:b-ucfknh)* status: LGTM missing from assignee sammy-tri(platform) (waiting on @sammy-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Sorry for missing the review assignment completely!
I'm cool with this as-is, will go ahead and merge it in.

-@sammy-tri +@ericcousineau-tri :lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162#-:-MJ08BSC4wu8Sl2epfPN:b5ff5fp)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14162)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @sherm1)

___
*[doc/credits.rst, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14162#-MJ08NNa6kzSgfhdjYMm:-MJ08NNa6kzSgfhdjYMn:bv2z65b) ([raw file](https://github.com/robotlocomotion/drake/blob/ab75cd18cc7c31bc529c39e68386080ac33681e7/doc/credits.rst#L5)):*
> ```reStructuredText
> *******
> 
> The Drake project was started by Russ Tedrake and the members of the 
> ```

nit Trailing whitespace.

Will push the change here and merge.

**Pull request merged**
