### PR TITLE
Simple crazyflie example

### PR DESCRIPTION
**Pull request by blandry**
Adding a crazyflie directory to the Quadrotor example. It contains a simple urdf model and a script to run direct collocation with it. This is for the research group that asked for our model.

### CODE REVIEW

**Comment by blandry** [comment]
Those build fails look like they come from the makefile correct?

**Comment by psiorx** [comment]
I'll take a look.

**Comment by psiorx** [comment]
Seems like a tab might be missing in a makefile?

**Comment by RussTedrake** [comment]
don't know what happened with the build servers.  all looks good to me, except that you don't actually need to include the wrl file (matlab can automatically convert stl to wrl).

**Comment by RussTedrake** [comment]
(note that to properly remove the wrl file, you'll want to actually remove it from the history, too)

**Comment by blandry** [comment]
I will redo a pull request. I filtered the history for the file and it messed up my branch.

**Pull request closed without merging**
