### PR TITLE
upgrade gurobi to 9.5.1 (which includes macos arm64 support)

### LINKED ISSUE #16604: Upgrade Gurobi to 9.5
FYI see #12419 for the most recent update (which was to 9.0.2).

@hongkai-dai Do you have any vote for whether and/or when Drake should switch to using Gurobi 9.5?

### PR DESCRIPTION
**Pull request by RussTedrake**
Closes #16604.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
+@hongkai-dai for feature review, please
+@jwnimmer-tri for platform review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716#-:-MxP1Xxh7NBvkaOlQ6K6:b-3ggkht)* status: LGTM missing from assignees hongkai-dai,jwnimmer-tri(platform), missing label for release notes (waiting on @hongkai-dai and @jwnimmer-tri)

**Comment by RussTedrake** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by RussTedrake** [comment]
@hongkai-dai and @jwnimmer-tri -- please let me know if you're happy with this change happening.  if yes, then I will ask @BetsyMcPhail to help get gurobi951 installed on the CI servers.

**Review by hongkai-dai — COMMENTED** [review]
We will also need to update some documentations, for example in https://github.com/RobotLocomotion/drake/blob/3bb4ed2a727e3d1d80c90fe8e311f449ab68f958/solvers/gurobi_solver.h#L28 where it currently points to gurobi 9.0.

Would you like me to send a commit to this PR to modify the documentation?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716#-:-MxQ0KJWE8Kj67cGTCZf:b8y4yl2)* status: LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> ... please let me know if you're happy with this change happening.

If @hongkai-dai is happy, then I'm happy.

Any upgrades to Drake's pinned version of Gurobi also require a matching Anzu PR to move in lockstep.  This also means uploading the newer Gurobi binaries to TRI's source control.  I don't recall if it also means a TRI license upgrade or license server upgrade, or if the same licensing works for any version.

**Review by hongkai-dai — COMMENTED** [review]
> please let me know if you're happy with this change happening.

Yes I think it is great to upgrade to gurobi 9.5.1. Recently the TRI IT department upgrades TRI's gurobi license server so we should support gurobi 9.5.1 at TRI.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716#-:-MxQAh1r2qE2igMJkIXb:bg64ti8)* status: LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai, missing label for release notes (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I've updated the PR overview to mark it as closing #16604.

**Review by RussTedrake — COMMENTED** [review]
@hongkai-dai -- I've updated the documentation links.  (I looked through #16604 and believe I've caught everything).
+@betsymcphail -- can you please upgrade the CI infrastructure (mac and linux) to gurobi 9.5.1?  (even the unprovisioned machines will need the update, i think).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716#-:-MxQhYdF5E9fHGefkyoQ:b-xtr5b0)* status: LGTM missing from assignees jwnimmer-tri(platform),hongkai-dai,BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail, @hongkai-dai, and @jwnimmer-tri)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716#-:-MxYO7zo1LbbnYCPNCX9:bg7igkv)* status: LGTM missing from assignees jwnimmer-tri(platform),BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail and @jwnimmer-tri)

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716)* status: 1 unresolved discussion, LGTM missing from assignees jwnimmer-tri(platform),BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[tools/workspace/gurobi/repository.bzl, line 16 at r2](https://reviewable.io/reviews/robotlocomotion/drake/16716#-Mx_00n8C1CZxTFYM0Ot:-MxbQVCRAKohq5ySnM5A:bgn7wzx) ([raw file](https://github.com/robotlocomotion/drake/blob/3bb4ed2a727e3d1d80c90fe8e311f449ab68f958/tools/workspace/gurobi/repository.bzl#L16)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The intent of this comment was "We do not obey the GUROBI_HOME environment variable on macOS." in contrast to Ubuntu where we do.  Some comment along those lines should remain here.
</blockquote></details>

Done.  That removal was unintentional.



_Code quote:_
```Starlark
        # Gurobi must be installed into its standard location.
```

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/16716)* status: LGTM missing from assignees jwnimmer-tri(platform),BetsyMcPhail, missing label for release notes (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
> @BetsyMcPhail also note for image updates -- PR https://github.com/RobotLocomotion/drake/pull/16701 has some package removals for the images (yaml-cpp) that you could do at the same time: ...

Nevermind, that PR is in the process of a revert: #16728.  Updating CI for Gurobi (only) is sufficient for now.

**Comment by RussTedrake** [comment]
@drake-jenkins-bot retest this please
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot mac-big-sur-unprovisioned-clang-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-unprovisioned-gcc-bazel-experimental-release please
@drake-jenkins-bot linux-focal-unprovisioned-gcc-bazel-experimental-release please

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.

**Comment by BetsyMcPhail** [comment]
@drake-jenkins-bot linux-bionic-gcc-bazel-experimental-everything-release please.
@drake-jenkins-bot linux-bionic-clang-bazel-experimental-everything-release please.

**Comment by jwnimmer-tri** [comment]
> Any upgrades to Drake's pinned version of Gurobi also require a matching Anzu PR to move in lockstep.

Oops.  For the record, I was wrong about this.  Anzu uses completely its own repository rule for Gurobi, so it does not need to sync with the `repository.bzl` changes in Drake PRs for Gurobi.

The only thing that needs to coordinate between Drake and Anzu is any implementation changes to `gurobi_solver.cc` in terms of its calls into `gurobi_c.h`.

**Pull request merged**
