### PR TITLE
Rephrased "allied apps" since it may be confusing to certain readers.

### PR DESCRIPTION
**Pull request by liangfok**
# Motivation

"Allied Apps" is not an industry standard term and thus may be confusing to certain readers.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/3590)

### CODE REVIEW

**Comment by liangfok** [comment]
+@rpoyner-tri for feature review please.
+@sherm1 for platform review please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3590#-:-KSbkqztr0kAAN9EzyTC:b2u752p)*

**Comment by rpoyner-tri** [comment]
Confusion is not for me to judge; I was not confused when I wrote it :)
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3590#-:-KSblwoC004_XHDms8kH:bh4omie)*

**Comment by liangfok** [comment]
Yes, I believe this is fundamentally why a "fresh pair of eyes" is sometimes necessary. I also believe this is why user studies are so useful; developers have no idea how someone else will end up understanding and using something.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3590#-:-KSbm8TEgNqvFE-lZJDC:bb9d7l4)*

**Comment by liangfok** [comment]
Odd CI failure tracked by #3592.

@drake-jenkins-bot retest this please.

**Comment by sherm1** [comment]
Platform review: I think it was fine before and it's fine now too! :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3590#-:-KSc4IBCtJKTYcuj1_BP:b-ek58el)*

**Comment by liangfok** [comment]
Thanks. Merging now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/3590#-:-KSfROIBKU9AC1yaMyjH:b4joi5f)*

**Pull request merged**
