### PR TITLE
add finiteness check to linear constraints

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for feature review? Or +@cohnt?

+(release notes: fix) 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-:-NrbGb2X1Ae3-V__zdMm:bpxeq5k)* status: LGTM missing from assignees hongkai-dai,cohnt, needs platform reviewer assigned

**Review by cohnt — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-:-NrbHx9wBeMxSiUkWa6p:bnfp4nl)* status: LGTM missing from assignee hongkai-dai, needs platform reviewer assigned

**Review by sherm1 — COMMENTED** [review]
Platform pass done. A few minor changes needed, PTAL.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-:-NrcC47F5onG161UjaqV:b-31rihg)* status: 9 unresolved discussions, LGTM missing from assignee sherm1(platform)

___
*[`solvers/constraint.h` line 607 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc7bnPEBGzymcDM3KT:-Nrc7bnPEBGzymcDM3KU:bwkx7s0) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L607)):*
minor: unfortunately, "finite" in the C++ vernacular is not the opposite of "infinite". Instead it means "not +/- infinity or NaN". So you should word this something like
> Throws if A has any entry which is non-finite.

(Same below)
___
*[`solvers/constraint.h` line 645 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc8a5k2S_tjfHIqKPM:-Nrc8a5k2S_tjfHIqKPN:b-lhdevy) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L645)):*
> ```objc
>    *
>    * Throws if new_A has any entry which is infinite or if new_A, new_lb, and
>    * new_ub don't all have the same rows.
> ```

nit: "same rows" -> "same number of rows"

(Also below)
___
*[`solvers/constraint.h` line 722 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc8wZ30YmINoQzx_wB:-Nrc8wZ30YmINoQzx_wC:b-vvkgqn) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L722)):*
> ```objc
>    * Constructs the linear equality constraint Aeq * x = beq.
>    *
>    * Throws is any entry in Aeq or beq is not finite
> ```

BTW yes, like that! (but with ending punctuation)
___
*[`solvers/constraint.h` line 748 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc95878armxt2Af2cr:-Nrc95878armxt2Af2cs:bmfjnu3) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L748)):*
> ```objc
>                            double beq)
>       : LinearEqualityConstraint(a, Vector1d(beq)) {
>     DRAKE_THROW_UNLESS(abs(beq) < std::numeric_limits<double>::infinity());
> ```

minor: assuming you want this scalar test to match the `allFinite()` vector cases,
use instead:
`DRAKE_THROW_UNLESS(std::isfinite(beq))`

(You could also call Eigen's allFinite() on the Vector1d if you have access to it)
___
*[`solvers/constraint.h` line 753 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc9lzjE_b1t3i9KaS3:-Nrc9lzjE_b1t3i9KaS4:b-owwsni) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L753)):*
> ```objc
>   /*
>    * @brief change the parameters of the constraint (A and b), but not the
>    *variable associations.
> ```

nit: missing space
___
*[`solvers/constraint.h` line 757 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-Nrc9pP8DG5MqkR2RrJF:-Nrc9pP8DG5MqkR2RrJG:b-owwsni) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L757)):*
> ```objc
>    * note that A and b can change size in the rows only (representing a
>    * different number of linear constraints, but on the same decision
>    *variables).
> ```

nit: missing space
___
*[`solvers/constraint.h` line 770 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-NrcApA8-NcuP0UwMiD0:-NrcApA8-NcuP0UwMiD1:b-vcc6ez) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/constraint.h#L770)):*
> ```objc
>    * Overloads UpdateCoefficients but with a sparse A matrix.
>    *
>    * Throws if any entry of beq or Aeq is infinite
> ```

nit: these sentences should all end in "."
___
*[`solvers/test/constraint_test.cc` line 147 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-NrcBVLT2vzNtJdbF38f:-NrcBVLT2vzNtJdbF38g:b-tvatrd) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/test/constraint_test.cc#L147)):*
> ```cpp
>   Eigen::Vector3d bound_bad(0, 1, kInf);
>   EXPECT_THROW(LinearEqualityConstraint(A_sparse_bad, bound),
>                std::invalid_argument);
> ```

nit: per Drake's [style guide](https://drake.mit.edu/styleguide/cppguide.html#Exceptions) you should only test for the more-generic `std::exception` base type here (and below). 
___
*[`solvers/test/constraint_test.cc` line 214 at r1](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-NrcByQZBolZfAZmIIGZ:-NrcByQZBolZfAZmIIG_:b-b1ml1k) ([raw file](https://github.com/RobotLocomotion/drake/blob/f633185830745d16577eacd0e99b4878cb76b72d/solvers/test/constraint_test.cc#L214)):*
> ```cpp
>   EXPECT_EQ(constraint.num_constraints(), 2);
> 
>   EXPECT_THROW(constraint.UpdateCoefficients(A_bad, b), std::runtime_error);
> ```

nit: std::exception rather than runtime_error

**Review by AlexandreAmice — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-:-Nri2ijvEz-G42m9-GzC:b-9755fn)* status: LGTM missing from assignee sherm1(platform), commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Review by sherm1 — COMMENTED** [review]
Thanks, Alexandre! Platform :lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/21049#-:-Nrkn2LP3veAFN0Cvq3n:b-ifzrow)* status: commits need curation (https://drake.mit.edu/reviewable.html#curated-commits) (waiting on @AlexandreAmice)

**Pull request merged**
